### PR TITLE
[compat] Remove "Standard Proposition Elimination"

### PR DESCRIPTION
**Pull request by ejgallego**
Following up on #6791, we remove the option "Standard Proposition Elimination"

### CODE REVIEW

**Comment by Zimmi48** [comment]
Note #6822 which refrained me from removing the dead code and stopped me altogether to remove compatibility options I was not specially interested in.

**Comment by gares** [comment]
> Note #6822 which refrained me from removing the dead code

I'm afraid that the argument by @herbelin to keep the code is very dangerous and should not be followed.
My understand of it is the following:
1. There is code that implements a deprecated feature (its semantics is not good enough)
2. Nobody uses it, so removing the syntax is painless
3. The code is a good starting point, even if I've no time now to improve it, if it stays there it won't bitrot (eg ported to new API)
4. hence (and here is the danger) we don't remove the syntax of the feature

My opinion:
a) If the syntax is not removed, then people may use it (even if it generates a deprecation warning), and hance making the removal impossible. The syntax should be removed *now* since we can.
b) I'm sympathetic about  bitrot argument *if* it comes together with a timeline (like I'll fix that for 8.9, or it can be removed).

This PR implements two things: i) syntax removal ii) dead code elimination.

IMHO #6822 does not imply a "needs: discussion" on i), on the contrary.
A discussion with @herbelin can take place about ii).
Hence we should remove the option syntax *now* and leave ii) for discussion

**Review by gares — CHANGES_REQUESTED** [review]
split this in i) + ii) in order to avoid the "avoid discussion" label.

**Comment by herbelin** [comment]
> Nobody uses it, so removing the syntax is painless

For the anecdote, there are 218 occurrences of `Unset Standard Proposition Elimination` in the coq contributions... but the effect is void since it is deactivated by default.

Applying both i) and ii) are ok to me at the current time.

**Comment by gares** [comment]
Great!

**Review by gares — APPROVED** [review]

**Comment by maximedenes** [comment]
I'm looking at the conflicts to see if a rebase is really needed.

**Comment by maximedenes** [comment]
Ok, it's not a real conflict, so I'll take care of it in the merge commit and will run a CI build on the result.

**Pull request merged**
