### PR TITLE
Do not rely on the Stream API to parse Coq project files.

### PR DESCRIPTION
**Pull request by ppedrot**
I wonder why this was done this way.

> inb4 "But streams are buffered111!!!"

- So are channels in OCaml.
- Even if not the case, I highly doubt that coqproject parsing is part of any hotspot.

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Review by Alizter — APPROVED** [review]

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Maybe we backport this for 4.14 support?

**Comment by Alizter** [comment]
FTR release packages of older versions will all work since the camlp-streams alert is only a warning. The alert only affects us in dev mode so I think fixing in master is enough.

**Comment by ppedrot** [comment]
Not a CI maintainer but it has been around for a few days in and out.

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
