### PR TITLE
Fix #9180 by reverting #9249 and #8187

### LINKED ISSUE #9180: Coq does not keep some notations
#### Version

8.10+alpha (cb287591722e4d44671eb8c90138cf063ac5b707)

#### Operating system

- macOS 10.14
- Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 

#### Description of the problem

Here is some code from Mathcomp's `ssrnat`, illustrating the issue.
```coq
Notation succn := (Datatypes.S).

Notation "n .+1" := (succn n) (at level 2, left associativity,
  format "n .+1") : nat_scope.

Locate ".+1".
(* Notation *)
(* "n .+1" := S n : nat_scope (default interpretation) *)
(** so Coq does not apply succn notation *)

Goal forall x : nat, x.+1 = x.+1.
(* forall x : nat, succn x = succn x *)
(** here Coq should keep ".+1" notations *)
```

Reported by @mr-ohman.

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #9180

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
I'm afraid this is the only solution for now.

**Comment by Zimmi48** [comment]
I am not able to judge, but note that if it is believed that the problem in #9180 is fixable without redesigning the feature, then it would make sense to revert in v8.10 only...

**Comment by Zimmi48** [comment]
BTW, it is quite puzzling to me that this large change did not have any entry in CHANGES.

**Comment by vbgl** [comment]
The CHANGES entry has been moved to the manual (section Version 8.9).

**Comment by Zimmi48** [comment]
OK so yet another case of a misplaced CHANGES entry that will be solved by #9964. I'll update #9939 to remove it.

**Comment by vbgl** [comment]
Who shall assign to this PR? It seems ready to go.

**Comment by Zimmi48** [comment]
@vbgl: From @herbelin's comment at https://github.com/coq/coq/issues/9180#issuecomment-487382878:

>In any case, a revert is the reasonable thing to do for 8.10, especially from the moment @vgbl succeeded in preparing a PR.

I didn't get what is Hugo's position wrt reverting in `v8.10` only or in `v8.10` + `master`. In any case, a solution could be to backport this PR to `v8.10` now (and then you don't need anyone else's approval to merge it) and to leave a few more days / weeks to take a decision on the revert in `master`.

**Comment by ejgallego** [comment]
The revert should happen in master too, IIUC.

**Comment by ejgallego** [comment]
> The revert should happen in master too, IIUC.

However indeed maybe it is a better strategy to leave #9180 open; so I suggest you follow @Zimmi48 's suggestion and apply in 8.10 -only for now until @herbelin / @ggonthier can provide more feedback on how they would like to proceed.

**Comment by vbgl** [comment]
Well. I’ve opened this PR against the `master` for a reason.

I think there is no point in keeping master broken until there is a plan: let’s have a working master until there is a plan.

**Comment by ejgallego** [comment]
> I think there is no point in keeping master broken until there is a plan: let’s have a working master until there is a plan.

Then, if we are going to close #9180 we need to improve the test suite so we don't reopen it in master by accident.

**Comment by herbelin** [comment]
Note that, strictly speaking, regression #9180 on top of #8187 was already fixed in #9207 but the latter was not merged. What is not fixed by #9207 of the #8187 regressions are the "`%MS`" and the swap of priority wrt specialized notations and abbreviations. These are not reported in #9180 but in the body of the discussion for #9207.

So, probably, the good thing to do is to:
- close #9180, close #9207 
- add a regression test for #9180 *and* for the "`%MS`" and swap of priority wrt specialized notations and abbreviations given in the discussion of #9207 (ideally, someone should also explore #9258)
- open a new PR with #8187 + #9207, to which a fix to the `%MS`" and swap of priorities issues will eventually be integrated when the discussion converges (I'm confident that a fix could be done relatively easily, on which I'd like to get a collective support though)

Incidentally, the discussions at #9180 and #9207 gave rise to side (independent) PRs #9292, #9297, and #9311. The first two ones have been merged. The third one is still under discussion.

**Comment by vbgl** [comment]
Test-case added.

**Comment by maximedenes** [comment]
@ejgallego CI green, can you merge so that we can backport? Thanks!

**Comment by ejgallego** [comment]
@herbelin are you OK with transforming your comment into an issue with the remaining TODO and merging this?

**Comment by ejgallego** [comment]
I have opened https://github.com/coq/coq/issues/10023 , will merge later today as to leave some window for further comment, but still ensuring this PR is ready for tomorrow.

**Comment by herbelin** [comment]
> @herbelin are you OK with transforming your comment into an issue with the remaining TODO and merging this?

Yes, very good. Then, I'll open a new PR after the revert is done.

**Comment by ejgallego** [comment]
Thanks for the very detailed feedback and status report.

**Pull request merged**
