### PR TITLE
fix: ssrmatching and primitive projections

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Is there a test for this?
Also typo in commit message (strucut).

**Comment by robbertkrebbers** [comment]
See https://github.com/coq/coq/pull/984#issuecomment-325129049 for a test.

**Comment by gares** [comment]
> Also typo in commit message (strucut).

This is my signature ;-)

**Comment by gares** [comment]
After discussing with @maximedenes I've broken the dependency on #984, now it only depends on master

**Comment by Zimmi48** [comment]
Closing / reopening, because this did not get a link to a Travis test.

**Comment by gares** [comment]
I'm afraid I can't make a test that works without part of PMP's patch.
The point is that once ssrmatching identifies the term to be replaced, unification (evarconv) is used to "confirm" the term really matches.  I guess the unification problem in question involves both primitive projections and canonical structures...

I'm trying to build it locally to be 100% sure, but I'm afraid that's the unfortunate situation.

**Comment by gares** [comment]
No, it works (I've just pushed a little fix the test).

**Comment by Zimmi48** [comment]
There's something going on. It still didn't get a link to a Travis job...

**Comment by gares** [comment]
On my personal github space it runs now, and it fails on formal topology and iris.
Are these failures expected? (iris uses ssr, no clue about topology)

**Comment by SkySkimmer** [comment]
Topology is normal and my fault (assuming the error is about universe instance sizes), I made a non backward compatible overlay for #1033 and it got merged (bmsherman/topology#14). A backward compatible version is waiting at bmsherman/topology#15.

**Comment by robbertkrebbers** [comment]
Iris does not seem to build at all, this is probably because @RalfJung changes the build system.

**Comment by RalfJung** [comment]
Got a build log?

**Comment by RalfJung** [comment]
But this sounds plausible; I now remember that the Coq CI does not use `make build-dep` but directly uses the opam.pins file, which is a hack that we finally got rid of. I can reinstate the file temporarily if that helps.

**Comment by robbertkrebbers** [comment]
https://travis-ci.org/gares/coq/jobs/277670213

**Comment by RalfJung** [comment]
Yeah, that's the one. I added opam.pins back, so if you re-run the CI that one should work again.

However, we no longer use that file and would prefer to get rid of it. Any chance Coq's CI could use opam to resolve dependencies?

---

What happened is that we finally properly use opam to express the dependency of Iris on std++. We have our own opam repo at <https://gitlab.mpi-sws.org/FP/opam-dev> where we automatically publish a new dev version of Iris and std++ every time something gets pushed to either repo (and passes CI). My hope was that by getting rid of opam.pins, it is much easier for people to use or depend on Iris and automatically get the right std++.

**Comment by SkySkimmer** [comment]
Is there some reason not to use std++ master?

**Comment by robbertkrebbers** [comment]
> Is there some reason not to use std++ master?

Yes, Iris may not have been updated to work with std++ master yet.

**Comment by RalfJung** [comment]
@SkySkimmer Yes, master may not always work. It's really hard in Coq to only make backwards-compatible changes, so we don't claim that we do and instead record exact dependencies.

Here's a super-hacky way to get the right commit ID without using opam:
```
curl "https://gitlab.mpi-sws.org/FP/opam-dev/raw/master/packages/coq-stdpp/coq-stdpp.$(cat opam | fgrep stdpp | egrep 'dev.([0-9.-]+)' -o)/url" | sed 's/^.*#\(.*\)"$/\1/'
```

**Comment by Zimmi48** [comment]
@RalfJung Thanks for temporarily reverting the `opam.pins` removal. May we ask you to provide a branch of coq-stdpp that would correspond to the version Iris builds with? That would be the simplest way for us to solve this issue. Right now, we cannot use opam for dependencies.

**Comment by RalfJung** [comment]
@Zimmi48 That would mean duplicate bookkeeping for us, so it is not better (worse, really) than continuing to maintain opam.pins. We don't want to use a branch for our purposes as we consider it important to be able to build historic versions of Iris, while a branch in std++ can only tell you which version the latest Iris needs.

Considering that opam is always recommended as the package manager to be used for Coq, are there plans to also use opam for installing CI artifacts?

**Comment by Zimmi48** [comment]
> That would mean duplicate bookkeeping for us, so it is not better (worse, really) than continuing to maintain opam.pins.

I was hoping that maybe you would be able to automate this.

> Considering that opam is always recommended as the package manager to be used for Coq, are there plans to also use opam for installing CI artifacts?

I think @ejgallego had plans to support this at some point but I don't know if he's still considering it.
I personally have no plan of the sort because I'm not a big fan nor user of opam myself.
But of course, our CI system, as the rest of Coq, is open to contributions from anyone...

**Comment by ejgallego** [comment]
I am not a fan of OPAM either, but it is fine for us if you want to maintain dependencies this way, we will figure out how to extract that info for use.

**Comment by RalfJung** [comment]
Okay, now that is surprising. But is there even any alternative to opam?

I will try and see if I can coerce opam into working in Coq's CI.^^

**Comment by Zimmi48** [comment]
> But is there even any alternative to opam?

Longer term I personally intend to promote Nix as an alternative to opam but this will require me to write a whole bunch of documentation at the very least so don't expect this soon.

**Comment by ejgallego** [comment]
> Okay, now that is surprising.

I think OPAM was not designed for some of the uses cases we'd like to have in the future; I think that is fair, OPAM is a distribution system, vs our desire for a package testing system.

**Pull request merged**
