### PR TITLE
Derive JMeq_eq from eq_rect_eq

### PR DESCRIPTION
**Pull request by gjurgensen**
This small change to the standard library would derive `JMeq_eq` from `eq_rect_eq`, rather than axiomatizing both independently. As described in [this issue](https://github.com/coq/coq/issues/14970), the two axioms are equivalent, and so it is redundant to introduce both axiomatically.

### CODE REVIEW

**Comment by Alizter** [comment]
@Zimmi48 Why is the linter unhappy with this?

**Comment by Zimmi48** [comment]
There's a trailing whitespace after the `Proof` keyword. It's unfortunate that's the extract from the trace in the GitHub Checks doesn't show this. Maybe we should improve the linter output.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Can you squash those commits however?

**Comment by gjurgensen** [comment]
> Can you squash those commits however?

No problem, they are squashed together now. It looks like the linter is happy now too.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
