### PR TITLE
Add /dev/bench to CODEOWNERS

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
The bench-maintainers team is not yet created (I don't know where the team creation buttons are).

**Comment by Zimmi48** [comment]
> The bench-maintainers team is not yet created (I don't know where the team creation buttons are).

See button "Add a team" here: https://github.com/orgs/coq/teams/pushers/teams

**Review by Zimmi48 — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Created https://github.com/orgs/coq/teams/bench-maintainers
Add yourself if you're willing @ppedrot @ejgallego @maximedenes etc

**Comment by Zimmi48** [comment]
I'm happy to merge this now if you wish but I suppose it would make more sense with at least one more member in this team.

**Comment by Zimmi48** [comment]
BTW, is the bench infrastructure in this folder superseding the one in https://github.com/coq/coq-bench/?

**Comment by Zimmi48** [comment]
@coqbot: merge now

**Pull request merged**
