### PR TITLE
cleanup: Lib.freeze doesn't use its [~marshallable] argument

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, @maximedenes , @gares ?

**Comment by maximedenes** [comment]
@SkySkimmer this argument was used at some point, wasn't it?

**Comment by maximedenes** [comment]
Taking this as a `library` maintainer.

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
>@SkySkimmer this argument was used at some point, wasn't it?

Yes, until e20a12d92c7cc7c40ee0ac0b6569b0ee5e0e0b0f

**Comment by gares** [comment]
I think it was used before ephemerons were introduced. Back then I had to purge thunks by hand here and there, with ephemerons it is the marshaller that does not find them no more.

**Comment by maximedenes** [comment]
> Yes, until [e20a12d](https://github.com/coq/coq/commit/e20a12d92c7cc7c40ee0ac0b6569b0ee5e0e0b0f)

Oh, right, probably I forgot to push the second part of this cleanup. Thanks!

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
