### PR TITLE
coq_makefile2 : improve backward compatibility w.r.t. inclusion of generated makefile

### PR DESCRIPTION
**Pull request by gares**
We improve the backward compatibility of the generated Makefile as per 
  https://github.com/UniMath/UniMath/pull/715

support for subdirectories is now as shaky as in coq_makefile 1, i.e. it only works with -j1 (otherwise you have no clue when they are processed). Still, there is no recursive call to the makefile, and this results in better backward compatibility.

### CODE REVIEW

**Comment by gares** [comment]
This should be merged in 8.7 before the release _or_ completely dropped, since in 8.8 we are going to break backward compatibility for project including the generated makefile

**Comment by maximedenes** [comment]
Aren't we just delaying the problem to the next release, without more warnings? If we want to break compatibility, either warn now and break later, or break now, don't you think?

**Comment by gares** [comment]
Hum, dunno... the thing I remove (pre/post all hooks) can be very easily implemented if you call the generated makefile, rather than include it.  So, in the approach I propose the code I remove serves no purpose. Still its implementation breaks compatibility with some projects. This is the conclusion on the PR I link.

BTW, the `$(warning ...)` has nothing to do with that, but had to go, since it again breaks backward compatibility.

I don't know if there is a way to detect that a makefile is being included and warn.
I think that I should first improve the doc (I've already added some words about including the Makefile, but I shall add more) and then be *no mercy* in the next release. One of the problems of coq_makefile1 is that is was essentially not documented and there was no hint about how to extend it, or what was its interface. And I'm afraid the random Coq user is not very experienced in build systems either, so I'd stay safe this time and just say *sorry I told you* the next time.

**Comment by maximedenes** [comment]
It seems the test suite failed on OSX. Not sure if it is a spurious failure or not.

**Pull request closed without merging**
