### PR TITLE
Check instance length in type_of_{inductive,constructor}

### PR DESCRIPTION
**Pull request by SkySkimmer**
I think this breaks some code, let's see CI.

### CODE REVIEW

**Comment by ppedrot** [comment]
Once again this begs the question of the contract enforced by kernel callers. I think that in this particular case, it should raise an exception rather than an anomaly.

**Comment by SkySkimmer** [comment]
>Once again this begs the question of the contract enforced by kernel callers. I think that in this particular case, it should raise an exception rather than an anomaly.

Why? It seems clearly an anomaly to me.

**Comment by ppedrot** [comment]
@SkySkimmer If you manage to define precisely what an anomaly is, I agree with you. But where do you draw the line between a typing error and an anomaly when we can send arbitrary stuff to the kernel?

**Comment by SkySkimmer** [comment]
>@SkySkimmer If you manage to define precisely what an anomaly is, I agree with you. But where do you draw the line between a typing error and an anomaly when we can send arbitrary stuff to the kernel?

Basically I don't see why you would ever want to catch this, if you're aware that your instance may be the wrong length it's saner to just check the length before sending to the kernel.

**Comment by ppedrot** [comment]
Problem is that we don't have any sanitize function in the code base. But I agree on principle, so I am not opposing this PR in its current form.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
