### PR TITLE
Fix `Typeclasses Unique Instances` option.

### LINKED ISSUE #6714: `Set Typeclasses Unique Instances` does not seem to be working
#### Version

8.7.1

#### Operating system

Linux

#### Description of the problem

According to the manual, `Set Typeclasses Unique Instances` makes sure that "when a solution to the typeclass goal of this class is found, we never backtrack on it, assuming that it is canonical". As the example below shows, I do not think it's actually doing that.

```
Set Typeclasses Unique Instances.

Class Foo (x y : bool) := {}.
Class Bar (x y : bool) := {}.
Class Bax (x : bool) := {}.

Instance bar_1 : Bar true false.
Instance bar_2 : Bar true true.

Instance bax_1 : Bax false.

Instance foo x y : Bar x y -> Bax y -> Foo x y.

Typeclasses eauto := debug.

Check (_ : Foo true _).
```

According to the type class debug output, this will:

1. First use the instance `foo`, which gives rise to goals `Bar true ?x` and `Bax ?x`
2. Solve `Bar true ?x` using `bar_2`, thus unifying `?x` with `false`.
3. Try to solve `Bax false`
4. Since that fails, it backtracks to (2) by solving `Bar true ?x` again using another instance.

When `Set Typeclasses Unique Instances` is enabled, it should not backtrack.

### PR DESCRIPTION
**Pull request by Janno**
Outdated description: ~~Unlike `Unique Instances`, `Really Unique Instances` does not allow  backtracking even in the presence of shared evars.~~

Fixes / closes #6714

- [x] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by Janno** [comment]
It might not be entirely accurate to say `Fixes / closes https://github.com/coq/coq/issues/6714`. The discussion there has become relatively detailed and identifies several cases. I need to figure out which ones of those could be addressed with this simple fix.

**Comment by gares** [comment]
Could you try to make this new behavior the one for the old option? If CI does not complain too much I'd rather replace the old option.

Also, two booleans have 4 states, if we keep the two options I think we should craft a 3 way ADT, since one combination does not make much sense to me.

**Comment by Janno** [comment]
> Could you try to make this new behavior the one for the old option? If CI does not complain too much I'd rather replace the old option.

Good idea. I temporarily reverted my change and pushed your suggestion instead.

While working on that I realized that the `unique` argument to `needs_backtrack` is not just `Typeclasses Unique Instances` but also some option of the search itself. I don't understand the code but whatever solution we end up with needs to be careful to interact with that option correctly. For now I refactored it into a separate argument to `needs_backtrack`.

**Comment by Janno** [comment]
I suspect the geocoq failure is unrelated? I cannot find any indication that it would be due to the change at hand.

**Comment by Janno** [comment]
I don't think there is a single user of `Set Typeclasses Unique Instances` out there so the absence of breakage is not surprising. Also, the new behavior matches the existing documentation. Can this just go in as it is?

**Comment by Janno** [comment]
I updated the comment and turned the two booleans into named arguments to avoid mistakes.

**Comment by Janno** [comment]
@gares is there any chance this could go into 8.18? Given the absence of users I suspect it to be uniquely uncontroversial :)

**Comment by Janno** [comment]
I removed the initial commit and its reversal.

**Comment by Zimmi48** [comment]
@gares ping

**Review by ppedrot — APPROVED** [review]
Looks sensible to me.

**Comment by ppedrot** [comment]
@gares if you're not merging soon I'll take the assignment over. I don't think we gain much by delaying this PR.

**Comment by gares** [comment]
@coqbot merge now

Sorry for the delay, I was on vac

**Comment by Zimmi48** [comment]
Wouldn't this (important) bug fix deserve to be highlighted in a changelog entry? At least @robbertkrebbers would be interested to know that this was fixed, but I guess he already knows since the issue that this closed was opened by him...

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18012

**Comment by robbertkrebbers** [comment]
Thanks for the ping. Indeed, mentioning this in the CHANGELOG would be nice.

I still have to experiment if this indeed allows me to replace uses of the `TCNoBackTrack` hack in Iris. On the other hand, after recent discussions with @gares and @FissoreD it seems that Prolog style "cuts" are really the thing you want instead of ad-hoc mechanisms to control backtracking.

**Pull request merged**
