### PR TITLE
Make ssr datastructures cpattern and rpattern public

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
It would be nice if `Ssrmatching.cpattern` and `Ssrmatching.rpattern` could be public. I need to access them in my plugin in order to modify generic witnesses that are part of ltac expressions.

Is there a particular reason why these are abstract? It seems they are the only datatypes that are abstract in the ssreflect plugin.

**Kind:** feature.

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by gares** [comment]
I'm OK with that as long as you write a comment on what the components are.

I have not touched that code in years, so I may recall things wrongly, but I think the `char` is an horrible encoding of "was the pattern `@foo` or `(pat)` or ...". Then there is a term and its interpretation environment.

**Comment by ppedrot** [comment]
I think that you should at least wrap it into a record, an even a private one. It's already a mess to track the invariants in ssr...

**Comment by gares** [comment]
> even a private one

He want to patch that data, it can't be private. Nothing against the record part.

**Comment by ppedrot** [comment]
Right, but then depending on the kind of change to apply, maybe a generic function could be even cleaner? E.g. if it's term substitution, just provide a map function.

**Comment by LasseBlaauwbroek** [comment]
That is exactly what I'm doing, but in my plugin. I have a huge file that performs a monadic map over the entire ltac datastructure...

**Comment by LasseBlaauwbroek** [comment]
I should indeed apply the Boy Scout Rule better here. I've now added two commits that (1) refactors `ssrtermkind` into an algebraic structure and (2) refactors `cpattern` into a record. The record is still fully public; using a generic function like @ppedrot suggests would be difficult because it would mean importing all the monadic machinery of my plugin into ssreflect.

**Comment by gares** [comment]
Thanks, the changes look great!

I think you can still have a function `val map_cpattern : (ssrterm -> ssrterm) -> cpattern -> cpattern` and inject it into a monadic type into you code, no?

**Comment by ppedrot** [comment]
@gares for this you need a fold, not a map.

**Comment by LasseBlaauwbroek** [comment]
I don't think that signature would be enough for me. I'd need something like `val map_cpattern : (ssrterm -> ssrterm Monad.t) -> cpattern -> cpattern Monad.t`. But even that would probably not be enough, because, at some point, I'll probably also have to do transformations on the interpretation context of `cpattern`.

But, before we start coming up with all kinds of crazy combinators to solve this problem, why don't we just simplify? I'm assuming you guys are raising this issue because you want to maintain certain invariants on `cpattern`? Why don't we just make `cpattern` private and provide an accessor `cpattern -> public_cpattern` and an injector `public_cpattern -> cpattern` that maintains these invariants? (Note that there was already a `mk_term` function, but that does not maintain any invariants).

**Comment by gares** [comment]
I'm ok with the type being public

**Review by gares — APPROVED** [review]
It's ok, but you actually fixed the FIXME in the comment of the first hunk, so you should remove it as well.

**Comment by LasseBlaauwbroek** [comment]
I changed the comments there a little bit. But some of it seems just documentation to me, and this is still a FIXME I think:
```
Cpattern is a temporary flag that becomes InParens ASAP.
```
(I'm not sure why `Cpattern` exists so I'm too afraid to do the refactoring that removes it).

**Comment by LasseBlaauwbroek** [comment]
Does this PR need a changelog btw?

**Comment by gares** [comment]
I'd say no, I'll merge once CI is over

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
