### PR TITLE
[stdlib] [List] add results around incl, filter and nth

### PR DESCRIPTION
**Pull request by olaure01**
Add some natural lemmas and make a  strengthening for an existing lemma.

**Kind:** feature.

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by nojb** [comment]
Hi, I have a general question only tangentially related to the present PR: I was wondering if there was a specific reason why `incl` is given only in the executable form and not also in the relational form (`Incl`?). I could propose a PR to add this if there is interest. Personally I find the relational form easier to reason about. Thanks!

**Comment by olaure01** [comment]
@nojb 
> not also in the relational form (`Incl`?)

I am not sure I see what you mean by "relational form"?

**Comment by nojb** [comment]
> @nojb
> 
> > not also in the relational form (`Incl`?)
> 
> I am not sure I see what you mean by "relational form"?

Yes, sorry, I was unclear. Something like:
```
Definition Incl (A : Type) : list A -> list A -> Prop :=
| Incl_nil: forall l, Incl nil l
| Incl_cons: forall x l, In x l' -> Incl l l' -> Incl (x :: l) l'.
```
or maybe even
```
Definition Incl (A : Type) (l l' : list A) := Forall (fun x => In x l') l.
```

**Comment by olaure01** [comment]
@nojb OK thanks
I would say it is probably an historical design choice.
I see no particular reason not to add `Incl`. In practice `incl` has been OK for me so far, but it is not an argument.
`Incl_cons` is present as lemma `in_cons` for a long time. I have added `Incl_nil` as `incl_nil_l` more recently.
I will add here an equivalence lemma:
```coq
incl l l' <-> Forall (fun x => In x l') l
```
so that it can give the alternative induction principle.
This being said, feel free to make a more developed PR.

**Comment by nojb** [comment]
> @nojb OK thanks
> I would say it is probably an historical design choice.
> I see no particular reason not to add `Incl`.

OK, thanks for the reply. I will give it a shot. Cheers!

**Review by herbelin — APPROVED** [review]
Relevant and useful as far as I can see. If nobody else wants to comment I may merge on Friday.

**Comment by herbelin** [comment]
@nojb:
> I see no particular reason not to add Incl

Same for me!

**Review by anton-trunov — APPROVED** [review]
LGTM!

**Comment by Zimmi48** [comment]
@olaure01 Wouldn't it make sense to merge this changelog entry with the one for #11249, which was already on lists?

**Comment by olaure01** [comment]
@Zimmi48 Sure, I'll do that. New PR, right?

**Comment by Zimmi48** [comment]
Right!

**Pull request merged**
