### PR TITLE
Include env and evar map in ltac backtrace constr for correct printing

### LINKED ISSUE #17449: `Set Ltac Backtrace` throws `Not_found` exception in 8.17.0
#### Description of the problem

The following file produces a `Not_found` exception in 8.17.0. In 8.16.1 it produces a normal error message.

```coq
From iris.proofmode Require Import proofmode.
#[global] Set Ltac Backtrace.

Axiom lemma : ∀ {PROP} {Q : unit → bi_car PROP} (q : unit), Q q ⊢ True.

Goal forall {PROP}, bi_pure True%type ⊢@{PROP} bi_pure True%type.
Proof. iIntros (?) "T". iDestruct (lemma with "T") as %?.
```

Output in 8.17.0:
```
File "./bug.v", line 7, characters 24-57:
Error: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.
```

Output in 8.16.1: (slightly different iris version but the details of the message don't matter anyway)
```
Error:
In nested Ltac calls to "iDestruct (open_constr) as % (simple_intropattern)",
"iDestructCore (open_constr) as (constr) (tactic3)",
"iPoseProofCore (open_constr) as (constr) (tactic3)",
"iPoseProofCoreLem (open_constr) as (tactic3)", "tac" (bound to
fun Htmp => spec_tac Htmp; [ .. | tac Htmp ]), "spec_tac" (bound to
fun Htmp =>
  lazymatch lem with
  | {| itrm := _; itrm_vars := ?xs; itrm_hyps := ?pat |} => iSpecializeCore
  {| itrm := Htmp; itrm_vars := xs; itrm_hyps := pat |} as p
  | _ => idtac
  end), "iSpecializeCore (open_constr) as (constr)",
"iSpecializeCore (open_constr) with (open_constr) (open_constr) as (constr)",
"iSpecializePat (open_constr) (constr)", "iSpecializePat_go",
"reduction.pm_reduce", "reduction.pm_eval" and "t" (with
t:=match
     environments.envs_replace (IAnon 1) ?X182@{__:=PROP}
       (if ?X181@{__:=PROP} then ?X182@{__:=PROP} else false)
       _ : ?X184@{__:=PROP}
       %env
       (environments.envs_delete false "T" ?X181@{__:=PROP}
          {|
            environments.env_intuitionistic :=
              _ : ?X49@{__:=PROP} ?X79@{__:=PROP} -∗ True
              ;
            environments.env_spatial := "T" : True
              ;
            environments.env_counter := 2%positive
          |})
   with
   | Some Δ'' => environments.envs_entails Δ'' (<absorb> ?X151@{__:=PROP})
   | None => False
   end), last term evaluation failed.
In environment
PROP : bi
Unable to unify "True%I" with "?Q ?Goal".
```

The failure can be reproduced using this script (assuming an otherwise empty opam switch):
```bash
opam repo add -y coq-released https://coq.inria.fr/opam/released
opam install -y coq.8.17.0 coq-iris.4.0.0

cat > bug.v << EOF
From iris.proofmode Require Import proofmode.
#[global] Set Ltac Backtrace.

Axiom lemma : ∀ {PROP} {Q : unit → bi_car PROP} (q : unit), Q q ⊢ True.

Goal forall {PROP}, bi_pure True%type ⊢@{PROP} bi_pure True%type.
Proof. iIntros (?) "T". iDestruct (lemma with "T") as %?.
EOF
coqc bug.v
```

#### Coq Version

8.17.0

cc @rlepigre

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17449

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — APPROVED** [review]
Yes.

**Comment by rlepigre** [comment]
Can we backport this to 8.17?

**Comment by ppedrot** [comment]
Ping @Zimmi48 about the backport.

**Comment by Zimmi48** [comment]
Sure!

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
This API looks pretty internal to me.

**Pull request merged**
