### PR TITLE
Hack the bench for https://github.com/gadmm/ocaml/tree/page-table-412.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
https://gitlab.com/coq/coq/-/jobs/1238148360

cc @gadmm

**Comment by ppedrot** [comment]
This is with https://github.com/gadmm/ocaml/tree/page-table-412.
```
┌─────────────────────────────┬──────────────────────────┬────────────────────────────────────────┬────────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]       │               CPU cycles               │            CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                          │                                        │                                        │                         │                 │
│                package_name │     NEW      OLD   PDIFF │            NEW             OLD   PDIFF │            NEW             OLD   PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-core │  107.68   131.46  -18.09 │   303817183095    370583804100  -18.02 │   442952959795    543188689549  -18.45 │  388644   388616   0.01 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  304.94   337.58   -9.67 │   860945022484    953831009968   -9.74 │  1516435577004   1588573131798   -4.54 │ 4069884  2515732  61.78 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  158.50   170.80   -7.20 │   442078481846    476199835103   -7.17 │   601408065091    609313201638   -1.30 │  756496   780956  -3.13 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  147.24   158.42   -7.06 │   410477331903    441904832899   -7.11 │   517941227795    526046801988   -1.54 │  573844   569216   0.81 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  181.53   194.93   -6.87 │   505193863025    543370292736   -7.03 │   694505196593    703979723882   -1.35 │  716252   711952   0.60 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  523.15   560.76   -6.71 │  1457072465693   1571728684041   -7.29 │  1810939261801   1850287171534   -2.13 │ 1195432  1190892   0.38 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-stdlib │  411.76   441.14   -6.66 │  1148711186548   1235133212632   -7.00 │  1531526965792   1560357961678   -1.85 │  582084   573376   1.52 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │  113.69   121.73   -6.60 │   324723498564    350007797862   -7.22 │   432182203652    436048037203   -0.89 │  490504   476516   2.94 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1403.15  1500.51   -6.49 │  3909575298665   4192604408155   -6.75 │  5664468695307   5759864649597   -1.66 │ 1087864  1118980  -2.78 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   51.93    55.53   -6.48 │   144360994762    154968895606   -6.85 │   194978531423    198092914893   -1.57 │  493608   487208   1.31 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  585.58   624.95   -6.30 │  1633108044928   1751830282603   -6.78 │  2593049791988   2630152518823   -1.41 │ 2864260  3110748  -7.92 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1324.80  1412.97   -6.24 │  3686712649449   3936999681192   -6.36 │  5124582427036   5193038194389   -1.32 │ 1193184  1212780  -1.62 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   57.56    61.32   -6.13 │   159514923092    170746639072   -6.58 │   197215808940    200724882973   -1.75 │  543676   537184   1.21 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   58.90    62.65   -5.99 │   163796390191    174556942628   -6.16 │   217766950634    221418976814   -1.65 │  474832   470984   0.82 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  184.59   196.17   -5.90 │   514882678626    551343199720   -6.61 │   677282179361    690145794096   -1.86 │  497260   494476   0.56 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  233.23   247.68   -5.83 │   649637176193    690274560933   -5.89 │   952482830916    959948773227   -0.78 │  678212   679884  -0.25 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1106.44  1173.25   -5.69 │  3081974072512   3268208385610   -5.70 │  4685216313747   4725090086116   -0.84 │  964708   966240  -0.16 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  154.16   163.38   -5.64 │   429302089178    455113755974   -5.67 │   512299038435    516489061814   -0.81 │  895432   879248   1.84 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 4851.54  5140.05   -5.61 │ 13504301843543  14329394699666   -5.76 │ 23465482510641  23842834414562   -1.58 │ 3189788  2378980  34.08 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-hott │  289.15   305.83   -5.45 │   808946760947    860244376643   -5.96 │  1223467274656   1238421287187   -1.21 │  584784   579472   0.92 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │  104.30   110.15   -5.31 │   289019419687    306259163149   -5.63 │   396544945586    399078501533   -0.63 │  560500   554548   1.07 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1545.61  1631.30   -5.25 │  4311972243532   4555807646442   -5.35 │  7047791478676   7118865761711   -1.00 │ 3146456  2991356   5.18 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   74.44    78.51   -5.18 │   205654188168    218792070048   -6.00 │   252029293446    253835538871   -0.71 │  584556   583996   0.10 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2205.07  2316.17   -4.80 │  6130274729777   6442882308039   -4.85 │ 12093420687655  12199199310078   -0.87 │  841004   819648   2.61 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  325.72   342.10   -4.79 │   906335130038    953559728414   -4.95 │  1536347990515   1546297327549   -0.64 │  755924   752688   0.43 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  750.45   786.33   -4.56 │  2086320064627   2189396094564   -4.71 │  3311687059121   3348871989849   -1.11 │ 1177800  1152828   2.17 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   59.64    62.28   -4.24 │   166081732697    174815053973   -5.00 │   218101991348    219163068580   -0.48 │  499004   493364   1.14 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  682.04   711.87   -4.19 │  1896293428026   1984685160145   -4.45 │  2935692529175   2954184289951   -0.63 │ 1167256  1163496   0.32 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │ 1398.90  1440.33   -2.88 │  3888828319085   4011876103024   -3.07 │  6369855493118   6393430150949   -0.37 │ 1108916  1099828   0.83 │   0    0    nan │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │    4.71     4.83   -2.48 │    13217458854     13473464625   -1.90 │    23982730125     24370111064   -1.59 │  378716   378868  -0.04 │   0    0    nan │
└─────────────────────────────┴──────────────────────────┴────────────────────────────────────────┴────────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
Trying https://github.com/gadmm/ocaml/tree/mark-prefetching-412 now: https://gitlab.com/coq/coq/-/jobs/1243628599

**Comment by gares** [comment]
WOW!

**Comment by ppedrot** [comment]
https://github.com/gadmm/ocaml/tree/mark-prefetching-412
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-core │  124.05   131.89  -5.94 │   349504367677    370256378075  -5.60 │   509414291709    543305078892  -6.24 │  388832   388420    0.11 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-coquelicot │   78.46    79.96  -1.88 │   218052415776    222320883522  -1.92 │   255061443701    260418722288  -2.06 │  575368   577544   -0.38 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  331.40   337.19  -1.72 │   935708092661    952031539164  -1.71 │  1552055302816   1588266961923  -2.28 │ 2515736  2515756   -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fiat-core │  120.56   122.40  -1.50 │   347835439237    351696832670  -1.10 │   436481892983    439432009419  -0.67 │  476692   476768   -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-stdlib │  433.65   439.89  -1.42 │  1214789898326   1233602848214  -1.53 │  1543179349943   1560257464762  -1.09 │  573544   573508    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  618.64   625.81  -1.15 │  1734632941823   1755101120106  -1.17 │  2615453316445   2639177010369  -0.90 │ 2895540  3109188   -6.87 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2295.01  2319.34  -1.05 │  6394668179571   6462847369323  -1.05 │ 12153329628280  12206789119464  -0.44 │  855180   817088    4.66 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-color │  557.43   563.27  -1.04 │  1562918364599   1577046641237  -0.90 │  1837221565179   1855007808446  -0.96 │ 1187076  1190604   -0.30 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-math-classes │  194.47   196.50  -1.03 │   545329895738    551497330274  -1.12 │   683170224754    689962213570  -0.98 │  481168   494484   -2.69 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-bignums │   61.78    62.42  -1.03 │   172716772365    174707547175  -1.14 │   219544595304    221284416706  -0.79 │  470816   470860   -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  169.90   171.34  -0.84 │   473457215189    477078118900  -0.76 │   606235759639    608969828770  -0.45 │  781168   780848    0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 5088.71  5127.71  -0.76 │ 14172954886920  14283336071672  -0.77 │ 23688830790618  23864486423780  -0.74 │ 2362932  2379072   -0.68 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-corn │ 1645.90  1658.48  -0.76 │  4591428564502   4623729918804  -0.70 │  6190740507132   6235920232495  -0.72 │  881816   881312    0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   60.62    61.06  -0.72 │   169139398684    170336654762  -0.70 │   198719780522    200586018306  -0.93 │  537024   536992    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-hott │  303.25   305.32  -0.68 │   854205032375    860125384075  -0.69 │  1230975371205   1240444611780  -0.76 │  573772   580236   -1.11 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1410.13  1419.52  -0.66 │  3929419527378   3954940001369  -0.65 │  5182357665728   5199057333024  -0.32 │ 1148076  1215224   -5.53 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-bedrock2 │  340.04   341.86  -0.53 │   948198885125    953058473337  -0.51 │  1542959064055   1546705763566  -0.24 │  750004   754268   -0.57 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  193.95   194.80  -0.44 │   540617317510    543511863739  -0.53 │   699259691965    703772735295  -0.64 │  712476   711956    0.07 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   54.98    55.22  -0.43 │   153584720879    154635695707  -0.68 │   196478139509    197929805711  -0.73 │  487116   487128   -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1495.86  1501.72  -0.39 │  4177860999251   4196058062363  -0.43 │  5732716365345   5766348216955  -0.58 │ 1114680  1119504   -0.43 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-verdi │  110.91   111.32  -0.37 │   308268929376    309725515455  -0.47 │   401387793711    403286831902  -0.47 │  557300   555364    0.35 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  157.72   158.24  -0.33 │   439720583113    441740228783  -0.46 │   522151326515    526082579758  -0.75 │  569116   569124   -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-flocq │  163.44   163.97  -0.32 │   455531453930    456818253521  -0.28 │   516696455575    519920439015  -0.62 │  884560   879208    0.61 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-perennial │ 7294.14  7315.41  -0.29 │ 20287510987744  20341735469488  -0.27 │ 29254780716333  29359877529506  -0.36 │ 3133604  3154732   -0.67 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1625.08  1628.67  -0.22 │  4547628734105   4556601713496  -0.20 │  7088095059631   7118755306997  -0.43 │ 1831336  2991336  -38.78 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1171.56  1174.09  -0.22 │  3263599627536   3269946813162  -0.19 │  4711171822983   4724836644948  -0.29 │  967524   966608    0.09 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1279.72  1282.39  -0.21 │  3569076328881   3577172272918  -0.23 │  4660637037974   4677308765161  -0.36 │  916228   927360   -1.20 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-coqutil │   62.67    62.80  -0.21 │   175050763045    176118131144  -0.61 │   219929094901    221020300896  -0.49 │  494128   493616    0.10 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-rewriter │  709.90   711.09  -0.17 │  1978344781343   1983061849283  -0.24 │  2946482102844   2953711824619  -0.24 │ 1245364  1243388    0.16 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqprime │ 1448.03  1448.90  -0.06 │  4032393238703   4035433941224  -0.08 │  6379221935465   6417131737913  -0.59 │ 1090360  1099944   -0.87 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  246.90   246.96  -0.02 │   688296925626    688574579977  -0.04 │   956082681041    959603139350  -0.37 │  679796   679736    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-unimath │ 4242.11  4228.09   0.33 │ 11826868525916  11787014795794   0.34 │ 21266135054700  21294798677316  -0.13 │ 1151472  1100068    4.67 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  785.07   781.88   0.41 │  2190505463580   2178993034321   0.53 │  3341348597114   3359107481331  -0.53 │ 1173668  1169040    0.40 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                         coq │    4.75     4.72   0.64 │    13358055683     13303691242   0.41 │    23895025086     24096098210  -0.83 │  380580   379108    0.39 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
Bench for https://github.com/gadmm/ocaml/tree/mark-prefetching-bis-412: https://gitlab.com/coq/coq/-/jobs/1249679739.

**Comment by gares** [comment]
```
 ────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                            │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                            │                         │                                       │                                       │                          │                 │
│               package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-core │  120.23   130.29  -7.72 │   338644669581    366120789328  -7.50 │   506786917355    543468702165  -6.75 │  388116   390312   -0.56 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-engine-bench-lite │  313.26   328.24  -4.56 │   879783822168    922140042802  -4.59 │  1544964362103   1586846459871  -2.64 │ 2515788  2515712    0.00 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│     coq-mathcomp-ssreflect │   58.32    59.70  -2.31 │   160968132785    164216442170  -1.98 │   198436782191    200636357396  -1.10 │  537164   537160    0.00 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-algebra │  150.56   153.80  -2.11 │   418849921345    426698110077  -1.84 │   521273065099    525973828541  -0.89 │  569128   569108    0.00 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-crypto │ 4939.10  5044.47  -2.09 │ 13727984166346  14014279627711  -2.04 │ 23652912445249  23884597500345  -0.97 │ 2356772  2378844   -0.93 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│           coq-math-classes │  191.82   195.84  -2.05 │   527837028956    536150634523  -1.55 │   682796531625    689964333482  -1.04 │  481272   494552   -2.69 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-solvable │  185.79   189.68  -2.05 │   516386503532    526481510747  -1.92 │   698298776446    703743455199  -0.77 │  712540   711748    0.11 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-fingroup │   52.80    53.90  -2.04 │   146406585556    149509279550  -2.08 │   196220786482    197961767620  -0.88 │  487220   487064    0.03 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│           coq-fiat-parsers │  599.80   611.86  -1.97 │  1662362445685   1695783945857  -1.97 │  2611892181053   2639018167032  -1.03 │ 2895572  3108952   -6.86 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-color │  536.86   547.25  -1.90 │  1487234565274   1517476923800  -1.99 │  1833466557825   1854774392204  -1.15 │ 1186704  1190652   -0.33 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-corn │ 1588.01  1618.52  -1.89 │  4413207855511   4494933004222  -1.82 │  6181412587337   6236119330360  -0.88 │  873732   881248   -0.85 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-fiat-core │  118.74   120.92  -1.80 │   333086894036    338140580311  -1.49 │   436150797610    439177477173  -0.69 │  476680   476860   -0.04 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-stdlib │  427.08   434.37  -1.68 │  1197306850614   1216590751701  -1.59 │  1542179312441   1560350746472  -1.16 │  573392   573600   -0.04 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-bignums │   60.50    61.53  -1.67 │   166643541355    169497605489  -1.68 │   219440374514    221294639701  -0.84 │  470676   470868   -0.04 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│     coq-mathcomp-character │  163.04   165.70  -1.61 │   453630759628    460941442422  -1.59 │   605183385128    609097837922  -0.64 │  780836   780968   -0.02 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-hott │  302.10   306.93  -1.57 │   819689562968    831477485501  -1.42 │  1230823873837   1240518020927  -0.78 │  573804   580344   -1.13 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-flocq │  156.93   159.22  -1.44 │   435728751851    441871812006  -1.39 │   516244501251    517059967422  -0.16 │  884556   879256    0.60 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│         coq-mathcomp-field │  238.04   241.42  -1.40 │   661626447641    671038199908  -1.40 │   955085900872    959675308729  -0.48 │  683960   679736    0.62 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-geocoq │ 1451.45  1470.28  -1.28 │  4031441784054   4084032505544  -1.29 │  5726818698418   5766541401114  -0.69 │ 1115784  1119512   -0.33 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│     coq-mathcomp-odd-order │ 1130.44  1141.90  -1.00 │  3143134944544   3176450327384  -1.05 │  4705935746104   4725225909495  -0.41 │  967740   966252    0.15 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-bedrock2 │  331.04   333.25  -0.66 │   917664504935    925644526372  -0.86 │  1542675437771   1546692229016  -0.26 │  750028   754420   -0.58 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqutil │   61.90    62.23  -0.53 │   169963812301    171045640627  -0.63 │   219947356726    221032595918  -0.49 │  494400   493416    0.20 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-performance-tests-lite │ 1579.87  1586.96  -0.45 │  4411565421630   4439433160407  -0.63 │  7087340305708   7120715130702  -0.47 │ 1831512  2991352  -38.77 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-rewriter │  690.69   692.38  -0.24 │  1919054606690   1924701682609  -0.29 │  2945218445295   2952913660069  -0.26 │ 1245392  1243348    0.16 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                        coq │    4.66     4.62   0.87 │    12841847518     12875172183  -0.26 │    23886145550     23894753137  -0.04 │  379924   380264   -0.09 │   0    0    nan │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-coqprime │ 1409.11  1396.88   0.88 │  3923413449846   3887717100755   0.92 │  6380224439973   6398227668244  -0.28 │ 1090484  1099924   -0.86 │   0    0    nan │
└────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
I think we can close this.

**Comment by gadmm** [comment]
Many thanks!

(For those reading out of context again, the results for mark-prefetching-412 are less than expected, which is most likely due to the page table, as shown by mark-prefetching-bis-412 which queries the page table differently.)

**Pull request closed without merging**
