### PR TITLE
Fix build of micromega & nsatz with OCaml 4.06

### LINKED ISSUE #6513: Coq doesn't find Nix-installed Num library for OCaml 4.06
#### Version

8.8+alpha (7e319ad03aba413f3165b848eaf821b364f9291b)

#### Operating system

Linux / NixOS

#### Description of the problem

As reported by @jwiegley today on Gitter, compiling Coq with OCaml 4.06 provided with Nix seems to hit an issue.

To reproduce, first apply the following patch to `default.nix`:

```diff
diff --git a/default.nix b/default.nix
index 3dd24bac4..1c438f47a 100644
--- a/default.nix
+++ b/default.nix
@@ -34,6 +34,7 @@ stdenv.mkDerivation rec {
 
     # Coq dependencies
     ocaml
+    ocamlPackages.num
     findlib
     camlp5_strict
 
@@ -56,7 +57,7 @@ stdenv.mkDerivation rec {
   ] else []) ++ (if lib.inNixShell then [
     ocamlPackages.merlin
     ocamlPackages.ocpIndent
-    ocamlPackages.ocp-index
+    # ocamlPackages.ocp-index
   ] else []);
 
   src =
```

The dependency on the Num library is otherwise missing, and ocp-index does not seem to compile in current `<nixpkgs>` (version NixOS/nixpkgs@93829f1b031a66c093865910b1e8823c6b59c720) with OCaml 4.06.

Then run `nix-shell --arg ocamlPackages "with import <nixpkgs> {}; ocaml-ng.ocamlPackages_4_06"`.
In the shell, we can see the library Num is found by ocamlfind:

```
$ ocamlfind query num
/nix/store/nkrk7hfp7xx3j0h4bl7dpvxm574p7mj4-ocaml4.06.0-num-1.1/lib/ocaml/4.06.0/site-lib/num
```
and configure runs without trouble:
```
$ ./configure -local
You have OCaml 4.06.0. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.03. Good!
You have native-code compilation. Good!
You have the Num library installed. Good!
LablGtk2 found (via ocamlfind, 2.18.6), with native threads:
=> native CoqIde will be built.
```
but launching the compilation fails with:
```
OCAMLC    plugins/micromega/sos_types.mli
File "plugins/micromega/sos_types.mli", line 15, characters 11-18:
Error: Unbound module Num
```
which seems to indicate that the Makefile doesn't know how to find the Num library (probably doesn't use ocamlfind for this).

### PR DESCRIPTION
**Pull request by vbgl**
Fixes #6513 

NB: I’m open to suggestions on how to avoid that much duplication in the Makefile rules.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>NB: I’m open to suggestions on how to avoid that much duplication in the Makefile rules.

You could put it in the CAMLFLAGS (defined through configure.ml, OCAMLC and OCAMLOPT use it).

**Comment by vbgl** [comment]
Do you mean always giving the argument `-package unix,num`, even to compile files that do not depend on these libraries?

**Comment by ejgallego** [comment]
Here there is a discrepancy wrt what `coq_makefile` does and what the build system does. Switching these plugins to `coq_makefile` would work too.

**Comment by herbelin** [comment]
BTW, isn't there a compositionality issue with the Makefile, or at least a confusing terminology issue? As far as I understand, the option `-package` is not an argument of `ocamlc` but of `ocamlfind ocamlc`. So, the suggested semantics that `OCAMLC` refers to `ocamlc` is wrong. At least, `OCAMLC` should be renamed into say `OCAMLFINDOCAMLC` so that it is clear that the variable is supposed to point to `ocamlfind ocamlc` and not to `ocamlc`. Or, alternatively, to preserve the meaning of the variable, to generalize the use of the function `bestocaml` and let this function control whether it uses `ocamlfind` or not, and whether it then accordingly uses `-package` or adds a `.cmxa`/`.cma` suffix to the name of the package.

**Comment by herbelin** [comment]
All what I can say is at least that this disturbed me. Once the surprise accepted, I'm ready to think at `OCAMLC` meaning `ocamlfind ocamlc`.

**Comment by gares** [comment]
> Switching these plugins to coq_makefile would work too.

It is on my plans for 8.8.

**Comment by Zimmi48** [comment]
> > Switching these plugins to coq_makefile would work too.
>
> It is on my plans for 8.8.

which shouldn't prevent merging this PR as a temporary workaround.

**Comment by maximedenes** [comment]
Should this be merged as it is? Or improved?

**Comment by gares** [comment]
> which shouldn't prevent merging this PR as a temporary workaround.

totally agree

**Comment by ejgallego** [comment]
> > Switching these plugins to coq_makefile would work too.
> 
> It is on my plans for 8.8.

Note however the likely impact on build times, the current make system has a great advantage of considering the whole of Coq globally, which while bad for modularity, it is great for users of `make -j`.

Not easy to solve.

**Review by gares — APPROVED** [review]

**Comment by RalfJung** [comment]
> Note however the likely impact on build times, the current make system has a great advantage of considering the whole of Coq globally, which while bad for modularity, it is great for users of make -j.

If the inner make is invoked properly, it should be sharing the jobserver with the outer make, so the impact on build times shouldn't be too bad -- right?

**Comment by ejgallego** [comment]
@RalfJung AFAIK the problem of makefile compositionality is not trivial and this is why experienced makefile users recommend a single global makefile.

`dune` is very interesting as indeed it supports a compositional model, I wouldn't rule out adding support to `.v` files, talking to `dune` upstream about this soon.

**Pull request merged**
