### PR TITLE
Correctly classify variables as being unfoldable in dnet patterns.

### LINKED ISSUE #12571: Typeclass resolution does not unfold local variables.
This was discovered as a byproduct of #12565. Here is a reproducible test.
```
Axiom IsTrunc : Type -> Type.

Existing Class IsTrunc.

Declare Instance trunc_forall :
  forall (A : Type) (P : A -> Type),
  IsTrunc (forall a : A, P a).

Axiom Graph : Set.
Axiom in_N : forall (n : Graph), Type.

Definition N : Type := @sigT Graph in_N.

Goal forall (P : N -> Type)
 (Q := fun m : Graph => forall mrec : in_N m, P (existT _ m mrec))
 (A : Graph), IsTrunc (Q A).
Proof.
intros.
typeclasses eauto. (* fails *)
```
This is due to a misclassification of local variables as being always opaque in the pattern computation algorithm of bounded dnets.

cc @mattam82

### PR DESCRIPTION
**Pull request by ppedrot**
Fixes #12571.

- [X] Added / updated test-suite
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by ppedrot** [comment]
This will need a (backwards compatible) overlay for HoTT.

**Comment by ppedrot** [comment]
The bug was correctly identified in many places in HoTT, there were several comments wondering why typeclass resolution was not solving the goal...

**Comment by maximedenes** [comment]
How about removing the default case, so as to prevent similar future problems? Maybe also in `constr_pat_discr_st`.

**Comment by maximedenes** [comment]
Could this improve the compatibility story for switching to discriminated bases (in which case it could be good to re-evaluate it), or is it a separate mechanism?

**Comment by ppedrot** [comment]
@maximedenes do you mean that we need to explicit all `constr` constructors? I don't think it'd help much, the problem here seems to have arised from the `when` clause instead.

**Comment by ppedrot** [comment]
> Could this improve the compatibility story for switching to discriminated bases

I don't think it'd matter much, it's fairly uncommon to have local definitions.

**Comment by maximedenes** [comment]
> do you mean that we need to explicit all `constr` constructors?

Yes, this is what I mean.

> I don't think it'd help much, the problem here seems to have arised from the `when` clause instead.

In general, I tend to recommend to avoid fragile pattern matchings on `constr`, as it makes it very hard to extend terms. The only exception is when you are really looking for a specific kind of terms.

Also, is there any drawback in listing the few remaining cases?

**Comment by ppedrot** [comment]
> In general, I tend to recommend to avoid fragile pattern matchings on constr

As far as I am concerned, I hate `when` clauses with a passion, even for non-constr matchings. They're an incredible source of bugs and subtle code, when it should be straightforward to inline an if-then-else branch that ensures statically a lot of stuff. Most other people seem to like them so I don't make a fuss, but personally I never introduce them.

> Also, is there any drawback in listing the few remaining cases?

It's going to make this one-line fix bigger, but if you insist...

**Comment by maximedenes** [comment]
> It's going to make this one-line fix bigger

I don't think it's a big problem to add 3-4 lines to this patch.

**Comment by ppedrot** [comment]
Your desires are orders.

**Review by maximedenes — APPROVED** [review]
Well spotted!

**Comment by ppedrot** [comment]
The HoTT overlay has been merged upstream, this should be ready now.

**Comment by maximedenes** [comment]
@mattam82 do you want to be the assignee, or should I take it, as this looks like a straightforward fix?

**Comment by ppedrot** [comment]
@maximedenes you should probably assign it's quite a straightforward PR.

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
