### PR TITLE
[ugraph] copy on marshal

### PR DESCRIPTION
**Pull request by gares**
Traversing the graph has a state, if a threads marshals a graph as it
finds it the receiver starts with wrong invariants.
CFR: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/STM.20woes

@SkySkimmer can you plase test this with your ultradebug framework? Also, is there another copy of the ugraph in the evar map?

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>Also, is there another copy of the ugraph in the evar map?

2 of them (UState.universes and UState.initial_universes)

**Comment by ppedrot** [comment]
This is a bit ugly. Can't we hack something slightly cleaner with cephemerons or something?

**Comment by gares** [comment]
Let's first see if it solves the issue.

**Comment by gares** [comment]
> 2 of them (UState.universes and UState.initial_universes)

OK, let me amend this patch first

**Comment by gares** [comment]
If only I could find the summary entry for the evarmap...

**Comment by SkySkimmer** [comment]
evar map is in this stuff https://github.com/coq/coq/blob/95dceef10354cb59a0eb4eca23f2c60589983258/vernac/vernacstate.ml#L102 I think

**Comment by SkySkimmer** [comment]
The only place I can find with `marshallable:true` is in Partac, am I missing something?

**Comment by ppedrot** [comment]
If the problem is due to marshalling invalid data, I propose instead that we add a `dirty` mutable flag to ugraphs, that is set when the code enters a critical section. If we enter a critical section with the dirty flag set, this means that the graph was marshalled concurrently with a graph traversal. Assuming single-threadeness of graph traversals, it is thus enough to clean up the state. This allows not touching the API.

**Comment by SkySkimmer** [comment]
Lots of segfaults in CI, also timeouts and https://gitlab.com/coq/coq/-/jobs/2523143483 which is a psatz / micromega error.
No ugraph related stuff it seems but that doesn't have to mean anything.

**Comment by gares** [comment]
In some sense good news. I'll implement PMP suggestion and push again.

**Comment by gares** [comment]
I haven't finished it yet because it is not trivial to hide mutability as I'd like. But more importantly, I do still need to change the API.
The problem is that *each graph* should have a distinct mutability bit, so `empty` becomes a function. This propagates everywhere, eg `env`. So, API wise, is it as ugly as the copy thing.

**Comment by ppedrot** [comment]
Well, you can always wrap the mutable reference in an option and set it to some fresh ref as soon as you add the first canonical node.

**Comment by SkySkimmer** [comment]
Sorry, I don't get it. What's wrong with addin a `mutable dirty : bool` to https://github.com/coq/coq/blob/ffc0ca5216f373dc9c632b89fc662088099b1b3f/lib/acyclicGraph.ml#L124 ? When we change the graph (add a node or edge) we will produce a new record with a separate dirty bit.

**Comment by gares** [comment]
> new record with a separate dirty bit.

But it may share some canonical node, so I'm not so sure my code is correct now.

**Comment by SkySkimmer** [comment]
Maybe we do want a  shared ref then

**Comment by gares** [comment]
It would be much more clear to to marshal a (potentially) broken graph, and in the clients start to sanitize it.
Or make a copy on freeze, as I was doing, to prevent it from bitrotting silently by side effect, which is the brain dead approach.

Having by invariant that all graphs share the same dirty bit since they potentially also share some canonical nodes, and that if one graph happens to be dirty one has to reset it (but also all the other ones sharing the same dirty bit), is too complex to explain and implement imo.

@ppedrot what the argument against copy? (other than the API which is boring, but dumb)?

**Comment by ejgallego** [comment]
Umm, if the problem is that we want to handle objects that are not functional in a functional way I'm afraid we are in a mess :(

**Comment by SkySkimmer** [comment]
Maybe we can do a real critical section, tell the marshalling thread to wait until the dirty work is done

**Comment by ejgallego** [comment]
> Again, we can code anything. But what is wrong with copy?!

It solves just one race, but relies on the user remembering to call it, right?

Indeed a real critical section may be safer.

**Comment by ejgallego** [comment]
Maybe I'm wrong, but I was under the assumption that for example in OCaml 5 we could treat the evar_map as something referentially transparent, imagine how many ways things can go wrong then unless we lock this .

**Comment by ejgallego** [comment]
I agree that with the current architecture copy seems doable (tho extremely fragile), but note my explicit mention to OCaml 5

We can discuss about it tomorrow if people is around for the call.

**Comment by gares** [comment]
#16127 is just better

**Pull request closed without merging**
