### PR TITLE
Vars.substituend: cache lifts, not just closedness

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by Alizter** [comment]
It's very small but it's still something. Do you think it's worth the extra code?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I don't think that the little increase in code size is problematic.

**Comment by ppedrot** [comment]
Merging soon, in any case.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
