### PR TITLE
Forbid defining ltac2 values and types inside module types

### PR DESCRIPTION
**Pull request by SkySkimmer**
It is completely broken.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
cf eg https://github.com/coq/coq/issues/16550

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
If I read the CI correctly before I clicked re-run, only fiat-crypto failed, due to the out-of-memory issue that already existed before this PR.

**Review by ppedrot — CHANGES_REQUESTED** [review]
I believe this should be a warning that errors by default, so that this can be turned off. Despite being unsound there are legitimate use-cases of Ltac2 appearing in interfaces (e.g. when the interface is a copy-paste of the module) which can arise if we want to have a lightweight interface mechanism for Coq files.

**Comment by ppedrot** [comment]
@SkySkimmer this should go into 8.17, but please implement the warning solution instead.

**Comment by SkySkimmer** [comment]
changed

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
