### PR TITLE
Bugzilla autolink: avoid linking inside links (fix #5974).

### LINKED ISSUE #5974: Coq_Bugzilla_autolink.user.js overwrites existing link with link to Bugzilla
It would be good if this user-script could add links to Bugzilla only when there is not already an existing link.
The migration script added a lot of instances of BZ#nnnn with an internal link to GitHub. There is also a header with "Original bug ID: BZ#nnnn": this one is on purpose, this is purposely to not create lots of links which could become dead whenever we decide to kill Bugzilla; but I was counting on @SkySkimmer's recently introduced user-script to still add the link to the original Bugzilla report automatically.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Not sure of this works if there are multiple BZ# in a node: BZ#1, BZ#2.

**Comment by SkySkimmer** [comment]
Indeed it doesn't work.

**Comment by SkySkimmer** [comment]
Now it should work.
Here's a link for testing on this page: [BZ#3](https://example.org) (should link example.org).

**Comment by Zimmi48** [comment]
Works like a charm, thanks! And it is incredible how I just had to click on view, then raw, and Greasemonkey automatically recognized a user-script and proposed me to install it!

**Pull request merged**
