### PR TITLE
Checker: use inductive's check_template flag

### PR DESCRIPTION
**Pull request by SkySkimmer**
And enable related test.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Should be ready.

**Review by ppedrot — COMMENTED** [review]
I know this is strictly not part of this PR, but it would be better to have an output test for coqchk on this kind of behaviours.

**Comment by ppedrot** [comment]
Also, the default seems not to print anything when using unsafe features in the checker, which look **VERY WRONG**.

**Comment by ppedrot** [comment]
I opened #11477, let's merge this in the meantime.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
