### PR TITLE
Port `eauto` to the new engine

### PR DESCRIPTION
**Pull request by ppedrot**
This removes the legacy tactic layer from `eauto`, which was the last place still using it in the Coq codebase.

We went for an essentially backwards compatible change (barring the fact that the compatibility layer was lossy in corner-cases). Contrarily to the first iteration of this PR, we didn't tweak the sorting of hints and had to resort to local evaluation of Extern hints to decide whether the solve the goal or not. Thus it shouldn't break scripts in the wild, at the cost of a somewhat hackish implementation.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1904878842

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
The stdpp failure is due to the corner-case change of priority of extern hints, right in the place where it hurts. A further minimized example:
```
Require Import Coq.micromega.Lia.

Global Hint Extern 1000 => lia : lia.
Definition is_Some {A} (mx : option A) := exists x, mx = Some x.

Axiom mk_is_Some : forall {A} (mx : option A) x, mx = Some x -> is_Some mx.
Global Hint Resolve mk_is_Some : core.

Axiom lookup_list : forall {A : Type}, nat -> list A -> option A.

Lemma foo : forall A, 0 < 0 -> @is_Some A (lookup_list 0 nil).
Proof.
intros A H.
debug eauto with lia.
Qed.
```

In master, the debug trace is
```
(* debug eauto: *)
1 depth=5 
1.1 depth=5 (*external*) lia
```
while in this PR it is
```
(* debug eauto: *)
1 depth=5 
1.1 depth=4 simple eapply @mk_is_Some
1.1.1 depth=4 (*external*) lia
```

As witnessed by the trace, master applies `lia` upfront because it solves the goal, despite a priority of 1000 (!). In this PR, only Extern hints with priority 0 are applied immediately, regardless of whether they solve the goal (we can't compute that in advance). I would tend to think it's a bug in stdpp but both the code and documentation are weird. cc @robbertkrebbers

**Comment by ppedrot** [comment]
Bench with partial evaluation: https://gitlab.com/coq/coq/-/jobs/1975971402

**Comment by ppedrot** [comment]
ping @robbertkrebbers about the stdpp example

**Comment by robbertkrebbers** [comment]
Apologies for not responding, I was on vacation at that time.

Just to get clear what happens:

- In the new situation: `mk_is_Some` is applied, then `lia`, and hence the proof fails because of an unresolved evar?
- The fact that `lia` was performed before `mk_is_Some` was a bug

If my understanding is correct, then I think we should fix std++.

**Comment by ppedrot** [comment]
> If my understanding is correct

I think so. We can try to fix std++ but I am not sure how to do that in a backwards compatible way. In the current iteration the PR is emulating the old buggy behaviour but this should be fixed in a way that can be tweaked via a flag maybe?

**Comment by ppedrot** [comment]
Bench with filter_tactics removed: https://gitlab.com/coq/coq/-/jobs/1978067441

**Comment by ppedrot** [comment]
Final bench: https://gitlab.com/coq/coq/-/jobs/1978804669

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-compcert │  292.25   301.44  -3.05 │  1270745120257   1312476451908  -3.18 │  1894362598398   1942761857089  -2.49 │ 1097636  1097104   0.05 │   0    0      nan │
│         coq-metacoq-erasure │   70.29    72.29  -2.77 │   302591555488    312255698936  -3.09 │   455005545944    460603719139  -1.22 │ 1071600  1070996   0.06 │   0    0      nan │
│                  coq-geocoq │  714.48   732.61  -2.47 │  3120311029871   3198011302326  -2.43 │  4949514364753   5037633321419  -1.75 │ 1074292  1074244   0.00 │   0    0      nan │
│                 coq-bignums │   28.61    29.29  -2.32 │   124593381315    127488324922  -2.27 │   172739780123    174173240805  -0.82 │  466192   466652  -0.10 │   0    0      nan │
│                    coq-corn │  808.97   827.93  -2.29 │  3530846891275   3616334813743  -2.36 │  5498261188794   5571958464945  -1.32 │  875164   876392  -0.14 │   0    0      nan │
│        coq-metacoq-template │   76.70    78.31  -2.06 │   328245188826    334583633703  -1.89 │   500881383030    502005950621  -0.22 │  699448   693644   0.84 │   0    2  -100.00 │
│           coq-metacoq-pcuic │  735.13   749.33  -1.90 │  3218474742602   3281063571313  -1.91 │  4579113711525   4609316000397  -0.66 │ 1116428  1110596   0.53 │   2    0      nan │
│                  coq-stdlib │  412.42   420.14  -1.84 │  1470127871241   1483687368351  -0.91 │  1443902091972   1445311845218  -0.10 │  604832   589276   2.64 │   0    0      nan │
│               coq-fiat-core │   55.21    56.24  -1.83 │   230913769912    236016342573  -2.16 │   324376185423    325483006030  -0.34 │  474220   473580   0.14 │   2    3   -33.33 │
│              coq-verdi-raft │  590.24   600.84  -1.76 │  2576836879945   2623239225496  -1.77 │  3991602448395   4046774664897  -1.36 │ 1220628  1218528   0.17 │   0    0      nan │
│            coq-math-classes │   96.62    98.23  -1.64 │   419813701581    426167667198  -1.49 │   591770299975    591898653339  -0.02 │  495388   495264   0.03 │   0    0      nan │
│                 coq-coqutil │   35.60    36.18  -1.60 │   153601541384    155766743317  -1.39 │   208272323737    208687635037  -0.20 │  601164   601976  -0.13 │   4    0      nan │
│                   coq-verdi │   49.58    50.34  -1.51 │   215480104525    218335409974  -1.31 │   322770373888    324267872456  -0.46 │  827792   830040  -0.27 │   0    0      nan │
│            coq-fiat-parsers │  342.61   347.63  -1.44 │  1482521271260   1501853362242  -1.29 │  2456680644685   2460025772110  -0.14 │ 2782240  2782400  -0.01 │   0    3  -100.00 │
│                coq-bedrock2 │  195.02   197.82  -1.42 │   851944491461    864044023107  -1.40 │  1571233834193   1575389950713  -0.26 │ 2049164  2049308  -0.01 │  32   17    88.24 │
│              coq-coquelicot │   35.23    35.72  -1.37 │   151986529214    153841446529  -1.21 │   202273753989    202263247613   0.01 │  749208   749232  -0.00 │ 169    0      nan │
│                  coq-flocq3 │   78.59    79.65  -1.33 │   342184419241    347060432036  -1.40 │   454765956159    455126846922  -0.08 │  986328   986948  -0.06 │   0    0      nan │
│       coq-mathcomp-solvable │   89.52    90.71  -1.31 │   391980868965    397120958655  -1.29 │   609623502728    609747252861  -0.02 │  670352   668272   0.31 │   0    0      nan │
│      coq-mathcomp-character │   78.26    79.25  -1.25 │   343089763405    346942016924  -1.11 │   526803857608    526758379340   0.01 │  738532   736468   0.28 │   0    0      nan │
│           coq-iris-examples │  472.27   478.00  -1.20 │  2062411343154   2087926867844  -1.22 │  3131111044378   3137719507166  -0.21 │ 1178748  1180568  -0.15 │  12    0      nan │
│                coq-coqprime │  185.69   187.90  -1.18 │   813157078756    821901159763  -1.06 │  1555023419392   1554741267304   0.02 │  827288   827088   0.02 │   0    0      nan │
│               coq-perennial │ 4229.84  4278.78  -1.14 │ 18502102737836  18711055171159  -1.12 │ 30651220684583  30688868567817  -0.12 │ 2597388  2589832   0.29 │   0    0      nan │
│     coq-metacoq-safechecker │  197.01   199.23  -1.11 │   859805670973    870122787677  -1.19 │  1164720277577   1167471689976  -0.24 │ 1178980  1180624  -0.14 │  45    2  2150.00 │
│                   coq-color │  271.67   274.42  -1.00 │  1179957823523   1192447475722  -1.05 │  1600968740513   1602590131401  -0.10 │ 1139304  1140892  -0.14 │   7    1   600.00 │
│          coq-mathcomp-field │  116.31   117.34  -0.88 │   509371142934    514118105270  -0.92 │   847489434426    847535128007  -0.01 │  651300   649220   0.32 │   0    0      nan │
│                coq-rewriter │  386.44   389.43  -0.77 │  1685989378945   1698652472429  -0.75 │  2769214818296   2776168251902  -0.25 │ 1057916  1061448  -0.33 │   9   11   -18.18 │
│                     coq-vst │ 1177.57  1186.45  -0.75 │  5144532316036   5185994748095  -0.80 │  8385479111216   8403487556049  -0.21 │ 1901836  1889764   0.64 │   4    0      nan │
│             coq-fiat-crypto │ 3043.02  3064.59  -0.70 │ 13280393384621  13377787327131  -0.73 │ 24372236081067  24367602867876   0.02 │ 3843528  3843660  -0.00 │  82   95   -13.68 │
│       coq-engine-bench-lite │  181.06   182.31  -0.69 │   760404710651    766056766340  -0.74 │  1488291880356   1491435492252  -0.21 │ 1172172  1172160   0.00 │   0    0      nan │
│        coq-mathcomp-algebra │   64.91    65.30  -0.60 │   283904499331    285662482576  -0.62 │   397699820871    397688834128   0.00 │  559788   560800  -0.18 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  950.27   955.36  -0.53 │  4152773871417   4175513762474  -0.54 │  7199844021019   7204383166724  -0.06 │ 1142844  1143384  -0.05 │   5    0      nan │
│      coq-mathcomp-odd-order │  572.60   575.58  -0.52 │  2509894976248   2523131999146  -0.52 │  4289413502262   4289659305251  -0.01 │  932872   932100   0.08 │   0    0      nan │
│                    coq-hott │  157.80   158.56  -0.48 │   683610004564    687948125175  -0.63 │  1075111486433   1075169662714  -0.01 │  659892   657724   0.33 │   0    0      nan │
│      coq-mathcomp-ssreflect │   26.48    26.59  -0.41 │   115511785526    115949692781  -0.38 │   147015979747    147062339950  -0.03 │  533572   530976   0.49 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.05    24.13  -0.33 │   104994534264    105525728280  -0.50 │   155026331024    155025252569   0.00 │  477968   478028  -0.01 │   0    0      nan │
│  coq-performance-tests-lite │  800.81   803.38  -0.32 │  3486170470684   3493548193260  -0.21 │  5925330747909   5922809800685   0.04 │ 2322252  2049972  13.28 │   2    0      nan │
│                 coq-unimath │ 3784.81  3791.02  -0.16 │ 16570146231080  16598331516021  -0.17 │ 33167575727705  33169897029794  -0.01 │ 3861820  3861740   0.00 │  20    3   566.67 │
│    coq-metacoq-translations │   20.35    20.35   0.00 │    87865736585     87848322769   0.02 │   153923499158    153890773857   0.02 │  931544   929572   0.21 │   0    0      nan │
│                    coq-core │  102.34   102.10   0.24 │   377465835520    375745222749   0.46 │   433439553674    433389011797   0.01 │  249472   248728   0.30 │   0    0      nan │
│               coq-fourcolor │ 1519.27  1507.49   0.78 │  6643684393825   6593844988891   0.76 │ 12082370930144  12082121319455   0.00 │  723872   725340  -0.20 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```
Quite a few remarkable speed-ups in the per-line diff.

**Comment by SkySkimmer** [comment]
> Hack a partial evaluation algorithm to restore the Hint Extern priority. 

Sounds fun

You should add some of the minimized stuff to the test suite (I like to use bug_$PR for the filename)

**Comment by ppedrot** [comment]
@SkySkimmer not sure I want to explicitly keep track of buggy behaviours in the test-suite (in the sense that it goes against the spec).

**Comment by SkySkimmer** [comment]
If we are explicitly keeping it then we should update the spec.

**Comment by ppedrot** [comment]
Keeping it for now, because I don't want to mix a port to the new engine with a change of semantics. I am going to write another PR to make it behave as intended, still. There are quite a few issues reporting that `eauto` doesn't really abide by the priorities.

**Comment by SkySkimmer** [comment]
OK

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
