### PR TITLE
CErrors & CClosure

### PR DESCRIPTION
**Pull request by letouzey**
Just as Lexer recently became CLexer, could we also rename our Errors and Closure modules ? They also appears in compiler-libs (in ocamlbytecomp.cm(x)a for the first, and ocamloptcomp.cm(x)a for the second, leading to nasty warnings, or even errors with 4.03 from what I've heard. These module name clash also prevent any attempt to use compiler-libs from Coq, which could be handy for Native Compute or my Extraction Compute prototype.
I known that it would be best to have a "packed" compiler-libs, or any form of namespace for compilation units, but in the meantimes, these module renamings do help. Following the current trend, I've used CErrors and CClosure for the new names.

### CODE REVIEW

**Comment by aspiwack** [comment]
That sounds like a sound plan. But maybe something should be done about the `Cerrors` module (`toplevel/cerrors.ml{,i}`). Having both a `CErrors` and a `Cerrors` module doesn't feel right.

**Comment by letouzey** [comment]
Right, I indeed forgot about this toplevel/cerrors.ml, thanks for spotting that. What about turning this one into explainError.ml or something like that ? Anyway, it doesn't seem to occur much in the sources...

**Comment by maximedenes** [comment]
Thanks Pierre, this was indeed on my list (and on the roadmap!). I can take of the merge if you wish.

**Comment by letouzey** [comment]
Hello maxime, as you prefer. Of course, the coq-contribs with ML code should be adapted accordingly (not done yet).

**Comment by ejgallego** [comment]
Cool thanks! This will fix https://coq.inria.fr/bugs/show_bug.cgi?id=4766

**Comment by maximedenes** [comment]
Rebased and merged, thanks!

**Comment by ejgallego** [comment]
It seems to be missing an entry in `doc/dev/changes.txt` right?

**Comment by maximedenes** [comment]
@ejgallego I had already added an entry in dev/doc/changes.txt, separately

**Pull request closed without merging**
