### PR TITLE
Fix #3415: coqdoc links projections rather than constructor in record tuples

### LINKED ISSUE #3415: The entry for record constructors given via record-building syntax spans the entire notation, and perhaps it should not
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#3415
From: @JasonGross
Reported version: 8.4
CC:   coq-bugs-redist@lists.gforge.inria.fr

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix / feature

Coqdoc was binding the whole content of a `{| ... |}` tuple to the constructor name. We instead bind each projection name to the corresponding declarations. This is more fine-grained and what we expect.

Fixes #3415.

- [X] Added / updated test-suite (will work correctly after #12026 is merged)
- [X] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

Don't know if this is supposed to be a fix or a feature after having used for long a link to the constructor. I put 8.12.

### CODE REVIEW

**Comment by herbelin** [comment]
CI is morally green (only a side effect of #11896).

**Review by ejgallego — APPROVED** [review]
Sorry for the delay @herbelin ; this looks good and I propose to merge in the next hours.

I have only one comment, I'm not sure the current handling of anonymous records is optimal and could not lead to problems [see for example the newly introduced `Option.get`]

Indeed it would be good if we could refactor that part of the code a bit as to have a better high-level of the different strategies / cases here; but I leave it a your criterion whether you would like to tweak this Pr further or continue later.

**Comment by ejgallego** [comment]
> I have only one comment, I'm not sure the current handling of anonymous records is optimal and could not lead to problems [see for example the newly introduced `Option.get`]
> 
> Indeed it would be good if we could refactor that part of the code a bit as to have a better high-level of the different strategies / cases here; but I leave it a your criterion whether you would like to tweak this Pr further or continue later.

@herbelin a last ping in case you have a comment on this, will merge later today otherwise.

**Comment by herbelin** [comment]
> I have only one comment, I'm not sure the current handling of anonymous records is optimal and could not lead to problems [see for example the newly introduced `Option.get`]

You're right, the `Option.get` is a bit ugly (it relies on an invariant that the fields are defined when `complete` is true). Somehow, it is also that I did dare not changing too much the `complete` argument. One could have passed functions of different types depending on the value of `complete`.

**Pull request merged**
