### PR TITLE
Release 8.10.0

### PR DESCRIPTION
**Pull request by vbgl**
TODO:

  - [x] turn the unreleased changelog into release notes

Théo, I’m not sure about what should be done regarding the changelog/release notes. Should this be documented into the [release process](https://github.com/coq/coq/blob/master/dev/doc/release-process.md) or in the [changelog documentation](https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog)?

Ping @Zimmi48

### CODE REVIEW

**Comment by Zimmi48** [comment]
> Should this be documented into the [release process](https://github.com/coq/coq/blob/master/dev/doc/release-process.md) or in the [changelog documentation](https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog)?

Yes, this is still a TODO for me. But in this particular case, there is nothing to do since no changes with changelogs have been backported between 8.10+beta3 and 8.10.0.

**Comment by Zimmi48** [comment]
> there is nothing to do

(as shown by the successful test-suite)

**Comment by vbgl** [comment]
Thanks for the explanation. I was a bit confused by the success of the run of the test-suite.

**Comment by Zimmi48** [comment]
So now you have backported a PR with a changelog entry I see... :laughing: I'll prepare the update to the release notes.

**Comment by Zimmi48** [comment]
See #10833

**Pull request merged**
