### PR TITLE
Separate parsing effects in VERNAC EXTEND macro

### PR DESCRIPTION
**Pull request by maximedenes**
This is a step towards #15409.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I would not call this "in vernac extensions" which I would expect to touch vernacextend, this is just "in coqpp / mlg"

**Comment by maximedenes** [comment]
@coqbot run full CI

**Comment by maximedenes** [comment]
"vernac extensions" was a reference to `VERNAC EXTEND`, which is the specific macro we take care of.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by maximedenes** [comment]
@SkySkimmer Thanks!

**Pull request merged**
