### PR TITLE
Ltac2: don't use mltop magic to set the default proof mode

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
This was probably written at a time we had no `export` flags for options.

**Comment by Janno** [comment]
I have all my Ltac2 Imports wrapped in an extra layer of `Module` to avoid them setting the default proof mode for the rest of the file. Which imports will set the proof mode to Ltac2 with this change? Only `Ltac2.Init`? All `Ltac2.<..>` modules?

**Comment by SkySkimmer** [comment]
This shouldn't change behaviour.

**Comment by ppedrot** [comment]
The new code should be equivalent to the old code. The only difference would happen if you declare the ltac2 ML plugin yourself.

**Comment by SkySkimmer** [comment]
PS
>I have all my Ltac2 Imports wrapped in an extra layer of Module to avoid them setting the default proof mode for the rest of the file.

Wouldn't it be simpler to issue Set Default Proof Mode "Classic"?

**Comment by Janno** [comment]
> Wouldn't it be simpler to issue Set Default Proof Mode "Classic"?

Yes. I think when I started doing this I would constantly forget the exact spelling of `Default Proof Mode` (I am used to the incorrect spelling "proofmode") and also forget that the default proof mode is called "Classic" and not "Ltac1" and also that it needs to be in a `"Classic"`, not just `Classic`. It ended up being much faster to always put everything into a Module. I also wasn't sure about the transitive behavior of these proof mode settings, be it through `Require Export Ltac2.<..>` or `Set Default Proof Mode` at the top level of a file. Better safe than sorry, I guess.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
