### PR TITLE
Add SMTCoq to CI

### PR DESCRIPTION
**Pull request by ckeller**
This pull request adds SMTCoq to Coq's CI

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ejgallego — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@Zimmi48 am I not authorized?

**Comment by ejgallego** [comment]
@coqbot run full ci

**Comment by ejgallego** [comment]
I guess we need to use the url trick @SkySkimmer

**Comment by Zimmi48** [comment]
Sorry about that. I think the bot is accidentally checking the author of the PR rather than the comment. I'm looking into it.

**Comment by ckeller** [comment]
SMTCoq's CI failed because it depends on `num`. How do I express this?

**Comment by Zimmi48** [comment]
You can add `num` to this line:

https://github.com/coq/coq/blob/a9f6dcdc199fe5f486c916caa0028a8a5bc626d5/dev/ci/docker/bionic_coq/Dockerfile#L49

Note that you will also need to update the `CACHEKEY` according to the instructions here:

https://github.com/coq/coq/blob/a9f6dcdc199fe5f486c916caa0028a8a5bc626d5/.gitlab-ci.yml#L19-L22

**Comment by ckeller** [comment]
> Note that you will also need to update the `CACHEKEY` according to the instructions here:
> 
> https://github.com/coq/coq/blob/a9f6dcdc199fe5f486c916caa0028a8a5bc626d5/.gitlab-ci.yml#L19-L22
Should I change the date, or only the hash?

**Comment by Zimmi48** [comment]
Both date and hash, but only the hash is checked.

**Comment by Zimmi48** [comment]
@coqbot run CI

**Comment by ejgallego** [comment]
This is ready to go, will merge tomorrow, in case @ckeller would like to squash (if not, that's OK too IMHO)

Sometimes I use the convention `[ci] Add num to docker image` to make the commit a bit more descriptive in Coq's git history, but we don't have a standard in the Coq organization as such.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
