### PR TITLE
[coqdep] Start to modularize loadpath handling.

### PR DESCRIPTION
**Pull request by ejgallego**
This should allow us at some point to make the code common between
coqdep / coqtop

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot ci minimize hott

**Comment by ejgallego** [comment]
@Alizter I know this is likely to be broken in some parts, I tried to signal it with `needs: progress` , the way I replaced the stlib special cases will likely not work. I can give it another go soon.

**Comment by Alizter** [comment]
The old dependency was #15821 which was merged.

**Comment by ejgallego** [comment]
Let's see how this fares.

**Comment by Alizter** [comment]
The windows failure looks real, however the itauto one is waiting for an overlay.

**Comment by ejgallego** [comment]
The issue is `System.(//)` vs `Filename.concat` , we have a mess with path handling of large proportions.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Merging soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
