### PR TITLE
Stop automatically using `assumption` in `replace by tac`

### LINKED ISSUE #17959: replace by tac should not mask tac's failure message
#### Description of the problem

```coq
Goal True.
  assert_succeeds replace True with False.
  Fail replace True with False; [ | exact I ].
  (* The command has indeed failed with message:
Ltac call to "exact (uconstr)" failed.
The term "I" has type "True" while it is expected to have type "False = True".
*)
  replace True with False by exact I.
  (* Error:
Ltac call to "replace (uconstr) with (constr) (clause_dft_concl) (by_arg_tac)" failed.
No applicable tactic.
   *)
```
#### Coq Version

8.19+alpha (61ee398ed32f9334dd664ea8ed2697178e6e3844)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #17959

Overlays (should be backwards compatible):
- https://github.com/mit-plv/bedrock2/pull/371
- https://github.com/coq-community/bignums/pull/79
- https://github.com/mit-plv/fiat-crypto/pull/1657

### CODE REVIEW

**Comment by ppedrot** [comment]
This looks quite non-backwards compatible... Is it worth it? The original bug could be solved much more simply as you commented there.

**Comment by SkySkimmer** [comment]
OK let's keep the auto assumption when there's no `by tac`

**Comment by ppedrot** [comment]
I was more on the line of using tclORELSE0 but if this version of the PR is backwards compatible enough it's also fine.

**Review by Zimmi48 — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
