### PR TITLE
Anonymous sections

### LINKED ISSUE #2177: Feature request: unnamed sections
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#2177
From: @Eelis
Reported version: 8.2
CC:   @tomprince

### PR DESCRIPTION
**Pull request by maximedenes**
This is an attempt at cleaning up the lib stack, and providing anonymous sections. It is still work in progress.

Fixes / closes #2177

Closely related to #8831.

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.md.

### CODE REVIEW

**Comment by ppedrot** [comment]
@maximedenes is this still an active PR or did your work on the libobject layer superseded it?

**Comment by ppedrot** [comment]
@maximedenes ping

**Comment by maximedenes** [comment]
> is this still an active PR or did your work on the libobject layer superseded it?

It is not subsumed. My other work is about the structure of libobjects, this is about the naming.

**Comment by ppedrot** [comment]
At the very least, this needs a rebase.

**Comment by maximedenes** [comment]
I no longer think this is a priority, will close the corresponding issue as a wontfix.

**Pull request closed without merging**
