### PR TITLE
Make abstract compatible with mangle names

### LINKED ISSUE #3146: Strange interaction between abstract and implicit argument naming
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#3146
From: @ppedrot
Reported version: 8.5
CC:   coq-bugs-redist@lists.gforge.inria.fr

### LINKED ISSUE #12928: Name mangling breaks using names in `abstract`
#### Description of the problem

The following proof script fails, but I would expect it to work:
```coq
Set Mangle Names.
Lemma test: forall x: nat, nat.
Proof. intros x. abstract (exact x). Qed.
```
It says:
```
Error: The reference x was not found in the current environment.
```

#### Coq Version

Latest Coq master

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #12928

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
The diff interface is not making clear that this is a one-line change modulo indentation, which seems correct. (Hopefully there are no possible interactions with sections...)

**Comment by SkySkimmer** [comment]
test-suite:edge+flambda https://gitlab.com/coq/coq/-/jobs/708635067
~~~
File "./primitive/float/compare.v", line 383, characters 0-53:
Error:
Dynlink error: The module `Coq_native5a6252' is already loaded (either by the main program or a previously-dynlinked library)
~~~
Is there an issue with the fresh name generation somehow?

**Comment by ppedrot** [comment]
Uh? How does native interact here? We're just renaming intro variables???

**Comment by maximedenes** [comment]
> Uh? How does native interact here? We're just renaming intro variables???

I think @SkySkimmer is suggesting an unrelated issue.

**Comment by SkySkimmer** [comment]
>I think @SkySkimmer is suggesting an unrelated issue.

yes
Let's rerun and see

**Comment by jashug** [comment]
It looks like this probably also fixes issue #3146, in which case the comment at the top of `test-suite/success/name_mangling.v` about it can now be removed.

**Review by jashug — APPROVED** [review]
Looks good to me.

**Pull request merged**
