### PR TITLE
Fix timestamp of coqchk manpage

### PR DESCRIPTION
**Pull request by k4rtik**
See [history](https://github.com/coq/coq/commits/master/man/coqchk.1) and the last commit updating this file: 9c0f36adac233efb1164ef88c86c78c7509d8b2c

**Kind:** documentation

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

In my judgment this minor correction need not go into the changelog. Leaving this last checkbox item around for maintainers to verify.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
How about removing it instead?

**Comment by k4rtik** [comment]
That's a good point from the maintenance perspective. Let me do that for all of the man pages and send another patch commit.

**Comment by k4rtik** [comment]
I felt okay removing the "Coq tools" part in the header for `coqdep.1` and `coqwc.1` as this terminology seems to be used for [other tools](https://github.com/coq/coq/wiki/Tools) now.

An alternative, if needed, could be Coq Utilities as the [reference manual uses](https://coq.inria.fr/refman/practical-tools/utilities.html) them.

**Review by Zimmi48 — APPROVED** [review]
Not really a manpage specialist but this seems reasonable to me. I'll merge this in a few days in case anyone wants to comment on this change first.

**Pull request merged**
