### PR TITLE
Deprecate List.Forall2_refl (it has a bad type)

### PR DESCRIPTION
**Pull request by SkySkimmer**
cf coq/stdlib#56 (close after the deprecation phase)

### CODE REVIEW

**Review by andres-erbsen — APPROVED** [review]

**Comment by andres-erbsen** [comment]
@coqbot run fill ci

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
changelog added

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Pull request merged**
