### PR TITLE
Remove Interval from the continuous integration.

### PR DESCRIPTION
**Pull request by silene**
It currently prevents the merge of #13895, and its master branch is about to become incompatible with the version of Flocq built during continuous integration.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
This goes against the efforts of @gares to make sure all plugins in the Coq platform are kept in sync with Coq master, but I don't see how we could oppose to its author requesting the removal...

**Comment by Zimmi48** [comment]
I guess you want this merged ASAP?

**Comment by Zimmi48** [comment]
I'll do that anyway since you have mistakenly pushed this branch to the main repo.

@coqbot merge now

**Comment by silene** [comment]
> I'll do that anyway since you have mistakenly pushed this branch to the main repo.

Argl, sorry about that. I really need to look if I can get Git to ask for confirmation when pushing to some specific repositories.

**Comment by erikmd** [comment]
Sorry for bumping a very old issue but I got aware of this one [from Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Coq.20Interval.20master.20does.20not.20build.20with.20Coq.208.2E16.2Brc1/near/285960549).

@silene 

> > I'll do that anyway since you have mistakenly pushed this branch to the main repo.
> 
> Argl, sorry about that. I really need to look if I can get Git to ask for confirmation when pushing to some specific repositories.

FWIW, I already experienced this in other contexts, and I had devised a small git alias to avoid this:

```bash
git config --global alias.togglessh '!f(){ if [ $# -lt 1 ]; then
  printf "Usage: git togglessh origin
   or: git togglessh <remote>  # toggle ssh<->https in remote URL\n";
  else url=$(git remote get-url "$1");
  if echo "$url" | grep -q -e "^git@"; then
    url=$(echo "$url" | sed -e "s/^git@//; s|:|/|; s|^|https://|");
  else
    url=$(echo "$url" | sed -e "s|^https://||; s|^ssh://||; s|/|:|; s|^|git@|");
  fi; git remote set-url "$1" "$url"; echo "$1 -> $url"; fi; }; f'

$ git togglessh 
Usage: git togglessh origin
   or: git togglessh <remote>  # toggle ssh<->https in remote URL

################################################################
# Assume one has an upstream remote that shouldn't be pushed to:

$ git remote -v
upstream    git@github.com:erikmd/git-scripts.git (fetch)
upstream    git@github.com:erikmd/git-scripts.git (push)

# Then we can just run this command:

$ git togglessh upstream
upstream -> https://github.com/erikmd/git-scripts.git

################################################################
# Or revert to the ssh url:

$ git remote -v
upstream    https://github.com/erikmd/git-scripts.git (fetch)
upstream    https://github.com/erikmd/git-scripts.git (push)
```

− Source: https://stackoverflow.com/a/69410672/9164010

**Pull request merged**
