### PR TITLE
[ci] track vscoq on main

### PR DESCRIPTION
**Pull request by gares**
overlay:
- https://github.com/coq-community/vscoq/pull/702

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Why?

**Comment by gares** [comment]
It was planned to have a single branch upstream.
Since 8.19 is out I did some work to have `main` work with both 8.18 and 8.19 (and master).

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by rtetley** [comment]
@gares or someone else ? Could we get this moving along ? Is there something I can do ?

**Comment by SkySkimmer** [comment]
https://github.com/coq-community/vscoq/pull/702 should be merged first
Then rebase and we can merge this

**Comment by rtetley** [comment]
Ah I don't have the rights to do anything... @SkySkimmer is it okay if I just open a new PR from my fork ?

**Comment by SkySkimmer** [comment]
yes

**Comment by rtetley** [comment]
Cool ! Done here: https://github.com/coq/coq/pull/18643

**Pull request closed without merging**
