### PR TITLE
[DO NOT MERGE] Dummy PR for testing coqbot ci minimize

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
@coqbot CI minimize ci-fiat_crypto_legacy

**Comment by JasonGross** [comment]
> @coqbot CI minimize ci-fiat_crypto_legacy

**Comment by ppedrot** [comment]
I suspect we can close this PR.

**Comment by JasonGross** [comment]
I want to use this again, so I'm going to reopen

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
@coqbot inline-stdlib=yes resume ci minimize ci-compcert
```
(* -*- mode: coq; coq-prog-args: ("-emacs" "-q" "-w" "-undeclared-scope" "-w" "-omega-is-deprecated" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/lib" "compcert.lib" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/common" "compcert.common" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/x86_32" "compcert.x86_32" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/x86" "compcert.x86" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/backend" "compcert.backend" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/cfrontend" "compcert.cfrontend" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/driver" "compcert.driver" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/export" "compcert.export" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/cparser" "compcert.cparser" "-Q" "/github/workspace/cwd" "Top" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/Flocq" "Flocq" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/Ltac2" "Ltac2" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/MenhirLib" "MenhirLib" "-top" "compcert.lib.FSetAVLplus" "-native-compiler" "no") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 532 lines to 70 lines, then from 75 lines to 71 lines *)
(* coqc version 8.18+alpha compiled with OCaml 4.14.0
   coqtop version runner-9umwxc8t-project-6138686-concurrent-0:/builds/coq/coq/_build/default,(HEAD detached at 8e4b0d6) (8e4b0d6575c1d1af940a135d9e08a3680ec7e862)
   Expected coqc runtime on this file: 0.452 sec *)
Require Coq.FSets.FSetAVL.

Import Coq.FSets.FSetInterface.

Module Make(X: OrderedType).

Include FSetAVL.Make(X).

Module Raw := MSet.Raw.

Check Raw.L.MO.OrderTac.TO.eq_equiv.
(*
expected (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv)
but got  (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.X'.eq_equiv)

NB: About foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv. says
syntactically equal to foo.Make.X'.eq_equiv
*)
```

**Comment by JasonGross** [comment]
@coqbot inline-stdlib=yes resume ci minimize ci-compcert
```
(* -*- mode: coq; coq-prog-args: ("-emacs" "-q" "-w" "-undeclared-scope" "-w" "-omega-is-deprecated" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/lib" "compcert.lib" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/common" "compcert.common" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/x86_32" "compcert.x86_32" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/x86" "compcert.x86" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/backend" "compcert.backend" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/cfrontend" "compcert.cfrontend" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/driver" "compcert.driver" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/export" "compcert.export" "-R" "/github/workspace/builds/coq/coq-failing/_build_ci/compcert/cparser" "compcert.cparser" "-Q" "/github/workspace/cwd" "Top" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/Flocq" "Flocq" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/Ltac2" "Ltac2" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/MenhirLib" "MenhirLib" "-top" "compcert.lib.FSetAVLplus" "-native-compiler" "no") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 532 lines to 70 lines, then from 75 lines to 71 lines *)
(* coqc version 8.18+alpha compiled with OCaml 4.14.0
   coqtop version runner-9umwxc8t-project-6138686-concurrent-0:/builds/coq/coq/_build/default,(HEAD detached at 8e4b0d6) (8e4b0d6575c1d1af940a135d9e08a3680ec7e862)
   Expected coqc runtime on this file: 0.452 sec *)
Require Coq.FSets.FSetAVL.

Import Coq.FSets.FSetInterface.

Module Make(X: OrderedType).

Include FSetAVL.Make(X).

Module Raw := MSet.Raw.

Check Raw.L.MO.OrderTac.TO.eq_equiv.
(*
expected (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv)
but got  (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.X'.eq_equiv)

NB: About foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv. says
syntactically equal to foo.Make.X'.eq_equiv
*)
```

**Comment by JasonGross** [comment]
@coqbot inline-stdlib=yes resume ci minimize ci-color
```
(* -*- mode: coq; coq-prog-args: ("-emacs" "-q" "-w" "-undeclared-scope" "-w" "-omega-is-deprecated" "-Q" "/github/workspace/cwd" "Top" "-top" "compcert.lib.FSetAVLplus" "-native-compiler" "no") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 532 lines to 70 lines, then from 75 lines to 71 lines *)
(* coqc version 8.18+alpha compiled with OCaml 4.14.0
   coqtop version runner-9umwxc8t-project-6138686-concurrent-0:/builds/coq/coq/_build/default,(HEAD detached at 8e4b0d6) (8e4b0d6575c1d1af940a135d9e08a3680ec7e862)
   Expected coqc runtime on this file: 0.452 sec *)
Require Coq.FSets.FSetAVL.

Import Coq.FSets.FSetInterface.

Module Make(X: OrderedType).

Include FSetAVL.Make(X).

Module Raw := MSet.Raw.

Check Raw.L.MO.OrderTac.TO.eq_equiv.
(*
expected (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv)
but got  (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.X'.eq_equiv)

NB: About foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv. says
syntactically equal to foo.Make.X'.eq_equiv
*)
```

**Comment by JasonGross** [comment]
Tracking https://github.com/coq/coq/pull/16967#issuecomment-1348525437, btw

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
@coqbot inline-stdlib=yes resume ci minimize ci-metacoq
```
(* -*- mode: coq; coq-prog-args: ("-emacs" "-q" "-w" "-undeclared-scope" "-w" "-omega-is-deprecated" "-Q" "/github/workspace/cwd" "Top" "-top" "compcert.lib.FSetAVLplus" "-native-compiler" "no") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 532 lines to 70 lines, then from 75 lines to 71 lines *)
(* coqc version 8.18+alpha compiled with OCaml 4.14.0
   coqtop version runner-9umwxc8t-project-6138686-concurrent-0:/builds/coq/coq/_build/default,(HEAD detached at 8e4b0d6) (8e4b0d6575c1d1af940a135d9e08a3680ec7e862)
   Expected coqc runtime on this file: 0.452 sec *)
Require Coq.FSets.FSetAVL.

Import Coq.FSets.FSetInterface.

Module Make(X: OrderedType).

Include FSetAVL.Make(X).

Module Raw := MSet.Raw.

Check Raw.L.MO.OrderTac.TO.eq_equiv.
(*
expected (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv)
but got  (foo.Make.Raw.L.MO.OrderTac.TO.eq_equiv, foo.Make.X'.eq_equiv)

NB: About foo.Make.MSet.Raw.L.MO.OrderTac.TO.eq_equiv. says
syntactically equal to foo.Make.X'.eq_equiv
*)
```

**Pull request closed without merging**
