### PR TITLE
Add odoc warnings for empty packages.

### LINKED ISSUE #14055: Docs for Coq's API doesn't show up
Some pages of coq docs at [https://coq.github.io/doc/master/api/coq/](https://coq.github.io/doc/master/api/coq/) is not showing up.

Of the following,

 - coq dev
 - coq-core
 - coq-doc
 - coq-stdlib
 - coqide
 - coqide-server

only the pages for coq-core and coqide-server are appearing.

I guess some html files got removed somehow.

The site is being served using the files from [https://github.com/coq/doc](https://github.com/coq/doc), right?

I did a git bisect on that repo and when the repo went from commit [3e699607fd43265f7174896ca2c92ffd36e92be9](https://github.com/coq/doc/tree/3e699607fd43265f7174896ca2c92ffd36e92be9/master/api/coq) to commit [fc0810b9b58780346146f9d8591ebf29f9dfeb19](https://github.com/coq/doc/tree/fc0810b9b58780346146f9d8591ebf29f9dfeb19/master/api/coq), the html files stopped appearing.

Not sure if that's when it started to happen though.

But some links with the version number instead of 'master' seem to be working. Like https://coq.github.io/doc/v8.12/api/coq/Global/index.html

Or is the link with master intended to be a work in progress and the one to be read by users is the one with version number?

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

Fixes / closes #14055

### CODE REVIEW

**Comment by ejgallego** [comment]
Umm, @Zimmi48 we are missing the actual `mld` files, aren't we?

**Comment by Zimmi48** [comment]
Sorry, I forgot to `git add .`

**Comment by Zimmi48** [comment]
Here is the result: https://coq.gitlab.io/-/coq/-/jobs/1156498947/artifacts/_build/default/_doc/_html/index.html

**Comment by ejgallego** [comment]
Nice, we could add a link to `../coq-core` from the mld in Coq if desired, otherwise we can merge like this.

**Comment by Zimmi48** [comment]
I didn't know how links work in ocamldoc, that's why I didn't put any.

**Comment by ejgallego** [comment]
Quoting the docs:
```
{{: string }  text } | put a link to the given address (given as string) on the given text.
```
https://ocaml.org/manual/ocamldoc.html#s%3Aocamldoc-comments

**Comment by Zimmi48** [comment]
Thanks. Done.

**Review by ejgallego — APPROVED** [review]
Works fine, thanks!

We should improve the index pages quite a bit, but this is a start.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
