### PR TITLE
Reroot primitive arrays on access

### LINKED ISSUE #12694: [CI] base+async failure on bug_9517.v
I'm opening this issue to track this problem. I've seen this popping out from time to time, eg
  https://gitlab.com/coq/coq/-/jobs/639262132
error is
```
==========> TESTING bugs/closed/bug_9517.v <==========
File "./bugs/closed/bug_9517.v", line 12, characters 0-43:
Warning: This notation will not be used for printing as it is bound to a
single variable. [notation-bound-to-variable,parsing]
File "./bugs/closed/bug_9517.v", line 13, characters 14-15:
Error: Syntax error: [constr:expr] expected after '!' (in [constr:stmt]).

0m0.000000s 0m0.000000s
0m0.050000s 0m0.040000s
==========> FAILURE <==========
    bugs/closed/bug_9517.v...Error! (bug seems to be opened, please check)
```

I can't reproduce it locally and I can't see how "async-proofs" would have any impact on this test.

### LINKED ISSUE #12947: Broken complexity with primitive arrays
Semi-persistent arrays are supposed to have an amortized complexity of O(1) for get/set, as long as they are performed on the last accessed array or an older version of it (for backtracking algorithms). Obviously, the constant factor is large, but we should be able to perform millions of array accesses per second in Coq, maybe even tens of millions. Let us try it.

```coq
Require Import BinPos Int63 PArray.

Definition foo (n : positive) :=
  let a := make 2 0 in
  let b := Pos.iter (fun b => set b 1 1) a 100000 in
  let v := get b 0 in
  (* backtrack point here, we no longer access b but only a *)
  Pos.iter (fun v => v + get a 0) v n.

Time Eval vm_compute in foo 1.       (* 0.02s *)
Time Eval vm_compute in foo 10.      (* 0.05s *)
Time Eval vm_compute in foo 100.     (* 0.37s *)
Time Eval vm_compute in foo 1000.    (* 3.56s *)
```

Millions of operations per second? No, just 300.

Why? Because `get` and `set` do not reroot the array. So, the complexity is no longer O(1); it is O(n). Moreover, it also means that the garbage collector can no longer collect discarded arrays in a backtracking algorithm, causing the memory to fill without end.

Now, the savvy user notices that `Parray` provides an explicit `reroot` function. So, perhaps we can improve performances by using it? Let us put an explicit call at the position of the backtrack point:

```coq
Definition foo (n : positive) :=
  let a := make 2 0 in
  let b := Pos.iter (fun b => set b 1 1) a 100000 in
  let v := get b 0 in
  let a := reroot a in
  Pos.iter (fun v => v + get a 0) v n.
```

Guess what? Still 300 operations per second.

Why? Because the VM does not care. More precisely, Coq decided to compile it as follows:

```coq
(* decompiled from Set Dump Bytecode *)
Definition foo (n : positive) :=
  let a := make 2 0 in
  let a1 := reroot a in
  let b := Pos.iter (fun b => set b 1 1) a 100000 in
  let v := get b 0 in
  Pos.iter (fun v => v + get a1 0) v n.
```

So, the exceedingly savvy user decides to rewrite the code as follows:

```coq
Definition foo (n : positive) :=
  let a := make 2 0 in
  let b := Pos.iter (fun b => set b 1 1) a 100000 in
  let v := get b 0 in
  Pos.iter (let a := reroot a in fun v => v + get a 0) v n.
```

Eight millions of array accesses per second. Now we are talking.

So, there is at least one bug, and potentially two:
1. `get` and `set` should be O(1), that is, they should always reroot;
2. the VM should refrain from swapping let-in constructs, to preserve the sanity of users.

### PR DESCRIPTION
**Pull request by silene**
Semi-persistent arrays are supposed to have amortized O(1) complexity. This pull request ensures it, without forcing the user to litter its functions with explicit calls to `reroot`.

This brings the performances to 22 Mops for the testcase of #12947 (instead of just 300 ops).

Fixes #12947

### CODE REVIEW

**Comment by silene** [comment]
As pointed out to me, primitive arrays have never been released yet. So, there is no point in preserving compatibility or in having a changelog entry. So, I have removed the corresponding commits.

**Review by maximedenes — APPROVED** [review]
Looks very good to me, thanks!

**Comment by maximedenes** [comment]
Iris failure looks spurious.

**Comment by maximedenes** [comment]
@coqbot merge now

**Pull request merged**
