### PR TITLE
fix coq_makefile on cygwin

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes <https://coq.inria.fr/bugs/show_bug.cgi?id=5780>.

Cc @maximedenes

### CODE REVIEW

**Comment by maximedenes** [comment]
If I'm not mistaken, this is fully identical to #1142. But thanks for testing :)

**Comment by maximedenes** [comment]
Hum, in fact I'd prefer to include your comment and my commit message :)

**Comment by maximedenes** [comment]
Ok, let's take this version then!

**Comment by RalfJung** [comment]
Oh sorry I did not see that you had already submitted a MR.

I can change the commit message, or you can copy the comment, I don't care.

**Comment by maximedenes** [comment]
> I can change the commit message, or you can copy the comment, I don't care.

If you changed the commit message, it would be wonderful :)

**Comment by RalfJung** [comment]
Done.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
