### PR TITLE
More efficient handling of patterns in exact hints.

### PR DESCRIPTION
**Pull request by ppedrot**
We know that the pattern for exact hints, in discriminated mode, is always set to the type of the hint. Instead of turning it into a constr_pattern stored at runtime and then turned into a dnet pattern, we treat this specifically and rebuild the dnet pattern directly out of the hint type.

This should be both more efficient and less memory-hungry.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
```
│ coq-fiat-crypto-with-bedrock │ 6226.12  6242.26  -0.26 │ 27981343260109  28045082330640  -0.23 │ 51617301322396  51701147874723  -0.16 │ 2860096  3945568  -27.51 │
```
That 27% reduction in peak memory is probably real...

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
