### PR TITLE
Fix #[warnings] attribute in synterp phase

### LINKED ISSUE #17982: Documentation incorrectly claims that `#[warnings=...]` is supported by every command
> I think you should use a local `#[warning]` attribute instead:
> 
> [coq.github.io/doc/master/refman/language/core/basic.html#coq:attr.warnings](https://coq.github.io/doc/master/refman/language/core/basic.html#coq:attr.warnings)

Oh, wow, this is exactly what I was looking for.  But it doesn't work, and the documentation lies when it says "The following attribute is supported by every command:"
```coq
Module Foo. #[warnings="-notation-overridden"] Infix "+" := Nat.mul : nat_scope. End Foo.
(* Warning: This command does not support this attribute: warnings.
[unsupported-attributes,parsing,default] *)
```

_Originally posted by @JasonGross in https://github.com/coq/coq/issues/17920#issuecomment-1696543674_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17982

@gares I'd like to have this in 8.18.0 so we don't have a version with the bug

Overlays: (not needed anymore)
- https://github.com/coq-community/vscoq/pull/610
- https://github.com/ejgallego/coq-serapi/pull/355

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I guess this won't be practical in 8.18 due to the need for overlays.

**Comment by SkySkimmer** [comment]
Actually that was overcomplicated, we don't need overlays

**Comment by gares** [comment]
@coqbot merge now

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
@gares Should the release summary highlight this feature now that it is fixed?

**Pull request merged**
