### PR TITLE
Enable whitespace checking for new Sphinx file extensions.

### PR DESCRIPTION
**Pull request by SkySkimmer**
This affects both linter and pre-commit hook.

These (rst, g and tokens) are all the new file extensions I saw, are there others?

### CODE REVIEW

**Comment by ejgallego** [comment]
Please fix the Travis lint target.

**Comment by SkySkimmer** [comment]
Fixed (I just reran it, the issue was from master's side).

**Comment by ejgallego** [comment]
> Fixed (I just reran it, the issue was from master's side).

You mean you are pushing a rebased PR or do you want me to merge as-is?

**Comment by ejgallego** [comment]
I would feel more comfortable having the CI ran again [you know that stuff is tricky].

**Comment by SkySkimmer** [comment]
Merge as-is.

Gaëtan Gilbert

**Comment by SkySkimmer** [comment]
Travis merged for us.

Gaëtan Gilbert

**Comment by ejgallego** [comment]
> Travis merged for us.

Ah I missed that sorry; pushed!

**Pull request merged**
