### PR TITLE
Renaming ETProdReference/TTReference -> ETProdGlobal/TTGlobal for uniformity

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** micro-cleanup

A trivial mostly cosmetic PR.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
What's with the change in dpdgraph? The rest is due to missing overlays but this one seems new.

**Comment by herbelin** [comment]
> What's with the change in dpdgraph?

Strange. I don't see a reason how it could be connected. I'll rerun when the pending overlays will be pushed.

**Comment by ppedrot** [comment]
Weird eisenbug then.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
