### PR TITLE
Unification.make_pattern_test: use newer evar map instead of older

### LINKED ISSUE #15978: `set` tactic broken with universes
(with hott)
~~~coq
From HoTT Require Import Basics Spaces.Nat.

Open Scope nat_scope.

Definition stdfinset (n: nat) := { m : nat | True }.

Definition n_m_t (n:nat) : {m : nat & True}. Admitted.

Context (n : nat) (P : stdfinset (S n) -> Type) (H0 : forall k : stdfinset (S n), Decidable (P k)).

Lemma foo :
  match H0 (n_m_t n) with
  | inl _ | _ => 0
  end =
    match H0 (n_m_t n) with
    | inl _ | _ => 0
    end.
Proof.
  set (n_m_t := n_m_t _).
  reflexivity.
Defined.
~~~
we get an error at Defined
~~~
The term "let n_m_t := n_m_t n in 1" has type
 "match
    H0@{Top.stdfinset.27 Top.stdfinset.28 Top.stdfinset.29}
      (n_m_t@{Top.stdfinset.27 Top.stdfinset.28} n@{Top.stdfinset.41 Top.stdfinset.42
         Top.stdfinset.43})
  with
  | inl _ | _ => 0
  end =
  match
    H0@{Top.stdfinset.27 Top.stdfinset.28 Top.stdfinset.29}
      (n_m_t@{Top.stdfinset.27 Top.stdfinset.28} n@{Top.stdfinset.41 Top.stdfinset.42
         Top.stdfinset.43})
  with
  | inl _ | _ => 0
  end" while it is expected to have type
 "match
    H0@{Top.stdfinset.27 Top.stdfinset.28 Top.stdfinset.29}
      (n_m_t@{Top.stdfinset.27 Top.stdfinset.28} n@{Top.stdfinset.32 Top.stdfinset.33
         Top.stdfinset.34})
  with
  | inl _ | _ => 0
  end =
  match
    H0@{Top.stdfinset.27 Top.stdfinset.28 Top.stdfinset.29}
      (n_m_t@{Top.stdfinset.27 Top.stdfinset.28} n@{Top.stdfinset.41 Top.stdfinset.42
         Top.stdfinset.43})
  with
  | inl _ | _ => 0
  end".
~~~
If constant `n_m_t` is universe monomorphic there is no error.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15978

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@ppedrot Do you really expect a performance difference here?

**Comment by ppedrot** [comment]
No, but better safe than sorry. This is a tricky piece of code.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
