### PR TITLE
Remove leading pwd from pretty timing logs

### PR DESCRIPTION
**Pull request by JasonGross**
Some developments use absolute paths in `_CoqProject`.  This change adjusts the prettified timing tables so that the absolute prefix is stripped off the file names, resulting in a more readable output.

- [x] Added / updated **test-suite**.
- [x] Added **changelog**

### CODE REVIEW

**Comment by gares** [comment]
could you add a test? either by calling the python script on some fabricated input, or a standard coq_makefile test

**Comment by JasonGross** [comment]
Test added

**Comment by JasonGross** [comment]
Er, wait, I need to fix the test

**Comment by JasonGross** [comment]
Test fixed

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@ppedrot please check the milestone

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
I don't think this qualifies for backport.

**Pull request merged**
