### PR TITLE
Skip useless universe instances in lambda code.

### PR DESCRIPTION
**Pull request by ppedrot**
Experimental follow-up of #19014.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Hmm, it's probably native compilation which is lacking the same tweak. It shouldn't affect the bench though.

**Comment by ppedrot** [comment]
Total vo size change:
```
TOTAL 1417049696 1412611262 -4438434 (-0%)
```
Top reductions in vo size:
```
coq-hott/./theories/Spaces/Spheres.vo 945071 876961 68110 (-7%)
coq-hott/./theories/Colimits/Sequential.vo 1327553 1258231 69322 (-5%)
coq-hott/./theories/Colimits/Colimit_Flattening.vo 1074070 990123 83947 (-8%)
coq-hott/./theories/WildCat/DisplayedEquiv.vo 991217 877472 113745 (-11%)
coq-hott/./theories/WildCat/Monoidal.vo 1860169 1743250 116919 (-6%)
coq-hott/./theories/Pointed/Core.vo 2699751 2428310 271441 (-10%)
coq-hott/./theories/Homotopy/CayleyDickson.vo 1865968 1484333 381635 (-20%)
coq-category-theory/./Functor/Construction/Product/Monoidal.vo 4859567 4298664 560903 (-12%)
coq-hott/./theories/Spaces/Torus/TorusEquivCircles.vo 3653883 3042063 611820 (-17%)
coq-hott/./theories/WildCat/Products.vo 4393617 3586991 806626 (-18%)
```
Weirdly enough there are also non-trivial vo files increase, here is the leaderboard:
```
coq-mathcomp-ssreflect/./mathcomp/ssreflect/order.vo 12234605 12254713 -20108 (0%)
coq-fiat-crypto-with-bedrock/./src/Assembly/Symbolic.vo 10404389 10421825 -17436 (0%)
coq-color/./Coccinelle/examples/cime_trace/rpo_extension.vo 6991132 7006289 -15157 (0%)
coq-color/./Term/Lambda/LSystemT.vo 8438484 8451867 -13383 (0%)
coq-color/./Term/Lambda/LCompClos.vo 7873351 7886385 -13034 (0%)
coq-fiat-crypto-with-bedrock/./src/Util/FSets/FMapOption.vo 3290478 3300060 -9582 (0%)
coq-metacoq-template/./common/theories/EnvironmentTyping.vo 10671589 10680754 -9165 (0%)
coq-fiat-crypto-with-bedrock/./src/Util/FSets/FMapProd.vo 4016067 4024919 -8852 (0%)
coq-fiat-crypto-with-bedrock/./src/Util/FSets/FMapSum.vo 3208270 3216823 -8553 (0%)
coq-mathcomp-algebra/./mathcomp/algebra/ssralg.vo 6579409 6587549 -8140 (0%)
```

**Comment by ppedrot** [comment]
Not sure it's really worth it. It's making the code more complex, and I have to fix native, but there is no crazy gain like the one we got by skipping irrelevant arguments.

**Comment by SkySkimmer** [comment]
>Total vo size change:

Should we only consider developments which use univ poly? ie hott and category theory

**Comment by ppedrot** [comment]
On HoTT and category-theory, the diff is
```
TOTAL 113659613 108792202 -4867411 (-4%)
```

**Comment by ppedrot** [comment]
Ping @silene, do you think this is still worth it?

**Comment by SkySkimmer** [comment]
I think the vo size reduction is worth it alone.

Also it seems we don't have anyone using the VM on univ poly inputs large enough for performance to matter, but all these removed instances probably mean a lot of removed callbacks to ocaml subst_instance_instance.

**Comment by ppedrot** [comment]
The current code is a bit ugly, I think I need to clean the API first.

**Comment by silene** [comment]
From a quick glance, the concept seems quite similar to your other pull request about rels. Could not we use the exact same machinery? That is, treat the universe instance as a standard function argument and optimize it the same way other arguments are?

**Pull request closed without merging**
