### PR TITLE
Remove the deprecated elimtype and casetype tactics.

### PR DESCRIPTION
**Pull request by ppedrot**
We also remove some internals API in the process.

### CODE REVIEW

**Review by jfehrle — APPROVED** [review]
LGTM

**Comment by ppedrot** [comment]
For some reason I hadn't written all necessary overlays for some devs. Given the time it takes for sf to integrate such changes, I'm turning this in a draft for the time being.

**Comment by SkySkimmer** [comment]
https://github.com/DeepSpec/sfdev/pull/541 ("Slf upgrade 2023 07" by @charguer, opened 4 days ago) removes the use of these tactics among other deprecated things

I don't know how long we should expect until it's merged and the public repo updated.

**Comment by charguer** [comment]
Pinging @bcpierce00 to notify that you would like to see my PR merged soon---my PR shouldn't be long too review, it's essentially just a version upgrading.

**Comment by bcpierce00** [comment]
I've merged Arthur's PR and am re-exporting the public version of SF (just the PLF and SLF volumes - right?) now...

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
needs rebase

**Comment by ppedrot** [comment]
@SkySkimmer this is ready to merge.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
