### PR TITLE
[ci] [docker] elpi version 1.1.0

### PR DESCRIPTION
**Pull request by gares**
I've not updated yet the coq-master branch of coq-elpi yet, since it would break things unless this is merged.
Tell me how/when to do it.

### CODE REVIEW

**Comment by ejgallego** [comment]
We'll merge this as soon as CI passes.

**Comment by ejgallego** [comment]
You need to update the cache key in the .gitlab.yml file too. I know, it is a pain.

**Review by ejgallego — CHANGES_REQUESTED** [review]
Cache key should be updated in the .gitlab.yml file too. Once that is done, please launch a docker image build using the web interface

**Comment by gares** [comment]
I've updated the file, but I've no idea of where to go in order to build the docker image

**Comment by Zimmi48** [comment]
@gares Build launched. There is a button to manually start a pipeline. It allows you to override some environment variables, in this case `SKIP_DOCKER`.

**Comment by ejgallego** [comment]
That should be documentes in the README of the CI system tho.

**Comment by Zimmi48** [comment]
The image was built but the ci-elpi target didn't pass.

**Comment by ejgallego** [comment]
> The image was built but the ci-elpi target didn't pass.

Yeah maybe @gares you could add an overlay so we are sure this all works?

**Review by ejgallego — CHANGES_REQUESTED** [review]
Please add an overlay for coq-elpi so we know things work.

**Comment by gares** [comment]
> That should be documented in the README of the CI system tho.

Naive question: can't coqbot start this pipeline whenever a PR touches these files?

**Comment by ejgallego** [comment]
> Naive question: can't coqbot start this pipeline whenever a PR touches these files?

I guess so, many improvements over the current workflow would be possible.

**Review by ejgallego — APPROVED** [review]
LGTM, will merge in a few minutes so @gares you can update the branch when you want.

Note for the nex time that for commit naming we tend to use the prefix `[ci] [docker]` which makes it easier to filter/understand.

**Comment by ejgallego** [comment]
By the way, in the case of elpi it would be better that you version branches not only by coq branch, but by elpi branch. This way older PR would continue working in the CI when elpi is updated, and you wouldn't even need an overlay or a merge.

**Comment by Zimmi48** [comment]
@coqbot could do that. I have many improvements I should do. Unfortunately, all such improvements have been postponed because of the delays in the 8.8.2 release (I'm also starting to wonder if I'll have to take over the 8.9 release :disappointed:).

**Comment by silene** [comment]
I am still struggling to backport this commit. After pinning `coq-elpi` to the branch `coq-v8.9`, I get the following error:
```
CAMLC -c src/coq_elpi_builtins.mli
File "src/coq_elpi_builtins.mli", line 12, characters 2-63:
Error: Unbound module Extend.CustomConstraint
Makefile.coq:594: recipe for target 'src/coq_elpi_builtins.cmi' failed
```

**Comment by silene** [comment]
Forget about that, the test passes after #8456 has been backported , so I guess it is just a transient issue (from a chronological point of view).

**Pull request merged**
