### PR TITLE
Cleanup: stm functions which don't change the doc don't return it

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by gares — APPROVED** [review]
the doc argument is still, you could just remove it

**Comment by SkySkimmer** [comment]
What does "still" mean?

**Comment by gares** [comment]
Sorry, I wrote from my phone. I meant "silly". It was added by Emilio with a plan of making the STM support multiple documents, but that never happened (and will never happen). If you look at the API, the value is always ignored/dummy.

**Comment by ejgallego** [comment]
Yes, I added the parameter in a attempt to have the clients thread the state, unfortunately I didn't manage to make a lot of progress on threading the state internally.

IMVHO it is not a bad thing that clients do use a more "functional" API, but I guess it doesn't matter a lot.

**Comment by SkySkimmer** [comment]
So are we merging this or not?

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
