### PR TITLE
solving b1859

### PR DESCRIPTION
**Pull request by forestjulien**
Proposal to solve the bug [1859](https://coq.inria.fr/bugs/show_bug.cgi?id=1859).

### CODE REVIEW

**Comment by herbelin** [comment]
@jforest: looks pretty interesting  but could you give a little more context? What brings this delaying of the `clear`? Provide an example of what was not working without the change.

**Comment by herbelin** [comment]
OK, got it. So, maybe a comment on the code to tell that you keep the old `H` to remember the location of where the new `H` has to be reinserted.

**Comment by forestjulien** [comment]
Done

**Comment by tchajed** [comment]
Could you add the following test case to `test-suite/bugs/closed/1859.v` (adapted from Julien Narboux's original report):

```coq
Require Import Ring.
Require Import ArithRing.

Ltac ring_simplify_neq :=
  match goal with
  | [ H: ?X <> ?Y |- _ ] => progress ring_simplify X Y in H
  end.

Lemma toto : forall x y, x*1 <> y*1 -> y*1 <> x*1 -> x<>y.
Proof.
  intros.
  ring_simplify_neq.
  ring_simplify_neq.
  (* make sure ring_simplify has simplified both hypotheses *)
  match goal with
  | [ H: context[_*1] |- _ ] => fail 1
  | _ => idtac
  end.
  auto.
Qed.
```

**Comment by Zimmi48** [comment]
@forestjulien I've added the suggested test to your branch. I hope it's OK with you.

**Pull request merged**
