### PR TITLE
Fixes #15621 by expecting an unchecked fix to however be on an inductive type

### LINKED ISSUE #15621: Anomaly "conversion was given unreduced term (FLambda)." with Unset Guard Checking
~~~coq
Unset Guard Checking.

Fixpoint bad (x:unit -> nat) {struct x} : nat := x tt.

Check eq_refl : bad (fun _ => 0) = bad (fun _ => 1).
~~~

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** design, fix

Fixes #15621. See discussion there.

- [x] Added / updated **test-suite**.

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by Alizter** [comment]
@SkySkimmer good for 8.15?

**Comment by SkySkimmer** [comment]
I think no

**Comment by herbelin** [comment]
@SkySkimmer: I made a changelog in the "change" category of the kernel section. Is that what you intended? Feel free to amend directly the changelog if you intend a different one.

**Review by SkySkimmer — APPROVED** [review]

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
merging soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
