### PR TITLE
Remove the ssrsearch plugin and the ssr Search command (deprecated in 8.12)

### PR DESCRIPTION
**Pull request by jfehrle**
List of 8.14 deprecation removals is in #13538.

### CODE REVIEW

**Comment by CohenCyril** [comment]
I'm worried that the team @ssreflect-maintainers was not automatically added for reviews.

**Comment by jfehrle** [comment]
Just so I understand: Why hasn't mathcomp "extensively tested" 8.12 or 8.13?  At 1 version/6 months, "a couple versions" seems excessive.  Is there an upper bound on that?  I'll leave it to others to consider your request; I'm just doing the code changes for removals.

**Comment by CohenCyril** [comment]
> Why hasn't mathcomp "extensively tested" 8.12 or 8.13? At 1 version/6 months,

It's easy to check .v still compile, it's way harder to check puerely interactive command have the desired behavior, especially a command as complex as Search. It's quite difficult to list all the use cases.
We could have had output checks, but the syntax and the output style changed, so it would have been a lot of work to update it.
I guess one should do it anyway.
Few people would update to 8.12 because of the bug that has been recently fixed in 8.12.2 and 8.13 is just out... So not many users yet...

As for the timing, ssreflect Search has been there for 15 years AFAIK, so 1 year / 6 month is nothing for switching habits...

**Comment by Zimmi48** [comment]
As I said in the issue, it would be easy to revert the removal if big issues arose during the release cycle. But it's also easy to leave this PR waiting for about five months and to only merge it after the `v8.14` branching point. In which case, there would be 4 major releases and 2 full years with the deprecation before the removal.

**Comment by gares** [comment]
I would wait too, 8.12 became a viable option only recently because of a few nasty bugs. I would postpone to 8.15.

**Comment by jfehrle** [comment]
OK, let's do it in 8.15 then.  Perhaps one you gentlemen would create an 8.15 milestone and set it for this PR?

**Comment by Zimmi48** [comment]
Done. Note that it was as simple as typing "8.15+beta1" in the milestone field and clicking "create".

**Comment by jfehrle** [comment]
Thanks.  I thought there were some limitations on adding tags so I didn't even think to try that.

**Comment by ppedrot** [comment]
Since we've branched this should be ready to merge, up to a rebase.

**Comment by ejgallego** [comment]
Is this such a maintenance burden? There are still many users of this search command, so I dunno if its removal is warranted.

**Comment by Zimmi48** [comment]
Not a burden AFAICT but the goal is just to go toward more uniformity of the language and blocking the removal defeats this purpose.

>There are still many users of this search command

If you know them, can you ask them to open issues regarding why they didn't switch to the improved vanilla `Search` command yet?

**Comment by jfehrle** [comment]
Updated.

**Comment by jfehrle** [comment]
I think the failures are unrelated.

**Comment by ejgallego** [comment]
Let me cc some expert such as @strub to see what he thinks about @Zimmi48 questions

**Comment by Alizter** [comment]
@ejgallego @Zimmi48 Any updates with this?

**Comment by Zimmi48** [comment]
I'm in favor of merging, but I am not a user of this and never was, so this is still awaiting feedback from actual users to confirm that they switched over to the new mechanism.

**Comment by jfehrle** [comment]
Let's discuss in the next Coq call.

**Comment by SkySkimmer** [comment]
In the coq call it was said
>reconsider after Math-Comp meeting if we remove in 8.15.

When is the mathcomp meeting?

**Comment by ejgallego** [comment]
> When is the mathcomp meeting?

https://github.com/math-comp/math-comp/wiki#meetings says September 22nd

**Comment by gares** [comment]
See also: https://coq.zulipchat.com/#narrow/stream/237664-math-comp-users/topic/Removal.20of.20ssrsearch

**Comment by ejgallego** [comment]
A brief summary of the discussion on the meeting:

  + @ybertot : mostly satisfied with the new search [heavy user of Search]
    - maybe need a bit more of testing, still migration work in progress
    - I like I can filter easily using + and -
  + @cyrilcohen :
    - need for better syntax, for example for module qualification
    - new search should be good, modulo some syntax improvements
  + Sometimes it is hard to remember all the options, for example `head_concl:` vs `concl:` [pointed by several people] , a bit of a learning curve
  + generally people in the meeting has no complaints about the removal

Wait a bit more to provide definitive feedback from more users: open a thread on Zulip to consult more users: decision on 1 month

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Decision was taken at the weekly call yesterday that this PR was ready to go. Since there is no point in waiting any further, I am assigning and merging this PR right now. (CI failures unrelated, by the way).

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
This broken the docgram lint

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/15167

**Comment by ppedrot** [comment]
Whoops, my brain filtered out this real failure of the CI...

**Pull request merged**
