### PR TITLE
Replace all the CoInductives with Variants in the SSR plugin

### PR DESCRIPTION
**Pull request by pi8027**
**Kind:** cleanup.

see: https://github.com/math-comp/math-comp/pull/204

### CODE REVIEW

**Comment by ppedrot** [comment]
FTR, this is already part of #7536.

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
@Zimmi48 I was not complaining, merely pointing out this fact. Obviously it should be quicker to merge this PR.

**Comment by gares** [comment]
thanks @pi8027 !

**Comment by pi8027** [comment]
I didn't know about PR #7536. It seems good news for me! Thank you. @ppedrot

**Pull request merged**
