### PR TITLE
Fix error when building with Sphinx 4.5

### LINKED ISSUE #15956: LaTeX documentation doesn't build with Sphinx 4.5.0
#### Description of the problem

When integrating Sphinx 4.5.0 to Fedora, we uncovered an issue with coq: the LaTeX documentation doesn't build correctly (as it did with previous Sphinx versions).
The investigation results were evaluated as likely regression in Sphinx and reported as https://github.com/sphinx-doc/sphinx/issues/10332. The issue in question contains the insights from the RPM build.

#### Coq Version

coq 8.15.1

### PR DESCRIPTION
**Pull request by mitya57**
Ideally, we should stop monkey-patching and forward the fix to Sphinx upstream. I don't know details of the fix, so it would be better if the original author @cpitclaudel does this.

Fixes / closes #15956

### CODE REVIEW

**Comment by rwmjones** [comment]
I tested this patch and it fixes the problem we had building Coq in Fedora Rawhide with the latest Sphinx.

**Comment by Alizter** [comment]
@Zimmi48 what more needs to be done for this?

**Comment by rwmjones** [comment]
Fedora package patched: https://src.fedoraproject.org/rpms/coq/c/00b57637d8246e51eaae207988a3b922aaf19ede?branch=rawhide

**Comment by Zimmi48** [comment]
As the author of the PR wrote, this patch cannot be merged as is because it breaks the build with older Sphinx version. Probably it should be a draft PR to reflect this.

We are also looking for feedback from @cpitclaudel on this code to know how to proceed.

**Comment by SkySkimmer** [comment]
Can we do something like `if sphinx_version < whatever then previous code else new code`? (the `CR` is just `\n` so we don't need to import it)

**Comment by mitya57** [comment]
> Can we do something like `if sphinx_version < whatever then previous code else new code`? (the `CR` is just `\n` so we don't need to import it)

Done. I left CR imported to make it easier to compare patched function with original version.

**Comment by cpitclaudel** [comment]
I will try to look this weekend

**Review by Zimmi48 — APPROVED** [review]
FWIW, I am fine with merging this solution.

@cpitclaudel Did you get the chance to look at it?

**Comment by cpitclaudel** [comment]
Oh, the patch looks fine (thanks @mitya57!).  By look at I meant that I'd try to upstream the change, but since I haven't had time since two weeks ago it's unlikely that I'll find the time soon :/ @mitya57 would you fell comfortable opening a PR on the Sphinx side?

**Comment by cpitclaudel** [comment]
Thanks!

**Pull request merged**
