### PR TITLE
Check that convertible occurrences of a tactic-selected pattern are of the same type

### LINKED ISSUE #14609: Selection of pattern with Sprop subterms may break typing
#### Description of the problem

`Sprop` breaks the invariant that two convertible terms are of the same type. Here is an example with pattern selection where this leads to identify definitionally irrelevant proofs in incomparable types.
```
Inductive STrue : SProp := I.
Inductive SBool : SProp := T | F.

Axiom f : forall A, A -> unit.
Goal f _ (fun _ : unit => I) = f _ (fun _ : unit => T).
set (fun _ => _).
(* Ill-typed goal:
y := fun _ : unit -> T : SBool
============================
  f (unit -> STrue) y = f (unit -> SBool) y
*)
```

Note that on its side, ssr's `set` fails with a typing error.

#### Coq Version

Up to master.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

Note that this is broken by the use of SProp. See #14609.

More generally, that would be broken if conversion of implicit arguments were eventually dropped.

Fixes #14609.

- [X] Added / updated test-suite
- [X] Entry added in the changelog

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1403279334

**Comment by herbelin** [comment]
I'm not very used at interpreting benches. Times seem to indicate a (very) slight slowdown on the average, right?

I'm a bit missing imagination about what would be the best fix and/or if the fix should be optimized. @ppedrot, what do you think?

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   53.60    53.84  -0.45 │   147246317651    146833811295   0.28 │   191104443431    191107186889  -0.00 │  526684   526904  -0.04 │   0    0    nan │
│  coq-performance-tests-lite │ 1552.98  1556.74  -0.24 │  4332063942161   4343619013715  -0.27 │  7128998158961   7125905291726   0.04 │ 2084952  2085020  -0.00 │   0    0    nan │
│                   coq-color │  483.62   484.30  -0.14 │  1349693110902   1349345257766   0.03 │  1700170043206   1699149033330   0.06 │ 1153952  1155372  -0.12 │   0    0    nan │
│            coq-fiat-parsers │  581.81   582.58  -0.13 │  1628106231807   1629189839801  -0.07 │  2496860982434   2496298910614   0.02 │ 3485396  3485500  -0.00 │   0    0    nan │
│             coq-fiat-crypto │ 4806.54  4812.61  -0.13 │ 13339558057268  13369022069336  -0.22 │ 23621685942286  23627694618214  -0.03 │ 2228032  2216212   0.53 │   0    0    nan │
│                   coq-flocq │  146.25   146.42  -0.12 │   406308086781    406140088747   0.04 │   504983502870    504932530428   0.01 │  810580   810580   0.00 │   0    0    nan │
│                coq-rewriter │  666.47   666.88  -0.06 │  1849309969901   1851011502443  -0.09 │  2846051343212   2843846008207   0.08 │ 1074172  1074136   0.00 │   0    0    nan │
│              coq-verdi-raft │ 1099.08  1099.64  -0.05 │  3060239638549   3062416547630  -0.07 │  4325345250986   4324526529098   0.02 │  902668   902956  -0.03 │   0    0    nan │
│                  coq-stdlib │  413.51   413.58  -0.02 │  1156913376958   1156432875433   0.04 │  1474404967837   1474472030562  -0.00 │  594744   594784  -0.01 │   0    0    nan │
│                    coq-hott │  281.42   281.46  -0.01 │   773698844318    771580760259   0.27 │  1193747954599   1193797842555  -0.00 │  569476   569480  -0.00 │   0    0    nan │
│                    coq-corn │ 1471.01  1470.01   0.07 │  4096593757631   4094497897602   0.05 │  5896166580765   5896053715228   0.00 │  812840   812972  -0.02 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │  736.41   735.75   0.09 │  2051654349275   2048907817316   0.13 │  3214182688274   3214185566215  -0.00 │ 1073968  1073976  -0.00 │   0    0    nan │
│            coq-math-classes │  174.92   174.66   0.15 │   487487257689    486351848180   0.23 │   644403978049    644450121289  -0.01 │  481388   481364   0.00 │   0    0    nan │
│               coq-fourcolor │ 2545.92  2541.54   0.17 │  7096921260234   7083337604167   0.19 │ 12242384064442  12240854598222   0.01 │  731944   731904   0.01 │   0    0    nan │
│      coq-mathcomp-character │  150.04   149.69   0.23 │   417230327963    416228014796   0.24 │   585387454520    585360751928   0.00 │  732048   732036   0.00 │   0    0    nan │
│             coq-lambda-rust │ 1263.17  1259.46   0.29 │  3514426451218   3503730558898   0.31 │  5062223020913   5064145437265  -0.04 │ 1075604  1099828  -2.20 │   0    0    nan │
│        coq-mathcomp-algebra │  141.35   140.93   0.30 │   392947596090    391389846085   0.40 │   511412726380    511472022685  -0.01 │  553688   553548   0.03 │   0    0    nan │
│               coq-perennial │ 6831.36  6810.27   0.31 │ 19029953438691  18963806951060   0.35 │ 29106617674073  29103223461355   0.01 │ 3126764  3085680   1.33 │   0    0    nan │
│                 coq-coqutil │   58.88    58.68   0.34 │   163192676598    163180534427   0.01 │   215079997694    214583661920   0.23 │  601256   600740   0.09 │   0    0    nan │
│                 coq-unimath │ 4302.69  4287.72   0.35 │ 11971350389103  11931342502801   0.34 │ 22915134816977  22900661674207   0.06 │ 3266716  3266644   0.00 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1051.20  1047.50   0.35 │  2928161934000   2917812227151   0.35 │  4665473906905   4665504040731  -0.00 │  904684   904540   0.02 │   0    0    nan │
│                 coq-bignums │   55.63    55.41   0.40 │   153466140371    153541086364  -0.05 │   206871206544    206848119552   0.01 │  464324   464136   0.04 │   0    0    nan │
│               coq-fiat-core │  108.84   108.40   0.41 │   306946091661    305726873622   0.40 │   414315488368    412874005570   0.35 │  480852   480996  -0.03 │   0    0    nan │
│       coq-mathcomp-solvable │  169.80   169.00   0.47 │   472330720553    470636989529   0.36 │   669487046908    669504318974  -0.00 │  673960   673972  -0.00 │   0    0    nan │
│                coq-bedrock2 │  310.98   309.25   0.56 │   862409698880    858082385999   0.50 │  1508399188747   1507628239570   0.05 │  799896   800036  -0.02 │   0    0    nan │
│                   coq-verdi │   98.11    97.56   0.56 │   270164100285    268878806855   0.48 │   380423334412    379381415051   0.27 │  544080   544116  -0.01 │   0    0    nan │
│       coq-mathcomp-fingroup │   48.32    48.04   0.58 │   133515678319    133031282067   0.36 │   186671489122    186723591251  -0.03 │  481000   481576  -0.12 │   0    0    nan │
│          coq-mathcomp-field │  222.21   220.91   0.59 │   617702031482    614739404834   0.48 │   940570049067    940600830928  -0.00 │  667484   667956  -0.07 │   0    0    nan │
│                  coq-geocoq │ 1338.70  1330.62   0.61 │  3729778125647   3708473983071   0.57 │  5469465470858   5468329299130   0.02 │  983708   981424   0.23 │   0    0    nan │
│       coq-engine-bench-lite │  313.08   311.12   0.63 │   880749621163    876267142608   0.51 │  1640376559496   1641073195353  -0.04 │ 3505896  3506096  -0.01 │   0    0    nan │
│              coq-coquelicot │   68.97    68.38   0.86 │   187534207151    186528365933   0.54 │   240466566836    239519795035   0.40 │  557616   557652  -0.01 │   0    0    nan │
│                coq-coqprime │  329.49   326.63   0.88 │   915295913313    906900776549   0.93 │  1596294271261   1595336976220   0.06 │  919816   919056   0.08 │   0    0    nan │
│                    coq-core │  107.49   106.01   1.40 │   296576494616    295971679037   0.20 │   458709823265    458645491969   0.01 │  290904   290860   0.02 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Looks like pure noise to me.

**Comment by herbelin** [comment]
Well, ok, then adding a change log and this should be ready.

**Comment by herbelin** [comment]
Needs an assignee.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I let @silene decide if the milestone is OK.
@coqbot merge now

**Pull request merged**
