### PR TITLE
Remove Regular Subst Tactic compat flag.

### PR DESCRIPTION
**Pull request by Zimmi48**
This compat flag was introduced in 8.5 and turned on by default in 8.6. I would like to assess the compatibility breakage that deprecating it and eventually removing it would incur.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Only two projects are affected: geocoq and verdi_raft. This seems very reasonable, so worth pursuing.

**Comment by herbelin** [comment]
From memory, one development which used _a lot_ of "non regular" `subst` was the contrib intuitionistic-nuprl. Quickly looking at [vrahli/NuprlInCoq](https://github.com/vrahli/NuprlInCoq), it seems that no occurrences of `Regular Subst Tactic` occur (anymore) though.

**Comment by ppedrot** [comment]
GeoCoq is the last user of this compat flag in our CI it seems, and I've just submitted the PR GeoCoq/GeoCoq#34 to fix this. After it is merged, it should be easy to finish this PR.

**Comment by Zimmi48** [comment]
Verdi Raft is still failing it seems.
Anyway, to merge this PR after the end-of-the-month `v8.14` branching, we should get a deprecation PR merged in before.

**Comment by ppedrot** [comment]
Here you go: #14336.

**Comment by ppedrot** [comment]
It turns out it's actually the verdi dev that uses this flag, not verdi-raft. We can't tell the difference from the CI failure alone since they are compiled together. I have opened [a PR](https://github.com/uwplse/verdi/pull/128) to remove it.

**Comment by ppedrot** [comment]
Since the 8.14 branch this is now ready to merge, and thus needs an assignee.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
