### PR TITLE
Remove transitive dependencies from vo summaries.

### PR DESCRIPTION
**Pull request by ppedrot**
This information can be recomputed, and keeping it results in a quadratic blowup of the vo summary field. This is more tricky than it sounds because the precise topological order of require matters, as some superglobal libobjects are not idempotent. We keep track of the explicit dependencies to be able to recompute the precise order we obtained after the chain of requires.

As a result, we could still have a quadratic blowup in the worst case, but this patch makes it unlikely in the average case.

Depends on:
- #19113

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
test suite per file diffs extracted from the bench: https://gist.github.com/SkySkimmer/defac0e9f2a601053a4e80d27f60be92
This means the reported -14% memory usage is from success/bteauto which only requires Program.Tactics, so probably spurious.
Timing diffs appear to be distributed over mostly coqchk calls, I guess checking a file with Require Reals in -norec mode takes about -0.3s less.

**Comment by ppedrot** [comment]
@SkySkimmer are you talking about the other PR? This one shouldn't affect the checker.

**Comment by SkySkimmer** [comment]
It's from this bench https://gitlab.inria.fr/coq/coq/-/jobs/4394147 (I used my ssh access to get the data)
that's this PR AFAICT

**Comment by ppedrot** [comment]
Leaderboard:
```
coq-fiat-crypto-with-bedrock/./src/PerfTesting/PerfTestPrint.vo 52008 647 51361 (-99%)
coq-fiat-crypto-with-bedrock/./src/PerfTesting/PerfTestSearch.vo 52011 650 51361 (-99%)
coq-fiat-crypto-with-bedrock/./src/PerfTesting/PerfTestSearchPattern.vo 52032 671 51361 (-99%)
coq-fiat-crypto-with-bedrock/./src/Bedrock/End2End/X25519/EdwardsXYZT.vo 1567407 1514873 52534 (-3%)
coq-fiat-crypto-with-bedrock/./src/Bedrock/End2End/X25519/MontgomeryLadder.vo 454802 402016 52786 (-12%)
coq-fiat-crypto-with-bedrock/./src/Bedrock/End2End/X25519/GarageDoor.vo 3067037 3013754 53283 (-2%)
coq-fiat-crypto-with-bedrock/./src/Bedrock/End2End/X25519/GarageDoorTop.vo 578881 524928 53953 (-9%)
coq-fiat-crypto-with-bedrock/./src/Bedrock/End2End/X25519/MontgomeryLadderRISCV.vo 292361 235801 56560 (-19%)
coq-unimath/./UniMath/All.vo 63657 3265 60392 (-95%)
coq-fiat-crypto-with-bedrock/./src/Bedrock/Everything.vo 72379 10818 61561 (-85%)
TOTAL 1171673392 1105733757 -65939635 (-6%)
```

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
