### PR TITLE
[stdlib] Remove deprecated module Zlogarithm

### PR DESCRIPTION
**Pull request by vbgl**
This module has been deprecated for quite a long time (since version 8.4). Removing it is a step towards #7878.

This still needs a simple overlay for CompCert/VST that I’ll submit if this PR gets some support.

Update: overlay for CompCert at https://github.com/AbsInt/CompCert/pull/286 and for VST at https://github.com/PrincetonUniversity/VST/pull/326

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
I don't mind the removal, especially if the porting is straightforward. Note that we don't have yet module-wide deprecation attributes, so some users could have been unaware of the deprecation if they hadn't read doc. But again, that doesn't matter too much if the porting is straightforward.

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
@herbelin you're the owner here.

**Comment by xavierleroy** [comment]
I removed the dependency on Zlogarithm in CompCert.  I still think the way you're going about this removal is wrong.

> Note that we don't have yet module-wide deprecation attributes, 

Then put deprecated attributes on every definition and theorem of the module.  How hard is this?

> so some users could have been unaware of the deprecation if they hadn't read doc.

Some users, yeah.  Once a proof works, nobody goes back to the comments of the stdlib modules at every release to make sure someone hasn't decided to deprecate it.  I don't see any mention of this deprecation in the CHANGES file either.  You're really expecting your users to be clairvoyant?

**Comment by vbgl** [comment]
> Then put deprecated attributes on every definition and theorem of the module.  How hard is this?

I guess we don’t have deprecation attributes for definitions or for
theorems…

**Comment by xavierleroy** [comment]
I'm pretty sure I've seen Coq emit warnings like "Foo.bar is deprecated".  I have no idea how those are implemented and generated, but the corresponding mechanism is what I meant by "deprecated attributes".

**Comment by maximedenes** [comment]
> I guess we don’t have deprecation attributes for definitions or for theorems…

I just tested, and it seems worse than that: the `deprecated` attribute is accepted on definitions but apparently has no effect.

> I'm pretty sure I've seen Coq emit warnings like "Foo.bar is deprecated". I have no idea how those are implemented and generated, but the corresponding mechanism is what I meant by "deprecated attributes".

Those were probably so-called "syntactic definitions" (declared using the `Notation` command). I'll make sure we support deprecation on all main constructions (I did it for tactics already), so that we avoid this kind of rough transitions in the future.

Honestly, I'm not sure even developers were aware of this particular deprecation (at least, I wasn't).

**Comment by ejgallego** [comment]
@xavierleroy you are right; we don't have the means to do well but IMHO we are aware of the many shortcomings we have w.r.t. compatibility, some of them are just not easy to fix due to real technical problems / lack of manpower [see for example https://github.com/coq/coq/issues/9664 ] For example we don't even have a unification test suite or a way to version the engine.

So for now we kind of piggyback on the CI testing and "continuous" development, which indeed is time-consuming and confusing for users; but rest assured that we are not satisfied with it.

**Comment by Zimmi48** [comment]
> I'll make sure we support deprecation on all main constructions (I did it for tactics already), so that we avoid this kind of rough transitions in the future.

Thanks for this @maximedenes. See also my requests in #6840 (remove the infrastructure for "compat notations" and replace it with deprecation attributes) and in #8382. This would be two issues that you would be closing by working on this.

If this is easy enough to do in 8.10, then we could consider adding these deprecation warnings for all the definitions and theorems of `Zlogarithm` in 8.10 and merge the present PR only after the branching.

**Comment by vbgl** [comment]
This PR is now ready. May someone please assign and merge? Thanks.

**Comment by ppedrot** [comment]
@herbelin is the natural assignee, but just in case, I can also perform the merge.

**Comment by herbelin** [comment]
Sorry, I'm coming late to the discussion. Was an agreement obtained?

I don't see a warning introduced in 8.10, right? So do we estimate (@xavierleroy included) that the number of incompatibilities in the wild, based on the CompCert CI sample, shall be too few to be worth a (at the current time not so cheap to implement) formal deprecation phase? Or do we add support for deprecating definitions and/or modules (what shall have to be done anyway at some time I guess) and use it for deprecating `Zlogarithm` and `Zsqrt_compat` in 8.10?

(Sorry in advance if I missed discussions which would already have given an answer to the above question.)

**Comment by ejgallego** [comment]
@herbelin indeed I'd guess that the effort of introducing a deprecation phase wouldn't be worth delaying this PR for two releases, fortunately it seems that 8.11 will provide much better deprecation facilities so hopefully this is the last time a situation like this happens.

[by the way I see that math-comp has introduced a way to deprecate lemmas too]

**Comment by ejgallego** [comment]
What's holding this? I propose @vbgl rebases and we merge; indeed the path was not ideal but IMHO the tradeoff is in favor of merge.

**Comment by vbgl** [comment]
I’ve rebased and CI went through.

**Comment by ejgallego** [comment]
> I’ve rebased and CI went through.

Thanks @vbgl , I am assigning and I propose to merge soon unless anyone would like to propose a different plan.

**Pull request merged**
