### PR TITLE
[native_compute] Delay computations with toplevel match

### PR DESCRIPTION
**Pull request by maximedenes**
This is an easy improvement on examples like:

Fixpoint zero (n : nat) :=
  match n with
  | O => O
  | S p => zero p + zero p
  end.

Definition foo := if true then zero 100 else 0.

Eval native_compute in if true then 0 else foo.

I didn't add a test case, because our current testing infrastructure is too
fragile for that.

### CODE REVIEW

**Comment by ppedrot** [comment]
Why precisely this heuristic? We don't we do that for every non-value?

**Comment by ppedrot** [comment]
For the lack of contenders, I'm assigning myself.

**Comment by maximedenes** [comment]
> Why precisely this heuristic? We don't we do that for every non-value?

I believe this is what it was trying to implement, just missing the match case.

The real problem is that this test should be done after compilation, through a straightforward analysis of the generated code (whether it is a value or not). Here we are trying to guess the shape of the generated code from the input, which is ugly.

Nonetheless, this PR is an improvement.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
CI failures look spurious.

**Pull request merged**
