### PR TITLE
Fix #5081 by more fine-grained LtacProf recording

### LINKED ISSUE #5081: LtacProf associates times spent in tactic-evaluation-phase with the wrong tactic
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5081
From: @JasonGross
Reported version: 8.6
CC:   @ppedrot, @gares

### PR DESCRIPTION
**Pull request by JasonGross**
To fix #5081, that LtacProf associates time spent in tactic-evaluation
with the wrong tactic, I added two additional calls to the profiler
during tactic evaluation phase.  These two calls do not update the call
count of the relevant tactics, but simply add time to them.

Although this fixes #5081, it introduces a new bug, involving tactics
which are aliases of other tactics, which I am not sure how to fix.
Here is the explanation of the issue, as I currently understand it (also
recorded in a comment in `profile_ltac.mli`):

Ltac semantics are a bit insane.  There isn't
really a good notion of how many times a tactic has been "called",
because tactics can be partially evaluated, and it's unclear
whether the number of "calls" should be the number of times the
body is fetched and unfolded, or the number of times the code is
executed to a value, etc.  The logic in `Tacinterp.eval_tactic`
gives a decent approximation, which I believe roughly corresponds
to the number of times that the engine runs the tactic value which
results from evaluating the tactic expression bound to the name
we're considering.  However, this is a poor approximation of the
time spent in the tactic; we want to consider time spent evaluating
a tactic expression to a tactic value to be time spent in the
expression, not just time spent in the caller of the expression.
So we need to wrap some nodes in additional profiling calls which
don't count towards to total call count.  Whether or not a call
"counts" is indicated by the `count_call` boolean argument.

Unfortunately, at present, we can get very strange call graphs when
a named tactic expression never runs as a tactic value: if we have
`Ltac t0 := t.` and `Ltac t1 := t0.`, then `t1` is considered to
run 0(!) times.  It evaluates to `t` during tactic expression
evaluation, and although the call trace records the fact that it
was called by `t0` which was called by `t1`, the tactic running
phase never sees this.  Thus we get one call tree (from expression
evaluation) that has `t1` calls `t0` calls `t`, and another call
tree which says that the caller of `t1` calls `t` directly; the
expression evaluation time goes in the first tree, and the call
count and tactic running time goes in the second tree.  Alas, I
suspect that fixing this requires a redesign of how the profiler
hooks into the tactic engine.

Notes:
1. Because there are two additional calls to the profiler in tactic expression evaluation, I'd like to get this benched.  (They should be no-ops, and add negligible overhead, but we should be sure.)  How can I get this to happen?  (This is why I've added the `needs: benchmarking` tag.)
2. Most of the diff is test-suite and comments; the actual code changes are +9,-7

### CODE REVIEW

**Comment by ppedrot** [comment]
> Ltac semantics are a bit insane.

I can only support this affirmation.

**Comment by maximedenes** [comment]
> I can only support this affirmation.

What about this PR. Do you approve it?

**Review by ppedrot — APPROVED** [review]
The whole endeavour of trying to get a sound timing semantics for Ltac seems completely crazy to me, as highlighted by @JasonGross himself. That said, I understand that the current profiling mechanism is *good enough* for the purposes of its users. The proposed PR doesn't seem wrong in that respect. Thus, I think it should make it into Ltac.

This doesn't prevent me thinking that we're all losing a lot of time working around the whole Ltac nonsense that could be used for better purposes.

**Comment by herbelin** [comment]
> This doesn't prevent me thinking that we're all losing a lot of time working around the whole Ltac nonsense that could be used for better purposes.

What do you think we should do?

For instance, at some time, I thought that `dependent destruction` could be rewritten in Ltac2 so that it supports e.g. more easily a `destruct_arg` à la `destruct`/`induction`. But maybe this is not the kind of thing that you have in mind since you seem to disrecommend custom notations for tactics.

So, can you explain a bit your vision so that we know where we can possibly help you?

**Review by gares — COMMENTED** [review]
I can't review this one: the code in profile_ltac is OK, but the part in the Ltac interpreter... I've no clue

**Pull request merged**
