### PR TITLE
Omega and romega know about context definitions (fix old bug 148)

### PR DESCRIPTION
**Pull request by letouzey**
When a context variable x is of the form `x := body : Z`, omega and romega are now made aware of this body. Technically, we push an equation `x = body` (either reified or not). For omega, this also works if `x` has type `nat`.

For compatibility, this extra feature of omega could be disabled via `Unset Omega UseLocalDefs`.
    
Caveat : for now, real let-ins deep inside goals or hyps aren't handled, use some "cbv zeta" reduction if you want to get rid of them. And context definitions whose types aren't Z or nat are ignored, some manual "unfold"  are still mandatory if expanding these definitions will help omega.

### CODE REVIEW

**Comment by JasonGross** [comment]
Please add the compatibility setting to Compat/Coq86.v

**Comment by maximedenes** [comment]
@letouzey This would deserve an entry in `CHANGES`.

**Comment by maximedenes** [comment]
Also, the option is not known in the compat file, because `Omega` is not loaded.

**Comment by letouzey** [comment]
- Rebased
  - a few words in CHANGES
  - a Require Omega in Compat/Coq86.v before setting the compatibility flag

**Comment by letouzey** [comment]
- Re-rebased
  - The few travis failures (fiat-crypto, math-comp, test-suite on Mac) don't seem to be related with omega

**Comment by Zimmi48** [comment]
Fiat-crypto is currently broken with trunk (a fix to funind was merged without passing a test). As for the rest, it could just be transient failures. Let's see what the build gives this time.

**Comment by JasonGross** [comment]
Can we either revert the funind patch or merge a fix to it before merging this? (@maximedenes?)  (Or could someone manually test fiat crypto against a build of this with a funind revert?) Fiat-crypto uses `omega ` in a bunch of places, and it would be nice to be sure that this doesn't break fiat-crypto in some unrelated place.

**Comment by maximedenes** [comment]
I'm going to revert the funind patch.

**Comment by maximedenes** [comment]
@letouzey Is the bignum fix backward compatible? If yes, can you merge it so that we can remove the overlay and merge this PR? Thanks!

**Comment by letouzey** [comment]
@maximedenes : no, the bignum fix isn't currently backward compatible, but I'm pretty sure it can be made so. Investigating that now.

**Comment by letouzey** [comment]
Ok, so bignum master now compiles with both version of omega (before and after this PR).
So I removed the overlay commit from this PR.

**Comment by maximedenes** [comment]
This PR seems to break `fiat-crypto`, but I'm not sure how. Maybe a rebase would be helpful to study the problem.

**Comment by letouzey** [comment]
Rebased as suggested.

**Comment by Zimmi48** [comment]
The breakage on fiat-crypto does still occur indeed:

```
File "./src/Util/Option.v", line 56, characters 4-107:
Error: No matching clauses for match.
```

**Comment by Zimmi48** [comment]
I guess this PR is unfortunately pending on someone helping debugging the breakage in fiat-crypto. Thus, tagging as `needs: help`.

**Comment by letouzey** [comment]
Gotcha! `Coq86` had unexpected side effects due to the `Require Omega` in it, put there to trigger the dynlink of the omega code, and hence make the boolean compat option appear. Even without `Import` in this `Require`, it was impacting a proof in `fiat-crypto/src/Util/Option.v`, apparently some subgoal order stuff. Maybe related with hints declared in `Omega.v` ? I do not know for sure, and I'm not sure I want to know. The easiest workaround was to put in `Coq86` the "Declare ML Module" instead of the full `Require`. We could also have put the compat option code outside the plugin (e.g. in Flags and Vernacentries), but that seems more intrusive.

Btw: rebased to today's master.

**Comment by letouzey** [comment]
Note: the travis failures are due to @ppedrot 's overlay for bignums not containing the omega fix I prepared some time ago. @maximedenes @Zimmi48 : could you please remove this overlay now that it isn't useful anymore ?

**Comment by letouzey** [comment]
Actually, the overlay removal has already been requested : PR #1117

**Comment by letouzey** [comment]
@maximedenes : at last, my travis is fully pleased by this PR.
Passed: letouzey/coq-wip#55 (omega-letin - 298b219).
Let's merge that in master before something else break !

**Comment by Zimmi48** [comment]
> Let's merge that in master before something else break !

Actually, if we decide that this is 8.8 material (and honestly, I think it is, sorry), then the compatibility settings should be in `Coq87.v`, not `Coq86.v`.

**Comment by letouzey** [comment]
Caramba, encore raté.
But yep, you're probably right.

**Comment by maximedenes** [comment]
Travis seems to have succeeded apart from a timeout in geocoq. So I guess we can now merge.

**Comment by Zimmi48** [comment]
@maximedenes Note how you should probably merge #1117 before, or this other PR won't have any content anymore.

**Pull request merged**
