### PR TITLE
Reduce the mess from elimination tactics

### PR DESCRIPTION
**Pull request by ppedrot**
This series of patches untangles a bit the situation we currently have with tactics taking elimination schemes as arguments. Among some added static invariants, we ensure in particular that barring the weird clause case, the only Case terms passed to the legacy refiner come from case-elimination building functions.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@herbelin would you assign?

**Comment by herbelin** [comment]
I approve the spirit of the PR but I would hardly find time to review in another way than superficially. However I'm ready to assign and trust i(f there are no objections on that way to proceed).

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
@coqbot merge now

**Pull request merged**
