### PR TITLE
Use \mathcal instead of \cal

### PR DESCRIPTION
**Pull request by SkySkimmer**
Apparently it's deprecated / doesn't always work, see
https://tex.stackexchange.com/questions/84041/why-does-calm-n-give-m

Tested both on my machine and on my gitlab.

See #9429 (we also need to fix the distributed file on the server).

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Hum. That's strange. Many jobs were skipped on GitLab CI, including the refman. But you said you've already tested this somewhere else, correct?

**Comment by Zimmi48** [comment]
BTW, the Azure failure is strange as well.

**Comment by SkySkimmer** [comment]
You can get the pdf from https://gitlab.com/SkySkimmer/coq/-/jobs/152960546/artifacts/raw/_install_ci/share/doc/coq/sphinx/latex/CoqRefMan.pdf?inline=false
Very strange CI behaviour for sure

**Comment by akr** [comment]
I think this also fixes an unintentional calligraphic font use in W-Global-Assum in HTML manual.

https://coq.inria.fr/distrib/current/refman/language/cic.html :

unintentional-calligraphy-in-html-manual

"E" in "c ∉ E" in W-Global-Assum is formatted in calligraphic font because
the effect of \cal retains after \Sort.

"E" in W-Global-Def doesn't use calligraphic font because it doesn't use \Sort.

So, it's better to update the HTML manual too.

**Comment by Zimmi48** [comment]
>So, it's better to update the HTML manual too.

For this, I will wait until we set up continuous deployment of the manual.

**Pull request merged**
