### PR TITLE
Add a PUSHACCMANY opcode.

### PR DESCRIPTION
**Pull request by silene**
Especially for symbols defined inside sections, callee functions might be invoked with the exact same arguments as caller functions. A similar situation happens with recursive functions that share most of their arguments across calls. This new opcode replaces a sequence of repeated `PUSH; ACC` opcodes with constant indices.

### CODE REVIEW

**Comment by silene** [comment]
@coqbot run full ci

**Comment by silene** [comment]
@coqbot bench

**Comment by silene** [comment]
The bench unfortunately failed to complete due to concurrent commits in the tested repositories, but it still gives an idea. As with #18964, the overall gain is minor, but specific developments nonetheless benefit heavily from it, e.g., `coq-hott` (18% reduction of the size of `Products.vo`), `coq-corn` (16% for `ACarith.vo`).

One I was not expecting is `coq-verdi-raft` (20% reduction for `RaftState.vo`), but it makes sense. Indeed, it implements the update pattern from OCaml (i.e., `{ record with field = value }`) for a large record with lots of section arguments, hence a naturally quadratic term, since they use non-primitive (I guess?) projections.

**Comment by ppedrot** [comment]
Let's retry @coqbot bench

**Comment by SkySkimmer** [comment]
Probably should rebase before retrying

**Comment by ppedrot** [comment]
Doesn't the bench script perform an auto-merge with master?

**Comment by SkySkimmer** [comment]
no

**Comment by silene** [comment]
After the merge of #18968, the benefits of this pull request increase notably, at least for `coq-hott`. For example, the size reduction of `Products.vo` now reaches 32% (instead of 18%), while it is 20% for `DisplayedEquiv.vo` (instead of 13%).

The `.vo` size reduction over the whole test-suite is 0.5%, with `coq-hott`, `coq-unimath`, and `coq-corn` being the biggest winners. Most developments do not see a single byte of difference.

@coqbot run fill ci

**Comment by silene** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@silene could you rebase on master? I'd like to see the effects of this PR after the merge of #19014.

**Comment by silene** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Doesn't seem to be very useful now. Leaderboard:
```
coq-metacoq-pcuic/./pcuic/theories/PCUICParallelReductionConfluence.vo 3371169 3334915 36254 (-1%)
coq-hott/./theories/Colimits/GraphQuotient.vo 595317 555941 39376 (-7%)
coq-corn/./reals/faster/ARArith.vo 503787 460949 42838 (-9%)
coq-metacoq-safechecker/./safechecker/theories/PCUICSafeRetyping.vo 3493744 3445252 48492 (-1%)
coq-hott/./theories/WildCat/DisplayedEquiv.vo 991217 937465 53752 (-5%)
coq-fiat-crypto-with-bedrock/./src/Util/FsatzAutoLemmas.vo 975316 886357 88959 (-9%)
coq-hott/./theories/WildCat/Monoidal.vo 1860169 1764618 95551 (-5%)
coq-hott/./theories/WildCat/Products.vo 4393617 4262042 131575 (-3%)
coq-metacoq-safechecker/./safechecker/theories/PCUICSafeConversion.vo 8255051 8069677 185374 (-2%)
coq-metacoq-safechecker/./safechecker/theories/PCUICSafeReduce.vo 7838949 7546806 292143 (-4%)
TOTAL 1378182007 1375499992 -2682015 (-0%)
```

**Comment by Janno** [comment]
> Doesn't seem to be very useful now.

Maybe your comment  is only about vo sizes but I just wanted to make sure the performance improvements don't get lost. At the usual going rate of 6 billion instructions per second this change yields an estimated ~5 minute overall improvement in the bench.

**Comment by proux01** [comment]
We can see a 5% decrease in CPU instructions for fourcolor (heavy VM user) but apparently doesn't really translates in time.

**Comment by ppedrot** [comment]
We can also merge, it's basically zero-cost in terms of maintenance.

**Review by ppedrot — APPROVED** [review]
FWIW.

**Comment by ppedrot** [comment]
Alea jacta est, @coqbot merge now

**Pull request merged**
