### PR TITLE
Mark #14610 and #14664 as present in 8.14.

### PR DESCRIPTION
**Pull request by silene**
This is an optimistically opened pull request, to get the CI to complete as soon as possible. The actual merge should be delayed until these pull requests are actually present on the 8.14 branch.

### CODE REVIEW

**Comment by silene** [comment]
The related pull requests are now part of the branch, so this is ready.

**Comment by Zimmi48** [comment]
@silene It seems like I missed this while reviewing #14490 but the current changelog is consolidated under a title "Changes in 8.14.0". While the `.0` release is expected to have very little change compared to the `+rc1` release, I still think that we should aim for accuracy and thus document this list as what is included in the `+rc1` release. Can you fix this before I merge (in a separate commit)?

**Comment by silene** [comment]
Are you sure? For the previous releases, we only wrote a separate changelog for betas, not for release candidates. So, naming the section "Changes in 8.14+rc1" does not seem consistent.

**Comment by Zimmi48** [comment]
It's been a very long time (8.5 or 8.6) since we didn't do release candidates, and at the time we also did beta releases. I guess we just interpreted differently what "release candidate" was supposed to mean in @gares's CEP. I didn't put as much meaning in this renaming as you did.

In the end, you're the RM so it's your call.

**Comment by Zimmi48** [comment]
In the interest of efficiency, I'll merge this PR and you can open another one if you adopt my interpretation.

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
