### PR TITLE
Use OCaml floating-point operations on 64 bits arch

### PR DESCRIPTION
**Pull request by proux01**
C functions were used for floating-point arithmetic operations, by
fear of double rounding that could happen on old x87 on 32 bits
architecture. This commit uses OCaml floating-point operations on 64
bits architectures.

The following snippet is made 17% faster by this commit.

```Coq
From Coq Require Import Int63 BinPos PrimFloat.
Definition foo n :=
  let eps := sub (next_up one) one in
  Pos.iter (fun x => add x eps) two n.
Time Eval native_compute in foo 1000000000.
```

(partly) addresses #13124

### CODE REVIEW

**Review by silene — APPROVED** [review]
Looks good to me. Moreover, it is not just `native_compute` that will benefit from it, but also the standard conversion/reduction machinery from the kernel.

However, I am curious. Does `[@@ocaml.inline always]` in a `.mli` file even make sense? Isn't it just ignored by the compiler?

**Comment by proux01** [comment]
> it is not just `native_compute` that will benefit from it, but also the standard conversion/reduction machinery from the kernel.

Sure, although I could not observe any noticeable performance impact here.

> However, I am curious. Does `[@@ocaml.inline always]` in a `.mli` file even make sense? Isn't it just ignored by the compiler?

No idea, I did not observe any difference puting/removing these annotations in the ml/mli, the compiler is probably inlining by itself anyway.

**Review by erikmd — APPROVED** [review]
Looks very good to me as well, thanks @proux01!

**Comment by erikmd** [comment]
@silene @proux0, which milestone would seem appropriate to you for this PR?

**Comment by silene** [comment]
This does not fix any soundness or usability bug. So, I don't see much benefit in backporting it.

**Comment by proux01** [comment]
I agree, 8.13 should be fine.
@silene, would you be the assignee?

**Comment by silene** [comment]
@coqbot: merge now

**Pull request merged**
