### PR TITLE
CI small fixes: git_download always cd, ci-sf no make clean

### PR DESCRIPTION
**Pull request by SkySkimmer**
See commits for details.

### CODE REVIEW

**Comment by ejgallego** [comment]
We used to do the `make clean` as otherwise Coq makefile would not be re-run again and that was creating some trouble, let me check if that's still the case.

**Comment by SkySkimmer** [comment]
@ejgallego ping

**Comment by ejgallego** [comment]
> @ejgallego ping

Sorry, it went under my radar after this hectic week; it seems that upstream tweak the make setup and we don't need to run clean anymore to have sf regenerate the makefile.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
