### PR TITLE
[sphinx] Fix regexp used in coqdomain.CoqtopBlocksTransform.split_lines

### LINKED ISSUE #12305: .. coqtop:: output regression
A recent PR (#12272) was intended to improve the `.. coqtop::` output. Unfortunately, between the first version of this PR (whose output I checked) and the one that was merged, a regression was introduced in the sentence splitting.
Compare the printing of the output in the example in the two links below:
- https://coq.gitlab.io/-/coq/-/jobs/542422443/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/vernacular-commands.html#coq:exn.module-section-qualid-not-found
- https://coq.gitlab.io/-/coq/-/jobs/544681807/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/vernacular-commands.html#coq:exn.module-section-qualid-not-found

In the second one nothing is split. All the outputs are at the end. Apparently, a double newline is necessary to have the sentences be split in the new version.

_Originally posted by @Zimmi48 in https://github.com/coq/coq/pull/12272#issuecomment-626387244_

Another example of bad output formatting was shown by @kyoDralliam: https://coq.gitlab.io/-/coq/-/jobs/548310062/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/ltac2.html#coq:cmd.ltac2-set

cc @mpu and @cpitclaudel

### PR DESCRIPTION
**Pull request by cpitclaudel**
**Kind:** bug fix / infrastructure.

Fixes / closes #12305 

This is the code I posted in #12305 ; @Zimmi48, you wrote:

> I tested the regexp proposed by @cpitclaudel but it doesn't seem to fix the issue of consecutive lines not being split.

Can you point to specific examples?  I think I'm missing something.

### CODE REVIEW

**Comment by Zimmi48** [comment]
The refman hasn't built yet but I remember I looked at examples in the description of the `Search` command. There were several queries on subsequent lines and their output was shown in a single block.

**Comment by cpitclaudel** [comment]
OK, happy to investigate specific examples if you find them (https://coq.gitlab.io/-/coq/-/jobs/584824501/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/vernacular-commands.html?highlight=searchhead#coq:cmd.searchhead seems fine)

**Comment by Zimmi48** [comment]
Maybe I hadn't applied the patch correctly then. Sorry for the false alarm.

**Comment by cpitclaudel** [comment]
(Maybe I'm looking at the wrong thing, too, that patch was written somewhat hastily)

**Review by Zimmi48 — APPROVED** [review]
I had a further look and everything looked OK. Thanks again!

**Pull request merged**
