### PR TITLE
reraise NotSameHead conversion errors in clenv_unify_binding_type

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #8202

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Maybe sensitive, but a priori ok.

**Comment by ppedrot** [comment]
Why don't we catch all possible exceptions within `ActualTypeNotCoercible` is another good question...

**Comment by herbelin** [comment]
Yes, same question in fact.

**Comment by ppedrot** [comment]
Should we close?

**Pull request closed without merging**
