### PR TITLE
Further clean up of the hint API

### PR DESCRIPTION
**Pull request by ppedrot**
Yet another cleanup PR that was found lying in my local branches.

### CODE REVIEW

**Comment by ppedrot** [comment]
Hm, there is something broken. Likely due to the removal of the `nf_evar` call, since this goes straight into `pattern_of_constr`.

**Comment by ppedrot** [comment]
Uh. Typeclass resolution is actually sensitive to the order in which the hypotheses are added to the local database. The more you know...

**Comment by mattam82** [comment]
It sure is, most recent first.

**Comment by ppedrot** [comment]
Indeed, upon reflection it is not surprising, but the fact we may depend on that silently for pure proof search seems a bit fragile.

**Comment by mattam82** [comment]
I think it has to be specified as it influences the final result by potentially instantiating some existentials with particular terms

**Comment by ppedrot** [comment]
Anyways this is now properly working after the hypotheses are added in the right order.

**Review by mattam82 — COMMENTED** [review]
Simple cleanup, looks good to me. Except I don't see why it is beneficial to pass the hyp ident rather than the declaration, and then lookup it's declaration?

**Comment by ppedrot** [comment]
@mattam82 this ensures that it does not depend on the type explicitly passed in the declaration. It could have been that the API takes a type that is not syntactically equal to the one already present in the environment.

**Comment by ppedrot** [comment]
@mattam82 this is ready to merge AFAICT.

**Review by mattam82 — APPROVED** [review]
Ok, thanks for the explanation.

**Comment by mattam82** [comment]
@coqbot merge now

**Pull request merged**
