### PR TITLE
[exninfo] Use record for backtrace storage in Exninfo

### PR DESCRIPTION
**Pull request by ejgallego**
I feel this is cleaner, side-effect free, and more according with what
other developments do [they define a type `Exn_with_backtrace.t`]

### CODE REVIEW

**Comment by ppedrot** [comment]
I actually find the code worse after this PR, and furthermore it always allocate 2 words for every `info` when the previous one was a direct integer...

**Comment by ejgallego** [comment]
> I actually find the code worse after this PR, and furthermore it always allocate 2 words for every `info` when the previous one was a direct integer...

I dunno; the motivation was a bit "should we get rid of the exninfo extensible part?" How would things look? So I wrote this little tree and it was rotting in my HD.

I'm not so worried about allocation, store can also allocate quite a bit and this PR improves `get`, I would not be surprised this is even an improvement.

I see your point so I dunno.

**Comment by ejgallego** [comment]
> I see your point so I dunno.

In fact I recall now, I submitted this tree as it provides a better implementation for `reify` in #11755

**Comment by ejgallego** [comment]
Yeah so I dunno @ppedrot , not a lot more to say than what written above. I still have a slight preference to use this by the reasons stated above, but if you don't like it please close.

**Comment by ppedrot** [comment]
I do agree that eventually we should get rid of the extensible nature of this data, and implement the enrichment where it belongs, but that requires way more work. In the meantime, I'd rather close this PR, even though I really don't have a strong opinion against it...

**Pull request closed without merging**
