### PR TITLE
Fix CI with parallel make (messed up dependencies)

### PR DESCRIPTION
**Pull request by SkySkimmer**
To avoid uselessly rebuilding CI developments (eg for Circle CI) we
used dummy files `_build_ci/.ci-foo.done`. To get reasonable looking
shell incatations the make targets are called `ci-foo` and are .PHONY.
To get reasonable looking dependencies in Makefile the `ci-foo`
targets depend on each other, ie `ci-foo: ci-bar`. Then
`ci-foo: _build_ci/.ci-foo.done`, but this allows starting foo before
bar is done leading to issues.

Instead we put the logic to avoid rebuilding stuff in the ci-wrapper
script.

We could instead make the `ci-foo` targets non PHONY and litter the
top level directory with empty files, but I prefer the present
solution.

### CODE REVIEW

**Comment by williammpratt** [comment]
This is so misguided in so many ways. I can't be bothered to explain the details.

Your quoting is also not correct. I have no interest in a conversation with the author. Please let a more experienced person go over the details if the author doesn't get the hint like this.

**Comment by ejgallego** [comment]
> Your quoting is also not correct. I have no interest in a conversation with the author. Please let a more experienced person go over the details if the author doesn't get the hint like this.

Given you attitude, we have certainly no interest in getting any further contribution from you. Please refrain from further comment, you way of speaking is not welcome here.

**Comment by maximedenes** [comment]
> I have no interest in a conversation with the author. Please let a more experienced person go over the details if the author doesn't get the hint like this.

Your behavior is clearly not welcome here. Please stop.

**Comment by williammpratt** [comment]
I remember the time that competent people worked on Coq. Too bad that's not the case anymore.

**Comment by SkySkimmer** [comment]
Another way is to have the dependencies in the makefile, not skip in the scripts, and if you want to skip dependencies you do the raw ci-wrapper calls instead of going through make (with circle as the only user for that currently).
We already need to duplicate the dependencies in the yml to get the artifact passing so it wouldn't be super bad I guess?
WDYT?

**Comment by ejgallego** [comment]
I need some time to think, the original intention was that `make` here would serve as a mere wrapper and the dependencies would be taken care by whatever tool the CI system was using [`opam`, our hacky shell scripts, etc...]

I am of course fine with any intermediate solution you would like to implement, as I am gonna be busy these days and likely won't have time to give any useful feedback.

**Comment by SkySkimmer** [comment]
New version calling ci-wrapper directly in Circle CI and unconditionally making all dependencies when called from make.
Had to mess around a bit to get NJOBS to work, see commit message and diff.

**Comment by SkySkimmer** [comment]
OK looks like it works now https://travis-ci.org/SkySkimmer/coq/jobs/319281285 (bignums job)

**Comment by SkySkimmer** [comment]
https://travis-ci.org/SkySkimmer/coq/jobs/319281286 color job (depends on bignums through makefile) is also working.

**Comment by maximedenes** [comment]
So should I merge this now, to resolve the CI situation?

**Comment by Zimmi48** [comment]
It seems to have mostly solved the issues (they are still some failures but probably unrelated). I guess if it needs more refinement it can be in a later PR.

**Comment by SkySkimmer** [comment]
Fixed the flock issue on circle. That leaves test suite failures on circle because it doesn't merge with master (the ltacprof_abstract thing) and equations failures everywhere which are unrelated.
Should be ready now.

**Comment by herbelin** [comment]
I feel like there was a panic because of these messages from @willampratt. It was admittedly unpleasant tone, but I disagree with deleting some of his messages and to block him (assuming a "his" from the "william" and from the picture at https://github.com/williampratt). I did not see anything wrong besides the tone.

I see no reason to avoid a discussion with him, even if it has to turn to the metalevel, i.e. on the relevance of the tone. If @williampratt uses this tone, there are maybe some reasons and my wish is to ask him about why. But by deleting his message and blocking him, no public discussion is possible anymore.

Sometimes I'm trolling or is negative myself, for some reason, and I may understand that, sometimes, some people may have also reasons to troll or be negative (e.g. because such person experienced repeated unwelcomedness or disrespect and moved in turn his/her own bad experience into aggressivity back). I'd like to understand these reasons because I'm sure that behind these reasons there are things to learn for myself (and possibly for the person).

**Comment by maximedenes** [comment]
You mentioned the wrong nickname again...

**Comment by Zimmi48** [comment]
Seriously @herbelin you should be more careful about this nickname issue. It has happened often that people that had nothing to do with us received an e-mail notification because they had been incorrectly mentioned.

**Comment by ejgallego** [comment]
> I did not see anything wrong besides the tone.

If that is the case, you need to look closer IMO. You should have all their messages in the mail. This was not about "tone", but about acceptable behavior.

> there are maybe some reasons and my wish is to ask him about why.

As far as I am concerned, it is not our role to understand the inner complexities of the trolling life, but to prevent abuse and disrespectful attitudes in the community. 

Really, there is nothing to see here wrt that troll, they didn't use "a bad tone", they were plainly disrespectful and insulted a core contributor and others.

Anyone who steps that line in the way they did, they should be aware of the strong response they will get.

**Comment by Zimmi48** [comment]
> 

Sometimes I'm trolling or is negative myself, for some reason, and I may understand that, sometimes, some people may have also reasons to troll or be negative (e.g. because such person experienced repeated unwelcomedness or disrespect and moved in turn his/her own bad experience into aggressivity back). I'd like to understand these reasons because I'm sure that behind these reasons there are things to learn for myself (and possibly for the person).

I've already privately expressed to you that trolling is never a good attitude and it never advances your cause. This code of conduct that we are discussing in #6477 should prohibit such behavior, including from core developers.

If @williammpratt has personal reasons for being negative, that's not our concern at all. We never interacted with them before and we are not responsible for what they may have lived. We are not their shrink.

**Comment by ejgallego** [comment]
> This code of conduct that we are discussing in #6477 should prohibit such behavior, including from core developers.

In fact core developers should be the ones held to the strictest of the standards in this regard.

Nobody is certainly perfect and we all have bad days, but certainly I would really appreciate people calling me out very loudly if I ever behave in an unwelcoming or non-respectful way.

**Pull request merged**
