### PR TITLE
Fix bench with and without split stdlib

### PR DESCRIPTION
**Pull request by SkySkimmer**
last time was #19347

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Not sure what's going on with the test suite, the current (previous?) way it works in the bench is kinda hackish so I guess I'll remove it from the benched packages until it can be improved.

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer is this ready?

**Comment by SkySkimmer** [comment]
yes

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
