### PR TITLE
Turn "overwriting previous delimiting key" and "hiding binding of key" messages into warnings

### LINKED ISSUE #8207: Overwriting previous delimiting key; Ambiguous paths ... are not official Warning messages
#### Description of the problem

Run this command (assuming the standard mathcomp installation for Coq 8.8.0):
`Require Import mathcomp.ssreflect.ssrbool.`

and I get these messages:
```
Overwriting previous delimiting key bool in scope bool_scope
Ambiguous paths:
[pred_of_mem_pred; sort_of_simpl_pred] : mem_pred >-> pred_sort
```

The word "Warning" does not appear, and in particular there is no indication of what Set Warning flag controls this message.

That part seems to be a Coq bug.  

For the ssreflect team, I wonder whether it's possible to write a line such as, 
`From mathcomp.ssreflect Require Import ssreflect seq ssrbool ssrnat ssrfun eqtype seq fintype finfun.
`
and not get any warning messages at all.  Am I doing something wrong?

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #8207

### CODE REVIEW

**Review by proux01 — APPROVED** [review]
LGTM, will merge when CI is green

**Comment by SkySkimmer** [comment]
This push just fixed the test suite output tests

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
