### PR TITLE
Change the default flag value for Refine.refine

### PR DESCRIPTION
**Pull request by ppedrot**
It used to be unsafe by default, which is probably **very bad**©. We turn it to safe by default, and explicit the old uses as well.

### CODE REVIEW

**Comment by aspiwack** [comment]
I don't think that it is a good idea. Because, in practice, you will have done type-checking prior to creating a term at all. There is no sense in type-checking yet a third time.

My advice is to either leave unsafe by default, or remove the default altogether (no optional argument) so that individual tactic _have_ to choose (I'm guessing that almost all of them will rightfully choose unsafe).

**Comment by maximedenes** [comment]
> in practice, you will have done type-checking prior to creating a term at all

This is *far* from being clear with the current API.

> or remove the default altogether

That could be an ok compromise.

**Comment by maximedenes** [comment]
> in practice, you will have done type-checking prior to creating a term at all

Or maybe we are not talking about the same thing. You will have done type-checking of what exactly?

**Comment by aspiwack** [comment]
I plead guilty of unclearness.

My point (and it's the reason for unsafe being the current default) is that a tactic will usually recover the conclusion, and craft a well-typed term of this type. This amounts to (manually) type-checking the partial proof. It's not necessary, but it's typical.

Making a call to refine safe is kind of a hack to force some extra unification to happen at refine time and I remember that in one case it actually changed the behaviour of a tactic (which was the reason to introduce the safe refine to begin with). But that would rather be considered a workaround of a bug rather than a desired behaviour.

An additional point I'd like to make is that "safe" refine doesn't actually make refine safer: it makes it fail earlier (an faulty refine will make the subsequent Qed fail). This is useful for debugging (it may actually be useful to have a debug mode where all refines are turned safe). But the tactics are usually not meant to produce faulty refines, and it is probably not a good idea to pay a significant computational cost in order to occasionally find a bug slightly easier.

**Comment by maximedenes** [comment]
So you are saying that for instance, when refining a proof term, a tactic is expected to insert the proper universe constraints manually in the current `evar_map`, without relying on `refine` to do it?

That sounds counter intuitive since, I believe, there is not even a wrapper for the pretyper in the monad (at least I coudn't find it: ` git grep type_of *.mli | grep tactic` gives nothing).

Are plugins expected to use `Unsafe.tclEVARS`?

**Comment by ppedrot** [comment]
+1 on making the `unsafe` named but mandatory.

**Comment by ejgallego** [comment]
Maybe `unsafe` is not the best name for the parameter?

**Comment by mattam82** [comment]
Maybe making a ~typecheck flag mandatory would be better indeed. And @maximedenes right that we're missing wrappers of type_of that have the side effect of adding the constraints/unifications results to the current evarmap in the API. Probably extensions of the Tacticals.New API are necessary, e.g a pf_type_of : constr -> types Proofview.tactic?

**Comment by ejgallego** [comment]
I really like @mattam82 suggestion of adding a mandatory `~typecheck` flag.

**Comment by ejgallego** [comment]
I don't understand why this has been delayed, AFAICS this amounts to a simple renaming that we should rather do in 8.7, right?

**Comment by maximedenes** [comment]
There was no opposition on this, so if anyone has the time to do it before I merge other PRs, we can integrate it.

**Comment by ejgallego** [comment]
Cool, it should be a 5-minute task.

**Comment by ppedrot** [comment]
Done.

**Pull request merged**
