### PR TITLE
Relax the pattern complexity test

### PR DESCRIPTION
**Pull request by JasonGross**
c.f. discussion at
https://github.com/coq/coq/pull/11177#issuecomment-559139477

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
That may still be too brittle; my preference would be to remove this test as it is basically useless.

The proper way to measure this is to have micro-benchmarks _à la_ core-bench, and compare among versions.

**Comment by Blaisorblade** [comment]
>  I do think that if occasionally Coq is just twice as slow (in user-time), even after correcting for CPU speed, that's a serious problem and we should figure out what's going on.)

If I may, BogoMIPS aren’t meant to be a serious benchmark about CPU speed, hence “bogus” is part of the name...

**Comment by JasonGross** [comment]
@ejgallego Feel free to make a PR reverting it; I would not object.

**Comment by ejgallego** [comment]
Let's see how the new threshold fares @JasonGross , even if not useful as a regression test per-se, it is good documentation for the day we have the cycles to implement micro-benchs.

**Pull request merged**
