### PR TITLE
Mini fixes in the tactics chapter

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix 

In passing, fixing two broken links and adding a few `:tacn:` hyperlinks.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
Thanks but may I request that #7301 is merged before? I can't be expected to rebase it once more. (Note that I ignore if these two PRs will conflict.)

**Comment by herbelin** [comment]
> Thanks but may I request that #7301 is merged before?

Sure. You may even cherry-pick this PR to yours if you want. I just checked and there was just one redundancy. I just removed it from my PR so that they can be merged.

**Comment by Zimmi48** [comment]
> You may even cherry-pick this PR to yours if you want.

I don't want to change it because then the tests would have to run again and this would delay merging once more ;-)

**Comment by Zimmi48** [comment]
There are fatal warnings when using a reference to an non-existing label. But apparently, there are no such warnings when the same happens with `:tacn:` or `:cmd:` or `:opt:`. Maybe because the first one is natively supported by Sphinx while the second one was added by @cpitclaudel?

**Comment by herbelin** [comment]
> Users can use it to better understand error messages they get. Currently the index is incomplete.
> What I propose is just to make it more complete. 

That's a good point. So, in the short term, maybe the index should be renamed into "Errors and Warnings (selection)"?

A quick grep gives 72 `CWarnings.create`, about 900 `user_err`, 190 errors centralized in `himsg.ml`, and about 200 errors or warnings in the index. So a ratio of 1/6, though probably among the most standard and thus useful ones.

So, we can maybe try to make progress. I don't know how we could organize but the experience showed that we can achieve big tasks collectively. So, assuming we add an argument to each `user_err` to tell to which command it pertains, that we add systematically in the source of the manual a link to a section listing the errors attached to each command, that we have a tool to automatically translate such `user_err` into a list of errors for the given command, and, finally, that we share the work for indexing all such `user_err`. Do you think it is feasible?

Additionally, that would help us to have more uniform error messages.

**Comment by cpitclaudel** [comment]
> Maybe because the first one is natively supported by Sphinx while the second one was added by @cpitclaudel?

That's right.  In coqdomain.py, can you try changing the roles section from this:

```
    roles = {
        # Each of these roles lives in a different semantic “subdomain”
        'cmd': XRefRole(),
        'tac': XRefRole(),
        'tacn': XRefRole(),
        'opt': XRefRole(),
        'thm': XRefRole(),
        'prodn' : XRefRole(),
        'exn': XRefRole(),
        'warn': XRefRole(),
```

to this?

```
    roles = {
        # Each of these roles lives in a different semantic “subdomain”
        'cmd': XRefRole(warn_dangling=True),
        'tac': XRefRole(warn_dangling=True),
        'tacn': XRefRole(warn_dangling=True),
        'opt': XRefRole(warn_dangling=True),
        'thm': XRefRole(warn_dangling=True),
        'prodn' : XRefRole(warn_dangling=True),
        'exn': XRefRole(warn_dangling=True),
        'warn': XRefRole(warn_dangling=True),
```

**Comment by Zimmi48** [comment]
This works! (some fatal warnings are emitted) Great!

**Comment by maximedenes** [comment]
@herbelin Would you mind rebasing this? It is next in my Sphinx-PRs list. Thanks!

**Comment by herbelin** [comment]
Rebase done.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
