### PR TITLE
Remove the deprecated Token module and port the corresponding code.

### PR DESCRIPTION
**Pull request by ppedrot**
This module was deprecated since camlp5 5.0 (!!). We simply remove the code and port the few depending loc in Coq.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Review by herbelin — APPROVED** [review]
I'll assume @ejgallego assigning for `gramlib` (not in `CODEOWNERS` yet apparently).

**Comment by ejgallego** [comment]
> I'll assume @ejgallego assigning for `gramlib` (not in `CODEOWNERS` yet apparently).

I think we said that @ppedrot would be the primary for gramlib, but I don't remember who could be the secondary. Maybe @herbelin would be a more sensible choice?

Anyways, I'll take this to be processed in the next round of merges as it is trivial.

**Comment by ejgallego** [comment]
I've relaunched the fiat build too, will merge ASAIC.

**Comment by ppedrot** [comment]
AFAIK the fix is still missing for Fiat.

**Comment by ejgallego** [comment]
> AFAIK the fix is still missing for Fiat.

I thought @JasonGross had merged it. Anyways `grep` on the fiat repos shows 0 occurences so I'll merge.

**Comment by Zimmi48** [comment]
You mentioned the idea of creating a parsing team. I think it is a great idea. It is just waiting to be done. Would you like me to create the team?

**Comment by ejgallego** [comment]
> You mentioned the idea of creating a parsing team. I think it is a great idea. It is just waiting to be done. Would you like me to create the team?

Would be great thanks @Zimmi48 ! What do @ppedrot @herbelin think?

**Comment by ppedrot** [comment]
I'm fine with it.

**Comment by herbelin** [comment]
> What do @ppedrot @herbelin think?

No opinion, but I'm ok to be in if one is created.

**Comment by Zimmi48** [comment]
Already done in #8924.

**Comment by ejgallego** [comment]
Thanks @Zimmi48

**Pull request merged**
