### PR TITLE
Allow feedback messages to carry a location.

### PR DESCRIPTION
**Pull request by ejgallego**
This is a try to provide a solution for the location reporting in the warnings machinery (c.f) #213 .

We extended the regular feedback message type to include a location, this makes the `ErrMsg` feedback type redudant.

Other solutions may exist but this is the best I could come with, comments welcome!

Things like proper coqtop integration are left for future work as they have high potential of modifying the output.

### CODE REVIEW

**Comment by ejgallego** [comment]
Also, note that 8.6 may be a good moment to introduce this as the XmlProtocol format for the Message type was already changed in f20fce1259563f2081fadc62ccab1304bb8161d5 .

**Comment by gares** [comment]
Looks fine.  8.6 or 8.7 I don't have a strong opinion.  I've a small neatpick: loc already has an empty value, called Loc.ghost.  So wrapping it in an option seems a bit overkill to me.  I mean, in OCaml you cannot even put in the same match
``
| (None | Some loc when Loc.is_ghost loc) ->
```
And I guess one wants to do the very same thing in these 2 cases.

**Comment by gares** [comment]
I mean, you have to write
```
| None -> code
| Some loc when Loc.is_ghost loc -> same code
| Some loc -> different code
```

**Comment by ejgallego** [comment]
Thanks for the review Enrico. 8.7 or 8.6 I don't mind either, I did the PR in response to the comments in the warnings PR.

I opted out by a `Loc.t option` type mainly indeed to distinguish the three cases, if you look at the warning s rebase indeed sometimes they want to print "unknown" whereas others they want to print nothing. It is currently done with a `~print_ghost` flags but it looks a bit messy to me.

In general I've found that having `a located = ('a * Loc.t option)` gives more pleasant code than having a dummy loc.

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
