### PR TITLE
factorize or_var_map

### PR DESCRIPTION
**Pull request by nobrakal**
**Kind:** bug fix

Hi there,

I did not really know how to classify this, so I have chosen `bug fix` even if this is not a bug fix, but more a code-quality related PR. It factorizes two exact same definitions.

### CODE REVIEW

**Review by vbgl — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by yurug** [comment]
For the record, this redundancy has been found using http://github.com/nobrakal/asak. Congrats @nobrakal !

**Comment by maximedenes** [comment]
> For the record, this redundancy has been found using [http://github.com/nobrakal/asak](https://github.com/nobrakal/asak). Congrats @nobrakal !

Interesting. Is it the only redundancy that was found? Sounds surprising to me :)

**Comment by yurug** [comment]
No, more PRs are to come.

**Comment by ppedrot** [comment]
@yurug I was about to answer something about the highest standards of code quality held in the Coq development, thankfully I turned my tongue seven times before doing so :stuck_out_tongue:

**Comment by ppedrot** [comment]
Trivial, CI green, merge.

**Pull request merged**
