### PR TITLE
Linter: print errors in red in CI

### PR DESCRIPTION
**Pull request by SkySkimmer**
Tested at https://gitlab.com/SkySkimmer/coq/-/jobs/6042770743

### CODE REVIEW

**Comment by ppedrot** [comment]
While we're at it, could we also put errors in bold?

**Comment by SkySkimmer** [comment]
Doesn't seem like bold works https://gitlab.inria.fr/coq/coq/-/jobs/3823634

**Comment by JasonGross** [comment]
> Doesn't seem like bold works https://gitlab.inria.fr/coq/coq/-/jobs/3823634

Actually it does, it's just barely visible.  Compare:
image image

**Comment by SkySkimmer** [comment]
ok let's do it then

**Comment by SkySkimmer** [comment]
anyone want to merge?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
