### PR TITLE
Remove decimal-only number notations (deprecated in 8.12)

### PR DESCRIPTION
**Pull request by proux01**
- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

Overlays:
- HoTT: https://github.com/HoTT/HoTT/pull/1418

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
It looks like there are a few projects that still rely on those (cc @JasonGross).

**Comment by JasonGross** [comment]
I'll update the compatibility files for fiat shortly, when I get a chance

**Comment by Zimmi48** [comment]
What about HoTT? Should we ping someone else?

**Comment by JasonGross** [comment]
I expect the overlay for HoTT should be relatively easy to prepare, unlike the one for fiat.  I can try to take care of that too, but feel free to look into it if you want it done before I get the chance

**Comment by proux01** [comment]
> I expect the overlay for HoTT should be relatively easy to prepare

@JasonGross Indeed, done

**Comment by JasonGross** [comment]
I've pushed the commit https://github.com/JasonGross/coq-scripts/commit/37c5b726706a0d28e91c79740afad9c36e705dbe and https://github.com/mit-plv/fiat/commit/27e5718c64dd33ed563af067b6391ebdbdbb3c06 so fiat-parsers should work now; I've restarted the pipeline.

**Comment by proux01** [comment]
@JasonGross great, thanks.
I added the changelog entry so this should be ready.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I'll wait for the HoTT overlay to be merged before merging this one.

**Pull request merged**
