### PR TITLE
Share the check for evar groundedness in eassumption.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1982521081

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                  coq-stdlib │  393.38   398.87  -1.38 │  1631101511524   1644001136959  -0.78 │  1404657470080   1405156554294  -0.04 │  609584   598032   1.93 │   0    0      nan │
│    coq-metacoq-translations │   19.32    19.57  -1.28 │    86825675655     87619434959  -0.91 │   152933756416    152887453830   0.03 │  930956   929984   0.10 │   0    0      nan │
│                   coq-color │  249.75   251.66  -0.76 │  1133132335951   1141190166553  -0.71 │  1537920478244   1537948227072  -0.00 │ 1151792  1151064   0.06 │   0    0      nan │
│                coq-compcert │  275.91   277.94  -0.73 │  1252250292299   1259913731795  -0.61 │  1872588679829   1876339007302  -0.20 │ 1097912  1097996  -0.01 │   0    0      nan │
│                   coq-verdi │   47.44    47.75  -0.65 │   215360612959    217321585458  -0.90 │   321816806504    321805631917   0.00 │  834628   832752   0.23 │   0    0      nan │
│              coq-verdi-raft │  556.63   559.68  -0.54 │  2540731415297   2556431495058  -0.61 │  3928577109963   3939142421619  -0.27 │ 1231828  1230936   0.07 │   0    0      nan │
│           coq-iris-examples │  420.13   422.15  -0.48 │  1913222973051   1923231279788  -0.52 │  2909874560900   2917489675011  -0.26 │ 1172020  1167900   0.35 │   0    0      nan │
│            coq-math-classes │   92.67    93.10  -0.46 │   420432082823    421029877788  -0.14 │   587766867796    587797313565  -0.01 │  496504   499548  -0.61 │   0    0      nan │
│                    coq-core │   95.49    95.82  -0.34 │   389059922714    389583722004  -0.13 │   433447358725    433555413846  -0.02 │  273696   272188   0.55 │   1    0      nan │
│         coq-metacoq-erasure │   62.36    62.56  -0.32 │   280007242014    280108893313  -0.04 │   422978258832    423182664256  -0.05 │ 1073856  1071644   0.21 │   0    0      nan │
│      coq-mathcomp-character │   75.40    75.62  -0.29 │   345123767752    345988662997  -0.25 │   525225960617    525197611646   0.01 │  725456   724832   0.09 │   0    0      nan │
│                    coq-hott │  151.44   151.82  -0.25 │   687014378048    687110230863  -0.01 │  1073587169654   1074106921525  -0.05 │  656280   659784  -0.53 │   0    0      nan │
│  coq-performance-tests-lite │  770.08   771.65  -0.20 │  3494348239466   3502220793226  -0.22 │  5917682246548   5915624742690   0.03 │ 2320964  2320380   0.03 │   1    0      nan │
│                 coq-unimath │ 3632.03  3638.36  -0.17 │ 16613511213077  16642090132584  -0.17 │ 33163891267156  33165299872927  -0.00 │ 4127092  4127772  -0.02 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  906.63   908.08  -0.16 │  4136206097486   4141168750315  -0.12 │  7151323791313   7154680983380  -0.05 │ 1143216  1143364  -0.01 │  15    7   114.29 │
│                coq-bedrock2 │  185.83   186.12  -0.16 │   847412904473    848724557084  -0.15 │  1564994040707   1565303827032  -0.02 │ 2049360  2049364  -0.00 │   0    0      nan │
│                 coq-coqutil │   34.34    34.38  -0.12 │   154489327105    154268414092   0.14 │   207553990174    207647144990  -0.04 │  601724   600620   0.18 │   0    0      nan │
│       coq-mathcomp-solvable │   86.34    86.44  -0.12 │   395248052314    395669432013  -0.11 │   609166215705    609129865843   0.01 │  668288   669768  -0.22 │   0    0      nan │
│               coq-fiat-core │   53.05    53.10  -0.09 │   231585783903    231013128674   0.25 │   321949115966    322234457599  -0.09 │  476200   476320  -0.03 │   2    0      nan │
│              coq-coquelicot │   33.81    33.84  -0.09 │   152663245263    152951951968  -0.19 │   201531255596    201609799245  -0.04 │  749320   749228   0.01 │   0    0      nan │
│             coq-fiat-crypto │ 2828.25  2830.08  -0.06 │ 12865578995846  12875731197464  -0.08 │ 23756488403579  23761581743567  -0.02 │ 3770004  3768196   0.05 │   0    0      nan │
│                  coq-flocq3 │   76.02    76.06  -0.05 │   345986103012    345929938224   0.02 │   454108454558    454323432273  -0.05 │  989864   992240  -0.24 │   0    0      nan │
│            coq-fiat-parsers │  327.37   327.52  -0.05 │  1477440003811   1475413432005   0.14 │  2434716164537   2435487764763  -0.03 │ 2786672  2783120   0.13 │   0    0      nan │
│                    coq-corn │  762.68   762.77  -0.01 │  3475449971462   3478023624400  -0.07 │  5358842989880   5363147744951  -0.08 │  868872   868136   0.08 │   0    0      nan │
│          coq-mathcomp-field │  111.41   111.29   0.11 │   510052403147    509987557328   0.01 │   838592279733    838530931218   0.01 │  651768   649468   0.35 │   0    0      nan │
│                 coq-bignums │   27.42    27.39   0.11 │   125103408428    124790918402   0.25 │   172075924640    172169988940  -0.05 │  466296   465360   0.20 │   0    0      nan │
│        coq-metacoq-template │   72.32    72.22   0.14 │   322722209688    322368397698   0.11 │   486628597088    489679291854  -0.62 │  694164   698488  -0.62 │   0    0      nan │
│               coq-perennial │ 3993.04  3987.18   0.15 │ 18226914642372  18205054229069   0.12 │ 30071632904705  30082818660274  -0.04 │ 2586684  2601036  -0.55 │   0   13  -100.00 │
│                coq-coqprime │  177.74   177.32   0.24 │   812146750460    811226343432   0.11 │  1554289317049   1554234030894   0.00 │  906068   908124  -0.23 │   0    0      nan │
│               coq-fourcolor │ 1475.86  1470.70   0.35 │  6728026013163   6708921090918   0.28 │ 12081404286868  12081385225835   0.00 │  724036   724456  -0.06 │   0    0      nan │
│       coq-engine-bench-lite │  176.50   175.88   0.35 │   765676019481    761374769790   0.56 │  1485487303835   1483514025999   0.13 │ 1172376  1172836  -0.04 │   0    0      nan │
│           coq-metacoq-pcuic │  478.86   477.05   0.38 │  2188760227641   2179946528690   0.40 │  3104948237346   3111441063795  -0.21 │ 1115024  1125196  -0.90 │   0    0      nan │
│        coq-mathcomp-algebra │   62.89    62.64   0.40 │   287277961879    286027258763   0.44 │   395692571105    395655954458   0.01 │  558492   557268   0.22 │   0    0      nan │
│      coq-mathcomp-odd-order │  550.41   547.99   0.44 │  2522137785490   2510864006596   0.45 │  4279759028495   4279845451302  -0.00 │  931140   932864  -0.18 │   0    0      nan │
│                     coq-vst │ 1050.71  1045.97   0.45 │  4790678935632   4769051271783   0.45 │  7792625137327   7795539892283  -0.04 │ 2115704  2120508  -0.23 │   6    6     0.00 │
│                  coq-geocoq │  688.32   685.19   0.46 │  3139261775273   3124359723702   0.48 │  4942870388655   4942933406941  -0.00 │ 1073956  1074348  -0.04 │   0    0      nan │
│                coq-rewriter │  365.65   363.95   0.47 │  1666027093429   1657487632535   0.52 │  2717936184092   2719391838890  -0.05 │ 1061160  1058076   0.29 │   0    0      nan │
│      coq-mathcomp-ssreflect │   25.47    25.35   0.47 │   116084053636    115452863520   0.55 │   146863329672    146858084954   0.00 │  531540   533864  -0.44 │   0    0      nan │
│       coq-mathcomp-fingroup │   23.36    23.19   0.73 │   106406131452    106016015546   0.37 │   155047305299    154980645239   0.04 │  477444   477444   0.00 │   0    0      nan │
│     coq-metacoq-safechecker │  183.37   181.95   0.78 │   836662490056    829172192708   0.90 │  1125659527934   1125769743911  -0.01 │ 1224152  1217448   0.55 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Comment by ppedrot** [comment]
Not clear it's worth it but it might become synergetic if we start sharing the groundedness of the conclusion the various auto tactics. Since it doesn't hurt either I'd lean towards merging anyways.

**Review by herbelin — APPROVED** [review]
OK to me.

Otherwise, to avoid the rather large code duplication, maybe a variant of `e_give_exact` taking `not_ground` as argument could be introduced?

**Comment by ppedrot** [comment]
I don't think one wants to export that, it's very specific to auto tactics and everybody has their own implementation.

**Comment by herbelin** [comment]
I agree, I did not talk about exporting but about factorizing two codes doing the same thing and that might later diverge w/o us realizing they diverge differently. (But again, it is also ok like this.)

**Comment by ppedrot** [comment]
@herbelin would you assign and merge?

**Comment by herbelin** [comment]
OK, will merge in a couple of hours.

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
