### PR TITLE
Only perform profile initialization and printing when the flag is set.

### PR DESCRIPTION
**Pull request by ppedrot**
These functions were called at coqtop start and close, and they were triggering
a minor GC, which represents a big overhead for small files.

### CODE REVIEW

**Comment by ejgallego** [comment]
Great; WDYT about banning all static initialization from "core" Coq?

**Comment by herbelin** [comment]
For more flexibility, I would suggest to just move the `if !prof_table <> [] then` test at the top of `close_profile`, otherwise we'll have one more thing to do for profiling a particular function with Raffalli's profiler (add a `Profile.profile` combinator but also turn `Flags.profile` on). (I can do it if you want.)

**Comment by ppedrot** [comment]
@ejgallego Would make sense indeed, but that's a lot to review.

@herbelin I don't quite understand your proposal, I'd be glad indeed if you implemented it for me to see.

**Comment by herbelin** [comment]
@ppedrot: [here](https://github.com/herbelin/github-coq/commit/9a001865d3f6fcd747fe7243b5075f966c7f260d)

**Comment by ppedrot** [comment]
OK, I see what you mean. But we also need to initialize the profiler, so don't we also need to guard the call to init profile somehow? In that case I don't know when because it is linked before the table is populated.

**Comment by herbelin** [comment]
Yes, that would be cleaner to initialize the profiler only when there is something to profile.

We could move the call to `init_profile` to the last file being linked, and guard it with a check on the emptyness of the `prof_table`, so that the various `declare_profile` made at initialization of the executable have populated the `prof_table` already.

Would like me to do it?

**Comment by ppedrot** [comment]
@herbelin Please do, you seem to know exactly what you want.

**Comment by herbelin** [comment]
Hum, but we may have the same problem as for warnings, that plugins are linked after `coqtop.ml` and that if a `declare_profile` occurs in a plugin, it will not be taken into account...

For `ocamldebug` was it the `Gc` calls the problem or also the `Unix.times` call?

**Comment by ppedrot** [comment]
It was the GC. But I'm not that concerned by the debugger, rather because of the cost of performing at least two or three Gc.minor for every coqtop invocation in batch mode. I remember seeing the GC taking most of the time in the profiling of short files, so that it would probably help a lot performance-wise.

**Comment by herbelin** [comment]
OK, so, on the same [branch](https://github.com/herbelin/github-coq/commit/9a001865d3f6fcd747fe7243b5075f966c7f260d), I made `init_profile` on demand.

**Comment by ppedrot** [comment]
@herbelin If you want, I can close this PR and let you submit another one that supersedes it.

**Comment by herbelin** [comment]
Or, you can reset your branch to mine, to keep comments.

**Comment by ppedrot** [comment]
What's the name of the branch exactly? Your link only points to a particular commit.

**Comment by herbelin** [comment]
master+less-intrusive-close-profile

**Comment by ppedrot** [comment]
Done.

**Comment by psteckler** [comment]
@ppedrot Commit c3ca30c in this PR makes `coqtop.byte` hang on startup from `ocamdebug`, as described in BZ#5688.

**Pull request merged**
