### PR TITLE
Fix the computation of recursive principles with let-bindings.

### PR DESCRIPTION
**Pull request by ppedrot**
We use a more robust implementation that does not assume that the type of the inductive is in ζ-normal form. This code path is not exercised, because due to the kernel typing algorithm, let-bindings in the type of a recursor are expanded away.

I discovered this while working on preserving let-bindings in the typing algorithm.

### CODE REVIEW

**Comment by ppedrot** [comment]
See #11838 for a motivation.

**Comment by gares** [comment]
I think you should add a test

**Comment by JasonGross** [comment]
From what I can read in the commit message, it's impossible to add a pure-Coq test until more of #11838 is fixed?

**Comment by ppedrot** [comment]
@JasonGross yes, you're right, the fix belongs to what is currently dead code.

**Comment by gares** [comment]
Hum, the code looks reasonable but without a way to run it I'm not happy to merge it.

**Comment by ppedrot** [comment]
I am afraid I don't have a way to do that currently, and I'd like having this fix first because the code clearly displays a bug :/

**Comment by JasonGross** [comment]
Unit tests?

**Comment by ppedrot** [comment]
I don't see how to make a meaningful unit test, and this function is only called once in the whole code base. @gares can't you make an exception, and convince yourself looking at the code that the change is indeed correct? Just try to typecheck the term generated under the context, before the PR it's applying let bindings, while after it's skipping them, which makes sense given that terms whose type is a let binding are not supposed to be applied (barring what is under the binding, obviously).

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
The code is OK, but nobody  uses `ctx`, unless the line actually turning it into a vector of rels. Am I missing something? Do you plan to actually use/pass ctx?

**Comment by gares** [comment]
sorry, I see now

**Pull request merged**
