### PR TITLE
More theorems about [eq], and transparent [f_equal]n

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by herbelin** [comment]
I always feel that we are missing lemmas about equality proofs, so going in this direction looks very good to me. Let me give some remarks.

That some Qed be Defined is a priori better than nothing, but I believe that what is really missing is a command allowing to make an opaque constant transparent (either Abhishek Anand style with duplication, or by implementing the admissible rule which reveals a body - but the latter requires a slight change in module subtyping, as far as I could see).

To be honest, I consider that eq_rect has wrong implicit arguments (which in passing are not the same as and eq_rect_r). Personally, I would recommend generalizing the use of the notations "rew ... in ..." and "rew <- ... in ...", unless someone has a better proposal of notations. So the statement would be something like `rew [fun _ => P] e in k = k`.

**Comment by JasonGross** [comment]
> I believe that what is really missing is a command allowing to make an opaque constant transparent

I agree.  But I don't think the lack of such a command should stop us from changing a few `Qed`s to `Defined`s where it's particularly likely to be useful.

> I would recommend generalizing the use of the notations

Done

**Comment by JasonGross** [comment]
I'd like this in 8.7; is there anything stripping this from being merged?

**Comment by maximedenes** [comment]
This is a naive question, but what are the use cases that require making these proofs transparent?

**Comment by JasonGross** [comment]
> what are the use cases that require making these proofs transparent?

If I have a dependently typed representation of terms indexed over codes for types, and I write a heterogenous recursive function that walks two syntax trees simultaneously, and outputs one thing when types line up, and a default value when they don't, to make the returned value well-typed, I will sometimes need to decide if two types are equal, and then cast across the equality proof.  If I'm producing a syntax tree that needs to be `vm_computable`, the equality cast needs to reduce away.  This means that the equality decision function on type codes must be fully transparent.  It's convenient to use `f_equal2` when proving that `a = a' -> b = b' -> a * b = a' * b'` (where `*` is the type code combinator for cartesian product).

**Comment by maximedenes** [comment]
closing and reopening to trigger test build

**Comment by maximedenes** [comment]
No objections to the addition of lemmas. But turning `Defined` into `Qed` does not scale, breaks abstraction and can make scripts slower. However, maybe we can consider that lemmas on equality are an exception (since they don't really contain relevant information)? I've seen @ppedrot express similar worries in another PR. @ppedrot, what do you think of this one?

**Comment by ppedrot** [comment]
I'm personally against turning any Prop-valued theorem from Qed to Defined. One should not have a look at the precise implementation of a proposition, for all of the already mentioned drawbacks. Furthermore, the justification for this change is once again an XY problem, namely a workaround to make a specifically crafted term compute properly.

We're writing a standard library, and we cannot hope that it will cover every possible uses. Making fiat rely on such fragile specifications is a *really bad idea*, and they should rather have their own version of the theorem on which they have fine control. If we start acknowledging über-specific desiderata, we're not going to converge anytime soon.

Note that this is a personal stance. If other developers think this patch makes sense, then I'll gladly abide by the collegial decision. But I'm still hoping that Coq-devs are reasonable...

**Comment by Zimmi48** [comment]
@ppedrot Why would it be more OK to introduce new "defined" terms as it is the case in #517 than to turn some "Qed" into "Defined"?
The propositions that this PR impacts have pretty trivial proofs and one must hope that by using very basic tactics, one is actually manually constructing a term.
Besides, once a term is "defined", developers shouldn't change its proof without care (because obviously there is a risk of breaking external developments). So there is no real lack of specification here.
The main problem I think is that you don't believe that tactics are suitable to write proof terms, even very simple tactics for that matter. That people in HoTT and UniMath are still using tactics for this purpose even if they have been warned of the danger, shows that there is some interest in being able to do that. Thus maybe the problem is actually with the tactics: how to make sure that they are doing what is expected from them. What do you think?

**Comment by Zimmi48** [comment]
By the way, @herbelin said much earlier in this thread:

> That some Qed be Defined is a priori better than nothing, but I believe that what is really missing is a command allowing to make an opaque constant transparent

At the time, it didn't hit me but now with the remarks of @maximedenes and @ppedrot I'm thinking that this is a VERY BAD IDEA. Because `Qed` guarantees abstraction, if we change a proof we know for sure that we are not breaking external developments. But if we provide a command to turn opaque terms into transparent terms, then this abstraction breaks down and changing *any* proof may lead to breakage. I feel that the strategy of changing `Qed` into `Defined` on a limited set of theorems is a much better one because at least we know that changing the proof of *those* may lead to breakage.

Finally, if @ppedrot does not like having "defined" terms in the core library, maybe the standard library could contain a file specifically dedicated to HoTTists which would contain such theorems. Another solution would be to provide two copies for some theorems, a transparent one with a `_transparent` suffix, and an opaque one (which could be proved in terms of the transparent one). Anyways, there is a demand for such theorems, so why not meet it?

**Comment by ppedrot** [comment]
If people are willing to have transparent versions of said theorems, why not. But I'm not sure this is they are actually longing for. If I'm not mistaken, @JasonGross et al. complaints boil down to the fact that 1. `decide equality` produces crappy proof terms, and 2. they want to compute with it. So I'd bet adding the transparent variant of the proofs would not stop the flow of 'what if we turn this particular one transparent?'

**Comment by JasonGross** [comment]
The complaint does boil down to "I don't want to have to rewrite `decide equality` to get proof terms that compute".  I actually don't care what proof terms `decide equality` constructs, as long as they reduce down to `eq_refl` on ground terms without some sort of terrible blow-up.

More generally, the complaint is "I don't want to have to rewrite bits of the standard library just to get proofs to go away when I use them to make types line up".  The fact that `proj1` and `proj2` are both opaque is another source of frequent annoyance.

The interface I want the standard library to export is, e.g., `f_equal2 f eq_refl eq_refl ≡ eq_refl`; Coq doesn't currently have a way of exporting such judgmental reduction rules, and I think there are sufficiently few choices in these proofs (namely, only what order to destruct the equalities in), that this is a fine thing to export.  It's not like the proofs are going to change anytime soon, and, if desired, I could rewrite explicit proof terms here rather than lemmas built with tactics; would that be preferred?

**Comment by JasonGross** [comment]
Rebased on trunk

**Comment by maximedenes** [comment]
Oh, so this does sound look an XY problem. You want an improved `decide equality`, with proper staging of proofs w.r.t. computations. Is that right?

**Comment by maximedenes** [comment]
Xavier has a very interesting related blog post btw: http://gallium.inria.fr/blog/coq-eval/

**Comment by JasonGross** [comment]
> You want an improved `decide equality`

Mostly, though being able to use a transparent `f_equal2` rather than rewriting it in a project-specific-file would be nice.

> , with proper staging of proofs w.r.t. computations. Is that right?

No.  The proof of the equality branch needs to be completely transparent, because I need to cast terms across that proof of equality and I need the cast to disappear in `vm_compute`.

**Comment by ppedrot** [comment]
@maximedenes: To be fair, I remember fixing this bug to specifically please Xavier. I could probably do the same with decide equality, but I'll need a bit of help, or else I'll end up reimplementing everything from scratch.

**Comment by mortberg** [comment]
About turning Qed to Defined: I don't think the idea is as bad as @Zimmi48 thinks. If some external library would use this feature on some Qed'd term in the standard library they should be blamed if the proof changes and breaks their proofs. What they should have done instead if they rely on the exact shape of the proof is to prove it the way they want in their own library and not rely on the standard library never changing.

I think this kind of feature could be very useful in UniMath where some lemmas (that we have defined ourselves) can be Qed'd 99% of the time leading to better performance, but very rarely I need to be able to unfold them and reason about the shape of the proof. What I do now is that I duplicate the proof locally and end it with Defined, this is quite annoying and having a command to do it would make me happy. 


About building terms using tactics: The reason I'm using tactics to build terms in UniMath is that there is no other support to interactively build terms (as far as I know). If there would be something similar to Agda where one can insert holes and gradually build the terms I would probably use that instead.

**Comment by Zimmi48** [comment]
@mortberg Can't we find a way to solve the issue you are describing without breaking abstraction guarantees? Of course, we can say "library authors are to blame when they are not following good practice" but:

1. There is no official reference of what is good practice and what kind of scripts may lead to breakage when updating versions.

1. We are now according much more attention to compatibility when developing Coq, which means testing changes against external developments (such as UniMath) and sometimes fixing them by submitting PRs. Sometimes, it means finding that a development was relying on auto generated names, or on an unspecified unification algorithm which led to breakage 200 lines below the actual problem. So experience has kind of showed that we can't really rely on external developers following good practice.

Additionally @herbelin was arguing for this command as a way to avoid changing some `Qed` into `Defined` in the standard library, so precisely for the kind of use you say would be bad practice.

Maybe we should give the possibility to a library author to say that a proof term is opaque by default but can be made transparent if needed (with a third keyword besides `Qed` and `Defined`), or maybe we should really think about having `Defined` lemmas be as fast as `Qed` lemmas when used in a context where the proof does not matter (I'm not saying it is easy).

As for the lack of interactive support for building terms, what about using only the `refine` tactic? (I'm not saying that this should be the only way, I'd rather have a larger, well determined, set of tactics whose behavior is known to be predictable.)

**Comment by ejgallego** [comment]
IMVHO we should be wary of supporting the "Opaque ‌⇒ Transparent" route, mainly for Opaque constants will actually have no proof attached in many cases (hi parallel processing)

While we could hack something to make that use case work, IMHO, unless the kernel is modified to really support "deferred" terms, doing so may not be worth the maintenance cost.

**Comment by mortberg** [comment]
On Tue, Mar 28, 2017 at 10:36 AM, Théo Zimmermann <notifications@github.com>
wrote:

> @mortberg <https://github.com/mortberg> Can't we find a way to solve the
> issue you are describing without breaking abstraction guarantees? Of
> course, we can say "library authors are to blame when they are not
> following good practice" but:
>
>    1.
>
>    There is no official reference of what is good practice and what kind
>    of scripts may lead to breakage when updating versions.
>    2.
>
>    We are now according much more attention to compatibility when
>    developing Coq, which means testing changes against external developments
>    (such as UniMath) and sometimes fixing them by submitting PRs. Sometimes,
>    it means finding that a development was relying on auto generated names, or
>    on an unspecified unification algorithm which led to breakage 200 lines
>    below the actual problem. So experience has kind of showed that we can't
>    really rely on external developers following good practice.
>
> That is great and very much appreciated! Even if the developer cannot
figure out what is going wrong and file a PR it is very useful to get a
heads up (e.g. as a github issue) as early as possible so that we can
investigate it.


> Additionally @herbelin <https://github.com/herbelin> was arguing for this
> command as a way to avoid changing some Qed into Defined in the standard
> library, so precisely for the kind of use you say would be bad practice.
>
> Maybe we should give the possibility to a library author to say that a
> proof term is opaque by default but can be made transparent if needed (with
> a third keyword besides Qed and Defined), or maybe we should really think
> about having Defined lemmas be as fast as Qed lemmas when used in a
> context where the proof does not matter (I'm not saying it is easy).
>
A third keyword is fine with me. As long as I get something that makes it
possible for me to turn Qed'd things into Defined without having to
copy-paste lemmas. Imagine if we would need to duplicate every lemma in
UniMath, this would (at least) double the very long compilation time of the
library.

For HoTT/UF I think the ideal situation would be if we could use Defined
everywhere as more or less every proof can be used later one (even proofs
of h-propositions, e.g. iscontr(X) is a h-prop but it carries the point of
contraction). However using Defined everywhere doesn't scale as things get
too slow. Maybe one could have something weaker than Qed which prevents
unification and conversion to unfold terms while not making them completely
opaque?


> As for the lack of interactive support for building terms, what about
> using only the refine tactic? (I'm not saying that this should be the
> only way, I'd rather have a larger, well determined, set of tactics whose
> behavior is known to be predictable.)
>
Yes, we are trying to use a fixed set of predictable tactics (including
refine) when building terms. But this is still relying on tactics and my
point was that it would be nice to have a convenient way of building
complicated terms gradually without using tactics. Another remark is that
it is quite confusing for a user to know which of apply, simple apply,
refine, simple refine... is best to use when building terms that will be
Defined in the end.

**Comment by silene** [comment]
Just for the record, I agree with @ppedrot that turning Qed into Defined is certainly not the way forward.

**Comment by herbelin** [comment]
The question of computing with `Qed`-blocked proofs in singleton types is a very long-standing problem. If turning a few simple proofs from `Qed` to `Defined` is not the right answer, or at least the only available short-term answer, what is the right answer?

I mean that I see many different possible directions to go in relation with this problem, but the `Defined`-on-trivial-proofs solution such as the one proposed by @JasonGross seems to me the simplest available one in practice, at least until a specific support at the level of the logic is made possible.

After all, proofs of equality on sets are (observationally) canonical, so there is no loss of abstraction by making them public. As for the possible performance issues coming with `Defined` proofs, maybe this is where we should on the contraty find better solutions?

**Comment by herbelin** [comment]
How to make progresses on the `Qed`/`Defined` issues? The proofs under consideration in this PR are pretty short, canonical. They are also computationally relevant. Are there objective facts allowing to assert that turning these computational lemmas transparent would either damage efficiency of conversion or break abstraction? Or, conversely, what concrete solution to provide to computing with equality proofs when this happens to be useful?

**Comment by maximedenes** [comment]
Summary of WG discussion (for this PR and related ones):
- The `Qed` -> `Defined` changes are controversial because they break an abstraction barrier, for use cases that are real but specific. We don't integrate them in the stdlib.
- As for new lemmas, we try to figure out whether their `Qed` equivalent can be useful. If yes, we merge those.
- We try to address the limitation of `decide equality` to make it accept user provided (possibly transparent) proofs of equalities.

**Comment by maximedenes** [comment]
This discussion took quite some time, so feel free to add missing bits / correct my summary if needed.

**Comment by JasonGross** [comment]
Do you want me to update the PR with the Qed'd versions?  I think they are still useful.

Is there a livestream of the discussion / WG somewhere?  I'd be interested in listening to the discussion and seeing where I stand in light of it.

**Comment by ejgallego** [comment]
Note that I will provide the late binding patch soon; it should solve quite a bit problems (including allowing HoTT to break free from having to ship its own stdlib).

**Comment by maximedenes** [comment]
@JasonGross Yes, a PR with the `Qed`'d versions would be welcome, thanks!

@mattam82 Can you give a pointer to the stream videos? Have we checked if the sound was ok?

**Comment by JasonGross** [comment]
Closed as superseded by #385.

@mattam82 @maximedenes Are the streams at https://www.youtube.com/watch?v=dt91xDgp9iU https://www.youtube.com/watch?v=7roE4SxwNUY and https://www.youtube.com/watch?v=wQ45AwCn1SE ?  The sound seems pretty quiet :-/

**Comment by JasonGross** [comment]
@maximedenes Do you want me to leave this open as separate from #385 (even though that one includes the commits from this one?)?  (I'm listening to the stream of the WG.)

**Comment by Zimmi48** [comment]
@JasonGross From what I understood, there is no real need in keeping those PRs separate. There is also the suggestion that people like you and @herbelin create an external library and OPAM package providing these alternative transparent lemmas. Hugo proposed to do it in a separate file in the standard library but it was opposed to him that this is not of enough general interest to deserve to be in the standard library*. All of this summary is only based on the discussion of the first day. If this was discussed again on the second day, I wasn't there to assist.

*I think this, and questions such as moving part of the standard library to separate OPAM packages, lead to the important question "What should be in the standard library?" There is no clear policy about this and it would be good if this was discussed eventually (e.g. at the Users meeting if this finally happens at some point).

**Comment by maximedenes** [comment]
> There is no clear policy about this and it would be good if this was discussed eventually (e.g. at the Users meeting if this finally happens at some point).

More than a policy, I convinced myself that a per-component long-term roadmap would help a lot those discussions, and would probably help us communicate and organize calmly. I feel like I got a bit too emotional in some parts of this discussion, and I'm sorry about that. I'll try to share some thoughts soon on how to organize a collective work on such a long term roadmap (@mattam82 had something similar in mind I believe, a long term todo list for the entire system).

**Pull request closed without merging**
