### PR TITLE
refactor: replace raise with raise_notrace

### PR DESCRIPTION
**Pull request by rgrinberg**
Replace raise with raise_notrace everywhere in kernel/vars.ml where we can immediately verify that Not_found does not escape.

### CODE REVIEW

**Comment by ppedrot** [comment]
In an ideal world we would even have static exceptions in OCaml, but it's going to be a be short for Christmas.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
By the way, @rgrinberg  do you know why even when backtraces are not recorded, raising an exception is that expensive? Up to a dereference + branch it should be the same, is my mental model wrong?.

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1873613909

**Comment by rgrinberg** [comment]
I suppose it's the cost of a caml_raise_exn call. 

```
      begin match k with
      | Lambda.Raise_regular ->
          I.mov (int 0) (domain_field Domainstate.Domain_backtrace_pos);
          emit_call "caml_raise_exn";
          record_frame env Reg.Set.empty (Dbg_raise i.dbg)
      | Lambda.Raise_reraise ->
          emit_call "caml_raise_exn";
          record_frame env Reg.Set.empty (Dbg_raise i.dbg)
      | Lambda.Raise_notrace ->
          I.mov (domain_field Domainstate.Domain_exception_pointer) rsp;
          I.pop (domain_field Domainstate.Domain_exception_pointer);
          I.pop r11;
          I.jmp r11
      end
```

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
