### PR TITLE
bench NEW 8.15 vs OLD 8.14

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1949179803

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1949185002

**Comment by Alizter** [comment]
```
┌─────────────────────────────┬──────────────────────────┬────────────────────────────────────────┬────────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]       │               CPU cycles               │            CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                          │                                        │                                        │                         │                   │
│                package_name │     NEW      OLD   PDIFF │            NEW             OLD   PDIFF │            NEW             OLD   PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  804.56   977.22  -17.67 │  3502205195708   4260669231079  -17.80 │  5988105495631   7428037442131  -19.39 │ 2074096  2082712  -0.41 │   0    0      nan │
│              coq-verdi-raft │  600.54   650.59   -7.69 │  2624509229900   2842787030237   -7.68 │  4056853740537   4375351490240   -7.28 │ 1221040  1238092  -1.38 │   0    0      nan │
│               coq-fiat-core │   55.09    59.44   -7.32 │   231196925729    250008745530   -7.52 │   324793635733    350717966043   -7.39 │  474932   485832  -2.24 │   7    0      nan │
│                coq-compcert │  302.73   325.67   -7.04 │  1316463350488   1418216710694   -7.17 │  1969010788268   2114582384991   -6.88 │ 1101252  1106660  -0.49 │   0    0      nan │
│                 coq-unimath │ 3784.56  4068.73   -6.98 │ 16570695780110  17818669420165   -7.00 │ 33234945942110  36601566366554   -9.20 │ 3819888  3598464   6.15 │  10   11    -9.09 │
│                    coq-hott │  157.77   169.29   -6.80 │   685211338024    734317694905   -6.69 │  1085935083520   1165803118105   -6.85 │  660392   644728   2.43 │   0    0      nan │
│                  coq-flocq3 │   78.67    84.36   -6.74 │   342490367428    367930840333   -6.91 │   457517841885    487725758020   -6.19 │  993396   999268  -0.59 │  29    0      nan │
│                  coq-geocoq │  738.61   791.02   -6.63 │  3225594282549   3454934261637   -6.64 │  5159722845582   5483493274263   -5.90 │ 1064220  1064812  -0.06 │   2    4   -50.00 │
│          coq-mathcomp-field │  119.65   126.97   -5.77 │   523971288069    556140784306   -5.78 │   869881148284    926191722843   -6.08 │  663008   671684  -1.29 │   0    0      nan │
│       coq-mathcomp-solvable │   91.92    97.12   -5.35 │   402325072390    425565433704   -5.46 │   626968922056    660559395222   -5.09 │  664924   649672   2.35 │   0    0      nan │
│      coq-mathcomp-character │   80.28    84.72   -5.24 │   351992438984    371011355164   -5.13 │   539181967860    572564996278   -5.83 │  737420   736308   0.15 │   0    0      nan │
│        coq-mathcomp-algebra │   66.00    69.61   -5.19 │   288800637315    304345731587   -5.11 │   404062517791    428491761482   -5.70 │  563464   563348   0.02 │   0    0      nan │
│            coq-math-classes │   96.40   101.27   -4.81 │   418756741871    441271096322   -5.10 │   591962439906    624265616577   -5.17 │  495564   500448  -0.98 │   0    0      nan │
│                   coq-verdi │   50.04    52.56   -4.79 │   217438709715    228714119605   -4.93 │   327542443894    344294317209   -4.87 │  832644   846684  -1.66 │   0    0      nan │
│      coq-mathcomp-odd-order │  590.30   617.87   -4.46 │  2587464484032   2708514652942   -4.47 │  4437147682496   4645735181172   -4.49 │  950720   950176   0.06 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.27    25.36   -4.30 │   106244463204    110998491113   -4.28 │   157043543655    164723472807   -4.66 │  483596   485000  -0.29 │   0    0      nan │
│                coq-rewriter │  387.36   403.81   -4.07 │  1691099928744   1763507522334   -4.11 │  2789502796030   2910668087144   -4.16 │ 1068264  1076348  -0.75 │  17    2   750.00 │
│                   coq-color │  271.76   282.94   -3.95 │  1180474180641   1231694793362   -4.16 │  1609558267424   1689985216838   -4.76 │ 1151176  1129044   1.96 │   9    0      nan │
│      coq-mathcomp-ssreflect │   26.55    27.62   -3.87 │   116125934785    120595570460   -3.71 │   148950951418    153912285159   -3.22 │  535756   541624  -1.08 │   0    0      nan │
│            coq-fiat-parsers │  338.80   350.34   -3.29 │  1465838313428   1515959163362   -3.31 │  2438128255159   2522696025284   -3.35 │ 2810520  2735224   2.75 │   3   36   -91.67 │
│                     coq-vst │ 1184.92  1224.69   -3.25 │  5176524154299   5350925494859   -3.26 │  8454049194355   8716026892281   -3.01 │ 2100152  2099024   0.05 │   2    4   -50.00 │
│               coq-perennial │ 4283.76  4403.46   -2.72 │ 18734344313254  19260867091613   -2.73 │ 31237614041531  31992261109255   -2.36 │ 2588792  2601528  -0.49 │   0    0      nan │
│                 coq-bignums │   29.25    30.06   -2.69 │   127512269029    130938420043   -2.62 │   176712006639    182012202117   -2.91 │  467832   473116  -1.12 │   0    0      nan │
│             coq-fiat-crypto │ 3044.21  3123.96   -2.55 │ 13285530351842  13638346343962   -2.59 │ 24448973942859  25101099694039   -2.60 │ 3744704  3585048   4.45 │ 104   90    15.56 │
│           coq-iris-examples │  476.81   488.72   -2.44 │  2082853345440   2135098870682   -2.45 │  3178288599114   3256954919619   -2.42 │ 1191212  1179804   0.97 │  16    0      nan │
│                    coq-core │  101.11   102.91   -1.75 │   382832842635    375930833264    1.84 │   435406062512    430986553238    1.03 │  249544   245836   1.51 │   1    0      nan │
│                 coq-coqutil │   35.85    36.48   -1.73 │   154128856619    156788088542   -1.70 │   207870542734    211817383310   -1.86 │  601728   607552  -0.96 │   2    0      nan │
│                coq-bedrock2 │  194.38   197.67   -1.66 │   849242870380    863849806927   -1.69 │  1574550395639   1596071200089   -1.35 │ 2056916  2059416  -0.12 │  35   28    25.00 │
│       coq-engine-bench-lite │  180.91   183.74   -1.54 │   760093969365    773398220919   -1.72 │  1486752496319   1511030544110   -1.61 │ 1184436  1226068  -3.40 │   0    0      nan │
│                  coq-stdlib │  418.19   423.14   -1.17 │  1503988927639   1525482922573   -1.41 │  1448535070835   1477995690048   -1.99 │  604364   602228   0.35 │   0    0      nan │
│              coq-coquelicot │   35.79    36.20   -1.13 │   153827138091    156618777014   -1.78 │   204168503998    206107168317   -0.94 │  751432   753488  -0.27 │ 145    5  2800.00 │
│               coq-fourcolor │ 1521.58  1531.47   -0.65 │  6655457470178   6698504565790   -0.64 │ 12103706457315  12143581247395   -0.33 │  735100   737812  -0.37 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  956.32   958.18   -0.19 │  4178924213249   4187851863037   -0.21 │  7237692909939   7195974654664    0.58 │ 1152936  1086924   6.07 │  13    0      nan │
│                coq-coqprime │  189.67   188.26    0.75 │   830233634920    824879225353    0.65 │  1561826660720   1569807336893   -0.51 │  854752   861216  -0.75 │   4    1   300.00 │
│                    coq-corn │  820.63   782.34    4.89 │  3583550074986   3418081108324    4.84 │  5611540788268   5314957526756    5.58 │  831840   861004  -3.39 │   0    0      nan │
└─────────────────────────────┴──────────────────────────┴────────────────────────────────────────┴────────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬──────────────────────────┬────────────────────────────────────────┬────────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]       │               CPU cycles               │            CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                          │                                        │                                        │                         │                   │
│                package_name │     NEW      OLD   PDIFF │            NEW             OLD   PDIFF │            NEW             OLD   PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼──────────────────────────┼────────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  804.56   977.22  -17.67 │  3502205195708   4260669231079  -17.80 │  5988105495631   7428037442131  -19.39 │ 2074096  2082712  -0.41 │   0    0      nan │
│              coq-verdi-raft │  600.54   650.59   -7.69 │  2624509229900   2842787030237   -7.68 │  4056853740537   4375351490240   -7.28 │ 1221040  1238092  -1.38 │   0    0      nan │
│               coq-fiat-core │   55.09    59.44   -7.32 │   231196925729    250008745530   -7.52 │   324793635733    350717966043   -7.39 │  474932   485832  -2.24 │   7    0      nan │
│                coq-compcert │  302.73   325.67   -7.04 │  1316463350488   1418216710694   -7.17 │  1969010788268   2114582384991   -6.88 │ 1101252  1106660  -0.49 │   0    0      nan │
│                 coq-unimath │ 3784.56  4068.73   -6.98 │ 16570695780110  17818669420165   -7.00 │ 33234945942110  36601566366554   -9.20 │ 3819888  3598464   6.15 │  10   11    -9.09 │
│                    coq-hott │  157.77   169.29   -6.80 │   685211338024    734317694905   -6.69 │  1085935083520   1165803118105   -6.85 │  660392   644728   2.43 │   0    0      nan │
│                  coq-flocq3 │   78.67    84.36   -6.74 │   342490367428    367930840333   -6.91 │   457517841885    487725758020   -6.19 │  993396   999268  -0.59 │  29    0      nan │
│                  coq-geocoq │  738.61   791.02   -6.63 │  3225594282549   3454934261637   -6.64 │  5159722845582   5483493274263   -5.90 │ 1064220  1064812  -0.06 │   2    4   -50.00 │
│          coq-mathcomp-field │  119.65   126.97   -5.77 │   523971288069    556140784306   -5.78 │   869881148284    926191722843   -6.08 │  663008   671684  -1.29 │   0    0      nan │
│       coq-mathcomp-solvable │   91.92    97.12   -5.35 │   402325072390    425565433704   -5.46 │   626968922056    660559395222   -5.09 │  664924   649672   2.35 │   0    0      nan │
│      coq-mathcomp-character │   80.28    84.72   -5.24 │   351992438984    371011355164   -5.13 │   539181967860    572564996278   -5.83 │  737420   736308   0.15 │   0    0      nan │
│        coq-mathcomp-algebra │   66.00    69.61   -5.19 │   288800637315    304345731587   -5.11 │   404062517791    428491761482   -5.70 │  563464   563348   0.02 │   0    0      nan │
│            coq-math-classes │   96.40   101.27   -4.81 │   418756741871    441271096322   -5.10 │   591962439906    624265616577   -5.17 │  495564   500448  -0.98 │   0    0      nan │
│                   coq-verdi │   50.04    52.56   -4.79 │   217438709715    228714119605   -4.93 │   327542443894    344294317209   -4.87 │  832644   846684  -1.66 │   0    0      nan │
│      coq-mathcomp-odd-order │  590.30   617.87   -4.46 │  2587464484032   2708514652942   -4.47 │  4437147682496   4645735181172   -4.49 │  950720   950176   0.06 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.27    25.36   -4.30 │   106244463204    110998491113   -4.28 │   157043543655    164723472807   -4.66 │  483596   485000  -0.29 │   0    0      nan │
│                coq-rewriter │  387.36   403.81   -4.07 │  1691099928744   1763507522334   -4.11 │  2789502796030   2910668087144   -4.16 │ 1068264  1076348  -0.75 │  17    2   750.00 │
│                   coq-color │  271.76   282.94   -3.95 │  1180474180641   1231694793362   -4.16 │  1609558267424   1689985216838   -4.76 │ 1151176  1129044   1.96 │   9    0      nan │
│      coq-mathcomp-ssreflect │   26.55    27.62   -3.87 │   116125934785    120595570460   -3.71 │   148950951418    153912285159   -3.22 │  535756   541624  -1.08 │   0    0      nan │
│            coq-fiat-parsers │  338.80   350.34   -3.29 │  1465838313428   1515959163362   -3.31 │  2438128255159   2522696025284   -3.35 │ 2810520  2735224   2.75 │   3   36   -91.67 │
│                     coq-vst │ 1184.92  1224.69   -3.25 │  5176524154299   5350925494859   -3.26 │  8454049194355   8716026892281   -3.01 │ 2100152  2099024   0.05 │   2    4   -50.00 │
│               coq-perennial │ 4283.76  4403.46   -2.72 │ 18734344313254  19260867091613   -2.73 │ 31237614041531  31992261109255   -2.36 │ 2588792  2601528  -0.49 │   0    0      nan │
│                 coq-bignums │   29.25    30.06   -2.69 │   127512269029    130938420043   -2.62 │   176712006639    182012202117   -2.91 │  467832   473116  -1.12 │   0    0      nan │
│             coq-fiat-crypto │ 3044.21  3123.96   -2.55 │ 13285530351842  13638346343962   -2.59 │ 24448973942859  25101099694039   -2.60 │ 3744704  3585048   4.45 │ 104   90    15.56 │
│           coq-iris-examples │  476.81   488.72   -2.44 │  2082853345440   2135098870682   -2.45 │  3178288599114   3256954919619   -2.42 │ 1191212  1179804   0.97 │  16    0      nan │
│                    coq-core │  101.11   102.91   -1.75 │   382832842635    375930833264    1.84 │   435406062512    430986553238    1.03 │  249544   245836   1.51 │   1    0      nan │
│                 coq-coqutil │   35.85    36.48   -1.73 │   154128856619    156788088542   -1.70 │   207870542734    211817383310   -1.86 │  601728   607552  -0.96 │   2    0      nan │
│                coq-bedrock2 │  194.38   197.67   -1.66 │   849242870380    863849806927   -1.69 │  1574550395639   1596071200089   -1.35 │ 2056916  2059416  -0.12 │  35   28    25.00 │
│       coq-engine-bench-lite │  180.91   183.74   -1.54 │   760093969365    773398220919   -1.72 │  1486752496319   1511030544110   -1.61 │ 1184436  1226068  -3.40 │   0    0      nan │
│                  coq-stdlib │  418.19   423.14   -1.17 │  1503988927639   1525482922573   -1.41 │  1448535070835   1477995690048   -1.99 │  604364   602228   0.35 │   0    0      nan │
│              coq-coquelicot │   35.79    36.20   -1.13 │   153827138091    156618777014   -1.78 │   204168503998    206107168317   -0.94 │  751432   753488  -0.27 │ 145    5  2800.00 │
│               coq-fourcolor │ 1521.58  1531.47   -0.65 │  6655457470178   6698504565790   -0.64 │ 12103706457315  12143581247395   -0.33 │  735100   737812  -0.37 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  956.32   958.18   -0.19 │  4178924213249   4187851863037   -0.21 │  7237692909939   7195974654664    0.58 │ 1152936  1086924   6.07 │  13    0      nan │
│                coq-coqprime │  189.67   188.26    0.75 │   830233634920    824879225353    0.65 │  1561826660720   1569807336893   -0.51 │  854752   861216  -0.75 │   4    1   300.00 │
│                    coq-corn │  820.63   782.34    4.89 │  3583550074986   3418081108324    4.84 │  5611540788268   5314957526756    5.58 │  831840   861004  -3.39 │   0    0      nan │
└─────────────────────────────┴──────────────────────────┴────────────────────────────────────────┴────────────────────────────────────────┴─────────────────────────┴───────────────────┘
~~~

**Comment by SkySkimmer** [comment]
What's going on with corn? I don't see +40s in the per line diff.

**Comment by ppedrot** [comment]
Are we sure we're comparing the same versions of the packages?

**Comment by SkySkimmer** [comment]
Looks like .dev for both according to the logs
rebench corn https://gitlab.com/coq/coq/-/jobs/1951839314

**Comment by SkySkimmer** [comment]
~~~
┌──────────────────┬───────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬───────────────────────┬─────────────────┐
│                  │     user time [s]     │             CPU cycles              │          CPU instructions           │ max resident mem [KB] │   mem faults    │
│                  │                       │                                     │                                     │                       │                 │
│     package_name │    NEW     OLD  PDIFF │           NEW            OLD  PDIFF │           NEW            OLD  PDIFF │    NEW     OLD  PDIFF │ NEW  OLD  PDIFF │
├──────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│ coq-math-classes │  91.67   96.43  -4.94 │  416210825112   439478267778  -5.29 │  585899366880   618389872911  -5.25 │ 497048  502296  -1.04 │   0    0    nan │
│      coq-bignums │  28.08   28.88  -2.77 │  127521930588   131422882157  -2.97 │  176535548568   181914254626  -2.96 │ 466316  471868  -1.18 │   0    0    nan │
│       coq-stdlib │ 397.06  405.09  -1.98 │ 1653063184218  1694203105000  -2.43 │ 1447891013175  1477190446567  -1.98 │ 604612  602464   0.36 │   0    0    nan │
│         coq-core │  96.69   95.33   1.43 │  396389614471   390225073500   1.58 │  435178563191   431202111583   0.92 │ 249824  245664   1.69 │   0    0    nan │
│         coq-corn │ 789.40  753.82   4.72 │ 3600853266234  3442750495950   4.59 │ 5589519249960  5294682832507   5.57 │ 832068  861952  -3.47 │   0    0    nan │
└──────────────────┴───────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────┘
~~~

**Comment by ppedrot** [comment]
Stuff that does not appear in the per-line diff notably include native compilation, checker and vo saving. Anything in corn that could observe that?

**Comment by SkySkimmer** [comment]
It's a standard coq_makefile project, so no native or checker.
I guess we should find a way to add per-file timings to the bench.

**Comment by ppedrot** [comment]
Normally there is already the infrastructure to do that in coq_makefile, see the `TIMING` flag and consorts. I don't know how to plug that in the bench script though.

**Pull request closed without merging**
