### PR TITLE
Don't fail when printing a ltac2 name local to another module

### LINKED ISSUE #17155: #[local] Ltac2 tactics break Ltac2 backtrace printing
#### Description of the problem

Ltac2 backtraces containing `#[local]` functions cannot be printed. I've been haunted by this bug for months and finally managed to accidentally reproduce it in a minimal setting.

```coq
From Ltac2 Require Import Ltac2.
Module M.
  #[local] Ltac2 f () := Control.throw (Invalid_argument None).
  Ltac2 g () := f ().
End M.
Fail Ltac2 Eval M.g ().         (* Fails, as expected. *)
Set Ltac2 Backtrace.
Fail Ltac2 Eval M.g ().         (* Anomaly "Uncaught exception Not_found." *)
```

#### Coq Version
8.16.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17155

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
Thanks for fixing this so quickly. I have two questions:
1. Any chance we can get this into the 8.17 release?
2. Whats the right mental model for `#[local] Ltac2`? Is it meant to provide abstraction? (That would be pretty awesome.)

**Comment by ppedrot** [comment]
@Zimmi48 it's probably too late but just so that you get a ping I'm putting this into the 8.17 milestone.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
