### PR TITLE
 CI: stop testing 4.11+trunk

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Incidentally resolves the error in the removed 4.11 job.
We should also update edge in the dockerfile but I'm not doing it in this PR.

**Comment by SkySkimmer** [comment]
Updated to also disable 4.12 since it also doesn't work.

**Comment by ejgallego** [comment]
Umm, maybe we should try to update the test to 4.11.1+trunk instead? The current error is due to OPAM upstream having removed 4.11.0+trunk [ehem ehem....]

**Comment by ejgallego** [comment]
> Updated to also disable 4.12 since it also doesn't work.

4.12 is gonna take some effort likely, indeed.

**Comment by SkySkimmer** [comment]
OK let's see if 4.11.1 works

**Comment by SkySkimmer** [comment]
~~~
The following dependencies couldn't be met:
  - ocaml-variants -> ocaml = 4.11.1
      no matching version
~~~

**Comment by SkySkimmer** [comment]
Could we accelerate merging this to stop the spam? @coq/ci-maintainers

**Comment by ejgallego** [comment]
OPAM, what a mess... I can merge tho the template becomes unused and no example given; I'm not sure this is the right solution to the spam problem tho; we are getting spam in other jobs too, IMHO the problem is the reporting mechanism which was hastily implemented.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by Zimmi48** [comment]
> IMHO the problem is the reporting mechanism which was hastily implemented.

Yes, it was hastily implemented upon request to do so. However, this was always seen as a temporary solution and it is going to be replaced very shortly by reporting in the Checks tab. In the meantime, we could also disable the reporting for some specific jobs if you wish.

**Review by ejgallego — APPROVED** [review]
Merging quickly as per @SkySkimmer 's request, see my comments tho.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
