### PR TITLE
[api] Move structures deprecated in the API to the core.

### PR DESCRIPTION
**Pull request by ejgallego**
We do up to `Term` which is the main bulk of the changes.

### CODE REVIEW

**Comment by ejgallego** [comment]
In particular I am not sure about the `Term` to `Constr` change, it seems a bit arbitrary to me to force users and plugins to switch.

You could see this as a complain about the tradeoffs in 4490dfcb94057dd6518963a904565e3a4a354bac
but anyways I think it is too late now and we are will be closing the circle in 2018 with the removal of the compatibility layer.

**Comment by ejgallego** [comment]
Only the linter fails, but given the nature of this commit I request an exception as I think I do not want to reindent half's of Coq code base.

**Comment by SkySkimmer** [comment]
Whitespace fixed version https://github.com/SkySkimmer/coq/tree/api-depr

**Comment by ejgallego** [comment]
I suggest we follow the same argument wrt whitespace as in #6065

**Comment by maximedenes** [comment]
> I suggest we follow the same argument wrt whitespace as in #6065

Yeah, looks ok to me.

**Pull request merged**
