### PR TITLE
Simplify `interp/constrintern.ml:sort_fields`

### PR DESCRIPTION
**Pull request by gasche**
Background: at the end of the Coq Coding Sprint, I decided that a feature that would be within reach (unlike `fun <pattern> =>`...) would be the ability to define records by reusing fields of an existing records, that is `{| r with f1 = ...; f2 = ... |}`.

The function to use for this purpose is `sort_fields` in `interp/constrintern.ml`. Unfortunately it is undocumented and its code was unclear enough that I could not understand what it does. (There was a boolean argument named `mode` and a local variable named `boolean`, for example.)

The current pull-request brings zero new feature, but is a series of simplification and changes to the code of `sort_fields` that allowed me to understand its semantics, culminating in a documentation comment. I suspect the code changes along the way could also help future readers, which is why I didn't just include the comment in the pull request.

Note 1: it's quite hard to review all changes at once, because there are a many simultaneous changes going on. I would recommend looking at the commits one by one, I tried to make them as atomic as reasonably possible.

Note 2: there is a question in a commend prefixed by `(* G.S.:`, if someone can answer it I think inline comments would be a good place to discuss it, otherwise I'll just remove the comment.

```
                         (* G.S.: why do we fail only in the
                            first-field case? I would expect to fail
                            whenever (not regular && complete), and
                            skip the fields only when (not complete *)
```

Note 3: now that I do understand what the function does, I suspect there should be a more direct way to implement it (than the inherently quadratic processing being performed here), but I resisted the temptation to do it. My point was just to make the existing implementation clearer.

Note 4: I did a couple mistakes during my changes, and observed that Coq immediately fails to build `theories/Logic/ExtensionalityFacts.vo`. I therefore suspect that Coq breaks in obvious way when this function is bugged, which gives me confidence that the new implementation is as bug-free as the previous one.

Note 5: I was a bit frightened when I discovered that `make test-suite` fails miserably in my feature branch, but then found out that it already fails on `trunk` with the same failures (included below), so I guess that is ok.

```
    success/decl_mode2.v...Error! (should be accepted)
    bugs/opened/3948.v...Error! (bug seems to be closed, please check)
    bugs/opened/4214.v...Error! (bug seems to be closed, please check)
    output/inference.v...Error! (unexpected output)
    output/Notations.v...Error! (unexpected output)
```

### CODE REVIEW

**Comment by gasche** [comment]
Hugo orally clarified my question-in-comments this morning: non-`regular` fields are defined as let-bindings in the record definition itself, so their value is fixed from the other fields. In particular, it does not make sense to provide their values at record construction time. I do think it is the case that the `not regular && complete` case should always be rejected.

Some thing I still don't understand is whether the `completer` function can be called when building record expressions (in terms of the new code, when `complete` is true). The [sort_fields call](https://github.com/gasche/coq/blob/simplify_intern_sort_fields/interp/constrintern.ml#L1509-L1513) used to build expressions plugs evars in the missing fields, but it is not clear to me whether it could ever happen (won't the function definition fail in this case?).

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Comment by mattam82** [comment]
@gasche The holes could be for typeclass instances, or turned into obligations by Program or subgoals by refine for example.
About the [not regular && complete] case, shouldn't these projections simply be skipped as you do now? Why fail there, when these projection values cannot be specified for patterns or constructed terms?

**Comment by maximedenes** [comment]
Merged, at last. Thanks a lot for this patch and sorry for the delay to merge it. We have become more reactive on pull requests since then :)

**Comment by gasche** [comment]
@maximedenes no harm done on my side, this is not a feature-implementing patch anyway, and for me the value was more in the making (getting to understand this corner of Coq better) than in the integration itself. But hopefully it will pave the way for more record-related ideas, possibly going back to that `{| foo with ... |}` syntax!

**Pull request closed without merging**
