### PR TITLE
[Debugger] Convert Loc.t filenames in Ltac tactic definitions to absolute paths at load time

### PR DESCRIPTION
**Pull request by jfehrle**
When the debugger stops at a breakpoint, it needs to find (from the Loc.t)  the associated `.v` file so it can be opened and displayed, and to highlight the stopping point in the buffer.  However, `coqc` generates `Loc.t`s with relative pathnames--which it must because modules can be installed in any directory.  This code replaces relative pathnames in the tactic objects with absolute pathnames when the tactic object is loaded.

I considered trying to map from the relative pathname to a module name and thence to a directory, but that is not necessarily unique.  I don't want to force the user to tell CoqIDE which of the possible matches is the correct one.  (They could pick the wrong one, too, generating great confusion.)

For now, the debugger will assume that the `.vo` and the `.v` file are in the same directory.  We can always relax that restriction in future versions.

I expect this has a negligible performance impact.  I don't understand the difference between `open_md` (which is where the change is) and `load_md` (which was my initial guess), or how often `open_md` is called.

This code is necessary to support the 2nd PR for the Ltac Debugger (which I will submit shortly).  That adds a lot of great functionality that users would benefit from in 8.14 even if it's somewhat incomplete or has some bugs.  I hope someone will be able to review this soon.

Depends on and incorporates #14224

### CODE REVIEW

**Comment by ppedrot** [comment]
I think it is a terrible way to perform this. Instead you should register a conversion table used by the debugger to map location tweaks. Also, I don't believe you can get a sound mapping for locations in general, this whole mess should be pushed as far as possible out of the Ltac runtime.

**Comment by ejgallego** [comment]
This PR is doing a few different things, some look ok, some are indeed a bit more strange; I'd suggest to split it to start with.

> However, coqc generates Loc.ts with relative pathnames--which it must because modules can be installed in any directory. This code replaces relative pathnames in the tactic objects with absolute pathnames when the tactic object is loaded.

This doesn't look OK, as of today, Coq has no good way to perform this kind of resolution, even after using the assumption of .v / .vo files in the same dir. Instead, the debugger IDE should be able to do the mapping itself with the information the IDE has, for example _CoqProject data.

**Comment by jfehrle** [comment]
You can have vo files in different modules with exactly the same relative path.  For example `foo.vo` in `Mod1.Foo` containing `./foo.v` in its `Loc.t`'s and the `foo.vo` in `Mod2.Foo` similarly containing `./foo.v` in its `Loc.t`'s.  AFAIK the debugger has no way to know which module is the right one--it would be much simpler if that info was available.  The IDE can ask the user to pick among alternatives, but the user doesn't necessarily know which one is the correct choice.  A perhaps realistic example is a user who has two different versions of a package available under different module names--there would be a lot of ambiguous file names.  A pathological case is a script that executes code from two vo files with identical pathnames--in this case the debugger has to ask the user which file to use whenever the debugger stops in either of them.

> I think it is a terrible way to perform this. Instead you should register a conversion table used by the debugger to map location tweaks. Also ... this whole mess should be pushed as far as possible out of the Ltac runtime.

Perhaps you would give objective reasons why you think this is "terrible" and a "mess"?  My initial thought was, I think, similar to yours, to use the existing module name-to-directory mapping, then checking which mapped directory+relative pathname has the file.  But the mapping is not guaranteed to be one to one, giving a poor user experience when the debugger stops in such files.

It wasn't my preference to do what I've done here, but what I have is a more reliable and more user-friendly approach.  The code added in `tacenv.ml` is self-contained.  If it would help I could move the code to a new file and limit the change in `tacenv.ml` to a single line.  One can argue that `tacenv.ml` has nothing to do with debugging and that therefore the code is architecturally out of place.  But I think this is a bit unrealistic--we create architecture to let us deliver functionality.  Supporting debuggers tends to affect more than a few parts of a system, some of which may be initially unexpected.

> I don't believe you can get a sound mapping for locations in general

Can you provide a counterexample?  Perhaps I'm missing some subtlety.

**Comment by ppedrot** [comment]
> The code added in tacenv.ml is self-contained.

Apart from that, it's also completely wrong because it won't go under quotations.

**Comment by jfehrle** [comment]
> I'd suggest to split it to start with

The first commit is just #14224.  Focus on the 3 files changed in the second commit.

> This doesn't look OK, as of today, Coq has no good way to perform this kind of resolution, even after using the assumption of .v / .vo files in the same dir. Instead, the debugger IDE should be able to do the mapping itself with the information the IDE has, for example _CoqProject data.

The spot I changed in `tacenv.ml` is AFAIK the only place that has access to both the module name and the relative file path for the .vo file--where the absolute pathname can be determined unambiguously (and saved in the updated `Loc.t`'s).  The `_CoqProject` file won't help because the debugger doesn't know from the `Loc.t` which module the tactic is in.

**Comment by jfehrle** [comment]
> it's also completely wrong because it won't go under quotations.

I don't understand this.  Perhaps you could elaborate a bit / give an example?

**Comment by ejgallego** [comment]
> You can have vo files in different modules with exactly the same relative path. For example `foo.vo` in `Mod1.Foo` containing `./foo.v` in its `Loc.t`'s and the `foo.vo` in `Mod2.Foo` similarly containing `./foo.v` in its `Loc.t`'s. AFAIK the debugger has no way to know which module is the right one--it would be much simpler if that info was available. The IDE can ask the user to pick among alternatives

I see, indeed for this case it has to be IDE which resolves this using the information in the build setup [as of today].

#14059 should provide a principled API to resolve this, after reading _CoqProject or similar.

**Comment by ejgallego** [comment]
> #14059 should provide a principled API to resolve this, after reading _CoqProject or similar.

You can also query this info today from `Loadpath`, but it is likely not to be 100% reliable, but the idea is:
```ocaml
  let base_dir_for_module = Loadpath.base_of_module mod_id in
  let actual_file_path = Filename.concat base_dir_for_module file_in_loc
```

**Comment by ppedrot** [comment]
> Perhaps you could elaborate a bit / give an example?

If you have something like `constr:(foo ltac:(bar))` it won't do anything.

> the only place that has access to both the module name and the relative file path

Then store this data in a map that can be accessed in the debugger. Don't mess with the Ltac AST please.

**Comment by jfehrle** [comment]
Side question:  I'm getting the "Several physical paths are associated with ..." anomaly from `Loadpath.find_logical`.  When I print the physical paths, I see they're all the same.  That seems very odd.  This condition would also make `Loadpath.find_load_path` fail.  Is it an artifact of using `Dyn` or something that perhaps should be fixed?

**Comment by jfehrle** [comment]
> > Perhaps you could elaborate a bit / give an example?

> If you have something like `constr:(foo ltac:(bar))` it won't do anything.

I don't know how to put that in an executable tactic.  Would you give me exact syntax so I can try it in `tactic_debug.ml`?

**Comment by ejgallego** [comment]
> EDITED: Side question: I'm getting the "Several physical paths are associated with ..." anomaly from `Loadpath.find_logical`. That seems very odd--I expected it would be 1 physical path per module. What would cause that?

It seems that both find_logical and maybe_convert are a bit wrong I think.

**Comment by JasonGross** [comment]
> > > Perhaps you could elaborate a bit / give an example?
> 
> > If you have something like `constr:(foo ltac:(bar))` it won't do anything.
> 
> I don't know how to put that in an executable tactic. Would you give me exact syntax so I can try it and see what `tactic_debug.ml` does with it?

```coq
Ltac do_stuff := let x := constr:(id ltac:(exact nat)) in idtac x.
Goal True.
  do_stuff.
Abort.
```

It seems to me that perhaps full module paths (including which bits are file path components and which are modules in a file) should be stored in tactic locations, rather than (or in addition to?) relative path names.  This information should be available when creating the location.  Then the debugger should translate the module name to a file name.

**Comment by ejgallego** [comment]
> including which bits are file path components and which are modules in a file

This won't work as of today, due to the relocatable nature of vo files.

**Comment by JasonGross** [comment]
> I expected it would be 1 physical path per module. What would cause that?

Module names are not unique unless you also include a separator that indicates which part of the module path is the file.  Consider `Module C` in `Module B` in file `A.v` vs `Module C` in file `A/B.v`. The HoTT category theory library does this a lot, by having a file `A.v` for every directory `A/` which either `Include`s or `Export`s or `Require`s all the files in the directories.  (Speaking of which, you should make sure the debugger works correctly when you invoke Ltac generated by module include and by functor application, in particular when the module (functor) is not defined in the same file as the substituted Ltac.). It seems that Coq will complain if you try to construct two different objects with the same kernel name, but will happily allow you to declare the same object with the same kernel name (via `Include`) multiple times.

**Comment by ejgallego** [comment]
> Module names are not unique unless you also include a separator that indicates which part of the module path is the file

I need to check your example, but indeed in general you need to call the nametab to resolve a module name to its full module name [this has been giving hell to serapi users for example]

**Comment by JasonGross** [comment]
> > including which bits are file path components and which are modules in a file
> 
> This won't work as of today, due to the relocatable nature of vo files. The info is already there as I explain above.

If you are talking about `Loadpath.base_of_module`, `git grep` says this function does not exist in the codebase.  I think perhaps the function is `Lib.dp_of_mp`, which is indeed the information I'm talking about?  Or perhaps `Libnames.qualid_path`?  There's also `Library.library_full_filename` and `Loadpath.try_locate_absolute_library`.

Note that I'm not suggesting that the names in the module path are meaningful in the filesystem, just that it's essential to be able to distinguish between `Ltac foo` in `Module B` in file `A.v` and `Ltac foo` in file `A/B.v`, even though both will have the same kernel name.  (And both can co-exist in the same project even, though I don't think it's possible to import both files at the same time if you do this.)

**Comment by JasonGross** [comment]
> in general you need to call the nametab to resolve a module name to its full module name [this has been giving hell to serapi users for example]

Is this about a user saying `Import A` and you needing to figure out that `A` is `Foo.Bar.Baz.A`?  Or is this about a user saying `Import Top.A` where the reason `Top.A` exists at all is because you just did an `Include B` where `Top.B` contains a `Module A` and hence the module `Top.A` is secretly the same as the module `Top.B.A`?  Or something else?

**Comment by JasonGross** [comment]
> Speaking of which, you should make sure the debugger works correctly when you invoke Ltac generated by module include and by functor application, in particular when the module (functor) is not defined in the same file as the substituted Ltac.

@jfehrle here is some code for this:
In `A.v`:
```coq
Ltac foo := idtac "I'm in A.v (1)"; idtac "I'm in A.v (2)".
Module B. Ltac foo := idtac "I'm in Module B in A.v (1)"; idtac "I'm in Module B in A.v (2)". End B.
Module Type BT. Ltac foo := idtac "I'm in Module Type BT in A.v (1)"; idtac "I'm in Module Type BT in A.v (2)". End BT.
Module Type EmpT. End EmpT.
Module Emp. End Emp.
Module F (E : EmpT). Ltac foo := idtac "I'm in Module Functor F in A.v (1)"; idtac "I'm in Module Functor F in A.v (2)". End F.
Module G (B' : BT). Include B'. End G.
```
In `B.v`:
```coq
Require Import A.
Module B1 := A.B.
Module B2. Include A.B. End B2.
Module B3 := A.F A.Emp.
Module B4 := A.G A.B.
```
In `C.v`:
```coq
Require Import B.
Goal True.
  B1.foo.
  B2.foo.
  B3.foo.
  B4.foo.
Abort.
```

The `idtac` string should tell you which tactic is being run.

**Comment by SkySkimmer** [comment]
>Ltac foo in Module B in file A.v and Ltac foo in file A/B.v, even though both will have the same kernel name.

They don't, the first is `MPdot (MPfile [A], B)` the second is `MPfile [B;A]`.

**Comment by SkySkimmer** [comment]
IIUC we want to store something in Loc.t which can be resolved to a file in a relocation resilient way.
IMO that means the Dirpath.t from `Lib.library_dp()`

**Comment by JasonGross** [comment]
> They don't, the first is `MPdot (MPfile [A], B)` the second is `MPfile [B;A]`.

This is good, and I think I was just saying that this difference is important.
I guess perhaps I should have said "same absolute name" or "same displayed kernel name" (where here I'm pulling "absolute name" from `Warning: Trying to mask the absolute name "Coq.Init.Datatypes"!` that I get if I write `Module Coq. Module Init. Module Datatypes.`).

**Comment by JasonGross** [comment]
> IIUC we want to store something in Loc.t which can be resolved to a file in a relocation resilient way.
> IMO that means the Dirpath.t from `Lib.library_dp()`

I agree with this.  Two questions:
1. Is this going to have a noticeable performance or vo size impact?  We are storing at least an extra pointer (+bytes for the boxing) per location, perhaps an entire extra linked list of strings if things are not sufficiently shared.
2. Is the `DirPath.t` redundant with the relative file name?  That is, would it be feasible to store only the `DirPath.t` and reconstruct the filename from the mapping in loadpath when printing messages?

**Comment by JasonGross** [comment]
Hmm, I guess here is another corner case:  Suppose I write some things in `A.v`, and then in `B.v`, I do `Load "/absolute/path/to/A.v".`.  What locations get associated to these objects?

**Comment by jfehrle** [comment]
I can look at modifying `coqc` so `Loc.t`s include the initial part of the module name.  At the moment, with my changes, `theories/Init/Tactics.v` is in module `Coq.Init` and has "./Init/Tactics.v" in the `Loc.t`'s, so it should be sufficient to also save `Coq` in the Loc.t.  Perhaps best add a new constructor to `Loc.source`.

IIUC module name always maps uniquely to a physical path.  But isn't it possible to reassign a logical name to a new physical path with a command?  If I've loaded foo.vo in Module1, then reassign Module1 to a different directory, can running scripts still invoke the original foo.vo after the reassignment?  If so, the debugger would look for foo.v in the wrong place.  Is this possible or prohibited?

Also, I'd appreciate if someone could address my earlier comment:

> Side question:  I'm getting the "Several physical paths are associated with ..." anomaly from `Loadpath.find_logical`.  That seems very odd--I expected it would be 1 physical path per module.  What would cause that?

**Comment by jfehrle** [comment]
@JasonGross: The .vo files will be slightly larger, but loaded .vo files surely a very small fraction of memory usage, especially compared to the scripts of yours we analyzed for memory use.  `Tactics.v` went from 29KB to 35 KB, up about 20%.

Your comments about the functors and the Load command are good points, but at the moment they're secondary or tertiary issues.

**Comment by JasonGross** [comment]
> The .vo files will be slightly larger, but loaded .vo files are surely a very small fraction of memory usage, especially compared to the scripts of yours we analyzed for memory use. `Tactics.vo` went from 29KB to 35 KB, up about 20%.

As a reference point, the .vo files from all installed versions of Coq on my machines take up about 4.5GB, and the .vo files from all the projects I have cloned are currently at about 1--1.5 GB.  So 20% is not negligible, but it's also tolerable.

> I can look at modifying `coqc` so `Loc.t`s include the initial part of the module name. At the moment, with my changes, `theories/Init/Tactics.v` is in module `Coq.Init` and has "./Init/Tactics.v" in the `Loc.t`'s, so it should be sufficient to also save `Coq` in the Loc.t. Perhaps best add a new constructor to `Loc.source`.

I think it might be better to store the entire `DirPath.t`, so that the information is more readily available and you don't need to do as much processing?

> IIUC module name always maps uniquely to a physical path. But isn't it possible to reassign a logical name to a new physical path with a command? If I've loaded foo.vo in Module1, then reassign Module1 to a different directory, can running scripts still invoke the original foo.vo after the reassignment? If so, the debugger would look for foo.v in the wrong place. Is this possible or prohibited?

Not so.  Coq is somewhat arbitrary about picking what file to use.  I think it will happily accept `-R foo1/ foo -R foo2/ foo` though.  If your project is set up right, then there will be no overlapping files between the directories (for example, HoTT has `-R theories HoTT -Q contrib HoTT.Contrib` and there's no `Contrib` file nor directory in `theories/`, so everything is fine).

> Also, I'd appreciate a more complete response to my earlier comment:
> 
> > Side question:  I'm getting the "Several physical paths are associated with ..." anomaly from `Loadpath.find_logical`.  That seems very odd--I expected it would be 1 physical path per module.  What would cause that?

Can you reproduce it by passing `-R foo1/ foo -R foo2/ foo` and making an `A.v` in both `foo1/` and `foo2/`?  (Btw, you can get several logical paths associated to the same physical path by doing `-R foo/ foo1 -R foo/ foo2`, I believe.  Or more commonly, something like `-R theories MyProject -Q . Top`.)

**Comment by jfehrle** [comment]
> Not so.

Please clarify which part of my comments you're responding to.   My only interest at the moment is to find a 100% reliable way to determine from the Loc.t where the .vo is.  If there is one.

> Coq is somewhat arbitrary about picking what file to use.

Sounds like a bug or design flaw to me.

**Review by ppedrot — CHANGES_REQUESTED** [review]
Just to be clear, because it seems the message hasn't reached its target: I am **strongly opposed** to this internal cuisine with the Ltac AST. Apart from the code style itself being dubious at least, this is nonsense. Instead, you must register metadata in a table that is exposed to the debugger and use it to mangle the locations there, not in the AST.

**Comment by JasonGross** [comment]
> > Not so.
> 
> Please clarify which part of my comments you're responding to.

Ah, sorry.  It was in response to "IIUC module name always maps uniquely to a physical path"

> > Coq is somewhat arbitrary about picking what file to use.
> 
> Sounds like a bug or design flaw to me.

Indeed, though I think C may have a similar problem with header file names?

> But isn't it possible to reassign a logical name to a new physical path with a command? If I've loaded foo.vo in Module1, then reassign Module1 to a different directory, can running scripts still invoke the original foo.vo after the reassignment?

I'm not sure what you're talking about here (do you have example code?). One thing I can say is that, IIUC, transitive require is by module name/logical path, not by physical path. So if Module1 loads Foo.foo from foo.vo, then something loading Module1 will go looking for a foo.vo in whatever physical path it thinks corresponds to Foo.foo, and then will check that the digest/sha hash matches the one recorded in Module1.

> 100% reliable way to determine from the Loc.t where the .vo is. If there is one.

Luckily you're sharing code with coqc's loading mechanism, and hence this should be possible (if you were writing a Python script there'd be no way to ensure it stayed in sync).  Just adjust the Loc.t to store the module DirPath.t information at creation time (as @ppedrot says, don't do post-hoc surgery on them), and then in the debugger look up the file name from the using the same logic / function that `Require` does.

**Comment by ejgallego** [comment]
> Just to be clear, because it seems the message hasn't reached its target: I am **strongly opposed** to this internal cuisine with the Ltac AST. Apart from the code style itself being dubious at least, this is nonsense. Instead, you must register metadata in a table that is exposed to the debugger and use it to mangle the locations there, not in the AST.

Indeed, I was feeling the same, but we didn't explain clearly, this solution seems wrong to me too, unless I'm missing something. Note that I'm not sure we even need a table the info is likely there; we could have a brief chat to help @jfehrle write the function, but first I suggest again to write down the type and specification of the location operation that is needed at the debugger level.

**Comment by JasonGross** [comment]
> Indeed, I was feeling the same, but we didn't explain clearly, this solution seems wrong to me too, unless I'm missing something.

Note that the info in the Loc.t does need to be changed.  The current information there (a relative file path) does not uniquely pin down a file on disk.  Contrary to what you say in https://github.com/coq/coq/pull/14251#issuecomment-832915681 and as explained in https://github.com/coq/coq/pull/14251#issuecomment-832908747

**Comment by jfehrle** [comment]
> @ppedrot it seems the message hasn't reached its target

I was giving this some thought and trying some experiments while working on other parts of debugger, e.g. #14224.

There are 3 cases that affect finding the correct source file from the `Loc.t`:
- The relative path in the `Loc.t` may not be unique across multiple modules.  This is a normal possibility that we should handle automatically, thus requiring some code change.
- A module has multiple top-level directories, permitting duplicate relative path names across those directories.  IIUC this is a user error because Coq doesn't define which one it will load.  Multiple top-level directories seems to be infrequent: only the test suites and 4 libraries failed for this reason with my original code.  The debugger can at least show a message to the user if the debugger stops in files with duplicated pathnames.  Outside of this PR, it seems to me Coq should check for this condition at startup and for `Add LoadPath`.
- I thought it might be possible to redefine a module so it points to another directory in the middle of the script.  If so, is it possible for the script to subsequently still call the prior version of a script in the module?  If that is the case, the current code that you dislike may be the only way to handle this case correctly.  If this case is possible, we might consider prohibiting it.  We could also deem it unsupported by the debugger.

Adding the module name in `Loc.t` at compile time would address the first two cases.  (I would lean toward making it `string option` within the `InFile` variant, but it could also be `Dirpath.t option`.)  If that's agreeable I'll do that.

**Comment by JasonGross** [comment]
> * I thought it might be possible to redefine a module so it points to another directory in the middle of the script.

If `Add LoadPath` does not do this, I don't believe it's possible.

**Comment by ejgallego** [comment]
>  Instead the Loc.t info must be augmented with enough info to uniquely pin down the file, which, as suggested #14251 (comment), I think should be a DirPath.t

I don't think so.

Loc.t only make sense in Ast nodes, and I think this is the confusion here.

In the context of the debugger there are very little Ast's at hand, at most the only Ast that would be valid is the one of the current tactic being executed.

If the debugger needs to look up where a tactic notation was defined, indeed there is not need to modify anything, as you can get the right context from the notation definition name in order to locate the AST for that particular tactic definition.

**Comment by jfehrle** [comment]
> >  Instead the Loc.t info must be augmented with enough info to uniquely pin down the file, which, as suggested #14251 (comment), I think should be a DirPath.t

> I don't think so.

If "I don't think so" applies to "I think should be a DirPath.t" as opposed to a `string`, that's a reasonable comment.  But it's necessary to have the module info present in some form in the `Loc.t` to handle the multiple-directories case.  Also, the debugger detects that it's reached a breakpoint by matching the current location against a hash table at every possible stopping point.  Doing some repeated more complex translation at every step would probably have a noticeable performance impact.

**Comment by JasonGross** [comment]
> In the context of the debugger there are very little Ast's at hand, at most the only Ast that would be valid is the one of the current tactic being executed.

I think you're forgetting about how insane the semantics of Ltac are.  Consider:
In A.v:
```
Ltac foo b :=
  match b with
  | true => fun _ => fail 0 "a"
  | false => fun _ => fail 0 "b"
  end.
```
In file B.v:
```coq
Ltac bar := let tac := foo true in tac.
```
When executing `tac` I think we no longer have the tactic name `foo`.  Perhaps what you're saying is that the filename information should be extracted from the backtrace rather than from the location nodes in the AST, and the location nodes should just be assumed to corresponds to the most recent frame? (I think there may be cases where this isn't valid, though I'm not 100% sure)

**Comment by jfehrle** [comment]
Users need to be able to set breakpoints even when Coq is not stopped in the function getting the new breakpoint.  In that case, we don't have a useful stack to examine.  Determining the name of the function would require parsing the file.  Adding the module info to `Loc.t` can handle this case very simply.

Furthermore, for single-file debugging, breakpoints can be added in functions that don't parse.

**Comment by ejgallego** [comment]
To provide a bit more of detail, a few comments on how to locate a tatic definition:

1. You need to obtain the kername for the tactic, this can done in many ways but example the backtrace already contains it
2. Then you can use `Tacenv.ltac_entries` to get the body of the tactic, that will provide you file-specific location of the tactic definition, this could indeed need some tweaks to store more data at tactic registration time, tho it will be OK I think
3. Now you have the file-local information, you need to resolve the actual location of the file using the kername and Loadpath

and that is all I think.

**Comment by jfehrle** [comment]
@JasonGross Would you also give me exact instructions for compiling your longer example [here](https://github.com/coq/coq/pull/14251#issuecomment-833490249) in a local build (i.e. `dune exec -- dev/shim/*-prelude ..`, including what directory to put them in relative to the top `coq` directory in the source tree?  (I've not done that often.)  And perhaps check it loads properly in the released coqide/coqtop?  Thanks.

**Review by ejgallego — CHANGES_REQUESTED** [review]
As discussed the resolution of the location to a project path has to happen on the IDE side in a late-binding fashion.

**Comment by JasonGross** [comment]
> @JasonGross Would you also give me exact instructions for compiling your longer example [here](https://github.com/coq/coq/pull/14251#issuecomment-833490249) in a local build (i.e. `dune exec -- dev/shim/*-prelude ..`, including what directory to put them in relative to the top `coq` directory in the source tree? (I've not done that often.) And perhaps check it loads properly in the released coqide/coqtop? Thanks.

I don't use local builds much, so you'll have to ask someone else (@ejgallego?) what the local equivalent is, but if you have Coq installed globally, then the command you want is:
```
for f in A B C; do coqc -q -R /path/to/vfiles Top /path/to/vfiles/$f.v; done
```
(you probably want to make a directory with just these three files, what directory doesn't matter, just feed its path to `coqc` in place of `/path/to/vfiles`)
and you should see things like `I'm in Module Functor F in A.v (1)` on compiling `C.v`.

**Comment by jfehrle** [comment]
> I see, indeed for this case it has to be IDE which resolves this using the information in the build setup [as of today].
>
> #14059 should provide a principled API to resolve this, after reading _CoqProject or similar.

If there's a small piece of your PR that you think would be helpful, please identify it.  I won't try to pull in all 34 files (still in draft PR) for the debugger at this time.  The resolution should be done on the server side--other IDEs will need this capability and `coqidetop` has all the internal data structures.  CoqIDE doesn't have a good way of tracking `LoadPath` commands that are relevant in addition to _CoqProject.

> You can also query this info today from `Loadpath`, but it is likely not to be 100% reliable, but the idea is:
```ocaml
  let base_dir_for_module = Loadpath.base_of_module mod_id in
  let actual_file_path = Filename.concat base_dir_for_module file_in_loc
```

I can't find `base_of_module` in any file in Coq nor in your PR.

**Comment by JasonGross** [comment]
> > You can also query this info today from `Loadpath`, but it is likely not to be 100% reliable, but the idea is:
> 
> ```ocaml
>   let base_dir_for_module = Loadpath.base_of_module mod_id in
>   let actual_file_path = Filename.concat base_dir_for_module file_in_loc
> ```
> 
> I can't find `base_of_module` in any file in Coq nor in your PR.

I mentioned my guesses for this in https://github.com/coq/coq/pull/14251#issuecomment-833483457

**Comment by jfehrle** [comment]
Replaced by #14354

**Pull request closed without merging**
