### PR TITLE
partac: don't ignore missing results

### LINKED ISSUE #16732: `par:` succeeds even when worker processes are OOM-killed
#### Description of the problem

@Zimmi48 [said](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/fiat.20crypto.20broken/near/306206665):
> FTR I've recently seen a different type of failure in fiat-crypto:
>
>     File "./src/Curves/Weierstrass/AffineProofs.v", line 49, characters 4-13:
>     Error:  (in proof commutative_group): Attempt to save an incomplete proof
>     
>     Command exited with non-zero status 1
>     src/Curves/Weierstrass/AffineProofs.vo (real: 74.58, user: 128.66, sys: 1.81, mem: 1424652 ko)
>
> (https://github.com/coq/coq/runs/9102466669)

I replied:
> That is another avatar of the same issue (but is possibly worth separately reporting as a bug in Coq?).  When a `par:` worker process is OOM-killed (sometimes? always?), without the main Coq process being OOM-killed, the main Coq process believes the worker completed successfully but did not solve any goals.  Hence the `Qed` fails with "Attempt to save an incomplete proof".

#### Coq Version

8.17+alpha

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16732 ?

Based on https://github.com/coq/coq/pull/16733

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Significantly changed, please rereview
(CI found the issue mentioned in the code comment about missing results when there are errors, then I found #16735 while inverstigating)

**Comment by gares** [comment]
please rebase

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
CI seems to confirm that #16732 is fixed by turning the error from "killed by signal 9" to "missing results"

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
