### PR TITLE
Update CI extension doc 

### PR DESCRIPTION
**Pull request by SkySkimmer**
See discussion around https://github.com/coq/coq/pull/17241#discussion_r1101247051

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Added info about the process instead of just saying "look at this PR"

**Comment by Alizter** [comment]
ping @coq/doc-maintainers

**Review by Alizter — APPROVED** [review]
LGTM

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
