### PR TITLE
Handle default locality at attribute time

### LINKED ISSUE #14704: Bad line number for warning about implicit `Global` on `Instance`
#### Description of the problem

The following code:
```
Class Test := { wit : nat }.

Instance test: Test.
Proof. constructor. exact 0. Qed.
```
produces a warning on Coq master:
```
File "/tmp/test2.v", line 4, characters 29-33:
Warning: The default value for instance locality is currently "local" in a
section and "global" otherwise, but is scheduled to change in a future
release. For the time being, adding instances outside of sections without
specifying an explicit locality attribute is therefore deprecated. It is
recommended to use "export" whenever possible. Use the attributes #[local],
#[global] and #[export] depending on your choice. For example: "#[export]
Instance Foo : Bar := baz." [deprecated-instance-without-locality,deprecated]
```
However, the line number of the warning is wrong: it points at the `Qed`, when it really should point at the `Instance` since that is where the problem lies.

This is particularly annoying since it means [automatic scripts](https://gitlab.mpi-sws.org/iris/iris/-/merge_requests/594#note_60292) that parse these warnings to add the missing explicit `Global` will edit the wrong line. (I found such scripts to be the only way to actually deal with this warning -- we get many dozens of these warnings in basically each of our developments; fixing them all by hand would be horrible.)

#### Coq Version

Coq master

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #14704

Overlays: https://github.com/Mtac2/Mtac2/pull/338 https://github.com/QuickChick/QuickChick/pull/231 https://github.com/mattam82/Coq-Equations/pull/419 https://github.com/MetaCoq/metacoq/pull/578  https://github.com/mit-plv/fiat/pull/55 https://github.com/LPCIC/coq-elpi/pull/279

### CODE REVIEW

**Comment by ppedrot** [comment]
Uh, I didn't think of doing it that straightforwardly. This will definitely conflict with #14697 though, can I advocate for merging mine first?

**Review by ppedrot — APPROVED** [review]

**Comment by jfehrle** [comment]
Shouldn't there be a brief changelog entry?

**Comment by ppedrot** [comment]
@SkySkimmer can you add a short changelog so we can merge this?

**Comment by ppedrot** [comment]
Will merge when CI finishes.

**Pull request merged**
