### PR TITLE
Add Ring respects polymorphism

### LINKED ISSUE #9201: `Add Ring` should detect whether it's in polymorphic or monomorphic mode when in a section and pick lemmas accordingly
#### Version

8.8.2

#### Description of the problem

```coq
Require Import Coq.setoid_ring.Ring.

Set Universe Polymorphism.
Inductive word : nat -> Type :=
| WO : word O
| WS : bool -> forall n, word n -> word (S n).
Axiom wzero : forall sz, word sz.
Axiom wone : forall sz, word sz.
Axiom wplus : forall sz, word sz -> word sz -> word sz.
Axiom wmult : forall sz, word sz -> word sz -> word sz.
Axiom wminus : forall sz, word sz -> word sz -> word sz.
Axiom wneg : forall sz, word sz -> word sz.
Axiom wring : forall (sz : nat), ring_theory (wzero sz) (wone sz) (@wplus sz) (@wmult sz) (@wminus sz) (@wneg sz) (@eq _).
Local Unset Universe Polymorphism.
Section foo.
  Context (sz : nat).
  Add Ring word_sz_ring : (wring sz). (* success *)
End foo.
Local Set Universe Polymorphism.
Section foo'.
  Context (sz : nat).
  Add Ring word_sz_ring' : (wring sz).
  (* Error: Cannot mix universe polymorphic and monomorphic declarations in sections. *)
End foo'.
```
I would like both of these to work.

cc @andres-erbsen @mattam82 @samuelgruetter

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #9201

Not sure that this works properly, let's see if CI blows up.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Looks like it works.

**Comment by ppedrot** [comment]
I think it won't work with polymorphic rings because IIRC we pass terms with meaningless universe instances in the Ltac code. But this PR is a reasonable first step.

**Comment by amahboubi** [comment]
I agree. What about an entry in the test suite?

**Comment by SkySkimmer** [comment]
>Not sure that this works properly

Indeed it doesn't work.
```coq
Require Import Coq.setoid_ring.Ring.

Set Universe Polymorphism.
Inductive word : Type -> Type :=.
Axiom wzero : forall sz, word sz.
Axiom wone : forall sz, word sz.
Axiom wplus : forall sz, word sz -> word sz -> word sz.
Axiom wmult : forall sz, word sz -> word sz -> word sz.
Axiom wminus : forall sz, word sz -> word sz -> word sz.
Axiom wneg : forall sz, word sz -> word sz.
Axiom wring : forall sz, ring_theory (wzero sz) (wone sz) (@wplus sz) (@wmult sz) (@wminus sz) (@wneg sz) (@eq _).


Section foo.
  Context (sz : Type).
  Add Ring word_sz_ring : (wring sz).

  Lemma use_ring : forall a b, wplus sz a b = wplus sz b a.
  Proof. intros. ring. (* anomaly *) Qed.

End foo.
```
I tried to figure out how to fix it but couldn't.

**Pull request closed without merging**
