### PR TITLE
autobuild .merlin files in CI scripts for some plugins

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
Two questions:
- Why do we want to do this in the CI?
- Why isn't the standard makefile generating this target by default?

**Comment by ejgallego** [comment]
I guess @SkySkimmer wants to this so he gets working merlin support for overlays.

That's still a very much suboptimal developer experience IMO, as compared to the method I was using some time ago (dune build @check with overlays enables)

**Comment by SkySkimmer** [comment]
I use dune build check for some projects where the CI uses dune (eg serapi, tactician) but it's also nice to be able to just `make ci-foo` and jump to the error line

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Let's merge, this is indeed trivial. @coqbot merge now

**Pull request merged**
