### PR TITLE
Add coq-bug-minimizer to the ci

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by ejgallego** [comment]
Umm, I am not sure what we would be testing here? A bunch of python scripts?

**Comment by JasonGross** [comment]
Yes, a bunch of python scripts, that interact with the format of `.glob` files and the output of `coqc` and `coq_makefile` in a particular way.  For example, if `coq_makefile` ever loses the ability to create a `Makefile` in `/tmp`, this ci would catch that.  If the errors output by `coqc` mistakenly change format to no longer be located, this ci would catch that.

**Comment by maximedenes** [comment]
I don't feel very comfortable merging this, since it would basically mean in practice that we do the maintenance of the minimizer w.r.t. Coq changes. If that's what we want, then ok.

**Comment by Zimmi48** [comment]
I don't think this is what it means, but rather that we will inform the author (@JasonGross) of any breaking change and maybe help him understand what changes are needed.

**Comment by maximedenes** [comment]
Well, that is not what happens today in practice, except if we merge it to the "allowed failures" section. Otherwise, merging a PR that breaks this test will mark all the subsequent PRs to be shown as not passing the tests.

**Comment by maximedenes** [comment]
So at the very least, merging any PR that breaks this test will have to wait for the author to provide such a patch.

**Comment by Zimmi48** [comment]
I wasn't saying we should merge a PR that breaks the minimizer but that there should be an implicit agreement with Jason that he will react quickly if a PR breaks it (for good reasons).
Note that we are already dependent today on our PRs getting merged by the developments we track and that's why we expect good responsiveness from the authors.

**Comment by Zimmi48** [comment]
If this happens to not work in practice, we can always revert this.

**Comment by maximedenes** [comment]
If that's ok with everyone, I have no objection. Although the tests currently fail, that should be fixed :)

**Comment by JasonGross** [comment]
I want this tested precisely because I want to know early when something breaks, so I can fix it, and so that if something breaks accidentally on Coq's side, I don't have to kludge around it.

Re failure, oh, right, this breaks because I adapted it to coq_makefile2, not realizing that Coq < trunk doesn't support `coq_makefile -o /tmp/foo`.  I'll fix that later today.

**Comment by ejgallego** [comment]
> the format of .glob files; the output of coqc; and coq_makefile.

Unfortunately all these interfaces are undocumented and thus considered unstable. I understand that the bug minimizer has to work with them, but the tool as it stands now is too fragile for my taste.

> For example, if coq_makefile ever loses the ability to create a Makefile in /tmp, this ci would catch that. If the errors output by coqc mistakenly change format to no longer be located, this ci would catch that.

Both examples IMHO, if relevant, should be added as tests to the test suite. Relying on the bug minimizer to check that doesn't seem like the right approach.

Additionally, the minimizer seems to depend on coq's output geared towards human consumption. I am afraid I think it is not a sensible long-term strategy to encourage tools to rely on such approach. [In fact, there already are many places where the output is "wrong" for humans and should be corrected.]

I thus remain concerned about adding the minimizer to the main CI. I do not have a concern to add it as `allow-fail`.

**Comment by JasonGross** [comment]
> Unfortunately all these interfaces are undocumented and thus considered unstable. I understand that the bug minimizer has to work with them, but the tool as it stands now is too fragile for my taste.

I'm not sure what you consider fragile, but these are consistent from 8.4 through 8.6, at the least, and I don't know any other interface, other than the basic vernacular, documented or undocumented, which is so stable across versions of Coq.  If I make a PR to document these features, many of which I expect have remained largely unchanged at least since 8.3, will this be less fragile?

> Additionally, the minimizer seems to depend on coq's output geared towards human consumption.

Indeed, though it depends only on the string that describes the location of errors (File name and line number), and basically nothing else; is this one of the wrong places?

> I thus remain concerned about adding the minimizer to the main CI. I do not have a concern to add it as allow-fail.

Is there a way to get Coq's Travis to email me if it fails, even when it's allowed-fail?

**Comment by Zimmi48** [comment]
@JasonGross I think there is: https://docs.travis-ci.com/user/notifications/#Configuring-email-notifications

**Comment by Zimmi48** [comment]
The discussion about this PR is here: https://youtu.be/wQ45AwCn1SE?t=1h57m9s
If I understood correctly from the video, the conclusion was "we do not merge".
Note that you can alternatively use Travis on your own repository and set cron jobs to run your tests regularly against trunk.

**Comment by ejgallego** [comment]
Thanks for the link Théo, I'll try to summarize the discussion for those not wanting to load video, but the basic idea is that we don't feel sure about the stability of the approach based on parsing Coq's output. In particular developers would have a hard time fixing the python scripts so we prefer not to commit to stable error messages etc... for now.

That doesn't mean of course we will purposely change them; but we want to send the message that they should not be relied upon. We also recognize the need for better interfaces, including true stable error codes so tools can rely on them.

However it would be fine to merge this in allow fail if @JasonGross deems it useful.

**Comment by maximedenes** [comment]
Btw, it is in no way meant to be a negative signal we would be sending w.r.t. the usefulness of the tool.

**Comment by ejgallego** [comment]
By the way it still fails. The `allow-fail` solution may have an advantage, that if after some time we deem the bug-minimizer stable, it could indeed be considered for promotion.

In fact, the plan is for official Travis policy to suggest that all new tests in the suite have to go throu a period of "quarantine" in allow-fail. Once we understand them a bit better, we can move them to required.

**Comment by JasonGross** [comment]
Yeah, I'm confused why it's failing.  If I run the test twice, it succeeds in the second run.  If I run the test manually on the command line, it succeeds.  If I run it through make on a clean checkout, it fails.  I'm looking into it, and will convent when I fix that issue.

**Comment by JasonGross** [comment]
This no longer fails, so i think there is no fix_needed @maximedenes, even if this still needs discussing.

**Comment by maximedenes** [comment]
So, there are two options here. Either we close this PR, or we move it two allow-fail. @ejgallego what shall we do?

**Comment by Zimmi48** [comment]
@ejgallego Clearly stated his opinion several times about this:
> I thus remain concerned about adding the minimizer to the main CI. I do not have a concern to add it as allow-fail.

> However it would be fine to merge this in allow fail if @JasonGross deems it useful.

> The allow-fail solution may have an advantage, that if after some time we deem the bug-minimizer stable, it could indeed be considered for promotion.

So the question is more which of the two options does @JasonGross choose? Is it useful to have this in allow-fail?

**Comment by JasonGross** [comment]
It would be useful to me to have it in allow-fail, especially if I can get Travis to email me when this particular ci (and only this ci) fails.  I'll plan to add the allow-fail line tomorrow, or one of you can do it.

**Comment by Zimmi48** [comment]
> It would be useful to me to have it in allow-fail, especially if I can get Travis to email me when this particular ci (and only this ci) fails.

@JasonGross Apparently, you cannot at the moment: travis-ci/travis-ci#7316. Instead, you could configure a cron job on the GitHub of your bug-minimizer to check each day if it is still compatible with Coq trunk: https://docs.travis-ci.com/user/cron-jobs/

Note that adding this target to the allow-fail category will still consume time and delay PRs so if it's not especially useful to you without the notification email setup, maybe it's not such a good idea to merge this.

**Pull request closed without merging**
