### PR TITLE
[stdlib][List] add inductive definition for list inclusion

### PR DESCRIPTION
**Pull request by nojb**
Following discussion in #12237 this PR proposes an inductive definition for list inclusion, which is already present in `List` under the name `incl` with a different definition.

This is my first contribution to the project, do not hesitate if you have any suggestions to share.

### CODE REVIEW

**Comment by olaure01** [comment]
I find the approach with:
```coq
Definition Incl (A : Type) (l l' : list A) := Forall (fun x => In x l') l.
```
that you mentioned in #12237 interesting: it allows to derive a number of properties of `Incl` from existing ones on `Forall`.

**Comment by nojb** [comment]
> I find the approach with:
> 
> ```coq
> Definition Incl (A : Type) (l l' : list A) := Forall (fun x => In x l') l.
> ```
> 
> that you mentioned in #12237 interesting: it allows to derive a number of properties of `Incl` from existing ones on `Forall`.

Indeed. I will give it a try. Thanks!

**Comment by nojb** [comment]
I rewrote it using `Forall`, which allowed for rather concise proofs, I would say.

**Comment by anton-trunov** [comment]
Hi @nojb and @olaure01!

I've noticed that most of the new lemmas in this PR can be proved by first defining the following piece of Ltac

```
Ltac Incl_to_incl := rewrite !Incl_iff_incl in *.
```
and then many of the proofs will be simply wrappers for the corresponding `incl`-lemmas:
```
Lemma Incl_<lemma> : ...
Proof.
  now intros <vars>; Incl_to_incl; apply incl_<lemma>.
Qed.
```
This provokes the thought that we should just have something like
```
  Definition Incl l m := Forall (fun a => @In A a m) l.
  Hint Unfold Incl : core.

  Lemma Incl_iff_incl : forall l m,
      Incl l m <-> incl l m.
  Proof.
    intros l m; unfold Incl.
    now rewrite Forall_forall.
  Qed.

  Ltac Incl_to_incl := rewrite !Incl_iff_incl in *.
```

and port the extra `Incl`-lemmas as the missing `incl`-lemmas. This would remove some code duplication. What do you think?

**Comment by olaure01** [comment]
@anton-trunov this looks convincing to me.

**Review by anton-trunov — CHANGES_REQUESTED** [review]
It would be great if we could make some progress here, basing on this suggestion https://github.com/coq/coq/pull/12276#issuecomment-671935736 (if that's ok with you @nojb)

**Comment by nojb** [comment]
> It would be great if we could make some progress here, basing on this suggestion [#12276 (comment)](https://github.com/coq/coq/pull/12276#issuecomment-671935736) (if that's ok with you @nojb)

Hi, sorry for having dropped the ball on this one. If you have the spare cycles to work on this, feel free to push directly to my branch (I believe you should be able to). Otherwise, I'll try to get around to it shortly.

**Comment by nojb** [comment]
Closing as this has completely fallen off my radar and won't have time soon to do the necessary changes... :(

**Pull request closed without merging**
