### PR TITLE
Check use of private inductives in the kernel

### PR DESCRIPTION
**Pull request by SkySkimmer**
Let's try #9609 again

Overlays:
- https://github.com/HoTT/Coq-HoTT/pull/1737 (backwards compatible)

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I think it would be useful to have a command to check the current proof term beyond `Guarded`. Not just for this but also for relevance marks and general typing issues.
Basically running Typing on it should be enough (not sure what we would do about any evar definitions / universe constraints Typing may add: ignore them, add them (so the command is effectful), just report them?)

But what to call this command? `Check Proof` sounds nice but collides with `Check` in an perhaps confusing way.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I think that the problem of having a checking command is unrelated to this PR. Hence @coqbot merge now

**Pull request merged**
