### PR TITLE
Produce warning+dynamic error on missing notation variable in Ltac2

### PR DESCRIPTION
**Pull request by SkySkimmer**
Lessen the impact of #17833

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
This is a very ugly hack but this is also a very messy area, so why not.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
Can this be backported to the v8.18 branch?

**Comment by Zimmi48** [comment]
If the 8.18.0 milestone has been properly configured, as documented in the release-process.md documentation, this PR would have been automatically added to the backport project. I've fixed this now (cc @maximedenes and @gares) and I've manually added the PRs that were already merged in 8.18.0 to the project (but the order may be random, in case there were dependencies between some of these PRs).

**Pull request merged**
