### PR TITLE
Standard headers for C and Python.

### LINKED ISSUE #6931: Some files don't have the default license header
See for example `kernel/byterun/coq_interp.c`.

It would probably be good to have variants of `dev/header` for the few languages we use.

### PR DESCRIPTION
**Pull request by maximedenes**
@Zimmi48 I don't know if the header file is used in a script (e.g. to update the header and check if it is present in all files).

Partially fixes #6931.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Nope. If I had made a proper script I would have shared it. Hopefully, the headers won't change anymore for a while now that they are quite generic, so only the year will have to be updated and having a script or a documented one-liner for this would be great.

**Comment by maximedenes** [comment]
@Zimmi48 do you approve?

**Review by Zimmi48 — APPROVED** [review]
Yes, sorry. Although, if you want my explicit approval, you should "request a review". Requested reviews and simple mentions do not appear the same in my notifications.

**Comment by Zimmi48** [comment]
In fact, I was wrong. My notification manager (octobox) did not put any particular mention for a "review required" on another PR. Damn!

**Pull request merged**
