### PR TITLE
[dune] Update to dune language version 2.0

### PR DESCRIPTION
**Pull request by ejgallego**
This is the minimal set of changes requires for Coq to build under 2.0
mode. We may likely take advantage of some more new features.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Why not target 8.11?

**Comment by ejgallego** [comment]
> Why not target 8.11?

I don't see the motivation, why would it be useful?

**Comment by SkySkimmer** [comment]
I think I misunderstood that current Coq would fail to compile for people who have dune 2 installed.

**Comment by ejgallego** [comment]
> I think I misunderstood that current Coq would fail to compile for people who have dune 2 installed.

Dune 2.0 still respects the `(lang dune 1.10)` in dune-project so indeed that's not a problem.

We will have to bump dune to 2.1 tho to fully bootstrap Coq, so that's the reason I'm keeping the dune-lang up to date.

**Comment by SkySkimmer** [comment]
>I recommend 4.07.1 , but indeed this version also has problems

What problems?

**Comment by ejgallego** [comment]
> What problems?

Developing Coq and Dune simultaneously is hard in 4.07.1 as merlin won't understand the `let+` syntax used in Dune.

**Review by Zimmi48 — COMMENTED** [review]
IIUC Dune 2.0 requires OCaml 4.06 (and Dune 2.1 will likely require OCaml 4.07). This should probably be mentioned in the relevant doc in `dev/doc`. This means it will also likely force our hand on the minimum supported OCaml version for Coq 8.12.

**Comment by Zimmi48** [comment]
@ejgallego Wouldn't the new `dune-action-plugin` library and the new `dynamic-run` action allow to remove the bootstrap phase without further updating Dune to 2.1?

**Comment by ejgallego** [comment]
> @ejgallego Wouldn't the new `dune-action-plugin` library and the new `dynamic-run` action allow to remove the bootstrap phase without further updating Dune to 2.1?

In the medium term it could indeed make sense to move the Coq part to the upcoming plugin API, tho it does need lots of work [including embedding coqdep] I'm unsure about what the action-plugin does support right now.

The original plan for coq_dune was indeed to use dune as a library, but it was recommended not to do so due to compat concerns; but at some point we may indeed move the support back to a plugin, even as an experiment.

**Comment by ejgallego** [comment]
Opam does provide now a way to build dune 2.0 in 4.05.0 [and older switches] , let's see how it goes indeed.

**Comment by Zimmi48** [comment]
> Opam does provide now a way to build dune 2.0 in 4.05.0 [and older switches] , let's see how it goes indeed.

That's good but not sufficient to e.g. package in Debian. Still, I think we should merge this PR, and we can debate later about the opportunity of making Dune the only build system in 8.12. Please mark this PR as ready for review when it is the case.

**Comment by ejgallego** [comment]
> That's good but not sufficient to e.g. package in Debian.

Debian testing already has 4.08.0 so that should not be a problem.

I will mark the PR ready for review when the windows build comes back to life.

**Review by Zimmi48 — APPROVED** [review]
I understand better now that the dependency of Dune on OCaml 4.06 should indeed not be a problem because opam will allow installing it for earlier versions of OCaml (like 4.05), so we can recommend people on Debian stable wanting to use the default OCaml version provided there to use opam to install Dune, and Coq 8.12 (if we switch to Dune as default build system) will be OK for Debian testing because it already has OCaml 4.08.

**Comment by Zimmi48** [comment]
Will merge on Friday if no more comments by then.

**Comment by SkySkimmer** [comment]
>> why not target 8.11
>I don't see the motivation, why would it be useful?

It's now preventing backport of ocamlformat #11257 over at https://github.com/coq/coq/pull/11093

**Comment by ppedrot** [comment]
I am marking this for backport then.

**Comment by ejgallego** [comment]
In fact I'd opt for not back porting #11257 instead, but as it makes you spend less time.

**Comment by ppedrot** [comment]
What do we lose by not backporting the ocamlformat changes? I'm not very clear on the topic.

**Comment by ejgallego** [comment]
You lose nothing, you can just backport the true patches.

**Comment by ppedrot** [comment]
OK, let's not backport then. Less work for the RM.

**Pull request merged**
