### PR TITLE
[ide] Move common protocol library to its own folder/object.

### PR DESCRIPTION
**Pull request by ejgallego**
The `ide` folder contains two different binaries, the language server
`coqidetop` and `coqide` itself.

These binaries have only in common that they link to the protocol
files, but in the rest, they are totally unrelated.

In order to clean up the build, we move the common protocol files to
its own library `ideprotocol`.

This helps towards integrating Dune and an IDE standalone make target,
such as the one that was implemented here:
https://github.com/ejgallego/coqide-exp

D̶e̶p̶e̶n̶d̶s̶ ̶o̶n̶ ̶#̶6̶8̶5̶9̶ ̶

### CODE REVIEW

**Comment by ejgallego** [comment]
Sorry for the PR stacking but I needed to get this out of my harddrive.

**Comment by SkySkimmer** [comment]
>Sorry for the PR stacking but I needed to get this out of my harddrive.

What does that mean?

**Comment by ejgallego** [comment]
> What does that mean?

It means that this PR depends on other, so codeowners etc... are incorrect.

I am trying to avoid that in new PRs, but it is harder to do in older PRs such as this one, that has been dormant in my HD for some months already.

**Comment by SkySkimmer** [comment]
You know you can push to github without making a PR right?

**Comment by ejgallego** [comment]
> You know you can push to github without making a PR right?

When I say "get out" I mean to actually expose the change so people have time to react.

**Comment by gares** [comment]
I understand what your last commit does, but I don't get why. I mean, "clean up the build" is not very clear.
What is the problem this reorganization solves?

**Comment by ejgallego** [comment]
> I understand what your last commit does, but I don't get why. I mean, "clean up the build" is not very clear.
> What is the problem this reorganization solves?

I'll try to improve the message, but what this basically allows is to have the builds of `ide_slave` and `coqide` to proceed separately in a cleaner way. See the linked repository in the description.

In the OCaml world, having "doubly linked" files is considered a bit of ugly practice, so it is better to put them in a single `cma`, and some build systems such as Dune actually enforce that as a sanity measure.

**Review by gares — APPROVED** [review]

**Comment by ejgallego** [comment]
This is ready to merge now.

**Comment by ejgallego** [comment]
@ppedrot I think you are the one to react here?

**Review by ppedrot — APPROVED** [review]
No strong opinion on this change.

**Comment by ejgallego** [comment]
Merci.

**Pull request merged**
