### PR TITLE
[ci] [gitlab] Remove Windows jobs.

### LINKED ISSUE #9213: Windows CI: source cache is not reused between CI runs
This is similar to #9212, but is a about the cache for downloaded source archives. This might be more controversial, because it might not be easy to setup a source cache such that malicious pull requests cannot badly influence the outcome of future runs on the same machine. One can easily achieve that existing files cannot be overwritten, but it would be tricky to ensure that only properly named files are in the cache.

### LINKED ISSUE #9401: Creation of Windows workers should be documented or automated
This issue is a reminder that we should either document the creation of workers on the Inria CloudStack infrastructure, or migrate to a platform like Azure where such creation is transparent for us.

### PR DESCRIPTION
**Pull request by ejgallego**
cc #7171, cc #7428 , closes #8622 , closes #9213 , closes #9401

Our windows worker setup has been problematic since day 1, and it is
creating frequent failures and other problems that cannot be publicly
disclosed.

IMSO this situation is not acceptable, the time has come to remove
them from our main CI infrastructure and have the Windows maintainers
implement the workflow in Azure / Travis.

### CODE REVIEW

**Review by maximedenes — CHANGES_REQUESTED** [review]
I would like this to be discussed before we take a decision on it.

**Comment by maximedenes** [comment]
> OK, so let's start the discussion.

Well, you mention some problems that cannot be disclosed publicly, so we need to find another place.

**Comment by ejgallego** [comment]
> Well, you mention some problems that cannot be disclosed publicly, so we need to find another place.

That discussion was already had for the most part, well, if we merge this PR then we can make it public :)

We can go back to offline if you want, sure.

**Comment by maximedenes** [comment]
> That discussion was already had for the most part

Well, I'm the one who put these workers online, but I have no idea what discussion you are referring to.

For the purpose of this discussion, I think you should clarify the concrete motivation and ping the relevant persons (I imagine @vbgl who was recently looking at these failures, and @MSoegtropIMC who's working on the windows scripts).

**Comment by ejgallego** [comment]
> Well, I'm the one who put these workers online, but I have no idea what discussion you are referring to.

Thread name already gives away too many details :)

That's the start of it `Message-ID: <87lg7s8e0o.fsf@x80.org>`

**Comment by MSoegtropIMC** [comment]
@ejgallego : I honetsly don't understand what you want to say with the linked issues.

<https://github.com/coq/coq/issues/7171> as far as I can tell the Windows CI tests more installation steps than any other CI test we do. At least it does call make install. See e.g. <https://github.com/Mtac2/Mtac2/pull/220> which was found on the Windows installer. It just doesn't test if the NSIS installer creates a faitfull image of that, but we never had issues with this, so this is low prio.

<https://github.com/coq/coq/issues/7428> the main stability issue are network outages between INRIA runners and gitlab servers, which happen about twice a month. I don't see how docker would solve this. In my experience docker behaves very badly if images are just killed (as the gitlab runner does in such situations) leaving a lot of debris around.

<https://github.com/coq/coq/issues/8622> I created a PR for this which, if I remember right, you rejected. It is not that fair that you now complain that this is not done.

<https://github.com/coq/coq/issues/9213> As discussed in the ticket this might not be advisable security wise. Also afaik the other CI tests we do don't have a source cache either and moving to Azure or docker also wouldn't change this. But it is a substantial inefficiency we might be able to solve one day.

<https://github.com/coq/coq/issues/9401> #8622 contained also documentation for handling the runners beyond what is anyway documented in INRIA VM docs and gitlab runner docs. See <https://github.com/MSoegtropIMC/coq/blob/832389eea35b4ff5e43c88ed4fcc94a988b6b375/dev/ci/tools/runner-maintanance/ReadMe.md>

Besides the disk full issues (caused by network issues) which could be solved in various ways, either by asking an INRIA IT supporter to follow the maintenance docs once a months or by removing the unique folder name stuff and deleting teh ci folder before each run. This was initially not done because we didn't understand what the issue was.

I honestly don't understand why you propose the removal of this test of an important part of our delivery without providing a replacement beforehand. I found fixing the bugs in CoqIDE after moving to GTK3 more important than this and had no time left. Travis has been discussed to be not an option cause of the time limits. The full build takes more than 4 hours, including artifact upload, while travis has a limit of what - 1 hour?). For Azure you said yourself some time back that it is tricky to get cygwin running there. Not sure what came out of this - I never tried. Also I am not sure what time limits Azure has. I guess one would have to split up the build, which might be substantial effort.

**Comment by ejgallego** [comment]
> #8622 I created a PR for this which, if I remember right, you rejected. It is not that fair that you now complain that this is not done.

I don't remember rejecting that concrete PR, but indeed I cannot support a system that requires such maintenance.

**Comment by MSoegtropIMC** [comment]
> I cannot support a system that requires such maintenance.

I am absolutely fine to have this changed. Is there any reason why you didn't setup an Azure build running the existing build scripts? The last thing I heard about this was that you tried and had issues with Cygwin.

**Comment by SkySkimmer** [comment]
The current azure scripts ue cygwin so it works at least enough for what we do there.

**Comment by MSoegtropIMC** [comment]
> The current azure scripts ue cygwin so it works at least enough for what we do there.

If I remember right, the issue was that the cygwin was preinstalled on Azure and that it was hard to change the packages or to install additional cygwins. But I never tried it myself. I will have a look at the existing Azure scripts next week.

**Comment by Zimmi48** [comment]
At least installing additional packages is doable since it is done for the test-suite job.

How far are we from being able to build the Coq packages on Windows using opam? And would it be sufficient to avoid installing a custom cygwin?

**Comment by XVilka** [comment]
Opam is [not yet ready](https://github.com/ocaml/opam/issues/2191) to handle the Windows without Cygwin. There are some [unsolved problems](https://github.com/ocaml/ocaml/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+windows) in OCaml itself (though not all of them are critical). Maybe @dra27 can tell more if it will be feasible in the near future.

**Comment by Zimmi48** [comment]
Thanks @XVilka for this valuable info, although my question was rather how far we are from building Coq on Windows using the special Windows opam, which itself depends on cygwin. In particular, the interest of this technique would be that our Windows packaging scripts wouldn't need to install a custom version of cygwin when run on Azure...

**Comment by SkySkimmer** [comment]
The windows32 job recently caught a bug, I think we can't remove those jobs without first having an alternative and so suggest closing this PR.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer: I agree. I am way busy with moving to Mac but plan to finish the Windows stuff (opam based builds, developer build, ...) end of this year.

**Comment by ejgallego** [comment]
> The windows32 job recently caught a bug, I think we can't remove those jobs without first having an alternative and so suggest closing this PR.

On the contrary, this PR is more relevant than ever as our windows infrastructure is in real bad state. For example, it seems only one runner does survive, and there are other issues as detailed elsewhere. If the remaining runner fails we will have no alternative but to merge this PR [note that a 32bit build could be added to Azure]

As replacements, we have Azure, and the Azure-by-gitlab version called "Gitlab Actions", these are promising IMHO but we need a rewrite of the whole packaging infrastructure which is hard to do for those of us who don't use win.

**Comment by Zimmi48** [comment]
Did you mean "GitHub Actions"? I've never heard of "GitLab Actions".

**Comment by ejgallego** [comment]
> Did you mean "GitHub Actions"? I've never heard of "GitLab Actions".

Indeed, sorry @Zimmi48 , I mean Github Actions [which is just azure integrated on github]

**Comment by MSoegtropIMC** [comment]
@ejgallego : if there are issues with the runners it would help if someone sends me a notification. With the right scripts (for which I once did a PR a year back which was rejected cause of the soon to happen switch to azure) it takes hardly 5 minutes to bring them all in good shape again. I recently gave instructions to @thery on how to do this. I think it would also make sense to delegate a job to INRIA IT service to have a look at the runners every 2 weeks. Btw.: since I switched companies I couldn't find out how to subscribe to the coq-dev mailing list so I don't read what is discussed there. I will have a look at the runners tonight (don't have a Windows machine here).

**Comment by SkySkimmer** [comment]
I still think this should be an issue, not a PR.

**Comment by SkySkimmer** [comment]
We already have issues to track why we may want to do this eventually, but we're not ready to do it so closing.

**Pull request closed without merging**
