### PR TITLE
CI: build bedrock2 compiler examples in separate job

### PR DESCRIPTION
**Pull request by SkySkimmer**
They are very slow

### CODE REVIEW

**Comment by andres-erbsen** [comment]
Note that this also removes the main hardware-software integration-proof case study. I don't have opinions on whether it should be included in normal CI runs, but I think as a benchmark it is a rather unique workload, exactly in the slow file KamiRiscv.

**Comment by andres-erbsen** [comment]
Cc @samuelgruetter do you have opinions? I think the background is this [Zulip discussion](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/examples.20in.20bedrock2.20take.20a.20long.20time) about liveverif on the critical path through fiat-crypto.

**Comment by Shadow666gamer** [comment]
Mi Mi ***@***.***> ezt írta (időpont: 2024. szept. 16., H 18:50):

**Comment by SkySkimmer** [comment]
>Note that this also removes the main hardware-software integration-proof case study. I don't have opinions on whether it should be included in normal CI runs, but I think as a benchmark it is a rather unique workload, exactly in the slow file KamiRiscv.


It is not the only slow file.

**Comment by SkySkimmer** [comment]
I think it's worth merging this even if only for increased possible parallelism, the only question is if we should add a bedrock2_examples job

**Comment by andres-erbsen** [comment]
:+1:  Yes, I'd prefer the case studies to be still tested (I also tried to express this on Zulip).

**Comment by SkySkimmer** [comment]
Added a job for the examples

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@andres-erbsen if you're fine with the current state, I can merge right away.

**Comment by andres-erbsen** [comment]
Yes, this looks good to me.

Later: Do we have a reliable way to evaluate the need for NJOBS=1? It may not longer be needed for the main bedrock2 job.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
