### PR TITLE
proof that R is uncountable

### PR DESCRIPTION
**Pull request by VincentSe**
**Kind:** feature.

This is my first pull request to Coq, so it is probably wrong in many places. It is only a new proof, that R is uncountable, it doesn't modify Coq's OCaml code. I am not sure about the header I copied into Runcountable.v. I do accept it is released under the Lesser GPL.

I am not a researcher and I did this on my free time, so I did not put an organisation next to my name in the CREDITS file.

The first part of the proof is a slight extension of Coq.Logic.ConstructiveEpsilon. But I did not modify this file because I do not know yet the coding conventions of Coq.

I could not run the test suite. Even before my modification, make test-suite fails on commit 56b355e9e3e0394625cc40084f7cf11a949ebb29, with this error:

TEST      unit-tests/printing/proof_diffs_test.ml
TEST      unit-tests/clib/inteq.ml
TEST      unit-tests/clib/unicode_tests.ml
make[3]: Entering directory '/home/vincent/coq/test-suite'
BUILDING SUMMARY FILE
FAILURES
    coq-makefile/findlib-package/run.sh...Error!
    coq-makefile/timing/run.sh...Error!
Makefile:198: recipe for target 'report' failed
make[3]: *** [report] Error 1
make[3]: Leaving directory '/home/vincent/coq/test-suite'
Makefile:119: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/vincent/coq/test-suite'
Makefile.build:627: recipe for target 'test-suite' failed
make[1]: *** [test-suite] Error 2
make[1]: Leaving directory '/home/vincent/coq'
Makefile:165: recipe for target 'submake' failed
make: *** [submake] Error 2

The 2 failed tests I noticed are below, but make report fails so I don't know what is wrong with them:
FAILED    coq-makefile/timing.log
FAILED    coq-makefile/findlib-package.log

I did check that coqc accepts Runcountable.v.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
About the test suite, you can look at the log files for details. Please come talk on gitter or the coqdev mailing list or open an issue if you still have problems with it.

**Comment by VincentSe** [comment]
apt-get install time solved the first test. For findlib-package, the log file says this error, which I don't understand:
Fatal error: unknown C primitive `coq_set_bytecode_field'

I posted it on gitter too.

**Comment by Zimmi48** [comment]
>I am not sure about the header I copied into Runcountable.v. I do accept it is released under the Lesser GPL.

The header you copied is indeed outdated. You can find the correct one in `dev/header.ml`.

>I am not a researcher and I did this on my free time, so I did not put an organisation next to my name in the CREDITS file.

That's fine. Maybe just put "2018" for now instead of "2018-now".

>The first part of the proof is a slight extension of Coq.Logic.ConstructiveEpsilon. But I did not modify this file because I do not know yet the coding conventions of Coq.

There are no clear coding conventions for the standard library yet, and a lot of older files would need to be updated to use a more modern style.

Finally, note that building the documentation fails because all files in the standard library must be listed in `doc/stdlib/index-list.html.template`.

**Comment by VincentSe** [comment]
I'm still waiting for it to be merged

**Comment by Zimmi48** [comment]
The maintainer for this part is @silene and he's been under the water lately with the release management and other stuff. We can ping him in person, or we can ask the second code owner @ppedrot what he thinks of this.

**Comment by VincentSe** [comment]
The constructive epsilon is for N, not for R. In the proof it gives the smallest index of a real number in a given real interval.

**Comment by herbelin** [comment]
> The constructive epsilon is for N, not for R.

Sorry, I made a confusion.

Then, yes, it could and should better be in `ConstructiveEpsilon.v`, which as far as I can see import `Arith` and thus has `le_lt_trans` and `le_lt_or_eq`. (Note also the possibility to use `Wf_nat.dec_inh_nat_subset_has_unique_least_element` but why not to do a direct proof also.)

The result seems otherwise worth to me to be integrated. I let a new week for discussions and shall otherwise merge at the end of next week.

Side remark, there should be in theory a better place for `enumeration`. Maybe a new file `Enumeration.v` in `Sets` but that is somehow going beyond the scope of the PR. And somehow, what is more generally missing is some infrastructure to get isolated statements from large libraries seen as name spaces, à la "we import definition Enumeration from library Set" without drawing unnecessary things. Matita is proposing that.

**Comment by VincentSe** [comment]
I am on holidays in Bolivia for the next 3 weeks, without access to a Coq compiler. I can do all the corrections you mention when I return. Otherwise, feel free to split and rearrange the proof as you see fit. It'll teach me the coding conventions of Coq.

**Comment by VincentSe** [comment]
Hola que tal? So what do we do with this pull request?

**Comment by herbelin** [comment]
> Hola que tal? So what do we do with this pull request?

Let's wait for your return from holidays.

**Comment by VincentSe** [comment]
Ok I'll be back next Thursday. I think I can replace the constructive epsilon by wf_nat has least element, as you suggest.

Also, enumeration looks doable with FinFun.Bijective.

Is there something else to correct?

**Comment by herbelin** [comment]
> I think I can replace the constructive epsilon by wf_nat has least element, as you suggest.

My remark was in passing. Do as you prefer (move `epsilon_smallest` to `ConstructiveEpsilon`, or use `wf_nat`).

> Also, enumeration looks doable with FinFun.Bijective.

Yes, that'd be good.

> Is there something else to correct?

That's ok as far as I'm concerned. Tell me when you are back to it.

**Comment by silene** [comment]
The proof does not depend on any spurious axiom, so that is fine with me. But I am a bit surprised by the final statement. I would have expected

    forall v : R -> nat, not (forall x y : R, v x = v y -> x = y)

or

    forall v : R -> nat, exists x y : R, v x = v y /\ x <> y

The latter might be impossible to prove in Coq's setting without an additional axiom. But I do not see either how to deduce the former statement from yours, so there is something a bit disturbing here.

That said, the following statement should be derivable from yours:

    forall u : nat -> R, not (forall x : R, exists y : nat, v y = x)

**Comment by VincentSe** [comment]
I tried git fetch upstream and git merge upstream/master but it failed.

So then I did git checkout upstream/master, git merge proofRuncountable and git push origin HEAD:proofRuncountable.

**Comment by Zimmi48** [comment]
@VincentSe You should go back to commit 92d81ef5771d0f35fce8274aa767d79b6a1d3942 with `git reset --hard 92d81ef5771d0f35fce8274aa767d79b6a1d3942` then do a proper rebase on master with `git rebase master`.

**Comment by Zimmi48** [comment]
Sorry I did not see your comment above. First make sure your master branch is reflecting upstream by doing `git checkout master && git reset --hard upstream/master` then switch back to your `proofRuncounatable` branch before applying the commands above.

**Comment by Zimmi48** [comment]
:disappointed: I'm pretty sure there was a way to fix this that did not require to delete the branch.

**Comment by VincentSe** [comment]
I just re-pushed the rebased branch, can we open again this pull request ?

**Comment by VincentSe** [comment]
I opened another pull request Proof runcountable #8887 instead

**Pull request closed without merging**
