### PR TITLE
Improve boxing in coqpp output

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should make it nicer to read the generated files when trying to understand what coqpp does.

### CODE REVIEW

**Comment by ejgallego** [comment]
Could be fun to try to use ppx to process the grammar files, as an experiment, newer ppx stack is much more user friendly and maintenable. Should not take more than a couple of hours.

Not sure if that is what you mean @herbelin ?

**Comment by herbelin** [comment]
I don't really know ppx. What I meant is that when the ocaml part of a mlg fails to compile, the location of the reported error is a bit approximative. That's apparently related to these `#` things in the ml files but I don't know how it works.

**Comment by SkySkimmer** [comment]
>Digression


Please don't do that. we have zulip and issues for that.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
