### PR TITLE
Properly close aux file after loading it

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
Newer OCaml has `Stdlib.In_channel.with_...` which is superb.

Maybe we could copy that API in a `FutureOCaml` module, so at some point we just have to remove the vendored code from upstream?

**Review by ejgallego — APPROVED** [review]
Other than my comment, this is good.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@ejgallego maybe we should merge this for the time being regardless of the ideal solution.

**Comment by ejgallego** [comment]
Yes I agree @ppedrot , I was just too busy with visitors this week; I let @SkySkimmer react to my comment, but indeed ✅

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
