### PR TITLE
[v8.7] Speed up fiat-crypto CI

### PR DESCRIPTION
**Pull request by JasonGross**
This removes a couple thousand useless calls to coqdep from the
fiat-crypto CI, giving us a bit more breathing room.  This is only for
v8.7; for v8.8, #6217 should be merged.

### CODE REVIEW

**Comment by maximedenes** [comment]
Why not apply this to master too? I agree #6217 should be merged, but that is orthogonal.

**Comment by JasonGross** [comment]
This should be reverted when #6217 is merged.  What this does is tell fiat-crypto to forget about all the autogenerated files, which are presently not built in the CI.  Ideally, it should not be forgetting about them, and coqdep should be fast enough to handle them.  If you want, I could retarget this to master, though, and leave open a PR to revert it which is blocked on #6217.  Shall I do that?

**Comment by Zimmi48** [comment]
I suppose that your argument make sense. Thus, I'm OK to merge this only in v8.7 if @maximedenes is OK.

**Comment by maximedenes** [comment]
I must confess I don't understand the whole picture with those generated files, so do as you like :)

**Comment by JasonGross** [comment]
If Coq and the CI were fast enough, we'd be testing all the generated files on each CI run.  Alas, we're not there (yet).

**Comment by JasonGross** [comment]
@Zimmi48 Is this closed now?  (It looks like you merged but GH didn't close?)

**Comment by Zimmi48** [comment]
Don't worry. I've merged it but only in my fork. I'm testing this on my Travis, as well as a bunch of backports at the same time. I'll push upstream when it passes.
So don't push to the branch, don't delete it. The PR will be closed automatically when I push upstream.

**Comment by Zimmi48** [comment]
Here we go.

**Comment by williammpratt** [comment]
Please learn the correct quoting rules for the shell you are using.

**Pull request merged**
