### PR TITLE
[contributing] [changes] Improve accuracy of credits.

### PR DESCRIPTION
**Pull request by ejgallego**
It has been a while that I am not very happy with our current system
to record changes and credits. I see several problems:

- imprecise credit for many features, for example, reviewers are not
  acknowledged [and are sometimes crucial for the design, etc...],
- dissociation of credits and change entries,
- lack of categorization / systematization.

This is indeed a hard problem to solve (cc: #8180) ; in this PR I have
a very modest proposal improve accuracy and traceability by adapting
the model used in OCaml.

In this model, every change entry includes the name of the author, the
PR numbers, and a list of additional acknowledgements, where revievers
are usually mandatory.

I have filled in the information for a few entries I am responsible
of; please let me know what you think.

### CODE REVIEW

**Comment by ejgallego** [comment]
> * some of the developers/contributors have rather cryptic github nicknames, maybe we could use real names when they are known from us

I do agree, however with real names the credits entry tends to get very large and outshine the change entry itself, so I am not sure what the right tradeoff here is.

> * it seems to me that only user-visible changes will be credited, whereas we may want to also credit large clean-ups and redesign. It is not so much because I spend most of my time on this kind of activity ;) but rather that I'd like to see it incentivized for other developers

Indeed that's a problem I'm well aware of :) We should also do this to `dev/doc/changes` or course.

Maybe we should have `NEWS.md` where the main relevant user news are, and `CHANGES.md` should be a complete list of all changes / PR sorted in some order.

I dunno, after all this is not an exact science.

**Comment by Zimmi48** [comment]
For a new project I really like this format for the changelog (it is the one used by Dune IIRC). However, in the case of Coq, I am unsure that this change on its own constitutes an improvement because it seems to me that we already have a lot of duplication of information (between `CREDITS`, `CHANGES`, the Credits chapter and the GitHub release notes) and this change seems to increases the duplication instead of reducing it. I would like this change to be part of a more general plan.

Furthermore, I agree with Maxime's second concern. `CHANGES` was a place for users to look at to learn about the most important information while upgrading. If we start crediting in this file, then there is no reason for not including everything that deserves credit, including large clean-ups, that are not necessarily of direct interest to the reader (no reason to bury this into `dev/doc/changes.md` either). In a sense, the separation between the Credits chapter (for credit and historical purposes) and the `CHANGES` file (for minimum information at the time of upgrade) seems to work well.

That being said, I would also be OK with a full consolidation of all this information in a single place (this is probably the only way to avoid duplication entirely): as long as we give it enough structure, like OCaml tries to do, it should be reasonable.

I generally agree with your initial considerations, including the one about the lack of credits for PR reviewers.

**Comment by ejgallego** [comment]
Should we then use `CHANGES` for all changes + credits, and `NEWS` for user-related information?

**Comment by Zimmi48** [comment]
Whichever solution is chosen must also include a strategy for the future of the Credits chapter.

**Comment by ejgallego** [comment]
> @ejgallego Some unrelated commits are included (at least according to the github UI)

Indeed thanks, I guess I did rebase against the wrong master.

**Review by gares — CHANGES_REQUESTED** [review]
Please resolve GitHub logins to real names.
We may move to another platform and these files would lose meaning. Also users do not necessarily know  these nicks.

**Comment by ejgallego** [comment]
@Zimmi48 let me know how should I proceed with this.

**Comment by Zimmi48** [comment]
@ejgallego I think I have mostly taken your recommendations into account in my work to consolidate changes and credits (#9668, #9939, #9964), so this PR could be closed. Let me know if I've missed something.

**Comment by ejgallego** [comment]
Thanks @Zimmi48 for all the great and time-consuming work. IMHO this is good to close; I hope I can have a deeper look some of these days.

**Pull request closed without merging**
