### PR TITLE
[readme] Add DOI badge.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by maximedenes** [comment]
Zenodo says "This DOI represents all versions, and will always resolve to the latest one.", but it seems like it shows V8.7+beta2 (maybe because of the V). Is there a way to fix that? Do we really want to cite beta versions?

**Comment by Zimmi48** [comment]
You didn't use the right one. You should use https://doi.org/10.5281/zenodo.1003420. That's the one that Zenodo will resolve to the latest version.

**Comment by ejgallego** [comment]
Ups indeed, somehow I didn't copy the right link. Fixed.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
> Do we really want to cite beta versions?

We may just decide not to create a new version on Zenodo when releasing a beta. OTOH it might allow some people writing a paper to cite the latest version earlier on.

**Pull request merged**
