### PR TITLE
remove compute_possible_guardness_evidences

### PR DESCRIPTION
**Pull request by Alizter**
Mostly an experiment to see why we are doing so much checking in the upper layers.

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
I can't tell if elpi is related. But seeing as this didn't cause any issues in the CI, it might be worth considering.

**Comment by SkySkimmer** [comment]
This provides early failure for Program Fixpoint:
~~~coq
Require Import Program.Tactics.

Program Fixpoint F (n:nat) : False :=
  match n with
  | 0 => F n
  | S k => _
  end.
(* master: Recursive definition of F is ill-formed.
	this PR: 1 obligation remaining, Qed/Defined of the obligation fails
 *)
~~~

**Comment by Alizter** [comment]
Thanks @SkySkimmer. Have you got a suggestion on what might be a better way to do this check?

**Pull request closed without merging**
