### PR TITLE
Fix cbv evar case

### LINKED ISSUE #18194: cbv on undefined evars under binders when the substitution involves cases produces unbound rel
#### Description of the problem
```coq
Eval cbv zeta in (fun (a : True) => (?[T] : True),
  let r :=
    let b := I in
    match tt with tt => b end
  in
  ?T@{a := r}).
```
```coq
= (fun a : True => ?T, ?T@{a:=match tt with
                              | tt => _UNBOUND_REL_1
                              end})
: (True -> True) * True
where
?T : [a : True |- True]
```

this can be turned into something which fails because of it, although the instance I found is contrived.

```coq
Require Import Coq.Program.Tactics.

Program Definition a := Eval cbv zeta in (fun (a : True) => (?[A] : nat),
  let r :=
    let b := I in match tt with tt => b end
  in
  ?A@{a := r},
  fun (a : True) => (eq_refl : ?A = _)).

Next Obligation.
  destruct a; exact 0.
Defined.
```
```
File "/tmp/foo.v", line 12, characters 0-8:
Error:
Unbound reference: In environment
anonymous' : unit
The reference 3 is free.
```

#### Coq Version
8.18.0, master

#### Fix
https://github.com/coq/coq/blob/f202dcb508508373702cdb3cc6a50b1b36d29cc8/pretyping/cbv.ml#L374
```diff
-        (mkCase (ci, u, pms, ty, iv, t,br))
+        (apply_env @@ mkCase (ci, u, pms, ty, iv, t,br))
```
PR #18195

### PR DESCRIPTION
**Pull request by yannl35133**
Fixes #18194

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Well spotted! Could you also add the test?

**Comment by herbelin** [comment]
Not sure it needs a full ci (others may know better than me). A change log telling it fixes #18194 would however be good (using `dev/tools/make-changelog.sh`).

**Comment by ppedrot** [comment]
It doesn't hurt to run a full ci: @coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
CI failures are spurious, so @coqbot merge now

**Pull request merged**
