### PR TITLE
Print type of offending expression in Ltac2 not-unit warning.

### PR DESCRIPTION
**Pull request by ppedrot**
Partial fix of #14013.

### CODE REVIEW

**Review by JasonGross — APPROVED** [review]
Do we want an output test?

**Comment by ppedrot** [comment]
@JasonGross would you assign? I don't think the output test is really necessary btw.

**Comment by JasonGross** [comment]
@coqbot: merge

**Comment by JasonGross** [comment]
@coqbot merge

**Comment by JasonGross** [comment]
@coqbot merge now

**Pull request merged**
