### PR TITLE
Take Suggest Proof Using outside the kernel.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Also add an output test for Suggest Proof Using.

This changes the .aux output: instead of getting a key
>context_used "$hyps;$suggest"

where $hyps is a list of the used hypotheses and $suggest is the
;-separated suggestions (or the empty string if Suggest Proof Using is
unset), there is a key
>context_used "$hyps"

and if Suggest Proof Using is set also a key
>suggest_proof_using "$suggest"

For instance instead of
112 116 context_used "B A;A B;All"
we get
112 116 context_used "B A"
112 116 suggest_proof_using "A B;All"

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I don't know if there's a specification of the .aux anywhere, or if someone is using the part I changed.

Also I'm not sure if I put the `Proof_using.suggest` calls at the right place.

**Comment by SkySkimmer** [comment]
@herbelin https://github.com/coq/coq/pull/883#issuecomment-315632321
>By the way, I'm wondering about Set Suggest Proof Using. It is a very valuable feature but is there any reason it is in the kernel? In addition from being useless for checking, this has the drawback that the proper printers for kernel names are not available and one sees a debugging-style printing of the form Top#A#foo. At least, only the basename should be printed.

I tried using `Printer.pr_constant` but there's some dependency issue (printing/ comes after proofs/). I don't know how this is supposed to work.

**Comment by ejgallego** [comment]
By the way, I think `context_used` serves no purpose currently [`pua` variable in the STM], so we may want to get rid of that too. @gares , what was the idea for this?

**Comment by ejgallego** [comment]
> I tried using Printer.pr_constant but there's some dependency issue (printing/ comes after proofs/). I don't know how this is supposed to work.

For the most part I think printers are in the wrong place of the hierarchy; instead of being defined in the module the datatype is defined, they are all placed together. That doesn't make a lot of sense I think, but there could be some different reasons for that.

**Comment by SkySkimmer** [comment]
>By the way, I think context_used serves no purpose currently [pua variable in the STM], so we may want to get rid of that too. @gares , what was the idea for this?

The STM uses aux file stuff?

**Comment by ejgallego** [comment]
This is very welcome and it was in my TODO list; however I think further cleanup is deserved; give a few minutes so I prepare a patch on top of yours.

**Comment by ejgallego** [comment]
> The STM uses aux file stuff?

Mainly the timing to see if a proof "is too expensive to delegate" I am not sure it makes sense.

**Comment by ejgallego** [comment]
@SkySkimmer have a look at this, and if it looks good to you please pull to your branch https://github.com/ejgallego/coq/commits/SkySkimmer-proof-using

**Comment by ejgallego** [comment]
You can indeed call the proper printer now.

**Comment by ejgallego** [comment]
The use in the STM of `get_hint_ctx` loooks very suspicious....

**Review by ejgallego — APPROVED** [review]
Much needed cleanup, thanks!

You may optionally use a different printer as suggested by @herbelin if you feel like it.

**Comment by silene** [comment]
> I don't know if there's a specification of the .aux anywhere, or if someone is using the part I changed.

It is hard to tell from your patch if you changed it (and maybe it no longer worked anyway), but it was used when processing interactively a script that was not explicitly using `Proof Using`. The first time the script was processed, complete proof evaluation had to be performed, so that the correct types were obtained at the end of sections. The second time the script was processed, Coq was reusing the information stored in the `.aux` file, so that proofs could be delayed indefinitely.

> Mainly the timing to see if a proof "is too expensive to delegate" I am not sure it makes sense.

I remember seeing benchmarks for the mathcomp library. It was making Coq several orders of magnitude faster (lots of small proofs that were expensive to serialize and delegate).

**Comment by ejgallego** [comment]
> I remember seeing benchmarks for the mathcomp library. It was making Coq several orders of magnitude faster (lots of small proofs that were expensive to serialize and delegate).

Well, in order to generate the `.aux` file with timings you have to run the file anyways.

I think I'd favor the STM doing some static analysis on the proof to build a "proof cost" and use that for scheduling; but first we need to decouple scheduling from document building.

**Comment by maximedenes** [comment]
> I think I'd favor the STM doing some static analysis on the proof to build a "proof cost"

Is that realistic? What cost would you give to `Proof. crush. Qed.`?

**Comment by silene** [comment]
> Well, in order to generate the .aux file with timings you have to run the file previously anyways.

You are missing the point. Do you know how many times I type `make` every day? I might have to recompile thousands of lemmas, yet only one was actually modified. For all the other ones, the decision of delegating or not is still valid!

**Comment by ejgallego** [comment]
> Is that realistic? What cost would you give to Proof. crush. Qed.?

It looks to me that `crush` would have quite a high cost from looking at its definition. Worst-case is that `crush` is not delegated, which is what happens today [the cost function should be under-approximating]

> You are missing the point. Do you know how many times I type make every day? I might have to recompile thousands of lemmas, yet only one was actually modified. For all the other ones, the decision of delegating or not is still valid!

I am not missing any point; your use case is as valid as the use case of the user that wants to compile a package for the first time. Of course is timing information is available it would be good to use it.

I am very curious now? Are you indeed using the STM capabilities to delegate the construction of `.vo` files? Care to share your setup / parameters?

**Comment by ejgallego** [comment]
Anyways, your use case is not properly handled by parallel proof building/checking but by some kind of incremental compilation.

**Comment by SkySkimmer** [comment]
>It is hard to tell from your patch if you changed it (and maybe it no longer worked anyway), but it was used when processing interactively a script that was not explicitly using Proof Using. The first time the script was processed, complete proof evaluation had to be performed, so that the correct types were obtained at the end of sections. The second time the script was processed, Coq was reusing the information stored in the .aux file, so that proofs could be delayed indefinitely.

OK I see that, this PR shouldn't break it.

**Comment by ejgallego** [comment]
> It is hard to tell from your patch if you changed it (and maybe it no longer worked anyway), but it was used when processing interactively a script that was not explicitly using Proof Using. The first time the script was processed, complete proof evaluation had to be performed, so that the correct types were obtained at the end of sections. The second time the script was processed, Coq was reusing the information stored in the .aux file, so that proofs could be delayed indefinitely.

This seems very very suspicious, doesn't it? Imagine I process my `Theorem foo` which is using hyp `A`. Now, I change the proof so it will use hyps `A B`, however, the STM is getting the stale information from the aux file and using that?

**Comment by ejgallego** [comment]
Another question, why do we have both `context_used` and `suggest_proof_using` ?

**Comment by herbelin** [comment]
> I tried using Printer.pr_constant but there's some dependency issue (printing/ comes after proofs/). I don't know how this is supposed to work.

You could have used also `Termops.print_constr`. That's true that where printers are, late in the linking hierarchy is not (always) very convenient. For global references however, it is better to have the `Nametab`.

**Comment by ejgallego** [comment]
@herbelin well, in this case IMVHO the badly located component was the proof_using module, not the printers; note that now all printers can be used.

**Comment by gares** [comment]
Sorry, I've arrived late in the discussion here.

Yes, the STM uses the aux files (or better the data they contain) in two ways.
- When you process interactively (in coqide) a file, the records (inside the STM) how long it took to delegate a lemma. If it is not convenient to do so, next time you process the same lemma (a lemma with the same name) it will choose not to delegate it.  Such data is not stored in the aux file, but such "memory" can be pre-seeded with an aux file
- in `-quick` mode such memory is pre-seeded with the `aux` file, if available and still up to date (it contains a hash of the source file).

IIRC there are 2 entries in the aux file, the literal list of variables used (that is what the STM need in quick mode) and a more "palatable" representation of such variable set one can use to write `Proof using` annotations.  Such data is there (together with a location) because one can craft a script that adds these annotations to .v file automatically. I never managed to make such script clean and robust, but for very consistent developments I could make experimens (ie. https://github.com/math-comp/math-comp/tree/experiment/proof_using_annotations)

**Comment by gares** [comment]
I think this PR is fine, it may only break 3rd party scripts to annotate files (since the change in the aux file format, and the new format is better, thanks @SkySkimmer).  I don't mind mine being broken, since it sucked anyway.  I kind of recall @JasonGross begin playing with this piece of info.  I'm citing him in this PR so that he eventually update his scripts, if any.

Thanks for the good work Gaetan!

**Comment by ejgallego** [comment]
@gares what about my comment wrt to stale aux info and its use in the STM ?

**Comment by SkySkimmer** [comment]
>in -quick mode such memory is pre-seeded with the aux file, if available and still up to date (it contains a hash of the source file).

If some tactic `Require`d from another file changes the information could be outdated even though the file hasn't changed. Is the check robust for that?
eg A.v:
``` coq
Ltac magic := exact I. (* or *) Ltac magic := assumption.
```
B.v:
``` coq
Require Import A.
Section Sec.
Variable x : True.
Lemma foo : True. Proof. magic. Qed.
End Sec.
```

**Comment by JasonGross** [comment]
@gares I use the command line output from `Set Suggest Proof Using `.  Using the `.aux` file seems like a useful alternative to support, though, if it also provides character locations / line numbers.

**Comment by maximedenes** [comment]
> This seems very very suspicious, doesn't it? Imagine I process my Theorem foo which is using hyp A. Now, I change the proof so it will use hyps A B, however, the STM is getting the stale information from the .aux file and using that?

> @gares what about my comment wrt to stale aux info and its use in the STM ?

> If some tactic Required from another file changes the information could be outdated even though the file hasn't changed. Is the check robust for that?

@gares ?

**Comment by SkySkimmer** [comment]
@maximedenes Note that this PR should have no impact on whether that's an issue. Maybe a bug should be opened, eg "STM may rely on stale info from aux files".

**Comment by gares** [comment]
> Maybe a bug should be opened, eg "STM may rely on stale info from aux files".

.a.aux file holds info about file a.v and contains the md5sum of a.v.
if a.v uses b.v, then the info is potentially outdated if one changes b.v.

there are 2 types of infos, time and section context.  Only the latter can generate bogus results (never logically incorrect, but quite unexpected). The fact that the check for "has a dependency changed?" is not precise is kind of a feature, since if you make it precise the "cache" would always be invalid. (If you recompile it means you changed something, right?)

In the long term I would like to see aux file only contain "time infos" and have "proof using" annotations be always there (or superseded by a better idea).

**Comment by maximedenes** [comment]
@SkySkimmer sorry, there seems to be a few small conflicts now. If you can rebase, I'll merge this PR immediately. Thanks!

**Comment by SkySkimmer** [comment]
Please wait for travis just in case.

**Comment by SkySkimmer** [comment]
Indeed I made an error while rebasing.

**Comment by maximedenes** [comment]
@SkySkimmer the error is now fixed, right? The only failure on Travis is a GeoCoq timeout. @ejgallego is this timeout going to be addressed?

**Comment by ejgallego** [comment]
@maximedenes the error is fixed; GeoCoq is pending from https://github.com/GeoCoq/GeoCoq/issues/8 I suggest we add a small patch to the CI meanwhile.

**Comment by Zimmi48** [comment]
> GeoCoq is pending from GeoCoq/GeoCoq#8 I suggest we add a small patch to the CI meanwhile.

Not a good idea. I suggest we submit a PR on GeoCoq itself instead. I would have done it but I'm too busy with the Bugzilla migration script right now.

**Pull request merged**
