### PR TITLE
Try testing performance without universes

### PR DESCRIPTION
**Pull request by SkySkimmer**
This is a hack to see how much faster we could be if we didn't worry about universes

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by JasonGross** [comment]
> 28.7230   15.6820  -13.0410  -45.40%    78  coq-rewriter/src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.v.html

This is bizarre, that file shouldn't be doing anything with universes

**Comment by JasonGross** [comment]
Is there any way to track down where the universe overhead is coming from in master on that line?

**Comment by SkySkimmer** [comment]
Run perf on coqc on that file I guess

**Comment by SkySkimmer** [comment]
I can't make equations work with this hack, otherwise I'd test metacoq.

**Comment by Janno** [comment]
> Is there any way to track down where the universe overhead is coming from in master on that line?

> Run perf on coqc on that file I guess

I find it easiest to advance to just before the line in question in coqtop, then run `perf record --call-graph dwarf,65500 -F 999 -p $(pgrep -f 'coqtop.*my_file.v')`, step over the line in coqtop and wait until coqtop is done processing, switch back to `perf` and hit ctrl+c. Adjust the value of `-F` according to the expected runtime. `999` samples per second are fine for a few seconds but you'll get gigabytes of data if you enter the realm of minutes.

I usually export the resulting profile with `perf script --max-stack=24000 -i perf.data > my.script` and view it in firefox profiler (https://profiler.firefox.com/).

P.S.: If you are not running a bleeding edge linux kernel (or, more specifically, very recent a linux-perf version), then you should probably add `--no-inline` to `perf script` because there is a bug that makes it take ages otherwise. I don't know how that option changes the output so I guess I should add an unqualified "use with caution". It hasn't ever changed the output for me but I also don't understand what it is supposed to do.

**Comment by JasonGross** [comment]
Thanks @Janno , I'll try that.

Btw, the line number in the bench report is wrong (cc @Alizter ?).  Line 78 is https://github.com/mit-plv/rewriter/blob/1d2dc36216ad110dcf49cf7ed2a05d2bbdd7546c/src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.v#L78
```coq
Notation extra_idents := (Z.eqb, orb, Z.gtb, PositiveSet.elements, @fst, @snd, PositiveSet.mem, Pos.succ, PositiveSet.add, List.fold_right, List.map, List.seq, Pos.mul, S, Pos.of_nat, Z.to_nat, Z.div, Z.pos, O, PositiveSet.empty) (only parsing).
```
and there's no way this is taking 15--30 seconds.  The correct line number is 80:
```coq
Time Make myrew := Rewriter For lemmas (with extra idents extra_idents) (with delta).
```
(And this file hasn't changed for over a year, so it's not that the numbers are off because the file changed underneath the bench runner.). Maybe the `Time` is messing things up???

**Comment by Alizter** [comment]
@JasonGross The bench script just reads the line number as reported in the HTML timing file. Here is the relevant one: 
https://coq.gitlab.io/-/coq/-/jobs/3145546937/artifacts/_bench/html/coq-rewriter/src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.v.html

Looks like there might be two bugs. First he reported line number is offset (by 2) and second the highlighting is offset (by 1). I believe there is a timing python script that generates these HTML files right?

**Comment by SkySkimmer** [comment]
@JasonGross did you manage to perf?

**Comment by JasonGross** [comment]
Not yet, unfortunately

**Comment by Janno** [comment]
Here is a profile on 8.15.1 (no native compute, no idea if that matters) for rewriter#1d2dc36216ad110dcf49cf7ed2a05d2bbdd7546c: https://share.firefox.dev/3yxLJS7

Searching for `UState` (upper right corner has a search field) shows 17s (out of ~40s) worth of stack samples that include that module. Some of them seem to come from `abstract`. In fact, cleaning up (merging into the caller) some of the proof monad functions shows that `abstract` seems to be responsible for around half of the runtime and a lot of those calls spend substantial time in `Evd.minimize_universes`: https://share.firefox.dev/3yyyvEQ

**Comment by SkySkimmer** [comment]
Probably got everything we can out of this branch. I expected unimath to show improvements but on second thought I think they use `Definition U := Type` and then U everywhere so no change is normal.

**Pull request closed without merging**
