### PR TITLE
merge-pr: add reviewer info to commit message

### PR DESCRIPTION
**Pull request by SkySkimmer**
This produces a commit message like 
~~~
Merge PR #9223: Fix universe restriction in delayed mode.

Reviewed-by: gares
Reviewed-by: ppedrot
~~~
The list is what appears in the "reviewers" github tab (on the top right of the PR view), including comment and change request reviews and without review requests.

We could filter out change requests or filter to only approving reviews. If we filter we essentially have a stronger implication that people appearing in the commit message approved the PR at the cost of missing some reviewers who just didn't approve in the github UI.

### CODE REVIEW

**Comment by gares** [comment]
The feature is very welcome.

The implementation is frankly a bit complex, in particular running multiple jobs in the background and waiting for them as late as possible is not going to make it easy to change the script (you have to understand all that).

Is it really worth it? Even if the scripts takes 10 seconds to merge a PR I think I could live with that.

**Comment by gares** [comment]
> this might be time to move the merging process from the script to using the bot

Do you mean that the bot would react to a specific message, eg "MERGE THIS"?
Or that I'll have to run a .ml script (sharing code with the bot) on my machine?

**Comment by gares** [comment]
To be clear, I think I can live with both commit being merged. But I'd prefer only the obvious one to be, and the other to be dropped (possibly in favor of the solution @Zimmi48 proposes).

**Comment by Zimmi48** [comment]
>Do you mean that the bot would react to a specific message, eg "MERGE THIS"?

Yes. With an optional (explicit) "Ignore CI failures." to ensure that CI failures are not ignored accidentally.

**Review by ejgallego — COMMENTED** [review]
I think approved reviews should add a `Signed-off-by:` right? That's the standard in the git community.

**Comment by gares** [comment]
> Yes. With an optional (explicit) "Ignore CI failures." to ensure that CI failures are not ignored accidentally.

For various reasons the merge script of today asks me many questions.. and I've just to answer y/n.
Here you propose to write sentences instead of a character.

Would it be possible to have some "click friendly" way of driving the bot? (eg imagine I misspell one of the options, I do a lot of mistakes when I type)

**Comment by Zimmi48** [comment]
I tried to explain this better in https://github.com/coq/bot/issues/27.

**Comment by SkySkimmer** [comment]
I think the specific tag to use is fairly project specific. For instance linux (whose process is email based so not necessarily compatible with our github based one) has descriptions of what the different tags mean in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD
~~~


The Signed-off-by: tag indicates that the signer was involved in the
development of the patch, or that he/she was in the patch's delivery path.

If a person was not directly involved in the preparation or handling of a
patch but wishes to signify and record their approval of it then they can
ask to have an Acked-by: line added to the patch's changelog.

Acked-by: is often used by the maintainer of the affected code when that
maintainer neither contributed to nor forwarded the patch.

Acked-by: is not as formal as Signed-off-by:.  It is a record that the acker
has at least reviewed the patch and has indicated acceptance.  Hence patch
mergers will sometimes manually convert an acker's "yep, looks good to me"
into an Acked-by: (but note that it is usually better to ask for an
explicit ack).

Acked-by: does not necessarily indicate acknowledgement of the entire patch.
For example, if a patch affects multiple subsystems and has an Acked-by: from
one subsystem maintainer then this usually indicates acknowledgement of just
the part which affects that maintainer's code.  Judgement should be used here.
When in doubt people should refer to the original discussion in the mailing
list archives.
[...]


Reviewed-by:, instead, indicates that the patch has been reviewed and found
acceptable according to the Reviewer's Statement:

Reviewer's statement of oversight
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

By offering my Reviewed-by: tag, I state that:

	 (a) I have carried out a technical review of this patch to
	     evaluate its appropriateness and readiness for inclusion into
	     the mainline kernel.

	 (b) Any problems, concerns, or questions relating to the patch
	     have been communicated back to the submitter.  I am satisfied
	     with the submitter's response to my comments.

	 (c) While there may be things that could be improved with this
	     submission, I believe that it is, at this time, (1) a
	     worthwhile modification to the kernel, and (2) free of known
	     issues which would argue against its inclusion.

	 (d) While I have reviewed the patch and believe it to be sound, I
	     do not (unless explicitly stated elsewhere) make any
	     warranties or guarantees that it will achieve its stated
	     purpose or function properly in any given situation.

A Reviewed-by tag is a statement of opinion that the patch is an
appropriate modification of the kernel without any remaining serious
technical issues.  Any interested reviewer (who has done the work) can
offer a Reviewed-by tag for a patch.  This tag serves to give credit to
reviewers and to inform maintainers of the degree of review which has been
done on the patch.  Reviewed-by: tags, when supplied by reviewers known to
understand the subject area and to perform thorough reviews, will normally
increase the likelihood of your patch getting into the kernel.
~~~

Personally I think saying "reviewed-by means this person made a review on github" is as accurate as we can get.

**Comment by ejgallego** [comment]
Sounds good then. Maybe when the person is a codeowner we should use acked-by, but that's indeed subtle.

**Comment by Zimmi48** [comment]
Reading this, it seems to me that in Linux terms, `Signed-off-by` is stronger than `Reviewed-by` which in turn is stronger than `Ack-by`. Thus I suggest we:
- use `Signed-off-by` only for the PR assignee who does the final approval of the finished PR and merges (seems all the more important in a context where @coqbot would commit the merge);
- use `Reviewed-by` to indicate approved reviews;
- use `Ack-by` to indicate comment reviews.

Whatever scheme we choose to adopt, we should document it, for instance in `CREDITS`.
We could in passing stop adding dates to `CREDITS` and say instead: for contributions starting from 2019, refer to the commit information that should be stored in the commits themselves as commit author, and `Co-authored-by`, `Signed-off-by`, `Reviewed-by` and `Ack-by` tags with the following conventional meaning... We could continue to use the rest of the `CREDITS` file to store ORCID for contributors only (since it can then be displayed on Zenodo).

**Comment by SkySkimmer** [comment]
Updated with Reviewed-by for approve and Ack-by for comment reviews.
There's no coqbot merging so I'm not bothering with signed-off-by.

**Comment by Zimmi48** [comment]
@maximedenes You are the code owner. I think this PR is basically ready and comments have been taken into account. I did not test the PR but I approve the principle.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
