### PR TITLE
Ltac2: improve "tactic definition must be a syntactical value" error

### LINKED ISSUE #17577: Puzzling error message for "Ltac2 x := apply I."
This message isn't very understandable for what's probably a common mistake.  Can we get a better message for this case, particularly since it's valid syntax for Ltac (and hence more likely for users to make a mistake)?  (Screenshot with 8.16 to show the tooltip location.)

image

### PR DESCRIPTION
**Pull request by SkySkimmer**
The error is located on the expression not the ident.

Add suggestion to thunk.

Close #17577

### CODE REVIEW

**Comment by ppedrot** [comment]
I'm not sure that underlining the whole definition is an improvement. It contains just as much information but fills the screen with noise.

**Comment by SkySkimmer** [comment]
The error is not about the ident so there's no point highlighting the ident

**Review by ppedrot — APPROVED** [review]
All right.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
