### PR TITLE
Remove API for 8.7.

### PR DESCRIPTION
**Pull request by maximedenes**
This is a 8.7-only PR, removing the API like we said during the Coq Implementors Workshop, until we figure out the remaining issues.

### CODE REVIEW

**Comment by Zimmi48** [comment]
According to Travis, this breaks stuff that does `open API`. But I thought that after @ejgallego changes, `open API` was not required anymore, which made the API backward-compatible. So why does it appear in bignums, color, and math-classes?

**Comment by ejgallego** [comment]
Likely these plugins were broken by the first API and had to be updated. Indeed, they should also remove the `open API` flag and let `coq_makefile` do the job for them.

**Comment by Zimmi48** [comment]
So this `open API` line is completely spurious and can just be removed?

**Comment by ejgallego** [comment]
> So this open API line is completely spurious and can just be removed?

Yup, `-open API` should be done by the makefile so it is not necessary to modify plugin source code to enable/disable the "API".

We must however test the patch in both 8.7 / 8.8, it is possible that some makefile imperfections are there.

**Comment by Zimmi48** [comment]
In the case of bignums, it doesn't use coq_makefile (why?), so it doesn't benefit from the automatic `open API`. @letouzey could you have a look? We're hoping for a fix that would be compatible both with master and with 8.7 (after this PR removing the API).

**Comment by Zimmi48** [comment]
In fact, what I hadn't realized in that all the tests that are failing depend on bignums so hopefully just fixing this will be enough.

**Comment by Zimmi48** [comment]
OK no surprise that I can't fix bignums: coq_makefile is broken since #788 (cf. my comment [here](https://github.com/coq/coq/commit/41489a97014ab60b3dcc0f32dfdd10aacc6bcb98#commitcomment-23555203)).

**Pull request merged**
