### PR TITLE
Move tactic code out of Extratactics into Internals.

### PR DESCRIPTION
**Pull request by ppedrot**
It is very bad practice to keep non-trivial code in mlg files, whose sole purpose is to declare grammar rules with syntactic sugar. We can probably even clean that up further but it is a good first step.

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Review by Matafou — APPROVED** [review]

**Comment by Matafou** [comment]
The whole code of funind should some day be replaced by a thin syntactic layer above Equations I suppose.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
waiting for rebase

**Comment by ppedrot** [comment]
@SkySkimmer done

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
