### PR TITLE
Prepare for 8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlays:
- https://github.com/JasonGross/coq-scripts/pull/8
- https://github.com/mit-plv/fiat/pull/61

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
@JasonGross As usual, fiat-parsers does not seem to accept the new version number :unamused:

**Comment by SkySkimmer** [comment]
I put the wrong PR number in the overlay file, should work now

**Comment by JasonGross** [comment]
Overlays have been merged, thanks for preparing them!

**Comment by Zimmi48** [comment]
@SkySkimmer Do I have a :+1: for merging now?

**Comment by SkySkimmer** [comment]
OK to merge

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
