### PR TITLE
Fix coqdoc bug #5648 on user idents colliding with keywords wrongly tagged as keywords

### PR DESCRIPTION
**Pull request by herbelin**
As noticed by V. Laporte at [#5648](https://coq.inria.fr/bugs/show_bug.cgi?id=5648), testing if an ident was used as a keyword was done without first looking at whether the ident was a user ident registered in the glob file. This fixes the problem.

Additionally, this introduces a coqdoc target in the test-suite.

### CODE REVIEW

**Comment by vbgl** [comment]
Thank you. This is indeed the fix that I had in mind.

However, it seems hazardous to bake wrong behaviours into non-regression tests: the parts `<span class="id" title="keyword">Next</span>` and `\coqdockw{Next}` are wrong.

Do I understand correctly that github is currently the preferred place for bug reports?

**Comment by Zimmi48** [comment]
> Do I understand correctly that github is currently the preferred place for bug reports?

No issues are not active on GitHub. We are still using Bugzilla. However, feel free to open a PR here if you want to propose a fix.

**Comment by herbelin** [comment]
> However, it seems hazardous to bake wrong behaviours into non-regression tests: the parts <span class="id" title="keyword">Next</span> and \coqdockw{Next} are wrong.

I agree. It is however difficult to do better without a bit more work, such as outputting in the glob file the location of tactic identifiers, or the location of keywords, since these are after all extensible (the table hard-wired in the code of `coqdoc` is approximative and even contains two-words keywords which cannot be reached and are there only for information).

There is a project of having more information provided by `coqtop`. @yurug, who has an ongoing implementation in this direction, might have more to tell.

**Comment by vbgl** [comment]
I agree. I’m not suggesting to fix this issue now, only to leave it out of the test case.

**Pull request merged**
