### PR TITLE
Dockerfile flambda switch: add "uri" for coq-lsp

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ejgallego** [comment]
Thanks @SkySkimmer , I need to update the procedure upstream so this doesn't happen again.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Review by ejgallego — APPROVED** [review]
@coqbot: merge now

**Pull request merged**
