### PR TITLE
Put Tac2intern.environment in its own module

### PR DESCRIPTION
**Pull request by SkySkimmer**
This will allow splitting tac2intern more, for instance have pattern
analysis in its own file.

### CODE REVIEW

**Comment by ppedrot** [comment]
This is exposing much more internal API though, I'm not sure I am a huge fan of this.

**Comment by SkySkimmer** [comment]
tac2intern doesn't expose environment using APIs so it's not possible to interfere with it through the newly exposed APIs though

**Comment by SkySkimmer** [comment]
@ppedrot ping

**Comment by ppedrot** [comment]
Meh. Please rebase, I'll merge this when we get a clean CI.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
