### PR TITLE
[toplevel] Modify printing goal strategy.

### PR DESCRIPTION
**Pull request by ejgallego**
Instead of using a command-analysis heuristic, coqtop will now print
goals if the goal has changed. We use a fast goal comparison
heuristic, but a more refined strategy would be possible.

This brings some [IMHO very welcome] change to PG and `-emacs`, which
will now disable the printing of goals. Now, instead of playing with
`Set/Unset Silent` and a bunch of other hacks, PG can issue a `Show`
command whenever it wishes to redisplay the goals.

This change will break PG, so we need to carefully coordinate this PR
with PG upstream (see ProofGeneral/PG#212).

Some interesting further things to do:

- Detect changes in nested proofs.
- Uncouple the silent flag from "print goals".

### CODE REVIEW

**Comment by ejgallego** [comment]
This is a RFC for now, but I'll like to get this in 8.8 if possible.

**Comment by gares** [comment]
I don't get the change "error -> warning" for example in the check task code, these are really errors to be printed as such.

I don't get the what is the point of having an heuristic to print the goals if PG is expected to ask for the print.
Can you elaborate on that?

**Comment by ejgallego** [comment]
> I don't get the change "error -> warning" for example in the check task code, these are really errors to be printed as such.

Can you comment on #6262 ? I am sorry I didn't properly tag this PR as depending. There is actually a very good reason for that.

> I don't get the what is the point of having an heuristic to print the goals if PG is expected to ask for the print.
> Can you elaborate on that?

This is only used in `coqtop` without emacs, that is, when a human is using it.

**Comment by psteckler** [comment]
So, in `-emacs` mode, the goal should not print at all, unless it's requested via `Show`?

**Comment by ejgallego** [comment]
> So, in -emacs mode, the goal should not print at all, unless it's requested via Show?

Correct. Backwards compatible way: do `Set Silent`, then `Show`.

**Review by herbelin — COMMENTED** [review]
Looks like a very good idea. Could we commit it so that we can get real-life feedback about it?

**Comment by JasonGross** [comment]
> Could we commit it so that we can get real-life feedback about it?

Please don't commit this until the fix for PG is merged (and after that, do feel free to commit this).  I use PG on master, so having this committed without the PG fix would break my workflow.

**Review by gares — APPROVED** [review]

**Comment by ejgallego** [comment]
Ok so this is ready again. The main blocker for the merge is to know what the PG devs think. This basically switches Proof General from randomly reciving goals and having to recognize them to actually never receiving goals, so PG should request goal display when it wants.

**Comment by ejgallego** [comment]
Note that by default `-emacs` still print goals [but only when the goal has changed]. It is `Set Silent` that behaves more strictly.

**Comment by ejgallego** [comment]
So #6801 will depend on this, I'd be good if emacs users could test this. Contrary to my expectations I did some testing and it seems to work fine [which is not suprising as this strategy is way less hacky].

So even if emacs could benefit from a different goal printing strategy, I think that this PR may be compatible with current PG.

**Comment by ejgallego** [comment]
@JasonGross , maybe you could test this PR and see if it works fine with PG?

It does on my computer, but admittedly I don't do anything fancy. After thinking a bit, this change should be compatible with the current PG implementation, but cannot be really sure given how many crazy things PG does in order to overcome interaction limitations.

**Comment by ejgallego** [comment]
Sucesssful build here: https://gitlab.com/ejgallego/coq/pipelines/18428771

**Pull request merged**
