### PR TITLE
[engine] Allow debug printers to access the environment.

### PR DESCRIPTION
**Pull request by ejgallego**
This should improve correctness and will be needed for the PRs that
remove global access to the proof state.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ping @ppedrot

**Review by ppedrot — APPROVED** [review]
Should be OK, I guess.

**Comment by ppedrot** [comment]
Even though you're not the one responsible, note that I really dislike the trace mechanism. It's a poor man debugger for Ltac, and it adds quite a cost to the monad layer, even when we don't use it. I think I remember it is a source of over allocation / memory leak. I hope your patch doesn't make things worse.

**Comment by ejgallego** [comment]
Let's do a bench if you want; I think that should not matter much; indeed this trace stuff is not something that I do dig a lot.

**Comment by ejgallego** [comment]
As anyways I had to test my recent changes to the CI system, I've rebased and launched a bench.

https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/603/

**Comment by ejgallego** [comment]
Well within the noise range, specially if as it seems, NEW usually has additional overhead.
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │         mem faults         │
│                        │                         │                                             │                                             │                                │                            │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │     NEW     OLD    PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│          coq-fiat-core │  137.84  138.51 -0.48 % │      384002286805      385131986211 -0.29 % │      520134021674      520241650517 -0.02 % │     508356     507916  +0.09 % │     290     191   +51.83 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│ coq-mathcomp-ssreflect │   67.00   67.18 -0.27 % │      184504566272      185019539459 -0.28 % │      268730026381      268790175494 -0.02 % │     538324     538472  -0.03 % │      17       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│       coq-math-classes │  255.10  255.73 -0.25 % │      702968422170      702888644621 +0.01 % │      927075088505      927255788529 -0.02 % │     533024     533152  -0.02 % │     294      83  +254.22 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│              coq-color │  746.99  748.26 -0.17 % │     2072402297190     2074030072484 -0.08 % │     2512822302925     2512292300143 +0.02 % │    1437332    1437452  -0.01 % │     384     149  +157.72 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│   coq-mathcomp-algebra │  184.73  184.93 -0.11 % │      511723429585      511731957413 -0.00 % │      694627547571      694770909509 -0.02 % │     645828     646508  -0.11 % │     109      74   +47.30 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│  coq-mathcomp-solvable │  221.55  221.75 -0.09 % │      615556538860      615492187743 +0.01 % │      865347564006      865110414136 +0.03 % │     851652     852256  -0.07 % │     161       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│              coq-flocq │  595.45  595.86 -0.07 % │     1656196530995     1658267035100 -0.12 % │     2425648559532     2426140696352 -0.02 % │    1775464    1589968 +11.67 % │     521     261   +99.62 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│     coq-mathcomp-field │  250.72  250.87 -0.06 % │      695686921701      696630575671 -0.14 % │     1042611234369     1043006259781 -0.04 % │     762524     761844  +0.09 % │      13       6  +116.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│        coq-fiat-crypto │ 6675.01 6671.80 +0.05 % │    18568764783884    18560045845353 +0.05 % │    30232903681371    30234534642464 -0.01 % │    2484052    2507768  -0.95 % │    1867    1241   +50.44 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│             coq-geocoq │ 2055.11 2053.50 +0.08 % │     5710222314915     5703871422128 +0.11 % │     8279491680485     8279276497934 +0.00 % │    1228492    1225788  +0.22 % │     627     203  +208.87 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│  coq-mathcomp-fingroup │   84.54   84.47 +0.08 % │      233492304406      233651534984 -0.07 % │      348666982175      348769032123 -0.03 % │     591624     591920  -0.05 % │       6     249   -97.59 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│       coq-fiat-parsers │  728.33  727.39 +0.13 % │     2019099603460     2018658865548 +0.02 % │     3073983601992     3074448093892 -0.02 % │    2928392    2946808  -0.62 % │     506     754   -32.89 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│ coq-mathcomp-character │  281.41  280.90 +0.18 % │      781254290560      780614615697 +0.08 % │     1114779606556     1114791784086 -0.00 % │    1069148    1068304  +0.08 % │       1      31   -96.77 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│               coq-hott │  332.89  332.22 +0.20 % │      921475124349      921094312478 +0.04 % │     1400692313098     1400654667381 +0.00 % │     475204     475220  -0.00 % │     464       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│ coq-mathcomp-odd-order │ 1410.62 1407.06 +0.25 % │     3927196114949     3919920207159 +0.19 % │     6509385882149     6513284027545 -0.06 % │    1370084    1370304  -0.02 % │      20     237   -91.56 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│                coq-vst │ 3178.81 3170.51 +0.26 % │     8843805037151     8822047257993 +0.25 % │    12269821539947    12280858813953 -0.09 % │    2232568    2235696  -0.14 % │     506    1274   -60.28 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│    coq-formal-topology │   58.85   58.68 +0.29 % │      160712925072      160979713769 -0.17 % │      249447362830      249612500641 -0.07 % │     485616     485620  -0.00 % │       0       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│            coq-bignums │  100.42   99.98 +0.44 % │      277787830522      276738968978 +0.38 % │      404621836522      404589021520 +0.01 % │     544628     544676  -0.01 % │     301      23 +1208.70 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│               coq-corn │ 1565.59 1553.19 +0.80 % │     4346599750965     4310572751197 +0.84 % │     6330999584755     6330920654225 +0.00 % │     876400     875976  +0.05 % │      45      45    +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│           coq-compcert │  909.04  900.28 +0.97 % │     2521484132240     2496887132564 +0.99 % │     3616291204931     3617099708039 -0.02 % │    1309324    1309224  +0.01 % │     253     510   -50.39 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴────────────────────────────┘
```

**Comment by ejgallego** [comment]
Ping @ppedrot

**Comment by ppedrot** [comment]
Let's merge, that looks like noise (hopefully).

**Pull request merged**
