### PR TITLE
Functional choice <-> [inhabited] and [forall] commute

### PR DESCRIPTION
**Pull request by SkySkimmer**
PR prompted by @jwiegley's question at https://sympa.inria.fr/sympa/arc/coq-club/2017-04/msg00123.html

### CODE REVIEW

**Comment by jwiegley** [comment]
The last bit I needed to actually use it was:

``` coq
Require Import Coq.Logic.ClassicalChoice.
Require Import Coq.Logic.ChoiceFacts.

Lemma inhabited_forall_choice : inhabited_forall.
Proof.
  apply choice_to_inhab.
  apply non_dep_dep_functional_choice.
  repeat intro.
  apply choice, H.
Qed.
```

**Comment by herbelin** [comment]
This is clear and neat, with the different components of the result dispatched in appropriate files. I like it.

There is a table of contents in `ChoiceFacts.v` where the result should be announced, by consistency with the rest of the files. Unfortunately, not to break the existing order, we are somehow constrained to put the result at the end of the list, item 10.

Or an alternative could also be to split item 5 into two subitems and let it be a more general item about "Alternative equivalent formulations of AC_fun" with 5.1 "Equivalence of functional choices on dependent or non dependent functional types" and 5.2 "Equivalence of functional choice with commutation of inhabitation and quantification". Yes, maybe better like this?

There is also a table of contents of statements, but I just realize that functional choice on dependent types is not listed, so the consistency is already broken. So, by consistency of presentation of the file, one should also add the latter in the list. So, let's call it AC_fun_dep.

Then a name would be needed for commutation of inhabitation and quantification. Are there already standard names for it used in the HoTT community?

**Comment by JasonGross** [comment]
> Then a name would be needed for commutation of inhabitation and quantification. Are there already standard names for it used in the HoTT community?

@mikeshulman or @andrejbauer would probably be the ones to ask about names for commuting truncation with Pi

**Comment by SkySkimmer** [comment]
I found the preamble comment difficult to read. Why not replace the current
``` coq
(**

We investigate the relations between the following choice and
description principles

- AC_rel  = relational form of the (non extensional) axiom of choice
            (a "set-theoretic" axiom of choice)
- AC_fun  = functional form of the (non extensional) axiom of choice
            (a "type-theoretic" axiom of choice)
- ... *)

Section ChoiceSchemes.

Variables A B : Type.

(** AC_rel *)

Definition RelationalChoice_on :=
  forall R:A->B->Prop,
    (forall x : A, exists y : B, R x y) ->
    (exists R' : A->B->Prop, subrelation R' R /\ forall x, exists! y, R' x y).

(** AC_fun *)

(* Note: This is called Type-Theoretic Description Axiom (TTDA) in
   [[Werner97]] (using a non-standard meaning of "description"). This
   is called intensional axiom of choice (AC_int) in [[Carlström04]] *)

Definition FunctionalChoice_on :=
  forall R:A->B->Prop,
    (forall x : A, exists y : B, R x y) ->
    (exists f : A->B, forall x : A, R x (f x)).

(** ... *)

End ChoiceSchemes.
```
with
``` coq
(**

We investigate the relations between the following choice and
description principles
 *)

Section ChoiceSchemes.

Variables A B : Type.

(** AC_rel = relational form of the (non extensional) axiom of choice
             (a "set-theoretic" axiom of choice) *)

Definition RelationalChoice_on :=
  forall R:A->B->Prop,
    (forall x : A, exists y : B, R x y) ->
    (exists R' : A->B->Prop, subrelation R' R /\ forall x, exists! y, R' x y).

(** AC_fun = functional form of the (non extensional) axiom of choice
             (a "type-theoretic" axiom of choice) *)

(* Note: This is called Type-Theoretic Description Axiom (TTDA) in
   [[Werner97]] (using a non-standard meaning of "description"). This
   is called intensional axiom of choice (AC_int) in [[Carlström04]] *)

Definition FunctionalChoice_on :=
  forall R:A->B->Prop,
    (forall x : A, exists y : B, R x y) ->
    (exists f : A->B, forall x : A, R x (f x)).

(** ... *)

End ChoiceSchemes.
```
?

**Comment by herbelin** [comment]
Maybe... I also find it difficult to read, as well as keeping it synchronized. Having coqdoc being able to generate a table of content would be much more comfortable. I'm ok with your proposal for a change.

**Comment by mikeshulman** [comment]
> names for commuting truncation with Pi

I would call it "the axiom of choice".  (-:

**Comment by SkySkimmer** [comment]
>Maybe... I also find it difficult to read, as well as keeping it synchronized. Having coqdoc being able to generate a table of content would be much more comfortable. I'm ok with your proposal for a change.

I don't know what to do with the table of contents in the meantime though. Maybe just move it after the definitions?

**Comment by herbelin** [comment]
@SkySkimmer: You mean because of the explicit names in the table of contents? Maybe to keep the toc at the beginning but replacing the formal names with natural language text? Or to put it after the definitions, why not.

@mikeshulman: indeed, that would highlight a "purified" view at the axiom of intensional choice in prop, though in this context, it is to compare different formulations, so it would be convenient to have specific names (hi, in passing!). By the way, what becomes the axiom of extensional choice (choice on setoids) when considered under the lense of commutation of forall and inhabitation/truncation? Doesn't it actually derive from intensional choice in HoTT (since proof-irrelevance and propositional extensionality hold)? Does this mean that e.g. Banach-Tarski holds in HoTT + commutation of forall and prop-truncation? And conversely then, that the axiom of intensional choice in prop is significantly more difficult to realize in HoTT than in CIC. Very interesting.

**Comment by mikeshulman** [comment]
What exactly do you mean by "intensional choice" and "extensional choice"?

**Comment by herbelin** [comment]
@mikeshulman: I'm referring to Martin-Löf and Carlström's terminology (see Carlström's "EM + Ext− + ACint is equivalent to ACext").

In CIC syntax, the intensional choice is AC_fun, which this PR proves equivalent to commutation of inhabitation and quantification, while the extensional choice is
```coq
∀ A B, ∀ R : A -> A -> Prop, ∀ T : A -> B -> Prop, Equivalence R ->
  (∀ x x' y, R x x' -> T x y -> T x' y) ->
  (∀ x, ∃ y, T x y) ->
  ∃ f : A -> B, ∀ x : A, T x (f x) /\ (∀ x' : A, R x x' -> f x = f x').
```
which is related to ZF's axiom of choice.

**Comment by mikeshulman** [comment]
It looks to me like extensional choice is just ordinary ("intensional"?) choice on the quotient A/R, so yes, it should follow from the latter.  And yes, "intensional" choice, or equivalently forall-trunc commutation, behaves like the usual axiom of choice in ZF, allowing you to prove all of its usual consequencecs like banach-tarski.

**Comment by SkySkimmer** [comment]
@herbelin that statement is equivalent to FunctionalChoice + 
``` coq
forall A (R : A -> A -> Prop),
    Equivalence R ->
    exists f : A -> A, (forall x, R x (f x)) /\ (forall x y, R x y -> f x = f y)
```
https://gist.github.com/SkySkimmer/8a07175b84e1664eebac9d420b352520

**Comment by herbelin** [comment]
Let me phrase it like this if you're ok: From a computational and intuitionistic point of view, forall-trunc commutation is very different from the "extensional" choice in that the former is directly interpretable as projections from an (untruncated) sigma but not the latter. From an extensional classical point of view, forall-trunc commutation is de facto an "extensional" choice, but the underlying computation would obviously not be purely functional. (And, on an informal note, this is what fascinates me in HoTT, how well the new bricks brought by HITs and by the extensionality of universes as well as the concept of h-level allow to nicely organize concepts about which the computational approach was somehow only able to locally observe or approximate the properties - Prop, Set, setoid rewrite, OTT, proof-irrelevance, ...).

**Comment by herbelin** [comment]
@SkySkimmer: Yes, exactly, and I think that you could do it with only unique choice as well.

**Comment by mikeshulman** [comment]
What do you mean by "interpretable as projections from an (untruncated) sigma?

**Comment by herbelin** [comment]
The standard AC := λH.<λx.𝝅₁(H x),λx.𝝅₂(H x)> : ∀x∑y.P(x,y) → ∑f.∀x.P(x,f(x))

**Comment by mikeshulman** [comment]
Oh, the "axiom" of choice that's not an axiom. (-:  I don't really see what you mean by forall-trunc commutation being "interpretable" as this, though, since the non-axiom of choice doesn't have a trunc in it.  I would say that the commutation of forall and trunc is exactly the content of the set-theoretic axiom of choice, and the absence of a truncation in the non-axiom of choice is what makes it a theorem rather than having any of the real content of the axiom of choice.

**Comment by SkySkimmer** [comment]
I'm not sure what this is about:
``` coq
(** We make them all polymorphic. Most of them have existentials as conclusion
    so they require polymorphism otherwise their first application (e.g. to an
    existential in [Set]) will fix the level of [A].
*)
(* Set Universe Polymorphism. *)
```
@mattam82 ?

**Comment by SkySkimmer** [comment]
>@SkySkimmer: Yes, exactly, and I think that you could do it with only unique choice as well.

Indeed this is already done at around https://github.com/coq/coq/blob/trunk/theories/Logic/ChoiceFacts.v#L1121 (AC_fun_setoid = extensional choice)

**Comment by SkySkimmer** [comment]
Why are these 2 https://github.com/coq/coq/blob/trunk/theories/Logic/ChoiceFacts.v#L303-L306 definitions in the middle of notations?

**Comment by SkySkimmer** [comment]
Something is going on with coqdoc https://travis-ci.org/SkySkimmer/coq/builds/227944048

**Comment by herbelin** [comment]
> I don't really see what you mean by forall-trunc commutation being "interpretable" as this, though, since the non-axiom of choice doesn't have a trunc in it.

I should clarify that I'm reasoning here with the commutation of forall and inhabitation version that @SkySkimmer proved, i.e. a restricted form of truncation formulated in Prop and without proof-irrelevance, which might be confusing since you probably had in mind truncation with proof-irrelevance. So, let's call it inhabitation rather than truncation.

Then, it is clear that in this "Coq" setting, everything that holds of inhabited A trivially holds of A, so that this choice formulated in Prop can be computationally interpreted the same as the "non-axiom" of choice by just dropping the inhabitation constraint. I did not mean more than that.

> I would say that the commutation of forall and trunc is exactly the content of the set-theoretic axiom of choice

You are assuming either HITs or univalence, I guess. Otherwise, on top of Coq + commutation of forall and inhabitation, we need more bricks to get extensional choice. In particular, Carlström's result is that extensional choice is intensional choice + excluded-middle + a weak form of functional extensionality, and, in the Coq standard library, I have an alternative decomposition as intensional choice + a weak form of predicate extensionality + proof-irrelevance.

So, assuming a proof-irrelevant setting, it still remains some form of extensionality to get in order to get the full extensional (set-theoretic) choice, and I don't see how we could get it without an explicit extensionality axiom (and, accordingly, univalence does the job, if your default setting has univalence, but this is not an anecdotic brick).

(Incidentally, this also means that even without univalence, HITs + forall/trunc commutation implies functional extensionality and propositional extensionality. That's interesting.)

Then, I don't know how much this matters for you but we can try to find a computational content to extensional choice. As said above, we can computationally interpret truncation by just reasoning on the original data. As for predicate extensionality, its intuitive computational content should be applicable. At the end, the piece which remains the most difficult to interpret seems to be proof-irrelevance. There, something like incrementally building finite approximations of the equivalence classes should probably act behind the scene.

**Comment by herbelin** [comment]
@SkySkimmer: The Definition in the middle of Notations are a mistake. Would you be kind to fix it while you are at it. 

About the problem with coqdoc: I don't know what could have happened. This should be investigated.

**Comment by SkySkimmer** [comment]
It looks like it didn't like
``` coq
(** AC!_dep = functional relation reification, with dependent functions
              see AC! *)
```
and prefers 
```
(** AC_dep! = functional relation reification, with dependent functions
              see AC! *)
```
Let's see if that fixes travis too.

**Comment by mattam82** [comment]
@SkySkimmer the comment and commented Set can be removed, it's probably a remnant of when I tried moving the library to full universe polymorphism.

**Comment by SkySkimmer** [comment]
That seems like something for another PR since it's not the only such commented Set around.

**Comment by maximedenes** [comment]
Thanks, this looks interesting! Is it ready for merge? The tests passed.

**Comment by SkySkimmer** [comment]
As far as I'm concerned yes.

**Comment by mikeshulman** [comment]
@herbelin Makes sense: in a context where we have enough ambient structure, various forms of choice are equivalent, but in a more impoverished world they can be distinguished.

**Comment by herbelin** [comment]
@SkySkimmer: looks very reasonable to me.

And an extra general remark: the same way as AC_trunk is a clean/simplified/pure, dont know well how to say it in English, form of AC_fun, I now realize that we could define as well an AC_trunk_setoid which is a clean/simplified/pure form of AC_fun_setoid. 

In any case, @SkySkimmer and @mikeshulman, thanks for the discussion, I learnt a lot.

**Comment by herbelin** [comment]
Euh, one more remark, speaking aloud, to the risk of saying what many certainly already realized, this is actually just double negation shift for the truncation monad rather than for the double-negation monad. So, this is basically Spector's decomposition of double-negation-translated choice into double negation shift and the MLTT-prouvable non-axiom of choice.

**Pull request merged**
