### PR TITLE
Delay kind_to_constr computation in hconstr

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — APPROVED** [review]
Doesn't seem to make a huge difference but this cannot hurt either.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
