### PR TITLE
Remove all remaining calls to “omega” from the standard library

### PR DESCRIPTION
**Pull request by vbgl**

### CODE REVIEW

**Comment by vbgl** [comment]
Benchmark results (old: 0a24fc1f7679f69d362f5fa3f73c1f8716c84bf8; new: 0af01cd7cbffb193f7f19398228ea1099183a1f3).

~~~
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │
│                        │                         │                                             │                                             │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-verdi-raft │ 1339.02 1343.96 -0.37 % │     3737881982755     3748957350631 -0.30 % │     5042395979929     5042864362066 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-character │  176.52  177.12 -0.34 % │      492055394411      493028993772 -0.20 % │      648293292808      648281461267 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-sf-plf │   46.67   46.82 -0.32 % │      131412092642      131399268331 +0.01 % │      170003965867      170021344161 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-unimath │ 4160.89 4168.72 -0.19 % │    11596869440755    11617381368951 -0.18 % │    21349848617101    21349221935390 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-math-classes │  573.45  574.51 -0.18 % │     1600984227276     1602024389596 -0.06 % │     2146359502457     2146428789841 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-color │ 3021.14 3025.91 -0.16 % │     8423339894815     8427605074993 -0.05 % │     9622359203366     9622628986273 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-bedrock2 │  537.06  537.64 -0.11 % │     1495807309793     1496312418568 -0.03 % │     2463903603719     2463839430622 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│       coq-fiat-parsers │  746.59  747.27 -0.09 % │     2087627151015     2089386557815 -0.08 % │     2992825284328     2993383724809 -0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-lambda-rust │ 1561.20 1562.56 -0.09 % │     4349974939769     4352155477947 -0.05 % │     5753197642380     5754275987482 -0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-solvable │  190.56  190.68 -0.06 % │      531223296621      531477336366 -0.05 % │      707979675947      707975559027 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-coqprime │  186.26  186.36 -0.05 % │      516965832394      517108244667 -0.03 % │      919295680152      919256323488 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-odd-order │ 1430.88 1431.52 -0.04 % │     3989265650187     3987050595971 +0.06 % │     6832757350396     6832866301392 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-fiat-crypto-legacy │ 6711.03 6713.40 -0.04 % │    18682991597130    18695075738017 -0.06 % │    30185887309102    30192868915530 -0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│   coq-mathcomp-algebra │  162.57  162.62 -0.03 % │      453313255193      453276737257 +0.01 % │      557707998291      557703136137 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│        coq-fiat-crypto │ 4417.98 4418.85 -0.02 % │    12275760136138    12276808395385 -0.01 % │    19122388083395    19121624949468 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fiat-core │  126.62  126.64 -0.02 % │      359755928330      360503548926 -0.21 % │      442331283326      442339992999 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-flocq │  256.28  256.31 -0.01 % │      711879954592      711653715187 +0.03 % │      906660253445      906629699396 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-rewriter │  579.02  579.00 +0.00 % │     1610570814200     1611226351157 -0.04 % │     2331208723974     2330955350219 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│          coq-fourcolor │ 2166.96 2166.65 +0.01 % │     6038703974725     6041506521550 -0.05 % │    11371178433066    11371117556638 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-coqutil │   62.35   62.34 +0.02 % │      173846591164      173916760979 -0.04 % │      210372450842      210392381862 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│           coq-compcert │  782.56  782.42 +0.02 % │     2180490729665     2180547842207 -0.00 % │     2917937661665     2917821559124 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-corn │ 1556.66 1556.21 +0.03 % │     4345550089836     4345001428354 +0.01 % │     6362122177775     6362469428280 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│         coq-coquelicot │   78.30   78.20 +0.13 % │      214704476866      214833130863 -0.06 % │      261475682595      261493210463 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│     coq-mathcomp-field │  226.96  226.59 +0.16 % │      631986888714      631377148354 +0.10 % │      898109396973      898105356576 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│  coq-mathcomp-fingroup │   51.52   51.43 +0.17 % │      143539532437      143441450006 +0.07 % │      186616918059      186620249650 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│            coq-bignums │   70.10   69.86 +0.34 % │      194907521530      194265735019 +0.33 % │      257242486377      257246976375 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│              coq-verdi │  122.95  122.43 +0.42 % │      340429733671      340833620992 -0.12 % │      423912711413      423903255939 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│               coq-hott │  365.16  363.15 +0.55 % │      990616940885      990257455851 +0.04 % │     1534946311126     1535049681677 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   41.91   41.64 +0.65 % │      115484968960      115576595282 -0.08 % │      139563257270      139570349993 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┤
│             coq-geocoq │ 1621.36 1602.78 +1.16 % │     4528056504062     4478283250693 +1.11 % │     6610537615110     6546451122114 +0.98 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┘
~~~

**Comment by JasonGross** [comment]
Perhaps the standard library should also be benched?  (Is there a reason the standard bench doesn't include the diff for how long it takes to build and install Coq?)

**Comment by ejgallego** [comment]
Any of the maintainers willing to assign this?

Otherwise I'll bench and assign per development policy.

**Comment by ejgallego** [comment]
I used the timing infrastructure to measure impact; unfortunately data failed to be generated, but I did a quick hack to measure just the files changed:
```
This PR:
real	0m11,855s
user	0m9,568s
sys	0m2,254s

Before this PR:
real	0m11,333s
user	0m9,176s
sys	0m2,139s
```
so indeed there is a slight slowdown [0.5~1 sec] in my repeated measures.

**Comment by vbgl** [comment]
Thanks for doing these measurements.

It is a negligible slow-down? An acceptable one?

FTR, the main motivation of this PR is to be able to remove the “omega” plugin from the standard library (note that this removal should also decrease the compilation time of said standard library). The “micromega” plug-in is actively maintained and provides enough functionality to replace the “omega” plugin that is not maintained.

**Comment by ejgallego** [comment]
> It is a negligible slow-down? An acceptable one?

I think it is an OK one, but it would be nice to understand the concrete slowdowns here and file an issue for micromega. Sadly I'm still fighting with the bench tools but maybe next week I can provide more details.

**Comment by ejgallego** [comment]
I thus propose to merge this PR and move to the next one, I'll merge once I get a few minutes to redo the bench and post an issue.

**Comment by ejgallego** [comment]
Ok, merging, plugins/nsatz/Nsatz.v is the only file that sees its runtime increased under this patch, unfortunately the timing script cannot really match two different files so I don't have more info.

**Review by ejgallego — APPROVED** [review]
Differences are minimal and the goal is worth it.

Unfortunately we don't have the proper tools to measure perf differences when .v files change, but so far I only observed a small slowdown on `Nsatz`.

We should keep an eye on performance tho.

**Comment by JasonGross** [comment]
It should not be too hard to give the per-line timing differ a `--fuzz=n` option which allows differences in character locations of up to n before considering lines to be different.  I could probably write this for you this weekend if you'd like?

**Comment by ejgallego** [comment]
> I could probably write this for you this weekend if you'd like?

That'd would pretty amazing @JasonGross , it is the first time I use these scripts tho so I may have some more feedback; for example they seem a bit slow even in my fast machine, I'll have a look.

**Comment by JasonGross** [comment]
@ejgallego #11230

Also, when you said "I used the timing infrastructure to measure impact; unfortunately data failed to be generated", what did you mean by that?

**Comment by ejgallego** [comment]
> Also, when you said "I used the timing infrastructure to measure impact; unfortunately data failed to be generated", what did you mean by that?

Thanks @JasonGross , my problem was in the lines of `Notation.v.after-timing not generated` or something like that; I'll keep you posted.

**Pull request merged**
