### PR TITLE
Revert "Merge PR #6651: Use r.(p) syntax to print primitive projectio…

### PR DESCRIPTION
**Pull request by maximedenes**
…ns."

This reverts commit 4fb4f1adf18648b4fb561986379e033b00423148, reversing
changes made to 349944eb8e3abd51dc2b94051a887253a2ae9198.

We revert because this change introduced regression #6764.

### CODE REVIEW

**Comment by maximedenes** [comment]
This breaks elpi because it changes API. So I'm going to have to postpone a fix (or a revert) to 8.8.0.

**Comment by ejgallego** [comment]
I'm not sure I understood you correctly but IMHO the API should not change from the beta to final release.

**Comment by maximedenes** [comment]
I agree, but I think I can unplug the feature without removing the `GProj` constructor, for 8.8.0.

**Comment by maximedenes** [comment]
(or do a proper fix, if not risky)

**Comment by gares** [comment]
```
gares@gargamel:~/LPCIC/coq-elpi-coq-master$ git grep GProj
src/coq_elpi_glob_quotation.ml:  | GProj _ -> nYI "(glob)HOAS for GProj"
```

I think you can break elpi

**Comment by gares** [comment]
And this is your overlay

https://github.com/LPCIC/coq-elpi/pull/14

**Comment by maximedenes** [comment]
Thanks a lot, @gares. Only elpi failed, so I'm going to merge this, finally.

**Pull request merged**
