### PR TITLE
Update bench default ocaml version

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]
@coqbot bench

**Comment by Alizter** [comment]
I'll merge tomorrow when bench finishes, just in case something surprising happens.

**Comment by ppedrot** [comment]
@Alizter I think you can already merge right now, there is no reason for this to go wrong per se and there is no other way to write the patch.

**Review by ppedrot — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

As you say.

**Pull request merged**
