### PR TITLE
Using Lemma/Theorem instead of Definition for opaque statements of clearly logical status

### PR DESCRIPTION
**Pull request by herbelin**
This is in anticipation of #19029 and fits better with the story about Definition/Theorem given in the refman.

### CODE REVIEW

**Review by olaure01 — APPROVED** [review]

**Comment by olaure01** [comment]
Is there a point in making a difference between `Theorem` and `Lemma` in stdlib?

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
> Is there a point in making a difference between Theorem and Lemma in stdlib?

Not really, some files favor `Theorem`, other `Lemma`.

**Review by andres-erbsen — APPROVED** [review]

**Comment by olaure01** [comment]
This PR should have no visible impact. I will merge tomorrow if no one objects.

**Comment by olaure01** [comment]
@coqbot merge now

**Pull request merged**
