### PR TITLE
[ci] Tentative fix for #7206: MacOS test-suite job failing.

### LINKED ISSUE #7206: MacOS test-suite job started failing a few hours ago
First failure on `master`: https://travis-ci.org/coq/coq/jobs/364005459

```
==> Downloading https://homebrew.bintray.com/bottles/gnu-time-1.9.sierra.bottle.tar.gz
==> Pouring gnu-time-1.9.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gnu-time/1.9: 9 files, 116.3KB
The command "brew install opam gnu-time" failed and exited with 1 during .
```

It seems that `opam` was installed correctly (before) and that the installation fails during the `gnu-time` install step but without an error message.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure fix.

Fixes / closes #7206

### CODE REVIEW

**Comment by Zimmi48** [comment]
Confirmed this fixes the problem here: https://travis-ci.org/Zimmi48/coq/jobs/364105435

Please @ejgallego or @SkySkimmer: merge ASAP (without waiting for all the unrelated tests to pass).

**Review by SkySkimmer — APPROVED** [review]
I don't really get it but it seems to work.

**Comment by Zimmi48** [comment]
The same problem had occurred before with the packaging job (which has more dependencies) so I just imitated the fix (that I had taken much longer to find then).

**Comment by ejgallego** [comment]
By the way I've always considered the CI part of the tree "special", so IMO the release managers should be OK pushing this kind of changes without too much of a delay, the maintainers can always amend later if they'd like to implement a different fix.

**Pull request merged**
