### PR TITLE
Remove outdated note about rlwrap in setup.txt

### PR DESCRIPTION
**Pull request by SkySkimmer**
Debian stable version is 0.42-3 right now.

### CODE REVIEW

**Comment by psteckler** [comment]
FWIW, I'm running Linux Mint 18.1 (latest version is 18.3), and it still has the old, buggy version of rlwrap. It was by reading `setup.txt` that I learned that I needed a newer version. The directions weren't quite right, but I was able to find a coqtop-compatibile version.

**Comment by Zimmi48** [comment]
Maybe just reduce the note to: "If you are using `rlwrap` make sure it is at least version 0.42. You may also use `ledit` alternatively."

**Review by maximedenes — DISMISSED** [review]
As @Zimmi48 wrote, please keep just one sentence explaining what is the minimal required version of rlwrap.

**Comment by SkySkimmer** [comment]
Changed.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
