### PR TITLE
Delayed building of application terms in pretyping

### PR DESCRIPTION
**Pull request by SkySkimmer**
Depends https://github.com/coq/coq/pull/14521 (now merged)

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
This needs a rebase to get a fresh CI, and probably an input by @gares who seemed to be concerned about this set of changes.

**Comment by gares** [comment]
My concerns are the same as in #14521 : can you exhibit a bench which shows an improvement? (even a synthetic one)

**Comment by ppedrot** [comment]
Well, same answer: the problem demonstrated by @JasonGross 's example is solved. Does it count as a synthetic bench?

**Comment by gares** [comment]
Can we have this bench run? How many arguments does an application need to have in order to benefit from the speedup?

**Comment by ppedrot** [comment]
@gares on my machine, this PR starts being faster for about ~1300 applications and the difference quickly diverges after that. Below it's hard to tell because the timing is too imprecise.

**Comment by gares** [comment]
> 1300 applications

what are 1300 applications? a term with 1300 `App` nodes?

**Comment by ppedrot** [comment]
The second one.

**Comment by Janno** [comment]
I am not sure how useful this is but I wanted to see if I could find out more about the timing differences with lower numbers of arguments. I don't think I really succeeded. I think I am probably measuring GC at these low numbers. Still! I have the data and it seems very reproducible across many runs (on my system, at least). Remember, though: _Wer misst, misst Mist._

The way to read this is to compare a white (gray?) line, which is coq-master, with it's succeeding light blue line, which is this MR rebased on the reference master branch. Ignore the last column. Just compare the number in the first one. The filename (e.g. `a10.v`) indicates how many arguments the function `f` accepts. The test cases consist of 1 line of 
```coq
Axiom f : unit->unit->unit->unit->unit->unit->unit->unit->unit->unit->unit.
```
followed by **100 copies** of
```coq
Goal unit.
exact (f  tt tt tt tt tt tt tt tt tt tt).
Abort.
```


| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a10.v` | 95.1 ± 1.2 | 93.5 | 99.0 | 1.01 ± 0.02 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a10.v` | 94.2 ± 1.3 | 92.7 | 98.5 | 1.00 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a20.v` | 105.4 ± 0.9 | 103.8 | 107.2 | 1.12 ± 0.02 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a20.v` | 105.9 ± 0.6 | 104.5 | 107.3 | 1.12 ± 0.02 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a30.v` | 117.9 ± 1.2 | 115.4 | 120.0 | 1.25 ± 0.02 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a30.v` | 117.4 ± 1.1 | 116.1 | 120.6 | 1.25 ± 0.02 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a40.v` | 129.3 ± 1.4 | 127.1 | 132.4 | 1.37 ± 0.02 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a40.v` | 129.0 ± 1.2 | 126.6 | 130.7 | 1.37 ± 0.02 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a50.v` | 140.5 ± 1.6 | 138.2 | 143.8 | 1.49 ± 0.03 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a50.v` | 140.0 ± 1.4 | 137.8 | 142.4 | 1.49 ± 0.03 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a60.v` | 151.9 ± 2.1 | 149.4 | 156.7 | 1.61 ± 0.03 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a60.v` | 151.0 ± 1.7 | 148.6 | 154.0 | 1.60 ± 0.03 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a70.v` | 161.9 ± 2.1 | 158.9 | 168.7 | 1.72 ± 0.03 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a70.v` | 162.2 ± 1.4 | 159.3 | 164.6 | 1.72 ± 0.03 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a80.v` | 172.7 ± 1.4 | 169.9 | 174.9 | 1.83 ± 0.03 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a80.v` | 173.8 ± 2.1 | 170.8 | 179.6 | 1.84 ± 0.03 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a90.v` | 184.8 ± 2.6 | 180.9 | 188.5 | 1.96 ± 0.04 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a90.v` | 183.7 ± 2.2 | 180.9 | 187.3 | 1.95 ± 0.04 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a100.v` | 194.9 ± 1.3 | 192.8 | 198.0 | 2.07 ± 0.03 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a100.v` | 195.0 ± 1.7 | 191.7 | 198.4 | 2.07 ± 0.03 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a110.v` | 206.2 ± 1.3 | 203.7 | 207.9 | 2.19 ± 0.03 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a110.v` | 206.8 ± 2.2 | 203.4 | 211.1 | 2.20 ± 0.04 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a120.v` | 216.3 ± 2.3 | 212.8 | 221.2 | 2.30 ± 0.04 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a120.v` | 215.0 ± 2.3 | 211.8 | 218.9 | 2.28 ± 0.04 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a130.v` | 228.3 ± 1.7 | 225.8 | 230.8 | 2.42 ± 0.04 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a130.v` | 226.6 ± 1.9 | 224.1 | 230.1 | 2.41 ± 0.04 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a140.v` | 240.3 ± 3.7 | 236.2 | 249.1 | 2.55 ± 0.05 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a140.v` | 237.1 ± 3.1 | 232.9 | 243.5 | 2.52 ± 0.05 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a150.v` | 251.7 ± 6.7 | 246.0 | 269.2 | 2.67 ± 0.08 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a150.v` | 248.6 ± 4.0 | 242.9 | 255.6 | 2.64 ± 0.06 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a175.v` | 295.1 ± 2.0 | 292.0 | 299.3 | 3.13 ± 0.05 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a175.v` | 277.1 ± 2.1 | 273.8 | 280.5 | 2.94 ± 0.05 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a200.v` | 308.9 ± 2.2 | 304.3 | 312.3 | 3.28 ± 0.05 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a200.v` | 312.9 ± 4.0 | 306.2 | 319.0 | 3.32 ± 0.06 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a250.v` | 340.1 ± 1.3 | 338.1 | 341.9 | 3.61 ± 0.05 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a250.v` | 339.3 ± 4.1 | 335.9 | 350.3 | 3.60 ± 0.07 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a300.v` | 394.9 ± 3.3 | 389.2 | 401.0 | 4.19 ± 0.07 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a300.v` | 314.1 ± 3.0 | 310.6 | 319.3 | 3.33 ± 0.06 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a500.v` | 634.3 ± 9.2 | 623.5 | 651.6 | 6.73 ± 0.14 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a500.v` | 465.1 ± 4.9 | 458.7 | 473.3 | 4.94 ± 0.09 |
| `/home/janno/src/coq-master/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-master/_build/default /tmp/a1000.v` | 1278.6 ± 8.6 | 1264.0 | 1290.2 | 13.57 ± 0.21 |
| `/home/janno/src/coq-faster-app/_build/default/topbin/coqc_bin.exe -coqlib /home/janno/src/coq-faster-app/_build/default /tmp/a1000.v` | 848.1 ± 6.7 | 839.7 | 864.1 | 9.00 ± 0.14 |

**Comment by gares** [comment]
This is in line with what @ppedrot was measuring, your data shows that for ~150 arguments (repeating 100 times) you see some improvement (which is 1500, not so far for the 1300 measured by PMP). Thanks for measuring this carefully.

To me these numbers are not very convincing, in the sense that while the speedup is there I'm not so sure the extra code is worth it, since very very few (if any) developments will actually see it. Indeed it is very hard to come up with 150 distinct types with very tiny inhabitants (if all the inputs are of the same type you can take a list, or even a primitive array, and go back to arity 1; if the inhabitants are not atoms then typing them will take some time as well). This is why I think this kind of patches should be discussed, possibly "in person".

**Pull request merged**
