### PR TITLE
[library] Make require more independent of the filesystem.

### PR DESCRIPTION
**Pull request by ejgallego**
This is a step towards allowing in-memory requires.

We don't export the right API yet as I think we should do some further
refactoring internally in `library.ml`

There is a minimal change of behavior in terms of feedback, before we
only emitted the file location for the first module, we now do for
all. That should be harmless (and in fact maybe better as the file
access is really happening)

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Added a slight simplification commit

**Comment by ejgallego** [comment]
> Added a slight simplification commit

LGTM thanks!

**Comment by ejgallego** [comment]
The motivation for this is to have my "simple compiler" check a whole set of Coq files without never marshalling an input lib twice (and in fact avoiding intra-theory marshalling at all).

Will it be faster? If so, by how much?

**Comment by SkySkimmer** [comment]
Probably uses more memory if opaque tables don't get evicted

**Comment by ejgallego** [comment]
> Probably uses more memory if opaque tables don't get evicted

Yes, it is expected to use more memory, tho actually memory consumption is not so easy to calculate.

In a fully parallel build, for example with 16 threads, if the theory is very parallel that will eat a lot of memory too. Simple compiler needs to spawn processes too but Linux may be able to share even across processes. I wish I could use OCaml 5.0 to do all the compilation in-process, in that setting I bet this strategy could outperform memory-wise too for maybe `-j 4`.

For opaque tables I really wish we could classify commands that require access to opaque info in the vernac type, that way it would be possible to schedule them much better; for now I'm first implementing the stats on universe variation for `Qed`.

**Comment by ppedrot** [comment]
> For opaque tables I really wish we could classify commands that require access to opaque info in the vernac type

+1 about this. We don't have that many commands that break the opaque barrier, but the current implementation is a real mess.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ejgallego** [comment]
Failure is unrelated.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
