### PR TITLE
FIND_SKIP_DIRS (make): ignore all dot directories

### LINKED ISSUE #11266: Makefile: please also skip directory .pc
#### Description of the problem

Please add in the main Makefile ".pc" to the value of FIND_SKIP_DIRS, like
[this](https://salsa.debian.org/ocaml-team/coq/blob/experimental/master/debian/patches/skip-dot-pc.patch). The .pc directory is used by the quilt patch queue manager to maintain state.

#### Coq Version

8.10.2

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #11266

Not sure if this will work with the gramlib stuff, will fix if it causes issues.

### CODE REVIEW

**Comment by gares** [comment]
You should probably add a `-type d`, since I don't see it and `.*` matches too much

**Comment by SkySkimmer** [comment]
-type d only helps for .merlin.in files, the real issue is that we `find .` so everything gets ignored.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I'm rebasing for you

**Comment by gares** [comment]
Apparently I cannot push to your remote. Could you please take the rebased commit from here: https://github.com/gares/coq/commit/8fcbbbe80d101fdd99387b80e3a82f1dd17dfbdf

**Pull request merged**
