### PR TITLE
Remove broken bench job flocq3

### PR DESCRIPTION
**Pull request by SkySkimmer**
They've been broken for a long time

### CODE REVIEW

**Comment by JasonGross** [comment]
What's wrong with rewriter-perf-SuperFast?  (It's not supposed to be broken)

**Comment by SkySkimmer** [comment]
~~~
- File "./src/Rewriter/Rewriter/Examples/PerfTesting/LiftLetsMap/_10_SuperFast.v", line 3, characters 11-27:
- Error: Illegal application: 
- The term "NatUtil.Thunked.nat_rect" of type "forall P : Type, (unit -> P) -> (nat -> P -> P) -> nat -> P"
- cannot be applied to the terms
-  "list Z" : "Set"
-  "fun H : Z => repeat H (Z.to_nat 1)" : "Z -> list Z"
- The 2nd term has type "Z -> list Z" which should be coercible to "unit -> list Z".
~~~
any bench in the last ? months

**Comment by JasonGross** [comment]
> ```
> - File "./src/Rewriter/Rewriter/Examples/PerfTesting/LiftLetsMap/_10_SuperFast.v", line 3, characters 11-27:
> - Error: Illegal application: 
> - The term "NatUtil.Thunked.nat_rect" of type "forall P : Type, (unit -> P) -> (nat -> P -> P) -> nat -> P"
> - cannot be applied to the terms
> -  "list Z" : "Set"
> -  "fun H : Z => repeat H (Z.to_nat 1)" : "Z -> list Z"
> - The 2nd term has type "Z -> list Z" which should be coercible to "unit -> list Z".
> ```
> 
> any bench in the last ? months

Sorry, I'll fix this shortly, and make sure it doesn't break again (apparently this was missing from the CI of rewriter).  Please don't remove from the bench though.  (Feel free to move it to the end of the list or whatever though)

**Comment by JasonGross** [comment]
The rewriter issue should be fixed by https://github.com/mit-plv/rewriter/pull/88 once I finish and merge it

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
