### PR TITLE
Python script checking missing/unnecessary [needs: rebase] label

### PR DESCRIPTION
**Pull request by SkySkimmer**
The token is used to get higher rate limit.

We could in principle automatically label/unlabel PRs but if there's a bug that could get annoying.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Note that:

- the "needs: rebase" label is sometimes used to indicate something else than a merge conflict (e.g the pull request is not currently based on the right branch);
- sometimes adding a "needs: rebase" label is not absolutely necessary even if there is a merge conflict (if the PR is ready to merge, the tests passed, but there is a conflict in CHANGES, it can be solved by the merger).

So indeed, it's probably better to avoid adding this label automatically.

**Review by Zimmi48 — APPROVED** [review]
I've tested the script. I find it very useful. I suggest adding a direct link to the PR in the output in case some action is required. I also suggest renaming the script to something more generic like `github-check-pull-requests.sh` to let the script be improved over time to check if other actions are needed.

**Comment by Zimmi48** [comment]
Last comment.

I ran the script with:

```
nix-shell -p python3 python3Packages.PyGithub --run ./github-check-rebase.py
```

I guess it could make sense to document this in a comment in the script. It's probably the easiest way to get it running in no time (for those who have already installed Nix at least).

And it would be great if the script saved the GitHub personal access token some place, like `./config/whatever` so that running the script again doesn't require providing the token again (especially given that GitHub lets you see the token just once).

**Comment by Zimmi48** [comment]
> I also suggest renaming the script to something more generic like `github-check-pull-requests.sh` to let the script be improved over time to check if other actions are needed.

For instance, this script could also check for PRs with the "needs: review" label and an approve review. Of course, here also it would not be 100% accurate but could still be helpful.

**Comment by SkySkimmer** [comment]
I keep getting false positives on the "PR is not dirty but is labelled" check, but I can't reproduce them without running the full script.

**Comment by Zimmi48** [comment]
I tried to reproduce but I got just one "is dirty and not labelled" and it was accurate.

**Comment by maximedenes** [comment]
Is this still in progress? I had done a local merge, but it seems new commits were pushed...

**Comment by SkySkimmer** [comment]
Code is never finished, but this should be fine to merge.

**Pull request merged**
