### PR TITLE
[future] Remove unused parameter greedy.

### PR DESCRIPTION
**Pull request by ejgallego**
It was always set to `greedy:true`. Submitting as instructed in #476

### CODE REVIEW

**Comment by gares** [comment]
LGTM

**Comment by gares** [comment]
IIRC one of the optimizations between pure and greedy is "tested" by test-suites/stm/ugly-long-name.v
The commit log may tell you which one.

**Comment by gares** [comment]
sorry I've no time today to figure it out myself.

**Comment by ejgallego** [comment]
Sorry @gares I couldn't locate what you are referring to.

**Comment by JasonGross** [comment]
I suspect @gares ' ugly-long-name is Nijmegen_QArithSternBrocot_Zaux, and the commit is  https://github.com/coq/coq/commit/e47c9a9ddfc26f4f2416cbb0c74cf1bacb9ed97f .  Alas, the message is unhelpful:
```
Regression test suite for STM
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/trunk@16840 85f007b7-540e-0410-9357-904b9bb8a0f7
```

**Comment by gares** [comment]
> I suspect @gares ' ugly-long-name is Nijmegen_QArithSternBrocot_Zaux

Indeed.  If such file passes after the patch with the same *space* complexity, then the patch is good.

`greedy` makes the future chain compute up to the point in which a *pure* future computation is found.  Such pure computation requires no system state to be stored (together with its final result). If the optimization is lost you end up with much more memory used.

**Review by gares — CHANGES_REQUESTED** [review]
If the `test-suite/stm/` passes without eating your RAM.

**Comment by ejgallego** [comment]
> greedy makes the future chain compute up to the point in which a pure future computation is found. Such pure computation requires no system state to be stored (together with its final result). If the optimization is lost you end up with much more memory used.

I am not sure I follow, did you meant to test #476 ? As I pointed out, the `greedy` parameter is actually never used in the code, it is always set to `true` so this change shouldn't make any different as the execution path remains unaltered. wrt to #476 indeed it seems beneficial in many cases such as the bug pointed out there, and so far no drawbacks.

Anyways here are the tests (note that I didn't rebase the PRs so the codebases are slightly different):
```
# Testing #476
$ git log -n 1 --pretty=oneline HEAD
4caa2859abb2db1b17a779bf08aa5683a68948ad [future] Use eager evaluation for chaining values.
$ /usr/bin/time -v bin/coqc test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v 
	Command being timed: "bin/coqc test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v"
	User time (seconds): 1.07
	System time (seconds): 0.04
	Percent of CPU this job got: 97%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.15
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 414984
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 21079
	Voluntary context switches: 27
	Involuntary context switches: 6
	Swaps: 0
	File system inputs: 0
	File system outputs: 1064
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

# Testing #479
$ git log -n 1 --pretty=oneline HEAD
3502cc7c3bbad154dbfe76558d411d2c76109668 [future] Remove unused parameter greedy.
$ /usr/bin/time -v bin/coqc test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v
	Command being timed: "bin/coqc test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v"
	User time (seconds): 1.14
	System time (seconds): 0.04
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.19
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 418472
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 8
	Minor (reclaiming a frame) page faults: 21439
	Voluntary context switches: 49
	Involuntary context switches: 10
	Swaps: 0
	File system inputs: 3728
	File system outputs: 1064
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

# Testing trunk
$ git log -n 1 --pretty=oneline HEAD
75dad64e8c5d7c09145491518290bdb749b2d03c Merge PR#487: Add a forgotten (?) line to "theories/Logic/vo.itarget".
$ /usr/bin/time -v bin/coqc test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v 
	Command being timed: "bin/coqc test-suite/stm/Nijmegen_QArithSternBrocot_Zaux.v"
	User time (seconds): 1.14
	System time (seconds): 0.05
	Percent of CPU this job got: 96%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:01.24
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 415788
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 8
	Minor (reclaiming a frame) page faults: 20761
	Voluntary context switches: 49
	Involuntary context switches: 38
	Swaps: 0
	File system inputs: 3736
	File system outputs: 1064
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```
as expected, things are virtually identical, as the problems in #476 need some specific workloads for the number of `unfreeze` to create a problem. It cuts however a couple of minutes on a few use cases.

**Review by gares — APPROVED** [review]

**Pull request merged**
