### PR TITLE
Update link to refman for master branch.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

cc @vbgl

### CODE REVIEW

**Review by vbgl — CHANGES_REQUESTED** [review]
I think there should be also a link to the documentation of the standard library.

**Comment by Zimmi48** [comment]
Sure. I did not put it yet because the deploy stage has never been reached since the PR that introduced the stdlib deployment because of fiat-crypto failing...
I don't mind delaying this PR until such a link can be added.

**Comment by vbgl** [comment]
Here is the link: https://coq.github.io/doc/master/stdlib/

It seems that some CSS files are missing, but that irrelevant to this issue, I guess.

**Comment by ejgallego** [comment]
> It seems that some CSS files are missing, but that irrelevant to this issue, I guess.

We have the same problem in the artifacts, so that's indeed a bug in the build system.

**Comment by Zimmi48** [comment]
@vbgl Updated.

**Review by vbgl — APPROVED** [review]

**Pull request merged**
