### PR TITLE
Few minor bugs in 8.5

### PR DESCRIPTION
**Pull request by mlasson**
Prior to commit 964d1b70, the dependency files .mllib.d and .mlpack.d
were generated by a call to coqdep using the argument -c (for ocaml
code). While doing some finetuning of the generation of implicit rules,
this commit removed (I think by mistake) this "-c". And without this
-c argument coqdep output nothing on mllib files leading to incorrect
linking of mllibs.

### CODE REVIEW

**Comment by mlasson** [comment]
I add a few commits for minor bugs: 
* add if_verbose for me "Fetchting opaque proofs from disk"),
* fix an error message for inductive with let-definitions,
* remove an extra space in the error message. 

This is completly unrelated to the coq_makefile issue. I should have made another pull-request but I thought that it would be less work for admins to accept them together.

**Comment by mattam82** [comment]
LGTM, @herbelin  @pirbo  or @letouzey do the Makefile changes suit you?

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
Merged in 8.5 branch, since these are minor and useful bug fixes. Thanks, Marc!

**Pull request closed without merging**
