### PR TITLE
chore: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
Dependabot is bad because it spams PRs on forks.

**Comment by Alizter** [comment]
More concretely, AFAIK dependabot is still missing configuration options for the frequency of PRs. @naveensrinivasan what is your motivation for introducing it? Just to avoid using insecure Github actions?

**Review by Zimmi48 — CHANGES_REQUESTED** [review]
At the moment, the only actions that we are using are:

- `actions/checkout@v2`
- `actions/upload-artifact@v2`
- `eps1lon/actions-label-merge-conflict@b8bf8341285ec9a4567d4318ba474fee998a6919`

The first two are not pinned at a specific version, so we already get all the security fixes from GitHub. The last one is pinned at a commit on purpose, precisely because it removes the need to trust updates from the author. So, no, this PR is really not helpful for this repo.

**Comment by naveensrinivasan** [comment]
> At the moment, the only actions that we are using are:
> 
> * `actions/checkout@v2`
> * `actions/upload-artifact@v2`
> * `eps1lon/actions-label-merge-conflict@b8bf8341285ec9a4567d4318ba474fee998a6919`
> 
> The first two are not pinned at a specific version, so we already get all the security fixes from GitHub. The last one is pinned at a commit on purpose, precisely because it removes the need to trust updates from the author. So, no, this PR is really not helpful for this repo.

OK, I'll close it. Thanks

**Pull request closed without merging**
