### PR TITLE
Rocqify Coqlib

### PR DESCRIPTION
**Pull request by ppedrot**
We rename this module and add a deprecated alias that also contains name-replaced APIs.

Overlays:
- https://github.com/coq-tactician/coq-tactician/pull/92

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Not sure if Rocqlib is the right name for this, maybe  `Registered` or some other name which makes it clear that this is based on `Register`

**Comment by ppedrot** [comment]
That was part of the plan, though.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
> Not sure if Rocqlib is the right name for this, maybe `Registered` or some other name which makes it clear that this is based on `Register`

IMHO it's a bit of a nonsense to ignore comments such as this one and to merge these kinds of PRs with overlays without even considering the naming options.

**Comment by proux01** [comment]
This can still be renamed later if we find a better name than the current canonical one.

**Comment by Zimmi48** [comment]
Yes, but my point is that by not waiting for a few days to even consider naming proposals, we take the risk of imposing two overlays to external maintainers instead of a single one. That being said, I won't bother proposing alternatives now, and I guess nobody will, so the result will not be two overlays, but rather not having taken the opportunity of an API renaming to even consider what other names it could have.

**Pull request merged**
