### PR TITLE
Addressing BZ#5713 (classical_left/classical_right artificially restricted to a non-empty context).

### PR DESCRIPTION
**Pull request by herbelin**
See [BZ#5713](https://coq.inria.fr/bugs/show_bug.cgi?id=5713).

The fix is obvious.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Why is this a tactic as opposed to a lemma?

**Comment by herbelin** [comment]
> Why is this a tactic as opposed to a lemma?

The reference manual presents them as classical variants of the `left` and `right` tactics (though applicable only to disjunction), so I guess that this was the motivation of the author.

Note that there is a lemma `imply_to_or P Q : (P -> Q) -> ~ P \/ Q.`, which is actually stronger (intuitionistically) than what `classical_right` does. This means that `classical_right` (resp `classical_left`) could be stronger by testing if the left-hand side of the negation is a negation and using excluded-middle after removing the negation... In which case, it would be strictly more general than applying a lemma...

**Comment by herbelin** [comment]
@skyskimmer: For fun, I wrote the following generalization:
```coq
Require Import Classical.
Ltac make_negative X :=
  match X with
  | ~ ?X => X
  | forall x:?A, ?X => let X := make_negative X in constr:(exists x:A, X)
  | ?X /\ ?Y => let X := make_negative X in let Y := make_negative Y in constr:(X \/ Y)
  | ?X -> ?Y => idtac X Y; let Y := make_negative Y in constr:(X /\ Y)
  | _ => fail
  end.

Ltac classical_right := match goal with
| |- ?X \/ _ => let H := fresh "H" in let X := make_negative X in (destruct (classic X) as [?|H]; [right|left;clear - H;tauto])
| |- ?X \/ _ => (destruct (classic X);[left;trivial|right])
end.

Example ex1 : forall A B, (forall x, x=0 -> ~A/\~B) \/ A.
intros.
classical_right.
```
However, Ltac1 is not powerful enough to deal with the `forall` case (error "this is an object of type constr_under_binders"). I don't understand Ltac2 well enough yet to see how it would be in Ltac2.

**Comment by SkySkimmer** [comment]
Here is a typeclass based version https://gist.github.com/SkySkimmer/45f58ce7163560400fefdb23e94cd36e
Typeclasses understand binders so it can deal with `forall`.
It's also user extensible since they can write their own instances for extra logical connectors.
For instance someone could define 
``` coq
Instance neg_le_gt n m : Neg (n <= m) := { neg := m < n }.
Proof. apply Nat.nle_gt. Defined.
```

**Comment by herbelin** [comment]
@SkySkimmer: Thanks!

**Comment by maximedenes** [comment]
So what should we do? Merge this PR in the short term and deprecate it in favor of a lemma-based approach in the long term, when we redesign the libraries?

**Comment by silene** [comment]
> Merge this PR in the short term

Yes.

I have mixed feelings though. I have a hard time believing the original code was some kind of mistake; clearly the developer was trying to achieve something there.

**Comment by SkySkimmer** [comment]
By the way `classical_{left,right}` is also in https://github.com/coq/coq/blob/master/doc/faq/FAQ.tex#L902-L910
The commit adding them to FAQ.tex is 50d849aec24e45da6922b0d1403814f3604c77ef (2004) and the commit adding them to Classical_Prop.v is 14e850d63d17d9a7094a23d2a59ca9f968b5976a (2005) so the FAQ version came first and the other was probably a copy-paste.

**Comment by Zimmi48** [comment]
Any opposition to backporting this? This is a change in a tactic definition, so normally it doesn't qualify for a backport between the beta and the final, but given that this is kind of trivial, I would say it is harmless to backport.

**Pull request merged**
