### PR TITLE
remove NArith.Ndist.v

### PR DESCRIPTION
**Pull request by andres-erbsen**
- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

### CODE REVIEW

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
Could anyone help me out with the doc failure? As this change does not touch `theories/Arith/Arith_base.v`, I am not sure where to list it.

The bedrock2 failure appears unrelated. The last non-refactor change to this file was seems to be 2da547dfc9e5b98e366da2fc959e9d812bdf25b0 from Sun Apr 8 2001 by Christine Paulin who I don't know a Github username for. I am not aware of any uses of this file. Vendoring the contents of this file would be a backwards-compatible fix. Given all this, do we want a deprecation cycle here? (

**Comment by Alizter** [comment]
@andres-erbsen doc failure is also upstream and unrelated.

**Comment by ana-borges** [comment]
What's the motivation for deleting the file? That it hasn't been updated since 2001?

**Comment by jfehrle** [comment]
A more specific PR title would be nice, e.g. mentioning `NDist.v` or `NArith/NDist.v`.

**Comment by andres-erbsen** [comment]
I am proposing to remove this library because it is not used or documented (except for code comments). As far as I understand, it was dead on arrival and has remained that way throughout the years while requiring maintenance on several occasions. Even so, the conventions in this file are substantial behind the standards of most files working with Z and N. I would not recommend building on top of this file even if the concept seems desirable.

What would be the motivation to keep this file?

**Comment by proux01** [comment]
@andres-erbsen you are probably right that this could be removed but this requires a bit more work.
The usual policy before removing something from Coq is to first deprecate it to warn the users for at least two releases before actual removal. Unfortunately IINM we don't yet have a way to deprecate a full module. THis means you have to deprecate each definition/lemma/... individually (you can look for instance at PRs like https://github.com/coq/coq/pull/14736 for examples of use of the deprecated attribute).
Once this done, the file with deprecaton could be removed two releases later.
This also requires a changelog entry.

**Comment by proux01** [comment]
No there is nothing automatic. Note that a good way to simplify things would be a solution to deprecate entire modules. This has been already discussed a few times but nobody found time to implement it yet.

**Comment by proux01** [comment]
Deprecate all definitions/lemmas/... by means of an intermediate notation. Grep for `#[deprecated` in `theories` for examples.

**Pull request closed without merging**
