### PR TITLE
Selection of occurrences of indices now using pattern-matching in `destruct`/`induction`

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** feature; depends on #6844.

This is an exploration towards making `destruct`/`induction`/`edestruct`/`einduction` succeeds more often by using pattern-matching on indices to find instances for the variables of the lemma. A typical example targetted by this PR is:
```coq
Goal forall x y , (forall y, x < S y) -> x = S (S y) -> x = y.
intros.
destruct H.
```
I however wonder whether this may be either too strong or too weak but not the right level. When several subterms match, the default (by consistency with what is done for the main term on which `destruct` is applied) is to consider the one occurring in the most ancient hypothesis is taken (other strategies could be possible, like failing if several subterm matching syntactically are found; or, using subterm selection up to conversion, or up to inner conversion).

This is in the direction of making `destruct` stronger in interactive mode. In the context of developping bricks for a tactic programming language, this would probably too strong and too difficult to control (compared to providing a language of primitive functions for subterm selection).

This is nothing compared to what an ideal extension of `destruct` could do, being able to invert automatically variables which can be so, as in
```coq
Goal forall x y , (forall y, x < S y) -> x = S y -> x = y.
intros; destruct H.
```
where we could detect that the second `y` can be rewritten as `pred (S y)` so that a most general unifier taken into account all occurrences of `y` can be found. In this sense, this PR is probably not good enough. (Neither `dependent destruction` nor `inversion` seem to be able to do that straightforwardly either.)

This change impacts `dependent destruction` since it calls `destruct`.

Wondering about the opinion of users.

Wondering about the compatibility with existing developments.

Wondering about similar works in this direction.

- [ ] Documentation: wondering whether this is the right time to document this level of details. I'm a bit reticent a priori.
- [ ] Probably needs a note in CHANGES so that users confrounted to an incompatibility can understand from where it comes

### CODE REVIEW

**Comment by ppedrot** [comment]
@herbelin, @mattam82 how does this compare to Equations?

**Review by ppedrot — COMMENTED** [review]
I definitely don't feel qualified to review this PR.

**Comment by mattam82** [comment]
Dependent destruction/Equations would not infer pred either, but I think it’s too strong to ask for that. I don’t understand the example exactly, which H is it that you destruct and what result do you expect?

**Comment by herbelin** [comment]
> Dependent destruction/Equations would not infer pred either, but I think it’s too strong to ask for that. I don’t understand the example exactly, which H is it that you destruct and what result do you expect?

The first example is a heuristic. The `H`, once instantiated, is of type `x < S ?y` and the idea was to look for a pattern in the goal which matches `S ?y`, on the same principle that `destruct (S _)` would also search for a subterm matching `S _` in the goal.

My second example is uselessly too complicated. One could simply consider:
```coq
Goal forall x y , x < S y -> x = y.
intros; destruct H.
```
where I would expect the first remaining goal to be `x = pred (S x)` (and not `x = y` as of now).

**Comment by ppedrot** [comment]
BTW, this is is one year old and unlikely to converge any time soon. Rather than keeping it open as a PR, which as the name indicates is a *request*, it would probably be better to write down the proposal somewhere (in the wiki perhaps?) and / or discuss it thoroughly at a WG.

**Comment by SkySkimmer** [comment]
No progress towards merge.

**Pull request closed without merging**
