### PR TITLE
ComInductive universe computation cleanups

### PR DESCRIPTION
**Pull request by SkySkimmer**
This PR reimplements ComInductive.inductive_levels to avoid needing universe minimization and to avoid needing adhoc max_sort functions. It also makes record.ml use inductive_levels instead of its own reimplementation.

This is a necessary step before kernel sort polymorphism.

~Depends https://github.com/coq/coq/pull/17810 (not a real dependency but it should be merged before this PR)~ (merged)

Overlays:
- https://github.com/LPCIC/coq-elpi/pull/474
- https://github.com/ejgallego/coq-serapi/pull/346
- https://github.com/QuickChick/QuickChick/pull/336

Backwards compatible:
- https://github.com/HoTT/Coq-HoTT/pull/1739
- https://github.com/jwiegley/category-theory/pull/128
- https://github.com/mit-plv/coqutil/pull/91
- https://github.com/mit-pdos/perennial/pull/52
- https://github.com/coq-community/coq-ext-lib/pull/138
- https://github.com/MetaCoq/metacoq/pull/971
- https://github.com/Mtac2/Mtac2/pull/389

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Changes:
- records would get lowered to Prop even with univ poly on (eg 3352, mostly produces instance length errors in the test suite). This is not a bug, it makes the behaviour of records the same as the one of inductives.
- bug `Class silly {T} := term : T.` sends qvar to the kernel (because Evarutil.finalize is doing the variable collapse, but we are normalizing qvars in the closure which uses the outdated evar map) (3382, 4781, probably all the "The kernel received a sort variable" failures)

The Evarutil.finalize is an API design issue, I'm not sure what the right solution is. 
In the case of record.ml we are doing `ESorts.kind sigma _` while inside the closure (so `sigma` is outdated), we also do `nf_relevance sigma`. Having `finalize` pass the updated evar map would work fine for relevances, but for normalizing univs it means it won't register the universe as being needed and may incorrectly restrict it.
Another way to work would be to wrap things in econstr to normalize them, ie do `destSort sigma (nf (mkSort _))` instead where `nf` is the function given to the closure. Here `destSort` is fine as finalize didn't touch the evars, just the universes. This is still pretty footgunny though.
Maybe we should pass a bunch of normalization functions for various types instead?
Or maybe we say that the case of record.ml is too complicated for finalize.

**Comment by SkySkimmer** [comment]
- `CoInductive G := { g : G }.` now produces `G : Prop` instead of `G : Type` in universe monomorphic mode

- this produces `foo : Set` `bar  : Prop` instead of both `: Type` (bug, `bar` is squashed without explicit `: Prop`) (shows up in vm_records test with the coinductive version, but the change is also for regular inductives)
```
Inductive foo := Foo (_ : bar)
with bar := Bar (_ : foo).
```

**Comment by SkySkimmer** [comment]
All the changes I know about should be either fixed or are bugfixes.

**Comment by SkySkimmer** [comment]
Pipeline on my repo while we have no workers: https://gitlab.com/SkySkimmer/coq/-/pipelines/919443100

**Comment by SkySkimmer** [comment]
~~~coq
Unset Universe Minimization ToSet.

Monomorphic Inductive redlist A := rlnil | rlcons : A -> redlist A -> redlist A.
~~~
is now non template poly
Indeed we get constraints `paramU <= arityU, Set <= arityU` with mimim to set off this produces `arityU := paramU` but the `Set <=` constraint remains because lbound is Prop and so prevents templateness

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
The error in elpi is because the Coq commit tested doesn't include https://github.com/coq/coq/issues/17955 but elpi does include the merged overlay for it.

**Comment by ppedrot** [comment]
Are we sure that the devs depending on elpi are compiling though?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
