### PR TITLE
Avoid using is_ground_env in evarconv

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should make the ephemeron-based memo not important (is_ground_env
is only used for program_inference_hook)

Alternative to https://github.com/coq/coq/pull/15492 and https://github.com/coq/coq/pull/15504

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1986737818

**Comment by ppedrot** [comment]
Interesting alternative, but is it really equivalent? It might be the case that we don't need to unfold an evar to check for conversion.

**Comment by SkySkimmer** [comment]
I made it so we only care about has_evar if conversion failed.

**Comment by SkySkimmer** [comment]
Why is nix unhappy? https://gitlab.com/coq/coq/-/jobs/1986737842 @coq/nix-maintainers

**Comment by Zimmi48** [comment]
I've never seen this kind of failure before. In principle, Nix builds should be reproducible. But here it looks like this failure appeared only in this PR and nowhere else. I've retried the job to see what would happen.

**Comment by ppedrot** [comment]
I had a similar failure on my PR and had to restart it as well.

**Comment by Zimmi48** [comment]
Indeed, the restarted build succeeded where the previous run had failed.

Failed build:

```
building '/nix/store/qk33w6qgdarzik7j3k6c4kl6b1q5a0ql-ocaml4.09.1-zarith-1.12.drv'...
unpacking sources
unpacking source archive /nix/store/agnv4yryhisn2pdaw8aydzhwqprs2ics-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
install flags: SHELL=/nix/store/wadmyilr414n7bimxysbny876i2vlm5r-bash-5.1-p8/bin/bash install
make: *** No rule to make target 'install'.  Stop.
note: keeping build directory '/builds/coq/coq/nix-build-ocaml4.09.1-zarith-1.12.drv-0'
builder for '/nix/store/qk33w6qgdarzik7j3k6c4kl6b1q5a0ql-ocaml4.09.1-zarith-1.12.drv' failed with exit code 2
cannot build derivation '/nix/store/r41xw45pqksnp5l13rl1wkqh9vbn2b7z-coq.drv': 1 dependencies couldn't be built
error: build of '/nix/store/r41xw45pqksnp5l13rl1wkqh9vbn2b7z-coq.drv' failed
```

Successful build:

```
building '/nix/store/qk33w6qgdarzik7j3k6c4kl6b1q5a0ql-ocaml4.09.1-zarith-1.12.drv'...
unpacking sources
unpacking source archive /nix/store/agnv4yryhisn2pdaw8aydzhwqprs2ics-source
source root is source
patching sources
configuring
configure flags: -installdir /nix/store/42s1yzbihnqscw5vw88hf42gvia6jhqr-ocaml4.09.1-zarith-1.12/lib/ocaml/4.09.1/site-lib
binary ocaml: found in /nix/store/gx9nlgh4rvrzg3kgf3ac7bck7qbw6wqy-ocaml-4.09.1/bin
binary ocamlc: found in /nix/store/gx9nlgh4rvrzg3kgf3ac7bck7qbw6wqy-ocaml-4.09.1/bin
...
```

One can see that it is building the same derivation and unpacking the same source archive, but for some reason, in the first case, it looks empty (no configure, no Makefile). This cannot be just a network issue, because Nix should check that the content of the source archive matches the specified hash.

@coq/nix-maintainers Is this a Nix bug that we should report upstream then?

**Comment by Zimmi48** [comment]
>I had a similar failure on my PR and had to restart it as well.

More than similar. If you are referring to https://gitlab.com/coq/coq/-/jobs/1986623568, the failure was exactly the same.

**Comment by gares** [comment]
`no configure script, doing nothing` ... to me it did not unpack the sources. Is the VM the same? (we recently had a weird one with a full disk)

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                    coq-core │   96.87    97.29  -0.43 │   386533562298    382939673585   0.94 │   433373410241    433267959851   0.02 │  273128   273940  -0.30 │   0    0      nan │
│               coq-fourcolor │ 1498.53  1503.58  -0.34 │  6613940041671   6639924167694  -0.39 │ 12080791865930  12081767211040  -0.01 │  724552   724856  -0.04 │   0    0      nan │
│                  coq-stdlib │  403.72   405.08  -0.34 │  1629467156475   1634876301584  -0.33 │  1405038896475   1405079628347  -0.00 │  597732   598696  -0.16 │   0    0      nan │
│                coq-bedrock2 │  188.75   189.06  -0.16 │   848037335359    847091248594   0.11 │  1565226256951   1565424103531  -0.01 │ 2049320  2049548  -0.01 │   1    0      nan │
│        coq-mathcomp-algebra │   62.22    62.31  -0.14 │   283876767625    283519372455   0.13 │   394896610077    395757872923  -0.22 │  558372   558168   0.04 │   0    0      nan │
│      coq-mathcomp-character │   75.49    75.58  -0.12 │   344785246298    344849781942  -0.02 │   525119972460    525173500008  -0.01 │  731972   728784   0.44 │   0    0      nan │
│              coq-verdi-raft │  560.98   560.87   0.02 │  2551783286790   2552126345439  -0.01 │  3940871089557   3939303834400   0.04 │ 1222576  1231760  -0.75 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  916.19   915.51   0.07 │  4121389880178   4118315930746   0.07 │  7152709261346   7155479848501  -0.04 │ 1215464  1143032   6.34 │   0    0      nan │
│                 coq-bignums │   27.78    27.74   0.14 │   125795628401    125541622932   0.20 │   172144613333    172168038612  -0.01 │  466804   464668   0.46 │   0    0      nan │
│                coq-rewriter │  366.90   366.02   0.24 │  1660621447285   1656926509062   0.22 │  2717767612700   2719575376557  -0.07 │  965020  1059876  -8.95 │   0    0      nan │
│      coq-mathcomp-odd-order │  552.81   551.39   0.26 │  2528942645541   2521771382570   0.28 │  4264655513260   4280004275489  -0.36 │  931012   931648  -0.07 │   0    0      nan │
│                    coq-corn │  767.99   765.03   0.39 │  3481781811811   3468323336638   0.39 │  5359299551934   5363096828703  -0.07 │  868932   868656   0.03 │   0    0      nan │
│          coq-mathcomp-field │  111.40   110.97   0.39 │   508844972885    506570283351   0.45 │   837409389882    838559038343  -0.14 │  651560   648960   0.40 │   0    0      nan │
│                   coq-verdi │   48.14    47.95   0.40 │   216828198592    216054062172   0.36 │   321827857992    321821358569   0.00 │  832032   831992   0.00 │   0    0      nan │
│                    coq-hott │  153.35   152.64   0.47 │   691042567898    685592016008   0.80 │  1073382416020   1074007965718  -0.06 │  656000   659048  -0.46 │   0    0      nan │
│       coq-mathcomp-solvable │   86.42    86.00   0.49 │   394554714781    392139807152   0.62 │   608778797288    609330042272  -0.09 │  669980   668232   0.26 │   0    0      nan │
│                 coq-coqutil │   34.83    34.66   0.49 │   155774022764    154218670095   1.01 │   207462000832    207574500600  -0.05 │  604036   604092  -0.01 │   0    0      nan │
│  coq-performance-tests-lite │  778.21   774.31   0.50 │  3493882576246   3475801487822   0.52 │  5921153313887   5916449070691   0.08 │ 2322472  2322564  -0.00 │   3    0      nan │
│                  coq-flocq3 │   76.11    75.72   0.52 │   344988554420    342954794123   0.59 │   454326259163    454444076377  -0.03 │  990592   990604  -0.00 │   7    0      nan │
│            coq-fiat-parsers │  334.13   332.38   0.53 │  1482057114192   1472460713817   0.65 │  2430740596107   2435248128078  -0.19 │ 2783652  2785092  -0.05 │   0    0      nan │
│             coq-fiat-crypto │ 2865.86  2850.28   0.55 │ 12917470356248  12847941078874   0.54 │ 23764941692100  23757433388924   0.03 │ 3845004  3770124   1.99 │   0    0      nan │
│                 coq-unimath │ 3665.82  3645.72   0.55 │ 16673501143416  16570186513711   0.62 │ 33165921867521  33162255589581   0.01 │ 3845280  4126664  -6.82 │   0    0      nan │
│       coq-mathcomp-fingroup │   23.24    23.10   0.61 │   105898223753    105204095048   0.66 │   154964556608    154979535416  -0.01 │  477764   477508   0.05 │   0    0      nan │
│                   coq-color │  254.54   252.95   0.63 │  1144398252192   1135798113025   0.76 │  1538274492388   1538156853807   0.01 │ 1148216  1149240  -0.09 │   0    0      nan │
│           coq-iris-examples │  424.82   421.85   0.70 │  1926176350109   1911919192914   0.75 │  2916872310753   2917682733491  -0.03 │ 1173348  1165744   0.65 │   0    0      nan │
│       coq-engine-bench-lite │  177.51   176.24   0.72 │   761890064139    755638730264   0.83 │  1480574928735   1485756181767  -0.35 │ 1172620  1172660  -0.00 │   0    0      nan │
│            coq-math-classes │   93.25    92.57   0.73 │   421069711624    417311410228   0.90 │   587577507961    587784766930  -0.04 │  495680   496028  -0.07 │   0    0      nan │
│                  coq-geocoq │  691.76   686.70   0.74 │  3141581746547   3118559675635   0.74 │  4942094179202   4942751375625  -0.01 │ 1075148  1074272   0.08 │   0    0      nan │
│    coq-metacoq-translations │   19.88    19.72   0.81 │    87438634173     86779187767   0.76 │   152034612869    152942921139  -0.59 │  929064   930012  -0.10 │   0    0      nan │
│                coq-compcert │  280.72   278.44   0.82 │  1262214950740   1250539323656   0.93 │  1876293611089   1876285136152   0.00 │ 1098060  1097472   0.05 │   0    0      nan │
│               coq-perennial │ 4001.80  3968.44   0.84 │ 18151047385249  17991612092024   0.89 │ 29877814565949  29880874315846  -0.01 │ 2615044  2602808   0.47 │   0    0      nan │
│         coq-metacoq-erasure │   63.59    63.02   0.90 │   283179223860    279850211391   1.19 │   423251735518    423119711494   0.03 │ 1068320  1071640  -0.31 │   0    0      nan │
│              coq-coquelicot │   34.27    33.96   0.91 │   153544867116    152038203669   0.99 │   201512970787    201468676912   0.02 │  746988   745600   0.19 │   4    0      nan │
│           coq-metacoq-pcuic │  485.95   481.36   0.95 │  2204989950021   2182669095459   1.02 │  3110308603287   3111079682523  -0.02 │ 1123700  1123880  -0.02 │   0    0      nan │
│        coq-metacoq-template │   73.73    72.98   1.03 │   326757579423    322799142841   1.23 │   489647188213    489803718520  -0.03 │  699228   698516   0.10 │   0    0      nan │
│      coq-mathcomp-ssreflect │   25.84    25.51   1.29 │   116563773027    115098650293   1.27 │   146874611542    146853301229   0.01 │  531588   531668  -0.02 │   0    0      nan │
│                     coq-vst │ 1061.74  1048.15   1.30 │  4810328194051   4747440484904   1.32 │  7794722549346   7794495748398   0.00 │ 2117472  2120692  -0.15 │   0    6  -100.00 │
│     coq-metacoq-safechecker │  186.68   183.40   1.79 │   848692042993    833936073301   1.77 │  1125746076185   1125749707393  -0.00 │ 1226228  1217896   0.68 │   0    0      nan │
│               coq-fiat-core │   54.31    53.34   1.82 │   234493554134    229789148193   2.05 │   322189548928    322241656417  -0.02 │  477364   477104   0.05 │   0    0      nan │
│                coq-coqprime │  182.60   177.40   2.93 │   832666894957    808763050961   2.96 │  1554241396808   1554361914257  -0.01 │  906044   905872   0.02 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
~~~

**Comment by SkySkimmer** [comment]
Benches here and https://github.com/coq/coq/pull/15504 look about equivalent, which do we prefer?

**Comment by ppedrot** [comment]
I prefer your PR.

**Comment by ppedrot** [comment]
@SkySkimmer you still need a PR to remove the memo function in Evarutil after this one.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
