### PR TITLE
ide: shift+enter to find backwards

### PR DESCRIPTION
**Pull request by slrnsc**
**Kind:** feature

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by slrnsc** [comment]
The `plugin:ci-coqhammer` CI job is the only one that failed (complaining of `Error: Unbound module Stdlib` on L79 of `src/lib/hhlib.ml`), and I don't see how it could be related to this PR which only touches a single file in `ide/`.

**Review by herbelin — APPROVED** [review]
Thanks a lot for the PR, that's a useful addition.

Would you be interested in implementing shift-enter also for replacing? If yes, we can wait a bit. If not, I believe this can be merged soon (say at the end of the week).

PS: `plugin:ci-coqhammer` is failing also in other PRs, so it seems indeed unrelated.

**Comment by slrnsc** [comment]
It isn't clear to me whether shift-enter for replacing would be expected to replace the previous match (which seems intuitive, but would be asymmetric with the buttons, as there isn't a button for "replace previous" at all) or to replace all (which would be symmetric use of shift to press the other button but doesn't have a precedent in other editors as far as I'm aware).

I would leave this patch as-is until someone wants to do a deeper dive on CoqIDE's find-replace functionality, if that's alright.

**Comment by herbelin** [comment]
> ... but would be asymmetric with the buttons, as there isn't a button for "replace previous" at all

OK, fine, then merging. Thanks again!

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
