### PR TITLE
coqc: support -o option to specify output file name

### PR DESCRIPTION
**Pull request by gares**
The -o option lets one put .vo or .vio files in a directory of choice,
i.e. decouple the location of the sources and the compiled files.
This ease the integration of Coq in already existing IDEs that handle
the build process automatically (eg Eclipse) and also enables one to
compile/run at the same time 2 versions of Coq on the same sources.

Eexample: b.v depending on a.v

  coq8.6/bin/coqc -R src Test -R out8.6 Test src/a.v -o out8.6/a.vo
  coq8.6/bin/coqc -R src Test -R out8.6 Test src/b.v -o out8.6/b.vo

  coq8.7/bin/coqc -R src Test -R out8.7 Test src/a.v -o out8.7/a.vo
  coq8.7/bin/coqc -R src Test -R out8.7 Test src/b.v -o out8.7/b.vo

### CODE REVIEW

**Comment by gares** [comment]
I think such a patch could be back ported to 8.5 to ease the migration 8.5 -> 8.6

@ale-f you may want to try this patch.

**Comment by mattam82** [comment]
LGTM. Actually in your example, the -R src Test will become useless no?

**Comment by gares** [comment]
My understanding is that -R src/ is to give a logical name to src/a.v, while -R outv8.6/ is to make a.vo found while compiling b.v.

I guess @silene knows better ;-)

**Comment by silene** [comment]
Right. But I guess your patch should be modified so that, whenever -o is used, it is not the source file that is used to guess the logical name but the target file. In fact, I had the same reaction as Matthieu.

**Comment by gares** [comment]
Oh, I see what you mean.  I'll look into it.

**Comment by silene** [comment]
And to answer Matthieu's question, yes, it just considers both directory trees whenever it looks for a file.

**Comment by gares** [comment]
Should work as expected now.

**Comment by silene** [comment]
If I am not mistaken, it seems like the old argument of Library.start_library is no longer used for anything useful. So I would suggest removing it and moving the error checking part to the only caller (?) of the function: Vernac.compile. In fact, I would suggest doing the same kind of clean up for Aux_file.start_aux_file_for. It should be renamed into start_aux_file and it is its caller who should be responsible for composing the file name. That would avoid this ugly optional argument.

**Comment by gares** [comment]
Good remarks, I'll clean it up.

**Comment by gares** [comment]
There we are, should be cleaner now.

**Pull request merged**
