### PR TITLE
[bugfix] Fixes #9967.

### LINKED ISSUE #9967: Cast is using vm for type-checking, even when byte compiler is disabled.
#### Description of the problem

The `<:` notation is translated to `VMcast`, and `vm_conv_gen` invokes the VM even if Coq was configured with `-bytecode-compiler no`. In `vm_conv_gen`, the flag `(typing_flags env).enable_VM` is tested, but this flag is set to `true` by default, unconditionally, since #8870.

#### Coq Version

8.10 (master)

### PR DESCRIPTION
**Pull request by corwin-of-amber**
**Kind:** bug fix.

Fixes #9967.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please use a more informative commit message.

**Comment by ejgallego** [comment]
Was this bug introduced in https://github.com/coq/coq/pull/8870 ?

**Comment by ejgallego** [comment]
Ummm, maybe that's not a bug in Coq, but in the jsCoq toplevel [sorry @corwin-of-amber only now I could look at the code]

I think the idea of #8870 was to delegate flags to the upper layers, so maybe is jsCoq who should do:
```
 Global.set_VM false;
 Global.set_native_compiler false;
```
as done by coqtop.

**Comment by ejgallego** [comment]
Anyways the handling of kernel flags need cleaning, I have a PR doing it somewhere so this kind of bugs don't happen again.

**Comment by corwin-of-amber** [comment]
Ok, so should we discard this one?

**Comment by corwin-of-amber** [comment]
Will be fixed by @ejgallego in a separate PR.

**Pull request closed without merging**
