### PR TITLE
Fix Windows builds: OPAM has changed its URL schema.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure fix.

### CODE REVIEW

**Review by MSoegtropIMC — APPROVED** [review]
I did some search and concluded that the official URL for this package is
```
http://download.camlcity.org/download/findlib-1.8.0.tar.gz
```
from this page:
```
http://projects.camlcity.org/projects/findlib.html
```
The contents is identical to the opam package, except that the opam package contains two additional files we don't need.

If it is urgent, the new opam URL is fine, otherwise I would prefer to use the URL mentioned above.

**Comment by Zimmi48** [comment]
@MSoegtropIMC The reason to use another one in #6739 is that the site camlcity was frequently down. This change has proved quite efficient until now.

**Comment by ejgallego** [comment]
Indeed; this is quite urgent as the CI is broken; I will take over a bit later if @MSoegtropIMC cannot do the merge today.

**Comment by ejgallego** [comment]
@MSoegtropIMC , note that `camlcity.org` seems to be hosted in some kind of home-server. As @Zimmi48 pointed out, we had very frequent outages in the past. The OPAM archive change is a kind of exceptional event so we should keep using that one.

**Comment by MSoegtropIMC** [comment]
Ok, if there is a good reason to use a secondary source, I am fine with it.

My plan was to do the merge today around 10:30 today, after CI went through, but fore sure if someone is waiting for it, I don't mind if it is done earlier by someone else.

**Comment by MSoegtropIMC** [comment]
@Zimmi48, @maximedenes : one thing which went slightly wrong with this merge: I recently changed my committer email to a git email. I updated my certificates but forgot to do so on my laptop from which I did run this merge, so the signature doesn't match the email and the commit appears as unverified. This is something one might want to check in the merge-pr.sh script. (I could likely quickly do a PR for this).

**Comment by Zimmi48** [comment]
Sure, if you know how to do so.

**Comment by MSoegtropIMC** [comment]
I created PR #8512.

Since this merge is still on top of the history, shall I quickly redo it signed?

**Pull request merged**
