### PR TITLE
Use lists instead of arrays for cbv application nodes.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by Alizter** [comment]
What is the typical length of these lists/arrays?

**Comment by ppedrot** [comment]
For the target I have in mind (fiat-crypto) I think they can be quite large due to PHOAS.

**Comment by ppedrot** [comment]
As a general rule of thumb, arrays are quite badly behaved in OCaml. They incur some penalties due to mutability and page table check. We had to fine-tune kernel reduction for instance, to expand the array mapping on small length to produce much more efficient code. `Array.make` is quite catastrophical.

**Comment by JasonGross** [comment]
>
```
| 111.6310  98.9160  -12.7150  -11.39%    22  coq-fiat-crypto-with-bedrock/src/Rewriter/Passes/ArithWithCasts.v.html                    │
│  95.4400  83.1020  -12.3380  -12.93%    20  coq-fiat-crypto-with-bedrock/src/Rewriter/Passes/NBE.v.html                               │
│  70.4970  65.4030   -5.0940   -7.23%    27  coq-fiat-crypto-with-bedrock/src/Rewriter/Passes/ToFancyWithCasts.v.html                  │
│  69.5500  68.1010   -1.4490   -2.08%   137  coq-fiat-parsers/src/Parsers/Refinement/SharpenedJSON.v.html                              │
```

Impressive!  Thanks!

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
Any takers? @gares?

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
