### PR TITLE
Change rewrite rules arrow to =>

### PR DESCRIPTION
**Pull request by yannl35133**
A consensus of five people agreed to this arrow

### CODE REVIEW

**Comment by jfehrle** [comment]
Aside from the merits (it looks OK but I don't have a strong opinion), we generally don't make breaking changes without a deprecation process.  That would mean supporting both `>->` and `=>` in one release with a warning message before requiring the change in a future release.  And we always have a changelog for breaking changes.

Why `=>` and not `->` as used in the rewrite tactic?  What is the relationship to the use of `>->` in the Identity and Coercion commands?  The grammar seems to use both `->` and `=>`, not sure there's a pattern to it.

> A consensus of five people agreed to this arrow

That's hardly persuasive.  How about providing some analysis of the proposed change?

**Comment by Alizter** [comment]
This feature was introduced in 8.20. cc @proux01 @silene is there any chance this can be squeezed in?

**Comment by proux01** [comment]
Yes, we still have time to backport the fix between the release of 8.20.0 (sorry, this was discussed offline during the CUDW)

**Comment by proux01** [comment]
And of course no need for any deprecation since this wasn't actually released.

**Comment by proux01** [comment]
For reference, there is some link with https://github.com/coq/coq/issues/18808

**Comment by proux01** [comment]
@coqbot run full ci

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
