### PR TITLE
[doc] Explicitly mention exponential notation in number syntax

### LINKED ISSUE #13280: Documentation should specify what scientific notation on hexadecimal numbers means
#### Description of the problem

In https://github.com/coq/coq/blob/a12112c15cdcb0467d4cf5f5a7cfa639852ccd49/doc/sphinx/language/core/basic.rst#L114-L134

There is no description of the semantics of `e`/`E` nor `p`/`P`.  I know from common usage that `e`/`E` means `*10^`, and apparently (from experimentation) `p` means `*2^`.  Both of these should be documented.

cc @proux01

#### Coq Version

master

### PR DESCRIPTION
**Pull request by WojciechKarpiel**
Hi!
This is a minor documentation change that closes #13280

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by WojciechKarpiel** [comment]
Thanks for the fast feedback!

**Review by jfehrle — APPROVED** [review]
LGTM.  @proux01 do you want to be the assignee since you're a subject matter expert?

**Review by proux01 — APPROVED** [review]
LGTM

**Comment by proux01** [comment]
Thanks @WojciechKarpiel and congrats for your first contribution here!

**Pull request merged**
