### PR TITLE
STM classifier: Guarded and Validate Proof are queries not proof steps

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by gares** [comment]
You are right @SkySkimmer , but how did you spot these?

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
I was looking at https://github.com/coq/coq/pull/19091#issuecomment-2233037785 and wondered if the problem was misclassification of Guarded.
It wasn't but Guarded still wasn't as precisely classified as it could be.

**Comment by gares** [comment]
Note that at some point `Undo`, for backward compatibility, was made to count only proof steps.
So if you classify guarded as Query it changes that for `Guarded`.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
only added changelog, full ci was green at https://gitlab.inria.fr/coq/coq/-/pipelines/1009037

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
