### PR TITLE
[doc] tell sphinxcontrib-bibtex which bibtex file to use

### PR DESCRIPTION
**Pull request by gares**
see https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html

### CODE REVIEW

**Comment by gares** [comment]
I've no clue what I'm doing and if CI will test against the version 2.0 of this utility.
Locally, it works for me.

**Comment by jfehrle** [comment]
What is the motivation?  You want the Bibliography look different somehow or is it because the Sphinx manual says `bibtex_bibfiles` should be configured?

**Comment by gares** [comment]
I get an error that this configuration line is required with a fresh installation of python. See the doc I linked.
Either we fix the README and suggest a pip3 line that installs the right version of the sphinxcontrib-bibtex, or we accept the user gets version 2 and add this config line.

**Comment by Zimmi48** [comment]
For now the only version we test in CI is 1.0.0, so I'm happy to merge this based on your local testing to fix compatibility with the latest version (and I will later take care of bumping the version in nixpkgs so that we start testing 2.0.0 in CI as well).

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Comment by Zimmi48** [comment]
We might want to require 2.0.0 as the minimal sphinxcontrib-bibtex version as it would allow re-enabling parallel builds (they were disabled last year in #11732 / #11796): see https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/develop/CHANGELOG.rst#200-12-december-2020.

**Pull request merged**
