### PR TITLE
Remove year in headers.

### PR DESCRIPTION
**Pull request by Zimmi48**
Requested by @SkySkimmer on Gitter.

FTR this is the commands that were used to create this PR:

```shell
# c-style headers
cp dev/header.c /tmp/
sed -i 's/2019/2020/' dev/header.c
dev/tools/change-header /tmp/header.c dev/header.c
# py-style headers
cp dev/header.py /tmp/
sed -i 's/2019/2020/' dev/header.py
dev/tools/change-header /tmp/header.py dev/header.py
# ml-style headers
cp dev/header.ml /tmp/
sed -i 's/2019/2020/' dev/header.ml
dev/tools/change-header /tmp/header.ml dev/header.ml
```

### CODE REVIEW

**Comment by Zimmi48** [comment]
Sorry for the infamous list of requested reviews. Maybe I should have opened this PR in draft mode (something to remember for next year).

**Comment by jfehrle** [comment]
Perhaps you could unselect most of the reviewers.

Should these files be updated, too?

```
kernel
float64.ml
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
float64.mli
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
vernac
declareObl.ml
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
declareObl.mli
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
obligations.ml
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
recLemmas.ml
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
recLemmas.mli
(*  v      *   INRIA, CNRS and contributors - Copyright 1999-2018       *)
```

**Review by jfehrle — APPROVED** [review]
Seems reasonable.  I did not read every line :-).

**Comment by ejgallego** [comment]
Actually the header update seems too noisy, maybe we should consider again using some header of the form `(c) 2001-current`

**Comment by herbelin** [comment]
In passing, I noticed that `numtok.ml` and `numtok.mli` were missing a header. This PR might be a good opportunity to add one. So are `byterun/coq_uint63_native.h`, `byterun/coq_uint63_emul.h`, `kernel/byterun/coq_float64.h` and the files in `theories/Floats` (which removes nothing to the wonderful achievement of having provided native floats and native integer!).

**Comment by SkySkimmer** [comment]
I don't know who should be assigned but I removed all the review requests as none seem appropriate.

**Comment by gares** [comment]
> Actually the header update seems too noisy, maybe we should consider again using some header of the form `(c) 2001-current`

I agree, I never understood why we are supposed to put the dates. Does anyone know?

**Comment by ppedrot** [comment]
> Does anyone know?

I thought that this was some Common Law legalese only valid in the American system, probably inherited from standard coding practices. This [general link](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/) seems to agree with me.

**Comment by ejgallego** [comment]
> I thought that this was some Common Law legalese only valid in the American system, probably inherited from standard coding practices. This [general link](http://www.contentious.com/2007/01/07/copyright-notice-is-the-year-really-necessary/) seems to agree with me.

I'd say for books of even served webpages the year may make sense indeed; as that is the publishing medium in the sense of that post "first published date".

For files that are published under public version control it seems to me that the commit metadata would fit this specification.

**Comment by jfehrle** [comment]
> I agree, I never understood why we are supposed to put the dates. Does anyone know?

Under US law, copyright does not last forever, so a specific end date is needed.  For example, the copyright on books expires 70 years after the author passes away.  Indeed, it is in the US constitution: "[The Congress shall have power] To promote the progress of science and useful arts, by securing for **limited** times to authors and inventors the exclusive right to their respective writings and discoveries."

I imagine it's not entirely different under other legal systems.

**Comment by gares** [comment]
My question is: why in *every* file!

I'm fine having a COPYRIGHT file with dates, but why on earth would one put the "first year of publication" on every page of a book!

**Comment by gares** [comment]
> I imagine it's not entirely different under other legal systems.

Indeed, same here.

**Comment by Zimmi48** [comment]
We are just following the standard FSF recommendation of putting a copyright header with authors, years and licensing on every file. The reason justifying this is so you can track the origin of a single file that someone would copy to another project.

But to each license, its own convention. For instance, the MPL 2.0 license is usually associated to a simpler file header with license information only (no authors, no years): https://www.mozilla.org/en-US/MPL/headers/
MIT license usually comes with no copyright header at all.

There are legal considerations as well: copyright headers are not legally required anymore since the latest international convention on copyright. However licenses such as LGPL strictly forbid altering or removing existing copyright headers... Let's talk about this in today's call.

**Comment by gares** [comment]
>  Let's talk about this in today's call.

Well we did not. I tried to grep https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html for "alter" and "remove" but I could not find it (also header shows up only once). Are you sure that clause is in LGPL v2.1?

**Comment by Zimmi48** [comment]
OK, my memory was a bit flawed. It turns out that the LGPL 2.1 has some conditions regarding such removal, but they are not super clear:
> keep intact all the notices that refer to this License

Copyright law might further prevent to remove such copyright headers, but someone would have to look into this (especially what French law has to say about this).

**Comment by Zimmi48** [comment]
I guess that there wouldn't be much risk moving to a fixed header such as:

```
##########################################################################
##         #   The Coq Proof Assistant / The Coq Development Team       ##
##  v      #         Copyright INRIA, CNRS and contributors             ##
## <O___,, # (see version control and CREDITS file for authors & dates) ##
##   \VV/  ###############################################################
##    //   #    This file is distributed under the terms of the         ##
##         #     GNU Lesser General Public License Version 2.1          ##
##         #     (see LICENSE file for the text of the license)         ##
##########################################################################
```

Copyright headers or copyright years are not actually a requirement anymore. I've just found [this page](http://geotoolsnews.blogspot.com/2016/07/copyright-headers-in-source-code-files.html) which confirms that copyright headers are purely informative, but further adds that files that are modified are "new work" and do not require preservation of copyright headers. This part seems more doubtful to me, but there is also not much risk in deciding to change or remove our copyright headers since the only affected organizations are our own institutions.

**Comment by ejgallego** [comment]
> I guess that there wouldn't be much risk moving to a fixed header

Indeed that header looks fine to me; the way I understand the situation [IANAL] is that what really matters is the date of "publication", in our sense this amounts to the time a change is pushed to the repos so indeed that would me more accurate.

Headers made sense when indeed there were no other forms of reliable metadata, such as when distributing with tar.gz archives. Signatures in git commits imply that the dates cannot be forged so easily.

**Comment by Zimmi48** [comment]
@coq/core: Should I change this PR to update the headers to something that looks like the example proposed [above](https://github.com/coq/coq/pull/11559#issuecomment-585628992) and does not have to be edited every year?

**Comment by herbelin** [comment]
As a PR, this is going to be outdated quickly. What about (regenerating and) merging the PR as is, delaying the question to possibly removing dates to a later time, or else, moving this PR to draft?

**Comment by Zimmi48** [comment]
Well, if I have to regenerate the PR, since there seemed to be a will to remove the dates, I'd appreciate knowing if there is any dissent to this option, so that I don't have to do work twice for nothing.

**Comment by Zimmi48** [comment]
The Coq developers at the Coq Call have approved the plan proposing the removal of the dates. I'll regenerate this PR soon.

**Comment by Zimmi48** [comment]
PR updated (sorry for the delay). I would appreciate if this is merged as soon as CI has passed and without waiting for the next conflict to occur.

**Comment by herbelin** [comment]
Ci passed. Is there an assignee ready, or could the first one "falling" on the PR do the merge?

**Comment by Zimmi48** [comment]
There was no volunteer so far.

**Comment by herbelin** [comment]
OK, doing it.

**Pull request merged**
