### PR TITLE
Simplify picking between uint63_63.ml and uint63_31.ml + makefile fixes

### PR DESCRIPTION
**Pull request by SkySkimmer**
- remove the architecture component (we don't do anything
  arch-specific so it was just a rewording of int_size)
- have configure tell the make build system about int_size instead of
  reimplementing cp

As a bonus, add the copyright header to uint63.mli.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Having architecture didn't bother me too much, it could be the case that someone wanted to implement even more optimized versions.

The new `OCAML_INT_SIZE` var will go away when we move to Dune, maybe you could add a comment?

Otherwise things look good.

**Comment by SkySkimmer** [comment]
>The new OCAML_INT_SIZE var will go away when we move to Dune, maybe you could add a comment?

The entire write_makefile part of configure would go away no? There's nothing specific to OCAML_INT_SIZE.

**Comment by ejgallego** [comment]
> The entire write_makefile part of configure would go away no? There's nothing specific to OCAML_INT_SIZE.

I am not sure if we still need to write some variables for Coq_Makefile, but indeed, you can leave things as they are now.

**Comment by ejgallego** [comment]
It seems that @gares is busy this week, so I may take this, but maybe he could have a look?

@vbgl @maximedenes do you expect arch to be important in the future?

**Comment by maximedenes** [comment]
> do you expect arch to be important in the future?

I think I'd prefer to not introduce too much arch-dependent stuff in principle. Of course, it could be the case in the future that we get extremely good optimizations on some architectures, but I doubt it.

**Review by vbgl — APPROVED** [review]

**Review by ejgallego — APPROVED** [review]

**Comment by vbgl** [comment]
Ping @maximedenes. I think this is good and ready. Thanks.

**Comment by maximedenes** [comment]
Was the MacOS failure spurious?

**Comment by vbgl** [comment]
Is the log lost?

**Comment by vbgl** [comment]
Rebased to get a fresh CI run. UniMath should fail as it is broken upstream.

**Comment by vbgl** [comment]
UniMath is alright, but the Windows job on gitlab failed:

> make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
chmod: ide/coqide_os_specific.ml: new permissions are r-xrwx---, not r-xr-x---
make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
chmod: kernel/uint63.ml: new permissions are r-xrwx---, not r-xr-x---
File "command line", line 1:
Error: Unbound module Gramlib
make[1]: *** [Makefile.build:790: gramlib/.pack/gramlib__Ploc.cmx] Error 2
make: *** [Makefile:176: submake] Error 2

**Comment by SkySkimmer** [comment]
Why's this breaking windows? I am very lost.
@MSoegtropIMC can you have a look at this?

**Comment by MSoegtropIMC** [comment]
> @MSoegtropIMC can you have a look at this?

The Coq build ends with:
```
File "command line", line 1:
Error: Unbound module Gramlib
make[1]: *** [Makefile.build:789: gramlib/.pack/gramlib__Ploc.cmx] Error 2
make: *** [Makefile:176: submake] Error 2
```
Not sure why this happens. If this doesn't tell you anything, I can make a local build of the branch and see what is going on.

**Comment by SkySkimmer** [comment]
It tells me nothing.
I'm trying setting VERBOSE, maybe it will be clearer. I'm not very optimistic about it though.

**Comment by MSoegtropIMC** [comment]
If I remember right, I have seen this once in a local build, but it was in an incremental build and it went away after doing a clean build. So it might be a makefile dependency issue which pops up randomly. I will compare the log file of a successfull build with this build.

**Comment by SkySkimmer** [comment]
It doesn't pop up randomly, there have been several failing pushes already.

**Comment by MSoegtropIMC** [comment]
> It doesn't pop up randomly, there have been several failing pushes already.

Well it could pop up randomly and changes improve the chances. I compared the build logs of your build and a recent passing build. what I see is that the builds massively diverge at

```
WRITE kernel/copcodes.ml
rm -f kernel/uint63.ml && cp kernel/uint63_63.ml kernel/uint63.ml && chmod -w kernel/uint63.ml
```
vs
```
WRITE kernel/uint63.ml
```
and that in the further course of events these lines are missing
```
OCAMLOPT  gramlib/.pack/gramlib.ml
OCAMLC    gramlib/.pack/gramlib.ml
OCAMLC    gramlib/.pack/gramlib__Ploc.mli
```
in your build before it needs gramlib. So I would say it is just by chance that gramlib is build in some builds before it is needed.

I attached the two log files.
[coq-local-make_log.fail.txt](https://github.com/coq/coq/files/3525066/coq-local-make_log.fail.txt)
[coq-local-make_log.pass.txt](https://github.com/coq/coq/files/3525069/coq-local-make_log.pass.txt)

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : do you agree with my assessment that this looks like a missing dependency in the makefile or should I start a local build for further investigation?

**Comment by SkySkimmer** [comment]
I don't know what dependency could be missing, especially something that's only a problem on windows.

**Comment by MSoegtropIMC** [comment]
> I don't know what dependency could be missing, especially something that's only a problem on windows.

As it looks gramlib is used before it is build which means whoever uses it should take care that it is build before. The order in which make processes files in absence of proper dependencies is unspecified and can change with unrelated changes in the makefile as in this case. It is not uncommon that things are build in the right order even without specifying required dependencies, and I would say this is what usually happens. The reason why the chosen unspecified order is different on Windows than on Linux may be due to different -j options or due to other arbitrary differences in the makefile. As far as I can see it is sheer luck that this works on other platforms.

Does the Linux build still use make or does already use dune? If so, I guess it is time to switch.

If you want I can fix this. It shouldn't be difficult (unless this is an issue in automatically generated dependency files).

**Comment by SkySkimmer** [comment]
the ci still tests make

If you can fix please do

Gaëtan Gilbert

**Comment by MSoegtropIMC** [comment]
> If you can fix please do

Ok, I will do a local build and see. It might take a day.

**Comment by MSoegtropIMC** [comment]
Unfortunately I cannot reproduce the failure locally, although all settings are identical except for path names. In the CI build one more commit from master was merged on top, but as far as I can see this shouldn't influence the outcome (changes only on CI make files). I did a comparison between log files. The issue in failing builds is that make starts building ml files before `OCAMLDEP  MLFILES MLIFILES` did run. I didn't find out as yet why this is, but this is obviously fatal. Interestingly the passing local build has two fatal errors in the make log, the failing build doesn't have:
```
Fatal error: exception Failure("gramlib/.pack/gramlib.ml : empty map file or parse error")
Fatal error: exception Failure("gramlib/.pack/gramlib.ml : empty map file or parse error")
```
Not sure where this comes from.

I attached a log comparison of the critical region. Maybe someone familiar with the phasing of generating ML files, running OCAMLDEP and building can have a quick look before I further investigate this.

[LocalPass_vs_GitlabFail.pdf](https://github.com/coq/coq/files/3528793/LocalPass_vs_GitlabFail.pdf)

Since I can't reproduce this locally, I would suggest to comment the runner cleanup in the gitlab.bat file so that I can have a look at the results and do some post failure experiments directly on the runner. Of cause one would have to be a bit careful with committing to this branch then, since one would have to cleanup the runner manually.

**Comment by vbgl** [comment]
IIUC, the Windows issue is not directly related to this PR: it is probably a makefile issue that is already present in master but revealed by this PR.

**Comment by MSoegtropIMC** [comment]
> IIUC, the Windows issue is not directly related to this PR: it is probably a makefile issue that is already present in master but revealed by this PR.

Yes, this is also my assumption. I would also say that it is more luck than systematic that it works on other platforms. Nevertheless it is interesting that some handling of uint63 files and the call to `OCAMLDEP MLFILES MLIFILES` is only a few lines appart in the log.

**Comment by SkySkimmer** [comment]
>Nevertheless it is interesting that some handling of uint63 files and the call to OCAMLDEP MLFILES MLIFILES is only a few lines appart in the log.

It's because when we do `open Uint63` ocamldep needs the file to already exist so that it will be found.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : since you are working on it, I assume that my analysis gave you some ideas on what might be going wrong. In case you need help, it would be useful if you comment in (https://github.com/coq/coq/blob/master/dev/ci/gitlab.bat) the two `RMDIR` in procedure `:CleanupFolders`. I can then log into the runners and run some make debug commands after the failure. But if you do it, you should ping me at least every 2nd CI run, so that I can cleanup the runners (or you do it yourself). The runners go out of disk beyond 3 no cleaned up runs (per runner).

> It's because when we do `open Uint63` ocamldep needs the file to already exist so that it will be found.

I just wanted to say that it is understandable that the changes trigger the assumed make file issue since they are timing wise so close in the make process.

**Comment by MSoegtropIMC** [comment]
I had a look at the logs with your latest changes. Now it tries to build something which needs gramlib even before:
```
echo " \
module Ploc    = Gramlib__Ploc \
module Plexing = Gramlib__Plexing \
module Gramext = Gramlib__Gramext \
module Grammar = Gramlib__Grammar" > gramlib/.pack/gramlib.ml
```
I attached a comparison (this is the complete log - so the failure is really early)
[GitlabFail_2_vs_3.pdf](https://github.com/coq/coq/files/3533519/GitlabFail_2_vs_3.pdf)

How shall we proceed? Do you do further investigations or shall I give it a try?

**Comment by SkySkimmer** [comment]
That's building a ml file so it can be seen by ocamldep and used later, it's part of gramlib but doesn't need it.

I have nothing further to try on my side.

TBH I don't know if it's worth the time to investigate further, this isn't an especially important PR so it could just wait until we drop make.

**Comment by MSoegtropIMC** [comment]
> it's part of gramlib but doesn't need it.

I would say the issue is that the generation of this file must be finished before dependency scanning runs and dependency scanning must run before building OCaml code starts.

I see if I can fix it over the weekend. Is it ok if I disable runner cleanup on your branch for further investigations? More or less this would mean that I hijack your branch over the weekend (I will take care to not mess it up ;-)

**Comment by SkySkimmer** [comment]
>I see if I can fix it over the weekend. Is it ok if I disable runner cleanup on your branch for further investigations? More or less this would mean that I hijack your branch over the weekend (I will take care to not mess it up ;-)

Do your worst ;)

**Comment by MSoegtropIMC** [comment]
Ok, here is the make file forensics. The culprit is this construct in `Makefile.build`:
```
gramlib/.pack/gramlib__%: COND_OPENFLAGS=-open Gramlib
```
I guess the expected behavior is that this sets `COND_OPENFLAGS` to `-open Gramlib` when building files with pattern `gramlib/.pack/gramlib__%`. But as it looks this also has an effect when building prerequisites of such files. E.g.

```
Updating goal targets....
 File 'gramlib/.pack/gramlib__Ploc.cmx' does not exist.
   File 'lib/loc.cmx' does not exist.
     File 'clib/exninfo.cmx' does not exist.
       File 'clib/store.cmx' does not exist.
         File 'clib/dyn.cmx' does not exist.
           File 'clib/int.cmx' does not exist.
             File 'clib/cMap.cmx' does not exist.
               File 'clib/cSig.cmi' does not exist.
              Must remake target 'clib/cSig.cmi'.
echo ""'OCAMLC    clib/cSig.mli'
"C:\\bin\\cygwin_coq64_skyskimmer_uint63-pick-file\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin/ocamlfind.exe" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence    -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I gramlib/.pack -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I tools -I tools/coqdoc -I plugins/omega -I plugins/micromega -I plugins/setoid_ring -I plugins/extraction -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -I user-contrib/Ltac2 -g  -open Gramlib -no-alias-deps -w -49 -c clib/cSig.mli
```
The build of `clib/cSig.cmi` fails because gamlib.cmx doesn't exist as yet. If `clib/cSig.cmi` is build directly, the `-open Gramlib` is not there:
```
$ make --debug -n clib/cSig.cmi
:
:
Updating goal targets....
 File 'clib/cSig.cmi' does not exist.
Must remake target 'clib/cSig.cmi'.
echo ""'OCAMLC    clib/cSig.mli'
"C:\\bin\\cygwin_coq64_skyskimmer_uint63-pick-file\\usr\\x86_64-w64-mingw32\\sys-root\\mingw\\bin/ocamlfind.exe" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-58   -safe-string -strict-sequence    -I coqpp -I config -I clib -I lib -I kernel -I kernel/byterun -I library -I engine -I pretyping -I interp -I proofs -I gramlib/.pack -I parsing -I printing -I tactics -I vernac -I stm -I toplevel -I tools -I tools/coqdoc -I plugins/omega -I plugins/micromega -I plugins/setoid_ring -I plugins/extraction -I plugins/cc -I plugins/funind -I plugins/firstorder -I plugins/derive -I plugins/rtauto -I plugins/nsatz -I plugins/syntax -I plugins/btauto -I plugins/ssrmatching -I plugins/ltac -I plugins/ssr -I user-contrib/Ltac2 -g   -c clib/cSig.mli
```
So as it looks the build of `clib/cSig.mli` inherits the `-open Gramlib` if it is build as dependency of `gramlib/.pack/gramlib__Ploc.cmx`.

I would say this means the creative trick:
```
gramlib/.pack/gramlib__%: COND_OPENFLAGS=-open Gramlib
```
is not usable. The same applies to other instances of this pattern. Of cause it might be that this is a bug in the version of make used on cygwin, which is `GNU Make 4.2.1`. What do you have on Linux?

One more note: I can reproduce the problem by asking make to clean build just one file:
```
make clean
make --debug=basic ./gramlib/.pack/gramlib__Ploc.cmx
```

I would suggest that I fix this by just replacing this one instance of this "variable assignment in dependencies" trick with a complete adjusted pattern rule. But I would say one should get rid of all such constructs soon (or get rid of make ...).

**Comment by MSoegtropIMC** [comment]
I found a way to fix the "set variable in dependencies" method. On has to add a generic rule to reset the variable for everything for which there is no more explicit rule:
```
# Reset COND_OPENFLAGS flags for all files for which it is not explicitly given
%: COND_OPENFLAGS=
```

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : i just saw your commit - this also looks like a good method. The reset method I outlined above would also work, but I would prefer your method since it is cleaner.

**Comment by SkySkimmer** [comment]
The windows build still fails with the same logs, but the `make ./gramlib/.pack/gramlib__Ploc.cmx` now works. I guess it wasn't the only problem x_x

**Comment by MSoegtropIMC** [comment]
> I guess it wasn't the only problem x_x

Having only one problem would be quite astonishing for a make file of this size ... I see what else I can find.

**Comment by MSoegtropIMC** [comment]
I did a `make clean` and `make -j 1 --debug=basic,makefile SHELL="/bin/bash -x"` on both the runner (where it fails) and locally (where it passes). The point in the log where it diverges is:

Runner:
```
+ chmod -w ide/coqide_os_specific.ml
chmod: ide/coqide_os_specific.ml: new permissions are r-xrwx---, not r-xr-x---
  Failed to remake target file 'ide/coqide_os_specific.ml'.
```

Local:
```
+ chmod -w ide/coqide_os_specific.ml
  Successfully remade target file 'ide/coqide_os_specific.ml'.
```

Apparently on cygwin this leads to an error:
```
$ echo bla > test.txt
$ chmod 770 test.txt
$ chmod -w test.txt
chmod: test.txt: new permissions are r-xrwx---, not r-xr-x---
```
Using `chmod a-w` instead works, so I changed this. The difference between runner and local is that the file has different permissions before the chmod, which might depend on the permissions of the containing folder on Windows, I need to further investigate this.

@skysimmer: can you please check if this is the same on Linux (that chmod 770 and then chmod -w is an error), or if this is a bug-feature in cygwin?

**Comment by SkySkimmer** [comment]
>@skysimmer: can you please check if this is the same on Linux (that chmod 770 and then chmod -w is an error), or if this is a bug-feature in cygwin?

it errors on linux as well, cygwin behaviour seems correct

**Comment by MSoegtropIMC** [comment]
The Windows build seems to be fine now. I re-enabled the runner clean up and manually cleaned up the two builds done without clean-up on the affected runners.

> it errors on linux as well, cygwin behaviour seems correct

This might mean that before the above change it did depend on the umask setting on Linux if a Coq build would succeed.

**Comment by SkySkimmer** [comment]
Thanks a lot for helping

Gaëtan Gilbert

**Comment by SkySkimmer** [comment]
Elpi failure is unrelated, anyone want to merge?

**Comment by ejgallego** [comment]
Looks good to me; I guess @gares should take care of this as the Make maintainer.

**Pull request merged**
