### PR TITLE
Print implicit arguments in types of references

### PR DESCRIPTION
**Pull request by SimonBoulier**
**Kind:** feature

This PR proposes to print the implicit arguments directly in the type of references for the commands `About` and `Search`.

For instance `About nil` now outputs:
```
nil : forall {A : Type}, list A

nil is template universe polymorphic on list.u0
Arguments nil {A}%type_scope
Expands to: Constructor Coq.Init.Datatypes.nil
```

And `Search list` now outputs:
```
nil: forall {A : Type}, list A
length: forall [A : Type], list A -> nat
cons: forall {A : Type}, A -> list A -> list A
app: forall [A : Type], list A -> list A -> list A
list_ind:
  forall [A : Type] (P : list A -> Prop),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
list_sind:
  forall [A : Type] (P : list A -> SProp),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
list_rect:
  forall [A : Type] (P : list A -> Type),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
list_rec:
  forall [A : Type] (P : list A -> Set),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
```
The change also affect `Print Implicit`, `SearchHead`, `SeachRewrite` and `SearchPattern` but has no effect on commands `Print` and `Check`.

The goal is to understand quicker which arguments are implicit (especially for `Search`).

When several list of implicit arguments are available, the stronger is chosen (the function `select_stronger_impargs` was already used several times in `constrextern.ml`).
For instance, after `Arguments nil {_}, _`, `About nil` outputs:
```
nil : forall {A : Type}, list A

nil is template universe polymorphic on list.u0
Arguments nil {A}%type_scope, _
Expands to: Constructor Coq.Init.Datatypes.nil
```

This is ready for review modulo doc/changelog.

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by herbelin — COMMENTED** [review]
This is a cool feature!

I have a question about automatic implicit arguments hidden behind a constant, as, say in:
```coq
Definition K B := forall A, A -> B -> A.
Set Implicit Arguments.
Axiom f : forall B, K B.
About f.
(*
f : forall B : Type, K B
Expanded type for implicit arguments
f : forall B A : Type, A -> B -> A
*)
```
Are the implicit arguments added only on the expanded version?

Regarding `Search`, I would suggest that it also indicates something when what it prints is not exhaustive, e.g. an extra message like `(use "About" for full details on implicit arguments)`, or maybe just a `(*)` and an initial message `(*): use "About" for full information on implicit arguments`.

**Comment by SimonBoulier** [comment]
Thanks for your comment @herbelin.
- For `f`, the output of `About` is:
```
f : forall [B : Type], K B

f is not universe polymorphic
Expanded type for implicit arguments
f : forall [B A : Type], A -> B -> A

Arguments f [B]%type_scope [A]
Expands to: Constant toto.f
```
and for Search:
```
f: forall [B : Type], K B
```
This seems reasonable. Is it okay for you?

- Good idea for the message, I added it at the end of the results to keep as space as possible, and without star, but this seems enough.
E.g.
 ```
nil: forall {A : Type}, list A
length: forall [A : Type], list A -> nat
cons: forall {A : Type}, A -> list A -> list A
app: forall [A : Type], list A -> list A -> list A
list_ind:
  forall [A : Type] (P : list A -> Prop),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
list_sind:
  forall [A : Type] (P : list A -> SProp),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
list_rect:
  forall [A : Type] (P : list A -> Type),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
list_rec:
  forall [A : Type] (P : list A -> Set),
  P nil ->
  (forall (a : A) (l : list A), P l -> P (a :: l)%list) -> forall l : list A, P l
(use "About" for full details on implicit arguments)
```

**Comment by SimonBoulier** [comment]
Would you add something in the manual? This does not seems necessary to me...

**Comment by herbelin** [comment]
Yes, this looks reasonable. As far as I'm concerned, I would not add something to the manual.

I propose to assign, but first leaving time for comments.

**Comment by SimonBoulier** [comment]
Ok thanks.

**Comment by herbelin** [comment]
@SimonBoulier: if you have some time available, the test-suite apparently needs some update.

**Comment by herbelin** [comment]
CI seems happy. Merging tomorrow.

**Review by herbelin — APPROVED** [review]

**Pull request merged**
