### PR TITLE
[type classes] Simplify cl_context

### LINKED ISSUE #13117: Inconsistency in implicit generalization for class defined with Class vs Record + Existing Class
~~~coq
Class A := {}.

Class B (x:A) := {}.

Fail Definition foo a `{B a} := 0.

Record C (x:A) := {}.
Existing Class C.

Definition bar a `{C a} := 0.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by herbelin** [comment]
Are there parts of the PR which you'd like we specially review?

You also want to add a reference to #13117 I guess.

**Comment by SkySkimmer** [comment]
>Are there parts of the PR which you'd like we specially review?

Nothing specific, just have a look

**Review by ppedrot — APPROVED** [review]
Code change is fine but the fix is going to be hard to backport, if this is desired.

**Comment by SkySkimmer** [comment]
Wouldn't it work to just backport the 2 middle commits? There's no need to remove the now-unused data from typeclasses in a backport.

**Comment by ppedrot** [comment]
Probably but it's not clear that the rebase is going to be painless. Anyways, I am not a release manager so I don't really care personally.

**Comment by ppedrot** [comment]
Let's merge, the CI failure is spurious.

**Comment by Zimmi48** [comment]
Besides, being hard to backport, it is not clear to me that it would be reasonable to ship this kind of behavior change in a patch-level release...

**Pull request merged**
