### PR TITLE
Update the CI branch for Equations.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is pending on the creation of said branch by @mattam82 as soon as he has access to a computer.

### CODE REVIEW

**Comment by mattam82** [comment]
Ok, now on my Equations repository master is for 8.9+alpha, 8.8 for 8.8, 8.7 for 8.7 and 8.6 for 8.6. @cmangin that's fine right?
I'll update the opam equations.8.6.dev package

**Comment by mattam82** [comment]
I've reverted the revert of Equations/#55 on the master branch

**Comment by Zimmi48** [comment]
Passed here https://travis-ci.org/Zimmi48/coq/jobs/366215213

**Review by SkySkimmer — APPROVED** [review]
I'm going to merge this as secondary maintainer since it fixes CI.

**Comment by ejgallego** [comment]
Sorry, I was busy with other stuff and missed this; thanks for taking over.

**Pull request merged**
