### PR TITLE
Do not apply discriminated unfold hints on arbitrary goals.

### LINKED ISSUE #14874: Exponential blowup with Hint Unfold
#### Description of the problem

I'm running into performance issues with Hint Unfold.  The following example shows `eauto 10` going from 0.01 second to 1 second by adding one `Hint Unfold`, and to 1 minute by adding another hint:

```coq
Fixpoint exp (P: Prop) n :=
  match n with
  | O => P
  | S x => exp P x /\ exp P x
  end.

Create HintDb test discriminated.

Goal exp False 12.
  unfold exp.

  Time eauto 10.

  Hint Unfold plus : test.
  Time eauto 10 with test.

  Hint Unfold minus : test.
  Time eauto 10 with test.
```

The problem is that the first eauto exits immediately, whereas the second one explores an exponential number of permutations of "unfold plus".  Here's part of the output of `debug eauto`:

```
Debug: 1 depth=5
Debug: 1.1 depth=4 unfold Nat.sub
Debug: 1.1.1 depth=3 unfold Nat.sub
Debug: 1.1.1.1 depth=2 unfold Nat.sub
Debug: 1.1.1.1.1 depth=1 unfold Nat.sub
Debug: 1.1.1.1.1.1 depth=0 unfold Nat.sub
Debug: 1.1.1.1.1.2 depth=0 unfold Nat.add
Debug: 1.1.1.1.1.3 depth=0 simple apply conj
Debug: 1.1.1.1.2 depth=1 unfold Nat.add
Debug: 1.1.1.1.2.1 depth=0 unfold Nat.sub
Debug: 1.1.1.1.2.2 depth=0 unfold Nat.add
Debug: 1.1.1.1.2.3 depth=0 simple apply conj
Debug: 1.1.1.1.3 depth=1 simple apply conj
Debug: 1.1.1.1.3.1 depth=0 unfold Nat.sub
Debug: 1.1.1.1.3.2 depth=0 unfold Nat.add
Debug: 1.1.1.1.3.3 depth=0 simple apply conj
Debug: 1.1.1.2 depth=2 unfold Nat.add
Debug: 1.1.1.2.1 depth=1 unfold Nat.sub
Debug: 1.1.1.2.1.1 depth=0 unfold Nat.sub
Debug: 1.1.1.2.1.2 depth=0 unfold Nat.add
Debug: 1.1.1.2.1.3 depth=0 simple apply conj
Debug: 1.1.1.2.2 depth=1 unfold Nat.add
Debug: 1.1.1.2.2.1 depth=0 unfold Nat.sub
Debug: 1.1.1.2.2.2 depth=0 unfold Nat.add
Debug: 1.1.1.2.2.3 depth=0 simple apply conj
Debug: 1.1.1.2.3 depth=1 simple apply conj
Debug: 1.1.1.2.3.1 depth=0 unfold Nat.sub
Debug: 1.1.1.2.3.2 depth=0 unfold Nat.add
Debug: 1.1.1.2.3.3 depth=0 simple apply conj
Debug: 1.1.1.3 depth=2 simple apply conj
Debug: 1.1.1.3.1 depth=1 unfold Nat.sub
Debug: 1.1.1.3.1.1 depth=0 unfold Nat.sub
Debug: 1.1.1.3.1.2 depth=0 unfold Nat.add
Debug: 1.1.1.3.1.3 depth=0 simple apply conj
```

Am I doing something wrong?

#### Coq Version

A recent master: 598628f437
Also in 8.12.

### PR DESCRIPTION
**Pull request by ppedrot**
The current behaviour was to indiscriminately try to apply on any goal unfold hints for transparent constants from discriminated databases, since they were not indexed by the head constant. In particular, this might have unfolded the constant even if it was at the head of the goal, contrarily to what the documentation claimed.

I think it was written this way out of fear of the dnet pattern algorithm. In discriminated mode, transparent constants are considered to match everything, but maybe the author of the code was confused by the complexity of the dnet implementation.

This patch changes the semantics of auto tactics in fringe cases, and should be mostly backwards compatible.

Fixes #14874: Exponential blowup with Hint Unfold.

### CODE REVIEW

**Comment by ppedrot** [comment]
Here is a minimal example of a fringe case.
```
Create HintDb foo discriminated.

Definition F (n : nat) := n.

Inductive Pred : nat -> Prop := pred : forall n, Pred (S n).

#[local]
Hint Unfold F : foo.

#[local]
Hint Resolve pred : foo.

Print HintDb foo.

Goal forall n, Pred (F (S n)).
Proof.
intros n.
solve [ auto with foo ]. (* with this PR auto leaves the goal unchanged and this line fails *)
Qed.
```

**Comment by ppedrot** [comment]
CI shows that only HoTT, math-classes and (by transitivity) corn are broken. It seems quite a small change in the end thus, so maybe it's worth pursueing and writing overlays. @mattam82 what do you think?

**Comment by ppedrot** [comment]
Let's close for the time being, I'll reopen after the deadzone known as summer.

**Comment by ppedrot** [comment]
Why are there CI failures in [ml-api](https://gitlab.com/coq/coq/-/jobs/1584884987) and [refman](https://gitlab.com/coq/coq/-/jobs/1584884980)? In the first case I don't see how it's related to this PR and in the second I don't even see any outstanding error.

**Comment by ppedrot** [comment]
All overlays were merged, so this is ready to go as-is and needs an assignee.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Maybe we could have a test for this?

**Comment by ppedrot** [comment]
Do you want a positive or a negative test?

**Comment by SkySkimmer** [comment]
Why not both?

**Comment by SkySkimmer** [comment]
ping

**Comment by ppedrot** [comment]
@SkySkimmer test added.

**Comment by SkySkimmer** [comment]
This test passes in master, shouldn't we test the changed behaviour?

**Comment by ppedrot** [comment]
You're right, let me add another discriminating test.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
