### PR TITLE
Revert #6651: Use r.(p) syntax to print primitive projections

### LINKED ISSUE #6764: Printing Notation regressed compared to 8.7
#### Version

git master

#### Operating system
Linux

#### Description of the problem

In the `gen_proofmode` branch of https://gitlab.mpi-sws.org/FP/iris-coq/, printing notations regressed compared to Coq 8.7. This is visible for example in `theories/bi/update.v`: What used to be printed as `(|==> P) ⊢ P` is now printed as `(sbi_bi PROP).(bi_entails) (|==> P)%I P`.

The relevant notation `⊢` is defined in `theories/bi/interface.v`:
```
Notation "P ⊢ Q" := (bi_entails P%I Q%I) : stdpp_scope.
```
`bi_entails` is a primitive projection, so #6651 could be related. Or maybe this is caused by one of the recent scope handling changes?

### PR DESCRIPTION
**Pull request by maximedenes**
Fixes #6764: Printing Notation regressed compared to 8.7

### CODE REVIEW

**Comment by ppedrot** [comment]
Why master? There is still a hope of a proper fix, isn't it?

**Comment by maximedenes** [comment]
> Why master? There is still a hope of a proper fix, isn't it?

I've exhausted the time I could spend on it, but if someone has a fix now, it is still not too late to push it to master indeed. But there's little point in keeping this in master forever if nobody is making progress on cleaning up the primitive projection / compatibility constants mess. Is anybody working on it?

**Comment by ppedrot** [comment]
@ejgallego The patch doesn't break the compilation, it just makes Iris essentially not usable because the printing is all messed up. I don't know whether this qualifies as unstability...

**Comment by ejgallego** [comment]
> @ejgallego The patch doesn't break the compilation, it just makes Iris essentially not usable because the printing is all messed up. I don't know whether this qualifies as unstability...

This qualifies 100%, CI for master has a lot of testing disabled. We either drop Iris from the CI or do the testing properly.

**Comment by gares** [comment]
> It is easy to revert the revert if someone has a fix.

I agree with @ejgallego wrt the severity, I don't agree with the fact that it is an easy revert. The API changes as CI shows, and if we re-revert then it will change again. I'd like an estimation of the cost of the proper fix of #6764  by @maximedenes

**Comment by ejgallego** [comment]
> I don't agree with the fact that it is an easy revert. The API changes as CI shows,

Oh indeed I has assumed that the revert would have tried to be a bit more cautions API-wise [if just to save effort] as this is a printing issue.

Anyways this is the kind of issue thankfully we are facing less and less as the CI testing becomes more complete, we didn't properly test the original PR by lack of test cases, but this should now be fixed. It would be also good if we could add some test case to the test suite extracted from the Iris one.

A big black hole in our testing is performance tho; hopefully we can fix it some day.

**Comment by maximedenes** [comment]
> Oh indeed I has assumed that the revert would have tried to be a bit more cautions API-wise

Initially, I thought we could just unplug the production of `GProj` nodes, while keeping the same AST type. However, it would be an intermediate state that should not stay as it is, and since I'm not aware of any work done to do the proper clean-up, I don't favor that option anymore.

If, on the other hand, someone commits to doing the clean-up, we could go for it.

**Comment by SkySkimmer** [comment]
Do we actually know what the proper fix is? Should `Notation foo := (p r)` also match the primitive projection `r.(p)`?

**Comment by RalfJung** [comment]
> Should Notation foo := (p r) also match the primitive projection r.(p)?

That would be the backwards compatible thing to do. Given that `p r` parses as `r.(p)` when used as a term, it seems rather surprising that the same does not happen when it is used as notation.

**Comment by ppedrot** [comment]
IIRC, the problem is that desugaring of primitive projections happens at pretyping, which happens after translation notation.

**Comment by ejgallego** [comment]
I am not sure if this should be considered pretyper or interp stuff.

If the second case applies, then @herbelin (or I with Hugo's blessings) could be the assignee.

**Comment by ejgallego** [comment]
Anyways for a start the CI looks very very red.

**Comment by maximedenes** [comment]
The test suite fails on `UnivBinders` it seems...

**Comment by herbelin** [comment]
> I am not sure if this should be considered pretyper or interp stuff.
> If the second case applies, then @herbelin (or I with Hugo's blessings) could be the assignee.

It can probably be both. Please assign if you wish.

> Do we actually know what the proper fix is? Should Notation foo := (p r) also match the primitive projection r.(p)?

> Given that p r parses as r.(p) when used as a term, it seems rather surprising that the same does not happen when it is used as notation.

I'm unsure to be aware of all the changes made in the last months, but If we succeed that for a given type, there is no need to have both a "compatibility" and a regular representation of the projection, the "fix" is not needed any more, right? In all cases, both `(p r)` and `r.(p)` will be possible notations for the corresponding projection.

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
The failure of `UnivBinders.out` is probably the `p.(punwrap)` to be changed in `punwrap p`. As for elpi, @gares, do we need synchronization and if yes what are your constraints? Otherwise, I shall merge (in master) a few hours after `UnivBinders.v` is fixed.

**Comment by Zimmi48** [comment]
Note to @silene: backporting this to v8.9 will require updating the hash of elpi.

**Comment by maximedenes** [comment]
> wrt elpi, it is for sure the constructor being removed. The patch is simple, so if this gets merged in v8.9 I can just make a v8.9 branch on elpi, do the fix myself, and let you point ci there.

@gares An elpi fix would be welcome, indeed.

**Comment by silene** [comment]
I am a bit lost. Is that the pull request without which Iris is unusable with 8.9? Or is that something else? I am trying to understand the blocker tag here.

**Comment by maximedenes** [comment]
> I am a bit lost. Is that the pull request without which Iris is unusable with 8.9?

Yes.

**Comment by maximedenes** [comment]
@gares ping

**Comment by maximedenes** [comment]
@herbelin should be good now, modulo CI

**Comment by herbelin** [comment]
Question is passing (before merging): this PR has an overlay. It will have no role once merged, so do I remove it before merging?

**Comment by gares** [comment]
The overlay automatically becomes inactive once the PR is merged.
The files are then removed from time to time...
So please go ahead.

**Comment by herbelin** [comment]
> The overlay automatically becomes inactive once the PR is merged.
The files are then removed from time to time...

Yes, but that's maybe non optimal to commit them and to remove them afterwards.

**Comment by Zimmi48** [comment]
It was argued that this serves some historical documentation purpose. I don't have a strong opinion on this but I suppose it's only limited noise since it's contained in a very specific folder.

**Comment by herbelin** [comment]
> It was argued that this serves some historical documentation purpose.

In this case, I did it wrong by removing from PRs those of my overlays which were merged upstream.

**Comment by maximedenes** [comment]
> In this case, I did it wrong by removing from PRs those of my overlays which were merged upstream.

That's not really wrong, IMHO each developer should do as they like for this matter.

**Comment by Zimmi48** [comment]
When I said "it was argued", I didn't mean that I did. I really think this is not an important matter but personally, I leave the overlays around.

**Comment by ejgallego** [comment]
Yeah I feel like there is not a lot to see here, these a "bureaucratic" files that as of today we have no better way to handle.

**Comment by silene** [comment]
@gares 
> wrt elpi, it is for sure the constructor being removed. The patch is simple, so if this gets merged in v8.9 I can just make a v8.9 branch on elpi, do the fix myself, and let you point ci there.

Could you do so? Otherwise, it seems I would also have to backport #8552, right?

**Comment by Zimmi48** [comment]
@silene Indeed, these are the only two options. If you go for the second route, don't forget that you have to run a pipeline with `SKIP_DOCKER=false`.

**Comment by Zimmi48** [comment]
@silene Enrico has created such branch but it still requires to backport #8552 (see discussion in #6764).

**Pull request merged**
