### PR TITLE
Clean up scheme computation in the induction tactic

### PR DESCRIPTION
**Pull request by ppedrot**
Yet another PR from my cellar. We statically enforce some hidden invariants in `induction`.

### CODE REVIEW

**Comment by herbelin** [comment]
Why not but I also have an ongoing PR (#12996) on reworking schemes which would probably overlap with most of what you did.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
>Why not but I also have an ongoing PR (#12996) on reworking schemes which would probably overlap with most of what you did.

Because this one has passing CI so can be merged.

**Comment by herbelin** [comment]
> Because this one has passing CI so can be merged.

Sure, un tien vaut mieux que deux tu l'auras! I just wanted to express that depending on the outcome of #12996, the content of this PR might be of limited length in time.

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
