### PR TITLE
Notation wish #17845: add support for notations with recursive binders involving "let" and "match"

### LINKED ISSUE #17845: Coq does not seem to provide a way to adjust recursive binders
#### Description of the problem

```coq
Notation "'uncurryλ' x1 .. xn => body"
  := (fun '(pair .. (pair tt x1) .. xn) => body)
       (only parsing, at level 200, x1 binder, xn binder, right associativity).
(* Error: Syntax error: ',' or ')' or '|' expected after [pattern level 200] (in [pattern]).*)
```

Is there some way to make this work without factoring the binders into a separate custom entry?  (I want to be able to make use of the binders in multiple recursive patterns.)

The actual example that I'm working on:
I'd like to be able to replace https://github.com/JasonGross/neural-net-coq-interp/blob/532199de278ac0de496f1e16bc7eda0d901a5e7e/theories/Torch/Einsum.v#L114-L116
with `(fun '(pair .. (pair tt k1) .. k_) => (`

cc @herbelin ?

#### Coq Version

8.17

### PR DESCRIPTION
**Pull request by herbelin**
This seems to work for parsing.

Recognizing instances of the recursive pattern of the notations for printing is more aleatory: it interacts with pattern-matching decompilation (done earlier in detyping) in ways difficult to control.

Fixes #17845

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
I would say that even if printing does not work symmetrically due to the difficult-to-control interaction with pattern-matching decompilation, I think that this is worth to go.

Note: I added a word on the changelog to say that the support is for parsing ("not for printing" implicitly implied). Not rerunning full ci though, as it is already green.

**Comment by herbelin** [comment]
@coqbot run full ci

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
Rerunning CI just to be safe before merging.

@coqbot run full ci

**Comment by proux01** [comment]
@herbelin sorry it appears I completely forget that one. Fixed the compilation issue do tu my delay.

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coqbot merge now

**Comment by proux01** [comment]
@herbelin sorry again for the delay here, I apparently just forgot to merge, feel free to "harass" me in such cases.

**Pull request merged**
