### PR TITLE
Fix #13283: improved error on `clear implicit` flag

### LINKED ISSUE #13283: Improve error message when "Arguments ... : clear implicit" is used with implicit annotations.
Sometimes, one wants to change which arguments of a constant are implicit which are not.

I just found out about the "rename" command because I wanted `clear implicit` to behave like `rename`. Before I always called Arguments twice: once to clear implicits, and once to set new.

Maybe one could improve the error message here:

````
Require Import Fin.

Fail Arguments Fin.of_nat_lt _ {_} _: clear implicits.
Arguments Fin.of_nat_lt _ {_} _: rename.
````

The Error is: `The "clear implicits" flag is incompatible with implicit annotations`
It could be: `The "clear implicits" flag is incompatible with implicit annotations. Use "rename" flag instead`

Alternatively, one could allow the failing command from above, so that `clear implicit` behaves like `rename`.

### PR DESCRIPTION
**Pull request by fakusb**
**Kind:** documentation.

Fixes / closes #13283

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please use a nicer commit message (the pr title would work fine)

**Comment by Zimmi48** [comment]
Thanks a lot! If you don't mind, I think that it would also be worth adding this error message to the doc (in `doc/sphinx/language/extensions/arguments-command.rst`).

**Comment by fakusb** [comment]
I added also a few more error messages to the documentation, but as they are self-explanatory, i did not document them further.

Can I render the sphinx-doc locally to check that my addition is correct without compiling all of coq? I did not test the additions.

**Comment by Zimmi48** [comment]
Thanks!

To build the doc without compiling all of Coq, you can use `SPHINXWARNERROR=0 QUICK=1 make refman-html`. But I haven't used this in a long while because I prefer to use `dune` and we haven't built anything equivalent to `QUICK` for `dune` yet. CI will also soon tell us if it builds and give a link to an HTML artifact.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Our linter is complaining because of some trailing whitespace on an empty line. You shouldn't see this kind of errors if you have the `pre-commit` hook installed. See https://github.com/coq/coq/blob/master/CONTRIBUTING.md#linter-failures

**Comment by jfehrle** [comment]
> Can I render the sphinx-doc locally to check that my addition is correct without compiling all of coq?

Just out of curiosity, how long does it take you to compile Coq?  On my system, it takes 2.5 minutes for `make -j 12` (after a `make clean`) and 1.5 minutes to run Sphinx.  I'm on Windows/WSL2 with a 6 core processor.

**Comment by jfehrle** [comment]
> you can use `SPHINXWARNERROR=0 QUICK=1 make refman-html`

Interesting.  I had no idea bash would accept this, I thought the `make` had to be first.

**Comment by Zimmi48** [comment]
> > Can I render the sphinx-doc locally to check that my addition is correct without compiling all of coq?
> 
> Just out of curiosity, how long does it take you to compile Coq? On my system, it takes 2.5 minutes for `make -j 12` (after a `make clean`) and 1.5 minutes to run Sphinx. I'm on Windows/WSL2 with a 6 core processor.

I can't really tell because I'm using `dune`, which has a cache, so it never recompiles everything, even if I'm cleaning everything first. But let see: `dune build coq.install` took 4.5 minutes with 4 jobs most of the time and `dune build @refman-html` took 1m45s (with no parallel job).

**Comment by fakusb** [comment]
I squashed my two commits and removed the trailing whitespace. (and set up my build environment on this machine)


> > Can I render the sphinx-doc locally to check that my addition is correct without compiling all of coq?
> 
> Just out of curiosity, how long does it take you to compile Coq? On my system, it takes 2.5 minutes for `make -j 12` (after a `make clean`) and 1.5 minutes to run Sphinx. I'm on Windows/WSL2 with a 6 core processor.

`make -j8` 2 minutes, WSL2 + 4 core processor , but I did not have set up the opam etc. to be able to build before. Also, I think that I used flambda before `while` compiling coq, maybe that was a bad idea to get fast in-development-compile-times.

**Comment by Zimmi48** [comment]
This is quite straightforward, so I'll take this PR and merge it by the end of the day.

**Comment by Zimmi48** [comment]
@coqbot: merge now

**Comment by jfehrle** [comment]
By the way, @fakusb, how well does WSL2 work with XWindows for you?  I'm using `vcXsrv`. I see my IDE process die several time a day.  I tend to think it's due to limitations of `vcXsrv` though it could be from my IDE (IntelliJ IDEA, a commercial product).  What has been your experience?

**Comment by fakusb** [comment]
@jfehrle  I use vscoq after fixing a few issues there, so no xserver in day-to-day use. The one time I tried CoqIde to test it's behaviour one something, i did so with Xming.

**Pull request merged**
