### PR TITLE
universes_of_constr don't include universes of monomorphic constants

### PR DESCRIPTION
**Pull request by SkySkimmer**
Apparently it was not useful. I don't remember what I was thinking
when I added it.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I was complaining against this in another PR I cannot find again, so I fully support this patch. Hopefully it doesn't break anything.

**Comment by ppedrot** [comment]
That was #891.

**Comment by ppedrot** [comment]
It seems Equations and elpi need an overlay.

**Comment by SkySkimmer** [comment]
See https://github.com/mattam82/Coq-Equations/pull/128 https://github.com/LPCIC/coq-elpi/pull/28

**Comment by ppedrot** [comment]
@mattam82 Are you fine with this PR?

**Review by maximedenes — CHANGES_REQUESTED** [review]
This kind of changes can't come with a documentation change/addition in the `.mli` files.

**Comment by maximedenes** [comment]
> You mean "should come" right?

I meant can't come without :) Sorry!

**Review by mattam82 — APPROVED** [review]
Indeed, no need.

**Comment by SkySkimmer** [comment]
Not sure what doc change you want, I changed it a bit.

**Comment by ppedrot** [comment]
Are you happy with this @maximedenes?

**Review by maximedenes — APPROVED** [review]
I'm far from satisfied with the documentation of this API in general, but for the scope of this PR, let's say it's ok.

**Pull request merged**
