### PR TITLE
Master+remove api leaks

### PR DESCRIPTION
**Pull request by ghost**
Like PR #808, this PR eliminates `Prelude` module from the API.

Unlike PR #808, this PR:
- eliminates all API-leaks
- does not throw away any useful information that was already present in the API
  (e.g. it does not "undeprecate" API elements that were already marked as `@@ocaml.deprecated`)
- does not include `open Constr` into plugins (plugins did not and do not use `Constr` module)
- reordering (and just reordering) is done in a separate commit. This commit is unreviewable, but has no other ambitions just to reorder API modules and eliminate `Prelude`.

Here, "linking order" was a used as a hint concerning the proper order of modules (so that we can get rid of `Prelude`). However, the "linking order" gives no direct clues concerning proper placement of modules in the `intf` directory. In addition to that, we deviate from the "linking order" in these cases:
- `Entries`
- `Retroknowledge`
- `Tacmach`

There, following blindly the "linking order" is not possible.

### CODE REVIEW

**Comment by matejkosik** [comment]
Commit `	cd80fcc` is a necessary condition that enables us to remove type equations.

**Comment by matejkosik** [comment]
TODO: make sure that we compile `API.mli`, all API-leaks are automatically detected and reported by the Ocaml compiler.

**Comment by matejkosik** [comment]
TODO: add [a note](https://github.com/coq/coq/blob/aa207188f56a608fca04ad3bf3c3a4e98381750d/API/API.mli#L9-L21) about the (non-random) order of modules.

**Comment by matejkosik** [comment]
@ejgallego Can I steal [your note](https://github.com/coq/coq/blob/aa207188f56a608fca04ad3bf3c3a4e98381750d/API/API.mli#L9-L21)?

**Comment by ejgallego** [comment]
Well, I still prefer my approach of #808 + #905 if only for clarity. Here:

- API.ml still is declaring things that should not do, like entries. [this is a serious problem]
- All the `.mlp` files are using symbols incorrectly qualified. [this is a serious problem]
- Commentary is better in #808 + #905.
- The deprecation happening is here is not correct as it implies that symbols not deprecated in Coq are deprecated in the API (meaning for instance that you cannot cut and paste).
- The PR doesn't compile for me. (fatal warnings, which raise concerns about the structure).
- On the positive side, this PR is a bit more careful than I was with projecting type aliases from the underlying interface code, but that is at most a few lines of difference.

Regarding @matejkosik comments about #808 + #905 I think all of them are not correct, for the reasons given above in particular the `open Constr` is needed if you want to avoid warnings.
So given that this PR needs some amount of work I vote to move with the other set, but of course I am conflicted here.

**Comment by matejkosik** [comment]
@ejgallego The points you raise:
- API.ml still is declaring things that should not do, like entries
- All the .mlp files are using symbols incorrectly qualified
- commentary is better in #808 + #905
- the deprecation happening is here is not correct as it implies that symbols not deprecated in Coq are deprecated in the API (meaning for instance that you cannot cut and paste from interfaces)

are (honestly) interesting, but they are orthogonal to the problem this PR addresses. The title of this PR reads "remove API leaks" and I am intentionally not trying to do anything else here as I believe that would disqualify this PR.

I am happy to include [your comment](https://github.com/coq/coq/blob/aa207188f56a608fca04ad3bf3c3a4e98381750d/API/API.mli#L9-L21), though.

**Comment by matejkosik** [comment]
@maximedenes @gares Does this PR look reasonable to you? Can the orthogonal issues raised by @ejgallego be addressed separately (by different PRs)?

**Comment by maximedenes** [comment]
@ejgallego Is there something in this PR that looks wrong as opposed to not addressed yet? @matejkosik is basically trying to separate the independent changes that were introduced in #808 and #905. So if the changes in this PR go in the right direction, I'd suggest Matej then picks the rest of the changes from #808 and #905 in a second step.

**Review by gares — APPROVED** [review]
I can't check every single line, but what I see seems to address the leak issue (and consequently re-order the sub modules of API in a consistent way).

I don't understand the top_printers.ml patch, but this is minor IMHO.

**Comment by matejkosik** [comment]
> I don't understand the top_printers.ml patch, but this is minor IMHO.

That is an inconvenient consequence of removing the type equations from the API.

We have to provide a value of type `API.Environ.env` to `Ltac_plugin.Pptactic.pr_glob_tactic` function. We cannot provide a value of type `Environ.env`. :-/

**Comment by ejgallego** [comment]
> @ejgallego Is there something in this PR that looks wrong as opposed to not addressed yet?

I suggest you compare both versions of `API.ml` and `API.mli`.

> is basically trying to separate the independent changes that were introduced in #808 and #905

This is not the case, the granularity of both PRs look fine to me.

> I'd suggest Matej then picks the rest of the changes from #808 and #905 in a second step.

So again you are suggesting we keep duplicating work #905 is ready and it was so before this PR, if you go that route, then he will have to duplicate the fixes and documentation that is already present in those commits.

Also, @matejkosik deviated from the proposal we did by mail in that he was supposed to base the equations changes in #808, the current logical order of this PR is meaningless in the removal of `Grammar_API` is incorrect as the `mlp` files are still wrong, it is also meaningless as much as the API is still leaking so indeed you can place aliases in an arbitrary order as long as you are lucky with type kinding.

**Comment by maximedenes** [comment]
> I suggest you compare both versions of API.ml and API.mli.

This will also include what is not addressed yet, so it doesn't answer my question.

> This is not the case, the granularity of both PRs look fine to me.

That doesn't look clear to me. An example is the `Term` -> `Constr` change in some plugins in #808. Was it impossible to separate it?

> So again you are suggesting we keep duplicating work #905 is ready and it was so before this PR, if you go that route, then he will have to duplicate the fixes and documentation that is already present in those commits.

I'm not suggesting anything, you guys can organize your work as you like, I'm just trying to make sure there is no divergence.

> the current logical order of this PR is meaningless in the removal of Grammar_API is incorrect as the mlp files are still wrong

Yes, @matejkosik should address this.

> , it is also meaningless as much as the API is still leaking

WDYM?

**Comment by matejkosik** [comment]
> Yes, @matejkosik should address this.

Done.

**Comment by ejgallego** [comment]
@maximedenes Ok I have done another pass and greatly optimized the diffs, as you can check. The whole bussiness is two commits which are IMO pretty clean.

I don't see the point on keeping @matejkosik do more duplicated work, we should pick the more complete solution and move on with other API stuff, there is plenty to do.

**Comment by matejkosik** [comment]
@ejgallego 
> This is not the case, the granularity of both PRs look fine to me.

This is false because you undeprecated `API.Names.universe_context_set` in a commit which says
> [api] Put modules in order in API.{mli,ml}

Undeprecation (of API elements) is a different operation than reordering (of API elements).

Undeprecation (if was is intentional) belongs to a separate commit. If it is not in a separate commit, it means that that information is destroyed. Why this happened, I do not know but it has shaken my confidence in the commit.

**Comment by ejgallego** [comment]
@matejkosik can we stop this loss of time once and for all?? ____Really____

I have explained that exact question like 900 times, my PR predates the merge of cumulatives, so I did something as simple as to cut and paste from `Univ`, there is no deprecated, why is it deprecated in the API?

I don't think that reintroducing all the previous breakage so you feel better about some random rules is an effective use of time. The PRs have been ready technically since some time, I didn't want to remove the broken deprecation as not to interfere more, all the removal of deprecation that has happened in my branch is due that _in the first time_ the old implementation was totally broken I had to cut and paste from interface code.

**Comment by ejgallego** [comment]
In other words, the current status of `API.Univ.universe_context_set` is more correct in my branch than in this one, I could fix the few of such discrepancies and revert them to a broken status but please, I am getting tired, let's stop losing time.

**Comment by maximedenes** [comment]
Things look simple here. Each of you made one mistake:
- Emilio should have separated the "undeprecation" from the reordering.
- Matej should never have deprecated things in the API that were not deprecated in Coq.

I have the feeling that the first error is more of the "meta" kind (i.e. about the organization of the changes rather than the changes themselves). The second one looks more serious to me. I don't quite get how it shakes confidence, and the only information that is "destroyed" is a plain mistake, so no big dea IMHO.

**Comment by ejgallego** [comment]
> Emilio should have separated the "undeprecation" from the reordering.

Well, I did not "undeprecate" on purpose, I just had to copy from the original `mli` files as it was faster than fixing the wrong aliases business. Example in current master:

```
module Constr :
sig
  type t = Term.constr
  [@@ocaml.deprecated "alias of API.Term.constr"]
```

Could I had imitated the old behavior? Yes. Does it make sense to imitate it. No. Thus, many key modules involved in the "`Prelude`" had their interfaces redone from scratch, as their interfaces were totally nuts wrt ordering. Explain to me how I am supposed to maintain nonsense like the above.

Does that make sense.

**Comment by matejkosik** [comment]
> can we stop this loss of time once and for all??

What I am trying to explain to you is that your PR introduces regressions.

If we don't care about regressions, we can indeed stop talking and merge your PR. If we do care about regressions then, unfortunatelly, we need to understand each other and we clearly don't understand each other.

But imagine, what would happen if we did not care about regressions? What would happen with the properties that you have painfully installed? The prospect is not appealing.

**Comment by maximedenes** [comment]
> What I am trying to explain to you is that your PR introduces regressions.

I don't understand this. The deprecation was bogus, so removing it is not a regression. So what regressions do you mean?

**Comment by matejkosik** [comment]
> I don't understand this. The deprecation was bogus, so removing it is not a regression. So what regressions do you mean?

The correct statement is "`@@ocaml.deprecated` annotates API elements which are bogus"
(i.e. `@@ocaml.deprecated` marks API elements that should be deleted)

That is not the same statement as "`@@ocaml.deprecated` annotations are bogus"
(i.e. if you delete `@@ocaml.deprecated` annotations, you lose the information about the things that could be deleted --- and that information is useful, is it not?)

**Comment by maximedenes** [comment]
Ok, but where are the regressions?

**Comment by maximedenes** [comment]
I disagree btw. The annotations themselves were bogus, because they were not reflecting the state of the Coq codebase. So again, they should never have been introduced in the API.

What had to be done is a separate PR introducing deprecations in Coq, so that we discuss them.

**Comment by maximedenes** [comment]
I also want to insist that those aliases play no role in the difficulty of plugin programming in Coq. Getting rid of them would be slighty better, but should be very low priority. Documenting unification for example would bring exponentially more to plugin writers than removing a few aliases. I don't even understand how we got to work on that, it is a terrible strategy given our limited resources and I said it many times.

**Comment by maximedenes** [comment]
> Documenting unification for example

I took that example, but it is true of almost any function that is in the API. Why aren't we working on documenting functions that appear in the API, rather than wasting time removing aliases?

**Comment by matejkosik** [comment]
> What had to be done is a separate PR introducing deprecations in Coq, so that we discuss them.

[It was.](https://github.com/coq/coq/pull/718)

**Comment by maximedenes** [comment]
> It was.

Ok, I had forgotten about it, so fine. But it also means that even more time than I thought was spend on this already.

**Comment by matejkosik** [comment]
@maximedenes @ejgallego I suspect we wouldn't have this discussion if I simply deleted the useless stuff from the API instead of marking it as `@@ocaml.deprecated` in PR #718. I guess that was the mistake. I tried to be too conservative and it backfired on me.

**Comment by maximedenes** [comment]
That's probably true. In fact, it also broke the view of API0 as "the minimal subset of functions used in our plugins". There were no clients of API yet, so removing the functions wouldn't have been a big deal.

**Comment by matejkosik** [comment]
> There were no clients of API yet, so removing the functions wouldn't have been a big deal.

[Yes](https://github.com/matejkosik/coq/blob/trunk%2BAPI_ROADMAP/API/PROBLEMS/uncategorized#L5-L9).

**Pull request closed without merging**
