### PR TITLE
Proof engine doc

### PR DESCRIPTION
**Pull request by akr**
I fixed the example in dev/doc/proof-engine.md.

The main problem is
(1) the existential variable, e1, is f, not r.
https://github.com/coq/coq/commit/bd9dc9858e7dc47ecd4b165dbe5beb82f946286c and
(2) the last let-in expression had no body
https://github.com/coq/coq/commit/96f55b052c33fb8adfd005f67197e3e22456fb43 .

I also updated the example to compile with Coq 8.15.1.

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Looks good, thanks.

**Review by ppedrot — CHANGES_REQUESTED** [review]
Please squash the commits.

**Comment by akr** [comment]
I squashed the commits.

**Comment by ppedrot** [comment]
@akr sorry to be a bummer, but could you also replace the list of messages from the squash with a short high-level message summarizing the changes? Right now it's not very readable and mostly noise.

**Comment by akr** [comment]
I see.  I updated the commit message.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
