### PR TITLE
[ci] Build fiat-crypto targets in sequence

### PR DESCRIPTION
**Pull request by JasonGross**
This should hopefully alleviate memory problems on gitlab, by first
building the `lite` targets, and then building the remaining
not-that-big targets.

**Kind:** bug fix / performance / infrastructure.

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks, let's see how it goes.

**Comment by JasonGross** [comment]
GitLab is happy with fiat-crypto on this one (https://gitlab.com/coq/coq/-/jobs/69835422)

**Comment by ejgallego** [comment]
WDYT @SkySkimmer ?

**Comment by SkySkimmer** [comment]
I don't see why this would help.
Maybe we should rerun the fiat-crypto job a few times to build confidence.

**Comment by ejgallego** [comment]
> I don't see why this would help.

I think the problem is too much parallelism, so this patch reduces it by sequentializing so no targets from the split can run together.

> Maybe we should rerun the fiat-crypto job a few times to build confidence.

The first build actually happened in the worker with 1 thread so that's usually the problematic case, but it took quite a bit of time to finish.

**Comment by ejgallego** [comment]
Build time for fiat-crypto [worker]
- master: 67m 15s [gitlab 2.30ghz 1 thread]
- this patch:

**Review by ejgallego — APPROVED** [review]
This patch cannot make things worse and Jason knows what he's doing here.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@ejgallego can merge this

Gaëtan Gilbert

**Comment by Zimmi48** [comment]
Here are two more "out of memory" failures after this being merged:

- https://gitlab.com/coq/coq/-/jobs/70229540
- https://gitlab.com/coq/coq/-/jobs/70364291

In both cases, the runner had only one cpu core.
Since we are able to print this information, can't we also extract it to set `NJOBS` accordingly to the number of cores? (It could even help make all the builds run faster.)

**Comment by ejgallego** [comment]
> Since we are able to print this information, can't we also extract it to set NJOBS accordingly to the number of cores?

Unfortunately that information is not reliable, in some setups `/proc/cpuinfo` may return 32 CPUs if the host has them but only one would be available to the build, it depends on your container method.

In order to do this stuff reliably we need `gitlab-runner` to export to us the resource limit, so maybe we should open a bug request.

**Comment by Zimmi48** [comment]
OK, another proposal then: now that the targets are divided in two parts, can we put NJOBS back to 1 for the second make?

**Comment by ejgallego** [comment]
Sure that sounds fine, maybe we could just remove one expensive target? IMHO anyways the free Gitlab runners are awesome as sometimes we get 200 runners so the backlog clears every days, but long running CI tends to get preempted and I think it is natural that a free service does. So maybe we should just set up our own `fast-runner`s and be done.

**Pull request merged**
