### PR TITLE
Backport changes to the checker from #870.

### PR DESCRIPTION
**Pull request by Zimmi48**
I'm backporting these changes on the suggestion of @ppedrot to allow me to backport #896 as well.
Opening the PR to get a quick second review before merging.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
LGTM. We should nonetheless add a few tests for the checker, to be sure it's actually working.

**Comment by ejgallego** [comment]
> We should nonetheless add a few tests for the checker, to be sure it's actually working.

How is this different from `validate` ?

**Comment by Zimmi48** [comment]
@ppedrot
> We should nonetheless add a few tests for the checker, to be sure it's actually working.

I'll let you do so in a different PR.

**Comment by ppedrot** [comment]
@ejgallego The validate target only checks the standard library, and there are maaaany things that are actually not tested in the stdlib.

**Comment by ejgallego** [comment]
Sure, what I was wondering if you meant to add a `validate-testsuite` target, or you truly meant adding specific tests for the checker. [Or maybe both]

**Pull request merged**
