### PR TITLE
Simplify the code that handles trust of side-effects in kernel typing.

### PR DESCRIPTION
**Pull request by ppedrot**
For some reason the code was returning int option when only the value of the integer was relevant.

Trivial change that does not modify the extensional behaviour.

### CODE REVIEW

**Comment by ppedrot** [comment]
I think it was just laziness, as the code relies on the option value inside the loop.

The side-effect code is half-broken anyways, I am pretty sure I can find a proof of False, if not several, by just using safe ML code. It helps preventing involuntarily errors though. I have further cleanups pending, and at some point I really want to make it work properly.

**Comment by gares** [comment]
> The side-effect code is half-broken anyways

This is the kind of bullshit comment that makes me postpone the task of reviewing your (very welcome) cleanup.

**Comment by ppedrot** [comment]
@gares What if I expose a soundness bug only using the safe interface?

**Comment by gares** [comment]
If the bug also comes with a PR that fixes it, then I'll pay you a beer.

**Review by maximedenes — APPROVED** [review]
LGTM

**Pull request merged**
