### PR TITLE
Ssreflect pattern matching facilities

### PR DESCRIPTION
**Pull request by gares**
The language for sub term selection used by ssreflect's tactics and documented in
https://hal.inria.fr/hal-00652286 and https://hal.inria.fr/inria-00258384

This patch exports an extensive ML API (documented in ssrmatching.mli) as well as
a minimalist Ltac API.

Enjoy!

### CODE REVIEW

**Comment by ejgallego** [comment]
Hi Enrico, thanks for the PR, it is indeed a great first step to make the life of users and integrators easier!

Does there exist a patched math-comp to use with this PR?

**Comment by herbelin** [comment]
Dear all,

I'm glad that Enrico proposed this pull request: this is an opportunity to address a question which I feel as blocking in the development of Coq, and which I'm clearly not the only one to feel as blocking.

Scientifically, the pull request makes sense: it is an interesting approach to subterm matching, extensively tested in a very large library, even if it is not clear yet to me how to unify this approach with the other directions taken in Coq for subterm matching, and even if it is not clear to me that a plugin is the best approach, compared, say, to a tighter integration within a file such as find_subterm.ml or unification.ml, and a flag to make the algorithm available to the user.

On the origin of the code, something has to be said though. For young developers who only knew the MSR joint lab and did not know about the situation before, it might be strange to realize that at this time, the decision of creating the joint lab was not very consensual. It was a time where the economical and political strategy pursued by Microsoft was perceived extremely negatively by a large number of people, especially in academy, and especially at the Institute. In this context, and as far as I could see, the decision to collaborate with Microsoft was taken by a small group of people at the Institute who were convinced, probably in good faith, that cooperating was good, apparently concerned by the fact that MSR was composed from respectful colleagues, sometimes even friends, tempted by the MSR adventure. But the fact at the end is that it hurt the cultural values of a number of other researchers at this time, including me, and this wound is still in the memories.

Obviously the situation has changed. My bitterness of what happened at this time starts to have a seriously negative impact on the harmony in the team, especially with respect to a generation who emerged after the collaboration started. Several people take the by-products of this collaboration as they are, at their scientific value, without judging about their origin, feeling protected by the non-coercitive licence of the code, not feeling tight to the origin of funding, not feeling Microsoft now significantly worse than other monsters of the digital economy. I think it is time for me to forgive a decision who engaged the institute in a non-consensual collaboration, time to accept that the "bad" made by Microsoft is not a reason to reject the "good" that come from the collaboration. This is also the reason of this message, an emphasis of the complexity of the reality, a message to say that bad and good are not binary, a message to say that one can accept to see the good out of the bad, without ending being complicit, without loosing one's freedom of speech. When conflictual situations degenerate in cascade into other conflictual situations, it is time to say stop, to give priority to the well-living together and I hope that those who shared my concerns about the collaboration will in turn understand my position.

So, let's keep our feelings for us on this matter and concentrate on the scientific aspects. I lost part of my neutrality by being touched so strongly, but that the discussion go on without me.

Hugo

**Comment by mattam82** [comment]
I think a good option would be to merge this, as a plugin, and work to find a hook interface for find_subterm/unify_to_subterm, so that we can switch between the different implementations, making rewrite, set etc... parametric on subterm matching. However I'm not sure how to uniformize so one can use todays constr_patterns or ssrmatching's cpatterns, Enrico, did you have ideas about unifying that? 

In a different direction, I'm looking at generalizing strategical rewriting to handle more programmable rewritings (including patterns) and I found that relying more on the patterns could avoid some uses of full conversion in ssrmatching, but that's a different story we can talk about. It's nowhere near fine-tuned and stable as ssrmatching.

**Comment by gmalecha** [comment]
@mattam82 What are the "more programmable rewritings" that you have in mind?

**Comment by mattam82** [comment]
@gmalecha the rewriting with strategies like rewrite_strat (inorder (pattern p; lemma foo))

**Comment by gares** [comment]
Unfortunately I don't know well enough constr_patterns and the two term section functions you mention to propose something right now.  I'll look into it.

**Pull request merged**
