### PR TITLE
[compat] remove 8.10

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Fiat parsers is failing currently on `master` because of an unmerged overlay (https://github.com/mit-plv/fiat/pull/45). Let's wait for this overlay to be in and restart the job to avoid masking potential real failures.

Coquelicot has been failing for several days now, I think we can safely ignore this failure.

**Comment by gares** [comment]
> Coquelicot has been failing for several days now, I think we can safely ignore this failure.

IIRC we merged a fix in math-comp master, see https://github.com/math-comp/math-comp/pull/633, are you saying it's not enough?

**Comment by gares** [comment]
@CohenCyril I think the fix was not enough

**Comment by Zimmi48** [comment]
Apparently not. Coquelicot has been consistently failing on master for the ast few days.

**Comment by JasonGross** [comment]
Fiat-Parsers now passes

**Comment by Zimmi48** [comment]
@coqbot: merge now

**Pull request merged**
