### PR TITLE
Enable warning 70 (missing mli), add mli files

### PR DESCRIPTION
**Pull request by SkySkimmer**
I am tired of seeing compilation bottleneck on random grammar files

Overlays:
- https://github.com/MetaCoq/metacoq/pull/860
- https://github.com/ejgallego/coq-serapi/pull/323

### CODE REVIEW

**Comment by ejgallego** [comment]
Do you have a trace of the bottleneck in terms of a dune `--trace-file` output?

Having .ml-only files can be very useful in some cases too.

**Comment by SkySkimmer** [comment]
IIRC it was around g_vernac

**Comment by SkySkimmer** [comment]
jasmin failure is unrelated, see https://github.com/jasmin-lang/jasmin/issues/367

**Comment by silene** [comment]
Overall, I am in favor. But I am not too fond of adding `.mli` files for the `.mlg` ones. This seems way too fragile and cumbersome in the long run. It would be better to disable warning 70 for the corresponding `.ml` files in the Dune files. (No idea how to do that.)

**Comment by SkySkimmer** [comment]
I do want mli files for the mlgs
It already found some unused code and tends to enable more parallelism when compiling

I don't think it will be especially cumbersome but if it is we can always remove the warning and mlis

**Comment by ppedrot** [comment]
I am heavily supporting adding mli to mlg files. This makes explicit the kind of autogenerated crap we depend on in 
the outside world.

**Comment by silene** [comment]
But that is only if it accurately reflects the dependencies of the outside world. Perhaps I am misunderstanding something here, but I don't think anybody is depending on all these definitions from `g_ring.mli`.

**Comment by SkySkimmer** [comment]
serapi depends on g_ring https://gitlab.com/coq/coq/-/jobs/3838992623

**Comment by SkySkimmer** [comment]
BTW the strategy I used for generating the mli for mlg was to autogenerate then remove anything other than Entry and genarg

**Comment by Alizter** [comment]
Surely the use of g_ring in serapi is not essential. @ejgallego what do you think?

**Comment by ejgallego** [comment]
> Surely the use of g_ring in serapi is not essential. @ejgallego what do you think?

It actually is, it is the only way SerAPI can access the extended AST and seralize or print it correctly.

I really wish we had a different way to do so c.f. https://github.com/ejgallego/coq-serapi/issues/82

So indeed adding .mli files to .mlg files , as it has been pointed out, can be often tricky and hamper users that require access to Coq's Ast. This is a problem as often you will detect that _after_ a new Coq release when the upstream adapts.

**Comment by SkySkimmer** [comment]
>So indeed adding .mli files to .mlg files , as it has been pointed out, can be often tricky and hamper users that require access to Coq's Ast. This is a problem as often you will detect that after a new Coq release when the upstream adapts.

Those users are plugins, so if they're not in CI them breaking is expected.

**Comment by silene** [comment]
> Those users are plugins, so if they're not in CI them breaking is expected.

But if I understand correctly, that is a bit worse than that. If someone adds a new vernacular argument to one of Coq's `.mlg` files but forgets to transpose it into the corresponding `.mli` file, then it will be impossible to update Serapi's code to support this new syntax. And  Serapi being part of the CI will be of little help to detect this issue, won't it?

**Comment by ejgallego** [comment]
> > Those users are plugins, so if they're not in CI them breaking is expected.
> 
> But if I understand correctly, that is a bit worse than that. If someone adds a new vernacular argument to one of Coq's `.mlg` files but forgets to transpose it into the corresponding `.mli` file, then it will be impossible to update Serapi's code to support this new syntax. And Serapi being part of the CI will be of little help to detect this issue, won't it?

Exactly, that's the current situation; so far we only detect that either by manual inspection (so in that sense, we remove .mli files and use merlin to see what asts are in a plugin), or when someone runs an experiment and it fails due to a missing serializer.

Extensible Ast is tricky, if you want it to be usable by other consumers other than their own; I happen to have a few use cases:
- new printer (coq-layout-engine)
- faithful serialization
- custom hash and comparison fucntions (in coq-lsp)

**Comment by SkySkimmer** [comment]
>But if I understand correctly, that is a bit worse than that. If someone adds a new vernacular argument to one of Coq's .mlg files but forgets to transpose it into the corresponding .mli file, then it will be impossible to update Serapi's code to support this new syntax. And Serapi being part of the CI will be of little help to detect this issue, won't it?

Serapi devs can open a PR on Coq in that case.

**Comment by Matafou** [comment]
This generation of mli (+ cleaning) could maybe be automated and put in precommit script to prevent desynchronisation?

**Comment by Alizter** [comment]
There are tools for auto generating mli files: https://dune.readthedocs.io/en/stable/faq.html#how-can-i-generate-an-mli-file-from-an-ml-file

**Review by ppedrot — APPROVED** [review]
FWIW here is my official seal of approval.

**Comment by ejgallego** [comment]
After thinking a bit about this I'm quite uneasy about a solution that doesn't ensure that .mlg files are indeed exporting **all** their AST definitions, that is just gonna cause a lot of churn as people forget, we need to patch stable releases, etc...

So NACK for mlgs in the current state.

**Comment by ejgallego** [comment]
> Exposing everything because some project wants to do introspection is just not a practical way to work.

I don't see the point on only exposing a partial AST.

The problem indeed is that checking we don't forget anything would require serializing the whole of the CI, if I understand what you say correctly, I mean, we can do this, but still fragile and what a waste.

The current situation is bad because with this method we can have a solid release for a few months, then some person uses for example the linter on some development we never heard of and the we go boom! And fixing that is _very painful_.

Instead, let's do something like:
- For each `foo.mlg`, `coqpp` generates `foo_ast.mli` with the public things found in the `.mlg`
- Then the `foo.mli` includes the auto-generated `foo_ast.mli`

That seems pretty simple (and robust) to me, what do you think?

**Comment by SkySkimmer** [comment]
Are you saying some mechanism uses a dynamically determined subset of the ocaml API?

**Comment by SkySkimmer** [comment]
>For each foo.mlg, coqpp generates foo_ast.mli with the public things AST things found in the .mlg

impossible, coqpp doesn't know the types (`foo` in `foo Entry.t`)

**Comment by ejgallego** [comment]
> Are you saying some mechanism uses a dynamically determined subset of the ocaml API?

Kind of, the way it works in serlib for plugins is that inspect the .cmi file for genargs, manually for each release.

So if the .cmi starts being incomplete, we will fail at runtime in some files.

Happy to have a better method, c.f. https://github.com/ejgallego/coq-serapi/issues/82

**Comment by gares** [comment]
@ejgallego I've seen you mentioning serapi is deprecated on zulip, so I guess we can move forward even if some choice is not favorable to it.

**Review by gares — APPROVED** [review]
+1

**Comment by ejgallego** [comment]
> @ejgallego I've seen you mentioning serapi is deprecated on zulip, so I guess we can move forward even if some choice is not favorable to it.

Serapi is deprecated, serlib is not (and essential to a few projects).

Anyways not only serlib, but any project that would eventually like to use Coq's AST is affected by this.

**Comment by ejgallego** [comment]
> > For each foo.mlg, coqpp generates foo_ast.mli with the public things AST things found in the .mlg
> 
> impossible, coqpp doesn't know the types (`foo` in `foo Entry.t`)

Let's have users declare them.

**Comment by ejgallego** [comment]
> I see, I think we should then discuss the approach of serlib once again, maybe at the Coq call.

It sounds good, anything that can improve the current status is good!

serlib is the only tool as of today that has been trying to make available the AST of large Coq developments, but that kind of need is exactly the same to any other tool that would like to manipulate ASTs, even for LTAC you already have that problem.

Regarding this PR I guess it is not really a big deal to merge it or not, however I feel a bit wary as the motivation of this PR is really a micro-optimization, so I get thinking if this micro-optimization on build time is worth making the already bad situation worse, in particular due to warning 70 enabled.

**Comment by ejgallego** [comment]
> How is enabling a warning making things worse?

It forces us to add mli files for a subset we shouldn't (MLG)

**Comment by SkySkimmer** [comment]
Another nice thing about having mli for mlg: it lets us edit the mlg without having to recompile everything that depends on it (at least with -opaque)

**Comment by gares** [comment]
> It forces us to add mli files for a subset we shouldn't (MLG)

Why shouldn't we? Making it explicit what we generate looks like a feature to me.

**Comment by ejgallego** [comment]
> Why shouldn't we? Making it explicit what we generate looks like a feature to me.

Indeed I think having the interface is great, in fact I use the one OCaml generates now `.cmi`, but the question is how to keep the `.mli` file in sync when the `.mlg` evolves.

To recap, without the .mli file, we can look at the .cmi file and see what new ASTs does the module contribute, with the .mli file we lose that ability, and we will only fail at runtime when such AST is found.

**Comment by ppedrot** [comment]
@ejgallego You could easily list the registered genargs at boot time in serapi and output a warning when finding a genarg which is missing the correct registered data. We could also have this in the CI.

**Comment by gares** [comment]
So, am I right the issue you see is for the serlib use-case?

**Comment by ejgallego** [comment]
> So, am I right the issue you see is for the serlib use-case?

The issue is for anyone that needs to access Coq's AST.

**Comment by ejgallego** [comment]
> @ejgallego You could easily list the registered genargs at boot time in serapi and output a warning when finding a genarg which is missing the correct registered data. We could also have this in the CI.

Something like that would be nice, trouble tho is that you need to load all the plugins too, so the check is something a bit more special.

I guess what makes more sense is that Coq makes the check itself, so what would work best is a version of `Genarg.Register` that actually works at the plugin level, and indeed produces a fatal error if the registration caller is not complete w.r.t. all the genargs exposed by the plugin. WDYT?

**Comment by SkySkimmer** [comment]
>I guess what makes more sense is that Coq makes the check itself, so what would work best is a version of Genarg.Register that actually works at the plugin level, and indeed produces a fatal error if the registration caller is not complete w.r.t. all the genargs exposed by the plugin. WDYT?

I don't understand what that means.

**Comment by SkySkimmer** [comment]
BTW where is the code in serapi that looks at the cmi?

**Comment by ejgallego** [comment]
> I don't understand what that means.

It means that today to register a manipulation function for a `genarg` we need to use `Genarg.Register`, however there is no way to check if we forgot some genargs.

Instead, we could extend that API so it works at the module (or plugin) level; then, after a plugin is loaded (or a linked-in module), you need to register all the genargs that the module provides at once, or else you get an error as Coq would check that.

If we agree that this is the way to go I'm happy as it would solve the serlib issue, and provide IMHO a usable API for other AST clients.

> BTW where is the code in serapi that looks at the cmi?

As noted above I use merlin inside emacs to generate the list of genargs, then a macro, then I check vs the list. It is not automated but it works for me so far, at each release I go and do that check for all the `serlib/plugins`.

I can make that into a script, didn't because I hope we can come up with a better solution.

**Comment by SkySkimmer** [comment]
I still don't understand. Are you talking about some specific instantiation of Genarg.Register (it's a functor)?
For instance the one in globenv is not meant to have every genarg registered (it has only 3 currently: ltac in constr, ltac2 in constr and ltac `$` in constr).

**Comment by gares** [comment]
I don't get it either. Genargs are already registered, we just don't require a fold function (but only a glob, interp and print ones, roughly).

**Comment by ejgallego** [comment]
> I still don't understand. Are you talking about some specific instantiation of Genarg.Register (it's a functor)?

I guess it would take some kind of list of pairs `genarg_key * genarg_fn` where `genarg_fn` is existentially wrapped.

> For instance the one in globenv is not meant to have every genarg registered (it has only 3 currently: ltac in constr, ltac2 in constr and ltac `$` in constr).

That's an interesting function, it will produce an anomaly for most genargs I see.

But sure, I think the register function I propose should be a new API, and the current per-genarg API should be kept.

**Comment by ejgallego** [comment]
While we are at it there is another huge dragon in serlib which is https://github.com/coq/coq/issues/9271 [just mentioning for info, let's not hijack the PR]

**Comment by SkySkimmer** [comment]
My understanding is that serapi needs to have these things https://github.com/ejgallego/coq-serapi/blob/3251ac7592000e32bcc10ad994ac4f30b4cc8cc0/serlib/plugins/ltac2/ser_g_ltac2.ml#L10-L21 and https://github.com/ejgallego/coq-serapi/blob/3251ac7592000e32bcc10ad994ac4f30b4cc8cc0/serlib/plugins/ltac2/ser_g_ltac2.ml#L35
~~~ocaml
(* val Ltac2_plugin.G_ltac2.wit_ltac2_entry:
   (Ltac2_plugin.Tac2expr.strexpr, unit, unit) Genarg.genarg_type *)
module L2Entry = struct
  type raw = Tac2expr.strexpr
  [@@deriving sexp,hash,compare]
  type glb = unit
  [@@deriving sexp,hash,compare]
  type top = unit
  [@@deriving sexp,hash,compare]
end

let ser_wit_ltac2_entry = let module M = Ser_genarg.GS(L2Entry) in M.genser

let () = Ser_genarg.register_genser G_ltac2.wit_ltac2_entry ser_wit_ltac2_entry
~~~
Since ocaml erases types at runtime there's nothing we can register in coq-core.

**Comment by ejgallego** [comment]
> I don't get it either. Genargs are already "registered", we just don't require a fold function (but only a glob, interp and print ones, roughly).

The need to register new functions is for example implement a new AST printer or serializer.

How would the fold function work, for example, to defiine a new AST analysis function?

**Comment by ejgallego** [comment]
> Since ocaml erases types at runtime there's nothing we can register in coq-core.

I don't follow, we register stuff in coq-core just right, look at `ser_stdarg` ?

[You likely mean a different thing I guess]

**Comment by SkySkimmer** [comment]
ser_stdarg is in serlib not in coq-core

**Comment by ejgallego** [comment]
> ser_stdarg is in serlib not in coq-core

Not sure if I follow you, but can't we use `Genarg.ArgT.eq` ?

**Comment by SkySkimmer** [comment]
I guess we are not talking about the same thing, I want an API which does not require exposing random implementation details in the mli

**Comment by ejgallego** [comment]
> I guess we are not talking about the same thing, I want an API which does not require exposing random implementation details in the mli

I think I see what you mean, not sure how can we indeed have an extensible Ast as we do now without exposing at least a witness of the type of the extension, will think about it tho.

Do you consider the current `val foo_wit : (ast_t, ...) genarg` a random implementation detail?

**Comment by SkySkimmer** [comment]
yes

**Comment by ejgallego** [comment]
> I think I see what you mean, not sure how can we indeed have an extensible Ast as we do now without exposing at least a witness of the type of the extension, will think about it tho.

One way to do it is _à la_ Haskell an use a full dynamic type-level reflection (so yes we would save the types after compilation then), but that's not precisely lightweight.

IMHO a per-module check would solve almost all problems, and seems doable enough (famous last words)

**Comment by ejgallego** [comment]
> yes

Then let's forget for a moment about OCaml and Coq, and let imagine we have a base AST:

```ocaml
type ext
type t := Var of int | Lam of t | App of t | Ext of ext
```

what would be the API you want for
1. plugins extending the AST
2. tools accessing the full AST
?

**Comment by gares** [comment]
You just need to reify the type of the arguments of the constructor you add via a gadt. I do tons of these in Elpi, I'll wite an example in a CEP.

**Comment by ejgallego** [comment]
> You just need to reify the type of the arguments of the constructor you add via a gadt. I do tons of these in Elpi, I'll wite an example in a CEP.

Interesting, so if I understand correctly then the Ast processor would just grab the runtime type information?

On the other hand seems like a pretty deep change, @ppedrot , what do you think about the module-level registration primitive?

Something like that should be workable pretty quickly and would solve the main issue here.

**Comment by gares** [comment]
> On the other hand seems like a pretty deep change

On the contrary it can be incremental. Eg `ARGUMENT EXTEND foo REIFY BY { data }`

> Interesting, so if I understand correctly then the Ast processor would just grab the runtime type information?

I have in mind something in between. We already register printing functions, we could register serialization functions, or fold functions (it is just that today you can only recurse on terms, IIRC, not any type).
IIRC it is already based on GADTs behind the scenes.

There would be no AST preprocessor. The serialize function would be there. And if you need something extra you use fold/map, to map the AST to something you like. For extension nodes fold can give you a GATD representing the type of sub terms of the extension node, so that you can write an n-ary function binding the arguments and doing what you want, including calling the fold/map on sub terms.

**Comment by ejgallego** [comment]
Yes, using runtime type info looks like a nice solution, if it can get rid of the registration requirements.

> We already register printing functions, we could register serialization functions, or fold functions (in today printing functions you can only recurse on terms, IIRC, not any sub term, but the scaffolding is there).

Note that indeed our registration of printing functions suffers from the same problem we are discussing, I bet not all genargs have a printing function registered, as we have nothing that ensures it, so indeed I'd bet we can try to print an AST and we hit `assert false` in genarg or the filler `missing printer` added by coqpp.

**Comment by LasseBlaauwbroek** [comment]
FWIW: Tactician also walks Coq's AST pretty extensively, and I've had similar problems to what @ejgallego describes w.r.t. AST datastructures being inaccessible. A solution that wouldn't make that worse would be great.

But indeed, the current situation is not so great either w.r.t. the extensible part of the AST, so a solution that improves that situation would be even better :-)

**Comment by ejgallego** [comment]
@LasseBlaauwbroek indeed the current setup it is a big PITA and as I wrote above, drivers away many developers that could be willing to work with Coq.

I am wondering tho that if you are maintaining you own set of registration for misc serializers, we could try to join forces with what serlib does (it already provides many useful functions over ASTs, and I'm gonna add a few more).

serlib has some kind of "coverage" infra already so tactician could profit from it.

I'm indeed thinking that we could rename serlib to coq-ast-utils because it is its main role today.

**Comment by LasseBlaauwbroek** [comment]
@ejgallego yes, this is certainly one of the major sources of code-bloat in Tactician, so if we can make that better together I'd be all for it. Not entirely sure what that would look like though. If you'd like a conversation about that I'd be interested (possibly in-person).

**Comment by ppedrot** [comment]
It was decided at the weekly call to merge this PR, exposing all the bits required by serapi in the mli. This should be backwards compatible and satisfy both parties. Further more principled solutions can be looked for later on.

**Comment by ejgallego** [comment]
Some problems with mli-only modules here, https://github.com/ocaml/dune/issues/9 , but certainly stuff like lack of type deriving or exception declaration seem fatal to me for a modern OCaml codebase.

**Comment by ppedrot** [comment]
> How are these bits to be determined?

Systematic exposition of wit + parsing rules + CI. Not very different from what we do with other APIs as of today.

> I can speak for the serlib party to state that the solution proposed is not satisfactory for serlib.

I still fail to see why. You have access to the same API.

**Comment by ejgallego** [comment]
> > How are these bits to be determined?
> 
> Systematic exposition of wit + parsing rules + CI. Not very different from what we do with other APIs as of today.
> 
> > I can speak for the serlib party to state that the solution proposed is not satisfactory for serlib.
> 
> I still fail to see why. You have access to the same API.

I worry about the maintenance, but indeed, while not satisfactory, I'm OK with adding mli to the mlg file. In that case, the rationale is clear (saving a second of build time)

We can also add warning 70, but we should understand what the change entails, and how it fits in the bigger picture in terms of code organization / interface duplication. Depending on we'd like to organize Coq's API , warning 70 could have no effect or create problems, so the rationale here is more delicate IMO.

**Comment by ejgallego** [comment]
With that observation about the implications of the .ml -> .mli renaming this PR does, I have nothing else to say, so feel free to go ahead if you think the current form is OK for you folks.

I suggest further discussion about interface organization to happen in #7422 for example.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
