### PR TITLE
Remove obsolete files from dev/doc

### PR DESCRIPTION
**Pull request by gares**
- cic.dtd is related to the XML plugin
- about-hints uses v7 syntax
- minicoq.tex talks about a tool that is not there
- translate.txt talks about the v7->v8 translation machinery
- transition-* talk about v5->v7 changes to the sources layout

### CODE REVIEW

**Comment by gares** [comment]
I think these files may be of some interest for some people, but I don't think they are in the right place, hence my PR.

There are other files in there that are good candidates, like `old_svn_branches.txt` that is about the svn->git migration, or `README-V1-V5.asciidoc` that is very important to Inria (@maximedenes) I guess but again it is out of place.

**Comment by ejgallego** [comment]
@gares I guess you may want to remove a few of those but some of them are of historical interest and should be preserved? How about creating a new directory `doc/historical` to place them there?

**Comment by ejgallego** [comment]
> README-V1-V5.asciidoc

This is for sure not to be removed IMVHO.

**Review by Zimmi48 — APPROVED** [review]
I'm OK for removing these specific files but I won't merge this PR before Wednesday to give a bit of time for people to express different opinions. The file `about-hints` (even if very old) may make sense to be moved on the wiki... WDYT?

**Comment by Zimmi48** [comment]
Thinking about it again, why not moving the `transition-*` file content as an addendum in `README-V1-V5.asciidoc` to avoid this information to be completely erased?

:+1: for creating a sub-directory `history/` and move a few files in there. This could include `COMPATIBILITY`, `newsyntax.tex`, `ocamlbuild.txt`, `old_svn_branches.txt` `README-V1-V5.asciidoc` and `versions-history.tex`.

Longer term, :+1: for integrating `README-V1-V5.asciidoc` in the manual.

I suggested moving `about-hints` to the wiki instead of erasing it completely. The same thing could be done to `notes-on-conversion.v` I suppose.

**Comment by ejgallego** [comment]
So what's the status on this?

**Comment by ejgallego** [comment]
Ping again.

**Pull request merged**
