### PR TITLE
Remove unused UVars.AInstance.subst_fn

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Because it's the one I noticed is unused.
(it taking (universe -> universe) confused @mattam82 while rebasing the algebraic univs branch)

**Comment by yannl35133** [comment]
If you want, I could do a true cleanup and remove `AInstance` entirely, its existence only comes from my ignorance that sorts in terms could not have algebraic universes; since they only have levels I can coerce all matched universes into levels and use the existing machinery of `Instance`.

**Comment by ppedrot** [comment]
Subsumed by #18905

**Comment by herbelin** [comment]
> Less structures around universes is always a bonus.

As an aside, another difficulty to follow the universe-related code is the heterogeneity of naming (e.g. `uctx` for either `UState.t` or `UContext.t` or `ContextSet.t`, or `univs` for `UGraph.t` or `UState.named_universes_entry` or `ContextSet.t` or `Level.Set.t` or `universe_state` or even `evar_map`, etc.).

**Pull request closed without merging**
