### PR TITLE
Really remove ssrsearch/g_search.mlg

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
Does this also remove the ssrsearch folder? I don't remember how git handles empty folders.

**Comment by ppedrot** [comment]
Note that a quick git grep shows that `doc/stdlib/hidden-files` still has a reference to ssrsearch.

**Comment by SkySkimmer** [comment]
yes

Gaëtan Gilbert

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
