### PR TITLE
Disable warning 40 Constructor or label name used out of scope.

### PR DESCRIPTION
**Pull request by SkySkimmer**
I stopped believing that it's worth bothering with.

### CODE REVIEW

**Comment by ejgallego** [comment]
On the contrary, this warning prevents about a very dangerous situation and there is even discussion about making it an error upstream. Thus in principle I am against your change.

But I guess that if you provide some motivation or concrete use case for disabling the warning we could reconsider.

**Comment by ejgallego** [comment]
cc: @gasche

**Comment by ejgallego** [comment]
> What changed from [ocaml/ocaml#1333](https://github.com/ocaml/ocaml/pull/1333)?

It can make sense that the warning's default is off in OCaml given how annoying/hard to port some developments could be. However in Coq we already follow a stronger scoping discipline which I'm not sure we'd like to loose.

Anyways, a use case could convince me.

**Comment by SkySkimmer** [comment]
An annoying case is 
~~~ocaml
match whatever with 
| Qualified.Foo -> bla
| Bar(* warning 40 + warning 42 *) -> bli
~~~

**Comment by ejgallego** [comment]
Then I'd vote not to implement this change for now, we could discuss at the WG if @SkySkimmer thinks it would be interesting to gather more opinions.

**Pull request closed without merging**
