### PR TITLE
[proof] Deprecate "proof mode" API

### PR DESCRIPTION
**Pull request by ejgallego**
Any users of this API should coordinate with the ongoing work in PRs
numbered #459 and #566.

We thus move these PRs to target the 8.8 milestone.

### CODE REVIEW

**Comment by maximedenes** [comment]
I'm ok with it, but it is a bit borderline, because in other PRs we argued that we should deprecate only if we have a replacement.

**Comment by ejgallego** [comment]
I see your point, dunno what to do here...

Note that due to technical reasons this feature is unlikely to go thou a deprecation phase, we will just replace it with a different API. Anyways nobody is relying on it now I think, but I wanted to cover the 8.7->8.8 window.

**Comment by ejgallego** [comment]
In fact I am convinced we can remove `Proof_global` entirely soon.

**Comment by maximedenes** [comment]
Yep, usually we just remove such APIs. Another thought, how is this going to interact with the API merge? I guess the warnings should be moved there at the very least, right?

**Comment by maximedenes** [comment]
So maybe not worth the pain, we can still freely change that API in 8.8. Anyway, a plugin writer seeing the warning cannot do much, just get in touch and wait for the next version.

**Comment by ejgallego** [comment]
> Yep, usually we just remove such APIs. Another thought, how is this going to interact with the API merge? I guess the warnings should be moved there at the very least, right?

That's a good question; I think it should not interact for now as the API merge includes no documentation so plugin writers still do have to fallback to the main `.mli` files, right?

> So maybe not worth the pain, we can still freely change that API in 8.8. Anyway, a plugin writer seeing the warning cannot do much, just get in touch and wait for the next version.

That is already almost infinitely better than the current alternative, which is that the plugin write doesn't see the warning, tries to use the API, discovers it doesn't work/has bugs (it is broken ATM) and then, after losing considerable time contacts us.

**Comment by ejgallego** [comment]
Well, in fact I didn't want to make that explicit, but now I do: the proof mode API is mostly buggy now (both itself and the STM to blame), so yeah, better stick a warning there. I lost a lot of time tracking down bugs there...

**Comment by aspiwack** [comment]
It's not much used anyway.

The principle is sound, but the parser hacks (which predate this API, by the way, my goal in putting the hack behind an API was in particular to allow moving stuff in plug-ins: I moved the declarative proof mode this way, and that was the first step towards ltac itself being a plug-in).

I don't know what the status is. But I'd be rather surprised if I learned other plug-ins have started using it. Ssr doesn't. Perhaps Iris?

**Comment by ejgallego** [comment]
@aspiwack no user known, the point is to guard against possible new users, that indeed should coordinate with the ongoing PR to try to alleviate the current discrepancies.

**Comment by aspiwack** [comment]
Yes. I just meant that there are no real cost to deprecate, or even remove the API altogether.

I didn't follow what replacement you had in mind, by the way. I'm intellectually interested.

**Comment by ejgallego** [comment]
@aspiwack it is nothing very surprising for now, we are just trying first to finish the integration with the STM, as after the STM was merged the proof modes become broken, `Load` too, etc... due to the parser not activating modes properly.

For now we think all that we want to support is parsing different syntaxes, an API a bit more refined that `unit -> unit`, however this is challenging due to a few reasons... In particular we'd like to have different bindings to tactics and proof languages, but details are in the air...

**Comment by aspiwack** [comment]
Is there a CEP thingy?

**Comment by ejgallego** [comment]
> Is there a CEP thingy?

Yup, but [it](https://github.com/coq/ceps/pull/16) hasn't been updated with the last discussions I think. Not much missing I think.

**Review by maximedenes — APPROVED** [review]
The deprecation looks sound to me, if the goal is to discourage plugin writers from starting to use this API.

**Comment by herbelin** [comment]
Sorry if I misunderstood the discussion, but was it converging? Can someone briefly summarize the whys and therefores of the discussion for the outsider (problems witht the stm, how to solve it, or whatever it is about)?

**Comment by maximedenes** [comment]
My feeling was that @ejgallego and @gares have converging plans, that would imply a redesign of this API. So adding a warning seemed strictly better than doing nothing.

As for a recap of the plans, I'll let @ejgallego elaborate.

**Comment by ejgallego** [comment]
> Sorry if I misunderstood the discussion, but was it converging?

I think it did.

> Can someone briefly summarize the whys and therefores of the discussion

Well there was not a lot of discussion to summarize as AFAICS we are all in the same page that deprecation here has no cost.

The old proof mode API (basically `unit -> unit`) was not used and should be split into a more structured method as sketched on the CEP.

With regards to proof modes in general, @herbelin, the situation is hard to summarize as the issue is complex and information is spread among bugs and PR. Lets just focus on a particular issue: enabling the "tactic parsing mode".

Before the STM, such parsing mode was enabled on `Proof_global.start_proof` and disabled on `Proof_global.end_proof`. This was fine, however it had the effect that full execution of all commands was necessary in order to parse a Coq document containing proofs.

When the `STM` was introduced, a functional overlap appeared. Now, the STM has to take over the proof mode in order to parse a document, and simulate `start/end_proof` so the parser is in the right state. However, there are some commands whose behavior here is dynamic so the STM must still execute them to see if a proof was opened or not. There are several more complications, etc...

The short story is that indeed `Proof_global` should go away altogether, in fact, I have a patch that almost does it. Now proof state is managed by the STM and will be supplied to vernac interpretation in a functional way.

A more pressing issue is how to manage the static classification of proof starting commands. For now, we are focused first on making such management _sound_, given than as of today the management has some bugs (however not easily observable, apart from the problem with `Load`). This was implemented by separating the parsing state from the rest of state in the PRs, however we still need to resolve who is managing the setting, and how to assert the soundness of the classifier.

**Comment by herbelin** [comment]
@ejgallego: Thanks.

**Comment by ejgallego** [comment]
Most welcome. Indeed this is a case where the dynamic nature made things very complicated; having a syntactic proof bracketing would really help here, so even if we don't consider it in the short term, IMVHO we should not forget about that idea. (Bracketing for notations imports could also have some benefits, I think there is some discussion in CEP000).

**Pull request merged**
