### PR TITLE
[rtauto] [auto] Use new proof engine.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Code change looks OK but this needs a benchmark.

**Comment by ppedrot** [comment]
Bench running here: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/601/console.

**Comment by ejgallego** [comment]
Thanks for the bench @ppedrot

**Review by PierreCorbineau — APPROVED** [review]

**Comment by ejgallego** [comment]
I'd say the bench is fine 
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬───────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │        mem faults         │
│                        │                         │                                             │                                             │                               │                           │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW     OLD   PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│              coq-sf-lf │   47.50   47.85 -0.73 % │      131119007509      131696452428 -0.44 % │      216498360513      216682162511 -0.08 % │     430828     430872 -0.01 % │     137     164  -16.46 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│ coq-mathcomp-ssreflect │   69.61   69.96 -0.50 % │      192146059440      192718420855 -0.30 % │      275940594587      276057840560 -0.04 % │     532452     532316 +0.03 % │     146      15 +873.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│             coq-sf-plf │   78.36   78.69 -0.42 % │      216738961091      217047980862 -0.14 % │      319169783763      319390701497 -0.07 % │     519412     519460 -0.01 % │      15      23  -34.78 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│    coq-formal-topology │   61.62   61.76 -0.23 % │      168397470300      168402542325 -0.00 % │      256229400839      256449478243 -0.09 % │     479876     479892 -0.00 % │       0       0    +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│   coq-mathcomp-algebra │  191.60  191.86 -0.14 % │      531492186623      531649212009 -0.03 % │      719552155530      719682615895 -0.02 % │     640056     640216 -0.02 % │      51      51   +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│  coq-mathcomp-fingroup │   87.48   87.59 -0.13 % │      242542684523      242753683188 -0.09 % │      357824470840      358030173351 -0.06 % │     581924     581928 -0.00 % │       0       0    +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│     coq-mathcomp-field │  267.03  267.02 +0.00 % │      742297179666      741378326462 +0.12 % │     1112377794449     1112675853703 -0.03 % │     754576     754884 -0.04 % │      14       2 +600.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│               coq-hott │  336.47  336.37 +0.03 % │      933311574626      932738435601 +0.06 % │     1408132638617     1408257365220 -0.01 % │     473508     473464 +0.01 % │     475      59 +705.08 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│              coq-flocq │  597.79  597.25 +0.09 % │     1663554334211     1660574883597 +0.18 % │     2428723286569     2428443832167 +0.01 % │    1770872    1772760 -0.11 % │     601     596   +0.84 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│ coq-mathcomp-odd-order │ 1439.42 1437.76 +0.12 % │     4009485048892     4005329477026 +0.10 % │     6598267458040     6598506094035 -0.00 % │    1374248    1374036 +0.02 % │      65      49  +32.65 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│       coq-fiat-parsers │  725.67  724.72 +0.13 % │     2011044709608     2009289573820 +0.09 % │     3066018869537     3066333840956 -0.01 % │    2888016    2908524 -0.71 % │     496     701  -29.24 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│         coq-coquelicot │  108.94  108.79 +0.14 % │      301482818757      300875166413 +0.20 % │      408887444116      408920354508 -0.01 % │     704748     704740 +0.00 % │     283     113 +150.44 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│            coq-unimath │ 2222.70 2219.50 +0.14 % │     6179966614025     6170735688746 +0.15 % │    10667625309101    10662413585500 +0.05 % │    3039260    3039276 -0.00 % │     238     112 +112.50 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│        coq-fiat-crypto │ 6488.36 6478.70 +0.15 % │    18042077645669    18018958043170 +0.13 % │    29230225684681    29232288890555 -0.01 % │    2459532    2559788 -3.92 % │    1662    1235  +34.57 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│ coq-mathcomp-character │  291.02  290.54 +0.17 % │      809362791020      808248582506 +0.14 % │     1151710957576     1151879487988 -0.01 % │    1106888    1106868 +0.00 % │     101     266  -62.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│            coq-bignums │  102.86  102.64 +0.21 % │      284384908368      284807116670 -0.15 % │      411438003089      411639581708 -0.05 % │     538156     537920 +0.04 % │     300     269  +11.52 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│           coq-compcert │  902.18  900.14 +0.23 % │     2501183418941     2497720386704 +0.14 % │     3607648121580     3607797702134 -0.00 % │    1305728    1305596 +0.01 % │     261     386  -32.38 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│  coq-mathcomp-solvable │  225.32  224.79 +0.24 % │      626151887990      623912843452 +0.36 % │      877066033903      877250383571 -0.02 % │     862940     862824 +0.01 % │     117       6 +1850.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│               coq-corn │ 1562.56 1558.30 +0.27 % │     4335174807469     4327260990591 +0.18 % │     6322719984008     6322724944920 -0.00 % │     873380     873324 +0.01 % │      45      45   +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│              coq-color │  750.23  747.67 +0.34 % │     2080095461862     2073112924778 +0.34 % │     2508256274647     2508135796561 +0.00 % │    1435948    1435848 +0.01 % │     248     476  -47.90 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│          coq-fiat-core │  139.47  138.96 +0.37 % │      388121589405      387644504534 +0.12 % │      521231238085      521362653089 -0.03 % │     501280     501164 +0.02 % │     393     196 +100.51 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│        coq-lambda-rust │ 2394.94 2385.65 +0.39 % │     6671925969268     6645655521475 +0.40 % │     8977446436210     8970557394768 +0.08 % │    1427788    1437304 -0.66 % │       0       0    +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│             coq-sf-vfa │   51.11   50.91 +0.39 % │      140878229450      140844606914 +0.02 % │      227331330362      227513001156 -0.08 % │     532816     532768 +0.01 % │      30      37  -18.92 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│                coq-vst │ 3184.78 3172.23 +0.40 % │     8859813496664     8827250621173 +0.37 % │    12255341530738    12259088014590 -0.03 % │    2228400    2229444 -0.05 % │     640     856  -25.23 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│       coq-math-classes │  258.62  257.22 +0.54 % │      711504751528      708601216453 +0.41 % │      932004002963      932113504835 -0.01 % │     528572     528824 -0.05 % │      88      83   +6.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────────────┤
│             coq-geocoq │ 2065.26 2052.50 +0.62 % │     5735716843529     5701537430998 +0.60 % │     8275129185338     8276175295087 -0.01 % │    1242612    1221440 +1.73 % │     604     180 +235.56 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴───────────────────────────┘
```

**Comment by ppedrot** [comment]
@ejgallego It seems this needs a rebase now.

**Comment by ejgallego** [comment]
Done.

**Comment by ejgallego** [comment]
Merci !

**Pull request merged**
