### PR TITLE
Stop describing ltac2 as experimental in doc

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by proux01** [comment]
While at it, maybe you can even say that the goal is to deprecate ltac1 and make ltac2 the default.

**Comment by SkySkimmer** [comment]
Merged to https://github.com/coq/coq/pull/19121/

**Comment by jfehrle** [comment]
> While at it, maybe you can even say that the goal is to deprecate ltac1 and make ltac2 the default.

FWIW It makes sense to encourage users to write new code in Ltac2 and to convert existing Ltac1 libraries to Ltac2.  AFAICT conversion is not trivial and there are no written guidelines on how to do so.  I expect we wouldn't consider removing Ltac1 until there's no longer any significant use of Ltac1.  That day may never come.  "Deprecate" suggests that a removal will definitely occur at some point.  I don't think we know that yet.

**Comment by Zimmi48** [comment]
Indeed, we can only deprecate when we are sure that the migration is feasible at a reasonable cost, and we don't know how long it will take before we reach that day. However, it's fine to state that eventual deprecation is a goal (or said otherwise, it is / should be on the long-term roadmap).

**Pull request closed without merging**
