### PR TITLE
V8.5 vm univ

### PR DESCRIPTION
**Pull request by gmalecha**
I'm seeking comments on this patch which adds support for computing with the virtual machine on definitions that are universe polymorphic. This is in relation to Coq bug 4247 (https://coq.inria.fr/bugs/show_bug.cgi?id=4247).

I also have several test cases (not included in this current patch) that this runs on, but I'm not sure where they should go in the tree.

Finally, there is one thing that seems to be different than standard computation. The following definition:

```
Time Definition _1 : height (@Empty nat) = O :=
  @eq_refl nat O <: height (@Empty nat) = O.
```

Fails while using a regular (:) cast succeeds. The error message is the following:

```
The term "@eq_refl nat@{Top.165} O@{Top.165}" has type
 "@eq nat@{Top.165} O@{Top.166} O@{Top.166}"
while it is expected to have type
 "@eq nat@{Set}
    (@height@{Top.161} nat@{Top.163} (Empty@{Top.62} nat@{Top.163})) O@{Set}"
(cannot unify "@eq nat@{Top.165} O@{Top.165} O@{Top.165}" and
"@eq nat@{Set}
   (@height@{Top.161} nat@{Top.163} (Empty@{Top.62} nat@{Top.163})) O@{Set}").
```

The two terms are _not_ equal but only due to universes. I'm not certain if the normal reduction mechanism is doing something different in terms of picking unifications later. With the correct universe annotations the definition goes through.

### CODE REVIEW

**Comment by maximedenes** [comment]
Hi Greg,

This is very helpful, thanks!

A lot of our energy goes into fixing other 8.5 bugs these days, but we'll to review this patch very soon. It is considered blocking for beta 3 anyway.

Meanwhile, to answer superficially your questions:
- the test files are very welcome and should go somewhere under test-suite/ in the tree
- the problem with casts is probably the same as https://coq.inria.fr/bugs/show_bug.cgi?id=4346
  I'm working on it :)

Thanks again for your contribution!

**Comment by mattam82** [comment]
Hi Greg,

  the code looks fine to me. From what I gather every constant application refers to a FVUnivs block that contains the substituted universes right? And every Type occurence accumulates a substitution of it's variables as well? A few remarks:

- You should maybe be comparing universes/levels according to the current (Environ.universes env) graph (with Univ.check_eq/leq)
- The cardinality test for Type u is maybe strange, what happens on max(Set, i) for example?

**Comment by gmalecha** [comment]
Thanks for the feedback.

Yes, every universe polymorphic definition contains a block that has the values for each of the universe variables. You are correct about the Type definition as well.

> * You should maybe be comparing universes/levels according to the current (Environ.universes env) graph (with Univ.check_eq/leq)

Where? I assume this is somewhere inside of (https://github.com/gmalecha/coq/blob/v8.5-vm-univ/kernel/vconv.ml) which I am slightly less certain about. Is this related to @maximedenes comment above about https://coq.inria.fr/bugs/show_bug.cgi?id=4346?

> * The cardinality test for Type u is maybe strange, what happens on max(Set, i) for example?

Are you referring to the code here (https://github.com/gmalecha/coq/blob/v8.5-vm-univ/kernel/cbytegen.ml#L604)? The intention of this code is to find all of the variables that occur in ```u``` and record their values. The code in vnorm (https://github.com/gmalecha/coq/blob/v8.5-vm-univ/pretyping/vnorm.ml#L202) then re-assembles the type. There are some assumptions in that about the order of the ```fold``` and the order of the values returned by ```elements```, but I could not come up with a nicer way to do it. Maybe assembling the substitution map during bytecode generation is a cleaner approach and storing the closure in the vm-value. The assertion about the length of the arguments seems reasonable because you can not partially apply ```Type```.

**Comment by mattam82** [comment]
Re comparing universes:
Yes, this is the same issue. Actually the VMs should be parameterized like conversion in kernel/reduction.ml by a universe_compare record to be able to perform inference and checking of universes according to the current graph. I guess Maxime is on it.

Re cardinality:
Indeed that was the code I was looking at but now that I see the map_filter and from your comment I think this is ok. Indeed the invariant on ordering should be made apparent in the Universe interface.

**Comment by gmalecha** [comment]
> Re cardinality:
> Indeed that was the code I was looking at but now that I see the map_filter and from your comment I think this is ok. Indeed the invariant on ordering should be made apparent in the Universe interface.

With a comment? Or would it be better to store a closure in the vm that constructs the universe given the arguments? I guess the benefit of the later is that the invariant occurs over n-lines instead of 3 files.

**Comment by mattam82** [comment]
Maxime and Benjamin Grégoire have been looking at it and think the more regular "one argument per universe variable" implementation would be more efficient (allocating arrays is not cheap apparently). Did you try that?

**Comment by gmalecha** [comment]
I am tracking down a final bug in my implementation of it. The implementation is simpler, I will try to look at performance, but I don't currently have a lot of code that uses vm compute on universe polymorphic definitions since it wasn't supported.

@maximedenes Are you also implementing this with @bgregoir ?

**Comment by gmalecha** [comment]
That code is available here: https://github.com/gmalecha/coq/tree/trunk-universes-curry (also rebased on top of trunk)

**Comment by gmalecha** [comment]
This is resolved.

**Pull request closed without merging**
