### PR TITLE
Simplify argument scopes

### PR DESCRIPTION
**Pull request by maximedenes**
We do not change the semantics, except for a few bugs when the scope
cache was not recomputed. In particular, we keep the dynamic binding
effect `Bind Scope` has on argument scopes.

### CODE REVIEW

**Comment by maximedenes** [comment]
@herbelin This seems ready. Are you willing to assign?

**Comment by herbelin** [comment]
> @herbelin This seems ready. Are you willing to assign?

I'am. Can you in the meantime give a brief summary of what bugs are fixed and provide a test for them? (A recent example of well summarized commit can be found e.g. in 588c4047.)

**Comment by maximedenes** [comment]
> Can you in the meantime give a brief summary of what bugs are fixed and provide a test for them?

That's not easy, because essentially we had a cache that we invalidated only sometimes. I have one repro case that I'll try to add, though.

**Comment by herbelin** [comment]
> I have one repro case that I'll try to add, though.

OK

**Comment by maximedenes** [comment]
@herbelin This is ready (the QuickChick failure is due to an overlay that had not yet been merged). Can you merge? Thanks!

**Comment by maximedenes** [comment]
I rebased just to get a green CI.

**Comment by herbelin** [comment]
Thanks, this is clearer. I wrote my questions at #10212,

On another topic, shouldn't the removal of `Compat88.v` morally go in another (specific) PR?

**Comment by maximedenes** [comment]
> Thanks, this is clearer. I wrote my questions at #10212,

Your questions about `Bind Scope` are interesting, but I believe they are orthogonal. This PR does not change the semantics of `Bind Scope`. It fixes the fact that argument scopes sometimes forget to take bound scopes into account (because the cache was incorrect).

> On another topic, shouldn't the removal of `Compat88.v` morally go in another (specific) PR?

Note that this PR is removing the test file called `Compat88.v`, not the compatibility file with the same name itself. I had to remove it because it is precisely testing that the bug occurs...

**Comment by maximedenes** [comment]
Now that the documentation has been updated, it is more clear that this is a bugfix. Is there anything more I should do?

**Comment by herbelin** [comment]
> Now that the documentation has been updated, it is clearer that this is a bugfix

Yes, it is clearer that it is a bugfix of the dynamic semantics. 

What about the semantics of `Bind Scope` wrt simple `Require` and wrt `Require Import`? Looking at the documentation, I don't see something about that?

So, strictly speaking, afaicj, there is also a change wrt (another) undocumented semantics.

> Is there anything more I should do?

If we go in the direction of documenting things more precisely (and apparently we do), documenting the semantics that we fix for  `Import` wrt  `Bind Scope` is still to be done.

If @silene is ok for the semantics wrt `Import` that this PR introduces, I would not argue too strongly against it in the sense that both options are defensible and it is practise which will tell. In this [comment](https://github.com/coq/coq/issues/10064#issuecomment-492937050), @ggonthier did not mention the question of import, so I don't know if his experience would give arguments in favor of one or the other semantics. In this [comment](https://github.com/coq/coq/issues/10064#issuecomment-489370006), @jashug did refer to `Import` but I could not infer whether it was to recommend that dynamic scopes are propagated even w/o import or if was it to recommend that static scopes stopped being propagated even w/o import.

On the `Compat88.v` question, you did not say anything. Don't you want to attach it to an stand-alone PR?

Side comments. For the record, the documentation PR is at #10227. For the record, the two suggestions at the bottom of this [comment](https://github.com/coq/coq/issues/10064#issuecomment-492937050) seem interesting.

**Comment by maximedenes** [comment]
> But it is not fully clear to me why it is affected by this PR, i.e. in which sense it is testing an import behavior.

It was testing a `Require` (without `Import`) behavior.

**Comment by maximedenes** [comment]
> What about the semantics of `Bind Scope` wrt simple `Require` and wrt `Require Import`?

As I wrote above, this PR does not change the `Import` behavior of `Bind Scope`:

`A.v`:
```coq
Declare Scope foo_scope.
Axiom T : Type.
Bind Scope foo_scope with T.
```

`B.v`:
```coq
Require A.
Print Scope foo_scope.
Import A.
Print Scope foo_scope.
```

produce the same on `master` and after this patch: the first `Print Scope` says `foo_scope` is not attached to any class, the second says it is attached to `T`.

**Comment by herbelin** [comment]
> As I wrote above, this PR does not change the `Import` behavior of `Bind Scope`:

OK.

Then, my question was not clear enough. My question is about what changed wrt `Require Import` and non-import `Require`? Typically, what are the answers to the remaining question marks below (I added `Arguments` so as to get an even more general picture and I put an `X` where this PR is fixing - but how? - an unexpected static behavior which we should not have to mention in the first place):

|                        | `Bind Scope` | static effect of `Bind on a declaration (i.e. `Bind` before declaration`)| dynamic effect of `Bind` on a declaration (i.e. `Bind` after declaration) | `Arguments`
| --- | --- | --- | --- | --- |
|                       | (as reported by `Print Scope`) | (as reported by `About`) | (as reported by `About`) | (as reported by `About`) |
| `Require` (master) | not done  | done (X) | not done (X) | done |
| `Require` (PR) | not done | ? | ? | ? |
| `Require Import` (master) | done | done | done | done |
| `Require Import` (PR) | done | done | done | done |

As for the documentation (after #10227), what is documented and what is not of the above table? As far as understand the effect of #10227, the dynamic effect of `Bind Scope` on declarations is documented, as well as the effect of `Arguments` and how `Arguments` takes precedence over dynamic scoping, but the behavior wrt to `Require` and `Import` is not documented, right?

> It was testing a `Require` (without `Import`) behavior.

Are all lines of `Compat88.v` made invalid with this PR or only some of them, and if the latter, which?

**Comment by maximedenes** [comment]
Thanks, it makes things easier to communicate.

I believe what this PR does is:

|                        | `Bind Scope` | static effect of `Bind on a declaration (i.e. `Bind` before declaration`)| dynamic effect of `Bind` on a declaration (i.e. `Bind` after declaration) | setting scopes with `Arguments`
| --- | --- | --- | --- | --- |
| `Require` (this PR) | not done | not done | not done | done |

**Comment by maximedenes** [comment]
> Are all lines of `Compat88.v` made invalid with this PR

AFAIK, yes. The comment at the top of the file explains that it is testing exactly what the bug was...

**Comment by herbelin** [comment]
There seems to have been a confusion on what the "bug" is. I thought it was about the difference of static vs dynamic behavior without `Import`. But the "bug" is actually easily explained by the difference between non-activation of `Bind Scope` at require-only (on which the dynamic behavior depends) and activation of `Arguments` at require-only (on which the static behavior depends).

I suspect then that a canonical and easy fix for the difference of behavior is to remove the various calls to ` declare_{inductive,ref}_argument_scopes` in `declare.ml`.

Now, once the discrepancy between `Bind` before a declaration and `Bind` after a declaration is fixed, one can wonder why `Arguments` is activated w/o import and `Bind Scope` is not. This looks a bit arbitrary.

One could argue that `Bind Scope` has an effect on the future declarations and that it should not be activated. But one can argue also that once a declaration has its scope assigned by means of `Bind Scope`, it  has to keep this scope the same way as `Arguments` keeps it without `Import`. But one can also argue conversely that `Arguments` should not activate scopes without an import.

The change made by this PR has no effect, so maybe (again), that's not so important which semantics is chosen (since after all an activated scope but without activated notations in the scope is basically as ineffective as no scope at all), but I'd be curious to know the impact on compatibility if we adopt the opposite solution, i.e. to make `Bind Scope` available even without `Import`.

> The comment at the top of the file explains that it is testing exactly what the bug was...

The comment basically amounts to tell that the file is testing availability of numeral notations w/o require (since this is what changed in 8.8). If this PR adds one more change in the compatibility between 8.8 and master, it is the Coq8.8.v file which should be changed to restore the 8.8 compatibility (by adding explicitly the not anymore automatically imported scopes) rather than removing the test.

**Comment by maximedenes** [comment]
I'm getting a bit lost here to be honest, and I've long exhausted the time I was planning to spend on this, so I think I let experts handle it. My idea was to refactor the arguments code before finishing #10049, but in retrospect it was not a great idea.

I'm fine with closing this, just let me know if that's the appropriate thing to do.

**Comment by herbelin** [comment]
You revealed a couple of issues wrt scopes and import which are subtle and important and that would be a pity not giving a clear solution to these problems (note in passing that similar problems on the interaction between `Auto` and `Manual` data exist with implicit arguments, see e.g. this [comment](https://github.com/coq/coq/pull/10231#issuecomment-495936228) to #10231).

I just tried to look at the details of the PR and its seems good.

What I would suggest is:
- remove dead code (`scope_of_arg`)
- experiment the other import semantics for `Bind Scope` (i.e. move the case ScopeClasses` of  `Metasyntax.open_scope_command` to  `Metasyntax.load_scope_command`)
- In any case, if not the latter, change `Coq88.v` rather than remove `Compat88.v`

**Comment by herbelin** [comment]
@maximedenes: there is no strict urgency on my side, but just eventually tell if the proposed plan is ok to you. I do think that the inconsistency that this PR fixes should be merged!

**Comment by ppedrot** [comment]
What do we do with this PR?

**Comment by maximedenes** [comment]
I'll come back to it, but it is not at the top of my priority list. I'm on holidays for now.

**Comment by Zimmi48** [comment]
Dear PR author(s) and contributors, it seems to us this PR may need additional work beyond the 8.12 branching deadline on May 15th.

We are thus removing the 8.12+beta1 milestone; please retarget as appropriate.

We apologize in advance if we misunderstood the PR status.

**Comment by maximedenes** [comment]
> I'll come back to it, but it is not at the top of my priority list. I'm on holidays for now.

Looking back at it, I feel the same way I wrote above: this fix is not a priority for me, so I'll let maintainers handle it the way they like. I could finish #10049 independently.

**Pull request closed without merging**
