### PR TITLE
Flag to disable cumulativity of Prop

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Probably a bit buggy in random tactics but the kernel side should be good.

**Comment by SkySkimmer** [comment]
cc @tabareau

**Comment by ppedrot** [comment]
Ah, not one of those SR-breaking typing flags again! Why do we need that beyond experimentation?

**Comment by SkySkimmer** [comment]
Universe inference doesn't know how to deal with noncumulative Prop yet

**Pull request closed without merging**
