### PR TITLE
Correctly report non-projection fields in records

### LINKED ISSUE #8736: Mixing in non-projection fields in a record results in an incorrect error message
#### Version

8.10+alpha

#### Operating system

macOS

#### Description of the problem

When a record contains fields that are projections as well as fields that aren't projections, the error message is "This record contains fields of different records" when the non-projections should be reported instead.

```coq
Record t :=
  { foo: nat }.

Fail Check {| unit := 2 |}.
(* unit: Not a projection *)

Fail Check {| unit := 2;
              foo := 2 |}.
(* unit: Not a projection *)

Check {| foo := 2;
         unit := 2 |}.
(* "This record contains fields of different records"
should be "unit: Not a projection" *)
```

### PR DESCRIPTION
**Pull request by tchajed**
**Kind:** bug fix.

Fixes #8736

- [x] Added / updated test-suite

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by ppedrot** [comment]
That's quite a trivial fix. @herbelin if you don't complain I'll merge quickly.

**Comment by tchajed** [comment]
I'd actually like to include the name of the inductive from the first projection in this error message (because it's known), but I'm not sure how to access it. Is there an easy to way to get it? If not it's ok, this is still an improvement.

**Review by ejgallego — CHANGES_REQUESTED** [review]
Extend `internalization` error and display the error from the upper layers.

**Review by ejgallego — APPROVED** [review]
Ok, this looks good to me. It should help to have better error message in the way @ppedrot mentioned; but you don't need to do that in this PR indeed as it will involve a lot of surgery.

**Comment by herbelin** [comment]
>  @herbelin if you don't complain I'll merge quickly.

I don't complain, well on the contrary.

Regarding the extension `internalization_error`, I approve, because it gives a better overall view to possible errors of the file.

We should however not restrict ourselves to write more informative error messages because of the cost induced by moving the printers to the upper layers. Moreover, there is an easy way to do it here. To get the user-level pretty-printed name, as hinted by @ppedrot, something like
 `shortest_qualid_of_global ?loc Id.Set.empty (IndRef (inductive_of_constructor record.Recordops.s_CONST))` should work.

**Comment by tchajed** [comment]
Thanks for the tip @herbelin! I’ll update the pull request tomorrow and improve the error message

**Comment by tchajed** [comment]
Done, and also added the conflicting records to the message "This record contains fields of different records".

**Comment by ppedrot** [comment]
@tchajed CI is complaining for spurious reasons, can you rebase atop of a recent master?

**Comment by ppedrot** [comment]
The CI failure is spurious, I'm merging the PR.

**Pull request merged**
