### PR TITLE
Add generated dune files to artifact paths

### LINKED ISSUE #16495: [ci] [build] refman job is rebuilding .vo
@ejgallego Have a look at this dummy PR:
https://github.com/coq/coq/pull/16491

For some reason, tarballing the _build dir seems to be triggering a rebuild but only for our coq rules. To be clear, the artifacts are all correctly passed along.

This has caused the refman build time to go from 4min to 14min.

Perhaps related to https://github.com/coq/coq/issues/10694

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16495

### CODE REVIEW

**Comment by Alizter** [comment]
@SkySkimmer Could you put a dummy commit with "--display" like the one in https://github.com/coq/coq/pull/16491 so we can see what is actually being built in the doc jobs?

**Comment by Zimmi48** [comment]
The timings for the first commit are telling: we are back to just 4 minutes for the stdlib doc job and 6 minutes for the refman job.

**Comment by SkySkimmer** [comment]
For some reason it remade the .vo for files which have a Declare ML Module but not the others https://gitlab.com/coq/coq/-/jobs/3067406166

**Comment by Zimmi48** [comment]
This is surprising, but should not prevent merging this PR quickly since it already contributes to saving lots of build time.

**Review by Alizter — APPROVED** [review]
I agree

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
