### PR TITLE
Hack for fixing #10578: handle between the three main CoqIDE windows not always set at the expected position

### LINKED ISSUE #10578: Coqide 8.10 starts with incorrect size allocation
When starting Coqide, its layout is completely messed up until the first interaction of the user with the window (e.g., clicking the "forward step" button). Only the "messages" lower part is visible, neither script nor goals are visible. On 50 consecutive starts of Coqide, the initial layout was correct only three times.

The layout is governed by the following code in `ide/session.ml`:
```ocaml
    eval_paned#misc#connect#size_allocate
      ~callback:
      (let b = ref true in
       fun {Gtk.width=paned_width;Gtk.height=paned_height} ->
       if !b then begin
           eval_paned#set_position (paned_width / 2);
           state_paned#set_position (paned_height / 2);
           b := false
	 end)
```

The callback is properly called at startup, but its modification to the layout are not immediately taken into account. My guess is that this modification would cause a recursive computation of the layout if it was taken into account, so Gtk silently delays its application. As a consequence, it is only when the user starts interacting with the window that the new layout is actually taken into account.

### PR DESCRIPTION
**Pull request by herbelin**
See #10578: Apparently, on some distribution, the `size_allocate` event is not activated before the first key is pressed, so, we preventively set the position of the handle at an estimated value depending on the width and height of the whole coqide windows in the preferences.

Also removing a apparently useless setting of handle position to 1.

**Kind:** bug fix

Expected to close #10578

### CODE REVIEW

**Comment by silene** [comment]
This works for me.

Your comment, however, is inaccurate. The `size_allocate` event is processed at the right time. But, since the event is triggered and processed during the so-called `Layout` stage of Gtk, the `set_position` effects will only be taken into account during the next `Update` stage, which will only take place once the next `Events` stage has completed, i.e., after an external event has occurred. (The stage cycle is `Events`, `Update`, `Layout`, `Draw`.) That is my understanding of Gtk's main loop.

**Comment by Zimmi48** [comment]
@ppedrot If you merge this today, this should help to ensure that this can get in 8.10+beta3.

**Comment by silene** [comment]
Do we still need the callback? Now that we have a good enough approximation of the initial position of the sliders, the callback seems counterproductive. Indeed, even if the initial approximation is off by a few pixels, the users won't notice that the sliders are not perfectly centered, but they will notice the visual glitch caused by their magical movement by a few pixels after interacting with the window.

**Review by ppedrot — APPROVED** [review]
Hackish as possible, but seems reasonable enough.

**Comment by ppedrot** [comment]
@herbelin If you don't answer @silene before tonight, I'll merge the PR as-is so as to make it part of 8.10. We can still refine it later anyways.

**Comment by herbelin** [comment]
> Do we still need the callback? Now that we have a good enough approximation of the initial position of the sliders, the callback seems counterproductive. Indeed, even if the initial approximation is off by a few pixels, the users won't notice that the sliders are not perfectly centered, but they will notice the visual glitch caused by their magical movement by a few pixels after interacting with the window.

As far as the callback is currently implemented (i.e. called exactly once because of the boolean), I agree that it is not anymore relevant. I updated the PR.

[One may have wondered whether it had been worth instead removing the boolean and call the callback every time a resizing occurs (rather than letting gtk choose itself the new position of the handle) but that may not be what we want: if, say, I manually move the handle at the first quarter of the window, then resize the window, I probably don't want the handle to be put again automatically at the middle.]

> Hackish as possible

Indeed! The point is that this code seems to build the structure of the layout without knowing the exact size it'll have. So I don't know how to precompute a handle position (even if to be placed in the middle) while still remaining parametric over the dimensions.

**Review by silene — APPROVED** [review]
I suppose we could query Gtk for more precise information about the dimensions, but I don't think it is worth the effort. (And since Gtk4 implements a Cassowary-like layout algorithm, the point will be moot.)

**Pull request merged**
