### PR TITLE
micromega: addition of a Let binding in the proof format

### LINKED ISSUE #15481: Lia very slow with exponential
#### Description of the problem

While checking this [reply](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/.E2.9C.94.20specification.20of.20the.20lia.20tactic.20on.20non-linear.20problems/near/267709899).
I have been trying this
```coq
Goal forall x : Z, 0 <= x ^ 2.
```
`lia` proves it immediately but it gets slower and slower as the exponential grows.
When testing
```coq
Goal forall x : Z, 0 <= x ^ 32.
```
my computer fan started making funny noise :wink:. Where the blow-up comes from?

#### Coq Version

coq8.14.0

### PR DESCRIPTION
**Pull request by fajb**
`lia` pre-processing is performing interval analysis to bound monomials.
The current proof term generation is exponential in the exponent.
This PR introduces a let-binding for avoiding duplicating sub-proofs.

Fixes #15481

- [x] Added / updated **test-suite**.

### CODE REVIEW

**Comment by thery** [comment]
@fajb Great! Is there a standard way to benchmark this?

**Comment by fajb** [comment]
@thery there is nothing `lia` specific. The standard coq-bench is running...
https://gitlab.com/coq/coq/-/jobs/2040794499
This is quite bad for `coq-coqprime`: +15%. I'll investigate.

**Comment by ppedrot** [comment]
Why is this PR polluted by the ocamlformat nonsense? I thought we had deactivated that crap. If not, we should do it ASAP.

**Comment by fajb** [comment]
Maybe this is due to my local config. I'll look about it.

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                    coq-core │  102.03   102.93  -0.87 │   373865699469    373867829120  -0.00 │   433330165740    433394413307  -0.01 │  272876   272996  -0.04 │   1    0      nan │
│        coq-mathcomp-algebra │   65.92    66.28  -0.54 │   287985781905    289932068208  -0.67 │   397574090249    397586552972  -0.00 │  555504   554244   0.23 │   0    0      nan │
│                   coq-verdi │   49.70    49.91  -0.42 │   216048552254    216713967176  -0.31 │   322025375777    322096736361  -0.02 │  832468   832320   0.02 │   0    0      nan │
│                  coq-flocq3 │   78.83    79.13  -0.38 │   343790737069    344384165150  -0.17 │   455131225573    455076252720   0.01 │  987712   989540  -0.18 │   0    0      nan │
│         coq-metacoq-erasure │   66.38    66.63  -0.38 │   285707812180    286388053992  -0.24 │   433278956027    433292416016  -0.00 │ 1079372  1079616  -0.02 │   0    0      nan │
│               coq-fiat-core │   55.32    55.51  -0.34 │   231879963581    232440508972  -0.24 │   321950079407    321985968477  -0.01 │  475072   475896  -0.17 │   3    3     0.00 │
│       coq-engine-bench-lite │  183.15   183.73  -0.32 │   769627382231    772147994017  -0.33 │  1487447856109   1487190938016   0.02 │ 1172748  1172756  -0.00 │   0    0      nan │
│                    coq-hott │  157.95   158.40  -0.28 │   684793778172    686584761045  -0.26 │  1072379448502   1072351346549   0.00 │  570636   569804   0.15 │   0    0      nan │
│                coq-rewriter │  379.57   380.46  -0.23 │  1656228511094   1659073570558  -0.17 │  2726308159739   2726274464183   0.00 │ 1057900  1057892   0.00 │  16   23   -30.43 │
│               coq-perennial │ 4095.02  4100.65  -0.14 │ 17910576396238  17929431692285  -0.11 │ 29804868822611  29807442939435  -0.01 │ 2592652  2593412  -0.03 │   0    1  -100.00 │
│                 coq-bignums │   28.85    28.88  -0.10 │   125954084022    126134409287  -0.14 │   172397572151    172265100708   0.08 │  464536   464684  -0.03 │   0    0      nan │
│    coq-metacoq-translations │   20.33    20.35  -0.10 │    88157637934     87850868781   0.35 │   154424377922    154380243712   0.03 │  949124   949020   0.01 │   1    0      nan │
│                  coq-geocoq │  715.36   715.85  -0.07 │  3121345052759   3125676401993  -0.14 │  4944083496355   4944224089414  -0.00 │ 1073916  1074160  -0.02 │   8    2   300.00 │
│          coq-mathcomp-field │  115.66   115.73  -0.06 │   507086060710    506931255136   0.03 │   837455834443    837502980786  -0.01 │  653188   653220  -0.00 │   0    0      nan │
│           coq-iris-examples │  438.71   438.94  -0.05 │  1914883628064   1915944769435  -0.06 │  2916322752411   2916112568744   0.01 │ 1170592  1170516   0.01 │   0    0      nan │
│                 coq-unimath │ 4067.15  4068.49  -0.03 │ 17808333920465  17814731135550  -0.04 │ 35865455598855  35864955159221   0.00 │ 3791776  3793308  -0.04 │   9    0      nan │
│      coq-mathcomp-odd-order │  571.52   571.57  -0.01 │  2505476193305   2505500726546  -0.00 │  4255989567366   4255964324531   0.00 │  932476   932980  -0.05 │   0    0      nan │
│            coq-fiat-parsers │  344.93   344.88   0.01 │  1490018915244   1491522427333  -0.10 │  2444233890097   2445022597551  -0.03 │ 2785032  2785088  -0.00 │   0    6  -100.00 │
│                    coq-corn │  785.19   785.04   0.02 │  3428913252652   3427465004369   0.04 │  5276348630454   5276204235600   0.00 │  871636   873024  -0.16 │   0    0      nan │
│       coq-mathcomp-solvable │   90.88    90.82   0.07 │   397868009375    397481505556   0.10 │   611112742767    611009925975   0.02 │  668344   668332   0.00 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.49    24.47   0.08 │   107118890335    106721814488   0.37 │   156007511109    155944288903   0.04 │  487832   485800   0.42 │   0    0      nan │
│                   coq-color │  217.08   216.90   0.08 │   940405019169    940738864155  -0.04 │  1319817150350   1319919256642  -0.01 │ 1142096  1139004   0.27 │   0    2  -100.00 │
│      coq-mathcomp-character │   79.12    79.05   0.09 │   346463890326    346502816697  -0.01 │   525757515985    525804107893  -0.01 │  730724   729936   0.11 │   0    0      nan │
│               coq-fourcolor │ 1510.31  1508.42   0.13 │  6607066438282   6597077450742   0.15 │ 12083085235009  12082792777587   0.00 │  724896   724884   0.00 │   0    0      nan │
│         coq-category-theory │ 1670.22  1668.07   0.13 │  7315828539979   7305828738286   0.14 │ 15270038238019  15270067718473  -0.00 │ 1476748  1476732   0.00 │   4    0      nan │
│             coq-fiat-crypto │ 2917.29  2913.21   0.14 │ 12729832306986  12714022679323   0.12 │ 23283896920633  23282849041649   0.00 │ 3843832  3843892  -0.00 │  87  109   -20.18 │
│  coq-performance-tests-lite │  801.45   800.25   0.15 │  3487797043638   3483327713582   0.13 │  5912573783531   5913047195382  -0.01 │ 1822004  1822004   0.00 │   3    0      nan │
│        coq-metacoq-template │   76.28    76.12   0.21 │   326341022588    325710189430   0.19 │   490368683906    490372893464  -0.00 │  710196   705896   0.61 │   0    9  -100.00 │
│     coq-metacoq-safechecker │  208.52   208.05   0.23 │   909500733503    907488240605   0.22 │  1210432755801   1210554596693  -0.01 │ 1115028  1117988  -0.26 │   8    1   700.00 │
│                     coq-vst │ 1098.30  1095.53   0.25 │  4793450509550   4785853931872   0.16 │  7796596227547   7796545149315   0.00 │ 2137172  2137040   0.01 │   3    5   -40.00 │
│ coq-rewriter-perf-SuperFast │  947.02   944.19   0.30 │  4139198308015   4124693425557   0.35 │  7160938574238   7160436080627   0.01 │ 1216184  1215328   0.07 │  29    0      nan │
│                coq-compcert │  289.31   288.37   0.33 │  1257722192059   1254749758738   0.24 │  1876871070530   1877003017524  -0.01 │ 1099144  1097716   0.13 │   0    0      nan │
│           coq-metacoq-pcuic │  756.23   753.35   0.38 │  3292524968709   3280066609290   0.38 │  4738162932294   4738395246068  -0.00 │ 1247876  1248216  -0.03 │   5   14   -64.29 │
│              coq-verdi-raft │  582.81   580.52   0.39 │  2544178412654   2535923661790   0.33 │  3941194178188   3941088080051   0.00 │ 1224940  1225908  -0.08 │   0    0      nan │
│              coq-coquelicot │   35.71    35.55   0.45 │   153211231646    152957088489   0.17 │   201870849695    201762358043   0.05 │  745716   747152  -0.19 │  66    0      nan │
│                 coq-coqutil │   36.25    36.04   0.58 │   155429211706    155755196395  -0.21 │   207859094740    207761665668   0.05 │  601848   600792   0.18 │   4    0      nan │
│      coq-mathcomp-ssreflect │   27.28    27.11   0.63 │   118294779830    118044078291   0.21 │   148233533128    148213920433   0.01 │  533860   532528   0.25 │   0    0      nan │
│            coq-math-classes │   93.55    92.93   0.67 │   405332898399    402930992537   0.60 │   568516805595    568516953674  -0.00 │  495800   495744   0.01 │   0    0      nan │
│                  coq-stdlib │  421.50   416.01   1.32 │  1484044102396   1469929591626   0.96 │  1409288600713   1410014358108  -0.05 │  599276   597784   0.25 │   0    0      nan │
│                coq-coqprime │  216.91   188.45  15.10 │   948949604085    824076131702  15.15 │  1785161424209   1554905811022  14.81 │  906192   827136   9.56 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
~~~

**Comment by fajb** [comment]
```┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│               coq-fiat-core │    0.70     0.71  -1.41 │     2236821535      2243538525  -0.30 │     3815899498      3838449167  -0.59 │   80056    79864   0.24 │   2    0      nan │
│                  coq-flocq3 │   78.98    79.77  -0.99 │   343926208728    346845454903  -0.84 │   456918477034    456811244674   0.02 │  990392   987648   0.28 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  949.68   955.08  -0.57 │  4149437911506   4172889842981  -0.56 │  7215539706776   7214456472400   0.02 │ 1220088  1220352  -0.02 │  11    0      nan │
│              coq-coquelicot │   35.44    35.64  -0.56 │   153379146715    152995988045   0.25 │   203811818237    203781801699   0.01 │  748336   749500  -0.16 │ 106    0      nan │
│                coq-rewriter │  385.74   387.33  -0.41 │  1682111409403   1689225023012  -0.42 │  2779961023127   2780137051008  -0.01 │ 1059220  1060832  -0.15 │  34   38   -10.53 │
│       coq-mathcomp-solvable │   90.63    90.95  -0.35 │   397258622177    397978360914  -0.18 │   611890340776    612067138877  -0.03 │  659704   658376   0.20 │   0    0      nan │
│                     coq-vst │ 1090.13  1093.95  -0.35 │  4760279540496   4777997084724  -0.37 │  7813898423651   7813819425456   0.00 │ 2069380  2069392  -0.00 │   3    0      nan │
│                 coq-coqutil │   36.00    36.11  -0.30 │   155824397151    154863733505   0.62 │   211574366558    211598295708  -0.01 │  602476   601732   0.12 │   4    0      nan │
│                coq-compcert │  288.74   289.54  -0.28 │  1255838917000   1259292848711  -0.27 │  1889488299201   1889668839788  -0.01 │ 1099072  1103432  -0.40 │   0    0      nan │
│                    coq-corn │  782.56   783.96  -0.18 │  3416406643271   3422528664338  -0.18 │  5291970234886   5291977110285  -0.00 │  874136   874836  -0.08 │   0    0      nan │
│           coq-iris-examples │  433.30   433.98  -0.16 │  1891717580441   1893974490869  -0.12 │  2908200286265   2908223772937  -0.00 │ 1166180  1166068   0.01 │  28    1  2700.00 │
│               coq-perennial │ 4089.85  4095.26  -0.13 │ 17883706796107  17903925179262  -0.11 │ 29822274648569  29810091612982   0.04 │ 2572844  2579156  -0.24 │   0    0      nan │
│                  coq-stdlib │  413.58   414.08  -0.12 │  1468587742747   1468854983313  -0.02 │  1413879893993   1414340614092  -0.03 │  607612   607644  -0.01 │   0    0      nan │
│              coq-verdi-raft │  581.08   581.64  -0.10 │  2536702206564   2540084519229  -0.13 │  3944627019234   3944450532510   0.00 │ 1230276  1233688  -0.28 │   0    0      nan │
│               coq-fourcolor │ 1515.89  1517.23  -0.09 │  6630066037729   6636664362414  -0.10 │ 12088047081270  12087866051313   0.00 │  725268   724844   0.06 │   0    0      nan │
│                  coq-geocoq │  715.59   716.20  -0.09 │  3120021922872   3123099995445  -0.10 │  4964652154788   4964491087189   0.00 │ 1075692  1075400   0.03 │   5    0      nan │
│         coq-category-theory │ 1668.55  1668.58  -0.00 │  7306633188025   7308646435137  -0.03 │ 15276456898980  15276344330390   0.00 │ 1477568  1477692  -0.01 │   0    0      nan │
│      coq-mathcomp-odd-order │  568.31   568.23   0.01 │  2491011800871   2490900017074   0.00 │  4257447557984   4257641788779  -0.00 │  931800   933212  -0.15 │   0    0      nan │
│           coq-metacoq-pcuic │  751.12   751.00   0.02 │  3269775651027   3268367322044   0.04 │  4740633403604   4740771351247  -0.00 │ 1230060  1229368   0.06 │   0    0      nan │
│                    coq-hott │  158.11   158.07   0.03 │   685842979038    685350432202   0.07 │  1077662995367   1077578320824   0.01 │  572476   570972   0.26 │   0    0      nan │
│  coq-performance-tests-lite │  799.90   799.18   0.09 │  3481864665872   3478722747931   0.09 │  5930903896822   5932119954860  -0.02 │ 1824544  1824360   0.01 │   2    0      nan │
│                 coq-unimath │ 4083.10  4078.90   0.10 │ 17873795421096  17855687426630   0.10 │ 35873301178951  35873580530175  -0.00 │ 3321840  3322592  -0.02 │  11    3   266.67 │
│                   coq-color │  216.71   216.48   0.11 │   939882337510    938119260590   0.19 │  1336422732057   1336328081392   0.01 │ 1137468  1134168   0.29 │   0    0      nan │
│             coq-fiat-crypto │ 2922.81  2918.86   0.14 │ 12750210205966  12736318328621   0.11 │ 23327351457268  23321981231321   0.02 │ 3850684  3849184   0.04 │  92  117   -21.37 │
│        coq-metacoq-template │   75.72    75.57   0.20 │   323877679401    324155795932  -0.09 │   493972888784    494011427068  -0.01 │  701904   698164   0.54 │   0    0      nan │
│          coq-mathcomp-field │  115.61   115.34   0.23 │   506852343552    505550230489   0.26 │   838051169927    838047688048   0.00 │  651212   651688  -0.07 │   0    0      nan │
│            coq-math-classes │   93.88    93.64   0.26 │   407036099152    405743954938   0.32 │   574022474826    574021341932   0.00 │  495928   495496   0.09 │   0    0      nan │
│        coq-mathcomp-algebra │   66.11    65.89   0.33 │   289085052245    288188994594   0.31 │   398866679681    398956649644  -0.02 │  556376   556388  -0.00 │   0    0      nan │
│       coq-engine-bench-lite │  182.04   181.41   0.35 │   764703240509    762650260613   0.27 │  1500970570550   1490513437137   0.70 │ 1173428  1173668  -0.02 │   0    0      nan │
│      coq-mathcomp-ssreflect │   27.01    26.91   0.37 │   117565188340    117394431804   0.15 │   149469599595    149531290127  -0.04 │  531864   532668  -0.15 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.48    24.38   0.41 │   106801665525    106510722936   0.27 │   156435167439    156492056066  -0.04 │  484804   483748   0.22 │   0    0      nan │
│                   coq-verdi │   49.92    49.68   0.48 │   216355273551    215249490436   0.51 │   324241174222    324195458010   0.01 │  843288   837720   0.66 │   0    0      nan │
│      coq-mathcomp-character │   78.91    78.44   0.60 │   345757618480    343799076187   0.57 │   526370760323    526349871731   0.00 │  730796   733156  -0.32 │   0    0      nan │
│                 coq-bignums │   29.06    28.79   0.94 │   126468317545    125685553304   0.62 │   173307349355    173257775227   0.03 │  466632   466464   0.04 │   0    0      nan │
│                    coq-core │  104.28   103.31   0.94 │   382454649809    380792111525   0.44 │   440809973906    440730563962   0.02 │  274700   273980   0.26 │   2    0      nan │
│                coq-coqprime │  191.61   188.87   1.45 │   838223673217    826209014790   1.45 │  1575002887485   1557035455126   1.15 │  907668   830504   9.29 │   0    0      nan │
│            coq-fiat-parsers │    0.74     0.67  10.45 │     2256727940      2260493045  -0.17 │     3858476527      3871880163  -0.35 │   79956    79928   0.04 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Comment by fajb** [comment]
In the code, I do not see strong reasons for performance regression.
Maybe @ppedrot can pinpoint a culprit...
If there is no obvious one, I think this is worth merging as is.

**Comment by ppedrot** [comment]
Where do you see a performance regression? The apparent coqprime slowdown is well within noise range, it's usual for this dev to have up to a 4% noise.

**Review by ppedrot — APPROVED** [review]

**Comment by thery** [comment]
Could we used the cache produced by lia to get a test that reflects more directly the impact of change? The cache generated by lia on Coqrime is about 14M!!

**Comment by ppedrot** [comment]
I don't know how to do that.

**Comment by ppedrot** [comment]
Let's merge anyways, this looks in a good shape. If ever we want to refine the patch we can do this later.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
