### PR TITLE
Fixes #12322: anomaly when printing "fun" binders with implicit types

### LINKED ISSUE #12322: Heisenanomaly: File "interp/constrextern.ml", line 844, characters 9-15: Assertion failed
#### Description of the problem

@llelf Antonio Nikishaev [said on Zulip](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/%28no.20topic%29/near/197471798)
> I noticed (while working on coq/coq#11992) that there's a crash in fiat_parsers CI: "File "interp/constrextern.ml", line 844, characters 9-15: Assertion failed.", even when CI is passing (don't ask me, no idea :) — e.g. grep for Anomaly in https://travis-ci.org/github/mit-plv/fiat/jobs/683994964 (web ui) / https://api.travis-ci.org/v3/job/683994964/log.txt (raw text). Is that a known Coq bug?

Note that this is
https://github.com/coq/coq/blob/ed0803efd1c8418c54dcde1255db110e1f2e648d/interp/constrextern.ml#L840-L844

Interestingly, this seems to reliably occur on the first invocation of coqc on my file, but when I invoke it a second time, it succeeds.  And it doesn't happen on Coq's CI.

#### Coq Version

master (ed0803efd1c8418c54dcde1255db110e1f2e648d)

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

Anomaly was introduced in #11261: a pattern-matching clause was missing.

The anomaly triggered in configurations like `fun (x:T) y =>` (even in the absence of `Implicit Types`).

Fixes / closes #12322

- [X] Added / updated test-suite
- [X] Entry added in the changelog

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, thanks @herbelin

**Comment by JasonGross** [comment]
Thanks!  I guess this was triggered in conjunction with the Ltac Profiler and was only sometimes visible because only sometimes would the relevant bit of syntax show up in the profile

**Comment by ejgallego** [comment]
By the way @JasonGross coq-tools failed spuriously 2 times for the CI of this PR.

**Comment by JasonGross** [comment]
@ejgallego thanks, can you link me to the logs of the failed jobs so I can investigate what's going on?

**Comment by ejgallego** [comment]
> @ejgallego thanks, can you link me to the logs of the failed jobs so I can investigate what's going on?

Looks like some kind of timing issue? Logs are:
- https://gitlab.com/coq/coq/-/jobs/554599727
- https://gitlab.com/coq/coq/-/jobs/551768190

**Pull request merged**
