### PR TITLE
Timing on ci via coq_makefile for various projects

### PR DESCRIPTION
**Pull request by JasonGross**
This is on top of #745.  

HoTT, which builds it's own makefile, and supports timing data, makes
use of its own timing script.

Everything else that uses `coq_makefile` goes through the coq-bundled timing scripts.  I haven't touched the projects that don't use `coq_makefile`.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
[I only reviewed the part new from #746]

I am OK with this, even if it adds a bit too much boilerplate, ideally we should be able to get timings in a simpler way just by modifying some env var that makes coq output the timing data and a global travis pass that could aggregate it.

**Comment by JasonGross** [comment]
> ideally we should be able to get timings in a simpler way just by modifying some env var that makes coq output the timing data and a global travis pass that could aggregate it

If you can figure out a way to get travis (or `make`) to dump the build log to a file based on an env var, then we can do this.  We could probably hook something up in `Makefile.ci`... let me try that

**Comment by JasonGross** [comment]
@ejgallego Now the boilerplate lives in `Makefile.ci`.  Is this way of doing it better?

**Comment by ejgallego** [comment]
@JasonGross oh interesting; I think I like it better, hopefully we could even output the timing data as a build artifact some day. I guess you could just globally set `TIMED=1` in travis, any drawback to do it?

**Comment by JasonGross** [comment]
> I guess you could just globally set TIMED=1 in travis, any drawback to do it?

None that I see, unless some of the `coq_makefile` test-suite tests would break from inheriting `TIMED=1`. 
 I'm not sure where to set it, though; where should it be set?

> hopefully we could even output the timing data as a build artifact some day

Yeah, then you want `TIMED=1` (per-file) and `TIMING=1` (per-line); the python script can dump the info to a file as well as printing it; just pass `time-of-build-pretty.log` and `-` as additional arguments.  Idk how to get the files off of travis, though.

**Comment by ejgallego** [comment]
> None that I see, unless some of the coq_makefile test-suite tests would break from inheriting TIMED=1.
> I'm not sure where to set it, though; where should it be set?

I guess in the global `env` section, but not sure if the makefile will pick it up correctly.

I hope I get some time to think about this a bit for 8.8, meanwhile, please take this infrastructure in the direction that better serves you.

My ideal vision on this is that we should be able to instrument any coq development without having to teach it about instrumentation, and hopefully we can set a kind of standard format to do that.

[Hopefully we can do the same for slicing]

**Comment by Zimmi48** [comment]
Why the change of base branch? We are trying to get rid of all PRs targeting v8.7 to allow a switch to a backporting policy.

**Comment by Zimmi48** [comment]
And just so that this is clear, this PR would totally qualify for a backport as it is only about infrastructure.

**Comment by JasonGross** [comment]
Change of base to v8.7 because the timing scripts were merged into v8.7, this is on top of the timing scripts, and v8.7 hasn't yet been merged into master.  When v8.7 gets merged into master, we can change the base of this to master.

**Comment by Zimmi48** [comment]
@JasonGross v8.7 has been merged into master and will not be merged again. So from now on, only PRs specific to the v8.7 branch should target the v8.7 branch and all other PRs should target the master branch, to be later backported.

**Pull request merged**
