### PR TITLE
Bench: use 4.14.1 by default

### LINKED ISSUE #18493: bench not installable packages
The following packages are currently broken in the bench:
- metacoq-translations: reference to removed file `Even` in `param_cheap_packed` https://github.com/MetaCoq/metacoq/pull/1041
- mathcomp-odd-order: some dependency resolution error, probably related to https://github.com/coq/coq/pull/18449#issuecomment-1880746147
  >I think the problem is that the bench runs ocaml 4.09 but coq-elpi.dev requires >= 4.10 coq/opam@a114c29/extra-dev/packages/coq-elpi/coq-elpi.dev/opam#L14
(and non-dev coq-elpi versions have upper bounds on the coq dependency)

  (for the same reason, the bench is testing mathcomp.1.dev packages, and there is no odd-order.1.dev)
- coquelicot: tries to install 3.4.0 instead of dev -> reference to removed `minus_Sn_m`
  probably because of mathcomp 2 being unavailable
- fourcolor: failed dependency resolution, again probably because of mathcomp 2

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix https://github.com/coq/coq/issues/18493 ?

### CODE REVIEW

**Comment by SkySkimmer** [comment]
why is flambda such a pain to enable
let's forget about flambda for this PR

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Seems to work, let's try a full bench
@coqbot bench

**Review by gares — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
