### PR TITLE
[vernac] Remove deprecated function.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
This is going to need overlays

**Comment by SkySkimmer** [comment]
Does this PR have a future?

**Comment by ejgallego** [comment]
> Does this PR have a future?

Yes @SkySkimmer , but it is looking a bit far in my TODO list sorry :/

**Comment by ejgallego** [comment]
Seems to work.

**Pull request merged**
