### PR TITLE
Avoid generated names for html pages of the reference manual (bug #4742).

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by Zimmi48** [comment]
It seems that 8.7 is a good time to fix this bug given how we have added / removed some chapters and links will be broken anyways. A question though: does this change preserve some limited compatibility? (Do number-based links continue to work?)

**Comment by silene** [comment]
> does this change preserve some limited compatibility? (Do number-based links continue to work?)

No (no). Anyway, I don't think it makes sense to ensure this kind of compatibility at the level of Coq sources. It will be much more effective to put a `.htaccess` file on the website to properly redirect the old addresses toward the new ones.

**Comment by Zimmi48** [comment]
> It will be much more effective to put a .htaccess file on the website to properly redirect the old addresses toward the new ones.

Good point.

**Comment by Zimmi48** [comment]
Who will be taking care of the `.htaccess`?

**Comment by Zimmi48** [comment]
If no one has this on their todo-list, this is going to be forgotten.

**Pull request merged**
