### PR TITLE
Camlp5 safe API strikes back

### PR DESCRIPTION
**Pull request by ppedrot**
Revival of the cleaning part of #8923 and further removal of all unsafe camlp5 exported API.

### CODE REVIEW

**Comment by gares** [comment]
Can you explain, high level, which are the unsafe API that gets removed? The patch does many things, eg `Gram.` disappears, but this is just distracting. I see a `delete_rule` gone. Is that it?

**Comment by ppedrot** [comment]
The important commit is the last one, it removes the type-unsafe API from our grammar engine. Internally the latter still uses unsafe casts, but as long as we trust its implementation this means we statically ensure that no undefined behaviour could happen by merely parsing stuff.

**Review by ejgallego — APPROVED** [review]
Very good; note the need for overlays tho. Once these are ready I will merge.

**Comment by ejgallego** [comment]
You can test `dev/tools/create-overlays.sh ppedrot 9051 equations ltac2` if you want @ppedrot ?

**Comment by ppedrot** [comment]
That's very strange, I cannot reproduce the error locally. I rebased to see whether that was some quirk, but otherwise I guess something is wrong.

**Comment by ppedrot** [comment]
OK, that was me being stupid. Should hopefully work now.

**Pull request merged**
