### PR TITLE
[configure] check that zarith dev files are available

### LINKED ISSUE #12951: configure succeeds but make fails when libzarith-ocaml but not libzarith-ocaml-dev is installed on ubuntu
#### Description of the problem

#12939 is not sufficient, see https://github.com/HoTT/HoTT/pull/1392/checks?check_run_id=1048236906 where [`./configure` says](https://github.com/HoTT/HoTT/pull/1392/checks?check_run_id=1048236906#step:9:130) :
```
You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have native-code compilation. Good!
You have the Zarith library installed. Good!
LablGtk3 or LablGtkSourceView3 not found:
=> no CoqIde will be built.

  Architecture                : Linux
  Sys.os_type                 : Unix
  Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath /usr/local/lib/coq/kernel/byterun
  Other bytecode link flags   : 
  OCaml version               : 4.05.0
  OCaml binaries in           : /usr/bin/
  OCaml library in            : /usr/lib/ocaml
  OCaml flambda flags         : 
  Native dynamic link support : true
  CoqIde                      : no
  Documentation               : None
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
```
but [`make coqocaml` fails with](https://github.com/HoTT/HoTT/pull/1392/checks?check_run_id=1048236906#step:9:367)
```
OCAMLC    tools/coqdep.ml
OCAMLOPT  tools/coqdep.ml
OCAMLBEST -o bin/coqdep
File "_none_", line 1:
Error: Cannot find file /usr/lib/ocaml/zarith/zarith.cmxa
Makefile.build:501: recipe for target 'bin/coqdep' failed
```

cc @SkySkimmer 

#### Coq Version

94d9fe2b6cb06fe7f862683d8337433e18314001

### PR DESCRIPTION
**Pull request by gares**
Fix #12951

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM

**Review by silene — COMMENTED** [review]
I am testing the exact same two files for Why3, so that part is fine. But I find it quite strange that you test for the existence of these files before having even verified that `ocamlfind` actually returned something meaningful. Perhaps you could turn the test into a boolean function rather than a boolean value? (Or just inline the conditional into the `when` clause.)

**Comment by ejgallego** [comment]
Indeed, the refinement Guillaume proposes makes sense. I'm too worried about it tho as we hope to rewrite configure soon and use a principled API to query ocamlfind.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
