### PR TITLE
[micromega] primitive support for boolean operators 

### PR DESCRIPTION
**Pull request by fajb**
- Support for andb, orb, eqb, implb
- Support for Z.{eqb, leb, ltb, geb, gtb}

### CODE REVIEW

**Comment by JasonGross** [comment]
It would be nice if things like `Nat.eqb` could be handled via `zify`

**Comment by JasonGross** [comment]
Also, nice!  I look forward to when I no longer have to maintain my own tactics for reasoning about boolean equality in Z

**Comment by fajb** [comment]
@JasonGross thanks. The idea would be for zify  to map `Nat.eqb` to `Z.eqb`.
That is on the roadmap and zify has the infrastructure for that.

With Coq master, there is already some support for booleans `Require Import ZifyBool` where booleans are encoded as integers 0 and 1 and `Nat.eqb` is dealt with. The downside is that the encoding might not scale.

With this PR, the overhead would be minimum.

**Comment by maximedenes** [comment]
What's the link between the support of boolean operators and the efficiency fixes? If possible, it would be better to separate them, but maybe they are fundamentally related?

**Comment by fajb** [comment]
This is because I am mono-task. 
Splitting will be painful but I guess doable if needed.

**Comment by Zimmi48** [comment]
The main advantage of splitting would be to allow backporting fixes to v8.11. But it's up to you.

**Comment by samuelgruetter** [comment]
In general, splitting two features has the advantage that it allows to test the performance implications of each feature separately. But I don't have enough insight in this specific case to judge whether it would be worth doing here.

**Review by ejgallego — CHANGES_REQUESTED** [review]
Indentation and code formatting of ML files does not conform to Coq style and it is not consistent with itself.

**Comment by fajb** [comment]
@ejgallego is-there a tool to ensure formatting style ?

**Comment by ejgallego** [comment]
> @ejgallego is-there a tool to ensure formatting style ?

As of today the quasi standard indentation style used in Coq is the default provided by `ocp-indent` [integrates well with tuareg and vim]

For more comprehensive automatic formatting support you could use `ocamlformat`, which if you want you could enable only for micromega.

See also https://github.com/coq/coq/issues/9572

**Comment by fajb** [comment]
thanks @ejgallego . I'll look into it.

**Comment by fajb** [comment]
@maximedenes , @Zimmi48 : split into 2 commits. Support for boolean operators is actually just disabled in 1st commit.
@ejgallego I have set up ocamlformat. I hope this solves the formatting issues.

**Comment by ejgallego** [comment]
> @ejgallego I have set up ocamlformat. I hope this solves the formatting issues.

Oh that's great; if you think it works for you indeed we could enable the dune support for the plugin. What options did you pass to it?

**Comment by fajb** [comment]
I passed the options you were proposing. To me, it looks ok but as you probably noticed I do not have strong opinions on coding styles. 

module-item-spacing=compact
sequence-style=terminator
cases-exp-indent=2
field-space=loose

**Comment by ejgallego** [comment]
> I passed the options you were proposing. To me, it looks ok but as you probably noticed I do not have strong opinions on coding styles.

Thanks, I will add support for this then in another PR so micromega will be always kept consistent.

**Comment by maximedenes** [comment]
> This is because I am mono-task.
> Splitting will be painful but I guess doable if needed.

I think we should really split, especially because the two contributions are of a different nature: one is a fix/improvement, and the other a new feature.

Can you say why you expect the splitting to be painful? It will make it easier for me to know where I can help.

**Comment by maximedenes** [comment]
> Indentation and code formatting of ML files does not conform to Coq style

As a side note, we never decided there was such a thing as a "Coq style" for code formatting. In particular, I don't think we should put any hard requirements on contributors. Of course, picking one consistent style is always a good idea.

**Comment by fajb** [comment]
@denes  I kind of did the splitting. The feature is disabled in first commit.

**Comment by fajb** [comment]
Regarding the CI:
- for pkg-nix, the failure seems unrelated
- for flocq, the bug fix improves lia a bit in corner cases.
It is solved by https://gitlab.inria.fr/flocq/flocq/merge_requests/9

**Comment by maximedenes** [comment]
> I kind of did the splitting. The feature is disabled in first commit.

Let's rather do it properly, otherwise the first commit introduces dead code. In fact, I'm pretty sure this should be two separate PRs.

If there's any difficulty in doing a proper split, I'd be happy to help.

**Comment by fajb** [comment]
I see a few hours of work. I agree that I have introduced some dead code.

**Comment by maximedenes** [comment]
About the formatting, I now see a lot of formatting-related changes that are mixed with real changes. Certainly not an improvement, as it makes reviewing much harder. @ejgallego maybe you should explain how to restrict the automatic formatting to pieces of code that are actually touched.

**Comment by Zimmi48** [comment]
> how to restrict the automatic formatting to pieces of code that are actually touched

There is no way to do that with `ocamlformat`. The point of `ocamlformat` would rather be to format once and to keep the formatting in check forever. The way to fix this in this particular case would be to apply `ocamlformat` as a separate commit and only after copy back the current state to obtain the new diff, and a separate commit.

**Pull request closed without merging**
