### PR TITLE
Cleanup the Hints API

### PR DESCRIPTION
**Pull request by ppedrot**
This PR introduces a bunch of cleanups around the Hints API, including likely bugfixes and static invariants.

Overlays:
- https://github.com/mit-plv/fiat/pull/40

### CODE REVIEW

**Comment by ppedrot** [comment]
CI failure is spurious, metacoq is broken upstream.

**Comment by ppedrot** [comment]
@herbelin do you want to assign?

**Review by herbelin — APPROVED** [review]
By curiosity, why removing `make_extern` from the API?

Leaving a few days for comments, and will merge.

**Comment by ppedrot** [comment]
I want to reduce the exposed surface of the API in order to change the representation of hint databases. There are quite a few invariants that should be enforced statically for that.

**Comment by herbelin** [comment]
And will be your alternative for `make_extern`?

**Comment by ppedrot** [comment]
The point is that you're not supposed to use those low-level primitives, every hint extension should go through the vernac command.

**Pull request merged**
