### PR TITLE
[ssr] notation to seed names at inductive declaration time

### PR DESCRIPTION
**Pull request by gares**
Using `=>[^ seed]` with eliminators is boring because the only way to attach names to all
hypotheses is to spell out explicitly the type of the eliminator, and update it every time you
update the inductive. Moreover this eliminator type is bizarre, since non dependent arguments
have to be quantified with a forall, rather than an arrow, just to give their name seed.

This PR adds a notation to let one annotate non dependent arguments of inductive types
with one or more names (more names are necessary if the argument is recursive, hence it
will come with an induction hypothesis).

Example: when block introduction is used after an elimination of an inductive with 
a constructor annotated as follows, one gets in the context of the corresponding goal
hypotheses names after the seeds:  `e u v pu tu mu tv tu' tv' p eu ev cap_u trm_u trm_v typ` and `IHp`, see the `__` separator to give two seeds in the last premise.

```coq
  | TyOutput (e : environment fv) u v pu tu mu tv tu' tv' p :

      e u = (Chan mu pu tu)                              # eu
      e v = tv                                           # ev
      {pu = Up} + {pu = UpDown}                          # cap_u
      type_remove (Chan mu pu tu) (Chan mu Up tu) tu'    # trm_u
      type_remove tv tu tv'                              # trm_v
      typechecks (update v tv' (update u tu' e)) p       # typ__IHp
      (*-----------------------------------------------*)
      typechecks e (Output u v p)
```
Note that, in each line `# name` plays the role of `->` (but also carrier name seeds).

Feedback on the notation is particularly welcome, I picked `#` because it reminds me of a
comment, but I'm open to other options, eg `,#` may be better at avoid conflicts.

**Kind:** feature
- [x] Added / updated test-suite
- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by gares** [comment]
CC @CohenCyril @charguer could be interested in commenting this features

**Comment by CohenCyril** [comment]
@gares interesting, I do not know what to thing...
do you think it is too heavy to write:
```coq
  | TyOutput (e : environment fv) u v pu tu mu tv tu' tv' p :

      (eu       : e u = (Chan mu pu tu))
      (ev       : e v = tv)
      (cap_u    : {pu = Up} + {pu = UpDown})
      (trm_u    : type_remove (Chan mu pu tu) (Chan mu Up tu) tu')
      (trm_v    : type_remove tv tu tv')
      (typ__IHp : typechecks (update v tv' (update u tu' e)) p)
      (*-----------------------------------------------*)
      typechecks e (Output u v p)
```
?

**Comment by gares** [comment]
Actually there are 2 questions. one is the (optional) Notation. One is the convention about the separator, that needs to be understood by elim/ipats.

The notation can be defined in a user  file, so maybe we should just focus on the __ thing

**Comment by CohenCyril** [comment]
@gares I do not understand why we need to seeds, could you provide an example?

**Comment by gares** [comment]
Think at nat: S has one argument but you need to name 2 in the inductive. case

**Comment by charguer** [comment]
> do you think it is too heavy to write:  [...]  `(x : foo)`  vs  `x  # foo`

I totally understand the motivation. 

Yet, as @CohenCyril suggests, I think you'll have a hard time convincing people that it is a good idea to reserve a symbol and introducing and introducing a new piece of syntax, which would yet adds to the already-huge cost-of-entry into the system for beginners.

Btw, in  ` | TyOutput (e : environment fv) u v pu tu mu tv tu' tv' p : forall`
I'm not sure why you need to have a `forall` there, can't you simply continue with the list of bindings until reaching the conclusion?

>  the __ separator to give two seeds in the last premise

As far as I know, the only case where you need two names is when you have an induction hypotheses. For all practical purposes that I can think of, I would always want the name of that induction hypotheses to be of the form "IHfoo" for an hypothesis of name "foo". So, would it be a problem to just hard code this pattern? (i.e. `"IH" ^ name`). 

> Moreover this eliminator type is bizarre, since non dependent arguments have to be quantified with a forall, rather than an arrow, just to give their name seed.

I just though of an alternative solution. If you extend the "Argument" command with a special token, say `>`, to mean "skip all dependent variables", then you could attach a posteriori names for your hypotheses. In your example: `Argument TyOutput > eu ev cap_u trm_u trm_v typ`.

The main drawback of this approach is the distance between the type of the hypothesis and the place where its name is provided. But perhaps it's better than nothing?

**Comment by gares** [comment]
> So, would it be a problem to just hard code this pattern? (i.e. `"IH" ^ name`).

It is probably doable, elim already "guesses" (proper) subgoals by looking for P (the predicate) in their types, it may as well use it to detect induction hyps. I'll give it a try.

> Argument

I thought about that but I think I prefer names to be part of the inductive itself, otherwise when you fix the inductive you have to remember to also fix Arguments.

Thanks for the feedback

**Comment by Zimmi48** [comment]
Based on the recent draft status of this PR, I'm removing the milestone.

**Pull request closed without merging**
