### PR TITLE
MacOS X install: accepting both dylib and so extensions for gtk im modules

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:**  infrastructure

Hack to try to [fix](https://github.com/coq/coq/pull/13310#issuecomment-722484285) the macos x build. Extrapolating on  dd7c679, it seems that whether the shared libraries are `.dylib` or `.so` is dependent on configuration options of gtk (see also e.g. a seemingly [related comment](https://github.com/trustable-code/NiGui/issues/63#issuecomment-538747664)).

### CODE REVIEW

**Comment by Zimmi48** [comment]
Still failing with:

```
install -m 644 "/usr/local/Cellar/gtk+3/3.24.23/lib/gtk-3.0/3.0.0/immodules/"*.so "/usr/local/Cellar/gtk+3/3.24.23/lib/gtk-3.0/3.0.0/immodules/"*.dylib bin/CoqIDE_8.13+alpha.app/Contents/Resources/immodules
install: /usr/local/Cellar/gtk+3/3.24.23/lib/gtk-3.0/3.0.0/immodules/*.dylib: No such file or directory
make[1]: *** [bin/CoqIDE_8.13+alpha.app/Contents/Resources/immodules] Error 71
```

**Comment by gares** [comment]
Nice! Could you also try to download the artefact from
https://dev.azure.com/coq/bb4af0bd-7538-469b-88fe-a614a5dc4649/_apis/build/builds/13508/artifacts?artifactName=coq-macOS-installer&api-version=6.0&%24format=zip
and test it locally?

**Comment by herbelin** [comment]
Unfortunately, my version of MacOS X is too old and does not support any more the packages built by CI (at least it was the case for 8.11.1 or 8.11.2 and later). @mattam82 has probably a more recent version of MacOS.

**Comment by mattam82** [comment]
I'll try it

**Comment by mattam82** [comment]
Works fine

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
I noticed only now, but it seems that this PR has been merged with a commit that was supposed to be temporary that disabled the test-suite...

**Comment by Zimmi48** [comment]
Not that this is a big issue, but we should re-enable it in `master` I think.

**Comment by gares** [comment]
Yup, sorry

**Comment by herbelin** [comment]
My fault too, I forgot about this commit before moving from draft mode. See #13491.

**Pull request merged**
