### PR TITLE
[bench] control opam binary, update to 2.1.3

### PR DESCRIPTION
**Pull request by ejgallego**
Version was pretty old, so it is better we control this.

It seems at the bench we don't enjoy the luxury of docker.

### CODE REVIEW

**Comment by Alizter** [comment]
Isn't sshing into the machines the correct thing to do?

**Comment by ejgallego** [comment]
I think the more we control the environment the bench setup is ran, the better for us.

**Comment by ejgallego** [comment]
We could extend path tho, instead of this use of variables.

**Comment by Alizter** [comment]
@coqbot bench

**Comment by ejgallego** [comment]
You prefer folks to have a `.bin` path and install local stuff there, or do this variable thing?

**Comment by SkySkimmer** [comment]
>You prefer folks to have a .bin path and install local stuff there, or do this variable thing?

I think I'd prefer the .bin solution

**Comment by ejgallego** [comment]
> I think I'd prefer the .bin solution

Ok, done like that, and added a bit of comment. I was a bit scared to update the PATH as `eval $(opam env)` modifies also the PATH in often pretty bad ways, but let's hope that's OK.

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@coqbot merge now

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now third times the charm

**Comment by SkySkimmer** [comment]
opam is complaining about
~~~
[WARNING] set-global was deprecated in version 2.1 of the opam CLI. Use opam var instead or set OPAMCLI environment variable to 2.0.
~~~
by the way

**Comment by Alizter** [comment]
Since we won't update opam for a while yet, it probably isn't worth addressing.

**Comment by SkySkimmer** [comment]
It is very noisy and definitely worth addressing.

**Pull request merged**
