### PR TITLE
Fix #7754: universe declarations on mutual inductives

### LINKED ISSUE #7754: Polymorphic universe instances for mutual inductive types are broken
#### Version

Coq 8.8

#### Description of the problem

The following code displays the bug.
```
Inductive foo@{i} : Type@{i} :=
with bar@{j} : Type@{j} := .
(** Undeclared universe: j *)
```
Different message but essentially the same issue:
```
Inductive foo@{i} : Type@{i} :=
with bar@{j} : Type@{i} := .
(* Universe i already exists. *)
```
The problem is  that only the first instance is used, and there is no check in vernacentries that they coincide.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@mattam82 ping

**Comment by herbelin** [comment]
@SkySkimmer, may I ask you for a brief summary of the cause of the problem and of how you fixed it? What was the probem with `ind_univs`?

**Comment by SkySkimmer** [comment]
The universe binding is global to the inductive block, ind_univs was one per inductive.
The bug was just that parsed stuff was silently ignored.

**Review by mattam82 — APPROVED** [review]
The proposed fix and change of grammar looks fine to me, it's better to forbid redeclarations than check they're the same or ignore them indeed. I realize we didn't document the syntax of @{i +} or the fact that inductives could take it either but that's somewhat unrelated.

**Comment by Zimmi48** [comment]
@mattam82 You are also the natural assignee here.

**Comment by mattam82** [comment]
@SkySkimmer please rebase and I'll merge

**Comment by SkySkimmer** [comment]
Rebased.

**Comment by Zimmi48** [comment]
@mattam82 ping

**Comment by mattam82** [comment]
@skyskimmer please rebase again

**Comment by Zimmi48** [comment]
CI passed except for Windows which is broken everywhere.

**Comment by Zimmi48** [comment]
@mattam82 please merge today for this to get in 8.8.2

**Comment by Zimmi48** [comment]
I should have checked before talking but this PR has lots of conflicts when backporting to v8.8 and API changes, so sorry about that but it won't go in.

**Comment by mattam82** [comment]
That's ok, it was ready for master anyways.

**Comment by silene** [comment]
I am completely unable to backport this pull request to 8.9. Is it depending on another pull request that should be backported first or is it master-only?

**Comment by SkySkimmer** [comment]
Don't bother backporting this if it's difficult, this is not an important fix.

**Pull request merged**
