### PR TITLE
Remove test stm/Nijmegen_QArithSternBrocot_Zaux

### PR DESCRIPTION
**Pull request by SkySkimmer**
It is useless and takes a long time.

### CODE REVIEW

**Comment by herbelin** [comment]
No particular opinion (except that it is the last one to terminate, but maybe if it was the first to be started, it would have finished before the others completed?).

This was an stm test and I don't know if @gares cares.

**Comment by gares** [comment]
No problem with the removal. if IIRC it is a stress test for the STM, but you need to compile in async mode. But I don't think it was *that* slow. How long does it take, @SkySkimmer ? I recall it being in the < 1m ballpark.

**Comment by SkySkimmer** [comment]
Currently around 1m30s in https://github.com/coq/coq/pull/19141 for instance

**Comment by ejgallego** [comment]
This file takes around 1/2 seconds to compile in the simple compiler, so indeed, it shows a few quadratic overheads in the stm, in particular it seems that `VCS.slice` is a culprit here.

I am having trouble finding a real-world file that goes faster with `-async` that without async (not talking about `par:` which I'm quite ignorant about), so I dunno if we should just remove the async capability entirely?

**Comment by ejgallego** [comment]
> This file takes around 1/2 seconds to compile in the simple compiler, so indeed, it shows a few quadratic (or even bigger) overheads in the stm, in particular it seems that `VCS.slice` is a culprit here.
> 
> I am having trouble finding a real-world file that goes faster with `-async` that without async (not talking about `par:` which I'm quite ignorant about), so I dunno if we should just remove the async capability entirely?

**Comment by SkySkimmer** [comment]
async is not used for speed, it's for testing the stm
There is no point removing it without removing the stm

**Comment by ejgallego** [comment]
> async is not used for speed, it's for testing the stm
> There is no point removing it without removing the stm

Ummm, I think you can remove proof delegation but you still have a good chunk of the stm remaining, for example for `par: `, `edit_at`, etc...

My point is more how much is proof delegation to users given its current runtime complexity?

**Pull request closed without merging**
