### PR TITLE
[v8.12] Bump Equation to 1.2.2 and UniCoq to 1.4.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@mattam82 @SimonBoulier Can you point me to a commit of MetaCoq that is compatible with Coq 8.12 and Equation 1.2.2?

**Comment by mattam82** [comment]
Baring an unexpected event, the coq-8.12 branch should work with 8.12+beta1 and equations 1.2.2 https://travis-ci.com/github/MetaCoq/metacoq/builds/172868715

**Review by MSoegtropIMC — APPROVED** [review]
LGTM

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : this PR is assigned to you - a bit uncommon for a PR you authored. Shall I take it and merge (as soon as CI goes through)?

**Comment by Zimmi48** [comment]
This is because this is not a PR on `master`. The principle is that the RM is / are the only one(s) who can merge into the release branches, so it's an exception to the "do not merge your own PR" rule. Cf. the contributing guide.

**Pull request merged**
