### PR TITLE
Sort goals by location.

### PR DESCRIPTION
**Pull request by cmangin**
Currently, when writing things like `refine (match x with S n => _ | O => _ end).`, the two generated subgoals are swapped compared to the other provided by the user. The goal of this PR is to remedy this at some point.
(The other goal is to just have the possibility to do that from a plugin.)

I am creating this PR to get a bit of feedback on this matter, since I really don't have a comprehensive understanding of the way evar sources are used. Specifically:
- The first commit fixes the fact that `change` loses the evar source. This might have been intended, especially since it required to change a file in the test-suite, but I don't know.
- The second commit adds a tactic `sortgoals` which will sort the currently focused goals by their location. Note that this does not solve everything, which is the main reason I would like feedback, from @herbelin for instance who seemed interested. Consider the following:

```coq
Inductive foo := A : nat -> foo | B : unit -> foo | C : bool -> foo.

Goal foo -> True.
Proof.
  refine (fun x =>
    match x with
    | C _ | A _ => _
    | B _ => _
   end).
```
Without this PR, the subgoals would be A -> B -> C.
With this PR, by adding `; sortgoals`, the subgoals would be A -> C -> B.
The reason is that the evars corresponding to A and C have the same location. I do not have a satisfying solution to this specific problem yet, but maybe it indicates that this PR is not the right way of addressing the problem. Hence the need for some feedback.

### CODE REVIEW

**Comment by ppedrot** [comment]
This feature looks horribly fragile to me. Making tactics depend on locations is of the same kind as the unification bug that made it sensitive to file names (or identifiers, I don't remember the exact eldritch horror). I think it is really a XY problem, because what this patch wants to solve, i.e. the order of holes generated by refine, is uniquely defined by one part of the code, namely pretyping. I am irremediably convinced that the genuine problem is that pretyping is *not* specified, and that this PR is at best a naive workaround, and at worst a terrible anti-feature we will be regretting 5 years from now.

**Comment by ppedrot** [comment]
Also, thinking about it, this is not even sound. What about using the same physical term (and thus the same locations) twice in two different goals, as e.g. this would arise with some `split; refine (...); sortgoals`? And toplevel Ltac definitions?

**Comment by cmangin** [comment]
Your second comment is the problem I was raising at the end: same physical location, so an arbitrary choice between the two is done (which is not always what the user would expect).

Point taken in any case, I would be glad to have a more specified pretyping which would agree with what the user writes. I guess I am closing this for now, this is exactly why I opened the PR in the first place.

**Comment by ejgallego** [comment]
I am not sure about this, but it seems that naming the goals explicitly in `refine` could be a more robust approach?

**Comment by aspiwack** [comment]
I don't have a particularly good idea of strategy either. But the somewhat unpredictable goal-order in refine is a bit of problem (since it's not specified, it may change between two versions of Coq too, not super nice).

Even if this was not the right way, thank you @cmangin for trying to make progress in this direction.

**Comment by aspiwack** [comment]
That being said, basing the ordering of goals on the text of the tactic is pretty reasonable an idea, it gives control to the programmer. But if it's done anywhere, it should be attached to the `refine` tactic proper (or the pretyper, which sort of amounts to the same), as doing so after the fact is littered with « interesting » issues.

However, even so there are still non-trivial questions. Like the fact that the pretyper may partially solve a goal written by the user this generates, say, two new goals. How do we place these ones? (this is actually two questions: how do we place them with respect to the other goals? and how do we order these two goals?).

PS: I'm assuming that holes generated by implicit arguments and notations have a location and can be easily ordered. Even if I'm not sure it's that trivial in the current codebase.

**Comment by herbelin** [comment]
Typical other examples worth to be specified, maybe changing their current semantics, or at least eventually providing an explicit possibility to indicate if we intend sharing or not.
One or two universe variables:
```
Check forall A B : _, A -> B.
```
One or two subgoals:
```
Check fun x y : _, (x,y).
Check fun x => match x with Lt => 1 | _ => _ end.
```

**Comment by Zimmi48** [comment]
> I am not sure about this, but it seems that naming the goals explicitly in refine could be a more robust approach?

👍 

although this:

```
Inductive foo := A : nat -> foo | B : unit -> foo | C : bool -> foo.

Goal foo -> True.
Proof.
  refine (fun x =>
    match x with
    | C _ | A _ => ?[ca]
    | B _ => ?[b]
   end).
```

is not legal and must be transformed into:

```
Inductive foo := A : nat -> foo | B : unit -> foo | C : bool -> foo.

Goal foo -> True.
Proof.
  refine (fun x =>
    match x with
    | C _ => ?[c]
    | A _ => ?[a]
    | B _ => ?[b]
   end).
  [c]: exact I.
  [a]: exact I.
  [b]: exact I.
Qed.
```

BTW, whenever we finally get `2: { }`, we can also consider implementing `[a]: { }`.

**Pull request closed without merging**
