### PR TITLE
Avoid OCaml naked pointer in accumulators

### LINKED ISSUE #10602: Obj.truncate and Obj.set_field will be deprecated in OCaml 4.10
`Obj.truncate` and `Obj.set_tag` have been deprecated in OCaml upstream, c.f. https://github.com/ocaml/ocaml/pull/2279 and https://github.com/ocaml/ocaml/pull/2279

Users in Coq are `Hashset` (for `Obj.truncate`) and `Nativevalues` (for `Obj.set_tag`) , I am not sure how hard it will be to fix in the second case.

cc: @maximedenes @ppedrot

### PR DESCRIPTION
**Pull request by chambart**
Using tag 0 on closure is going do be broken quite soon, so at some point this codes needs to change.

The only safe way to distinguish accumulators from other function is to record the set of all accumulator produced. To avoid leaking this is recorded in a weak table. Sadly the Weak module does not allow to use the physical equality function to retrieve values since it is applied on a copy. Ephemeron does not have this problem.

I don't know Coq enough to understand whether changing the tag to something else than 0 is a problem. And this is certainly slower than the original version.

To be honnest I have another solution but it is seriously evil and would prefer to avoid it as much as possible.

**Kind:** bug fix

Fixes / closes #10602

### CODE REVIEW

**Comment by SkySkimmer** [comment]
What's the evil solution?

**Comment by ppedrot** [comment]
@chambart This will break all the compilation scheme, since pattern-matching compilation relies on accumulators having tag 0. The only sane solution I know to fix the naked pointer issue is to have a dedicated caml_apply function inserted in the translation phase.

**Comment by ppedrot** [comment]
Another alternative would be to have OCaml support for pattern-matching of the form
```
match foo with
| C1 ... -> ...
| Cn ... -> ...
| Closure_tag _ -> ...
```
with `C1`, ..., `Cn` are regular constructors.

AFAIU it's possible to generate intermediate flambda code for this kind of pattern-matching but (fortunately?) there is nothing user-facing for this kind of hack.

**Comment by SkySkimmer** [comment]
Can't we do something like
~~~ocaml
if Obj.tag foo = Closure_tag then ...
else match foo with ...
~~~
?

**Comment by ppedrot** [comment]
@SkySkimmer Yes, but then it's horribly inefficient. `Obj.tag` calls the page table check.

**Comment by SkySkimmer** [comment]
In future ocaml it won't though if I understand https://github.com/ocaml/ocaml/commit/6e9d39bb264e1fa0d53e94fa0f1101ed394fe699 correctly.

**Comment by ppedrot** [comment]
It would still be less efficient than a jump through the pattern-matching table. We can probably roll up our own variant of `is_closure` in C that does not check the page table (since it knows that it's always a block or a direct integer) and see what happens.

**Comment by silene** [comment]
I am lost. How is the proposed patch related to naked pointers? In other words, which of the memory words of an accumulator is a naked pointed? Is the issue due to the first word being allocated on the static heap rather than the collected heap? If so, why not just change that?

**Comment by silene** [comment]
Replying to myself, I guess the operating system will complain in an abrupt way. The `camp_apply` solution would indeed work around this issue, but I expect it to be costly.

**Comment by silene** [comment]
So, there are three kinds of accumulators, those of inductive types that can be matched against, those of arrow types that can be applied, those of abstract types that can be nothing (?). Only accumulators that can be matched against need to have tag 0. For others, we do not care. But, if I am not mistaken, even in an inconsistent context, these three kinds of accumulators are exclusive. So, why do we bother changing the tag in the first place? Would it not work just fine if we leave the tags unchanged? Obviously, this means doing a bit more work at reconstruction time to recover all the accumulators, but this part is not performance sensitive.

**Comment by ppedrot** [comment]
> But, if I am not mistaken, even in an inconsistent context, these three kinds of accumulators are exclusive.

Unfortunately I think you don't have enough runtime information to know that. How would you handle an accumulator of type `forall b : bool, if b then unit else unit -> unit`? More generally you'd need to simulate the whole CIC type system (in particular arbitrary conversion) in the compilation scheme of accumulators *at runtime*, which looks like a very inefficient thing.

**Comment by silene** [comment]
> How would you handle an accumulator of type `forall b : bool, if b then unit else unit -> unit`?

That is not an inductive type, so a value of this type will never be matched against. But I see your point. Once applied, the resulting accumulator can be both matched and applied. So, even a simpler example such as an accumulator of type `unit -> unit` is already problematic, since it means that the accumulating function needs some typing information.

**Comment by ppedrot** [comment]
This PR is broken, and the correct fix is much more involved. I believe that the Coq dev team is acutely aware of the problem, in particular @maximedenes, but solving this requires a non-trivial amount of work. Given that, I am closing this PR and will be personally butt-kicking the knowledgeable people around (including myself) so that there is progress on the issue.

**Comment by ppedrot** [comment]
BTW @chambart if you're missing pieces of the picture, I'd be happy to discuss with you the internals of native compilation so that it's clearer why we use this horrible hack.

**Comment by jhjourdan** [comment]
I discussed with @gasche of this problem, and he suggested an elegant solution: in https://github.com/ocaml/RFCs/pull/14, @yallop is proposing to add the possibility of unboxing some constructor of algebraic types.

In particular, (a small extension of) this RFC would allow unboxing algebraic type constructor whose content is a function (with a closure tag or an infix tag). From the perspective of this PR, if one adds an unboxed constructor of type `Obj.t -> Obj.t` to every translated Coq inductive type, this is essentially the same as allowing to discriminate over the closure tag in a pattern matching.

Now, the problem is that https://github.com/ocaml/RFCs/pull/14 is still an RFC, and there still exists no implementation. So, @ppedrot, @maximedenes, could you please confirm that this would help for solving this problem? If so, could you please participate to the discussion in https://github.com/ocaml/RFCs/pull/14 to make things move faster?

**Comment by xavierleroy** [comment]
For the record let me summarize the two plausible fixes that have been mentioned already:
1. Represent accumulators by functions (properly tagged `Closure_tag`) and compile pattern-matchings to
```
  if is_closure x then (* accumulator case *) else match x with ... (* normal cases *)
```
2. Represent accumulators by zero-tagged blocks and compile function applications `f arg` to
```
  if is_closure f then f arg (* normal case *) else ... (* accumulator case *)
```

Solution 2 is horribly expensive if all function applications are transformed, but could be OK if applications of known functions (i.e. variables let-bound to function abstractions) are not transformed, since in this case the function cannot be an accumulator.

Both solution need a fast `is_closure` test.  `Obj.tag` is a little slow, although it will get faster in no-naked-pointers mode (no page table check).  A C function declared "noalloc" should do for initial experiments.  It should be possible to generate entirely inlined code for this test.

**Pull request closed without merging**
