### PR TITLE
Use make -n in create_overlays instead of trying to compile.

### PR DESCRIPTION
**Pull request by SkySkimmer**
It's not perfect but I think it's better than the current state.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Actually nevermind I feel like this is asking for bugs since the scripts don't expect to be run with -n.

**Comment by SkySkimmer** [comment]
Instead we should use an environment variable `CHECKOUT_ONLY` and use it in the CI scripts.

**Comment by ejgallego** [comment]
Yup this needs to be fixed, I was lazy. We could maybe use make targets for that?

**Comment by SkySkimmer** [comment]
Alternatively we could tell people to use a workflow like
- while not `make ci-broken`; do fix
- run create-overlays broken
- commit in ci-broken (or create-overlays could auto commit and push)

and remove the `make` line from the script.

**Comment by ejgallego** [comment]
Umm, I'm not sure I understand this workflow, seem pretty cumbersome. My current workflow is:
- do change, push to CI; observe broken,
- `create-overlays ejgallego XXX broken`
- make -f Makefile.dune check # this is M-c in my emacs and critically builds all the broken overlays at once.

Then I just wait for emacs to send me to the broken place, I do commit and push from emacs too.

**Pull request closed without merging**
