### PR TITLE
[ci] Add mit-plv/cross-crypto

### PR DESCRIPTION
**Pull request by JasonGross**
I followed the code for fiat-crypto / fiat-parsers.  I hope I didn't
miss anything.

**Kind:** infrastructure.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM

**Comment by JasonGross** [comment]
Build [fails on my travis](https://travis-ci.org/JasonGross/coq/builds/377059034) in a number of places, generally with the message
```
[ERROR] camlp5.7.03 is not available because your system doesn't comply with
        ocaml-version >= "4.02" & ocaml-version < "4.06.1".
```
and also
```
ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during 
```
but it succeeds on the ci this PR is adding.

**Comment by Zimmi48** [comment]
The first unrelated error you report is being fixed by #7471. As for the second one, it seems like a temporary connectivity problem.

**Comment by ejgallego** [comment]
Yup @JasonGross you may want to rebase on top of #7471 or wait a few minutes that CI completes on that one so it'll be merged in master.

**Comment by ejgallego** [comment]
Won't delay this needlessly, again appveyor is slow.

**Pull request merged**
