### PR TITLE
Add timeout to the bench

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
I guess @ppedrot needs to take a look

**Comment by ppedrot** [comment]
Not sure if this is a good idea to have such a hard limit. What if we want to test custom packages?

**Comment by SkySkimmer** [comment]
You can easily add a commit to change the timeout

**Comment by ppedrot** [comment]
Why not put it in a user-facing variable then?

**Comment by SkySkimmer** [comment]
ok have a variable

**Review by ppedrot — APPROVED** [review]

**Comment by Alizter** [comment]
alright will merge soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
