### PR TITLE
[CI] Update nixpkgs

### PR DESCRIPTION
**Pull request by proux01**
In an attempt to fix the cachix installation issue.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Does not seem to work

**Comment by proux01** [comment]
This one should work (if the docker image behaves as locally)

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
I see nix failing in 8.20 backports PR https://github.com/coq/coq/pull/19255 so I guess this PR should be in 8.20

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
