### PR TITLE
Allow dependent products as keys of canonical instances

### PR DESCRIPTION
**Pull request by pi8027**
This PR revives #12349 and changes the category of the changelog entry for #14041 (See https://github.com/coq/coq/pull/14041#discussion_r639606398).

**Kind:** feature.

Fixes / closes #12349

- [x] Added / updated test-suite

- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by pi8027** [comment]
May I have the right to run benchmarks? My GitLab.com ID is `pi8027`.

**Comment by ppedrot** [comment]
@pi8027 you should probably ask this on zulip, I don't know who has the rights to do that but they are unlikely to read this comment.

**Comment by pi8027** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1294686381

**Review by gares — APPROVED** [review]

**Comment by Zimmi48** [comment]
@gares Shouldn't you also self-assign?

**Comment by gares** [comment]
I'll be on parental VAC from tomorrow for a few days.. if I can merge before that, I will assign. If not, I'd love someone else to pick this up.

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1680.40  1687.66  -0.43 │  4695039279543   4710206978177  -0.32 │  7452216937427   7454586890554  -0.03 │ 1902280  1902140   0.01 │   0    0    nan │
│       coq-engine-bench-lite │  337.60   339.03  -0.42 │   947942760539    949949282665  -0.21 │  1655522592291   1655979430249  -0.03 │ 3536356  3536276   0.00 │   0    0    nan │
│          coq-mathcomp-field │  239.16   239.93  -0.32 │   665298024969    666827659014  -0.23 │   953692717350    953721373057  -0.00 │  664644   664592   0.01 │   0    0    nan │
│              coq-coquelicot │   74.08    74.25  -0.23 │   204746555258    204758342575  -0.01 │   241326447436    240706391768   0.26 │  560108   559240   0.16 │   0    0    nan │
│                 coq-unimath │ 4174.71  4179.29  -0.11 │ 11601730287444  11614377704817  -0.11 │ 21238730052039  21235278729183   0.02 │ 1123052  1123024   0.00 │   0    0    nan │
│                   coq-color │  527.40   527.90  -0.09 │  1461885140785   1463054711743  -0.08 │  1724774726953   1723898074972   0.05 │ 1131868  1131624   0.02 │   0    0    nan │
│       coq-mathcomp-solvable │  184.55   184.72  -0.09 │   512343751370    512699705543  -0.07 │   680575724107    680683580196  -0.02 │  683484   683428   0.01 │   0    0    nan │
│             coq-lambda-rust │ 1359.81  1360.97  -0.09 │  3786432233462   3788151621986  -0.05 │  5118477431329   5121415517383  -0.06 │ 1105072  1109104  -0.36 │   0    0    nan │
│      coq-mathcomp-character │  163.20   163.33  -0.08 │   453448048879    454125066380  -0.15 │   596477679372    596537700293  -0.01 │  744432   744972  -0.07 │   0    0    nan │
│        coq-mathcomp-algebra │  150.09   150.20  -0.07 │   417716713404    418026944426  -0.07 │   507650317925    507713548663  -0.01 │  552144   552580  -0.08 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1131.11  1131.78  -0.06 │  3146963188924   3148288876385  -0.04 │  4707098723563   4707528284729  -0.01 │  903608   911540  -0.87 │   0    0    nan │
│               coq-perennial │ 7289.67  7291.20  -0.02 │ 20302502811957  20309172756631  -0.03 │ 29178705898729  29181617710245  -0.01 │ 3115000  3128088  -0.42 │   0    0    nan │
│                    coq-hott │  300.55   300.50   0.02 │   811951006147    811477305800   0.06 │  1187929397859   1187967458204  -0.00 │  584280   583924   0.06 │   0    0    nan │
│            coq-fiat-parsers │  645.18   645.07   0.02 │  1789565357679   1791811894051  -0.13 │  2555410935562   2555665473984  -0.01 │ 3270980  3270800   0.01 │   0    0    nan │
│                    coq-corn │ 1573.52  1572.90   0.04 │  4367802454165   4368088611048  -0.01 │  5985770579741   5986181771168  -0.01 │  816968   816980  -0.00 │   0    0    nan │
│                coq-bedrock2 │  334.92   334.62   0.09 │   930227610610    928641136296   0.17 │  1534703561354   1532982392593   0.11 │  752832   752724   0.01 │   0    0    nan │
│                  coq-geocoq │ 1462.25  1459.73   0.17 │  4060370823714   4055898157894   0.11 │  5633342744651   5631897164529   0.03 │  991324   991188   0.01 │   0    0    nan │
│             coq-fiat-crypto │ 5136.02  5126.29   0.19 │ 14301014942093  14271162268583   0.21 │ 24017046448036  24003677257273   0.06 │ 2209664  2216424  -0.30 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │  798.70   797.02   0.21 │  2227304326212   2221872774694   0.24 │  3309607607655   3309367673872   0.01 │ 1099912  1100012  -0.01 │   0    0    nan │
│               coq-fiat-core │  116.40   116.11   0.25 │   327534848797    326980494489   0.17 │   409784194088    408725042330   0.26 │  479472   479504  -0.01 │   0    0    nan │
│                    coq-core │  110.92   110.63   0.26 │   310244344242    310611827204  -0.12 │   457044165258    457040675581   0.00 │  295660   295752  -0.03 │   0    0    nan │
│              coq-verdi-raft │ 1243.83  1240.42   0.27 │  3462109575990   3446104833275   0.46 │  4614155913464   4613437871166   0.02 │  902392   902684  -0.03 │   0    0    nan │
│                coq-rewriter │  727.73   725.66   0.29 │  2022321402185   2016621283849   0.28 │  2947786784020   2945613442937   0.07 │ 1100120  1100132  -0.00 │   0    0    nan │
│                  coq-stdlib │  422.25   420.86   0.33 │  1184778209110   1181124259005   0.31 │  1469941691972   1469961202518  -0.00 │  566404   566056   0.06 │   0    0    nan │
│                 coq-bignums │   59.69    59.48   0.35 │   164690330293    164249046608   0.27 │   209977100438    209943478758   0.02 │  473732   473696   0.01 │   0    0    nan │
│       coq-mathcomp-fingroup │   52.23    52.04   0.37 │   144526070015    144616721590  -0.06 │   188947961554    188936907421   0.01 │  482040   481916   0.03 │   0    0    nan │
│               coq-fourcolor │ 2706.76  2696.56   0.38 │  7535870099959   7511028061171   0.33 │ 12245655965721  12244217828260   0.01 │  730180   730244  -0.01 │   0    0    nan │
│                         coq │    4.56     4.54   0.44 │    12510602602     12544964466  -0.27 │    23497982294     23494264155   0.02 │  276960   276924   0.01 │   0    0    nan │
│            coq-math-classes │  188.92   188.08   0.45 │   519243558603    518286650128   0.18 │   652974109444    652976449156  -0.00 │  479876   479832   0.01 │   0    0    nan │
│      coq-mathcomp-ssreflect │   58.42    58.07   0.60 │   160153096870    159780561108   0.23 │   189829389590    189856607009  -0.01 │  523020   523372  -0.07 │   0    0    nan │
│                   coq-verdi │  106.25   105.60   0.62 │   292933186841    292193084061   0.25 │   387254746313    386461617024   0.21 │  540232   540260  -0.01 │   0    0    nan │
│                coq-coqprime │ 1498.22  1488.90   0.63 │  4172728443195   4144866513626   0.67 │  6592762717816   6592172864818   0.01 │ 1055644  1055564   0.01 │   0    0    nan │
│                 coq-coqutil │   62.79    62.13   1.06 │   172807000788    171399770406   0.82 │   214162470911    213824674586   0.16 │  598440   597684   0.13 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
~~~

**Pull request merged**
