### PR TITLE
Comment difference between the 2 hashes on constr

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
That's not the only difference. From what I can read, the hash is also different for arrays, because it is not processed in the same order. IIRC I think there were other subtle differences as well.

**Comment by ppedrot** [comment]
@SkySkimmer ping?

**Comment by SkySkimmer** [comment]
>From what I can read, the hash is also different for arrays, because it is not processed in the same order

Not AFAICT, am I missing something?

**Comment by ppedrot** [comment]
Look at the order of arguments of `combine` in `hash_term_array`.

**Comment by ppedrot** [comment]
@SkySkimmer ping

**Comment by SkySkimmer** [comment]
Changed

**Review by ppedrot — APPROVED** [review]
Let's merge, no reason to further delay this.

**Pull request merged**
