### PR TITLE
Move rewrite_db tactic in doc

### PR DESCRIPTION
**Pull request by jfehrle**
As suggested [here](https://github.com/coq/coq/pull/15546#issuecomment-1022064667).

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Zimmi48** [comment]
If we consider this tactic worth to have, then I'd put it under "Usage" (even if it relies on things that have not been explained yet) rather than at the very end of the page.

**Comment by jfehrle** [comment]
@Alizter Perhaps you should have allowed a bit more time for comment before merging this one.

**Comment by Alizter** [comment]
@jfehrle I haven't merged anything yet, I'm still waiting for others to review.

**Comment by Zimmi48** [comment]
I guess now that we have two PRs open, one of them doing what I suggested, we can close this one in favor of the new one (#15563).

**Comment by jfehrle** [comment]
Ah, multitasking makes you stupid :-(

**Pull request closed without merging**
