### PR TITLE
Remove the side-effect role from the kernel.

### PR DESCRIPTION
**Pull request by ppedrot**
We move the role data into the evarmap instead.

Overlays:
- https://github.com/mattam82/Coq-Equations/pull/214

### CODE REVIEW

**Review by gares — APPROVED** [review]
Yea!!!

**Comment by gares** [comment]
If a kernel maintainer ( @maximedenes ) acks then I can assign this

**Comment by maximedenes** [comment]
> If a kernel maintainer ( @maximedenes ) acks then I can assign this

Sure, you are more competent on side-effects stuff.

**Comment by ppedrot** [comment]
I think I should also move the role type out of Entries. I'll push an additional patch.

**Comment by ppedrot** [comment]
@gares should be ready

**Comment by ppedrot** [comment]
@gares ping.

**Pull request merged**
