### PR TITLE
lint-commits: actually check that intermediate commits build

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
For instance https://gitlab.com/coq/coq/-/jobs/1207074548 reported all green even though some commits didn't build :disappointed:

**Comment by ejgallego** [comment]
Looks OK, what difference does the worktree call make tho?

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
> We need to git checkout the commits to build them, but I want to be able to run this locally without changing my state so it needs to happen in a fresh directory.

So it is really the `set -e` which matters here?

**Comment by SkySkimmer** [comment]
No, the `set -e` is just to get shellcheck to shut up about unguarded `cd`/`pushd`
The `git checkout` is what does work, the worktree makes it work without messing with the user's tree.

**Comment by ejgallego** [comment]
> For instance https://gitlab.com/coq/coq/-/jobs/1207074548 reported all green even though some commits didn't build

Umm, sorry for asking again [we can just merge and stop if you think the discussion is overkill], but in that lint job log, where is the bug, reading it does regular checkout + `@check`, so it should have failed? What kind of mess did checkout did there?

**Comment by SkySkimmer** [comment]
Where do you see it doing checkout? The `Checking XXX` output is just the echo at https://github.com/coq/coq/blob/e219f0f18167d16c31e2a575b912aa065152afc4/dev/lint-commits.sh#L25

**Comment by ejgallego** [comment]
Oh indeed :facepalm: :facepalm: , thanks.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
