### PR TITLE
[compat] Remove "Shrink Obligations"

### PR DESCRIPTION
**Pull request by ejgallego**
Following up on #6791, we the option "Shrink Obligations".

### CODE REVIEW

**Comment by Zimmi48** [comment]
Breaks Equations.

**Comment by ejgallego** [comment]
@mattam82 what should be done here?

**Comment by mattam82** [comment]
Equations currently needs the defined obligations it generates itself (not the ones coming from pretyping terms) to have the same arguments they were declared with. I think it's the only client needing that. One way out would be to allow the shrinking flag to be passed on a per-obligation basis (and set always on by default). Then the flag can be deprecated.

**Comment by ejgallego** [comment]
> Then the flag can be deprecated.

The flag is already deprecated. You mean removed? Or should we undeprecate it then?

Also note that Equations does:
```
theories/Init.v:Global Unset Shrink Obligations.
```
So the flag will be globally set for any user of the library I think.

**Comment by mattam82** [comment]
Sorry, I meant removed ! The Global Unset can be removed accordingly
afterwards.

**Comment by ejgallego** [comment]
Ok so then we delay this to 8.9 [at least]

**Comment by mattam82** [comment]
Yes, sounds reasonable. Sorry I should have taken the time to move on that
issue before.

**Comment by ejgallego** [comment]
This is on the Obligations / Equations side so I am closing this PR.

**Pull request closed without merging**
