### PR TITLE
Congruence tactic engine update

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:**  cleanup / fix

This is the part of #7067 without the `EConstr` port as proposed [here](https://github.com/coq/coq/pull/7067#pullrequestreview-107255111).

Copying from #7067 the relevant component here:
- getting rid of a call to a V82 layer of the proof engine (see commit message for explanation)
- fixing what seems a bug with primitive projections (there was a special treatment of primitive projections constant which seems buggy and redundant; at least removing this code makes congruence working more with primitive projections; @mattam82, am I missing something? do you remember the intent of this code? maybe the objective was to make the projections compact again after expansion? If so, the fix should be improved)

So, I would be safer with a quick opinion from @mattam82 about the primitive projection stuff.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Good for me but I'm waiting for a comment from @mattam82 on the primitive projection fix.

**Comment by ppedrot** [comment]
@mattam82 Ping.

**Comment by ppedrot** [comment]
@mattam82 Ping again!

**Comment by mattam82** [comment]
As everything passes and the test-suite looks like the right test, I'm fine with it. I don't exactly remember why I did that change. Maybe I wanted to make congruence insensitive to the representation of the projection (using the constant or Proj)?

**Comment by herbelin** [comment]
> Maybe I wanted to make congruence insensitive to the representation of the projection (using the constant or Proj)?

Yes, the input to `congruence` was processed with `expand_projection` (in `Cctac.decompose_term`) and I did modify this part of the code.

What was more mysterious is the treatment in `Ccalgo.constr_of_term` which was buggy (the ` | hd :: tl -> Term.applistc (mkProj (p, hd)) tl)` line, as far as I can tell) but about which I did not spent enough time to understand whether it is called only at the end of the procedure to build the proof or if it is also used in the construction of the problem (based on the name of the file, my guess is solution 1 - if @PierreCorbineau is online, he could tell quickly).

**Comment by Zimmi48** [comment]
Ping @herbelin @ppedrot can you answer my question regarding backporting?

**Comment by herbelin** [comment]
@zimmi48: What you propose seems ok.

**Pull request merged**
