### PR TITLE
Factorize code in hint declaration.

### PR DESCRIPTION
**Pull request by ppedrot**
This allows to remove internal API from the mli as well.

### CODE REVIEW

**Comment by ejgallego** [comment]
Adding a tag so this is not merged before the branching point.

**Comment by ppedrot** [comment]
This needs an assignee.

**Comment by ppedrot** [comment]
@herbelin maybe?

**Comment by herbelin** [comment]
I can. Giving a 24h delay.

**Review by herbelin — APPROVED** [review]

**Pull request merged**
