### PR TITLE
Fix bench variables

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
:godmode:

**Comment by SkySkimmer** [comment]
Before this PR: https://gitlab.com/coq/coq/-/jobs/805855979
After this PR: https://gitlab.com/coq/coq/-/jobs/805870557

**Review by ppedrot — APPROVED** [review]
*Sans commentaire*.

**Comment by ppedrot** [comment]
The new bench seems to be working, let's merge.

**Pull request merged**
