### PR TITLE
Rename interp/ -> intern/, pretyping/ -> interp/

### PR DESCRIPTION
**Pull request by SkySkimmer**
I'm pretty sure that the `interp/ -> intern/` part is a good idea, slightly less sure about the pretyping/ part.
This may be followed by a pr renaming the pretyping module someday, but that requires editing ml files.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Perhaps instead of pretyping -> interp it should be -> infer

**Comment by proux01** [comment]
I fear intern and interp may sound to close, infer looks better with that respect.

**Comment by ejgallego** [comment]
Can we maybe take this chance to make the libraries wrapped?

**Comment by ppedrot** [comment]
The first change is totally natural, because we already have files called something-intern in there. The second one much less so, the modules are explicitly called pretyping, and it's a jargon we're used to in addition.

**Comment by Alizter** [comment]
Don't we also call pretyping elaboration?

**Comment by gares** [comment]
Yes, that would be more modern. But if the kernel does typing, this component does pre-typing (it prepares a term for being checked by the kernel). So it is not wrong.

IMO either we don't rename it, or I agree elaborator would be the better name.

**Comment by silene** [comment]
"pretyping" was fine in the early ages, before coercions, canonical structures, and typeclasses. But, nowadays, "elaboration" seems a better fit.

**Comment by ejgallego** [comment]
Yeah elaboration is what we mostly use informally.

**Comment by SkySkimmer** [comment]
Isn't intern included in elaboration?

**Comment by ppedrot** [comment]
@SkySkimmer I'd personally call "elaboration" the whole pipeline "syntax ↦ constr" but YMMV.

**Comment by jfehrle** [comment]
My 2 cents: "interp" is a very generic name.  It may at times need to be distinguished from, say, the Ltac interpreter.  So not my favorite.

IIUC "elaboration" covers much more than just pretyping.  If **_all_** the elaboration code is under the current `pretyping` directory that it makes sense to rename to "elaboration", otherwise it may be confusing.  In a future description of elaboration in the doc, "pretyping" can identify a subsection.

**Comment by Zimmi48** [comment]
What about moving all the elaboration code under one shared directory? This would make navigating the code base easier for newcomers...

**Comment by gares** [comment]
In a book chapter under writing we (Freek and me) idetify elaboration as the process that goes from text to typed ast, it includes even parsing for example. The most interesting step for us is the one performed by the elaborator, whinch infers implicit contents, hence it gives the name to the whole pipeline.

pretyping is the elaborator, in that sense.

**Pull request closed without merging**
