### PR TITLE
New implementation of cycle detection in univ.ml - On trunk

### PR DESCRIPTION
**Pull request by jhjourdan**
Same as https://github.com/coq/coq/pull/89, but on trunk.

### CODE REVIEW

**Comment by jhjourdan** [comment]
mattam: concerning the changes to Universes.leq_constr_univs_infer, it breaks HoTT_coq_053.v with the following error message:

Error:
In environment
n : nat
H : nat
The term "DiscreteCategory Bool" has type
 "PreCategory@{Top.55 Top.55}"
while it is expected to have type
 "PreCategory@{Top.54 Prop}".


And 1951.v with:



Error: Illegal application:
The term "list_rect" of type
 "forall (A : Type) (P : list A -> Type),
  P nil -> (forall (a : A) (l : list A), P l -> P (a :: l)) -> forall l
: list A, P l"
cannot be applied to the terms
 "a" : "Set"
 "fun ls : list a => ipl2 (fun _ : a => Type) ls -> Prop" : "list a -> Type"
 "fun _ : ipl2 (fun _ : a => Type) nil => sg" : "ipl2 (fun _ : a =>
Type) nil -> Prop"
 "fun (a0 : a) (ls : list a) (_ : ipl2 (fun _ : a => Type) ls -> Prop)
(_ : ipl2 (fun _ : a => Type) (a0 :: ls)) =>
  sg"
   : "forall (a0 : a) (ls : list a),
      (ipl2 (fun _ : a => Type) ls -> Prop) -> ipl2 (fun _ : a => Type)
(a0 :: ls) -> Prop"
 "ls" : "list a"
 "X" : "ipl2 (fun _ : a => Type) ls"
The 2nd term has type "list a -> Type@{max(Set+1, Top.10)}" which should
be coercible to
 "list a -> Type@{Coq.Init.Datatypes.46}".

In both cases it seems a bit obscure to me...

**Comment by jhjourdan** [comment]
Other benchmarks: on Compcert, we get 17% improvement and 20% improvement with the odd order theorem (the previous benchmark of mathcomp was without the odd order theorem).

**Comment by ppedrot** [comment]
A quick remark: it seems strange to use lists instead of sets in the fields le, lt and gtge of canonical nodes. If I am not mistaken, we never rely on the order, and moreover, many operations we perform on the data structure are set operations. Is there a reason other than keeping the old code around?

**Comment by jhjourdan** [comment]
Indeed. I do not expect much change in performances, though, given that I rarely traverse these lists for finding an element.

I updated the code so that ltle & gtge use LMap and LSet instead. Given lt and le are often used the same way, I merged them into an LMap with booleans indicating whether it is an Lt or an Le.

**Comment by ppedrot** [comment]
I made some performance check on this branch, and the use of polymorphic equality in topo_compare is actually observable (it amounts for up to around 2% on some ssreflect files). It should use a dedicated comparison function instead, providing both efficiency and well-defined behaviour.

**Comment by jhjourdan** [comment]
I've just replaced all that with manual lexicographic comparison.

**Comment by jhjourdan** [comment]
Following up on that: thanks for having done the necessary refactoring and proof-reading.

I did a few clarifications of the comments, mainly to match the original paper.

**Comment by ppedrot** [comment]
Your code has already been merged in trunk. If you want to clean it up, you should probably open a new pull request.

**Comment by jhjourdan** [comment]
Well, I can, but these are really minor changes.

**Comment by ppedrot** [comment]
Cherry-picked as 9e585d7479af0.

**Pull request closed without merging**
