### PR TITLE
Prepare support for -Q semantics for plugins

### PR DESCRIPTION
**Pull request by maximedenes**
We make the computation of the load path a bit more fine grained, to prepare support for loading some plugins using `-Q` (notably Ltac2 if we ship it with Coq).

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Review by ejgallego — CHANGES_REQUESTED** [review]
I don't like having a configure-time list of plugins; why is that needed?

Other than the bug fix [which looks correct] the patch doesn't seem to change much, maybe if you say more about your use case we could understand what this PR brings.

**Comment by maximedenes** [comment]
> I don't like having a configure-time list of plugins; why is that needed?

I'm not sure I understand. This PR does not introduce any configure-time list of plugins. It simply changes the way we iterate over the content of the `plugins` folder.

The point of the PR is to make it possible to use `-Q` to bring plugins in scope, rather than `-R`, for some plugins. Doing it for all is what we want in the long term, but it will break some developments.

Do you want me to change something in this PR?

**Comment by maximedenes** [comment]
You're right that the approach needs to be refined. I'll separate the fix so that we can integrate it meanwhile.

**Comment by ejgallego** [comment]
I will take this following up discussion at CoqPL.

**Comment by ejgallego** [comment]
@maximedenes I'd say this PR can be closed, right? [I mean, none of the code here will resemble the solution we discussed about]

IMHO a `vendor/` directory could be the way to go.

**Comment by ejgallego** [comment]
Closing as to avoid PRs as issues; this will need some design indeed.

**Comment by maximedenes** [comment]
> IMHO a `vendor/` directory could be the way to go.

Yep, will explore that. Closing.

**Pull request closed without merging**
