### PR TITLE
configure: make -annotate fatal, and color error and warnings

### PR DESCRIPTION
**Pull request by SkySkimmer**
Warnings are just too hard to see. Also there is no point keeping a
noop option except to point people at the replacement, which does not require configure to succeed.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
(prompted by a recent coqclub thread where someone was confused due to not noticing the -annotate warning)

**Comment by Zimmi48** [comment]
@ejgallego Can you take over as the secondary maintainer for `./configure`?

**Comment by ejgallego** [comment]
> @ejgallego Can you take over as the secondary maintainer for ./configure?

No problem.

**Review by ejgallego — APPROVED** [review]
I think this is ready to merge, @SkySkimmer ?

**Comment by SkySkimmer** [comment]
Should be.

**Pull request merged**
