### PR TITLE
more descriptive universe length mismatch message

### PR DESCRIPTION
**Pull request by Alizter**
We now also print the length of the provided universes which can make it easier to amend universe contexts when things change.

- [x] Added / updated **test-suite**.

- [x] Added **changelog**.
- [x] Added / updated **documentation**.
  
  - [x] Documented any new / changed **user messages**.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by Alizter** [comment]
I added a universe length mismatch error to `univGen` that can be used where we error on differing universe lengths.

**Comment by SkySkimmer** [comment]
Still needs squashing

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
I didn't see that mtac2 failure, was that related?

**Pull request merged**
