### PR TITLE
Fix handling of anticipate objects in sealed modules

### LINKED ISSUE #17273: Anomaly unknown constant with Require in opaque module
~~~coq
Module Type T.
 Parameter f : forall {A} {B : A -> Type},
   forall (f g : forall x : A, B x),
     (forall x, f x = g x) -> f = g.
End T.

Module M : T.
  Require Import FunctionalExtensionality.
  Definition f := @functional_extensionality_dep.
End M.

Print Assumptions M.f.
~~~
For some reason we drop the anticipate objects (ie Require) when the module is opaque, probably we should keep them.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17273

### CODE REVIEW

**Comment by ppedrot** [comment]
Just out of safety: @coqbot bench

**Comment by SkySkimmer** [comment]
(failures are because of the find_map PR and overlays)

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer you're talking about CI failures as well, right? This is mergeable AFAIU, correct me otherwise.

**Comment by SkySkimmer** [comment]
I mean the metacoq (and cat-theory) failures in the bench, from failing dependency equations. This is mergeable.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
