### PR TITLE
[toplevel] [emacs] Don't quote errors in emacs mode.

### PR DESCRIPTION
**Pull request by ejgallego**
In 8.6 + emacs, errors were quoted sometimes with special
markers (e.g. `Print Module foo.` for a non-existing `foo`)

In 8.7 we uniformized error handling and now all errors are quoted,
however, this behavior confuses emacs as it seems that the quotes are
meant to be applied only to warnings.

We thus reflect the de-facto situation, removing quoting for errors
and updating the code so it is clear that the quoter is a warnings
quoter.

This fixes ProofGeneral for trunk users.

c.f. https://github.com/ProofGeneral/PG/issues/175

### CODE REVIEW

**Comment by maximedenes** [comment]
Why does @hubot appear as having pushed this merged? Are we having a security problem?

**Comment by Zimmi48** [comment]
@maximedenes I hope that's just a display bug but it would probably make sense to report this to GitHub immediately: https://github.com/contact

**Comment by ejgallego** [comment]
Maybe this is a good moment for you to start signing merges.

**Comment by maximedenes** [comment]
@ejgallego I started to sign them a few weeks ago :p

**Comment by ejgallego** [comment]
Oh in fact I don't have your key, where can I get it securely?

**Comment by ejgallego** [comment]
you may consider adding it to GitHub too

**Comment by ejgallego** [comment]
never mind I see it's there...

**Comment by Zimmi48** [comment]
So the question of @coqbot vs @hubot is not so who merges the PR but rather who pushes from gforge to GitHub. If GitHub were not a mirror, we would see @maximedenes merged the PR, not @coqbot merged the PR.

**Pull request merged**
