### PR TITLE
Infrastructure for ocamldebug on the checker

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
Nobody willing to assign this PR to himself?

**Comment by herbelin** [comment]
> Nobody willing to assign this PR to himself?

Don't know if @letouzey is online. I can merge it otherwise. @SkySkimmer: you tested it and we can thus merge it as it, right?

**Comment by SkySkimmer** [comment]
>@SkySkimmer: you tested it and we can thus merge it as it, right?

Yes

**Comment by herbelin** [comment]
OK, shall do around tomorrow noon if noone objects.

**Pull request merged**
