### PR TITLE
Move abstract out of tactics.ml

### PR DESCRIPTION
**Pull request by SkySkimmer**
tactics.ml is too big:
- tools slow down 
- it's hard to figure out how it's organized

This is a step towards reducing the problem.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Agreed.

**Comment by herbelin** [comment]
`tactics.ml` is indeed too big. Alternative names could also be `abstracttac.ml`, `tacabstract.ml`, `tacAbstract.ml`, .... Maybe, the naming scheme shall also depend on which names shall be used for further steps of split of `tactics.ml` (which shall be a difficult task: for instance,`intro_patterns` is already internally using forward hooks),

**Comment by ejgallego** [comment]
If we start to wrap libs that would be called `Tactics.Abstract` which IMHO looks pretty good.

**Comment by herbelin** [comment]
> Tactics.Abstract 

Yes, that'll be good.

**Review by gares — APPROVED** [review]

**Comment by JasonGross** [comment]
I think this also needs an overlay for fiat-parsers that updates the relevant `.ml{,4}.master` files

**Comment by SkySkimmer** [comment]
How does the fiat-parsers versioning work? There are 810, trunk and master files around.

**Comment by JasonGross** [comment]
trunk is outdated from back when the branch was called trunk.  The 810 and master files should be updated.

**Comment by JasonGross** [comment]
(Currently 810 and master files are identical.  I think we use master as a fallback.)

**Comment by JasonGross** [comment]
What's the policy on whether backwards-incompatible overlays should be merged before or after the relevant PR in Coq?  (I have a slight preference for after, to keep fiat's CI working, but I could be convinced merge before)

**Comment by Zimmi48** [comment]
@JasonGross The policy is to merge the overlay right after.

**Pull request merged**
