### PR TITLE
[dev] shorten names of shims

### PR DESCRIPTION
**Pull request by Alizter**
The added `-prelude` suffix was wearing out my fingers.

### CODE REVIEW

**Comment by ejgallego** [comment]
The idea was to denote that we were also building the prelude. I'm OK with the change, but a bit afraid of breaking everyone's workflow.

[I myself never have to type this, I have it aliased obviously]

**Comment by ppedrot** [comment]
> [I myself never have to type this, I have it aliased obviously]

Despite having read and reread the dune documentation and the `build-system-dune.md` file from the Coq repo, I still don't understand how you can do that. You cannot obviously modify the dune files by hand because this is stored in the git repo, and you can't do that globally because the dune-config file doesn't talk about rules (and hence aliases). I am utterly clueless about the whole dune stuff, and no amount of reading seems to solve it. Do you have a big folder with all the Coq developments as subfolders and a bunch of dune files at toplevel?

**Comment by Alizter** [comment]
@ppedrot I think @ejgallego is talking about a bash alias rather than a Dune one.

**Comment by ejgallego** [comment]
@ppedrot indeed I have the dune setup configured in my IDE, to my taste. What are you trying to do?

**Review by gares — APPROVED** [review]
It would be nice to keep the old one but error out a help message

**Comment by Alizter** [comment]
@gares Sure I can do that.

**Comment by Alizter** [comment]
I've added a message but I will push after https://github.com/coq/coq/pull/16630 since it saves me rebasing.

**Comment by SkySkimmer** [comment]
Missing mention in https://github.com/coq/coq/blob/master/dev/doc/build-system.dune.md#quick-start

**Review by ejgallego — APPROVED** [review]
LGTM.

I'd be nice if we could use `dune coq top` tho, a way to do that is to allow the bootstrap to actually use the built-in Dune Coq mode, when a dev requests it.

**Comment by Alizter** [comment]
@ejgallego `dune coq top` is only available from 3.1.0. Until we bump our minimal Dune version, I won't change the shims to use it. It also won't work correctly since we are generating our own Dune rules and not using the coq.theory stanza.

**Comment by ejgallego** [comment]
> @ejgallego `dune coq top` is only available from 3.1.0. Until we bump our minimal Dune version, 

devs can use (and should) more recent dune versions.

> I won't change the shims to use it.

Indeed, the shims shouldn't use it, devs should directly call `dune coq top`

> I also don't think it will work correctly since we are generating our own Dune rules and not using the coq.theory stanza.

That's why I suggested that maybe we could make the bootstrap process to generate `(coq.theory` in some cases such that command becomes usable. (On a different PR)

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by SkySkimmer** [comment]
>Indeed, the shims shouldn't use it, devs should directly call dune coq top

The shim works fine for me, why would I change?

**Comment by ejgallego** [comment]
> The shim works fine for me, why would I change?

`dune coq top` can build the deps for any file which the shims can't do as of today.

**Comment by SkySkimmer** [comment]
I never want that though

**Comment by ejgallego** [comment]
> I never want that though

Yeah not useful for you. I can see myself using it for a few cases, such as running test-suite files quick and interactively. In the end it is nothing else than on-the-fly rule generation + a build.

**Pull request merged**
