### PR TITLE
Alternative implementation of the Micromega persistent cache

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of loading the whole file in memory, we simply load an index table associating a file position to a key hash. Cache access is then performed on the fly by unmarshalling the data whose hash corresponds and checking key equality.

This source of memory consumption was identified in perennial, which was recently failing regularly with OOM errors.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
It would be nice to combine with https://github.com/coq/coq/pull/13233 for benching

**Comment by ppedrot** [comment]
The memory bench is not very precise though, it has a strong tendency to wildly swing in ranges that can reach 10-15% of the average. I don't know whether this PR will be distinguishable from this kind of noise. (Maybe we could ask Coq to dump the OCaml GC stats instead of trying to track it externally via perf...)

**Comment by SkySkimmer** [comment]
>The memory bench is not very precise though, it has a strong tendency to wildly swing in ranges that can reach 10-15% of the average. I don't know whether this PR will be distinguishable from this kind of noise. (Maybe we could ask Coq to dump the OCaml GC stats instead of trying to track it externally via perf...)

We would see if there's an impact on time at least.

**Comment by ppedrot** [comment]
It seems I need to regenerate the cache for the test-suite to go through, but I don't know how to do that.

**Comment by fajb** [comment]
Could it be `.csdp.cache.test-suite` ? Which would be a copy of your locally generated `.csdp.cache`.

**Comment by ppedrot** [comment]
The git hook that checks for newlines seems to be unhappy with binary files and potentially messing with them.

**Comment by ppedrot** [comment]
Bench is meh:
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │    mem faults     │
│                             │                         │                                             │                                             │                               │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-coquelicot │   67.66   68.13 -0.69 % │      185362529804      185649199173 -0.15 % │      236042095122      236042016124 +0.00 % │     566000     565908 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  169.55  170.48 -0.55 % │      472611688693      473593677263 -0.21 % │      668230077473      668267525015 -0.01 % │     662332     662300 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-coqutil │   60.09   60.36 -0.45 % │      166881623082      167168142746 -0.17 % │      208425735694      208395077660 +0.01 % │     523392     524716 -0.25 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  363.52  364.36 -0.23 % │     1021786885672     1025374921922 -0.35 % │     1741695145777     1746146717025 -0.25 % │    3991768    3996324 -0.11 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  140.14  140.41 -0.19 % │      390216275171      389957768262 +0.07 % │      500794958161      500670644800 +0.02 % │     546836     546920 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-verdi │  102.30  102.44 -0.14 % │      282024140105      282598167395 -0.20 % │      396884103411      396722478253 +0.04 % │     550228     550540 -0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1240.90 1242.46 -0.13 % │     3453272193843     3458634574136 -0.16 % │     4923934050658     4922716678198 +0.02 % │    1113772    1100296 +1.22 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   47.56   47.61 -0.11 % │      131807669909      131595134605 +0.16 % │      181458559228      181489891574 -0.02 % │     480168     481356 -0.25 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  223.58  223.76 -0.08 % │      621782485671      622554061625 -0.12 % │      945280694949      945302371475 -0.00 % │     672964     672904 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-compcert │  641.30  641.73 -0.07 % │     1788192887171     1789439623760 -0.07 % │     2469428157770     2468714415244 +0.03 % │    1047592    1047556 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2540.99 2542.63 -0.06 % │     7084260540986     7088592503780 -0.06 % │    11781918321180    11781539870850 +0.00 % │     723852     723840 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1444.59 1445.21 -0.04 % │     4030782066058     4031470480200 -0.02 % │     6136917315559     6137035321100 -0.00 % │    1020480    1023944 -0.34 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1047.07 1047.27 -0.02 % │     2916343062679     2916759679578 -0.01 % │     4645960460783     4645832016361 +0.00 % │     976472     976240 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                         coq │  519.39  519.34 +0.01 % │     1455632273814     1456333297793 -0.05 % │     1952650070837     1953521083839 -0.04 % │     578596     578428 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  155.87  155.78 +0.06 % │      433391658365      433009368781 +0.09 % │      600305433118      600298463099 +0.00 % │     716872     716676 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-color │  511.79  511.29 +0.10 % │     1427001771622     1427192579294 -0.01 % │     1791865242382     1796718410054 -0.27 % │    1077408    1077548 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-hott │  321.23  320.82 +0.13 % │      873192350085      872547692361 +0.07 % │     1419600695887     1419537160680 +0.00 % │     672016     671564 +0.07 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-unimath │ 3937.18 3931.32 +0.15 % │    10954648130975    10942053838563 +0.12 % │    20979006799907    20977715275200 +0.01 % │    1144152    1126696 +1.55 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1225.89 1223.96 +0.16 % │     3413617221395     3408676470639 +0.14 % │     4840735590822     4836872742718 +0.08 % │     899580     899184 +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-corn │ 1627.04 1624.40 +0.16 % │     4524096424888     4521702715968 +0.05 % │     6937152626913     6936240475463 +0.01 % │     840908     840276 +0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  630.83  629.74 +0.17 % │     1766052433124     1763874729365 +0.12 % │     2662696716207     2661900895400 +0.03 % │    3257232    3257200 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-rewriter │  718.48  717.22 +0.18 % │     1992777681862     1991358688446 +0.07 % │     3046782021610     3046357917940 +0.01 % │     990788     986040 +0.48 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 5064.46 5052.94 +0.23 % │    14069187998360    14042022867521 +0.19 % │    24272426420461    24241665020229 +0.13 % │    2271984    2270760 +0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  790.48  788.50 +0.25 % │     2199911621408     2196289049649 +0.16 % │     3415347010522     3415481077552 -0.00 % │     985356     985336 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-math-classes │  213.26  212.47 +0.37 % │      592840625776      593003764615 -0.03 % │      812134798750      812123302701 +0.00 % │     506792     506664 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   51.02   50.82 +0.39 % │      138824872722      138689777880 +0.10 % │      175781560920      175705629561 +0.04 % │     514444     514416 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fiat-core │  102.79  102.30 +0.48 % │      291521579415      290853956599 +0.23 % │      386659239593      386104778129 +0.14 % │     480464     480144 +0.07 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-bignums │   57.36   56.98 +0.67 % │      157713932603      157224953146 +0.31 % │      211285481085      211041856399 +0.12 % │     467920     470076 -0.46 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-flocq │  158.08  156.30 +1.14 % │      438957209173      434532785049 +1.02 % │      546553705902      541481915229 +0.94 % │     823904     823060 +0.10 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-coqprime │   80.88   79.87 +1.26 % │      221644746162      218674020022 +1.36 % │      312637713897      306552380437 +1.99 % │     760780     761168 -0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  226.64  222.49 +1.87 % │      627172545101      616419029507 +1.74 % │     1037471390960     1023255373459 +1.39 % │    1088872    1088844 +0.00 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴───────────────────┘
```
I confirm that nonetheless this shaves off quite a bit of constant memory consumption at startup in perennial (in the range of ~ 200 Mio). Maybe we could try to simply deactivate the cache by default?

**Comment by SkySkimmer** [comment]
No perennial in bench?

**Comment by ppedrot** [comment]
Nope, it was not part of the bench at the time. I can rerun it, but once again memory consumption is unlikely to be observable in our current infrastructure (... and by the way adding a precise memory profiling requires https://github.com/coq/coq/pull/13420).

**Comment by ppedrot** [comment]
Bench restricted to perennial running at https://gitlab.com/coq/coq/-/jobs/864295615.

**Comment by ppedrot** [comment]
Note that the slowdowns are real, it's not merely noise. Here is the list of the 10 major slowed down lines in the above bench by absolute value.
```
html/coq-fiat-crypto/src/Rewriter/RulesProofs.v.html:682 0.76 3.97 4.73 (19%)
html/coq-rewriter-perf-SuperFast/src/Rewriter/Rewriter/Wf.v.html:510 0.83 34.50 35.33 (2%)
html/coq-fiat-crypto/src/Arithmetic/FancyMontgomeryReduction.v.html:106 0.84 1.76 2.60 (47%)
html/coq-bedrock2/bedrock2/src/bedrock2Examples/bsearch.v.html:252 0.84 3.20 4.04 (26%)
html/coq-corn/model/Zmod/ZGcd.v.html:1328 0.88 2.40 3.28 (36%)
html/coq-fiat-crypto/src/Rewriter/RulesProofs.v.html:769 1.06 3.52 4.58 (30%)
html/coq-fiat-crypto/src/Rewriter/Passes/Arith.v.html:23 1.32 50.82 52.14 (3%)
html/coq-bedrock2/bedrock2/src/bedrock2Examples/bsearch.v.html:270 1.42 2.56 3.99 (56%)
html/coq-fiat-crypto/src/Rewriter/RulesProofs.v.html:593 2.61 13.92 16.53 (19%)
html/coq-fiat-crypto/src/Arithmetic/BarrettReduction.v.html:487 4.18 5.30 9.48 (79%)
```

**Comment by ppedrot** [comment]
After a bit of profiling, we can probably do better. BarrettReduction access counts to the cache are:
- 4094 total accesses
- 4043 (98.75%) cache hits
- 3649 (89.13%) live cache hits

where the last case corresponds to accesses to the cache that have already been accessed once before. Currently we don't keep the cache hits in memory, so that we have to systematically unmarshal data on a cache hit. Given that most of the hits are "live", if we kept the cache hits in memory we would't have to pay for I/O, while keeping a reasonably low memory profile (i.e. not crazy loading of whatever unrelated data from the disk cache). I'll have a try at that.

**Comment by ppedrot** [comment]
New bench:
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  140.02  140.44 -0.30 % │      389780734655      389994164754 -0.05 % │      500664359177      500691990489 -0.01 % │     545668     545252  +0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-perennial │ 5262.22 5276.04 -0.26 % │    14634403759313    14678518618025 -0.30 % │    21915354256756    22038029525174 -0.56 % │    2963432    3453592 -14.19 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   79.62   79.79 -0.21 % │      218784182289      218889929673 -0.05 % │      307235196161      307276002754 -0.01 % │     764184     764268  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   67.80   67.93 -0.19 % │      185727840044      185865797188 -0.07 % │      236736208215      236698999284 +0.02 % │     565312     565408  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   60.74   60.84 -0.16 % │      169019912847      168813966650 +0.12 % │      209073316122      209045229123 +0.01 % │     524192     524404  -0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 3935.66 3941.98 -0.16 % │    10952021139492    10966400452971 -0.13 % │    20978339232607    20979759255745 -0.01 % │    1142240    1139112  +0.27 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1619.98 1622.50 -0.16 % │     4508749277885     4513120116617 -0.10 % │     6926693095817     6938959514378 -0.18 % │     847872     852756  -0.57 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1225.86 1227.32 -0.12 % │     3413597062143     3414487087216 -0.03 % │     4836848755624     4838813382577 -0.04 % │     900068     900472  -0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  784.89  785.79 -0.11 % │     2187985183612     2188986857494 -0.05 % │     3417860379550     3417694443703 +0.00 % │     977180     977116  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  222.44  222.68 -0.11 % │      615530551036      615700139114 -0.03 % │     1022450330262     1023857258613 -0.14 % │    1085236    1085084  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 5043.69 5049.12 -0.11 % │    14013821414449    14027528841031 -0.10 % │    24233349198901    24259640958788 -0.11 % │    2274244    2271624  +0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1238.10 1239.43 -0.11 % │     3446563006274     3449065724815 -0.07 % │     4937700324444     4932994090558 +0.10 % │    1095684    1112236  -1.49 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  156.87  157.00 -0.08 % │      435674189057      436275488605 -0.14 % │      541772612388      542082332934 -0.06 % │     820744     820772  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  212.65  212.78 -0.06 % │      592064990987      592129396634 -0.01 % │      812826148138      812809577206 +0.00 % │     506204     506120  +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  512.32  512.45 -0.03 % │     1428040945741     1428984330462 -0.07 % │     1794008248216     1798089634541 -0.23 % │    1077884    1132624  -4.83 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  716.65  716.80 -0.02 % │     1990984361249     1986971830032 +0.20 % │     3051358521161     3050697412190 +0.02 % │     989484     989436  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  170.02  170.03 -0.01 % │      472553119256      473033085071 -0.10 % │      668441417874      668442881455 -0.00 % │     660072     682768  -3.32 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  155.47  155.47 +0.00 % │      432104927139      432181747375 -0.02 % │      599858741191      599880503161 -0.00 % │     711792     711380  +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  630.49  630.40 +0.01 % │     1765769526223     1765541087234 +0.01 % │     2669273039465     2668808313546 +0.02 % │    3639320    3639404  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1045.64 1045.18 +0.04 % │     2912855244687     2910357120574 +0.09 % │     4647821359861     4647805634880 +0.00 % │     974184     974100  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1447.43 1446.67 +0.05 % │     4033759413509     4028035356871 +0.14 % │     6138096456370     6137966820856 +0.00 % │    1023588    1023268  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2558.72 2557.23 +0.06 % │     7133355300489     7122417672669 +0.15 % │    11797334575161    11797071954147 +0.00 % │     722368     722372  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  640.68  640.11 +0.09 % │     1786638984218     1784397507079 +0.13 % │     2470258503179     2470201171187 +0.00 % │    1046908    1047020  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  363.70  362.96 +0.20 % │     1022862982850     1020775750918 +0.20 % │     1744639474285     1746525711882 -0.11 % │    3978924    3978840  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  223.22  222.55 +0.30 % │      620756133056      620214137334 +0.09 % │      945629559678      945594634457 +0.00 % │     675596     675480  +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   57.44   57.26 +0.31 % │      158683919434      158145293891 +0.34 % │      211367318129      211677338051 -0.15 % │     479244     481280  -0.42 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  522.41  520.36 +0.39 % │     1460666796838     1458536368197 +0.15 % │     1953225073318     1954848990981 -0.08 % │     562468     562032  +0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  321.87  320.03 +0.57 % │      872159694273      871084916832 +0.12 % │     1419644431914     1420532603220 -0.06 % │     665428     723092  -7.97 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  103.09  102.47 +0.61 % │      282778139609      281976014087 +0.28 % │      397597438897      397430943099 +0.04 % │     547192     547316  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   47.73   47.39 +0.72 % │      131758624536      131529063685 +0.17 % │      181500369899      181525813020 -0.01 % │     480696     480672  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  102.64  101.86 +0.77 % │      292377372121      290937620861 +0.49 % │      387294815658      387033055730 +0.07 % │     479828     479788  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   51.06   50.56 +0.99 % │      138736333730      138389013165 +0.25 % │      176413037466      176333136895 +0.05 % │     511344     513520  -0.42 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```

Perennial indeed has a  -14.19 % top memory reduction.

**Comment by ppedrot** [comment]
This needs a assignee, I consider this PR ready.

**Review by vbgl — APPROVED** [review]
This needs a changelog entry, at least to state that old caches should be disposed of.

**Comment by fajb** [comment]
@ppedrot  the percentage of cache hit is surprisingly high; especially, on a non-interactive context. Investigation for another time.

For the code, I had only a very quick look. Looks good to me!
I understand there is a memory tradeoff but do you any idea what would happen if instead of doing `skipblob` you would keep the `bytes` and only parse them on-demand?

About `perennial`, is the cache so big? The next question is: why?

**Comment by ppedrot** [comment]
> the percentage of cache hit is surprisingly high; especially, on a non-interactive context. Investigation for another time.

Given the additional profiling data on tactics, I suspect that these developments perform a lot of eauto proof search with leaves that call lia , so a lot of branches are revisited many times. I don't have an actual proof of that though.

> what would happen if instead of doing skipblob you would keep the bytes and only parse them on-demand?

I am not sure I understand the proposal. Isn't it what the PR does?

> About perennial, is the cache so big? The next question is: why?

At the end of the perennial compilation chain, from the top of my head, the cache was almost 300 Mio once unmarshalled, and a factor of 10 smaller on disk. A flat 300 Mio per-process memory toll ends up being a large fraction of your memory when each process uses 2 Gio of RAM and you call several instances of coqc in parallel. As for the why, it's just that there are a lot of calls to lia in perennial, multiply that by a lot of files, and there you go.

Also I am not sure that sharing the results on disk really make sense in general. We could try to have three possible states for the cache, i.e. in addition to no cache / on-disk cache as of today, a third in-memory cache flag where the cache is only kept for one coqc invocation but never marshalled on disk. I don't know how often we have a cache hit for something that comes from the disk, but I'd bet not a lot.

**Comment by ppedrot** [comment]
@vbgl added a changelog. I don't know whether it's very important since a cache using the previous structure will be automatically regenerated because it will fail to unmarshall.

**Comment by fajb** [comment]
> I am not sure I understand the proposal. Isn't it what the PR does?

It seems you drop the bytes (`skipblob`). Instead, you could  store the blob in memory and parse (`Marshal.from_bytes`?) only if the hash is accessed. I guess that would  use more memory.

> Also I am not sure that sharing the results on disk really make sense in general. We could try to have three possible states for the cache, i.e. in addition to no cache / on-disk cache as of today, a third in-memory cache flag where the cache is only kept for one coqc invocation but never marshalled on disk. 

For the bench, I agree, using only in-memory caches should be enough. 
Before your explanation about cache hits, I would have not have imagined that caches would be useful for coqc, at all.

**Comment by fajb** [comment]
> @vbgl added a changelog. I don't know whether it's very important since a cache using the previous structure will be automatically regenerated because it will fail to unmarshall.

I am always a bit afraid by the absence of type safety of unmarshal. If you are sure this will fail, that's good.

**Comment by ppedrot** [comment]
You'd be pretty unlucky to hit a magic number at random. I know 2³² is considered ridiculously small for crypto, but that's still fairly uncommon. And furthermore there are other checks in the marshalled data header that would likely fail.

**Comment by vbgl** [comment]
@coqbot: merge now

**Pull request merged**
