### PR TITLE
Make `change` create a cast node

### LINKED ISSUE #13984: `change T` should leave `REVERTcast`
All the other reduction tactics do, `change` (in the goal) should as well.  At least the version that's not doing `change x with y`, though ideally that version too.  See https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/How.20to.20Debug.20slow.20QED.3F/near/231488512 for more discussion.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13984

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by MSoegtropIMC** [comment]
I see that this increases time/cycles/memory for  few projects. Would it make sense to add an option to not create a cast? IMHO the cast should be there by default, though.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by Alizter** [comment]
I think it is a good idea, but I guess needs some more investigation. Have you got any unexplored ideas that you can summarise for anybody else who wants to take over?

**Comment by SkySkimmer** [comment]
see the issue

**Pull request closed without merging**
