### PR TITLE
[ssr] Remove no longer used not_locked_false_eq_true

### PR DESCRIPTION
**Pull request by proux01**
Successfully tested on math-comp CI: https://github.com/math-comp/math-comp/pull/1246

- ~[ ] Added / updated **test-suite**.~

- [x] Added **changelog**.
- [x] Added / updated **documentation**.
  
  - ~[ ] Documented any new / changed **user messages**.~
  - ~[ ] Updated **documented syntax** by running `make doc_gram_rsts`.~

#### Overlays (to be merged before the current PR)

* https://github.com/math-comp/analysis/pull/1262
* https://github.com/math-comp/bigenough/pull/12
* https://github.com/coq-community/graph-theory/pull/41

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by proux01** [comment]
@CohenCyril could yo please merge the last remaining overlay on bigenough: https://github.com/math-comp/bigenough/pull/12

**Comment by proux01** [comment]
@coqbot bench now

**Comment by proux01** [comment]
@coqbot bench now

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
As expected, bench shows nothing / a tiny speedup.

CI green, this is ready, @gares would you be the assignee?

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I would still write a changelog entry, after all there are overlays

**Comment by gares** [comment]
Sorry @proux01 it seems you forgot to git add.

**Comment by proux01** [comment]
Indeed, thanks for noticing, done

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
