### PR TITLE
Reduce the number of calls to canonical-observing functions outside of kernel

### PR DESCRIPTION
**Pull request by ppedrot**
A cleanup from my attic.

Overlays:
- https://github.com/mattam82/Coq-Equations/pull/536
- https://github.com/Mtac2/Mtac2/pull/376

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
I don't think it's a change serious enough to deserve a specific entry.

**Review by JasonGross — APPROVED** [review]
Approving changes to the numbers code.  There are no performance implications, right?  `Environ.QGlobRef.equal` is not doing anything asymptotically slower (or with much larger constants)?

**Comment by ppedrot** [comment]
This code change is the identity, it just marks pieces of code that implicitly depend on the quotient from an environment.

**Comment by SkySkimmer** [comment]
A future code change will do some lookups in a map from the passed environment.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
