### PR TITLE
Fix version switcher when building with Dune.

### LINKED ISSUE #12395: [refman] Version switcher is broken
The version switcher doesn't appear anymore on https://coq.github.io/doc/master/refman/ and https://coq.github.io/doc/v8.12/refman/. I assume this is a consequence of the update of the version of the theme (part of #12224 that we failed to notice when reviewing the output of this PR).

cc @cpitclaudel (is this something that you think would be easy to fix)

### PR DESCRIPTION
**Pull request by Zimmi48**
Closes #12395.

@ejgallego I don't understand why Dune ignored the sub-directory named `_templates`. I didn't find any doc of this being an expected behavior. Should I report a bug to Dune?

### CODE REVIEW

**Comment by ejgallego** [comment]
This is documented, you can use `(dirs ...)` to enable directories starting with `_`. 

https://dune.readthedocs.io/en/stable/dune-files.html#dirs-since-1-6

**Comment by Zimmi48** [comment]
OK thanks. What puzzled me is that `_static` seemed to be correctly copied OTOH.

**Comment by ejgallego** [comment]
> OK thanks. What puzzled me is that `_static` seemed to be correctly copied OTOH.

It is already present in `doc/sphinx/dune` `(dirs ...)` stanza.

**Comment by ejgallego** [comment]
So you may want to avoid the renaming.

**Comment by Zimmi48** [comment]
> It is already present in `doc/sphinx/dune` `(dirs ...)` stanza.

Oh! I'm so used to looking at the `doc/dune` file that I forgot that there was a dune file in `doc/sphinx` as well.

**Comment by Zimmi48** [comment]
That makes for a much simpler fix.

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
