### PR TITLE
[api] Deprecate a couple of aliases that we missed.

### PR DESCRIPTION
**Pull request by ejgallego**
We missed a couple of functions in the "big deprecation". IMHO it would be worth the effort to update this so we can clean up at once in 8.9.

Risk is very low as this only adds more warnings.

### CODE REVIEW

**Comment by ejgallego** [comment]
This was **silently** re-milestoned but as no reason was given I'd ask the RMs to reconsider, missing this deprecation warnings will incur in a _lot_ of extra load over two releases for little benefit.

**Comment by SkySkimmer** [comment]
How do aliases generate "a lot of load"? I consider them more as an annoyance, maybe not even that for type aliases.

**Comment by ejgallego** [comment]
> How do aliases generate "a lot of load"? I consider them more as an annoyance, maybe not even that for type aliases.

Going to an extra deprecation phase is what will generate the load. In 8.9, when removing the deprecated aliases we'll have to do a pass on all plugins as to fix the warnings first so they compile when the deprecated stuff is removed. If we miss this couple of forgotten aliases, we'll have to do a second alias removal pass in 8.10. Thus double the work for no actual gain.

A third option of course is just not giving a damn.

**Review by gares — APPROVED** [review]

**Review by gares — CHANGES_REQUESTED** [review]
whitespace lint, the rest is ok

**Comment by ejgallego** [comment]
Linter fixed; rebased; still requesting 8.8.0 consideration.

**Comment by maximedenes** [comment]
> This was silently re-milestoned but as no reason was given I'd ask the RMs to reconsider

Sorry, I did it silently because I just didn't have the concrete time to do it for 8.8+beta1, but indeed I'll think about it and read the patch for 8.8.0.

**Comment by maximedenes** [comment]
FTR, I proposed an amendment of the merging process in #7052 that would typically cover this kind of PRs, reducing the number of required code owners review to 1.

**Comment by ejgallego** [comment]
I think that my strategy will be to assign this to the current RM.

**Review by maximedenes — APPROVED** [review]
I reviewed the patch, it looks ok to me. It consists in a few systematic renamings across the codebase, I don't think a review of all maintainers is required. I'm also ok to put it in 8.8.0, since the risk is virtually non-existent (a few renamings of aliased functions and types, and a few more OCaml warnings).

**Comment by maximedenes** [comment]
Since other maintainers are concerned (although I don't think their review is required), I'll leave a bit of time before merging.

**Review by herbelin — COMMENTED** [review]
OK with @maximedenes' proposal (not surveying all details then). (And thanks for the "bit of time" :heart:.)

**Comment by Zimmi48** [comment]
Putting the 8.8.0 milestone following @maximedenes' decision.

**Review by mattam82 — APPROVED** [review]
Fine with me too.

**Pull request merged**
