### PR TITLE
Print info about dependant section variables in Print/About

### LINKED ISSUE #16165: Provide a way to display dependencies on section variables before the section is closed
@Blaisorblade [says](https://github.com/coq/coq/issues/16163#issuecomment-1151602171) "that would seem a useful usability enhancement — especially when the `Proof using` command does not list assumptions explicitly, but uses wildcards like `Type*`."

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16165

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@RalfJung could you add 
~~~sed
# coq/coq#16208 (this regex deletes an empty line followed by the "uses section variable" line)
/^$/{N;/.* uses section variable.*/d}
~~~
or similar to the test normalizer seds?

**Comment by RalfJung** [comment]
Sorry for the long delay.

Unfortunately that pattern breaks the [test output on Coq 8.13](https://gitlab.mpi-sws.org/iris/iris/-/jobs/193775), probably because handling empty lines here means other patterns don't get to run after empty lines. I think the pattern should just match a single line, these multi-line things are too fragile.

**Comment by RalfJung** [comment]
Oh, [looking at the output](https://github.com/coq/coq/pull/16208/checks?check_run_id=6967771084) there are new empty lines here. That is odd, isn't it?
```
test_op_3 =
{[10 := {[20 - 2 := [11]; 1 := [22]]};
  20 := {[99 + length [1] := [1; 2; 3]]};
  4 := {[4 := [4]]};
  5 := {[5 := [5]]}]}
     : M (M (list nat))

test_op_3 uses section variables M H1 H2.
```
Both of these refer to the same thing, but they are spaced apart as if they were separate. Why that?

**Comment by SkySkimmer** [comment]
The shape of Print output is 
~~~
name =
body

meta info
~~~
but if `meta info` is empty there is no empty line.
The empty line is to provide separation between the body and the meta info.

**Comment by SkySkimmer** [comment]
This normalizer stuff is such a hack, every time it is a pain to update. Why not have a .ref per tested Coq version instead?

**Comment by RalfJung** [comment]
> The empty line is to provide separation between the body and the meta info.

However when I `Print` 5 things, Coq adds no separation between these 5 things. So then it looks really odd, as if the meta info of one variable was attached to the printing of the next.

> Why not have a .ref per tested Coq version instead?

That would mean everyone who wants to contribute to Iris and changes tests needs to have 4-5 versions of Coq installed and re-build everything withe each version to update the reference files. Iris/stdpp++ changes more frequently than Coq output.

I agree it is annoying, but I haven't found a better way yet. :/  We do need these output tests, some aspects of a Coq library just cannot be reliably tested otherwise (and things like notation and Ltac errors are super easy to break accidentally so they do need tests).

I have now pushed https://gitlab.mpi-sws.org/iris/stdpp/-/commit/c4055887b620efc04310e73e4f8682ae6cad1b73, that should also help I hope? Not sure if we have other section variable printing terms in Iris itself.

**Comment by SkySkimmer** [comment]
>However when I Print 5 things, Coq adds no separation between these 5 things. So then it looks really odd, as if the meta info of one variable was attached to the printing of the next:

In interactive mode there is no confusion since they get run one at a time. I don't know what would be a nice solution for batch mode, maybe the printer could add an extra newline at the end of each message?

**Comment by RalfJung** [comment]
> I have to first propagate it through to iris/examples

I did that now, so if you restart CI it should pick up the new std++.

**Comment by SkySkimmer** [comment]
The iris job hasn't started yet, no need to restart

**Comment by SkySkimmer** [comment]
Doesn't work? (The job used https://gitlab.mpi-sws.org/iris/stdpp/-/commit/c4055887)

**Comment by SkySkimmer** [comment]
Maybe `Eval cbv delta [foo] in @foo` instead of `Print foo` would be more stable (doesn't print the metadata)

**Comment by RalfJung** [comment]
So `Let` terms are also considered section variables? :/

**Comment by SkySkimmer** [comment]
Thy probably shouldn't as 
~~~coq
Section S.
  Let x := 0.
  Lemma foo : nat.
  Proof using.
    exact x.
  Qed.
~~~
is accepted.

**Comment by SkySkimmer** [comment]
Changed to not print section letins.

**Comment by Alizter** [comment]
merging soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
