### PR TITLE
Trying to properly propagate errors in Windows CI script.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Wow! Goto programming to emulate `set -e` on Windows!

**Comment by maximedenes** [comment]
Goto is idiomatic batch...

**Comment by gares** [comment]
We all know that structured control flow is for wimps [since '66](https://en.wikipedia.org/wiki/Structured_program_theorem) ;-)

**Comment by SkySkimmer** [comment]
With `set -e` you don't get to print an error message, this is better.

**Pull request merged**
