### PR TITLE
Minor fixes of relevance around evar-generating code

### PR DESCRIPTION
**Pull request by ppedrot**
A small step on the long road towards full-SProp compliance.

Overlays:
- https://github.com/damien-pous/relation-algebra/pull/37 (backwards compatible)

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
@coqbot bench

**Review by SkySkimmer — APPROVED** [review]

**Comment by ppedrot** [comment]
Backwards compatible overlay waiting at https://github.com/damien-pous/relation-algebra/pull/37 so I don't have to push an overlay commit here.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
