### PR TITLE
Redirect command: enable `Redirect "/dev/null"` etc by not adding suffixes

### PR DESCRIPTION
**Pull request by Blaisorblade**
Fix `Redirect "/dev/null"`, and generally increase flexibility — no need to force extensions on the user.

Fixes / closes #????

- [ ] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.
  
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make doc_gram_rsts`.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by ejgallego** [comment]
Redirect is already a pretty bad security hole, this makes it much worse

**Comment by Alizter** [comment]
I agree that it is a security hole, but how is it any different than say a text editor?

**Comment by Blaisorblade** [comment]
I'd buy gating `Redirect` under a `--trusted-source` option (but details are tricky since code comes with build scripts), or even restricting it to the `HideOutput` case (if we have nothing else like that already) and using cram tests instead for other cases.

**Comment by JasonGross** [comment]
Does `Test` hide output?  I'd be okay with allowing `--trusted-source` (maybe it should be `--redirect-whitelist`, and be able to be passed multiple times?), but please don't unconditionally enable overwriting, e.g., `/bin/true`

**Comment by JasonGross** [comment]
> I agree that it is a security hole, but how is it any different than say a text editor?

A text editor and a compiler are different tools.  Eventually I want a version of Coq that is hardened against even adversarial inputs.

**Comment by Alizter** [comment]
In this case, perhaps the better direction is to add infrastructure to Coq to silence output. If that is the intention with redirect. We probably want to move away from supporting redirect in the future.

**Comment by SkySkimmer** [comment]
Coq is more an interpreter than a compiler IMO

**Comment by Blaisorblade** [comment]
Correction: `--trusted-source` seems kinda pointless — since `make`/`dune` are too powerful, you rather want something like `opam` sandboxing.

* If you build an hostile software project, the attacker can do anything it wants with your user via either `make` and `dune` rules. Usually they can't overwrite `/bin`, but they can attack user-installed binaries, read your entire home folder, etc. `dune` supports sandboxes but they're opt-in and not presented as a security mechanism. I'm ignoring the special case where coq code is built by pure Coq rules, since this is rather fragile.
* Coqc options are provided with the project so they're also under attacker control.
* VsCode's lets _the user_ trust a folder when opening it, so VsCode Coq plugins can use that information — but for untrusted code they cannot invoke a build system.
* Things like JsCoq seems the main scenario where `make` and `dune` aren't involved; that should definitely disable `Redirect` altogether.

* I'm not sure what the use-case for `Redirect "file"` is — it's not necessary for cram testing, even with `coq_makefile`.

**Comment by andres-erbsen** [comment]
IMO it is a pity that Coq chose `Redirect` over a specialized solution (and that this choice was kept last the the security aspect here was reported,) but perhaps the best we can hope for at this point is to clearly and elaborately document that we disclaim any security, even from interactive input pasted into CoqIDE. I would also be fine with `Redirect` being redesigned now, but please let's not hold this change due to it adding more ways to abuse `Redirect` without going after the existing ones.

**Comment by JasonGross** [comment]
> * Coqc options are provided with the project so they're also under attacker control.

This is not always true.  Consider the threat model of, e.g., https://www.codewars.com/.  Users on the site provide the contents of the file, but the site itself provides the build options.  If you remove the extension from `Redirect`, you break every coding challenge on that site, since (I expect) users will be able to overwrite the test harness with `Redirect`.

**Comment by SkySkimmer** [comment]
It's only a security hole if you consider that coq shouldn't be allowed to write to files. But where does this assumption come from?

**Comment by Zimmi48** [comment]
I agree with the opinions in this thread that there should probably be a plan to retire `Redirect` rather than making it more powerful. As for the use case of this PR, what about adding a `quiet` attribute instead?

**Comment by ejgallego** [comment]
> It's only a security hole if you consider that coq shouldn't be allowed to write to files. But where does this assumption come from?

It is widely expected by users that running `coqc` should not overwrite your `~/.bashrc` for example.

As @Zimmi48 points out, verbosity controls do belong more at the `coqc / fcc` level than in vernacs (or maybe at worst an attribute). 

It is a valid use that commands may need to write to files, but in this case I think a saner model should be implemented and commands should register that capability with an upper layer, so the upper layer can apply proper isolation / build management of these files. The current model where vernacs can do IO has a lot of problems from the UI / DM / Build perspective.

**Comment by SkySkimmer** [comment]
Doesn't seem likely to be merged

**Pull request closed without merging**
