### PR TITLE
Preview of the debugger (added to 8.14)

### PR DESCRIPTION
**Pull request by jfehrle**
This PR will be used to put out the debugger preview.  It should not be merged or reviewed.

### CODE REVIEW

**Comment by jfehrle** [comment]
I need it to get and test the Windows installer.

**Comment by jfehrle** [comment]
@Zimmi48 The failure in the base build job is very curious.  Do you have any thoughts?  However, it may not affect using this branch for the preview.

**Comment by Zimmi48** [comment]
That has to do with the documentation of the stdlib. But it doesn't look related to your code changes, so that is really strange. You've never seen this before? I wouldn't worry if it doesn't show up in one of your other PRs.

**Comment by Zimmi48** [comment]
Is there still a point to this PR staying open?

**Comment by jfehrle** [comment]
I don't want to forget about it for a while longer.

**Pull request closed without merging**
