### PR TITLE
coq_makefile2 : improve backward compatibility w.r.t. inclusion of generated makefile

### PR DESCRIPTION
**Pull request by gares**
see https://github.com/coq/coq/pull/725

### CODE REVIEW

**Comment by maximedenes** [comment]
Test suite still fails on OSX.

**Comment by maximedenes** [comment]
@gares Can you have a look at this? Otherwise it is going to miss 8.7beta1.

**Comment by maximedenes** [comment]
@gares ping

**Comment by Zimmi48** [comment]
Re-targeting to 8.7.0 as this is most likely going to miss 8.7+beta.

**Comment by Zimmi48** [comment]
Should we just close this?

**Pull request closed without merging**
