### PR TITLE
coq_makefile shall quote misc. arguments

### PR DESCRIPTION
**Pull request by Columbus240**
**Kind:** feature / breaking change.

- [X] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).
- [ ] Overlay pull requests (if this breaks 3rd party developments in CI, see
https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md for details)

This patch changes the semantics of how coq_makefile treats strings after `-arg` in _CoqProject files. The current behaviour is difficult to simulate by other programs that read `_CoqProject`, like [ProofGeneral](https://github.com/ProofGeneral/PG/issues/589), this patch would make it easier.

Currently (before merging this PR), when `-arg "Some String" -arg "Other String"` is written in the `_CoqProject` file, coq_makefile writes `COQMF_OTHERFLAGS =
Some String Other String` in the configuration file. When make calls
coqc, it splits arguments on spaces, so coqc gets the argument list
`["Some", "String", "Other", "String"]`.

This patch makes coq_makefile print `COQMF_OTHERFLAGS = "Some String"
"Other String"` and coqc will get the argument list `["Some String",
"Other String"]`.

Detail:  if you currently write `-arg "'Some String'" -arg "'Other
String'"` in `_CoqProject`, then coq_makefile will write
`COQMF_OTHERFLAGS = 'Some String' 'Other String'`. Since these are
properly quoted strings in the eyes of make, coqc will get the argument
list `["Some String", "Other String"]`. This behaviour is difficult to simulate, since after reading all the arguments and removing the double quotation marks, we'd have to re-group by single quotation marks. To adapt this use-case to the new behaviour, simply remove the single quotes.

**Breaking change:** Currently you can write `-arg "-w default"` and (by
the above process) have coqc receive `["-w", "default"]`. To achieve the same effect after this PR, you have to write `-arg -w -arg default`. This is an inconvenience inherent to the approach of this patch.
I see three ways of resolving this:
* Not merging this PR.
* Merging this PR and thus ordering all people using `-arg "-w default"` to change their _CoqProject files to `-arg -w -arg default`.
* Adapting lib/coqProject_file.ml to treat `-w` arguments as it does `-R`, `-Q` etc. arguments. Then merging the resulting PR. Forcing everyone to change their files from `-arg "-w default"` to `-w default`.

I’m in favor of the third option, since I expect there aren’t many other arguments like `-w` that would need special treatment (though I’m not certain). And it would remove the long construction. My main use case for the patch is making a global `Set Default Goal Selector "!".` easier to deal with.

### CODE REVIEW

**Comment by Columbus240** [comment]
Ah, I got another idea. We could also make an exception for `-set`, instead of making an exception for `-w`. I.e. defining that `-set "Some Option=A"` should be passed on as `COQMF_OTHERFLAGS = -set "Some String"`, resulting in `["-set", "Some String"]`. This would still permit the current "weird" behaviour with `-w`, and would probably not need so many changes to _CoqProject files.

I’m not inclined to this solution, because the behaviour (and the existence) of `-arg` is (I believe) the major inconvenience of _CoqProject files.

**Comment by Columbus240** [comment]
Yet another possible solution to the whole mess of coq_makefile: Currently there are (at least) two parts of the code that handle arguments independently. In lib/coqProject_file.mli and in toplevel/coqargs.mli.
How about merging them in some giant general argument parsing mess? Maybe the [Arg](https://ocaml.org/api/Arg.html) module of the OCaml stdlib could be helpful?

**Comment by Columbus240** [comment]
I have to think about this.

**Comment by Columbus240** [comment]
I think this change in the semantics of `-arg` is necessary, if we want to improve how _CoqProject files are handled. Even with this change, make may do expanding of variables in `COQMF_OTHERFLAGS` if some dollar-signs appear.
(Try for example `-arg $(MAKE)` in a _CoqProject file)

**Comment by gares** [comment]
> Currently (before merging this PR), when `-arg "Some String" -arg "Other String"` is written in the `_CoqProject` file, coq_makefile writes `COQMF_OTHERFLAGS = Some String Other String` in the configuration file. When make calls
> coqc, it splits arguments on spaces, so coqc gets the argument list
> `["Some", "String", "Other", "String"]`.

I think this PR and the one about the doc are the occasion to *define* the quotation rules.
I guess the main problem is `-arg -set -arg 'This Option="this string value"'`. What goes wrong in this case?

**Comment by gares** [comment]
>  (Try for example `-arg $(MAKE)` in a _CoqProject file)

This is not expected to work. The whole point of splitting _CoqProject and Makefile.coq.local was to put make specific code in the latter, and have _CoqProject stay "build tool" independent.

**Comment by Columbus240** [comment]
> > (Try for example `-arg $(MAKE)` in a _CoqProject file)
> 
> This is not expected to work. The whole point of splitting _CoqProject and Makefile.coq.local was to put make specific code in the latter, and have _CoqProject stay "build tool" independent (e.g. PG should be able to parse _CoqProject, should not even try parsing the other one).

If make shouldn’t do any expansion etc. inside `COQMF_OTHERFLAGS`, then coq_makefile should do a lot more quoting & escaping in [`generate_conf_defs`](https://github.com/coq/coq/blob/cd489dc28f99855fa9abdc882ef194fcd0c48465/tools/coq_makefile.ml#L280-L284). I think lots of quoting & escaping when writing `COQMF_OTHERFLAGS` would be great.

> I guess the main problem is `-arg -set -arg 'This Option="this string value"'`. What goes wrong in this case?

The function [`parse`](https://github.com/coq/coq/blob/789ccb61cdee5c10c1d0fd0f2569b05f02e41a9a/lib/coqProject_file.ml#L91-L139) from coqProject_file.ml, will create the following list of strings: `["-arg", "-set", "-arg", "'This", "Option=""this", "string", "value""'"]`, (where `""` inside a string stands for the character `"`, OCaml-style). In the next phase [`process_cmd_line`](https://github.com/coq/coq/blob/789ccb61cdee5c10c1d0fd0f2569b05f02e41a9a/lib/coqProject_file.ml#L160) accepts the pairs `-arg -set` and `-arg 'This`, and tries to match on `Option="this`, noticing that it is neither an option nor a filename thus throwing an error.

Why is the list of strings so weird:
* single-quotes get treated like ordinary characters
* the double-quotes only begin a quote if they’re at the start of a "token". Both double quotes in your example are in the tail of a token, and are thus treated like ordinary characters.

**Pull request closed without merging**
