### PR TITLE
CI: Use bundled compcert for VST

### PR DESCRIPTION
**Pull request by SkySkimmer**
The compcert configure looks complicated, and this should get CI working again until someone looks deeply into it.

### CODE REVIEW

**Comment by Zimmi48** [comment]
This looks related to @MSoegtropIMC recent work on making VST compatible with a pre-installed CompCert.

**Comment by Zimmi48** [comment]
If we want to update the VST version that is pinned in `v8.12` to the latest release, then we might need to backport this fix as well.

**Comment by MSoegtropIMC** [comment]
I am about to release an opam package for VST, but there is a VST tag 2.6+beta which does work with a bundled compcert. Please note that the bundled CompCert must have the patches included in the 3.7~coq-platform version - otherwise VST will not build. Most important is the change to install a "compcert.config" file under user-contrib/compcert, which VST can use to find out what configuration compcert has.

Do you need this now or can you wait until early next week? I think VST 2.6 will be pretty final then (I just had some final discussions with Andrew today). One thing I wanted to do over the weekend is to move the install process of VST into the makefile, which would simplify the Windows build scripts.

**Comment by Zimmi48** [comment]
Early next week is fine for us. We don't expect to be able to tag 8.12.0 before Wednesday. As for master, is this PR OK?

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
This is replaced by #12745

**Comment by SkySkimmer** [comment]
>This is replaced by #12745

8.12 only

**Comment by ejgallego** [comment]
> 8.12 only

Yes indeed, I meant my message to explain the change of milestone.

**Pull request merged**
