### PR TITLE
Fixes #18223: nested entry coercions possibly printed in the wrong order depending on the order in which coercions were declared

### LINKED ISSUE #18223: Coq uses wrong notations using custom entries
#### Description of the problem
Coq displays a goal using a notation defined in another custom entry (see the end of the code below).

```coq
Declare Custom Entry foo.
Declare Custom Entry bar.

Section example.

Context (A : Type).
Context (Q : A -> A -> A).
Context (P : A -> A).


Notation "< x >" := (P x) (x custom foo).
(* Should not be allowed in a foo expression *)
Notation "| x |" := (x) (x custom bar).

Notation "{ x }" := (x) (in custom foo, x constr).

(* If moving the above notation |-| here, the issue disappears
*)


Notation "x y" := (Q x y)  (in custom bar at level 1, right associativity).
Notation "x" := x (in custom bar at level 0, x global).

Check (fun a b => < {Q b a} >).
(*  returns fun (a : A) (b : B) => < | {b a} | > 
The | - | notation should not be used! And indeed it is not accepted as input, as seen below.
*)
Fail Check (fun a b =>  < | {b a} | >).
End example.
```

#### Coq Version

8.18.0

### PR DESCRIPTION
**Pull request by herbelin**
Fixes / closes #18223

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coqbot merge now

**Comment by ejgallego** [comment]
Should this go into 8.18.1 ?

**Comment by proux01** [comment]
It's not immediate to backport so I'd say no.

**Pull request merged**
