### PR TITLE
kernel: bugfix in filter_stack_domain.

### PR DESCRIPTION
**Pull request by mattam82**
It did not consider that the argument might be higher-order, e.g. [nat -> I]. Morally the function arguments' size should not matter for the filtering criterion.

### CODE REVIEW

**Comment by maximedenes** [comment]
Can you provide a test case?

**Comment by cmangin** [comment]
Here is an example which currently does not work (`Recursive call to bar has principal argument equal to "g' 0" instead of "g".`), and works with @mattam82 's patch:
```coq
Inductive foo : Type -> Type :=
| End A : foo A
| Next A : (A -> foo A) -> foo A.

Definition nat : Type := nat.

Fixpoint bar (A : Type) (e : nat = A) (f : foo A) {struct f} : nat :=
match f with
| End _ => fun _ => O
| Next A g => fun e =>
    match e in (_ = B) return (B -> foo A) -> nat with
    | eq_refl => fun (g' : nat -> foo A) => bar A e (g' O)
    end g
end e.
```

**Comment by ejgallego** [comment]
Who could help reviewing this?

**Comment by maximedenes** [comment]
I'm reviewing it. It looks correct at first, because we have already a very similar rule modulo commutation. I just need to make sure thos commutations are always well typed, but my guess is they should be, with the current restrictions.

**Comment by mattam82** [comment]
Hmm, is that too late for 8.7 then?

**Comment by maximedenes** [comment]
The meat of this change is the commutation between:

```coq
match e : X = Y in _ = Y return (U Y -> I Y) -> T Y with
   eq_refl => fun g' : U X -> I X => F (g' x)
end g
```
and
```coq
F (match e' : Y = X in _ = X return U X -> I X with eq_refl => g end x).
```

`F` in this commutation should be studied separately, as it plays the same role as in the current guard condition. So what remains added by this patch is the application of `g'` or the `match` expression to `x`, which seems ok, even when `g` has a dependent type.

So to me this patch looks ok. I would still not bet my life on the correctness of the guard condition, but it doesn't seem to make things worse.

**Comment by maximedenes** [comment]
So @mattam82, can you update the PR to include the test case? I'll merge it.

**Review by maximedenes — APPROVED** [review]

**Comment by Zimmi48** [comment]
@maximedenes Is your approval valid for v8.7 as well?

**Comment by mattam82** [comment]
Added the script

**Comment by maximedenes** [comment]
@Zimmi48 Well, it is not risky in terms of compatibility and stability. So I'd say why not. This is not a big kernel change, more like an oversight in the existing condition (in my code, more precisely) which is already justified in parts by hand-waving :)

**Comment by maximedenes** [comment]
Of course, if @barras can double check, it would be even better :)

**Pull request merged**
