### PR TITLE
Postponing of universe constraints unification in term equality.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of calling the universe unification at each term node, we accumulate them and try to perform unification at the very end. This seems to be experimentally faster.

This shouldn't change the semantics, assuming that unification is associative and commutative.

Timing with one iteration:

```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┐
│                        │      user time [s]      │             CPU cycles              │          CPU instructions           │
│                        │                         │                                     │                                     │
│           package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │           NEW           OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│                coq-vst │ 1331.20 1410.58 -5.63 % │ 3696858945813 3916153449517 -5.60 % │ 5417304683847 5719991507682 -5.29 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│               coq-iris │  359.76  378.66 -4.99 % │  996911174164 1049387911500 -5.00 % │ 1303555089515 1380386963619 -5.57 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│     coq-bedrock-facade │  933.83  964.79 -3.21 % │ 2591477764220 2669910161178 -2.94 % │ 3296359030115 3432136935072 -3.96 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│        coq-bedrock-src │  909.72  937.19 -2.93 % │ 2523258195214 2595319282428 -2.78 % │ 3219951187273 3349561603264 -3.87 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│              coq-color │  583.64  599.32 -2.62 % │ 1616112941890 1658205978198 -2.54 % │ 2025644979039 2082908108122 -2.75 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│       coq-fiat-parsers │  514.81  525.72 -2.08 % │ 1405692042924 1437670927738 -2.22 % │ 2019968673555 2067914099122 -2.32 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│    coq-formal-topology │   37.44   37.78 -0.90 % │  100499496143  101445131020 -0.93 % │  137376221925  139054878208 -1.21 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│ coq-mathcomp-odd_order │ 1388.28 1391.84 -0.26 % │ 3866342876865 3873227410986 -0.18 % │ 6837909854704 6825390686015 +0.18 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│         coq-coquelicot │   71.69   71.79 -0.14 % │  196479041224  195746710701 +0.37 % │  247865655983  248047902751 -0.07 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│               coq-hott │  234.95  235.23 -0.12 % │  632223028311  634096768573 -0.30 % │ 1078467156902 1078232321764 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│              coq-flocq │   55.26   55.24 +0.04 % │  151594277680  151303273148 +0.19 % │  196079687496  196189896634 -0.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│                 coq-sf │   44.38   44.19 +0.43 % │  121403500082  120660771617 +0.62 % │  158667832814  158349797855 +0.20 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│   coq-mathcomp-algebra │  169.10  168.27 +0.49 % │  469633942585  466363964994 +0.70 % │  672133061622  671469639527 +0.10 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│        coq-fiat-crypto │ 2045.30 2034.32 +0.54 % │ 5651816898503 5622462788698 +0.52 % │ 9443113349974 9412586688188 +0.32 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│  coq-mathcomp-fingroup │   57.98   57.65 +0.57 % │  159810915179  159098264469 +0.45 % │  225952848759  225937554699 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│     coq-mathcomp-field │  454.73  452.06 +0.59 % │ 1265488976614 1258374516696 +0.57 % │ 2110828037001 2112935533837 -0.10 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   43.02   42.74 +0.66 % │  117131783908  116493560487 +0.55 % │  150848451858  150999371562 -0.10 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│            coq-unimath │ 1283.04 1272.61 +0.82 % │ 3557321830706 3528545420069 +0.82 % │ 6028998852821 6025865621681 +0.05 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│           coq-compcert │  814.05  806.45 +0.94 % │ 2256688084101 2239032986361 +0.79 % │ 3428078265056 3405603373251 +0.66 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│ coq-mathcomp-character │  269.83  267.12 +1.01 % │  750285368770  742756855901 +1.01 % │ 1108567612870 1105661591906 +0.26 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┤
│  coq-mathcomp-solvable │  191.85  189.70 +1.13 % │  531573178228  526244969201 +1.01 % │  777121740611  775476804396 +0.21 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┘
```

### CODE REVIEW

**Comment by jhjourdan** [comment]
Are you sure it does not change the semantics with respect to, e.g., backtracking in unification?

**Comment by ppedrot** [comment]
@jhjourdan It should not, because the equality function is merging the constraints before doing anything else. The function the patch changes is mere syntactic equality, not conversion.

**Comment by jhjourdan** [comment]
Oh, I see. Any idea why this is faster?

Moreover, it seems like there is an opportunity of doing the universe checking for all the constraints at the same time instead of doing it one constraint after the other. If the good algorithm were used, that could mean a nice speedup.

**Comment by ppedrot** [comment]
It is used a lot by old unification, and I believe that most of the time the terms being equated are similar but distinct, so that it should fail earlier without having to compute the universe unification. Obviously you could find the dual case (where universe unification should fail early), but this doesn't seem to happen in practice.

**Comment by maximedenes** [comment]
@mattam82 how does this look to you?

**Review by mattam82 — APPROVED** [review]
Looks fine to me, the experimental results seem to be in favor of postponing indeed

**Comment by herbelin** [comment]
Can we remove the needs_review flag then so that it appears in the [overview](https://github.com/coq/coq/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aopen%20-label%3Afix_needed%20-label%3Ain_progress%20-label%3Aneeds_testing%20-label%3Aneeds_review%20-label%3Aneeds_discussion%20-label%3Arebase_needed) for 8.7 integration?

**Comment by maximedenes** [comment]
> Can we remove the needs_review flag then so that it appears in the overview for 8.7 integration?

Done. Feel free to do it when you think it better reflects the current state of the PR.

**Pull request merged**
