### PR TITLE
Don't catch anomalies for evarconv "cannot find an instance" error

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, will wait for @coq/pretyper-maintainers to comment / assign, but I'm proposing this for 8.12 as it may be helpful in getting better error traces from users.

**Comment by ejgallego** [comment]
@SkySkimmer how about:
```
@@ -1334,6 +1334,13 @@ let thin_evars env sigma sign c =
   let c' = applyrec (env,0) c in
   (!sigma, c')
 
+exception InstanceSearchFailed of exn
+
+let _ = CErrors.register_handler (function
+    | InstanceSearchFailed exn ->
+      Some Pp.(str "Instance Search failed: " ++ CErrors.print exn)
+    | _ -> None)
+
 let second_order_matching flags env_rhs evd (evk,args) (test,argoccs) rhs =
   try
   let evi = Evd.find_undefined evd evk in
@@ -1478,7 +1485,9 @@ let second_order_matching flags env_rhs evd (evk,args) (test,argoccs) rhs =
                           List.exists (fun c -> isVarId evd id (EConstr.of_constr c)) l ->
                  instantiate_evar evar_unify flags env_rhs evd ev vid
                | _ -> evd)
-           with e -> user_err (Pp.str "Cannot find an instance")
+           with e when CErrors.noncritical e ->
+             let exn, info = Exninfo.capture e in
+             Exninfo.iraise (InstanceSearchFailed e, info)
```

**Comment by SkySkimmer** [comment]
I don't really know what this code does, won't we end up printing `instance search failed: Not_found`? Also it's not a "search" AFAICT

**Comment by ejgallego** [comment]
That's what I get:
```
Error: Instance Search failed: Ill-typed evar instance
```

I dunno, I found this already useful.

[indeed Search is not the proper name]

**Comment by ejgallego** [comment]
The error occurs here btw:
```
Inductive interleaved
  : itree (A +' C) R -> itree (B +' C) R -> Prop :=
| interleaved_Ret r : interleaved (Ret r) (Ret r)
| interleaved_Left {U} (t : itree _ U) k1 k2 :
    (forall (x : U), interleaved (k1 x) (k2 x)) ->
    interleaved (interp (case_ g inr_) t >>= k1) (t >>= k2)
| interleaved_Right {U} (t : itree _ U) k1 k2 :
    (forall (x : U), interleaved (k1 x) (k2 x)) ->
    interleaved (t >>= k1) (interp (case_ f inr_) t >>= k2)
.
```

**Comment by herbelin** [comment]
Hi, did you have an example for the "interleaved" error you are talking about? The PR improved on the previous situation but I observed that it may embed in `NotFoundInstance` the internal exceptions `IllTypedInstance` (and `TypingFailed`) for which there is no handler. So, something needs to be done more but it is unclear what without a proper example. (This part of code is rather fragile, I agree.)

**Comment by herbelin** [comment]
Hi, do you have plans regarding a continuation of this PR? Otherwise, I may offer a [branch](https://github.com/coq/coq/compare/master...herbelin:master+minifix-NotFoundInstance) which should improve on this PR and fixes #13266 as well (but not #5512 :( ).

**Comment by SkySkimmer** [comment]
No plans here

**Pull request merged**
