### PR TITLE
Make gappa allow_failure

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
@SkySkimmer Do you want this merged before or after #15191 (i.e., target 8.15 or 8.16)?

**Comment by SkySkimmer** [comment]
Before

**Comment by ppedrot** [comment]
Isn't this a bit extreme? We're essentially pending on @silene 's merge of the upstream overlay that might occur anytime soon...

**Comment by Zimmi48** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
> Isn't this a bit extreme? We're essentially pending on @silene 's merge of the upstream overlay that might occur anytime soon...

Sorry, it was not my intention to ignore this comment, I only noticed it after I clicked the "Comment" button.

**Comment by Zimmi48** [comment]
I don't think it is extreme because it is easy to revert. In the meantime, this failure has been polluting everyone's CI for the past week.

**Pull request merged**
