### PR TITLE
Improve warning for nonuniform coercions

### PR DESCRIPTION
**Pull request by proux01**
So as to better advertize the attribute introduced in https://github.com/coq/coq/pull/15853

- [x] Added / updated **test-suite**.

- [ ] ~Added **changelog**.~
- [x] Added / updated **documentation**.
  
  - [x] Documented any new / changed **user messages**.
  - [ ] ~Updated **documented syntax** by running `make doc_gram_rsts`.~

- [ ] ~Opened **overlay** pull requests.~

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by Alizter** [comment]
Actually what's the point of the `#[nonuniform]` attribute now that we can silence specific warnings using attributes?

**Comment by proux01** [comment]
Good point! So let me open another PR deprecating the `nonuniform` attribute and advertizing the use of the `warning` attribute introduced in 8.18 by https://github.com/coq/coq/pull/16902 and let's close the current PR.

**Comment by jfehrle** [comment]
FWIW the correct spelling is "advertising".

**Comment by proux01** [comment]
> FWIW the correct spellings are "advertise" and "advertising".

Thanks, I guess I tried to look overly american ;)

**Pull request closed without merging**
