### PR TITLE
Tweak CList.firstn: return original list when fully used

### PR DESCRIPTION
**Pull request by SkySkimmer**
I don't think this changes perf but you never know

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by Alizter** [comment]
Looks like it is shaving something off four color there.

**Comment by Alizter** [comment]
Hmm lets see another one.

@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
