### PR TITLE
Doc: rename `coqtop::` -> `rocqtop::`, `coqdoc::` -> `rocqdoc::`

### PR DESCRIPTION
**Pull request by SkySkimmer**
The implementation is unchanged, ie it's still called coqdomain, calls coqtop, produces CSS classes named coqdoc-keyword etc

### CODE REVIEW

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
CI failure is unrelated, let's merge

**Comment by proux01** [comment]
@coqbot merge now

**Comment by proux01** [comment]
@coqbot merge now

**Comment by jfehrle** [comment]
"rocqdoc" sounds like a PhD geologist
"rocqtop" could be a granite kitchen counter :-)

**Pull request merged**
