### PR TITLE
Bump version number to 8.11.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Iris keeps failing for reasons seemingly related to notations (maybe #10773 in disguise?). What am I supposed to do? Summoning @jhjourdan and @RalfJung anyways.

**Review by JasonGross — APPROVED** [review]

**Comment by RalfJung** [comment]
> Iris keeps failing for reasons seemingly related to notations

Iris tests the output of Coq and has some version-specific hacks for when Coq changed over time. I'll need to adjust those to support version 8.11.

**Comment by RalfJung** [comment]
I think I fixed this in Iris bumped it in LambdaRust, so this should work now.

**Comment by ppedrot** [comment]
@RalfJung Looks good, thanks. Who's assigning this PR? @Zimmi48 maybe?

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
I don't think we need to wait for an ack of other code owners, but just in case, I'll only merge this tomorrow.

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
