### PR TITLE
remove OCAMLRUNPARAM warning in debugging.txt

### PR DESCRIPTION
**Pull request by psteckler**
This PR anticipates such time as Coq is built with OCaml 4.06 or greater. The hanging issue with ocamldebug should be fixed in those versions of OCaml.

I'm submitting this PR now, because I will likely forget to do it later.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Has the fix been committed on the OCaml side? Don't you rather want to update your warning to mention that the easiest fix is to use OCaml 4.06 or greater?

**Comment by psteckler** [comment]
Yes, the fix has been merged in OCaml: https://github.com/ocaml/ocaml/pull/1361

4.06 hasn't yet been released, and AFAIK, we haven't tested building Coq with it.

**Comment by psteckler** [comment]
BTW, note that we have no explanation why unsetting `OCAMLRUNPARAM` masks the bug.

**Comment by psteckler** [comment]
@Zimmi48 Assuming that #6045 will be merged, I should change the message the message to say "use 4.06 if you can, otherwise use the workaround".

**Comment by Zimmi48** [comment]
Yes I agree.

**Comment by psteckler** [comment]
Well, that didn't work right.

**Pull request closed without merging**
