### PR TITLE
Move tests in bugs/ to bugs/closed/.

### PR DESCRIPTION
**Pull request by nlewycky**
**Kind:** infrastructure.

- [*] Added / updated test-suite

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
#5996 is still open (cc @ppedrot @JasonGross)

**Comment by ppedrot** [comment]
I think that #5996 is a WONTFIX. @JasonGross ?

**Comment by JasonGross** [comment]
I would be willing to have #5966 closed as WONTFIX if the relevant behavior of `constr` / `type of` is documented in more detail in the reference manual.  However, I maintain that allowing ill-typed `constr` is a bad design decision, and that even if this is not fixed in Ltac1, things which can generate ill-typed `constr`s should be relegated to `Unsafe` modules (such as `Constr.Unsafe.make`).  I am fine with any of:
1. Closing #5966, opening a new bug about the doc and a separate bug about the design decision, and having the code checking the current behavior being moved to `bugs/closed`
2. Leaving #5966 open, and having the code checking the current behavior be in `bugs/opened`
2. Leaving #5966 open, but have it be a bug about the design decision and documentation, and moving the code checking the behavior to `test-suite/success` to be a check about `constr` / `type of` / Ltac semantics.

**Comment by nlewycky** [comment]
I see no reason not to move forward with the rest of the files while we decide what to do about #5966.

As a git matter, I tried to a) undo the change to 5966.v and amend the commit b) rebase against master c) push that. I don't understand why coqbot thinks I need to rebase or why it added all the reviewers. I'd appreciate it if someone could walk me through what I ought to do now.

**Review by Zimmi48 — APPROVED** [review]

**Pull request merged**
