### PR TITLE
[sphinx] More fatal warnings.

### PR DESCRIPTION
**Pull request by Zimmi48**
This first commit was proposed by @cpitclaudel in #7365.
In order to merge this, we need to fix these new warnings.
But before getting started on this task, let's wait on #7301 being merged.

### CODE REVIEW

**Comment by Zimmi48** [comment]
This is now on top of #7301 and includes #7365 and fixes all new warnings.

**Comment by Zimmi48** [comment]
Merging this and other Sphinx PRs at the same time without testing their interaction is dangerous, since this adds new fatal warnings. The best course of action would be to do a batch merge and running CI before pushing upstream. Another solution is to merge this and to request other Sphinx PRs to rebase before merging them.

**Comment by maximedenes** [comment]
Will merge right after #7365.

**Comment by Zimmi48** [comment]
Unfortunately, this was merged without being tested on a recent version of the manual. And since it introduced new fatal warnings, it broke the compilation, as could be expected. Fortunately, #7487 already fixes this.

**Pull request merged**
