### PR TITLE
[bench] set OPAMCLI to 2.0 to silence warnings

### PR DESCRIPTION
**Pull request by Alizter**
This should address the warnings observed in https://github.com/coq/coq/pull/16223

### CODE REVIEW

**Comment by Alizter** [comment]
There is perhaps a more correct fix by using the new syntax, however I couldn't work out how to do this. This seemed like the easier path.

**Comment by Alizter** [comment]
@coqbot bench

**Comment by ejgallego** [comment]
I think you just replace `opam config set` by `opam set`, etc...

**Comment by SkySkimmer** [comment]
Still noisy with `Added '[jobs "12" "Set through 'opam var'"]' to field global-variables in global configuration` so I pushed a commit to redirect to /dev/null. Also used the `opam var` command while I'm at it.

**Comment by SkySkimmer** [comment]
test run https://gitlab.com/coq/coq/-/jobs/3118178438

**Comment by SkySkimmer** [comment]
@ppedrot can you take this?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
