### PR TITLE
Enable fragile pattern warning in cclosure

### PR DESCRIPTION
**Pull request by SkySkimmer**
This file is already mostly in the required style so I wanted to see
what it looks like.

For a couple matches I locally disabled the warning as it was too
annoying otherwise (`when` clauses are especially annoying).

There are a couple places where I think it clearly looks better (eg
assoc_defined at the beginning of the file) but overall I'm not all
that convinced.
What do other people think?

### CODE REVIEW

**Comment by ejgallego** [comment]
For this particular file and component I like the patch.

**Review by ppedrot — APPROVED** [review]
I am not a fan of locally disabling the flag, but I like the idea anyways.

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
I don't think this requires a big discussion, it is kernel-only and makes maintainers happy. @SkySkimmer can I merge?

**Comment by SkySkimmer** [comment]
yes

Gaëtan Gilbert

**Comment by ppedrot** [comment]
@maximedenes ping.

**Comment by maximedenes** [comment]
Failure is spurious, merging.

**Pull request merged**
