### PR TITLE
Fix problems with `destruct using`

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
This consists of two parts:

### Remove broken code-path in product param atomization of `destruct`

`Tactics.atomize_param_of_ind_then` thinks that it has the ability to atomize
parameters inside of products. This code-path is at least partially broken.
I also believe that there is no way to exercise this code-path in a
non-trivial way that does not generate anomalies. (In other words: I think it is
dead code.) Hence we remove it.

Testcase:
```
Inductive test : unit -> Prop :=.
Definition test2 := forall x, test x.
Lemma t (H : test2) : True.
edestruct H using test_rect.
Abort.
(* Used to error with:
Unbound reference: In environment
H, t : test2
The reference 1 is free.

Now errors with:
Not an inductive definition.
*)
```

### Equalize behavior between `destruct` and `destruct using`

Let `X` be an inductive. Then one would expect `destruct H` and `destruct H
using X_rect` to behave identically (`H` being an appropriate term).

Currently this is not the case however:
```
Inductive test : unit -> Prop :=.
Definition test2 := forall x, test x.
Lemma t (H : test2) : True.
Fail edestruct H using test_rect.
edestruct H.
Abort.
```

The issue is that `edestruct using` fails to normalize the type of `H` enough.
We fix this by using `Tacred.reduce_to_quantified_ref` to reduce `H` (and a a `allow_failure` mode to this function).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Looks like this was pushed before the ulimit fix, please rebase

**Comment by Zimmi48** [comment]
This new command should avoid having to ask for a rebase, since it runs the CI with a fresh merge commit with master:

@coqbot run CI now

**Comment by LasseBlaauwbroek** [comment]
Mhm, Corn is clearly challenging my assumptions here. I'll take a look.

**Comment by LasseBlaauwbroek** [comment]
I believe that I've isolated an fixed the problem with Corn. Can I push that fix and get another run of CI or are the CI minutes to scarce at the moment?

**Comment by LasseBlaauwbroek** [comment]
Oops, I pushed accidentally anyway. But it seems the CI is only building the smaller subset (I'm not entirely up to date on what the current policy is).
Whenever some CI minutes are available, can somebody run the full suite? (Also, can I request such a run myself from coqbot or does somebody from the core team need to do that?)

**Comment by Zimmi48** [comment]
@LasseBlaauwbroek Do not worry about CI minutes. We have disabled shared GitLab runners and are using some Inria VMs instead. We only have 8 of them so the only thing we risk is getting a long queue of jobs. This is why we run a light pipeline by default now.

To get a full pipeline, put the `needs: full CI` label then push or write @coqbot run CI now (like I'm doing now).

I've invited to join the `@coq/contributors` team so that you have the permissions to set labels and to run coqbot commands.

**Comment by LasseBlaauwbroek** [comment]
Thanks!

**Comment by Zimmi48** [comment]
Something strange has happened with the GitLab pipeline. `SKIP_DOCKER=false` was set, which normally happens only when the Dockerfile has changed. I'll try to figure this out and restart the pipeline.

**Comment by Zimmi48** [comment]
OK should be fixed now. That's a bug that must have been there for a long time, but I only discover it now that our new runners cannot handle the Docker job.

@coqbot run CI now

**Comment by LasseBlaauwbroek** [comment]
@coqbot run CI now

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Do you want to add a changelog entry?

**Comment by LasseBlaauwbroek** [comment]
Changelog added.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
