### PR TITLE
Display timing data for fiat-*, bedrock, and HoTT on travis

### PR DESCRIPTION
**Pull request by JasonGross**
aThis is not as good as having the bench display per-file timing data, but at least it'll give us some sort of per-file timing log for these projects, at almost no cost.

### CODE REVIEW

**Comment by JasonGross** [comment]
( cc @ejgallego ; request 8.7 milestone )

**Comment by ejgallego** [comment]
I am not so inclined to favor this as Travis is basically useless for timing data. Does this change imply that the developments are built twice?

**Comment by ejgallego** [comment]
I also wonder about the chain-effect that this developments have as the scripts are in a submodule, for a start, is the submodule properly checked-out ?

**Comment by JasonGross** [comment]
> as Travis is basically useless for timing data

What makes you say this?  It certainly doesn't have great precision, but if a project slows down by 10%, it should be noticeable on travis.  And it'll list the files in the order of how much time they take to build, which can speed up debugging performance issues.

> Does this change imply that the developments are built twice?

It adds `-k` to the first build (which will slow things down in failing cases, because all of the succeeding files will still be built), and when the development fails to fully build, at most `NJOBS` files will be built twice.  I can fix this, if it's important.  The overhead on succeeding jobs is roughly the amount of time it takes to invoke `make` when no targets need to be updated (so, slow if we were building chrome, but a non-issue for basically all Coq projects).

> is the submodule properly checked-out by our scripts?

The script checks out a fresh clone each time, right?  If the submodule isn't checked out, travis will fail to build this PR, and I'll go fix the scripts.

**Comment by ejgallego** [comment]
> What makes you say this?

Builds routinely slow down in Travis by more than 10%. CPU time is not guaranteed and 20-40% variation in build time is common. It is just the wrong tool for the job.

**Comment by ejgallego** [comment]
> for a start, is the submodule properly checked-out by our scripts?

It was not, thou this is broken.

**Comment by JasonGross** [comment]
Superseded by #746

**Pull request closed without merging**
