### PR TITLE
Hack a bench checking for page effect.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
https://gitlab.com/coq/coq/-/jobs/975327352

**Comment by silene** [comment]
I am confused as what you are trying to test. Given that `always` seems to give a 4% speedup, do you think we should be running `coqtop` with `OCAMLRUNPARAM=H`?

**Comment by ppedrot** [comment]
This is actually a set of experiments for @gadmm, I was only launching them for him. The goal is to understand better the OCaml allocator settings, as Coq is a good stress test for memory use.

**Comment by gadmm** [comment]
> Given that `always` seems to give a 4% speedup, do you think we should be running `coqtop` with `OCAMLRUNPARAM=H`?

To try to get THP benefits you can install jemalloc and run your program with `MALLOC_CONF="thp:always,metadata_thp:auto" LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 <command>`. This is in fact the next bench I have asked from @ppedrot :)

The idea is indeed to see how to best benefit from huge pages in OCaml by default. I am also trying to get `OCAMLRUNPARAM=H` to work without success for now, so I am operating in the blind. For instance I'd like to get an idea of benefits brought by 1G pages with such large working sets, but I cannot manage to allocate any on my computer. @ppedrot, can you try and report if as root `echo 100 > /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_overcommit_hugepages` indeed changes the value of `nr_overcommit_hugepages` on the benchmark machine?

**Comment by gadmm** [comment]
Pour référence le deuxième test (always vs. madvise) est là: https://gitlab.com/coq/coq/-/jobs/980321229

**Comment by SkySkimmer** [comment]
Is this PR still useful open?

**Comment by gadmm** [comment]
I let you see if you still want to explore these possible perf improvements. The next step is to test with jemalloc with the command line shown above, which I expect to give even faster results. It could motivate working on huges pages in OCaml in the future, and let people know how faster they could have Coq run with the jemalloc command line.

**Comment by ppedrot** [comment]
I don't have a lot of time right now, so I'll close this PR for the time being. We can reopen a new one whenever we need.

**Pull request closed without merging**
