### PR TITLE
Generalize well-founded Fix extensionality proofs to arbitrary relations

### PR DESCRIPTION
**Pull request by JasonGross**
This is a straightforward generalization from `eq` to arbitrary relations.  I've also added an extensionality proof based on `Fix_eq`.  This is useful rewriting with well-founded fixpoints and setoid relations.

Question (@mattam82?): Is there a good place to insert a `Proper` instance for `Fix` with arbitrary transitive relations?  (And what would the type be?  Presumably `F_ext` and `G_ext` would become `Proper` hypotheses...)

### CODE REVIEW

**Comment by JasonGross** [comment]
Oops, sorry, I made this to the trunk branch.  Should I close and remake one to the 8.5 branch, or leave it as-is?

**Comment by gmalecha** [comment]
A similar proof exists in the ExtLib library: https://github.com/coq-ext-lib/coq-ext-lib/blob/master/theories/Recur/GenRec.v

**Comment by JasonGross** [comment]
@gmalecha: Is that a suggestion to use that proof instead, or an argument that this would be useful to have in the stdlib, or an argument that Wf should be ripped out of the stdlib all-together, or something else?

**Comment by gmalecha** [comment]
The later (I believe that this belongs in the standard library). It is a
very useful proof.

That said, there are many useful proofs. What is the criteria for belonging
in the standard library? It might be useful, at some point, to revisit
pieces of the standard library and make separate packages out of them? In
part because updating the standard library requires a new release of Coq
which means that if you had decided that this theorem was a good candidate
for the standard library in a few months (after 8.5 is official) then it
would only be useful to people running on top of trunk (or when pl1 comes
out).

On Wed, Feb 18, 2015 at 1:05 PM, Jason Gross <notifications@github.com>
wrote:

> @gmalecha <https://github.com/gmalecha>: Is that a suggestion to use that
> proof instead, or an argument that this would be useful to have in the
> stdlib, or an argument that Wf should be ripped out of the stdlib
> all-together, or something else?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coq/coq/pull/53#issuecomment-74947617>.
>



-- 
gregory malecha

**Comment by aspiwack** [comment]
I can't comment on the particulars. However, I will urge you *not* to make it a commit for v8.5. I believe it is a bad idea to add stuff at this point in the release cycle (which is already long enough as it is).

**Comment by herbelin** [comment]
OK to me, with the "TODO" to be removed (would suggest not using typeclasses in Wf.v).

**Comment by mattam82** [comment]
I'm ok with putting it in trunk now, can you remove the TODO?

**Comment by JasonGross** [comment]
> I'm ok with putting it in trunk now,

Thanks!

> can you remove the TODO?
Done.

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Pull request merged**
