### PR TITLE
[travis] Add VST

### PR DESCRIPTION
**Pull request by ejgallego**
Need to see how much we can build, making a guess now, but for sure `msl` can be built. This will also require adjustments due to #415 , but it should be fairly straightforward.

### CODE REVIEW

**Comment by ejgallego** [comment]
(cc: @herbelin @maximedenes @mattam82 @ppedrot etc... )

Hey folks,

so after a couple more experiments we are close to testing an almost full VST build, however
it seems that a6f687852c0c7509a06fdf16c0af29129b3566d5 (to be included in 8.6.1) breaks the build.

This is a bit inconvenient as it will happen in a minor release, however the breakage seems fairly minor and easy to fix. How should we proceed here? Should we assume the effects of a6f687852c0c7509a06fdf16c0af29129b3566d5 are intended and try to find a solution for VST that works on both 8.6 / 8.6.1 ?

Cheers.

**Comment by herbelin** [comment]
Is the fix improving the script or damaging it? For instance, is it about an unification problem which failed and the fix simply makes the script now working as expected? Or is it rather a situation where, I don't know, a6f6878 would make unification enter in one of these situations where it is not commutative and then not working any more?

**Comment by ejgallego** [comment]
> Is the fix improving the script or damaging it?

I didn't have time to develop a fix or to look at the script, this is just the result of my bisect scripts.

**Comment by gares** [comment]
My take is that the fix is reasonable. What is not reasonable is to break a development when upgrading from 8.6.0 to 8.6.1.  Especially in this case, the machinery of delayed constraints is not documented, almost invisible for the user, not controllable by the user.

Maybe we should try to refine the definition of a fix that goes into a minor release.  I propose: 

> a fix (w.r.t. the specification or the intended behavior of some code or a bug reported)  that is *known to break* developments does not qualify as a fix for a minor release, unless it fixes a proof of False.

**Comment by ejgallego** [comment]
Ok so I've pushed a couple of commits that should allow the standard VST distro to build. Let's see how timing works out, based on my laptop we should be close to fit within Travis limits.

**Comment by ejgallego** [comment]
Ok so the full build took 43 minutes, yay! This should be ready to go once you folks decide what to do with a6f6878 , let me know and I'll rebase it.

**Comment by herbelin** [comment]
@ejgallego: do you have a link to the commits you pushed to VST?

**Comment by Zimmi48** [comment]
Actually Emilio reverted the faulty commit in Coq instead. The tested version of VST is the official one.

**Comment by Zimmi48** [comment]
(Reverted in this branch I mean)

**Comment by ejgallego** [comment]
Indeed, thanks @Zimmi48

**Comment by herbelin** [comment]
@ejgallego: So, maybe do you have a link to the line where VST fails, possibly with some context, so that I can evaluate whether the fix is good or not.

**Comment by ejgallego** [comment]
@herbelin I guess you can just pull this tree and do `make ci-vst`

**Comment by herbelin** [comment]
For the record, the difference is the following. In the statement of the lemma, there is some `p` with an implicit type. The `p` is used in a context where unification gives it type `list (positive * type)` and in another context where it gives it the type `list (ident * type)`, where `ident` is an alias for `positive`. The order of resolution changes and the type inferred for `p` is the second type in 8.6 and the first one after a6f6878.

50 lines later in the proof, at the time of a `destruct`, a name is invented. This name is based on the type of `p`. In one case it is `i`, in the other case it is `p` again. This fails at the time of referring to `i` since `i` is now `p`.

**Comment by maximedenes** [comment]
@herbelin Thanks for investigating this.

The real problem is to rely on generated names, and not the fix of course. But since a lot of code does that, I think it would be more reasonable to merge the fix to trunk and revert it from 8.6.

They key motivation is that we want early adoption of minor releases. And we can get that only if users can upgrade without any script change (as long as they don't rely on a behavior that is a clear violation of user documentation).

**Comment by ejgallego** [comment]
Thanks for the investigation @herbelin , so it seems that we will have to patch VST anyways, right?

**Comment by herbelin** [comment]
Any solution for 8.6 is ok to me. After all, the less we fix bugs, the less we have to prepare patch level releases :)

About automatic generation of names, I already mentioned it, but a tool which automatically translate scripts by adding the needed missing names in most of the cases is far from unattainable. That may be a good direction to prevent both developers and users from bumping again and again and again on the fragility of name inference and give some space to continue to evolve.

@ejgallego: the patch is, at line 1070 of `veric/expr_lemmas.v`, change `destruct a0` into `destruct a0 as (i,t0)`.

**Comment by ejgallego** [comment]
https://github.com/PrincetonUniversity/VST/pull/67

**Comment by ejgallego** [comment]
Ok this should be ready to merge now.

**Pull request merged**
