### PR TITLE
Add myself as the primary maintainer of the warnings system

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by maximedenes** [comment]
@ejgallego is that ok with you?

**Review by ejgallego — APPROVED** [review]

**Comment by Zimmi48** [comment]
@ejgallego I don't think that Maxime was asking you to merge the PR (I am the second code owner of the CODEOWNER file). But never mind, you have my *a posteriori* blessing.

**Comment by ejgallego** [comment]
Umm, what got me here is that I didn't see the shield on the review request, so then I acted as the maintainer of `lib` [which IMHO is the one that should do the call]

**Comment by ejgallego** [comment]
Oh, so maybe shields are gone because the merge option was deactivated?

**Comment by ejgallego** [comment]
Oh never mind, of course the shield is not shown as we are talking about the secondary maintainer here... Mornings....

**Pull request merged**
