### PR TITLE
Allow Ltac2 as a plugin

### PR DESCRIPTION
**Pull request by ppedrot**
These patches provide Coq with the minimal amount of API to allow Ltac2 to land as a plugin. Note that by themselves, they are pretty much unrelated to Ltac2. The four patches provide the following features:

- An access to the Nametab API which was not exported before (we should probably also extract the Ltac-relevant API from it and move it to the Ltac implementation now).
- A way to extend internalization environments with user-defined data. Likewise, Ltac stuff should go there at some point but that is more complicated due to the interactions between the internalization procedure and Ltac. Left for when we have OO-style API...
- A generalization of `refine` that takes a tactic as an argument. Technically that should replace the current API which uses `'a Constr.run`, which is semantically a subtype of `'a tactic`, but I was unsure about breaking the source compatibility just for fun. I can fix it though, if you judge it useful.
- The generalization of tactic-in-terms to any type of argument, as long as there is an interpretation function registered for it.

### CODE REVIEW

**Comment by ejgallego** [comment]
A few comments:
- I am positive we need to export more of the `Nametab` API as the current access is not enough for clients; however I must oppose that we export the current `Nametree` API as it is; it is just not the right API to export for many use cases (like doing identified completion) thus I believe that a) the API is "exported" but marked as private; b) a proper name tree API is designed and exported.
- I am also very concerned about the two `extra` "generic" (that is, type-unsafe) fields added in `interp`. `ltac_vars` is already suspicious (why do we need a special environment for ltac)? How is this supposed to work? AFAICS the commit gives no information to the purpose or need of this fields.

**Comment by ppedrot** [comment]
> I am positive we need to export more of the Nametab API as the current access is not enough for clients; however I must oppose that we export the current Nametree API as is; it is just not the right API to export for many use cases (like doing identified completion) thus I believe that a) the API is "exported" but marked as private; b) a proper name tree API is designed and exported.

I think you're mixing the API need of end-users with the one of low-level code writers here. Clearly we want helper functions around this restricted API, but the atomic primitives are the ones provided by `Nametree`, and those are the ones used throughout the Coq codebase (with name aliasing).

> I am also very concerned about the two extra "generic" (that is, type-unsafe) fields added in interp. ltac_vars is already suspicious (why do we need a special environment for ltac)? How is this supposed to work? AFAICS the commit gives no information to the purpose or need of these fields.

Once again, they're **not** type-unsafe, but dynamically typed. Which is something one needs to write extensible code if we don't know the required interface of those objects. Ideally, Ltac1 should rely on such a mechanism together with late-binding AST mappers to define its own interp_constr and the like, but that's not how its done as of today. In the case of Ltac2, we use this to carry the typing environment for `ltac2:(...)` injections. Other users of the interpretation API could define their own objects. That's pretty much typical of all the crazily extensible code found in typical OO-style open transformers.

**Comment by ejgallego** [comment]
> I think you're mixing the API need of end-users with the one of low-level code writers here. Clearly we want helper functions around this restricted API, but the atomic primitives are the ones provided by Nametree, and those are the ones used throughout the Coq codebase (with name aliasing).

I think I am not; the problem is that the set of atomic primitives provided by `Nametab` is inadequate for several reasons; exposing them is a risk as many people (including me) will be tempted to use them due to spartan nature of the current API. I understand the need to go beyond it, but we should be careful about exposing this API.

> Once again, they're not type-unsafe, but dynamically typed.



> Which is something one needs to write extensible code if we don't know the required interface of those objects. 

I have to disagree here, I think that other non-dynamically typed approaches are possible using polymorphism (c.f. warnings, CEP 12) IMVHO we should try to move away about the current "generic" model as it is quite problematic API-wise in some parts. My favorite example is "ask a normal OCaml developer develop a printer for vernacular expressions".

> In the case of Ltac2, we use this to carry the typing environment for ltac2:(...) injections.

How does that work? In fact this was my primary concern here: "How is this supposed to work? AFAICS the commit gives no information to the purpose or need of these fields"

Maybe I am missing something obvious but I fail to see how LTAC2 is supposed to use these fields.

> Other users of the interpretation API could define their own objects.

and make the life of consumers of such objects really miserable, in particular because our code will type-check but fail to take into account the new "dynamic types". I'd rather try to gather maximum help from the type checker in a system which is over 200.000 lines of code.

> That's pretty much typical of all the crazily extensible code found in typical OO-style open transformers.

Sorry, I did fail to assign a meaning to this, but if anyone was to ask my instinct, the words **"crazily extensible OO-style open transformers"** , far from being reassuring, heavily trigger many alerts in my reptilian brain.

**Comment by ejgallego** [comment]
Oh, I forgot in my original comment, but IMHO it would be great if we could coordinate plans on internalization. On one hand, we have a plan to make a stage-based system with attributes, on the other hand we have the needs of LTAC2. I wonder how they do relate.

**Comment by ejgallego** [comment]
> Ideally, Ltac1 should rely on such a mechanism together with late-binding AST mappers to define its own interp_constr and the like, but that's not how its done as of today.

I can assign many meaning to this, would you mind elaborating more on what this "ideal" model is concretely?

In case it was not clear, note that it is not my intention to block this PR, in the sense that developing LTAC2 is likely way more important than this API design issues. However, I would indeed be very concerned if we merge inadequate API without a fat big warning : INTERNAL, DON'T EVER USE.

We recently had some in-person discussion about what _experimental_ should mean for Coq. I like a pretty radical definition "experimental means it can change at any time, including on stable releases".

**Comment by ejgallego** [comment]
After having a second look to 144f2ac7c7394a701808daa503a0b6ded5663fcc , indeed it won't be a trivial amount of work to remove the generic argument from the AST in favor of a statically-typed one, would we ever want to do that, the selection would have to happen at parsing calling time and I ignore what camlp5 does for polymorphic entries.

**Comment by ejgallego** [comment]
So given how `CHole` is implemented today I think I'll retract my concern for the `extra` argument, for better or worse we are bound to having an AST with dynamic typing in the medium term.

I think I'll provide a patch adding a comment to the file.

My concern wrt to the `Nametab` API is still on thou.

**Comment by ppedrot** [comment]
> > Ideally, Ltac1 should rely on such a mechanism together with late-binding AST mappers to define its own interp_constr and the like, but that's not how its done as of today.

> I can assign many meaning to this, would you mind elaborating more on what this "ideal" model is concretely?

What I meant is that for all AST-transforming primitives such as internalization and pretyping, we apply an open-recursion translation similar to `Constr` primitives (e.g. like `iter`) or more precisely like PPX transformers. For instance, pretyping would be described by a big record:

```ocaml
type pretyping = {
  pretype_var : pretyping -> Id.t -> unit tactic;
  pretype_lam : pretyping -> Name.t -> types -> constr -> unit tactic;
  ...
}
```
where each field corresponds to a constructor of `glob_constr`, together with a blanket implementation
```ocaml
val default_pretyping : pretyping
```
implementing straightforward pretyping, i.e. most notably without Ltac trickery about identifiers and the like.

Observe how the recursion is open, by taking the call to the immediate subterms as an argument. This way, Ltac could redefine its own variant of the pretyper by inheriting `default_pretyping` and overloading the fields for its own needs.

Note that we could even go one step further and functorialize the type over any monad which is a semantical subtype of `tactic`, i.e. by requiring some free monad API over the return type. This would allow to do for free a lot of stuff such as threading an additional environment, etc.

**Comment by matejkosik** [comment]
My naïve hope is that this is reconcilable with the rat-race™.

**Comment by ejgallego** [comment]
Thanks for the update, indeed I was thinking of something such as http://gallium.inria.fr/~fpottier/publis/fpottier-visitors-unchained.pdf but I was not sure.

A couple of thoughts related to your comment (IMHO to be discussed at Le Croisic not to pollute this PR more), first, I am not sure we really want to keep that for "internalization" IMHO we would like to substitute it for passes on the AST, however the genarg embedding thing greatly complicates the design :( I have no idea whether the cost/benefit of an overridable pretyper is worth it.

I have also been thinking for a while what would mean to make the pretyper/unification use the tactic engine, and I am not sure I fully like the implications wrt to modularity of the codebase. Imagine I want to design my own proof engine, (a perfectly valid intention IMHO). I would hope that my proof engine would sit above unification and pretyping, and that I could use both components in a modular way. If we tie them to the current proof engine, coupling would become way stronger.

**Comment by maximedenes** [comment]
@ejgallego What do you suggest to do about your `Nametab` concerns?

**Comment by ejgallego** [comment]
> What do you suggest to do about your Nametab concerns?

I big fat warning in the `.mli` marking this stuff as "not for public use" would be fine to me.

**Comment by maximedenes** [comment]
Sounds good as a temporary solution. @ppedrot can you take care of it?

**Comment by ppedrot** [comment]
Done.

**Comment by ejgallego** [comment]
@ppedrot the CI fails in the `-warn-error` case.

**Comment by ppedrot** [comment]
I fixed the first one encountered, but I don't really know to check for them all at once. Furthermore, can it be the case that at the time this PR branch, the `-warn-error` flag was not enforced and some lines that were triggering warnings were removed in trunk?

**Comment by SkySkimmer** [comment]
You can just compile with -warn-error on your machine. If the warning is due to a combination of your changes and parallel merges into trunk you may need to compile the result of merging.
travis merges before testing so lines removed in trunk are removed in the version travis compiles (merge conflict means no travis).

**Comment by ppedrot** [comment]
What do you mean, with warn-error? By setting the `USERFLAGS` variable to it? Then it miserably fails in unrelated stuff complaining that implementations are missing. Is there some configure time flag or something?

**Comment by SkySkimmer** [comment]
-warn-error is a configure flag (which tells the Makefiles to use the ocaml flag of the same name)
Actually it should still warn without it (just without failing since it's just warnings) so you shouldn't strictly need to run -warn-error if you watch for warnings in the compilation log.

**Comment by ppedrot** [comment]
@SkySkimmer There are a few spurious deprecation warnings in my OCaml version. Anyway I've merged and pushed again, it should be OK now.

**Comment by maximedenes** [comment]
Summary of WG discussion: ok to merge

**Pull request merged**
