### PR TITLE
Remove unused `overwrite` optional argument of tactic_extend

### PR DESCRIPTION
**Pull request by SkySkimmer**
May be unused since its ancestors from before 2000 AFAICT

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
This is precisely there for hacking purposes.

**Comment by SkySkimmer** [comment]
What does that mean?

**Comment by ppedrot** [comment]
It's a way to hook into the internals, in case a external plugin wants e.g. to keep track of calls to some primitive ML tactic without having to recompile a separate branch.

**Comment by ppedrot** [comment]
I don't really see the risk nor the maintenance cost of this API, while I see the problem with having to use a dedicate Coq branch to be able to test a given plugin. I won't insist much though, if you really want to get rid of it please carry on.

**Pull request closed without merging**
