### PR TITLE
Fix recursively vs corecursively defined message

### LINKED ISSUE #12177: Coq mixes up reporting "recursively defined" and "corecursively defined"
#### Description of the problem

These are backward:

```coq
CoInductive T: Type := mkT.
CoFixpoint corecursive (x:T) : T := x.
(* corecursive is defined
   corecursive is recursively defined *)
Fixpoint recursive (x:unit) : unit := x.
(* recursive is defined
   recursive is corecursively defined *)
```

Seems likely #11785 broke this in a refactor.

#### Coq Version

8.12+alpha

### PR DESCRIPTION
**Pull request by tchajed**
**Kind:** bug fix.

Closes #12177

- [ ] Added / updated test-suite

I'm not sure it's possible to test this, since it's an info message.

### CODE REVIEW

**Comment by ppedrot** [comment]
This is already part of #12121, I don't know if it's worth it to merge separately.

**Comment by ppedrot** [comment]
(Although this PR is self-contained, which is a clear advantage.)

**Review by ppedrot — APPROVED** [review]

**Comment by herbelin** [comment]
Please merge this PR which is well-delimited and ready.

**Comment by tchajed** [comment]
Awesome, thanks for the fast responses @ppedrot and @herbelin!

**Pull request merged**
