### PR TITLE
Fix `make TIMED=1` garbage

### PR DESCRIPTION
**Pull request by JasonGross**
It should not emit ` (user: 0.00 mem: 2852 ko)` multiple times

### CODE REVIEW

**Review by gares — CHANGES_REQUESTED** [review]
No please, the right fix is to move $(TIMER) where $(COQC) and $(COQCHK) are used, and leave $(COQC) hold the path of the `coqc` binary.

This way even if $(TIMER) holds a value, calling $(COQC) to print the version of Coq does not print how long it takes to do that...

**Comment by JasonGross** [comment]
@gares Updated

**Comment by maximedenes** [comment]
@gares is it ok now?

**Comment by maximedenes** [comment]
@gares ping

**Comment by maximedenes** [comment]
@gares ping

**Review by gares — APPROVED** [review]

**Pull request merged**
