### PR TITLE
Delay the computation of frozen evars in legacy unification.

### PR DESCRIPTION
**Pull request by ppedrot**
This source of slowness has been observed in VST, but it is probably pervasive. Most of the unification problems are not mentioning evars, it is thus useless to compute the set of frozen evars upfront.

We also seize the opportunity to reverse the flag, because it is always used negatively.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench:
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬────────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │         mem faults         │
│                        │                         │                                             │                                             │                                │                            │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │     NEW     OLD    PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│                coq-vst │ 2934.66 3007.84 -2.43 % │     8162481235423     8366797808373 -2.44 % │    11202780571581    11522043394812 -2.77 % │    2215332    2217576  -0.10 % │     582     860   -32.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│ coq-mathcomp-ssreflect │   68.15   68.49 -0.50 % │      187965304997      188008626284 -0.02 % │      269146250029      269397014168 -0.09 % │     530664     530884  -0.04 % │      27     162   -83.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│    coq-formal-topology │   60.98   61.25 -0.44 % │      166435851263      167214676716 -0.47 % │      253028633270      253339683162 -0.12 % │     477844     477932  -0.02 % │       0       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│            coq-bignums │  100.18  100.59 -0.41 % │      277940362133      278098640925 -0.06 % │      401489895074      403290089560 -0.45 % │     533320     536388  -0.57 % │     290      43  +574.42 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│ coq-mathcomp-odd-order │ 1384.86 1389.87 -0.36 % │     3857935032534     3872518173463 -0.38 % │     6492592259428     6492044661009 +0.01 % │    1365092    1365220  -0.01 % │     264     146   +80.82 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│     coq-mathcomp-field │  261.38  262.14 -0.29 % │      727005087115      728125055762 -0.15 % │     1100210184099     1100411294039 -0.02 % │     756300     756292  +0.00 % │       2      15   -86.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│               coq-hott │  342.48  343.29 -0.24 % │      948885519899      951142723904 -0.24 % │     1448191471213     1448972447842 -0.05 % │     611584     611596  -0.00 % │     477       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│        coq-lambda-rust │ 2329.85 2334.48 -0.20 % │     6489910120983     6501928990940 -0.18 % │     8906085103396     8916084076485 -0.11 % │    1427656    1406064  +1.54 % │      59       5 +1080.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│              coq-color │  738.13  739.48 -0.18 % │     2047034486426     2048274527304 -0.06 % │     2465568011933     2466080634262 -0.02 % │    1356844    1356700  +0.01 % │      43     447   -90.38 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│            coq-unimath │ 1420.64 1421.97 -0.09 % │     3947132839282     3947049978796 +0.00 % │     6692294912956     6691959656268 +0.01 % │    1083472    1083260  +0.02 % │     342      23 +1386.96 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│             coq-sf-plf │   77.30   77.33 -0.04 % │      213456548452      213330931143 +0.06 % │      312477733964      312730714547 -0.08 % │     518292     513200  +0.99 % │      15       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│               coq-corn │ 1534.42 1534.40 +0.00 % │     4259609841789     4259608523193 +0.00 % │     6272717187483     6273184309866 -0.01 % │     834840     835920  -0.13 % │      44      44    +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│  coq-mathcomp-fingroup │   84.98   84.95 +0.04 % │      235280946980      234718018883 +0.24 % │      348915905924      349079063560 -0.05 % │     584348     584536  -0.03 % │       6     101   -94.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│        coq-fiat-crypto │ 6190.36 6187.36 +0.05 % │    17216215515498    17219600256059 -0.02 % │    27965823121446    28021602899543 -0.20 % │    2457960    2516688  -2.33 % │    1685    1362   +23.72 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│              coq-sf-lf │   46.95   46.91 +0.09 % │      129808354650      129028713523 +0.60 % │      211423129541      211665238486 -0.11 % │     426280     426344  -0.02 % │     129       0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│       coq-math-classes │  252.87  252.62 +0.10 % │      696628401235      696443491107 +0.03 % │      912129608801      912405433397 -0.03 % │     524744     524632  +0.02 % │      90      83    +8.43 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│   coq-mathcomp-algebra │  186.44  186.23 +0.11 % │      517368151167      516946634775 +0.08 % │      704427647970      704834668285 -0.06 % │     640692     640616  +0.01 % │     327      16 +1943.75 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│             coq-sf-vfa │   49.84   49.77 +0.14 % │      137998866498      138172334576 -0.13 % │      221696704545      221970896718 -0.12 % │     535612     535444  +0.03 % │      30       5  +500.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│         coq-coquelicot │  106.73  106.56 +0.16 % │      295930446373      295104563152 +0.28 % │      400407355732      400190020462 +0.05 % │     708140     707892  +0.04 % │     281      14 +1907.14 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│       coq-fiat-parsers │  717.14  715.97 +0.16 % │     1989746976754     1984992215224 +0.24 % │     3037052561361     3038076550317 -0.03 % │    2810996    2882216  -2.47 % │     594     699   -15.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│             coq-geocoq │ 2015.06 2010.23 +0.24 % │     5596833301278     5582122868891 +0.26 % │     8117029012568     8118031455990 -0.01 % │    1213256    1217244  -0.33 % │     598     177  +237.85 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│ coq-mathcomp-character │  282.25  281.52 +0.26 % │      784356231504      782498628881 +0.24 % │     1124807891744     1125179446297 -0.03 % │    1096764    1097228  -0.04 % │      27     164   -83.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│  coq-mathcomp-solvable │  218.25  217.56 +0.32 % │      605295613399      604296346369 +0.17 % │      857521969611      857668939553 -0.02 % │     863024     864096  -0.12 % │       0       1  -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│          coq-fiat-core │  137.99  137.44 +0.40 % │      382957587958      382983211495 -0.01 % │      513445053761      513821428323 -0.07 % │     499220     499536  -0.06 % │     614     193  +218.13 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│           coq-compcert │  890.54  883.07 +0.85 % │     2468596955900     2448128806111 +0.84 % │     3559035437757     3558784642553 +0.01 % │    1328040    1327700  +0.03 % │     582     304   +91.45 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼────────────────────────────┤
│              coq-flocq │  597.40  590.56 +1.16 % │     1661872889270     1644070871166 +1.08 % │     2422932022825     2420477913023 +0.10 % │    1586060    1772756 -10.53 % │     387     571   -32.22 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴────────────────────────────┘
```

Note that the difference in time in VST is actually concentrated almost in only one file. I am a bit surprised by the slowdown in compcert, in which we should have solved the same performance issue as VST. I'll relaunch a bench to be sure.

**Comment by mattam82** [comment]
That's curious indeed.

**Review by mattam82 — COMMENTED** [review]
The change to allowed_evars might makes things clearer. Why add AllowAll when this can be represented by AllowFun (fun _ => true), to avoid closures?

**Comment by ppedrot** [comment]
> to avoid closures

Well technically `fun _ -> true` is not a closure, but well, having a non-functional data for 3/4 of the calls seems cleaner to me.

**Comment by mattam82** [comment]
@ppedrot Did the new bench give you any answer?

**Comment by ppedrot** [comment]
It showed a similar slowdown. I remember that with an explicit lazy set it was faster, I'll try to adapt the PR.

**Comment by vbgl** [comment]
Is someone working on this for 8.10? If not please update the milestone label.

**Comment by ppedrot** [comment]
So I reran the benches on a recent master and could not observe any slowdown. Maybe it was noise after all?
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │       mem faults       │
│                        │                         │                                             │                                             │                               │                        │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW    OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│            coq-bignums │   68.19   69.08 -1.29 % │      189881374323      192117000685 -1.16 % │      251869363526      253727841636 -0.73 % │     492168     493324 -0.23 % │     180    143 +25.87 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│          coq-fiat-core │  109.53  110.08 -0.50 % │      311885889317      313355413679 -0.47 % │      390830517296      390883911548 -0.01 % │     494312     494332 -0.00 % │     297    204 +45.59 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│           coq-compcert │  778.61  782.17 -0.46 % │     2169410887021     2178118023334 -0.40 % │     2921952214562     2923113219130 -0.04 % │    1066028    1065904 +0.01 % │     257    165 +55.76 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│              coq-color │  704.46  707.64 -0.45 % │     1966794264848     1979369851799 -0.64 % │     2352538650531     2353141685254 -0.03 % │    1386036    1340444 +3.40 % │      80     89 -10.11 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│        coq-lambda-rust │ 1528.64 1535.49 -0.45 % │     4260060356979     4278679275833 -0.44 % │     5648018979527     5645541336003 +0.04 % │    1486488    1485568 +0.06 % │      47      4 +1075.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│              coq-verdi │  119.49  120.01 -0.43 % │      332476864991      333844523560 -0.41 % │      419807227496      419789772927 +0.00 % │     561312     561068 +0.04 % │      10      6 +66.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│       coq-fiat-parsers │  639.34  641.58 -0.35 % │     1787279867326     1794390350378 -0.40 % │     2705585201146     2706290107929 -0.03 % │    3188516    3198688 -0.32 % │     302    671 -54.99 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│         coq-coquelicot │   76.40   76.66 -0.34 % │      209554026507      210508860267 -0.45 % │      255026340623      255015906840 +0.00 % │     662820     662688 +0.02 % │     215     12 +1691.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│         coq-verdi-raft │ 1319.54 1323.81 -0.32 % │     3682176106761     3693575258813 -0.31 % │     4999582763109     4998952560566 +0.01 % │    1812192    1812132 +0.00 % │       0      1 -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│               coq-corn │ 1452.50 1457.04 -0.31 % │     4055235452103     4068060406465 -0.32 % │     6019379000671     6019656446217 -0.00 % │     860680     860764 -0.01 % │       1      7 -85.71 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│  coq-mathcomp-fingroup │   51.28   51.44 -0.31 % │      143030105712      143178930203 -0.10 % │      186620755071      186597548036 +0.01 % │     565568     565464 +0.02 % │       7      5 +40.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-fiat-crypto-legacy │ 6295.78 6309.94 -0.22 % │    17531461799281    17570907990232 -0.22 % │    28485633493030    28538609842093 -0.19 % │    2386936    2386512 +0.02 % │     919    994 -7.55 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│              coq-flocq │  463.12  463.92 -0.17 % │     1287735078872     1290635593531 -0.22 % │     1783513619769     1783275343120 +0.01 % │    1118492    1118864 -0.03 % │     226     66 +242.42 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│        coq-fiat-crypto │ 3801.69 3807.70 -0.16 % │    10560850360116    10576171882218 -0.14 % │    16545138212909    16567583864449 -0.14 % │    2344004    2351632 -0.32 % │    1108    794 +39.55 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│             coq-geocoq │ 1576.56 1579.00 -0.15 % │     4401875409817     4409577915822 -0.17 % │     6444154146810     6447096377712 -0.05 % │    1365700    1365836 -0.01 % │     108    215 -49.77 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│     coq-mathcomp-field │  230.76  231.04 -0.12 % │      643319790006      643827806716 -0.08 % │      920433446738      920428212612 +0.00 % │     741280     741348 -0.01 % │       0     78 -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-mathcomp-character │  182.33  182.45 -0.07 % │      507935970039      508217828526 -0.06 % │      672061298285      672007795542 +0.01 % │     898740     897640 +0.12 % │      95     46 +106.52 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-mathcomp-ssreflect │   40.18   40.20 -0.05 % │      110887398411      110952381981 -0.06 % │      134702451220      134691903897 +0.01 % │     527892     527832 +0.01 % │     132     11 +1100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│   coq-mathcomp-algebra │  165.04  165.09 -0.03 % │      459671121353      460367094215 -0.15 % │      570755744587      570792718435 -0.01 % │     636052     636108 -0.01 % │      14      6 +133.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│  coq-mathcomp-solvable │  189.10  189.12 -0.01 % │      527143054655      527389589443 -0.05 % │      705706007108      705710064824 -0.00 % │     773688     773860 -0.02 % │       6      2 +200.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│               coq-hott │  338.40  338.36 +0.01 % │      917539359878      919939323527 -0.26 % │     1376311087724     1376901937859 -0.04 % │     479864     479908 -0.01 % │     458    265 +72.83 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│            coq-unimath │ 4038.72 4033.24 +0.14 % │    11254471435260    11239422485861 +0.13 % │    20805646452225    20807333656991 -0.01 % │    1794360    1735416 +3.40 % │     523    198 +164.14 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-mathcomp-odd-order │ 1437.80 1435.41 +0.17 % │     4008281307523     4001624325693 +0.17 % │     6864359866079     6864728688625 -0.01 % │    1240192    1240156 +0.00 % │      41     26 +57.69 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│          coq-fourcolor │ 2170.20 2163.55 +0.31 % │     6052424921715     6035173148856 +0.29 % │    11362290695169    11362812533996 -0.00 % │     930060     930092 -0.00 % │       1      0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│       coq-math-classes │  217.68  216.92 +0.35 % │      607116735733      607053432209 +0.01 % │      769195736827      769207709849 -0.00 % │     514728     514740 -0.00 % │      22     15 +46.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│             coq-sf-plf │   44.18   43.85 +0.75 % │      123569458324      123874836610 -0.25 % │      160045837336      160074103603 -0.02 % │     493180     492900 +0.06 % │      30      0  +nan % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴────────────────────────┘
```

If so I believe that this PR is ready to go.

**Review by mattam82 — APPROVED** [review]
Looks good, and I guess the generalization of the flag from a set to a function is going to be useful in other cases as well.

**Comment by mattam82** [comment]
We don't have vst in the CI anymore?

**Comment by ejgallego** [comment]
> We don't have vst in the CI anymore?

It wasn't launched, added to the list here https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/758/console

Tho these opam-based packages tend to be a bit out of date, let's see if that works.

**Comment by vbgl** [comment]
Should we consider backporting this performance improvement to the 8.10 branch?

**Comment by mattam82** [comment]
It's slightly changing the (mainly internally used) API, otherwise it is fine.

**Comment by maximedenes** [comment]
@ppedrot any reason why this should not also be done in evarconv? I'm asking because it now shows up in unifall. I can take care of it, if you think it is the way to go.

**Comment by ppedrot** [comment]
@maximedenes you should probably do the same for evarconv indeed.

**Pull request merged**
