### PR TITLE
Type cleanup in `Metasyntax`

### PR DESCRIPTION
**Pull request by ejgallego**
Types were a bit difficult to read as they were mostly based on
anonymous products, this commit replaces them by named records and
refactors out some imperative code.

There is still quite a bit of room for improvement, but at least the
records provide a basis for more fine-grained understanding and
documentation.

### CODE REVIEW

**Comment by herbelin** [comment]
Even if this is mainly cosmetic, no objection on my side. I understood from various previous discussions in working group that there were a general preference for named records over anonymous tuple, as this somehow self-documents itself.

I would be happy to hear also the opinion from people who are liable to work on this part of the code in the future, or from other people having tried to read the code and maybe suffered about understanding it.

For instance, also working at documenting the functions of metasyntax.ml would be a very nice added value.

**Comment by ejgallego** [comment]
Thanks for the review Hugo, indeed let's hear from others. I plan to document it a bit more, and maybe refactor some bits (such as the duplicated final parts in `add_notation_in_scope/add_notation_interpretation_core`) and uniformize records.

It would be great if people more familiar with the code could add some documentation, there still are some records hard to guess.

**Comment by ppedrot** [comment]
LGTM. There is indeed still work to do both from the point of view of documentation and code cleanliness, but this is a very good first step.

**Comment by maximedenes** [comment]
Merged, thanks!

**Comment by ejgallego** [comment]
Merci !

**Pull request merged**
