### PR TITLE
Fixing #2881 ("change with" failing in an Ltac definition).

### PR DESCRIPTION
**Pull request by herbelin**
A present for Jason...

The code around internalization/interpretation of pattern remains pretty convulated. How is doing Ltac2 on this matter (`change with`, `match goal`, ...)? Is it worth making Ltac1 improve on pattern interpretation or is Ltac2 ready to take the continuation, and, e.g., to eventually provide support for things such as `replace (S ?x = ?y) with (x = S y)` etc.?

### CODE REVIEW

**Comment by ppedrot** [comment]
@herbelin There is no proper handling of this feature of the `change` tactic in Ltac2, although it wouldn't be that hard I guess. Essentially the only thing you have to do is to take a function as the right-hand-side argument and compute the result on the fly. That's what is done for match over terms and goals.

**Comment by herbelin** [comment]
I think my question is: I would like to provide a `replace (S ?x = ?y) with (x = S y)`. Currently, this is difficult because there is no easy way to make the interpretation of two productions of a `TACTIC EXTEND` dependent one over the other (though maybe `uconstr` could now help?). Is it worth that I spend some time in developing this on top of the current Ltac1 `TACTIC EXTEND` `intern`/`interp` architecture or will it be easier to do in Ltac2?

**Comment by ppedrot** [comment]
@herbelin Definitely easier, although I'm sure you can already do that in Ltac1 with TACTIC EXTEND by returning a function as the second argument through a new dynamic argument.

**Review by ppedrot — COMMENTED** [review]
As far as Ltac semantics are involved, this looks OK. The test seems very ill-chosen though. Aren't we planning to remove (Ltac) definitions inside proofs at some point?

**Comment by ppedrot** [comment]
@herbelin I've just implemented the change tactic in Ltac2. This relies on the same kind of macro-expansion used for match-goal, i.e. the notation computes the meta-variables defined in a pattern and abstracts another term over them. For instance, the following code:
```
change (?a + 1 = 2) with (2 = $a + 1).
```
is expanded to
```
let cl := None
with c := (
  Some pattern:(?a + 1 = 2),
  (fun a => let a := Array.get a 0 in constr:(2 = $a + 1))) in
change0 c cl
```
where
```
change0 : pattern option * (constr array -> constr) -> clause option -> unit
```
Note how `a` is bound in the quotation `constr:(2 = $a + 1)`.

**Comment by herbelin** [comment]
> The test seems very ill-chosen though. Aren't we planning to remove (Ltac) definitions inside proofs at some point?

Very ill-chosen because of `Ltac` coming after `Goal` or for another reason? In any case, I moved the `Ltac` before. (Note though that it was after `Goal` in the original report.)

**Comment by herbelin** [comment]
> I've just implemented the change tactic in Ltac2. This relies on the same kind of macro-expansion used for match-goal, i.e. the notation computes the meta-variables defined in a pattern and abstracts another term over them. 

Yes, I think you're right in this approch.

> For instance, the following code:
> ```
> change (?a + 1 = 2) with (2 = $a + 1).
> ```
By the way, I have a question: if we remove all `$`'s from an `Ltac2` syntactic expression, is there a way to canonically reinsert them or there would be cases where it is ambiguous (assuming that we reason up to α-conversion, e.g. adopting Barendregt's convention to have all kinds of binders globally distinct)?

**Review by ppedrot — APPROVED** [review]
With the Ltac definition outside of the goal in the test, I now fully approve this PR.

**Comment by ppedrot** [comment]
> By the way, I have a question: if we remove all $'s from an Ltac2 syntactic expression, is there a way to canonically reinsert them or there would be cases where it is ambiguous (assuming that we reason up to α-conversion, e.g. adopting Barendregt's convention to have all kinds of binders globally distinct)?

We're a bit hijacking this thread, but while we're at it: I don't think it is possible to do what you propose, as there is always the ambiguity between a bound variable and a global constant. Even with Barendregt's conventions, this makes a fundamental closed-world assumption, because the well-definedness of a term is not stable by extension of the environment.

(By the way, I never quite understood all the fuss around Barendregt's convention. It's a technique that allows nice-looking handwaving on paper, but which turns out to be a real pain to formalize, if doable at all, while we have De Bruijn indices that *just work* at our fingertips.)

**Comment by herbelin** [comment]
> We're a bit hijacking this thread, but while we're at it: I don't think it is possible to do what you propose, as there is always the ambiguity between a bound variable and a global constant. 

The reason I'm asking is that it seems (at least superficially), that if the `$`'s were dropped in the syntax and re-inferred at internalization time, one would get _exactly_ (?) the same syntax for primitive tactics as in current Coq, and, thus, your code could already replace all the parsing/interp/intern/subst rules done for atomic tactics (while additionally providing an applicative syntax for them).

> Even with Barendregt's conventions, this makes a fundamental closed-world assumption, because the well-definedness of a term is not stable by extension of the environment.

That's right, but this is already the case for `constr`, so, would you like that we have different syntactic classes for global references and variables already in Gallina?

> (By the way, I never quite understood all the fuss around Barendregt's convention. It's a technique that allows nice-looking handwaving on paper, but which turns out to be a real pain to formalize, if doable at all, while we have De Bruijn indices that just work at our fingertips.)

Your remark is amusing because I never understood all the fuss around Barendregt's convention either (for the reason that it is not stable by reduction, and this is probably what you mean by it being a real pain to formalize, and also for the reason that, as a programmer, I don't see what is wrong in writing things like `let x = ... in let x = ... in ...`). If I used this expression it is because I thought it would emphasize better what I wanted to describe, namely a situation where all names are distinct over both Ltac's  and `constr` bindings (knowing also that I read many papers referring to Barendregt's convention and that I then got used to consider that it belongs to the basic λ-calculus background).

**Pull request merged**
