### PR TITLE
[ci] [docker] Add more dependencies for Dune-aware jobs.

### PR DESCRIPTION
**Pull request by ejgallego**
- odoc: used to generate the ML API documentation by Dune's `@doc` target.
- dune-release: Automatic OPAM package generation and release.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Why do this now instead of when we want to use them?

**Comment by ejgallego** [comment]
#8053 depends on this one.

**Comment by SkySkimmer** [comment]
So include this in it.

**Comment by ejgallego** [comment]
> So include this in it.

It is already included, rebasing just in case.

**Comment by SkySkimmer** [comment]
Part of #8053

**Pull request closed without merging**
