### PR TITLE
deprecate prod_curry and prod_uncurry

### PR DESCRIPTION
**Pull request by liyishuai**
Per https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/prod_curry.2Funcurry.20seem.20named.20backward

**Kind:** feature.

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

**Comment by Blaisorblade** [comment]
Cool, thanks! Follow-up: Can a library be compatible with older Coqs, use these functions and avoid triggering warnings?

**Comment by liyishuai** [comment]
> Can a library be compatible with older Coqs, use these functions and avoid triggering warnings?

I know Java has `@SuppressWarnings("deprecation")`, maybe worth a Coq equivalent?

**Comment by Zimmi48** [comment]
Yes, you should use `Set Warnings "-foo".` where `foo` is either the warning name or the warning category. You can also add `Set Warnings "foo".` afterwards to reactivate the warning for the rest of the file.

**Comment by anton-trunov** [comment]
CI keeps failing for this PR. Can something be done here? Maybe a rebase would help if it has already been fixed on master?

**Comment by liyishuai** [comment]
CI seems happy now.

**Pull request merged**
