### PR TITLE
Remove unused print tagging infrastructure

### PR DESCRIPTION
**Pull request by ejgallego**
This PR removes the functorial-based tagging parametrization printers. It also removes unused "generic" tags.

Printers now tag unconditionally, and it is up to the backends to interpret tags.

The motivation for this PR is:
- The full capabilities of the API were not used, the intended use case was not clear.
- It made printers more complex, but extensiblity still depended on manual modification of printers.
- Unused `Ppannotation` confused people as what its purpose was.

The PR is split in two patches. The first one removes the functors, the second initiates a rework of tagging.

Future work is to sync the notion of rich document and tags.

Tested, test-suite passes, colors work, saves 24K of bytecode.

Notes:
- We have also removed the `Richprinter` module. It was only used in the `annotate` IDE protocol call, its output was identical to the normal printer (or even inconsistent if taggers were not kept manually in
  sync).
- Note that Richpp didn't need a single change for the first part. This is due as its main API entry point `Richpp.rich_pp` is not used by anyone.

### CODE REVIEW

**Comment by ejgallego** [comment]
Test suite just passed on the new rebase.

**Comment by ppedrot** [comment]
I'm not against merging that PR in 8.6 (if time permits) but I would like to hear from @yurug first...

**Comment by gares** [comment]
Lets put it like that: if Yann does not shout now, we merge it.  If the generality the old coded provided will be needed again, we will put it back.  We can always undo a commit if we need.

**Comment by ejgallego** [comment]
Sure, let's wait for @yurug . I'd have no problem delaying this 8.7, the only pain is to have to do the rebase again which is not trivial. By the way, I have been working on coqdoc/jscoq for a while, Clément has done the Sphinx adaptation, merging `richpp/std_ppcmd` was discussed for a bit. At least on our side we'd like to converge so it would be great to talk.

Note that there are still a few quirks coming from the old setup like `pp_with` still taking a `?pp_tag` parameter, the duplicated printing in toplovel (which has to be removed with extra care) etc... 

Likely the next time we will propose to touch the printing part is when SerAPI consumers have specific printing use cases, we are not in that moment yet.

**Comment by yurug** [comment]
Please do not remove the generality of RichPp. As Pierre-Marie said, I use it in plugins (and maybe others do too.)

If you want a serializable RichPp, I can prepare a patch for 8.7 if you want.

**Comment by ejgallego** [comment]
Ok! Let's postpone this 8.7. A couple of comments:
- would you mind pointing out where this is used? I had trouble figuring out how it could be used.
- we already serializable richpp, no need to do anything here, thanks.

**Comment by gares** [comment]
@yurug, can you point us to such piece of code?  I guess it would clarify how to take advantage of the RighPp API, since there is not code in Coq really doing so.

**Comment by ejgallego** [comment]
By the way @yurug , the plan we discussed was to be able to serialize `std_ppcmds`, so IDEs could do reflowing themselves, obviously that representation of `Tags` was a problem. Once you go to a standard representation of tags (take for instance the SGML model), then you can even unify `std_pcmds` with `Richpp.t` (which serializes fine today even if IDEs have a hard time interpreting the non standard model).

[A pet-peeve of mine, why some Coq modules follow the `M.t` convention where others do `M.m` for their private datatypes; it would be great to agree on this]

**Comment by ejgallego** [comment]
Also, not that I mind so much, but I'd like to remind that the tag interface, apart from impure, is unsafe. Hint: try `let _ = Tag.create "uh", Tag.create "uh"`.

**Comment by ppedrot** [comment]
This is not the bloody definition of being unsafe. It would be unsafe if this function allowed Coq to segfault, which it does not. Words have a meaning, pretty please.

**Comment by ejgallego** [comment]
Well, I dunno what you call `unsafe`, I'd bloody say that Coq aborting with a fatal error seems pretty "unsafe" to me:
```
Dynamic tag collision: uh vs. uh
Fatal error: exception File "lib/dyn.ml", line 84, characters 6-12: Assertion failed
```

**Comment by ejgallego** [comment]
YMMV.

**Comment by ppedrot** [comment]
Yes, when a non-statically checkable precondition of a function is not verified, it is usual to die badly at runtime. Try randomly dropping a few universes in an evarmap and see what happens, for instance.

**Comment by gares** [comment]
Dyn are dynamic types, so type declaration and type checking are done at run time. A program with a dynamic type error does not terminate with a result, it terminates with a run time exception.

**Comment by ejgallego** [comment]
Sorry, but that is a "global precondition", how can for instance plugin writers manage that global namespace.

And sorry again, but in functional programming it is not usual "to die badly at runtime".

**Comment by gares** [comment]
Emilio, you name the dynamic type "yourplugin:yourtype" ;-)

**Comment by ejgallego** [comment]
@gares thus the dynamic types interface makes Coq to segfault, thus it is unsafe. I don't say that I'm opposed to dynamic types, but I am just pointing out that they are, well, unsafe.

**Comment by ejgallego** [comment]
> Emilio, you name the dynamic type "yourplugin:yourtype" ;-)

Oh well... :rooster: also I need to make sure that my init function is never called again...

**Comment by gares** [comment]
I think the only way to use dynamic types reasonably is to declare them at the top level of a file.  Such code is executed once and forall when the plugin is loaded.  So yes, maybe dyn.mli should say that.

**Comment by ejgallego** [comment]
My point is that we have an unsafe pretty printing module. This has a set of drawbacks, (no serialization, modules have to coordinate, reentrancy, etc..) Now, what I am waiting for is what are the benefits.

**Comment by ejgallego** [comment]
> I think the only way to use dynamic types reasonably is to declare them at the top level of a file. Such code is executed once and forall when the plugin is loaded. So yes, maybe dyn.mli should say that.

IMO no point on discussing more about this, but things start to get pretty messy when you want to have fancy modules that can unregister, etc..

**Comment by gares** [comment]
My impression is that people are doing there with dynamic types, is what one could do with objects: they say a tag is a base class to be extended by the user.  To me the real question is why not objects %-)  given that (O)Caml has objects.  Am I right @yurug ?

**Comment by ejgallego** [comment]
Also, it is possible to do safe dynamic typing, but may be involved in Ocaml.

**Comment by ppedrot** [comment]
@ejgallego: "the dynamic types interface makes Coq to segfault, thus it is unsafe". This is just false. A segfault (i.e. corrupting memory) is not the same as an unhandled exception. I mean, this is the whole story about "well-typed programs can't go wrong", and the ML progress theorem you usually prove as an undergraduate does take into account this case (viz. value, exception and non-termination). I am not wishing to spend more time on this sterile topic, so I'll refrain from responding here to this longstanding troll.

As for the POO stance, we cannot use OCaml object because of serialization, and thus rely on registering methods on dynamic types at toplevel through the Dyn.Map module. Same for OCaml 4.03 extensible types which rely on pointer equality (just as exceptions).

**Comment by ejgallego** [comment]
Oh indeed that statement I wrote is incorrect, sorry:

> thus the dynamic types interface makes Coq to segfault

should read:

> thus the dynamic types interface makes Coq to abort with a fatal error

**Comment by ejgallego** [comment]
By the way, while I agree that the topic is sterile, I must strongly disagree with your use of the word "troll" here. I sincerely hope you are not referring to me as a "troll" or you intended a non standard meaning.

Best regards,
Emilio

**Comment by maximedenes** [comment]
@yurug, could you point us to some code you mentioned using the generality of RichPP and comment on the use of objects suggested by @gares ? It will help us take the best decision. Thanks!

**Comment by ejgallego** [comment]
This is mostly superseded by https://github.com/ejgallego/coq/tree/pp_new , however I'd like to get some feedback in the WG before I close this and propose a merge.

**Comment by ejgallego** [comment]
Superseded by #390

**Pull request closed without merging**
