### PR TITLE
[travis] Remove some jobs that are run by CircleCI.

### PR DESCRIPTION
**Pull request by maximedenes**
Travis has a lot of capacity issues these days (as well as spurious
failures), so we remove the jobs that are better handled by CircleCI
because of the dependency handling.

We may want to remove more jobs, since CircleCI handles the others
nicely, but let's try this as a first step.

### CODE REVIEW

**Comment by Zimmi48** [comment]
While overall in favor of this change, I'm also a bit worried of the consequences: what will happen when everyone starts running CircleCI on their fork? What time will take the backporting process? ...
That being said, experience will tell so I'm still OK for trying.
However, given that the main role of testing external developments is now shifted from Travis to CircleCI, I think it is time to update the corresponding documentation (I'm talking about `CONTRIBUTING.md` and `dev/ci/README.md`).

**Comment by ejgallego** [comment]
I think that Circle hasn't seen enough testing as to become the default by far.

**Comment by maximedenes** [comment]
Well, it seems to be working great and is much faster than Travis. That said, keeping things as they are is only going to slow down the integration of PRs, I won't be the first to complain.

**Comment by SkySkimmer** [comment]
>I think that Circle hasn't seen enough testing as to become the default by far.

The travis failures are pretty bad though.

**Comment by maximedenes** [comment]
> The travis failures are pretty bad though.

Indeed. I don't remember the last time I merged two PRs in a row without bypassing spurious failures. It is only a matter of time before I bypass actual failures by mistake...

**Comment by ejgallego** [comment]
> It is only a matter of time before I bypass actual failures by mistake...

How can that happen if Circle CI is enabled? If the problem is the github indicators, I'd be OK with a flag that would skip those builds if building on the main Coq repos, but it would still build on the user's branch.

**Comment by maximedenes** [comment]
> How can that happen if Circle CI is enabled?

I don't know how to distinguish Travis from Circle CI in the merge scripts and filters.

**Comment by Zimmi48** [comment]
> I don't know how to distinguish Travis from Circle CI in the merge scripts and filters.

I think I could set GitHub for this but this basically means that we stop caring about the MacOS jobs and the linter (everything that is in Travis only). So I'm not in favor of that.

**Comment by SkySkimmer** [comment]
I don't think we can distinguish in the filters but for the scripts we might be able to do something with the github API.
Here's some exploration, looking at #6620.
https://gist.github.com/SkySkimmer/0cd929f99a2cd49c12e8b855f3c0b733
There are a lot of statuses (209!).
Circle CI seems to create 2 identical statuses per job (possibly one at creation and one at success). Jobs can be recognised by the `context` field (eg `"context": "ci/circleci: opam-boot"`).
Travis seems to make 1 status per job (possibly will double on completion) all identical.

So we could make a script like
```python
for status in statuses:
  # TODO state == 'pending'
  if status.state == 'failure':
    # also record target_url ?
    failed += [status.context]

remove duplicates from failed

if failed:
  print "the following failed:"
  for status in failed:
    print failed
```
Which would say something like
```
the following failed:
ci/circleci: iris-lambda-rust 
```
(current state of this PR ^^)

Statuses are accessed by repository and commit so I don't know how this interacts with people building on their branches.

**Comment by JasonGross** [comment]
Can we work around the spurious failures?  e.g., rather than (or in addition to) using the `apt` add-on, we write a script that runs `apt-get update`, and retries up to 10 times or something depending on the error code / grepping for failures?

**Comment by Zimmi48** [comment]
Once again, even if it is technically possible, it doesn't make sense to automatically bypass Travis CI. There are no benefits and significant drawbacks compared to simply removing the tests that this PR removes. Once again, I'd like to hear some more explicit concerns from @ejgallego than simply "CircleCI hasn't been tested enough" (it has IMHO).

@JasonGross 
> Can we work around the spurious failures? e.g., rather than (or in addition to) using the apt add-on, we write a script that runs apt-get update, and retries up to 10 times or something depending on the error code / grepping for failures?

Feel free to try. Personally, I spent already too much time trying to fix this.

**Comment by ejgallego** [comment]
How many developers are using Circle? Are @mattam82 , @herbelin etc.. using it? This is what I mean. I'm wary of relying only on Circle with what amounts to 1 month of testing only.

More problems not yet solved on Circle: I cannot restart jobs; folding doesn't work. Those are blockers for me. I am OK with moving the Travis jobs to allowed failure thou.

**Comment by ejgallego** [comment]
So it seems that neither @mattam82 @ppedrot @herbelin are in CircleCI . I'd say before enabling this by default let's get them in Circle and let's them do some of their usual development.

**Comment by Zimmi48** [comment]
OK so I now see your concerns and they actually correspond to mine: not that it is unsafe to use CircleCI to test PRs, but that it is going to impede developers to remove these tests from Travis. So I suggest that @maximedenes updates this PR to make these jobs conditional instead of removing them, like what is done here:
https://github.com/coq/coq/blob/9aa2464375c1515aa64df7dc910e2f324e34c82f/.travis.yml#L184

**Comment by ejgallego** [comment]
Well I meant testing in a broad sense, that includes of course getting all core devs on CircleCI and see how the system responds. We have put Travis throu a huge load, we should IMHO at least be fair and push Circle CI a bit more.

**Comment by ejgallego** [comment]
I guess we just need confirmation from @mattam82 @ppedrot @psteckler @JasonGross and @herbelin that they are in Circle CI. I assume @SkySkimmer is already there, right?

**Comment by SkySkimmer** [comment]
>I assume @SkySkimmer has already done so, right?

Yes.
I did disable email notification because it kept spamming me though.

**Comment by maximedenes** [comment]
The number of spurious failures under Travis these days is impressive, so I'd like to move forward with this. @mattam82 @ppedrot @psteckler @JasonGross can you reply to @ejgallego to make him happy? Thanks!

@herbelin already said he was busy these days, but I don't think we need all devs to switch to Circle CI immediately

**Comment by Zimmi48** [comment]
@maximedenes Just merge #6636 instead.

**Comment by psteckler** [comment]
> I guess we just need confirmation at least from @mattam82 @ppedrot @psteckler @JasonGross and @herbelin have enabled Circle CI builds for their forks.

I've just signed up for Circle CI, and added `coq` as a project.

**Comment by JasonGross** [comment]
Another alternative: #6644

**Comment by maximedenes** [comment]
Closing in favor of #6636 and #6644.

**Pull request closed without merging**
