### PR TITLE
Reuse the same dnet implementation for autorewrite and auto hints.

### PR DESCRIPTION
**Pull request by ppedrot**
Hacky hacky but the test-suite passes. Let's see what the CI gives, and then a bench.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
Reduced example:
```coq
Require Coq.Setoids.Setoid.
Export Coq.Classes.Morphisms.
Export Coq.Setoids.Setoid.

Axiom A : Type.
Axiom equiv : relation A.
Axiom sg_op : A -> A -> A.
Axiom mon_unit : A.
Axiom negate : A -> A.

#[export] Declare Instance sg_setoid : Equivalence equiv.
#[export] Declare Instance sg_op_proper : Proper (equiv ==> equiv ==> equiv) sg_op.
Axiom right_identity : forall x, equiv (sg_op x mon_unit) x.
Axiom left_inverse : forall x, equiv (sg_op (negate x) x) mon_unit.

#[global] Hint Rewrite @right_identity @left_inverse using apply _: group_cancellation.

Goal equiv mon_unit (sg_op (negate mon_unit) mon_unit).
Proof.
rewrite_strat (try bottomup (hints group_cancellation)). (* selects left_inverse in master, right_identity with this PR *)
reflexivity.
Qed.

```

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Not sure if it's noise, but some lines seem to indicate this is even slightly faster on average. Anyways, I think this is ready.

**Comment by ppedrot** [comment]
FTR, the failure above simply checks that the hints are produced in the right order. The first iteration of the PR had them reversed compared to master because I seemingly can't grasp the difference between folding order.

**Comment by SkySkimmer** [comment]
What are the FIXME about?

**Comment by ppedrot** [comment]
Oh, right, I forgot additional cleanups. Will do.

**Comment by ppedrot** [comment]
Done.

**Comment by ppedrot** [comment]
I've added the extracted test to the test suite, at least we now have an example that is sensitive to the order of introduced hints.

**Comment by ppedrot** [comment]
Any takers? @SkySkimmer ?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@ppedrot what's is going on with the Windows CI. Is it related?

**Comment by ppedrot** [comment]
@Alitzer I don't see how this would have anything to do with this PR. Looks like a transient error to me.

**Comment by Alizter** [comment]
Thank you for the cleanup :)

**Pull request merged**
