### PR TITLE
Allow interactive editing of {C,}Morphisms in PG

### PR DESCRIPTION
**Pull request by JasonGross**
See https://github.com/coq/coq/pull/386#issuecomment-298065390 and preceding comments for discussion with @Zimmi48 .

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks @JasonGross!

**Comment by Zimmi48** [comment]
This works (I just tested to be sure) but can you tell me why the `-emacs` option is not needed in the `coq-prog-args`?

**Comment by psteckler** [comment]
It looks like `-emacs` is added algorithmically, cons'ed onto `coq-prog-args`, inside of PG.

Look at `coq-coqtop-prog-args` in `coq/coq-system.el`.

**Comment by Zimmi48** [comment]
Thanks @psteckler for the explanation!
In that case, is there any reason why `-emacs` is explicitely added in a lot of test-suite files?
Here is a small excerpt of `git grep coq-prog-args test-suite/`:
```
test-suite/bugs/closed/3080.v:(* -*- coq-prog-args: ("-emacs" "-nois") -*- *)
test-suite/bugs/closed/3323.v:(* -*- coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3332.v:(* -*- coq-prog-args: ("-emacs" "-time") -*- *)
test-suite/bugs/closed/3346.v:(* -*- mode: coq; coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3348.v:(* -*- mode: coq; coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3352.v:(* -*- coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3375.v:(* -*- mode: coq; coq-prog-args: ("-emacs" "-impredicative-set") -*- *)
test-suite/bugs/closed/3393.v:(* -*- coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3427.v:(* -*- mode: coq; coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3539.v:(* -*- mode: coq; coq-prog-args: ("-emacs" "-indices-matter") -*- *)
test-suite/bugs/closed/3612.v:(* -*- mode: coq; coq-prog-args: ("-emacs" "-indices-matter" "-nois") -*- *)
test-suite/bugs/closed/3649.v:(* -*- coq-prog-args: ("-emacs" "-nois") -*- *)
test-suite/bugs/closed/3881.v:(* -*- coq-prog-args: ("-emacs" "-nois" "-R" "../theories" "Coq") -*- *)
```
Could we drop them?

**Comment by psteckler** [comment]
> Could we drop them?

I think so.

If I run one of those files (I tried 3080.v) in PG, and examine the `coqtop` command-line via `ps aux`, I see the `-emacs` flag. If I remove `-emacs` from the top-of-file comment, and run the file in PG, I still see the `-emacs` flag via `ps`.

**Comment by JasonGross** [comment]
> In that case, is there any reason why `-emacs` is explicitely added in a lot of test-suite files?

Because I was not aware that it was unneeded when I wrote those files.  Feel free to drop them.

**Comment by psteckler** [comment]
Should I create a PR that changes those files? Or maybe @Zimmi48 can just make the changes, since it doesn't need review, I'd say.

**Comment by Zimmi48** [comment]
That would be great thanks!

(PS: to answer your now modified comment, I don't have commit rights.)

**Comment by psteckler** [comment]
I amended my comment to spare myself the possible wrath of @ejgallego  :-)

**Comment by psteckler** [comment]
Should the PR be against 8.6, or trunk, do you think?

**Comment by ejgallego** [comment]
@psteckler the discussion had already been held and we had all agreed on a common strategy. But then it turns out we ignore what have discussed... I don't know you but I do value my time.

**Comment by psteckler** [comment]
@ejgallego Yes, I understand!

**Comment by psteckler** [comment]
In fact, the issue of no-commits-only-PR-merges came up in the wish list from MIT to Coq devs.

**Comment by psteckler** [comment]
#589 created (against 8.6).

**Pull request merged**
