### PR TITLE
ccnv: convert inner stack elements first.

### LINKED ISSUE #13419: Failing unification slower in 8.12.1 than in 8.11.2
#### Description of the problem

The call to `refine` in the code below takes almost no time (~5 ms incl. printing the error) to fail with Coq 8.11.2. With 8.12.1 it takes forever.

```coq
From Coq.ZArith Require Import BinIntDef.
From Coq Require Import List String.
Import BinNums.
Import ListNotations.
Import Z.
Open Scope Z_scope.

Goal forall a : Z,
  @Logic.eq Z
    ((fix get (ls : list Z) : Z :=
        match ls return Z with
        | nil => Zpos (xO (xO (xO (xO (xO (xO xH))))))
        | cons l ls0 => match testbit a l return Z with
                        | true => l
                        | false => get ls0
                        end
        end) (@map nat Z of_nat (seq O (BinPos.Pos.to_nat (xO (xO (xO (xO (xO (xO xH))))))))))
    match eqb a Z0 return Z with
    | true => sub (pow (Zpos (xO xH)) (Zpos (xO (xO (xO (xO (xO (xO xH)))))))) (Zpos xH)
    | false =>
        (fix get (ls : list Z) : Z :=
           match ls return Z with
           | nil => Zpos (xO (xO (xO (xO (xO (xO xH))))))
           | cons l ls0 => match testbit a l return Z with
                           | true => l
                           | false => get ls0
                           end
           end) (@map nat Z of_nat (seq O (BinNat.N.to_nat (Npos (xO (xO (xO (xO (xO (xO xH))))))))))
    end

.
  intros.
  Time Fail refine (@Logic.eq_refl _ _).
```

#### Coq Version
8.12.1

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13419

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Bench waiting https://gitlab.com/coq/coq/-/jobs/861521154

**Comment by ppedrot** [comment]
> coq-unimath │ 17423.57 3946.32 +341.51 %

Noice.

**Comment by gares** [comment]
from https://github.com/coq/coq/issues/13419#issuecomment-731094306 my take is that this is not the right fix for that class of bugs. (Improving conversion is OK, but not to deal with doomed cases).

**Comment by ppedrot** [comment]
I agree with @gares stance, by the way. Hacking the conversion is fine for gains on average, but trying to be clever on a single example should be avoided at all costs.

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬────────────────────────────┬───────────────────────────────────────────────┬───────────────────────────────────────────────┬───────────────────────────────┬───────────────────┐
│                             │       user time [s]        │                  CPU cycles                   │               CPU instructions                │     max resident mem [KB]     │    mem faults     │
│                             │                            │                                               │                                               │                               │                   │
│                package_name │      NEW     OLD   PDIFF   │               NEW               OLD   PDIFF   │               NEW               OLD   PDIFF   │        NEW        OLD PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │   136.48  140.56   -2.90 % │      380141395979      390774768916   -2.72 % │      485543685178      500669265005   -3.02 % │     544288     545024 -0.14 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-flocq │   155.87  156.61   -0.47 % │      433735301377      435397086409   -0.38 % │      540995015597      541313016885   -0.06 % │     821188     821284 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-bignums │    56.97   57.17   -0.35 % │      157171641065      157284971371   -0.07 % │      211188497746      210957198836   +0.11 % │     476536     481216 -0.97 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-coquelicot │    68.10   68.28   -0.26 % │      186662757953      185987075464   +0.36 % │      238168599579      235946510178   +0.94 % │     565596     566592 -0.18 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │   789.37  790.46   -0.14 % │     2198152369670     2200404296035   -0.10 % │     3417040493389     3417042205247   -0.00 % │     985948     980748 +0.53 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-rewriter │   719.47  720.18   -0.10 % │     1997451912238     1998052497543   -0.03 % │     3050883423153     3049078411232   +0.06 % │     986452     986284 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-math-classes │   213.52  213.73   -0.10 % │      595236174922      595670692537   -0.07 % │      812163748929      812094600247   +0.01 % │     522140     522108 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fiat-core │   101.53  101.60   -0.07 % │      291058301951      291576858870   -0.18 % │      386380447438      386006775689   +0.10 % │     479340     480060 -0.15 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-compcert │   642.59  642.97   -0.06 % │     1792336961775     1789305220849   +0.17 % │     2470219191780     2469310137796   +0.04 % │    1046800    1046792 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │   365.73  365.93   -0.05 % │     1028167008789     1030057856849   -0.18 % │     1745773626430     1746396079717   -0.04 % │    3502360    3502356 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │   155.58  155.66   -0.05 % │      432648112514      432701451934   -0.01 % │      600143057293      599638450158   +0.08 % │     708864     711756 -0.41 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-coqprime │    79.60   79.59   +0.01 % │      218059969503      219024979086   -0.44 % │      304760742480      306573042049   -0.59 % │     761800     764100 -0.30 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-lambda-rust │  1245.34 1244.61   +0.06 % │     3467010088132     3465778851174   +0.04 % │     4941512638491     4935860373211   +0.11 % │    1117896    1102060 +1.44 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-color │   514.07  513.57   +0.10 % │     1433659682626     1433600637766   +0.00 % │     1797908859477     1797737366917   +0.01 % │    1132700    1132664 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-bedrock2 │   224.01  223.74   +0.12 % │      620470371645      619988611642   +0.08 % │     1023393427774     1023010524511   +0.04 % │    1085736    1085912 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                         coq │   522.44  521.68   +0.15 % │     1463870800313     1460774810067   +0.21 % │     1950593142701     1953985558189   -0.17 % │     578760     578636 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-verdi-raft │  1231.31 1229.47   +0.15 % │     3426815060955     3422073075115   +0.14 % │     4843075331709     4836187923937   +0.14 % │     899876     899976 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │   636.92  635.66   +0.20 % │     1784432216768     1776358454840   +0.45 % │     2687992601135     2668574173351   +0.73 % │    3642276    3604216 +1.06 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-verdi │   103.02  102.64   +0.37 % │      283217820642      283084100260   +0.05 % │      396969316969      396652442255   +0.08 % │     548500     549164 -0.12 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │  5096.38 5071.53   +0.49 % │    14157595670469    14093219586395   +0.46 % │    24405861629753    24272727983063   +0.55 % │    2274344    2268220 +0.27 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-coqutil │    60.86   60.54   +0.53 % │      169468516451      168623322581   +0.50 % │      208603284603      208342383315   +0.13 % │     524436     524488 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │  1060.17 1053.16   +0.67 % │     2953683122876     2933590235304   +0.68 % │     4673693979790     4645824297563   +0.60 % │     974792     974268 +0.05 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fourcolor │  2572.42 2552.01   +0.80 % │     7171833567647     7103474160124   +0.96 % │    11934101249132    11797627767806   +1.16 % │     722516     722516 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │    47.67   47.29   +0.80 % │      131801331767      131694081845   +0.08 % │      181152131071      181442711602   -0.16 % │     477364     479764 -0.50 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │    51.20   50.79   +0.81 % │      139017592582      138616324892   +0.29 % │      175530424676      175381151671   +0.09 % │     512860     513816 -0.19 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-corn │  1637.46 1624.30   +0.81 % │     4554386585214     4529364100035   +0.55 % │     6962014653983     6937326271474   +0.36 % │     864492     841116 +2.78 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │   171.88  170.19   +0.99 % │      477972508699      473365724325   +0.97 % │      672768834706      668252183298   +0.68 % │     682864     682832 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │   228.67  223.73   +2.21 % │      636830723069      622905134255   +2.24 % │      968695781815      945596263884   +2.44 % │     676660     673000 +0.54 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-geocoq │  1562.82 1455.44   +7.38 % │     4354028887140     4054557410419   +7.39 % │     6690588822071     6136971347534   +9.02 % │    1013908    1023848 -0.97 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-hott │   541.98  323.22  +67.68 % │     1487485346731      877313984937  +69.55 % │     2596710937972     1418977886466  +83.00 % │     728592     664988 +9.56 % │    0    0  +nan % │
├─────────────────────────────┼────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-unimath │ 17423.57 3946.32 +341.51 % │    48480290835332    10982744328823 +341.42 % │    88538787944318    20981668856459 +321.98 % │    1142364    1142328 +0.00 % │    0    0  +nan % │
└─────────────────────────────┴────────────────────────────┴───────────────────────────────────────────────┴───────────────────────────────────────────────┴───────────────────────────────┴───────────────────┘
INFO: failed to install coq-performance-tests-lite
coq-sf-plf
~~~

**Comment by herbelin** [comment]
An alternative patch could be to look at `match` starting from inside (which is what we would de facto do if we had commutative cuts), but to keep the comparison of arguments in the same order.

Also, it would be interesting to extract the UniMath and HoTT example(s) that fail. By classifying the typical patterns that raise problems, maybe will we find one day a general rule that discriminates them.

**Comment by SkySkimmer** [comment]
Looks like basically the entire slowdown on hott is on https://github.com/HoTT/HoTT/blob/756ff79da22d0804194145db775865c11c14aa48/theories/Homotopy/BlakersMassey.v#L487
1 line going from 0s to 220s (3min and 40s)

Unimath slowdown is on https://github.com/UniMath/UniMath/blob/c81731f19d00fb3676cda7fff24a9150a7793fdc/UniMath/RealNumbers/NonnegativeReals.v#L2098
also 1 line going from 0s to 13.5ks (3h and 45min)

There are some small speedups but nothing really worth noticing.

**Pull request closed without merging**
