### PR TITLE
add perennial to benchmark suite

### LINKED ISSUE #13221: Add perennial to Coq benchmarks
#### Description of the problem

In https://github.com/coq/coq/pull/12914, @ppedrot asked if there were other representative Iris-based benchmarks we could add besides lambda-rust. @tchajed then suggested Perennial, which I would not call representative, but it is certainly stress-testing Iris and has lots of slow proofs, so is probably a reasonable performance test. However, it is quite slow to build, taking more than 1h.

Would the Coq team be okay with adding Perennial to its benchmarks, and what would that take?

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/coq/coq/issues/13221
Cc @ppedrot 

I am not entirely sure how to test this though...

### CODE REVIEW

**Comment by SkySkimmer** [comment]
You need to rebase as you based your commit on the right day to have a broken bench system (https://github.com/coq/coq/pull/13243)
Then we can test

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I have launched a bench with just perennial: https://gitlab.com/coq/coq/-/jobs/857412392. That should be sufficient given the dependencies of the perennial opam package.

**Comment by RalfJung** [comment]
@tchajed should this use the "lite" target? In that case we should change the `opam` file in the perennial repo.

**Comment by ppedrot** [comment]
The bench failed with "Package coq-perennial does not exist". How is the package chosen?

**Comment by RalfJung** [comment]
The package should exist due to
```
opam pin add -nq coq-perennial.dev git+https://github.com/mit-pdos/perennial#coq/tested
```
Locally, after I run this command, I can do `opam install coq-perennial`. What exact opam command is the bench running?

**Comment by ppedrot** [comment]
On my machine, the pin command ask
```
Package coq-perennial does not exist, create as a NEW package? [Y/n] 
```
which is answered no on the bench.

**Comment by ppedrot** [comment]
I imagine the command should read `opam pin add -ynq ...`.

**Comment by RalfJung** [comment]
Ah, good point!

**Comment by RalfJung** [comment]
Rebased, and fixed that.

**Comment by ppedrot** [comment]
Let's try again https://gitlab.com/coq/coq/-/jobs/863341739.

**Comment by ppedrot** [comment]
Bench happy, let's merge.

**Pull request merged**
