### PR TITLE
Deduplicate some names in .mailmap

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by silene** [comment]
You got it wrong: the proper email address is supposed to be on the left.

**Comment by silene** [comment]
Also, please respect the alphabetical ordering, so that we can spot at a glance the various addresses of a user.

**Comment by JasonGross** [comment]
Oops, thanks!  Should be fixed now. 

(I saw they weren't sorted by first name, and didn't think to check sorting by last name.)

**Comment by maximedenes** [comment]
Cherry-picked to v8.5 branch. Thanks!

**Pull request closed without merging**
