### PR TITLE
Document the signing procedure of released binary packages.

### PR DESCRIPTION
**Pull request by ppedrot**
/cc @maximedenes, in particular regarding the MacOS whereabouts.

### CODE REVIEW

**Comment by ppedrot** [comment]
@maximedenes shouldn't we merge this even if we somehow forgot how to sign the MacOS package?

**Comment by Zimmi48** [comment]
So is the conclusion that we forgot how to sign the macOS package? When is 8.11.1 going to be announced? With or without a signed macOS package it seems like it should.

**Comment by ppedrot** [comment]
OK, this is unrelated to the PR at hand but I'll try to upload the unsigned MacOS package. Hopefully it has not been garbage collected on the CI, otherwise I'll have to randomly push branches on the github repo again.

**Comment by maximedenes** [comment]
We didn't forget how to sign the packages. I lost access to the VM that has the certificate. I believe the last releases were signed by @vbgl (not 100% sure), maybe he knows more.

Note that we never had an officially approved and stable process for macOS signing (unlike for Windows).

**Comment by Zimmi48** [comment]
> I'll have to randomly push branches on the github repo again.

You can also directly push a branch on the GitLab repository, or even manually trigger a build there.

**Comment by ppedrot** [comment]
@Zimmi48 the problem is that the MacOS packages are generated by Azure, not gitlab. I still have no way to get in there, it rejects all of my e-mail addresses as being already used but is otherwise refusing to send me password resets, conversely claiming that the addresses don't exist. Anyways, luckily the package was still live so I didn't have to do that.

**Comment by vbgl** [comment]
I do have access to the certificate. So does Maxime.

I can try to sign 8.11.1 if requested. I can take notes of what I do to also resolve this issue (basically there is a shell script next to the certificate on the file-system of the VM).

**Comment by vbgl** [comment]
I’ve written a wiki page: https://github.com/coq/coq/wiki/SigningReleases

I’m updating the release page with a dmg holding the signed CoqIDE_8.11.1.app

FTR, Coq-8.11.0 has been signed by Maxime on January 27th., 2020.

**Comment by maximedenes** [comment]
> I do have access to the certificate. So does Maxime.

As I wrote above, I failed to access the VM when I tried (the password was rejected). Maybe it was a transient issue, though.

**Comment by Zimmi48** [comment]
@ppedrot sounds like the PR should be updated to refer to this document

**Comment by ppedrot** [comment]
@Zimmi48 done

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
@maximedenes is assigned, so letting him take care of merging the PR.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
