### PR TITLE
[changes] Rectify changelog w.r.t. configure fixes.

### PR DESCRIPTION
**Pull request by ejgallego**
Thanks to Théo Zimmerman for all the attention dedicated to this
issue.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Did you mean "rectify"?

**Comment by Zimmi48** [comment]
IINM, for this PR, there was also a `dev/doc/changes.md` entry that needs to be moved to.

**Comment by Zimmi48** [comment]
> IINM, for this PR, there was also a `dev/doc/changes.md` entry that needs to be moved to.

Actually, it was not for this PR but for #14059 (still it was inserted in the wrong place).

**Comment by ejgallego** [comment]
> Did you mean "rectify"?

Yes, sorry, I am a bit dyslexic sometimes.

> Actually, it was not for this PR but for #14059 (still it was inserted in the wrong place).

I see, thanks again; let's see now.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
