### PR TITLE
Fix test suite after parallel merge of #15301 and #15307

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
`kind:race` ?

**Comment by ppedrot** [comment]
@ejgallego you should probably merge already, the test-suite jobs have passed and there is no point in letting other PRs fail anymore.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
