### PR TITLE
CoqIDE: no button shadow (is too slow) #12779

### PR DESCRIPTION
**Pull request by btj**
Significantly improves the GUI sluggishness reported in #12779 .

Note: uses new bindings introduced in lablgtk 3.1.2 (released 2021-12-24).

### CODE REVIEW

**Comment by btj** [comment]
Note that these button shadows are not even actually visible, so this PR has no visible effect, other than dramatically improving the frame rate.

**Comment by ppedrot** [comment]
This needs a bump of the lablgtk dependency in the various places where it's needed. First and foremost, the CI is failing because the Coq docker image uses an older release. @btj this should be performed in another PR, but I don't know the intricacies of version bumping enough to tell you all the places we need this. Probably opam files, dune files, docker build files and a few more?

**Comment by btj** [comment]
I guess the first thing is for @garrigue to create an opam package for lablgtk 3.1.2.

**Comment by garrigue** [comment]
Already in pipeline:
https://github.com/ocaml/opam-repository/pull/20311

**Comment by Zimmi48** [comment]
When the new version is available through opam, you will need to update the version of the package in `dev/ci/docker/bionic_coq/Dockerfile` and update the value of `CACHEKEY` in `.gitlab-ci.yml`. The version used in the macOS job is not pinned, so the job should fix itself when it is re-run and the new version is available. IINM, the Windows failure is unrelated.

**Comment by Zimmi48** [comment]
Could it make sense to have this fix be dependent on the version of lablgtk used, so that it can be shipped in 8.15.0 without requiring a bump in the minimal supported version of OCaml and lablgtk?

**Comment by btj** [comment]
I'm not sure what you are suggesting; this fix makes essential use of new bindings introduced in lablgtk 3.1.2. (An alternative fix for bug #12779, however, would be to ship the modified Adwaita theme (`Adwaita_no_button_shadows`) with CoqIDE; that would require no new lablgtk bindings. However, I haven't gotten around to figuring out exactly how to do that, yet.)

**Comment by Zimmi48** [comment]
We have some version detection mechanism in configure, see:
https://github.com/coq/coq/blob/8d7a42c9a92c41d25a82f0fee1a2b2c517bea3e5/tools/configure/coqide.ml#L26-L34

We could refine it to detect whether we have a sufficiently high lablgtk version to apply this fix, and apply the fix conditionally (though that might not be doable without a preprocessor).

Another solution would be to only ship this fix in Coq 8.16 (as planned by @SkySkimmer given the milestone he added to #15402) but to also apply it as a patch in the opam archive, depending on the version of lablgtk that is used (providing that opam does support conditional patching).

**Comment by SkySkimmer** [comment]
Is it impossible to make lablgtk compatible with older ocaml?

**Comment by garrigue** [comment]
It should be possible to make lablgtk3 compatible with ocaml 4.06. This just requires to make d'une configurator detect the version as the code for this is already in the lablgtk2 (master) branch.

**Comment by SkySkimmer** [comment]
@garrigue what about 4.05?

**Comment by garrigue** [comment]
There is a compatibility problem with the C headers shipped with 4.05 which led me to drop support for it.
Some header is using an `Assert` macro in place of `CAMLassert`, without defining it.

**Comment by Zimmi48** [comment]
If this is 8.16 material anyway, it would be fine to decide to bump the minimal OCaml version to 4.06 (we've even talked about 4.07 in the past). Bumping to 4.08 or beyond is dependent on #15220.

**Comment by SkySkimmer** [comment]
So what do we do about this?

**Comment by Zimmi48** [comment]
The lablgtk version was bumped in #15947, so this should now be possible to merge this PR (after a rebase). Since #15947 forgot to include a changelog entry about the lablgtk bump, an option would be to add one to this PR (unless someone opens a separate PR for this).

**Comment by MSoegtropIMC** [comment]
I guess this needs to be changed: https://github.com/coq/platform/blob/1af4a9d6fac8f681e0172855fad8805c9877e47a/package_picks/package-pick-8.15%7E2022.04.sh#L58 then?

**Comment by Zimmi48** [comment]
@MSoegtropIMC, the lablgtk version was bumped to 3.1.2. So, no, this does not need to change.

**Review by ppedrot — APPROVED** [review]

**Comment by proux01** [comment]
Looks like the windows failure in CI was real https://github.com/coq/coq/runs/6211150026?check_suite_focus=true and was overlooked.

**Comment by Zimmi48** [comment]
For this kind of PRs, it's a bit unfortunate that CI failures are overlooked. Note that just updating the pin of the Platform (e.g., to the latest Platform tag) should be sufficient to fix the problem.

**Comment by MSoegtropIMC** [comment]
Indeed the previous (2022.01) release of Coq Platform had an older version of lablgtk, which as far as I understand is not compatible with recent Coq.

**Pull request merged**
