### PR TITLE
Functional pretyping interface

### PR DESCRIPTION
**Pull request by maximedenes**
This is an attempt at cleaning up the interfaces of the pretyper.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by herbelin** [comment]
I strongly approve the initiative, `pretyping` being one of the module of which the API is the most difficult to understand in my opinion.

Actually, even if I'm responsible for the name, I'm not fond of the `understand` name. But maybe this is a minor point and if it is not shoking for others, we might keep it.

Then, about passing the evar_map explicitly or by side-effect, I have no absolute opinion, but I have a relative one. There is already a common convention which is to use the `e_` prefix for such variants. So, if the plan is not to remove all existing `e_` variants, it would be acceptable (and consistant) to simply rename `understand_tcc_evars` into `e_understand_tcc`.

The rest is ok and I would lean towards going further, trying to merge `understand`, `understand_tcc`, and `understand_ltac` thanks to a system of optional arguments, if e.g. this meets similar feelings from @mattam82 and @ppedrot. (But I also remember that I tried at some time and that there were some issues.)

**Comment by maximedenes** [comment]
> if the plan is not to remove all existing e_ variants

Indeed, I had assumed it was the plan, to remove all functions doing side effects on the evar map. I thought it was a step towards having the pretyper in the monad. @ppedrot did I interpret correctly?

**Comment by ppedrot** [comment]
@maximedenes Indeed, we want to get rid of ref-based state.

**Comment by herbelin** [comment]
I don't care on having these `e_` versions or not (I think they were introduced by Chet and we just continued to use them). But I don't see how to motivate the change in another way than by some form of cosmetic uniformity.

From a technical point of view, I don't see why the `e_` functions would be bad in themselves. It is not about a global state, it is just about the way of passing arguments and both styles are isomorphic as far as I can judge.

**Comment by ppedrot** [comment]
@herbelin They're isomorphic as long as you only have state-passing. As soon as we have something more involved (e.g. being in the tactic monad) then we're going to suffer. Also, it's easy to mess up with other first-class effects (e.g. setting an evar-map that ought to be backtracked).

**Comment by herbelin** [comment]
OK, trusting you.

**Pull request merged**
