### PR TITLE
Clean up Clenv API

### PR DESCRIPTION
**Pull request by ppedrot**
This PR introduces various cleanups of the Clenv API, including:
- inlining of functions used only once
- exposing static knowledge through typing
- reduction of attack surface

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1324044303

**Comment by ppedrot** [comment]
Rerunning a bench on the noisy coqprime to check whether the slowdown was real: https://gitlab.com/coq/coq/-/jobs/1381540510.

**Comment by SkySkimmer** [comment]
~~~
┌──────────────┬───────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬───────────────────────┬─────────────────┐
│              │     user time [s]     │             CPU cycles              │          CPU instructions           │ max resident mem [KB] │   mem faults    │
│              │                       │                                     │                                     │                       │                 │
│ package_name │    NEW     OLD  PDIFF │           NEW            OLD  PDIFF │           NEW            OLD  PDIFF │    NEW     OLD  PDIFF │ NEW  OLD  PDIFF │
├──────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│ coq-coqprime │ 326.87  347.48  -5.93 │  908943690362   965668933675  -5.87 │ 1587529395017  1588128764554  -0.04 │ 905412  937516  -3.42 │   0    0    nan │
│   coq-stdlib │ 413.02  413.62  -0.15 │ 1155595286279  1157648317479  -0.18 │ 1473283284831  1474456469526  -0.08 │ 598024  595900   0.36 │   0    0    nan │
│     coq-core │ 107.75  107.31   0.41 │  297096260950   295851577573   0.42 │  458628879047   458390423206   0.05 │ 320816  320908  -0.03 │   0    0    nan │
└──────────────┴───────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────┘
~~~

**Comment by ppedrot** [comment]
Either coqprime is *very* noisy or this PR does weird stuff.

**Comment by ppedrot** [comment]
This needs an assignee.

**Comment by herbelin** [comment]
coqprime manipulates very large integers so is probably pretty sensitive to cache/memory issues (???).

Let me assign since I'm currently around.

**Review by herbelin — APPROVED** [review]
Looks globally good. Trusting the details.

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
