### PR TITLE
Use evar handler when renaming arguments in retyping

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
This goes against the standard design of the API for upper layers. It should take an evarmap instead.

**Comment by SkySkimmer** [comment]
changed

**Comment by SkySkimmer** [comment]
Push as I just found out that Typing already had its own wrapper around check_hyps_inclusion so we should share them

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
