### PR TITLE
Nicer printing for decimal constants

### PR DESCRIPTION
**Pull request by proux01**
Nicer printing for decimal constants in R and Q
    
Print 1.5 as 1.5 and not 15e-1.
    
We choose the shortest representation with tie break to the dot notation (0.01 rather than 1e-3).
    
The printing remains injective, i.e. 12/10 is not mixed with 120/100, the first being printed as 1.2 and the last as 1.20.

This follows a suggestion from @herbelin in #11703 

~Depends on: #11703~

If #8743 goes first, i'd be happy to rebase over it.

- [x] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Thanks! Looks very good.

Do you plan to move the code that heuristically choose between `1.23` and `123e-2` in `NumTok`? (It is a pity that this code has to be duplicated on the OCaml and the Coq side by the way.)

> The printing remains injective, i.e. 12/10 is not mixed with 120/100, the first being printed as 1.2 and the last as 1.20.

Cool!

**Comment by herbelin** [comment]
I guess I'm the canonical assignee (for when #11703 will be merged). @proux01: note that I now fixed QuickChick in #11703.

**Comment by proux01** [comment]
> Do you plan to move the code that heuristically choose between `1.23` and `123e-2` in `NumTok`? (It is a pity that this code has to be duplicated on the OCaml and the Coq side by the way.)

I indeed thought about that. My (not very strong) opinion refraining me from doing so is that Reals is the only remaining numeral notation implemented in OCaml (along with the special cases of primitive integers and floats). So if one day its implementation switches to Coq, this OCaml code will just disappear.

**Comment by proux01** [comment]
Rebased, CI green

**Comment by herbelin** [comment]
OK, giving a day for further comments if any before merging.

**Pull request merged**
