### PR TITLE
tify tactic generalises zify

### PR DESCRIPTION
**Pull request by fajb**
Make sure that the zify infrastructure can be used for injecting other types e.g. R

Implement a rify, similar to zify,  that is called by lra, nra.

**Kind:**  bug fix / feature 

- [ ] Corresponding documentation was added /

### CODE REVIEW

**Comment by fajb** [comment]
@thery Could you have a look a `Rify_power.v`? I suspect the proofs could be streamlined and maybe moved in a more relevant place.

**Comment by Zimmi48** [comment]
Given that these new commands had been introduced in #9856, which has not been released yet, it is fine to modify them if this PR goes in 8.11 as well, so I'm adding the milestone. If this PR is not merged in time for 8.11, something more will have to be done.

**Comment by Zimmi48** [comment]
@fajb Since this PR has been retargeted to 8.12, you cannot just rename the `Zify` commands into `Tify`. You will need to deprecate the old commands and introduce new ones. Another solution would be to open a PR doing only the renaming and request that this PR be included in 8.11.

**Comment by ejgallego** [comment]
Hi @fajb this was mentioned recently on Gitter, what's the status?

**Comment by fajb** [comment]
I do not have the time right now and, since then, the zify code has evolved quite a bit.
Could you tell me about the use-case? And the timeline of 8.12?

**Comment by ejgallego** [comment]
> I do not have the time right now and, since then, the zify code has evolved quite a bit.
> Could you tell me about the use-case? And the timeline of 8.12?

The context is [this thread](https://gitter.im/coq/coq?at=5e6a027dd17593652b7b7f57)

> Q: I wonder what the status of proving trivial integer arithmetic goals with bool relational operators with lia is.
>
> A: on 8.11 or master, you need this (choose branch): https://github.com/pi8027/mczify
>
> Q: Ah ok, thanks! It is just one file - do you think it would be worthwhile to create an opam package so that people find it easily?
>
> A: author is waiting for coq/coq#10982 to be merged before making a package, etc.

Freeze for 8.12 should happen in a couple of months (more or less)

cc: @pi8027

**Comment by fajb** [comment]
So the issue is with ssreflect, right.
For that, I really hope the current zify 8.11 is up to the task -- with the support implemented by @pi8027.
The tify think was meant to target other types e.g. R (Z -> R ; Q -> R etc)

**Comment by pi8027** [comment]
My point is that, if a change on the interface (type classes) of zify is expected soon, the mczify library is considered to be experimental. When that interface become stable enough, I would like to migrate mczify to the MathComp organization and make a release. (Since I am typing from my phone now, I will write more tomorrow.)

**Comment by Zimmi48** [comment]
Dear PR author(s) and contributors, it seems to us this PR may need additional work beyond the 8.12 branching deadline on May 15th.

We are thus removing the 8.12+beta1 milestone; please retarget as appropriate, and also consider updating labels to reflect current status, moving the PR to draft status, etc.

We apologize in advance if we misunderstood the PR status.

**Comment by pi8027** [comment]
Sorry for the delayed response. My previous response seems wrong -- this PR does not change any type class in `ZifyClasses.v`. Also, MathComp has its own rational numbers and this feature would be really helpful to reason about them.

**Review by jfehrle — CHANGES_REQUESTED** [review]
This code removes several `Show Zify ...` commands.  Generally we deprecate commands and tactics for at least one release before removing them.  Also, your proposed documentation changes are for an out of date version of `micromega.rst`--you'll need to fix that after rebasing.

**Comment by fajb** [comment]
This PR is in limbo. I'll close it for now.
As there seems to be some interest, I'll try to re-start from scratch.

**Pull request closed without merging**
