### PR TITLE
[ci] Remove CircleCI setup.

### PR DESCRIPTION
**Pull request by ejgallego**
GitLab setup is quite stable these days thanks to the work of many
people and `coqbot`. We decided to keep CircleCI support for a while
as a safeguard in case something happened in the migration to GitLab,
but these days we are just wasting resources to them and to us. As I'm
afraid CircleCI won't scale for us, the time to remove it has arrived.

Still, CircleCI had some awesome functionality that GitLab's CI
doesn't offer yet, see the links at:

https://github.com/coq/coq/issues/6919#issuecomment-395885573

- https://gitlab.com/gitlab-org/gitlab-ce/issues/29347
- https://gitlab.com/gitlab-org/gitlab-ce/issues/35222
- https://gitlab.com/gitlab-org/gitlab-ce/issues/41947
- https://gitlab.com/gitlab-org/gitlab-ce/issues/47063

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
I've just disabled CircleCI manually to avoid seeing more:
>**ci/circleci** — No test commands were found

in the future

**Review by SkySkimmer — APPROVED** [review]
I can either merge today or someone else will need to do it.

**Comment by Zimmi48** [comment]
@SkySkimmer You don't need to wait for the other code owners to merge this.

BTW, even if not much was still running on Circle, here is what they had to say about us:
>Your current usage represents 1405% of your coq Linux plan's limit.

**Comment by SkySkimmer** [comment]
>@SkySkimmer You don't need to wait for the other code owners to merge this.

OK, @ejgallego was the main reason we kept circle after all

**Pull request merged**
