### PR TITLE
Bench: use -j 2

### PR DESCRIPTION
**Pull request by SkySkimmer**
IIRC we tried -j $number_of_processors but it was too unstable. However I don't think we tried -j 2, there's a chance it's reasonably stable.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Also apparently stdlib has been running -j12 since who knows when (cf wraplog.txt which says `dune build -p coq-stdlib -j 12`)

**Comment by ejgallego** [comment]
If that's the case it is due to opam passing `-j 12` to dune, right? So I'd expect other developments to be affected too? Or is the stdlib package handled in some special path?

Last time I tried other than -j 1 I got unusable data, but let's see.

**Comment by SkySkimmer** [comment]
630min instead of eg 1000min (https://gitlab.inria.fr/coq/coq/-/jobs/3544318)
(more recent benches had failing jobs so were quicker)

**Comment by SkySkimmer** [comment]
Doesn't look less stable than usual IMO

**Comment by ppedrot** [comment]
FTR I think it's a bad idea to do this...

**Comment by SkySkimmer** [comment]
ok then

**Pull request closed without merging**
