### PR TITLE
Remove ppedrot/ltac2 from CI after integration in main repo

### PR DESCRIPTION
**Pull request by SkySkimmer**
Do we still build ltac2?
I think this breaks the windows addon stuff, not sure how it works.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Indeed, it would have to be removed from the Windows scripts as well.
The current setup does build Ltac2 as part of the main build.
Hopefully, this will later be refined in a series of smaller packages.

**Comment by ppedrot** [comment]
Should be merged quickly, otherwise writing dummy Ltac2 overlays for the CI is going to be a pain.

**Comment by ppedrot** [comment]
@Zimmi48 are you assigning this PR to yourself?

**Comment by Zimmi48** [comment]
@ppedrot I'll help move this PR forward by removing ltac2 from the Windows add-on stuff, but them someone else should be the assignee.

**Comment by Zimmi48** [comment]
Done.

**Comment by ppedrot** [comment]
@ejgallego do you want to assign instead? We're already hitting the problem I described above in PR #10052.

**Comment by Zimmi48** [comment]
If @ejgallego is not available, @MSoegtropIMC and @maximedenes know enough about the CI infrastructure to self-assign too.

**Comment by MSoegtropIMC** [comment]
Since this is also about the Windows stuff, I guess I best take care of this. In a usual Windows CI build on master, the plugins are not build, this is only done on release branches. Still there is an option to build everything, which needs to be adjusted.

Just to make sure I understand this right: Ltac2 is now longer a plugin but part of basic Coq, so it needs to be removed as separate component from CI?

**Comment by maximedenes** [comment]
> Just to make sure I understand this right: Ltac2 is now longer a plugin but part of basic Coq, so it needs to be removed as separate component from CI?

It is still a plugin, but has been integrated in Coq's repo. See #10002.

**Comment by Zimmi48** [comment]
In particular, it is built and installed as part of the main make and dune targets.

**Comment by MSoegtropIMC** [comment]
Ok, so it is technically a plugin and "product wise" part of basic Coq. I will add the change to this PR a bit later today.

**Comment by Zimmi48** [comment]
> I will add the change to this PR a bit later today.

What change?

**Comment by MSoegtropIMC** [comment]
> What change?

Ok, I was thinking we are discussing to remove ltac-2 from <https://github.com/coq/coq/blob/master/dev/ci/gitlab.bat>

I didn't realize it is already done here. So your request was just about review and merge?

**Review by MSoegtropIMC — APPROVED** [review]
Changes are fine and complete (ltac-2 is not build on appveyor or azure, so nothing to be changed there).

**Pull request merged**
