### PR TITLE
Support for updating orderedGrammar with Dune.

### PR DESCRIPTION
**Pull request by Zimmi48**
This PR adds an `orderedGrammar.new` target that can be used to update `orderedGrammar` and the `rst` files at the price of some manual action (`mv doc/tools/docgram/orderedGrammar.new doc/tools/docgram/orderedGrammar` and `cp -r _build/default/doc/sphinx doc/`). I also considered promoting a directory `doc` in `doc/tools/docgram` that would need to be moved with `mv doc/tools/docgram/doc .` but Dune does not support promoting directories (more precisely, it segfaults, similarly to what happens when trying to install directory targets).

Unfortunately, we need to repeat dependencies because doc_grammar excepts the mlg and rst files on the command line.

Anyway, this is not perfect but this is useful to avoid me switching back to `make`.

cc @jfehrle

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM

**Comment by jfehrle** [comment]
You don't want to (or can't) copy the updated rst files?  The concept sounds fine though I don't know Dune well.

> Unfortunately, we need to repeat dependencies because doc_grammar excepts the mlg and rst files on the command line.

We could consider changing that at some point.  At the time it seemed like the right thing to do rather than hardcoding the list in the source.  At this point, it's almost always "make doc_gram_rsts".

**Comment by Zimmi48** [comment]
> You don't want to (or can't) copy the updated rst files? The concept sounds fine though I don't know Dune well.

Unfortunately not as part of the Dune build process as this create a dependency cycle between the target and the dependency, which is something that Dune rejects.

>We could consider changing that at some point. At the time it seemed like the right thing to do rather than hardcoding the list in the source. At this point, it's almost always "make doc_gram_rsts".

Yes, I didn't want to do a fix that was risking to be invasive to your work right now, but longer term it be could to implement some changes to doc_grammar to simplify the process.

**Comment by ejgallego** [comment]
> Unfortunately not as part of the Dune build process as this create a dependency cycle between the target and the dependency, which is something that Dune rejects.

Why don't you produce a `.new` files and then diff them?

**Comment by Zimmi48** [comment]
I do produce a `.new` file in the case of `orderedGrammar` but this is the same reason: diffing creates an implicit target and Dune rejects that.

**Comment by ejgallego** [comment]
Ummm, you are right Dune rule language cannot support this case as it is indeed a fixpoint [i.e. traced diagram] Maybe it would be worth opening a Dune issue [tho I'm not optimistic about the solution?]

What'd be the plan for this tool otherwise?

**Comment by jfehrle** [comment]
What if you copy the file in a way that Dune is unaware you're copying it?

**Comment by Zimmi48** [comment]
> What'd be the plan for this tool otherwise?

> What if you copy the file in a way that Dune is unaware you're copying it?

The plan to me looks like we will still need to wrap this into a small Makefile or a shell script doing the final copying. Note that this is not such a big deal as this is a developer-only target that is used to update the committed sources.

**Comment by Zimmi48** [comment]
I'll open a Dune issue anyway, and some about the segfaults related to directory targets too.

**Comment by Zimmi48** [comment]
Cf. ocaml/dune#3303 for the segfault issues.

**Comment by Zimmi48** [comment]
Actually I was wrong. `diff?` is precisely meant for what we need.

**Comment by Zimmi48** [comment]
Updated. Cf. the new commit message:

```
 New target check-gram to check if fullGrammar and orderedGrammar are up-to-date.

Use `dune build @check-gram --auto-promote` to automatically update
these two files.  You will need to run it twice if the two files need
to be updated (which is the case most often) as Dune will stop after
the first diff failure.

The rst files are also updated but left in the `_build/` directory as
Dune wouldn't support targets outside the current directory.  You can
just `mv _build/default/doc/sphinx doc` to update them after running
the @check-gram target.
```

The reason why it was not working before is because I was using Dune's `copy` rule, which made it smartly understand that there were more dependencies / targets than what was declared. The current solution uses bash instead to avoid this. Longer-term the solution will be to fix `doc_grammar`.

**Comment by jfehrle** [comment]
> Longer-term the solution will be to fix `doc_grammar`.

Such as a doc_grammar option to do the necessary the file copying?

**Comment by Zimmi48** [comment]
>Such as a doc_grammar option to do the necessary the file copying?

The copy `.old` / `.new` dance is a work around what `doc_grammar` does. Ideally, `doc_grammar` should support outputting to `fullGrammar.new` and `orderedGrammar.new` and leaving `fullGrammar` and `orderedGrammar` unchanged. This would make it possible to remove the `bash` commands from the build script. But there's no rush.

**Comment by jfehrle** [comment]
> Ideally, `doc_grammar` should support outputting to `fullGrammar.new` and `orderedGrammar.new` and leaving `fullGrammar` and `orderedGrammar` unchanged.

As an option?  For developers doing a bunch of edits on the grammar, you really want to update these files directly so the updates can be checked in.  It's simple to add such an option.  But we don't have to resolve this right now.

**Comment by Zimmi48** [comment]
I think you are misunderstanding. The goal is indeed to update these files. It's just that it is Dune that takes care of it after `doc_grammar` generates a `.new` file. Anyway, as long as `Makefile.doc` exists, this has to be a separate option of course.

**Comment by jfehrle** [comment]
Is this what you need?

- doc_grammar command line option that leaves the 2 files unchanged but creates *.new versions
- same thing for the rsts, or not?

**Comment by ejgallego** [comment]
Just to clarify my comment above, this kind of circular dependencies are a bit tricky for build systems as indeed they are equivalent to computing a fixpoint; imagine I have the script `foo` that reads file `a` containing an integer `n` and writes to `a` `n+1`

When is `a` up to date? Only when a fixpoint is reached; so in this case the build system should look or risk losing idempotency [which is really bad]

**Comment by Zimmi48** [comment]
> Just to clarify my comment above, this kind of circular dependencies are a bit tricky for build systems as indeed they are equivalent to computing a fixpoint; imagine I have the script `foo` that reads file `a` containing an integer `n` and writes to `a` `n+1`

Indeed, and note that when using the `diff` stanza, Dune let's the user take care of reaching the fixpoint, since it fails immediately after the diffing (and fixing the file when `--auto-promote` is used).

> Is this what you need?
> 
>* doc_grammar command line option that leaves the 2 files unchanged but creates *.new versions
> 
>* same thing for the rsts, or not?

Yes. For now, only for the two grammar files.

**Pull request merged**
