### PR TITLE
coq_makefile: build/use .cma for packed plugins too

### PR DESCRIPTION
**Pull request by gares**
a .cma contains linking info, e.g. findlib's -package options
while a simple, packed, .cmo file does not.  So even if we pack,
we put the packed .cmo into a .cma to carry linking flags.

### CODE REVIEW

**Comment by gares** [comment]
The build chain is *always*
```
ml -> cmo -> cma 
ml -> cmx -> cmxa -> cmxs
```
where the last step is optional. If we are packing, then it becomes
```
ml -> cmo \ 
ml -> cmo --> cmo -> cma
ml -> cmo / 

ml -> cmxo \ 
ml -> cmxo --> cmxo -> cmxa -> cmxs
ml -> cmxo / 
```

The interest of always having a `.cma` or `.cmxa` is that such file can carry linking flags, that
in findlib terms means which `-package` was use to build the plugin.

I'll try to put a test in the test-suite in order to detect this regression in the future (I'm sure it worked before a6a0c2c437c0b2920096d931fc595c0cf1f30d64).

**Comment by gares** [comment]
If you checkout 587f64e you get the error, while e1c14c0 introduces the fix

**Comment by gares** [comment]
56eb038 is restoring the compilation of `byte` as a prerequisite of `test-suite`.
It used to be like that since not long ago (depends on `world` that used to depend on `byte`).

**Comment by gares** [comment]
At the light of this fix, I think the code of `coqdep` could be simplified.
  https://github.com/coq/coq/blob/master/tools/coqdep_common.ml#L386-L412
In particular it should always be `.cma` and/or `.cmxs` and the `Variable` case should go away too.

**Comment by Zimmi48** [comment]
You have this error being raised in the test-suite when compiled with OCaml 4.05 / camlp5 7.01:

```
FAILURES

    coq-makefile/findlib-package/run.sh...Error!
```

I ignore if this is a non-deterministic error or if it is relevant to this PR. I'll let you judge.

**Comment by gares** [comment]
Hum, I think it is relevant to look at it.  It is 4.05 specific, but it is exactly the test this PR should make it work :-/

**Comment by gares** [comment]
I pushed a commit that fixes the issue on 4.05, let's see what travis says...

**Comment by gares** [comment]
Oh, it finally passed travis... @maximedenes is the deadline for 8.7beta expired?

**Comment by Zimmi48** [comment]
A few remarks:

- This was finally merged without a review from @letouzey. OK, he didn't react but I hope he's not going to be pissed about 10a3ad4074fbc85ca146d44449c1fe433515e3db.

- The commit history contains a lot of going back and forth. Would some of these commits have been squashed together, it would have helped me not to solve three times the same merge conflict. I'm especially not fond of commit ba64f7c64ad3da70d4c939b33384099ad8df7124 which claims to improve the documentation but also changes (once again) the implementation.

**Comment by gares** [comment]
> OK, he didn't react but I hope he's not going to be pissed about 2f6eda3.

How can I test byte compilation without compiling Coq in byte? Moreover I think make world still does not compile coq byte, you need to make test-suite to trigger that.

Sorry for the messy history.

**Comment by Zimmi48** [comment]
Well, I'm sorry to announce that this PR (likely) breaks the test-suite on Windows. See: https://ci.appveyor.com/project/Zimmi48/coq/build/v8.7~5
So I'm sorry, but it's probably going to miss 8.7+beta.

**Comment by gares** [comment]
This PR was merged, where should I push/test the fix?

**Comment by Zimmi48** [comment]
Open a new PR ...

**Comment by gares** [comment]
#1011

**Comment by Zimmi48** [comment]
@gares Do you think these recent intermittent coq-dpdgraph failures could be linked to this PR? I don't think they used to happen not so long ago (I may be wrong though, because coq-dpdgraph used to be in the allow_failure category). Moreover, I didn't see these failures when backporting to v8.7 before I backported this one.

```
CAMLOPT -a -o dpdgraph.cmxa
CAMLOPT -shared -o dpdgraph.cmxs
CAMLOPT -a -o dpdgraph.cmxa
CAMLOPT -shared -o dpdgraph.cmxs
COQC dpdgraph.v
gcc: error: dpdgraph.cmxs.startup.o: No such file or directory
File "caml_startup", line 1:
Error: Error during linking
make[2]: *** [dpdgraph.cmxs] Error 2
```

https://travis-ci.org/coq/coq/jobs/272359901
https://travis-ci.org/coq/coq/jobs/272068116

**Comment by gares** [comment]
Hum, if it is intermittent could be a race condition.  Are compiling with `-j` ?
I'll try to have a look this afternoon.

**Comment by Zimmi48** [comment]
Yes, -j2

**Comment by gares** [comment]
Hum, I've the impression the makefile of dpdgraph calls `coq_makefile` twice (in parallel) once to build `./dpdgraph.cmxs` and one to build `./dpdgraph.vo`.  Indeed in the traces above you see twice
`CAMLOPT -a -o dpdgraph.cmxa`, and the race condition on disk access makes the thing fail.

How to proceed? IMHO the fix is to remove `./dpdgraph.cmxs` from
https://github.com/Karmaki/coq-dpdgraph/blob/master/Makefile.in#L22

I'll make a PR with the just the overlay

**Comment by gares** [comment]
https://travis-ci.org/gares/coq/jobs/274106799

**Comment by Zimmi48** [comment]
How to proceed? I would say the best way would be to test locally if you can reproduce the race condition and test your fix to dpdgraph, then if it solves the problem, submit a PR on Karmaki/coq-dpdgraph. (If you see this as their bug rather than our bug.)

About the Travis job you shown, I don't think the commit setting the overlay (https://github.com/gares/coq/commit/ffda9cdd29d2a1dc0f5dd14011ddd6be99556642) is appropriate since it sets the wrong variables (mathcomp related).

**Comment by gares** [comment]
See #1044

**Comment by gares** [comment]
thanks for spotting the thing, I'll fix the variable name

**Pull request merged**
