### PR TITLE
Quote $(OCAMLFIND) in CoqMakefile.in for Windows

### PR DESCRIPTION
**Pull request by JasonGross**
This, I hope, will fix [bug #5620](https://coq.inria.fr/bugs/show_bug.cgi?id=5620)

### CODE REVIEW

**Comment by gares** [comment]
Awesome!

While you are touching that code, could you please also name the ocamldoc thing with a variable in the preamble as all other ocaml* commands?

**Review by gares — APPROVED** [review]

**Comment by JasonGross** [comment]
> While you are touching that code, could you please also name the ocamldoc thing with a variable in the preamble as all other ocaml* commands?

Done

**Comment by JasonGross** [comment]
I've also added a few more quotes around things, and changed from `echo "..."` to `echo '...'` so that backslashes in `COQLIB` won't be interpreted as escapes by `echo`

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
>I've also added a few more quotes around things, and changed from echo "..." to echo '...' so that backslashes in COQLIB won't be interpreted as escapes by echo

Is this some `make` trick?

**Comment by JasonGross** [comment]
> Is this some make trick?

No, this is a shell thing; Makefile variable expansion is independent of quotes.  However, if you, say, have a `$` in your folder name, the shell will expand that if you wrap it in double quotes, and will treat it as a literal if you wrap it in single quotes, I believe

**Comment by SkySkimmer** [comment]
For variables sure, but AFAIK character escapes are interpreted by the `echo` itself which doesn't know how you passed its arguments.

**Comment by JasonGross** [comment]
Oh, does the shell not interpret character escapes, only `$`? Say you have this:
```
print:
        echo $(v)
        echo "$(v)"
        echo '$(v)'
```
What do you see from the following?  (I'm not at a computer to test it out.)
```
make v='$PATH'
make v='$'
make v='\n'
make v='x       y'
make v='$(pwd)'
make v='\$'
```

Even so, I think single quotes are strictly better than double quotes, for `$` if nothing else.

**Comment by SkySkimmer** [comment]
```
echo ATH
ATH
echo "ATH"
ATH
echo 'ATH'
ATH
echo 

echo ""

echo ''

echo \n
n
echo "\n"


echo '\n'
\n
echo x       y
x y
echo "x       y"
x       y
echo 'x       y'
x       y
echo 

echo ""

echo ''

echo \

echo "\"
/bin/sh: 1: Syntax error: Unterminated quoted string
Makefile:4: recipe for target 'print' failed
make: *** [print] Error 2
```
Same if I set `SHELL=/bin/sh` (the default), but if I set `SHELL=/bin/bash` I get
```
echo ATH
ATH
echo "ATH"
ATH
echo 'ATH'
ATH
echo 

echo ""

echo ''

echo \n
n
echo "\n"
\n
echo '\n'
\n
echo x       y
x y
echo "x       y"
x       y
echo 'x       y'
x       y
echo 

echo ""

echo ''

echo \
\
echo "\"
/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file
Makefile:4: recipe for target 'print' failed
make: *** [print] Error 1
```
But if I run `echo "\n"` and `echo '\n'` in my `/bin/sh` I get newlines in both cases.

`¯\_(シ)_/¯`

**Comment by JasonGross** [comment]
Rebased on top of newly fixed trunk

**Pull request merged**
