### PR TITLE
Reduce nitpick_ignore list a little.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Review by cpitclaudel — APPROVED** [review]
Nice :+1:

**Comment by cpitclaudel** [comment]
Is it OK to merge this, or should I worry about the test pipelines?

**Comment by Zimmi48** [comment]
It's best to wait for the pipeline to complete at least the refman build (I restarted it because it hadn't started).

**Comment by jfehrle** [comment]
`destruction_arg` is used in ltac2.rst and by a number of tactics.  You should keep it.

**Comment by Zimmi48** [comment]
> `destruction_arg` is used in ltac2.rst and by a number of tactics. You should keep it.

This one I removed only because it appeared twice in the list.

@cpitclaudel CI looks good now.

**Pull request merged**
