### PR TITLE
[RM] Backports 8.13

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
@Zimmi48 what is exactly the object of this is_a_released_version ? Because encoding the status of a branch inside the sources seems not the right thing

**Comment by Zimmi48** [comment]
If it is true, then there is no "Unreleased changelog".

**Comment by gares** [comment]
What I mean is that I don't get why you want the test suite to tell me that I need to move the changelog files, and that in turns needs to see a flag in configure.

A different approach (if this is the only problem) would be that the backport PR also does the job of moving the unreleased entry to the main changelog file.

**Comment by Zimmi48** [comment]
>What I mean is that I don't get why you want the test suite to tell me that I need to move the changelog files, and that in turns needs to see a flag in configure.

The point of the test-suite file is only to ensure dangling changelog entries are not left over at release time. For sure, you want to get this test to fail *before* you actually tag.

>A different approach (if this is the only problem) would be that the backport PR script also does the job of moving the unreleased entry to the main changelog file (or force me to do it as it forces me to fix conflicts)

Doesn't work because the job of moving changelog entries to the release changelog must be done as a PR on *master*.

**Comment by gares** [comment]
> Doesn't work because the job of moving changelog entries to the release changelog must be done as a PR on _master_.

Another approach: one could call dev/tools/make-signed-tag-and-push.sh which fails if there are leftover changelog entry, and forces him to make a PR (on master) and backport it before tagging.

**Comment by gares** [comment]
(I understand the invariant, it is the way it is enforce that seems perfectible)

**Comment by Zimmi48** [comment]
>it is the way it is enforced that seems perfectible

Agreed.

>Another approach: one could call dev/tools/make-signed-tag-and-push.sh which fails if there are leftover changelog entry, and forces him to make a PR (on master) and backport it before tagging.

Sounds good but you still need a way to decide to not print the Unreleased changelog. This could be as soon as there is no dangling changelog entry, but that would need to be implemented.

**Comment by gares** [comment]
> need a way to decide to not print the Unreleased changelog.

I'm not so sure I understand what you talk about, can you clarify?

**Comment by Zimmi48** [comment]
See the first lines (`ifconfig::` ...) in this file: https://github.com/coq/coq/blob/master/doc/sphinx/changes.rst
The included file `unreleased.rst` is generated by doing a cat of all the files in `doc/changelog`, including the title files, so even in the case of an empty section, we print the section title.
We could improve this system by doing something more clever than a cat, to not show empty sections.
But until then, we need to hide this unreleased section from the released versions.

**Comment by gares** [comment]
@ppedrot do you really want me to backport PR #14012 ? If so please assess the failure

**Pull request merged**
