### PR TITLE
Share evar identities between clenv evars.

### PR DESCRIPTION
**Pull request by ppedrot**
We have to slighlty tweak the Evarutil API.

### CODE REVIEW

**Comment by ppedrot** [comment]
This is fairly trivial and needs an assignee.

**Comment by Alizter** [comment]
I can assign, but I need some help understanding what is going on here. Can you give a short description of what this accomplishes/why it's needed?

**Comment by ppedrot** [comment]
Evars lazily cache their identity instance, and generating them is O(n). Since we statically know that all the evars have the same instance we share it explicitly to reduce the cost.

**Comment by Alizter** [comment]
OK, is it something that can be seen in the bench?

**Review by Alizter — APPROVED** [review]

**Comment by ppedrot** [comment]
> OK, is it something that can be seen in the bench?

Probably not, but I think @JasonGross had some examples that were victim of the previous non-sharing behaviour.

**Pull request merged**
