### PR TITLE
Remove calls to structural equality in Micromega

### PR DESCRIPTION
**Pull request by ppedrot**
They were observed while profiling, there is no reason not to remove them.

### CODE REVIEW

**Comment by ppedrot** [comment]
Linter not happy due to #11251. Can I get a bit of justification on how why decided make the life of anybody trying to clean the *semantic* mess of micromega a hell only taking into account arbitrary *syntactic* constraints?

(I happen to hate a few elements of style generated by ocamlformat with a passion, and actually have good arguments against them. But while it's a thing to output crap, it's another one to make force anybody to submit to it.)

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
Benchmark running: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/886/console

**Comment by ppedrot** [comment]
@vbgl CI green, this is ready and needs an assignee.

**Comment by Zimmi48** [comment]
@coq/code-of-conduct-team got an *anonymous* report of a code of conduct violation pointing to the commit message "Fuck off ocamlformat". I have no idea where this is coming from and I don't especially like the idea of anonymous reports. In particular, I have no idea if the reporter was really offended by this or just trolling as a response to https://gitter.im/coq/coq?at=5e74a34a45afc57511e437b4 (I suspect the latter). But I still feel compel to tell @ppedrot that this was not necessarily the smartest idea for a commit message given that this is now engraved forever in our version control.

**Comment by ppedrot** [comment]
That was a hotfix to check it would work, and I should have changed the commit message. That said, I am not the first one to randomly insult tooling for the posterity (6560ae848fbc6a60e432d48d85fbbf12a8d2e6aa).

**Pull request merged**
