### PR TITLE
API cleanup: aliases

### PR DESCRIPTION
**Pull request by ghost**
Technically, this is a followup of #652 .

With this pull-request, I would like to develop a **process** for cleaning up API.

In this pull-request I picked a [single counterproductive feature](https://github.com/matejkosik/coq/blob/trunk__API__remove_low_hanging_cobwebs/API/PROPERTIES#L8) and addressed it consistently.

It is possible that we will see two classes of problems:
- questions related to aliases (and whether it is a good idea, in particular cases, to remove them from the API)
- questions related to the API cleanup process

There are many things to address. My initial plan is to declare what kind of [properties](https://github.com/matejkosik/coq/blob/trunk__API__remove_low_hanging_cobwebs/API/PROPERTIES) currently API satisfies. At the moment, there is not much but it is supposed to grow. It purpose is to define:
- where we are
- it will enables us to avoid walking in circles.

### CODE REVIEW

**Comment by ejgallego** [comment]
I all for removing aliases, however you may need to do it in a more fine-grained way so we can review each one individually. Also, you should try to deprecate as much as possible, but admittedly, I don't know how that works for types.

**Review by ejgallego — CHANGES_REQUESTED** [review]
- commit naming is, at best, obtuse; please fix.
- deprecate aliases when possible.
- make the removal of each logical set of aliases into a commit.

**Comment by gares** [comment]
I agree with Emilio on point 1, in particular commit messages should not depend on context.

To make it more clear, another example of bad commit messages are "fix bug 123" that makes no sense unless you have the bugzilla open (mentioning the number is fine, but putting just that is a bit obscure).

In this specific case "property 1" without having at hand the `PROPERTIES` file is not very clear.

Anyway, +1 for the removal of aliases

**Comment by matejkosik** [comment]
@ejgallego 
> make the removal of each logical set of aliases into a commit.

If only I knew what you mean by "logical set of aliases". All I see is a "aliases".

When I started this branch, I tried to put every deprecation into a single commit. So with each alias I did the same actions: `a`, `b` and `c`. But in the middle of the process (30-th commit out of 57) I realized that instead of `a`, `b`, `c` for each alias we have to do `a`, `b`, `d`. Now what? If these changes are atomized, I can't very much remove `c` from all commits and instead do `d`. So I just squashed everything to a single commit; then undid `c` 30-times; and then did `d` 30-times.

Believe me, I would very much like to give you your 57-commits instead of 1 but that would exclude any partial backtracking. Its much easier said than done.

Are you sure the branch in this form (i.e. one big commit (957ce5ed0ef98dd675fb33dcbe432efb1888f900) instead of 57 separate µ-commits) is unreviewable? Did you have a look, specifically, at changes in [API.mli](https://github.com/coq/coq/pull/718/commits/957ce5ed0ef98dd675fb33dcbe432efb1888f900#diff-98ab24345b65563bb8de6c2d2e2dfa80)?

There are only two things happening:
- attaching `[@@ocaml.deprecated "alias of ..."]` tag to elements that (I in opinion) deserve it. This is what needs to be reviewed.
- replacing each occurrence of deprecated element with its corresponding non-deprecated counterpart (that's not so interesting).

**Comment by matejkosik** [comment]
@ejgallego To give you what you just requested means one day of work. Not a disaster (can be done). But I would like to check first if it cannot be avoided.

**Comment by matejkosik** [comment]
@ejgallego 
> commit naming is, at best, obtuse; please fix.

I've forced-pushed a commit with a corrected commit-message:

```Remove (useless) aliases from the API.```

**Comment by matejkosik** [comment]
@ejgallego 
> deprecate aliases when possible.

I've marked all of them (which I had in mind) as `[@@ocaml.deprecated "alias of ..."]`. In total 72-times in `API/API.mli`. Did you have something else in mind?

**Comment by matejkosik** [comment]
@ejgallego When reviewing, you can ignore commit 0c74978e. That is a [separate pull-request](https://github.com/coq/coq/pull/652).

**Comment by ejgallego** [comment]
Ok, fair point, lets keep the granularity as is. My point about adding `[@@deprecated]` is that I think you should also deprecate such functions _internally_, that is to say, in the proper core `.mli` files too.

This looks good to me then, however I have a last question, is `open Name` really what we want here? I would prefer not opening such a low-level module (it will expose `t`).

**Review by ejgallego — CHANGES_REQUESTED** [review]
- Consider not doing `open Name`

**Comment by matejkosik** [comment]
@ejgallego 
> Consider not doing open Name

[Done](https://github.com/coq/coq/pull/718/commits/1b8f2d2e4d68a894a4e36adbef0356ed7c4e3d5c).

**Comment by matejkosik** [comment]
@ejgallego 
> My point about adding [@@deprecated] is that I think you should also deprecate such functions internally, that is to say, in the proper core .mli files too.

That is (unfortunatelly) outside the scope of my contract with INRIA so I hesitate making promises in this case. There are **tons** of such things.

**Comment by ejgallego** [comment]
Why was this not triggered by warning mechanism?

**Review by ejgallego — APPROVED** [review]

**Comment by matejkosik** [comment]
I am wondering about the same thing...

**Comment by matejkosik** [comment]
**TODO** : document justification for these changes (explain why it makes sense to remove aliases).

**Comment by ejgallego** [comment]
@matejkosik how about deprecating the aliases in the relevant core `.mli` files too? Are you planning to do that?

**Comment by matejkosik** [comment]
I consider that a good idea that is outside the scope of this pull-request.

**Comment by matejkosik** [comment]
What I/we plan to do, is also a good question...

**Comment by matejkosik** [comment]
(as well as a bug in our process)

**Comment by matejkosik** [comment]
I've found some more aliased function so I've deprecated these aliases two.

Originally, `Stdarg.wit_ref` was marked as the original and `Stdarg.wit_reference` was marked as (deprecated) alias. I decided to switch their roles: keep `Stdarg.wit_reference` as the original and deprecate `Stdarg.wit_ref` as its alias. I think this is more logical and more practical (if one opens the `Stdarg` module, which is what cannot be avoided, the `ref` from `Stdarg` would shadow the `ref` from `Pervasives`).

If you disagree with this, let me know.

**Comment by herbelin** [comment]
At some time, the names of the `wit` keys were dynamically bound in `TACTIC EXTEND` and co.
Looking at `tacextend.mlp`, line 66, this seems to be still the case. This means that if it is called `wit_ref`, `TACTIC EXTEND` will have to use `ref` to parse a global reference. If it is called `wit_reference`, it will have to use `reference` (as it does in e.g. `g_ltac.ml4`). If both aliases exist, then bot `ref` and `reference` will be usable in `TACTIC EXTEND`. Currently, only `reference` seems to be used (e.g. also in `g_ground.ml4` or `g_indfun.ml4`), so this is consistent with your approach to prefer `wit_reference`.

**Comment by matejkosik** [comment]
Thanks for the review!

I am afraid that more aliases may be still lurking in there. I did only single pass through the API.

**Comment by maximedenes** [comment]
This PR doesn't compile according to Travis.

**Comment by matejkosik** [comment]
It must wait until #652 is merged.

**Comment by maximedenes** [comment]
@matejkosik Can you rebase?

**Comment by matejkosik** [comment]
Done.

**Comment by JasonGross** [comment]
@matejkosik The overlay to fiat and bedrock won't work; it's not backwards compatible.  I have a way of making it add `-bypass-API` to only trunk (as long as `-bypass-API` shows up somewhere in `coqc -help`), but I'd like to understand what the reason is for doing this, as opposed to correcting the aliases in the `*.ml.trunk` and `*.ml4.trunk` files.

**Comment by matejkosik** [comment]
Status update:

Travis reports that VST [fails](https://travis-ci.org/matejkosik/coq/builds/240870220) but the failure is unrelated to my branch. Yesterday we [reported](https://github.com/PrincetonUniversity/VST/issues/72) that VST compilation was broken. It was fixed quickly (yey) but immediatelly after that [somebody](https://github.com/scuellar) else pushed commit that rebroke it.

Travis reports that fiat-crypto is broken. I am trying to reproduce that and see what needs to be done.

**Comment by JasonGross** [comment]
Fiat-crypto was broken for a few hours earlier; it should now be fixed (and sorry about that).  If the error is about a non-existent `modulo` argument, restarting the build will be enough to fix it.

**Comment by matejkosik** [comment]
@JasonGross Thanks for the update.

@maximedenes Travis now has [two complains](https://travis-ci.org/matejkosik/coq/builds/240870220):
- `vst` does not compile (the reason is that it was broken upstream)
- `coq-fiat-crypto` ... this one ["exceeded the maximum time limit for jobs, and has been terminated."](https://travis-ci.org/matejkosik/coq/jobs/240870229).

We still need to decide what to do in case of `vst` and `coq-fiat-crypto`, but maybe it is not a blocking issue for this pull-request. Can this be merged WDYT?

**Comment by JasonGross** [comment]
I think there is still the issue with bedrock and fiat-parsers; the overlays are not mergeable because they are not backwards compatible.  If `-bypass-API` is mentioned in `coq_makefile -help`, I can adapt them to pass `-bypass-API`, but what is the status moving forward of plugins that pass `-bypass-API`?  And how much work is it to fix aliases from the plugins of bedrock and fiat-parsers?

**Comment by JasonGross** [comment]
> coq-fiat-crypto ... this one "exceeded the maximum time limit for jobs, and has been terminated.".

I've pushed a commit just now that removes the latest file we added (which takes about 2-3 minutes on travis) from the `lite` target.  Hopefully this will be enough to restore the status quo...  (If not, open an issue on fiat-crypto.)

**Comment by ejgallego** [comment]
Thanks @JasonGross .

**Comment by matejkosik** [comment]
@JasonGross I've dropped the overlays. They are not needed for this pull-request.

For the head of this branch, all tests [succeed](https://travis-ci.org/matejkosik/coq/builds/241323045).

Anything else need to be done here?

**Comment by matejkosik** [comment]
@maximedenes Is the "fix needed" label still meaningful? Can it be dropped?

**Pull request merged**
