### PR TITLE
Tidy the exposed API of the Clenv module

### PR DESCRIPTION
**Pull request by ppedrot**
Yet another reduction of the surface attack of clenv-related code.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
coq-tools is spurious error
I don't think there's any reason this would change perf so fiat-crypto timeout is spurious too

@coqbot merge now

**Comment by JasonGross** [comment]
> coq-tools is spurious error I don't think there's any reason this would change perf so fiat-crypto timeout is spurious too

How long has coq-tools been failing?  I don't think the error is spurious (though I do think it's not related to this PR), and I think something broke coq-side, given that the CI on coq-tools passed the last time it ran

**Comment by SkySkimmer** [comment]
Spurious means not related to this PR

**Comment by ppedrot** [comment]
According to https://gitlab.com/coq/coq/-/pipelines?page=1&scope=all&ref=master, it worked on 9bbe89ac but failed on a3bf5ca4 so it's either #17443 or #17504.

**Pull request merged**
