### PR TITLE
ci: update build script for coq-simple-io

### LINKED ISSUE #68: Broken in Coq CI
https://gitlab.inria.fr/coq/coq/-/jobs/4150746

### PR DESCRIPTION
**Pull request by Lysxia**
Fixes Lysxia/coq-simple-io#68

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by Lysxia** [comment]
What makes it want to do native compilation?

**Comment by SkySkimmer** [comment]
We have native configured on in CI.

**Comment by Lysxia** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@SkySkimmer what is this blocking on? CI is broken and we may merge PRs accumulating errors in the meantime.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
