### PR TITLE
Newlocations

### PR DESCRIPTION
**Pull request by maximedenes**
As described in one of the two commits, this PR adds file name, line number and beginning of line position to locations. No more tricks to play to reconstruct this information.

### CODE REVIEW

**Comment by ejgallego** [comment]
+1000. Looks good to me, I'm not expert in `camlpX` stuff thou.
Tested with SerAPI, it seems to give accurate info.

**Comment by ppedrot** [comment]
LGTM. I am a bit afraid that people are going to start relying on location representation though... Couldn't you provide an opaque `t` type defined internally as an alias for a `repr` type corresponding to the record, together with a function `make : repr -> t`?

**Comment by maximedenes** [comment]
We could, but I feel it is a bit overkill. The most likely change to locations is to add a field, and that has an easy migration path for plug-in writers. In any case, move to separate repr and t types is still easy to do after merge.

**Comment by ejgallego** [comment]
Ok so a couple of comments after some more testing, in case someone know how to fix them; thanks Maxime for the patch!

- I'd suggest that Pp.loc understands the debug flag and prints the whole location information.
- It seems that newline reporting is broken in the commits:
```
(Control (StmAdd 100 None "
Inductive A :=
 | AA .

(* this is a comment
   line 1
   line 2
*)

Inductive B.
"))
((fname "") (line_nb 2) (bol_pos 1) (line_nb_last 2) (bol_pos_last 1) (bp 1) (ep 23))
((fname "") (line_nb 7) (bol_pos 70) (line_nb_last 7) (bol_pos_last 70) (bp 70) (ep 82))
```
  as you can see, `line_nb` for for B should be 10, so the 3 newlines were lost.
- Also, while we are at it would be awesome to document how to set the initial position in a parsable. Scenario: imagine that after #204 we can send the Stm the whole document. However, on `EditAt`s the IDE will need to create a new parsable and hint it the initial position.

**Comment by maximedenes** [comment]
Thanks Emilio for the very useful feedback! I'll fix the line numbers with comments, it is easy. As for the second point, giving an initial location to a parsable is natural and part of the camlp4 interface. However, I didn't find any easy way to do so with camlp5. I'll try to find a local hack providing such a nice interface.

**Comment by ejgallego** [comment]
Thanks Maxime. Other than seeding a location to a parsable I don't see any other way for the IDEs to give accurate file location to Coq. Maybe I'm missing something... I'll have a look the camlp5 stuff to see if a ring bells.

**Comment by siegebell** [comment]
Could you add a function to get the location from a state_id?

**Comment by ejgallego** [comment]
@siegebell , if I understand things properly, that is not possible currently due the way `Stm` parsing is done. You are best for now caching that information client side.

Sertop can indeed simulate this client-side by doing its own parsing, but it needs to use the ML API.

Proper support of this feature in Coq would require:
  - Merging this patch.
  - Modifying the protocol so IDEs can seed a location to add.
  - Likely merging #204, (including fixing the indentation support).

So yeah, unless I'm missing something, it may be hard to add for now

**Comment by ejgallego** [comment]
https://coq.inria.fr/bugs/show_bug.cgi?id=4833 may be something to keep an eye too

**Comment by ejgallego** [comment]
Also, while we are looking at the lexing/parsing pipeline, there is some stuff that looks like cruft:

- `cLexer:{,restore,save}_com_state`: Not used, called in #158 but I wonder why.
- `cLexer:{,restore,save}_location_table`: Idem.
- `vernac:{restore,save}_translator_coqdoc`: Idem.

Looking at the history they all look like a leftover of a previous implementation of coqdoc that is not used long time ago.

It would greatly help if we could add a `cLexer.mli` file.

**Pull request merged**
