### PR TITLE
[ci] [appveyor] Enable cache for builds.

### PR DESCRIPTION
**Pull request by ejgallego**
We cache CYGWIN and OPAM. Current cygwin install is not deterministic
but should do the job in the scope of this job.

### CODE REVIEW

**Comment by ejgallego** [comment]
It seems I don't have the permissions to enable caching in appveyor, so someone should do it.

**Comment by ejgallego** [comment]
Ping @maximedenes

**Comment by ejgallego** [comment]
Ping @maximedenes

**Comment by maximedenes** [comment]
Isn't this going to delay the detection of problems related to cygwin? My fear is for example a cygwin package update would break the build but we don't detect it because of the cache, until the release when we try to sign the package.

Is that not an issue?

**Comment by Zimmi48** [comment]
@maximedenes Note that this is changing AppVeyor only, and so it is unrelated to the packaging question.

**Review by maximedenes — APPROVED** [review]

**Comment by ejgallego** [comment]
@maximedenes did you enable the cache in the settings? AFAICT this was never tested due to myself lacking permissions.

My fault for not setting the `needs: testing` tag. This should be harmless tho.

**Comment by maximedenes** [comment]
Ouch, I saw it last time I looked at this PR, but forgot this time. @Zimmi48 do you know what I should do to give Emilio permission on appveyor?

**Comment by Zimmi48** [comment]
@maximedenes I am not sure. I recently activated the new AppVeyor GitHub App for the Coq repo and I also messed up my own AppVeyor settings, so the result is that everyone in the Coq organization who logs into AppVeyor using their GitHub account should have basic permissions like restarting the builds, but I don't have more than this myself anymore. You can try to look around to see if you can make me an admin (again) and then I can have a deeper look.

**Pull request merged**
