### PR TITLE
Fix typo in CHANGES.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation fix

### CODE REVIEW

**Comment by Zimmi48** [comment]
I used `[skip ci]` in the commit message but unfortunately:

> Currently neither [ci skip] nor [skip ci] supports fork PRs.

https://circleci.com/docs/1.0/skip-a-build/

It seems to work for Travis though.

**Comment by Zimmi48** [comment]
Oh and moreover this is the CircleCI 1.0 doc. Not sure the feature exists for 2.0.

**Comment by SkySkimmer** [comment]
https://circleci.com/docs/2.0/skip-build/ (essentially the same as 1.0)

**Comment by gares** [comment]
I hope we can write the comment in the GH issue, and not in the real commit message...

**Comment by Zimmi48** [comment]
We're missing code owners for CHANGES but I assume this should have been the same as for other toplevel documentation files and you @maximedenes are the secondary code owner here.

**Comment by maximedenes** [comment]
> We're missing code owners for CHANGES

I didn't put owners, because I thought it would be too much noise since many PRs are supposed to have a `CHANGES` entry, and I don't think that requires a specific review.

**Comment by Zimmi48** [comment]
Very sensible. I had completely overlooked this.

**Comment by Zimmi48** [comment]
But still assigning this to you since we can't self-merge. Maybe the owner should still be defined but in comment only.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
