### PR TITLE
Fix for bug #4784

### PR DESCRIPTION
**Pull request by ejgallego**
We revert to the old flushing strategy in the toplevel.

PR #179 introduced a different flushing in toplevel, but now a new
line is produced when Set Printing Width is large and proof general complains.

IMO, this is a pitfall of the current setup, in particular, it is using
format without enclosing expressions in top-level boxes, which results
in undefined behavior and fragile printing such as this bug shows.

Test suite passes.

### CODE REVIEW

**Comment by JasonGross** [comment]
Thanks @ejgallego!  It seems to work well on the few examples I tried it on.

**Comment by ejgallego** [comment]
Cool, thanks. I'll push some other safety fixes for printing corner cases. Indeed, Coq reimplemented Ocaml's flush_all with different semantics so I didn't catch that in my cleanup ! When I removed Coq's flush_all a few different places started to use Ocaml's one, hence the source of error. (toghether with fragile printing)

**Comment by ejgallego** [comment]
I've added a preventive fix to other parts of the code that could share the same problem. A deeper fix is desirable (see https://coq.inria.fr/bugs/show_bug.cgi?id=4789) but this should avoid some messages being lost.

**Comment by ejgallego** [comment]
Merged outside github

**Pull request closed without merging**
