### PR TITLE
[RFC] Use bash in makefiles

### PR DESCRIPTION
**Pull request by JasonGross**
This paves the way to use `.SHELLFLAGS = -o pipefail -c`, which would
allow us to avoid the use of temporary files in #745.

There was a bit of discussion on gitter, involving me and @Zimmi48 and @psteckler.  Is this a desired thing?

Pros: better predictability
Cons: no more support for systems without bash

### CODE REVIEW

**Comment by JasonGross** [comment]
CI fails on `validate` with
```
File "kernel/nativecode.mli", line 1:
Error: Corrupted compiled interface
kernel/declarations.cmi
```
This is unrelated, I presume?

**Comment by ejgallego** [comment]
> This is unrelated, I presume?

yup, this is a side effect of the API patch; which needs to be corrected.

**Comment by JasonGross** [comment]
Rebased on top of newly fixed trunk

**Comment by JasonGross** [comment]
This is basically superseded by #968 (though there may still be a question about what to do in `coq_makefile`-made `Makefile`s).

**Pull request closed without merging**
