### PR TITLE
Travis: cleanup environment variables a bit.

### PR DESCRIPTION
**Pull request by SkySkimmer**
- BUILD_TARGET not used
- Put elpi's FINDLIB_VER="" at the end of the environment for nicer
  display in the travis UI.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Circle failures seem unrelated, merging.

**Comment by Zimmi48** [comment]
Did you bypass the milestone check on purpose?

The merging doc says:

> This script conducts various checks before proceeding to merge. Don't bypass them without a good reason to, and in that case, write a comment in the PR thread to explain the reason.

(OK, it was not there from the beginning)

I don't want to be a pain in the ass, but these checks help me trust that I don't need to screen everything that is going on. Of course, this one case was completely unimportant because this is an infrastructure PR. I'm just mentioning this as a generic principle.

**Comment by SkySkimmer** [comment]
Why is bypassing the milestone check allowed? With eg the CI check it's 
easy to see when we want to bypass it but this one less so.

Gaëtan Gilbert

**Comment by Zimmi48** [comment]
> Why is bypassing the milestone check allowed? With eg the CI check it's easy to see when we want to bypass it but this one less so. 

It's allowed for when you merge into an old branch like `v8.6`. Then there is no appropriate milestone. Or if you want to use the merge script to merge in a topic branch on your fork.

> I bypassed it on purpose as CI changes are kind of meta changes, right? So I was not sure if they should belong to the milestone, but yeah, sorry for that.

They are, but there are already labels that allow to differentiate the various kinds of PRs.

**Pull request merged**
