### PR TITLE
Cleanups around the use of Evd.expand_existential.

### PR DESCRIPTION
**Pull request by ppedrot**
It's written on the label of the can.

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
bench failed because https://github.com/coq/coq/pull/16584

**Comment by Alizter** [comment]
@ppedrot Can you rebase on top of a fresh master?

**Comment by Alizter** [comment]
@coqbot bench

**Review by SkySkimmer — APPROVED** [review]
looks ok

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
