### PR TITLE
[ocamlformat] Update to 0.14.0

### PR DESCRIPTION
**Pull request by ejgallego**
No diff to sources (luckily), see release notes at
https://discuss.ocaml.org/t/ann-ocamlformat-0-14-0/5435 for more
information.

### CODE REVIEW

**Review by Zimmi48 — DISMISSED** [review]
Updates to the version of ocamlformat that is required should be done in sync with updates of nixpkgs. Fortunately, ocamlformat has already been updated in nixpkgs, so all that is needed is a bump. I can take care of pushing a commit that does it.

Furthermore, I want to test the behavior of the pre-commit hook when ocamlformat is available but not at the right version. It's likely not go well. The fix should be pretty easy (test the version instead of testing only if ocamlformat is available) and I can also take care of pushing it.

**Comment by Zimmi48** [comment]
>Updates to the version of ocamlformat that is required should be done in sync with updates of nixpkgs. Fortunately, ocamlformat has already been updated in nixpkgs, so all that is needed is a bump. I can take care of pushing a commit that does it.

Done.

>Furthermore, I want to test the behavior of the pre-commit hook when ocamlformat is available but not at the right version. It's likely not go well. The fix should be pretty easy (test the version instead of testing only if ocamlformat is available) and I can also take care of pushing it.

Done. This does not change anything if you don't change any ML file. If you do, you get the error message:

```
ocamlformat: Error while parsing .ocamlformat:
             For option "version": expecting "0.13.0" but got "0.14.0"
```

But this does not prevent the pre-commit hook to run successfully. This can be fixed separately, together with #12049.

I cannot be the assignee since I've now co-authored this PR.

**Comment by Zimmi48** [comment]
@ejgallego You have forgotten to update the Dockerfile key (this explains the error in the linter: the Docker image it uses still has ocamlformat 0.13.0).

**Comment by ejgallego** [comment]
Thanks for all the work on this @Zimmi48 ; I will fix the PR shortly.

**Comment by ejgallego** [comment]
> @ejgallego You have forgotten to update the Dockerfile key (this explains the error in the linter: the Docker image it uses still has ocamlformat 0.13.0).

In fact how I did not overwrite the old image? (_merde_ ?) XDDD

**Comment by ejgallego** [comment]
There is a bug in `ocamlformat` opam files, fixes submitted:
- https://github.com/ocaml/opam-repository/pull/16171
- https://github.com/ocaml-ppx/ocamlformat/pull/1330
I will tho wait to bump dune until 2.5.0 is in opam, as we want to bump Dune to that version first for other reasons; then this PR can go in.

**Comment by ejgallego** [comment]
@Zimmi48 I've dropped the nix update as I understand the nix ref should be good after the Dune 2.5.0 update.

**Review by Zimmi48 — APPROVED** [review]

**Pull request merged**
