### PR TITLE
Statically generate a universe for omega type1.

### PR DESCRIPTION
**Pull request by SkySkimmer**
This is useful with [-natdynlink no] as otherwise every universe level
is bumped by one, leading to diffs in the output tests.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@mattam82 poke

**Comment by maximedenes** [comment]
@SkySkimmer Sorry, how exactly does this related to `-natdylink no`?

**Comment by SkySkimmer** [comment]
I guess the plugin is initialized automatically or earlier? Mostly I observed that it was breaking output tests.
(assuming I didn't make some mistake while testing)

**Comment by maximedenes** [comment]
@SkySkimmer I think it would be better to investigate the underlying issue, and not rush a workaround. If that's ok, can we move this to 8.8.0?

**Comment by SkySkimmer** [comment]
OK

Gaëtan Gilbert

**Comment by mattam82** [comment]
Clearly looks like a initialization order issue, not sure what better solution we can have.

**Comment by SkySkimmer** [comment]
>Clearly looks like a initialization order issue, not sure what better solution we can have.

So do we put this in or close (opening an issue at the same time)?

**Comment by maximedenes** [comment]
do we understand the problem, now?

**Pull request closed without merging**
