### PR TITLE
Add minimal CHANGES entry about deprecated compat notations

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** documentation

- [x] Entry added in CHANGES.

Please do suggest alternative ways of phrasing things, or that a gist should be created rather than linking to a script in an issue comment, etc.

### CODE REVIEW

**Review by Zimmi48 — CHANGES_REQUESTED** [review]
Yes, please do create this gist and document the use of the script very clearly (how to run it, probably with a pipe and a stderr redirect; document also that some very rare fixes could still be needed after applying the script).

The CHANGES entry should say something along the line of "These deprecated compatibility notations are easy to fix thanks to the hint contained in the warnings. For projects that require more than a handful of such fixes, there is a script that will do it automatically, using the output of `coqc`."

**Comment by JasonGross** [comment]
@Zimmi48 Updated.  I have added the documentation to the python script itself:
```python
# Usage: ./replace-notations.py logfile
# Uses the warnings in logfile to locate compatibility notation warnings,
# then search and replace to use the correct notations.
#
# Extended Usage:
# First, using the old version of Coq (e.g., 8.9), which emits deprecation
# warnings, run something like
#    make -Okj 2>&1 | tee logfile
# You may want to first run `make clean` to ensure that all files get built.
# N.B. The -O is for --output-sync, which ensures that output is interwoven
#  correctly when running with -j
#
# Once the build completes, you can run
#     ./replace-notations.py logfile
# This will update the .v files in place.  After this, you will want to run
# `make clean; make` with the *new* version of Coq (e.g., master, 8.10),
# which does not support compatbility notations, or else you will want to run
# `make OTHERFLAGS='-w "+compatibility-notation"'` with the old version of Coq.
#
# Note that in rare cases, there may be some compatibility notation uses that are
# not correctly updated by this script, and which have to be updated by hand.
#
# From https://github.com/coq/coq/issues/8383#issuecomment-424525941
```

**Review by Zimmi48 — APPROVED** [review]
Thanks! I suggest adding the name of the authors in the comment in the gist:

```python
# Authors: Jason Gross and Jean-Christophe Léchenet
```

I also suggest using the `[ ]()` format for the link in `CHANGES.md`. Let's make the most out of what Markdown offers! (And the link to the gist is not very interesting anyways.)

**Comment by JasonGross** [comment]
> I suggest adding the name of the authors in the comment in the gist:

Done

> I also suggest using the ...

Done

**Pull request merged**
