### PR TITLE
 AConstr: avoid building subarrays in mkApp 

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Not sure those changes are real

**Comment by ppedrot** [comment]
I don't think it changes anything in terms of runtime, and contrarily to the previous patch I actually think that this is making the code slightly worse. @SkySkimmer do you still want to get this merged?

**Comment by SkySkimmer** [comment]
WDYT about having just the first commit?

**Comment by ppedrot** [comment]
I don't like it either. My main source of distaste is the use of arbitrary exceptions for control flow that went from a local use to a global one, separating the invariant in the source code.

**Pull request closed without merging**
