### PR TITLE
CClosure: don't partially apply evar_repack

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Apart from likely not being observable, you're now paying the allocation as many times as the evar is normalized, whereas you'd be paying it only once per instance before. As such I believe it'd be worse on micro-benchmarks.

**Comment by SkySkimmer** [comment]
>Apart from likely not being observable, you're now paying the allocation as many times as the evar is normalized, whereas you'd be paying it only once per instance before. 

I don't think that makes sense. In the before code it needs to allocate a closure for `fun args -> info.i_cache.i_sigma.evar_repack (evk, args)` (capturing `evk`) in knht, and a tuple for `(evk, args)` when it gets called. In the after code it needs to allocate the tuple when it gets called, resulting in a little less allocation.

Mostly I think this makes the code a bit cleaner, I don't expect significant perf changes.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
