### PR TITLE
Fixing BZ#5741 (anomaly in info_trivial).

### PR DESCRIPTION
**Pull request by herbelin**
The anomaly was introduced in my commit 1559f73.

I made a quick patch, @letouzey, please tell if the way I did it respects your initial intent.

Note that 8.7 is concerned too.

### CODE REVIEW

**Comment by herbelin** [comment]
Additional question: in 8.6,
```coq
Goal True.
debug trivial.
```
gives
```
Debug: (* debug trivial: *)
Debug:  assumption. (*fail*)
Debug:  intro. (*fail*)
Debug:  exact I (in core). (*success*)
```
but
```coq
Goal True.
debug auto.
```
gives
```
Debug: (* debug auto: *)
Debug: * assumption. (*fail*)
Debug: * intro. (*fail*)
Debug: * exact I (in core). (*success*)
```
As it is, the PR changes the output of `debug trivial` by adding a `*` too (in between the two spaces). Is that ok? Or do we prefer to not print a `*` with `debug trivial`? Or do we reduce the number of `*` by 1 for `auto` (i.e. starting with 0)?

**Comment by Zimmi48** [comment]
> Or do we reduce the number of * by 1 for auto (i.e. starting with 0)?

I would vote for this. It's less confusing, I think.

**Comment by maximedenes** [comment]
@letouzey ping

**Comment by maximedenes** [comment]
@herbelin Should I merge even if we don't get feedback from @letouzey? Or do you want to wait?

**Comment by maximedenes** [comment]
@herbelin ping

**Comment by letouzey** [comment]
Hi @maximedenes @herbelin, sorry for the late answer. Do what you please...

**Pull request merged**
