### PR TITLE
Delayed substitution in VM normalization of telescopes.

### PR DESCRIPTION
**Pull request by ppedrot**
This is the same trick used in several places to prevent a quadratic blowup due to repeated unary substitution in telescopes. Instead we carry around a substitution and rely on fconstr low-level APIs.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
I think that some of the effects in the speed-ups are real, albeit small. Maybe we should merge this PR, I don't think it can hurt anyways.

**Comment by ppedrot** [comment]
Ping @coq/vm-native-maintainers, any taker?

**Review by SkySkimmer — APPROVED** [review]
sure why not

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
