### PR TITLE
Printing tweaks: use format "compacting box" instead of hovbox + tweak `fun =>` break hint

### PR DESCRIPTION
**Pull request by SkySkimmer**
IMO this looks better at least on the test suite examples

Not sure if we want to change the code to replace `hov` with `box` everywhere

Overlays:
- https://github.com/JasonGross/coq-tools/pull/210

### CODE REVIEW

**Comment by herbelin** [comment]
Looks also rather good to me.

**Comment by proux01** [comment]
> IMO this looks better at least on the test suite examples

I tend to agree

> Not sure if we want to change the code to replace `hov` with `box` everywhere

Adding box to https://github.com/coq/coq/blob/master/lib/pp.mli#L46-L50 and replacing all current uses of hvbox with box would probably make sense indeed. The number of occurences doesn't seem crazy (less than 200 according to a quick grep), so that's probably reasonnably feasible.

**Comment by SkySkimmer** [comment]
This replaces hovbox not hvbox

**Comment by proux01** [comment]
My bad, I indeed mixed them up, then the number of occurences is indeed a bit higher (more like 600).

**Comment by SkySkimmer** [comment]
Not sure what's going on in coq-tools, cc @JasonGross

**Comment by JasonGross** [comment]
I guess you need to update the error message regex at https://github.com/JasonGross/coq-tools/blob/fc4c213b6a6089922c8946b5c27f3547b4e4b7e8/examples/run-example-042.sh#L51-L53, you can probably use the same pattern as on L50--51 to allow a choice between line breaks and spaces

**Comment by ppedrot** [comment]
Let's rerun a fresh CI, @coqbot run full ci

**Comment by ppedrot** [comment]
Since everybody seems to like the new output, I will merge this soon except if somebody strongly disagrees.

**Review by ppedrot — APPROVED** [review]

**Comment by JasonGross** [comment]
Sorry, I missed the overlay at https://github.com/JasonGross/coq-tools/pull/210.  I've just told the CI to run and set it to auto merge.  Please wait until the overlay is merged before merging this (and please ping me if the CI there fails and I haven't noticed)

**Comment by JasonGross** [comment]
I've merged https://github.com/JasonGross/coq-tools/pull/210, feel free to merge now

**Comment by ppedrot** [comment]
Then @coqbot merge now

**Pull request merged**
