### PR TITLE
Document -vos flag for coqdep

### PR DESCRIPTION
**Pull request by SkySkimmer**
cc @charguer

### CODE REVIEW

**Review by ejgallego — CHANGES_REQUESTED** [review]
You need to modify also `usage` in `coqdep.ml`

**Comment by SkySkimmer** [comment]
changed

Gaëtan Gilbert

**Review by ejgallego — APPROVED** [review]
LGTM, leaving some time for @coq/doc-maintainers

**Review by Zimmi48 — APPROVED** [review]
I believe you have already reviewed the content of the PR Emilio, so that's a go from me for the form.

**Pull request merged**
