### PR TITLE
Remove sed command which fails with MacOS's sed

### PR DESCRIPTION
**Pull request by mattam82**
**Kind:**  bug fix / infrastructure.

This patch removes sed invocations that are not valid with macOS's BSD sed and make the build fail depending on the make version.

### CODE REVIEW

**Comment by RalfJung** [comment]
Ah yes, the fun of `sed` on macOS. This is the reason why I switched to `awk` for Iris' Makefile patching.

**Comment by mattam82** [comment]
It's curious that appveyor reports an error while the log shows no error, is it a timeout thing?

**Comment by SkySkimmer** [comment]
Should have a CHANGES I think.

**Comment by mattam82** [comment]
Actually, the echo solution failed on nix and windows, so I reverted to removing the incriminated line

**Comment by SkySkimmer** [comment]
Probably it interpreted \n badly, you want `printf '\n\n\n'` (with single quotes) or `echo; echo; echo` for reliable newlines I think.

**Review by vbgl — APPROVED** [review]

**Pull request merged**
