### PR TITLE
[parsing] Remove hacks for reduced Prelude.

### PR DESCRIPTION
**Pull request by ejgallego**
These hacks to warn the users about needed modules are not needed
anymore in 8.8, as the proper error message is done in 8.7 already.

This helps in avoiding a dependency from parsing to `MlTop`.

### CODE REVIEW

**Comment by maximedenes** [comment]
@letouzey Does this look ok to you?

**Comment by Zimmi48** [comment]
This would have to be merged after @tchajed's #1030, or part of the latter would have to become v8.7-only.

**Comment by ejgallego** [comment]
IMHO #1030 looks like 8.7-only, but lets see first if this can go throu.

**Comment by ejgallego** [comment]
Isn't it the review in #939 enough for this PR to move forward?

**Comment by Zimmi48** [comment]
I've personally made sure that @letouzey was aware of this by mentioning it to him as something he should have a look at before it's merged. I don't know what his conclusion was because I didn't stay with him at the time but I suppose that he's not opposed to it since he didn't comment on it.

**Comment by maximedenes** [comment]
As discussed, this follows our deprecation / removal policy, and no opposition was raised in more than a month, so merging.

**Pull request merged**
