### PR TITLE
Remove useless "New" wrapper modules

### LINKED ISSUE #16637: Outdated documentation on tactics/tacticals.mli
#### Description of the problem
The ocamldoc documentation in tactics/tacticals.mli still refers to `Tacticals.New`, which does not exist anymore.
Similarly, the documentation about deprecated features in proofs/tacmach.mli also refers to `New`.

#### Coq Version
Coq-8.15 and Coq-8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
and fix #16637

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Review by gares — APPROVED** [review]
thanks!

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
As is common these days, fiat-crypto is broken, but AFAIK it doesn't use any of the New modules that were unfolded in this PR so this should be safe to merge. Since it's a low-stake PR, let's merge now. @coqbot merge now

**Comment by JasonGross** [comment]
Urg, I guess 5GB RAM (5261276 ko) is too much for Coq's CI?
I've made https://github.com/mit-plv/fiat-crypto/issues/1427
cc @andres-erbsen

**Comment by JasonGross** [comment]
@ppedrot any chance we could get https://github.com/coq/coq/issues/11994 (`-mem` flag to print the memory stats at each command) soon to help debug this?

**Comment by Alizter** [comment]
@JasonGross Open an issue about it.

**Comment by Alizter** [comment]
@JasonGross My bad!

**Pull request merged**
