### PR TITLE
Add module types USetS UMapS for unordered maps

### PR DESCRIPTION
**Pull request by SkySkimmer**
instead of doing assert false in the hmap implementation

Overlays:
- https://github.com/ejgallego/coq-serapi/pull/412

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
OK on my side

**Comment by herbelin** [comment]
A priori going to merge if noone complains

**Comment by herbelin** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
ping @herbelin

**Pull request merged**
