### PR TITLE
Introduce GitHub Action to check for conflicts in PRs.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

This is an alternative to adding this feature to @coqbot (coq/bot#14).

### CODE REVIEW

**Comment by Zimmi48** [comment]
Tested here: Zimmi48/coq#8.

**Review by SkySkimmer — APPROVED** [review]
Looks cool.
Should we worry about malicious updates using the token somehow?

**Comment by Zimmi48** [comment]
>Should we worry about malicious updates using the token somehow?

Malicious update to the action? I agree this is a concern given that this is published by an individual that we don't know personally and that these things happen (as in the event-stream fiasco). I can change the PR to use a fixed commit instead. Note though that I didn't even review the current code of the action.

**Comment by SkySkimmer** [comment]
Could we have a more restricted token than the autogenerated one? ie restrict write permissions to the minimum for changing labels.

**Comment by Zimmi48** [comment]
No, tokens don't have fine-grained permissions.

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
