### PR TITLE
Fix macOS CI on Azure.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@coq/ci-maintainers Now that https://github.com/Homebrew/homebrew-core/issues/61772 seems to have been resolved, this PR fixes the macOS CI build by removing the failing `brew update` step and unpinning homebrew.

Unfortunately, because of problems discovered by @ejgallego in #12672 during the previous attempt to fix #12657, this makes the bundle generation step fail, so we disable it for now.

[Failing log](https://dev.azure.com/coq/coq/_build/results?buildId=12795&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=82eb5711-24fa-5d76-924d-28dd4736936e):

```
/Applications/Xcode_11.3.1.app/Contents/Developer/usr/bin/make --warn-undefined-variable --no-builtin-rules -f Makefile.build bin/CoqIDE_8.13+alpha.app
rm -rdf bin/CoqIDE_8.13+alpha.app/Contents
install -d bin/CoqIDE_8.13+alpha.app/Contents
OCAMLC    ide/coqide/macos_prehook.mli
sed -e "s/VERSION/8.12.90/g" ide/coqide/MacOS/Info.plist.template > bin/CoqIDE_8.13+alpha.app/Contents/Info.plist
install -d "bin/CoqIDE_8.13+alpha.app/Contents/MacOS"
OCAMLOPT  ide/coqide/macos_prehook.ml
install -d bin/CoqIDE_8.13+alpha.app/Contents/Resources/immodules
install -m 644 "/usr/local/Cellar/gtk+3/3.24.23/lib/gtk-3.0/3.0.0/immodules/"*.dylib bin/CoqIDE_8.13+alpha.app/Contents/Resources/immodules
install: /usr/local/Cellar/gtk+3/3.24.23/lib/gtk-3.0/3.0.0/immodules/*.dylib: No such file or directory
make[1]: *** [bin/CoqIDE_8.13+alpha.app/Contents/Resources/immodules] Error 71
make[1]: *** Waiting for unfinished jobs....
make: *** [submake] Error 2
```

Unless we can fix this issue or find another way to generate the bundle, we might have to ship 8.12.1 without a macOS installer (this is unfortunate because it usually receives many downloads according to GitHub's figures).

cc @Blaisorblade @MSoegtropIMC

**Comment by MSoegtropIMC** [comment]
What I would like to see is that we move to a more opam depext way of handling. This should also allow for switching between MacPorts and homebrew. I put quite a bit of effort into fixing Mac depext records in opam as part of the platform project. I planned to work on Mac and Windows installers during the CUDW. Or do you plan to release 8.12.1 before the CUDW?

**Comment by Zimmi48** [comment]
Yes, we plan to tag and release ASAP. I think we'll do so without a macOS installer and annonce that one may become available several weeks later.

**Comment by Zimmi48** [comment]
Anyway, I propose to merge the PR to fix the red CI issue.

**Comment by ejgallego** [comment]
I tried some workarounds indeed in the past but I didn't succeed; maybe we should have a virtualbox image so we can debug this more easily?

**Comment by Zimmi48** [comment]
We do have a machine now (check your email). But I don't have time to debug this anymore.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : if there is something I can do for Mac (besides working on the platform) please let me know. If it is about the installer, I guess I have to study how you did it in the past anyway.

**Comment by Zimmi48** [comment]
The problem with our current scripting for generating the installer is that it is old and nobody really understands it anymore. The best is certainly to work on a new script for the platform and, if it works, to use it to generate the 8.12.1 installer.
(Once the platform is ready with code to generate Windows and macOS installers, we should probably remove this code from Coq anyway.)

**Comment by Zimmi48** [comment]
ping @coq/ci-maintainers: this PR is ready to merge (it is best to go back to a green macOS CI without packaging that to keep a failing macOS CI, right?)

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
