### PR TITLE
Use closed_ts in flex_kind_of_term

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
LGTM, as we discussed with @mattam82, these subterms are evar-free, except for let-ins where the transparency status is not used.

**Comment by SkySkimmer** [comment]
Proj may have evars

**Comment by maximedenes** [comment]
> Proj may have evars

Oh, right! Maybe we should test whether the subterm is ground or not, in that specific case, and pick the transparency state accordingly.

**Comment by SkySkimmer** [comment]
@Zimmi48 incorrect failing check here

**Comment by maximedenes** [comment]
Bench shows only noise (from -0.14% to +0.31%).

**Comment by ppedrot** [comment]
@maximedenes this isn't surprising since AFAICT all instances of the codebase set `open_ts` and `closed_ts` to the same value?

**Comment by maximedenes** [comment]
> this isn't surprising since AFAICT all instances of the codebase set `open_ts` and `closed_ts` to the same value?

I see. However, this won't be the case anymore after https://github.com/coq/coq/pull/991

**Comment by maximedenes** [comment]
The more I look at the code, the less I understand about the `open_ts` vs `closed_ts` distinction. In particular, `open_ts` seems to be used with (potentially) closed terms in many places. But I'm not even sure why evarconv carries three transparent state in the first place.

**Comment by mattam82** [comment]
The motivation was maybe a bit clearer in unification.ml. The subterm_ts is quite special as it applies to the occurrence selection for higher-order unification problems, IIRC. I'd rather have a single transparent state instead of open_ts and closed_ts too, if that's not breaking everything.

**Comment by maximedenes** [comment]
After testing more, I think we should close this PR: it unfortunately makes `simple apply` perform some delta steps that it should not.

**Comment by SkySkimmer** [comment]
>After testing more, I think we should close this PR: it unfortunately makes simple apply perform some delta steps that it should not.

OK then

**Pull request closed without merging**
