### PR TITLE
[bench] Dump the vo size difference.

### PR DESCRIPTION
**Pull request by ppedrot**
It's useful.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Can we have it as a column in the big table?

**Comment by ppedrot** [comment]
That would require too much bash scripting of mine. I am happy with this patch since I have scripts to analyze the output, so if you want such a bleeding-edge feature I think I'd let you write it...

**Comment by ppedrot** [comment]
Hmm, the display script is actually written in OCaml, I can have a try.

**Comment by ppedrot** [comment]
... but what OCaml... I think I'd have preferred a bash script. The printing function is a mess, I'd have to rewrite it from scratch.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
