### PR TITLE
[experiment] Do not return the argument constr in check_and_clear functions.

### PR DESCRIPTION
**Pull request by ppedrot**
It was statically known to be the evar-expanded form of the argument. We also clean up the implementation and rely on the EConstr API.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/2007886390

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │    mem faults     │
│                             │                         │                                       │                                       │                          │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼───────────────────┤
│    coq-metacoq-translations │   19.47    19.71  -1.22 │    87495456218     88152437581  -0.75 │   152066858943    152107050760  -0.03 │  928848   928520    0.04 │   0    0      nan │
│     coq-metacoq-safechecker │  185.78   187.14  -0.73 │   847347716569    853574849113  -0.73 │  1126063605508   1125421020578   0.06 │ 1226188  1224716    0.12 │   0    0      nan │
│                   coq-color │  208.11   209.56  -0.69 │   940980139893    947719892516  -0.71 │  1318917975855   1318340526310   0.04 │ 1144720  1140444    0.37 │   0    0      nan │
│                 coq-bignums │   27.67    27.85  -0.65 │   126079320053    126759856721  -0.54 │   172219679520    172213030406   0.00 │  465024   466024   -0.21 │   0    0      nan │
│                  coq-stdlib │  401.13   403.29  -0.54 │  1655617810881   1659216768978  -0.22 │  1409059191342   1408904361757   0.01 │  597320   597648   -0.05 │   0    0      nan │
│                    coq-core │   95.02    95.53  -0.53 │   390511773239    387487599511   0.78 │   433163168854    433128555576   0.01 │  272756   272636    0.04 │   1    0      nan │
│  coq-performance-tests-lite │  771.41   774.21  -0.36 │  3501768698923   3515176155181  -0.38 │  5914012939312   5914527284470  -0.01 │ 1822076  1821952    0.01 │   0    0      nan │
│         coq-metacoq-erasure │   62.86    63.08  -0.35 │   282385081897    282706984819  -0.11 │   423582821692    423120089073   0.11 │ 1068460  1068428    0.00 │   0    0      nan │
│        coq-metacoq-template │   73.17    73.38  -0.29 │   326456777323    327363265872  -0.28 │   490041919380    489712866697   0.07 │  697600   699540   -0.28 │   0    0      nan │
│            coq-fiat-parsers │  331.79   332.60  -0.24 │  1495503158602   1498122447657  -0.17 │  2444558891767   2444675807390  -0.00 │ 2787580  2787544    0.00 │   0    0      nan │
│      coq-mathcomp-odd-order │  548.81   549.67  -0.16 │  2514418803254   2518358723575  -0.16 │  4255634568485   4255953257802  -0.01 │  932504   932252    0.03 │   0    0      nan │
│          coq-mathcomp-field │  111.56   111.72  -0.14 │   510810739063    511585370006  -0.15 │   837634198772    837569407027   0.01 │  649536   653564   -0.62 │   0    0      nan │
│           coq-metacoq-pcuic │  479.57   480.20  -0.13 │  2192187192687   2194715300185  -0.12 │  3091645065673   3088842584434   0.09 │ 1111304  1111592   -0.03 │   0    0      nan │
│               coq-fourcolor │ 1458.51  1459.92  -0.10 │  6655934656806   6663409164567  -0.11 │ 12082822058508  12082755484283   0.00 │  724500   724892   -0.05 │   0    0      nan │
│      coq-mathcomp-character │   75.79    75.86  -0.09 │   346712340893    347400912864  -0.20 │   525935212840    525759194439   0.03 │  733844   730560    0.45 │   0    0      nan │
│                coq-compcert │  278.67   278.89  -0.08 │  1265378786743   1264781119327   0.05 │  1877436785256   1876613123972   0.04 │ 1097792  1097836   -0.00 │   0    0      nan │
│                 coq-unimath │ 3629.11  3630.37  -0.03 │ 16598235132718  16602866519082  -0.03 │ 32970722970000  32968812480632   0.01 │ 3852884  3845752    0.19 │   0    0      nan │
│            coq-math-classes │   89.91    89.88   0.03 │   407458168701    407438756139   0.00 │   568734575567    568452349895   0.05 │  496248   495372    0.18 │   0    0      nan │
│                coq-coqprime │  180.59   180.37   0.12 │   825730146972    824991392607   0.09 │  1554913691032   1555199731126  -0.02 │  859196   910084   -5.59 │   0    0      nan │
│                    coq-hott │  152.74   152.48   0.17 │   692431961905    689935158381   0.36 │  1072899522971   1072487465854   0.04 │  571984   569760    0.39 │   0    0      nan │
│                  coq-geocoq │  692.46   690.98   0.21 │  3156698389944   3151193757179   0.17 │  4946010579581   4943343526551   0.05 │ 1078648  1075672    0.28 │   0    0      nan │
│                 coq-coqutil │   34.80    34.72   0.23 │   156882870035    156460974941   0.27 │   207648342669    207566442671   0.04 │  601012   601620   -0.10 │   0    0      nan │
│                coq-rewriter │  366.40   365.38   0.28 │  1671274987276   1665599659536   0.34 │  2717720810483   2715068849736   0.10 │ 1063568  1061116    0.23 │   0    0      nan │
│       coq-engine-bench-lite │  178.17   177.64   0.30 │   772007052313    771008618421   0.13 │  1486889650818   1489457319068  -0.17 │ 1172708  1176880   -0.35 │   0    0      nan │
│             coq-fiat-crypto │ 2804.37  2794.51   0.35 │ 12754771436266  12714450125950   0.32 │ 23292068261820  23282191778915   0.04 │ 3844840  3881200   -0.94 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  909.92   906.10   0.42 │  4152291110795   4136127139146   0.39 │  7151917641257   7149689560755   0.03 │ 1216072  1216816   -0.06 │   0    0      nan │
│           coq-iris-examples │  425.54   423.70   0.43 │  1938219762853   1930114223712   0.42 │  2916604316461   2915603930079   0.03 │ 1172944  1173340   -0.03 │   0    0      nan │
│                  coq-flocq3 │   76.75    76.41   0.44 │   349500174214    347486535449   0.58 │   455141428595    454994166867   0.03 │  988628   990476   -0.19 │   0    0      nan │
│               coq-fiat-core │   53.77    53.52   0.47 │   234627275256    233578230022   0.45 │   321742207775    321679362259   0.02 │  476844   475824    0.21 │   0    0      nan │
│        coq-mathcomp-algebra │   63.87    63.56   0.49 │   291599960936    290655821454   0.32 │   397624082290    397639251880  -0.00 │  554780   555144   -0.07 │   0    0      nan │
│       coq-mathcomp-solvable │   87.52    87.09   0.49 │   400306212797    398750842853   0.39 │   611036509889    611034679726   0.00 │  671248   668368    0.43 │   0    0      nan │
│       coq-mathcomp-fingroup │   23.68    23.56   0.51 │   108338500114    107398869364   0.87 │   155925601886    155957045568  -0.02 │  482884   483504   -0.13 │   0    0      nan │
│                   coq-verdi │   48.21    47.92   0.61 │   218623149968    217455646014   0.54 │   322199463780    321984797455   0.07 │  833556   831384    0.26 │   0    0      nan │
│      coq-mathcomp-ssreflect │   26.22    26.04   0.69 │   119506002340    118346066658   0.98 │   148238164988    148208364579   0.02 │  531324   532328   -0.19 │   0    0      nan │
│               coq-perennial │ 3981.20  3953.49   0.70 │ 18177897784137  18049078956586   0.71 │ 29831779055649  29807022643656   0.08 │ 2595612  2604924   -0.36 │   0    3  -100.00 │
│              coq-coquelicot │   34.49    34.20   0.85 │   154704672102    154144382417   0.36 │   201635256500    201572314248   0.03 │  747384   745984    0.19 │   0    0      nan │
│                     coq-vst │ 1058.92  1049.93   0.86 │  4831117219875   4788407452034   0.89 │  7799132523661   7793080902118   0.08 │ 1900796  2140316  -11.19 │   3   23   -86.96 │
│              coq-verdi-raft │  564.08   558.91   0.93 │  2574994573916   2551479856317   0.92 │  3943566668388   3940965823989   0.07 │ 1230272  1229396    0.07 │   0    0      nan │
│                    coq-corn │  761.03   753.16   1.04 │  3470754377337   3434713908869   1.05 │  5275236574741   5274876966368   0.01 │  873752   873704    0.01 │   0    0      nan │
│                coq-bedrock2 │  322.44   194.77  65.55 │  1474347071017    889507223056  65.75 │  3145643278070   1615999350499  94.66 │ 2049400  2049360    0.00 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴───────────────────┘
```
WTF bedrock2???

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by JasonGross** [comment]
The error in iris is an output test failing, not an error from coqc, so the minimizer cannot minimize it.

Are you sure the bench got the same version of bedrock2 both times?  Line 325 is the `end` in
```
all :
    try match goal with
    |- mmio_event_abstraction_relation _ _ =>
        (left+right); eexists _, _; split; exact eq_refl
    end.
```
which does not look like it should be that slow, but 329 is right in the middle of a `match` branch: https://github.com/mit-plv/bedrock2/blob/482051f434e4672c99b21df2fc3c2a3eaadaad5d/bedrock2/src/bedrock2Examples/lightbulb.v#L329. I thought the time for lines in the middle of statements should not be reported at all?

**Comment by ppedrot** [comment]
Line numbering is not the syntactic one, it corresponds to
```coq
all : repeat trans_ltu;
repeat match goal with
| H : word.unsigned ?v <> 0 |- _ =>
    let v := rdelta.rdelta v in
    let __ := lazymatch v with if word.eqb _ _ then word.of_Z 1 else word.of_Z 0 => I end in
    eapply Properties.word.if_nonzero in H; eapply word.eqb_true in H
| H : word.unsigned ?v = 0 |- _ =>
    let v := rdelta.rdelta v in
    let __ := lazymatch v with if word.eqb _ _ then word.of_Z 1 else word.of_Z 0 => I end in
    eapply Word.Properties.word.if_zero in H; eapply word.eqb_false in H
end;
repeat match goal with x := _ |- _ => subst x end;
repeat match goal with H : _ |- _ => rewrite !byte_mask_byte in H end.
```
I can reproduce locally.

**Comment by ppedrot** [comment]
@JasonGross that's the only hypothesis I can think of.

**Pull request closed without merging**
