### PR TITLE
use List.In_dec for ListSet.set_In_dec

### PR DESCRIPTION
**Pull request by haansn08**
`List.v` already had a proof for  `ListSet.set_In_dec`.

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
I'm OK with this, just unsure about keeping the proof in one line. @coq/stdlib-maintainers what do you think?

**Review by olaure01 — APPROVED** [review]

**Comment by olaure01** [comment]
While cleaning this file, wouldn't it be natural to use `set_In` in a systematic way rather than `In` as it is the case in some statements (e.g. `set_add_iff`, `set_remove_*`, etc.)?

**Comment by Alizter** [comment]
@haansn08 ping

**Comment by haansn08** [comment]
@Alizter @olaure01 pong. Do you want me to replace every `In` with `set_In` as part of this PR?

**Comment by Alizter** [comment]
@haansn08 I guess that is what @olaure01 is asking, but I don't think it has to come in this PR. Can you open a new one with the suggested cleanups?

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
