### PR TITLE
Add compatibility Nonrecursive Elimination Schemes

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by herbelin** [comment]
Looks like this request should indeed be integrated to next 8.5 patch level release.

**Comment by JasonGross** [comment]
What's blocking this from being merged? / Who is responsible for this bit?

**Comment by herbelin** [comment]
Nothing was blocking to my knowledge. Guillaume was the one to commit the compat file. Let's forward the decision of merging to him if he is ok.

**Comment by JasonGross** [comment]
@silene ?

**Comment by silene** [comment]
Merged. Thanks.

**Comment by JasonGross** [comment]
Thanks!

**Pull request closed without merging**
