### PR TITLE
Kernel: split reduction.ml to have conversion-related functions in conversion.ml

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlays:
- https://github.com/ejgallego/coq-serapi/pull/329
- https://github.com/damien-pous/relation-algebra/pull/39
- https://github.com/Mtac2/Mtac2/pull/378
- https://github.com/unicoq/unicoq/pull/82
- https://github.com/mattam82/Coq-Equations/pull/544
- https://github.com/LPCIC/coq-elpi/pull/451
- https://github.com/smtcoq/smtcoq/pull/119

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
A lot of consequences but I like the idea.

**Review by ppedrot — APPROVED** [review]
I like this.

**Comment by ppedrot** [comment]
@SkySkimmer the overlay for stmcoq hasn't been pushed to github it seems.

**Comment by ppedrot** [comment]
Still broken, and https://github.com/SkySkimmer/smtcoq is still a 404.

**Comment by ppedrot** [comment]
Merging soon.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
