### PR TITLE
Add a "Show Proof Diffs" message to the XML protocol

### LINKED ISSUE #12800: Need a way to support commands accessing Stm history in XML interface
Currently there are a few commands that access `Stm` history that are only available in `coqtop` and in Proof General (which uses `coqtop`) but not CoqIDE.  These are `Show Proof Diffs` (diffs on the `Show Proof` output) and `Show Goal`, which are executed in `Coqloop.process_toplevel_command`.  There's also an open issue #10020 to show diffs in the proof context in the `Show` command that might require handling that command similarly.

I'd like to address this in 8.13, adding support for these in the XML interface if not `coqtop` as well.  IIUC, @erikmd has someone working on finishing up the previously stalled XML interface for PG.  Losing support for these commands in PG with XML would delay the adoption and perhaps the completion of the PG XML changes.  Erik et al already added an optional window in PG to automatically display the `Show Proof Diffs` output for use in teaching Coq.

In #10020 I suggested a simple approach that @ejgallego doesn't like that a couple of the other developers thought was reasonable.  I don't mind doing something a bit different, but it's not reasonable to say that XML interface operations can never access Stm history.

@ejgallego how do you suggest we address this?  Perhaps we can figure it out in this issue.  If need be, we can discuss on a call when those resume in September.

cc: @gares

### PR DESCRIPTION
**Pull request by jfehrle**
Work in progress, just going step by step.

@gares Perhaps you can save me a good bit of time puzzling through the CoqIDE code.  How can I have `Coqide.show_proof_diffs` send a message so the Coq side routine `Idetop.proof_diffs` and then get back the return value on the CoqIDE side?  This is only to test my protocol addition.  For the moment, I just want to pass a string and get a string back.  Later, the return value will be a `Pp.t` and I'll have the latter routine call command code elsewhere in Coq.

Fix #12800

### CODE REVIEW

**Comment by gares** [comment]
I think you should copy the code of `Query.query` which implements a family of commands
https://github.com/coq/coq/blob/40285cd17ee2721362f4b72122a4d8f6306e2aed/ide/coqide/coqide.ml#L712
You should add some code in coqOps.ml and coq.ml, the former can find the tip of the document (I guess you need that state id, the raw_coq_query code)
https://github.com/coq/coq/blob/40285cd17ee2721362f4b72122a4d8f6306e2aed/ide/coqide/coqOps.ml#L357
while the latter should contain a en try point for your protocol message
https://github.com/coq/coq/blob/40285cd17ee2721362f4b72122a4d8f6306e2aed/ide/coqide/coq.ml#L509

**Comment by Zimmi48** [comment]
Note that you pushed your branch to the upstream repo directly. If this PR is a WIP and thus not going to be merged very soon, then I suggest you delete the branch and reopen it from your fork.

**Comment by jfehrle** [comment]
Whoops.  Is there a simple way to preserve the comments here after creating a new branch?

**Comment by jfehrle** [comment]
Is there a way to disable creating branches directly in master without losing some essential capability?  If people merge with coqbot then seems like there's less need to do that.

**Comment by Zimmi48** [comment]
Unfortunately no to both questions. Deleting the branch will close the PR forever. And the ability to push new branches cannot be dissociated from the "write access" permission that allows contributors to, e.g., edit comments (such as the ones by @coqbot imported from Bugzilla).

**Pull request closed without merging**
