### PR TITLE
Cleanup of ltac cmxs

### PR DESCRIPTION
**Pull request by letouzey**
In the previous setting, all plugins/ltac/*.cmxs except ltac_plugin.cmxs
 (for instance coretactics.cmxs, g_auto.cmxs, ...) were utterly bogus :
  - wrong -for-pack used for their inner .cmx
  - dependency over modules not provided (for instance Tacenv, that ends
    up being a submodule of the pack ltac_plugin).
 But we were lucky, those files were actually never loaded, thanks to the
 several DECLARE PLUGIN inside coretactics and co, that end up in ltac_plugin,
 and hence tell Coq that these modules are already known, preventing
 any attempt to load them.

 Anyway, this commit cleans up this mess (thanks PMP for the help)

### CODE REVIEW

**Comment by letouzey** [comment]
Updated version:
  - coqdep wasn't handling correctly `Local Declare ML Module`
  - anyway, `Local Declare ML Module "tauto_plugin"` wasn't working correctly, let's remove the `Local`

**Comment by letouzey** [comment]
Updated test-suite

**Comment by letouzey** [comment]
Updated test-suite, bis (3469.v was still broken).

**Review by ppedrot — APPROVED** [review]
I confirm that this patch is sound to my eyes.

**Comment by maximedenes** [comment]
@letouzey Something strange is going on with HoTT, could you have a look?

**Comment by maximedenes** [comment]
Sorry, closed by mistake.

**Comment by ejgallego** [comment]
HoTT needs a patch to its own version of Notations.

**Comment by Zimmi48** [comment]
@ejgallego That would be great if you could fix HoTT ASAP as currently all PR builds are failing due to this. Thanks!

**Comment by ejgallego** [comment]
I can't test the fix now; but it should be very simple; just sync `Notations.v` HoTT's copy with Coq's, feel free to submit a PR to my repo.

**Comment by Zimmi48** [comment]
Submitted PR ejgallego/HoTT#8.

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
