### PR TITLE
Understand covariant inductive cumulativity in evarconv

### LINKED ISSUE #16872: Type inference / universe algorithm forbids perfectly valid definition when identity function is removed
#### Description of the problem

```coq
Local Set Universe Polymorphism.
Cumulative Inductive TM@{t} : Type@{t} -> Type :=
(* Monadic operations *)
| tmReturn {A:Type@{t}}
  : A -> TM A
| tmBind {A B : Type@{t}}
  : TM A -> (A -> TM B) -> TM B
.
Definition _lift@{a u1 u2} {A : Type@{a}} : TM@{u1} A -> TM@{u2} A := fun x => x.
Definition tmFix_body@{a b f1 f2 fx fr}
           {A : Type@{a}} {B : Type@{b}} (f : (A -> TM@{f1} B) -> (A -> TM@{f2} B))
           (tmFix : unit -> A -> TM@{fx} B)
  : A -> TM@{fr} B
  := f (fun a => tmBind@{fr} (tmReturn@{fr} tmFix) (fun tmFix => _lift (tmFix tt a))).
Definition tmFix_body'@{a b f1 f2 fx fr}
           {A : Type@{a}} {B : Type@{b}} (f : (A -> TM@{f1} B) -> (A -> TM@{f2} B))
           (tmFix : unit -> A -> TM@{fx} B)
  : A -> TM@{fr} B
  := f (fun a => tmBind@{fr} (tmReturn@{fr} tmFix) (fun tmFix =>       (tmFix tt a))).
(* Error:
In environment
A : Type
B : Type
f : (A -> TM B) -> A -> TM B
tmFix : unit -> A -> TM B
a : A
tmFix0 : unit -> A -> TM B
The term "tmFix0 tt a" has type "TM@{fx} B" while it is expected to have type
"TM@{fr} ?B" (universe inconsistency: Cannot enforce fx = fr because fr < fr = fx).
*)

```

Interestingly, if I use the term printed by
```coq
Set Printing Implicit.
Set Printing Universes.
Section foo. Universes a b f1 f2 fx fr. Compute @tmFix_body@{a b f1 f2 fx fr}. End foo.
```
Coq is perfectly happy to accept
```coq
Definition tmFix_body'@{a b f1 f2 fx fr}
  := fun (A : Type@{a}) (B : Type@{b}) (f : (A -> TM@{f1} B) -> A -> TM@{f2} B)
         (tmFix : unit -> A -> TM@{fx} B) =>
       f
         (fun x : A =>
            @tmBind@{f1} (unit -> A -> TM@{fx} B) B
                   (@tmReturn@{f1} (unit -> A -> TM@{fx} B) tmFix)
                   (fun x0 : unit -> A -> TM@{fx} B => x0 tt x)).
```
Coq in fact still accepts it if I remove most type annotations, as in
```coq
Definition tmFix_body'@{a b f1 f2 fx fr}
  := fun (A : Type@{a}) (B : Type@{b}) (f : (A -> TM@{f1} B) -> A -> TM@{f2} B)
         (tmFix : unit -> A -> TM@{fx} B) =>
       f
         (fun x =>
            @tmBind@{f1} _ B
                   (@tmReturn@{f1} _ tmFix)
                   (fun x0 => x0 tt x)).
```
But if I remove the `B` to `tmBind`, I get
```coq
Definition tmFix_body'@{a b f1 f2 fx fr}
  := fun (A : Type@{a}) (B : Type@{b}) (f : (A -> TM@{f1} B) -> A -> TM@{f2} B)
         (tmFix : unit -> A -> TM@{fx} B) =>
       f
         (fun x : A =>
            @tmBind@{f1} (unit -> A -> TM@{fx} B) _
                   (@tmReturn@{f1} (unit -> A -> TM@{fx} B) tmFix)
                   (fun x0 : unit -> A -> TM@{fx} B => x0 tt x)).
(* Error:
In environment
A : Type@{a}
B : Type@{b}
f : (A -> TM@{f1} B) -> A -> TM@{f2} B
tmFix : unit -> A -> TM@{fx} B
x : A
x0 : unit -> A -> TM@{fx} B
The term "x0 tt x" has type "TM@{fx} B" while it is expected to have type
"TM@{f1} ?B" (universe inconsistency: Cannot enforce fx = f1 because f1 < f1 = fx).
*)
```

What's going on?

#### Coq Version

8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16872

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
I don't want to deal with overlays so I reverted the API change

**Comment by ppedrot** [comment]
@SkySkimmer a rebase would probably help.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
The CI failures are unrelated. @Zimmi48 I'll tag this as backportable to 8.17 since it's a fix but feel free to postpone it.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
