### PR TITLE
Remove pidetop from CI

### PR DESCRIPTION
**Pull request by maximedenes**
pidetop relies on some rather low level API from STM, which we'd like to
change. It does not seem maintained much anymore, and still hasn't moved
to github.

If more information is required, I think @gares can describe the situation more precisely.

### CODE REVIEW

**Comment by maximedenes** [comment]
The motivation for this change is to make upcoming work like #9019 easier, by not having to maintain pidetop on our side (by submitting overlays to bitbucket, etc).

On the other hand, I'll be happy to provide assistance to UI maintainers if they need to adjust code to API changes.

**Review by ejgallego — DISMISSED** [review]
I don't think allow failures makes a lot of sense here; we rather support `pidetop` or we rather remove it in full. What is the point of having a zombie here?

Regarding what to do, @gares indeed has the word on that.

**Comment by maximedenes** [comment]
> I don't think allow failures makes a lot of sense here; we rather support `pidetop` or we rather remove it in full. What is the point of having a zombie here?

Ok, removing it is also fine with me. Will update the patch.

**Comment by maximedenes** [comment]
@ejgallego updated to remove rather than allowing failures

**Review by ejgallego — COMMENTED** [review]
Up to @gares to decide, CI changes are OK.

**Comment by gares** [comment]
The plan is to restore the Coqoon backend speaking the XML protocol, since the PIDE one is shaky.
The XML protocol never went away fully, and the code is parametrized by that, so it should be doable, and in the future it should be doable to plug LSP in there. @ale-f did not manage to update the XML protocol to the current variant yet. When it will be done I think we should probably unplug pidetop.

I'd personally like to see at least the failure we have today on pidetop while changing the STM API, so maybe allowed-failures is a reasonable compromise in the meanwhile.

**Comment by ejgallego** [comment]
It was not clear from your message @gares if you approve this PR or not. What should we do?

Except for very specific, special cases (*), I'm afraid that `allow_failure: true` is not an allowed situation for a CI entry; if we know a CI is broken we are not gonna launch hundredths of useless jobs for them to fail.

If the plan is allow `pidetop` to be broken for some time and then to rewrite that's fine; we can remove it now, and add it back later on.

(*) So far we are allowing bedrock first because it mostly succeeds, and second because of a bug they cannot implement the proper fix [sadly the Coq PR has been complicated to get thu] Also, we will allow OCaml trunk to fail for obvious reasons, but even this job should mostly succeed once we polish the details, otherwise it should be removed.

**Comment by gares** [comment]
Pidetop is broken by a pr of Maxime, if I can write a fix easily then it can stay. But I need to see the failure, the pr is not up to date so I don't know if it is fixable. Please don't merge it now

**Comment by maximedenes** [comment]
> Pidetop is broken by a pr of Maxime, if I can write a fix easily then it can stay. But I need to see the failure, the pr is not up to date so I don't know if it is fixable. Please don't merge it now

I think there's a misunderstanding. I expect the failure to be easy to fix, it is not the motivation of this PR. The motivation is the cost (in terms of delay) of porting an unmaintained interface to a new API, especially by means of overlays.

But maybe I should reverse the question: why am I expected to do the porting or wait for somebody to do it each time I touch an STM API? What's the goal, since as you say, the whole thing is probably going to be replaced.

**Comment by maximedenes** [comment]
I believe it would be a better strategy to save my time and let me help porting Coqoon to LSP when the time comes.

**Review by gares — APPROVED** [review]

**Comment by ejgallego** [comment]
Ok, I understand @gares green tick as an indication to go ahead with this PR then. Will merge later today.

**Comment by herbelin** [comment]
Actually, do we have an idea of how many people are using Coqoon? Is it used e.g. for teaching? Do we have an idea of the plans of the developers of Coqoon?

If needed, a concrete agreement could maybe then be made with them on helping them to rebind Coqoon on top of LSP?

**Comment by gares** [comment]
> Do we have an idea of the plans of the developers of Coqoon?

I meant *their* plan in:

> The plan is to restore the Coqoon backend speaking the XML protocol, since the PIDE one is shaky.
> The XML protocol never went away fully, and the code is parametrized by that, so it should be doable, and in the future it should be doable to plug LSP in there. @ale-f did not manage to update the XML protocol to the current variant yet. When it will be done I think we should probably unplug pidetop.

**Review by ejgallego — APPROVED** [review]
Merging as per upstream-author.

**Comment by herbelin** [comment]
@gares: Thanks.

I have many other questions which may however require to enter technical details. So, if ever you have time for explaining, is there a way to summarize the (conceptual) defects / advantages of pidetop wrt the xml protocol (independently of the cost of maintenance of this or that proposal)?

If too complicated, don't worry.

**Comment by maximedenes** [comment]
> I have many other questions which may however require to enter technical details. So, if ever you have time for explaining, is there a way to summarize the (conceptual) defects / advantages of pidetop wrt the xml protocol (independently of the cost of maintenance of this or that proposal)?

Could we move this discussion somewhere else?

**Comment by herbelin** [comment]
> Could we move this discussion somewhere else?

Sure, maybe on #9012? Or another issue? The UIs issues are so fascinating. There are so much to do, and very interesting things to do.

How to proceed? Do I let you open a new issue? Do we let @gares open an issue if he wants to contribute?

**Comment by maximedenes** [comment]
> Sure, maybe on #9012? Or another issue? The UIs issues are so fascinating. There are so much to do, and very interesting things to do.

I guess it depends what you want to ask about. If your questions are related to the LSP server, #9012 seems like the right place. Otherwise, just open a new issue.

**Pull request merged**
