### PR TITLE
Hint Opaque/Transparent/Unfold: don't error on Opaque Defined constants

### PR DESCRIPTION
**Pull request by SkySkimmer**
Helps with #12566

### CODE REVIEW

**Comment by ppedrot** [comment]
This is consistent with the semantics of the plain `Opaque` command, but I think you shouldn't even error on opaque constants since they might be instantiated later on if this command is called inside a functor.

**Comment by gmalecha** [comment]
Would it make sense to warn (rather than error) on inductives, constructors, axioms, etc? I'm thinking of instances where you have a wrapper like:

```coq
Inductive t' := ...
Definition t := t'
```

(perhaps because you're working in a module and the kernel doesn't allow instantiating `Parameter`s with `Inductive`). And then at some point this changes (e.g. you move your code out of the module) and now everyone's code breaks when it really doesn't need to.

**Comment by SkySkimmer** [comment]
>This is consistent with the semantics of the plain Opaque command, but I think you shouldn't even error on opaque constants since they might be instantiated later on if this command is called inside a functor.

That would be something like 
~~~coq
Module Type T. Parameter x : nat. End T.
Module F(A:T). Hint Opaque A.x. End F.
~~~
?

Is that really useful?

**Comment by ppedrot** [comment]
> Is that really useful?

I am just mentioning that if you don't do it then it's a known bug...

**Comment by ppedrot** [comment]
@SkySkimmer I think you've screwed up your rebasing.

**Comment by SkySkimmer** [comment]
It was github bugging out AFAICT

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@ppedrot would you like to take this PR?

**Comment by ppedrot** [comment]
Will merge soon.

**Pull request merged**
