### PR TITLE
Typeclasses debug: use registered printer for CannotUnify

### PR DESCRIPTION
**Pull request by SkySkimmer**
This makes the printing in #17323 more sensible.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by Blaisorblade** [comment]
Could this be backported to 8.17.1? At least it cherry-picks cleanly...

**Comment by SkySkimmer** [comment]
Are we doing a 8.17.1? cc @Zimmi48

**Comment by Zimmi48** [comment]
Sure, we can.

**Pull request merged**
