### PR TITLE
Fix #11553: magicaly_constant_of_fixbody checks existence of made up constant

### LINKED ISSUE #11553: (8.11.0) cbn gives Anomaly on mutual inductives, mutual fixpoints and typeclasses
#### Description of the problem

```coq
From Coq Require Import Utf8.
From Autosubst Require Export Autosubst.

Inductive tm : Type :=
  | tv : vl_ -> tm
 with vl_ : Type :=
  | var_vl : var -> vl_
  | vabs : tm -> vl_.

Definition vl := vl_.

Fixpoint tm_rename (sb : var → var) t : tm :=
  let a := tm_rename : Rename tm in
  let b := vl_rename : Rename vl in
  match t with
  | tv v => tv (rename sb v)
  end
with
vl_rename (sb : var → var) v : vl :=
  let a := tm_rename : Rename tm in
  let b := vl_rename : Rename vl in
  match v with
  | var_vl x => var_vl (sb x)
  | vabs t => vabs (rename (upren sb) t)
  end.

Instance rename_vl : Rename vl := vl_rename.

Lemma foo ξ x: rename_vl ξ (var_vl x) = var_vl x.
(* Succeeds *)
cbn. Abort.

Lemma foo ξ x: rename ξ (var_vl x) = var_vl x.
(* Fails *)
cbn.
```

```coq
File "./theories/DSub/syn/syn.v", line 135, characters 2-53:
Error:
Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."
Please report at http://coq.inria.fr/bugs/.

Command exited with non-zero status 129
```

The crash survives dropping `tv` and `vabs`, but it disappears when making `vl_rename` not mutually recursive.

#### Coq Version

8.11.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fixes #11553

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by Blaisorblade** [comment]
I confirm this patch also fixes the original, unminimized codebase.

**Comment by ejgallego** [comment]
Thanks @Blaisorblade for the detailed bug report analysis.

**Comment by Blaisorblade** [comment]
Just for the record, what I tested was  https://github.com/Blaisorblade/coq/commit/ddd8b2a229159078e4199ececf67dd2a01f47d08 — luckily, a pretty straight backport.

**Comment by ppedrot** [comment]
No need to wait, it's trivial. And it also reminds us that using exceptions for control should be shunned.

**Pull request merged**
