### PR TITLE
Clean-up Travis folds.

### PR DESCRIPTION
**Pull request by Zimmi48**
This has become mostly garbage since GitLab CI became our main CI platform.

### CODE REVIEW

**Comment by ejgallego** [comment]
Umm, why did they bothered you? `bot`-related?

**Comment by Zimmi48** [comment]
No, I just stumbled upon them while looking at this file. I don't mind closing the PR if you'd rather keep them.

**Comment by ejgallego** [comment]
> No, I just stumbled upon them while looking at this file. I don't mind closing the PR if you'd rather keep them.

I don't mind either way, I was just wondering if the PR arose from a `bot` need.

**Review by SkySkimmer — APPROVED** [review]
Fine with me.

**Pull request merged**
