### PR TITLE
Use a proper data type to collect tactic errors

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** code organization

Depends on #11735 (merged).

We introduce a type `tactic_error` embedded into `exn` using a constructor `TacticError` and encapsulate all calls to `user_err` in `tactics.ml` into a constructor of `tactic_error`. In particular, this delays the printing to the moment we really need to display the error message.

We merge some similar error messages in passing.

~~Unfortunately, we need to inform `catchable_error` of the existence of this new constructor of exceptions, so we use an extra encapsulation into a new `Catchable` exception known from `catchable_exception`.~~ Resolved thanks to #11735.

In passing, we also reduce a complex filtering of exceptions in `apply` into a `catchable` filtering, hoping that this is compatible.

Since some of the error messages used to silently prepare printing of terms at every backtracking step, this may locally have some impact on efficiency (?).

### CODE REVIEW

**Review by ppedrot — DISMISSED** [review]
Please don't add another layer of exception mangling. This is the purpose of `TacticException` already, and if you think there should be more catchable exceptions, you should remove the call to `catchable_exception` in `tclTRY` and consorts instead.

**Comment by herbelin** [comment]
> Please don't add another layer of exception mangling. This is the purpose of `TacticException` already, and if you think there should be more catchable exceptions, you should remove the call to `catchable_exception` in `tclTRY` and consorts instead.

You mean `TacticFailure`? I understood from your gitter message that it was a "panic" exception, but I may have misunderstood.

Testing whether removing `catchable_exception` in `tclTRY` does not give surprises is fine to me.

**Comment by ppedrot** [comment]
There is no need to wrap anything in the monad, because backtracking exceptions are never handled by try-with blocks. The `TacticException` block is used for fatal exceptions raised with the monadic raise, and which are never supposed to be caught outside of toplevel. I don't know why `tclTRY` is secretly doing its little cooking, but I suspect that this is legacy code that is safe to remove.

**Comment by herbelin** [comment]
@ppedrot:

Side remark about terminology: when you say `TacticException` you apparently mean `Exception` (should we rename it?) which is indeed a "meta-level" exception shortcutting the normal flow of the monadic execution (which already has its own backtrack continuation).

> if you think there should be more catchable exceptions, you should remove the call to catchable_exception in tclTRY and consorts instead.

We could do that, but we have no control on what third-party do. If they themselves use `catchable_exception`, we have to tell them to use instead `noncritical`. (Assuming that I understood correctly what you have in mind.)

**Comment by ppedrot** [comment]
I think I was not clear, but my point is that as long as you only use the monadic interfaces (i.e. no OCaml raise / try-with) then you should never have to call `catchable_exception`. Even `noncritical` is handled by the basic combinators, so it should never evaluate to false for exceptions manipulated by the tactic layer.

**Comment by herbelin** [comment]
Not using OCaml's `raise` means using `tclZERO` right?

But old code for tactics (and pretyping as well) uses OCaml's `raise` (fortunately turned into `tclZERO` by `nf_enter`).

Are you saying that we want to tell to all third-party developers of tactics (and to us as well), that we should use only `tclZERO`? Why not, but this is a significant move for all the plugin community.

**Comment by ppedrot** [comment]
There is indeed leeway to use the OCaml `raise` *in some well-defined situations only*. Typically, in the closure argument of `nf_enter`, as you highlighted. This has been done in order to ensure backwards compatibility with the previous tactic engine. But that's about it, otherwise you're likely to wreak havoc with the invariants.

**Comment by ppedrot** [comment]
Anyway, the bottom line is that `catchable_exception` must die and be replaced by a mixture of `noncritical` and decreasing of `TacticFailure`.

**Comment by herbelin** [comment]
> Anyway, the bottom line is that `catchable_exception` must die and be replaced by a mixture of noncritical and decreasing of `TacticFailure`.

(Here, you obviously mean `FailError` rather than `TacticFailure`.)

I'm ok to make the move of deprecating `catchable_exception`.

Anyway, this will not solve the issue of this PR which is that adding this new exception `TacticError` is liable to break third-party code if they do a `Proofview.tacORELSE`/`tclOR`/`tclIFCATCH` testing `UserError` or `catchable_exception`.

So, proposal:
- We deprecate `catchable_exception` together with a message telling to use instead... what actually? `tclORELSE`?
- Plus, in case `tclORELSE` is used, to take care that some former `UserError` are now `TacticError` (which can be easier matched).

Is that OK?

**Comment by ppedrot** [comment]
I believe this PR was superseded by #11735, so let's close it.

**Comment by herbelin** [comment]
> I believe this PR was superseded by #11735, so let's close it.

No, no. This PR will include #11735 and it is still doing more (i.e. introducing a new type constructor, different from `UserError` for the errors of `tactics.ml`). It is needing #11735 so that this new type constructor is not rejected by the too-restrictive `catchable_exception` which #11735 deprecates in the API and remove in the codebase.

**Review by ppedrot — COMMENTED** [review]
I support the reification of tactic errors as data, but I don't like the fact that these errors are all grouped together into an inductive type. This is pretending that tactics form an organized, self-contained system, but  this is clearly not true. Contrastingly, in the kernel it makes sense to have an algebraic type of error, since this is a closed code over which we have full control. Furthermore, this is introducing unneeded coupling in the code, what if we want to move some tactics around?

Although more unwieldy, I think it would be better to declare a unique exception for each error and register them individually via `CErrors.register_handler`. Or alternatively, define the `tactic_error` type as an open inductive type.

**Comment by herbelin** [comment]
Isolated exceptions would be ok. The problem I saw is that the error printer is sequential, so, we would lose direct access to the relevant exception printer.

My primary purpose was to avoid the `Pp.t` messages to be built uselessly, which I think is important. Any other solution is ok. For instance, how would you provide an open type?

**Comment by ppedrot** [comment]
> For instance, how would you provide an open type?

There is support for that [since OCaml 4.02](https://caml.inria.fr/pub/docs/manual-ocaml/extensiblevariants.html).

**Comment by herbelin** [comment]
How would you register a new handler with an extensible type? Either you add a new mechanism of extensibility of pattern-matching over the type `tactic_error` (with the cost of implementing this mechanism), or you extend directly the `CErrors` printer (with the same effect of a pattern-matching linear in the number of errors to know which printer to use).

Alternatively, would it be a problem to see the `tactic_error` type to be the type of errors possibly returned by the tactics implemented in the `tactics` directory, without pretending more than that? Of course, it may depend on what are the future plans in term of organization of tactics though.

**Comment by ppedrot** [comment]
You're right, indeed. Then maybe design a system à la `CWarnings` relying on our own dynamic type...

**Comment by ppedrot** [comment]
For the time being, I think we shouldn't bother too much and stick to the dialect used so far, that is, create a new exception and register a handler for it. In practice, the fact that handling exceptions is linear in the number of register handlers shouldn't be a performance issue since this printing only happens when reaching toplevel and not in tight loops.

**Comment by ejgallego** [comment]
Indeed , the key point here is to have tactics avoid calling the print routine at all costs. I've removed myself quite a few of these calls.

**Comment by herbelin** [comment]
> For the time being, I think we shouldn't bother too much and stick to the dialect used so far, that is, create a new exception and register a handler for it. In practice, the fact that handling exceptions is linear in the number of register handlers shouldn't be a performance issue since this printing only happens when reaching toplevel and not in tight loops.

I agree that in practice, error printing is mostly used once, or interactively, and that even browsing say 500 exceptions would be mostly imperceptible. Nevertheless, I find it a bit inelegant. Moreover, I think a bit of structure among exceptions is good, so I'd prefer to have an extensible type of tactic errors than having everything flat.

Incidentally, what I did is rather naive. Some further merges between errors could be done, like merging `AlreadyUsed` and `IntroAlreadyDeclared` which are basically the same, which is not very different also in spirit from the multiple `already exists` errors which we can find elsewhere in vernac code. More structure could be added too to group errors into well-formedness errors, dependency errors, name errors, .... And this is not independent of the question of documenting errors. I'm getting a bit confused about what would be the best compromise to do at the current stage.

**Review by maximedenes — COMMENTED** [review]
@herbelin I see that you added the `needs:progress` flag. How about turning this PR into a draft until it is ready for review?

**Review by ejgallego — APPROVED** [review]
LGTM, thanks. Will merge tomorrow.

Indeed, would be nice to continue work in #12602 to address the comments made, but this PR is actually very helpful IMHO as to port the errors to the open mechanism.

**Review by ppedrot — APPROVED** [review]
I think that the big monolithic handler is a bit ugly but it's better now than before, so let's merge indeed.

**Comment by herbelin** [comment]
I don't know what to conclude from the bench: +6.40 for bedrock2, -3.81 for verdi-raft.

**Comment by ejgallego** [comment]
> I don't know what to conclude from the bench: +6.40 for bedrock2, -3.81 for verdi-raft.

The beckrock stuff looks very fishy, can we repeat that one?

**Comment by herbelin** [comment]
I tried to browse a few files of bedrock2 in the job artifact but that's not easy by hand. Globally it looks faster on the average everywhere there is a peak. Could it be possible that one file has a big slowdown. I suspect that @ppedrot has tools to pinpoint these kinds of things (??).

**Comment by ppedrot** [comment]
There are only two slow lines in bedrock2, but the difference is huge.
```
html/coq-bedrock2/bedrock2/src/bedrock2Examples/lightbulb.v.html:678 6.40 3.66 10.06 (175%)
html/coq-bedrock2/bedrock2/src/bedrock2Examples/lightbulb.v.html:685 13.33 10.60 23.93 (126%)
```
First one is
```
    eapply lightbulb_loop_ok;
    (eapply recvEthernet_ok || eapply lightbulb_handle_ok);
        eapply lan9250_readword_ok; eapply spi_xchg_ok;
        (eapply spi_write_ok || eapply spi_read_ok).
```
and second one is
```
    eapply lightbulb_init_ok; eapply lan9250_init_ok;
    try (eapply lan9250_wait_for_boot_ok || eapply lan9250_mac_write_ok);
    (eapply lan9250_readword_ok || eapply lan9250_writeword_ok);
        eapply spi_xchg_ok;
        (eapply spi_write_ok || eapply spi_read_ok).
```

Meanwhile, the major speed up in verdi is concentrated in one line in absolute value
```
html/coq-verdi-raft/raft-proofs/LogMatchingProof.v.html:1190 -18.05 38.97 20.91 (-46%)
```
which is
```
intuition; prep_packets.
```
but there are quite a few other speed-ups of smaller absolute magnitude (< 0.5s).

I believe that the bedrock2 lines should be investigated. It might be the case that a stray exception is caught, leading to weird codepaths being taken.

**Comment by ppedrot** [comment]
The two bedrock2 lines are passing their time in `Tactics.try_red_apply`. There is probably something going wrong with the try-with block there, triggering a quadratic behaviour. We should match on the exception instead of making the recursive call inside the block...

**Comment by herbelin** [comment]
Since this is about `apply`, it is probably related to the first commit of the PR (f4fd9fd0) which "simplified" a `tclORELSE`. The argument of the second tactic is potentially costly to build. I made #14820.

Thanks for your help.

**Comment by herbelin** [comment]
By the way, it seems we did not adopt a strategy about filtering specific exceptions (with the risk of missing somes) and filtering all non-critical exceptions (with a loss of information about what exceptions can really occur). How to take a decision on this kind of matter.

**Comment by JasonGross** [comment]
My gut response is that we should almost never be filtering on specific exceptions, except insofar as the exception is meant to communicate a particular sort of return value (e.g. `Not_found` from `find`).  Certainly in all the cases where we're filtering rather than handling, we should have a comment, ideally a separate filtering function, indicating what the subset of errors being filtered is.

**Comment by ppedrot** [comment]
This is the good old "exceptions for control flow are evil" adage. When one wants to discriminate return values, they should use algebraic datatypes instead.

**Pull request merged**
