### PR TITLE
[ci] bump elpi

### PR DESCRIPTION
**Pull request by gares**
overlay:
- https://github.com/LPCIC/coq-elpi/pull/564
- https://github.com/math-comp/hierarchy-builder/pull/406

### CODE REVIEW

**Comment by gares** [comment]
@CohenCyril this PR requires to merge the PR on HB which requires 8.18 + coq-elpi 2.0.
Do you think it is reasonable?

 We have then to make a release which will work on 8.18 and 8.19 (just tgged), using coq-elpi 2.0.0/2.0.1.

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
Dear @coq/ci-maintainers this PR is ready.

**Comment by gares** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
