### PR TITLE
ci-bedrock2: understand DOWNLOAD_ONLY

### PR DESCRIPTION
**Pull request by SkySkimmer**
not sure how I missed this

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
This is what we said in the original PR, this code workflow can only be kept sane by a miracle, we need to move to a different setup where each script provides methods that are called by the top-level driver.

**Comment by SkySkimmer** [comment]
@ejgallego assign?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
will merge soon

**Comment by ejgallego** [comment]
> @ejgallego assign?

Yes, sorry I forgot to merge indeed.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
