### PR TITLE
Increase the time limit on 4366.v to make gitlab work better.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
output-modulo-time/ltacprof_cutoff.v also does strange things sometimes but I don't have a clue what the output-modulo-time tests do.

**Comment by maximedenes** [comment]
In an offline discussion, @ppedrot claimed that the bug reported forced him to add this test case, whereas he thought timing-based test cased were too fragile. Then we discovered he was the bug reporter...

So I guess it means we can safely merge this.

**Comment by JasonGross** [comment]
It'd be nice to test this against the version of Coq that occurred before the bug was fixed, and make sure that the test still fails there.

**Comment by JasonGross** [comment]
Re output-modulo-time, the intent is to test the Ltac profiler, in particular prevent regressions against the formatting of the table, and the counts of tactics.  Unfortunately, the times need to be stripped off the outputs, and the results need to be sorted, and there are occasionally issues with zeros... I suspect this would be much easier to test in the xml protocol, if we get a structured table back.

**Comment by herbelin** [comment]
An alternative to better love 4366.v is	to move it to the test-suite complexity with a line of the form
```coq
(* Expected time < 1.00s *)
```
and time will be adjusted to the bogomips of the current machine.

Not an absolute answer but I'm satisfied by it in general for a threshold chosen to clearly separate classes of complexity up to error margin.

**Comment by herbelin** [comment]
Was this the "right" solution to a recurrent problem?

**Comment by ejgallego** [comment]
> Was this the "right" solution to a recurrent problem?

I am afraid I don't see a right solution here; whatever method we use today may be invalidated by the next processor family; (more centralized) manual tweaking of a scale factor seems like the way to go.

**Comment by Zimmi48** [comment]
@herbelin Would it make sense to move *all* of the `Timeout` test files to the complexity setting you mentioned? (And to document it and to prohibit new additions of test files with timeouts?)

**Comment by herbelin** [comment]
I don't know of a "right" solution in the absolute, but it seems that the way the `complexity` directory is made does not raise the problems that test `4366.v` is regularly raising. Do I miss something?

**Comment by SkySkimmer** [comment]
How reliable are the timeout tests and the complexity tests? ie what's their history of catching/not catching performance regressions?

**Comment by maximedenes** [comment]
> I don't know of a "right" solution in the absolute, but it seems that the way the complexity directory is made does not raise the problems that test 4366.v is regularly raising. Do I miss something?

Sorry, I forgot to write a comment saying that I was merging this because it is a strict improvement over what was done before, and spurious test failures are really annoying. But if we have a better solution, it can be merged at any time, of course.

I've heard @ppedrot say that bogomips were not reliable, but I know nothing about it.

**Comment by herbelin** [comment]
@maximedenes: Ah sorry, I thought you were opposed to merge things which were strict improvements while still being improvable :smile:

About bogomips, I'm not expert at all. But empirically, an approximative relative value seems to work better than an absolute value.

**Comment by maximedenes** [comment]
> @maximedenes: Ah sorry, I thought you were opposed to merge things which were strict improvements while still being improvable

Then you misunderstood what I said.

**Pull request merged**
