### PR TITLE
Fix for bug 5507. Mispelt de Bruijn.

### PR DESCRIPTION
**Pull request by Zimmi48**
Fix for https://coq.inria.fr/bugs/show_bug.cgi?id=5507

### CODE REVIEW

**Comment by herbelin** [comment]
Incredible that we succeed to do so many times this mispelling.

While we are at it, why not to add systematically a space between then "de" and "Bruijn"?

As for the writing "de" vs "De", I always wondered. I don't know the experience of @ppedrot, but for "Nicolaas Govert de Bruijn", Dutch colleagues write "à la de Bruijn", "de Bruijn factor", "by de Bruijn", "de Bruijn indices" or sometimes "de Bruijn's indices", so I would say that "de" should be lowercase.

**Comment by Zimmi48** [comment]
I've added a second commit for moving to a more consistent writing (I agree that we should prefer having the space and the lowercase "de"). I've kept the two commits separate because only the first one corresponds to the fix of bug 5507.

**Comment by maximedenes** [comment]
@herbelin Does this now look good to you?

**Comment by herbelin** [comment]
Sure! But maybe you should also ask all persons of the group as pernickety as me on this kind of subject, whether it is ok for them, as I don't feel having a priori more right nor knowledge nor legitimity than any other one to tell if a spelling is good in the absolute.

We could also ask @JasonGross.

Well, ok, on the other side, there are more interesting things to discuss, so let's merge it.

**Comment by Zimmi48** [comment]
Yeah, let's not lose time trying to get a consensus on such trivialities.

**Comment by maximedenes** [comment]
Sure, I was asking a confirmation because Hugo had already commented on it. Thanks!

**Pull request merged**
