### PR TITLE
Tweak the implementation of reduce_to_atomic_ind.

### PR DESCRIPTION
**Pull request by ppedrot**
Small cleanup attempt from my git attic. This patch reduces the amount of code calling the dreaded `hnf_constr` function, replacing it with a nicer `whd_all`.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
The relation-algebra bug is essentially an issue with the refolding performed by `intro`. The previous code was refolding while now it doesn't anymore. Minimal example:
```
Fixpoint In {A : Type} (a : A) (l : list A) {struct l} : Prop :=
match l with
| nil => False
| cons b m => b = a \/ In a m
end.

Goal forall b l, In true (cons b l) -> True.
Proof.
intros b l.
intros [?|?].
+ constructor.
+ Fail progress change (In true l) in H.
Abort.
```
I guess we critically rely on this behaviour, so this PR is doomed...

**Comment by SkySkimmer** [comment]
Doomed indeed.

**Comment by ppedrot** [comment]
Maybe we can salvage the first commit, it's a standalone patch that doesn't change the semantics.

**Pull request closed without merging**
