### PR TITLE
Add .byte targets for every bestocaml target

### PR DESCRIPTION
**Pull request by SkySkimmer**
This makes it easier to compile our executables for debug purposes.

### CODE REVIEW

**Comment by Zimmi48** [comment]
I lack Makefile-reader power and I have always been a bit lost among all the developer-friendly targets we provide. Maybe this could be a good opportunity to start a small documentation about them? (In `dev/doc`.) If you don't have the will to do this, can you at least explain quickly how to use what this PR provides?

**Comment by Zimmi48** [comment]
BTW, is it really useful to backport this PR given that most of the development today happens on master?

**Comment by SkySkimmer** [comment]
This started when investigating #7413, I added the coqdep target, did `make bin/coqdep.byte` then ran ocamldebug on it.

**Comment by Zimmi48** [comment]
I guess I see then. This might semantically "conflict" with #6859 BTW.

**Comment by gares** [comment]
> This might semantically "conflict" with #6859 BTW.

I see conflicts, but why "semantic"?

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
> Maybe this could be a good opportunity to start a small documentation about them

To my eyes this PR just adds `make bin/whatever.byte` targets, so nothing very unexpected.

**Review by ejgallego — COMMENTED** [review]
Note that with Dune support coming soon, developers will almost always better served by using the builtin support for this kind of stuff it does provide.

So indeed we could consider whether we want to spend a lot of time tweaking the complex make setup.

**Comment by Zimmi48** [comment]
> To my eyes this PR just adds make bin/whatever.byte targets, so nothing very unexpected.

Indeed.

> I see conflicts, but why "semantic"?

Well, it seems that all the new `.byte` targets are added manually. When #6859 is merged there will be more executable files, so more potential `.byte` which won't have been added. I'm saying all this with a very remote perspective though (as I said before, I don't understand and don't want to understand Makefile language. I'm very eager for Dune to be our main build system because it also means I won't have to understand that part of the code).

**Comment by gares** [comment]
> I'm very eager for Dune to be our main build system because it also means I won't have to understand that part of the code

I guess you will have to understand dune.

I'm fine postponing the merge of this PR until #6859 is merged not to cause conflicts if @SkySkimmer is fine with it.

**Comment by SkySkimmer** [comment]
>I'm fine postponing the merge of this PR until #6859 is merged not to cause conflicts if @SkySkimmer is fine with it.

I don't understand that PR but it seems to have had some issues getting merged.

**Pull request merged**
