### PR TITLE
Use a linear-time register allocation algorithm for the native compiler.

### PR DESCRIPTION
**Pull request by ppedrot**
This was only available starting from OCaml 4.06 but now we require 4.09.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by Alizter** [comment]
Very impressive!

**Comment by ppedrot** [comment]
It's probably just testing compilation though. In theory linscan produces slightly less efficient code, the tradeoff being a shorter compilation time. Once again, we lack a proper native bench to really assess the changes.

**Comment by SkySkimmer** [comment]
The top slowdown (from rewriter) is a native_compute call so probably shows that lesser efficiency. Some of the other slowdowns are probably similar.

**Comment by ppedrot** [comment]
Closing this for now.

**Comment by ejgallego** [comment]
Actually the flags passed to ocamlopt should be configurable by the users, that could have a great impact on some cases. But I guess the request can come from the users themselves.

**Pull request closed without merging**
