### PR TITLE
[stm] Remove support for .vio files

### LINKED ISSUE #4007: "Error: Attempt to save an incomplete proof" are tied to the wrong line number on [coqc -quick]
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#4007
From: @JasonGross
Reported version: 8.5
CC:   @ejgallego

### LINKED ISSUE #4013: Request for a variant of [par: abstract (...)] that defers proof obligations in -quick mode
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#4013
From: @JasonGross
Reported version: trunk
CC:   @gares

### LINKED ISSUE #4123: .vio files should be smaller
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#4123
From: @JasonGross
Reported version: 8.5
CC:   @charguer, @ejgallego, @ppedrot, @RalfJung

### LINKED ISSUE #5223: coqc: flag to ignore .vo (load .vio)
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5223
From: @hendriktews
Reported version: 8.5
CC:   @gares, @silene, @RalfJung

### LINKED ISSUE #5308: Quick compilation: unlocalized error
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5308
From: @fblanqui
Reported version: 8.6
CC:   @ejgallego, @gares, @fblanqui

### LINKED ISSUE #6720: -schedule-vio2vo is broken on Windows
#### Version

git master

#### Operating system
Windows

#### Description of the problem

Running `make quick && make vio2vo`, the second step fails saying
```
make[1]: Leaving directory '/cygdrive/c/projects/coq/test-suite/coq-makefile/vio2vo/_test'
make[1]: Entering directory '/cygdrive/c/projects/coq/test-suite/coq-makefile/vio2vo/_test'
"/cygdrive/c/projects/coq/bin/coqc"  -q  -I src  -R src test -R theories test  \
	-schedule-vio2vo 2 theories/test.vio
Error:
Anomaly "Uncaught exception Invalid_argument("Unix.wait not implemented")."
Please report at http://coq.inria.fr/bugs/.
```

### LINKED ISSUE #8402: Coq -schedule-vio2vo reports errors as warnings
#### Version

8.8.1

#### Operating system

Linux

#### Description of the problem

```bash
$ cat bar.v
Theorem t : True.
Proof.
  Fail exact I.
Qed.
$ coqc -q -quick bar.v; echo $?
0
$ coqc -q -quick -schedule-vio2vo 3 bar.vio; echo $?
File "./bar.v", line 3, characters 2-15:
Warning: File ./bar.v: proof of t: chars 27-40 The command has not failed!
1
```

Perhaps this is so that multiple errors can be reported on a single run, but it is a bit confusing.

### LINKED ISSUE #9637: [ci] build:quick takes around 3 hours to complete sometimes.
Sometimes, the `build:quick` job takes around 3 hours to complete. Examples:
- https://gitlab.com/coq/coq/-/jobs/166438863
- https://gitlab.com/coq/coq/-/jobs/166471390

IMHO this makes the job fail the "reasonable build time" clause of the CI rules, thus we I suggest we place it on a 30-days quarantine, and if the problem is not fixed, remove.

### LINKED ISSUE #11471: 8.11+beta1: please document -quick/-vio and interaction with -vos
#### Description of the problem

I really appreciate the precise documentation of `-vos`/`-vok`, especially what files they read and produce! I would suggest to also document to following points:

- option `-quick` : What does it do? Can it still be used?
- interaction of `-quick` and `-vos`: Can one use `-vos` on a file of which some dependencies have been compiled with `-quick`?
- consistency guarantees with `-vok`: Section "Compiled interfaces (produced using -vos)" contains a warning about missing universe constraints when using `-vos`. I would suggest to change `Technically, when using -vos,` into `Technically, when using -vos and/or -vok`, to make it very clear that checking all proofs with `-vok` does not guarantee consistency.

#### Coq Version

This is about the documentation https://coq.github.io/doc/v8.11/refman/practical-tools/coq-commands.html in the version of January 28, 2020.

### PR DESCRIPTION
**Pull request by ejgallego**
As discussed in https://github.com/coq/coq/wiki/Coq-Call-2023-07-11 , we do this PR as a first step to evaluate what are the gains when removing `.vio` files.

Due to #4123, it is not likely that `.vio` files are useful in practice, and `.vos` files provide a viable alternative (as outlined in the original vos PR)

Moreover, we have no plans to address the remaining vio bugs in the issue tracker.

This PR:

- closes #4007
- closes #4013
- closes #4123
- closes #5308
- closes #5223
- closes #6720
- closes #8402
- closes #9637 
- closes #11471
- closes #18380

Related: #5388 #6710

See also the previous attempt: #8767 #8783

### CODE REVIEW

**Comment by ejgallego** [comment]
As discussed in the call, I'm proposing this for merge.

Will update the docs / changelog once the decision is taken.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by SkySkimmer** [comment]
>+100 −1,112

That's a nice diffstat indeed

**Comment by ejgallego** [comment]
> > +100 −1,112
> 
> That's a nice diffstat indeed although I guess a lot is from the test suite ;)

Indeed it is not the panacea but IMO helps a little bit.

More detailed `diffstat`:
```
- checker: 3 files changed, 24 insertions(+), 38 deletions(-)
- kernel: 2 files changed, 7 insertions(+), 18 deletions(-)
- library: 2 files changed, 2 insertions(+), 3 deletions(-)
- vernac: 6 files changed, 17 insertions(+), 84 deletions(-)
- stm: 5 files changed, 20 insertions(+), 387 deletions(-)
- toplevel: 6 files changed, 7 insertions(+), 194 deletions(-)
- tools: 6 files changed, 13 insertions(+), 125 deletions(-)
- test-suite: 21 files changed, 4 insertions(+), 201 deletions(-)
```

**Review by gares — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
mtac2 failure looks unrelated

@coqbot merge now

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
We will see if anyone complains 
- before the RC
- between RC and release
- after the release

;)

**Pull request merged**
