### PR TITLE
Fixed many typos and grammar errors in chapter 11 of the manual.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is #6796. It has been waiting for too long for a review. I did review it and I fixed a small mistake which made the compilation fail. Now everything is good and this should be mergeable without risk.

### CODE REVIEW

**Comment by maximedenes** [comment]
I would prefer to integrate this on the fly with the sphinx migration. Will take care of it.

**Comment by Zeimer** [comment]
@maximedenes 
> I would prefer to integrate this on the fly with the sphinx migration. Will take care of it.

So this means I should go on with the rest of the fixes, yeah? Which workflow would you prefer: one pull request per chapter of the manual, or one big pull request with everything?

**Comment by maximedenes** [comment]
@Zeimer Ideally, it would be better to do the fixes after the migration is complete. I hope to integrated all ported chapters next week.

But if there are some fixes you already did, please submit one PR per chapter, it would be easier to try to port the fixes themselves to Sphinx.

Thanks!

**Comment by Zeimer** [comment]
@maximedenes 

I didn't do any fixes in the meantime and I will wait until the port is complete. Hope this Sphinx stuff will be easier to compile than the current documentation.

**Comment by Zimmi48** [comment]
> I would prefer to integrate this on the fly with the sphinx migration. Will take care of it.

Since you didn't take care of it, I did. This is once again @Zeimer's fixes but ported to the new Sphinx chapter.

**Review by maximedenes — APPROVED** [review]
Looks very good, thanks a lot!

**Pull request merged**
