### PR TITLE
A temporary fix of #13018 and #12775 for branch 8.12

### LINKED ISSUE #12775: Parens not printing right in custom grammar
In 8.12, there is a printing bug involving parens that turns one of SF's associativity lemmas into nonsense:

     Theorem seq_assoc : forall c1 c2 c3,
       cequiv [[(c1;c2);c3]] [[c1;(c2;c3)]].

becomes

     1 subgoal (ID 47)
  
       c1, c2, c3 : com
       st, st' : state
       ============================
       st =[ c1; c2; c3 ]=> st' <-> st =[ c1; c2; c3 ]=> st’

I believe Hugo understands what the problem is already, but I can provide more details if needed.

### LINKED ISSUE #13018: custom entry without explicit level prints as constr instead
#### Description of the problem

If a notation specifies a subexpression as `x custom entry gargs` without an explicit level, `x` is still printed as if it was `constr` even in contexts where `constr` is not accepted by the grammar. This results in surprising cases where an expression is parsed and printed, but the resulting string cannot be parsed again.

```coq
browse@ashryn ~ % cat /tmp/ee.v
Undelimit Scope list_scope.
Declare Custom Entry gnat.
Declare Custom Entry gargs.

Notation "!" := 42 (in custom gnat).
Notation "gargs:( e )" := e (e custom gargs).
Notation "( x )" := (cons x (@nil nat)) (in custom gargs, x custom gnat).
Notation "( x , y , .. , z )" := (cons x (cons y .. (cons z nil) ..))
  (in custom gargs, x custom gnat, y custom gnat, z custom gnat).

Check gargs:( (!) ). (* cons 42 nil *)
Check gargs:( (!, !, !) ). (* cons 42 (42 :: 42 :: nil) *)

Definition OnlyGargs {T} (x:T) := x.
Notation "OnlyGargs[ x ]" := (OnlyGargs x) (at level 10, x custom gargs).
Check OnlyGargs[ (!) ]. (* OnlyGargs[ cons 42 nil] *)

Declare Custom Entry gargs999.
Notation "gargs999:( e )" := e (e custom gargs999 at level 999).
Notation "( x )" := (cons x (@nil nat)) (in custom gargs999, x custom gnat at level 999).
Notation "( x , y , .. , z )" := (cons x (cons y .. (cons z nil) ..))
  (in custom gargs999, x custom gnat at level 999, y custom gnat at level 999, z custom gnat at level 999).

Check gargs999:( (!) ). (* gargs999:( (!)) *)
Check gargs999:( (!, !, !) ). (* gargs999:( (!, !, !)) *)
Check OnlyGargs[ (!) ]. (* OnlyGargs[ gargs999:( (!))] *)

Definition OnlyGargs999 {T} (x:T) := x.
Notation "OnlyGargs999[ x ]" := (OnlyGargs999 x) (at level 10, x custom gargs999 at level 999).
Check OnlyGargs999[ (!) ]. (* OnlyGargs999[ (!)] *)
```

#### Coq Version

`The Coq Proof Assistant, version 8.12.0 (August 2020)
compiled on Aug 29 2020 11:02:15 with OCaml 4.11.0`

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

We arbitrarily use max_int as higher level of custom entries in printing, which should be ok since only `<` and `<=` are used to decide when to use coercions.

Fixes #12775
Fixes #13018 

- [X] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

**Comment by herbelin** [comment]
@jasongross: coq_tools fails. When I replay on my computer it fails but not exactly the same. It seems to fail with #13027 too. Is it correct to suspect that this is unrelated to this particular PR?

**Comment by SkySkimmer** [comment]
Is this supposed to be 8.12 only?

**Comment by herbelin** [comment]
> Is this supposed to be 8.12 only?

Yes.

**Comment by JasonGross** [comment]
Sorry, I missed the tag until just now.  The coq-tools failure was a transient state where I accidentally pushed before testing.  It should be fixed now, if you retry it.

**Comment by ejgallego** [comment]
> > Is this supposed to be 8.12 only?
> 
> Yes.

@herbelin the PR is targetting master, shouldn't you then target the 8.12 branch?

**Comment by herbelin** [comment]
Indeed, sorry about it. (And sorry about the number of review requests the change of base induced.)

**Comment by ejgallego** [comment]
Thanks @herbelin , will merge once CI is OK.

**Comment by ejgallego** [comment]
@coqbot: merge now

Note that the bugs should be fixed by a commit targetting `master`

**Comment by Zimmi48** [comment]
I am quite worried about this PR having been merged in `v8.12` only while the same bugs have not been fixed in `master`. What was the problem exactly with merging in `master` and backporting (the usual process) even though a "better" fix was to be eventually merged in `master`?

The problems with the current approach are:
- if the fix for `master` was not eventually merged or delayed for too long, then we would introduce a regression between 8.12 and 8.13
- we also have to manually check that the test cases for #13026 and #13025 are exactly the same
- finally, the changelog entry is in `v8.12` only which breaks the workflow for preparing the release notes as those are prepared in the `master` branch first (for good reasons).

For all those reasons, 8.12.1 cannot be released until #13025 is merged in `master` (with the exact same test cases *and* exact same changelog entry). In particular, when I say "exact same changelog entry" I mean the changelog entry from #13026, i.e. same file name and same content.

**Comment by ejgallego** [comment]
Good point @zimmi48 , I suggest we also merge this or in master and have @herbelin rebase the other one on top.

In fact the original setup to target master made sense, sorry it was a bad idea to change base branch

**Comment by herbelin** [comment]
So, is that correct that I have nothing to do until this PR (#13026) is also merged to master? (And then I'm rebasing #13025 to factor the test suite and change log.)

**Comment by Zimmi48** [comment]
This is OK to me. @herbelin you would still need to reopen a PR corresponding to commit c55f520032492ac203a0533c88ecc6c850217be0, i.e. your branch when it was still targeting `master` so that @ejgallego can merge it.

**Comment by ejgallego** [comment]
This has landed on `master`, thanks folks.

**Comment by Zimmi48** [comment]
@herbelin I found a way to avoid triggering many code owner review requests when changing the target branch of a PR: turn it into a draft first. See https://github.com/coq/coq/pull/12919#event-3798248356.

**Pull request merged**
