### PR TITLE
Fix ring/field in sections

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

This fixes the bug reported by @VincentSe at [#12409](https://github.com/coq/coq/pull/12409#issuecomment-633700593): `ring` not cleaning its auxiliary lemmas at the end of a section.

There is a drawback to the fix: it turns the auxiliary lemmas as local definitions. Thus, they appear in the local context of goals...

Has anyone another fix to propose? We could e.g. add an information to local definitions of a section telling that they should not be visible in the goal (when non dependent)?

- [X] Added / updated test-suite
- [ ] Entry added in the changelog

### CODE REVIEW

**Comment by VincentSe** [comment]
:+1:

**Comment by VincentSe** [comment]
Why do the auxiliary lemmas show in sections, but are hidden when the rings are added globally ? Can't you use the same hiding mechanism ?

**Comment by SkySkimmer** [comment]
Shouldn't we get fresh names instead of forcing to discharge the lemmas?

**Comment by herbelin** [comment]
@SkySkimmer:
> Shouldn't we get fresh names instead of forcing to discharge the lemmas?

We could... something would still leak unexpectedly though.

Another alternative is that `Add Ring` is always discharged...

@VincentSe:
> Why do the auxiliary lemmas show in sections, but are hidden when the rings are added globally ? Can't you use the same hiding mechanism ?

This is a convention for goals: we copy the dischargable part of the section context in the goal but not the part which survives the section.

**Comment by ejgallego** [comment]
After a quick review it seems to me that this change may be too risky for 8.12, what do you think @Zimmi48 ?

**Comment by herbelin** [comment]
> After a quick review it seems to me that this change may be too risky for 8.12, what do you think @Zimmi48 ?

It is not a very invalidating limitation, and a better fix could be done. I moved the milestone to 8.13.

**Comment by ejgallego** [comment]
> It is not a very invalidating limitation, and a better fix could be done. I moved the milestone to 8.13.

Thanks for the quick feedback @herbelin

**Comment by herbelin** [comment]
Any further comments about this PR? Here is my analysis of the situation and possible solutions:
1. to generate fresh names at each new `Add Ring` so that the residual of a previous `Add Ring` in section is not blocking a new declaration in another section; the drawback is that we add new lemmas to the name space which we don't want to see;
2. add a flag to local definitions to tell they should not appear in the goal context; this seems a bit ad hoc, so one could wonder whether there would be other applications;
3. add a flag to global definitions to tell to discharge them anyway; but this defeats the purpose of distinguishing local and global definitions;
4. instead of building an auxiliary lemma we could inline the lemma in the proof produced by `ring`; but that seems to defeat the purpose of sharing this lemma over several uses of `ring` in the section (expanding the 1st lemma would e.g. replace the application of the lemma to 7 arguments by an application to arguments involving 75 global references); note that option 2. would do the same actually, at the level of a declaration;
5. expecting the user to give explicitly the names for the lemmas at the time of `Add Ring`; but this seems to force the user to be aware of something which could be kept hidden.

I'm really satisfied with none of the solutions. 

I'm currently leaning towards implementing either 1. (with a name of the form `sectionname_ringname_lemma`) or 4. (with the recommendation for efficiency to instead use the parametric ring feature).

**Comment by ppedrot** [comment]
> add a flag to local definitions to tell they should not appear in the goal context; this seems a bit ad hoc, so one could wonder whether there would be other applications;

I think I mentioned it during the call, but for a cleaner handling of hints-as-globals, one would need a way to introduce let-bindings that are inlined after section closing. Those needs look similar.

**Comment by herbelin** [comment]
> > add a flag to local definitions to tell they should not appear in the goal context; this seems a bit ad hoc, so one could wonder whether there would be other applications;
> 
> I think I mentioned it during the call, but for a cleaner handling of hints-as-globals, one would need a way to introduce let-bindings that are inlined after section closing. Those needs look similar.

And you don't want them to be shown in the goal context too?

If yes, would you see the information directly in the name_context or in a table outside the kernel?

**Comment by herbelin** [comment]
@ppedrot:

> If yes, would you see the information directly in the named_context or in a table outside the kernel?

Then, I'm leaning to add a new Boolean in `Decls.variable_data`.

**Comment by herbelin** [comment]
It now depends on #12855. I'll do the overlays once it is clear that adding an argument to `Discharge` to tell if the declaration is to be made visible in goal is an ok way to go.

**Comment by herbelin** [comment]
Relying rather on #12890.

**Pull request closed without merging**
