### PR TITLE
[ssr] when porting v8.2 code no backtracking point has to be added

### LINKED ISSUE #12837: [ssr] regression in error reporting on name reuse after case with coq-8.12
#### Description of the problem

When running the following in coq-8.12 
```coq
Require Import ssreflect.
Goal forall p : nat * nat , True.
case => x x.
```
I get the following obscure error message:
```
Error: Could not fill dependent hole in "apply"
```
In coq-8.11, I get the expected error:
```
Error: x already used
```
Note: `move=> [x x].` and `case; move=> x x.` behave the same, while `case. move => x x.` yields the expected "x already used" error even on 8.12.  :fearful: 

#### Coq Version

8.12

### PR DESCRIPTION
**Pull request by gares**
Amends c1b1afe76e1655cc3275bdf4215f0ab690efc3cc
Fix #12837

### CODE REVIEW

**Comment by gares** [comment]
CC @ppedrot 

I think the choice `tclOR` v.s. `tclORELSE` is quite poor, and the root of this bug.

In particular `tclOR` is just an alias for `plus` which is the new backtracking "or", and nobody would have used it while porting v8.2 code, since back than there was no `plus`.

Should we ditch the alias and just keep `plus`?

**Review by ppedrot — APPROVED** [review]

**Comment by gares** [comment]
Thanks @ppedrot , you may have want to assign to this one.
Any opinion about the API name? The `tclOR` name is not used very much:
```shell
gares@ollypat:~/COQ/master$ git grep tclOR\ 
engine/proofview.ml:(** [tclOR t1 t2] behaves like [t1] as long as [t1] succeeds. Whenever
engine/proofview.ml:let tclOR = Proof.plus
engine/proofview.ml:        tclOR (tclUNIT x) (fun e -> aux (n+1) (k e))
engine/proofview.ml:  let (<+>) t1 t2 = tclOR t1 (fun _ -> t2)
engine/proofview.mli:(** [tclOR t1 t2] behaves like [t1] as long as [t1] succeeds. Whenever
engine/proofview.mli:val tclOR : 'a tactic -> (Exninfo.iexn -> 'a tactic) -> 'a tactic
engine/proofview.mli:  (** {!tclOR}: [t1+t2] = [tclOR t1 (fun _ -> t2)]. *)
plugins/firstorder/g_ground.mlg:  Proofview.tclOR begin
plugins/ltac/tacinterp.ml:  Proofview.tclOR tac (fun exn ->
plugins/ltac/tacinterp.ml:      Tacticals.New.tclOR (interp_tactic ist tac1) (interp_tactic ist tac2)
plugins/ltac/tactic_matching.ml:    { stream = fun k ctx -> Proofview.tclOR (k x ctx) (fun e -> (pick l e).stream k ctx) }
plugins/ltac/tactic_matching.ml:            | Some nctx -> Proofview.tclOR (k lhs nctx) (fun e -> (map s e).stream k ctx)
plugins/ltac/tactic_matching.ml:      Proofview.tclOR (head.stream k ctx) (fun e -> (tail e).stream k ctx)
plugins/ltac/tactic_matching.ml:      Proofview.tclOR (head.stream k ctx) (fun e -> (tail e).stream k ctx)
plugins/ssr/ssrcommon.ml:  Proofview.tclOR (applyn ~with_evars ~first_goes_last ~with_shelve:true ?beta n (EConstr.of_constr oc))
plugins/ssr/ssrequality.ml:    Proofview.tclOR cvtac begin function
tactics/class_tactics.ml:    let ortac = if backtrack then Proofview.tclOR else Proofview.tclORELSE in
tactics/class_tactics.ml:      Proofview.tclOR (hints_tac hints info kont)
tactics/class_tactics.ml:                      (fun e -> Proofview.tclOR (intro info kont)
tactics/class_tactics.ml:      else tclOR (t depth) (function
tactics/class_tactics.ml:    let tac = Proofview.tclOR tac error in
tactics/tacticals.ml:  let tclOR t1 t2 =
tactics/tacticals.mli:  val tclOR : unit tactic -> unit tactic -> unit tactic
tactics/tactics.ml:  Proofview.tclOR (clear [id])
user-contrib/Ltac2/tac2core.ml:    Proofview.tclOR (return ans) (fun _ -> of_ans s)
user-contrib/Ltac2/tac2core.ml:    Proofview.tclOR (return ans) (fun _ -> of_ans s)
user-contrib/Ltac2/tac2core.ml:  Proofview.tclOR (thaw x) (fun e -> Tac2ffi.apply k [Value.of_exn e])
user-contrib/Ltac2/tac2core.ml:      Proofview.tclOR tac wrap >>= fun () ->
user-contrib/Ltac2/tac2match.ml:    { stream = fun k ctx -> Proofview.tclOR (k x ctx) (fun e -> (pick l e).stream k ctx) }
user-contrib/Ltac2/tac2match.ml:            | Some nctx -> Proofview.tclOR (k (Some (Lazy.force m_ctx)) nctx) (fun e -> (
```
which also makes me think the same bug was introduces in ssrequality...

**Comment by ppedrot** [comment]
No preference for the name, but since we tend to call tacticals `tclSOMETHING` it'd be weird to special case this one.

**Comment by gares** [comment]
The let's call is `tclPLUS`.

My problem is that I think that 2 bugs were introduces just because `tclOR` and `tclORELSE` are very similar words with very similar meaning but not at all alike in the semantics of the proof engine.

**Comment by ppedrot** [comment]
Actually, I am surprised that `tclOR` doesn't work as intended in this case. I guess I have to think harder about the semantics of backtracking.

**Comment by gares** [comment]
The problem is `+` and `;`.
The code of SSR was already using the new `;` in, morally, `case ; move=> x; move=> x`.
Your commit changed things to `(apply term_implementing_case + error "cannot apply"); move=> x; move=> x`.
The second move fails, but there is still a choice point. The fact that the RHS of `+` is `error` and not `apply another_term_that_may_work` is what makes this behavior totally unwanted. If we had the venerable `!` or Prolog, one could write `((apply term_implementing_case; !) + error "cannot apply")` which is morally the implementation of what we call "if then else" in a regular PL.

**Comment by gares** [comment]
But again, if you port V82 code, why would you add a `+` ? I think you did it mostly by "autocompletion", hence my proposal to rename the operator so that it does not happen again.

**Comment by ppedrot** [comment]
No, I did it willingly. The problem is that `tclORELSE` does not behave correctly when applied to multisuccess tactics, and I thought that `tclOR` followed by a `tclZERO` would essentially rename the exception when applied to a zero-success tactic but it seems it's not the case.

**Comment by gares** [comment]
> The problem is that `tclORELSE` does not behave correctly

What do you mean? That is does stop at the first solution? ;-)

**Comment by ppedrot** [comment]
Obviously that depends what you want to do, but my gut feeling is that if magically ssr becomes overly backtracking one day we'll have strange error messages again.

**Comment by gares** [comment]
Do you think `tclOR` was "misused" elsewhere?
I don't see how this problem applies to SSR in particular.

**Comment by JasonGross** [comment]
> In particular `tclOR` is just an alias for `plus` which is the new backtracking "or", and nobody would have used it while porting v8.2 code, since back than there was no `plus`.

I believe there's a difference between`+` and `plus`, which is that the former focuses (and hence does not work on multigoal tactics) while the latter does not focus.

> The problem is that `tclORELSE` does not behave correctly when applied to multisuccess tactics

I think there's a different primitive that you want here, which is neither `tclOR` nor `tclORELSE`: I think the actual primitive here should take the same arguments, say `tac1` and `tac2` as these two combinators, but the semantics should be "if `tac1` has any successes, then the result is all of the successes of `tac1`; if `tac2` has no successes, then it behaves as `tac2`".

**Comment by gares** [comment]
What is going on with ci?

**Comment by ppedrot** [comment]
SSR output seems to have changed in output/ssr_error_multiple_intro_after_case.v, so it looks like a relevant error.

**Comment by gares** [comment]
Indeed I did put garbage in the .out file (the test failing is introduced in this PR)

**Comment by gares** [comment]
all green

**Review by CohenCyril — APPROVED** [review]
LGTM

**Comment by maximedenes** [comment]
> all green

It seems, it wasn't:

> For your complete information, the job [test-suite:base+async](https://gitlab.com/coq/coq/-/jobs/696372035) in allow failure mode has failed for commit [af686af](https://github.com/coq/coq/commit/af686af3cf333d2d138e5e3e485fd7228b30ab85): [ssr] when porting v8.2 code no backtracking point has to be added

**Comment by gares** [comment]
Shame on me, I forgot an `Abort` at the end of the test file.

**Comment by Zimmi48** [comment]
I'll put a label to remind myself that this needs a fix to be backported.

**Comment by gares** [comment]
https://github.com/coq/coq/pull/12897

**Comment by maximedenes** [comment]
@gares Thanks!

**Pull request merged**
