### PR TITLE
Repair coqide option "Display parentheses"

### LINKED ISSUE #12793: Coqide menu "Display parentheses" does not work as expected
#### Description of the problem

The coqide menu does not have the same effect as the textual option.

For instance,

```
Goal 4 + 2 + 1 = 7.
Set Printing Parentheses.
```
correctly prints
```
((4 + 2) + 1) = 7
```
while using "Display parentheses" in the "View" menu, one gets:
```
eq
  (Nat.add
     (Nat.add (S (S (S (S O)))) (S (S O)))
     (S O)) (S (S (S (S (S (S (S O)))))))
```
(Actually, the option is checked by default. We obtain the term above if we disable the option, which makes no sense).

#### Coq Version

8.12

### PR DESCRIPTION
**Pull request by eponier**
**Kind:** bug fix.

Fixes / closes https://github.com/coq/coq/issues/12793

### CODE REVIEW

**Comment by eponier** [comment]
The error seems to be trivial, probably a copy/paste error, so I propose this fix. Maybe some other things must be done.

**Comment by Zimmi48** [comment]
@eponier GitHub does not seem to be aware of your `@irisa` e-mail address.

**Review by ppedrot — APPROVED** [review]
It definitely looks like a copy-paste error.

**Comment by eponier** [comment]
Thanks for noticing, @Zimmi48. I force-pushed with the right email address, but the content is the same. Sorry for the noise.

**Review by gares — APPROVED** [review]

**Pull request merged**
