### PR TITLE
LtacProf test infrastructure

### PR DESCRIPTION
**Pull request by JasonGross**
This is on top of #277, #272, and #217.  It gives us the ability to write tests for formatting and display of the LtacProf results, modulo leading and trailing spaces and decimal numbers.  This should go into 8.6.

### CODE REVIEW

**Comment by gares** [comment]
I'm testing this and eventually merging it.  This PR subsumes many others, I'm closing them

**Comment by gares** [comment]
#277 and #272 are now closed

**Comment by gares** [comment]
merged

**Comment by JasonGross** [comment]
Thanks!

**Pull request closed without merging**
