### PR TITLE
Decidable class instances

### PR DESCRIPTION
**Pull request by imaxw**
- [x] Added Instance DecidableClass.Decidable_eq_Q : forall (x y : Q), DecidableClass.Decidable (x == y)%Q.
- [x] Added Instance DecidableClass.Decidable_le_Q : forall (x y : Q), DecidableClass.Decidable (x <= y)%Q.
- [x] Added Instance DecidableClass.Decidable_eq_byte : forall (x y : byte), DecidableClass.Decidable (x = y).
- [x] Added Instance DecidableClass.Decidable_eq_ascii : forall (x y : ascii), DecidableClass.Decidable (x = y).
- [x] Added Instance DecidableClass.Decidable_eq_string : forall (x y : string), DecidableClass.Decidable (x = y).

### CODE REVIEW

**Comment by Alizter** [comment]
Shouldn't we think about adding these instances as they appear rather than accumulating them in the same file. It doesn't seem to scale too well.

**Comment by imaxw** [comment]
> Shouldn't we think about adding these instances as they appear rather than accumulating them in the same file. It doesn't seem to scale too well.

Perhaps so; I put them in this file following in the trend of the few existing declared instances (and because as a new contributor I was less skittish about making changes in a single file rather than across multiple otherwise-unrelated modules). If we think the instances would be better located in the modules, perhaps by making the existing decidability proofs class instances, then that is an easy change. Though probably we would keep at least the instance for byte equality in the DecidableClass module since the byte type is defined in Init.Datatypes.

**Comment by Alizter** [comment]
Yes, perhaps it is somewhat orthogonal to this PR. My only worry is the increased number of deps for the classes files. My question above is really to @coq/stdlib-maintainers.

**Comment by andres-erbsen** [comment]
Thank you for the contribution. Apologies that this PR has been neglected for so long.

I agree that DecidableClass.v should not depend on QArith, String, or Ascii. (IMO it also should not depend on Arith or ZArith, but changing that is another matter.)  I think the best place to put new instances is right next to the lemmas that are used to prove them. The Bool instance can stay in DecidableClass as it depends on Init anyway.

The warning `Instance` prints without `#[global]` suggests that new instances should use `#[export]`; I think that's a good idea.

I also think that `Program` mode and `forall ... : ... := { ... }` is overkill for these simple instances; either of the following would be preferred:

```coq
#[export]
Instance Decidable_eq_ascii (x y : ascii) : DecidableClass.Decidable (x = y) := {|
  Decidable_witness := Ascii.eqb x y; Decidable_spec := eqb_eq x y;
|}.
```

```coq
#[export,refine]
Instance Decidable_eq_ascii (x y : ascii) : DecidableClass.Decidable (x = y) := {|
  Decidable_witness := Ascii.eqb x y
|}.
Proof.
  now case (Ascii.eqb_spec x y).
Qed.
```

**Comment by SkySkimmer** [comment]
Note that `Qed` for `#[refine] Instance` makes the whole definition Qed, unlike Program obligations where the obligation is an auxiliary definition. Use `abstract` for the subgoal and `Defined` if you want to make the `Decidable_spec` part opaque.

**Pull request closed without merging**
