### PR TITLE
Bench: use coq-flocq3

### PR DESCRIPTION
**Pull request by SkySkimmer**
added https://github.com/coq/opam-coq-archive/pull/1940

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Should we get a bench running on this PR to double check that everything is fine?

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1795500845

**Comment by ppedrot** [comment]
Hmmm....
```
INFO: failed to install coq-vst
```

**Comment by SkySkimmer** [comment]
VST isn't happy about the compcert version, we will have to deal with it in another pr

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
