### PR TITLE
Persistent_cache.t is always Open

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by fajb — APPROVED** [review]
Well spotted!

**Comment by ppedrot** [comment]
FTR, I have the very same patch on another branch of mine where I try to give a slightly less naive implementation of the persistent cache. @SkySkimmer in order not to duplicate efforts, do you happen to be working on the same thing?

**Comment by ppedrot** [comment]
CI failures are spurious. Given this is a trivial PR it'd be nice if it would go in quickly so that I can rebase my own PR and submit it right after.

**Comment by ejgallego** [comment]
> CI failures are spurious. Given this is a trivial PR it'd be nice if it would go in quickly so that I can rebase my own PR and submit it right after.

@ppedrot , indeed, go ahead and merge !

**Comment by SkySkimmer** [comment]
>FTR, I have the very same patch on another branch of mine where I try to give a slightly less naive implementation of the persistent cache. @SkySkimmer in order not to duplicate efforts, do you happen to be working on the same thing?

I vaguely looked at it but gave up.

**Pull request merged**
