### PR TITLE
More accurate IllTypedInstance error messages

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix

While debugging, I realized that two instances of the "unable to find a well-typed instantiation" unification error messages were not mentioning the right types. They also had outdated evar_map. This PR fixes it.

I don't know how much these two instances of the error can arrive in practice. I found the first one while working on not yet correct code.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Merging soon.

**Comment by Alizter** [comment]
Is it worth adding an output test?

**Comment by ppedrot** [comment]
I don't think so, as remarked by @herbelin this occurs with unsound code.

**Comment by herbelin** [comment]
> > Is it worth adding an output test?

> I don't think so, as remarked by @herbelin this occurs with unsound code.

Strictly speaking, the `IllTypeInstance` error is later turned into an `InstanceNotSameType` error which this time is reported as a regular error to the user. But I have no clear idea about whether `InstanceNotSameType` can really be triggered in practice. I suspect it can with ill-typed first-order unification but this would require a thorough analysis of the code to know exactly if this is possible (the way I observed it is while debugging an incorrect code and this is not enough to cook a test).

**Pull request merged**
