### PR TITLE
Test quotation bytecode

### LINKED ISSUE #11808: test misc/quotation_token fails on bytecode architecures
#### Description of the problem

The test misc/quotation_token fails on byecode architectures. The list of archs where I have observed this failure:

armel mips64el mipsel hppa ia64 powerpc riscv64 x32

Here is how this looks like on armel:

````
(sid_armel-dchroot)treinen@abel:~/coq-8.11.0/test-suite$ make misc/quotation_token.log 
TEST      misc/quotation_token.sh
FAILED    misc/quotation_token.log
(sid_armel-dchroot)treinen@abel:~/coq-8.11.0/test-suite$ cat misc/quotation_token.log 
==========> TESTING misc/quotation_token.sh <==========
make[1]: Entering directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
CLEAN
make[1]: Leaving directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
make[1]: Entering directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
COQDEP VFILES
COQPP src/quotation.mlg
COQDEP src/quotation_plugin.mlpack
CAMLDEP src/quotation.ml
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
CAMLC -c src/quotation.ml
CAMLC -pack -o src/quotation_plugin.cmo
CAMLC -a -o src/quotation_plugin.cma
make[1]: Leaving directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
wong loc: 
0m0.000000s 0m0.000000s
0m1.840000s 0m0.490000s
==========> FAILURE <==========
    misc/quotation_token.sh...Error!
````
It seems that the first Fatal Errors are already produced by the invokation of make clean.

#### Coq Version

8.11.0

### PR DESCRIPTION
**Pull request by treinen**
**Kind:** infrastructure.

Fixes / closes #11808

-  Added / updated test-suite

This fixes the test failure on bc architectures as reported in that bug report. However it does *noT fix the failure of runnning the test directly from the test-suite directory (dll loading) that has been observed with @herbelin, and which is orthogonal.

### CODE REVIEW

**Review by herbelin — COMMENTED** [review]
Thanks for fix and the analysis.

If you have the ability to test with a setting `OPT=-$BEST`, that'd be good.

**Comment by treinen** [comment]
@herbelin : I tried with OPT=$BEST as you suggested but that does not work, which is not surprising as the shell scriot does not know about the BEST variable (for that it would have to include something). I also tried OPT='$BEST" in the hope that this would protect the $BEST from the shell and have it expanded by the makefile, but that didn't work either.

**Comment by herbelin** [comment]
When you run from the main `Makefile`, `config/Makefile` is imported. Can you add a minus sign in front of `$BEST` (`coq_makefile` and `configure` don't have the same convention exactly)?

**Comment by treinen** [comment]
@herbelin : that doesn't work either, with or without single quotes around $BEST

**Comment by herbelin** [comment]
Then, maybe passing `OPT=-$(BEST)` to the call to `$(MAKE)` in the `test-suite` target of the toplevel `Makefile.buid`? As in:
```
 test-suite: world byte $(ALLSTDLIB).v
       $(MAKE) $(MAKE_TSOPTS) clean
       $(MAKE) OPT=-$(BEST) $(MAKE_TSOPTS) all
```

**Comment by herbelin** [comment]
Hi @treinen, what did you finally do? Did you had a patch to the Debian package?

I'd be tempted to adapt the PR with the addition of `OPT=-$(BEST)` (which I can do, if it is ok for you that I push the PR).

**Comment by treinen** [comment]
Hello @herbelin: I will use for the next debian package a patch that corresponds to my original pull request. Besides, I stopped trying random changes. I think that it in the end this should be fixed in the generated Makefile.
However, if you send me a patch (in the patch(1) format) I can try it out.

**Comment by treinen** [comment]
Thanks for the patch proposed by @herbelin in PM to me (passing OPT=-$(BEST) in Makefile.build). This fixes the failure of misc/quotation_token when executing the testsuite from the top-level directory, so I am OK with applying this patch instead of my PR. Note however that it probably won't work when executing that individual test from within test-suite/.

**Comment by treinen** [comment]
Though there is still another test that fails on bytecode, even with the patch by @herbelin applied, that is
coq-makefile/findlib-package-unpacked. Here is the log of that test:
````
BUILDING SUMMARY FILE
logs/coq-makefile/findlib-package-unpacked.log
make[3]: Entering directory '/home/treinen/coq-8.11.1~pre1/test-suite/coq-makefile/findlib-package-unpacked/_test/findlib/foo'
rm -f *.cmo *.cma *.cmx *.cmxa *.cmi *.o *.a
make[3]: Leaving directory '/home/treinen/coq-8.11.1~pre1/test-suite/coq-makefile/findlib-package-unpacked/_test/findlib/foo'
# This configuration file was generated by running:
# /home/treinen/coq-8.11.1~pre1/bin/coq_makefile -f _CoqProject -o Makefile


###############################################################################
#                                                                             #
# Project files.                                                              #
#                                                                             #
###############################################################################

COQMF_VFILES = theories/test.v
COQMF_MLIFILES = src/test.mli src/test_aux.mli
COQMF_MLFILES = src/test_aux.ml
COQMF_MLGFILES = src/test.mlg
COQMF_MLPACKFILES = 
COQMF_MLLIBFILES = src/test_plugin.mllib
COQMF_CMDLINE_VFILES = 

###############################################################################
#                                                                             #
# Path directives (-I, -R, -Q).                                               #
#                                                                             #
###############################################################################

COQMF_OCAMLLIBS = -I src
COQMF_SRC_SUBDIRS = src
COQMF_COQLIBS = -I src  -R src test -R theories test
COQMF_COQLIBS_NOML =  -R src test -R theories test
COQMF_CMDLINE_COQLIBS =   

###############################################################################
#                                                                             #
# Coq configuration.                                                          #
#                                                                             #
###############################################################################

COQMF_LOCAL=0
COQMF_COQLIB=/home/treinen/coq-8.11.1~pre1/
COQMF_DOCDIR=/usr/share/doc/coq/
COQMF_OCAMLFIND=/usr/bin/ocamlfind
COQMF_CAMLFLAGS=-thread -rectypes -w +a-4-9-27-41-42-44-45-48-58-67   -safe-string -strict-sequence
COQMF_WARN=-warn-error +a-3
COQMF_HASNATDYNLINK=false
COQMF_COQ_SRC_SUBDIRS=config lib clib kernel library engine pretyping interp gramlib gramlib/.pack parsing proofs tactics toplevel printing ide stm vernac plugins/btauto plugins/cc plugins/derive plugins/extraction plugins/firstorder plugins/fourier plugins/funind plugins/ltac plugins/micromega plugins/nsatz plugins/omega plugins/rtauto plugins/setoid_ring plugins/ssr plugins/ssrmatching plugins/syntax
COQMF_WINDRIVE=

###############################################################################
#                                                                             #
# Extra variables.                                                            #
#                                                                             #
###############################################################################

COQMF_OTHERFLAGS = 
COQMF_INSTALLCOQDOCROOT = test
CAMLPKGS   += -package foo
make[3]: Entering directory '/home/treinen/coq-8.11.1~pre1/test-suite/coq-makefile/findlib-package-unpacked/_test/findlib/foo'
"/usr/bin/ocamlfind" opt -c foolib.ml
ocamlfind: Not supported in your configuration: ocamlopt
make[3]: *** [Makefile:7: all] Error 2
make[3]: Leaving directory '/home/treinen/coq-8.11.1~pre1/test-suite/coq-makefile/findlib-package-unpacked/_test/findlib/foo'
==========> FAILURE <==========
    coq-makefile/findlib-package-unpacked/run.sh...Error!

FAILURES
    coq-makefile/findlib-package-unpacked/run.sh...Error!
make[3]: *** [Makefile:212: report] Error 1
make[3]: Leaving directory '/home/treinen/coq-8.11.1~pre1/test-suite'
make[2]: *** [Makefile:131: all] Error 2
make[2]: Leaving directory '/home/treinen/coq-8.11.1~pre1/test-suite'
make[1]: *** [Makefile.build:617: test-suite] Error 2
make[1]: Leaving directory '/home/treinen/coq-8.11.1~pre1'
make: *** [Makefile:178: submake] Error 2
````

**Comment by herbelin** [comment]
> Thanks for the patch proposed by @herbelin in PM to me (passing OPT=-$(BEST) in Makefile.build). This fixes the failure of misc/quotation_token when executing the testsuite from the top-level directory, so I am OK with applying this patch instead of my PR. Note however that it probably won't work when executing that individual test from within test-suite/.

OK, I now made another (nicer) patch at #12082 which works `misc/quotation_token` and also when run from within test-suite/.

> Though there is still another test that fails on bytecode, even with the patch by @herbelin applied, that is
> coq-makefile/findlib-package-unpacked. Here is the log of that test:

In byte, I have however plenty of other failures in `coq-makefile` due to the `cmx` files not being generated but expected to be there. I guess you had these failures too (e.g. for `coq-makefile/coqdoc1`)?

@skyskimmer, @gares: what do we do with tests which test the presence of `cmx` file, as e.g. `coqdoc1/run.sh` which checks for
```
-./test/test_plugin.cmx
-./test/test_plugin.cmxa
-./test/test_plugin.cmxs
```
Do we grep out these files? Or do we deactivate coq_makefile tests for byte?

I also failures with native computation and floats/int63 (see #12082).

**Comment by treinen** [comment]
In fact debian has already a number of tests disabled. To see which ones look at
https://salsa.debian.org/ocaml-team/coq/-/tree/master/debian%2Fpatches the patches that have "remove" and "tests" in their names. This includes coq-makefile/coqdoc1, however according to the comment in the patch for an entierely different reason. I can add coq-makefile/findlib-package-unpacked. to that list. We also disable the complexity tests.

Having a way to simply switch off the tests that require a native code compiler would be great, of course.

**Comment by SkySkimmer** [comment]
Replaced by https://github.com/coq/coq/pull/12082

**Pull request closed without merging**
