### PR TITLE
Format pairs in pr_depth to get alternating separators, no-thunks version

### PR DESCRIPTION
**Pull request by psteckler**
This is the same as #869, except that instead of memoizing thunks in `prlist_sep_lastsep`, callers (direct or indirect) pass values instead of thunks.

### CODE REVIEW

**Comment by ejgallego** [comment]
As I said I am not OK with this going in 8.7. For 8.8, I don't really see the point of the patch, see my comment in #869 ; I trades something bad for something worse IMO. So NACK.

**Comment by psteckler** [comment]
@ejgallego Yes, I know you're opposed to this one. @SkySkimmer asked for me to create this branch, and @ppedrot had mentioned removing thunks as a possibility. So here it is, for others to look at.

**Comment by psteckler** [comment]
I missed a file in `dev/`, which wasn't built by just `make`. Fixed, commits squashed.

**Comment by psteckler** [comment]
Since #869 was merged, should this be closed, or is this still up for inclusion in a later release?

**Comment by ejgallego** [comment]
I don't really see the point of this patch, other than adding some noise, but if some others think it brings some benefit I won't oppose it.

**Comment by Zimmi48** [comment]
Let's close, this was opened more for comparison purpose than for getting merged anyways.

**Pull request closed without merging**
