### PR TITLE
Tentatively fix CI by restricting VST to one process.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by JasonGross** [comment]
Maybe it would be better (faster) for Fiat Crypto if we did `make -j2 || make -j1`?  Or even had a function that parsed the output of `make -j2` and only tried again when it was killed with signal 9?

**Comment by ppedrot** [comment]
Indeed, this was not enough for fiat-crypto. I'm not sure whether this is because the makefile disregards the NJOBS variables or fiat-crypto takes too much memory anyways, though. In any case this helps with VST so maybe we could merge at least this part.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
We are already -j1 on Fiat Crypto:
https://github.com/coq/coq/blob/93537d23c6e809354bd834097455c5e89061d85f/dev/ci/ci-fiat_crypto.sh#L25-L26

But it seems there's no `COQEXTRAFLAGS="-async-proofs-j 1"` and `par:` ignores `-j`, maybe that's what's going on?

**Comment by ppedrot** [comment]
Let's see whether this works: https://github.com/coq/coq/pull/16801

**Pull request merged**
