### PR TITLE
Remove Comments vernacular

### PR DESCRIPTION
**Pull request by vbgl**
Does not seem used anymore.

### CODE REVIEW

**Comment by ppedrot** [comment]
I'm surprised, I thought I already removed it. Anyways, supporting the removal.

**Comment by ejgallego** [comment]
Surprisingly it has some users, like me XD [I use it to specify options to jsCoq].

If you think folks it really bothers you, not a big deal, we'll find another way.

**Comment by maximedenes** [comment]
@ejgallego We would like to clean up the vernacular as much as we can, is this really the right technical solution to your problem?

**Comment by ejgallego** [comment]
It was very convenient indeed to specify IDE options: `Comment "load-pkgs: math-comp, coquelicot"` etc... without having to parse comments which is always messy. Kind of a `#pragma` directive that Coq unfortunately doesn't have.

**Comment by maximedenes** [comment]
Ok, I'll discuss it with @vbgl.

**Comment by SkySkimmer** [comment]
Maybe I shouldn't have used Comments in cacb68cb861f25c214904db1b56e7fe363f5343d considering this PR...

**Comment by Zimmi48** [comment]
I almost used this PR as an argument for changing the example, but then I remembered Emilio's comment and thought this PR had been closed or was going to be. Anyways, if this PR goes through it just needs to update `test-suite/README.md`.

**Comment by ejgallego** [comment]
We could instead just rename `Comment` to `Pragma` ? Such construction is sometimes useful IMHO and it is not such a maintenance burden. On the other hand, the above change will just break a couple of user scripts. not a big deal IMHO.

**Comment by Zimmi48** [comment]
What benefit would the renaming bring? (As opposed to just closing this PR.)

**Comment by ejgallego** [comment]
> What benefit would the renaming bring? (As opposed to just closing this PR.)

To clarify the purpose, but indeed the benefit seems moot.

**Comment by maximedenes** [comment]
Alright, @vbgl and I were not aware that there were some uses of this vernacular, so let's close this PR.

**Pull request closed without merging**
