### PR TITLE
Remove unused abort_on_undefined_evars:false in ComAssumption

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by herbelin** [comment]
@SkySkimmer : is your analysis that the flag does not matter anyway since there is already a `check_evars` just before?

**Comment by SkySkimmer** [comment]
yes

**Comment by herbelin** [comment]
Then ok. (Maybe can I just review now)

**Review by herbelin — APPROVED** [review]
See discussion

**Comment by ejgallego** [comment]
Note that this was added as indeed at some point in time, we reached this code without calling check_evars, but fortunately it seems this is solved now.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
