### PR TITLE
Backport v8.11

### PR DESCRIPTION
**Pull request by ppedrot**
Keeping track of v8.11 backports.

### CODE REVIEW

**Comment by vbgl** [comment]
Are you sure you want to target the `master` branch?

**Comment by ppedrot** [comment]
@vbgl When I put the draft flag correctly, the branch is wrong. I cannot do two things at once it seems...

**Comment by vbgl** [comment]
While we are at it, you should create a dedicated docker image that has `v8.11` in its name (see examples there: https://gitlab.com/coq/coq/container_registry). Otherwise, it may be garbage-collected and hard to regenerate.

**Comment by ppedrot** [comment]
The Docker documentation is pure Tamil to me. IIUC I have to tweak the `gitlab-ci.yml` file and push a dedicated job on my GitLab? I'm not sure where the environment variable is supposed to come from. A step-by-step guide in the Coq dev documentation would be appreciated.

**Comment by vbgl** [comment]
Let me open a PR…

**Pull request merged**
