### PR TITLE
Bump version number to 8.9+alpha

### PR DESCRIPTION
**Pull request by maximedenes**
@ejgallego please let me know what I should do for the `META.coq` file.

### CODE REVIEW

**Comment by ejgallego** [comment]
> @ejgallego please let me know what I should do for the META.coq file.

You can bump to 8.9, the plan I'd to see to for 8.9 is META automatically generated by Dune.

**Comment by Zimmi48** [comment]
@maximedenes Please update the `META` file.
Then @silene should probably be the one to merge this.

**Comment by ejgallego** [comment]
Just a small comment here, Dune provides something called a "promote" functionality, which means that we can still use it to generate automatically files such as `META` that can be committed for those not willing to use Dune. I need to investigate more tho.

**Comment by maximedenes** [comment]
Updated `META.coq` and rebased. @silene can you merge once CI says  ok?

**Review by ejgallego — APPROVED** [review]
Thanks, that's a pain indeed. Hopefully #6857 makes the file to go away soon.

**Comment by maximedenes** [comment]
Seem to break a lot of stuff..

@JasonGross Can you make fiat-crypto recognize this version number? Or better, provide a way to bypass this check in our CI?

Is the Equations failure known?

**Comment by JasonGross** [comment]
Yes, I'll aim to do that later today

**Comment by JasonGross** [comment]
@maximedenes You can "bypass the check" by specifying `COQ_VERSION=master` (or `COQ_VERSION=8.8.0` or whatever).  You can't disable it entirely because it actually selects different files depending on which version of Coq you're using, so you have to tell it which version you want the files from.  I'll go make it recognize 8.9* now, though.

**Comment by JasonGross** [comment]
Should work with 8.9 version number now

**Comment by silene** [comment]
Could someone with the appropriate rights restart the `ci-fiat-parsers` job? Thanks.

**Comment by Zimmi48** [comment]
Done. @silene If you give me your GitLab username, I can add you to the Coq organization there. If you don't have a GitLab(.com) account yet, you can just sign-in using your GitHub account and it will create a GitLab username for you (the same as on GitHub if available).

**Comment by maximedenes** [comment]
@mattam82 Do you understand the failure in equations?

**Comment by ejgallego** [comment]
Either this PR is based on a too old Coq branch or Equations didn't had some PR merged. In all cases a rebase should do.

**Comment by mattam82** [comment]
Yep that’s the unification interface improvement PR that’s responsible

**Comment by Zimmi48** [comment]
And one last rebase to make CI API: done!

**Comment by maximedenes** [comment]
@Zimmi48 Thanks! @silene can you merge?

**Comment by Zimmi48** [comment]
I've opened #7785 following your experience regarding the restarting of a failed job.

**Comment by Zimmi48** [comment]
BTW, something that remains to be done is to put the V8.9+alpha tag, cf. third checkbox at https://github.com/coq/coq/blob/master/dev/doc/release-process.md#as-soon-as-the-previous-version-branched-off-master.

bc0fa22b91b55a110def7daec66713d2a7fb909e should be the tagged commit.

**Comment by silene** [comment]
> bc0fa22 should be the tagged commit.

No, I won't tag a random commit that is completely unrelated to the actual release. I want to be able to tell people to try the alpha tag, so it should be more or less feature-complete. In particular, there should not be six months of additional features after the tag. So, the alpha tag will occur sometimes between the branching out of master and the beta release.

If developers need a `V8.8+after` tag, so be it. But please let us not pervert the meaning of an alpha release.

**Comment by Zimmi48** [comment]
You could have told me so when reviewing the release doc, which is built around this assumption.

Tagging the first diverging commit has a number of advantages but I understand that's the name of the tag that is problematic to you.

In any case, I must strongly oppose to adding an alpha tag between the branching and the beta release. Wikipedia says:

> The alpha phase usually ends with a feature freeze, indicating that no more features will be added to the software. At this time, the software is said to be feature complete.

But the branching is meant to correspond to the feature freeze, so to the end of the alpha phase!

**Comment by Zimmi48** [comment]
So if you don't want to follow the convention that we had applied for the alpha tag for the last two versions of Coq, just don't use alpha (like was the case before 8.7), it will avoid some unnecessary confusion.

**Comment by silene** [comment]
> Wikipedia says

Since you are quoting Wikipedia, you could also have quoted the very first sentence of the paragraph:

> The alpha phase of the release life cycle is the first phase to begin software testing.

Are we really in the testing phase currently?

**Comment by maximedenes** [comment]
> Are we really in the testing phase currently?

We do testing during the entire cycle. This sentence from wikipedia looks anachronistic to me.

But I think the RM should be free to organize the use of tags as they like :) And I understand the concern of confusion.

I don't know if you have the context, this tag was meant to be used for #483, as `git` can generation version names from tags.

> No, I won't tag a random commit that is completely unrelated to the actual release. I want to be able to tell people to try the alpha tag, so it should be more or less feature-complete. In particular, there should not be six months of additional features after the tag. So, the alpha tag will occur sometimes between the branching out of master and the beta release.

Note that tags and release are not the same thing. Releases are listed on the corresponding github page, not all tags are there.

**Comment by Zimmi48** [comment]
I quoted the part I needed to oppose to your proposal, not to defend mine, which I agree is stretching the definition of alpha quite far. But Maxime just told you the context of why we added this tag.

> Releases are listed on the corresponding github page, not all tags are there.

Technically, they are listed as well but very thinly so they are barely visible.

**Comment by maximedenes** [comment]
> Technically, they are listed as well but very thinly so they are barely visible.

Really? I don't see the alpha tags on the current release page.

**Comment by maximedenes** [comment]
Oh yes, you are right. Indeed they are... not very visible :)

**Comment by ejgallego** [comment]
@silene what name to put in the tag is open, however it has to make `git describe` work and meet the versioning ordering contraints described in #483. I pretty much concur with @maximedenes that 8.9+alpha seems to me like the right name for the development version. These days, master is supposed to be usable by day-to-day users.

By the way how to properly handle versioning of dev releases is still being discussed in Dune upstream, cc https://github.com/ocaml/dune/issues/880

**Comment by Zimmi48** [comment]
BTW @silene: maybe you want to edit the 8.9+beta1 milestone to put the information about the freeze date: https://github.com/coq/coq/milestones/7/edit

**Comment by ejgallego** [comment]
Well, the discussion didn't converge, so indeed I propose we continue with the current scheme and thus close #8543 adding a `v8.9+alpha` tag for bc0fa22.

I will add the tag in a few days unless somebody opposes.

**Comment by mattam82** [comment]
@silene are you ok with that? Maybe we should find another name like v8.9+init or something but it has to respect an ordering I guess? I'm hoping I can find the list of contributors to 8.9 using bc0fa22 to start the credits reliably.

**Comment by Zimmi48** [comment]
@ejgallego said on Gitter:
>IMHO the alpha tag is OK, I disagree with him about historic usage, alpha always meant "random crap"
>and in fact we will use alpha-102 meaning alpha version 102 etc...

and I agree with him (especially the second line is important: when using `git describe` each commit will be its own alpha version).
As remarked by @mattam82, `alpha` is also more convenient than e.g. `init` because it comes before `beta` in alphabetical ordering.

**Comment by Zimmi48** [comment]
@mattam82 A note on writing the CREDITS: you also need to know what @silene will finally decide to put in 8.9. There are still many feature PRs in the ["Request inclusion" column](https://github.com/coq/coq/projects/29#column-3371618) and I think the plan is to postpone most of them to 8.10 (i.e. remove them from there) but @silene hasn't done it yet.
Another question is the attributes: should it really be part of the 8.9 release or should it be postponed to 8.10 to give it time to get refined?
When we know what goes in and what doesn't we'll have some clean-up work to do on the CHANGES file. (Switching to auto-generation of CHANGES should avoid this in the future.)

**Comment by Zimmi48** [comment]
@herbelin That's not the only new attribute. There are `template` / `no-template` too. But the PR adding this has not yet been backported to v8.9. So the only current actual use of attributes in Coq v8.9 is one deprecating the alias of `fourier` to `lra`. I personally find this alias confusing anyways so it could easily be replaced by `Ltac fourier := fail "Use lra instead.".`

That being said, I advise against continuing the discussion on attributes in this thread, simply because I don't think that @silene actually follows it. This discussion would be better suited for Coqdev. (I won't start the thread because I already told to Guillaume in a private mail what I just repeated here.)

**Comment by herbelin** [comment]
> > In particular, the only really new attribute, "deprecated", is currently a misleading no-op.

> So the only current actual use of attributes in Coq v8.9 is one deprecating the alias of fourier to lra.

Thanks, I indeed did not realize that `Ltac` was supporting deprecation. This is good!

I was looking at the only occurrence of `#[deprecated]` in `theories` which _is_ a no-op. So, something should eventually be done to support it really and to check that no attribute is silently ineffective. As another example `#[polymorphic] Ltac ...` is also silently accepted. [Sorry to show little understanding, but I think this is a fair reaction to the hurry with which the PR has been merged. On the other side, I'd be happy to help in making the attribute system working better.]

**Comment by SkySkimmer** [comment]
My PR #8515 says `Error: This command does not support this attribute: polymorphic.` on polymorphic Ltac ^^
Please have a look and comment there with any thoughts.

**Pull request merged**
