### PR TITLE
Fix Inductive.instantiate_context not substituting universes in relevances

### PR DESCRIPTION
**Pull request by yannl35133**
I haven't found a way to trigger the issue (not involving the unstable branches I'm working on), but the existing code is wrong

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by mattam82** [comment]
@yannl35133 This seems wrong: in expand_arity we give a ctx which is already substituted, while in expand_branch_contexts we do not

**Comment by mattam82** [comment]
Specifically, we should replace
```
let na = Context.make_annot Anonymous (UVars.subst_instance_relevance u mip.mind_relevance)  in
```
by 
```
  let na = Context.make_annot Anonymous mip.mind_relevance in
```
in expand_arity, so that we don't get a double substitution situation

**Comment by SkySkimmer** [comment]
>Specifically, we should replace [...]

I agree

**Comment by yannl35133** [comment]
To be clear, it's not about `ctx` in any of the two functions; only the binder `na` in the `[na, self]` entry in `expand_arity` is ususbstituted twice in the end, right ?

**Comment by mattam82** [comment]
Yes, I think so

**Comment by yannl35133** [comment]
Since I'm looking at all uses of instantiate_context, do we agree that the reason why `detyping.ml` uses `Context.anonR` instead of   `Context.make_annot Anonymous mip.mind_relevance` is just because this never broke ?

**Comment by mattam82** [comment]
I think there's also a wrong relevance annotations in auto_ind_decl

**Pull request merged**
