### PR TITLE
Fix #8908: incorrect refresh of algebraic universes.

### LINKED ISSUE #8908: Untypable term produced by tactics
#### Version

8.8 (probably since 8.5)

#### Description of the problem

By not removing the algebraic status of universe variables in refresh_universes, we can get in a situation where algebraics appear in terms. 

```
Record foo : Type :=
  { fooA : Type; fooB : Type }.
Definition id {A : Type} (a : A) := a.
Definition untypable : Type.
  unshelve refine (let X := _ in let Y : _ := ltac:(let ty := type of X in exact ty) in id Y).
  exact foo.
  constructor. exact unit. exact unit. Show Proof. Show Universes.
Defined.
```

Looking at the proof:
```
(let X : foo : Type@{Top.10} := Build_foo unit unit : foo : Type@{Top.10} in
 let Y : Type@{Top.10} := foo : Type@{Top.10} in @id Type@{Top.10} Y)
```

We see that Top.10 should not be algebraic but it still is, breaking the invariant that algebraics don't appear in terms. Then minimization of universes doesn't deal with two algebraic universes one strictly higher than the other.
 
This results in `The term "foo" has type "Type@{max(Top.2+1,Top.3+1)}" while it is expected to have type "Type@{Top.10}"`.

### PR DESCRIPTION
**Pull request by SkySkimmer**
I think this deserves a backport. mli change but only by adding new vals (and making a comment more accurate).

### CODE REVIEW

**Review by mattam82 — APPROVED** [review]
It fixes this bug, but I fear we should do it all the time and not only when ~onlyalg:true, in refresh_universes.

**Comment by SkySkimmer** [comment]
>It fixes this bug, but I fear we should do it all the time and not only when ~onlyalg:true, in refresh_universes.


Changed.

**Review by ppedrot — COMMENTED** [review]
Too mysterious for me, but I trust @mattam82.

**Comment by mattam82** [comment]
It's great that this didn't produce any incompatibility! I just found another example playing with Equations which should be fixed by this.

**Comment by mattam82** [comment]
If you have time, just for reassurance a bench would be good.

**Comment by SkySkimmer** [comment]
>It's great that this didn't produce any incompatibility

There was an incompatibility in ext-lib, see https://github.com/coq-ext-lib/coq-ext-lib/pull/47

**Comment by SkySkimmer** [comment]
>If you have time, just for reassurance a bench would be good.

https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/576/console includes this PR and #8854 
~~~

┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬─────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │       mem faults        │
│                        │                         │                                             │                                             │                               │                         │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW     OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-odd-order │ 1372.24 1395.74 -1.68 % │     3823657624175     3887374311772 -1.64 % │     6480242482221     6479156070758 +0.02 % │    1347620    1343464 +0.31 % │       0       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│           coq-compcert │  879.00  889.56 -1.19 % │     2437957363309     2466672076391 -1.16 % │     3555344050743     3554617447842 +0.02 % │    1327336    1327700 -0.03 % │     101     179 -43.58 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│            coq-unimath │ 1318.02 1333.75 -1.18 % │     3661321611564     3703232837907 -1.13 % │     6186925865521     6186340946599 +0.01 % │    1079784    1079684 +0.01 % │     344      19 +1710.53 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│            coq-bignums │   98.95  100.06 -1.11 % │      274587349508      276701758657 -0.76 % │      398229226056      398574696260 -0.09 % │     539928     539996 -0.01 % │      60       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│               coq-hott │  341.52  345.27 -1.09 % │      945496384494      954498327203 -0.94 % │     1445890790533     1446274982290 -0.03 % │     600652     600608 +0.01 % │     136       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│               coq-corn │ 1525.31 1541.30 -1.04 % │     4232087639748     4276238684552 -1.03 % │     6268781754262     6268920521201 -0.00 % │     837212     836992 +0.03 % │      44      44 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│       coq-math-classes │  249.86  252.22 -0.94 % │      688807066752      694217350895 -0.78 % │      906349705980      906726582785 -0.04 % │     524356     524460 -0.02 % │      84      84 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-geocoq │ 1999.86 2017.66 -0.88 % │     5556035205950     5605613679252 -0.88 % │     8114704415223     8115367066440 -0.01 % │    1222152    1240300 -1.46 % │     205     162 +26.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-flocq │  589.57  594.76 -0.87 % │     1640939536822     1654585173404 -0.82 % │     2413161358887     2414153283750 -0.04 % │    1767380    1767424 -0.00 % │     169      40 +322.50 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│  coq-mathcomp-solvable │  215.56  217.45 -0.87 % │      598820712787      603490976667 -0.77 % │      852007233905      852159246123 -0.02 % │     847920     865324 -2.01 % │      17     112 -84.82 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│        coq-fiat-crypto │ 6233.20 6287.80 -0.87 % │    17571097809262    17723312004351 -0.86 % │    28895904376270    28880119929078 +0.05 % │    2441912    2457116 -0.62 % │    1359    1296 +4.86 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│     coq-mathcomp-field │  258.58  260.74 -0.83 % │      719064745832      724914821593 -0.81 % │     1095389620434     1095682680750 -0.03 % │     756680     756984 -0.04 % │       0     175 -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│  coq-mathcomp-fingroup │   83.68   84.30 -0.74 % │      231513139380      232432772524 -0.40 % │      344018898591      344216536620 -0.06 % │     586284     586336 -0.01 % │     129       1 +12800.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│          coq-fiat-core │  135.96  136.77 -0.59 % │      379396925133      381599619391 -0.58 % │      511032902178      511284550290 -0.05 % │     500104     500052 +0.01 % │     265     174 +52.30 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│       coq-fiat-parsers │  711.58  715.56 -0.56 % │     1973723009244     1987699709587 -0.70 % │     3032568782898     3033099553573 -0.02 % │    2908072    2911076 -0.10 % │     301     454 -33.70 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-character │  279.32  280.76 -0.51 % │      776847914160      780967741951 -0.53 % │     1121186336081     1121524357823 -0.03 % │    1094332    1094572 -0.02 % │      14       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│                coq-vst │ 2963.70 2977.88 -0.48 % │     8245673144479     8284863796380 -0.47 % │    11417552143515    11416042535999 +0.01 % │    2217476    2219276 -0.08 % │     387     250 +54.80 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-sf-plf │   75.67   76.01 -0.45 % │      209492169714      210519580657 -0.49 % │      307497771711      307926213968 -0.14 % │     513816     513724 +0.02 % │      15       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-color │  733.17  736.34 -0.43 % │     2032510470717     2041270341323 -0.43 % │     2461896035973     2461104936367 +0.03 % │    1371252    1431988 -4.24 % │      59     132 -55.30 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│        coq-lambda-rust │ 2318.74 2328.64 -0.43 % │     6460306969707     6485908254009 -0.39 % │     8892925402764     8894729780994 -0.02 % │    1443808    1438200 +0.39 % │       4      15 -73.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│   coq-mathcomp-algebra │  184.62  185.36 -0.40 % │      511962768877      514755932353 -0.54 % │      700089716960      700212056290 -0.02 % │     642752     643184 -0.07 % │     127      12 +958.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│             coq-sf-vfa │   48.73   48.92 -0.39 % │      134526802816      135130764001 -0.45 % │      216741151792      217070284135 -0.15 % │     537016     536740 +0.05 % │      30       5 +500.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│         coq-coquelicot │  105.16  105.56 -0.38 % │      290521436383      292268162032 -0.60 % │      393423113255      393806129687 -0.10 % │     711720     711496 +0.03 % │     281      13 +2061.54 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│ coq-mathcomp-ssreflect │   67.00   67.22 -0.33 % │      184402744492      185232603845 -0.45 % │      264345149427      264664004665 -0.12 % │     532924     533100 -0.03 % │       2       0  +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│              coq-sf-lf │   45.77   45.81 -0.09 % │      126439250337      126259981597 +0.14 % │      206433520986      206794474562 -0.17 % │     427880     427768 +0.03 % │     115       1 +11400.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────────┤
│    coq-formal-topology │   59.87   59.55 +0.54 % │      163345755647      163771170230 -0.26 % │      248005452396      248324525891 -0.13 % │     479468     479540 -0.02 % │       0       0  +nan % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴─────────────────────────┘
~~~

**Comment by mattam82** [comment]
I see. I guess the next step can be changing univ_flexible_alg into univ_flexible for the return types of cases in cases.ml

**Comment by mattam82** [comment]
@ppedrot ok with me

**Pull request merged**
