### PR TITLE
Support quotations (genargs) in patterns

### PR DESCRIPTION
**Pull request by SkySkimmer**
For #11641

`constr_pattern` is split in 2 types, one is allowed to contain genargs and the other not.
To share code this uses a GADT `'i constr_pattern_r`, with genargs allowed instantiated to `` [`uninstantiated] constr_pattern_r ``, without genargs instantiated to `` constr_pattern = [`any] constr_pattern_r ``.

Ltac2 instantiates the genargs in the `ml_interp` for the TacExt ie a pattern expression is interned to `` [`uninstantiated] constr_pattern_r `` then interped to `constr_pattern`.

Most code (basically everything except ltac2) uses only the no-genarg version (TODO change this? but currently we have no non-ltac2 genargs handled).

For now I just have it handling `$pattern:x` quotations.

We probably don't want to have `$constr:x` in patterns, if we really want the functionality we could expose pattern_of_constr as a `constr -> pattern` (also a `preterm -> pattern` function).

Then do we want to interpret `$x` as `$pattern:x` in patterns?
But if we have a `preterm -> pattern` we will need to consider what happens to a `$x` in the preterm and that could get confusing.

Overlays:
- https://github.com/LPCIC/coq-elpi/pull/500
- https://github.com/mattam82/Coq-Equations/pull/560
- https://github.com/ejgallego/coq-serapi/pull/359
- https://github.com/coq-tactician/coq-tactician/pull/66

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Changed: instead of supporting `$constr:x` we add `$pattern:x` and support that.
Maybe having `$x` mean `$pattern:x` in patterns would make sense?
For converting from constr and preterm using functions probably makes more sense, ie instead of `pattern:(S $preterm:x)` we have to do `let x' := pattern_of_preterm in pattern:(S $pattern:x)`.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@ejgallego I don't know how to write the overlay for serapi, it seems derivation isn't supported for GADTs

**Comment by ejgallego** [comment]
> @ejgallego I don't know how to write the overlay for serapi, it seems derivation isn't supported for GADTs

This is indeed a big PITA; let me write down in serlib's README how to do it so it remains documented (I'll use this PR as an example so the overlay almost writes by itself)

**Comment by SkySkimmer** [comment]
BTW if it makes things easier we can use a smaller GADT, ie instead of the current 
~~~
type 'i pattern_r =
| ... (* lots of cases *)
| PGenarg : Genarg.glob_generic_argument -> [ `uninstantiated ] constr_pattern_r
~~~
we can do
~~~
type _ gen_pattern = GPat : Genarg.glob_generic_argument -> [ `uninstantiated ] gen_pattern

(* not a GADT *)
type 'i pattern_r =
| ...
| PGenarg of 'i gen_pattern 
~~~

**Comment by ejgallego** [comment]
Added some notes at https://github.com/ejgallego/coq-serapi/pull/356

Rendered version: https://github.com/ejgallego/coq-serapi/blob/serlib%2Breadme_gadt/serlib/README.md

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci
(pipeline is currently pending, remerge master to be compatible with just now merged overlays)

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
Let's merge now otherwise this will never get in. @coqbot merge now

**Pull request merged**
