### PR TITLE
Mention the migration from Bugzilla to GitHub issues in dev/doc/changes.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is a proposal to record the migration from Bugzilla to GitHub issues.
I'd appreciate any kind of comments on the PR and on the [blog post](https://www.theozimmermann.net/2017/10/bugzilla-to-github/), including linguistic remarks from native English-speakers (you can either comment here, or submit a PR editing the [source file of the blog post](https://github.com/Zimmi48/zimmi48.github.io/blob/master/_posts/2017-10-23-bugzilla-to-github.md)).

This mention could possibly be duplicated as a "news" on the Coq website.

I put the `needs: progress` flag because it is lacking a link to an archive containing the XML export of Bugzilla and the log file containing the Bugzilla / GitHub ID correspondence.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@herbelin I followed your suggestion of providing a stripped down version of the log file only showing bugs that had to be renumbered. I put it in the gist with the migration script and it shows nicely, see [here](https://gist.github.com/Zimmi48/d923e52f64fe17c72852d9c148bfcdc6#file-bugzilla2github_stripped-csv).

**Comment by herbelin** [comment]
Looks excellent to me. I hope the blog post will be useful to other organizations.

As far as I'm concerned, I think I'd like a copy of the correspondence old-new in the archive (e.g in an other `dev/doc` file, or in the same file as this one), so that we don't need to rely on a web access or to an url who may not evolve synchronously with coq. Maybe this is overkill and noone would never use it but if I or others would have to use it, it would be onvenient to have it immediately at hand.

**Comment by Zimmi48** [comment]
> I'd like a copy of the correspondence old-new in the archive

The complete one or the stripped down one?

**Comment by herbelin** [comment]
The stripped one is the one containing the relevant information from which the non stripped one can be reconstructed, right? If so, yes, the stripped one.

**Comment by Zimmi48** [comment]
Basically yes, this is doable to reconstruct this information since it contains both the Bugzilla numbers that were renumbered and the GitHub numbers that were used (and thus did not correspond to any Bugzilla number).

**Pull request merged**
