### PR TITLE
Recognize opaque primitive projections in `Hint Extern`

### LINKED ISSUE #19668: TC search fails spuriously for primitive projections in 8.20
### Description of the problem

The example below works in 8.19 but not in 8.20. There are zero candidates so this points to a dnet issue.

`git bisect` points to
a366091573afce31e1cfb5802d2048287f07163d is the first bad commit
```
commit a366091573afce31e1cfb5802d2048287f07163d
Author: Gaëtan Gilbert <gaetan.gilbert@skyskimmer.net>
Date:   Tue Mar 26 15:19:45 2024 +0100

    Define Tacred.soft_evaluable_of_global_reference

 plugins/ltac/tacintern.ml | 20 +-------------------
 pretyping/tacred.ml       | 12 +++++++++++-
 pretyping/tacred.mli      |  8 +++++++-
 vernac/comHints.ml        |  9 ++-------
 4 files changed, 21 insertions(+), 28 deletions(-)
```

cc @SkySkimmer 

### Small Coq file to reproduce the bug

```coq
#[projections(primitive)]
Record bi : Type := BI {car : Type; foo : car}.
Axiom PROP:bi.
Inductive Fwd (P : car PROP) : Type := MKFWD.
Create HintDb db discriminated.
#[local] Hint Opaque foo : db.
#[global] Hint Extern  0 (Fwd ((@foo PROP))) => constructor : db.
Goal Fwd (@foo PROP).
Proof.
  intros.
  Set Printing All.
  Set Typeclasses Debug Verbosity 2.
  typeclasses eauto with db.
Qed.
```

### Version of Coq where this bug occurs

8.20

### Last version of Coq where the bug did not occur

8.19

### PR DESCRIPTION
**Pull request by Janno**
A simple oversight introduced by yours truly in https://github.com/coq/coq/pull/18979. I am not sure why  `git bisect` did not lead me there directly. 

Fixes / closes #19668

- [x] Added / updated **test-suite**.

- [x] Added **changelog**.
- [ ] Added / updated **documentation**.
  
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make doc_gram_rsts`.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by Janno** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]
Indeed.

**Comment by ppedrot** [comment]
A changelog cannot hurt, in any case.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
The serapi failure looks unrelated at first glance.

**Comment by ppedrot** [comment]
Probably, so @coqbot merge now

**Pull request merged**
