### PR TITLE
Add camlp-streams dep

### PR DESCRIPTION
**Pull request by Alizter**
We can do whatever will happen in #15867 later, no need to punish the rest of the 4.14 users with that discussion.

### CODE REVIEW

**Comment by Alizter** [comment]
Ah but ofc we need a new docker image. Oh well.

**Review by ejgallego — COMMENTED** [review]
Looks good but please:
- squash
- document the change
- update `coq.opam.docker`

**Comment by Alizter** [comment]
Don't know how to fix Nix for the time being. I want to get some feedback on this PR from others too first. I wanted to quickly patch this so I could use 4.14 easily, but this PR has basically grown into https://github.com/coq/coq/pull/15867 so I would probably rather go down that road.

I'm not entirely happy with adding a new dep, but I have put the option out there. I think #15867 should probably be merged instead.

**Comment by JasonGross** [comment]
@SkySkimmer I've just tried backporting it now, and as long as you don't need anything newer than 5.0, [it's fine](https://launchpad.net/~jgross-h/+archive/ubuntu/coq-master-daily/+packages?field.name_filter=camlp-streams&field.status_filter=published&field.series_filter=)

**Comment by JasonGross** [comment]
Would this be a build-dependency (coq only), a dev dependency (also needed for compiling plugins), or a runtime dependency (needed to run coqc)?

**Comment by Alizter** [comment]
Technically, when building in release mode the "Alert" becomes a warning rather than an error, so the opam packages don't have any issues. It's only when building in dev mode that you get issues.

**Comment by ppedrot** [comment]
I also largely prefer @SkySkimmer 's solution. Adding a dependency has always a non-trivial cost (version constraints, coupling and supply chain attacks) especially when the alternative solution is literally zero cost. I am also a clib maintainer and if @ejgallego doesn't want to handle that one I can volunteer for that precise file.

**Comment by Alizter** [comment]
There is one more solution that @ejgallego wanted, and that is to plop a copy of camp-streams in Coq. This has the advantage of being maintainable by us and being good practice. However note, we have already modified camlp-streams beyond recognition in #15867 so at this point I am not sure what we really gain. If @ppedrot is willing to "maintain" it then @ejgallego I think you should just let #15867 happen. Remember also, that at this point we have changed it considerably.

The fact that we didn't have this file in Coq before can by attributed to a historical accident IMO. Since we went down the route of "camlp5 is not enough for us, lets copy and modify it" we should have done this from the begining. The fact that camlp-streams was left out in the OCaml stdlib was merely on oversight. I am not saying that copying camlp was a good decision back then, but since it is what we intended to do, we might as well carry it out fully and work on fixing its problems than lamenting about a poor maintenance decision.

Let's also come to a decision quick since 8.16 is so close.

**Comment by ejgallego** [comment]
Finally we forked `streams` as a part of gramlib in #15867

**Pull request closed without merging**
