### PR TITLE
Fix fixpoint related lifting in open recursors + related cleanups

### PR DESCRIPTION
**Pull request by SkySkimmer**
(the kernel doesn't use fold_with_full_binders so no risk of inconsistency in existing code)

Not sure how to get some observable differences. Maybe I should just try making some unit tests.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Not very pretty to move substitution code to constr, but unluckily I don't think there is a way around...

**Comment by herbelin** [comment]
Maybe the internal representation of `fix` should instead be changed and the term be lifted by default. Moreover, that would eventually allow to support mutual fixpoints with sequential dependencies, as in:
```
Fixpoint A (n:nat) : Type :=
...
with f (n:nat) : A n :=
...
```
which, currently, we can only (unfortunately) simulate by gluing the pair of fixpoints in a sigma-types.

**Comment by ppedrot** [comment]
@herbelin I think this change is part of @mattam82's branch for induction-recursion, so this will (hopefully) eventually happen.

**Comment by herbelin** [comment]
@skyskimmer, @ppedrot: looks like you are saying the same thing, no?

>  I think this change is part of @mattam82's branch for induction-recursion, so this will (hopefully) eventually happen.

Yes, I think so. (But changing the representation now would avoid the inclusion of lift in constr.ml.).

By the way, it is a long time I did not have news about induction-recursion. What is the status?

**Comment by SkySkimmer** [comment]
ping @maximedenes or @ppedrot (as secondary kernel maintainer)

**Comment by ppedrot** [comment]
@maximedenes are you fine with the patch? It's simple and fixes a long-lurking bug.

**Review by maximedenes — APPROVED** [review]
I'm ok with the patch, but please confirm @herbelin is too.

**Comment by mattam82** [comment]
For the record I’m also fine with this, let’s make it apparent that currently fixpoint types are not a telescope and need to be lifted. We can go back when ind-ind lands.

**Comment by ppedrot** [comment]
@herbelin ping.

**Comment by herbelin** [comment]
I agree with the proposal (let's keep the convention as it is, which would prevent potential incompatibilities with code abroad if the purpose is only bugfixing and not providing a new feature).

**Pull request merged**
