### PR TITLE
[v8.12] Use tag v2.6 for VST, like in the platform.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:**  infrastructure.

@MSoegtropIMC What are the other things to change in `ci-basic-overlays.sh`? CompCert?

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Not sure if this works in CI - the "platform friendly" build assumes that at least the open source part of CompCert is already installed.

**Comment by Zimmi48** [comment]
> Not sure if this works in CI - the "platform friendly" build assumes that at least the open source part of CompCert is already installed.

I don't understand this comment. Does it explain why VST built fine in the Windows job but not in the normal CI job?

**Comment by MSoegtropIMC** [comment]
> I don't understand this comment. Does it explain why VST built fine in the Windows job but not in the normal CI job?

Yes. Before your change there where separate versions for main CI (using a self contained VST) and Windows (using a VST assuming Flocq and CompCert are already there). The platform friendly version does only compile if one compiles and installs Flocq and at least the open source part of CompCert before installing VST.

Please note that the 2.6 tag still supports a self contained build, but this is no longer the default. One has to give an a few extra option to make. I think
```
COMPCERT=bundled
BITSIZE=32
ARCH=x86
```
should do. See (https://github.com/PrincetonUniversity/VST/blob/master/BUILD_ORGANIZATION.md#install-method-3-advanced-manual-make-eg-with-bundled-compcert).

Long term the main CI build of VST should change to use a pre-installed (say via opam) version of CompCert and Flocq. The issue is that the quick to compile open source variant of CompCert currently exists only in opam - it requires patches CompCert make files.

A solution might be to test CompCert and VST in one - possibly with a non platform friendly CompCert (that is one with bundled Flocq and coq-menhirlib).

Sorry for the mess, but this change was required, mainly because if CompCert uses its own Flocq, one cannot use Coq-Interval or Gappa to prove things about C programs with VST, because both have equal but from Coq's point of view not identical definitions of floats.

**Comment by Zimmi48** [comment]
Don't apologize. I'm really happy about this change. Just trying to understand what should be done. In the end, I guess simply backporting commit 11588869d33e7faba70ab29123e6fafedcd7def2 should be enough to fix this.

**Comment by Zimmi48** [comment]
Last time, the Windows test passed. It is broken now because of the Cygwin update but this is unrelated, so I'll merge.

**Pull request merged**
