### PR TITLE
Remove some univ_flexible_alg from cases

### PR DESCRIPTION
**Pull request by SkySkimmer**
There are a couple left which seem OK.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
See #7490 for context.

**Comment by mattam82** [comment]
@SkySkimmer is there a way to restart build:base on gitlab's CI?

**Comment by SkySkimmer** [comment]
>@SkySkimmer is there a way to restart build:base on gitlab's CI?

I added you to the gitlab Coq group so you should have a button now.
I also clicked the button for you in this case.

**Comment by SkySkimmer** [comment]
It seems like this breaks quickchick somehow.

**Comment by SkySkimmer** [comment]
>It seems like this breaks quickchick somehow.

They have a match somewhere with `return Type@{max(Set,Ui,Uv)}` which now causes the `hlist_tl` constant to have an extra universe. Then intuition fails to unify different instances.

**Comment by SkySkimmer** [comment]
Basically hitting #5351.

**Comment by ppedrot** [comment]
Hopefully #8905 will be the correct fix allowing this PR to go through (if still of relevance).

**Review by mattam82 — APPROVED** [review]
Let's hope this just goes through!

**Comment by SkySkimmer** [comment]
@mattam82 should be good to merge

**Comment by ppedrot** [comment]
Let me take over.

**Comment by mattam82** [comment]
Ok

**Comment by mattam82** [comment]
A PR needs to be merged upstream that’s all.

**Comment by ejgallego** [comment]
> A PR needs to be merged upstream that’s all.

Ah, I missed the overlay sorry.

**Pull request merged**
