### PR TITLE
Make it clear how to import Ltac2

### PR DESCRIPTION
**Pull request by cpitclaudel**
**Kind:** documentation

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by ejgallego** [comment]
@cpitclaudel you created the branch in the main Coq repository instead of in your fork.

**Comment by cpitclaudel** [comment]
Woops, sorry about that.

I made this patch by clicking on "edit on github" in the manual, then creating the patch through the github web UI.  I don't see an option to create the branch in my repo with that UI, so maybe I just need to remember to go to my own repo after clicking "edit on github"?

**Comment by JasonGross** [comment]
Yeah, it's an unfortunate fact that there's no easy way to edit on your fork (especially if your fork's branch is not up to date), unless you *don't* have write access to the main repo (in which case "edit on GitHub" behaves sensibly)

**Comment by Zimmi48** [comment]
I think I have already reported this to GitHub staff before. But if you do too, they will feel some more pressure to make this an important request. A related problem is that we cannot give write access to people without giving them permission to create new branches.

**Pull request merged**
