### PR TITLE
Make some keywords into normal idents

### PR DESCRIPTION
**Pull request by SkySkimmer**
Axiom
CoFixpoint
CoInductive
Definition
Fixpoint
Hypothesis
Inductive
Parameter
Theorem
Variable
Variant
discriminated

### CODE REVIEW

**Comment by SkySkimmer** [comment]
It is a mystery whether this will go through travis.

**Comment by gares** [comment]
May I ask Why?

Do you really want this to be accepted?
```
Lemma Axiom Variant : Variable = Qed :> Variant.
```

IMO all command names should be keywords.

**Comment by JasonGross** [comment]
@gares having something as a keyword prevents it from showing up in an option, right?  So `Set Inductive Cumulatively` is invalid without this change.

**Comment by Zimmi48** [comment]
@gares See [this discussion on Gitter](https://gitter.im/coq/coq?at=58ed380ba0e4856242f54756) and [the corresponding bug report](https://coq.inria.fr/bugs/show_bug.cgi?id=5464) (and also the discussion @JasonGross is talking about at #613).

**Comment by herbelin** [comment]
Actually, we could hack the parsing rule of `Set` so that it accepts `Inductive`. I even just found a way to hack it so that it generically accepts any keywords (see [here](https://github.com/herbelin/github-coq/tree/trunk+set-any-keyword-valid-as-ident)).

So, this PR can also be considered independently of the `Set` issue.

**Comment by SkySkimmer** [comment]
@herbelin  "This branch is even with coq:trunk." did you forget to push?

I'm generally of the opinion that as few things as possible should be keywords.
On the other hand I just found out that Coq is insane about keywords:
``` coq
Definition Variable := Prop.
(* rejected: Syntax error: [Prim.pidentref] expected after [def_token] (in [vernac:gallina]). *)
```
but
``` coq
Notation "'Variable'" := Prop.
Lemma foo : Variable.
Proof.
exact True.
Qed.
(* works *)
```

**Comment by aspiwack** [comment]
I can get kind of worse:

```coq
(* [Variable] is a keyword *)
Notation "'Variable'" := Prop.

Variable Foo : Prop.

(* [Variables] is not a keyword *)
Notation "'Variables'" := Prop.

(* Doesn't parse: *)
Variables (Foo : Prop).
```

That's because `Notation`-s declare their string token as keywords. It would be good to reverse this design too, I suppose.

Anecdote: in a time past `->` was not a notation but a special token. I had the amusing, and bemusing, experience of writing a notation with `'->'` in it, which declared a new keyword for `'->'` and overrid the token, suddenly the the arrow didn't parse in types.

**Comment by silene** [comment]
> That's because Notation-s declare their string token as keywords. It would be good to reverse this design too, I suppose.

Be careful there. I hope you were only talking about pure ident-like keywords. Otherwise you would break a bunch of Coq developments that rely on the keyword mechanism. For instance, the `'M_n` notation of mathcomp is parsed correctly (that is, split before `n`) thanks to the keyword mechanism.

**Comment by herbelin** [comment]
@SkySkimmer: commit pushed.
 
@aspiwack: The phenomenon that you mention has been fixed about 18 months ago. With 8.6, I get "Error: Foo already exists.".

But, yes, in general, one can do crazy things with notations, for the good or the bad.

**Comment by aspiwack** [comment]
@silene 

> Be careful there. I hope you were only talking about pure ident-like keywords.

Indeed. But it may still be fraught with detail-devils.

@herbelin 

> The phenomenon that you mention has been fixed about 18 months ago. With 8.6, I get "Error: Foo already exists.".

Oh? It seems I just popped up a rather old version of Coq…

**Comment by maximedenes** [comment]
I thought the lack of keywords was making the parsing of the vernacular more difficult. For instance, isn't it because of it that we have to add a silly dot at the end of each command?

So I personally would be rather in favor of exploring Hugo's way of solving the `Set` issue (making it accept keywords).

**Comment by Zimmi48** [comment]
The discussion about this PR starts here: https://youtu.be/wQ45AwCn1SE?t=1h25m52s
It was hijacked by Maxime to argue against dots (and this digression lasts almost 10 minutes ^^).
Then a conclusion was quickly reached that the alternative solution to the `Set Inductive blabla` issue proposed by Hugo is going to be preferred.
Although since only the `Set` issue was discussed, and not the `Require Import` issue (see https://coq.inria.fr/bugs/show_bug.cgi?id=5464), may I ask if the alternative proposed solution is generic enough to solve this problem as well? From the title of the branch I suppose it is not, so for me what this PR proposes looks like a better and more generic solution to a pervasive problem. I wasn't there though to defend this viewpoint.

**Comment by maximedenes** [comment]
> It was hijacked by Maxime to argue against dots (and this digression lasts almost 10 minutes ^^).

I don't know what crossed my mind to start that. Sorry!

**Comment by herbelin** [comment]
@Zimmi48: The alternative solution cannot be applied generically once and for all but the ad hoc entry I added can be used one by one to all rules which need to accept keywords.

**Comment by SkySkimmer** [comment]
Personally I don't care about `Set Inductive`, I want to be able to do `Inductive Inductive (p : Parameters) : Indices -> Type := Constructor : forall v : Variables, Inductive p (Axiom p v).` without hitting a syntax error that cannot actually be explained by parsing constraints (otherwise this PR wouldn't be possible) and which is reasonable about `Inductive` vs `Variable` vs `Variables`.

If the set of keywords was expanded so as to have non dot terminated commands then things being keywords would have a sense as well, although I don't think there would be much benefit (ie I don't mind the dots) and literally everything would have to be rewritten so I doubt it will happen.

**Comment by Zimmi48** [comment]
@herbelin Indeed, now looking at your branch, it is very light and it could be applied to `Require` / `Import` as well. I suppose though that it wouldn't be easy to cover the use case just given by @SkySkimmer.

@SkySkimmer Yes, indeed. I don't think that the dot is going away anytime soon and @maximedenes was seemingly the only one who was bothered about it. It would be interesting to understand what are the other reasons for not wanting to have less keywords. Unfortunately, they were not spelled out in the discussion (or I missed them in the video).

**Comment by maximedenes** [comment]
I think we can forget about the removal of the dots, indeed. It is not forbidden to think about it (I hope), but there's little incentive to change things there.

A general discussion on the motivations for more keywords vs fewer keywords should indeed take place at some point. Personally, I don't feel qualified. I believe @gares had some ideas.

**Comment by maximedenes** [comment]
I'm afraid we (I) misunderstood the main intent behind this PR. I thought it was really for `Set`.

**Comment by SkySkimmer** [comment]
So do we do this or should we make the Variable etc aliases into keywords?
Or something else (what)?

**Comment by Zimmi48** [comment]
I'm still in favor of this but I acknowledge that I may be unaware of all the implications. If someone is still against this, please make a summary of the reasons why.

**Comment by gares** [comment]
```
Definition X := Y (* oops I forget the dot *)
Axioms IlikeKeywords : Type.
```

Keywords help detecting parsing errors. In particular in combination with a UI that tries constantly to parse a document while being edited (e.g. the one of Isabelle, or Coqoon for Coq)... you get silly "parsable" sentences if you remove all keywords.

Please make all commands keywords instead.

**Comment by gares** [comment]
> I want to be able to do Inductive Inductive (p : Parameters) : Indices -> Type := Constructor : forall v : Variables, Inductive p (Axiom p v).

I see your problem, but there are simpler solutions requiring no changes to Coq
```
Inductive inductive (p : parameters) : indices -> Type := constructor : ....
```
or `InductiveType` or `InductiveDecl` or `IndTy`.

**Review by gares — CHANGES_REQUESTED** [review]
please don't do that

**Comment by Zimmi48** [comment]
> ```
> Definition X := Y (* oops I forget the dot *)
> Axioms IlikeKeywords : Type.
> ```
>
> Keywords help detecting parsing errors. In particular in combination with a UI that tries constantly to parse a document while being edited (e.g. the one of Isabelle, or Coqoon for Coq)... you get silly "parsable" sentences if you remove all keywords.
>
> Please make all commands keywords instead.

Finally a good argument against this PR. I am personally convinced by this.

**Comment by SkySkimmer** [comment]
Rejected to help IDEs.

**Comment by Zimmi48** [comment]
Should there be more keywords instead?

**Pull request closed without merging**
