### PR TITLE
[dune] Teach coq_dune about `.glob` and `.aux` files.

### PR DESCRIPTION
**Pull request by ejgallego**
This is a required step in order to be able to call `coqdoc` an
generate the documentation of the stdlib, and also useful for other
uses such as the asynchronous engine.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ping, asking for assignee.

**Review by Zimmi48 — APPROVED** [review]
Trivially OK. Sorry for the delay, I didn't have much time to review PRs lately. Can you rebase?

**Comment by ejgallego** [comment]
No worries at all @Zimmi48 , thanks for you help.

**Comment by ejgallego** [comment]
Failure status is spurious here.

**Comment by Zimmi48** [comment]
Indeed, this is a consequence of the change of context name and disabling the automatic GitLab-GitHub integration (cf. coq/bot#25).

**Comment by ejgallego** [comment]
Thanks @Zimmi48 !

**Pull request merged**
