### PR TITLE
add Ltac2 function for printing booleans

### PR DESCRIPTION
**Pull request by carlpaten**
**Kind:** feature

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

___

The existing functions don't seem to have any documentation so I figure this is probably OK?

Note that I haven't worked out how to build Coq locally, so for all I know this may not work at all. (Any recommendations on local Coq development are welcome.)

___

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Can't this be done in Ltac2:
```
Ltac2 of_bool b := match b with true=>of_string "true" | false=>of_string "false" end.
```
(see e.g. test-suita/ltac2/array-lib.v).

**Comment by lilred** [comment]
Sure, works for me.

**Comment by MSoegtropIMC** [comment]
I still think we should have this in the standard library, just not as OCaml function but as Ltac2 function. I wanted to say that you should change your PR accordingly.

@ppedrot : what is your opinion about this?

**Comment by ppedrot** [comment]
@MSoegtropIMC didn't have the time to comment on that one, but that was actually going to be my main comment: this should exist as an Ltac2 function, not a primitive.

**Comment by MSoegtropIMC** [comment]
@ppedrot : I am about to make a PR with message / printing utilities including this. I have one last question: do you think this should be in the Message module as of_bool or in the Bool module as to_message or both? Bool is in the end just a "user level" type but on the other hand an important one. How about having both, also for other "core level" types?

For many of my user defined types I define a to_message function and having both would advertise this as standard practice.

**Comment by ppedrot** [comment]
Maybe call it `print` rather than `to_message`, it is probably better. As for the exact location, I don't know, this could probably discussed with the emerging community of Ltac2 users?

**Comment by MSoegtropIMC** [comment]
Hmm I have a bunch of print functions, but they actually print it. to_message is just supposed to convert it to a message.

**Comment by JasonGross** [comment]
There is already `Message.of_constr`.  It seems more extensible to use `Foo.to_message` rather than `Message.of_foo` (since user libraries can't extend `Message` without making their own `Message` module).  I guess I'm sorry not sure which to use, but I think we should pick one and be consistent

**Comment by MSoegtropIMC** [comment]
My suggestion is to have for the most basic types an `of_<type>` in the Message module and a `to_message` in their respective Module like Constr, Bool, Int. But I am fine to change everything to `to_message` in the respective module. As you, say this makes more sense for extensions.

But then this would a non compatible change. OCaml also has for many things both an `of_` and a `to_` function which are way redundant, so I think it is not that bad to have `Message.of_<type>`. But I would restrict this to those where the function is an OCaml function + Bool.

**Comment by JasonGross** [comment]
Your proposal sounds good

**Comment by MSoegtropIMC** [comment]
@ppedrot , @JasonGross : I have a fairly extensive printing library for my one use which is good enough for my needs, but it is not terribly elegant - in the end I have functions like print_sc which take a string and a constructor term and print it and variants which print it e.g. in tuple and list forms, a few functions to "tuplify" lists of messages and the like. All in all maybe 50..100 functions. I am still in the process of thinking about how this could be made more elegant - moving between having an OCaml style format string parser and using some sort of converter/combiner operators, so that one would write e.g.
```
printf .S <string> .C <constr> .N
```
where `.N` is for newline. This variant would be more easily user extensible compared to a format string parser. The .S ... term builds up a list of messages and printf prints this list. I would have a few variants of print which print stuff e.g. as tuple or list or just space or comma separated and also operators which take a list and e.g. tuplify it to a message so that this can again be combined with other stuff.

What is your opinion on this? And also: should I make a PR for what I have before everybody reinvents the wheel?

**Comment by ppedrot** [comment]
I have on my TODO list to implement a type-safe printf-style syntax in Ltac2. It's not super hard given that the implementation is done OCaml side and thus does not require GADTs, it is enough to have abstract types with phantom arguments. The API would look like what OCaml does for their `format4` type (except abstract) and a nice syntax could be provided by mere desugaring to primitive combinators via a notation scope.

**Comment by MSoegtropIMC** [comment]
I am honestly not sure if a fixed printf string parser as in OCaml is the best solution. The downside is that one cannot (easily) extend it with user defined types. The converter/combinator approach is I think more flexible and easier to extend. I must say initially I didn't like the message concept a lot, but with a bit of boiler plate code it is actually quite nice.

**Comment by JasonGross** [comment]
Is it really that ugly to use `%a` as in OCaml's `printf`?

**Comment by MSoegtropIMC** [comment]
> Is it really that ugly to use `%a` as in OCaml's `printf`?

I dont like it if predefined stuff and user defined stuff is generally treated differently. But for sure I could live with %a.

**Pull request closed without merging**
