### PR TITLE
Deprecate { … } syntax for instance definitions. Recommend {| … |} instead.

### PR DESCRIPTION
**Pull request by vbgl**
- [x] Corresponding documentation was added / updated.
- [x] Entry added in CHANGES.

### CODE REVIEW

**Review by JasonGross — CHANGES_REQUESTED** [review]
I think CHANGES should mention a suggested way to enable BIDI without enabling the other features of `Program`, such as autoinsertion of sigma projection and use of the obligation tactic.

**Comment by SkySkimmer** [comment]
Record syntax also doesn't work to replace `{}` (completely automatic solving).

**Comment by vbgl** [comment]
To get “completely automatic solving”, it is possible to write `Instance foo : Class.`, i.e., not to give any term. Do I miss something else?

Concerning BIDI, could it be always enabled? Maybe with some flag/option/attribute to locally disable it. Are there other concerns than compatibility that would motivate disabling it?

**Comment by mattam82** [comment]
AFAIK, only compatibility is a problem for BIDI

**Comment by SkySkimmer** [comment]
>To get “completely automatic solving”, it is possible to write Instance foo : Class., i.e., not to give any term. Do I miss something else?

```coq
Class Foo := {}.

Class Bar := { foo : Foo }.

Instance : Foo. (* works *)

Instance : Bar.
Abort. (* ^ started a proof *)

Instance : Bar := {}.
(* works *)
```
It doesn't work for `Bar`, and it fails silently which I seriously dislike.

**Comment by SkySkimmer** [comment]
I don't think we're ready to deprecate `{}`, so I think we should close this PR.

**Comment by maximedenes** [comment]
If we close this PR, it would be good to open an issue to remind us of the remaining steps.

**Comment by SkySkimmer** [comment]
>Status of this?

We still don't have a good replacement for `{}`. Let's close until that changes.

**Comment by maximedenes** [comment]
> Let's close until that changes.

As per my comment above, please open an issue.

**Pull request closed without merging**
