### PR TITLE
Thread the goal state through tactics in `ssrfwd` and `equality`

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
In https://github.com/coq/coq/pull/16194 and https://github.com/coq/coq/pull/15121 some uses of `Proofview_monad.with_empty_state` where introduced. We replace them with a proper call to `Proofview_monad.goal_with_state`.

### CODE REVIEW

**Comment by ppedrot** [comment]
The code change is fine but I have two questions / remarks:
- Do you have a test to trigger the issue?
- I guess this boils down to settling for a precise specification, but I feel that the goal state machinery is globally exposing details about the internals of tactics. Here it seems you want to fix an issue in ssr by tweaking internals of equality-related tactics. Since nobody really agrees on what it means to be a subgoal and which tactic should preserve the goal state, isn't there a more local fix to the ssr code? For instance, threading the state there explicitly instead of leaking it into the engine.

**Comment by LasseBlaauwbroek** [comment]
- The problem triggers in my plugin. I have a warning setup whenever a tactic 'forgets'  the state of a goal, which triggers on the tactics that use this code. Unfortunately I don't have a simple testcase for the test-suite.

> Here it seems you want to fix an issue in ssr by tweaking internals of equality-related tactics.

The `ssr` changes and the `equality` changes in this PR are actually completely independent. (I can split the PR into two if you like).

**Comment by ppedrot** [comment]
So I guess the invariant you want to maintain is that for any output goal produced by a tactic such that the very same underlying evar was in the input state, then the extra goal data should be left untouched? Or is it something else?

**Comment by LasseBlaauwbroek** [comment]
Here is a non-exhaustive specification of the goal state:

1. Say a tactic `tac` is executed on a single focused goal (evar) `?x`.
2. If `tac` fills `?x` with a term `t` containing non-shelved evars `?a`, `?b`, `?c`, then all those evars need to be accompanied with the possibly updated state of `?x`. (The meaning of 'update' is unspecified, but the state should obviously not just be emptied.)

**Comment by ppedrot** [comment]
What about multi-goal tactics (and solving at distance by e.g. unification)? That's precisely where the "subgoal" model stops making any sense.

**Comment by LasseBlaauwbroek** [comment]
Multi-goal tactics are still well-defined:
1. Say `tac` is executed on two focused goals (evars) `?x` and `?y`.
2. If `tac` fills in `?x` by a term `u` and `?y` by a term `v`, then all evars in `u` inherit the state of `?x` and all evars in `v` inherit the state of `?y`.

Solving at a distance does indeed break this model. Maybe at some point I'll come up with some more rules. But for now, I'd be perfectly happy with leaving the behavior unspecified in this case. Tactics can either forget any state of evars solved at a distance, or fill in any other state they like.

**Review by ppedrot — APPROVED** [review]
I'm still not convinced by the intended semantics but the current code change is reasonable.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by LasseBlaauwbroek** [comment]
Note that in most cases, the problem with dependent evars being solved at a distance is mute. Most dependent evars actually live on Coq's shelf. The shelf does not maintain a state for it's evars, and hence the spec does not need to cover this. These things only become a problem when, for whatever reason a dependent evar is not on the shelf (which is also why the `unshelve` tactic understandably violates the spec). Those situations are rare enough that leaving this under-specified seems okay to me.

**Comment by gares** [comment]
I think the semantics explained by @LasseBlaauwbroek makes sense, and is the one I had in mind when "goal state" was introduced.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
