### PR TITLE
Do not warn about deprecated -native-compiler when passed "off"

### PR DESCRIPTION
**Pull request by SkySkimmer**
cf discussion in #16889

### CODE REVIEW

**Comment by Zimmi48** [comment]
Light CI should be sufficient, shouldn't it?

@coqbot run light CI

@ppedrot Do you want this in 8.16.1? If not, I want this in 8.17+rc1 for sure.

**Comment by ppedrot** [comment]
@SkySkimmer can you rebase? This is with the broken master.

**Comment by SkySkimmer** [comment]
@coqbot run light CI

**Comment by Zimmi48** [comment]
FWIW, my previous call was already post-#16895, it was just pending, so there was nothing to do. @ppedrot we do not need to rebase when there are no conflicts, asking coqbot to trigger a new CI creates a fresh merge commit with the base.

**Comment by ppedrot** [comment]
Why are the MacOS / Windows runs still failing then? I'm a bit confused.

**Comment by Zimmi48** [comment]
These are out of the scope of coqbot. Unfortunately, GitHub Actions use the merge commit created by GitHub at the time of the event which triggered the Actions. Thus, if we retry it, the updated merge commit is not used.

**Comment by SkySkimmer** [comment]
because computers hate us

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
