### PR TITLE
Add changes for -set

### PR DESCRIPTION
**Pull request by SkySkimmer**
I realized this was missing just as the PR got merged

### CODE REVIEW

**Comment by Zimmi48** [comment]
Please don't do this (putting the milestone after merging): this breaks the automation in place.

**Comment by ejgallego** [comment]
Sorry @Zimmi48 , indeed I raced against myself.

**Comment by ejgallego** [comment]
Maybe we should disallow skipping a merge if the milestone is not yet?

**Comment by Zimmi48** [comment]
Unfortunately, these checks were intended as something people should almost never skip but some of them have become too frequent and people have gotten used to skipping them.

**Comment by ejgallego** [comment]
> Unfortunately, these checks were intended as something people should almost never skip but some of them have become too frequent and people have gotten used to skipping them.

I never skip the milestone/kind check, and indeed I see no good reason to; in this case it was just that I pushed before I clicked on the UI interface :(

**Comment by ejgallego** [comment]
But indeed if they should never be skipped maybe we should remove the y/n question?

**Comment by SkySkimmer** [comment]
Maybe the script could ask the user which milestone they want and set it.
That would require some work to get tokens for authenticating to github I guess.

**Comment by ejgallego** [comment]
Yup, for sure @SkySkimmer at some point we want the tooling to interact with Github [for example to have a submit pr with overlays] script.

I am working on these stuff [in OCaml tho] but I don't think I'll be able to produce anything before the CUDM.

**Pull request merged**
