### PR TITLE
[state] Consolidate state handling into Vernacstate

### PR DESCRIPTION
**Pull request by ejgallego**
After #12504 , we can encapsulate and consolidate low-level state
logic in `Vernacstate`, removing `States` which is now a stub.

There is hope to clean up some stuff regarding the handling of
low-level proof state, by moving both `Evarutil.meta_counter` and
`Evd.evar_counter_summary` into the proof state itself [obligations
state is taken care in #11836] , but this will take some time.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
Seems OK, @coq/stm-maintainers may want to have a look too.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
A comment is a bit risky. Especially if the obligation state survives more than one proof. In that case the meta counter better live next to it, not in the proof state (which, to my understanding, does not survive a proof).

**Comment by ejgallego** [comment]
> A comment is a bit risky.

What do you mean @gares ?

> Especially if the obligation state survives more than one proof. In that case the meta counter better live next to it, not in the proof state (which, to my understanding, does not survive a proof).

Indeed, the meta/evar counters should be associated to their corresponding evar_map , indeed the obligations state capture evar_map that survive a full proof state, and there are some other weird surgeries in the codebase.

So indeed it would be good to localize the global counters a bit more, but that's not gonna be easy.

**Comment by gares** [comment]
> What do you mean @gares ?

It suggests to go in a direction, but it seems we are going another. I chose the wrong word. I hope its clear now.

**Comment by ejgallego** [comment]
@gares I think we are on the same page here, aren't we?

For example (forgetting about worker sync which is a different issue) , if the obligation sigma survives, would we place the counter with the sigma could be an option?

(Not sure about the feasibility of it, just brainstorming)

**Comment by gares** [comment]
Yes, the counters should be inside sigma.

**Comment by ejgallego** [comment]
> Yes, the counters should be inside sigma.

I was experimenting with this yesterday, but there are some problems due to evar_map manipulation, see more in #12629

**Pull request merged**
