### PR TITLE
Allow passing arguments directly to nix-shell.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Note that the reason why I explicitly listed the names of the arguments instead of using an ellipsis is to have `nix-shell --arg` auto-completion work.

**Comment by vbgl** [comment]
Do you know you can already use: `nix-shell default.nix --arg shell true`?

**Comment by Zimmi48** [comment]
Yes, this was documented in `shell.nix`. However the documentation in `default.nix` was incorrect, and it is easy to forget that there is also a `shell.nix` that takes precedence.

**Review by maximedenes — COMMENTED** [review]
No strong opinion on this, what's your take @vbgl?

**Comment by vbgl** [comment]
I don’t see the motivation. But I’m not against the change.

**Comment by Zimmi48** [comment]
The motivation is: I forgot about `shell.nix` and it took me a while to understand why the arguments I passed to it didn't work (especially difficult since the header of `default.nix` was incorrect / out-of-date with respect to this). This is my fix, but of course an alternative is to fix the documentation inside `default.nix`.

**Comment by vbgl** [comment]
What about dropping `shell.nix` altogether and setting the default value of the `shell` parameter to `true`?

**Comment by Zimmi48** [comment]
> What about dropping `shell.nix` altogether and setting the default value of the `shell` parameter to `true`?

The issue then becomes that you have to remember to pass `--arg shell false` to `nix-build`.

**Comment by vbgl** [comment]
How often do you manually call `nix build`? Isn’t that mostly used in CI scripts or the like?

**Comment by Zimmi48** [comment]
> How often do you manually call `nix build`? Isn’t that mostly used in CI scripts or the like?

Yes, that's correct, but there are a great number of such scripts that would have to be fixed, e.g. those using coq-community's templates.

**Comment by Zimmi48** [comment]
This is going to be superseded by the use of the Coq Nix Toolbox.

**Pull request closed without merging**
