### PR TITLE
[ci] [docker] Make sure we don't install optional packages with apt.

### PR DESCRIPTION
**Pull request by ejgallego**
This should help towards ensuring that the system only has the
packages we specify in the Dockerfile.

### CODE REVIEW

**Comment by ejgallego** [comment]
boot pipeline https://gitlab.com/coq/coq/pipelines/24970341

**Comment by ejgallego** [comment]
Aha, `git` doesn't seem to be pulled now :)

**Comment by ejgallego** [comment]
As expected, we need to fix a couple of things.

**Comment by ejgallego** [comment]
Indeed `git rsync python3-setuptools python3-wheel` where missing from our list of packages.

**Comment by ejgallego** [comment]
Ok this seems to be ready: https://gitlab.com/coq/coq/pipelines/24991705

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
