### PR TITLE
[funind] Untabify; necessary to ease the review of subsequent work.

### PR DESCRIPTION
**Pull request by ejgallego**
I am submitting this PR which is a whitespace-only change as otherwise rebasing and reviewing #9849 is very difficult due to interactions with the indenting engine and the linter.

I am thus requesting an exception so we can clean up this notorious plugin of its large amount of tabs.

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
I'm personally ok with the exception.

**Comment by Zimmi48** [comment]
Unfortunately, there is already a conflict. Once the conflict is solved, the PR will have to be merged quickly to avoid any further conflict.

**Comment by ppedrot** [comment]
I am taking the liberty of assigning and merging this PR. It is trivial and any delay introduces potential conflicts. Also, the CI failure is spurious.

**Comment by ejgallego** [comment]
Thanks Pierre-Marie

**Pull request merged**
