### PR TITLE
[vernac] Deprecate the unqualified “Print” command

### PR DESCRIPTION
**Pull request by vbgl**
Using “Print qualid” sometimes produces strange errors, as reported in #10708. 

- [x] Added / updated test-suite
- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
Please don't do that. It's handy to have a short name for a commonly used command. If it happens to clash very rarely with some other printing commands, bad luck, but we're not going to change all devs just for a handful of special words...

**Comment by vbgl** [comment]
But this command is so commonly used that IDEs have convenient shortcuts to use it, isn’t it?

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
Don't do this, we can fix the parsing errors which can be fixed and live with the others.

**Comment by ppedrot** [comment]
I propose closing this PR thus.

**Pull request closed without merging**
