### PR TITLE
update elpi to 1.7

### PR DESCRIPTION
**Pull request by gares**
Overlay: https://github.com/LPCIC/coq-elpi/pull/79

### CODE REVIEW

**Comment by gares** [comment]
I can prepare a backport to v8.10, since the real master of coq-elpi still tracks v8.10 if @vbgl agrees

**Comment by gares** [comment]
CI light green @coq/ci-maintainers

**Comment by gares** [comment]
ping

**Comment by gares** [comment]
@coq/ci-maintainers can I do something to get this one in?

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
