### PR TITLE
Revert "Notations: Trying using a notation with or w/o removal of coe…

### LINKED ISSUE #11033: Notations for coercions make coercions always visible
#### Description of the problem

Please consider the following test case:

```coq
Section Test.

Variables (A B : Type) (a : A) (b : B).
Variable c : A -> B.
Coercion c : A >-> B.

Notation COERCION := (c).

Goal b = a.
(**
The goal is displayed as
  b = COERCION a

but
  b = a
is expected
*)
Abort.

End Test.
```

The real issue arises when using e.g. `predI` from `ssrbool`.
`(predI a a) x = a x && a x` is displayed as `pred_of_simpl (predI a1 a2) x = a1 x && a2 x`

#### Coq Version

8.10.0 and 8.11+alpha (ab8ed0a39e7e39573716a473618ed4f7c219d072)

(The issue does not appear on Coq 8.9.1)

### PR DESCRIPTION
**Pull request by gares**
Fix #11033 

Or course any other fix is fine to me

### CODE REVIEW

**Comment by gares** [comment]
This bug affects 8.10 too, if a new point release is to be made @vbgl can consider backporting this

**Comment by vbgl** [comment]
Can you please add a test-case corresponding to the bug report? Thanks.

**Comment by gares** [comment]
There you are, this is the test I've used for bisecting (plus `grep COERCION`, that should not succeed, since coercions should not be printed)

**Comment by gares** [comment]
Also 8.11 is affected, CC @ppedrot @mattam82 .

I don't know if a better fix can be provided in time for the release, I see this PR for the worst case scenario.

**Comment by herbelin** [comment]
@gares, thanks for the quick finding of the issue! If it is clear that #11033 is a change of semantics, I would not say that it is bug though, especially regarding this other [expectation](https://github.com/coq/coq/pull/8890#issuecomment-440296811).

Since this is already released in 8.10, I'd be tempted to test the following cheap-to-implement improvement of the criterion used in #8890: look for notations which span the full application of the coercion to a term, rather than looking for a notation which applies to any partial prefix of the term as it is with #8890. By doing so, in the #11033 example, `Notation COERCION x := (c x).` would use the notation but `Notation COERCION := c.` would not. This looks like a reasonable compromise on guessing what the intent of the user is in defining a notation involving a coercion.

**Comment by JasonGross** [comment]
> Since this is already released in 8.10, I'd be tempted to test the following cheap-to-implement improvement of the criterion used in #8890: look for notations which span the full application of the coercion to a term, rather than looking for a notation which applies to any partial prefix of the term as it is with #8890. By doing so, in the #11033 example, `Notation COERCION x := (c x).` would use the notation but `Notation COERCION := c.` would not. This looks like a reasonable compromise on guessing what the intent of the user is in defining a notation involving a coercion.

I would prefer this solution over simply reverting #8890

**Comment by herbelin** [comment]
See #11090 for the variant of #8890 which looks only for notations matching the fully applied coercion.

**Comment by ejgallego** [comment]
Superseeded by #11090

**Pull request closed without merging**
