### PR TITLE
Document Printing Goal Tags flag

### PR DESCRIPTION
**Pull request by jfehrle**
@Zimmi48 Perhaps you could be the assignee?

### CODE REVIEW

**Comment by Zimmi48** [comment]
I'm not sure what kind of review you expect from me here? Do you consider that the PR is ready to merge as is? The name of the PR is a bit misleading since it says "document" but it just lists the flag with no description.

**Comment by jfehrle** [comment]
Yeah, a little unclear.  I only meant documenting that the flag exists, which I discovered while doing other things.

**Comment by Zimmi48** [comment]
Let's not document it without description. According to the comment next to the flag definition in the code it could be documented as:

>Internal flag used to implement Proof General's proof-tree mode.

**Comment by jfehrle** [comment]
Got it, updated.

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
