### PR TITLE
Fix undefined variables in test-suite/Makefile + add PRINT_LOGS

### PR DESCRIPTION
**Pull request by SkySkimmer**
PRINT_LOGS can be used for interactive calls, eg

           make report PRINT_LOGS=1

### CODE REVIEW

**Comment by Zimmi48** [comment]
If #6557 is merged first, this PR should be updated to add documentation. And conversely.

**Review by gares — APPROVED** [review]

**Comment by maximedenes** [comment]
I'm going to merge #6557, so please update this PR with documentation. Thanks!

**Comment by SkySkimmer** [comment]
Adding needs: review for the new documentation.

**Review by Zimmi48 — APPROVED** [review]
The documentation looks good to me.

I would have personally used test examples using better known features of Coq, e.g.:

```
Goal False. exact I. Qed.
```

and

```
Goal True. exact I. Qed.
```

but that's a matter of personal taste. I'm not requesting changes.

You may also want to fix in passing the typo on line 9 ("is on of the sub-directories") and put the "-B" on line 13 between back-ticks. Or not, given how this is unrelated.

**Pull request merged**
