### PR TITLE
[doc] [README] [ci] Add links to documentation builds.

### PR DESCRIPTION
**Pull request by ejgallego**
cc: #7161
cc: https://github.com/coq/www/pull/69

### CODE REVIEW

**Comment by ejgallego** [comment]
Rendered: https://github.com/ejgallego/coq/blob/25798f84bad109a8e3b69ec369c2971632abcaaa/README.md

**Review by Zimmi48 — COMMENTED** [review]
Putting these links in the README may make more sense that what I proposed in coq/www#69.
However, I wouldn't create a new section for this, I would put the links in the already existing "documentation" section.
Additionally, the current state of the standard library documentation isn't acceptable and we should not link to it until we fix it.

**Comment by ejgallego** [comment]
> Additionally, the current state of the standard library documentation isn't acceptable and we should not link to it until we fix it.

We have a bug for it?

**Comment by Zimmi48** [comment]
Not yet. Feel free to open one, or I will eventually.

**Comment by ejgallego** [comment]
> Not yet. Feel free to open one, or I will eventually.

Thanks for opening #7720

**Comment by Zimmi48** [comment]
This PR was semantically depending on #7684. If you want to have it merged soon, you should remove the mli docs. The stdlib also doesn't make much sense to keep until #7720 is solved. Moreover the link to the refman needs to be updated after #7515. Finally, as I said in my review comment, I would prefer these links (this link actually, after the removal of the other two) to be in the preexisting documentation section of the README. If you don't have time for this, I can also take over.

**Pull request closed without merging**
