### PR TITLE
[api] Be more explicit about deprecation of debug printers.

### PR DESCRIPTION
**Pull request by ejgallego**
As suggested by @mattam82

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
This might be slightly too emphatic, but that's not really important. Will merge tomorrow.

**Comment by ejgallego** [comment]
> This might be slightly too emphatic, but that's not really important. Will merge tomorrow.

Let me try an alternate wording.

**Comment by Zimmi48** [comment]
Sorry for the noise. I thought in this case the rebase label was spurious but in fact it was not...

**Comment by ejgallego** [comment]
> Sorry for the noise. I thought in this case the rebase label was spurious but in fact it was not...

In fact it was not :) we are talking about a race of seconds :)

**Pull request merged**
