### PR TITLE
[dune] Fix PHONY target in Dune's helper makefile.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
In fact, none of these targets are telling me "missing PHONY" when I test them without the fix. So what is this fixing?

**Comment by ejgallego** [comment]
> In fact, none of these targets are telling me "missing PHONY" when I test them without the fix. So what is this fixing?

What do you mean? Targets that are not a file should be declared `PHONY` as to preventively avoid problems.

**Comment by Zimmi48** [comment]
OK it's just that I'm used to Makefile detecting these problems and raising a warning but here it wasn't the case.

**Comment by SkySkimmer** [comment]
That's actually a custom Coq thing

%:
	@echo "Error: no rule to make target $@ (or missing .PHONY)" && false

in Makefile.build

Since Makefile.dune doesn't include it that doesn't happen.

Gaëtan Gilbert

**Pull request merged**
