### PR TITLE
In Ltac, interpret constr arguments of an Ltac definition by default as open constr (with type classes inference)

### PR DESCRIPTION
**Pull request by herbelin**
This is an experience, initially suggested by the compatibility in #17084.

- [ ] Added / updated **test-suite**.
- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

### CODE REVIEW

**Comment by herbelin** [comment]
The failures in tlc and sf are both related to tlc's `rapply` which is "broken" since `refine` changed in 2015 (new proof engine), and which the PR makes working again (up to unwanted extra shelving). To evaluate if the impact of the PR on the `rapply` behavior is ok or not, the status of `rapply` should first be clarified.

The code failing in Mtac2 is associated to a comment `(** One tricky thing about our nice notation [!] is that it doesn't work for open terms: *)`. I don't know how to interpret the comment, that is: whether it is a good failure or not.

So, shortly, it is unclear at the current time whether the change is expected or not.

**Comment by JasonGross** [comment]
> the status of `rapply` should first be clarified.

Is this the same `rapply` as in the Coq stdlib?  I think the desired/ideal behavior of `rapply` is to interpret its arguments `uconstr`

**Comment by herbelin** [comment]
I did not know the `rapply` in the standard library. This actually seems worth to be moved from `Program` to `Init`.

The `rapply` of `tlc` is the same idea except that it is broken (it does not add `_`).

**Comment by ppedrot** [comment]
Closing this as it's explicitly branded as an experiment.

**Pull request closed without merging**
