### PR TITLE
Making coq_makefile usage consistent with what it claims + possibly fixing printing errors (was: Removing failure of coq_makefile on no arguments)

### PR DESCRIPTION
**Pull request by herbelin**
This is "brocante" day... cleaning the open branches I have, I found this minor fix to `coq_makefile`, whose usage says that all arguments are optional, but which in practice expects at least one argument.

I solved the inconsistency by accepting no arguments. One could have also fixed it by changing the usage. Don't know what the `coq_makefile` experts would prefer.

### CODE REVIEW

**Comment by gares** [comment]
In the manual I wrote
```
The recommended way of invoking coq_makefile is the following one:

coq_makefile -f _CoqProject -o CoqMakefile
```
so I think I'd rather try to make the checks on the command like stricter.

**Review by gares — CHANGES_REQUESTED** [review]
Please fix the usage message

**Comment by herbelin** [comment]
@gares: which argument would you like to be made mandatory?

**Comment by gares** [comment]
The `-o` one

**Comment by herbelin** [comment]
Fortunately, it is easy to test if `-o` has been given (with a test to the `Makefile` variable in `coqProject_file.ml4`). But I see that the same code is used to parse `_coqProject` files. Apparently, this means that a `_coqProject` file is able to have an option `-o` in it, and an option `-f` as well (since at least 8.3).

While at it, I fixed that problem.

There is however an extra problem which I'm not so expert to fix it. The problem is that error messages of `coqProject_file.ml4` are sent to a feedback (for use in CoqIDE I guess), but, when `coqProject_file.ml4` is called from `coq_makefile` the error messages are not displayed. So, I guess that either a feedback_feeder (is that the correct name?) should be given, or `coqProject_file.ml4` be able to work in two modes, with feedback or directly to stdout.

Note that I did not expect `-o file` to be the last option, so it can still be given at any place (on the contrary of what the usage is suggesting, but this tolerance is maybe not so important).

**Review by gares — APPROVED** [review]

**Comment by herbelin** [comment]
Adding a box for the remaining problem observed, so that we don't forget:
- [ ] Making error messages from `coqProject_file.ml4` be displayed when called from `coq_makefile`

**Comment by maximedenes** [comment]
> Making error messages from coqProject_file.ml4 be displayed when called from coq_makefile

Do you want to fix this in the current PR or another?

**Comment by herbelin** [comment]
> Do you want to fix this in the current PR or another?

I would need help from @ejgallego to know how to fix it in the proper way. So it depends on whether @ejgallego can look at it in the next days?

**Comment by ejgallego** [comment]
We should indeed add a helper for the tools, including `coqchk`; I planned to do that but however to do it cleanly I'd like to have solved the current coqtop / coqide hacks [due to missing error feedbacks].

@herbelin I will submit a PR shortly. Meanwhile, the idea of @silene of adding some kind of warning to the feedback system when there is no feeder is interesting [a warning that can be disabled, not a fatal error], I will try to give it a go.

**Comment by ejgallego** [comment]
Ok @herbelin #6087

**Comment by herbelin** [comment]
I added @ejgallego's magic line from #6087 but I did not take time to test. So, when #6087 will be merged, it will be good to check that this PR now compiles, and check that errors from the command line are now correctly printed.

**Comment by Zimmi48** [comment]
Given that the goal of this PR changed significantly since you opened it, could you change the title to reflect this? Thanks!

**Comment by maximedenes** [comment]
Closing and reopening to test after the merge of #6087

**Comment by maximedenes** [comment]
The test-suite timed out, so there seems to be something strange going on.

**Comment by herbelin** [comment]
The errors seem to be due to uses of `coq_makefile` w/o option `-o` in the test suite, or in some packages tested on Travis.

In the meantime, I added a new commit to improve the `usage` message depending on whether we parse the command line or a project file.

**Comment by herbelin** [comment]
@gares: what do you suggest: do you have the courage to modify the test files and tested packages which calls `coq_makefile` without a `-o` option?

**Comment by herbelin** [comment]
@gares: are you willing to change the packages and test which calls `coq_makefile` without the `-o` option? Otherwise, what do you think of finally renouncing to making `-o` mandatory?

**Comment by gares** [comment]
I've no energy for proposing a fix for all build failures.

**Comment by herbelin** [comment]
> I've no energy for proposing a fix for all build failures.

@gares: so, principle of reality and not requiring the `-o` argument? We could still say in the usage that `-o` is recommended.

**Comment by gares** [comment]
yes, that is  a good idea

**Comment by herbelin** [comment]
Updating according to recent discussion.

**Pull request merged**
