### PR TITLE
Remove bugged test of leaking evars in class_tactics

### LINKED ISSUE #5243: Anomaly in class_tactics.ml with give_up in Hint Extern
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5243
From: @Zimmi48
Reported version: 8.6
CC:   @ppedrot

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #5243

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
The bench failures are because of an unrelated overlay merge. Considering mathcomp isn't a big typeclass user and big typeclass users show no change I don't think we need to run a new bench.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
