### PR TITLE
Fixing an incompleteness of Rtree.inter

### PR DESCRIPTION
**Pull request by herbelin**
While working on #17950, I found an incompleteness of `Rtree.inter`, that is a case of two equal recursive trees whose computation of the intersection was raising an `assert false`.

The incompleteness is visible for instance when computing the intersection of:
```ocaml
Rec{Mrec[Top.Wrapper, 0],
    [(Rec{Nested[Top.Unwrapper, 0], [(), (#1:0)]})]}
```
and
```ocaml
Rec{Nested[Top.Wrapper, 0],
    [(Rec{Mrec[Top.Unwrapper, 0], [(), (Rec{Nested[Top.Wrapper, 0], [(#1:0)]})]})]}     
```
which are two equivalent regular trees for `Wrapper Unwrapper` from the following example (wish #9045):
```coq
Inductive Wrapper (T : Type) := Wrap : T -> Wrapper T.
Inductive Unwrapper :=
  | Empty : Unwrapper
  | Unwrap : Wrapper Unwrapper -> Unwrapper.                                   
```

I believe this PR to reconstruct the "intended" behavior of `Rtree.inter`, that is:
- for efficiency purpose, the expansion of recursive trees was avoided and the instantiation of recursive variables was delayed;
- but at the time of checking if an intersection problem of the exact same form had already been encountered, the code was forgetting that the recursive variables were not instantiated. Ensuring this instantiation is what the PR does.

As far as I can judge, if the recursive structure of inductive types is built incrementally (without never recomputing afterwards the structure of an instantiated type), all instances of a given type shares the same structure as a regular tree and an incompleteness cannot be met. But #17950 recomputes the recursive structure of instantiated types.

Note: something better can maybe be done when in presence of different presentations of a mutual inductive types (as before and after applying Bekić's theorem), but the PR does not modify that part.

### CODE REVIEW

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
> Why's this still draft?

The situation is more complex than I thought. I had made several experiments in the context of #17950:
- what worked is that I could get a variant of #17950 using recursive arguments with parameters (and which then does not need this PR)
- however, when trying to support dynamic recomputation of the recursive struture of fixpoints, I met various problems, one of them being an inefficiency problem; it seems that Maxime and Bruno fell on efficiency issues too and that may be the reason why `Rtree.inter` has been kept incomplete; so, what to do exactly to get the most general case of #17950 is still unclear to me.

**Comment by proux01** [comment]
Likely not ready for upcoming 8.20 branching (I guess, considering it's still a draft), removing the milestone.

**Comment by herbelin** [comment]
Yes, I'm stuck on finding a good solution to the whole issue. I can even close the PR.

**Pull request closed without merging**
