### PR TITLE
Supporting fix and cofix in Ltac pattern-matching (wish #7092)

### LINKED ISSUE #7092: Ltac matching on (co)fix should be supported
#### Version

8.8+alpha

#### Description of the problem

I'd like something like this to work:
```coq
Goal True.
  lazymatch (eval cbv delta [Nat.add] in Nat.add) with
  | (fix F (n : nat) (v : ?A) {struct n} : @?P n v
     := match n with
        | O => @?O_case v
        | S n' => @?S_case n' v (F n')
        end)
    => unify O_case (fun v : nat => v);
         unify S_case (fun (p : nat) (m : nat) (add_p : nat -> nat)
                       => S (add_p m))
  end.
```
Note that doing it in exactly this way would require #7091, but this should also work (but is less convenient for my needs):
```coq
Goal True.
  lazymatch (eval cbv delta [Nat.add] in Nat.add) with
  | (fix F (n : nat) (v : ?A) {struct n} : @?P n v
     := match n with
        | O => @?O_case v
        | S n' => @?S_case n' v F
        end)
    => unify O_case (fun v : nat => v);
         unify S_case (fun (p : nat) (m : nat) (add : nat -> nat -> nat)
                       => S (add p m))
  end.
```

cc @herbelin @ppedrot

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

Github magic word: closes #7092.

This includes:
- accepting a full pattern rather than just a constr in `PFix` and `PCoFIx` (i.e. support for metavariables in `fix` expressions)
- completing a few functions which were failing on `PFix` and `PCoFix`
- improving Ltac existing pattern-matching code for `fix` and `cofix` avoiding useless "collision between bound variable names" messages
- a couple of mini-restructurations on the way

- [x] Entry added in CHANGES.

### CODE REVIEW

**Comment by JasonGross** [comment]
Thanks!  Does Ltac now support matching on every kind of thing other than casts? (I seem to recall there being some issue with metavariables in return clauses (maybe with as or in or something), and I'm wondering if that's been fixed, and also if there are any other missing edge cases.)

**Comment by herbelin** [comment]
> I seem to recall there being some issue with metavariables in return clauses (maybe with as or in or something, and I'm wondering if that's been fixed, and also if there are any other missing edge cases.)

I vaguely remember an issue in binding variable names in the `return` clause but my memory is not strong enough to clearly. Here is a list of some closed issues mentioned in the file implementing `match`/`lazymatch`: #5434, #2602, #5487, #4198.

**Review by ppedrot — APPROVED** [review]
As far as I'm concerned it is a welcome enhancement and the code looks OK to me. There is a test and a change entry so that's good to go.

**Comment by maximedenes** [comment]
@ppedrot this was merge without the approval of the other two code owners. When that is wanted, please indicate why you feel their review of their component is useful before merging.

**Comment by maximedenes** [comment]
In this case, the `pretyper` received some non-trivial changes, so I don't understand why a review from @mattam82 was not required. And `pretyper` similarly, for which the secondary maintainer @ejgallego wasn't even assigned as a reviewer...

**Comment by ppedrot** [comment]
@maximedenes The changes in the detyper were moving code around and minor refactoring. I thought it didn't really require an in-depth review...

**Comment by ejgallego** [comment]
Yup in particular this at least needs a benchmark, even tho it looks good.

**Comment by ejgallego** [comment]
Hopefully someone can provide automatic performance testing for PRs soon.

**Comment by maximedenes** [comment]
> The changes in the detyper were moving code around and minor refactoring. I thought it didn't really require an in-depth review...

In many cases, code movement should be briefly reviewed by maintainers. The changes in `interp` don't look trivial to me (it even fixes a `FIXME`), similarly for `interp/constr_matching` and in `intf` a natural question was why `PFix` no longer takes a `fixpoint` for example.

**Comment by ppedrot** [comment]
> in intf a natural question was why PFix no longer takes a fixpoint for example.

Well, for that one, that's the whole point of the PR.

**Comment by maximedenes** [comment]
> Well, for that one, that's the whole point of the PR.

Yes, but my point is that it takes an ad-hoc tuple whereas it was previously taking a defined type.

**Comment by herbelin** [comment]
> Yes, but my point is that it takes an ad-hoc tuple whereas it was previously taking a defined type. The new interface is much less readable.

I actually hesitated to give a name to this tuple. I could have done it.

**Comment by SkySkimmer** [comment]
There's the polymorphic Constr.pfixpoint already existing.

Gaëtan Gilbert

**Comment by ppedrot** [comment]
Hum, indeed I probably have screwed the merge of this PR. Do we have a formal process in that case? Revert?

**Comment by maximedenes** [comment]
I don't think a revert is necessary, we can adjust things in another PR. You may want to make sure maintainers have a look at this PR, since their filter probably excludes closed/merged PRs. My remarks were mainly for the next ones you'll shepherd.

**Comment by ejgallego** [comment]
Yeah revert is overkill, if we want some change let's just open an issue to remember and that is.

**Comment by ejgallego** [comment]
Bench here https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/379/

**Pull request merged**
