### PR TITLE
[release] bump version to 8.18+rc1

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
@coqbot run full ci

**Comment by Zimmi48** [comment]
If this was for 8.18+rc1, why was this put in the 8.18.0 milestone?

**Comment by gares** [comment]
I had a problem with the milestone handling in the release process, in particular after all PR were backported and the change log closed we had to pause for one week, and people continued adding PRS, so I did close it forgetting a few PRS were not in yet.

**Comment by Zimmi48** [comment]
Closing the milestone is indeed a good strategy to let people know they shouldn't add new PRs in it, but it doesn't mean that you cannot add PRs in the closed milestone anyway. When clicking on the milestone selection, you have an open tab and a closed tab.

**Pull request merged**
