### PR TITLE
CI: build lambdaRust (which depends on Iris) rather than just Iris

### PR DESCRIPTION
**Pull request by RalfJung**
The title pretty much says it all...

### CODE REVIEW

**Comment by RalfJung** [comment]
Looks like CI is happy :)

**Comment by SkySkimmer** [comment]
`ci-iris-coq.sh` should probably be renamed to `ci-lambda-rust.sh` (or maybe `ci-iris-and-lambda-rust.sh`?).
Note that this requires changes in `Makefile.ci`, `.travis.yml` and `.gitlab-ci.yml`.

The version detection makes me uncomfortable somehow but there doesn't seem to be a way around it.

**Comment by RalfJung** [comment]
> ci-iris-coq.sh should probably be renamed to ci-lambda-rust.sh (or maybe ci-iris-and-lambda-rust.sh?).

Well, if we interpret Iris to also mean "... and some of its ecosystem"... ;)
But sure, I can rename. I'd just prefer if Iris stayed in the name somehow, so that people don't forget that this *also* tests Iris.

> The version detection makes me uncomfortable somehow but there doesn't seem to be a way around it.

I advocated for a more opam-based approach previously, bot nobody liked it. ;)

**Comment by ejgallego** [comment]
> The version detection makes me uncomfortable somehow but there doesn't seem to be a way around it.

We will eventually move that to a common library function, I hope.

**Review by ejgallego — APPROVED** [review]
Good to go, we should move some of this functionality to our common "CI-lib" in the future.

**Comment by RalfJung** [comment]
So should I rename the file and target now, or not?

**Comment by ejgallego** [comment]
> So should I rename the file and target now, or not?

Please do, sorry for the omission.

**Comment by RalfJung** [comment]
Done. Let's see if this works.

**Comment by RalfJung** [comment]
Looks like CI is happy.

**Pull request merged**
