### PR TITLE
Remove Evd.evars_reset_evd from the API.

### PR DESCRIPTION
**Pull request by ppedrot**
It was a legacy function. All its three uses have been simplified to either nothing or just setting the metas.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
The only change that could introduce a difference is the instantiate one, and that's a very rarely used tactic. Do you fear this PR could be observable at all?

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]
It feels a bit wasteful to fold through the metas instead of setting a pointer to the correct map but the bench indicates that it doesn't actually matter.

**Pull request merged**
