### PR TITLE
fix(coq.opam.docker): Remove leftover `make byte`

### PR DESCRIPTION
**Pull request by erikmd**
Context: [this Zulip topic](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Why.20.60coqorg.2Fcoq.3Adev.60.20FTBFS.20currently.3F/near/270316804).

* Fixes https://github.com/coq/coq/commit/6184404b74da850ecebc16d33a3784e2867a10cb (incomplete cleanup commit)

* Related: https://github.com/coq/coq/pull/15506

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
Shouldn't this file be in https://github.com/coq-community/docker-coq nstead of here?

**Comment by Zimmi48** [comment]
I guess the point for being there was precisely that a PR like #15506 could have fixed it directly.

**Comment by SkySkimmer** [comment]
But it's not in CI so there's no actual chance of that

**Pull request merged**
