### PR TITLE
[ci] Add plugin-tutorial to CI.

### LINKED ISSUE #7618: Adding the plugin tutorial to CI
Reminder to add https://github.com/ybertot/plugin_tutorials to the CI.

### PR DESCRIPTION
**Pull request by ejgallego**
This closes #7618.

### CODE REVIEW

**Comment by ejgallego** [comment]
The tutorial is currently broken wrt to `master`, thus this PR is blocked on https://github.com/ybertot/plugin_tutorials/issues/9

**Comment by ejgallego** [comment]
Should be ready to go once CI blesses it.

**Comment by ejgallego** [comment]
Appveyor failure is spurious [overtime?]

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
Meeerci !

**Pull request merged**
