### PR TITLE
Documenting and reorganizing prettyp.ml; showing implicit arguments also in the main type shown by "Print"

### PR DESCRIPTION
**Pull request by herbelin**
The PR first makes a new pass of documentation and reorganization of `prettyp.ml`.

Then, it adds printing of implicit arguments in the main type printed by `Print`, and not only in the unfolded type. E.g.:

```coq
Print fst.
(* Before:
fst =
fun (A B : Type) (p : A * B) => let (x, _) := p in x
     : forall A B : Type, A * B -> A
*)
(* After:
fst =
fun (A B : Type) (p : A * B) => let (x, _) := p in x
     : forall {A B : Type}, A * B -> A
*)
```

Maybe the printing of `Arguments` can then be removed in `Print`?

What to exactly provide for GUIs supporting hovering to be discussed.

- [x] Added / updated **test-suite**.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Merging soon if no complaints.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@herbelin this probably needs a changelog, it's a user-visible change.

**Comment by proux01** [comment]
> ```coq
> (* Before:
> fst =
> fun (A B : Type) (p : A * B) => let (x, _) := p in x
>      : forall {A B : Type}, A * B -> A
> *)
> (* After:
> fst =
> fun (A B : Type) (p : A * B) => let (x, _) := p in x
>      : forall {A B : Type}, A * B -> A
> *)
> ```
I'm not able to spot any difference?

**Comment by SkySkimmer** [comment]
I see `: forall A B : Type, ...` (no implicits) before. See also the diff of output tests.

**Comment by ppedrot** [comment]
Let's not start mixing features in a PR. This one is already borderline at it mixes cleanups with a small tweak, so let's merge it fast before it turns into a potpourri.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
