### PR TITLE
[micromega] use Coqlib.lib_ref to get Coq constants.

### LINKED ISSUE #11739: micromega should be ported to `Coqlib.lib_ref`
Like a few other plugins, micromega is using a deprecated `Coqlib` API. See for example: 

https://github.com/coq/coq/blob/18aa9ca60ec9b3d1712276ec0c615dfe54c1a251/plugins/micromega/coq_micromega.ml#L218-L223

Current work on stdlib2 requires it to be ported to `Coqlib.lib_ref`.

Could we get some help from @coq/micromega-maintainers on this issue?

### PR DESCRIPTION
**Pull request by fajb**
Port micromega to the Coqlib.lib_ref API.

Closes  #11739.

### CODE REVIEW

**Comment by ppedrot** [comment]
This needs an assignee. Also, I think we should have a common discussion about the registration mechanism, I don't think there is a point in going through indirections for globals that are not meant to be dynamically replaced, e.g. here the micromega specific constants. There is already an OCaml-Coq FFI, and that's the name of the constant.

**Comment by silene** [comment]
> I don't think there is a point in going through indirections for globals that are not meant to be dynamically replaced

That is my opinion too.

**Comment by maximedenes** [comment]
> I don't think there is a point in going through indirections for globals that are not meant to be dynamically replaced, e.g. here the micromega specific constants. There is already an OCaml-Coq FFI, and that's the name of the constant.

Can you be more explicit about what you mean by that?

E.g. if we port micromega's theories to stdlib2, how do we reuse the plugin?

**Comment by ppedrot** [comment]
The question is: does it make sense to replace, say, the `micromega.GFormula.TT` constructor if you port micromega to stdlib2?

**Comment by maximedenes** [comment]
> The question is: does it make sense to replace, say, the `micromega.GFormula.TT` constructor if you port micromega to stdlib2?

I guess, yes, we could try to replace it with a universe polymorphic one, for example (some other constructors in this type take a `Type`).

**Comment by silene** [comment]
> if we port micromega's theories to stdlib2, how do we reuse the plugin?

Is there anything wrong with the `Add Ring` approach? That is, registering structures that make it possible to use a tactic plugin with any similar types.

**Comment by ppedrot** [comment]
@maximedenes That was the typical counter-example I was going to actually point at. Thanks for summoning it! If you go universe polymorphic, you need to rewrite the whole plugin. So there is no point in sharing the ML code.

**Comment by maximedenes** [comment]
> If you go universe polymorphic, you need to rewrite the whole plugin

Really? Does it mean we have no good transition strategy to offer to such plugins? Or is there a specific difficulty?

**Comment by ppedrot** [comment]
> Does it mean we have no good transition strategy to offer to such plugins?

I tried and failed. Reflection in OCaml in a universe-polymorphic world is hell.

**Comment by ppedrot** [comment]
(That is, with the constraint that you want to be efficient and not allocate gazillions of universes that will all be unified to the same one in the end.)

**Comment by fajb** [comment]
Is there a consensus about what to do with this PR? Should I just trash it?

**Comment by maximedenes** [comment]
@fajb I still think this PR is an improvement compared to the existing.

@ppedrot What would be the plan for stdlib2 if we don't merge this PR? Micromega's constants are today hardwired in stdlib1's namespace `Coq.XXX`.

**Comment by Zimmi48** [comment]
There's no reason why this PR should not get merged. Some alternative standard libraries may wish to use an existing plugin with other theory files and there's no reason not to allow that (even if the definitions have to be the same).

**Comment by ppedrot** [comment]
FTR I was not complaining about this particular PR, more about the general rules on binding constants Coq-side.

**Comment by Zimmi48** [comment]
But my comment also responds to the general complaint, doesn't it?

**Comment by MSoegtropIMC** [comment]
My opinion on this is that it is a matter of cleanliness to declare the interface of software modules. If OCaml modules access Coq symbols, these should be declared as "exported to OCaml" regardless of the question if we can foresee good reasons for changing them for these reasons:

1.) It is good documentation telling people that they will break a plugin if they change these symbols
2.) Other people writing similar plugins will more likely choose the same set of symbols
3.) The exported set of symbols can be actively designed during library design
4.) It doesn't make a lot of sense to have two mechanisms to access Coq symbols from OCaml, one for "likely to change" symbols and one for "not likely to change" symbols.

**Review by maximedenes — APPROVED** [review]

**Comment by herbelin** [comment]
What is the exact summary? Is this ready for 8.12?

**Pull request merged**
