### PR TITLE
Correct some spelling errors

### PR DESCRIPTION
**Pull request by bbarenblat**
**Kind:** infrastructure

Lintian found some spelling errors in the Debian packaging for coq. Fix them most places they appear in the current source. (Don’t change documentation anchor names, as that would invalidate external deeplinks.)

This also fixes a bug in coqdoc: prior to this commit, coqdoc would highlight `instanciate` but not `instantiate`.

### CODE REVIEW

**Review by gares — APPROVED** [review]
thanks!

**Review by ejgallego — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
I'm afraid this needs a rebase.

**Comment by Zimmi48** [comment]
Please use `git rebase master --whitespace=fix` to fix the whitespace problems at the same time.

**Comment by herbelin** [comment]
I'm afraid that the PR is not among the priority of the user. I made a rebase [here](https://github.com/herbelin/github-coq/tree/bbarenblat-pr8117). 

@bbarenblat, in case you see this message, can you confirm that you'd be glad that someone takes your PR over? In this case, I shall force-push the rebase I made to the PR.

@maximedenes, you are assignee, what are your plans? This PR is purely about spell-checking. Do you intend to continue to manage it (and otherwise don't hesitate to put me as assignee)?

To be noticed: the PR induces two spelling changes of the API (but presumably in code of no interest for plugin - `future.mli`).

**Comment by bbarenblat** [comment]
@herbelin: I’d be happy for you to take over the PR. I’d still like to see this happen, but as you’ve noted, it has not been at the top of my priority list.

**Comment by herbelin** [comment]
OK, closing this one then. See #8589 for the rebase. Thanks for having reported.

**Pull request closed without merging**
