### PR TITLE
Legacy refiner handle eta-expanded case analysis

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** architecture (preliminary step towards enforcing the model of cep [#34](https://github.com/coq/ceps/pull/34)).

We prepare the legacy refiner to deal with eta-expanded case-analysis schemes. For that, we need to treat the binders in the branches of a `match` in an ad hoc way as the `Refine` method of legacy refiner (`Logic.prim_refiner`) was originally able to deal only with purely applicative terms.

This is in prevision of enforcing cep [#34](https://github.com/coq/ceps/pull/34) which itself aims at fixing a couple of issues due to the mismatch between the user view and the implemented view of `match`.

Note: it is planned that `logic.ml` disappear. When it will, this temporary code could be removed.

### CODE REVIEW

**Comment by herbelin** [comment]
I believe this PR is no risk. It extends the support for case analysis scheme in the old refiner and it shall eventually disappear with the the old refiner.

**Review by ppedrot — APPROVED** [review]
By no means I understand the old engine enough to assess that this is OK, but I trust @herbelin enough to believe it is indeed fine. CI also adds evidence to that. Anyways, the old engine is probably bound to disappear soon (8.9? 8.10?), and giving strychnine to a dying man cannot hurt that much. So I approve inclusion. Should you disagree, please voice your concerns!

**Comment by maximedenes** [comment]
Probably a naive question, but how easy will it be to port this feature to evarconv (as part of "unifall")?

**Comment by herbelin** [comment]
> I guess it is already supported by evarconv, but it would be good to see a confirmation.

Actually, the feature is not about unification but about `refine`. The old _internal_ "refiner" (which was implemented in `logic.ml`) had a special node called `Refine` which was able to deal only with purely applicative nodes (`App`/`Case`) without any binders in them. (Not to be confused with the old _external_ `refine` (implemented in `tactics/refine.ml`) which was an implementation of the legacy  `refine` tactic on top of the old (limited) internal "refiner" of `logic.ml`!)

The new refiner (`proofs/refiner.ml`) already takes an arbitrary term (including binders). So, there is indeed nothing to "port".

**Pull request merged**
