### PR TITLE
Wrap notice feedback in `<infomsg>`, in `-emacs` mode

### LINKED ISSUE #11501: `(* debug eauto: *)` incorrectly fails to be wrapped in <infomsg>
#### Description of the problem

```
$ echo 'Set Debug Eauto. Goal True. eauto.' | coqtop -emacs -q
Welcome to Coq 8.10.0 (January 2020)
Skipping rcfile loading.

<prompt>Coq < 1 || 0 < </prompt>
<prompt>Coq < 2 || 0 < </prompt>1 subgoal (ID 1)

  ============================
  True

<prompt>Unnamed_thm < 3 |branch| 0 < </prompt>(* debug eauto: *)
<infomsg>Debug: 1 depth=5 </infomsg>
<infomsg>Debug: 1.1 depth=5 exact I</infomsg>
No more subgoals.

<prompt>Unnamed_thm < 4 |branch| 0 < </prompt>
```

#### Coq Version

8.10.0, also 8.11.0

### PR DESCRIPTION
**Pull request by maximedenes**
Fixes #11501

### CODE REVIEW

**Comment by maximedenes** [comment]
@Matafou can you try this out? Thanks!

**Comment by Matafou** [comment]
Tried.

It works but it breaks the ltac debugging mode in PG (which dispatches goals vs debug messages in the 2 output buffers). This is because in Ltac debug mode goals are displayed as Notice (together with other information), which is probably not very accurate.

**Comment by maximedenes** [comment]
> which is probably not very accurate

Can you make explicit why it is not accurate?

**Comment by Matafou** [comment]
I am not sure of the significance of Notice vs Debug vs Info. Do they nest?

During Ltac debug (not debug Eauto) a lot of informations are displayed after each hit on `return`. Among them intermediate goals, and other information about recursive calls etc.

Morally these are all debug informations so at first sight it should be "debug" and not "Notice". That is why I think message categories are not accurate in ltac debug mode.

On second sight we want these goals to be dispatched in goals buffer, and the other outputs to the response buffer. So ideally these messages should be categorized differently, even if they are all debugging messages.

Currently (before the present patch) this is the case: goals are displayed Notice (without any tag) and other messages are "infomsg". This is not accurate but it works.  With your patch they are all infomsg.

We should probably revamp all this more deeply.

**Comment by maximedenes** [comment]
Thanks for testing!

My understanding is that debug feedback are for Coq debug facilities (i.e. useful to Coq / plugin developers). The Ltac debugger is at another level, IMHO, it is a debugging facility for user programs.

Anyway, I'll be happy to implement any encoding that suits PG.

**Comment by Matafou** [comment]
> The Ltac debugger is at another level, IMHO, it is a debugging facility for user programs.

That makes perfectly sense to me but <here would you put `Set Ltac Eauto.`  and `Set Ltac Debug`? To me they look equally useful to then end user (that is a advanced user using Ltac).

Maybe during debug goals  should be "Info" and other infos should be "Notice". Let me think about it for some time.

**Comment by Matafou** [comment]
Actually it breaks even the Normal displaying of goals (which is a Notice).
So basically goals (normal and debug) should have there own tag in -emacs mode. I wonder if this is possible in the current state of coq loggers.

**Comment by Matafou** [comment]
I have a naive question: what is the purpose of the "(* eauto debug *)" being in a different category than the remaining of the output?

**Comment by maximedenes** [comment]
> I have a naive question: what is the purpose of the "(* eauto debug *)" being in a different category than the remaining of the output?

That seems strange indeed.

> So basically goals (normal and debug) should have there own tag in -emacs mode. I wonder if this is possible in the current state of coq loggers.

I think it is possible. Maybe we should have a quick call to discuss a bit what is desirable for PG, and I can try to implement it, WDYT?

**Comment by Matafou** [comment]
OK.

**Comment by maximedenes** [comment]
@Matafou Following our call today, I updated this branch with a fix for `debug eauto`, and a specific `<notice>` wrapper for notice Feedback.

I'll wait for your feedback on the PG side before asking to merge this PR, if everything works ok.

**Comment by Matafou** [comment]
I came up with something that seems to works (https://github.com/Matafou/PG/tree/new-coq-noticetag) but something is wrong in the pretty printing: you should add a newline  after <notice>. Otherwise coq's boxed pretty printing (in particular in goals) is wildly shifting everything to the right. And since PG does not perform any kind of pretty printing.

Actually it should also be done for other kinds of messages too, but it is less of a problem.

**Comment by Matafou** [comment]
@maximedenes can you modify this PR so that the `<notice>` tag become `<notice>\n` please?
Otherwise the whole pretty printing of coq is broken (PG prints goals and messages "as is").

You may also add this newline to `<infomsg>` by the way, although it is less important.

**Comment by Matafou** [comment]
I am all for this PR once the missing newline is added.

**Comment by SkySkimmer** [comment]
@Matafou it should print newlines now.

**Comment by ejgallego** [comment]
Needs a tweak on the test-suite. I understand this is something desirable in 8.12, however we are maybe a bit late as not to risk PG breakage?

**Comment by Matafou** [comment]
Yes, this is maybe a bit late now. I will make some tests.

**Comment by maximedenes** [comment]
@Matafou do you still need this for PG?

**Comment by Matafou** [comment]
This is not needed. It was first proposed to fix  #11501 that is not very important and it eventually went beyond (trying to reorganize coqtop output categorization). I think we should just put "(* eauto debug *)" inside the same category than the remaining of `Set Debug Eauto.` and forget about reorganization for now.

**Comment by Matafou** [comment]
I am fine with closing this PR or reducing it to just putting `(* eauto debug *)` in the same ouput category than the remaining of `Set Debug Eauto.`. But really closing is not a problem IMHO, bug #11501 is no big deal (@JasonGross do you confirm?).

**Pull request closed without merging**
