### PR TITLE
[ci] Add Ltac2

### PR DESCRIPTION
**Pull request by JasonGross**
This is blocked on https://github.com/ppedrot/ltac2/pull/31 (and on travis passing Ltac2, obviously).  Hopefully this being a ci will prevent future similar breakages.

### CODE REVIEW

**Comment by ejgallego** [comment]
Given that the developer of LTAC2 is a core Coq developer I think it corresponds to him to make the choice of including LTAC2 in the CI, decision that obviously have my utmost blessings.

**Review by SkySkimmer — APPROVED** [review]
Looks fine.

**Comment by ppedrot** [comment]
I'm OK for adding Ltac2 to the CI. Actually I was even considering starting implementing it.

**Review by ppedrot — APPROVED** [review]
I'm no Travis specialist but this looks OK.

**Comment by maximedenes** [comment]
closing / reopening since the build of Ltac2 appears to have failed.

**Pull request merged**
