### PR TITLE
Add Z.mod_div lemma to standard library.

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Should I be adding some of these as hints to zarith?

### CODE REVIEW

**Comment by ejgallego** [comment]
It seems the stdlib doesn't compile.

**Comment by roconnor-blockstream** [comment]
Sorry, I pushed a "trivial" change.  I'll be more careful in the future.

It is fixed now.

**Comment by ejgallego** [comment]
No worries, if your change creates some problem Travis is likely to notice.

**Review by letouzey — APPROVED** [review]
Looks good to me

**Comment by maximedenes** [comment]
Merged in master, thanks for contributing!

**Pull request merged**
