### PR TITLE
CI: allow_failure for fiat_crypto_ocaml

### PR DESCRIPTION
**Pull request by SkySkimmer**
Failing since https://gitlab.com/coq/coq/-/jobs/2537542809 (the PR's
CI succeeded https://gitlab.com/coq/coq/-/jobs/2527415579)

cc @JasonGross

### CODE REVIEW

**Review by Alizter — APPROVED** [review]
Just to be clear, this is broken upstream right? I couldn't tell from their CI.

**Comment by SkySkimmer** [comment]
No idea what's wrong, the error message isn't exactly informative, but I don't see how it could be our bug since it just started appearing AFAICT

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
PRs merged, please revert.  (Or I can make a PR reverting this)

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/16155

**Comment by SkySkimmer** [comment]
>(I'd prefer in the future a bit more time to fix fiat-crypto before it's declared allowed failure.)

Personally I think we should be more agressive with putting allow_failure. In this case we left it to fail for a few days vaguely hoping it would get fixed, I don't think you were even contacted. Immediately opening a PR to allow_failure would be a clear point to contact people about their stuff failing in CI.

**Comment by JasonGross** [comment]
Ah, yeah, I was not aware of this until I woke up to this PR being merged.  I think opening the PR immediately and tagging is a good idea; the thing I was requesting was having more than 4 hours (which this time all occurred when I was still asleep, I believe) between when I'm tagged and when the allow failure PR is merged.

**Comment by SkySkimmer** [comment]
What's the point of leaving it failing, even if the allow_failure would get reverted quickly?

**Comment by JasonGross** [comment]
I guess if you or whomever creates the allow failure PR is also happy to create the reversion PR, I have no objection.  It might even be nice to create the reversion PR as a draft as soon as the allow failure PR is merged, so that there's a canonical place to restart the relevant job and test out fixes?

**Comment by Alizter** [comment]
It would be nice if we could say `@coqbot ci fiat-crypto is broken` or something and then it created a allow-failure and revert PR for us to merge.

**Comment by Zimmi48** [comment]
Sounds good. Feel free to open an issue on the bot repository so that we remember about this idea.

**Pull request merged**
