### PR TITLE
Fix test suite after parallel merge of #15340 and #15343

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge when CI green

**Comment by ppedrot** [comment]
@coqbot if you are listening to us, knock three times.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
That's https://github.com/coq/bot/issues/108

**Pull request merged**
