### PR TITLE
Split coq package into coq-base and coq

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
This is an initial attempt at splitting Coq's standard library from the rest. The Ocaml code is called `coq-base` and the stdlib `coq` for backwards compatibility reasons. The original motivation for this was a proposal by @silene here: https://github.com/coq/opam-coq-archive/pull/1488#issuecomment-738001867. However, I suppose this is useful for other things as well. (1) Libraries like HoTT don't need to depend on the stdlib. (2) Something like this probably needs to be done when stdlib2 is released.

There are some issues with this PR:
- Ltac2 is currently still compiled together with the standard library. This is because otherwise, it needs a `-noinit` flag. However, when I add this, then `coqdep` throws a tantrum about not being able to find the `-coqlib`. I suppose this is a bug with Dune, because it needs to add `-boot` to `coqdep`?
- The split results in the libraries being split over the directories `lib/coq-base/` and `lib/coq/`. This is a problem because Coq expects everything to be in the same directory (for example, when using `-coqlib`). I can see several potential solutions for this:
  1. Convince opam/dune to install both packages into the directory `lib/coq/`. I've not been able to figure out how to do this yet.
  2. Create symlinks from `lib/coq-base` to `lib/coq`. I've not managed to get dune to do that either
  3. Modify Coq to load from both of these directories. The downside is that this would be a breaking change because modifications to the `-coqlib` argument (and probably other things) would be needed.
- I've kept the tests as part of `coq` because otherwise the tests would probably need to be split into two as well. For this reason `coq-doc` also depends on `coq`.

Thoughts/suggestions/comments anyone?

**Kind:** infrastructure.

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by ejgallego** [comment]
Note an existing proposal here https://github.com/coq/coq/pull/12567

**Comment by LasseBlaauwbroek** [comment]
Ah, I was not aware of that one. Shall I close this?

**Comment by ejgallego** [comment]
> Ah, I was not aware of that one. Shall I close this?

Let me get that one up-to-date and compare, I didn't try Rudi suggestion yet, but if I recall correctly, some of the problems you identified above were working on the other branch.

I know it is frustrating the large amount of PRs and issues Coq has, I'd suggest that in terms of infrastructure, and before doing all this large amount of work, to ping devs on gitter to see what the status is. The dune migration / build infrastructure rework has unfortunately a lot of in-progress work, so the situation is not good, sorry for that.

**Comment by LasseBlaauwbroek** [comment]
No problem, in this case @silene suggested this and I just went with it. But I suppose he also didn't know about the other PR.

In the end I now know more about Coq's build system so that's good :-)

**Comment by ejgallego** [comment]
PRs are very similar, except that #12567 introduces coq-stdlib, so my preference is to go with that one then, but we need to wait from potentially interested shephers.

**Comment by ejgallego** [comment]
I have made a lot of progress with #12567 to the point that I feel this PR is not needed; I did a diff between the two branches and things seem OK.

Regarding the most critical point which is that the plugins will go now under `coq-base`, this hopefully will be solved very soon as once I can get #12567 and #13617 in, I will remove all plugin handling code from Coq in favor of findlib's `Fl_dynlink` which can locate things symbolically, and moreover brings a whole new array of advantages, including proper handling of plugins with dependencies.

**Pull request closed without merging**
