### PR TITLE
ssr: fill_occ_pattern: return valid ustate even if no match (fix #6106)

### LINKED ISSUE #6106: Ltac call to "case (ssrcasearg) (ssrclauses)" failed. Conversion test raised an anomaly
#### Version

The Coq Proof Assistant, version 8.7.0 (November 2017)
compiled on Nov 7 2017 10:41:15 with OCaml 4.02.3

#### Operating system

GNU/Linux Debian 9.2 amd64

#### Description of the problem

I tried compiling a specific commit of Multinomials with Coq 8.7, namely
https://github.com/math-comp/multinomials/commit/5b46e50983ee68dd1b6932e7e4a3bfc1113e7360
(which already compiles [with Coq 8.5](https://travis-ci.org/CoqEAL/CoqEAL/jobs/298479845#L758) and [with Coq 8.6](https://travis-ci.org/CoqEAL/CoqEAL/jobs/298479844#L758))
but with Coq 8.7 and MathComp 1.6.4 I got the error
```
File "./finmap/finmap.v", line 2297, characters 0-72:
Error:
Ltac call to "by (ssrhintarg)" failed.
Conversion test raised an anomalyAnomaly
                                 "Universe SsrMultinomials.finmap.1382 undefined."
                                 Please report at http://coq.inria.fr/bugs/.
```

I extracted below a minimal working example to reproduce the bug (but the error message is not exactly the same). And maybe it could be further minified in order not to rely on eqtype/ssrnat/seq/finset/fintype...

```
From mathcomp Require Import ssreflect ssrfun ssrbool eqtype ssrnat seq finset fintype.

Lemma domf_cat_MWE (K : finType) (V : Type) (f g : V) (domf : V -> {set K}) (x : K) :
  (x \notin domf g) && (x \in domf f) || (x \in domf g) = (x \in domf f) || (x \in domf g).
case: (boolP (_ \in _)).
(* Toplevel input, characters 0-23: *)
(* > case: (boolP (_ \in _)). *)
(* > ^^^^^^^^^^^^^^^^^^^^^^^ *)
(* Error: *)
(* Ltac call to "case (ssrcasearg) (ssrclauses)" failed. *)
(* Conversion test raised an anomalyAnomaly "Universe Top.8 undefined."  *)
(* Please report at http://coq.inria.fr/bugs/. *)
Abort.
```

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
@Zimmi48 I've looked at the `CONTRIBUTING` file but I could not see how to ask for the fix to be backported (to 8.7 in this case). I put it in the milestone 8.7.1, is it ok?

**Comment by Zimmi48** [comment]
@gares Yes, it's OK to put the 8.7.1. Another way is to put it in the "Coq 8.7" project. Both ways are fine to me and you can even use both.
Otherwise, when there is no explicit demand, I find the information by myself by looking first if the PR is a bug fix or a documentation improvement, then in case it is a fix, if the bug that is fixed was reported on 8.7 (or earlier) or if it was a 8.8-only bug. In this case, it would have been easy for me to find the information since you put the bug number and the bug report is clearly tagged as a 8.7 regression.

**Comment by gares** [comment]
@erikmd reports this patch fixes his issue, so I guess we are good here.

**Comment by gares** [comment]
Updated the patch to make lint happy

**Comment by gares** [comment]
@maximedenes ping

**Comment by maximedenes** [comment]
Ok, we reviewed this together and found similar problems (in `fold`) that would be worth fixing at the same time.

**Review by maximedenes — DISMISSED** [review]
Let's fix `fold` (at least a bit) at the same time.

**Comment by Zimmi48** [comment]
Even if it's worth fixing at the same time, these problems should not delay the integration of this PR. We will gain nothing by missing the 8.7.1 milestone for this bugfix.

**Comment by Zimmi48** [comment]
@maximedenes Are you going to make this fix miss the 8.7.1 deadline?

**Comment by maximedenes** [comment]
Ok, let's merge this one and fix remaining problems as part of a larger cleanup.

**Comment by Zimmi48** [comment]
You can open an issue or put a reminder in the code.

**Pull request merged**
