### PR TITLE
Fix #6956: Uncaught exception in bytecode compilation

### LINKED ISSUE #6956: Uncaught exception Invalid_argument("index out of bounds") in bytecode compilation
The following code raises an uncaught exception `Invalid_argument("index out of bounds")` on 2069c0aec44a50031e33bcb9f7d86c1535ef6b84.
```
Set Universe Polymorphism.

Inductive t A : nat -> Type :=
| nil : t A 0
| cons : forall (h : A) (n : nat), t A n -> t A (S n).

Definition case0 {A} (P : t A 0 -> Type) (H : P (nil A)) v : P v :=
match v with
| nil _ => H
| _ => fun devil => False_ind (@IDProp) devil
end.
```
The backtrace is
```

Anomaly "Uncaught exception Invalid_argument("index out of bounds")."
Please report at http://coq.inria.fr/bugs/.
frame @ file "ide/xmlprotocol.ml", line 667, characters 29-46
frame @ file "ide/ide_slave.ml", line 406, characters 12-15
frame @ file "ide/ide_slave.ml", line 208, characters 13-28
frame @ file "stm/stm.ml", line 2646, characters 11-49
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 2635, characters 4-55
frame @ file "stm/stm.ml", line 2525, characters 4-100
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 934, characters 6-10
frame @ file "stm/stm.ml", line 2398, characters 16-43
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "stm/stm.ml", line 1087, characters 12-89
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2317, characters 4-36
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacentries.ml", line 2284, characters 8-666
frame @ file "lib/flags.ml", line 100, characters 20-44
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
frame @ file "vernac/comDefinition.ml", line 132, characters 12-179
frame @ file "vernac/declareDef.ml", line 60, characters 4-54
frame @ file "vernac/declareDef.ml", line 38, characters 11-77
frame @ file "interp/declare.ml", line 158, characters 23-36
frame @ file "library/lib.ml", line 240, characters 2-26
frame @ file "interp/declare.ml", line 91, characters 6-37
frame @ file "library/global.ml", line 73, characters 16-31
frame @ file "kernel/term_typing.ml", line 498, characters 2-76
frame @ file "kernel/environ.ml", line 473, characters 28-79
frame @ file "kernel/cbytegen.ml", line 901, characters 22-78
raise @ unknown
frame @ file "kernel/cbytegen.ml", line 866, characters 10-117
frame @ file "kernel/cbytegen.ml", line 135, characters 13-16
frame @ file "kernel/cbytegen.ml", line 630, characters 8-75
frame @ file "kernel/cbytegen.ml", line 135, characters 13-16
frame @ file "kernel/cbytegen.ml", line 535, characters 7-79
frame @ file "kernel/cbytegen.ml", line 135, characters 13-16
frame @ file "kernel/cbytegen.ml", line 422, characters 2-92
frame @ file "kernel/cbytegen.ml", line 630, characters 8-75
frame @ file "kernel/cbytegen.ml", line 135, characters 13-16
frame @ file "kernel/cbytegen.ml", line 535, characters 7-79
frame @ file "kernel/cbytegen.ml", line 135, characters 13-16
frame @ file "kernel/cbytegen.ml", line 535, characters 7-79
frame @ file "kernel/cbytegen.ml", line 135, characters 13-16
frame @ file "kernel/cbytegen.ml", line 507, characters 16-34
frame @ file "kernel/univ.ml", line 516, characters 18-41
frame @ file "kernel/univ.ml", line 519, characters 26-43
frame @ file "kernel/univ.ml", line 509, characters 7-18
frame @ file "kernel/univ.ml", line 189, characters 19-27
```
which seems to indicate a problem in universe compilation in the VM. Also, the bug is not there in 8.7.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by maximedenes** [comment]
@ppedrot can you test this against the development that revealed #6956 ?

**Comment by ppedrot** [comment]
I'm not sure that development is in any state that allows for proper testing... It's more like a bunch of half-compiling code than anything, but I can still try.

**Comment by maximedenes** [comment]
I'm not sure what to do w.r.t. code owners here. The secondary maintainer of the kernel is @barras, but we never heard back from him (is he still developing Coq?). Maybe we need another volunteer instead?

**Comment by ppedrot** [comment]
I think that kernel-affecting patches should be more carefully scrutinized by people, the owner system might be a bit limited here. People known to have messed a bit with the kernel recently include @mattam82, @SkySkimmer and myself, we could raise some highly transversal synergetic taskforce (with the help of AI obviously).

**Comment by maximedenes** [comment]
Ok, but I tend to think that would mean we need more maintainers for the kernel, not fewer...

Anyway, who is willing to review this? you or @SkySkimmer ?

**Comment by ppedrot** [comment]
Regarding the development, it's CoqHott/univalent_parametricity, and it seems it's not 8.8 compatible anyways, there is a unification failure where it succeeds in 8.7.

**Comment by maximedenes** [comment]
Is that a regression? If so, it should be reported.

**Comment by ppedrot** [comment]
@maximedenes Just a stupid change: the 8.8-introduced function `String.concat` shadows another local one. No reason to be afraid.

**Comment by SkySkimmer** [comment]
>Anyway, who is willing to review this? you or @SkySkimmer ? (@mattam82 is on vacation and this is solving a bug marked as blocker)

I don't understand the VM (here specifically what it does with universes) and this changed function is pretty tightly integrated so not me.

**Comment by ppedrot** [comment]
I can review it, I already had a look at the bug actually trying to solve it myself.

**Comment by maximedenes** [comment]
The root of the bug was the call to `remap_var u i j` that should have been `remap_var u i (j+1)`. I tried to make the code easier to understand.

**Comment by ppedrot** [comment]
Even if that probably doesn't matter, the algorithm seems quite naive to me, it looks like an insertion sort and is probably O(n²). Why don't you just build the set of variable indices in O(n log n) and return that? That would make the code even clearer...

**Comment by maximedenes** [comment]
Yes, it is O(n²) (where n is the number of local universe variables). I don't think it matters.

> just build the set of variable indices in O(n log n) and return that

You mean build this set, and get an ordered list of elements from that to represent the mapping?

**Comment by ppedrot** [comment]
> You mean build this set, and get an ordered list of elements from that to represent the mapping?

Yep. You would get intended meaning for free. The current patch still feels esoteric to me when compared to what the comment says.

**Comment by ppedrot** [comment]
@maximedenes Right, but after generating the substitution you apply it to the universe and *voilá*. Anyways, this is not really important, as long as the intent is expressed to a human I think it's fine.

**Comment by maximedenes** [comment]
> Right, but after generating the substitution you apply it to the universe and voilá. Anyways, this is not really important, as long as the intent is expressed to a human I think it's fine.

Don't I need to invert the substitution, then? What is the recommended way to do it efficiently?

**Comment by ppedrot** [comment]
I'd personally build the inverse substitution at the same time as the forward one, while folding over the argument universe.

**Review by ppedrot — APPROVED** [review]
That looks correct to me. And way more elegant that way, I might say!

**Comment by ppedrot** [comment]
@maximedenes Do you want me to take responsibility of the merge after the CI results?

**Comment by maximedenes** [comment]
Yeah, thanks for the suggestion. For some reason, I was trying hard to make sure the mapping was increasing, but it plays no role and was making things much trickier.

**Comment by maximedenes** [comment]
> Do you want me to take responsibility of the merge after the CI results?

Yes, please do.

**Comment by ppedrot** [comment]
Ltac2 failure unrelated, will merge.

**Comment by Zimmi48** [comment]
@maximedenes @ppedrot This is not eligible for backporting because this change a `.mli`. What to do?

**Comment by maximedenes** [comment]
IMHO an exception should be made here as
1. this is probably a critical bug fix (although I haven't spent time on trying to build a proof of false)
1. there probably isn't any client of the API changed here, because it was introduced just before the beta (to fix a critical bug)

**Comment by ppedrot** [comment]
It's possible to backport without changing the API anyways, it is sufficient to tweak the code of of `compact`.

**Comment by maximedenes** [comment]
But maybe we can first see if it breaks anything on the v8.8 branch?

**Comment by ppedrot** [comment]
Personally I wouldn't give a shit, as mentioned by @maximedenes this is an API that has been introduced recently and specifically for the VM...

**Comment by Zimmi48** [comment]
Thanks for the comments. Will backport then.

**Pull request merged**
