### PR TITLE
change Hint Extern btauto.Algebra.bool to #[export]

### PR DESCRIPTION
**Pull request by andres-erbsen**
- [x] Added **changelog**.

### CODE REVIEW

**Comment by andres-erbsen** [comment]
I don't understand what's up with the CI run for bedrock2, the bedrock2 repo has a fixup merged but it is not getting picked up. The failing log says [`CI_JOB_STARTED_AT=2023-02-23T22:42:41Z`](https://gitlab.com/coq/coq/-/jobs/3826692832#L244) and ran `git clone https://github.com/mit-plv/bedrock2` to [retrieve](https://gitlab.com/coq/coq/-/jobs/3826692832#L582)  and test the bedrock2 commit https://github.com/mit-plv/bedrock2/commit/7e8b2694bd5aa4a3dd01ed9a0d626388edf274d2 from 2 days ago. Somehow the bedrock2 commit from  https://github.com/mit-plv/bedrock2/pull/329#event-8593870902 which was merged at 11:48 EST = 16:48Z did not make it to the Coq CI. (This seems bizarre enough that maybe I'm just confused).

**Comment by andres-erbsen** [comment]
@coq/btauto-maintainers Please review. The change is literally one line and CI passed in https://github.com/coq/coq/pull/17022

**Review by ppedrot — APPROVED** [review]
Sorry for the late review. As usual, playing with Require-scoped commands is a dangerous sport, but if CI is happy...

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
