### PR TITLE
[api] Remove type equalities from API.

### PR DESCRIPTION
**Pull request by ejgallego**
This ensures that the API is self-contained and is, well, an API.
Before this patch, the contents of `API.mli` bore little relation with
what was used by the plugins [example: `Metasyntax` in `tacentries.ml`].

Many missing types were added as well as correcting some more
dependencies that were not fully solved in #808.

A sanity check of the `API.mli` file can be done with:

`ocamlfind ocamlc -rectypes -package camlp5 -I lib API/API.mli`

### CODE REVIEW

**Comment by ejgallego** [comment]
Note that this depends on #808 so only the last commit is valid. It also gets rid of Grammar_API.

**Comment by ejgallego** [comment]
Main blame for the size of the diff is on the `Grammar_API` removal, note that this follows a correct approach wrt qualification and `-open`

**Comment by maximedenes** [comment]
Ok, so Enrico and I asked @matejkosik to do this this week. I seem to recall he wrote to you he was working on it (you even replied that he was reimplementing #808). Are we all wasting our time doing the same things with poor communication around? Is there a place where I can read about the current plan for API and the order in which to merge PRs?

**Comment by ejgallego** [comment]
@maximedenes I think the plan is basically unchanged from what is in the mail, other than after all the discussion we took a way more conservative approach to #808 . About the type equations indeed I had told @matejkosik to go ahead but then I realized that I could be done within 1h of saying that so I didn't thought we would collide.

So IMO the merging plan is #808 and then #905 then all of the rest of @matejkosik 's commits plus some refinements that can be done.

IMHO if you get a few minutes with @matejkosik tomorrow you should be able to review and merge this, it is little more than a reordering.

In fact, the only change that @matejkosik has complained about I think is the removal of some deprecation notices from API, but I did that because such functions / types are not deprecated in the `mli` files of Coq. [The reason I tweaked that was by the way a practical need: I wanted cut-and-paste from Coq mli's to API to work]

I am sorry but I think that we should first remove the aliases in Coq, and then mark them as deprecated in the API, otherwise we have the bizarre situation that a type uses in Coq's .mli files is not allowed to be used in `API.mli`.

**Pull request merged**
