### PR TITLE
Update to 8.13.

### PR DESCRIPTION
**Pull request by Zimmi48**
Part of this PR was automatically generated by running `dev/doc/update-compat.py --master`.

**Kind:** infrastructure.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@JasonGross There seems to be the usual business that needs your attention regarding fiat-parsers. (BTW, would there be a way to anticipate this for you?)

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@Zimmi48 , proposed tag for 8.13+alpha is f1238742f9 , branching point is b456cf69ea

**Comment by ejgallego** [comment]
> @JasonGross There seems to be the usual business that needs your attention regarding fiat-parsers. (BTW, would there be a way to anticipate this for you?)

Indeed @JasonGross you could maybe do 8.13, 8.14, 8.15 :)

**Comment by ejgallego** [comment]
By the way I rebased as to get a more linear history.

**Comment by JasonGross** [comment]
I've updated fiat.  I've also added [a script to coq-scripts](https://github.com/JasonGross/coq-scripts/blob/master/compatibility/generate-compat-files.sh) that will automatically update the compatibility versions as necessary.  I've also reduced the number of manual changes that need to be made.  However, there are still some things that I don't want to do too early:
- When `Coq.Compat.Coq811` stops existing, I'll need to update the my scripts to pull in a different compat file, and perhaps manually copy/paste the contents into my own compat files (at some point, I should probably simplify the build system of fiat, and also remove compat hacks that aren't needed)
- I don't want to create version-specific copies of the .ml files in fiat.  If it doesn't recognize the version, it's just a warning, and it defaults to the 8.12 version of the files.  And if I create them early, then every change to the relevant ml interfaces will need to change not just the .813 ml files, but also the .814, .815, etc, for all the not-yet-created versions.

**Comment by ejgallego** [comment]
Thanks @jasongross

**Pull request merged**
