### PR TITLE
Bring the behaviour of the two kind of dnets closer for Prod and Sort.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1445322875

**Comment by Janno** [comment]
Where do you think slowdowns could occur? My understanding is that this change could only negatively affect developments that use undiscriminated hint databases, because only those can now yield more matches. Is that correct? (I tried working backwards from clients of `Btermdn` to find out when the transparency state is `None`.)

Do you know of any developments in the benchmark suite that rely on hints in undiscriminated databases?

**Comment by ppedrot** [comment]
> Do you know of any developments in the benchmark suite that rely on hints in undiscriminated databases?

Virtually everybody since this is the default for all hint bases. The sole standard user of a discriminated database is the typeclass mechanism.

> only those can now yield more matches. Is that correct?

So indeed only undiscriminated dbs are affected, but it's not even clear we get more matches since the pattern algorithm is also generating more precise shapes. For subterms that match `Nothing` we actually get less results, not more, and for `Sort / Prod` we should get the same thing in the end.

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2535.05  2556.19  -0.83 │  7067826325532   7127258283827  -0.83 │ 12240680499831  12230832720365   0.08 │  732156   732216   -0.01 │   0    0    nan │
│            coq-fiat-parsers │  582.23   585.94  -0.63 │  1628196192501   1637572727266  -0.57 │  2491497136806   2512157333629  -0.82 │ 3485524  3485628   -0.00 │   0    0    nan │
│                  coq-stdlib │  413.75   415.90  -0.52 │  1156387796879   1161000005842  -0.40 │  1473184981039   1473058406752   0.01 │  598032   598008    0.00 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1055.13  1057.48  -0.22 │  2937435253641   2944223575749  -0.23 │  4664367401104   4664127581757   0.01 │  941736   941720    0.00 │   0    0    nan │
│                    coq-hott │  298.28   298.72  -0.15 │   819342680814    819686663313  -0.04 │  1270255513029   1270249700787   0.00 │  570720   570420    0.05 │   0    0    nan │
│        coq-mathcomp-algebra │  140.70   140.86  -0.11 │   391381609045    391839242017  -0.12 │   511186660879    511191468232  -0.00 │  554148   554268   -0.02 │   0    0    nan │
│                 coq-unimath │ 4289.96  4294.67  -0.11 │ 11934070944667  11953017713813  -0.16 │ 22875456383890  22879006795834  -0.02 │ 3267408  3711516  -11.97 │   0    0    nan │
│                coq-coqprime │  330.78   331.12  -0.10 │   919125875419    919601664904  -0.05 │  1596112341891   1595488624832   0.04 │  917480   918256   -0.08 │   0    0    nan │
│                   coq-flocq │  146.60   146.74  -0.10 │   406624495548    406331284411   0.07 │   503683449093    503721209206  -0.01 │  810100   810060    0.00 │   0    0    nan │
│                    coq-corn │ 1461.08  1462.45  -0.09 │  4069553971473   4070640181948  -0.03 │  5878509190786   5878580063726  -0.00 │  788820   788952   -0.02 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │ 1632.20  1633.06  -0.05 │  4542751666075   4545589055583  -0.06 │  7157155866888   7154684931030   0.03 │ 1074272  1074204    0.01 │   0    0    nan │
│      coq-mathcomp-ssreflect │   53.92    53.91   0.02 │   147074886915    147104947442  -0.02 │   191145593354    191148861392  -0.00 │  525824   526544   -0.14 │   0    0    nan │
│                   coq-color │  483.78   483.58   0.04 │  1350407040502   1346538650422   0.29 │  1697787656303   1696730287182   0.06 │ 1154636  1154628    0.00 │   0    0    nan │
│       coq-mathcomp-fingroup │   48.17    48.15   0.04 │   133161761538    133128986425   0.02 │   186767022384    186787659116  -0.01 │  482612   482712   -0.02 │   0    0    nan │
│  coq-performance-tests-lite │ 1543.26  1542.59   0.04 │  4305871986276   4302369625904   0.08 │  7117252176547   7117426763304  -0.00 │ 2085064  2085008    0.00 │   0    0    nan │
│      coq-mathcomp-character │  149.93   149.80   0.09 │   416657777110    416203988597   0.11 │   585327874070    585323533781   0.00 │  731900   732036   -0.02 │   0    0    nan │
│            coq-math-classes │  172.81   172.64   0.10 │   482524087232    481797578273   0.15 │   642501393625    642462047675   0.01 │  481992   482004   -0.00 │   0    0    nan │
│               coq-perennial │ 6833.16  6825.44   0.11 │ 19032560645249  19014808023189   0.09 │ 29135352114206  29138561456159  -0.01 │ 3073492  3072280    0.04 │   0    0    nan │
│          coq-mathcomp-field │  221.58   221.31   0.12 │   616445947075    615588427282   0.14 │   940317279602    940346275596  -0.00 │  667372   664832    0.38 │   0    0    nan │
│                    coq-core │  107.28   107.14   0.13 │   296895961457    296659216417   0.08 │   459517143892    459450444470   0.01 │  292992   293004   -0.00 │   0    0    nan │
│       coq-engine-bench-lite │  312.91   312.50   0.13 │   880835812535    879910620334   0.11 │  1641840308197   1641594454705   0.01 │ 3505728  3505868   -0.00 │   0    0    nan │
│             coq-fiat-crypto │ 4815.60  4808.10   0.16 │ 13373697287205  13353460655830   0.15 │ 23618435183697  23612476015200   0.03 │ 2225728  2215028    0.48 │   0    0    nan │
│                  coq-geocoq │ 1327.60  1325.47   0.16 │  3702575507073   3694798284407   0.21 │  5438600092576   5437787545656   0.01 │  978432   976972    0.15 │   0    0    nan │
│                coq-bedrock2 │  309.80   309.07   0.24 │   858635992768    857818798069   0.10 │  1506512088177   1507406922575  -0.06 │  759688   800068   -5.05 │   0    0    nan │
│                coq-rewriter │  684.67   682.80   0.27 │  1900661054765   1896281536387   0.23 │  2937836652363   2935831263325   0.07 │ 1074252  1074204    0.00 │   0    0    nan │
│       coq-mathcomp-solvable │  169.84   169.31   0.31 │   472194029527    470947670842   0.26 │   669431951826    669490823851  -0.01 │  673884   695960   -3.17 │   0    0    nan │
│              coq-verdi-raft │ 1097.05  1090.66   0.59 │  3056512165660   3039232668269   0.57 │  4308374901495   4302001197983   0.15 │  916368   916260    0.01 │   0    0    nan │
│                 coq-bignums │   55.84    55.50   0.61 │   153679730326    153463428142   0.14 │   206702770744    206697505129   0.00 │  463240   463324   -0.02 │   0    0    nan │
│              coq-coquelicot │   68.62    68.14   0.70 │   187207455744    186612602916   0.32 │   240347845820    239332602644   0.42 │  558124   557812    0.06 │   0    0    nan │
│                 coq-coqutil │   59.11    58.21   1.55 │   163438007767    162622292434   0.50 │   215144168589    214601735020   0.25 │  599644   599620    0.00 │   0    0    nan │
│                   coq-verdi │   98.18    95.77   2.52 │   270445671655    262669993229   2.96 │   379786335675    374162597952   1.50 │  542380   541920    0.08 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
Despite the somewhat remarkable slowdown, the per-line diff for verdi does not show anything suspicious. Since the absolute time diff is small (2.5s), it is likely to be just noise. We can rerun a bench if there is concern.

**Comment by ppedrot** [comment]
Taking advantage of the rebase to bench verdi again: https://gitlab.com/coq/coq/-/jobs/1450443432

**Comment by ppedrot** [comment]
```
┌──────────────┬───────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬───────────────────────┬─────────────────┐
│              │     user time [s]     │             CPU cycles              │          CPU instructions           │ max resident mem [KB] │   mem faults    │
│              │                       │                                     │                                     │                       │                 │
│ package_name │    NEW     OLD  PDIFF │           NEW            OLD  PDIFF │           NEW            OLD  PDIFF │    NEW     OLD  PDIFF │ NEW  OLD  PDIFF │
├──────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│    coq-verdi │  92.01   92.59  -0.63 │  255469437200   256094311837  -0.24 │  360422817884   360452203526  -0.01 │ 541360  541448  -0.02 │   0    0    nan │
│   coq-stdlib │ 413.44  414.67  -0.30 │ 1155482904458  1158911228492  -0.30 │ 1473298582467  1473302889353  -0.00 │ 598128  598184  -0.01 │   0    0    nan │
│     coq-core │ 107.08  106.56   0.49 │  297263486994   296742435034   0.18 │  459574318461   459610490201  -0.01 │ 312324  312288   0.01 │   0    0    nan │
└──────────────┴───────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────┘
```
It was indeed noise.

**Comment by ppedrot** [comment]
This needs an assignee.

**Review by herbelin — COMMENTED** [review]
I have no idea how dnets work. Does the change imply a change of semantics?

**Comment by ppedrot** [comment]
> Does the change imply a change of semantics?

Probably, but I did not manage to come up with an example because it needs a star alignment to trigger. You basically need to have a double δ-indirection that reduces to a product (otherwise hnf makes it disappear) in a pattern that has holes (otherwise the ground path is taken). Furthemore, this cannot be a leading product otherwise it would have been instantiated by clenv functions or led to a hint failure. Given that parts of the matching function are overriden by unification in the hint application, it's not even clear this is sufficient. So, my guess is that nobody ever relied on that in the wild.

**Review by herbelin — APPROVED** [review]
Then, I believe that bringing the two behaviors closer is even worther. Approving on my side. I don't know if someone wants to comment more. Assigning.

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
