### PR TITLE
[coqdoc] Some refactoring / cleanup in preparation for component consolidation

### PR DESCRIPTION
**Pull request by ejgallego**
This PR does some simple refactoring to coqdoc in preparation of a couple deeper refactorings:
- unification of loadpath handling, and some other code factorizations [for example moving glob data handling to it's own lib, etc... , should be much easier after #13617 is merged]
- compositional documentation build, to be used from dune.

We build on some work done in #122 , #128 , #133 , this PR should not introduce any observable change.

### CODE REVIEW

**Comment by ejgallego** [comment]
Let's mark this as depending on #13617 as it is not worth to fix the make build system at this stage.

**Review by herbelin — APPROVED** [review]
As far as I understand (and as said in the PR initial comment) this is mostly re-factorization to better isolate the different conceptual components. The reorganization is clear and it will a priori be easy to adopt and to adapt to. So, it looks fully legitimate to me.

**Comment by ejgallego** [comment]
Should be good now.

**Comment by ejgallego** [comment]
Needs assignee , maybe @herbelin ?

**Comment by ejgallego** [comment]
Ping someone

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
