### PR TITLE
A few corner case notation bugs in the presence of binders

### PR DESCRIPTION
**Pull request by herbelin**
The PR fixes four small bugs:
- a notation wrongly used because of a missing unification
- an alpha-conversion bug (resulting in a wrong output which was overlooked in the test-suite output)
- a bug with let-in in binders which are used also as terms
- a bug with too early use of alpha-conversion

- [x] Added / updated **test-suite**

### CODE REVIEW

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Last commit doesn't come with a test

**Comment by herbelin** [comment]
> Last commit doesn't come with a test

I did not have the courage to build one... it would require to expose a configuration of the form `fun x => fun x : x => ...` (or something like that) which I'm unsure we can easily build.

**Comment by proux01** [comment]
Last commit looks like not chenging anything (semantically speaking) to me, which surprises me considering its title?

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
So nobody understands that last commit, let's just remove it and merge the remaining for now.

**Comment by herbelin** [comment]
> So nobody understands that last commit, let's just remove it and merge the remaining for now.

I believe that "somebody" understands this commit ;): the unification of `t` and `t'`, when comparing binders `na:t` and `na':t'`, should not be done in the context of a renaming that includes the renaming `na -> na'` but in the context of the renaming built up to before comparing `na:t` and `na':t'`. This is why the new renaming is now renamed `alp'` so that it does not override the previous renaming named `alp`.

**Comment by proux01** [comment]
But the old `alp` is not used anyway so is it just a code cleanup without any semantics change?

**Comment by herbelin** [comment]
The old `alp` is used in `unify_term alp.renaming t t'`.

**Comment by proux01** [comment]
My bad, then let's retrieve the commit, rerun CI and merge

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
