### PR TITLE
More efficient implementation of token manipulation in Grammar

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Probably not worth it.

**Comment by Janno** [comment]
Where would you expect speedups from this? I will soon be in a position to test this on BlueRock code but maybe it's not worth the effort?

**Comment by ppedrot** [comment]
On the microbenchmarks from the delayed import of notations, these functions appeared in the profile. Maybe it matters in extreme examples but even there it was overall a small absolute value.

**Comment by Janno** [comment]
I see. I did end up testing it and there is basically no change.
| Relative | Master   | MR       | Change   | Filename
|---------:|---------:|---------:|---------:|----------
|   -0.07% |  30380.9 |  30359.6 |    -21.3 | cpp2v-generated
|   -0.04% |  89220.2 |  89188.4 |    -31.8 | other
|   -0.04% | 119601.1 | 119548.0 |    -53.1 | total

**Pull request closed without merging**
