### PR TITLE
.ocamlformat: remove unused detritus

### PR DESCRIPTION
**Pull request by artagnon**
I'm using VSCode with the latest version of the official "OCaml Platform" extension to provide some conveniences. Unfortunately, it keeps erroring out every time I hit save without this patch.

### CODE REVIEW

**Comment by Zimmi48** [comment]
It's a bit weird to update the ocamlformat version without updating the formatting of the corresponding files. Maybe we should just remove all remaining `.ocamlformat` files from the repo since we do not enforce formatting anymore.

**Comment by ppedrot** [comment]
> Maybe we should just remove all remaining .ocamlformat files

Please.

**Comment by artagnon** [comment]
Done.

**Comment by ejgallego** [comment]
> Please

I see why you think like that; however a few of us have a different opinion, and ocamlformat has been very useful in many other projects.

I am not satisfied at all at how the ocamlformat issue has been handled by the people that don't like it.

**Comment by artagnon** [comment]
Fwiw, the inter-diff is available [here](https://termbin.com/q5mm).

**Review by Zimmi48 — APPROVED** [review]
We haven't been able to agree on a workflow that the whole team would be comfortable with, so this PR just acknowledges the actual state of things.

**Comment by Zimmi48** [comment]
The title will need to be updated though.

**Comment by ejgallego** [comment]
I agree @Zimmi48 , it is fine if people don't like ocamlformat. Expressing their dislike as hate is on the other hand toxic and not ok to me .

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
