### PR TITLE
Fix algebraic comparison with sprop on one side

### LINKED ISSUE #12909: Anomaly SProp undefined with module subtyping
#### Description of the problem
```
Module Type T.
Axiom A : Type.
End T.

Module M <: T.
Axiom A : SProp.
End M.
(* Anomaly "Universe SProp undefined." *)
```
#### Coq Version

8.10 to master

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #12909

### CODE REVIEW

**Comment by ppedrot** [comment]
Ugh, all this in the kernel... SProp shouldn't even be part of the graph to start with...

**Comment by SkySkimmer** [comment]
>SProp shouldn't even be part of the graph to start with...

It's not, that's why you get an anomaly

**Comment by ppedrot** [comment]
I mean, we should have static type separation between what goes in the graph and the sorts built out of those levels.

**Comment by herbelin** [comment]
By the way, as far as I understand, the intended model is that `SProp` ⊂ `Prop`  ⊂ `Set` ⊂ ... but I don't remember the technical reason why `SProp` is not included the hierarchy. What would go wrong at doing so in the current state of the implementation?

**Comment by SkySkimmer** [comment]
Cumulative SProp means relevance marks aren't stable by well typed substitution.
eg in `(fun (A:Type) (x:A) => x) (sTrue : SProp)` when you reduce you need to fix the relevance of `x`

Also if we get irrelevance in Set we can have an irrelevant unit in Set which we can't do with untyped conversion

**Comment by herbelin** [comment]
> Cumulative SProp means relevance marks aren't stable by well typed substitution.

Thanks! That's what I was trying to reconstruct. So, the current solution is explicit subtyping, i.e. to decorate the above term into `fun a : sTrue => unbox ((fun (A:Type) (x:A) => x) (Box sTrue) (box a))`.

> Also if we get irrelevance in Set we can have an irrelevant unit in Set which we can't do with untyped conversion

Yes, this is something which we should really address. @ppedrot had a way to implement it iirc.

**Comment by herbelin** [comment]
Conversely, if we had support for subtyping (i.e. automatically tracking where a coercion is needed), we would get proof-irrelevance for `unit:Set` without needing anything more in the conversion (since all variables liable to produce by application a term of type `unit` would be recognized automatically as proof-irrelevant).

**Comment by ppedrot** [comment]
@mattam82 can you confirm you're fine with this change?

**Review by mattam82 — APPROVED** [review]
Yes, that's fine with me.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
