### PR TITLE
gramlib/grammar: remove compat Entry.create

### PR DESCRIPTION
**Pull request by artagnon**
Replace instances of Entry.create with Entry.make in the codebase.

### CODE REVIEW

**Comment by ppedrot** [comment]
Given that we have much fewer calls to Entry.create, it should probably the contrary, shouldn't it?

**Comment by artagnon** [comment]
I removed it to match `Rules.make` and `Production.make`.

**Review by ppedrot — APPROVED** [review]
OK then.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@artagnon this needs a rebase.

**Comment by artagnon** [comment]
@ppedrot Done.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@artagnon at least elpi needs an overlay.

**Comment by ppedrot** [comment]
@artagnon sorry, but this needs a rebase (again)...

**Comment by SkySkimmer** [comment]
I merged the overlay

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
