### PR TITLE
Modify coqdev-setup-proofgeneral to work with dune compiled Coq.

### PR DESCRIPTION
**Pull request by SkySkimmer**
It seems to work.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
I have a bit of different setup that I should reconcile; I am OK merging this if that's useful for you tho.

Something I avoid is having to type make as the idea is to use an alias so executing coqtop would make sure the right libraries are rebuilt.

Also, I bind make to `dune build @check`, but I am still not happy with that until we get rid of the `voboot` target which is a pain in the ass.

**Comment by Zimmi48** [comment]
Looks good. This supersede the two "shim" PRs, right?

**Comment by SkySkimmer** [comment]
No, coqdev only works within the Coq repo. Calling Coq from somewhere unrelated in the filesystem is still a pain.

**Comment by ejgallego** [comment]
@SkySkimmer what kind of progress do you want here?

**Comment by SkySkimmer** [comment]
>I have a bit of different setup that I should reconcile

I am very interested in your setup and general workflow with dune.
I'm not sure what exactly is missing for me to start using dune by default, I'll have to try again sometime. Maybe I'll wait for ocaml/dune#1555 though.

**Comment by SkySkimmer** [comment]
Needs further thought.

**Comment by ejgallego** [comment]
> I am very interested in your setup and general workflow with dune.

Unfortunately I feel like my current setup is still very unstable thus not suitable for further release; but indeed I hope we can finish the Dune Coq issue before Christmas [almost have a proper setup for recursive modules] and then things should be way smoother.

We will still have a hard time managing libs tho until we can add lib support.

**Pull request closed without merging**
