### PR TITLE
Identify tacticals and Ltac constructs as "(tactical)" in index

### PR DESCRIPTION
**Pull request by jfehrle**
Add "tactical" as an index NotationObject
Include tacticals in tactics index
Change items in Ltac chapter to tactical::
Document is_* tacticals, move 2 of them to ltac chapter
Plus a few miscellaneous doc tweaks

**Kind:** documentation

### CODE REVIEW

**Comment by jfehrle** [comment]
What do you think about also identifying tactics that don't modify the proof state in the index (e.g. "swap")?  Not with "(tactical)", with something else.

Should I move the everything under "Checking properties of terms" from the tactics chapter to the Ltac chapter?

BTW, "tacticals" is not a great name; "tactical" is normally an adjective.  But I expect it's been used too long to think about changing it.  Right?

**Comment by Zimmi48** [comment]
I think there was a confusion in our private discussion: tactical is not a generic term for everything that Ltac does but only for "tactic modifiers". Maybe @herbelin or someone else can explain what is generally meant by this terminology.
I think we also want to hear about @ppedrot's views on how to classify things as Ltac / tactics. It seems indeed that it would make sense to stop using the terminology "tactic" for something that *returns* a value instead of modifying the proof state.

**Comment by jfehrle** [comment]
By all means, let's get input from others on how to group items and what the categories should be.  "Tactics and tacticals index" may not work as a title.  Do you have any thoughts on my first 2 questions?

**Comment by Zimmi48** [comment]
>What do you think about also identifying tactics that don't modify the proof state in the index (e.g. "swap")? Not with "(tactical)", with something else.

In the index, I don't think so. Keeping things in alphabetical index is important for easy retrieval. However in the manual itself, yes. There is already a section about this: https://coq.inria.fr/refman/proof-engine/tactics.html#non-logical-tactics.

>Should I move the everything under "Checking properties of terms" from the tactics chapter to the Ltac chapter?

Yes, that was one of my suggestions in #8946.

**Comment by jfehrle** [comment]
>  Keeping things in alphabetical index is important for easy retrieval.

Huh?  Adding a suffix like "(tactical)", "Ltac", etc. won't change the
order in the index.  (Though eventually we may want to add brief overview
summaries of tactics to the beginning of sections so you don't need to
read/skim the entire section as often.)

I'll look at doing some of the easier items you mention in
https://github.com/coq/coq/issues/8946, maybe as a separate commit/PR.

**Comment by Zimmi48** [comment]
Sorry I think I had misread your question. Then, it's fine, although I don't know what to think of this whole business of adding things in parentheses as this is usually done only to distinguish between identically named index entries. I guess it depends how people use the index. I personally only use it to search for the documentation of a tactic I already know the existence of.

**Comment by Zimmi48** [comment]
>(Though eventually we may want to add brief overview summaries of tactics to the beginning of sections so you don't need to read/skim the entire section as often.

Something like:

```
In this section, we will describe the tactics :tacn:`apply`, :tacn:`exact` and :tacn:`assumption`.
```

Yes, that would be great to have this!

**Comment by jfehrle** [comment]
> I don't know what to think of this whole business of adding things in parentheses as this is usually done only to distinguish between identically named index entries. I guess it depends how people use the index. I personally only use it to search for the documentation of a tactic I already know the existence of.

Yeah, it's not perfect.  Better to have section summaries but that may take some time to create; IMHO the section summary should be more than just a list of names for tactics--there should be a one line description of each tactic so you can get the overview without reading every tactic in the chapter and maybe grouped by function if there are many entries.  Probably shown as a table.  Annotating the index is just a quick step.

Also, if we list things like `fresh` in the Tactics and tacticals index, how would the user discover that `fresh` is a tactical (or whatever category)?

**Comment by JasonGross** [comment]
For me, a "tactical" is a(n unapplied) higher order tactic.  Any tactic which takes a tactic as an argument is as tactical.

I think the following are interesting categories of tactics:
- tactics that don't modify the proof term (`change`, `constr_eq`, `move ... at ...`, `is_evar`, `revgoals `, etc)
- tactics that don't change the appearance of the goal (I.e., don't make progress) (e.g., `idtac `, `fail `, `is_evar`)
- tactics/tactic expressions that can return constrs / that get run during tactic expression evaluation phase rather than tactics that are values (e.g., let, match, lazymatch)

**Comment by cpitclaudel** [comment]
This is a good direction.  Thanks! :+1:  One question: do you actually need to add `(tactical)` to the name of all tacticals?

I think I agree with Jason's definition of a tactical.  And I wouldn't put tests like `is_constr` in there, since that feels mostly like a normal tactic to me.  numgoals, swap, and the like I would call goal-manipulation primitives, and I'd be fine with stuffing them with fresh and is_constr in a large bag of "ltac builtins", or something similar.  See my comments on adding tags to tactics in https://github.com/coq/coq/issues/8946#issuecomment-491292988

**Comment by jfehrle** [comment]
> do you actually need to add `(tactical)` to the name of all tacticals?

I thought that made sense because the items would be in the section "Tactic Index" but they would tend to be documented in the Ltac chapter(s) rather than the "Tactics" chapter.  The manual uses "tactical" over 100 times, seems to me it must be a useful distinction.  Precision in terminology is very important for a reference manual.

**Comment by samuelgruetter** [comment]
Today I was looking for documentation of the various `is_*` tactics in the manual, and I see that this PR would provide this, so here's one user who would have found this useful, FWIW

**Comment by jfehrle** [comment]
They will eventually show up in the tactics index but probably without the "(tactical)" marking.  They are:

   is_cofix @one_term
   is_const @one_term
   is_constructor @one_term
   is_evar @one_term
   is_fix @one_term
   is_ground @one_term
   is_ind @one_term
   is_proj @one_term
   is_var @one_term

**Comment by jfehrle** [comment]
@Zimmi48 I think we dropped the idea of making a distinction long ago, so closing.

**Pull request closed without merging**
