### PR TITLE
Reduce the amount of useless typing performed by subst.

### PR DESCRIPTION
**Pull request by ppedrot**
Bench: https://gitlab.com/coq/coq/-/jobs/2193500540

### CODE REVIEW

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│         coq-metacoq-erasure │   60.61    63.28  -4.22 │   270896307955    282967461108  -4.27 │   406423025442    428597642332  -5.17 │ 1088288  1089580  -0.12 │   0    0      nan │
│     coq-metacoq-safechecker │  187.35   191.64  -2.24 │   854356523091    873375767131  -2.18 │  1156178778039   1161171050782  -0.43 │ 1226032  1232428  -0.52 │   0    0      nan │
│                  coq-stdlib │  397.12   403.41  -1.56 │  1656304011053   1674800755454  -1.10 │  1416351460718   1416940330192  -0.04 │  593244   613512  -3.30 │   0    0      nan │
│                   coq-verdi │   46.61    47.32  -1.50 │   211217544456    215334933885  -1.91 │   314914280922    319040899213  -1.29 │  837532   839712  -0.26 │   0    0      nan │
│           coq-metacoq-pcuic │  545.49   553.30  -1.41 │  2488328987642   2522138078824  -1.34 │  3547139546327   3558903712727  -0.33 │ 1663876  1664892  -0.06 │   0    0      nan │
│  coq-performance-tests-lite │  767.36   777.77  -1.34 │  3483523324608   3532206269293  -1.38 │  5942202762877   5941674609349   0.01 │ 1824364  1827952  -0.20 │   0    0      nan │
│              coq-coquelicot │   33.00    33.44  -1.32 │   149491424562    150215097822  -0.48 │   196364224282    196350161396   0.01 │  755056   755256  -0.03 │   4    0      nan │
│        coq-metacoq-template │   76.48    77.47  -1.28 │   341470030271    345177427758  -1.07 │   512967371078    513887043405  -0.18 │  914464   911208   0.36 │   0    0      nan │
│            coq-math-classes │   89.72    90.79  -1.18 │   406155246042    411579663642  -1.32 │   571349752505    571440842641  -0.02 │  502840   502788   0.01 │   0    0      nan │
│                coq-rewriter │  369.09   373.49  -1.18 │  1683299609753   1701404824556  -1.06 │  2770837260591   2772658166805  -0.07 │ 1063784  1060152   0.34 │   0    0      nan │
│          coq-mathcomp-field │   97.62    98.69  -1.08 │   447000938926    451728999353  -1.05 │   737064314637    737010104555   0.01 │  705932   706364  -0.06 │   0    0      nan │
│                     coq-vst │ 1046.66  1057.79  -1.05 │  4775664576864   4823396216299  -0.99 │  7698467844200   7715461446301  -0.22 │ 2029812  2140980  -5.19 │   0    1  -100.00 │
│      coq-mathcomp-odd-order │  515.93   521.23  -1.02 │  2363363295363   2387675617216  -1.02 │  4048129656044   4048147360575  -0.00 │ 1224260  1224316  -0.00 │   0    0      nan │
│                coq-compcert │  278.20   280.77  -0.92 │  1262808672466   1274495011042  -0.92 │  1877787180709   1889312692631  -0.61 │ 1106160  1105952   0.02 │   0    0      nan │
│      coq-mathcomp-character │   66.63    67.18  -0.82 │   304789072886    307277149062  -0.81 │   463033913789    463038111743  -0.00 │  825728   826108  -0.05 │   0    0      nan │
│               coq-perennial │ 3949.54  3977.81  -0.71 │ 18031331492896  18164280334390  -0.73 │ 29769041639538  29752906322137   0.05 │ 2639156  2623712   0.59 │   0    0      nan │
│               coq-fiat-core │   55.05    55.44  -0.70 │   238134965135    238748085337  -0.26 │   332359219563    332255553102   0.03 │  480708   480968  -0.05 │   0    0      nan │
│                   coq-color │  207.38   208.79  -0.68 │   939871892346    945639336976  -0.61 │  1324907012001   1327669467986  -0.21 │ 1154356  1155144  -0.07 │   0    0      nan │
│                    coq-hott │  162.05   162.96  -0.56 │   735445708475    738972529442  -0.48 │  1160470751920   1160373878984   0.01 │  617544   615768   0.29 │   0    0      nan │
│              coq-verdi-raft │  554.05   556.39  -0.42 │  2528882138785   2539668119767  -0.42 │  3907323647252   3927486933536  -0.51 │ 1260900  1259096   0.14 │   0    0      nan │
│       coq-mathcomp-solvable │   78.91    79.23  -0.40 │   360820538958    362219247476  -0.39 │   552097716575    552076750907   0.00 │  665332   665340  -0.00 │   0    0      nan │
│                coq-coqprime │   42.56    42.71  -0.35 │   19288376[1974](https://gitlab.com/coq/coq/-/jobs/2193500540#L1974)    193135395076  -0.13 │   283350678715    283422000689  -0.03 │  762104   762408  -0.04 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  925.49   928.69  -0.34 │  4223515628193   4238645482710  -0.36 │  7268627377710   7268392408463   0.00 │ 1149844  1150800  -0.08 │   1    0      nan │
│                 coq-bignums │   27.45    27.53  -0.29 │   125034611742    125846125522  -0.64 │   171930786194    171942233611  -0.01 │  468124   468016   0.02 │   0    0      nan │
│       coq-mathcomp-fingroup │   21.21    21.27  -0.28 │    96826704484     96735428996   0.09 │   139285677464    139266119550   0.01 │  485088   484976   0.02 │   0    0      nan │
│         coq-category-theory │ 1640.07  1644.50  -0.27 │  7508755044339   7527290580788  -0.25 │ 15547871693480  15548153852374  -0.00 │ 1469292  1468820   0.03 │  16    8   100.00 │
│                  coq-flocq3 │   75.89    76.09  -0.26 │   344779650751    346391234514  -0.47 │   456418931783    456868215506  -0.10 │  990704   991072  -0.04 │   0    0      nan │
│                    coq-corn │  752.74   754.70  -0.26 │  3433248090828   3441215105236  -0.23 │  5276529304532   5276904542539  -0.01 │  881040   879244   0.20 │   0    0      nan │
│                 coq-unimath │ 4280.43  4291.57  -0.26 │ 19588434482844  19635544012705  -0.24 │ 38985382370639  38984666766313   0.00 │ 3271548  3270668   0.03 │   0    0      nan │
│             coq-fiat-crypto │ 2786.01  2793.24  -0.26 │ 12671504873856  12706133160080  -0.27 │ 23237662116963  23239138591092  -0.01 │ 3850648  3850784  -0.00 │   0    0      nan │
│            coq-fiat-parsers │  333.10   333.76  -0.20 │  1497966179102   1502663914272  -0.31 │  2453329903782   2453322638833   0.00 │ 2697700  2696680   0.04 │   0    0      nan │
│                    coq-core │  100.46   100.65  -0.19 │   405449693077    405303446459   0.04 │   4417708[1996](https://gitlab.com/coq/coq/-/jobs/2193500540#L1996)6    442124857976  -0.08 │  278244   278440  -0.07 │   0    0      nan │
│    coq-metacoq-translations │   19.91    19.92  -0.05 │    89810680133     89505489760   0.34 │   156897202083    156978344584  -0.05 │  970628   971964  -0.14 │   0    0      nan │
│      coq-mathcomp-ssreflect │   24.53    24.53   0.00 │   111480353377    111854169131  -0.33 │   139796339494    139779269823   0.01 │  538532   536248   0.43 │   0    0      nan │
│        coq-mathcomp-algebra │   57.67    57.67   0.00 │   262979378903    263631963788  -0.25 │   359909048950    359992096425  -0.02 │  595496   595716  -0.04 │   0    0      nan │
│                coq-bedrock2 │  218.77   218.59   0.08 │   997589510226    996942678426   0.06 │  1794557690605   1795145193556  -0.03 │ 2051960  2051996  -0.00 │   0    0      nan │
│           coq-iris-examples │  412.56   412.10   0.11 │  1878627789373   1876231276817   0.13 │  2838363032036   2838991360411  -0.02 │ 1181780  1182060  -0.02 │   0    0      nan │
│                  coq-geocoq │  693.99   693.03   0.14 │  3163482029710   3160277578717   0.10 │  4989870946080   4989993855963  -0.00 │ 1080676  1077132   0.33 │   0    0      nan │
│                 coq-coqutil │   34.86    34.64   0.64 │   155980810816    155699044669   0.18 │   209830492350    209863259132  -0.02 │  607956   607272   0.11 │   0    0      nan │
│       coq-engine-bench-lite │  178.47   177.13   0.76 │   773455138858    767341094205   0.80 │  1496098477214   1488710608651   0.50 │ 1236472  1235028   0.12 │   0    0      nan │
│               coq-fourcolor │ 1459.81  1448.29   0.80 │  6656353220577   6608791375455   0.72 │ 12063652101226  12063725447629  -0.00 │  759856   758248   0.21 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Comment by ppedrot** [comment]
Any assignee? @mattam82 maybe?

**Review by SkySkimmer — APPROVED** [review]
trusting CI here

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
