### PR TITLE
Windows CI use `ci` pick

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
CI passed, so this apparently worked.

Since I suggested the change it is not within the spirit of our rules if I approve it - so I would appreciate an additional approval before I merge.

**Review by MSoegtropIMC — APPROVED** [review]
Works as expected, but since I suggested this change we should have an additional approval.

**Comment by SkySkimmer** [comment]
If you want to see it that way then you're the one who wrote the change and I'm the one approving.

**Comment by MSoegtropIMC** [comment]
That's fine. I will merge then.

**Comment by MSoegtropIMC** [comment]
@coqbot merge now

**Pull request merged**
