### PR TITLE
[ci] pin user developments

### PR DESCRIPTION
**Pull request by gares**
PR with overlays in 8.13+beta1 (not yet taken into account here are) are:
https://github.com/coq/coq/pull/12653
https://github.com/coq/coq/pull/13312
https://github.com/coq/coq/pull/13352
https://github.com/coq/coq/pull/13386

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
LGTM. CI will tell us if everything is fine.

**Comment by gares** [comment]
equations is waiting for an overlay https://github.com/mattam82/Coq-Equations/pull/316
math comp is bogus, re running

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
ah ah, we will see @coqbot

**Comment by Zimmi48** [comment]
Currently, coqbot can only merge in `master`. I haven't implemented the logic of merging into release branches because it is quite different from the one of the `master` branch (in principle, we would need the RM info, but we could just check that the author of the comment is in the `@coq/core` team). Let me know if this is something that you would like to get or if it's not very important.

**Pull request merged**
