### PR TITLE
Force dune to use locally built coqide for the shim

### LINKED ISSUE #14292: `dune build dev/shim/coqide-prelude` succeeds and `dune exec ...` fails with unclear error message when CoqIDE dependencies are not installed.
#### Description of the problem

Running `dune exec ./dev/shim/coqide-prelude` on a switch where coqide is not installed leads to the error
```
<project-root>/coq/_build/default/dev/shim/coqide-prelude: line 2: <project-root>/coq/_build/default/dev/shim//usr/bin/coqide: No such file or directory
```

If this cannot be easily fixed, I'd suggest this should at least be documented somewhere.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #14292

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, another possibility is to see if `(env (bin ))` could help here too.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by LasseBlaauwbroek** [comment]
Cool! Thanks guys!

**Pull request merged**
