### PR TITLE
[stm] remove warning about fat state

### PR DESCRIPTION
**Pull request by gares**
Fix: #8609

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
Why is a debug message a problem?

**Comment by silene** [comment]
> Why is a debug message a problem?

Because it is displayed prominently by Coqide. Maybe that is a bug in Coqide, but that it is the only debug message that floods the user, as far as I know.

**Review by silene — APPROVED** [review]
If you consider that fat states are not an issue in the general case, then the commit is obviously fine.

**Comment by gares** [comment]
A worker sends back a fat state when there is a change in the env (IIRC using == to check if there was one).

Two possibilities: the env started to be unshared for no deep reasons during tactic execution (it used to be the case for nested lemmas, or abstract, IIRC, dunno for broken proofs as the test case). The other one is that the warning used to be discarded and is not displayed.

In both cases it is pointless to show it to the final user. In the first case, something has to be investigated.

**Comment by gares** [comment]
I made this PR just to let the RM choose. IMO silencing is fine. Finding the root cause is better. In any case, the only difference is performance (instead of the evar map, it sends back the env + evar map...).

**Comment by silene** [comment]
So, #8609 is worth keeping open, right? Because I just can't see how the environment was changed there.

**Comment by gares** [comment]
I think so, but note that there the proof is incomplete so maybe that plays too. I'll try to investigate

**Comment by gares** [comment]
I digged a bit more, it is the `==` on safe env that fails (as if someone has added constants to it)... I need to dig more.

**Comment by gares** [comment]
See #8712

**Pull request closed without merging**
