### PR TITLE
Add advice and an example to the documentation of fold.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

Thanks @herbelin for the hint!

### CODE REVIEW

**Review by cpitclaudel — APPROVED** [review]

**Comment by cpitclaudel** [comment]
This is useful, thanks!

**Comment by cpitclaudel** [comment]
Merged :) By the way, I think the custom is to not have a period at the end of the first line of the commit message.

**Comment by Zimmi48** [comment]
>Merged :) By the way, I think the custom is to not have a period at the end of the first line of the commit message.

In the Coq repository, the custom is to have one (and to start the message with a capital letter). At least that's what I was told when I opened my first PR on this repo in 2015 :wink:

**Comment by cpitclaudel** [comment]
Oh! Funny.  Is it documented somewhere?  Maybe it doesn't matter.

```
$ git log --pretty=oneline | grep '\.$' | wc -l
10871

$ git log --pretty=oneline | grep '[^.]$' | wc -l
16799
```

**Pull request merged**
