### PR TITLE
Add a reminder to update the OPAM using page to the release doc.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

cc @RalfJung 
Do you think that it is OK to consider that it is the role of the OPAM maintainer to update this page?

### CODE REVIEW

**Comment by RalfJung** [comment]
I didn't even know that page existed.^^

I agree this makes sense, but I will surely forget this if there is no automatic test...^^

**Comment by ejgallego** [comment]
Note that `dune-release` [and similarly `topkg`] can be used to automate the release of the package. I dunno why the using opam page should change when a new version is released.

**Comment by Zimmi48** [comment]
This using page explains how to pin the Coq package. To do that it needs to know what the current version is. I agree it's bad that this is not better integrated with the rest of the website which is also aware of the current version. WDYT @gares @maximedenes?

**Comment by ejgallego** [comment]
Well, honestly I don't like our current OPAM instructions very much. We recommend the user do a lot of extra stuff (including installing a very old compiler) whereas the instructions IMHO should be more "setup OPAM to your taste, then opam install coq".

We should not have duplicate packages, and the opam extra repos is the only thing the user should be aware of.

**Comment by Zimmi48** [comment]
Feel free to propose an improvement, the code is there: https://github.com/coq/opam-coq-archive/blob/master/USING.md
As I'm not myself an OPAM user, I don't feel very concerned. I guess the initial goal was to give sufficiently detailed instructions for people who are not OCaml / OPAM users already...

**Comment by gares** [comment]
The instructions targets people that don't know opam. They should be able to copy paste in their terminal.

Sure, the two website should be merged and the version number be a variable.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I closed the pr mistake

**Review by maximedenes — COMMENTED** [review]
Did you say OPAM?

**Comment by Zimmi48** [comment]
>Did you say OPAM?

Is that a reminder that there still isn't any OPAM package for 8.8.2?

**Comment by maximedenes** [comment]
> Is that a reminder that there still isn't any OPAM package for 8.8.2?

No, it's more a reminder that I'm not a competent reviewer for OPAM-related matters ;)

**Comment by ejgallego** [comment]
The page is now empty https://coq.inria.fr/opam/www/using.html

So I wonder what does that mean for this PR.

**Comment by Zimmi48** [comment]
That's not normal! @vbgl it must be a bug following your recent changes.

**Comment by vbgl** [comment]
This page moved there: https://coq.inria.fr/opam-using.html

**Comment by Zimmi48** [comment]
Oh I see. But none of the links have been updated (e.g. in the README). It would be good to set up a redirection as well.

**Comment by Zimmi48** [comment]
So, following the move of the sources of the page, it clearly becomes the responsibility of the RM rather than the opam maintainer, to update this page, as part of the site update. So this PR is useful but must certainly be updated. Ideally, we could do even better and have the Makefile automatically use the latest available versions of Coq and OCaml. Or else, we could rewrite the page to let the user determine which version to install, e.g. with the appropriate query commands.

**Comment by vbgl** [comment]
The `OCAMLV` variable still exists. It is defined there: https://github.com/coq/www/blob/master/pages/opam-using.html#L2

The `COQV` variable has disappeared. It is now shared with the other parts of the website, as `CURRENTVERSION`.

If some links need to be updated, please show which.

**Comment by Zimmi48** [comment]
>If some links need to be updated, please show which.

[Google gives many instances](https://www.google.com/search?source=hp&ei=-JFZXLWkM_3jgwfA4Ju4CA&q=https%3A%2F%2Fcoq.inria.fr%2Fopam%2Fwww%2Fusing.html&btnK=Recherche+Google&oq=https%3A%2F%2Fcoq.inria.fr%2Fopam%2Fwww%2Fusing.html&gs_l=psy-ab.3...426.426..1248...0.0..0.100.180.1j1......0....2j1..gws-wiz.....0.OyEH2-h3CUc), that's why I think a redirection would be useful.

As for Coq per se, I think we just need to fix the links in the wiki and in the README:

```
[~/git/coq]$ git grep https://coq.inria.fr/opam/www/using.html
README.md:[opam-using]: https://coq.inria.fr/opam/www/using.html
[~/git/coq.wiki]$ git grep https://coq.inria.fr/opam/www/using.html
Installation-of-Coq-on-Linux.md:(<https://coq.inria.fr/opam/www/using.html>) or [[Nix]]
```

**Pull request closed without merging**
