### PR TITLE
cbn: do not refold constants with ! and / when the ! matched.

### LINKED ISSUE #4555: Cbn does not simplify non-recursive definition
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#4555
From: @robbertkrebbers
Reported version: 8.5
CC:   @RalfJung

### LINKED ISSUE #7674: `cbn` fails to unfold even though argument is a constructor
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem
Description embedded in the code:

```coq
Require Bool.

Definition do_something (p q : bool) (a b : nat) : option nat :=
  if Bool.eqb p q then Some a else Some b.
Arguments do_something !_ !_ _ _ /.

Lemma test a b :
  exists x, do_something false true a b = x.
Proof. intros. eexists.
(* Now the goal is do_something false true a b = ?x.
   I'd expect the following to unfold [do_something] because the
  argument specification is satisfied. However, nothing happens. *)
Fail progress cbn [do_something].
(* However, adding the boolean comparison function to the list of
  symbols enables the unfolding. *)
progress cbn [do_something Bool.eqb].
reflexivity.
Qed.
```

So it seems that whether the occurrence of a symbol *inside* a definition makes a difference for whether or not the definition itself is unfolded. This is such a "wtf" that it took me forever to figure out.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #4555
Fix #7674

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Related but not fixed:
- https://github.com/coq/coq/issues/13800
- https://github.com/coq/coq/issues/13646
- https://github.com/coq/coq/issues/12619

Not sure if fixed:
- https://github.com/coq/coq/issues/13801

**Comment by SkySkimmer** [comment]
@coq/coqbot-maintainers are there supposed to be this many reported checks? (on https://github.com/coq/coq/commit/84d8ed69acffe78f5e2540f4f594e5fd5ef2e7a9, pipeline https://gitlab.com/coq/coq/-/pipelines/409828074)

**Comment by SkySkimmer** [comment]
@ppedrot ping

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
