### PR TITLE
Reject Timeout 0, correctly handle when synterp takes longer than the timeout without getting a signal.

### LINKED ISSUE #17579: Anomaly if timeout is zero on Linux
#### Description of the problem
Both `Timeout 0 Check nat.` and `Set Default Timeout 0. Check nat.` fail with the anomaly
`Error: Anomaly "Uncaught exception Unix.Unix_error(Unix.EINVAL, "setitimer", "")."`

To disable the `Default Timeout`, the correct command is `Unset Default Timeout.` as documented in the refman.

I think it'd be most natural if the argument to `Timeout` is required to be a positive natural number.
Two alternative solutions which both introduce a special case for zero:
* The timer is set, but the commands triggers a `Timeout!` error, no matter how long the command takes.
* No timer is set and no command triggers a `Timeout!` error. Treating it like infinity.

kind: anomaly

#### Coq Version
v8.18+alpha, Linux

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17579

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
Thanks!

**Comment by maximedenes** [comment]
How about adding a small test checking that we correctly reject `Timeout 0`? It would have helped detect the bug.

**Comment by SkySkimmer** [comment]
test added

**Comment by maximedenes** [comment]
@coqbot merge now

**Pull request merged**
