### PR TITLE
Evarconv: don't use canonical structure to solve [proj (ctor ...) == ...]

### LINKED ISSUE #19564: Regression in 8.21+alpha introducing universe inconsistency
### Description of the problem

Between `8.20.0` and current `8.21+alpha` for (to me) unclear reasons there are universe inconsistencies in [coq-library-undecidability](https://github.com/uds-psl/coq-library-undecidability/tree/master).

### Small Coq file to reproduce the bug

```coq
Require Import ssreflect.

Structure myType := MyType { myType_X :> Type }.

Canonical Structure myType_CS X := MyType X.

Lemma dummy : MyType (unit * unit) -> True.
Proof.
  case.
Admitted.

Axiom f : (unit * myType) -> Prop.
Fail Axiom ax : forall (x : unit * myType), (fun A => f A) x.
```
resulting in
```
The command has indeed failed with message:
In environment
x : unit * myType
A : ?T
The term "A" has type "?T" while it is expected to have type
 "(unit * myType)%type"
(unable to find a well-typed instantiation for "?T": cannot ensure that
"Type@{myType.u0+1}" is a subtype of "Type@{prod.u1}").
```
This issue gets worse to find (in a real-world repository) when there are multiple files involved which results in non-local, hard to find errors.

The above, when split into three files `A.v`, `B.v`, `C.v` results in 
```
Error: Universe inconsistency. Cannot enforce prod.u1 <= B.2 because B.2
<= myType.u0 < prod.u1.
```
on `Require Import B.` in `C.v` compiled using `coqc A.v; coqc B.v; coqc C.v`.
The file contents are as follows:
`A.v`:
```coq
Structure myType := MyType { myType_X :> Type }.
```

`B.v`:
```coq
Require Import A ssreflect.

Canonical Structure myType_CS X := MyType X.

Lemma dummy : MyType (unit * unit) -> True.
Proof.
  case.
Admitted.
```

`C.v`:
```coq
Require Import A.

Axiom f : (unit * myType) -> Prop.
Axiom ax : forall (x : unit * myType), (fun A => f A) x.

Require Import B.
```

As a side note, it is unfortunate (pardon my bias) that `coq-library-undecidability` is not part of the CI anymore, since it did help find regressions in the past.

### Version of Coq where this bug occurs

8.21+alpha

### Last version of Coq where the bug did not occur

8.20.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
It seems better / less constraining to reduce.

Not sure if we actually want this though.

Fix #19564

### CODE REVIEW

**Comment by CohenCyril** [comment]
@Tragicus is reaching the same conclusion

**Comment by pi8027** [comment]
Yes, I have the impression that this PR should fix the performance issue we observed in math-comp/math-comp#1125.

**Comment by Tragicus** [comment]
I actually have the same idea, but brutally forbidding the CS resolution like that leads to the unification algorithm unfolding things, which means that we lose keys that would have been used with the current version. In other words, I am pretty sure the CI will complain.

**Comment by SkySkimmer** [comment]
@coqbot ci minimize ci-mathcomp

**Comment by pi8027** [comment]
@SkySkimmer, are you investigating the breakage of MathComp? If not, I'm willing to do that.

**Comment by SkySkimmer** [comment]
I was waiting for the minimization to finish to have a look (mathcomp usually takes a while in the minimizer).
Since you know how mathcomp is supposed to work you have a chance of understanding what's going on without minimizing so maybe it's better that you handle it.

**Comment by pi8027** [comment]
In the unification trace, this is the last step before coq-master and this `cs-no-proj-ctor` branch of Coq behave differently:
```
Debug:
[unification]
  GRing.Lalgebra.sort|ZApp(reverse_coercion Algebraics.Implementation_type__canonical__GRing_Ring algC,
                           {|
                             GRing.Lalgebra.sort := GRing.Algebra.sort ?t;
                             GRing.Lalgebra.class :=
                               {|
                                 GRing.Lalgebra.GRing_isNmodule_mixin :=
                                   GRing.Algebra.GRing_isNmodule_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.choice_hasChoice_mixin :=
                                   GRing.Algebra.choice_hasChoice_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.eqtype_hasDecEq_mixin :=
                                   GRing.Algebra.eqtype_hasDecEq_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Nmodule_isSemiRing_mixin :=
                                   GRing.Algebra.GRing_Nmodule_isSemiRing_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Nmodule_isZmodule_mixin :=
                                   GRing.Algebra.GRing_Nmodule_isZmodule_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Zmodule_isLmodule_mixin :=
                                   GRing.Algebra.GRing_Zmodule_isLmodule_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Lmodule_isLalgebra_mixin :=
                                   GRing.Algebra.GRing_Lmodule_isLalgebra_mixin (GRing.Algebra.class ?t)
                               |}
                           |})
  GRing.regular|ZApp(GRing.Ring.sort
                       (reverse_coercion Algebraics.Implementation_type__canonical__GRing_Ring algC))
```
where `GRing.regular` is the identity function on `Type`, but is used to trigger the inference of "regular" algebras (a ring `R` forms an algebra over `R` itself).

So, coq-master triggers this inference:
```
Debug:
[unification]
  GRing.Lalgebra.Pack|ZApp(reverse_coercion Algebraics.Implementation_type__canonical__GRing_Ring algC,
                           GRing.Algebra.sort ?t,
                           {|
                             GRing.Lalgebra.GRing_isNmodule_mixin :=
                               GRing.Algebra.GRing_isNmodule_mixin (GRing.Algebra.class ?t);
                             GRing.Lalgebra.choice_hasChoice_mixin :=
                               GRing.Algebra.choice_hasChoice_mixin (GRing.Algebra.class ?t);
                             GRing.Lalgebra.eqtype_hasDecEq_mixin :=
                               GRing.Algebra.eqtype_hasDecEq_mixin (GRing.Algebra.class ?t);
                             GRing.Lalgebra.GRing_Nmodule_isSemiRing_mixin :=
                               GRing.Algebra.GRing_Nmodule_isSemiRing_mixin (GRing.Algebra.class ?t);
                             GRing.Lalgebra.GRing_Nmodule_isZmodule_mixin :=
                               GRing.Algebra.GRing_Nmodule_isZmodule_mixin (GRing.Algebra.class ?t);
                             GRing.Lalgebra.GRing_Zmodule_isLmodule_mixin :=
                               GRing.Algebra.GRing_Zmodule_isLmodule_mixin (GRing.Algebra.class ?t);
                             GRing.Lalgebra.GRing_Lmodule_isLalgebra_mixin :=
                               GRing.Algebra.GRing_Lmodule_isLalgebra_mixin (GRing.Algebra.class ?t)
                           |})
  GRing.GRing_regular__canonical__GRing_Lalgebra|ZApp(reverse_coercion
                                                        Algebraics.Implementation_type__canonical__GRing_Ring
                                                        algC)
```

However, this branch of Coq first unfolds `GRing.regular` (which is wrong):
```
Debug:
[unification]
  GRing.Lalgebra.sort|ZApp(reverse_coercion Algebraics.Implementation_type__canonical__GRing_Ring algC,
                           {|
                             GRing.Lalgebra.sort := GRing.Algebra.sort ?t;
                             GRing.Lalgebra.class :=
                               {|
                                 GRing.Lalgebra.GRing_isNmodule_mixin :=
                                   GRing.Algebra.GRing_isNmodule_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.choice_hasChoice_mixin :=
                                   GRing.Algebra.choice_hasChoice_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.eqtype_hasDecEq_mixin :=
                                   GRing.Algebra.eqtype_hasDecEq_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Nmodule_isSemiRing_mixin :=
                                   GRing.Algebra.GRing_Nmodule_isSemiRing_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Nmodule_isZmodule_mixin :=
                                   GRing.Algebra.GRing_Nmodule_isZmodule_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Zmodule_isLmodule_mixin :=
                                   GRing.Algebra.GRing_Zmodule_isLmodule_mixin (GRing.Algebra.class ?t);
                                 GRing.Lalgebra.GRing_Lmodule_isLalgebra_mixin :=
                                   GRing.Algebra.GRing_Lmodule_isLalgebra_mixin (GRing.Algebra.class ?t)
                               |}
                           |})
  GRing.Ring.sort|ZApp(reverse_coercion Algebraics.Implementation_type__canonical__GRing_Ring algC)
```
and then try to solve the problem using a canonical instance (implementing the fact that `GRing.Lalgebra` inherits from `GRing.Ring`):
```
Debug:
[unification]
  @reverse_coercion|ZApp(ringType, Type, Algebraics.Implementation_type__canonical__GRing_Ring, algC)
  GRing_Lalgebra__to__GRing_Ring|ZApp(reverse_coercion Algebraics.Implementation_type__canonical__GRing_Ring
                                        algC,
                                      {|
                                        GRing.Lalgebra.sort := GRing.Algebra.sort ?t;
                                        GRing.Lalgebra.class :=
                                          {|
                                            GRing.Lalgebra.GRing_isNmodule_mixin :=
                                              GRing.Algebra.GRing_isNmodule_mixin (GRing.Algebra.class ?t);
                                            GRing.Lalgebra.choice_hasChoice_mixin :=
                                              GRing.Algebra.choice_hasChoice_mixin (GRing.Algebra.class ?t);
                                            GRing.Lalgebra.eqtype_hasDecEq_mixin :=
                                              GRing.Algebra.eqtype_hasDecEq_mixin (GRing.Algebra.class ?t);
                                            GRing.Lalgebra.GRing_Nmodule_isSemiRing_mixin :=
                                              GRing.Algebra.GRing_Nmodule_isSemiRing_mixin
                                                (GRing.Algebra.class ?t);
                                            GRing.Lalgebra.GRing_Nmodule_isZmodule_mixin :=
                                              GRing.Algebra.GRing_Nmodule_isZmodule_mixin
                                                (GRing.Algebra.class ?t);
                                            GRing.Lalgebra.GRing_Zmodule_isLmodule_mixin :=
                                              GRing.Algebra.GRing_Zmodule_isLmodule_mixin
                                                (GRing.Algebra.class ?t);
                                            GRing.Lalgebra.GRing_Lmodule_isLalgebra_mixin :=
                                              GRing.Algebra.GRing_Lmodule_isLalgebra_mixin
                                                (GRing.Algebra.class ?t)
                                          |}
                                      |})
```

Is it possible to force evarconv to reduce `proj (ctor ...)` first for the unification problems of the form `proj (ctor ...) == ...`?

**Comment by pi8027** [comment]
A related question: Is there any way to instruct Coq to unfold which constant first to solve a unification problem whose head symbols are both constants? It seems that the `Strategy` command has no effect in evarconv.

**Comment by SkySkimmer** [comment]
The code which chooses which side to reduce for constant / constant is AFAICT https://github.com/coq/coq/blob/c51bef629961a27b4bdc4bad96a6dab96e59fe6e/pretyping/evarconv.ml#L1050-L1076

**Comment by SkySkimmer** [comment]
I'm going to stop the minimizer, it's probably not going to be useful.

**Pull request closed without merging**
