### PR TITLE
Use thunks to univ instead of lazy constr for template typing

### PR DESCRIPTION
**Pull request by SkySkimmer**
This avoids to EConstr.to_constr when we only care about the codomain of a product.

Overlays: https://github.com/mattam82/Coq-Equations/pull/260 https://github.com/coq-community/paramcoq/pull/47 https://github.com/LPCIC/coq-elpi/pull/116

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Note that `sort_of_arity` should probably use the kernel reduction rather than the RAKAM.

**Comment by SkySkimmer** [comment]
>Note that sort_of_arity should probably use the kernel reduction rather than the RAKAM.

We await your PR.

**Comment by ppedrot** [comment]
The proper PR would probably consist in getting rid of the RAKAM altogether (except for `cbn`), but I am not sure everybody will be happy about it.

**Comment by maximedenes** [comment]
> The proper PR would probably consist in getting rid of the RAKAM altogether

You would use "lazy" reduction from the pretyper instead?

**Comment by ppedrot** [comment]
@maximedenes you can't use the call-by-need reduction because it creates normal forms that are different from the call-by-name one in the case of weak-head reduction. I think I would first perform a few experiments with the kernel reduction set to call-by-name (i.e. share flag set to false) and with a custom machine that is performing "clever" call-by-name, i.e. a bit of call-by-need to share whnfs and delayed substitutions.

**Comment by herbelin** [comment]
> The proper PR would probably consist in getting rid of the RAKAM altogether (except for cbn), but I am not sure everybody will be happy about it.

I don't know where we are now, but, at some time, it was clear to me that a quick and easy approach to address the question of unfolding definitions hiding a fixpoint in the intended way (RAKAM-like) was to treat global fixpoint natively in the kernel, by what I mean fixpoints which are not global definitions as we have now of the form:
```
Definition qualid := fun x:A => fix f := φ(f).
```
but rather definitions of the form:
```
Definition qualid := fun x:A => fix f := φ(qualid x).
```
so that unfolding `qualid` with a constructed term does what the RAKAM does now (*).

Otherwise said, a cheap implementation of named fixpoints not requiring to change the structure of `constr`, only to kernel-register that some constants behave like globally named fixpoints.

(*) assuming only one level of naming

**Comment by ppedrot** [comment]
@herbelin I think that this is irrelevant to the problem at hand. We use the RAKAM for two different purposes, namely
1. as a user-friendly reduction machine equipped with refolding, which is the point you stress out.
2. for mostly everything else above `Reductionops`, probably because we wanted call-by-name.

The net result of this code sharing is that we have a horribly inefficient reduction algorithm where this matters, e.g. in Evarsolve. Even though the reduction is call-by-name, there are many ways to perform it more cleverly. For instance, we currently substitute terms upfront even when this does not matter for unification. I was just advocating for splitting those two uses, potentially reusing kernel reduction for point 2.

**Comment by herbelin** [comment]
> I think that this is irrelevant to the problem at hand.

Indeed, we are probably not talking about the same thing.

I was answering to your "I am not sure everybody will be happy about [getting rid of the RAKAM altogether (except for cbn)]", and on how to replace it _uniformly_ (in all reduction mechanisms) with a different reduction rule for "global"-like `fix` and `cofix`.

Your point about efficiency is of course critical and I'm entirely supporting you here.

> we currently substitute terms upfront even when this does not matter for unification

I don't know what you mean by this sentence, but afair, pirbo originally implemented the RAKAM for the purpose of unification, so that the user is not exposed to inferred types of the form `fix` while a refolding was expected. So, using kernel reduction would require using refolded `fix` in the kernel too (which I'm advocating for, obviously).

**Comment by ppedrot** [comment]
We're clearly hijacking the thread, but actually @herbelin the refolding mechanism is only used by `cbn`. Unification merely relies on a hand-crafted wrapper that performs fixpoint unfolding only in specific cases. I don't have a particular judgment on this, it is orthogonal to the fact that the RAKAM implementation is overly complex for 99% of its use cases, i.e. not `cbn`. We could do much better by tearing it down to a simpler machine while still relying on the ad-hoc fixpoint unfolding.

**Comment by herbelin** [comment]
> We're clearly hijacking the thread

Yes, clearly! One of my point is that we need to write somewhere such important issues (in a roadmap?), and that we fix ourselves clear and consensual objectives wrt this (now long-standing) important issues (@mattam82 promised last week to prepare such a document).

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/854/console
~~~

┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │    mem faults     │
│                             │                         │                                             │                                             │                               │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1339.43 1366.57 -1.99 % │     3735421475972     3809805293053 -1.95 % │     6725380192706     6724703498087 +0.01 % │    1293980    1291924 +0.16 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-coqutil │   57.34   58.04 -1.21 % │      160092346122      160872744693 -0.49 % │      204965588748      204969782931 -0.00 % │     537520     525320 +2.32 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-verdi │  118.14  119.40 -1.06 % │      327713580892      328911150126 -0.36 % │      426897187716      426927876865 -0.01 % │     538460     538548 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-corn │ 1417.94 1428.68 -0.75 % │     3958519780910     3979043775372 -0.52 % │     6158210994924     6158257299759 -0.00 % │     871396     871456 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-flocq │  198.73  199.84 -0.56 % │      552265884715      554411026825 -0.39 % │      714997113593      715169807200 -0.02 % │     927156     927140 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-math-classes │  205.26  206.39 -0.55 % │      573215445021      575698477087 -0.43 % │      769844638861      769721025582 +0.02 % │     518588     518364 +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-hott │  332.90  334.69 -0.53 % │      906132220441      911661735664 -0.61 % │     1468305799289     1468358874230 -0.00 % │     625132     625236 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4030.50 4049.66 -0.47 % │    11222856234933    11278825236271 -0.50 % │    21436138452440    21435211260815 +0.00 % │    1055420    1055984 -0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1525.15 1532.17 -0.46 % │     4258688867455     4277476523263 -0.44 % │     6516168871963     6516192196199 -0.00 % │    1383232    1376384 +0.50 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-coquelicot │   73.51   73.84 -0.45 % │      201861336564      202444760298 -0.29 % │      267425433837      267413916522 +0.00 % │     655716     655080 +0.10 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  163.26  163.82 -0.34 % │      454711876205      456520492550 -0.40 % │      638701088774      638651131947 +0.01 % │     847908     847404 +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4309.18 4323.58 -0.33 % │    11968649880633    12008291621962 -0.33 % │    19872145009346    19874875414711 -0.01 % │    2361776    2371252 -0.40 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  145.14  145.61 -0.32 % │      404510753216      405246405333 -0.18 % │      538872543124      538912104777 -0.01 % │     610944     610564 +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-rewriter │  564.23  565.79 -0.28 % │     1566929003009     1570410698765 -0.22 % │     2414990249169     2416099035772 -0.05 % │     909248     909300 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1272.09 1275.59 -0.27 % │     3547511712220     3555497732771 -0.22 % │     5034248273980     5033902567917 +0.01 % │    1820012    1820088 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  598.65  600.10 -0.24 % │     1675978727156     1680625966913 -0.28 % │     2695817873079     2697872729750 -0.08 % │    3253892    3194344 +1.86 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-fiat-crypto-legacy │ 5955.26 5968.68 -0.22 % │    16576379125431    16617574295928 -0.25 % │    28099130552491    28100302829889 -0.00 % │    2422804    2368576 +2.29 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-bignums │   62.90   63.04 -0.22 % │      174425448952      175002172289 -0.33 % │      244449931958      244452996122 -0.00 % │     483328     483192 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  993.08  995.23 -0.22 % │     2766530227092     2773040523941 -0.23 % │     4554157169934     4552517781445 +0.04 % │     930436    1022548 -9.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fiat-core │  101.96  102.18 -0.22 % │      289504209425      290488163826 -0.34 % │      389570237481      389496223762 +0.02 % │     498076     497696 +0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-compcert │  678.16  679.54 -0.20 % │     1890288546275     1892469187064 -0.12 % │     2650999331019     2651327746938 -0.01 % │    1038076    1038240 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   49.11   49.17 -0.12 % │      136172858760      136532341999 -0.26 % │      189816696995      189832152961 -0.01 % │     557660     557380 +0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  175.73  175.92 -0.11 % │      489149321259      490274386080 -0.23 % │      697010766938      696992797911 +0.00 % │     792900     792736 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   49.02   49.06 -0.08 % │      134540906731      134761458674 -0.16 % │      175951541456      175989739421 -0.02 % │     568372     568424 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  262.41  262.55 -0.05 % │      730670657663      731607839266 -0.13 % │     1123447802682     1123509373398 -0.01 % │     790324     790284 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-color │  653.51  653.40 +0.02 % │     1822931887888     1824616923556 -0.09 % │     2323279159429     2323654793536 -0.02 % │    1132304    1130868 +0.13 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1530.02 1529.74 +0.02 % │     4261799761549     4264298216050 -0.06 % │     6179809030405     6180297849790 -0.01 % │    1138356    1132436 +0.52 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-sf-plf │   43.80   43.78 +0.05 % │      121898062949      122348319897 -0.37 % │      169146670196      169163659870 -0.01 % │     494828     494924 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  210.21  210.07 +0.07 % │      582376022968      582265637859 +0.02 % │      977190105582      977024575335 +0.02 % │    1119768    1119808 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-performance-tests │   11.84   11.81 +0.25 % │       32329647085       32375872484 -0.14 % │       55759964111       55754795304 +0.01 % │     466820     466752 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2098.04 2092.42 +0.27 % │     5854063510925     5839815231052 +0.24 % │    11490060127946    11490016423718 +0.00 % │     952572     952384 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-coqprime │   85.14   84.39 +0.89 % │      232822317294      232394585891 +0.18 % │      335509789196      335477596588 +0.01 % │     757384     756872 +0.07 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴───────────────────┘
~~~

**Comment by ppedrot** [comment]
Will merge this soon.

**Comment by ppedrot** [comment]
@SkySkimmer did you also rebase the overlays?

**Comment by SkySkimmer** [comment]
no

**Comment by ppedrot** [comment]
@SkySkimmer can you rebase both this and the overlays so as to get a clean CI? Better safe than sorry.

**Pull request merged**
