### PR TITLE
Disable whitespace linter for .out files.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by maximedenes** [comment]
Ah ah, the linter complains about this one :)

**Comment by SkySkimmer** [comment]
Should be fixed.

**Comment by SkySkimmer** [comment]
For future reference, if run in a dirty directory the linter will check whitespace in generated .ml files which are binary files and thus error.
This isn't a problem for travis though.

**Comment by maximedenes** [comment]
@ejgallego Could we do something about the GeoCoq timeout? Or has it been already addressed?

**Comment by Zimmi48** [comment]
> Could we do something about the GeoCoq timeout? Or has it been already addressed?

How frequent is it these days? It seemed to be it had been mostly addressed. Maybe one or two more files should be removed from the CI target, see https://github.com/GeoCoq/GeoCoq/blob/master/configure-ci.sh.

**Comment by ejgallego** [comment]
Yup I propose we remove 3-4 minutes more, we fell a bit short IMHO. [Or alternative let's make Coq faster XD]

**Comment by Zimmi48** [comment]
I'll let you do the PR on GeoCoq this time.

**Comment by ejgallego** [comment]
I will try but I don't promise anything as my urgent TODO list is totally overblow :(

**Comment by Zimmi48** [comment]
OK, I've created [a reminder](https://github.com/coq/coq/projects/9#card-5823970) so that we don't completely forget about it. Another solution would be to open an issue at GeoCoq. Maybe Julien can help us this time.

**Comment by JasonGross** [comment]
> For future reference, if run in a dirty directory the linter will check whitespace in generated .ml files which are binary files and thus error.
This isn't a problem for travis though

Can this be fixed?  It seems very unfortunate to have a linter that can only be run on clean checkouts.  (Perhaps have it look only at the files listed by `git ls-files` by default?)

**Comment by SkySkimmer** [comment]
>     Can this be fixed? It seems very unfortunate to have a linter that can only be run on clean checkouts. (Perhaps have it look only at the files listed by git ls-files by default?)

#6227

**Pull request merged**
