### PR TITLE
Delay universe conversion as late as possible in Reductionops.infer_conv.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Doesn't change much, but it cannot hurt either, especially if we get algebraic universes. cc @mattam82 

I did a bit of statistics with this PR, and it seems that the vast majority of the universe problems generated by the FO heuristic are of size ≤ 1, which means that this PR only matters when conversion would have failed. This is probably rather uncommon, hence the essentially lack of speedup here.

**Comment by ppedrot** [comment]
I'm undrafting this, it should be ready. It doesn't hurt and can help with the algebraic branch, so it can probably go as-is.

**Comment by proux01** [comment]
@coqbot merge now

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
