### PR TITLE
Do not use the constant stack in whd_betaiota_deltazeta_for_iota_state.

### PR DESCRIPTION
**Pull request by ppedrot**
There is no point, it is always called with refolding turned off.

Overlays:
- https://github.com/unicoq/unicoq/pull/27

### CODE REVIEW

**Comment by ppedrot** [comment]
@herbelin do you want to assign?

**Review by herbelin — COMMENTED** [review]
Asking abstractly: may refolding happen to be worth to be activated here or is this definitely code for which refolding shall reasonably not be relevant?

**Comment by ppedrot** [comment]
@herbelin Judging from the invariants appearing in chiaroscuro in the unification algorithm, I would naturally think you don't want that to happen. The only place that currently relies on the refolding machinery is `Redexpr.whd_cbn`, which happens to implement `cbn`, thus leading me to believe that we're using most of the time an overly complex machine for no good reason.

**Comment by herbelin** [comment]
OK, then merging tomorrow evening.

**Review by herbelin — APPROVED** [review]

**Pull request merged**
