### PR TITLE
[ssr] Declare prenex implicits for `Some_inj`

### LINKED ISSUE #6910: SSReflect: Some_inj should have maximally inserted implicit arguments
#### Version

The Coq Proof Assistant, version 8.7.2 (February 2018)
compiled on Feb 16 2018 21:18:01 with OCaml 4.06.0

#### Operating system

macOS High Sierra 10.13.2

#### Description of the problem

`Some_inj` lemma cannot be used as a view because not all of its implicit arguments are declared as maximally inserted. The following snippet is expected not to fail, but it does:
```
From Coq Require Import ssreflect ssrfun.

Lemma foo (x y : nat) : Some x = Some y -> x = y.
Proof.
Fail move/Some_inj.
Abort.
```

It can be easily fixed like so:
```
Prenex Implicits Some_inj.
Lemma foo (x y : nat) : Some x = Some y -> x = y.
Proof. by move/Some_inj. Qed.
```

### PR DESCRIPTION
**Pull request by anton-trunov**
**Kind:** documentation / bug fix.

Fixes / closes #6910 

Also fixes a minor typo in the documentation comment in ssrfun.v

### CODE REVIEW

**Comment by anton-trunov** [comment]
If this gets merged in, then I'm willing to prepare the corresponding fix for mathcomp's legacy ssrfun.v files for Coq v8.5 and v8.6

**Comment by gares** [comment]
@ggonthier would you review this PR?

**Comment by gares** [comment]
Well, I guess I can review it myself. I was puzzled by the fact that the bug was there is the first place.

I guess it is simply that people inject using the injection tactic here (or the overloaded `[...]` intro pattern), this is why it was not spot/fixed before.

Thanks @anton-trunov for the  PR!

**Review by gares — APPROVED** [review]

**Comment by maximedenes** [comment]
@gares Is `Prenex Implicits` still recommended?

**Comment by anton-trunov** [comment]
@maximedenes I was following the style of `ssrfun.v`. Though `ssrbool.v` uses both `Prenex Implicits` and `Arguments {...}`.

I can change `Prenex Implicits Some_inj.` into `Arguments Some_inj {T x1 x2}.` if this is preferred. Then, as a separate PR the rest of `Prenex Implicits` can be dealt with.

Please let me know what you think. (CC @gares )

**Comment by gares** [comment]
In this specific case it is equivalent to the line you write, but this is not the point: there is always an
`Argument` line equivalent to the result of `Prenex`.

Last time I checked `Prenex` is still doing something Coq has no command for, hence it cannot be deprecated (but rather advocated). IIRC `Prenex` sets the longest prefix of implicits as maximal, while leaves the others untouched (as they were inferred by Set Implicit Arguments).

**Comment by gares** [comment]
Maybe your question was: can it be merged in `Arguments`... food for thought

**Comment by ejgallego** [comment]
Yeah `Prenex` is needed for example when using reflection lemmas chained with views or with other lemmas as in `ifP fooP` etc...

**Comment by anton-trunov** [comment]
I was surprised by the fact that non-maximal implicit arguments do not work here.
E.g. the following works:
```
Lemma foo (x y : nat) : Some x = Some y -> x = y.
Proof.
by move=> H; move: {H}(Some_inj H).
Qed.
```
but `move/Some_inj.` does not.
Is this expected behavior? If it's not then I'm just providing a workaround, not fixing the problem.

**Comment by maximedenes** [comment]
I think the patch is fine anyway, so let's merge.

**Comment by ggonthier** [comment]
The move/Some_inj behaviour is normal. Views try to add wildcard arguments to the view lemma until the view application type checks, ignoring implicit declarations - there are many cases where one needs either fewer or more implicits than convenient for normal application. Usually type checking forces the insertion of the usual (type-dependent) implicits, but this occasionally fails for highly polymorphic lemmas like `Some_inj`. The remedy for that is indeed to add a `Prenex` declaration, which ensures the implicits are added before the view is interpreted.

**Comment by ggonthier** [comment]
I'm having second thoughts about this issue and PR, following some experience using the `Some_inj` lemma. Essentially, we have a usage conflict, between using this injectivity lemma as a view, and using it as an explicit argument to another lemma that requires injectivity, such as `mathcomp/seq/inj_map`.
The former requires inserting 3 implicit arguments, and the latter only one. Normally (i.e., in all other cases in MathComp), the latter is favoured, the two implicit arguments implied by the `injective` predicate are left as on-demand implicits; there is no actual conflict because these two arguments will then be inserted both by explicit application and view interpretation. The latter fails here because `Some` is totally polymorphic, resulting in an obscure error.
   However, as @gares noted, `Some_inj` is not useful as a view because it is actually easier to use the injectivity intro pattern, and indeed the main motivation for having the lemma at all is to use it as an argument to other lemmas, which this PR spoils - by giving `Some_inj` implicits that are inconsistent with the rest of MathComp, to boot.
   The main positive of this PR, which is that it avoids a failure with a diagnostic that will be obscure to a non-expert user slightly misusing the library, would be better achieved by having the view code insert fully polymorphic dependent arguments - so I'd suggest re-opening this PR, reverting the `Some_inj` implicits, and adapting the view interpretation code instead.

**Pull request merged**
