### PR TITLE
[ci] Add coq-community/coq-performance-tests

### PR DESCRIPTION
**Pull request by JasonGross**
It's tested on the bench, so might as well test it on the CI.  Hopefully
it's not too memory-heavy.  (It should only take a couple of minutes,
time-wise.)

**Kind:** infrastructure.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
This seems way too heavy, it is taking close to one hour in most CI runs now https://gitlab.com/coq/coq/-/jobs/617318412

**Comment by JasonGross** [comment]
If you change `make coq perf` with `make coq perf-Sanity perf-SuperFast`, that will make it significantly lighter.  If you further drop `perf-SuperFast`, that will make it even lighter.

**Comment by JasonGross** [comment]
(And `make coq perf-Sanity` alone would be enough to catch any bugs / regressions that `make coq perf` does, as `perf` and `perf-SuperFast` run the same tests as `perf-Sanity`, just on larger inputs.)

**Comment by ejgallego** [comment]
Thanks @JasonGross , what should be done about the `validate` / `install` steps?

**Comment by JasonGross** [comment]
Nothing.  `make coq` is enough for the `validate` and `install` targets.  There's a separate `install-perf` target that depends on `make perf`, but it's not important for Coq to test it.  (And there's no point in running `coqchk` on the `vo`s generated by the `perf` target(s); the files there all just `Require Import` two files, and then do `Goal True. <run_perf_tactic> Abort.`.)

**Comment by ejgallego** [comment]
> Nothing

Not sure I follow, they should be removed from the CI file? I mean, you say there is no point on running validate right?

**Comment by JasonGross** [comment]
No, I mean leave them as they are.  The new invocation should be
```diff
-( cd "${CI_BUILD_DIR}/coq_performance_tests" && make coq perf && make validate && make install )
+( cd "${CI_BUILD_DIR}/coq_performance_tests" && make coq perf-Sanity && make validate && make install )
```

**Pull request merged**
