### PR TITLE
[experiment] Use kernel reduction in Inductiveops.find_rectype and variants.

### PR DESCRIPTION
**Pull request by ppedrot**
We also factorize a bit the code.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by Alizter** [comment]
cc @Zimmi48

**Comment by ppedrot** [comment]
Probably not worth it?

**Comment by Alizter** [comment]
Well there are some genuine speedups in unimath. It might be worth it, tho if you don't want to touch the kernel for no reason then it's fine.

**Comment by ppedrot** [comment]
This doesn't touch the kernel though.

**Pull request closed without merging**
