### PR TITLE
Do not automatically declare unfold hints for Program subproofs.

### PR DESCRIPTION
**Pull request by ppedrot**
Alternative to #16277, let's see how the CI fares. (I don't expect much breakage, if any.)

### CODE REVIEW

**Comment by ppedrot** [comment]
CI all green...

**Comment by SkySkimmer** [comment]
changelog?

**Review by SkySkimmer — APPROVED** [review]

**Comment by ppedrot** [comment]
Changelog added. I've checked, and AFAICT the documentation did not mention that quirk so that there is nothing else to do.

**Comment by ppedrot** [comment]
@SkySkimmer ping

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
