### PR TITLE
[ci] Add scripts for coq-itree

### PR DESCRIPTION
**Pull request by ejgallego**
Useful for debugging some bugs, such as https://github.com/coq/coq/issues/12668

BTW, we should split mathcomp into 3 separate jobs these days.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I'm not sure if it's useful to have non-tested scripts.

**Comment by ejgallego** [comment]
> I'm not sure if it's useful to have non-tested scripts.

They don't bother much, we already have all the ones in `nix/` that are not tested IIC, see the discussion for #8978

**Comment by SkySkimmer** [comment]
The nix stuff is more separate IMO

**Comment by ejgallego** [comment]
> The nix stuff is more separate IMO

What we do with this @SkySkimmer ?

**Comment by SkySkimmer** [comment]
Close or add to the gitlab jobs

**Comment by ejgallego** [comment]
> Close or add to the gitlab jobs

Actually I think that having a database of developments to test is useful even if not in the CI, let's chat about this in the next call.

**Comment by ejgallego** [comment]
After discussion in today's call it was decided that this should not be kept unless it is in the CI.

I still disgress in the sense that would some other report about itree come up I would have to re-do all this work again, this quickly accumulates to a loss of time.

**Pull request closed without merging**
