### PR TITLE
Fix #15420: statically hardwiring the names of arguments in induction schemes

### LINKED ISSUE #15420: `apply...with` does not work any more with `(Combined) Scheme` since they have self-conflicting arguments
#### Description of the problem

It seems #13837 breaks `apply ... with` for induction schemes (both normal and those produced by `Scheme` and by `Combined Scheme`); in practice that's mostly a problem for `Combined Scheme`s since the `induction` tactic works for everything else.

The problem is that argument names look like:
```
typed_mut_ind :
∀ (P : ctx → tm → ty → Prop) (P0 : ctx → ty → nat → ty → nat → Prop),
Arguments typed_mut_ind
  (P P f f f f f f f f f f f f f f f f f f f)%function_scope 
  Γ t t t
```

dot-iris@9f031fb6f956e900c846284f56d976e66f98b5fa shows a patch that was necessary. In that case `apply (term args)` is a reasonable (and better) alternative, but that alternative would be more annoying for datatypes declared in a `Section`.

I'm not sure what the best fix would be; here one could move the renaming that was done by `apply` into the code generator.
But I wonder whether top-level functions with argument name conflicts should at least trigger a warning.

#### Coq Version

8.15-rc1

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix

Names of schemes used to be dynamically recomputed in the local context (an old heritage of working with `coqtop` and not having `Arguments` at hand). #13837 fixes this by providing stable names.

The dynamic renaming used to also ensure distinct names. This PR ensures that distinct names are chosen statically.

This allows in particular to have `apply with` to continue to work.

Fixes #15420.

Notes:
- I did not try to be particularly efficient in collecting names. If needed, efforts can be made
- I favored compatibility to nice choice of names: for instance, in `Inductive F f := f -> F f.`, `F_rect` has arguments `f P f0 f1` and `Inductive PP P := D : P -> PP P.` has arguments `P P0 f p`
- I did not take time yet to look at other schemes to double-check if they do have static names

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
The devil of names has struck again. Interestingly, when defining `Inductive eq A (x:A) : A -> Prop := eq_refl : eq A x x.`, `eq_rect` has names `A`, `x`, `P`, `f`, and `y`. Where does the `y` comes from? From a bug in passing the correct environment to the function which generates names from their type. Without the bug, it should have been `a` (because the variable inhabits `A`). But with the bug, the variable is unbound and it gets the default name `y`.

Fixing the bug and using an explicit `Arguments` to force the name in `eq_rect` seems enough to fix the stdlib. Let's see if ok with CI (the bug is about the non-dependent indices in non-recursive types in Prop, so basically for `eq`).

**Comment by herbelin** [comment]
As expected, only names for redefinitions of `eq` are concerned by the naming bug. What to do, correcting the bug or considering that this is a minor and rather local issue which would better be left as is?

**Comment by JasonGross** [comment]
It's easy to make a backwards compatible overlay with `Arguments`, right?  I'd say document the incompatibility in the change log, prepare the overlays for eq-like types, and merge the fix

**Comment by mattam82** [comment]
I agree with @JasonGross here.

**Comment by SkySkimmer** [comment]
bench https://gitlab.com/coq/coq/-/jobs/2017024214

**Comment by herbelin** [comment]
@SkySkimmer: are you ok with the changes? Do you see other situations where we might need to statically compute distinct names in advances? See also #15539 which would be another step in statically ensuring distinct names for constants.

**Comment by SkySkimmer** [comment]
I'm ok

**Comment by herbelin** [comment]
The backwards compatible overlays have been merged.

**Review by mattam82 — APPROVED** [review]
Looks good, thanks Hugo for the fix! I think this is ready to merge, right?

**Comment by herbelin** [comment]
>  I think this is ready to merge, right?

Yes, I would say so.

**Pull request merged**
