### PR TITLE
Prevent back and forth change of representation in kernel strong reduction

### PR DESCRIPTION
**Pull request by ppedrot**
Fix en passant a subtle bug in relevance computation for the domain of Flambda. The info passed was the one for the extended context when the type was expected to live in the outer context. Not critical because the kernel does not rely on this.

### CODE REVIEW

**Comment by ppedrot** [comment]
https://gitlab.com/coq/coq/-/jobs/1256519783

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-hott │  291.33   293.78  -0.83 │   793058420727    796746415991  -0.46 │  1165026981145   1165980128794  -0.08 │  584200   584704   -0.09 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   51.94    52.21  -0.52 │   144386970408    144635667318  -0.17 │   188661772437    188894839438  -0.12 │  480084   481196   -0.23 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  646.08   649.28  -0.49 │  1793823632824   1804501021770  -0.59 │  2555141239326   2563993115836  -0.35 │ 3274404  3677908  -10.97 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1243.96  1248.61  -0.37 │  3453553810230   3466765376999  -0.38 │  4615342540798   4624208108520  -0.19 │  903916   900520    0.38 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  150.12   150.68  -0.37 │   417260080661    418839532598  -0.38 │   507578469814    508131330210  -0.11 │  554644   556116   -0.26 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-coqutil │   61.86    62.05  -0.31 │   170865811001    170289549042   0.34 │   210320585993    210502141128  -0.09 │  517936   523540   -1.07 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  163.36   163.79  -0.26 │   454446077863    455267854667  -0.18 │   596411772511    597012616196  -0.10 │  744300   731720    1.72 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                         coq │    4.49     4.50  -0.22 │    12477039948     12406298201   0.57 │    23206738706     23208242073  -0.01 │  274496   274464    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 5073.53  5083.51  -0.20 │ 14127732187247  14146542435017  -0.13 │ 23708575403799  23709922122366  -0.01 │ 2212988  2208212    0.22 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-bedrock2 │  334.23   334.88  -0.19 │   928340287986    930880625130  -0.27 │  1531820889441   1533321792831  -0.10 │  752924   774072   -2.73 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-bignums │   60.30    60.41  -0.18 │   166173627399    166197284228  -0.01 │   211834996286    211913820450  -0.04 │  463672   465184   -0.33 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-coquelicot │   73.84    73.95  -0.15 │   204297504761    203978643946   0.16 │   241484217900    241315461897   0.07 │  559488   559532   -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  184.70   184.89  -0.10 │   513530419789    514095377739  -0.11 │   680956732371    681149966595  -0.03 │  683676   691324   -1.11 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-corn │ 1580.54  1581.96  -0.09 │  4395150560833   4387040878783   0.18 │  5985133246145   5995040368227  -0.17 │  773196   789904   -2.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2713.22  2715.40  -0.08 │  7550319541050   7556925431517  -0.09 │ 12245840039126  12247322434837  -0.01 │  730632   730812   -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1633.98  1634.68  -0.04 │  4561754825075   4572969293743  -0.25 │  7210339585875   7218080404179  -0.11 │ 2154032  2154152   -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-stdlib │  421.59   421.58   0.00 │  1180919351191   1182020172355  -0.09 │  1470291102497   1472361728003  -0.14 │  566772   569348   -0.45 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-rewriter │  722.48   722.20   0.04 │  2010750358719   2011166778990  -0.02 │  2932946992463   2935353994203  -0.08 │ 1100320  1100540   -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   57.44    57.40   0.07 │   158304333883    158529974322  -0.14 │   188535977109    188793076427  -0.14 │  522664   521124    0.30 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1136.80  1135.50   0.11 │  3161697319716   3159189407854   0.08 │  4708385476821   4713977449290  -0.12 │  907572   905952    0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  239.58   239.30   0.12 │   667363457291    666306907474   0.16 │   952759897698    953868335800  -0.12 │  665284   666056   -0.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-verdi │  105.89   105.75   0.13 │   292086870682    291801933608   0.10 │   386793709665    386772217424   0.01 │  539496   543988   -0.83 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-math-classes │  189.38   189.12   0.14 │   522386359511    520420538429   0.38 │   652657111931    654479252585  -0.28 │  479364   479664   -0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1460.29  1458.18   0.14 │  4050335704547   4044397799876   0.15 │  5634869188548   5638841028445  -0.07 │  992320   992156    0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-unimath │ 4179.69  4172.38   0.18 │ 11630498624897  11596349711741   0.29 │ 21227245324003  21243782225051  -0.08 │ 1121376  1121320    0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-perennial │ 7304.43  7291.52   0.18 │ 20319242940210  20272631524960   0.23 │ 29061266859448  29091121019757  -0.10 │ 3101524  3131532   -0.96 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-color │  528.94   527.74   0.23 │  1467596311864   1465873501052   0.12 │  1725942696622   1728764012925  -0.16 │ 1131740  1146308   -1.27 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  795.68   793.47   0.28 │  2218705234533   2213176655242   0.25 │  3291355725257   3296250686486  -0.15 │ 1101536  1100640    0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-core │  110.46   110.09   0.34 │   308859520456    307713055665   0.37 │   453878144014    453297690717   0.13 │  274544   274540    0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1362.19  1355.96   0.46 │  3784728236532   3769697056993   0.40 │  5099121498479   5103576852278  -0.09 │ 1107816  1106312    0.14 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-flocq │  158.86   157.87   0.63 │   441641438921    439172052110   0.56 │   508147714798    508324644049  -0.03 │  821784   817388    0.54 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fiat-core │  116.94   116.12   0.71 │   327875913120    327594780342   0.09 │   409562186260    409032089409   0.13 │  479100   479076    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  335.59   332.95   0.79 │   942995937790    936635977286   0.68 │  1661356895929   1650299842800   0.67 │ 3119144  3118832    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqprime │ 1505.99  1487.87   1.22 │  4192429616517   4142228246827   1.21 │  6588359373378   6591161741144  -0.04 │ 1056288  1056308   -0.00 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
This doesn't seem to have an observable effect, but:
- It fixes a bug
- In my completely unbiased opinion, I find the new code cleaner, notably inlining `zip_term` makes it clear that it's only used for strong normalization.

**Comment by SkySkimmer** [comment]
coqprime timing is slightly suspicious, is the line by line timing reassuring?

**Review by SkySkimmer — APPROVED** [review]

**Comment by ppedrot** [comment]
Nothing specific in the per-line time diff of coqprime. For some reason, this dev seems to be a bit more noisy than the other ones, you can see that in the recent benches from other PRs.

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
