### PR TITLE
Windows: Fix interval tactic 

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
The patch for intevral I delivered compiled, but the tactic did not work in all cases. This PR
- fixes the interval patch
- enables testing of interval in the Windows build

**Kind:** bug fix

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Looks like it was a good idea to enable the test suite for interval. It passes in the 64 bit build but not in the 32 bit build (for no obvious reasons). Interestingly there is a very substantial difference between the 32 bit and 64 bit builds of coq (the build logs of interval are identical modulo folder and architecture names). I will create a separate issue for this.

**Comment by MSoegtropIMC** [comment]
This PR is blocked by #11321.

**Comment by MSoegtropIMC** [comment]
Just a note: I have a more elegant fix for the hiding or nil and cons by RList - simply Import List again. I will change this in the files which have this frequently.

**Comment by ppedrot** [comment]
I've backported the relevant PR into 8.11, @MSoegtropIMC can you rebase on the latest 8.11? Thanks.

**Comment by MSoegtropIMC** [comment]
@ppedrot : you are good to go. I downloaded the 32 bit installer and tested it with the test cases I developed. I added @silene as reviewer.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@MSoegtropIMC does this PR *require* a review from @silene? I think it's nice if he can comment on it, but the changes are somehow straightforward enough not to have to be pending on an additional review, and thus delaying merge.

**Comment by MSoegtropIMC** [comment]
> does this PR _require_ a review from @silene? I think it's nice if he can comment on it, but the changes are somehow straightforward enough not to have to be pending on an additional review, and thus delaying merge.

I don't think so - it is definitely an improvement. Without this PR interval does not work. With this PR at least the Interval test suite and my own tests run through. I think it is unlikely that there are errors left in the Ltac part where the type checker can't detect them at compile time (without using the tactics). First I did the repair systematically by repalcing all occurecnes of cons and nil and second this is mostly reflection based and the tactics are only doign the translation and this should be covered by the test cases. The complicated stuff is in Gallina and this is fully checked when compiling the library.

I just wanted to give @silene a chance to comment.

**Comment by ppedrot** [comment]
OK, will merge tomorrow then.

**Pull request merged**
