### PR TITLE
Fix anomaly in [Type foo] command, + print uctx like Check.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by maximedenes** [comment]
I don't see the point of this undocumented command, so I would rather be in favor of removing it. What do you think?

**Comment by SkySkimmer** [comment]
*shrug* I don't care either way.

**Comment by ejgallego** [comment]
Maybe this command is useful to some developers for debug purposes wrt the kernel?

**Comment by herbelin** [comment]
> I don't see the point of this undocumented command, so I would rather be in favor of removing it. What do you think?

The syntax is probably not good. We should probably find one reminiscent of ` Check`, but the use case is clear: it is to `Check` in the global context rather than in the context of the current goal as `Check` does by default.

Maybe `0:Check` would be clearer? Though certainly a bit too hacky. Or `Global Check`? What do you think?

**Comment by ejgallego** [comment]
> to Check in the global context rather than in the context of the current goal as Check does by default.

That's interesting, when do you need to do that? Is it due to shadowing?

**Comment by herbelin** [comment]
I don't know if it "really" needed. In particular, with a GUI, it is probably as easy to move the cursor outside the current goal and to type `Check` (or to call the `Check` menu).

It is just a matter of consistency. As soon as we can "check" in the `n`-th subgoal, it should be legitimated to "check" outside of the current proof. Actually, the code for `vernac_global_check` should a priori be the same as the one for `Check` (but using the `Global.env()` rather than `get_current_context_of_args`).

**Comment by ejgallego** [comment]
Thou conceptually to me it looks like `Check` should not live in the proof state really, as it is not a tactic, but yeah, I guess there are many ways to see it.

**Review by ejgallego — APPROVED** [review]
In my limited understanding, this looks good.

**Comment by Zimmi48** [comment]
@SkySkimmer Your test being 8.8-only, I don't know if the anomaly is reproducible in 8.7 with a slightly different test. Thus, putting the 8.8 milestone but if you can find a way to reproduce the anomaly in 8.7, please change the milestone (and the test, so that it is easy to backport).

**Comment by SkySkimmer** [comment]
>@SkySkimmer Your test being 8.8-only, I don't know if the anomaly is reproducible in 8.7 with a slightly different test. Thus, putting the 8.8 milestone but if you can find a way to reproduce the anomaly in 8.7, please change the milestone (and the test, so that it is easy to backport).

Test fixed.

**Comment by SkySkimmer** [comment]
The anomaly dates from a long time ago, maybe even 7.0 (it should exist in some form after commit 8e82c4096357355a148705341742702ff285f72a), see new test which doesn't use universe polymorphism.

**Comment by SkySkimmer** [comment]
New new test: `Type Type : Type.`

**Comment by maximedenes** [comment]
Let's merge this fix and discuss the removal of the command separately.

**Comment by herbelin** [comment]
> Let's merge this fix and discuss the removal of the command separately.

I would propose to use an inclusive writing:

"Let's merge this fix and discuss the removal or non removal of the command separately."

**Pull request merged**
