### PR TITLE
Update frozen evars after running typeclasses in solve_remaining_evars

### LINKED ISSUE #5239: Hint Rewrite fails with "Evar ?X62 was not declared. Please report"
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5239
From: @pilki
Reported version: 8.5
CC:   coq-bugs-redist@lists.gforge.inria.fr

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #5239

Overlays:
- https://github.com/AbsInt/CompCert/pull/465
- https://github.com/PrincetonUniversity/VST/pull/642
- https://github.com/mit-plv/fiat-crypto/pull/1519

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
fiat-crypto and vst also look like real errors (vst is from the bundled compcert)
@coqbot ci minimize ci-compcert ci-fiat_crypto

**Comment by SkySkimmer** [comment]
Seems like it relies on buggy behaviour like
~~~coq
Class Inhabited (A:Type) := {repr : A}.

(* Removing this instance gets rid of the bug *)
#[local] Instance Inhabited_option A : Inhabited (option A) := {repr := None}.

Lemma option_refl {A}: forall `{Inhabited A} (u : A), u = u.
Proof. reflexivity. Qed.

Definition ignore {A} (x:A) := tt.

Goal unit.
Proof.
  exact (ignore option_refl). (* should fail but leaves shelved Type goal *)
  (* therefore *) Fail Qed. (* Qed after exact on the only goal shouldn't fail *)
~~~

**Comment by SkySkimmer** [comment]
Actually I don't know if exact is buggy, eg `apply _` also accepts it but that uses a different checker (tclwithholes)

**Comment by SkySkimmer** [comment]
This one looks like
~~~coq
Ltac foo x := refine x.

Goal unit.
Proof.
  foo (ignore option_refl).
~~~
before: succeeds with Type goal shelved
after: fails

**Comment by SkySkimmer** [comment]
Overlays added

**Comment by ppedrot** [comment]
@SkySkimmer shouldn't you add a changelog? This is a user-visible change.

**Comment by SkySkimmer** [comment]
Changelogged

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by Zimmi48** [comment]
I would appreciate getting this merged soon, so that I can start pinning commits used in CI on the `v8.17` branch.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
