### PR TITLE
Stale workflow: fix syntax for using secret.

### PR DESCRIPTION
**Pull request by Zimmi48**
Hopefully, this will be the last iteration fixing this workflow.
Currently, the pipeline runs but coqbot answers "Error: Incorrect secret".

cc @ppedrot

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
Can the workflow be run manually to test before the night?

**Comment by Zimmi48** [comment]
> Can the workflow be run manually to test before the night?

Not AFAIK.

**Comment by Zimmi48** [comment]
I tried to see if by chance re-running the last stale workflow would do that, but it apparently reuses the workflow definition from when it last ran.

**Comment by Zimmi48** [comment]
Looks like it worked this time.

**Pull request merged**
