### PR TITLE
Fix computation of {struct} with implicit generalization

### LINKED ISSUE #13157: Generalizable Variables breaks fixpoint decreasing argument reference
#### Description of the problem
This issue is a special case of #2344 that does not seem handled by the fix `r13086`.

```coq
Generalizable Variable A.
Implicit Type A : Type.

Definition works2344 : forall `(l : list A) (l' : list A), unit :=
  fix flist `(l : list A) (l' : list A) {struct l'} := tt.

Fail Definition fails : forall `(l: list A), unit :=
  fix flist `(l : list A) {struct l} := tt.

(* Error: *)
(* Recursive definition of flist is ill-formed. *)
(* In environment *)
(* flist : forall A : Type, list A -> unit *)
(* Recursive definition on "Type" *)
(* which should be a recursive inductive type. *)
(* Recursive definition is: "fun (A : Type) (_ : list A) => tt". *)
```

#### Coq Version

Observed on a variant of master (`bd57c1a48cca55be374e597e2d89fe619a39c26e`) and on coq 8.11.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13157

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Looks good.

**Comment by SkySkimmer** [comment]
assignee?

**Comment by herbelin** [comment]
Assiging. Merging soon.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
