### PR TITLE
Use weak ref to memoize Evarutil.is_ground_env

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fixes part of #12487

### CODE REVIEW

**Comment by ppedrot** [comment]
I confirm that this solves the evar leak on my minimal example.

**Review by ppedrot — APPROVED** [review]
Code change looks good, but this needs a benchmark.

**Comment by SkySkimmer** [comment]
Bench 971 is pending.

**Comment by ppedrot** [comment]
I ran a dynamic analysis of the cache on the stdlib, and it seems not to be very useful, as it misses in the vast majority of the time. I suspect that the equality test on the environment is too coarse, as it is defeated by e.g. universe refinement. I will try to see what happens on unification-heavy runs.

**Comment by SkySkimmer** [comment]
For reference the memo was introduced in c580f69cc36cc4cc908febb900a55ae751039a0c

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/971/console
~~~
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬─────────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │     mem faults      │
│                             │                         │                                             │                                             │                               │                     │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │   NEW   OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│       coq-mathcomp-fingroup │   49.55   49.89 -0.68 % │      138038063685      137928976301 +0.08 % │      191719794108      191839799548 -0.06 % │     551488     552892 -0.25 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│       coq-performance-tests │ 1954.50 1967.24 -0.65 % │     5444768251495     5481161672011 -0.66 % │    10151078133304    10147791914853 +0.03 % │    4316028    4315976 +0.00 % │     5     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                coq-rewriter │  580.48  584.24 -0.64 % │     1611651843264     1621190830052 -0.59 % │     2477861109512     2477998193734 -0.01 % │     985172     953464 +3.33 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│ coq-rewriter-perf-SuperFast │ 1039.58 1045.30 -0.55 % │     2892473226109     2909265313227 -0.58 % │     4580468957276     4582002379101 -0.03 % │    1056056    1056024 +0.00 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                   coq-verdi │  120.54  120.86 -0.26 % │      334105918440      333913811254 +0.06 % │      418789913702      418967485497 -0.04 % │     561508     562360 -0.15 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                 coq-bignums │   58.44   58.51 -0.12 % │      162239425314      162034288826 +0.13 % │      219247445982      219259411231 -0.01 % │     468024     467928 +0.02 % │    11     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                 coq-coqutil │   60.83   60.89 -0.10 % │      169683688584      168130774825 +0.92 % │      212842837512      212878791063 -0.02 % │     528980     529760 -0.15 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                         coq │  555.17  555.53 -0.06 % │     1557874395969     1557686402618 +0.01 % │     2124785827414     2125778950807 -0.05 % │     602840     602680 +0.03 % │     6     6 +0.00 % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│            coq-fiat-parsers │  661.07  661.24 -0.03 % │     1850521380917     1851234871588 -0.04 % │     2782765842148     2783468739948 -0.03 % │    3588108    3580480 +0.21 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│            coq-engine-bench │ 6402.37 6401.72 +0.01 % │    17870641055827    17871275485010 -0.00 % │    31407562591860    31408393664607 -0.00 % │    4315960    4316016 -0.00 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│          coq-mathcomp-field │  264.90  264.81 +0.03 % │      737938998155      736768352657 +0.16 % │     1124110310996     1124129116629 -0.00 % │     792836     799980 -0.89 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                    coq-hott │  305.03  304.76 +0.09 % │      826625497973      825653711866 +0.12 % │     1317982601930     1317971654814 +0.00 % │     630496     630648 -0.02 % │     6     5 +20.00 % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│             coq-fiat-crypto │ 5177.87 5171.96 +0.11 % │    14387119556051    14366521343886 +0.14 % │    24350291682730    24358339574795 -0.03 % │    2391564    2466340 -3.03 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│      coq-mathcomp-character │  163.96  163.75 +0.13 % │      456519668767      456159409826 +0.08 % │      634350923239      634549991163 -0.03 % │     810648     810428 +0.03 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│       coq-mathcomp-solvable │  176.44  176.20 +0.14 % │      491783341209      491224191135 +0.11 % │      695917426043      696038212858 -0.02 % │     787696     789908 -0.28 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                coq-bedrock2 │  223.49  223.18 +0.14 % │      619196586245      618672635542 +0.08 % │     1026884447571     1027243691883 -0.03 % │    1090960    1091004 -0.00 % │     4     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│      coq-mathcomp-odd-order │ 1139.86 1137.77 +0.18 % │     3175377709513     3167526759577 +0.25 % │     5098675711820     5099237247269 -0.01 % │    1268740    1276476 -0.61 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│              coq-verdi-raft │ 1278.80 1275.21 +0.28 % │     3561426955133     3552009182009 +0.27 % │     4967686868832     4968172639946 -0.01 % │     973016     972988 +0.00 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│               coq-fiat-core │  110.30  109.98 +0.29 % │      314494710400      313205967808 +0.41 % │      418565080196      418683115895 -0.03 % │     488708     489784 -0.22 % │     6     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                 coq-unimath │ 4087.14 4074.96 +0.30 % │    11371032902685    11336279602643 +0.31 % │    21521234434006    21519667140480 +0.01 % │    1011240    1011184 +0.01 % │     1     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│            coq-math-classes │  205.99  205.35 +0.31 % │      574986465267      572983477795 +0.35 % │      775826881423      776706337395 -0.11 % │     512192     520132 -1.53 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│             coq-lambda-rust │ 1532.36 1527.09 +0.35 % │     4265720639006     4251593252452 +0.33 % │     6073943808390     6072682809053 +0.02 % │    1205532    1213188 -0.63 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│      coq-mathcomp-ssreflect │   52.89   52.70 +0.36 % │      145597760889      144862913265 +0.51 % │      189873918492      189903137278 -0.02 % │     572996     574456 -0.25 % │     2    14 -85.71 % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│              coq-coquelicot │   74.18   73.86 +0.43 % │      203717395646      203114139244 +0.30 % │      266742859647      266999932529 -0.10 % │     659800     660952 -0.17 % │    16     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                    coq-corn │ 1637.00 1629.93 +0.43 % │     4557178390754     4545407858301 +0.26 % │     6966184386461     6968342071231 -0.03 % │     888224     887888 +0.04 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                  coq-geocoq │ 1500.58 1493.88 +0.45 % │     4178610685329     4162736021679 +0.38 % │     6326674793396     6328058380011 -0.02 % │    1215564    1215452 +0.01 % │     2     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│        coq-mathcomp-algebra │  143.78  143.13 +0.45 % │      399171827364      398406765057 +0.19 % │      520220360921      520247733648 -0.01 % │     614960     616088 -0.18 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                coq-compcert │  691.46  688.09 +0.49 % │     1928140836477     1918753786299 +0.49 % │     2672065040383     2673028053447 -0.04 % │    1077140    1077088 +0.00 % │     1     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                   coq-color │  657.47  654.22 +0.50 % │     1833385832403     1826319384986 +0.39 % │     2310570520051     2311218798493 -0.03 % │    1153268    1154224 -0.08 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                   coq-flocq │  171.96  170.98 +0.57 % │      476844770623      474823507388 +0.43 % │      598135273682      598419435655 -0.05 % │     903196     904204 -0.11 % │     6     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                coq-coqprime │   83.66   83.09 +0.69 % │      229769608325      228942426470 +0.36 % │      322943123675      322990813693 -0.01 % │     764748     765068 -0.04 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│               coq-fourcolor │ 2540.56 2521.81 +0.74 % │     7083200331225     7032697933707 +0.72 % │    11585258297743    11583026652655 +0.02 % │     875072     875056 +0.00 % │     0     0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼─────────────────────┤
│                  coq-sf-plf │   44.12   43.73 +0.89 % │      123096649288      122462637874 +0.52 % │      168017338198      168016747030 +0.00 % │     508752     502568 +1.23 % │     0     0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴─────────────────────┘
~~~

**Comment by ppedrot** [comment]
Let's merge, I don't think there is more to be said both about the issue and the fix.

**Pull request merged**
