### PR TITLE
Port the ssr tactic API to the new engine.

### PR DESCRIPTION
**Pull request by ppedrot**
In practice, this means that all ssreflect tactics now export new tactic
types. Internally, they still rely on the compatibility layers, but this
means it will be easier to port the code piecewise.

Specific types that were not tactics, like a few `pf_*` variants, were left
as-is. Still, they should also be given in terms of tactics at some point
as well.

### CODE REVIEW

**Comment by ejgallego** [comment]
Out of curiosity, bench at https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/250/

**Comment by ejgallego** [comment]
Relevant bits:
```
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   39.04   38.84 +0.51 % │  107916743104  106696184436 +1.14 % │  134395398747  132933285665 +1.10 % │  479712  480372 -0.14 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  266.96  264.78 +0.82 % │  742725530086  735725461865 +0.95 % │ 1104843387635 1094843856434 +0.91 % │  982512  982380 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   60.47   59.87 +1.00 % │  167158417136  165232580059 +1.17 % │  234015092316  231509410587 +1.08 % │  528988  528668 +0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  168.34  166.44 +1.14 % │  467407653057  463024019441 +0.95 % │  718911070381  714912376094 +0.56 % │  734976  728688 +0.86 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  171.53  169.40 +1.26 % │  476343297345  470702666532 +1.20 % │  677721635028  671899721473 +0.87 % │  592264  590464 +0.30 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  453.72  446.28 +1.67 % │ 1261863371525 1242487193257 +1.56 % │ 2118488574752 2093338983270 +1.20 % │  726172  731960 -0.79 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  195.56  190.82 +2.48 % │  543440078150  529873078948 +2.56 % │  792717996580  773291158060 +2.51 % │  716340  716260 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1427.88 1371.44 +4.12 % │ 3974028121692 3821358624086 +4.00 % │ 6968764783734 6716324236891 +3.76 % │ 1118040 1211708 -7.73 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

So that's a 2.79% global penalty, and that's just for switching the interface, right?

We know that the new engine is not the paramount of efficiency but these numbers are a bit concerning.

**Comment by ppedrot** [comment]
The reason is that the compatibility layer adds upfront evar-normalization. Getting rid of it would give back the old performance.

**Comment by ejgallego** [comment]
Oh indeed that explains things. So maybe it would be better to pack this PR together with the one removing the compat layer in full?

**Comment by gares** [comment]
Also I've always found the nf_evar argument a bit fishy.
It is true that replacing in a goal G all assigned evars with their values is expensive.
It is true that code ported to EConstr applies the substitution lazily.
What is not necessarily true is that performing the replacement once and forall is slower than performing it lazily over an over.

In some sense when a constr T is normalized to T1 you are caching in T1 its normal form.
So it really depends what you do, e.g. if you use your goal G (the conclusion) twice, say in f1 and f2, better normalize it once to G1 use f1 G1 and f2 G1. Sure, the evar map have evolved so f2 may need some extra
normalization steps, but at least will not need the ones already done in G1.

So I really want to see how things behave in practice before buying any speedup on paper.
Finally, it really seems the claim is close to "call by name is faster than call by value"... that is hardly true (in practice) even if you use everything linearly.

**Comment by ppedrot** [comment]
@gares You're definitely right, removing evar-normalization may theoretically trigger blowups. In practice, the trade-off is clearly in favour of EConstr, compared to the cost of repeatedly normalizing goals (and in particular hypotheses). That said, I do want to provide a more clever representation of tactic constrs so as to share evar-expansion, which would correspond to call-by-need in your analogy.

Also, the old engine was not performing normalization most of the time, only in very specific primitives, so not performing it either in the new engine cannot be really worse.

**Comment by ejgallego** [comment]
Well, in my view `EConstr` is more about correctness than about performance, and indeed I think that it will be always better in practice, note that nothing forbids the tactic writer to be eager and call `nf_evar` on a term.

The only two cases I think `EConstr` seems to fall short is universes, and in some parts of unification which want to handle set of constraints, which is at odds with lazy substitution. Only the first matters for tactics IMHO.

And of course, more porting needs to be done, and many bugs related to evar_map substitution seem to be still lurking around, but we are close to be able to enforce stronger invariants I think.

**Comment by gares** [comment]
> Well, in my view EConstr is more about correctness than about performance

I totally agree, and I've always liked EConstr. I was just pointing out that, when all the code will be safely behind the EConstr abstraction, removing  `nf_evar` may not always be a speedup, i.e. you may not recover what you think is temporarily lost by using the V82 compat layer (that this PR pushes).

So, as you said, I think this PR should be evaluated together with a full port of some tactics to tactic monad.

I think we (maxime and myself) will be able to fully port `ssrfwd` to the tactic monad (+EConstr) by February, complementing this PR.

**Comment by maximedenes** [comment]
@ppedrot  can you update the milestone to reflect your current schedule? Thanks!

**Comment by ppedrot** [comment]
I think I can close this PR, @gares is working on this on his own. The branch is still alive if people want to pick commits.

**Pull request closed without merging**
