### PR TITLE
Pass stdlib with default goal selector ! (except ssr)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by silene — APPROVED** [review]
Looks good. But do I understand correctly that, except for these few lines, the vanilla standard library was already perfectly structured? That is mind-boggling.

**Comment by SkySkimmer** [comment]
That's because there was work to make it that way
- https://github.com/coq/coq/pull/9386
- https://github.com/coq/coq/pull/16037

**Comment by Zimmi48** [comment]
Should the Dune rules be adapted so that the default goal selector `!` is used when building the stdlib?

**Comment by SkySkimmer** [comment]
If we start enforcing it we should make sure editors also enforce as otherwise it's rather difficult to fix issues.
Last time I tried I couldn't find a good way to do that, Default Goal Selector being multiple words makes it hard to use properly in _coqproject

Considering how few cases needed to be fixed since the last time a year ago I don't think it's worth putting time into automatic enforcement.

**Review by andres-erbsen — APPROVED** [review]

**Comment by andres-erbsen** [comment]
If whitespace in the vernac command is the blocker, I think we can do something about that. Here's one possible avenue:

```
$ head settings/defgs.v
#[export]
Set Default Goal Selector "!".
$ coqc -Q settings Settings settings/defgs.v 
$ coqtop -Q settings Settings -require-import 'Settings.defgs'
Welcome to Coq 8.16.1

Coq < Goal True /\ True.
1 goal
  
  ============================
  True /\ True

Unnamed_thm < split.
2 goals
  
  ============================
  True

goal 2 is:
 True

Unnamed_thm < auto.
Toplevel input, characters 0-5:
> auto.
> ^^^^^
Error: Expected a single focused goal but 2 goals are focused.
```

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Pull request merged**
