### PR TITLE
Move the DeclareUctx module from tactics/ to vernac/.

### PR DESCRIPTION
**Pull request by ppedrot**
Not sure why it was there but the reason is now probably invalid, since all callers live in vernac/. Since the raison d'être of this module is to mess with the global environment it should definitely live upper than tactics.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ppedrot** [comment]
Why is there an unrelated warning in the test-suite now???

**Comment by ejgallego** [comment]
I recall right, it was used by `tactics/hints.ml`, but 674dcda367d9ed43f3b0cc8264a0ef10bc7fd751 fixed that.

**Comment by SkySkimmer** [comment]
>Why is there an unrelated warning in the test-suite now???

If you mean the coqdoc verbatim thing it's also in master https://gitlab.com/coq/coq/-/jobs/1754045996#L1976

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
