### PR TITLE
Micro-optimizations of the tight loop in Hashset.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by gares** [comment]
If it was Lua, I'd say it's a pretty standard optimization. For OCaml, I think I need a bench...

**Comment by ppedrot** [comment]
https://gitlab.com/coq/coq/-/jobs/878420673
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1229.46  1248.89  -1.56 │  3421113818506   3476613789841  -1.60 │  4960626503087   4984804023367  -0.49 │ 1113780  1097804    1.46 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-perennial │ 5731.28  5810.29  -1.36 │ 15918953171274  16141314961709  -1.38 │ 24092400027137  24197564738860  -0.43 │ 3104164  3092144    0.39 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  629.06   636.86  -1.22 │  1759713727861   1782566349689  -1.28 │  2713819047514   2728982833998  -0.56 │ 3241992  3639508  -10.92 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   51.00    51.62  -1.20 │   139115929539    140517085499  -1.00 │   177840387986    178616755025  -0.43 │  509676   511916   -0.44 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-hott │  320.14   324.03  -1.20 │   869609557288    880310273220  -1.22 │  1424160312677   1434595711567  -0.73 │  618660   728704  -15.10 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-color │  505.08   510.65  -1.09 │  1409190377929   1426367268260  -1.20 │  1784233197132   1795545619641  -0.63 │ 1133800  1077812    5.19 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-compcert │  635.01   641.75  -1.05 │  1768917208544   1788501790866  -1.10 │  2468601470540   2479174733698  -0.43 │ 1047376  1046884    0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-coquelicot │   67.52    68.22  -1.03 │   184709716285    186226248222  -0.81 │   236909103293    237536678565  -0.26 │  564700   566048   -0.24 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                         coq │  516.86   522.07  -1.00 │  1446581347184   1462257430533  -1.07 │  1955856335726   1960060182453  -0.21 │  569320   562404    1.23 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-bedrock2 │  225.65   227.84  -0.96 │   624874434170    629881043372  -0.79 │  1041137637023   1043044527771  -0.18 │ 1159992  1085152    6.90 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  153.60   155.07  -0.95 │   427229482656    430975860900  -0.87 │   597775829513    599603091116  -0.30 │  709816   708992    0.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-unimath │ 3901.48  3937.92  -0.93 │ 10855714306945  10950663581364  -0.87 │ 20927638857706  20985223507105  -0.27 │ 1142404  1134208    0.72 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-coqutil │   59.98    60.51  -0.88 │   166895866181    168195116648  -0.77 │   209035064522    209291318671  -0.12 │  524140   524348   -0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqprime │   78.81    79.46  -0.82 │   216237317542    217736489379  -0.69 │   305610591982    306138342518  -0.17 │  761160   760268    0.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-flocq │  155.31   156.54  -0.79 │   431042921476    434704447111  -0.84 │   539899267096    541082505575  -0.22 │  820832   820820    0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   47.00    47.35  -0.74 │   130490572904    131555763871  -0.81 │   180827934456    181496476934  -0.37 │  478360   481652   -0.68 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  169.52   170.73  -0.71 │   471329276395    475411893671  -0.86 │   669793301679    671953562706  -0.32 │  659516   675176   -2.32 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  137.19   137.97  -0.57 │   381058170892    383404384859  -0.61 │   493682951178    495398509526  -0.35 │  546272   546136    0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-math-classes │  211.53   212.70  -0.55 │   591011676058    592704794615  -0.29 │   812685654834    813117254173  -0.05 │  524416   521956    0.47 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 5085.30  5113.37  -0.55 │ 14133256679949  14206651369264  -0.52 │ 24808197174965  24810346878007  -0.01 │ 2276204  2288004   -0.52 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  222.50   223.57  -0.48 │   618666752032    621986809406  -0.53 │   949109668886    951149442716  -0.21 │  673352   671464    0.28 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1053.64  1058.02  -0.41 │  2934652557494   2944785149108  -0.34 │  4686300224967   4692778629136  -0.14 │  975744   975656    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  364.79   366.18  -0.38 │  1024993925445   1029082418465  -0.40 │  1742372831053   1746959601982  -0.26 │ 3978988  3500064   13.68 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1447.61  1452.66  -0.35 │  4029084009305   4046249820551  -0.42 │  6135930810289   6141547279551  -0.09 │ 1016300  1016956   -0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2577.44  2586.42  -0.35 │  7185002357424   7200193300882  -0.21 │ 12430698883209  12433516888484  -0.02 │  723128   722544    0.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-corn │ 1615.37  1620.69  -0.33 │  4498782776356   4517514585994  -0.41 │  6933731294736   6944938560621  -0.16 │  809148   860408   -5.96 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1220.06  1223.74  -0.30 │  3398457917733   3409312027419  -0.32 │  4829907922708   4837776656664  -0.16 │  903580   901668    0.21 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  788.18   789.46  -0.16 │  2195195835870   2199048248530  -0.18 │  3471671555285   3476464966390  -0.14 │  992284   981300    1.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-rewriter │  721.45   722.04  -0.08 │  1999669271243   2003692683100  -0.20 │  3101196876096   3104759142433  -0.11 │  973876   989060   -1.54 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-verdi │  102.28   102.17   0.11 │   280373365871    282280886933  -0.68 │   397178460545    398415227084  -0.31 │  546720   546596    0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-bignums │   56.80    56.52   0.50 │   157114335037    156348817899   0.49 │   211078630444    211461254036  -0.18 │  473720   476684   -0.62 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fiat-core │  103.32   102.78   0.53 │   292309736966    292679587407  -0.13 │   389637262831    389828188875  -0.05 │  478380   479720   -0.28 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```
Quite small but undeniable speedup. It probably also affects minor heap allocation quite a lot but it's not visible in this data.

**Comment by ppedrot** [comment]
Typo in the commit message fixed.

**Comment by SkySkimmer** [comment]
What's the optimization about? Turning `let rec loop` to an imperative loop?

**Comment by ppedrot** [comment]
Yes. It prevents allocating a useless closure, because for some reason the recursive function was not unrolled into a while loop.

**Comment by SkySkimmer** [comment]
Now I wonder what the impact is on flambda.

**Comment by ppedrot** [comment]
I think I remember that flambda with the default options was clever enough to do that, but it's fragile to rely on underspecified compiler optimizations for this kind of critical functions.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
