### PR TITLE
A stronger progress tactical

### PR DESCRIPTION
**Pull request by aspiwack**
This PR adds a flavour of progress which detects that all the initial goals still appear as subgoals. As discussed in #1766.

This new `strong_progress` tactical is much slower than progress. It also has the property that `strong_progress (swap 1 2)` will always fail. So it's not a drop-in replacement for replace. It is meant to be used, for instance, as part of automation to cut useless branches.

Questions:
- Is `extractactics.ml4` the right place for such new tacticals? (@ppedrot?)
- The CHANGES doesn't distinguish 8.6 commits and post-8.6 commits. We may want to address that before merging this PR.

(cc @maximedenes )

### CODE REVIEW

**Comment by maximedenes** [comment]
@ppedrot where to put such new tacticals?

@aspwicak can you answer @jonleivent 's question?

**Comment by ppedrot** [comment]
Personally, I'd rather put it either in Tacticals or in Tactics. There is a lot of stuff in Extractactics mixed with grammar rules, and we should instead extrude things out of it, not add more.

**Comment by aspiwack** [comment]
Yes, @jonleivent is right.

Do I need to move the code about? I'm fine with it. I'm also fine if we decide that this is not worth including and we close this PR.

@maximedenes @ppedrot let me know what I should do with it.

**Comment by ppedrot** [comment]
After pondering a bit, if we don't have a strongly motivated use case for this tactical, I'd rather close this PR rather than merging it. Otherwise it adds yet another too high-level primitive with a wobbly specification: with respect to which notion of equality *is a subset* is defined? What about multiplicity? (Yes, I know the answer from the code.)

**Comment by ppedrot** [comment]
Let's close this PR then.

**Pull request closed without merging**
