### PR TITLE
Warn non-reversible-notation for notations using volatile casts

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by herbelin — COMMENTED** [review]
What are the typical examples of notations with a volatile cast? For instance, if we used the notation without the cast for printing, would it generally go beyond the intent of the user?

**Comment by SkySkimmer** [comment]
The one I looke zt was https://github.com/coq/coq/pull/18762#issuecomment-1985533031

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@SkySkimmer shouldn't the new warning be documented in the refman?

**Comment by SkySkimmer** [comment]
It's an expanded warning not a new warning.

**Comment by proux01** [comment]
Meh, ok, let's merge.

@coqbot merge now

**Pull request merged**
