### PR TITLE
Consolidate funind documentation onto a single page.

### PR DESCRIPTION
**Pull request by Zimmi48**
This PR consolidates all the documentation of the Funind plugin onto a single page (in the new "Libraries and plugins" chapter). This page was initially created as part of #11914, which extracted the documentation of `Function` from the "Gallina extensions" chapter. The rest of the Funind documentation was taken from the Tactics chapter (`function induction` and `functional inversion`) and from the "Proof schemes" chapter (`Functional Scheme`). By using the technique described in https://github.com/coq/coq/pull/11914#issuecomment-608464355, we preserve the full git history of all the extracted and consolidated parts (`git blame` works perfectly). This additionally required doing some stuff in three commits instead of one (see ff9a3c6, ec34150, 042800c) otherwise `git` heuristics thought I had inserted some lines, which broke the blame.

My conclusion from this experiment is that it takes a lot of effort and while the present case was the perfect example (merge documentation pieces that were previously in different files but make sense to put in a single file but in separate sections), it would not be worth doing when the documentation pieces to consolidate will need much interleaving afterwards.

cc @coq/funind-maintainers

### CODE REVIEW

**Comment by Zimmi48** [comment]
Here is the consolidated Funind doc: https://coq.gitlab.io/-/coq/-/jobs/520652935/artifacts/_install_ci/share/doc/coq/sphinx/html/using/libraries/funind.html

Note that the documentation of `Function` was recently improved following a pass on the "Gallina extensions" chapter, but it was not the case yet of the documentation of `function induction`, `functional inversion` and `Functional Scheme`. It could be worthwhile doing a pass on this new file after this PR is merged.

**Comment by Matafou** [comment]
I don't know when this typo was introduced: the tactic is "functional
induction" and not "function induction".
P.

Le mar. 21 avr. 2020 à 19:40, Théo Zimmermann <notifications@github.com> a
écrit :

**Comment by Zimmi48** [comment]
@Matafou OK, too bad I didn't realize that before, because now that would be too much work to reword the one commit that mentions `function induction`. But I will still push a new commit fixing the doc.

**Comment by Matafou** [comment]
My bad.

**Comment by Matafou** [comment]
oops sorry

**Review by jfehrle — APPROVED** [review]
It looks OK.

**Comment by Zimmi48** [comment]
@cpitclaudel It seems that this won't receive any more changes. Can you merge?

**Pull request merged**
