### PR TITLE
Quote coercions

### PR DESCRIPTION
**Pull request by fchyzak**
Kill dead code (first commit) + Proposed new functionality: [Set Printing Coercions Quoted] that displays coercions between “...”.

### CODE REVIEW

**Comment by gares** [comment]
I guess it is already on your todo list, but just in case it is not, I think collapsing multiple coercions into a single "quote" is a plus.  Another remark is that the current code makes printing/parsing not "round trip".  In the sense that "coercion x" is mapped to "``x''" that is in turn parsed as "QuoteCoercion x" that is not well typed (imagine you copy paste the output of Coq and Check it).  I think you can easily refine the patch by turning QuoteCoercion into a polymorphic identity function so that "``x''" is convertible to "x" (I guess you can just generate an extra GHole in "extern" for the type argument of the identity function).  I also think this constant should not be in Logic.v but in another file of the prelude.  In particular there is one called Notations (sorry, I did not recall its existence this morning).

**Comment by letouzey** [comment]
Dummy comment, for testing notifications from github to coqdev...

**Comment by fchyzak** [comment]
On Tue, 2015-06-23 at 12:56 -0700, Enrico wrote:
> I guess it is already on your todo list, but just in case it is not, I
> think collapsing multiple coercions into a single "quote" is a plus.

It is not, and it is not crystal-clear to me that it would be a plus.  I
would be in favor of keeping the behaviour and/or adding an additional
toggle to have either nested quotes or collapsed quotes.  I may try to
start by defining an additional [Set Printing Coercions Quoted Nested],
but then it seems I have to think more globally of an option that is not
just a bool.

>  Another remark is that the current code makes printing/parsing not
> "round trip". In the sense that "coercion x" is mapped to "x''" that
> is in turn parsed as "QuoteCoercion x" that is not well typed (imagine
> you copy paste the output of Coq and Check it).

OK.  But at the same time, as we saw yesterday, the design of [Print] is
not “round trip”, in the sense that it does not represent a coercion at
the head of a printed term the same way as internally.  If I chose to
copy-paste the display of [Print], it would be to put it in my script in
a context where sufficient information is there to have the external
coercion unnamed, too.  Wouldn't it make sense that [Print] prints the
term together with enough type information?

> I think you can easily refine the patch by turning QuoteCoercion into
> a polymorphic identity function so that "x''" is convertible to "x" (I
> guess you can just generate an extra GHole in "extern" for the type
> argument of the identity function).

Easy or not (for me), I will try this.

> I also think this constant should not be in Logic.v but in another
> file of the prelude. In particular there is one called Notations
> (sorry, I did not recall its existence this morning).

Fair enough, I'll do that too.

Frédéric

**Comment by fchyzak** [comment]
I discussed the proposed approach with Hugo, who was worried it might be not general enough.  It is indeed possible to think more generally that Coq could/should produce terms augmented with identities decorated with information representing how a given subterm was obtained by refinement/elaboration.  So, instead of only the QuotedCoercion constant, which I propose in this branch and which would soon be imitated for other markings, it would be possible to have something along the following lines:

Inductive annotation (T : Type) (t : T) :=
| Coercion (T' : Type) (f : T' -> T) (x : T') (_ : f x = t) : annotation T t
(*
| ImplicitArgs ... : annotation T t
| Notation ... : annotation T t
| TypeClass ... : annotation T t
| ...
*)
.

Definition AnnotatedNode (T : Type) (t : T) (a : annotation T t) (n : nat) :=
  t.

Notation "“ x ? n ”" := (AnnotatedNode _ _ (Coercion _ _ _ _ x _) n) (at level 0,
    format "“ x  ?  n ”").

Check AnnotatedNode C (g (AnnotatedNode B (f a)
    (Coercion B (f a) A f a eq_refl) 42)) (Coercion C (g (f a)) B g
      (AnnotatedNode B (f a)
        (Coercion B (f a) A f a eq_refl) 42) eq_refl) 123.

which displays:

““a ? 42” ? 123”
     : C

After that, in the augmented display mode, the user could ask for expansion of a given node only.

Discussing with Enrico, it seems that it would be best to have paths from the top of the term to the annotated subterms, rather than nat identifiers (we want stability of the "numbering").  Also, it could be sufficient to mark only a few levels of the term, and let the user navigate into lower levels step by step.

**Comment by fchyzak** [comment]
Hi,

Here are a few conclusions about my experiment at the Coq Coding Sprint in proposing different display options for coercions.  Summarizing:
- the prototype in the pull request #72 is not ready for any merge;
- the current implementation takes place at externalization, after detyping; to realize all of the goals listed below, some work would have to be done at detyping as well, so as to forget less information at that early point;
- the implementation approach I followed makes the standard library rely on new constants and notations triggered by those constants; this is used at display time only, with not computational consequence; I view this as a plain, genuine hack, and it has been frowned upon by others; I understand the point of well separating the library and the naked coqtop, and this suggests I should move my work into a plugin;
- making a plugin for changing the externalization behavior would require a number of hooks and exposing a number of functions (I give a tentative list below); in order to work further in this direction, I would need the developer team to commit on what hooks and functions they agree to provide to plugin developers, and to document them.

My original goal was to propose a mode making one able to observe the presence (and location) of coercions in terms and goals without necessarily displaying all coercions names.  That is, for a term [f x] with introduced coercion [f], besides the display [x] (no coercion printed, the default) and [f x] (coercions printed), I wanted a mode of 'quoted coercions' that display [“x”].  In case of iterated coercions, a question is whether there should appear several pairs or a single pair of quotes; I chose to propose both modes ('nested' and 'collapsed').  I had initially no idea of the structure of the Coq sources, and I also planned to have a mode with display [“x : T”] to display the target type of the coercion, that is, assuming [f : S -> T].  Discussions during the week led to observing that a need shared by several people would be to enable/disable alternative displays on a per-subterm basis, rather than applying the alternative display to all coercions of a certain kind (all of them; all occurrences of [f]; etc).  A possible interface would be to have an integer [<n>] in a display like [“x, id = <n>”], so that further interaction could ask for more information/a change of the display of the node with id [<n>].  (This proposed interface is for tty-based interaction; whether/how id's would be hidden by a GUI is another story.)

The prototype implements:
- the nested mode of quoted coercions,
- the data structure that would be used for the collapsed mode, but not this display itself yet,
- a mock-up for the type-annotated quoted coercions, which appear in the form [“x : _”] (the wanted type is not available without a larger implementation effort, which requires design decisions first),
- nothing yet for the id-annotated mode.

I would be willing to continue on this project, but to do so, I would need the following hooks/additions of exported ocaml val's:
- two hooks into remove_coercions in intern/constrextern.ml, one to overload the decision to process coercions, one to overload the action; in fact, each mode of coercion printing would have its implementation of the pair of hooks, so alternatively, one could consider a more complete mechanism to register pairs (condition, action) to be run in order, with the possibility to register new pairs before and after the default one,
- I expect to need similar hooks into the detyping phase, in order to add code to keep track of the target types of coercions; this hints to the need for a common mechanism for hook declaration in the various layers of printing,
- a hook at the entry point of externalization, in order to reset a counter for subterm id's; I expect this entry point to be extern_constr in intern/constrextern.mli, but what about the other extern_* functions?
- the machinery of boolean options like [Set Printing Coercions] does not scale: for my situation, I have counted 6 modes of coercion printing, and proposing several booleans leads to combinations with unclear wanted behavior; instead, the prototype introduces a [Set Printing Coercions Mode "<mode>"]; in a plugin reimplementation, a few modes would be proposed by vanilla coqtop and be augmented by the plugin; this creates a need to provide new functions to plugin developers to make this possible,
- a string_items (to be implemented) similar to the existing bool_items in (ide/coq.ml).

Of course I could greedily hack hooks and exports everywhere I see my need, but in order to obtain a plugin that could be maintained, a thinking should be supervised by the developers' team.

Frédéric

**Comment by gares** [comment]
Chrystal clear analysis, really!

I think we should seriously discuss (among the devs) about hooks, that is not only the show stopper for your patch to become a plugin, but for many other potential contributions.  Not sure this pull request is the right place, but 3 out of the 5 points above are really about that.

Some pieces of code are already "replaceable" by the user (e.g. you can already plug your own "evarconv" algorithm).  This is in general unsatisfactory, because you need to re-implement the full algorithm.  If you want to piggy back on the standard one, then there is no way to "interrupt" it and go back to yours.  In some sense what I think most users would like is to be able to use the existing code as we use the various iterators on terms (that I find a very nice API, e.g fold_constr_with_binders): you only specify your cases of interest, and let the iterator do all the boring work.

E.g. I guess Frederic would like his code to be called at each "application" node (both in detyping and extern).  His code would check if the head is a coercion.  If so, it would do something special, or else it would let the "iterator" run on the subterms and eventually call back his code again.  Having to recode the whole detyping/extern code in the plugin, or sneaking-in "ad-hoc" callbacks in the code of Coq seem not the elegant/scalable solution to me.

I'm hand waving here, but I'd like the discussion to begin (maybe on coqdev).  Do you think what I propose would be doable (and reasonably efficient) for a good part of the recursive-on-terms algorithms?

**Comment by gasche** [comment]
In the OCaml community, a standard ("visitor") pattern is to expose open-recursive `map` and `fold` to help people economically implement their own traversals. There are examples of this in the compiler-provided library exposed to users to preprocess OCaml abstract syntax trees, [ast_mapper.mli](https://github.com/ocaml/ocaml/blob/trunk/parsing/ast_mapper.mli#L50-L104), using records and explicit open recursion (see this [usage example](http://whitequark.org/blog/2014/04/16/a-guide-to-extension-points-in-ocaml/)), and in the library printing said syntax trees to strings (letting others maybe tweak the pretty-printing) [in object-oriented style](https://github.com/ocaml/ocaml/blob/trunk/parsing/pprintast.mli#L14-L133).

**Comment by gares** [comment]
Thanks!

Any idea how it compares performance-wise with:
  https://github.com/coq/coq/blob/v8.5/pretyping/termops.mli#L87
usage example:
  https://github.com/coq/coq/blob/v8.5/toplevel/assumptions.ml#L146

Both API (the ast_mapper one and the one in Coq) look equally good to me.  The one of Coq pays the cost of pattern matching twice.  Is ocamlc happy with the "indirect calls" / dispatching ast_mapper does?

I could just benchmark, but I'm on a deadline ;-)

**Comment by maximedenes** [comment]
test build

**Comment by coqdev** [comment]
Stop merci                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: Maxime DénèsEnvoyé: lundi 6 juillet 2015 17:42À: coq/coqRépondre à: coq/coqObjet: Re: [coqdev] [coq] Quote coercions (#72)test build

—Reply to this email directly or view it on GitHub.

**Comment by maximedenes** [comment]
test build

**Comment by gares** [comment]
Closing this PR.  The UI side of ITP is moving toward communication protocols able to work with rich(er) data (eg. structured goal representation).  Hopefully the need expressed by this PR will be implemented on top of that.

**Pull request closed without merging**
