### PR TITLE
Make coqbot print failing bench job info

### LINKED ISSUE #243: bench report should list failed jobs

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close https://github.com/coq/bot/issues/243

### CODE REVIEW

**Comment by SkySkimmer** [comment]
cf https://github.com/coq/bot/pull/254

**Comment by SkySkimmer** [comment]
@coqbot run light ci

**Comment by ppedrot** [comment]
Is this ready?

**Comment by SkySkimmer** [comment]
Yes

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
