### PR TITLE
[docker] update elpi to 1.3.1

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
I've still to prepare the overlay (I've a elpi1.3 branch but not rebased on master).

If I push another commit here, do I have to SKIP_DOCKER=false again?

**Comment by SkySkimmer** [comment]
>If I push another commit here, do I have to SKIP_DOCKER=false again?

If the dockerfile stays the same you can leave skip_docker alone.

**Comment by ejgallego** [comment]
Indeed `SKIP_DOCKER` is tied to `CACHEKEY`.

**Comment by gares** [comment]
please merge

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
