### PR TITLE
add binary output notation test

### PR DESCRIPTION
**Pull request by andres-erbsen**
This test documents the current behavior wrt non-text characters in printing notations. `0x1a` that does not work on Windows is excluded. A similar test with all 256 bytes has been a part of bedrock2 for more than a year, but we are removing it now in favor of a Ltac2-only implementation.

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
FTR the test-suite currently doesn't run on Windows.

**Comment by andres-erbsen** [comment]
Does this mean that the tests are expected to work only on Linux, or that their behavior on Windows should be tested manually before merging?

**Comment by Alizter** [comment]
Ideally in the future, the test-suite will also run on Windows. There are some technical limitations to achieving this ranging from some of tests being written in bash to the relatively new support for OCaml on Windows. For the current CI, it doesn't matter if a test doesn't run on Windows, but on the other hand its good to know that it does.

>Does this mean that the tests are expected to work only on Linux, or that their behavior on Windows should be tested manually before merging?

For this PR, I'm fine with merging the test as is. And when we finally start running the test-suite on Windows, we can always refer back to this PR if something doesn't work.

**Comment by andres-erbsen** [comment]
Okay. FWIW, I'm not whether running this on Windows will get LF->CRLF conversion applied or not.

**Comment by Alizter** [comment]
@andres-erbsen Let's worry about that when we actually run the test-suite on Windows then.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
