### PR TITLE
Change version number to 8.8.0.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
This is a very particular PR and as the RM I think you should self-merge.

**Comment by maximedenes** [comment]
Yep. I can even do the same for the Sphinx clean-ups, for the sake of the release, but if you're not too far from a merge button, feel free to do it :)

**Comment by Zimmi48** [comment]
> I think you should self-merge

Am I stupid? Of course, this is the rule for PRs on v8.8 anyways.

However the addition to the CHANGES file should also be forward-ported to master.

**Comment by Zimmi48** [comment]
I am still on my phone ;-)

**Comment by maximedenes** [comment]
> However the addition to the CHANGES file should also be forward-ported to master.

I removed the `CHANGES` addition and made a separate PR for `master` after I realized that.

**Pull request merged**
