### PR TITLE
Ocaml extraction, avoid double call to pp_module_type

### PR DESCRIPTION
**Pull request by psteckler**
This code change comes from P. Letouzey's patch for 8.4pl6, which fixes Bug 5310.

The affected section of code appears in 8.4, 8.5 and 8.6, and so could be merged into all those branches.

### CODE REVIEW

**Comment by ejgallego** [comment]
Hi @psteckler I think you want to do some squashing of commits here, the log looks a bit strange.

**Comment by ejgallego** [comment]
By the way, if this is a fix for 8.4 I think the accepted policy is to get it fixed in 8.4, and merged back into 8.5, 8.6 and trunk.

**Comment by psteckler** [comment]
I get those commits in the log every time I sync my fork. Any way to avoid that?

**Comment by ejgallego** [comment]
Also, it would be good to have in the commit message a brief explanation of what the patch actually does.

**Comment by ejgallego** [comment]
> I get those commits in the log every time I sync my fork. Any way to avoid that?

Do a rebase or merge with rebase.

**Comment by psteckler** [comment]
The commit message states the important thing that the patch does, avoiding that double call. More than that, you need to consult the diffs.

**Comment by maximedenes** [comment]
Hi Paul, thanks for the PR! Would it be possible to write a short explanation (in the commit message) why this patch is correct despite the side effects? It was not clear to us when we discussed it in our last call. I thought the two calls had been introduced on purpose by Pierre.

**Comment by maximedenes** [comment]
Actually, looking at the code more closely, I see that it prints `module type of struct ...` so I can get an idea of why it is correct. Maybe what is really missing is a short comment in the code saying what the line does.

**Comment by psteckler** [comment]
Pierre Letouzey, who wrote that code originally, as well as the patch in this PR, tells me he can't now recall the purpose of that double call. With the two calls, you get an exponential time blowup.

The new code uses the `module type of` construct to get a module type, instead of using the result of the second call to `pp_module_type`.

With the Bedrock example given in Bug 5310, the output with 8.4pl6 after applying this patch is identical, and takes much less time. That suggests that an exception is raised somewhere, because we don't see the changed syntax in the output.

**Comment by psteckler** [comment]
I added a comment, see if that's helpful.

**Comment by psteckler** [comment]
If needed, I can make the change in the 8.4 branch instead.

**Comment by gares** [comment]
I don't get why the code does `module type of struct include Foo end` instead of `module type of Foo`.
Which is the difference?

**Comment by psteckler** [comment]
@gares I think you can just use the module name, instead of that include stuff, in fact.

**Comment by psteckler** [comment]
It looks like Pierre has already committed his fix, so this PR is unneeded.

**Comment by letouzey** [comment]
Indeed, thanks Paul for the effort, but I've already propagated this fix myself.

@gares: the difference between `module type of Foo` and `module type of struct include Foo end` is *strengthening* : the second form will contain type equalities such as `type t = M.t = T1 | T2 | ...` instead of just type redefinitions like `type t = T1 | T2 | ...` (which will hence be incompatible with `M.t`). See also the [OCaml doc](http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec233). In the precise situation here (module aliasing), that's definitively the second form we want. So my earlier code was both slow *and* slightly incorrect (but nobody noticed this really really rare incorrectness).

Note also that when the extraction will target OCaml 4.02, we'll benefit from better [module alias]( http://caml.inria.fr/pub/docs/manual-ocaml/extn.html#sec235), and something like `module Bar : module type of struct include Foo end` will be able to be shortened into `module Bar = Foo` (yes, even in the signature). But for now I prefer to stay rather conservative over the OCaml version required to compile extracted code (this `module type of` dates from 3.12).

Best
Pierre

**Comment by ejgallego** [comment]
The fix seems to have been committed as separate commits in each branch.

@ppedrot , won't this break the merging flow [8.5 -> 8.6 -> 8.7] ? 

AFAICT, git won't know that the commits are related

**Comment by ppedrot** [comment]
This should be OK, the patches are the same and git can make sense of this kind of situations.

**Comment by ejgallego** [comment]
@ppedrot , do you mean that git will remove the extra patch, or do we end up with two copies of the patch after merging? I'll try.

**Comment by ejgallego** [comment]
Indeed both patches remain in the tree, IMHO this makes history a bit convoluted as indeed depending on how you merge.

I think it is not a problem but this particular patch, but maybe you folks would like to avoid such patch duplication in the future.

**Pull request closed without merging**
