### PR TITLE
[travis] Backport from trunk: VST

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Is there a reason for the backporting PRs? Instead of targeting 8.6 first, then merging in trunk like we do for bugfixes?

**Comment by ejgallego** [comment]
> Is there a reason for the backporting PRs? Instead of targeting 8.6 first, then merging in trunk like we do for bugfixes?

Yes, `master` is the main development platform for these fixes, and they should be first tested there. A few ones may be suitable for 8.6, hence backported.

**Comment by maximedenes** [comment]
@ejgallego hum can you change the base branch to v8.6? It looks like you are backporting from trunk to trunk :)

**Comment by ejgallego** [comment]
Ups, done.

**Pull request merged**
