### PR TITLE
Fixing the "beautifier" and checking the parsing-printing reversibility (#2)

### PR DESCRIPTION
**Pull request by herbelin**
All's well that ends well, the 8.6 beta1 is out, and I believe this is a relief for many of us.

I'm here reporting on work in progress about the beautification: recompilation the standard library after translation now works without too serious hacks.

A first bunch of commits are fixes to the printers (many of them are as well for v8.5 as for v8.6) [8 commits].

A second bunch of commits are improvements in the formatting. This are hence enhancements more than bugs [7 commits].

A third bunch of commits are deeper changes to the printer system. So, opinions are expected, especially from @ppedrot, knowing if it is compatible with the other pending objectives around [6 commits].

A commit is adding the "name:(...)" capsule around generic arguments, so that to improve the reparsability of the output of "Print Ltac".

A commit is adding support for a precedence in generic printers. It is not so nice because only tactic uses precedences in practice, but the precedences are now everywhere. Maybe a better solution could be found later on.

A commit is fixing the printing of "()", i.e. unit, in ltac, while it becomes clear what is the future of "()" (i.e. hard-wired or not).

A commit is adding support for printing vernac extensions as they were defined, including the list separator when relevant (as in `ne_constr_list_sep(x,",")`).

The last bunch of commits is about layout changes which are at the border of being hacks and which need more thought [3 + -1 commits].

A lot remains to be done to improve further the layout, but that's going in the good direction. A next step includes adding bullets automatically. One may also think at producing automatically the
"Proof using" clause. Contact me if you are interested in contributing.

### CODE REVIEW

**Comment by herbelin** [comment]
@maximedenes: no objection to push the 8 first bug fixes of this list (up to 7cd0ca9e0550, in commit order, not in date order)? If no, would you mind if I let it to you to merge them?

**Comment by maximedenes** [comment]
@herbelin The commits you mention seem to be straightforward printer fixes, so no objection against merging them. I'll do it, if you don't mind, to avoid concurrent merges since there will be quite a few today.

**Comment by maximedenes** [comment]
@herbelin Ok, I realize only now that I can't find an order that gives me the commit you refer to as the 8th. Can you give me an explicit list of commits you want to get merged?

**Comment by herbelin** [comment]
7cd0ca9e0550545d55287f58e2444827a7ac5dcc
d6b8eb872a98c43a0c4de4e964fa25b60fe3e6dd
ee2d5325c14c6da265b72ce424fc34c773169a72
675adbe695cc2ca612344a22f80a937c062ed630
9729c6b975c9e4829cbd35381597c4dec092d165
1d0074da4959e6f2623db14ebf1d90c858753dd3
a0a2a030586a46fce1c317ad2ccc4b39727ec5d2
fb13595d83943ca3f6663ad4c4e1f3281b7570d8
bcbbb1ff783d0345d2be5554140559319fc179ed

which are nine actually.

**Comment by maximedenes** [comment]
Your `fb13595d` conflicts in v8.6 with a similar fix by Guillaume. Can you confirm your fix is the one I should merge? (with `keyword` and `surround`)

**Comment by herbelin** [comment]
I don't know... Apparently "constr:" is a keyword, so "ltac:" should be also by consistency. Between surround and explicit parentheses it does not matter per se, but surround seems to be in general used in the file, so maybe preferring surround is indeed more consistent with the rest of the file, so, I guess Guillaume will do the same analysis, so, let's use my patch.

**Comment by herbelin** [comment]
About your previous comment: If we do useless job (with e.g. Buffer) and can avoid doing it when not in beautifying more, we should indeed avoid it. So if you find such thing, don't hesitate to improve.

**Comment by maximedenes** [comment]
I think we do already, and the commit adds more. But I'm lacking time to fix it, so I'll merge hoping that it is negligible.

**Comment by maximedenes** [comment]
@herbelin Ok, I merged the commits you asked. I'm closing this PR, please reopen a new one (after rebasing) if you want the integration of the other commits to be discussed, it will be easier to distinguish from what has already been implemented.

**Pull request closed without merging**
