### PR TITLE
Use Typing.type_of less in tactics.ml

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@SkySkimmer how are you sure this is correct and there isn't some fancy case where we really pass ill-typed terms to these tactics?

**Comment by SkySkimmer** [comment]
I looked at where the arguments came from and where I was dubious I left it alone

**Review by ppedrot — APPROVED** [review]
Good enough for me.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
