### PR TITLE
Print sub-error in ReplacementIllTyped

### LINKED ISSUE #8048: "Replacement would lead to an ill-typed term." is not a good way for "change" to report a universe inconsistency
#### Version

8.8.0

#### Description of the problem

```coq
Goal nat = nat.
  pose (nat : Type) as n.
  change nat with n. (* Error: Replacement would lead to an ill-typed term. *)
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #8048

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Nice! Maybe can you add an example or two in passing?

**Comment by SkySkimmer** [comment]
Sure, example added

**Comment by herbelin** [comment]
Let's merge tonight if no comments by then.

**Review by Alizter — APPROVED** [review]

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
