### PR TITLE
Fix #18657: "Include" objects were not always taken into account in Search

### LINKED ISSUE #18657: `Search` in a module does not show lemmas obtained when `Includ`ing a module type
#### Description of the problem

As the title says, there is an issue when `Searching` inside a module:

The first example works as expected:
```coq
Module First.
  Definition bar := 1.
  Lemma bar_1 : bar = 1. Proof. reflexivity. Qed.
End First.

Module Import Second.
  Include First.
  Search bar. (*First.bar_1: First.bar = 1*)
  Search "bar".
  (*
First.bar: nat
First.bar_1: First.bar = 1
  *)
  Lemma one_bar : 1 = bar. Proof. rewrite bar_1. reflexivity. Qed.
End Second.
```

Now with a module type instead:
```coq
(* Now with a module type *)
Module Type B.
  Definition bar := 1.
  Lemma bar_1 : bar = 1. Proof. reflexivity. Qed.
End B.

Module A.
  Include B.
  Search bar. (* nothing *)
  Lemma one_bar : 1 = bar. Proof. rewrite bar_1; reflexivity. Qed.
  Search bar. (* only one_bar *)
End A.
```
This makes working in long modules which include many module types (like `PeanoNat`) really tedious.

In addition, the same issue arises with functors:
```coq
Module Type HasFoo.
  Parameter t : Type.
  Parameter foo : t.
End HasFoo.

Module MakeBaz (Import M : HasFoo).
  Definition baz := fun (_ : unit) => foo.
  Lemma baz_foo : baz tt = foo. Proof. reflexivity. Qed.
End MakeBaz.

Module Import Baz <: HasFoo.
  Definition t := nat.
  Definition foo := 42.
  Include MakeBaz.
  Search baz. (* nothing *)
  Search "baz". (* nothing *)
  Lemma foo_bas : foo = baz tt. Proof. rewrite baz_foo. reflexivity. Qed.
End Baz.
```

#### Coq Version

8.12, 8.16, 8.18, 8.19 and current master (8.20+alpha)

### PR DESCRIPTION
**Pull request by herbelin**
The fix was simple.

Note that this may imply duplication of results: in the case of a module, we have a result both with the original name and with the included names. But this is a phenomenon which is not only about `Include`. E.g., `Module M := N` has similar consequences.

Fixes / closes #18657

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by Villetaneuse** [comment]
That was quick! Thank you very much. The duplication is unfortunate but this can be treated at another time. I'm not even sure there is a better solution; after all the lemmas are there with two names so this behaviour is expected.

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
> The duplication is unfortunate but this can be treated at another time.

Indeed, nothing specific to the current PR. Still, this duplication remains one of the painful issues of `Search` IMHO. I guess, outputing only the shortest name would be the best solution in case of duplication.

**Comment by herbelin** [comment]
> I guess, outputing only the shortest name would be the best solution in case of duplication.

Probably, the simplest would be to ensure that the `Search` is done starting from the most recent declarations and that whenever an `Include N` (for `N` a module) or `Module M:=N` is encountered, `N` is added to the list of modules to later skip.

**Comment by proux01** [comment]
There are also `Import` and `Export`. Maybe a deduplication mechanism would be enough as a short term solution.

**Comment by herbelin** [comment]
If I'm not mistaken, the impact of `Import` and `Export` on logical declarations is just about how they are made visible in the nametab. `Search` sees the contents of non-imported modules anyway.

Oh, maybe a simple way is to display only the names whose user name is the same as the canonical name! That could be tried.

**Comment by herbelin** [comment]
Hum, if we do that, printing only the original "canonical" constants, then this means printing the oldest one, which is probably not the intended, shortly-named, one.

On the other side, if we hide re-aliased module, that's not fully satisfactory either. If we have `Module M := N. Module P := N.` or `Module M := N. Module P := M`, we want to give names in `P` but skip `N` and `M`. But that also seems more work.

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
