### PR TITLE
[lib] [future] Small cleanup of ununsed functions.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by gares — CHANGES_REQUESTED** [review]
I'm OK removing `sink` and `from_here`, but I still see the purpose of `customize_*` so please leave them there.

**Comment by ejgallego** [comment]
Done.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
This is material for a maintainer of `lib/` which I'm not...

**Comment by ppedrot** [comment]
I am supposed to be a secondary maintainer, let me assign and merge.

**Comment by ppedrot** [comment]
FTR, this code is likely to disappear as it is soonish, after CEP#40 is finally implemented. In particular, in direct style the hooks don't really make sense anymore, it is the responsibility of the caller to handle those cases.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
