### PR TITLE
Generalize pretyping type constraints to handle arities with inferred sort

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not yet useful but should be useful for https://github.com/coq/coq/pull/19228

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
This runs into essentially https://github.com/coq/coq/issues/19246 such that
~~~coq
Check fun x => True -> match x with true => True | false => False end.
~~~
generates `match x return Set` instead of `match x return Prop` (and the same issue with `if x then True else False`).

Being on the right of the arrow means we have expected type `is_type` ie `OfArity []`.
`match` (and `if`) compilation need a term as expected type, so we generate a fresh qsort and use that as the type constraint, then run into the issue.

Possible fixes (inclusive OR list):
1. generalize match and if compilation to understand OfArity type constraints (not sure how much work this is)
2. fix https://github.com/coq/coq/issues/19246, then maybe OfArity can be strictly an optimization to avoid generating extra univ variables
3. revert the pretype_type change such that on non-holes we still pretype with no tycon and later coerce to sort instead of pretyping with is_type tycon, this means the only user of OfArity would be template poly.
Since template poly in master uses the global default universe in the tycon (so eg `Check fun x:bool => prod True (match x with true => True | false => False end).` produces `match x return Type@{prod.u1}`) it is ok even if not ideal to get a qvar when the template argument is a `match` even if the qvar gets non-optimally collapsed.
It would cause a bidi loss when going through ltac2 $preterm (eg `prod _ $preterm:x`) (because ltac2 $preterm calls pretyping through the standard entry point, which calls pretype_type when the tycon is `is_type`) but that should be quite rare so probably we don't care.

**Comment by SkySkimmer** [comment]
Testing with solution 3

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by SkySkimmer** [comment]
@JasonGross weird minimization, the error happens on
~~~
intros Hidx; eassert (Some _ = Some _) as HS; [ | injection HS; intros Hs; apply Hs ].
~~~
but it kept the tactics and Qed after it

**Comment by SkySkimmer** [comment]
The error is like 
~~~coq
Set Universe Polymorphism.

Inductive opt@{s|u|} (A:Type@{s|u}) : Type@{u} := some (_:A).
Arguments some {_} _.

(* NB can't say "x = y" because eq is not sort poly *)
Lemma foo@{s|u|+} (A:Type@{s|u}) (x y:A) : some x = some y -> True.
Proof.
  intros H.
  injection H.
  (* Error: No information can be deduced from this equality and the
     injectivity of constructors. This may be because the terms are
     convertible, or due to pattern matching restrictions in the sort
     Prop. You can try to use option Set Keep Proof Equalities. *)
~~~
but with template poly instead of sort poly

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
It failed to fetch menhir for some reason, let's retry
@coqbot bench

**Comment by JasonGross** [comment]
> @JasonGross weird minimization, the error happens on
> 
> ```
> intros Hidx; eassert (Some _ = Some _) as HS; [ | injection HS; intros Hs; apply Hs ].
> ```
> 
> but it kept the tactics and Qed after it

Thanks for flagging this, there was an issue with how the minimizer was counting lines.  Should be fixed by https://github.com/JasonGross/coq-tools/pull/218.

**Comment by SkySkimmer** [comment]
@coqbot bench

**Pull request closed without merging**
