### PR TITLE
[travis] Remove some more jobs from PR testing now that they are on Gitlab.

### PR DESCRIPTION
**Pull request by ejgallego**
This is a "test" PR, but could be merged if we like it.

### CODE REVIEW

**Comment by ejgallego** [comment]
Rebased and updated to latest setup, only lint and osx jobs are remaining.

Build on branch [thus full] is at:
https://travis-ci.org/ejgallego/coq/builds/376133831

I would suggest we also remove some jobs from the full build, in particular we could only do one test suite and validate, but that can happen in a separate PR I guess.

**Comment by ejgallego** [comment]
Théo I agree with the plan and indeed it's time we close the documentation issue. However this PR is IMHO a step towards that, I think it is good to remove the testing in gradual steps.

Fiat crypto is readded back in the depending PR if I am not mistaken. It works fine AFAICT

**Comment by Zimmi48** [comment]
> Fiat crypto is readded back in the depending PR if I am not mistaken. It works fine AFAICT

OK, I thought @SkySkimmer was doubting this. Does it work fine even with shared runners?

**Comment by ejgallego** [comment]
> OK, I thought @SkySkimmer was doubting this. Does it work fine even with shared runners?

So far I haven't found a problem with fiat-crypto and given the specs of the shared runners I would be surprised to see one. The problem in the past was likely that `fiat-crypto` itself was way more demanding or that the runners had lower specs.

**Comment by Zimmi48** [comment]
OK great to hear!

**Comment by Zimmi48** [comment]
So given the pretty terrible situation of Travis tests currently (lots of problems installing dependencies) and given how easy it is to setup GitLab CI support for one's fork, I would say it is time to remove these jobs from Travis for real (both on PRs and on branches). I'm going to do the update to the CI doc. The present PR should also include a removal of the Travis badge...

**Comment by Zimmi48** [comment]
Cf. #7482.

**Comment by ejgallego** [comment]
IMHO it is still too early to move from Travis, reliability problems are not exclusive of it [gitlab has it's own bunch of problems]. In particular I'd like to see #6919 closed first.

**Comment by Zimmi48** [comment]
At least, move these jobs that you keep but are redundant to the allow failure category. I don't want to have Travis badge in the README red because yet another time out or failed to fetch issue. The color of the Travis badge should only reflect the status of the macOS job.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
OK I'm not going to wait for gitlab's windows.

**Pull request merged**
