### PR TITLE
Generalizing the various evar_map printers in Termops over an environment

### PR DESCRIPTION
**Pull request by herbelin**
This is a small incremental step towards limiting calls to the global environment.

Don't hesitate to discuss design choices. Better now than latter.

**Kind:** architecture

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
Something that was not clear to me in this file if the printers were supposed to be "debug", that is to say, to print the raw terms themselves or not.

**Comment by herbelin** [comment]
> Something that was not clear to me in this file if the printers were supposed to be "debug"

That's a good question. I can't tell for all printers, but the `evar_map` printer is not very pretty and it was mainly intended for debugging. In practice, it is however used for the errors messages of `rewrite.ml` and also in `Himsg.explain_unsatisfiable_constraints`.

> that is to say, to print the raw terms themselves or not.

This is a different question I think. When I debug, I prefer in general to have "nice" terms, and I get nice terms with the tracer for instance. In ocamldebug, the printer of the debugger does not have access to the `Global.env` anyway (i.e. it runs in an empty `Global.env`), so it does not make a difference whether we pass it an `env` which in practice shall be empty, or if it takes dynamically a `Global.env` which shall also be empty.

In any case, it is not clear that this env-passing in evar-things printers is important. But this costs nothing to make them functional either.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@herbelin Looks like elpi needs an overlay...

**Comment by herbelin** [comment]
Overlay at LPCIC/coq-elpi#36.

I'm afraid there's going to be quite a lot of overlays to come on the `Global.env()` topic...

**Pull request merged**
