### PR TITLE
dev/build/windows/makecoq_mingw.sh: install camlp5's META file

### PR DESCRIPTION
**Pull request by gares**
In this way camlp5 is installed "the same way" by opam or this script

### CODE REVIEW

**Comment by maximedenes** [comment]
This PR can be tested automatically once #1022 is merged.

**Comment by gares** [comment]
rebased to take advantage of #1022, let's see what appveyor has to tell us

**Comment by gares** [comment]
travis *and* appveyor were OK, I've removed the spurious commit with the extra print

**Comment by Zimmi48** [comment]
> travis and appveyor were OK

Good to know, since AppVeyor is currently broken. So should be ready to merge, right?

**Comment by gares** [comment]
Yes it was all green.

Today the failure is about NAN begin printed as -oo or something like that... so I guess it is unrelated.

**Pull request merged**
