### PR TITLE
[toplevel] Refine start of interactive mode conditions.

### LINKED ISSUE #6691: `make vio2vo` does not do anything
#### Version

Git master

#### Operating system
Linux

#### Description of the problem

* `git clone https://gitlab.mpi-sws.org/robbertkrebbers/coq-stdpp.git`
* `make quick -j8`
* `make vio2vo J=8`

The last command returns immediately and does nothing: `ls theories` shows no `.vo` files.
I reproduced this in a smaller project that doesn't mess with `coq_makefile`'s output.

With Coq 8.7, everything still works as expected.

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #6691. We also tweak the vio auxiliary function.

### CODE REVIEW

**Comment by ejgallego** [comment]
Looks like the fiat-crypto failure is unrelated?

**Comment by RalfJung** [comment]
Should this add a test for the vio2vo target to make sure this doesn't regress again?

**Comment by maximedenes** [comment]
I'll merge it now, so that we don't delay the fix, but a test case is indeed welcome!

**Comment by RalfJung** [comment]
I will add a testcase as part of my `quick2vo` PR.

**Comment by ejgallego** [comment]
Thanks @RalfJung , indeed the test case is much needed, testing your examples I discovered some other subtle problems that later or sooner would have been bit us; some of them are fixed by the loadpath commit, some others still require investigation [such as what vio2vo is really doing with the summary]

**Comment by RalfJung** [comment]
@ejgallego I was just going to add a test that checks whether the .vo files exist. :)  Nothing fancy. I am not sure which subtle problems you talk about, but they seem unlikely to be caught by such a superficial test.

**Comment by ejgallego** [comment]
A more complete test should also check exit codes and vo validity. Indeed, I think that having two files such that:
- The first file, `A.v` is compiled with quick, then compiled to `.vo`.
- The second file imports `A`, uses a lemma, and Print Assumptions, and we check the output.

**Comment by RalfJung** [comment]
exit codes are propagated upwards from `make`, I assume.

**Comment by ejgallego** [comment]
> exit codes are propagated upwards from make, I assume.

No idea.

**Comment by RalfJung** [comment]
Eh, how else is failure reported?^^ Who would know this stuff better?

**Comment by Zimmi48** [comment]
The embryonic doc at https://github.com/coq/coq/tree/master/test-suite#coq-test-suite would certainly be worth improving.

**Pull request merged**
