### PR TITLE
Remove 8.14 deprecation

### PR DESCRIPTION
**Pull request by proux01**
Now that 8.15 is out, we could think about removing things deprecated in 8.14.

Overlays (should be merged before merging the current PR):

* coq-community/bignums#69 (merged)
* Flocq 3: https://gitlab.inria.fr/flocq/flocq/-/merge_requests/19 (merged)
* https://github.com/thery/coqprime/pull/45 (merged)
* https://github.com/math-comp/math-comp/pull/856 (merged)
* https://github.com/LPCIC/coq-elpi/pull/344 (merged)
* https://github.com/proux01/itauto (merged)
* https://github.com/MetaCoq/metacoq/pull/655 (merged)
* https://github.com/JasonGross/coq-scripts/pull/9 (merged)
* https://github.com/mit-plv/fiat/pull/70 (merged)
* https://github.com/mit-plv/fiat-crypto/pull/1159 (mered)
* https://github.com/mit-plv/rupicola/pull/51 (merged)
* https://github.com/mit-plv/fiat-crypto/pull/1162 (merged)
* https://github.com/mit-plv/fiat-crypto/pull/1168 (merged)

Fixes / closes #14637

### CODE REVIEW

**Comment by proux01** [comment]
@JasonGross I get a seemingly unrelated error on fiat-crypto:
```
File "./src/Bedrock/Specs/Field.v", line 138, characters 2-29:
Error:
Notation "fnspec! _ _ .. _ / _ .. _ ~> _ .. _ , { requires _ _ := _ ; ensures _ _ := _ }" is already defined
at level 200 with arguments constr at level 0, binder, binder, closed binder,
ident, ident, constr at level 200, ident, ident, constr at level 200
while it is now required to be at level 200 with arguments constr at level 0,
binder, binder, closed binder, name, name, constr at level 200, name, name,
constr at level 200.
```
does that ring a bell?

**Comment by proux01** [comment]
@JasonGross sorry for the noise, this wasn't unrelated at all, here is an overlay: https://github.com/mit-plv/rupicola/pull/51

**Comment by proux01** [comment]
So CI is finally green here, there are two overlays left to merge:
* https://github.com/LPCIC/coq-elpi/pull/344 @gares could you have a look (no hurry, but this is a trivial one)
* https://github.com/proux01/itauto/commit/40b66e957de9a7ca075133345cbc9af4f2eadb93 @fajb you can either pick that commit or give me rights on gitlab.inria if you want a proper merge request (my login there is proux), again this is a trivial one

**Comment by fajb** [comment]
>     * [proux01/itauto@40b66e9](https://github.com/proux01/itauto/commit/40b66e957de9a7ca075133345cbc9af4f2eadb93) @fajb you can either pick that commit 

I have  rebased against your branch. Thanks.

**Comment by proux01** [comment]
@fajb thank you

**Comment by proux01** [comment]
So, all overlays are now merged (thanks to everyone involved) and CI is green, this is looking for an assignee.

**Comment by SkySkimmer** [comment]
cc @herbelin

**Comment by proux01** [comment]
It seems to me, this should just be marked as closing #14637

**Comment by proux01** [comment]
Looks like we'll have to do it manually, it seems github can autoclose isssues but not PRs.

**Comment by proux01** [comment]
This is still looking for an assignee, maybe @Alizter this should be a relatively easy one now that all overlays are merged.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by proux01** [comment]
Thanks!

**Comment by Zimmi48** [comment]
Sorry for not having reviewed this PR earlier, but it is missing two very important things, that would have been reminded by the PR template if only it had been kept:

1. This PR should have had a changelog entry. You cannot silently remove or change the semantics of features, even if they were deprecated before! This is even more important for a PR that had a huge number of overlays, making it crystal clear that users will need guidance on how to make their code compatible.

2. This PR should also have updated the related documentation. In particular, see the notes at https://coq.github.io/doc/master/refman/user-extensions/syntax-extensions.html#predefined-entries and below https://coq.github.io/doc/master/refman/user-extensions/syntax-extensions.html#coq:warn.Use-of-%E2%80%98string%E2%80%99-Notation-is-deprecated-as-it-is-inconsistent-with-pattern-syntax.

I'm also a bit surprised that the decision was taken to proceed with the change of semantics for `ident` despite the hesitation of @herbelin in the related PR and without going through the initially planned fatal warning phase. But maybe this was actually the right move and we were too cautious in our previous plans. It seems in particular that making the warning fatal would have actually broken many more projects than just changing its semantics did (and the warning has been there for 3 versions, so it's not like users could have ignored it completely). I'm interested in hearing from @proux01 on his experience fixing the `name` / `ident`-related warnings and how common this issue was and how likely it is that the users will understand where the problem comes from when they are confronted to it. Depending on the answer, the changelog for this change of semantic should be displayed more or less prominently in the 8.16 release notes.

**Comment by proux01** [comment]
My bad, I'll do the changelog and doc update in a separate PR.
Regarding the easyness of porting, the error messages clearly indicate they are related to ident but may lead the user to think it is a priority issue. I should put an example of error in the changelog to help users.

**Comment by Zimmi48** [comment]
>I should put an example of error in the changelog to help users.

Yes, that would help a lot.

Thanks!

**Pull request merged**
