### PR TITLE
Avoid running interactive tests on Windows.

### PR DESCRIPTION
**Pull request by maximedenes**
This is a temporary workaround, until we fix the underlying issue which
makes coqtop hang on those tests.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
How about instead in the test suite Makefile have
``` make
INTERACTIVE := interactive
VSUBSYSTEMS := prerequisite success failure $(BUGS) output \
  output-modulo-time $(INTERACTIVE) micromega $(COMPLEXITY) modules stm \
  coqdoc
```
then in the appveyor script use `make -C test-suite INTERACTIVE=`?
This would be more resilient to changes in the list of targets in the test suite.

**Comment by maximedenes** [comment]
Yes, thanks.

For now it is only a quick test, I'm expecting AppVeyor to hang on other tests, since there is really nothing specific to those files (except that they contain almost nothing, so they are processed very quickly).

**Comment by Zimmi48** [comment]
Looks like it passed (did not hang on any other test). Would be worth to merge after taking Gaetan's comments into account given that this will (at the very least) reduce the number of spurious failures.

**Comment by Zimmi48** [comment]
After your change, this passed again (did not hang on any other test). I guess this is a candidate for urgent merging.

**Pull request merged**
