### PR TITLE
Ascii: add leb and ltb

### PR DESCRIPTION
**Pull request by liyishuai**
**Kind:** feature.

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by anton-trunov** [comment]
Hi @liyishuai! These functions look good to me. Could you re-run the CI jobs please? (I can't restart them for some reason)

**Comment by ppedrot** [comment]
@anton-trunov you should probably assign yourself and merge.

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
@coqbot merge now

**Comment by anton-trunov** [comment]
@ppedrot thanks for the ping :)

**Pull request merged**
