### PR TITLE
[warnings] Remove `set_current_loc` hack.

### LINKED ISSUE #6172: Problems with locations for a warning
#### Version

8.7

#### Operating system

Linux

#### Description of the problem

I use the following Coq script:

```
Structure S := { x : nat -> nat }.
Canonical Structure C := {| x y := y + 1 |}.
Lemma L : True. Proof. trivial. Qed.
```

In Coqide, asking for processing the whole buffer **at once** triggers a warning on the second line. However, for some reason, only the first four characters are underlined.

See also the followig proof general bug [https://github.com/psteckler/ProofGeneral/issues/95#issuecomment-344746709](url).

### PR DESCRIPTION
**Pull request by ejgallego**
Instead of the current hack that won't work as soon as we check some
part of the document asynchronously, we make the warning processor
recover a proper location if the warning doesn't have one attached.

This is what CoqIDE does [but it queries it's own document model].

EDIT by Théo: this happens to fix #6172.

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Thanks for the patch! And thanks for the explanations, I feel I understand better and better the interaction model.

A question by curiosity: What remains to be done for `Error` to be handled also by the `coqloop_feed`?

(Not directly related, but I found a CoqIDE problem when the warning is raised at parsing time, I'm going to submit an issue.)

**Comment by ejgallego** [comment]
> What remains to be done for Error to be handled also by the coqloop_feed?

Quite a lot unfortunately, see #5479 . I have a tree fixing this but it is complicated to push it cleanly while a the same time maintaining compatibility, I think I'll try to push #6171 before but that's not gonna be an easy task.

**Comment by Zimmi48** [comment]
This happens to fix #6172.
Is this a non-backportable fix (for instance because it depends on previous changes done in `master` only)?

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
well done

**Review by maximedenes — APPROVED** [review]
I haven't tested it, but the patch looks good to me.

**Comment by maximedenes** [comment]
Since this is about the warnings system, I can take care of the PR. I'll update the CODEOWNER to add myself as an owner of the warnings system.

**Pull request merged**
