### PR TITLE
Stop catching anomalies from conversion

### PR DESCRIPTION
**Pull request by SkySkimmer**
It seems unused now

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by JasonGross** [comment]
Seems like this made it worse, but still in ways not covered by the test-suite?  @coqbot ci minimize

**Comment by SkySkimmer** [comment]
Seems to work

**Comment by ppedrot** [comment]
I'm pretty sure you can still trigger it in weird corner-cases, because this is used by Retyping and most uses are very *lenient* (euphemism) when it comes to the expected invariants to be allowed to call it. This should be considered a bug in the client though, so I'm still supporting merging this.

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Retyping doesn't use conversion

**Comment by ppedrot** [comment]
Fair enough, but still, we sometimes convert stuff that has no reason to live in a common supertype.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Merging this soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
