### PR TITLE
Update the OCaml version in `default.nix` to 4.09.0

### PR DESCRIPTION
**Pull request by maximedenes**
It is more convenient to use recent versions of OCaml while developing
(better backtraces, etc).

Cc @Zimmi48

### CODE REVIEW

**Comment by maximedenes** [comment]
@Zimmi48 I get an error building the doc in the nix package:

```
Warning, treated as error:
the sphinxcontrib.bibtex extension is not safe for parallel reading
```

any what this is about?

**Review by Zimmi48 — APPROVED** [review]
Agreed!

**Comment by Zimmi48** [comment]
> @Zimmi48 I get an error building the doc in the nix package:
> 
> ```
> Warning, treated as error:
> the sphinxcontrib.bibtex extension is not safe for parallel reading
> ```
> 
> any idea what this is about?

It would seem that this extension has been updated in nixpkgs and is producing a new warning. I'll try to dig a bit further.

**Comment by Zimmi48** [comment]
It was indeed updated from 0.4.2 to 1.0.0 in https://github.com/NixOS/nixpkgs/pull/71893.

**Comment by maximedenes** [comment]
@Zimmi48 How can we disable parallel reading in sphinx, to avoid the warning?

**Comment by Zimmi48** [comment]
Your commit 9cc4c1d89fd9c2439f9f1017d2a49641f01a3ed7 isn't about the Nix job so seems irrelevant to this PR. I'll look into this and try to provide you with an answer soon.

**Comment by maximedenes** [comment]
> Your commit [9cc4c1d](https://github.com/coq/coq/commit/9cc4c1d89fd9c2439f9f1017d2a49641f01a3ed7) isn't about the Nix job so seems irrelevant to this PR. I'll look into this and try to provide you with an answer soon.

Right, I wanted to do a quick test but got confused.

**Comment by Zimmi48** [comment]
I don't know what we can do except changing `enableParallelBuilding = true;` to `enableParallelBuilding = not buildDoc;` for now. When Dune supports everything that we build in the Nix package, I'd like to switch to Dune and split the Nix package into several parts corresponding to the various packages that Dune defines. Then, we can disable parallel building only for the doc part.

**Comment by Zimmi48** [comment]
When building Coq with this update, I get a few such warnings:

```
File "kernel/nativevalues.ml", line 99, characters 15-26:
99 |       let () = Obj.set_tag ans accumulate_tag [@ocaml.alert "--deprecated"] in
                    ^^^^^^^^^^^
Alert deprecated: Stdlib.Obj.set_tag
Use with_tag instead.
```

Is this expected?

**Comment by ejgallego** [comment]
> Is this expected?

Yep, see the relevant bugs for 4.09 / 4.10 support.

**Comment by maximedenes** [comment]
@Zimmi48 I followed your suggestion. Let's see what it gives.

**Comment by maximedenes** [comment]
@Zimmi48 Still the same error, what did I do wrong?

**Comment by Zimmi48** [comment]
I don't understand. I would need to take time to debug this. Maybe @vbgl can confirm that my suggestion should work in principle. But even then, I'm not sure I fully understand how `Makefile.doc` works...

**Comment by maximedenes** [comment]
> don't know what we can do except changing `enableParallelBuilding = true;` to `enableParallelBuilding = not buildDoc;` for now

How are these flags related to Sphinx' parallel reading?

**Comment by maximedenes** [comment]
`Makefile.doc` was passing `-j 4` to Sphinx regardless of options passed to make. Should be now fixed, let's see.

**Review by Zimmi48 — APPROVED** [review]

**Pull request merged**
