### PR TITLE
[ssr] do not solve TC when generating have proof term (fix #16720)

### LINKED ISSUE #16720: Tactic failure with ssreflect when the goal is solvable by "apply _"
#### Description of the problem

See the following example.
```coq
From Coq.Classes Require Import DecidableClass.
From Coq Require Import ssreflect ssrfun ssrbool.

Goal True.
Proof.
  (* Works as expected. *)
  Fail Fail have P_iff : (forall n, n = 0 <-> 0 = n).
Abort.

Goal forall (x y : bool), Decidable (eq x y).
Proof.
  Fail Fail apply _.
  (* Fails with: "Error: Tactic failure: Incorrect number of goals (expected 0 tactics)." *)
  Fail have P_iff : (forall n, n = 0 <-> 0 = n).
Abort.
```

This was further minimized by @Janno, to obtain the following (he is also currently bisecting).
```coq
From Coq Require Import ssreflect.
Class Trivial := trivial {}.
#[local] Existing Instance trivial.
Goal Trivial.
  Succeed assert True.
  Fail have: True.
Abort.
```

#### Coq Version

This fails on version 8.16.0, but used to work correctly in 8.15.1.

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
Dear @coq/tactics-maintainers what I'm doing here is to, morally, call `Tactics.eapply` and deep down pass `~with_classes:false`.
I did to by inlining the 3 interesting lines, but I could also add the flag to to `Tactics.eapply`. I don't know if that would be of interest to others, if so just tell me and I'll rewrite the patch.

**Comment by ppedrot** [comment]
I think it would be better to add a flag to eapply, so that we don't duplicate the horrendous clenv code in ssr.

**Comment by gares** [comment]
@coqbot run full ci before I change everything

**Comment by gares** [comment]
done
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by gares** [comment]
I did just rebase and squash, the code is unchanged.

**Review by SkySkimmer — APPROVED** [review]

**Comment by gares** [comment]
@ppedrot maybe this can be backported if a .1 is in the making

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Backporting changes with affect mli files is not great. Maybe we can go for the original variant for the 8.16 backport.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
