### PR TITLE
Revert "Stop catching anomalies from conversion"

### PR DESCRIPTION
**Pull request by SkySkimmer**
This reverts commit 89b0356.

Properly fixing the bugs it created seems hard. Maybe if we get unifall to work we can stop catching anomalies again.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
NB: it would be tempting to catch anomalies only in conversion calls from unification.ml, but #17910 is getting the anomaly through evarconv called by unification.ml
<details><summary>backtrace</summary>

~~~
Error: Anomaly "ill-typed term: found a match on a partially applied constructor."
Please report at http://coq.inria.fr/bugs/.
Raised at Exninfo.iraise in file "clib/exninfo.ml", line 79, characters 4-11
Called from CClosure.get_branch in file "kernel/cClosure.ml", line 763, characters 13-50
Called from CClosure.knr in file "kernel/cClosure.ml", line 1325, characters 26-68
Called from CClosure.kni in file "kernel/cClosure.ml" (inlined), line 1392, characters 2-19
Called from CClosure.whd_stack in file "kernel/cClosure.ml", line 1578, characters 10-29
Called from Conversion.eqappr in file "kernel/conversion.ml", line 447, characters 19-84
Called from Conversion.eqappr in file "kernel/conversion.ml", line 528, characters 20-60
Called from CArray.fold_right2.fold in file "clib/cArray.ml", line 242, characters 11-40
Called from Conversion.eqappr in file "kernel/conversion.ml", line 432, characters 9-55
Called from Conversion.generic_conv in file "kernel/conversion.ml", line 937, characters 4-60
Called from Reductionops.infer_conv_gen in file "pretyping/reductionops.ml", line 1190, characters 10-87
Called from Evarconv.infer_conv_noticing_evars in file "pretyping/evarconv.ml", line 557, characters 8-70
Called from Evarconv.evar_conv_x in file "pretyping/evarconv.ml", line 574, characters 6-80
Called from Evarsolve.check_evar_instance_evi in file "pretyping/evarsolve.ml", line 906, characters 8-86
Called from Evarsolve.instantiate_evar in file "pretyping/evarsolve.ml", line 1579, characters 13-61
Called from Evarsolve.evar_define.(fun) in file "pretyping/evarsolve.ml", line 1815, characters 4-50
Called from Evarsolve.solve_simple_eqn in file "pretyping/evarsolve.ml", line 1888, characters 14-79
Called from Unification.solve_simple_evar_eqn in file "pretyping/unification.ml", line 1394, characters 8-72
Called from Unification.w_merge.w_merge_rec in file "pretyping/unification.ml", line 1437, characters 20-69
Called from Unification.w_merge in file "pretyping/unification.ml", line 1516, characters 4-157
Called from Unification.w_unify_core_0 in file "pretyping/unification.ml", line 1568, characters 12-65
Called from Clenv.clenv_unify in file "proofs/clenv.ml", line 298, characters 25-73
...
~~~

</details>

**Comment by Blaisorblade** [comment]
Can this be added to 8.18.1 if it happens? The Coq platform isn't even out (so many users haven't upgraded) and we have three reports. And in cases I've seen, the anomaly hides an actionable error message that allows fixing the proof script and completing the proof.

PMP how sure are you other callers do not trigger this anomaly? Or would your proposal turn Coq users into beta testers to find out?

Either way, we've already applied this patch internally as-is at Bedrock.

**Comment by SkySkimmer** [comment]
>I don't think this is a satisfactory revert. We should have instead an explicit list of calls to conversion known to send random ill-typed junk to the algorithm, and only catch anomalies there.

I think this is difficult and I have better things to do. We should just merge

**Comment by ppedrot** [comment]
Can't we merge this one in 8.18 only and try reverting piecewise in master?

**Comment by SkySkimmer** [comment]
We can try the piecewise thing in master after doing the full revert.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I'd like this one to be merged ASAP

**Review by ppedrot — APPROVED** [review]
If you're all insisting...

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
