### PR TITLE
Fix failing Windows CI builds.

### PR DESCRIPTION
**Pull request by Zimmi48**
Following a recent change in Cygwin.

**Kind:** infrastructure.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@JasonGross It looks like you may have broken performance-tests in your recent changes...

**Comment by JasonGross** [comment]
Oh, I think this is because the CI here is the only place where it's tested as not a git clone, and `find -name` prefixes things with `./`, and the logic I was using to filter-out files uses string comparison, and the list of disabled files was previously empty on master and therefore the combination of find + filter-out was untested.  Is there a standard way to get find to not prefix with ./, or should I just remove it from the strings afterwards?

**Comment by JasonGross** [comment]
I've pushed a fix for coq-performance-tests and restarted the job

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
Thanks!

**Pull request merged**
