### PR TITLE
Remove Canary

### PR DESCRIPTION
**Pull request by whitequark**
See #7839 for motivation.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Fine with me, this was mostly used for debugging anyways.

**Review by ppedrot — CHANGES_REQUESTED** [review]
You also need to adapt the checker/values.ml file accordingly, as you changed the memory representation of kernel names.

**Comment by whitequark** [comment]
Done.

**Comment by whitequark** [comment]
I think the `coq-dpdgraph` test fails because of [this line](https://github.com/Karmaki/coq-dpdgraph/blob/master/graphdepend.ml4#L54-L55). `GlobRef.ConstRef` has a `KerPair`, which is a pair of `KerNames`, which used to have a `canary`. So the old canary implementation didn't even catch bugs...

**Comment by ppedrot** [comment]
Why do you think so? It is only comparing the integer part AFAICS...

**Comment by whitequark** [comment]
I'm not entirely sure, but `Canary.obj` has quite surprising behavior:
```ocaml
# let obj = Obj.new_block Obj.closure_tag 0;;
val obj : Obj.t = <abstr>
# obj = obj;;
Exception: Invalid_argument "compare: functional value".
Raised by primitive operation at unknown location
Called from file "toplevel/toploop.ml", line 180, characters 17-56
# obj < obj;;
Exception: Invalid_argument "compare: functional value".
Raised by primitive operation at unknown location
Called from file "toplevel/toploop.ml", line 180, characters 17-56
# compare obj obj;;
- : int = 0
```
From the docs of `Canary`:
```
val obj : t
(** Canary. In the current implementation, this object is marshallable,
    forbids generic comparison but still allows generic hashes. *)
```
In other words, the purpose of Canary was to disallow polymorphic comparison, but it doesn't really do that, and in a way relevant to the behavior of those lines. But of course I may be wrong.

**Comment by ppedrot** [comment]
@whitequark I don't think it has anything to do with that. If I understand the diff correctly, it is simply that the output is sensitive to the order in which the hashtable storing the graph is traversed. As this patch changes the hash function, you get a different permutation. That said, the code is still wrong as it relies on generic hashtables for global references. So, the plugin is incorrect no matter what. I will write a patch to solve this issue.

**Comment by ppedrot** [comment]
Karmaki/coq-dpdgraph#49 makes this PR go through.

**Review by ppedrot — APPROVED** [review]

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
> Are you OK with the PR?

Yes, feel free to merge!

**Pull request merged**
