### PR TITLE
 Warnings on coercions used without being Imported

### PR DESCRIPTION
**Pull request by maximedenes**
This warning makes it much easier to stop relying on `Set Automatic
Coercions Import`. Tested with success on math-classes.

Depends on #8103 [merged].

### CODE REVIEW

**Comment by maximedenes** [comment]
@gares can you be the assignee for this one too? Thanks!

**Review by Zimmi48 — CHANGES_REQUESTED** [review]
I believe this is a case that would really benefit from an addition to the reference manual, since it supports documenting warnings with the `.. warn::` object. I suggest you document this warning inside the description of the corresponding (deprecated) option.

Not all my comments are hard requests but I would like to see at least some documentation or a clearer warning message, ideally both.

**Review by gares — APPROVED** [review]
My only concern was already reported by @Zimmi48 (making the text of the warning more explicit on the remedy).

**Review by herbelin — APPROVED** [review]
Not a heavy user of coercion and thus difficult to make up a proper opinion, but that looks a priori like a useful proposal.

**Comment by maximedenes** [comment]
@Zimmi48 comments addressed.

**Review by Zimmi48 — APPROVED** [review]

**Pull request merged**
