### PR TITLE
Fix overlay system: projects need to be loaded before overlays.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Also fixes is_in_projects

### CODE REVIEW

**Comment by SkySkimmer** [comment]
cc @gares

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I thought I had tested it, sorry for the mess.

**Comment by gares** [comment]
I think this is urgent, so I'll take it.

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
