### PR TITLE
[ssreflect] Fix module scoping problems due to packing and mli files.

### PR DESCRIPTION
**Pull request by ejgallego**
Unfortunately, mli-only files cannot be included in packs, so we have
the weird situation that the scope for `Tacexpr` is wrong. So we
cannot address the module as `Ltac_plugin.Tacexpr` but it lives in the
global namespace instead.

This creates problem when using other modular build/packing strategies
[such as #6857] This could be indeed considered a bug in the OCaml
compiler.

In order to remedy this situation we face two choices:
- leave the module out of the pack (!)
- create an implementation for the module

I chose the second solution as it seems to me like the most sensible
choice.

Overlays:
- https://github.com/mattam82/Coq-Equations/pull/58
- https://github.com/ppedrot/ltac2/pull/47

cc: #6512.

### CODE REVIEW

**Comment by maximedenes** [comment]
@ppedrot Any opinion on this?

**Comment by ejgallego** [comment]
[Sucessful] build on https://gitlab.com/ejgallego/coq/pipelines/18440720

**Comment by ppedrot** [comment]
@maximedenes I'd rather create a soft link from the ml file to the corresponding mli file rather than simply removing the mli file. I already complained about that and just as @ejgallego thinks mli-only modules are wrong, I think that it's a very bad idea to have ml-only modules. So let's take the join!

**Comment by SkySkimmer** [comment]
Would it be possible to use `ocamlc`'s `-impl`/`-intf` to compile the same file twice instead of copying it / linking it?

**Comment by ppedrot** [comment]
@SkySkimmer This requires a non-trivial change to the build system, and probably has dire consequences like race conditions and the like.

**Comment by ejgallego** [comment]
> @maximedenes I'd rather create a soft link from the ml file to the corresponding mli file rather than simply removing the mli file. I already complained about that and just as @ejgallego thinks mli-only modules are wrong.

What about windows? I'm fine with a symlink tho, but the other way around.

> I think that it's a very bad idea to have ml-only modules. So let's take the join!

So far you no single technical reason has been given in support for that. On the other, as clearly illustrated here `.mli` only modules are severely broken.

**Comment by ejgallego** [comment]
> Would it be possible to use ocamlc's -impl/-intf to compile the same file twice instead of copying it / linking it?

I much prefer we minimize the amount of hacks, that is to say, let's do as every other sane dev is doing a provide a real module.

**Comment by maximedenes** [comment]
So, what should we do about this?

**Comment by ejgallego** [comment]
> So, what should we do about this

IMO this should go as is, if someone wants to "beautify" the tree of course feel free to submit an additional PR.

There are more problems related to packing, plugins, and mli files that we should try to address before 8.8.

**Review by ppedrot — DISMISSED** [review]
I'm standing my ground, please make a soft link instead of moving the mli file. It's a trivial detail, and I'll definitely support the PR after this tiny change. Otherwise next thing I'll do is revert the move when submitting a PR introducing soft links, which is stupid.

**Comment by ejgallego** [comment]
Can someone confirm that a symlink in the source tree is not problematic?

I am still against doing it here as it introduces significant risk for systems not supporting them, _for only cosmetic benefit_.

Note that other `.mli`-only files in `plugins` also escape packing, however they are not so critical due to not having any consumers.

**Comment by maximedenes** [comment]
> Can someone confirm that a symlink in the source tree is not problematic?

I *think* it's ok, even on Windows, because git does something special. Generating a symlink at build time is not ok, though. But I'm not 100% sure.

**Comment by ejgallego** [comment]
Yeah I dunno, **everybody else** is using `.ml` files for interfaces these days, even for build systems that support a hack, it turns out that problems arise. I do not understand why we want to complicate our lives so much here...

**Comment by Zimmi48** [comment]
Just duplicate the code!

**Comment by ejgallego** [comment]
> Just duplicate the code!

Pierre-Marie is against that, so I am.

**Comment by Zimmi48** [comment]
Will I'm against .mli without .ml as you and against .ml without .mli as @ppedrot.

**Comment by ejgallego** [comment]
xD

**Comment by ejgallego** [comment]
Ok, let's try the symlink route. I hope it doesn't break anything.

**Comment by maximedenes** [comment]
Travis succes here: https://travis-ci.org/ejgallego/coq/builds/351072682

But for this one, we want to check if appveyor succeeds too.

**Comment by Zimmi48** [comment]
Unfortunately, it doesn't:

```
OCAMLC    plugins/ltac/tacexpr.mli
OCAMLOPT  plugins/ltac/tacexpr.ml
File "plugins/ltac/tacexpr.ml", line 1, characters 0-7:
Error: Unbound value tacexpr
```

**Comment by Zimmi48** [comment]
See also https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

**Comment by ejgallego** [comment]
Yeah as I feared symlinks were not a good idea. So let's aim for correctness first, then everyone is welcomed to find some solution that is not a hack for aesthetic pleasure.

**Comment by maximedenes** [comment]
In the absence of an answer from @ppedrot, I'll postpone this.

**Comment by maximedenes** [comment]
> In the absence of an answer from @ppedrot, I'll postpone this.

I meant if he doesn't this afternoon.

**Comment by ejgallego** [comment]
Sorry but this is a critical API fix and we shouldn't allow plugins writers to rely in a broken packing for 8.8, and they will find their plugins are broken in misterious ways.

The reasons given for the delay make at best no absolute sense, so please revert the milestone change.

**Comment by ejgallego** [comment]
Be well aware that releasing the beta without this in means that you'l break plugins _after_ the beta, so this in an absolute blocker.

**Comment by maximedenes** [comment]
We agreed offline we would go for an 8.8-only patch that duplicates the `.ml` and `.mli` files. I'll take care of it.

**Comment by ejgallego** [comment]
> We agreed offline we would go for an 8.8-only patch that duplicates the .ml and .mli files. I'll take care of it.

Umm let me give it a go as you are likely busy with other stuff.

**Comment by ejgallego** [comment]
But why 8.8 only patch? I don't understand, it is even more critical that `master` is not broken as otherwise quite a few PRs on the build system are gonna be broken as they perform basic sanity checks.

**Comment by maximedenes** [comment]
> But why 8.8 only patch?

Sorry, I meant a patch that will likely be replaced by a better fix soon after branching.

**Comment by ejgallego** [comment]
And what is the better fix going to be? Because unless you feel like rewriting the OCaml compiler there is no other choice than to ship a `.ml` file.

**Comment by maximedenes** [comment]
A better fix could be to switch to an `.ml`-only file :)

Is there any problem in going through a cycle where that's achieved by duplicating the files instead?

**Comment by ejgallego** [comment]
> Is there any problem in going through a cycle where that's achieved by duplicating the files instead?

Yes. What do we gain by that?

**Comment by maximedenes** [comment]
> Yes.

What is it, then?

**Comment by ejgallego** [comment]
> What is it, then?

That we gain nothing?

**Comment by maximedenes** [comment]
> That we gain nothing?

We make @ppedrot happy?

**Comment by ejgallego** [comment]
> We make @ppedrot happy?

We can provide him an emacs macro that will turn every `.ml` of his choice into an `.mli` file. By they way have you told him about the `coqp5` binary?

**Comment by maximedenes** [comment]
> By they way have you told him about the coqp5 binary?

No, I was letting you do it :)

**Comment by maximedenes** [comment]
This seems ok. Some failures are due to other overlay PRs not yet integrated.

Since the soft link solution doesn't work, I think this is a reasonable compromise for all participants to this discussion.

A better solution (avoiding duplication) will have to be found for `master`. In particular, @ppedrot and @Zimmi48 should clarify why they don't like the `.ml`-only solution, or provide an alternative way.

**Comment by maximedenes** [comment]
Rebased (after integration of the AST-related PRs), pipeline at https://gitlab.com/maximedenes/coq/pipelines/18684991

**Comment by Zimmi48** [comment]
> In particular, @ppedrot and @Zimmi48 should clarify why they don't like the .ml-only solution, or provide an alternative way.

Since I see this only now, let me answer: it is @gares who made me realize the problem when he asked during the last WG about how my backporting script ensured that there was no change to the API. Well, it reports any change to a `.mli` file. So in a sense this is important that all API is kept to `.mli` files.

Now let me ask what is the problem with a duplicated file. Don't tell me duplicated code is bad because this is the whole point of `.mli` files (duplicating type definitions and function declarations).

**Comment by ejgallego** [comment]
Duplicating is a pain, no question about it. Large developments in fact use a `foo_intf.ml` file as to avoid such tedious duplication, which is then used as a signature in the proper places. 

The `.mli` point detection is a good one, even thou if the script could be refined to consider as candidates files with no `.mli` implementation. I dunno what to do, but the problem with alias/packs is very real.

**Pull request merged**
