### PR TITLE
Fix #17852 (universe issue with reverse coercions)

### LINKED ISSUE #17852: Universe issue with reverse coercions
#### Description of the problem

```Coq
Record type : Type := Pack { sort :> Type }.
Canonical UnitProp := Pack Set.

Check Set : type.
(* Error: Anomaly "Unable to handle arbitrary u+k <= v constraints." *)
```

I'm opening a PR with a fix.

#### Coq Version

only master

### PR DESCRIPTION
**Pull request by proux01**
Fixes #17852 

- [x] Added / updated **test-suite**.

- [ ] ~Added **changelog**.~ (bug shouldn't appear in any released version)
- [ ] ~Added / updated **documentation**.~
  
  - [ ] ~Documented any new / changed **user messages**.~
  - [ ] ~Updated **documented syntax** by running `make doc_gram_rsts`.~

- [ ] ~Opened **overlay** pull requests.~

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by gares** [comment]
Dear @coq/universes-maintainers we would like to tag 8.18rc in 10 days. If you can review this bugfix by then I would be very happy.

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
Still fails on 
~~~coq
Record type : Type := Pack { sort :> nat -> Type }.

Definition set := fun _ : nat => Set.

Canonical UnitProp := Pack set.

Check set : type.
~~~

you should use `refresh_universes ~onlyalg:true ~status:Evd.univ_flexible (Some false)` on the types not some adhoc `if issort then new_type` hack

**Comment by gares** [comment]
Thanks both for acting quickly!

**Comment by proux01** [comment]
Thanks @SkySkimmer it's indeed much better than my horrible hack.

**Comment by SkySkimmer** [comment]
You should undraft and run full ci if this is ready

**Comment by proux01** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by proux01** [comment]
The windows failure seems unrelated, otherwise CI is green.

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
It would be nice to revert the change to HB and confirm MCA has no problems

**Pull request merged**
