### PR TITLE
Add a paragraph on reviewing PRs from newcomers.

### LINKED ISSUE #12274: [contributing] Integrate Théo's remarks in the contributing guide.
I think it would be a good idea to integrate Théo's remarks and advice on the contributing guide:

https://sympa.inria.fr/sympa/arc/coqdev/2020-03/msg00003.html

### PR DESCRIPTION
**Pull request by Zimmi48**
Fixes / closes #12274

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Thanks!

Something we should remind at some point too is to bear a bit with people not being native in English and cultural differences; for example Spanish speakers tend to sound too harsh in English if translated directly, etc....

**Comment by Zimmi48** [comment]
> Something we should remind at some point too is to bear a bit with people not being native in English and cultural differences; for example Spanish speakers tend to sound too harsh in English if translated directly, etc....

Maybe something that could even be said in the Code of Conduct.

**Comment by ejgallego** [comment]
> Maybe something that could even be said in the Code of Conduct.

Indeed, there may be some overlap with those, for example, on how to approach newcomers, people that has started to program recently, etc...

Merging for now, thanks!

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
