### PR TITLE
do not re-export ListNotations from Program

### PR DESCRIPTION
**Pull request by llelf**
Any particular reason why it's there?
I'm going to update the tests if this is going to be merged.

**Kind:** bug fix.

- [x] Added / updated test-suite
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

overlays

- [x] https://github.com/AbsInt/CompCert/pull/352
- [x] https://github.com/fblanqui/color/pull/25
- [x] https://github.com/coq-community/math-classes/pull/85
- [x] https://github.com/mattam82/Coq-Equations/pull/275
- [x] https://github.com/coq-community/coq-ext-lib/pull/85
- [x] https://github.com/mit-plv/fiat/pull/39
- [x] https://github.com/PrincetonUniversity/VST/pull/411

### CODE REVIEW

**Comment by anton-trunov** [comment]
Couple of observations:
- `git log` says it's been introduced in d068a422173a55eda92996aa46ec1094be614520;
- CI says a lot of projects rely on this implicitly imported notation (I guess we could try and fix those)

Is it the case you are using `Program` and would like to reuse the standard list notation for something else?

**Comment by llelf** [comment]
> Is it the case you are using Program and would like to reuse the standard list notation for something else?

For now it’s just the annoyance of figuring out which `Import` changed my list notation for reason whatsoever.

**Comment by herbelin** [comment]
Indeed, that would probably be more scalable that `Program` does not reexport `ListNotations but there are incompatibilies. If @mattam82 is around, he will maybe have a suggestion.

**Comment by herbelin** [comment]
Indeed, that would probably be more scalable that `Program` does not reexport `ListNotations but there are incompatibilies. If @mattam82 is around, he will maybe have a suggestion.

**Comment by ejgallego** [comment]
Seems pretty easy to fix I guess.

**Review by Zimmi48 — APPROVED** [review]
I am in favor of this PR. I suggest preparing a changelog entry, overlays and fixing the test-suite (should be easy to do). But I don't think we need to wait for input of Matthieu or any transition path (adding `Import ListNotations.` to a file is easy.

**Comment by Zimmi48** [comment]
Can we get an assignee from @coq/stdlib-maintainers?

**Review by ejgallego — APPROVED** [review]
Nicely spotted @llelf , thanks; IMO it is good to avoid this kind of implicit deps.

Update milestone as this seems good to have in 8.12 beta.

@llelf fixes to developments should be backward compatible, right? If so you can just suggest the authors to merge the overlays right now.

**Comment by llelf** [comment]
> fixes to developments should be backward compatible, right?

@ejgallego yep, they should be indeed

> If so you can just suggest the authors to merge the overlays right now

will do.

**Comment by llelf** [comment]
> to merge the overlays right now

is my understanding correct that they are to be merged before this?

**Comment by anton-trunov** [comment]
> is my understanding correct that they are to be merged before this?

Yes, it is.

**Comment by Zimmi48** [comment]
Status: this is just waiting on one last overlay to be merged AFAICT.

**Comment by llelf** [comment]
ready

**Comment by anton-trunov** [comment]
ok, looks like the overlays can be removed from this PR now

**Comment by llelf** [comment]
@anton-trunov you mean the `dev/ci/user-overlays/….sh` file?

**Comment by anton-trunov** [comment]
> you mean the dev/ci/user-overlays/….sh file?

Yes, indeed.

This will ensure CI with no overlays passes (see here for the relevant discussion -- https://github.com/coq/coq/pull/12312)

**Comment by anton-trunov** [comment]
Unfortunately I couldn't get `ci-sf` job working for the past several days, but since it used to pass and it is not in the set of overlays I'm going to merge this PR anyway.

**Review by anton-trunov — APPROVED** [review]

**Pull request merged**
