### PR TITLE
Print less trailing spaces in `Print`

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Those CI failures are going to be tricky.

**Comment by Alizter** [comment]
We can suggest to this CI failures that they can fix their tests (with an overlay) or else I think we should just explicitly disable those files ourselves like we do for unimath.

**Comment by SkySkimmer** [comment]
@JasonGross fiat crypto needs https://github.com/tchajed/coq-record-update/pull/35 / https://github.com/mit-plv/bedrock2/pull/252 through rupicola

@RalfJung please update stdpp with something like 
~~~diff
Adapt to coq/coq#16130

2 files changed, 8 insertions(+), 6 deletions(-)
test-normalizer.sed |  2 ++
tests/notation.ref  | 12 ++++++------

modified   test-normalizer.sed
@@ -4,3 +4,5 @@ s/subgoal/goal/g
 /[0-9]* focused goals\?$/{N;s/\n */ /;}
 # locations in Fail added in https://github.com/coq/coq/pull/15174
 /^File/d
+# extra space removed in https://github.com/coq/coq/pull/16130
+s/= $/=/
modified   tests/notation.ref
@@ -1,21 +1,21 @@
 test_2 = {[10 := {[10 := 1]}; 20 := {[20 := 2]}]}
      : M (M nat)
-test_3 = 
+test_3 =
 {[10 := {[10 := 1]}; 20 := {[20 := 2]}; 30 := {[30 := 3]}]}
      : M (M nat)
-test_4 = 
+test_4 =
 {[10 := {[10 := 1]}; 20 := {[20 := 2]}; 30 := {[30 := 3]}; 40 := {[40 := 4]}]}
      : M (M nat)
-test_op_2 = 
+test_op_2 =
 {[10 := {[10 ^ 2 := 99]}; 10 + 1 := {[10 - 100 := 42 * 1337]}]}
      : M (M nat)
-test_op_3 = 
+test_op_3 =
 {[10 := {[20 - 2 := [11]; 1 := [22]]};
   20 := {[99 + length [1] := [1; 2; 3]]};
   4 := {[4 := [4]]};
   5 := {[5 := [5]]}]}
      : M (M (list nat))
-test_op_4 = 
+test_op_4 =
 {[10 := {[20 - 2 := [11];
           1 := [22];
           3 := [23];
@@ -30,6 +30,6 @@ test_gmultiset_2 = {[+ 10; 11 +]}
      : gmultiset nat
 test_gmultiset_3 = {[+ 10; 11; 2 - 2 +]}
      : gmultiset nat
-test_gmultiset_4 = 
+test_gmultiset_4 =
 {[+ {[+ 10 +]}; ∅; {[+ 2 - 2; 10 +]} +]}
      : gmultiset (gmultiset nat)

~~~

**Comment by RalfJung** [comment]
> please update stdpp with something like

Done.

**Comment by Alizter** [comment]
@JasonGross gentle ping, can you fix fiat?

**Comment by JasonGross** [comment]
Hmm, dependabot is supposed to update fiat-crypto's submodules daily, but https://github.com/mit-plv/fiat-crypto/network/updates says it was last checked 2 days ago...  Ah, but I can trigger a manual update from that page by clicking on "last checked 2 days ago", so let me do that

**Comment by JasonGross** [comment]
Ah, the issue that rupicola itself needs the update

**Comment by JasonGross** [comment]
Once https://github.com/mit-plv/rupicola/pull/58 is merged (ping me again there if the CI has passed and nobody has merged it) I will trigger dependabot on fiat-crypto, and tell it to auto-merge once CI passes.  Hopefully this will all be done within a couple of days.  Sorry for the delay.

**Comment by JasonGross** [comment]
Once dependabot merges https://github.com/mit-plv/fiat-crypto/pull/1299 this should be good to (rerun CI and) go

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
