### PR TITLE
Extraction: reduce primitive projections in types (fix bug 4709)

### PR DESCRIPTION
**Pull request by letouzey**
See [bug 4709](https://coq.inria.fr/bug/4709)

### CODE REVIEW

**Comment by maximedenes** [comment]
Is there a way to add a test case for this bug?

**Comment by letouzey** [comment]
Not easily until #859 is merged. Or we put the test case in  `test-suite/output` and check the textual output of the extraction, but that's really fragile and I prefer to avoid that.

**Comment by maximedenes** [comment]
@letouzey #859 was merged, so maybe a test case is doable now.

**Comment by letouzey** [comment]
rebased + promised test case added

**Pull request merged**
