### PR TITLE
Revert cross-crypto breaking PR.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
Adding RMs and CI maintainers for comment.

**Comment by ejgallego** [comment]
cc #7718

**Comment by SkySkimmer** [comment]
https://github.com/adampetcher/fcf/pull/19 should fix (cross-crypto will need to update their submodule).

**Comment by SkySkimmer** [comment]
>adampetcher/fcf#19 should fix (cross-crypto will need to update their submodule).

Not sure how active that repo is though.

**Comment by Zimmi48** [comment]
Maybe you should ping the maintainer of cross-crypto there. They can always change the location of the sub-module. And they may be in closer contact with the maintainer of FCF.

**Comment by ejgallego** [comment]
That's @JasonGross

**Comment by ejgallego** [comment]
I am not sure if the revert is breaking quite a few other developments.

**Comment by SkySkimmer** [comment]
>I am not sure if the revert is breaking quite a few other developments.

??

**Comment by ejgallego** [comment]
Quite a few developments are failing.

**Comment by SkySkimmer** [comment]
Are we looking at different pipelines? I see no failing developments.

**Comment by ejgallego** [comment]
I see equations and mtac failing, but that's maybe becuase my branch?

**Comment by ejgallego** [comment]
I've pushed a new branch, let's see.

**Comment by JasonGross** [comment]
@andres-erbsen is actually the one to contact for cross-crypto, and it looks like he's on top of things.  Given that the fcf PR has been merged, I expect https://github.com/mit-plv/cross-crypto/issues/6 to be resolved soon

**Comment by ejgallego** [comment]
Ok so please close this when the upstream fixes are in.

**Comment by Zimmi48** [comment]
Submodule was updated.

**Comment by andres-erbsen** [comment]
https://github.com/mit-plv/cross-crypto/issues/6 is resolved

**Pull request closed without merging**
