### PR TITLE
Purify calls to Proof.refine_by_tactic w.r.t. the global state.

### LINKED ISSUE #13324: coqchk -o incorrectly reports abstracted subproofs from the obligation tactic in Program Definition as axioms in master
#### Description of the problem

```
$ cat abs.v
```
```coq
Require Import Coq.Program.Basics Coq.Program.Tactics.
Obligation Tactic := abstract exact I.
Program Definition foo : True := _.
Print Assumptions foo.
```
```
$ for ver in master 8.12.0; do (true | ~/.local64/coq/coq-$ver/bin/coqtop -q); ~/.local64/coq/coq-$ver/bin/coqc -q abs.v; ~/.local64/coq/coq-$ver/bin/coqchk -silent -o abs.vo; done
Welcome to Coq jgross-Leopard-WS:/home/jgross/Downloads/coq/coq-master,master (cdfe69d6da6b32338ba74c9f599c74389089c9dd)
Skipping rcfile loading.

Coq <
Closed under the global context

CONTEXT SUMMARY
===============

* Theory: Set is predicative

* Axioms:
    abs.temporary_proof1_subproof

* Constants/Inductives relying on type-in-type: <none>

* Constants/Inductives relying on unsafe (co)fixpoints: <none>

* Inductives whose positivity is assumed: <none>

Welcome to Coq 8.12.0 (August 2020)
Skipping rcfile loading.

Coq <
Closed under the global context

CONTEXT SUMMARY
===============

* Theory: Set is predicative

* Axioms: <none>

* Constants/Inductives relying on type-in-type: <none>

* Constants/Inductives relying on unsafe (co)fixpoints: <none>

* Inductives whose positivity is assumed: <none>

```

This is a regression over 8.12.0.  Interestingly, it only occurs when the `abstract` is in the obligation tactic.

#### Coq Version

cdfe69d6da6b32338ba74c9f599c74389089c9dd

### PR DESCRIPTION
**Pull request by ppedrot**
This is very hackish but I do not see a way around while the side-effect API is imperative.

Fixes #13324.

### CODE REVIEW

**Comment by ejgallego** [comment]
Uff, this seems to me like a case where the remedy is worse than the illness.

**Comment by ppedrot** [comment]
Furthermore, it's broken. As demonstrated by the CI there are pieces of code that depend on the global state being expanded at that point. This seems very suspicious to say the least.

**Comment by ejgallego** [comment]
I hard a pretty bad fight with this stuff a few months ago... I lost. I'm much afraid the only way we have for this is try to really cleanup all the stuff, making explicit the invariants / non-semantics.

**Comment by SkySkimmer** [comment]
Lots of "signature and its instance do not match", what does this anomaly mean?

**Comment by ppedrot** [comment]
I have some patches that make the side-effect API purely functional, so it might solve the relevant bug by side-effect (pun intended). There are still weird things going on with the namespace and I am not sure how to make this work properly...

**Comment by ppedrot** [comment]
@SkySkimmer I suspect this is due to some incorrect call from `Goal.V82.env` which relies on the global environment to create evar contexts, but I am not sure. This needs more investigation.

**Comment by ppedrot** [comment]
Closing as a PR, but I will keep that in my back pocket for further study.

**Comment by SkySkimmer** [comment]
- I think it breaks because the evar counter is in the summary, so we generate garbage evars
- I don't think this actually fixed the bug (testing on this example from the issue still shows the axiom:
~~~coq
Definition foo : True := ltac:(abstract exact I).

Print ltac_gen_subproof.
~~~
)

**Pull request closed without merging**
