### PR TITLE
Handle `-time` without tampering with ASTs

### PR DESCRIPTION
**Pull request by maximedenes**
The current hack was getting in the way of #15409.

### CODE REVIEW

**Comment by maximedenes** [comment]
@coqbot run full CI

**Comment by Alizter** [comment]
@coqbot bench

**Comment by maximedenes** [comment]
@Alizter does the bench rely on `-time`?

**Comment by SkySkimmer** [comment]
-time is how we get the per-line diffs

**Comment by SkySkimmer** [comment]
The per line slowdowns are all on Qed, since there are no corresponding big per line speedups and the per project stats show no change it seems -time now captures more of the cost of Qed.

**Comment by SkySkimmer** [comment]
For instance https://github.com/mit-plv/fiat-crypto/blob/93f79b646576c767c58b54e5ec58957046aff490/src/Assembly/WithBedrock/Proofs.v#L3269 got 
~~~
│   7.0480   21.2550  14.2070   201.57%  3261  coq-fiat-crypto-with-bedrock/src/Assembly/WithBedrock/Proofs.v.html                                 │
~~~
(for some reason the bench sees slightly different line numbers than the real file, for instance https://coq.gitlab.io/-/coq/-/jobs/3835879849/artifacts/_bench/html/coq-fiat-crypto-with-bedrock/src/Assembly/WithBedrock/Proofs.v.html the first 2 lines are both marked as line 1)

**Comment by gares** [comment]
The new behavior is the correct one, IMO

**Comment by maximedenes** [comment]
So is this ok?

**Comment by SkySkimmer** [comment]
Yes

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by ejgallego** [comment]
There were some bugs I think about the incorrect reporting of time, didn't find it, https://github.com/coq/coq/issues/14475 is related tho.

**Comment by maximedenes** [comment]
There was this, it seems: https://github.com/coq/coq/issues/8236

**Comment by ejgallego** [comment]
> There was this, it seems: #8236

Yes, that's the one I was thinking about!

**Pull request merged**
