### PR TITLE
Proof using cleanup, small doc addition and fix using Type in collections

### LINKED ISSUE #12930: Proof using collections broken when using Type
eg
~~~coq
Section S.
  Variable v : Prop.
  Variable vv : v.
  Collection easy := Type*.

  Lemma ybar : v.
  Proof using easy.
    exact vv.
  Qed. (* error: vv was not in the collection *)
End S.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #12930

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
Doc addition looks good.

As for the fix itself, it looks like it introduces a dynamic behavior to the Collection mechanism. I have no idea if that's something that's already expected or not.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Apparently I'm not a maintainer for this, in spite of having written the feature O_o.
I guess someone from @coq/vernac-maintainers has to take it.

**Comment by Zimmi48** [comment]
@gares I think you can overrule this, especially given that it's been 11 days and this PR still has no assignee. Feel free also to open a PR editing the code ownership for this very file if you'd like to be officially a maintainer without having to join the @coq/vernac-maintainers team.

**Comment by maximedenes** [comment]
@gares Yes, feel free to take it. If you prefer, I can also merge it.

**Comment by gares** [comment]
@coqbot please merge now

**Comment by gares** [comment]
Was I too kind?
@coqbot merge now , dammit!

**Pull request merged**
