### PR TITLE
Makefile: fix build on macOS

### LINKED ISSUE #9084: Installation via OPAM failed on macOS in Travis CI
#### Version

8.10+alpha

#### Operating system
macOS

#### Description of the problem

[QuickChick build #771.3](https://travis-ci.org/QuickChick/QuickChick/jobs/459251880#L927) could not install `coq.dev` via opam:
```
#=== ERROR while compiling coq.dev ============================================#
# context     2.0.1 | macos/x86_64 | ocaml-base-compiler.4.05.0 | https://coq.inria.fr/opam/core-dev
# path        ~/.opam/ocaml-base-compiler.4.05.0/.opam-switch/build/coq.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -j1
# exit-code   2
# env-file    ~/.opam/log/coq-86220-d4902a.env
# output-file ~/.opam/log/coq-86220-d4902a.out
### output ###
# [...]
# sed: 1: "1i # 1 "gramlib/plexing ...": command i expects \ followed by text
# make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
# OCAMLDEP  plugins/MLFILES plugins/MLIFILES
# Fatal error: exception Failure("gramlib__pack/gramlib.ml : empty map file or parse error")
# cp -a gramlib/gramext.ml gramlib__pack/gramlib__Gramext.ml
# sed -e "1i # 1 \"gramlib/gramext.ml\"" -i gramlib__pack/gramlib__Gramext.ml
# sed: 1: "1i # 1 "gramlib/gramext ...": command i expects \ followed by text
# OCAMLOPT  config/coq_config.ml
# File "config/coq_config.ml", line 1:
# Error: Could not find the .cmi file for interface config/coq_config.mli.
# make[1]: *** [config/coq_config.cmx] Error 2
# make: *** [submake] Error 2
```

### PR DESCRIPTION
**Pull request by liyishuai**
**Kind:** bug fix

Fixes / closes #9084 

- [ ] Entry added in CHANGES.md.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Thanks @liyishuai !

**Comment by maximedenes** [comment]
Why wasn't this caught by CI? Don't we test a macOS build?

**Comment by gares** [comment]
How are the backup files named on OSX? I think it should be `sed ... -i.bak` without the quotes.

**Comment by Zimmi48** [comment]
> Why wasn't this caught by CI? Don't we test a macOS build?

We do but we install `gnu-time`. Could it be responsible for installing `gnu-sed` in turn?

**Comment by ejgallego** [comment]
> Why wasn't this caught by CI? Don't we test a macOS build?

Also different OSX versions have different `sed` with different capabilities; I remember the build failed with some other specific OSX quick so we were not calling `gsed` I think.

**Comment by gares** [comment]
Note that the solution with `echo` based approach proposed in #8985 gets rid of sed altogether.

**Comment by ejgallego** [comment]
This has been stuck for no good reason and it is causing pain to OSX users; I will take over then.

@liyishuai , can you rebase please? [and sorry for the delay]

**Comment by herbelin** [comment]
The fix does not work for me. It says:
```
sed -e "1i # 1 \"gramlib/ploc.ml\"" -i'.bak' gramlib/.pack/gramlib__Ploc.ml
sed -e "1i # 1 \"gramlib/plexing.ml\"" -i'.bak' gramlib/.pack/gramlib__Plexing.ml
sed -e "1i # 1 \"gramlib/gramext.ml\"" -i'.bak' gramlib/.pack/gramlib__Gramext.ml
sed -e "1i # 1 \"gramlib/grammar.ml\"" -i'.bak' gramlib/.pack/gramlib__Grammar.ml
sed: 1: "1i # 1 "gramlib/ploc.ml"
": command i expects \ followed by text
sed: 1: "1i # 1 "gramlib/plexing ...": command i expects \ followed by text
cp -a gramlib/ploc.mli gramlib/.pack/gramlib__Ploc.mli
...
```

**Comment by SkySkimmer** [comment]
Replaced by #9194.

**Pull request closed without merging**
