### PR TITLE
Add optional stage argument to libobject helpers (global_object etc)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
Why do you need this @SkySkimmer ?

**Comment by SkySkimmer** [comment]
I thought it would be needed for https://github.com/LPCIC/coq-elpi/issues/516
@gares ended up writing a fix first using ` { (global_object ...) with stage = Synterp }` instead but I think having the argument would be nicer in the future

**Comment by ejgallego** [comment]
I understand now, thanks. Indeed it makes sense.

IMHO we should try to make staging more robust by typing, still having to rely on the current system is gonna later or sooner create bugs. I still think that using an existential that passes to the plugin the parsing state to update is worth it.

**Review by ejgallego — APPROVED** [review]
Trivial, merging myself as not worth involving others.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
