### PR TITLE
Bench: don't print CPU cycles in table

### PR DESCRIPTION
**Pull request by SkySkimmer**
It's useless AFAICT

### CODE REVIEW

**Comment by silene** [comment]
If the processors of the bench machine have the "turbo boost" feature, then the number of cycles might be a better metric than the user time. (That is, the processor will run at the maximum frequency until it overheats, at which points it scales down the frequency. The cycle count, contrarily to the user time, is independent of the overheating.) If there is no "turbo boost", I agree it is kind of useless.

**Comment by silene** [comment]
And looking at the output of of `/proc/cpuinfo`, the processors do have the feature. They run at 4.8GHz, until they overheat and degrade to 3.6GHz.

**Comment by SkySkimmer** [comment]
Maybe in theory, but in practice I don't think we've seen much difference between time and cpu cycle results

**Comment by Janno** [comment]
I personally always have to scroll to the right to get to the results that I want to see 99% of the time. So I am in favor of removing either of the first two columns. 

The turbo boost thing is interesting but also have not seen meaningful differences between time and cycles, neither in benchmarks here nor in local benchmarks. I suspect for most longer-running examples this only affects a small prefix of the run until everything stabilizes at the lower frequency?

**Comment by silene** [comment]
> until everything stabilizes at the lower frequency?

Yes, it might be that the thermal behavior is reproducible enough, so that it does not matter much. Note that the frequency does not necessarily stabilize. More often than not, it will oscillate between two values: heat accumulates, the frequency decreases to 3.6GHz, heat gets evacuated, the frequency increases to 4.8GHz, and so on. Also, it is highly dependent on whether the other cores are busy or not, since the heat from one core will propagate to neighboring cores. In fact, if only one single core is busy (e.g., `make -j1`), it might well stay at the boosted frequency for a long time. (This was the whole marketing argument around this feature.) Conversely, if several cores are busy, they will be stuck at the lowest frequency.

**Comment by ppedrot** [comment]
So, to merge or not to merge?

**Comment by Janno** [comment]
+1 for merging

**Comment by ppedrot** [comment]
If @silene doesn't complain soon, I'll merge at some point then.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
