### PR TITLE
Add support for instantiating non-implicit arguments by name or index

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** feature

Depends on #11099  (support for instantiating non-dependent implicit arguments by index) (merged).

See CEP [#49](http://github.com/coq/ceps/pull/49).

The current state of the PR is that arguments denoted by name or index can be given in any order. Other arguments are used to fill in order the remaining non implicit arguments that are not yet instantiated. No hole should remain at the end of the instantiation.

For instance:
```
Definition p {A} (x:A) (y:A) := (x,y).
Check p (y:=0) (x:=1).
Fail Check p (y:=0). (* x is missing *)

Definition p2 {A} B (x:A) (y:B) := (x,y).
About p2.
Check p2 (y:=1) (1:=0) nat. (* nat instantiates B *)
Fail Check p2 (y:=1) (1:=0). (* B is missing *)
```

- [X] Added / updated test-suite
- [ ] Corresponding documentation was added / updated
- [ ] Entry added in the changelog

### CODE REVIEW

**Comment by silene** [comment]
Since this depends on #11099 which has no milestone, I am removing the milestone from this one.

**Comment by Zimmi48** [comment]
Since this depends on another PR, I am turning this one into draft mode and unsubscribing. Please ping me if you need me here.

**Comment by SkySkimmer** [comment]
Doesn't seem ready for 8.15

**Comment by Alizter** [comment]
@herbelin Is this ready to be reviewed?

**Comment by herbelin** [comment]
> @herbelin Is this ready to be reviewed?

Yes and no.

I think that the ability of referring to all arguments by name (implicit or not) is quite powerful. On the other side, it seems to me that the PR should go farther:
- I'm not very satisfied by the failure when one argument in the middle is missing: wouldn't it be more natural to abstract over the missing arguments when this is possible? E.g. why not to provide `eq_trans (y:=0)` as a notation for `fun x => eq_trans x (y:=0)` (i.e. `fun x => eq_trans x 0`)?
- I find the reference by index of non-dependent argument (as in `(1:=0)`) a bit cryptic. I think we need to keep it by consistency with the similar notation in `apply with`, but I would recommend declaring a name also for non-dependent arguments, rather than counting. If really we want a selection by position, I would look for another notation (e.g. `(pos[n]:=...)`, or `(!n:=...)`, or `(nondep[n]:=...)`, ...).

It should also go together with other changes such as:
- forbid declarations like `Definition foo (a a : nat) : nat := 3.` which lead to ambiguous names (see #6785),
- allow to refer to non-dependent arguments by name also in `apply with`.

**Comment by SkySkimmer** [comment]
>On the other side, it seems to me that the PR should go farther:

Why should this further work be done in this PR rather than in followup PRs?

**Comment by silene** [comment]
> I'm not very satisfied by the failure when one argument in the middle is missing: wouldn't it be more natural to abstract over the missing arguments when this is possible?

I don't like the failure either. But please do not implicitly create an abstraction. Just make it an evar.

**Comment by herbelin** [comment]
> I don't like the failure either. But please do not implicitly create an abstraction. Just make it an evar.

But wouldn't the cases where we would not like to add an evar be precisely those where we want a partial application, e.g. to pass as a function to a functional?

Otherwise said, it seems practically easier to add manually a _` when we don't want to abstract than to add a `fun x =>` when we want to abstract?

**Comment by herbelin** [comment]
> Why should this further work be done in this PR rather than in followup PRs?

That's right. I'll try to do a compromise for this PR (especially improving the error messages and thinking at the documentation).

**Comment by silene** [comment]
> Otherwise said, it seems practically easier to add manually a `_` when we don't want to abstract than to add a `fun x =>` when we want to abstract?

Less verbose, certainly. But making it possible to skip the "fun" keyword does not really qualify as "easier".

I am not even sure what the rules would be. Consider a declaration `foo x y (H: P x y)`. How do you elaborate the term `foo (H := K)`? Do you create the ill-typed term `fun x y => foo x y K`? Or do you detect the dependency and just create `foo _ _ K`?

(Whether toplevel terms with uninstantiated variables should be automatically abstracted as in SSReflect is a different matter.)

**Comment by SkySkimmer** [comment]
Is this waiting for something? @herbelin

**Comment by SkySkimmer** [comment]
@herbelin ping

**Pull request closed without merging**
