### PR TITLE
Small optimization in Tacticals.compute_constructor_signatures.

### PR DESCRIPTION
**Pull request by ppedrot**
We do not compute the inductive structure when not computing recursive signatures. This is both cleaner and faster.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Review by herbelin — APPROVED** [review]
Simple enough not to wait further.

**Comment by ppedrot** [comment]
ping @herbelin this is a trivial tweak

**Comment by herbelin** [comment]
@coqbot merge now

No visible effect on the bench though iiuc.

**Pull request merged**
