### PR TITLE
[experiment] Universes loop checking with clauses

### PR DESCRIPTION
**Pull request by mattam82**
This is an experiment to reimplement the current consistency check using 
an algorithm from Bezem & Coquand based on Horn clauses which can handle
the enforcement of universe constraints on arbitrary max (u_i + k_i) universes.
Currently this is restricted to the constraints Coq can handle (u_i + {0, 1} <= v_i and u_i = v_i).
The new algorithm subsumes the current graph algorithm functionality, but it is not clear
it can be made as efficient. It currently slows down significantly in the Cauchy Reals development.

Fixes / closes #????

- [ ] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.
  
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make -f Makefile.dune doc_gram_rsts`.

- [ ] Opened **overlay** pull requests.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@mattam82 What on earth is happening here:
```
│   3.0610  2478.7720  2475.7110  80879.16%    32  coq-performance-tests-lite/src/n_polymorphic_universes.v.html                   │
```

**Comment by JasonGross** [comment]
> @mattam82 What on earth is happening here:
> 
> ```
> │   OLD        NEW       DIFF       %DIFF     Ln                  FILE                                                             │
> │   3.0610  2478.7720  2475.7110  80879.16%    32  coq-performance-tests-lite/src/n_polymorphic_universes.v.html                   │
> ```

```coq
Set Universe Polymorphism.
Record prod A B := pair { fst : A ; snd : B }.

Ltac make n base :=
  lazymatch n with
  | S ?n => let v := make n base in
            uconstr:(prod v v)
  | O => base
  end.
```
Up through `n = 5`.  Apparently typechecking a binary tree of `prod` with ~2^5 leaves is very slow

**Comment by mattam82** [comment]
This was absolutely not ready to be benched :)

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
@ppedrot I think I'll need your help identifying the hotspots here with perf, I tried to reasonably optimize this but I probably overlooked the main source of slowdown.

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
FTR, before the last commit:
```
┌────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                            │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                            │                         │                                       │                                       │                          │                 │
│        package_name        │   NEW     OLD    PDIFF  │      NEW             OLD       PDIFF  │      NEW             OLD       PDIFF  │   NEW      OLD    PDIFF  │ NEW  OLD  PDIFF │
├────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-core │  130.37  127.07    2.60 │   470000988387   463738254102    1.35 │   492716721886   489837911475    0.59 │  287212   287744   -0.18 │   0    0    nan │
│      coq-engine-bench-lite │  184.99  179.35    3.14 │   783884724133   758482317675    3.35 │  1426436352203  1390549077833    2.58 │ 1045464  1227400  -14.82 │   0    0    nan │
│ coq-performance-tests-lite │  901.69  838.14    7.58 │  3930814376882  3651983047229    7.64 │  6623963729903  6268296130813    5.67 │ 2060664  2057160    0.17 │   0    0    nan │
│               coq-bedrock2 │  534.76  399.50   33.86 │  2341341322122  1748895708696   33.88 │  4160257158044  3339681232944   24.57 │ 1834632  1831580    0.17 │   0    0    nan │
│                coq-coqutil │   51.58   37.55   37.36 │   224406222582   162221775894   38.33 │   320385664435   231535191873   38.37 │  591016   586984    0.69 │   0    0    nan │
│                coq-bignums │   42.27   30.52   38.50 │   184557091226   133231741407   38.52 │   258443786634   187821165788   37.60 │  479472   468292    2.39 │   0    0    nan │
│     coq-mathcomp-odd-order │  804.69  558.86   43.99 │  3525845286797  2448863840700   43.98 │  5491145498618  4162934687039   31.91 │  931508   932612   -0.12 │   0    0    nan │
│      coq-mathcomp-fingroup │   35.59   24.11   47.62 │   155787700310   105329241678   47.91 │   219035554202   153606303368   42.60 │  508956   487848    4.33 │   0    0    nan │
│                   coq-corn │ 1286.02  846.04   52.00 │  5626684805412  3697687717686   52.17 │  8242557703794  5756610774111   43.18 │  840976   838416    0.31 │   0    0    nan │
│           coq-math-classes │  156.07  100.69   55.00 │   680972358243   438708253601   55.22 │   942862430111   628587393667   50.00 │  530972   506744    4.78 │   0    0    nan │
│      coq-mathcomp-solvable │  139.98   88.99   57.30 │   613076731275   389400744484   57.44 │   880343652131   596422667182   47.60 │  696932   646168    7.86 │   0    0    nan │
│              coq-fiat-core │   96.89   60.13   61.13 │   410642733220   250476002887   63.94 │   585074500882   356908558261   63.93 │  522568   476976    9.56 │   0    0    nan │
│                 coq-stdlib │  781.82  470.94   66.01 │  3074895553817  1673246206561   83.77 │  2202740926091  1532239128056   43.76 │  624188   597796    4.41 │   0    0    nan │
│                 coq-geocoq │ 1280.22  744.52   71.95 │  5604611635566  3254179957346   72.23 │  8555020832479  5234624216181   63.43 │ 1075688   981128    9.64 │   0    0    nan │
│     coq-mathcomp-character │  129.41   73.29   76.57 │   566732044408   320482191484   76.84 │   791797120876   485197985199   63.19 │  719520   728724   -1.26 │   0    0    nan │
│                 coq-flocq3 │  150.04   79.90   87.78 │   655775964701   348031885506   88.42 │   904874049388   468048229912   93.33 │ 1071056   993332    7.82 │  67    0    nan │
│     coq-mathcomp-ssreflect │   55.05   27.82   97.88 │   241099196675   121510409551   98.42 │   317338955553   155440001602  104.16 │  560136   531732    5.34 │   0    0    nan │
│       coq-mathcomp-algebra │  129.31   64.82   99.49 │   566348777596   283476531663   99.79 │   752827708153   390273076577   92.90 │  601244   555348    8.26 │   0    0    nan │
│               coq-coqprime │   97.99   46.59  110.32 │   428083151539   202224792232  111.69 │   61[973](https://gitlab.com/coq/coq/-/jobs/2505680308#L973)7775928   303786877533  104.00 │  814128   755640    7.74 │   0    0    nan │
│         coq-mathcomp-field │  239.92  104.15  130.36 │  1051361178560   456143593938  130.49 │  1500700987483   74912[983](https://gitlab.com/coq/coq/-/jobs/2505680308#L983)8269  100.33 │  779724   635920   22.61 │   0    0    nan │
│                  coq-color │  676.18  240.23  181.47 │  2956593744468  1046660816987  182.48 │  4151731135941  1493566529732  177.97 │ 1253804  1040932   20.45 │   0    0    nan │
│               coq-rewriter │ 3671.41  349.71  949.84 │ 16092808888445  1527839929225  953.30 │ 21496237284505  25140[986](https://gitlab.com/coq/coq/-/jobs/2505680308#L986)51219  755.03 │ 1214356   969644   25.24 │   0    0    nan │
└────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
FTR, before performance tuning:
```
┌────────────────────────────┬───────────────────────────┬─────────────────────────────────────────┬────────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                            │       user time [s]       │               CPU cycles                │            CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                            │                           │                                         │                                        │                          │                 │
│        package_name        │   NEW      OLD     PDIFF  │      NEW             OLD         PDIFF  │      NEW             OLD        PDIFF  │   NEW      OLD    PDIFF  │ NEW  OLD  PDIFF │
├────────────────────────────┼───────────────────────────┼─────────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-unimath │ 4930.17  4947.89    -0.36 │ 22553692276463  22630540024664    -0.34 │ 45244863730457  45263391078393   -0.04 │ 3400836  3420864   -0.59 │   0    0    nan │
│                   coq-core │  111.23   110.84     0.35 │   467437944755    459315169180     1.77 │   487037743976    483041473672    0.83 │  289132   286440    0.94 │   0    0    nan │
│      coq-engine-bench-lite │  170.88   169.65     0.73 │   739004203912    732632363028     0.87 │  1402936819959   1386705907732    1.17 │ 1098652  1228460  -10.57 │   0    0    nan │
│              coq-fourcolor │ 1501.34  1480.73     1.39 │  6851075023101   6754868609578     1.42 │ 12359678795895  12233008591860    1.04 │  721504   720720    0.11 │   0    0    nan │
│               coq-bedrock2 │  377.95   367.78     2.77 │  1726834013738   1679406426226     2.82 │  3360231296881   3290941567314    2.11 │ 1831064  1979816   -7.51 │   0    0    nan │
│                 coq-geocoq │  721.57   700.09     3.07 │  3288961410004   3190501271966     3.09 │  5327026482778   5232115568917    1.81 │ 1012764   977748    3.58 │   0    0    nan │
│ coq-performance-tests-lite │  823.88   799.04     3.11 │  3740471389538   3627129966776     3.12 │  6514736526918   6371091689200    2.25 │ 2056640  2056608    0.00 │   0    0    nan │
│                   coq-hott │  179.48   172.23     4.21 │   813821985436    781627319989     4.12 │  1303257917317   1269490676897    2.66 │  573236   575624   -0.41 │   0    0    nan │
│                coq-coqutil │   37.81    35.50     6.51 │   170086117586    159412302487     6.70 │   247307176896    232082030678    6.56 │  588220   586196    0.35 │   0    0    nan │
│               coq-coqprime │   46.48    43.50     6.85 │   210626553413    196998797222     6.92 │   324295992238    302636736873    7.16 │  757084   755828    0.17 │   0    0    nan │
│                 coq-stdlib │  452.32   423.15     6.89 │  1896956187990   1763189344068     7.59 │  1565662757548   1527976758926    2.47 │  605720   586988    3.19 │   0    0    nan │
│                coq-bignums │   30.83    28.69     7.46 │   140145898082    131035842131     6.95 │   200050614936    186405577329    7.32 │  469320   468992    0.07 │   0    0    nan │
│      coq-mathcomp-fingroup │   24.25    22.48     7.87 │   110834660706    102513224398     8.12 │   164535868125    151832988331    8.37 │  495128   486084    1.86 │   0    0    nan │
│                 coq-flocq3 │   82.69    75.23     9.92 │   376410792834    341864883397    10.11 │   522473106555    466509789591   12.00 │  992060   995228   -0.32 │   0    0    nan │
│                  coq-verdi │   52.20    47.31    10.34 │   237578723038    214240161751    10.89 │   366091649777    330158645596   10.88 │  828208   772912    7.15 │   0    0    nan │
│      coq-mathcomp-solvable │   92.48    83.58    10.65 │   422309544152    381861780979    10.59 │   647299926125    590724270688    9.58 │  669768   651556    2.80 │   0    0    nan │
│     coq-mathcomp-odd-order │  589.90   527.83    11.76 │  2700579140154   2415093842456    11.82 │  4512717739244   4139835888843    9.01 │  934940   867796    7.74 │   0    0    nan │
│     coq-mathcomp-character │   78.61    68.82    14.23 │   359076395505    314374863133    14.22 │   543535564677    481353672249   12.92 │  763152   730008    4.54 │   0    0    nan │
│                   coq-corn │  957.53   796.04    20.29 │  4365761415586   3625409366931    20.42 │  6707120045047   5738910382148   16.87 │  904476   841004    7.55 │   0    0    nan │
│             coq-verdi-raft │  667.49   551.49    21.03 │  3049699196345   2518223974149    21.11 │  4991812636424   4003631546429   24.68 │ 1253224  1198980    4.52 │   0    0    nan │
│       coq-mathcomp-algebra │   74.49    61.29    21.54 │   340225042970    279403809724    21.77 │   470216765183    389152505030   20.83 │  572248   553568    3.37 │   0    0    nan │
│     coq-mathcomp-ssreflect │   31.50    25.88    21.72 │   143345471995    117259047365    22.25 │   191682855190    152181092267   25.96 │  547212   529200    3.40 │   0    0    nan │
│                    coq-vst │ 1246.32  1019.94    22.20 │  5679367475226   4648955624750    22.16 │  9132747919741   7582815425583   20.44 │ 2661848  2595792    2.54 │   0    0    nan │
│         coq-mathcomp-field │  121.39    98.41    23.35 │   555350825038    450112134978    23.38 │   886630236247    744721[1707](https://gitlab.com/coq/coq/-/jobs/2562907286#L1707)84   19.06 │  776392   638820   21.54 │   0    0    nan │
│             coq-coquelicot │   43.91    34.80    26.18 │   198065173568    157173565256    26.02 │   278867236041    215975903165   29.12 │  770716   744636    3.50 │   0    0    nan │
│                  coq-color │  289.80   226.17    28.13 │  1314600054798   1022967446621    28.51 │  1903178733097   1495535892490   27.26 │ 1139764  1041000    9.49 │   0    0    nan │
│           coq-math-classes │  126.76    95.09    33.31 │   575269441979    430740752585    33.55 │   821962849647    630021657019   30.47 │  513400   505648    1.53 │   0    0    nan │
│           coq-fiat-parsers │  468.60   341.18    37.35 │  2117949859163   1534886853156    37.99 │  3527139278115   2577438347514   36.85 │ 3044836  3041632    0.11 │   0    0    nan │
│              coq-fiat-core │   77.48    56.31    37.60 │   341620408708    243984032472    40.02 │   505508733376    356785436400   41.68 │  496044   477728    3.83 │   1    0    nan │
│              coq-perennial │ 5793.69  3989.43    45.23 │ 26457524359376  18191492219169    45.44 │ 41482594762571  30004391062978   38.26 │ 2684032  2610980    2.80 │   0    0    nan │
│          coq-iris-examples │  674.07   440.91    52.88 │  3072550550524   2004400343613    53.29 │  4637548845923   3062567207991   51.43 │ 1298324  1187076    9.37 │   0    0    nan │
│   coq-metacoq-translations │   20.69    13.38    54.63 │    93573855984     60074149813    55.76 │   144486044499     98264558547   47.04 │  774400   719772    7.59 │   0    0    nan │
│       coq-metacoq-template │  221.92   130.58    69.95 │  1004527197821    586455718007    71.29 │  1524517211820    982587133755   55.15 │ 1181928  1216476   -2.84 │   0    0    nan │
│        coq-metacoq-erasure │ 1707.03   194.15   779.23 │  7816699504200    880601366011   787.65 │  9539915788122   1435680389453  564.49 │ 1759496  1363700   29.02 │   0    0    nan │
│    coq-metacoq-safechecker │ 1780.76   179.23   893.56 │  8160758459210    815941396813   900.16 │  9686182746870   1185525542843  717.04 │ 1578320  1309972   20.49 │   0    0    nan │
│          coq-metacoq-pcuic │ 6584.89   576.73  1041.76 │ 30[1716](https://gitlab.com/coq/coq/-/jobs/2562907286#L1716)02214775   2622099238101  1050.67 │ 36113536564135   3876125186779  831.69 │ 2056864  1818004   13.14 │   0    0    nan │
└────────────────────────────┴───────────────────────────┴─────────────────────────────────────────┴────────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
@coqbot bench

**Comment by marcbezem** [comment]
Do the libraries contain Fail examples that fail because of universe inconsistency? If not I think it would be a good idea to add them. The reason is of course that we also want to know that the algorithm actually detects existing loops. We also want to know how fast the algorithm is finding the loops. For that purpose it would be good to have a whole library of Fail results that have in practice. (It may require a community effort to build such a library, for example asking people who have worked on paradoxes, Hott, or formalizing higher category theory.)

**Comment by mattam82** [comment]
@marcbezem that's a good point, I don't think we have many such examples available except in the test-suite, to test paradoxes don't hold for example. I don't think I've ever seen a Fail universe test in a user development.

**Comment by mattam82** [comment]
@coqbot bench

**Comment by mattam82** [comment]
@coqbot bench

**Pull request closed without merging**
