### PR TITLE
[engine] Fix #9259

### LINKED ISSUE #9259: Disable developer-only options
8.10 version of #7531

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by maximedenes** [comment]
Thanks!

**Comment by ppedrot** [comment]
@vbgl should probably be the assignee of this bug.

**Comment by Zimmi48** [comment]
Unfortunately, @coqbot doesn't track the change of base branch, so we'll have to close / reopen. I could add support for this, but this is quite a rare case.

**Comment by Zimmi48** [comment]
And @maximedenes can't you do something to definitely disable AppVeyor? It keeps showing up in the status checks from time to time.

**Review by gares — APPROVED** [review]

**Pull request merged**
