### PR TITLE
[ci] [travis] Remove CI contrib testing from Travis.

### PR DESCRIPTION
**Pull request by ejgallego**
This was kept as a fallback for some time, not worth keeping it
anymore as our GitLab setup seems mature and reliable enough.

### CODE REVIEW

**Comment by ejgallego** [comment]
https://travis-ci.org/ejgallego/coq/builds/436116436

**Comment by ejgallego** [comment]
> There's seem to be an issue with the current version. Also please, reactivate temporarily Travis building on your fork so that we can also see what this gives on a branch build.

Should be better now.

**Review by Zimmi48 — APPROVED** [review]
:heart:

**Comment by Zimmi48** [comment]
BTW this PR should also remove file `sudo-apt-get-update.sh` from `dev/tools` and `CODEOWNER`.

**Comment by ejgallego** [comment]
> BTW this PR should also remove file `sudo-apt-get-update.sh` from `dev/tools` and `CODEOWNERS`.

Good catch, done.

**Comment by Zimmi48** [comment]
@SkySkimmer Please merge this now. Travis branch testing is anyways currently broken following the recent merge of the PR updating the minimal version of OCaml.

**Pull request merged**
