### PR TITLE
Removal of the FAQ LaTex document.

### PR DESCRIPTION
**Pull request by mattjquinn**
The Coq FAQ has been moved to the GitHub wiki section of this source repository. Issue #6180 of this repository tracks that now-completed work. Therefore the FAQ Latex artifact within this repository is now obsolete.

This pull request simply removes the doc/faq directory from this repository.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
It's probably a good idea though to add a mention of this move in the `CHANGES` file at the root of the repository.

**Comment by mattjquinn** [comment]
Just added a note to CHANGES.

**Comment by maximedenes** [comment]
I see some failures on Travis, it looks like some build rules for the FAQ haven't been removed.

**Comment by SkySkimmer** [comment]
That's a lot of commits.

**Comment by letouzey** [comment]
Note that the website has been updated, <https://coq.inria.fr/faq> now redirects to the wiki page.

Ok to this PR, the latex sources of the FAQ are indeed obsolete. But some related files might still be of interest : `axioms.fig` (xfig source of `axioms.jpg`) and `interval_discr.v`. I'll put both in the wiki.

**Comment by maximedenes** [comment]
@mattjquinn Would you mind squashing the two commits? The second is really a fix for the first which won't compile. Thanks!

**Comment by mattjquinn** [comment]
Yes just squashed them.

**Comment by maximedenes** [comment]
@Zimmi48 is it ok to add a 8.7.1 entry in `CHANGES`? The change did happen before 8.7.1, but the released `CHANGES` did not mention it.

**Comment by Zimmi48** [comment]
No, it's a 8.8 change. When it happened in the release timeline doesn't matter. The removal of the FAQ from the sources is not going to be backported.

**Pull request merged**
