### PR TITLE
Remove "kind" from pull request template

### PR DESCRIPTION
**Pull request by SkySkimmer**
It's useless AFAICT.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
The goal was to give the possibility of clarifying intent for contributors without write access (and thus unable to set labels). But OK, I agree that it hasn't been useful in practice.

~~@coqbot merge now~~

**Comment by Zimmi48** [comment]
Actually, let's leave a few days for comments if anyone wants to make some.

**Comment by herbelin** [comment]
Personally I used to like the kind field, but that's also true that it can be reinferable from the labels (the template could also incite to use the labels by the way, at least for users that know what to put)

On a related note, couldn't issues be better triaged, incitating users to put labels, maybe incitating to cc at least one group of maintainers?

**Comment by Zimmi48** [comment]
> the template could also incite to use the labels by the way, at least for users that know what to put

And who have permissions to do so.

>On a related note, couldn't issues be better triaged, incitating users to put labels, maybe incitating to cc at least one group of maintainers?

Yes, I've been considering the question for a while. GitHub issue templates have become much more powerful (pull request templates less so).

Here is what we can do with them:

- Create multiple issue templates depending on the nature of the issue. This is typically used to request different information when reporting a bug or opening a feature request.
- Automatically add labels (even if the user doesn't have the appropriate permission for doing that manually): this is typically useful in combination to providing multiple issue templates since this reflects what template was used.
- Automatically add assignees. We used to do that in Bugzilla depending on the component, but that wasn't really useful because developers were getting hundreds of assigned issues and didn't manage them. Now that we have maintainer teams, we could consider assigning maintainer teams sometimes (e.g. if we have a different template for, say, CoqIDE bugs). Another thing I considered would be to create a "triage" team (whose members could be rolling), which would be assigned incoming issues, and whose role would be to treat them until they are properly triaged (in a sense that would need to be defined, but which could include: having reproduced the issue, having decided if that's a real bug or an acceptable feature request, having determined a level of difficulty, having assigned a priority, having found an assignee and put a milestone if it's a high priority issue, having put the "help wanted" or "good first issue" label if it's up for grabs...).
- Create structured forms. That's a new feature (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) that can be useful to add more textual help to the user reporting a bug without making the resulting issue to heavy (because explanation text won't be kept).

We can follow up on this discussion here or on Zulip if anyone is motivated to start experimenting with this.

**Comment by SkySkimmer** [comment]
>Now that we have maintainer teams, we could consider assigning maintainer teams sometimes

I don't think teams can be assignees. Or is that a web ui limitation?

**Comment by Zimmi48** [comment]
> I don't think teams can be assignees. Or is that a web ui limitation?

Oh! I didn't realize this.

**Comment by Zimmi48** [comment]
We could consider using the `needs: triage` label instead of assigning a triage team.

Anyway, here is an example of what using multiple template and forms could give: https://github.com/Zimmi48/coq/issues/new/choose

**Comment by Zimmi48** [comment]
Let's merge this PR for now: @coqbot merge now

I'll open a draft PR for the multiple issue templates with forms proposal.

**Pull request merged**
