### PR TITLE
Unconditionally load opaque proofs in coqchk even in norec mode.

### PR DESCRIPTION
**Pull request by ppedrot**
This was an optimization, but it turns out that opaque proofs from dependencies are still accessed by functor instantiation and module inclusion. Therefore, as a simple fix we just load them as well. We could have tried to be more clever by either loading it on the fly or carrying around additional data for delayed typing, but it is probably not worth it both in terms of complexity and efficiency.

### CODE REVIEW

**Comment by ppedrot** [comment]
This is essentially a revert of 2f1111e, cc @SkySkimmer.

**Comment by Alizter** [comment]
Random question: Is there anyway we could bench coqchk? A lot of jobs in the bench probably have a validate target for instance.

**Comment by JasonGross** [comment]
> Random question: Is there anyway we could bench coqchk? A lot of jobs in the bench probably have a validate target for instance.

Please do this, the validate target on Fiat Crypto takes 30 minutes (45 if you turn off the vm, ~90 if you turn off the vm and use Mac OS)

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by JasonGross** [comment]
@ppedrot I thought the bench only tests the install targets?

**Comment by JasonGross** [comment]
Apparently [opam has `--with-test`](https://opam.ocaml.org/doc/Manual.html#opamfield-run-test).

**Comment by JasonGross** [comment]
I've created https://github.com/coq/opam-coq-archive/issues/2155, btw

**Comment by ppedrot** [comment]
It doesn't hurt to check anyways.

**Comment by SkySkimmer** [comment]
Is bedrock just randomly broken in the bench?
~~~
# File "/home/gitlab-runner/builds/av_eR6za/0/coq/coq/_bench/opam.NEW/ocaml-base-compiler.4.07.1/.opam-switch/build/coq-bedrock2.dev/bedrock2/src/bedrock2Examples/LiveVerif/swap.v", line 363, characters 4-61:
# Error: Expected a single focused goal but 5 goals are focused.
~~~

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
Bench succeeded this time round. I guess before there was a solar flare or something.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@ppedrot  @SkySkimmer are we happy with this? I will assign and merge if so.

**Comment by ppedrot** [comment]
I am happy with this patch, even though we didn't really check for its performance effects.

**Comment by SkySkimmer** [comment]
test suite (master) https://gitlab.com/coq/coq/-/jobs/2330261643 and test suite (this pr) https://gitlab.com/coq/coq/-/jobs/2301177950) took similar amounts of time so perf is hopefully ok
same for validate

**Comment by Alizter** [comment]
merging tomorrow then

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
