### PR TITLE
Fix #11303: skip complexity tests on windows even if bogomips found

### LINKED ISSUE #11303: Spurious failures in complexity tests
I have seen recently a number of spurious failures in our CI due to complexity tests. I believe we should run them on the bench infrastructure (which we have precisely to get consistent performance) instead of the CI, where VMs can make performance vary greatly from one build to another.

Cc @coq/ci-maintainers

### PR DESCRIPTION
**Pull request by SkySkimmer**
Apparently the bogomips produced by cygwin are extra-bogo.

### CODE REVIEW

**Comment by JasonGross** [comment]
I don't think this is actually the issue.  I think the issue is that the user time in some commands from `Time` gets reported as `0.` and Windows adds `\r` which the Makefile does not correctly strip, and so the `expr` command to calculate the time fails with "syntax error" and gives an empty time.  I think the current state of #11308 might finally fix this issue, and if it does (or if I can get it working within the next day or so), I think we should merge #11308 rather than this PR.

**Comment by SkySkimmer** [comment]
We should merge this now, and take our time to investigate if we want to run these tests on windows rather than letting cygwin updates decide for us.

**Comment by JasonGross** [comment]
Sure, I can just include a revert of this PR in #11308 if that's preferred.

**Comment by ppedrot** [comment]
@JasonGross #11198 is not part of 8.11 AFAICT and the Windows CI is broken there as well. Isn't it conflicting with your explanation?

**Comment by JasonGross** [comment]
@ppedrot No, there was already an `expr` command (now failing with a syntax error in 8.11).  #11198 added a second one.  The second one had an additional syntax issue that I also fix in #11308 , and I was quite confused when this did not fix the issue, until I improved the error reporting enough to detect the extra trailing newline.  (It's also possible that I was following a red herring in the syntax of addition and division; I cannot recall if I was running expr from cmd.exe or from bash.  But removing the unneeded escaping there does not hurt in any case.)

**Comment by maximedenes** [comment]
What's holding this? I still see spurious failures on all PRs, we should do something about it.

**Comment by maximedenes** [comment]
In fact, we should probably rather merge https://github.com/coq/coq/pull/11308 IIUC.

**Comment by ppedrot** [comment]
I am in favour of merging and sorting out the problem later. Backporting PRs in 8.11 shouldn't trigger spurious failures.

**Comment by ppedrot** [comment]
@Zimmi48 Why wasn't this automatically added to the 8.11 project? Does it mean we might have lost some *backportenda* PRs?

**Comment by ppedrot** [comment]
OK, I understood: this PR is actually part of #11308, but the latter is not backportable to 8.11. Pretty tricky situation.

**Comment by SkySkimmer** [comment]
This actually got merge AND reverted by #11308, not sure why it was included at all...

**Comment by Zimmi48** [comment]
So FTR, currently the bot will watch the commits that are pushed to determine which PRs have been merged and should be backported (rather than being triggered on GitHub merge events). The alternative setup would have been possible as well and would have resulted in a different behavior (but then the backporting script would have failed anyway). In any case, the main mistake here is that the "needs: merge of dependency" label should have been used in #11308. Then, there would have been two options, either merge this PR properly first, or close it, remove the corresponding commits (or not) and merge #11308.

**Pull request merged**
