### PR TITLE
Make some match-all cases more precise in stm.ml

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
By the way, why do we have variants in the STM instead of proper ADTs? It makes the code much more brittle and results in unreadable types...

**Comment by gares** [comment]
because I was lazy I guess. IIRC there is only one place, in vcs, where I really use their typing rules

**Comment by gares** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
I interestingly get unused warnings when using static types... Will submit the full version anytime soon.

**Pull request merged**
