### PR TITLE
Stronger invariants on the syntax of records and variants

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** Enhancement

The vernac, kernel and documentation layers were not so clear about whether a `Record` or `Variant` type could be recursive and/or mutually defined, leading e.g. to errors such as:

```coq
Record t := { a : nat } with u := { b : nat }.
Print u.
(* Record t : Set := Build_t { a : nat }. *)
```
We make it more robust, to the point of disallowing using `with` in the `Record` and `Variant` syntax. This will also hopefully make the doc about `Record` and `Variant` less confusing with this regard.

- [x] Added / updated **test-suite**.
- [x] Added / updated **documentation**.
- [x] Updated **documented syntax** by running `make -f Makefile.dune doc_gram_rsts`.

### CODE REVIEW

**Comment by jfehrle** [comment]
Do you think people were using the `with` clause for definitions?  Should that be deprecated first?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@jfehrle I don't think it is necessary since it was a noop to begin with.

**Comment by Alizter** [comment]
Merging tomorrow

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
FTR, this is one step in the direction initiated in #11868. However, there are still other things (that were mentioned in the description of this PR) that could be worth changing.

**Comment by Zimmi48** [comment]
In particular, the `:=` syntax is not supported by the `Variant` command. Instead of raising an error at interpretation time, it would make more sense to separate the parsing rules, wouldn't it?

**Comment by herbelin** [comment]
> In particular, the `:=` syntax is not supported by the `Variant` command. Instead of raising an error at interpretation time, it would make more sense to separate the parsing rules, wouldn't it?

I don't know how to solve the tension between the advantages of factorizing and the advantages of duplicating. We would need higher-order parsing rules...

**Pull request merged**
