### PR TITLE
[general] Merge parsing with highparsing, put toplevel at the top of the linking chain.

### PR DESCRIPTION
**Pull request by ejgallego**
this is on top of #938 #937

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I'm not very happy to see Metasyntax moved to parsing, at it also deals with constrexpr-related stuff, but apart from that I support this PR. We'll find a way to clean Metasyntax afterwards.

**Comment by ppedrot** [comment]
(Also, not sure it makes sense to provide 3 separate PRs for this cleanup, but if we merge this one the others are going to be merged automatically.)

**Comment by ejgallego** [comment]
> (Also, not sure it makes sense to provide 3 separate PRs for this cleanup, but if we merge this one the others are going to be merged automatically.)

I though the changes deserve separate review; indeed if some of the others PRs is not OK, this one would be affected / rebased.

That being said, I think that the changes are relatively minor and if you agree on this we should be able to move forward.

[I'm gonna rebase your lazy printing patch btw so it doesn't get stuck more time]

**Comment by ejgallego** [comment]
> I'm not very happy to see Metasyntax moved to parsing, at it also deals with constrexpr-related stuff, but apart from that I support this PR. We'll find a way to clean Metasyntax afterwards.

I am not sure I understand what you mean here. Currently metasyntax basically deals with modifying the parser, so I think this is the proper place.

In fact, I did this patch moving the thing long time ago, but given that it was just moving for the sake of moving I didn't pull it out my hat until I had a real need for it.

**Comment by ppedrot** [comment]
> I am not sure I understand what you mean here. Currently metasyntax basically deals with modifying the parser, so I think this is the proper place.

Not only. Metasyntax does a lot of things, that are currently mixed together. From a cursory glance:
- Extension of the parser indeed
- Interpretation of vernacular notations
- Computation of printing representations ("formats")
- Definition of libstack objects related to notations

I don't think all of this should live in parsing, definitely not the last item at least.

**Comment by ejgallego** [comment]
Interesting list.

> Interpretation of vernacular notations
> Computation of printing representations ("formats")

Indeed parsing/printing of notations could be factored outside, and a better datatype used, however I think this is low priority and things are too coupled to the design of the parsing rules to split easily.

> Definition of libstack objects related to notations

Umm, not so clear where you would put these, without a large refactoring. Maybe it would be better to start refactoring the parser state management a bit first?

**Comment by herbelin** [comment]
Not enthousiastic either at moving `metasyntax.ml` outside of `vernac`. It is really about the vernac interpretation of notation-related commands.

**Comment by ejgallego** [comment]
> Not enthousiastic either at moving metasyntax.ml outside of vernac. It is really about the vernac interpretation of notation-related commands.

Well, it really looks like parsing specific code to me. In fact, it is called from the parser. Should we split it up?

**Comment by herbelin** [comment]
@ejgallego: there is `vernac/classes.ml` and `pretyping/typeclasses.ml`, `vernac/class.ml` and `pretyping/classops.ml`, `vernac/command.ml` and the whole type inference system. A functionality spans from high level to low level, and I don't see a problem at keeping different strata of abstraction. For instance, `metasyntax.ml` is about the internal logic of notations not about the parsing itself. In particular, it is mainly independent of the effective parser we may use. Even the extension of the parser properly speaking is not done in `metasyntax.ml` but rather in `egramcoq.ml`.

**Comment by ejgallego** [comment]
@herbelin, personally I have a feeling that parts of metasyntax do really belong to the parser and others indeed are vernac-specific. However, a small hint about the proper placement of the file is that it can be moved to parsing without breaking anything.

I see your point however and I can see 3 possible solutions:
- Move `G_vernac` from parsing to `vernac`
- Keep parsing rules of Coq in grammar, move the neeeded small bits from `Metasyntax` to `G_vernac` itself.
- Have the grammar of Coq proper live above `vernac` [this is my least preferred option].

**Comment by ppedrot** [comment]
What is the dependency that makes Metasyntax needed in parsing?

**Comment by ppedrot** [comment]
Answering myself: the only use of Metasyntax in parsing comes from this line in `G_vernac`.
```ocaml
          Metasyntax.check_infix_modifiers l;
```
It's very easy to get rid of it, and that's a strange call to have at parsing time. I have a trivial patch that puts back metasyntax in vernac if people want so.

**Comment by ejgallego** [comment]
@ppedrot sure post the patch here and I'll integrate.

**Comment by ejgallego** [comment]
Ok, merged @ppedrot changes, now `Metasyntax` remains in its place. IMHO it should be ready to merge.

**Pull request merged**
