### PR TITLE
Document minimal ocamlfind version and make sure we test it in base switch.

### PR DESCRIPTION
**Pull request by Zimmi48**
Closes #16015.

### CODE REVIEW

**Comment by Alizter** [comment]
Looks like we have a version conflict.

**Comment by Zimmi48** [comment]
This is informative. We had to bump ocamlfind to 1.8.1 as a consequence of the OCaml bump to 4.09. I've updated the PR and added appropriate documentation. But for some reason, the `coq-core.opam` and `dune-project` files were already requesting ocamlfind 1.8.1 ever since they were created.

**Review by SkySkimmer — APPROVED** [review]
Trusting that all occurences have been found

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
