### PR TITLE
improve deprecation message for 8.16 deprecated Arith lemmas

### LINKED ISSUE #15544: minus_plus is not superseded by Nat.add_sub
#### Description of the problem
While porting to Coq master, I found that `minus_plus :  forall n m : nat, n + m - n = m`
is deprecated in favor of `Nat.add_sub: forall n m : nat, n + m - m = n` but those don't have the same type.

#### Coq Version

master

### PR DESCRIPTION
**Pull request by Alizter**
fixes #15544

### CODE REVIEW

**Comment by olaure01** [comment]
I think we should address the other similar situations from `Arith.Arith_prebase` at the same time. I can do it if you want.

**Comment by Alizter** [comment]
@olaure01 Feel free to push to this PR.

**Comment by olaure01** [comment]
@Alizter done.

**Comment by herbelin** [comment]
Assigning, as discussed in the coq call.

You both are happy with the changes, right?

Do you know if a version of @JasonGross's [script](https://gist.github.com/JasonGross/9770653967de3679d131c59d42de6d17#file-replace-notations-py) for automatic  renaming exists for these new deprecations?

**Comment by Alizter** [comment]
The changes seem fine.

I don't know if Jason's script will work here exactly, since some lemmas require a bit more work to replace. The deprecation warnings should be specific about what needs to be done now however.

**Comment by olaure01** [comment]
I think it is for sure better than the current situation.
However clearly it does not provide a completely systematic/automatic way of correcting deprecation.
A script should be feasible for one-to-one renamings (but with probably some necessary additional work on the `Require` part of files anyway).

**Comment by Alizter** [comment]
ping @herbelin

**Comment by Alizter** [comment]
@herbelin ping looks like we missed this

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
@coqbot: merge now

(Sorry, I missed it)

**Pull request merged**
