### PR TITLE
abstract_list_all: try to do less work

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize ci-fiat_crypto

**Comment by SkySkimmer** [comment]
Further minimized:
~~~coq
Axiom admit : False.
Ltac admit := abstract destruct admit.

Axiom T : nat -> Type.
Axiom n : nat.

Lemma sorted_put (m:list (T n)) : false = true.
Proof.
  destruct m eqn:?Hmm.
  all: admit.
Qed.
~~~
(fails on Qed, but `revert Hmm;admit` fails in the abstract on either subgoal)

**Comment by SkySkimmer** [comment]
This time it's https://github.com/coq/coq/blob/b7258c31fe740df94f8546f5c7865e55c1be2456/tactics/tactics.ml#L4615 and https://github.com/coq/coq/blob/b7258c31fe740df94f8546f5c7865e55c1be2456/tactics/tactics.ml#L2774-L2777

**Comment by SkySkimmer** [comment]
Top non unimath speedups
~~~
│   5.5690    4.2070   -1.3620    -24.46%     61  coq-fiat-parsers/src/Parsers/ParserFromParserADT.v.html
│  38.2790   37.2130   -1.0660     -2.78%     10  coq-fourcolor/theories/job107to164.v.html
│  29.0260   28.1380   -0.8880     -3.06%   2290  coq-perennial/src/goose_lang/logical_reln_fund.v.html
│  35.3890   34.5610   -0.8280     -2.34%     10  coq-fourcolor/theories/job190to206.v.html
│  27.9420   27.1410   -0.8010     -2.87%     10  coq-fourcolor/theories/job307to310.v.html
│  11.4060   10.6210   -0.7850     -6.88%    112  coq-fiat-parsers/src/Parsers/Refinement/SharpenedJSON.v.html
│   8.7070    7.9770   -0.7300     -8.38%   1719  coq-perennial/src/program_proof/wal/recovery_proof.v.html
│  32.3800   31.6560   -0.7240     -2.24%     10  coq-fourcolor/theories/job319to322.v.html
│  41.3320   40.6360   -0.6960     -1.68%     10  coq-fourcolor/theotries/job254to270.v.html
│  24.5680   23.8740   -0.6940     -2.82%     10  coq-fourcolor/theories/job315to318.v.html
~~~
Top hott speedup
~~~
│   3.5060    2.8770   -0.6290    -17.94%    103  coq-hott/theories/Colimits/Colimit_Pushout.v.html
~~~

**Review by SkySkimmer — COMMENTED** [review]
Code is messy, especially the Case/Case branch, but perf results on unimath are pretty good so let's open for review.
cc @ppedrot

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
github went down during the bench...
@coqbot bench

**Comment by Alizter** [comment]
Is it possible to download the packages into the opam cash instead of one by one? That way if Github goes funny during a long bench, we won't run into this situation.

**Comment by JasonGross** [comment]
> Is it possible to download the packages into the opam cache instead of one by one?

I haven't tried it, but maybe we can combine `opam install --download-only` ("Fetch the sources of the packages, but don't build or install anything.") with `opam install --skip-updates` ("When running an install, upgrade or reinstall on source-pinned packages, they are normally updated from their origin first. This flag disables that behaviour and will keep them to their version in cache. This is equivalent to setting $OPAMSKIPUPDATE.")?

**Comment by SkySkimmer** [comment]
Please discuss bench infra somewhere not this PR

**Review by ppedrot — APPROVED** [review]
This is a bit ugly but I don't know how to do it in a cleaner way. That'll be good enough then.

**Comment by ppedrot** [comment]
@SkySkimmer can you rebase to get a clean CI?

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
