### PR TITLE
Moving assert (the "Cut" rule) to new proof engine

### PR DESCRIPTION
**Pull request by herbelin**
Hi, this patch moves the `Cut` rule of the former proof engine to @aspiwack's proof engine.

For those interested in the details, the `Cut` rule supported 2×2 variants:
- from `... id:T(:=c) ... |- U` to `... |- V` and `... id:V ... |- U` (`assert` style, replacing `id`)
- from `... id:T(:=c) ... |- U` to `... id:V ... |- U` and `... |- V` (`enough` style, replacing `id`)
- from `... |- U` to `... |- V` and `... id:V |- U` (`assert` style, `id` new)
- from `... |- U` to `... id:V |- U` and `... |- V` (`enough` style, `id` new)

Not having really better to propose, I basically replicated this with the same variants and policy in the new proof engine. In particular:
- the initial goal, extended with a new declaration, remains the principal goal
- the store of the initial goal is attached to the principal goal only

I guess the last bit, `Refine` will go away with the `unifall` PR, #539. Then, `logic.ml` will basically only contain a few utility functions for moving, renaming, converting hyps, etc. We shall have to think at a new file for that, I guess.

The PR incidentally fixes a minor bug in `symmetry in H` when `H` is the oldest hypothesis of the context (see test file`ltac.v`).

It also allows `Info` on tactic `assert` and derivatives not to give an `<unknown>`.

By the way, a stupid question: why not to expose `Proofview.Goal.t`, or, at least to provide an observation `'a t -> { env : Environ.env; sigma : Evd.evar_map; concl : EConstr.constr ; self : Evar.t }`, or similar. That would save several lines of boilerplate each time we `enter`. Maybe too late now that a large part of code is rewritten with `enter`, but on the other side, we just removed the `enter` record, so, maybe not too late, in this period of heavy restructurations.

Similarly, why does `Refine.refine` takes only a `sigma` and not say also an `env`, or even a `Proofview.Goal.t`. This basically forces calls to `refine` to be embedded in calls to `enter` but then the dependency of `sigma` in `refine` is redundant. (I'm not asking a priori for a change, I just try to understand the rationale.)

### CODE REVIEW

**Comment by Zimmi48** [comment]
> provide an observation 'a t -> { env : Environ.env; sigma : Evd.evar_map; concl : EConstr.constr ; self : Evar.t }, or similar. That would save several lines of boilerplate each time we enter.

Indeed, this looks to me like a good idea to reduce the boilerplate.

> Maybe too late now that a large part of code is rewritten with enter

But would it really require rewriting any tactic already written with this boilerplate? If this is just providing an alternative, shorter way, then the transition could be smoother.

**Comment by aspiwack** [comment]
> but then the dependency of sigma in refine is redundant

I had no particular reason for not having an `env`, I guess. Though if you expect said `env` to contain the goal hypothesis, there are some composition issues to take into account as it means implicitly wrapping `env `in a `Goal.enter`. Since I expected that, most of the time, one would be calling `refine` from a `Goal.enter` already, I didn't want to impose another `Goal.enter` right inside it (though there is nothing preventing from making a helper with these two primitives combined if that's helpful).

On the other hand the `sigma` is really not redundant. If you refer to the `sigma` of the proof within a `refine` call, you will get unexpected (and undefined) behaviour. This is the reason why @ppedrot had made the `refine` call be monotonous in the `sigma`.

**Comment by ppedrot** [comment]
I've had a cursory glance at your implementation, and remembering a similar branch I have somewhere, I find your code pretty convoluted. Why do you have to define a new evar-generating primitive?

Furthermore, I think that most of the uses of the `internal_cut` tactical are nowadays useless, and would better be off rewritten from scratch depending on the call site. I understand you wanted to write a readily usable drop-off implementation, but in the long run it may be worthwhile to check whether this coffee-making primitive is still needed, and how to cleanly get rid of it.

That said, I'll support any patch that reduces the `Logic` module, so I'm not going to complain too much...

**Comment by psteckler** [comment]
@aspiwack Forgive me, but did you mean "monotonic", rather than "monotonous"? 

http://www.gingersoftware.com/english-online/spelling-book/confusing-words/monotonic-monotonous

**Comment by aspiwack** [comment]
@psteckler yes (now fixed). They are the same word in French, so I sometimes mix them up.

**Comment by herbelin** [comment]
@aspiwack: ok.

@ppedrot: I did not need `new_evar_from_context`, as `new_evar` would have been fine. I somehow introduced it as an intermediary step towards understanding what would be a possible "cleaning" step of the `new_evar` family API which I think should happen. The function `new_evar ` is for the general case of an a priori non-empty  `rel_context`. I wanted to see whether `new_evar_from_context` was a more interesting entry point for tactics than `new_evar`.

Otherwise, I'm not particularly happy with my change which I find cumbersome. I also wondered whether there could be a better organization of the basic `assert` family of tactics, but failed to find something which satisfied me. So, feel free to experiment differently. My original motivation is that I needed to modify `internal_cut` for the name warnings and I seized this opportunity to move it to the new proof engine.

**Comment by gares** [comment]
> By the way, a stupid question: why not to expose Proofview.Goal.t, or, at least to provide an observation 'a t -> { env : Environ.env; sigma : Evd.evar_map; concl : EConstr.constr ; self : Evar.t }, or similar.

This is an awesome idea.

**Comment by mattam82** [comment]
It's very easy to desynchronize the sigma in the goal with the tactic one. I'd rather move the sigma passing to a monad instead to avoid this. What do you think about another state-passing monad 'a GoalLocal = Goal.t -> 'a * Goal.t ensuring that sigma can be extended but existing bindings cannot be instantiated, hence the goal doesn't change. I think many if not most sigma-passing functions used in tactics fall into this class (primitives like this cut reimplementation are a different story though). I'm wondering if you tried something like this @aspiwack and decided not to go through.

@herbelin what's cumbersome here exactly?

**Comment by herbelin** [comment]
@mattam82: By cumbersome I meant the boilerplate I guess (the new function is 34 lines vs 20 lines for the former). And having to do a `tclEVARS` (or, at least, I did not know how to avoid one, except rewriting `clear_hyps2` as a `unit tactic`)..

**Comment by maximedenes** [comment]
@ppedrot So what should we do with this PR? Do you have improvements to suggest?

**Comment by ppedrot** [comment]
I think it's OK to merge this as a first cleaning phase, but we should be wary that this is still kind of legacy code, and that tactics using it would have to be rewritten cleanly at some point.

**Comment by aspiwack** [comment]
> I'm wondering if you tried something like this @aspiwack and decided not to go through.

The original API took a `constr Tactic.t`. Or something like that. But it proved impractical for compability with the rest of Coq. After fiddling around, trying to handle the various ways in which evars could be created, I followed a suggestion by @herbelin and simplified the API to this form. What I found is that, basically, it didn't lower guarantees because I would always use unsafe escape hatch anyway.

We have more experience in writing tactics with `refine` now. So we may very well decide that mine was an ill-advised move.

**Pull request merged**
