### PR TITLE
[backport] Fix backtracking over plugin vernac extensions

### PR DESCRIPTION
**Pull request by ejgallego**
This is a backport of #17069 , just to see how the CI is impacted, as this is quite serious bug on some UI cases.

### CODE REVIEW

**Comment by ejgallego** [comment]
@SkySkimmer this works pretty well in practice but the test-suite failure scares me:
```
failed on hypident
failed on hypident
File "./bugs/bug_17069_1.v", line 15, characters 0-14:
Error: Anomaly "Uncaught exception Not_found."
```
that happens a .vo save time it seems (line 15th).

Moreover I don't understand the evil failure in the test suite either.

Is that because I should backport some further additional PR? 

I could also have messed the backport up, will re-check when I have a minute.

**Comment by SkySkimmer** [comment]
You probably need 9710b73554fcc6dec751801e046f0aa800b50c0b too

**Comment by SkySkimmer** [comment]
It was originally in #17069 then moved to #17098 because that went in earlier

**Comment by SkySkimmer** [comment]
The evil failure is 260c93ac0b8d7001831d701d8cfd94c214f65d88

**Comment by SkySkimmer** [comment]
>that happens a .vo save time it seems (line 15th).

No it happens on line 15 ie the last command, not after it. An error at vo save time would look like the remaining obligations:
~~~
Error: Unsolved obligations when closing file /tmp/foo.v:
foo has unsolved obligations.
~~~

**Comment by ejgallego** [comment]
Thanks a lot @SkySkimmer , I will have a look into this.

Question for @SkySkimmer and the RMs (cc @Zimmi48 ) , is this PR something that would / should be considered for backporting to 8.17 ? TIA

**Comment by ejgallego** [comment]
Thanks a lot @SkySkimmer , PR updated.

Overlays would be trivial and backwards compatible I understand.

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by ejgallego** [comment]
8.17 RMs decided this is not fit for backporting, I will instead provide this fix in a custom tree. Letting the PR open for a day for CI testing.

c.f: https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Coq.20Release.208.2E17/near/326847731

**Comment by ejgallego** [comment]
CI looked pretty good, the tree is now availabe at https://github.com/ejgallego/coq/tree/v8.17%2Blsp

**Comment by ejgallego** [comment]
@coqbot run full CI

**Pull request merged**
