### PR TITLE
Split documentation of coqdoc on separate page.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

As part of the ongoing refactoring of the refman, this PR splits the documentation about coqdoc on a separate page. For now, this is the only splitting that I can do because @jfehrle's current grammar documentation improvements are basically affecting all the other chapters that would need to be split.

As explained in the [CEP](https://github.com/coq/ceps/pull/43), another PR (#11872) is going to do the same file splitting on the v8.11 branch but without any user-visible change, thanks to Sphinx's `.. include::` directive. This will avoid conflicts if any change to the doc of coqdoc needs to be backported.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@cpitclaudel Have you seen this PR? The corresponding one has already been merged in v8.11.

**Comment by cpitclaudel** [comment]
Do you think it would be worth keeping the history of that section?

**Comment by Zimmi48** [comment]
> Do you think it would be worth keeping the history of that section?

How would you manage to do that? IIUC git can recognize when files are moved but not when files are split in two. Only the largest chunk will keep its history.

**Comment by Zimmi48** [comment]
Oh sorry, I missed your comment on the other PR explaining how to do this. I'll look into this.

**Comment by Zimmi48** [comment]
Even GitHub's blame seems to work pretty well. Thanks for the advice @cpitclaudel!

**Review by cpitclaudel — APPROVED** [review]

**Pull request merged**
