### PR TITLE
Remove quote plugin

### PR DESCRIPTION
**Pull request by maximedenes**
As far as I know, this plugin is untested and barely maintained. I don't
think it has real use cases any more, so let's move it out from the repo
and see if somebody wants to take over and maintain it.

We also remove the documentation, which was telling our users to look at
ring to see an example of reification done using quote, when in fact it
wasn't using it anymore.

Based on #7890.

### CODE REVIEW

**Comment by ppedrot** [comment]
You also need to remove the `Require Import Quote` in setoid ring.

**Comment by Zimmi48** [comment]
This is definitely missing an entry in CHANGES.

> let's move it out from the repo and see if somebody wants to take over and maintain it

I don't know if I should interpret this as "let's remove it from the repo" or "let's create a new repo coq/quote and wait for a maintainer there". If that's the first, fine. If that's the second, I suggest you don't. If someone wants to maintain it externally, the right place to do so would probably be https://github.com/coq-community.

You can formulate the CHANGES entry in the following way:

> The quote plugin (https://coq.inria.fr/distrib/V8.8.0/refman/proof-engine/detailed-tactic-examples.html#quote) was removed. If some users are interested in maintaining this plugin externally, the Coq development team can provide assistance for extracting the plugin and setting up a new repository.

**Comment by maximedenes** [comment]
> You also need to remove the Require Import Quote in setoid ring.

Indeed, thanks.

> I don't know if I should interpret this as "let's remove it from the repo"

Yes, that's what I meant.

> You can formulate the CHANGES entry in the following way:

Thanks, I followed your suggestion.

**Comment by herbelin** [comment]
>  If not, @herbelin can you take care of this PR?

I can be the assignee and take care of this PR. However, I feel that some larger dialogue/consultation should be ensured for  situations such as removal of a feature. I know don't if I'm the only one to feel that, but I feel that we are working these days "extremely focussed" ("le nez dans le guidon") and in a "just-in-time" manner, maybe partly due to the amount of activity to daily deal with which leaves little time for breathing. Or maybe I'm the only one to feel that. Anyway, I shall open an issue about that within a few days so as to collect the general impression about our current working methods.

**Comment by mattam82** [comment]
I think also for Quote, which is not readily subsumed by another feature, it would be good to have a deprecation phase or make a preemptive call to users on coq-club to check if some of them do rely on it outside our CI. My guess would be that it is not the case and that in many cases reification requires more ingenuity than what Quote can provide, but better safe than sorry.

**Comment by maximedenes** [comment]
Yes, I agree that this one needs discussion. An e-mail on Coq-Club sounds good, because I'm not sure we have all the information in the team.

**Comment by JasonGross** [comment]
This is probably not what you're asking for, but if you do want to add an existing project that uses `quote` to the CI, I can add my "let's perf all the reification methods I'm aware of" project to Coq's CI.

**Comment by maximedenes** [comment]
@JasonGross I would rather be interested to know if you use it.

**Comment by JasonGross** [comment]
I have used it.  Once.  Solely for the purpose of including it in a benchmark.  (Result: it's fast, but doesn't seem to support PHOAS.)  Other than including it for benchmarking in my ITP 2018 paper, I don't/haven't used it.

**Comment by herbelin** [comment]
@jasongross: I like a lot your efficient two-lines-of-Ltac-code solution, as if there was still something to take from the good old Church's encoding of data types (extended with binders). 

I have an extra question about how to deal with foreign subterms (as e.g. a multiplication subterm in a linear arithmetic expression). Is this done by an initial phase of generalization to turn them into variables?

About `Quote`: based on the two Coq-Club answers to the removal questions, it seems clear that what should be done in the future goes by going further than what the current `Quote` plugin is doing (so eventually getting out the handkerchiefs about the latter).

(Incidentally, if I remember correctly, @PierreCorbineau had thought at how to extend `quote` with binders at some time. Don't know what were his conclusions though.)

@mattam82: Deprecation phase or not? (What is the rule in this kind of circumstances?)

**Comment by Zimmi48** [comment]
> Deprecation phase or not? (What is the rule in this kind of circumstances?)

Given that we don't really propose a replacement solution, it looks like a deprecation phase wouldn't do any good. And the similar case of the Mathematical Language was handled in the same way. If there are users out there, they can either reply to the Coq-Club thread, or take on (later) the offer in the CHANGES entry:

> If some users are interested in maintaining this plugin externally, the Coq development team can provide assistance for extracting the plugin and setting up a new repository.

In particular, if there are users and the plugin is extracted as an external package, this provides a good backward compatible solution.

**Comment by maximedenes** [comment]
Ok, so the Coq-club discussion seems to show we can safely merge this. @herbelin, are you ready to do so? If yes, I'll rebase.

**Comment by herbelin** [comment]
> Ok, so the Coq-club discussion seems to show we can safely merge this. @herbelin, are you ready to do so? If yes, I'll rebase.

I'm ready to do so.

Could you however open an issue or wiki page on the status of quoting, typically reporting about the conclusion of the Gross-Erbsen-Chlipala paper and about the coq-club discussion, so that we can feel that the future is not about providing less but instead about a vision of how to provide more and better in a simpler way?

**Comment by Zimmi48** [comment]
>Could you however open an issue or wiki page on the status of quoting, typically reporting about the conclusion of the Gross-Erbsen-Chlipala paper and about the coq-club discussion, so that we can feel that the future is not about providing less but instead about a vision of how to provide more and better in a simpler way?

@maximedenes wasn't there at ITP for @JasonGross's presentation. I don't know if he has read the paper, but if not, he might not be the most appropriate person to do a summary of the situation. Of course, this doesn't prevent opening the issue. The most competent person to do so however would be @JasonGross himself.

**Comment by herbelin** [comment]
> > Ok, so the Coq-club discussion seems to show we can safely merge this. @herbelin, are you ready to do so? If yes, I'll rebase.
> 
> I'm ready to do so.

I'm sorry, but I did not judge myself correctly. I can't press the button for removing a small plugin which does no harm (less than 10 straightforward commits for maintenance in one year), and which, even if of limited scope, has no direct replacement for what it does well.

I'm unassigning and let someone else take the responsibility.

**Comment by mattam82** [comment]
I can take it

**Comment by maximedenes** [comment]
> I can take it

Thanks, will rebase now.

**Comment by Zimmi48** [comment]
@maximedenes Build is broken.

**Comment by maximedenes** [comment]
Right, should be fixed now.

**Comment by Zimmi48** [comment]
>a small plugin which does no harm (less than 10 straightforward commits for maintenance in one year)

I wanted to react to this: it may do no harm maintenance-wise (although even this is debatable) but you must also consider the harm it does in term of wrong signal sent to our users. Coq being a widely used software many users rely on, we must be careful in choosing which plugins we make "standard" because, whether we want it or not, users will first look for solutions to their problem that are "standard". The same consideration should go, of course, in what we put in the standard library.

This is very different for coq-community, which has room to accommodate projects in various shapes, including "failed" / non-conclusive experiments. But because we don't want to send wrong signals in coq-community either, it will be the role of the editorial board to put forward the projects / packages that are deemed the most valuable to the users, either because they are good packages to rely on, or for documentation purposes.

**Comment by herbelin** [comment]
> I wanted to react to this: it may do no harm maintenance-wise (although even this is debatable) but you must also consider the harm it does in term of wrong signal sent to our users.

I agree with this, but removing the plugin per se does not help. What would help is either to provide a good standard solution (even more that it would probably be only a few hours of work based on the conclusion of the discussion with @jasongross on coq-club) or to communicate about the limitations of `Quote` and about what to recommend. Note that I have my own opinion on `Quote` but I would be glad to read a factual justification of why `Quote` would be a "failure" or a "non-conclusive experience" or a "bad signal" which deserves to be removed (in particular the message from @tchajed on coq-club is talking about limitations; the message from @jwiegley I must confess I didn't understand well what it meant).

And of course, the same considerations apply to many components of Coq.

**Comment by Zimmi48** [comment]
I believe it's better not to provide any standard solution to a given problem rather than to provide an half-baked one. Of course if the plugin actually had some users to whom it was useful and some other users thought it was too limited, then it would make sense to keep it and to document its limitations better, but the conclusion of the Coq-Club thread seems rather to be that everyone who tried to use it ended up not being satisfied by it.

**Comment by herbelin** [comment]
And yet, Coq is full of half-baked solutions...

Anyway, my own experience with `Quote` is not only that it is limited but that the approach does not scale. It is unrealistic to be able to capture all possible forms of an interpretation function.

Can you imagine my suffering at seeing so many nice ideas which we could implement (like the extended `pattern` we were talking about with @jasongross) but no time to implement them!

**Comment by Zimmi48** [comment]
>Can you imagine my suffering at seeing so many nice ideas which we could implement (like the extended pattern we were talking about with @JasonGross) but no time to implement them!

I do. I feel this too. One thing I'd like us to get better at is taking the time to explain these ideas and advertise them to potential contributors. But even this takes time!

**Comment by Zimmi48** [comment]
@maximedenes The doc build is still failing:

```
/builds/coq/coq/doc/sphinx/proof-engine/tactics.rst:4184:undefined label: quote (if the link has no caption the label must precede a section header)
```

**Review by gares — APPROVED** [review]

**Review by herbelin — COMMENTED** [review]
@mattam82: as agreed, I let you take it.

**Comment by Zimmi48** [comment]
@maximedenes This PR has been waiting for a trivial fix for more than a month.

**Review by Zimmi48 — APPROVED** [review]

**Comment by maximedenes** [comment]
Ok, no action is happening here, I'm not going to rebase for months again. And I don't need this patch.

**Comment by Zimmi48** [comment]
Closing just because @mattam82 hasn't merged in the few days you have given him since the rebase? Shall I remind you that before this, it had been waiting for a trivial fix from you for more than one month? I think you are being unfair by saying this:

>no action is happening here, I'm not going to rebase for months again

**Comment by Zimmi48** [comment]
FTR rebasing this was completely trivial. You're welcome.

**Comment by maximedenes** [comment]
> I think you are being unfair

Oh sorry, there was absolutely no judgement in my message. It's just that I don't really need the patch, so just the overhead of monitoring it in my list is significant. Also it seems to have introduced some tension with @herbelin, so probably not worth it.

Sorry for not having elaborated in the previous message.

**Comment by mattam82** [comment]
Sorry if this wasn't clear, I was monitoring it for the rebase to happen as well...

**Comment by maximedenes** [comment]
> I get it. Though in this case, given the discussion that happened, the announcement on Coq-Club, the response of users, the fact that we generally need to reduce our maintenance overhead, and the fact that it's just one merge script run away, I think it should still be merged. There is no reason why this should be in 8.9 so I'll push once more to move the CHANGES entry. Then, I'll merge early next week if no more comments (taking over from @mattam82 who seems to be too busy).

Ok, sounds good thanks. I went through my entire list of stall PRs, maybe I was a bit too quick on this one indeed.

> Sorry if this wasn't clear, I was monitoring it for the rebase to happen as well...

Ah ok, sorry for the miscommunication then.

**Comment by Zimmi48** [comment]
You mean mtac2? Yes, unrelated but it should have been fixed now. Restarting.

**Comment by maximedenes** [comment]
@mattam82 ping

**Comment by Zimmi48** [comment]
>@mattam82 ping

I said I would merge this PR on Monday, but @mattam82 feel free to go ahead and merge this before since you were the one initially planning to do so.

**Comment by maximedenes** [comment]
> I said I would merge this PR on Monday

Sorry, but why not now?

**Pull request merged**
