### PR TITLE
Pass some files to strict focusing mode

### PR DESCRIPTION
**Pull request by SkySkimmer**
continuation of https://github.com/coq/coq/pull/9386

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Didn't review carefully every single file but from a random sample it looks OK.

**Comment by SkySkimmer** [comment]
There was some stuff left on my local disk.
You can merge if you want, have a look at the new commits and let CI run though (we may need to add a compat Require Reals to nsatz)

**Comment by SkySkimmer** [comment]
That should be the whole stdlib (except ssr because ssr has its own style)

**Comment by Zimmi48** [comment]
If the whole stdlib except SSR passes, can we add a flag when building it so that this is checked and doesn't regress?

**Pull request merged**
