### PR TITLE
refactor: micro optimize Hashset.repr

### PR DESCRIPTION
**Pull request by rgrinberg**
Remove 5 checks from the happy path

Binding to `caml_weak_get` is a little questionable, but this check seems more expensive than the rest.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1872769945

**Comment by ppedrot** [comment]
Hashconsing is pretty sensitive in Coq, but we're doing it wrong. (We're doing weird things with some recursive types, for instance. Don't stare too much at it.) Hopefully this gives a net speedup.

**Comment by rgrinberg** [comment]
Am I misreading the benchmarks or did removing bound checks actually made things slower?

**Comment by ppedrot** [comment]
No, this is within noise range. Most devs have a noise range around 1% but some are more noisy, e.g. it's not uncommon for coqprime to reach a 3% noise.

**Comment by ppedrot** [comment]
Per-line diff doesn't show anything interesting.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Let's merge, I don't think this can hurt.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
