### PR TITLE
Backport fix #8121: anomalies in native_compute with let and evars.

### LINKED ISSUE #8121: anomalies in native_compute with let and evars
#### Version

Coq 8.8

#### Description of the problem

Similarly to #8119, native compilation behave wrongly on evars.

### PR DESCRIPTION
**Pull request by ppedrot**
Backport of #8124.

### CODE REVIEW

**Comment by Zimmi48** [comment]
The changes to the `.mli` are still there though, aren't they?

**Comment by Zimmi48** [comment]
>Do we make any promise regarding binary compatibility of object files between minor versions?

We usually try to preserve this as well yes (we don't usually bump magic numbers).

**Comment by ppedrot** [comment]
I've pushed an mli-compatible backport.

**Review by Zimmi48 — APPROVED** [review]
Thanks!

**Pull request merged**
