### PR TITLE
add deprecation warnings to Numbers.Cyclic.ZModulo.ZModulo

### PR DESCRIPTION
**Pull request by andres-erbsen**
Warnings as @proux01 requested in https://github.com/coq/coq/pull/17258#issuecomment-1486710696; deprecation #16914; full ci from february https://github.com/coq/coq/pull/17258#issuecomment-1433009020.

### CODE REVIEW

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
Great, let's rerun the CI just to be on the safe side and merge.

@coqbot run ci now

**Comment by proux01** [comment]
@coqbot run full ci now

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
Jasmin also fails on master https://github.com/coq/coq/runs/13441313603

**Comment by proux01** [comment]
Yes, it's an issue upstream https://github.com/coq/coq/pull/17595#issuecomment-1545943800 let's merge.

@coqbot merge now

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
