### PR TITLE
Fixing an amusing small bug in parsing decimal numbers in R

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:**  bug fix

Parsing `1.5_%R` was wrongly interpreted as `0.15` due to miscounting the number of digits in the decimal part.

```
Require Import Reals.Rdefinitions.
Check 1.5_%R.
(* 15e-2%R *)
```
- [X] Added / updated test-suite

### CODE REVIEW

**Comment by ppedrot** [comment]
Is the real syntax documented somewhere? I don't find it in the refman.

**Comment by proux01** [comment]
The parser for reals is specific but the syntax is not, they are numerals as described in https://coq.inria.fr/refman/language/gallina-specification-language.html#lexical-conventions

**Review by proux01 — APPROVED** [review]
I'm the one who introduced this bug, thanks for fixing it!

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@herbelin isn't this supposed to target Coq master instead?

**Comment by herbelin** [comment]
> @herbelin isn't this supposed to target Coq master instead?

The fix for master was in #11703 (reworking of NumTok), but, indeed, the PR could also target master and #11703 be combined with the fix. One reason I made it for 8.11 is that the fix is somehow quick and dirty. But if we consider that #11703 will anyway come afterwards, that'd not be a problem.

The patch actually directly applies to master so maybe can you merge it to master yourself?

Note in passing: the bug was found by @proux01 while reviewing #11703.

**Comment by ppedrot** [comment]
OK, I think I'll rebase this on master, merge it there, and backport it to 8.11 then.

**Pull request merged**
