### PR TITLE
[build] Move core OCaml libraries under `core`

### PR DESCRIPTION
**Pull request by ejgallego**
As discussed in the Coq Call, this is a step towards #6137 .

This is the most painful step to do, but still that issue is not
closed, as we can hope for a few other files at root to go away, such
as the makefiles, the .opam files, `install.sh`, the `user-contrib`
directory, and likely `coqpp`, which could be placed under `tools`.

We may also move `plugins` once #14059 lands in main.

[sorry for the review spam in advance]

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
There is a notable risk that this will make backporting stuff to `v8.14` more painful, so maybe the right time to merge this would be just before the `v8.15` cutoff date.

**Comment by ejgallego** [comment]
> There is a notable risk that this will make backporting stuff to `v8.14` more painful, so maybe the right time to merge this would be just before the `v8.15` cutoff date.

Sure, no problem in waiting.

**Comment by Alizter** [comment]
There are 30 or so whitespace changes here also. Since this is such a massive change, it's easy for these to fly under the radar. Are these intended?

**Comment by ejgallego** [comment]
> There are 30 or so whitespace changes here also. Since this is such a massive change, it's easy for these to fly under the radar. Are these intended?

That's the post-commit hook cleaning up stray end-of-file newlines. I'd say there are OK.

I would go much further and impose ocamlformat in all the codebase, but I'm alone here :=

**Comment by Alizter** [comment]
>I would go much further and impose ocamlformat in all the codebase, but I'm alone here :=

Right but that's a different issue to this. I would agree that uniformity of format is something that we should have a separate discussion about however. Why do you suggest you are alone?

**Comment by Zimmi48** [comment]
> I would go much further and impose ocamlformat in all the codebase, but I'm alone here :=

Not alone. I've supported you on that one all along. But we've lost that battle.

**Comment by Zimmi48** [comment]
> There are 30 or so whitespace changes here also

I was surprised in fact that they were not more numerous. This shows that the pre-commit hook has been a great success and we've already got rid of most whitespace issues in the code base.

**Comment by herbelin** [comment]
By curiosity, why `core` and not the seemingly more standard `src`?

For the record, Coq versions 5 and 6 had ML files in subdirs of `src`. This was changed in version 7 (but I don't know the reason).

**Comment by Zimmi48** [comment]
> By curiosity, why `core` and not the seemingly more standard `src`?

Because of the `coq-core` name of the opam package (though it doesn't matches fully with its content).

**Comment by SkySkimmer** [comment]
>Because of the coq-core name of the opam package (though it doesn't matches fully with its content).

Since it doesn't actually match I think `src`is really better.

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
src is better than core

**Comment by ejgallego** [comment]
I'll try to summarize the result of today's discussion in the Coq call.

- Naming was argued, `core` vs `src`, Emilio finds `src` very generic and uninformative, and notes that few large projects use that convention anyways [gcc, linux, OCaml's core, etc...] The name `core` was chosen as the libraries there mainly correspond to what we ship in the `coq-core` package.
- The correspondence with `coq-core` is not complete anyways, as noted in the PR `plugins` `tools` and some other stuff is missing, however they could be moved. But indeed, the question of how to organize the source code is open at this moment.
- There was a substantial discussion on organization of the project's code, there are many altenatives, Maxime was wondering about a medium / long term plan ; Emilio notes that he didn't have a long term plan into account, it was just trying to reduce clutter which some find problematic.
- The PR is not urgent, so it seems a good idea to wait and think a bit about how to organize Coq's source code; many possibilities exist; Maxime would like to see some use cases.
- Splitting on "hard" packages is not so easy due to test-suite, also we lack motivation; the current soft split seems nice.
- Some discussion about IDEs had place; we noted that PG is maintained well, however indeed it is not using a nice protocol.

So based on the above, let's reflect about this a bit more, and hopefully discuss at some point. Moving the milestone.

Now, on a personal level, these are some of my thoughts:
- I'd like to see coqide move to is own project, just as a matter of issue handling etc.... I am not so afraid of version mismatch in the sense that we break the protocol very rarely, so still it should be possible to use a decoupled coqide
- coq-core could become a pure library package, for example it wouldn't make sense for `document-manager` to depend on coqc / coqdoc etc... [or maybe yes?] Also, if we are going to do a Coq 9 project, we'd like to have a well defined self-contained Coq 8 setup. For example, we could well have a setup where we have `core-v8` and `core-v9`.
- Whether the clutter in the root dir is a problem, that's indeed open; I dunno.

**Comment by Alizter** [comment]
@SkySkimmer @ejgallego will this make 8.15?

**Comment by Zimmi48** [comment]
No, this was retargeted for 8.16 already (because after discussing the name of the new folder in a Coq Call, we came to the conclusion reported above, basically that we want to know before deciding the name if the plan is to eventually have a match between the contents of `coq-core` and of `core/` and with what inside).

**Pull request closed without merging**
