### PR TITLE
Fixing yet a source of dependency on alphabetic order in unification.

### LINKED ISSUE #7256: Yet another source of dependency on alphabetic order in unification
#### Description of the problem

In the following examples, the return clause is not resolved the same for the two calls to `refine`:
```
Lemma foo (n1 n2: nat) (e: n1 = n2) : e = e.
refine (match e as a in _ = b return _ with refl_equal => _ end).
(* gives "eq_refl = eq_refl" *)
Undo 1.
refine (match e as z in _ = y return _ with refl_equal => _ end).
(* gives "e = e" *)
```
This is observable since version 8.4. Fix coming.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

Fixes #7256, refining c24bcae8 (PR #924) and 6304c843:
- c24bcae8 fixed the order in the heuristic governed by the `choose` flag
- 6304c843 improved the order by preferring projections

There remained a dependency in the alphabetic order in selecting unification candidates. This PR fixes it by radically changing the representation of the substitution to invert, using a map indexed on the rank in the signature rather than on the name of the variable. Note that more could be done to use numbers further, e.g. for representing aliases (but not a priority at the moment).

~~Added note: The fix seems to break things elsewhere. To be investigated.~~ ~~This PR now depends on PR #7274 for the compilation of the test-suite.~~ (Updated 28 July 2018)

### CODE REVIEW

**Comment by herbelin** [comment]
@mattam82: is it asking you a lot to review this PR considering your schedule?

**Comment by ppedrot** [comment]
#7274 has been merged, can you rebase @herbelin?

**Review by mattam82 — APPROVED** [review]
Looks good to me. Removing the choose function and rather returning the ordered list of possible projections makes the algorithm much clearer I think. I suppose the Notations.out change is unrelated right?

**Comment by herbelin** [comment]
> I suppose the Notations.out change is unrelated right?

It is not unrelated. This was a case where the inference of the return predicate was dependent on the names of variables. The change in `Notations.out` reflects what is the canonical way to infer the predicate, independently of how the variables are named.

I added a note in `CHANGES` to clarify the potential incompatibilities.

I also removed the UniMath overlay, since this has been merged upstream.

**Comment by herbelin** [comment]
> Are the CI failures related?

Probably. No visibility though on when I can work on it.

**Comment by herbelin** [comment]
Note in passing: `make ci-vst` on MacOS X fails. The makefile sets `$ARCH` to `Darwin` and the `.depend` targer looks for `compert/Darwin` which does not exist. Maybe setting `ARCH` manually in `dev/ci-vst.sh` would work (if ever an accepted way to proceed).

**Comment by herbelin** [comment]
Note for myself: fiat-parsers failing on a change of unification in the following example:
```coq
Goal forall n, n = 0 -> exists p, p = n /\ p = 0.
eexists ?[p]. split. rewrite H.
reflexivity.
```

**Comment by herbelin** [comment]
@ CI experts: cross-crypto has an instance of unification which depends on the ASCII order, and which this PR fixes. The incompatibility is in the submodule FCF. Is there a way to make an overlay for a submodule or do I need instead to let upstream FCF first merge the (backwards-compatible) [fix](https://github.com/herbelin/fcf/tree/master%2Bfix-coq7257-ascii-sensitive-unification) I made?

**Comment by SkySkimmer** [comment]
You can make an overlay updating the submodule but it's probably easier 
to just let them merge.

Gaëtan Gilbert

**Comment by herbelin** [comment]
@SkySkimmer: I went towards submitting a PR to FCF. If it takes too long, I'll do an overlay of cross-crypto linking to my own version of the submodule. Thanks!

**Comment by herbelin** [comment]
Finally, I made an overlay to cross-crypto to tell it which HEAD of FCF to get. Should I submit a PR to cross-crypto just for that or can I expect that cross-crypto updates the head of its submodule automatically?

**Comment by herbelin** [comment]
Overlays merged upstream. Seems ready.

**Pull request merged**
