### PR TITLE
NArith, PArith: Add facts about iter

### PR DESCRIPTION
**Pull request by Lysxia**
**Kind:** feature.

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]
LGTM!

**Comment by anton-trunov** [comment]
If there will be no objections, I'll merge tomorrow. 

/cc @herbelin

**Comment by herbelin** [comment]
LGTM too!

Otherwise, maybe adding a space between the following declarations `(f:A->B)(g:A->A)(h:B->B)`, but that's nitpicking.

**Comment by Lysxia** [comment]
Yeah that came from copy-pasting the corresponding `PArith` lemma. I added spaces just now.

**Pull request merged**
