### PR TITLE
[future] Be eager when "chaining" already resolved future values.

### PR DESCRIPTION
**Pull request by ejgallego**
The current future system is lazy when "chaining" (*) a resolved future. IMHO, it is more natural not to delay the evaluation of the mapping over an already forced future, usually the functorial rule here would be to indeed respect the previously evaluated status.

This also solves a kind of _critical_ bug in the current system. Indeed, the current code path falls back to a very unoptimized code path in `Future.split2` due to the following accumulation of
circumstances:

```
split2 x -> chain x (fun x -> fst x)

 =>

  let y = chain ~pure x (fun x -> fst x) in
  if is_over x && greedy then ignore(force ~pure y);
  y

=> [y <- Closure (fun x -> fst x)]

  ignore(force (Closure (fun x -> fst x)))

=>

  purify_future (force ~pure) (Closure (fun x -> fst x))

```
which makes the test in `purify_future` to fail provoking a totally spurious state reset operation.

This was first noted at https://sympa.inria.fr/sympa/arc/coqdev/2016-02/msg00081.html , and possibly related to https://coq.inria.fr/bugs/show_bug.cgi?id=5382

We fix this problem by making chaining eager, but other solutions would be possible. Given that the main user of `chain` is `split2` which wants to do `snd/fst`, I recommend this solution.

The difference in calls to `unfreeze_state` is dramatic:
```
| File                                   | Freeze Calls After | Freeze Calls Before |
|----------------------------------------+--------------------+---------------------|
| theories/Init/Notations.v              |                  0 |                   0 |
| theories/Init/Logic.v                  |                 57 |                 614 |
| theories/Init/Datatypes.v              |                 13 |                 132 |
| theories/Init/Logic_Type.v             |                  7 |                  57 |
| theories/Init/Specif.v                 |                  5 |                  35 |
| theories/Init/Nat.v                    |                  0 |                   0 |
| theories/Init/Peano.v                  |                 22 |                 264 |
| theories/Init/Wf.v                     |                  8 |                  89 |
| theories/Init/Tactics.v                |                  2 |                  24 |
| theories/Init/Tauto.v                  |                  0 |                   0 |
| theories/Init/Prelude.v                |                  0 |                   0 |
| Bool/Bool.v                            |                104 |                1220 |
| Program/Basics.v                       |                  0 |                   0 |
| Classes/Init.v                         |                  0 |                   0 |
| Program/Tactics.v                      |                  0 |                   0 |
| Relations/Relation_Definitions.v       |                  0 |                   0 |
| Classes/RelationClasses.v              |                 21 |                 341 |
| Classes/Morphisms.v                    |                 47 |                 689 |
| Classes/CRelationClasses.v             |                 18 |                 245 |
| Classes/CMorphisms.v                   |                 50 |                 587 |
| Classes/Morphisms_Prop.v               |                  3 |                 127 |
| Classes/Equivalence.v                  |                  6 |                 105 |
| Classes/SetoidTactics.v                |                  0 |                   0 |
| Setoids/Setoid.v                       |                  4 |                  33 |
| Structures/Equalities.v                |                  8 |                  93 |
| Relations/Relation_Operators.v         |                  0 |                   0 |
| Relations/Operators_Properties.v       |                 35 |                 627 |
| Relations/Relations.v                  |                  2 |                  24 |
| Structures/Orders.v                    |                 12 |                 148 |
| Numbers/NumPrelude.v                   |                  0 |                   0 |
| Structures/OrdersTac.v                 |                 13 |                 234 |
| Structures/OrdersFacts.v               |                 73 |                 931 |
| Structures/GenericMinMax.v             |                 82 |                1294 |
| Numbers/NatInt/NZAxioms.v              |                  0 |                   0 |
| Numbers/NatInt/NZBase.v                |                  7 |                  87 |
| Numbers/NatInt/NZAdd.v                 |                 14 |                 168 |
| Numbers/NatInt/NZMul.v                 |                 12 |                 144 |
| Logic/Decidable.v                      |                 28 |                 336 |
| Numbers/NatInt/NZOrder.v               |                 81 |                1174 |
| Numbers/NatInt/NZAddOrder.v            |                 24 |                 288 |
| Numbers/NatInt/NZMulOrder.v            |                 46 |                 552 |
| Numbers/NatInt/NZParity.v              |                 35 |                 420 |
| Numbers/NatInt/NZPow.v                 |                 29 |                 348 |
| Numbers/NatInt/NZSqrt.v                |                 54 |                 673 |
| Numbers/NatInt/NZLog.v                 |                 64 |                 797 |
| Numbers/NatInt/NZDiv.v                 |                 49 |                 588 |
| Numbers/NatInt/NZGcd.v                 |                 36 |                 432 |
| Numbers/NatInt/NZBits.v                |                  0 |                   0 |
| Numbers/Natural/Abstract/NAxioms.v     |                  0 |                   0 |
| Numbers/NatInt/NZProperties.v          |                  0 |                   0 |
| Numbers/Natural/Abstract/NBase.v       |                 14 |                 177 |
| Numbers/Natural/Abstract/NAdd.v        |                  6 |                  72 |
| Numbers/Natural/Abstract/NOrder.v      |                 29 |                 349 |
| Numbers/Natural/Abstract/NAddOrder.v   |                  5 |                  60 |
| Numbers/Natural/Abstract/NMulOrder.v   |                  8 |                  96 |
| Numbers/Natural/Abstract/NSub.v        |                 36 |                 432 |
| Numbers/Natural/Abstract/NMaxMin.v     |                 18 |                 216 |
| Numbers/Natural/Abstract/NParity.v     |                  4 |                  48 |
| Numbers/Natural/Abstract/NPow.v        |                 26 |                 312 |
| Numbers/Natural/Abstract/NSqrt.v       |                  9 |                 108 |
| Numbers/Natural/Abstract/NLog.v        |                  0 |                   0 |
| Numbers/Natural/Abstract/NDiv.v        |                 50 |                 600 |
| Numbers/Natural/Abstract/NGcd.v        |                 14 |                 168 |
| Numbers/Natural/Abstract/NLcm.v        |                 29 |                 348 |
| Numbers/Natural/Abstract/NBits.v       |                168 |                2016 |
| Numbers/Natural/Abstract/NProperties.v |                  0 |                   0 |
| Arith/PeanoNat.v                       |                 77 |                 990 |
| Arith/Le.v                             |                  2 |                  57 |
| Arith/Lt.v                             |                 14 |                 168 |
| Arith/Plus.v                           |                 20 |                 269 |
| Arith/Gt.v                             |                 17 |                 248 |
| Arith/Minus.v                          |                 11 |                 132 |
| Arith/Mult.v                           |                 14 |                 168 |
| Arith/Between.v                        |                 19 |                 299 |
| Logic/EqdepFacts.v                     |                 26 |                 539 |
| Logic/Eqdep_dec.v                      |                 13 |                 361 |
| Arith/Peano_dec.v                      |                  3 |                  26 |
| Arith/Compare_dec.v                    |                 35 |                 360 |
| Arith/Factorial.v                      |                  3 |                  36 |
| Arith/EqNat.v                          |                 10 |                 111 |
| Arith/Wf_nat.v                         |                 18 |                 173 |
| Arith/Arith_base.v                     |                  0 |                   0 |
| Numbers/BinNums.v                      |                  0 |                   0 |
| PArith/BinPosDef.v                     |                  0 |                   0 |
| PArith/BinPos.v                        |                229 |                2810 |
| NArith/BinNatDef.v                     |                  0 |                   0 |
| NArith/BinNat.v                        |                107 |                1330 |
| PArith/Pnat.v                          |                 51 |                 688 |
| NArith/Nnat.v                          |                 30 |                 360 |
| setoid_ring/Ring_theory.v              |                 43 |                 756 |
| Lists/List.v                           |                195 |                2908 |
| setoid_ring/BinList.v                  |                  6 |                  90 |
| Numbers/Integer/Abstract/ZAxioms.v     |                  0 |                   0 |
| Numbers/Integer/Abstract/ZBase.v       |                  3 |                  36 |
| Numbers/Integer/Abstract/ZAdd.v        |                 46 |                 552 |
| Numbers/Integer/Abstract/ZMul.v        |                  8 |                  96 |
| Numbers/Integer/Abstract/ZLt.v         |                 21 |                 252 |
| Numbers/Integer/Abstract/ZAddOrder.v   |                 45 |                 543 |
| Numbers/Integer/Abstract/ZMulOrder.v   |                 24 |                 288 |
| Numbers/Integer/Abstract/ZMaxMin.v     |                 22 |                 264 |
| Numbers/Integer/Abstract/ZSgnAbs.v     |                 41 |                 492 |
| Numbers/Integer/Abstract/ZParity.v     |                  6 |                  72 |
| Numbers/Integer/Abstract/ZPow.v        |                 10 |                 120 |
| Numbers/Integer/Abstract/ZDivTrunc.v   |                 68 |                 816 |
| Numbers/Integer/Abstract/ZDivFloor.v   |                 70 |                 840 |
| Numbers/Integer/Abstract/ZGcd.v        |                 29 |                 348 |
| Numbers/Integer/Abstract/ZLcm.v        |                 50 |                 600 |
| Numbers/Integer/Abstract/ZBits.v       |                205 |                2460 |
| Numbers/Integer/Abstract/ZProperties.v |                  0 |                   0 |
| ZArith/BinIntDef.v                     |                  0 |                   0 |
| ZArith/BinInt.v                        |                212 |                2839 |
|----------------------------------------+--------------------+---------------------|
```

(*) I would call it `Future.map` better than chain.

### CODE REVIEW

**Comment by ejgallego** [comment]
If this fix doesn't create problems, it should be IMHO also merged into 8.6

**Comment by silene** [comment]
I don't know this code at all, but isn't it what `greedy` is supposed to mean? It seems like your code would force an evaluation even when `greedy` is false, which seems quite unnatural.

**Comment by ppedrot** [comment]
@silene Doesn't this simply mean that the first chain function should also take a `greedy` argument to perform this optimization when possible?

**Comment by ejgallego** [comment]
First, `greedy` is never called with `false` in the current implementation in Coq, so it always set to true.

Second, if you look at the code you will see that indeed it has no effect. In the future, things never are what they seem.

Third, in current state rework, `greedy` and `pure` are gone (`greedy` was not used anyways, `pure` was used only once and is IMHO a layering violation). IMHO, this is the right thing to do.

**Comment by ejgallego** [comment]
Even if it is somehow becoming clear in my head, I am still having a hard time trying to explain how things are interconnected between all the layers, so please bear with me if I write nonsense.

**Comment by ejgallego** [comment]
Unfortunately this change seems to have a real performance impact in code that is using lots of modules, I need to investigate that part, this may indeed be a hard problem to solve with the current framework.

The main question for me now if this changes the profile @ppedrot did for bug 5382

**Comment by ejgallego** [comment]
Well, I keep getting inconsistent performance numbers. Here is some data on state freeze before and after the patch:
```
| File                                   | Freeze Calls After | Freeze Calls Before |
|----------------------------------------+--------------------+---------------------|
| theories/Init/Notations.v              |                  0 |                   0 |
| theories/Init/Logic.v                  |                 57 |                 614 |
| theories/Init/Datatypes.v              |                 13 |                 132 |
| theories/Init/Logic_Type.v             |                  7 |                  57 |
| theories/Init/Specif.v                 |                  5 |                  35 |
| theories/Init/Nat.v                    |                  0 |                   0 |
| theories/Init/Peano.v                  |                 22 |                 264 |
| theories/Init/Wf.v                     |                  8 |                  89 |
| theories/Init/Tactics.v                |                  2 |                  24 |
| theories/Init/Tauto.v                  |                  0 |                   0 |
| theories/Init/Prelude.v                |                  0 |                   0 |
| Bool/Bool.v                            |                104 |                1220 |
| Program/Basics.v                       |                  0 |                   0 |
| Classes/Init.v                         |                  0 |                   0 |
| Program/Tactics.v                      |                  0 |                   0 |
| Relations/Relation_Definitions.v       |                  0 |                   0 |
| Classes/RelationClasses.v              |                 21 |                 341 |
| Classes/Morphisms.v                    |                 47 |                 689 |
| Classes/CRelationClasses.v             |                 18 |                 245 |
| Classes/CMorphisms.v                   |                 50 |                 587 |
| Classes/Morphisms_Prop.v               |                  3 |                 127 |
| Classes/Equivalence.v                  |                  6 |                 105 |
| Classes/SetoidTactics.v                |                  0 |                   0 |
| Setoids/Setoid.v                       |                  4 |                  33 |
| Structures/Equalities.v                |                  8 |                  93 |
| Relations/Relation_Operators.v         |                  0 |                   0 |
| Relations/Operators_Properties.v       |                 35 |                 627 |
| Relations/Relations.v                  |                  2 |                  24 |
| Structures/Orders.v                    |                 12 |                 148 |
| Numbers/NumPrelude.v                   |                  0 |                   0 |
| Structures/OrdersTac.v                 |                 13 |                 234 |
| Structures/OrdersFacts.v               |                 73 |                 931 |
| Structures/GenericMinMax.v             |                 82 |                1294 |
| Numbers/NatInt/NZAxioms.v              |                  0 |                   0 |
| Numbers/NatInt/NZBase.v                |                  7 |                  87 |
| Numbers/NatInt/NZAdd.v                 |                 14 |                 168 |
| Numbers/NatInt/NZMul.v                 |                 12 |                 144 |
| Logic/Decidable.v                      |                 28 |                 336 |
| Numbers/NatInt/NZOrder.v               |                 81 |                1174 |
| Numbers/NatInt/NZAddOrder.v            |                 24 |                 288 |
| Numbers/NatInt/NZMulOrder.v            |                 46 |                 552 |
| Numbers/NatInt/NZParity.v              |                 35 |                 420 |
| Numbers/NatInt/NZPow.v                 |                 29 |                 348 |
| Numbers/NatInt/NZSqrt.v                |                 54 |                 673 |
| Numbers/NatInt/NZLog.v                 |                 64 |                 797 |
| Numbers/NatInt/NZDiv.v                 |                 49 |                 588 |
| Numbers/NatInt/NZGcd.v                 |                 36 |                 432 |
| Numbers/NatInt/NZBits.v                |                  0 |                   0 |
| Numbers/Natural/Abstract/NAxioms.v     |                  0 |                   0 |
| Numbers/NatInt/NZProperties.v          |                  0 |                   0 |
| Numbers/Natural/Abstract/NBase.v       |                 14 |                 177 |
| Numbers/Natural/Abstract/NAdd.v        |                  6 |                  72 |
| Numbers/Natural/Abstract/NOrder.v      |                 29 |                 349 |
| Numbers/Natural/Abstract/NAddOrder.v   |                  5 |                  60 |
| Numbers/Natural/Abstract/NMulOrder.v   |                  8 |                  96 |
| Numbers/Natural/Abstract/NSub.v        |                 36 |                 432 |
| Numbers/Natural/Abstract/NMaxMin.v     |                 18 |                 216 |
| Numbers/Natural/Abstract/NParity.v     |                  4 |                  48 |
| Numbers/Natural/Abstract/NPow.v        |                 26 |                 312 |
| Numbers/Natural/Abstract/NSqrt.v       |                  9 |                 108 |
| Numbers/Natural/Abstract/NLog.v        |                  0 |                   0 |
| Numbers/Natural/Abstract/NDiv.v        |                 50 |                 600 |
| Numbers/Natural/Abstract/NGcd.v        |                 14 |                 168 |
| Numbers/Natural/Abstract/NLcm.v        |                 29 |                 348 |
| Numbers/Natural/Abstract/NBits.v       |                168 |                2016 |
| Numbers/Natural/Abstract/NProperties.v |                  0 |                   0 |
| Arith/PeanoNat.v                       |                 77 |                 990 |
| Arith/Le.v                             |                  2 |                  57 |
| Arith/Lt.v                             |                 14 |                 168 |
| Arith/Plus.v                           |                 20 |                 269 |
| Arith/Gt.v                             |                 17 |                 248 |
| Arith/Minus.v                          |                 11 |                 132 |
| Arith/Mult.v                           |                 14 |                 168 |
| Arith/Between.v                        |                 19 |                 299 |
| Logic/EqdepFacts.v                     |                 26 |                 539 |
| Logic/Eqdep_dec.v                      |                 13 |                 361 |
| Arith/Peano_dec.v                      |                  3 |                  26 |
| Arith/Compare_dec.v                    |                 35 |                 360 |
| Arith/Factorial.v                      |                  3 |                  36 |
| Arith/EqNat.v                          |                 10 |                 111 |
| Arith/Wf_nat.v                         |                 18 |                 173 |
| Arith/Arith_base.v                     |                  0 |                   0 |
| Numbers/BinNums.v                      |                  0 |                   0 |
| PArith/BinPosDef.v                     |                  0 |                   0 |
| PArith/BinPos.v                        |                229 |                2810 |
| NArith/BinNatDef.v                     |                  0 |                   0 |
| NArith/BinNat.v                        |                107 |                1330 |
| PArith/Pnat.v                          |                 51 |                 688 |
| NArith/Nnat.v                          |                 30 |                 360 |
| setoid_ring/Ring_theory.v              |                 43 |                 756 |
| Lists/List.v                           |                195 |                2908 |
| setoid_ring/BinList.v                  |                  6 |                  90 |
| Numbers/Integer/Abstract/ZAxioms.v     |                  0 |                   0 |
| Numbers/Integer/Abstract/ZBase.v       |                  3 |                  36 |
| Numbers/Integer/Abstract/ZAdd.v        |                 46 |                 552 |
| Numbers/Integer/Abstract/ZMul.v        |                  8 |                  96 |
| Numbers/Integer/Abstract/ZLt.v         |                 21 |                 252 |
| Numbers/Integer/Abstract/ZAddOrder.v   |                 45 |                 543 |
| Numbers/Integer/Abstract/ZMulOrder.v   |                 24 |                 288 |
| Numbers/Integer/Abstract/ZMaxMin.v     |                 22 |                 264 |
| Numbers/Integer/Abstract/ZSgnAbs.v     |                 41 |                 492 |
| Numbers/Integer/Abstract/ZParity.v     |                  6 |                  72 |
| Numbers/Integer/Abstract/ZPow.v        |                 10 |                 120 |
| Numbers/Integer/Abstract/ZDivTrunc.v   |                 68 |                 816 |
| Numbers/Integer/Abstract/ZDivFloor.v   |                 70 |                 840 |
| Numbers/Integer/Abstract/ZGcd.v        |                 29 |                 348 |
| Numbers/Integer/Abstract/ZLcm.v        |                 50 |                 600 |
| Numbers/Integer/Abstract/ZBits.v       |                205 |                2460 |
| Numbers/Integer/Abstract/ZProperties.v |                  0 |                   0 |
| ZArith/BinIntDef.v                     |                  0 |                   0 |
| ZArith/BinInt.v                        |                212 |                2839 |
|----------------------------------------+--------------------+---------------------|
```

**Comment by ppedrot** [comment]
> The main question for me now if this changes the profile @ppedrot did for bug 5382

I'm pretty sure it will. The stack traces were clear about how we kept unfreezing state to chain values. I'll try to check with your patch to be sure though.

**Comment by ppedrot** [comment]
It takes too long to see whether we gained something in the total timing yet, but I confirm that I don't see unfreezing taking half of the time on bug #5382 with your patch.

**Comment by ejgallego** [comment]
> It takes too long to see whether we gained something in the total timing yet, but I confirm that I don't see unfreezing taking half of the time on bug #5382 with your patch.

Good to know, thanks for letting me know.

It seems my previous performance testing was spurious due to server load, now I see normal performance, but we should make sure before merging this.

@matej-kosik , is it possible to test this PR with the performance suite? Thanks.

**Comment by ejgallego** [comment]
> @matej-kosik , is it possible to test this PR with the performance suite? Thanks.

I managed to do some testing in a stable server, on the travis test suite, performance seems unaffected (slight improvements but not significant)

**Comment by ppedrot** [comment]
I confirm that this patch, together with PR #475, solve the first part of bug #5382, i.e. tactics taking twice as much time as needed.

**Comment by ejgallego** [comment]
IMHO both of #475 #476 would make good 8.6.1 candidates.

**Comment by gares** [comment]
LGTM, but I need to look carefully a future.ml to be understand why it has such an impact.
Can you point me to the line that does more work on `Closure` than `Val`?

**Comment by gares** [comment]
Also, we could/should remove `~greedy`

**Comment by ejgallego** [comment]
> Also, we could/should remove ~greedy

I already have a tree doing that, will submit.

**Comment by ejgallego** [comment]
> Can you point me to the line that does more work on Closure than Val?

It is coming from the call to `split2` in `Proof_global.close_proof`.

**Comment by ejgallego** [comment]
We still have a few spurious `unfreezes`, but they are coming from the order of traversal:

```
[ndouble_install:  98 | 455 / 457 ]
Raised by primitive operation at file "stm/stm.ml", line 808, characters 22-47
Called from file "stm/stm.ml", line 2348, characters 18-33
Called from file "stm/stm.ml", line 881, characters 6-10
Called from file "stm/stm.ml", line 2376, characters 4-100
Called from file "stm/stm.ml", line 2409, characters 4-48
Called from file "stm/stm.ml", line 2419, characters 2-35
Called from file "stm/stm.ml", line 2949, characters 8-30
Called from file "toplevel/vernac.ml", line 203, characters 6-16
Called from file "lib/flags.ml", line 11, characters 15-18
Called from file "lib/flags.ml" (inlined), line 154, characters 19-41
Called from file "toplevel/vernac.ml", line 221, characters 6-87
Called from file "toplevel/vernac.ml", line 311, characters 14-48
Called from file "toplevel/vernac.ml", line 349, characters 2-13
Called from file "list.ml", line 77, characters 12-15
Called from file "toplevel/coqtop.ml", line 638, characters 6-22
Called from file "toplevel/coqtop.ml", line 662, characters 11-59
Called from file "/tmp/coqmain259ed9.ml", line 2, characters 17-31
```

**Comment by ejgallego** [comment]
@gares do you want this in trunk or in 8.6?

**Comment by ejgallego** [comment]
The way I debug this is by adding to `Stm.unfreeze_global_state`:

``` ocaml
    incr nfreeze;
    Format.eprintf "[nfreeze: %3d ]\n%!" !nfreeze;
    let cs = Printexc.get_callstack 25 in
    Printexc.print_raw_backtrace stdout cs; Pervasives.flush stdout;
....
```

**Review by gares — APPROVED** [review]
Given `greedy:true` this makes a lot of sense.

**Comment by ejgallego** [comment]
Moved to 8.6

**Comment by matejkosik** [comment]
@maximedenes 

> is it possible to test this PR with the performance suite? Thanks.

Measurements (from 3 iterations we get precision around 1%):
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┐
│                        │      user time [s]      │             CPU cycles              │           CPU instructions            │
│                        │                         │                                     │                                       │
│           package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│       coq-math-classes │  219.34  220.52 -0.54 % │  605100790816  606928681019 -0.30 % │   859710417047   859617037917 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│  coq-mathcomp-solvable │  198.65  199.15 -0.25 % │  552201915545  552114148020 +0.02 % │   828940002917   828699464550 +0.03 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│  coq-mathcomp-fingroup │   56.42   56.55 -0.23 % │  155907571141  155996588131 -0.06 % │   222303574351   222315050940 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│               coq-iris │  425.22  425.98 -0.18 % │ 1182668540148 1183839903635 -0.10 % │  1712329473618  1712404892066 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│     coq-mathcomp-field │  480.36  480.98 -0.13 % │ 1337628571922 1338085315937 -0.03 % │  2265266765062  2265132251608 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│ coq-mathcomp-character │  265.10  265.30 -0.08 % │  737575610050  738083929619 -0.07 % │  1103178538029  1103042436007 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│            coq-unimath │ 1279.60 1279.84 -0.02 % │ 3548371867578 3547283776105 +0.03 % │  5955428886862  5955719681568 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│              coq-color │  629.11  629.21 -0.02 % │ 1746288565256 1744969306336 +0.08 % │  2281181272170  2281141806453 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│           coq-compcert │  819.84  819.79 +0.01 % │ 2277544681798 2279946692545 -0.11 % │  3484697434562  3484209258278 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│        coq-fiat-crypto │ 2316.62 2316.46 +0.01 % │ 6443615619556 6443933667277 -0.00 % │ 10869507653157 10862221832922 +0.07 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│         coq-coquelicot │   68.84   68.82 +0.03 % │  190909681518  190801952995 +0.06 % │   242311803145   242272822071 +0.02 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│              coq-flocq │   51.16   51.14 +0.04 % │  141033218495  140940012808 +0.07 % │   181867180912   181855029525 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│               coq-hott │  227.82  227.66 +0.07 % │  615551338395  615277982802 +0.04 % │  1041649825566  1041665267290 -0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│               coq-corn │ 1531.68 1530.20 +0.10 % │ 4253409861284 4252345355398 +0.03 % │  6840369719390  6840351397838 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│       coq-fiat-parsers │  512.32  511.67 +0.13 % │ 1405259885319 1405661393889 -0.03 % │  2019471132767  2019408929223 +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│             coq-geocoq │ 2389.67 2385.59 +0.17 % │ 6650301323973 6638720409295 +0.17 % │ 11367621913538 11366951833349 +0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│   coq-mathcomp-algebra │  168.27  167.82 +0.27 % │  466555390362  466718115957 -0.03 % │   674015593544   674051372103 -0.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│ coq-mathcomp-ssreflect │   41.62   41.44 +0.43 % │  113274771740  113037124279 +0.21 % │   147401530541   147253466843 +0.10 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│                 coq-sf │   44.27   43.94 +0.75 % │  120586101252  120395373410 +0.16 % │   159209333188   159276449316 -0.04 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┘
```

**Comment by ejgallego** [comment]
Cool, this is consistent with what we saw.

**Comment by silene** [comment]
> Cool, this is consistent with what we saw.

I am getting confused. Wasn't this patch meant to improve performances? According to Matej's tests, there is absolutely no impact. Does that mean that Matej is not testing what is being actually impacted by this pull request?

**Comment by ppedrot** [comment]
It was meant to improve performances in very specific cases, namely scripts relying heavily on abstracting subproofs. I don't think there are a lot of such instances in the development we bench, so that it is rather reassuring that overall performance is *not* impacted.

**Comment by ejgallego** [comment]
@silene the patch is mainly a bugfix, but performance wise in this cases we are talking about a few thousand states reset vs a dozen, but time for each is negligible unless in very specific cases, and we also merged #478 which makes state unfreezing way more efficient in some cases.

The real fear was that this patch could improve some cases but make other slowers, as future are "less lazy" now. However we could find a path where the laziness is actually used. Indeed, in this aspect the future for command line compilation is a bit irrelevant as hopefully we can aim for 0 unfreezes when calling `coqc` in a linear-processing style.

**Pull request merged**
