### PR TITLE
Split github CI actions into 2 workflows + disable windows while it's broken

### PR DESCRIPTION
**Pull request by SkySkimmer**
To be able to rerun one OS without rerunning the other.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
BTW, the reason why the Windows CI fails seems to be simply because the `dev-ci` branch has been removed. Can you try to simply replace `dev-ci` with `main` and see what this gives?

**Comment by SkySkimmer** [comment]
>BTW, the reason why the Windows CI fails seems to be simply because the dev-ci branch has been removed. Can you try to simply replace dev-ci with main and see what this gives?

Still not working (different error though)

**Comment by Zimmi48** [comment]
FWIW, the first error is the following one:

```
Run .\dev\ci\platform\coq-pf-03-build.bat
Install cygwin and download, compile and install OCaml and Coq for MinGW
!!! Illegal parameter -override-dev-pkg
```

The call is done in:

https://github.com/coq/coq/blob/24a705b84a5b05e67be4b25314f11da661859839/dev/ci/platform/coq-pf-03-build.bat#L14-L24

@MSoegtropIMC The Windows CI is failing for Coq because the `dev-ci` branch of the Platform repository has been removed, and it had an `-override-dev-pkg` option that is not there in the main branch. We will need your help to fix this (but this is OK to wait until after the next Platform release to take care of this, we can disable the CI job as proposed in this PR in the meantime).

**Comment by Zimmi48** [comment]
Will merge after confirming that macOS CI passes.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : OK, I cleaned up a bit too much. What would you recommend? I don't think I still want the dev-ci branch since it is effort to maintain it.

I now have a working dev pick, but it points to master for all packages.

I guess it would make most sense to create a dedicated "ci" pick which honors the 

I guess it would make sense to create a "ci" pick which honors the -override-dev-pkg option and/or possibly also takes the overlay information for -extent=f and -extent=x. @gares started something like this in https://github.com/coq/platform/pull/44.

**Comment by Zimmi48** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
@MSoegtropIMC Indeed, I agree that reintroducing the `dev-ci` branch is not a good solution. Furthermore, we don't need to test the full extent, just Coq + CoqIDE. And we can't just test the `master` branch of Coq, we need to be able to point to a local version to be able to test PRs. So basically, we just need an option similar to `-override-dev-pkg` to define specifically where to look for the source of Coq.

**Comment by MSoegtropIMC** [comment]
OK, I will add a ci pick which at first only contains coq + coqide (f and x extents will be empty) and which honors the -override-dev-pkg flag.

In addition I would mid term like to have a pick which mimics Coq's CI. Any suggestions how these two picks should be named?

**Comment by Zimmi48** [comment]
"dev"?

**Comment by Zimmi48** [comment]
Sounds good to me.

**Comment by SkySkimmer** [comment]
Looks like I'm backporting this since it's also broken for 8.15

**Pull request merged**
