### PR TITLE
Hooks have no default value

### PR DESCRIPTION
**Pull request by SkySkimmer**
Hooks are meant to be a workaround to lack of cross-file recursive module, and as such a hook is meant to refer to 1 specific function.

Hooks with default values were either meant to be set to arbitrary functions by plugins in which case they should be refs, or the default was not actually used.

### CODE REVIEW

**Comment by ppedrot** [comment]
While I agree that hooks are not meant to be set by external users, I do think we need an API to signal that some references *are* meant to be accessed as plugins. This could just be a thin wrapper around the ref type.

**Review by ejgallego — COMMENTED** [review]
Agree with @ppedrot , this is as such is making things even worse.

**Comment by gares** [comment]
We already have refs with no wrapper used by plugins. Why these ones need a dedicated wrapper?

**Comment by SkySkimmer** [comment]
Maybe we should expose just setters instead of the whole ref? Indeed that's already how it's done for evar_conv_x

**Comment by gares** [comment]
Bah, for a trivial change we have already spent enough energy IMO.

**Comment by Zimmi48** [comment]
The whole pipeline failed because of runner failures. New attempt: @coqbot run full CI.

> Maybe we should expose just setters instead of the whole ref? Indeed that's already how it's done for evar_conv_x

This does sound more principled.

**Comment by ejgallego** [comment]
I agree that we did bikeshed on the original PR.

However this one is making an architectural change and indeed we need to be careful here, the upper layers do work on the invariant that `VernacState.freeze` will be sound (thanks to summary), and here we a just putting more refs which at some point will be abused and we will lose a lot of time debugging stuff.

Overridable stuff must be controlled in some way, having just a `ref` is unsound w.r.t. semantics of the upper layers.

**Comment by gares** [comment]
> Maybe we should expose just setters instead of the whole ref? Indeed that's already how it's done for evar_conv_x

@ppedrot @ejgallego would this work for you?

**Comment by gares** [comment]
> Maybe we should expose just setters instead of the whole ref? Indeed that's already how it's done for evar_conv_x

@ppedrot @ejgallego can this work for you? If later one wants to make a call to these APIs "taint" the summary, he can without breaking clients.

**Comment by ppedrot** [comment]
I am fine with @SkySkimmer 's solution.

**Comment by SkySkimmer** [comment]
It's an option generator so goptions

**Comment by ejgallego** [comment]
For me anything that "taints" the refs is indeed fine; so if we have problems / bugs in the future we can see how's calling the dangerous API quickly (or I can put a printf).

Other than tainting, I wouldn't lose a lot more time on this until an actual use case appears. At least myself I'm unable to anticipate how the use cases will be. For example using goptions could be fine, or totally insufficient if for example a tactic wants to dynamically override the unification ref.

**Comment by SkySkimmer** [comment]
What does "taint" mean?

**Comment by Zimmi48** [comment]
Probably means "mark as special".

**Comment by ejgallego** [comment]
> What does "taint" mean?

Taint indeed means "to pollute" , to mark as questionable. I guess it go popular in CS due to the Linux kernel having a `tainted` bit, when a non-free module was loaded [so in this case maintainers would reject any bug report that had the tainted bit set]

**Comment by SkySkimmer** [comment]
That doesn't help me understand what it's supposed to mean in the context of coq though.

Anyway let's do the setters and come back if someone actually tries to use them.

**Comment by gares** [comment]
Taint means, to me, that a system state is no more valid because a change is not recorded. If we use goptions, then the change is recorded, so we are good (undo will workbfor example).

**Comment by ejgallego** [comment]
> That doesn't help me understand what it's supposed to mean in the context of coq though.

What means in the context of Coq is updating the global state without going thru the summary, thus the main invariant of the vernacular layer is broken, and all kind of bugs can happen then.

**Comment by gares** [comment]
> If we want something user controllable we could do a wrapper around declare_interpreted_string_option_and_ref
> 
> ```ocaml
> (** Declares a user settable value (string option) with plugin extensibility.
>     Type [t] does NOT need to be marshallable.  *)
> module MakeSettable (T:sig
>     type t
> 
>     val user_name : string list
>   end) : sig
>   open T
> 
>   val get : unit -> t
>   (** Errors if never set *)
> 
>   type register
>   val register : string -> t -> register
>   (** Called at plugin link time. Registers a new value for the option with name the string. *)
> 
>   val set : register -> unit
>   (** Programmatic set, [set reg] is equivalent to [Goptions.set_string_option_value user_name reg] *)
> end
> ```

@SkySkimmer are you going for this one in the end?

**Comment by SkySkimmer** [comment]
Currently the only changed api is the stm hooks, IMO not worth developping this system for them. Exposing setters as in the current state of the pr should be fine.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
