### PR TITLE
[stm] Solve bug 5577 "STM branch name is incorrect with Time"

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by JasonGross** [comment]
Thanks!

**Comment by JasonGross** [comment]
Maybe add an output test-suite file, so this doesn't happen again?

**Comment by ejgallego** [comment]
Yup, but again I am not very willing to add tests for `-emacs`; even if not in the next release, we need to start getting used to this protocol going away at some point.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I think we should really put all these "attributes" of vernac commands as Time/Timeout/Fail... into a proper attribute field. In other words, I think we should extend the approach for the ast of terms also the the ast of commands

**Comment by ejgallego** [comment]
@gares that's an interesting idea; you also have `Local/Global/Program` etc... modifying vernacs, I have a patch somewhere trying to clean `Vernacentries` a bit but I guess it is down in the TODO list these days.

**Pull request merged**
