### PR TITLE
Cleaner README

### PR DESCRIPTION
**Pull request by clarus**
The README is converted to MarkDown for a better rendering on the GitHub landing page. It also includes the short project's description.

### CODE REVIEW

**Comment by lancejpollard** [comment]
+1

**Comment by clarus** [comment]
I ping again, in case this pull-request was forgotten.

**Comment by ppedrot** [comment]
I'm in favour. We should probably wait for Hugo's approval nonetheless.

**Comment by herbelin** [comment]
Personally, I'm positive on this patch. (Looks nice to read as a pure text file and a benefit to be mechanically understanble. So this is all positive. Since we decided for being hosted on github, it is consistent to use github's lightweight markup syntax, over another syntax.)

Unless there is an urgency, we can leave the final decision to the next WG as originally planned I think.

**Comment by ppedrot** [comment]
As this will probably be never settled by a workgroup before the end of the universe, I take the responsibility of merging that one.

**Comment by clarus** [comment]
Thanks!

**Pull request merged**
