### PR TITLE
Restore compilation of the bytecode interpreter with OCaml 5.00.

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by ejgallego** [comment]
If you give me one day I can test this on the working multicore branch

**Comment by ppedrot** [comment]
@ejgallego did you have time to give it a try?

**Comment by ejgallego** [comment]
> @ejgallego did you have time to give it a try?

ocaml 5.0.0 removal of stuff is giving me pain, I can't even compile findlib so it will take a bit longer than expected [I could try with 4.12+domains but it's not the real thing anymore]

**Comment by ejgallego** [comment]
Managed to fix the toolchain and workaround Coq problems, now the patch doesn't compile:
```
/usr/bin/ld: kernel/byterun/libcoqrun_stubs.a(coq_fix_code.o): in function `coq_stat_alloc':
/home/egallego/external/coq-master/_build/default/kernel/byterun/coq_fix_code.c:36: undefined reference to `raise_out_of_memory'
collect2: error: ld returned 1 exit status
```

**Comment by ejgallego** [comment]
Ok, here's the current tree that manages to run the test suite [with native=off]

https://github.com/ejgallego/coq/tree/vm-multicore%2Bmc_10

**Comment by ejgallego** [comment]
test suite says [without unit tests as ounit is broken too]
```
FAILURES
    misc/coq_environment.sh...Error!
    complexity/impargs.v...Error! (should run faster (178 >= 100))
    complexity/pattern.v...Error! (should run faster (385 >= 165))
    complexity/pretyping.v...Error! (should run faster (300 >= 150))
```

**Comment by silene** [comment]
> now the patch doesn't compile

My bad. This is due to a bug in Multicore, which I had fixed in my local OCaml and forgotten about. I did not expect it would not have been fixed in OCaml yet. I have force-pushed a fix.

**Comment by ejgallego** [comment]
> My bad. This is due to a bug in Multicore, which I had fixed in my local OCaml and forgotten about. I did not expect it would not have been fixed in OCaml yet. I have force-pushed a fix.

No worries the fix was trivial on my side, so things seem to work; I'm a bit worried about the Ephereron part of the patch to have the rest build / run @ppedrot @silene do you know what should be done here?

https://github.com/ejgallego/coq/commit/216ae5e2570bfe1ee51e45b8d9f7fddee6e98b49#diff-1d6b3c3f6c590c988e51ec547cf9f28b0ed6d0ece71cfc6ad71cedbbc5370dabL122

**Comment by silene** [comment]
I am a bit confused. Why is this function named `memo`? It does not look like memoization to me. It looks more like a single-entry cache. Anyway, since ephemerons are now immutable, I guess the solution is just to add an indirection, that is, storing the ephemeron in a reference and overwriting with a new one instead of modifying the current one.

**Comment by ppedrot** [comment]
> It looks more like a single-entry cache

... which is a poor man's memoization, so the name is not too far-fetched. The name seems to have been picked up by Bruno Barras in c580f69cc36cc4cc908febb900a55ae751039a0c.

**Comment by ppedrot** [comment]
@ejgallego yes, just wrap this in a reference. You can even push this in master it should behave the same and the indirection is unlikely to have any cost.

**Comment by ejgallego** [comment]
I will do a pass, then the only blocker is the `set_tag` stuff, but I think we can wrap it in a conditional and thus make Coq work with OCaml trunk again.

**Comment by ppedrot** [comment]
I suggest that we should perform the 5.0 synchronization stepwise. In particular, since this PR seems to allow compiling the VM on OCaml 5.0 and is self-contained, I'd recommend merging it in a standalone way. We'll fix the other issues independently. @ejgallego are you fine with this?

**Review by ppedrot — APPROVED** [review]
Judging from the upstream changes in the OCaml bytecode evaluator, this looks legit to me.

**Comment by ejgallego** [comment]
@ppedrot I'm fine, modulo we should be careful to add this kind of PRs when we are not testing the compilation on the CI, if we don't act quickly it will bitrot.

**Comment by ppedrot** [comment]
I agree with the bitrot issue, but can we easily add OCaml 5.0 to the CI?

**Comment by ejgallego** [comment]
> I agree with the bitrot issue, but can we easily add OCaml 5.0 to the CI?

Yup, I don't see any issue doing that, we just need a couple of patches.

**Comment by ppedrot** [comment]
All right, then I recommend merging this PR now and then relatively quickly add support for OCaml 5.0 in the CI. Have you already written the small patch to remove ephemeron mutability or should I open a PR myself?

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
@coqbot merge now, unholy offspring of SkyNet.

**Comment by ejgallego** [comment]
> All right, then I recommend merging this PR now and then relatively quickly add support for OCaml 5.0 in the CI. Have you already written the small patch to remove ephemeron mutability or should I open a PR myself?

I didn't yet, please go ahead.

For the CI, this is what's needed:
- a patched findlib
- a patched Dune [but I shall release 2.9.2 this week solving this]

For Coq, we need:
- the Ephemeron patch
- the set_obj patch
- the format patch [which I'm not sure it'll be backwards compat all the way down to 4.05]

**Comment by SkySkimmer** [comment]
What's happening with format?

**Comment by ejgallego** [comment]
> What's happening with format?

All deprecated functions removed in 5.0

**Comment by ejgallego** [comment]
And the replacements where not introduced until 4.08 , so we either add compat code or raise the OCaml compiler.

Change is `pp_open_tag` -> `pp_open_stag` etc... [as seen in the patch]

**Comment by ejgallego** [comment]
@silene , multicore devs are asking about the `caml_process_pending_actions_exn` fixme, concretely:

>  We have a question about the use of a runtime functionality introduced in recent OCaml version for asynchronous callbacks, `caml_process_pending_actions_exn`
>
> Coq seems to be the only public codebase using the functionality, and multicore doesn’t implement this functionality yet. It may be a lot of refactoring of the runtime to implement this functionality. How critical is this for Coq?

**Comment by silene** [comment]
It is not critical. It is more of a quality-of-life concern. Currently, if a bytecode computation seems to go wrong, the user can just interrupt it and keep working. Once Coq is compiled with OCaml 5.0, the user better kills the whole process and restarts it, because all bets will be off.

By the way, the FIXME is on that line, but it could just have been on the definition of `Coq_alloc_small`, which is just as broken.

**Comment by kayceesrk** [comment]
Thanks, @silene and @ejgallego for the answer. CC @sadiqj.

**Comment by ejgallego** [comment]
Thanks for the feedback @silene , it seems to me that based on the comments that I've seen over the years from users, not being able to use Ctrl-C to interrupt a vm_compute operation could be indeed a dealbreaker for a few of them (cc @JasonGross may have some more insight on this)

So it seems to me a "medium severity" issue, so while not urgent, it would be nice to think of possible better workarounds; I think we are not tied to actually maintaining the current API tho, any other solution that would allow interrupt to get back to work could be adopted I think.

**Comment by JasonGross** [comment]
Yes, not being able to interrupt vm_compute without restarting the whole file would likely mean that I don't upgrade my version of OCaml.  If Coq loses this ability even on older OCaml, I probably won't upgrade Coq on projects that use the VM.  However, if you give me a flag that says "always spawn the VM in a separate process, and kill that process on Ctrl+C", I would be willing to tolerate that and the overhead of process creation in interactive mode.  (Better though would be a persistent separate process dedicated to running the VM, which is set up at the beginning and restarted on Ctrl+C.)

(The context here is that sometimes the VM might be running a computation that by accident is not expected to finish before I die, but I've already spent many minutes waiting for the file to get to this point.  Often I don't know what the slow part is interactively until I hit it, if, e.g., some change elsewhere made a function that was previously fully applied now be partially applied or have a typeclass evar that blocks reduction and blows up in the VM.)

**Comment by silene** [comment]
And just to be complete, handling signals is just one of the issues. The other is what to do with `Alloc_small`. Indeed, we pass as the last macro argument some C code that calls `caml_process_pending_actions`. Again, we do not care what the runtime performs at this point and how long it takes. We just need some way to catch any exception that might be raised.

**Pull request merged**
