### PR TITLE
Ref. Man.: Updating the current official writing of OCaml; updating Camlp4->Camlp5.

### PR DESCRIPTION
**Pull request by herbelin**
A minor PR, which was lost in the forest of #982 commits. All is in the title.

Depending on the status of the move to sphinx, this is at least relevant for 8.7.1 I guess.

### CODE REVIEW

**Comment by psteckler** [comment]
The vernacular for extraction uniformly uses "Ocaml" when it should be "OCaml". The same is true for the chapter on extraction, which doesn't use the TeX macro.

**Comment by herbelin** [comment]
Well, this is then worth a refinement of this PR. Do you want to push new commits to this PR? Or do you prefer I do it?

**Comment by psteckler** [comment]
Can push to your Github? If I can, it won't be until Monday, though.

**Comment by psteckler** [comment]
Maybe I could do a separate PR for those issues.

**Comment by herbelin** [comment]
Whatever you prefer.

**Comment by psteckler** [comment]
I'll do a separate PR, I think.

**Pull request merged**
