### PR TITLE
 proposed fix for issue #3213: extra variable m in Lt.S_pred

### PR DESCRIPTION
**Pull request by fredokun**
follow up to PR #6280

### CODE REVIEW

**Comment by Zimmi48** [comment]
Hi, thank you for contributing, but please read the contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md
In particular this:

> We recommend you create a fork of the repository on GitHub and push your changes to a new "topic branch" in that fork.

When you need to make modifications to your PR, you can just add new commits and push to your branch, or amend previous commits and force-push. Please avoid, closing a PR and reopening a new one, this does not help with the review.

(Since you pushed these changes on your master branch, please consider this branch as your "topic" branch as long at this PR is opened.)

**Comment by fredokun** [comment]
Sorry it's a small change I did not read the CONTRIBUTING.md file (next time I will).

**Review by maximedenes — DISMISSED** [review]
Something seems off: this PR contains two commits with the same message.

**Comment by Zimmi48** [comment]
Squashing the two commits with `rebase -i HEAD~2` followed by ` push -f` should solve this.

**Comment by herbelin** [comment]
As far as I know from @letouzey's work on arithmetical libraries, the file `Lt.v`, and similar files in `Arith`, are mainly compatibility files (see the `OBSOLETE` in the header). And, indeed, the proofs of the lemmas there are essentially `apply` of a generically-named lemma (e.g. `S_pred` is essentially the `Nat` instance `Nat.lt_succ_pred` of the generic arithmetical property `lt_succ_pred`).

I just browsed the library. A `Search "pos" "pred" "succ".` gives:
```coq
Nat.succ_pred_pos: forall n : nat, (0 < n)%nat -> S (Nat.pred n) = n
```
So, the lemma is already there. What is missing is only a name  compliant with the ad hoc (legacy) naming scheme used in `Lt.v`. So, my feeling is that `S_pred_pos` should just be an `apply` of `Nat.succ_pred_pos` (composed with symmetry). By making such an explicit reference to `Nat.succ_pred_pos` in the proof would also probably help to know that this lemma already exists in the generic library.

**Comment by fredokun** [comment]
Ok, I've learned the rebase things and I think it's ok now with only one commit.
As for @herbelin comment  `Nat.succ_pred_pos` is probably the thing to use now.
It's probably safe to use `S_pred` from within `S_pred_pos` but perhaps `S_pred` coud be rewritten later on. And in fact maybe `S_pred_pos` is not needed after all ?
You decide ;-).

**Comment by herbelin** [comment]
As soon as `Lt.v` is still there, that some people fall on it, and that some developments are still relying on the naming scheme and way-of-stating scheme of this file and similar files, I'd say (as a personal opinion) that adding this lemma to `Lt.v` is still worth.

**Comment by SkySkimmer** [comment]
@maximedenes rebase issues have been fixed here.

**Review by maximedenes — COMMENTED** [review]
The history is now clean, but I have no opinion on the change itself. Let's ask @letouzey.

**Comment by Zimmi48** [comment]
I showed this PR to @letouzey who is OK with the position that as long as the file is still there it is OK to keep adding stuff to it (as long as the equivalent stuff exists in the newer part of the library) and even if at some point the file should be removed.

**Review by letouzey — APPROVED** [review]
No objection. @herbelin and @Zimmi48 summarized quite well my views :smile: . As @herbelin said, it would be better to prove this extra lemma via the use of the "modern" lemma. But for a one-liner proof, that's not a big deal.

**Pull request merged**
