### PR TITLE
Remove HoTT overlay

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by JasonGross** [comment]
Uh, we don't currently have a branch that tracks trunk on HoTT, and because we need to replace the standard lib, we can't be compatible with multiple versions.

**Comment by maximedenes** [comment]
This is 8.6, not trunk.

**Comment by ejgallego** [comment]
> Uh, we don't currently have a branch that tracks trunk on HoTT, and because we need to replace the standard lib, we can't be compatible with multiple versions.

@JasonGross once #483 is merged I hope the main HoTT layout can be something such as `coq-VERSION` with a symlink being made at configure time.

**Comment by JasonGross** [comment]
Oh, I see.  I was unaware that this overlay made it into the v8.6 branch.

**Review by JasonGross — APPROVED** [review]

**Comment by JasonGross** [comment]
It's unfortunate that the mobile version of github doesn't display the merge base.

**Pull request merged**
