### PR TITLE
romega revisited : no more normalization trace, cleaned-up resolution trace

### PR DESCRIPTION
**Pull request by letouzey**
This revised version of romega should normally be compatible with the current one, except for one bug fixed (see the end of [ROmega0.v](test-suite/success/ROmega0.v)). But this implementation is quite smaller (-35%), cleaner and should be easier to maintain. It also generates smaller proofs, in the same time (or slightly less). Apart from some code and proofs refactoring, the main difference concerns the traces that end up in the proofs that romega generates:

  - The former normalization trace is now gone, replaced by a direct normalization function on the Coq-side (that mimick the ML normalization performed earlier). This is allowed by a careful synchronization of the variable numbers on the ML and Coq sides. As expected, it turns out that this trace was rather large and cumbersome for no particular speed-up (on the contrary) compared with a direct Coq implementation.
  - The resolution trace is kept, but contains less constructors, and a few useless arguments have been removed.

### CODE REVIEW

**Comment by gares** [comment]
It looks nice. Sorry if my question is dumb and a bit off topic: what is the relation with `omega`? Can we replace it?

**Comment by letouzey** [comment]
That's the plan. But it won't be obvious. Even if omega and romega share the same resolution engine, and should hence have the same strength, the devil is in the details (and in the PR number ;-). In particular, omega is "natively" able to handle goals about nat (or mixed nat+Z goals), plus a few other tricks hard-wired in [coq_omega.ml](plugins/omega/coq_omega.ml). I hope that `romega with *`(the version preprocessed by my little `zify` tactic) should already be almost as strong (or more) that `omega`. But I still need to quantify this "almost" on various developments (and in particular the stdlib), before being able to announce that omega is deprecated.

**Comment by letouzey** [comment]
Extension of this PR : by putting some division function in ReflOmegaCore, we are able to shorten the resolution trace (and hence the size of the proofs generated by romega) even more, for no extra time cost.

**Comment by maximedenes** [comment]
Merged, thanks for this diabolical pull request ;)

**Pull request merged**
