### PR TITLE
[ci] [ocaml] Track OCaml 4.12

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Is it useful to have both 4.11 and 4.12 jobs?

**Comment by ejgallego** [comment]
> Is it useful to have both 4.11 and 4.12 jobs?

4.11 is almost in beta so I expect it should move to be our next `edge` soon. I'd say to keep it for a while.

**Comment by SkySkimmer** [comment]
Maybe we should templatize these 2 jobs? something like 
~~~yaml

.test-suite:superedge+dune-template:
  stage: stage-1
  except:
    variables:
      - $ONLY_WINDOWS == "true"
  interruptible: true
  dependencies: []
  script:
    - opam switch create $OCAMLVER --empty
    - eval $(opam env)
    - opam repo add ocaml-beta https://github.com/ocaml/ocaml-beta-repository.git
    - opam update
    - opam install ocaml-variants=$OCAMLVER+trunk
    - opam install dune num
    - eval $(opam env)
    - export COQ_UNIT_TEST=noop
    - make -f Makefile.dune test-suite
  variables:
    OPAM_SWITCH: base
  artifacts:
    name: "$CI_JOB_NAME.logs"
    when: always
    paths:
      - _build/log
      - _build/default/test-suite/logs
    expire_in: 2 week
  allow_failure: true

test-suite:4.11+dune:
  extends: .test-suite:superedge+dune-template
  variables:
    OCAMLVER: 4.11.0

test-suite:4.12+dune:
  extends: .test-suite:superedge+dune-template
  variables:
    OCAMLVER: 4.12.0
~~~

**Comment by ejgallego** [comment]
> Maybe we should templatize these 2 jobs? something like

Didn't do because the 4.11 is gonna be short-lived, but now that you've written the code I'll update the file.

**Comment by ejgallego** [comment]
Thanks, sorry for the delay; I've made a few tweaks so the job can be used with more general switches such as `4.12+trunk+pr2323` etc...

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
It seems something changed between the CI of the PR 2 days ago and the CI of the merge now: it's failing to build dune now.
https://gitlab.com/coq/coq/-/jobs/614298727

**Comment by ejgallego** [comment]
Yup, that would be a good moment to introduce testing for master in Dune.

**Pull request merged**
