### PR TITLE
Add metacoq to bench packages

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1959843215

**Comment by ppedrot** [comment]
Hmm, the packages don't seem to compile...

**Comment by SkySkimmer** [comment]
The bench doesn't run the merged commit, so we need to rebase after an overlay gets merged.

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1960001474

**Comment by SkySkimmer** [comment]
~~~
┌──────────────────────────┬───────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │     user time [s]     │             CPU cycles              │          CPU instructions           │  max resident mem [KB]  │   mem faults    │
│                          │                       │                                     │                                     │                         │                 │
│             package_name │    NEW     OLD  PDIFF │           NEW            OLD  PDIFF │           NEW            OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├──────────────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-core │  98.62  101.26  -2.61 │  382931111671   381868934463   0.28 │  432996161376   433061933609  -0.02 │  249316   249324  -0.00 │   0    0    nan │
│            coq-equations │   5.51    5.64  -2.30 │   22839553176    22889656121  -0.22 │   35153498023    35159912978  -0.02 │  375952   376288  -0.09 │   0    0    nan │
│ coq-metacoq-translations │  20.07   20.09  -0.10 │   86821924825    86958535297  -0.16 │  152047205473   152027479589   0.01 │  904464   904384   0.01 │   0    0    nan │
│     coq-metacoq-template │  77.78   77.82  -0.05 │  333084658323   333655347179  -0.17 │  500238260637   500346829972  -0.02 │  700036   700184  -0.02 │   0    0    nan │
│        coq-metacoq-pcuic │ 770.44  770.13   0.04 │ 3374954034659  3373288643723   0.05 │ 4707171115119  4706944251205   0.00 │ 1141064  1141156  -0.01 │   0    0    nan │
│  coq-metacoq-safechecker │ 200.33  199.40   0.47 │  874987489142   870731212464   0.49 │ 1166249555697  1166262503446  -0.00 │ 1218372  1218884  -0.04 │   0    0    nan │
│      coq-metacoq-erasure │  72.98   72.45   0.73 │  315010766467   312624084655   0.76 │  460621573029   460942572913  -0.07 │ 1075456  1077208  -0.16 │   0    0    nan │
│               coq-stdlib │ 423.35  417.92   1.30 │ 1509447972888  1493323045705   1.08 │ 1445998942644  1445879438038   0.01 │  589408   590832  -0.24 │   0    0    nan │
└──────────────────────────┴───────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────┴─────────────────┘
~~~
A bit sad that we only see 5s of equations, maybe we should bench with tests?

**Comment by ppedrot** [comment]
Not sure whether the tests will really show anything. Also, equations is damn slow because of its own code, it's not clear to me that we want to observe that.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
In any case, I propose to merge now this can always be tweaked further.

**Comment by SkySkimmer** [comment]
Let me remove the equations package, getting it through deps will avoid spamming the bench.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
