### PR TITLE
setoid_rewrite: try subterms when rewriting produces identity

### LINKED ISSUE #8080: setoid_rewrite finds wrong subterm to rewrite in for trivial problems in 8.9+alpha that succeeded in 8.8
#### Version

8.9+alpha (02fe76c0c1c3f01c6fb4310dd4450b35f43005da)

#### Description of the problem

This code works in 8.8.1, but fails in somewhat-recent master:
```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-R" "." "Crypto" "-R" "../bbv/" "bbv" "-R" "../coqprime/src/Coqprime" "Coqprime" "-top" "Arithmetic" "-R" "." "Top") -*- *)
(* File reduced by coq-bug-finder from original input, then from 4345 lines to 410 lines, then from 376 lines to 34 lines, then from 44 lines to 22 lines, then from 32 lines to 22 lines *)
(* coqc version 8.9+alpha (July 2018) compiled on Jul 2 2018 12:06:11 with OCaml 4.02.3
   coqtop version jagro.cam.corp.google.com:/usr/local/google/home/jagro/Downloads/coq/coq-master,master (02fe76c0c1c3f01c6fb4310dd4450b35f43005da) *)
Require Import Coq.Lists.List.
Require Import Coq.Classes.Morphisms.

Axiom pointwise_map : forall {A B}, Proper ((pointwise_relation _ eq) ==> eq ==> eq) (@List.map A B).
Axiom flat_map_singleton : forall A B (f : A -> B) (xs : list A), flat_map (fun x => cons (f x) nil) xs = map f xs.
Existing Instance pointwise_map.
Goal forall (ls : list (list nat)) ls', map (fun t => flat_map (fun x => x::nil) t) ls = ls'.
  intros.
  setoid_rewrite flat_map_singleton.
  (* Error:
Ltac call to "setoid_rewrite (orient) (glob_constr_with_bindings)" failed.
Tactic failure: setoid rewrite failed: Failed to progress.
*)
```

cc @mattam82

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #8080

### CODE REVIEW

**Comment by mattam82** [comment]
This makes sense indeed.

**Comment by SkySkimmer** [comment]
Bench https://gitlab.com/coq/coq/-/jobs/2054403535

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│               coq-fiat-core │    0.69     0.73  -5.48 │     2238211359      2251979095  -0.61 │     3831566196      3851909099  -0.53 │   79848    79736   0.14 │   0    0      nan │
│                 coq-coqutil │   35.01    35.23  -0.62 │   156140941186    156202350796  -0.04 │   211486806756    211471595617   0.01 │  602320   602472  -0.03 │   0    0      nan │
│              coq-verdi-raft │  560.28   563.29  -0.53 │  2549528003932   2559510566845  -0.39 │  3944310268352   3944391065138  -0.00 │ 1231416  1234288  -0.23 │   0    0      nan │
│       coq-engine-bench-lite │  177.08   177.74  -0.37 │   759458766490    762039202554  -0.34 │  1490459050806   1493864318331  -0.23 │ 1175916  1174304   0.14 │   0    0      nan │
│                coq-coqprime │  180.46   181.13  -0.37 │   822261103474    826022502139  -0.46 │  1557183339495   1557171412271   0.00 │  830912   828920   0.24 │   0    0      nan │
│          coq-mathcomp-field │  111.24   111.58  -0.30 │   507797306849    509616289514  -0.36 │   838083550657    838071815477   0.00 │  649324   651860  -0.39 │   0    0      nan │
│                 coq-unimath │ 3936.32  3946.23  -0.25 │ 17891768688194  17931379784646  -0.22 │ 35864278857997  35864124053331   0.00 │ 3323564  3323180   0.01 │   0    0      nan │
│       coq-mathcomp-fingroup │   23.54    23.59  -0.21 │   107287437672    107231870019   0.05 │   156411212399    156438801961  -0.02 │  484944   486176  -0.25 │   0    0      nan │
│                    coq-corn │  755.10   756.54  -0.19 │  3423031845049   3429880395429  -0.20 │  5290596886895   5290759636153  -0.00 │  875172   872352   0.32 │   0    0      nan │
│        coq-metacoq-template │   73.43    73.57  -0.19 │   324991217378    325637296044  -0.20 │   493765274982    493785371316  -0.00 │  700056   699268   0.11 │   0    0      nan │
│                   coq-color │  210.70   211.04  -0.16 │   941290137121    943740338238  -0.26 │  1335734518626   1335853237093  -0.01 │ 1136208  1137084  -0.08 │   0    0      nan │
│      coq-mathcomp-odd-order │  546.74   547.61  -0.16 │  2500635347230   2504197316694  -0.14 │  4257794634481   4257784915831   0.00 │  932556   931624   0.10 │   0    0      nan │
│      coq-mathcomp-ssreflect │   25.96    25.99  -0.12 │   117815848400    117564979369   0.21 │   149525831933    149495632111   0.02 │  531764   531800  -0.01 │   0    0      nan │
│         coq-category-theory │ 1611.89  1613.25  -0.08 │  7361277822562   7365655607619  -0.06 │ 15276099664883  15276440949758  -0.00 │ 1479872  1481324  -0.10 │   0    3  -100.00 │
│                  coq-flocq3 │   75.98    76.04  -0.08 │   344920019866    344437226316   0.14 │   456755242259    456789706234  -0.01 │  988520   988700  -0.02 │   0    0      nan │
│                    coq-hott │  152.97   153.09  -0.08 │   688640159523    688367983636   0.04 │  1077597041556   1077602063160  -0.00 │  570024   570916  -0.16 │   0    0      nan │
│                 coq-bignums │   27.65    27.66  -0.04 │   125428417381    125634875754  -0.16 │   173188186852    173187814770   0.00 │  465804   465756   0.01 │   0    0      nan │
│                coq-rewriter │  374.11   374.04   0.02 │  1692039394256   1691922514435   0.01 │  2778997843236   2779038782957  -0.00 │ 1059316  1059080   0.02 │   0    0      nan │
│                     coq-vst │ 1051.90  1051.59   0.03 │  4762916115119   4762074032394   0.02 │  7812536737263   7812669169455  -0.00 │ 2073152  2073424  -0.01 │   0    0      nan │
│           coq-metacoq-pcuic │  733.74   733.26   0.07 │  3296737730190   329565617[1676](https://gitlab.com/coq/coq/-/jobs/2054403535#L1676)   0.03 │  4741161455010   4741225342169  -0.00 │ 1236880  1238348  -0.12 │   0    0      nan │
│      coq-mathcomp-character │   76.32    76.22   0.13 │   348265426538    347987554673   0.08 │   526348770181    526354585284  -0.00 │  731880   732384  -0.07 │   0    0      nan │
│                coq-compcert │  280.63   280.14   0.17 │  1260772887031   1259557427951   0.10 │  1889129018745   1889242487213  -0.01 │ 1099384  1100404  -0.09 │   0    0      nan │
│           coq-iris-examples │  419.89   419.02   0.21 │  1902562767781   1899128087880   0.18 │  2907956066812   2907994579130  -0.00 │ 1166720  1[1679](https://gitlab.com/coq/coq/-/jobs/2054403535#L1679)76  -0.11 │   0    0      nan │
│                    coq-core │   98.83    98.61   0.22 │   389919220414    388395482544   0.39 │   440797444962    440792664706   0.00 │  273600   273360   0.09 │   0    0      nan │
│               coq-fourcolor │ 1504.21  1500.64   0.24 │  6639482460241   6625802487595   0.21 │ 12088433890859  12088377804013   0.00 │  726692   725356   0.18 │   0    0      nan │
│                  coq-geocoq │  690.53   688.79   0.25 │  3134642601960   3128898986477   0.18 │  4963841192327   4963967070674  -0.00 │ 1076556  1077000  -0.04 │   0    0      nan │
│        coq-mathcomp-algebra │   63.94    63.75   0.30 │   291014132049    290081423170   0.32 │   398941126432    398921707233   0.00 │  555640   555808  -0.03 │   0    0      nan │
│             coq-fiat-crypto │ 2816.92  2808.14   0.31 │ 12689555168310  12650944831794   0.31 │ 23318596869437  23313342676460   0.02 │ 3850584  3850412   0.00 │   0    0      nan │
│       coq-mathcomp-solvable │   87.61    87.31   0.34 │   399776474189    398266858968   0.38 │   612005795089    612041559995  -0.01 │  660080   658256   0.28 │   0    0      nan │
│  coq-performance-tests-lite │  777.84   774.86   0.38 │  3494415901265   3479732157332   0.42 │  5932168853928   5930230632708   0.03 │ 1826780  1825048   0.09 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  925.68   921.87   0.41 │  4163801390505   4147362569403   0.40 │  7216790779727   7216141327695   0.01 │ 1220396  1220836  -0.04 │   0    0      nan │
│            coq-math-classes │   90.85    90.41   0.49 │   410251016628    407368063444   0.71 │   573965299017    573968856257  -0.00 │  495732   496148  -0.08 │   0    0      nan │
│                   coq-verdi │   48.36    47.93   0.90 │   217380276332    216618102409   0.35 │   324[1680](https://gitlab.com/coq/coq/-/jobs/2054403535#L1680)66942    324180614950  -0.00 │  838268   840244  -0.24 │   0    0      nan │
│              coq-coquelicot │   34.71    34.39   0.93 │   153992587521    153111561103   0.58 │   203690233897    203669410290   0.01 │  749300   749428  -0.02 │   0    0      nan │
│                  coq-stdlib │  404.76   399.74   1.26 │  1633215732223   1610467341844   1.41 │  1413637914407   1413679396915  -0.00 │  606472   606280   0.03 │   0    0      nan │
│            coq-fiat-parsers │    0.69     0.63   9.52 │     2254820181      2250254785   0.20 │     3864830320      3852775191   0.31 │   81940    79908   2.54 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```
The fiat devs are currently broken on the bench, we should probably rerun it when they're fixed since this PR is likely to affect them.

**Comment by SkySkimmer** [comment]
rebench https://gitlab.com/coq/coq/-/jobs/2068429120 (fiat should be fixed)

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                  coq-stdlib │  415.39   420.31  -1.17 │  1474609732874   1479857975213  -0.35 │  1414195416756   1414235122510  -0.00 │  608860   607084   0.29 │   0    0      nan │
│      coq-mathcomp-ssreflect │   27.16    27.27  -0.40 │   118371651073    118637417975  -0.22 │   149186425437    149173696448   0.01 │  532772   531836   0.18 │   0    0      nan │
│                    coq-hott │  167.97   168.14  -0.10 │   729362518407    729602844060  -0.03 │  1150135133190   1150145367877  -0.00 │  588140   590092  -0.33 │   0    0      nan │
│      coq-mathcomp-odd-order │  572.60   573.11  -0.09 │  2509894426037   2512316174520  -0.10 │  4256900995919   4257052153660  -0.00 │  933428   932948   0.05 │   0    0      nan │
│               coq-fourcolor │ 1510.15  1511.48  -0.09 │  6606023075826   6610648904588  -0.07 │ 12087391775339  12087590137110  -0.00 │  704020   704904  -0.13 │   0    0      nan │
│                 coq-bignums │   29.00    29.02  -0.07 │   126522032641    126749960814  -0.18 │   173132607148    173146874223  -0.01 │  466284   467352  -0.23 │   0    0      nan │
│                   coq-verdi │   50.03    50.04  -0.02 │   217066357646    217078692176  -0.01 │   323053590983    323035091951   0.01 │  835196   838236  -0.36 │   0    0      nan │
│         coq-category-theory │ 1673.19  1673.44  -0.01 │  7327564137961   7331089829312  -0.05 │ 15272615583801  15272875306053  -0.00 │ 1477148  1478664  -0.10 │   0    0      nan │
│                    coq-core │  103.91   103.91   0.00 │   380948583454    380530635236   0.11 │   440566428731    440781896202  -0.05 │  273460   274496  -0.38 │   1    0      nan │
│           coq-iris-examples │  437.71   437.71   0.00 │  1911161211147   1911580110610  -0.02 │  2908481499450   2908628698808  -0.01 │ 1169436  1167492   0.17 │  10    0      nan │
│                coq-coqprime │   61.93    61.92   0.02 │   269919658897    269004707359   0.34 │   445553130097    445552424319   0.00 │  760116   759992   0.02 │   0    0      nan │
│              coq-coquelicot │   35.77    35.76   0.03 │   154397812103    153940320630   0.30 │   202715108870    202710964344   0.00 │  746852   751412  -0.61 │  94    0      nan │
│ coq-rewriter-perf-SuperFast │  960.37   960.07   0.03 │  4196930488384   4195846924403   0.03 │  7300015339167   7299457218061   0.01 │ 1146500  1146368   0.01 │   4    0      nan │
│            coq-math-classes │   93.48    93.45   0.03 │   405756901212    405445000969   0.08 │   572081985025    572042880286   0.01 │  496056   495884   0.03 │   0    0      nan │
│      coq-mathcomp-character │   79.46    79.43   0.04 │   348204379890    348231225238  -0.01 │   526205556518    526275682013  -0.01 │  736560   732064   0.61 │   0    0      nan │
│                 coq-unimath │ 4076.51  4074.42   0.05 │ 17850336006851  17841094293851   0.05 │ 35844073970800  35843907390428   0.00 │ 3341276  3340488   0.02 │   1    3   -66.67 │
│             coq-fiat-crypto │ 2923.32  2921.61   0.06 │ 12756447644368  12749761957275   0.05 │ 23305921621831  23300657006985   0.02 │ 3849140  3849128   0.00 │  87   85     2.35 │
│                   coq-color │  217.59   217.45   0.06 │   945501731778    944167062762   0.14 │  1329601450199   1329590773261   0.00 │ 1140880  1138660   0.19 │   0    0      nan │
│            coq-fiat-parsers │  348.35   348.07   0.08 │  1501997753333   1499999408733   0.13 │  2458952356189   2458332976266   0.03 │ 3042196  3042028   0.01 │   0   23  -100.00 │
│  coq-performance-tests-lite │  806.96   806.19   0.10 │  3512349046796   3510100556776   0.06 │  5975620363653   5973064388903   0.04 │ 1826568  1824456   0.12 │   2    0      nan │
│                coq-compcert │  292.03   291.71   0.11 │  1268805200197   1268534504196   0.02 │  1895268418307   1895092682327   0.01 │ 1097452  1096452   0.09 │   0    0      nan │
│          coq-mathcomp-field │  116.21   116.01   0.17 │   509677922111    508516257319   0.23 │   837847571882    837796158844   0.01 │  651512   653988  -0.38 │   0    0      nan │
│        coq-metacoq-template │   76.54    76.39   0.20 │   327805773019    327669042568   0.04 │   492368641993    492519936489  -0.03 │  708636   705148   0.49 │   1    0      nan │
│       coq-mathcomp-solvable │   91.30    91.09   0.23 │   399936522574    399061987448   0.22 │   611688010003    611690706110  -0.00 │  661352   658356   0.46 │   0    0      nan │
│              coq-verdi-raft │  582.81   581.34   0.25 │  2544916714377   2538107771235   0.27 │  3937325939979   3937152155870   0.00 │ 1230216  1230620  -0.03 │   0    0      nan │
│           coq-metacoq-pcuic │  755.61   753.32   0.30 │  3290191111959   3280512637876   0.30 │  4738434353924   4738754739550  -0.01 │ 1234632  1236464  -0.15 │  34    1  3300.00 │
│                     coq-vst │ 1079.52  1076.22   0.31 │  4714316694425   4700575882107   0.29 │  7613554914860   7613604158422  -0.00 │ 2069208  2069368  -0.01 │   2    0      nan │
│                    coq-corn │  787.92   784.93   0.38 │  3439794622094   3428570312415   0.33 │  5285107363587   5284658542047   0.01 │  873328   871912   0.16 │   0    0      nan │
│                  coq-geocoq │  720.04   716.98   0.43 │  3144139035106   3128681536959   0.49 │  4955202331829   4955262284018  -0.00 │ 1075780  1077544  -0.16 │   4    7   -42.86 │
│                coq-rewriter │  387.68   385.90   0.46 │  1691843563153   [1683](https://gitlab.com/coq/coq/-/jobs/2068429120#L1683)735415556   0.48 │  2777637256684   2777536242849   0.00 │ 1060792  1060848  -0.01 │  14   28   -50.00 │
│       coq-engine-bench-lite │  184.43   183.57   0.47 │   775616446210    772362981138   0.42 │  1506018855060   1502198784799   0.25 │ 1175852  1173764   0.18 │   0    0      nan │
│        coq-mathcomp-algebra │   66.59    66.22   0.56 │   291425000495    289474762639   0.67 │   398584073463    398537516730   0.01 │  556328   555372   0.17 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.72    24.57   0.61 │   107847971437    107360186345   0.45 │   156329540963    156260823669   0.04 │  484756   485448  -0.14 │   0    0      nan │
│               coq-fiat-core │   57.75    57.38   0.64 │   238221442434    237120828687   0.46 │   330756670548    330795908700  -0.01 │  477152   477848  -0.15 │   2    6   -66.67 │
│                 coq-coqutil │   36.50    36.18   0.88 │   156623831405    155714737148   0.58 │   209629364652    209641978794  -0.01 │  601652   601676  -0.00 │   4    0      nan │
│                  coq-flocq3 │   79.77    78.95   1.04 │   347916291989    344383575439   1.03 │   456101029640    456057791375   0.01 │  988576   989168  -0.06 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
FTR, nothing observable from the per-line diff.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
Looks like this broke something in the part of perennial we don't test.

**Comment by tchajed** [comment]
It did break something in Perennial in lockmap_proof.v (and identical code in crash_lockmap_proof.v), but it was pretty minor. I was able to fix it by avoiding the setoid_rewrite entirely. The left and right hand sides were convertible, perhaps this PR causes such a rewrite to be skipped?

**Comment by JasonGross** [comment]
This sounds like it might be yet a separate bug in rewrite_strat: does `progress` consider there to be no progress when the proof term is the identity but the sides are not syntactically equal?

**Comment by SkySkimmer** [comment]
rewrite strat progress uses syntactic identity

**Pull request merged**
