### PR TITLE
CI: build Iris examples instead of lambda-Rust

### LINKED ISSUE #12836: Replace iris/lambda-rust in Coq CI by iris/examples
We'd like to replace lambda-rust in Coq CI by another of our repositories, [iris/examples](https://gitlab.mpi-sws.org/iris/examples/). lambda-rust doesn't see much activity recently, whereas new things are added to iris/examples semi-regularly. The last 2 Coq major version bumps both caused a (minor) incompatibility in iris/examples (see [this commit](https://gitlab.mpi-sws.org/iris/examples/-/commit/a6257e3482fd30f35e50d00fe0466edfb73485af) for the most recent one; the main point is tracked in [this std++ issue](https://gitlab.mpi-sws.org/iris/stdpp/-/issues/79)), so it seems to be a good sentinel for backwards compatibility. This is probably also caused by its very diverse coding style, because the different parts have been independently developed by different people with different levels of Iris and Coq experience.

Probably the biggest problem is that iris/examples has two extra dependencies besides Iris: autosubst, and our [string-ident ltac2 "plugin"](https://gitlab.mpi-sws.org/iris/examples/). This is easy via opam but could be a bit annoying with the CI setup.

@ppedrot (or whoever else would be the right person to ask), would this be okay for you, and what would it take to do this change?
Also Cc @robbertkrebbers.

### PR DESCRIPTION
**Pull request by RalfJung**
**Kind:** infrastructure.

Fixes https://github.com/coq/coq/issues/12836

I hope I got this right, but I guess CI will tell me. ;)
I have no idea what to do with the nix file (dev/ci/nix/lambda-rust.nix), in particular given that there are some new dependencies. @vbgl @maximedenes if you could provide a patch for that, that would be awesome -- I won't be able to do it.

### CODE REVIEW

**Comment by RalfJung** [comment]
It says "pipeline job limit exceeded"... does that mean it is in a queue and waiting, or is some action required to actually make the job go?

**Comment by SkySkimmer** [comment]
It needs kicking, see https://github.com/coq/coq/issues/11320
I kicked it

**Comment by RalfJung** [comment]
Looks like the Iris build passed. :D (Not sure why the overall CI state is still red.)

The [log](https://gitlab.com/coq/coq/-/jobs/716176052) is full of deprecation warnings so one cannot see anything; these should be fixed after a rerun (I just pushed a fix to our repo).

**Comment by SkySkimmer** [comment]
>The log is full of deprecation warnings so one cannot see anything; these should be fixed after a rerun (I just pushed a fix to our repo).

rerun started https://gitlab.com/coq/coq/-/jobs/720408801

**Review by SkySkimmer — APPROVED** [review]

**Comment by RalfJung** [comment]
That log looks much better, doesn't it? :D

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
