### PR TITLE
Update locations of ltac errors based on Loc.finer

### PR DESCRIPTION
**Pull request by SkySkimmer**
~~~coq
Ltac r0 := refine 0.

Goal False.
Proof.
  Fail refine 0. (* before: whole tactic, after: just 0 *)
  Fail r0. (* before: "refine 0" in the ltac definition, after: r0 in this line *)
Abort.
~~~

Based on #15174 to be able to write the test in a sane way.

### CODE REVIEW

**Comment by ppedrot** [comment]
Wut. We have a lot of affected output tests!

**Comment by SkySkimmer** [comment]
No, that's from the base PR because it changes failing commands to use Fail

**Comment by ppedrot** [comment]
This PR is probably for @herbelin.

**Review by ppedrot — APPROVED** [review]
I am personally unconvinced that the new criterion makes more sense than the previous one in the absolute, but at least it fixes the issues with uconstr and does not break the other output tests so that will be good enough for me.

**Comment by herbelin** [comment]
Roughly same opinion. Still not fully clear why tracking when we enter an Ltac definition, a Tactic Notation or an ML tactic, and keeping the information we are at toplevel when passing toplevel arguments is so difficult.

At least, we're getting each time closer to what the trace-based mechanism was producing.

**Comment by ppedrot** [comment]
@SkySkimmer if you rebase quickly I'll be able to merge this before the freeze!

**Comment by ppedrot** [comment]
What's with the coqtail failure?

**Comment by SkySkimmer** [comment]
https://github.com/whonore/Coqtail/pull/209

**Comment by ppedrot** [comment]
Since @herbelin seems happy with the change, let's merge.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
