### PR TITLE
Understand Mangle Names in implicit generalization

### LINKED ISSUE #13131: Implicit generalization ignores Mangle Names
~~~coq
Set Mangle Names.

Class A := {}.

Lemma foo `{A} : A.
Proof. exact H. Qed.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13131

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Well spotted. Good to me.

**Comment by SkySkimmer** [comment]
@herbelin merge?

**Comment by herbelin** [comment]
OK, shall do tomorrow. No risk at first view for targetting 8.12.1 too?

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
