### PR TITLE
Deifnition of Lift

### PR DESCRIPTION
**Pull request by JasonGross**
Make definitions to lift types and lift and lower terms.

### CODE REVIEW

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
Could you give an example showing that Lift is of general interest? The development team is currently trying to trim down the standard library, so we would consider integration of new definitions only if they are expected to be useful to a majority of users. Thanks!

**Comment by JasonGross** [comment]
I'm no longer sure this would be of particular general interest, so I'm going to close this.

**Pull request closed without merging**
