### PR TITLE
[ci] [overlays] Pin unicoq to a stable version.

### PR DESCRIPTION
**Pull request by ejgallego**
Following upstream advice.

cc: https://github.com/coq/coq/pull/12480#issuecomment-640682725

### CODE REVIEW

**Comment by ejgallego** [comment]
@Zimmi48 I understand we don't need this on 8.12 as it is already the case.

**Comment by Zimmi48** [comment]
That's correct.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
FTR, CI for mtac2 is green. No need to wait longer before merging.

**Comment by ejgallego** [comment]
Thanks!

**Comment by beta-ziliani** [comment]
Hey, I fixed the problem that originated this PR, so it can now be undoed (I can issue a PR if you want @ejgallego). I don't know why in the tests Coq is using the files from the installation instead of the files from the local directory as instructed in the Make file :-(

**Comment by ejgallego** [comment]
> Hey, I fixed the problem that originated this PR, so it can now be undoed (I can issue a PR if you want @ejgallego). I don't know why in the tests Coq is using the files from the installation instead of the files from the local directory as instructed in the Make file :-(

Cool thanks! Yup please open a PR, or we can do it.

It is hard to recall why we are using this exact setup, we added Mtac2 and Unicoq to the CI long time ago, but indeed we can tweak to setup to proceed in the way it should.

**Comment by beta-ziliani** [comment]
But I face the same problem in my computer, and that's why I failed to see I've committed a broken commit. I'm seeing all sort of weird issues with the compilation. For instance, recently I've got [this issue](https://github.com/unicoq/unicoq/issues/40) in my computer but after a `make clean` and `make` it worked with no problem. And looking at the (former) `Make` file (now `_CoqProject`) there is nothing strange :shrug:

**Pull request merged**
