### PR TITLE
Remove dead code [Universes.simplify_universe_context]

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by mattam82 — APPROVED** [review]
Fine with me, indeed it can be removed, this is done as part of minimization now.

**Comment by maximedenes** [comment]
@SkySkimmer Would you mind rebasing? Thanks!

**Comment by SkySkimmer** [comment]
@maximedenes Rebased.

**Comment by maximedenes** [comment]
Merged in master, thanks!

**Pull request merged**
