### PR TITLE
Don't store vcs_backup unless interactive

### PR DESCRIPTION
**Pull request by SkySkimmer**
cf https://github.com/coq/coq/issues/12639

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by Alizter** [comment]
Did it make a difference? Looks like noise to me.

**Comment by SkySkimmer** [comment]
Some of the memory differences may be real but our memory benching infrastructure is pretty bad.
I'm looking into improving it so maybe I'll try this PR again after that.

**Pull request closed without merging**
