### PR TITLE
Linter: skip PRs older than the linter.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Tested with old PR https://travis-ci.org/SkySkimmer/coq/jobs/312415681 https://github.com/SkySkimmer/coq/pull/4

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
That's a bit overkill but thanks !

**Comment by SkySkimmer** [comment]
How is it overkill?

**Review by maximedenes — APPROVED** [review]
Thanks!

**Comment by herbelin** [comment]
Wasn't there a pending question before merging?

**Comment by ejgallego** [comment]
Well I meant that this PR was truly attention to the detail, sorry if my comment was misunderstood.

**Comment by herbelin** [comment]
@maximedenes: My question was to clarify our protocols. In particular, do we consider that it is a good protocol that questions get answered?

@ejgallego: thanks for your clear answer.

**Comment by JasonGross** [comment]
@herbelin My understanding of the (implicit?) protocol is that some questions are deemed "blocking merge" (definitely any that come with an explicit "change requested" mark, maybe some others), and others are deemed "non-blocking but interesting" (e.g., I think some of the discussions we had on the sigma-inversion PR which seemed to me (and I think to you) beyond the scope of that PR, but useful to bring up), and there's a bit of a judgment call involved here, and that it's good to answer all questions, but only the merge-blocking ones should block merges.
(@maximedenes Does this agree with your sense?)

**Comment by herbelin** [comment]
@JasonGross: I'm probably oversensitive to this kind of situation due to a number of previous situations where I felt that important questions or discussions were made unwelcome. I don't know how to go past these former bad experiences, but I hope that, stepwise, we shall be able to clarify what it is about.

Otherwise, I agree that in the present case, the question is not deemed "blocking merge".

**Comment by JasonGross** [comment]
@herbelin Yeah, that makes sense.  I've always found feeling unwelcome to be a really unpleasant experience, and often hard to integrate.

**Pull request merged**
