### PR TITLE
Add missing paragraph to introduction

### PR DESCRIPTION
**Pull request by bcpierce00**
Add a paragraph summarizing part 5 of the manual to the front matter of the reference manual.

### CODE REVIEW

**Comment by herbelin** [comment]
I'm copying here a comment made at #927: Note that there is already a mention to the fifth part in the item `Addendum` of the `List of additional documentation`. So, this `Addendum` paragraph should be merged with the item that you wrote. Would you be ok to go this way? (Historical notice: at the end of 90's, beginning of 00's, at a period of time where it was still relatively common to work with a printed paper copy, the pdf manual was distributed in two parts.)

**Comment by bcpierce00** [comment]
Yes, that's fine.  I'm not at all attached to the wording of what I wrote -- just noticed that the first four parts are described in that section and the fifth is missing.

**Comment by herbelin** [comment]
In any case, if you want to do the merge of both texts yourself, don't hesitate, as this is somehow the rule of the game with pull requests, compared to bug reports. If not, don't worry, we'll push this as an open request for enhancement.

**Comment by bcpierce00** [comment]
OK, adjusted.  The fix has now become a really minor one (you could just drop it), but I think it's a slight improvement in that it avoids a minor puzzle.  

It does make me wonder, though, why it's worth bothering to distribute the addendum separately.  Nobody prints the Coq manual any more, I'm sure, and some of the topics in the addendum are just as "core" as some of what's in the "core manual."

**Comment by Zimmi48** [comment]
I'm all for making the Addendum disappear and moving chapters at more appropriate places.

**Comment by herbelin** [comment]
> It does make me wonder, though, why it's worth bothering to distribute the addendum separately.  

Sorry, I realized that I was not clear. The seperate Addendum item is a bug as there is actually no separate release of the Addendum since Coq 8.0 (2004). So, it is this Addendum paragraph which should have been adapted into a fifth item in the list long time ago already. 

Reading carefully this Addendum paragraph, I think that the simplest way to go is finally to keep your first proposal and to simply drop the Addendum item which after all is mainly about information which is irrelevant in the absence of a separate Addendum.

I know how busy you are, so the simplest is probably that @maximedenes takes your first formulation (7a47079), remove the Addendum paragraph and commits the result, if he's ok (and if noone has no more special comments about the PR).

**Comment by bcpierce00** [comment]
Yes, that’s fine.  (And best for me this time since I’m going on vacation tomorrow...)

   - B

**Comment by Zimmi48** [comment]
> I know how busy you are, so the simplest is probably that @maximedenes takes your first formulation (7a47079), remove the Addendum paragraph and commits the result, if he's ok (and if noone has no more special comments about the PR).

@herbelin Note the nice feature of GitHub that I just made use of. As a contributor with write rights, unless the PR author has unchecked a specific box, I can push (even force-push) to the branch corresponding to the PR. Of course this should only be done with the PR author prior permission.

In this case, this allowed me reverting the PR to Benjamin's initial commit, then add a further commit dropping the paragraph about the Addendum as you suggested. This will avoid putting more load on Maxime's shoulder (who has more urgent things to do IMO).

BTW can you confirm that the new state of this PR corresponds to what you had in mind?

**Comment by herbelin** [comment]
> BTW can you confirm that the new state of this PR corresponds to what you had in mind?

Totally, yes.

> I'm all for making the Addendum disappear and moving chapters at more appropriate places.

Then part 5 could already be renamed "Additional features", so that it is fully clear that it is a part of the reference manual proper.

On the longer term, a deeper restructuration shall indeed be appropriate (my main worry is the existing references which we can already find in the literature, for instance, it is common to talk about "chapter 4" rather than "the chapter describing the calculus of inductive constructions", but again maybe better to think in term of future than in term of past).

Thanks for the hint, I did not know github allowed this.

**Pull request merged**
