### PR TITLE
Solve universe error with SSR 'rewrite !term'

### LINKED ISSUE #10711: Are Proofview.Progress.goal_equal environments passed in the wrong order?
On the following line https://github.com/coq/coq/blob/0c6726655ee0ec06a40240cca44202d584506c9c/proofs/goal.ml#L94

it seems that the environments are passed in the wrong order. My reason to believe this is because later the environments are passed on to [Evarutil.eq_constr_univs_test](https://github.com/coq/coq/blob/0c6726655ee0ec06a40240cca44202d584506c9c/engine/evarutil.mli#L212) in the same order, and the documentation says
```
[eq_constr_univs_test sigma1 sigma2 t u] tests equality of [t] and
    [u] up to existential variable instantiation and equalisable
    universes. The term [t] is interpreted in [sigma1] while [u] is
    interpreted in [sigma2]. The universe constraints in [sigma2] are
    assumed to be an extension of those in [sigma1].
```
I would not expect the universes in `gls.Evd.sigma` to be an extension of those in `glss.Evd.sigma`, I would expect the opposite.

I discovered this while working on compiling math-comp with HoTT, by getting universe errors from `rewrite !term`. I have tried changing the line to
```
  | [ g ] -> not (Proofview.Progress.goal_equal gls.Evd.sigma gls.Evd.it glss.Evd.sigma g)
```
This seems to work. I am however unsure about this. After all, I think it is unlikely that there is an error here.

What do you think? Have I corrected the error in the wrong place?

### PR DESCRIPTION
**Pull request by andreaslyn**
**Kind:** bug fix.

Fixes / closes #10711 

- [x] Added / updated test-suite

### CODE REVIEW

**Comment by andreaslyn** [comment]
See the issue https://github.com/coq/coq/issues/10711 for some background for this PR

**Comment by gares** [comment]
Cool, thanks. The code in question is not in SSR, so I guess another Dev should take care of this pr.

**Comment by ppedrot** [comment]
It'd probably be good to add a comment somewhere or implement @ejgallego's proposal for named arguments so as to not reproduce this issue unwillingly.

**Comment by andreaslyn** [comment]
@ppedrot What do you think?

There is a chance that the interface changes will affect Coq users, such as MetaCoq. Do we need a changelog entry for this?

**Comment by ppedrot** [comment]
We usually don't mention such minor ML API changes in the changelog, so this is OK as is.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
