### PR TITLE
remove Zdigits

### PR DESCRIPTION
**Pull request by andres-erbsen**
- [x] Added **changelog**.
- [x] Added / updated **documentation**.

### CODE REVIEW

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@andres-erbsen the refman failure seems real

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
[CI before doc fix](https://gitlab.inria.fr/coq/coq/-/pipelines/854838) with timeouts in fiat-crypto and 32-bit build, [diff](https://github.com/coq/coq/compare/99ee448033f2007b7d42b613d6185bf7c92c6a46..ade94e2c89ba2590325884333610a43f4a8599dd).

**Comment by proux01** [comment]
@coqbot merge now

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
