### PR TITLE
 Fixes #14938: in the reference manual, mentions the role of non-recursively uniform parameters in the strict positivity condition

### LINKED ISSUE #14938: Inductives satisfying the refman's positivity criteria are rejected by the implementation (or, my math is wrong)
#### Description of the problem

I was reading through [this question](https://stackoverflow.com/questions/56143587/why-is-my-definition-not-allowed-because-of-strict-positivity) on StackOverflow.  Simplified, the example is this:

```coq
Inductive Inner (A : Type) : Type := inner : Inner bool -> Inner A.
Inductive Outer := outer : Inner Outer -> Outer.
```

(Ignore for a moment the fact that the first type is empty)
Coq rejects the second inductive:

```
Error: Non strictly positive occurrence of "Outer" in "Inner Outer -> Outer".
```

My math is likely wrong, but following the rules in the refman suggests that this type should not be rejected:

1. [Correctness rules](https://coq.inria.fr/refman/language/core/inductive.html#correctness-rules)
   image
2. [Positivity condition](https://coq.inria.fr/refman/language/core/inductive.html#positivity-condition)   
   image
   Here,
   ```
   X = Outer
   T = forall x: Inner X, X
   ```
   So we're in the second case with
   ```
   U = Inner X
   V = X
   ```

   1. `V` is easy, so let's do that first:
      `V = (X)` falls in the first case, with no `t_i`, hence is positive for X
   2. For `U`: is `U = Inner X` [strictly positive](https://coq.inria.fr/refman/language/core/inductive.html#strict-positivity) wrt `X`?
      image
      Here,
      ```
      T = Inner X
      ```
      Hence we're in the last case: `T` converts to `(I a1)` (no `t_i`) with
      ```
      I = Inner
      a1 = X
      ```
      and `X` does not occur in the `t_i`, since there are no `t_i`.
      Do the instantiated types of the constructors satisfy the nested positivity condition?
      There is only one constructor:
      1. `inner : Inner bool -> Inner X.`
         Does this satisfy the [nested positivity condition](https://coq.inria.fr/refman/language/core/inductive.html#nested-positivity)?
         Here,
         ```
         T = forall x: Inner bool, Inner X.
         ```
         So we're in the second case with
         ```
         U = Inner bool
         V = Inner X
         ```
         1. `X` does not occur in `U`, so `X` is strictly positive in `U`.
         2. Does `V` satisfy the nested positivity condition for `X`?
            Here,
            ```
            T = Inner X
            ```
            Hence we're in the first case: `T` converts to `(I b1)` (no `u_i`) with
            ```
            I = Inner
            b1 = X
            ```
            There are no `u_i`, so `V` satisfies the nested positivity condition.

So, this looks valid, but Coq rejects it.  Is my math wrong, or is the positivity checker wrong, or is the manual wrong? (ordered by my mental model of relative likelihood ^^)

#### Coq Version

8.13

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** fix

Fixes / closes #14938

- [x] Added **changelog**.
- [X] Added / updated **documentation**.

We also slightly reformulate the nested positivity condition to clarify that we are recursively talking about the same type.

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
If this PR is ready, it should be marked as such. Also, can I let someone who understands that stuff self-assign?

**Review by jfehrle — COMMENTED** [review]
Tweaks.

**Review by SkySkimmer — APPROVED** [review]

**Comment by Zimmi48** [comment]
@SkySkimmer I suggested that @coq/kernel-maintainers or such should assign this PR. If someone in @coq/doc-maintainers wants to do it, that's also fine, but I won't.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
