### PR TITLE
Generalize the URL for base repository in the bench script.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of hardwiring it to a specific value, we use the generic environment variable as provided by GitLab instances.

### CODE REVIEW

**Comment by ppedrot** [comment]
Just to try quickly @coqbot bench

**Comment by Zimmi48** [comment]
I'm not a bench maintainer, but this seems like an important fix to adapt to the move to Inria GitLab CI, so I can merge it if you want.

**Comment by ppedrot** [comment]
@Zimmi48 yes, please.

**Comment by ppedrot** [comment]
Actually, this should probably be backported to 8.18, so cc @gares.

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
