### PR TITLE
More explicit error message for missing constraints in @{...|...}

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Alizter** [comment]
Output test?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I don't think an output test is necessary, but I won't object if @SkySkimmer adds one.

**Comment by SkySkimmer** [comment]
No point testing this imo

**Comment by ppedrot** [comment]
CI failure unrelated, let's merge.

**Pull request merged**
