### PR TITLE
Congruence: don't replace error messages by "congruence failed"

### LINKED ISSUE #13595: congruence drops incompleteness message
The info documented at https://coq.github.io/doc/master/refman/proofs/automatic-tactics/logic.html#coq:exn.goal-is-solvable-by-congruence-but-some-arguments-are-missing-try-congruence-with-term-term-replacing-metavariables-by-arbitrary-terms is never printed.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13595

### CODE REVIEW

**Review by PierreCorbineau — COMMENTED** [review]
I'm fine with the changes. Fixes the bug.
 Looks like some CI jobs failed but is it really related to this commit.
Will approve if someone confirms CI jobs failures are unrelated.

**Comment by SkySkimmer** [comment]
macos is always failing as of some time ago

**Review by ejgallego — APPROVED** [review]
Looks good to me.

**Comment by ejgallego** [comment]
> Will approve if someone confirms CI jobs failures are unrelated

Indeed they are, so we can go ahead IMHO.

@coqbot: merge now

**Pull request merged**
