### PR TITLE
Fix the check in configure.ml following instructions in INSTALL.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Comment by herbelin** [comment]
For the record:
- I can compile with ocamlc 4.02.1, camlp5 6.14 and lablgtk 16.0, so, independently of the policy adopted in `configure`, interested users might appreciate the information that 4.02.1 is actually ok
- `INSTALL.ide` actually mentions 4.02.1 (in master)

**Comment by Zimmi48** [comment]
I think there was a reason for requiring 4.02.3 but I don't remember what.

**Comment by ejgallego** [comment]
> I think there was a reason for requiring 4.02.3 but I don't remember what.

The reason is that our lower bound for testing is 4.02.3, so it seems unfair to advertise an untested version. Also, all the distributors of 4.02 that we could find use 4.02.3

**Comment by herbelin** [comment]
> The reason is that our lower bound for testing is 4.02.3, so it seems unfair to advertise an untested version. Also, all the distributors of 4.02 that we could find use 4.02.3

As you want. I just wanted to tell that I tested, that it works, and that this can be a useful information to give, even if it is not the "officially" minimal supported version.

Not a big issue anyway.

**Comment by Zimmi48** [comment]
I don't want to push this PR too much, but we should aim for consistency in the communication, whether it is 4.02.3 or 4.02.0, right?

**Comment by herbelin** [comment]
Note that, in any case, we cannot recommend 4.02.0 with which coq is unusable due to a critical inefficiency bug.

**Comment by Zimmi48** [comment]
Just found out that this commit c1ad8fa3 was doing the opposite of what this PR is doing (it relaxed the requirement in `./configure` from 4.02.3 to 4.02.1). So there is really no reason to "revert it"

**Pull request closed without merging**
