### PR TITLE
Reduce the amount of typechecking in Ssrequality.

### PR DESCRIPTION
**Pull request by ppedrot**
We could do even better for the typing of the non-linear predicate but I will leave this to a hypothetical later PR.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by gares** [comment]
Not a net win according to the bench.

**Comment by Janno** [comment]
> Not a net win according to the bench.

Going by instruction this is actually a net win of -1.5E10 instructions, i.e. pretty much exactly -0.1% overall. Not sure if that makes it worth it..

**Comment by ppedrot** [comment]
This looks indeed like noise. Nonetheless, this patch makes it easier to further reduce the amount of typing in that function, that does keep appearing in my random profiles.

**Comment by gares** [comment]
What makes me dislike the profiling here is that ssr users are all spread around, metacoq that uses mainly rewrite is on the slow side, mathcomp all spread all around. IMO is very inconclusive.

If the new code helps profiling, I'm fine with it.

**Comment by gares** [comment]
but it needs a comment, If I see this code in 2 years I'll surely "deoptimize" it

**Comment by ppedrot** [comment]
Comment added.

**Review by gares — APPROVED** [review]

**Pull request merged**
