### PR TITLE
Amending #13663 for backwards compatibility with vscoq (goal name in XML protocol)

### LINKED ISSUE #240: Compatibility with 8.14
The changes for https://github.com/coq/coq/pull/13663 mean that vscoq does not work with 8.14 yet.

We probably need a change that just acknowledges the existance of that new field and fixes parsing, without using the name (yet?), probably involves only shifting the array subscript positions in the goal case of the doDeserialize:
https://github.com/coq-community/vscoq/blob/master/server/src/coqtop/xml-protocol/deserialize.base.ts#L436

Preferably, we do so depending on the "protocol_version " for backwards-compatibility.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** improved compatibility

Fixes / closes coq-community/vscoq#240

See also discussion at [Zulip](https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs.20.26.20users/topic/Change.20in.20XML.20protocol/near/241794300).

### CODE REVIEW

**Comment by ppedrot** [comment]
This is a fragile hack, but if it happens to work why not. Except we might break coqtail now, ping @whonore .

**Comment by herbelin** [comment]
Indeed, you're right, this would require coqtail's whonore/Coqtail#211 to be amended too.

So, let's wait at least to know if this would really help vscoq.

**Comment by whonore** [comment]
The fix for Coqtail is trivial. whonore/Coqtail#213 should do it.

**Review by ppedrot — APPROVED** [review]

**Comment by herbelin** [comment]
I looked at [vscoq relevant file](https://github.com/coq-community/vscoq/blob/master/server/src/coqtop/xml-protocol/deserialize.base.ts). It may be that having the field coming last would preserve the compatibility but I don't understand the ` || []` on line [440](https://github.com/coq-community/vscoq/blob/6a5eec9989c2b99105165ba78c189245f57896a9/server/src/coqtop/xml-protocol/deserialize.base.ts#L440) to be sure.

**Comment by ppedrot** [comment]
Can somebody test this on vscoq just to be sure? I'll leave a bit of time for optional comments before merging as well.

**Comment by ppedrot** [comment]
ping @fakusb

**Comment by herbelin** [comment]
@fakusb answered in [coq-community/vscoq#240](https://github.com/coq-community/vscoq/issues/240#issuecomment-864139039) though it is not fully a confirmation that it has been tested.

**Comment by Zimmi48** [comment]
Maybe @mattam82 can take care of testing this PR since he was the one whose work was blocked before this fix.

**Comment by mattam82** [comment]
It works on VSCoq as far as I could test

**Comment by ppedrot** [comment]
Let's merge.

**Pull request merged**
