### PR TITLE
Add Mtac2 1.0 to Coq 8.8 Windows packages.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

- [x] Entry added in CHANGES.

Now that Mtac2 1.0 has been adapted to Coq 8.8, we add it to the Windows installer to give it more chances to "compete against" Ltac and Ltac2.
Note that this is a 8.8-only PR because Mtac2 1.0 is not yet compatible with Coq 8.9 / master (the `master-sync` branch that is tested in CI for Coq master is an outdated version of Mtac2 so it wouldn't make sense to distribute it in the Windows package). We hope that Mtac2 1.0 will be made compatible with Coq 8.9 by the time of the release but in the meantime, it would make sense to remove Mtac2 from CI for Coq master.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@beta-ziliani said:
>A quick update: master-sync is now also in 1.0

So I will also prepare a similar PR for master.

**Review by MSoegtropIMC — APPROVED** [review]
Changes are fine.

**Comment by MSoegtropIMC** [comment]
When is the deadline for 8.8.2? I am working on adding quite a few more packages (at least optionally but some make sense to include e.g. QuickChick). Also I have now a generic shell function for getting the SHA code and doing a build prep. I can hopefully make the PR tomorrow.

**Comment by Zimmi48** [comment]
OK if the PR is almost ready we can have it supersede this one and #8306.
I didn't set a date for the 8.8.2 release yet. I hope it can be around Sep 1st.

**Review by ejgallego — APPROVED** [review]
LGTM.

**Comment by Zimmi48** [comment]
This will be superseded by #8322 or its v8.8 counter-part.

**Review by MSoegtropIMC — APPROVED** [review]
Looks good!

**Comment by Zimmi48** [comment]
No luck. It looked like the Windows build of Mtac2 failed even though the normal CI build succeeded.

**Comment by Zimmi48** [comment]
Of course, I'm stupid. I forgot the dependency on UniCoq. It would be simpler if we could reuse the dependency knowledge from `Makefile.ci`.

**Comment by Zimmi48** [comment]
Updated. I didn't put UniCoq in the installable packages but if the dependency management is fixed, we can consider adding it.

**Pull request merged**
