### PR TITLE
Fix insertion of default timeout

### LINKED ISSUE #17580: Combining Timeout and Default Timeout misbehaves
#### Description of the problem
Consider the following situation: a `Default Timeout` is set and a command is run with an additional `Timeout` prefix.
The command triggers a `Timeout!` error if it takes longer than either of the two limits. The reference manual states that only the latter limit should apply. It states about `Default Timeout`: "When this [option](https://coq.inria.fr/refman/language/core/basic.html#term-option) is set, each [sentence](https://coq.inria.fr/refman/language/core/basic.html#grammar-token-sentence) is treated as if it was prefixed with `Timeout natural`, except for [`Timeout`](https://coq.inria.fr/refman/proof-engine/vernacular-commands.html#coq:cmd.Timeout) commands themselves. If unset, no timeout is applied."

Code to verify the behaviour:
```coq
Fixpoint branch (n : nat) : Prop :=
  match n with
  | 0 => True
  | S n => (branch n) /\ (branch n)
  end.

Goal branch 14. (* change this number as necessary *)
  Fail Timeout 1 repeat constructor.
  Timeout 2 repeat constructor.
Abort.
Set Default Timeout 1.
Goal branch 14.
  Fail Timeout 2 repeat constructor. (* refman says this should succeed *)
```

The behaviour described in the manual is useful if one has set a "small" `Default Timeout` and wants to set a higher timeout for a single command.

#### Coq Version
v8.18+alpha, Linux

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17580

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
(Timeout is had to test reliably so no test)

**Comment by SkySkimmer** [comment]
@maximedenes

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
