### PR TITLE
Unconditionally print explanation for universe inconsistencies

### PR DESCRIPTION
**Pull request by SkySkimmer**
ie regardless of the Print Universes flag.

AFAICT there is no point in skipping them.

### CODE REVIEW

**Comment by JasonGross** [comment]
The lack of explanation when the flag is under has always bothered me.

**Comment by ejgallego** [comment]
Wasn't the original motivation performance in some developments [that is, errors taking a long time to print] ?

**Comment by SkySkimmer** [comment]
I guess we can bench, but note that the flag used to be tested when the error was raised so the error probably got absorbed more often.

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/860/console

**Comment by JasonGross** [comment]
@ejgallego That should not be.  In any case, the performance of printing the error does not matter much, as long as it only shows up when the error is actually printed, and does not show up when it's caught and suppressed by, eg, `try`.

**Comment by SkySkimmer** [comment]
No real change
~~~
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │    mem faults     │
│                             │                         │                                             │                                             │                               │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-sf-plf │   43.35   43.94 -1.34 % │      121436386213      121884560421 -0.37 % │      168649640857      168663704917 -0.01 % │     488420     488348 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1361.37 1370.94 -0.70 % │     3794484642150     3821036959120 -0.69 % │     6725045911707     6725102416256 -0.00 % │    1300660    1301008 -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  994.42 1000.96 -0.65 % │     2771565894165     2788389378650 -0.60 % │     4554071363957     4553102775667 +0.02 % │     930492     930536 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  175.32  176.40 -0.61 % │      489141575873      490826260064 -0.34 % │      697172741542      697143931998 +0.00 % │     793404     793364 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  593.02  595.12 -0.35 % │     1661648486231     1668132447200 -0.39 % │     2680092520195     2679819235610 +0.01 % │    3131624    3131668 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-compcert │  674.34  676.20 -0.28 % │     1881282136039     1882400675953 -0.06 % │     2644518722438     2644365219687 +0.01 % │    1038100    1038188 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-color │  651.46  653.23 -0.27 % │     1818029320994     1822084976822 -0.22 % │     2318811243773     2319248387506 -0.02 % │    1141032    1143276 -0.20 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-verdi │  115.73  116.04 -0.27 % │      320987709812      320845340363 +0.04 % │      417336331217      417295637897 +0.01 % │     541700     541824 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-performance-tests │   11.47   11.50 -0.26 % │       31470837952       31473161908 -0.01 % │       54616629908       54611638080 +0.01 % │     410316     410244 +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1251.52 1254.75 -0.26 % │     3486445971054     3494149190887 -0.22 % │     4960512051556     4960598640557 -0.00 % │    1826076    1826076 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  262.79  263.46 -0.25 % │      732011865153      733700506928 -0.23 % │     1123794649146     1123829125771 -0.00 % │     789752     789360 +0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2099.99 2105.29 -0.25 % │     5860823851498     5873198501981 -0.21 % │    11489414733748    11489387998382 +0.00 % │     952544     952504 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-flocq │  198.84  199.26 -0.21 % │      552685869440      553710852845 -0.19 % │      715588636727      715614891571 -0.00 % │     927400     927272 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-corn │ 1430.15 1432.95 -0.20 % │     3985574654352     3997176956299 -0.29 % │     6157181639104     6156697034179 +0.01 % │     876672     876708 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4043.53 4050.82 -0.18 % │    11258976327739    11279688984598 -0.18 % │    21440842729847    21442007198626 -0.01 % │    1088476    1088608 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fiat-core │  101.94  102.12 -0.18 % │      288626692980      288646941053 -0.01 % │      388670749587      388594198088 +0.02 % │     498656     499080 -0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-rewriter │  569.81  570.72 -0.16 % │     1581586479665     1585256127221 -0.23 % │     2446013374690     2445989192434 +0.00 % │    1000692    1000776 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1539.66 1541.45 -0.12 % │     4290645477564     4294269636678 -0.08 % │     6207049206316     6207047125029 +0.00 % │    1138796    1139032 -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-hott │  315.06  315.42 -0.11 % │      855463921060      857334795086 -0.22 % │     1387001683203     1387054363633 -0.00 % │     597808     597884 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4384.88 4387.49 -0.06 % │    12180871066246    12183813487955 -0.02 % │    20184422019417    20181329090115 +0.02 % │    2375448    2363284 +0.51 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-math-classes │  205.38  205.44 -0.03 % │      572889233197      573576309962 -0.12 % │      769988673070      769930955007 +0.01 % │     518780     517320 +0.28 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-coqprime │   84.13   84.14 -0.01 % │      232503496427      232487118571 +0.01 % │      335590284501      335572309570 +0.01 % │     757112     757116 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   49.16   49.16 +0.00 % │      134790919964      134752835875 +0.03 % │      176238118025      176213003933 +0.01 % │     568692     568660 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  211.85  211.78 +0.03 % │      587615008563      587031999658 +0.10 % │      983151367699      983565889284 -0.04 % │    1119900    1119780 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-fiat-crypto-legacy │ 5931.86 5928.93 +0.05 % │    16517910462047    16506736440143 +0.07 % │    28005176068312    28005313068859 -0.00 % │    2395888    2395792 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-coqutil │   57.24   57.18 +0.10 % │      158781614267      159373166712 -0.37 % │      203522453814      203519774713 +0.00 % │     534952     534904 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1524.54 1522.90 +0.11 % │     4250846628143     4248569993398 +0.05 % │     6517841595669     6517899591962 -0.00 % │    1378020    1377892 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  164.21  163.96 +0.15 % │      456641690890      456946137361 -0.07 % │      639015407170      639134585448 -0.02 % │     801364     848616 -5.57 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  145.93  145.58 +0.24 % │      405998118624      405868669067 +0.03 % │      539033854341      539040801727 -0.00 % │     613796     610780 +0.49 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   49.30   49.14 +0.33 % │      136578194673      136517577494 +0.04 % │      190052937067      190056904692 -0.00 % │     557152     557184 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-bignums │   63.10   62.78 +0.51 % │      174740781562      174066081948 +0.39 % │      244650770686      244641910979 +0.00 % │     483240     483268 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-coquelicot │   74.16   73.47 +0.94 % │      203008604921      202710926730 +0.15 % │      267689818976      267697792857 -0.00 % │     654696     654612 +0.01 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴───────────────────┘
~~~

**Review by ejgallego — APPROVED** [review]
Ok then.

**Pull request merged**
