### PR TITLE
Make multiplication of Cauchy reals transparent and accelerate it

### PR DESCRIPTION
**Pull request by VincentSe**
**Kind:** feature

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
More precisions on the PR:

This PR is the implementation of a proposition by @silene of splitting `QCauchySeq_bounded` into a purely computational term and a proof that the term satisfies the property, with the objective of computing with constructive reals.

There is no more essential contents as far as I understood.

@thery was a member of the discussion with @silene and @VincentSe too, so I think it is ok to assign and to plan to merge say by Tuesday (if no other comments by then).

**Comment by VincentSe** [comment]
@herbelin I just pushed the other idea of @silene, which is to use binary integers, so that large precisions like 2^128 are very fast to compute. It also simplifies many proofs.

**Review by herbelin — COMMENTED** [review]
OK for the change to binary positive integers, but I'm a bit afraid about the message to pass about the  status of the constructive and abstract reals. It seems that you changed quite a lot of statements, so if you think that this may still happen after 8.12 is released, we should be explicit that this part of the library is still "experimental" and liable to evolve.

Maybe could we plan a virtual meeting at some time and start from the coqdoc export of the library to see how to document it better. For instance, some comments could already be of the `(**` form rather than simply `(*`.

**Comment by VincentSe** [comment]
@herbelin It is not recommended to use Cauchy reals directly, rather use Abstract constructive reals (which did not change in this PR). Cauchy reals are simply a proof that the structure `ConstructiveReals` is inhabited, which in turn proves that the classical reals `R` exist.

That being said, we can improve Cauchy reals when possible. Here 300 lines of code were removed, and binary integers compute a lot faster than unary integers, and take much less memory.

**Comment by VincentSe** [comment]
Hi @herbelin would you mind merging ?

**Comment by Zimmi48** [comment]
@VincentSe If it is not recommended, is this documented somewhere?

**Comment by VincentSe** [comment]
@Zimmi48 At the moment no. What is the best place to write this documentation ?

**Comment by herbelin** [comment]
> What is the best place to write this documentation ?

I would say at the top of the corresponding file (or, if succinct enough, in the file `doc/stdlib/index-list.html.template`).

> would you mind merging ?

Ah sorry, after your second push, it stopped to be clear to me that the PR was ready on your side.

**Comment by VincentSe** [comment]
@herbelin @Zimmi48  Tonight I'll write a warning at the beginning of file `ConstructiveCauchyReals.v` that it is not meant to be directly imported, and that users should rather import `ConstructiveReals.v`.

**Comment by Zimmi48** [comment]
Unfortunately, we don't yet have a mechanism for private modules (or even private objects within modules).

**Comment by Zimmi48** [comment]
Maybe you can also add a note in the 8.11 release notes where it was said that the `ConstructiveCauchyReals` module was introduced that it is not meant for direct use.

**Comment by VincentSe** [comment]
@herbelin @Zimmi48 It is documented at both places now. I have nothing else to develop in this pull request, can you merge ?

**Comment by herbelin** [comment]
Will give one more day for possible comments and merge tomorrow evening.

**Pull request merged**
