### PR TITLE
dune states target: respect user's global verbosity setting

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
Leaving it to @ejgallego.

**Review by ejgallego — APPROVED** [review]

**Review by ejgallego — APPROVED** [review]
This was aimed to be an usability help for those migrating, but I guess indeed that the side-effects of this are bad.

**Comment by ejgallego** [comment]
I had seconds thoughts tho; are you folks using this target?

I never use it myself, I either use the shim or `@check` so it could be the case the display hack is still useful for the intended audience?

**Comment by SkySkimmer** [comment]
I use it

**Comment by ejgallego** [comment]
> I use it

Ok, we can add a `states-verbove` or `vstates` target if there is further demand.

**Pull request merged**
