### PR TITLE
Faster computation of head equality in Ssrequality.rwprocess_rule.

### PR DESCRIPTION
**Pull request by ppedrot**
We only compute once the hnf reduction of the rewrite witness. This seems to be a critical path in metacoq.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/2178233571

**Comment by ppedrot** [comment]
The bench shows only noise but unfortunately metacoq is not running currently...

**Comment by ppedrot** [comment]
Metacoq bench, hopefully: https://gitlab.com/coq/coq/-/jobs/2189360515

**Comment by ppedrot** [comment]
```
┌──────────────────────────┬────────────────────────┬──────────────────────────────────────┬──────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                          │     user time [s]      │              CPU cycles              │           CPU instructions           │  max resident mem [KB]   │   mem faults    │
│                          │                        │                                      │                                      │                          │                 │
│             package_name │    NEW     OLD   PDIFF │           NEW            OLD   PDIFF │           NEW            OLD   PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├──────────────────────────┼────────────────────────┼──────────────────────────────────────┼──────────────────────────────────────┼──────────────────────────┼─────────────────┤
│        coq-metacoq-pcuic │ 568.55  730.59  -22.18 │ 2486111608680  3180219980471  -21.83 │ 3555394871939  [465](https://gitlab.com/coq/coq/-/jobs/2189360515#L465)2697093386  -23.58 │ 1491384  1663712  -10.36 │   0    0    nan │
│  coq-metacoq-safechecker │ 196.03  201.80   -2.86 │  855424896668   880755713068   -2.88 │ 1160523788420  1202021059045   -3.45 │ 1231796  1230508    0.10 │   0    0    nan │
│                 coq-core │ 105.74  106.98   -1.16 │  394494097526   386648783263    2.03 │  441923917967   442125417232   -0.05 │  278548   277872    0.24 │   0    0    nan │
│      coq-metacoq-erasure │  64.96   65.59   -0.96 │  279249013751   281722519388   -0.88 │  426398077435   431350584010   -1.15 │ 1088344  1112444   -2.17 │   0    0    nan │
│     coq-metacoq-template │  78.58   78.53    0.06 │  33747271[470](https://gitlab.com/coq/coq/-/jobs/2189360515#L470)3   336934745472    0.16 │  509207632805   509190385570    0.00 │  911028   911212   -0.02 │   0    0    nan │
│               coq-stdlib │ 414.76  413.47    0.31 │ 1489616037930  1484357812531    0.35 │ 1417584964633  1427306370320   -0.68 │  607796   608052   -0.04 │   0    0    nan │
│ coq-metacoq-translations │  20.39   20.30    0.44 │   88412634774    88067073925    0.39 │  155610405278   155666[471](https://gitlab.com/coq/coq/-/jobs/2189360515#L471)136   -0.04 │  933536   933212    0.03 │   0    0    nan │
└──────────────────────────┴────────────────────────┴──────────────────────────────────────┴──────────────────────────────────────┴──────────────────────────┴─────────────────┘
```
So many cycles burnt uselessly...

**Comment by ppedrot** [comment]
Rerunning a full bench just in case the switch to whd-lazy had unforeseen effects: https://gitlab.com/coq/coq/-/jobs/2189555265

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now this big speedup

**Pull request merged**
