### PR TITLE
Miscellaneous ring improvements in code + error messages

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** cleanup / error messages

The PR basically:
- thread the evar_map functionally in the code of `ring.ml`
- standardize the naming evd -> sigma in `ring.ml`
- provides more informative user error messages

Co-Authored with @VincentSe.

### CODE REVIEW

**Review by ppedrot — COMMENTED** [review]
Code changes are fine but the documentation needs to be adapted accordingly for the message tweaks.

**Comment by herbelin** [comment]
> Code changes are fine but the documentation needs to be adapted accordingly for the message tweaks.

As far as I could see the messages which are modified in the PR are not documented.

I'm otherwise a bit reluctant to document them, as I consider this kind of documentation fragile (even if useful!). There should be a direct way to link error messages from the code to the documentation, I don't know exactly how though. Maybe with a shared index and each `user_err` accepting as argument a tag which has to be registered in the index, and the `.. exn::` command of the reference manual being also able to take as argument the same tag, then the compilation of the reference manual either getting the error message from the code via the tag, or checking that it coincides.

PS: The reference manual mentions errors "Cannot find a declared ring structure over @term" and "Cannot find a declared ring structure for equality @term" but the code mentions only the former. Should we remove the latter?

PS2: I made extra small changes to adjust the capitalization of sentences between the refman and the code for those messages which are mentioned in the reference manual.

**Comment by ppedrot** [comment]
Fair enough, that's fine then.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
This is a refactoring so I'll leave a short amount of time for comments before merging.

**Pull request merged**
