### PR TITLE
Coqinit split init_runtime to better support having multiple docs

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlays:
- https://github.com/coq/vscoq/pull/945

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@gares are you merging?

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
