### PR TITLE
[release] V8.18 backports

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
Good trick ;-)

**Comment by gares** [comment]
@coqbot run full ci

**Comment by Zimmi48** [comment]
> Good trick ;-)

Closing and reopening to get a CI run? You don't need to do this anymore. It's superseded by `run light CI` / `run full CI`.

**Comment by gares** [comment]
I got the wrong base when I opened the PR, the branch was not created on gitlab...

**Comment by gares** [comment]
This is the last one @maximedenes

**Pull request merged**
