### PR TITLE
Split Universes

### PR DESCRIPTION
**Pull request by SkySkimmer**
This completely deprecates universes.ml in favor of
- some misc function moves when they're helpers only used in some module
- UnivNames for dealing with universe user names (independent of the others, maybe should live in `library`?)
- UnivGen for fresh universe generation (ie the universe counter and functions around it) (independent of the others)
- UnivSubst for non-kernel universe substitutions, including `nf_evars_and_universes_opt_subst`
- UnivProblem for constraint generation (the old Universes.Constraints) (Universes.Constraints became UnivProblem.Set, is that OK? see uses for what it looks like in practice) (depends on UnivSubst because it defines its own substitution functions)
- UnivMinim for universe minimisation (depends on UnivSubst as it uses substitutions)

Universes is just a bundle of deprecated aliases now.

### CODE REVIEW

**Review by herbelin — COMMENTED** [review]
Makes sense to me (but I'm not the expert).

**Comment by ejgallego** [comment]
cc: #6414

**Review by gares — APPROVED** [review]
STM & SSR: OK

**Review by forestjulien — APPROVED** [review]

**Review by PierreCorbineau — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Someone self-assign this PR please.
Most likely seem to be @mattam82 or @ppedrot.

**Review by ppedrot — APPROVED** [review]
I'm not completely convinced by the cambrian explosion of universe-related modules, but there also seems to be a fair amount of clean up in this PR, so I'm still supportive.

**Review by mattam82 — APPROVED** [review]
I'm ok with the splitting and the renamings.

**Comment by SkySkimmer** [comment]
Please ping me when a needs: rebase appears.

**Comment by ppedrot** [comment]
@SkySkimmer doesn't that appear in the list of updated PR that mention you?

**Comment by SkySkimmer** [comment]
I hope we can merge before I make a mistake copying changes around.

**Comment by ppedrot** [comment]
@SkySkimmer Sorry, merging one of your other PRs seems to have triggered a need for rebase here again...

**Comment by SkySkimmer** [comment]
Rebased (this one was easy)

**Pull request merged**
