### PR TITLE
[plugins] Remove Derive plugin.

### PR DESCRIPTION
**Pull request by ejgallego**
There was some discussion about whether this plugin was still
supported or should be moved to an external repository; it also raised
some questions about integration with the STM.

We submit this commit as a testing/RFC, and we also proceed to trim
`Proof_global` a bit as we would eventually like to get rid of it.

### CODE REVIEW

**Comment by aspiwack** [comment]
I would have preferred if the first step of this PR would have been to phone me.

Can I enquire what the questions are about integration with the STM? (do avoid weasel words in PR title, they're not helpful to the passer-by)

I'm ok with derive moving to being an external plugin. That was the plan all along, anyway. I didn't do it because it is the only code that tests `start_dependent_proof`. But now there is Travis, and Jenkins, and such. So we could move this to Opam and make some of the CI build it.

Do _not_ remove `start_dependent_proof`, however. It's part of the API as it was designed. In fact, the reason why I wrote `Derive` in the first place was to test `start_dependent_proof` (and before you asked: yes, I did find bugs in the process. Actually, I believe realised the API was a tad weak, and I had to make some changed to the exposed type). Also because it was kind of neat, of course.

**Comment by herbelin** [comment]
Hi @ejgallego: may I suggest that we serialize questions! We are at D minus 6 of the 8.7 freeze, there is still a rough estimation of 80 pending pull requests to be treated by then and Travis is over-saturated. I understand that you'd like a discussion to happen on `Proof_global` and `derive`, and I'm sure that, made open and factual, this will lead to a very interesting discussion. I understand also that this PR is just a RFC non related to 8.7 and that it can happen asynchronously to 8.7 (and without charging Travis) but it seems to me that it could be reasonable to also concentrate on 8.7 at the current time. [And to clarify for @aspiwack, there was no such discussion about `Proof_global` and `derive` at the last WG.]

**Comment by ejgallego** [comment]
> I would have preferred if the first step of this PR would have been to phone me.

Phones are so old fashion :D come on! This PR is a "Request for Comments", however in fact I forgot to put you as a reviewer but this was my original plan, sorry for that. However I was told that:

> I'm ok with derive moving to being an external plugin. That was the plan all along, anyway.

so that's why this PR got into my TODO list.

> Can I enquire what the questions are about integration with the STM?

The commit that lead me to look at this plugin is in fact db65876404c7c3a1343623cc9b4d6c2a7164dd95 as I  (and neighboring commits) IMHO it doesn't provide the details on how this solution is the correct choice and how does it integrate with the rest of the design. In particular, now we have two (really 3) methods to determine opacity, IMHO we should stick to one.

Which brings me to:

> it is the only code that tests `start_dependent_proof`

I have to say that indeed this is the strongest reason for the removal of such API; IMHO we should never introduce API and features without strong use cases, and I think we can all name quite a few features already present in Coq that meet this definition, or are justified only by _toy_ examples. What good is an API without users? It is my impression that derive is not very used in the wild; so the whole package hasn't been tested (and I wouldn't be surprised if it had any bugs).

> Do not remove `start_dependent_proof`

I am personally neutral on this one as I am not an expert on this subsystem; however the fact that no other plugin seems to need it may well be an indicator towards its non-survival.

@herbelin sorry, indeed this is low priority, but I am myself in 8.8 mode and need to see what is going on with the `GuaranteesOpacity` that was introduced specifically for this plugin and had a medium impact on the STM, in order to implement the new document model at Le Croisic.

Thanks for the feedback guys!

**Comment by ejgallego** [comment]
Ah regarding `Proof_global` we have been discussing about it for some time (not "formally"), and we all seem to agree that it would be great to have less and less of it, in particular by removing `Proof_global.pstates` and threading it along the rest of the env.

**Comment by gares** [comment]
One thing that impacts the STM is that this plugin is the only one needing Doen'tGuaranteeOpacity, i.e. the only piece of code that puts an exception to Qed producing opaque proofs.

Frankly I never understood why that was needed. Arnaud could you explain that?

**Comment by ejgallego** [comment]
> this plugin is the only one needing Doen'tGuaranteeOpacity

Note that this is not the case now! In fact, since the addition of that parameter for Derive, some other parts of the code have started to use it!

[And indeed due to these dependencies is not trivial to remove now]

**Comment by maximedenes** [comment]
> some other parts of the code have started to use it!

Do you know which ones? This is worrying, so making a list would help us make a plan to remove it step by step.

**Comment by ejgallego** [comment]
Well it is used in `Obligations` and in the main classifier for polymorphic and discharging defs . Note that "removal" of the feature is not enough, some deeper redesign of the scheduling is likely needed.

**Comment by aspiwack** [comment]
@ejgallego 
> Phones are so old fashion :D come on!

Fax then.

My point was just that it helps making this sort of choices to have clarity on the reasons behind the existence of a particular piece of code or API design. It's kind of good homework to do. It makes the PRs better too.

> >it is the only code that tests start_dependent_proof
>
> I have to say that indeed this is the strongest reason for the removal of such API; IMHO we should never introduce API and features without strong use cases, and I think we can all name quite a few features already present in Coq that meet this definition, or are justified only by toy examples. What good is an API without users? It is my impression that derive is not very used in the wild; so the whole package hasn't been tested (and I wouldn't be surprised if it had any bugs).

I will have to disagree with this. This is all fine when your interfaces are a closed world. You don't need a function that you don't use in the rest of the code. But because of the plugin, this also acts as a library so you do have to think ahead and design for the future. Otherwise, when a plugin requires a missing bit of API, it has to wait an extra release cycle to be able to compile against a current version.

The reason for `start_dependent_proof` was for things like `Program`. Where you start several goals, and you assemble the results somehow. That's not how `Program` is implemented. But it's easy to envision features that will want to leverage such API. The case in point being `Derive`. Which I wasn't thinking of when I designed the API, but really requires dependent goals at the start of the proof.

And it's a perfectly legitimate feature. But if you remove `start_dependent_proof` I don't think I can make it into a plugin at all.

@gares 
> One thing that impacts the STM is that this plugin is the only one needing Doen'tGuaranteeOpacity, i.e. the only piece of code that puts an exception to Qed producing opaque proofs.
>
> Frankly I never understood why that was needed. Arnaud could you explain that?

`Derive` produces two terms. One of them is always transparent.

The goal of `Derive` is to produce two terms: a definition and a specification.  The former is typically transparent, the latter is typically opaque. In Coq-ish terms it's more of a `sig` than an `ex`.

Since we have only one `Qed`-like command, it will not impact all goals. I chose it to impact the specification because it's the one we're ostensibly writing (`Derive` shows a single goal at the beginning of the proof, which stands for the specification, the definition is a shelved goal). Plus it's probably more interesting to make the specification transparent than the definition opaque.

At any rate, despite opening a proof, and despite closing it by `Qed`, there can be (and must, as it stands) transparent constants created by the command. Therefore, it is not correct to run this proof in parallel.

@maximedenes 
> Do you know which ones? This is worrying, so making a list would help us make a plan to remove it step by step.

Why is it worrying?

**Comment by gares** [comment]
@aspiwack is the proof really needed in order to synthesize the type and body of the transparent definition?

**Comment by aspiwack** [comment]
Not its type, it follows from the `Derive` statement itself.

But the body is deduced by running the proof (the proof term itself is not needed, but we still need to run the tactics).

The idea is that we start with a specification. In the case of Bird-style equational reasoning, it's an inefficient, but semantically obvious, implementation of the function we want to define (an executable specification). Then we apply successive rewriting (tactics) on the specification, until the appropriate definition is revealed. We then conclude the proof yielding the desired definition and it's defining property.

More:
- [Simple example: `scan_right`](https://gist.github.com/aspiwack/7787372#file-scan-v-L18)
- [More complex example with a link to the source material](https://gist.github.com/aspiwack/7787372)

**Comment by gares** [comment]
OK, I understand. Thanks for the pointers.

From the Stm perspective, the one could easily end the proof by a "new" keyword, like `End Derive`, that can be classified as `Defined` on the spot, rather than having `Derive` (that begins the proof) thread a boolean up to the Qed making it behave as Defined (from a scheduling perspective).

From the `start dependent proof` business I'm afraid I find it overkilling. One can achieve the same by `eexists` + `shelve` or something along these lines.  Why should a proof beginning this way have an ML API dedicated? Other constructs in Coq already make a few proof steps implicit today, for example `Lemma foo x : ...` starts with a bunch of intros.  I don't know if the API for starting a proof with a few tactics is general enough (to take an arbitrary tactic and not just `intros`), though, but that could be the way to go.

I think point 1 is already supported by Coq, a plugin can easily add an `End Derive` vernacular that
 ends a proof.  For point 2 we could check and eventually generalize the current API.

Best,

**Comment by ejgallego** [comment]
Well note that detection of "opaqueness" by looking at the closing word of the proof is indeed a bit inconvenient, even if well-adapted to the backwards traversal, I think it doesn't fit all use cases and this is the reason we have two mechanisms now. We should think a bit more about this one IMHO.

**Comment by ejgallego** [comment]
We had some more discussion about `start_dependent_proof` and friends yesterday, as we stumbled upon it due trying to clean up the `close_proof`path. In particular, there is a mismatch between what the proof terminator require and what the reality is; given an opening telescope of length `N`, the terminator is supposed to receive a list of N `definition_entry`which however doesn't map well to the shared `evar_map` among all the goals. (Example: side-effects are duplicated if we have a telescope)

This seems like a serious problem that will certainly require invasive fixing; I am wondering about terminators too; they seems to certainly introduce quite a bit of functionality duplication; maybe we should make such mechanism weaker.

**Comment by Zimmi48** [comment]
> From the start dependent proof business I'm afraid I find it overkilling. One can achieve the same by `eexists` + `shelve` or something along these lines. Why should a proof beginning this way have an ML API dedicated? Other constructs in Coq already make a few proof steps implicit today, for example `Lemma foo x : ...` starts with a bunch of `intros`. I don't know if the API for starting a proof with a few tactics is general enough (to take an arbitrary tactic and not just `intros`), though, but that could be the way to go.

Maybe the Derive plugin should be modified in such a way. Then, this would confirm that the `start_dependent_proof` function is really not needed and it could safely removed from the API.

**Comment by ejgallego** [comment]
> Maybe the Derive plugin should be modified in such a way. Then, this would confirm that the start_dependent_proof function is really not needed and it could safely removed from the API.

Well, that seems quite easy

**Comment by ejgallego** [comment]
Ups, I clicked the wrong button; indeed we had some discussion and so far it is not clear what to do here.

It really boils down to whether it is convenient for a single proof to create several top-level identifiers; IMO with the current architecture this creates more problems that it solves; but that doesn't necessarily mean that our architecture shouldn't be fixed instead.

**Comment by ejgallego** [comment]
Much interesting discussion here, however I don't think this is on the short-term roadmap as the current todo list is largely orthogonal to this change.

**Comment by ejgallego** [comment]
Hi folks,

I am reopening this as indeed I have found problem with the current implementation on some other unrelated PRs, and it seems it won't be easy to support the `Derive` code at least for some transitory state.

I will submit the refactoring PR soon, however the main problem is that the `Proofview.init` / `Prooview.return` API is not synchronized with the save_proof API, basically some parts of the code don't properly understand a proof returning several [or none! as in `class_tactics`] proof terms.

This is a very serious issues creating a large amount of code duplication for example in terminators.

IMHO the best way for now is to enforce that a `Proofview` run ultimately has a single goal; and once we fix the control inversion for that case, we could think of generalizing the API again [whcih would involve teaching `vernac` and `stm` about it]

**Comment by mattam82** [comment]
For what it's worth, I've been playing with the start dependent proof API for Equations lately, and:
- start_dependent_proof takes a telescope but I'd rather just give an evar_map of already ordered evars instead.
- it doesn't work with effects and admitted subgoals if you have multiple subgoals (I'm making this Equations mode experimental until it does support that).
- otherwise you do get constant entries for all your subgoals (which might dependent on each other) and it's nice
- I'm doing this in the hope to have a real term refinement mode (à la Agda/Idris) and it makes more sense to let the user just see the subgoals generated in proof mode rather than using obligations for that.

**Comment by ejgallego** [comment]
The proof refiment mode is a good point @mattam82 but why do you need the start dependent proof API?

I am all indeed for having an API that allows to generate several constant bodies, however I am afraid that we have to rework significant parts of the stm / vernac implementation to make that indeed work; so IMHO the quickest part is to remove that API for now, refactor the constant handling in these subsystems, and then re-implement a solution that is generic so for example the code doesn't have to be duplicated in each "terminator".

**Comment by mattam82** [comment]
I need the API because I want to start a proof with multiple subgoals depending on each other, which should ultimately give me multiple constants whose types depend on each other. I'm not sure why the current terminator setup couldn't be generalized to deal with admitted proofs or abstracted subproofs and custom opacity settings for each subproof: proof_object takes already a private_constants for each entry and Admitted could as well use a proof_object with multiple parameter_entry's. In other words I think it's mainly about reorganizing. In my use case, the user should be able to use abstract if he wants just some subproof to be opaque, and the closing "Qed" or "Defined" should apply globally to all subgoals, but I can see that Derive needs a different semantics where the main subgoal is opaque depending on the "Qed" or "Defined" but other subgoals are transparent. Obligations use a similar setting: the tool can know that some obligation _must_ be defined transparent otherwise guard checking will fail, for example. We could have a generic start_dependent_proof API that would tell for each subgoal if there is a requirement of transparency or not, and at the end of the proof generate the proof objects accordingly.

**Comment by mattam82** [comment]
That's a very good point @gares , it would be better to not overload Qed in the cases of derivations and multiple obligations of an attached program treated simultaneously. I suppose it's problematic from the STM view point as well, to do classification?

**Comment by gares** [comment]
Oh, and for `Program` I think it makes sense to let the user to say "this subgoal as to be made opaque" but please not via a call to abstract (the tactic of today). The use could just leave a mark in the proof term (eg a special identity function) of the corresponding evar, and then `End Program` will decide how to interpret it.
That is, let's try to avoid to give yet another use case of the current abstract.

**Comment by gares** [comment]
> I suppose it's problematic from the STM view point as well, to do classification?

Yes, this is exactly why I'm trying to help the removal of `Doesn'tGuaranteeOpacity` in the first place, and possibly of the higher order terminators (that I cannot even marshall and are morally part of the proof state).

**Comment by mattam82** [comment]
I think associating an `option transparency` to each initial goal (e.g. in Proofview.entry or elsewhere) to indicate forced transparency/opacity would be enough, no? That would only apply to the toplevel subgoals though, unlike what abstract is supposed to handle.

**Comment by gares** [comment]
That would work, but I thought you wanted to let the user decide "while closing the obligations" rather than beforehand.

**Comment by mattam82** [comment]
The issue is that I'd like to tell the user that it's not ok to define an obligation as opaque if it has some recursive prototypes in its context, so not every obligation can be made opaque.

**Comment by gares** [comment]
> The issue is that I'd like to tell the user that it's not ok to define an obligation as opaque if it has some recursive prototypes in its context, so not every obligation can be made opaque.

Then I guess `End Program` could ignore (and emit a warning) if the user marked as opaque a sub proof that cannot be opaque?

**Comment by mattam82** [comment]
How about solving the abstract issue in general by saying evar bodies can
be defined or opaque ? Only EConstr.to_constr would be allowed to unfold
these bodies when the proof is finished. During the proof, defined abstract
evars would not be unfoldable and not redefinable of course, maintaining
the abstraction. Is this a bad idea?

**Comment by mattam82** [comment]
@gares Yes, that should be doable.

**Comment by gares** [comment]
>  Is this a bad idea?

I think it is ok to add the metadata to the evarmap, but I don't know the code of the pretyper well enough to know how many clients unfold evars by hand (these would need to be patched in order to have the metadata taken into account).

**Comment by SkySkimmer** [comment]
`to_constr` is called in more places than proof end.
There are probably many places which assume that any evar left by `EConstr.kind` is definable.
So it would be tricky.

**Comment by mattam82** [comment]
I don't think many clients do that by hand thanks to EConstr and having this as an algebraic sum in the evar_body would help handle this cleanly I suppose. It would be great if we could remove all the constant building cruft from define_constant_by_tactic etc... Then the creation of abstracted constants could be done entirely at the end of the proofs. One problem with the idea of tagging in the term is that actually you want to maintain the abstract status of the subproof: typically, think of an arithmetic obligation that appears in a later goal, you don't want to unfold a proof by lia in the following subgoals. 
In particular, you want that later constants defined for dependent subgoals mention previously defined constants for their dependencies and not the actual proof terms. That's one thing obligations allow today that I can't reproduce with the current proof API.

**Comment by mattam82** [comment]
@SkySkimmer You mean if kind returns an evar then its undefined rather, I suppose?

**Comment by gares** [comment]
> One problem with the idea of tagging in the term is that

I fully agree, having a proper tag with an opacity meaning is way more powerful

**Comment by mattam82** [comment]
I think such a design would work with ltac:() as well, completely functionalizing the abstract part, so the trickiness could have some benefits. `abstract` would not longer be a tactical either, it could just refine to a new subgoal with the mark. Would such a design cause problems with par: ?

**Comment by gares** [comment]
> Would such a design cause problems with par: ?

No, it would be simpler to support actually

**Comment by ejgallego** [comment]
> I think associating an `option transparency` to each initial goal (e.g. in Proofview.entry or elsewhere) to indicate forced transparency/opacity would be enough, no? That would only apply to the toplevel subgoals though, unlike what abstract is supposed to handle.

Indeed @mattam82 something like this is the plan; the thing is that I considered that the best path tho would be to pass by an intermediate state where we (temporarily) remove the multiple proof bodies support, then reify `Qed` code handling so saving (calls to `declare_constant`) are done only once, and then we add support for this but indeed it has to go first in the STM level (which now is done in a very hackish way)

There may be other options.

Regarding the comment about `Proofview.init []`, the thing is that indeed we should make the API a bit stronger IMHO, and it would be good to start with an invariant where each `Proofview` instantiation is solving a single goal [and then the upper layers can be correct by construction and indeed handle proof saving]

But indeed as we have discussed some other times the story for the and-part of the engine refinement seems to be not fully developed so this is another instance of this problem IMO.

**Comment by aspiwack** [comment]
My review was required, but I don't know what to say.

I'm, honestly, disappointed to see this go. I quite liked this extension. It was cool, and rather practical. But ultimately, it is not my decision to remove this feature. It's not a technical decision _per se_. And there is no code to review. So I'm not sure what I can help with.

**Comment by Zimmi48** [comment]
Note that I think recent discussions on Coq-Club have made it clear that Derive had users, so I don't think it should get removed without consulting them. In fact, the best would be to keep it working even if its internals have to change.

**Comment by ejgallego** [comment]
@mattam82  could Equations subsume the functionality of Derive once it is using the new proof interface?

**Comment by ejgallego** [comment]
> I'm, honestly, disappointed to see this go. I quite liked this extension. It was cool, and rather practical. But ultimately, it is not my decision to remove this feature. It's not a technical decision _per se_. And there is no code to review. So I'm not sure what I can help with.

It is indeed a technical decision as we'd like to rework the interface in `proofs` and Derive is the only user. Indeed I do agree that the functionality that Derive provides is useful and maybe should be incorporated into Equations of the plugin resurrected once we have the reworked API.

Maintaining the plugin alive while we rework the API could be still done, however it is not easy as in order to enforce some invariants in the full save_proof path it'd be much more convenient to have the one proof == one term relation to hold for a while.

**Comment by gares** [comment]
> one proof == one term relation to hold for a while.

My personal take is that the wrong step was to say that `Derive...Qed` is the way one delimits "derivations". Something like `Derive.. End Derive` would have been more appropriate, since the terminator would have been easier to recognize (no `Doesn'tGuaranteeOpacity` thing) and `End Derive` would have been the code generating 2 terms (rather than Qed + hook to generate a second one).
The same for `Program...Next Obligation...Qed` where the last `Qed` generates the term for the last obligation plus finishes the program. I'd say `Program...End Program` would have made things simpler.

I'm saying that because `1 proof = 1 term` is not so clear to me. In both examples above one evar map is generated from the starting sentence and finally used to generate many terms by the ending sentence. In the middle one can imagine a single proof scripts (with eventually many initial goals). So this is 1 proof for many terms to me. And if make Program and Derive not overload `Qed`, then `Qed` can be only used to end 1 proof that generates 1 term.

@ejgallego are we on the same page?

**Comment by ejgallego** [comment]
> @ejgallego are we on the same page?

I think so; I am looking more at the proof save path tho so the vernac terminators don't matter here so much, as even the regular `Lemma... Qed` have problems there with the inversion due to the proof-level terminators.

**Comment by gares** [comment]
Are there non-trivial terminators other than the ones for program and derive?
Trivial ones should be hardwired to Qed, while the others hardwired to `End Program` and `End Derive` (so that we can drop the higher order argument and avoid the inversion of control).

**Comment by ejgallego** [comment]
> Are there non-trivial terminators other than the ones for program and derive?
> Trivial ones should be hardwired to Qed, while the others hardwired to `End Program` and `End Derive` (so that we can drop the higher order argument and avoid the inversion of control).

IMHO we should first relieve work terminators have to do, this is why the invariant is convenient.

Splitting them into an AST [I have a tree that tries that] is still nice, however you still have the problem of lots of non marshalleable data as in practice they use a closure with hooks etc...

**Comment by maximedenes** [comment]
> this is exactly why I'm trying to help the removal of `Doesn'tGuaranteeOpacity`

@gares what about universe polymorphic definitions? Today they carry that classification, and they are much more frequently used than `Derive`...

**Comment by ejgallego** [comment]
> @gares what about universe polymorphic definitions? Today they carry that classification, and they are much more frequently used than `Derive`...

That's a strange thing introduced by the Opacity commit I do think and it doesn't make a lot of sense.

Let's recall the problem: the current proof API only allows to specify opacity for one top_level constant, however `Derive` produces several. So instead of properly reifying the API we introduced this hack, so even if the `Qed` is opaque the system doesn't treat like that.

Needless to say how broken the approach is. Currently I do think that allowing one proof term per constant is the way to go in the cleanup [we will relay that later], as for example this is critical in the terminators path; given that this functionality is not very robust and little used it makes sense to remove the plugin, enforce the invariant, and then add to Equations / Program similar functionality.

**Comment by ejgallego** [comment]
In particular clients closing a proof should never ever have to call `declare_constant` and friends!

**Comment by gares** [comment]
I try to sum up here the discussion I had with Maxime yesterday.

I think it would be reasonable say `Qed` has one, single, meaning: it generates an opaque term.

If you have to generate two, 7, send an email, reboot your PC, you don't use `Qed` with a fancy terminator hook. You define a new terminator, eg `Derive ... End Derive.` and there you call appropriate API (that I don't think existed at the time of derive and maybe they still don't exist) to do what you have to do.

This is related but orthogonal to the `Doesn'tGuaranteOpacity` thing, that is an annotation in a `Fork` STM node that says: no matter how this proof is terminated, we are unable to process it in async mode. Given the meaning I guess I used it at some point to be sure we don't do univ-poly proofs in async mode (and I forgot about that, so I thought the flag could be removed).

So after all I'm not so sure anymore that removing derive would solve any problem.
Maybe the thing to do is to provide a decent API to start multiple related goals (cfr the talk by Matthieu at the last WG) and to save constants. Then changing the terminator of `Derive` from `Qed` to `End Derive` and simply implement it as such. WRT to the STM, I believe a `Derive` proof could just look like a sequence of commands (not even a fork/merge for now).

**Comment by ejgallego** [comment]
> So after all I'm not so sure anymore that removing derive would solve any problem.

It allows to reify terminators and to remove all the `assert false` paths when `proof_object.entries` is not a singleton list.

IMO that is pretty significant.

**Comment by ejgallego** [comment]
I think we could even have `Qed.` work for multiple terms, but we need to fully refactor the API and that is better done by temporarily going the one-object one-qed path, then to introduce a different API in the lines Matthieu explained and which can work with workers.

**Comment by ejgallego** [comment]
It seems we won't remove the `start_dependent_lemma` API anytime soon; so closing this for now.

**Pull request closed without merging**
