### PR TITLE
Remove SF testing until it is fixed.

### PR DESCRIPTION
**Pull request by Zimmi48**
Cf. WIP PR #11165.

**Kind:** infrastructure.

Temporary solution to be backported to v8.11 until #11165 is finished.

### CODE REVIEW

**Comment by ppedrot** [comment]
I don't think this is critical enough to get into the beta, we've been living with this warning for months already. So I'm postponing this to 8.11.0.

**Review by ejgallego — COMMENTED** [review]
I think this is the wrong fix, as SF is already fixed upstream. We should instead request them for a new release or host a fixed tarball on our own while they do fix the release.

We can indeed close the "SF not working bug" if that's gonna be a problem.

**Comment by ejgallego** [comment]
Note that at least my view is that SF has a special grandfathered status; it is a very important development and moreover they have strong reasons as not to follow regular open source hosting.

**Comment by Zimmi48** [comment]
Fine.

**Pull request closed without merging**
