### PR TITLE
[declare] Call interp_proof_using only once per mutual block.

### PR DESCRIPTION
**Pull request by ejgallego**
Follow-up to https://github.com/coq/coq/pull/18890

Not sure what the effect on this will be, doing as suggested by the PR
discussion.

### CODE REVIEW

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by herbelin** [comment]
Going to merge soon.

**Review by herbelin — APPROVED** [review]
Morally, "using" clauses are common to all components of a co/fixpoint from the moment they are really recursive. No need to compute n times the same clause (knowing that each individual body already contains all the components of the co/fixpoint).

**Comment by herbelin** [comment]
@coqbot merge now

**Pull request merged**
