### PR TITLE
[ci] call dmesg after quick/async jobs to detect OOM

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
The output of `dmesg` is quite long. Maybe it could make sense to redirect it to a file that would be preserved as an artifact? Let me know what you think.

**Comment by gares** [comment]
That would be nicer but I don't know how to do it in 2 minutes, so ...

**Comment by Zimmi48** [comment]
> That would be nicer but I don't know how to do it in 2 minutes, so ...

I guess the "redirect to a file" part you know. As for how to preserve it as an artifact, see these examples:

https://github.com/coq/coq/blob/09a8989d98219e974ceb7a2620686117c9ad6fef/.gitlab-ci.yml#L201-L205


https://github.com/coq/coq/blob/09a8989d98219e974ceb7a2620686117c9ad6fef/.gitlab-ci.yml#L128-L134

**Comment by gares** [comment]
done, thanks for the hints.

**Comment by SkySkimmer** [comment]
This is broken as it stops uploading the artifact when succeeding, so eg validate:quick gets nothing (and due to 633b462dc0c0211d353faebc6acbe6393c1566b6 (https://github.com/coq/coq/pull/12111) it succeeds)
see eg https://gitlab.com/coq/coq/-/jobs/745262366

**Comment by Zimmi48** [comment]
Oops, indeed. Then, the fix is just to remove the `when:` line since it is the default since #13024.

**Comment by Zimmi48** [comment]
Do we also need to repeat the artifact paths defined in the build template?

https://github.com/coq/coq/blob/6b991f6111006cf4635b3321232d61c4f5c54f40/.gitlab-ci.yml#L76-L81

**Comment by SkySkimmer** [comment]
Just add dmesg to the template IMO

**Comment by ejgallego** [comment]
> Just add dmesg to the template IMO

IMHO we have no business dealing with kernel stuff, it is OK as a hack for a couple of cases, but we shouldn't assume it is available, and in the large majority of cases it is a waste of space [and dmesg can take many MiBs]

**Comment by gares** [comment]
How do I detect an OOM otherwise?

**Pull request merged**
