### PR TITLE
Cleanup noisy prefixes

### PR DESCRIPTION
**Pull request by SkySkimmer**
These bug me every time I look at them, they're not accessible outside section.ml / ustate.ml so there's no ambiguity to resolve.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
I like prefix-free record names. Tho, in general wrapping these into a module, for example `module S = struct type t = { } ` tends to work a bit better for my taste.

**Review by ppedrot — APPROVED** [review]
I actually prefer it the other way around, amongst others because it makes file search easier, even if this is only used locally. But I guess it's fine this way also.

**Comment by SkySkimmer** [comment]
No assignee?

**Comment by ppedrot** [comment]
Will merge soon.

**Pull request merged**
