### PR TITLE
Fix copyright date.

### PR DESCRIPTION
**Pull request by Zimmi48**
Initially found by Maxime Dénès and implemented by Matthieu Sozeau (@mattam82) in #14569.

### CODE REVIEW

**Comment by Alizter** [comment]
Would it be too fragile to get the current year and use that instead?

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by Zimmi48** [comment]
> Would it be too fragile to get the current year and use that instead?

This would be a step back in terms of build reproducibility. That being said, this may still be happening for some reason or another. See #7378.

**Comment by Alizter** [comment]
Hmm, in which case why not have a variable for the current year which we set manually. But then compare it with the actual year and throw a warning/error (at least one the devs can see) if they are not aligned. That way, it reminds you to update the year whilst being reproducible.

**Comment by Zimmi48** [comment]
Yeah, that does sound pretty reasonable to me. Feel free to open a PR for this or to open a new issue with this idea or to edit the one I linked if you think this is related. You can also cc `@cpitclaudel` (the original author of the Sphinx-based refman infrastructure) to get his opinion.

**Pull request merged**
