### PR TITLE
Faster reduction for canonical structure registering.

### PR DESCRIPTION
**Pull request by ppedrot**
We use the kernel reduction to shave off lambda abstrations from the head of the term, instead of the notoriously slow Reductionops variant. This furthermore simplifies the code since we don't have to perform unsafe conversions from econstr to constr.

On a microbenchmark that consists in
```
Require Import mathcomp.all.all
```
the time goes down from ~2.2s to ~1.5s on average.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1486708253

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
```
│              coq-fiat-core │   68.51    65.77   4.17 │   290714573257    278666314572   4.32 │   429283420719    409242511147   4.90 │  485064   485332  -0.06 │   0    0    nan │
```

**Comment by ppedrot** [comment]
@gares could be noise, it's hard to tell without looking at the precise per-line data.

**Comment by SkySkimmer** [comment]
This is running on ci-coq-03.sophia.inria.fr which has previously claimed fake slowdowns.

**Comment by gares** [comment]
Hum, I've enabled that one since this bench was waiting for a worker...

**Comment by ppedrot** [comment]
Oh, so this is running on the workers that were disabled precisely because they were producing unreliable results :worried: I guess we'll have to rerun the bench to get meaningful results then.

**Comment by gares** [comment]
My bad. Said that, having 4 machines idle is silly. If we don't figure out to make them reliable bench workers we should al least make them build workers.

**Comment by ppedrot** [comment]
Let's rerun: https://gitlab.com/coq/coq/-/jobs/1501591404.

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │  327.50   332.83  -1.60 │   909010735071    924379737513  -1.66 │  1595875532208   1594976830001   0.06 │  918692   919128  -0.05 │   0    0    nan │
│          coq-mathcomp-field │  217.03   220.25  -1.46 │   604350376034    613768844271  -1.53 │   918653113947    935828921625  -1.84 │  660164   664796  -0.70 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1032.50  1041.72  -0.89 │  2877400532099   2902392705905  -0.86 │  4597041061980   4616713574601  -0.43 │  912444   959592  -4.91 │   0    0    nan │
│                 coq-bignums │   55.11    55.58  -0.85 │   152970459691    153372683729  -0.26 │   207057761016    207066753324  -0.00 │  463460   463412   0.01 │   0    0    nan │
│                    coq-hott │  296.67   299.16  -0.83 │   816034010183    820075922277  -0.49 │  1268278728464   1268356396270  -0.01 │  570928   571032  -0.02 │   0    0    nan │
│                  coq-stdlib │  412.01   415.05  -0.73 │  1152028998948   1159411713521  -0.64 │  1470055514113   1470174896987  -0.01 │  597420   597368   0.01 │   0    0    nan │
│      coq-mathcomp-character │  147.80   148.79  -0.67 │   410484693321    413540489546  -0.74 │   576560478920    581213046413  -0.80 │  732316   724320   1.10 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │ 1616.77  1624.45  -0.47 │  4499392897946   4519908840900  -0.45 │  7153730341845   7154215131756  -0.01 │ 1073680  1074768  -0.10 │   0    0    nan │
│       coq-mathcomp-solvable │  168.32   169.11  -0.47 │   468734820986    470143683911  -0.30 │   665452869214    665534763127  -0.01 │  692992   691792   0.17 │   0    0    nan │
│                 coq-unimath │ 4616.42  4637.39  -0.45 │ 12849105701095  12909291850877  -0.47 │ 24877637687324  24875284814669   0.01 │ 3722164  3728032  -0.16 │   0    0    nan │
│            coq-math-classes │  171.78   172.52  -0.43 │   479103877849    481651214475  -0.53 │   642057280676    642052114777   0.00 │  481968   481992  -0.00 │   0    0    nan │
│                    coq-corn │ 1455.89  1462.10  -0.42 │  4051050276074   4068183654215  -0.42 │  5872695606518   5872494750644   0.00 │  822896   822848   0.01 │   0    0    nan │
│        coq-mathcomp-algebra │  138.95   139.52  -0.41 │   385665808763    387584787749  -0.50 │   502481391318    505677557302  -0.63 │  556492   556504  -0.00 │   0    0    nan │
│             coq-fiat-crypto │ 4828.02  4847.48  -0.40 │ 13407876623520  13462016916633  -0.40 │ 23770070667624  23773256831566  -0.01 │ 2233556  2229060   0.20 │   0    0    nan │
│                  coq-geocoq │ 1319.59  1324.76  -0.39 │  3678856652350   3689281716087  -0.28 │  5422560095493   5422055982283   0.01 │  984504   984480   0.00 │   0    0    nan │
│            coq-fiat-parsers │  580.74   582.75  -0.34 │  1624455486454   1629199868691  -0.29 │  2491407870493   2490877480250   0.02 │ 3485420  3485420   0.00 │   0    0    nan │
│             coq-lambda-rust │ 1265.67  1269.51  -0.30 │  3521529009847   3532231401927  -0.30 │  5084975950356   5083372589884   0.03 │ 1112412  1112276   0.01 │   0    0    nan │
│       coq-engine-bench-lite │  291.62   292.39  -0.26 │   821769950279    823324410434  -0.19 │  1495709223243   1500740323478  -0.34 │ 1411884  1411820   0.00 │   0    0    nan │
│                   coq-verdi │   98.50    98.74  -0.24 │   271616222832    270566407027   0.39 │   380485341971    379526507645   0.25 │  545176   544796   0.07 │   0    0    nan │
│                coq-bedrock2 │  302.56   303.28  -0.24 │   837908314782    840626680225  -0.32 │  1493034891196   1492451034178   0.04 │  778660   799996  -2.67 │   0    0    nan │
│  coq-performance-tests-lite │ 1545.33  1548.88  -0.23 │  4310360969082   4324263036258  -0.32 │  7113622175389   7113682776157  -0.00 │ 2085076  2085040   0.00 │   0    0    nan │
│              coq-verdi-raft │ 1092.80  1094.81  -0.18 │  3042730337889   3049145437223  -0.21 │  4310679835792   4309782019536   0.02 │  916980   916636   0.04 │   0    0    nan │
│                   coq-color │  483.08   483.79  -0.15 │  1346605596011   1348547100748  -0.14 │  1701510552483   1699812303898   0.10 │ 1155736  1155688   0.00 │   0    0    nan │
│       coq-mathcomp-fingroup │   48.01    48.07  -0.12 │   132788039213    133027302268  -0.18 │   186721875126    186729182580  -0.00 │  482584   482820  -0.05 │   0    0    nan │
│               coq-fiat-core │  108.43   108.55  -0.11 │   306252100427    306027769680   0.07 │   414470349819    413007247242   0.35 │  480312   480320  -0.00 │   0    0    nan │
│               coq-perennial │ 7191.86  7199.36  -0.10 │ 20029920172823  20054877973949  -0.12 │ 30693766773495  30694199560605  -0.00 │ 2981016  3046148  -2.14 │   0    0    nan │
│                coq-rewriter │  682.18   681.92   0.04 │  1892946265104   1892965473312  -0.00 │  2933063994680   2933064797973  -0.00 │ 1073876  1143744  -6.11 │   0    0    nan │
│                    coq-core │  108.05   107.98   0.06 │   299054018232    298673610639   0.13 │   462601338601    462749327247  -0.03 │  298564   298584  -0.01 │   0    0    nan │
│               coq-fourcolor │ 2544.21  2540.81   0.13 │  7092940868718   7082526204577   0.15 │ 12239868217151  12237392578911   0.02 │  732820   732772   0.01 │   0    0    nan │
│                   coq-flocq │  146.27   146.01   0.18 │   405367296426    405796253979  -0.11 │   504019733584    503981784961   0.01 │  810092   810112  -0.00 │   0    0    nan │
│              coq-coquelicot │   68.98    68.84   0.20 │   187990579064    187770851141   0.12 │   242052374751    241057338863   0.41 │  558892   558732   0.03 │   0    0    nan │
│      coq-mathcomp-ssreflect │   54.35    54.18   0.31 │   147501467728    147513491719  -0.01 │   191519667668    191547283568  -0.01 │  530424   530360   0.01 │   0    0    nan │
│                 coq-coqutil │   59.73    59.21   0.88 │   165467765155    164914076294   0.34 │   218856179912    218285238063   0.26 │  600060   600100  -0.01 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
`coq-mathcomp-field` is probably showing a small albeit real effect of this PR, the rest is noise.

**Review by SkySkimmer — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now this fine pr

**Pull request merged**
