### PR TITLE
Don't refresh universes when pretyping cast

### LINKED ISSUE #19161: casts incorrectly refresh universes
### Description of the problem

Check introduce fresh universe variables in places where it looks reasonable to report a failure.

### Small Coq file to reproduce the bug

```coq
Set Universe Polymorphism.
Set Printing Universes.
Section test.
  Universe u.
  Check Type@{u} : Type@{Set+1}.
  Fail Definition a := Type@{u} : Type@{Set+1}.
  Fail Check (fun A  : Type@{Set+1} =>  A) Type@{u}.
End test.
```

### Version of Coq where this bug occurs

8.19.0

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #19161

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Seems nothing relied on it

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
If no complaints, I'll merge soon.

**Comment by Janno** [comment]
Could this have a positive or even negative impact on performance? I have seen files where a fresh universe can make the difference between fast and slow.

**Comment by ppedrot** [comment]
We can run a bench if you're concerned, but I'm not expecting much change. @coqbot bench

**Comment by Janno** [comment]
Thanks! I think the bench looks perfectly fine with a very slight tendency towards a bit of a speedup.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
