### PR TITLE
Add optimize_heap tactic for #6488

### PR DESCRIPTION
**Pull request by psteckler**
This PR partially addresses the request in #6488 to have a tactic equivalent to `Optimize Heap`.

The request to have a tactic that works along the lines of `Optimize Proof` remains unfulfilled, because it's not clear how that should work.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by maximedenes** [comment]
The linter complains.

**Comment by psteckler** [comment]
Pushed fix for linter issue, squashing with previous commits.

**Comment by psteckler** [comment]
Incidentally, knowing the existence of `Optimize Heap`, which has no logical effect, makes me feel less guilty about the reviled `HashConsing` option proposed in #1013.

**Comment by ppedrot** [comment]
@psteckler I'd personally take it the other way around: it's a good hint that there shouldn't be such a tactic...

**Comment by psteckler** [comment]
@ppedrot Silly me! :-)

**Comment by psteckler** [comment]
The PR now passes the linter. I canceled the rest of the Travis job.

**Comment by Zimmi48** [comment]
@psteckler You may as well let Travis run: it is not overloaded these days (not much activity) and @maximedenes is on vacation so no PR will be merged until next week.

**Pull request merged**
