### PR TITLE
Warn when Collection and Variable names clash

### LINKED ISSUE #13296: Constants and collections clash without error or documentation.
## Description of the problem

The following code does not raise an error, and the behavior is undocumented. 

```coq
Section Test.
Variables (b : bool) (n : nat) (All : unit).
Collection n := b.

Lemma foo : True.
Proof using n.
trivial.
Qed.

Lemma bar : True.
Proof using All.
trivial.
Qed.
End Test.

Check foo : bool -> True.
Check bar : bool -> nat -> unit -> True.
```

I detected this problem while looking at the new attribute syntax `using` in #13183, and suggesting that we switch to the syntax `{x y z}` for single names and `c` for collections, as in commands `Proof using ({x y z} + c) - {y}` and `Collection c' := ({x y z} + c) - {y}`, and attribute `#[using="({x y z} + c) - {y}"]`.

I suggest, if it is doable, we keep backward compatibility the current syntax with a warning ("deprecated syntax collection") when there is no ambiguity, and raise an error otherwise.

#### Coq Version
Coq 8.10 at least but most probably from Coq 8.5 and above.

### PR DESCRIPTION
**Pull request by WojciechKarpiel**
Closes  #13296

This PR adds "Collection"-related and "Proof using"-related warnings for some corner cases.
It has one breaking change (I don't think this affects anyone though):

* Error is signalled when user tries to define collecion named "All" (was previously allowed, but defining such collection had no effect)

Otherwise, there are new warnings without any semantics change.
Warning is signalled when:

* User redefines a collection
* User defines collection using name of already existing variable
* User invokes "Proof using" using collection whose name clashes with already existing variable (repeating previous warning)
* User invokes "Proof using" using "All" collection, if "All" is also name of a variable

- [x] Added / updated **test-suite**.

- [ ] Added **changelog**. <- This is insignificant change, should it get a changelog?
- [x] Added / updated **documentation**.
  - [x] Documented any new / changed **user messages**.

### CODE REVIEW

**Review by jfehrle — COMMENTED** [review]
A few quick tweaks.  I'll leave it others to consider whether we should have these warnings.

**Review by gares — COMMENTED** [review]
Thanks for the contribution! Here a few suggestions.

**Review by gares — APPROVED** [review]

**Comment by Zimmi48** [comment]
>these warnings could become errors

But is that a desirable change? If yes, then the plan to turn this into errors should be documented (in the refman and the changelog). If not, then another category should be used (I think we all agree on the use of `proof-using`.

**Comment by gares** [comment]
> But is that a desirable change?

I'd say so. @WojciechKarpiel what do you think?

**Comment by WojciechKarpiel** [comment]
I think that turning these warnings into errors would be good. In general, I think that the less footguns are available the better

* User redefines a collection -- I think it should become error, this is mostly a footgun
* User defines collection using name of already existing variable -- error, this is a footgun
* User invokes "Proof using" using collection whose name clashes with already existing variable -- after above warnings are turned into errors, I think the only way for this to appear is to first define a Collection and then define a Variable. In such scenario, user might assume that later-defined variable takes precedence, which is not the case. I think this should become an error because it's a counter-intuitive footgun. The main argument against turning it into error is that reporting the error  is separated from the root cause (defining a thing with clashing name). I don't think that error should be reported when declaring the new variable, because `Proof using` might not be used after new declaration.
* User invokes "Proof using" using "All" collection, if "All" is also name of a variable -- I think this should also become error but "All" should be an allowed variable name by similar reasoning to above

**Comment by gares** [comment]
OK, then @Zimmi48 would like a changelog entry (suggesting these warnings will become errors), see `dev/tools/make-changelog.sh` for a script which creates a template changelog entry for you (you will have to open a new PR for submitting this file).

About the manual, @Zimmi48 what do you want exactly? Now these warnings are documented. Is there a special "tag" to be put?

**Comment by Zimmi48** [comment]
Something like this to insert somewhere:

```rst
.. deprecated:: 8.15

   Redefining a collection, defining a collection with the same name as a variable [...]
   are deprecated.
   See the documentation of the warnings below.
```

**Pull request merged**
