### PR TITLE
Remove mathcomp_base job

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not needed since elpi supports newer ocaml.

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot run full CI

**Review by Zimmi48 — APPROVED** [review]
This will save runner minutes, so this is probably a good idea, but this will delay the build of the jobs that depend on it (and require the mathcomp build to fully pass for these jobs to run at all).

**Comment by Zimmi48** [comment]
@coqbot run CI now

**Comment by SkySkimmer** [comment]
Added " Split running the mathcomp test suite to its own job " commit

**Comment by ejgallego** [comment]
The rationale for building some jobs with the flambda version and other with the base one was that if we would switch everything to the flambda Coq (which is what makes sense from a speed point of view) , we wouldn't test the base version enough.

But maybe it is time we refine this policy.

**Comment by ejgallego** [comment]
By refinement I mean, we could only do basic checks on the other compilers, and run everything with the flambda one, then have once a month a full rebuild with other compilers.

That way users and platform have at least one known to work combination.

**Comment by SkySkimmer** [comment]
IIRC we saw 1 difference a while back between flambda and non flambda, so I'm not worried about it.

**Comment by SkySkimmer** [comment]
flambda may be slower for the jobs with native on though?

**Comment by ejgallego** [comment]
> flambda may be slower for the jobs with native on though?

Not by a lot as we disable optimizations when calling ocamlopt, but IIRC there was some slowdown. The question is how much.

**Comment by Alizter** [comment]
So? Do we want this or no?

**Comment by ppedrot** [comment]
Whatever we do, we shouldn't compile parts of the library CI with different flags (and recompile bits of them twice in the process). Either we uniformly set the flambda flag everywhere, and it can be done after this PR, or we remove it everywhere, and it can also be done after this PR.

**Comment by Zimmi48** [comment]
> So? Do we want this or no?

Yes, we do.

**Comment by Alizter** [comment]
Alright, I'm gonna go ahead and merge this.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
