### PR TITLE
Declaremods: do not protect summaries 

### PR DESCRIPTION
**Pull request by SkySkimmer**
Resetting the summary when an exception is raised is useless here, the
higher layers will handle it.

By not resetting the summary errors can be correctly printed since we
have the correct nametab (the added test used to print
`expected type "A1.<inductive:t:0> -> A1.<inductive:t:0>"` etc).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
Is this related to the issue that coqc and coqtop (iirc) do not always print errors in the same environment?

**Comment by SkySkimmer** [comment]
I guess both issues are related to the fact that exceptions don't capture the full environment needed to print them but otherwise no.
Also I think coqtop and coqc print in the same env since https://github.com/coq/coq/pull/16746

**Review by ppedrot — APPROVED** [review]
This looks like a reasonable change indeed.

**Comment by ppedrot** [comment]
Mergin soon, in any case.

**Review by ejgallego — COMMENTED** [review]
Can't be a bad thing. Wouldn't it safer tho for the corresponding errors to actually capture the environment information needed for printing instead?

**Comment by SkySkimmer** [comment]
Even if they did it wouldn't justify uselessly resetting the state in these functions

**Comment by ejgallego** [comment]
> Even if they did it wouldn't justify uselessly resetting the state in these functions

Of course not, on the contrary.

The justification would be other way tho: does not resetting the envs here is enough to guarantee correct printing?

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
