### PR TITLE
Set Printing Parens

### PR DESCRIPTION
**Pull request by aa755**
implementation suggested by @herbelin 

**Kind:** feature

### CODE REVIEW

**Comment by herbelin** [comment]
@aa755: Thanks for the PR. I'm curious about the opinion of the other developers.

To me, it makes sense, and I'm even dreaming of the day where we will have a panel with checkbox in user interfaces and we will be able to check/uncheck the printing of parentheses, or the printing of notations, or the printing of implicit arguments in one click...

About the feature itself, I thought during the night that it might be worth to be refined a little. For instance, when printing `{x:nat|x=0}`, I guess there is no interest in seeing {x:nat|(x=0)}, so, in a second approximation, we may want to see parentheses only at the border of notations.

Also, what would you like for recursive notations? With your patch, we have:
```
Check (1,2,3,4). 
(*  (1,2,3,4).  *)
Require Import List. Import ListNotations.
Check [1;2;3;4].     
(* [1; 2; 3; 4] *)
```
Would you prefer to see `(((1,2),3),4)` and `1::2::3::4`? If yes, something more would have to be done.

Note: as reminded recently to me by @ejgallego, this is related to #6560 which goes towards collecting all printing options we may want in a centralized way.

**Comment by Zimmi48** [comment]
I think this PR is a net improvement for pedagogical purposes, so I would support merging it without delay even if it could be further refined.

Note that printing flags in CoqIDE usually warn "Set this option from the IDE menu instead." I don't know how that works but it would make sense for this issue to follow the existing model, and to extend the "View" menu in CoqIDE.

**Comment by herbelin** [comment]
> I would support merging it without delay even if it could be further refined.

As far as I'm concerned, I would suggest before merging to implement without delay the cancellation of precedences only at the borders (but to keep recursive notations as they are).

As a matter of rule, it is common to underestimate the importance of a printer. The printer is a tool which we use daily. Being able to tweak it to our daily needs has to be seriously taken into account.

For the PR, I would also recommend:
- to call the option `Set Printing Parentheses` (even if it is only about parentheses for notations). It is a longer word, but more consistent with the usage; moreover, this is anyway (eventually) supposed to be provided by a click, a menu, or a combination of keys;
- indeed to add the option now to the View coqide menu (one line in file `idetop.ml`, function `coqide_known_option`)
- to add a couple of tests (e.g. in `test-suite/output/PrintingParenthesis.v` with the expected result in `test-suite/output/PrintingParenthesis.out`) which highlight the key expectations of the feature.

@aa755: I can do the above (or part of it) but I'd be very happy too if you want to do it.

**Review by ejgallego — APPROVED** [review]
Modulo the missing documentation.

**Comment by aa755** [comment]
> About the feature itself, I thought during the night that it might be worth to be refined a little. For instance, when printing `{x:nat|x=0}`, I guess there is no interest in seeing `{x:nat|(x=0)}`, so, in a second approximation, we may want to see parentheses only at the border of notations.
> 
Yes, parentheses are ideally avoided in the case of {x:nat|(x=0)}, but it may be okay to keep it if it simplifies the implementation and documentation.

> Also, what would you like for recursive notations? With your patch, we have:
> 
> ```
> Check (1,2,3,4). 
> (*  (1,2,3,4).  *)
> Require Import List. Import ListNotations.
> Check [1;2;3;4].     
> (* [1; 2; 3; 4] *)
> ```
> 
> Would you prefer to see `(((1,2),3),4)` and `1::2::3::4`? If yes, something more would have to be done.

I would prefer to see `(((1,2),3),4)` and `((1::2)::3)::4`. For arbitrary recursive notations, seeing those parentheses may be helpful.

**Comment by aa755** [comment]
> For the PR, I would also recommend:
> 
> * to call the option `Set Printing Parentheses` (even if it is only about parentheses for notations). It is a longer word, but more consistent with the usage; moreover, this is anyway (eventually) supposed to be provided by a click, a menu, or a combination of keys;
> * indeed to add the option now to the View coqide menu (one line in file `idetop.ml`, function `coqide_known_option`)
> * to add a couple of tests (e.g. in `test-suite/output/PrintingParentheses.v` with the expected result in `test-suite/output/PrintingParentheses.out`) which highlight the key expectations of the feature.
> 
> @aa755: I can do the above (or part of it) but I'd be very happy too if you want to do it.

I did the first one. It would be great if you can do the rest.

**Comment by herbelin** [comment]
> I would prefer to see `(((1,2),3),4)` and `((1::2)::3)::4`. For arbitrary recursive notations, seeing those parentheses may be helpful.

Ok

> I did the first one. It would be great if you can do the rest.

Thanks. Ok

**Comment by tchajed** [comment]
> Would you prefer to see `(((1,2),3),4)` and `1::2::3::4`?

@herbelin yes, I was definitely expecting the first since this is a big source of confusion for me when using recursive notations. For the second I think either `[1;2;3;4]` or `1::(2::(3::(4::nil)))` would be OK.

**Comment by aa755** [comment]
Sorry I incorrectly parenthsized the list.

**Comment by herbelin** [comment]
@aa755 : is it ok for you if I push directly on the PR?

**Comment by aa755** [comment]
Yes it is ok, thanks.

**Comment by herbelin** [comment]
> Yes it is ok, thanks.

OK, done, and rebased. I manage to display `(((1,2),3),4)` and, seeing it in action, this feature is quite cool. A very good idea.

You can probably squash some of the commits. There is also a changelog to do. Are you willing to do it? Do `dev/tools/make-changelog.sh`, choose a category (probably 3 for notations), and fill the template (possibly looking at inspiration from other files in `dev/changelog/`). If you are willing to, documentation is otherwise to put in `doc/sphinx/user-extensions/syntax-extensions.rst`, typically in the same section as `Set Printing Notations`.

**Comment by herbelin** [comment]
@ejgallego: since I contributed, can you be the assignee?

**Comment by ejgallego** [comment]
@aa755 @herbelin are the `needs: ` tags still relevant, or is this ready for merging?

**Comment by aa755** [comment]
I think it is ready for merging. I don't see how to remove those tags.

**Comment by ejgallego** [comment]
> I think it is ready for merging. I don't see how to remove those tags.

Can you try now? [After accepting the invitation]

**Comment by ejgallego** [comment]
Will merge in a couple of day if no further comments.

**Pull request merged**
