### PR TITLE
[lib] Remove custom backtrace-destroying finalizers

### PR DESCRIPTION
**Pull request by ejgallego**
in favor of the one in the OCaml standard library.

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
For such minor issues, I'd rather wait for the required dependency on OCaml 4.08 in Coq instead of introducing a bunch of files that'll need to be removed afterwards. We can live without backtraces for micromega file manipulations in the meantime, which would be trivial anyways because it's just about serialization.

**Comment by ppedrot** [comment]
@ejgallego thoughts on my comment?

**Comment by ejgallego** [comment]
> @ejgallego thoughts on my comment?

It is OK to me; I'd still like to fix the wrong `finally` in `micromega` so I dunno, should I keep the copy embedded or move it to `Util`?

**Comment by ejgallego** [comment]
Added a simpler fix; IMHO we can merge [I found this lack of BT in the real world so it would help]

**Review by ppedrot — APPROVED** [review]

**Comment by ejgallego** [comment]
All the failures were spurious.

**Pull request merged**
