### PR TITLE
Fix profiling plugin

### PR DESCRIPTION
**Pull request by JasonGross**
Allow LtacProf tactics to be called.

This fixes #6378.  Previously the ML module was never declared anywhere.

Thanks to @cmangin for the pointer.

Also, use `msg_info` for LtacProf, so that `Time Show Ltac Profile.` shows the profile in `*response*` buffer in PG without extra `infomsg` tags from mixed messages.

### CODE REVIEW

**Comment by JasonGross** [comment]
Travis success: https://travis-ci.org/JasonGross/coq/builds/315068870

**Comment by ejgallego** [comment]
That looks OK to me, @ppedrot ?

**Comment by maximedenes** [comment]
fiat-crypto times out. @ejgallego @JasonGross is there an easy way to increase the margin?

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by JasonGross** [comment]
I can make a PR that makes fiat-crypto about five minutes faster by removing a couple thousand calls to coqdep.  But I'd like to also see the coqdep PR get merged

**Comment by JasonGross** [comment]
Does me deleting the branch mess with the backporting process?

**Comment by Zimmi48** [comment]
Nope :)

**Comment by Zimmi48** [comment]
The backport script is in `dev/tools` BTW if you want to have a look at it.

**Pull request merged**
