### PR TITLE
Fix quoting in shims

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
Oh, that's an interesting idea; I'm OK with it, tho I was hoping to remove the shims altogether once dune 2.9 is released.

IMHO the right fix for these concrete cases is to have a target a bit small than install that will setup the contents on install.

**Comment by Zimmi48** [comment]
Should we still merge this as a temporary fix?

**Comment by ejgallego** [comment]
> Should we still merge this as a temporary fix?

Not sure this will help a lot @ppedrot 's case, as indeed IIUC he needs a full working env with coqdep coq_makefile etc... so the shims are just too little.

**Comment by ppedrot** [comment]
Yes, the other binaries won't be available, so this is not really helping in practice.

**Comment by Zimmi48** [comment]
Right. So that would just create confusion without actually helping anyone?

**Comment by SkySkimmer** [comment]
Changed to just te quoting fix

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
