### PR TITLE
coqchk: fix check for kelim with functors

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I am surprised that this is allowed by the kernel, but if so, the fix is fine.

**Comment by SkySkimmer** [comment]
The kernel doesn't see it, it's the checker.

**Comment by ppedrot** [comment]
Will wait a bit to let @maximedenes, @herbelin and @mattam82 to optionally comment.

**Review by mattam82 — COMMENTED** [review]
I'm confused, this relaxes the checker check so that M.ind can be eliminated into Type?

**Comment by SkySkimmer** [comment]
The checker sees M.ind after the functor application, so as far as it's concerned it can be eliminated into Type.

**Comment by mattam82** [comment]
Ok. On the other hand the kernel does not see that and prevents such elimination, right?

**Comment by SkySkimmer** [comment]
yes

Gaëtan Gilbert

**Comment by herbelin** [comment]
> Will wait a bit to let @maximedenes, @herbelin and @mattam82 to optionally comment.

OK from my point of view.

This looks like dual to lowering a `Type` to `Prop` if a singleton type, i.e. unboxing a `Prop` to `Type` when eventually known to be a singleton. Ok to make it accepted by the kernel too if some interest to do so. Ok to make the `mind_kelim` a function dependent on the universes occurring in the type (or even dynamically recomputed) if it may help.

**Comment by SkySkimmer** [comment]
@ppedrot can you merge?

**Pull request merged**
