### PR TITLE
Remove Safe_typing.universes_of_private by handling them in upper layers

### PR DESCRIPTION
**Pull request by SkySkimmer**
Alternative to #11524

### CODE REVIEW

**Review by ppedrot — COMMENTED** [review]
Assuming this works, I prefer this PR to mine. But IIRC there were subtle interactions for nested side-effects.

**Comment by ppedrot** [comment]
After a bit of pondering, it might be the case that the cleanups regarding delayed computation of side-effects removed the need to care for this kind of situation. Let's see what the CI says.

**Comment by ppedrot** [comment]
It worked, great!

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Will leave a bit of time for comments before merging.

**Comment by ppedrot** [comment]
Actually, if I want to remove the set of constraints from the `Monomorphic` field, I need it inside the set of kernel-facing side-effects. That is, exactly what the other PR was doing... In which case I think it's better to close this one and reopen the other :wheelchair:

**Comment by SkySkimmer** [comment]
Could you explain more?

**Comment by ppedrot** [comment]
When replaying the private definition, I also need to push the set of constraints introduced by this definition, as performed by the `add_field` primitive. Nonetheless, this set is part of the TCB and needs to coincide with what the environment expects. So, if removed from the constant declaration, it needs to be part of the side-effect structure.

**Comment by SkySkimmer** [comment]
OK
Maybe better to remove accesses to Monomorphic for side effect purposes in 1 PR.

**Pull request closed without merging**
