### PR TITLE
[vernac] taint two out-of-api `to_constr` use in `comDefinition`.

### LINKED ISSUE #7448: New anomaly with Program Definition
#### Version

8.9+alpha (6c8b00e47334f60f200256d45a5542fa80ce4b12)

#### Description of the problem

```
Require Program.Tactics.
Program Definition foo := _.
```

gives:

```
Anomaly "grounding a non evar-free term"
```

In `v8.8` (0c88f3b50d6e213fc7bfb02525c4e349a630275c and 8.8.0), it gives:

```
Cannot infer an internal placeholder of type "Type".
```

Putting the 8.9+beta1 milestone because someone should probably self-assign this.

### PR DESCRIPTION
**Pull request by ejgallego**
This should fix #7448 and #7265.

### CODE REVIEW

**Comment by ejgallego** [comment]
Why is this not asking the codeowner to do the review @maximedenes @Zimmi48

**Comment by maximedenes** [comment]
The codeowners file is now fixed. This PR is pending on a review by @mattam82.

**Comment by ejgallego** [comment]
Note that in this case CODEOWNERS doesn't do the best job of identifying the best reviewer in the sense that here the "right" person to review this kind of change is the maintainer of `EConstr`; we have this problem in other areas of the codebase where a patch modifying how an API is used should be reviewed by the API implementer not the user.

**Comment by maximedenes** [comment]
I agree it is a problem that exists, but I'm not so sure it is the case here. This PR is about a newly introduce invariant not respected by a piece of code. It looks ok to me to have the maintainer of that piece of code review it, not necessarily the maintainer of the code that enforces the invariant.

**Comment by ejgallego** [comment]
Well indeed both should have a look to this, as it is requested. Maybe in fact we should even open a bug about the implementation of `comDefinition` et al.

**Review by ppedrot — COMMENTED** [review]
This is merely side-stepping the problem, which is that Program is misusing evar-bearing terms. The current solution is thus a quick workaround, but a proper fix should be designed at some point.

**Comment by maximedenes** [comment]
@ppedrot Do we have an issue for the program-with-evars pb? If yes, can you give a pointer? If not, can you open it (you probably know better what has to be done)? Thanks!

**Comment by ejgallego** [comment]
Indeed we should open the issue. Given that @mattam82 has hardware problems and this is a trivial fix to a bug impacting a couple of users I'd suggest that either @ppedrot or @maximedenes take care of it.

**Review by ppedrot — APPROVED** [review]
In case this was not clear, I'm fine with merging this PR as-is.

**Comment by ppedrot** [comment]
@mattam82 Are you fine with this PR?

**Pull request merged**
