### PR TITLE
Fix #7124: Warning "Ignoring implicit status" does not provide line number

### LINKED ISSUE #7124: Warning message "Ignoring implicit status" does not provide line number
#### Description of the problem

The warning message "Ignoring implicit status of product binder cs and following binders"
does not say what file name and line number, unlike most warning messages.  That makes it difficult
to track down!   (If you fix this one, perhaps search the source code for all other warning messages with
the same problem.)

```
(* in VST,  floyd/closed_lemmas.v, any version between January 1 and March 29, 2018 *)
Definition expr_closed_wrt_lvars (S: ident -> Prop) (e: expr) : Prop :=
  forall {cs: compspecs} rho ve',
     (forall i, S i \/ Map.get (ve_of rho) i = Map.get ve' i) ->
     eval_expr e rho = eval_expr e (mkEnviron (ge_of rho) ve' (te_of rho)).
```

### PR DESCRIPTION
**Pull request by maximedenes**
There were actually two problems with this warning: it was emitted without using the warning infrastructure (instead, it was calling `Feedback.msg_warning` directly) which makes it impossible to configure. Also, it forgot to pass a location. This PR fixes both problems.

### CODE REVIEW

**Comment by herbelin** [comment]
GTM. A side question though: are there some developer rules which we could start to document about how to name warning and categories of warnings. For instance, I see no warnings already in a category `interpretation`. On the other side, I see a category `implicits` with 2 warnings already in the category. Could e.g. `implicits`  be stabilized as a category name and used here? (Or, conversely, maybe eventually supporting several categories for a warning.)

Meta-side-question: I think I've seen even @jasongross using words such as "implicits" and "inductives" but I also heard comments from other people telling that these words are only adjectives in English. So wondering how much using these adjectives in plural form looks shocking from a native English point of view or not.

**Comment by maximedenes** [comment]
> For instance, I see no warnings already in a category interpretation. On the other side, I see a category implicits with 2 warnings already in the category.

Good point, I'll use `implicits` instead.

**Comment by herbelin** [comment]
> Good point, I'll use implicits instead.

Fine to me.

PS: Some people suggested to me that I was maybe using too often open-ended questions. If you also feel that I'm doing that too much, I can try to me more in a "request changes" mode, even if it would be an effort, as I rarely think that there is one solution worth to be considered better than other ones (and this is the case here).

**Review by herbelin — DISMISSED** [review]
Status: pending on change of the category name.

**Comment by maximedenes** [comment]
Category name changed, PR rebased.

**Comment by herbelin** [comment]
@maximedenes: as said in review dismissal, thanks a lot. If ci is ok, I'll merge tomorrow.

**Pull request merged**
