### PR TITLE
[dev] add missing worker deps to shim

### LINKED ISSUE #16573: `make world ; dune exec` recompiles stuff
I'm on master = fec24c7e6485cc18658929c24c3fa45bc7cdf773 and
```
make world
dune exec -- dev/shim/coqc-prelude test-suite/some/file.v
```
recompiles coqc.
@coq/build-maintainers Is this expected?

### PR DESCRIPTION
**Pull request by Alizter**
Fix #16573

### CODE REVIEW

**Comment by gares** [comment]
I guess we wait until the PR unifying workers is merged

**Comment by ppedrot** [comment]
Workers are now united, time to seize the dependencies.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
In general we should rework the Coq infra so `coqc` / `coq-lsp` can request such tools on-demand, as they could for .vo files too.

**Pull request merged**
