### PR TITLE
Fix ci-all target

### PR DESCRIPTION
**Pull request by SkySkimmer**
I'm not sure if it's actually useful, maybe we should just delete it.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Indeed, I don't personally see a use case as I would never compile all CI targets locally and this is not used in our actual CI.

**Comment by ejgallego** [comment]
I do compile them from time to time if Travis is busy as my 32 core computer does a way better job.

**Comment by SkySkimmer** [comment]
>I do compile them from time to time if Travis is busy as my 32 core computer does a way better job.

But would you use `ci-all` for that?

**Comment by SkySkimmer** [comment]
@ejgallego ping

**Comment by ejgallego** [comment]
> But would you use ci-all for that?

I do, with `make -j` and is messy I admit :D

**Pull request merged**
