### PR TITLE
Reduce rational numbers in Cauchy real addition, to accelerate it

### PR DESCRIPTION
**Pull request by VincentSe**
**Kind:**  feature

Reduce rational numbers to accelerate successive Cauchy real additions. Simplify proofs.

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
I guess the plan is that we integrate this PR first, then I rebase and continue with my work?

I will do the review asap.

**Comment by silene** [comment]
As I explained in my email, `Qred` is not that good an idea, because it only reduces fractions if they are reducible. Using the definition akin to the following ensures that fractions are always reduced to the optimal size:
```coq
Definition CReal_plus (x y : CReal) : CReal
  := exist _ (fun n : positive =>
    let (p, q) := (proj1_sig x (4 * n)%positive + proj1_sig y (4 * n)%positive)%Q in
    (Zdiv (p * 2 * n) q) # (2 * n)
           (CReal_plus_cauchy x y).
```

**Comment by MSoegtropIMC** [comment]
> As I explained in my email, `Qred` is not that good an idea, because it only reduces fractions if they are reducible. Using the definition akin to the following ensures that fractions are always reduced to the optimal size:

I would prefer to have two instances, one which embeds rationals exactly and one which uses dyadic rationals. I would say there is no good reason for using approximate non dyadic rationals. Embedding rationals exactly is a usability feature - e.g. in stochastic or when computing taylor series, people might want to see the exact rationals.

**Comment by VincentSe** [comment]
@MSoegtropIMC Again, you have exact rationals in abstract `ConstructiveReals`. Cauchy reals is simply a computational layer, we do not need exact rational in it.

**Comment by MSoegtropIMC** [comment]
> @MSoegtropIMC Again, you have exact rationals in abstract `ConstructiveReals`. Cauchy reals is simply a computational layer, we do not need exact rational in it.

ok, but we don't need approximate fractional rationals either, except as a temporary speed up until we have dyadic rationals.

But I must say I am not yet 100% convinced about that. In the end we will need to be able to do mixed arithmetic between dyadic and fractional rationals and that code must be somewhere. I can't imagine it is in ConstructiveReals.

**Comment by VincentSe** [comment]
@silene Why do you approximate `x,y` to precision `4*n` ? That's twice too much.

**Comment by VincentSe** [comment]
@MSoegtropIMC 

> ok, but we don't need approximate fractional rationals either, except as a temporary speed up until we have dyadic rationals.
Even with dyadic rationals, @silene 's proposal is interesting. He says that `proj1_sig x (2*n)` might be too precise, using rational numbers with too many digits. He truncates to the precision requested in the sum, to get a rational number with less digits that computes faster.

**Comment by silene** [comment]
The function I wrote is not the one you want to implement and prove. The one you want is
```coq
Definition CReal_simpl (x : CReal) : CReal
  := exist _ (fun n : positive =>
      let (p, q) := proj1_sig x (2 * n)%positive in
      (Zdiv (p * 2 * n) q) # (2 * n))
    (CReal_simpl_cauchy x).
```

And you prove that this function is the identity on real numbers.

Then you define the optimized version of `CReal_plus` as the composition of `CReal_simpl` and the current version of `CReal_plus`. That is how I get `4 * n` in the version I wrote above.

Anyway, I have not quite followed how the definition of `QSeqEquiv` evolved recently, so maybe having `2 * n` in `CReal_simpl` is excessive and `n` is sufficient.

**Comment by VincentSe** [comment]
@silene So to get a truncated rational approximation within `1/n`, `CReal_simpl` first approximates `x` within `2/n`. That's a bit sad, because `x` might be slow to compute. It is unclear that the acceleration thanks to the smaller rationals offsets the loss in `2/n`.

Don't you have a way to truncate the rational number at `1/n` by approximating `x` at `1/n` also ?

**Comment by silene** [comment]
If you first approximate `x` at `1/n` and then approximate the result at `1/n`, then you have obtained an approximation of `x` at `2/n`, not at `1/n`. There is no way around it.

The fact that `x` is slow to compute does not matter. What matters is how much slower approximating `x` at `1/2n` is, with respect to approximating it at `1/n`. The good news is that the overhead is negligible in practice. More precisely, the relative overhead is of the order of `1 / log n` (so it tends to zero as `n` grows). The gain of using more compact rational numbers largely compensates this overhead.

By the way, this is related to the reason why changing the convergence speed from `1/k` to `1/2^k` makes sense. The latter is sufficiently fine-grained, since there is not much difference between computing at accuracy `1/(n+1)` and `1/2n`, due to the logarithm above.

**Comment by VincentSe** [comment]
@silene What if we leave it to the programmer's responsibility not to overfit the Cauchy sequences? For instance the truncation would be done in `inject_Q`, instead of using constant sequences. In the square root the truncation is already done. If all initial Cauchy sequences have optimal sizes, can errors still appear during the computations ?

**Comment by silene** [comment]
> In the square root the truncation is already done.

Which square root are you talking about? If you are talking about the one performing `Z.pos (Pos.sqrt (i*j*n*n)) # (j*n)`, then no truncation is done, since the divisor is `j*n` instead of `n`.

> If all initial Cauchy sequences have optimal sizes, can errors still appear during the computations?

I do not understand. Which errors are you talking about?

**Comment by VincentSe** [comment]
@silene You are right about the square root. So we could truncate it :-) By "errors" I meant rational numbers too big that slow down computations. So if we truncate square root and inject_Q, do computations about them always keep optimal size, or can big rationals still creep in ?

**Comment by MSoegtropIMC** [comment]
To guide the discussion a bit, let me recap the requirements I have on a practically useful number representation:

1.) numbers are easy to use in proofs, e.g. they build exactly a field (not just approximately as floats do)
2.) rational numbers can be embedded exactly, e.g. 1/3 is not 0.3333 but 1/3
3.) irrational numbers can be represented numerically to arbitrary precision in a way which does not compromise requirement 1
4.) numerical computations are reasonably efficient (not more than 10x slower than equivalent precision arithmetic in Maxima (lisp) would be ideal)
5.) the numbers are in the physically relevant area (that is roughly 10^+-100) scale invariant, that is performance does not depend (substantially) on scale (please note that mathematicians might have much higher needs on scale invariance, think of Knuth's arrow notation or the busy beaver function but as physicist I don't care too much ;-)

Up to now nothing like this exists in CAS software (Mathematica, Maxima, Maple, ...). What exists are:

- exact rationals (e.g. 437/83), fulfil requirement 1 und 2
- arbitrary precision floats (z.B. 1.378*10^-15), fulfil requirements 4 and 5
- symbolic irrationals (e.g. sqrt(2)), partly fulfil requirement 1 (as far as symbolic stuff goes - e.g. showing sqrt(2)<1.5 is no fun) and properties 2 and 5

In efficient constructive reals I see the potential to fulfil all 5 requirements but I see a tendency towards dropping 2 - all I say is: please keep this in mind. I know that @VincentSe thinks that this is solved at a higher level but I don't see this - in the end one needs e.g. algorithms to convert fractional rationals to dyadic rationals of requested precision and these need to be somewhere - I guess in a CReals variant. What I am asking for is to think carefully where to put stuff like rounding to requested precision so that this remains optional.

My plan is still to define a computational base structure which has to fulfil certain properties and have various implementations. There might also be speed vs trustworthiness variants like using algebraic datatype numbers vs using machine integer arithmetic and/or floats. In the end for efficiency reasons one might think about working with machine floats to some precision and then seamlessly going to arbitrary precision dyadic rationals. I don't think that hard wiring any computational base structure into CReals is the right approach.

**Comment by VincentSe** [comment]
@MSoegtropIMC I think abstract `ConstructiveReals` fulfills all 5 requirements. Rational numbers are represented exactly by `CR_of_Q`, which in a field injection from rationals to reals. Why do think that's not enough for item 2 ?

**Comment by MSoegtropIMC** [comment]
> Why do you think that's not enough for item 2 ?

I absolutely agree that this would be enough to fulfil requirement 2, but I don't see how this would play together with requirement 3 and 4. Think e.g. of a truncated Taylor series where you want the coefficients be exact rationals and the x being an uninstantiated variable. For representing the term to the user this is the best one can do. Now you instantiate the variable x with a dyadic rational based CReal - say you want to plot the function and compute it at several points. What would happen then? The rationals must be combined with the dyadic rational CReal x. How is this supposed to work?

**Comment by VincentSe** [comment]
@MSoegtropIMC Let `R : ConstructiveReals` be any implementation of constructive reals, possibly `CReal`. The exponential is this Taylor series (truncated at N)

`Definition exp (x : CRcarrier R) := CRsum R (fun n:nat => CR_of_Q R (1 # n!) * x^n) N`

Then you can evaluate `exp (CR_of_Q R (23 # 7)) : CRcarrier R` which is an exact real number. Finally if you want to approximate it on dyadic rationals you will instantiate `R` by `CReal` and `proj1_sig` at any precision you want.

**Comment by MSoegtropIMC** [comment]
> Then you can evaluate `exp (CR_of_Q R (23 # 7)) : CRcarrier R` which is an exact real number. Finally if you want to approximate it on dyadic rationals you will instantiate `R` by `CReal` and `proj1_sig` at any precision you want.

I see what you mean terms are always abstract and only when you want to see a number, they are instantiating it with a CReal.

The issue might be that a CAS is not like a programming language, one does do computation on terms, combine previous results to new terms and the like. I must admit that I don't see yet how this will work out - I think one has to try it. Fact is that mankind is looking for a solution to this kind of problems since 50 years and up to now there is none. I am convinced that we can solve this based on constructive reals somehow but I don't see all the details as yet and also need not see them right now. What I want now is to keep it flexible so that one can easily try different variants.

**Review by MSoegtropIMC — APPROVED** [review]
This is definitely a substantial in clarity of the definitions and the proofs. The separation of computational and proof part could be further improved in a few places, but I am fine with merging it as is and doing a final cleanup and review run after I did my changes. Please let me know your preference.

**Comment by VincentSe** [comment]
@MSoegtropIMC You can go back and forth between `ConstructiveReals` and `CReal`, thanks to the theorem that all implementations of `ConstructiveReals` are equivalent.

For example, let `x : forall R:ConstructiveReals, CRcarrier R` be an exact real number parametrized by the implementation `R` of constructive reals. You might want to bound it by a rational number `q : Q`. Then there is this theorem

`(forall R:ConstructiveReals, x R <= CR_of_Q R q) <-> (x CReal <= CR_of_Q CReal q).`

So you would prove the right-hand side by computation in `CReal` and then go back to abstract exact terms.

**Comment by VincentSe** [comment]
@MSoegtropIMC Please merge this now. I agree there are many other corrections to do, I even have further simplifications almost ready on my machine. We'll iterate on several pull requests. I think there shouldn't be too many merge conflicts with your other pull request.

**Comment by silene** [comment]
> You are right about the square root. So we could truncate it :-)

Note that it is just a matter of composing the current square root with `CReal_simpl` (or whatever it is called).

> By "errors" I meant rational numbers too big that slow down computations. So if we truncate square root and inject_Q, do computations about them always keep optimal size, or can big rationals still creep in?

They instantly creep in. For example, consider `sqrt 2 + sqrt 3`. Assume that `sqrt` is already truncated, that is, divisors are of the order of `2n` at index `n`. Then you perform an addition on rational numbers, which computes the product of the divisors taken at index `2n`. So, at index `n`, the divisor of the sum of square roots is of the order of `16n^2`. Yet the truncated one would be of the order of `2n`. Thus, after only one addition, the rational numbers are already completely out of control. And the more operations, the worse it gets.

To avoid that, a solution is to compose all the operations with `CReal_simpl`. Note that, in some cases, this is overkill. In particular, for `inject_Q`, it is counterproductive for large indices `n`. Indeed, truncation gives divisors of the order of `2n`, which become arbitrarily larger than the original divisor. The trade-off I was suggesting was to use `CReal_simpl` only on addition. (And as was mentioned, the trade-off depends on the underlying arithmetic. For dyadic numbers, truncation would rather be done on multiplication.)

**Pull request merged**
