### PR TITLE
Added take to VectorDef

### PR DESCRIPTION
**Pull request by stelleg**
Seems like a useful function to have.

### CODE REVIEW

**Comment by herbelin** [comment]
No strong opinion on this particular choice of definition over other ones, so it is ok at least to me. While you are at it, maybe do you have also properties around about `take`?

**Comment by stelleg** [comment]
OK, I've added some properties for `take`. I also slightly changed the definition to make proving things about it a little cleaner.

It's worth noting that the choice of `take` differs from list's analogous `firstn`. I think the semantics are different enough to warrant different names, but I'm happy to change it to `firstn` if people are opinionated about that. 

I also wrote an almost identical `drop` definition. I considered including it here, but proving things about it proved tricky due to some nasty rewrite rules.

**Comment by herbelin** [comment]
A few more comments, since I'm asked for.

- The use of the suffix `idem` is a priori raising questions. In the stdlib, `List` uses `idem`, `NArith`/`ZArith` are using `idemp`, `Arith`/`Sets`/`Structures` are using `idempotent`. However, since `Vector` is close to `List`, and as far as no one has better to propose (e.g. @letouzey?), `idem` is fine to me.

- Another minor remark is that the name `l` for a proof of `p <= n` is maybe misleading, since `l` is often used for lists. Maybe `H`, or `le`, or `Hle` would be less ambiguous? But that's not critical.

So, as far I'm concerned, I think this PR is good, but an opinion of at least @letouzey, (maybe also of @mattam82 if he has time) would be welcome.

**Comment by stelleg** [comment]
Thanks for the feedback. I was unaware of the `idem` controversy. I agree that `l` was poorly chosen. I've changed it to `le`.

**Comment by maximedenes** [comment]
@letouzey do you give this PR the green light?

**Comment by letouzey** [comment]
No objections. Vector is already quite different from List, so different naming conventions isn't a big deal here...

**Comment by maximedenes** [comment]
@stelleg the commits of this PR seems to need a bit of squashing, could you do it? Thanks!

**Comment by stelleg** [comment]
@maximedenes this squashing OK?

**Comment by maximedenes** [comment]
@stelleg I'll amend the commit message, because it still mentions changes that are not happening in the commit, but thanks!

**Comment by maximedenes** [comment]
Merged, thanks a lot for contributing!

**Comment by stelleg** [comment]
Thanks for merging! Hopefully I'll eventually get around to adding `drop` as well, such that `take p le v ++ drop p le v = v`.

**Pull request closed without merging**
