### PR TITLE
Test for #16803: use Defined to work with async proofs

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Maybe we should have an attribute to evaluate Qed proofs eagerly in the STM...

**Comment by SkySkimmer** [comment]
What's the point of running full ci here?

**Comment by ppedrot** [comment]
Useless, I did that out of reflex but it can't hurt.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
