### PR TITLE
Add a test for #9750.

### LINKED ISSUE #9750: tactic remember makes goal ill-typed
#### Description of the problem
In the following example, the goal is "H a p" with "p : f a".
The tactic "remember (f a) as b" changes the type of "p" to "b", which makes "H a p" ill-typed.
~~~coq
Parameter A : Type.

Parameter f : A -> A.
Parameter P : A -> Prop.
Parameter H : forall a, P (f a) -> Prop.

Lemma Foo : forall a (p : P (f a)), H a p.
  intros a p.
  remember (f a) as b.
  match goal with |- ?g => let _ := type of g in idtac end. (* fails *)
  Check (H a p). (* fails (goal is H a p) *)
~~~
#### Coq Version
8.9.0

### PR DESCRIPTION
**Pull request by ppedrot**
Fixes #9750.

### CODE REVIEW

**Comment by Alizter** [comment]
merging soon

**Comment by Alizter** [comment]
not merging soon, didn't see that the CI didn't run before.

**Comment by ppedrot** [comment]
[It did run](https://gitlab.com/coq/coq/-/pipelines/480440440), it's just that coqbot is having a stroke.

**Comment by Alizter** [comment]
OK merging then. I hope coqbot feels better.

**Comment by Alizter** [comment]
@coqbot merge now

**Review by Alizter — APPROVED** [review]

**Pull request merged**
