### PR TITLE
Diff option in CoqIDE

### LINKED ISSUE #8146: CoqIDE displays diffs even if nobody told it to do so
The CHANGES file says:
```
- coqtop and coqide can now highlight the differences between proof steps
  in color. This can be enabled from the command line or the
  "Set Diffs on|off|removed" command. Please see the documentation for
  details.  Showing diffs in Proof General requires small changes to PG
  (under discussion).
```
but here I see the diffs and I did not pass any options, nor write `Set...` in my document.

### PR DESCRIPTION
**Pull request by ppedrot**
This is a followup of #6801. We add a way to switch the diff option inside CoqIDE be means of a menu, instead of setting it by default at the start.

EDIT: Fixes #8146.

### CODE REVIEW

**Comment by jfehrle** [comment]
Thanks for adding the GUI controls for the diff setting.  Still so much for me to learn about the CoqIDE code.  Also, the IDE development process on Windows is painfully awkward.

**Review by gares — CHANGES_REQUESTED** [review]

**Comment by ppedrot** [comment]
Actually I did test it, but I didn't quite understand what the removed flag was supposed to do. No wonder why it printed the same as the other diff!

**Comment by gares** [comment]
It print ~~stuff~~ for things that went away.

**Review by gares — APPROVED** [review]

**Comment by Zimmi48** [comment]
>If you enter the command Set Diffs "on". in the command line, it is applied only for the next proof step. I think it should persist.

This is pretty bad, but for consistency with other view options, it would make sense to completely ignore `Set Diffs "on"` in CoqIDE and print a warning.

**Comment by jfehrle** [comment]
The other view options have the same problem but show no warning in CoqIDE.  For example, `Unset Printing All.`  If CoqIDE is going to go to the trouble of detecting and ignoring some Set and Unset commands, it's almost as easy to automatically set the option in the menus--and simpler for users.

**Comment by Zimmi48** [comment]
`Unset Printing All.` does show a warning: `Set this option from the IDE menu instead`.
But I am not defending this UX here, I'm rather advocating for consistency. I don't know why this design choice was made. If you think it should be reverted, better open a specific issue to discuss it.

**Comment by jfehrle** [comment]
You're right.  I missed the orange-on-yellow message

**Pull request merged**
