### PR TITLE
Improve support for -w options

### LINKED ISSUE #5736: When several -w options are given, only the last one has an effect
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5736
From: @herbelin
Reported version: 8.7+beta1
CC:   coq-bugs-redist@lists.gforge.inria.fr

### PR DESCRIPTION
**Pull request by silene**
Fix #5736

### CODE REVIEW

**Comment by herbelin** [comment]
I would call this a hack as, morally, the work is done twice, but I don't know if it is worth to spend more time on it, so this is just a remark, not a disapproval :smile:

**Comment by herbelin** [comment]
Actually, wouldn't repeating the job also repeat warnings on unknown warnings, which would not be good.

Isn't there an algebraic way to store warnings better than a string, so that e.g. normalization of flags is by construction. Maybe a three level construction with a `none`/`all` option, then a partial list of categories with a bool (or a total with an optional bool), then a partial list of flags with a bool (or a total one with an optional bool), with precedence of the first list over the second and of the second over the third?

Of course, if depends also on what is the semantics of `+all`, `-all`, `all`, `+none`, `-none`, `none`, etc. In particular, once I have set `all` in some form, can I cancel it so as to restore a more flag-per-flag or category-per-category previous state or is it a definitive choice?

**Comment by silene** [comment]
> Actually, wouldn't repeating the job also repeat warnings on unknown warnings, which would not be good.

I admit I haven't tested this scenario, but if I remember correctly, warnings are disabled anyway because there is no way to predict which plugins will be loaded during a session. (This is the weakest point of the current system; most other tools get away with it by enforcing that warnings defined by a plugin are prefixed by the plugin name, thus solving the issue of predictability.)

> Exposing a string in the API still looks a bit like the time of low-level languages to me though.

It isn't as bad as it looks. `CWarnings` proposes two interfaces: the first one is string-based, which makes sense since the user mostly communicates through text with Coq; the second is really high level, and is meant to be used by code.

What is missing is some way to query the existing flags and categories. But that is orthogonal to the existence of the two interfaces above.

**Comment by herbelin** [comment]
> I admit I haven't tested this scenario, but if I remember correctly, warnings are disabled anyway because there is no way to predict which plugins will be loaded during a session. (This is the weakest point of the current system; most other tools get away with it by enforcing that warnings defined by a plugin are prefixed by the plugin name, thus solving the issue of predictability.)

Would it be to have this plugin prefixation policy too?

> It isn't as bad as it looks. CWarnings proposes two interfaces: the first one is string-based, which makes sense since the user mostly communicates through text with Coq; the second is really high level, and is meant to be used by code.

One could make this even clearer by splitting parsing and interpretation, like it is done for the other features of Coq. A parsing phase from `string` to say a list of `((All | Category of string | Warning of string) * status) list` (almost the current `flags_of_string`) and an interpretation phase (almost the current `parse_warnings`), with the use of `string` limited to parsing the command line (in `coqtop.ml`) and, since there is a hack to store the state of warnings as a `string` of diffs, also at the time of synchronizing it with the interaction infrastructure (in `vernacentries.ml`).

BTW: About the warning about non-existent warnings: why not to let it activated when using `Set Warnings`, since the plugins having to be loaded are supposed to having be loaded at that time?

> What is missing is some way to query the existing flags and categories. But that is orthogonal to the existence of the two interfaces above.

Do you mean something along the lines of #439?

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
