### PR TITLE
Ltac2 `intropattern` scope supports views (`%`)

### LINKED ISSUE #12292: Ltac2 eintros is dead code, because views aren't supported yet
@kyoDralliam writes in #12235:
> It would be great to add a test case [for `eintros`], however I don't see how to that without a view (as you wrote in gitter), and looking at the ltac2 implementation, those are not supported yet as intropatterns...

I figured this might warrant an issue.
EDIT: concretely, whoever implements views should make sure to add a test for where `eintros Hfoo%lemma` succeeds and creates evars and `intros Hfoo%lemma` fails (see explanation below).

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #12292

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]
I am vaguely concerned that `unit -> constr` might not be the right argument type for IntroApplyOn but this is not directly related to this PR.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
>I am vaguely concerned that unit -> constr might not be the right argument type for IntroApplyOn

Why?

**Comment by ppedrot** [comment]
There is always the choice to pick preterm vs. unit -> constr and it's not clear to me what's the most general / better fitted.

**Pull request merged**
