### PR TITLE
More robust treatment of maximal implicit arguments in notations

### PR DESCRIPTION
**Pull request by herbelin**
The PR does the following:
- fixes a bug with notations denoting applied constant and applied to multiple blocks of implicit arguments (in `Impargs.drop_first_implicit`) (first commit)
- fixes a small printing bug (spurious extra parentheses) when an applied notation absorbs all its arguments as maximal implicit arguments (second commit, now merged via #18447)
- decide to hide as more as possible implicit arguments behind notations when there are several possible blocks of implicit arguments (e.g. if we do a notation for `eq_refl` which accepts 1 or 2 arguments, it will hide 2 arguments) (third commit, now second)
- add support for insertion of maximal implicit arguments to number/string notations referring to a functional constant (useful e.g. if a field of a record is written `0` or `1`) (fourth commit, now third)

This will be useful in #18446 for fixing #3516 and for generalizing the support for maximal implicit arguments and multiple blocks of implicit arguments in notations. 

- [X] change log added
- [X] test-suite updated

##### Backwards-compatible overlays

* jwiegley/category-theory#137 (merged)
* mit-plv/fiat-crypto#1807 (merged)

### CODE REVIEW

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
Will merge as soon as the overlay is merged.

**Comment by JasonGross** [comment]
@proux01 please wait a bit.

@herbelin is there an overlay for Fiat Crypto Legacy?

**Comment by JasonGross** [comment]
Thank you!  And maybe we should move f-c-l out of allowed-failure?

**Comment by herbelin** [comment]
Backwards-compatible overlay for fiat-crypto-legacy at mit-plv/fiat-crypto#1807 (I could not test fcl in full due to a segfault I have in `src/Algebra/Field.v`, maybe a too short stack?).

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
