### PR TITLE
Prevent redefinition of Ltac2 types and constructors inside a module

### LINKED ISSUE #10097: Prevent (or deal with) type redefinitions
If I understood correctly, open variants are defined as follows:

```
Ltac2 Type openT := [ .. ].
Ltac2 Type openT ::= [ MyT1(string) ].
Ltac2 Type openT ::= [ MyT2 ].
Ltac2 Eval [ MyT1 "hi"; MyT2 ].
```

(even though the [documentation](https://github.com/ppedrot/ltac2/blob/master/doc/ltac2.md) says that single `:=` can be used to extend open variants).

If one tries to do it differently, surprising things happen: :wink:

1:

```
Ltac2 Type openT := [ MyT1 ].
Ltac2 Type openT := [ MyT2 ].
Ltac2 Eval [ MyT1; MyT2 ].
```

prints

```
- : openT list = [MyT2; MyT2]
```

2: 

```
Ltac2 Type openT := [ MyT1(string) ].
Ltac2 Type openT := [ MyT2 ].
Ltac2 Eval [ MyT1 "hi"; MyT2 ].
```

prints
```
Error: Anomaly "File "src/tac2print.ml", line 118, characters 10-16: Assertion failed."
```

3:

```
Ltac2 Type openT := [ .. ].
Ltac2 Type openT := [ MyT1(string) ].
Ltac2 Type openT := [ MyT2 ].
Ltac2 Eval [ MyT1 "hi"; MyT2 ].
```

prints

```
Error: Anomaly "File "src/tac2print.ml", line 118, characters 10-16: Assertion failed."
```

### PR DESCRIPTION
**Pull request by kyoDralliam**
**Kind:** bug fix .

Fixes / closes #10097 #11046 

- [x] Added / updated test-suite

### CODE REVIEW

**Comment by Zimmi48** [comment]
@kyoDralliam GitHub does not know the e-mail address with which you committed.

**Comment by gares** [comment]
I understand from the tests that types are global, but constructors are not. Which is the rationale?

**Comment by kyoDralliam** [comment]
@gares Both Ltac2 types and constructors have to be unique inside a module. Which test make you think the opposite ?

**Comment by gares** [comment]
I think I was mislead by `t'` in
```
(* constructors with the same name can be defined in distinct modules *)
Module Other.
  Ltac2 Type t ::= [A(bool)].
End Other.
Module YetAnother.
  Ltac2 Type t' := [A].
End YetAnother.
```
Could you write `t` there?

**Comment by kyoDralliam** [comment]
I changed `t'` to `t` in the test-suite if it seems more clear.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
