### PR TITLE
enforcing Ltac2 constructor name are uppercased

### LINKED ISSUE #10196: Ltac2 Type foo := [ bar ] should fail.
#### Description of the problem

`bar` does not start with an uppercase letter so shouldn't be supported.
Indeed, when trying to evaluate `bar`, later on it says that it is unbound, whereas if it was capitalized, it would say it has type `foo` when evaluated.

#### Coq Version

8.11+beta1

### PR DESCRIPTION
**Pull request by kyoDralliam**
**Kind:** bug fix

Fixes / closes #10196

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Hmm, forgot about it but it probably needs a test. Can you add one, @kyoDralliam ?

**Comment by kyoDralliam** [comment]
Indeed, it was a good thing to add a test, I hadn't fixed the case of open types.

Just added a test in `test-suite/bugs/closed/`. Is that the right place to put it ?

**Comment by kyoDralliam** [comment]
Btw, looking at the code for open types, there are no check whether 
1) two constructors have the same name;
2) if a constructor has a recursive occurence of the open type itself.
That is the following code is currently accepted
```coq
Ltac2 Type foo := [.. ].
(* A declared twice, the first copy is shadowed *)
Ltac2 Type foo ::= [A | B | A(foo)].
Ltac2 Eval A B.



Ltac2 Type mylist := [..].
Ltac2 Type mylist ::= [MyNil | MyCons(bool,mylist)].

Ltac2 Eval (MyCons true (MyCons false MyNil)).
```

Are these behaviour expected ? Should I open a bug ?

**Comment by ppedrot** [comment]
First point is a bug, second one looks legit. Why wouldn't you want to allow recursive constructors?

**Pull request merged**
