### PR TITLE
Take unfolding state out of Names.Projection.t

### PR DESCRIPTION
**Pull request by SkySkimmer**
I think it makes more sense this way. 

I added a bool to Constr.Proj, then to various FooProj when I ended up needing one.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Bench is 347.

**Comment by SkySkimmer** [comment]
```

┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                     │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-formal-topology │   33.87   34.40 -1.54 % │   93885059026   94382123736 -0.53 % │   123993431854   124172085080 -0.14 % │  481864  482080 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-corn │ 1467.78 1482.78 -1.01 % │ 4083581783674 4114798253583 -0.76 % │  6382235556821  6383535905993 -0.02 % │  846228  846896 -0.08 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   75.32   75.90 -0.76 % │  207944862104  209280595570 -0.64 % │   282065615219   282263919649 -0.07 % │  525940  526268 -0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   58.97   59.38 -0.69 % │  162267377223  163238127972 -0.59 % │   209918801362   210003635127 -0.04 % │  663052  662912 +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  168.53  169.69 -0.68 % │  466876778366  468070058342 -0.25 % │   654854131073   655183044515 -0.05 % │  589492  588984 +0.09 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3015.16 3035.45 -0.67 % │ 8383389071611 8446786712946 -0.75 % │ 13952264918628 13954227088483 -0.01 % │ 1208344 1233168 -2.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 2893.04 2905.84 -0.44 % │ 8063282707869 8104943071292 -0.51 % │ 11768528624033 11770399969939 -0.02 % │ 2208000 2208276 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   59.83   60.01 -0.30 % │  165673090862  166296541349 -0.37 % │   230844107180   230976144395 -0.06 % │  526788  529880 -0.58 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  190.69  191.21 -0.27 % │  527029807761  529030752367 -0.38 % │   762172016507   762260346795 -0.01 % │  709460  709532 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  101.73  102.00 -0.26 % │  288219813611  288874975008 -0.23 % │   374031399903   374064614271 -0.01 % │  498880  498956 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  439.17  440.25 -0.25 % │ 1219267741649 1221985077083 -0.22 % │  2022378017620  2022927557633 -0.03 % │  715652  715660 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   74.83   75.01 -0.24 % │  205818104890  206837672889 -0.49 % │   257329785078   257683845625 -0.14 % │  657456  657860 -0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  262.60  263.08 -0.18 % │  728127965154  730401118395 -0.31 % │  1073886452211  1074176644903 -0.03 % │  989680  989728 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  565.20  565.55 -0.06 % │ 1574706961706 1579995725866 -0.33 % │  1976957428424  1976943550349 +0.00 % │ 1439000 1439092 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1361.98 1361.02 +0.07 % │ 3781630872532 3780372986501 +0.03 % │  6591694612040  6592088426692 -0.01 % │ 1081408 1081356 +0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  803.88  802.92 +0.12 % │ 2242997607519 2238405092498 +0.21 % │  3411502555977  3411284843945 +0.01 % │ 1338064 1338464 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-hott │  313.89  313.17 +0.23 % │  852837604771  850617934652 +0.26 % │  1371891521945  1373044369864 -0.08 % │  497192  497120 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  653.48  650.91 +0.39 % │ 1820099666125 1819148931464 +0.05 % │  2945938828346  2945762910122 +0.01 % │ 2831232 2831276 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  166.38  165.69 +0.42 % │  460592020557  459780435786 +0.18 % │   698872538271   699129647804 -0.04 % │  719580  719584 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   40.65   40.23 +1.04 % │  111551762704  111263415976 +0.26 % │   137214801458   137227306618 -0.01 % │  477716  477724 -0.00 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Looks within noise boundaries.

**Comment by SkySkimmer** [comment]
Is this the direction we want to go in? Otherwise I won't bother rebasing / making overlays.

**Comment by SkySkimmer** [comment]
I don't think this is getting into 8.8.

**Comment by mattam82** [comment]
Yeah, I'm not sure we want to have this intermediate state. At the WG we seemed to agree on a more drastic removal of the compatibility layer which would just remove this unfolding boolean.

**Comment by SkySkimmer** [comment]
OK then.

**Pull request closed without merging**
