### PR TITLE
 [search] Thread evar_map to fix evar_map FIXMEs.

### PR DESCRIPTION
**Pull request by ejgallego**
Not really essential, but due to API uniformization it is convenient
to get them done.

Depends on #6233 .

### CODE REVIEW

**Comment by ppedrot** [comment]
I don't think it's a good idea to make search functions dependent on the evar map. In practice, they only observe kernel terms and thus don't belong to the same realm.

**Comment by ejgallego** [comment]
> I don't think it's a good idea to make search functions dependent on the evar map. In practice, they only observe kernel terms and thus don't belong to the same realm.

That's true today, maybe not true tomorrow if someone improves search to search, for example, the proof context.

Note that indeed search functions don't depend on the evar_map however the printing functions do. The FIXMEs were added by you, but dunno to what side of the expression you were referring.

What should we do about the printing functions anyways? A sigma has to be created somewhere, so this doesn't hurt too much, although I agree with your comment.

**Comment by ejgallego** [comment]
I do agree thou that maybe it would be good to assume that all `Constr.t` are ground term, and thus have printing [and some other stuff] not taking `evar_maps`.

However, I feel like we are a bit far from enforcing that view in the implemention, WDYT?

**Comment by ppedrot** [comment]
> However, I feel like we are a bit far from enforcing that view in the implemention, WDYT?

Mostly a desirable goal that has been made possible since the introduction of EConstr. But yeah, we should do that progressively.

**Comment by ejgallego** [comment]
WG: No discussion, we'd like to first resolve #6454 and then reconsider this one again.

**Pull request closed without merging**
