### PR TITLE
Inline the definition of CClosure.mk_clos_deep.

### PR DESCRIPTION
**Pull request by ppedrot**
An important part of this function was dead code, due to the fact it was only used for whd evaluation of specific shapes of constr.

### CODE REVIEW

**Comment by maximedenes** [comment]
Can we get a bench, just in case?

**Comment by ppedrot** [comment]
Bench running here: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/503/.

**Comment by ppedrot** [comment]
The bench had to be aborted due to fiat-crypto not compiling at that point, but it only showed a slight speedup, which was not unexpected. AFAICT this PR is good to go.

**Comment by herbelin** [comment]
Expected assignee is @maximedenes.

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
@ppedrot sorry, this needs a rebase. I can merge as soon as it is done. Thanks!

**Comment by ppedrot** [comment]
@maximedenes ping. The bedrock failure is spurious.

**Pull request merged**
