### PR TITLE
Sphinx doc chapter 21

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Review by silene — APPROVED** [review]

**Comment by maximedenes** [comment]
@silene did you use the merge script?!

**Comment by silene** [comment]
No, it was not obvious to me that it is compatible with github's interface for resolving merge conflicts. Is it?

**Comment by maximedenes** [comment]
The script has to be called manually. When you use the GitHub interface, it does something different.

In particular, here, it created a merge commit of `master` into this branch before merging the branch back. Rebasing is cleaner IMHO. The other problem is that CI wasn't run on the merge commit.

**Comment by maximedenes** [comment]
I should have made each PR depend on the previous ones, to avoid conflicts.

**Comment by silene** [comment]
> The other problem is that CI wasn't run on the merge commit.

That was on purpose (I would have done so with the script too.). The CI is already overloaded, no need to wait for it to complete in case of a trivial merge conflict in the documentation.

> Rebasing is cleaner IMHO.

Okay. Then I will wait for you to rebase all the other pull requests.

**Comment by maximedenes** [comment]
> Okay. Then I will wait for you to rebase all the other pull requests.

Ok. I will do a chain of them so that merging one doesn't create conflicts in the others.

**Comment by maximedenes** [comment]
Another big problem is that we can't backport these PRs automatically.

**Comment by Zimmi48** [comment]
In any case, this is one of the most cleanly ported chapters. Thanks @letouzey!

**Pull request merged**
