### PR TITLE
Fix order of load_printer calls in dev/core.dbg

### PR DESCRIPTION
**Pull request by SkySkimmer**
1c55826018c5f07ee25b5771e59fe0389293cb62 put highparsing before
toplevel.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
1c55826 changed the order in Makefile.common `CORECMA` (copying this is why I put highparsing before stm). Maybe core.dbg could be generated from `CORECMA`?

**Comment by ejgallego** [comment]
I think:
- we should merge #939 before this, then sort out your concerns.
- we should add some testing for this debug file so future PRs avoid the problem.

**Comment by SkySkimmer** [comment]
Is #939 backportable?

**Comment by ejgallego** [comment]
@SkySkimmer no, it should not be backported.

**Comment by maximedenes** [comment]
I'm a bit lost. Why not merge this now, @ejgallego ?

**Comment by ejgallego** [comment]
It may be broken again by #939 , so IMHO I'd merge #939 and then sort out any remaining issue with debugging in one shot. Of course, my plan assumes that #939 is ready which AFAICS is.

**Comment by maximedenes** [comment]
Unfortunately, #939 depends on #938 which is awaiting review by Pierre.

**Comment by ejgallego** [comment]
I think that #938 has nothing particularly special as to require an specific review, in fact, the nature of the change means that the patch should be reviewed more by the RM themselves I think.

**Comment by ejgallego** [comment]
I think that #938 has nothing particularly special as to require a specific review, in fact, the nature of the change means that the patch should be reviewed more by the RM themselves I think.

**Comment by maximedenes** [comment]
> approval should depend on our specific compat policy

Yes, but precisely, I don't think we have established any such policy. That's why I was asking Pierre if he's ok with it for 8.8.

**Comment by ejgallego** [comment]
> but precisely, I don't think we have established any such policy

Well this case seems to even be a subcase of the current policy "deprecate in X, remove in X.+1".

**Comment by maximedenes** [comment]
Right, somehow with the lack of sleep, I forgot that we had discussed this at a WG, after I raised the issue of the compat options lifetime. Is it what you were referring to?

**Comment by ejgallego** [comment]
Anyways, I think the patch in #938 is clearly right, given our current architecture, such compatibility workarounds should have been introduced as a compat plugin that is still loaded in 8.7, with 8.8 just dropping the loading of the plugin.

Let's wait to hear from Pierre thou.

**Comment by silene** [comment]
More precisely, the compatibility policy we agreed on was to ensure the following, as much as reasonably possible:
- it is possible for the user to write libraries that are compatible with three consecutive versions (e.g. it should be possible to modify a user library so that it works with both 8.5 and 8.7),
- nothing is removed without first deprecating it.

Both requirements are satisfied by #938, as far as I can tell.

**Comment by Zimmi48** [comment]
> More precisely, the compatibility policy we agreed on was to ensure the following, as much as reasonably possible:
> - it is possible for the user to write libraries that are compatible with three consecutive versions (e.g. it should be possible to modify a user library so that it works with both 8.5 and 8.7),
> - nothing is removed without first deprecating it.

Is that so? That's interesting information, and that would be worth to have it written down somewhere.

**Comment by maximedenes** [comment]
That information can probably be found in a youtube video :)

**Comment by ejgallego** [comment]
Yup, maybe we should use the wiki to take notes from the meetings.

**Comment by Zimmi48** [comment]
I was saying this more as a preamble to `COMPATIBILITY`. Anyways, this is part of the general subject of documenting our processes. I will come back to this often in the future and propose a handful of PRs on the subject.

**Comment by SkySkimmer** [comment]
Not useful with #939 merged.

**Comment by ejgallego** [comment]
@SkySkimmer is there nothing more to fix after #939 ?

**Comment by SkySkimmer** [comment]
Nothing that I know of.

**Pull request closed without merging**
