### PR TITLE
Use a compact representation for real literals

### PR DESCRIPTION
**Pull request by silene**
This patch set has three main consequences. The first one is the intended one; the two others are side-effects.

- Parsing and printing of real literals no longer use the binary representation; they now use `IZR`. In other words, `5%R` is no longer syntactically equal to `1 + 2 * 2`; it is now `IZR 5`.

- `IZR` no longer reduces to a unary representation but to a binary representation, that is, `IZR 5` is no longer `2 + 1 + 1 + 1` but `1 + 2 * 2`. (This also means that `5%R` is still convertible to `1 + 2 * 2`, due to the first item.)

- Morphism rings no longer unfold their ring morphisms. This is mostly a hack so that `ring_simplify` and `field_simplify` are still usable on `R`.

Note that several of these commits (8d92932, e0a09d3, 3758cbf, 7f82a39, e3c978c) are worth applying even if this feature is deemed too intrusive.

### CODE REVIEW

**Comment by herbelin** [comment]
Don't feel expert enough to comment in the details but I like it.

**Comment by silene** [comment]
I should make it clear that the third item (no more unfolding for morphisms) is kind of a breaking change. I have no idea though how often people have been using `ring_simplify` in conjunction with a morphism ring out there, and even so, they can easily work around the change in a backward compatible way by using the postprocess option. Still, this is not satisfactory.

**Comment by JasonGross** [comment]
I believe we do some things with `ring_simplify` in https://github.com/mit-plv/fiat-crypto ; does this change break fiat-crypto?

**Comment by silene** [comment]
> I believe we do some things with ring_simplify in https://github.com/mit-plv/fiat-crypto ; does this change break fiat-crypto?

Possibly. For instance, in some cases where `ring_simplify` would have answered something like `@exists (F.F 17) (fun z : Z => z = z mod 17) 8 (Z_mod_mod 42 17)`, it will now answer `@F.of_Z 17 42`. I would say the new behavior is actually an improvement in your case too, but your mileage may vary.

**Comment by ejgallego** [comment]
@silene I've pushed a Travis build with your PR, maybe it is useful to see the impact? https://travis-ci.org/ejgallego/coq/builds/198858560

**Comment by ejgallego** [comment]
Well, after having a look to https://travis-ci.org/ejgallego/coq/builds/198948362 , it seems this PR breaks Coquelicot and Flocq (and Compcert by transitivity) , I guess the author know how to handle that :)

Do you know of any other development that runs in 8.6/8.7 and could be interesting to test?

**Comment by silene** [comment]
> it seems this PR breaks Coquelicot and Flocq

Regarding Flocq, the breakage gives a better view of the impact of this pull request, due to the number of different contributors. In particular, the following issues never occurred when converting the standard library:

- In various places, people have avoided typing an extra character by using `R0` instead of `0%R` (same for `R1` and `1%R`). They are no longer syntactically equal, so `rewrite` throws a fit whenever a rewriting lemma contains them.

- People tend to write `rewrite Rmult_plus_distr_r, Rmult_1_l` when they want to replace `2 * x` with `x + x`. Again `rewrite` complains since `2` and `1 + 1` are no longer syntactically equal. Same issue when replacing `3 * x` with `x + 2 * x`.

**Comment by ejgallego** [comment]
Interesting, thanks @silene . By the way, I see you seem to have pushed related changes to Flocq's master, this however breaks the automated build for both Coq 8.6 and trunk. Did you intend that?

If what you want is to have the ci scripts to point to a particular flocq branch for this PR, let me know and I'll add a Flocq overlay.

**Comment by silene** [comment]
> this however breaks the automated build for both Coq 8.6 and trunk

This was certainly not intended, especially since I successfully performed a full build of Flocq with Coq 8.6 before pushing (including Flocq's regression checks). Could you point me to these automated builds, so that I try to understand what went wrong?

**Comment by silene** [comment]
> I successfully performed a full build of Flocq with Coq 8.6 before pushing

Forget about that. I did indeed perform a full build, but the result was not successful. I am not quite sure how the failure went unnoticed. I will fix it.

**Comment by silene** [comment]
Interestingly enough, most of the compilation failures came from misfeatures that this pull request intends to fix. For instance, there was a case of `replace 1 with (/2 * 2)` turning `2` into `(/2 * 2 + /2 * 2)`, which was certainly not the intent of the user.

**Comment by maximedenes** [comment]
Does this PR still require fixes? Or can it be selected for the next round of merges?

**Comment by silene** [comment]
No, it does not require any fix. So, at this point, it is mostly a question of deciding whether the benefits (faster decision procedures, more intuitive proofs, one parser/printer less) outweigh the issues (poor backward compatibility for low-level scripts).

**Comment by ejgallego** [comment]
Merging this patch (which looks great IMO) would break testing of flocq, compcert, and coquelicot. These are important packages. Guillaume, do you think such packages could be updated upstream as to be compatible with both 8.6 and 8.7 + this patch?

**Comment by ppedrot** [comment]
As for myself, I think that the benefits are strictly greater than the one issue of this PR, namely backward-compatibility. So I'm in favour of merging it.

**Comment by silene** [comment]
> Guillaume, do you think such packages could be updated upstream as to be compatible with both 8.6 and 8.7 + this patch?

For Coquelicot, it should be possible (though I won't have time to do that for the next two weeks). For Flocq, it is next to impossible, since Flocq comes with its own mechanism for "fixing" `IZR` (basically the same one as this pull request). Thus Flocq's mechanism intrinsically depends on the "broken" definition of `IZR`. So while the patch to Flocq is trivial (just replace the whole mechanism by a few identity functions), I can't think of a way to make Flocq compatible with both 8.6 and 8.7. Please someone implements `#ifdef` for Coq! Anyway, this would solve the issue only for the standalone version of Flocq, not the one included in CompCert. Now that dependencies are more easily handled thank to using `opam`, we should revisit the issue of Flocq being embedded in CompCert.

**Comment by ejgallego** [comment]
> Please someone implements #ifdef for Coq!
+1 I've been thinking about this for a long time.

For now I guess you could use a poor's man version. There are two ways as far as I know:
- ship to different versions of a module containing the differences, and set the proper symlink at make time, this is what math-comp does.
- use `#ifdef` and call `cpp` at make time to generate the proper version of the file.

I may try the second approach to make `HoTT` 8.6/8.7 compatible.

**Comment by silene** [comment]
> ship two different versions of a module containing the differences, and set the proper symlink at make time, this is what math-comp does

Yes, that is what we have been using for the Coq library of Why3 too. Some of the files exist in three different versions (8.4, 8.5, and 8.6) and the `Makefile` machinery copies them around.

**Comment by JasonGross** [comment]
> Please someone implements #ifdef for Coq!

Here is a messier but lighter-weight poor man's `ifdef` inside of Coq:
```coq
      Ltac ifdef' name x y :=
        tryif constr_eq name name then exact x else exact y.
      Definition F
        := ltac:(ifdef' x True False).
      Definition T
        := ltac:(ifdef' True True False).
      Print F. (* F = False *)
      Print T. (* T = True *)
```

**Comment by ppedrot** [comment]
> Please someone implements #ifdef for Coq!

... which opportunately reminds me that the discussion on attributes for the 8.7 version has stalled...

**Comment by ejgallego** [comment]
Indeed, it would likely be more lightweight if `coq_makefile2` would support `cpp`, together with seeding the files the proper version variables, etc...

**Comment by herbelin** [comment]
>    Please someone implements #ifdef for Coq!

And which reminds me Coq 8.0 which had a "V7only [ vernac list ]." command :)

**Comment by Zimmi48** [comment]
@ppedrot: there is no CEP for attributes, is there? If not, then maybe you could create a minimal one and the discussion could start again on the PR in the CEP repo (as this was the new workflow proposed by @silene).

**Comment by ppedrot** [comment]
At some point @aspiwack was mumbling something about writing such a CEP...

**Comment by herbelin** [comment]
The basic idea was to have commands like "Inductive [ attributes ] T ...", "Definition [ attributes ] C ...", etc... Did I understand correctly?

**Comment by ppedrot** [comment]
The exact syntax has not been decided, but in the spirit yes. This would allow to define stuff on a Coq version basis, assuming we have some attribute `version(...)`.

**Comment by herbelin** [comment]
Would the syntax for tactics get attribute, whether it is on an individual basis, or at the level of a sentence?

**Comment by aspiwack** [comment]
Regarding attributes: I've got a draft proposal somewhere, indeed, as well as an incomplete prototype implementation. I'll try to unearth it next week.

**Comment by Zimmi48** [comment]
I would very much be in favor of tactics taking attributes too, with some of them being generic and some being tactic-specific. That would avoid having tons of custom syntax: less syntax is better for learning...

**Comment by ppedrot** [comment]
That's starting to be a bit off-topic, but I'd personally like that attributes are attached to sentence rather than particular constructs, so that the syntax is uniform. For instance, something along the lines of:
```
#[version(8.5)]
Definition foo := 0.
```

**Comment by amahboubi** [comment]
I like this PR very much : I vote for its integration in spite of the backward compat issues. @silene : have you considered using the feature of the ring tactic allowing for a post-processing sub-tactic? May be this could help with the issue of re-folding constants, the one you mention in the log of d0d79fe4d821d1602824d62ff8d2ad7cd0a6ce21.

**Comment by silene** [comment]
> have you considered using the feature of the ring tactic allowing for a post-processing sub-tactic?

I did for a while, but I dismissed it. Otherwise that would have mean that 1. the simplification tactic evaluates the morphisms, 2. the kernel checks convertibility, 3. the post-processing tactic refolds the morphisms, 4. the kernel checks convertibility. So three steps out of four are just wasting a lot of computational power.

By removing the simplification step, we now have: 1. the kernel checks convertibility, 2. the post-processing tactic evaluates the morphisms (if needed), 3. the kernel checks convertibility (if needed). So out of the four original steps, only one is still mandatory. The two optional steps are needed only if the user needs both a transparent morphism and a simplification tactic, which I have yet to see in practice.

Also, for people who are less familiar with this topic, I should mention that, in the first solution, the post-processing tactic has to be some full-blown reification function, while in the second solution, a one-liner should be sufficient (`cbv`). So not only is the second solution more efficient, it is also more user-friendly.

**Comment by amahboubi** [comment]
This is convincing. Thank you for your answer @silene.

**Comment by silene** [comment]
I have rebased the branch on top of trunk. I have also reordered the commits so that the first four ones can be applied whether this pull request is accepted or not. Backward compatibility has been improved so that all the issues with `INR` should have vanished. In particular, the controversial pull request #450 is no longer needed.

The remaining backward compatibility issues are:
- opaqueness of ring morphisms (but that is for the greater good), and
- no syntactical identity between `-(42)` (`Ropp (IZR 42)`) and `-42` (`IZR (-42)`).

**Comment by maximedenes** [comment]
From what I understood during the WG, the failure on CoRN still has to be investigated before merge.

**Comment by silene** [comment]
> From what I understood during the WG, the failure on CoRN still has to be investigated before merge.

The initial failure was an actual issue with the pull request (ring morphisms strike again), which has been fixed by the latest rebase. Now the failures are purely due to the new definition of `IZR`, so they can only be fixed upstream. In other words, it is just a matter of finding some time to make sure that my CoRN patch is also suitable for 8.6 and submit it upstream.

I also intend to check that Flocq's failure does not hide an actual failure in CompCert, just to be on the safe side before merging.

**Comment by silene** [comment]
I confirm that CompCert is fine too, so it is again just a matter of making a patch and pushing it upstream. By the way, I very much doubt that other pull requests will be depending on this one anytime soon, so we might well wait for the various patches to have migrated upstream before considering merging this pull request.

**Comment by Zimmi48** [comment]
If #456 could be merged, 21a161e could then be replaced by a commit setting

    Corn_CI_BRANCH=IZR
    Corn_CI_GITURL=https://github.com/silene/corn.git

(this is I think what @ejgallego calls "an overlay").

**Comment by maximedenes** [comment]
#456 merged :)

**Comment by ejgallego** [comment]
Yes, the overlay system is a bit clunky for the moment, I suggest you put all the overlays in a temporary commit to be later just dropped.

**Comment by ejgallego** [comment]
@Zimmi48 there is a prototype of a clunky system here: https://github.com/ejgallego/coq/tree/travis+basic_overlay, basically untested but I hope it expresses the idea.

**Comment by maximedenes** [comment]
FTR, the CompCert fix has been merged. Now waiting for https://github.com/c-corn/corn/pull/40

**Comment by silene** [comment]
@maximedenes If you want me to, I can merge (and fix the conflicts).

**Comment by maximedenes** [comment]
Maybe simply rebasing and dropping the overlay would be perfect, since it would launch Travis one last time.

**Comment by maximedenes** [comment]
@silene are you doing it or should I do it? Either way is fine, but it would be good to get this merged :)

**Comment by silene** [comment]
Testing each rebased commit takes some time, which I haven't been able to allocate yet. I doubt I will be able to do it in the next few days, so feel free to do it.

**Comment by maximedenes** [comment]
Oh, but we don't usually test each intermediate commit. Is there any reason this PR should receive special treatment?

**Comment by herbelin** [comment]
> but we don't usually test each intermediate commit.

Wouldn't it be better for "git bisect" if it were?

**Comment by Zimmi48** [comment]
@maximedenes I think that there is a tradition that each intermediate commit is correct w.r.t the test-suite. This is something that can be achieved by adding `exec make check` commands in between each commit during the rebase, but which obviously takes time. I don't think that this policy has really been enforced lately anyways. At least newcomers aren't really informed about it.

**Comment by maximedenes** [comment]
@herbelin yes, I was not implying that it is useless. It is indeed better for bisects.

I can setup the infrastructure to do such test locally before merging. @ejgallego can Travis do that?

**Comment by ejgallego** [comment]
@maximedenes not that I know of

**Comment by Zimmi48** [comment]
Travis is already very busy with all the PRs. I don't think it would be reasonable to test external development compatibility at each commit anyways.

**Comment by maximedenes** [comment]
Indeed. But I'll try to improve my merge script so that it builds each intermediate commit and maybe runs the test-suite.

**Comment by ejgallego** [comment]
So I feel that recommended forms of rebase in the guide should either be:
- `git rebase -x "make clean && make -j" trunk` 
- `git rebase -x "make clean && make -j test-suite trunk"`
depending on the nature of the changes.

**Comment by maximedenes** [comment]
Rebased, test-suite running on each commit. Final Travis test at: https://travis-ci.org/maximedenes/coq/builds/213931842

**Comment by maximedenes** [comment]
Rebased and merged in trunk, thanks a lot!

**Comment by herbelin** [comment]
This is a report of experience on porting the contributions `AILS` and `Float` to the new models for integer numbers in `R`.

[Note: `AILS` is an implementation of the _Airborne Information for Lateral Spacing_ algorithm while `Float` is a floating-point library - maybe is it obsolete?]

In `AILS` and sometimes `Float`, there were typical breakages of the following form:

- `4*x` does not rewrite anymore to `2*2*x` by associatiativy
- `1+1` not any more the same as `2`
- `1` syntactically distinct from `R1`
- `0` syntactically distinct from `R0`
- `-1` syntactically distinct from `Ropp R1`
- for better compatibility, `-0` should now be written `-(0)`

So, I guess this is expected and, at least for the two first cases, we cannot do a lot about it.

In Float specifically, the breakages are of different kinds:

- `simpl` on expressions of the form `IZR local_constant` are now blocked. This is fixable by using a `unfold local_constant`.
- `simpl` on expressions of the form `IZR (Zpos p)` are now blocked. This is fixable using typically a `unfold IZR; rewrite <- INR_IPR`.
  - Example: `auto` expects to apply the hint `0 <= INR (Pos.to_nat n)` but finds `0 <= IZR (Z.pos n)`.	
  - Note that in the case of `ring`, no changes would have been needed if `ring` had been able to recognize that `IZR (Z.pos p)` and `INR (Pos.to_nat p)` are the same. Don't know if it would be easy to do it.
- Another issue with `ring` is that `ring_simplify` on `0+1` now returns `R1`, while the scripts would have worked without needing a change if it had returned `1%R`, since all lemmas involving the units in the library are now about `0%R` and `1%R`. Is there anything we can do for that? More generally, could it be possible to do so that we never have to see `R0` and `R1` any more?
- Finally, note that sometimes, a full block of several lines is not anymore necessary, which looks very good!

**Comment by Zimmi48** [comment]
It's kind of unfortunate that this porting was not done while the PR was still open, isn't it? If the coq-contribs AILS and Float are still considered worth maintaining, they should be added to Travis CI. But you are suggesting yourself that maybe Float is obsolete. Was it the contrib which was strongly criticized as fundamentally incomplete by some people a while ago?

More generally, the question could be asked for all contribs. Which ones are still worth maintaining? Which ones are useful to people, and actually used? Could some of them find an external maintainer? ...

**Comment by silene** [comment]
> `simpl` on expressions of the form `IZR local_constant` are now blocked.

Yes, I have experienced it too. I feel like it is more of an issue with `simpl` than with `IZR`. For some reason, `simpl` is not applied to inner terms when outer terms are not simplifiable.

> `auto` expects to apply the hint `0 <= INR (Pos.to_nat n)` but finds `0 <= IZR (Z.pos n)`.

I wonder if we should add `IZR_le` to the hint database. This would automatically solve a bunch of goals.

> if `ring` had been able to recognize that `IZR (Z.pos p)` and `INR (Pos.to_nat p)` are the same

No real difficulty but quite a bit of work. Since `IZR (Z.pos p)` and `INR (Pos.to_nat p)` are no longer convertible, the current reification mechanism of `ring` cannot handle them the same way. It would have to be extended the way it was for `psatz` and `lra`, which are able to recognize a lot of constants.

>  `ring_simplify` on `0+1` now returns `R1`

That surprises me. Part of the commits were especially meant to prevent that from happening. I will have to take a look at it.

> More generally, could it be possible to do so that we never have to see `R0` and `R1` any more?

Theoretically, if none of your developments explicitly mention `R0` and `R1`, they should only appear when you perform full-blown reduction à la `vm_compute`. Hopefully, no one ever calls `vm_compute` on a term of type `R`.

**Comment by herbelin** [comment]
> > simpl on expressions of the form IZR local_constant are now blocked.

> Yes, I have experienced it too. I feel like it is more of an issue with simpl than with IZR. For some reason, simpl is not applied to inner terms when outer terms are not simplifiable.

Looks unavoidable as this seems the standard way to work for `simpl`. It does not unfold a local definition if this does not contribute to a reduction.

This has by the way sometimes surprising consequences:
```coq
Lemma f (x := 1) : S x = x -> x + x = x * x.
intro; simpl.
(* S x = x -> S x = 1 *)
```
> > auto expects to apply the hint 0 <= INR (Pos.to_nat n) but finds 0 <= IZR (Z.pos n).

> I wonder if we should add IZR_le to the hint database. This would automatically solve a bunch of goals.

Maybe worth to try, I don't know.
> > ring_simplify on 0+1 now returns R1

> That surprises me. Part of the commits were especially meant to prevent that from happening. I will have to take a look at it.

Here is a reproducible example:
```coq
Require Import Reals Ring.
Goal (0+1=0)%R.
ring_simplify (0+1)%R.
```
> >  if ring had been able to recognize that IZR (Z.pos p) and INR (Pos.to_nat p) are the same

> No real difficulty but quite a bit of work. Since IZR (Z.pos p) and INR (Pos.to_nat p) are no longer convertible, the current reification mechanism of ring cannot handle them the same way. It would have to be extended the way it was for psatz and lra, which are able to recognize a lot of constants.

Could a pre-processor which rewrites one in the other relevant? An equivalent to `zify` for `ring`?

**Comment by silene** [comment]
> Here is a reproducible example

That is a funny one. It happens that 1 and -1 are hardcoded in the tactic. Since I had exercised the `ring_simplify` tactic only on non-trivial examples, I had missed this special case. Patch incoming.

> Could a pre-processor which rewrites one in the other relevant? An equivalent to `zify` for `ring`?

That would be relevant. Yet, since `ring` is a reflective tactic and since this work can be done efficiently in a reflective setting, it would be a bit frustrating to have to fall back to rewriting here.

**Comment by herbelin** [comment]
@Zimmi48: We need an infrastructure for benchmarking. We need a way to evaluate the impact of our changes on user developments. At best, this is the collection of all developments we are aware of, but reasonably, it can only be a representative subset of them.

Now, there is an inner contradiction in a benchmarking test: if we decide for a change of semantics, as we did for this PR, we must update the benchmarking suite otherwise it would not test anything further. This has been done for the packages tested on Travis, but of course there are many other packages available around which where not tested and which we could decide to test also. It is about finding an optimal compromise. In particular, we provided patches for the contributions tested on Travis so that we were still able to use the benchmarking suite (and, incidentally, this provides with a graceful service that we offer to the developers of these packages which we test).

Personally, as I said a couple of times, I believe that contributing to build a repository of mathematical and computer science results is important. This is a direction that Isabelle follows with AFP and that Mizar also follows with MML, a direction about which there was a [seminar](www.dagstuhl.de/16421) last October and which shows the interest of a community in this direction (especially the CICM community). Coq is not only a programming software, Coq has also a historical role to play as a tool to build formal mathematical knowledge and we should not lose this opportunity.

Also, when I'm testing `AILS` and `Float`, my objective is not to maintain them per se but to study from examples what should be done to improve the compatibility, what should be done so that the users don't have to waste time in maintaining their own contributions. Then, once they compile, they can in turn be reasonably reused for testing.

`Float` is not the contrib which was discussed some time ago. It was `IEEE374`. I'm mentioning `Float` as an example of package in the "contribs" subset which the authors may want to remove if they think e.g. that `Flocq`, developed by a group of authors non-disjoint from the ones of `Float`, can maybe seen as the natural upgrade of `Float`.

**Comment by Zimmi48** [comment]
> Personally, as I said a couple of times, I believe that contributing to build a repository of mathematical and computer science results is important. This is a direction that Isabelle follows with AFP and that Mizar also follows with MML, a direction about which there was a seminar last October and which shows the interest of a community in this direction (especially the CICM community). Coq is not only a programming software, Coq has also a historical role to play as a tool to build formal mathematical knowledge and we should not lose this opportunity.

You know I agree with you on that objective. This is also why I'm arguing for putting the standard library into its own repository. It could be the occasion to gather more contributions. For me, contribs do not correspond to the notion of a central repository. They are still external developments, even if they are maintained by the Coq developers.

> Also, when I'm testing AILS and Float, my objective is not to maintain them per se but to study from examples what should be done to improve the compatibility, what should be done so that the users don't have to waste time in maintaining their own contributions. Then, once they compile, they can in turn be reasonably reused for testing.

Yes but then, why not include them into Travis? Your feedback would have been useful to improve the PR. It is still useful now, but earlier would have been better. And we would have got that feedback earlier if these contribs had been included in the Travis tests.

> Float is not the contrib which was discussed some time ago. It was IEEE374. I'm mentioning Float as an example of package in the "contribs" subset which the authors may want to remove if they think e.g. that Flocq, developed by a group of authors non-disjoint from the ones of Float, can maybe seen as the natural upgrade of Float.

OK thanks! Indeed, this should be considered and decided by the authors themselves. Similarly, the author of GeoCoq asked for the removal of the older contrib for which it is a replacement (I don't know if that wish has been taken into account though.)

**Comment by herbelin** [comment]
@Zimmi48: In general, I'm more on the side of thinking that it is unavoidable to have an experimentation phase for features, even more that we clearly have the responsiveness to deal with post-commit improvements. So, I'm not shocked by this PR having been merged, after having taken into account the elements of the PR discussion, in a state which looks to me reasonable.

And I'm fine with being the one who looks at the contribs compatibility.

**Comment by silene** [comment]
> Flocq, developed by a group of authors non-disjoint from the ones of Float, can maybe seen as the natural upgrade of Float

To be clear, the natural upgrade of Float (15 years old) is PFF (10 years old). Note that it might be that the content of the contrib is actually PFF and it just happens that the contrib was never renamed; I haven't checked. Flocq is meant to absorb PFF in the long run, but it is not there yet. In fact, Flocq contains some `.v` files that actually require PFF; they are not compiled by default to avoid the dependency.

**Comment by herbelin** [comment]
@silene: the version we have contains files which are the light grey ones at the [pff](http://lipforge.ens-lyon.fr/www/pff/) page (up to `AllFloat.v`).

So, what are your projects with the PFF extension of Float? If the project is that Flocq absorbs
PFF in the long run, and if Flocq actually already morally depends on PFF, wouldn't it make more sense that PFF is integrated to Flocq now, even if in the long run some modifications are brought to PFF?

Of course, this is a very naive question since I'm unaware of the technical and material issues relative to such a move. So, I apologize for this probable naivety.

**Comment by silene** [comment]
> the version we have contains files which are the light grey ones at the pff page

So it is indeed the Float part only.

> So, what are your projects with the PFF extension of Float?

It is not clear yet. We certainly don't want to expose the (outdated) interface of Float/PFF, but some of the more complicated results are only available in PFF. As a rule of thumb, all the facts proved in the light grey files (that is, Float) have been made obsolete by Flocq, but some of the higher-level files of PFF (e.g. `FmaErrApprox`) still contain original (and sufficiently interesting) results.

**Comment by Zimmi48** [comment]
So since Float has been made obsolete and Flocq is tested in Travis, do you think Float should be removed from the contribs or does it still make sense to keep it?

**Comment by herbelin** [comment]
A few more comments about the impact of this PR on compatibilitity.
- That `simpl` on expressions of the form `IZR (Zpos p)` or `IZR (Zneg p)` are now blocked remains one of the important cause of incompatibilities. Is there something to improve here? In particular, it is not fully clear to me what are the situations when we want `IZR` to be `simpl never` and when we would like instead it to reduce a bit. @silene, do you know more?
- There are still a few lemmas which `auto` cannot solve anymore. A typical one is `0 <= 2` formerly proved by `Rlt_le, Rle_lt_0_plus_1, Rlt_le, Rlt_0_1`, but which now fails because `Rle_lt_0_plus_1` produces `R1` while `Rlt_0_1` expects `1%R`. Should `Rle_lt_0_plus_1` mention `1%R` instead?

**Comment by silene** [comment]
> That `simpl` on expressions of the form `IZR (Zpos p)` or `IZR (Zneg p)` are now blocked remains one of the important cause of incompatibilities.

There might be a misunderstanding there. The cause of the incompatibility is not that `IZR` no longer reduces, it is that it is no longer convertible to `INR` (except for 0, 1, and 2). I cannot think of a single situation where reducing `IZR` is actually interesting, even for compatibility purpose.

> Should `Rle_lt_0_plus_1` mention `1%R` instead?

Does it not?

    Lemma Rle_lt_0_plus_1 : forall r, 0 <= r -> 0 < r + 1.

Anyway, as I said, a goal like `0 <= 2` is meant to be solved by `IZR_le` rather than a long sequence of lemmas. Unfortunately, I have not yet found time to check what would be broken by adding this lemma to the hint database of `auto`.

**Comment by herbelin** [comment]
@silene: Looks like I'm going round in circles. I'm hoping a strict compatility of `simpl in IZR (Z.neg x)` returning `Ropp (INR (Pos.to_nat x))`, which is hopeless. The workaround is `unfold IZR; rewrite <- INR_IPR` and strict compatibility seems unattainable.

About `Rle_lt_0_plus_1`, I indeed spoke too quickly, it is `apply`ing the lemma which exposes the `R1` after unfolding `2%R`. So, nothing really new since my previous message.

**Comment by herbelin** [comment]
Hi, I noticed another example of unexpected unfolding of real constants using the Maple mode which is relying on low-level commands of the `ring`/`field` plugin. I could not find though a way to get a similar behavior with the high-level tactics `field_simplify` or `ring_simplify`.
```coq
Require Import Reals.
Ltac f x := constr:(FEc 2%Z).
Goal True.
prove_with_field ltac:(f) (1+1)%R.
(* (R1 + R1)%R = (R1 + R1)%R -> True *)
```
This is related to `protect_fv` which normalizes the constants, but I'm unsure how to fix that (don't know how to adapt the `ring_simplify` fix from d6ced637).

**Comment by silene** [comment]
> don't know how to adapt the ring_simplify fix from d6ced63

From a quick glance at the code, it seems like the function that needs protection is `FEeval`. So the trick is to look at the commit message of ddbc383. The `phi` argument occurs at position `10`, so `10` has to be moved from `Eval` to `Rec`, as was done in d6ced63. I will try later today whether it breaks anything.

**Comment by herbelin** [comment]
Seems indeed to fix the problem I observed. Thanks very much!

**Comment by herbelin** [comment]
For compatibility purposes, I'm trying to transform a real constant into an expression made only of `Rplus`, `Rmult`, `R0`, `R1`, `Rdiv`, `Ropp`. Don't know if this is the best idea, but my first try is to prove lemmas such as `forall x, IZR (Zpos (xO x)) = 2 * IZR (Zpos x)` which do not seem to exist. There is an optimizing function `IPR_2` which saves a trailing `* R1` as we did before. Do I consider that this optimization is important, even if the expansion of constants is now supposingly to be exceptional and prove a sublemma `IPR_2 x = 2 * IPR x`?

Alternatively, that would be cool to have some `set IZR simpl nomatch in tac` tacticielle.

**Comment by silene** [comment]
> For compatibility purposes, I'm trying to transform a real constant into an expression made only of

What I did for `fourier` is just `compute [IZR IPR IPR_2]`. Since the normal form of real constants has not changed between 8.6 and trunk, I don't see the point of having lemmas, reducing should be enough.

**Comment by herbelin** [comment]
@silene, a comment not to forget: the chapter describing notations still mentions the old encoding of reals.

**Comment by silene** [comment]
Oh! I didn't even know it was documented in the reference manual. Will do.

**Pull request closed without merging**
