### PR TITLE
[bench] 4.11.1 vs 4.07.1

### PR DESCRIPTION
**Pull request by ejgallego**
Don't look at me.

### CODE REVIEW

**Comment by ppedrot** [comment]
For more lulz you should also try with 4.06 vs. some recent stuff.

**Comment by ejgallego** [comment]
> For more lulz you should also try with 4.06 vs. some recent stuff.

@ppedrot 4.06 vs 4.07 should work too?

[last time I did that I couldn't spot a big difference]

**Comment by ejgallego** [comment]
Well, interesting results:
```
┌─────────────────────────────┬──────────────────────────┬──────────────────────────────────────────────┬──────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]       │                  CPU cycles                  │               CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                          │                                              │                                              │                                │                   │
│                package_name │     NEW     OLD  PDIFF   │               NEW               OLD  PDIFF   │               NEW               OLD  PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2219.53 2521.57 -11.98 % │     6188352401580     7018881497705 -11.83 % │    12570826950155    11446962364839  +9.82 % │     819672     774980  +5.77 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1007.96 1057.93  -4.72 % │     2804145845820     2941994213577  -4.69 % │     4626204295813     4629296786612  -0.07 % │    1070104    1070760  -0.06 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  367.42  382.39  -3.91 % │     1032929756316     1075374563874  -3.95 % │     1760988596378     1837850703519  -4.18 % │    3294368    3508672  -6.11 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  593.12  611.01  -2.93 % │     1646095524284     1695075682115  -2.89 % │     2597286055082     2583778137837  +0.52 % │    1049640    1036416  +1.28 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  630.43  644.30  -2.15 % │     1764748168865     1806067063580  -2.29 % │     2908550025100     2718213247620  +7.00 % │    3373196    2997960 +12.52 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 3919.63 3989.04  -1.74 % │    10898395420607    11099620651127  -1.81 % │    21093424472985    21162644041489  -0.33 % │    1026212    1113256  -7.82 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  217.20  220.11  -1.32 % │      601861572804      608365035725  -1.07 % │     1013857394019     1003205178221  +1.06 % │    1087880    1087500  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   58.82   59.57  -1.26 % │      162808378553      165334755466  -1.53 % │      211647767225      204977885884  +3.25 % │     509512     528856  -3.66 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4894.45 4953.55  -1.19 % │    13595520117501    13747186151354  -1.10 % │    24526173681941    23634361532446  +3.77 % │    2147396    2325156  -7.65 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  538.64  545.08  -1.18 % │     1506723766518     1523763571503  -1.12 % │     2679843639051     2794946296622  -4.12 % │     691160     747372  -7.52 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1062.18 1071.17  -0.84 % │     2958394905201     2983994850900  -0.86 % │     4768819205838     4750383014522  +0.39 % │    1051004     995372  +5.59 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1254.39 1263.46  -0.72 % │     3492868234006     3517381749092  -0.70 % │     4960765830528     4897357937114  +1.29 % │     927808     934576  -0.72 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  289.07  291.06  -0.68 % │      804868064537      810595834280  -0.71 % │     1252412058517     1249550256940  +0.23 % │     834736     827656  +0.86 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  315.38  316.95  -0.50 % │      854928579097      857698454914  -0.32 % │     1398285756188     1376082294104  +1.61 % │     608732     635908  -4.27 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  161.14  160.48  +0.41 % │      448019105121      445943831113  +0.47 % │      631960923427      619054071468  +2.08 % │     749340     735360  +1.90 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1483.24 1474.56  +0.59 % │     4135126562389     4107465640498  +0.67 % │     6397763675247     6222387074122  +2.82 % │    1182616    1164380  +1.57 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  161.80  160.28  +0.95 % │      448324438753      445543638301  +0.62 % │      570944112262      553096576990  +3.23 % │     833232     822056  +1.36 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   81.93   80.60  +1.65 % │      224639297465      222180114513  +1.11 % │      328100100367      310424105697  +5.69 % │     782568     768524  +1.83 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   59.78   58.72  +1.81 % │      165901498444      161734022002  +2.58 % │      229964583586      215328903715  +6.80 % │     471316     472088  -0.16 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1793.86 1761.80  +1.82 % │     4996195675938     4906886376306  +1.82 % │     7830505518407     7512945384964  +4.23 % │     859932     855748  +0.49 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  175.76  172.59  +1.84 % │      489179286418      480510685593  +1.80 % │      702143836157      677602444160  +3.62 % │     705904     691792  +2.04 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1291.28 1263.65  +2.19 % │     3593132019711     3517748788483  +2.14 % │     5145701602052     4950184399389  +3.95 % │    1238984    1174724  +5.47 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  143.19  140.04  +2.25 % │      398316964221      390407936233  +2.03 % │      527671353637      503677892197  +4.76 % │     572976     565056  +1.40 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  124.84  121.47  +2.77 % │      343435639901      335773985565  +2.28 % │      433051775261      413624326565  +4.70 % │     570712     574152  -0.60 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   49.70   48.16  +3.20 % │      137393049422      133302011858  +3.07 % │      193756629526      183798025741  +5.42 % │     495060     486332  +1.79 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   52.56   50.65  +3.77 % │      143746267854      138368567687  +3.89 % │      189078340757      176319199609  +7.24 % │     532388     520776  +2.23 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  198.47  191.09  +3.86 % │      554361501369      532163857417  +4.17 % │      755487792735      700314983260  +7.88 % │     508836     505068  +0.75 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  699.29  664.91  +5.17 % │     1948548051819     1854076888671  +5.10 % │     2786337702812     2556013202303  +9.01 % │    1128004    1131220  -0.28 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  573.61  543.64  +5.51 % │     1604572527057     1518215487986  +5.69 % │     2237429635889     2073882823396  +7.89 % │     604468     592392  +2.04 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  112.51  106.18  +5.96 % │      319253112246      302260752861  +5.62 % │      437435530782      401496545163  +8.95 % │     485268     487352  -0.43 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  656.62  618.91  +6.09 % │     1830626663379     1726226996352  +6.05 % │     2416311450164     2190563233295 +10.31 % │    1593232    1455000  +9.50 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   75.48   69.50  +8.60 % │      206859130050      191017016431  +8.29 % │      276977963077      245324147911 +12.90 % │     590580     587328  +0.55 % │    0    0  +nan % │
└─────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────┴──────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```

**Comment by ejgallego** [comment]
Here is a bench running 4.07.1 vs 4.11.1 + best_fit https://gitlab.com/coq/coq/-/jobs/741853859

**Comment by ppedrot** [comment]
The speedup in fourcolor is concentrated in Qed commands in the `theories/job*.v` files, which are essentially VM invocations.

**Comment by ejgallego** [comment]
New bench https://gitlab.com/coq/coq/-/jobs/743387217 , this time for 4.07.1+flambda vs 4.11.1+flambda

**Comment by Zimmi48** [comment]
> Here is a bench running 4.07.1 vs 4.11.1 + best_fit https://gitlab.com/coq/coq/-/jobs/741853859

Are you also planning a bench of 4.11.1 vs 4.11.1+best_fit?

**Comment by ejgallego** [comment]
> Are you also planning a bench of 4.11.1 vs 4.11.1+best_fit?

Yes, but we already have numbers that we understand more or less in #11277

**Comment by JasonGross** [comment]
@ejgallego I'm surprised you don't spot a big difference with 4.06 vs >= 4.07 in fiat-crypto due to the performance blow-ups of https://github.com/ocaml/ocaml/issues/7826 on generated OCaml code

**Comment by gasche** [comment]
Could you provide numbers for 4.07.1 vs 4.08.1? This would be helfpul to discuss https://github.com/ocaml/ocaml/issues/9326 without the noise related to later-version changes.

**Comment by ejgallego** [comment]
@SkySkimmer actually this is still pending as we need to test the fix for the GC issue which was recently released.

**Comment by gasche** [comment]
The OCaml upstream is still interested in understanding and resolving the cause of post-4.07 performance regression. It would help if some people on the Coq side were willing to help us investigate, at least by running benchmarks.

**Comment by ejgallego** [comment]
@gasche indeed definitively on my TODO list

**Pull request closed without merging**
