### PR TITLE
Faster computation of coprime systems in Micromega

### PR DESCRIPTION
**Pull request by ppedrot**
We assert a hidden invariant and leverage it to reduce crawling over lists.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
I'm not sure the coq-stlib speedup is related (maybe Nia.v from the test-suite?) but in any case this cannot hurt.

**Comment by SkySkimmer** [comment]
Test suite is `coq` not `coq-stdlib`

**Comment by ppedrot** [comment]
As per the bench, I actually meant the `coq` package.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
