### PR TITLE
[rm] update release notes

### PR DESCRIPTION
**Pull request by gares**
This seems the more safe way to push the tags you want.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Why not, but what case are you trying to circumvent with this option?

**Comment by gares** [comment]
The old code pushed *all tags*. The new code pushes only the ones in the release branch, which is a subset ;-)

**Comment by Zimmi48** [comment]
> The old code pushed _all tags_. The new code pushes only the ones in the release branch, which is a subset ;-)

Yes, it's better, I agree. I have been confused because I did the following test `git push origin v8.12 --follow-tags --dry-run` and it resulted in:

```
To github.com:Zimmi48/coq.git
 * [new branch]            v8.12 -> v8.12
 * [new tag]               V8.10+alpha -> V8.10+alpha
 * [new tag]               V8.11+alpha -> V8.11+alpha
 * [new tag]               V8.12+alpha -> V8.12+alpha
 * [new tag]               V8.12+beta1 -> V8.12+beta1
 * [new tag]               V8.12.0 -> V8.12.0
 * [new tag]               V8.12.1 -> V8.12.1
 * [new tag]               V8.13+alpha -> V8.13+alpha
 * [new tag]               V8.14+alpha -> V8.14+alpha
 * [new tag]               V8.8.2 -> V8.8.2
 * [new tag]               V8.9+alpha -> V8.9+alpha
```

and even if I understand why there are all those `+alpha` tags (which were done on `master`), and the three 8.12 tags, it puzzles me that there is also `V8.8.2` in the list.

**Review by Zimmi48 — APPROVED** [review]
Anyway, I agree this is better.

**Comment by gares** [comment]
I just found out that you can push a single tag by just got push upstream tag. Too obvious. That should be the suggested command.

**Comment by Zimmi48** [comment]
Will you update your PR to recommend this instead?

**Comment by gares** [comment]
done. I left the dry run there, but I really don't see what could go wrong.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
@coqbot: merge now

**Pull request merged**
