### PR TITLE
Split pretyping/ into unification/ and pretyping/

### PR DESCRIPTION
**Pull request by SkySkimmer**
pretyping/ feels like it was doing 2 things IMO: high level econstr manipulations (reductionops, unification stuff) and turning globs into constrs. It was also pretty big (in file count) so seems worth splitting.

unification.ml cannot be easily moved as it calls
Pretyping.solve_remaining_evars (and through it typeclasses etc) which
seems to belong to pretyping/. Maybe a hook should be used?
It also calls Coercion (see diff).

Based on https://github.com/coq/coq/pull/15302

### CODE REVIEW

**Comment by herbelin** [comment]
I like the idea, but it is not fully clear to me that having `typing.ml`, `reductionops`, `inductiveops`, `cbv.ml`, `arguments_renaming.ml`, `retyping`, `pretype_errors.ml` ... in `unification`, but `unification.ml` in `pretyping` is intelligible. Maybe dispatch into three directories, or move some files to `engine`.

> `unification.ml` cannot be easily moved

Would cutting it in two parts work?

**Comment by SkySkimmer** [comment]
>unification.ml cannot be easily moved 

Looking at it again the pretyping call isn't really part of unification.ml, it's a separate API which can be moved to tactics.ml.

There are still calls to coercions and typeclasses which I'm not sure about moving and can't be removed.

**Comment by SkySkimmer** [comment]
Also I'm not sure that unification/ is the best name.

**Comment by ejgallego** [comment]
Better than a hook is to expose the API as a parameter, even if the top level users get a fixed call for now, at least the deps get recorded in the type IMHO.

[And in the future it may turn out that the resolution parameter is actually used differently]

**Comment by ppedrot** [comment]
Rather than `unification` I'd call it something-something-`typing` because most of the modules are reduction/typing-oriented.

**Comment by gares** [comment]
typing, retyping and arguments_renaming should not be in unification/

**Comment by SkySkimmer** [comment]
Maybe unification.ml should move upwards to tactics (this can be done if we also take clenv from proofs, tbh I don't know why clenv is in proofs).
What I called unification/ is really some sort of "econstr ops" directory and pretyping/ is more glob_constr-oriented

**Comment by herbelin** [comment]
> Maybe unification.ml should move upwards to tactics (this can be done if we also take clenv from proofs, tbh I don't know why clenv is in proofs).

The file `clenv` moved several times in the past. It was notoriously difficult to find a place for it.

> What I called unification/ is really some sort of "econstr ops" directory and pretyping/ is more glob_constr-oriented

Then, a name needs to be found for talking about reduction, typing, unification altogether? Maybe `infer`? Or simply `typing`? Or even `constr`? I find `unification` a bit restrictive, but why not also.

Side question, do we have a graph of file dependencies somewhere?

**Comment by herbelin** [comment]
Thanks. And, if easy, when run on the two directories of the PR?

**Comment by SkySkimmer** [comment]
deps

**Comment by SkySkimmer** [comment]
(the globenv -> evardefine is just for `type type_constraint = types option` btw, pretty trivial)

**Comment by gares** [comment]
imo vnorm and nativenorm should go in unification (where "reduction" is), similarly find_subterm, tacred and constr_matching.
If you do so, the only weird thing, is IMO, globops, which has nothing to do with unification. Maybe it can be split?
At the same time typing and retyping should go to pretyping.

**Comment by gares** [comment]
IMO the dependency of evarsolving on retyping is one of the spagetti that is fundamental (I don't care if it is represented using HO features or a ref). It is like typing/conversion in the kernel, if we had to split it we would not put typing under conversion because of (IIRC) a corner case in sprop.

**Comment by gares** [comment]
I'm fine with "matching tools" be part of unification, since they are very much related.

**Comment by SkySkimmer** [comment]
> At the same time typing and retyping should go to pretyping.

I strongly disagree, I see them as being much lower level concepts.

**Comment by SkySkimmer** [comment]
BTW inductiveops and reductionops might belong in engine/, not sure

**Comment by gares** [comment]
IMO typing should not even exist, it is a boring copy of pretyping because of a wrong setup of our datatypes. If we were using polymorphic variants, for example, there would be no reason to have both (the input would have ``` `Implicit``` while the output would not).

Retyping is something you can only do on an already typed term, so it is naturally higher than the function to type it for the first time.

At least to me `unification/` is about conversion extended to evars. Typing in any of its forms seem not to fit there.

**Comment by SkySkimmer** [comment]
IMO pretyping/ should be about glob stuff, "unification" is just a guess at what to put the rest under. Maybe I should have called it econstrops instead. Or maybe globtyping/ and etyping/.
The current state of the PR does not necessarily match my dream.

**Comment by gares** [comment]
vnorm and nativenorm may even be moved elsewhere, even if I don't know where (maybe in tactics)

**Comment by gares** [comment]
> IMO pretyping/ should be about glob stuff

Well, this is exactly why we disagree. To me Glob_term.t should really ``` Constr.t + `Implcit ``` , so defining a component around a datatype which is "wrong" unsettles me.

Note that type classes for example are a key component of elaboration (pretyping) but have nothing to do with glob terms.

**Comment by SkySkimmer** [comment]
There are other differences, like cases and coercions. Or would we want to apply coercions in typing?

**Comment by gares** [comment]
The unfolding of deep pattern match depends on types only when there are no branches (otherwise from the constructor you know the inductive, hence everything you need to expand). In the vacuous case we could require `in False` or `in Empty`, or even default to the former.

About coercions, that is the thing: I don't understand the use case for `typing`, which does all but coercions. I mean ,CS resolution, TC resolution... I don't think this deserves a new algorithm, it is just an option to the elaboration one (disabling one feature). Imo `typing` exists only because of the data type problem I was writing about. I would be happy to call pretyping on an econstr all the times, but I can't (and in Elpi I do have hacks that go trough detyping...).

Retping is another story, we don't store the types all the times (on subterms and subterms) and we often discard them in tactics and need to quickly recompute them. It is really a poor man cache. Be it somewhere just above econstr, fine. Be it in unification because it is the "first client"... bleah.

**Comment by SkySkimmer** [comment]
Maybe we can talk about this in the WG or some other time.

**Pull request closed without merging**
