### PR TITLE
chore: add #7392 to test-suite

### LINKED ISSUE #7392: eapply triggers Anomaly "Uncaught exception Not_found."
#### Version

Coq master

#### Operating system
Linux

#### Description of the problem
 The following code triggers an anomaly:

```coq
From Coq Require Import Utf8.

Class ElimInv {X Y : Type} (Pout : X → Y) (Pclose : X → option Y) :=
  elim_inv : False.

Class IntoAcc {X Y : Type} (E1 E2 : nat) (α β : X → Y) :=
  into_acc : False.

Global Instance elim_inv_acc_with_close {X Y : Type} E1 E2 α β (foo : nat → nat → Y → Y) :
  IntoAcc E1 E2 α β →
  ElimInv (X:=X) (Y:=Y) α (λ x, Some (foo E1 E2 (β x))).
Proof. intros []. Qed. 

Lemma tac_inv_elim {X Y : Type} Pout Pclose :
  ElimInv (X:=X) (Y:=Y) Pout Pclose →
  False.
Proof. intros []. Qed.

Global Instance into_acc_na E n :
  IntoAcc (X:=unit) (Y:=nat) E E (λ _, 0) (λ _, 5 + n).
Proof. Admitted.

Goal False.
eapply tac_inv_elim with (Pclose:=(λ xx, Some _)).
eapply @elim_inv_acc_with_close.
eapply @into_acc_na. (* EXPLOSION *)
```
This seem to be related to the fact that `into_acc_na` unifies `E1` and `E2` -- if I change that instance to make the two `E` independent, the anomaly goes away.

I originally ran into this during Iris development, and got a different error message:
```
Error: Unable to unify "?E2" with "?E1@{x:=_UNBOUND_REL_1}" as
 "?E1@{x:=_UNBOUND_REL_1}" contains local variables.
```
I am not sure if that's actually a different problem, but for now I can't really make progress on minimizing the original issue.

### PR DESCRIPTION
**Pull request by Alizter**
`bug_7392.v` already existed for the same bug (#7586) but was named wrong. I've renamed it and added #7392 correctly.

Closes #7392.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
No webhook was delivered for the comment. I'll report to GitHub.

**Comment by Alizter** [comment]
@ppedrot ping

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
