### PR TITLE
Allow universe declarations for [with Definition].

### PR DESCRIPTION
**Pull request by SkySkimmer**
Depends on #6879.

### CODE REVIEW

**Comment by Zimmi48** [comment]
No CHANGES, no tests, no doc?

**Review by ppedrot — DISMISSED** [review]
The code is OK, but as mentioned by @Zimmi48, this needs at least one test and probably a CHANGES entry as well.

**Comment by SkySkimmer** [comment]
Found #6878 while writing tests.

**Comment by SkySkimmer** [comment]
@ppedrot changed

**Comment by Zimmi48** [comment]
@SkySkimmer You could put this PR on top of the other one and add the label "needs: merge of dependency" or just uncomment the test and add the label "needs: independent fix"...

**Comment by SkySkimmer** [comment]
Now depends on #6879.

**Pull request merged**
