### PR TITLE
Fix kernel incorrectly assuming the "using" hyps are transitively closed

### LINKED ISSUE #13903: Anomaly when using #[using=...]
#### Description of the problem

The following code snippet raises an anomaly.
```coq
Section test.
Variables (T : Type) (x : T).
#[using="x"] Definition test : unit := tt.
```
results in 
```
Error:
Anomaly
"File "kernel/term_typing.ml", line 274, characters 15-21: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

I spotted this while trying to fix an issue in https://github.com/math-comp/hierarchy-builder/pull/181 and was noticing the anomaly through the coq-elpi API. It turns out the problem is on the Coq side.

CC @gares 

#### Coq Version

Coq 8.13.0 and 8.13.1

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13903

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
I'd rather have the upper layers generate the right set of variables. The kernel should be as dumb as possible.

**Comment by SkySkimmer** [comment]
This PR removes code in the kernel, it's simpler this way imo

**Comment by SkySkimmer** [comment]
Being dumb also means not requiring extra invariants that you have no use for.

**Comment by gares** [comment]
Oh, so the code was already handling the transitive closure? And the invariant was wrong.

**Review by ppedrot — APPROVED** [review]
I am not super fan of the solution, but OK.

**Comment by ppedrot** [comment]
(The motivation for the broken invariant is to detect that somebody up is wreaking havoc, which was witnessed here. We can make the life of the upper layers easier, but it will also prevent detecting suspicious behaviours.)

**Comment by gares** [comment]
But this PR only removes the check! This is what I don't get: the test passes a non-closed list of section variables.

**Pull request merged**
