### PR TITLE
Simplify the newring hack

### PR DESCRIPTION
**Pull request by ppedrot**
We simplify the newring hackish implementation of selective reduction. Not perfect yet but less entangled.

The new implementation is 100% compatible with the previous one, but it is more compact and does not use a tricky translation function from the kernel.

### CODE REVIEW

**Review by amahboubi — APPROVED** [review]
Ok with me. Note that @barras is probably the author of this piece of code. He may want to have a look as well.

**Review by maximedenes — APPROVED** [review]
The kernel change is trivial.

**Comment by maximedenes** [comment]
@amahboubi can you assign yourself and merge this PR? @barras doesn't seem often online.

**Comment by ppedrot** [comment]
@amahboubi Thanks!

**Comment by SkySkimmer** [comment]
The merge commit has a github-style commit message, did you use the merge script?

**Comment by amahboubi** [comment]
No, I used the github merge. Sorry, I just discovered the dev doc about it (trying to understand what you were referring to). Thanks @SkySkimmer. Should I do something specific to improve it?

**Comment by Zimmi48** [comment]
@amahboubi 
> Should I do something specific to improve it?

Are you asking about improving the merging doc or about improving the situation with respect to this particular PR?
For the merging doc, make sure you have read and understood it fully. If that's not the case, open an issue or a pull request if you have a proposal on how to make it better.
For this particular PR, there is nothing to do to improve the situation. It is not a big deal anyways but the merge script will run a bunch of checks before merging and will format the commit in a way that is expected by the backport script (in this case the PR doesn't need to be backported so no worries).

**Comment by amahboubi** [comment]
@Zimmi48 I was asking about this particular PR. Thanks for the clear answer.

**Pull request merged**
