### PR TITLE
[ci] [gitlab] Update OCaml trunk gitlab jobs.

### PR DESCRIPTION
**Pull request by ejgallego**
- OCaml trunk is now called 4.10.0+trunk
- findlib and dune should not need pinning
- the build should be warning free for 4.10.0 after #10471

### CODE REVIEW

**Comment by ejgallego** [comment]
This requires https://github.com/coq/coq/issues/10602 to be fixed first.

**Comment by ejgallego** [comment]
After adding workaround for the issues mentioned above, the test-suite passes again.

**Comment by ejgallego** [comment]
If #10606 is merged, the PR should work by itself, for now the realistic solution is to keep using the deprecated `Obj.` constructions.

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
Turned out to be trickier than expected , closing in favor of #10726

**Pull request closed without merging**
