### PR TITLE
[travis] Fix version of camlp5 for OCaml 4.06.1.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Fix is correct, Travis script is indeed buggy.

**Comment by SkySkimmer** [comment]
I guess opam init is noop even if the compiler is not the current one?

**Comment by ejgallego** [comment]
> I guess opam init is noop even if the compiler is not the current one?

Yeah that's a problem we've been carrying with us since at least the original script I think.

**Comment by ejgallego** [comment]
> Yeah that's a problem we've been carrying with us since at least the original script I think.

So in fact we need to do a switch; Théo, could you add the following line to this PR?
```
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- opam switch "$COMPILER"
- eval $(opam config env)
```

**Comment by ejgallego** [comment]
Thanks, let's see how this goes in the CI.

**Comment by Zimmi48** [comment]
It passed here, and on my branch as well: https://travis-ci.org/Zimmi48/coq/builds/376959995

**Comment by ejgallego** [comment]
Will not wait for Appveyor as it seems it would introduce a > 24 hour lag.

**Pull request merged**
