### PR TITLE
Correct description of multiple hintdb handling

### PR DESCRIPTION
**Pull request by jfehrle**

### CODE REVIEW

**Comment by jfehrle** [comment]
@coq/doc-maintainers Would someone review?  Thanks.

**Review by Zimmi48 — APPROVED** [review]
Thanks!

And good idea to add a test matching the documentation improvement!

@coqbot merge now

**Comment by proux01** [comment]
This doesn't readily backports to the v8.20 branch.

**Comment by jfehrle** [comment]
Don't worry about it then.

**Pull request merged**
