### PR TITLE
Remove global output_native_objects flag.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure about the 2nd commit, but without it, it bugged me that output_native_objects is in coqargs instead of coqcargs.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Finally!!! Looks great, and it really fixes https://github.com/coq/coq/issues/4607

**Comment by ejgallego** [comment]
This is pretty straightforward so will merge quickly.

**Comment by SkySkimmer** [comment]
>it really fixes #4607

Behaviour shouldn't change so I don't know what you mean.

**Review by maximedenes — APPROVED** [review]

**Comment by ejgallego** [comment]
> Behaviour shouldn't change so I don't know what you mean.

We were never too comfortable with having two boolean flags for what essentially is a ternary one.

**Pull request merged**
