### PR TITLE
Rename generated directory gramlib__pack -> gramlib/.pack

### PR DESCRIPTION
**Pull request by SkySkimmer**
It's a bit cleaner this way, especially wrt the number of toplevel directories.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Nice!

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@gares @ejgallego one of you should assign

**Comment by ejgallego** [comment]
ltac2 fails.

**Comment by SkySkimmer** [comment]
Let's see how it goes now.

**Comment by ejgallego** [comment]
Ok merging.

**Pull request merged**
