### PR TITLE
Add changes for 8.15.2.

### PR DESCRIPTION
**Pull request by ppedrot**
As discussed in #16064. I'll tweak the latter accordingly. cc @SkySkimmer

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by SkySkimmer** [comment]
We should probably come up with a changelog for the coqide stuff too.

**Comment by Zimmi48** [comment]
@SkySkimmer Please update the PR and let me know when you want this to be merged.

**Comment by SkySkimmer** [comment]
Updated

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
