### PR TITLE
Remove use of "tacv" in Ltac doc

### PR DESCRIPTION
**Pull request by jfehrle**
See #16652, second item.

### CODE REVIEW

**Comment by jfehrle** [comment]
@Alizter could you assign/merge this one, to?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
Sorry that took so long, it must have slipped through my notifications. =

**Comment by jfehrle** [comment]
I don't see a lot of value in tweaking `doc_grammar` for this.  Indentation already distinguishes the variants.  One needs to know when to stop making changes.  Better to work on other things that will provide more value.  The Sphinx doc could say that tacv/cmdv are deprecated.  Perhaps you would make that change?

On another topic, what about [this](https://coq.zulipchat.com/#narrow/pm-with/299351,299404-pm/near/340683046)?

**Comment by jfehrle** [comment]
> Sorry that took so long, it must have slipped through my notifications.

No worries, thanks.

**Pull request merged**
