### PR TITLE
extending zify saturate class with arguments

### PR DESCRIPTION
**Pull request by frantisekfarka**
- [ ] Added / updated **test-suite**.

- [x] Added **changelog**.
- [x] Added / updated **documentation**.
  
  - [x] Documented any new / changed **user messages**.
  - [x] Updated **documented syntax** by running `make -f Makefile.dune doc_gram_rsts`.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by frantisekfarka** [comment]
Can e.g. @maximedenes say what he thinks about breaking backward compatibility / deprecating existing TC's first?

**Comment by Alizter** [comment]
Since none of the developments in the CI have failed, I think we should keep this PR as is. We should also add a changelog entry detailing the difference in arguments, in case anybody was relying on it before.

I feel like going through the deprecation cycle will be overkill. cc @coq/stdlib-maintainers @Zimmi48

**Comment by Zimmi48** [comment]
Suppose that some project outside CI is broken by this change. Is there a simple solution for this project to be fixed in a compatible way (e.g., by redefining some classes/instances)? If yes, your proposal sounds reasonable, especially with a clear changelog.

I'm asking without having looked at the PR contents precisely.

**Comment by frantisekfarka** [comment]
Re fixing a broken project; it means fixing instances of `Sataurate` class the same way instances in `ZifyN.v` and `ZifyNat.v` are fixed in this PR.

**Comment by Alizter** [comment]
@frantisekfarka In that case, could you add a changelog entry and a small instruction on how to fix potential issues? See https://github.com/coq/coq/tree/master/doc/changelog#how-to-add-an-entry

**Comment by frantisekfarka** [comment]
I added the changelog entry

**Comment by frantisekfarka** [comment]
Any idea why the CI job `library:ci-unimath` started failing? I went through before and I didn't change code.

**Comment by SkySkimmer** [comment]
It's unrelated.
Should stop happening since #16509 (merged after this PR's CI started)

**Comment by frantisekfarka** [comment]
Ok, still I rebased and pushed so CI should go through.

**Comment by frantisekfarka** [comment]
What happens next? Can someone approve the PR?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
LGTM will merge soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
