### PR TITLE
Fix timing diff script to support non-utf8

### LINKED ISSUE #9705: coq-makefile: print-pretty-timed-diff broken
When trying to use the print-pretty-timed-diff target, there is some problem with the invoked python code (at least when using Python 3.7.2):

```
> make -f Makefile.coq print-pretty-timed-diff 
Traceback (most recent call last):
  File "/home/fakusb/.opam/coq-dev/lib/coq//tools/make-both-time-files.py", line 16, in <module>
    print_or_write_table(table, args[3:])
  File "/home/fakusb/.opam/coq-dev/lib/coq/tools/TimeFileMaker.py", line 215, in print_or_write_table
    print(table.encode("utf-8"), file=binary_stdout)
TypeError: a bytes-like object is required, not 'str'
make: *** [Makefile.coq:337: print-pretty-timed-diff] Error 1
```

this occurs both on coq 8.8.2 and master (at least in a build from 2 weeks ago)

### LINKED ISSUE #9767: Timing diff scripts should support non-utf8
#### Description of the problem

TimeFileMaker.py does not support files which emit non-utf-8 to stdout.  See [this job log](https://gitlab.com/coq/coq/-/jobs/176113494) and the conversation in https://github.com/coq/coq/pull/9752.  It would be nice for them to support this.  This requires using bytes/`rb` rather than `r`, etc.  I might do this on my own in about two weeks, though I'd love if someone more familiar with python3 and `bytes` would do this.

#### Coq Version

8.9

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** bug fix / infrastructure.

Fixes / closes #9767
Fixes / closes #9705
On top of #9766
Closes #9766

- [x] Added / updated test-suite
- [x] Entry added in CHANGES.md.

(Should this be backported to 8.9.1?)

### CODE REVIEW

**Comment by JasonGross** [comment]
Who should be assignee on this?

**Review by jashug — APPROVED** [review]
The input and output handling changes look OK to me.
I don't see what was changed to support non-ASCII in filenames nor does that seem to be tested.

**Comment by JasonGross** [comment]
Ah, oops.  Yeah, I realized afterwards that the change was actually to support python3 at all, I think.  I'll update the changes

**Comment by JasonGross** [comment]
While I'm at it, I guess I can also test for non-ascii filenames

**Comment by JasonGross** [comment]
> I don't see what was changed to support non-ASCII in filenames nor does that seem to be tested.

It is now tested, and I've updated the CHANGES to be more accurate

**Comment by Zimmi48** [comment]
>(Should this be backported to 8.9.1?)

Seems reasonable to me. FTR, to request backporting to v8.9, you should use the 8.9.1 milestone instead.

**Review by ejgallego — APPROVED** [review]
Thanks a lot @JasonGross ; looks pretty straightforward to me so I'll merge tomorrow.

**Comment by ejgallego** [comment]
@JasonGross @andres-erbsen @samuelgruetter bedrock2 is not failing with a missing `hexdump` https://gitlab.com/coq/coq/-/jobs/187636065

Could it be related to this PR?

**Comment by JasonGross** [comment]
The missing `hexdump` is a red herring (it is not fatal due to `|| true `), the real error is:
```
COQC /builds/coq/coq/_build_ci/bedrock2/deps/riscv-coq/src/Spec/MetricPrimitives.v
File "/builds/coq/coq/_build_ci/bedrock2/deps/riscv-coq/src/Spec/MetricPrimitives.v", line 35, characters 41-47:
Error: getMem is not a projection.
```
This is caused by the merge of #8829, which collided in flight with the merge of this PR ; the CI of this PR succeeded because #8829 had not yet been merged, and the CI of #8829 erroneously succeeded because the pipe to iconv that this PR reverted was masking errors in bedrock2 (I guess we forgot to set pipefail in the PR that added iconv).  The solution is to prepare an overlay for bedrock2 for #8829.

**Comment by ejgallego** [comment]
Oh, indeed sorry, thanks for the analysis @JasonGross

**Pull request merged**
