### PR TITLE
Fix printing anomaly in conv

### PR DESCRIPTION
**Pull request by herbelin**
This fixes (or more precisely improves) an ill-formatted error message as shown in this [comment](https://github.com/coq/coq/issues/6106#issue-271852409) at PR #6106.

The new proposed message is:
```
Error:
Ltac call to "case (ssrcasearg) (ssrclauses)" failed.
Conversion test raised an anomaly: Universe Top.3 undefined.
```

Note: I removed the "please report" since this anomaly is (on purpose) turned into an error (wouldn't it be left as an anomaly if it was to be reported?). (edited: removal cancelled)

In passing: fixing an apparently misplaced `spc` in the please report message, hoping I'm not breaking other intended behavior.

### CODE REVIEW

**Comment by herbelin** [comment]
PS: Same question as @gares: it is (also) a 8.7 bugfix, but I don't know how to indicate it. I set the milestone but I don't remember if this is supposed to be set only by @Zimmi48 or by everyone,

**Comment by maximedenes** [comment]
I thought on the contrary that we did want users to report conversion anomalies (and hence make it true anomalies), but that some of the legacy unification infrastructure was breaking the conversion test invariant that input terms should be of convertible types.

**Comment by herbelin** [comment]
@maximedenes: Indeed, see the discussion at #6106.

**Comment by herbelin** [comment]
@mattam82, @maximedenes: I removed the removal of "report". When the error arrives at toplevel, it should indeed be reported (it should also be turned into a proper anomaly, but that would be a bit complicated to keep the anomaly turned as an error in `unification.ml` and to turn it again as an anomaly when at toplevel, so I'm renouncing.).

**Comment by mattam82** [comment]
Ok, fine with me.

**Comment by Zimmi48** [comment]
@herbelin Same answer than to @gares: feel free to put the milestone and/or put the PR in the "Coq 8.7" project.

**Pull request merged**
