### PR TITLE
Remove opam files from repository.

### PR DESCRIPTION
**Pull request by Zimmi48**
They were not introduced for external use by users but because they were needed by Dune.  Now that they can be autogenerated by Dune, we do not need to check them into the repo anymore.  Removing them will remove the ability for users to rely on them and thus a confusing experience (due to not having Dune, or not getting `coqidetop` installed with the `coq` package, or the installation of `coq-doc` failing).

### CODE REVIEW

**Comment by kyoDralliam** [comment]
After this removal, is it still possible to install in a specific opam switch a checked out (and usually modified) coq worktree ? Will the *.opam files generated automatically by any dune target or is there a specific target to be called ?

**Comment by Zimmi48** [comment]
It should be possible. Both `dune build` and `dune build coq.opam` regenerate the opam files. However, I'm surprised that this trick was not enough to make CI pass, but I'm far from an opam expert, so I'll leave it to others to understand the issue.

**Comment by ejgallego** [comment]
Likely this fails because the files are not checked-in in the repository?

**Comment by Zimmi48** [comment]
But why would the files need to be tracked by git to work? I added the `dune build` commands to recreate these opam files before calling opam...

**Comment by ejgallego** [comment]
> But why would the files need to be tracked by git to work?

I think this is how opam works? I used to know this better, but I forgot.

**Comment by silene** [comment]
> But why would the files need to be tracked by git to work?

This is indeed a feature of Opam. And a good one, in my opinion. By considering only tracked files, this ensures that the pin does not get polluted by existing compilation artifacts. So, you do not need to run `git clean -fxd` before pinning a package.

But the case of `opam` files indeed looks like a chicken-and-egg issue. I think it is just an oversight because at the time `opam pin add` was designed, autogenerating `opam` files was not a thing.

If I remember correctly, you can bypass this check by passing `--kind=path` to `opam pin add` (instead of `--kind=git`, by default for a Git repository).

**Comment by Zimmi48** [comment]
Thanks for the explanation.

**Pull request closed without merging**
