### PR TITLE
Recurse less in extraction

### LINKED ISSUE #16172: Extraction is exponential with sequential functor instantiations even when only a linear amount of code is generated
#### Description of the problem

```coq
Require Import Coq.FSets.FMapPositive.
Require Import Coq.Structures.Equalities.
Require Import Coq.FSets.FMapInterface.
Local Set Implicit Arguments.

Module OptionMap (M:WS) <: WS.
  Module E <: DecidableType.
    Definition t := option M.E.t.
    Include HasEq <+ IsEqOrig <+ HasEqDec.
  End E.
  Definition t elt := (option elt * M.t elt)%type.
  Definition key := E.t.
  Definition empty elt : t elt := (None, @M.empty _).
  Definition MapsTo elt (k : key) (v : elt) (m : t elt) : Prop
    := match k with
       | None => fst m = Some v
       | Some k => M.MapsTo k v (snd m)
       end.
  Section Types.
    Variable elt:Type.
    Parameter is_empty : t elt -> bool.
    Parameter add : key -> elt -> t elt -> t elt.
    Parameter find : key -> t elt -> option elt.
    Parameter remove : key -> t elt -> t elt.
    Parameter mem : key -> t elt -> bool.
    Variable elt' elt'' : Type.
    Parameter map : (elt -> elt') -> t elt -> t elt'.
    Parameter mapi : (key -> elt -> elt') -> t elt -> t elt'.
    Parameter map2 :
     (option elt -> option elt' -> option elt'') -> t elt -> t elt' ->  t elt''.
    Parameter elements : t elt -> list (key*elt).
    Parameter cardinal : t elt -> nat.
    Parameter fold : forall A: Type, (key -> elt -> A -> A) -> t elt -> A -> A.
    Parameter equal : (elt -> elt -> bool) -> t elt -> t elt -> bool.
    Section Spec.
      Variable m m' m'' : t elt.
      Variable x y z : key.
      Variable e e' : elt.
      Definition In (k:key)(m: t elt) : Prop := exists e:elt, MapsTo k e m.
      Definition Empty m := forall (a : key)(e:elt) , ~ MapsTo a e m.
      Definition eq_key (p p':key*elt) := E.eq (fst p) (fst p').
      Definition eq_key_elt (p p':key*elt) :=
          E.eq (fst p) (fst p') /\ (snd p) = (snd p').
      Parameter MapsTo_1 : E.eq x y -> MapsTo x e m -> MapsTo y e m.
      Parameter mem_1 : In x m -> mem x m = true.
      Parameter mem_2 : mem x m = true -> In x m.
      Parameter empty_1 : Empty (@empty _).
      Parameter is_empty_1 : Empty m -> is_empty m = true.
      Parameter is_empty_2 : is_empty m = true -> Empty m.
      Parameter add_1 : E.eq x y -> MapsTo y e (add x e m).
      Parameter add_2 : ~ E.eq x y -> MapsTo y e m -> MapsTo y e (add x e' m).
      Parameter add_3 : ~ E.eq x y -> MapsTo y e (add x e' m) -> MapsTo y e m.
      Parameter remove_1 : E.eq x y -> ~ In y (remove x m).
      Parameter remove_2 : ~ E.eq x y -> MapsTo y e m -> MapsTo y e (remove x m).
      Parameter remove_3 : MapsTo y e (remove x m) -> MapsTo y e m.
      Parameter find_1 : MapsTo x e m -> find x m = Some e.
      Parameter find_2 : find x m = Some e -> MapsTo x e m.
      Parameter elements_1 :
        MapsTo x e m -> InA eq_key_elt (x,e) (elements m).
      Parameter elements_2 :
        InA eq_key_elt (x,e) (elements m) -> MapsTo x e m.
      Parameter elements_3w : NoDupA eq_key (elements m).
      Parameter cardinal_1 : cardinal m = length (elements m).
      Parameter fold_1 :
	forall (A : Type) (i : A) (f : key -> elt -> A -> A),
        fold f m i = fold_left (fun a p => f (fst p) (snd p) a) (elements m) i.
     Definition Equal m m' := forall y, find y m = find y m'.
     Definition Equiv (eq_elt:elt->elt->Prop) m m' :=
         (forall k, In k m <-> In k m') /\
         (forall k e e', MapsTo k e m -> MapsTo k e' m' -> eq_elt e e').
     Definition Equivb (cmp: elt->elt->bool) := Equiv (Cmp cmp).
     Variable cmp : elt -> elt -> bool.
     Parameter equal_1 : Equivb cmp m m' -> equal cmp m m' = true.
     Parameter equal_2 : equal cmp m m' = true -> Equivb cmp m m'.
    End Spec.
  End Types.

  Parameter map_1 : forall (elt elt':Type)(m: t elt)(x:key)(e:elt)(f:elt->elt'),
      MapsTo x e m -> MapsTo x (f e) (map f m).
  Parameter map_2 : forall (elt elt':Type)(m: t elt)(x:key)(f:elt->elt'),
      In x (map f m) -> In x m.
  Parameter mapi_1 : forall (elt elt':Type)(m: t elt)(x:key)(e:elt)
                            (f:key->elt->elt'), MapsTo x e m ->
                                                exists y, E.eq y x /\ MapsTo x (f y e) (mapi f m).
  Parameter mapi_2 : forall (elt elt':Type)(m: t elt)(x:key)
                            (f:key->elt->elt'), In x (mapi f m) -> In x m.
  Parameter map2_1 : forall (elt elt' elt'':Type)(m: t elt)(m': t elt')
	                    (x:key)(f:option elt->option elt'->option elt''),
      In x m \/ In x m' ->
      find x (map2 f m m') = f (find x m) (find x m').
  Parameter map2_2 : forall (elt elt' elt'':Type)(m: t elt)(m': t elt')
	                    (x:key)(f:option elt->option elt'->option elt''),
      In x (map2 f m m') -> In x m \/ In x m'.
End OptionMap.

Module ProdMap (M1:WS) (M2:WS) <: WS.
  Module E <: DecidableType.
    Definition t := (M1.E.t * M2.E.t)%type.
    Include HasEq <+ IsEqOrig <+ HasEqDec.
  End E.
  Definition t elt := M1.t { m : M2.t elt | ~M2.Empty m }.
  Definition key := E.t.
  Definition empty elt : t elt := @M1.empty _.
  Definition MapsTo elt (k : key) (v : elt) (m : t elt) : Prop
    := exists m2, M1.MapsTo (fst k) m2 m /\ M2.MapsTo (snd k) v (proj1_sig m2).
  Section Types.
    Variable elt:Type.
    Parameter is_empty : t elt -> bool.
    Parameter add : key -> elt -> t elt -> t elt.
    Parameter find : key -> t elt -> option elt.
    Parameter remove : key -> t elt -> t elt.
    Parameter mem : key -> t elt -> bool.
    Variable elt' elt'' : Type.
    Parameter map : (elt -> elt') -> t elt -> t elt'.
    Parameter mapi : (key -> elt -> elt') -> t elt -> t elt'.
    Parameter map2 :
     (option elt -> option elt' -> option elt'') -> t elt -> t elt' ->  t elt''.
    Parameter elements : t elt -> list (key*elt).
    Parameter cardinal : t elt -> nat.
    Parameter fold : forall A: Type, (key -> elt -> A -> A) -> t elt -> A -> A.
    Parameter equal : (elt -> elt -> bool) -> t elt -> t elt -> bool.
    Section Spec.
      Variable m m' m'' : t elt.
      Variable x y z : key.
      Variable e e' : elt.
      Definition In (k:key)(m: t elt) : Prop := exists e:elt, MapsTo k e m.
      Definition Empty m := forall (a : key)(e:elt) , ~ MapsTo a e m.
      Definition eq_key (p p':key*elt) := E.eq (fst p) (fst p').
      Definition eq_key_elt (p p':key*elt) :=
          E.eq (fst p) (fst p') /\ (snd p) = (snd p').
      Parameter MapsTo_1 : E.eq x y -> MapsTo x e m -> MapsTo y e m.
      Parameter mem_1 : In x m -> mem x m = true.
      Parameter mem_2 : mem x m = true -> In x m.
      Parameter empty_1 : Empty (@empty _).
      Parameter is_empty_1 : Empty m -> is_empty m = true.
      Parameter is_empty_2 : is_empty m = true -> Empty m.
      Parameter add_1 : E.eq x y -> MapsTo y e (add x e m).
      Parameter add_2 : ~ E.eq x y -> MapsTo y e m -> MapsTo y e (add x e' m).
      Parameter add_3 : ~ E.eq x y -> MapsTo y e (add x e' m) -> MapsTo y e m.
      Parameter remove_1 : E.eq x y -> ~ In y (remove x m).
      Parameter remove_2 : ~ E.eq x y -> MapsTo y e m -> MapsTo y e (remove x m).
      Parameter remove_3 : MapsTo y e (remove x m) -> MapsTo y e m.
      Parameter find_1 : MapsTo x e m -> find x m = Some e.
      Parameter find_2 : find x m = Some e -> MapsTo x e m.
      Parameter elements_1 :
        MapsTo x e m -> InA eq_key_elt (x,e) (elements m).
      Parameter elements_2 :
        InA eq_key_elt (x,e) (elements m) -> MapsTo x e m.
      Parameter elements_3w : NoDupA eq_key (elements m).
      Parameter cardinal_1 : cardinal m = length (elements m).
      Parameter fold_1 :
	forall (A : Type) (i : A) (f : key -> elt -> A -> A),
        fold f m i = fold_left (fun a p => f (fst p) (snd p) a) (elements m) i.
     Definition Equal m m' := forall y, find y m = find y m'.
     Definition Equiv (eq_elt:elt->elt->Prop) m m' :=
         (forall k, In k m <-> In k m') /\
         (forall k e e', MapsTo k e m -> MapsTo k e' m' -> eq_elt e e').
     Definition Equivb (cmp: elt->elt->bool) := Equiv (Cmp cmp).
     Variable cmp : elt -> elt -> bool.
     Parameter equal_1 : Equivb cmp m m' -> equal cmp m m' = true.
     Parameter equal_2 : equal cmp m m' = true -> Equivb cmp m m'.
    End Spec.
  End Types.

  Parameter map_1 : forall (elt elt':Type)(m: t elt)(x:key)(e:elt)(f:elt->elt'),
      MapsTo x e m -> MapsTo x (f e) (map f m).
  Parameter map_2 : forall (elt elt':Type)(m: t elt)(x:key)(f:elt->elt'),
      In x (map f m) -> In x m.
  Parameter mapi_1 : forall (elt elt':Type)(m: t elt)(x:key)(e:elt)
                            (f:key->elt->elt'), MapsTo x e m ->
                                                exists y, E.eq y x /\ MapsTo x (f y e) (mapi f m).
  Parameter mapi_2 : forall (elt elt':Type)(m: t elt)(x:key)
                            (f:key->elt->elt'), In x (mapi f m) -> In x m.
  Parameter map2_1 : forall (elt elt' elt'':Type)(m: t elt)(m': t elt')
	                    (x:key)(f:option elt->option elt'->option elt''),
      In x m \/ In x m' ->
      find x (map2 f m m') = f (find x m) (find x m').
  Parameter map2_2 : forall (elt elt' elt'':Type)(m: t elt)(m': t elt')
	                    (x:key)(f:option elt->option elt'->option elt''),
      In x (map2 f m m') -> In x m \/ In x m'.
End ProdMap.

Require Import Coq.extraction.Extraction.
Require Import Coq.extraction.ExtrOcamlBasic.
Unset Extraction Optimize.
Extraction Language OCaml.
Module OptionPositiveMap := OptionMap PositiveMap.
Module A0 <: WS := OptionPositiveMap.
Module A1 <: WS := ProdMap OptionPositiveMap A0.
Module A2 <: WS := ProdMap OptionPositiveMap A1.
Module A3 <: WS := ProdMap OptionPositiveMap A2.
Module A4 <: WS := ProdMap OptionPositiveMap A3.
Module A5 <: WS := ProdMap OptionPositiveMap A4.
Module A6 <: WS := ProdMap OptionPositiveMap A5.
Module A7 <: WS := ProdMap OptionPositiveMap A6.
Module A8 <: WS := ProdMap OptionPositiveMap A7.
Set Warnings Append "-extraction-logical-axiom,-extraction-opaque-accessed,-extraction-axiom-to-realize".
Time Redirect "A0.ml" Recursive Extraction A0.empty. (* Finished transaction in 0.245 secs (0.163u,0.081s) (successful) *)
Time Redirect "A1.ml" Recursive Extraction A1.empty. (* Finished transaction in 0.087 secs (0.087u,0.s) (successful) *)
Time Redirect "A2.ml" Recursive Extraction A2.empty. (* Finished transaction in 0.135 secs (0.135u,0.s) (successful) *)
Time Redirect "A3.ml" Recursive Extraction A3.empty. (* Finished transaction in 0.406 secs (0.403u,0.002s) (successful) *)
Time Redirect "A4.ml" Recursive Extraction A4.empty. (* Finished transaction in 1.22 secs (1.22u,0.s) (successful) *)
Time Redirect "A5.ml" Recursive Extraction A5.empty. (* Finished transaction in 2.307 secs (2.307u,0.s) (successful) *)
Time Redirect "A6.ml" Recursive Extraction A6.empty. (* Finished transaction in 8.235 secs (8.235u,0.s) (successful) *)
Time Redirect "A7.ml" Recursive Extraction A7.empty. (* Finished transaction in 32.504 secs (32.488u,0.01s) (successful) *)
```

Extracting An Seems to scale as approximately 4^(n - 4.5).  

Reduced from [Zulip thread](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Performance.20of.20.60Recursive.20Extraction.60/near/285754477).

Here's the [`perf.data` (in a .7z inside a .zip)](https://github.com/coq/coq/files/8886289/slow-extraction.perf.7z.zip), [svg flamegraph in a .zip file](https://github.com/coq/coq/files/8886294/slow-extraction-flamegraph.zip), and the flamegraph as an svgz: [slow-extraction.svg.gz](https://github.com/coq/coq/files/8886300/slow-extraction.svg.gz)

cc @ppedrot 

#### Coq Version

8.14.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16172

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@JasonGross could you test this on your original example?

**Comment by JasonGross** [comment]
My laptop is currently broken and I don't have access to Coq, but the code is available at https://github.com/mit-plv/fiat-crypto/pull/1293, just run `make SKIP_BEDROCK2=1 src/ExtractionOCaml/saturated_solinas.ml TIMED=1` and see if it takes closer to 20 seconds than 90 minutes to extract the .ml file.

**Comment by SkySkimmer** [comment]
Messed up the testing overlay the first time, let's try this again

**Comment by SkySkimmer** [comment]
It timed out in the Assembly/Symbolic that @ppedrot mentioned on zulip

**Comment by ppedrot** [comment]
Ah! Told you so. I have a partially written fix for this though, I can push it somewhere after some polishing.

**Comment by JasonGross** [comment]
That is very strange, it seems to work fine on our CI https://github.com/mit-plv/fiat-crypto/runs/6943380653?check_suite_focus=true , taking only 34s on master (https://github.com/mit-plv/fiat-crypto/runs/6943380973?check_suite_focus=true#step:7:3159).  This might be using an outdated version of master, though, since I haven't gotten around to updating my launchpad packages to have the latest dune, not to fix the issue with configure failing to detect the lablgtk version

**Comment by ppedrot** [comment]
I would be very surprised if this has to do with some recent change on master, though. The problem is basically the same as the exponential blowup of the reduced type for extraction. Here we're performing a (nonsensical) recursive analysis of nested inductive types to compute equality schemes, and since it reduces the constructor types, you get the blowup as well.

**Comment by SkySkimmer** [comment]
It's the Symbolic version in https://github.com/mit-plv/fiat-crypto/pull/1293 that's got an issue not the fiat-crypto master version. You can see it fail on that PR's CI too.

**Comment by JasonGross** [comment]
Oh, I see, that makes sense.  I guess the version I was timing the commit on was old enough (8.14, maybe? Or 8.11?) that it wasn't generating equality schemes for records, or something like that, and hence on that certain Symbolic went from 30s to 26s.  I'll probably disable scheme generation for that record when I actually merge the PR (and/or will make the type not exponentially sized).

**Comment by JasonGross** [comment]
> Ah! Told you so. I have a partially written fix for this though, I can push it somewhere after some polishing.

@ppedrot Should we open a separate issue to track this?

I've pushed an update to https://github.com/mit-plv/fiat-crypto/pull/1293 disabling the equality generation and I've restarted the CI here.  I've also opened https://github.com/coq-community/coq-performance-tests/pull/22 with the smaller examples

**Comment by JasonGross** [comment]
Seems to work!
```
      Time |   Peak Mem | File Name                       
------------------------------------------------------------------------------------------------------
  0m50.12s | 2330152 ko | ExtractionOCaml/bedrock2_word_by_word_montgomery.ml
  0m50.12s | 2330648 ko | ExtractionOCaml/with_bedrock2_word_by_word_montgomery.ml
  0m48.75s | 2287600 ko | ExtractionOCaml/word_by_word_montgomery.ml
  0m33.02s | 1988808 ko | ExtractionOCaml/with_bedrock2_unsaturated_solinas.ml
  0m32.82s | 1988728 ko | ExtractionOCaml/bedrock2_unsaturated_solinas.ml
  0m30.68s | 1871988 ko | ExtractionOCaml/unsaturated_solinas.ml
  0m27.56s | 1828552 ko | ExtractionOCaml/with_bedrock2_base_conversion.ml
  0m27.51s | 1849064 ko | ExtractionOCaml/bedrock2_saturated_solinas.ml
  0m27.42s | 1828688 ko | ExtractionOCaml/bedrock2_base_conversion.ml
  0m27.15s | 1848784 ko | ExtractionOCaml/with_bedrock2_saturated_solinas.ml
  0m25.41s | 1769136 ko | ExtractionOCaml/saturated_solinas.ml
  0m25.26s | 1734456 ko | ExtractionOCaml/base_conversion.ml
  0m23.38s | 1751072 ko | ExtractionOCaml/perf_word_by_word_montgomery.ml
  0m22.28s | 1707496 ko | ExtractionOCaml/perf_unsaturated_solinas.ml
```

**Comment by JasonGross** [comment]
Er, wait, was that run without the overlay pointing it at the right branch?

**Comment by JasonGross** [comment]
Could you re-add the overlay and we can test this here?

**Comment by JasonGross** [comment]
Ping @SkySkimmer

**Comment by JasonGross** [comment]
Gah, I did not realize that the CI merges the overlay with the current master, I guess I'll have to adjust the overlay branch

**Comment by JasonGross** [comment]
I still have to look into the failures at [the OCaml job](https://gitlab.com/coq/coq/-/jobs/2674308809) and [the underlying fiat-crypto job](https://gitlab.com/coq/coq/-/jobs/2674308807), but let me try running this with the intended branch

**Comment by JasonGross** [comment]
@SkySkimmer Minimized: https://github.com/coq/coq/issues/16288  This issue is already present in master, it was just exposed here by merging the overlay branch into fiat-crypto's master

**Comment by JasonGross** [comment]
@SkySkimmer CI looks to be building fiat-crypto fine now, and this PR seems to fix the issue:
```
      Time |   Peak Mem | File Name             
---------------------------------------------------------------------------------------------------------
  0m55.07s | 2347376 ko | ExtractionOCaml/with_bedrock2_word_by_word_montgomery.ml
  0m55.02s | 2347808 ko | ExtractionOCaml/bedrock2_word_by_word_montgomery.ml
  0m52.72s | 2332244 ko | ExtractionOCaml/word_by_word_montgomery.ml
  0m37.16s | 2023224 ko | ExtractionOCaml/bedrock2_unsaturated_solinas.ml
  0m37.10s | 2022888 ko | ExtractionOCaml/with_bedrock2_unsaturated_solinas.ml
  0m35.08s | 1909716 ko | ExtractionOCaml/unsaturated_solinas.ml
  0m31.97s | 1948772 ko | ExtractionOCaml/bedrock2_base_conversion.ml
  0m31.92s | 1948516 ko | ExtractionOCaml/with_bedrock2_base_conversion.ml
  0m31.66s | 1899424 ko | ExtractionOCaml/bedrock2_saturated_solinas.ml
  0m31.26s | 1899196 ko | ExtractionOCaml/with_bedrock2_saturated_solinas.ml
  0m29.98s | 1808244 ko | ExtractionOCaml/base_conversion.ml
  0m29.78s | 1853300 ko | ExtractionOCaml/saturated_solinas.ml
  0m26.05s | 1803544 ko | ExtractionOCaml/perf_word_by_word_montgomery.ml
  0m24.63s | 1771960 ko | ExtractionOCaml/perf_unsaturated_solinas.ml
```

Shall we merge, or do you want a formal bench?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@JasonGross Do you want this in 8.16? If we ask @ppedrot nicely he might agree.

**Comment by JasonGross** [comment]
It would be nice to have in 8.16, but I don't feel particularly strongly

**Comment by Alizter** [comment]
@ppedrot Please consider this for 8.16, but no biggie.

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@SkySkimmer Where is the overlay?

**Comment by SkySkimmer** [comment]
It's not a real overlay, it's only for testing

**Pull request merged**
