### PR TITLE
Reorganize the order of subsections under "Semantics" in Ltac chapter

### PR DESCRIPTION
**Pull request by jfehrle**
WDYT?

Separately, the subsection on `abstract` seems a bit out of place, perhaps it belongs in another chapter.

### CODE REVIEW

**Comment by Zimmi48** [comment]
> Separately, the subsection on `abstract` seems a bit out of place, perhaps it belongs in another chapter.

Agreed. It would probably be better suited in the Proof mode chapter.

**Comment by Zimmi48** [comment]
Toplevel goal selectors might also make more sense in the Proof mode chapter.

**Comment by Zimmi48** [comment]
Shouldn't "goal selectors" be under the "processing multiple goals" section?

**Comment by Zimmi48** [comment]
Shouldn't "control flow" come before "branching and backtracking" since the latter needs to talk about `;` which is presented in the former?

I don't have further comments on the reorganization? I defer to @JasonGross to confirm if this looks good to him.

Is the PR only reorganizing sections or is there new text that should be reviewed?

**Comment by jfehrle** [comment]
> Shouldn't "goal selectors" be under the "processing multiple goals" section?

The latter makes the specific point that the tactic has to succeed for all selected goals., somewhat different from goal selectors.  It doesn't have any subsections at the moment.  Also it's common for a goal selector to select a single goal.  I suppose they could merged into one section, but I thought it better to make them both visible in the TOC.  I'd leave this alone for now.

**Comment by jfehrle** [comment]
> Toplevel goal selectors might also make more sense in the Proof mode chapter.

It could be moved.  There's currently a little bit on selectors in the tactics chapter under "Invocation of tactics", so probably better to address in #15015.

**Comment by jfehrle** [comment]
> Shouldn't "control flow" come before "branching and backtracking" since the latter needs to talk about `;` which is presented in the former?

The description of `;` refers to backtracking, so the text has some circular references.  Readers will figure it out. Backtracking is more complex, so better to fully describe that first. 

Everything up to and including "Branching and backtracking" is general material that applies to many tactics/constructs, while "Control flow" and following sections describe all the individual tactics/constructs.

I think it's fine this way.

**Comment by jfehrle** [comment]
> Is the PR only reorganizing sections or is there new text that should be reviewed?

Just reorganizing.

Updated.

@JasonGross Any further comments?

**Comment by Zimmi48** [comment]
`abstract` could probably use its own section instead of being a subsection of "Navigating in the proof tree". I don't think it fits so well there (the location seems fine if it becomes a section).

**Comment by jfehrle** [comment]
I moved `abstract` outside of "Navigating in the proof tree".  Updated and squashed.

**Comment by Zimmi48** [comment]
> > Toplevel goal selectors might also make more sense in the Proof mode chapter.
> 
> It could be moved. There's currently a little bit on selectors in the tactics chapter under "Invocation of tactics", so probably better to address in #15015.

Possibly worth waiting to see how goal selectors will or will not be handled in Ltac2 (see #15378).

**Comment by jfehrle** [comment]
@JasonGross Is this OK in its current form?  I'd like to finish this PR--even though it's pretty simple, it's been pending 2 months. @Zimmi48 thought he was not the best person to review it.  You're probably a better choice.

**Review by JasonGross — APPROVED** [review]
Looks basically good to me.

**Comment by jfehrle** [comment]
@Zimmi48 Now that this has the @JasonGross seal of approval, would you merge it?  Merci.

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
