### PR TITLE
[pretyper] Less imperative passing of the evar_map, part I.

### PR DESCRIPTION
**Pull request by ejgallego**
This builds on the work on #8545.

### CODE REVIEW

**Comment by ejgallego** [comment]
The PR removing the rest of the pretyper is almost ready, however the test suite fails so I need to have another look before submitting.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
> The PR removing the rest of the pretyper is almost ready

I hope you don't mean that literally ;-)

**Comment by ejgallego** [comment]
> I hope you don't mean that literally ;-)

Ups, corrected.

**Comment by ejgallego** [comment]
Closed in favor of complete PR #8581

**Pull request closed without merging**
