### PR TITLE
Bench plotter script

### PR DESCRIPTION
**Pull request by SkySkimmer**
Use like `dev/bench/plotter coq-hott` (currently only supports 1 argument)

Should probably be cleaned up before merging.
hott
unimath

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>Should probably be cleaned up before merging.

cc @JasonGross as our main python dev
feel free to push directly to my branch

**Comment by SkySkimmer** [comment]
Some TODOs:
- gitlab logs get cached in ~/.cache but if the script is run while a bench is ongoing that bench's log will get stale requiring manual cleanup
- the y axis should have basis 0 not whatever the shortest time was

**Comment by JasonGross** [comment]
Another TODO:
- the x axis should display some dates, not random numbers. (even if it only displays like two or three dates, I think that's much better)

**Comment by SkySkimmer** [comment]
Maybe we should merge now and let additions happen when someone has a use for them?

**Comment by ppedrot** [comment]
I support merging indeed.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
