### PR TITLE
[options] Remove deprecated option automatic introduction.

### PR DESCRIPTION
**Pull request by ejgallego**
Resurrection of #6907

### CODE REVIEW

**Comment by ejgallego** [comment]
Ready. Overlay:
- https://github.com/UniMath/UniMath/pull/1053

**Comment by ejgallego** [comment]
Overlay has been merged, does anyone volunteer to take this trivial PR?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@ejgallego Can you remove the overlay? It's useless now.

**Comment by ejgallego** [comment]
> @ejgallego Can you remove the overlay? It's useless now.

Done.

**Pull request merged**
