### PR TITLE
Fix #5981, bugs/opened/3263.v is non-deterministic by removing the test.

### LINKED ISSUE #5981: bugs/opened/3263.v is non-deterministic
In [this AppVeyor run](https://ci.appveyor.com/project/coq/coq/build/master~537/job/ho0iwmmr2ey189on), [bugs/opened/3263.v](https://github.com/coq/coq/blob/master/test-suite/bugs/opened/3263.v) failed.
But in [this other AppVeyor run on the same commit](https://ci.appveyor.com/project/coq/coq/build/master~539/job/8ewgirptq6o2k7sm), the test passed.

Given that this is an "open" bug, maybe we could just remove this test to solve the problem.

#### Failure log (edit to complete)

- on AppVeyor on 2017-10-19

### PR DESCRIPTION
**Pull request by Zimmi48**
This bug fails non-deterministically from time to time (see #5981, and the most recent failure in #6809).
It is of the utmost importance to fix these random failures because when they happen we are forced to ignore them anyways.
In this case, given that this is an open (performance) bug, I think the most simple solution is just to remove the test. I'm open to alternative solution but not to an absence of action.
BTW this line `Fail Timeout 60 Defined. (* Timeout! *)` looks very suspicious to me: do we actually lose on minute (on one core) of compilation because of this test file??

### CODE REVIEW

**Comment by SkySkimmer** [comment]
> BTW this line Fail Timeout 60 Defined. (* Timeout! *) looks very suspicious to me: do we actually lose on minute (on one core) of compilation because of this test file??

Yes. The NSatz test also takes a while.

**Comment by Zimmi48** [comment]
Then it's one more reason to remove it. It must have made us lose hours (in total) and when it fails we don't even care.

**Review by JasonGross — APPROVED** [review]
It'd be nice to have something more deterministic here, but I don't have time right now to look into this, so I'm fine with removing it.

**Comment by Zimmi48** [comment]
Can I let you merge this then? The file doesn't have a listed owner (as with the rest of the test-suite).

**Comment by JasonGross** [comment]
Sure, I can merge.  What milestone should I set?

**Pull request merged**
