### PR TITLE
[thread] protect threads against sigalrm

### PR DESCRIPTION
**Pull request by gares**
Fix #7408 (when compiled with 4.08 if I got it right)

### CODE REVIEW

**Comment by gares** [comment]
My hope is that this PR makes the `success/auto.v` file work reliably with `-async-proofs on` (as of today there is a Timeout generating a signal that is sometimes catch by the wrong thread

**Review by ejgallego — COMMENTED** [review]
A few comments:
- I am not sure I like the `create` name; we should either name it `create_ignore_sigalarm` as it would be very confusing otherwise, or just do the ignore on the right places.
- How can we test this is working? Should you add a unit test?
- Hardcoding the signal name seems fragile, should timeout export a `timeout_signal` identifier?
- I am a bit confused how this is supposed to work. If you ignore a signal, it won't be redelivered to the right thread, but lost. So how is this supposed to work?

**Comment by gares** [comment]
>     * I am a bit confused how this is supposed to work. If you ignore a signal, it won't be redelivered to the right thread, but lost. So how is this supposed to work?

I don't mask the signal in the main thread, that is the one doing the computations (both in master and in the workers).

**Comment by gares** [comment]
> How can we test this is working? Should you add a unit test?

I really don't know how to reproduce it effectively, I was planning of running (by hand) the appropriate CI job a few times.

A unit test would just test what they do in caml, that is that `setsigmask` actually masks.
In the context of Coq I don't know... I'd just grep for `Thread.create` in order to be sure the entire codebase uses `CThread.create`.

**Comment by gares** [comment]
> Hardcoding the signal name seems fragile, should timeout export a `timeout_signal` identifier?

I'm not sure I follow, the `alarm` system call is not changing the signal it raises, ever (it is a standard).

**Comment by gares** [comment]
run 1 of `test-suite:base+async` passed, running again

**Comment by gares** [comment]
run 3 of `test-suite:base+async` passed, running again

**Comment by ejgallego** [comment]
Ok, thanks for the responses, I am indeed OK with the current status of the patch then, an in particular with using `create`.

However I am still confused about this:

> I don't mask the signal in the main thread, that is the one doing the computations (both in master and in the workers).

So does POSIX guarantee that the signal will be delivered to the main thread? Where is this particular case specified? I am wary because of the comment of Xavier a few weeks ago about the futility of implementing `Timeout` like this.

**Comment by gares** [comment]
> So does POSIX guarantee that the signal will be delivered to the main thread

IIRC signal should be delivered to all threads (the main one is not special).

In any case, there are plenty of tests using Timeout, so I'm pretty sure it is delivered.
What I can't test is that we actually mask it in all threads (but the main one). I run it 5 times...

**Comment by ejgallego** [comment]
> IIRC signal should be delivered to all threads (the main one is not special).

It is indeed delivered not to all threads but to an arbitrary one. After reading the documentation I do think indeed blocking should be enough as the wording says "the signal will be delivered to an arbitrary thread which didn't block the signal".

I am OK with the patch then, maybe you want to tweak the commit message a bit to use "main thread" instead of "computing thread" which confused me a bit.

CI is failing on Windows tho, what's going on there?

**Comment by ejgallego** [comment]
> CI is failing on Windows tho, what's going on there?

So indeed it seems that this PR breaks Timeout on Windows.

**Comment by gares** [comment]
>  I guess `Sys.os_type` returns "Cygwin"

No, it returns "Windows" hence we run a code path that should not be affected by this patch.
Indeed Windows jobs on appveyor and gitlab worked, so there must be something special about the azure job... 

Anything comes to mind? @coq/ci-maintainers

**Comment by ejgallego** [comment]
> Anything comes to mind? @coq/ci-maintainers

It is not very likely but it could well be a different kernel version making a different threading choice?

**Comment by gares** [comment]
I found it: `Thread 2 killed on uncaught exception Invalid_argument("Thread.sigmask not implemented")`

So I guess I should just make the syscall safe

**Comment by gares** [comment]
Something weird is happening since the azure job is not running... ideas? 

A side note for @coq/ci-maintainers : the issue is that the ocaml runtime running on azure is not the same runtime running on gitlab since it has nonstandard external C functions: sigmask shoud not raise `Invalid_argument "not implemented"`, but it does.

**Comment by SkySkimmer** [comment]
>Something weird is happening since the azure job is not running... ideas?

Indeed I don't know

**Comment by gares** [comment]
I try a close + open to give azure a second chance

**Comment by jhjourdan** [comment]
I am currently working on the OCaml patch to make Thread.sigmask. We had to revert the original patch, which created some regressions. It turns out it is more difficult than initially anticipated, and I now have a bug to debug on MacOS X.

See https://github..com/ocaml/ocaml/pull/2211, and stay tuned.

**Comment by jhjourdan** [comment]
(That's said, this is no reason to suspend the integration to this patch in Coq, since the function already exists in previous OCaml versions.)

**Comment by ejgallego** [comment]
> A side note for @coq/ci-maintainers : the issue is that the ocaml runtime running on azure is not the same runtime running on gitlab since it has nonstandard external C functions: sigmask shoud not raise `Invalid_argument "not implemented"`, but it does.

Can you tell more about what the above means? How they can differ, they are the same than appveyor for example?

Any link to an OCaml issue?

**Comment by gares** [comment]
Ci is green now, also on azure. Can someone merge this?

**Comment by gares** [comment]
The prebuilt opam for Windows thing has a heavily patched runtime. Iirc one can find the diff online, and be scared...

**Comment by ejgallego** [comment]
> The prebuilt opam for Windows thing has a heavily patched runtime. Iirc one can find the diff online, and be scared...

Yes but what I mean is that in Appveyor we use the same exact runtime and still didn't see a difference?

**Review by ejgallego — APPROVED** [review]
The `try ... with ...` block on `cThread` likely deserves a comment, other than that the patch seems good.

**Comment by gares** [comment]
comment added

**Comment by Zimmi48** [comment]
@gares Do you expect this to solve #7483, #7388, and #5982?

**Pull request merged**
