### PR TITLE
Use Cpred for simpl_never, more efficient Tacred.make_simpl_reds

### PR DESCRIPTION
**Pull request by SkySkimmer**
Alternative to https://github.com/coq/coq/pull/18184

Overlays:
- https://github.com/LPCIC/coq-elpi/pull/526
- https://github.com/coq-community/vscoq/pull/680

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer looks like vscoq needs an overlay.

**Comment by RalfJung** [comment]
This seems overall [slightly faster](https://coq-speed.mpi-sws.org/d/1QE_dqjiz/coq-compare?orgId=1&var-project=iris&var-branch1=ci/timing&var-commit1=7429a2500c8edb75c291414b7e5409df23a102ec&var-config1=build-coq.dev&var-branch2=ci/timing&var-commit2=00dad6b95411dd6ca5039d66301b189806e6d1e8&var-config2=build-coq.dev&var-metric=instructions) than the other PR I benchmarked. It's slower on some files but faster on others and over all of Iris it's a bit faster.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
