### PR TITLE
Compatibility of 8.6 with OCaml 4.06.0.

### PR DESCRIPTION
**Pull request by herbelin**
Roughly as suggested by @ejgallego.

How complicated would it be to adapt the release scripts to make a 8.6.2?

### CODE REVIEW

**Comment by ejgallego** [comment]
That's great @herbelin , indeed you may want to modify 8.6 .travis.yml so it tests against 4.06.0 instead of 4.04.0 as today.

**Comment by ejgallego** [comment]
And thanks for fixing my suggestion, now I realized I was looking at the wrong configure.ml file. Even 8.7.0 is not compatible with 4.06.0

**Comment by Zimmi48** [comment]
For the num library, why not use the test as it is in master?

```ocaml
(** Num library *)

(* since 4.06, the Num library is no longer distributed with OCaml (replaced
   by Zarith)
*)

let check_for_numlib () =
  if caml_version_nums >= [4;6;0] then
    let numlib,_ = tryrun camlexec.find ["query";"num"] in
    match numlib with
    | ""  ->
       die "Num library not installed, required for OCaml 4.06 or later"
    | _   -> printf "You have the Num library installed. Good!\n"

let numlib =
  check_for_numlib ()
```

**Comment by Zimmi48** [comment]
> How complicated would it be to adapt the release scripts to make a 8.6.2?

It would be pretty easy. However, I'm rather against doing a new release because I think this would send a wrong message:
- That 8.6 is still supported: but that is not true, no fix has been backported to the v8.6 branch since the 8.6.1 release. Being serious about doing a 8.6.2 release would first require going through the long list of fixes that have been done since then, and backporting what can be. I'm not personally motivated by this prospect.
- That it is normal for our users to continue relying on 8.6.1. It is not. There was a real compatibility effort done between 8.6 and 8.7. The only users who can complain are plugin writers but library developers should have a good experience moving to 8.7. I've much more compassion for users being stuck at 8.4.

The 8.7.1 release is planned for next week and will bring OCaml 4.06 support. In the meantime, it is OK to just say that the tip of the v8.6 and v8.7 branches are compatible with OCaml 4.06 (once this PR is merged).

**Comment by herbelin** [comment]
> It would be pretty easy. However, I'm rather against doing a new release because I think this would send a wrong message:
> 
>    That 8.6 is still supported: but that is not true, no fix has been backported to the v8.6 branch since the 8.6.1 release. Being serious about doing a 8.6.2 release would first require going through the long list of fixes that have been done since then, and backporting what can be. I'm not personally motivated by this prospect.

@matafou proposed to call it "compiler-compatibility" release. Would the message be still wrong for you? I guess that it is standard to release minor releases of old branches to fix such critical-use weaknesses. 

>    That it is normal for our users to continue relying on 8.6.1. It is not. There was a real compatibility effort done between 8.6 and 8.7. The only users who can complain are plugin writers but library developers should have a good experience moving to 8.7. I've much more compassion for users being stuck at 8.4.

The 8.6 to 8.7 move is certainly one of the most compatible one we ever had but, as @beta-ziliani e.g. told recently on gitter, we are never protected from various problems liable to arrive for one reason or another. For instance, 8.7 has regressions. What if the needs of a user fall into one of this regression while s/he was satisfied with the weaknesses of 8.6? What is `coq_makefile` stops to work as s/he was expecting to? What if PG starts to behave differently? And so on.

Let's not fall in "forced comsumption". I find perfectly legitimate that we advertise the advantages of 8.7 and recommend a move. I don't find legitimate that we impose a move and pretend that everything wil be fully effortless, and even more when this happens in the stress of the days preceding an important automn school for which a Coq fully under control is crucial.

**Comment by ejgallego** [comment]
I do think that Théo point is valid thou, in this case the users are willing to stay on an old Coq version, but they move to a bleeding-edge OCaml which brings a change breaking hundreths of OCaml project?

Seems like a weak case IMHO.

IMVHO what @Zimmi48 points out is more important than it looks. Coq dev resources are very limited and users should understand that old versions have limited support. From 8.6 to 8.7 it is true that we lacked the deprecation mechanism of OCaml, so the move was a bit rocky, but since 8.7, even plugins writers should have a much better time.

> For instance, 8.7 has regressions. What if the needs of a user fall into one of this regression while s/he was satisfied with the weaknesses of 8.6? What is coq_makefile stops to work as s/he was expecting to? What if PG starts to behave differently? And so on.

Then the user is welcome to also use a supported OCaml version.

**Comment by herbelin** [comment]
> Coq dev resources are very limited and users should understand that old versions have limited support. 

Of course, but that's not what they demand. They just demand compatibility with OCaml 4.06.0.

> Then the user is welcome to also use a supported OCaml version.

This is a question to ask to Benedikt. But I can understand that he and the colleagues who will teach UniMath with him are used to 8.6 and don't want to take risks, that the school starts soon, that they ask users to install Coq 8.6, but that among these users, some like to live on the bleeding edge and maybe have OCaml 4.06.0, some maybe just don't know what OCaml exactly is and fell by chance on 4.06.0 without being really aware about it, and so on, and so on.

Shortly, many reasons are possible for them to prefer using Coq 8.6. Many reasons are possible for them for needing that it compiles with OCaml 4.06. Personally, I would be happy that this school works well and to make their life easier, whatever reasons they have.

But again, I'm just defending a general principle of "your mileage might vary". If you want to know their exact reasons and convince them to work differently, you should ask the organizers.

**Comment by herbelin** [comment]
> For the num library, why not use the test as it is in master?

Because I did not realize/remember that this was already done. Sorry. Now rebased to cherry-pick the commit checking for num.

**Comment by Matafou** [comment]
Maybe just replacing downloadable packages with the 4.06 compatible one? If this is the only change we can legitimately pretend that this is the same version.

**Comment by maximedenes** [comment]
> Maybe just replacing downloadable packages with the 4.06 compatible one? If this is the only change we can legitimately pretend that this is the same version.

No way! Shipping a different software with the same version number is a terrible practice, and defeats the purpose of version numbers.

**Comment by maximedenes** [comment]
I didn't follow the entire discussion, but could somebody remind us how a release will help the school? I thought UniMath was embedding Coq as a submodule, which has many other drawbacks, but with the benefit that they could just update the commit it points to, as soon as we merge the fix in the 8.6 branch.

What am I missing?

**Comment by Zimmi48** [comment]
I think the question of a new release is completely independent of the question of the UniMath winter school. @benediktahrens only asked that the tip of the v8.6 branch be compatible with OCaml 4.06 and this is what this PR is ensuring. No user explicitly asked that a 8.6.2 version be released (read the e-mail thread again if you're not sure).

**Review by Zimmi48 — APPROVED** [review]
Let's merge this. The update to Travis bleeding edge can come at a later time.

**Comment by benediktahrens** [comment]
Indeed, as @Zimmi48 says, a commit that ensures that 8.6 can be compiled with ocaml 4.06 is entirely sufficient - no release is required.

I am sorry for the hassle my request has caused. The discussion on coq-club had given me the impression that
- the Coq developers saw benefits in maintaining compatibility of older Coq branches (not necessarily releases) with newer ocaml versions independently of my specific use, and
- the change would be quite trivial.
It was not my intention to bind a lot of resources.

**Comment by Zimmi48** [comment]
@benediktahrens Indeed, don't worry about the hassle. The Coq Development Team tends to be subject to lots of internal debates ;-)

**Comment by Matafou** [comment]
Indeed all this is not very important. My only concern is: what happens when someone does `opam pin coq 8.6` with an opam having ocaml 4.06? Does it say "incompatible version of ocaml"? Does it fail in the middle of the compilation process? Does it propose to also pin ocaml down?

This is not really related to release/not release problem as opam can point to a git commit.

I don't use opam but I was bitten by the problem when preparing a small tutorial on coq recently.

**Comment by Zimmi48** [comment]
> Indeed all this is not very important. My only concern is: what happens when someone does opam pin coq 8.6 with an opam having ocaml 4.06? Does it say "incompatible version of ocaml"? Does it fail in the middle of the compilation process? Does it propose to also pin ocaml down?

It should say "incompatible version of ocaml" (at least since https://github.com/ocaml/opam-repository/commit/f293fd39c25b56ca0b5c3ac5ebe18c8259a322d2).

**Comment by herbelin** [comment]
By the way, for the 8.6.dev opam package to work properly with OCaml 4.06.0, coq/opam-coq-archive#240 should be merged (but I don't remember the protocol for committing to opam-coq-archive).

**Comment by benediktahrens** [comment]
Thanks a lot for providing this fix, and more generally for providing a great basis for UniMath!

**Pull request merged**
