### PR TITLE
[test-suite] Fix display of check.

### PR DESCRIPTION
**Pull request by ejgallego**
After #8655

### CODE REVIEW

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
We should either stick with "chk" to match coqchk, or fully expand to "check"

**Comment by ejgallego** [comment]
> We should either stick with "chk" to match coqchk, or fully expand to "check"

I do prefer to keep the alignment with `TEST` which is 4 chars, and seems way more pleasant aesthetically, what do others think?

[I'm fine with any 4-letter combination tho, or then just `CHECK` indeed]

**Comment by ejgallego** [comment]
> While you are at it, please also fix this discrepancy:

Sure, in which way tho? The basename there was added on purpose by @vbgl , I guess we'd like indeed to remove it right? [I do prefer full paths]

**Comment by vbgl** [comment]
I can’t remember why I put this `basename` there. Feel free to remove them. Thanks.

**Comment by gares** [comment]
```
TEST      failure/Case7.v 
CHECK     failure/Case7.vo
```

**Comment by gares** [comment]
Actually, I quite don't get why we write `TEST` now that we run `COQC`...

**Comment by SkySkimmer** [comment]
Rather I don't get why we write check

**Comment by gares** [comment]
because we are running coqchk to check the .vo

**Comment by gares** [comment]
Oh, I see, you want COQCHK... fine

**Comment by SkySkimmer** [comment]
That could be viewed as part of testing no?

Gaëtan Gilbert

**Comment by gares** [comment]
yes but we don't run it on all files... eg misc or coq-makefile stuff

**Comment by ejgallego** [comment]
For me the current status of this comestic PR is OK now, and fixes an annoying problem. If you want to change `TEST` to other stuff that's fine, but maybe it does belong to a different change.

**Review by gares — APPROVED** [review]

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
