### PR TITLE
[v8.0] Add support for `-h` and `--help` to configure

### PR DESCRIPTION
**Pull request by JasonGross**
d8b4083b2e865d6ab32e3aa33fa7eb50fa9c901f added a usage function without
adding support for calling it.

This will allow my scripts that configure multiple versions of Coq to
work more fluently.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>This will allow my scripts that configure multiple versions of Coq to
work more fluently.

Your scripts are not expected to work with the released versions?

**Comment by JasonGross** [comment]
No, this is just a script I use anytime I set up a new machine to install all the versions of Coq.  It installs released versions bank through 8.4 and also all the development branches.

**Comment by ppedrot** [comment]
Any assignee? Not sure if I'm the most indicated one for this.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
What milestone do I set?!

**Comment by Zimmi48** [comment]
@Alizter you don't set any, but also you can't merge to vX.X branches (coqbot won't support it anyway). The policy is that the RM merges to these branches (using the merge script), but for the unmaintained vX.X branches, any core dev can merge, including Jason himself.

**Pull request merged**
