### PR TITLE
Use a proper printing handler for a setoid rewrite error.

### PR DESCRIPTION
**Pull request by ppedrot**
We save a potentially costly evar info printing.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
No observable effect, but it can't hurt, so undrafting.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@ppedrot Can you rebase and make the CI green to be sure.

**Comment by ppedrot** [comment]
Unrelated CI failure happening in master as well.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
