### PR TITLE
[ocamlformat] Use doc-comments=before style.

### PR DESCRIPTION
**Pull request by ejgallego**
IMHO it is a bit more logical, WDYT?

### CODE REVIEW

**Comment by SkySkimmer** [comment]
It's the opposite of what we do in pretty much every mli though isn't it?

**Comment by SkySkimmer** [comment]
BTW when I messed with ocamlformat I ended up using the following config:
~~~
profile=conventional
cases-exp-indent=2
exp-grouping=preserve
indicate-multiline-delimiters=no
leading-nested-match-parens
let-and=sparse
~~~
It's fairly different from the one we have currently but I liked it better (I don't remember specifics as it's been a while)

**Comment by ejgallego** [comment]
> It's the opposite of what we do in pretty much every mli though isn't it?

I didn't count stats, but I'd say we have a mixed approach, for example `kernel/constr.ml` follows a before style.

**Comment by ejgallego** [comment]
> It's fairly different from the one we have currently but I liked it better (I don't remember specifics as it's been a while)

Indeed it is a bit different; I dunno. At first I liked the style you propose more; then I got used to the `ocamlformat` style in some other projects and now I prefer it. Hard question, style... for example people expressed the preference to keep `begin/end` where used.

Maybe we can for now at least agree on the comments?

**Comment by SkySkimmer** [comment]
>Maybe we can for now at least agree on the comments?

I don't really care about the comments tbh

**Review by Zimmi48 — APPROVED** [review]
I prefer that comments come before but I would like this change to be discussed in the call before being merged before I would like to avoid some back and forth between the two options.

**Comment by Zimmi48** [comment]
It seems to me that if this is merged this should be backported to avoid creating any conflict when backporting fixes to micromega.

**Comment by Zimmi48** [comment]
Please rebase and I'll  merge.

**Comment by ejgallego** [comment]
Done thanks!

**Comment by ppedrot** [comment]
I don't think that this PR is backportable to 8.11, is it?

**Comment by Zimmi48** [comment]
Yeah, probably not.

**Pull request merged**
