### PR TITLE
[ci] Test branches for v8.8.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

Update the branches we are testing for `v8.8`.

@gares Elpi's `coq-master` branch is currently incompatible with 8.8. Can you create a new `coq-v8.8` branch?
@ybertot Could you create a new `coq-v8.8` branch for coq-dpdgraph?
@ppedrot Could you create a new `v8.8` branch for Ltac2?
@mattam82 @cmangin Right now the branch we are testing on master is `coq-8.8+alpha`. Do you wish to create a new `coq-8.9+alpha` branch or should the `master` branch be tracked on Coq's master?

### CODE REVIEW

**Comment by Zimmi48** [comment]
@ppedrot Actually, Ltac2 `master` probably doesn't compile with Coq `v8.8` right now either. The new `v8.8` branch should probably point to ppedrot/ltac2@49736b7a1acc23cda6c869645f4a8755ca1b8b65.

Note that this is pretty urgent as we need CI to run to be able to backport.

**Comment by ppedrot** [comment]
@Zimmi48 Done.

**Comment by Zimmi48** [comment]
Thanks! @gares?

**Comment by gares** [comment]
https://github.com/LPCIC/coq-elpi/tree/coq-v8.8

**Comment by Zimmi48** [comment]
You mean different from the `coq-trunk` branch?

**Comment by ybertot** [comment]
Śorry, I was thinking of preparing an opam package, but maybe that is not what we are talking about here.

**Comment by Zimmi48** [comment]
Indeed, we don't use opam in Coq main CI. The only thing that I'm asking here is to have a branch in coq-dpdgraph that can be tracked in Coq's `v8.8` branch. (It could be a tag as well.) The goal is to be able to merge breaking changes in coq-dpdgraph's `coq-trunk` without compromising the CI testing of Coq's `v8.8` branch.

**Comment by mattam82** [comment]
Equations/master it is for Coq's master now.

**Comment by ybertot** [comment]
There is now a coq-v8.8 branch on Karmaki/coq-dpdgraph
There is also a coq-trunk branch that should track the modifications to 
coq master

**Comment by Zimmi48** [comment]
Thanks!

**Pull request merged**
