### PR TITLE
[coqchk] support for -boot flag

### PR DESCRIPTION
**Pull request by Alizter**
We support the -boot flag in coqchk which stops the stdlib from being required.

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
I think COQPATH needs to be respected even when boot is set?

What does the documentation of COQPATH say?

**Comment by ejgallego** [comment]
I checked and indeed when we pass `-boot` we don't respect COQPATH; I guess it actually makes sense, but Dune will have to parse it to build the cmdline flag.

**Comment by ejgallego** [comment]
@coqbot run ci

**Review by ejgallego — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot run full CI

**Pull request merged**
