### PR TITLE
[default.nix] Add dependencies of the merging script.

### PR DESCRIPTION
**Pull request by Zimmi48**
This may be useful for new code owners who now need to use the merging script.

### CODE REVIEW

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
VST failure is unrelated (time out).

**Comment by Zimmi48** [comment]
Yes, VST is broken (cf. https://github.com/coq/coq/pull/7023#issuecomment-375084707). I'll report it tomorrow.

**Comment by ejgallego** [comment]
I'm investigating VST, but indeed it seems that a file takes more than 20 minutes to compile, I'll see what's going one. The file is `veric/rmaps.v`.

I'll wait first to see if the file ever finishes compilation, then I'll try with 8.7.

**Comment by vbgl** [comment]
I’ve run the merge script… which failed:

```
+ git merge -S --no-ff FETCH_HEAD -m 'Merge PR #7030: [default.nix] Add dependencies of the merging script.' -e
hint: Waiting for your editor to close the file... fatal: cannot run vi: No such file or directory
error: unable to start editor 'vi'
Not committing merge; use 'git commit' to complete the merge.
```

So probably some dependency is not properly declared…

I’ve run `git commit -m '…'` to complete the merge commit, but I’ve no clue what to do after…

**Comment by vbgl** [comment]
I do not have the (technical) right to merge this, sorry:

> remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
To github.com:coq/coq.git
 ! [remote rejected]     master -> master (protected branch hook declined)

**Comment by Zimmi48** [comment]
I will look into this tomorrow.

**Comment by Zimmi48** [comment]
So in fact I looked into it right away. I thought I had given the push rights on master to the pushers team but I had apparently forgotten to save. Should be OK now. And about the error message, it is not normal. Isn't it that your `$EDITOR` environment variable is set to `vi` but you don't have it in path? In my case (when I use the merging script), it opens `nano`. However, I didn't try with @gares' latest iteration of the merging script. If this is what you did, it may be a bug in there.

**Comment by vbgl** [comment]
This PR is about declaring proper dependencies of the merge script. You mention that I should have nano or vi in my path, but this is nowhere declared.

Other missing dependency: trust certificates; otherwise curl will (silently) fail…

I do not think any of these deserves more fixing, though.

**Comment by Zimmi48** [comment]
So as I understand it, you have no editor in your PATH. That's a strange situation which I hadn't imagined. (If you have one and `$EDITOR` is properly set, you shouldn't see this failure.) But in any case, I don't understand why the merge script passes the `-e` option to `git merge`. @maximedenes?

**Pull request merged**
