### PR TITLE
Update of Coq version history

### PR DESCRIPTION
**Pull request by herbelin**
This is a quick update of the history of Coq versions. I made a selection of hightlights. Don't hesitate to comment/propose.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@herbelin Do you think it would make sense to turn this document into a Markdown file? It is not compiled as part of anything and it would be easier to view online and offline without compilation if it was in Markdown. It isn't either using any LaTeX-specific features (e.g. GitHub Markdown supports tables).

To get this:

| header 1  | header 2  |
|-----------|-----------|
| content 1 | content 2 |
|           | content 3 |

The code is this:
```
| header 1  | header 2  |
|-----------|-----------|
| content 1 | content 2 |
|           | content 3 |
```

which I find quite readable even without compilation, as long as one uses a Monospace font.

**Comment by MSoegtropIMC** [comment]
Dear Hugo,

do you think it makes sense to also publish a diff of the reference manual as attached? I find this quite useful and I don't think everybody has tools to create such a diff of PDFs (I did this with Beyond Compare with some rules to exclude headers and the like). Of cause, possibly it would make more sense to create the diff from the sources, but this way it is easy to find things if one is familiar with the reference manual in its pdf form.

[ManualDiff-87-86.zip](https://github.com/coq/coq/files/1418589/ManualDiff-87-86.zip)

Best regards,

Michael

**Comment by herbelin** [comment]
Dear Michael,

> do you think it makes sense to also publish a diff of the reference manual as attached?

This looks indeed like a very good idea for users upgrading from a version to another. If you have already a tool, you may probably share it. To get a diff automatically from sources, I must confess that I did not investigate how to do it, but I've seen many people being able to do that with their papers in LaTeX, so this would certainly be possible. I would then turn towards @maximedenes or @Zimmi48 or @ejgallego (or others) for their help.

Another question is that there is an ongoing move/experiment towards relying on a sphinx source of the reference manual. I don't know how a diff could then be obtained automatically (but maybe there are already tools for that).

In the short term, unless someone has a better idea, maybe could we just take benefit of your diff and link it from the web page. I don't know what others involved in the release process think?

Best,

Hugo

**Comment by herbelin** [comment]
@Zimmi48 

> Do you think it would make sense to turn this document into a Markdown file? It is not compiled as part of anything and it would be easier to view online and offline without compilation if it was in Markdown.

Indeed, it is not compiled as part of anything, and markdown is common these days and automatically rendered online. No objection at all to that.

**Comment by maximedenes** [comment]
Let's merge this and turn it into Markdown later if we want to.

**Comment by Zimmi48** [comment]
Indeed. It would be cool opening an issue listing all the files we would like to convert to Markdown and add the "help wanted" flag to it.

**Comment by MSoegtropIMC** [comment]
Dear Hugo,

regarding my question on the manual diff: sorry for coming back so late - I got a bit lost in the number of emails I got since the move to GitHub and just managed to organize it today and then so your answer.

The tool I use is a commercial tool (beyond compare 3). For the time being I could provide a diff of each patch/minor version and also a diff between all major versions (say 8.7 vs. 8.6 vs 8.5).

I can see if I can hook something up with Linux pdf tools, diff and xslt to get a similar result.

Best regards,

Michael

**Comment by Zimmi48** [comment]
I would try something based on `git diff`, e.g.:

    git diff V8.6 V8.7.0 doc/refman/RefMan-pre.tex

Note that this is already quite readable as is, but that could be different for other sections.

**Comment by MSoegtropIMC** [comment]
Dear Théo,

yes, doing it on the sources is definitely an option, but the output could be more readable. I will try a few things ...

Best regards,

Michael

**Pull request merged**
