### PR TITLE
Backport #10252

### PR DESCRIPTION
**Pull request by ppedrot**
This is a backport of #10252.

### CODE REVIEW

**Comment by ppedrot** [comment]
Why is dpdgraph failing with an OCaml error? I didn't touch the API in this PR.

**Comment by Zimmi48** [comment]
I think I have seen it failing on v8.9 already.

**Comment by Zimmi48** [comment]
I meant v8.10.

**Comment by ppedrot** [comment]
@vbgl the corresponding PR has been merged into master, I think you should assign this one.

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
Merged as 5eabd30767742e178ba78cca95a3294d035b1d22

**Pull request closed without merging**
