### PR TITLE
[release] Bump magic numbers after 8.12.0 tag

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by Zimmi48 — CHANGES_REQUESTED** [review]
We usually do not bump magic numbers between patch-level releases. This is what is written in the release checklist, but the previous RM @ppedrot can probably confirm as well.

**Comment by ejgallego** [comment]
Umm, OK, I'm gonna close, but I am not sure we should allow the same numbers in patch-level releases.

**Comment by ejgallego** [comment]
Well, at least `coq_version` seems worth bumping, right?

**Comment by Zimmi48** [comment]
I'm not saying that this is not worth doing, just that this wasn't done until now. I'd be happy to have this discussed (both the intermediate version question and the magic number question). In particular, your suggestion for the version number seems fine. Just note that I won't personally be able to attend the Coq Call on next Wednesday.

**Pull request closed without merging**
