### PR TITLE
Additional rewrite lemmas on Ensembles, in Powerset_facts

### PR DESCRIPTION
**Pull request by nomeata**
I found that I was missing these, and upon ranting about the standard library,
I was told to not rant but rather contribute. So here is my first attempt at
contributing to the Coq standard library...

### CODE REVIEW

**Comment by ppedrot** [comment]
For the record, I thought that the `Ensembles` library was unofficially deprecated. I remember discussing about it with some other devs at some point, but I can't remember the exact details. Anybody around with a better memory?

**Comment by mattam82** [comment]
I remember some wanted it deprecated too but I think if we get pull-requests we should revisit this, what we’re the arguments to deprecate it? The PR looks fine to me, just addition of pretty obviously useful lemmas.

**Comment by mattam82** [comment]
Maybe the deprecation argument was that this all relies on an extensionality axiom for equality of sets? It’s basically funext IIUC. I think this is the easiest representation of infinite sets though.

**Comment by gares** [comment]
> deprecation argument was that this all relies on an extensionality axiom for equality

Yes, that was the main argument, if I recall correctly.

In any case I think accepting the PR is orthogonal to the (eventual) decision to put this part of the standard library into an OPAM pakage and move its sources in a separate github repo.

**Comment by maximedenes** [comment]
So who can review that?

**Comment by herbelin** [comment]
Same opinion as @mattam82. To me, this looks nice and consistent with the rest of the file (and actually even with improved style).

Maybe a minor remark, we generally tend to use the bullets in the order `-, `+`, `*`, but this is not redhibitory to me.

In any case, I'm in favor of merging it.

**Comment by maximedenes** [comment]
@herbelin so do you approve the PR?

**Comment by herbelin** [comment]
@herbelin so do you approve the PR?

Yes, as far as I'm concerned, I approve it.

**Comment by maximedenes** [comment]
Thanks for contributing!

**Pull request merged**
