### PR TITLE
Suppress warning: undefined variable 'DESTDIR'

### PR DESCRIPTION
**Pull request by JasonGross**
I did not notice this when reviewing #14258

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
This looks like a straightforward fix. Will merge tomorrow.

**Comment by ejgallego** [comment]
This is due to the order of includes, shouldn't we just move `DESTDIR` from `Makefile.install` to `Makefile.build` instead? Another choice is just to swap the include order.

**Comment by Zimmi48** [comment]
OK, I won't merge tomorrow then. If you have a better fix in mind, maybe just open a PR with it @ejgallego (and @JasonGross can assign).

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/14341

**Comment by ejgallego** [comment]
Replaced by #14341

**Pull request closed without merging**
