### PR TITLE
Do not rely on the contents of the Monomorphic constructor for side-effects

### PR DESCRIPTION
**Pull request by ppedrot**
This is a minor cleanup on the way to the removal of the field of the `Monomorphic` constructor. It is small and self-contained, so it doesn't hurt to submit it as-is.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
Sure why not

**Comment by SkySkimmer** [comment]
>Why not

I think we can do better by handling universes_of_private completely outside the kernel, see #11533

**Comment by ppedrot** [comment]
Superseded by #11533.

**Comment by ppedrot** [comment]
*Un partout, la balle au centre*. @SkySkimmer it's your turn to play.

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
This PR title is incorrect as side effects still rely on Monomorphic, which is why the alternative PR was incorrect.

**Comment by ppedrot** [comment]
They don't rely anymore on the constructor though, so the title does seem correct to me.

**Comment by SkySkimmer** [comment]
Is this not relying on the contents of Monomorphic for side effects?
https://github.com/coq/coq/blob/633d9829d4e3678583c9e1ad161253fb53be1290/kernel/safe_typing.ml#L631

**Comment by ppedrot** [comment]
Indeed, this needs to be fixed.

**Comment by ppedrot** [comment]
Should be fine now.

**Comment by SkySkimmer** [comment]
What about https://github.com/coq/coq/blob/5c2737297219e40555f66759e1eb12e27db17705/kernel/safe_typing.ml#L708 (constant_entry_of_side_effect) and https://github.com/coq/coq/blob/5c2737297219e40555f66759e1eb12e27db17705/kernel/safe_typing.ml#L769 (export_side_effects)?

**Comment by ppedrot** [comment]
This will go away when removing the Monomorphic field whatsoever...

**Comment by SkySkimmer** [comment]
I guess I'm just not convinced that this is an improvement, considering it just duplicates the information.
That also applies to #11528 but since that was about template I didn't notice it as much.

Maybe it's better to just include those commits with whatever relies on them.

**Comment by ppedrot** [comment]
I prefer having split PRs so that their individual intent is clearer. Here we're tweaking the side-effect part, getting rid of the field will touch other unrelated pars of the code.

**Comment by ppedrot** [comment]
Fine, I'll add this patch in the mono-cleaning PR.

**Pull request closed without merging**
