### PR TITLE
Adapting base_include to 91df40272 (body_of_constant_body moved to Global).

### PR DESCRIPTION
**Pull request by herbelin**
A trivial fix after #870 (to be pushed w/o delay).

### CODE REVIEW

**Comment by Zimmi48** [comment]
That's a bit annoying that such bugs are missed by the test-suite. There is in the test-suite a test for `#use "include";;` but none for `#use "base_include";;`. Moreover, for some reason the test for `#use "include";;` is not very robust. (Recently it was failing on my machine but succeeding on Travis.) Could we imagine a more robust test for `#use "include";;` and `#use "base_include";;` based on some OCaml file building fine rather than a `grep`?

**Comment by herbelin** [comment]
@zimmi48: Yes, certainly. One of the problem is that when calling `#use`, if it fails, it does not exit the OCaml loop. We would need some return exit code, but I don't know of such thing in the OCaml loop. So, I'm stumped. Maybe playing with `ocamlc` instead?

**Comment by Zimmi48** [comment]
Indeed, I was thinking about `ocamlc`. However, it may not be possible because IIUC `#` directives are for the toplevel specifically and `ocamlc` doesn't know what to do with them...

**Comment by mattam82** [comment]
+1 for merging anyway

**Pull request merged**
