### PR TITLE
Add Ltac2.String.sub.

### PR DESCRIPTION
**Pull request by rlepigre**

### CODE REVIEW

**Comment by rlepigre** [comment]
@SkySkimmer this is a trivial addition, is it worth getting that in before the 8.20 branch is cut?

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
IMO it's generally a bad idea to care about branching timings, we should merge stuff when it's ready and not later (or sooner)

**Comment by rlepigre** [comment]
> IMO it's generally a bad idea to care about branching timings, we should merge stuff when it's ready and not later (or sooner)

Agreed, the only reason I asked is because I thought this MR would be immediately considered ready given its triviality.

**Comment by SkySkimmer** [comment]
CI failures look unrelated
@coqbot merge now

**Pull request merged**
