### PR TITLE
use Int.equal instead of polymorphic = 

### PR DESCRIPTION
**Pull request by psteckler**
Trivial code change; this code is called a lot.

### CODE REVIEW

**Comment by ppedrot** [comment]
I think this patch has no effect, as the compiler is clever enough in that case to deduce from typing that this is integer comparison.

**Comment by psteckler** [comment]
I ran experiments with tight loops using the different operations, and the specialized version was consistently a bit faster. I'd have to look at the assembly output to know for sure, though.

**Comment by maximedenes** [comment]
Since the change cannot hurt (can it?), we could make it even without measuring again. WDYT?

**Comment by ppedrot** [comment]
No, I'm not complaining against the merge actually. This was merely a remark on the expected effects. In practice, I'd like to see all uses of polymorphic equality to be eradicated, so this goes in the right direction!

@psteckler That's a bit strange, I never saw polymorphic equality appear at this place in the code during the performance profiles I did.

**Comment by psteckler** [comment]
@ppedrot The equality call didn't show up in profiles. It's just something I noticed when I eyeballed the hashconsing code, which did show up in profiles.

**Comment by psteckler** [comment]
In a tight loop, the magnitude of the effect is small, about 1/10 sec out of 3 sec, around 3%.

**Comment by ppedrot** [comment]
@psteckler Which version of OCaml are you using? With 4.04.0+fp, the generated assembly is the same...

**Comment by psteckler** [comment]
Also using 4.0.4+fp here.

Int.equal calls `external %eq`, and I think `==` calls the same (as distinguished from `=`).

**Comment by psteckler** [comment]
OK, I just tried reversing the order of the loops. The second one is almost always faster, so the difference is due to some loading/cache effect.

So @ppedrot is right, the change looks to be a no-op.

**Pull request merged**
