### PR TITLE
Windows 8.12: picks for various plugins

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This PR adjusts the version and Windows build steps for
- menhir
- coq-menhirlib
- compcert (also enable using platform supplied Flocq and MenhirLib)
- VST (also enable using platform supplied Flocq and CompCert)
- Gappa tool
- Flocq (just version adjusted, build fix taken from rebase)
Please note that gappa plugin does not work yet. I would add gappa tool anyway because this makes it easier to fix and test gappa.

### CODE REVIEW

**Comment by Zimmi48** [comment]
FTR, my intent regarding the merging process is, as much as possible, to merge fixes in `master` to follow the normal backporting process (even if testing them in priority on `v8.12` is the right thing to do). For instance, this PR looks just fine for `master` as well, so once tests have (successfully) completed on `v8.12`, it should be retargeted to `master`.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : indeed - everything which does not build in master should be fixed there as well. I will take care to do the final rebasing / squashing such that the changes in the make files are separated from version picking in the overlay file.

**Comment by Zimmi48** [comment]
In the case of menhir, since it is only used for the Windows add-ons (and not in the CI), it would even be reasonable to leave the picking in the `master` branch (at least it documents what was the last version known to work with the current configuration).

**Comment by Zimmi48** [comment]
Since the build of this PR was successful, we could already proceed to retarget this PR to `master` and merge it. (Unless you want to do further manual testing before.)

**Comment by MSoegtropIMC** [comment]
Give me a short while - I am testing the installer ...

**Comment by MSoegtropIMC** [comment]
I would prefer to merge this together with the change you have in overlay to switch from menhirlib to menhir. I did some adjumstments to my shell functions so that I can build two modules from the CI overlay seetings (menhir and the menhir coq library). Of cause one could also discuss to merge these into one package. What do you think? Keep this separate as it was or merge it?

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : here you can see how I would like to do it:
(https://github.com/coq/coq/pull/12476/commits/0d33f0c62bd683e97bb06a04ed3cdeb79ae9d56e)
But this only works with your menhir related changes from the overlays file.

**Comment by Zimmi48** [comment]
>the change you have in overlay to switch from menhirlib to menhir

Huh? I was planning to drop these changes since they were becoming redundant with yours.

>But this only works with your menhir related changes from the overlays file.

You may just reproduce these changes in your PR. WDYT?

>Keep this separate as it was or merge it?

I'm not sure what is the use case for installing menhir without menhirlib, so I would say merge, but I may not be the best person to answer this.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : CompCert CI is running in #12476 - it did work locally.

This requires a working Flocq since this variant uses the platform supplied Flocq rather than the bundled Flocq. This is essential for being able to verify numerical code because otherwise tools like CoqInterval or Gappa are not compatible with CompCert - they would prove thinsg about a different instance of Flocq.
When I am finished with this based on your branch, I will merge it back to this PR including the things from your branch this relies on.
The MenhirLib stuff was a bit tricky - I hope VST is easier.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : this would be my picking. Gappa plugin unfortunately does not work (Error is "Unbound module Vernacstate.Proof_global" I should translate it to Ltac2).

This are just cherry picks from #12476 which went through CI (Windows was still running, but it was in the upload phase, which takes a while when CompCert is in - something I should change one day - I don't think many people can make use of the .vo files of the lower layers of CompCert).

For Flocq I changed the version to what you had in #12415. I rebeased before I cherry picked, so the Flocq build fix is in.

**Comment by Zimmi48** [comment]
Thanks! Regarding the Gappa plugin, it is not really surprising that it is not compatible given that it is not in CI and that many changes go in at each release.

**Comment by Zimmi48** [comment]
@MSoegtropIMC I have a patch ready for Gappa but I need your help to prepare the appropriate `.patch` file. `dev/build/windows/difftar-folder.sh` is impossible to understand alone.

**Comment by Zimmi48** [comment]
See my message in #12415.

**Pull request closed without merging**
