### PR TITLE
-time: include parsing time

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Looks like parsing is fine

**Comment by ejgallego** [comment]
> Looks like parsing is fast, it doesn't show up in the perline diff AFAICT

Parsing seems indeed mostly pretty fast, most of the time is often spent in the state restoring functions I think.

I'm sure there are corner cases tho, soon I'll have some more better stats. But for example Pfff.v is measured as spending in parsing 2.2 seconds in total for 20707 sentences.

**Comment by SkySkimmer** [comment]
yes

**Review by ppedrot — APPROVED** [review]
OK.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
Ah, the ruleset bug is still occurring. I guess I'll wait for somebody to fix it before being able to merge.

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
Does this change the format of the output of `-time`?  Or change anything other than the numbers?  If so, I suspect this is the PR that broke coq-tools, cf


> According to https://gitlab.com/coq/coq/-/pipelines?page=1&scope=all&ref=master, it worked on 9bbe89ac but failed on a3bf5ca4 so it's either #17443 or #17504.

_Originally posted by @ppedrot in https://github.com/coq/coq/issues/17526#issuecomment-1523677823_

**Comment by SkySkimmer** [comment]
It shouldn't change the format, and the numbers should change only a little

**Comment by JasonGross** [comment]
Are you sure that it doesn't change the ordering of the timing info with respect to other things printed?  Or change whether or not some lines get timing info at all?  coq-tools is very sensitive to the format of `coqtop -emacs -time`, especially with regard to the ordering of `<prompt>`, `foo is defined`, and the timing info messages.  (Changing the numbers should not matter.)

**Comment by JasonGross** [comment]
It looks like, at the very least, the timing info is now printed in the wrong place when errors are raised, because `ignore(Stm.edit_at ~doc:state.doc state.sid);` used to happen after the timing info was printed but now happens before.  I'm not sure if this is what breaks coq-tools, or whether it's something else

**Comment by SkySkimmer** [comment]
Also edit_at is only when interactive, doesn't coq-tools use coqc?

**Comment by JasonGross** [comment]
coq-tools uses `coqtop -emacs -time` to parse the document, and uses `coqc` after that.  The errors look like the sort of errors I'd expect if the bug minimizer is failing to split the document into sentences.

Is there some other part of the code responsible for printing `<prompt>` in `-emacs` mode on every state id change that isn't edit_at?

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/17535

**Pull request merged**
