### PR TITLE
Eagerly reduce rigid / flex conversion problems

### PR DESCRIPTION
**Pull request by ppedrot**
bench https://gitlab.com/coq/coq/-/jobs/809145859

### CODE REVIEW

**Comment by ppedrot** [comment]
The test-suite failure is real. It is caused by some tricky conversion problem on primitive types, here is a small reproucible example that fails on this PR.
```
Require Import Floats.

Definition toZ (i : Int63.int) : unit :=
  if Int63.is_even i then tt else tt.

Definition Prim2SF :=
 let (r, exp) := frshiftexp one in
 match toZ (normfr_mantissa r) with
 | tt => tt
 end.

Definition TT := tt.

Check (eq_refl : TT = Prim2SF).
```

I suspect that there is some fishy thing going on with primitive functions and that this PR uncovered a bug somewhere else in the kernel.

Side remark: it'd be nice if the primitive-defining files were stripped down to their bare minimal, in particular not relying the whole of ZArith and the like when I just want my float / int63 types...

**Comment by ppedrot** [comment]
Aha, @maximedenes, since when primitive values are "normal"?
```
  | FFlex(ConstKey (kn,_u as c)) when red_set info.i_flags (fCONST kn) ->
      (match ref_value_cache info tab (ConstKey c) with
        | Def v -> kni info tab v stk
        | Primitive op when check_native_args op stk ->
          let rargs, a, nargs, stk = get_native_args1 op c stk in
          kni info tab a (Zprimitive(op,c,rargs,nargs)::stk)
        | Undef _ | OpaqueDef _ | Primitive _ -> (set_norm m; (m,stk))) (** <- look at me, nice little bug hiding in there *)
```
The terminology is indeed confusing because CClosure.Norm actually corresponds to what is generally called *neutral* terms, i.e. terms s.t. they never trigger a reduction when they replace a variable in another term. Primitive values are not neutral, they are *normal* in the usual sense, i.e. CClosure.Cstr. Still, this is a clear bug.

**Comment by maximedenes** [comment]
> Aha, @maximedenes, since when primitive values are "normal"?

@ppedrot good catch, I'm on vacations but I trust your fix. As you write, the bug is the name IMHO. Primitive values are in normal form.

**Comment by ppedrot** [comment]
Rerunning a bench on https://gitlab.com/coq/coq/-/jobs/824899982.

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  223.52  225.80 -1.01 % │      621626012906      628022606006 -1.02 % │      936043568118      955070915161 -1.99 % │     668388     675512  -1.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 3929.97 3964.91 -0.88 % │    10934935095641    11032667350906 -0.89 % │    20652005351260    21019211215789 -1.75 % │    1129328    1120844  +0.76 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   47.43   47.64 -0.44 % │      131544401064      131843498173 -0.23 % │      180177533859      181146980673 -0.54 % │     480168     479872  +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  511.20  513.38 -0.42 % │     1429402059061     1432449378760 -0.21 % │     1793387758756     1796766097817 -0.19 % │    1133128    1076188  +5.29 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  155.47  156.04 -0.37 % │      432279634946      433748704153 -0.34 % │      595417359916      600644122893 -0.87 % │     709312     708568  +0.11 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1227.90 1231.80 -0.32 % │     3418213659872     3429995757158 -0.34 % │     4821847438485     4859404051533 -0.77 % │     902048     901628  +0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  170.33  170.82 -0.29 % │      473539011536      475170412886 -0.34 % │      664860172738      669232988377 -0.65 % │     683860     678844  +0.74 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   60.13   60.23 -0.17 % │      166385819269      166670197969 -0.17 % │      206680854558      206787657904 -0.05 % │     524720     524808  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   49.97   50.05 -0.16 % │      137032916749      137066553411 -0.02 % │      173587610034      173924748310 -0.19 % │     514212     512468  +0.34 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  156.80  156.99 -0.12 % │      435213218209      435815325118 -0.14 % │      540586457369      541760050675 -0.22 % │     821708     822148  -0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  642.44  642.96 -0.08 % │     1790743747631     1791185540341 -0.02 % │     2466914808959     2469364554584 -0.10 % │    1047056    1046984  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  101.80  101.87 -0.07 % │      291273696779      291513362840 -0.08 % │      386188253814      386092410038 +0.02 % │     479528     479792  -0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2548.40 2549.54 -0.04 % │     7105491201147     7107740866196 -0.03 % │    11781293084954    11790039108300 -0.07 % │     765484     764936  +0.07 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  140.26  140.30 -0.03 % │      389388235259      390165037199 -0.20 % │      497526783148      499270617113 -0.35 % │     545328     543256  +0.38 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1050.75 1050.62 +0.01 % │     2926069243218     2925699630914 +0.01 % │     4622597464644     4657062496506 -0.74 % │     975800     975952  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1445.78 1444.18 +0.11 % │     4028183387547     4029276831936 -0.03 % │     6085794038220     6109509657412 -0.39 % │    1028312    1024264  +0.40 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1239.52 1237.26 +0.18 % │     3451396802385     3442369296616 +0.26 % │     4916179085272     4924953047610 -0.18 % │    1097316    1118432  -1.89 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 5051.72 5039.82 +0.24 % │    14037346144383    14004230753310 +0.24 % │    24141236819996    24168000333487 -0.11 % │    2281948    2271444  +0.46 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  102.54  102.29 +0.24 % │      282484101993      282463835060 +0.01 % │      395549275243      396543263157 -0.25 % │     547904     546900  +0.18 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  323.19  322.03 +0.36 % │      878294307647      872724829730 +0.64 % │     1421050792681     1420361438289 +0.05 % │     678928     735596  -7.70 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   56.97   56.76 +0.37 % │      157506095844      156657715308 +0.54 % │      210551630668      210688821767 -0.07 % │     469672     466572  +0.66 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  519.71  517.64 +0.40 % │     1455430198576     1450216115398 +0.36 % │     1945998217342     1946575576304 -0.03 % │     578416     562316  +2.86 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  711.68  708.80 +0.41 % │     1976596003018     1969702294311 +0.35 % │     3007158000072     3008952920545 -0.06 % │     976104     981716  -0.57 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   80.09   79.70 +0.49 % │      219126969794      218760886151 +0.17 % │      305820560894      306972586598 -0.38 % │     763016     763332  -0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  635.16  632.01 +0.50 % │     1776461948893     1768588894632 +0.45 % │     2667172288822     2665309063580 +0.07 % │    3651100    3250772 +12.31 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  212.57  211.44 +0.53 % │      592921984938      589829187609 +0.52 % │      810096842490      809889178229 +0.03 % │     507108     507532  -0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  367.17  364.94 +0.61 % │     1032706492804     1025724899817 +0.68 % │     1741818377390     1742188790597 -0.02 % │    3986772    3506508 +13.70 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1633.37 1623.09 +0.63 % │     4544513473163     4515891179801 +0.63 % │     6923744402948     6935160307573 -0.16 % │     839992     820084  +2.43 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  785.02  780.07 +0.63 % │     2184793247460     2172175418296 +0.58 % │     3374681455045     3377792009053 -0.09 % │     979320     980636  -0.13 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  223.49  221.93 +0.70 % │      618344775869      614568203978 +0.61 % │     1018967526438     1019762873484 -0.08 % │    1086876    1086916  -0.00 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```
Compared to the first bench this one is essentially within noise threshold. I do believe that unimath is slightly faster although it's not really observable in this run. The other bench showed a 2% speedup, so with ~1% noise threshold there could be a non-trivial, albeit small, effect.

I think nonetheless that the code is clearer that way, and prone to further enhancements, so I'd still advocate for a merge despite the meager results.

**Review by SkySkimmer — APPROVED** [review]
In principle this could be slower on some cases (when both sides can be unfolded we throw away the result of unfolding the oracle loser) but the bench says it works out, and I agree the code is clearer.

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
