### PR TITLE
[build] Build Coq without linkall

### PR DESCRIPTION
**Pull request by ejgallego**
This PR is a draft to request for more comments, likely far from final
form yet.

See issue #9547

This is also related to PR #10951 and #7698

We seem to save half to one megabyte in the binaries:

```
-rwxr-xr-x 1 egallego egallego 31651662 janv. 31 00:05 coqc_bin.bc
-rwxr-xr-x 1 egallego egallego 32467231 janv. 31 00:08 coqc_bin.bc

-rwxr-xr-x 1 egallego egallego 23781840 janv. 31 00:05 coqc_bin.exe
-rwxr-xr-x 1 egallego egallego 24395352 janv. 31 00:08 coqc_bin.exe

-rwxr-xr-x 1 egallego egallego 23751520 janv. 31 00:05 coqtop_bin.exe
-rwxr-xr-x 1 egallego egallego 24395608 janv. 31 00:08 coqtop_bin.exe

-rwxr-xr-x 1 egallego egallego 41996191 janv. 31 00:05 coqtop_byte_bin.bc
-rwxr-xr-x 1 egallego egallego 43020328 janv. 31 00:08 coqtop_byte_bin.bc
```

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
This is surreptitiously introducing #10951 as a *cavalier législatif*, without even mentioning it. All commentators were against this PR, can't you fix the `-linkall` problem without relying on this code move?

**Comment by ppedrot** [comment]
@ejgallego do you have a high-level explanation for the need of linkall?

**Comment by ejgallego** [comment]
> This is surreptitiously introducing #10951 as a _cavalier législatif_, without even mentioning it.

It is mentioned in the commit message; and in fact it is mandatory to do this with this approach as these modules are not used by Coq itself, only by the plugin; other solution [which I don't discard] is to improve the linker; indeed I didn't expand a lot on that as I mentioned this PR is not likely in anything closer to the final form.

> @ejgallego do you have a high-level explanation for the need of linkall?

As of today `-linkall` is needed only to link the grammar files, and the few modules in tactics that are left hanging around in the binary as they are unreferenced but later on used in the plugin.

I submitted the PR mainly to inform others of the current situation of modules that are not referenced but used; I am also working in improving the dynamic linker [so we can properly link plugins with 3rd party libs] , so consider this a work in progress; it is likely we want to do non-trivial modifications to the plugin init/linking setup.

**Comment by ppedrot** [comment]
Hum, pardon me, but *related to PR XXXX* does not mean the same as *including PR XXXX* to me...

**Comment by ejgallego** [comment]
> Hum, pardon me, but _related to PR XXXX_ does not mean the same as _including PR XXXX_ to me...

Actually the set of files moved here is different from the ones in that PR, indeed sorry for the imprecision; I didn't expand a lot in this draft PR as for example it is not clear that the final solution should indeed include the ltac module move.

**Pull request closed without merging**
