### PR TITLE
Precompute unicode tables to reduce exe size

### PR DESCRIPTION
**Pull request by SkySkimmer**
On my machine this reduces coqc_bin.exe size by about 1.6MB (from 30.6MB, ie 5%)

Not sure if worth it.

TODO test with release build

### CODE REVIEW

**Comment by ppedrot** [comment]
I think that the segment tree representation is a bit wasteful on disk, could you try keeping the representation of the first commit for the `to_lower` table? Also turning the polymorphic variants into a proper ADT will definitely help.

**Comment by SkySkimmer** [comment]
I wonder if it would make sense to use `Bytes.t` for the table instead of `int array`, at 2 code points / byte.
In 32 bit mode it should be as compact (2 code points / byte vs 4 code points + 1 tag bit / 4-byte int).
And in 64 bite mode (~ every user) we are not using the high bits of the `int`.

**Comment by ppedrot** [comment]
Practice wins over theory, doesn't it?

**Comment by SkySkimmer** [comment]
Removed second commit.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
