### PR TITLE
Reduce the amount of useless typing in Equality.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Virtually no observable effect except for very few lines, but it doesn't hurt either in terms of code. I still think it's worth it.

**Comment by JasonGross** [comment]
Are the slowdowns in coq-fiat-crypto-with-bedrock/src/UnsaturatedSolinasHeuristics/Tests.v real?  (I wouldn't be surprised if they are.). Do you know what's going on there?

**Comment by ppedrot** [comment]
Are they? They're important in absolute value, but it's only ~1% in relative time. We can rerun a bench just for those if you wish.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Weird error with the bench: https://gitlab.com/coq/coq/-/jobs/2376393044. cc @coq/bench-maintainers

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by Alizter** [comment]
The bench error is known. For some reason the (coq side?) lua timing script in fiat crypto fails giving my script a headache when it reads a malformed html file.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Movies coming out this week: "Will fiat-crypto be benched successfully for Christmas?" @coqbot bench

**Comment by ppedrot** [comment]
The same two lines are still appearing as slow-downs, but with a very small relative diff. Not sure what to think.

**Comment by JasonGross** [comment]
> The same two lines are still appearing as slow-downs, but with a very small relative diff. Not sure what to think.

The small relative diff is because most of the time is spent in `native_compute`.  I'm a bit confused by the line numbers (cc @Alizter ), because line 139 is `Local Set NativeCompute Profiling.` and line 153 is blank, but line 141 is
```coq
Time Definition possible_limbs :=
  Eval native_compute in
    Option.List.lift
      (Option.List.map
         (fun p => match parseZ_arith_to_taps p with
                   | Some (s, c)
                     => if (s <=? 2^350)%Z
                        then Some (Some (p, [(64, get_possible_limbs s c 64); (32, get_possible_limbs s c 32)]))
                        else None
                   | None => Some None
                   end)
         primes).
```
and 155 is
```coq
Time Definition balances
  := Eval native_compute in
      option_map
       (fun ps
        => Option.List.lift
             (List.map
                (fun '(p, ls)
                 => option_map
                      (fun '(s, c)
                       => (p,
                           List.map
                             (fun '(bw, ns)
                              => List.map
                                   (fun n
                                    => let bal := @balance default_tight_upperbound_fraction n s c in
                                       let tub := @tight_upperbounds default_tight_upperbound_fraction n s c in
                                       let dif := map2 Z.sub bal tub in
                                       ((bw, n),
                                        ("balance:                                        ",
                                         (let show_lvl_Z := PowersOfTwo.show_lvl_Z in show bal),
                                         (let show_lvl_Z := Hex.show_lvl_Z in show bal)),
                                        ("tight_upperbounds:                              ",
                                         (let show_lvl_Z := PowersOfTwo.show_lvl_Z in show tub),
                                         (let show_lvl_Z := Hex.show_lvl_Z in show tub)),
                                        ("balance - tight_upperbounds:                    ",
                                         (let show_lvl_Z := PowersOfTwo.show_lvl_Z in show dif),
                                         (let show_lvl_Z := Hex.show_lvl_Z in show dif))))
                                   ns)
                             ls))
                      (parseZ_arith_to_taps p))
                ps))
       possible_limbs.
```

Where in `Definition foo := Eval native_compute in bar` would this patch impact?  (Btw, if you want to try this out on your own, the dependency tree for this file isn't very large.  I can make a standalone version if you want.)

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
