### PR TITLE
[comDefinition] Use prepare function from DeclareDef.

### PR DESCRIPTION
**Pull request by ejgallego**
We also update the plugin tutorial.

This was already tried [in the same exact way] in #8811, however the
bench time was not convincing then, but now things seem a bit better,
likely due to the removal of some extra normalization somewhere.

Some more changes from #8811 are still pending.

Backported from my proof tree.

### CODE REVIEW

**Comment by ejgallego** [comment]
https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/692/

**Comment by ejgallego** [comment]
Note that this code was already in the original #8811 I think. But it seems we now do a bit better bench-wise. https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/693/console
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬──────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │        mem faults        │
│                        │                         │                                             │                                             │                               │                          │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW    OLD   PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-odd-order │ 1537.86 1552.42 -0.94 % │     4287074481026     4328398797717 -0.95 % │     7269883256480     7271463120771 -0.02 % │    1260776    1260204 +0.05 % │      40    120  -66.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-hott │  344.64  347.64 -0.86 % │      937837132192      944103257656 -0.66 % │     1427623006769     1427704293149 -0.01 % │     479524     479392 +0.03 % │     458    246  +86.18 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-bignums │   72.35   72.78 -0.59 % │      201695667178      202563098902 -0.43 % │      267052729415      267167507170 -0.04 % │     501208     501228 -0.00 % │     186    154  +20.78 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-corn │ 1498.78 1506.27 -0.50 % │     4184895627375     4202487551477 -0.42 % │     6196806680967     6197049834116 -0.00 % │     836984     836796 +0.02 % │       1     38  -97.37 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│          coq-fiat-core │  109.52  109.95 -0.39 % │      312919007738      313410265300 -0.16 % │      391355923696      391341422054 +0.00 % │     503104     503080 +0.00 % │     691    282 +145.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-fiat-parsers │  699.14  701.78 -0.38 % │     1954584222955     1961735739155 -0.36 % │     2982549504108     2984727009819 -0.07 % │    3024384    2849256 +6.15 % │     443    628  -29.46 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│  coq-mathcomp-fingroup │   55.59   55.79 -0.36 % │      154796466241      155197026512 -0.26 % │      203155473695      203188010412 -0.02 % │     579112     577504 +0.28 % │      92     16 +475.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-fiat-crypto │ 4169.94 4180.09 -0.24 % │    11587517700992    11613057854960 -0.22 % │    18440324756109    18436620891393 +0.02 % │    2482436    2634948 -5.79 % │    1046    887  +17.93 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│     coq-mathcomp-field │  240.46  241.04 -0.24 % │      670281332957      671492365188 -0.18 % │      960946690676      960979339378 -0.00 % │     769356     770724 -0.18 % │       9     17  -47.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│           coq-compcert │ 1036.22 1038.46 -0.22 % │     2889672614506     2894994195020 -0.18 % │     4401759777612     4403419232027 -0.04 % │    1041404    1041344 +0.01 % │     414    541  -23.48 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│  coq-mathcomp-solvable │  204.63  204.88 -0.12 % │      570426302504      571019097992 -0.10 % │      765661792296      765731471588 -0.01 % │     805468     805544 -0.01 % │       6     75  -92.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-geocoq │ 2002.97 2005.39 -0.12 % │     5588101973208     5595811819740 -0.14 % │     8071884523628     8071801607673 +0.00 % │    1193440    1189848 +0.30 % │     487    457   +6.56 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-math-classes │  217.78  217.98 -0.09 % │      608151734228      609758712979 -0.26 % │      771395525332      771404151289 -0.00 % │     513220     513224 -0.00 % │     143     21 +580.95 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│   coq-mathcomp-algebra │  175.62  175.77 -0.09 % │      489354345568      490534977790 -0.24 % │      609822559836      609634332539 +0.03 % │     634624     634624 +0.00 % │       7      4  +75.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-character │  205.38  205.55 -0.08 % │      572265704177      573166980870 -0.16 % │      764175870053      764208482980 -0.00 % │    1066240    1066320 -0.01 % │     138     16 +762.50 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-color │  708.24  707.56 +0.10 % │     1975961497077     1980161200310 -0.21 % │     2354452912829     2354411283737 +0.00 % │    1342536    1379616 -2.69 % │     520    572   -9.09 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-flocq │  588.58  587.88 +0.12 % │     1638129581385     1636785043307 +0.08 % │     2274664268833     2274498205765 +0.01 % │    1243544    1243644 -0.01 % │     344    398  -13.57 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-ssreflect │   40.41   40.30 +0.27 % │      111588162459      111894315504 -0.27 % │      134330305259      134358283977 -0.02 % │     529912     529976 -0.01 % │      13     61  -78.69 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴──────────────────────────┘
```

**Comment by SkySkimmer** [comment]
PR/commit title seems wrong as declaredef isn't touched.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
What's going on with azure?

**Comment by ejgallego** [comment]
It think the Azure failure was temporary, and it is working now. Will indeed amend the title and the description and re-push, so we can see if it works now [will wait for the bench to complete tho as to avoid missing refs]

**Comment by ejgallego** [comment]
Final results are out. IMHO they are OK.

**Comment by SkySkimmer** [comment]
OK, let's merge

**Comment by ejgallego** [comment]
Merci

**Pull request merged**
