### PR TITLE
Fixes #7913: fixpoint with decreasing argument hidden behind a definition

### LINKED ISSUE #7913: Defining mutually recursive fixpoints as (definitional) type class instances
#### Version

8.8.0

#### Operating system

Linux

#### Description of the problem
Defining mutually recursive fixpoints as instances of definitional/singleton type classes is a little awkward right now. The following is an example that illustrates the problem.

```coq
Inductive bexp : Set :=
  | b_true : bexp
  | b_false : bexp
  | b_eq : aexp -> aexp -> bexp
with aexp : Set :=
     | a_of_bool : bexp -> aexp.

Class ContainsFalse (A : Set) :=
  contains_false : A -> bool.

Fixpoint bexp_ContainsFalse (b : bexp) :=
  match b with
  | b_true => false
  | b_false => true
  | b_eq a1 a2 => orb
                   (@contains_false aexp aexp_ContainsFalse a1)
                   (@contains_false aexp aexp_ContainsFalse a2)
  end with
aexp_ContainsFalse (a : aexp) :=
  match a with
  | a_of_bool b => (@contains_false bexp bexp_ContainsFalse b)
  end.

Instance BexpContainsFalse : ContainsFalse bexp := bexp_ContainsFalse.
Instance AexpContainsFalse : ContainsFalse aexp := aexp_ContainsFalse.
```

In the above code there are two awkward patterns. Firstly, I had to manually pass implicit parameters to `contains_false`, since I couldn't declare the instances a priori. Secondly, I had to rebind `bexp_ContainsFalse` and `aexp_ContainsFalse` to `BexpContainsFalse` and `AexpContainsFalse` so that I could declare them as instances.

Ideally I should be able to define instances with something like the following:
```coq
Fixpoint BexpContainsFalse (b : bexp) :=
  match b with
  | b_true => false
  | b_false => true
  | b_eq a1 a2 => orb (contains_false a1) (contains_false a2)
  end with
AexpContainsFalse (a : aexp) :=
  match a with
  | a_of_bool b => (contains_false b)
  end
with Instance BexpContainsFalse : ContainsFalse bexp
with Instance AexpContainsFalse : ContainsFalse aexp.
```

Could we extend coq's syntax for `Fixpoint` or `Instance` to support recursive singleton instances?

### PR DESCRIPTION
**Pull request by herbelin**
Fixes / closes #7913 (made possible by #19091 and #19259).

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by Blaisorblade** [comment]
The original wish involves mutual inductives and recursion too. Can a test for that be added?

**Comment by Blaisorblade** [comment]
And forgot to say, huge thanks @herbelin for working on this!!! Real quality of life improvement when these situations arise!

**Comment by herbelin** [comment]
Thanks for your feedback. Done!

**Comment by herbelin** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
