### PR TITLE
Describe changes from #14644 (Ltac visual debugger)

### PR DESCRIPTION
**Pull request by jfehrle**
Following up on @ejgallego's suggestion in #14644.

How does this look?

Tangentially, it's good practice for the client and server to exchange info on what versions of the protocol they can send/accept (minimally, "Client: I'm sending version X".  Server: ["Great!" | "Sorry, I don't work with that version"]) rather than a sloppy failure.  IIRC we don't have this in the XML protocol.  This isn't needed for CoqIDE but might be helpful for other clients such as coqtail.  Also, the version numbering is weak.  It could be more like the Coq version plus an optional suffix, e.g. `8.15` plus `.v1`, ignoring the Coq minor version number `8.15.0`.

### CODE REVIEW

**Comment by ejgallego** [comment]
> Tangentially, it's good practice for the client and server to exchange info on what versions of the protocol they can send/accept (minimally, "Client: I'm sending version X. Server: [Great! | Sorry I don't work with that version]) rather than a sloppy failure. IIRC we don't have this in the XML protocol. This isn't needed for CoqIDE but might be helpful for other clients such as coqtail. Also, the version numbering is weak. It could be more like the Coq version plus an optional suffix, e.g. `8.15` plus `.v1`, ignoring the Coq minor version number `8.15.0`.

Indeed, versioning and capability negotiation are required by any protocol that is meant to be not private.

As you know for example both DuneRPC and LSP do implement versions of this.

For SerAPI I didn't bother, as it was too experimental, but all the successors will be versioned.

**Comment by jfehrle** [comment]
I also corrected the name of the changelog file to match the branch name.

**Review by ejgallego — APPROVED** [review]
Thanks!

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
