### PR TITLE
Fixed grammar in changelog for Class > change

### PR DESCRIPTION
**Pull request by Alizter**
cc @Zimmi48 @ppedrot

### CODE REVIEW

**Comment by ppedrot** [comment]
Is it worth to be backported to 8.16?

**Comment by Alizter** [comment]
@ppedrot I think so.

**Comment by jfehrle** [comment]
@coqbot: merge now.

@Alizter: you win the award for the longest branch name

**Review by jfehrle — APPROVED** [review]
@coqbot: merge now

**Pull request merged**
