### PR TITLE
Lint stdlib with -mangle-names #5

### PR DESCRIPTION
**Pull request by jashug**
**Kind:** cleanup
A part of coq/stdlib#50

Nothing surprising here.
`ZMicromega.v` is file with the most changes.

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]
LGTM, thanks! Let's wait a week for others to comment.

**Comment by anton-trunov** [comment]
@coqbot merge now please

**Comment by anton-trunov** [comment]
Windows64 CI failure looks unrelated.

**Comment by Zimmi48** [comment]
Yes, it is unrelated. There's a PR (#13650) fixing the issue that has been opened for a week. Sorry about that 🙄

**Pull request merged**
