### PR TITLE
Document rewrite_db

### PR DESCRIPTION
**Pull request by jfehrle**

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
`rewrite_strat` is documented in: https://coq.inria.fr/refman/addendum/generalized-rewriting.html#strategies-for-rewriting
Maybe it would make sense to move `rewrite_db` next to it?

**Comment by jfehrle** [comment]
@Zimmi48 Your suggestion got me wondering what would happen if I pushed this same branch again with changes and whether it could then be merged again after rebasing.  Or would github/coqbot refuse to merge a PR that's already been merged once?  If permitted, it would be confusing/unexpected to have it merged twice.

**Comment by Alizter** [comment]
It wouldn't be the same PR but I am fairly sure that the branch doesn't matter.

**Comment by Zimmi48** [comment]
Correct, you cannot reopen a merged PR.

**Pull request merged**
