### PR TITLE
[experiment] typeclasses caching

### PR DESCRIPTION
**Pull request by mattam82**
This is an experiment to cache failures and successes during typeclass resolution.
This currently applies only to evar-free goals, and the maintainance of the cache throughout resolution is not perfect.
I'm mainly curious to see if this has an impact and if it's worth pursuing further.

- [ ] Added / updated **test-suite**

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

### CODE REVIEW

**Comment by Janno** [comment]
How persistent is the cache? Is it only used for single `typeclasses eauto` invocations?

**Comment by mattam82** [comment]
Right now, yes, a single invocation. I fear invalidation would not be so easy, as you'd have to consider updates to the DB and take care of dependencies in the local environment. If we only used a success cache then it could be easier.

**Comment by Janno** [comment]
I suspect successes for typeclasses with unique instances could be cached across calls but anything beyond that needs invalidation logic AFAICT. That might still be a helpful, though. Maybe this could help with queries generated by setoid_rewrite? I suspect `Proper` has unique instances so one could save on reconstructing complex `Proper` instances made up of smaller instances.

**Comment by Janno** [comment]
Actually, even caching unique instances without invalidation might backfire because of universes: it could be that a newly added or otherwise newly available hint would fire without the cache and that it would generate different universe constraints from the hint the cache chooses. I doubt anybody writes proofs like that on purpose but I have stopped hoping that universes will not somehow find a way to break stuff like this.

**Comment by ppedrot** [comment]
I suspect that as per the tag, this can be closed.

**Pull request closed without merging**
