### PR TITLE
{new,setoid_}ring -> ring

### PR DESCRIPTION
**Pull request by maximedenes**
I believe this renaming makes it easier for new contributors to discover
the code of `ring`.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Wow, that's a lot of breakages. I don't think it is OK to proceed with the renaming without providing better compatibility. One option would be to keep the renaming for the OCaml parts (unlikely to break much) and to undo the `theories` renaming. Another option is to introduce compatibility modules in `theories/setoid_ring` that reexports the modules from `theories/ring`.

**Comment by maximedenes** [comment]
Yep, let's split the change in two.

**Comment by jfehrle** [comment]
The .v files seem to have whitespace-only changes that are unnecessary.

Should Coq have some aliasing/deprecation mechanism to cover renaming things like this?

**Comment by maximedenes** [comment]
> The .v files seem to have whitespace-only changes that are unnecessary.

They were done automatically by the commit hook.

**Review by jfehrle — COMMENTED** [review]
Probably those lines were modified in your original commit, then you amended the commit to reverse many of the changes, leaving the space removal in place.  If it can be fixed in a few minutes, great, and if not, so be it.

**Comment by Zimmi48** [comment]
> Should Coq have some aliasing/deprecation mechanism to cover renaming things like this?

See also #8032.

**Comment by herbelin** [comment]
If the (indeed unexpectedly named) `setoid_ring` is anyway renamed, why not to change it to `Ring` which is consistent with the use of capital letters in the rest of `theories`.

**Comment by Zimmi48** [comment]
> If the (indeed unexpectedly named) `setoid_ring` is anyway renamed, why not to change it to `Ring` which is consistent with the use of capital letters in the rest of `theories`.

The renaming was backtracked due to the compatibility impact.

**Comment by herbelin** [comment]
> The renaming (in the theories) was backtracked due to the compatibility impact.

Ah, ok. I thought it was split into two.

Back to the compatibility impact, I think that, _if we want it_, the impact is minor and can be addressed easily with a python-or-so script.

**Comment by SkySkimmer** [comment]
Removed whitespace only changes

**Comment by maximedenes** [comment]
If nobody is interested (no assignee), I'll close this soon as it is very low priority for me.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
I'll take it.

**Comment by maximedenes** [comment]
Thanks!

**Comment by SkySkimmer** [comment]
@maximedenes ping you need to rebase

**Comment by maximedenes** [comment]
@SkySkimmer done

**Comment by SkySkimmer** [comment]
I killed the whitespace changes again

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
