### PR TITLE
Extending "contradiction" so that it recognizes statements such as "x<>x" or "~True"

### PR DESCRIPTION
**Pull request by herbelin**
This is the change of "contradiction" promised in the 8.6 roadmap.

Led to a single incompatibility in contribs.

### CODE REVIEW

**Comment by herbelin** [comment]
What protocol to adopt to decide where to merge this? Are there objections to merge it to v8.6 (somehow as promised)?

**Comment by maximedenes** [comment]
This is a bit complex. On one hand, if it is on the roadmap, we can integrate it. On the other hand, I'm a bit scared that we didn't have much time to study the impact on compatibility.

**Comment by herbelin** [comment]
What do you suggest to study the impact on compatibility (independently of the targetted version)?

**Comment by mattam82** [comment]
Given that it's an ending tactic used to solve leaves of the proof my guess is that incompatibilities will be relatively easy to spot compared to e.g the subst changes, so I am in favor of merging it. I think we all agree that the good protocol will be Ltac versioning and we should strive to have this for the next version. Right now we only have gut feelings and (our limited) empirical data to rely on. Just one thing, we should have a compat-version test here no?

**Comment by maximedenes** [comment]
That's fine with me. Giving more thought, it seems indeed that the incompatibilities should not be too hard to fix for reasonably structured proofs. But you are right, @mattam82, Jason will soon ask if the -compat flag gives the old behavior :)

**Comment by herbelin** [comment]
How to help in the direction of supporting Ltac versioning? One thing that remains to do is to attach a version number to defined ltac functions, right? Then, assuming we keep the same code for tactics and be very careful about tracking the changes, is it just about providing a command to set the set of relevant flags all at once (and then "Compat/CoqXY.v" would also activate this command)?

**Comment by silene** [comment]
I am not sure to understand what you mean. But the important use case is the following one. Assume that a tactic foo is used by two libraries to provide tactics named bar and baz. Assume that the user loads both libraries because bar and baz are great tactics. Assume that one library expects the 8.5 semantics for foo, while the other library expects the 8.6 semantics for foo. It is important that, when the user invokes both bar and baz, both semantics are not mixed up.

So it is not just a matter of having flags, it is a matter of setting flags on a per tactic basis. Ideally, `Compat/Coq85.v` would simply contain the following line:

    Ltac foo := foo version 8.5. (* whatever the syntax *)

**Comment by herbelin** [comment]
I believe we are saying the same thing: to attach a version number to tactic definitions.

For instance, what I have in mind is that if `Ltac foo` or `Tactic Notation "foo"` is defined in a file which sets ltac version to say 8.5, then foo is internally tagged with 8.5 and every use of foo sets the ltac environment to 8.5.

Then, if one wants foo to be called by using either the 8.5 or 8.6 semantics of its components, then one would indeed need a way to dynamically rebind its semantics (do you have a concrete application in mind?).

**Comment by silene** [comment]
Actually, I was not attaching the version to definitions, but to uses. I should have used extra symbols to make it clearer:

    Ltac foo := (foo@8.5).

But your solution seems to work too. For a moment, I thought that it would break for tactics written in a continuation-passing style, but I cannot find a counter-example.

As for wanting to dynamically rebind semantics, I don't have any use case. And using `Ltac ::=` should do the trick anyway, I guess.

**Comment by herbelin** [comment]
I fell again yesterday on the need for it (with these `Gt<>Gt` hypotheses in ZArith) so I'm seizing this green light to push it to 8.6. @maximedenes: I did not add a flag, but if compat is set to <= 8.5, then the new behavior is not activated. If e.g. Jason thinks it is better to have a flag, it is also possible, but the changes are so exceptional and so easy to spot, and scripts easy to change so that they work for both behaviors that I'm unsure that an (extra) flag is needed. @mattam82: What do you have in mind as "compat-version test"?

**Comment by mattam82** [comment]
I was precisely asking for a test in the code to activate it for >= 8.6
only.

**Comment by herbelin** [comment]
Ah, ok then.

**Pull request closed without merging**
