### PR TITLE
allow empty tactic_rules in ARGUMENT EXTEND

### LINKED ISSUE #10275: YouShouldNotTypeThis tokens in the ssr grammar? coqpp change to fix?
#### Description of the problem

The ssr grammar has a number of productions that start with `YouShouldNotTypeThis`.  If `ARGUMENT EXTEND` in coqpp allowed an empty `tactic_rules`, could these rules be deleted?  Or is there some other simple change to make them unnecessary?

I will submit a PR for this if it makes sense.

### PR DESCRIPTION
**Pull request by DabrowskiFr**
**Kind:** feature

Fixes / closes #10275 

- [ ] Added / updated test-suite
- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
There are still some youshouldnottypethis, like https://github.com/coq/coq/blob/805211a603431f4ba351e0164b0bd147a771a1a0/plugins/ssr/ssrparser.mlg#L523
Why?

**Review by gares — APPROVED** [review]
Thanks!

**Comment by maximedenes** [comment]
@gares, do you know the answer to @SkySkimmer's question?

**Comment by DabrowskiFr** [comment]
@SkySkimmer If I get it right, "YouShouldNotTypeThis" was used in two situations
1) when no rule should match, in this case an anomaly was raised
2) [as a] token for tacticals that don't start with a token (see plugins/ssr/ssrparser.mlg)
The PR is concerned by the first situation only.

**Comment by maximedenes** [comment]
@DabrowskiFr Oh yes, that rings a bell. I thought I had removed this limitation, though (tactics used to have to start with a symbol indeed, but I'm not sure if it is still the case). We can try to remove it in a next PR, but this one looks good to me as it is.

**Comment by maximedenes** [comment]
@ppedrot can you take this one?

**Review by ppedrot — APPROVED** [review]
This looks OK, but I still hope that this doesn't interfere with the backtracking mechanism strapped on the camlp5 engine.

**Comment by maximedenes** [comment]
> This looks OK, but I still hope that this doesn't interfere with the backtracking mechanism strapped on the camlp5 engine.

Can you say more about your concern? I don't really see what you mean.

**Comment by ppedrot** [comment]
There is imperative code in Pcoq handcrafted to handle backtrack of entry creation and extension. I was just hoping that this code was sane when the list of rules provided is empty. (I have no idea whether it is sane in general, so don't ask me.)

**Comment by maximedenes** [comment]
> There is imperative code in Pcoq handcrafted to handle backtrack of entry creation and extension. I was just hoping that this code was sane when the list of rules provided is empty. (I have no idea whether it is sane in general, so don't ask me.)

I see, thanks. Since CI is green and the scenario you mention would be a bug in that other part of the code, I think this is good to go :)

**Pull request merged**
