### PR TITLE
Rebuild coqtop$(EXE) in "make coqbinaries" in addition to coqtop.opt$(EXE).

### LINKED ISSUE #7758: Make target coqbinaries only rebuilds coqtop.opt, not coqtop
#### Version

Coq 8.9+alpha

#### Operating system

Windows and Linux

#### Description of the problem

Since #6859, running `make` will generate two identical binaries `bin/coqtop` and `bin/coqtop.opt`. However, changing something then running `make coqbinaries` will only regenerate `bin/coqtop.opt`, leaving `bin/coqtop` unchanged.

cc @ejgallego

### PR DESCRIPTION
**Pull request by jfehrle**
Rebuild *.exe in "make coqbinaries" in addition to *.opt.exe for top binaries

**Kind:** bug fix / infrastructure.

Fixes #7758.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
As mentioned in the issue, this should be only for coqtop, not coqproofworker etc.

**Comment by jfehrle** [comment]
Ah, I wasn't sure what @ejgallego meant by "The other 3 binaries are internal so indeed I guess the explicit naming is preferrable."  Emilio, do you agree I should not copy coqproofworker.opt.exe to coqproofworker.exe (and the other 2)?  Only coqtop.opt.exe?

**Comment by ejgallego** [comment]
> do you agree I should not copy coqproofworker.opt.exe to coqproofworker.exe (and the other 2)? Only coqtop.opt.exe?

I do agree, only coqtop I think.

**Comment by ejgallego** [comment]
The current maintainer for the make system is @gares

**Comment by gares** [comment]
The makefile contains code like `...  && $(STRIP) $@ && $(CODESIGN) ...` hence you cannot put `$(HIDE)` as part of the value of `CODESIGN`.

**Comment by jfehrle** [comment]
I tried a lot of alternatives for this define but couldn't get it to to work.  I suppose the alternatives are a) insert conditionals wherever there is CODESIGN command or b) let it be since it's a minor issue.

```
define codesign
if [ "$(CODESIGN)" != true ] then $(CODESIGN) $@; fi
endef
```

**Comment by jfehrle** [comment]
This is ready for review.

FWIW, I noticed there were some places in the makefiles where only CODESIGN or STRIP are called, rather than both.  Hope that's correct.

**Review by ejgallego — APPROVED** [review]
The parts I understand look good to me.

**Review by gares — APPROVED** [review]
This PR is 1 line fix (`Makefile.build`, line 398) plus two unrelated changes, namely the renaming of `TOPBIN` to `TOPBINOPT` and (in a separate commit) the hiding of a useless (on windows and linux) message.

I won't nitpick this time, but next time please separate unrelated changes in separate PRs/commits.

**Comment by ejgallego** [comment]
@gares are you taking this?

**Pull request merged**
