### PR TITLE
[Ltac2] : Add system functions for writing and reading files and running processes

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This PR is a partial/preliminary implementation of #10369.

Before I finish this, I would like to discuss 2 things:

1.) Is this agreeable (if not I can make a separate plugin)

2.) I need some help with catching the potential Sys_error. I couldn't figure out how to add a throw inside of the wrap. Most functions already there first check parameters, possible throw and then do a wrap. I am not sure if this would work here.

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
P.S.: regarding the error handling: it works reasonably fine as is. If I write e.g. to a non existing path I get (in CoqIDE) the error:
```
System error: "C:/Tempa/test1.txt: No such file or directory"
````

Here is some sample code:
```
Require Import Ltac2.Ltac2.
Require Ltac2.Message.
Require Ltac2.String.
Require Ltac2.System.

Require Import String.

Goal True.
Message.print (Message.of_string (String.of_coq_string (constr:("ABCD"%string)))).
System.file_write_coq_string  "C:/Temp/test1.txt" (constr:("ABCD\n"%string)).
System.file_append_coq_string  "C:/Temp/test1.txt" (constr:("EFGH\n"%string)).
```

**Comment by MSoegtropIMC** [comment]
@ppedrot : can you please have a quick look at this PR and leave a comment if this is concept wise agreeable? As stated this is only preliminary but I would like to have a general go/no-go comment from you at this stage before I put effort into finishing and polishing it.

**Comment by ppedrot** [comment]
I am not so sure about the availability of these functions by default. It looks like a big security hole to me, such an API should be opt-in. I remember people complaining about similar features from Ltac1 (the infamous `external` tactical), there was even a bug opened. Also, exposing the horrors of IO in Ltac2 brings in sordid considerations about the OS and the file system. Remember the HFS hack to emulate case-sensitivity in library resolution?

As a matter of fact, I think these functions should be provided as an external library.

**Comment by MSoegtropIMC** [comment]
> As a matter of fact, I think these functions should be provided as an external library.

Ok, I also thought along these lines.

One question: does the "ltac2" in
```
Ltac2 @external file_write : string -> string -> unit := "ltac2" "system_file_write".
```
mean that I could just create a DLL with another name, say "ltac2-sys", and move the OCaml code into this DLL? If this would work it would be a super useful extension feature. Right now it is quite a bit harder to integrate custom tactics.

**Comment by ppedrot** [comment]
> does the "ltac2" mean that I could just create a DLL with another name, say "ltac2-sys", and move the OCaml code into this DLL?

Yes and no. You just have to change the name used for the registration of this primitive, see `Tac2env.define_primitive`. The `"ltac2"` string corresponds to the first field of the `ml_tactic_name` record type.

**Comment by ppedrot** [comment]
If this is supposed to be provided as an external plugin, I think we can close this PR.

**Pull request closed without merging**
