### PR TITLE
Moving file primitive.ml to cPrimitive.ml to avoid conflict with OCaml.

### PR DESCRIPTION
**Pull request by herbelin**
Indeed OCaml has a similar file and this conflicts, at least in debugger.

Without this fix, loading the ocamldebug printers (`source db`) fails for me from about 27 July 2017.

I did not check for 8.7 if this happens also.

Happy vacations in passing.

### CODE REVIEW

**Comment by psteckler** [comment]
Maybe this fixes BZ#5688?

**Comment by psteckler** [comment]
No, this does not fix BZ#5688.

**Comment by Zimmi48** [comment]
No, in v8.7 there is no error.
BTW, has it always been the case that one must call the `devel` target of the Makefile before being able to `source db`?

**Comment by psteckler** [comment]
@Zimmi48 In master, I get errors when running `source db` from ocamldebug within Emacs. It runs fine after apply this patch, and building `byte` and `coqlib` (not `devel`).

But `coqtop.byte` still hangs, as described in BZ#5688.

**Comment by Zimmi48** [comment]
Indeed, thanks @psteckler I had tested `make` and `make states BEST=byte`, but `make byte` was the good one.

**Comment by herbelin** [comment]
This is another example where, as already mentioned, it would be nice to have support from OCaml for not reserving some file names, but where, for obvious practical reasons, I don't see how to avoid acting on our side. My proposal is simply to apply the usual trick, but maybe someone has a better idea? In any case, this PR answers a somehow critical developer need!

**Comment by Zimmi48** [comment]
Unless someone else has a better idea, it would be good to merge this quickly. As you may have remarked though, @maximedenes was on vacation and only came back a few days (initially he planned one day) to work on the beta release. That's why this PR has not yet been merged.

**Comment by maximedenes** [comment]
I agree this is a bit sad, but probably the best thing to do in the current situation. I'll merge it now, sorry for being slow these days.

**Pull request merged**
