### PR TITLE
Restrict  zify saturation to work on hypotheses of the initial goal

### LINKED ISSUE #18151: Zify saturation leads to Qed failure due to bad order of let-bindings
#### Description of the problem

This likely relates to the feature introduced in https://github.com/coq/coq/pull/16355 (cc @frantisekfarka).

```coq
Require Import Coq.ZArith.BinInt.
From Coq Require Import Zify ZifyClasses.
Import Z.
Open Scope Z_scope.

#[global] Instance sat_mod_le : ZifyClasses.Saturate BinIntDef.Z.modulo :=
  {|
    ZifyClasses.PArg1 := fun a => 0 <= a;
    ZifyClasses.PArg2 := fun b => 0 < b;
    ZifyClasses.PRes := fun a b ab => ab <= a;
    ZifyClasses.SatOk := mod_le
  |}.
Add Zify Saturate sat_mod_le.

(* phrase in terms of division by 1 or larger? *)
Lemma shiftr_lbound a n:
   0 <= a -> True -> 0 <= (Z.shiftr a n).
Proof. now intros; apply Z.shiftr_nonneg. Qed.

#[global] Instance sat_shiftr_lbound : ZifyClasses.Saturate BinIntDef.Z.shiftr :=
  {|
    ZifyClasses.PArg1 := fun a => 0 <= a;
    ZifyClasses.PArg2 := fun b => True;
    ZifyClasses.PRes := fun a b ab => 0 <= ab;
    ZifyClasses.SatOk := shiftr_lbound
  |}.
Add Zify Saturate sat_shiftr_lbound.

Axiom TODO: forall {P}, P.
Goal
  forall (x4 x5 t0 : N)
    (_ : and (le Z0 (of_N x4)) (le (of_N x4) 18446744073709551615)),
  @Logic.eq Z
    (land (modulo (shiftr (of_N x4) (of_N t0)) (pow (Zpos (xO xH)) (of_N (Npos (xO (xO (xO (xO (xO (xO xH))))))))))
       (sub (shiftl (Zpos xH) (of_N x5)) (Zpos xH))) (land (shiftr (of_N x4) (of_N t0)) (sub (shiftl (Zpos xH) (of_N x5)) (Zpos xH))).
  intros.
  zify.
  apply TODO.
Qed. (* Fails with: No such section variable or assumption: __sat6. *)
```

The proof term is the following:
```
(fun (x4 x5 t0 : N) (_ : 0 <= of_N x4 <= 18446744073709551615) =>
 let cstr : 0 <= of_N x4 := Znat.N2Z.is_nonneg x4 in
 let __sat9 : 0 < 2 -> 0 <= of_N (Npos 64) -> 0 < 2 ^ of_N (Npos 64) := pow_pos_nonneg 2 (of_N (Npos 64)) in
 let __sat8 : 0 <= 2 -> True -> 0 <= 2 ^ of_N (Npos 64) :=
   fun (Ha : 0 <= 2) (_ : True) => pow_nonneg 2 (of_N (Npos 64)) Ha in
 let __sat7 :
   0 < 2 ^ of_N (Npos 64) -> shiftr (of_N x4) (of_N t0) mod 2 ^ of_N (Npos 64) <= shiftr (of_N x4) (of_N t0) :=
   mod_le (shiftr (of_N x4) (of_N t0)) (2 ^ of_N (Npos 64)) __sat6 in
 let __sat6 : 0 <= shiftr (of_N x4) (of_N t0) := shiftr_lbound (of_N x4) (of_N t0) cstr I in TODO)
```
Note that `__sat7` uses `__sat6`, which is defined later.

CC @Janno who helped me minimize this.

#### Coq Version

8.17.0 and also master

### PR DESCRIPTION
**Pull request by rlepigre**
Fixes / closes #18151.

### CODE REVIEW

**Comment by silene** [comment]
Is there a chance that it also fixes #17983 or is it unrelated?

**Comment by rlepigre** [comment]
> Is there a chance that it also fixes #17983 or is it unrelated?

I think it must be unrelated, as I get the same error in my branch. Also, the symptoms are different since no `__satN` variable seem involved.

**Comment by fajb** [comment]
Hi @rlepigre , thanks for the fix.

The more I think about it the less I am pleased with this saturation feature.
I am re-reading the code and I am unsure  having `sat_x` using `sat_y`  was anticipated...
Also, the current code seems fragile as it depends on the order of `CstrTable.HConstr.fold`.

As it is buggy, no one would use the sat_x depending on sat_y.
Could we forbid it instead?
In principle, it will be less powerful but maybe less fragile.

**Comment by fajb** [comment]
I have committed a more conservative proposal.

**Comment by rlepigre** [comment]
Thanks Frédéric! We'll have a look to see if that is still good enough for our use-cases.

**Comment by fajb** [comment]
@coqbot: run full CI

**Review by silene — CHANGES_REQUESTED** [review]
The changes to the OCaml code are fine. But the changelog entry is now outdated, both in its description and in its attribution. No need to re-run the full CI once amended.

**Comment by rlepigre** [comment]
Also, I forgot to say, but it seems the fix is good enough for our use-cases.

**Review by fajb — APPROVED** [review]

**Comment by fajb** [comment]
> I fixed the changelog and tweaked the commit message. Do check that it works for you @fajb, since I amended your commit.

Good for me

**Comment by silene** [comment]
Just to be clear, I was not suggesting that you remove yourself from the attribution, just that you add Frédéric (since you submitted the testcase and located the issue in the code). So, I will wait a bit before merging, in case you wish to change the changelog entry back.

**Review by silene — APPROVED** [review]

**Comment by fajb** [comment]
> Just to be clear, I was not suggesting that you remove yourself from the attribution, (since you submitted the testcase and located the issue in the code). 

Yes, @rlepigre you should be mentioned.

**Comment by rlepigre** [comment]
OK, I added my name back, thanks! I forgot I wrote the test case.

**Comment by silene** [comment]
@coqbot merge now

**Pull request merged**
