### PR TITLE
Algorithmically faster hypothesis picking in goal matching

### PR DESCRIPTION
**Pull request by ppedrot**
We use a map rather than a list. This has a O(n log n) upfront cost to build the map, and slightly higher overheads, but it saves O(n) reconstructions of the intermediate lists, preventing a quadratic blowup. This is also likely to save some memory.

### CODE REVIEW

**Comment by Janno** [comment]
Wouldn't an array be more straight-forward?

**Comment by ppedrot** [comment]
How do you remove an element from an array in O(log n)?

**Comment by ppedrot** [comment]
This PR is faster on micro-benchmarks but I don't know if it will have any effect in the real world. The ultimate goal is to counter the slowdown introduced by #8905.

**Comment by ppedrot** [comment]
@Janno no, the algorithm is not just about browsing the hypothesis list. Given a list of patterns P and a list of hypotheses H, it constructs the list of injections P → H, i.e. |P|-tuples of elements of H without redundancy. To do this you need to keep track of the hypotheses that have been already used up, hence the map. (If you happen to know an even more efficient algorithm for this, I am all ears, btw.)

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-coqprime │   61.88    62.08  -0.32 │   269637755938    270322029909  -0.25 │   448775249133    448784235386  -0.00 │  763868   763856   0.00 │   0    0      nan │
│                coq-compcert │  290.80   291.54  -0.25 │  1264229093508   1268059908665  -0.30 │  1903230008950   1890184340324   0.69 │ 1105944  1104672   0.12 │   0   34  -100.00 │
│       coq-mathcomp-fingroup │   24.67    24.72  -0.20 │   107546003301    107719034891  -0.16 │   157041097338    157025661997   0.01 │  490864   489976   0.18 │   0    0      nan │
│                     coq-vst │ 1090.16  1091.67  -0.14 │  4762009660850   4769064140637  -0.15 │  7718427953510   7713647708274   0.06 │ 2114404  2134444  -0.94 │   1    0      nan │
│      coq-mathcomp-odd-order │  571.49   571.87  -0.07 │  2504652678853   2506697143321  -0.08 │  4288745936420   4288328175080   0.01 │ 1222292  1226416  -0.34 │   0    0      nan │
│               coq-fiat-core │   56.95    56.97  -0.04 │   235404526808    234284299480   0.48 │   332420619767    331088530812   0.40 │  479328   479596  -0.06 │   1    6   -83.33 │
│                 coq-unimath │ 4446.26  4446.40  -0.00 │ 19471726036606  19472397310195  -0.00 │ 38995427926788  38967847483815   0.07 │ 3258412  3258224   0.01 │   2    0      nan │
│               coq-fourcolor │ 1518.20  1517.81   0.03 │  6638277956812   6634946967320   0.05 │ 12117039630237  121[1682](https://gitlab.com/coq/coq/-/jobs/2127845907#L1682)2358578   0.00 │  756640   755672   0.13 │   0    0      nan │
│                 coq-bignums │   28.66    28.64   0.07 │   125039904188    124754403941   0.23 │   172846984745    172488470937   0.21 │  469064   469872  -0.17 │   0    0      nan │
│                    coq-hott │  167.06   166.84   0.13 │   725569709352    723296544415   0.31 │  1151266688342   1150895807189   0.03 │  616956   617468  -0.08 │   0    0      nan │
│          coq-mathcomp-field │  119.67   119.48   0.16 │   524077161389    523712365659   0.07 │   861716220222    861715119707   0.00 │  709616   712260  -0.37 │   0    0      nan │
│        coq-mathcomp-algebra │   66.91    66.75   0.24 │   292184038184    291826123354   0.12 │   402724609489    402692692891   0.01 │  600280   600908  -0.10 │   0    0      nan │
│      coq-mathcomp-ssreflect │   27.06    26.98   0.30 │   117805383792    117579457755   0.19 │   149237232681    149210842152   0.02 │  537116   537160  -0.01 │   0    0      nan │
│       coq-mathcomp-solvable │   91.53    91.25   0.31 │   400718912177    399465980870   0.31 │   613653337520    613636087181   0.00 │  668084   668684  -0.09 │   0    0      nan │
│             coq-fiat-crypto │ 2919.25  2909.90   0.32 │ 12733504100298  12693424601399   0.32 │ 23290153231321  23209223317460   0.35 │ 3848740  3836608   0.32 │  87   89    -2.25 │
│                  coq-stdlib │  414.29   412.93   0.33 │  1482073329955   1477023651960   0.34 │  1424701815427   1427899933540  -0.22 │  595600   604408  -1.46 │   0    0      nan │
│                   coq-color │  216.13   215.40   0.34 │   937170155753    934852055130   0.25 │  1330609769309   1325942422995   0.35 │ 1150124  1150848  -0.06 │   0    0      nan │
│  coq-performance-tests-lite │  805.29   802.47   0.35 │  3504437372273   3492986705305   0.33 │  5979419354292   5959449400955   0.34 │ 1824280  1826532  -0.12 │   0    0      nan │
│                    coq-core │  106.72   106.31   0.39 │   387774128135    384696733416   0.80 │   441185933177    441156658526   0.01 │  278320   277988   0.12 │   1    0      nan │
│               coq-perennial │ 4126.25  4109.55   0.41 │ 18043717268671  17970074770806   0.41 │ 29854945436925  29819923036171   0.12 │ 2612736  2619124  -0.24 │   0    0      nan │
│           coq-iris-examples │  427.60   425.62   0.47 │  1865024998813   1857555486804   0.40 │  2842602542593   2841381459353   0.04 │ 1182232  1191556  -0.78 │   0    0      nan │
│                    coq-corn │  784.85   780.83   0.51 │  3427768380445   3410249367287   0.51 │  5304799520604   5278104523560   0.51 │  878864   878624   0.03 │   0    0      nan │
│                  coq-flocq3 │   79.10    78.60   0.64 │   344052289527    342989852003   0.31 │   455707782616    455312140541   0.09 │  992196   994636  -0.25 │   0    0      nan │
│              coq-coquelicot │   35.56    35.31   0.71 │   153042102488    152449444891   0.39 │   203543181588    202624045696   0.45 │  753704   753652   0.01 │ 156    0      nan │
│         coq-category-theory │ 1701.00  [1687](https://gitlab.com/coq/coq/-/jobs/2127845907#L1687).13   0.82 │  7452803377049   7390159277244   0.85 │ 15551896498350  15422805242050   0.84 │ 1469252  1469560  -0.02 │   0    0      nan │
│       coq-engine-bench-lite │  182.92   181.34   0.87 │   769162617497    761750752208   0.97 │  1510987699829   1492564525393   1.23 │ 1236644  1357392  -8.90 │   0    0      nan │
│      coq-mathcomp-character │   80.68    79.92   0.95 │   353209836147    350259721414   0.84 │   533375538108    533403442466  -0.01 │  852728   850576   0.25 │   0    0      nan │
│            coq-fiat-parsers │  347.55   344.23   0.96 │  1498706671701   1485973735907   0.86 │  2472024524753   2448464258074   0.96 │ 2694616  2694776  -0.01 │   0   13  -100.00 │
│                coq-rewriter │  392.66   388.66   1.03 │  1713555312109   [1696](https://gitlab.com/coq/coq/-/jobs/2127845907#L1696)135472645   1.03 │  2823060815287   2769924165750   1.92 │ 1060036  1065316  -0.50 │   2   11   -81.82 │
│ coq-rewriter-perf-SuperFast │  968.10   958.04   1.05 │  4229820752324   4185467746330   1.06 │  7326175162619   7272038617571   0.74 │ 1147052  1145192   0.16 │   4    0      nan │
│                 coq-coqutil │   36.36    35.93   1.20 │   156895207423    154686099586   1.43 │   212504613587    208706220259   1.82 │  602968   604004  -0.17 │   4    0      nan │
│                coq-bedrock2 │  226.03   222.67   1.51 │   987139001331    973215174547   1.43 │  1800977712862   1768828226731   1.82 │ 2053868  2051996   0.09 │  11   10    10.00 │
│            coq-math-classes │   95.10    92.88   2.39 │   412893466408    403450254877   2.34 │   586624297967    571416871346   2.66 │  502664   502968  -0.06 │   0    0      nan │
│                   coq-verdi │   50.63    49.34   2.61 │   220432549014    213816524709   3.09 │   332052358163    320949082856   3.46 │  843332   837164   0.74 │   0    0      nan │
│                  coq-geocoq │  754.58   726.90   3.81 │  3295371486519   3171154581822   3.92 │  5288379909764   4994926397458   5.88 │ 1075804  1075476   0.03 │  27    7   285.71 │
│              coq-verdi-raft │  608.54   575.68   5.71 │  2659640564146   2514507410268   5.77 │  4202466690088   3905684143949   7.60 │ 1256412  1256144   0.02 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```
Not good. I supposed we can have a fast-path when there is at most one hypothesis to select, maybe that would save the map reconstruction.

**Comment by ppedrot** [comment]
I never get tired: https://gitlab.com/coq/coq/-/jobs/2131464285

**Comment by ppedrot** [comment]
I am letting the bench finish, but #15734 is a much cleaner implementation that has the same performance profile on extreme examples and no overhead. Consequently I'll close this one in favour of the other PR.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/15731#issuecomment-1049588055
How do you get URLs in your copy-paste?

**Comment by Alizter** [comment]
@SkySkimmer Gitlab seems to be outputting some information that gets interlaced with the render. Github always renders links too.

**Comment by SkySkimmer** [comment]
When I copypaste from gitlab I don't get any links though
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-coqprime │   61.88    62.08  -0.32 │   269637755938    270322029909  -0.25 │   448775249133    448784235386  -0.00 │  763868   763856   0.00 │   0    0      nan │
│                coq-compcert │  290.80   291.54  -0.25 │  1264229093508   1268059908665  -0.30 │  1903230008950   1890184340324   0.69 │ 1105944  1104672   0.12 │   0   34  -100.00 │
│       coq-mathcomp-fingroup │   24.67    24.72  -0.20 │   107546003301    107719034891  -0.16 │   157041097338    157025661997   0.01 │  490864   489976   0.18 │   0    0      nan │
│                     coq-vst │ 1090.16  1091.67  -0.14 │  4762009660850   4769064140637  -0.15 │  7718427953510   7713647708274   0.06 │ 2114404  2134444  -0.94 │   1    0      nan │
│      coq-mathcomp-odd-order │  571.49   571.87  -0.07 │  2504652678853   2506697143321  -0.08 │  4288745936420   4288328175080   0.01 │ 1222292  1226416  -0.34 │   0    0      nan │
│               coq-fiat-core │   56.95    56.97  -0.04 │   235404526808    234284299480   0.48 │   332420619767    331088530812   0.40 │  479328   479596  -0.06 │   1    6   -83.33 │
│                 coq-unimath │ 4446.26  4446.40  -0.00 │ 19471726036606  19472397310195  -0.00 │ 38995427926788  38967847483815   0.07 │ 3258412  3258224   0.01 │   2    0      nan │
│               coq-fourcolor │ 1518.20  1517.81   0.03 │  6638277956812   6634946967320   0.05 │ 12117039630237  12116822358578   0.00 │  756640   755672   0.13 │   0    0      nan │
│                 coq-bignums │   28.66    28.64   0.07 │   125039904188    124754403941   0.23 │   172846984745    172488470937   0.21 │  469064   469872  -0.17 │   0    0      nan │
│                    coq-hott │  167.06   166.84   0.13 │   725569709352    723296544415   0.31 │  1151266688342   1150895807189   0.03 │  616956   617468  -0.08 │   0    0      nan │
│          coq-mathcomp-field │  119.67   119.48   0.16 │   524077161389    523712365659   0.07 │   861716220222    861715119707   0.00 │  709616   712260  -0.37 │   0    0      nan │
│        coq-mathcomp-algebra │   66.91    66.75   0.24 │   292184038184    291826123354   0.12 │   402724609489    402692692891   0.01 │  600280   600908  -0.10 │   0    0      nan │
│      coq-mathcomp-ssreflect │   27.06    26.98   0.30 │   117805383792    117579457755   0.19 │   149237232681    149210842152   0.02 │  537116   537160  -0.01 │   0    0      nan │
│       coq-mathcomp-solvable │   91.53    91.25   0.31 │   400718912177    399465980870   0.31 │   613653337520    613636087181   0.00 │  668084   668684  -0.09 │   0    0      nan │
│             coq-fiat-crypto │ 2919.25  2909.90   0.32 │ 12733504100298  12693424601399   0.32 │ 23290153231321  23209223317460   0.35 │ 3848740  3836608   0.32 │  87   89    -2.25 │
│                  coq-stdlib │  414.29   412.93   0.33 │  1482073329955   1477023651960   0.34 │  1424701815427   1427899933540  -0.22 │  595600   604408  -1.46 │   0    0      nan │
│                   coq-color │  216.13   215.40   0.34 │   937170155753    934852055130   0.25 │  1330609769309   1325942422995   0.35 │ 1150124  1150848  -0.06 │   0    0      nan │
│  coq-performance-tests-lite │  805.29   802.47   0.35 │  3504437372273   3492986705305   0.33 │  5979419354292   5959449400955   0.34 │ 1824280  1826532  -0.12 │   0    0      nan │
│                    coq-core │  106.72   106.31   0.39 │   387774128135    384696733416   0.80 │   441185933177    441156658526   0.01 │  278320   277988   0.12 │   1    0      nan │
│               coq-perennial │ 4126.25  4109.55   0.41 │ 18043717268671  17970074770806   0.41 │ 29854945436925  29819923036171   0.12 │ 2612736  2619124  -0.24 │   0    0      nan │
│           coq-iris-examples │  427.60   425.62   0.47 │  1865024998813   1857555486804   0.40 │  2842602542593   2841381459353   0.04 │ 1182232  1191556  -0.78 │   0    0      nan │
│                    coq-corn │  784.85   780.83   0.51 │  3427768380445   3410249367287   0.51 │  5304799520604   5278104523560   0.51 │  878864   878624   0.03 │   0    0      nan │
│                  coq-flocq3 │   79.10    78.60   0.64 │   344052289527    342989852003   0.31 │   455707782616    455312140541   0.09 │  992196   994636  -0.25 │   0    0      nan │
│              coq-coquelicot │   35.56    35.31   0.71 │   153042102488    152449444891   0.39 │   203543181588    202624045696   0.45 │  753704   753652   0.01 │ 156    0      nan │
│         coq-category-theory │ 1701.00  1687.13   0.82 │  7452803377049   7390159277244   0.85 │ 15551896498350  15422805242050   0.84 │ 1469252  1469560  -0.02 │   0    0      nan │
│       coq-engine-bench-lite │  182.92   181.34   0.87 │   769162617497    761750752208   0.97 │  1510987699829   1492564525393   1.23 │ 1236644  1357392  -8.90 │   0    0      nan │
│      coq-mathcomp-character │   80.68    79.92   0.95 │   353209836147    350259721414   0.84 │   533375538108    533403442466  -0.01 │  852728   850576   0.25 │   0    0      nan │
│            coq-fiat-parsers │  347.55   344.23   0.96 │  1498706671701   1485973735907   0.86 │  2472024524753   2448464258074   0.96 │ 2694616  2694776  -0.01 │   0   13  -100.00 │
│                coq-rewriter │  392.66   388.66   1.03 │  1713555312109   1696135472645   1.03 │  2823060815287   2769924165750   1.92 │ 1060036  1065316  -0.50 │   2   11   -81.82 │
│ coq-rewriter-perf-SuperFast │  968.10   958.04   1.05 │  4229820752324   4185467746330   1.06 │  7326175162619   7272038617571   0.74 │ 1147052  1145192   0.16 │   4    0      nan │
│                 coq-coqutil │   36.36    35.93   1.20 │   156895207423    154686099586   1.43 │   212504613587    208706220259   1.82 │  602968   604004  -0.17 │   4    0      nan │
│                coq-bedrock2 │  226.03   222.67   1.51 │   987139001331    973215174547   1.43 │  1800977712862   1768828226731   1.82 │ 2053868  2051996   0.09 │  11   10    10.00 │
│            coq-math-classes │   95.10    92.88   2.39 │   412893466408    403450254877   2.34 │   586624297967    571416871346   2.66 │  502664   502968  -0.06 │   0    0      nan │
│                   coq-verdi │   50.63    49.34   2.61 │   220432549014    213816524709   3.09 │   332052358163    320949082856   3.46 │  843332   837164   0.74 │   0    0      nan │
│                  coq-geocoq │  754.58   726.90   3.81 │  3295371486519   3171154581822   3.92 │  5288379909764   4994926397458   5.88 │ 1075804  1075476   0.03 │  27    7   285.71 │
│              coq-verdi-raft │  608.54   575.68   5.71 │  2659640564146   2514507410268   5.77 │  4202466690088   3905684143949   7.60 │ 1256412  1256144   0.02 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
~~~

**Comment by Alizter** [comment]
btw Gtihub can't render code blocks inside a summary if you don't put a newline after details.

**Comment by Alizter** [comment]
The reason the other one had links in it is because it has links in the log. Your one doesn't have any links.

**Comment by Alizter** [comment]
I suspect its a bug with the gitlab log display updating in real time. The actual log has no links. @ppedrot Can you confirm you copied the table having left the log running in your browser?

**Comment by ppedrot** [comment]
I opened the bench in a fresh window and copied the output. I don't think it's due to some weird interaction with the buffering, rather it's a recent rendering issue that didn't happen before. I agree this is a bit annoying though.

**Pull request closed without merging**
