### PR TITLE
Share computation of unifiable evars

### LINKED ISSUE #6204: `refine` is exponential in the number of fresh evars that it creates
#### Version

8.7.0

#### Operating system

Linux

#### Description of the problem

Consider this script:
```coq
Record Evars
       {T0 T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11 T12 T13 T14 T15 T16 T17 T18 T19 T20 T21 T22 T23 T24 T25 T26 T27 T28 T29 T30 T31 T32 T33 T34 T35 T36 T37 T38 T39 T40 T41 T42 T43 T44 T45 T46 T47 T48 T49 T50 T51 T52 T53 T54 T55 T56 T57 T58 T59 T60 T61 T62 T63 T64 T65 T66 T67 T68 T69 T70 T71 T72 T73 T74 T75 T76 T77 T78 T79 T80 T81 T82 T83 T84 T85 T86 T87 T88 T89 T90 T91 T92 T93 T94 T95 T96 T97 T98 T99 T100 T101 T102 T103 T104 T105 T106 T107 T108 T109 T110 T111 T112 T113 T114 T115 T116 T117 T118 T119 T120 T121 T122 T123 T124 T125 T126 T127 T128 T129 T130 T131 T132 T133 T134 T135 T136 T137 T138 T139 T140 T141 dT0 dT1 dT2 dT3 dT4 dT5 dT6 dT7 dT8 dT9 dT10 dT11 dT12 dT13}
:= {
    v0:T0 ; v1:T1 ; v2:T2 ; v3:T3 ; v4:T4 ; v5:T5 ; v6:T6 ; v7:T7 ; v8:T8 ; v9:T9 ; v10:T10 ; v11:T11 ; v12:T12 ; v13:T13 ; v14:T14 ; v15:T15 ; v16:T16 ; v17:T17 ; v18:T18 ; v19:T19 ; v20:T20 ; v21:T21 ; v22:T22 ; v23:T23 ; v24:T24 ; v25:T25 ; v26:T26 ; v27:T27 ; v28:T28 ; v29:T29 ; v30:T30 ; v31:T31 ; v32:T32 ; v33:T33 ; v34:T34 ; v35:T35 ; v36:T36 ; v37:T37 ; v38:T38 ; v39:T39 ; v40:T40 ; v41:T41 ; v42:T42 ; v43:T43 ; v44:T44 ; v45:T45 ; v46:T46 ; v47:T47 ; v48:T48 ; v49:T49 ; v50:T50 ; v51:T51 ; v52:T52 ; v53:T53 ; v54:T54 ; v55:T55 ; v56:T56 ; v57:T57 ; v58:T58 ; v59:T59 ; v60:T60 ; v61:T61 ; v62:T62 ; v63:T63 ; v64:T64 ; v65:T65 ; v66:T66 ; v67:T67 ; v68:T68 ; v69:T69 ; v70:T70 ; v71:T71 ; v72:T72 ; v73:T73 ; v74:T74 ; v75:T75 ; v76:T76 ; v77:T77 ; v78:T78 ; v79:T79 ; v80:T80 ; v81:T81 ; v82:T82 ; v83:T83 ; v84:T84 ; v85:T85 ; v86:T86 ; v87:T87 ; v88:T88 ; v89:T89 ; v90:T90 ; v91:T91 ; v92:T92 ; v93:T93 ; v94:T94 ; v95:T95 ; v96:T96 ; v97:T97 ; v98:T98 ; v99:T99 ; v100:T100 ; v101:T101 ; v102:T102 ; v103:T103 ; v104:T104 ; v105:T105 ; v106:T106 ; v107:T107 ; v108:T108 ; v109:T109 ; v110:T110 ; v111:T111 ; v112:T112 ; v113:T113 ; v114:T114 ; v115:T115 ; v116:T116 ; v117:T117 ; v118:T118 ; v119:T119 ; v120:T120 ; v121:T121 ; v122:T122 ; v123:T123 ; v124:T124 ; v125:T125 ; v126:T126 ; v127:T127 ; v128:T128 ; v129:T129 ; v130:T130 ; v131:T131 ; v132:T132 ; v133:T133 ; v134:T134 ; v135:T135 ; v136:T136 ; v137:T137 ; v138:T138 ; v139:T139 ; v140:T140 ; v141:T141 ; dv0:dT0 v26 ; dv1:dT1 v33 ; dv2:dT2 v40 ; dv3:dT3 v47 ; dv4:dT4 v54 ; dv5:dT5 v61 ; dv6:dT6 v68 ; dv7:dT7 v87 ; dv8:dT8 v94 ; dv9:dT9 v101 ; dv10:dT10 v108 ; dv11:dT11 v115 ; dv12:dT12 v122 ; dv13:dT13 v129 }.

Goal True.
  Time
    refine (let H0 : Evars -> Prop := _ in
            let H1 : Evars -> Prop := _ in
            let H2 : Evars -> Prop := _ in
            let H3 : Evars -> Prop := _ in
            let H4 : Evars -> Prop := _ in
            let H5 : Evars -> Prop := _ in
            let H6 : Evars -> Prop := _ in
            let H7 : Evars -> Prop := _ in
            let H8 : Evars -> Prop := _ in
            let H9 : Evars -> Prop := _ in
            let H10 : Evars -> Prop := _ in
            let H11 : Evars -> Prop := _ in
            let H12 : Evars -> Prop := _ in
            let H13 : Evars -> Prop := _ in
            let H14 : Evars -> Prop := _ in
            let H15 : Evars -> Prop := _ in
            let H16 : Evars -> Prop := _ in
            let H17 : Evars -> Prop := _ in
            let H18 : Evars -> Prop := _ in
            let H19 : Evars -> Prop := _ in
            let H20 : Evars -> Prop := _ in
            let H21 : Evars -> Prop := _ in
            let H22 : Evars -> Prop := _ in
            let H23 : Evars -> Prop := _ in
            let H24 : Evars -> Prop := _ in
            let H25 : Evars -> Prop := _ in
            let H26 : Evars -> Prop := _ in
            let H27 : Evars -> Prop := _ in
            let H28 : Evars -> Prop := _ in
            let H29 : Evars -> Prop := _ in
            let H30 : Evars -> Prop := _ in
            let H31 : Evars -> Prop := _ in
            let H32 : Evars -> Prop := _ in
            let H33 : Evars -> Prop := _ in
            let H34 : Evars -> Prop := _ in
            let H35 : Evars -> Prop := _ in
            let H36 : Evars -> Prop := _ in
            let H37 : Evars -> Prop := _ in
            let H38 : Evars -> Prop := _ in
            let H39 : Evars -> Prop := _ in
            let H40 : Evars -> Prop := _ in
            let H41 : Evars -> Prop := _ in
            let H42 : Evars -> Prop := _ in
            let H43 : Evars -> Prop := _ in
            let H44 : Evars -> Prop := _ in
            let H45 : Evars -> Prop := _ in
            let H46 : Evars -> Prop := _ in
            let H47 : Evars -> Prop := _ in
            let H48 : Evars -> Prop := _ in
            let H49 : Evars -> Prop := _ in
            let H50 : Evars -> Prop := _ in
            let H51 : Evars -> Prop := _ in
            let H52 : Evars -> Prop := _ in
            let H53 : Evars -> Prop := _ in
            let H54 : Evars -> Prop := _ in
            let H55 : Evars -> Prop := _ in
            let H56 : Evars -> Prop := _ in
            let H57 : Evars -> Prop := _ in
            let H58 : Evars -> Prop := _ in
            let H59 : Evars -> Prop := _ in
            let H60 : Evars -> Prop := _ in
            let H61 : Evars -> Prop := _ in
            let H62 : Evars -> Prop := _ in
            let H63 : Evars -> Prop := _ in
            let H64 : Evars -> Prop := _ in
            let H65 : Evars -> Prop := _ in
            let H66 : Evars -> Prop := _ in
            let H67 : Evars -> Prop := _ in
            let H68 : Evars -> Prop := _ in
            let H69 : Evars -> Prop := _ in
            let H70 : Evars -> Prop := _ in
            let H71 : Evars -> Prop := _ in
            let H72 : Evars -> Prop := _ in
            let H73 : Evars -> Prop := _ in
            let H74 : Evars -> Prop := _ in
            let H75 : Evars -> Prop := _ in
            let H76 : Evars -> Prop := _ in
            let H77 : Evars -> Prop := _ in
            let H78 : Evars -> Prop := _ in
            let H79 : Evars -> Prop := _ in
            let H80 : Evars -> Prop := _ in
            let H81 : Evars -> Prop := _ in
            let H82 : Evars -> Prop := _ in
            let H83 : Evars -> Prop := _ in
            let H84 : Evars -> Prop := _ in
            let H85 : Evars -> Prop := _ in
            let H86 : Evars -> Prop := _ in
            let H87 : Evars -> Prop := _ in
            let H88 : Evars -> Prop := _ in
            let H89 : Evars -> Prop := _ in
            let H90 : Evars -> Prop := _ in
            let H91 : Evars -> Prop := _ in
            let H92 : Evars -> Prop := _ in
            let H93 : Evars -> Prop := _ in
            let H94 : Evars -> Prop := _ in
            let H95 : Evars -> Prop := _ in
            let H96 : Evars -> Prop := _ in
            let H97 : Evars -> Prop := _ in
            let H98 : Evars -> Prop := _ in
            let H99 : Evars -> Prop := _ in
            _).
```
I estimates with 1, 2, 3, and 4 `H`s suggest it will take about 2^99 seconds to run.  replacing the `_`s with appropriate `ltac:(clear H0 ... Hn)` makes it much faster.  Note that each `H : Evars -> Prop` creates about 100 evars.

### PR DESCRIPTION
**Pull request by ppedrot**
This PR fixes #6204 in two orthogonal ways:
- It solves an algorithmic issue in `shelve_unifiable` that made the computation of dependent evars cubic or quartic.
- It defines a fine-grained cache retaining the computation of free evars of a given hypothesis. This is similar in spirit to a previous tentative patch of @psteckler, except that the cache is not stored in the evar map (which can gobble up memory, see e.g. #4547) and that its granularity is at the level of hypotheses, not whole evars. This is done by checking for physical equality of the type of hypotheses. Doing it at the level of evars is not efficient enough to solve #6204.

### CODE REVIEW

**Comment by mattam82** [comment]
This looks great! Actually my assumption that we'd need something similar for typeclasses is wrong. The new proof search engine directly uses ``Proofview.unifiable`` so will benefit from it. It seems ``evar_dependencies`` and ``top_sort`` in class_tactics, that are used to order the set of goals coming from an evar_map (i.e. during type-checking) could also use the optimized ``filtered_undefined`` instead of ``undefined_evars_of..``.

**Comment by maximedenes** [comment]
> It seems evar_dependencies and top_sort in class_tactics, that are used to order the set of goals coming from an evar_map (i.e. during type-checking) could also use the optimized filtered_undefined instead of undefined_evars_of...

@mattam82 Can you open an issue for that so that we don't forget?

**Comment by ppedrot** [comment]
@mattam82 Ping!

**Review by mattam82 — APPROVED** [review]
Sorry, I forgot to add a review but I meant to approve.

**Comment by ppedrot** [comment]
I already performed a benchmark back then:
```
┌──────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                       │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │            NEW            OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-formal-topology │   33.58   34.30 -2.10 % │    93246267703    94478356665 -1.30 % │   124832893991   126880155898 -1.61 % │  482580  482548 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   73.70   75.06 -1.81 % │   205510611830   209035082815 -1.69 % │   280215398949   285221267175 -1.76 % │  535068  535148 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-fiat-crypto │ 3680.19 3720.19 -1.08 % │ 10241944397715 10337753790047 -0.93 % │ 17431799446724 17539744646553 -0.62 % │ 3282612 3282520 +0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-sf-vfa │   18.72   18.90 -0.95 % │    51882958596    52211120443 -0.63 % │    71169145950    71216492183 -0.07 % │  537228  537148 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  566.30  571.60 -0.93 % │  1584704591184  1596002600694 -0.71 % │  1998749010946  2016130464660 -0.86 % │ 1489884 1488072 +0.12 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 2169.00 2186.97 -0.82 % │  6051048959451  6097585071404 -0.76 % │  8827184102157  8891482299291 -0.72 % │ 1952268 1951684 +0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   59.21   59.45 -0.40 % │   163858814786   164133415094 -0.17 % │   229519875997   229611133215 -0.04 % │  530996  531180 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  119.11  119.54 -0.36 % │   315798247451   315598750895 +0.06 % │   424340026648   424138908723 +0.05 % │  503100  502628 +0.09 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  169.24  169.70 -0.27 % │   470393699404   471604030723 -0.26 % │   668826488555   668745662230 +0.01 % │  590344  590216 +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  673.45  675.22 -0.26 % │  1862771918468  1868387722845 -0.30 % │  3032828820777  3029658716335 +0.10 % │ 3524160 3535120 -0.31 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  268.66  269.18 -0.19 % │   747271780839   748850878279 -0.21 % │  1101133084899  1101052595773 +0.01 % │  981820  981676 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-unimath │ 1278.32 1280.63 -0.18 % │  3562154428554  3570299526878 -0.23 % │  6134403787248  6134243602011 +0.00 % │ 1151236 1151152 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1380.20 1382.25 -0.15 % │  3846840237495  3852530906433 -0.15 % │  6710695470685  6704025062598 +0.10 % │ 1121760 1110212 +1.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  452.14  452.67 -0.12 % │  1259505964509  1259765078067 -0.02 % │  2096522398007  2096334576336 +0.01 % │  727632  728424 -0.11 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3107.60 3105.96 +0.05 % │  8657731118044  8656660556570 +0.01 % │ 14332118546796 14317413368033 +0.10 % │ 1251244 1250240 +0.08 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  167.05  166.86 +0.11 % │   464238277524   463607571775 +0.14 % │   712364776837   712386438149 -0.00 % │  731992  732108 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  190.32  190.03 +0.15 % │   528727395357   528737457800 -0.00 % │   769362720651   768374423724 +0.13 % │  716384  714844 +0.22 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-sf-lf │   15.44   15.41 +0.19 % │    42662576777    42777256049 -0.27 % │    59965377449    59976406958 -0.02 % │  418932  419092 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   74.90   74.73 +0.23 % │   206378236491   205876623977 +0.24 % │   259532610271   259542304648 -0.00 % │  661864  662160 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-sf-plf │   42.06   41.86 +0.48 % │   116927037906   116756645807 +0.15 % │   153653982349   153499797858 +0.10 % │  518396  518388 +0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  806.21  801.24 +0.62 % │  2245998306164  2233678892282 +0.55 % │  3409160091269  3415189691290 -0.18 % │ 1387916 1387936 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   38.52   38.14 +1.00 % │   105852136086   105708894129 +0.14 % │   131473780154   131427378753 +0.04 % │  477720  477768 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   58.22   57.58 +1.11 % │   159298617117   158842008925 +0.29 % │   205528222266   205369189844 +0.08 % │  644024  643952 +0.01 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘


PDIFF = proportional difference between measurements done for the NEW and the OLD Coq version
      = (NEW_measurement - OLD_measurement) / OLD_measurement * 100%

NEW = 8eea5a5ecdd33d85e4e7d42408360fff68e04f5d
OLD = d0c42fea9edfef645a822e9f12d475c205f93932

```

**Pull request merged**
