### PR TITLE
[v8.12] Use more tags for Windows add-ons and bump some of them.

### PR DESCRIPTION
**Pull request by Zimmi48**
cc @gares and @MSoegtropIMC

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : did you compare this with (https://github.com/coq/platform/blob/master/coq_platform_packages.sh)? I think we should try to keep these in sync.

**Comment by gares** [comment]
OK for elpi's tags, but I don't see the patch for windows/shasum problem. Should I?

**Comment by MSoegtropIMC** [comment]
> OK for elpi's tags, but I don't see the patch for windows/shasum problem. Should I?

On Windows the previous method of using a different executable did work so your final patch of using OCaml never made it here. I must admit I am fairly lazy these days with maintaining the legacy scripts since I am busy with the platform and in 8.13 the plan is to replace this with the platform.

**Comment by Zimmi48** [comment]
@MSoegtropIMC 
>I think we should try to keep these in sync.

Yes, you are right: I've now checked the list and bumped some tags to be up-to-date with https://github.com/coq/platform/blob/v8.12/coq_platform_packages.sh. The only remaining differences are these two packages which have a more recent release than the one present in the 8.12 platform:
- coq-elpi: 1.6.0
- simple-io: 1.4.0

Is that OK or do you think I should backtrack on these updates?

@gares 
>OK for elpi's tags, but I don't see the patch for windows/shasum problem. Should I?

There was some confusion on my hand on the tags that I used. This PR only updates coq-elpi. Elpi was already updated when backporting #13175 and the Windows patch was added as part of this backport. Cf. https://github.com/coq/coq/blob/v8.12/dev/build/windows/patches_coq/elpi-base.patch

**Comment by MSoegtropIMC** [comment]
@Zimmi48:

> The only remaining differences are these two packages which have a more recent release than the one present in the 8.12 platform:
> 
> * coq-elpi: 1.6.0
> * simple-io: 1.4.0

The sync should of cause be bidirectional - I will update the platform.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 :

coq-hierarchy-builder has in opam:
```
depends: [
  "coq-elpi" {>= "1.5.0" & < "1.6.0~"}
  ]
```
I don't understand how this works ...

**Comment by MSoegtropIMC** [comment]
@gares : can you please comment on if hierarchy builder 0.10 is - despite what the opam file says - compatible with coq-elpi 1.6? If so, how should the opam file be changed? to `< "1.7.0~"`? The Windows build seems to pass.

**Comment by MSoegtropIMC** [comment]
On Mac I get for elpi 1.6.0 in a coq platform v8.12 branch context:
```
#=== ERROR while compiling coq-elpi.1.6.0 =====================================#
# context              2.0.7 | macos/x86_64 | ocaml-base-compiler.4.07.1 | https://coq.inria.fr/opam/released#2020-10-20 15:00
# path                 ~/.opam/_coq-platform_.8.12.0+beta1/.opam-switch/build/coq-elpi.1.6.0
# command              ~/.opam/opam-init/hooks/sandbox.sh build make COQBIN=/Users/msoegtrop/.opam/_coq-platform_.8.12.0+beta1/bin/ ELPIDIR=/Users/msoegtrop/.opam/_coq-platform_.8.12.0+beta1/lib/elpi
# exit-code            2
# env-file             ~/.opam/log/coq-elpi-7428-2913ab.env
# output-file          ~/.opam/log/coq-elpi-7428-2913ab.out
### output ###
# [...]
# File "./coq-lib.elpi", line 262, characters -32-200:
# Warning: constant coq.elaborate-ty-skeleton has no declared type. [lib,elpi]
# COQC theories/examples/example_usage_derive.v
# nat_eq_OK
#      : forall s1 : nat, eq_axiom_at nat nat_eq s1
# File "./theories/examples/example_usage_derive.v", line 13, characters 0-67:
# Error: elpi: Inductive type declaration illtyped: no diagnostic returned
```

**Comment by Zimmi48** [comment]
Thanks for investigating @MSoegtropIMC. Maybe I should have waited before merging this PR. Let me know @gares if this is something I should revert...

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : `simple-io: 1.4.0` works fine btw, but elpi-1.6.0 has two issues, the opam file for hierarchy-builder and that it doesn't compile (at least in some cases).

**Comment by MSoegtropIMC** [comment]
P.S.: I just checked if `coq-elpi-1.5.1` still works and it does.

**Comment by Zimmi48** [comment]
@gares I need to take a decision whether to revert to coq-elpi-1.5.1 or to keep coq-elpi-1.6.0 with some real hope that it will be fixed to also work with the platform.

**Comment by ejgallego** [comment]
Note that I think that `< 1.6` is preferred to `< 1.6.0~`

**Comment by gares** [comment]
I think I've seen this problem. Do you have coq-elpi.1.5.x installed in the switch (or available somewhere?).
Try `find ... -name coq-builtin.elpi`. I suspect it finds an old version of this file.

**Comment by gares** [comment]
[coq-hierarchy-builder] I believe we have no release that works with 1.6.0, my bad. We hope to release HB 1.0 soon, in a couple of week max, and that will depend on coq-elpi 1.6.0. So, I guess you have to stay with 1.5.1 + 0.10 for now.

**Comment by Zimmi48** [comment]
OK to revert to 1.5.1, but I'm surprised that the CI didn't detect this incompatibility.

**Comment by MSoegtropIMC** [comment]
> OK to revert to 1.5.1, but I'm surprised that the CI didn't detect this incompatibility.

This is indeed strange - I reviewed the tests in 8.12 and agree that CI should have flagged this.

Anyway - the consensus is to revert to 1.5.1 and 0.10 here and in Coq platform 8.12?

**Comment by Zimmi48** [comment]
>Anyway - the consensus is to revert to 1.5.1 and 0.10 here and in Coq platform 8.12?

Yes, at least for now.

**Pull request merged**
