### PR TITLE
[coq_makefile] COQMF_WINDRIVE is empty on linux (fix #7233)

### LINKED ISSUE #7233: Makefile.coq generates bad COQLIBINSTALL when DESTDIR set
#### Version

The Coq Proof Assistant, version 8.7.2 (February 2018)
compiled on Feb 16 2018 8:50:49 with OCaml 4.06.0

#### Operating system

Arch Linux

#### Description of the problem

When `DESTDIR` is set, `concat_path` causes `COQLIBINSTALL` to equal `$(DESTDIR)/user-contrib`, instead of `$(DESTDIR)/$(COQLIB)/user-contrib`. My current workaround is to set `COQMF_WINDRIVE` to the empty string in `Makefile.coq.local`.

 I believe the problem is in the definition of `concat_path`, or in the function `windrive` in `coq_makefile`.

```makefile
concat_path = $(if $(1),$(1)/$(subst $(COQMF_WINDRIVE),/,$(2)),$(2))

COQLIBINSTALL = $(call concat_path,$(DESTDIR),$(COQLIB)user-contrib) 
```

`COQMF_WINDRIVE` is set to the same path (/usr/lib/coq) as `COQLIB` on my system (Arch Linux)  due to the definition of the `windrive` function in `coq_makefile`. So, `concat_path` removes `COQLIB` from the install path, when trying to remove `COQMF_WINDRIVE`.

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
It was tested by the author of the bugreport, and it works.

**Comment by maximedenes** [comment]
@silene if you can have a quick look at this and merge this morning, it could make it into 8.8.0, since it is a very small fix.

**Comment by maximedenes** [comment]
No reviews, so postponing to 8.8.1.

**Comment by gares** [comment]
Ping

**Comment by gares** [comment]
@silene any time for this one?

**Comment by Zimmi48** [comment]
@silene ping

**Comment by gares** [comment]
@JasonGross can you have a look at this PR wrt your bugreport #7740

**Comment by gares** [comment]
@Zimmi48 would you mind taking this one?

**Review by SkySkimmer — COMMENTED** [review]
A review was requested from me but I have no clue what this WINDRIVE stuff is.

**Comment by Zimmi48** [comment]
I'm sorry but I don't feel competent to review this. Can someone call @silene on the phone or send him an e-mail? I've no idea who else could review this. Maybe @JasonGross.
@maximedenes We could have a policy for self-merging when everyone other than the PR author is clueless or unresponsive...

**Review by JasonGross — APPROVED** [review]
This fixes #7740 (and I'd be willing to close #7722 with #7740 in light of this, if this gets merged).  I approve this change for how the code works on Linux.

Perhaps a review of @MSoegtropIMC makes sense, as a main consumer of Coq on Windows?

**Comment by JasonGross** [comment]
Though perhaps it makes sense to update the PR title and commit message to indicate that the new state is that `COQMF_WINDRIVE` is empty on Linux (e.g., replace "is" with "should be" or "is now"); it wasn't clear to me whether the title meant "`COQMF_WINDRIVE` is empty on Linux, this is a problem, this PR fixes that" or "`COQMF_WINDRIVE` should be empty on Linux; this PR makes that happen").

**Comment by MSoegtropIMC** [comment]
@JasonGross : not sure I understand this. Was this an issue on Linux or Windows? At least in the past the installation of docs to absolute paths did work on Windows.

**Comment by wilbowma** [comment]
This was an issue that occurs when building on Linux (see also: #7233)

**Comment by JasonGross** [comment]
@MSoegtropIMC This was an issue with passing `DESTDIR` to `coq_makefile`-based projects on Linux.  I do not know what the semantics of passing `DESTDIR` should be on Windows, and I do not know whether or not things currently work correctly on Windows.  If using `DESTDIR` works correctly on Windows, then this PR seems good.  If using `DESTDIR` doesn't work correctly on Windows, then I wonder why we bother with `COQMF_WINDRIVE` in the first place.

**Comment by gares** [comment]
I think we should give a few days to Michael but not delay for another 2 months this silly patch.
@Zimmi48 I wanted you to get assigned the PR, not necessarily making the review (we now have one BTW, thanks to @JasonGross).

**Comment by gares** [comment]
The issue should affect only Linux, and this fix should change things only on Linux (see the .ml file, I edited the else branch of the if).

**Comment by Zimmi48** [comment]
OK

**Comment by MSoegtropIMC** [comment]
@JasonGross : I see. I must admit I don't have a current overview over what works and what not with coq_makefile on Windows. I am (from time to time) working on making coq_makefile work without bash / cygwin. Before this works, it is of little use for me (I currently write the makefiles manually).

**Comment by Zimmi48** [comment]
We have users of coq_makefile on Windows though (pretty much any plugin or library that one might want to install, including bignums that is now shipped in the Windows package)...

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : well but this is not really Windows, it is cygwin which in this respect should be treated like Linux. I think the Windows path "hacks" we are discussing here are not used in the build process of bignums as we build it in the official delivery.

As far as I can tell on real Windows (MinGW) this doesn't work unless you use a cygwin make/bash which makes it non Windows again. The way I want to fix this is by exchanging the OCaml system function which something which is Posix compliant for the cases which occur in practice. But as is, at least for me, this doesn't really work and all I could do in a review is judging if this changes it from 35% working to 37% working or 33% working.

Of cause it can also be that I got a bit lost in the Windows / cygwin universe - it is definitely a bit more complex than the situation under Linux.

**Comment by Zimmi48** [comment]
> I think the Windows path "hacks" we are discussing here are not used in the build process of bignums as we build it in the official delivery.

@gares Can you comment on this?

**Comment by gares** [comment]
I think the hack was put in place to support `make install DESTDIR=tmp/` on windows.
Unfortunately some paths on windows (even if we are using cygwin) are of the form `c:/foo/bar` (IIRC it is the case even today using Michael's scripts). So to generate the path `tmp/foo/bar` one has to first strip `c:`.

I don't think we use a non empty `DESTDIR` on today's scripts. But I think we do use this feature in the `test-suite`.

But again, this PR should not change the behavior on windows, it is only fixing the fact that, on Linux, such variable should be empty (there is nothing to strip, you can just concatenate the two paths to honor DESTDIR).

**Comment by Zimmi48** [comment]
The test-suite is still run on Windows using AppVeyor as of today. It would be interesting to remove this hack to confirm that this breaks the test-suite.

In any case, I'll merge this PR tomorrow.

**Comment by MSoegtropIMC** [comment]
Let me summarize my understanding of what we are discussing:

* We are discussing make files generated by coq_makefile, not the makefile(s) of coq as such.
* I assume the makefile for the bignum module is generated using coq_makefile, otherwise I don't understand how bignum is related to coq_makefile.
* The generation of the bignum makefile appears to be outside of the build process, since the build instructions for bignum just get sources and call make, so changing something and testing the build probably doesn't test any behavior of coq_makefile.
* The make install for bignum is called without further parameters in the build, which would be another reason why changing something and running the build probably doesn't prove much.

Would you agree to this assessment and conclusions?

**Comment by Zimmi48** [comment]
> The generation of the bignum makefile appears to be outside of the build process, since the build instructions for bignum just get sources and call make, so changing something and testing the build probably doesn't test any behavior of coq_makefile.

Running `make` triggers `coq_makefile`: https://github.com/coq/bignums/blob/master/Makefile

> The make install for bignum is called without further parameters in the build, which would be another reason why changing something and running the build probably doesn't prove much.

:+1:

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : thanks, getting closer ;-)

One more question: how does the bignum make install know where to put things? In CI installer builds, the Coq install folder is outside of the cygwin folder structure - or at least not at the default location, and somehow this seems to work.

**Comment by gares** [comment]
> One more question: how does the bignum make install know where to put things? In CI installer builds, the Coq install folder is outside of the cygwin folder structure - or at least not at the default location, and somehow this seems to work.

`coq_makefile` uses the value of `-prefix` passed to Coq's `./configure` (eventually prefixed by value of the DESTDIR variable, if set). That is, projects built with coq_makefile do install in the same directory of coq, more specifically in the user-contrib subdirectory.

**Comment by gares** [comment]
> Coq install folder is outside of the cygwin folder structure

Here I've two things to say:
- cygwin understands many paths, including `c:/coq_install` and the `WINDRIVE` variable this PR fixes is to deal with it
- cygwin can also point to the same directory via `/cygdrive/c/coq_install` that would be a Unix path

Now that I write that we could, on windows, `./configure -prefix .` and then `make install DESTDIR=/cygdrive/c/coq_install` (without re-configuring Coq, that, IIRC, we do just before running make install)

**Comment by MSoegtropIMC** [comment]
@gares : 
> Now that I write that I realize we could, on windows, ./configure -prefix . and then make install DESTDIR=/cygdrive/c/coq_install (without re-configuring Coq, that, IIRC, we do just before running make install)

One has to be very careful with this. The built Coq and tools are MinGW and MinGW binaries don't understand /cygdrive/c/... nor do they understand cygwin paths like /usr/lib. But MinGW binaries do understand / instead of \\, actually as I later found out every Windows binary does.

But that's the reason why in my build I have Windows, MinGW and cygwin variants of all path variables. Windows is C:\\path, MinGW is C:/path and cygwin is /cygdrive/c/path.

The reconfigure is done to switch from a build with absolute paths to a build with relative paths, which can then be moved to any other path (this is what the installer does).

**Comment by MSoegtropIMC** [comment]
P.S.: this relative reconfigure thing is really a hack, but it works ;-)

**Comment by gares** [comment]
> The reconfigure is done to switch from a build with absolute paths to a build with relative paths, which can then be moved to any other path (this is what the installer does).

I'm sorry I was not very clear, and it was a bit off topic here.

What I think is possible to do in the windows build script is to (up to minor details):
```
./configure -prefix ./
make
make install COQINSTALLPREFIX=/cygdrive/c/coq_install
```
rather than
```
./configure -prefix ./
make
./configure -prefix /cygdrive/c/coq_install
make install
```
I did not test it, but it should work.

The variable `COQINSTALLPREFIX` is not named in a standard way, but plays the role of the standard `DESTDIR` variable supported by the majority of build systems (coq_makefile included). This is why this idea come up, sorry if my brain jumped "du coq à l'âne" :-).

FTR `DESTDIR` is used by linux distributions to `./configure -prefix /usr` but install in `/tmp/pkg-being-built`.
So it would not be an hack to use it in the windows build, while re-configuring Coq is more surprising to me.

**Comment by Zimmi48** [comment]
As announced, I'll merge today. Unless @silene wants to take over...

**Comment by MSoegtropIMC** [comment]
@gares :

```
./configure -prefix ./
make
make install COQINSTALLPREFIX=/cygdrive/c/coq_install
```
This should indeed work and is not a hack as the current solution. Please open an issue for it and assign it to me.

@Zimmi48 , @JasonGross : I have no objections against this change but I cannot test it right now.

**Pull request merged**
