### PR TITLE
Use new coqrst syntax for alternatives in SSReflect chapter.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

@gares Please review that this is correct. In particular I have doubts about the definition of `i_view` (is `{}` specific to the first kind of view?), the definition of `r_pattern`.

On top of #10187 to avoid conflicts. Please review only the last commit.

### CODE REVIEW

**Comment by gares** [comment]
You are right about the clear switch. I'll check the rest later

**Comment by cpitclaudel** [comment]
This LGTM, but I don't know enough about the SSReflecct syntax to give it the thumbs up. Thanks for porting this part.

**Review by gares — APPROVED** [review]

**Comment by Zimmi48** [comment]
@gares I think it would make sense for you to merge this one.

**Comment by gares** [comment]
I left my office, assign me and I'll do it on Monday

**Pull request merged**
