### PR TITLE
Backport PR #7798: Remove hack skipping comparison of algebraic universes in subtyping.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks! There are only 3 commits instead of 4. I guess that's wanted.

**Comment by SkySkimmer** [comment]
I just ran the cherry-pick you gave me on gitter.

**Comment by Zimmi48** [comment]
Arf, it seems I didn't copy the right commits then...

**Comment by Zimmi48** [comment]
Sorry, I guess it should have been:
`git cherry-pick -x 6715e6801c1d285a12eeca55dd8b831d7efb8c0d..1311a2bf08ac1deb16f0b3064bc1164d75858a97`

**Comment by SkySkimmer** [comment]
Added the commit.

**Comment by Zimmi48** [comment]
It seems like this is breaking the test-suite :confused:

**Comment by SkySkimmer** [comment]
Should be fixed.

**Comment by Zimmi48** [comment]
Thanks!

**Comment by herbelin** [comment]
@zimmi48: will you backport to 8.7? (And possibly further in time?)

I did not get exactly from when the bug holds. From template polymorphism, from universe polymorphism?

**Comment by Zimmi48** [comment]
@herbelin It is my intention to backport this and the other recent critical bug fixes to older branches. However, I must first backport recent changes in CI as well, so this is not as high in my TODO list as releasing 8.8.1.

**Pull request merged**
