### PR TITLE
Fix calling conversion with wrong mode in case inversion

### LINKED ISSUE #16226: Insufficient conversion in case inversion (UIP mode)
~~~coq
Inductive sBool : SProp := strue | sfalse.

Set Definitional UIP.

Inductive seq {A:SProp} (a:A) : A -> SProp := srefl : seq a a.
Arguments srefl {_ _}, {_} _.

Definition x (b:bool) := if b then strue else sfalse.

Definition proof : seq (x true) (x false) := srefl.

Record Box (A:SProp) : Prop := box { unbox : A }.
Arguments box {_}.

Definition foo :=
  match proof return SProp with
  | srefl _ => nat -> seq x x
  end.

Definition bla (f:foo) := f 0.
(* Error: Illegal application (Non-functional construction) *)
~~~
We need to call with Conversion mode here https://github.com/coq/coq/blob/e5f033432386bc0c8168858c2d9281c2790a23f6/kernel/cClosure.ml#L1557

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16226

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Maybe we could even tweak the type of the callback not to take a full-blown info but rebuild it instead from Reduction.

**Comment by ppedrot** [comment]
Oh, actually it's explained in the commit message of f3aa5579c36223c98968c82545500340d76b5378.

**Comment by SkySkimmer** [comment]
Did we ever have a test for whatever issue that's supposed to cause?

**Comment by ppedrot** [comment]
I think that the previous code mentioned some legendary example from @ggonthier where this led to an incompleteness of the algorithm, but I've personally never seen it.

**Comment by ppedrot** [comment]
Let's merge anyways, the current PR doesn't make it worse and fixes an issue.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
