### PR TITLE
Enforce that stm options are accessed after they are initialized

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
ping @coq/stm-maintainers

**Comment by ppedrot** [comment]
Given the lack of reaction and the reasonableness of this change, I'm assigning and will merge soon if nobody complains.

**Review by ppedrot — APPROVED** [review]

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer can you rebase to get a clean CI, just in case?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
