### PR TITLE
miscelaneous commits

### PR DESCRIPTION
**Pull request by ghost**
Several, mutually unrelated, commits.

### CODE REVIEW

**Comment by herbelin** [comment]
Fine to me.

**Comment by ejgallego** [comment]
Well, I do have an issue with the commit number and naming, this approach seems a bit noisy to me wrt history, WDYOT?

**Comment by matejkosik** [comment]
@ejgallego : number : maybe they are numerous but does that matter? The commits are unrelated, squashing them together is a trivial operation that I can do, but I haven't seen any advantage, only downsides. E.g. for the purposes of bisecting, it is more advantageous to have finer commits than coarser ones. That's said, I'll happily squash them if they would seem to alien to the rest of the team.

@ejgallego : naming : I've changed commit message for the two commits originally named as `trivial` (which did did not convey too much information).

**Comment by ejgallego** [comment]
The logs look much better now, thanks!

**Pull request closed without merging**
