### PR TITLE
Remove himsg.pr_puniverses, use @{} for universe printing in errors

### PR DESCRIPTION
**Pull request by SkySkimmer**
Replaces #6401.

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
Looks good, thanks!

**Comment by maximedenes** [comment]
@SkySkimmer can you provide an overlay?

**Comment by SkySkimmer** [comment]
See https://github.com/mattam82/Coq-Equations/pull/126

**Comment by SkySkimmer** [comment]
@maximedenes @herbelin ping

**Comment by SkySkimmer** [comment]
@mattam82 also ping

**Comment by maximedenes** [comment]
@SkySkimmer why ping me?

**Comment by SkySkimmer** [comment]
I was quickly looking at the reviewer list.

**Comment by Zimmi48** [comment]
For some weird reason, your Equation overlay seems to be broken on Windows.

**Comment by SkySkimmer** [comment]
That's that thing where it doesn't understand a trailing .git.

**Review by herbelin — COMMENTED** [review]
I did not follow the recent changes on universes so doing a proper review who takes some time. But it seems that the discussion on #6401 had converged so I guess it is mostly to @mattam82 to validate. (But I can be assignee if @mattam82 has no time for merging.)

**Comment by ppedrot** [comment]
@SkySkimmer Can you rebase?

@mattam82 this patch is simple enough, if you don't comment on this PR soon I'll take the liberty to merge it whatsoever.

**Pull request merged**
