### PR TITLE
Use named_context_val for fast lookup in intern named reference

### PR DESCRIPTION
**Pull request by SkySkimmer**
See #9582

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/640/console
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬──────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │        mem faults        │
│                        │                         │                                             │                                             │                               │                          │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │     NEW    OLD   PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-ssreflect │   38.71   39.10 -1.00 % │      107281041770      107522295550 -0.22 % │      128108172659      128143516746 -0.03 % │     523328     523264 +0.01 % │      85     10 +750.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-bignums │   69.86   70.49 -0.89 % │      194554291709      195313995179 -0.39 % │      257317734059      257399821608 -0.03 % │     524444     524508 -0.01 % │     182    192   -5.21 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-odd-order │ 1370.83 1380.88 -0.73 % │     3821310487887     3849282776681 -0.73 % │     6373612628538     6373947097792 -0.01 % │    1358960    1359016 -0.00 % │      54    115  -53.04 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-unimath │ 1943.94 1952.50 -0.44 % │     5415565489418     5437465274179 -0.40 % │     9433044461411     9434274717535 -0.01 % │     956492     956140 +0.04 % │     527    204 +158.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│  coq-mathcomp-fingroup │   54.42   54.61 -0.35 % │      151738312255      152510844017 -0.51 % │      197933912327      197908399771 +0.01 % │     573144     574600 -0.25 % │       5      6  -16.67 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│     coq-mathcomp-field │  220.24  220.90 -0.30 % │      614055847740      615121602553 -0.17 % │      891348258225      891426578129 -0.01 % │     745452     745660 -0.03 % │      10      2 +400.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│         coq-verdi-raft │ 1371.52 1375.38 -0.28 % │     3826816749733     3836437987864 -0.25 % │     5247726325992     5247759909956 -0.00 % │    1801444    1801280 +0.01 % │       0      0    +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-character │  250.08  250.72 -0.26 % │      696864035587      698753777411 -0.27 % │      963353057935      963330240797 +0.00 % │    1060764    1052044 +0.83 % │     118     13 +807.69 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-corn │ 1491.61 1495.28 -0.25 % │     4162959718202     4174570298827 -0.28 % │     6173921713662     6173914375702 +0.00 % │     854872     854948 -0.01 % │       1      1   +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│  coq-mathcomp-solvable │  190.60  191.04 -0.23 % │      531355237862      531929004748 -0.11 % │      711681108722      711705819197 -0.00 % │     842964     837488 +0.65 % │      11     78  -85.90 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│   coq-mathcomp-algebra │  151.93  152.22 -0.19 % │      423519152815      424803481449 -0.30 % │      534623975096      534582119991 +0.01 % │     633584     633736 -0.02 % │      16      5 +220.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-math-classes │  216.94  217.34 -0.18 % │      606850056020      607058515140 -0.03 % │      769044803614      769052599272 -0.00 % │     516352     516256 +0.02 % │      53     20 +165.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-verdi │  123.48  123.70 -0.18 % │      343226706214      343849596289 -0.18 % │      443672012321      443711145975 -0.01 % │     606468     606244 +0.04 % │      10      4 +150.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│                coq-vst │ 3033.75 3036.64 -0.10 % │     8454695139602     8464382036021 -0.11 % │    11831977413262    11832094169143 -0.00 % │    1926020    1926004 +0.00 % │     291    547  -46.80 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-color │  687.47  687.30 +0.02 % │     1921967362470     1920564032192 +0.07 % │     2296418009347     2296519098162 -0.00 % │    1384592    1377224 +0.53 % │     211    152  +38.82 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│    coq-formal-topology │   29.94   29.92 +0.07 % │       82434332936       82603269548 -0.20 % │      107831294817      107829551890 +0.00 % │     467420     467512 -0.02 % │      24      3 +700.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│         coq-coquelicot │   74.48   74.43 +0.07 % │      204434620019      204311854279 +0.06 % │      245784588677      245819842431 -0.01 % │     690072     690108 -0.01 % │     213     11 +1836.36 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-sf-plf │   43.48   43.44 +0.09 % │      121479207618      121391877701 +0.07 % │      153708804410      153697546249 +0.01 % │     499708     499644 +0.01 % │      43      0    +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-lambda-rust │ 2073.57 2070.99 +0.12 % │     5777415622317     5772958686447 +0.08 % │     7939477695904     7947085867386 -0.10 % │    1387108    1371216 +1.16 % │      47      0    +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-fiat-parsers │  694.11  693.22 +0.13 % │     1942128966641     1936929643913 +0.27 % │     2960475792863     2960142528900 +0.01 % │    2852520    2871108 -0.65 % │     228    695  -67.19 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-geocoq │ 2005.87 2002.04 +0.19 % │     5595619227900     5586589035726 +0.16 % │     8104205027011     8104352224922 -0.00 % │    1246164    1246076 +0.01 % │     479    301  +59.14 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│          coq-fiat-core │  106.32  106.03 +0.27 % │      301945523625      301613829599 +0.11 % │      376531482710      376516444274 +0.00 % │     479120     479044 +0.02 % │     425    208 +104.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-hott │  338.53  337.14 +0.41 % │      916235657618      916832120537 -0.07 % │     1397458979539     1397540923107 -0.01 % │     479156     479100 +0.01 % │     457    255  +79.22 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-fiat-crypto │ 3904.87 3867.51 +0.97 % │    10840533008412    10746220657228 +0.88 % │    17250608318541    17249266057600 +0.01 % │    2560284    2465060 +3.86 % │    1139    794  +43.45 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-flocq │  568.10  562.43 +1.01 % │     1580952327498     1565170996244 +1.01 % │     2286291915566     2286205513816 +0.00 % │    1718096    1718096 +0.00 % │     295    389  -24.16 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│           coq-compcert │ 1029.84 1010.64 +1.90 % │     2870036518236     2815375609895 +1.94 % │     4374752456652     4375001032511 -0.01 % │    1299036    1298996 +0.00 % │     333    313   +6.39 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴──────────────────────────┘

```

**Review by herbelin — APPROVED** [review]
:+1:

**Comment by SkySkimmer** [comment]
@herbelin will you assign?

**Comment by ejgallego** [comment]
Assigning as per-inaction. Running a bench on the two worst devs tho, the slowdown seems a bit higher than noise: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/651/

**Comment by SkySkimmer** [comment]
~~~
┌──────────────┬─────────────────────────┬───────────────────────────────────────────┬───────────────────────────────────────────┬───────────────────────────────┬────────────────────────┐
│              │      user time [s]      │                CPU cycles                 │             CPU instructions              │     max resident mem [KB]     │       mem faults       │
│              │                         │                                           │                                           │                               │                        │
│ package_name │     NEW     OLD PDIFF   │              NEW              OLD PDIFF   │              NEW              OLD PDIFF   │        NEW        OLD PDIFF   │    NEW    OLD  PDIFF   │
├──────────────┼─────────────────────────┼───────────────────────────────────────────┼───────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│    coq-flocq │  570.25  562.80 +1.32 % │    1584780317242    1566589302203 +1.16 % │    2287661320883    2287713240824 -0.00 % │    1718056    1718124 -0.00 % │    552    346 +59.54 % │
├──────────────┼─────────────────────────┼───────────────────────────────────────────┼───────────────────────────────────────────┼───────────────────────────────┼────────────────────────┤
│ coq-compcert │ 1028.74 1010.75 +1.78 % │    2864439965730    2814202617236 +1.79 % │    4369496192566    4369597017304 -0.00 % │    1301088    1301056 +0.00 % │    196    252 -22.22 % │
└──────────────┴─────────────────────────┴───────────────────────────────────────────┴───────────────────────────────────────────┴───────────────────────────────┴────────────────────────┘
~~~
cursed incomprehensible perf gods

**Comment by ppedrot** [comment]
It's very suspicious that *internalization* causes a slowdown, this should not appear on the dynamics. Maybe some crazy tactic codepath is causing the trouble. Can you get more precise timing diffs?

**Comment by ppedrot** [comment]
> Can you get more precise timing diffs?

Answering to myself to rant: gee, those two developments are not using the standard TIME interface for per-line timing. Seriously.

**Comment by SkySkimmer** [comment]
Let's try something dumb.

**Comment by ejgallego** [comment]
> It's very suspicious that _internalization_ causes a slowdown, this should not appear on the dynamics. Maybe some crazy tactic codepath is causing the trouble. Can you get more precise timing diffs?

internalization is _super_ heavy @ppedrot , when we refactored some evar_map handling [mainly removing references and barriers] we got a 3% speedup on some devs!

Indeed I cannot explain why, but there is evidence for it impacting build time.

Resurrecting a per-pass profile should be a top priority of the engineering team.

**Comment by ejgallego** [comment]
Uh, I dunno what to do, this is not something to take lightly...

Note that a part of the slowdown in compcert could be due to Flocq itself.

**Comment by ejgallego** [comment]
So @SkySkimmer @ppedrot what to do here?

**Comment by ejgallego** [comment]
Ping @ppedrot @SkySkimmer ; I am undecided myself, but if we take no action we can just close the PR.

**Comment by ppedrot** [comment]
I'd still favour merging, it's better to be 1.5% slower but not quadratic.

**Comment by JasonGross** [comment]
I am strongly in favor of merging this.

**Comment by ppedrot** [comment]
@SkySkimmer At worst if you want to mitigate the slowdown, you can call the linear fetch below some length threshold. You can get the height of a map in `O(1)`.

**Comment by ejgallego** [comment]
Ok, so merging this then, given the low risk of conflict, I'll leave a few days in case anyone wants to comment as this is not trouble-free; maybe Gaëtan would like to try the threshold tho [not sure it is going to help tho].

**Pull request merged**
