### PR TITLE
[build] Remove binary code signing for OSX

### PR DESCRIPTION
**Pull request by ejgallego**
This is just an experiment, not to be merged.

### CODE REVIEW

**Comment by ejgallego** [comment]
Packages were build on Travis, we need signing.

**Comment by ejgallego** [comment]
We could also push a temporal branch for testing?

**Comment by ejgallego** [comment]
Adding @maximedenes to the reviewers as he's the only who know about packages.

**Comment by ejgallego** [comment]
How can we make progress on this?

**Comment by ejgallego** [comment]
Not at all, just trying to figure out a plan.

**Comment by ejgallego** [comment]
Maybe some Mac user could test this.

**Review by maximedenes — CHANGES_REQUESTED** [review]
Needs to be tested before we can say anything.

**Review by gares — COMMENTED** [review]
The change to the makefile are sound.
I've no idea of what the absence of a signature on the binary implies on OSX.

**Comment by ejgallego** [comment]
I am doing a last rebase of this PR, but orphaning. I don't need it neither I have to means to test it, if I ever get involved with binary signing in OSX is because Dune will natively support it.

**Comment by ejgallego** [comment]
Orphaning == will close in a few weeks if nobody takes over.

**Pull request closed without merging**
