### PR TITLE
Remove travis

### LINKED ISSUE #6059: MacOS tests on Travis sometimes fail.
The MacOS test-suite Travis build sometimes fail with something along the following lines:

```
/bin/sh: /bin/sh: cannot execute binary file
make[2]: *** [bugs/closed/1519.v.log] Error 126
make[2]: *** Waiting for unfinished jobs....
make[2]: *** wait: No child processes.  Stop.
make[1]: *** [test-suite] Error 2
make: *** [submake] Error 2
/Users/travis/.travis/job_stages: line 57: shell_session_update: command not found
```

This trace is from a [failed build](https://travis-ci.org/coq/coq/jobs/295768247) on 2017-11-01.

My understanding is that the last line can be ignored (such lines also show after successful builds, and we avoid any problems with them by resetting `set +e` at the end of the Travis script). The really problematic line seems to be the first one.

This issue generally occurs in the middle of the test-suite run, e.g. on the above example the test had run for 18 minutes.

### LINKED ISSUE #9090: Travis macOS packaging job currently failing with timeout.
The packaging job was already very close to the timeout limit but since 22 hours ago, all the jobs have been going over this time limit. I expect this isn't specific to the master branch (but is due to changes on Travis's side), and if that's the case, it means that the 8.9.0 release could be affected by this (unless it is build and not just signed on a VM). @vbgl @maximedenes What is the status of #7501?

### PR DESCRIPTION
**Pull request by SkySkimmer**
The azure OSX job replaces the first travis job, and the second always
fails and so is useless.

Closes #6059
Closes #9090

### CODE REVIEW

**Comment by maximedenes** [comment]
Can you remind us what the second job is?

**Comment by SkySkimmer** [comment]
Some packaging thing which doesn't run on PRs. I have no clue what packaging does.

**Comment by ejgallego** [comment]
I am powerless on the OSX jobs, I'll leave that to the OSX packagers.

**Comment by MSoegtropIMC** [comment]
Changes on my files (makecoq_mingw.sh) are fine in case Travis is removed.

As maintainer of the Windows build I would say that travis doesn't serve a useful purpose for the Windows build and that I would appreciate the CI simplification resulting from removing travis. But this is a subjective view and I can't comment on the general usefulness of Travis.

**Comment by Zimmi48** [comment]
This will close #9090. However, but let's not forget that until it is ported to Azure, this means that we don't have a macOS packaging build anymore.

**Review by Zimmi48 — APPROVED** [review]

**Comment by ejgallego** [comment]
Note that Travis also has windows support these days, however as noted by Gaetan we get less workers.

**Comment by Zimmi48** [comment]
Just do it.
The packaging issue should be tracked somewhere else. It has not been working correctly on Travis for the last two months.

**Comment by vbgl** [comment]
Indeed. Let me open a new issue.

**Review by vbgl — APPROVED** [review]

**Pull request merged**
