### PR TITLE
[gramlib] Refactor gramlib interface.

### PR DESCRIPTION
**Pull request by ejgallego**
This is in preparation for making the Gramlib interface the canonical
one; see #11647 .

I tried to implement some of the ideas that were floated around in a
chat with Pierre-Marie, suggestions / comments are welcome.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ok let me know what you think of this @ppedrot then I'll make #11714 to sit on this, adding an entry compat interface.

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by ejgallego** [comment]
> LGTM.

You don't want to assign too? @herbelin any comment here?

**Comment by ppedrot** [comment]
Will leave a bit of time to comment.

**Comment by herbelin** [comment]
I don't have a lot of time to look at it. It is OK to me.

**Comment by ejgallego** [comment]
Thanks Pierre-Marie

**Pull request merged**
