### PR TITLE
Dockerfile: update menhir version

### PR DESCRIPTION
**Pull request by SkySkimmer**
Compcert needs a new menhir.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This doesn't actually work as we get an error in compcert: https://gitlab.com/SkySkimmer/coq/-/jobs/246416596
~~~
COQC MenhirLib/Validator_complete.v
File "./MenhirLib/Validator_safe.v", line 187, characters 37-43:
Error: The reference state0 was not found in the current environment.
~~~
I don't know if this is a Coq regression or something else.

cc @xavierleroy

**Comment by ejgallego** [comment]
What happened is a race condition with the name of docker image, you are using the one featuring OCaml 4.08

**Comment by ejgallego** [comment]
Pushed with a fixed tag.

**Comment by ejgallego** [comment]
Well actually that didn't help, indeed the bad code is here:
```
Instance impl_is_state_valid_after_pop_is_validator state sl pl P b :
  IsValidator P b ->
  IsValidator (state_valid_after_pop state sl pl -> P)
              (if is_state_valid_after_pop state sl pl then b else true).
Proof.
  destruct (is_state_valid_after_pop state0 sl pl) eqn:EQ.
  - intros ??. auto using is_validator.
  - intros _ _ Hsvap. exfalso. induction Hsvap=>//; [simpl in EQ; congruence|].
    by destruct sl.
Qed.
```
in master the `state` parameter is not renamed to `state0` anymore to avoid a clash with `A.state`; I remember seeing a discussion over a bug in that area.

A backward compatible [but not optimal] fix is:
```
 destruct (is_state_valid_after_pop _ sl pl) eqn:EQ.
```
or just not use instance like this, but prove the lemma separately.

**Comment by ejgallego** [comment]
Also just renaming state would work.

**Comment by ejgallego** [comment]
So something like this works
```patch
@@ -179,10 +179,10 @@ Fixpoint is_state_valid_after_pop (state:state) (to_pop:list symbol) annot :=
   | p::pl, s::sl => is_state_valid_after_pop state sl pl
   end.
 
-Instance impl_is_state_valid_after_pop_is_validator state sl pl P b :
+Instance impl_is_state_valid_after_pop_is_validator state0 sl pl P b :
   IsValidator P b ->
-  IsValidator (state_valid_after_pop state sl pl -> P)
-              (if is_state_valid_after_pop state sl pl then b else true).
+  IsValidator (state_valid_after_pop state0 sl pl -> P)
+              (if is_state_valid_after_pop state0 sl pl then b else true).
 Proof.
   destruct (is_state_valid_after_pop state0 sl pl) eqn:EQ.
   - intros ??. auto using is_validator.
```
but i'd be great to actually locate the commit that produced this change before submitting to CompCert.

**Comment by SkySkimmer** [comment]
Compcert already has https://github.com/AbsInt/CompCert/pull/303 submitted

**Pull request merged**
