### PR TITLE
Turn the CoqProject_file module into a pure ML file

### PR DESCRIPTION
**Pull request by ppedrot**
We also seize the opportunity to make the parsing algorithm slightly less crazy.

### CODE REVIEW

**Comment by ejgallego** [comment]
I think that I am delegating this to @gares , `coqfind` will introduce a different project format and uses its own camlp5-free parser.

**Comment by maximedenes** [comment]
Maybe we can update the owner, then.

**Review by gares — APPROVED** [review]
I don't have time to check the code, but I'm ok with the change if it passes the tests

**Comment by ppedrot** [comment]
Elpi failure is spurious, it requires merging two PRs to compile on master.

**Pull request merged**
