### PR TITLE
Share the computation of aliasing data in Evarsolve.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of recomputing the index corresponding to the last identifier pointed by the aliasing list, we compute it at the same time as the aliasing structure itself. This removes a source of slowness in an example from #9582.

cc @herbelin

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot minimize

**Comment by SkySkimmer** [comment]
Are the test suite failures not clear enough?

**Comment by ppedrot** [comment]
Ah, I've missed the test-suite failure in there. Yes, this should be enough indeed. (Though the aliasing mechanism is notably undertested, see e.g. #13751.)

**Comment by ppedrot** [comment]
I hereby officially abandon any tentative to understand the Evarsolve aliasing system. I suspect it's trying to achieve something, but this exists beyond the chasm of interplanar worlds.

(A rough specification might change my decision.)

**Pull request closed without merging**
