### PR TITLE
Normalize more paths in coqdep to avoid spurious warnings

### PR DESCRIPTION
**Pull request by rlepigre**
This fixes warnings such as the following:
```
Warning: ltac_plugin.cmxs already found in [...]/_opam/lib/coq-core/plugins/ltac (discarding [...]/_opam/lib/coq/../coq-core/plugins/ltac/ltac_plugin.cmxs)
         [multiple-matching-files,filesystem,default]
```

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
Seems fine to me but I'm not a coqdep expert.
@ejgallego @Alizter I think you are more up to date on coqdep, any objections?

**Comment by ejgallego** [comment]
Thanks @rlepigre , I was actually looking into this the other day; the "right" fix would be to have Coq stopping to set `coq/../coq-core` as a path. However this change requires a bit of deep surgery on the config code, so I didn't have the cycles to finish it.

[Basically you want to move from the current setup where `coqlib` is the "root" for a Coq install to a true `prefix` root, where packages are then located]

Happy to have this in Coq meanwhile.

Regarding testing, I think using `ppx_inline_test` or use unit tests to check the implementation in all architectures would be the best option.

**Comment by ejgallego** [comment]
> Seems fine to me but I'm not a coqdep expert. @ejgallego @Alizter I think you are more up to date on coqdep, any objections?

Patch is an improvement over the current situation.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
