### PR TITLE
[test-suite] close the proof added in #12857

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
CC @Zimmi48

**Review by Zimmi48 — APPROVED** [review]

**Comment by maximedenes** [comment]
Why was this captured only by the async test-suite?

**Comment by gares** [comment]
In linear mode you only see the first failure in the file (1: case; 2: no terminator). In async mode you get to skip the proof and...

**Comment by gares** [comment]
apparently output tests are allowed to fail as long as they generate the right output

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
