### PR TITLE
Remove compatibility with Coq 8.14.

### PR DESCRIPTION
**Pull request by Zimmi48**
Changes generated by running `dev/tools/update-compat.py --release`.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@coqbot run full CI

**Comment by Zimmi48** [comment]
cc @JasonGross (fiat-parsers) and @silene (Flocq). Why isn't Flocq included in the minimization suggestions BTW?

**Comment by JasonGross** [comment]
I will aim to fix Fiat shortly

> Why isn't Flocq included in the minimization suggestions BTW?

The coqbot logs should describe the reason.  What do they say?

**Comment by SkySkimmer** [comment]
Does it know how to minimize projects built with remake?

**Comment by Zimmi48** [comment]
I'll look at the logs when I get in front of a computer.

Yes, it's supposed to be build system agnostic (see the ITP paper for the explanation).

**Comment by JasonGross** [comment]
Yes, the build system doesn't matter, it uses Coq's CI scripts to build the project.  The issue is that the error message
```
Error: Compatibility with version 8.14 not supported.
```
contains no file nor line number, so the minimizer would have no way to discover what file to minimize.

**Comment by silene** [comment]
I have no idea why the continuous integration passes option `-compat 8.14` to Flocq.

**Comment by SkySkimmer** [comment]
It seems to date from the removal of omega. I think we can stop passing it.

**Comment by Zimmi48** [comment]
Sorry, I had not noticed that the `-compat 8.14` flag was passed on the Coq side.

**Comment by JasonGross** [comment]
What's up with
```
File "kernel/byterun/dune", line 1, characters 0-287:
1 | (library
2 |  (name coqrun)
3 |  (synopsis "Coq's Kernel Abstract Reduction Machine [C implementation]")
4 |  (public_name coq-core.vm)
5 |  (foreign_stubs
6 |   (language c)
7 |   (names coq_fix_code coq_float64 coq_memory coq_values coq_interp)
8 |   (flags -fPIC (:include %{project_root}/config/dune.c_flags))))
(cd _build/default && /root/.opamcache/4.09.0+32bit/bin/ocamlmklib.opt -g -o kernel/byterun/coqrun_stubs kernel/byterun/coq_fix_code.o kernel/byterun/coq_float64.o kernel/byterun/coq_interp.o kernel/byterun/coq_memory.o kernel/byterun/coq_values.o)
/usr/bin/ld: i386:x86-64 architecture of input file `kernel/byterun/coq_fix_code.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `kernel/byterun/coq_float64.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `kernel/byterun/coq_interp.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `kernel/byterun/coq_memory.o' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `kernel/byterun/coq_values.o' is incompatible with i386 output
kernel/byterun/coq_fix_code.o: In function `coq_stat_alloc':
/builds/coq/coq/_build/default/kernel/byterun/coq_fix_code.c:36: undefined reference to `caml_raise_out_of_memory'
```
at https://gitlab.com/coq/coq/-/jobs/3340994725?  Stale cache?

**Comment by Zimmi48** [comment]
@maximedenes: could there be some leaks between different runs on the same runner?

Anyway, this shouldn't hold this PR. This test was passing in the previous version, before I fixed `dev/ci/ci-flocq.sh`. Please someone merge ASAP so that the release process can move forward.

**Comment by gares** [comment]
@coqbot merge now

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
>could there be some leaks between different runs on the same runner?

That was a wrong interpretation because it also fails in the same way on shared runners: https://gitlab.com/coq/coq/-/jobs/3345281060

**Pull request merged**
