### PR TITLE
ci-compcert.sh: use default value for NJOBS when installing menhir.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
So for instance if you do `make ci-compcert` it will work.

**Comment by ejgallego** [comment]
Why don't set NJOBS at the entry point globally instead so we don't have to worry about it?

**Comment by SkySkimmer** [comment]
What entry point?

**Comment by ejgallego** [comment]
would an export in `ci-common` work?

**Comment by SkySkimmer** [comment]
>would an export in ci-common work?

Done.

**Review by ejgallego — APPROVED** [review]
Indeed this fixes a flagrant bug on the original implementation of the scripts, thanks @SkySkimmer .

**Pull request merged**
