### PR TITLE
Move README-V1-V5 to credits chapter

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

I have been bothered by the spread of documentation and especially release notes and credits in many places for a while. So this is a first step towards a consolidation.

I'm pretty sensitive to not rewording these parts of the doc too much since they are dated and have clearly identified authors. That's why this consolidation does not try to get rid of all duplication, but at the same time it tries to ensure that everything can be found in the same place, and the order is chronological as much as possible. Some notes were added to make the context more explicit.

I'm pretty happy with the result, it seems to make sense and be consistent. Have a look at the rendered version. If I may request help, it would be on the bibliography. I added articles to the `.bib` file by searching the title in Google Scholar and copy-pasting the bibtex that I could find. People who like TeX better than me might be able to improve the data for these new entries.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Rendered: https://zimmi48.gitlab.io/-/coq/-/jobs/129632245/artifacts/_install_ci/share/doc/coq/sphinx/html/credits.html

**Review by cpitclaudel — APPROVED** [review]
I think this is great. I'd like someone else to have a look, if possible, since I don't much about the history of Coq. We could also consider reversing this file (from most recent to oldest instead of the current oldest to most recent).

Here are the LaTeX entries I get using CrossRef (through the biblio package for Emacs):

```
@Article{CH85,
  author       = {Coquand, Thierry and Huet, Gérard},
  title        = {Constructions: A higher order proof system for mechanizing
                  mathematics},
  year         = 1985,
  pages        = {151–184},
  issn         = {1611-3349},
  doi          = {10.1007/3-540-15983-5_13},
  url          = {http://dx.doi.org/10.1007/3-540-15983-5_13},
  isbn         = 9783540396840,
  journal      = {Lecture Notes in Computer Science},
  publisher    = {Springer Berlin Heidelberg}
}

@Article{CP90,
  author       = {Coquand, Thierry and Paulin, Christine},
  title        = {Inductively defined types},
  year         = 1990,
  pages        = {50–66},
  issn         = {1611-3349},
  doi          = {10.1007/3-540-52335-9_47},
  url          = {http://dx.doi.org/10.1007/3-540-52335-9_47},
  isbn         = 9783540469636,
  journal      = {Lecture Notes in Computer Science},
  publisher    = {Springer Berlin Heidelberg}
}

@Article{H88,
  author       = {Huet, Gérard},
  title        = {Induction principles formalized in the calculus constructions
                  of},
  year         = 1987,
  pages        = {276–286},
  issn         = {1611-3349},
  doi          = {10.1007/3-540-17660-8_62},
  url          = {http://dx.doi.org/10.1007/3-540-17660-8_62},
  isbn         = 9783540477464,
  journal      = {Lecture Notes in Computer Science},
  publisher    = {Springer Berlin Heidelberg}
}

@Article{P89,
  author       = {Paulin-Mohring, Christine},
  title        = {Extracting $\omega$’s programs from proofs in the calculus of constructions},
  year         = 1989,
  doi          = {10.1145/75277.75285},
  url          = {http://dx.doi.org/10.1145/75277.75285},
  isbn         = 0897912942,
  journal      = {Proceedings of the 16th ACM SIGPLAN-SIGACT symposium on Principles of programming languages - POPL '89},
  publisher    = {ACM Press}
}

@Article{P93,
  author       = {Paulin-Mohring, Christine},
  title        = {Inductive definitions in the system Coq rules and properties},
  pages        = {328–345},
  doi          = {10.1007/bfb0037116},
  url          = {http://dx.doi.org/10.1007/bfb0037116},
  isbn         = 3540565175,
  journal      = {Typed Lambda Calculi and Applications},
  publisher    = {Springer-Verlag}
}

@Article{PP90,
  author       = {Pfenning, Frank and Paulin-Mohring, Christine},
  title        = {Inductively defined types in the Calculus of Constructions},
  pages        = {209–228},
  doi          = {10.1007/bfb0040259},
  url          = {http://dx.doi.org/10.1007/bfb0040259},
  isbn         = 0387973753,
  journal      = {Mathematical Foundations of Programming Semantics},
  publisher    = {Springer-Verlag}
}
```

They all have DOIs.

**Comment by gares** [comment]
May I suggest to reorder the credits section in reverse chronological order (most recent first) and put a date next to the new additions? This would make the beginning less surpring and requiring a footnote.

**Comment by Zimmi48** [comment]
>put a date next to the new additions

If you mean the new additions from this PR, this is already the case. The note marks the top of the added section, and the bottom https://coq.gitlab.io/-/coq/-/jobs/129652892/artifacts/_install_ci/share/doc/coq/sphinx/html/credits.html#version-5.

**Comment by Zimmi48** [comment]
Regarding reverse chronological order that you both suggested, I'm unsure. On the one hand, it makes sense that users having a look at this chapter would want to read the latest additions first. On the other hand the sections Historical roots - Version 5 make more sense in chronological order. Version 1 - Version 5 given that they were written in one go (in 2015). But also because of the duplication with the section "Brief summary of the versions up to 5.10" (written in 1995). If we reverse the order, then it could make sense to try to reduce this duplication even more. And finally, such a big change should be thought in conjunction to other discussions happening elsewhere (#9103, #7058, etc.). It could also be delayed to a subsequent PR.

**Comment by Zimmi48** [comment]
Added DOIs. Otherwise, I'm unconvinced by CrossRef's use of the `Article` class instead of `inProceedings`, especially in the case of the LNCS articles where the conference name is lost.

**Comment by gares** [comment]
> Regarding reverse chronological order that you both suggested, I'm unsure.

Maybe you could split credits in two main section:
- Current version: 8.x, in reverse order
- History: from 1 to 7, in chronological order

The point is that the old and new material play a different role.
The old one is clearly in the wrong order, it is a changelog, you put on top new stuff.
The one you just added is history, not easy to read it backward.

**Comment by Zimmi48** [comment]
It seems like a good compromise. But indeed, making Credits more like a changelog really means that this should be done in conjunction with the discussion in #9103. cc @ejgallego @mattam82

**Comment by Zimmi48** [comment]
Closing / reopening to get a recent build.
I suggest we merge this PR as-is and address the question of chronological / reverse chronological order in follow-up PRs.

**Comment by Zimmi48** [comment]
CI passed except for some unrelated failures. Most of the failed status checks are still from older runs anyways.

**Comment by Zimmi48** [comment]
ping @mattam82

**Comment by Zimmi48** [comment]
@mattam82 has approved this orally during the last WG (and is now eaten by the ICFP deadline) and no one has expressed any opposition so far so back to one of @coq/doc-maintainers to self-assign and merge.

**Comment by cpitclaudel** [comment]
I'm in ICFP mode too, but a quick look-through looks good. I can merge if no-one beats me to it ^^
(Great work as always, btw)

**Comment by Zimmi48** [comment]
ICFP's deadline passed now, isn't it?

**Comment by cpitclaudel** [comment]
It has :) Merged, thanks.

**Pull request merged**
