### PR TITLE
Update API for fiat

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Seems very reasonable to me.
The `Proof_global` stuff is going to disappear in 8.8 (at least these are @ejgallego's plan) but in the meantime I don't see why it couldn't be here in the API.

**Comment by JasonGross** [comment]
If by `Proof_global` stuff you mean `Pfedit.current_proof_statement`, that's fine; it's currently used to reimplement [`Tactics.name_op_to_name`](https://github.com/coq/coq/blob/0a577d3c979af094ca00be3e7e323109c7e1f6ab/tactics/tactics.ml#L5030-L5041)---perhaps we should instead export that, or move it to a saner place and export it?  (It's used in the plugin to basically create an alternate version of [`tclABSTRACT`](https://github.com/coq/coq/blob/0a577d3c979af094ca00be3e7e323109c7e1f6ab/tactics/tactics.ml#L5043-L5047).)

**Comment by matejkosik** [comment]
I don't have any objections.
(because none of the proposals violate any of the API [properties](https://github.com/coq/coq/blob/trunk/API/PROPERTIES) we currently maintain).

**Review by ghost — APPROVED** [review]
I don't have any objections.
(because none of the proposals violate any of the API [properties](https://github.com/coq/coq/blob/trunk/API/PROPERTIES) we currently maintain).

**Comment by JasonGross** [comment]
Rebased, and removed fiat-parsers from allowed-failures

**Comment by JasonGross** [comment]
@maximedenes How is this an 8.8 change?  I'd like fiat-parsers to be tested on the 8.7 ci; what's the proposed pathway for this to happen?

**Comment by maximedenes** [comment]
@JasonGross We are probably going to have to remove the API from 8.7, due to a few technical issues. But it will stay in trunk, to be integrated in 8.8. If that scenario is confirmed, this PR will be integrated just after we make the 8.7 branch. If not, I'll merge it in 8.7. We'll make sure we test fiat-parser either way, don't worry.

**Comment by SkySkimmer** [comment]
>this PR will be integrated just after we make the 8.7 branch.

@maximedenes  Are we go now?

**Pull request merged**
