### PR TITLE
fresh now accepts more things than just identifiers.

### PR DESCRIPTION
**Pull request by Matafou**
Namely, it accepts, variables, constants, inductives, constructors (and sorts).
When these have a qualified name, the fresh is done on its basename.

### CODE REVIEW

**Comment by jonleivent** [comment]
IMHO it is hard to imagine why someone would use fresh's original stinginess of arg kinds to test for something in a tactic, such that a failure of fresh is meaningful to the tactic.  Probably there should be just some kinds of errors that are not trappable in tactics and that indicate an actual usage mistake - and a bad arg for fresh is probably one such case.

But, that said, maybe there should be ways to check the "kind" of various Ltac values without relying on such backhanded failures as from fresh.  For instance, I once used a tactic notation to check if a uconstr was acceptable as an open_constr using this hack:

(*check_open_constr fails at level 1 if term is well formed, fails at level 0 if not*)
Tactic Notation "check_open_constr" open_constr(term) := fail 1.

Maybe this is more acceptable - at least it indicates much more clearly what it is trying to do.

**Comment by Matafou** [comment]
Can someone explain if the "topwith" part is necessary? I think I will push this on trunk since noody objects.

P.

**Comment by RalfJung** [comment]
Does this allow us to use "fresh x" for a constr x of type String, and use a Gallina-level string to name the variable?

**Comment by Matafou** [comment]
No. You are not the first one to suggest this but it is not implemented in this patch AFAIK. It would be nice indeed. I am afraid it is too late for 8.6 but someone should report this as a feature wish.

P.

**Comment by RalfJung** [comment]
We already bribed PMP for this (with beer), so he should be aware. ;-)

**Pull request merged**
