### PR TITLE
Remove deprecate+write read state vernaculars

### PR DESCRIPTION
**Pull request by ejgallego**
IMHO time has come to perform this cleanup; the functionality was at best half-working and likely with many bugs; see the individual commits for more details.

Note however that I think that such functionality of "session save" is very useful and could indeed be supported in the future, however with a different implementation (likely reusing some parts of the STM/workers).

### CODE REVIEW

**Comment by maximedenes** [comment]
Note: I'm pretty sure one can prove `False` using those vernaculars and `native_compute` (maybe `vm_compute` also).

**Comment by ejgallego** [comment]
Honestly the needs:discussion doesn't make sense. This is broken, if we need to offer some functionality like this in the future it has to be integrated with the STM and go trhought some design [CEP?]

**Comment by maximedenes** [comment]
It seems no deprecation warnings were emitted in 8.7 when using those commands. If that is true, we should do it now.

**Comment by ejgallego** [comment]
Maybe it is a good idea to have them deprecated? They can be fixed too; but it is non trivial work.

**Comment by Zimmi48** [comment]
If these commands are really completely broken and not used at all, it would be acceptable to remove them without a deprecation notice, but given that we are just about to release 8.7.0, that would be the perfect time to add such a notice (wouldn't cost much). You just need to act fast.

**Comment by herbelin** [comment]
As a spokesperson of people who used to use these commands, could you remind the "many bugs" they have and the potential proofs of False they could allow?

**Comment by maximedenes** [comment]
The problem is that not everything is part of the state saved in those files, AFAIK. For example, dynlinked code is not there. And the internal state of the VM runtime is not fully saved IIRC.

**Comment by maximedenes** [comment]
The STM does some analysis to distinguish commands to be replayed on workers from the ones that should send the state after their execution. I guess what Emilio is saying is that a correct implementation of those snapshot commands would reuse this kind of knowledge.

But it is nontrivial work indeed, so meanwhile we will have either to deprecate those commands or continue to ship broken stuff.

**Comment by herbelin** [comment]
OK, thanks. These arguments would help to explain the deprecation.

**Comment by maximedenes** [comment]
If that's ok with everybody, I'd be in favor of deprecating those vernacular commands in 8.7 (with a warning saying that they may not fully work). We can then see what to do in 8.8, i.e. leave them there, replace with an STM based implementation, etc.

**Comment by maximedenes** [comment]
Note that the warning can be disable by users if they want too. But at least, they know that they may hit some problems related to the use of these commands.

**Comment by ejgallego** [comment]
Indeed at the very least a warning should be given, after the STM was introduced these commands controlled state in a non-syncronized way, for example, they didn't save the document tree, etc...

Dropping the commands is the "easy" path, but maybe we can indeed reimplement them, but questions may remain.

**Comment by maximedenes** [comment]
WG discussion: see #1145

**Pull request closed without merging**
