### PR TITLE
Add Ltac2.Array.{for_all2,equal}

### PR DESCRIPTION
**Pull request by JasonGross**
We mirror the List functions.

- [ ] Added / updated **test-suite**. (should I?)
- [x] Added **changelog**.
- [ ] Added / updated **documentation**. (is there any to update?)

### CODE REVIEW

**Review by MSoegtropIMC — APPROVED** [review]
LGTM. Test cases wouldn't hurt but are IMO not required.

**Comment by JasonGross** [comment]
@MSoegtropIMC Do you want to assign?

**Comment by MSoegtropIMC** [comment]
@JasonGross : I am currently busy with Coq Platform stuff and also got two new workstations which are not fully set up yet (things like signing), so it might take a week. If this is no issue, I can take it.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
