### PR TITLE
improve Strings/Byte performance

### PR DESCRIPTION
**Pull request by mrhaandi**
Improve performance of `Strings/Byte.v`
from
`Byte.vo (real: 3.78, user: 3.74, sys: 0.04, mem: 470260 ko)`
to
`Byte.vo (real: 1.96, user: 1.91, sys: 0.04, mem: 467360 ko)`
by using `do ... refine` with an appropriate lemma instead of an ad-hoc `repeat match goal with`.

Since only some proofs are touched, no changelog needed.

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Review by andres-erbsen — APPROVED** [review]

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by Villetaneuse** [comment]
I confirm that I could reproduce the impressive speed-up locally:
```console
$ time coqc Byte.v # from the faster-Byte branch
real	0m2,339s
user	0m2,126s
sys	0m0,185s
$ time coqc Byte.v # from the master branch

real	0m4,829s
user	0m4,615s
sys	0m0,176s
```

**Comment by Villetaneuse** [comment]
As a side note, the requirement of `EqNat` could be dropped, but we may do so in a separate PR.

**Comment by mrhaandi** [comment]
> I also tried to simplify some proofs and failed miserably, even though they looked simple (1 line-ish) and somewhat low level. If you have some time, I would be happy to learn why `refine` performs that much better when repeated 256 times.

@Villetaneuse One way to think about performance is to consider the smallest / most elegant CIC proof term, then use `refine` to construct it. Also `destruct` can go overboard on type annotations resulting in a quadratic term whereas a linear one would suffice (also resulting in slow `Qed`). For `Byte.v` some proof terms are still unnecessarily quadratic due to type annotations and there is room left for improvement.

**Comment by mrhaandi** [comment]
@Villetaneuse for reference, below is a computationally efficient proof of `to_of_nat_option_map` which follows a different approach to avoid nested blowup:
```coq
  Lemma to_of_nat_option_map x : option_map to_nat (of_nat x) = if Nat.leb x 255 then Some x else None.
  Proof.
   destruct (PeanoNat.Nat.leb_spec x 255) as [H|H].
   - pose (f := fun z => match option_map to_nat (of_nat z) with Some y => Nat.eqb z y | None => false end).
     enough (f x = true) as H'.
     { subst f. simpl in H'.
       destruct (option_map to_nat (of_nat x)); [|easy].
       apply PeanoNat.Nat.eqb_eq in H'. now subst x. }
     enough (nat_rect _ (f 0) (fun y b => andb (f (S y)) b) 255 = true) as H'.
     { revert H H'. generalize 255. intros y. induction y as [|y IH].
       - now destruct x.
       - simpl. intros [?|?]%PeanoNat.Nat.le_succ_r [? ?]%Bool.andb_true_iff.
         + now apply IH.
         + now subst x. }
     reflexivity.
   - rewrite <- (PeanoNat.Nat.sub_add _ _ H).
     now rewrite PeanoNat.Nat.add_comm.
  Qed.
```
However, I feel that the above proof is quite overengineered for performance and is less clear / maintainable than the current one.

**Pull request merged**
