### PR TITLE
Remove packaging scripts while waiting for a fix to #5998.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is a temporary commit which should be reverted once the issue is fixed.

### CODE REVIEW

**Comment by ejgallego** [comment]
You may want to comment them out instead of removing?

**Comment by maximedenes** [comment]
Enrico reported that it is probably a change in the command line options accepted by Cygwin's setup.exe. So I'll try to have a look. If I fail to fix it quickly, we can merge this. Otherwise, better merge the fix.

**Comment by Zimmi48** [comment]
@ejgallego 

> You may want to comment them out instead of removing?

Sure, I just didn't take the time to find what the syntax for comments is in AppVeyor configuration files. Probably simply start the line with `#` I guess...

**Comment by ejgallego** [comment]
> Probably simply start the line with # I guess...

I think `yml` specifies that indeed. [but not 100% sure]

**Comment by Zimmi48** [comment]
@maximedenes Please merge this if you can't finish #6102 today.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
