### PR TITLE
Add a sponsor button with a link to the Consortium page.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation / infrastructure.

For reference about sponsor buttons, see https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository.
And here is the list of supported funding models (most of them are mostly directed towards individual maintainers):

```
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
```

Note: we could also consider opening an Open Collective https://opencollective.com/ if this helps us get smaller contributions from individuals or companies.

### CODE REVIEW

**Comment by maximedenes** [comment]
Thanks, I like the idea, of course. I'm not 100% comfortable linking with the current page knowing that we are not ready to take new subscribers for academic memberships, and are also not ready to send a Consortium agreement. @ybertot what do you think we should do?

**Comment by Zimmi48** [comment]
I'm perfectly fine about waiting to merge this. I was actually expecting this kind of answer. What do you think of the open collective idea? (Maybe we can discuss this IRL next week.)

**Comment by Zimmi48** [comment]
Can we have a Consortium status point at the next WG?

**Comment by maximedenes** [comment]
> Can we have a Consortium status point at the next WG?

We can, but there's no update yet.

**Comment by Zimmi48** [comment]
Too bad, well maybe a very brief recap then.

**Comment by Zimmi48** [comment]
Closing until the situation with the consortium changes.

**Pull request closed without merging**
