### PR TITLE
Use kernel reduction to assess whether a term can be a canonical structure

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
It doesn't seem very effective but still improves corn a bit so might be worth merging?

**Comment by ppedrot** [comment]
You tell me.

**Comment by Janno** [comment]
Corn and also iris-examples seem to have significant instruction count reductions and the change looks pretty small to me.

I am a little worried about `RedFlags.all`. What is the desired semantics of canonical structure resolution when intermediate terms are opaque in the transparency state?

One thing that to keep in mind  when using repeated kernel reduction is the cost of creating the definition cache (`CClosure.create_tab`). Mtac2 suffered from that quite substantially until I refactored the interpreter to keep the cache around as long as possible. I am not sure if `is_open_canonical_projection` is called often enough to warrant an experiment to avoid that, though.

**Comment by ppedrot** [comment]
I'm undrafting this, it doesn't hurt and seems to help marginally.

> I am a little worried about RedFlags.all

This PR is keeping the previous semantics, we can try to tweak that but expect incompatibilities.

> cost of creating the definition cache

Given the cost of everything else around, I think this is really a very minor concern in this context.

**Comment by ppedrot** [comment]
This seems to be breaking mathcomp-analysis...

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Pull request closed without merging**
