### PR TITLE
[proof] Minor cleanup in proof.ml

### PR DESCRIPTION
**Pull request by ejgallego**
I had this sitting on my HD so I think it is worth pushing it.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Maybe it would make sens eto have a function returning only the evar map?

**Comment by SkySkimmer** [comment]
(instead of going through `data`)

**Comment by ejgallego** [comment]
> Maybe it would make sens eto have a function returning only the evar map?

IMHO it is not worth it.

**Comment by ejgallego** [comment]
Failure is spurious.

[OSX CI is broken again, OMG :/]

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Let's merge.

**Pull request merged**
