### PR TITLE
Make the bench easier to run locally

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Janno** [comment]
How does one run the bench locally?

**Comment by SkySkimmer** [comment]
dev/bench/bench.sh is the script to run 
With this PR when run locally it will ask interactively which coq commits you want to test
Without this PR it doesn't work because it gets confused about the repo url and which commits to test

NB on some machines the cpu cycle and instruction counts will not be printed in the table because perf will print something the table generator doesn't expect, cf https://www.man7.org/linux/man-pages/man1/perf-stat.1.html#INTEL_HYBRID_SUPPORT
You can still manually look at _bench/logs/whatever.perf to see the data counts

**Comment by Janno** [comment]
Thank you very much!

**Review by ppedrot — APPROVED** [review]
I'm probably not a target demographic of this PR but this does seem reasonable.

**Pull request merged**
