### PR TITLE
Fix CoRN & Flocq CI scripts.

### PR DESCRIPTION
**Pull request by Zimmi48**
Auto-generated files like the Makefile have recently been removed from the sources (cf. coq-community/corn#88).  Calling ./configure.sh is now required.

**Kind:** infrastructure.

Could be backported, but not absolutely required since the version tested in v8.11 is pinned.

### CODE REVIEW

**Comment by VincentSe** [comment]
How about we remove the CoRN's `configure.sh` and give it a standard coq-community makefile like
`https://github.com/coq-community/graph-theory/blob/master/Makefile` ?

**Comment by Zimmi48** [comment]
@VincentSe: Sure! This would have to be done ASAP though to fix Coq's CI.

**Comment by VincentSe** [comment]
Push this correction on Coq's CI first. Then in the coming days I'll have a look at how to implement the 8.12 version test in a makefile. This is not a shell script, so the syntax is different.

By the way, why did you chose to have that recursive `make Makefile` that calls `make Makefile.coq`? A `configure.sh` that produces a `Makefile` is pretty standard in linux.

**Comment by Zimmi48** [comment]
> By the way, why did you chose to have that recursive `make Makefile` that calls `make Makefile.coq`? A `configure.sh` that produces a `Makefile` is pretty standard in linux.

This practice was adopted in the contribs a long time ago and has spread around. I think the intent was not to replace a `configure.sh` (most projects didn't have one) but an autogenerated `Makefile` checked in the sources.

Personally, I haven't taken a great care of the build systems in coq-community yet because I was waiting for the Coq support in Dune to become stable enough so that its use can be widespread.

**Comment by VincentSe** [comment]
Then what do you prefer ? Personally recursive makefiles give me headaches and I am comfortable with `configure.sh` that produces the makefile.

Besides, if the real build system target is Dune, there is little point in fine-tuning it in between.

**Comment by Zimmi48** [comment]
@VincentSe I'm fine with the current solution.

**Comment by Zimmi48** [comment]
@coq/ci-maintainers This is now a fix for not one but two broken CI scripts!

**Review by ejgallego — APPROVED** [review]
LGTM

**Comment by ejgallego** [comment]
@Zimmi48 flocq is still broken so it seems.

**Comment by ejgallego** [comment]
Well, I didn't see it broken in the first place; so I wonder about the change.

**Comment by Zimmi48** [comment]
> Well, I didn't see it broken in the first place; so I wonder about the change.

That's because the breaking change is from today. Here's a broken build on master: https://gitlab.com/coq/coq/-/jobs/497855596

**Comment by ejgallego** [comment]
Well flocq fails in this PR so I cannot merge this.

**Comment by Zimmi48** [comment]
Indeed, let's wait to get @silene's feedback. I can also remove the second commit to fix at least CoRN.

**Comment by ejgallego** [comment]
> Indeed, let's wait to get @silene's feedback. I can also remove the second commit to fix at least CoRN.

That seems like the best choice for now.

**Comment by Zimmi48** [comment]
Done. Note that the fix to CoRN has already been tested (https://gitlab.com/coq/coq/-/commit/8289a5c9130186d811e9d7230aa2b748a4da6deb) so I am not sure that it is useful to restart the blocked GitLab CI pipeline.

**Comment by Zimmi48** [comment]
@silene has already answered so I'll try to fix it once more.

**Comment by ppedrot** [comment]
I think it's better not to backport this, as highlighted in the top post.

**Pull request merged**
