### PR TITLE
add XML protocol doc for 8.6

### PR DESCRIPTION
**Pull request by psteckler**
This is an edited version of CJ Bell's XML protocol doc, for the 8.6 branch.

This follows Theo's suggestion in #516 to separate the docs into PRs for the 8.5 and 8.6 branches.

### CODE REVIEW

**Comment by maximedenes** [comment]
@psteckler There seems to be a problem with end-of-line characters in `dev/doc/xml-protocol.md`. Can you fix it?

**Comment by psteckler** [comment]
Do I still need to fix the EOL characters?

**Comment by maximedenes** [comment]
This push was not intentional, sorry about that. I'll fix the file.

**Comment by maximedenes** [comment]
Fixed.

**Pull request merged**
