### PR TITLE
Obligation state is a stack with push/pop on module and section start/end

### PR DESCRIPTION
**Pull request by SkySkimmer**
Depends https://github.com/coq/coq/pull/14779

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Weird test suite failure, did we get a hash collision or tmp name reuse?

**Comment by ejgallego** [comment]
Can't hurt, I wonder what more state we have on vernac w.r.t. section / modules.

IMHO it would be great to work a bit on declaremods as a lot of things are happenning there under the rug.

**Comment by ejgallego** [comment]
@SkySkimmer I'll be happy to merge when you remove the needs tag.

**Review by ejgallego — APPROVED** [review]
LGTM

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
