### PR TITLE
Makefiles: Fixes for byte compilation

### PR DESCRIPTION
**Pull request by SkySkimmer**
- default targets don't depend on ocamlopt when it's unavailable
- coqc.byte is built by byte target and coqc by coqbinaries target
- unit tests use best ocaml
- poly-capture-global-univs tests ml compilation with ocamlc

cf https://github.com/coq/coq/issues/9464

### CODE REVIEW

**Comment by andres-erbsen** [comment]
building on amd64 debian unstable ocaml ` --no-native-compiler`: [script](https://builds.sr.ht/api/jobs/26393/manifest), [log](https://builds.sr.ht/~andres/job/26393) making progress

**Comment by ejgallego** [comment]
@andres-erbsen @SkySkimmer  `CAML_LD_LIBRARY_PATH` is not properly set.

**Comment by SkySkimmer** [comment]
Now sets CAML_LD_LIBRARY_PATH in byte mode.

**Comment by andres-erbsen** [comment]
better -- it got to stdlib this time, dragging along at https://builds.sr.ht/~andres/job/26407

**Comment by JasonGross** [comment]
Can we add the script to Coq's CI to test opt-less platforms?

**Comment by SkySkimmer** [comment]
Updated install targets

**Comment by andres-erbsen** [comment]
running at https://builds.sr.ht/~andres/job/26519

**Comment by SkySkimmer** [comment]
Looks like it works.
@Zimmi48 there's an uncaught "ERROR: Job failed: exit code 137" https://gitlab.com/coq/coq/-/jobs/157087250

**Comment by bbarenblat** [comment]
I’m successfully able to build 8.9.0 for MIPS with these patches applied! I just uploaded 8.9.0 (with patches) to Debian. It should enter unstable in a few hours and then testing a couple days after that. You can follow the progress on the [tracker page](https://tracker.debian.org/pkg/coq).

I’ll send out a more formal thank-you once everything’s finalized on the Debian end, but in the meantime, I want to thank you all for helping me get Coq building without `ocamlopt`. Your responsiveness and willingness to help are indisputably above and beyond the call of duty. I’m very excited about the prospect of an up-to-date Coq in Debian.

**Comment by andres-erbsen** [comment]
I further confirmed that the install places enough files to compile (most of) bedrock2: https://builds.sr.ht/~andres/job/26607 (timeout at 1h).

**Comment by Zimmi48** [comment]
Thanks for the report @SkySkimmer

**Comment by Zimmi48** [comment]
cc @gares

**Review by gares — APPROVED** [review]

**Pull request merged**
