### PR TITLE
Reimplement nf_evars in a saner way.

### PR DESCRIPTION
**Pull request by ppedrot**
We get rid of a quadratic behaviour by performing universe substitution and evar expansion at the same time.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ejgallego** [comment]
Umm, wasn't nf_evars_and_universes_opt_subst doing already that?

(c.f. #11917 for vaguely related ref)

**Comment by ejgallego** [comment]
> @ejgallego no, there is a recursive call after the expansion of evars so you can get a superlinear blowup there.

Well that's not quadratic but O(n) on the resulting expanded term, right? [quadratic is what got me confused there]

How similar are these implementations tho, maybe it would make sense to tweak the one in univsubst? Anyways the speedup is not good enough IMHO.

**Comment by Alizter** [comment]
Some of that slow down doesn't look like noise however. Let's see what the line timings reveal.

**Comment by SkySkimmer** [comment]
I think this was the last user for nf_evars_and_universes_opt_subst so it can be deleted now.

**Comment by ppedrot** [comment]
@Alizter I didn't try to be clever in this patch. The current asymptotically inefficient code has also some fast-paths that were not reproduced here, we would do that as well.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Any idea what's going wrong now?

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
OK, so it's definitely not worth it trying to not perform substitutions by checking for identity arguments. The weird thing is that I don't see the slowdowns from coq-rewriter-perf-SuperFast in the per-line diff. Maybe they're not timed? cc @JasonGross

**Comment by JasonGross** [comment]
> The weird thing is that I don't see the slowdowns from coq-rewriter-perf-SuperFast in the per-line diff. Maybe they're not timed? cc @JasonGross

Yeah, the coq-rewriter-perf-* benches don't have meaningful per-line diffs, and unfortunately the way we generate performance plots messes with the script that creates per-line timing diffs.  The relevant thing is to figure out the per-file diff, and look at the thing that that file is testing.

**Comment by ppedrot** [comment]
Closing for now.

**Pull request closed without merging**
