### PR TITLE
Fixes #16752: irrelevance check missing for opaque names in kernel conversion

### LINKED ISSUE #16752: Unification not finding a rew in 8.16.0; used to work in 8.15.2
[bonak](https://github.com/artagnon/bonak) is broken on `8.16.0`, while it was working fine in `8.15.2`. I've included a minimized bug report. On the last line, the `destruct` isn't able to match the `rew`: we tried with `set` too, but it doesn't seem to match. We tried displaying implicit arguments, and copying the whole line as-is to match, but it still doesn't pick it up. Ofcourse, the `rew` notation hides some arguments, but the output of displaying all low-level notations is unreadable.

```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-w" "-deprecated-native-compiler-option,-native-compiler-disabled" "-R" "." "Top" "-I" "theories/NType/" "-top" "Top.theories.NType.NType" "-native-compiler" "ondemand") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 620 lines to 253 lines, then from 266 lines to 517 lines, then from 522 lines to 292 lines, then from 305 lines to 432 lines, then from 437 lines to 325 lines, then from 338 lines to 407 lines, then from 412 lines to 334 lines, then from 339 lines to 333 lines *)
(* coqc version 8.16.0 compiled with OCaml 4.14.0
   coqtop version 8.16.0
   Expected coqc runtime on this file: 0.931 sec *)
Notation "( a ; b )" := (existT _ a b).
Notation "x .1" := (projT1 x) (at level 1, left associativity, format "x .1").
Notation "x .2" := (projT2 x) (at level 1, left associativity, format "x .2").
Notation "x .+1" := (S x) (at level 1, left associativity, format "x .+1").
Notation "x .+2" := (S (S x)) (at level 1, left associativity, format "x .+2").
Notation "x .+3" := (S (S (S x))) (at level 1, left associativity, format "x .+3").

Arguments id {A} x.

Notation "(= u ; v )" := (eq_existT_curried u v)
(at level 0, format "(= u ;  '/  ' v )").
Module Export HSet.

Set Universe Polymorphism.

Record HSet := {
  Dom:> Type;
  UIP {x y: Dom} {h g: x = y}: h = g;
}.

Lemma sigT_UIP {A: HSet} {B: A -> HSet} (x y: {a: A & B a}) (p q: x = y): p = q.
Admitted.
Definition hsigT {A: HSet} (B: A -> HSet): HSet.
exact ({|
  Dom := {a: A & B a};
  UIP := sigT_UIP;
|}).
Defined.
Notation "{ x : A & P }" := (hsigT (A := A) (fun x => P)): type_scope.

Definition hpiT_UIP {A: Type} (B: A -> HSet)
  (f g: forall a: A, B a) (p q: f = g): p = q.
Admitted.

Definition hpiT {A: Type} (B: A -> HSet): HSet.
Proof.
  exists (forall a: A, B a).
intros x y h g.
now apply hpiT_UIP.
Defined.

Notation "'hforall' x , A" := (hpiT (fun x => A))
(x binder, at level 200): type_scope.

End HSet.
Fixpoint leR (n m : nat) : SProp.
Admitted.

Definition leY n m := forall p, leR p n -> leR p m.
Infix "<=" := leY : nat_scope.

Theorem leY_contra {n}: n.+1 <= O -> False.
Admitted.
Definition leY_refl n : n <= n.
Admitted.

Notation "♢" := leY_refl (at level 0).
Definition leY_trans {n m p} (Hnm : n <= m) (Hmp : m <= p) : n <= p.
exact (fun q (Hqn : leR q n) => Hmp _ (Hnm _ Hqn)).
Defined.

Infix "↕" := leY_trans (at level 45).

Lemma leY_down {n m} (Hnm: n.+1 <= m): n <= m.
Admitted.

Notation "↓ p" := (leY_down p) (at level 40).

Lemma leY_lower_both {n m} (Hnm: n.+1 <= m.+1) : n <= m.
Admitted.

Notation "⇓ p" := (leY_lower_both p) (at level 40).

Ltac find_raise q :=
  match q with
  | ?q.+1 => find_raise q
  | _ => constr:(q)
  end.

Ltac invert_le Hpq :=
  match type of Hpq with
  | ?p.+1 <= ?q => let c := find_raise q in destruct c;
                   [exfalso; clear -Hpq; repeat apply leY_lower_both in Hpq;
                   now apply leY_contra in Hpq |]
  end.
Import Logic.EqNotations.

Universe m.

Universe m'.

Variable side: HSet.

Class PartialFramePrev (n: nat) (prefix: Type@{m'}) := {
  frame' {p} (Hp: p.+1 <= n): prefix -> HSet@{m};
  frame'' {p} (Hp: p.+2 <= n): prefix -> HSet@{m};
  restrFrame' {p q} {Hpq: p.+2 <= q.+2} (Hq: q.+2 <= n) (ε: side) {D: prefix}:
    frame' (↓ (Hpq ↕ Hq)) D -> frame'' (Hpq ↕ Hq) D;
}.

Class PartialFrame (n p: nat) (prefix: Type@{m'})
  (FramePrev: PartialFramePrev n prefix) := {
  frame (Hp: p <= n): prefix -> HSet@{m};
  restrFrame {q} {Hpq: p.+1 <= q.+1} (Hq: q.+1 <= n) (ε: side) {D: prefix}:
    frame (↓ (Hpq ↕ Hq)) D -> FramePrev.(frame') (Hpq ↕ Hq) D;
  cohFrame {q r} {Hpr: p.+2 <= r.+2} {Hrq: r.+2 <= q.+2} {Hq: q.+2 <= n}
    {ε: side} {ω: side} {D: prefix} (d: frame (↓ (⇓ Hpr ↕ (↓ (Hrq ↕ Hq)))) D):
    FramePrev.(restrFrame') (Hpq := Hpr ↕ Hrq) Hq ε
      (restrFrame (Hpq := ⇓ Hpr) (↓ (Hrq ↕ Hq)) ω d) =
    (FramePrev.(restrFrame') (Hpq := Hpr) (Hrq ↕ Hq) ω
      (restrFrame (Hpq := ↓ (Hpr ↕ Hrq)) Hq ε d));
}.

Class PartialFillerPrev (n: nat) (prefix: Type@{m'})
  (FramePrev : PartialFramePrev n prefix) := {
  filler' {p} {Hp: p.+1 <= n} {D: prefix}: FramePrev.(frame') Hp D -> HSet@{m};
  filler'' {p} {Hp: p.+2 <= n} {D: prefix}: FramePrev.(frame'') Hp D -> HSet@{m};
  restrFiller' {p q} {Hpq: p.+2 <= q.+2} (Hq: q.+2 <= n) (ε: side) {D: prefix}
    {d : FramePrev.(frame') (↓ (Hpq ↕ Hq)) D}:
    filler' d -> filler'' (FramePrev.(restrFrame') Hq ε d);
}.

Class PartialFiller (n: nat) (prefix: Type@{m'})
  {FramePrev: PartialFramePrev n prefix}
  (FillerPrev: PartialFillerPrev n prefix FramePrev)
  (Frame: forall {p}, PartialFrame n p prefix FramePrev) := {
  filler {p} {Hp: p <= n} {D: prefix}:
    (Frame.(frame) (♢ _) D -> HSet@{m}) -> Frame.(frame) Hp D -> HSet@{m};
  restrFiller {p q} {Hpq: p.+1 <= q.+1}
    (Hq: q.+1 <= n) (ε: side) {D : prefix} {E: Frame.(frame) (♢ _) D -> HSet@{m}}
    {d: Frame.(frame) (↓ (Hpq ↕ Hq)) D} (c: filler E d):
    FillerPrev.(filler') (Frame.(restrFrame) Hq ε d);
  cohFiller {p q r} {Hpr: p.+2 <= r.+2}
    {Hrq: r.+2 <= q.+2} {Hq: q.+2 <= n}
    (ε: side) (ω : side) {D: prefix} (E: Frame.(frame) (♢ _) D -> HSet@{m})
    (d: Frame.(frame) (↓ (⇓ Hpr ↕ (↓ (Hrq ↕ Hq)))) D) (c: filler E d):
    rew [FillerPrev.(filler'')] (Frame.(cohFrame) d) in
    FillerPrev.(restrFiller') (Hpq := Hpr ↕ Hrq) Hq
    ε (restrFiller (Hpq := ⇓ Hpr) (↓ (Hrq ↕ Hq)) ω c) =
      (FillerPrev.(restrFiller') (Hpq := Hpr) (Hrq ↕ Hq)
      ω (restrFiller (Hpq := ↓ (Hpr ↕ Hrq)) Hq ε c));
}.
Arguments restrFiller {n prefix FramePrev FillerPrev Frame} _ {p q Hpq Hq ε D E} [d] c.

Class NType (n : nat) := {
  prefix: Type@{m'};
  FramePrev: PartialFramePrev n prefix;
  Frame {p}: PartialFrame n p prefix FramePrev;
  FillerPrev: PartialFillerPrev n prefix FramePrev;
  Filler: PartialFiller n prefix FillerPrev (@Frame);

  Layer' {p} {Hp: p.+1 <= n} {D: prefix} (d: Frame.(frame) (↓ Hp) D) :=
    hforall ε, FillerPrev.(filler') (Frame.(restrFrame) Hp ε d);
  Layer'' {p} {Hp: p.+2 <= n} {D: prefix} (d: FramePrev.(frame') (↓ Hp) D) :=
    hforall ε, FillerPrev.(filler'') (FramePrev.(restrFrame') Hp ε d);
  RestrLayer' {p q ε} {Hpq: p.+2 <= q.+2} {Hq: q.+2 <= n} {D: prefix}
    (d: Frame.(frame) (↓ ↓ (Hpq ↕ Hq)) D) (l: Layer' d):
      Layer'' (Frame.(restrFrame) Hq ε d) :=
  fun ω => rew [FillerPrev.(filler'')] Frame.(cohFrame) (Hrq := Hpq) d in FillerPrev.(restrFiller') Hq ε (l ω);

  eqFrame0 {len0: 0 <= n} {D: prefix}: (Frame.(frame) len0 D).(Dom) = unit;
  eqFrame0' {len1: 1 <= n} {D: prefix}: (FramePrev.(frame') len1 D).(Dom) = unit;
  eqFrameSp {p} {Hp: p.+1 <= n} {D: prefix}:
    Frame.(frame) Hp D = {d: Frame.(frame) (↓ Hp) D & Layer' d} :> Type;
  eqFrameSp' {p} {Hp: p.+2 <= n} {D: prefix}:
    FramePrev.(frame') Hp D = {d : FramePrev.(frame') (↓ Hp) D & Layer'' d}
      :> Type;
  eqRestrFrame0 {q} {Hpq: 1 <= q.+1} {Hq: q.+1 <= n} {ε: side} {D: prefix}:
    Frame.(restrFrame) (Hpq := Hpq) Hq ε (rew <- [id] eqFrame0 (D := D) in tt) =
      (rew <- [id] eqFrame0' in tt);
  eqRestrFrameSp {ε p q} {D: prefix} {Hpq: p.+2 <= q.+2} {Hq: q.+2 <= n}
    {d: Frame.(frame) (↓ ↓ (Hpq ↕ Hq)) D}
    {l: Layer' (Hp := ↓ (Hpq ↕ Hq)) d}:
    Frame.(restrFrame) Hq ε (rew <- [id] eqFrameSp in (d; l)) =
      rew <- [id] eqFrameSp' in (Frame.(restrFrame) Hq ε d; RestrLayer' d l);
  eqFillerSp {p} {Hp: p.+1 <= n} {D: prefix} {E d}:
    Filler.(filler) (Hp := ↓ Hp) E d = {l: Layer' d &
      Filler.(filler) (D := D) E (rew <- [id] eqFrameSp in (d; l))} :> Type;
  eqFillerSp' {p} {Hp: p.+2 <= n} {D: prefix} {d}:
    FillerPrev.(filler') (Hp := ↓ Hp) d = {b : Layer'' d &
      FillerPrev.(filler') (rew <- [id] eqFrameSp' (D := D) in (d; b))} :> Type;
  eqRestrFiller0 {p} {Hp: p.+1 <= n} {D: prefix} {E} {d} {ε: side}
    {l: Layer' d} {Q: Filler.(filler) (D := D) E (rew <- eqFrameSp in (d; l))}:
      l ε = Filler.(restrFiller) (Hq := Hp) (rew <- [id] eqFillerSp in (l; Q));
  eqRestrFillerSp {p q} {Hpq: p.+2 <= q.+2} {Hq: q.+2 <= n} {D: prefix} {E} {d}
    {ε: side} {l: Layer' (Hp := ↓ (Hpq ↕ Hq)) d}
    {Q: Filler.(filler) (D := D) E (rew <- eqFrameSp in (d; l))}:
    Filler.(restrFiller) (Hpq := ↓ Hpq) (ε := ε) (rew <- [id] eqFillerSp in (l; Q)) = rew <- [id] eqFillerSp' (Hp := Hpq ↕ Hq) in
      (RestrLayer' d l; rew [FillerPrev.(filler')] eqRestrFrameSp in
        Filler.(restrFiller) Q);
}.
Arguments RestrLayer' {n} _ {p q} ε {Hpq Hq D d} l.
Definition mkprefix {n} {C: NType n}: Type@{m'}.
exact (sigT (fun D : C.(prefix) => C.(Frame).(frame) (♢ _) D -> HSet@{m})).
Defined.
Definition mkFramePrev {n} {C: NType n}: PartialFramePrev n.+1 mkprefix.
exact ({|
  frame' (p: nat) (Hp: p.+1 <= n.+1) (D: mkprefix) := C.(Frame).(frame) (⇓ Hp) D.1;
  frame'' (p: nat) (Hp: p.+2 <= n.+1) (D: mkprefix) :=
    C.(FramePrev).(frame') (⇓ Hp) D.1;
  restrFrame' (p q: nat) (Hpq: p.+2 <= q.+2) (Hq: q.+2 <= n.+1) (ε: side)
    (D: mkprefix) (d: _) :=
    C.(Frame).(restrFrame) (Hpq := ⇓ Hpq) (⇓ Hq) ε d;
|}).
Defined.
Definition mkLayer {n p} {Hp: p.+1 <= n.+1} {C: NType n} {D: mkprefix}
  {Frame: PartialFrame n.+1 p mkprefix mkFramePrev} {d: Frame.(frame) (↓ Hp) D}: HSet.
exact (hforall ε, C.(Filler).(filler) D.2 (Frame.(restrFrame) (Hpq := ♢ _) Hp ε d)).
Defined.

Definition mkRestrLayer {n p q} {ε: side} {Hpq: p.+2 <= q.+2} {Hq: q.+2 <= n.+1}
  {C: NType n} {D: mkprefix} {Frame: PartialFrame n.+1 p mkprefix mkFramePrev}
  (d: Frame.(frame) (↓ ↓ (Hpq ↕ Hq)) D)
  (l: mkLayer): C.(Layer') (Frame.(restrFrame) Hq ε d) :=
  fun ω => rew [C.(FillerPrev).(filler')] Frame.(cohFrame) d in
    C.(Filler).(restrFiller) (Hpq := ⇓ Hpq) (l ω).

Definition mkCohLayer {n p q r} {ε ω: side} {Hpr: p.+3 <= r.+3}
  {Hrq: r.+3 <= q.+3} {Hq: q.+3 <= n.+1} {C: NType n} {D: mkprefix}
  {Frame: PartialFrame n.+1 p mkprefix mkFramePrev}
  {d: Frame.(frame) (↓ ↓ ↓ (Hpr ↕ Hrq ↕ Hq)) D} (l: mkLayer):
  let sl := C.(RestrLayer') (Hpq := ⇓ (Hpr ↕ Hrq)) ε
              (mkRestrLayer (Hpq := ⇓ Hpr) d l) in
  let sl' := C.(RestrLayer') (Hpq := ⇓ Hpr) ω
               (mkRestrLayer (Hpq := ↓ (Hpr ↕ Hrq)) d l) in
  rew [C.(Layer'')] Frame.(cohFrame) (Hpr := ↓ Hpr) (Hrq := Hrq) (Hq := Hq) d in sl = sl'.
Admitted.

#[local]
Instance mkFrame0 {n} {C: NType n}: PartialFrame n.+1 O mkprefix mkFramePrev.
Admitted.

#[local]
Instance mkFrameSp {n p} {C: NType n} {Frame: PartialFrame n.+1 p mkprefix mkFramePrev}:
  PartialFrame n.+1 p.+1 mkprefix mkFramePrev.
  unshelve esplit.
  *
 intros Hp D; exact {d : Frame.(frame) (↓ Hp) D & mkLayer (d := d)}.
  *
 simpl; intros * ε * (d, l); invert_le Hpq.

    now exact (rew <- [id] C.(eqFrameSp) in
      (Frame.(restrFrame) Hq ε d; mkRestrLayer d l)).
  *
 simpl; intros q r Hpr Hrq Hq ε ω D (d, l).

    invert_le Hpr; invert_le Hrq.

    etransitivity.
apply (C.(eqRestrFrameSp) (Hpq := ⇓ (Hpr ↕ Hrq)) (Hq := ⇓ Hq)).
    etransitivity.
    2: symmetry; apply (C.(eqRestrFrameSp) (Hpq := ⇓ Hpr) (Hq := ⇓ (Hrq ↕ Hq))).

    apply f_equal with (B := C.(FramePrev).(frame') _ D.1)
      (f := fun x => rew <- (C.(eqFrameSp') (Hp := ⇓ (Hpr ↕ Hrq) ↕ ⇓ Hq)) in x).
    now exact (= Frame.(cohFrame) (Hrq := Hrq) d; mkCohLayer l).

Defined.

#[local]
Instance mkFrame {n} {C: NType n} p: PartialFrame n.+1 p mkprefix mkFramePrev.
  induction p.
  +
 now exact mkFrame0.

  +
 now exact (mkFrameSp (Frame := IHp)).

Defined.
#[local]
Instance mkFillerPrev {n} {C: NType n} : PartialFillerPrev n.+1 mkprefix mkFramePrev.
exact ({|
  filler' (p: nat) (Hp: p.+1 <= n.+1) (D: mkprefix) := C.(Filler).(filler) D.2:
    mkFramePrev.(frame') Hp D -> HSet;
  filler'' (p: nat) (Hp: p.+2 <= n.+1) (D: mkprefix)
    (d : mkFramePrev.(frame'') Hp D) :=
    C.(FillerPrev).(filler') d;
  restrFiller' (p q: nat) (Hpq: p.+2 <= q.+2) (Hq: q.+2 <= n.+1) (ε: side)
    (D: mkprefix) (d : _) (b : _) := C.(Filler).(restrFiller) (Hpq := ⇓ Hpq)
    (Hq := ⇓ Hq) (E := D.2) b;
|}).
Defined.

Definition mkfiller {n p} {C: NType n} {Hp: p <= n.+1} {D: mkprefix}
  (E: (mkFrame n.+1).(frame) (♢ _) D -> HSet)
  (d: (mkFrame p).(frame) Hp D): HSet.
Admitted.

Lemma mkfiller_computes {n p} {C: NType n} {Hp: p.+1 <= n.+1} {D: mkprefix}
  {E: (mkFrame n.+1).(frame) (♢ _) D -> HSet} {d}:
  mkfiller (Hp := ↓ Hp) E d = {l : mkLayer & mkfiller (Hp := Hp) E (d; l)} :> Type.
Admitted.

Definition mkRestrFiller {n} {C: NType n} {p q} {Hpq: p.+1 <= q.+1}
  {Hq: q.+1 <= n.+1} {ε: side} {D}
  (E: (mkFrame n.+1).(frame) (♢ _) D -> HSet)
  (d: (mkFrame p).(frame) (↓ (Hpq ↕ Hq)) D)
  (Filler: mkfiller (Hp := ↓ (Hpq ↕ Hq)) E d):
    mkFillerPrev.(filler') ((mkFrame p).(restrFrame) Hq ε d).
Admitted.

Lemma mkRestrFiller_base_computes {p n} {C: NType n} {Hp: p.+1 <= n.+1}
  {ε: side} {D E} {d: (mkFrame p).(frame) _ D} {c}:
  mkRestrFiller (Hq := Hp) E d c =
  match (rew [id] mkfiller_computes in c) with
  | (l; _) => l ε
  end.
Admitted.

Lemma mkRestrFiller_step_computes {q r n} {C: NType n} {Hq: q.+2 <= n.+1}
  {Hrq: r.+2 <= q.+2} {ε: side} {D E} {d: (mkFrame r).(frame) _ D} {c}:
  mkRestrFiller (Hpq := ↓ Hrq) (Hq := Hq) (ε := ε) E d c =
  match (rew [id] mkfiller_computes in c) with
  | (l; c) => rew <- [id] C.(eqFillerSp) in
    (mkRestrLayer d l; mkRestrFiller (Hpq := Hrq) E (d; l) c)
  end.
Admitted.

Definition mkCohFiller_base {q r n} {ε ω: side} {C: NType n} {D: mkprefix}
  {Hrq: r.+2 <= q.+2} {Hq: q.+2 <= n.+1}
  {E: (mkFrame n.+1).(frame) (♢ _) D -> HSet}
  (d: (mkFrame r).(frame) (↓ ↓ (Hrq ↕ Hq)) D)
  (c: mkfiller E d):
  rew [mkFillerPrev.(filler'')] (mkFrame r).(cohFrame) (Hpr := ♢ _) d in
    mkFillerPrev.(restrFiller') (Hpq := Hrq) Hq ε
      (mkRestrFiller (ε := ω) (Hpq := ♢ _) (Hq := ↓ (Hrq ↕ Hq)) E d c) =
  mkFillerPrev.(restrFiller') (Hpq := ♢ _) (Hrq ↕ Hq) ω
    (mkRestrFiller (ε := ε) (Hpq := ↓ Hrq) (Hq := Hq) E d c).
  change (♢ _ ↕ ?H) with H; change (⇓ (♢ _) ↕ ?H) with H.
  rewrite mkRestrFiller_base_computes, mkRestrFiller_step_computes.
  destruct (rew [id] mkfiller_computes in c) as (l, c'); clear c.
```

Additionally, I've run a bisect, and [57081c1a](https://github.com/coq/coq/commit/57081c1a) authored by @ppedrot is to blame for the breakage:

```
commit 57081c1ae01a742033dec44a2a42bffa08a9f5af
Author: Pierre-Marie Pédrot <pierre-marie.pedrot@inria.fr>
Date:   Wed Jan 20 13:38:04 2021 +0100

    Introduce a new irrelevant term in the reduction machine.

    It is used to shortcut computation of terms living in a strict proposition,
    and behaves as an exception.

 kernel/cClosure.ml          | 180 +++++++++++++++++++++++++++++++++++++-------
 kernel/cClosure.mli         |   6 +-
 kernel/inferCumulativity.ml |   1 +
 kernel/reduction.ml         |  52 +++++++++----
 kernel/relevanceops.ml      |   1 +
 5 files changed, 198 insertions(+), 42 deletions(-)
```

From the description, it seems like an `SProp` bug, but I haven't looked any deeper.

### PR DESCRIPTION
**Pull request by herbelin**
This is a possible fix against master for #16752 (v8.16 would require a slightly different fix).

Fixes / closes #16752

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by herbelin** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
(I cancelled the older bench)

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by herbelin** [comment]
Is this acceptable? What would be the alternatives otherwise?

**Review by ppedrot — APPROVED** [review]
This looks perfectly fine to me.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
I will merge soon except if somebody complains.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
