### PR TITLE
Expose and use delayed evar substitution in a few key functions.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
I know for sure that the two mathcomp speedups are real and reproducible. No so sure about the rest though, so it's unclear to me whether this is really beneficial in practice.

**Comment by Janno** [comment]
This looks like an improvement across the board. Any reason not to take it?

**Comment by ppedrot** [comment]
@Janno we definitely want this in, the question is whether we can cancel the very local but very important slowdowns of fiat-crypto.

**Comment by ppedrot** [comment]
I'm undrafting this as it's overall more efficient, even if this requires a new API.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
