### PR TITLE
Plug ltac2 into the ltac profiler

### LINKED ISSUE #10111: Request: Ltac2 profiler like Ltac profiler
Either the Ltac profiler should support Ltac2 (ideal case), or there should be separate profiling for Ltac2.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure if separating ltac1 and ltac2 profiling would be useful

Close https://github.com/coq/coq/issues/10111

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I'm not sure if it's working correctly. On 
~~~coq
Require Import ZArith. Open Scope Z_scope.

Require Import Ltac2.Ltac2.

Ltac2 succ r := constr:(S $r).

Ltac2 of_coq_bool c :=
  lazy_match! c with
  | true => true
  | false => false
  end.

Ltac2 rec z2nat_constr x :=
  let b := eval cbv in (Z.leb $x 0) in
  if of_coq_bool b
  then constr:(O)
  else
    let pred := eval cbv in (Z.pred $x) in
    let r := z2nat_constr pred in
    succ r.

Time Ltac2 Eval
  start_profiling ();
  let _ := (z2nat_constr constr:(10000)) in
  show_profile().
~~~
I get 
~~~
total time:     25.200s

 tactic                                   local  total   calls       max
────────────────────────────────────────┴──────┴──────┴───────┴─────────┘
─z2nat_constr --------------------------   0.0% 100.0%       1   25.200s
─<fun let b :=        let c := constr:($ 100.0% 100.0%   10001   25.199s
─of_coq_bool ---------------------------   6.1%  57.3%   10001    0.019s
─Pattern.lazy_match0 -------------------   4.0%  51.1%   10001    0.019s
─Control.once --------------------------   1.9%  42.7%   10001    0.019s
─<coq-core.plugins.ltac2:once> ---------   1.9%  40.8%   10001    0.019s
─<fun interp pats> ---------------------   4.1%  38.9%   10001    0.019s
─<fun match m with      | [] => Control.   2.0%  34.7%   20001    0.019s
─Control.plus --------------------------   2.0%  32.7%   20001    0.018s
─<coq-core.plugins.ltac2:plus> ---------   4.2%  30.8%   20001    0.018s
─<fun let context := Pattern.empty_conte  10.0%  20.9%   20001    0.007s
─<fun interp m> ------------------------  14.2%  14.2%   10000    0.018s
─<extn:constr> -------------------------  11.3%  11.3%   30003    0.003s
─succ ----------------------------------   2.4%  11.2%   10000    0.008s
─Pattern.empty_context -----------------   6.5%   6.6%   30001    0.007s
─Std.eval_cbv --------------------------   4.8%   6.0%   20001    0.007s
─<fun f context bind> ------------------   4.3%   4.4%   10001    0.012s
─Pattern.matches_vect ------------------   4.0%   4.4%   20001    0.004s

 tactic                                   local  total   calls       max
────────────────────────────────────────┴──────┴──────┴───────┴─────────┘
─z2nat_constr --------------------------   0.0% 100.0%       1   25.200s
└<fun let b :=        let c := constr:($ 100.0% 100.0%   10001   25.199s
 ├─of_coq_bool -------------------------   6.1%  57.3%   10001    0.019s
 │└Pattern.lazy_match0 -----------------   4.0%  51.1%   10001    0.019s
 │ ├─Control.once ----------------------   1.9%  42.7%   10001    0.019s
 │ │└<coq-core.plugins.ltac2:once> -----   1.9%  40.8%   10001    0.019s
 │ │└<fun interp pats> -----------------   4.1%  38.9%   10001    0.019s
 │ │└<fun match m with      | [] => Cont   2.0%  34.7%   20001    0.019s
 │ │└Control.plus ----------------------   2.0%  32.7%   20001    0.018s
 │ │└<coq-core.plugins.ltac2:plus> -----   4.2%  30.8%   20001    0.018s
 │ │ ├─<fun let context := Pattern.empty  10.0%  20.9%   20001    0.007s
 │ │ │ ├─Pattern.empty_context ---------   6.5%   6.6%   30001    0.007s
 │ │ │ └─Pattern.matches_vect ----------   4.0%   4.4%   20001    0.004s
 │ │ └─<fun interp m> ------------------  14.2%  14.2%   10000    0.018s
 │ └─<fun f context bind> --------------   4.3%   4.4%   10001    0.012s
 ├─succ --------------------------------   2.4%  11.2%   10000    0.008s
 │└<extn:constr> -----------------------   8.9%   8.9%   10000    0.003s
 ├─Std.eval_cbv ------------------------   4.8%   6.0%   20001    0.007s
 └─<extn:constr> -----------------------   2.5%   2.5%   20002    0.000s

- : unit = ()
Finished transaction in 25.209 secs (24.556u,0.643s) (successful)
~~~
Without profiling it takes 6.7s and 90% of that seems to be in `constr:(S $r)`, ie with https://github.com/coq/coq/pull/17346 it takes 0.7s without profiling and 25s (!!) with profiling.

so I guess the profiling is heavilty distorting the results?
 cc @JasonGross maybe you have a better understanding of this stuff

**Review by JasonGross — APPROVED** [review]
Thank you, this is great!

> Without profiling it takes 6.7s and 90% of that seems to be in constr:(S $r), ie with #17346 it takes 0.7s without profiling and 25s (!!) with profiling.
> 
> so I guess the profiling is heavilty distorting the results?
> cc @JasonGross maybe you have a better understanding of this stuff

This does not surprise me.  This kind of profiling works best when most of the time is spent in primitive operations.  When you need to run the top level tactic 1000s of times to get any measurable result, profiling will add significant overhead.  (25s overhead on 10000 iterations is 0.0025s for the real profiling overhead for the number of operations you wrote; while this is not trivial I think it's fine; when the profile is dominated by slow primitives, profiling shouldn't add that much overhead; when the profile is dominated by the sheer number of operations being performed, profiling should not bias the profile too much, I think.  It's only when the primitives are not individually too slow, but still slow enough that you care about absolute times and not just the numbers of calls, that profiling will distort the results beyond usability.)

**Comment by JasonGross** [comment]
Can this make it into 8.17?

**Comment by Zimmi48** [comment]
> Can this make it into 8.17?

Definitely not, sorry.

**Review by JasonGross — APPROVED** [review]

**Comment by JasonGross** [comment]
> > This kind of profiling works best when most of the time is spent in primitive operations
> 
> Doesn't this defeat the purpose of the Great Plan to write most new tactics directly in Ltac2?

I don't think so.  We may eventually want some sort of hook that says "disable profiling when entering this tactic; reenable on exit", but even without that, it's still the case that we can use call counts for profiling, at least to some extent, when everything is written in Ltac2.  It would be nice to also get a version of profiling that doesn't add so much overhead at some point, though, perhaps by sampling the call stack every 0.01 seconds or something.  I guess that the same infrastructure could be used to support that mode, just have it not check/record the call stack if not enough time has passed?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
