### PR TITLE
coqdoc refactoring

### PR DESCRIPTION
**Pull request by ejgallego**
This is a unification of PR #122 and PR #128: we propose some conservative refactoring of coqdoc, please review. The commits are mostly self-contained and could partially merged.

We have been very convervative wrt to modification of old backend code, things seem to work. Tested with Coq documentation, seems to be OK; SF and CPDT seem also OK, that is, they exhibit the same artifacts in vanilla v8.5 vs the refactored version.

Some of the changes are:
- use of first class modules for output backends
- move to Format
- removal of some unused API, globals, and options
- added a jscoq backend
- removed of the seldom used --lib-subtitles option

### CODE REVIEW

**Comment by mattam82** [comment]
I need more time to review this but it looks fine, could you rebase on trunk though for integration in 8.6?

**Comment by ejgallego** [comment]
Sure, I will, thanks Matthieu!

**Comment by ejgallego** [comment]
I didn't really set my mind whether we should really push this PR or not. It is likely that the original use case doesn't apply anymore.

**Comment by maximedenes** [comment]
@ejgallego what shall we do with this PR? Would you like to get it on the 8.7 roadmap?

**Comment by ejgallego** [comment]
I am not using coqdoc anymore (switched to something closer to `coq2html`), so I'll let the coqdoc maintainers decide.

**Comment by maximedenes** [comment]
@silene and @mattam82, you're listed as coqdoc maintainers :)

What do you think of this PR? Should I tag it for merge request in 8.7?

**Comment by ejgallego** [comment]
I don't plan to support this anymore.

**Pull request closed without merging**
