### PR TITLE
CoqIDE: Avoid invalidation of an iterator in insert callback

### LINKED ISSUE #11943: CoqIDE crash
#### Description of the problem

CoqIDE consistantly crashes when editing with message
```
(coqide:588): Gtk-WARNING **: 11:08:49.687: Invalid text buffer iterator: either the iterator is uninitialized, or the characters/pixbufs/widgets in the buffer have been modified since the iterator was created.
You must use marks, character numbers, or line numbers to preserve a position across buffer modifications.
You can apply tags and insert marks without invalidating your iterators,
but any mutation that affects 'indexable' buffer contents (contents that can be referred to by character offset)
will invalidate all outstanding iterators
```
 Its happens about every 30 minutes on average.

#### Coq Version
The Coq Proof Assistant, version 8.11.0 (March 2020)
compiled on Mar 24 2020 12:42:57 with OCaml 4.06.0

Coq and CoqIDE are install via opam on MacOS.

### PR DESCRIPTION
**Pull request by herbelin**
This is an alternative to PR #12068 which hopefully treats the problem of invalid iterators at the root and fix the segfaults we observed with completion. In any cases, it cannot hurt.

**Kind:** bug fix

Hopefully fixes #11943 (see discussion there).

- [ ] Entry added in the changelog

### CODE REVIEW

**Comment by ppedrot** [comment]
It's true that it cannot hurt, but we should perform solid testing to convince ourselves that it does fix #11943. I'll merge it first and let @formalize test thoroughly the master branch.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
CI failures irrelevant, let's merge.

**Comment by ppedrot** [comment]
This PR doesn't seem to be enough, I experienced a CoqIDE crash on my machine.

**Comment by herbelin** [comment]
Zut... 

That was not in the debugger I suppose?

**Comment by ppedrot** [comment]
Unfortunately no...

**Pull request merged**
