### PR TITLE
[toplevel] Refactor command line argument handling.

### PR DESCRIPTION
**Pull request by ejgallego**
We mostly separate command line argument parsing from interpretation,
some (minor) imperative actions are still done at argument parsing
time. This tidies up the code quite a bit and allows to better follow
the complicated command line handling code.

To this effect, we group the key actions to be performed by the
toplevel into a new record type. There is still room to improve.

Depends on #6711

### CODE REVIEW

**Review by gares — APPROVED** [review]
I can't check that every single option is parsed as before.
I did check if the initialization of the system makes sense and it does. The code is way better than before.

**Comment by maximedenes** [comment]
Seems to trigger strange failures, not 100% sure if they are real ones.

**Comment by ejgallego** [comment]
The failure is real and I know what it is, it must be a silly thing but you know how the command line logic is... a bit convoluted [many cases depending if you have `-batch` etc... Will look into it later this week.

**Comment by ejgallego** [comment]
Ok so the culprit was a stupid logical error when moving a condition around, this should be good now.

**Pull request merged**
