### PR TITLE
Bench: do not save profiles from OLD as artifacts

### PR DESCRIPTION
**Pull request by SkySkimmer**
We are getting close to the 500MB compressed limit for artifacts, this should help.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@SkySkimmer seems to have worked. Is that ready to merge?

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
It is ready

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
