### PR TITLE
[build] Fix checks and notes noting 4.02.1 instead of 4.02.3

### PR DESCRIPTION
**Pull request by ejgallego**
Bumping to 4.02.3 was decided some time ago in the WG, however a
couple of places escaped updating.

### CODE REVIEW

**Comment by Zimmi48** [comment]
This was already proposed in #6121. I'd rather not have this discussion again. This "inconsistency" will disappear by itself when we upgrade to 4.05 anyways.

**Comment by maximedenes** [comment]
One thing that I really don't like with the status quo (which is due to a misunderstanding during the WG discussion btw), is that I don't think anything would detect if we release a 8.8.1 that does not compile with 4.02.1.

**Comment by ejgallego** [comment]
I didn't want to get into another version fight, but we discussed this in person this year and indeed using 4.02.1 is a bug; to all extents 4.02.1 is unsupported today. 

Also, now it seems like we have a real reason to bump the dependency to 4.02.3 so let's do it.

**Comment by ejgallego** [comment]
Note than in my view the upgrade to 4.05.0 will likely happen for 8.10, so we shouldn't rely too much on it for the short term.

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
@letouzey may be busy and I am configure's 2nd, so I'd suggest @maximedenes takes care of this.

**Comment by maximedenes** [comment]
> This was already proposed in #6121. I'd rather not have this discussion again. This "inconsistency" will disappear by itself when we upgrade to 4.05 anyways.

That discussion concluded it should not revert a commit of mine that was meant to be temporary. I never understood why we didn't fix the problem. So let's do it now!

**Pull request merged**
