### PR TITLE
[ci] document what project name should be

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@ejgallego Will you merge this one too? It looks directly related to #13633 that you just merged.

**Comment by ejgallego** [comment]
> @ejgallego Will you merge this one too? It looks directly related to #13633 that you just merged.

I can take care sure, however I'm not sure these are related; AFAICT the limitation of having to translate `foo-bar` to `foo_var` is due to `foo-bar` not being a valid shell variable name.

Hopefully we would rewrite this stuff in some better language we could indeed use the right upstream names. Not sure if this is discussed in some part of the code already [likely in the commit messages yes]

@gares , letting you some time in case you want to document the above a bit better.

**Comment by SkySkimmer** [comment]
>Hopefully we would rewrite this stuff in some better language 

We could do it in bash using associative arrays instead of variables (so eg `${refs[foo-bar]}` instead of `$foo_bar_ref`)

**Comment by ejgallego** [comment]
> We could do it in bash using associative arrays instead of variables (so eg `${refs[foo-bar]}` instead of `$foo_bar_ref`)

If that works why not? Myself I'm still interesting in using OCaml.

**Comment by gares** [comment]
I thought about that in the `project` function, but then I saw the `overlay` one and I copied it.
I can do this in another PR.

**Comment by gares** [comment]
(in the meanwhile documenting the status quo cannot hurt)

**Comment by ejgallego** [comment]
So we merge as is or do you want to add a "due to bash limitations in the naming of variables, dash cannot appear in project names" ?

**Pull request closed without merging**
