### PR TITLE
Mention ./configure in INSTALL.doc

### PR DESCRIPTION
**Pull request by Zimmi48**
As prompted in https://coq.inria.fr/bugs/show_bug.cgi?id=2831

### CODE REVIEW

**Comment by Zimmi48** [comment]
In passing I wonder if it makes sense to keep a `-nodoc` option in configure given that this is the default.

**Comment by ejgallego** [comment]
> In passing I wonder if it makes sense to keep a -nodoc option in configure given that this is the default.

IMHO yes, so I can be explicit about it and yet be future proof in case the default changes.

**Comment by Zimmi48** [comment]
You can be as explicit with `-with-doc no`

**Comment by ejgallego** [comment]
Ah OK, then it looks fine to me.

**Comment by Zimmi48** [comment]
I've added a commit that deprecates `-nodoc` following the way @maximedenes did it for `-debug`.

**Pull request merged**
