### PR TITLE
Remove test-suite/bugs/opened/bug_3395.v: not a bug

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by herbelin** [comment]
What do you mean by "not a bug"? That the inefficiency/regression disappeared? That this should be tested differently?

**Comment by SkySkimmer** [comment]
The "bug" is that `admit` declaring a fresh axiom for every call behaves differently from `admit` using a common abstract axiom.

**Comment by herbelin** [comment]
> The "bug" is that admit declaring a fresh axiom for every call behaves differently from admit using a common abstract axiom.

If that's the "bug", then OK.

**Comment by SkySkimmer** [comment]
>admit using a common abstract axiom.

Should have been "absurd" not "abstract" btw ;)

**Review by herbelin — APPROVED** [review]
This test slows down the test suite and the solution to the issue is not to use `admit`. Removal is justified. Will merge tonight.

**Comment by herbelin** [comment]
CI failures are unrelated (CanOrd in Elpi et dpdgraph et iota_add's in Coquelicot).

@coqbot: merge now

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
