### PR TITLE
Provide a reinit data for Ltac2 notations with entry level 4.

### LINKED ISSUE #14156: Ltac2 broken with async
Since https://github.com/coq/coq/pull/14094
See https://gitlab.com/coq/coq/-/jobs/1187763526

### PR DESCRIPTION
**Pull request by ppedrot**
The grammar engine has the great idea to silently delete empty levels on rule removal. Since Ltac2 level 4 is initially empty, it means that when backtracking on the loading of the Ltac2 plugin, the grammar would be in a state where the level 4 was not there at all.

There is a dedicated API for that situation in Pcoq, but it is kind of crazy that we have to use this kind of workaround when the problem is clearly that gramlib has the wrong default.

Fixes #14156: Ltac2 broken with async.

### CODE REVIEW

**Comment by ejgallego** [comment]
Note that we tried to fix the root of the problem in #9067 , maybe we should try to follow the plan there?

**Comment by gares** [comment]
Thanks for looking into this. I'm a bit surprised the fix is not to have gramlib, which we now vendor, not delete levels in the first place.

**Comment by ppedrot** [comment]
This is a hotfix, ideally gramlib should have a decent API, but this is much more work that requires design. This PR is based on the current statu quo, so ready to merge.

**Comment by ppedrot** [comment]
@JasonGross would you assign? It's kind of urgent since its triggering phony CI half-failures.

**Comment by JasonGross** [comment]
I don't really understand the code, but the CI passes, so I'll merge

@coqbot merge now

**Review by JasonGross — APPROVED** [review]

**Comment by JasonGross** [comment]
@coqbot merge now

**Pull request merged**
