### PR TITLE
coqdep: Option `-w` to adjust warnings

### PR DESCRIPTION
**Pull request by swasey**
Relevant to #10156

This PR switches coqdep to use `CWarnings` so people can promote warnings to errors, when necessary, via the command line. It does not change the set of warnings, but it necessarily changes what gets printed. (That matters to people who parse fd 2 in coqdep wrappers.)

It's a draft due to (light testing and)

- [ ] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.
  
  - [ ] Documented any new / changed **user messages**.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Looks good to me and indeed pretty useful, thanks!

**Comment by ejgallego** [comment]
@swasey note CI is broken.

**Comment by swasey** [comment]
Thanks for the quick response (and sorry about the lag).

I'll take care of the TODOs in a day or two.

**Comment by gares** [comment]
Not ready for 8.18 inclusion. I don't put a new milestone because it is a draft PR.

**Pull request closed without merging**
