### PR TITLE
Fix coq-elpi CI

### LINKED ISSUE #695: Broken in Coq CI
eg https://gitlab.inria.fr/coq/coq/-/jobs/4772378
AFAICT it's since the merge of https://github.com/LPCIC/coq-elpi/pull/684

### PR DESCRIPTION
**Pull request by rlepigre**
This should fix https://github.com/LPCIC/coq-elpi/issues/695.

### CODE REVIEW

**Comment by rlepigre** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Doesn't seem to have worked

**Comment by rlepigre** [comment]
That's odd, this does seem to fix the issue locally. That is, even after `git clean -xfd` on the branch, the following succeeds:
```bash
make world
make ci-elpi_hb
```
Is there anything else I should be trying locally?

**Comment by proux01** [comment]
I tried to add the `--root .` to build and now dune complains about
```
dune build --root . -p coq-elpi @install
dune: option '--root' cannot be repeated
```
(I don't even understand how it could be repeated)

**Comment by rlepigre** [comment]
> (I don't even understand how it could be repeated)

I believe that the `-p` option implies `--release`, which itself implies `--root .`.

**Comment by SkySkimmer** [comment]
Maybe better to call dune directly instead of through make

**Comment by rlepigre** [comment]
@coqbot run full ci

**Comment by rlepigre** [comment]
Trying to just add a `dune-workspace` file.

**Comment by SkySkimmer** [comment]
Didn't work

**Comment by rlepigre** [comment]
Damn... Is anyone able to reproduce locally? I don't know how to debug this.

**Comment by SkySkimmer** [comment]
Cannot reproduce either, I tried matching the versions in the docker image but it didn't matter.

**Comment by SkySkimmer** [comment]
@ejgallego any ideas?

**Comment by ejgallego** [comment]
> @ejgallego any ideas?

I think this is #18435 bitting you back.

**Comment by ejgallego** [comment]
There are ways to control cmt generation and dependency in Dune, I believe, but I'm not expert on that stuff.

**Comment by SkySkimmer** [comment]
I guess te easiest solution is to revert the cmt cleaning

**Comment by ejgallego** [comment]
> I guess te easiest solution is to revert the cmt deleting

That was on other hand useful, it saved quite a bit of space. I'm actually suprised to see there are rules that depend on `.cmt` files, I'm having a look.

We can disable `.cmt` stuff using `(bin_annot )` in the `env` stanza, so indeed maybe adding that setting on the CI would work?

**Comment by ejgallego** [comment]
I had a look and it seems like the culprit may be `odoc` rules, this is the only part I see `cmt` files depended on, but needs someone to have a more careful look.

**Comment by SkySkimmer** [comment]
IIUC the problem is coq-elpi says `(deps (package elpi))`, and dune knows that elpi contains some cmt files which are missing.

**Comment by ejgallego** [comment]
@SkySkimmer , correct, in this case the problem is that the `dune-package` file of elpi becomes incorrect, and there is a dep `(package coq-elpi)`.

So what happens is:
- coq-elpi has a rule that depends on `(package elpi)`
- as `elpi` is installed, `(package elpi)` is expanded to the contents of `$lib/elpi/dune-package`, which as `elpi` was built with `(bin_annot on)` contains something like:
   ```lisp
(lang dune 3.16)
(name elpi)
(version 1.19.6)
(sections (lib .) (libexec .) (bin ../../bin) (doc ../../doc/elpi))
(files
 (lib
  (.private/elpi__Builtin_map.cmi
   .private/elpi__Builtin_map.cmt
   .private/elpi__Builtin_set.cmi
   .private/elpi__Builtin_set.cmt
   .private/elpi__Builtin_stdlib.cmi
   .private/elpi__Builtin_stdlib.cmt
   .private/elpi__Compiler.cmi
   .private/elpi__Compiler.cmt
   .private/elpi__Compiler.cmti   
   ```
- the files are missing, and dune complains.

I am not sure what to do here, I see quite a few different possible fixes. Maybe the easiest is to pass `--exclude elpi` to our cleaning step?

**Comment by SkySkimmer** [comment]
I removed the cmt delete from the edge image, it seems to work.
The container registry https://gitlab.inria.fr/coq/coq/container_registry/2437 says before = 1.01GiB, after = 1.14GiB
It's not nothing but I'm not sure it's worth trying to be smarter.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
