### PR TITLE
Addressing proposal  #15562: cleaning API of functions for destructing/constructing abstractions or products wrt contexts

### LINKED ISSUE #15562: Proposal for naming/organizing the functions for destructing/constructing abstractions or products wrt contexts
Hi, this is a proposal for (re-)organizing the functions for destructing/constructing abstractions or products over contexts, following a [remark](https://github.com/coq/coq/pull/15453#discussion_r787250431) by @mattam82.

## TL;DR:

The proposal is to standardize the naming of OCaml functions destructing sequences of abstractions or dependent products combined with let-ins, under the scheme:
- either {decompose_,strip_,}{lam,prod}{_n,}{_assum,_decls,}{_red,}
- or {it_}dest{Lambda,Prod}{_wo_LetIn,_or_LetIn,}{_red,}

and to update the current exceptions to the general rule (see proposition 1' below for details on the corresponding semantics).

## Current situation

As of now, we have the following decomposition functions
- decompose_lam [Term,EConstr]
- decompose_lam_n [Term] (unused), [Extraction] (on EConstr)
- decompose_lam_assum [Term,EConstr]
- decompose_lam_n_assum [Term,EConstr]
- decompose_lam_n_decls [Term,EConstr]
- decompose_prod [Term,EConstr]
- decompose_prod_n [Term]
- decompose_prod_assum [Term,EConstr]
- decompose_prod_n_assum [Term,EConstr] (works like decompose_lam_n_decls rather than like decompose_lam_n_assum)

The following functions return the body (i.e. snd (decompose_{lam,prod}{_n,_assum})
- strip_lam [Term]
- strip_lam_n [Term] (unused)
- strip_lam_assum [Term] (unused)
- strip_prod [Term] (unused)
- strip_prod_n [Term] (unused)
- strip_prod_assum [Term]

The following functions return the context (i.e. fst (decompose_{lam,prod}{_n,_assum})
- lam_assum [Term] (unused)
- lam_n_assum [Term] (unused)
- prod_assum [Term], [Hipattern] (on Econstr)
- prod_n_assum [Term]

Non-standard variants
- Nativenorm.decompose_prod/Vnorm.decompose_prod: destProd with reduction and name forcing
- decompose_prod_letin, ad hoc, used internally to termops.ml, I propose to make it local to termops.ml

Functions decomposing using whd-reduction
- dest_prod [Reduction], splay_prod [Reductionops]
- dest_prod_assum [Reduction], splay_prod_assum [Reductionops]
- splay_prod_n [Reductionops]
- dest_lam [Reduction], splay_lam [Reductionops]
- dest_lam_assum [Reduction]
- splay_lam_n [Reductionops]

#### Proposition 1

It does not make sense to strip both {lam,prod} and let-ins by counting only {lam,prod} without telling what to do with the remaining let-ins on the body. So, the proposition is to remove the current behavior of decompose_lam_n_assum and adopt the following:
- {lam,prod}{_n,}assum means removing *only* {lam,prod} (and counting only {lam,prod}) but returning a rel_context
- {lam,prod}{_n,}decls means removing {lam,prod} *and let-ins* and returning a rel_context
- {lam,prod}{_n,} means, like now, removing only {lam,prod} (and counting only {lam,prod}) and returning a list of assumptions)

This means:
- adding decompose_lam_decls as a replacement for the current semantics of decompose_lam_assum (i.e. including let-ins)
- renaming decompose_prod_n_assum into decompose_prod_n_decls, which is what it does according to this proposition
- adding a new decompose_prod_n_assum which works similarly to decompose_lam_n_assum
- otherwise, stopping decomposing let-ins in decompose_{lam,prod}{_n,}_assum (i.e. one needs the decls suffix to decompose let-ins)
- in particular the two existing occurrences of decompose_lam_n_assum disappears (the one in inductive.ml was a bug: it needed reduction, see #15453; the one in inv.ml is actually assuming no let-ins, i.e. the new proposed behavior fits)

#### Proposition 1'

Name all {lam,prod} decomposition functions using only two naming schemes:

- {decompose_,strip_,}{lam,prod}{_n,}{_assum,_decls,}{_red,} for multiple decomposition
- dest{Lambda,Prod}{_red,} for one-step decomposition

The meaning for {decompose_,strip_,} is the following:
- decompose: returns context and body
- strip: returns body
- nothing: returns context

The meaning for {_assum,_decls,} is as in proposition 1.

The meaning of {_n,} is to stop after n {assum,decls,} or to continue until there is no more {assum,decls}.

The meaning of _red is to additionally whd-reduce to find the {assum,decls,} (this requires to pass the environment)
- with assum or nothing, reduction is whd_all
- with decls, reduction is whd_allnolet

In particular:
- {dest,splay}_{lam,prod} are renamed to decompose_{lam,prod}_red
- splay_{lam,prod}_n are renamed to decompose_{lam,prod}_n_assum_red (assum because no let-ins)
- {dest,splay}_{lam,prod}_assum are renamed to decompose_{lam,prod}_decls_red (decls because let-ins are preserved)
- {decompose_,strip_,}{lam,prod}_assum are renamed to decompose_{lam,prod}_decls (decls because let-ins are preserved)

Note: An alternative to the decompose radical would be to use instead the prefix it_dest and to capitalize {lam,prod}. One would then respectively have: {it_}dest{Lambda,Prod}{_wo_LetIn,_or_LetIn,}{_red,}.

Note: An alternative to the suffix red could be a prefix whd (following the whd_all) or hnf (following the model of hnf_prod_applist).

Note: An alternative to renaming many "assum" to "decls" would be to keep "assum" and rename the only exception (namely decompose_lam_n_assum) in something else. However "decls" is better to mean both Lam/Prod and LetIn and "assum" to mean only Lam/Prod, consistently with the other uses of "assum" in the codebase, so even if it is more renaming, this seems better.

Note: should {lambda,prod}_app{list,vect}_assum be renamed into {lam,prod}_app{list,vect}_decls? Or maybe in {lam,prod}_app{list,vect}_context?

Note: should lam be replaced by lambda by consistency with Lambda/Prod?

#### Proposition 2

Move all Termops.{it_,}mk{Lambda,Prod}{,{_or,_wo}_Letin} etc. in EConstr where some already exist duplicated.

Incidentally, deprecate compose_lam [Term, EConstr] which is redundant with it_mkLambda.

#### Proposition 3

Termops has both extensions of Term and extensions of EConstr. A proposition is to create EConstrops out of Termops for what is relevant to EConstr and to keep in Termops only extensions of Term (i.e. constr related).

An alternative is to have only EConstr and to move the econstr part of Termops in EConstr.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** cleanup

Overlay for Equations: mattam82/Coq-Equations#504

Fixes / closes #15562

This organizes the naming of functions for destructing/constructing abstractions or products wrt contexts around the schemes "{decompose_,strip_,}{lam,prod}{_n,}{_assum,_decls,}{_red,}" and "dest{Lambda,Prod}{_red,}". See #15562 for details (from there, it implements propositions 1', 2 and the alternative in proposition 3; it implements note 2 using `hnf_`; it implements notes 3, 4 and 5; proposition 1 is implemented but with some remaining confusion regarding _assum, see #17947 and the addendum to #15562; note 1 is _not_ implemented).

Better to merge #15453 (done), #15524 (done), #15565 (done) first.

- [x] take a decision on possibly using `hnf_` (like in `hnf_prod_applist`) rather than `_red` to mean that one reduces before looking for a binder (decision is to use `hnf_`)
- [x] keep old names with a deprecation notice? or at least document the changes (both are done)
- [x] goes one step further in uniformization and easiness to remember by using the radical `lambda` rather than `lam` (consistently with `mkLambda`, `destLambda` etc.)

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Are there any dependencies left to merge?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@herbelin please link overlay PRs in the opening comment of this PR

**Comment by herbelin** [comment]
Overlay link: done

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
