### PR TITLE
Move bugs that have been closed on Bugzilla

### PR DESCRIPTION
**Pull request by tchajed**
To find these bugs, I searched for all the open bugs that are resolved by visiting the following URL, run from the root of the Coq sources.

```
$ echo 'https://coq.inria.fr/bugs/buglist.cgi?bug_id_type=anyexact&bug_status=RESOLVED&list_id=331382&product=Coq&query_format=advanced&resolution=FIXED&bug_id='$(ls test-suite/bugs/opened/*.v | grep -o '\d\+' | tr '\n' ',')
```

### CODE REVIEW

**Comment by maximedenes** [comment]
There is something odd here. Usually when moving a test case from open to closed, you need to invert the logic of the test (typically remove Fail).

The test case `1501.v` is incorrect. In fact, I'm guessing the bug should have been closed with INVALID.
`2456.v` still fails, for a different reason, so it may be a regression.
`2814.v` seems a legitimate move since it now fails whereas it was emitting an anomaly before.
`3100.v` is similar
`3320.v` is probably not really testing the bug
`3794.v` I don't understand why the bug is closed.

**Comment by Zimmi48** [comment]
Tagging as `help wanted` because I'm guessing the lack of response from @tchajed means that he doesn't really want to spend more time on this.

**Comment by tchajed** [comment]
Ok, I checked the new list of resolved bugs in `opened/`. Here are the details from manually checking each bug:

- #1501: example was invalid, but added Matthieu Sozeau's example (with a small fix for implicits).
- #2814: still fails, but not with an anomaly (added an Undo to try to trigger the bug)
- #3209: removed duplicate copy in `bugs/opened/`
- #3320: still fails, but not with an anomaly
- #3916: removed duplicate copy in `bugs/opened`
- #3100: still fails, but not with an anomaly
- #3948: removed duplicate copy in `bugs/opened`
- #2456: fixed, and amended slightly
- #3230: fixed, example works
- #3938: fixed, example works

not addressed:
- #3794: the bug report says the behavior is buggy and it hasn't changed - I think this bug should remain open
- #4781: clearly still open, due to a regression
- #4813: indeed goes through with `Program`, but not otherwise - was this ever fixed?

**Review by mattam82 — APPROVED** [review]
This looks fine to me, indeed the changes to 1501 are alright. For issue #4813 this is another instance where a bidirectional typechecking flag or something more general to control inference would be useful.

**Comment by Zimmi48** [comment]
There is no code owner for the test-suite (maybe for the same reason that there is no code owner for CHANGES). @maximedenes do you want to take care of this PR?

**Comment by Zimmi48** [comment]
@mattam82 Since you approved this and it has no owner, will you take care of merging it?
@tchajed Can you rebase? It should be straightforward.

**Comment by tchajed** [comment]
Rebased.

**Comment by maximedenes** [comment]
I'll merge, since this has been approved.

**Pull request merged**
