### PR TITLE
[CI] Bump ci-jasmin

### PR DESCRIPTION
**Pull request by JasonGross**
cf https://github.com/coq/coq/pull/18449#issuecomment-2118895265

This is to allow coqbot to minimize #18449, cf https://github.com/coq/coq/pull/18449#issuecomment-2119523320

### CODE REVIEW

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
C.f. https://github.com/jasmin-lang/jasmin/pull/799

**Comment by Alizter** [comment]
Why are we pinning it to brgin with?

**Comment by proux01** [comment]
https://github.com/coq/coq/pull/18449#issuecomment-2118895265

**Comment by gares** [comment]
```diff
diff --git a/proofs/compiler/lower_spill_proof.v b/proofs/compiler/lower_spill_proof.v
index 88fb480b..8c64653a 100644
--- a/proofs/compiler/lower_spill_proof.v
+++ b/proofs/compiler/lower_spill_proof.v
@@ -213,8 +213,8 @@ Proof.
   move: hx; rewrite /get_gvar /mk_lvar /= => /get_varP /= [? hd ?]; subst vx.
   have ? : (evm s).[x] = vt; last subst vt.
   + by apply: (truncate_val_subtype_eq htr); apply getP_subtype.
-  have hvm : vm.[x <- (evm s).[x]] =1 vm.
-  + move=> z; rewrite Vm.setP; case: eqP => // ?; subst z.
+  have hvm z : vm.[x <- (evm s).[x]].[z] = vm.[z].
+  + rewrite Vm.setP; case: eqP => // ?; subst z.
     rewrite  vm_truncate_val_eq; first by apply heq.
     by apply: truncate_val_has_type htr.
   exists vm.[x <- (evm s).[x]].
```

**Comment by proux01** [comment]
Done in #18449

**Pull request closed without merging**
