### PR TITLE
Fast path in Unification.make_abstraction_core.

### PR DESCRIPTION
**Pull request by ppedrot**
We keep track of the variables available from the context in order to skip declarations when the pattern mentions variables not yet introduced. This is very slightly non-equivalent to the previous code as a variable may disappear by reduction through unification. But the code already makes a similar assumption when computing dependent declarations. In practice it should not matter.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
There are some speedups in fiat-crypto, but nothing as violent as #18925. Should we merge nonetheless?

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
