### PR TITLE
Moving back interface-only files to mli after API removal.

### PR DESCRIPTION
**Pull request by ppedrot**
This indicates intent, and is probably better for the build system (there used to be races due to mli-lacking source files, not sure if still the case though).

### CODE REVIEW

**Comment by ejgallego** [comment]
As far as I understand many OCaml users explicitly recommend against this practice. Quoting `dune`'s README: https://github.com/ocaml/dune#mli-only-modules

> Due to the low-level details of OCaml compilation, it is currently possible to write a module that has only a .mli and no .ml file. This works as long as the mli contains only type declarations.
>
> This is not a properly supported feature of the compiler, and in particular it is not possible to alias such modules or use them as the argument of a functor. Moreover, if you do write a value declaration, or even just define an exception in the .mli, then you won't get an error until the point where you link an executable using this module.
>
> For these reason, mli only modules are not recommended by Jbuilder until the compiler support them properly.

I would indeed prefer we don't switch back to `.mli`-only files. First, I don't really see the advantages, second, this approach is at odds with a modular view on Coq, and in particular with #6512 and an upcoming PR adding `dune` support to Coq.

**Comment by ppedrot** [comment]
> and in particular it is not possible to alias such modules or use them as the argument of a functor

AFAIU this has been fixed (in 4.06?).

> I would indeed prefer we don't switch back to .mli-only files. First, I don't really see the advantages,

As advocated in the dune thread you mention, mli-only files do have their interest, and the fact that one particular build system does not handle them doesn't look like a good argument to me...

> second, this approach is at odds with a modular view on Coq, and in particular with #6512 and an upcoming PR adding dune support to Coq.

What does it have to do with modularity? I understand that it's at odds with dune, but having an alternative build system needs to be somewhat motivated, we don't do that just because it's the new shiny toy that's trendy amongst OCaml hipsters.

Also cc-ing @letouzey, I think he was the fiercest defender of the cause.

**Comment by ejgallego** [comment]
> AFAIU this has been fixed (in 4.06?).

Not that I know of, but not sure.

> As advocated in the dune thread you mention, mli-only files do have their interest.

I still fail to see what is the interest they have. Could you elaborate as to why we do need them?

IMHO such "half-modules" live in a very strange limbo, as they are not proper modules, and in particular they have seemed to encourage bad practices wrt modularity as files belonging to very different modules are "dumped" together in that directory. For example, how are we supposed to implement properly a META file for Coq, what should `-package coq.engine` do wrt `-I` ?

See also: https://discuss.ocaml.org/t/future-of-mli-only-module-setups/445

**Comment by ejgallego** [comment]
> having an alternative build system needs to be somewhat motivated, we don't do that just because it's the new shiny toy that's trendy amongst OCaml hipsters.

I'll leave `dune` discussion to its PR as indeed it is mostly unrelated to this [dune could generate the `ml` files on the fly so that's not a problem, just a bit more burden], but your statement on `dune` is just a bit far from what the reality is.

**Comment by maximedenes** [comment]
I'm wondering if there's not a _quiproquo_ here. IMHO the current state is not ideal because we have `.ml` files without interfaces, so nothing prevents somebody from adding code there, plus that can create race conditions in our current build system.

However, the idea of turning those files into `.mli` ones doesn't seem to me like the right solution. I would much prefer to have components with clear interfaces, and I don't see any advantage in mixing all those interfaces in one single folder. I think this is the view @ejgallego has with the `META` file.

So I guess the solution would be rather to put interfaces right where they belong (in each component), which would make the system easier to grasp.

**Comment by ejgallego** [comment]
> So I guess the solution would be rather to put interfaces right where they belong (in each component), which would make the system easier to grasp and develop modularly.

That's #6512 . In fact I agree with @maximedenes in the sense that a mli-only file seems of little use in our case, what's the value of having `foo` and `foo_ops` ? I think that `foo` is more idiomatic (and allows using `foo` as a functor parameter. [I think https://github.com/coq/ceps/pull/19 tries to address some of the above points]

On the other hand due to hooks and lots of static linking initialization we are still far from having a true modular system, and there are issues such as printing (see #6524) that don't have a clear proposal yet.

I guess we will find out soon as I was recently contacted by some people interested in using some parts of Coq only and they will likely see the system from the `META` point of view.

**Comment by ppedrot** [comment]
@maximedenes I think we agree, I'm not actually saying the files should be in the `intf` folder, quite the contrary. What I'm advocating against is code duplication that would be created by adding both ml and mli files whose only purpose is to define types, potentially large like e.g. ASTs tend to be.

**Comment by Zimmi48** [comment]
> What I'm advocating against is code duplication

It would seem to me that you are arguing against the whole interface-file idea. Indeed, this is a source of code duplication. An alternative approach exists. This is the one implemented by Haskell.

**Comment by ejgallego** [comment]
> What I'm advocating against is code duplication

The current status avoid code duplication by using `.ml`-only files. I believe the problem of "having code added to them" is minor, and in fact, not a problem at all.

**Comment by SkySkimmer** [comment]
To have both ml and mli, instead of copying the files in git we could do it at make time. I'm not sure that's worth doing.

**Comment by ppedrot** [comment]
> It would seem to me that you are arguing against the whole interface-file idea. Indeed, this is a source of code duplication. An alternative approach exists. This is the one implemented by Haskell.

Yes, and by Rust as well. I personally hate this approach because it is not easy to extract the relevant information as it tends to be drowned in a sea of noise, which usually forces you to use a dedicated tool to get it separately. In contrast, mli files have this nice side that you can read it as a text file and you can also write there a nice terse summary and potentially vast documentation of the content of that module.

> The current status avoid code duplication by using .ml-only files. I believe the problem of "having code added to them" is minor, and in fact, not a problem at all.

I see two relatively minor but annoying problems:
1. It generates useless modules that get linked even though they're just empty.
2. As a developer, it forces you to remember that those ml files are special and that you have to look for it instead of the corresponding mli file to read the documentation.

I've been personally bitten several times by the second point, it's a real annoyance to my workflow.

> To have both ml and mli, instead of copying the files in git we could do it at make time. I'm not sure that's worth doing.

I think git understands soft links, and tries to emulate them on platforms that don't support them. At the very last, I'd like to have the ml file to be a symbolic link to the mli file...

**Comment by ejgallego** [comment]
@ppedrot I agree with most of your points, however I am still missing why do we want `foo` and `foo_ops` as opposed to just `foo`.

**Comment by psteckler** [comment]
I'll make the argument that special cases are bad/confusing, so having some modules be `.mli`-only, and others not, is not desirable. The same argument applies to `.ml`-only modules.

**Comment by ejgallego** [comment]
IMHO the real showstopper for the `mli` vs `ml` discussion is that you cannot wrap `mli`-only modules, that is to say, no way to put a `mli`-only module in a wrapped namespace `Kernel` for example.

**Comment by Zimmi48** [comment]
> I think git understands soft links, and tries to emulate them on platforms that don't support them. At the very last, I'd like to have the ml file to be a symbolic link to the mli file...

So what about adopting this solution for now?

**Comment by ejgallego** [comment]
> So what about adopting this solution for now?

I think there is nothing wrong with the current situation.

**Comment by Zimmi48** [comment]
> I think there is nothing wrong with the current situation.

You didn't read @ppedrot comment well then:

> I see two relatively minor but annoying problems:
> 
>   1. It generates useless modules that get linked even though they're just empty.
>   2. As a developer, it forces you to remember that those ml files are special and that you have to look for it instead of the corresponding mli file to read the documentation.

At least, the symlink solution would solve Pierre-Marie's second problem.

**Comment by ejgallego** [comment]
1. is not a problem but actually an improvement,
2. why are those files special? why is it a problem to add functions to such files?

AFAICT nobody but @herbelin in #6512 has even tried to justify .mli-only files.

**Comment by ppedrot** [comment]
@ejgallego Once again, you're mixing two things:
- the problem of the `intf` folder, about which I fully agree with you.
- the existence of mli-only files, which I personally support.
The two above points are completely orthogonal, so please don't try to bring up arguments against `intf` coming from different PRs.
 
And also, @letouzey is probably not following the github notifications but he did have a few good arguments in favour of mli-only files. Maybe if we ping him enough he'll end up popping here.

**Comment by ejgallego** [comment]
> the existence of mli-only files, which I personally support.

Ok, so why do you support then? I guess you have your own reasons, or is that support coming by transitivity?

As far I can see, they have many downsides (including the _critical one_ of not being possible to alias them) vs the single "benefit" of allowing only type definitions. [Which I claim is also a downside].

Not to say that big players in the OCaml space have long chosen to put interfaces in .ml files, they do have good reasons indeed.

**Comment by ppedrot** [comment]
> including the critical one of not being possible to alias them

That's an OCaml bug, not a synthetic a priori fact.

> Not to say that big players in the OCaml space have long chosen to put interfaces in .ml files, they do have good reasons indeed.

Reference needed, or at least a more comprehensive survey of the use of ml-only files in the wild. Otherwise, I'll consider this as FUD.

> Ok, so why do you support then? I guess you have your own reasons, or is that support coming by transitivity?

So, the untold assumption of mine is that *every ml file should come with an mli file*. There are various reasons to that, but the two main arguments from the top of my head are:
1. A social one: as I've already said, mli files are a de-facto standard for documentation, and people expect to find it there. No mli file means that you puzzle people.
2. A tooling one: ml-only files need to be handled specially by the build system, because they do not respect the same dependency rules. Indeed, say `A` logically depends on `B`. Then `A.cmi` depends on `B.cmi` and `A.cmo` depends on `A.cmi` and `B.cmo`. The problem is that in absence of the `B.mli` file, the build system needs to be aware that there is no mli file otherwise you get into race conditions, as `B.cmi` can be alternatively made out of `B.ml` in this specific case. So you need a non-uniform rule, depending on the existence of another file.

**Comment by ppedrot** [comment]
> Not to say that big players in the OCaml space have long chosen to put interfaces in .ml files, they do have good reasons indeed.

For the record, OCaml itself uses mli-without-ml files, precisely for AST types. @ejgallego Do you consider the OCaml compiler not to be a big player of the OCaml space?

**Comment by ejgallego** [comment]
> For the record, OCaml itself uses mli-without-ml files, precisely for AST types. @ejgallego Do you consider the OCaml compiler not to be a big player of the OCaml space?

I have not discussed with OCaml people about this choice, but I do have discussed with other users and I tend to share that point of view.

The balance seems pretty clear to me, `mli` only modules bring quite a few problems as of today, including they can't be used as a real module in many places, whereas the benefit is very small IMHO.

**Comment by maximedenes** [comment]
It seems this is not going to converge, so let's postpone to 8.9.

**Comment by ppedrot** [comment]
Can we at least create a soft link between the two files, as advocated on another thread?

**Comment by Zimmi48** [comment]
Can't we just move all these types in appropriate locations (near functions that use them) and guarantee that no `.ml` comes without a `.mli` and no `.mli` comes without a `.ml`?

**Comment by ejgallego** [comment]
Note @ppedrot that I'd rather keep the `.mli` files only, so "morally", I agree with you, and understand your position.

However, their implementation is just broken, so we have no choice for now if we ever want to any kind of packing or alias. About symlinking I dunno, that's OK for me but I don't know what the implications are. I'd rather put the symlinks in git proper instead of have a tailor-made rule in make.

**Comment by ejgallego** [comment]
We need to progress on this:
- I am OK having `mli`-only files, even if then I have to manually annotate them in `Dune` so an implementation is generated,
- I am not OK having such files in plugin as the current build system cannot alias them,
- I am not OK having duplicated files.

**Comment by maximedenes** [comment]
> We need to progress on this, not being able to alias certain modules is creating a lot practical problems for me:
> 
> I am OK having mli-only files, even if then I have to manually annotate them in Dune so an implementation is generated,
> I am not OK having such files in plugins as the current build system cannot alias them and the generated packs are wrong,
> I am not OK having duplicated files.

+1 (on the three items)

**Comment by ejgallego** [comment]
> +1 (on the three items)

A remaining question is "is it worth keeping the `.mli` files in the core codebase?" What are the advantages vs the disadvantages of having to use a big hack.

**Comment by ejgallego** [comment]
So who's gonna be the driver for this? I was asked a review by @ppedrot and I think my short-term position is summarized in [this comment](https://github.com/coq/coq/pull/6664#issuecomment-375425526)

In the medium term, I think that `.mli`-only files should become very rare in Coq. For most the `.mli`-only files we already have a `Foo` and `Foo_ops` file, which is an artificial split that makes devs and docs worse, quite a few of us think.

**Comment by ejgallego** [comment]
So this issue with `.mli`-only files came up in a totally unrelated discussion but I thought I'd share it here.

A strong reason to store interfaces in `ml` files is that in many cases, you want to apply some `[@@deriving ...]` to your types. For example, it is common to derive comparators, debug printers, or serializers this way.

The `.mli` setup doesn't allow you to do that without complex hacks.

**Comment by ppedrot** [comment]
I don't know what to do with this PR, I think closing it is the most reasonable solution locally. That said, I still want my mli files back...

**Comment by ejgallego** [comment]
I think you can have your `.mli` backs if you want.

I am not opposed to it, but be aware of some of the limitations, in particular with the current build system it is not possible to have `mli` only files in packed modules in a good way [that is, in plugins].

Also I am not sure about other drawbacks such as those I pointed out about generating structures for types. But absolutely keep this PR open and maybe let's have a discussion in the IM.

**Comment by Zimmi48** [comment]
> w.r.t. avoiding duplication, there are also many interesting patterns that have recently emerged in the OCaml community that could be of interest for Coq.

Can you say more?

**Comment by ejgallego** [comment]
> Can you say more?

I am not an expert, but those usually involve using modules aliases [introduced in 4.02 I do believe] and indeed pure interface files of the form `foo_intf.ml`. I will try to inform myself better to see how large libraries are being organized in this way.

**Comment by ppedrot** [comment]
I'm closing this PR for the moment, but please make my mli great again!

**Pull request closed without merging**
