### PR TITLE
[toplevel] Properly redirect stdout on `Redirect` vernac.

### LINKED ISSUE #6130: `Redirect` does not redirect typeclass resolution log in 8.7
#### Version

8.7.0

#### Operating system

Linux

#### Description of the problem

The following used to produce log.txt.out file with typeclass resolution log unde Coq-8.6.
Under 8.7 it does not redirect to file but rather prints to output. The file created but it is empty.

```
Typeclasses eauto := debug.
Redirect "log.txt" setoid_rewrite Rule.

```

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #6130, it was a silly omission from a previous output
refactoring.

We redirect all channels as this was the implied semantics of the old
command.

### CODE REVIEW

**Comment by ejgallego** [comment]
Note that the semantics of redirect are indeed "suspicious" after the feedback system got in place for messages. This commit really doesn't address that, but maybe it should.

**Comment by ejgallego** [comment]
In particular Redirect will remain broken in CoqIDE I think :(

**Comment by ejgallego** [comment]
Umm, I would welcome some discussion about what desired semantics for this feature are.

**Comment by maximedenes** [comment]
@ejgallego If you don't mind, I'll cancel the Travis build job for now, to reduce backlog. I don't think `Redirect` is used in any of our tests.

**Comment by ejgallego** [comment]
I think we can do as follows: apply this less invasive fix to 8.7.1, and the more invasive one could go in 8.8.

**Comment by ejgallego** [comment]
In fact I am convinced that in 8.8 / 8.9, time permitting, we should change a lot of things on the feedback side.

**Comment by Zimmi48** [comment]
@ejgallego May I remove the `needs: progress`, `needs: testing`, `help wanted` labels to put this PR in the merge queue? We can decide to keep the corresponding bug open if it needs more work before 8.8.

**Comment by ejgallego** [comment]
Thanks @Zimmi48 for taking care of this. The situation is as follows:
- I think the current fix is good for 8.7, but the bug is indeed not fully solved.
- I hope we can ship a better fix in 8.8, however it would be better to push the fix after some other changes are done.

So if you think than merging this and keeping the bug open is OK, please go ahead!

**Comment by maximedenes** [comment]
Now launching a Travis build.

**Pull request merged**
