### PR TITLE
Minor phrasing fixes

### PR DESCRIPTION
**Pull request by mattam82**
Spotted by @maximedenes and myself

**Kind:** documentation

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

@mattam82 Do not use the web edit button of GitHub because it creates a branch here (and doesn't support creating a branch on your fork) when you have write access. If you want to use the button, you can first go to your fork, synchronize master (this is now supported in the web interface), use the edit button, and change the target of the PR to upstream.

**Comment by mattam82** [comment]
Ah ok. That's quite annoying for users who would like to contribute...

**Comment by Zimmi48** [comment]
It is only a problem for contributors with write access.

**Comment by mattam82** [comment]
What happens to contributors without write access?

**Comment by Zimmi48** [comment]
For them it works the way we want it: it creates a branch on their fork (it even creates the fork if it doesn't exist).

**Pull request merged**
