### PR TITLE
Don't specialize dep hyps in zify

### LINKED ISSUE #17936: `zify` / `Z.euclidean_division_equations_cleanup` should not instantiate dependent hypotheses
#### Description of the problem

```
From Coq Require Import Lia ZArith Zify PreOmega.
Open Scope Z_scope.

Goal forall m n, n * m = 1 -> n = 1 \/ n = -1.
  pose proof Z.mul_eq_1; intros.
  Z.to_euclidean_division_equations.
  assumption. (* should not succeed *)
Qed.
(* swapped n m order *)
Goal forall n m, n * m = 1 -> n = 1 \/ n = -1.
  pose proof Z.mul_eq_1; intros.
  Z.to_euclidean_division_equations.
  Fail assumption. (* correctly does not succeed *)
  let T := type of Z.mul_eq_1 in
  lazymatch goal with
  | [ H : T |- _ ] => idtac
  | _ => fail 0 "Z.to_euclidean_division_equations should not mangle dependent quantifiers"
  end.
Abort.
```

Sorry, this is my blunder with not adequately checking for non-dependency around
https://github.com/coq/coq/blob/e78e90d219e66ce00bf9e78e228ac51b5ab17020/theories/omega/PreOmega.v#L92-L99

### PR DESCRIPTION
**Pull request by JasonGross**
`zify` / `Z.euclidean_division_equations_cleanup` now no longer instantiates dependent hypotheses.

This will by necessity make `Z.to_euclidean_division_equations` a bit weaker, but the previous behavior was overly sensitive to hypothesis ordering.  Users wishing to reclaim the previous power (and then some) may use this alternative:
```coq
Ltac saturate_at :=
  let unique_pose_proof lem :=
    let ty := type of lem in
    lazymatch goal with
    | [ H : ty |- _ ] => fail
    | _ => pose proof lem
    end in
  repeat match goal with
    | [ H : forall x : ?T, _, H' : ?T |- _ ] => unique_pose_proof (H H')
    | [ H : forall a (x : ?T), _, H' : ?T |- _ ] => unique_pose_proof (fun a => H a H')
    end.
Ltac Zify.zify_internal_to_euclidean_division_equations ::= Z.to_euclidean_division_equations; saturate.
Ltac Zify.zify_post_hook ::= Z.to_euclidean_division_equations; saturate.
```

Users who were overly sensitive to the previous behavior can replace `unique_pose_proof` with `specialize` to more closely match the previous fragile behavior.

Advanced users who were relying on `zify` to instantiate hypotheses *dependently* quantifying over proofs of `?x = ?x`, `?x <= 0`, and/or `0 <= ?x` and for some reason wish to continue relying on this behavior, may feel free to make the questionable decision of adding the following cases to `saturate`:
```coq
    | [ H : forall pf : ?x = ?x, _ |- _ ] => unique_pose_proof (H eq_refl)
    | [ H : forall a (pf : ?x = ?x), _ |- _ ] => unique_pose_proof (fun a => H a eq_refl)
    | [ H : 0 <= ?x -> _, H' : ?x <= 0 |- _ ] => unique_pose_proof (fun pf => H (@Z.eq_le_incl 0 x (eq_sym pf)))
    | [ H : ?A -> 0 <= ?x -> _, H' : ?x <= 0 |- _ ] => unique_pose_proof (fun a pf => H a (@Z.eq_le_incl 0 x (eq_sym pf)))
    | [ H : ?x <= 0 -> _, H' : 0 <= ?x |- _ ] => unique_pose_proof (fun pf => H (@Z.eq_le_incl 0 x pf))
    | [ H : ?A -> ?x <= 0 -> _, H' : 0 <= ?x |- _ ] => unique_pose_proof (fun a pf => H a (@Z.eq_le_incl x 0 pf))
```

Fixes #17936

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.
- [x] Opened **overlay** pull requests. (fingers crossed, hopefully none)

### CODE REVIEW

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
@coqbot ci minimize fiat_crypto

**Review by andres-erbsen — APPROVED** [review]

**Comment by andres-erbsen** [comment]
This is a meticulous fix to a silly unintended behavior. I intend to merge the next time I look at this unless there are objections.

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Pull request merged**
