### PR TITLE
Support for notations with autonomous only-parsing and only-printing declarations.

### LINKED ISSUE #7462: (only printing) notations should not remove (only parsing) notations
#### Version

8.8.0

#### Description of the problem

This code should work
```coq
Notation "$ x" := (@id nat x) (only parsing, at level 0).
Notation "$ x" := (@id bool x) (only printing, at level 0).
Check $1.
(* Error: Unknown interpretation for notation "$ _". *)
```
Similarly, this code should work:
```coq
Notation "$ x" := (@id bool x) (only printing, at level 0).
Notation "$ x" := (@id nat x) (only parsing, at level 0).
Check $1. (* Error: Syntax Error: Lexer: Undefined token *)
```

See also #5567
cc @herbelin

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix / wish

Fixes / closes #7462.

- [X] Entry added in CHANGES (put in section 8.9 / to be put in section 8.8.1 if seen as a fix).

Added note: #5567 not fixed.

### CODE REVIEW

**Comment by ejgallego** [comment]
Taking this as interp's 2nd.

**Comment by ejgallego** [comment]
I am neutral as whether this should go into 8.8.1 , I guess that if @JasonGross would appreciate it, the change is small enough as not pose significant risk I believe.

On an related note, we should move metasyntax from `vernac`, the Dune build indicates that with current code it can sit in `printing`, or `parsing` if a bit of refactoring is done.

**Comment by Zimmi48** [comment]
It would make sense to consider this as a bug fix: only printing and only parsing notations should not interact. I don't see any threat to compatibility either. @maximedenes if you disagree, please say so. However, I would then rephrase the entry in CHANGES: "Fixed unwanted collision between only-parsing and only-printing notations (cf. #7462)."

**Review by ejgallego — APPROVED** [review]
Looks good to me, I wonder whether we should make the `onlyprint` parameter mandatory but it is likely not a good idea.

@herbelin , would you mind implementing @Zimmi48 's suggestion in the wording of CHANGES?

**Comment by herbelin** [comment]
Added a section on 8.8.1 changes and reworded.

**Comment by ejgallego** [comment]
Yup it seems like the phrasing could use some improvement, Théo's working looked OK to me.

**Comment by Zimmi48** [comment]
@ejgallego You probably missed the recent update by @herbelin. The phrasing is now closer to what I had suggested and LGTM.

**Comment by ejgallego** [comment]
Indeed I checked but for some reason I saw the old page. Looks fine to me, but maybe we would like to add the issue / PR number to changes? [I tend to find this useful]:

>  Fixed unexpected collision between only-parsing and only-printing notations. (#7477)

**Comment by herbelin** [comment]
OK, added issue number.

We shall have to remember though that the list is not exhaustive.

I used "issue" while, formerly, "BZ" was used. "BZ" seems now inappropriate but I did not take the responsibility of changing the existing BZ into "issue" or whatever short terminology is used to refer to "issues".

**Comment by Zimmi48** [comment]
Issue is fine. Just `#` is also fine since there are no more collisions between PR numbers and bug report / issue numbers.

**Pull request merged**
