### PR TITLE
Add Ltac2.Constr.equal_nounivs

### LINKED ISSUE #10091: Please expose constr_eq and constr_eq_nounivs

### PR DESCRIPTION
**Pull request by JasonGross**
Close #10091

- [ ] Added / updated **test-suite**. (should I?)
- [x] Added **changelog**.
- [ ] Added / updated **documentation**. (is there any to add?)

### CODE REVIEW

**Comment by ppedrot** [comment]
I'm not sure that reflecting the mess of the OCaml implementation is a good strategy for Ltac2. I'd rather have some generic constr equality function with an abstract set of flags to tweak the various possible behaviours.

**Comment by JasonGross** [comment]
@ppedrot That sounds like a good idea to me.  Do you have a particular interface in mind?  (How does one do "abstract set of flags" in Ltac2?)

**Comment by ppedrot** [comment]
If #10117 was implemented first we would be able to have a record with a default instance and explicit setting of flags with the `with` clause. Right now, this requires more machinery with setter-style API over an opaque type.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/issues/10117 is now implemented

**Pull request closed without merging**
