### PR TITLE
[ssr] anomaly -> error

### PR DESCRIPTION
**Pull request by gares**
Looks like this bug was introduced when unification started raising the
UnableToUnify exception in 8ac929e .
I now turn this exception into a PretypeError that is correctly catched
and printed.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@gares Why is this tagged as "needs: fixing"?

**Comment by herbelin** [comment]
Looks like a canonical fix. The assignee should be @maximedenes.

**Comment by maximedenes** [comment]
@gares is the failure spurious?

**Comment by gares** [comment]
`ls: cannot access '/builds/coq/coq/_install_ci/bin/': No such file or directory`

I'd say yes. I've restarted it...

**Comment by Zimmi48** [comment]
That's because the CI run is more than a week old so the artifacts were removed. Anyways, at this time, VST was broken indeed.

**Comment by gares** [comment]
@maximedenes this is ready

**Comment by gares** [comment]
closed by mistake, rebased

**Comment by Zimmi48** [comment]
@maximedenes ping

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
