### PR TITLE
Remove the :> type cast?

### LINKED ISSUE #13908: Is the type cast :> worth keeping?
While discussing #13707, others observed

> it looks like a feature that is too intricate and of limited use, that we could propose for removal instead of documenting it

and

> So `x :>` means `proj1_sig x` in Program mode when `x` is of type `sig _` (i.e., `x : { n : _ | _ }`) (technically, of a type that is unifiable with whatever is registered as `core.sig.type`), and in all other cases `x :>` is just `x`.

> Unlike the other cast nodes, it seems that `:>` does not persist past pretyping, i.e., does not show up as a cast node in the term the kernel sees.  (It in fact seems a bit unfortunate for the rest of the code to have to deal with `CastCoerce` when it seems like in fact there's no reason for it to be valid in the syntax layers post-pretyping.)  (I might be missing something, though.)

See the discussion at and above https://github.com/coq/coq/pull/13707#issuecomment-792012857

Should we keep this or maybe remove it?

### PR DESCRIPTION
**Pull request by jfehrle**
Evaluate the impact of removing the :> type cast.  Merging this PR would close #13908.

Attn: @Zimmi48

### CODE REVIEW

**Comment by jfehrle** [comment]
The ref man has examples that use the construct and there are bits of explanation of the feature scattered in the manual.  (Note that the token `:>` is still used for other purposes.)  Also 2 CI jobs fail.  So I guess the answer is that we should not remove the type cast.

**Comment by Zimmi48** [comment]
>So I guess the answer is that we should not remove the type cast.

I haven't the same conclusion. FWIW, the Coq-Elpi failure seems unrelated. So this test shows that this feature is only used in one project, maintained by the Coq developer who introduced the feature in the first place. So it's a pretty much unused feature AFAICT. Furthermore, it's problematic because it is just a notation that works only in Program-mode for something that the Program library already provides another notation for, as shown by the `Print` statement in Jason's example. I'll try to complete this PR to make it pass.

**Comment by Zimmi48** [comment]
The Elpi failure is actually related but because it's a plugin, not because it uses a feature. Actually, it explicitly doesn't support the feature:

https://github.com/LPCIC/coq-elpi/blob/d7b07a9a98c1147e6fb65b8cec30640a03a6c035/src/coq_elpi_glob_quotation.ml#L184

The failure is a fatal warning that this pattern-matching case is not required anymore.

The Equations fix is pretty trivial: https://github.com/Zimmi48/Coq-Equations/commit/086fb6c7db06536d7d8e829aa461bd37b66bcbc1

This looks to me like we should proceed with the deprecation and removal of the feature (or even the removal without deprecation given how little it's used and known).

**Comment by mattam82** [comment]
I'm fine with the change as discussed in the Coq Call.

**Comment by jfehrle** [comment]
@Zimmi48 I'll let you finish this PR, if that's what you have in mind.

**Comment by Zimmi48** [comment]
Yes, I'll take over from there.

**Comment by Zimmi48** [comment]
@mattam82 can you be the assignee?
There are two overlays:
- one backward-compatible for Equations (https://github.com/mattam82/Coq-Equations/pull/350) that you can merge now;
- one backward-incompatible for Coq-Elpi (https://github.com/LPCIC/coq-elpi/pull/222) to merge at the same time as this PR.

**Comment by jfehrle** [comment]
I restored Théo's changed that I zapped by mistake.  So what once was now is again.

**Comment by Zimmi48** [comment]
@ppedrot You have merging rights on Equations and @mattam82 has been unresponsive since he approved this PR during a Coq Call. Can you self-assign and merge the backward-compatible Equations PR?

**Comment by Zimmi48** [comment]
ping @ppedrot or @mattam82

**Review by mattam82 — APPROVED** [review]

**Comment by mattam82** [comment]
@coqbot merge now

**Comment by mattam82** [comment]
@coqbot merge now

**Pull request merged**
