### PR TITLE
Update zarith 1.10 -> 1.12

### PR DESCRIPTION
**Pull request by SkySkimmer**
Hopefully fix bedrock2

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Looks like it works

**Comment by ppedrot** [comment]
Since this is pretty urgent, if no CI maintainer merges this by the time the CI finishes I'll do it myself.

**Comment by ejgallego** [comment]
> Since this is pretty urgent, if no CI maintainer merges this by the time the CI finishes I'll do it myself.

Go ahead if you want @ppedrot , but this needs update on the opam package and in the documentation to raise the lower bounds.

**Comment by ppedrot** [comment]
Fine. Technically I don't even think we need to bump zarith in the Coq opam package since this is only needed for a dependency and not Coq itself, but I don't know what the CI requirements are exactly.

**Comment by ejgallego** [comment]
What I mean is that we need to document that zarith 1.10 is broken.

**Comment by Zimmi48** [comment]
If we want to keep officially supporting versions below 1.12, then one of the two switches (the one that bedrock2 doesn't use) should keep this older version (lower bound). Updating the required version is also fine, but should indeed get doc and a changelog (which could be done in this PR or a separate one).

**Comment by ppedrot** [comment]
OK let's merge to get a clean CI now, and let somebody write the doc / opam PR.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ejgallego** [comment]
> OK let's merge to get a clean CI now, and let somebody write the doc / opam PR.

Please don't do this without at last adding a blocker bug :S

**Comment by JasonGross** [comment]
Note, btw, that bedrock2 works fine with zarith 1.11

**Comment by Zimmi48** [comment]
Before "writing the doc", we should decide if we want to update our lower zarith bound (to 1.11, to 1.12) or not.

**Comment by Zimmi48** [comment]
I'll create an issue about this.

**Pull request merged**
