### PR TITLE
PR for minimizing bug with zarith 1.10

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by JasonGross** [comment]
This is very strange (and please feel free to tag me when the minimizer fails to work as expected in the future).

**Comment by JasonGross** [comment]
It looks like somehow the glob file is misused or miscomputed

**Comment by JasonGross** [comment]
Turns out this is a bug in Coq that I just need to make the minimizer robust to: `Load` results in inaccurate .glob files, cf https://github.com/coq/coq/issues/15497

**Comment by JasonGross** [comment]
But unfortunately the minimizer can't handle minimizing against two different versions of zarith based on two different docker images. :-/

**Pull request closed without merging**
