### PR TITLE
Fix changelog entry for PR 14087

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
This trivial PR just moves a change log entry to the correct folder.

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
@koraa : fyi: the change log entry for your PR #14087 ended up in a wrong folder (which is fixed by this PR). Do you remember how you created it? I guess you followed some documented procedure and we might want to fix this documentation. I darkly remember that I did the same once, so I guess it is somewhere written down that it should be done like this.

**Comment by Zimmi48** [comment]
>I guess you followed some documented procedure and we might want to fix this documentation.

AFAIK, the documentation only mentions the script that should be used to generate changelog entries.

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Comment by MSoegtropIMC** [comment]
> AFAIK, the documentation only mentions the script that should be used to generate changelog entries.

Yes I know, the documentation here (https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog) is clear, but as I said, afair I did exactly the same thing once and really wonder how it came to that. I suspect there is some outdated alternate documentation which google leads to or whatever.

**Comment by SkySkimmer** [comment]
Yeah if the branch name contains a slash (as #14807 did) the script would misbehave.

**Pull request merged**
