### PR TITLE
Adding ML headers in setoid_ring

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** infrastructure (?)

A trivial commit in passing, by uniformity.

### CODE REVIEW

**Review by amahboubi — APPROVED** [review]
Not much to say here, thanks for this update!

**Comment by Zimmi48** [comment]
@amahboubi You're the one supposed to merge the PR in such cases.

**Comment by Zimmi48** [comment]
Note that the SF failure is unrelated and was fixed on master.

**Comment by Zimmi48** [comment]
@amahboubi Ping. If you can't take care of it currently, I can merge it for you if you want.

**Comment by maximedenes** [comment]
@amahboubi ping

**Comment by maximedenes** [comment]
Ok, since this has been approved and it is trivial, I'll merge so that we can ship those headers in 8.8.0.

**Pull request merged**
