### PR TITLE
kernel interrupts to improve STM processing.

### PR DESCRIPTION
**Pull request by gmalecha**
- pull request on behalf of Alec Faithful (@alef)

### CODE REVIEW

**Comment by gares** [comment]
My reading of the patch is that it makes it possible to interrupt 2 things:
1. hashconsing proof terms, this may take time at the end of a section for example where all proof terms are hashconsed one after the other
2. unwinding the lazy reduction machine during a strong (under binder) reduction

I'm ok for 1.

For 2 I need both a use case (full reduction with the lazy machine seems an odd pattern to me, do you have a proof script?) and the opinion of another developer understanding the lazy machine.  In particular, the check seem to be performed at each constr node being constructed while unwinding.  Is there a better (less expensive) place?  @maximedenes @herbelin (I can't find Bruno's nick)

**Comment by gmalecha** [comment]
@ale-f Do you have comments on this?

**Comment by maximedenes** [comment]
At first sight, it seems that putting a check for interrupt in zip_term is not a good idea. The efficiency of this function is critical for many developments (according to perf).

**Comment by JasonGross** [comment]
Bruno's alias is @barras

**Comment by ejgallego** [comment]
What shall we do with this PR?

My personal view is that `check_for_interrupt` is hopeless anyways and we will have to move a slightly different architecture to have good processing reactivity (`master` becomes just a coordinator between a `master_worker` and several `children_worker` that do all the dirty work).

Thus I propose that we reject this PR.

**Comment by barras** [comment]
check_for_interrupt may be hopeless, but the inability to interrupt is very frustrating for users. There are testcases (e.g. reflection) where starting to reduce under binders the calls to a recursive function may induce an exponential overhead, so you *really* want to be able to interrupt.
 This function is just doing a deref and a boolean test, so I do not think the patch is going to make zip_term's performance sink. (zip_term is not tail-rec anyway, it has been written like that so you can see at first glance what is is doing, and hasn't been tuned for speed).
Is it possible to run the perf tool with the patch applied ?

**Comment by ejgallego** [comment]
Rebasing the patch should trigger Travis, dunno about other perfs tools @matej-kosik ?

I've push a rebased branch here, I will run a couple of performance tests myself and report back.
https://github.com/ejgallego/coq/tree/kernel-interrupts

I am totally fine with this patch, but in my experiments, in order to make jsCoq moderately interruptible, it seemed like we would need to add one order of magnitude more of `check_for_interrupts`

**Comment by ejgallego** [comment]
Preliminary testing shows indeed a non-negligible slowdown. If confirmed, I would propose again to reject.

**Comment by barras** [comment]
I agree with you that adding checks in many places is not a good solution in the long run, and we may hope for a more robust solution. Meanwhile, though, I propose that recursive functions with bad complexity are good candidates for such additions, as long as its cost is not too high. So, for me, if Travis permits, Gregory's and Alec's request is OK.

**Comment by barras** [comment]
Sorry Emilio, I didn't see your last post before replying.
Is it possible to have a look at the results, to see if the slowdown is global or on specific places (which library, which tactics, etc.) ?

**Comment by ejgallego** [comment]
Tests are simple averaged 3 runs building the following contribs:
```
| App         | with patch | trunk      |
|-------------+------------+------------|
| unimath     |            |            |
|-------------+------------+------------|
| real        | 43m00.702s | 42m14.214s |
| user        | 41m52.828s | 41m17.348s |
| sys         |  0m51.016s |  0m44.868s |
|-------------+------------+------------|
| compcert    |            |            |
|-------------+------------+------------|
| real        | 19m41.932s | 18m58.475s |
| user        | 18m22.884s | 17m48.756s |
| sys         |  0m59.156s |  0m54.832s |
|-------------+------------+------------|
| fiat-crypto |            |            |
|-------------+------------+------------|
| real        | 50m23.892s | 49m23.492s |
| user        | 48m30.288s | 47m43.556s |
| sys         |  1m36.612s |  1m24.232s |
```
So it seems like you can feel something if my tests are correct.

It is a bit surprising indeed, I guess check_for_interrupt could be optimized to entirely go away in the non-interactive case.

**Comment by maximedenes** [comment]
@matejkosik could you bench this PR too? Thanks!

**Comment by matejkosik** [comment]
@maximedenes I've added it to the [queue](https://ci.inria.fr/coq/view/benchmarking/job/benchmark-the-whole-branch/). I think it will start on Sunday and terminate on Monday.

**Comment by ejgallego** [comment]
We are working on some STM changes that will affect `check_for_interrupt`, thus delaying this to 8.8.

**Comment by ejgallego** [comment]
If I am gonna be the one responsible of this then we can close this PR. `check_for_interrupt` is a hack and we cannot obviously make this solution scale or be robust.

**Pull request closed without merging**
