### PR TITLE
Add EConstr.ERelevance abstraction barrier to force normalizing relevances

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlays:
- https://github.com/coq-community/aac-tactics/pull/139
- https://github.com/coq-community/atbr/pull/43
- https://github.com/damien-pous/coinduction/pull/20
- https://github.com/lukaszcz/coqhammer/pull/178
- https://github.com/LPCIC/coq-elpi/pull/621
- https://github.com/mattam82/Coq-Equations/pull/591
- https://gitlab.inria.fr/fbesson/itauto/-/merge_requests/15
- https://github.com/SkySkimmer/coq-lean-import/pull/19
- https://github.com/Mtac2/Mtac2/pull/402
- https://github.com/unicoq/unicoq/pull/92
- https://github.com/coq-community/paramcoq/pull/123
- https://github.com/ejgallego/coq-serapi/pull/405
- https://github.com/smtcoq/smtcoq/pull/142
- https://github.com/coq-community/stalmarck/pull/31
- https://github.com/coq-tactician/coq-tactician/pull/81
- https://github.com/impermeable/coq-waterproof/pull/53
- https://github.com/MetaCoq/metacoq/pull/1080
- https://github.com/damien-pous/relation-algebra/pull/43

### CODE REVIEW

**Comment by ppedrot** [comment]
This line is suspect.
```
│   1.8560    2.7790  0.9230  49.73%   736  [coq-stdlib/Reals/Cauchy/ConstructiveCauchyReals.v.html](https://coq.gitlabpages.inria.fr/-/coq/-/jobs/4248766/artifacts/_bench/html/coq-stdlib/Reals/Cauchy/ConstructiveCauchyReals.v.html#L736)                                             │
```

**Comment by SkySkimmer** [comment]
No, stdlib still uses -j12 (cf https://gitlab.inria.fr/coq/coq/-/jobs/4248766/artifacts/file/_bench/logs/coq-stdlib.NEW.1.3.perf) so lots of noise

**Comment by ppedrot** [comment]
Are you really sure? That's a rewrite in Type, famous for stressing universes.

**Comment by proux01** [comment]
I read the "CPU instructions" column as "nothing happening here".

**Comment by SkySkimmer** [comment]
Pick a random bench and you'll find similar noise in stdlib

**Comment by ppedrot** [comment]
Fine, fine.

**Comment by SkySkimmer** [comment]
stdlib doesn't produce the profile files but they're available for coq_makefile projects and have instruction counts

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
green ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Since I believe this is pretty much uncontroversial, let's not waste time with the annoying overlays and merge right away. @coqbot merge now

**Pull request merged**
