### PR TITLE
Remove test-suite/bugs/opened

### PR DESCRIPTION
**Pull request by SkySkimmer**
It is useless and running them is a waste of time.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Recently in coq call https://github.com/coq/coq/issues/3928 had a -disabled test exemplifying the uselessness of this folder.

**Comment by JasonGross** [comment]
test-suite/bugs/opened/bug_3928.v-disabled should be moved to test-suite/bugs/bug_3928.v, I think.  Should we check if any of the other disabled bugs were in fact solved?

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
The size of this PR makes the Github interface really struggle on my computer. From what I can gather, there are whitespace changes littered throughout right? Do you also want have a look at what Jason asked or should we make an issue and do it in the future (at some point)?

**Comment by SkySkimmer** [comment]
>Do you also want have a look at what Jason asked or should we make an issue and do it in the future (at some point)?

I had a look and there's nothing interesting AFAICT

**Comment by Alizter** [comment]
Alright then, will merge soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
