### PR TITLE
Forbid template prop

### LINKED ISSUE #9296: False positives in auto template polymorphism warning
eg with `Inductive Foo := foo : Type -> Foo.` it doesn't matter whether it's declared template or not, so why warn?

See also https://github.com/coq/coq/pull/8488#issuecomment-450424437

### PR DESCRIPTION
**Pull request by ppedrot**
Let's see what the CI gives.

Fixes #9296

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Only test suite and fiatlegacy fail, seems to work OK.

**Comment by ppedrot** [comment]
So there is still a little problem with this PR, which is that AFAIK I don't know how to get a monomorphic singleton inductive type to live in Type rather than in Prop. This is not new, but before due to template polymorphism it was less user-visible. If you wanted to have e.g. an accessibility predicate preserved by extraction, or a predicative variant of it, it might be problematic.

**Comment by SkySkimmer** [comment]
Does `: Set` not work?

**Comment by ppedrot** [comment]
@SkySkimmer yes, but it lands in Set, not in Type.

**Comment by SkySkimmer** [comment]
Then declare a universe 
~~~coq
Inductive cat@{u|Set<u} : Type@{u} := .
~~~
or
~~~coq
Universe u.
Inductive cat :Type@{u} := .
~~~

**Comment by ppedrot** [comment]
Yes, I realized that there are workarounds, another one is to define an arity like `Definition U := Type` and pass that. But the problem is more about intent. It is quite surprising to explicitly annotate an inductive type with `Type` and observe it land in `Prop`. We should do something now that it's really `Prop`, not some funny thing that is printed `Type` from time to time.

**Comment by ppedrot** [comment]
The test-suite failure for #5281 with this branch is likely a duplicate of #14502. The goal is similar (it's an equality derived from a Scheme using induction tactics internally) and I get the same warning.

**Comment by ppedrot** [comment]
Yet another difference between template "Type" and Prop: the induction scheme generated in the first case are dependent, not in the second case. Not sure what to do to preserve backwards compatibility as much as possible.

**Comment by JasonGross** [comment]
I'm very confused by the fcl error message; it seems to be about naming schemes of decidable equality?

**Comment by ppedrot** [comment]
I suspect that it's due to a scheme that failed to be generated and is incorrectly used by a tactic. The last failing test from the test-suite is precisely a scheme failing to be generated.

**Comment by JasonGross** [comment]
> is incorrectly used by a tactic

Is there a "correct" way to use the bl and lb lemmas?  I know they have "internal" in the name, but there seems to be no way to get non-internal automatically generated proofs of correctness of the autogenerated Boolean equality schemes.  (Or do you mean something else by "incorrectly"?)

**Comment by ppedrot** [comment]
See also #6833.

**Comment by herbelin** [comment]
> I don't know how to get a monomorphic singleton inductive type to live in Type rather than in Prop. If you wanted to have e.g. an accessibility predicate preserved by extraction ...

Would giving a status to Type(0-) more clearly distinct from Prop be possible and useful for extraction?

>  or a predicative variant of it, it might be problematic.

Would a predicative variant of accessibility behave really differently than an impredicative one? If one believes in resizing, it would still be in the lowest level.

**Comment by ppedrot** [comment]
> If one believes in resizing

And funext, and unique choice. Anyways, I am not sure what this has to do with the current PR which is only trying to remove a piece of useless code in the kernel and faces issues with tactics observing the template status.

**Comment by herbelin** [comment]
> I am not sure what this has to do with the current PR

I admit that I only read the title.

In relation with what the title of the PR says, I'm trying to understand the model that you have in mind about `Prop` so that I can integrate your view to my own vision of things. It is probably that I'm missing background but I must confess that, at the current time, I don't understand your model. So, my comments have for only purpose to help me to understand your model, a model that I'll be ready to adopt once I will have understood it and integrated it to the naive picture I have in mind.

**Comment by herbelin** [comment]
I'm still interested in understanding what would be wrong with template `Prop` (besides extraction having to adapt).

**Comment by ppedrot** [comment]
@herbelin nothing. The rule is just redundant. A template inductive type in Prop has the same typing rules as its non-template variant, hence the PR.

**Comment by herbelin** [comment]
I'm still interested in understanding what would be wrong with template `Prop` (besides extraction having to adapt).

> @herbelin nothing. The rule is just redundant. A template inductive type in Prop has the same typing rules as its non-template variant, hence the PR.

OK, sorry for my confusion.

**Comment by ppedrot** [comment]
Closing for the time being.

**Pull request closed without merging**
