### PR TITLE
Deactivation of notations grants verbose mode

### PR DESCRIPTION
**Pull request by herbelin**
See [Zulip](https://coq.zulipchat.com/#narrow/stream/423352-Coq-Notation-system/topic/How.20to.20overwrite.20one.20notation.20with.20another/near/419413047).

### CODE REVIEW

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
Can we force a verbose mode in the test-suite?

**Comment by proux01** [comment]
I don't find any.

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@jellooo038 @jim-portegies I'm surprised by waterproof failure here, is waterproof master known to be broken?

**Comment by SkySkimmer** [comment]
yes https://github.com/impermeable/coq-waterproof/pull/49

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
