### PR TITLE
[general] Move files to directories so they match linking order.

### PR DESCRIPTION
**Pull request by ejgallego**
We move a bunch of modules (`Impargs`, `Declare`, `Ind_tables`,
`Miscprint`) to their proper place as they were declared in different
`mllib` files than the one in their directory.

In some cases this could be refined but we don't do anything fancy, we
just reflect the status quo.

### CODE REVIEW

**Comment by ejgallego** [comment]
This should be trivial to merge once Travis gives the OK.

**Comment by silene** [comment]
This does not make any sense to me. For example, why should a file containing only printing functions be moved outside the `printing` directory?

**Review by ppedrot — COMMENTED** [review]
It would be nice to have a tool to check this at compile time. I can probably write a script.

Also, I'm not convinced by the semantics of that. Declare should be somewhat above (e.g. in vernac) and  Ind_tables should be somewhere else...

**Comment by ejgallego** [comment]
> This does not make any sense to me. For example, why should a file containing only printing functions be moved outside the printing directory?

The move was done long time ago; this PR only makes the situation explicit. See `proofs/proofs.mllib`.
Basically the problem is that `proofs.cma` depends on `Miscprint` however, `proofs.cma` is linked before `printing.cma`.

I agree with both of you; I say, let's apply this patch to reflect reality, and then let's fix the organization independently if we think it does not make sense.

IMHO, a script would be nice but this kind of stuff has really to be catched by code review.

**Review by ppedrot — APPROVED** [review]
Indeed, let's first merge this and fix the mess afterwards.

**Pull request merged**
