### PR TITLE
Changelog and test for #17789

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@Janno please check that the changelog seems accurate

**Comment by SkySkimmer** [comment]
ping @Janno

**Comment by SkySkimmer** [comment]
I just grabbed the test from https://github.com/coq/coq/issues/6714#issue-295251212

**Comment by Janno** [comment]
Okay, it took me a while to page this stuff back into my brain. I got confused because I thought the output in the test was the current state of things. But it's what happened before. Would it make sense to turn it into the following?
```coq
Fail Definition t : Foo true _ := _.
(*
The command has indeed failed with message:
The following term contains unresolved implicit arguments:
  (Foo true ?y)
More precisely: 
- ?y: Cannot infer this placeholder of type "bool".
*)
```
That way a future regression would turn into a test failure.

**Comment by SkySkimmer** [comment]
It's pretty common for our tests to contain the old buggy output in a comment. Not sure what the point of putting the current output would be.

**Comment by Janno** [comment]
Okay, I don't want to get into the finer details of what should and shouldn't be in tests (and I honestly haven't given it much consideration so it's not like I have to anything useful to add here). I'll just approve the PR.

**Review by Janno — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
