### PR TITLE
When univ minim to set is off, don't get confused by Prop lbound

### LINKED ISSUE #13927: There should be a way to prevent inductive auto-minimization
```coq
Set Printing Universes.
Unset Universe Minimization ToSet.
Test Universe Polymorphism. (* Universe Polymorphism is off *)
```

(we keep Universe Polymorphism off for the reasons summarized at https://github.com/coq/coq/issues/10513#issuecomment-512468004,  except for a few selected definitions where we really need it)

```coq
Polymorphic Axiom tuple@{i} : Type@{i} -> nat -> Type@{i}.
```

The following definition is monomorphic, so its universe in `T : Type@{ht.u0}` becomes a global universe, so it won't be possible to instantiate it to Set (https://github.com/coq/coq/issues/9813).
```coq
Axiom ht: forall T: Type, tuple T 4.

Axiom test1: forall n: nat, tuple unit n -> bool.
About test1. (* test1 : forall n : nat, tuple@{test1.u0} unit n -> bool
Thanks to `Unset Universe Minimization ToSet.`, we get @{test1.u0} instead of @{Set},
which makes the following go through: *)

Check (test1 4 (ht unit)).
```

But now, if we want to do the same inside a box, `Unset Universe Minimization ToSet.` does not help any more:

```coq
Record box := mkBox {
  elimBox: forall n: nat, tuple unit n -> bool;
}.
About elimBox. (* elimBox : box -> forall n : nat, tuple@{Set} unit n -> bool
We get @{Set} instead of @{box.u}! *)

Fail Check (fun (b: box) => elimBox b 4 (ht unit)).

Record box'@{u} := mkBox' {
  elimBox': forall n: nat, tuple@{u} unit n -> bool;
}.
About elimBox'. (* elimBox' : box' -> forall n : nat, tuple@{box'.u} unit n -> bool
We get @{box'.u}, good *)

Check (fun (b: box') => elimBox' b 4 (ht unit)). (* works! *)
```

Feature request: When `Universe Minimization ToSet.` is off, the definition of `box` (without universe annotations) should have the same result as the definition of `box'`.

Coq version: 8.13.0

/cc @andres-erbsen

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13927

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Review by ppedrot — APPROVED** [review]
You're the one who knows what's going on here. CI is green so that's good for me.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
