### PR TITLE
Make kernel comparison strategy consistent with unification.

### PR DESCRIPTION
**Pull request by maximedenes**
We make the kernel compare application nodes from left to right, and
stacks from top to bottom, as is done in evarconv.

Testing it quickly on the stdlib seems to give a 5% speedup, although the timing is not reliable nor scientific. I would be *extremely* interested to see more extensive and more scientific measurements.

### CODE REVIEW

**Comment by JasonGross** [comment]
Can you test this on UniMath, [HoTT](https://github.com/HoTT/HoTT/pull/846), the `parsers` target of [fiat](https://github.com/mit-plv/fiat), and [fiat-crypto](https://github.com/mit-plv/fiat-crypto/), and the `src` and `facade` targets of [bedrock (branch `8.4+8.5`)](https://github.com/JasonGross/bedrock/tree/8.4%2B8.5)?  Let me know if any of these fail to build with Coq 8.6 or trunk.

I'm worried about the effects of this change on performance; I think there are a few spots in UniMath where @DanGrayson is using a tactic I gave him that gets the kernel to run unification in the other direction (basically, it flips the sense of `unify a b`); if this reverses that direction (does it?), I'm worried those locations might slow down, or infinite loop.

**Comment by mattam82** [comment]
It just changes comparison of applications so that arguments are compared in the natural left to right order... one comparison's success ensuring that the next is done between terms of convertible types.

**Comment by psteckler** [comment]
I ran an experiment comparing times using both strategies, flagging terms where the times were much different. Results available on request!

**Comment by psteckler** [comment]
Latest results comparing the patched, unpatched code:

  http://people.csail.mit.edu/psteck/kernel-stack-2017-02-23.log

These results are from the mathcomp library. These are instances where the times were much different; I picked the 17 cases with the greatest percentage discrepancy. It happens that for these instances, the unpatched code is always faster.

**Comment by SkySkimmer** [comment]
Unimath dies of ill-typed conversion
Corn and vst die of too long with no output

**Comment by ppedrot** [comment]
By problem you mean the lack of documentation? If so, I agree.

**Comment by ppedrot** [comment]
@maximedenes Can you give a try to this PR after the merge of #8824? I'm curious.

**Review by ppedrot — COMMENTED** [review]
I am fine with the patch per se, but we cannot merge this due to the efficiency loss it has. I have a PR that separates between safe (i.e. between to terms with a common supertype) and unsafe conversion, we might try to set the type-preserving reduction on the first case only. Alternatively or in parallel, we can also try to precisely pin down the source of slowness and see if we can work around this.

**Comment by ejgallego** [comment]
Maybe this should be closed as a PR and turned into an issue instead? It seems some non-trivial design work will be needed here.

**Comment by ppedrot** [comment]
Sorry to be a bit pushy, but I'm closing this PR. Everybody in the dev team is aware of the issue, it is of little relevance to people except the handful of arcane kernel experts, which probably explains why documentation didn't magically appear. Feel free to open an issue if that prevents you from sleeping at night.

**Comment by maximedenes** [comment]
@ppedrot Please don't close without creating an issue, though. Otherwise we are just going to loose information. Next time we try to address the problem I don't see why this draft wouldn't be useful, as it hit mainly compatibility issues, but is not known to be incorrect.

**Pull request closed without merging**
