### PR TITLE
Remove unused references from biblio.

### PR DESCRIPTION
**Pull request by Zimmi48**
A few reference have moved around when they were not in alphabetical order already due to the method I used to remove unused ones.

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
Welcome cleanup, thanks! How did you detect the unused ones?

**Comment by Zimmi48** [comment]
Rebased.

**Comment by ejgallego** [comment]
I indeed had the same thought, IMHO having a large related biblio to come with Coq is a nice thing.

**Comment by ejgallego** [comment]
We could make this formal as in "papers using and citing Coq", some people tried to do that in a wiki page but IMHO a bib entry + generated page works well too. Example:

https://github.com/math-comp/math-comp/wiki/Publications

**Comment by Zimmi48** [comment]
I don't understand this request why we would want to keep a copy in the archive: I don't think that anyone ever relied on this list (at least outside of the dev team); it hasn't ever been advertised. And the repository doesn't sound like the right place to store this anyways. If you want to start a wiki page, this will be a very welcome addition that may reveal very useful (in particular for students). Including the bibtex entries in the wiki page can be done with code blocks...

**Comment by ejgallego** [comment]
> why we would want to keep a copy in the archive

As @herbelin mentioned this is important historical data, and Coq is above all a research project so shipping a historical bibliography is IMVHO proper.

**Comment by herbelin** [comment]
> who really looked at it in the past?

It has been useful for me at some time. I agree that it is almost invisible from people other than developers. Then, a quick solution would be to copy it (as a bib file) on the wiki.

**Comment by Zimmi48** [comment]
OK indeed that's the quickest solution so I'll implement it.

**Comment by Zimmi48** [comment]
Done here: https://github.com/coq/coq/wiki/Published-Works
with a link on the main page, here: https://github.com/coq/coq/wiki#coq-community
Thus, I think nothing is delaying this PR anymore.

**Comment by maximedenes** [comment]
@ejgallego @herbelin Can I merge now?

**Comment by ejgallego** [comment]
Sure, I wasn't meaning to block this PR but more to state that I like software that comes with a biblio, as I think Hugo does.

But indeed taking care of the biblio is a lot of work so unless someone volunteers to make it "official" and supported I am fine with its move to the other repository.

**Comment by herbelin** [comment]
Same as @ejgallego. Some work should be done to sort in the biblio what "resisted to time" but I have no time to do it currently and the move to the wiki is good enough. And after all, if we later need a reference which has been removed by this PR, it shall also be easy to add it again.

**Pull request merged**
