### PR TITLE
CI: check that we put the expected files in _install_ci

### PR DESCRIPTION
**Pull request by SkySkimmer**
Prevent repeats of #17159, expected to fail until
https://github.com/coq/coq/pull/17165 is merged.

### CODE REVIEW

**Comment by Alizter** [comment]
We could also hook up a Dune rule that checks and updates the list locally. That way we don't need to update the list by hand.

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ejgallego — COMMENTED** [review]
Indeed using a dune diff rule would make the thing less ad-hoc and more easy to manage in case of update, which could be frequent.

Actually, for both `(library ...)` and `(coq.theory ...)` stanza, Dune has its own test-suite, so that's IMHO less of a worry. We just need indeed to test our custom rule generation setup, so I'd restrict the list to `lib/coq/`

**Review by ejgallego — CHANGES_REQUESTED** [review]
- make the list easier to update using a promotion + diff rule
- don't include stuff in `lib/coq-core`

**Comment by SkySkimmer** [comment]
I don't know how to make a dune rule that depends on the result of the installed stuff.

**Comment by ejgallego** [comment]
> I don't know how to make a dune rule that depends on the result of the installed stuff.

You can depend on `coq-core.install` `coq-stdlib.install`

Actually, maybe it would be better to detect changes in those?

**Comment by ejgallego** [comment]
Making such a test would be much simpler tho if we had  #16583 in, but so far nobody volunteered to sheperd it.

**Comment by SkySkimmer** [comment]
Why would it be simpler?

**Comment by ejgallego** [comment]
Because we could write it as a simple dune output test without going by the Makefile.

I think my concern about updating the file list is real, at least for OCaml that can arrive pretty often, and it is going to be annoying for devs.

So we can either add an "accept-output" target, or maybe drop coq-core from the list so we only track stdlib files.

Anyways I don't feel strongly about this, happy to merge as is if you want.

**Comment by SkySkimmer** [comment]
I don't have motivation to continue this

**Pull request closed without merging**
