### PR TITLE
[experiment] Convert arguments in the right order in kernel.

### PR DESCRIPTION
**Pull request by ppedrot**
Persevere diabolicum.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
Could be worse.

**Comment by ppedrot** [comment]
The VST slowdown is essentially due to the fact that functor proofs are transparent. It should be considered a problem on their side, I believe. Here is a small self-contained snippet that shows the problem.
```coq
From Coq Require List.

Axiom extensionality:
  forall (A B: Type) (f g : A -> B),  (forall x, f x = g x) -> f = g.

Definition id (A:Type) := fun x:A => x.
Definition compose (A B C:Type) (g:B -> C) (f:A -> B) := fun x => g (f x).
Arguments compose [A B C] _ _ _.
Infix "oo" := compose (at level 54, right associativity).

Module functors.

Set Implicit Arguments.

Module CovariantFunctor.

Record functorFacts (PS : Type -> Type)
  (fmap : forall A B (f : A -> B), PS A -> PS B) : Type :=
FunctorFacts {
  ff_id : forall A, fmap _ _ (id A) = id (PS A);
  ff_comp : forall A B C (f : B -> C) (g : A -> B),
fmap _ _ f oo fmap _ _ g = fmap _ _ (f oo g)
}.

Record functor : Type := Functor {
  _functor: Type -> Type;
  fmap : forall A B (f : A -> B), _functor A -> _functor B;
  functor_facts : functorFacts _functor fmap
}.

End CovariantFunctor.

Module ContraVariantFunctor.

Record functorFacts (PS : Type -> Type)
  (fmap : forall A B (f : B -> A), PS A -> PS B) : Type :=
FunctorFacts {
  ff_id : forall A, fmap _ _ (id A) = id (PS A);
  ff_comp : forall A B C (f : C -> B) (g : B -> A),
fmap _ _ f oo fmap _ _ g = fmap _ _ (g oo f)
}.

Record functor : Type := Functor {
  _functor: Type -> Type;
  fmap : forall A B (f : B -> A), _functor A -> _functor B;
  functor_facts : functorFacts _functor fmap
}.

End ContraVariantFunctor.

Module MixVariantFunctor.

Record functorFacts (PS : Type -> Type)
 (fmap : forall A B (f1 : A -> B) (f2 : B -> A), PS A -> PS B) : Type :=
FunctorFacts {
  ff_id : forall A, fmap _ _ (id A) (id A) = id (PS A);
  ff_comp : forall A B C (f1 : B -> C) (f2 : C -> B) (g1 : A -> B)
(g2 : B -> A), fmap _ _ f1 f2 oo fmap _ _ g1 g2 = fmap _ _ (f1 oo g1) (g2 oo f2)
}.

Record functor : Type := Functor {
  _functor: Type -> Type;
  fmap : forall A B (f1 : A -> B) (f2 : B -> A), _functor A -> _functor B;
  functor_facts : functorFacts _functor fmap
}.

End MixVariantFunctor.

Module CovariantBiFunctor.

Record functorFacts (PS : Type -> Type -> Type)
 (fmap : forall A1 B1 A2 B2 (f1 : A1 -> B1) (f2 : A2 -> B2),
    PS A1 A2 -> PS B1 B2) : Type :=
FunctorFacts {
  ff_id : forall A1 A2, fmap _ _ _ _ (id A1) (id A2) = id (PS A1 A2);
  ff_comp : forall A1 A2 B1 B2 C1 C2 (f1 : B1 -> C1) (f2 : B2 -> C2)
(g1 : A1 -> B1) (g2 : A2 -> B2),
  fmap _ _ _ _ f1 f2 oo fmap _ _ _ _ g1 g2 = fmap _ _ _ _ (f1 oo g1) (f2 oo g2)
}.

Record functor : Type := Functor {
  _functor: Type -> Type -> Type;
  fmap : forall A1 B1 A2 B2 (f1 : A1 -> B1) (f2 : A2 -> B2),
    _functor A1 A2 -> _functor B1 B2;
  functor_facts : functorFacts _functor fmap
}.

End CovariantBiFunctor.

Coercion CovariantFunctor._functor:
  CovariantFunctor.functor >-> Funclass.
Coercion MixVariantFunctor._functor:
  MixVariantFunctor.functor >-> Funclass.
Coercion CovariantBiFunctor._functor:
  CovariantBiFunctor.functor >-> Funclass.

Module CovariantFunctorLemmas.

Import CovariantFunctor.

Axiom fmap_id : forall {F: functor}, forall A, fmap F (id A) = id (F A).
Axiom fmap_comp : forall {F: functor}, forall A B C (f : B -> C) (g : A -> B),
  fmap F f oo fmap F g = fmap F (f oo g).

End CovariantFunctorLemmas.

Module MixVariantFunctorLemmas.

Import MixVariantFunctor.

Axiom fmap_id : forall {F: functor}, forall A, fmap F (id A) (id A) = id (F A).
Axiom fmap_comp : forall {F: functor}, forall A B C (f1 : B -> C) (f2: C -> B)
(g1 : A -> B) (g2: B -> A),
  fmap F f1 f2 oo fmap F g1 g2 = fmap F (f1 oo g1) (g2 oo f2).

End MixVariantFunctorLemmas.

Module CovariantBiFunctorLemmas.

Import CovariantBiFunctor.

Axiom fmap_id : forall {F: functor}, forall A1 A2, fmap F (id A1) (id A2) = id (F A1 A2).

Axiom fmap_comp : forall {F: functor}, forall A1 A2 B1 B2 C1 C2 (f1 : B1 -> C1)
(f2: B2 -> C2) (g1 : A1 -> B1) (g2: A2 -> B2),
  fmap F f1 f2 oo fmap F g1 g2 = fmap F (f1 oo g1) (f2 oo g2).

End CovariantBiFunctorLemmas.

Module GeneralFunctorGenerator.

Definition CovariantFunctor_MixVariantFunctor (F: CovariantFunctor.functor):
  MixVariantFunctor.functor.
  refine (@MixVariantFunctor.Functor
   (fun T => F T)
   (fun A B f _ => CovariantFunctor.fmap F f) _).
  constructor; intros; simpl.
  + apply CovariantFunctor.ff_id, CovariantFunctor.functor_facts.
  + apply CovariantFunctor.ff_comp, CovariantFunctor.functor_facts.
Defined.

Definition CovariantFunctor_MixVariantFunctor_compose
(F1: CovariantFunctor.functor) (F2: MixVariantFunctor.functor):
  MixVariantFunctor.functor.
  refine (@MixVariantFunctor.Functor
   (fun T => F1 (F2 T))
   (fun A B f g => CovariantFunctor.fmap F1 (MixVariantFunctor.fmap F2 f g)) _).
  constructor; intros; simpl.
  + rewrite MixVariantFunctorLemmas.fmap_id, CovariantFunctorLemmas.fmap_id; auto.
  + rewrite !CovariantFunctorLemmas.fmap_comp, MixVariantFunctorLemmas.fmap_comp; auto.
Defined.

Definition CovariantBiFunctor_MixVariantFunctor_compose
(F: CovariantBiFunctor.functor)
(F1 F2: MixVariantFunctor.functor):
  MixVariantFunctor.functor.
  refine (@MixVariantFunctor.Functor
   (fun T => F (F1 T) (F2 T))
   (fun A B f g => CovariantBiFunctor.fmap F
      (MixVariantFunctor.fmap F1 f g) (MixVariantFunctor.fmap F2 f g)) _).
  constructor; intros; simpl.
  + rewrite !MixVariantFunctorLemmas.fmap_id, CovariantBiFunctorLemmas.fmap_id; auto.
  + rewrite CovariantBiFunctorLemmas.fmap_comp, !MixVariantFunctorLemmas.fmap_comp; auto.
Defined.

End GeneralFunctorGenerator.

Module CovariantBiFunctorGenerator.

Import CovariantBiFunctor.
Import CovariantBiFunctorLemmas.

Definition Fpair: functor.
  refine (@Functor
   (fun T1 T2 => prod T1 T2)
   (fun _ _ _ _ f1 f2 x => (f1 (fst x), f2 (snd x))) _).
  constructor; intros; simpl; auto.
  apply extensionality; intros p; destruct p as [a1 a2]; simpl; auto.
Defined.

End CovariantBiFunctorGenerator.

Module CovariantFunctorGenerator.

Import CovariantFunctor.
Import CovariantFunctorLemmas.

Definition fconst (T : Type): functor.
  refine (@Functor (fun _ => T) (fun _ _ _ x => x) _).
  constructor; intros; auto.
Defined.

Definition Foption: functor.
  refine (@Functor (fun T => option T)
   (fun _ _ f x => match x with Some x0 => Some (f x0) | _ => None end) _).
  constructor; intros; simpl; auto.
  + apply extensionality; intro x; destruct x; auto.
  + apply extensionality; intro x; destruct x; auto.
Defined.

Definition Flist: functor.
  refine (@Functor (fun T => list T)
   (fun _ _ f x => List.map f x) _).
  constructor; intros; simpl; auto.
  + apply extensionality; intro x; apply List.map_id.
  + apply extensionality; intro x; apply List.map_map.
Defined.

End CovariantFunctorGenerator.

Module MixVariantFunctorGenerator.

Import MixVariantFunctor.
Import MixVariantFunctorLemmas.

Definition fconst (T : Type): functor :=
  GeneralFunctorGenerator.CovariantFunctor_MixVariantFunctor
  (CovariantFunctorGenerator.fconst T).

Definition fpair (F1 F2: functor): functor :=
  GeneralFunctorGenerator.CovariantBiFunctor_MixVariantFunctor_compose
  CovariantBiFunctorGenerator.Fpair
  F1
  F2.

Definition foption (F: functor): functor :=
  GeneralFunctorGenerator.CovariantFunctor_MixVariantFunctor_compose
  CovariantFunctorGenerator.Foption
  F.

Definition flist (F: functor): functor :=
  GeneralFunctorGenerator.CovariantFunctor_MixVariantFunctor_compose
  CovariantFunctorGenerator.Flist
  F.

End MixVariantFunctorGenerator.

Unset Implicit Arguments.

End functors.

Import functors.
Import functors.MixVariantFunctor.
Import functors.MixVariantFunctorGenerator.
Axiom fpreds : functor.

Record Ghost : Type := Build_Ghost
  { G : Type;
    valid : G -> Prop; }.

Definition ghost (PRED : Type) : Type :=
  list (option ({g: Ghost & {a: @G g | valid _ a}} * fpreds PRED)%type).

Definition ghost_fmap (A B:Type) (f:A->B) (g:B->A)(x:ghost A) : ghost B :=
  fmap (flist (foption (fpair (fconst _) fpreds))) f g x.

Inductive ghost_join PRED : ghost PRED -> ghost PRED -> ghost PRED -> Prop :=
| ghost_join_nil_l m: ghost_join PRED nil m m
| ghost_join_nil_r m: ghost_join PRED m nil m
| ghost_join_cons a1 a2 m1 m2 a3 m3:
    ghost_join PRED (cons a1 m1) (cons a2 m2) (cons a3 m3).

Goal forall (A B : Type) (f : A -> B) (g : B -> A)
  (a1 a2 a3 : option ({g0 : Ghost & {a : @G g0 | @valid g0 a}} * _functor fpreds A))
  (m1 m2 m3 : ghost A),
  ghost_join B (ghost_fmap A B f g (cons a1 m1)) (ghost_fmap A B f g (cons a2 m2))
  (ghost_fmap A B f g (cons a3 m3)).
Proof.
intros.
constructor.
Fail Timeout 5 Qed. (* immediate on master, takes ages with this PR *)
Abort.
```

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
https://github.com/MetaCoq/metacoq/blob/coq-8.19/erasure-plugin/theories/ErasureCorrectness.v blew up in CI (we don't do erasure-plugin in the bench)

vst blew up in progs/verif_incr.v, looks like we don't do progs in the bench

**Comment by SkySkimmer** [comment]
The vast majority of the hott change is https://coq.gitlabpages.inria.fr/-/coq/-/jobs/4969414/artifacts/_bench/html/coq-hott/theories/Homotopy/ExactSequence.v.html#L485
~~~
│   0.0020    3.4910    3.4890  174450.00%    485  coq-hott/theories/Homotopy/ExactSequence.v.html                                                                            │
~~~

**Pull request closed without merging**
