### PR TITLE
Print more info before trying to push to coq-on-cachix.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

This should help debugging next time there is a failure like https://github.com/coq/coq/pull/9594#issuecomment-473925288.

### CODE REVIEW

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
Still failing.

~~~
$ git fetch --unshallow
From https://gitlab.com/coq/coq
 + c5890bfbf2...636857d2e7 pr-9776    -> origin/pr-9776  (forced update)
 + c52f912a9d...369b7e2e68 pr-9797    -> origin/pr-9797  (forced update)
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
$ git branch -v
* (HEAD detached at 6fd12bf575) 6fd12bf575 Merge PR #9795: Print more info before trying to push to coq-on-cachix.
  master                        016f4a3020 [behind 1738] Merge PR #8634: (For v8.9 and master) Remove -compat 8.6 and document the compat updates to do as part of a release.
$ git push git@github.com:coq/coq-on-cachix "${CI_COMMIT_REF_NAME}"
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
To github.com:coq/coq-on-cachix
 ! [rejected]              master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:coq/coq-on-cachix'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
~~~

Why is there a `git fetch` from the gitlab.com mirror repository?

**Comment by vbgl** [comment]
Should we use a more precise `push` command? e.g.:
~~~
git push git@github.com:coq/coq-on-cachix "${CI_COMMIT_SHA}":"${CI_COMMIT_REF_NAME}"
~~~

**Comment by Zimmi48** [comment]
Sorry, do you mind including a link to the log when you see such a failure?

**Comment by Zimmi48** [comment]
In any case, I think that your proposed more precise `push` command would indeed solve the issue that we are facing.

**Comment by vbgl** [comment]
This is the link: <https://gitlab.com/coq/coq/-/jobs/180173062>.

Do you want that I do the PR including the proposed fix?

**Comment by Zimmi48** [comment]
>Do you want that I do the PR including the proposed fix?

Yes, please.

**Comment by vbgl** [comment]
Done: #9805

**Pull request merged**
