### PR TITLE
cleanup: convert evarsolve to use raise_notrace

### PR DESCRIPTION
**Pull request by rgrinberg**
all exceptions not defined in the mli are assumed to private, and hence their backtraces aren't needed. I went over all the callers to make sure they are indeed being caught, but a second glance wouldn't hurt.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This seems like a bad idea, maybe they're caught now but if that changes we will get to enjoy no-backtrace bugs.

**Comment by SkySkimmer** [comment]
Maybe we should instead define `Exninfo.raise e = if !is_recording then raise e else raise_notrace e` and use that everywhere

**Comment by rgrinberg** [comment]
I'd say bench it first, see how important it is here.

> Maybe we should instead define Exninfo.raise e = if !is_recording then raise e else raise_notrace e and use that everywhere

The problem with writing code like that is that it doesn't convey the intent. When one writes `raise_notrace` the expectation is that the exception is used purely for flow control and must be caught. If you switch to a general raise, you now have to wonder which is it. So perhaps something like this:
```
let raise_notrace =
  if Printexc.backtrace_status () then
    raise
  else
    raise_notrace
```

**Comment by ppedrot** [comment]
I am really not too fond of the proposed code change. We don't use raise_notrace in Coq to signal intent, and this looks like a poor man's type system to me. A system of static exceptions in the type system would check the intent at compile time so this would be enforced statically. But we don't have this in OCaml.

Here we start raising exceptions across function calls. This makes it way easier to get this wrong compared to the situation where the handler and the raise are scoped statically in the same function body. Worse, if we introduce a bug (which *will* happen) the exception will escape, ad we will not even get a backtrace.

**Comment by rgrinberg** [comment]
Unfortunately, the way the code is written makes it non trivial to refactor it so that exception handling doesn't spill across functions.

Some of the code in this PR is definitely in the hot path, so perhaps it's worth firing the benchmarks to see if the refactor would be at all worthwhile.

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1885374331

**Comment by ppedrot** [comment]
Given that neither the hashconsing PR nor the universe graph one led to performance enhancement, I am not very confident that this one will be observable either. The two former components are much more critical for performance than Evarsolve internals (if we forget about algorithmic issues with the representation of evar substitutions).

**Comment by rgrinberg** [comment]
Yes, the difference is mostly noise.

**Pull request closed without merging**
