### PR TITLE
Update headers to the new year.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation / infrastructure.

I finally took the time to update the copyright headers to the new year since no one else had done it.
I was happily surprised that the `dev/tool/change-header` script still works, although I had to adapt it to handle all types of headers.

Additionally, I fixed files stuck on outdated headers, and other files with outdated copyright mentions. The command `git grep "1999-" | grep -v "2019"` was useful to find these, as well as stuck headers.

Finally, I cleaned-up the CREDITS file a bit.

See commit messages for details.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Nice, thanks.  The number of files makes it hard to use the commenting UI, but here is one quick point: if possible, it would be nice to support shebangs, especially for fontsupport.py, since that file runs only in python2 (due to the fontforge dependency), and that fact isn't otherwise documented.  But we could also just add a comment to that file.

**Review by cpitclaudel — APPROVED** [review]

**Comment by Zimmi48** [comment]
I first considered doing that but I ended up thinking these were useless.

> that file runs only in python2 (due to the fontforge dependency), and that fact isn't otherwise documented

Do we really still depend on python2?!

**Comment by Zimmi48** [comment]
>Do we really still depend on python2?!

@cpitclaudel?

**Comment by cpitclaudel** [comment]
> Do we really still depend on python2?!

Yes and no? Yes, because Fontforge bindings were only available for Python 2 when I wrote the script, and I haven't checked recently whether Fontforge moved to Python 3 (I expect I wrote most of that script to be forward-compatible once Fontforge added Py3 bindings). No, because this code is mostly there for documentation purposes (it's used to generate a font file, but that file is checked into the repo, so the script doesn't need to (ever) be rerun)

**Comment by Zimmi48** [comment]
I have adapted the `change-header` script to handle shebangs. It could turn out to be more generally useful given the number of bash scripts that we have (currently without copyright headers).

**Comment by Zimmi48** [comment]
Can I get an assignee for this straightforward PR?

**Comment by cpitclaudel** [comment]
Done, thanks for the reminder

**Comment by JasonGross** [comment]
Note that this PR broke `fontsupport.py`; python *requires* the `# ... coding` line to be either the first or second line in the file; c.f. https://www.python.org/dev/peps/pep-0263/ .  (However, as we seem to be moving to python3 only, it is not so important, as python3 does not require such coding lines.)

**Pull request merged**
