### PR TITLE
Clean up/less files at root

### PR DESCRIPTION
**Pull request by Zimmi48**
See #6137.

### CODE REVIEW

**Review by SkySkimmer — DISMISSED** [review]
I think CONTRIBUTING should stay a toplevel file.

**Comment by Zimmi48** [comment]
> I think CONTRIBUTING should stay a toplevel file.

I hesitated about this one, so I'm going to follow your opinion. This reduces the interest of putting `ISSUE_TEMPLATE` in `.github/` but this will still reduce the number of files at the root whenever we decide to merge #975 and this also "hides" it.

**Comment by ejgallego** [comment]
Sorry I disagree with the removal of COPYRIGHT, also really hesitating about `README.doc`.

**Comment by SkySkimmer** [comment]
What is the README.doc for?

**Comment by gares** [comment]
> I disagree with the removal of COPYRIGHT

+1

**Comment by gares** [comment]
> README.doc

Looks like a file made of dust, designed to be outdated, and finally useless (the documentation is something you look up in the homepage of a software, not in its sources.. also it does not say where things are, so you learn nothing, really)

I think it should be removed.

**Comment by Zimmi48** [comment]
@ejgallego @gares 
> Sorry I disagree with the removal of COPYRIGHT, also really hesitating about README.doc.

You are aware though that this file isn't even up-to-date *and* does not bring any information, compared to what is in `CREDITS` and what is in the header of each of the source files in the repository? What are your reasons for wanting to keep it? If this is the name of the file, we could rename `CREDITS` into `COPYRIGHT` at the same time.

**Comment by ejgallego** [comment]
> we could rename CREDITS into COPYRIGHT at the same time.

The motivation is that COPYRIGHT is a standard file expected by many tools and developers, up to the point that it usually carries legal status. If COPYRIGHT is incorrect it should be updated, not removed IMO.

**Comment by Zimmi48** [comment]
I've removed the commit removing the COPYRIGHT file because this PR is not the place to have a legal discussion. But I some point I'll come back to this question.

**Pull request merged**
