### PR TITLE
Cache set of undefined impossible case evars in evar_flags

### LINKED ISSUE #8233: refining with an evar is 5x-10x slower than refining with a constr
#### Version

8.8.1

#### Operating system

Linux

#### Description of the problem

What is responsible for this difference in the speed of `refine` (which gets more pronounced at the number of iterations increases?

```coq
Goal True.
Time do 2000 (let x := open_constr:(_ : True) in idtac).
(* Finished transaction in 0.178 secs (0.148u,0.027s) (successful) *)
Undo.
Time do 2000 (let x := open_constr:(I : True) in idtac).
(* Finished transaction in 0.039 secs (0.04u,0.s) (successful) *)
Undo.
Time do 2000 (let x := open_constr:(_ : True) in refine (let y := x in _); clear y).
(* Finished transaction in 1.366 secs (1.367u,0.s) (successful) *)
Undo.
Time do 2000 (let x := open_constr:(I : True) in refine (let y := x in _); clear y).
(* Finished transaction in 0.208 secs (0.2u,0.008s) (successful) *)
```

cc @ppedrot

### PR DESCRIPTION
**Pull request by SkySkimmer**
This avoids a fold_undefined in evarconv, significantly improving perf
on the cases with ma,y undefined evars in
https://github.com/coq/coq/issues/8233#issuecomment-1792508252

0 defined evars + 20k undefined evars: 1.6s -> 0.11s

60k defined evars + 20k undefined evars: 4.1s -> 0.75s

Close #8233

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by JasonGross** [comment]
Nice!  Is it worth adding this example to coq-performance-tests (either one-off or in scaling)?

**Comment by SkySkimmer** [comment]
@coqbot ci minimize ci-bedrock2

**Comment by SkySkimmer** [comment]
Further reduced
~~~coq
Require Coq.Init.Byte Coq.Strings.Byte Coq.ZArith.ZArith.

Axiom proof_admitted : False.
Tactic Notation "admit" := abstract case proof_admitted.

Import Byte.

Module Export word.
  Class word {width : BinInt.Z} := {
      rep : Type;
    }.
  Arguments word : clear implicits.

End word.
Notation word := word.word.
Global Coercion word.rep : word >-> Sortclass.



Module map.
  Class map {key value:Type} := mk {
                                    rep : Type;
                                  }.
  Arguments map : clear implicits.
  Global Coercion rep : map >-> Sortclass.

End map.
Local Notation map := map.map.
Global Coercion map.rep : map >-> Sortclass.

Definition SuchThat(R: Type)(P: R -> Prop) := R.
Existing Class SuchThat.

Notation "'annotate!' x T" := (match x return T with b => b end)
                                (at level 10, x at level 0, T at level 0, only parsing).

Notation "'infer!' P" :=
  (match _ as ResType return ResType with
   | ResType =>
       match P with
       | Fun => annotate! (annotate! _ (SuchThat ResType Fun)) ResType
       end
   end)
    (at level 0, P at level 100, only parsing).

Global Hint Extern 1 (SuchThat ?RRef ?FRef) =>
         let R := eval cbv delta [RRef] in RRef in
           let r := open_constr:(_ : R) in
           let G := eval cbv beta delta [RRef FRef] in (FRef r) in
             let t := open_constr:(ltac:(cbv beta; typeclasses eauto) : G) in
             match r with
             | ?y => exact y
             end
               : typeclass_instances.

Class Multiplication{A B R: Type}(a: A)(b: B)(r: R) := {}.
Notation "a * b" := (infer! Multiplication a b) (only parsing) : oo_scope.


Import map.

Section Sep.
  Context  {map : Type}.
  Definition sep (p q : map -> Prop) (m:map) : Prop. Admitted.

End Sep.

Import Coq.ZArith.ZArith.

Section Scalars.
  Context {width : Z} {word : word width}.

  Context {mem : map.map word byte}.
  Definition scalar : word -> word -> mem -> Prop. Admitted.

End Scalars.

#[export] Instance MulSepClause{K V: Type}{M: map.map K V}(a b: @map.rep K V M -> Prop)
  : Multiplication a b (sep a b) | 10 := {}.


Class PointsTo{width: Z}{word: word.word width}{mem: map.map word Byte.byte}{V: Type}
  (addr: word)(val: V)(pred: mem -> Prop) := {}.
Global Hint Mode PointsTo + + + + + + - : typeclass_instances.

Class PointsToPredicate{width}{word: word.word width}{mem: Type}
  (V: Type)(pred: word -> V -> mem -> Prop) := {}.

#[export] Instance PointsToPredicate_to_PointsTo
  {width}{word: word.word width}{mem: map.map word Byte.byte}{V: Type}
  (pred: word -> V -> mem -> Prop){p: PointsToPredicate V pred}
  (a: word)(v: V): PointsTo a v (pred a v) := {}.

#[export] Instance PointsToScalarPredicate
  {width}{word: word.word width}{mem: map.map word Byte.byte}:
  PointsToPredicate word scalar := {}.

Section TestNotations.
  Context {width: Z} {word: word.word width} {mem: map.map word Byte.byte}.
  Local Open Scope oo_scope.
  Set Printing All.
  Goal forall (a1 a2 ofs sz v1 v2: word) (R: mem -> Prop) (m: mem),
      (infer! Multiplication R (infer! PointsTo a1 v1)) m.
~~~
seems to be from the first commit. Not sure what's happening.

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Cancelled the bench because without https://github.com/coq/coq/pull/18286 it will have a bunch of failures

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
