### PR TITLE
[test-suite] Remove a test with a Timeout that fails frequently on CI.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

We agreed previously that test files containing `Timeout` that failed randomly on CI would be removed. Here is one more. Last failure: https://gitlab.com/coq/coq/-/jobs/203628478.

### CODE REVIEW

**Comment by gares** [comment]
Is there a reason to prefer removal of the test to the removal of timeout?

**Comment by SkySkimmer** [comment]
The test without the timeout is of no interest AFAICT

Gaëtan Gilbert

**Comment by Zimmi48** [comment]
New occurrence: https://gitlab.com/coq/coq/-/jobs/205853343

**Comment by Zimmi48** [comment]
Yet another occurrence: https://gitlab.com/coq/coq/-/jobs/206370726

**Comment by gares** [comment]
There is anyway something wrong if, sometimes, the silly example takes forever. If slaves "sleep" for seconds, the we should  code an option to have timeout add some seconds of grace.  Removing the tests seems a wrong fix to me.

**Comment by Zimmi48** [comment]
New occurrence (this time, not a Nix job): https://gitlab.com/coq/coq/-/jobs/207374087

**Comment by gares** [comment]
having Coq understand a `TIMEOUT_GRACE` env variable is not very hard to implement. If you think this is desirable, then I can propose a PR. After all the `Timeout` vernacular is not the right way to measure performance regressions, so I see no big difference between `Timeout 1` and say `Timeout 5`. Still I prefer not to eventually remove all the tests using `Timout` just because the CI workers are trashing.

**Comment by Zimmi48** [comment]
We have infrastructure for complexity testing in `test-suite/complexity`. If I have more time to allocate to this question right now, what I would do is to port all the test files containing `Timeout` to use this infrastructure instead. That being said if you want to implement the solution you propose, that could already be a good step to solve the problem we are facing. Or, we could even just bump the values passed to `Timeout` in all the problematic tests...

**Review by vbgl — APPROVED** [review]

**Pull request merged**
