### PR TITLE
More efficient abstraction over variables in Cooking.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of repeatedly replacing the variables with a De Bruijn index and closing it, we do this in one pass. We furthermore share the abstraction over the context.

This source of slowdown was observed in lambda-rust.

### CODE REVIEW

**Comment by gares** [comment]
I've the impression that the new function should be somewhere in `Context` and be named `Named.to_rel` or `Rel.of_named`.

I'm also inferring from the code that `subst_var` replaces a variable by its position in the list. It is documented (I've just checked), but I think that, given the name is not particularly clear, you should sneak a comment in your code, eg "subst: maps named variables to De Bruijn indexes, the value of the index is the position of the variable in the list".

**Comment by ppedrot** [comment]
> I've the impression that the new function should be somewhere in Context and be named Named.to_rel or Rel.of_named.

This requires explicitly depending on terms, so it goes against #7080. Better not mess too much with side PRs.

> given the name is not particularly clear, you should sneak a comment in your code

Will do.

**Comment by ppedrot** [comment]
Added a comment.

**Comment by gares** [comment]
> This requires explicitly depending on terms, so it goes against #7080

Can you be more explicit?

I see the modules I named shall be moved elsewhere, but this is not the point.
My point is that a function converting a context from named to rel should be in `Context`.
You can named it `rel_context_of_named_context` if this is how the types are called after #7080 was merged.

**Comment by ppedrot** [comment]
I don't think either it makes much sense to put it in Cooking. Do you really think it's worthwhile to export this code?

**Review by maximedenes — APPROVED** [review]
The idea looks good, I tend to agree with @gares that `abstract_context` could find a better place, but I've no suggestion.

**Comment by maximedenes** [comment]
So @gares, what should we do?

**Pull request merged**
