### PR TITLE
Fix typo in documentation for identity

### PR DESCRIPTION
**Pull request by tchajed**
Fixes Coq [bug 5635](https://coq.inria.fr/bugs/show_bug.cgi?id=5635).

### CODE REVIEW

**Comment by tchajed** [comment]
I'm submitting this against v8.6, but if the rules are now different then I can re-target.

**Comment by psteckler** [comment]
Quoting @maximedenes from Gitter:

```
If it is trivial (like doc / comment fixes), you can target the 8.7 branch.
The workflow will very soon be to target trunk for everything, and branch maintainers will cherry-pick.
```

**Comment by herbelin** [comment]
Obvious fix indeed.

**Comment by ejgallego** [comment]
8.6.1 has been released, and it is all but frozen, it is likely that no more merges from 8.6 happen so I'd rather target `8.7`.

All this mess.... the default should be to always target `master` (yes, I wrote **master**) and we would have saved 100h.

**Comment by tchajed** [comment]
Oh right, I even saw that but didn't realize it applied to this situation just as well.

**Comment by tchajed** [comment]
@ejgallego: it's actually not a big deal to have the main branch be called `trunk` - it's unusual but everything mostly works since it's the branch you get when you clone in any tool. On the other hand, submitting PRs against version branches is unusual and bites me every time. I will be very happy when the recommendation is to submit all PRs against trunk and to backport only selectively.

**Comment by ejgallego** [comment]
> I will be very happy when the recommendation is to submit all PRs against trunk and to backport only selectively.

@tchajed this will be the case very soon, I hope...

> it's actually not a big deal to have the main branch be called trunk

It depends on your tooling, I think it is a pain for not a good reason. IMHO a very good thing to have wrt to external plugins and Travis stuff would be for them to mirror the branch structure of Coq; but most of them not surprisingly use `master` for the main dev branch...

**Pull request merged**
