### PR TITLE
Add a box and align items of the ( x , y , .. , z ) and [ x ; y ; .. ; z ] notations

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

So that it shows:
```
(long-term,
 other-term)
```
rather than
```
(long-term,
other-term)
```

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
The overlays should all just be output test updates.

**Comment by Alizter** [comment]
Unless the extra space in the printing of `(x, y, z)` is a mistake?

**Comment by SkySkimmer** [comment]
I think the spaces should be restored, `(x, y)` is nicer than `(x,y)`.

**Comment by herbelin** [comment]
> I think the spaces should be restored, `(x, y)` is nicer than `(x,y)`.

Losing the space was an overlook. I restored it.

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@coqbot merge now please

**Pull request merged**
