### PR TITLE
Correctly identify [Time Defined.] as a defined

### PR DESCRIPTION
**Pull request by tchajed**
Need to check inside control expressions. Also fixes handling of [Redirect "file" Defined.] and [Timeout n Defined.].

Fixes #5411: coqc -quick hangs on [Time Defined.]

### CODE REVIEW

**Comment by tchajed** [comment]
There's some very similar surrounding code that also handles Time/Timeout/Redirect incorrectly. If you'd like I can fix all of it with a `get_nested_expr` that factors out the logic to get the most nested expression, combined with doing those pattern matches on the result of `get_nested_expr e`.

**Comment by tchajed** [comment]
Also I couldn't get a test to fail without the fix using existing infrastructure. Even if I did, when it failed the test would hang, which would be annoying. Nonetheless it's troubling to fix any bug without a corresponding test.

**Comment by ejgallego** [comment]
LGTM! Wrt other fixes, note that we are actively experimenting on some refactoring of the STM which could render the fixes moot.

We were thinking of having a call to chat a bit about plans for the STM and parsing layer some of these days ( @maximedenes how's that going?) maybe you would like to join?

**Comment by tchajed** [comment]
@ejgallego sure, sounds good! Can you loop me in to an email thread or some other form of scheduling, at tchajed@mit.edu?

**Comment by JasonGross** [comment]
Does `Fail Defined ` behave correctly?

**Comment by JasonGross** [comment]
> Also I couldn't get a test to fail without the fix using existing infrastructure

Try sticking
```coq
(* -*- coq-prog-args: ("-quick" "-compile" "bugs/closed/PLACEHOLDER.v") -*- *)
```
at the top; does that work?

**Comment by tchajed** [comment]
`Fail Defined` works fine already.

That `coq-prog-args` doesn't quite work, but this does, in file `success/TimeDefined.v`:

```
(* -*- coq-prog-args: ("-quick" "-compile" "success/TimeDefined.v") -*- *)
Goal unit.
  exact tt.
Time Defined.
```

I think this test is ok, with a comment explaining what's going on (it compiles itself using the command line arguments, and then the regular test compilation is irrelevant). However, the failure mode is still an infinite loop, which I'd rather avoid if possible.

This is a low priority bug for me so I'll worry about it later.

**Comment by JasonGross** [comment]
> However, the failure mode is still an infinite loop, which I'd rather avoid if possible.

I'd rather avoid that if possible too, but I think having a test-case that hangs on failure is better than not having a test-case at all.

**Review by gares — APPROVED** [review]
Thanks!

**Comment by maximedenes** [comment]
Fixed in 8.6, thanks for contributing!

**Pull request merged**
