### PR TITLE
Stop handling evars as free variables in the VM.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead we rely on the structured constant mechanism, which globally allocates them. This is more efficient as it does not require to carry along evar values in closures.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
This PR is ready and needs an assignee.

**Review by silene — APPROVED** [review]
Looks sensible. My only fear is that this code path is completely untested, so who knows what kind of bugs might be lurking here.

**Pull request merged**
