### PR TITLE
[tools] Add memory stats to tables by default

### LINKED ISSUE #11575: Timing scripts should be able to display peak memory usage
The data is in the timing log, we should be able to process it.

Making this issue mostly to track that I want to do this (though others should feel free to do this if they want to and I haven't gotten to it yet)

### PR DESCRIPTION
**Pull request by JasonGross**
The Python scripts now support `--no-include-mem` to turn it off, and also support `--sort-by-mem`.

**Kind:** feature / infrastructure.

Fixes / closes #11575 

- [x] Added / updated test-suite
- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by JasonGross** [comment]
Question: Should the memory stats be enabled by default?  My inclination is yes.

**Comment by SkySkimmer** [comment]
Is there anyone who's familiar enough with the timefilemaker.py to review its changes?

**Comment by JasonGross** [comment]
cc @ejgallego who was assignee for the last PR on these files

**Comment by ejgallego** [comment]
Thanks for the ping @JasonGross , I'll need a couple of days but for sure this will be in 8.12 beta.

**Review by ejgallego — APPROVED** [review]
LGTM, `ko` is a weird unit tho.

**Pull request merged**
