### PR TITLE
[stdlib] [Arith] Typo in user message: Nat.add_com should be Nat.add_comm

### LINKED ISSUE #16463: Typo in suggestion `Nat.add_com`
#### Description of the problem

The file `https://github.com/coq/coq/blob/master/theories/Arith/Minus.v` gives warnings with error messages such as
```
The Arith.Minus file is obsolete. Use Nat.add_sub (together with Nat.add_com) instead.
```
with the typo `Nat.add_com` instgead of `Nat.add_comm`.

#### Coq Version

`8.16.dev`

### PR DESCRIPTION
**Pull request by olaure01**
Typo introduced in #15549.

Fixes #16463

### CODE REVIEW

**Review by proux01 — APPROVED** [review]
Will merge once CI is green

**Review by Alizter — APPROVED** [review]
ping @proux01

**Comment by proux01** [comment]
Thanks, this CI takes so long :sleepy: 

@coqbot merge now

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
