### PR TITLE
Temporarily remove VsCoq from CI

### PR DESCRIPTION
**Pull request by maximedenes**
The copy of VsCoq that is currently in the CI is an outdated ancestor of VsCoq 2. We remove it temporarily, and will put back the current VsCoq 2 development branch once #17331 is merged (and VsCoq 2 uses Coq's
  master).

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Makefile.ci and gitlab yml also need to have it removed

**Comment by maximedenes** [comment]
Oh ! But I did it locally, probably forgot to stage it.

**Comment by maximedenes** [comment]
Should be better now.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
