### PR TITLE
Move typed_vernac to its own file from vernacextend

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlays:
- https://github.com/coq-tactician/coq-tactician/pull/64
- https://github.com/LPCIC/coq-elpi/pull/481

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Nice, actually we could split `vernac` in two too.

**Comment by ejgallego** [comment]
Can you rebase @SkySkimmer ?

**Comment by ejgallego** [comment]
Unfortunately upstream changes in vscoq broke vscoq CI 

This PR is pretty harmless but could require an overlay, would you like @SkySkimmer to go ahead and merge or would you like to wait for the CI fix and re-run CI ?

cc: @maximedenes @gares

**Comment by SkySkimmer** [comment]
I'm not in a rush

**Comment by maximedenes** [comment]
> cc: @maximedenes @gares

https://github.com/coq/coq/pull/17949

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ejgallego** [comment]
@coqbot run full ci

**Comment by ejgallego** [comment]
It seems fiat_crypto is not working since the lastest changes, maybe we should disable it for now.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
