### PR TITLE
Fix #10176: shadowing vs automatic class based generalization + cleanups

### LINKED ISSUE #10176: Class-based automatic generalization ignores shadowing
~~~coq
Class Foo (xxx:nat) := foo : nat.

Lemma xy (Foo:bool->Type) `{Foo} : nat.
  (* Foo : bool->Type, xxx : bool, H : Foo xxx |- nat *)
Abort.

Fail Lemma yx (Fooo:bool->Type) `{Fooo} : nat.
~~~
`xy` should also fail.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlay https://github.com/QuickChick/QuickChick/pull/162

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
@skyskimmer: Trying to Interpret the `id` in a `` `{id ...}`` first as a bound variable seems also more natural to me (#10176). So I approve the objective.

More in the details, could the function `Libnames.idset_mem_qualid` be named more semantically? Intuitively, I would have called it `is_qualid_bound` or something like that.

Further in the semantics, one may wonder whether class detection should be done before or after interpretation. For instance, if I have:
```
Class Foo (xxx:nat) := foo : nat.
Notation myFoo := Foo.
Lemma aa `{myFoo} : nat.
```
should `myFoo` be considered as a class or not? So, maybe `implicit_application` should be call after `intern_type`?

Note incidentally that the canonical reviewer should rather be @mattam82, I guess.

**Comment by SkySkimmer** [comment]
>Intuitively, I would have called it is_qualid_bound or something like that.

I feel like the set doesn't have to be a set of bound names

>Further in the semantics, one may wonder whether class detection should be done before or after interpretation.

I dunno, make a PR trying, it'll open a discussion thread and show if there's an impact on CI I guess

**Comment by herbelin** [comment]
> I feel like the set doesn't have to be a set of bound names

OK. Let's keep it like this then.

> I dunno, make a PR trying, it'll open a discussion thread and show if there's an impact on CI I guess

I prefer to let @mattam82 here tell what he'd like.

In any case, I'm ok with the PR as it is.

**Comment by SkySkimmer** [comment]
@herbelin shall you merge?

**Comment by herbelin** [comment]
It seems that open questions remain (e.g. whether detection of a class should be done before or after interpretation of notations), but @mattam82 is apparently not available and the PR looks good to me as it is, so ok for merging. Shall do tomorrow

**Comment by herbelin** [comment]
@vbgl: Putting a priori milestone 8.10 for this bug fix on the basis that the API is conservative.

**Pull request merged**
