### PR TITLE
[api] Fix base_include LTAC parts.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by ejgallego** [comment]
Anyways when the configure option `--disable-API` is introduced we may want to refine this more, but should be good for now.

**Comment by mattam82** [comment]
LGTM, it makes the test-suite pass again right?

**Comment by ejgallego** [comment]
@mattam82 I think the test suite was not failing on this one, this include is just not tested AFAICS.

**Comment by mattam82** [comment]
It is tested in misc/printers.sh, and the patch solves it

**Comment by ejgallego** [comment]
> It is tested in misc/printers.sh, and the patch solves it

I see, weird it was not catch by Travis then.

**Comment by Zimmi48** [comment]
That's not the first time that this test fails and Travis doesn't catch it. Can someone open a bug report about this?

**Pull request merged**
