### PR TITLE
refactor: remove pointless array allocation

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
In Coq land "refactor" implies a bigger change, this is "cleanup"

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I don't think it's worthwhile to run a bench, this is very, very unlikely to be observable.

**Comment by rgrinberg** [comment]
Yes, it's mostly for the removal of the unused variable and the corresponding warning

Rudi.

**Comment by ppedrot** [comment]
CI failures are unrelated, let's merge.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
