### PR TITLE
program_inference_hook: use refine_by_tactic instead of build_by_tactic

### PR DESCRIPTION
**Pull request by SkySkimmer**
refine_by_tactic is more appropriate AFAICT (program_inference_hook is
similar to an implicit ltac:() which is refine_by_tactic).

This would also allow us to call it on non evar free goals (ie remove
the is_ground checks just above) but not sure we want to.

Overlays:
- https://github.com/Mtac2/Mtac2/pull/401

### CODE REVIEW

**Comment by SkySkimmer** [comment]
May be incorrect when the tactic doesn't solve the goal but modifies it, I  need to look into this more.

**Comment by ppedrot** [comment]
Can't you just wrap the tactic in a tclSOLVE?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@JasonGross the error is caught by the surrounding code in case of failure of solving the goal. If there were an issue we would have caught it in the CI anyways.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
