### PR TITLE
Better messages for kernel qualities and relevance errors

### PR DESCRIPTION
**Pull request by ppedrot**
In order to ease the life of the poor soul who is trying to debug the upper layers sending wrong qualities and relevances to the kernel, we print more information in the corresponding error messages. Note that these messages are always signaling a bug in the implementation and should actually never reach the end-user, once we fix all the bugs above.

I had to hack a bit to intercept the bad-relevance warning and turn it into the (previously unused) BadRelevance error. We do this by exposing an API to check the current status of a warning.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
>I had to hack a bit to intercept the bad-relevance warning and turn it into the (previously unused) BadRelevance error. We do this by exposing an API to check the current status of a warning.

Having an API to declare a warning with the printer declared in an upper layer would also be useful, but certainly out of scope for this PR.

**Comment by JasonGross** [comment]
> Note that these messages are always signaling a bug in the implementation and should actually never reach the end-user, once we fix all the bugs above.

Should they be anomalies, then?

**Comment by ppedrot** [comment]
> Should they be anomalies, then?

No, because they would make SProp unusable. For the time being we ought to be able to deactivate them to work around the bugs in the implementation. (Also, the notion of "anomaly" for the checker is more questionable when we can be given very wrong input.)

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
