### PR TITLE
[v8.7] Don't allow coq-dpdgraph to fail

### PR DESCRIPTION
**Pull request by JasonGross**
This can be merged into 8.7, but the merge into master requires an independent fix

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks. I'll take care of it as soon as Travis gives the green light.

**Comment by Zimmi48** [comment]
@JasonGross Sorry but it didn't pass.
There are several `open API` that should be dropped now.

**Comment by JasonGross** [comment]
Argh, dropping `open API` completely breaks the build with master at an earlier point...

**Comment by JasonGross** [comment]
Overlay added

**Comment by Zimmi48** [comment]
Normally it shouldn't but you may have to go through a trick to call coq_makefile each time as in https://github.com/coq/bignums/pull/2

**Comment by JasonGross** [comment]
[It builds fine with the overlay, without any special tricks.](https://travis-ci.org/coq/coq/jobs/265036630)  I've added back the `needs: independent fix`, under the assumption that we're waiting to merge this until https://github.com/Karmaki/coq-dpdgraph/pull/33 gets merged and we don't need the overlay anymore.  (Is this right?)  And I've moved the project to 8.7.0, since this shouldn't block the beta.

**Comment by Zimmi48** [comment]
Right, I had only seen the first part of your overlay commit so I thought that whatever needed to be had been merged.

**Comment by SkySkimmer** [comment]
Please do the gitlab.yml change too (also in #971).

**Comment by JasonGross** [comment]
Overlay removed, `.gitlab-ci.yml` updated

**Pull request merged**
