### PR TITLE
allow failure on metacoq

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
Is it really that hard to fix? Allow-failure is just pushing the dirt under the rug.

**Comment by Zimmi48** [comment]
>Allow-failure is just pushing the dirt under the rug.

Not completely, since we still get the (neutral) status report "Test has failed".

The benefit is that people can stop worrying why their PR is not passing CI.

How long has metacoq been failing?

**Comment by SkySkimmer** [comment]
since https://gitlab.com/coq/coq/-/jobs/2084795762

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Merging soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
