### PR TITLE
Fix logic for which names are considered taken by globals

### PR DESCRIPTION
**Pull request by SkySkimmer**
See discussion in #9493.

### CODE REVIEW

**Comment by maximedenes** [comment]
This looks closely related to https://github.com/coq/coq/issues/9323, can you check if it fixes it?

**Comment by SkySkimmer** [comment]
>This looks closely related to #9323, can you check if it fixes it?

It doesn't.

**Comment by SkySkimmer** [comment]
This breaks compatibility, do we go forward with overlays or drop it?

**Comment by SkySkimmer** [comment]
If we're changing how to alpha rename things we should also put some thought into it. For instance why do we rename in
~~~coq
Definition x := Prop.
Goal forall x : Prop, x.
~~~
?
What about 
~~~coq
Definition x := Prop.
Module M.
  Goal forall x : Prop, x.
~~~
?

**Comment by SkySkimmer** [comment]
See #9593

**Pull request closed without merging**
