### PR TITLE
Issues with printing based on scope (#873): performance and use of abbreviation for printing.

### LINKED ISSUE #6777: Regression in notation printing
From mathcomp, `fingroup/quotient.v`:
```
Variables (gT : finGroupType) (Q A : {set gT}).
Notation H := <<A>>.
Check <<A>>.
(*
@generated gT A
     : @set_of (FinGroup.arg_finType (FinGroup.base gT))
         (Phant (Finite.sort (FinGroup.arg_finType (FinGroup.base gT))))
*)
Check H.
(*
@generated gT A
     : @set_of (FinGroup.arg_finType (FinGroup.base gT))
         (Phant (Finite.sort (FinGroup.arg_finType (FinGroup.base gT))))
*)
```
In both cases, the system prints `<<A>>` and not `H`.

I don't know when the regression took place.

### PR DESCRIPTION
**Pull request by herbelin**
Fixes #6777, #6536 and #6416.

Warning: it builds on top of #6247 with which it interferes.

I made some cleaning at the same time, so, it might not be unwise to not commit it in urgency on a day of freeze.

### CODE REVIEW

**Comment by maximedenes** [comment]
> it might not be unwise to not commit it in urgency on a day of freeze.

I'm not very good with classical logic. Concretely, what do you suggest? That we target 8.9 for #873 and this ?

**Comment by Zimmi48** [comment]
I think that this is indeed what @herbelin suggests, so I guess that requires branching and merging the revert PR #6949 only in v8.8...

**Comment by herbelin** [comment]
I don't know what to answer because I'm lost in what is the intent of the beta and in what are the plans between the beta and the final. Is the beta-final period intended for bug fixes? Is it naive to consider that the current PR precisely enters the category of fixes elligible for integration between a beta and a final?

PS: I'm asking the question also on #6954 to centralize such discussions.

**Comment by Zimmi48** [comment]
I'm going to answer here and over there. Here I am going to be more specific.
You are correct that the period of the beta is for bug fixes (and documentation improvements). However, we like as much as possible to avoid what we call "dangerous" bug fixes. Moreover clean-ups, and new features are strictly forbidden. Of course the category of "dangerous" bug fixes is not well defined but it includes very large diffs, changes to the behavior of tactics, or the pretyper.
If we discover an important bug after the beta release, of course we fix it nonetheless, even if the fix is "dangerous" but then we are forced to do a new beta and this poses the threat of making the final release late.
That's why, if we discover an important bug *before* the beta release (like in this case), we can't ship the beta with this bug: this would defeat the purpose of the beta.
Given the "dangerous" nature of this particular bug fix (including in passing new features and a refactoring), we can only delay the whole stuff as I said in my comment above (but I thought that's what you meant as well).

However, all ends well in that this feature can stay nonetheless in master thanks to the fix you provided. There are many users that use Coq master, and this means that you won't have to wait six months to get users testing this and giving you feedback (we wouln't have discovered the bugs if there weren't). It's a huge advantage for such a feature to get merged early in the cycle because it means getting lots of time to gather feedback and having the possibility of refining the feature without having to care about breaking compatibility. So yeah that's a pretty good outcome :fireworks:

**Comment by herbelin** [comment]
It seems to be a matter of compromise... I'd prefer to adopt the view that releasing the feature in 8.8 is prioritary. After all, we can just commit my fix and if ever a second step is needed, it will be possible to do it in the beta period. We are in a domain of relatively well-delimited features anyway.

**Comment by maximedenes** [comment]
This "fix" is really a complement of a missing feature of the original PR (called an "open problem" in the commit message). If this feature was prioritary for 8.8, you could have implemented it fully before the freeze.

But as @Zimmi48 said, the good news is we can integrate it early in 8.9, and I'm sure our users who follow `master` will be happy to give feedback.

**Comment by herbelin** [comment]
> This "fix" is really a complement of a missing feature of the original PR (called an "open problem" in the commit message). If this feature was prioritary for 8.8, you could have implemented it fully before the freeze.

Are you talking about the "custom" PR or are you talking about the fix to #873?

If you are talking about "custom", I don't understand what you mean by "fully implemented". The "custom" was and is still waiting for users.

If you are talking about the fix #873, what "open problem" are you talking about?

I feel that there is miscommunication about what 8.8beta and 8.8.0 are supposed to be. Several users have expressed interest in both features and I feel that they are not listened to.

**Comment by Zimmi48** [comment]
> Several users have expressed interest in both features and I feel that they are not listened to.

I feel like it is you who are not listening as one of these users was @RalfJung and he precisely backed our position.

**Comment by herbelin** [comment]
@Zimmi48: So, how do you propose to make progresses? I don't feel responsible for not having had feedback on the PR between Nov 2017 and 2 days ago. So, what is your analysis of the failure?

**Comment by Zimmi48** [comment]
Well for this feature in particular, I pretty much said it already, you just have to read my comments again. For the more general question of the efficiency and analysis of the failure, I'm going to take the time to answer but as said before, this may take a week.

**Comment by Zimmi48** [comment]
In fact no, *this* will be my last words: you bare the full responsibility of not having prepared this fix earlier for issues that were reported weeks ago and even more problematic for not having clearly said that you didn't like the conclusion to revert of the last WG.

**Comment by herbelin** [comment]
> you bare the full responsibility of not having prepared this fix earlier for issues that were reported weeks ago

I accept the responsibility of not having prepared a fix earlier (about #873). I apparently did not take the measure of how it was important for some people.

Reading the #873 thread there, I indeed said mid-December that "I shall try to concentrate on it by a few days" which I did not. I think that one reason I did not was that I was not fully clear at which level to address the incompatibilities exactly yet.

Later on, to be honest, I wondered at some time whether @ppedrot would like to propose a fix to the efficiency issue (as he did, on his own initiative for the evar names inefficiency).

> even more problematic for not having clearly said that you didn't like the conclusion to revert of the last WG.

I was particularly surprised by this decision. I thought I was one of the person primarily concerned with #873 and I did not understand why nobody had asked me my opinion about it. I cautiously wrote to @maximedenes to understand what were the motivations.

Of course I was willing to do a fix. I just did not realize how important it was that it had to be done quickly. Sorry about that.

**Comment by herbelin** [comment]
Taking advantage that custom entries are merged (#8815), #8187 replaces this PR.

**Pull request closed without merging**
