### PR TITLE
remove Zdigits

### PR DESCRIPTION
**Pull request by andres-erbsen**
- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

### CODE REVIEW

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
The CI failures appear unrelated.

**Comment by proux01** [comment]
Shouldn't this be deprecated before removal? In any case, this would require a changelog entry.

**Comment by Alizter** [comment]
It would be nice to be able to completely deprecate modules. cc @coq/vernac-maintainers how feasible would this be to implement?

**Pull request closed without merging**
