### PR TITLE
Split timing tests

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should make error reporting nicer as we won't get a big unrelated log before the failure.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
ping @coq/test-suite-maintainers

**Comment by herbelin** [comment]
Not very knowledgeable on timing, but I can merge if noone objects.

**Comment by SkySkimmer** [comment]
Please merge

**Review by ejgallego — APPROVED** [review]
LGTM.

However, makefile stuff like this is IMHO impossible to review properly.

IMHO we should discuss the test-suite roadmap, I think that doing further work on the makefile system may risk that the work is never properly reviewed or merged.

I think we should focus instead on improving the infrastructure so it can be maintained. I don't think we can properly maintain the current system.

**Comment by herbelin** [comment]
> IMHO we should discuss the test-suite roadmap

I don't have an opinion, nor have the expertise to comment. I can talk about some of my needs:
- it is convenient to be able to run parts of the test-suite, e.g. `make output` or `make success`, or even `make foo.v.log`, in parallel with others tasks, so without being blocked by a dune lock
- it is inconvenient to have to do `rm -f test-suite/summary.log` after having run the test suite
- the `make summary` is excessively long (maybe it is me who wrote it, but if so, the way I did it did not scale with the increase of the size of the test-suite, so, something better should be proposed)
- I need to access the failing logs easily, and even the failing line of a test easily

**Pull request merged**
