### PR TITLE
Apply whd_beta before checking dependencies in dtauto

### PR DESCRIPTION
**Pull request by jashug**
Original issue #6393.

I rewrote `has_nodep_prod_after` to only perform one pass over the term being checked, and to
`whd_beta` reduce the types of arguments before checking for dependencies on previous arguments.
(c.f. my other PR which used `nf_beta`).

In #6461, @SkySkimmer said that the returned args from `match_with_one_constructor` should
also be beta reduced. This PR currently does not do so, such reduction could be done simply by
a `List.map whd_beta` or by having `has_nodep_prod` return the list of normalized args
(note that `prod_assum` runs the exact same loop as `has_nodep_prod`).

This should be faster than the other PR, but the little testing I did suggests this is
way off any performance-critical path. Also:
* The rewritten `has_nodep_prod_after` is harder to understand.
* If we want to strengthen the normalization to a full normal form (not head-normal), then
  we may as well normalize the whole type once at the beginning.
* In this approach, I don't see how to reduce let-ins in the middle of the type, as suggested in #2629.

My opinion is that #6461 is a better approach, but I wanted to share this version for comparison.

### CODE REVIEW

**Comment by herbelin** [comment]
About the impact on #2629, well found! This makes me suspect that using the let-in-aware `Vars.prod_applist_assum` rather than `prod_applist` may fix the let-in issues (but I'm telling that without having carefully looked at the problem, so maybe I'm wrong).

**Comment by jashug** [comment]
`prod_applist` does cause problems (see #6490), but the suggestion in #2629 was that a post-`prod_applist` type of the constructor could be recognized as non-dependent by expanding let-ins in the regular fields.
`prod_applist` is only used here to apply the known parameters, so using `prod_applist_assum` wouldn't grant the feature wish in #2629.
(It might fix #6490 though. Is there a version of `prod_applist_assum` that works with econstr? If I'm reading the ocaml right, [the one in kernel/term.ml](https://github.com/coq/coq/blob/ddfca160f14eba979bcaa238da4c91e4e445f37b/kernel/term.mli#L262) is typed to constr.

**Comment by herbelin** [comment]
> Is there a version of prod_applist_assum that works with econstr?

Not yet, so it should be added. Not clear by the way that the version in `term.ml` is necessary. Maybe the version from `term.ml` should just be econstrized to `termops.ml` (don't know the opinion of @ppedrot).

In any case, avoiding mixing questions, for the purpose of this PR, adding an `EConstr` copy of `prod_applist_assum` should be enough for at least #6490.

**Comment by jashug** [comment]
Closing in favor of #6461.

**Pull request closed without merging**
