### PR TITLE
coqdoc: Support comments in verbatim output

### PR DESCRIPTION
**Pull request by tchajed**
Fixes [BZ#5700](https://coq.inria.fr/bugs/show_bug.cgi?id=5700)

### CODE REVIEW

**Comment by silene** [comment]
The patch makes sense to me, but the oracle does not make sense. So I would refrain from including this pull request until it is clearer what is going wrong. (Committing seemingly incorrect oracles usually incurs undue pains in the long term.)

**Comment by mattam82** [comment]
@silene The oracle? Which oracle?

**Comment by silene** [comment]
> The oracle? Which oracle?

I am talking about the two `.out` files added to the testsuite. How would you call them if not oracle?

**Comment by tchajed** [comment]
Those are expected output from coqdoc. That seems to be how the two existing coqdoc tests work.

I would certainly prefer a finer-grained set of coqdoc tests (eg, that checked output for a single comment), but that isn't the subject of the PR and isn't necessary for this change. In the meantime, this change needs a test, and tests need expected output.

Am I missing some other way to add a test for this change?

**Comment by mattam82** [comment]
The expected HTML output looks good to me and I don't think there's other ways to test this but I may be missing something as well.

**Comment by silene** [comment]
You missed my point. I am not saying this change does not need a test. I am saying that the output of your test is incorrect (the second comment is seemingly parsed as an inline one while it is obviously not). So either there is a bug in your patch or an existing bug in coqdoc. Even in the latter case, we should refrain from pushing this commit because it would somehow make this existing bug the expected behavior.

**Comment by silene** [comment]
> The expected HTML output looks good to me

No, the second comment should be output as

    <pre>more (* nested (* comments *) within verbatim *) </pre>

**Comment by tchajed** [comment]
@silene I've updated the test to avoid triggering this coqdoc bug.

For the record, I did not notice anything wrong with the test, nor do I find it obvious that the second comment should also be output as a block. Furthermore, the latex and HTML output agreed that the first comment should be block and the second should be inlined. It would have been helpful if your comment had been a review comment attached to the particular lines you found problematic.

**Comment by maximedenes** [comment]
@silene do I understand correctly that this PR is ok but the coqdoc bug should be reported?

**Comment by silene** [comment]
> do I understand correctly that this PR is ok but the coqdoc bug should be reported?

Right.

**Comment by herbelin** [comment]
Hi, I'm curious about the remaining coqdoc "bug", if any, but I could not find the original 39700a7 commit any more, nor the original example. @tchajed: could you remind it, please?

**Comment by tchajed** [comment]
Oh sorry, I did a force push to fix the PR. The bug is that with consecutive comments with verbatim text, the first comment is rendered as a block (`<pre>` or `\begin{verbatim}`) whereas the second is rendered inline (`<tt>` or `\texttt`).

Coq:
```coq
(** << here's a comment >> *)

(** << there's a comment >> *)
```

LaTeX (snippet):
```tex
\begin{coqdoccode}
\end{coqdoccode}
\begin{verbatim}here's a comment \end{verbatim}
 

 \texttt{there's a comment } \begin{coqdoccode}
\end{coqdoccode}
```

HTML (snippet)
```html
<div class="code">
</div>

<div class="doc">
<pre>here's a comment </pre>
 
<div class="paragraph"> </div>

 <tt>there's a comment </tt> 
</div>
<div class="code">
</div>
</div>
```

@silene: Could you turn this example into a Coq bug report, with some rationale for why you think both comments should be block?

**Comment by herbelin** [comment]
@tchajed, @silene: I fixed the inconsistency at #1009 but I'm uncertain that it is the intended behavior from the original 893a3ac7b. In
```coq
(**
<<
...
>>
*)
```
it is clearly verbatim which is expected, but is it clear that we want 
```coq
(** << foo1 >> *)
```
giving `<pre>` and
```coq
(** bar << foo2 >> *)
```
giving instead `<tt>`?

Do I understand correctly @silene's message that `foo1` should morally not be in a block, and hence be a `<tt>`?

**Comment by tchajed** [comment]
@maximedenes ping, I think this has everyone's approval. Discussion about the coqdoc behavior for consecutive commands should move to [bug 5711](https://coq.inria.fr/bugs/show_bug.cgi?id=5711).

**Pull request merged**
