### PR TITLE
[release] Bump magic numbers for 8.12.0 tag

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by Zimmi48** [comment]
The reason for the failing test-suite is that #12734 should be merged and backported first.

**Comment by ejgallego** [comment]
Ok @Zimmi48 , I think we are all set [modulo adjusting VST if it arrives on time]

Should the CI work here, that'd be a candidate for the tag I think.

**Comment by ejgallego** [comment]
Rebased.

**Comment by Zimmi48** [comment]
Oh, I don't think this is necessary to wait for CI to be green for this PR again. I'll merge now and we'll wait to have a fully green CI (and tested Windows and macOS packages) for `v8.12` before we actually put the tag.

**Comment by ejgallego** [comment]
Ok that works too, please cancel this pipeline then.

**Pull request merged**
