### PR TITLE
Legacy build: remove nonsense `byte` target and noop `install-byte`

### LINKED ISSUE #14658: Makefile.build should not have byte:world
This is just nonsense, either we should do the right calls to dune (I have no clue what they are) or remove the target.

### PR DESCRIPTION
**Pull request by SkySkimmer**
`byte` was equivalent to `world`

Close #14658

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
OSX failure is real

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@SkySkimmer this was kept for compat as many custom build scripts did `make byte`, I suggest you at least print a message for 8.16 if the user does `make byte`

**Comment by gares** [comment]
@SkySkimmer would you mind rebasing?

**Comment by SkySkimmer** [comment]
>@SkySkimmer this was kept for compat as many custom build scripts did make byte, I suggest you at least print a message for 8.16 if the user does make byte

make will say "unknown target" or some such thing by itself

**Comment by gares** [comment]
nix failure is real?!

**Comment by SkySkimmer** [comment]
Looks like install-byte is a noop so I also removed it.

**Review by vbgl — APPROVED** [review]
Changes to `default.nix` look good.

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
