### PR TITLE
Fix handling of recursive notations with custom entries

### LINKED ISSUE #9490: Error: Anomaly "Uncaught exception Failure("unknown level 202")."
#### Description of the problem
The following code raises an uncaught exception. In my understanding, it should work just fine.
```coq
Declare Custom Entry with_pattern.
Declare Custom Entry M_branch.
Notation "'with' | p1 | .. | pn 'end'" :=
  (cons p1 (.. (cons pn nil) ..))
  (in custom with_pattern at level 91, p1 custom M_branch at level 202, pn custom M_branch at level 202).
Notation "'bla'" := I (in custom M_branch at level 202).
Notation "'[use_with'  l  ]" := (l) (at level 0, l custom with_pattern at level 91).
Check [use_with with | bla end].
Check [use_with with | bla | bla end].
(* 
Error: Anomaly "Uncaught exception Failure("unknown level 202")."
Please report at http://coq.inria.fr/bugs/.
frame @ file "toplevel/coqloop.ml", line 380, characters 10-36
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "toplevel/coqloop.ml", line 265, characters 6-89
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "lib/flags.ml", line 17, characters 14-17
raise @ file "clib/exninfo.ml", line 65, characters 2-15
frame @ file "vernac/vernacstate.ml", line 22, characters 10-35
raise @ file "clib/exninfo.ml", line 65, characters 2-15
*)
```

*Note* that in line 8 (second-to-last line), the same notation with just one instance of the recursive part works.

#### Coq Version
8.9 & master as of today.

cc @herbelin (who probably knows best what's going on here)

### LINKED ISSUE #9532: custom entry recursive notation parsed as constr
#### Description of the problem

```coq
Declare Custom Entry atom.
Notation "1" := tt (in custom atom).
Notation "atom:( s )" := s (s custom atom).

Declare Custom Entry expr.
Notation "expr:( s )" := s (s custom expr).
Notation "( x , y , .. , z )" :=  (@cons unit x (@cons unit y .. (@cons unit z (@nil unit)) ..))
  (in custom expr at level 0, x custom atom, y custom atom, z custom atom).

Check atom:(1).
Check expr:((1,1)).
Check expr:((1,1,1)).
(* > Check expr:((1,1,1)). *)
(* >                  ^ *)
(* Error: The term "1" has type "nat" while it is expected to have type "unit". *)
Check expr:((1,1,1,1,1)).
(* Toplevel input, characters 17-18: *)
(* > Check expr:((1,1,1,1,1)). *)
(* >                  ^ *)
(* Error: The term "1" has type "nat" while it is expected to have type "unit". *)
```

#### Coq Version

8.9.0

@herbelin ?
requesting part:notations

### PR DESCRIPTION
**Pull request by maximedenes**
Fixes #9532
Fixes #9490

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Looks very good. Well done!

**Comment by maximedenes** [comment]
@coq/ci-maintainers is the bedrock2 failure known?

**Comment by maximedenes** [comment]
> @coq/ci-maintainers is the bedrock2 failure known?

Ah yes, just saw https://github.com/mit-plv/bedrock2/issues/120, sorry.

**Comment by maximedenes** [comment]
@herbelin I believe this fix is ready for merge, the windows and bedrock2 failures are known to be spurious.

**Comment by herbelin** [comment]
OK, I assign and will merge.

**Pull request merged**
