### PR TITLE
Do not allocate AConstr evar instances.

### PR DESCRIPTION
**Pull request by ppedrot**
They are never used by `w_unify_to_subterm`, and it should save a lot of memory in fiat-crypto.

### CODE REVIEW

**Comment by JasonGross** [comment]
This brings the memory usage of Derive.vo down to 3667348 ko, which is enough of an improvement to build that file.  Now we're failing in a way that suggests we need both this and https://github.com/coq/coq/pull/16801 to make fiat-crypto pass.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
I am marking this as ready for review, as it cannot hurt.

**Review by SkySkimmer — APPROVED** [review]
A bit hacky but seems correct

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
