### PR TITLE
Default HintDb option

### LINKED ISSUE #10559: Allow hints with no specified database inside sections.
This issue records that something needs to be done to properly handle the depreciation in 8.10 
of hints added to the core database: https://github.com/coq/coq/pull/8987
Discussed with @Zimmi48 and @maximedenes 

The illegitimate use pattern that the PR aims to get rid of is:

```
Hint Resolve mylemma. (* outside of any section, trying to extend the global database *)

Lemma bla... (* possibly in a different file, with a call to auto implicitly using mylemma. *)
```

However, one very legitimate use pattern is:

```
Section Foo. 
Hint Resolve mylemma.
Lemma bla...
End Foo.
```

I think it should continue to be accepted, in its current form, with the semantics that the hint spans over the section.

Yet to be addressed in the case of:

```
Section Foo. 
Lemma bla.
Proof.
   Hint Resolve mylemma. (* hint inside a proof *)
Qed.
End Foo.
```
Should this be allowed? Should the hint span over the current proof only (intuitive) or the entire section (not intuitive, but I think it's the current behavior).

Furthermore, as a facility for users who were previously relying on the core database, and for other users in general, one very nice feature would be to enable extending the "current" hint database with an existing database.

```
Hint Resolve bar1 bar2  : mydatabase. (* replace previous use of core *)

Section Foo. 
Hint mydatabase. (* here all mydatabase lemmas can be used by auto *)
Lemma bla...
End Foo.
```

Such a script could be a properly fixed version of the illegitimate pattern described at first in this thread.

Last, as a killer feature, one would be able to assign a name to the union of several bases. This would enable *modularity* in proof scripts. Such a desirable property. 

```
Declare HintDb mybase1 := union mydatabase1 mydatabase2.
```
Ability to remove one or several hints would also be the next feature wish (that would require hint externs to be assigned explicit names, to allow referring to them).

Please note that:
- the "eauto with" syntax is good to have, but in general is super heavy and does not scale up well, in comparison to using per-section hints,
- rebinding "auto" to something else is super not modular (two libraries could rebind it differently).

Remark: if the syntax `Hint Resolve foo.` not inside a section is removed, it could then be reinterpreted as `Local Hint Resolve foo`, which has the meaning "use foo as a hint within the scope of the current file".

### PR DESCRIPTION
**Pull request by Alizter**
We add a `Default HintDb` optional string that will let users set which hint database we fall back on when tactics such as `auto` and `eauto` are used. At the moment, such behavior is de facto claimed by `core`, so we set `core` as the default hint database in the stdlib globally.

Fixes / closes #10559

Related is #14752 but there is a more bold feature proposed there.

- [x] Added / updated **test-suite**.
- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.
  - [ ] Documented any new / changed **user messages**.
  - [ ] Updated **documented syntax** by running `make -f Makefile.make doc_gram_rsts`.
- [ ] Opened **overlay** pull requests.
  - Expected overlays (these don't use stdlib so "core" is not set to default):
    - [ ] Overlay for stdlib2
    - [ ] Overlay for HoTT

I've marked this PR as a draft as there is more work to do:

I've changed the semantics (by accident) for "nocore". I've found #2188 discussing the indented semantics. When I first wrote this patch, I completely removed the nocore database and tried to replace it with setting and unsetting the default hint database, but this didn't really work as intended. I therefore reverted to touching the behaviour of nocore as little as possible but it seems I haven't been successful in this regard.

I would like to perhaps add a modifier to `auto` and `eauto` which lets them skip the addition of the default hint database to a list. This ought to subsume the behaviour of nocore.

`typeclasses eauto` is another problem I didn't really want to get into but, I suppose needs to be discussed. It acts like `typeclass_instances` is it's core database, and I have even seen uses of it using the (psuedo)database nocore in the test-suite. I am unsure what needs to be done here.

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot ci minimize

**Comment by Zimmi48** [comment]
Hi @Alizter, thanks for working on this! But somehow it seems that you have implemented something closer to my initial post at  #14752 rather than the more limited first bullet-point of https://github.com/coq/coq/issues/14752#issuecomment-894775692 (which only changes the behavior of `Hint` commands without changing the one of `auto` / `eauto`).

It seems that since users may want a cumulative behavior for defining the default databases of `auto` / `eauto`, it would be preferable to not provide any default database feature for `auto` / `eauto` until we can provide it fully. In the meantime, the `Default HintDb` option would still be quite useful (for `Hint` commands) to allow moving forward with the deprecation of the implicit core db feature.

**Comment by Alizter** [comment]
OK, so you want `Default HintDb` to only change the behaviour of the hint commands and not `auto`? That seems a bit weird to me since someone might do:
```coq
Set Default HintDb "myhintdb".
Axiom magic : nat.
Hint Resolve magic.
Goal nat.
auto.
```
I would expect this to be invariant of setting the default hint database, but with what you are proposing this would no longer be the case.

**Comment by Zimmi48** [comment]
That's a good point.

**Comment by Alizter** [comment]
@JasonGross @Zimmi48 the minimizer seems to have gone a bit haywire. How can I stop it?

**Comment by Zimmi48** [comment]
I've canceled the current run.

**Comment by Alizter** [comment]
@Zimmi48 Should I make progress with this?

**Comment by JasonGross** [comment]
If this happens, it might make sense to solve https://github.com/coq/coq/issues/7725 at the same time?  (I'd like to see https://github.com/coq/coq/issues/7725 solved in any case, but having the default database for `intuition` be `auto using *` seems really bad.)

**Comment by Alizter** [comment]
Closing for now since I have no plans to continue this.

**Pull request closed without merging**
