### PR TITLE
[ssr] Stop relying on camlp5 recovery mechanism

### PR DESCRIPTION
**Pull request by proux01**
Stop relying on camlp5/coqpp recovery mechanism for "do [tac] => intro" and "tac; [tac|..|tac] => intro"

This is in preparation of https://github.com/coq/coq/pull/17876

- [ ] ~Added / updated **test-suite**.~

- [ ] ~Added **changelog**.~
- [ ] ~Added / updated **documentation**.~
  
  - [ ] ~Documented any new / changed **user messages**.~
  - [ ] ~Updated **documented syntax** by running `make doc_gram_rsts`.~

- [ ] ~Opened **overlay** pull requests.~

#### Overlays (to be merged before the current PR)

- [x] https://github.com/math-comp/analysis/pull/1088
- [x] https://gitlab.mpi-sws.org/iris/stdpp/-/merge_requests/536
- [x] https://github.com/mit-pdos/perennial/pull/58

#### Overlays (to be merged in sync with the current PR)

- [x] https://github.com/mattam82/Coq-Equations/pull/578
- [x] https://github.com/MetaCoq/metacoq/pull/1035
- [x] https://github.com/LPCIC/coq-elpi/pull/586

### CODE REVIEW

**Comment by herbelin** [comment]
By the way, the notations `.1` and `.2` are extremely standard and should be reserved in `Init` (even if whether they apply to prod or sigT is not standardized... somehow we should eventually find a way to overload the notations for prod and sigT...).

**Comment by herbelin** [comment]
Note: as future work for the notation system, we could think at how to define a notation `x . N` on lists or n-tuples which stands for `hd (tl .. (tl x) ..)` repeated `N` times. Something like:

```coq
Notation "x . N" := (hd (tl .. (tl x) ..)) (N meta-natural).
```
or maybe
```coq
Notation "x . N" := (hd (iter N tl x)) (eval iter on fixed N).
```

**Comment by proux01** [comment]
FWIW It's probably already possible to get something like `(fun x => hd (tl ... (tl x)) x` using number notations.

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coq/ssreflect-maintainers this is finally ready (windows failure in CI is unrelated)

**Comment by ppedrot** [comment]
Let's explicitly ping @gares, I think this is an important foundational PR.

**Comment by ppedrot** [comment]
Ping @gares for assignee again, the sooner this is merged the better I think.

**Comment by proux01** [comment]
This s mostly a three lines PR, it shouldn't take much time to look at.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
This seems to be a breaking change, why no changelog?

**Comment by proux01** [comment]
Indeed, here it is https://github.com/coq/coq/pull/18798

**Pull request merged**
