### PR TITLE
Less init plugins

### PR DESCRIPTION
**Pull request by letouzey**
After a discussion with @ejgallego at the implementors meeting, I think we should reduce the amount of plugins that are loaded initially when coqtop launchs. With this PR:
- the extraction isn't available until a Require Extraction (or Coq.extraction.Extraction)
- the declarative mode (a.k.a math-mode) isn't available until a Require DeclarativeMode (or Coq.decl_mode.DeclarativeMode)
- Function (and related stuff such as Functional Scheme, functional induction / inversion) isn't available until a Require Import FunInd (or Coq.funind.FunInd). Note the "Import" here to be sure that the tactics functional induction and inversion  are in scope.

The primary motivation of this PR is to help jsCoq by avoiding a mandatory load of the three biggest plugins. This could also helps regular coqtop (not measured yet): these three plugins are major components of Coq, especially the first one ;-), but rather peripherical, and far from used in all Coq files. Moreover, at least in the case of the extraction, this could also ease the development of autonomous and/or alternative versions of these plugins (via opam packages, probably). 

The last plugins that are initially loaded are Cc and Ground, providing respectively the congruence and firstorder tactics. We checked with @ejgallego, they're far smaller than the others, and these tactics are quite mainstream (at the point we could probably migrate them to the tactics/ and ltac/ directories, but that's another story).

Concretely, the impact on the user is a few extra Require in their files. The second commit of this PR is designed to make this transition as smooth as possible: when the user tries a "Extraction foo" on a fresh coqtop, it should normally get now a "Illegal begin of vernac" error, but the error message is now "Please do first a Require Extraction". Same for the two other concerned plugins. This is obtained by (temporary) hacks in g_vernac and g_tactics: declaration of some bogus grammar entries, for instance for IDENT "Extraction".

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks Pierre!

**Comment by maximedenes** [comment]
Do you want this in 8.6?

**Comment by ejgallego** [comment]
I don't have a strong opinion, the change is really small and bring a bit of start up time improvement.

**Comment by maximedenes** [comment]
@letouzey WDYT?

**Comment by maximedenes** [comment]
I haven't heard opposition to the integration of this change to 8.6, so let's tag it.

**Comment by maximedenes** [comment]
Shouldn't the recommended Requires be "From Coq Require (Import) XXX"? It would be more robust to later changes to the logical paths layout (or capitalization changes).

**Comment by maximedenes** [comment]
After discussing with Matthieu, we agreed that while we like this patch, it would be better to discuss it and get some feedback from users. So let's postpone it, since the merge window has been closed for a while now, and we need to converge on a stable 8.6.

**Comment by maximedenes** [comment]
I merged with trunk and run a test build here: https://travis-ci.org/maximedenes/coq/builds/208794473

The failures seem to be the expected ones.

Two suggestions:
- "Please do first a Require Import XX" sounds a bit weird to my ears. Shouldn't we write something like "Please first do a Require Import XX"? Any native speaker? (I would avoid to put "first" at the end of the sentence if possible to avoid confusion with module names).
- Shouldn't the message suggest to add a `From Coq Require Import XX` instead? It seems more robust.

I can make those changes if everyone agrees.

**Comment by gares** [comment]
I'd suggest something along the lines: "Please add `from X require Y` to file a.v in order to make command Z work".

**Comment by maximedenes** [comment]
I hadn't realized that we're asking here our users to make a non-backward compatible change in their scripts: the file `FunInd.v` did not exist previously. Couldn't we reuse the existing `Recdef.v` instead? The plugin is also named `recdef_plugin`.

**Comment by letouzey** [comment]
We could indeed reuse the existing `Recdef.v` and put the `Declare ML Module` in it. But note that's also an incompatible change, since this Recdef is currently required only for doing well-founded Function, but not for a structural Function or Functional Scheme. See for instance theories/FMaps for my use of Functional Scheme without the need for Recdef. Anyway, the content of Recdef seems innocuous enough for us to impose it to be required each time Function / Functional Scheme / etc is desired. At first, I was also afraid that the "Recdef" name wasn't enough related with the commands it will enable (Function, ...),  but since Recdef is already there and is related to these commands anyway, it might not be such a problem, but rather a clarification.

Now, concerning the "From Coq" debate, I'm against mentioning that in our messages. These messages should be short and provide the most convenient way to adapt to this change for the average user.

**Comment by Zimmi48** [comment]
> We could indeed reuse the existing Recdef.v and put the Declare ML Module in it. But note that's also an incompatible change

Breaking change but not incompatible change if there exists a solution that will work in both versions (in this case by requiring `Recdef`).

**Comment by maximedenes** [comment]
> Now, concerning the "From Coq" debate, I'm against mentioning that in our messages. These messages should be short and provide the most convenient way to adapt to this change for the average user.

Oh! I'm surprised by that. Advertising robust ways of fixing problems will likely spare ourselves some pain later, don't you think? In fact, I see that even in the stdlib you did you fully qualified names (which is more verbose and probably slightly less robust than `From Coq` if we reorganize the directory structure of a plugin).

**Comment by ejgallego** [comment]
> Now, concerning the "From Coq" debate, I'm against mentioning that in our messages. These messages should be short and provide the most convenient way to adapt to this change for the average user.

It doesn't seem like a big deal, will that bother the user?

I think there has been some informal recommendation for some time to prepend `From Coq` to includes from the stdlib. Indeed, there are collisions in the real world, and they are problematic for distributions such as jsCoq that try to distribute many libraries.

**Comment by maximedenes** [comment]
I can prepare patches for upstream devs that we test, and merge this PR, if @letouzey is ok with `From Coq`.

**Comment by maximedenes** [comment]
Ok, a branch using `Recdef` instead of `FunInd` for better compatibility is being tested here: https://travis-ci.org/maximedenes/coq/builds/214053500

The next step is to submit patches upstream. Note that in the case of extraction, those fixes cannot be made backward-compatible (no `Extraction.v` existed in 8.6).

As for the `From Coq` "controversy", I'll make a separate PR improving the error message so that discussion can happen without blocking this PR.

**Comment by ejgallego** [comment]
> those fixes cannot be made backward-compatible (no Extraction.v existed in 8.6).

That's really inconvenient, couldn't we add the requires files to 8.6.1 ?

**Comment by maximedenes** [comment]
Sure, I'll do that as well, but will stay incompatible with 8.6.0.

**Comment by ejgallego** [comment]
> Sure, I'll do that as well, but it will stay incompatible with 8.6.0.

That's still way better than 8.7 for some users, I am thinking of Compcert and SF, for example.

**Comment by maximedenes** [comment]
Ouch! `Recdef.v` defines a function called `max`. So much for compatibility... So I guess I'll revert my commit, and will introduce two empty files in the 8.6 branch (for extraction and funind).

**Comment by maximedenes** [comment]
8.6 with empty files being tested here: https://travis-ci.org/maximedenes/coq/builds/214067410

**Comment by ejgallego** [comment]
In fact I think using the `From Coq Import` should be mandatory. Now, we are introducing new modules in the namespace, and the only way to be sure they don't clash it that one. In fact, `CompCert` has an `extraction.v` module, so that is close...

**Comment by letouzey** [comment]
Hum. What is this business of introducing extra `.v` files in minor releases such as  8.6.1 ? Looks to me as *precisely* what we do not want to do in minor releases, since that's clearly not a bugfix. \me confused...

**Comment by maximedenes** [comment]
As explained above, the problem if we don't add these files is that users cannot fix their script in a way that works with 8.6 and 8.7. We did the same thing when moving Ltac to a plugin, for instance.

**Comment by letouzey** [comment]
Ok, got it now

**Comment by ejgallego** [comment]
@letouzey indeed that stuff is not pretty, but we are out of a better idea so people don't have two maintain a gazillion branches.

**Comment by maximedenes** [comment]
I'm starting to think that the smoothest way to make the transition to integrate this PR would be to release Coq 8.6.1 (the timing seems good in terms of bug fixing anyway).

**Comment by maximedenes** [comment]
@letouzey Could you rebase this PR so that we merge it? Thanks!

**Comment by letouzey** [comment]
Rebased over today's trunk (and expunged from any mention of declarative_mode)

**Comment by Zimmi48** [comment]
@letouzey I think you forgot to force-push.

**Comment by letouzey** [comment]
Oups, really push the rebased version to the right place this time :-)

**Comment by letouzey** [comment]
Re-oups, a fix of `plugins/micromega/MExtraction.v` was missing, should be there now...

**Comment by Zimmi48** [comment]
This PR adds a lot of `Require Coq.extraction.Extraction` to files which already contain unqualified imports. This distinction looks a bit strange (as if there was a reason for using a fully qualified module name in one case and a short module name in the other case).

**Comment by letouzey** [comment]
Added a missing Require in `bugs/closed/5372.v`, this should fix the test-suite

**Comment by letouzey** [comment]
Damn, something is quite wrong here.
```
Require Import Recdef.
Lemma test : True.
functional induction foo.
```
leads to `Anomaly "Uncaught exception Invalid_argument("Lexer: location function")."`
While this is ok:
```
Require Import FunInd Recdef.
Lemma test : True.
functional induction foo.
```
This ends up with an error on foo being unknown, as expected.
Same if we directly do some  `Declare ML Module`.
Very ackward, since Recdef requires FunInd...
To be investigated tomorrow.

**Comment by ejgallego** [comment]
Pierre, what's the backtrace like?

**Comment by ejgallego** [comment]
Ok, I got it myself:

```
value parse_parsable entry p = do {
  let efun = entry.estart 0 in
  let ts = p.pa_tok_strm in
  let cs = p.pa_chr_strm in
  let fun_loc = p.pa_loc_func in
  let restore =
    let old_floc = floc.val in
    let old_tc = token_count.val in
    fun () -> do {
      floc.val := old_floc;
      token_count.val := old_tc;
    }
  in
  let get_loc () =
    try
      let cnt = Stream.count ts in
      (* Exact point of the error *)
      let loc = fun_loc cnt in
      if token_count.val - 1 <= cnt then loc
      else Ploc.encl loc (fun_loc (token_count.val - 1))
    with
    [ Failure _ -> Ploc.make_unlined (Stream.count cs, Stream.count cs + 1) ]
  in
  floc.val := fun_loc;
  token_count.val := 0;
  try do {
    let r = efun ts in
    restore ();
    r
  }
  with
  [ Stream.Failure -> do {
      let loc = get_loc () in
      restore ();
      Ploc.raise loc (Stream.Error ("illegal begin of " ^ entry.ename))
    }
  | Stream.Error _ as exc -> do {
      (* This is the wrong call leading to the exn *)
      let loc = get_loc () in
      restore ();
      Ploc.raise loc exc
    }
```

**Comment by ejgallego** [comment]
So changing `Recdef.v` to do:

```
Require Export Coq.funind.FunInd.
```

seems to solve the problem. It thus seems some module scoping problem.

**Comment by ejgallego** [comment]
That is the diff between the module trace in the bad case and the good case (with `Export`):
```
--- m1.txt	2017-06-07 02:20:46.765726940 +0200
+++ m2.txt	2017-06-07 02:21:00.913018789 +0200
@@ -18343,6 +18343,10 @@
 [obj: IMPLICITS] => {op loader}
 [obj: HEAD] => {op loader}
 [obj: ARGUMENTS-SCOPE] => {op loader}
+[obj: ML-MODULE] => {op opener}
+[obj: TacticGrammar] => {op opener}
+[obj: TacticGrammar] => {op opener}
+[obj: TacticGrammar] => {op opener}
 [obj: CONSTANT] => {op opener}
 [obj: IMPLICITS] => {op opener}
 [obj: HEAD] => {op opener}
@@ -18386,8 +18390,6 @@
 [obj: IMPLICITS] => {op opener}
 [obj: HEAD] => {op opener}
 [obj: ARGUMENTS-SCOPE] => {op opener}

```

**Comment by ejgallego** [comment]
This looks like a bug thou, right?

**Comment by maximedenes** [comment]
So, what should be done for this PR? @letouzey @ejgallego

**Comment by ejgallego** [comment]
The solution to the above problem is clear `RecDev` should export `FunInd` as to properly have the grammar registered. [I was referring to that to be a bug in Coq itself].

As for the other problems I don't know, it seems to me that it shouldn't be too much of a problem.

**Comment by letouzey** [comment]
@ejgallego : thanks for your help on this issue.
@maximedenes  : ok for an `Export` in `Recdef.v` as workaround for this PR, I'm doing that now.
But the underlying behavior of Coq looks a lot like a bug, to be investigated separately.

**Comment by ejgallego** [comment]
Well after a few minutes more of thinking I think it is _not strictly a bug_ but a "feature" of Coq, in the sense that the plugin writer is required to do manual management of these kind of dependencies.

Almost in all the system you could question the semantics of require vs import, and indeed, it is a bit strange that the libobject API allows for such arbitrary control vs a more systematic control of the exported structures, but yeah, we will have to live with that on the medium term.

**Comment by letouzey** [comment]
Weird. Travis currently fails during Coq compilation:
```
File "plugins/ltac/g_tactic.ml4", line 209, characters 10-31:
Error: Unbound value Mltop.module_is_known
```
But I do not have this error here, everything compiles fine, even after a git clean.
Something related with the API PR#652 ??

**Comment by Zimmi48** [comment]
Indeed @letouzey I was able to reproduce this error on my machine by merging trunk into your branch.
The issue should be indeed that the API doesn't export `Mltop.module_is_known` (but Coq plugins need to go through the API). However, I tried just adding the signature of `module_is_known` to the `Mltop` module in the `API.mli` file but this did not fix the problem. Maybe @matejkosik can help here.

PS: @letouzey add a separating space between PR and #something. It allows GitHub to parse the #-part and insert a link automatically (even in commit messages).

**Comment by matejkosik** [comment]
... I am going to have a look ...

**Comment by Zimmi48** [comment]
OK I understood the issue: I was adding the signature to `API.mli` when it should have been added to `grammar_API.mli`. @matejkosik: Does it make sense that there is a `Mltop` module both in `API.mli` and `grammar_API.mli`?!

Here is a patch that fixes this error:
```
diff --git a/API/grammar_API.mli b/API/grammar_API.mli
index 44aae771f..e750c0369 100644
--- a/API/grammar_API.mli
+++ b/API/grammar_API.mli
@@ -212,6 +212,7 @@ module Mltop :
 sig
   val add_known_module : string -> unit
   val declare_cache_obj : (unit -> unit) -> string -> unit
+  val module_is_known : string -> bool
 end
 module Vernacinterp :
 sig
```

**Comment by matejkosik** [comment]
@Zimmi48 Probably yes. Those items of `Mltop` that are useful for plugin writers, should go to `API.Mltop`. Those items that are needed only because of macro expansions, should go to `Grammar_API.Mltop`. 

Although I see that `declare_cache_obj` appears both in `API.Mltop` as well as in `Grammar_API.Mltop`. That's a mistake. We should decide which one we want to keep and drop the other one.

**Comment by Zimmi48** [comment]
@matejkosik The issue AFAIU with having this module in both places is that one will shadow the other. That's why adding `module_is_known` to `Mltop` in `API.mli` did not fix the problem initially.

**Comment by Zimmi48** [comment]
@letouzey FTR, with the merge of trunk, this is not the last error. The second and last one is due to poor interaction with #515:
```
make[1] : on entre dans le répertoire « /home/theo/coq-pr-220 »
OCAMLDEP  plugins/micromega/micromega.mli
OCAMLDEP  plugins/micromega/micromega.ml
MD5SUM cic.mli
OCAMLC -o bin/coqide.byte
Fatal error: exception Failure("input_value: bad object")
make[1]: *** [Makefile.ide:94: bin/coqide.byte] Error 2
```
Now, since there were talks of reverting this PR, I didn't look for a real fix. Reverting this PR indeed allows the compilation to go through.

**Comment by matejkosik** [comment]
@Zimmi48  If this becomes a pain, we can add `include API.Mltop` inside the signature of `Grammar_API.Mltop`. Technically, that's possible but I wasn't sure whether it is necessary / good thing to do.

**Comment by ejgallego** [comment]
> Those items of Mltop that are useful for plugin writers, should go to API.Mltop. Those items that are needed only because of macro expansions (but plugin writers are not supposed to touch them explicitely), should go to Grammar_API.Mltop.

Well I am not 100% sure but I think there are parts of the API that simultaneously fall in these two categories, thus raising a question on this approach, @ppedrot ?

**Comment by letouzey** [comment]
Right, I got mislead by the "no conflict" green light at the bottom of the PR page ... which is far from indicating that things compile ok after a rebase :-(.

I just puhed a rebased version with `Mltop.is_known_module` added both in `API.mli` and `grammar_API.mli`.

@Zimmi48 : I cannot reproduce the second issue you mention (the one about PR #515).

**Comment by Zimmi48** [comment]
@letouzey I don't see this error anymore either. It's possible that it is due to the different results of merging trunk into this branch vs rebasing this branch on top of trunk.

**Comment by ejgallego** [comment]
Still getting anomalies in a couple of contribs.

**Comment by letouzey** [comment]
The anomalies were actually caused by the hack in `g_tactics.ml4` (the one trying to customize the error messages of ̀`functional induction` and `functional inversion` when recdef isn't loaded yet). So here comes a version without this hack (but still with the hacks of `g_vernac.ml4`).

**Comment by herbelin** [comment]
Note: the overlays coming with this PR rely on a version of sed which does not work on MacOS. A possible fix for the life span of the overlay is of the form (in `/dev/ci/ci-color.sh`):

`sed -i".bak" -e '15i\'$'\n''From Coq Require Import FunInd.'$'\n' ${Color_CI_DIR}/Coccinelle/basis/ordered_set.v`

**Comment by ejgallego** [comment]
I suggest we sent the patches to CoLoR's maintainer, he will gladly merge them AFAICT.

**Comment by herbelin** [comment]
Hi, I checked the portability of contribs wrt the PR and this worked very well: The `Require Extraction` and `Require Import FunInd` recommended insertions were very useful to help for the transition. Note one case not associated to a message though, it is when using `functional induction`.

**Comment by letouzey** [comment]
@herbelin : I originally tried to have customized error messages for `functional induction`, but unlike with vernac, hacking into `g_tactic.ml4` was creating havoc (see comments above about an anomaly). So I removed these hacks.

**Comment by Zimmi48** [comment]
There was a complaint of @xavierleroy about this PR:

> > Note also that the FunInd.v file was introduced at the time of the PR in 8.7 and also in 8.6.1 for backward compatibility, but compatibility with 8.6(.0) is not maintained.
>
> This is not nice. It would have been more professional to introduce FunInd.v, wait one full 8.7 release cycle, then make FunInd.v mandatory in Coq 8.8. I mean, it's not like this change is fixing a serious bug in Coq, it's just twiddling with stuff that already worked.

Given that 8.7.0 is not released yet (even 8.7beta1 isn't), we can still partially revert this PR in v8.7 (keeping it as-is only in master), if the Coq developers wish.

I'm raising this question (and not taking any side). Discussion should happen quickly though if we want to take action before the beta release (expected at about the time when @mattam82 comes back from vacation).

**Comment by letouzey** [comment]
Could I remind that the "fix" of Compcert is a one-liner (an added `Require` in the first file of Compcert) ? How many lines of comments already written for such a minor matter ? I obviously prefer this PR to stay in 8.7, the sooner we close this story the better (it was initially meant for 8.6). Anyway, I'm quite fed up with this, do what you want with it.

**Comment by Zimmi48** [comment]
> do what you want with it

If this is addressed to me, I won't do anything. I only raised the question because I felt I had to given the complaint of Xavier. I'm quite happy with things the way they are.

**Comment by ejgallego** [comment]
Well the complaint indeed has some merit in the sense that the process to introduce such changes should be a bit more polished, with the 6-months cycle, deprecation becomes much easier, but indeed this change was targetted to the old model where releases _used_ to badly break things.

**Comment by maximedenes** [comment]
> Could I remind that the "fix" of Compcert is a one-liner

Yes, but @xavierleroy's point is that he can't make CompCert compatible with 8.6 and 8.7.

Anyway, I think it is too late to take any action, we'll try to do better next time.

**Pull request merged**
