### PR TITLE
[CoqIDE] Display warnings in their own tab.

### PR DESCRIPTION
**Pull request by ppedrot**
Follow-up of #19188. It was annoyingly confusing to get the warnings in the error tab, as it seemed to indicate that the file was not properly compiling.

### CODE REVIEW

**Comment by ppedrot** [comment]
I also realized *en passant* that the location for the warning line is wrong, but this is already the case on master.

**Comment by proux01** [comment]
@jfehrle would you please assign this

**Comment by jfehrle** [comment]
> I also realized en passant that the location for the warning line is wrong, but this is already the case on master.

Yeah, I've thought about how to fix that.  It would be pretty simple if the table data model supported hidden columns (e.g. containing the sentence id), but it appeared that wasn't possible with GTK.

**Comment by jfehrle** [comment]
Rather than adding a new panel for warnings, how about this?
- only show the red highlight on "Errors" if there are errors
- if there are warnings but no errors, highlight "Errors" in blue

We could also add a column to show E or W to distinguish errors and warnings.  If I make that a sortable column it's easy for the user to ignore warnings.  And probably should make the message column sortable, too, so you can fix specific repeated errors all at once.

WDYT?

**Comment by ppedrot** [comment]
I'd still prefer to have a separate list, it's annoying to have to order columns to sort out things that are important (errors) from things that are mostly noise (warnings). Note that vscoq also has separate panes, but they are selectable through a drop-down list.

**Review by SkySkimmer — APPROVED** [review]
This is already an improvement.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
