### PR TITLE
Mention label name in signature mismatch error when constant expected

### LINKED ISSUE #13987: Error message about module parameters instantiated by inductives doesn't say which parameter is causing trouble
#### Description of the problem

```
Module Type S. Parameter A: Type. End S.
Module I : S. Inductive A :=. End I.
```

```
Error:
The kernel does not recognize yet that a parameter can be instantiated by an inductive type. Hint: you can rename the inductive type and give a definition to map the old name to the new name.
```
This error message is fine for a small signature, but with large signatures it gets tricky to know where the problem comes from.  It would be much better if Coq explicitly mentioned `A` instead.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13987

### CODE REVIEW

**Comment by herbelin** [comment]
After so many years, maybe indeed wise to renounce to the `yet` in the message.

**Review by ppedrot — COMMENTED** [review]
The new message is a bit terse. Maybe you can add an argument to the `DefinitionFieldExpected` for this situation, so that it prints a variant of the helpful message that was there before?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Merging soon.

**Comment by ppedrot** [comment]
CI failures unrelated, let's merge.

**Pull request merged**
