### PR TITLE
[mltop] Deprecate -load-ml options in anticipation of #11409

### PR DESCRIPTION
**Pull request by ejgallego**
**Kind:** documentation / deprecatio.

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
The changelog is probably missing a newline.

Also, I don't want to mark this as a blocker, but @gares this needs to get in ASAP not to delay any further the 8.11 release.

**Comment by gares** [comment]
It looks OK to me, but CI has exploded...

**Review by gares — APPROVED** [review]
merge it when you like PMP

**Comment by ppedrot** [comment]
Most CI failures are due to missing overlays for #11368.

**Comment by ppedrot** [comment]
Let's merge regardless of CI, failures are unrelated now that the newline issue has been fixed.

**Pull request merged**
