### PR TITLE
Stupid but critical unfolding heuristic.

### PR DESCRIPTION
**Pull request by ppedrot**
We favour unfolding of variables over constants because it is more frequent for the former to depend on the latter. This has huge consequences on a few extremely slow lines in mathcomp, up to dividing by 3 single-line invocations that were taking about 30s on my laptop before the patch.

```
┌──────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                          │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                          │                         │                                       │                                       │                         │                   │
│             package_name │     NEW     OLD PDIFF   │            NEW            OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │  NEW  OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│       coq-mathcomp-field │  451.52  470.17 -3.97 % │  1256043920785  1307499881942 -3.94 % │  2039642380866  2125985727874 -4.06 % │  799080  805436 -0.79 % │    0   23 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│ coq-mathcomp-real-closed │  181.46  188.46 -3.71 % │   504892234076   524215868132 -3.69 % │   757711653396   790457635832 -4.14 % │  834296  828084 +0.75 % │    8    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│              coq-unimath │ 1325.43 1336.12 -0.80 % │  3681679259332  3708538536896 -0.72 % │  6179317614400  6222320894210 -0.69 % │  986772  985524 +0.13 % │  356   21 +1595.24 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│    coq-mathcomp-solvable │  219.08  220.25 -0.53 % │   608797537680   611189014049 -0.39 % │   867625487689   873007484061 -0.62 % │  819324  857276 -4.43 % │    0  253 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│         coq-fiat-parsers │  720.67  722.96 -0.32 % │  2000208918420  2004623043606 -0.22 % │  3058299308839  3058326911836 -0.00 % │ 2902324 2900992 +0.05 % │  144  488 -70.49 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│              coq-bignums │   98.71   99.02 -0.31 % │   273072599990   273677176889 -0.22 % │   392925460275   393691214873 -0.19 % │  536264  536424 -0.03 % │   14    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│               coq-sf-plf │   74.56   74.79 -0.31 % │   206312768406   206681404110 -0.18 % │   300628456391   300793941880 -0.06 % │  517772  518080 -0.06 % │   15    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│            coq-fiat-core │  135.30  135.71 -0.30 % │   376717172228   377099349882 -0.10 % │   503947956067   503947945028 +0.00 % │  497972  497584 +0.08 % │  301  169 +78.11 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│          coq-fiat-crypto │ 6309.56 6325.22 -0.25 % │ 17541473517561 17591620619420 -0.29 % │ 28886741757670 28949118285129 -0.22 % │ 2527464 2442976 +3.46 % │ 1429 1604 -10.91 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│     coq-mathcomp-algebra │  205.52  205.79 -0.13 % │   570756493375   570824541479 -0.01 % │   797968129879   798592485059 -0.08 % │  641780  640908 +0.14 % │   13    6 +116.67 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                 coq-corn │ 1549.43 1550.91 -0.10 % │  4299177955994  4304767005454 -0.13 % │  6351031458314  6345679761648 +0.08 % │  818156  818080 +0.01 % │   44   44 +0.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│               coq-geocoq │ 2835.56 2837.44 -0.07 % │  7883254537381  7887266939714 -0.05 % │ 12581310463650 12580378357181 +0.01 % │ 1289188 1285740 +0.27 % │  321  178 +80.34 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│   coq-mathcomp-odd-order │ 1431.87 1432.56 -0.05 % │  3988503267711  3989436346228 -0.02 % │  6650430717672  6654458068276 -0.06 % │ 1364656 1360124 +0.33 % │    0    2 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                 coq-hott │  342.14  342.28 -0.04 % │   948452221439   947717140665 +0.08 % │  1439699491374  1439423119663 +0.02 % │  666944  666992 -0.01 % │  382    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                  coq-vst │ 1714.00 1714.29 -0.02 % │  4764986261802  4765835678370 -0.02 % │  6523473751238  6526214668298 -0.04 % │ 2227400 2226844 +0.02 % │  282  286 -1.40 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-gpfsl │ 1202.25 1202.20 +0.00 % │  3348424834354  3350145488560 -0.05 % │  4403586425502  4406497294245 -0.07 % │ 1620244 1587020 +2.09 % │   64    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│   coq-mathcomp-ssreflect │   65.58   65.55 +0.05 % │   180634941007   180188270946 +0.25 % │   256343795744   256383543912 -0.02 % │  532196  532240 -0.01 % │    2    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│         coq-math-classes │  249.97  249.78 +0.08 % │   687772203013   687852583176 -0.01 % │   898725881448   898785908738 -0.01 % │  521896  521744 +0.03 % │   84   84 +0.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│    coq-mathcomp-fingroup │   85.04   84.97 +0.08 % │   234731017390   234785733709 -0.02 % │   348232320594   348351868361 -0.03 % │  588272  587564 +0.12 % │  156    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-color │  736.73  735.84 +0.12 % │  2041003298859  2040706082908 +0.01 % │  2469055547704  2468533084188 +0.02 % │ 1370684 1429024 -4.08 % │   29  125 -76.80 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│               coq-sf-vfa │   47.51   47.42 +0.19 % │   131258414117   131337549759 -0.06 % │   209539052188   209723174423 -0.09 % │  535660  535548 +0.02 % │   28    5 +460.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-flocq │  594.14  592.81 +0.22 % │  1653379570180  1650326873739 +0.18 % │  2412867943085  2414747976836 -0.08 % │ 1764196 1764464 -0.02 % │  304   72 +322.22 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│             coq-compcert │  892.66  890.48 +0.24 % │  2474398884437  2469212143007 +0.21 % │  3563190637748  3563333486762 -0.00 % │ 1355244 1355808 -0.04 % │  173  200 -13.50 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│      coq-formal-topology │   57.97   57.82 +0.26 % │   158704356032   158734343611 -0.02 % │   239295939520   239343068057 -0.02 % │  477660  477608 +0.01 % │    0    0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│   coq-mathcomp-character │  294.20  293.39 +0.28 % │   817703227889   815703662517 +0.25 % │  1188165014136  1185265372027 +0.24 % │ 1110704 1060032 +4.78 % │    5    2 +150.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│           coq-coquelicot │  103.74  103.42 +0.31 % │   286843510132   286677435187 +0.06 % │   386118985227   386218345638 -0.03 % │  712688  714148 -0.20 % │  279   13 +2046.15 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-sf-lf │   44.62   44.39 +0.52 % │   122205285805   122358099952 -0.12 % │   198837633045   198990048150 -0.08 % │  423104  423264 -0.04 % │  128    0  +nan % │
└──────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

### CODE REVIEW

**Review by maximedenes — DISMISSED** [review]
You forgot to update the checker.

**Comment by ppedrot** [comment]
That was on purpose, actually. I thought that the less complex the heuristics the safer.

**Comment by maximedenes** [comment]
> That was on purpose, actually. I thought that the less complex the heuristics the safer.

I don't see why. What could go wrong with this heuristics in terms of soundness?!

**Comment by gares** [comment]
If the checker is going to vanish, what is the point of updating it?

The question I'd like an answer to is: how did you find out? The speedup is huge, and the logic behind the optimization is understandable. I'm almost crying ;-)

**Comment by maximedenes** [comment]
> If the checker is going to vanish, what is the point of updating it?

Well, we don't really want the checker to vanish, we want to factorize its code with the kernel, as much as possible. How much I'll manage to factorize is still an open question, so meanwhile, I think it makes sense to try to control the divergence.

> The question I'd like an answer to is: how did you find out? The speedup is huge, and the logic behind the optimization is understandable. I'm almost crying ;-)

Yes, this is very nice! It would be interesting to hear about how came the idea of this improvement (and if similar ones are still possible).

**Comment by ppedrot** [comment]
> Yes, this is very nice! It would be interesting to hear about how came the idea of this improvement (and if similar ones are still possible).

I was profiling the slowest diffs of @SkySkimmer's [Sprop branch](https://github.com/coq/ceps/pull/37), and came upon what looked like extremely slow conversions that were made worse by this branch. Had a deeper look and realized that the conversion was stupid.

(The unofficial reason is that I badly want Sprop to land, and negating the slowdowns that it introduces by unrelated optimizations makes it easier for people to accept this. You know the drill.)

Also, I am currently trying to devise some even better heuristic based on the dependency between constants, but I don't know yet how to do it efficiently. The idea is that if a constant transitively contains another one, it is more likely that unfolding the former before the latter is going to lead to a shorter conversion route.

**Comment by ppedrot** [comment]
> It does not work fell for ho stuff, since the head means little (eg fold or any projection)

Yes, I was aware of that, but I don't know the ratio between HO/FO conversion in typical code. I'd intuitively think that FO conversion is more frequent.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
