### PR TITLE
Revert another part of a477dc in good measure

### PR DESCRIPTION
**Pull request by mattam82**
We now fail on non-class subgoals at toplevel as in 8.5, instead of the
previous a477dc behavior of shelving them and failing if shelved goals
remained. It means typeclass resolution during refinement is closer to
all:[> try typeclasses eauto].

### CODE REVIEW

**Comment by mattam82** [comment]
Success here: https://ci.inria.fr/coq/view/coq-contribs/job/coq-contribs/596/console

**Comment by JasonGross** [comment]
Note that 8.5 did not fail on non-class subgoals.  This code worked:
```coq
Hint Resolve I : typeclass_instances.
Goal True.  typeclasses eauto. Qed.
```
Is this change intentional?

**Comment by mattam82** [comment]
Being discussed on coq-club right now :) We'll revert it I think.

**Comment by mattam82** [comment]
The commit message says it all:

We stop failing automatically on non-declared-class nested or toplevel
subgoals as in 8.5, instead of the previous a477dc behavior of shelving
those goals and failing if shelved goals remained at the end of
resolution. It means typeclass resolution during refinement is closer to
all:typeclasses eauto. Hints in typeclass_instances for non-declared
classes can be used during resolution of _nested_ subgoals when it is
fired from type-inference, toplevel goals considered in this case are
still only classes (as in 8.5 and before). The code that triggers the
restriction to only declared class subgoals is commented.

Revert changes to test-suite, adding test for #5203, #5198 is fixed too.

Add corresponding tests in the test-suite (that will break if we,
e.g. disallow non-class subgoals) and update the refman accordingly.

**Comment by maximedenes** [comment]
https://ci.inria.fr/coq/view/coq-contribs/job/coq-contribs/597/console

**Pull request merged**
