### PR TITLE
Fix #10842: incorrect handling of unicode input before space

### LINKED ISSUE #10842: Latex to unicode does not work in CoqIDE 8.10+beta3
#### Description of the problem
Pressing shift+space or invoking the command from the menu only inserts a space and does not convert the Latex, such as \pi, to unicode.

#### Coq Version
8.10+beta3, Ubuntu 19.04.

### PR DESCRIPTION
**Pull request by charguer**
Fixes #10842.

This bug fix removes a useless optimization that had introduced a bug.

### CODE REVIEW

**Comment by ppedrot** [comment]
Can somebody confirm it does fix the bug? @julesjacobs or @Zimmi48?

**Comment by Zimmi48** [comment]
Despite being clearly completely unrelated to this PR, the failed test is very strange:

```
File "./bugs/opened/bug_3345.v", line 1, characters 15-30:
Error: Unable to locate library TestSuite.admit.
```

Has anyone seen this before? Was it an issue on master at the time the PR was opened?

**Review by Zimmi48 — APPROVED** [review]
I do confirm that this fixes the bug.

**Comment by ppedrot** [comment]
Failure cannot be related, I'll merge this anyways.

**Review by ppedrot — APPROVED** [review]

**Comment by julesjacobs** [comment]
Great! Thanks so much.

**Pull request merged**
