### PR TITLE
dune-project: memtrace is a depopt

### LINKED ISSUE #19103: Optional memtrace dependency is not made visible to OPAM
### Description of the problem

Installing `memtrace` and `coq` at the same time via `opam` can lead to coq being compiled without memtrace support. This can be fixed by re-installing coq afterwards but that is less than ideal. I don't know anything about opam but the manual mentions a `depopts` field that can probably be used to fix this. (I hope `opam` is smart enough to schedule the compilation of `coq-core` after that of `memtrace` if coq optionally depends on it.)

### Small Coq file to reproduce the bug

_No response_

### Version of Coq where this bug occurs

_No response_

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #19103

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
How are the opam files in opam-repository updated? Do we need to make a note of this for the release process?

**Comment by Alizter** [comment]
@coqbot run full CI

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
@SkySkimmer What's the meaning of the 8.17.2 milestone here? Was this PR actually backported anywhere, or was it forgotten because of the automation not being configured for this milestone (as discussed in https://github.com/coq/coq/pull/18513#issuecomment-2172519531 and on Zulip)?

**Comment by SkySkimmer** [comment]
I guess it was not backported

**Pull request merged**
