### PR TITLE
[zify] several efficiency enhancements

### PR DESCRIPTION
**Pull request by fajb**
- zify_iter_specs is entirely in OCaml
- zify_op has been improved
  * The generation of proof-terms is more direct
  * It does not `rewrite` but instead either performs
    a `pose proof` or a `change`
  * The support for `and`, `or`, `not`, arrow is hardcoded
- zify_elim_let is entirely in OCaml (no Ltac callback)

### CODE REVIEW

**Comment by fajb** [comment]
The optimisations are not completely backward compatible:
1. There are less intermediate equations
2. Section Hypotheses are eagerly transformed -- they used to generate evars that were garbage collected if useless. 
As far as I can tell, the failures are related to either 1) or 2).

The failures of the CI:
- `flocq`: this is due to 2) and this is solved clearing explicitly the hypothesis.
- `vst`: this is due to 1) and this would be solved by upgrading CompCert
- `fiat-crypto`:   to be investigated...

**Comment by fajb** [comment]
I made some progress:
PR https://gitlab.inria.fr/flocq/flocq/merge_requests/10 should solve the  flocq issue
PR https://github.com/mit-plv/fiat-crypto/pull/646 should solve the fiat-crypto issue

**Comment by JasonGross** [comment]
Fiat-Crypto PR merged

**Comment by fajb** [comment]
@vbgl could you run a bench ? Thanks again!
I am relatively confident but anyway...

**Comment by vbgl** [comment]
Sure. May you rebase?

**Comment by fajb** [comment]
I've just done it and hit the infamous "job activity limit exceeded".

**Comment by vbgl** [comment]
https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/847/console

**Comment by fajb** [comment]
Thanks @vbgl . Not too bad...

NB: The last commit should change nothing: just clean up of Import and removal of dead code.

**Comment by ejgallego** [comment]
This seems ready right @fajb ? [modulo the rebase]

**Comment by fajb** [comment]
@ejgallego , I hope this is ready. I've just rebased.

**Comment by vbgl** [comment]
Pff still fails. Why hasn’t https://gitlab.inria.fr/flocq/flocq/merge_requests/10 been merged?

Ping @silene.

**Comment by herbelin** [comment]
> Ping @silene.

I saw him last week. You should e-mail him directly I believe.

**Comment by maximedenes** [comment]
> 2\. Section Hypotheses are eagerly transformed -- they used to generate evars that were garbage collected if useless.

@fajb can you explain how this speeds things up? Just to get an idea.

Where the "several enhancements" benchmarked separately?

**Comment by fajb** [comment]
@maximedenes , my benchmark was `coq-prime` using @vbgl  branch where `auto with zarith` is using lia. Each enhancement has a noticeable impact on the `Ltac profile`. Now, I believe this is really the core of `zify` i.e. `zify_op` that is still costly.
I also made the experiment of only running `zify` if `lia` failed without it. For `coq-prime`, this is a winning strategy...

For your specific point:  replacing a `rewrite` by a `pose proof` applying directly the equivalence.
The impact was quite noticeable `coq-prime`, again in the `Ltac Profile`.
 As the rewrite is with a `<->`, some `setoid rewrite` machinery is probably triggered. Here, it seems it is costly.

**Comment by ejgallego** [comment]
> Why hasn’t https://gitlab.inria.fr/flocq/flocq/merge_requests/10 been merged?

If Guillaume is busy we can always pin flocq temporarily; we had to do this a few weeks ago. IMO that's better than holding this up.

**Comment by fajb** [comment]
@ejgallego I got a notification that the Flocq PR has been merged.

**Comment by fajb** [comment]
The failures seem unrelated to the PR.

**Comment by fajb** [comment]
This time. I think this is *really* ready to go.

The last commit piggy-back a bugfix causing a stack-overflow -- thanks @vbgl for the report.
It also avoids to `pose proof`  the same hypothesis twice e.g. `0 <= Z.of_nat x`

**Comment by vbgl** [comment]
Latest benchmark results look good: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/866/console

**Review by vbgl — APPROVED** [review]
It would be nice if the overlay for VST were merged. Thanks.

**Comment by vbgl** [comment]
The overlay for VST has been merged. Thank you Andrew!

Frédéric, may you please rebase and drop the overlay? Thanks.

**Comment by fajb** [comment]
@vbgl rebase done.

**Comment by vbgl** [comment]
I wonder whether the file `test-suite/.csdp.cache` has been added on purpose or by mistake.

**Comment by fajb** [comment]
On Wed, 2020-03-04 at 01:46 -0800, Vincent Laporte wrote:
> I wonder whether the file test-suite/.csdp.cache has been added on
> purpose or by mistake.

I did not remember it was not there.
I think the CI does not have csdp...
Anyhow, it needs to be updated to take into account the zify
modifications.

**Comment by vbgl** [comment]
My bad. Indeed, the file was already there. Sorry for the confusion.

**Pull request merged**
