### PR TITLE
Drop opaque bodies of abstracted definitions.

### PR DESCRIPTION
**Pull request by ppedrot**
This should save us a lot of useless hashconsing. This change should not be observable because outside of the proof, the abstracted definition will be either inlined or redefined with the body coming from the side-effect.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench (https://gitlab.com/coq/coq/-/jobs/709113538):
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  548.93  565.51 -2.93 % │     1533842013743     1580199889160 -2.93 % │     2796903235173     2882489210194 -2.97 % │     747992     751112  -0.42 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4989.52 5082.70 -1.83 % │    13857322187348    14121261400700 -1.87 % │    23904086813481    24362088093095 -1.88 % │    2396980    2393996  +0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  161.31  163.93 -1.60 % │      447816216310      454712551045 -1.52 % │      555937637832      562135023796 -1.10 % │     822100     822524  -0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  609.82  619.39 -1.55 % │     1694059979198     1719871364498 -1.50 % │     2596005619746     2639386562711 -1.64 % │    1035852    1037148  -0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1052.75 1062.93 -0.96 % │     2931568207749     2959003047492 -0.93 % │     4628483962822     4628000730807 +0.01 % │    1070676    1070624  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   69.90   70.28 -0.54 % │      191707036099      192362495549 -0.34 % │      245545188781      245745334320 -0.08 % │     585172     583744  +0.24 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4030.47 4051.61 -0.52 % │    11214507527061    11269988192465 -0.49 % │    21424462431199    21475921394456 -0.24 % │    1124300    1018752 +10.36 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  292.33  293.78 -0.49 % │      814705841951      817862890396 -0.39 % │     1258590834074     1258692464796 -0.01 % │     822704     822404  +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  120.25  120.82 -0.47 % │      332608796351      333785326227 -0.35 % │      413604603427      413620551979 -0.00 % │     554500     554528  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  325.35  326.42 -0.33 % │      883264072443      886669385586 -0.38 % │     1438968514758     1442848772594 -0.27 % │     625880     625916  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   81.20   81.45 -0.31 % │      222723691512      223799492528 -0.48 % │      311385467258      312749893625 -0.44 % │     767888     768072  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1693.69 1698.80 -0.30 % │     4711764304121     4729372853255 -0.37 % │     7254987695898     7258591677483 -0.05 % │     855600     855536  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  190.17  190.52 -0.18 % │      531353698186      532236742290 -0.17 % │      703204315655      703217795226 -0.00 % │     504592     504380  +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  105.52  105.70 -0.17 % │      302684620877      302286288718 +0.13 % │      401982033200      402046790895 -0.02 % │     486432     486580  -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  139.00  139.23 -0.17 % │      387007009584      387156685989 -0.04 % │      500733127317      500716366860 +0.00 % │     565520     558256  +1.30 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1073.04 1074.69 -0.15 % │     2987138931114     2992939864569 -0.19 % │     4780362528204     4780336453733 +0.00 % │    1026600    1027464  -0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1266.68 1268.62 -0.15 % │     3525107060779     3531220546351 -0.17 % │     4929684404367     4930967530294 -0.03 % │     934044     934164  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  652.93  653.81 -0.13 % │     1827749705763     1829749444264 -0.11 % │     2760002077433     2762268343106 -0.08 % │    3000468    3000468  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  173.67  173.85 -0.10 % │      483329540404      483588781349 -0.05 % │      680301165927      680309088907 -0.00 % │     689016     689168  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  669.03  669.46 -0.06 % │     1864385854290     1864351457488 +0.00 % │     2572174215480     2573057651509 -0.03 % │    1130968    1131332  -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1397.65 1398.46 -0.06 % │     3889629528658     3893983775905 -0.11 % │     5532086255715     5531762910592 +0.01 % │    1111920    1170948  -5.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1476.10 1476.79 -0.05 % │     4115825246277     4119869273731 -0.10 % │     6249882226134     6249793002549 +0.00 % │    1142548    1160496  -1.55 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  223.89  223.97 -0.04 % │      620082753636      619721265073 +0.06 % │     1025476098060     1026294116012 -0.08 % │    1087296    1087160  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2503.76 2504.07 -0.01 % │     6981348594115     6982110226000 -0.01 % │    11452085013805    11450627768871 +0.01 % │     771348     771400  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  621.78  621.55 +0.04 % │     1734447758316     1735461210344 -0.06 % │     2206229311972     2206439423186 -0.01 % │    1455932    1455884  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   48.32   48.30 +0.04 % │      134008493923      134225324707 -0.16 % │      184772794735      184746461519 +0.01 % │     485076     485180  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  542.47  542.20 +0.05 % │     1516681879136     1516537992264 +0.01 % │     2070782745559     2071305870403 -0.03 % │     593056     592824  +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  161.43  161.32 +0.07 % │      448968072189      448675774739 +0.07 % │      622125348208      622109491909 +0.00 % │     727756     726188  +0.22 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   58.20   58.16 +0.07 % │      160997306132      161250125853 -0.16 % │      215582660329      216469405948 -0.41 % │     473536     474400  -0.18 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  381.49  381.14 +0.09 % │     1073097276154     1071150390745 +0.18 % │     1836946973638     1838755668016 -0.10 % │    3508300    3508448  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   50.02   49.62 +0.81 % │      136687004118      136691679542 -0.00 % │      174093278533      174071107127 +0.01 % │     519740     517424  +0.45 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   60.50   59.62 +1.48 % │      168102729754      165754314382 +1.42 % │      207924413175      207954018944 -0.01 % │     531552     532920  -0.26 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```
I've seen better.

**Comment by JasonGross** [comment]
This seems to have pretty impressive results on coq-performance-tests-lite (17s) and coq-fiat-crypto (nearly 100s).  Is it distributed across files or is it localized to specific files / lines?

**Comment by ppedrot** [comment]
Looks pretty much distributed. The fiat-crypto speedup is slightly more concentrated in a few calls to make_rewriter, but nothing that outstanding either.

**Comment by JasonGross** [comment]
Hmm, there are a couple of places in coq-performance-tests where we do something like `(time abstract time foo); gfail` in an attempt to measure how long it takes to Qed a proof, maybe the fact that we have expensive terms which are abstracted but completely dropped is giving the speedups?  (Fiat-Crypto doesn't do this, though; all of the abstracted constants in make_rewriter are kept around and the proof ends with `Defined`, IIRC)

**Comment by ppedrot** [comment]
I am marking this as ready for review, since it is a simple patch and the improvements, without being crazy, are observable.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
Note that this PR introduced bug https://github.com/coq/coq/issues/13324

**Comment by ppedrot** [comment]
If anything I'd rather blame coqchk and its incomplete heuristic to decide whether something is an axiom or not. I don't understand why this PR changes anything here, it shouldn't affect the vo up to some hashconsing representation difference?

**Comment by ejgallego** [comment]
Very wild guess, seeing how the status of the code is, maybe the bit "this proof term will be either inlined or reexported" is not true in all cases?

I wouldn't be surprised given the mess we have if that would be the case.

**Pull request merged**
