### PR TITLE
[ssr] Fixing [dup] and [swap] working around a bug

### PR DESCRIPTION
**Pull request by CohenCyril**
**Kind:**  bug fix

This is a workaround for bug #13458

- [x] Added / updated test-suite

- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by gares** [comment]
The test suite is broken

**Comment by CohenCyril** [comment]
@gares repaired?

**Comment by gares** [comment]
Sometimes we reach the threshold of pipelines on gitlab and CI jobs don't start automatically. One has to restart by hand.

**Comment by CohenCyril** [comment]
@gares  All checks have passed

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
