### PR TITLE
explain_unification_error: reinfer universe inconsistencies

### LINKED ISSUE #17420: "Illegal application ... has type ... should be coercible to" errors that bottom out in universe inconsistencies should explain the universe inconsistency
#### Description of the problem

I spent multiple hours trying to track down a bug in my MetaCoq code that would have been much more obvious if "Illegal application" error messages were as informative as "expected type" error messages.

cc ... @SkySkimmer? @herbelin?

```coq
Universes u0 u1.
Constraint u1 <= u0.
Axiom idu1 : Type@{u1} -> Type@{u1}.
Universe u.
Constraint u = u0.
Fail Check idu1 Type@{u}.
(* The command has indeed failed with message:
The term "Type" has type "Type@{u+1}" while it is expected to have type
"Type@{u1}" (universe inconsistency: Cannot enforce u < u1 because u1 <= u0 = u).
 *)
Fail Check ltac:(refine (idu1 _); exact_no_check Type@{u}).
(* The command has indeed failed with message:
Illegal application:
The term "idu1" of type "Type -> Type"
cannot be applied to the term
 "Type" : "Type"
This term has type "Type@{u+1}" which should be coercible to
"Type@{u1}".
*)
```

#### Coq Version

8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
and missing constraints.

We also make cant_explain_bad_type from typing.ml carry the unification error.

Fix #17420

I'm a bit worried about perf for this.
The bench probably wouldn't tell us since this is about failures.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>What's the concern about perf? 

It can probably be made to blow up arbitrarily. For instance we may have been using a different transparent state when raising the error.

**Comment by ppedrot** [comment]
I'm also a bit concerned about performance with this PR.

**Comment by SkySkimmer** [comment]
Maybe it would be safer to reinfer only for cant_apply_bad_type, where if we don't have the unif error we can be reasonably sure that it's from the kernel and we're re-infering with basically the same algorithm.

**Comment by JasonGross** [comment]
Can this error also get a universe explanation?  (Should I open a new issue?)
```coq
Error: In pattern-matching on term "p0" the branch for constructor
"pair@{}" has type
 "Universes.universes_decl ->
  list Universes.Level.t_ ->
  Type@{max(Set,All_Forall.All.u0,All_Forall.All.u1,T.term.u0,binder_annot.u0,MetaCoq.Common.BasicAst.289,WithTemplate.tmRetypeAroundMetaCoqBug853.u2)}"
which should be
 "Universes.universes_decl ->
  list Universes.Level.t_ ->
  Type@{WithTemplate.tmRetypeAroundMetaCoqBug853.u2}".
```

**Comment by SkySkimmer** [comment]
We're not going to continue this approach.

**Pull request closed without merging**
