### PR TITLE
Fix Equation's ci script

### PR DESCRIPTION
**Pull request by mattam82**
This PR will need to be merged at the same time as mattam82/Coq-Equations#186 as Equations changed its build setup, requiring a first configure step.

**Kind:** infrastructure.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>This PR will need to be merged at the same time as mattam82/Coq-Equations#186 as Equations changed its build setup, requiring a first configure step.

It may be easiest for you to do the merge as an exception to the no-merging-your-own-PRs rule then.

**Comment by mattam82** [comment]
It needs PR HoTT/HoTT#1016 and PR #9776 first

**Comment by mattam82** [comment]
Yes. I'll do that once the other ones are in

**Review by ejgallego — APPROVED** [review]

**Comment by ppedrot** [comment]
@mattam82 up to a rebase, this is ready, isn't it? The dependencies have been merged in their respective repo.

**Comment by mattam82** [comment]
Yep, thanks for the reminder

**Comment by mattam82** [comment]
@ppedrot Shall we check with a CI run that this works? Otherwise feel free to merge

**Comment by ppedrot** [comment]
@mattam82 you can rebase and push indeed, it doesn't hurt to get a full CI.

**Comment by mattam82** [comment]
Can’t, I’m on a phone

**Comment by ppedrot** [comment]
Equation seems broken...

**Comment by mattam82** [comment]
It shouldn’t do parallel make probably, or just missing a dependency from test-suite on the theories

**Comment by ppedrot** [comment]
Is this still relevant?

**Comment by mattam82** [comment]
Yes the ./configure is now necessary on master and the 8.10 branch and up

**Comment by mattam82** [comment]
Rebased, let's see now.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
