### PR TITLE
Remove FCast from CClosure.fterm.

### PR DESCRIPTION
**Pull request by ppedrot**
Just like in the Sixth Sense, it turns out it was dead code all along.

### CODE REVIEW

**Comment by ppedrot** [comment]
CI failure is unrelated to this PR, it is due to Iris being broken on master.

**Comment by SkySkimmer** [comment]
@Zimmi48 here the bot didn't push a status for the failing gitlab job

**Comment by SkySkimmer** [comment]
If we made `fterm` private ocaml would have told us 
> Error (warning 37): constructor FCast is never used to build values.
> (However, this constructor appears in patterns.)

There is only 1 instance of building a fconstr, at https://github.com/coq/coq/blob/2f99e6f1da920f97bf083c846653bec25fb5848e/plugins/setoid_ring/newring.ml#L60
Maybe we should expose some mkapp function and make fterm private.

**Comment by ppedrot** [comment]
IIRC Mtac2 uses (or at least used to use) fconstr to have a tweaked efficient reduction machine.

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
@maximedenes You should probably be the assignee here.

**Review by mattam82 — APPROVED** [review]

**Review by maximedenes — APPROVED** [review]

**Comment by Janno** [comment]
> IIRC Mtac2 uses (or at least used to use) fconstr to have a tweaked efficient reduction machine.

We have our own copy of cClosure.ml because we wanted to pierce some abstraction there. (I don't remember which one, but I think it had to do with some cache.)

**Pull request merged**
