### PR TITLE
Fixing hash consing of constants in cooking

### PR DESCRIPTION
**Pull request by herbelin**
The first part of this patch fixes hash-consing of user kernel names in Cooking and tries to extend PMP's cleaning of the API of Names.

The second part of this patch is proposing to rename equal into eq when it is about hash-consing, so as to hopefully avoid overloading the name equal too often.

### CODE REVIEW

**Comment by herbelin** [comment]
PMP, is it ok for you?

**Comment by ppedrot** [comment]
As far as I can tell this looks OK to me.

**Comment by mattam82** [comment]
I like it too. What does it mean for Cooking though? Is it less sharing for module fields refered to by syntactically different names or is it just preserving the syntactically different names through cooking?

**Comment by herbelin** [comment]
On Cooking's hashconsing, it says not to share two names which are syntactically different, so as to preserve this syntactic name. which was the behavior before PMP's commit. (With PMP's commit, it was using the canonical name (MutInd.equal = Kerpair.equal = KerPair.CanOrd.equal) to decide hash-consing, thus loosing the syntactic name.)

So, yes, it is less sharing than with PMP's commit but the same as before PMP's commit 28a2641d (where just equality on the full ind was used if I'm not mistaken).

Does it answer your question?

**Comment by mattam82** [comment]
Yes, thanks!

**Comment by herbelin** [comment]
Merged

**Pull request closed without merging**
