### PR TITLE
[bench] report pdiff info

### PR DESCRIPTION
**Pull request by Alizter**
We make some new tables for pdiff and increase the table count to 50.

We will need to coordinate this with coqbot: https://github.com/coq/bot/pull/240

<s>I've also changed the table file extensions to .txt so we can browse them on GitLab hopefully.</s>

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>I've also changed the table file extensions to .txt so we can browse them on GitLab hopefully.

That won't work, see logs/wraplog.txt

**Comment by Alizter** [comment]
@coqbot bench native

**Comment by Alizter** [comment]
@coqbot bench native

**Comment by SkySkimmer** [comment]
why native?

**Comment by Alizter** [comment]
@SkySkimmer No reason, just testing new things.

**Comment by Alizter** [comment]
Didn't work since somewhere the .txt extension got truncated. I have now removed them all since they are useless anyway.

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
Hmm kind of working but I will need to push a change that will slow things down so we can actually see pdiff changes.

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@SkySkimmer This is good to go, I will remove the debug stuff in the commit.

**Comment by SkySkimmer** [comment]
Do we actually want this? Seems kinda verbose.

**Comment by Alizter** [comment]
@SkySkimmer @ppedrot wanted to see the line changes ordered by diff a while back.

**Comment by Alizter** [comment]
Actually @SkySkimmer, which part are you finding verbose? The count increase or pdiff?

**Comment by SkySkimmer** [comment]
The pdiff

**Comment by Alizter** [comment]
I will do a few iterations on the coqbot side. I can hide the pdiff changes in the comment, but include them in the summary.

**Pull request closed without merging**
