### PR TITLE
Delay import of notation sets in Notationextern.

### PR DESCRIPTION
**Pull request by ppedrot**
This speeds up a lot importing files that define a lot of notations. The underlying algorithm is still very inefficient and quite non-sensical, as it adds elements in a list in O(n) w.r.t. an order which is not total. We should reimplement it in a more sensible way but that requires a redesign, e.g. using some kind of dnets. In the meantime this patch is simple and seems to solve a good part of the problems in practice.

Alleviates #19357 but does not fix the underlying problem.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
The bench doesn't seem very convincing.

**Comment by ppedrot** [comment]
Sure, nobody hits that in standard devs. Yet on @Janno 's examples it was clearly observable.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by Janno** [comment]
Thanks! This is much appreciated!

**Comment by SkySkimmer** [comment]
@Janno dd you run your private bench on this?

**Comment by Janno** [comment]
Yes, but the result was recorded in the issue because the PR did not exist at the time: https://github.com/coq/coq/issues/19357#issuecomment-2478821880

**Pull request merged**
