### PR TITLE
Faster coherence check when adding coercions.

### PR DESCRIPTION
**Pull request by ppedrot**
When the coherence warning is unset, which is the case for heavy user of coercions, we do not perform an expensive traversal of the graph. The underlying algorithm is still very bad as it is at least quadratic in the number of classes, but this patch should alleviate a good part of the issues.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Awesome, but ci is red

**Comment by ppedrot** [comment]
The CI failures are unrelated, these are just missing overlays.

**Comment by proux01** [comment]
Great!
Cc @pi8027 FYI

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by pi8027** [comment]
@ppedrot Thanks. BTW, you changed the internal representation of the coercion graph in #14754. We can probably get rid of `cl_reachable_from` and `cl_reachable_to` thanks to that, but I don't remember the details. Shall we take a look at it after the summer vacation?

**Comment by ppedrot** [comment]
Definitely, the current algorithm is really suboptimal and may explode for serious users of coercions, we should have a look at that in September.

**Pull request merged**
