### PR TITLE
Fix bug #5255

### PR DESCRIPTION
**Pull request by ppedrot**
See https://coq.inria.fr/bugs/show_bug.cgi?id=5255.

### CODE REVIEW

**Comment by maximedenes** [comment]
@mattam82 ping

**Review by mattam82 — APPROVED** [review]
This overlook means nobody must have used definitions in Context before so no compatibility worries a priori

**Comment by ppedrot** [comment]
@ejgallego This is a bugfix for 8.6, I don't think it makes sense to mark it being part of the 8.7 milestone.

**Comment by JasonGross** [comment]
> This overlook means nobody must have used definitions in Context before so no compatibility worries a priori

I've used them occasionally when I didn't want to declare types for all of the arguments; I'd do something like
```coq
Context `(foo' := bar a b c d e f).
Let foo := bar a b c d e f.
```
I never relied on `:=` dropping the body, though.

**Pull request merged**
