### PR TITLE
Avoid bad gcc warning

### LINKED ISSUE #16426: warning: storing the address of local variable ‘coq_lbl_ACC0’ in ‘coq_instr_base’
I guess gcc updated and now I get this:
~~~
         gcc kernel/byterun/coq_interp.o
coq_interp.c: In function ‘coq_interprete’:
coq_interp.c:301:20: warning: storing the address of local variable ‘coq_lbl_ACC0’ in ‘coq_instr_base’ [-Wdangling-pointer=]
  301 |     coq_instr_base = coq_Jumptbl_base;
      |                    ^
coq_interp.c:74:26: note: ‘coq_lbl_ACC0’ declared here
   74 | #  define Instruct(name) coq_lbl_##name:
      |                          ^~~~~~~~
coq_interp.c:325:7: note: in expansion of macro ‘Instruct’
  325 |       Instruct(ACC0){
      |       ^~~~~~~~
In file included from coq_interp.c:28:
coq_fix_code.h:20:15: note: ‘coq_instr_base’ declared here
   20 | extern char * coq_instr_base;
      |               ^~~~~~~~~~~~~~
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16426

see also https://github.com/ocaml/ocaml/pull/11379

### CODE REVIEW

**Comment by ppedrot** [comment]
I don't feel qualified for this PR, so I'm leaving it to the appreciation (and assignment) of @silene.

**Review by JasonGross — APPROVED** [review]
I'm not a code maintainer here, but I was curious, so I read the OCaml and gcc bug reports, and I more-or-less understand what's going on here.  As long as we're not jumping to these labels from functions other than where they're declared, silencing the warning seems fine, and this seems like a fine way to do it.  (But I wouldn't be surprised if there's some warning in a future version of gcc about passing the addresses of local labels to other functions, since the thing we're doing is a thing that gcc is genuinely trying to warn about, namely, making it possible to jump into the middle of a function.)

**Comment by silene** [comment]
I am conflicted. Part of the changes in this pull request are due to `VALINSTR` escaping `coq_fix_code.c`, which does not make any sense to me. Let me see if we can improve on that first.

**Comment by silene** [comment]
See #16961, which includes this pull request.

**Pull request closed without merging**
