### PR TITLE
[ci] coq-elpi 1.10.0

### PR DESCRIPTION
**Pull request by gares**
overlay PR: https://github.com/LPCIC/coq-elpi/pull/245

### CODE REVIEW

**Comment by gares** [comment]
CI is green (the interesting job is elpi). For some reason the link here is wrong, the most recent pipeline is: https://gitlab.com/coq/coq/-/pipelines/307412518

**Comment by gares** [comment]
ready!

**Review by Zimmi48 — APPROVED** [review]
You will need to rebase and regenerate the Docker image.
Let me know when you want to see this merged.

**Comment by gares** [comment]
ASAP

**Comment by Zimmi48** [comment]
The Docker image was rebuilt and ci-elpi passed.
@coqbot merge now

**Pull request merged**
