### PR TITLE
Bug fix : variable capture in ltac code of Nsatz

### PR DESCRIPTION
**Pull request by thery**
changing
set (x := val)
into
let x := fresh "x" in
set (x := val)

### CODE REVIEW

**Comment by silene** [comment]
It looks good, but just for the sake of minimizing the noise, could you revert the changes to the blank lines (two lines added, two lines removed)? There is also the blank you added at the end of a line when changing the debug code. I can do these changes myself if you prefer.

**Comment by thery** [comment]
It would be nice if you could do it  (I'vent completed my github 
training so I don't know how to revert partially a commit except by 
creating a brand new commit ;-))

**Comment by silene** [comment]
I am stumped. Was your patch really against v8.5? One of the commits requires the Feedback interface, which I don't think was ever part of 8.5. So I will be committing only the other one to v8.5, once I have checked everything runs fine.

**Comment by silene** [comment]
I have committed the actual fix about variable capture, so I am closing this pull request. But I do agree that something has to be done regarding the verbosity (to be polite) of `nsatz`.

**Comment by maximedenes** [comment]
Thanks Guillaume, I'll take care of the print part. Actually, I wrongly advised Laurent to use Feedback.msg_debug. My brain has fully switched to 8.6 :) sorry about that

**Pull request closed without merging**
