### PR TITLE
Bench: export TIMED=1 (enable coq_makefile per file timings)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Looks fine
~~~
   After |  Peak Mem | File Name                                                    |   Before |  Peak Mem ||    Change || Change (mem) | % Change | % Change (mem)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
2m32.97s | 592972 ko | Total Time / Peak Mem                                        | 2m33.34s | 595092 ko || -0m00.37s ||     -2120 ko |   -0.24% |         -0.35%
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
0m05.57s | 452532 ko | Homotopy/Syllepsis.vo                                        | 0m05.60s | 453764 ko || -0m00.02s ||     -1232 ko |   -0.53% |         -0.27%
0m05.26s | 443076 ko | Classes/implementations/natpair_integers.vo                  | 0m05.24s | 443504 ko || +0m00.01s ||      -428 ko |   +0.38% |         -0.09%
0m04.73s | 592972 ko | Colimits/Colimit_Flattening.vo                               | 0m04.73s | 595092 ko || +0m00.00s ||     -2120 ko |   +0.00% |         -0.35%
0m03.76s | 514620 ko | Colimits/Colimit_Pushout.vo                                  | 0m03.78s | 514336 ko || -0m00.02s ||       284 ko |   -0.52% |         +0.05%
0m02.74s | 401288 ko | Colimits/Sequential.vo                                       | 0m02.76s | 397872 ko || -0m00.01s ||      3416 ko |   -0.72% |         +0.85%
0m02.64s | 428440 ko | Cubical/PathCube.vo                                          | 0m02.64s | 428656 ko || +0m00.00s ||      -216 ko |   +0.00% |         -0.05%
(etc)
~~~

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
The combined log is not great as not everything prints the file's absolute path so it's hard to tell where a file came from, but I guess it's better than nothing.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
