### PR TITLE
move instances out of DecidableClass

### PR DESCRIPTION
**Pull request by andres-erbsen**
See also https://github.com/coq/coq/pull/16345#issuecomment-1349821783

- [x] Added **changelog**.

### CODE REVIEW

**Comment by andres-erbsen** [comment]
I don't know about these instances specifically, but IIUC developments broadly rely on Require bringing in standard-library instances so I didn't want to get compat-rabbitholed here.

**Comment by Alizter** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
CI failures look unrelated. @Alizter are you willing to be the assignee?

**Comment by Alizter** [comment]
@andres-erbsen looks like metacoq might be related however.

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by MSoegtropIMC** [comment]
@andres-erbsen : I am confused - aren't the same changes in (https://github.com/coq/coq/pull/17022)?

**Comment by andres-erbsen** [comment]
@Alizter I missed the filename and thought a make error wouldn't be related; thanks. I'm building it locally to investigate.

@MSoegtropIMC yes; if that's not how Coq develeopment is supposed to work please let me know. I made stacked PRs because I thought the reviews would be rather different and in principle we could decide to refactor and have either one but not the other.

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by MSoegtropIMC** [comment]
> @MSoegtropIMC yes; if that's not how Coq develeopment is supposed to work please let me know. I made stacked PRs because I thought the reviews would be rather different and in principle we could decide to refactor and have either one but not the other.

I somehow read over your corresponding comment in #17022 - it is fine.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@andres-erbsen If you need help with metacoq, you can ask the maintainers on Zulip.

**Comment by andres-erbsen** [comment]
I do intend to return to this, but probably in a week or so.

**Comment by Alizter** [comment]
@andres-erbsen ping

**Comment by andres-erbsen** [comment]
Thanks for the poke. I have reproduced the issue locally; continuing at https://coq.zulipchat.com/#narrow/stream/237658-MetaCoq/topic/Build.20errors.20.28coq.2317021.29

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
@samuelgruetter do you understand this ci-bedrock2 failure? https://gitlab.com/coq/coq/-/jobs/3619360787#L4848

**Comment by Alizter** [comment]
@andres-erbsen That doesn't seem to be relevant for us as the failure appears in master. I will merge this soon.

**Pull request merged**
