### PR TITLE
CI: add job printing stats about the current pipeline

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I added a token and put it in variable PIPELINE_STATS_TOKEN
It has only read access at "guest" level so I don't think we particularly need to worry about it being misused.

**Comment by SkySkimmer** [comment]
Light pipeline
~~~
| name                   | duration   | artifacts size   | log size   |      id |
|------------------------+------------+------------------+------------+---------|
| pipeline-stats         | 12s        | 0.00 B           | 0.00 B     | 5075732 |
| doc:init               | 54s        | 1.73 MiB         | 35.99 KiB  | 5075729 |
| plugin:plugin-tutorial | 1min 17s   | 0.00 B           | 43.08 KiB  | 5075726 |
| doc:ml-api:odoc        | 1min 26s   | 5.83 MiB         | 521.04 KiB | 5075730 |
| lint                   | 2min 50s   | 0.00 B           | 40.55 KiB  | 5075725 |
| build:base:dev         | 2min 9s    | 234.99 MiB       | 35.51 KiB  | 5075724 |
| doc:refman             | 3min 17s   | 12.38 MiB        | 57.13 KiB  | 5075727 |
| test-suite:base:dev    | 4min 49s   | 0.00 B           | 0.00 B     | 5075731 |
| doc:refman-pdf         | 5min 19s   | 11.74 MiB        | 0.00 B     | 5075728 |
| docker-boot            | 5min 23s   | 0.00 B           | 6.96 KiB   | 5075722 |
| total                  | 26min 37s  | 266.67 MiB       | 740.24 KiB | 1085921 |
~~~

@coqbot run full ci

**Comment by SkySkimmer** [comment]
full ci
~~~
| name                             | duration   | artifacts size   | log size    |      id |
|----------------------------------+------------+------------------+-------------+---------|
| pipeline-stats                   | 13s        | 0.00 B           | 0.00 B      | 5075847 |
| validate:base+32bit              | 41s        | 13.79 KiB        | 77.38 KiB   | 5075755 |
| validate:base                    | 44s        | 13.76 KiB        | 89.03 KiB   | 5075754 |
| plugin:ci-ltac2_compiler         | 48s        | 731.50 KiB       | 60.69 KiB   | 5075792 |
| plugin:ci-reduction_effects      | 54s        | 159.72 KiB       | 943.11 KiB  | 5075796 |
| validate:edge+flambda            | 58s        | 13.79 KiB        | 85.20 KiB   | 5075756 |
| plugin:ci-tactician              | 1min 1s    | 6.11 MiB         | 54.50 KiB   | 5075802 |
| plugin:ci-lean_importer          | 1min 7s    | 15.99 MiB        | 71.14 KiB   | 5075791 |
| plugin:plugin-tutorial           | 1min 7s    | 0.00 B           | 43.07 KiB   | 5075744 |
| library:ci-coqtail               | 1min 11s   | 167.33 KiB       | 63.55 KiB   | 5075762 |
| library:ci-simple_io             | 1min 18s   | 56.17 MiB        | 195.88 KiB  | 5075813 |
| doc:init                         | 2min 36s   | 1.73 MiB         | 35.99 KiB   | 5075747 |
| plugin:ci-waterproof             | 2min 40s   | 51.58 MiB        | 314.21 KiB  | 5075803 |
| doc:ml-api:odoc                  | 2min 44s   | 5.83 MiB         | 499.71 KiB  | 5075748 |
| plugin:ci-vscoq                  | 2min 49s   | 170.34 MiB       | 71.83 KiB   | 5075799 |
| plugin:ci-aac_tactics            | 2min 57s   | 51.39 MiB        | 91.37 KiB   | 5075780 |
| library:ci-bigenough             | 2min 57s   | 217.60 MiB       | 222.47 KiB  | 5075834 |
| pkg:nix                          | 2min 3s    | 0.00 B           | 246.39 KiB  | 5075743 |
| library:ci-autosubst             | 2min 6s    | 49.00 MiB        | 63.33 KiB   | 5075758 |
| library:ci-menhir                | 2min 7s    | 105.13 MiB       | 959.39 KiB  | 5075770 |
| plugin:ci-quickchick             | 2min 10s   | 239.12 MiB       | 453.13 KiB  | 5075841 |
| library:ci-argosy                | 2min 13s   | 47.23 MiB        | 97.03 KiB   | 5075757 |
| library:ci-stdlib_doc            | 2min 19s   | 52.53 MiB        | 71.05 KiB   | 5075815 |
| library:ci-bbv                   | 2min 20s   | 45.78 MiB        | 136.39 KiB  | 5075759 |
| library:ci-paco                  | 2min 21s   | 56.49 MiB        | 207.42 KiB  | 5075773 |
| library:ci-ext_lib               | 2min 21s   | 55.08 MiB        | 222.36 KiB  | 5075766 |
| library:ci-itree_io              | 2min 21s   | 90.67 MiB        | 257.00 KiB  | 5075836 |
| build:base+async                 | 2min 29s   | 222.62 MiB       | 59.94 KiB   | 5075740 |
| library:ci-tlc                   | 3min 33s   | 50.39 MiB        | 92.23 KiB   | 5075777 |
| plugin:ci-stalmarck              | 3min 41s   | 49.74 MiB        | 138.24 KiB  | 5075801 |
| build:base                       | 3min 50s   | 222.63 MiB       | 38.07 KiB   | 5075735 |
| library:ci-rupicola              | 3min 51s   | 168.95 MiB       | 459.36 KiB  | 5075844 |
| build:base+32bit                 | 3min 53s   | 213.13 MiB       | 35.62 KiB   | 5075736 |
| plugin:ci-smtcoq                 | 3min 6s    | 58.18 MiB        | 250.18 KiB  | 5075800 |
| lint                             | 3min 8s    | 0.00 B           | 40.75 KiB   | 5075741 |
| library:ci-neural_net_interp     | 3min 10s   | 68.87 MiB        | 150.21 KiB  | 5075772 |
| library:ci-flocq                 | 3min 11s   | 57.28 MiB        | 107.23 KiB  | 5075768 |
| library:ci-coqutil               | 3min 14s   | 65.96 MiB        | 282.89 KiB  | 5075763 |
| plugin:ci-coqhammer              | 3min 18s   | 55.04 MiB        | 105.17 KiB  | 5075787 |
| plugin:ci-autosubst_ocaml        | 3min 23s   | 100.03 MiB       | 75.84 KiB   | 5075782 |
| library:ci-coqprime              | 4min 36s   | 65.60 MiB        | 168.40 KiB  | 5075807 |
| library:ci-hott                  | 4min 41s   | 22.42 MiB        | 227.29 KiB  | 5075771 |
| build:base:dev                   | 4min 43s   | 235.00 MiB       | 35.62 KiB   | 5075738 |
| plugin:ci-smtcoq_trakt           | 4min 46s   | 151.91 MiB       | 411.51 KiB  | 5075845 |
| plugin:ci-paramcoq               | 4min 0s    | 52.34 MiB        | 150.38 KiB  | 5075794 |
| plugin:ci-equations              | 4min 1s    | 58.14 MiB        | 112.23 KiB  | 5075789 |
| plugin:ci-coq_dpdgraph           | 4min 3s    | 52.53 MiB        | 85.80 KiB   | 5075786 |
| library:ci-stdlib                | 4min 5s    | 53.27 MiB        | 85.60 KiB   | 5075775 |
| library:ci-stdlib_test           | 4min 9s    | 44.24 MiB        | 173.23 KiB  | 5075814 |
| plugin:ci-equations_test         | 4min 12s   | 66.51 MiB        | 205.32 KiB  | 5075820 |
| library:ci-trakt                 | 4min 12s   | 133.24 MiB       | 166.52 KiB  | 5075817 |
| plugin:ci-coinduction            | 4min 14s   | 49.35 MiB        | 84.24 KiB   | 5075785 |
| plugin:ci-bignums                | 4min 20s   | 55.90 MiB        | 103.80 KiB  | 5075784 |
| doc:refman                       | 4min 21s   | 12.38 MiB        | 35.88 KiB   | 5075745 |
| library:ci-engine_bench          | 4min 22s   | 46.41 MiB        | 157.72 KiB  | 5075765 |
| library:ci-mczify                | 5min 37s   | 219.85 MiB       | 319.86 KiB  | 5075832 |
| test-suite:base:dev              | 5min 38s   | 0.00 B           | 187.25 KiB  | 5075752 |
| docker-boot                      | 5min 42s   | 0.00 B           | 6.96 KiB    | 5075733 |
| library:ci-math_classes          | 5min 44s   | 68.38 MiB        | 344.65 KiB  | 5075810 |
| library:ci-sf                    | 5min 45s   | 129.40 MiB       | 735.65 KiB  | 5075774 |
| plugin:ci-hb_test                | 5min 51s   | 145.81 MiB       | 264.51 KiB  | 5075819 |
| library:ci-deriving              | 5min 52s   | 221.27 MiB       | 233.48 KiB  | 5075838 |
| plugin:ci-elpi_hb                | 5min 54s   | 132.69 MiB       | 516.96 KiB  | 5075788 |
| test-suite:base+32bit            | 5min 58s   | 0.00 B           | 844.17 KiB  | 5075750 |
| plugin:ci-elpi_test              | 5min 3s    | 162.67 MiB       | 1.50 MiB    | 5075818 |
| plugin:ci-mtac2                  | 5min 4s    | 62.22 MiB        | 395.87 KiB  | 5075793 |
| plugin:ci-itauto                 | 5min 8s    | 60.65 MiB        | 1009.79 KiB | 5075783 |
| plugin:ci-atbr                   | 5min 11s   | 61.12 MiB        | 1.02 MiB    | 5075781 |
| plugin:ci-relation_algebra       | 5min 18s   | 228.95 MiB       | 318.60 KiB  | 5075843 |
| library:ci-mathcomp_test         | 5min 18s   | 217.73 MiB       | 244.64 KiB  | 5075831 |
| library:ci-finmap                | 5min 26s   | 219.35 MiB       | 250.75 KiB  | 5075833 |
| library:ci-kami                  | 6min 43s   | 75.92 MiB        | 299.44 KiB  | 5075769 |
| library:ci-mathcomp_word         | 6min 53s   | 218.10 MiB       | 247.68 KiB  | 5075816 |
| test-suite:base                  | 6min 4s    | 0.00 B           | 868.53 KiB  | 5075749 |
| test-suite:edge+flambda          | 6min 16s   | 0.00 B           | 854.39 KiB  | 5075751 |
| library:ci-stdlib+flambda        | 6min 23s   | 61.28 MiB        | 113.05 KiB  | 5075776 |
| library:ci-color                 | 6min 26s   | 115.56 MiB       | 763.33 KiB  | 5075805 |
| library:ci-cross_crypto          | 6min 27s   | 57.28 MiB        | 725.40 KiB  | 5075764 |
| build:base:dev:dune              | 7min 31s   | 0.00 B           | 47.39 KiB   | 5075739 |
| plugin:ci-coq_lsp                | 7min 36s   | 251.16 MiB       | 162.96 KiB  | 5075798 |
| doc:refman-pdf                   | 7min 38s   | 11.74 MiB        | 37.02 KiB   | 5075746 |
| plugin:ci-quickchick_test        | 7min 48s   | 244.99 MiB       | 852.05 KiB  | 5075842 |
| test-suite:base+async            | 7min 49s   | 0.00 B           | 872.68 KiB  | 5075753 |
| build:edge+flambda               | 7min 9s    | 396.43 MiB       | 60.12 KiB   | 5075737 |
| library:ci-fiat_crypto_ocaml     | 7min 17s   | 0.00 B           | 0.00 B      | 5075827 |
| library:ci-http                  | 7min 20s   | 335.14 MiB       | 559.84 KiB  | 5075840 |
| library:ci-fcsl_pcm              | 7min 27s   | 229.77 MiB       | 248.32 KiB  | 5075808 |
| plugin:ci-rewriter               | 8min 34s   | 64.69 MiB        | 402.29 KiB  | 5075797 |
| plugin:ci-fiat_parsers           | 8min 60s   | 60.81 MiB        | 1.26 MiB    | 5075790 |
| library:ci-compcert              | 8min 8s    | 197.33 MiB       | 162.19 KiB  | 5075806 |
| library:ci-coquelicot            | 8min 15s   | 224.54 MiB       | 367.71 KiB  | 5075825 |
| library:ci-category_theory       | 8min 18s   | 69.78 MiB        | 212.12 KiB  | 5075804 |
| library:ci-riscv_coq             | 10min 33s  | 89.53 MiB        | 245.74 KiB  | 5075822 |
| pkg:opam:native                  | 10min 43s  | 19.62 KiB        | 64.71 KiB   | 5075742 |
| library:ci-jasmin                | 10min 15s  | 255.02 MiB       | 350.79 KiB  | 5075839 |
| library:ci-corn                  | 10min 20s  | 171.44 MiB       | 785.84 KiB  | 5075830 |
| library:ci-mathcomp              | 10min 29s  | 217.53 MiB       | 277.94 KiB  | 5075811 |
| library:ci-coq_performance_tests | 11min 2s   | 55.42 MiB        | 544.26 KiB  | 5075760 |
| library:ci-itree                 | 11min 24s  | 89.68 MiB        | 325.35 KiB  | 5075812 |
| library:ci-analysis              | 12min 49s  | 265.69 MiB       | 406.75 KiB  | 5075835 |
| library:ci-coq_tools             | 12min 56s  | 47.03 MiB        | 55.48 KiB   | 5075761 |
| library:ci-oddorder              | 12min 21s  | 237.86 MiB       | 352.31 KiB  | 5075828 |
| library:ci-verdi_raft            | 13min 51s  | 84.87 MiB        | 301.47 KiB  | 5075779 |
| library:ci-bedrock2              | 13min 28s  | 150.88 MiB       | 685.96 KiB  | 5075823 |
| library:ci-iris                  | 16min 57s  | 108.08 MiB       | 484.67 KiB  | 5075809 |
| doc:ci-refman                    | 17min 3s   | 24.67 MiB        | 1.49 MiB    | 5075846 |
| plugin:ci-perennial              | 17min 13s  | 125.49 MiB       | 155.04 KiB  | 5075795 |
| library:ci-unimath               | 21min 27s  | 46.14 MiB        | 398.97 KiB  | 5075778 |
| library:ci-fourcolor             | 22min 54s  | 236.47 MiB       | 387.68 KiB  | 5075829 |
| library:ci-fiat_crypto_legacy    | 28min 33s  | 106.66 MiB       | 2.06 MiB    | 5075767 |
| plugin:ci-metacoq                | 28min 48s  | 235.11 MiB       | 1020.04 KiB | 5075821 |
| library:ci-vst                   | 29min 26s  | 275.99 MiB       | 710.24 KiB  | 5075837 |
| library:ci-fiat_crypto           | 34min 49s  | 367.00 MiB       | 1.40 MiB    | 5075826 |
| library:ci-bedrock2_examples     | 38min 34s  | 186.70 MiB       | 514.00 KiB  | 5075824 |
| total                            | 13h 33min  | 11.40 GiB        | 39.27 MiB   | 1085922 |
~~~

**Comment by SkySkimmer** [comment]
Not sure what's going on in docker-boot but the previous pipelines worked and nothing should have changed since then.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
