### PR TITLE
Remove test file with Timeout that failed spuriously.

### PR DESCRIPTION
**Pull request by Zimmi48**
In #9502 it was agreed to remove test files that contain the `Timeout` command and fail spuriously. Here is another one (see failure at https://gitlab.com/coq/coq/-/jobs/187496964).

**Kind:** infrastructure.

### CODE REVIEW

**Review by maximedenes — CHANGES_REQUESTED** [review]
I think it is a bad idea to remove such tests. Instead, they should be made reliable.

In this case, it should be easy, just bound the search depth, no?

**Comment by Zimmi48** [comment]
If you bound the search depth, the test isn't testing anything useful anymore. I think these tests were added mostly by @JasonGross and merged without much consideration. We already have infrastructure for complexity test: this should be used instead.

**Comment by maximedenes** [comment]
> If you bound the search depth, the test isn't testing anything useful anymore.

Why? I thought the initial bug report was about depth count having changed semantics.

**Comment by Zimmi48** [comment]
OK maybe then, but we would need to check that the test file would have still caught the bug at that time. No point in keeping test files that don't test anything.

**Comment by Zimmi48** [comment]
Yet another failure: https://gitlab.com/coq/coq/-/jobs/208454712

**Comment by Zimmi48** [comment]
New instance: https://gitlab.com/coq/coq/-/jobs/210749660

**Review by SkySkimmer — APPROVED** [review]
Unless someone makes a PR with a better alternative soon (let's say this week) we should get on with it and merge.
I think we rely on the bench much more than tests to avoid perf regressions.

**Comment by Zimmi48** [comment]
Yet another occurrence: https://gitlab.com/coq/coq/-/jobs/214414670

**Comment by Zimmi48** [comment]
And yet another one! https://gitlab.com/coq/coq/-/jobs/214658761

**Comment by SkySkimmer** [comment]
As announced, let's merge. @maximedenes if you still want to have a test for #4429 please open a PR with one, or if you don't have time you can make an issue.

**Pull request merged**
