### PR TITLE
Sphinx doc chapter 26

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by maximedenes** [comment]
@Zimmi48 did you review this chapter like the others?

**Comment by Zimmi48** [comment]
Yes, I did sorry for not saying anything. I am planning to open a new issue to report on this general experience.

**Comment by maximedenes** [comment]
Pipeline at https://gitlab.com/maximedenes/coq/pipelines/19709225

**Comment by maximedenes** [comment]
only spurious failures. @silene can you merge this one after the ones it depends on? Thanks!

**Pull request merged**
