### PR TITLE
cleanup locality in comRewrite

### PR DESCRIPTION
**Pull request by Alizter**
This is the locality cleanups from #17161.

Overlays:
- https://github.com/mattam82/Coq-Equations/pull/530

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
ping @ppedrot

**Comment by ppedrot** [comment]
The Equations overlay seems to be out of date, maybe you should rebase it?

**Comment by ppedrot** [comment]
Indeed.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
ping @ppedrot

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
