### PR TITLE
Code cleanups in tactics

### PR DESCRIPTION
**Pull request by ppedrot**
We factorize some code and remove dead code in apply/destruct-related tactics.

### CODE REVIEW

**Comment by ppedrot** [comment]
@herbelin would you assign?

**Comment by herbelin** [comment]
> @herbelin would you assign?

When you say "asssign", do you mean review, coordinate the discussion, and eventually merge, or only the latter?

In any case, I made a quick review. So, you made the following:
- factorizing parts of `elimination_clause_scheme` and `elimination_in_clause_scheme` and inlining the former;
- removing `sidecond_first` made obsolete by the removal of the corresponding option;
- removing `elimrename` made obsolete by the removal of the option "Standard Proposition Elimination".

Is that all?

**Review by herbelin — APPROVED** [review]
I did not look at every piece of code changed, but that looks like a welcome simplification.

**Comment by ppedrot** [comment]
> When you say "asssign", do you mean review, coordinate the discussion, and eventually merge, or only the latter?

All of that. For some reason you didn't appear on the code owners, but I believe that this PR falls neatly in your area.

**Comment by ppedrot** [comment]
> Is that all?

I guess so.

**Comment by herbelin** [comment]
OK. I will now assume that most possibly concerned people here are enough busy with more important matters for wanting spending time on a purely cleaning PR.

So, preventively leaving an extra day for reflection, I'll merge tomorrow afternoon.

**Pull request merged**
