### PR TITLE
Miscellaneous fixes for notations

### PR DESCRIPTION
**Pull request by herbelin**
This is a small collection of short fixes for notations. It is morally applicable to any version for which it is relevant to do so (independently of the question of releasing of course). Regarding 8.7, it can be before or after 8.7beta.

Edit: this depends on #916 to avoid the failure in the test suite.

### CODE REVIEW

**Comment by herbelin** [comment]
Someone willing to review and/or merge this? A merge would help rebasing #982.

**Comment by maximedenes** [comment]
I'll try to have a look soon, but I'm not expert at all, so it would be better if @ejgallego or @ppedrot could review it, for instance. In any case, I'm ready to merge it as soon as a review gives green light.

**Review by ejgallego — COMMENTED** [review]
Looks good to me for both 8.8 and 8.7

**Review by ejgallego — APPROVED** [review]

**Comment by herbelin** [comment]
Wow, thanks!

**Comment by Zimmi48** [comment]
FTR all the commits in this PR but two are easy to backport (they go through without conflicts). Two commits (5d3d60e and 6c3fd3b) are conflicting due to the recent `CAst` -> `DAst` changes. In the case of 5d3d60e, the conflict is still bearable and Travis testing should be enough to confirm no mistake is made but 6c3fd3b has conflicts all over the place and I won't manage to backport it without help.

**Comment by ppedrot** [comment]
@Zimmi48 I guess this is an indirect call for my help. Do you have a branch over which I should perform the backport of 6c3fd3b for you?

**Comment by ppedrot** [comment]
@Zimmi48 Actually it is not that hard. Instead of `is_gvar p e`, look for `Id.equal p e` in the 8.7 branch. The changes are then just adding the corresponding `not (occur_glob_constr p ...)` where clause.

**Comment by Zimmi48** [comment]
@ppedrot Will have a better look tomorrow and come back to you if I can't manage on my own.

**Comment by herbelin** [comment]
Probably you already did the exercice of undoing DAst. Otherwise, I pushed the branch before the DAst rebase [here](https://github.com/herbelin/github-coq/tree/master%2Bmisc-fixes-notations-avant-DAst).

**Comment by Zimmi48** [comment]
@herbelin If you have kept this that would be even simpler, but unfortunately the branch you pointed me to is already after the DAst change.

**Comment by Zimmi48** [comment]
@ppedrot Your advice was enough for the first conflicts. But then I get into some real trouble after a while, cf. https://github.com/Zimmi48/coq/tree/backport-pr-981 (I committed d6a90314ea9f17b1d2eb5147703e1704287cd7e5 with conflicts unresolved).
If you see how to do it easily, the best thing might be for you to do the backport entirely and submit a PR. The command to do this is:
```
git cherry-pick -x cc94172036789cfef28007f59510b7f17df5d45d..b9106a956c32e1352fcad5f0138a4e3ddee0474c
```

**Comment by ppedrot** [comment]
@Zimmi48 I'm on it.

**Pull request merged**
