### PR TITLE
Checking validity of coqdoc file name (fixes #12265)

### LINKED ISSUE #12265: coqdoc script injection vulnerability
#### Description of the problem

I renamed the [links.v test](https://github.com/coq/coq/blob/master/test-suite/coqdoc/links.v) to:
`links<iframe src='javascript:alert(1);'>Evil.v`

Running coqdoc on this file results in injection into the generated index.html:
`<a href="links<iframe src='javascript:alert(1);'>Evil.html">links<iframe src='javascript:alert(1);'>Evil</a> [library]<br/>`

There's some escaping happening [here](https://github.com/coq/coq/blob/master/tools/coqdoc/output.ml) where the markup appears to be generated, however it doesn't seem to apply everywhere it should.

I'm testing on coqdoc version 8.9.0 so it's possible something has changed since the latest version, but I'm still seeing [mostly the same code in `format_global_index`](https://github.com/coq/coq/blob/master/tools/coqdoc/output.ml#L850) so I think likely this works in the latest release as well.

#### Coq Version

8.9.0

index.html contains:
iframe

### PR DESCRIPTION
**Pull request by herbelin**
In particular, this fixes #12265 (javascript injection vulnerability in file name).

**Kind:** bug fix

Fixes / closes #12265 (it fixes at least the reported vulnerability; there may be others).

- [ ] Entry added in the changelog

### CODE REVIEW

**Review by randomdross — COMMENTED** [review]
(TBH I haven't looked at ml for 25 years, and thus it's fair to ask why I'm even finding bugs in coq, but...)
https://github.com/coq/coq/blob/master/clib/unicode.ml
...seems to suggest that now only letters, numbers and single quotes will be valid filename chars.  Is that correct?  Wouldn't it block filenames with dashes in them?  Seems better to address this with filtering closer to the generated HTML markup, rather than reducing the definition of a filename.

**Comment by herbelin** [comment]
@ejgallego: I need some help: how should I tell to `dune` that this PR adds a dependency of `coqdoc` into `clib/unicode.ml`?

**Comment by herbelin** [comment]
> seems to suggest that now only letters, numbers and single quotes will be valid filename chars. Is that correct? Wouldn't it block filenames with dashes in them? Seems better to address this with filtering closer to the generated HTML markup, rather than reducing the definition of a filename.

Yes, this restricts the class of filenames. But this class is already restricted because there is a mapping of filenames to module names and module names (which we can refer to in Coq files) exactly follow the above convention.

Try for instance:
```
coqc foo-bar.v
```
It already fails with message `Invalid character '-' in identifier "foo-bar"`.

**Comment by ejgallego** [comment]
> @ejgallego: I need some help: how should I tell `dune` that this PR adds a dependency of `coqdoc` into `clib/unicode.ml`?

Add `(libraries coq.clib)` to the executable stanza in `tools/coqdoc/dune`

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
If @coq/coqdoc-maintainers do not react, you can assign this to me.

**Comment by Zimmi48** [comment]
FTR I don't think a changelog is absolutely required in this case, since those file names where already not valid for processing with `coqc`. I intend to merge this over the week-end.

**Pull request merged**
