### PR TITLE
Update Azure MacOS version 10.13 -> 10.14

### LINKED ISSUE #11449: azure macos 10.13 deprecated
Azure sent me an email "Azure Pipelines will stop supporting Default Hosted, WinCon, and MacOS 10.13 images on March 23, 2020"
We need to change `vmImage: 'macOS-10.13'` to 10.14 before then.

### PR DESCRIPTION
**Pull request by SkySkimmer**
10.13 is deprecated as an azure VM

Close #11449

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
I guess that should be fine, we do build the OSX images here do we?

Can someone test the artifact at https://dev.azure.com/coq/coq/_build/results?buildId=8082&view=artifacts&type=publishedArtifacts ?

**Comment by Zimmi48** [comment]
cc @herbelin 
I think he has a pretty old macOS version, so would be a perfect candidate for testing the installer.

**Comment by herbelin** [comment]
When trying to install the file `coq-8.12+alpha-installer-macos.dmg` linked above, I get (translated to English): Impossible to open the disk image, no mountable file system.

Note: I'm on MacOS 10.11.1.

**Comment by ejgallego** [comment]
> Note: I'm on MacOS 10.11.1.

@herbelin does the one here work https://dev.azure.com/coq/coq/_build/results?buildId=8123&view=artifacts&type=publishedArtifacts ?

**Comment by herbelin** [comment]
> @herbelin does the one here work https://dev.azure.com/coq/coq/_build/results?buildId=8123&view=artifacts&type=publishedArtifacts ?

Yes, it installs perfectly, and I could `Check True.` in CoqIDE!

**Comment by ejgallego** [comment]
Thanks @herbelin , thus the PR seems to break the image, I'm afraid we need more help from an OSX expert; actually this is kind of critical as azure will remove the old image in 12 days!

**Comment by Zimmi48** [comment]
cc @MSoegtropIMC who is not yet an OSX expert but is learning about it.

**Comment by herbelin** [comment]
It seems that adding option `-fs hfs+` to the call to `hdiutil` in `dev/build/osx/make-macos-dmg.sh` would make the package work for versions of MacOS < 10.2.

If I understand the information on the web correctly, MacOS 10.4 (Mojave) uses by default a different file system, APFS, replacing the HFS+ default. APFS is recognized only from MacOS 10.2 (High Sierra).

Since the exact choice of file system does not a priori matter for the CoqIDE package, staying with HFS+ seems a good solution.

@SkySkimmer: could you try adding the option and restarting?

**Comment by ejgallego** [comment]
Thanks @herbelin @SkySkimmer ; Hugo, can you try the image at https://dev.azure.com/coq/coq/_build/results?buildId=8155&view=artifacts&type=publishedArtifacts

**Comment by herbelin** [comment]
It works!

**Comment by ejgallego** [comment]
Great, thanks a lot for all the testing @herbelin

**Pull request merged**
