### PR TITLE
Be a bit smarter when substituting letins in cbn/simpl

### PR DESCRIPTION
**Pull request by SkySkimmer**
This speeds up the example in https://github.com/coq/coq/issues/15720
but does not solve the larger algorithmic issues.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/2217482925

**Comment by SkySkimmer** [comment]
Apparently this patch didn't work for reductionops, let's try just the cbn/simpl part

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/2217649553

**Comment by SkySkimmer** [comment]
Still a bit broken but probably worth fixing
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬────────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │            CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                        │                         │                 │
│        package_name         │   NEW      OLD    PDIFF │      NEW             OLD        PDIFF │      NEW             OLD        PDIFF  │   NEW      OLD    PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼────────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  862.68   926.29  -6.87 │  3935333913103   4225568598966  -6.87 │  6523316154304   7266021017047  -10.22 │ 1147904  1145988   0.17 │   0    0    nan │
│      coq-mathcomp-character │   67.00    67.41  -0.61 │   306551105598    308460721297  -0.62 │   464608786243    464782880265   -0.04 │  829228   829152   0.01 │   0    0    nan │
│          coq-mathcomp-field │   98.57    99.13  -0.56 │   451302201272    453997623726  -0.59 │   738037591599    738962584815   -0.13 │  710772   710560   0.03 │   0    0    nan │
│                 coq-unimath │ 4249.65  4272.33  -0.53 │ 19447920308573  19548822314317  -0.52 │ 38875339079619  38979601013331   -0.27 │ 3259224  3260744  -0.05 │   0    0    nan │
│                    coq-core │  101.56   101.94  -0.37 │   400567650620    400114254179   0.11 │   442811024677    442555215664    0.06 │  280564   279560   0.36 │   0    0    nan │
│                 coq-bignums │   27.50    27.57  -0.25 │   125285499027    125358216643  -0.06 │   170976871602    171903038718   -0.54 │  468636   471660  -0.64 │   0    0    nan │
│            coq-fiat-parsers │  331.23   331.83  -0.18 │  1490404949422   1492973677769  -0.17 │  2447366973435   2449732040195   -0.10 │ 2696768  2695320   0.05 │   0    0    nan │
│                    coq-hott │  162.52   162.79  -0.17 │   737917779835    738625496331  -0.10 │  1162554974045   1163039020641   -0.04 │  617448   617368   0.01 │   0    0    nan │
│       coq-engine-bench-lite │  176.33   176.50  -0.10 │   762724159946    764538809008  -0.24 │  1490515710694   1487753264761    0.19 │ 1357292  1357920  -0.05 │   0    0    nan │
│       coq-mathcomp-fingroup │   21.44    21.46  -0.09 │    97823543031     97770368732   0.05 │   140532315400    140532100942    0.00 │  490592   488472   0.43 │   0    0    nan │
│                  coq-flocq3 │   76.49    76.53  -0.05 │   348108625417    348020533463   0.03 │   456128009226    456951287833   -0.18 │  992076   991336   0.07 │   0    0    nan │
│      coq-mathcomp-ssreflect │   24.80    24.81  -0.04 │   112988140968    112936376866   0.05 │   140134206357    140163925002   -0.02 │  536588   536348   0.04 │   0    0    nan │
│       coq-mathcomp-solvable │   79.87    79.83   0.05 │   365024798620    365610626279  -0.16 │   555858029387    555939067964   -0.01 │  666748   668624  -0.28 │   0    0    nan │
│               coq-fiat-core │   54.82    54.78   0.07 │   236309686229    235927831804   0.16 │   330751643606    330519314616    0.07 │  480044   479740   0.06 │   1    0    nan │
│        coq-mathcomp-algebra │   58.30    58.25   0.09 │   266276359446    265764845265   0.19 │   360694495073    360763593879   -0.02 │  599244   595712   0.59 │   0    0    nan │
│                   coq-color │  208.72   208.53   0.09 │   944694288966    944815171596  -0.01 │  1325430743893   1325307957311    0.01 │ 1109612  1110536  -0.08 │   0    0    nan │
│            coq-math-classes │   90.09    90.00   0.10 │   407677483424    407788838084  -0.03 │   570566524447    571429698588   -0.15 │  502024   502024   0.00 │   0    0    nan │
│                coq-coqprime │   42.24    42.18   0.14 │   191574850982    191480898965   0.05 │   282692657959    282733449331   -0.01 │  762408   764760  -0.31 │   0    0    nan │
│             coq-fiat-crypto │ 2780.76  2776.07   0.17 │ 12646661474747  12626849012346   0.16 │ 23124901454098  23223398063662   -0.42 │ 3845032  3845276  -0.01 │   0    0    nan │
│                coq-rewriter │  371.92   371.23   0.19 │  1693286051885   1690713176630   0.15 │  2765375759911   2771175022112   -0.21 │ 1060384  1060352   0.00 │   0    0    nan │
│               coq-fourcolor │ 1449.25  1445.94   0.23 │  6604708796562   6601209259353   0.05 │ 12059786844438  12072263740110   -0.10 │  792644   792780  -0.02 │   0    0    nan │
│  coq-performance-tests-lite │  771.64   769.81   0.24 │  3502635787396   3494792880099   0.22 │  5941038149453   5941510042067   -0.01 │ 1824868  1824392   0.03 │   0    0    nan │
│                    coq-corn │  753.27   751.38   0.25 │  3433066357799   3427331696184   0.17 │  5278622117668   5280400491761   -0.03 │  878600   882512  -0.44 │   0    0    nan │
│                  coq-geocoq │  691.48   689.34   0.31 │  3154289970496   3145414330259   0.28 │  4986232359519   4985887508067    0.01 │ 1077464  1077372   0.01 │   0    0    nan │
│                 coq-coqutil │   34.86    34.75   0.32 │   156280668191    156251444935   0.02 │   209229987486    209059225220    0.08 │  605896   606924  -0.17 │   0    0    nan │
│                coq-bedrock2 │  217.84   216.98   0.40 │   993871158330    989482094793   0.44 │  1785239638658   1788365367747   -0.17 │ 2051904  2051872   0.00 │   0    0    nan │
│                   coq-verdi │   47.45    47.26   0.40 │   214643977629    214517851032   0.06 │   318522834329    318695278308   -0.05 │  838656   835840   0.34 │   0    0    nan │
│               coq-perennial │ 3989.07  3972.60   0.41 │ 18214580812746  18135541258163   0.44 │ 29786148818982  29782639114093    0.01 │ 2626664  2616428   0.39 │   0    0    nan │
│      coq-mathcomp-odd-order │  525.43   523.18   0.43 │  2407563899487   2397814463142   0.41 │  4060798466831   4083459102334   -0.55 │ 1214400  1226512  -0.99 │   0    0    nan │
│              coq-verdi-raft │  558.11   554.48   0.65 │  2545692649576   2530142767920   0.61 │  3924910379060   3924724342278    0.00 │ 1257952  1260616  -0.21 │   0    0    nan │
│              coq-coquelicot │   33.34    33.11   0.69 │   149624641652    149404488766   0.15 │   196036214388    195845260868    0.10 │  758064   753876   0.56 │   4    0    nan │
│           coq-iris-examples │  416.02   413.09   0.71 │  1894420959438   1882521742045   0.63 │  2838746210444   2838675298824    0.00 │ 1186016  1182424   0.30 │   0    0    nan │
│                coq-compcert │  279.72   277.49   0.80 │  1269635661176   1259493795975   0.81 │  1888918345321   1889453554463   -0.03 │ 1106552  1107196  -0.06 │   0    0    nan │
│                     coq-vst │ 1060.01  1051.21   0.84 │  4834194928897   4796372463900   0.79 │  7708676860648   7713075143762   -0.06 │ 2113916  2140168  -1.23 │   0    0    nan │
│                  coq-stdlib │  402.36   398.39   1.00 │  1651939248232   1635326114675   1.02 │  1416594287793   1416589556544    0.00 │  611788   609024   0.45 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴────────────────────────────────────────┴─────────────────────────┴─────────────────┘
~~~

**Comment by ppedrot** [comment]
@SkySkimmer I almost have a patch for simpl to add delayed substitutions, half of this patch would be superseded.

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by SkySkimmer** [comment]
bench https://gitlab.com/coq/coq/-/jobs/2228293774

**Comment by Janno** [comment]
Not bad!

```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬────────────────────────────────────────┬──────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │            CPU instructions            │  max resident mem [KB]   │    mem faults     │
│                             │                         │                                       │                                        │                          │                   │
│        package_name         │   NEW      OLD    PDIFF │      NEW             OLD        PDIFF │      NEW             OLD        PDIFF  │   NEW      OLD    PDIFF  │ NEW  OLD   PDIFF  │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼────────────────────────────────────────┼──────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  893.69   963.46  -7.24 │  3904600750857   4210192285945  -7.26 │  6520857581149   7266928275102  -10.27 │ 1146608  1147160   -0.05 │   3    0      nan │
│                coq-compcert │  287.50   291.23  -1.28 │  1248914698031   1265453406256  -1.31 │  1876836579039   1877245543227   -0.02 │ 1105072  1105296   -0.02 │   0    9  -100.00 │
│                  coq-flocq3 │   78.90    79.75  -1.07 │   343871746326    346923335619  -0.88 │   455750377601    456766862847   -0.22 │  995688   991556    0.42 │   0    0      nan │
│         coq-category-theory │ 1689.53  1705.43  -0.93 │  7398107209837   7469506044058  -0.96 │ 15539365112424  15545756190327   -0.04 │ 1321748  1469180  -10.03 │   0    0      nan │
│      coq-mathcomp-odd-order │  543.01   547.67  -0.85 │  2381372609834   2400827437444  -0.81 │  4060781917517   4083436012068   -0.55 │ 1214340  1224616   -0.84 │   0    0      nan │
│      coq-mathcomp-ssreflect │   25.66    25.86  -0.77 │   111577912833    112609761489  -0.92 │   140320119295    140394050622   -0.05 │  538996   538792    0.04 │   0    0      nan │
│                coq-coqprime │   44.21    44.54  -0.74 │   191404119572    192676391045  -0.66 │   283175135674    283321567484   -0.05 │  761568   761592   -0.00 │   1    0      nan │
│                 coq-coqutil │   36.19    36.38  -0.52 │   155588726424    155791816873  -0.13 │   209688108208    209681902956    0.00 │  603988   604404   -0.07 │   4    4     0.00 │
│                    coq-hott │  168.68   169.43  -0.44 │   735387212168    735669182217  -0.04 │  1162592202201   1163055979244   -0.04 │  618640   619136   -0.08 │   0    0      nan │
│                     coq-vst │ 1086.70  1090.54  -0.35 │  4746822287686   4762222226462  -0.32 │  7687102129875   7691349910629   -0.06 │ 2027572  2028004   -0.02 │   1    0      nan │
│         coq-metacoq-erasure │   61.11    61.32  -0.34 │   262008673619    262326161128  -0.12 │   392576113424    392692062112   -0.03 │ 1086744  1082680    0.38 │   0    0      nan │
│            coq-fiat-parsers │  346.61   347.73  -0.32 │  1494570715015   1498071518505  -0.23 │  2449421648018   2451712140476   -0.09 │ 2694848  2694820    0.00 │   0    0      nan │
│               coq-fourcolor │ 1498.45  1503.09  -0.31 │  6556437054864   6573376932753  -0.26 │ 12059490023011  12071390434579   -0.10 │  791692   791660    0.00 │   0    0      nan │
│             coq-fiat-crypto │ 2937.42  2946.01  -0.29 │ 12814543190229  12852827689281  -0.30 │ 23318352738212  23400642012779   -0.35 │ 3830792  3830704    0.00 │  81   79     2.53 │
│     coq-metacoq-safechecker │  165.23   165.70  -0.28 │   720029494150    721813358949  -0.25 │   949297003572    949736268539   -0.05 │ 1200192  1199788    0.03 │  12    6   100.00 │
│                   coq-verdi │   48.31    48.44  -0.27 │   209699919442    209985211143  -0.14 │   313595060399    313685152205   -0.03 │  837216   838828   -0.19 │   0    0      nan │
│               coq-perennial │ 4097.23  4106.30  -0.22 │ 17920355448606  17955613080016  -0.20 │ 29787220882245  29790361949002   -0.01 │ 2633564  2634644   -0.04 │   0    0      nan │
│      coq-mathcomp-character │   69.40    69.52  -0.17 │   303933486637    304557820472  -0.20 │   464610242721    464738449287   -0.03 │  829120   833464   -0.52 │   0    0      nan │
│        coq-metacoq-template │   78.97    79.10  -0.16 │   337097243771    338052149780  -0.28 │   502711785418    503356883509   -0.13 │  939580   911404    3.09 │  29    9   222.22 │
│                coq-rewriter │  387.28   387.89  -0.16 │  1689099204350   1692512862412  -0.20 │  2762360786018   2768189701466   -0.21 │ 1060420  1060340    0.01 │   7    5    40.00 │
│    coq-metacoq-translations │   20.85    20.88  -0.14 │    90234744124     90377768763  -0.16 │   156383071259    156627412073   -0.16 │  964968   965224   -0.03 │   0    0      nan │
│  coq-performance-tests-lite │  800.61   801.73  -0.14 │  3484138976843   3488576683607  -0.13 │  5944617328239   5942736739124    0.03 │ 1826324  1824560    0.10 │   0    0      nan │
│        coq-mathcomp-algebra │   60.36    60.42  -0.10 │   263450510353    263930491350  -0.18 │   360588019447    360684944136   -0.03 │  595972   595720    0.04 │   0    0      nan │
│                 coq-bignums │   28.69    28.71  -0.07 │   125061321203    125065900968  -0.00 │   170987543491    171927867627   -0.55 │  468016   469288   -0.27 │   0    0      nan │
│              coq-coquelicot │   34.52    34.54  -0.06 │   148648418125    148547183112   0.07 │   196752401869    196755994249   -0.00 │  754456   755344   -0.12 │ 144    0      nan │
│                coq-bedrock2 │  232.02   232.13  -0.05 │  1013304376091   1014796764134  -0.15 │  1823504123432   1825779764789   -0.12 │ 2055900  2051960    0.19 │  14    2   600.00 │
│       coq-mathcomp-solvable │   82.89    82.92  -0.04 │   362753038210    363078512103  -0.09 │   555739228925    555940634683   -0.04 │  667148   665360    0.27 │   0    0      nan │
│                 coq-unimath │ 4442.81  4443.05  -0.01 │ 19454856821722  19455716327074  -0.00 │ 38945341348747  39021243970160   -0.19 │ 3258336  3258736   -0.01 │  13    2   550.00 │
│       coq-engine-bench-lite │  181.36   181.36   0.00 │   762147698159    761646530370   0.07 │  1491040963347   1491034967109    0.00 │ 1357472  1357424    0.00 │   0    0      nan │
│          coq-mathcomp-field │  102.36   102.35   0.01 │   448406126171    448694911483  -0.06 │   738014187976    739122417171   -0.15 │  710916   707960    0.42 │   0    0      nan │
│                    coq-corn │  783.09   782.81   0.04 │  3419153920555   3419418622421  -0.01 │  5279163491183   5281082643600   -0.04 │  879852   878604    0.14 │   0    0      nan │
│           coq-iris-examples │  425.49   425.19   0.07 │  1858047360401   1857210104826   0.05 │  2838565388768   2839556035407   -0.03 │ 1179156  1185168   -0.51 │  22    0      nan │
│       coq-mathcomp-fingroup │   22.21    22.18   0.14 │    97010787659     96991121929   0.02 │   140509850552    140531777873   -0.02 │  487948   487780    0.03 │   0    0      nan │
│           coq-metacoq-pcuic │  552.50   551.56   0.17 │  2411673973526   2408570383752   0.13 │  3387980484659   3388518940838   -0.02 │ 1572992  1573060   -0.00 │   1   13   -92.31 │
│                  coq-geocoq │  726.95   725.47   0.20 │  3170941782616   3165472128288   0.17 │  4990697827062   4990948252965   -0.01 │ 1076156  1076012    0.01 │   3   15   -80.00 │
│                   coq-color │  217.71   217.11   0.28 │   940976945595    940749737198   0.02 │  1324280100930   1324641028757   -0.03 │ 1151920  1151908    0.00 │   3    3     0.00 │
│            coq-math-classes │   93.35    93.06   0.31 │   405226885184    403993354325   0.31 │   570449106311    571286308779   -0.15 │  502796   501920    0.17 │   0    0      nan │
│              coq-verdi-raft │  576.57   574.49   0.36 │  2516559885472   2508240072804   0.33 │  3905145017569   3905538173800   -0.01 │ 1265016  1261648    0.27 │   0    0      nan │
│                    coq-core │  107.66   107.27   0.36 │   387195319896    387757126012  -0.14 │   442409954579    442591559849   -0.04 │  281872   280788    0.39 │   0    0      nan │
│               coq-fiat-core │   57.24    57.02   0.39 │   236022413247    235356692927   0.28 │   331603124867    331560477894    0.01 │  480076   480184   -0.02 │   6    0      nan │
│                  coq-stdlib │  415.95   413.98   0.48 │  1471436027601   1471761644757  -0.02 │  1416054239195   1426013204976   -0.70 │  594080   593244    0.14 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴────────────────────────────────────────┴──────────────────────────┴───────────────────┘
```

```
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                           TOP 25 SLOW DOWNS                                                            │
│                                                                                                                                        │
│   OLD      NEW     DIFF    %DIFF     Ln                    FILE                                                                        │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  0.0260   1.5110  1.4850  5711.54%  1506  coq-unimath/UniMath/Bicategories/DisplayedBicats/Examples/DisplayedInserter.v.html           │
│ 90.6800  92.1070  1.4270     1.57%    20  coq-fiat-crypto/src/Rewriter/Passes/NBE.v.html                                               │
│ 61.3090  62.1640  0.8550     1.39%   641  coq-unimath/UniMath/SubstitutionSystems/LiftingInitial_alt.v.html                            │
│ 12.0390  12.7380  0.6990     5.81%  1518  coq-unimath/UniMath/Bicategories/DisplayedBicats/Examples/DisplayedInserter.v.html           │
│ 59.3490  59.9120  0.5630     0.95%   820  coq-unimath/UniMath/SubstitutionSystems/LiftingInitial.v.html                                │
│ 27.2200  27.7820  0.5620     2.06%   510  coq-rewriter/src/Rewriter/Rewriter/Wf.v.html                                                 │
│ 10.0330  10.5750  0.5420     5.40%  1631  coq-unimath/UniMath/Bicategories/DisplayedBicats/Cartesians.v.html                           │
│  3.5060   3.9760  0.4700    13.41%    27  coq-fiat-crypto/src/Rewriter/Passes/ToFancyWithCasts.v.html                                  │
│ 22.3860  22.7100  0.3240     1.45%   267  coq-perennial/src/program_proof/memkv/memkv_coord_start_proof.v.html                         │
│ 28.5000  28.8230  0.3230     1.13%  1157  coq-unimath/UniMath/Bicategories/DisplayedBicats/Cartesians.v.html                           │
│  6.4460   6.7690  0.3230     5.01%  1601  coq-unimath/UniMath/Bicategories/DisplayedBicats/FiberBicategory/FiberBicategory2.v.html     │
│ 52.9850  53.3010  0.3160     0.60%   587  coq-unimath/UniMath/SubstitutionSystems/SignatureExamples.v.html                             │
│ 32.9250  33.2410  0.3160     0.96%   218  coq-fiat-crypto/src/Curves/EdwardsMontgomery.v.html                                          │
│ 17.2740  17.5820  0.3080     1.78%   388  coq-verdi-raft/raft-proofs/EndToEndLinearizability.v.html                                    │
│ 34.3850  34.6710  0.2860     0.83%   352  coq-fiat-crypto/src/Curves/Montgomery/XZProofs.v.html                                        │
│ 67.2070  67.4900  0.2830     0.42%   787  coq-vst/veric/extend_tc.v.html                                                               │
│ 26.9450  27.2220  0.2770     1.03%   510  coq-rewriter-perf-SuperFast/src/Rewriter/Rewriter/Wf.v.html                                  │
│ 32.7470  33.0210  0.2740     0.84%  1375  coq-fourcolor/theories/cfmap.v.html                                                          │
│ 29.8930  30.1660  0.2730     0.91%  1640  coq-geocoq/Tarski_dev/Ch16_coordinates_with_functions.v.html                                 │
│ 39.4070  39.6750  0.2680     0.68%   520  coq-perennial/src/program_proof/txn/twophase_refinement_proof.v.html                         │
│ 40.6220  40.8830  0.2610     0.64%   633  coq-unimath/UniMath/SubstitutionSystems/Signatures.v.html                                    │
│ 14.7080  14.9640  0.2560     1.74%   169  coq-unimath/UniMath/SubstitutionSystems/BinProductOfSignatures.v.html                        │
│ 28.7960  29.0410  0.2450     0.85%  1938  coq-unimath/UniMath/Bicategories/MonoidalCategories/ActionBasedStrongFunctorsMonoidal.v.html │
│ 38.0270  38.2610  0.2340     0.62%   445  coq-unimath/UniMath/SyntheticHomotopyTheory/Circle2.v.html                                   │
│  0.3250   0.5440  0.2190    67.38%   922  coq-category-theory/Functor/Construction/Product/Monoidal.v.html                             │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                             TOP 25 SPEED UPS                                                             │
│                                                                                                                                          │
│   OLD       NEW      DIFF     %DIFF    Ln                    FILE                                                                        │
├──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│  16.6240   14.4770  -2.1470  -12.92%   594  coq-unimath/UniMath/Algebra/GroupAction.v.html                                               │
│  67.4890   65.5010  -1.9880   -2.95%    27  coq-fiat-crypto/src/Rewriter/Passes/ToFancyWithCasts.v.html                                  │
│  49.4640   47.8630  -1.6010   -3.24%    57  coq-category-theory/Construction/Comma/Natural/Transformation.v.html                         │
│ 221.1390  219.7710  -1.3680   -0.62%   139  coq-fiat-crypto/src/UnsaturatedSolinasHeuristics/Tests.v.html                                │
│  96.7610   95.3990  -1.3620   -1.41%   803  coq-vst/veric/binop_lemmas4.v.html                                                           │
│  44.0090   43.0930  -0.9160   -2.08%   235  coq-rewriter/src/Rewriter/Rewriter/Examples/PerfTesting/LiftLetsMap.v.html                   │
│  38.8500   38.0340  -0.8160   -2.10%    96  coq-vst/veric/binop_lemmas5.v.html                                                           │
│ 127.3330  126.5220  -0.8110   -0.64%   153  coq-fiat-crypto/src/UnsaturatedSolinasHeuristics/Tests.v.html                                │
│   2.0900    1.3060  -0.7840  -37.51%   305  coq-unimath/UniMath/CategoryTheory/DisplayedCats/Constructions.v.html                        │
│  21.7330   21.1070  -0.6260   -2.88%   812  coq-perennial/src/program_proof/wal/logger_proof.v.html                                      │
│   3.8250    3.2690  -0.5560  -14.54%    18  coq-fiat-crypto/src/Language/IdentifiersBasicGENERATED.v.html                                │
│  15.7700   15.2790  -0.4910   -3.11%   132  coq-category-theory/Functor/Strong/Product.v.html                                            │
│   0.9110    0.4630  -0.4480  -49.18%   745  coq-unimath/UniMath/Bicategories/DisplayedBicats/ExamplesOfCleavings/CodomainCleaving.v.html │
│  16.1420   15.7220  -0.4200   -2.60%   320  coq-category-theory/Construction/Comma/Adjunction.v.html                                     │
│  23.5190   23.0990  -0.4200   -1.79%    93  coq-category-theory/Functor/Construction/Product/Monoidal.v.html                             │
│  26.0570   25.6440  -0.4130   -1.58%    19  coq-fiat-crypto/src/Spec/Test/X25519.v.html                                                  │
│  15.1160   14.7070  -0.4090   -2.71%    24  coq-fiat-crypto/src/Rewriter/Passes/MulSplit.v.html                                          │
│  26.0650   25.6600  -0.4050   -1.55%    24  coq-fiat-crypto/src/Spec/Test/X25519.v.html                                                  │
│  37.4050   37.0020  -0.4030   -1.08%    10  coq-fourcolor/theories/job439to465.v.html                                                    │
│ 141.4810  141.0790  -0.4020   -0.28%    47  coq-fiat-crypto/src/Curves/Weierstrass/AffineProofs.v.html                                   │
│  25.3350   24.9480  -0.3870   -1.53%    24  coq-fiat-crypto/src/Rewriter/Passes/MultiRetSplit.v.html                                     │
│   0.8910    0.5110  -0.3800  -42.65%   548  coq-fiat-crypto/src/AbstractInterpretation/ZRangeProofs.v.html                               │
│  27.5150   27.1400  -0.3750   -1.36%   233  coq-fiat-crypto/src/Curves/EdwardsMontgomery.v.html                                          │
│   0.4560    0.0850  -0.3710  -81.36%  1733  coq-unimath/UniMath/Bicategories/DisplayedBicats/Examples/DisplayedInserter.v.html           │
│ 120.8910  120.5260  -0.3650   -0.30%   992  coq-performance-tests-lite/src/fiat_crypto_via_setoid_rewrite_standalone.v.html              │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by SkySkimmer** [comment]
>`│  0.0260   1.5110  1.4850  5711.54%  1506  coq-unimath/UniMath/Bicategories/DisplayedBicats/Examples/DisplayedInserter.v.html           │`

I guess it had a hiccup, that's a rewrite call
https://github.com/UniMath/UniMath/blob/dcebb9873660e2285d346471c52312f1d05e5d82/UniMath/Bicategories/DisplayedBicats/Examples/DisplayedInserter.v#L1507
Does that even call cbn/simpl?

**Comment by Janno** [comment]
Quite a few of the lines with significant changes look like applications and rewrites. The last one I looked at is 
```
│  0.3250   0.5440  0.2190    67.38%   922  coq-category-theory/Functor/Construction/Product/Monoidal.v.html
```
and it's https://github.com/jwiegley/category-theory/blob/master/Functor/Construction/Product/Monoidal.v#L922, which is a rewrite:
```
rewrite <- bimap_comp.
```

**Comment by SkySkimmer** [comment]
Let's have another bench, if the same lines show slowdowns it may be worth looking into.
@coqbot bench

**Comment by SkySkimmer** [comment]
Not sure what to do with this, @ppedrot maybe you can decide if we should merge/close/other

**Pull request closed without merging**
