### PR TITLE
Fix debug printers

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I had a similar patch on my machine but I didn't take the time to submit it...

**Comment by ppedrot** [comment]
By the way, weren't we supposed to test this?

**Comment by ejgallego** [comment]
> By the way, weren't we supposed to test this?

The test passed due to the make-based system having a compat layer; unification of this will happen in #13617 , which is almost ready, I need to find some spare time to fix the OSX App IDE creation....

**Comment by SkySkimmer** [comment]
@ppedrot assign?

**Pull request merged**
