### PR TITLE
Define an "apply under binders" tactic

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by JasonGross** [comment]
Responding to @herbelin, since comments on individual commits go away on rebase:

> Looks pretty interesting.
>
> Could the names of the variables be kept instead of regenerated using names "x'", "x'0", etc?
>
> I would personally have tried to code it in OCaml, maybe as a tactical usable around "apply_in_once" in tactics/tactics.ml. In any case, this is a very good case study of how to program tactics.

Yes, probably; many of the quirks of this definition are due to previous bugs in Coq, which have since been fixed.  Shall I update the pull request with a version that removes the workarounds?

**Comment by herbelin** [comment]
I primarily meant in my comment that the feature provided by this patch is pretty interesting.

About the code itself, I would feel more comfortable with a code written in OCaml. 

At least, I would need some time to digest the Ltac code. As you know, whether ltac should be promoted or not for writing complex tactics is something which is under discussion.I know that ltac is the only language available coq-side at the current time, but I wonder whether the feature you are implementing could not be written in a more  appealing way. Maybe, it is just about giving some better syntax or more high-level names to the use of "solve [tac|failure]" as a try-with, or to the use of $ as some "abstract the complete subproof obtained by the given tactic as a term", or to the use of "[tac|tac' ..] as a "solve goal with tac and side-conditions with tac', I can't evaluate it at the current time.

More generally, I have to confess that I'm catching up with the way you (and Jonathan actually) suceeded to program so far with ltac, and I don't feel able to give an opinion yet on whether this is the kind of tactic programming I and other people would like to promote in coq or not (and as side questions, how robust this kind of programming is, and who would maintain your code).

As an example, destruct is leaving side conditions first while and apply in, induction and rewrite are leaving side conditions last. Shouldn't this order be stabilized before writing ltac functions relying on the assumption that side conditions come last?

**Comment by JasonGross** [comment]
> At least, I would need some time to digest the Ltac code. 

There is a version with significantly more comments here: https://github.com/HoTT/HoTT/blob/master/theories/Tactics/BinderApply.v

> As an example, destruct is leaving side conditions first while and apply in, induction and rewrite are leaving side conditions last. Shouldn't this order be stabilized before writing ltac functions relying on the assumption that side conditions come last?

Probably.  But I think there are two good (maintainable) kinds of Ltac, and anything in between them is horrible.  The first kind is specialized tactics, often with complicated code, that perform a single, well-defined task.  These tactics often are full of hacks and kludges and could probably use a much better language.  The other kind of tactic is your standard automation, which, I think, should ideally take the form of a `repeat match goal with` and do nothing complicated in any branch; it should really just be doing things by brute force, perhaps with some backtracking.  The former are sensitive to things like side-goal order and such, but the fact that their goal is precisely specified should make them maintainable.  The latter should, ideally, be largely insensitive to changes in the tactic engine, and should not require any deep thought to fix.

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
This tactic seems interesting, but the development team unfortunately does not feel like maintaining its Ltac implementation, since it uses features that are themselves unstable (e.g. tactics in terms). We would be more willing to integrate it if written in ML.

**Pull request closed without merging**
