### PR TITLE
Simplify Evarconv.occurence_match_test

### PR DESCRIPTION
**Pull request by SkySkimmer**
The removed arguments were not used

### CODE REVIEW

**Comment by ppedrot** [comment]
Isn't this used by unicoq though?

**Comment by SkySkimmer** [comment]
CI says it's not

**Review by ppedrot — APPROVED** [review]
Fine with me but you need to be sure that this was not a conscious design choice.

**Comment by ppedrot** [comment]
@mattam82 can you confirm that this is fine?

**Comment by ppedrot** [comment]
I think I'll merge this, it's a simple fix that can be rolled back easily if there is any problem.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
