### PR TITLE
update-compat --release for 8.19

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
As usual fiat-parsers needs a change
cc @JasonGross

**Comment by JasonGross** [comment]
Sorry, I thought I had future-proofed against this change, but the future proofing was accidentally lost in https://github.com/JasonGross/coq-scripts/pull/11 adapting to https://github.com/coq/coq/pull/17977.  This should work once https://github.com/mit-plv/fiat/pull/102 auto-merges, hopefully within the next hour.  (And future version bumps should not require updates to fiat-parsers anymore, which no longer attempts to pull in the Compat file)

**Comment by SkySkimmer** [comment]
ping @coq/compat-maintainers

**Comment by SkySkimmer** [comment]
ping @coq/compat-maintainers

**Comment by SkySkimmer** [comment]
ping @JasonGross @Zimmi48

**Review by JasonGross — APPROVED** [review]
Sorry for the delay

**Comment by SkySkimmer** [comment]
So are you merging?

**Comment by JasonGross** [comment]
@coqbot merge now

**Pull request merged**
