### PR TITLE
[api] Remove (most) 8.9 deprecated objects.

### PR DESCRIPTION
**Pull request by ejgallego**
A few of them will be of help for future cleanups. We have spared the
stuff in `Names` due to bad organization of this module following the
split from `Term`, which really difficults things removing the
constructors.

### CODE REVIEW

**Comment by ejgallego** [comment]
As expected most plugins need some fixing. Unfortunately we didn't deprecate the constructors of some types we'd like to get rid of. That's a bit of work, but should be done before 8.9. See #8498

**Review by ppedrot — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]
Goodbye universes.ml

**Comment by SkySkimmer** [comment]
Shouldn't this be `kind: cleanup` rather than `kind: compatibility`?

**Review by herbelin — COMMENTED** [review]
OK to me

**Comment by ejgallego** [comment]
List of issues that this PR depends on:
- https://github.com/mit-plv/fiat/issues/14
- https://github.com/ppedrot/ltac2/issues/73
- https://github.com/Mtac2/Mtac2/issues/109
- https://github.com/QuickChick/QuickChick/issues/106
- https://github.com/LPCIC/coq-elpi/issues/29

**Comment by ejgallego** [comment]
@Zimmi48 @coqbot in incorrect here.

**Comment by Zimmi48** [comment]
Was it? But then what did you do to help him remove the label? It would be helpful if next time this happens you let me inspect the state before rebasing or you give me some more details on the commit hashes.

**Comment by ejgallego** [comment]
> Was it? But then what did you do to help him remove the label? It would be helpful if next time this happens you let me inspect the state before rebasing or you give me some more details on the commit hashes.

I just re-pushed the same commit with a different hash. I didn't find the info very interesting, just a commit on top of 5424ad236574e22a7ef2dce0d1d9468a9b768a16

**Comment by Zimmi48** [comment]
OK thanks for the additional info.

**Comment by ejgallego** [comment]
Ok, so this is finally ready to go! Needs an assignee, not a complicated PR.

All the proper deprecation notices are in 8.9 [except for record fields that cannot be deprecated] and this is a requisite of #6171 .

**Comment by bollu** [comment]
@ejgallego does this need some sort of sweeping understanding of the changes? If it's mostly mechanical, I'm happy to help :)

**Comment by ppedrot** [comment]
I'll merge when CI finishes.

**Comment by ejgallego** [comment]
> I'll merge when CI finishes.

TIA @ppedrot

**Comment by ejgallego** [comment]
Rebasing due to a conflict :S

**Comment by ejgallego** [comment]
Another conflict.

**Pull request merged**
