### PR TITLE
Document intuition_solver for 8.15

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I didn't notice that a doc change was needed for https://github.com/coq/coq/pull/15866
I guess it's not worth a 8.15.3 but we should be able to fix the online manual @Zimmi48

**Comment by SkySkimmer** [comment]
cc also @ppedrot for 8.16

**Review by jfehrle — APPROVED** [review]

**Comment by jfehrle** [comment]
@coqbot: merge

**Comment by jfehrle** [comment]
@coqbot: merge now

**Comment by jfehrle** [comment]
I'll let you guys do the merge.

**Comment by Zimmi48** [comment]
@ppedrot Watch out that this PR targets v8.15. Thus the 8.16.0 milestone isn't really going to help (e.g., with backporting). Was another PR opened for master?

**Comment by Zimmi48** [comment]
@SkySkimmer If you want, we can copy the content of https://github.com/coq/doc/tree/master/v8.15/refman to https://github.com/coq/doc/tree/master/V8.15.2/refman.

**Comment by SkySkimmer** [comment]
sounds good

**Comment by Zimmi48** [comment]
Then, @ppedrot, given that the latter is an 8.17-PR, you will need to manually port this one to v8.16.

**Pull request merged**
