### PR TITLE
Refresh universes in apply tactic

### LINKED ISSUE #8310: Anomaly "Unable to handle arbitrary u+k <= v constraints" w/ universes
#### Version

8.8.1

#### Operating system

Linux

#### Description of the problem

(* Not sure if this is a duplicate but.. *)

Check ltac:(let U := constr:(Type) in apply U).

(* Conversion test raised an anomaly:
Anomaly "Unable to handle arbitrary u+k <= v constraints."

Note: You get the anomaly w/ apply, eapply and eexact; w/ exact and refine it works *)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #8310

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Does NOT fix https://github.com/coq/coq/issues/4632

**Comment by SkySkimmer** [comment]
bench https://gitlab.com/coq/coq/-/jobs/1647238740

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I am a bit surprised that we don't see anything in the bench, but let's be positive.

**Comment by Alizter** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  181.44   183.87  -1.32 │   762040549140    772766982789  -1.39 │  1478712108473   1483746175192  -0.34 │ 1409240  1410912  -0.12 │   0    0      nan │
│                    coq-core │  102.34   103.20  -0.83 │   378316662150    377181383284   0.30 │   434876208170    435194774986  -0.07 │  246248   246176   0.03 │   0    0      nan │
│                 coq-coqutil │   32.10    32.23  -0.40 │   138653373376    138952159575  -0.22 │   181966767510    181968307545  -0.00 │  601236   604012  -0.46 │   0    0      nan │
│                   coq-color │  269.84   270.66  -0.30 │  1175029581751   1176178902268  -0.10 │  1594110938105   1593827744922   0.02 │ 1240364  1239872   0.04 │   0    0      nan │
│              coq-coquelicot │   35.58    35.65  -0.20 │   153452584496    153747631142  -0.19 │   200463861208    200353757489   0.05 │  751392   751252   0.02 │  38   10   280.00 │
│            coq-fiat-parsers │  342.05   342.52  -0.14 │  1480208714974   1481545925050  -0.09 │  2440333041635   2439118817756   0.05 │ 3548388  3547124   0.04 │   0    8  -100.00 │
│      coq-mathcomp-character │   80.50    80.61  -0.14 │   352434901064    353208751051  -0.22 │   540160023885    540112663765   0.01 │  742192   736460   0.78 │   0    0      nan │
│       coq-mathcomp-solvable │   93.14    93.26  -0.13 │   407867527676    408150344769  -0.07 │   630104808178    630099942211   0.00 │  663444   664684  -0.19 │   0    0      nan │
│      coq-mathcomp-ssreflect │   26.32    26.35  -0.11 │   114891952268    114703243989   0.16 │   145458248319    145438122063   0.01 │  529660   530764  -0.21 │   0    0      nan │
│      coq-mathcomp-odd-order │  606.32   606.97  -0.11 │  2658058804612   2660510345660  -0.09 │  4525396399528   4524487455051   0.02 │  942532   935184   0.79 │   0    0      nan │
│        coq-mathcomp-algebra │   75.68    75.72  -0.05 │   331199168868    331455163075  -0.08 │   467782857558    467829111350  -0.01 │  557932   561240  -0.59 │   0    0      nan │
│       coq-mathcomp-fingroup │   24.26    24.26   0.00 │   105887093039    106146493842  -0.24 │   156803977694    156739395361   0.04 │  479940   478788   0.24 │   0    0      nan │
│              coq-verdi-raft │  600.18   600.06   0.02 │  2621189355243   2620321395629   0.03 │  4039619272554   4032416419230   0.18 │ 1217992  1221940  -0.32 │   0    0      nan │
│          coq-mathcomp-field │  121.51   121.47   0.03 │   532124913145    532305065722  -0.03 │   875025909338    874685506716   0.04 │  661724   661616   0.02 │   0    0      nan │
│                   coq-verdi │   50.34    50.25   0.18 │   218631265358    218277060915   0.16 │   325692125472    325392579573   0.09 │  830344   831160  -0.10 │   0    3  -100.00 │
│               coq-perennial │ 3773.83  3766.69   0.19 │ 16505053231854  16477749950205   0.17 │ 27484298469585  27482378312693   0.01 │ 2702036  2699968   0.08 │   1    1     0.00 │
│                 coq-unimath │ 2784.90  2779.35   0.20 │ 12191954896903  12167787327971   0.20 │ 24264841718851  24265309263936  -0.00 │ 3807676  3831368  -0.62 │  13    5   160.00 │
│                  coq-geocoq │  746.88   744.83   0.28 │  3260439951362   3252718810335   0.24 │  5154037762943   5151914048026   0.04 │  976872   977136  -0.03 │   0    0      nan │
│               coq-fourcolor │ 1501.23  1496.95   0.29 │  6569279817139   6548099322270   0.32 │ 11955343029528  11955031099748   0.00 │  730224   730348  -0.02 │   0    0      nan │
│             coq-fiat-crypto │ 2879.75  2871.35   0.29 │ 12568537782453  12532049292271   0.29 │ 23140915967363  23135633761217   0.02 │ 2423020  2422972   0.00 │  25   32   -21.88 │
│             coq-lambda-rust │  668.27   666.15   0.32 │  2923785333451   2913984297206   0.34 │  4579325390912   4575058399401   0.09 │ 1070172   994320   7.63 │   5    0      nan │
│            coq-math-classes │   96.50    96.15   0.36 │   419228767912    418594567809   0.15 │   590693117053    590421758012   0.05 │  496020   495936   0.02 │   0    0      nan │
│                coq-coqprime │  188.81   188.06   0.40 │   826406903326    822828419761   0.43 │  1562190532388   1561996435532   0.01 │  831512   831512   0.00 │   0    0      nan │
│                    coq-corn │  829.91   826.02   0.47 │  3627529881340   3610560289492   0.47 │  5610138670033   5608478812059   0.03 │  828212   830380  -0.26 │   0    0      nan │
│                 coq-bignums │   29.70    29.56   0.47 │   129414191142    128813722329   0.47 │   176842472007    176724400739   0.07 │  466296   466668  -0.08 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  934.12   929.66   0.48 │  4082103004605   4063687101197   0.45 │  6981296293597   6980236985818   0.02 │ 1149816  1151648  -0.16 │   9   11   -18.18 │
│                coq-rewriter │  391.57   389.65   0.49 │  1709358471594   1700240922382   0.54 │  2794125208551   2790710522551   0.12 │ 1066488  1065580   0.09 │   0    0      nan │
│               coq-fiat-core │   55.75    55.45   0.54 │   233445112018    233190421990   0.11 │   323547134705    323250456027   0.09 │  474536   474168   0.08 │   0    0      nan │
│  coq-performance-tests-lite │  848.44   843.58   0.58 │  3693285010497   3671814605398   0.58 │  6228958990327   6229018346665  -0.00 │ 2064440  2064568  -0.01 │   2    0      nan │
│                coq-bedrock2 │  176.83   175.79   0.59 │   772537709165    768764422768   0.49 │  1432023442026   1431224214310   0.06 │  790044   790832  -0.10 │   1    0      nan │
│                    coq-hott │  160.21   159.25   0.60 │   693738643826    690275450304   0.50 │  1086736817744   1086448401513   0.03 │  659112   660180  -0.16 │   0    0      nan │
│                  coq-stdlib │  414.48   411.89   0.63 │  1477740868310   1470932174413   0.46 │  1426032526240   1425605886640   0.03 │  593252   591148   0.36 │   0    0      nan │
│                   coq-flocq │   77.60    76.94   0.86 │   338160393754    335692670174   0.74 │   446127499489    445788787896   0.08 │  995472   994504   0.10 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Comment by silene** [comment]
The code is way too different between 8.14 and master for me to reconcile the changes.

**Comment by SkySkimmer** [comment]
Looks pretty similar, the merge conflict is just that `thm_ty0` is renamed to `thm_ty` by the patch.

**Comment by silene** [comment]
> the merge conflict is just that `thm_ty0` is renamed to `thm_ty` by the patch.

But in doing so, it shadows a preexisting `thm_ty` variable. So, I am not sure how I am supposed to proceed. Is the shadowing on purpose? Or should I change the variable name back to `thm_ty0`?

**Comment by SkySkimmer** [comment]
There is no preexisting thm_ty variable AFAICT, the code looked like
~~~ocaml
let thm_ty0 = stuff in 
let f thm_ty = stuff not using thm_ty0 in 
stuff using thm_ty0
~~~
so the name change makes it obvious that the surrounding `thm_ty` is not used in `f` (without having to look at the body of `f`)

**Comment by silene** [comment]
I get your point. But put yourself in my shoes. When you see the following merge conflict, does it look that obvious to you?
```diff
@@@ -1651,15 -1787,16 +1651,16 @@@ let general_apply ?(respect_opaque=fals
        if respect_opaque then Conv_oracle.get_transp_state (oracle env)
        else TransparentState.full
      in
      let flags =
        if with_delta then default_unify_flags () else default_no_delta_unify_flags ts in
-     let thm_ty0 = nf_betaiota env sigma (Retyping.get_type_of env sigma c) in
+     let thm_ty = nf_betaiota env sigma (Retyping.get_type_of env sigma c) in
+     let sigma, thm_ty = Evarsolve.refresh_universes ~onlyalg:true None env sigma thm_ty in
      let try_apply thm_ty nprod =
        try
          let n = nb_prod_modulo_zeta sigma thm_ty - nprod in
 -        if n<0 then error NotEnoughPremises;
 +        if n<0 then error "Applied theorem does not have enough premises.";
          let clause = make_clenv_binding_apply env sigma (Some n) (c,thm_ty) lbind in
          Clenv.res_pf clause ~with_evars ~flags
        with exn when noncritical exn ->
          let exn, info = Exninfo.capture exn in
          Proofview.tclZERO ~info exn
@@@ -1679,34 -1813,28 +1680,44 @@@
              second order unification *)
          let exn, info = Exninfo.capture exn in
          let info = Option.cata (fun loc -> Loc.add_loc info loc) info loc in
          let tac =
            if with_destruct then
 -            Proofview.tclORELSE
 -              (descend_in_conjunctions Id.Set.empty
 -                (fun _ b id ->
 -                  Tacticals.New.tclTHEN
 -                    (try_main_apply b (mkVar id))
 -                    (clear [id]))
 -                (exn0, info) c)
 -              (fun _ -> Proofview.tclZERO ~info exn0)
 +            descend_in_conjunctions Id.Set.empty
 +              (fun _ b id ->
 +                Tacticals.New.tclTHEN
 +                  (try_main_apply b (mkVar id))
 +                  (clear [id]))
 +              (exn0, info) c
            else
              Proofview.tclZERO ~info exn0 in
          if not (Int.equal concl_nprod 0) then
 -          Tacticals.New.tclORELSE0 (try_apply thm_ty 0) tac
 +          tclORELSEOPT
 +            (try_apply thm_ty 0)
 +            (function (e, info) -> match e with
 +            | PretypeError _|RefinerError _|UserError _|Failure _->
 +              Some tac
 +            | _ -> None)
          else
            tac
      in
  <<<<<<< HEAD
 +    tclORELSEOPT
 +      (try_apply thm_ty0 concl_nprod)
 +      (function (e, info) -> match e with
 +      | PretypeError _|RefinerError _|UserError _|Failure _ ->
 +        Some (try_red_apply thm_ty0 (e, info))
 +      | _ -> None)
  ||||||| parent of 556a5c5f00... Refresh universes in apply tactic
--    Proofview.tclORELSE
--      (try_apply thm_ty0 concl_nprod)
--      (try_red_apply thm_ty0)
  =======
+     Proofview.tclORELSE
+       (try_apply thm_ty concl_nprod)
+       (try_red_apply thm_ty)
  >>>>>>> 556a5c5f00... Refresh universes in apply tactic
      end
    in
      Tacticals.New.tclTHEN
        (try_main_apply with_destruct c)
        (apply_clear_request clear_flag (use_clear_hyp_by_default ()) c)
```

**Comment by SkySkimmer** [comment]
I didn't remember this PR so I did look at the conflict and it felt pretty obvious tbh

**Pull request merged**
