### PR TITLE
Remove the bfs implementation from eauto

### PR DESCRIPTION
**Pull request by ppedrot**
We remove the corresponding code in the implementation and simplify the API. The Explore module has also been inlined in the two only callers in view of the change of implementation of eauto based on the new tactic engine.

### CODE REVIEW

**Comment by ppedrot** [comment]
I will wait for #15323 to be merged before fixing this one since it interacts with it at the documentation level.

**Review by jfehrle — APPROVED** [review]

**Comment by ppedrot** [comment]
The overlay will need a rebase after the merge of https://github.com/lukaszcz/coqhammer/pull/116 to work properly.

**Comment by SkySkimmer** [comment]
I don't see a conflict

**Comment by SkySkimmer** [comment]
(recall https://github.com/coq/coq/pull/13177)

**Comment by ppedrot** [comment]
Not sure what this PR is supposed to do, but upstream is missing the patch that should make it work on master. Since the overlay I wrote is just for this PR, AFAIU the CI will fail on this run.

**Comment by ppedrot** [comment]
CI green, this is ready.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
merging soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
