### PR TITLE
Stop sharing universes in interp_context

### PR DESCRIPTION
**Pull request by SkySkimmer**
On top of https://github.com/coq/coq/pull/19276

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
CI was green at https://gitlab.inria.fr/coq/coq/-/pipelines/996891 before adding the changelog

**Comment by ppedrot** [comment]
Are we sure this doesn't interfere with the change in template typing rules? Just in case I think another CI doesn't hurt. @coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Will merge soon if no complaints.

**Pull request merged**
