### PR TITLE
Remove badly supported and broken cram tests

### PR DESCRIPTION
**Pull request by SkySkimmer**
As as been said multiple times, these tests are not properly integrated with the test suite and can result in very confusing outut `NO FAILURES` followed by failure code.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Also these specific tests are broken so we can see the confusing output in the CI for the PR which introduced them: https://gitlab.inria.fr/coq/coq/-/jobs/3676723

**Comment by SkySkimmer** [comment]
This stuff also managed to break the opam packages: trying to install coq-core with tests on produces 
~~~
# Error: No rule found for theories/extraction/Extraction.vo
# -> required by alias test-suite/cram/runtest
# Error: No rule found for theories/Arith/PeanoNat.vo
# -> required by alias test-suite/cram/runtest
~~~

**Review by herbelin — APPROVED** [review]
Approving in urgency (leaving discussions for later if needed).

**Comment by herbelin** [comment]
@coqbot merge now

**Comment by herbelin** [comment]
@coqbot merge now

**Comment by ejgallego** [comment]
It is easy to keep the tests (and fix the problems pointed out by @SkySkimmer ) if you folks would like to do so.

**Comment by herbelin** [comment]
> It is easy to keep the tests (and fix the problems pointed out by @SkySkimmer ) if you folks would like to do so.

I'm not in position to judge what we would like to do, but I'd be happy to hear about the different ins and outs.

**Comment by ejgallego** [comment]
I guess the main point is if we think the tests are useful, if so, fixing them is easy:
- `dune promote` will update the cram `run.t` files for any changed output
- we must attach the cram tests to the right package (coq, not coq-core)

That would fix the two most pressing issues. Also, we want to tweak what `dune runtest` does, by separating `runtest` from the cram setup, and runs the dune native tests and the test-suit separately, and in the right order, using two aliases.

**Comment by ejgallego** [comment]
I am still very convinced that Ali's work on porting the test-suite for Dune would produce huge savings in developer time and maintenability.

**Comment by herbelin** [comment]
Sorry again for my ignorance on the matter, but what is the status of porting the test-suite to Dune?

**Pull request merged**
