### PR TITLE
Remove pkg:opam job (redundant with pkg:opam:native)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
How are they redundant? I think they test different code paths in configure / build ?

**Comment by SkySkimmer** [comment]
Because I don't think pkg:opam is at risk of being the only job to fail

**Comment by ejgallego** [comment]
> Because I don't think pkg:opam is at risk of being the only job to fail

I dunno, I know the code and I'm not sure; but that's very subjective, indeed, it is very unlikely we break that, except when we will break it.

Note that I think that if you remove this, all codepaths in CI pass `-native-compiler yes`, except for the dev build, so if that's the case, IMHO this PR could be a problem.

But indeed I'm happy to merge this PR, after all a tradeoff has to be made in terms of exhaustiveness of CI.

**Comment by SkySkimmer** [comment]
As long as we keep the dev build it should be fine imo

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
