### PR TITLE
stdlib Arith: remove use of files mentioned as (mostly) obsolete

### PR DESCRIPTION
**Pull request by olaure01**
This is a tentative of clarifying the different uses of properties of `nat` in the standard library by relying mostly on Arith.PeanoNat and not anymore on files mentioned to be (mostly) obsolete such as Arith.Plus Arith.Le Arith.Even, etc. and thus also (by transitivity) Arith.Arith_base and Arith.Arith for example.

I am not sure this is really useful, but it could lead to a more formal deprecation of some old parts of stdlib dealing with (natural) numbers.

### CODE REVIEW

**Comment by olaure01** [comment]
@coq/stdlib-maintainers I would be happy to have some feedback (not formal reviews) whether this cleaning proposal is meaningful or not?

**Comment by Zimmi48** [comment]
GitHub restricts who can ping a team. So let me ping them for you @coq/stdlib-maintainers, then invite you to our `@coq/contributors` team (not @-mentioning this one on purpose :stuck_out_tongue_closed_eyes:) so that you get the permissions to request reviews / set labels / ping teams.

**Comment by olaure01** [comment]
Perfect, thanks!

**Comment by herbelin** [comment]
I apparently missed this PR when it arrived, sorry.

What it tries to do is not an easy task!

There are apparently 3 kinds of change:
- use of standardized names such as `Nat.add_assoc`
- getting rid of `auto with arith`
- some modules renaming (such as `Arith` -> `PeanoNat`, `ZArith` -> `BinInt`, or not including `Le` any more, etc.)

I have no doubt that the first one is desired and possible with little costs (the remaining `plus_Sn_m` could even be changed into `Nat.add_succ_l`, with a rewriting in the other direction).

For the second, I'm afraid of the incompatibilities it would imply. Calling `auto with arith` is very popular, so I don't see how it could really be avoided. At the same time, this may be an opportunity to rethink at the automatisation for `Arith`. I wonder what specialists of `auto` and hints think (@ppedrot, @mattam82): should we just preserve the existing (up to a renaming of lemmas), or aim at something different?

For the third, I agree about not requiring `Le` explicitly any more. I don't have an opinion about calling `PeanoNat` or `BinInt` rather than `Arith` or `ZArith`. I find the later rather simple and intuitive, but maybe it is also misleading? Shortly, unless there is a good argument to avoid them, I would lean to keep these main entry names to the `nat` and `Z` libraries.

**Comment by olaure01** [comment]
@herbelin It is probably my fault if you missed it: I made it a draft PR since it is not stabilized (maybe it is not the best way to do). Thanks for your comments anyway.

* Point 1.
You are right about `plus_Sn_m`. I kept it because it comes from `Init.Peano` not from one of the obsolete files I am trying to avoid. But it is even more natural to avoid it as well.

* Point 2.
The database `arith` is mainly populated by statements from the obsolete files. I see at least two possibilities here:
  * getting rid of it as done in the present PR (at least for stdlib) but it is probably a too drastic approach unless one considers `lia` to be the appropriate way of solving this kind of goals (I am not expert enough to see the consequences of this in terms of expressiveness, efficiency, etc.);
  * replace the `arith` declarations by their analogue with `Nat.xxx` statements. I imagine this would probably have almost no impact on `auto with arith` while getting read of the obsolete files.

* Point 3.
Why not keeping `Arith` indeed, if the 3 levels of the current hierarchy `PeanoNat` < `Arith_base` < `Arith` are meaningful. Are there strong reasons for these 3 levels? (these many entry-points are part of what makes the arithmetic part of stdlib difficult to grasp for me).
If `Arith` and `Arith_base`, etc. are kept, the point is then to clean them from their depencies over obsolete components.

**Comment by herbelin** [comment]
About point 2: I don't have a strong opinion.

Maybe suggesting `lia`, or `lra`, or`ring` is indeed a rather natural solution from the user point of view. As far as I'm concerned, I would have blindly gone for the simplicity and just rename the hints using the `Nat.xxx` analogues, but maybe this is just reasoning with an old model and missing an opportunity of doing better, so I'm not against experimenting other solutions.

About point 3: from the user point of view, the `Arith_base` should indeed be probably be skipped as it mostly adds noise.

> these many entry-points are part of what makes the arithmetic part of stdlib difficult to grasp for me

The [stdlib](`https://coq.inria.fr/distrib/current/stdlib/) web page (whose template is actually in `doc/stdlib/index-list.html.template`) probably needs some care actually...

**Pull request closed without merging**
