### PR TITLE
Small cleanup wrt attributes_of_flags and template attribute

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Requesting attention @mattam82 or @maximedenes

**Comment by SkySkimmer** [comment]
This type/function pair is a remnant of the original attribute system. We reduce its exposure in anticipation of removing it someday.

**Comment by SkySkimmer** [comment]
@maximedenes ping

**Comment by maximedenes** [comment]
@vbgl Would you mind reviewing this one?

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
I think that CI failures reveal a design issue in our CI process, but not an issue in this PR. Merging.

**Pull request merged**
