### PR TITLE
template_universes don't duplicate level data

### PR DESCRIPTION
**Pull request by SkySkimmer**
only store whether that argument binds the universe, which can be gotten from its type through syntactic destArity.

Overlays:
- https://github.com/coq-community/paramcoq/pull/126

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer this needs a rebase, and I think in any case that it should probably go after #19262.

**Comment by SkySkimmer** [comment]
>this needs a rebase

It doesn't

**Comment by ppedrot** [comment]
Well, it probably breaks the tweaks I wrote in paramcoq so I think that it would be better to rebase so that we clearly express some implicit changes relied upon from the outside.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
