### PR TITLE
[ci] [circleci] Remove jobs done in Gitlab efficiently.

### PR DESCRIPTION
**Pull request by ejgallego**
Following the migration to Gitlab (#6919) we reduce Circle load, see
also discussion in #7436 and #7482 .

### CODE REVIEW

**Review by SkySkimmer — COMMENTED** [review]
Why not go all the way and remove circle?

**Comment by ejgallego** [comment]
> Why not go all the way and remove circle?

Eventually we may do that I guess, but I'd like to go step by step. Gitlab still needs more testing IMO, so it is good the leave the fallbacks in place for now.

**Comment by ejgallego** [comment]
This just reduces the load on circle a lot so overall latency should improve.

**Comment by SkySkimmer** [comment]
It reduces the load a lot because there isn't much left, so in what way is it a fallback?

**Comment by ejgallego** [comment]
> It reduces the load a lot because there isn't much left, so in what way is it a fallback?

We still build Coq and a few contribs there; so that's an extra sanity check.

**Comment by ejgallego** [comment]
We will eventually drop it, but for this kind of stuff I like to go slooow.

**Comment by ejgallego** [comment]
slooow = let's have Gitlab do a few more thousand builds and then we'll see.

**Comment by ejgallego** [comment]
Another heavy dependency that's not properly captured in Circle is math-comp. But again I dunno what to do in Gitlab, using stages would be bad for latency, but indeed maybe that's the best after all.

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
