### PR TITLE
Remove many unsafe_type_of uses

### PR DESCRIPTION
**Pull request by SkySkimmer**
This leaves the ones in coercion.ml (see https://github.com/coq/coq/pull/10204) and about a quarter hundred uses in the Fun Induction plugin.

I tried to use retyping when reasonable and may have made mistakes both by using it when I shouldn't and by not using it when I could have.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Also I made quite small commits so if there's an issue it should be easy to bisect.

**Comment by SkySkimmer** [comment]
Passed CI first time, nice
Bench should start as 850

**Comment by SkySkimmer** [comment]
Also removed the funind uses.

**Comment by Matafou** [comment]
Not really able to guess the consequences of this change. We will see the result of tests.
Is unsafe_type_of going to be disabled?

**Comment by SkySkimmer** [comment]
yes

Gaëtan Gilbert

**Review by gares — APPROVED** [review]
wrt pretyping

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/850/console
~~~
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-performance-tests │   11.64   12.10 -3.80 % │       31798155428       33306046495 -4.53 % │       54779016720       57372240776 -4.52 % │     444368     462296  -3.88 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  116.30  118.36 -1.74 % │      319900558834      327395695014 -2.29 % │      416451470219      426838917470 -2.43 % │     540424     538468  +0.36 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  552.18  561.00 -1.57 % │     1533686340579     1556771435595 -1.48 % │     2365517786380     2393616786143 -1.17 % │     986236     994652  -0.85 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1259.47 1276.73 -1.35 % │     3510925048600     3562310587068 -1.44 % │     4959154149973     5033581726965 -1.48 % │    1828444    1820000  +0.46 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  208.20  210.73 -1.20 % │      576764955572      583103102564 -1.09 % │      966741977237      976803835040 -1.03 % │    1114804    1114764  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   48.88   49.47 -1.19 % │      134453653414      134790229820 -0.25 % │      175959250062      175899890013 +0.03 % │     568712     567316  +0.25 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   56.84   57.17 -0.58 % │      158369551823      159191302043 -0.52 % │      202149305762      204907317462 -1.35 % │     525460     537372  -2.22 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1524.74 1532.06 -0.48 % │     4252241754164     4273455354186 -0.50 % │     6517478215043     6515997858609 +0.02 % │    1376308    1382788  -0.47 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1528.88 1534.81 -0.39 % │     4258443860800     4275788582892 -0.41 % │     6171839349468     6177429709835 -0.09 % │    1124408    1132364  -0.70 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   49.01   49.19 -0.37 % │      136165744562      136419377524 -0.19 % │      189736912306      189765029263 -0.01 % │     557460     557456  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  674.76  676.96 -0.32 % │     1880943631355     1887595870262 -0.35 % │     2644909182519     2651057344648 -0.23 % │    1039020    1038696  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  651.33  653.39 -0.32 % │     1818960627172     1823618819573 -0.26 % │     2318694640040     2323598520512 -0.21 % │    1141716    1124312  +1.55 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  102.34  102.57 -0.22 % │      289653740631      290833371811 -0.41 % │      388631733662      389388046620 -0.19 % │     498284     497688  +0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-fiat-crypto-legacy │ 6021.87 6033.72 -0.20 % │    16772498841375    16807645852358 -0.21 % │    28594340666081    28658478169917 -0.22 % │    2413532    2368568  +1.90 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  205.99  206.26 -0.13 % │      573365756221      574364953913 -0.17 % │      769675033899      769650233596 +0.00 % │     517424     518552  -0.22 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  175.62  175.85 -0.13 % │      489146801230      489541351063 -0.08 % │      696969187774      696951661430 +0.00 % │     793468     793136  +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4208.98 4212.27 -0.08 % │    11689858343096    11697159578525 -0.06 % │    19279665751181    19331958214853 -0.27 % │    2367000    2359192  +0.33 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   84.06   84.12 -0.07 % │      231779512691      232116594170 -0.15 % │      335335808116      335485335797 -0.04 % │     757444     756828  +0.08 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  198.48  198.56 -0.04 % │      551246489363      551836125316 -0.11 % │      714405899260      715111174974 -0.10 % │     927176     927152  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1340.68 1341.08 -0.03 % │     3736718015092     3738837290713 -0.06 % │     6725580958627     6724911569141 +0.01 % │    1294908    1295360  -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  599.46  599.59 -0.02 % │     1677321858575     1678343482787 -0.06 % │     2691409995106     2697655850153 -0.23 % │    3196844    3192996  +0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4024.28 4024.08 +0.00 % │    11207543183527    11210645412775 -0.03 % │    21443791427284    21437927328787 +0.03 % │     982728    1112260 -11.65 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  163.92  163.88 +0.02 % │      455894859767      455851583911 +0.01 % │      638631213814      638578780867 +0.01 % │     804788     805340  -0.07 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1424.62 1423.63 +0.07 % │     3969605994409     3966632914223 +0.07 % │     6156771261885     6157940013991 -0.02 % │     870992     871376  -0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  262.34  262.09 +0.10 % │      730603879627      730315341582 +0.04 % │     1123480643706     1123402062141 +0.01 % │     790260     790320  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   73.72   73.64 +0.11 % │      202165143627      201940552628 +0.11 % │      267035582588      266962216152 +0.03 % │     654388     655220  -0.13 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1057.54 1055.44 +0.20 % │     2946092527479     2939971068033 +0.21 % │     4728911830391     4728020156738 +0.02 % │     930496     930452  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   63.23   62.97 +0.41 % │      174879490905      174348700334 +0.30 % │      244357577839      244360219958 -0.00 % │     483168     483156  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  335.05  333.38 +0.50 % │      911060066303      907898223821 +0.35 % │     1468462361348     1468361568073 +0.01 % │     650408     650328  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-sf-plf │   43.85   43.60 +0.57 % │      121771591498      122029570338 -0.21 % │      168347147065      169092789292 -0.44 % │     493396     494944  -0.31 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  146.24  145.35 +0.61 % │      405830011230      405516266772 +0.08 % │      538855709108      538836086235 +0.00 % │     614232     610364  +0.63 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2106.05 2091.62 +0.69 % │     5877147091619     5836543730062 +0.70 % │    11490197934391    11489809844150 +0.00 % │     952808     952420  +0.04 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
~~~

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Funind delenda est.

**Comment by ppedrot** [comment]
CI passes and bench shows an actual enhancement. I'll let a bit of time for additional comments, but essentially up to a squash this looks ready to me. @SkySkimmer can you perform it?

**Comment by Matafou** [comment]
Funind needs to be subsumed by Equations before being removed IMHO, because it has users. Sadly it is not yet the case. Hopefully I may have time to help on this in the following months.

**Review by Matafou — APPROVED** [review]

**Comment by herbelin** [comment]
> Funind needs to be subsumed by Equations before being removed IMHO, because it has users. Sadly it is not yet the case. Hopefully I may have time to help on this in the following months.

Thierry M. (SED Inria Paris) promised to help on this in the forthcoming year. I can put you in touch.

**Comment by Matafou** [comment]
Sure.

**Comment by SkySkimmer** [comment]
>CI passes and bench shows an actual enhancement. I'll let a bit of time for additional comments, but essentially up to a squash this looks ready to me. @SkySkimmer can you perform it?

No need for squash IMO, each commit is self contained. And if we have a problem later keeping them apart will help with bisect.

**Comment by ppedrot** [comment]
@SkySkimmer OK, fine then.

**Pull request merged**
