### PR TITLE
Statically ensure that some universe constraints are merged in ssrmatching

### PR DESCRIPTION
**Pull request by ppedrot**
This saves a lot of useless splitting-then-merging of universes.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1967440419

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
Smaller test:
```coq
Require Import Coq.ssr.ssreflect.

Class Dist A := dist0 : nat -> A -> A -> Prop.

Definition dist {A : Type} {Dist : Dist A} : nat -> A -> A -> Prop := Dist.

Axiom later : forall (A : Type), Type.

Context {A : Type}.

Axiom later_dist : Dist (later A).

Axiom Reflexive : forall {A : Type}, (A -> A -> Prop) -> Prop.

Axiom foo : forall n, Reflexive (later_dist n).

Goal forall n : nat, @Reflexive (later A) (@dist (later A) later_dist n).
Proof.
intros n.
rewrite /dist.
match goal with [ |- Reflexive (later_dist n) ] => refine (foo n) end.
Qed.
```
For some wicked reason I didn't manage to get rid of the `Class` definition, there must be some weird thing going on w.r.t. universes.

**Comment by ppedrot** [comment]
Subseded by #15478 which is just a subset, but at least a correct one.

**Comment by JasonGross** [comment]
> For some wicked reason I didn't manage to get rid of the `Class` definition

Does the issue still occur with Definition + Existing Class?  If so, maybe there's typeclass resolution triggering at `rewrite /dist`?

**Comment by ppedrot** [comment]
Yes, there is something going on at the intersection of resolution and implicit argument though I haven't dug that much. Ssr handles patterns in a weird way, the `/dist` unfolding from the example creates a dangling evar.

**Pull request closed without merging**
