### PR TITLE
Slightly less stupid algorithm for simpl fixpoint expansion + cleanups

### PR DESCRIPTION
**Pull request by ppedrot**
On the issue fixed in #13769 it divides the time by 2 from ~10s to ~5s. Still not as good as cbn but given the huge number of simpl users in the wild it might have a big impact.

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/976054879

**Comment by ppedrot** [comment]
I still recommend merging, it's making the code less hackish and given the impressive time diff on the degenerate example, it means it can be beneficial in extreme cases.

**Review by mattam82 — APPROVED** [review]
I approve. I think I felt this in MetaCoq for example (cbn is way faster then)

**Comment by mattam82** [comment]
@coqbot merge now

**Pull request merged**
