### PR TITLE
Test code owner interaction with PRs turned draft.

### PR DESCRIPTION
**Pull request by Zimmi48**
This is a test PR. Let's say I open a WIP PR and accidentally forget to make it a draft PR.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Now I make it a draft PR.

**Comment by Zimmi48** [comment]
Now I remove the automatically triggered review requests?

**Comment by Zimmi48** [comment]
Let's say this PR is finally ready. I'm going to mark it as ready for review again.

**Comment by Zimmi48** [comment]
It triggers a review request from the build maintainers team because the review request had been prevented while the PR was in draft status. That's already pretty good news. However, the CI maintainers whose review request had been initially triggered and which I had manually removed are not requested a review again. Therefore, I would have to request their review again manually.

A good workaround that GitHub could provide would be a button to automatically re-request reviews for every relevant code owners. And the UI could ask the user marking a PR ready for review whether that should be done.

**Comment by Zimmi48** [comment]
As a related test, let's say I request manually a review from another maintainer team, then remove the review request.

**Comment by Zimmi48** [comment]
In this case, despite having previously removed the review request for this team, the fact that I changed a file where they were a code owner still triggered a new automatic review request (that's good).

**Comment by Zimmi48** [comment]
However, if I do remove again the review request.

**Comment by Zimmi48** [comment]
Then change another file that they are code owners for, this does not trigger again a review request. I guess this is to avoid spamming. But it would be good in special cases (like when marking a PR as ready for review again) to be able to re-trigger review requests from every code owner.

**Comment by SkySkimmer** [comment]
>However, the CI maintainers whose review request had been initially triggered and which I had manually removed are not requested a review again. Therefore, I would have to request their review again manually.

Did you rebase? If not maybe they would get requested for a rebased push.

**Comment by Zimmi48** [comment]
I didn't. It's possible that I missed a few corner cases indeed. I've written to GitHub support about this feedback. Let's see what they answer.

**Pull request closed without merging**
