### PR TITLE
Remove dependency of native_compile on global env for symbols

### PR DESCRIPTION
**Pull request by SkySkimmer**
Instead we get the symbols from a Environ.env.
We make them accessible to the produced code through a reference
managed by the kernel, similar to the return values except inverting
when it's written and when it's read.

### CODE REVIEW

**Comment by ppedrot** [comment]
What is the motivation for this patch? I know that linking is fundamentally imperative, but I still feat a bit uneasy about relying on a mutable reference in the implementation of safe environments.

**Comment by ejgallego** [comment]
> What is the motivation for this patch?

This patch is needed in the various parts pushing `Global` and `Library` up to vernac.

**Comment by ppedrot** [comment]
Why don't you pass a safe_env instead of an env then?

**Comment by SkySkimmer** [comment]
>Why don't you pass a safe_env instead of an env then?

Because safe_typing depends on this code
What's wrong with passing an env?

**Comment by ppedrot** [comment]
> What's wrong with passing an env?

The fact that you have to rely on a mutable reference to store it in the safe_env. I mean, that' not critical, but it's kind of a wart.

**Comment by SkySkimmer** [comment]
>The fact that you have to rely on a mutable reference to store it in the safe_env. 

What are you talking about?

**Comment by ppedrot** [comment]
Nativelib.native_symbols. You should pass it as an argument somehow.

**Comment by SkySkimmer** [comment]
>Nativelib.native_symbols. You should pass it as an argument somehow.

It's passed as an argument since it's in the env, except for the accesses by generated code which use the ref. Passing it everywhere through the generated code seems quite complex and of low utility.

**Comment by SkySkimmer** [comment]
I don't know why you're talking about safe_env, this is all happening of the level of nativeconv and below, so certainly below typeops.

**Review by ppedrot — APPROVED** [review]
Whatever, the discussion is not leading anywhere and I am satisfied enough with this code to give it my approval.

**Comment by SkySkimmer** [comment]
ping @maximedenes

**Review by maximedenes — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
