### PR TITLE
Document supported attributes of Add Relation / Add Morphism and fix #17039.

### LINKED ISSUE #17039: Refman broken Instance notation for Add Parametric Relation
In the Coq 8.16 reference manual, at https://coq.inria.fr/distrib/current/refman/addendum/generalized-rewriting.html#first-class-setoids-and-morphisms

it says "the declaration . . . Add Parametric Relation . . .  is equivalent to an instance declaration . . .
```
Instance (x1 : T1) ... (xn : Tn) => id : @Equivalence (A t1 ... tn) (Aeq t′1 ... t′m) :=
 .  .  .
```
However, Coq 8.16 does not accept an Instance declaration in this syntax.  What seems to work instead is,

```
Instance id (x1 : T1) ... (xn : Tn)  : @Equivalence (A t1 ... tn) (Aeq t′1 ... t′m) :=
 .  .  .
```

And, of course, the manual should say what scope (export, global, whatever) should be attached to the Instance, to be equivalent to an Add Parametric Relation declaration.

### PR DESCRIPTION
**Pull request by Zimmi48**
Fixes #17039.

### CODE REVIEW

**Comment by Zimmi48** [comment]
This PR does not document `program` as being supported because it is a no-op and #17042 removes it.

**Review by jfehrle — APPROVED** [review]
Looks OK.  Does this depend on #17042 being merged first?

**Comment by Zimmi48** [comment]
Sorry, I missed your question. The related PR is merged now, but any order was fine as long as both were accepted.

**Comment by jfehrle** [comment]
@coqbot: merge now

**Pull request merged**
