### PR TITLE
lib/Unicodetable: Update.

### PR DESCRIPTION
**Pull request by yurug**
This code has been generated from the latest Unicode tables using UUCD, an OCaml library to parse the official Unicode tables.

### CODE REVIEW

**Comment by ejgallego** [comment]
Well, those tables and most of `Unicode` seem only used by `System.all_subdirs` and AFAICT the tables play not a significant role.

Is there any reason for not just to remove this?

**Comment by ejgallego** [comment]
Never mind my previous comment, this was not the place to discuss about the Unicode stuff, I'm sorry. I will move the discussion to the `-safe-string` PR.

**Comment by ppedrot** [comment]
Shouldn't that rather go in 8.6? This looks like a bugfix more than anything else...

**Comment by maximedenes** [comment]
Hugo made the remark offline that compatibility concerns are not completely vacuous here. A unicode character that was previously unknown was parsed as a symbol whereas know it could be recognized as a letter (so part of an ident for example). So low risk, but not zero. Given how much we've been struggling to wrap up the 8.6 release, I'd like to keep it for 8.7.

**Comment by mattam82** [comment]
Agreed with Maxime, let's get it out!

**Comment by herbelin** [comment]
@maximedenes: About my offline remark: the only risk of incompatibility I could imagine is when a user has an ident immediately followed by a unicode letter which was not recognized as such. This looks unlikely, because if Coq does not see the unicode letter as a letter, the human would presumably do and would have put a space to avoid his unicode letter to visually form a human-level identifier. Moreover, if ever an incompatibility happens, it is the user who will have to do a change and not us to change Coq again. Also, strictly speaking, because there will be more works around at the time of 8.7, we will have a greater risk of incompatibility by postponing this PR than by merging it now. So, all arguments are in favor of merging this PR as soon as possible.

My perception is rather that the question is that we collectively want the beta1 release to be completed without further delay.

So, to be consistent with this collective will, no further PR should be accepted, even PRs to be legitimately pushed as soon as possible.

In particular, accepting a last minute  PR such as #360 whose urgency level does not seem higher than the unicode one does not seem justified to me. Wasn't there one year ago a series of talks from someone  named Maxime Dénès explaining in a doctoral way what the good practices of programming should be. Wasn't there an argument that PRs are good because they allow a discussion period? When was the discussion period for #360? It happens that I'm using `Stm Command Undo` under coqtop. This is an incompatibility, an effective one, while the one for the unicode PR is still virtual. (Note that I just talked with Emilio who is fully willing to restore `Stm Command Undo` or to at least provide a similar command, and more generally to continue cleaning up the different paths involved in the interfaces, something which is really needed I think.)

So, where are we? What is the release model that we are implementing? Continuing merging PRs until all proposals are exhausted, or even until everyone is exhausted? And merging PRs in a hurry, because at the same time as we want to satisfy everyone, we also have no more time left for discussing. Or even worse than that, to rather randomly merge some PRs and other not on speculations of incompatibilities?

Or are we implementing the model proposed last year by Monsieur Maxime Dénès (and approved by many of us) of not working in a hurry?

We are all wanting to contribute and to have our contributions to be available as soon as possible.
The more the 8.6 is postponed, the more the perspective of a quick 8.7 melts and the more we want to be in 8.6 because of an absence of visibility on 8.7. Wasn't the agreed objective to revert the flow of this cycle and that on the contrary, we are all looking forward to coq 8.7 and, for this reason, we all also want that 8.6 is concluded quickly?

So, I don't know what is the current status but could we for instance collectively agree that no newly created PR is pushed at all anymore to the exception of Matthieu's last fixes?

And on the technical note, an extra question: there is a V8.6beta2 tag in coq-bugs, what suggests that there will be a second beta but you told me privately on the phone that you actually have in mind a model with no beta2. Is the intent then that no further bug-fix phase is expected to happen after the beta1 is released, and that it directly becomes a rc and a final, with say a Christmas target?

**Comment by mattam82** [comment]
Stopping anything from happening on 8.6 is the goal, but my PR slipped
through and caused problems, I'm guilty for not having foreseen the
incompatibilities and explained them at the time. Then Maxime merged it as
I okayed it, and we've been struggling to revert the incompatible parts
since two weeks or so. In the meantime we were in a gray area where PR's
should not have been merged anymore as we considered 8.6beta done but we
were lenient and accepted some (I know it is arbitrary, sorry for that).
Since my last fix yesterday I think nothing should be merged except for a
critical bug fix so that we can all move on. We hope no beta2 will be
necessary but You Never Know :)
Le jeu. 17 nov. 2016 à 15:53, Hugo Herbelin <notifications@github.com> a
écrit :

**Comment by ejgallego** [comment]
@herbelin , IMO the reasoning to merge the commit was sound as precisely we wanted to avoid users relying on the functionality you precisely did, so indeed it qualifies as high-priority. "La excepción confirma la regla" :)

Regarding the missing command, AFAICS `Back n` or `Undo n` should do the same for you, note that the code in `Stm.undo_vernac_classifier` was not changed.

Let me know in private the exact use case that is failing now for you and we'll figure it out.

**Comment by ejgallego** [comment]
By the way, the bugs about interruption handling and printing are RC IMO, they will need some testing for sure... I am sorry I didn't get time to complete a PR.

**Comment by Zimmi48** [comment]
Not wanting to troll but I think #332 qualified as the kind of PR to remove something that we did not want users to rely on, but it got decided that it wouldn't get merged ;)

**Comment by mattam82** [comment]
Ah, the inconsistency...

**Comment by gares** [comment]
#360 is broken because there is no XML message to call Stm.wait().

Said that, calling "Stm Command Undo" makes no sense!  I had to add twist for you Hugo, exactly to let you just write "Undo" and have the 8.4 semantics. Please don't use "Stm Command Undo".

**Comment by maximedenes** [comment]
I easily acknowledge that merging PR#360 was a mistake. However, I was anyway about to revert it, so the consequences will be very limited. I would appreciate that people get some understanding that maintaining consistency throughout a release process, while designing that process at the same time, is an exhausting task. Mistakes can and will happen, and can be reported without a cynical tone.

After this revert, I'll try to prepare the beta without merging any more PR, unless an unexpected blocking problem occurs.

**Comment by ejgallego** [comment]
Sorry, I don't think #360 is broken, maybe the protocol is. IMHO not applying #360 will do way more harm than good, as IMO Hugo's use case illustrates.

What is the good of shipping commands that make absolutely no sense? I could open a bug and then this would be a "bugfix"? We know there are many bugs in the STM, there even are comments indicating them, so we can start to fill many bugs.

Regardless of what you do in #360, fixing the circularities in the STM interface means that all this `Stm` vernacular stuff will have to go, so if this is going to block progress for 8.7 again then... I don't know what to say.

**Comment by Zimmi48** [comment]
Maybe the discussion on #360 should move back to #360.
@yurug In the name of all, I apologize for polluting this PR's discussion.

**Comment by herbelin** [comment]
@ejgallego, @gares: To be honest, I'm using coqtop on a daily basis but I'm not using `Stm Command Undo` on a daily basis. Sometimes some `Reset`, or simply restarting the session is enough from a practical point of view. Somehow, my interest in `Stm Command Undo` was also that I was still at a step of trying to understand what it exactly does, and what was the concept behind it.

@mattam82, @maximedenes: don't take my message as an affaire d'état! Just as an attempt to improve a few things in a global process which is anyway in clear progress wrt previous years.

@maximedenes: I fully understand that the release process is an exhausting task (not talking about all these people expressing unsatisfaction!). Fundamentally, my point is to improve the situation (better communication, less arbitrariness, more rigorous rules, better respect of each of us, and, who knows, maybe less exhaustion at the end), not to make it worst. And I don't think that my tone echoing to last year is cynical.

By curiosity, to continue with the beta2 question: is the plan to adopt the rule which is sometimes followed that the last beta has to be identical to the first rc, or we don't care about this rule?

**Comment by mattam82** [comment]
I think indeed Maxime hoped for no second beta, if we get at worst minor
bug reports that we want to put in 8.6 I guess. It will all depend on the
kind of issues the beta release reveals I think, so it's hard to predict in
advance.

**Pull request merged**
