### PR TITLE
Split off Nsatz tactic part into Nsatz_tactic

### LINKED ISSUE #5445: [Require Nsatz] should not add axioms to the tcb as described by coqchk
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5445
From: @JasonGross
Reported version: 8.6
CC:   @ppedrot

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** bug fix

Note that other than removing trailing whitespace, this is entirely just cut/copy and paste.  (+ a test-suite file)

Closes #5445

- [x] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

**Review by anton-trunov — APPROVED** [review]

**Comment by herbelin** [comment]
The PR is indeed welcomed.

I think we should also consider the naming question. The camel case is not systematic but more common in the current status of the stdlib, so, if this does not matter for you, I would lean for it.

**Comment by JasonGross** [comment]
It does not matter to me; I will plan to rename it later today

**Comment by JasonGross** [comment]
Hmm, perhaps I should use `Include` rather than `Export`; this would make things backwards compatible and make fiat-crypto not need an overlay

**Comment by JasonGross** [comment]
Updated; I've renamed and switched to `Include` rather than `Export` to avoid compatibility issues.

**Comment by ppedrot** [comment]
Module inclusion is a can of worms. I think we'd be better off with a slightly backwards-incompatible code that does not rely on complex features of this kind.

**Comment by JasonGross** [comment]
Okay, I can do that and then prepare overlays

**Comment by JasonGross** [comment]
What's up with "Pipeline job activity limit exceeded"?

**Comment by herbelin** [comment]
> What's up with "Pipeline job activity limit exceeded"?

I learnt from @ejgallego that this is issue #11320!

**Comment by JasonGross** [comment]
I rebased this to try to fix VST (the only failure), but I'm concerned the test-suite might fail anyway given that it's currently failing on master.  What remains to be done to get this merged?

**Comment by JasonGross** [comment]
@MSoegtropIMC What should be done about the out-of-space errors on Windows64?

**Comment by MSoegtropIMC** [comment]
> @MSoegtropIMC What should be done about the out-of-space errors on Windows64?

A server cleanup run - I will do it around lunch time today.

**Comment by MSoegtropIMC** [comment]
> A server cleanup run - I will do it around lunch time today.

Done. Two servers where hit heavily by network outages 3 days back. It always leaves some debris if the runners looses connection with the gitlab host and cleaning this up automatically is also not so reliable, because sometimes some zombie processes live for quite a while and lock files. Maybe I can do a scheduled job on the Windows runners to do the cleanup automatically once a day.

**Comment by Zimmi48** [comment]
There's a bug in `CODEOWNERS` that made this PR not trigger any review request from @coq/nsatz-maintainers but the assignee should probably be among one of them.

BTW, I restarted the failed Windows job.

**Review by ppedrot — APPROVED** [review]
I already had a look at this PR, and I trust @JasonGross that this is indeed copy-pasting.

**Comment by ppedrot** [comment]
I'll merge when we manage to get a full CI.

**Comment by JasonGross** [comment]
> I trust @JasonGross that this is indeed copy-pasting.

Note that the third commit, needed to actually make nsatz not depends on R axioms, is not just a copy-paste, and involves replacing the hard-wired call to discrR with a call to a new tactic which is defined to be idtac in NsatzTactic and then redefined to be discrR in Nsatz.

**Comment by ppedrot** [comment]
@JasonGross yes, this is fine. The commit that was hard to review is the first one.

**Pull request merged**
