### PR TITLE
Gitattributes file added to generate archive.

### PR DESCRIPTION
**Pull request by clarus**

### CODE REVIEW

**Comment by aspiwack** [comment]
Can someone familiar with making the `tar.gz` archive of Coq check that these are the appropriate files to omit?

@clarus can you remind us why you need this attribute file?

**Comment by clarus** [comment]
As mentioned by @gares on the *coq-dev* mailing list, the `.gitattributes` file is useful to generate the `.tar.gz` archive with `git archive` excluding some files.
The list of files to exclude can be obtained running:

    curl -L https://coq.inria.fr/distrib/V8.4pl5/files/coq-8.4pl5.tar.gz |tar -xz
    mv coq-8.4pl5/ coq-public
    curl -L https://github.com/coq/coq/archive/V8.4pl5.tar.gz |tar -xz
    mv coq-8.4pl5/ coq-dev
    diff coq-dev/ coq-public/

**Comment by letouzey** [comment]
> Le 13 mars 2015 à 15:09, Arnaud Spiwack <notifications@github.com> a écrit :
> 
> Can someone familiar with making the tar.gz archive of Coq check that these are the appropriate files to omit?
I did. I think it is OK.

**Comment by aspiwack** [comment]
Ok, sounds good, I'll merge it. On what branches will it be useful? v8.4 and v8.5 (and trunk)? Should I add v8.3 too?

**Comment by clarus** [comment]
Yes, I guess it should be useful on other branches too. For the branches `v8.5` and `trunk` there is a new file `.mailmap` which is not in the `.tar.gz`.

**Comment by aspiwack** [comment]
See also commits b8c8c115ef827cfaaff933abb64e1882497a30b5 and c8d143654489d9ae7295095a9e5e17cf89118b7a for the v8.5 branch. And 2b9e187f639c64bd5f49d2955149e21f929361e5 for v8.3 branch.

**Comment by clarus** [comment]
Thanks!

**Pull request closed without merging**
