### PR TITLE
Fix cbv on matching products

### LINKED ISSUE #18801: cbv on RR product match is broken
### Description of the problem

Anomaly Invalid_argument("Array.fold_left3_i") on cbv

### Small Coq file to reproduce the bug

```coq
Symbol dom : Prop -> Prop.
Rewrite Rule dom_rew := dom (forall (x : ?A), ?B) ==> ?A.
Eval compute in dom (True -> True).
```

### Version of Coq where this bug occurs

master

### Last version of Coq where the bug did not occur

_No response_

### LINKED ISSUE #18829: Invalid_argument("Array.fold_left3_i") on cbv with rewrite rules
~~~coq
(* -*- coq-prog-args: ("-allow-rewrite-rules"); -*- *)

Symbol dom : Prop -> Prop.
Rewrite Rule dom_rew := dom (forall (x : ?A), ?B) ==> ?A.

Eval cbv in dom (True -> True).
~~~

### PR DESCRIPTION
**Pull request by yannl35133**
Fix #18829

### CODE REVIEW

**Comment by yannl35133** [comment]
Does this really need full CI?

**Review by SkySkimmer — APPROVED** [review]
Please add test from #18829

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
