### PR TITLE
Fix whitespace.

### PR DESCRIPTION
**Pull request by SkySkimmer**
I've been growing more friendly with the idea of 1 big commit fixing all this whitespace stuff, so let's see what it looks like.

The following script was run on all files:
```bash
#!/usr/bin/env bash

attr=$(git check-attr whitespace -- "$1")

# NB: don't do bat files
if echo "$attr" | grep -q -e 'unset$' -e 'unspecified$' -e 'cr-at-eol';
then
    exit 0
fi

tmp=$(mktemp)

expand "$1" > "$tmp"
chmod --reference="$1" "$tmp"

mv "$tmp" "$1"

sed -e's/[[:space:]]*$//' "$1" > "$tmp"
chmod --reference="$1" "$tmp"

mv "$tmp" "$1"
```

Then the md5 in checker/values.ml was updated.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Some stuff to consider:

- GitHub built-in blame doesn't pass the `--ignore-whitespace` option it seems. So I still stumble, from time to time, upon that old "whitespace commit" 61ccbc81a2f3b4662ed4a2bad9d07d2003dda3a2 from several years ago. Interestingly it is about the same size as your own commit (29,000 lines affected, but it was only for trailing whitespaces apparently).

- If we merge this, we should all agree never to bypass the linter anymore. We can't fix an issue and then re-introduce it little by little.

- Are we going to apply yet another "big commit" affecting indentation in the near future? (E.g. using some tool to automatically reformat source files?) If yes, maybe we should do this right now, instead of duplicating the "big commits".

**Comment by SkySkimmer** [comment]
At least it doesn't break the CI https://gitlab.com/SkySkimmer/coq/pipelines/14289598

**Comment by herbelin** [comment]
>    GitHub built-in blame doesn't pass the --ignore-whitespace option it seems. So I still stumble, from time to time, upon that old "whitespace commit" 61ccbc8 from several years ago. Interestingly it is about the same size as your own commit (29,000 lines affected, but it was only for trailing whitespaces apparently).

Apparently, one has indeed to give explicitly `-w` (and optionally `-M`) at each call.

>    If we merge this, we should all agree never to bypass the linter anymore. We can't fix an issue and then re-introduce it little by little.

Idem.

>    Are we going to apply yet another "big commit" affecting indentation in the near future? (E.g. using some tool to automatically reformat source files?) If yes, maybe we should do this right now, instead of duplicating the "big commits".

Looks reasonable, assuming that the near future is "near", but I did not see a lot of support for a "canonical" formatting yet.

**Comment by Zimmi48** [comment]
> Looks reasonable, assuming that the near future is "near", but I did not see a lot of support for a "canonical" formatting yet.

I would support it but I wouldn't volunteer to handle the technical aspect of it and I would want to discuss the style choice.

**Comment by maximedenes** [comment]
Following @mattam82 's "People seem really ambivalent about the large commit so I'd refrain for now and maybe do it later if we see fit." (see https://github.com/coq/coq/issues/6268), I'll close this PR. We can reopen at some point if we want to.

**Pull request closed without merging**
