### PR TITLE
Stop using module type CList.ExtS + Remove CList.except (alias of remove)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
Why did we do this in the first place?

**Comment by SkySkimmer** [comment]
No idea. It seems to be from you: f8394a52346bf1e6f98e7161e75fb65bd0631391

**Comment by ppedrot** [comment]
Yeah, I think the motivation was to statically ensure we're compatible with OCaml's List library.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
