### PR TITLE
Remove deprecated commands `AddPath`, `AddRecPath` and `DelPath`

### LINKED ISSUE #10576: Bogus syntax for AddPath and AddRecPath commands
Notice that these commands require 2 `as` strings in a row if `as_dirpath` is not empty.  Probably an editing error.  On the other hand, if no one has noticed this since 10/24/2017, are these commands really needed?

```
  command:
         :
       (* For compatibility *)
      | IDENT "AddPath"; dir = ne_string; "as"; alias = as_dirpath ->
	  { VernacAddLoadPath (false, dir, alias) }
      | IDENT "AddRecPath"; dir = ne_string; "as"; alias = as_dirpath ->
	  { VernacAddLoadPath (true, dir, alias) }

  as_dirpath:
    [ [ d = OPT [ "as"; d = dirpath -> { d } ] -> { d } ] ]
```

### PR DESCRIPTION
**Pull request by Zimmi48**
Fixes #10576

(extracted from #10575)

**Kind:** clean-up

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@Zimmi48 I understand this shouldn't be merged until you provide the changelog entry?

**Comment by Zimmi48** [comment]
I was actually wondering if it needed one, but the answer is probably yes.

**Comment by ejgallego** [comment]
> I was actually wondering if it needed one, but the answer is probably yes.

Ok, I'll wait then [unless you decide not to add one in the end]

**Comment by Zimmi48** [comment]
Done.

**Pull request merged**
