### PR TITLE
Fix #7101: STM delegation policy broken

### LINKED ISSUE #7101: STM delegation policy broken
Commit coq/coq@30d3515546cf244837c6340b6b87c5f51e68cbf4 changed the format of `.aux` files without updating the corresponding parser nor the `.aux` format version. This means that since Coq 8.7, CoqIDE always delegate proofs(*). In some examples I run from VST, it would typically mean a 7-second compilation (with `coqc`) turning into 10 minutes or so (when processing them with CoqIDE).

I'll fix it, but suggestions are welcome as to how to test this, so that it doesn't happen again.

(*) except if the threshold is manually set to 1.0 or more

### PR DESCRIPTION
**Pull request by maximedenes**
I make here a minimal fix, but a lot of cleaning should be done around
Aux_file handling, including removing some code from the kernel.

- [X] Entry added in CHANGES.

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
I have no idea how this aux stuff works :S

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Well the problem is that `---` breaks the parser of these files, hence the file is of no use anymore.
The `---` was introduced in one of the `Loc.t` refactorings, before it was printing the dummy loc (the `0 0`).

**Comment by gares** [comment]
@maximedenes you tried to convince me that this is not food for a unit test. I don't buy it. An `.ml` file that creates an aux file (using the API) and fills in with a few entries (including ones with no `Loc.t`) and the tried to read it back (using the API) would have detected this. No need to generate the file using `coqtop`.

**Review by gares — CHANGES_REQUESTED** [review]
The entry in CHANGES is a bit sketchy. Why "was"? Also since "Coq 8.7 it was ignoring it.." who?

**Comment by SkySkimmer** [comment]
Wouldn't it make more sense to parse ---? Although I understand not wanting to do it considering parsing is scanf-based.

**Comment by maximedenes** [comment]
> Wouldn't it make more sense to parse ---? Although I understand not wanting to do it considering parsing is scanf-based.

What would be the motivation?

**Comment by gares** [comment]
The format could be made much nicer, but not in a PR targeting 8.8.0

**Comment by ejgallego** [comment]
I surely had a reason to introduce the `---`, but sorry folks I don't remember.

**Comment by gares** [comment]
There is no problem at all. The good question is "what is the meaning of ---?" The meaning of "0 0" was Loc.ghost (that is None). The use for it was "this piece of info is not attached to a specific line, it is global". So "---" can carry the same meaning, it is just the one has to fix the parser too ;-)

Wrt scanf, yes, maybe I was too nostalgic, but between scanf and a camlp5 parser... dunno who wins

**Comment by gares** [comment]
@maximedenes could you fix the CHANGES?

**Comment by maximedenes** [comment]
I understand only half of your remark about the `CHANGES` entry. I can remove "it" and use a passive form, but "was" is because it is past...

**Comment by gares** [comment]
I think it is correct English after all. I was mislead by the fact that my brain made "it" point to "Coq" rather than the delegation policy. Pronouns, how wonderful. Hint:

Delegation policy: take into account previous runs and only delegate proofs that are known to take longer than `-option` (default zzz).
From version XX to YY Coq ignored previous runs, making the `-option` ineffective.

**Comment by gares** [comment]
I've reworded the entry while merging a conflict.

**Comment by ejgallego** [comment]
So I'm pretty sure that I introduced the `---` with the intent to change the parser, but I forgot to do it as I likely though that change would make testing fail.

**Pull request merged**
