### PR TITLE
Remove spurious anomalies in kernel reduction

### PR DESCRIPTION
**Pull request by SkySkimmer**
~Replaces https://github.com/coq/coq/pull/11681~

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Breaks on
~~~coq
Lemma foo : False.
Proof.
  (* I is a proof of True *)
  do 2 try rewrite I.
  (* First rewrite produces side effect internal_True_rew_r with a fresh universe.
     Then it fails (because producing identical goal), failure is caught by try.
     Then we try again, find the side effect but don't have its universes in the evar map. *)
~~~

**Comment by ppedrot** [comment]
@SkySkimmer Shouldn't #11681 be merged anyways then?

**Comment by SkySkimmer** [comment]
I guess

**Comment by ppedrot** [comment]
@SkySkimmer status of this?

**Comment by SkySkimmer** [comment]
Let's try this less ambitious version where we still catch anomalies in reductionops

**Comment by ppedrot** [comment]
@SkySkimmer Thanks for the quick reaction.

**Comment by SkySkimmer** [comment]
Looks like it works

**Comment by maximedenes** [comment]
@ppedrot do you want to be the assignee for this PR?

**Comment by ppedrot** [comment]
Let's merge then.

**Review by ppedrot — APPROVED** [review]

**Comment by LasseBlaauwbroek** [comment]
Note for historians like me: This fixed #11771 and #5466

**Pull request merged**
