### PR TITLE
Try using -j2 for fiat-crypto

### LINKED ISSUE #17222: Fiat-crypto timeouts
Fiat-crypto keeps timing out, and it's already long enough that I want to reduce the timeout and oppose increasing it.
Can we get a subset of it to run in CI?
If not then IMO we should remove it.

cc @JasonGross

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17222 ?

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I ran it 3 times and timing was reasonable

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Errors are unrelated

**Comment by ppedrot** [comment]
How do we know this is going to be reliable?

**Comment by SkySkimmer** [comment]
It probably isn't worse than what we have now

**Comment by SkySkimmer** [comment]
Assignee?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
I'm not a CI maintainer but I'll merge soon anyways.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
