### PR TITLE
Make detyping robust w.r.t. broken environments.

### PR DESCRIPTION
**Pull request by ppedrot**
Extracted from #9710.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
How do we get broken envs?

**Comment by ppedrot** [comment]
I don't remember, but probably in the debugger.

**Comment by SkySkimmer** [comment]
Does that mean the debugger will be unusable on matches?

**Comment by ppedrot** [comment]
I don't think so, because we also tweak the case printer IIRC. The problem here is that the absence of the inductive raises an exception at the wrong place.

**Comment by SkySkimmer** [comment]
I tested it and it breaks debug printing.

**Comment by SkySkimmer** [comment]
Do we even lookup the inductive in detyping?

**Comment by ppedrot** [comment]
M'kay. I don't remember the details of this patch, so maybe it was a ugly hack. We can probably close for the time being.

**Pull request closed without merging**
