### PR TITLE
Fix handling of extraction and funind not being loaded by default

### PR DESCRIPTION
**Pull request by tchajed**
Improve the error messages and add a note to CHANGES since this requires updating user code.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks!
I don't know why I missed this CHANGES entry when preparing 8.7+beta1 but anyways, it should be in the 8.6.1 to 8.7+beta1 section, not where you put it.

**Comment by tchajed** [comment]
Makes sense, moved the entry.

**Comment by maximedenes** [comment]
@Zimmi48 I guess this should be cherry-picked to v8.7, don't you think?

**Comment by Zimmi48** [comment]
@maximedenes Actually, now that you merged #938, this PR should be split in two PRs. One on master with only the `CHANGES` entry, one v8.7-only with the improved error message. @tchajed can I let you do this? Sorry for the additional hassle. (I suggest that you transform this PR into the v8.7-only PR and open a new one for `CHANGES` but that's up to you.)

**Comment by Zimmi48** [comment]
@tchajed Do you mind updating this PR as I suggested in my previous message? If you don't have time for this, I can do it myself, but please let me know.

**Pull request closed without merging**
