### PR TITLE
Put back coqdep -dumpgraph(box) options

### LINKED ISSUE #13636: Reintroducing `coqdep -dumpgraph[box]`?
#### Description of the problem

As discussed both [on Discourse](https://coq.discourse.group/t/tool-for-drawing-coq-project-dependency-graph/653/4) and [on Zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/coqdep.20-dumpgraph.20on.208.2E12) the option to generate dependency graphs to be rendered by the `dot` tool was/is used by quite a few people. This was removed as part of #11523 and I advocate for reverting the removal of the `-dumpgraph[box]` options.

#### Coq Version

8.12

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #13636

### CODE REVIEW

**Comment by gares** [comment]
CC @chdoc

**Comment by ejgallego** [comment]
> What does maintain mean? This is pretty static code, no need to mess with it.

Maintains means than I have a lot more work to do due to the extra exported functions when I get to refactor coqdep , moreover the exported API makes no sense.

The code was removed because was abandonware, was not tested in the full CI, and most users such as math-comp and flocq use another solution, not to say there are universal packages to produce dep graphs from Make rules so I don't see why we have too keep this NIH code.

Maintain in this case means:
- adding documentation
- adding a test-suite

**Comment by ejgallego** [comment]
> Please, we are wasting more energy in this discussion than in maintaining that code for years.
> Let it go, it will make some users happy at a very little cost.

The cost for me is significant, as I'm working in coqdep.

Morever, what I am trying to do here makes a lot of sense, instead of having 4 different half-baked ways of generating that information, let's converge to a single, official solution.

**Review by ejgallego — CHANGES_REQUESTED** [review]

**Comment by SkySkimmer** [comment]
I guess I understand where @ejgallego is coming from as I don't want to mess with this further either.

**Comment by ejgallego** [comment]
> I guess I understand where @ejgallego is coming from as I don't want to mess with this further either.

Actually I'm gonna implement the required coqdep interface as part of the build system / test suite work, so if someone would like to work on this it should be pretty easy to get it back.

**Comment by ppedrot** [comment]
What about backporting that to 8.15 only? We have quite a few users who complained about that removal already.

**Comment by Zimmi48** [comment]
I'd rather avoid doing that kind of thing if we're not sure what we'll be able to provide in 8.16...

**Pull request closed without merging**
