### PR TITLE
Fix incorrect name refreshing when interning a generalized binder

### LINKED ISSUE #13249: Bad error message: "foo already exists", but does not exist
#### Description of the problem

The following code leads to a very confusing error message:
```
Global Generalizable All Variables.

Section test.
Context {A : Type}.
Context `{!foo A}.
```
It says
```
Error: foo already exists.
```
Which is not right, or at least not helpful -- the problem is actually caused by `foo` *not* existing. (I just got this error when I had a typo in my typeclass name. If a class named `foo` actually exists, there is no error.)

#### Coq Version

8.12.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #13249

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Looks reasonably good. Will merge tomorrow (+ margin) if no other comments by then

PS: I have also somewhere a mini-cleaning of this part of the code. I'll try to resurrect it.

**Comment by herbelin** [comment]
@gares: this is a simple fix, no overlays, it makes sense for 8.13.

**Comment by gares** [comment]
ok

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by RalfJung** [comment]
Thanks @SkySkimmer :-)

**Pull request merged**
