### PR TITLE
Deprecate Nat and Int implementations in Numbers

### PR DESCRIPTION
**Pull request by Villetaneuse**
A library deprecation attribute has been inserted. The 3 files
- `theories/Numbers/Integer/Binary/ZBinary.v`
- `theories/Numbers/Integer/NatPairs/ZNatPairs.v`
- `theories/Numbers/Natural/Binary/NBinary.v`
are leaves in the stdlib and are probably not used anywhere.

### CODE REVIEW

**Review by proux01 — APPROVED** [review]
Great

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@coqbot merge now

**Comment by Villetaneuse** [comment]
> @Villetaneuse sorry, I forgot something: due to the deprecation, it would be nice to add a changelog, could you add one in a separate PR?

I'll do this asap, sorry I should have thought about it too.

**Comment by proux01** [comment]
No hurry, there is some time left before next release ;)

**Pull request merged**
