### PR TITLE
[build] [test-suite] Don't install fake_ide

### LINKED ISSUE #14306: Since dune, make install has changed
`make install` installs files to a different layout now.  I assume the following changes are intended:
- `/usr/lib/coq{ => -core}/tools/{coqdoc/coqdoc.css,coqdoc/coqdoc.sty,CoqMakefile.in,TimeFileMaker.py,make-both-time-files.py,make-one-time-file.py,make-both-single-timing-files.py}`
- `/usr/lib/coq{ => -core}/{revision,META}`

I'm not sure about the following ones:
- `/usr/lib/coq/plugins/micromega/csdpcert` => `/usr/bin/csdpcert` (seems suspicious)
- `/usr/lib/coq/kernel/byterun/dllcoqrun.so` => `/usr/lib/stublibs/dllcoqrun_stubs.so` (maybe reasonable?)

The following changes are wrong:
- `/usr/share/texmf/tex/latex/misc/coqdoc.sty` => `/usr/share/coq-core/texmf/tex/latex/misc/coqdoc.sty`
- `/usr/bin/fake_ide` is now installed, whereas it wasn't previously (we might want to prefix this with `coq` and install it, but we definitely don't want to install it like this)

The following directories used to be installed but no longer are:
- `doc/stdlib/html`

Log of changes at https://launchpadlibrarian.net/537997360/buildlog_ubuntu-xenial-amd64.coq_8.master~git~202105101453+22306-0~daily347-c6223fc6aa~ubuntu16.04.1_BUILDING.txt.gz

### PR DESCRIPTION
**Pull request by ejgallego**
Closes #14306 , in the future we will improve this by fixing #10613

### CODE REVIEW

**Comment by Alizter** [comment]
I forgot to ask in the call, what is the point of `fake_ide`? Is it documented anywhere?

**Comment by ejgallego** [comment]
> I forgot to ask in the call, what is the point of `fake_ide`? Is it documented anywhere?

It is a head-less client for the XML protocol, this way you can test it without having to script coqide or have a GUI at hand.

**Comment by ejgallego** [comment]
As a result of this, the test-suite is broken because we removed the fake_ide hack on the Dune migration.

**Comment by SkySkimmer** [comment]
Maybe fake_ide should be fully part of the test suite (move the code to test-suite/fakeide, build it in test-suite/Makefile)?

**Comment by ejgallego** [comment]
> Maybe fake_ide should be fully part of the test suite (move the code to test-suite/fakeide, build it in test-suite/Makefile)?

That would make sense, and dunerized test setups do provide good kind of support for this case IIANM.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/commit/f590493defdae8a84e6c88ac981f89ac33744891#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7L104
No idea how nix worked.

**Comment by Columbus240** [comment]
A heads-up, because I volunteered to look into this.

> Maybe fake_ide should be fully part of the test suite (move the code to test-suite/fakeide, build it in test-suite/Makefile)?

I think that's the cleanest solution. But it might be even better, if dune would build the executable. Then we wouldn't have to manage the compilation process in the Makefile. I currently have dune building it, but had to put it in `test-suite/fake_ide.ml` instead of `test-suite/ide/fake_ide.ml` where I'd have liked it to be. I don't know how to get dune to build the executable if the source is in the subdirectory. (Anyone know a trick?)

I tried going on in this setting, but came across a slight problem: `fake_ide` has hardcoded, that the `coqidetop` executable lies in the same directory as itself. I have nothing against removing this requirement, but the code currently uses `System.get_toplevel_path` for this, which I'd need to modify, replace or duplicate.
Am still trying out.

**Comment by ejgallego** [comment]
> I don't know how to get dune to build the executable if the source is in the subdirectory. (Anyone know a trick?)

Just add the dune fine in `test-suite/ide/dune` with the executable stanza.

**Comment by Zimmi48** [comment]
Superseded by #14656.

**Comment by ejgallego** [comment]
Thanks for taking care of this.

**Pull request closed without merging**
