### PR TITLE
Remove the new auto tactic.

### PR DESCRIPTION
**Pull request by ppedrot**
It does not seem to be used in Coq, let's see if there are users out there.

Depends on #14528.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
"new" since e961ace331ec961dcec0e2525d7b9142d04b5154 (2008)

**Comment by ppedrot** [comment]
@SkySkimmer yes, I've mentioned the original commit in the message of #14528.

**Comment by ppedrot** [comment]
This needs an assignee.

**Review by herbelin — APPROVED** [review]
No particular comments on the PR (there was already a discussion at #14528).

I'm not necessarily up-to-date with deprecation policies though, so, here trusting.

For assigning, maybe someone github-active on a daily basis could do it?

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
