### PR TITLE
note since when the things recommended in a deprecation note are supported

### PR DESCRIPTION
**Pull request by RalfJung**
See https://github.com/coq/coq/pull/15802#issuecomment-1164285307
Cc @Zimmi48

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by RalfJung** [comment]
Those are the ones I knew about and cared about enough to do the research required (find out which Coq version the locality was first supported in).

How many more of these warnings are there?

**Comment by ppedrot** [comment]
```
$ git grep "The default value for" -- '*.ml'
tactics/autorewrite.ml:    (fun () -> strbrk "The default value for rewriting hint locality is currently \
tactics/hints.ml:    (fun () -> strbrk "The default value for hint locality is currently \
vernac/classes.ml:  "The default value for Typeclasses Opaque and Typeclasses \
vernac/classes.ml:    (fun () -> strbrk "The default value for instance locality is currently \
```

**Comment by ppedrot** [comment]
At some point we didn't have attributes but only command modifiers, so it depends on how you phrase the claim.

**Comment by RalfJung** [comment]
Looks like `#[local] Lemma foo : bar` is supported since Coq 8.9. That counts as "forever".

So I don't know other warnings that would currently benefit from this kind of information.

**Review by ppedrot — APPROVED** [review]
OK, fine with me then.

**Pull request merged**
