### PR TITLE
[ci-itauto] adds itauto to the CI

### PR DESCRIPTION
**Pull request by fajb**
This PR adds the itauto plugin to the CI.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.inria.fr/fbesson/itauto/-/blob/master/Makefile looks a bit complex, I guess to handle the extraction step

**Comment by SkySkimmer** [comment]
you can use ci-template-flambda to get a newer ocaml

**Comment by Zimmi48** [comment]
FWIW @palmskog has some experience with projects using extraction and his solution lately has been to rely on Dune.

**Comment by palmskog** [comment]
Right, I have used Dune successfully to build the [Stalmarck](https://github.com/coq-community/stalmarck) library+plugin, where the plugin uses code extracted from. The relevant Dune file is [here](https://github.com/coq-community/stalmarck/blob/master/tactic/dune).

@fajb would you consider adding a Dune build to your project? If so, I can take an initial look at it later today. I think the Makefile build could still be left in place.

**Comment by fajb** [comment]
@palmskog I have no knowledge of dune. If this simplifies things, that's good for me.

**Comment by JasonGross** [comment]
Regarding the Makefile, I think if you stick `src/prover.ml: | theories/Prover.vo` in `CoqMakefile.local`, along with any other compilation / patching targets not covered by `coq_makefile`, that might be enough to let you combine the two `coq_makefile` invocations into one.  I believe this will have the effect of demanding that `theories/Prover.vo` be up to date before considering any target that depends on `src/prover.ml`, which I think should be the behavior you want.  I'm not completely sure, though.

**Review by Alizter — APPROVED** [review]
@fajb Are you happy with this being merged as is or are you planning to switch to dune first?

**Comment by fajb** [comment]
@Alizter I'am happy now. It compiles... dune can wait. Thanks

**Comment by Alizter** [comment]
Excellent will merge tomorrow

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
This dev is currently broken on master, as there was a race with #15159.

**Pull request merged**
