### PR TITLE
Deprecate "~=" notation for JMeq in Program.Equality

### PR DESCRIPTION
**Pull request by SkySkimmer**
Because of coq/stdlib#16

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Looks ok to me (but @mattam82 is the first one concerned I guess).

**Comment by ppedrot** [comment]
@SkySkimmer refman not happy

**Comment by SkySkimmer** [comment]
refman now happy

**Review by Alizter — APPROVED** [review]
@SkySkimmer Can you quickly ask @mattam82 about his opinion on this?

**Comment by mattam82** [comment]
Fine with me

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
