### PR TITLE
Backport batch of PRs to v8.12.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@ejgallego You didn't choose your moment well for merging #12363. Basically, I will have to re-prepare this batch of backports.

**Comment by Zimmi48** [comment]
Incidentally, you've already removed the Docker image that v8.12 uses (which explains why https://gitlab.com/coq/coq/pipelines/148917368 is failing :wink:) but this PR fixes it by introducing a v8.12 specific image.

**Comment by ejgallego** [comment]
> @ejgallego You didn't choose your moment well for merging #12363. Basically, I will have to re-prepare this batch of backports.

Actually I was aware of it, why is that a problem? Can't we just merge this tree?

**Comment by ejgallego** [comment]
> Incidentally, you've already removed the Docker image that v8.12 uses (which explains why https://gitlab.com/coq/coq/pipelines/148917368 is failing ) but this PR fixes it by introducing a v8.12 specific image.

I was actually going to introduce the v8.12 image, cool if this PR does it.

**Comment by ejgallego** [comment]
> I was actually going to introduce the v8.12 image, cool if this PR does it.

I merged the OSX PR because it was actually not using docker.

**Comment by Zimmi48** [comment]
>Can't we just merge this tree?

Given that the "Backport PR #...." commits are already merge commits, the idea is usually to merge these batch of backports in fast-forward mode to avoid extra merge commits.

>I was actually going to introduce the v8.12 image, cool if this PR does it.

Yep, I figured that if I didn't alert you about this, we would be duplicating work.

**Comment by ejgallego** [comment]
> Given that the "Backport PR #...." commits are already merge commits, the idea is usually to merge these batch of backports in fast-forward mode to avoid extra merge commits.

I see, IMHO an extra merge commit is not a big deal [unless it breaks tooling tho], but if we want to avoid that we should have v8.12 PRs target this branch instead of v8.12, otherwise the synch seems a bit complex, doesn't it?

**Comment by Zimmi48** [comment]
>unless it breaks tooling tho

It probably doesn't.

>we should have v8.12 PRs target this branch instead of v8.12

Sounds too complex for a case that doesn't happen that often (there are rarely PRs opened against a release branch). Let's see how it goes. You are probably right that an extra merge commit once in a while is probably not a big deal.

**Comment by ejgallego** [comment]
Overlay https://github.com/mattam82/Coq-Equations/pull/309

I will push the rest of PRs soon.

**Comment by Zimmi48** [comment]
CI for Equations failed because you've removed your fork's branch. You should probably push a commit going back to the main repository for Equations (branch `8.12`) to fix it.

**Comment by ejgallego** [comment]
> CI for Equations failed because you've removed your fork's branch. You should probably push a commit going back to the main repository for Equations (branch `8.12`) to fix it.

Indeed i saw that, already done tho I have pinned the particular commit.

**Comment by Zimmi48** [comment]
@gares Can you help debug the HB failure? I strongly doubt that it has any relation to the PRs I'm trying to backport. FYI, this is testing Coq-Elpi `coq-v8.12` together with `v0.9.1`.

**Comment by gares** [comment]
Sorry but I'm a bit lost. Which versions are in 8.12.0 and why did they move? Did I push some ref by mistake?

**Comment by Zimmi48** [comment]
I gave you the versions in my message. One of them is a branch, so it can move.

**Comment by gares** [comment]
My bad, I indeed moved v8.12. I guess the best is to use coq-elpi 1.5.1 and HB 0.10.0 (tags, not branches). Does this work for you?

**Comment by Zimmi48** [comment]
> Does this work for you?

Sure, if they work with Coq 8.12!

**Comment by gares** [comment]
HB 0.10.0 works with both 8.11 and 8.12, they depend on coq-elpi 1.5.x where the x is 0 on 8.11 and 1 on 8.12

**Comment by Zimmi48** [comment]
@JasonGross Is that a spurious failure https://gitlab.com/coq/coq/-/jobs/700548952? I'm restarting the job.

**Comment by JasonGross** [comment]
Belatedly, yes, that failure is spurious.  It got unlucky and timed out after 2 seconds on a file that is supposed to take a fraction of a second.  Most of the time this is not fatal, but there are a few places where such timeouts unluckily result in fatal failures; I'll go add a couple of retries to those spots.

**Comment by Zimmi48** [comment]
@JasonGross Looks like another spurious failure: https://gitlab.com/coq/coq/-/jobs/816046589

**Pull request closed without merging**
