### PR TITLE
Move ltac2 ml files to plugins/ltac2

### PR DESCRIPTION
**Pull request by SkySkimmer**
This matches how it gets installed.

### CODE REVIEW

**Comment by ppedrot** [comment]
I have literally no idea how the build system is working (and I think I don't want to know), but the CI seems quite unhappy.

**Comment by Alizter** [comment]
Why was it in user-contrib to begin with?

**Comment by ppedrot** [comment]
@Alizter a horrible implementation detail that forced plugins in `plugins/` to be loaded with `-R` while plugins in `user-contribs/` where loaded with `-Q`. But there are many files in the Ltac2 plugin whose base name conflicts with other files in the stdlib, so adding it with `-R` was not a viable option, since the loadpath mechanism would find the completely wrong file.

**Comment by SkySkimmer** [comment]
There were several related hacks in the legacy build, I think I removed all of them. Even the test suite looks happy in CI.

**Comment by Zimmi48** [comment]
>a horrible implementation detail that forced plugins in `plugins/` to be loaded with `-R` while plugins in `user-contribs/` where loaded with `-Q`. But there are many files in the Ltac2 plugin whose base name conflicts with other files in the stdlib, so adding it with `-R` was not a viable option, since the loadpath mechanism would find the completely wrong file.

Note that this choice was made at a time when theory files for plugins were kept together with ML code in the `plugins/` directory. Now this has changed: theory files for plugins have moved to `theories/` and only the ML code remains in `plugins/`. Meanwhile, this PR only updates the location of ML files (to make it consistent with the rest of the plugins). It keeps the Ltac2 theory files inside `user-contrib/`.

Note that a next step that would be consistent with the top-level namespace of the Coq stdlib and the Ltac2 stdlib would be to move the two next to each other inside a common directory (that could be named `theories/`).

**Review by jfehrle — APPROVED** [review]
The doc_grammar changes look OK.

**Comment by gares** [comment]
This PR goes toward a better layout, but stops at an intermediate, worse, setup (ltac2 half here half there). I don't get if there is any chance in moving the theory files where they belong, afaict the name conflicts and recursiveness of the load path are still there.

**Comment by SkySkimmer** [comment]
Have you seen the hacks removed from the build system? How is this worse?

**Comment by gares** [comment]
I agree with that, but the fact that Ltac2 is half here half there is not sarisfactory to me. I'm fine with this PR, I just want to know the whole plan.

**Comment by gares** [comment]
Said otherwise, maybe there is another way to skin the cat, which is stop loading the stdlib with -R and just move ltac2 in there full stop. After all we added From for a reason.

**Comment by SkySkimmer** [comment]
All plugins have ml files in plugins/ and v files elsewhere

**Comment by SkySkimmer** [comment]
Having the ltac2 v files in user-contrib hasn't been a problem so far so why bother moving them.
Having the ml files in user-contrib causes issues in the _build_vo layout.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Well, it's not a big problem, but it surely makes things harder to find (also using user-contrib was a hack in the first place).

**Comment by ejgallego** [comment]
@gares there is not real plan, what would you like to see, something such as `theories/stdlib` and `theories/Ltac2` , indeed we called that user contrib as to distinguish the -R vs -Q plan.

[And in fact `theories` is special, as it is the only library compiled with -R by dune, this is a side-effect of the `(boot)` flag]

I think the plan should be to have the stdlib under the `Coq` prefix, there is an issue for it; when I looked at achieving the plan was pretty hard to do, but if we could put all the loadpath code in one place finally we could properly undergo this transition now I think.

**Comment by ejgallego** [comment]
@gares there is not real plan, what would you like to see, something such as `theories/stdlib` and `theories/Ltac2` , indeed we called that user contrib as to distinguish the -R vs -Q plan.

[And in fact `theories` is special, as it is the only library compiled with -R by dune, this is a side-effect of the `(boot)` flag]

I think the plan should be to have the stdlib under the `Coq` prefix, there is an issue for it; when I looked at achieving the plan was pretty hard to do, but if we could put all the loadpath code in one place finally we could properly undergo this transition now I think.

IIRC it was tricky to produce the `You are using library Lists without qualification` warning.

**Review by ppedrot — COMMENTED** [review]
I declare myself incompetent for this change, I'd rather have a build system expert assign.

**Comment by ppedrot** [comment]
Does the fact that the Coq folder is called `Ltac2` and the plugin one `ltac2` matter? For uniformity shouldn't they share the same name?

**Comment by ejgallego** [comment]
> Does the fact that the Coq folder is called `Ltac2` and the plugin one `ltac2` matter? For uniformity shouldn't they share the same name?

For the ml part is not relevant at all, we follow the convention tho as the ocamlfind library is `coq.plugins.ltac2`

For the Coq part it also doesn't matter, the installation directory does, so it is convenient in some setups where you want to do `-Q user-contrib .`

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Async failure not related; gappa missing overlay.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
