### PR TITLE
[API] Remove `open API` in ml files in favor of `-open API` flag.

### PR DESCRIPTION
**Pull request by ejgallego**
Plus some documentation + a fix for the `META` file.

We still have a problematic case in `Grammar_API`.

### CODE REVIEW

**Comment by matejkosik** [comment]
@ejgallego Do you think that you can add `plugis/.merlin` file so that Merlin works as expected also when we edit the implementation of plugins? Here's something that seems to achieve this goal:
```
FLG -rectypes -thread -safe-string -w +a-4-9-27-41-42-44-45-48-50 -open API

S ../API
B ../API

S ../lib
B ../lib


S **
B **

PKG threads.posix camlp5
```
Without this file, Merlin assumes that plugins are using the original modules rather than the ones we have in the "API".

**Comment by ejgallego** [comment]
Yes, we should add a `.merlin` file, however you should use the `REC` flag instead of duplicating all the main configuration.

**Review by ghost — DISMISSED** [review]
Things which I think are missing:
- `plugin/.merlin`
- explanation what do we gain

**Comment by ejgallego** [comment]
> explanation what do we gain

where do you want me to put this?

**Comment by ejgallego** [comment]
Done.

**Comment by matejkosik** [comment]
@ejgallego I don't think I understand why this is a good thing to do (removing `open API` from the implementation of individual plugins). We all know what will, in the end, be happening, but that knowledge will not be available to other people who will try to understand the code (implementation of plugins).

After your changes, the fact that the `API` module is being opened will be clear only if:
- the reader tries to compile the code (I am not sure whether it is OK to expect that)
- the reader will employ `VERBOSE=1` (I am not sure whether we can make an assumption that any reader will now about that possibility)
- the reader will carefully investigate the compiler output

:-(

**Comment by ejgallego** [comment]
Usually, when one changes a linking option, it it not a wise idea to force the code to be updated. For instance this way upstream plugins can work without requiring any patch.

If I am writing a plugin I couldn't care less if "API" is open or not. I care about the exposed interface, and merlin will correctly pick that.

**Comment by ejgallego** [comment]
Said in other words: your approach basically broke every plugin and tool linking to coq in existence without a real need to do so.

**Comment by Zimmi48** [comment]
@matejkosik The solution to the problems you mention is documentation, isn't it? For now, Coq officially provides virtually zero documentation for plugin writers. Creating this documentation should be the top priority.

**Comment by matejkosik** [comment]
@Zimmi48 Just because something can be documented does not make it a good idea.

Imagine that somebody suggest it is OK to include (in Coq source-code) written in language X with an excuse "well, here is a text-book that teaches you language X".

**Comment by Zimmi48** [comment]
No but your opposition was: let's not do this because it will make it hard for the plugin developer to understand what is going on. Well, I'm just saying that this is not a good reason to reject this change IMHO because we are already making plugin developers' life very hard by not having documentation and if we had documentation, then this would of course explain the principle of the API and at least this (what you are linking against when developing a plugin) would be made quite clear.

**Comment by ejgallego** [comment]
At the risk of repeating the obvious, as it stands today "API" is a linking mechanism not a namespacing(*) one, requiring the plugin developers to do `open API` is wrong, not backwards compatible, makes impossible to disable it, and tends to create a mess in the long term.

**Comment by ejgallego** [comment]
Anyways this is not the only option possible; indeed it is easy to imagine to a different design that would favor an `open API` approach; the key here is to study how all the supported linking combinations interact (I can imagine about 6 use cases) and what do we want to do in the future.

So yeah, a bit of further design is needed.

**Comment by ejgallego** [comment]
I think this should be ready to go too, @matejkosik requested a few documentation fixed but IMHO they should happen in a separate commit due to the revertion of the API in 8.7

**Comment by ejgallego** [comment]
The makefile improvement is valid too, (displaying `CAML  file foo             (-open API)`) but IMHO can also go in a separate commit.

**Comment by ejgallego** [comment]
Rebased; I am not sure the makefile hack used to determine the includes is what we want, it seems to introduce an overhead for every call to ocaml.

**Comment by matejkosik** [comment]
> overhead for every call to ocaml

What do you mean?

**Comment by ejgallego** [comment]
> What do you mean?

```makefile
LOCALINCLUDES=$(if $(filter plugins/%,$<),-I lib -I API -open API $(addprefix -I plugins/,$(PLUGINDIRS)),$(addprefix -I ,$(SRCDIRS)))
```

**Comment by matejkosik** [comment]
Is the difference perceptible?

**Comment by ejgallego** [comment]
> Is the difference perceptible?

This is not a problem of perceptibility...

**Comment by matejkosik** [comment]
It is possible that now we need two variables instead of a single one...

One for plugins, one for non-plugins.

**Comment by ejgallego** [comment]
I think so, that would also help with printing the command line.

**Comment by matejkosik** [comment]
Ok. I will have a look.

**Comment by matejkosik** [comment]
> One for plugins, one for non-plugins.

Ok. I've checked. The split wouldn't be pretty because in addition to splitting `LOCALINCLUDES`, we would have to similarly split `MLINCLUDES` and `DEPFLAGS`. After that, we would be forced to split all the `make` targets where these variables are used
- i.e. we would have one set of targets for plugins
- and another set of targets for non-plugins

Only then we would be able to use right flavors of these three variables in the right places.

I am not sure what would we achieved (other than making the makefiles more messy).

**Comment by matejkosik** [comment]
> help with printing

What do you mean?

**Comment by matejkosik** [comment]
@maximedenes @ejgallego What (yet) needs to be done here before it can be merged?

**Comment by Zimmi48** [comment]
The Travis failure is spurious indeed (currently VST is failing in all branches due to the version number).

**Comment by maximedenes** [comment]
> dependency information is computed at each variable use.

Is there still a performance concern?

**Comment by ejgallego** [comment]
IMO just bad makefile style, but this was there before so

**Comment by maximedenes** [comment]
Ok, so let's merge, we can still fix it later.

**Comment by matejkosik** [comment]
Haleluja!

**Pull request merged**
