### PR TITLE
Taking into account the renaming of bound variables for tactics-in-terms

### LINKED ISSUE #7299: Tactics-in-terms confused by section variables and binders with same name
#### Version

All versions since tactics-in-terms.

#### Description of the problem

This was a bad interaction between `ltac:(..)` and sections submitted by @beta-ziliani on coq-club and already discussed [here](https://github.com/coq/coq/pull/307#issuecomment-330970214). 

```coq
Section test.
Variable x : nat.
Check fun x y:nat=>ltac:(exact (x + y)). (* fun _ y : nat => x + y *)
```
Putting it as an issue for the record. A fix is coming.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix, enhancement

Fixes #7299 and grants #3248.

- [ ] Corresponding documentation was added / updated.
- [ ] Entry added in CHANGES.

This PR fixes issues with bound term variables in Ltac (and virtually in Ltac2). The first issue, #7299, is an obvious clash between a  bound variable name and a section variable name. The second issue is more generally about giving a proper meaning to term binders in Ltac expressions such as `constr:(fun x => ltac:(... x ...))` when `x` is not already bound to an Ltac name (e.g. via a `fresh`). It thus grants a wish implicit in issue #3248.

The fix is by taking into account evar context renamings for interpreting tactics-in-terms.

Notes:
- It depends on ~~#307~~ (for a keep-name renaming policy), ~~#7288~~ (for the modular treatment of renaming in pretyping), ~~#7257~~ (for the fix in sensitivity of naming to alphabet), ~~#7274~~ (for improved dependency in return clause). The interesting commits here are "Taking into account evar context renaming for interpreting tactics-in-terms" and "Control tac-in-term process of renaming in GlobEnv rather than in Proofview".
- I did not investigate but this is part of code which is shared by Ltac2, so I would assume that this would also apply to Ltac2. However, it did not out of the box, so, some tweaking is maybe also needed on Ltac2 side, but waiting first for a feedback from @ppedrot.
- This allows to interpret more tactics-in-terms examples, but I don't claim that this is an absolute answer. E.g. mixing  `rename` or `clear` with binders in an LtacX code might lead to strange things. I feel however that we may be able in the longer term to set a kind of type system to track binders (adding, renaming, and removing effects) in LtacX code.

### CODE REVIEW

**Comment by gares** [comment]
I'm sorry but I'm not going to review this PR until its dependencies are merged (see #7167).

**Review by forestjulien — APPROVED** [review]

**Comment by herbelin** [comment]
@ppedrot: Thanks for caring. I rebased but it apparently needs some investigations to know if the failures come from bugs I introduced or from the change of semantics, and, in the latter case, whether the new semantics is arguably better or not.

**Comment by herbelin** [comment]
@ejgallego (or @zimmi48): This PR fails with Dune build, suspectingly due to a question of dependency (new dependency of `Pretyping` in `Stdarg` apparently not taken into account as a needed compilation dependency).

I tried to reproduce locally by doing `make -f Makefile.dune world` but this fails (Dune 1.2.1) with:
```
dune build  @vodeps
File "plugins/btauto/dune", line 18, characters 7-48:
18 |  (deps (:pp-file ../../theories/Init/Prelude.vo)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unknown constructor DYNOBJ
```
What should I do? What am I missing?

**Comment by ejgallego** [comment]
> What should I do? What am I missing?

Hi @herbelin , this is due to a dirty tree from the a previous makefile. `make clean` or `git clean -fxd` [use with care this will discard changes] should solve it.

**Comment by ejgallego** [comment]
@herbelin I should be on gitter if you have any question regarding Dune or the enforcement of deps.

**Comment by herbelin** [comment]
@ejgallego: Now it works (I suspect it was the `.*d` files which had to be removed).

So, the problem is apparently that I'm now using `Stdarg` in `pretyping` while the file is still in `interp`. Moving `Stdarg` to pretyping would indirectly bring other files, like `constrexpr`, so I need to find something else. I'm only needing `wit_ident`.

An easy solution would be to move `wit_ident` from `Stdarg` to `Geninterp`, as an exceptional case. @ppedrot, would you be ok?

The reason I'm using `wit_ident` in (actually) `GlobEnv` is to give a better error message when an Ltac `ident` is expected to be a term but has another type. @ppedrot, I know that you don't like this part of the code very much, but would you accept an exceptional case in `Geninterp` to make things simpler (otherwise, I/we'll have to think further with alternatives). 

If yes, there is also the question of whether I keep `Stdarg.wit_ident` as a copy of `Geninterp.wit_ident` or if I change all occurrences of `Stdarg.wit_ident` in the code to `Geinterp.wit_ident`?

**Comment by herbelin** [comment]
I don't use it directly in the error message. Actually, I forgot that I use it for more than the error message. I use it also for the interpretation, to pass to Ltac the information that a variable, as in say `constr:(fun x x => ltac:(... x ...))` has been renamed.

**Comment by ppedrot** [comment]
I don't think moving `wit_ident` to an ad-hoc place is a good idea. It'll break many EXTEND statements, and furthermore it will make the life of macro writers harder. I am trying to understand why you need that in the code, let's see if there is an alternative solution.

**Comment by herbelin** [comment]
> I don't think moving wit_ident to an ad-hoc place is a good idea

I could try to use a backward reference... E.g. that the function `interp_glob_genarg`, and maybe also `interp_ltac_variable`, are set to non-identity function by the ltac plugin?

**Comment by ppedrot** [comment]
Sorry about the added delay, but I think I'd really try to understand this PR before going further. I have a queasy sensation that it will make the code more intricate for the purpose of handling Ltac quirks. Let me signal here when this is done, although it will probably require a viva voce discussion with @herbelin.

**Comment by herbelin** [comment]
> although it will probably require a viva voce discussion 

Marseille LHC 17-18 octobre?

**Review by ppedrot — COMMENTED** [review]
I am artificially commenting on this PR to remove if from my "to review" list, but I definitely didn't remove it from the list of PRs I am watching. I forgot to bring it on the table at the last WG, but hopefully we'll meet some time soon to discuss it.

**Comment by ppedrot** [comment]
This seems to have been mostly an experiment and getting stale. The issue this is trying to solve is deeply rooted into the (non-)semantic of Ltac1 binders, and this PR breaks a lot of stuff. As such, I believe that if we *really* want to go that way it needs a more thorough design phase via a CEP. In the meantime, I am closing this.

**Comment by herbelin** [comment]
>  if we really want to go that way it needs a more thorough design phase via a CEP. In the meantime, I am closing this.

Working on the code is useful to experiment but working through a CEP is also reasonable. Anyway, it seems that one the main issue is also to understand what plans we give us about Ltac2. If we put our forces in Ltac2 (including maybe a way to mechanically port the code, though I don't know how realistic it is), it might be better to develop a support for binding of bound variables on top of Ltac2. Of course, it depends also on your own projects.

**Pull request closed without merging**
