### PR TITLE
Add option Typeclasses Default Generalize Instance Variables.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure the \ref in the documentation is the correct one.

Not sure I completely understood what it's doing, as I feel like the meaning of `Implicit` and `Explicit` are inverted.

Ping @RalfJung, see #6030.

### CODE REVIEW

**Comment by Zimmi48** [comment]
You should probably turn this option off in the compatibility file `Coq87.v`.

**Comment by SkySkimmer** [comment]
>You should probably turn this option off in the compatibility file Coq87.v.

No, the default behaviour is the 8.7 behaviour.

**Comment by RalfJung** [comment]
Thanks!

IIRC 8.7 does *not* generalize typeclass instance variables per default, but only if `Generalizable All Variables` is set.

Also, what is the interaction of the new option with `Generalizable All Variables`?

**Comment by SkySkimmer** [comment]
It only generalizes those variables which are generalizable.
Basically we have preexisting syntax `Instance foo : !bar` which disables generalization, new syntax 
```
Instance foo : `bar
```
which enables it and without an explicit marker the option decides which is picked (with 8.7 always picking `)

Github using ` for code blocks is a pain.

**Comment by RalfJung** [comment]
But that changes behavior, right?  The following currently passes:
```
Class Bar (n:nat) := {}.
Fail Instance bar : Bar n := {}.
```
With your PR, because it defaults to `` ` ``, this will pass, no?

**Comment by SkySkimmer** [comment]
It already defaults to `` ` ``. This PR only adds an option to switch the default and explicit syntax to pick `` ` ``.

**Comment by RalfJung** [comment]
Ah, so `` ` `` actually just has no effect unless `Generalizable All Variables` is set?

**Comment by SkySkimmer** [comment]
It's probably more complicated than that. `` ` `` avoids running some `implicit_application` transformation on the type of the instance, but I don't quite understand what's going on.
Could use some help.

Like what is going on here 95dd7304f68eb155f572bf221c4d99fca85b700c

**Comment by SkySkimmer** [comment]
If I come back to this issue I probably won't base my work on this PR.

**Comment by RalfJung** [comment]
I opened an issue at https://github.com/coq/coq/issues/6888to make sure this doesn't get forgotten.

**Pull request closed without merging**
