### PR TITLE
Remove absurd_hyp.

### PR DESCRIPTION
**Pull request by Zimmi48**
Let's see if this is used.

- [x] Added **changelog**.

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Zimmi48** [comment]
@coqbot run full CI

(the previous pipeline had lots of runner failure errors and I want to keep it untouched)

**Comment by Alizter** [comment]
@Zimmi48 Can you fix the lint?

**Comment by Zimmi48** [comment]
The lint job was fixed in #16674. We can reasonably think that there are no other error given that the part of the lint job that failed comes last. Making the job green in this PR would require triggering a new pipeline. This doesn't sound such a great idea to me.

**Comment by Alizter** [comment]
OK I trust that it will work then.

@coqbot merge now

**Pull request merged**
