### PR TITLE
Removing support for 8.5 compatibility.

### PR DESCRIPTION
**Pull request by herbelin**
See #882.

### CODE REVIEW

**Comment by herbelin** [comment]
I'm not the one who will push strongly towards merging this. Seeing how some regressions of 8.4 are still not resolved, I don't see it as a bad thing that we keep a compatibility flag `V8_5` for a while more.

**Comment by Zimmi48** [comment]
I'd suggest to go further and remove in this PR the code for the 8.5 compatibility options that were deprecated in 8.6 / 8.7. Otherwise the code removal induced by this PR is quite insignificant.

**Comment by herbelin** [comment]
And what to do about #884, supposed to be related to a 8.3 compatibility? I'm not very fond of the `VOld` version number, since it will change meaning by removing `V8_5`. So,
- either we remove the unactivated `compat "8.3"` in notations, considering that it was an error;
- or we change them to `compat "8.6"` and activate them, justifying the change to `"8.6"` by them being inactivated until now.

(I'm then not proposing keeping the status quo, i.e. keeping `VOld` to mean <= 8.4, since it does not seem popular.)

**Comment by Zimmi48** [comment]
I suppose that these PRs would be worth discussing at the WG...

**Comment by ejgallego** [comment]
It could be worth giving this a try again.

**Comment by Zimmi48** [comment]
My understanding is that this was blocked on the question of `VOld` (i.e. deprecated notations). I tried to summarize here https://github.com/coq/coq/pull/884#issuecomment-351010823 what I think was the conclusion of the last WG. If this conclusion is implemented, then nothing is blocking this PR anymore (and no one has ever opposed to it).

**Comment by ejgallego** [comment]
Well, I guess the notations could stay [making them 8.6 compat], but we could remove the rest, right?

**Comment by Zimmi48** [comment]
I'd like to request that a solution be found quickly so that this can get merged. The removal of lots of deprecated options is depending on this PR, and in turns a lot of code cou

**Comment by Zimmi48** [comment]
@herbelin Any way we can move forward on this topic? I would like to be able to get rid of the compatibility code in `tactic/classes.ml` before diving again into #721, and this depends on this PR.

**Comment by herbelin** [comment]
I'm not sure to have the best overview of all the issues and answers to them. The idea was to follow this [comment](https://github.com/coq/coq/pull/884#issuecomment-351010823) and to renounce to the 8.3 deprecation notations, right? Then, OK to me.

If so, is what remains to do after removal of the deprecated flag in the corresponding aliases, to rebase the current PR? And if so, would you (@Zimmi48) be ok to do it?

**Comment by Zimmi48** [comment]
Superseded by #6791.

**Pull request closed without merging**
