### PR TITLE
Partac: don't drop critical exceptions

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure why exactly, but without this change raising a critical
exception (eg anomaly, assert false) in a par: tactic gets ignored.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I'm OK with this PR, but I don't have the time to see if CI is ok. I see these job fail often. Is it spurious/unrelated?

**Comment by SkySkimmer** [comment]
yes

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
