### PR TITLE
Sanitize instance interpretation

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Seems pretty self explanatory to me.

**Comment by mattam82** [comment]
LGTM

**Comment by Zimmi48** [comment]
@mattam82 FYI GitHub provides a built-in way to "approve the changes" (in "Files changed" tab by clicking the "Review changes" button). This way, the PR won't be marked as "Awaiting requested review from mattam82").

**Comment by SkySkimmer** [comment]
@mattam82 could you click the button?

**Pull request merged**
