### PR TITLE
deprecate Cd command

### PR DESCRIPTION
**Pull request by Alizter**
Keeping this as a draft for now. We need to provide output directory support for extraction first.

### CODE REVIEW

**Comment by Alizter** [comment]
@herbelin @SkySkimmer There was this plan to deprecate Cd entirely because it was only used in extraction. It might help with the output directory PR. If you disallow output directory and Cd to be used, it might simplofy the implementation.

We can deprecate Cd as extraction can now have its output directory set IIRC. That was the only blocker.

**Comment by Alizter** [comment]
Oh I see that you've already seen this so nevermind then.

**Comment by herbelin** [comment]
I realize that I apparently misinterpreted this PR as an issue and opened #17403 which at the end is redundant. I can close #17403 so that you can reopen #16119.

**Comment by Alizter** [comment]
@herbelin I won't have time to work on this so feel free to take over. I just wanted to make sure you knew about it.

**Pull request closed without merging**
