### PR TITLE
[make] Move makefiles to their own subdirectory.

### PR DESCRIPTION
**Pull request by ejgallego**
This helps with #6137. I didn't complicate the system a lot, just
added a new makefile prefix to the proper places.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks @ejgallego! I wondered if it could make sense to have the Makefiles for the checker and the IDE in their respective sub-directories, like for the test-suite. But then I remembered this:

https://github.com/coq/coq/blob/a77f3a3e076e273af35ad520cae2eef0e3552811/Makefile#L14-L19

So I guess that your proposal is more consistent with this view.

**Comment by ejgallego** [comment]
Despite the "single" makefile view, I think the tradeoff on removing the makefiles for the checker and the IDE are positive and I have plans for that, it is just not prioritary now.

Recall the experiments done in: 
even if ocamlbuild was quite simpler than the current make system, it still didn't manage some critical aspects such as installation etc... However, `jbuilder` is working pretty well and indeed _does_ avoid the compositionality problem, so IMHO at some point I hope we can move forward this way.

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
gitlab uses `make -f Makefile.ci` to avoid rebuilding .ds so needs to be changed.

**Comment by ejgallego** [comment]
I don't have the energy to rebase this once more.

**Comment by Zimmi48** [comment]
Too bad :(

**Comment by ejgallego** [comment]
The tree is here https://github.com/ejgallego/coq/tree/tree+clean_mk if someone feels like merging it.

**Pull request closed without merging**
