### PR TITLE
Rename `perf/perf.c` into `perf/coq_perf.c`

### PR DESCRIPTION
**Pull request by rlepigre**
This makes it more obvious that the corresponding dll that is installed comes from Coq (requested by @JasonGross in https://github.com/coq/coq/pull/17744).

### CODE REVIEW

**Review by JasonGross — APPROVED** [review]
Thank you!

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
@rlepigre This was not adequate, I'm still seeing
```
dh_missing: warning: usr/lib/ocaml/stublibs/dllperf_stubs.so exists in debian/tmp but is not installed to anywhere
```
[here](https://launchpadlibrarian.net/694948137/buildlog_ubuntu-lunar-amd64.coq_8.master~git~202310281847+24387-0~daily403-9e891cf7b2~ubuntu23.04.1_BUILDING.txt.gz).  Does https://github.com/coq/coq/blob/9e891cf7b24a1b220ffb24deb1aec51207fe3943/perf/dune#L2 need to be changed to `coq_perf`?  Or does https://github.com/coq/coq/blob/9e891cf7b24a1b220ffb24deb1aec51207fe3943/perf/dune#L4 need to be changed to `coq-core.coq_perf`?  (cc @coq/build-maintainers @ejgallego?)

**Comment by rlepigre** [comment]
> @rlepigre This was not adequate

Oh no, I should have checked, sorry!

I would put all my money on your first suggestion, in which case the renaming of the C file was not necessary. I don't have time to fix this right now, but if you don't get to it first I'll make an MR later in the week.

**Pull request merged**
