### PR TITLE
Bump year in headers.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Some files have a header without years, eg https://github.com/coq/coq/blob/trunk/lib/cErrors.mli
Is that normal?

**Comment by maximedenes** [comment]
I have no idea if it was made on purpose or not. I believe the dates in copyright notices are optional nowadays, but I'm not a lawyer. It would be good to know, though, we could get rid of this task of updating the headers.

**Comment by Zimmi48** [comment]
@maximedenes Copyright notices are completely optional but are recommended (especially by the FSF) as this allows to track down the origin of a single file.
However when you put copyright notices, the FSF has clear recommendation and this *does* include indicating the dates: https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html
FTR, doing mistakes in copyright notices is not supposed to prevent copyright enforcement (but I suppose these mistakes shouldn't be done purposely).

**Comment by ejgallego** [comment]
The header stuff comes from the time where file distribution didn't include file metadata, recall the CVS `$Header` keyword, what a pain! Note that you were supposed to include author information and a bunch of other things as indicated by GPL 2.

Nowadays, the preferred form for code distribution is the full git repository, thus, including such metadata in the file is not necessary as there is a cryptographically signed record containing all the needed information in `.git`.

[1] http://www.badgertronics.com/writings/cvs/keywords.html

**Pull request merged**
