### PR TITLE
Delay lifting in Evarsolve aliasing.

### PR DESCRIPTION
**Pull request by ppedrot**
It turns out that eagerly computing the lift of huge terms when it is not used is not great for performance.

Fixes part of #11488.

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
It took me forever to get that the `t' -> _` was indeed a fix on top of another PR of yours... so it seems OK to me.

I don't like the API of get_expansion_var, but given the two clients I don't know how to improve it, so I guess I should just live with it.

**Comment by ppedrot** [comment]
@gares are you assigning?

**Comment by gares** [comment]
I'd like a bench, the code makes sense, but I've no idea if it is faster/slower.

**Comment by SkySkimmer** [comment]
bench just started (845)

Gaëtan Gilbert

**Comment by ppedrot** [comment]
No observable difference on our bench:
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │    mem faults     │
│                             │                         │                                             │                                             │                               │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   48.97   49.47 -1.01 % │      134596819876      134685898873 -0.07 % │      175941958572      175948388800 -0.00 % │     568672     568664 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1352.56 1363.34 -0.79 % │     3771675141715     3799738041507 -0.74 % │     6725719885817     6770348240108 -0.66 % │    1301668    1300052 +0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-hott │  337.65  339.28 -0.48 % │      920270748194      920508946903 -0.03 % │     1483767287390     1483449830217 +0.02 % │     592324     592344 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-coqprime │   84.28   84.56 -0.33 % │      232517495096      232332047274 +0.08 % │      335307545608      334774615628 +0.16 % │     756264     757072 -0.11 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2089.45 2095.61 -0.29 % │     5831464521052     5848903213183 -0.30 % │    11489492431891    11488905775380 +0.01 % │     952316     952360 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-sf-plf │   43.86   43.98 -0.27 % │      122527772121      122375011749 +0.12 % │      168873721779      168848273201 +0.02 % │     488924     494884 -1.20 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-fiat-crypto-legacy │ 6071.58 6085.47 -0.23 % │    16904583761778    16942220207458 -0.22 % │    28695324535383    28658132382541 +0.13 % │    2368524    2368708 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  599.48  600.10 -0.10 % │     1678241443283     1679355843491 -0.07 % │     2697145744099     2696472848754 +0.02 % │    3192392    3196164 -0.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1276.50 1277.29 -0.06 % │     3562387437230     3558764073262 +0.10 % │     5032913371850     5032821154515 +0.00 % │    1825780    1825656 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4231.43 4233.34 -0.05 % │    11749322658784    11761975753803 -0.11 % │    19334424380164    19332186673847 +0.01 % │    2364000    2362452 +0.07 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-rewriter │  558.75  558.79 -0.01 % │     1550904174064     1552410078298 -0.10 % │     2393565832236     2392576695974 +0.04 % │    1000588     997740 +0.29 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4044.83 4043.97 +0.02 % │    11263573683945    11258222886405 +0.05 % │    21426241179656    21430577519671 -0.02 % │    1112180    1119744 -0.68 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1062.90 1062.05 +0.08 % │     2961325596924     2957857038183 +0.12 % │     4729017739372     4729673872075 -0.01 % │     930372     930372 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                    coq-corn │ 1425.56 1423.66 +0.13 % │     3976918475815     3966507046751 +0.26 % │     6157983480895     6157665667615 +0.01 % │     871324     871240 +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  145.26  145.04 +0.15 % │      404827613854      403786346690 +0.26 % │      538888658613      538867002732 +0.00 % │     610400     613900 -0.57 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  175.25  174.96 +0.17 % │      488525207609      487361025897 +0.24 % │      697051599351      696843796773 +0.03 % │     793112     793104 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1525.11 1522.05 +0.20 % │     4254955203160     4248455886702 +0.15 % │     6514806758136     6513888332765 +0.01 % │    1383340    1382660 +0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   49.08   48.98 +0.20 % │      136321182581      136063224950 +0.19 % │      189820390661      189772983774 +0.02 % │     557340     557180 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1533.62 1530.45 +0.21 % │     4273840882865     4264865424791 +0.21 % │     6176574723348     6172970291009 +0.06 % │    1134136    1131016 +0.28 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  163.38  163.00 +0.23 % │      454508902008      453778738758 +0.16 % │      638763606430      638710392026 +0.01 % │     811500     804128 +0.92 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-coqutil │   57.76   57.62 +0.24 % │      160012632319      160058487188 -0.03 % │      203788989672      203619417648 +0.08 % │     537520     525008 +2.38 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-flocq │  199.10  198.57 +0.27 % │      552919164234      551199380180 +0.31 % │      715258924514      715136458100 +0.02 % │     927240     927200 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-color │  654.46  652.19 +0.35 % │     1825540148925     1819549264930 +0.33 % │     2322227174374     2321820637800 +0.02 % │    1124196    1123824 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  262.10  261.15 +0.36 % │      729869658442      727542438014 +0.32 % │     1123502677346     1122974579272 +0.05 % │     790160     790164 -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│            coq-math-classes │  205.80  204.99 +0.40 % │      574503325746      572863690593 +0.29 % │      769819778325      769626388049 +0.03 % │     519420     517216 +0.43 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  225.58  224.68 +0.40 % │      623738762880      622604706592 +0.18 % │     1057292930703     1056046491412 +0.12 % │    1139800    1139860 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│              coq-coquelicot │   73.77   73.45 +0.44 % │      202561972682      201695182214 +0.43 % │      266822601526      266390156393 +0.16 % │     655212     655296 -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                   coq-verdi │  119.44  118.91 +0.45 % │      329460248770      328657393015 +0.24 % │      426529928807      426121418837 +0.10 % │     538536     538392 +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│               coq-fiat-core │  102.65  102.15 +0.49 % │      289928364469      289111625188 +0.28 % │      388751456140      388153301921 +0.15 % │     498208     498204 +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│       coq-performance-tests │   12.13   12.06 +0.58 % │       33217720346       33212515666 +0.02 % │       57320225694       57253515029 +0.12 % │     454676     462312 -1.65 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼───────────────────┤
│                 coq-bignums │   63.08   62.64 +0.70 % │      174376480803      173802606965 +0.33 % │      244390018759      244388284794 +0.00 % │     483156     483080 +0.02 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴───────────────────┘
```

**Comment by ppedrot** [comment]
This is ready to go.

**Pull request merged**
