### PR TITLE
Move serialization functions out of Stm

### PR DESCRIPTION
**Pull request by ejgallego**
Serialization should be specific to each particular backend, so we let
the Stm clients choose how the send the nodes.

This should be quite safe to pull in. Test suite passes.

Related to #180

### CODE REVIEW

**Comment by gares** [comment]
Fine with the idea, but I dislike Inl/Inr (in general, it's like monads, it irritates my skin) and here I guess an option type is just fine.

I'll merge it this afternoon.

**Comment by ejgallego** [comment]
Cool, thanks Enrico! Give me 10 minutes to push a fix for your comments.

**Comment by ejgallego** [comment]
Ok @gares , this is ready to merge now IMO.

**Comment by ejgallego** [comment]
Integrated in #180

**Pull request closed without merging**
