### PR TITLE
Making management of installation directories more structured, more uniform

### PR DESCRIPTION
**Pull request by herbelin**
This is an attempt to make more uniform and more robust the management of installation directories.

- There are three different installation layouts:
  - dispatched over directories shared by multiple application as in unix
  - self-contained style like in windows
  - local pseudo-installation as with option -local (e.g. not any more looking for the documentation in "" in -local layout while the doc is nevertheless there in subdirectory doc, and similarly for datadir and configdir).
- The configuration for these layouts is centralized in configure.ml (no more repetition of where the standard library is in 3 different files - it was inconsistent previously).
- Relocability of the installation is detected for all installation directories (doc, config, data) and not only for the standard library. It is now detected also when -prefix is given.
- This fixes what seems to be a few other bugs
  - the default config directory was prefix/etc/xdg/coq while it should be always be /etc/xdg/coq under unix scheme, no?
  - under windows-style layout, the default directories for man, data and latex were share/coq, share/man, share/doc/coq which seems to be for the unix scheme

There is an extra dependency of coqide and coqdoc on envars.ml, I hope this is ok.

By doing this simplification and uniformisation, I hope making the life of contributors touching at this part of the system easier, so review from specialists of this part of the system, and more specifically from windows/macos installation specialists is needed.

This can of course be committed to 8.6 (in that it fixes a number of inconsistent behaviors) but I would prefer not if time needed for reviewing would mean delaying the beta1.

### CODE REVIEW

**Comment by maximedenes** [comment]
Oh, I had missed this PR. It seems very nice, I'll try to review it after the 8.6 release.

**Comment by herbelin** [comment]
Rebased on trunk + fix for preserving relative use of `/etc/xdg/coq` when an explicit prefix is given, as it is done currently.

**Comment by JasonGross** [comment]
Does this change where things are actually installed?  (Will I have to update my [debian packaging](https://github.com/JasonGross/coq-packaging) [scripts](https://github.com/JasonGross/coq-debian-build-scripts) when this lands?)

**Comment by herbelin** [comment]
Current default configuration with the PR for win32 without `-prefix` is unchanged:
  - the Coq binaries will be copied in C:/coq/bin
  - the Coq library will be copied in C:/coq/lib
  - the Coqide configuration files will be copied in C:/coq/config
  - the Coqide data files will be copied in C:/coq/share
  - the Coq man pages will be copied in C:/coq/man
  - the Coq documentation will be copied in C:/coq/doc
  - the Coq Emacs mode will be copied in C:/coq/emacs
  - the Coqdoc LaTeX files will be copied in C:/coq/latex

Current configuration with the PR for win32 with `-prefix foo` is 
  - the Coq binaries will be copied in /foo/bin
  - the Coq library will be copied in /foo/lib
  - the Coqide configuration files will be copied in /foo/config
  - the Coqide data files will be copied in /foo/share
  - the Coq man pages will be copied in /foo/man
  - the Coq documentation will be copied in /foo/doc
  - the Coq Emacs mode will be copied in /foo/emacs
  - the Coqdoc LaTeX files will be copied in /foo/latex

while in trunk, it is currently:
  - the Coq binaries will be copied in /foo/bin
  - the Coq library will be copied in /foo
  - the Coqide configuration files will be copied in /foo/config
  - the Coqide data files will be copied in /foo/share/coq
  - the Coq man pages will be copied in /foo/share/man
  - the Coq documentation will be copied in /foo/share/doc/coq
  - the Coq Emacs mode will be copied in /foo/emacs
  - the Coqdoc LaTeX files will be copied in /foo/latex

Is the difference a problem? (It is easily configurable.)

Current default configuration with the PR for unix without `-prefix`:
  - the Coq binaries will be copied in /usr/local/bin
  - the Coq library will be copied in /usr/local/lib/coq
  - the Coqide configuration files will be copied in /etc/xdg/coq
  - the Coqide data files will be copied in /usr/local/share/coq
  - the Coq man pages will be copied in /usr/local/share/man
  - the Coq documentation will be copied in /usr/local/share/doc/coq
  - the Coq Emacs mode will be copied in /usr/local/share/emacs/site-lisp
  - the Coqdoc LaTeX files will be copied in /usr/local/share/texmf/tex/latex/misc

Current configuration with the PR for unix with `-prefix foo` is (with a change for LaTeX files - currently in `/foo/share/emacs/site-lisp`!)
  - the Coq binaries will be copied in /foo/bin
  - the Coq library will be copied in /foo/lib/coq
  - the Coqide configuration files will be copied in /foo/etc/xdg/coq
  - the Coqide data files will be copied in /foo/share/coq
  - the Coq man pages will be copied in /foo/share/man
  - the Coq documentation will be copied in /foo/share/doc/coq
  - the Coq Emacs mode will be copied in /foo/share/emacs/site-lisp
  - the Coqdoc LaTeX files will be copied in /foo/share/texmf/tex/latex/misc

Each individual directory remains configurable independently of the other.

**Comment by JasonGross** [comment]
What's the current trunk configuration with `-prefix` on Unix?  The real question is, do any of the paths in [debian/rules](https://github.com/JasonGross/coq-packaging/blob/trunk/debian/rules) or any .install or .install.in files in [debian/](https://github.com/JasonGross/coq-packaging/tree/trunk/debian) need to be changed?
 
> the default config directory was prefix/etc/xdg/coq while it should be always be /etc/xdg/coq under unix scheme, no?

Possibly.  Will things break things if I install multiple versions of Coq into different prefixes?

**Comment by JasonGross** [comment]
I guess `usr/share/emacs/site-lisp/coqdoc.sty` will be in a different location now?

**Comment by herbelin** [comment]
I don't know well enough debian packaging to answer. The interface of `configure` did not change and you continue to have full control to installation paths if you use `-mandir`, `-configdir`, `-emacslib`, `-coqdocdir`, `-libdir`, `-bindir`, `-datadir`, `-docdir`.

If you have a `-prefix /foo` and no `-coqdocdir`, the proposal is that `/foo/emacs/site-lisp/coqdoc.sty` will be in `/foo/share/texmf/tex/latex/misc`,as proposed to you if you had no `-prefix`, what looks  reasonable.

Note that I changed yesterday the `/etc/xdg/coq/` setting in `-prefix` mode: it is now relative.

> Will things break things if I install multiple versions of Coq into different prefixes?

As far as I can tell, no as far  installation is concerned, but the `/etc/xdg/coq/` thing reminds me that configuration files, e.g. in $HOME, are at the same place for all versions. So, maybe this is something to thing about...

**Comment by maximedenes** [comment]
This change looks good to me. IIUC, `etc/xdg/coq` will be located relatively to a prefix if one is provided. I think it is the right behavior. In particular, users providing a prefix in a directory they own should not need sudo rights to install.

I'm not qualified to understand all the implications under Windows, but it will be enough to carefully test the packages.

@herbelin Would you mind rebasing? Thanks!

**Pull request merged**
