### PR TITLE
Gitlab: don't cache opam

### PR DESCRIPTION
**Pull request by SkySkimmer**
The current system is too unreliable. I ended up having to delete cache again today because of an error linking gtk which came up a few days ago.
I don't think the cache is giving us enough speedup to justify it.

@ejgallego was talking about having a custom docker image with opam packages preinstalled but I don't know how far off that is. Until then we can live without the cache.

### CODE REVIEW

**Comment by ejgallego** [comment]
> @ejgallego was talking about having a custom docker image with opam packages preinstalled but I don't know how far off that is. Until then we can live without the cache.

That shouldn't be too hard. I am not sure I like the cache going away just like that, why is the gtk problem arising? That seems strange. I'd rather try to understand why the cache goes bad.

Also, I am not sure the base build should be building so much stuff. At least in the original travis setup, the basic build left out coqide and documentation on purpose.

**Comment by ejgallego** [comment]
By the way that's the template to build a proper Docker `opam` image: https://github.com/ocaml/opam-dockerfiles

**Comment by ejgallego** [comment]
The way I see it we should only have to modify the script to:
- install the extra apt deps.
- install the extra opam switches and packages.

**Comment by SkySkimmer** [comment]
Would we install all the switches in the same image or have 1 image/switch?

Gaëtan Gilbert

**Comment by ejgallego** [comment]
> Would we install all the switches in the same image or have 1 image/switch?

I guess installing all switches in one image is simpler. I am not sure if you can pull a different docker image based on env vars.

**Comment by ejgallego** [comment]
> I guess installing all switches in one image is simpler. I am not sure if you can pull a different docker image based on env vars.

So yeah, in order to keep this in sync we should add the docker script to the coq repos and have it read the variables in `.gitlab.yml`

**Comment by ejgallego** [comment]
> Why would we use env vars?

Well, if we have several images the `image: ocaml/opam:ubuntu` field in `.gitlab-ci.yml` has to depend on the current matrix somehow, right?

**Comment by ejgallego** [comment]
Yeah I don't think that's possible.

In other news, the new runner has significantly more cores, however the Xeon CPUs are quite slower than the ones used in the first "test runner". So indeed timeout has to around 80 minutes I'm afraid.

Ahhhhh.

**Comment by SkySkimmer** [comment]
>Well, if we have several images the image: ocaml/opam:ubuntu field in .gitlab-ci.yml has to depend on the current matrix somehow, right?

We just override `image:` for the BE and the 32bit jobs. There is no matrix.

**Comment by ejgallego** [comment]
> We just override image: for the BE and the 32bit jobs. There is no matrix.

Can you do that?

Anyways maintaining images is kinda expensive so I do prefer to have a single coq-dev image. In the future, you could for example keep that docker imagine synchronized with `dune` workspaces, giving thus a more uniform environment.

**Comment by ejgallego** [comment]
I am OK merging this but I'd rather try to understand why the GTK does happen. I have the feeling that we may be missing something so I'd be better to understand what is going on instead of trying to use a big `rm -rf` hammer.

**Comment by ejgallego** [comment]
Well, indeed I am not merging this as-is. It seems that the handling of `EXTRA_PACKAGES` is a mess in our current gitlab setup so indeed that variable is incorrectly set and as a consequence GTK is not installed when it should.

**Pull request closed without merging**
