### PR TITLE
Produce correct error paths when compiling stdlib

### PR DESCRIPTION
**Pull request by SkySkimmer**
I tried to figure out how to get dune to run from the right directory to get nice paths but couldn't.

Therefore instead I made a way to get coq to report a different path.

### CODE REVIEW

**Review by ejgallego — DISMISSED** [review]
I suggest we fix the rules instead of adding this, I can try to give it a go next week, what has to happen for a file `Lib/A.vo` is:

```lisp
(rule
  (targets A.glob A.vos A.vo)
  (deps ../Init/Prelude.vo ../Lib/Foo.vo)
  (action
   (run coqc -R ../. Coq  %{dep:DecimalString.v})))
```

needs to become:

```lisp
(rule
  (targets A.glob A.vos A.vo)
  (deps ../Init/Prelude.vo ../Lib/Foo.vo)
  (action
   (cd ../.. (run coqc -R theories Coq %{dep:theories/Lib/A.v}))))
```
which is doable, and that's actually what the stuff for `(coq.theories ...)` and OCaml does.

We could copy the Dune API design in our own gen_rules, the api basically has a `~dir` parameter to run, which indeed sets the directory where a command will be ran from; we already have the right infrastructure to relocate paths in our gen_rules.

**Comment by SkySkimmer** [comment]
>I suggest we fix the rules instead of adding this

That's beyond my capacity, faced with no fix or this PR I choose this PR

**Comment by ejgallego** [comment]
> > I suggest we fix the rules instead of adding this
> 
> That's beyond my capacity, faced with no fix or this PR I choose this PR

I will give it a go then ASAP, sorry for the wait on fixing that bug.

IMO we should avoid the pattern that is so present in Coq codebase of adding hacks to lower layers to cover bugs in the clients.

**Comment by ppedrot** [comment]
Can we get this issue fixed? It's my n°1 annoyance w.r.t. dune builds.

**Review by Alizter — APPROVED** [review]
If it works it works. I agree with Emilio that there is a better fix, but I don't see any point in blocking merging this as it requires time from Emilio or me that we don't have at the moment. When we do get around to fixing it we can always revert.

If this causes any issues, we can always revert.

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by ejgallego** [comment]
Please don't override my request for changes without consulting me first.

**Comment by Alizter** [comment]
@ejgallego You mentioned that you would have a go a week ago and never got round to it. We can always revert. I don't see the point in blocking this.

**Comment by ejgallego** [comment]
You don't see the point but I do.

**Comment by Alizter** [comment]
If you feel that strongly then you can revert. Just trying to make the lives of other devs easier.

**Comment by ejgallego** [comment]
And for some others harder!

**Comment by Alizter** [comment]
https://github.com/coq/coq/pull/17380

**Pull request merged**
