### PR TITLE
Generalizing "Load ident" into "Load qualid" and clarifying difference with "Load file"

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** Feature, cleanup

We generalize `Load ident` to `Load qualid`: the file is found by looking for a `.v` file in the loadpath to which the logical path `qualid` refers. This differs from `Load "file"` which, if the name is not absolute, looks in the physical part of the loadpath for the first file it finds that ends in `file`.

Before, `Load ident` was working like `Load "ident"`. Assuming `-R` is used, and unless there is an ambiguity in finding `ident.v`, in which case it now fails while before it was choosing one of the files, this should work the same. Using `-Q` however requires now to qualify the name enough (maybe could we complete the picture by adding `From qualid Load qualid.` and get a nice consistency with `Require`?).

Question: shouldn't we forbid `Load "file"` when `file` is not an absolute name? It seems reasonable to use a qualid and look in the loadpath whenever we have a relative file name in mind?

- [ ] Added **changelog**.
- [x] Added / updated **documentation**.

### CODE REVIEW

**Comment by ppedrot** [comment]
I thought we were on our way to deprecate Load, not extend it.

**Comment by Alizter** [comment]
I was also under that impression.

**Comment by herbelin** [comment]
> I thought we were on our way to deprecate `Load`, not extend it.

No opinion on deprecating or not. My point is mostly that if we don't deprecate it, let's give it at least a clearer, more robust status, a bit like an equivalent of `Include` (over "self") but for files.

**Comment by herbelin** [comment]
The bedrock2 error is indeed due to `Load` now respecting `-Q` and `-R` in the PR. Unclear why bedrock2 would need this `Load` actually.

**Comment by ppedrot** [comment]
> The bedrock2 error is indeed due to Load now respecting -Q and -R in the PR

Yet another argument to let Load die in its corner.

**Comment by herbelin** [comment]
The `Load` in bedrock2 is quite ugly (it opens a section which is later closed in the file calling the `Load`!), but my impression is that it is like `Undo` in files, or nested theorems, the kind of things which we don't want in a "published" development, but which are convenient in the process of developing, or in talks.

(Alternatively, no need for `Load` to do ugly things...)

**Comment by JasonGross** [comment]
See also https://github.com/mit-plv/bedrock2/issues/224

**Comment by JasonGross** [comment]
> shouldn't we forbid Load "file" when file is not an absolute name?

Given `Load ident`, we should probably deprecate it at least.  Forbidding it seems bad compatibility-wise, and I don't think absolute paths are ever useful here except in development, given that different systems may have different layouts

**Pull request closed without merging**
