### PR TITLE
Strict checking of explicit universe bindings.

### PR DESCRIPTION
**Pull request by mattam82**
Fixing this bug introduces an incompatibility when lemmas starting with explicit universe binders are processed, enforcing that the type can be typechecked using these universes only, after minimization (see bug # 4527). With locations of unbound universes added, the error message can be made a little better, locating the definition which introduced the unbound level.

### CODE REVIEW

**Comment by JasonGross** [comment]
This incompatibility should be mentioned in CHANGES.

Am I right that any definition that is accepted with these changes is also accepted without them?  (That is, by working in the new version, files are automatically compatible with the old version?)

**Comment by mattam82** [comment]
Yes, you are right, twice.

**Comment by mattam82** [comment]
I'm looking at how it affects HoTT now.

**Comment by mattam82** [comment]
@herbelin, @maximedenes what do you think, pl2 or trunk?

**Comment by herbelin** [comment]
No strong opinion but there should be an appropriate discourse. We could present 8.5 and 8.5pl1 as somehow still de facto more beta versions than stable versions for a couple of new features. Or we could think at the whole 8.5 branch as a stable "beta" version for these new features.

Maybe the second?

**Comment by mattam82** [comment]
I think in this case the discourse should be the same as for the notations with universe binders patch, we restrict what can be done in a way compatible with 8.5 and 8.5pl1 (i.e. we're making the semantics more precise, not different). I'm fine with moving this to 8.6 too, it is a minor issue, if you look at the patch to HoTT, there is a single case where it's truly needed.

**Comment by maximedenes** [comment]
I don't have a strong opinion on this one (for pl2 vs trunk). I agree that it is not really a change of semantics, and code that breaks should be easily fixable. The "non-strict" behavior of universe annotations looks like a bug.

**Pull request closed without merging**
