### PR TITLE
fix: Shorten ssrsetoid.v to fix TC performance issue

### LINKED ISSUE #23: Checking time increase in 8.11 and master
The checking time of the project increased from around 7 minutes in Coq 8.10 to around 18 minutes in 8.11+beta1 and master (as measured by Travis). This could be due to changes in `omega` and deserves further investigation.

### PR DESCRIPTION
**Pull request by erikmd**
**Kind:** bug fix / performance.

This PR should fix coq-community/atbr#23 regarding the performance of `setoid_rewrite`
(@palmskog can you confirm this?) and maybe as well coq/coq#11250 (reported by  @samuelgruetter)

* This patch is a quick fix that removes part of the features of coq/coq#10022, namely the ability to directly use `setoid_rewrite` with a (`Under_rel`)-tagged relation R. This means we'll need to do an extra step `rewrite UnderE.` which was unnecessary with Coq 8.11+alpha. (*see example below*)
* This PR stays backward-compatible w.r.t. Coq 8.10 and also keeps the salient feature of coq/coq#10022 (generalize `under` & `over` to any Reflexive relation).

More concretely, now it is not possible anymore to do this (a feature suggested by @CohenCyril, @Armael and @damien-pous @dpous from a discussion at the Coq Workshop 2019), cf. the `Fail` command below:

```coq
Require Import ssreflect Arith Setoid.
Instance le_rr : RewriteRelation Nat.le:= {}.
Goal forall n i (lem : forall i, Nat.le (S i) n -> Nat.le (3 + i) (3 + n)),
    exists Goal,  Under_rel nat Nat.le (3 + i) (Goal i).
intros n i lem; eexists.
Fail rewrite lem; first over.
(* now we need to do *) rewrite UnderE lem; first exact: Nat.le_refl.
```
(*minimal working example minimized from [test-suite/ssr/under.v](https://github.com/coq/coq/blob/9daa001972ba820545/test-suite/ssr/under.v#L371-L374)*)

As said above, this is a quick fix (given the deadline for 8.11 is pending and the performance issue a bit cumbersome); we might want to re-add an improved version of the lines removed here in a future PR, and in the meantime if Armaël and Damien already need this feature with Coq 8.11, maybe they can just incorporate the TC lines at stake in their development(?)

Cc @CohenCyril @gares @ppedrot @mattam82 could one of you be the assignee?

#### Checklist

- [x] Added / updated test-suite
- [x] ~Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).~ [unneeded]
- [x] Entry *modified* in the changelog

### CODE REVIEW

**Comment by erikmd** [comment]
Dear @Zimmi48, sorry to bother you with this question, but if this PR were accepted for 8.11, given the removed enhancement (which just amounts to the presence of several TC instances) has not yet been released in a stable Coq version, I was wondering if it would be OK to directly update the changelog instead of adding another changelog entry (?)
If yes, I've added a second commit that does this.

**Comment by palmskog** [comment]
@erikmd I can confirm on my local machine that this PR fixes the performance degradation issue in Coq master with the ATBR project, i.e., coq-community/atbr#23.

Specifically, here is what `time make -j2` on master yields with your patch:
```
real    1m33.687s
user    2m46.981s
sys     0m7.135s
```
And here are the same numbers for 8.10.2:
```
real    1m44.709s
user    3m7.744s
sys     0m7.573s
```

**Comment by Zimmi48** [comment]
> Dear @Zimmi48, sorry to bother you with this question, but if this PR were accepted for 8.11, given the removed enhancement (which just amounts to the presence of several TC instances) has not yet been released in a stable Coq version, I was wondering if it would be OK to directly update the changelog instead of adding another changelog entry (?)
> If yes, I've added a second commit that does this.

Absolutely, you did the right thing IMHO.

**Comment by erikmd** [comment]
Hi, any objection to integrate this PR?

**Comment by ppedrot** [comment]
Not from me, but I am not a TC expert, so I'd like to have comments from others before assigning.

**Comment by ppedrot** [comment]
Also, I think this should definitely go into 8.11, it could even be considered a blocker to some extent. The faulty feature has not been released yet, so I think it doesn't matter if we merge this into 8.11 without an actual in-depth review from experts. The worst possible outcome is that it makes the setoid algorithm generalization more cumbersome to use, as observed in the top post. Thus, if nobody reacts in time I'll take the liberty to merge this myself.

**Comment by erikmd** [comment]
Thanks @ppedrot for your comments; IMHO the feature that was brought by the TCs removed in this PR was essentially an extra convenience for one use case of `under`, and the lack of these TCs in this case can be easily overcome, as we'll just need to replace `rewrite lem.` with `rewrite UnderE lem.` (BTW I've rephrased the minimal complete example in the top post to make this more explicit)

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
please merge this. If we find a better way to integrate under with setoids we can always bring the feature back.

**Comment by erikmd** [comment]
by the way this PR avoids a potential small issue regarding the closing of `'Under[ _ ]` goals, namely with the following TC instance:
```coq
Instance Under_Reflexive {A} (R : relation A) :
  RelationClasses.Reflexive R ->
  RelationClasses.Reflexive (Under_rel.Under_rel A R) | 12.
```

the following goal could have been unexpectedly discharged by the TC-enhanced tactic `reflexivity`:
```coq
============================
@Under_rel nat Nat.le (f i) (?Goal i)
```
while the intended behavior AFAICT was to be able to discharge it only with `over`…

**Comment by Zimmi48** [comment]
@gares You didn't self-assign: does it mean that you are not in a situation where you are able to perform the merge yourself?

**Comment by gares** [comment]
Tomorrow I can merge, I'm on vac

**Pull request merged**
