### PR TITLE
[CI] Add Sniper project

### PR DESCRIPTION
**Pull request by tomaz1502**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This does not appear to be a plugin (I can't see any ml files). What is the benefit of having it in Coq's CI?

**Comment by tomaz1502** [comment]
> This does not appear to be a plugin (I can't see any ml files). What is the benefit of having it in Coq's CI?

You're right, I should have marked it as "library" instead of "plugin". It is important to have it in Coq's CI since it relies on MetaCoq which is constantly changing. Therefore, it  would be beneficial to receive the patches in case something breaks.

**Comment by ppedrot** [comment]
> It is important to have it in Coq's CI since it relies on MetaCoq which is constantly changing. 

Metacoq is not Coq, it should be the duty of either their CI, or yours, to check that everything still compile. Otherwise the Coq maintainers are going to have to suffer yet another often broken dev in the CI despite having no relationship whatsoever to the cause of the breakage.

**Comment by proux01** [comment]
In any case, if this is using metacoq, it should first be inserted in metacoq CI before even considering adding it in Coq CI.

**Comment by ckeller** [comment]
@mattam82 @yforster Is there a way to integrate the MetaCoq CI?

**Comment by yforster** [comment]
Yes. You can check what coq-undecidability-library does, it also relies on MetaCoq

**Comment by tomaz1502** [comment]
@ppedrot @proux01 Just so we can understand, why exactly does it make sense to add `coq-library-undecidability` in Coq's CI and not `Sniper`? We are in doubt because both of them do not contain OCaml code.

**Comment by proux01** [comment]
coq-library-undecidability is in metacoq CI

**Comment by ckeller** [comment]
> coq-library-undecidability is in metacoq CI

Sorry for bothering you, but we quite not understand what it means. Can you give us a link?

**Comment by proux01** [comment]
Hmm, apparently it indeed isn't, but it should be. We should discuss that with metacoq people.

**Comment by proux01** [comment]
C.f. https://github.com/coq/coq/pull/19339 for a quick fix

**Pull request closed without merging**
