### PR TITLE
Consistent permissions in the stdlib

### PR DESCRIPTION
**Pull request by Villetaneuse**
Give to Logic/Adjointification.v and Reals/Rtrigo_facts.v the same permissions as the other files in the stdlib (rw-r--r--).

This is a glorious PR, achieving +0/-0 modifications.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by Villetaneuse** [comment]
Certainly nothing could really be broken by the fact that two `.v` files had x permissions and now do not.
Here are the failures:
`jasmin`:
```
File "./lang/varmap.v", line 1013, characters 4-7:
Error:
In environment
wsw : WithSubWord
vm1 : ?B → ?A
vm2 : ?B → ?A
vm1' : Vm.t
vm2' : Vm.t
d : Sv.t
The term "vm1" has type "?B → ?A" while it is expected to have type "Vm.t".
```
`unimath` : timeout
`metacoq`:
```
File "./theories/Syntax/PCUICOnFreeVars.v", line 57, characters 7-34:
Error: The LHS of (shiftnP_add 1)
    (shiftnP 1 (shiftnP _ _) _)
does not match any subterm of the goal
Command exited with non-zero status 1
```
`test-suite:base:dev`: timeout

**Comment by Villetaneuse** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@Villetaneuse one is never cautious enough. The failures do look unrelated but that means that the CI on master is quite broken. We already knew about jasmin, but now metacoq is also broken.

**Comment by SkySkimmer** [comment]
We know about metacoq too, cf https://github.com/MetaCoq/metacoq/pull/1028

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
