### PR TITLE
CI: simple-io now depends on ext-lib

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Umm, this seems still broken ;(

**Comment by SkySkimmer** [comment]
Looks like they renamed a bunch of stuff https://github.com/Lysxia/coq-simple-io/commit/5404780445c970209d6391a035e3f2ae75743b72
I don't know what to do.

**Comment by SkySkimmer** [comment]
cc @Lysxia

**Comment by ejgallego** [comment]
Thanks @SkySkimmer and @Lysxia , let us know when this should be tested again.

**Comment by ejgallego** [comment]
Anyways I'm merging this as it cannot hurt.

**Pull request merged**
