### PR TITLE
[ci] [doc] Notes about branch names.

### PR DESCRIPTION
**Pull request by ejgallego**
I'd like to add this convention as it is very convenient for the
development of dev tools. Example, I can do `setup-coq-devs ltac
equations` and then get a fully composed tree. Similarly for preparing
overlays.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
I'm fine with it.

**Comment by Zimmi48** [comment]
Since I don't know what is `setup-coq-devs`, it's hard to comment on this proposal but I already expressed my worries about the recommended convention here: https://github.com/ybertot/plugin_tutorials/issues/9

**Comment by ejgallego** [comment]
> Since I don't know what is `setup-coq-devs`, it's hard to comment on this proposal but I already expressed my worries about the recommended convention here: [ybertot/plugin_tutorials#9](https://github.com/ybertot/plugin_tutorials/issues/9)

Well, the only worry I see there so far is recommending `coq-8.8` vs `v8.8`. IMHO that's not worth the gain as people then would likely get it wrong, name it differently. IMHO same name is what makes most sense.

**Review by Zimmi48 — APPROVED** [review]
OK, as long as it is only a recommendation.

**Comment by Zimmi48** [comment]
Let me ping @gares here too since he is also one of the users of the coq-v8.8 convention...

**Comment by ejgallego** [comment]
> It would be written down after this PR.

The whole point of the convention is not to have to look at docs, but only at the source code. I dunno, I am following this pattern based on what other convention-based system do [RoR lol, old times]

Of course is only a recommendation, but allows you to skip defining a branch name.

**Comment by ejgallego** [comment]
Note that some people find conventions "obscure" or "too magical" sometimes, I dunno. But it does bothers me a bit the diverse variety of branches we have. [And despite pinning we still need a branch name to update the pinning].

**Comment by Zimmi48** [comment]
>And despite pinning we still need a branch name to update the pinning

Absolutely, yes!

**Comment by SkySkimmer** [comment]
>The whole point of the convention is not to have to look at docs, but only at the source code.

What source code?

**Comment by ejgallego** [comment]
> What source code?

I mean Coq's git repos. For the branch name.

**Comment by SkySkimmer** [comment]
Since @gares was pinged I'm going to wait for him to say something.

**Comment by ejgallego** [comment]
Ping @gares

**Comment by gares** [comment]
If you name the branch with a version it may clash with a branch of the sw itself. Hence I prefer to prefix it with coq-

**Comment by SkySkimmer** [comment]
In order to avoid being stuck in bikeshed limbo I'll merge tomorrow (barring objections).

**Comment by gares** [comment]
you can merge it now, for me

**Pull request merged**
