### PR TITLE
Tidy stdlib

### PR DESCRIPTION
**Pull request by Zimmi48**
I went through one of the files of the standard library and slightly modified the proofs of most lemmas, with the following criteria:
- Remove `induction` when it is not necessary. Use `destruct` instead or, even better, a destructive intro pattern.
- Remove heavy automation such as `auto with arith` when not necessary and `trivial` or `assumption` are enough.
- Shorten the proofs, only when it does not hinder readability. In particular, `auto with arith` can be replaced by `...` when used several times.
- Add bullets systematically.
- Do not rely on automatically generated names.
- Use `;` only when it concludes some of the goals.

Most proofs were modified in distinct commits so:
- If you don't like something, we can revert some specific commits.
- If you think there are too many commits, I can squash them.

If this receives positive feedback, I might do the same for other files of the standard library.

### CODE REVIEW

**Comment by ppedrot** [comment]
I'm not too fan of the `Proof with` technique, but other people may have their own taste. Apart from that, this looks good... We should probably open a discussion about the stdlib at some point BTW.

**Comment by herbelin** [comment]
Hi Théo, thanks indeed for launching a discussion on tactic style in the standard library (which could be moved to another place if necessary). I'm afraid that there are so many styles around, even among developers, that finding a general rule might be difficult, but if we do not try, there are little chances to succeed, so let's try.

Personally, I'm supporting the following in the commits you made:
- not using induction when not necessary
- using bullets (or { }) whenever there is some branching

I shall otherwise list some ways of doing which I like, knowing that this is just a personal view:
- I like to use "(... , ... , ...)" (and "(... & ... & ....)" when relevant) for intro patterns when there is only one constructor; it looks to me more expressive (though I know others don't like it because they find it a redundant syntax)
- I consider that the elim/induction, case/destruct discrepancy should eventually be removed, because it is difficult to explain. The idea I have in mind (in the long run) is that "elim" becomes a deprecated synonymous for "induction" (thus preferring "induction", which I find intuitive and standard, over "elim", which I find a bit jargon). Another idea I have in mind is also to go towards using "case" as a replacement of "destruct" for case analysis (i.e. several constructors) and to restrict the use of "destruct" to splitting objects of an inductive type with zero or one constructor, as it looks to me a more appealing terminology. Then, the idea is that current "elim" is renamed into "induction:" and current "case" is replaced by either "destruct:" (for zero or one constructor) or "case:" (for more than one constructor). By doing so, the stack-based ssreflect model could be revisited as an extension of the so newly-defined "induction:" (alias "elim:") and "case:"/"destruct:" (the ":" telling: "work on the head of the goal, possibly pushing arguments first").
- I always found frustrating that there is no introduction pattern for "induction". I had a syntax in mind which I never fully implemented, even though it would be easy, it is "[pat ... pat]_ind" (though one may think that more structure should be put in this pattern, in particular to distinguish induction hypotheses from other hypotheses, so that it could be e.g. "[pat ... pat -- IHpat ... IHpat]_ind", or even e.g. "[pat ... pat -- IHpat ... IHpat]", considering that the "_ind" is redundant with the "--" (though less cryptic)).
- Between the "now tac" style, and the "tac; assumption" style, I don't have a stable opinion. I like the "now" style (borrowed from ssreflect) which is a light way to express that a "trivial" step concludes the proof, but I like also the "tac; assumption" style which is more precise on how the proof is concluded. Thinking aloud, maybe a way to generalize these two styles into one could be to provide a "now tac by tac'", or "now tac using tac'", which would at the same time express that the step is complete and say how it is completed, with "now tac" defaulting to "now tac by easy" (or "now tac using easy")?
- To tell the truth, I'm not a big fan of "..." either, though I don't really have arguments other than the subjective feeling that it does not look syntactically very nice to me.

**Comment by Zimmi48** [comment]
To be honest, I don't generally use `Proof using` as I don't feel the need but for some proofs in this file it felt just right. See for instance how it thins out the proof of `between_not_exists`.

**Comment by Zimmi48** [comment]
I replaced two `[ ... ]` pattern instances with `(..., ...)` instead following your comment @herbelin. However, in other cases it wouldn't make sense: forcing to replace `[]` with `(?, ?)`. `[]` is nice when you don't want to name the hypotheses it generates.

**Comment by Zimmi48** [comment]
Rebased. Squashed.
Following remarks from various people, I stopped using `Proof using ...`
I replaced all calls to `elim` with `destruct` or `induction` instead.
I think that there shouldn't be any problem left which would prevent merging this PR.
Of course the same treatment could be applied to other files of the standard library but this is a first self-contained step.

**Pull request merged**
