### PR TITLE
In gitlab set TRAVIS_BRANCH so user overlays will work as expected.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Zimmi48** [comment]
What about giving a more generic name to this variable like just `BRANCH`, setting it to `TRAVIS_BRANCH` in case we are on Travis, and adapting the code in `dev/ci/user-overlays` to this change? We could even have a fallback in case we are neither on Travis nor on GitLab CI and use `git branch | grep \* | cut -d ' ' -f2`...

**Comment by SkySkimmer** [comment]
If we want to be robust we should just not merge user overlays into master and make them unconditional.

**Comment by Zimmi48** [comment]
Yeah, well historically @ejgallego wanted us to merge user overlays in master to keep some historical record but @maximedenes disagreed and merged PRs after dropping commits adding user-overlays (and when we first submit a PR with a backward compatible fix and it gets merged before the PR, the author is generally the one who drops the user overlay).
I guess the main advantage of having this logic is that even if we forget to remove the user overlay, it won't affect our testing once merged. The main disadvantage is that people seem to think that it is OK to instead change the basic overlay in `ci-basic-overlay.sh`, so that we now get a polluted file with lots of development being tracked elsewhere than on the official repository.

**Comment by ejgallego** [comment]
Yup, a polluted `ci-basic-overlay` should be a blocker for merging.

**Comment by Zimmi48** [comment]
Unfortunately, it currently isn't. See my rant at https://github.com/coq/coq/pull/914#discussion_r138953974.

**Comment by maximedenes** [comment]
@SkySkimmer Should I merge this?

**Comment by SkySkimmer** [comment]
Please do merge.

**Pull request merged**
