### PR TITLE
[ci] bump elpi

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by gares** [comment]
Green light

**Comment by gares** [comment]
@SkySkimmer plz merge

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by gares** [comment]
thanks

**Comment by proux01** [comment]
@SkySkimmer I don't have the slightest idea of what could have happened but according to the CI log, this is the first PR merge after which itree appears broken.

**Comment by proux01** [comment]
In fact, the issue comes from this commit in paco: https://github.com/snu-sf/paco/commit/ae2b3c9918824f2616a7e71cd85c63aa77494a1f

**Comment by proux01** [comment]
@gilhur this last commit on paco breaks ITree in the CI of Coq. Could it be reverted for now.
More generally there should be a CI on paco testing ITree and nothing should be pushed there until the CI is green.
Grep @minkiminki FYI since you are the point of contact listed for paco in Coq CI.
Cc @Lysxia FYI (point of contact for ITree)

**Pull request merged**
