### PR TITLE
Mini reorganization keyword detection before addressing issue 4712

### PR DESCRIPTION
**Pull request by herbelin**
*Kind*: cleanup

We do the following:
- add new Unicode classes `Separator` and `Control` so as to be able to classify the `0x00-0x7F` ascii fragment of Unicode without a specific treatment
- merge code for ascii and non-ascii utf-8 characters in the lexer
- prepare `progress_further` to address #4712 and its variants

### CODE REVIEW

**Comment by herbelin** [comment]
In passing, a non-breaking space is officially classified as a Unicode separator. Separators are not allowed in Coq identifiers in general but there is an exception for non-breaking spaces. Interestingly, changing Coq convention so as to stop allowing non-breaking spaces in identifiers (as I did unconsciously in a first version of the PR) revealed that 2 developments (GeoCoq and Coquelicot) used non-breaking spaces in identifiers in an non-intended way (presumably as a copy-paste turning spaces into non-breaking spaces). So, maybe, that was a bad idea to accept non-breaking spaces in identifiers.

**Review by proux01 — APPROVED** [review]
<wrong PR>

**Review by proux01 — APPROVED** [review]
I'm not a unicode expert but this looks reasonable and is needed for #16322 so I'll merge by the end of next week if there is no further comment.

**Comment by proux01** [comment]
> So, maybe, that was a bad idea to accept non-breaking spaces in identifiers.

I agree this looks dangerous. Considering it seems unused, we should probably turn non breaking spaces into regular separators.

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
