### PR TITLE
Inline calls to Functional Scheme in MSetAVL.

### PR DESCRIPTION
**Pull request by ppedrot**
Equivalent of #19312 for MSetAVL. Last standing after this one is FMapFullAVL. cc @proux01 

Backwards compatible overlays:
- https://github.com/AbsInt/CompCert/pull/515

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This breaks compcert because the dependency on extraction through funind disappeared

**Review by proux01 — APPROVED** [review]
Will merge once compcert overlay is.

**Comment by ppedrot** [comment]
@proux01 CI green and overlays merged, this is ready to go.

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
