### PR TITLE
Deprecate Lemma ... with ...

### PR DESCRIPTION
**Pull request by SkySkimmer**
This command is irregular as a single Lemma won't create fixpoints.
Fixpoint ... with ... should work fine to replace mutual Lemmas.

### CODE REVIEW

**Comment by ejgallego** [comment]
That command is for sure used quite a bit in the wild, I do believe.

**Comment by SkySkimmer** [comment]
Why's aac running with -w +default? anyway I made them a PR.

**Comment by herbelin** [comment]
> This command is irregular as a single Lemma won't create fixpoints.

If the motivation is to address the lack of regularity, why not to rather change the syntax to `Recursive Lemma .... with ...` and that it works for a single lemma?

I'm unsure that the intuition bound to the keyword `Fixpoint` is really the same as the intuition bound to `Lemma` (otherwise, we could as well remove `Lemma` without `with` and use `Definition` instead).

**Comment by SkySkimmer** [comment]
Shall we merge?

>If the motivation is to address the lack of regularity, why not to rather change the syntax to Recursive Lemma .... with ... and that it works for a single lemma?

I don't think there are enough users to justify having a Fixpoint alias.

**Comment by ejgallego** [comment]
IMHO we should check we don't get like hundredths of deprecation warnings, my impression is that this is quite used so if we don't have a realistic removal path we should not deprecate IMHO.

I don't know how to do that tho :(

**Comment by SkySkimmer** [comment]
I guess we can try with the warning set AsError and see what CI says.

**Comment by ejgallego** [comment]
> I guess we can try with the warning set AsError and see what CI says.

The problem with that is that it won't capture quantitative data; if there are like 2 uses in a development we could easily deprecate, if we have 200 maybe we want to think twice.

**Comment by Zimmi48** [comment]
In the past, I had ambitions of adding a `Lemma :=` syntax (I haven't completely forgotten about it). I had encountered these inconsistencies in the grammar while getting started on the implementation.

While I support this change in principle, I agree it is important to assess the impact the removal would have. I vaguely remember having done so and having discovered a few additional irregularities that were harder to translate (but my memory recollection is really vague).

Regarding the possibility of adding explicit information to `Lemma` about its recursive nature, I would be OK with it in the form of an attribute, provided that it is also accepted by `Definition` and such (again for maximum grammar consistency). So, using the current syntax of attributes (which might make @herbelin cringe), this would be e.g. `#[ rec ] Definition` and `#[ rec ] Lemma`.

In the future, I wish `Definition ... :=` was just a synonymous for `#[ transparent ] Lemma ... :=`, and `Lemma ... :=` a synonymous for `#[ opaque ] Definiion ... :=`.

**Comment by herbelin** [comment]
> I don't think there are enough users to justify having a `Fixpoint` alias.

I continue to think that the intent behind the name `Lemma` is not the same as the intent behind `Fixpoint` (not everyone is born in the cauldron of Curry-Howard).

I agree though about the lack of regularity with single `Lemma`. So maybe an attribute would help (then closing the eyes not to see the syntax :smile:).

**Comment by ppedrot** [comment]
Judging from the discussion, I think we lost the original motivation of this deprecation (or at least, the thing that I thought motivated this PR) so let me restate it here.

> "We want to get rid of the after-the-fact `struct` monkey patching and force users to specify a recursive argument when writing a mutual lemma."

The deprecation is not motivated by a Fixpoint vs. Lemma intended semantics shenanigan, but by the fact that syntactically Lemma doesn't allow you to specify a struct argument *at all*.

**Comment by Zimmi48** [comment]
@ppedrot If that's the motivation, why allow `Fixpoint` in proof mode? Does it allow to specify a `{ struct }`? (Sorry I didn't check.) If yes, then it has the same issue. If no, then shouldn't it be forced upon the user? And if having a `#[ rec ] Lemma` syntax is deemed useful, nothing would prevent making it require a `{ struct }` annotation...

**Comment by ppedrot** [comment]
> Does it allow to specify a { struct }?

Yes.

> If no, then shouldn't it be forced upon the user? 

Struct annotations should be indeed mandatory for Fixpoint without bodies. This was discussed in some related PR.

> And if having a #[ rec ] Lemma syntax is deemed useful, nothing would prevent making it require a { struct } annotation too...

I am under the impression that the attribute business is getting a bit out of hand. Attributes should be used for optional flags that can coexist with other such flags. Here it's supposed to be mandatory part of the syntax, that doesn't feel like the role of an attribute. (Which we didn't really define, but well...)

**Comment by gares** [comment]
> > "We want to get rid of the after-the-fact `struct` monkey patching and force users to specify a recursive argument when writing a mutual lemma."

Indeed I think "deprecating" is misleading. What we really want is:
- whenever the thing is recursive:
  - let the user actually write a `{struct}` annotation
  - eventually force a `{struct}` annotation (that would be a "deprecation" phase)

Today `Fixpoint` lets you put the struct annotation if you put the body (but not if you don't), and Lemma [with] does not let you write struct at all (nor in the statement, nor in the body since you can't write the body).

So to me the steps should be (in this order):
1. Fix the syntax of Fixpoint and [Recursive-]Lemma-with allowing one to write {struct} in the statement
2. deprecate the complete absence of {struct} (in body and statement)
3. bonus: Lemma (recursive or not) with an actual body, kind of something @Zimmi48  wanted to do at some point

If we agree on that plan, then this PR is not quite right.

**Comment by SkySkimmer** [comment]
This ended up harder to get merged than I expected.

**Pull request closed without merging**
