### PR TITLE
Remove "stdlib2" from CI

### PR DESCRIPTION
**Pull request by SkySkimmer**
It doesn't seem like it will be continued, efforts on standard library are not going there.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
ping @coq/ci-maintainers

**Comment by MSoegtropIMC** [comment]
So is it official that stdlib2 is dead?

**Comment by proux01** [comment]
Maybe this should be checked during a short Coq call point?

**Comment by SkySkimmer** [comment]
What is there to check, there's been no activity other than our overlays for years.

**Comment by proux01** [comment]
I'm indeed expecting it to be mostly immediate but I just want to make sure nobody comes complaining that this has been removed without notice.

**Comment by proux01** [comment]
Nobody disagreed during today's meeting: https://github.com/coq/coq/wiki/Coq-Call-2024-12-03

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
