### PR TITLE
CI: do not set interruptible:true on protected branches

### LINKED ISSUE #258: Bot no longer offers to minimize CI?
@Zimmi48 do you know what's going on with the bot not offering to minimize https://github.com/coq/coq/pull/16904#issuecomment-1326875225 ?

### PR DESCRIPTION
**Pull request by SkySkimmer**
Using conditional includes was the only I had to achieve this.

Fixes coq/bot#258

### CODE REVIEW

**Comment by Zimmi48** [comment]
> Fix (mostly?) [coq/bot#258](https://github.com/coq/bot/issues/258)

Not in full because pipelines on protected branches will still be cancelled if they have not started (and maybe the jobs that have not started will be cancelled as well) IINM.

Note: we need to modify these lines in the coqbot sources to account for these new GitLab CI configuration files.

https://github.com/coq/bot/blob/74ee44efb686ea0835099e6ee21778362ee1dc1c/src/actions.ml#L2254-L2261

**Comment by SkySkimmer** [comment]
I'm going to invert the logic, wait for a job to get picked up, then push again. Then we can see how cancellation behaves with running jobs.

**Comment by SkySkimmer** [comment]
assignee?

**Review by Zimmi48 — APPROVED** [review]
Sorry I missed this. Will merge soon (I need to update coqbot first).

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
