### PR TITLE
Rebinding Cd/Pwd to a synchronous option Set Pwd "dir"

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** Adaptation to synchronous use of Coq

The commands `Cd` and `Pwd` are among the oldest commands of Coq and they are not synchronized with backtracking.

This PR adds a synchronous `Set Pwd "dir"` command and rebind `Cd "dir"` to `Set Pwd "dir"` and `Pwd` to `Test Pwd`.

Don't know well how to evaluate the importance of this change. In some sense `Cd` is rarely used (only virtually for `Extraction`?). On the other sense, reducing `Cd` to just an option seems to be a simplification (but then what to do with the redundance of syntax?).

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.

### CODE REVIEW

**Comment by ppedrot** [comment]
Motivation of this PR? I thought we were on our way to phase out this kind of commands, not adding more variants of them.

**Comment by herbelin** [comment]
Let's say that the motivation is to trigger a discussion on `Cd`: removal, reduction to a normal flag, modification of `Extraction` so that we can control the extraction directory...

In any cases, I arrived to it to prepare #14721, but the latter does not really need #14720.

**Comment by ppedrot** [comment]
I don't think I see the point of writing a PR that is bound to be closed in favour of another one just to trigger discussion, but well...

**Comment by herbelin** [comment]
I made the code anyway, and, at the moment we support `Cd` (at least for extraction), it is better to have it synchronized with backtracking, and the PR is a strict improvement on the current situation. If another approach is used to control the extraction directory, then the PR can be closed. So, It seems to me that the PR is leading to a positive move in all cases.

**Comment by ejgallego** [comment]
I share @ppedrot 's view, I'd rather remove the `Cd` command at all, it is a disaster waiting to happen.

**Comment by ppedrot** [comment]
Let's close then.

**Pull request closed without merging**
