### PR TITLE
Adding a fold_glob_constr_with_binders combinator

### PR DESCRIPTION
**Pull request by herbelin**
This PR adds combinators on `glob_constr` so as to allow more code factorization. Incidentally, it fixes a few minor bugs about detection of free/bound variables in `fix`/`cofix` and `match` expressions in a couple of functions.

The reason for using generic combinators in such situation is standard: not only we improve robustness (it is easier to carefully design the combinator once and for all than checking the code of each new function which could have used the combinator but did not use it; and even if there is a remaining bug in the code of the combinator for one constructor of `glob_constr`, more functions use it and there is then more chance that we find it) but we simplify maintenance since a little change to the syntax of `glob_constr` needs to be passed on only to the combinators, freeing the developers to think at how to apply the change at otherwise every single function. Also, if a plugin uses itself a combinator, it takes benefit automatically of the generic change.

### CODE REVIEW

**Comment by ejgallego** [comment]
From some gitter discussion I understood that plugins were not supposed to use `glob_constr`, what is the status on that?

**Comment by maximedenes** [comment]
@ejgallego This is an interesting discussing, but should happen somewhere else IMHO. (coqdev?)

**Review by ppedrot — APPROVED** [review]

**Comment by herbelin** [comment]
By the way, @maximedenes, or @mattam82, are there plans around to write a proposal on how to stabilize the APIs?

I know this is a huge task, and the fact that it is a huge task is one of the reasons it is difficult to make progress as much as one would like to do, but there are nevertheless a couple of general ideas which seem to be worth to be written black on white.

For instance, there is still `constr` and `Constr.t`. Shall we move every types to `Constr.t` or shall we instead keep `constr` (for instance, practical advantage of only one type, besides relaxing the mind, this would makes `grep` on `mli` simpler)? Other example, shall we also add a module `Types` with a field `t`, alias of `constr`, and move all uses of `types` to `Types.t`? Indeed, one could see an interest in a module `Types` distinct from `Constr`: this module could enforce extra syntactic checks on `Type.t` which do not apply to `Constr.t`. For instance, functions such as `find_rectype` or `decompose_prod` would naturally go in `Types`. (But note that this is just a proposal and maybe, by lack of time, we would prefer to stabilize instead the current situation.)

Other idea: shall we adopt for `Termops` the same model as for `List` and `Array`? Putting in it a module `Context` which extends `context.mli`, a module `Constr` which extends `constr.mli`, etc?

We do have a support for documenting APIs, and, the objective of stabilizing the APIs for say at least the next 10 years (if not more!) is important for the development of a sustainable ecosystem of plugins. But to do that, we need to converge towards an API layout which makes sense to us and with which we shall feel durably comfortable to work with.

**Comment by ejgallego** [comment]
"Stabilizing the API" may be a futile goal in a research of the scale of Coq, at least if you want Coq to evolve. Note that this is not the same than breaking the API for no purpose. 

For instance, the Linux Kernel gave up on API stability since the beginning. They (correctly) believed that a stable API would make the evolution of the project impossible. On the other extreme you have projects such as GTK, which promised API stability. They had to pay a quite high price for it, IMHO not worth it and in the end they had to break the API anyways.

**Comment by maximedenes** [comment]
This PR has leftover dead code: `add_name_to_ids` in `glob_ops.ml`. Could you remove it? Thanks!

**Comment by maximedenes** [comment]
Never mind, I'll do it in a subsequent commit.

**Comment by herbelin** [comment]
Well spotted. Ah, if you do it, then thanks a lot.

**Pull request merged**
