### PR TITLE
Fix some incorrect uses of proof-local environment

### PR DESCRIPTION
**Pull request by maximedenes**
I extracted these fixes from #10050. They had been done by @ejgallego too, in an earlier PR. In both cases, they were orthogonal to the PR containing them, so I submit them separately here.

### CODE REVIEW

**Review by gares — APPROVED** [review]
ssr ok

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Will merge soon if nobody complains. (@ejgallego may comment on that PR, let's summon him.)

**Comment by ejgallego** [comment]
You can go ahead @ppedrot

**Comment by maximedenes** [comment]
@ppedrot can you merge? Thanks!

**Comment by maximedenes** [comment]
Thanks!

**Pull request merged**
