### PR TITLE
Math-classes and Corn new maintainer

### PR DESCRIPTION
**Pull request by proux01**
Update point of contact for CI.

Cc @Lysxia

### CODE REVIEW

**Comment by proux01** [comment]
C.f. https://github.com/coq-community/manifesto/issues/158

**Review by Lysxia — APPROVED** [review]

**Comment by proux01** [comment]
Thanks

**Comment by Lysxia** [comment]
Oops, sorry. I will remember.

**Comment by Zimmi48** [comment]
Is there also some contact update to-do on the Coq Platform side? cc @MSoegtropIMC @rtetley

**Pull request merged**
