### PR TITLE
Fix vernac classification of `Fail Instance`

### PR DESCRIPTION
**Pull request by maximedenes**
AFAIK `Fail Instance` cannot open a goal, so this is probably a mistake by me when I wrote the `vernac_control` code.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Why's Fail not always a VtQuery?

**Comment by gares** [comment]
I think Gaetan is correct. Fail should always behave like a query (no trace left in the system state)

**Comment by maximedenes** [comment]
@gares when classifying `Fail` as a query, I get more errors. You can open `test-suite/success/bteauto.v` in coqide to observe the problem. I probably need some help there.

**Comment by maximedenes** [comment]
Ok, so it seems the STM makes a lot more assumptions on query (and in particular, distinguishing it from tactics) than just "it does not change the environment". This will require more work.

**Comment by maximedenes** [comment]
@gares how do you think we should fix this? It seems the code is not consistent w.r.t. what it calls "queries".

**Comment by gares** [comment]
We renounce to this

**Comment by maximedenes** [comment]
> We renounce to this

Let's at least clarify what a query is, in the code. What's a query?

**Comment by gares** [comment]
What a query should be is clear, so what this PR tries to do is morally OK. Unfortunately in the code the fact that something is labelled as a Query has other effects that, as we tried, makes Fail misbehave.

I consider that a sort of bug that requires a cleanup. Now I don't recall exactly what we found the other day, but it wound not be a documentation but rather an analysis of this bug report.

**Comment by gares** [comment]
Another way to put it is that this PR should become a bugreport, or be rebased on top of the cleanup one that still does not exist.

**Review by gares — CHANGES_REQUESTED** [review]
to signal I don't need to review this anymore and that it is not in a mergeable state

**Comment by maximedenes** [comment]
@gares Could you list somewhere (in the code, around the classification I guess) the current expectations the STM has w.r.t. queries? i.e. what is a query, basically. At least, it would clarify the current status quo, and we could work on lifting some of these assumptions.

**Comment by maximedenes** [comment]
@gares I reverted to the original version of the patch, which should be merged if CI passes, as it removes a code path generating `VtUnknown` (for no reason).

Of course, it would be better if we could implement @SkySkimmer 's suggestion, but it seems hard without understanding more the hidden invariants.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I don't even compile it with quick (unless env variables are inherited)

**Comment by maximedenes** [comment]
@gares ping

**Pull request merged**
