### PR TITLE
A fix to #5414 (ident bound by ltac names now known for "match").

### PR DESCRIPTION
**Pull request by herbelin**
This fixes the missing interpretation of ident bound to names in "match" and in a few other places. See bug [#5414](https://coq.inria.fr/bugs/show_bug.cgi?id=5414).

I had to move `ltac_var_map` and `ltac_interp_name` so that `cases.ml` can use it. I put them (a bit arbitrarily) in `glob_term.ml` and `glob_ops.ml`. Tell me @ppedrot if you see a better place.

By the way, maybe would it be useful to get an overview of existing plans for the future of this feature?

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
In the long run we should make the pretyping phase open (in the sense of late-binding) so that each end user would tweak it in their code base. Typically, `ltac_var_map` would end up in the Ltac implementation, as well as variable interpretation.

Yet, this is a long term goal. The current patch seems reasonable to me meanwhile.

**Comment by maximedenes** [comment]
@herbelin Could you rebase this PR to make the tests run? Thanks!

**Comment by herbelin** [comment]
Note: This is dependent on #600 for ssreflect compatibility.

**Comment by herbelin** [comment]
Rebased done (loc, loc, loc, ...). Note that it still depends on #600 being integrated first.

**Comment by maximedenes** [comment]
Post-merge test running here: https://travis-ci.org/maximedenes/coq/builds/239856206

**Comment by maximedenes** [comment]
It seems Fiat is broken. I may have introduced a problem when merging, though. @herbelin, can you have a look?

**Comment by herbelin** [comment]
New rebase made.

**Pull request merged**
