### PR TITLE
Add conf- dependencies for opam

### PR DESCRIPTION
**Pull request by SkySkimmer**
python3 used by the update-compat and timing tests
time used by the timing test

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
We also need
~~~opam 
   "conf-linux-libc-dev" {os = "linux"}
~~~
in coq-core.opam.
Is there a way to express that in dune-project? @ejgallego @Alizter @rgrinberg

**Comment by ejgallego** [comment]
> We also need
> 
> ```
>    "conf-linux-libc-dev" {os = "linux"}
> ```
> 
> in coq-core.opam. Is there a way to express that in dune-project? @ejgallego @Alizter @rgrinberg

I'm sure it is, should be similar to `with-test` etc..., sexp should be `(= os "linux")` or similar.

[I can look into that later, now gotta run to a meeting]

**Comment by palmskog** [comment]
If I write `(conf-linux-libc-dev (= os "linux"))` in a `dune-project` I get ` "conf-linux-libc-dev" {"os" = "linux"}`.

The faulty quotes for `os` probably means this one needs to go in `coq.opam.template`.

**Comment by ejgallego** [comment]
Does it work with `(= :os linux)` ?

**Comment by palmskog** [comment]
@SkySkimmer `(conf-linux-libc-dev (= :os "linux"))` in `dune-project` works for me locally to replicate what we in the opam file for the `coq` package, so you'll probably want to add that to this PR.

**Comment by SkySkimmer** [comment]
Added conf-linux-libc-dev

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
