### PR TITLE
[RM] Update magicno & compat

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
LGTM.
Can you also bump the reference to 8.13 found in the `default.nix` file?
@JasonGross Can you take care of making fiat-parsers compatible with the 8.14 version number?

**Comment by gares** [comment]
I hope it makes sense, I don't know nix

**Review by Zimmi48 — APPROVED** [review]

**Comment by JasonGross** [comment]
I've updated fiat-parsers and restarted the job.  Hopefully it works now.  Should the update to default.nix be automated?

**Comment by Zimmi48** [comment]
Hum, still failing with:
```
File "src/Common/Tactics/hint_db_extra_tactics.ml", line 27, characters 23-38:
Error: Unbound type constructor Hints.full_hint
```

**Comment by JasonGross** [comment]
Should be fixed now

**Comment by Zimmi48** [comment]
@coqbot: merge now

**Pull request merged**
