### PR TITLE
[ci] Add mit-plv/engine-bench

### PR DESCRIPTION
**Pull request by JasonGross**
This is a new development where I'm aggregating a specific set of
benchmarks.  It's intended to be relatively lightweight, taking only a
handful of minutes (I can make the CI target much, much lighter if
desired).  It's probably one of the few developments currently testing
Ltac2.

**Kind:** infrastructure

### CODE REVIEW

**Comment by SkySkimmer** [comment]
It failed and I can't tell why.

**Comment by JasonGross** [comment]
Very strange.  It failed because the following script fails
```bash
#!/bin/sh

set -x

lscpu
uname -a
lsb_release -a
```
I'll update the code to make this more robust against failure, but do you have any idea why this would fail?

**Comment by SkySkimmer** [comment]
Probably one of those commands is missing
In fact since it fails and there's no `set -e` it's probably missing lsb_release

**Comment by JasonGross** [comment]
Should work now (still waiting on the CI to be sure, though).

**Comment by JasonGross** [comment]
CI passes in 4 minutes 9 seconds : https://gitlab.com/coq/coq/-/jobs/559588771 , timing log:


Time |   Peak Mem | File Name                                                  
 ---------|---------------|-----------------------------------------------------------
 0m40.47s | 2425192 ko | **Total Time / Peak Mem**
 --|--|--
 0m34.15s | 2425192 ko | app_n.vo                                                   
 0m01.60s |  441364 ko | Harness.vo                                                 
 0m00.48s |  404524 ko | do_n_open_constr_True/_0_Sanity.log                        
 0m00.41s |  343012 ko | app_n_ltac2.vo                                             
 0m00.40s |  323164 ko | open_constr_n_lambda_no_types_different_names/_0_Sanity.log
 0m00.39s |  329236 ko | app_n_uconstr.vo                                           
 0m00.39s |  333420 ko | open_constr_n_lambda_no_types_different_names.vo           
 0m00.39s |  322780 ko | open_constr_n_lambda_no_types_no_names/_0_Sanity.log       
 0m00.38s |  328536 ko | app_n_ltac2/_0_Sanity.log                                  
 0m00.38s |  347240 ko | do_n_open_constr_True.vo                                   
 0m00.38s |  333648 ko | open_constr_n_lambda_no_types_no_names.vo                  
 0m00.38s |  333500 ko | open_constr_n_lambda_no_types_same_names.vo                
 0m00.36s |  323440 ko | open_constr_n_lambda_no_types_same_names/_0_Sanity.log     
 0m00.35s |  323448 ko | app_n_uconstr/_0_Sanity.log                                
 0m00.04s |   59760 ko | evar_creation.vo

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
