### PR TITLE
Fix setoid_rewrite under non dependent binders

### LINKED ISSUE #5369: [setoid_rewrite] fails to find occurances under binders when there are side conditions (even when the side-conditions don't mention bound variables)
Note: the issue was created automatically with bugzilla2github tool

Original bug ID: BZ#5369
From: @JasonGross
Reported version: 8.6
CC:   @andres-erbsen, @psteckler

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #5369

The substitution made unconditional is necessary as an anti-lift even
if the binder is nondependent.

Overlay: https://github.com/mit-plv/fiat/pull/58

### CODE REVIEW

**Comment by ppedrot** [comment]
We don't need that for meta-based clenv (see `Clenv.clenv_environments`) because the invariant is that we only call it on closed terms at toplevel. Are you saying that the evar instance can capture a rel somewhere? I don't understand how that can happen, except if setoid_rewrite is incorrectly calling the clenv on an open term.

**Comment by SkySkimmer** [comment]
setoid_rewrite calls refresh_hypinfo https://github.com/coq/coq/blob/eb745e1d2bd511e7f7e5db54468e9a3c7ecc2247/plugins/ltac/rewrite.ml#L596 on constant `Hfg : forall n m, n = n -> f n m = g n m`
make_evar_clause is called on its type (which is closed) https://github.com/coq/coq/blob/eb745e1d2bd511e7f7e5db54468e9a3c7ecc2247/plugins/ltac/rewrite.ml#L503
Prior to this PR this produces a cl_concl with an unbound rel in an evar instance
~~~
cl_concl = (eq nat
     (f ?X121@{__:=n; __:=_UNBOUND_REL_2} ?X122@{__:=n; __:=_UNBOUND_REL_2})
     (g ?X121@{__:=n; __:=_UNBOUND_REL_2} ?X122@{__:=n; __:=_UNBOUND_REL_2}))
~~~
(the env being `[n : nat] [(n' : nat)]`)
after this PR the rel is number 1 (ie n') which works.

**Comment by ppedrot** [comment]
Ah, yes, obviously the problem is that the environment has an non-empty rel context...

**Comment by SkySkimmer** [comment]
No idea what's going on in fiat_parsers, cc @JasonGross

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by JasonGross** [comment]
I've hopefully fixed the import problem, let's try again (and wait another couple of days, because I'm too lazy to do manual minimization to take advantage of manual resumption).

@coqbot ci minimize

**Comment by SkySkimmer** [comment]
@JasonGross can you stop the minimization? I don't think it's going to be useful.

**Comment by SkySkimmer** [comment]
Ready

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
