### PR TITLE
[doc] [ssr] fix documentation of reflect

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@gares You pushed to the main repo instead of pushing with your fork. Did you create this PR with `gh pr create`? If that's the case, then be careful when it asks you whether to push to `coq/coq` or your own fork.

**Comment by gares** [comment]
oops, I did it from the web UI and I thought that "create branch" did something sensible... I think it did in the past, but maybe I did not have push rights on the repo so it picked my fork...

**Comment by Zimmi48** [comment]
Yeah, that's a frequent reason for this kind of accidents! Unfortunately, you cannot benefit from the PR from web UI feature as soon as you get write-access on the Coq repo, which is the case for more than 50 people. Every time find about this, I encourage them to complain to https://support.github.com/contact/feedback. Hopefully, with enough spam GitHub will eventually hear us.

**Comment by gares** [comment]
You are also encourgared to make a review and merge this, so that we can purge the branch.

**Review by CohenCyril — APPROVED** [review]
Obviously

**Comment by CohenCyril** [comment]
I'm not sure how to read failing CI anymore, anyway I do not see how the failure could be related to this PR...

**Comment by Zimmi48** [comment]
The GitLab pipeline did not started (it often happens) but it seemed unnecessary to me to restart it for just a comment.

**Comment by CohenCyril** [comment]
Shall I merge?

**Comment by gares** [comment]
yes

**Comment by CohenCyril** [comment]
@coqbot: merge now!

**Comment by CohenCyril** [comment]
@coqbot: merge now!

**Pull request merged**
