### PR TITLE
correcting bug 5372

### PR DESCRIPTION
**Pull request by forestjulien**
The other pull-request can be closed

### CODE REVIEW

**Comment by maximedenes** [comment]
Hi Julien!

Thanks a lot for the fix!

Could you add a test file in the test-suite? Also, would you mind amending the commit to mention the bug title?

Last thing: shouldn't we integrate this fix in 8.6? If yes, could you rebase it?

**Comment by forestjulien** [comment]
Hi Maxime, 
maybe we can push the fix  #495 and not this one (it integrates both my modifications and a test file). 

For the rebase on v8.6, I can do it but (as far as I kown) only by pushing it directly on gforge not on github (I don't think I have the rights to do that). And first of all, I must first check the correction is also valid in v8.6 (I think that's good but I'm not sure)

**Comment by maximedenes** [comment]
In fact, pull request authors can rebase and push to the same branch as they used to create it. But given that we want to merge #495, I'll ask @tchajed if he can do it. Travis will run automated tests that should tell us if it works ok in 8.6. So no action required on your side, I believe, since you answered @tchajed original question about the anomaly. Thanks!

**Comment by tchajed** [comment]
@forestjulien: thanks for the explanation, that makes me feel better that this is the right fix! I'm not sure what comment to add to the code so I didn't add any explanation (sorry).

Also no hard feelings about the pull request, I understand that the process around using GitHub is neither obvious to people nor documented. Seems like everything worked out, once #495 is merged.

**Pull request closed without merging**
