### PR TITLE
Assign circleci files to @SkySkimmer

### PR DESCRIPTION
**Pull request by SkySkimmer**
Someone should volunteer to be secondary maintainer.

### CODE REVIEW

**Comment by ejgallego** [comment]
I'd be happy to help too. Taking this as the CI maintainer, but won't merge fast as to allow discussion.

**Comment by Zimmi48** [comment]
> Taking this as the CI maintainer, but won't merge fast as to allow discussion.

In principle, the owner of the CODEOWNER file is Maxime. Just saying...

**Comment by aspiwack** [comment]
I can be of help. But I do believe that @ejgallego would be a better secondary maintainer indeed.

**Comment by SkySkimmer** [comment]
Updated.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
