### PR TITLE
Check types when converting irrelevant terms in old unification

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fixes probably many strange issues such as the example in #13171

### CODE REVIEW

**Comment by gares** [comment]
Why comparing the type only if they are in sProp?

**Comment by SkySkimmer** [comment]
>Why comparing the type only if they are in sProp?

Fear of the bench

**Comment by ppedrot** [comment]
Even this way, timeo benchos et non dona ferentes.

**Comment by SkySkimmer** [comment]
What does that mean?

**Comment by gares** [comment]
Do we even have benches that turn sProp on?

**Comment by ppedrot** [comment]
@SkySkimmer run the bench and you'll see.

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/786124113

**Comment by gares** [comment]
I don't get if the bug is related to sProp or not. Can you clarify?

**Comment by SkySkimmer** [comment]
The bug is related to sprop, we unify terms at different irrelevant types and get an error because they're not really convertible.

**Comment by gares** [comment]
Sorry to insist, but I don't see how we are measuring the right thing. AFAIK no job enables sprop, so we are not measuring how much the new code branch costs, but only how much does the if guard costs. Is this what we want to measure?

Also I still don't see how the bug is sprop only. Sure, the reported one is, but the buggy code path seems accessible even without sprop no?

**Comment by SkySkimmer** [comment]
Converting terms at different non sprop types will fail without prechecking the types.

**Comment by SkySkimmer** [comment]
~~~

┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   57.31   57.91 -1.04 % │      159051913560      159741788069 -0.43 % │      215912196581      215770524392 +0.07 % │     476980     475144  +0.39 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   61.20   61.45 -0.41 % │      169685839123      170466124770 -0.46 % │      212680824104      212523122095 +0.07 % │     530672     530128  +0.10 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  159.06  159.59 -0.33 % │      441317442906      442470717847 -0.26 % │      553012851984      552705636345 +0.06 % │     822036     821876  +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  105.44  105.76 -0.30 % │      301221453795      301990366546 -0.25 % │      401671138429      401574803180 +0.02 % │     489340     491164  -0.37 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  156.88  157.34 -0.29 % │      437058675826      436755977510 +0.07 % │      605474124267      605725320180 -0.04 % │     759780     732640  +3.70 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1268.48 1271.90 -0.27 % │     3530398771327     3538643105270 -0.23 % │     4979577038946     4977683672559 +0.04 % │    1180872    1167384  +1.16 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2576.06 2581.98 -0.23 % │     7181447700199     7190685268877 -0.13 % │    11817812158491    11818000303766 -0.00 % │     775344     775348  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  223.53  223.90 -0.17 % │      619428402870      619468435636 -0.01 % │     1027253010852     1026003625476 +0.12 % │    1086912    1087032  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1473.75 1475.88 -0.14 % │     4106202062967     4110059217469 -0.09 % │     6239965696227     6229684636296 +0.17 % │    1182180    1154116  +2.43 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  609.18  609.90 -0.12 % │     1690667809579     1692859434167 -0.13 % │     2585374453019     2581978421545 +0.13 % │    1009988     998212  +1.18 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  663.22  663.92 -0.11 % │     1848529422223     1849673409938 -0.06 % │     2564891578096     2562848193778 +0.08 % │    1130152    1130048  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4951.65 4954.21 -0.05 % │    13752431420279    13761802880218 -0.07 % │    23780715436550    23785525721956 -0.02 % │    2393460    2442360  -2.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  543.13  543.26 -0.02 % │     1517497206562     1518695813723 -0.08 % │     2801776946709     2802897008532 -0.04 % │     792916     792612  +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1262.03 1262.26 -0.02 % │     3514454730088     3515490919507 -0.03 % │     4918375371369     4911313094367 +0.14 % │     935196     935236  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1063.93 1063.67 +0.02 % │     2965641799166     2961797945564 +0.13 % │     4731431737860     4731456512974 -0.00 % │    1014060    1014812  -0.07 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1638.34 1637.52 +0.05 % │     4567148214149     4560382797752 +0.15 % │     7012565164567     7007619675250 +0.07 % │     855328     855536  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  536.78  536.48 +0.06 % │     1497383311196     1496647685446 +0.05 % │     1903359240996     1901971685907 +0.07 % │    1423496    1422980  +0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  649.73  649.29 +0.07 % │     1819357360058     1818821904461 +0.03 % │     2744732950714     2744016247896 +0.03 % │    2997360    2997060  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  172.04  171.92 +0.07 % │      478649845988      478418683791 +0.05 % │      676724349681      676685586096 +0.01 % │     692204     692324  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  383.81  383.41 +0.10 % │     1079722289360     1078550595819 +0.11 % │     1854936963733     1850008567388 +0.27 % │    3507232    3507236  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   69.89   69.81 +0.11 % │      191479412682      191402618471 +0.04 % │      246192441774      246110845101 +0.03 % │     583452     582604  +0.15 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   80.62   80.45 +0.21 % │      221941217383      222030142469 -0.04 % │      312427205550      312368453781 +0.02 % │     768612     768400  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  531.81  530.64 +0.22 % │     1483308456052     1482517309450 +0.05 % │     2002094595730     2001256336606 +0.04 % │     593068     594044  -0.16 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  216.22  215.68 +0.25 % │      603461317850      600691457516 +0.46 % │      830918261716      829436697928 +0.18 % │     518948     519192  -0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4000.90 3990.67 +0.26 % │    11128865045085    11106232232420 +0.20 % │    21163303303154    21161243463721 +0.01 % │    1018240    1018556  -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  325.24  324.08 +0.36 % │      880798777045      877858967731 +0.33 % │     1425911956721     1425440106191 +0.03 % │     635828     677288  -6.12 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1066.16 1062.29 +0.36 % │     2966201185253     2954833567051 +0.38 % │     4653045830948     4652197193399 +0.02 % │    1190092    1070608 +11.16 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  227.32  226.49 +0.37 % │      632547720196      630377148184 +0.34 % │      963170663727      963109366865 +0.01 % │     692620     693236  -0.09 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   48.11   47.93 +0.38 % │      133235489752      133073093004 +0.12 % │      184485211758      184506990616 -0.01 % │     486396     486404  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  140.91  140.28 +0.45 % │      391855255769      390852534916 +0.26 % │      503934631490      503931519741 +0.00 % │     560004     563788  -0.67 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   50.76   50.52 +0.48 % │      138683605523      138436264632 +0.18 % │      176777016519      176773899813 +0.00 % │     521808     521800  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  123.40  122.41 +0.81 % │      340007972000      338950396646 +0.31 % │      416177212198      415508348232 +0.16 % │     600268     600264  +0.00 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
~~~

**Comment by SkySkimmer** [comment]
Let's see how it goes if we remove the relevance guard https://gitlab.com/coq/coq/-/jobs/792600977

**Comment by SkySkimmer** [comment]
Right, removing the guard doesn't compile because for relevant terms they may have a supertype so converting the types is too strict.

**Comment by SkySkimmer** [comment]
>@SkySkimmer run the bench and you'll see.

@ppedrot  I still don't know what it means.

**Comment by SkySkimmer** [comment]
@coq/pretyper-maintainers ping

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now plz

**Comment by gares** [comment]
@coqbot merge now (sudo)

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
Next time I'll try with `coqbot merge now (drop table BUGS)` ;-)

**Comment by Zimmi48** [comment]
Sorry, this is a bug from GitHub (inconsistent databases) that I need to work around in coqbot. It used to be infrequent. It has become very frequent this week, so this is becoming a higher priority, but I've been busy with other stuff.

**Comment by gares** [comment]
OK, it was just confusing then. Maybe a message "please retry later" would have suffice

**Comment by Zimmi48** [comment]
I should put "Internal error" :stuck_out_tongue_closed_eyes:

**Pull request merged**
