### PR TITLE
Refactor code in rewrite.ml

### PR DESCRIPTION
**Pull request by Zimmi48**
@mattam82 @ppedrot : Here are the changes I made following your advice. Normally, there is no semantic change, only refactoring. It passes the test-suite (I mean it passes the same tests the trunk passed before the changes). Tell me if it looks OK to you.
Thanks.

### CODE REVIEW

**Comment by gasche** [comment]
The field record punning syntax (`f;` for `f = f;`) was introduced in OCaml 3.12.0. If the (OCaml >= 3.12.1) dependency marked in Coq's INSTALL file is accurate, you may use it in your patch -- I think it would improve readability.

**Comment by Zimmi48** [comment]
Thanks for the syntax suggestion. I didn't know that. I'll do the change.
As for term1 and ty1, it is because I'm planning to add a term2 and ty2 later. I tried not to change the code to much however.
I also chose the name "unfresh" instead of "avoid" to name the list of unfresh identifiers in the record type.

**Comment by gasche** [comment]
> As for term1 and ty1, it is because I'm planning to add a term2 and ty2 later.

Indeed, this makes perfect sense. (Punning is nice but one should not become enslaved to it.)

**Comment by letouzey** [comment]
This is a test comment
(Debugging a new transfer method for github notifications toward coqdev...)

**Pull request closed without merging**
