### PR TITLE
Separate interning and pretyping of universes

### LINKED ISSUE #13303: Notations don't resolve universes until use
#### Description of the problem

As pointed out by @SkySkimmer in #13299, in the current system (both master and this PR) universe expression are unchanged by the intern phase and completely handled at the pretyping phase, but we should be resolving global universes in the intern phase.

#### Test Cases

```coq
Module M. Universe i. End M.
Module N. Universe i. End N.
Import M.
Notation foo := Type@{i (* M.i??? *)}.
Import N.
Check foo : Type@{M.i}. (* should NOT succeed *)
Fail Check foo : Type@{i (* N.i *)}. (* should succeed *)
```

```coq
Module M. Universe i. Notation foo := Type@{i}. End M.
Fail Definition foo1 := M.foo. (* should succeed, currently errors undeclared universe i *)
Fail Definition foo2@{i} : Type@{i} := M.foo. (* should succeed, currently errors universe inconsistency *)
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
This allows proper treatment in notations, ie fixes #13303

Overlays: https://github.com/LPCIC/coq-elpi/pull/196 https://github.com/coq-community/paramcoq/pull/60 https://github.com/mattam82/Coq-Equations/pull/337

### CODE REVIEW

**Comment by SkySkimmer** [comment]
TODO write up an explanation of the changes

**Comment by SkySkimmer** [comment]
Wrote some stuff in the commit message.

**Comment by SkySkimmer** [comment]
Although this is a fix which could have significant impact on anyone using notations with named universes (population >= 0), it's relatively complicated so I don't know if it should be in 8.13. cc @gares

**Review by mattam82 — COMMENTED** [review]
I like the (long overdue :) change. Why does pr_glob_constr take a sigma now? For naming universes I suppose?

**Comment by SkySkimmer** [comment]
>Why does pr_glob_constr take a sigma now? For naming universes I suppose?

Because extern needs to know which universes are locally bound.

**Comment by SkySkimmer** [comment]
@mattam82 Should be ready.

**Review by mattam82 — APPROVED** [review]
Looks good to me. This is a fairly straightforward and uniform change.

**Comment by mattam82** [comment]
I added an 8.13beta1 milestone because in the end this is mainly a bugfix. @gares feel free to postpone it if that's much more work for you.

**Comment by mattam82** [comment]
@coqbot merge now

**Pull request merged**
