### PR TITLE
Drop conclusion from defined evars

### PR DESCRIPTION
**Pull request by ppedrot**
This should release a lot of memory early.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by Alizter** [comment]
What happened with the resident memory here?
```
│        coq-engine-bench-lite  1202332  1069980   12.37 │

```
Other than that, it seems to take a good chunk off.

**Comment by ppedrot** [comment]
The bench is not very good at measuring memory use, it relies on OS profiling. We should extend Coq with finer ways to display memory consumption using OCaml internals instead. So, the effects of this PR are not very clear.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
I am marking this as ready as it doesn't need any overlay now and it cannot hurt.

**Comment by Alizter** [comment]
Apparently we have a `coqc -m` command for memory. Shall we add it to the bench?

**Comment by ppedrot** [comment]
@Alizter indeed, but this requires a bit of rework. We don't care about some data that has a cost to generate, and the output of the GC is redirected to a file that needs to be passed through an environment variable.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
