### PR TITLE
Fix #7323: coqchk puts polymorphic univs of inductive in global env

### LINKED ISSUE #7323: coqchk: polymorphic inductives add their universes to the context
eg
```coq
Set Universe Polymorphism.

Inductive ind@{u v | u < v} : Prop := .

Definition cst@{u v | v < u} := Prop.
```
will fail in the checker because `ind` will add `Var(0) < Var(1)` to the context and it will still be there when `cst` wants to add `Var(1) < Var(0)`.

This is triggered by HoTT after #6798 is merged.

### PR DESCRIPTION
**Pull request by SkySkimmer**
EDIT: Fixes #7323.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Indeed a stupid bug. The fix seems correct.

**Comment by ppedrot** [comment]
@SkySkimmer Can you rebase?

**Comment by SkySkimmer** [comment]
Rebased.

**Comment by ppedrot** [comment]
Let's wait for the CI, I'll merge when it finishes.

**Pull request merged**
