### PR TITLE
[checker] Add missing Feedback printer (BZ#5587)

### PR DESCRIPTION
**Pull request by ejgallego**
This fixes longstanding bug likely introduced in the first `pp` to
`Feedback` migration, namely the checker didn't register a feedback
printer, thus no calls to `Feedback.msg_*` were printed in the
checker.

This closes bug: https://coq.inria.fr/bugs/show_bug.cgi?id=5587

We fix this by adding a custom printer to the checker, this is correct
as the checker owns now the full console, however a cleanup should
happen in any of these two directions:

- all the calls to feedback are removed, and the checker always uses
  its own printing mechanism.

- all the calls to `Format/Printf` are removed and the checker always
  uses the `Feedback` mechanism.

Currently, I have no opinion on this.

### CODE REVIEW

**Comment by ejgallego** [comment]
For some reason the `validate` target is not setting the `quiet` flag properly, looking into that.

**Comment by maximedenes** [comment]
I'm trying to fix the Travis failure due to verbosity.

**Comment by maximedenes** [comment]
It turns out `coqchk` ignores the `-silent` flag since https://github.com/coq/coq/commit/ff918e4bb0ae23566e038f4b55d84dd2c343f95e#diff-4b449d7a20333f564dd562eef52b33ceL29

**Comment by maximedenes** [comment]
Btw, I wonder how these changes to the checker were tested, with `coqchk` emitting no output.

**Comment by ejgallego** [comment]
Good catch; yeah, indeed we need to improve the checker test-suite.

**Comment by maximedenes** [comment]
Superseded by #1075.

**Pull request closed without merging**
