### PR TITLE
Fix "obligation already solved" message

### LINKED ISSUE #15106: Obligation already solved message is mis-numbered and mis-spaced
#### Description of the problem

```coq
Require Import Coq.Program.Program.
Obligation Tactic := try constructor.
Program Definition foo := (fun (x : False) (y : True) => I) _ _.
Obligation 2. (* Error: Obligation 1already solved. *)
```

#### Coq Version

8.13

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15106

### CODE REVIEW

**Review by JasonGross — DISMISSED** [review]
Thanks!  Code change looks good to me, but the output test needs an expected output file.  (Does it also need to be `Fail Obligation 2`, or are output tests allowed to fail?)

And does this need a changelog entry, or is it too small?

**Comment by SkySkimmer** [comment]
No need for changelog

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
I was going to suggest making an algebraic exception, but I think it better to do a pass in a future PR.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
