### PR TITLE
Increase timeout for fiat-crypto.

### PR DESCRIPTION
**Pull request by Zimmi48**
On `v8.17`, I'm getting too many timeouts related to fiat-crypto.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Shouldn't we test less of fiat-crypto instead?

**Comment by JasonGross** [comment]
> Shouldn't we test less of fiat-crypto instead?

It seems that fiat-crypto keeps finding bugs in Coq, and it's not clear to me that there's an easy way to get the coverage of fiat-crypto without testing all of fiat-crypto.  Additionally, maintaining targets for Coq's CI that stop the build in arbitrary places is a moderate maintenance overhead on fiat-crypto.  It's also the case some of the recent memory (and time?) overheads on fiat-crypto were fixed by Coq-side improvements, and I'd be quite interested in knowing if there are any more low-hanging optimization fruit for fiat-crypto.

**Review by Alizter — APPROVED** [review]
Let's do this for the time being and think about how to test less of fiat crypto at a late date.

**Comment by Alizter** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
>Let's do this for the time being and think about how to test less of fiat crypto at a late date.

How do we avoid that being "never"?

**Comment by Alizter** [comment]
@SkySkimmer We can't avoid it, but we can create an issue to remind ourselves that it is still a problem. Since this is affecting the 8.17 branch we should merge this so we don't get as many timeouts.

**Comment by Zimmi48** [comment]
I can merge only in `v8.17` if @SkySkimmer prefers.

**Comment by SkySkimmer** [comment]
yes

**Comment by Zimmi48** [comment]
Sorry for the accidental code reviews while changing this PR base.

**Pull request merged**
