### PR TITLE
[ocaml] [lib] Remove some compatibility layers for OCaml < 4.03.0

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Didn't you have some compatibility layers in coq_dune as well?

**Comment by ejgallego** [comment]
> Didn't you have some compatibility layers in coq_dune as well?

There were already taken care of by the main 4.05 PR.

**Comment by ejgallego** [comment]
This is not to say that indeed quite a few parts of the code can take advantage of the new compiler. In addition to some existing PRs, now @ppedrot can add inline annotations at will :)

**Comment by ejgallego** [comment]
Ready to go, needs an assignee. All trivial code changes.

**Review by ppedrot — APPROVED** [review]
LGTM, will merge quickly if no objections.

**Pull request merged**
