### PR TITLE
[declare] Move proof_entry type to declare, put interactive proof data on top of declare.

### PR DESCRIPTION
**Pull request by ejgallego**
This PR is a follow up to #10406 , moving the then introduced
`proof_entry` type to `Declare`.

This makes sense as `Declare` is the main consumer of the entry type,
and already provides the constructors for it.

This is a step towards making the entry type private, which will allow
us to enforce / handle invariants on entry data better.

A side-effect of this PR is that now `Proof_global` does depend on
`Declare`, not the other way around, but that makes sense given that
closing an interactive proof will be a client of declare.

Indeed, all `Declare` / `Pfedit` / and `Proof_global` are tied into
tactics due to `abstract`, at some point we may be able to unify all
them into a single file in `vernac`.

Overlay:
- https://github.com/mattam82/Coq-Equations/pull/237

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ejgallego** [comment]
I've added a small cleanup on trivial uses of the record, after that only two places do indeed access entry internals in write mode:
- `Abstract` due to the shrink hackery [indeed this is a good candidate to become primitive "declare" functionality"
- `Proof_global` for hack related to building delayed constraints. Indeed refactoring that is one of the main goals of this series of PRs, still unclear how to best resolve this [a few options are possible.
- `Lemmas`, with the infamous `adjust_guardness_conditions`

For the goal of making the type fully private, that is, no read-only access, we have:
- some hackery in `Pfedit` related to side-effects [solvable]
- `Obligations` and `Definition` related to delaying indeed, solvable but will take time

So quite a bit of work to do but nothing unfeasible IMO.

**Comment by ejgallego** [comment]
It seems this is ready for merge, right @ppedrot ? Would you like to be the assignee? [seems like the natural choice to me]

**Comment by ppedrot** [comment]
Will merge soon if nobody complains.

**Comment by ejgallego** [comment]
Merci.

**Pull request merged**
