### PR TITLE
Simplify proof of Peano_dec.le_unique

### PR DESCRIPTION
**Pull request by jeanas**

### CODE REVIEW

**Comment by jeanas** [comment]
(CC @maximedenes as author of e0c70fc7cd8)

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
This makes the proof depend on an axiom instead of being axiom free

**Comment by jeanas** [comment]
Ugh. I didn't know `dependent destruction` used the `eq_rect_eq` axiom. (AFAICS it is not documented.) Let me fix this.

**Comment by mukeshtiwari** [comment]
@jeanas  I have written a few proofs of `le_unique` and you can see them here [1] (see the file Le_unique_first.v). They depend on uniqueness of identity proof (uip_nat), which is provable in Coq so basically they are axiom free. @DmxLarchey has written the other two (Le_proof_more_Dominique.v, Le_unique_Dominique.v). (I always wanted to push the code but I didn't know how to build Coq locally so I never managed to push it). 

[1] https://github.com/mukeshtiwari/Le_unique_proof

**Comment by ppedrot** [comment]
@jeanas since there is no progress, I'm closing this PR. Please reopen if you implement the axiom-free version.

**Comment by jeanas** [comment]
OK, I did a new version. https://github.com/coq/coq/commit/06dc205a2e2867e31b4e837ae4a669d7cae213f5 Not as simple as I had hoped, but still hopefully more readable than the previous dance with `generalize n0 at 1 4 5 7` and suchlike.

@ppedrot It looks like I don't have the rights to reopen the PR myself. Also, I (force-)pushed the changes to my branch but for some reason they don't seem to appear here (??).

**Comment by jeanas** [comment]
@mukeshtiwari Thanks, that was helpful.

**Comment by ppedrot** [comment]
I believe that github doesn't like if you force-push a branch while the PR is closed, so you should just open a fresh one.

**Comment by jeanas** [comment]
OK, done https://github.com/coq/coq/pull/19893

**Pull request closed without merging**
