### PR TITLE
Vernactypes: use record instead of multiple arguments and tuples

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should make it easier to add states (eg opaque tables).

### CODE REVIEW

**Comment by ppedrot** [comment]
I think that this is even a legitimate use case of objects, or maybe at least of a map indexed with a phantom object type that tracks the available components (à la js_of_ocaml).

**Comment by SkySkimmer** [comment]
What would that buy us?

**Comment by ppedrot** [comment]
Even more future-proof code, as you don't have to rely on a fix arity of fields.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
Indeed we could maybe even do better, but IMO this is already an improvement so no reason to delay it. Will merge tomorrow if no one opposes.

The QC failure in CI is also present in `master` :/

**Comment by SkySkimmer** [comment]
See #18826 for quickchick

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
