### PR TITLE
Show correct index entries in pdf

### LINKED ISSUE #12361: Multiple index keys for the same command does not work in the PDF output.
#### Description of the problem

In the 8.12 version of the reference manual, it is possible to have a single command that is referred to by multiple index keys (this is the case of `Definition` / `Example`, `Theorem` and variants, `Parameter` and variants, `Require` / `Require Import` / `Require Export`, `Implicit Type` and plural form, `Record` / `Structure`). This works fine in the HTML output, but it doesn't in the PDF output: only the last key works, and the others are displayed with some `??` showing a reference not found.

See example here: https://coq.gitlab.io/-/coq/-/jobs/543104421/artifacts/_install_ci/share/doc/coq/sphinx/latex/CoqRefMan.pdf

#### Coq Version

v8.12 and master

cc @jfehrle who implemented this feature

### PR DESCRIPTION
**Pull request by jfehrle**
Fixes #12361

### CODE REVIEW

**Comment by Zimmi48** [comment]
Wow, that was fast!

**Comment by jfehrle** [comment]
Don't be too impressed until I check that it works.  Remember I can't build the pdf index on my system.  :smiley:

**Comment by jfehrle** [comment]
I've tried a lot of things, basically all day, but I have a limited understanding of docutils and a very limited understanding of Latex.  At the moment the general index in the pdf has the right entries with their page numbers, but the pdf Commands index is still missing page numbers except for 9 of the alternatives (except for `Variables`).  Both the general and command indexes in the HTML are correct.

@cpitclaudel If you have any suggestions I'd like to hear them.

The current bits generate the following nodes for the `Variables` command (from printf (node) after `node = newnode`):

```
<inline>
    <inline first="False" ids="['coq:cmd.axiom']" names="['Axiom']"/>
    <inline first="False" ids="['coq:cmd.axioms']" names="['Axioms']"/>
    <inline first="False" ids="['coq:cmd.conjecture']" names="['Conjecture']"/>
    <inline first="False" ids="['coq:cmd.conjectures']" names="['Conjectures']"/>
    <inline first="False" ids="['coq:cmd.hypothesis']" names="['Hypothesis']"/>
    <inline first="False" ids="['coq:cmd.hypotheses']" names="['Hypotheses']"/>
    <inline first="False" ids="['coq:cmd.parameter']" names="['Parameter']"/>
    <inline first="False" ids="['coq:cmd.parameters']" names="['Parameters']"/>
    <inline first="False" ids="['coq:cmd.variable']" names="['Variable']"/>
    <desc desctype="cmd" domain="coq" noindex="False" objtype="cmd">
        <desc_signature first="False" ids="coq:cmd.variables" names="Variables">
            <desc_annotation xml:space="preserve"><inline classes="sigannot">Command</inline></desc_annotation> <desc_name
                xml:space="preserve"><inline classes="notation"><pending_xref refdomain="std" reftarget="assumption_token" reftype="token"><inline classes="hole">assumption_token</inline></pending_xref> <inline
   :
```

For which I get the following in the tex file:

```
\phantomsection\label{\detokenize{language/core/assumptions:axiom}}
\index{Variables (command)@\spxentry{Variables}\spxextra{command}}
\index{Axiom (command)@\spxentry{Axiom}\spxextra{command}}
\index{Axioms (command)@\spxentry{Axioms}\spxextra{command}}
\index{Conjecture (command)@\spxentry{Conjecture}\spxextra{command}}
\index{Conjectures (command)@\spxentry{Conjectures}\spxextra{command}}
\index{Hypothesis (command)@\spxentry{Hypothesis}\spxextra{command}}
\index{Hypotheses (command)@\spxentry{Hypotheses}\spxextra{command}}
\index{Parameter (command)@\spxentry{Parameter}\spxextra{command}}
\index{Parameters (command)@\spxentry{Parameters}\spxextra{command}}
\index{Variable (command)@\spxentry{Variable}\spxextra{command}}

\begin{fulllineitems}
\phantomsection\label{\detokenize{language/core/assumptions:coq:cmd.variables}}
\pysigline{\sphinxbfcode{\sphinxupquote{\DUrole{sigannot}{Command}}} \sphinxbfcode{\sphinxupquote{\DUrole{notation}{{\hyperref[\detokenize{language/core/assumptions:grammar-token-assumption-token}]{\sphinxcrossref{\DUrole{hole}{assumption\_token}}}}~
  :
```

**Comment by jfehrle** [comment]
Interesting detail: links in the index jump to the top of the page containing the command name, whereas `:cmd:` links jump to the exact spot mid-page.

**Comment by Zimmi48** [comment]
IIUC this should be closed in favor of #12380.

**Pull request closed without merging**
