### PR TITLE
[vernac] Remove unused `start_hook` `save_hook` from Lemmas.

### PR DESCRIPTION
**Pull request by ejgallego**
These hooks are 10-years old and long unused I think.

### CODE REVIEW

**Comment by ppedrot** [comment]
I think it used to be set by the XML plugin, if memory serves.

**Comment by ejgallego** [comment]
> I think it used to be set by the XML plugin, if memory serves.

Could be, it was indeed used by Coq itself in the 2008 implementation, see e8ef565dadd110329f806fa3c281055fcd807440

**Comment by ejgallego** [comment]
This is trivial I think and thus ready for merge.

**Comment by herbelin** [comment]
OK, let me assign. Shall merge late tonight.

**Review by herbelin — APPROVED** [review]
It is simple enough to add it again if ever some plugin needs it.

**Comment by ejgallego** [comment]
¡Gracias!

**Pull request merged**
