### PR TITLE
[build] Fix missing (EXE) in tool name in makefile.

### PR DESCRIPTION
**Pull request by ejgallego**
Was causing failures on windows builds.

### CODE REVIEW

**Comment by Zimmi48** [comment]
@ejgallego Your branch has conflicts with `master`. Can you rebase so that CI can run?

**Comment by ejgallego** [comment]
Ups sorry about that.

**Review by gares — APPROVED** [review]

**Comment by Zimmi48** [comment]
This doesn't fix the problem :cry:

**Comment by SkySkimmer** [comment]
Looks like windows is building the wrong commit, you can see https://gitlab.com/coq/coq/-/jobs/1219206204#L1438
>[coq.dev] synchronised from git+https://github.com/coq/coq.git#master

**Comment by SkySkimmer** [comment]
So I think this fixes the missing exe bug, and there is also a ci bug which should be handled in another PR

**Comment by Zimmi48** [comment]
So that would explain why CI didn't catch the problem in the Dune PR.

**Comment by ejgallego** [comment]
Yup, I was puzzled by the failure, indeed the CI setup is fishy. IMVHO this is safe to merge anyways if we want.

**Comment by Zimmi48** [comment]
If we don't fix the Windows CI issue leading to test the `master` branch instead of the PR branch, then we should disable it on PRs since it is useless and confusing.

**Comment by ejgallego** [comment]
> If we don't fix the Windows CI issue leading to test the `master` branch instead of the PR branch, then we should disable it on PRs since it is useless and confusing.

Agree; I'd suggest opening a new issue and merging this PR .

**Comment by Zimmi48** [comment]
OK

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
