### PR TITLE
Improve the Gallina chapter of the reference manual.

### PR DESCRIPTION
**Pull request by Zimmi48**
Fixes around the documentation of terms.
Including adding missing irrefutable-patterns to the grammar of binders.

Things that are still missing after this commit in the grammar of terms are:
- explicit `Type` annotations (cc @SkySkimmer)
- primitive projections

Additionally, what is `term :>`? It is in the grammar but not described in the rest of the section below.

EDIT: depends on #7606

### CODE REVIEW

**Comment by Zimmi48** [comment]
Thanks! Is that documented anywhere? I guess documenting it is just a matter of adding one sentence in the "Cast" subsection...

**Comment by SkySkimmer** [comment]
>Thanks! Is that documented anywhere? I guess documenting it is just a matter of adding one sentence in the "Cast" subsection...

It's mentioned in https://github.com/coq/coq/blob/master/doc/sphinx/addendum/program.rst#syntactic-control-over-equalities
>Also, :g:`term :>` explicitly asks the system to coerce term to its support type. It can be useful in notations, for example [...]

**Comment by Zimmi48** [comment]
I think we just need to create a specific issue regarding the grammars in the reference manual (see also #7583).

**Comment by Zimmi48** [comment]
I've finished this PR. Note that it is based upon #7606 because in some cases we have a common documentation for several objects. It leaves no object without body in this chapter (sometimes it uses the `:undocumented:` flag, in particular for many error messages). But we cannot automatically check and enforce this (until #7602 is solved).

**Review by maximedenes — APPROVED** [review]
I approve this PR blindly :)

**Pull request merged**
