### PR TITLE
Avoid Level.Set.union in univs_of_constr + factorize code

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
I remember a similar change being impactful when we used Instance.levels, but apparently not this time.

**Comment by SkySkimmer** [comment]
I guess the `init` stuff doesn't matter but the code factorization is still nice (less places to modify when we change constr)

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Pull request merged**
