### PR TITLE
Farewell decl_mode

### PR DESCRIPTION
**Pull request by gares**
This commit removes from the source tree plugins/decl_mode,
its chapter in the reference manual and related tests.

### CODE REVIEW

**Comment by gares** [comment]
I need people to check if the change to firstorder is fine.
In the process of removing the code, I notice that firstorder did (apperently) set hooks in decl_mode.

**Comment by ejgallego** [comment]
IMHO #220 should be merged first, also, the orphaning notice and wait period should be given.

Depending on the result of the orphaning, further cleanups could be done. There seems to be a fair amount of `decl_mode` specific API (including hooks for printing and the proof mode) that IMO would be great to remove (in favor of the newly proposed API) if nobody steps up to maintain the mode.

This would also impact #455

**Comment by gares** [comment]
fail on geocoq only, so I guess it is fine.

**Comment by ejgallego** [comment]
> geocoq only, so I guess it is fine.

Yes, that should be fine. Who is sending the orphaning mail?

**Comment by Zimmi48** [comment]
Wasn't the conclusion of the discussion at the working group:
- remove the decl_mode
- create a repository with the code of the plugin
- mark this repository as "looking for a maintainer"
- send an announcement about all of this
?

@ejgallego Are proposing instead to send the notice and wait for a grace period before taking any action?

@gares Do you intend to create the new repo as well? It would be cool if the commit history could be kept. I'm not sure how to do that. Do you know how to do it?

**Comment by silene** [comment]
> It would be cool if the commit history could be kept. I'm not sure how to do that. Do you know how to do it?

    git filter-branch --prune-empty --subdirectory-filter plugins/decl_mode/ temporary_branch
    git push decl_mode_repo temporary_branch:master

**Comment by ejgallego** [comment]
> @ejgallego Are proposing instead to send the notice and wait for a grace period before taking any action?

Indeed I think first we should try to send the notice now. If a new maintainer appears, they should have the say on how they want to proceed.

If no new maintainer steps forward, I would just delete the code.

**Comment by Zimmi48** [comment]
> If no new maintainer steps forward, I would just delete the code.

This seems pretty radical to me. It must be noted that:
- as of today, the declarative mode seems still to be working somehow (at least the features that I tested, cf. https://github.com/coq/ceps/pull/16#issuecomment-285087662);
- there are some good ideas in this mode that are worth not forgetting: one of them is the induction / case-analysis feature (even though I am not fully convinced by the result);
- the orphaning announcement that we send won't be wide spread enough; and the grace period won't be long enough; by creating a repo with the code and an announcement there, we are sending a permanent call for maintainers, and someone could very well step forward in 7 months, when they realize that the declarative mode is not part of Coq 8.7.

Of course I know that nothing would be completely lost because of git history but browsing a repo is much easier than browsing git history, I think.

**Comment by maximedenes** [comment]
I agree, the cost of making this code available on a distinct repo seems very low, so why not do it?

**Comment by ejgallego** [comment]
> This seems pretty radical to me.

Are you volunteering to maintain the mode?

> the orphaning announcement that we send won't be wide spread enough; and the grace period won't be long enough;

How so? IMHO two weeks + coq-club is more than enough.

> I agree, the cost of making this code available on a distinct repo seems very low, so why not do it?

Just there is no point, either the new maintainer does it, or I totally fail to see the point or having another abandoned repository. The existing 8.6 repos works for that.

**Comment by Zimmi48** [comment]
> Are you volunteering to maintain the mode?

No.

**Comment by ejgallego** [comment]
For the record, would a maintainer pop up I do indeed volunteer to help them to integrate the code with the ongoing efforts on the tactic parsings modes.

**Comment by gares** [comment]
Merging this PR *does not delete* any history or code in a non-reversible way.
FTR, the command @silene suggests can be run in 10 years from now.

It is the whole point of any VCS!

**Comment by gares** [comment]
Anyway, the point of this PR was to do some of the work needed.
One still needs to announce the removal and create the repo (as discussed at the GT).

I to think nobody will step in, and hence creating the repo is pointless, but this is what was discussed.
I'm doing it (as soon as I'm back from VAC)

**Comment by ppedrot** [comment]
Any progress on this front?

**Comment by maximedenes** [comment]
@mattam82 said he woud send an e-mail last Friday :)

**Comment by herbelin** [comment]
A mail to the author first, then to coq-club?

**Comment by maximedenes** [comment]
Indeed, that's what I suggested, thinking it would be more polite.

**Comment by maximedenes** [comment]
@mattam82 Can you send the announcement? I'd like to merge this PR next week. Thanks!

**Comment by mattam82** [comment]
Yes right, I'll send the email today, the maintainer agreed on the way we decided to proceed at the working group.

**Comment by mattam82** [comment]
And done

**Pull request merged**
