### PR TITLE
Iris CI: use opam to install dependencies

### PR DESCRIPTION
**Pull request by RalfJung**
Let's see if this works...

### CODE REVIEW

**Comment by ejgallego** [comment]
I'm afraid this is conflict with other goals for the CI infrastructure, IMHO it is OK to use OPAM to extract meta information, but actually depending on opam may be a different story.

**Comment by RalfJung** [comment]
opam is already installed, so I am not sure what the problem is. And it seems like the most natural thing to use a package manager to install packages... I don't think anything else will scale, if more people start to use opam seriously and actually depend on things.

But anyway, how would "using opam to extract meta information" even work?

**Comment by SkySkimmer** [comment]
This fake-coq seems pretty hacky. I prefer the `curl`+`grep` system in https://github.com/coq/coq/pull/1006#issuecomment-330841608
We could use `opam show` to get the commit, the annoying part is getting the right version of stdpp to call it with.

**Comment by RalfJung** [comment]
> This fake-coq seems pretty hacky.

True. OTOH, this should actually scale to install packages with arbitrary many opam-managed dependencies as part of the CI.

> We could use opam show to get the commit

I looked at `opam show -f depends`, but that's not very parseable either.

> the annoying part is getting the right version of stdpp to call it with.

A less-hacky version could do
```
opam repo add iris-dev https://gitlab.mpi-sws.org/FP/opam-dev.git -p 0
opam show coq-stdpp.$STDPP_VERSION -f upstream-url
```

**Comment by SkySkimmer** [comment]
That's what I was intending, but if I get $STDPP_VERSION by some adhoc grep I'm not sure there's much value in going through opam for the last step rather than curling the right URL.

**Comment by Zimmi48** [comment]
> That's what I was intending, but if I get $STDPP_VERSION by some adhoc grep I'm not sure there's much value in going through opam for the last step rather than curling the right URL.

Opam being already installed, what would it cost to use it to get this information?
As the very least, this looks more readable, and easier to reproduce on some other examples.

**Comment by RalfJung** [comment]
I am unfortunately hitting some very weird design problem in opam. (Again.) Even though I created a new pin file for coq, opam still honors the `coq.install` file from the main opam repository, and then of course things break. I don't see how this makes any sense; setting a pin shouldn't mix-and-match the package description from the repository and the path things are pinned to. I can't come up with a work-around right now.

(Also, I have no idea why opam decides to upgrade camlp when I request installation of the pinned coq package.)

**Comment by RalfJung** [comment]
Fake package installation works now. I made a silly mistake in the "install build-dependencies" part of the script, which I only just fixed, so the next round of CI will hopefully show whether the fake packages are enough to "fool" opam.

However, it still insists on upgrading camlp. It's almost as if some part of the "real" coq package "leaks through" even though we prepared this fake version. I will try to set an empty `depends`, maybe opam doesn't consider missing fields to be empty but instead makes them some form of overlay?

**Comment by RalfJung** [comment]
CI passes now. I still do not understand why it upgrades camlp.

**Comment by RalfJung** [comment]
Somehow travis got confused and re-checked f9eaa747 rather than checking  dc4a961.

**Comment by RalfJung** [comment]
*sigh* and yet another strange failure. I *think* what is going on is that the opam directory gets cached, and hence opam thinks that stdpp is still installed -- but at the same time, the directory where Coq libraries are installed to is *not* cached, and hence stdpp is actually *not* installed.

**Comment by RalfJung** [comment]
Ideally, the opam that's cached would be the state right before this CI runs.

Or maybe it would make sense to use a dedicated opam switch for this?

**Comment by ejgallego** [comment]
Ralf, I think you've gathered enough evidence as to why we won't be using OPAM for CI in the near future :) Honestly, I think something closer to Nix is what we want.

**Comment by RalfJung** [comment]
Well, yeah, opam is not easy to use automated because it has so many strange corner-cases. However, some of this is because Coq itself is *not* built with opam by the Coq CI, so we have to hack around some of its dependency management. Nix would have the same problem. Other problems are caused by caching some things but not all things; again Nix would have the same problem.

Also, unlike Nix, opam is already (in principle) usable as a Coq package manager *now*. I don't want to have the opam.pins in Iris for the coming 2 years. Neither do we plan to support multiple package managers. Not to mention that Nix seems to have even less of a Windows story than opam, and that opam is currently being marketed as the recommended package manager for Coq and switching that one every other year will certainly not make people happy.

**Comment by ejgallego** [comment]
OPAM is great as a package manager for users; that is fine, we will extract the proper information from it to build Iris, and you are very welcome to use it.

OPAM is not great as a build system for CI, as our requirements are quite different, for example, custom patching of Makefile and build scritps. In one word, agility; had we tried to use OPAM to setup the CI system, we would have no CI system as of today. You really need _finer_ control of the build process than what OPAM will ever provide.

Please maintain the `.pins` file for a couple of extra weeks, until our CI system gains the capability to grab the info from OPAM.

**Comment by RalfJung** [comment]
All right, I am now trying (as you suggested) a different approach where opam is just used to figure out which git commit of std++ to fetch.

**Comment by SkySkimmer** [comment]
@RalfJung by the way from the frequency of your commits you seem to be waiting for Coq's travis to get to your PR to see if it works, but if you enable travis for your repository you wouldn't have to wait and you could even cancel the non-iris jobs to get a result in ~20min.

**Comment by ejgallego** [comment]
even better, you can disable all other builds in your particular Travis and thus only test the thing you want.

**Comment by RalfJung** [comment]
Ah, thanks for the hint -- I did not think of setting up Travis for my fork of Coq.

Anyway, CI passes now. :)

**Comment by SkySkimmer** [comment]
Cache is separate between branches and PRs. They can be seen at https://travis-ci.org/user/repo/caches.

**Comment by SkySkimmer** [comment]
Iris is broken again, https://gitlab.mpi-sws.org/FP/iris-coq/commit/93eb2615c36f7d87f164d567662b36259e58cc25 wasn't reflected in the .pin file.

**Comment by RalfJung** [comment]
Sorry for this, I fixed opam.pins.

What is this PR currently waiting for?

**Comment by maximedenes** [comment]
@ejgallego added the "needs: discussion" to this PR. Was it resolved?

**Comment by ejgallego** [comment]
Yeah we need to add some generic support in our CI so we can extract the metadata from OPAM; but of course feel free to merge this now.

**Comment by ejgallego** [comment]
I think the solution still has to be refined but I am happy with if if @RalfJung is [which seems to be].

Thanks @RalfJung !

**Review by ejgallego — APPROVED** [review]

**Comment by Zimmi48** [comment]
Iris still appears as broken to me, I don't know if this is related to `opam.pins` or something else is going on. Anyways, let's merge this PR quickly.

**Comment by RalfJung** [comment]
> I think the solution still has to be refined but I am happy with if if @RalfJung is [which seems to be].

It's better than opam.pins :)
However, it still doesn't really scale to e.g. adding packages that depend on Iris to the CI.

**Comment by RalfJung** [comment]
Now that this has landed in 8.7, is it okay to remove the opam.pins from Iris?

**Comment by Zimmi48** [comment]
Yes, thanks.

**Pull request merged**
