### PR TITLE
Stop calling Id.Map.domain on univ binders every individual universe

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Trusting. PS: [link](https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Printing.20performance.20regression.20from.208.2E12.2E1.20to.20master/near/218551954) to the motivating Zulip discussion.

**Comment by silene** [comment]
Should we run a bench?

**Comment by SkySkimmer** [comment]
We may do a bench after https://github.com/coq/coq/pull/13552 is merged

**Comment by gares** [comment]
This lacks an assignee

**Comment by herbelin** [comment]
I can assign. Based on the Zulip discussion and the discussion at #13552, I assume a support from at least @ppedrot. This seems urgent and I will merge at 3:30pm Paris time.

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by gares** [comment]
Hem, we don't have the bench yet

**Comment by gares** [comment]
Can I get one before backporting?

**Comment by herbelin** [comment]
I let a bench expert do it then.

**Comment by ppedrot** [comment]
I will be running at https://gitlab.com/coq/coq/-/jobs/891413057.

**Comment by SkySkimmer** [comment]
What about https://gitlab.com/coq/coq/-/jobs/891412602 (not sure who started it)?

**Comment by gares** [comment]
> Job #891412602 triggered 5 hours ago by Pierre-Marie Pédrot's avatar Pierre-Marie Pédrot 

So far it is noise. Are we sure this PR does good?
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                        │      user time [s]      │             CPU cycles              │          CPU instructions           │  max resident mem [KB]  │   mem faults    │
│                        │                         │                                     │                                     │                         │                 │
│           package_name │     NEW      OLD  PDIFF │           NEW            OLD  PDIFF │           NEW            OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-engine-bench-lite │  363.38   365.08  -0.47 │ 1021826402261  1026267714494  -0.43 │ 1744160899714  1742025063416   0.12 │ 3979180  3978948   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coqprime │   78.45    78.73  -0.36 │  216050650331   216046689162   0.00 │  305701177118   305707828667  -0.00 │  761572   762952  -0.18 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-geocoq │ 1439.54  1444.16  -0.32 │ 4015245407167  4021737296222  -0.16 │ 6135998204524  6135965840119   0.00 │ 1014168  1018332  -0.41 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-field │  221.16   221.67  -0.23 │  616358474169   617159461058  -0.13 │  948984288304   949004136905  -0.00 │  673824   673896  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-rewriter │  718.46   719.84  -0.19 │ 1994161135135  1996957866474  -0.14 │ 3100883481490  3100276291487   0.02 │  973964   973976  -0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-mathcomp-solvable │  168.53   168.80  -0.16 │  469961041519   470394265408  -0.09 │  669785339170   669814938151  -0.00 │  685012   685160  -0.02 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-odd-order │ 1050.31  1051.80  -0.14 │ 2923626059987  2927232650915  -0.12 │ 4686730209171  4686742130267  -0.00 │  984012   984084  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-ssreflect │   51.24    51.30  -0.12 │  139139301779   139006004880   0.10 │  178065460038   178030822632   0.02 │  510152   508012   0.42 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-compcert │  634.44   635.01  -0.09 │ 1768648909912  1769201863752  -0.03 │ 2468981834349  2468706728437   0.01 │ 1047584  1047464   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-mathcomp-fingroup │   46.84    46.86  -0.04 │  129838735475   130135965275  -0.23 │  180993773821   180989548438   0.00 │  477852   477724   0.03 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-character │  153.44   153.20   0.16 │  425898779802   425899185241  -0.00 │  597975798165   597963817250   0.00 │  710220   710616  -0.06 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-corn │ 1621.87  1619.26   0.16 │ 4514171472906  4505898924580   0.18 │ 6934174559650  6934162013967   0.00 │  809212   808996   0.03 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-algebra │  137.04   136.77   0.20 │  380076491590   379644542788   0.11 │  493631330272   493713449802  -0.02 │  549212   542704   1.20 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-flocq │  155.61   155.18   0.28 │  431510963825   430708353298   0.19 │  539945191598   539913497397   0.01 │  820700   820708  -0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-bedrock2 │  226.59   225.76   0.37 │  625206971767   623969445348   0.20 │ 1041346075620  1041072043526   0.03 │ 1159848  1160088  -0.02 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq │  520.30   518.16   0.41 │ 1454532566721  1451725375905   0.19 │ 1956229182616  1956617765107  -0.02 │  568628   569232  -0.11 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-color │  505.74   503.60   0.42 │ 1411096210883  1406624226389   0.32 │ 1784305377841  1784209168218   0.01 │ 1133912  1133912   0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-coqutil │   60.64    60.36   0.46 │  167551382858   167908287639  -0.21 │  209171516668   209128501747   0.02 │  524164   524172  -0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-math-classes │  213.28   211.88   0.66 │  593502210683   591016602620   0.42 │  812832030617   812778549167   0.01 │  524620   524564   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-fiat-core │  102.95   102.27   0.66 │  293004069057   291253075875   0.60 │  389749256155   389548806995   0.05 │  478212   478588  -0.08 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-hott │  321.19   318.20   0.94 │  871417923526   865712088235   0.66 │ 1424445469859  1424422772645   0.00 │  618636   618632   0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-bignums │   56.79    56.20   1.05 │  156732622906   155735492820   0.64 │  211205056619   211202753801   0.00 │  473628   473796  -0.04 │   0    0    nan │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by SkySkimmer** [comment]
I don't know. I wanted to wait for https://github.com/coq/coq/pull/13552 anyway since after it the universe_binders are empty much more often so the `domain` calls would be less significant.

**Comment by ppedrot** [comment]
In any case it can't really hurt.

**Pull request merged**
