### PR TITLE
Delay the evaluation of goal dependency in typeclass eauto.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
It's unclear we want that, it actually makes fiat-crypto slower.

**Comment by Janno** [comment]
Do you know what exactly is getting slower in fiat-crypto? I've had a look at the code changes in this MR and I am surprised to see a measurable regression from introducing laziness. Is it just from extra GC?

**Comment by ppedrot** [comment]
There is a small cost to laziness, in addition to more GC there is also a mutation involved. I guess fiat-crypto stresses this path because it calls typeclass resolution a lot on contexts that do need evaluating the dependency check.

**Comment by ppedrot** [comment]
Probably not worth it.

**Pull request closed without merging**
