### PR TITLE
[test-suite] Add test for #10182

### LINKED ISSUE #10182: anomaly "Not enough lambda/let's." on rewrite with lambda
#### Description of the problem

```coq
Require Import Coq.Arith.PeanoNat.
Goal forall A m pf1 pf2 (H : (fun _ : False => A) = (fun _ : False => A)),
match Nat.nlt_0_r m pf1 with end = match Nat.nlt_0_r m pf2 with end :> A.
Proof. intros. rewrite H.
(* Error: Anomaly "Not enough lambda/let's." *)
(* Please report at http://coq.inria.fr/bugs/. *)
```

Minimized from LambdaTamer 2009 export, which presumably compiled at the time... feel free to remove kind:regression if that seems like too much. On the other hand, this report may just be a duplicate of #3166 (from 2013) anyway...

#### Coq Version

8.9.0 and some 8.10+alpha compiled on Apr 8 2019

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #10182 ; likely solved by the case representation PR #13563

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by Alizter** [comment]
Can we make this an output test so we know it failed for the right reason?

**Comment by ejgallego** [comment]
> Can we make this an output test so we know it failed for the right reason?

Should we get an anomaly, Fail won't succeed I understand.

**Comment by Alizter** [comment]
> > Can we make this an output test so we know it failed for the right reason?
> 
> Should we get an anomaly, Fail won't succeed I understand.

Right, but if it fails for a different reason than the expected one in some future PR how will we tell otherwise?

**Comment by SkySkimmer** [comment]
We don't care about the reason, we just don't want an anomaly.

**Review by Alizter — APPROVED** [review]
Fair enough

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
