### PR TITLE
Substitute universes in types of proof-mode mutual fixpoints.

### LINKED ISSUE #14057: mutual fixpoints don't declare universes correctly
#### Description of the problem

```coq
Set Universe Polymorphism.
Axiom admit : forall {T}, T.
Axiom IsGlob@{u} : forall (n : nat) (A : Type@{u}), Type@{u+1}.
Fixpoint F {n : nat} {A : Type} {H : IsGlob n A} {struct n} : nat
with G {n : nat} {A} {H : IsGlob n A} {struct n} : nat.
Proof.
  1: pose (G n A).
  all: exact admit.
Defined.
(* Error: Undeclared universe: foo.14 (maybe a bugged tactic). *)
```
Replacing `{A}` with `{A : Type}` in the type of `G` causes the issue to go away.

Minimized from https://github.com/HoTT/HoTT/pull/1302 h/t @mikeshulman

#### Coq Version

8.12, also master c2ed2e395f2164ebbc550e70899c49af23e1ad1e

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #14057

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, cc @mattam82 @herbelin @ppedrot

**Comment by ejgallego** [comment]
@silene you want this in 8.14?

**Comment by silene** [comment]
Not really. It has been broken since 8.11. It can stay broken a bit longer.

**Comment by ejgallego** [comment]
@SkySkimmer should we wait for more reviews or you want to go ahead now?

**Comment by SkySkimmer** [comment]
Go

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
