### PR TITLE
Avoid using async proofs cache in output tests

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by herbelin** [comment]
Is it for consistency of results?

**Comment by ejgallego** [comment]
I'm not sure I understand why this PR is doing from the title description, why all these changes to the test files removing `Undo` etc...?

**Comment by SkySkimmer** [comment]
I was looking at the simple compiler PR and these commands were causing noise in the test suite results.

**Comment by ejgallego** [comment]
> I was looking at the simple compiler PR and these commands were causing noise in the test suite results.

We do support Undo et al in the newer versions of Flèche (once you have memoization these commands are fun)

It is actually pretty easy to update the simple compiler to support them if you want (still as of today, the simple compiler is a stripped down version of Flèche), so I'm happy to update the simple compiler to support those if you want.

Still there is this big difference of semantics between Flèche / simpler compiler at `Qed` time, so beware of that (stm typechecks in initial env, we do in env after last tactic)

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Coqc never memoized more than one state, and that is quite important for space performance.
Tests were run via coqtop, that memoizes all states, hence Undo/Reset are efficient.
Today tests are run with coqc, hence the stm option to force the meoization for interactive mode also in batch mode.

IMHO Undo & co are very easy to eliminate even in tests, so this PR counts as progress.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
No need to wait further, @coqbot merge now

**Pull request merged**
