### PR TITLE
[api] Two more missing deprecations.

### PR DESCRIPTION
**Pull request by ejgallego**
We missed two more constructor / record deprecation.

### CODE REVIEW

**Comment by ejgallego** [comment]
Also this is trivial enough that some good samaritan such as @ppedrot may want to take it.

**Review by ppedrot — APPROVED** [review]
Trivial, will merge promptly if no objection.

**Comment by ejgallego** [comment]
Merci !

**Comment by ejgallego** [comment]
Merci !

**Comment by silene** [comment]
Does that even work? As far as I know, OCaml ignores deprecation attributes on record fields, as can be seen on the following example:
```ocaml
type t = { x : int; [@ocaml.deprecated] }
let f () = let ({ x } as y) = { x = 1 } in x + y.x
```

**Comment by ejgallego** [comment]
Indeed, unfortunately for the record fields we may be out of luck, at least until 4.08. So that part of the PR is basically documentation.

**Pull request merged**
