### PR TITLE
Separate cache representation between CClosure and CBV

### PR DESCRIPTION
**Pull request by ppedrot**
This PR separates the kernel implementation for the term cache and its reuse in the out-of-kernel CBV reduction. This allows for further cleanups of static or unused data.

Interestingly this also seems to provide a slight speedup of reduction-sensitive code.
```
┌──────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬────────────────────┐
│                          │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │     mem faults     │
│                          │                         │                                       │                                       │                         │                    │
│             package_name │     NEW     OLD PDIFF   │            NEW            OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │  NEW  OLD  PDIFF   │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│   coq-mathcomp-odd-order │ 1413.05 1433.83 -1.45 % │  3936200361735  3991982030141 -1.40 % │  6657542410323  6652776875661 +0.07 % │ 1356092 1345092 +0.82 % │    4    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│              coq-unimath │ 1325.72 1336.06 -0.77 % │  3680931560751  3709374098474 -0.77 % │  6223627455366  6225637391659 -0.03 % │  985872  985580 +0.03 % │  348   21 +1557.14 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│                 coq-corn │ 1541.16 1550.72 -0.62 % │  4278355546708  4302072163965 -0.55 % │  6346360131011  6348694252677 -0.04 % │  817852  818160 -0.04 % │   44   44  +0.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│      coq-formal-topology │   57.82   58.12 -0.52 % │   158252480280   158862827706 -0.38 % │   239278904725   239331308650 -0.02 % │  477680  477528 +0.03 % │    1    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│               coq-sf-vfa │   47.25   47.49 -0.51 % │   131097445726   131399601231 -0.23 % │   209549446297   209686634872 -0.07 % │  535292  535256 +0.01 % │   28    5 +460.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│                 coq-hott │  340.96  342.64 -0.49 % │   943983791515   950635728409 -0.70 % │  1439975222178  1439870859678 +0.01 % │  666940  666980 -0.01 % │  352    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│         coq-math-classes │  249.17  250.39 -0.49 % │   686942585955   688630954925 -0.25 % │   899313771879   899466497392 -0.02 % │  522888  522212 +0.13 % │   64   84 -23.81 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│                coq-flocq │  592.77  595.04 -0.38 % │  1649059475849  1653074410465 -0.24 % │  2404513919593  2406543201466 -0.08 % │ 1764112 1764340 -0.01 % │  344   32 +975.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│                coq-sf-lf │   44.24   44.39 -0.34 % │   121932405828   122626918467 -0.57 % │   198885677984   199012338540 -0.06 % │  423264  423300 -0.01 % │  129    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│              coq-bignums │   98.77   99.08 -0.31 % │   273657555331   274535522530 -0.32 % │   393510509924   393892288229 -0.10 % │  534136  538748 -0.86 % │   86    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│ coq-mathcomp-real-closed │  188.30  188.68 -0.20 % │   523440151820   524391610432 -0.18 % │   789843292993   789976527848 -0.02 % │  826472  831292 -0.58 % │    0    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│                  coq-vst │ 1717.76 1720.14 -0.14 % │  4776374591324  4780909974134 -0.09 % │  6525488495716  6532166702347 -0.10 % │ 2217968 2228656 -0.48 % │  194  299 -35.12 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│            coq-fiat-core │  135.18  135.33 -0.11 % │   377999966645   377779853405 +0.06 % │   503923863163   503939929462 -0.00 % │  498120  498068 +0.01 % │  375   87 +331.03 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│               coq-sf-plf │   74.63   74.71 -0.11 % │   206396236504   206726735480 -0.16 % │   300637338941   300839115016 -0.07 % │  518504  517796 +0.14 % │   15    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│   coq-mathcomp-character │  293.80  294.00 -0.07 % │   815880104751   817338238136 -0.18 % │  1185191881805  1188810406387 -0.30 % │ 1059884 1121056 -5.46 % │    2    1 +100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│    coq-mathcomp-fingroup │   85.07   85.12 -0.06 % │   235223378961   235449271478 -0.10 % │   348178560496   348365967702 -0.05 % │  587972  586136 +0.31 % │   97    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│     coq-mathcomp-algebra │  205.79  205.88 -0.04 % │   570404737780   570928523892 -0.09 % │   798681235303   798758320160 -0.01 % │  641188  640976 +0.03 % │    3    8 -62.50 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│         coq-fiat-parsers │  721.09  721.25 -0.02 % │  1999945286551  2002628103041 -0.13 % │  3059005727085  3057044369804 +0.06 % │ 2885928 2893888 -0.28 % │   75  587 -87.22 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│       coq-mathcomp-field │  469.04  469.09 -0.01 % │  1304710899828  1305702280513 -0.08 % │  2126286498831  2126317357619 -0.00 % │  805448  803620 +0.23 % │    0   16 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│             coq-compcert │  891.81  891.82 -0.00 % │  2474262675171  2473064164018 +0.05 % │  3564477250562  3564731108132 -0.01 % │ 1338256 1355804 -1.29 % │  241  187 +28.88 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│           coq-coquelicot │  103.85  103.82 +0.03 % │   287231604244   286765317288 +0.16 % │   386312079100   386467983760 -0.04 % │  713136  713892 -0.11 % │  280   13 +2053.85 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│          coq-fiat-crypto │ 6316.50 6314.11 +0.04 % │ 17565493923648 17551920695226 +0.08 % │ 28902570487302 28910277315266 -0.03 % │ 2450616 2498820 -1.93 % │ 1456 1657 -12.13 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│    coq-mathcomp-solvable │  220.72  220.30 +0.19 % │   612335913431   611910070003 +0.07 % │   872563463204   873075353816 -0.06 % │  823900  830012 -0.74 % │   38  262 -85.50 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│   coq-mathcomp-ssreflect │   65.52   65.31 +0.32 % │   180002611438   179979782598 +0.01 % │   256309184417   256391588636 -0.03 % │  532240  532300 -0.01 % │    3    0   +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│                coq-color │  740.47  737.30 +0.43 % │  2052826863434  2041882358223 +0.54 % │  2469067663213  2469659508054 -0.02 % │ 1370332 1370692 -0.03 % │   30  243 -87.65 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼────────────────────┤
│               coq-geocoq │ 2870.61 2849.27 +0.75 % │  7979869322158  7920706343924 +0.75 % │ 12577347545415 12578877488088 -0.01 % │ 1289212 1286460 +0.21 % │  198  179 +10.61 % │
└──────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴────────────────────┘
```

### CODE REVIEW

**Review by maximedenes — DISMISSED** [review]
Shouldn't the checker be updated as well?

**Comment by maximedenes** [comment]
> Shouldn't the checker be updated as well?

Maybe it doesn't apply, I haven't checked. But I think any kernel change that is not ported to the checker should mention it.

**Comment by ppedrot** [comment]
There is no reason, the data structures are not shared.

**Comment by ppedrot** [comment]
The check could have performed the cleanup long ago, as it was not exporting its API and had static invariants of the uses. I guess I can backport the changes though.

**Comment by ppedrot** [comment]
Removing i_rels in the checker requires more work because it doesn't use the same environment representation.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
