### PR TITLE
Fix V7 syntax in refman.

### PR DESCRIPTION
**Pull request by Zimmi48**
By the way, I would like to ask about the status of undocumented `Show` commands.

If we believe the command index, the documented commands are:
```
Show.
Show Conjectures.
Show Existentials.
Show Intro.
Show Intros.
Show Ltac Profile.
Show Obligation Tactic.
Show Proof.
Show Script.
Show Universes.
```

Thus the undocumented ones are:
```
Show ident.
Show Goal.
Show Goal n.
Show Implicit Arguments.
Show Node.
Show Tree.
Show Match.
Show Thesis.
```

Which ones are still useful and should be documented? Which ones are obsolete and should get either fixed or deprecated?
Just so you know, I have been contemplating the idea of fixing `Show Tree.` (which does not work since 8.4).

### CODE REVIEW

**Comment by JasonGross** [comment]
I believe `Show Match` is used by company-coq (@cpitcla ?) and it would be nice if it could be improved to work on qualified names (like `Logic.eq`) and not just unqualified ones.

**Comment by maximedenes** [comment]
@Zimmi48 you should ask this question on coqdev, it should be addressed.

**Comment by ejgallego** [comment]
A few of them were disabled when the new proof engine happened as you can see by peeking in to `vernacentries.ml`

**Comment by cpitclaudel** [comment]
Yup, company-coq uses Show Match.

**Comment by psteckler** [comment]
`Show Match` is also available in Proof General and also in PG/xml, via a `Query` call, in both cases available via `C-c C-a C-m`.

**Pull request merged**
