### PR TITLE
Backport #8247 and #8394 to 8.9

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Comment by silene** [comment]
Sorry for the spam, I do not expect any review, that is just for continuous integration.

**Comment by Zimmi48** [comment]
@silene We could kill the `CODEOWNER` file in v8.9 to avoid this issue in the future. WDYT? But what I used to do to avoid opening PRs when backporting to v8.8, was just to push to a special `staging-v8.8` branch to GitLab so that GitLab CI would run. Travis and AppVeyor are mostly redundant nowadays so I would only run them before pushing in case of doubt.

**Comment by Zimmi48** [comment]
@silene If you want I can push a commit on top of this branch that would pin the tested versions of Elpi, HoTT and Ltac2 so that they pass CI (currently this is testing their master branch which contains breaking changes for commits that are only in master).
I can also push the commit fixing the Travis build by pinning OPAM to OPAM 1.2.

**Comment by Zimmi48** [comment]
See #8574.

**Pull request closed without merging**
