### PR TITLE
Fix Coqtail test directory.

### PR DESCRIPTION
**Pull request by whonore**
**Kind:** bug fix / infrastructure.

Fixes failing CI because the test directory was moved in https://github.com/whonore/Coqtail/pull/134.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Comment by jtcoolen** [comment]
@SkySkimmer Don't worry, there's a permission missing for the app to merge a pull request, we will correct this tomorrow.

**Comment by Zimmi48** [comment]
Since the very recent move to a GitHub App for @coqbot, the merge feature did not work anymore because of the branch protection rules for `master` (@coqbot was an admin of the Coq organization, so allowed to push, but the app @coqbot-app isn't). I've fixed this by adding @coqbot-app in the allowed pushers for `master`. In principle, that should solve it.

**Pull request merged**
