### PR TITLE
update elpi to version 1.2

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
I gave a quick look at dev/doc/docker but I could not find how where to go in order regenerate the docker image (IIRC it is manual). So please tell me, or take care of it.

**Comment by gares** [comment]
ci-failure on coq-elpi is due to the fact that the docker image is not updated (it still contains elpi 1.1.x and not 1.2.0)

**Comment by SkySkimmer** [comment]
You have to update the key in dockerfile and in the gitlab yml, then do a manual run with SKIP_DOCKER=false

**Comment by gares** [comment]
thanks!

**Comment by gares** [comment]
@coq/ci-maintainers the failure on nix was spurious (restarted now). AFAICT, this PR if ready.

**Review by SkySkimmer — APPROVED** [review]

**Comment by Zimmi48** [comment]
@gares Latest build of master 75c5264a with latest version of coq-elpi LPCIC/coq-elpi@7fd221b gives an error:

```
make[1]: Entering directory '/builds/coq/coq/_build_ci/elpi'
Using coq found in /builds/coq/coq/_install_ci/bin/, from COQBIN or PATH
Makefile:52: Makefile.coq.conf: No such file or directory
echo "let elpi_dir = \"/root/.opamcache/4.05.0/lib/elpi\";;" > src/coq_elpi_config.ml
camlp5 macro files not supported anymore, please port src/coq_elpi_vernacular_syntax.ml4 to coqpp
```

**Comment by gares** [comment]
I must have done something silly

**Comment by gares** [comment]
should be fixed now

**Pull request merged**
