### PR TITLE
Elpi 1.4.0

### PR DESCRIPTION
**Pull request by gares**
overlay: https://github.com/LPCIC/coq-elpi/pull/67

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@gares milestone for this?

**Comment by ejgallego** [comment]
[nitpicking: you may want to add `[docker] [ci] Upgrade to Elpi 1.4.0` to the commit message so readability of git shortlog is a bit better]

**Comment by gares** [comment]
I'm unsure about the milestone, but I want to release coq-elpi soonish for Coq 8.10

**Comment by ejgallego** [comment]
8.10 makes sense then, so the CI image there is updated.

**Review by ejgallego — CHANGES_REQUESTED** [review]
Please improve at least the second commit message [ideally both as indicated]

**Comment by gares** [comment]
done

**Comment by ejgallego** [comment]
Thanks!

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
