### PR TITLE
Call guard checking with evar handlers in higher layers

### LINKED ISSUE #18358: Anomaly raised by the Guarded command (kernel evar_handler encounters an evar)
In Coq v8.18, an anomaly triggered by a call to `Guarded` when coinduction hypothesis is used in an `assert`. 
Minimal example:

```
CoInductive P : nat -> Prop :=
  | Pintro : forall n, P 0 -> P 0 -> P (S n) -> P n.

Lemma P_any : forall n, P n.
Proof.
  cofix IH. intros.
  assert (H: P 0). { apply IH. }  Guarded. (*Guarded: anomaly*)
  apply Pintro. { apply H. } { apply H. } { apply IH. }
Qed. (*Guard checker happy *)
```

### LINKED ISSUE #18680: Assertion failed on kernel/constr.ml (Program Fixpoint sends evars to guard checker)
#### Description of the problem

The following file seems to break a kernel invariant.

File:
```
Set Universe Polymorphism.

Require Import Coq.Arith.PeanoNat.
Require Import Coq.Logic.JMeq.

Inductive narray {X : Type} : nat -> Type :=
    | Elt : X -> narray 0
    | Cons {c : nat} (x : X) (n : narray c) : narray (c + 1).

Lemma eqb_eq : forall x, Nat.eqb x x = true.
Proof.
  intros.
  induction x.
  - reflexivity.
  - simpl. apply IHx.
Qed.

Lemma sub_still_le : forall x y, 
  Nat.eqb x y = false -> x <= y -> x + 1 <= y.
Proof.
  intros x y NatEq xLey.
  induction xLey.
  - rewrite eqb_eq in NatEq. discriminate NatEq.
  - replace (x + 1) with (S x).
    * apply le_n_S. apply xLey.
    * rewrite Nat.add_comm. simpl. reflexivity.
Qed.

(* Returns the nth element of the array; this version works. *)
Program Fixpoint get 
   {X : Type} {sz : nat}
   (get_n : nat) (cpt : nat) (l : narray sz) : X := 
    match l with
    | Elt x => x
    | Cons x tl =>
      match Nat.eqb get_n cpt with 
      | true => x 
      | false =>
        get get_n (cpt + 1) tl
    end
  end.

(* Same than get, but carries additional proofs. *)
Program Fixpoint get' 
   {X : Type} {sz : nat}
   (get_n : nat)
   (Inv : get_n < sz) 
   (cpt : nat)
   (P : cpt <= get_n) 
   (l : narray sz) : X := 
    match l with
    | Elt x => x
    | Cons x tl =>
      match Nat.eqb get_n cpt with 
      | true => x 
      | false => 
        let CondFalse: Nat.eqb get_n cpt = false := _ in
        let P' : cpt + 1 <= get_n := 
          sub_still_le cpt get_n CondFalse P
        in
        get' get_n Inv (cpt + 1) P' tl
    end
  end.
```

The error: 

```
Anomaly "File "kernel/constr.ml", line 1478, characters 26-32: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

This error is raised on 8.18.0 & 8.19.0.

### LINKED ISSUE #18850: Coq 8.18 Program Definition bug (also interacts with Classes.SetoidClass in unexpected ways)
### Description of the problem

This is a two in one bug. In my reproducible example if you comment out the `Classes.SetoidClass` import you get an error:
```
Error: not found in table: core.JMeq.type
```

But if you leave the import you get another error
```
Error:
Anomaly
"File "kernel/constr.ml", line 1485, characters 26-32: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

Neither of those is good behavior afaik.

### Small Coq file to reproduce the bug

```coq
From Coq Require Import
  Fin
  Classes.SetoidClass. (* comment out for different error message *)

Notation fin := t.

Program Definition next_fin {n}: fin (S n) -> fin (S n) :=
  fix loop (f : fin (S n)) : fin (S n) :=
    match f with
    | F1 => F1
    | FS f' => match f' with
              | F1 => F1
              | FS _ => FS (loop f')
              end
    end.
```

### Version of Coq where this bug occurs

8.17 - master

### Last version of Coq where the bug did not occur

<= 8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #18358
Fix #18680
Fix #18850

Overlays:
- https://github.com/mattam82/Coq-Equations/pull/587

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by SkySkimmer** [comment]
IDK what made that equations test start failing, AFAICT this PR shouldn't change what happens since equations called search_guard without evar handler. The overlay to make it work again looks more correct than the previous code so not spending much time on figuring it out.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
