### PR TITLE
Aligning homogeneous map terminology in Context.mli to Smart terminology + heterogeneous map

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** cleanup

Following a [comment](https://github.com/coq/coq/pull/9317#pullrequestreview-199553442) of @ppedrot, we align the terminology for homogeneous map functions in `Context` to the `Smart` terminology already present in `List`, `Option`, ...

We also add `map_het` on contexts (to be used in #13445).

Not using `Smart` is deprecated. In a next step, the `_het` suffix of heteregeneous version could be to dropped.

This is at the limit of being overzealous though: the risk is that thinking to use the `Smart` versions whenever possible becomes less obvious from the moment the hetero- and homogeneous versions have the same name. We compensate this by recommending looking at the `Smart` versions in the documentation of the heterogeneous ones.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Didn't we decide against doing this when the first heterogeneous map was introduced so that maps would be smart by default?

**Comment by herbelin** [comment]
> Didn't we decide against doing this when the first heterogeneous map was introduced so that maps would be smart by default?

I have no information about a decision. The only information I saw was the [comment](https://github.com/coq/coq/pull/9317#pullrequestreview-199553442) by @ppedrot at #9317. If a decision was no, the PR can be closed!

**Comment by SkySkimmer** [comment]
Perhaps my memory got bitflipped.

**Comment by herbelin** [comment]
I was needing too more `map_het` functions and this is what guided me to that. But otherwise, the status quo is fine to me.

**Comment by SkySkimmer** [comment]
@ppedrot I leave this to you

**Comment by ppedrot** [comment]
I don't remember and don't have a strong opinion either...

**Comment by herbelin** [comment]
I'm myself not fully convinced that it is worth the burden. It seems that we would be going towards renouncing then??

**Comment by ppedrot** [comment]
@herbelin Your call.

**Comment by herbelin** [comment]
So closing (and I will add `map_het`s in another PR which needs them).

**Pull request closed without merging**
