### PR TITLE
Proof runcountable

### PR DESCRIPTION
**Pull request by VincentSe**
**Kind:** feature

This is a reopening of https://github.com/coq/coq/pull/8325, after a bad merge.

### CODE REVIEW

**Comment by VincentSe** [comment]
I implemented the smallest element in constructive epsilon and used FinFun.Bijective in the final statement of the theorem.

However it is difficult to completely replace enumeration by Bijective, as sometimes we want to have the inverse function in Sort Set.

**Comment by VincentSe** [comment]
I don't know why this pull request says  kernel/cClosure.ml is modified, this file does not show on my repo when I do git fetch upstream, git diff upstream/master HEAD --name-only

**Comment by SkySkimmer** [comment]
Because you're not based on the right commit.

**Comment by Zimmi48** [comment]
You should seriously try to use `git rebase` instead of `git merge`. You would avoid all the problems you've been having.

**Comment by VincentSe** [comment]
I did git rebase upstream/master, but then it complained about the previous deleted proofRuncountable branch.

Shall I re-do this pull request from scratch with another branch ? It is just 4 files to modify, might be easier than fixing git's history.

**Comment by Zimmi48** [comment]
I was in the process of answering you but well...

Fixing git history is not such a difficult thing.
Let's proceed step by step:
```
git remote -v # should show you upstream pointing to the official repo and origin pointing to your fork
git checkout master
git fetch upstream
git reset --hard upstream/master
git branch --set-upstream-to=upstream/master
...
```

**Comment by VincentSe** [comment]
Yes, sorry about this mess, I'll use rebase from now on. At my company rebase is forbidden, so I'm not used to it.

Now the pull request is Proof runcountable rebase #8888, is it assigned to the correct reviewer ?

**Pull request closed without merging**
