### PR TITLE
[options] New helper for creation of boolean options plus reference.

### PR DESCRIPTION
**Pull request by ejgallego**
This makes setting the option outside of the synchronized summary impossible.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>This makes setting the option outside of the synchronized summary impossible.

What does that mean? Why do we care?

**Comment by ejgallego** [comment]
> What does that mean? Why do we care?

As of today it doesn't mean a lot indeed so indeed I should be more clear about this being basically a cleanup. This is in fact part of a small refactoring trying to make group options to behave well [see the problems in #8666 .

Imagine we have `flag_foo = false`, then some code does: `flag_foo := true`. Now the `Summary` contains a different value for `foo`.

If that happens below the `Vernacentries.interp` freeze barrier, then the flag will be correctly saved upon, however, it that happens above, the change to `foo` will be lost as the summary will be reinstalled.

Thus, this API could provide a method for the upper layers to actually modify a setting properly, which is what I was thinking when I wrote that.

**Comment by SkySkimmer** [comment]
>Thus, this API could provide a method for the upper layers to actually modify a setting properly

The API only restricts how it may be set compared to the preexisting method, do you mean that it forces to use the proper method?

**Comment by ejgallego** [comment]
> The API only restricts how it may be set compared to the preexisting method, do you mean that it forces to use the proper method?

It is a step towards making the "proper method" work, as of today it forces you go to thru `Goptions` to set the value, however, `Goptions` still doesn't do the proper thing.

**Comment by ejgallego** [comment]
So indeed I agree I should tweak the commit message.

**Comment by ejgallego** [comment]
Umm, I think I want to think more on this one; maybe I should go further beyond and finish implementing proper handling of group options. It would be a lost of time if I have to change the interface again.

**Review by ppedrot — APPROVED** [review]
I am not sure this is the ideal API, but at least it looks better than what we have currently.

**Comment by herbelin** [comment]
I'm curious. What would typically be a more ideal API?

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
@herbelin You should be able to also modify the 'reference' if you are in the right context, i.e. once we get a pure API you would also get a `state -> bool -> state` function. Maybe this can be made forward-compatible by returning a record with only one field for now...

**Comment by herbelin** [comment]
>  You should be able to also modify the 'reference' if you are in the right context, i.e. once we get a pure API you would also get a `state -> bool -> state` function. Maybe this can be made forward-compatible by returning a record with only one field for now...

Yes, indeed, at some time, it should be that. What is unclear to me though is how to stepwise implement the transition. Threading the state of options in one go is maybe too much work, and we also have to give time to plugins for the translation. So, in the transitory period, we could maybe have the 3 variants:
- the current `declare_bool_option` (and variants) in deprecation mode
- the intermediate step done in this PR
- the fully-functional step with type `state -> bool -> state`

But, in the latter case, what shall be the definition of `state`? Will it be `state = { options : Goptions.option_state ; ... }` as you suggest, will it be `Goptions.option_state`, will it be `option_state = { printing_option_state : printing_option_state ; typeclass_option_state : typeclass_option_state ; ...}`, will it be `printing_option_state` selectively using a group of options depending on functions, will it be `'a Goptions.group_option_state` using a dynamic tag to enforce the `'a`?

I guess that in the transitory period, until everything is made functional, we shall need functions `save_state`/`get_state` or `save_option_state`/`get_option_state` to temporarily switch from the imperative to the functional view?

Is that what you have in mind?

**Comment by ppedrot** [comment]
I'd personally be in favour of merging this PR as-is. Other improvements can be done afterwards, but letting this PR bitrot is a no-no. Otherwise, we should close it. @ejgallego ?

**Comment by ejgallego** [comment]
I wouldn't say this PR will bitrot, IMHO it needs a further revision, unfortunately I've been quite busy so the slot for this fell back a bit behind.

**Comment by ejgallego** [comment]
Indeed no point in delaying this more; let's merge and we can improve more later.

**Pull request merged**
