### PR TITLE
Clarify the documentation for merging PRs with overlays

### PR DESCRIPTION
**Pull request by anton-trunov**
**Kind:** documentation.

This is an attempt at further clarifying the workflow for PRs with backwards compatible overlays.

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
I would formulate this in a more lax way such as "it might be a good idea to ask the PR author to remove the overlay information from the PR to get a fresh CI run and ensure that all the overlays have been merged".

Indeed, this is not usually seen as mandatory and might be a bit overkill when a PR has just one or two small overlays. We also want to avoid putting too many additional constraints on the contributing process. But of course, this is a very good practice and it can actually save the assignee a lot of time in the case of a PR with lots of overlays.

**Comment by anton-trunov** [comment]
@Zimmi48 Thanks, I incorporated your suggestion "as is".

>  We also want to avoid putting too many additional constraints on the contributing process.

Makes sense!
Sorry, one more question: is it OK for an assignee to push a commit removing the overlay information directly onto someone else's PR?

**Comment by Zimmi48** [comment]
> Sorry, one more question: is it OK for an assignee to push a commit removing the overlay information directly onto someone else's PR?

Yes. We consider that if an assignee becomes a co-author of a PR, the assignee should change. But (force-)pushing a rebase to solve conflicts, typo fixes, a fix to the test-suite, or removing the commit introducing overlays should all not be considered as "co-authoring". There are already a few notes on collaborating on a PR and on PR co-authoring but maybe this should be made even more explicit. Feel free to add this to this PR.

**Comment by anton-trunov** [comment]
@Zimmi48 I added a new commit with some more (I hope) clarification. Please have a look.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
I'll wait until tomorrow to merge in case anyone wants to add something.

**Pull request merged**
