### PR TITLE
Disallow evar definition on disallowed evars

### LINKED ISSUE #18804: Pattern variable unrecognised in match branch
### Description of the problem

In some correct positions, pattern variables are not available for the replacement term

### Small Coq file to reproduce the bug

```coq
Symbol t : unit.
Rewrite Rule t_rew :=
| match t with tt => @eq_refl ?A ?a end ==> @eq_refl ?A ?a.
```

### Version of Coq where this bug occurs

master

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by yannl35133**
Fixes / closes #18804

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]
Please add the test

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by yannl35133** [comment]
All the failures are because the test uses the old syntax for rewrite rules, so I don't think it's worth retesting everything for just that simple fix

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
