### PR TITLE
Hack an efficient typing rule for let-bindings.

### PR DESCRIPTION
**Pull request by ppedrot**
bench https://gitlab.com/coq/coq/-/jobs/900732089

### CODE REVIEW

**Comment by gares** [comment]
I think we tried that in matita... I'm very curious to see what it gives here.

**Comment by gares** [comment]
The old code was (also) "garbage collecting" let-in which don't contribute to the type, If I understand it right. Now you don't.

**Comment by ppedrot** [comment]
It shouldn't matter, because this flag is only used for type inferences that are never going to be exposed to the user. It will only appear in conversion problems.

**Comment by gares** [comment]
Sure, but even there you may end up with `let unused := t in ty` to be converted to `ty`. It's not very expensive to push let ins I guess, but if the term you typecheck is an ML term in ANF (a long list of letins not appearing in the type), then you will synthesize a large type for nothing (again, if I got your patch right).

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2574.15  2598.25  -0.93 │  7175292916047   7238757200250  -0.88 │ 12433817528829  12432988397300   0.01 │  728516   728480   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │  102.62   102.81  -0.18 │   292688127566    292879048648  -0.07 │   390161974100    389984696045   0.05 │  478888   479032  -0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  156.07   156.12  -0.03 │   432538065626    433509619920  -0.22 │   541288752512    540679040460   0.11 │  821292   820752   0.07 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │  520.04   519.99   0.01 │  1452981221325   1454890592115  -0.13 │  1955826885070   1955161086083   0.03 │  567656   565412   0.40 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  154.52   154.50   0.01 │   429982156066    429538111413   0.10 │   602259906787    602358661852  -0.02 │  707896   711120  -0.45 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  627.45   626.98   0.07 │  1756952510232   1756458953704   0.03 │  2696869479342   2697919135639  -0.04 │ 3242032  3242116  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-compcert │  636.56   635.30   0.20 │  1772158790014   1768202152189   0.22 │  2469975811648   2469259023157   0.03 │ 1047072  1047092  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  723.58   721.90   0.23 │  2008428894442   2004546269753   0.19 │  3090106934635   3088798385330   0.04 │  975636   982792  -0.73 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │  102.71   102.47   0.23 │   281742235707    281544399336   0.07 │   397784980055    397634720758   0.04 │  547760   547664   0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  138.39   138.06   0.24 │   383764609367    383186122160   0.15 │   499691373521    499689005504   0.00 │  548784   549052  -0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  506.76   505.53   0.24 │  1412885402409   1409788626416   0.22 │  1786418631837   1786691500658  -0.02 │ 1133408  1133456  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-perennial │ 5508.18  5494.66   0.25 │ 15299896197467  15262193476365   0.25 │ 23024193192785  23032457440056  -0.04 │ 3091444  3058408   1.08 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 5044.37  5030.86   0.27 │ 14014892951904  13980343873278   0.25 │ 24621407711428  24615019176788   0.03 │ 2389292  2410512  -0.88 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  798.36   796.17   0.28 │  2221493523178   2217946641004   0.16 │  3485094439495   3484829587797   0.01 │  981240   975780   0.56 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  224.87   224.16   0.32 │   621746526409    619339116927   0.39 │  1031230892670   1030974576099   0.02 │ 1027660  1027668  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  214.04   213.30   0.35 │   595258510108    593824600153   0.24 │   813170876493    813074570561   0.01 │  522544   522764  -0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   67.76    67.52   0.36 │   184896548745    184687366340   0.11 │   237185426930    236904000308   0.12 │  571928   568784   0.55 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   47.34    47.17   0.36 │   130932384568    130553726313   0.29 │   182064262062    182048127834   0.01 │  480924   481004  -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  344.13   342.57   0.46 │   967430770267    963498031009   0.41 │  1746235894082   1744418167947   0.10 │ 3499924  3499996  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1227.56  1221.91   0.46 │  3415510219293   3400181227524   0.45 │  4931677334920   4929726262951   0.04 │ 1095816  1111032  -1.37 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1465.51  1458.52   0.48 │  4079989589358   4064390547896   0.38 │  6180270508327   6183148542110  -0.05 │ 1028384  1026548   0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │   79.47    79.06   0.52 │   217573890571    217049828595   0.24 │   307107309370    307070676474   0.01 │  763812   764656  -0.11 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  169.43   168.52   0.54 │   471196359314    469117730088   0.44 │   669602804748    669501218815   0.02 │  661888   684640  -3.32 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1234.25  1226.86   0.60 │  3434615801982   3415683845604   0.55 │  4868463954292   4867188454667   0.03 │  901348   901312   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-hott │  328.92   326.86   0.63 │   893240378425    888590199108   0.52 │  1452129705802   1451566369570   0.04 │  609212   602568   1.10 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  222.96   221.45   0.68 │   620837900333    616559839882   0.69 │   949723654157    949732074791  -0.00 │  676164   676560  -0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   61.25    60.82   0.71 │   169305899167    168863456549   0.26 │   209887222668    209820885746   0.03 │  527024   527308  -0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 4003.69  3974.02   0.75 │ 11135143330684  11056622455353   0.71 │ 21383330514718  21382626957360   0.00 │ 1022860  1022720   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   56.98    56.54   0.78 │   156522258260    155609819253   0.59 │   210224972496    210163068998   0.03 │  474288   474248   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1051.72  1042.08   0.93 │  2927052485246   2904380064522   0.78 │  4664186915262   4664228530232  -0.00 │  978548   983180  -0.47 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-corn │ 1637.48  1621.81   0.97 │  4559006958742   4513696878476   1.00 │  6940302064161   6940466278469  -0.00 │  774880   774792   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   51.26    50.63   1.24 │   139216723788    138929167985   0.21 │   178347548551    178261748934   0.05 │  509596   506996   0.51 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
~~~

**Comment by ppedrot** [comment]
Not worth it.

**Pull request closed without merging**
