### PR TITLE
Remove from CircleCI builds that are already taken care of by Travis.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

Should save some build time now that CircleCI is overloaded.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Review by ejgallego — APPROVED** [review]

**Comment by maximedenes** [comment]
Strange failure in CircleCI, it seems.

**Comment by Zimmi48** [comment]
Indeed, for some strange reason, `configure` detected the presence of lablgtk and wants to build CoqIDE. Will look into this.

**Comment by SkySkimmer** [comment]
It's getting the cache. I guess getting cache from previous config.yml to speed startup when it changes was a mistake.

**Comment by Zimmi48** [comment]
Oh OK, this was my guess as well, but I was thinking that the cache was checking the hash of `config.yml`. Anyways, it should be easy to fix with `./configure -coqide no` even if we don't want to change the way the cache is selected...

**Comment by ejgallego** [comment]
As I suggested in https://github.com/coq/coq/pull/6636#issuecomment-366529578 , we could extend this PR to take a few extra jobs back to Travis. WDYT?

**Comment by SkySkimmer** [comment]
We could also ask people not to use circle for their own branches, leaving it to PRs.

**Comment by ejgallego** [comment]
> We could also ask people not to use circle for their own branches, leaving it to PRs.

That's another option, however I don't this would have helped the load a lot.

**Comment by Zimmi48** [comment]
> That's another option, however I don't think this would have helped the load a lot.

It would at least help someone like me canceling duplicate builds or builds not deemed useful. The current situation is pretty terrible: we are forced to share our build time with forks but we can't control what forks do with it. The situation was pretty bad because of this during the 8.7.2 release and I regret not having considered at that time kicking people out of the Coq organization to reduce the build time sharing.

**Comment by maximedenes** [comment]
I would be in favor of trying it too.

**Comment by Zimmi48** [comment]
Trying to ask people to stop using CircleCI on their forks or trying to kick people out of the organization?

**Comment by maximedenes** [comment]
Asking people to stop using CircleCI seems like the simplest option to me. At least as a first attempt.

**Comment by Zimmi48** [comment]
OK, the list of people using it is quite short: @ejgallego @gares @SkySkimmer @psteckler @maximedenes and myself. So please people, disable CircleCI on your forks. Let's go back to using Travis to test our branches.

**Comment by maximedenes** [comment]
done

**Comment by SkySkimmer** [comment]
I disabled it earlier today, do I still show as using it?

Gaëtan Gilbert

**Comment by Zimmi48** [comment]
> I disabled it earlier today, do I still show as using it?

I have no way of checking if you've disabled it. I just made this list from what I saw in the longest queue (100-hour wait) of last week builds. I don't know if I'm missing some privileges on CircleCI which would allow me to see who in the organization are building their forks on CircleCI.

**Comment by ejgallego** [comment]
Ok will disable my CircleCI and see how things go.

**Comment by gares** [comment]
I've just checked and on my fork circleci is disabled (it has always been I guess)

**Comment by Zimmi48** [comment]
@gares But you have builds pending nonetheless: https://circleci.com/gh/gares/workflows/coq
Where did you check? That's where I would go: https://circleci.com/gh/gares/coq/edit

**Comment by gares** [comment]
thanks, I stopped building Coq there (I was looking in the project setting's app tab, and there I did see only travis)

**Comment by maximedenes** [comment]
@Zimmi48 Should I merge this, finally?

**Comment by Zimmi48** [comment]
Yes, it should still be merged. However, it now conflicts. Will rebase.

**Comment by Zimmi48** [comment]
Done. Let's still wait for the tests to pass before merging.

**Comment by ejgallego** [comment]
I'm afraid to say that even after disabling contributor builds circle remains very overloaded and it doesn't seem to get better. So after this PR is merged we should consider moving some more jobs to Travis.

I am much afraid that the Circle scheduling strategy is really really painful for development, as it doesn't really give any priority to older PRs versus new ones, and incoming ones can indefinitely delay older ones, which obviously cannot sustain any kind of development rhythm.

Just for that reason, I hope Coq can move from Circle sooner than later.

**Pull request merged**
