### PR TITLE
[api] Move reduction modules to `tactics`

### PR DESCRIPTION
**Pull request by ejgallego**
These modules do actually belong there.

We have to slightly reorganize printers, removing a couple of
duplicated ones in the way.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Why not.

**Comment by ejgallego** [comment]
Overlay at: https://github.com/mattam82/Coq-Equations/pull/156

**Comment by ejgallego** [comment]
Dropping the overlay as it is backward compatible.

**Comment by ejgallego** [comment]
Ping!

**Review by herbelin — APPROVED** [review]
Why not indeed.

**Comment by maximedenes** [comment]
> fixing thus the open bug about it

Do you have a pointer?

**Comment by ejgallego** [comment]
> Do you have a pointer?

#8240

**Comment by ejgallego** [comment]
But fixing that bug will require 3 PR at least

**Comment by ejgallego** [comment]
A nasty one.

**Comment by ejgallego** [comment]
Needs assignee.

**Comment by ppedrot** [comment]
Last round of comments before I merge.

**Comment by ejgallego** [comment]
Ping @ppedrot

**Comment by ejgallego** [comment]
Merci!

**Pull request merged**
