### PR TITLE
[coqtop] Tweak API to avoid abstraction breakage.

### PR DESCRIPTION
**Pull request by ejgallego**
We provide a principled mechanism to mask a particular feeder, and
modify the feeder API so it users can name them.

This allows to clean up the use of different feeders in `coqtop`, in
particular it avoids having to leak feeder ids to miscellaneous
subroutines.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ok, this is ready for review and if appropriate, merge; should solve the issue with #8686

**Review by gares — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]
The new API does look better.

**Comment by ejgallego** [comment]
@ppedrot you assigned / unassigned ? Does that mean you prefer someone else to be the assignee?

**Comment by ppedrot** [comment]
I deassigned because I realized that I would have to submit a PR to pidetop and/or signal the mergeability of the latter, and it turns out it would be much faster if @gares perfoms all of this himself.

**Comment by ejgallego** [comment]
There already is a pr for pidetop

**Comment by ppedrot** [comment]
Yeah but commenting there means creating an account on bitbucket, so it looks easier to leave @gares handle this PR.

**Comment by ejgallego** [comment]
> Yeah but commenting there means creating an account on bitbucket, so it looks easier to leave @gares handle this PR.

Ok, @gares this is on your hands.

**Comment by ejgallego** [comment]
Closed in favor of #8950 . IMHO the design of the feedback system needs a bit more thinking including how to handle initial feedback for toplevel plugins.

**Pull request closed without merging**
