### PR TITLE
Pass more complete cstr in Rewrite.transitivity strategy

### LINKED ISSUE #15568: rewrite_strat regression in 8.15
#### Description of the problem

The following example demonstrates a problem with `rewrite_strat` which does not arise in 8.13 and 8.14. There seem to be some weird interplay with type class search: removing either or both of the `Reflexive` and `Transitive` instances also fixes the problem.

```coq
Require Import Coq.ZArith.BinInt.
Require Import Coq.Classes.RelationClasses.

Axiom mod_mod : forall a b : Z, Z.modulo (Z.modulo b a) a = Z.modulo b a.

#[global] Hint Rewrite Z.add_0_r mod_mod : bu.

Definition modEq (d:Z) := fun (a b :Z)=> Z.modulo a d = Z.modulo b d.

#[global] Instance modEqR (d:Z): Reflexive  (modEq d). Admitted.
#[global] Instance modEqT (d:Z): Transitive (modEq d). Admitted.

Goal forall d a e, Z.modulo (Z.modulo a d + 0) d = e.
intros.
Fail rewrite_strat try (bottomup (hints bu)). (* Should not fail. *)
(*
Error: Illegal application: 
The term "modEqT" of type "forall d : Z, Transitive (modEq d)"
cannot be applied to the terms
 "?d" : "Z"
 "((Zmodd d a + 0) mod d)%Z" : "Z"
 "(Zmodd d a mod d)%Z" : "Z"
 "(a mod d)%Z" : "Z"
 "reflexive_proper Z.modulo (Zmodd d a + 0)%Z (Zmodd d a) (Z.add_0_r (Zmodd d a)) d d (eq_proper_proxy d)"
   : "modEq ?d ((Zmodd d a + 0) mod d) (Zmodd d a mod d)"
 "Zmodd_mod d a" : "(Zmodd d a mod d)%Z = (a mod d)%Z"
The 6th term has type "(Zmodd d a mod d)%Z = (a mod d)%Z" which should be coercible to
 "modEq ?d (Zmodd d a mod d) (a mod d)".
*)
rewrite Z.add_0_r; rewrite mod_mod. (* Produces the expected result. *)
```

/cc @Janno

#### Coq Version

8.15

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15568 (on v8.15)
Not sure if this fixes anything on master.

### CODE REVIEW

**Comment by ppedrot** [comment]
Is this targetting master then?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer ping

**Comment by SkySkimmer** [comment]
>Is this targetting master then?

yes

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
