### PR TITLE
CI: Put "v8.16" in CACHEKEY

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should keep the image from getting cleaned up in the future.

### CODE REVIEW

**Comment by ppedrot** [comment]
The docker job doesn't seem to have run?

**Comment by Zimmi48** [comment]
Indeed, Docker image creation is only triggered automatically by the bot when the Dockerfile itself has been modified. So, in this case, I guess it should be triggered manually on GitLab by setting SKIP_DOCKER to false.

**Comment by SkySkimmer** [comment]
rerunning

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
