### PR TITLE
Fix printing of `functional induction`

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
Testcase:
```
Require Import FunInd.
Ltac u a b := functional induction a as b.
Print u.
(* used to be Ltac u a b := functional induction a  as <simple_intropattern> *)
```

### CODE REVIEW

**Comment by ejgallego** [comment]
@LasseBlaauwbroek now that you are doing all this, I guess you have some needs to instrument plugins as they are loaded. SerAPI has been doing this for a while, but it is a bit cumbersome to maintain. I'd be nice if we implement a more principled setup.

**Comment by ejgallego** [comment]
[Moreover we may need to be sure instrumentations compose, which I bet is not the case today]

**Comment by LasseBlaauwbroek** [comment]
I'm not sure what you mean exactly by 'instrument plugins'. For ssreflect I do have some hacky setup to load an additional plugin when ssreflect gets loaded. Is that what you mean?
https://github.com/coq-tactician/coq-tactician/blob/3694246006584c572707247f4af38ae5ccf888af/src/ltacrecord.ml#L197-L204

**Comment by ejgallego** [comment]
> I'm not sure what you mean exactly by 'instrument plugins'. For ssreflect I do have some hacky setup to load an additional plugin when ssreflect gets loaded. Is that what you mean?

I mean two things:
- instrumenting the loader to load additional instrumentation plugins; this can be done in a principled way already, see https://github.com/ejgallego/coq-serapi/blob/v8.16/sertop/sertop_loader.ml
- making sure that a plugin instrumentation is complete w.r.t. all the `Genarg` extension points added by a plugin. This is hard to do today, an error prone, see https://github.com/ejgallego/coq-serapi/issues/82

**Comment by LasseBlaauwbroek** [comment]
- Yes, doing this in a pricipled way would be nice. But `Mltop.set_top` does not look like something that I should be calling from a plugin :-) (Correct me if I'm wrong.) But it would indeed be great if I could get some kind of callback when a plugin gets loaded.
- Having better `Genarg` support would be great, but it is not clear to me how this should be done. Currently I have some rather cumbersome files that deal with generic arguments... I'm not sure if you have any ideas on doing this automatically in a generic way?
https://github.com/coq-tactician/coq-tactician/blob/coq8.11/src/map_all_the_witnesses.ml
https://github.com/coq-tactician/coq-tactician/blob/coq8.11/src/map_ssr_witnesses.ml

**Review by Matafou — APPROVED** [review]
AFAICT this looks good to me.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
