### PR TITLE
Remove nondeterministic tests

### LINKED ISSUE #5982: bugs/closed/4366.v is non-deterministic
[`bugs/closed/4366.v`](https://github.com/coq/coq/tree/master/test-suite/bugs/closed/4366.v) failed on a merge commit [on Travis](https://travis-ci.org/coq/coq/jobs/233112145#L5193) but didn't afterwards.

#### Failure log (edit to complete)

- On Travis on 2017-05-17.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #5982 #7388 #7483 #9497

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
Barring any comment, I'm intending to merge this next Monday.

**Comment by ejgallego** [comment]
cc @JasonGross

**Review by JasonGross — APPROVED** [review]
Sure, I will not block this.  I would still like to see a version of `Timeout` that counts CPU cycles or something, and is effectively platform independent.

**Comment by Zimmi48** [comment]
@JasonGross This is what `test-suite/complexity` is supposed to do. Have you looked into it?

**Pull request merged**
