### PR TITLE
closing bug #4250

### PR DESCRIPTION
**Pull request by forestjulien**
Fix for [bug 4250](https://coq.inria.fr/bugs/show_bug.cgi?id=4250).

### CODE REVIEW

**Comment by JasonGross** [comment]
Why was this merged with a failing travis?  The failure of fiat-crypto on this is a legitimate bug, now reported as [bug #5618](https://coq.inria.fr/bugs/show_bug.cgi?id=5618).

**Comment by maximedenes** [comment]
@JasonGross My bad, I'm so used to seeing fiat-crypto timeout that I bypassed it by mistake. @forestjulien   @Matafou do you see how to fix the bug? If not, I'll revert while we sort things out.

**Comment by JasonGross** [comment]
Yeah, sorry that fiat-crypto is so close to the timing limit.  I've dropped the two slowest files from the `lite` target, hopefully that should help a bit.

**Comment by ejgallego** [comment]
Unfortunately GitHub doesn't allow to reopen merged Pull Request, a new PR for this will have to be reopened.

**Comment by forestjulien** [comment]
I'll try to find the problem.

**Comment by forestjulien** [comment]
Should be solve by PR 843

**Pull request merged**
