### PR TITLE
CI: VST uses master branch

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlay https://github.com/PrincetonUniversity/VST/pull/510 (to be merged before this PR)

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by SkySkimmer** [comment]
@JasonGross that doesn't look right

**Comment by ejgallego** [comment]
@SkySkimmer @Zimmi48 IMVHO this is a good example of the problems that high latency in CI may cause, just noting this one in case we do a writeup of the CI.

**Comment by JasonGross** [comment]
@SkySkimmer The minimizer is set up to minimize a single source against two versions of Coq.  Here you have two different versions of the CI against one version of Coq.  What were you hoping for?

**Comment by SkySkimmer** [comment]
@JasonGross I see.
Is there a way to run the minimizer against the success with 8.13 at https://gitlab.com/coq/coq/-/jobs/1509687999 ?

**Comment by JasonGross** [comment]
@SkySkimmer the easiest way to do that is to rebase this PR on that commit, or else open a new PR with that commit as the base one.  If you want to do it without rebasing, that's doable, but quite painful; you basically need to be coqbot and make a branch on the minimizer repo with the relevant files filled out.

**Comment by JasonGross** [comment]
Also, if that job isn't from master, you'll also need to target the PR to whatever branch that job is on (and the branch should be on coq/coq at least long enough for the minimizer to run)

**Comment by SkySkimmer** [comment]
Looks like VST isn't compatible with the fix to #13413, I will PR

**Comment by SkySkimmer** [comment]
Ready

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
@coqbot: merge

**Pull request merged**
