### PR TITLE
Fix #16288: wrongly self-referencing extraction of primitive projections in functors

### LINKED ISSUE #16288: Extraction generates invalid code for primitive records in functors
#### Description of the problem

```coq
Module Type Nop. End Nop.
Module Empty. End Empty.
Module M (N : Nop).
  Local Set Primitive Projections.
  Record M_t_NonEmpty elt := { M_m :> list elt }.
End M.
Module M' := M Empty.
Require Import Coq.extraction.Extraction.
Require Import Coq.extraction.ExtrOcamlBasic.
Extraction Language OCaml.
Recursive Extraction M'.
(*
module type Nop =
 sig
 end

module Empty =
 struct
 end

module M =
 functor (N:Nop) ->
 struct
  type 'elt coq_M_t_NonEmpty = 'elt list
    (* singleton inductive, whose constructor was Build_M_t_NonEmpty *)

  (** val coq_M_m : 'a1 coq_M_t_NonEmpty -> 'a1 list **)

  let coq_M_m =
    coq_M_m
 end

module M' = M(Empty)

*)
Extraction TestCompile M'.
(* Error: Unbound value coq_M_m *)
```
#### Coq Version

8.14.0

### PR DESCRIPTION
**Pull request by herbelin**
Fixes #16288 (usual problem of imperative tables not being updated in functors).

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
The failure in itauto is because the PR now extracts the constant form of a primitive projection only if the Coq code refers to it. Previously, a projection in the primitive form was elaborated in the projection in constant form, so, even if the Coq code referred only to the primitive form (`Proj`), the constant form (`Const`) was inferred detected as used and therefore extracted. Example:
```coq
Set Primitive Projections.
Module Import A.
Record t := {a:bool;b:bool}.
End A.
Definition c x := x.(a).
Require Import Extraction.
Recursive Extraction c.
```
- before:
  ```ocaml
  type bool = | True | False
  module A = struct type t = { a : bool; b : bool } (** val a : t -> bool **) let a t0 = t0.a end
  (** val c : A.t -> bool **) let c x = x.A.a
  ```
- after:
  ```ocaml
  type bool = | True | False
  module A = struct type t = { a : bool; b : bool } end
  (** val c : A.t -> bool **) let c x = x.A.a
  ```
@coq/extraction-maintainers: that would probably not be too much a problem to say that when a projection in primitive form is used, we effectively extract the projection in constant form (even if strictly speaking not needed). In case you have an opinion, would I implement this for optimal compatibility, or do you think we can as well renounce to it (then, third-party developments mixing extracted Coq code with private OCaml code, such as itauto, will have to use in OCaml the `x.a` notation rather than the applicative notation `a x`)?

**Comment by SkySkimmer** [comment]
I think the new behaviour is correct, it means that if using the constant form is desired then the user must say `Extraction a` instead of getting t by side effect extracting something that does not use it.

**Comment by herbelin** [comment]
I should also have said that the new behavior creates a difference between "primitive" and non "primitive" projections, which maybe is weakening the flexibility in using or not the "Primitive Projections" flag.

**Comment by herbelin** [comment]
After more digging, I could summarize the situation in issue #17337. In particular, prior to this PR, there is a difference of behavior wrt inlining between being at toplevel (where inlined functions are pruned) or in a module (where inlined functions, especially projections, are not pruned). I made #17341 to address this and this now shows the itauto failure even without this PR. In particular, I'm now leaning towards changing itauto.

**Comment by herbelin** [comment]
Rerunning CI, since it is a long time ago

@coqbot run full ci

**Comment by herbelin** [comment]
This is an old PR looking for an assigne. @ppedrot, would you have some time by chance?

**Comment by ppedrot** [comment]
This is a bit outside of my expertise area... There are weird spec considerations as well. I'll see if I can grok this.

**Review by ppedrot — APPROVED** [review]
I'm a bit puzzled about why you simply don't write the miniML matching directly instead of getting it by the composition of fake_match_projection + extract_term, but I guess it's a bit more uniform this way.

**Comment by ppedrot** [comment]
Merging soon if nobody complains.

**Comment by herbelin** [comment]
Thanks!

**Pull request merged**
