### PR TITLE
Have the coq_makefile timing test-suite print more

### PR DESCRIPTION
**Pull request by JasonGross**
This should help debug things like
https://github.com/coq/coq/issues/5675#issuecomment-345324924 if they
ever show up again.

### CODE REVIEW

**Comment by Zimmi48** [comment]
I'm not at all an expert of the test-suite but it is my understanding that by default running the test-suite doesn't print any output. I'm not really sure but there might be a way to change this with a `VERBOSE` flag or such. So you might want to activate this `VERBOSE` flag (if it exists) on AppVeyor and Travis. On AppVeyor in particular, rather than printing to standard output, another solution would be to generate a debug artifact...

**Comment by JasonGross** [comment]
I believe Travis and AppVeyor cat the logs of failing tests.   This file already emitted output on stdout, and I could see that in the failing log.

**Comment by Zimmi48** [comment]
Ah OK cool

**Comment by maximedenes** [comment]
Strange build failure, restarting.

**Pull request merged**
