### PR TITLE
Fixing encoding in coqdoc output tests.

### PR DESCRIPTION
**Pull request by herbelin**
Hi, this is a trivial fix of the encoding in coqdoc output tests. Could be pushed without further delays.

### CODE REVIEW

**Comment by maximedenes** [comment]
This breaks the test suite it seems...

**Comment by gares** [comment]
Indeed the output is different ;-)
```
--- links.html.out	2017-11-08 10:41:09.126023781 +0000

+++ Coqdoc.links.html	2017-11-08 10:53:26.712597607 +0000

@@ -2,7 +2,7 @@

 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

 <html xmlns="http://www.w3.org/1999/xhtml">

 <head>

-<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

+<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

 <link href="coqdoc.css" rel="stylesheet" type="text/css" />

 <title>Coqdoc.links</title>

 </head>
```

**Comment by herbelin** [comment]
I updated the test-suite files.

The file links.v was using utf-8 characters so the patch was needed at least to test this file in a way which renders it properly. For the other files, it is not completely without effect since it makes that symbols like => and forall are respectively displayed ⇒ and ∀.
    
Maybe tests with iso-8859-1 or test without a charset option should be kept (for files with no non purely 7-bit ASCII characters). But no time for it now.

**Comment by Zimmi48** [comment]
> Maybe tests with iso-8859-1 or test without a charset option should be kept (for files with no non purely 7-bit ASCII characters). But no time for it now.

You can always open a new issue as a to-do for the future.

**Comment by maximedenes** [comment]
It seems there were some unrelated failure. Trying to rebuild.

**Pull request merged**
