### PR TITLE
[pp] Fix bugs 5651 [incorrect thunk in pretty printer]

### PR DESCRIPTION
**Pull request by ejgallego**
Fix bug introduced by a Haskell programmer.

### CODE REVIEW

**Comment by ejgallego** [comment]
This is an important bugfix that should be applied to 8.7.

**Comment by silene** [comment]
Do we even care? If I understand correctly, this has been broken for several months and nobody noticed the change. Can't we just remove this superfluous exception handling?

**Comment by ejgallego** [comment]
It is not clear there was no problem because of this, for instance @JasonGross reported some missing outputs some times. IMO no harm in applying this change until a deeper restructuring happens.

**Comment by JasonGross** [comment]
Is this related to the silent failure of coqchk on HoTT?

**Comment by ejgallego** [comment]
> Is this related to the silent failure of coqchk on HoTT?

Not likely, but you never know. BTW, have you submitted a bug for that?

**Comment by JasonGross** [comment]
[Bug #5587](https://coq.inria.fr/bugs/show_bug.cgi?id=5587) - it's even assigned to you, @ejgallego

**Comment by ejgallego** [comment]
Ok, thanks, indeed sorry it is a bit low in my bugzilla query.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
I stumbled upon that code by accident (I wanted to mix a Format.formatter printing infrastructure with Coq's std_ppcmds and that function had an interesting type).  So I did see no bug.

I've no idea it if is useful, but the code before @ejgallego 's clean up had it... hence my report.

**Comment by ejgallego** [comment]
Your report is 100% correct @gares, thanks.

**Comment by maximedenes** [comment]
Shouldn't this be part of the 8.7 milestone? Or was the change that introduced the problem in 8.8 only?

**Pull request merged**
