### PR TITLE
Properly implement local references in Summary.

### LINKED ISSUE #13777: Summary.Local broken
~Since 8.12, due to https://github.com/coq/coq/pull/11264,~ one cannot use the Summary.Local API to create a piece of state which is not sent to a worker.

### PR DESCRIPTION
**Pull request by ppedrot**
Fixes #13777.

### CODE REVIEW

**Comment by gares** [comment]
Thanks!

**Review by gares — APPROVED** [review]

**Comment by ejgallego** [comment]
Umm, is the documentation of this module correct? I don't see anything that prevents the state being sent to a worker.

**Comment by SkySkimmer** [comment]
Can we get a test for this? Even if it needs a misc/ test with a plugin doing silly things (considering the lack of users of this API)

**Comment by gares** [comment]
Well, I discovered the bug in Coq-Elpi... I can push a commit using the updated API there ( I have a test there, see https://github.com/LPCIC/coq-elpi/commit/f2c9b184235660bc3398421a7668fc934a697c5c ).

Otherwise I can craft a plugin and do the same kind of test here.

**Comment by gares** [comment]
@SkySkimmer there you have it

**Comment by SkySkimmer** [comment]
cool

**Comment by gares** [comment]
test-suite completed
@coqbot merge now

**Pull request merged**
