### PR TITLE
When resetting edit_at after error, print error before changing state

### LINKED ISSUE #16745: error in error printer in coqtop interactive mode
~~~coq
Class Def (x:=0) := def : bool.
~~~
~~~
Error: <in exception printer>: Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.
<original exception>: Uncaught exception Type_errors.TypeError(_, _).
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16745

### CODE REVIEW

**Review by JasonGross — APPROVED** [review]
Is the policy that minor bugfixes don't deserve changelog "fixed" entries?

**Review by gares — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Assignee?

**Review by ejgallego — DISMISSED** [review]
This seems like the wrong fix to me, if the error needs an enviroment to be printed properly, it should put it in the exception, as many other errors do.

**Comment by SkySkimmer** [comment]
>as many other errors do.

What error puts the nametab in the exception?

**Comment by ejgallego** [comment]
> What error puts the nametab in the exception?

Oh damn, this indeed fails at `Nametab.shortest_qualid_of_global` :/ I though this was coming from `Environ`.

We should really work on making the printer functional.

So we can do this hack, try to do the proper fix (passing the nametab), or use a bit more principled approach which is to wrap the exception in their `sid` and have the top-level handler set the state properly (this is what serapi / jscoq / coq-lsp) do.

I guess you will choose option 1 right @SkySkimmer ?

**Comment by SkySkimmer** [comment]
Is there a correct sid for this?

**Comment by ejgallego** [comment]
> Is there a correct sid for this?

Indeed what I have been using is the `sid` where the exception was raised, but you got a point that maybe there is not correct `sid` if the nametab for example is extended by the command interpretation.

**Comment by ejgallego** [comment]
The hack likely works because the nametab is left in a limbo state and the printing can work. 

Indeed, I now remember I took care in coq-lsp to print the errors just after they happen due to stuff like this.

**Review by gares — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
