### PR TITLE
Use the Evarutil cache for Class_tactics.evar_dependencies.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/906234067.

**Comment by ppedrot** [comment]
Let's try a full-bedrock2 bench: https://gitlab.com/coq/coq/-/jobs/910294473.

**Comment by ppedrot** [comment]
Bedrock2 bench: https://gitlab.com/coq/coq/-/jobs/949000637.

**Comment by SkySkimmer** [comment]
Some small effect or noise?
Code change is simple so we can merge either way.

**Comment by ppedrot** [comment]
I believe it does have a small effect. Adding a cache cannot hurt, so I'd favour merging anyways.

**Comment by ppedrot** [comment]
@SkySkimmer would you assign?

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
