### PR TITLE
Don't use raw evarconv in ltac2 quotation

### LINKED ISSUE #15681: ill-typed `constr:(...)` in Ltac2 sometimes results in anomaly instead of typing error
When I try to build an ill-typed constr in Ltac2, I usually get a typing error. For instance,

```coq
Require Import Ltac2.Ltac2.

Definition foo{E: Type}(f: E -> E): nat := 0.

Ltac2 feed_one_to_foo () := constr:(foo 1).

Fail Ltac2 Eval feed_one_to_foo ().
```

results in

```
The command has indeed failed with message:
The term "1" has type "nat" while it is expected to have type "?E -> ?E".
```

which is very useful to debug my tactics.
However, if I do

```coq
Ltac2 feed_constr_to_foo(x: constr) := constr:(foo $x).

Ltac2 Eval feed_constr_to_foo constr:(fun (a: nat) => a + 1).  (* succeeds *)

Ltac2 Eval feed_constr_to_foo constr:(1).
```

I get

```
Error: Anomaly "Uncaught exception Evarconv.UnableToUnify(_, 1)."
Please report at http://coq.inria.fr/bugs/.
```

Desired behavior: It should also print a typing error like above.

Coq version: 8.15-rc1

/cc @ppedrot

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15681

Not sure if it's better to coerce or convert, I chose to coerce (see test).

EDIT: ended up converting as according to the doc

### CODE REVIEW

**Comment by ppedrot** [comment]
I think that converting is better than coercing, because the latter can be obtained from the former by adding a type ascription. The converse is not possible so you'll lose expressivity (and efficiency).

**Review by ppedrot — CHANGES_REQUESTED** [review]
This is a formal RFC to use conversion rather than coercion.

**Comment by SkySkimmer** [comment]
>I think that converting is better than coercing, because the latter can be obtained from the former by adding a type ascription. 

IMO the behaviour with coercion is more intuitive, we're writing in gallina where everything is expected to be coerced as needed. Also if you want coercion from conversion you'll need something like `($x : type of $x) : target type` which seems quite strange.
I don't think we have a lot of efficiency issues with coercions, if someone has a sufficiently bad case they can still use Unsafe to build their terms.

**Comment by ppedrot** [comment]
If you insist. But then this needs a changelog.

**Comment by SkySkimmer** [comment]
Actually the doc says
~~~rst
In a Coq term, writing :g:`$x` is semantically equivalent to
:g:`ltac2:(Control.refine (fun () => x))`, up to re-typechecking. It allows to
insert in a concise way an Ltac2 variable of type :n:`constr` into a Coq term.
~~~
which doesn't coerce. Should I keep coercing and adapt the doc? What does "up to re-typechecking" mean?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
> What does "up to re-typechecking" mean?

That means that the `$x` syntax trusts that the term is well-typed, whereas refine does not. That is, it uses retyping rather than typing.

You can adapt the doc if you want, but I am still unconvinced by the fact that we want coercing.

**Review by ppedrot — CHANGES_REQUESTED** [review]
I changed my mind again. Please convert rather than coerce. This is a language design issue that will become pervasive, and coercion may be a performance killer. Once again, if people want coercion they can get it with explicit casts whereas the other direction requires low-level hackery.

**Comment by SkySkimmer** [comment]
Change to conversion.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
