### PR TITLE
[cleanup] pretype arguments

### PR DESCRIPTION
**Pull request by gares**
The motivation is that I'd like to add a flag to disable coercion insertion and I don't want to pass yet one more argument.
In passing I also touch coercion.ml since the resolve_tc flag was unnamed, and I'd like to add another boolean.

### CODE REVIEW

**Comment by gares** [comment]
@maximedenes I could use a quick handling by pretype maintainers

**Comment by gares** [comment]
@maximedenes I could use a quick handling by pretype maintainers

**Review by SkySkimmer — APPROVED** [review]

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
@coqbot merge now

**Comment by gares** [comment]
apparently the bot did not obey

**Comment by Alizter** [comment]
I edited Maxime's post and coqbot picked it up. Whilst good for this PR it seems flaky for coqbot to behave this way.

**Pull request merged**
