### PR TITLE
[travis] Perform parallel testing

### PR DESCRIPTION
**Pull request by ejgallego**
We extend the work of #419 , mainly by spanning parallel tests to test different libraries and setups. The patch includes a small README on how to add an external library to be tested.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ok so I think this should be ready to go if people find it useful (I greatly do on my own PRs).

Future work:

- PR overlays: when a PR breaks the external `ci-*` tests, it must provide an "overlay" with a fixed version of the external developments before the PR may be considered. This overlay should be automatically picked from `${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}`, and if things go well, and upstreams fixed the thing the overlay should be empty at merge-time. I will provide a prototype of this idea next month so people can evaluate, for now, comments on how to handle external breakage for travis tests are welcome.
- provide better caching for the `ci-*` tests. Now, every individual `ci-*` test build its own minimal version of Coq, however they could all share it. This is doable by using some external cache, unfortunately I won't have the time to implement it anytime soon.

**Comment by maximedenes** [comment]
Even if this is not the final setup (we may want to take advantage of OPAM if possible, although the caching strategy is not easy to implement then), I'll merge because it is immediately useful to test other PRs and proceed for round 1 of 8.7 merges (as announced on coqdev). Feel free to keep discussing, improving,etc.

**Comment by maximedenes** [comment]
Any objection to moving `ci` to the `dev` folder? `tools` is for tools that are shipped with Coq. `dev` is for dev tools and documentation.

**Comment by Zimmi48** [comment]
@ejgallego While you're at it, maybe you could add GeoCoq as well. Its author recently asked for inclusion in coq-contribs:
> By the way can you add GeoCoq as a contrib ? and remove tarski-geometry which is now contained in GeoCoq ?
> GeoCoq has an opam package, it is also listed in the index on Coq's website.
It compiles with 8.6: https://github.com/GeoCoq/GeoCoq
> But I can not find it on jenkins: https://ci.inria.fr/coq/
> Thanks ?
> Julien

But I think what he really meant was inclusion in the automated testing. (And Matej added it to the testing on Jenkins BTW.)

Also, congratulation for a really impressive work. It seems that using Travis is really going to bring large benefits in real "automated" testing.

As a future improvement, it could be interesting to have the details of which development had a successful build when clicking on "Show all checks." at the bottom of a PR.

**Comment by matej-kosik** [comment]
@Zimmi48 `geocoq` is being tracked:
- [for Coq 8.5](https://ci.inria.fr/coq/job/opam-install-coq-compcert/582/consoleFull),
- [Coq 8.6](https://ci.inria.fr/coq/job/opam-install-coq-geocoq/132/console),
- [Coq trunk](https://ci.inria.fr/coq/job/opam-install-coq-geocoq/134/console)

and you can test whether it builds for your [custom branch](https://ci.inria.fr/coq/job/opam-install-coq-geocoq/136/console) on Jenkins.

If you want some more packages to be tested (and they have corresponding OPAM packages), let me know.

**Comment by Zimmi48** [comment]
@matej-kosik Yes I am aware (that is what I was saying in parentheses in my previous comment). Thanks!

**Comment by ejgallego** [comment]
GeoCoq Added

**Comment by ejgallego** [comment]
> As a future improvement, it could be interesting to have the details of which development had a successful build when clicking on "Show all checks." at the bottom of a PR.

Do you know how to do implement  that?

**Comment by Zimmi48** [comment]
@ejgallego No idea, sorry...

**Pull request merged**
