### PR TITLE
Coq version 8.10+β2

### PR DESCRIPTION
**Pull request by vbgl**
Let’s get ready for a second round of β!

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

**Comment by vbgl** [comment]
Théo, should we wait for #10239 and #10394? Otherwise, I think this is ready.

Also, what’s wrong with the change-log test case?

**Comment by SkySkimmer** [comment]
>Also, what’s wrong with the change-log test case?

You're missing f197a72c65d1313d10b93aec23801ce43f1bdb8f on the PR branch and coqbot doesn't rebase for you.

**Comment by Zimmi48** [comment]
> Théo, should we wait for #10239 and #10394? Otherwise, I think this is ready.

Up to @ppedrot on those two.

**Comment by vbgl** [comment]
Are we ready now?

**Comment by Zimmi48** [comment]
@vbgl I just merged #10239. #10394 does not seem ready.

**Comment by Zimmi48** [comment]
You can also postpone #10239 to 8.10.0 if you prefer to tag now...

**Comment by gares** [comment]
I'm writing some tests for 10394 right now

**Comment by gares** [comment]
I've added a few unit tests (that pass locally) so I believe the patch in #10394 is OK to me.
Unfortunately I had to patch a few other things in order to have unit-tests working on CoqIDE, so the PR itself many break on some CI setup (let's see)

**Pull request merged**
