### PR TITLE
Avoid using "subgoals" in the UI, it means the same as "goals"

### PR DESCRIPTION
**Pull request by jfehrle**
Using "subgoals" in the UI suggests that they are somehow different from "goals" (e.g. do "subgoals" belong to "goals"?) when there is, in fact, no difference.  This PR changes many of those references to "goals", such as in the screen shot below.  We'll still use "subgoals" in some places in the doc and some messages, with this definition:  "Some tactics, such as `split`, create new goals, which may be referred to as _subgoals_ for clarity."

image

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
I support the change, because the systematic use of "subgoal" instead of "goal" doesn't bring anything. In particular, it's not clear of what these are subgoals.
However, I would revert the changes made to the files in `tactics/` as in this case, the parent relationship is clear (a tactic error / info message talks about the (sub)goals generated by this tactic). IMHO, removing the "sub" part in this case makes it more difficult to understand the meaning of the message.

**Comment by jfehrle** [comment]
Looks like I need to create overlays for ci-iris and ci-bedrock because the Coq output in a couple of their tests includes "subgoals".  I've not done that before.  I tried running the script in "Experimental automatic overlay creation and building".  It fails if I include `iris`, maybe because its source is in gitlab.

For bedrock2, the file I need to change is in a dependency, i.e. in https://github.com/tchajed/coq-record-update/blob/d72e98f28a60ffd7fe32011e81f40562b2be3aa6/tests/coqpl_2021.ref.  How do I handle that with an overlay?

**Comment by Zimmi48** [comment]
The main issue with these output tests is that it's hard to be flexible with them and support several Coq versions at once. If I were you, I wouldn't spend time on creating overlays now. I would wait for the PR to be officially approved and then ping `@tchajed` and `@RalfJung` to get their help on fixing those tests in a backward-compatible way.

**Comment by jfehrle** [comment]
Is this is how to do it?
- create a branch in the dependency with the fix, then
- change `_build_ci/bedrock2/.gitmodules` in bedrock with an overlay to refer to the specific branch, 
- merge in Coq
- merge the branch in the dependency into its master
- remove the overlay in Coq
- remove the branch from the dependency

I probably need the dependency code owner to create and remove the branches.

**Comment by jfehrle** [comment]
However, that could break bedrock2's CI if it uses a specific version of Coq rather than master, in which case I should create a branch in the dependency.

**Comment by Zimmi48** [comment]
>Is this is how to do it?

What you described would work for a non-backward-compatible patch, but we do this only for plugins. Libraries generally want to keep compatible with older Coq versions. In this case, I guess this could be done with a Makefile trick but I would involve the project maintainers to have their help. When backward-compatible fixes are prepared we get them merged in the tested projects before merging the corresponding PR in Coq, to avoid the temporary CI breakage.

>should create a branch in the dependency

No branch. As I said, it is the same version of the library that should be kept compatible with several versions of Coq...

But again, I think it shouldn't be the contributor's job to prepare these overlays when libraries have output tests.

**Comment by jfehrle** [comment]
Updated.  What's an appropriate group of reviewers?

**Comment by Zimmi48** [comment]
It's really up to any Coq dev to take this PR as assignee.

**Comment by jfehrle** [comment]
OK.  It's not always clear when there are trivial changes that span multiple subsystems, or even sometimes what qualifies as trivial.

**Comment by silene** [comment]
I am wary of these changes. Changing the output of `coqtop` will break the testing framework of some projects, as you have already experienced. But it might also break editors that parse that output, such as ProofGeneral. I am very reluctant to apply such changes, until all the known Coq editors have been tested for compatibility.

**Comment by Zimmi48** [comment]
That's a good point: our CI infrastructure is currently lacking in terms of tests of external UIs.

On the positive side, "all the known Coq editors" rely on the XML protocol at this point, except for PG. So it's mostly a matter of pinging @Matafou, @erikmd and @cpitclaudel to get their opinion and possibly a compatibility fix.

**Comment by Matafou** [comment]
This will definitely break PG.
But it is only a couple of regexp to change, so I guess there is no real problem.

**Comment by Matafou** [comment]
That said there is a meaning to the name "subgoal", which is the meaning every user of coq understands quite well: 

we call subgoals of a tactic tac (on a goal g) the set of goals on which tac2 would be applied during the execution of:

[g]: tac1 ; tac2.

**Comment by Zimmi48** [comment]
> That said there is a meaning to the name "subgoal", which is the meaning every user of coq understands quite well:
> 
> we call subgoals of a tactic tac1 (on a goal g) the set of goals on which tac2 would be applied during the execution of:
> 
> [g]: tac1 ; tac2.

Agreed, and this is in fact what we finally wrote as a definition as part of #13470. See https://coq.gitlab.io/-/coq/-/jobs/930753747/artifacts/_install_ci/share/doc/coq/sphinx/html/proofs/writing-proofs/proof-mode.html#term-subgoal

**Comment by jfehrle** [comment]
> Libraries generally want to keep compatible with older Coq versions. In this case, I guess this could be done with a Makefile trick but I would involve the project maintainers to have their help.

Or perhaps the test can convert `subgoals` to `goals` with `sed` or `awk` before checking for equality.

> our CI infrastructure is currently lacking in terms of tests of external UIs

Automatically testing external GUIs is not easy.  The tooling would generally be specific to the GUI and the technology used to build it.  How do you detect error messages in the GUI, for example?

**Comment by Zimmi48** [comment]
> > Libraries generally want to keep compatible with older Coq versions. In this case, I guess this could be done with a Makefile trick but I would involve the project maintainers to have their help.
> 
> Or perhaps the test can convert `subgoals` to `goals` with `sed` or `awk` before checking for equality.  Then a single version of the library would work with both old and new versions of Coq.

Yes, that's a sensible option.

> > our CI infrastructure is currently lacking in terms of tests of external UIs
> 
> Automatically testing external GUIs is not easy.  The tooling would generally be specific to the GUI and the technology used to build it.  How do you detect error messages in the GUI, for example?

Indeed, it's not easy to add such tests. There's already one of the vim plugin (Coqtail) in our CI, although I don't know what it tests.

**Comment by jfehrle** [comment]
@Zimmi48 If we should discuss this in a Coq call, I will add it for the January 6th meeting.  Should we?

**Comment by Zimmi48** [comment]
Yes, it's probably a good idea so that we can take a decision and merge or close the PR quickly.

BTW, the test-suite is failing because of the revert of the changes to the `tactics/` folder. You will also need to revert the changes to the corresponding test-suite files (a simple `make -C test-suite approve-output` should do it).

**Review by Zimmi48 — APPROVED** [review]
This PR has been approved by the Coq developers in today's call. To be able to merge it, we would need help from Iris (cc @RalfJung and @robbertkrebbers) and Bedrock2 (cc @samuelgruetter and @andres-erbsen) maintainers to adapt their test-suite to account for this change. Here is a suggestion by Jim on how to do that:

> perhaps the test can convert `subgoals` to `goals` with `sed` or `awk` before checking for equality.  Then a single version of the library would work with both old and new versions of Coq.

Also, @Matafou: you can go ahead and merge your PR adapting Proof General.

**Comment by RalfJung** [comment]
Yeah, we already have a normalization infrastructure for our ui tests, so replacing "subgoal" by "goal" shouldn't be a problem.

**Comment by samuelgruetter** [comment]
As far as I know, we don't test for "subgoal" output in bedrock2 itself, only the dependency [coq-record-update](https://github.com/tchajed/coq-record-update), maintained by @tchajed does.

**Comment by RalfJung** [comment]
I have adjusted the Iris test suite and bumped the Iris dependency in the examples repository.
However, I just realized I probably need to do the same thing with the std++ test suite; that's next.

**Comment by tchajed** [comment]
I just updated the coq-record-update test suite.

**Comment by tchajed** [comment]
@samuelgruetter could you update the coq-record-update submodule in bedrock2? `git submodule update --remote deps/coq-record-update` should work

**Comment by samuelgruetter** [comment]
> @samuelgruetter could you update the coq-record-update submodule in bedrock2? `git submodule update --remote deps/coq-record-update` should work

That's what I already did, but there's still a diff: https://github.com/mit-plv/bedrock2/runs/1696783956?check_suite_focus=true#step:6:633

**Comment by RalfJung** [comment]
The Iris side of the updates should be done.

**Comment by Zimmi48** [comment]
Thank you all for your incredibly fast response!

**Comment by jfehrle** [comment]
Rebased to force a new run.  Let's see how we're doing.

**Comment by jfehrle** [comment]
@samuelgruetter I see this test still expects for `subgoals`.  There could be others after it.

```
@@ -1,11 +1,11 @@
-1 subgoal
+1 goal
   
   f : nat -> nat
   x : X
   ============================
   {| A := A x; B := f (B x); C := C x |} =
   {| A := A x; B := f (B x); C := C x |}
-1 subgoal
+1 goal
   
   x : X
   ============================
Makefile.coq.local:23: recipe for target 'tests/coqpl_2021.vo' failed
```

**Comment by jfehrle** [comment]
@RalfJung Thanks, Iris passes now.

**Comment by tchajed** [comment]
@jfehrle Coq CI uses bedrock2's `tested` branch, which updates automatically every 24h if bedrock2's CI passes.

Unfortunately that CI is broken. @samuelgruetter I'm not sure what happened in bedrock2's CI, but I did finally fix coq-record-update's CI and make sure the test harness works on old Coq versions. It should work on Coq 8.12, including checking the output.

**Comment by samuelgruetter** [comment]
I updated coq-record-update again, noticed that it doesn't work with 8.12.0 (because apparently some error message changed between 8.12.0 and 8.12.2), noticed that I can't update bedrock2's stable CI to 8.13.0 yet because we don't have Ubuntu packages yet, but updated it to 8.12.2, and now, assuming that my fast-forwarding script is not more broken than what I'm [aware of](https://github.community/t/rest-api-for-check-runs-seems-to-ignore-filter-latest/155091), the bedrock2 branch `tested` (that's used by Coq's CI) should get updated tonight :sweat_smile:

**Comment by Matafou** [comment]
I juste pushed the PR adapting PR ProofGeneral/PG#535. This needs more testing though.

**Comment by Zimmi48** [comment]
OK, so if there are no more comments, I'll merge this PR on Monday.

**Comment by jfehrle** [comment]
CI is green now--thanks @samuelgruetter!

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
