### PR TITLE
Document the Set Default Proof Mode command.

### LINKED ISSUE #10909: Set Default Proof Mode is not documented, and is important to mix Ltac2 and Ltac1.
It is just hinted in the doc in a single example, that starts with:

```
From Ltac2 Require Import Ltac2.
Set Default Proof Mode "Classic".
```

And it should be made more explicit.

The option `Set Default Proof Mode` is not documented at all, and neither are its possible values, which include at least "Noedit", "Classic" and "Ltac2".

### PR DESCRIPTION
**Pull request by ppedrot**
Fixes #10909: Set Default Proof Mode is not documented.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Maybe should say something about the -noinit default.

**Comment by ppedrot** [comment]
@SkySkimmer done.

**Comment by ppedrot** [comment]
CI failure is spurious.

**Review by Zimmi48 — APPROVED** [review]
@ppedrot This looks very good but you it would be even better if you could also add a quick mention of the proof mode command in the "Compatibility layer with Ltac1" section of the Ltac2 chapter (not just in the example).

**Comment by ppedrot** [comment]
@Zimmi48 done. This should be ready.

**Review by Zimmi48 — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
