### PR TITLE
Update load_printers after coq-core.boot was added.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
We should add a check for this, or even better, have dune understand ocamldebug.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by Alizter** [comment]
@ejgallego Are there plans for dune to understand ocamldebug?

**Comment by ejgallego** [comment]
> @ejgallego Are there plans for dune to understand ocamldebug?

There is consensus it would be great to have such support, but so far nobody volunteered to do the work , c.f. https://github.com/ocaml/dune/issues/4229

**Pull request merged**
