### PR TITLE
Cleanup disabled test suite directories

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]
Why were they disabled to begin with?

**Review by ejgallego — APPROVED** [review]
LGTM but I'd like confirmation of @herbelin and @mattam82 wrt deleted tests.

**Comment by ejgallego** [comment]
> Why were they disabled to begin with?

Likely due to the old way of merging [for vos and typeclasses] it missed the proper integration; ideal-features is very old so who knows.

**Comment by SkySkimmer** [comment]
vos is relatively new, probably just forgot to add it to the "subsystem" list
typeclasses is older and not wired up in the other targets so who knows 
ideal-features was more a adhoc record of feature wishes, not testing (the ones which were kept got implemented at some point)

**Comment by herbelin** [comment]
I believe that we are aware of the complexity issue in `evar_subst.v` and I suspect that there an official issue open about it (??). For the `Apply.v` file, there is a probably an issue somewhere, otherwise, it is probably worth to open one. For `Case9.v` it would be solved with small inversion presumably (and there is an issue already). It seems that there is something to grasp from `universes.v` also but I would not have time myself, so it is your choice. The file `implicit_binders` was apparently a discussion before taking a decision on syntax, so it is obsolete.

**Comment by SkySkimmer** [comment]
@ejgallego merge?

**Comment by SkySkimmer** [comment]
disabled async proofs in the vos test, see https://github.com/coq/coq/issues/15140

**Comment by ejgallego** [comment]
> @ejgallego merge?

let me process @herbelin comments, but yes, we merge.

Also wouldn't mind if @mattam82 would take a look to typeclasses before we remove it.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
