### PR TITLE
Simplify the intepretation functions of intropatterns.

### PR DESCRIPTION
**Pull request by ppedrot**
We were threading an evarmap state but it turns out this was never modified. This was probably the case since 5dcafa9 actually.

### CODE REVIEW

**Comment by ppedrot** [comment]
cc @herbelin

**Comment by Alizter** [comment]
Will this have an effect on the bench?

**Review by herbelin — APPROVED** [review]
Threading the sigma here seems indeed useless since the evaluation of the argument of `ApplyOn` was delayed.

**Comment by ppedrot** [comment]
@Alizter probably none. If anything this is going to be ε > 0 faster but the difference will be ridiculously small.

**Comment by ppedrot** [comment]
@herbelin would you assign? I don't think there is anything to wait for, it's a purely local change that is trivially correct.

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
