### PR TITLE
Create new record_comments flag and fix comment lexing

### PR DESCRIPTION
**Pull request by rtetley**
Allows for parsing comments independently of beautify.

### CODE REVIEW

**Comment by rtetley** [comment]
The code for parsing comments seems buggy. This example:
```coq
Inductive coulfeu : Set :=
  | Vert : coulfeu
  | Orange : coulfeu
  | Rouge : coulfeu
.


Definition coul_suiv : coulfeu -> coulfeu :=
  fun c =>
    match c with
    | Vert => Orange
    | Orange => Rouge
    | Rouge => Vert
    end.

Theorem th_crou_gen : forall c : coulfeu, c = Rouge -> coul_suiv c = Vert.
Proof.
  intro c0.
  (** Pour démontrer [c0 = Rouge -> coul_suiv c0 = Vert],
      on suppose [c0 = Rouge]
      et on doit alors prouver [coul_suiv c0 = Vert]
      sous cette hypothèse supplémentaire ;
      lorsque l'on introduit une hypothèse, on lui donne un nom. *)
  intro c0rou. (* /!\   CRASH ON THIS LINE   /!\ *)
  (** Le raisonnement sous-jacent est :
      soit c0rou une preuve arbitraire (inconnue) de [c0 = Rouge],
      on peut s'en servir pour démontrer coul_suiv [c0 = Vert]. *)
  rewrite c0rou. cbn [coul_suiv]. reflexivity.
Qed.
```
Produces the following comments / locations: 
```
[document            , 30068, 1710843498.917372] PARSED NEW COMMENTS: 
[document            , 30068, 1710843498.917379] [start: 88, stop: 91, comment 


]
[document            , 30068, 1710843498.917382] [start: 235, stop: 237, comment 

]
[document            , 30068, 1710843498.917385] [start: 311, stop: 312, comment 
]
[document            , 30068, 1710843498.917391] [start: 318, stop: 321, comment 
  ]
[document            , 30068, 1710843498.917395] [start: 330, stop: 590, comment 
  (** Pour démontrer [c0 = Rouge -> coul_suiv c0 = Vert],
      on suppose [c0 = Rouge]
      et on doit alors prouver [coul_suiv c0 = Vert]
      sous cette hypothèse supplémentaire ;
      lorsque l'on introduit une hypothèse, on lui donne un nom. *)
  ]
[document            , 30068, 1710843498.917401] [start: 602, stop: 817, comment  (* /!\   CRASH ON THIS LINE   /!\ *)
  (** Le raisonnement sous-jacent est :
      soit c0rou une preuve arbitraire (inconnue) de [c0 = Rouge],
      on peut s'en servir pour démontrer coul_suiv [c0 = Vert]. *)
  ]
[document            , 30068, 1710843498.917404] [start: 831, stop: 832, comment  ]
[document            , 30068, 1710843498.917407] [start: 848, stop: 849, comment  ]
[document            , 30068, 1710843498.917413] [start: 861, stop: 862, comment 
]
[document            , 30068, 1710843498.917415] ------------------
```

Tested from the vscoq extension. The locations are completely wrong and some comments are simply empty strings ?

**Comment by SkySkimmer** [comment]
Pushed a commit hopefully fixing it.

**Comment by SkySkimmer** [comment]
bonus commit makes beautify not completely broken

**Comment by rtetley** [comment]
Have a hard time testing with nix. I can't build anymore, I get the following error: 
```
File "./theories/Logic/Hurkens.v", line 319, characters 2-3:
Error: Syntax error: illegal begin of vernac.

File "./theories/Numbers/NatInt/NZDiv.v", line 490, characters 1-11:
Error: Syntax error: illegal begin of vernac.

File "./theories/Numbers/NatInt/NZParity.v", line 221, characters 3-4:
Error: Syntax error: illegal begin of vernac.

File "./theories/Numbers/NatInt/NZPow.v", line 381, characters 1-9:
Error: Syntax error: illegal begin of vernac.
```

**Comment by SkySkimmer** [comment]
CI shows the same error

**Comment by SkySkimmer** [comment]
Reduced:
~~~coq
Lemma foo : True.
  (* hello *)
  + idtac.
Abort.
~~~

**Comment by SkySkimmer** [comment]
Should work now

**Comment by rtetley** [comment]
Everything seems to work on the example above 👍

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Not sure if I should assign to myself as a good chunk of the code is from me.
I guess if nobody picks it up in a reasonable time I will do it.

**Comment by SkySkimmer** [comment]
ping @coq/parsing-maintainers

**Comment by ejgallego** [comment]
@SkySkimmer I'm happy if you wanna handle this, tho indeed it is scary code so it would benefit from @herbelin or @ppedrot having a look as you proposed with the ping.

[I'd love to review this myself but I'm gonna clear my current queue first]

**Comment by herbelin** [comment]
It is indeed difficult to judge just at looking at the code. Could we add a few examples, both for checking and preventing regression? I'm otherwise positive at it.

**Comment by SkySkimmer** [comment]
>It is indeed difficult to judge just at looking at the code. Could we add a few examples, both for checking and preventing regression? I'm otherwise positive at it.

Added test

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by herbelin** [comment]
IIUC, there would be still fine-tuning to do (as in the "CRASH" line) but this is well worth a merge. So, unless someone says it is not ready, I'll merge soon.

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
@coqbot merge now

**Pull request merged**
