### PR TITLE
[gitlab-ci] Only run Windows jobs when ONLY_WINDOWS variable is true.

### PR DESCRIPTION
**Pull request by Zimmi48**
The schedule is used to run Windows with all the addons.  We are not interested in having any other job run in this case.

cc @gares

### CODE REVIEW

**Comment by Zimmi48** [comment]
Regarding the reporting of the failures, we could have @coqbot open an issue when this happens (and there wasn't already an issue about this). WDYT?

**Comment by SkySkimmer** [comment]
Why except:schedule instead of using an env var?

**Review by gares — APPROVED** [review]

**Review by ejgallego — DISMISSED** [review]
This is not modular and thus prone to errors.

Moreover `schedule` builds seem like a waste of resources and don't integrate well with our workflow; IMO Coq's core CI should be kept lean, builds such as the proposed windows packaging one should be moved to a different repository.

**Comment by ejgallego** [comment]
Moreover the current windows build should be done modularly, it makes little sense to have such a long build that does fail if there is some package just fails.

@corwin-of-amber did define a more compact package format for jscoq that could be of use here.

**Comment by Zimmi48** [comment]
@ejgallego You are blocking a simple improvement to the status quo by hijacking the PR to remind everyone of what could be best. But *I* am not going to do the changes that you ask for because it will become obsolete anyway as soon as the platform project moves forward and *Enrico* simply found a not so satisfying situation and proposed a few changes to make it less bad. So please withdraw this change request.

**Comment by Zimmi48** [comment]
> Moreover the current windows build should be done modularly, it makes little sense to have such a long build that does fail if there is some package just fails.

FTR, I agree with this. This is just not a valid reason to block this PR from getting merged.

**Comment by ejgallego** [comment]
Sorry I consider my request for changes valid and so far it stands, let me clarify:

- by modular I mean that the schedule job contaminates every other job, thus it is hard to maintain as now every person editing the gitlab file must be aware of this side effect which is furthermore non-visible. It prevents on running the other jobs as a scheduled task would we ever want to do it. Sorry if I confused you with the other request for modularity, which I agree is unrelated and I meant as a suggestion
- I consider this schedule job a waste of precious CI resources and out of the scope of Coq's CI
- I consider this an increase of the technical debt of the CI, and I don't like that we have even to hack coqbot for this, which would pollute the namespace. Also, it is not clear how the bugs coqbot would be solved, certainly they cannot be solved by a commit.

I think the best is to move this check to other organization / repository.

**Comment by Zimmi48** [comment]
This PR is not introducing the schedule. The schedule job is already running. This PR is *saving* resources.

I'm failing to see exactly what you suggest that could improve the PR.

**Comment by SkySkimmer** [comment]
>Why except:schedule instead of using an env var?

ping

**Comment by Zimmi48** [comment]
> > Why except:schedule instead of using an env var?
> 
> ping

Since the goal is to exclude, this would give exactly the same number of lines changed and not solved the modularity issue @ejgallego is complaining about. I put `schedule` since it is only used for this purpose for now. But sure, an env var would work as well.

**Comment by ejgallego** [comment]
> This PR is not introducing the schedule. The schedule job is already running. This PR is _saving_ resources.

I think we should remove that scheduled job.

**Comment by ejgallego** [comment]
Anyways @zimmi48 I'm not strongly opposed to this , just don't like to handle this kind of problems with hacks and resources. So if you want to push this PR as is please feel free to discard my request for changes.

**Comment by gares** [comment]
Isn't the schedule job testing we can actually build the windows package for the release? This seems important to me. Sure, one day the platform repo will take care of this. But when? Theo said not before 8.12 during the call. The schedule runs every day, I'm ok runnin it less often (it is a Cron, we have all the freedom we need)

**Comment by Zimmi48** [comment]
>there is no plan for what happens when the job fails

The goal is to notice such failures earlier. We have to fix them anyway to be able to release. The fact that Enrico wanted to add some more add-ons to the Windows installer undercovered an issue with native-compute (which is going to be fixed in Coq) which created a failure in Bignums. We should have known before.

The add-ons build is not run by default because it is taking lots of resources. But when we removed it, we clearly said that we would replace it by a cron job. But no one ever took care of making this happen (I'm the one to blame here). Now, this has been fixed (thanks Enrico!). I know this is still not satisfactory, but as long as we stay with the status quo, it is better to be aware of problems earlier than later.

BTW, I forgot to cc @MSoegtropIMC in this PR.

**Comment by Zimmi48** [comment]
For this PR, the only question to me is whether we keep excluding based on "schedule" (it makes sense IMHO as long as this is the only scheduled job we want to run) or whether we prefer to exclude based on an env var. Up to you @SkySkimmer.

**Comment by Zimmi48** [comment]
Regarding the build frequency, yes, running it only once a week should be enough IMHO.

**Comment by SkySkimmer** [comment]
I prefer an env var

**Comment by gares** [comment]
> I prefer an env var

if you do so then don't forget to update the cron

**Comment by Zimmi48** [comment]
I've fixed the PR and the scheduled pipeline.

**Comment by MSoegtropIMC** [comment]
> I think we should remove that scheduled job, it was not introduced in a proper way, in particular there is no plan for what happens when the job fails, and quite a few other issues.

Didn't we discuss and agree that as soon as the Coq platform is out (I plan to release the first one for 8.12, so a 1..3 months after the 8.12.0 release) we split CI such that for every PR we just run core Coq CI and teh platform CI runs as a schedules job, say once every night?

Right now we have the issue that changes in master from things we run in our CI break our CI regularly and there is not that much of a plan what to do about that either. I find the solutuon of a core CI where then really everybody tries to fix it eimmediately when it breaks and a platform CI where the atcion is more "send an email to the maintainer" absolutely reasonable.

And I see this PR a step in that direction - also to experiment what to do in which way in CI.

**Comment by Zimmi48** [comment]
Yes. BTW, I need to write to you about the platform. I'll do it in the coming week.

**Comment by MSoegtropIMC** [comment]
> Yes. BTW, I need to write to you about the platform. I'll do it in the coming week.

Sure. Maybe we should have a call on the topic.

**Comment by Zimmi48** [comment]
@SkySkimmer This is ready.

**Pull request merged**
