### PR TITLE
[default.nix] Add ocpIndent and ocp-index.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I thought this file was for directing compilation, but this doesn't have anything to do with that? 😕

**Comment by maximedenes** [comment]
It is used for typically two purposes : setting up a build environment for Coq, or a development environment.

IIUC, the first one is what you had in mind. This PR is improving the second one.

**Comment by Zimmi48** [comment]
The `if lib.inNixShell` part is restricting the set of packages for the "development environment" but they won't be used in the package compilation phase.

**Comment by SkySkimmer** [comment]
>The if lib.inNixShell part is restricting a subset of the packages to the "development environment". They won't be used in the package compilation phase.

I see, that makes sense.

**Pull request merged**
