### PR TITLE
[ci] Fix fiat-crypto-ocaml build

### PR DESCRIPTION
**Pull request by JasonGross**
See https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/fiat.20crypto.20broken/near/279808950 and https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/fiat.20crypto.20broken/near/279824688, thanks @silene for tracking down and explaining the issue

### CODE REVIEW

**Comment by silene** [comment]
Note that the overlays are pinned once and for all inside release branches. So, unless the `ocamlfind` change in `fiat-crypto-ocaml` predates the branching point for 8.15, this pull request does not need to be backported.

**Comment by ppedrot** [comment]
Any takers? The CI is still broken on master.

**Comment by silene** [comment]
@coqbot: merge now

**Review by silene — APPROVED** [review]

**Comment by silene** [comment]
@coqbot: merge now

**Pull request merged**
