### PR TITLE
Fast accumulator check in native compilation

### PR DESCRIPTION
**Pull request by ppedrot**
This PR replaces the call to `Nativevalues.is_accu` function in native compilation of fixpoints by a trivial ML pattern-matching. The latter is way faster than the former, as it is just a jump, while the `is_accu` function needs to call low-level C functions that perform a lot of useless checks.

The same trick could be used for cofixpoints, but I'll leave that to another PR.

This mitigates #8019.

@maximedenes is without a doubt the natural assignee.

### CODE REVIEW

**Comment by ppedrot** [comment]
Benchmark running here: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/488/.

**Comment by ppedrot** [comment]
Bench:
```
┌──────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                       │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │            NEW            OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  881.44  889.85 -0.95 % │  2443862051978  2465772518028 -0.89 % │  3547665843516  3547752051498 -0.00 % │ 1349540 1349484 +0.00 % │  33 430 -92.33 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   61.65   61.98 -0.53 % │   170000921796   170233781009 -0.14 % │   240129859810   240264828842 -0.06 % │  531744  531772 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  711.58  715.11 -0.49 % │  1971668635670  1981691459065 -0.51 % │  3034558111412  3033665949171 +0.03 % │ 3374288 3559696 -5.21 % │   1  10 -90.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  462.67  464.76 -0.45 % │  1287108465171  1292677542480 -0.43 % │  2116461449978  2116617587939 -0.01 % │  803476  803692 -0.03 % │   5   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  215.75  216.64 -0.41 % │   598983011957   600965722446 -0.33 % │   856534214040   856655276627 -0.01 % │  844292  860468 -1.88 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real-closed │  184.17  184.87 -0.38 % │   510314351753   512725715027 -0.47 % │   776353438037   776386063368 -0.00 % │  831892  831868 +0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  199.18  199.80 -0.31 % │   552663475175   554414250749 -0.32 % │   777806756541   777837569456 -0.00 % │  643776  643744 +0.00 % │   0   1 -100.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd-order │ 1426.73 1430.62 -0.27 % │  3964336886931  3985945961544 -0.54 % │  6703415185153  6703979362008 -0.01 % │ 1371676 1371756 -0.01 % │  41   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  728.84  729.92 -0.15 % │  2016382721684  2017054340058 -0.03 % │  2429587098918  2430055207715 -0.02 % │ 1387732 1387704 +0.00 % │   6  11 -45.45 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-formal-topology │   54.26   54.34 -0.15 % │   147549563377   147867669358 -0.22 % │   221430890107   221473794672 -0.02 % │  479432  479240 +0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  289.12  289.53 -0.14 % │   801346358189   803173216538 -0.23 % │  1169404284222  1169562099881 -0.01 % │ 1112328 1111048 +0.12 % │   9  18 -50.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-corn │ 1557.76 1559.22 -0.09 % │  4324283804088  4327276622638 -0.07 % │  6394525537353  6394386098701 +0.00 % │  883880  883760 +0.01 % │  55   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  128.54  128.58 -0.03 % │   356440814007   357032674658 -0.17 % │   473333567613   473635698987 -0.06 % │  496176  496072 +0.02 % │  21   1 +2000.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   81.12   81.08 +0.05 % │   224095302487   224093782255 +0.00 % │   332043945958   331882126074 +0.05 % │  585652  585056 +0.10 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 2828.46 2824.69 +0.13 % │  7844417509814  7833378845266 +0.14 % │ 12570573962531 12570332705372 +0.00 % │ 1387992 1395436 -0.53 % │  45  50 -10.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   95.88   95.68 +0.21 % │   265348580734   264417930258 +0.35 % │   377045359919   377162126166 -0.03 % │  516500  516416 +0.02 % │  13   0  +nan % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 4003.87 3994.03 +0.25 % │ 11135762158511 11102671220158 +0.30 % │ 14593369151528 14593241158465 +0.00 % │ 2225648 2225776 -0.01 % │   7   9 -22.22 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │  276.61  274.92 +0.61 % │   767951404367   764525145073 +0.45 % │   984443895699   984735229741 -0.03 % │ 1244608 1244648 -0.00 % │ 215   2 +10650.00 % │
├──────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-math-classes │  242.86  241.37 +0.62 % │   667731643530   665776232023 +0.29 % │   863009233314   863241487635 -0.03 % │  532844  532980 -0.03 % │ 216   0  +nan % │
└──────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by JasonGross** [comment]
Let me update fiat-crypto so that the bench will test `native_compute`.

**Review by maximedenes — APPROVED** [review]
Very nice! Benjamin and I were not aware that `Obj.tag` was costly.

**Pull request merged**
