### PR TITLE
Split pretty printing representation from IO operations.

### PR DESCRIPTION
**Pull request by ejgallego**
This patch splits pretty printing representation from IO operations, continuing work started in 8.5 by the introduction of feedback
- `Pp` is kept in charge of the abstract pretty printing representation.
- The `Feedback` module provides interface for doing printing IO.

The patch continues work initiated for 8.5 and has the following effects:
- The following functions in `Pp`: `pp`, `ppnl`, `pperr`, `pperrnl`,
  `pperr_flush`, `pp_flush`, `flush_all`, `msg`, `msgnl`, `msgerr`,
  `msgerrnl`, `message` are removed. `Feedback.msg_*` functions must be
  used instead.
- Feedback provides different backends to handle output, currently,
  `stdout`, `emacs` and CoqIDE backends are provided.
- Clients cannot specify flush policy anymore, thus `pp_flush` et al are
  gone.
- `Feedback.feedback` takes an `edit_or_state_id` instead of the old
  mix.

Lightly tested: Test-suite passes, Proof General and CoqIDE seem to work.

### CODE REVIEW

**Comment by herbelin** [comment]
Hi, as discussed, it seems there are problems with flushing when using the coqtop interface.

In coqtop, if I type an unknown command, say "foo", then no error message is displayed. If I type a second command, then a message is finally displayed.

If I type say "Goal True.", newline, then "I.", newline, then "I.", newline, then "J", newline, an error is displayed only at the time of typing "J".

I don't have time to look at it myself. Emilio, can I let you investigate? That would be great.

**Comment by ejgallego** [comment]
Hi Hugo, I will take care of that next week, IMO it should be easy to fix.

**Comment by ejgallego** [comment]
Hi @herbelin , I cannot reproduce the first one "foo". After I type `foo .` the error is always displayed.

With regards to the second one, I need to investigate more but it is likely that flushing is not the culprit! Indeed, if you input any constructor no error message is printed at all, but I'll investigate more.

I did a review of flushing again and it seems correct.

**Comment by herbelin** [comment]
Indeed, with "foo" it is ok. In my experiment, I was using I and J and extrapoled to arbitrary foo what was wrong. The problem seems to be with one-letter words. That's strange, and maybe not related to this commit.

f.     (*  silent *)
f.     (* Syntax error: illegal begin of vernac. Toplevel input, characters 0-1: *)

Thanks for looking at it.

**Comment by JasonGross** [comment]
Is this related to [bug #4784](https://coq.inria.fr/bugs/show_bug.cgi?id=4784)?

**Comment by ejgallego** [comment]
Hi Jason, indeed it is almost sure that #179 is the culprit, the emacs printing cleanup was the most delicate part. I'll have a look for sure before Thu but the fix should be trivial.

**Comment by ejgallego** [comment]
Hi @herbelin , #193 also fixes the problem you noticed. Sorry for the bug!

**Pull request merged**
