### PR TITLE
[bench] cleanup remaining mem faults values

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Don't run a full bench for this
Repush and bench with just bignums

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
@SkySkimmer Looks like its fine.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
