### PR TITLE
Tag 8.13 beta1

### PR DESCRIPTION
**Pull request by gares**
This should be it.
It's not super clear what "We generally do not update the magic numbers at this point." means. In which case should I do that?

### CODE REVIEW

**Comment by Zimmi48** [comment]
> In which case should I do that?

This was just based on observing how previous beta were handled when I wrote this. I'm not the expert on magic numbers though, so this could be a discussion to have with other Coq devs.

**Comment by Zimmi48** [comment]
It looks like we're doomed! Homebrew has chosen to start failing again on all PRs since yesterday :scream: 

See https://dev.azure.com/coq/coq/_pipeline/analytics/stageawareoutcome?definitionId=1 (this looks like a 100% failure rate today with 4 failures, all during this step).

**Comment by gares** [comment]
```
==> `brew cleanup` has not been run in 30 days, running now...
Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12.0MB)
```

**Comment by gares** [comment]
can we "reset" the workers on azure? I really don't know how these VMs are handled, but it seems that is the cleanup that fails

**Comment by Zimmi48** [comment]
I know very little about Azure. You have a whole bunch of settings that you can access here https://dev.azure.com/coq/coq/_settings/testmanagement after being logged in with GitHub though.

To add to the doom, it looks like the Windows job is failing as well: https://coq.gitlab.io/-/coq/-/jobs/894114063/artifacts/artifacts/buildlogs/ocaml-4.08.1-make-flexdll_err.txt

**Comment by gares** [comment]
For windows we don't have the right job in CI yet

**Comment by gares** [comment]
@Zimmi48 , but for the failures, is the PR OK? I'd like to merge and tag.

**Comment by Zimmi48** [comment]
Sure but you have another strategy to produce the macOS installer once this is tagged if we don't manage to fix the Azure failure without changing the configuration itself? (Like asking a Coq developer on macOS to produce the installer?)

**Comment by gares** [comment]
I have an installer build on azure that has the only difference in the contents of this PR (version number).
As soon as I tag I can ask on zulip if Matthieu can build it, for example.

**Comment by gares** [comment]
OSX is back on track

**Pull request merged**
