### PR TITLE
[vernac] Remove unused abstraction from declaration_hook type.

### PR DESCRIPTION
**Pull request by ejgallego**
"Declaration" hooks can be polymorphic on their return type, however
this facility doesn't seem used in the codebase.

We thus remove the polymorphism with the hope to be able to reify the
control later on.

### CODE REVIEW

**Comment by ejgallego** [comment]
This needs a trivial overlay, will do if I get green light on the change itself.

**Review by mattam82 — APPROVED** [review]

**Review by herbelin — APPROVED** [review]
Is good and I'd use it in my cleanup of lemmas.ml.

**Comment by herbelin** [comment]
Assigning, and shall merge tomorrow noon, if no comments by then.

**Comment by ejgallego** [comment]
Is the windows build correctly using the overlays here? It looks like it is not. Not that it should build the addons in the PR, it seems redundant to me.

**Comment by ejgallego** [comment]
> Assigning, and shall merge tomorrow noon, if no comments by then.

Great thanks; in fact I was wondering about unifying the two hooks, I was thinking whether it would make sense to have a weaker and stronger type and so they would take different codepaths.

I see you have unified them in a different PR will have a look.

**Comment by herbelin** [comment]
> shall merge tomorrow noon, if no comments by then.

I forgot the presence of overlays for Elpi, Equations and plugin_tutorials. I need to synchronize with @gares, @mattam82 and @ybertot, right? So, maybe is it better to plan, say, Monday noon Central European Summer Time. Please tell if not possible for you around that time to merge the respective `vernac+monify_hook` branches.

(Or are event-triggered merges possible? Something like validating in advance that a PR shall be automatically merged at the time a dependence from another project is merged?)

**Comment by ejgallego** [comment]
> I forgot the presence of overlays for Elpi, Equations and plugin_tutorials. I need to synchronize with @gares, @mattam82 and @ybertot, right? So, maybe is it better to plan, say, Monday noon Central European Summer Time. Please tell if not possible for you around that time to merge the respective `vernac+monify_hook` branches.
> 
> (Or are event-triggered merges possible? Something like validating in advance that a PR must be automatically merged at the time a dependence from another project is merged?)

I should submit the PRs first. Let me do that.

**Comment by ejgallego** [comment]
> I should submit the PRs first. Let me do that.

Done:
- https://github.com/LPCIC/coq-elpi/pull/34
- https://github.com/mattam82/Coq-Equations/pull/140
- https://github.com/ybertot/plugin_tutorials/pull/11

**Pull request merged**
