### PR TITLE
Clean support of primitive integers

### PR DESCRIPTION
**Pull request by silene**
This pull request fixes some awful code we found when trying to add support for signed primitive operations.

### CODE REVIEW

**Comment by silene** [comment]
I am completely stumped by the error with FLambda+Dune and Opam:
```
File "kernel/uint63.mli", line 36, characters 11-14:
36 | val of_z : Z.t -> t
                ^^^
Error: Unbound module Z
```

**Review by ppedrot — COMMENTED** [review]
I am not competent for those changes, but if you manage to find a reviewer and you need an assignee...

**Comment by SkySkimmer** [comment]
>I am completely stumped by the error with FLambda+Dune and Opam:

dune needs to be told that the kernel depends on zarith, ie moving the zarith mention from https://github.com/coq/coq/blob/2eeeba76598258bd5691a9825fd888c350fbcef3/interp/dune#L6 to kernel/dune 
Is this dependency actually desired though?

**Comment by silene** [comment]
> Is this dependency actually desired though?

I guess it is a matter of point of view. Anyway, I worked around the issue by making the abstraction barrier a bit weaker. The whole CI went through successfully.

**Review by proux01 — APPROVED** [review]
LGTM

**Comment by proux01** [comment]
> I am not competent for those changes, but if you manage to find a reviewer and you need an assignee...

Indeed @ppedrot, I was able to review but cannot assign, so your offer is welcome.

**Review by ppedrot — COMMENTED** [review]
If this is a unsoundness bug, do you have a reliable test?

**Comment by proux01** [comment]
That would require a plugin. Calling `Uint63.of_int` with a negative value on 32 bit arch could have caused issues but this is inaccessible from the vernacular side.

**Comment by ejgallego** [comment]
> I guess it is a matter of point of view. Anyway, I worked around the issue by making the abstraction barrier a bit weaker. The whole CI went through successfully.

Indeed, `zarith` is only used on the notations layer and up [by plugins], dune allows to make build dependencies much stricter than the current make setup, including forbidding libraries to have access to transitive dependencies, so whether to have the kernel for example using `zarith` is up to you. [I guess it should not, IIANM]

**Review by ppedrot — APPROVED** [review]
Trusting the relevant experts on these delicate matters.

**Comment by ppedrot** [comment]
I'll merge this soon, but maybe @maximedenes wants to comment before?

**Comment by silene** [comment]
> If this is a unsoundness bug, do you have a reliable test?

I do not know if it is reliable, because I have not coded it. But here is the idea. First you prove `L: forall x, ((x >> 1) <=? x)%int63 = true`. Then you build the term `L x`, with `x` created by a 32-bit plugin using `Int63.of_int (-1)`. Finally, you convert the type of `L x` to `false = true` by reduction (either `compute` or `vm_compute`, not sure about `native_compute`).

(To be clear, this is not an axiom-free proof of `False`, since `L` relies on the axioms of `Int63.v`.)

**Comment by gares** [comment]
If there are "unsafe" ML APIs, as a plugin writer I'd like to know that.
Some files export APIs in `Unsafe` or `Internal` sub modules, which is a clear indicator you should read the doc.
This `Uint63.of_int` that does not check for positivity should be in one of these, and maybe a slower variant with a runtime check outside.

**Comment by silene** [comment]
> This `Uint63.of_int` that does not check for positivity should be in one of these, and maybe a slower variant with a runtime check outside.

First, the positivity is not the issue, since the function has to support negative inputs. It is is just that these negative values have to be stored on 63 bits rather than 64 bits.

Second, some other function (namely `Uint63.of_int64`) could indeed be split into an unsafe version and a safe version. But nobody would ever notice any performance gain from this split. Indeed, there is only one instruction more at the assembly level, for a function that is almost never called. So, this is not worth the effort.

**Comment by proux01** [comment]
@silene while you are at it, there are three instances of `Z.of_string (Uint63.to_string _)` that could benefit from going through int64 in `interp/constrextern.ml`, `interp/notation.ml` and `plugins/syntax/float_syntax.ml`.

**Comment by silene** [comment]
Right, and now that I search for them, there are several other instances in `numTok.ml`. Do they reproduce when we are not looking?!

**Comment by ppedrot** [comment]
@silene are you opening another PR, or should I wait for your changes in this one?

**Comment by proux01** [comment]
> there are several other instances in `numTok.ml`

`numTok.ml` is for number token (unbounded) not for 63-bit integers so I doubt going through int64 would be appropriate there.

**Comment by silene** [comment]
> are you opening another PR

I do not have time right now, so I will open another PR if this one has been merged by then.

**Comment by ppedrot** [comment]
Let's merge now then.

**Comment by ejgallego** [comment]
Note that some of the code discussed here was in this shape due to the migration to `zarith`, which indeed offers a different API and hence the mismatch.

**Pull request merged**
