### PR TITLE
Avoid trivial (u=u) constraints in AcyclicGraph.constraints_for

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure how often this happens in practice but it seems it could.

### CODE REVIEW

**Comment by ejgallego** [comment]
cc: @jhjourdan

**Comment by ejgallego** [comment]
Would you like to bench this @SkySkimmer ?

**Comment by SkySkimmer** [comment]
The bench wasn't busy so I started https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/714/console

**Comment by SkySkimmer** [comment]
```
┌────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬───────────────────────────────┬──────────────────────────┐
│                        │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]     │        mem faults        │
│                        │                         │                                             │                                             │                               │                          │
│           package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD PDIFF   │    NEW    OLD    PDIFF   │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│           coq-compcert │ 1014.86 1030.63 -1.53 % │     2829529146662     2871274094681 -1.45 % │     4395483888026     4396473937434 -0.02 % │    1040444    1042512 -0.20 % │    211    335   -37.01 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│          coq-fourcolor │ 2535.40 2559.72 -0.95 % │     7070454563244     7136177881905 -0.92 % │    12953350638570    12957523703029 -0.03 % │     884792     922776 -4.12 % │      1      0     +nan % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-flocq │  593.24  598.48 -0.88 % │     1650829830371     1665032133149 -0.85 % │     2330939876294     2330376623444 +0.02 % │    1262880    1243680 +1.54 % │    277    276    +0.36 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-hott │  343.51  345.82 -0.67 % │      935827965314      938883991066 -0.33 % │     1430183933002     1430576226195 -0.03 % │     479704     479808 -0.02 % │    476    264   +80.30 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-math-classes │  218.12  218.54 -0.19 % │      609594046109      610471407881 -0.14 % │      777646972840      778087743061 -0.06 % │     518744     519536 -0.15 % │     43     16  +168.75 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-sf-plf │   42.07   42.14 -0.17 % │      117354032610      117804041201 -0.38 % │      150584580150      151254345563 -0.44 % │     493220     487800 +1.11 % │     11     19   -42.11 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-fiat-crypto │ 4162.37 4167.63 -0.13 % │    11565719092634    11579884436394 -0.12 % │    18435781389087    18440173613325 -0.02 % │    2486132    2490680 -0.18 % │    990    755   +31.13 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-ssreflect │   40.10   40.14 -0.10 % │      110932946185      110953890201 -0.02 % │      133747457447      133796791508 -0.04 % │     532264     532612 -0.07 % │     12     64   -81.25 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-verdi │  124.02  124.14 -0.10 % │      344893737915      344628348698 +0.08 % │      443338643651      443753538480 -0.09 % │     595300     597436 -0.36 % │      9      9    +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│     coq-mathcomp-field │  239.44  239.65 -0.09 % │      667527340071      667888820844 -0.05 % │      962353856652      962475512339 -0.01 % │     767636     769472 -0.24 % │      0     76  -100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│  coq-mathcomp-solvable │  203.34  203.51 -0.08 % │      566769793354      566600355636 +0.03 % │      764858921413      765173446111 -0.04 % │     804724     805612 -0.11 % │     11     13   -15.38 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│             coq-geocoq │ 1994.72 1995.84 -0.06 % │     5564847652497     5570307282642 -0.10 % │     8114999200062     8117226731478 -0.03 % │    1195660    1201336 -0.47 % │    295    190   +55.26 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│               coq-corn │ 1488.03 1488.46 -0.03 % │     4155146983482     4154890649575 +0.01 % │     6205950501695     6206790411482 -0.01 % │     836664     836760 -0.01 % │      1      1    +0.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-character │  203.72  203.77 -0.02 % │      567340390562      567440261245 -0.02 % │      763889389422      764190240664 -0.04 % │    1085288    1084508 +0.07 % │     26     62   -58.06 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-unimath │ 2705.03 2703.51 +0.06 % │     7536230480598     7532439265622 +0.05 % │    13598414233270    13608949488740 -0.08 % │     911544     912304 -0.08 % │    278    377   -26.26 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│         coq-verdi-raft │ 1358.24 1357.17 +0.08 % │     3786410630823     3786572729264 -0.00 % │     5173535503373     5177500022672 -0.08 % │    1815236    1830036 -0.81 % │      2      1  +100.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│       coq-fiat-parsers │  695.59  694.93 +0.09 % │     1945806549498     1945094778659 +0.04 % │     2983741886008     2982538255374 +0.04 % │    3190588    3218464 -0.87 % │    296    641   -53.82 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│         coq-coquelicot │   74.84   74.74 +0.13 % │      205581545155      205919240690 -0.16 % │      247760460446      248472543813 -0.29 % │     680040     680200 -0.02 % │    206     18 +1044.44 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│            coq-bignums │   72.00   71.90 +0.14 % │      200376696033      200416331978 -0.02 % │      267211392069      267210253765 +0.00 % │     500788     500676 +0.02 % │    174    148   +17.57 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│   coq-mathcomp-algebra │  174.92  174.65 +0.15 % │      487549886177      486973189330 +0.12 % │      610843656078      610912487157 -0.01 % │     635956     636172 -0.03 % │     16      3  +433.33 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│ coq-mathcomp-odd-order │ 1532.98 1530.06 +0.19 % │     4268842706113     4265020317552 +0.09 % │     7277571777505     7280635781301 -0.04 % │    1252148    1258112 -0.47 % │     97     42  +130.95 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│        coq-lambda-rust │ 2086.36 2080.00 +0.31 % │     5807860304748     5796945154276 +0.19 % │     7999224426349     7974387052215 +0.31 % │    1407272    1408468 -0.08 % │     53      5  +960.00 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│              coq-color │  707.75  705.25 +0.35 % │     1978160562264     1972758730571 +0.27 % │     2372443980063     2373524878110 -0.05 % │    1387004    1376008 +0.80 % │    251    454   -44.71 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│          coq-fiat-core │  109.91  109.37 +0.49 % │      312750891577      311522356297 +0.39 % │      392005733068      392179478000 -0.04 % │     503308     503492 -0.04 % │    634    250  +153.60 % │
├────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼───────────────────────────────┼──────────────────────────┤
│  coq-mathcomp-fingroup │   55.61   55.24 +0.67 % │      154843878591      154486819762 +0.23 % │      203180085868      203275039497 -0.05 % │     579672     579648 +0.00 % │     84      6 +1300.00 % │
└────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴───────────────────────────────┴──────────────────────────┘

```

**Comment by ejgallego** [comment]
Seems positive in general, let's merge.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
On a more general comment, CODEOWNERS for this file should be updated to someone else more familiar with the code; maybe @jhjourdan or @Armael ?

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
