### PR TITLE
Avoid using Evd.empty in a few places

### PR DESCRIPTION
**Pull request by SkySkimmer**
The rtauto change fixes the geocoq error (uncaught Not_found hidden by `try`) in https://github.com/coq/coq/pull/17346
Not sure if it's possible to get the error without that change, the geocoq code is fairly big so I'm not minimizing.

Overlays:
- https://github.com/mattam82/Coq-Equations/pull/543

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
What's with the test-suite failure?

**Comment by SkySkimmer** [comment]
Apparently the Evd.empty in cases is needed

**Comment by SkySkimmer** [comment]
Cases patch fixed and split off to https://github.com/coq/coq/pull/17445

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
serapi failure is spurious, it worked in https://gitlab.com/coq/coq/-/jobs/4031016846

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
