### PR TITLE
Add `reg` theorems for `nat` on multiplication

### LINKED ISSUE #17354: Cancelation lemmas for multiplication on `nat` are missing
#### Description of the problem

There are lemmas `Z.mul_reg_{l,r}` for cancellation of multiplication on integers:

```
Z.mul_reg_l
     : ∀ n m p : Z, p ≠ 0 → p * n = p * m → n = m
Z.mul_reg_r
     : ∀ n m p : Z, p ≠ 0 → n * p = m * p → n = m
```

These lemmas also hold for `nat` but are missing in Coq's standard library.

Std++ includes versions these lemmas for `nat`, but it would be great to have them in Coq's standard library. See https://gitlab.mpi-sws.org/iris/stdpp/-/merge_requests/450 

#### Coq Version

```
The Coq Proof Assistant, version 8.16.1
compiled with OCaml 4.13.1
```

### PR DESCRIPTION
**Pull request by HaoYang670**
Fixes / closes #17354

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by proux01** [comment]
We already have
```Coq
Lemma eqn_pmul2l m n1 n2 : 0 < m -> (m * n1 == m * n2) = (n1 == n2).
Lemma eqn_pmul2r m n1 n2 : 0 < m -> (n1 * m == n2 * m) = (n1 == n2).
```
why would you need a weaker version? (if the implication is really needed, one can use `eqbLR` or `eqbRL`)

**Comment by HaoYang670** [comment]
Hi @robbertkrebbers, do we still need these?

**Comment by proux01** [comment]
Ho, sorry it's about Coq stdlib here. I accidentally mixed up with MathComp, so please disregard my comment above.
I have no opinion about that part of the the stdlib since I'm not using it.

**Comment by robbertkrebbers** [comment]
Thanks for the PR.

I think it's important that `Z` and other number types are consistent. So we should either have this lemma for all `Numbers` instances, or none at all. Otherwise it's confusing.

If we want to have them for all, we should remove the specific versions for `Z` and the comment, see https://github.com/coq/coq/blob/master/theories/ZArith/BinInt.v#L1281

If we want to have them for none at all, we should deprecated the versions for `Z` and have a warning that says to use the `<->` lemma instead.

**Comment by HaoYang670** [comment]
Hi @robbertkrebbers, should we define a type class for all number types?

**Comment by HaoYang670** [comment]
Hi @robbertkrebbers, could I know which module it is?

**Comment by robbertkrebbers** [comment]
`NZMulOrderProp` I think, here's the abstract version of the biimplication that was mentioned in the issue: https://github.com/coq/coq/blob/master/theories/Numbers/NatInt/NZMulOrder.v#L100

**Comment by HaoYang670** [comment]
Move `mul_reg_l` and `mul_reg_r` from BigInt to NZMulOrder.

**Comment by proux01** [comment]
Note that if you  (re)move lemmas, you need a deprecation (https://coq.inria.fr/distrib/current/refman/using/libraries/writing.html).

**Comment by robbertkrebbers** [comment]
> Note that if you (re)move lemmas, you need a deprecation (https://coq.inria.fr/distrib/current/refman/using/libraries/writing.html).

Unless I am mistaken, you can still refer to the `Z` lemmas by `Z.lem`. It merely got moved to a different place and generalized from Z to all instances of Numbers.

**Comment by robbertkrebbers** [comment]
By the way, it appears there are plenty of more lemmas specific to `Z` in https://github.com/coq/coq/blob/master/theories/ZArith/BinInt.v#L1281 which should either be generalized to Numbers or be deprecated.

**Comment by HaoYang670** [comment]
Thank you, @proux01 @robbertkrebbers for your review!

> > Note that if you (re)move lemmas, you need a deprecation (https://coq.inria.fr/distrib/current/refman/using/libraries/writing.html).

> Unless I am mistaken, you can still refer to the Z lemmas by Z.lem. It merely got moved to a different place and generalized from Z to all instances of Numbers.

I am not familiar with the module type in Coq. But actually, I can't refer Z.mul_reg_l or Z.mul_reg_r. I need to check if `Z` implements `NZMulOrderProp`.

> By the way, it appears there are plenty of more lemmas specific to Z in https://github.com/coq/coq/blob/master/theories/ZArith/BinInt.v#L1281 which should either be generalized to Numbers or be deprecated.

Good point!. I filed https://github.com/coq/coq/issues/17606 to track it

**Comment by HaoYang670** [comment]
@coqbot run full ci

**Comment by Zimmi48** [comment]
Sorry, @HaoYang670, this coqbot command only works if you're a member of `@coq/contributors`. We should make coqbot provide feedback when it ignores it. Let me re-run it for you.

@coqbot run full CI

**Comment by SkySkimmer** [comment]
Not sure if CI failures are real, at least some of them are not so let's get a fresh run
@coqbot run full ci

@coq/stdlib-maintainers please take a decision on this PR instead of waiting another year

**Comment by andres-erbsen** [comment]
Let's merge if CI passes.

**Review by andres-erbsen — APPROVED** [review]

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Pull request merged**
