### PR TITLE
[ssr] import ssreflect test suite from math-comp

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by maximedenes — CHANGES_REQUESTED** [review]
Please move these tests to a dedicated `ssr` folder and remove the `ssr_` prefixes.

**Comment by Zimmi48** [comment]
> Please move these tests to a dedicated ssr folder and remove the ssr_ prefixes.

I fail to see the point. Especially given that some of them are using the `output/` infrastructure.

Unrelated: it is pretty uncommon to put copyright headers for test files. Especially given that tests often come from external bug reporters...

**Comment by maximedenes** [comment]
> I fail to see the point. Especially given that some of them are using the output/ infrastructure.

There was a bit offline discussion, sorry about that. My request was about the files in `success`, but maybe I can reformulate it: how do I know if `success` is the right place for these files, rather than, say, `failure`? Since I don't understand the semantics of these folder, I was suggesting to use a per-component approach, which is clear in the case of ssr. But maybe you can explain the semantics instead, @Zimmi48 ?

**Comment by herbelin** [comment]
> how do I know if success is the right place for these files, rather than, say, failure? Since I don't understand the semantics of these folders, 

The `failure` directory is from before the introduction of `Fail`, at a time where failure was technically observed by the return code of the coqtop executable. Since 56b3ad5, `failure` technically works like `success`. As far as I can judge, the difference nowadays seems a bit semantics and mostly historical. For instance, there are already 199 `Fail` in `success` and only `94` in `failure`. Your question suggests that it might be clearer to remove `failure` and move its contents to `success`. This is what I would support (unless someone is interested in maintaining it).

**Comment by maximedenes** [comment]
> The failure directory is from before the introduction of Fail, at a time where failure was technically observed by the return code of the coqtop executable. Since 56b3ad5, failure technically works like success. As far as I can judge, the difference nowadays seems a bit semantics and mostly historical. For instance, there are already 199 Fail in success and only 94 in failure. Your question suggests that it might be clearer to remove failure and move its contents to success. This is what I would support (unless someone is interested in maintaining it).

Thanks for the explanation. IMHO it would make sense to reorganize the files per-component way, to prepare the work for more systematic testing. @ejgallego has often promoted the idea of a unification test-suite inspired from Unicoq, for example.

**Comment by Zimmi48** [comment]
OK for the component solution for the "success/failure" part of the test suite.

**Comment by gares** [comment]
so, what do you want me to do? move most of the stuff to `test-suite/ssr/success/`?

**Comment by gares** [comment]
ping

**Comment by maximedenes** [comment]
why not just `test-suite/ssr`?

**Comment by gares** [comment]
done (I left the prerequisite file and the output one named `ssr_*`, but I've removed the `ssr_` prefix from the other names)

**Comment by gares** [comment]
@maximedenes can you merge this? I'd like to add some tests in #7236 and having this merged would give them a place to be

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
Where is the target that triggers those tests?

**Comment by gares** [comment]
good spot, I'll add one (not all subdirectories have one, the stm does...)

**Comment by maximedenes** [comment]
If you can rebase at the same time (even if there are no conflicts), it could make the CI results look better.

**Comment by gares** [comment]
Failures seem unrelated

**Pull request merged**
