### PR TITLE
Fix bug introduced in #18564 (deprecation of stdlib `map_length`)

### PR DESCRIPTION
**Pull request by proux01**
Fix bug introduced in https://github.com/coq/coq/pull/18564

### CODE REVIEW

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@herbelin congrats, CI confirms that this fixes metacoq

**Comment by herbelin** [comment]
Then probably no need to wait further. Thanks!

@coqbot merge now

**Review by herbelin — APPROVED** [review]
Obvious

**Comment by herbelin** [comment]
@coqbot merge now

**Pull request merged**
