### PR TITLE
Split the Reductionops machine from the cbn one

### PR DESCRIPTION
**Pull request by ppedrot**
The `cbn` tactic used the same reduction machine as the one used everywhere else, notably in unification and tactics. Unfortunately, a lot of code was specific to the refolding machinery only used in `cbn`, thus polluting the rest of the implementation. In particular, this complexity would prevent a lot of potential changes driven by performance considerations in unification, which is a critical part of the system.

The solution is simple but brutal: split those two implementations. While this looks like a lot of duplication and thus bad engineering-wise, it is actually making things much more self-contained. As a matter of fact, the simplicity of the refolding-free machine is obvious when considering the raw loc overhead introduced by this PR: a mere ~430 lines of code. Furthermore, additional cleanups are now in reach, which would make this overhead even smaller.

### CODE REVIEW

**Comment by ppedrot** [comment]
Before you ask for it, the bench only shows noise.
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1521.74 1538.89 -1.11 % │     4242050056541     4288652787603 -1.09 % │     6152264910165     6202064883005 -0.80 % │    1138740    1137460  +0.11 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1406.64 1421.87 -1.07 % │     3928208624108     3969771860680 -1.05 % │     6111141077788     6157445482372 -0.75 % │     841828     876492  -3.95 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  203.59  205.12 -0.75 % │      568773496531      572647332516 -0.68 % │      763155468597      769894743267 -0.88 % │     513960     516992  -0.59 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  648.83  653.12 -0.66 % │     1811720628413     1821774049642 -0.55 % │     2305428114013     2318987050033 -0.58 % │    1141428    1143620  -0.19 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   48.96   49.26 -0.61 % │      135909762004      136379112590 -0.34 % │      189460152994      189965744484 -0.27 % │     557288     557176  +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   73.69   74.14 -0.61 % │      202669098235      203355017038 -0.34 % │      266807723378      267584734801 -0.29 % │     652980     654812  -0.28 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  198.08  199.14 -0.53 % │      550668913099      552942009911 -0.41 % │      711687636820      714956627903 -0.46 % │     928392     927424  +0.10 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  101.73  102.27 -0.53 % │      288328843965      289645988077 -0.45 % │      387334528002      388925754434 -0.41 % │     498504     498332  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  163.08  163.85 -0.47 % │      453765239547      455858300232 -0.46 % │      637206007651      638967574342 -0.28 % │     811180     850412  -4.61 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4288.79 4308.65 -0.46 % │    11912952962022    11966243824131 -0.45 % │    19753965913362    19848610384260 -0.48 % │    2356008    2363856  -0.33 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  206.85  207.75 -0.43 % │      574275268739      575432528031 -0.20 % │      963333587293      967307518713 -0.41 % │    1115908    1114804  +0.10 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1247.84 1253.11 -0.42 % │     3477086261161     3495576094419 -0.53 % │     4933648557354     4960005853406 -0.53 % │    1823720    1819356  +0.24 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  596.42  598.93 -0.42 % │     1667429211039     1676420643411 -0.54 % │     2672920843527     2684144011874 -0.42 % │    3184852    3185776  -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-fiat-crypto-legacy │ 5898.35 5921.67 -0.39 % │    16421276043951    16482989113057 -0.37 % │    27916861099966    28009043707156 -0.33 % │    2410168    2375796  +1.45 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  144.84  145.35 -0.35 % │      403369653402      404728889069 -0.34 % │      537276526968      539035134848 -0.33 % │     612340     613944  -0.26 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  674.09  676.22 -0.31 % │     1881220695337     1885766491172 -0.24 % │     2632702952943     2645380675415 -0.48 % │    1041372    1038140  +0.31 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-sf-plf │   43.73   43.86 -0.30 % │      121623574501      122051281219 -0.35 % │      167953631559      168673886053 -0.43 % │     494968     494960  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  175.10  175.55 -0.26 % │      488064634857      488885025846 -0.17 % │      695311758887      697121843875 -0.26 % │     793388     793356  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   62.71   62.86 -0.24 % │      173736152275      174166272534 -0.25 % │      243718760735      244583865419 -0.35 % │     485692     483252  +0.50 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  569.14  570.28 -0.20 % │     1579532011146     1581666011424 -0.13 % │     2439749609437     2446218512067 -0.26 % │     910496     929404  -2.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2099.39 2103.55 -0.20 % │     5856792312590     5870579995743 -0.23 % │    11482900314375    11489805702450 -0.06 % │     952900     952596  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1346.32 1348.59 -0.17 % │     3752745177012     3758055889448 -0.14 % │     6707803011674     6725619371036 -0.26 % │    1299876    1300292  -0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4025.51 4029.74 -0.10 % │    11208807842359    11218797710804 -0.09 % │    21405863278049    21438667639642 -0.15 % │    1199280    1088676 +10.16 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │  992.44  993.30 -0.09 % │     2763992023940     2767330261136 -0.12 % │     4546334434261     4552938178503 -0.15 % │     931508     930684  +0.09 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   84.41   84.48 -0.08 % │      232215838825      232710080741 -0.21 % │      334560324385      335517593535 -0.29 % │     758560     756880  +0.22 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  262.04  262.18 -0.05 % │      730006984866      730256033420 -0.03 % │     1121728366036     1123747111961 -0.18 % │     788828     791244  -0.31 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1523.94 1524.05 -0.01 % │     4249592848745     4255222263824 -0.13 % │     6497274752776     6518195049910 -0.32 % │    1388032    1376832  +0.81 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  333.96  333.98 -0.01 % │      908639239718      911047063147 -0.26 % │     1467540154844     1472332193577 -0.33 % │     625276     630168  -0.78 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  115.80  115.69 +0.10 % │      319648972154      319894374969 -0.08 % │      415109698159      416809668404 -0.41 % │     538976     539108  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   49.34   49.10 +0.49 % │      134614021587      134837638862 -0.17 % │      175581565728      176122427806 -0.31 % │     566056     568904  -0.50 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   57.67   56.87 +1.41 % │      159391288464      158018572630 +0.87 % │      201964821165      202423110340 -0.23 % │     530580     534912  -0.81 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-performance-tests │   11.73   11.50 +2.00 % │       31953833089       31681605049 +0.86 % │       55052646740       54580119644 +0.87 % │     424156     410324  +3.37 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```

**Comment by gares** [comment]
The cbn machine is call by name. Do you plan to replace it (for unification for example) with the lazy one?

**Comment by ppedrot** [comment]
We cannot use a call-by-need machine because unification is sensitive to the syntactic form of the expressions. But indeed, using the kernel reduction with the call-by-name flags is a potential solution.

**Comment by gares** [comment]
Matita was keeping the original term and the eventually reduced by side effect one (in the env of the machine). When reducing further, the machine would use the latter. When unwinding or inspecting the machine, one would use the former.

Anyway, If we stay in call by name to avoid breaking things, then I vote for using the kernel one with appropriate flags. Or at least try. I don't like very much this PR as it reaches an undesirable intermediate step. If using the kernel machine does not work (for reasons to be discovered) then I may change my mind.

Just duplicating the code with no further plan seems a bit arbitrary to me. This is why I've asked.

**Comment by ppedrot** [comment]
There is an overhead to kernel reduction though, because of the back-and-forth conversion between representations. I remember having seen it in several experiments.

**Comment by SkySkimmer** [comment]
>While this looks like a lot of duplication and thus bad engineering-wise,

It's just separation of concerns and thus good engineering-wise.

**Comment by herbelin** [comment]
> There is an overhead to kernel reduction though, because of the back-and-forth conversion between representations. I remember having seen it in several experiments.

Eventually, we may think at replacing `constr` with a `fconstr`-based syntax 😉

**Comment by ppedrot** [comment]
@herbelin if Coq were written in a proper language, we could have a system of views and code generic on the underlying representation of terms. Maaaaaybe implicit modulars will help...

**Comment by herbelin** [comment]
I did not closely look at the PR, but is this leaning towards an "undesirable intermediate step (...) with no further plan" or towards a proper "separation of concerns" with "additional cleanups (...) in reach"?

**Comment by ppedrot** [comment]
As the totally unbiased author of the PR, I believe this is separation of concerns. Two thirds of the code for the Reductionops machine is about constant refolding, when it is only used in `cbn`.

**Comment by ppedrot** [comment]
Although this was not discussed in this thread, I must mention that @maximedenes was not very pleased at the idea of having one more reduction machine after this PR, since he'd have to reimplement the native array reduction there as well. As advocated in #11922, if we get both this PR and that one, it becomes very easy to merge the local and global Reductionops machines, which results in a net equilibrium in the number of reduction machines, while pushing all the complexity into `cbn`.

**Comment by herbelin** [comment]
Am I also understanding correctly that with something like coq/ceps#45, `cbn` would not be necessary anymore?

**Comment by gares** [comment]
> `cbn` would not be necessary anymore?

This is not quite true. It is true that global fixpoints need no refolding (horay!), but iota and delta step can still be interleaved and hence one may like some refolding to happen. A silly example is defining a function as the composition of two global fixpoints: you want simpl to evaluate, but possibly refold the composition. It seem more "equational" than before, but there is still some work for `simpl` IMO.

**Comment by herbelin** [comment]
@gares: `simpl` is sometimes able to refold several steps (though I would need time to find again an example) but I don't remember if `cbn` can do the same? Do you an example in mind? 

For instance, I tried:
```
Definition add1 n := n + 1. 
Parameter n  : nat.
Eval cbn in add1 (S n).
(* S (n + 1) *)
Eval simpl in add1 (S n).
(* add1 (S n) *)
```
But even if it is the case, I believe it would still be more efficient and more intuitive that such reduction is working as expected consistently for all reduction machines (including the lazy one), rather than adding tweaks to compensate more or less successfully what the official reduction rules of the underlying logic cannot do.

For instance, in the `add1` case above, it shouldn't be difficult to (eventually) let the kernel check that it is safe that some constants come with special unfolding rules, like `add1 (S n)` unfolds to `S (add1 n)` and `add1 0` unfolds to `1`, and `add1 n` for `n` a variable is blocked (while preserving at the level of the conversion that `add1 n` and `n + 1` are equal). Actually, what does Matita for such cases?

**Comment by gares** [comment]
I wrote simpl but I meant any implementation of the same idea.
To me simpl  does iota, with the liberty of Delta, and the hope of

**Comment by Zimmi48** [comment]
@ppedrot Should this still go into 8.12?

**Comment by ppedrot** [comment]
I don't really care since it's purely internal. If it's not merged in time, so be it.

**Review by maximedenes — COMMENTED** [review]
Quick question on this PR: if `Cbn` is now used only by the tactic of the same name, why keep it in the pretyper?

**Comment by ppedrot** [comment]
It could be very well moved to the `tactics/` folder indeed.

**Review by maximedenes — APPROVED** [review]

**Comment by ppedrot** [comment]
CI green!

**Pull request merged**
