### PR TITLE
Attempt to fix the bench after coq-core split

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1078834720

**Comment by ppedrot** [comment]
Seems to be working.

**Comment by ppedrot** [comment]
@SkySkimmer I don't think we have to wait for the bench to terminate, as witnessed by the current state the problem has been solved by this PR. I propose that you remove the draft status and that we merge this ASAP.

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Why did the job get interrupted?

**Comment by ppedrot** [comment]
I did it to free the bench for the other PR. It was not necessary to wait for full completion, the failure was only happening at the beginning.

**Comment by SkySkimmer** [comment]
>It was not necessary to wait for full completion, the failure was only happening at the beginning.

Except it looks like hott & co are failing

**Comment by SkySkimmer** [comment]
retry https://gitlab.com/coq/coq/-/jobs/1080461877

**Comment by ppedrot** [comment]
Probably for unrelated reasons, though. The opam packages likely need to be adapted, don't they?

**Comment by ppedrot** [comment]
@SkySkimmer It'd be more informative to run this locally rather than on the bench infrastructure, if you want to debug the opam installation.

**Comment by SkySkimmer** [comment]
~~~

┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │    2.51     2.54  -1.18 │    11218380321     11332034744  -1.00 │    22731182772     22730472330   0.00 │  248684   248540   0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-core │  105.09   106.02  -0.88 │   413334703571    409572408795   0.92 │   465877341460    466154883348  -0.06 │  262544   261756   0.30 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  209.03   209.94  -0.43 │   904603583087    908535067393  -0.43 │  1717482745467   1719512696488  -0.12 │ 3547892  3547880   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │   85.15    85.48  -0.39 │   389628668400    390729409498  -0.28 │   599757781380    599729729121   0.00 │  736484   736144   0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   26.80    26.89  -0.33 │   122127851771    122451755398  -0.26 │   187504969727    187516643779  -0.01 │  483720   482832   0.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │  705.24   707.16  -0.27 │  3216609573019   3226126834130  -0.30 │  4918468987799   4915022552687   0.07 │ 2981964  2971436   0.35 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  119.42   119.69  -0.23 │   541910162274    543008692200  -0.20 │   764819739632    764240232643   0.08 │  506232   506304  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-corn │  853.18   854.38  -0.14 │  3888734895068   3896240119173  -0.19 │  5929462154905   5928869168257   0.01 │  862960   862976  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 2826.47  2830.11  -0.13 │ 12855194366602  12870485303225  -0.12 │ 23532268095696  23519325778669   0.06 │ 2272864  2259896   0.57 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-stdlib │  382.21   382.69  -0.13 │  1588047973199   1586884673909   0.07 │  1398937568417   1398986422180  -0.00 │  574328   574356  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │  925.29   926.34  -0.11 │  4191151035459   4196547557498  -0.13 │  7279766010065   7279158662147   0.01 │ 2440160  2440504  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-lambda-rust │  713.24   713.28  -0.01 │  3255438671063   3257208126923  -0.05 │  5050369664557   5085589215523  -0.69 │ 3152288  3138472   0.44 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 1519.69  1519.67   0.00 │  6926390432963   6923411023491   0.04 │ 12238470134291  12233468396508   0.04 │ 3008212  2977576   1.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 2345.30  2344.29   0.04 │ 10713843443118  10705569836639   0.08 │ 21253974408436  21237802966446   0.08 │ 1011432  1009264   0.21 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │  594.35   593.83   0.09 │  2723175014922   2721500424428   0.06 │  4691072601261   4690917471714   0.00 │  984728   983476   0.13 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │   94.69    94.54   0.16 │   433051875667    432199905827   0.20 │   680437610668    680369542758   0.01 │  638672   638740  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   32.06    31.99   0.22 │   145052797616    145057198878  -0.00 │   208776718233    208207847852   0.27 │  467912   469488  -0.34 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │   85.64    85.43   0.25 │   387995651523    386973401764   0.26 │   627195220190    625744911557   0.23 │ 2984312  2965764   0.63 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │   75.86    75.56   0.40 │   346032296320    345072961559   0.28 │   493770050895    493732818569   0.01 │  540940   540640   0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  470.15   468.27   0.40 │  2138010274245   2127869335299   0.48 │  3544616401580   3533395994321   0.32 │ 2974356  2960460   0.47 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  283.93   282.40   0.54 │  1287275181854   1279587225236   0.60 │  1748171578789   1732457868474   0.91 │ 1108464  1108380   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  124.79   124.10   0.56 │   571460470163    568432699505   0.53 │   949497337297    949440270175   0.01 │  675360   677008  -0.24 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │  793.74   787.79   0.76 │  3617298328787   3590498370017   0.75 │  5679879868325   5663951608571   0.28 │ 1002356  1003860  -0.15 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  401.78   398.16   0.91 │  1826513928734   1810882618774   0.86 │  2941399081654   2925266574673   0.55 │  998304   998304   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  359.26   355.96   0.93 │  1616485883824   1602187884535   0.89 │  2627456100473   2614565941936   0.49 │ 2913384  2913088   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   30.21    29.92   0.97 │   136730686527    135768212003   0.71 │   192843054828    192423467874   0.22 │  517372   517260   0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │   82.57    81.58   1.21 │   375544296342    371519091296   1.08 │   505043625167    504469363829   0.11 │  833420   833236   0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  116.65   115.00   1.43 │   530324806506    522976650721   1.41 │   935425528243    920218399813   1.65 │  754416   754388   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │   65.83    64.17   2.59 │   279154139953    271557561733   2.80 │   402023857104    386292528163   4.07 │  483320   485300  -0.41 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │   47.13    45.47   3.65 │   211656958817    204651531105   3.42 │   325375527185    309585700876   5.10 │  762468   762576  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   40.51    38.97   3.95 │   182613685449    175684411582   3.94 │   256052457871    240627524266   6.41 │  565180   565108   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   36.41    34.79   4.66 │   163334645289    156424851361   4.42 │   221618423828    206634196229   7.25 │  524488   524392   0.02 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
~~~
It seems there is a pretty reliable fake slowdown on the smaller developments. Could be something stupid like opam caching the source download for all I know.

**Comment by SkySkimmer** [comment]
I paused the new machines until this gets checked out.

**Pull request merged**
