### PR TITLE
Disable warning 40

### PR DESCRIPTION
**Pull request by SkySkimmer**
It keeps getting in my way and AFAICT it provides no benefit.
Disabling it while working on the lean importer was a great experience.

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
I dunno, we already discussed this in https://github.com/coq/coq/pull/9400 and IIRC [cannot find the discussion now] some OCaml devs and myself got convinced the warning is pretty legitimate as it is really weird that OCaml allows you to refer to things that are not in scope.

Having different scoping for constructors and values seems kinda weird; also this could have strange effects in the (very far) future of not allowing implicit transitive deps in the OCaml ecosystem.

**Comment by SkySkimmer** [comment]
I wasn't convinced back then, and after trying it out I am now convinced that we should disable the warning.

**Comment by ejgallego** [comment]
More relevant discussion https://github.com/ocaml/ocaml/issues/6000

**Comment by ejgallego** [comment]
I've added this to next Coq call.

**Comment by ppedrot** [comment]
I don't agree with this PR. This warning is one of the few useful ones from the set of annoying warnings in the kernel. I actually don't understand why OCaml is so lax about constructors. Until recently (4.x?) it was not the case, and that was much better IMO.

**Comment by ejgallego** [comment]
> I actually don't understand why OCaml is so lax about constructors.

Indeed that feature is quite strange as for example if breaks substitution and other stuff; but indeed the discussion is tricky so I suggest we allocate some time in the call, while I am in favor of warning 40 I can also understand Gaëtan's position.

> This warning is one of the few useful ones from the set of annoying warnings in the kernel.

@ppedrot if you think that the warning set should be modified indeed please suggest so.

**Comment by SkySkimmer** [comment]
Rejected in call

**Pull request closed without merging**
