### PR TITLE
Remove broken `Solve Obligation` command.

### LINKED ISSUE #16841: `Solve Obligation` does not count obligations from 1 and does not check bounds.
Fix incoming.

#### Description of the problem

```coq
Require Import Program Arith.

Program Definition id (n : nat) : { x : nat | x = n } :=
  if dec (leb n 0) then 0
  else S (pred n).
(* Works:
Obligation 1.
now symmetry; apply Nat.le_0_r, leb_complete.
Qed.
*)
Solve Obligation 0 with now symmetry; apply Nat.le_0_r, leb_complete.
```

Also raises anomalies when passed with a number that's too high.

#### Coq Version

8.6-8.16

### PR DESCRIPTION
**Pull request by Zimmi48**
Closes  #16841.

- [ ] Added / updated **test-suite**.

- [x] Added **changelog**.
- [x] Added / updated **documentation**.

- [ ] Opened **overlay** pull requests.

### CODE REVIEW

**Comment by Zimmi48** [comment]
`Solve Obligation` was undocumented in 8.16, so this is why I think this is OK to fix it in a backward (and forward) incompatible way. But let the CI confirm.

**Comment by SkySkimmer** [comment]
No idea wtf is going on here

**Comment by Zimmi48** [comment]
This command does not look important enough to deserve spending more time on debugging it. I'll remove it instead.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
