### PR TITLE
Fix caching in Tacred.reference_eval and cache univ poly

### LINKED ISSUE #18490: Changing `simpl never` not respected with alias
Remnant of #13428 
~~~coq
Definition plus' := plus.

Definition foo := Eval simpl in plus' 1 2.

Arguments plus : simpl never.

Lemma test P : P 3 -> P (plus' 1 2).
Proof.
intros p3.
simpl.
(* goal is P 3 *)
~~~
This is because `Definition foo` precomputed the unfolding of `plus'` with `plus` not simpl never and cached it in a global table https://github.com/coq/coq/blob/068232d2c884b6ac829d800e417682ba57b3ca6a/pretyping/tacred.ml#L177

In other words the caching at https://github.com/coq/coq/blob/068232d2c884b6ac829d800e417682ba57b3ca6a/pretyping/tacred.ml#L352-L362 is not correct when `allowed_reds` changes.

### PR DESCRIPTION
**Pull request by SkySkimmer**
We replace the global cache with a cache per invocation of simpl.

Since the cache is now local there is no need to avoid putting data from univ poly constants in it.

Fix #18490

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
previous bench interrupted due to finding a bug

@coqbot bench

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer I think this is worth backporting to 8.19, so I'm putting this in the milestone.

**Comment by ppedrot** [comment]
@SkySkimmer can you 1. confirm you're fine with the current version and 2. add a test for the bug fixed? I'll merge afterwards.

**Comment by SkySkimmer** [comment]
Test added, ready to merge.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
