### PR TITLE
Fix stage of ltac2 notation interp map (Tac2env.ltac_notations)

### LINKED ISSUE #772: Anomaly "Uncaught exception Not_found." when trying to use Ltac2
On this file:
```coq
From Ltac2 Require Import Ltac2.

Goal True /\ True.
  split; exact I.
Qed.
```

I get the following error:
```
Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/.
Raised at HMap.Make.find in file "clib/hMap.ml", line 361, characters 31-46 Called from Ltac2_plugin__Tac2env.interp_notation in file "plugins/ltac2/tac2env.ml" (inlined), line 126, characters 25-54
Called from Ltac2_plugin__Tac2intern.expand_notation in file "plugins/ltac2/tac2intern.ml", line 1093, characters 8-34
Called from Ltac2_plugin__Tac2intern.intern_rec in file "plugins/ltac2/tac2intern.ml", line 1228, characters 10-36
Called from Ltac2_plugin__Tac2intern.intern_rec in file "plugins/ltac2/tac2intern.ml", line 1236, characters 17-39
Called from Ltac2_plugin__Tac2intern.intern in file "plugins/ltac2/tac2intern.ml", line 1554, characters 15-36
Called from Ltac2_plugin__Tac2entries.ltac2_interp in file "plugins/ltac2/tac2entries.ml", line 1233, characters 15-40
Called from ComTactic.solve in file "vernac/comTactic.ml" (inlined), line 58, characters 10-22
Called from Ltac2_plugin__Tac2entries.call in file "plugins/ltac2/tac2entries.ml", line 1242, characters 2-71
Called from Vernactypes.vtmodifyproof.(fun) in file "vernac/vernactypes.ml", line 185, characters 32-47
Called from Vernactypes.typed_vernac.(fun) in file "vernac/vernactypes.ml", line 170, characters 65-71
Called from Vernactypes.run.(fun) in file "vernac/vernactypes.ml", line 164, characters 15-32
Called from Vernactypes.combine_runners.(fun) in file "vernac/vernactypes.ml", line 126, characters 16-23
Called from Vernactypes.OpaqueAccess.runner.(fun) in file "vernac/vernactypes.ml", line 114, characters 30-34
Called from Vernactypes.combine_runners.(fun) in file "vernac/vernactypes.ml", line 125, characters 14-100
Called from Vernactypes.combine_runners.(fun) in file "vernac/vernactypes.ml", line 126, characters 16-23
Called from Vernactypes.Proof.runner.(fun) in file "vernac/vernactypes.ml", line 72, characters 19-22
Called from Vernactypes.combine_runners.(fun) in file "vernac/vernactypes.ml", line 125, characters 14-100
Called from Vernactypes.Prog.runner.(fun) in file "vernac/vernactypes.ml", line 27, characters 30-34
Called from Vernactypes.combine_runners.(fun) in file "vernac/vernactypes.ml", line 124, characters 12-173
Called from Vernactypes.combine_runners.(fun) in file "vernac/vernactypes.ml", line 124, characters 12-173
Called from Vernactypes.run in file "vernac/vernactypes.ml", line 163, characters 14-96
Called from Vernacinterp.interp_expr in file "vernac/vernacinterp.ml", line 120, characters 60-157
Called from Vernacinterp.interp_control.(fun) in file "vernac/vernacinterp.ml", line 153, characters 24-126
Called from Flags.with_modified_ref in file "lib/flags.ml", line 17, characters 14-17 Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Vernacinterp.interp_gen in file "vernac/vernacinterp.ml", line 197, characters 16-41 Re-raised at Exninfo.iraise in file "clib/exninfo.ml", line 81, characters 4-38
Called from Dm__ExecutionManager.interp_ast in file "dm/executionManager.ml", line 156, characters 13-46
```

Coq version: https://github.com/coq/coq/commit/ed9fe8e2351ff59f662c3950c1cb07813db312bd.
Language server version: https://github.com/coq-community/vscoq/commit/d37fd297e509ee41e07bbad07a4e497cbb77d485.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix coq-community/vscoq#772

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Not sure we have a good way to test stage issues in our test suite.

**Comment by ejgallego** [comment]
> Not sure we have a good way to test stage issues in our test suite.

I think testing this kind of stuff is always futile; a type-safe API may be the right way to do this.

**Comment by ppedrot** [comment]
I don't understand the invariants of the phase distinction, but why is this summary not synterp when the corresponding object inTac2Notation is?

**Comment by SkySkimmer** [comment]
This is the inTac2NotationInterp object no?

**Comment by gares** [comment]
Thanks @SkySkimmer

**Comment by gares** [comment]
I believe a simple compiler not using the stm can test these things quite easily, it is just the matter of parsing the entire file and then interpreting it.

**Comment by ppedrot** [comment]
> This is the inTac2NotationInterp object no?

Indeed, and that one is effectively not synterp. I guess this is OK then. (We should probably enforce this by the type system as suggested by @ejgallego...)

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ejgallego** [comment]
> I believe a simple compiler not using the stm can test these things quite easily, it is just the matter of parsing the entire file and then interpreting it.

Having some test case like that would be nice, however it seems to me that there are combinatorial number of cases to test, including arbitrary freeze/unfreeze, so that would be far from complete.

> We should probably enforce this by the type system as suggested by @ejgallego...

I have lost the count of the issues and time spent on bugs due to the parsing split optimization, so indeed it seems to me that in the medium term we would all benefit from this.

**Comment by gares** [comment]
I'd be happy to use types, but I really don't see how.

**Comment by ejgallego** [comment]
> I'd be happy to use types, but I really don't see how.

As we do for proofs, have commands declare what they do on the state, and pack them. That would have some other great effects as maybe getting closer to having the printer functional.

I would have just packed the commands as I suggested in my initial reviews.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
