### PR TITLE
[dune] [coqdoc] Install coqdoc.sty also in share/texmf

### PR DESCRIPTION
**Pull request by ejgallego**
Noticed by @gares that we did this in the make install system.

### CODE REVIEW

**Comment by Zimmi48** [comment]
I have no idea what this installed file is about, but I'm willing to blindly merge this if people think it's a good idea.

**Comment by ejgallego** [comment]
Let's cc @gares @treinen who may know about where this file should go in the FHS.

**Comment by treinen** [comment]
On Tue, Apr 06, 2021 at 11:11:04AM -0700, Emilio Jesús Gallego Arias wrote:
> Let's cc @gares @treinen who may know about where this file should go in the
> FHS.

The FHS will propbably tell you that when the software is part of the
operating system then coqdoc.sty should go somewhere under
/usr/share/tex*, and if it is locally installed by the sysadmin
then somewhere under /usr/local/share/tex*.

If you want to know what subdirectory of the tex* directory then you
probably have to consult the documentation of the tex distribution.

-Ralf.

**Review by Zimmi48 — APPROVED** [review]
This is indeed the default location for installing the "Coqdoc LaTeX file" according to the output of `./configure` run without parameters.

@coqbot merge now

**Pull request merged**
