### PR TITLE
Simplify hint pattern handling

### PR DESCRIPTION
**Pull request by ppedrot**
We add a few static invariants and factorize code that were performing slightly differently for no reason.

Overlay:
- https://github.com/lukaszcz/coqhammer/pull/75

### CODE REVIEW

**Review by mattam82 — APPROVED** [review]
Looks like a fine refactoring/cleanup to me.

**Comment by ppedrot** [comment]
@mattam82 what's this waiting for to be merged?

**Comment by ppedrot** [comment]
@mattam82 ping

**Comment by mattam82** [comment]
The overlay did not work?

**Comment by ppedrot** [comment]
There was a race with another PR of mine, I'll rebase first.

**Comment by ppedrot** [comment]
@mattam82 CI green!

**Comment by mattam82** [comment]
There was one overlay on coq-hammer

**Comment by SkySkimmer** [comment]
>There was one overlay on coq-hammer

As assignee you're supposed to tell them to merge

**Comment by mattam82** [comment]
Well, it's merged now.

**Pull request merged**
