### PR TITLE
Fix bug #5377: @? patterns broken.

### PR DESCRIPTION
**Pull request by ppedrot**
See https://coq.inria.fr/bugs/show_bug.cgi?id=5377.

### CODE REVIEW

**Comment by ppedrot** [comment]
This patch seems to have broken fiat-crypto and fiat-parsers. Not sure why though...

**Comment by JasonGross** [comment]
Thanks!  Can you explain (here or on the bug tracker) what the issue was, and how what the changes do?

I'm surprised that it broke fiat-parsers, though I suppose I stopped testing it against 8.4 a while back.  I'm not surprised it broke fiat-crypto; it's entirely possible that we're accidentally taking advantage of the broken behavior.  (Alternatively, we use open terms, and it looks like you changed something with open terms?)  For example, I recently hit an issue where the abstracted variables in a `?@` pattern were abstracted in reverse(!), and the variables in the open term were similarly reversed, in such a way that I could build and pose an ill-typed term in Ltac that wouldn't be caught until `Defined `.  (Might this fix that issue too?)

**Comment by ppedrot** [comment]
@JasonGross The criterion for validity of λ-abstractions was just completely crazy.  Furthermore there were also lifting issues that could produce wrong DeBruijn indices. I don't know under the influence of which drug I wrote that code. This code now looks correct and will probably fix your errors, hopefully.

Indeed, if you take advantage of broken patter-matching in your developments, it may explain that. If you have time, could you try to guess if this was the case?

**Comment by JasonGross** [comment]
If you can point me to the lines where the pattern match is written that used to work and no longer does (or just to the proof that breaks and what the error message is), I'll take a look later today; otherwise I'll plan to take a look tomorrow.

**Comment by ppedrot** [comment]
The first error is the following:
```
COQC src/Compilers/TestCase.v
File "./src/Compilers/TestCase.v", line 65, characters 11-75:
Ltac call to "reify_abs" failed.
Error: No matching clauses for match.
```
I had a look, and it was not caused by a failing second-order pattern-matching, but rather because the term produced by the reification procedure had not the right form. Where this starts diverging, I have no idea.

**Comment by JasonGross** [comment]
Oooh, I bet this is related to a bug that I haven't yet tracked down where reification is sensitive to binder names (which I thought was supposed to be impossible in Ltac)

**Comment by JasonGross** [comment]
I'll take a look tomorrow

**Comment by JasonGross** [comment]
@ppedrot Here is code that works (correctly, IMO) in v8.6, but fails in this branch, which is the source of the reification failure:
```coq
Goal True.
  let c := lazymatch constr:(fun (T : nat -> Type) (y : nat) (_ : T y) => y) with
           | fun _ y _ => @?C y => C
           end in
  pose c.
```

**Comment by JasonGross** [comment]
Here is code that worked (correctly, IMO) in 8.6, but fails in this branch (part of the list facts failure in fiat-parsers):
```coq
Goal (forall x : nat, x = x -> x = x \/ x = x) -> True.
  intro.
  lazymatch goal with
  | [ H : forall y, @?P y -> @?P y \/ _ |- _ ]
    => clear H
  end.
```

**Comment by JasonGross** [comment]
Here is code that works (correctly) in v8.6 which fails in this branch, making multiple `@?` patterns unusable for me:
```coq
Goal (forall x : nat, x = x -> x = x \/ x = x) -> True.
  intro.
  lazymatch goal with
  | [ H : forall y, @?P y -> @?Q y \/ _ |- _ ]
    => idtac
  end.
```

**Comment by JasonGross** [comment]
Am I running the right version of this code?  It seems like this does not fix the extremely close cousin on 5377:
```coq
$ ../coq/bin/coqtop
Welcome to Coq jgross-Leopard-WS:/home/jgross/Documents/repos/coq,fix-5377 (228dd63101e9e0500add59ca4120e85cdb1da750)

Coq < Goal (forall (x : nat), x = x -> x = x) -> True.
1 subgoal
  
  ============================
  (forall x : nat, x = x -> x = x) -> True

Unnamed_thm < intro
Unnamed_thm < .
1 subgoal
  
  H : forall x : nat, x = x -> x = x
  ============================
  True

Unnamed_thm < match goal with H : forall x, _ -> @?P x |- _ => idtac end.
Toplevel input, characters 0-59:
> match goal with H : forall x, _ -> @?P x |- _ => idtac end.
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: No matching clauses for match.

Unnamed_thm < 
```
or, to make it look more like 5377:
```coq
Axiom eq : forall {T} (_ : T), Prop.
Goal forall _ : (forall t (_ : eq t) (x : t), eq x), Prop.
  intro.
  lazymatch goal with
  | [ H : forall t (_ : eq t) x, _ |- _ ]
    => idtac H
  end.
  lazymatch goal with
  | [ H : forall t _ x, @?P t x |- _ ]
    => idtac
  end.
Admitted.
```

**Comment by ppedrot** [comment]
@JasonGross Right, this should now be fixed. I wouldn't be sure until everything compiles, because with DeBruijn indices you can never be sure...

**Comment by ppedrot** [comment]
Sorry, forgot to commit everything!

**Comment by maximedenes** [comment]
@JasonGross Can you confirm that your examples work fine now?

**Comment by JasonGross** [comment]
If Travis says that fiat-crypto and fiat-parsers build, then I don't think this breaks anything new, and it fixes incorrect behavior, so I have no objections to merging it.  On the other hand, I still have an example with lifting(?) produces incorrect DeBruijn indices that this patch does not fix; let me see if I can get a small test case from that.

**Comment by JasonGross** [comment]
Minimized to [bug #5486](https://coq.inria.fr/bugs/show_bug.cgi?id=5486)... but this seems to have more to do with function application than with `@?` patterns.

**Pull request merged**
