### PR TITLE
Rocqify the checker.

### PR DESCRIPTION
**Pull request by ppedrot**
This commit only touches comments and internal definitions. We do not attempt to modify user messages related to the name of the binaries nor to fiddle with the dune library names.

### CODE REVIEW

**Review by proux01 — APPROVED** [review]

**Comment by ppedrot** [comment]
I have no idea why dpdgraph output changed, it seems very unlikely it's related to this PR.

**Comment by proux01** [comment]
Yeah, that puzzles me too, but it's not happening on master apparently?

**Comment by SkySkimmer** [comment]
Rerunning the job made it work, let's blame bitflips

**Comment by ppedrot** [comment]
@proux01 CI green.

**Comment by proux01** [comment]
@coqbot merge now

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
