### PR TITLE
Fix #7836: tools/inferior-coq.el uses next-line instead of forward-line.

### LINKED ISSUE #7836: tools/inferior-coq.el uses next-line instead of forward-line
#### Version

8.8.0

#### Description of the problem

In inferior-coq.el, we see:

```elisp
(defun coq-send-line ()
  "Send the current line to the Coq process."
  (interactive)
  (save-excursion
    (end-of-line)
    (let ((end (point)))
      (beginning-of-line)
      (coq-send-region (point) end)))
  (next-line 1))
```

`next-line` is for interactive use only, and the proper function to use is `forward-line`. Because of this, error messages are now printed during initialization in emacs 26, which is rather irritating.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** bug fix

Fixes / closes #7836

### CODE REVIEW

**Comment by Zimmi48** [comment]
@ejgallego @SkySkimmer or @Matafou would you like to be the owner for this PR? I'm giving random names of Emacs-knowledgeable persons.

**Comment by Matafou** [comment]
yeah why not me.

**Comment by Zimmi48** [comment]
Thanks!

**Review by Matafou — APPROVED** [review]
obviously OK.

**Comment by Matafou** [comment]
I will merge this unless @cpitclaudel has something to say against it.

**Review by ejgallego — APPROVED** [review]

**Comment by cpitclaudel** [comment]
Looks fine

**Comment by Matafou** [comment]
Ho yes sorry I have to merge.

Not used to the new way of doing things.
I will do the merge.
P.

**Comment by Zimmi48** [comment]
Maybe time to read again the merging doc? ;-)
https://github.com/coq/coq/blob/master/dev/doc/MERGING.md

**Comment by Zimmi48** [comment]
Thanks!

**Comment by Matafou** [comment]
indeed, I need that each time, I don't merge often enough to remember.
Should be ok now.

**Pull request merged**
