### PR TITLE
Zify: replace local definitions by equations

### PR DESCRIPTION
**Pull request by vbgl**
This also makes the `lia` tactic stronger.

### CODE REVIEW

**Comment by Zimmi48** [comment]
This enhancement should be backported to 8.9 since this is to cover a use case that was covered by `romega`.

**Review by fajb — APPROVED** [review]
I can't think of any situation where this could produce a regression.

For me, this is fine.

**Comment by vbgl** [comment]
CompCert and VST have been updated to accommodate for this change; this PR is thus ready to merge.

**Comment by herbelin** [comment]
Assignee should normally be @fajb...

**Comment by Zimmi48** [comment]
@thery Please do not use GitHub's merge button. It breaks automation that is assuming that you are using the merge script. If you have forgotten about it, re-reading https://github.com/coq/coq/blob/master/dev/doc/MERGING.md cannot hurt.

**Comment by ejgallego** [comment]
@Zimmi48 can't we just disable the GitHub merge button?

**Comment by thery** [comment]
@Zimmi48 sorry about that, got already scolded by @maximedenes ;-)

**Comment by Zimmi48** [comment]
>can't we just disable the GitHub merge button?

@ejgallego Unfortunately, that is not something that GitHub allows even if it is a very common feature-request. I invented a trick to still make it impossible to use it though: https://github.com/Zimmi48/certified-origin
But it is quite complex to use as it would require a push script that needs to be parametrized with a personal access token.
So in fact, the easiest way out, I think would be to make @coqbot the only one allowed to merge and the developers call it through a comment. This would anyways be a good first step in putting in place a bors-like merging process (coq/bot#18) so I'll work on this.

**Pull request merged**
