### PR TITLE
ci-wrapper: fix OSTYPE = darwin check on systems which include version info

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by herbelin** [comment]
Do we need a CI?

**Comment by SkySkimmer** [comment]
Not much point when we don't run ci-wrapper on any osx runner

**Comment by herbelin** [comment]
So, merging w/o needing much delay?

**Comment by SkySkimmer** [comment]
@herbelin please merge

**Comment by herbelin** [comment]
@coqbot merge now

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
@coqbot merge now

**Pull request merged**
