### PR TITLE
Mini-update of version history with recent changes.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** documentation

I find convenient to have this kind of information at hand (e.g. I needed it to get the global picture for critical bugs).

### CODE REVIEW

**Comment by herbelin** [comment]
I don't think that the credits chapter has all the information that the version-history file has. And if it has, it certainly does not have it in the same synthetic way.

I'm anyway ok to continue to maintain the file as long as it is useful for me.

**Review by Zimmi48 — APPROVED** [review]
OK then.

Do you want to keep it a `.tex` file though?

**Comment by herbelin** [comment]
Is there a way to render the tables and tabulations nicely in .md? If yes, we can move it to markdown.

**Comment by Zimmi48** [comment]
Tables, yes: https://help.github.com/articles/organizing-information-with-tables/

**Comment by Zimmi48** [comment]
@herbelin Shoud I merge this now and leave the conversion for later?

**Comment by herbelin** [comment]
It'd be preferable, yes, if ok for you.

**Pull request merged**
