### PR TITLE
Fix #8361: dependency states: camldevfiles

### LINKED ISSUE #8361: Coq no longer builds on master (`make states` fails)
#### Version

master (bf1446294dba45d3ea9b7bb39d2fc96617848c03)

#### Operating system

Linux

#### Description of the problem

I discovered today that HoTT's CI is broken because master does not build.  Here is the [log](https://api.travis-ci.org/v3/job/422600637/log.txt):
```
$ ./configure -prefix /usr/local
You have OCaml 4.02.3. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.03. Good!
You have native-code compilation. Good!
Warning: No such directory '/usr/lib/ocaml/lablgtk2' (in OCaml library).
LablGtk2 not found:
=> no CoqIde will be built.

  Architecture                : Linux
  Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath /usr/local/lib/coq/kernel/byterun
  Other bytecode link flags   : 
  OCaml version               : 4.02.3
  OCaml binaries in           : /usr/bin/
  OCaml library in            : /usr/lib/ocaml
  OCaml flambda flags         : 
  Camlp5 version              : 7.03
  Camlp5 binaries in          : /home/travis/.opam/system/bin
  Camlp5 library in           : /home/travis/.opam/system/lib/camlp5
  Native dynamic link support : true
  CoqIde                      : no
  Documentation               : None
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
  Coq web site                : http://coq.inria.fr/
  Bytecode VM enabled         : true
  Native Compiler enabled     : true

  Paths for true installation:
  - the Coq binaries will be copied in /usr/local/bin
  - the Coq library will be copied in /usr/local/lib/coq
  - the Coqide configuration files will be copied in /usr/local/etc/xdg/coq
  - the Coqide data files will be copied in /usr/local/share/coq
  - the Coq man pages will be copied in /usr/local/share/man
  - the Coq documentation will be copied in /usr/local/share/doc/coq
  - the Coqdoc LaTeX files will be copied in /usr/local/share/texmf/tex/latex/misc

If anything is wrong above, please restart './configure'.

*Warning* To compile the system for a new architecture
          don't forget to do a 'make clean' before './configure'.
$ make states tools coqlight plugins grammar/grammar.cma
rm -f  
make: Circular .merlin.in <- submake dependency dropped.
cp -a ".merlin.in" ".merlin"
make: Circular ide/.merlin <- submake dependency dropped.
make: Circular plugins/.merlin <- submake dependency dropped.
make: Circular META.coq.in <- submake dependency dropped.
cp -a "META.coq.in" "META.coq"
mkdir bin
make --warn-undefined-variable --no-builtin-rules -f Makefile.build states tools coqlight plugins grammar/grammar.cma
make[1]: Entering directory `/home/travis/build/HoTT/HoTT/coq-HoTT'
OCAMLC    clib/segmenttree.mli
OCAMLOPT  clib/segmenttree.ml
OCAMLC    clib/segmenttree.ml
OCAMLC    clib/unicodetable.ml
OCAMLOPT  clib/unicodetable.ml
OCAMLC    clib/unicode.mli
OCAMLOPT  clib/unicode.ml
OCAMLC    clib/unicode.ml
OCAMLC    clib/minisys.ml
OCAMLOPT  clib/minisys.ml
OCAMLC    tools/coqdep_lexer.mli
OCAMLLEX  tools/coqdep_lexer.mll
314 states, 4454 transitions, table size 19700 bytes
2927 additional bytes used for bindings
OCAMLOPT  tools/coqdep_lexer.ml
OCAMLC    tools/coqdep_common.mli
OCAMLOPT  tools/coqdep_common.ml
OCAMLC    tools/coqdep_boot.ml
OCAMLOPT  tools/coqdep_boot.ml
OCAMLBEST -o bin/coqdep_boot
COQDEP    VFILES
sed -n -e '/^  /s/ \([A-Z]\)/ \&\&coq_lbl_\1/gp' \
               -e '/^}/q' kernel/byterun/coq_instruct.h > "kernel/byterun/coq_jumptbl.h" || (RV=$?; rm -f "kernel/byterun/coq_jumptbl.h"; exit ${RV})
CCDEP     kernel/byterun/coq_memory.c
CCDEP     kernel/byterun/coq_values.c
CCDEP     kernel/byterun/coq_fix_code.c
CCDEP     kernel/byterun/coq_interp.c
OCAMLLEX  tools/ocamllibdep.mll
14 states, 417 transitions, table size 1752 bytes
OCAMLC    tools/ocamllibdep.ml
OCAMLOPT  tools/ocamllibdep.ml
OCAMLBEST -o bin/ocamllibdep
OCAMLC    coqpp/coqpp_ast.mli
OCAMLYACC  coqpp/coqpp_parse.mly
make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
OCAMLC    coqpp/coqpp_parse.mli
OCAMLC    coqpp/coqpp_parse.ml
OCAMLLEX  coqpp/coqpp_lex.mll
133 states, 7508 transitions, table size 30830 bytes
OCAMLC    coqpp/coqpp_lex.ml
OCAMLC -a bin/coqpp
OCAMLLEX  ide/utf8_convert.mll
15 states, 827 transitions, table size 3398 bytes
OCAMLLEX  ide/config_lexer.mll
30 states, 1657 transitions, table size 6808 bytes
6052 additional bytes used for bindings
OCAMLLEX  ide/protocol/xml_lexer.mll
80 states, 774 transitions, table size 3576 bytes
OCAMLLEX  ide/coq_lex.mll
97 states, 1352 transitions, table size 5990 bytes
OCAMLLEX  tools/coqdoc/cpretty.mll
2654 states, 8247 transitions, table size 48912 bytes
OCAMLLEX  tools/coqwc.mll
244 states, 858 transitions, table size 4896 bytes
COQPP   toplevel/g_toplevel.mlg
COQPP   plugins/omega/g_omega.mlg
COQPP   plugins/cc/g_congruence.mlg
COQPP   plugins/nsatz/g_nsatz.mlg
COQPP   plugins/btauto/g_btauto.mlg
COQPP   plugins/rtauto/g_rtauto.mlg
COQPP   plugins/quote/g_quote.mlg
COQPP   plugins/micromega/g_micromega.mlg
COQPP   plugins/romega/g_romega.mlg
COQPP   plugins/ltac/g_eqdecide.mlg
COQPP   plugins/ltac/coretactics.mlg
COQPP   plugins/ltac/g_tactic.mlg
COQPP   parsing/g_prim.mlg
COQPP   parsing/g_constr.mlg
COQPP   vernac/g_vernac.mlg
COQPP   vernac/g_proofs.mlg
tr -d "\r" < kernel/byterun/coq_instruct.h | sed -n -e '/^enum/p' -e 's/,//g' -e '/^  /p' | \
	awk -f kernel/make-opcodes > "kernel/copcodes.ml" || (RV=$?; rm -f "kernel/copcodes.ml"; exit ${RV})
OCAMLLIBDEP  plugins/MLLIBFILES plugins/MLPACKFILES
OCAMLC -c grammar/q_util.mli
OCAMLC -c -pp grammar/q_util.mlp
OCAMLC -c -pp grammar/argextend.mlp
OCAMLC -c -pp grammar/tacextend.mlp
OCAMLC -c -pp grammar/vernacextend.mlp
Testing grammar/grammar.cma
OCAMLC -a grammar/grammar.cma
CAMLP5O   plugins/extraction/g_extraction.ml4
CAMLP5O   plugins/ssrmatching/g_ssrmatching.ml4
CAMLP5O   plugins/setoid_ring/g_newring.ml4
CAMLP5O   plugins/firstorder/g_ground.ml4
CAMLP5O   plugins/ssr/ssrvernac.ml4
CAMLP5O   plugins/ssr/ssrparser.ml4
Redundant [TYPED AS] clause in [ARGUMENT EXTEND ssrindex].
CAMLP5O   plugins/funind/g_indfun.ml4
CAMLP5O   plugins/ltac/g_obligations.ml4
CAMLP5O   plugins/ltac/g_class.ml4
CAMLP5O   plugins/ltac/profile_ltac_tactics.ml4
CAMLP5O   plugins/ltac/g_rewrite.ml4
CAMLP5O   plugins/ltac/extraargs.ml4
CAMLP5O   plugins/ltac/g_ltac.ml4
CAMLP5O   plugins/ltac/g_auto.ml4
CAMLP5O   plugins/ltac/extratactics.ml4
CAMLP5O   plugins/derive/g_derive.ml4
OCAMLDEP  plugins/MLFILES plugins/MLIFILES
OCAMLLIBDEP  MLLIBFILES MLPACKFILES
CAMLP5O   ide/coqide_main.ml4
CAMLP5O   parsing/cLexer.ml4
OCAMLDEP  MLFILES MLIFILES
cp -a kernel/names.mli checker/names.mli
sed -i.bak '1i(* AUTOGENERATED FILE: DO NOT EDIT *)\n\n\n\n\n\n\n\n' checker/names.mli && rm checker/names.mli.bak
cp -a kernel/names.ml checker/names.ml
sed -i.bak '1i(* AUTOGENERATED FILE: DO NOT EDIT *)\n\n\n\n\n\n\n\n' checker/names.ml && rm checker/names.ml.bak
cp -a kernel/esubst.mli checker/esubst.mli
sed -i.bak '1i(* AUTOGENERATED FILE: DO NOT EDIT *)\n\n\n\n\n\n\n\n' checker/esubst.mli && rm checker/esubst.mli.bak
cp -a kernel/esubst.ml checker/esubst.ml
sed -i.bak '1i(* AUTOGENERATED FILE: DO NOT EDIT *)\n\n\n\n\n\n\n\n' checker/esubst.ml && rm checker/esubst.ml.bak
OCAMLLIBDEP  checker/MLLIBFILES checker/MLPACKFILES
OCAMLDEP  checker/MLFILES checker/MLIFILES
make[1]: Leaving directory `/home/travis/build/HoTT/HoTT/coq-HoTT'
make[1]: Entering directory `/home/travis/build/HoTT/HoTT/coq-HoTT'
make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
Error: no rule to make target camldevfiles (or missing .PHONY)
make[1]: *** [camldevfiles] Error 1
make[1]: Leaving directory `/home/travis/build/HoTT/HoTT/coq-HoTT'
make: *** [submake] Error 2
```

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by JasonGross** [comment]
Thanks!

**Comment by JasonGross** [comment]
This is blocking #8064 (numeral notations) because the overlay for HoTT won't be merged until this is fixed.  So I'd like to see this merged sooner rather than later.

**Review by JasonGross — APPROVED** [review]

**Comment by gares** [comment]
I can merge it Monday, if you want to merge it now, just do it .

**Comment by JasonGross** [comment]
I will merge this now, so that HoTT's CI is fixed.

**Pull request merged**
