### PR TITLE
Revert "Compat for serapi"

### PR DESCRIPTION
**Pull request by SkySkimmer**
This reverts commit b2c778b7f33897754aa542521b878757fe334b83.

Overlay:
- https://github.com/ejgallego/coq-serapi/pull/299

### CODE REVIEW

**Comment by ppedrot** [comment]
What's the point of this PR if it works on master?

**Comment by SkySkimmer** [comment]
It removes some redundant type declarations and makes ugraph.explanation abstract

**Review by ppedrot — APPROVED** [review]
OK then.

**Comment by ejgallego** [comment]
> It removes some redundant type declarations and makes ugraph.explanation abstract

Making `explanation` abstract seems a bit weird tho, isn't that a thing that UIs would like to understand as to potentially show better error mesages?

**Comment by SkySkimmer** [comment]
To get the error message you call `explain_universe_inconsistency`

**Comment by ppedrot** [comment]
Merging soon then.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
