### PR TITLE
Fixes #8369: Not_found in printing message about an unresolved subevar.

### LINKED ISSUE #8369: Anomaly when using pattern-matching under lambda
#### Version

master (bf1446294dba45d3ea9b7bb39d2fc96617848c03)

#### Operating system

macOS 10.13.6

#### Description of the problem

```coq
Definition foo := fun '(u, v) p2 => (u, v).
```

master (bf1446294dba45d3ea9b7bb39d2fc96617848c03): 
> Error: Anomaly "Uncaught exception Not_found." Please report at http://coq.inria.fr/bugs/.

Coq 8.8.1:
> Error: Cannot infer an internal placeholder of type "Type" in environment:
> pat, p0 : ?T0 * ?T1

### PR DESCRIPTION
**Pull request by herbelin**
We were trying to print the name of a resolved evar. As a fix, we use the name of the evar if it has a known user name but print an anonymous "subterm" expression if it has no known user name.

Maybe should we not even try to use the original name as this name may have been "donated" to another (unresolved) evar in situations of instantiations which do not "essentially" change the view we have at the evar (i.e. `intro`, `assert`)?

**Kind:** bug fix

Fixes #8369

- [X] Added / updated test-suite

### CODE REVIEW

**Comment by mattam82** [comment]
> Maybe should we not even try to use the original name as this name may have been "donated" to another (unresolved) evar in situations of instantiations which do not "essentially" change the view we have at the evar (i.e. intro, assert)?

I'm not sure I understand. Isn't evar_ident always returning None for an evar that's been defined?

I tried restarting the ci-hott target but the failure looks totally unrelated, maybe a rebase is needed? The last one looks recent though.

**Comment by herbelin** [comment]
@mattam82: You're probably right. I'll need more time to think at it.

**Comment by herbelin** [comment]
I have "existential" doubts. I introduced in #7062 a way to refer to subterms of an evar so that we can produce the following kind of error message:
```coq
Goal forall a f, f a = 0
>               ^
Error: Cannot infer the domain ?T of the type of f.
```
Elaborating on #8369, I wonder if, finally, it could not be as simple and more informative to give:
```coq
Goal forall a f, f a = 0
>               ^
Error: Cannot infer ?T in the partial instance "?T -> nat"
found for the type of f.
```
Similarly, what would be the best here (for #8369):
```coq
Definition foo := fun '(u, v) p2 => (u, v).
>                   ^^^^^^^^^^^^^^^^^^^^^^^^
Error: Cannot infer ?T in the partial instance
"?T@{pat:=pat; p0:=pat} -> ?T0 * ?T1" found for the type
of this pattern-matching problem in environment:
pat, p0 : ?T0 * ?T1
```
or (following the strategy introduced in #7062):
```coq
Definition foo := fun '(u, v) p2 => (u, v).
>                   ^^^^^^^^^^^^^^^^^^^^^^^^
Error: Cannot infer the domain of a subterm of the type
of this pattern-matching problem in environment:
pat, p0 : ?T0 * ?T1
```

Any opinions?

**Comment by herbelin** [comment]
I think I'm finally going to backtrack on #7062 and to rather adopt the style `Cannot infer ?T in the partial instance "?T -> nat" found for the type of f`. This is both more informative and simpler to implement.

**Comment by herbelin** [comment]
@mattam82: This PR is again ready for collecting opinions. I finally simplified things, tell me if you like it better.

**Comment by herbelin** [comment]
@mattam82: if you like the new version of the error messages, this PR shall not take you a lot of time. If you don't like it, I can continue to work on it.

**Review by mattam82 — APPROVED** [review]
I like the new error message better indeed, and the code looks fine.

**Comment by mattam82** [comment]
@herbelin This seems to have broken quite a few things in the CI.

**Comment by herbelin** [comment]
> This seems to have broken quite a few things in the CI.

It is because I forgot to add `bug_` prefix to the bug number. Restarting.

**Comment by ppedrot** [comment]
@herbelin Overlays have been merged downstream, you should probably relaunch / rebase this PR.

**Comment by mattam82** [comment]
@herbelin I guess a rebase is all that's needed here.

**Comment by herbelin** [comment]
@mattam82:
> @herbelin I guess a rebase is all that's needed here.

It seems indeed to have been the case. CI now all green.

**Comment by mattam82** [comment]
I think this could be backported if you think it's worth it.

**Pull request merged**
