### PR TITLE
cbn: handle combination of / and simpl nomatch

### LINKED ISSUE #15206: cbn ignores ! when simpl nomatch
In https://github.com/coq/coq/blob/14e7c829abeb0e9401f5af0e020bebf6d07340e1/tactics/cbn.ml#L598 `recargs` is bound but not used.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Depends on https://github.com/coq/coq/pull/15653

Close https://github.com/coq/coq/issues/15206

### CODE REVIEW

**Comment by JasonGross** [comment]
@SkySkimmer the ci-iris issue should be fixed by https://github.com/JasonGross/coq-tools/commit/abedb0edf1b193d3149fee865c53839ba75d863a (it was incorrectly treating the message of `Fail fail.` as an error because it had a location and did not start with `Warning`).  So let's try again @coqbot ci minimize ci-iris

**Comment by SkySkimmer** [comment]
That still looks bugged @JasonGross

**Comment by JasonGross** [comment]
@SkySkimmer What looks bugged?  The minimizer fails to fully inline stdpp.numbers, but otherwise the file looks fine to me.  I guess it's suspicious that the `Goal`s before the end aren't removed, let me take a look at the verbose log to see if it'll say what went wrong with removing them.

**Comment by JasonGross** [comment]
So, apparently the inlining failure gives the error message:
```
File "/tmp/tmpulno7c89/bug_01.v", line 113, characters 29-39:
Error: Expected a single focused goal but 0 goals are focused.
```
on the file
```coq
(* -*- mode: coq; coq-prog-args: ("-emacs" "-q" "-w" "-deprecated-hint-rewrite-without-locality" "-w" "-deprecated-typeclasses-transparency-without-locality" "-w" "-deprecated-native-compiler-option" "-Q" "/github/workspace/cwd" "Top" "-Q" "/github/workspace/builds/coq/coq-failing/_build_ci/stdpp/theories" "stdpp" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/Autosubst" "Autosubst" "-Q" "/github/workspace/builds/coq/coq-failing/_install_ci/lib/coq/user-contrib/Ltac2" "Ltac2" "-top" "bug_01" "-test-mode" "-native-compiler" "ondemand") -*- *)
(* File reduced by coq-bug-minimizer from original input, then from 85 lines to 31 lines, then from 44 lines to 440 lines, then from 445 lines to 61 lines, then from 74 lines to 440 lines, then from 445 lines to 76 lines, then from 89 lines to 273 lines, then from 278 lines to 107 lines, then from 120 lines to 532 lines, then from 537 lines to 99 lines, then from 112 lines to 3566 lines, then from 3571 lines to 125 lines, then from 138 lines to 710 lines, then from 715 lines to 125 lines, then from 138 lines to 1513 lines, then from 1513 lines to 126 lines, then from 139 lines to 555 lines, then from 560 lines to 141 lines, then from 154 lines to 5269 lines, then from 5274 lines to 143 lines, then from 149 lines to 144 lines, then from 157 lines to 143 lines *)
(* coqc version 8.16+alpha compiled with OCaml 4.13.0
   coqtop version runner--azerasq-project-6138686-concurrent-0:/builds/coq/coq/_build/default,(HEAD detached at 472dea0) (472dea0d7790ad4f0930f869c67464e1b448e673)
   Expected coqc runtime on this file: 0.785 sec *)

Declare ML Module "coq-core.plugins.ltac".
Module Export AdmitTactic.
Module Import LocalFalse.
Inductive False : Prop := .
End LocalFalse.
Axiom proof_admitted : False.
Global Set Default Proof Mode "Classic".
Tactic Notation "admit" := abstract case proof_admitted.
End AdmitTactic.
Module stdpp_DOT_numbers_WRAPPED.
Module numbers.
(** This file collects some trivial facts on the Coq types [nat] and [N] for
natural numbers, and the type [Z] for integers. It also declares some useful
notations. *)
Require Export Coq.Logic.EqdepFacts Coq.PArith.PArith Coq.NArith.NArith Coq.ZArith.ZArith Coq.Numbers.Natural.Peano.NPeano.
Require Import Coq.QArith.QArith Coq.QArith.Qcanon.
Require Export stdpp.base stdpp.decidable stdpp.option.
Require Import stdpp.options.
Local Open Scope nat_scope.

Global Instance comparison_eq_dec : EqDecision comparison.
Proof. solve_decision. Defined.

(** * Notations and properties of [nat] *)
Global Arguments minus !_ !_ / : assert.
Global Arguments Nat.max : simpl nomatch.

Typeclasses Opaque lt.

Reserved Notation "x ≤ y ≤ z" (at level 70, y at next level).
Reserved Notation "x ≤ y < z" (at level 70, y at next level).
Reserved Notation "x < y < z" (at level 70, y at next level).
Reserved Notation "x < y ≤ z" (at level 70, y at next level).
Reserved Notation "x ≤ y ≤ z ≤ z'"
  (at level 70, y at next level, z at next level).

Infix "≤" := le : nat_scope.
Notation "x ≤ y ≤ z" := (x ≤ y ∧ y ≤ z)%nat : nat_scope.
Notation "x ≤ y < z" := (x ≤ y ∧ y < z)%nat : nat_scope.
Notation "x < y ≤ z" := (x < y ∧ y ≤ z)%nat : nat_scope.
Notation "x ≤ y ≤ z ≤ z'" := (x ≤ y ∧ y ≤ z ∧ z ≤ z')%nat : nat_scope.
Notation "(≤)" := le (only parsing) : nat_scope.
Notation "(<)" := lt (only parsing) : nat_scope.

Infix "`div`" := Nat.div (at level 35) : nat_scope.
Infix "`mod`" := Nat.modulo (at level 35) : nat_scope.
Infix "`max`" := Nat.max (at level 35) : nat_scope.
Infix "`min`" := Nat.min (at level 35) : nat_scope.

Global Instance nat_eq_dec: EqDecision nat := eq_nat_dec.
Global Instance nat_le_dec: RelDecision le := le_dec.
Global Instance nat_lt_dec: RelDecision lt := lt_dec.
Global Instance nat_inhabited: Inhabited nat := populate 0%nat.
Global Instance S_inj: Inj (=) (=) S.
Proof. by injection 1. Qed.
Global Instance nat_le_po: PartialOrder (≤).
Proof. repeat split; repeat intro; auto with lia. Qed.
Global Instance nat_le_total: Total (≤).
Proof. repeat intro; lia. Qed.

Global Instance nat_le_pi: ∀ x y : nat, ProofIrrel (x ≤ y).
Proof.
  assert (∀ x y (p : x ≤ y) y' (q : x ≤ y'),
    y = y' → eq_dep nat (le x) y p y' q) as aux.
  { fix FIX 3. intros x ? [|y p] ? [|y' q].
    - done.
    - clear FIX. intros; exfalso; auto with lia.
    - clear FIX. intros; exfalso; auto with lia.
    - injection 1. intros Hy. by case (FIX x y p y' q Hy). }
  intros x y p q.
  by apply (Eqdep_dec.eq_dep_eq_dec (λ x y, decide (x = y))), aux.
Qed.
Global Instance nat_lt_pi: ∀ x y : nat, ProofIrrel (x < y).
Proof. unfold lt. apply _. Qed.

Lemma nat_le_sum (x y : nat) : x ≤ y ↔ ∃ z, y = x + z.
Proof. split; [exists (y - x); lia | intros [z ->]; lia]. Qed.

(** [Arith.Minus.minus_plus] is deprecated starting in 8.16 *)
Lemma nat_minus_plus n m : n + m - n = m.
Proof. lia. Qed.
(** [Arith.Minus.le_plus_minus] is deprecated starting in 8.16 *)
Lemma nat_le_plus_minus n m : n ≤ m → m = n + (m - n).
Proof. lia. Qed.

Lemma Nat_lt_succ_succ n : n < S (S n).
Proof. auto with arith. Qed.
Lemma Nat_mul_split_l n x1 x2 y1 y2 :
  x2 < n → y2 < n → x1 * n + x2 = y1 * n + y2 → x1 = y1 ∧ x2 = y2.
Proof.
  intros Hx2 Hy2 E. cut (x1 = y1); [intros; subst;lia |].
  revert y1 E. induction x1; simpl; intros [|?]; simpl; auto with lia.
Qed.
Lemma Nat_mul_split_r n x1 x2 y1 y2 :
  x1 < n → y1 < n → x1 + x2 * n = y1 + y2 * n → x1 = y1 ∧ x2 = y2.
Proof. intros. destruct (Nat_mul_split_l n x2 x1 y2 y1); auto with lia. Qed.

Notation lcm := Nat.lcm.
Notation divide := Nat.divide.
Notation "( x | y )" := (divide x y) : nat_scope.
Global Instance Nat_divide_dec : RelDecision Nat.divide.
Proof.
  refine (λ x y, cast_if (decide (lcm x y = y))); by rewrite Nat.divide_lcm_iff.
Defined.
Global Instance: PartialOrder divide.
Proof.
  repeat split; try apply _. intros ??.
```

Idk what's up with this...

**Comment by JasonGross** [comment]
The extra `Goal` statements is due to https://github.com/coq/coq/issues/15666

**Comment by JasonGross** [comment]
> Idk what's up with this...

Even more strangely, I cannot reproduce this error message locally using the tip of this PR...

**Comment by SkySkimmer** [comment]
The bug in this PR is
~~~coq
Definition foo (n:nat) := n + n.
Arguments foo !_ / : simpl nomatch.
Lemma bar n : foo n = 0.
Proof.
  cbn.
  (* BAD n + n = 0 *)
~~~
(no idea what's up with minimization)

**Comment by SkySkimmer** [comment]
#3988 is still open, I haven't looked into it.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
