### PR TITLE
[RM] Changelog for 8.13.1

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by Zimmi48** [comment]
So, no changelog for #13870 in the end?

**Comment by gares** [comment]
ok

**Comment by gares** [comment]
can you merge it now @Zimmi48 ?

**Comment by Zimmi48** [comment]
IMHO this is more of a fix than an addition, but good to go.

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
