### PR TITLE
Fix the build on Windows

### PR DESCRIPTION
**Pull request by JasonGross**
This fixes bug #4828 (https://coq.inria.fr/bugs/show_bug.cgi?id=4828).

### CODE REVIEW

**Comment by JasonGross** [comment]
Oops, sorry, this breaks other things.  I'll make a fix soon.

**Comment by JasonGross** [comment]
Should be fixed now (at least, it builds for me on Windows)

**Comment by ppedrot** [comment]
I'm no build system expert, nor a Windows user, so I won't take the responsibility to merge this PR. People like @gares and @letouzey should be more knowledgeable on this topic.

**Comment by gares** [comment]
Thank you guys!

**Pull request merged**
