### PR TITLE
Fix incorrect line numbers in Errors panel

### LINKED ISSUE #15531: Line numbers in 'Error' tab in coqide wrong after upgrade
After upgrading from coq 8.14.1 to 8.15 using the package manager of
my linux distribution (pacman and archlinux) the line numbers in the
'Error' tab are wrong. An example file is here: http://chrisdams.nl/euclid.v
Opening this in coqide and going to the end of the file by pressing the
down button 'Run to end' yields an error. The 'Errors' tab contains the line
number 533 and the error message 'Tactic failure: tauto failed.'. However,
the line number 533 is wrong. The actual error occurs on line 303. Also,
double clicking on the error in the 'Errors' tab brings us to line 533 which
is not where the error is.

cc: @jfehrle

### PR DESCRIPTION
**Pull request by jfehrle**
Fixes: #15531.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Maybe this bug fix should be considered of sufficient importance to deserve its changelog entry?

**Comment by Alizter** [comment]
Is there someway we can test these operations? THe issue is that this code is really easy to break, so either we make it super sturdy or better yet add something to the test-suite.

**Comment by jfehrle** [comment]
To test this well, we would probably need to flesh out a white-box testing framework (doable, but not trivial) or, more convincingly, create black box tests for the GUI.  I believe the latter is far more than we would want to take.

One reason I didn't catch this earlier is that I didn't know how to reach this routine from the GUI.  It would help to document more of CoqIDE's behavior--for users, for hand testing and to act as spec.  That is a reasonable effort.  (Ex: the operation of the Compile menu is still terra incognita for me).

I'll add a changelog.

**Comment by jfehrle** [comment]
@Zimmi48 I wonder if the 8.15 platform might include this fix even if it's not in 8.15 proper (if it's not too much trouble for @MSoegtropIMC).  Waiting for 8.15.1 seems like a long time for this particular bug.  Or is this a bad idea?

**Comment by Zimmi48** [comment]
Up to @MSoegtropIMC to say. But what I can say is that the Coq Platform 2022.01 is expected for tomorrow and has already been delayed quite a lot, so we'd like to avoid delaying it further. Note that this Platform release will have Coq 8.14 as its default version and Coq 8.15 as a beta version. The Platform release with Coq 8.15 as its default version is expected for the end of February / very beginning of March and should be called 2022.03.

**Review by ppedrot — APPROVED** [review]
Looks like a legit change, if it solves the issue that's good for me.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
