### PR TITLE
 Put back digests in mltop

### LINKED ISSUE #15649: dune misses transitive dependencies of vo files on plugins
ie https://github.com/coq/coq/issues/10874 reopened by #15220

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #15649

### CODE REVIEW

**Comment by gares** [comment]
I'll save you some time:
```ocaml
(* Fl_split.in_words is not exported *)
let fl_split_in_words s =
  (* splits s in words separated by commas and/or whitespace *)
  let l = String.length s in
  let rec split i j =
    if j < l then
      match s.[j] with
	    | (' '|'\t'|'\n'|'\r'|',') ->
	        if i<j then (String.sub s i (j-i)) :: (split (j+1) (j+1))
		      else split (j+1) (j+1)
      |	_ ->
	        split i (j+1)
    else
      if i<j then [ String.sub s i (j-i) ] else []
  in
  split 0 0
```

**Comment by SkySkimmer** [comment]
WTF it compiles fine on my machine

**Comment by silene** [comment]
> WTF it compiles fine on my machine

`Fl_split` has been exported for only two weeks (since 1.9.3). You live on the edge.

By the way, function `fl_split_in_words` could be separated by a blank line from the previous one. It would also benefit from a non-garbled indentation. But other than these syntactic issues, it looks good.

**Review by silene — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
