### PR TITLE
Add `hex_{Z,N,positive}_scope`

### PR DESCRIPTION
**Pull request by JasonGross**
I have no idea why these were not already present.

**Kind:** feature

- [x] Added / updated test-suite
- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).
- [ ] Overlay pull requests (if this breaks 3rd party developments in CI, see
https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md for details)

### CODE REVIEW

**Comment by proux01** [comment]
@JasonGross looks good for printing, could you also add parsing while you are at it?

**Comment by JasonGross** [comment]
I think parsing already worked fine.  I'll add some tests though.

**Comment by JasonGross** [comment]
I've added a bunch more tests for parsing of hex constants.

**Comment by proux01** [comment]
My bad, thanks for the test. I really don't know why I didn't implement those printers.

**Comment by JasonGross** [comment]
Is this blocked on anything?

**Review by anton-trunov — APPROVED** [review]
The changes in the stdlib LGTM!

@proux01 would you like to be the assignee for this PR?

**Review by proux01 — APPROVED** [review]
Looks good to me

**Comment by proux01** [comment]
> @proux01 would you like to be the assignee for this PR?

I don't have merge rights, so feel free to proceed.

**Comment by JasonGross** [comment]
If you assign, you can just say "@coqbot merge now", and it will listen to you as an assignee

**Comment by proux01** [comment]
@coqbot merge now

**Comment by proux01** [comment]
Indeed, thanks!

**Pull request merged**
