### PR TITLE
Fix backtraces in conversion anomalies caught by Reductionops.

### PR DESCRIPTION
**Pull request by ppedrot**
The call to is_anomaly actually destroyed the backtrace, because it would call arbitrary code, in particular in Himsg which relied internally on raising exceptions.

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]
I confirm this fixes backtraces for exceptions coming from conversion. Seems straightforward, so I'll merge soon if no objection.

**Comment by maximedenes** [comment]
Let's cc @ejgallego since he was recently involved in backtrace-related code, so he may be interested.

**Comment by SkySkimmer** [comment]
Maybe it would make sense to replace those anomalies by regular NotConvertible? Considering they can be raised by simple examples like
~~~coq
Inductive Hide := hide : forall A, A -> Hide.
Definition HideMore (_:Hide) := 0.

Lemma foo : HideMore (hide Type Type) = HideMore (hide (nat -> Type) (fun x : nat => Type)).
Proof.
  Fail reflexivity.
  match goal with |- ?l = _ => exact_no_check (eq_refl l) end.
Qed. (* this one can't be caught by Fail, it's a real anomaly! *)
~~~
which should succeed.

**Comment by ppedrot** [comment]
You don't even need unsafe tactics, IIRC `set` calls conversion on terms that do not have the same type and thus can trigger the error.

**Review by ejgallego — COMMENTED** [review]
Indeed the patch is OK, however I wonder why the special function is needed at all.

**Comment by maximedenes** [comment]
> why the special function

which special function do you mean?

**Comment by ejgallego** [comment]
> which special function do you mean?

I think the same you mentioned on gitter, `report_anomaly`; seems a pretty suspicious thing to do.

**Comment by ejgallego** [comment]
> Himsg which relied internally on raising exceptions.

Indeed there has been some change there; now I realize that the solution I used there after moving the printers to `Pp.t option` is not a good one [an example of trying to minimize the diff gone wrong]

So indeed we should fix that.

**Pull request merged**
