### PR TITLE
[doc] [sphinx] Run in silent mode by default

### PR DESCRIPTION
**Pull request by ejgallego**
The convention in the dune build is to be silent except for warnings
and errors, so they don't go unnoticed.

We could have this controlled by a variable if needed (likely would
require some support from Dune?)

Solves part of #12194

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
> We could have this controlled by a variable if needed (likely would
> require some support from Dune?)

What about renaming `SPHINXWARNOPT` into `SPHINXOPTS` and putting the `-q` as part of the default value?

**Comment by ejgallego** [comment]
> What about renaming `SPHINXWARNOPT` into `SPHINXOPTS` and putting the `-q` as part of the default value?

I tried that but bleh, couldn't convince dune to assign a default variable with spaces ... moreover `%{env:VAR=DEFAULT}` seems undocumented, I'm sure I already had a problem with this in the past.

**Comment by ejgallego** [comment]
Ok, I had to tweak things a bit but this is almost perfect.

**Review by Zimmi48 — APPROVED** [review]
Great, thanks again! I'll merge this tomorrow. (Next step, will be to try to solve the warnings :wink:)

**Comment by Zimmi48** [comment]
Should we mark this PR as solving completely #12194?

**Comment by ejgallego** [comment]
> Should we mark this PR as solving completely #12194?

I did not as the warnings for the PDF mode persist; we can open a new issue for them tho, but they look quite silly so they should be solvable.

**Comment by ejgallego** [comment]
p.s. your idea to rename `SPHINXWARNOPT` is nice, but as I mentioned I found some problems with spaces in the default value of `%{env:_}` , I'm in touch with Dune upstream to see what's going on.

**Comment by ejgallego** [comment]
Another problem this PR has is that Sphinx doesn't use `latexmk` on Windows, but IIANM the only bad effect is that the pdf manual will be generated in verbose mode.

**Comment by Zimmi48** [comment]
That does sound quite reasonable as a first step. Do you want me to leave this open a bit longer or can I merge now?

**Comment by ejgallego** [comment]
> That does sound quite reasonable as a first step. Do you want me to leave this open a bit longer or can I merge now?

For now I have nothing else planned to do here.

**Pull request merged**
