### PR TITLE
Kernel sort comparison: fully delegate to ugraph

### LINKED ISSUE #14420: Cumulative StrictProp, but SProp alias isn't cumulative
in 8.13.2:
```Coq
Set Cumulative StrictProp.
Definition ok(x:SProp) : Type := x. (*SProp is cumulative*)
Definition sp := SProp. (*sp aliases SProp*)
Fail Definition bug(x:sp) : Type := x. (*sp is not cumulative*)
```
The failure is:
```
The command has indeed failed with message:
The term "fun x : sp => x" has type "sp -> sp"
while it is expected to have type "sp -> Type".
```

### PR DESCRIPTION
**Pull request by SkySkimmer**
This fixes #14420

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Shouldn't we get a bench just in case?

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1306615590

**Comment by ppedrot** [comment]
*Bracing for unimath.*

**Comment by SkySkimmer** [comment]
~~~
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │  111.29   111.53  -0.22 │   316838522138    316126865048   0.23 │   411688153438    410562498370   0.27 │  479328   479304   0.01 │   0    0    nan │
│             coq-fiat-crypto │ 5019.10  5024.75  -0.11 │ 13937229199434  13945539565588  -0.06 │ 24017069693475  24012161795451   0.02 │ 2221376  2223952  -0.12 │   0    0    nan │
│                    coq-core │  109.70   109.75  -0.05 │   303959760162    303729257322   0.08 │   457252021610    456987993855   0.06 │  296408   296504  -0.03 │   0    0    nan │
│            coq-fiat-parsers │  617.57   617.76  -0.03 │  1727292336684   1729715826929  -0.14 │  2560115580416   2558978390622   0.04 │ 3073188  3073368  -0.01 │   0    0    nan │
│                    coq-corn │ 1540.63  1540.88  -0.02 │  4289091763960   4290645753231  -0.04 │  6035930946402   6035714063983   0.00 │  810140   810056   0.01 │   0    0    nan │
│                   coq-color │  504.17   504.19  -0.00 │  1408742763122   1406033031157   0.19 │  1712928804570   1711961589700   0.06 │ 1141468  1141708  -0.02 │   0    0    nan │
│              coq-verdi-raft │ 1209.78  1209.73   0.00 │  3369679542996   3367047038554   0.08 │  4623803928338   4622957136339   0.02 │  901308   901680  -0.04 │   0    0    nan │
│       coq-mathcomp-solvable │  178.45   178.33   0.07 │   497676794982    496496611848   0.24 │   683193123514    683220290304  -0.00 │  693188   672544   3.07 │   0    0    nan │
│      coq-mathcomp-character │  158.11   157.96   0.09 │   439766434499    439003121419   0.17 │   598639051885    598678366180  -0.01 │  730820   715904   2.08 │   0    0    nan │
│             coq-lambda-rust │ 1325.07  1323.46   0.12 │  3692002748702   3688567131931   0.09 │  5139392732125   5137387249422   0.04 │ 1096004  1096396  -0.04 │   0    0    nan │
│  coq-performance-tests-lite │ 1654.55  1652.02   0.15 │  4612738224163   4610673898182   0.04 │  7469322834680   7470641587745  -0.02 │ 2077256  2077424  -0.01 │   0    0    nan │
│      coq-mathcomp-ssreflect │   55.69    55.58   0.20 │   154271394073    153700553715   0.37 │   190660750776    190711464290  -0.03 │  522116   522692  -0.11 │   0    0    nan │
│               coq-perennial │ 7093.65  7079.02   0.21 │ 19750223820529  19705326791457   0.23 │ 29183811229100  29187044268555  -0.01 │ 3095812  3091224   0.15 │   0    0    nan │
│                coq-rewriter │  721.00   719.20   0.25 │  2001597128908   1999264849385   0.12 │  2980004707299   2978088108425   0.06 │ 1071032  1071040  -0.00 │   0    0    nan │
│          coq-mathcomp-field │  231.42   230.74   0.29 │   645044244884    642931439534   0.33 │   955253158238    955324766840  -0.01 │  658992   657872   0.17 │   0    0    nan │
│               coq-fourcolor │ 2640.07  2631.81   0.31 │  7350356447813   7325929246089   0.33 │ 12249393114347  12250795219237  -0.01 │  730980   795200  -8.08 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │  791.40   788.88   0.32 │  2203237688455   2198032077673   0.24 │  3345988763169   3345956234490   0.00 │ 1071080  1070804   0.03 │   0    0    nan │
│                    coq-hott │  351.46   350.25   0.35 │   974980672266    971885307680   0.32 │  1410519736900   1410309388450   0.01 │  568796   568780   0.00 │   0    0    nan │
│       coq-mathcomp-fingroup │   50.43    50.24   0.38 │   140314747431    140016501381   0.21 │   189763936308    189762137889   0.00 │  479888   479792   0.02 │   0    0    nan │
│                 coq-bignums │   58.04    57.82   0.38 │   160962494618    160378226820   0.36 │   210042502166    210064373496  -0.01 │  467316   467308   0.00 │   0    0    nan │
│            coq-math-classes │  182.46   181.68   0.43 │   507723213588    506819850062   0.18 │   654330474805    654297067059   0.01 │  481444   481436   0.00 │   0    0    nan │
│                  coq-geocoq │ 1423.62  1417.36   0.44 │  3968992876383   3950924725468   0.46 │  5641926510336   5640612149822   0.02 │  988756  1066908  -7.33 │   0    0    nan │
│              coq-coquelicot │   71.82    71.50   0.45 │   196948221701    196080046403   0.44 │   242306323396    241585587535   0.30 │  558724   558820  -0.02 │   0    0    nan │
│        coq-mathcomp-algebra │  145.32   144.59   0.50 │   405114707246    403135347550   0.49 │   509298785049    509271318758   0.01 │  553256   552864   0.07 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1105.51  1099.82   0.52 │  3076549800483   3062656926302   0.45 │  4721473578731   4721758530276  -0.01 │  938432   903888   3.82 │   0    0    nan │
│                 coq-unimath │ 4073.74  4051.99   0.54 │ 11334574241844  11283572493513   0.45 │ 21288086984923  21281800334290   0.03 │ 1128284  1128448  -0.01 │   0    0    nan │
│       coq-engine-bench-lite │  328.56   326.74   0.56 │   925343971948    921919754733   0.37 │  1667280436456   1660924526185   0.38 │ 3506700  3506748  -0.00 │   0    0    nan │
│                  coq-stdlib │  425.02   422.16   0.68 │  1188334261974   1182678734969   0.48 │  1492161561523   1492103280575   0.00 │  596132   596088   0.01 │   0    0    nan │
│                coq-coqprime │ 1103.81  1095.98   0.71 │  3070120685318   3052618578124   0.57 │  5104521563847   5103563831382   0.02 │ 1035316  1035504  -0.02 │   0    0    nan │
│                   coq-verdi │  103.40   102.62   0.76 │   285066681233    283750871314   0.46 │   388577834874    387895076390   0.18 │  543948   544164  -0.04 │   0    0    nan │
│                coq-bedrock2 │  320.53   317.72   0.88 │   890641309583    883084221536   0.86 │  1520642003538   1519999012899   0.04 │  770432   797880  -3.44 │   0    0    nan │
│                 coq-coqutil │   60.56    59.68   1.47 │   167829566602    166561106660   0.76 │   214883323584    214490937780   0.18 │  600632   600740  -0.02 │   0    0    nan │
│                         coq │    4.58     4.48   2.23 │    12138758740     12129282221   0.08 │    23631551312     23656997642  -0.11 │  302092   302080   0.00 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
~~~

**Pull request merged**
