### PR TITLE
Bench old before new

### PR DESCRIPTION
**Pull request by SkySkimmer**
Discussion now at https://github.com/coq/coq/issues/14159

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/1087272734

**Comment by silene** [comment]
Should we try doing `opam source --dir=whatever $coq_opam_package` to force Opam to download the sources beforehand?

**Comment by SkySkimmer** [comment]
Would the source be in the cache in addition to `whatever`?

**Comment by silene** [comment]
For regular packages, yes. Let me try if that is also true for Git repositories.

**Comment by SkySkimmer** [comment]
I'll replace this with an issue and run experiments on my gitlab to avoid spamming push notifications

**Pull request closed without merging**
