### PR TITLE
Statically ensure that only polymophic hint terms come with a context.

### PR DESCRIPTION
**Pull request by ppedrot**
It is the duty of the caller to properly declare monomorphic global constraints when creating a non-globref hint. All callers were already abiding by this convention.

Overlays:
- https://github.com/mit-plv/fiat/pull/44
- https://github.com/mattam82/Coq-Equations/pull/319

### CODE REVIEW

**Comment by ppedrot** [comment]
This needs an assignee. @mattam82 maybe?

**Comment by ppedrot** [comment]
@mattam82 ping

**Comment by ppedrot** [comment]
@mattam82 pingy-ping.

**Review by mattam82 — APPROVED** [review]
Nice cleanup!

**Comment by mattam82** [comment]
@coqbot merge now

**Comment by mattam82** [comment]
@coqbot merge now

**Pull request merged**
