### PR TITLE
Remove table of hashconsed term arrays

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not convinced that it's actually useful.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — CHANGES_REQUESTED** [review]
This is a terrible idea, now you fundamentally rely on the hack that arrays are mutated in place to be efficient when hashconsing. If the arrays were kept pure, then this would basically prevent sharing of all first-order subterms, which is the typical case where it matters.

**Comment by SkySkimmer** [comment]
I don't understand how it relies on the mutation, AFAICT it would work if we did Array.map instead of in place mutation

**Comment by silene** [comment]
Yes, it would presumably work with `Array.map`. But first, the code is not using `Array.map`. Second, why allocate memory when you can reuse the memory of the old array? (If `Array.map` was not triggering the GC barrier, then it would sometimes be faster than in-place modification, but since it does, it is never faster.)

**Comment by SkySkimmer** [comment]
Does the unrolled array map trigger the gc barrier on short arrays? ie
~~~ocaml
let map f = function
| [||] -> [||]
| [|x|] -> [|f x|]
| [|x;y|] -> let fx = f x in let fy = f y in [|fx;fy|]
(* ... however many cases seems useful *)
| a -> Array.map f a
~~~

**Comment by silene** [comment]
No, it does not trigger the GC barrier. But it is not particularly cheap either. Indeed, it first allocates a record, and then it converts it into an array, assuming there is no floating-point numbers (otherwise, it allocates yet another array).

**Comment by silene** [comment]
Sure, but the way Gaetan wrote `map`, the types are unknown, so the whole machinery is involved. (Even if it is semantically the identity function, `caml_array_make` is no joke, CPU-wise.)

**Comment by ppedrot** [comment]
> so the whole machinery is involved

Yes, indeed, but it's trivial to annotate the argument like we do it in CClosure.

**Comment by SkySkimmer** [comment]
The instruction change might not be nothing but it's not really worth caring about either.

**Comment by silene** [comment]
Compiled files are much larger, so it broke some sharing anyway:
```
coq-verdi-raft/./theories/RaftProofs/CroniesCorrectProof.vo 1039258 1240414 201156 19%
coq-verdi-raft/./theories/RaftProofs/NoAppendEntriesRepliesToSelfProof.vo 69458 84878 15420 22%
coq-verdi-raft/./theories/RaftProofs/LogMatchingProof.vo 970884 1198039 227155 23%
coq-verdi-raft/./theories/RaftProofs/CandidatesVoteForSelvesProof.vo 195867 246654 50787 25%
coq-verdi-raft/./theories/RaftProofs/LeaderSublogProof.vo 540803 686710 145907 26%
coq-verdi-raft/./theories/RaftProofs/TermsAndIndicesFromOneLogProof.vo 100705 128957 28252 28%
```

**Pull request closed without merging**
