### PR TITLE
Deprecate Typeclasses Axioms Are Instances

### PR DESCRIPTION
**Pull request by SkySkimmer**
People should use Declare Instance instead.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
ping @mattam82 or @maximedenes

**Review by ppedrot — APPROVED** [review]
That was the next logical step, I believe.

**Comment by jfehrle** [comment]
@Zimmi48 Ah, you're suggesting I take it off the to-do list in the other PR?

**Comment by jfehrle** [comment]
OK, you must mean don't bother adding the doc since it's being deprecated.

**Comment by Zimmi48** [comment]
Indeed.

**Comment by ppedrot** [comment]
@SkySkimmer can you rebase to get a clean CI?

**Pull request merged**
