### PR TITLE
Take into account the existing delta-resolver when starting a new interactive module or module type

### LINKED ISSUE #12525: Search command inside a module fails to see declarations coming by module inclusion
#### Description of the problem

```coq
Require Import Arith.

Search Nat.lcm. (* prints a bunch of lemmas *)

Module M.

Search Nat.lcm. (* prints nothing *)
```

But if we search for `Nat.add` instead, it works. I guess this is a bug of the new `Search` functionality introduced in 8.12 (#8855).

#### Coq Version

master

### LINKED ISSUE #12647: Search no longer works with Coq 8.12
In Coq 8.12, `Search` no longer returns any result. This might be a duplicate of #12525.

```coq
From Coq Require Lia.

Module Type Foo.
Axiom P : nat -> Prop.
Axiom L : P 0.
End Foo.

Module Bar (F : Foo).
Search F.P. (* empty, except for a warning about SSReflect, which I did not even require indirectly *)
```

This is a regression with respect to Coq 8.11.

If I remove `Require Lia`, then it suddenly works. Unfortunately, `Lia` is most certainly going to be directly or indirectly required by any user development.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

The default value of the delta-resolver for name aliasing was reinitialized to the empty substitution at `Module` and `Module Type` starting time. The existing resolver was saved but the saved resolver was not used in `Safe_typing.constant_of_delta_kn_senv` and `Safe_typing.mind_of_delta_kn_senv`.

A possible fix could have been to take the saved resolver into account in `Safe_typing.constant_of_delta_kn_senv` and `Safe_typing.mind_of_delta_kn_senv`. We instead try to just not reset it.

This incidentally fixes #12525 (`Search` unable to see through an `Include` when inside an interactive `Module`).

The issue apparently comes from the beginning of modules aliases (2008, 0d0d1ba857).

I suspect this only loses some delta equalities and is otherwise w/o bad consequences.

Fixes #12525, fixes #12647 (indirectly).

- [X] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Color error:
~~~
 File "./Coccinelle/examples/cime_trace/rpo_extension.v", line 393, characters 2-33:
Error: Signature components for label support do not match: expected type
"EqtM.T.VSet.t -> list EqtM.T.VSet.EDS.A" but found type
"EqtM.T.VSet.t -> list EqtM.T.VSet.EDS.A".
~~~

I don't know if the timeout in test-suite:edge:dune:dev https://gitlab.com/coq/coq/-/jobs/599774707 is a real issue, let's worry about it after the color issue is fixed.

**Comment by herbelin** [comment]
@skyskimmer: are you ok to take (or at least share) the responsibility of this PR?

What the last version of the PR does is only to stop resetting the existing resolvers when a module or module type starts, which is expected since a module or module type extend the current environment with a new "open parenthesis".

At ending of the module or module type, the resolver of the env extended with the new module (i.e. informally "env; [Module. ... End Module]") is recomputed from the resolver of env and from the `mod_delta` bound to the module exactly as it was before.

Otherwise said, the change has an impact only inside the module or module type being interactively built, and this change is obviously expected (i.e. from the inside of a module, the start-module mark should be ignored, i.e. "env. Module T (X:U). decls" should behave exactly like "env. Module X:U. decls", what the PR does wrt resolvers associated to "env").

**Comment by SkySkimmer** [comment]
>@SkySkimmer: are you ok to take (or at least share) the responsibility of this PR?

Do you mean assigning?

**Review by SkySkimmer — APPROVED** [review]
Leaving it to 8.12 maintainers to decide whether to backport this or if https://github.com/coq/coq/pull/12663 is enough.

**Comment by ejgallego** [comment]
> Leaving it to 8.12 maintainers to decide whether to backport this or if #12663 is enough.

Thanks @SkySkimmer , how risky do you think this change is? My understanding of the handling of name aliasing in the module system is null.

**Comment by SkySkimmer** [comment]
@herbelin what was the color issue about in the initial version of the PR? Could we have a reproduction case in the test suite?

**Comment by herbelin** [comment]
The CoLoR example was pretty involved (with functors rexporting their arguments in their body, ...) and I would not know how to reproduce it without spending an hour or so.

The reason it failed is that I was overoptimistic (or overnaive) in the first version (57510c6) of the PR: at ending of the module, I was reusing the resolver `mod_delta` built by `build_module_body` which I was expecting to extend the resolver existing at the start of the module.

In the second version, I made the alternative assumption that the `mod_delta` was attached to the module being closed and that adding its bindings on top of the old resolver `Mod_subst.add_delta_resolver mb.mod_delta oldsenv.modresolver` was relevant .

Since you are asking the question, I now double-checked and the situation is actually inbetween:
- If the module has no (forced) type, the `mod_delta` is the current value of `modresolver` at the end of the module (executation path: `build_module_body`, `Mod_typing.finalize_module` with `senv.modresolver`, `Mod_typing.mk_mod`).

  In this case, regarding the value of the resolver at module ending:
  - the original code was (presumably) ok (combining the old resolver with the new one built incrementally on top of an empty resolver);
  - the first version of the PR is ok (returning the resolver incrementally on top of the old resolver) iff `Mod_subst.add_delta_resolver` does the same in one go as an incremental extension of the resolver;
  - the second version of the PR is ok (combining the old resolver with the new one built incrementally on top of the old resolver) iff `Mod_subst.add_delta_resolver` is idempotent on re-adding the incremental extension of the old resolver on top of the old resolver (*).
- If the module has a type, the `mod_delta` is built from the module type only (executation path: `build_module_body`, `Mod_typing.finalize_module` with `senv.modresolver`, `translate_modtype`, `translate_mse_funct`, `translate_mse`, which takes the `mod_delta` bound to the main part of the module type and enrich it with bindings derived by application of module arguments and by use of `with` clauses).

  In this case, regarding the value of the resolved at module ending:
  - the original code was (presumably) ok (combining the old resolver with the one specifically associated to the module type);
  - the first version of the PR was wrong (not combining the resolver specific to the module type with the old resolver);
  - the second version of the PR is doing the same as the original code (combining the old resolver with the specifically associated to the module type).

Conclusion:
- if the assumption (*) holds, the PR is good;
- if we don't want to take risks about (*) and ensure that the current version of the PR works exactly the same as before regarding the value of the resolve at module ending, we could force `senv.modresolver` to be the old `senv.modresolver` in `build_module_body`.

Do you agree with the analysis? What do you think about the conclusion?

**Comment by maximedenes** [comment]
@ppedrot Did you see this PR? I know you are "interested" in delta-resolvers, and I had missed it myself.

**Comment by ppedrot** [comment]
@maximedenes I saw it and was quite frightened by the fact that a fix to Search required a kernel change, but I convinced myself at the time that the patch was fine and did not mention it further.

**Pull request merged**
