### PR TITLE
Do not duplicate delta resolved when opening modules.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of storing the resolver coming from the ambient module, we just keep the constraints introduced by the module being defined.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
We don't lose anything from this and it's making the code more correct, so I'm undrafting this PR.

**Review by SkySkimmer — APPROVED** [review]
>it's making the code more correct

If you say so then I believe you

**Comment by ppedrot** [comment]
@herbelin seemed to somehow agree as well.

**Comment by ppedrot** [comment]
As a matter of fact, we should probably harden our implementation to raise anomalies when redefining aliases already part of the current environment.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
