### PR TITLE
Remove LaTeX refman, now that migration to Sphinx is complete

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by maximedenes** [comment]
Tested as part of https://gitlab.com/maximedenes/coq/pipelines/20598027

**Comment by Zimmi48** [comment]
Two questions:

1. I thought there was still a way to generate a PDF for the Sphinx manual but apparently there isn't. No big deal but if there is still a way, we probably want to continue providing a target for this.
2. Shouldn't we keep the `refman` target as an alias to `sphinx`?

**Comment by anton-trunov** [comment]
I have used the PDF version for the following reasons:

- to have a local copy of the manual;
- to search for stuff across the whole manual.

Is it possible to do it with the Sphinx version?

**Comment by Zimmi48** [comment]
- The Sphinx HTML version can easily be compiled locally but I guess it is less easy to distribute than a single PDF file (it could be distributed in a tarball).
- The Sphinx manual has a search bar so for global search, I think it will be even better.

**Comment by anton-trunov** [comment]
- Personally I'm fine with compiling my local HTML version as long as it really does compile without too much effort (as opposed to the PDF version which I just downloaded).
- Yes, you are right -- I completely forgot about this feature.

**Pull request merged**
