### PR TITLE
Remove the Refiner module

### PR DESCRIPTION
**Pull request by ppedrot**
The deprecated aliases were move to were they belong, as well as the little leftover.

Overlay:
- https://github.com/mattam82/Coq-Equations/pull/303

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by ppedrot** [comment]
Two additional backwards compatible overlays are waiting to be merged.

**Comment by ejgallego** [comment]
Pending on https://github.com/damien-pous/relation-algebra/pull/12 then I'll merge.

**Comment by ejgallego** [comment]
Needs a small rebase [the code moved to `Declare`]

**Comment by ejgallego** [comment]
CI is fine now; coq performance tests have gone out of hand in both time and memory, only a few days after there were merged....

**Pull request merged**
