### PR TITLE
[build] Fix VM dynamic linking prep in byte builds.

### PR DESCRIPTION
**Pull request by ejgallego**
We correctly set the path of `libcoqrun` in non-local builds. This bug
was introduced by #6038.

c.f. #6475 , #5992.

### CODE REVIEW

**Comment by maximedenes** [comment]
This seems to break compilation on OSX.

**Comment by ejgallego** [comment]
I'd bet the OSX CI is bugged, not the patch.

**Comment by ejgallego** [comment]
Umm, can anyone with a mac see what's going on here. Doing a `make VERBOSE=1 bin/coqtop.byte` should suffice.

**Comment by herbelin** [comment]
`make VERBOSE=1 bin/coqtop.byte` succeeds on my OS X 10.11.1. Just a few warnings like

findlib: [WARNING] Interface main.cmi occurs in several directories: tools/coqdoc, ~/.opam/4.03.0+trunk/lib/ocaml/compiler-libs
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: ~/.opam/4.03.0+trunk/lib/ocaml/compiler-libs, ~/.opam/4.03.0+trunk/lib/ocaml

What should have it tested?

**Comment by ejgallego** [comment]
Merci @herbelin , are you testing this branch I assume? For some reason the build fails on Travis, I'll have to create a custom CI branch to see what's going on.

**Comment by herbelin** [comment]
OK, I had configured with `-no-custom` which I need for the loading of printers in ocamldebug to work in Mac OS X. Looking at the Travis failure, I retried without the `-no-custom` and it now fails the same as in Travis.

**Comment by ejgallego** [comment]
@herbelin and what is the build log for the make command with `VERBOSE=1`

**Comment by SkySkimmer** [comment]
I pushed this to gitlab and all 3 test suite jobs succeeded, which is fairly rare, so I'm hopeful.

**Comment by herbelin** [comment]
@ejgallego: Is this the line you want?
```
"/Users/herbelin/.opam/4.03.0+trunk/bin/ocamlfind" ocamlc -thread -rectypes -w +a-4-9-27-41-42-44-45-48-50   -safe-string  -linkall -linkpkg -I toplevel \
	                 -I kernel/byterun/ -custom \
                         -package num,str,unix,dynlink,threads -package camlp5.gramlib,compiler-libs.toplevel \
	                 clib/clib.cma lib/lib.cma kernel/kernel.cma intf/intf.cma library/library.cma engine/engine.cma pretyping/pretyping.cma interp/interp.cma proofs/proofs.cma parsing/parsing.cma printing/printing.cma tactics/tactics.cma vernac/vernac.cma stm/stm.cma toplevel/toplevel.cma  -g  \
	                 toplevel/coqtop_byte_bin.cmo toplevel/coqtop_bin.ml -o bin/coqtop.byte
```

**Comment by ejgallego** [comment]
@herbelin indeed thanks, but that line is the one of a successful build using `-custom`, right?

**Comment by ejgallego** [comment]
Oh I see, MacOS uses `-custom` by default. Ummm, I wonder whether that default should be updated.

**Comment by ejgallego** [comment]
I can reproduce now on Linux, thanks folks!

**Comment by ejgallego** [comment]
@SkySkimmer let me know how it goes but this should indeed fix the problem you were seeing.

**Pull request merged**
