### PR TITLE
[coercion] fix error message after saturation by typeclass resolution

### PR DESCRIPTION
**Pull request by mattam82**
We were returning the old evar map, which doesn't explain the error
after typeclass resolution was tried.

**Kind:** bug fix

Not really a "bug" but a misfeature. 

- [x] Added / updated test-suite

### CODE REVIEW

**Comment by ejgallego** [comment]
Assigning as per inactivity of the secondary; this needs rebase and fixing.

**Comment by ejgallego** [comment]
Ping @mattam82

**Comment by ejgallego** [comment]
Cleaning up my "assigned" list, please ping when activity resumes.

**Comment by mattam82** [comment]
Finally rebased

**Comment by ejgallego** [comment]
Still broken :/
```
==========> TESTING bugs/closed/bug_4782.v <==========
Debug: 1: looking for (C (dom ?A)) with backtracking
Debug: 1.1: exact cn on (C (dom ?A)), 0 subgoal(s)
Debug: 1: looking for (C (dom ?A)) with backtracking
Debug: 1.1: exact cn on (C (dom ?A)), 0 subgoal(s)
File "./bugs/closed/bug_4782.v", line 24, characters 7-25:
Error:
In environment
A : T
x : dom A
The term "(x, x)" has type "(dom A * dom A)%type"
while it is expected to have type "let (dom) := B in dom".

0m0.000000s 0m0.000000s
0m0.040000s 0m0.040000s
==========> FAILURE <==========
    bugs/closed/bug_4782.v...Error! (bug seems to be opened, please check)
```

**Comment by Zimmi48** [comment]
Dear PR author(s) and contributors, it seems to us this PR may need additional work beyond the 8.12 branching deadline on May 15th.

We are thus removing the 8.12+beta1 milestone; please retarget as appropriate, and also consider updating labels to reflect current status, moving the PR to draft status, etc.

We apologize in advance if we misunderstood the PR status.

**Comment by ppedrot** [comment]
@mattam82 shouldn't we close this PR?

**Pull request closed without merging**
