### PR TITLE
bench NEW=2024-10-09 OLD=2024-07-09

### PR DESCRIPTION
**Pull request by SkySkimmer**
last time was https://github.com/coq/coq/pull/19347

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Looks like something interesting happened in coqprime

**Comment by ejgallego** [comment]
I've been also observing that requires take a longer time in main, didn't measure this formally tho, but if you are compare to 8.20 maybe keep an eye.

**Comment by JasonGross** [comment]
Where are the error logs for the failures to install (I'm curious about rewriter in particular)?  And would it be possible to make the info message link directly to the error logs when the failure cause is not about dependency?

**Comment by SkySkimmer** [comment]
rewriter had a couple overlays since OLD so it's nothing interesting

**Pull request closed without merging**
