### PR TITLE
Fix #8291: print universe names in universe context for Check.

### LINKED ISSUE #8291: Check doesn't support nonstrict universe declaration (in printing)
~~~coq
Unset Strict Universe Declaration.
Set Printing Universes.
Check Type@{i}.
(* Type@{i}
     : Type@{i+1}
(* {Top.13} |=  *)
*)
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Why were we avoiding the shadowing of the old `sigma`?

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Added the print for Eval for #8091 since I don't want to deal with a conflict for this trivial stuff.

**Comment by Zimmi48** [comment]
@mattam82 ping

**Review by mattam82 — APPROVED** [review]
It's not clear to me why we avoided the shadowing before, maybe @herbelin has an idea. The code looks simpler and cleaner with your changes.

**Comment by Zimmi48** [comment]
@mattam82 Don't forget to self-assign when you are the only code owner.

**Comment by herbelin** [comment]
@mattam82: it is in your code (0132b5b51fc), so I guess this was a typo (actually favored by me not shadowing for no particular good reason). @skyskimmer's fix is then good :+1:.

**Pull request merged**
