### PR TITLE
Fix Univ.enforce_leq dropped constraints when algebraic on the right

### PR DESCRIPTION
**Pull request by SkySkimmer**
There's probably a proof of false using subtyping if someone wants to
look.

NB: the checker doesn't handle algebraics on the right.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I don't know why fold_right was used but fold_left is standard when the order doesn't matter.

**Comment by Zimmi48** [comment]
Hum, the code is broken.

**Comment by Zimmi48** [comment]
@SkySkimmer VST passed so I think it would make sense that you rebased #7798 on top of this one to check whether removing this instability is enough to make it go through

**Review by mattam82 — APPROVED** [review]
That’s pretty bad indeed, and certainly triggerable through module subtyping.

**Comment by SkySkimmer** [comment]
>There's probably a proof of false using subtyping if someone wants to
look.

On second thought I think it's sound, when doing `max(a_i){i<=k} <= max(b_j){j<=l}` it becomes `max(a_i){i<=k} <= b_l` so it picks a random level to be smaller than based on the hash order. The main issue is the unstability of the algorithm.

**Comment by mattam82** [comment]
Right, slightly restrictive and really unstable but it was sound indeed.
Le mar. 19 juin 2018 à 22:38, Gaëtan Gilbert <notifications@github.com> a
écrit :

**Comment by Zimmi48** [comment]
@maximedenes CI failures are all unrelated: can you merge?

**Comment by SkySkimmer** [comment]
>@maximedenes CI failures are all unrelated: can you merge?

@mattam82 is maintainer for the univ.ml (with me but I'm PR author ^^) though?

**Comment by Zimmi48** [comment]
Sorry I meant to ping @mattam82 but I was probably bitten by GitHub auto-complete.

**Pull request closed without merging**
