### PR TITLE
remove unused import of os

### PR DESCRIPTION
**Pull request by fchapoton**
found by lgtm

https://lgtm.com/projects/g/coq/coq/

**Kind:** documentation / bug fix / feature / performance / infrastructure.

Fixes / closes #????

- [ ] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.md.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ping @JasonGross

**Review by JasonGross — APPROVED** [review]
Sorry for the delay, LGTM

**Comment by JasonGross** [comment]
I'm probably not going to have much access to a computer other than my cell phone for the next two weeks, though, so if you want this merged before then, someone else should merge

**Comment by ejgallego** [comment]
Thanks @JasonGross , I can take over once you have approved.

**Pull request merged**
