### PR TITLE
Share hashing and hashconsing in lists.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1588541281

**Comment by SkySkimmer** [comment]
Did you feel that this makes the code more complicated? Getting rid of that `recursive_hcons` thing seems like a good thing even at 0% perf improvement.

**Comment by ppedrot** [comment]
It could be considered as a cleanup indeed, as it makes the code flow more explicit. If you want to merge it, I could reopen it.

**Comment by ppedrot** [comment]
I am indeed rebranding this as a cleanup. Might be worth the trouble performance-wise even in some corner cases, who knows.

**Comment by ppedrot** [comment]
@SkySkimmer this one is for you

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
