### PR TITLE
Add coq-tactician to CI

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
I'd like to revisit #13571. Unfortunately, some of the hacky workarounds in Tactician that were discussed there have not yet been resolved. But always chasing after upstream changes is also not great. So I'd like to gauge again how many objections there are regarding inclusion from the core devs.

### CODE REVIEW

**Comment by LasseBlaauwbroek** [comment]
@coqbot run full ci

**Comment by LasseBlaauwbroek** [comment]
@coqbot run full ci

**Comment by LasseBlaauwbroek** [comment]
Locally, it seems to work fine. But the CI seems to be missing `dune-site`.

**Comment by LasseBlaauwbroek** [comment]
@coqbot run full ci

**Comment by LasseBlaauwbroek** [comment]
I've now restricted the build to only the part that strictly relies on Coq.

**Comment by Alizter** [comment]
We can add dune-site if needed, just need to update the docker image.

**Comment by LasseBlaauwbroek** [comment]
> I don't mind if there are hacks, so long as we understand that if they break and it's not easy to fix the solution is to remove tactician from CI.

Fair enough.

> We can add dune-site if needed, just need to update the docker image.

Yeah, I realise now that the non-coq part has a few more dependencies, notably the Opam libraries, which are likely not in CI. Testing this in Coq's CI likely has little benefit anyway. So I think we can do without it.

If there are no objections to inclusion, then I think this is ready.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
