### PR TITLE
[coqlib] Always produce anomalies when a constant doesn't exist.

### LINKED ISSUE #10989: [API] Coqlib.lib_ref raises UserError
That if I'm not mistaken is catched by tactics. I guess it should be a fatal error, signalling some library was not loaded. As of today if you Ltac backtracking can depend on ML code not finding a Coqlib reference being registered by a not loaded v file.

### PR DESCRIPTION
**Pull request by ejgallego**
Using `user_err` means that the exception may be recoverable from tactic
code. Ideally we would have `lib_ref` to return an option type but
that was pretty invasive w.r.t. codebase.

Fixes #10989

Fix in the libraries:

- `Init.Datatypes`: `core.identity.type` is used by `destruct` or
  `auto` so we had to move it earlier.

### CODE REVIEW

**Comment by ejgallego** [comment]
Two potential problems / bugs:

```
File "./bugs/closed/bug_5066.v", line 3, characters 0-224:
Error: Anomaly "not found in table: core.JMeq.type"
```

```
File "./success/Discriminate_HoTT.v", line 64, characters 1-16:
Error: Anomaly "not found in table: core.eq.type"
Please report at http://coq.inria.fr/bugs/.
```

Interesting, I'd like to get some help as to see what is going on.

**Comment by ejgallego** [comment]
> `./success/Discriminate_HoTT.v`

In this case I guess all we have to do is to register `core.eq.type`.

**Comment by ejgallego** [comment]
> Using `user_err` means that the exception may be recoverable from tactic
> code. Ideally we would have `lib_ref` to return an option type but
> that was pretty invasive w.r.t. codebase.

We are in pretty bad situation here; I think we still lack the ability for tactics to emit non-recoverable user errors except for anomalies, right?

**Comment by Zimmi48** [comment]
I think you can with Ltac2...

**Comment by ejgallego** [comment]
> I think you can with Ltac2

Some of the error logic is in `engine` so I'm not sure, @ppedrot ?

**Comment by ppedrot** [comment]
@ejgallego you can do it with `Proofview.NonLogical.throw` which is what Ltac2 uses to implement non-recoverable exceptions.

**Comment by ejgallego** [comment]
> @ejgallego you can do it with `Proofview.NonLogical.throw` which is what Ltac2 uses to implement non-recoverable exceptions.

Yup, but unfortunately in most of the problems we have in this sense arise in non-monadic code :/

**Comment by SkySkimmer** [comment]
>@ejgallego you can do it with Proofview.NonLogical.throw which is what Ltac2 uses to implement non-recoverable exceptions.

`Unbound value Proofview.NonLogical.throw`
not sure what function you mean.

**Comment by gares** [comment]
> Yup, but unfortunately in most of the problems we have in this sense arise in non-monadic code :/

Indeed, we want an API `val fatal_error : Pp.t -> 'a` exactly as we have `user_error`. So I think we need first a new exception, and the have the monad runtime convert it to the non-logical one.

**Comment by ejgallego** [comment]
> `Unbound value Proofview.NonLogical.throw`
> not sure what function you mean.

I guess he means `raise` ?

> Indeed, we want an API `val fatal_error : Pp.t -> 'a` exactly as we have `user_error`. So I think we need first a new exception, and the have the monad runtime convert it to the non-logical one.

That would work, but I'm a bit reluctant to just go and add it; I think the whole treatment of exceptions needs a deeper revision, for example I'd like to seal `UserErr` but that's not possible yet.

I'd like to discuss with people a bit more to see how can we handle this.

**Comment by herbelin** [comment]
Are there plans about this PR?

@gares' suggestion to add a `fatal_error` registration looks good, no? Or maybe should it be `non_proof_engine_recoverable_error` so that the callers can still catch the corresponding specific error w/o looking like recovering from an anomaly?

Regarding `Coq.lib_ref`, isn't it also that we should fix the API once for all, whether it raises a `UserErr` that the caller is supposed to catch if unsure, or it raises an anomaly and the caller is supposed to check that it exists beforehand with some `mem` function, or it raises a specific option declared as not-proof-engine-catchable, or to return an option type. (I believe my preference would be for returning an option type.)

**Pull request closed without merging**
