### PR TITLE
[experiment] Use kernel reduction in Unification.expand reduction.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/2046992450

**Comment by ppedrot** [comment]
This is faster on some cherry-picked examples, but I don't see much effect on the bench. Not sure if worth it.

**Comment by Janno** [comment]
I might be biased but I would be glad to see more places use kernel reduction. That way when kernel reduction improves, many other things improve as well.

**Comment by ppedrot** [comment]
Well, not only that, you should also consider the fact that the high-level reduction is utterly naive and uses eager substitution all over the place.

**Pull request closed without merging**
