### PR TITLE
Adding a "smart" version of List.fold_left_map and List.fold_right_map

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** cleanup

The applications are rare but I guess it cannot hurt.

### CODE REVIEW

**Comment by Alizter** [comment]
Worth a bench?

**Comment by herbelin** [comment]
Ok, I started one. I'm unsure that the three functions liable to take benefit of it are enough used so that it is visible. `Constr.fold_map_invert` is about small structures at first glance. `Constr.fold_map` is not really used. The most used is probably `Environ.map_named_val`, in the proof engine.

**Comment by SkySkimmer** [comment]
>Constr.fold_map_invert is about small structures at first glance

Also only when uip is on, so the bench won't see it.

**Comment by herbelin** [comment]
Should this be considered a bit positive or too much in the noise range?
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬───────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │    mem faults     │
│                             │                         │                                       │                                       │                         │                   │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD    PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼───────────────────┤
│                coq-coqprime │  176.69   181.68  -2.75 │   806384854302    828686855110  -2.69 │  1560674199559   1560757811971  -0.01 │  905076   907040  -0.22 │   0    0      nan │
│      coq-mathcomp-ssreflect │   25.83    26.14  -1.19 │   116648477918    118251030478  -1.36 │   148337986293    148369659157  -0.02 │  532236   532540  -0.06 │   0    0      nan │
│                  coq-stdlib │  402.28   406.84  -1.12 │  1648722509304   1663194493105  -0.87 │  1446328306085   1446370062817  -0.00 │  602988   604456  -0.24 │   0    0      nan │
│              coq-coquelicot │   34.41    34.79  -1.09 │   154072179004    155913875455  -1.18 │   203176578841    203164576743   0.01 │  747744   747472   0.04 │   3    0      nan │
│               coq-fiat-core │   53.66    54.19  -0.98 │   231430870726    234492492144  -1.31 │   323610265708    323585835848   0.01 │  473124   473112   0.00 │   0    0      nan │
│            coq-math-classes │   93.34    93.95  -0.65 │   421581997532    424455147573  -0.68 │   592697156106    592688665032   0.00 │  495752   495952  -0.04 │   0    0      nan │
│                coq-compcert │  291.43   293.29  -0.63 │  1311189819395   1320594385914  -0.71 │  1950303293830   1950315152953  -0.00 │ 1098380  1097096   0.12 │   0    0      nan │
│                 coq-coqutil │   34.47    34.67  -0.58 │   154443460810    155239166039  -0.51 │   207390844979    207447010990  -0.03 │  601240   601132   0.02 │   0    0      nan │
│                 coq-bignums │   28.40    28.56  -0.56 │   128661306762    129540527020  -0.68 │   176152635442    176179256460  -0.02 │  466160   467876  -0.37 │   0    0      nan │
│            coq-fiat-parsers │  332.11   333.96  -0.55 │  1473648013091   1482077197106  -0.57 │  2438940387701   2438957640173  -0.00 │ 3538212  3537084   0.03 │   0    0      nan │
│           coq-iris-examples │  463.57   466.02  -0.53 │  2103592064527   2113584390283  -0.47 │  3162828448958   3162976806947  -0.00 │ 1181116  1181360  -0.02 │   0    5  -100.00 │
│                    coq-core │   96.07    96.54  -0.49 │   389815448545    386550421574   0.84 │   433381925933    433305588485   0.02 │  249964   249620   0.14 │   0    0      nan │
│       coq-engine-bench-lite │  178.55   179.40  -0.47 │   765877781175    771232957779  -0.69 │  1498908104303   1497909272882   0.07 │ 1173848  1173588   0.02 │   0    0      nan │
│                    coq-hott │  153.69   154.23  -0.35 │   691736120557    693118113159  -0.20 │  1082583793427   1082592127503  -0.00 │  662296   659548   0.42 │   0    0      nan │
│      coq-mathcomp-odd-order │  557.67   559.16  -0.27 │  2550896555943   2557954100091  -0.28 │  4338835180931   4338687223858   0.00 │  932824   932872  -0.01 │   0    0      nan │
│               coq-perennial │ 4150.35  4161.08  -0.26 │ 18843920110346  18873475553428  -0.16 │ 31051310094463  31050384079577   0.00 │ 2627036  2627040  -0.00 │   4    0      nan │
│       coq-mathcomp-solvable │   87.29    87.51  -0.25 │   398398989418    399491908185  -0.27 │   616835074260    616823286596   0.00 │  670564   670852  -0.04 │   0    0      nan │
│                    coq-corn │  797.85   799.82  -0.25 │  3618670199699   3631202113746  -0.35 │  5599098251280   5599243065958  -0.00 │  826100   826172  -0.01 │   0    0      nan │
│          coq-mathcomp-field │  113.96   114.23  -0.24 │   520475889130    521692574321  -0.23 │   856536444157    856502080547   0.00 │  657196   657780  -0.09 │   0    0      nan │
│                   coq-verdi │   48.63    48.70  -0.14 │   219010060024    219843106486  -0.38 │   325214972525    325177164357   0.01 │  826764   827156  -0.05 │   0    0      nan │
│  coq-performance-tests-lite │  788.00   788.80  -0.10 │  3540824559629   3546213171924  -0.15 │  6029070877834   6028973601587   0.00 │ 1825920  1829356  -0.19 │   0    0      nan │
│                  coq-flocq3 │   76.09    76.16  -0.09 │   345234663731    345538815269  -0.09 │   456317781593    456209901100   0.02 │  989948   988264   0.17 │   7    0      nan │
│             coq-fiat-crypto │ 2945.47  2947.29  -0.06 │ 13289489049679  13302316402997  -0.10 │ 24431229284551  24420543800565   0.04 │ 3855120  3854108   0.03 │   1    0      nan │
│      coq-mathcomp-character │   76.60    76.61  -0.01 │   349686578793    349890707395  -0.06 │   531609569781    531652471459  -0.01 │  735676   738440  -0.37 │   0    0      nan │
│              coq-verdi-raft │  581.57   581.61  -0.01 │  2647420232006   2648725859067  -0.05 │  4052474257854   4052510240328  -0.00 │ 1218724  1217256   0.12 │   0    0      nan │
│                     coq-vst │ 1151.63  1151.60   0.00 │  5224030321179   5220386296326   0.07 │  8432071635815   8432546300771  -0.01 │ 1893468  1892308   0.06 │   5    0      nan │
│                   coq-color │  264.23   264.19   0.02 │  1189016746017   1191039432541  -0.17 │  1608876894375   1608970236414  -0.01 │ 1174728  1176476  -0.15 │   0    0      nan │
│        coq-mathcomp-algebra │   63.59    63.43   0.25 │   289872001373    289018345845   0.30 │   401855615736    401949263932  -0.02 │  558704   558460   0.04 │   0    0      nan │
│                coq-bedrock2 │  189.59   189.08   0.27 │   850689811145    849573486796   0.13 │  1571342412777   1571428817618  -0.01 │ 2053804  2053892  -0.00 │   0    0      nan │
│                  coq-geocoq │  718.49   715.91   0.36 │  3266934553144   3256653462213   0.32 │  5160039987606   5159980497942   0.00 │ 1077188  1079988  -0.26 │   0    0      nan │
│ coq-rewriter-perf-SuperFast │  931.76   927.29   0.48 │  4197331639854   4175635622317   0.52 │  7286493089255   7287090733256  -0.01 │ 1148068  1147812   0.02 │  16    0      nan │
│                coq-rewriter │  375.48   373.66   0.49 │  1700159647856   1692731595731   0.44 │  2776289133372   2775477138525   0.03 │ 1059824  1063192  -0.32 │   0    0      nan │
│       coq-mathcomp-fingroup │   23.33    23.20   0.56 │   106527415720    106016902206   0.48 │   156299558860    156301702096  -0.00 │  477640   477824  -0.04 │   0    0      nan │
│                 coq-unimath │ 3379.68  3353.44   0.78 │ 15387393846188  15266286478802   0.79 │ 30525645714786  30526950511571  -0.00 │ 3895996  3895512   0.01 │   0    0      nan │
│               coq-fourcolor │ 1510.86  1497.90   0.87 │  6676947269338   6622531869848   0.82 │ 12092831784483  12092698529953   0.00 │  726348   726348   0.00 │   0    0      nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴───────────────────┘
```

**Comment by ppedrot** [comment]
coqprime is very noisy, so it's not surprising. I think the rest can be safely considered as noise.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
