### PR TITLE
Rename Lexer -> Coq_lexer to fix flambda build

### PR DESCRIPTION
**Pull request by mshinwell**
Current Coq v8.5 will not build with high optimization on flambda due to an implementation inconsistent assumptions error on Lexer.  We think this is because, when using camlp4, we end up with two modules called "Lexer" (one from OCaml compiler-libs and one from Coq parsing/lexer.mll) in the same program.  This pull request renames the Coq one to avoid the clash.

We think that it's strange that there wasn't an _interface_ inconsistent assumptions error, probably between the Camlp4 pack and Coq's Lexer module, which may indicate another compiler bug.  However even if such a bug was not present, it is not sufficient to prevent a problem, since the two modules could in theory have the same interface.

### CODE REVIEW

**Comment by herbelin** [comment]
It looks like it is not a big deal for Coq's development. It is ok as far as I'm concerned.

**Comment by maximedenes** [comment]
That issue of name clashes should be discussed seriously with the OCaml team. I believe "Lexer" is not the only name clash occurring between Coq and compiler-libs, is it? OCaml should provide a reliable way to avoid these problems.

**Comment by herbelin** [comment]
Indeed, it would help if OCaml could make progress on this kind of things.

For the record, toplevel/errors.ml and pretyping/matching.ml had already been renamed into toplevel/cerrors.ml and (now) pretyping/constr_matching.ml for reasons of clash with modules from OCaml.

At the current time, I still have lib/errors.ml reported as occurring both in coq and compiler-libs with OCaml 4.02.3 but apparently without bad consequences. Whether I'm using camlp5 or camlp4, I don't have a clash reported on lexer.cmi, even though there is one in compiler-libs. So, indeed, there seems to be something to investigate more that you could do with Maxime.

**Comment by mshinwell** [comment]
I've pushed another changeset that renames Ephemeron to Coq_ephemeron, since that also now clashes with upstream OCaml trunk.

@herbelin You probably didn't see the clash on Lexer because you weren't (I assume) building with Flambda and high optimization.

I don't think there is any likelihood of upstream OCaml changing the problematic names in the short term.  Packing compilerlibs isn't going to happen.  As such the only solution is likely to be the adoption of some more sophisticated namespacing proposal (and we're not there yet unfortunately).

**Comment by mshinwell** [comment]
@herbelin (Also, in this case there probably should have been an interface mismatch error on the Lexer modules, possibly even without flambda, but for some reason that doesn't happen.  This is presumably due to a compiler bug.  That said, an interface mismatch error in the general case is not sufficient to catch these name clash problems of course, since the interface might be the same...)

**Comment by mattam82** [comment]
I'm fine with prefixing lexer, ephemeron etc... to avoid the problem. However I'd like to understand why compiler-libs is not going to be packed. It seems like the easy way out, isn't it @mshinwell, @gashe?

**Comment by maximedenes** [comment]
I talked a bit with Xavier about this. We should distinguish clashes with OCaml's stdlib (like "Ephemerons", already fixed in 8.5), which we can easily live with (they don't occur often). However, compiler-libs is much more of a problem, since there are many very common names and it changes. Like @herbelin  said, "Lexer" is not the only clash currently, there is also "Errors". Of course we can rename these two without guarantees about future clashes, but like @mattam82 I'd like to know why packing compiler-libs isn't going to happen on OCaml's side.

**Comment by herbelin** [comment]
Amusingly, I made a change to a file using lexer.ml and the inconsistency showed up. Could it be that whether the inconsistency is reported depends on the order of the value of the checksum of the files, or something like that? Anyway, this being fragile, I would be leaning to pull the patch without delay.

**Comment by mattam82** [comment]
We agreed to merge the foo -> cfoo renamings, @mshinwell or @he

**Comment by ppedrot** [comment]
So what do we do? Do we just dump this PR and reimplement it from scratch? (Not a hard work, but just asking.)

**Comment by mattam82** [comment]
Yes, that's the idea. @herbelin was ok with that too, but if you have spare cycles to do it, it's yours :)

**Comment by ppedrot** [comment]
All right. Should I patch 8.5 as well?

**Comment by mattam82** [comment]
I think so.

**Comment by ppedrot** [comment]
This'll break at least mathcomp... Well', let's go.

**Comment by ppedrot** [comment]
Fixed in a66b57b.

**Pull request closed without merging**
