### PR TITLE
Use a more traditional definition for uint63_div21 (fixes #10551).

### LINKED ISSUE #10551: vm_compute in 8.10
There is something terribly wrong with `vm_compute` in Coq 8.10. This was first noticed by @MSoegtropIMC, who is experiencing strange failures with CoqInterval (https://github.com/coq/coq/pull/10522#issuecomment-513721248). I am still in the process of reducing the testcase, so it still depends on CoqInterval, sorry. By the way, one can trivially build a proof of `False` from the testcase, since `vm_compute` disagrees with `cbv`.

```coq
From Coq Require Import Reals List.
From Bignums Require Import BigZ.
From Interval Require Import Interval_tactic Interval_xreal Interval_bisect Interval_specific_ops.
Import ListNotations Private.

Lemma foo (x : R)
(H : (0 <= x <= 1 / 512)%R)
(formula := [Unary (PowerInt (Z.of_nat (1 + (1 + 0)))) 0; Unary (PowerInt (Z.of_nat 32)) 3;
           Binary Div 5 0; Binary Mul 0 2; Binary Add 0 5;
           Unary (PowerInt (Z.of_nat (1 + 0))) 5; Binary Div 10 4; 
           Binary Mul 0 1; Binary Add 0 3; Unary (PowerInt (Z.of_nat 0)) 9;
           Binary Div 15 8; Binary Mul 0 1; Binary Add 0 3;
           Unary (PowerInt (Z.of_nat 2)) 13; Binary Add 20 0; 
           Unary Sqrt 0; Binary Add 16 0; Binary Div 23 0; Unary Atan 0; 
           Unary Sin 0; Binary Sub 0 7; Unary Abs 0; Unary (PowerInt (Z.of_nat 34)) 24;
           Binary Div 29 0; Binary Sub 0 2] : list term)
(bounds := [A.Bproof x (I.bnd SFBI2.zero (Float 1%bigZ (-9)%bigZ)) H;
          let f := SFBI2.zero in
          A.Bproof (I.T.toR SFBI2.zero) (I.bnd f f)
            (conj (Rle_refl (I.T.toR SFBI2.zero)) (Rle_refl (I.T.toR SFBI2.zero)));
          let f := Float 1%bigZ 1%bigZ in
          A.Bproof (I.T.toR (Float 1%bigZ 1%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float 1%bigZ 1%bigZ))) (Rle_refl (I.T.toR (Float 1%bigZ 1%bigZ))));
          let f := Float (-23622187)%bigZ 4%bigZ in
          A.Bproof (I.T.toR (Float (-23622187)%bigZ 4%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float (-23622187)%bigZ 4%bigZ)))
               (Rle_refl (I.T.toR (Float (-23622187)%bigZ 4%bigZ))));
          let f := Float (-759250737)%bigZ 1%bigZ in
          A.Bproof (I.T.toR (Float (-759250737)%bigZ 1%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float (-759250737)%bigZ 1%bigZ)))
               (Rle_refl (I.T.toR (Float (-759250737)%bigZ 1%bigZ))));
          let f := Float 759250125%bigZ 2%bigZ in
          A.Bproof (I.T.toR (Float 759250125%bigZ 2%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float 759250125%bigZ 2%bigZ))) (Rle_refl (I.T.toR (Float 759250125%bigZ 2%bigZ))));
          let f := Float 1%bigZ 0%bigZ in
          A.Bproof (I.T.toR (Float 1%bigZ 0%bigZ)) (I.bnd f f)
            (conj (Rle_refl (I.T.toR (Float 1%bigZ 0%bigZ))) (Rle_refl (I.T.toR (Float 1%bigZ 0%bigZ))))] : list A.bound_proof) :
match bounds with
| A.Bproof _ (Interval_interval_float.Ibnd l u) _ :: tail =>
    let fi :=
      fun b : I.type =>
      A.TaylorValuator.TM.eval (prec_of_nat 60, 2%nat)
        (nth 0
           (A.TaylorValuator.eval (prec_of_nat 60) 2 b formula
              (A.TaylorValuator.TM.var
               :: map
                    (fun b0 : A.bound_proof =>
                     A.TaylorValuator.TM.const (A.interval_from_bp b0)) tail))
           A.TaylorValuator.TM.dummy) b b in
    A.bisect_1d l u (fun b : I.type => A.check_f A.positive_check (fi b)) 5 = true
| _ => False
end.
Proof.
vm_compute. (* false = true *)
apply eq_refl.
Qed.
```

### PR DESCRIPTION
**Pull request by silene**
This code has not been tested. It is just there to show how a naive division algorithm is supposed to look like. This new version is shorter, faster, and hopefully less buggy than the current one.

### CODE REVIEW

**Comment by proux01** [comment]
Sounds really nice, I just have a few remarks:
* I do agree with the initialization and preservation of the loop invariant, but when exiting the loop, we get `q * y + nh = (xh % y)*2^63 + xl` which does not look to me exactly what we are looking for (i.e. it seems to be the division of (xh%y,xl) by y instead of the division of (xh,xl)), I guess the following should fix this
  * initialize `q` as `xh / y` instead of `0`
  * change `xh % y` by `xh` in the invariant
  * change `Val_int(q)` to `Val_in(q % 2^63)`
  * as `q` can overflow, a kind of ghost variable `qh` might have to be introduced
    to preserve the invariant
* Do you think you could port this algorithm to the two other implementations in OCaml ?
(c.f. https://github.com/coq/coq/pull/10046#issue-275251724)
* Of course, the test case that led here should be added in the test suite
(file `test-suite/arithmetic/diveucl_21.v`).

**Comment by silene** [comment]
> it seems to be the division of `(xh%y,xl)` by `y` instead of the division of `(xh,xl)`

Remember that we are looking for the quotient restricted to its lower word. So, the result cannot distinguish between `xh` and `xh % y` (or any other upper word of the dividend congruent to `xh` modulo `y`). What you propose is correct, but ultimately pointless: you initialize `q` with `xh / y`, then shift it 63 times to the left, and finally return `q % 2^63`, which means that whatever you used to initialize `q` is completely lost.

> Do you think you could port this algorithm to the two other implementations in OCaml?

Sure.

**Comment by proux01** [comment]
Indeed, nice point!

As a small remark that might even further simplify the code, as noted in https://github.com/coq/coq/issues/10551#issuecomment-514221147 all uses of the function by Bignum are done in cases where no overflow can happen so, if we update the specification,
`xh % y` could just be replaced by `xh`

**Comment by silene** [comment]
> `xh % y` could just be replaced by `xh`

That is not sufficient. The function is still total, so its behavior needs to be consistent across all implementations, even if the inputs fall outside its specification domain. Otherwise, proving false is trivial. Note that it might be as simple as adding a test `xh < y` at the start of `uint63_div21`.

**Review by proux01 — APPROVED** [review]
Congratulation for the -76 lines!

**Comment by maximedenes** [comment]
@bgregoir told me this is not the way it should be done (he said we should rather follow the certified implementation @thery and him had), but he had to leave and is now away for holidays. I'd like to get a bit of time to review this PR with @thery.

I'm probably the one who introduced all this mess, not sure where my mind was when I wrote this code, so sorry about that.

**Comment by MSoegtropIMC** [comment]
I just compiled this branch and verified that my developments using CoqInterval, which lead to detecting this error, work again. This are 24 precision (> 32 bit) polynomial approximations of transcendental functions (which I unfortunately cannot share). This should contain many divisions with rather tight error bounds, so this should be a fairly tough test.

If there is interest, I could create a few CoqInterval test cases which should detect this and many other possible errors in numerical vm_compute.

Since this fixes a proof of False, I would vote for merging it like this into 8.10 and master now and discuss possibly better options later.

@vbgl : what is your opinion on this?

**Comment by vbgl** [comment]
Thanks for your careful testing. Here is what I understand from the current situation.

There is a critical bug in the 8.10 and master branches, so we must correct it before the next release.

Guillaume presented two fixes that address the issue: this PR and adding a missing bit masking (as implemented here: https://github.com/vbgl/coq/commit/3fdf7e99fbbac83ed5739069176aed62df92dd7e). Guillaume also noted that the current implementation is complex and hard to understand.

Maxime expressed some concerns about this PR: a primitive operation should not be implemented using a naive algorithm. He recommends that the implementation in the kernel follows an efficient algorithm that is itself formally verified. He suggests to implement TAOCP algorithm for long division.

So we have two implementations: one too simple, one too complex. Let’s wait a few days to see if a third implementation that pleases everyone show up.

**Comment by MSoegtropIMC** [comment]
If this helps I could verify this or another C implementation against the spec using Princeton VST.

**Comment by silene** [comment]
If you want something fast, portable, and reasonably safe, do not even try to implement the algorithm from TAOCP, just trust your C compiler.

I have benchmarked various implementations of `uint63_div21` on a i7-7600U processor:
1. the current implementation in Coq, with the trivial fix,
2. the proposed implementation (optimized by assuming that the specification of div21 is modified, i.e., no early modulo),
3. the pure single assembly opcode (which requires that the specification of div21 is modified to avoid exceptions),
4. the compiler implementation, aka `udivmodti4`.

The number of cycles per division are as follows:
1. 344
2. 173
3. 86
4. 94

So, the version I propose is twice as fast as the current one (even without the modification to the specification). The pure assembly version is twice as fast as the version I propose. And the compiler version is almost as fast, as it basically does a bunch of comparisons before it concludes that calling the assembly version is safe.

Also, you might wonder why the assembly code is only twice as fast as my naive algorithm. That is due to division on x86 being also implemented using a linear algorithm, except that it uses radix 4 instead of radix 2, so it takes half as many cycles. (On Itanium, they went for a quadratic algorithm, the performances were impressive, and so was the energy consumption.)

Finally, if even the processor is using a naive algorithm, you might wonder whether you can beat the assembly version (or the compiler version) using some plain code. In that case, just have a look at GMP. Its developers have concluded that it was not possible.

**Comment by thery** [comment]
@silene I am a bit puzzled. I thought the division algorithms of current processor were using at least using radix 16, so we should always be better off trying to use some 64 bits divisions. If this is not the case, your algo is clearly ok.

**Comment by silene** [comment]
I didn't want to enter too much into details. More precisely, a common implementation uses two cascading radix-4 basic blocks, which indeed amounts to a radix-16 algorithm. But the number of cycles needed for such a pseudo radix-16 algorithm is not quite a quarter as for radix-2 algorithms. And if you take into account the time needed to initiate the division (my benchmark accounts for function calls and the like), the gain becomes less noticeable. That said, I was expecting the assembly to nonetheless perform much better, say three times as fast, rather than just twice as fast.

**Comment by thery** [comment]
@silene still puzzled. I've tried to google udivmodti4.c, but  what I found looks to me like some
full 128 bits division code. Where can I see the c code of 4 that is benchmarked?

**Comment by MSoegtropIMC** [comment]
I would prefer the algorithm proposed by @silene for the following reasons:

- the performance difference of a factor of 2 for division shouldn't make a relevant performance difference for practical purposes
- it is less system dependent than relying on the compiler
- it is a plain and clean while the previous implementation was hard to understand
- I can verify it with VST, if this would help the case
- it survives rather tough test cases
- it is unlikely that one can come up with an implementation which is substantially faster, safer or otherwise better than this in a short time

**Comment by SkySkimmer** [comment]
>   * it is less system dependent than relying on the compiler

Don't we rely on the compiler regardless?

Gaëtan Gilbert

**Comment by MSoegtropIMC** [comment]
> Don't we rely on the compiler regardless?

sure, but + and shift and loops are more commonly used features than "double quadword" division, so it is less likely that there are bugs in there. I would think if vm_compute would have had a bug in plain 63 bit addition, we would have found out much earlier.

Maybe in a not so far future we can compile Coq with certified compilers (CertiCoq + CompCert).

**Comment by silene** [comment]
> but what I found looks to me like some full 128 bits division code. Where can I see the c code of 4 that is benchmarked?

It is a 128-by-128 division, but it first tests whether it can defer it to the 128-by-64 divisor of the processor. Here is the C code I benchmarked:
```c
uint64_t f4(uint64_t x, uint64_t y, uint64_t z, uint64_t *q) {
  unsigned __int128 w = x;
  w = (w << 63) | y;
  *q = w / z;
  return w % z;
}
```

**Comment by thery** [comment]
> ```c
>   *q = w / z;
>   return w % z;
> ```

Just a naïve question, I would have done w - q * z instead of w % z. Is this equivalent?

**Comment by silene** [comment]
Semantically yes, but there is a small difference for the generated code. Indeed, GCC is able to detect that `w / z` and `w % z` are the two sides of a single division, but not when you use `w - *q * z`. As a consequence, it compiles the later to `udivti3` followed by a multiplication and a subtraction. That said, it does not make any noticeable difference on performance.

**Comment by thery** [comment]
@silene Thanks! Still puzzling. Anyway I think we should merge your version with the fix on the spec for 8.10.

**Comment by silene** [comment]
Note that the fix on the specification is not strictly needed. (It gains only a few cycles.) I would suggest we delay that work to 8.11, so that we don't have to rush to adapt Bignums to the new specification.

**Comment by thery** [comment]
I am a bit lost here. I must miss something. Bignum was built with the idea that div21 would never
overflow so it should be almost insensitive to the change of spec.

**Comment by silene** [comment]
Sure. But we all know what kind of impact an innocuous change in a theorem statement can have on the subsequent Coq proofs. Adapting Bignums is not something I can promise to be completed in the next few days.

**Comment by thery** [comment]
> Adapting Bignums is not something I can promise to be completed in the next few days.

Submit your change of spec, then we'll see if the break in Bignum is easily fixable.

**Comment by silene** [comment]
In `theories/Numbers/Cyclic/Int63/Int63.v`, change

```coq
Axiom diveucl_21_spec :  forall a1 a2 b,
   let (q,r) := diveucl_21 a1 a2 b in
   let (q',r') := Z.div_eucl ([|a1|] * wB + [|a2|]) [|b|] in
   [|q|] = Z.modulo q' wB /\ [|r|] = r'.
```

into

```coq
Axiom diveucl_21_spec :  forall a1 a2 b,
   let (q,r) := diveucl_21 a1 a2 b in
   let (q',r') := Z.div_eucl ([|a1|] * wB + [|a2|]) [|b|] in
   [|a1|] < [|b|] -> [|q|] = q' /\ [|r|] = r'.
```

Obviously, before even considering Bignums, Coq's standard library needs to be adapted.

**Comment by thery** [comment]
Ok, I see if I can find some time tonight to play with this

**Comment by thery** [comment]
if @proux01 is not on holiday, it would be nice if he could give his opinion

**Comment by thery** [comment]
for Coq. It looks like the new spec simplifies the proof.
https://github.com/thery/coq/commit/030d37ced3bbc47a9a7a837993abfcd2c9aec84d
for Bignums, nothing is broken.

**Comment by silene** [comment]
Do you mean that Bignums never calls `diveucl_21_spec` directly? I didn't expect that. So, I will just rebase my patch on top of yours.

**Comment by thery** [comment]
> Do you mean that Bignums never calls `diveucl_21_spec` directly

seems so!

> So, I will just rebase my patch on top of yours.

very good.

**Comment by silene** [comment]
It went well.

That said, now that I know that users rely on `diveucl_21_spec_aux` instead of `diveucl_21_spec`, and that the former has a superfluous hypothesis stating that the divisor is normalized, this opens the way to fast division algorithms, some of which might even be faster than in-silicon implementations. But that is certainly not 8.10 material.

**Comment by vbgl** [comment]
So it seems that we should merge this PR in Coq 8.10. Then, we may investigate other implementations for this primitive.

Ping asignee @maximedenes

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
