### PR TITLE
[clib] Deprecate string functions available in OCaml 4.05

### PR DESCRIPTION
**Pull request by ejgallego**
- `CString.strip -> String.trim`
- `CString.split -> String.split_on_char`

### CODE REVIEW

**Comment by ppedrot** [comment]
Note that the semantics of both variants are marginally different. For instance, OCaml `trim` also takes line feeds (LF) into account. Similarly, OCaml `split` never returns an empty list whereas Coq `trim` does on the empty string.

**Comment by ejgallego** [comment]
> Note that the semantics of both variants are marginally different. For instance, OCaml `trim` also takes line feeds (LF) into account. Similarly, OCaml `split` never returns an empty list whereas Coq `trim` does on the empty string.

[You mean split not trim, right].

Noted in the commit message, IMHO the OCaml semantics are preferred, if only for the lower maintenance burden.

**Comment by ppedrot** [comment]
If CI compiles I'll merge this quickly.

**Review by ppedrot — APPROVED** [review]

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
CI failure is unrelated.

**Pull request merged**
