### PR TITLE
Update CODEOWNERS (mostly regarding the test-suite)

### LINKED ISSUE #7426: Need owner for test-suite infrastructure and specific components
Currently, the test-suite has no owner because it would be more spam than anything each time someone adds a test file in `bugs/` (same is true for `CHANGES` for instance). However, there are a few infrastructure or documentation files in `test-suite/` that are not modified so often and would deserve an owner:

- `Makefile`
- `save-logs.sh`
- `_CoqProject`
- `README`

Who would be volunteer to be an owner for these files? Let me propose a few names: @gares @herbelin  @JasonGross @SkySkimmer. We need two volunteers.

Furthermore, Jim has continued Paul's work to add a unit-test framework to the test-suite in #6808 and there are two new small infrastructure files introduced there in `test-suite/unit-tests/src/` who would also need owners (potentially the same people). There is the idea however that tests in the `unit-test/` folder will be organized component-wise and the maintainers for each component will naturally become the owners of the unit tests for this component.

More generally, the test-suite is already partially organized by components and there seem to be a will (see #7227) to go further in a component-based hierarchy. Thus, some current and upcoming test folders could have owners who would naturally be the same as for the corresponding component. This should avoid any spurious review requests. The folders already concerned are `coqchk` `coqdoc` `coq-makefile` `coqwc` `ide` `interactive` `micromega` `modules` `stm` `typeclasses` and `vio`. All these folders should naturally have owners. To this, we can soon add `ssr` (see #7227).

Even if it is not a "component" I feel like the `complexity` folder would also need an owner (@herbelin?).

### PR DESCRIPTION
**Pull request by Zimmi48**
This PR is in two parts:

- Add @ppedrot to the list of secondary maintainers for the kernel (without removing @barras). This should mitigate #7346 further and reflect the reality of the situation in #7521 for instance.

- Add maintainers for the test-suite infrastructure and well-delimited components (closes #7426).

@gares agreed to be the primary maintainer for the test-suite. @SkySkimmer is that OK that I put you as the secondary one? (And first one for `save-logs`?)

@jfehrle Would you like to be the primary maintainer for the unit-test infrastructure? The documentation of what is expected of maintainers is here: https://github.com/coq/coq/blob/master/dev/doc/MERGING.md. *You should completely feel free to say no.* I put @SkySkimmer again as secondary maintainer (is that OK with you @SkySkimmer?)

When parts of the test-suite correspond to specific components, I put the same maintainer as for the component. The idea is that these parts will likely be updated simultaneously so this shouldn't create much more noise. We can experiment what it gives in practice. To ease the maintenance, I put these components of the test-suite, not in the test-suite section but in their respective component sections. This is also true for unit tests. For now, there is only `clib/` but as soon as we had more unit tests we should update this file further...

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Review by ppedrot — DISMISSED** [review]
I think we also need a secondary maintainer for the checker. There are a bunch of checker fixes waiting to be integrated and nobody taking care of them nor morally allowed to do so. This is a serious issue.

**Comment by jfehrle** [comment]
@Zimmi48 I'd be happy to be a reviewer for the unit-test infrastructure.  I'm less eager to take on the merging because that would let me make inadvertent mistakes that could be hard to recover from.  And I am apt to make at least some small mistakes the first couple times.  Plus a bunch more details to master...

How do we recover if a maintainer makes some disastrous mistake?  Do we have a way to recover an earlier good version of the repository if it gets messed up?  (My use of "recover" including possibly replacing git repository/metadata files in the server file system if that's ever a sane thing to do.)

Also, FWIW:
- in the MERGING.md document, "deprecationg propagation" didn't make sense.
- "overlays" seems an odd choice of terminology.  I don't entirely understand the purpose or concept.
- dev/ci/user-overlays/README.md is not very informative.  The first sentence is less than clear ("An overlay is a file" vs "so that overlays work on your own fork").

```
An overlay is a file containing very simple logic to test whether we are currently building
a specific pull request or git branch (useful so that overlays work on your own fork) and
which changes some of the variables whose default can be found in ci-basic-overlay.sh.
```

**Comment by SkySkimmer** [comment]
>@Zimmi48 I'd be happy to be a reviewer for the unit-test infrastructure. I'm less eager to take on the merging because that would let me make inadvertent mistakes that could be hard to recover from. And I am apt to make at least some small mistakes the first couple times. Plus a bunch more details to master...

Merging is just running the merge script when a PR is ready, which runs some automatic checks (eg did CI succeed) then runs git merge. You are not supposed to fix conflicts.
Github will stop you from force pushing so it's always possible to revert.

**Comment by Zimmi48** [comment]
@jfehrle There are indeed quite a few checks in place that should make it quite safe to perform a merge and you wouldn't be blamed if a mistake slipped in anyways but that's your call of course. Thanks for the comments on the doc. I'll try to propose improvements.

**Comment by Zimmi48** [comment]
@ppedrot Should I add you as a secondary maintainer of the checker as well? (@maximedenes is already a secondary maintainer of the checker so he can handle the PRs that are not his own.)

**Comment by jfehrle** [comment]
OK, I'll give it a try.  I will automatically get an email when a relevant PR is created?

**Comment by ppedrot** [comment]
@Zimmi48 I'm fine with that.

**Comment by maximedenes** [comment]
Let's not stay with components whose principal maintainer is not reactive. @ppedrot, can you become the principal maintainer of the checker instead of a secondary one?

**Review by maximedenes — APPROVED** [review]
LGTM apart from my remark that @ppedrot should be the principal maintainer of the checker, not a secondary one.

**Comment by ppedrot** [comment]
@maximedenes Why not.

**Pull request merged**
