### PR TITLE
Prevent useless typing in Equality.subst_tuple_term

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
What uses this function? Is it just `dependent rewrite` and `cutrewrite`?

**Comment by ppedrot** [comment]
I think it's used internally by inversion as well.

**Comment by SkySkimmer** [comment]
(test suite failed in the bench because it ran the test suite for master with the coq from this PR which is missing a few commits compared to master)

**Comment by ppedrot** [comment]
Regardless of the optimizations, I think I'll submit the first commit alone as a cleanup as it makes the code simpler.

**Pull request closed without merging**
