### PR TITLE
Relaxing syntax of parameters in well-formedness of inductive types.

### PR DESCRIPTION
**Pull request by herbelin**
The main part of this PR is to do that parameters are considered up to conversion rather than syntactically being variables in the definition of an inductive type. This allows for instance to support the following:

```coq
Inductive sig {A:Type} (P:A -> Prop) : Type :=
    exist : forall x:A, P x -> { x : A | P x }
where "{ x : A |  P }" := (sig (fun x : A => P)) : type_scope.
```
where the parameter P appears not as a variable but as an eta-expanded variable.

The rest of the PR is more about raising questions.

The PR contains also a commit experimenting defining `ex`, `sig`, `sigT`, `ex2`, `sig2`, `sigT2` jointly with their notation. This is not anodyne, as it introduces an η-expansion which has an effect on how the type of the constructor is printed, and which also has an effect on pattern-matching on the type of such a constructor, what raises question on how robust is the system wrt such trivial conversion.

The PR contains also a commit proposing to replace the use of `sig`, `sigT`, `sig2`, `sigT2` which were not using a notation in `Specif.v` by using the notations (in relation with the discussion at PR #385). Again, this means changing the type of the corresponding functions by addding an η-expansion (is this an extra argument to tell that substitution of terms creating βɩ-redexes should maybe reduce those redexes on the fly?).

The PR also contains two fixes already committed in branch 8.5 (so, to be eventually absorbed when merging v8.5).

### CODE REVIEW

**Comment by JasonGross** [comment]
> The PR contains also a commit experimenting defining ex, sig, sigT, ex2, sig2, sigT2 jointly with their notation. This is not anodyne, as it introduces an η-expansion which has an effect on how the type of the constructor is printed, and which also has an effect on pattern-matching on the type of such a constructor, what raises question on how robust is the system wrt such trivial conversion.

Is there any reason to prefer this over record syntax, i.e.,
```coq
Record sig {A:Type} (P:A -> Prop) :=
    exist { proj1_sig : A ; proj2_sig : P proj1_sig }
where "{ x : A |  P }" := (sig (fun x : A => P)) : type_scope.
```
This will change the autogenerated names of fields given by `destruct `, but no one should depend on those.

I think we should move towards having `sigT` and co be primitive records with eta.

> is this an extra argument to tell that substitution of terms creating βɩ-redexes should maybe reduce those redexes on the fly?

I believe I have an open issue asking for the ability to mark identifiers in a way that tells substitution to βδ reduce them on the fly (particularly useful for identity coercions); perhaps there should also be a way to mark notations in a similar way, and have them reduce βɩ-redexes in the fly?

**Comment by herbelin** [comment]
> Is there any reason to prefer this over record syntax, i.e.,
>
> ```coq
> Record sig {A:Type} (P:A -> Prop) :=
>     exist { proj1_sig : A ; proj2_sig : P proj1_sig }
> where "{ x : A |  P }" := (sig (fun x : A => P)) : type_scope.
> ```
> This will change the autogenerated names of fields given by destruct, but no one should depend on those.

I also considering using records for `sig`, `prod`, etc. as a possible move, and to actually use primitive records. I started some experiments in this direction, but the compatibility is not immediate.

Typical issues I encountered are:
- `intros` is not any more blocked on `let '(x,y) := p in c` since the `let '(x,y) := p in c` unfolds into `c[x:=fst p][y:=snd p]` when `prod` is a primitive record.
- `destruct`/`induction` are indeed generating names based on the projection names as you mention.
- one easily sees `fst` unfolded into `let (fst0, _) := x in fst0` which is a bit unexpected.

> I believe I have an open issue asking for the ability to mark identifiers in a way that tells substitution to βδ reduce them on the fly (particularly useful for identity coercions); perhaps there should also be a way to mark notations in a similar way, and have them reduce βɩ-redexes in the fly?

The idea I'm contemplating is to have the "subst" functions taking an optional argument reduction function to be applied to the head of any subterm `E[x]` in which `x` is substituted (think at `E[x]` as the natural deduction form of a cut rule). Another application would be in induction hypotheses: if we have an induction hypothesis, say, `x+y = y+x`, then, substituting `S x` to `x` could automatically give `S (x + y) = y + S x`, i.e. with the addition automatically simplified (maybe this is too smart for a beginner usage, but this might be an interesting behavior for an expert user).

Indeed, this would also be useful also for identity coercions, and even more in a context where each applicative subterm is potentially anticipating the presence of a coercion which eventually is detected to be the identity (as in [bug report](https://coq.inria.fr/bugs/show_bug.cgi?id=5199)), even if what you are requiring is maybe not exactly related to substitution per se, but more to a general automatic post-processing of goals.

Do you have other examples of wanting to automatically unfold a constant on the fly than the case of identity coercions? (E.g. maybe automatically expanding `fst x` into `p` when substituting `x` with `(p,q)`?)

**Comment by JasonGross** [comment]
I'm not suggesting that we immediately make it a primitive record, but that we make it a record now, and make it primitive later; I believe this maintains compatibility for all code that doesn't rely on autogenerated names.

> Do you have other examples of wanting to automatically unfold a constant on the fly than the case of identity coercions?

Sometimes I use identifiers solely to help with type inference, notation resolution, or typeclass resolution.  In these cases, I'd often prefer that they disappear once the term is fully-formed.

> maybe automatically expanding `fst x` into `p` when substituting `x` with `(p,q)`

I'd very much like something like this for cases when `cbv [fst]` is wrong (not all `fst`) gets unfolded, and `simpl @fst` is too slow (I don't want any reduction beyond that local expansion).  Currently, I have tactics like [this](https://github.com/mit-plv/fiat-crypto/blob/master/src/Util/Prod.v#L104-L110) and once or twice I've played with something like this for reducing `fst` under binders:
```coq
Definition fst' := @fst.
Definition fst'' := Eval cbv [fst] in @fst.
Ltac cbn_fst :=
  change @fst with @fst';
  repeat (change @fst' with @fst'' at 1;
          match goal with
          | [ |- context[@fst'' _ _ (_, _)] ]
            => unfold fst''
          | _ => change @fst'' with @fst
          end).

Goal (fun x y z => fst (x, y) + y + fst z) = (fun x y z => x + snd z).
Proof.
  cbn_fst.
```

**Comment by herbelin** [comment]
For the record, the failure in `math-classes` is related to the impact of the eta-expansion of the type of `proj1_sig` in commit 1125619 on the outcome of the unification algorithm. In the following example
```coq
Check fun x : sig (id le 0) => exist _ (proj1_sig x) _ : sig (le 0).
```
returns
```coq
fun x : sig (id le 0) => exist (le O) (@proj1_sig nat (le 0) y))
```
when `proj1_sig : forall (A : Type) (P : A -> Prop), sig (fun x => P x) -> A` and
```coq
fun x : sig (id le 0) => exist (le O) (@proj1_sig nat (id le 0) y))
```
when `proj1_sig : forall (A : Type) (P : A -> Prop), sig P -> A`.

Then `ring`, which is not robust wrt conversion in recognizing a problem it can solve, eventually fails.

**Comment by silene** [comment]
I understand why you would want convertibility rather than syntactically equality. But what I missing is why, once you have checked arguments are indeed convertible, you don't put forcefully put back `Rel` as an argument. That would eliminate all these eta-expansion issues and restore backward-compatibility, if I am not mistaken.

**Comment by silene** [comment]
I also felt it was quite miraculous that you didn't have to modify the checker, but I guess that is what travis is complaining about.

**Comment by herbelin** [comment]
@silene: I patched the checker. Putting `Rel` would not help for the eta-expansion issue I had spotted as it was not related to the change in the kernel but to changes in the types of the `sig` argument of a few lemmas in `Specif.v`. Testing again, as it is not yet clear if the other causes of failure have the checker or the changes in `Specif.v` as origin.

**Comment by Zimmi48** [comment]
Is the only thing blocking this PR is a needed rebase or is there something else? (I didn't re-read the discussion.)

**Comment by maximedenes** [comment]
I'm inferring that @herbelin is scheduling this for 8.9, so I'll update the milestone.

**Comment by herbelin** [comment]
I have a mitigated opinion on the ratio advantages/incompatibilities of this PR. I'm postponing taking an opinion.

**Comment by ppedrot** [comment]
@herbelin Have you made any progress on forming an opinion?

**Comment by herbelin** [comment]
> @herbelin Have you made any progress on forming an opinion?

Somehow my current feeling is that the (unfortunate) number of related issues to address is not worth the advantage of the change, especially considering other priorities. So, if your question is about possibly closing it, we can probably do.

**Pull request closed without merging**
