### PR TITLE
Avoid exposing an internal name when "intros _ H" fails because of _ being dependent in H

### LINKED ISSUE #13336: When the introduction pattern _ would break a dependency, the error message exposes an internal name _tmp.
#### Description of the problem

Improvement to come soon.

#### Coq Version

Since 8.6.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

Fixes / closes #13336. 

The new proposed error message is of the form "The variable is used in hypothesis id" (together with highlighting of the `_`).

- [X] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
This is simple enough that I can take it in for 8.13.
I'd still like to have a changelog entry and a confirmation that the `?loc` is not `None` in the test suite example.
I mean `this variable` without a loc is a bit hard to understand. I could test it myself but @herbelin while you check out for the changelog could you please double check this?

**Comment by herbelin** [comment]
> I'd still like to have a changelog entry

Added.

> and a confirmation that the ?loc is not None in the test suite example.

The loc is on `_` (but `Fail` lost it).

> I mean `this variable` without a loc is a bit hard to understand

Yes, I agree and I'm not satisfied either by the message. The problem is that it is `_`, which by definition has no name. Maybe can I change the message to "The variable to which "_" refers cannot be erased because it is used in hypothesis H", or something in this vein?

**Comment by gares** [comment]
> Maybe can I change the message to "The variable to which "_" refers cannot be erased because it is used in hypothesis H", or something in this vein?

I think it is fine, the loc is pointing to `_`.

**Comment by gares** [comment]
@coqbot  merge now

**Comment by gares** [comment]
@coqbot merge now

**Pull request merged**
