### PR TITLE
[api] Deprecate all legacy uses of Names in core.

### PR DESCRIPTION
**Pull request by ejgallego**
Prerequisite to move `Names` out of API, depends on #6064

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]

**Comment by ejgallego** [comment]
Ok rebased anyways so Travis get run. It should not matter I think.

**Comment by ejgallego** [comment]
Only the linter fails, but given the nature of this commit I request an exception as I think I do not want to reindent half's of Coq code base.

**Comment by SkySkimmer** [comment]
Whitespace fixed version https://github.com/SkySkimmer/coq/tree/api-names
Make by
- git format-patch HEAD~
- git reset --hard HEAD~
- git apply --whitespace=fix foo.patch
- git commit (need to retype commit message, if original commit is by someone else need to override author)

**Comment by ejgallego** [comment]
> Whitespace fixed version https://github.com/SkySkimmer/coq/tree/api-names

Indentation does not seem correct, does it?

https://github.com/SkySkimmer/coq/commit/d63712b7fb43260a43c17dc4eccacdac5e304f56#diff-bbcb05d045ba64ccf4ca6bc0ff20a750R377

**Comment by SkySkimmer** [comment]
>Indentation does not seem correct, does it?

When I open it locally it looks correct (with 8 spaces/tab).
I think it's because of interaction between the diff `+` and tabs in the github UI (note the surrounding lines still have tabs).

**Comment by ejgallego** [comment]
Umm, I am not sure we want to have mixed tab-spaces sequences of indentation, usually when I eliminate tabs I do it for the whole block as to keep consistency, but no strong opinion on that.

Personally I wouldn't delay this merge due to this, given its "special" nature.

**Comment by maximedenes** [comment]
Why not do one big pass on the entire codebase, and then become strict, now that we have a linter?

**Comment by maximedenes** [comment]
> Why not do one big pass on the entire codebase, and then become strict, now that we have a linter?

(but then we should do it after merging those PRs)

**Comment by ejgallego** [comment]
> Why not do one big pass on the entire codebase, and then become strict, now that we have a linter?

IMHO that's too noisy, it makes indeed sense to do it block by block; I think this PR is a bit special due to the pervasive use of `sed` to replace deprecated identifiers and we should not reindent all that blocks.

**Comment by ejgallego** [comment]
> (but then we should do it after merging those PRs)

but yes, if we eliminate tabs we better do it with a full, separate commit.

**Comment by SkySkimmer** [comment]
I think line by line is what we can enforce. If people do blocks in their PRs that's nice but requiring them to is too strict. OTOH we can require that every changed line is fixed even in this PR since it can be done automatically.

**Comment by ejgallego** [comment]
I think enforcing line by line is good. I also think that ideally authors should fix whole blocks, so that's why I don't regard the automated solution as ideal. Given the size of this patch I prefer to keep block-level tab (in)consistency.

**Comment by maximedenes** [comment]
@SkySkimmer Are you ok that we merge as it is despite the whitespace issues, like @ejgallego requests?

**Comment by SkySkimmer** [comment]
It's not my preferred solution but let's get this API stuff done.

**Pull request merged**
