### PR TITLE
Ltac2 assert by precedence

### LINKED ISSUE #17491: Ltac2 assert: by clause eats all semicolons
In Ltac1, this works:

```coq
Goal forall (a: nat), a = a.
Proof.
  intros.
  assert (a = a) by reflexivity;
  assumption.
Qed.
```

However, if I do `Require Import Ltac2.Ltac2.` before that snippet, it stops working: At the `Qed.`, I get `Error:  (in proof Unnamed_thm0): Attempt to save an incomplete proof`.
It seems that the assert-by is parsed as `assert (a = a) by (reflexivity; assumption)`, because it works again if I add explicit parentheses like this: `(assert (a = a) by reflexivity); assumption`.

This behavior is not only inconsistent with Ltac1, but it's also inconsistent with Ltac2's `rewrite` `by`, as this example shows (which works as expected):

```coq
Goal forall (a c: nat) (P: Prop), (P -> a = c) -> P -> 2 * a = 2 * c.
Proof.
  intros.
  rewrite H by exact H0; reflexivity.
Qed.
```

I believe this could (and should) be fixed by inserting ` LEVEL "2"` after `ltac2_expr` in the following place:

https://github.com/coq/coq/blob/54274eeeaf61edc73f1bef95983b588288d7afaf/plugins/ltac2/g_ltac2.mlg#L893-L897

Coq version: 8.16.0

### PR DESCRIPTION
**Pull request by samuelgruetter**
Fixes #17491

- [X] Added / updated **test-suite**.
- [x] Added **changelog**.
- [X] Added / updated **documentation**.
  - [X] Updated **documented syntax** by running `make doc_gram_rsts`.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]

**Comment by samuelgruetter** [comment]
As revealed by the CI run, I picked the wrong level!
When I chose level 1, I only considered the grammar in the [manual](https://coq.inria.fr/refman/proof-engine/ltac2.html#term-syntax), but forgot to take into account that most Ltac2 Notations are at level 5 (as revealed by `Print Grammar ltac2_expr`). So now I put it at level 5, hopefully that's correct!

**Comment by samuelgruetter** [comment]
I believe this is ready! @ltac2-maintainers could you please have a look?

**Review by ppedrot — APPROVED** [review]
This looks fine. I'm a bit concerned about the limited choice of levels in Ltac2, I took the same as Ltac1 for backwards compatibility but we might need to expand the level numbering to a much bigger choice.

**Comment by SkySkimmer** [comment]
Maybe we could try to use levels like constr does rather than like ltac1? eg fix https://github.com/coq/coq/issues/16432

@coqbot merge now

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
