### PR TITLE
Change release process to prepare the version change PR earlier

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Alternatively perhaps we should recommand to create the PR with the new version number early so that there's time to deal with CI issues.

**Comment by Zimmi48** [comment]
> Alternatively perhaps we should recommand to create the PR with the new version number early so that there's time to deal with CI issues.

:+1: 
That sounds like a more bullet-proof approach.

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
I intend to merge this PR tomorrow.

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
