### PR TITLE
Use a registered printer for tactic coercion failure.

### PR DESCRIPTION
**Pull request by ppedrot**
Otherwise we pay a high cost for printing that might never make it to the user.

### CODE REVIEW

**Comment by ppedrot** [comment]
This was found in bedrock2, but I don't know how to bench this since it's part of the stuff not in the opam package.

**Review by ejgallego — APPROVED** [review]
Trivial, will make to master soon so Pierre-Marie can reduce his working delta.

**Comment by ppedrot** [comment]
We can try to get a bench out of curiosity though.

**Review by herbelin — COMMENTED** [review]
All noncritical errors distinct from `Logic_monad.Exception` are (now?) Ltac-`try` catched by default, right?

**Comment by SkySkimmer** [comment]
BTW we have `CErrors.is_anomaly` which runs the printers for nothing, we should look into removing it.

**Comment by ppedrot** [comment]
@herbelin it should be the case indeed.

**Comment by ejgallego** [comment]
> BTW we have `CErrors.is_anomaly` which runs the printers for nothing, we should look into removing it.

Indeed, the PR about the error registration API was trying to fix that, but a simpler fix may be worth it.

**Comment by ppedrot** [comment]
As expected, the bench is only noise:
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-bedrock2 │  222.11   223.18  -0.48 │   614593294015    616960596144  -0.38 │  1028730359069   1031085886061  -0.23 │ 1027240  1027732  -0.05 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-color │  503.91   505.89  -0.39 │  1406987584880   1410294205471  -0.23 │  1786585854106   1786587270758  -0.00 │ 1133552  1111660   1.97 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1223.42  1227.74  -0.35 │  3405804962320   3416699184977  -0.32 │  4849383208077   4867409413909  -0.37 │  901128   901228  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  789.56   792.16  -0.33 │  2200097075454   2205238067344  -0.23 │  3484821617761   3485511935590  -0.02 │  970148   975528  -0.55 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2571.74  2578.14  -0.25 │  7169637691927   7186945088012  -0.24 │ 12433495765557  12433742836618  -0.00 │  728596   728508   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                         coq │  516.94   518.05  -0.21 │  1447892807063   1449855332539  -0.14 │  1955258208477   1955353657822  -0.00 │  568216   568132   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-flocq │  155.68   156.00  -0.21 │   432465035775    433243218327  -0.18 │   540792930467    540852615424  -0.01 │  820852   820856  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 5019.08  5027.52  -0.17 │ 13945910694937  13958978847517  -0.09 │ 24608827040948  24641069221067  -0.13 │ 2412460  2410300   0.09 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-rewriter │  716.95   717.77  -0.11 │  1989563680877   1994959576498  -0.27 │  3088484971641   3088803799826  -0.01 │  990144   982632   0.76 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   50.72    50.76  -0.08 │   138596779857    138556886789   0.03 │   178415411423    178396157748   0.01 │  509828   509652   0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  153.67   153.78  -0.07 │   427205332258    427477634028  -0.06 │   602480971441    602389199889   0.02 │  711040   711008   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1045.61  1046.30  -0.07 │  2913158734035   2914299082913  -0.04 │  4664337266272   4664291614424   0.00 │  983780   983808  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  221.07   221.21  -0.06 │   615425051504    615455926278  -0.01 │   949843863592    949815205783   0.00 │  677012   677392  -0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  626.92   626.85   0.01 │  1754277611637   1754375622232  -0.01 │  2698473250016   2698653703129  -0.01 │ 3241960  3242004  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-perennial │ 5468.08  5467.35   0.01 │ 15181078180281  15195272212839  -0.09 │ 22961882150025  22974165384047  -0.05 │ 3037556  3098996  -1.98 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1219.53  1219.23   0.02 │  3393371311575   3393408333937  -0.00 │  4914406762141   4917724560751  -0.07 │ 1117668  1117672  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  168.09   168.03   0.04 │   467804053141    467807372123  -0.00 │   669619618554    669609457632   0.00 │  662396   672832  -1.55 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-corn │ 1619.17  1618.08   0.07 │  4507191030376   4505303685327   0.04 │  6940505255486   6940643107115  -0.00 │  774888   774780   0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1455.54  1454.39   0.08 │  4054547059479   4050884058901   0.09 │  6183020242779   6183178768200  -0.00 │ 1028136  1033236  -0.49 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-unimath │ 3997.22  3993.62   0.09 │ 11118703899421  11112097500742   0.06 │ 21384508260167  21380840085015   0.02 │ 1022764  1022884  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  342.85   342.48   0.11 │   964716763734    964279996247   0.05 │  1751623101765   1748966835694   0.15 │ 3499976  3499916   0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-compcert │  634.00   633.28   0.11 │  1765859342595   1765644035564   0.01 │  2469321572527   2469342184917  -0.00 │ 1047064  1047172  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-coqutil │   60.63    60.56   0.12 │   167807724519    167767202363   0.02 │   209772967943    209907035315  -0.06 │  527132   527176  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  137.47   137.31   0.12 │   382001712697    382282596761  -0.07 │   499715297763    499708655109   0.00 │  548764   548792  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                   coq-verdi │  101.79   101.44   0.35 │   279462149224    279826799484  -0.13 │   395990756236    397741791083  -0.44 │  544312   547612  -0.60 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq-hott │  328.00   326.40   0.49 │   888341187289    887276984494   0.12 │  1453554993098   1452158780864   0.10 │  607428   602672   0.79 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-coqprime │   79.23    78.81   0.53 │   216762566831    216691656322   0.03 │   307228485512    307159925533   0.02 │  764396   760172   0.56 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-fiat-core │  102.55   101.99   0.55 │   292010477801    291796535030   0.07 │   390332021884    390055620055   0.07 │  478988   479000  -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-coquelicot │   67.72    67.33   0.58 │   184630508510    184534770203   0.05 │   237241245766    237208460074   0.01 │  568664   568540   0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-math-classes │  213.13   211.65   0.70 │   592440053057    591104454784   0.23 │   813179279782    813177506762   0.00 │  522660   522692  -0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   47.19    46.66   1.14 │   130333539397    129934665508   0.31 │   182167503042    182154796102   0.01 │  479536   480872  -0.28 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-bignums │   57.20    56.43   1.36 │   156785584728    156211054472   0.37 │   210298801121    210283084054   0.01 │  474244   474224   0.00 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
