### PR TITLE
[ci] [appveyor] Pass -j2 to Appveyor's build and build test suite again

### PR DESCRIPTION
**Pull request by ejgallego**
Let's see how much the speedup is.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Appveyor https://ci.appveyor.com/project/coq/coq/builds/21065378 said
> 7 days ago in 47 min 27 sec 

Around the same time azure was taking 36min https://dev.azure.com/coq/coq/_build/results?buildId=13

No clue what the variance for appveyor runners is.

**Comment by ejgallego** [comment]
I wonder how much time is spent on setup.

**Comment by SkySkimmer** [comment]
>I wonder how much time is spent on setup.

Azure says about 5min, for appveyor we would have to print timing info in the log.

**Comment by ejgallego** [comment]
> Azure says about 5min, for appveyor we would have to print timing info in the log.

Appveyor already has the timing info in the log, setup takes ~ 3 mins 40 secs

**Comment by maximedenes** [comment]
@ejgallego what's the conclusion of this experiment? Should I merge?

**Comment by ejgallego** [comment]
Merge if you want, it should provide some speedup. Anyways we will remove Appveyor soon.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
