### PR TITLE
Let coqdoc be informed by coq about binding variables (incidentally fixes #7697)

### LINKED ISSUE #7697: coqdoc gets confused when a binder is named like a reduction strategy
#### Version

8.8.0

#### Operating system

linux

#### Description of the problem

Running `coqdoc` on

    Definition foo (beta : unit) := beta.

gives

```
<span class="id" title="keyword">Definition</span> ...
(<span class="id" title="keyword">beta</span> : ...) :=
<a class="idref" href="foo.html#beta"><span class="id" title="variable">beta</span></a>.
```

Notice how the `beta` binder has `title="keyword"` while it should have `title="var"`. When this binder is used, it is correctly marked with `title="variable"`. The issue also occurs with `iota`, `zeta`, etc.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix / feature

By passing information on binders to coqdoc, we open the way to eventually give more information about the structure of the text. ~~Currently, it is only displaying "binder" when hovering, but, eventually, this could add a link, or provide type information, etc~~. Extended to add proper hyperlinks (even though it is rare that variables are far from their binder).

Incidentally, this fixes #7697 since coqdoc can rely on Coq to know that an ident is a binder rather than making a wrong guess (like e.g. thinking it is a tactic word because the name is called `beta`).

Anyone knows how a line could be drawed to the binding variable when hovering on the occurrence of a variable?

Fixes / closes #7697

- [X] Added / updated test-suite
- [x] Entry added in the changelog

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Tests seem slightly broken

**Comment by herbelin** [comment]
> Tests seem slightly broken

Yes, these coqdoc tests are painful to manage. First, it is very difficult to check diffs when the lines are hundreds of characters long. Maybe a postprocessing adding a newline after each html tag would be a good idea. Secone, one would need some `approve-coqdoc` when it is clear that the output is right.

**Comment by ejgallego** [comment]
> Yes, these coqdoc tests are painful to manage. First, it is very difficult to check diffs when the lines are hundreds of characters long.

Does `patdiff` help @herbelin ?

**Comment by herbelin** [comment]
> Does patdiff help @herbelin ?

Wouaouh: that's magic! Thanks.

**Comment by ejgallego** [comment]
> Wouaouh: that's magic! Thanks.

Glad to hear it helped. Adding `patdiff` support for both Coq users and developers is in my TODO.

**Comment by herbelin** [comment]
This is ready on my side. Feedback welcome.

PS: I saw that javascript packages allow to draw lines on html documents. Should we go in the direction of supporting more javascript fancy features on coqdoc pages?

**Review by Lysxia — APPROVED** [review]

**Comment by Lysxia** [comment]
Looks good to me. I'll take another pass and merge at the end of the week.

> Anyone knows how a line could be drawed to the binding variable when hovering on the occurrence of a variable?

I don't know about drawing lines, but alternatively, highlighting the binder seems simple enough (maybe even with CSS only).

**Comment by herbelin** [comment]
> I don't know about drawing lines, but alternatively, highlighting the binder seems simple enough (maybe even with CSS only).

Indeed, `:target` seems to do the trick, thanks! I made a proposal for that at #12091. We may also want to highlight the target without clicking on it, but that's already good to so with so little infrastructure.

**Pull request merged**
