### PR TITLE
[interp] [numeral] Improve numeral notations to support Ind and to not use the VM

### LINKED ISSUE #9840: Printing part of numeral notation does not work in all cases.
#### Description of the problem

While in the following case, the printing part of numeral notations works fine:

```coq
Record a := { n : nat ; p : True }.

Definition to_a i := Build_a (Nat.of_uint i) I.
Definition of_a '(Build_a n _) := Nat.to_uint n.

Numeral Notation a to_a of_a : foo_scope.

Open Scope foo_scope.

Check 1.

(* 1
     : a
*)
```

in these variations, it does not:

```coq
Axiom h : False.

Record a := { n : nat ; p : False }.

Definition to_a i := Build_a (Nat.of_uint i) h.
Definition of_a '(Build_a n _) := Nat.to_uint n.

Numeral Notation a to_a of_a : foo_scope.

Open Scope foo_scope.

Check 1.

(* {| n := 1; p := h |}
     : a
*)
```

```coq
Record a := { n : nat ; p : or True False }.

Definition to_a i := Build_a (Nat.of_uint i) (or_introl I).
Definition of_a '(Build_a n _) := Nat.to_uint n.

Numeral Notation a to_a of_a : foo_scope.

Open Scope foo_scope.

Check 1.

(* {| n := 1; p := or_introl I |}
     : a
*)
```

```coq
Parameter A : Prop.
Axiom h : A.

Record a := { n : nat ; p : A }.

Definition to_a i := Build_a (Nat.of_uint i) h.
Definition of_a '(Build_a n _) := Nat.to_uint n.

Numeral Notation a to_a of_a : foo_scope.

Open Scope foo_scope.

Check 1.

(* {| n := 1; p := h |}
     : a
*)
```

```coq
Record a := { n : nat ; p : 0 = 0 }.

Definition to_a i := Build_a (Nat.of_uint i) eq_refl.
Definition of_a '(Build_a n _) := Nat.to_uint n.

Numeral Notation a to_a of_a : foo_scope.

Open Scope foo_scope.

Check 1.

(* {| n := 1; p := eq_refl |}
     : a
*)
```

Found by @roglo while trying to use numeral notations for his rational numbers.

cc @JasonGross 

#### Coq Version

8.9.0

### LINKED ISSUE #9844: Conditions of numeral notation printing support should be documented
See discussion starting at https://github.com/coq/coq/issues/9840#issuecomment-477248872

Roughly the condition is "printing only works for ground terms" but what exactly "ground" means is subtle (currently it means "made only of app, construct, and GInt, but this might change to admit Ind and Sort).

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** bug fix

Fixes / closes #9840
Fixes / closes #9844
Supersedes / closes #9655 

- [x] Added / updated test-suite
- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in CHANGES.md.

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
This seems OK to me, I'll wait for @herbelin to comment tho, even if indeed this should go even in 8.9.1 I guess, right @JasonGross ?

**Comment by JasonGross** [comment]
It would be nice to get this in 8.9.1, but I think you care about that more than I do.  (I will note that this doesn't break anything that's currently working, so it should be fine to add to 8.9.1.)  Certainly I'd prefer this / 031e771d4b14711685ac9e91279c60ab692cc814 over #9655 though.

**Comment by ejgallego** [comment]
> I think you care about that more than I do.

We have all but moved all our projects to 8.10; 8.9 was quite unusable for us on many fronts.

**Review by Zimmi48 — APPROVED** [review]
The additions to the documentation are useful clarifications.

**Comment by JasonGross** [comment]
I think this needs to be rebased and updated due to a conflict between one of the tests I added and https://github.com/coq/coq/pull/8829.  (Making a note here so I remember to fix later.)

**Comment by JasonGross** [comment]
@Zimmi48 I have updated the doc a bit more to be more accurate (primitive integers are considered ground for numeral notations) (and also added a comment to the .ml file to update the doc if the corresponding function changes).  You may or may not want to re-review the doc.

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
