### PR TITLE
Update headers following #6543.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

Follow up of #6543.

### CODE REVIEW

**Comment by maximedenes** [comment]
Why are Inria and CNRS now mentioned, but not other institutions?

**Comment by Zimmi48** [comment]
> Why are Inria and CNRS now mentioned, but not other institutions?

Quoting myself from the PR when the template header was changed:

> I also removed the list of research labs in the headers: first of all, it doesn't make much sense to list them there (they cannot be copyright holders being neither the authors, nor their employers), the list is necessarily incomplete, already obsolete (PPS was merged into IRIF in 2016). I added a general mention "and contributors" which is very classic; together with the reference to the CREDITS file, this makes the headers more accurate. I kept INRIA and CNRS but maybe it should be further reduced to INRIA and contributors (INRIA being the employer of the most part of the development team, with other prominent members of the development team having been attached to INRIA as members of one of its project-teams).

Anyways, if discussion was needed on this aspect, I would have appreciated if it had happened in the relevant PR (#5643).

**Comment by maximedenes** [comment]
I think the link is the wrong one. And the part you quote doesn't explain why you kept Inria and CNRS.

**Comment by Zimmi48** [comment]
Sorry, link edited.

From the initial list "INRIA - CNRS - LIX - LRI - PPS", I removed the lab names. This results in "Inria - CNRS". I think you'll agree that this answers your question.

Now a further question might be: why did I remove the lab names. That part is explained in my quote above: labs cannot be copyright holders so it doesn't make sense to list them there. Moreover they change too often: keeping track of that in *every* source file is a burden. The general clause "and contributors" ensures that we are not leaving anyone out (as was the case before), including employees of French higher-education institutions (universities, CNAM, Mines...) and non-French institutions (MIT, MPI...).

**Comment by Zimmi48** [comment]
If you think that it is unfair to keep CNRS but not universities, we could further reduce this to just "Inria and contributors". I would have preferred to know about that before preparing this big PR but well...

**Comment by maximedenes** [comment]
Sure, and I agree it makes no sense to put labs there. But what I would have expected is to change the names of labs into the names of the institution they belong to.

If we want to go the other way, I'd suggest "Inria and contributors", but then I think we need legal advice.

**Comment by maximedenes** [comment]
Sorry, I didn't have time to contribute to the previous discussion. My point of view is:
- It doesn't take a lawyer to understand that it makes no sense to put labs there, so turning labs into institutions is ok to do now.
- Whether we can remove the explicit mention to some of these copyright holders (replacing with "and contributors") is much less clear IMHO, and should be legally reviewed.

**Comment by Zimmi48** [comment]
> But what I would have expected is to change the names of labs into the names of the institution they belong to.

That would only have made the list longer and wouldn't have solved the problems that a lots of institutions were missing from that list. The "and contributors" part and the "(see CREDITS file for the list of authors)" part do.

> If we want to go the other way, I'd suggest "Inria and contributors"

OK fine.

> I think we need legal advice

No seriously we don't. I know what I'm doing. The copyright headers were wrong but that didn't bother anyone. And when I fix them, I get answered "we need legal advice". Seriously?

> Whether we can remove the explicit mention to some of these copyright holders (replacing with "and contributors") is much less clear IMHO, and should be legally reviewed.

That's a well spread (and legal) practice in the world of free software, trust me on this one.

**Comment by maximedenes** [comment]
Again, the "fix" part is only about turning labs into institution, so I'm not saying to review the fix.

That said, I don't oppose the change. Maybe put "Inria and contributors" and get a green light from @mattam82, confirming he thinks this doesn't need a legal review.

**Comment by Zimmi48** [comment]
> Sorry, I didn't have time to contribute to the previous discussion.

The previous PR was opened from Jan 3rd to five days ago (so almost two months) and *you* merged it ;-)

> That said, I don't oppose the change. Maybe put "Inria and contributors" and get a green light from @mattam82, confirming he thinks this doesn't need a legal review.

OK, @mattam82 do you give the green light? I'll do the change from "Inria - CNRS - and contributors" to "Inria and contributors" only then.

**Comment by maximedenes** [comment]
> The previous PR was opened from Jan 3rd to five days ago (so almost two months) and you merged it ;-)

Sure, but I've been very busy and I don't block the merge of PRs just because I couldn't contribute to the discussion.

**Comment by herbelin** [comment]
As a representative of the last 30 years of Coq, my personal feeling is that what @Zimmi48 proposed is pretty sensible (INRIA of course, but also CNRS as a stable partner of most labs which have contributed over the last 30 years, on the contrary of universities which are, especially these days, in an ongoing process of restructuration).

**Comment by maximedenes** [comment]
Sure, I'm not going to block this, I would like to get a green light from @mattam82, though.

**Comment by Zimmi48** [comment]
@maximedenes Assuming this gets the green light from @mattam82, can I let you handle the merge conflict? It should be a simple `git rm theories/Compat/Coq85.v`.

**Comment by mattam82** [comment]
Let’s go with Inria, CNRS and contributors. I won’t fight for the case
change, you have my green light!

Le dim. 4 mars 2018 à 21:05, Théo Zimmermann <notifications@github.com> a
écrit :

**Pull request merged**
