### PR TITLE
String: add leb

### PR DESCRIPTION
**Pull request by liyishuai**
**Kind:** feature.

- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by JasonGross** [comment]
Perhaps also add `ltb`?  And maybe we want a lemma that says that if two strings are leb in both directions, them they're equal, and that for all strings, one is leb to the other?  (Maybe look at what lemmas exist around Z.leb?) But feel free also to not add these; we don't want the perfect to be the enemy of the good

**Comment by liyishuai** [comment]
I'm restructuring these definition into `compare`-based.

**Comment by liyishuai** [comment]
I'm getting offline soon. Releasing locks on this branch. Feel free to (force) push.

**Comment by liyishuai** [comment]
Not sure why MetaCoq was broken. Did I pollute its namespace?

**Comment by herbelin** [comment]
Metacoq was broken for all PRs a few days ago. You should rebase to double-check.

**Comment by liyishuai** [comment]
@coqbot ci minimize
(Did the bot just talk to itself?)

**Comment by anton-trunov** [comment]
@liyishuai I tried re-running the MetaCoq job but to no avail.

**Comment by liyishuai** [comment]
> This job depends on other jobs with expired/erased artifacts: build:base

Should I re-push?

**Comment by JasonGross** [comment]
> (Did the bot just talk to itself?)

Oops.  I've fixed this issue.  The other issue is waiting on waiting on feedback from @Zimmi48 on how to retrieve PR info on non-review comments, so I've disabled the ci minimization for now

**Comment by JasonGross** [comment]
@coqbot CI minimize

**Comment by herbelin** [comment]
Hi, I took the freedom of rebasing the PR so as to restart CI. It seems that the incompatibility is only in `leb` needing to be qualified into `Nat.leb` in file `pcuic/theories/PCUICToTemplateCorrectness.v` of MetaCoq.

**Review by silene — APPROVED** [review]

**Comment by liyishuai** [comment]
@coqbot ci minimize

**Comment by JasonGross** [comment]
Unfortunately minimization of metacoq does not work yet due to https://github.com/coq/coq/issues/14453

**Comment by herbelin** [comment]
@ liyishuai: if you rebase, metacoq should now pass, after MetaCoq/metacoq#561 and MetaCoq/metacoq#562 were merged.

**Comment by Alizter** [comment]
@anton-trunov Will you be merging this?

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
@coqbot merge now

**Comment by anton-trunov** [comment]
@Alizter thanks for the ping :)

**Pull request merged**
