### PR TITLE
Fix #8043: Unsafe assignment in checker.

### PR DESCRIPTION
**Pull request by ppedrot**
We use a dedicated mutable constructor to perform a Landin knot.

### CODE REVIEW

**Comment by gares** [comment]
Can't you just revert 578d73a8b8eb6623bfa ? I really don't see any use for that (in votour I mean)

**Comment by gares** [comment]
Said otherwise: the code in that file should be generated by a ppx, spending time on it seems really futile, especially for data that is not even used by the checker.

**Comment by ppedrot** [comment]
@gares I guess I could, I think I introduced that for debugging. That said, the current PR is helpful even in general, because it allows to abstract over the OCaml limitation that recursive data structures need to be syntactically constructors.

**Comment by ppedrot** [comment]
@gares I remember why I introduced that: I was debugging memory allocation of vio files, and for that you need to observe the STM data structures. Does it really hurt to have it here?

**Comment by gares** [comment]
Well, I'd say no it does not hurt, but there was a bugreport and your fix... hence it happens to have some cost to keep this code around.

**Comment by herbelin** [comment]
Any conclusion to this discussion? In any case, the only official reviewer mentioned should assign it to him.

**Comment by ppedrot** [comment]
@maximedenes could you take care of this one?

**Comment by maximedenes** [comment]
> @maximedenes could you take care of this one?

Sure, will do.

**Review by maximedenes — APPROVED** [review]
The `vi`-related memory issues are far from solved, so I think it makes sense to keep the debugging code meanwhile.

**Comment by Zimmi48** [comment]
@maximedenes Here we go with the notification you requested in https://github.com/coq/coq/pull/8094#issuecomment-426231518 (this was only a test and will happen every time in the future).

**Pull request merged**
