### PR TITLE
Fixes #8553: regression of tactic "change" under binders.

### LINKED ISSUE #8553: Regression of tactic `change` under binders
#### Version

Since 8.5.

#### Description of the problem

Reported by @cpitclaudel on Coq-club.

```coq
Definition add2 n := n +2.
Goal (fun n => n) = (fun n => n+2).
Fail change (?n + 2) with (add2 n).
```
It used to work with Coq 8.4.

Fix to come.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

Fixes / closes #8553

Easy fix: the exact environment at the time of type-checking the subterm was not passed. A pity that we did not use more systematically regression tests earlier.

- [X] Added / updated test-suite

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by gares** [comment]
can you explain how it happened to work? what broke it?

**Comment by herbelin** [comment]
@gares: Apparently, it is me who introduced the bug in 4c576db3ed4 while fixing another bug (to be found in `test-suite/success/change.v`)

**Comment by ppedrot** [comment]
Looks like this breaks Equations and Ltac2.

**Comment by herbelin** [comment]
Thanks for noticing. Overlays pushed and going to submit PRs.

**Comment by herbelin** [comment]
@ppedrot: seems ready (synchronizing with ltac and equations). Appveyor stopping brutally on coqchk is strange (a timeout?). In any cases, no reason that it is related.

@silene: this fix is a candidate for 8.9 (it changes the API and is thus not for a minor version).

**Comment by ppedrot** [comment]
@herbelin Sorry, your message went under my radar. I'll merge this PR tomorrow so that people are more reactive for the overlay merging.

**Comment by silene** [comment]
@herbelin @ppedrot 

> this fix is a candidate for 8.9 (it changes the API and is thus not for a minor version)

With respect to testing Ltac2 on 8.9, this pull request conflicts with #7288 , which is not scheduled for backporting to 8.9. So, I would need a `v8.9` branch in `ppedrot/ltac2` that contains ppedrot/ltac2@eb9fb37b98c6e4e625843ae129cfa13e10b9804b but not ppedrot/ltac2@d4c019e93b75ceebb5f8c42a648d91ced4a3b30d. (Hopefully, I got it right.)

**Comment by herbelin** [comment]
@silene, @ppedrot, tell me if you expect me to do it. Otherwise, I'll assume that @ppedrot (who is probably more directly able to do it) is doing it.

**Comment by silene** [comment]
I would also expect it to be faster for @ppedrot to do it.

**Comment by silene** [comment]
You missed the point of my request. I cannot push the backport if the continuous integration fails. That is why I need you to blindly apply the commit to the branch.

**Comment by ppedrot** [comment]
OK, let's do this.

**Pull request merged**
