### PR TITLE
Fix evar sensitivity in context compaction

### LINKED ISSUE #17386: Context compaction is evar sensitive
~~~coq
Goal True.
evar (x:nat).
pose (y:=1).
let _ := constr:(eq_refl : x = 1) in idtac.
(*
x := 1
y := 1

should be
x, y := 1
 *)
Abort.
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #17386

Overlays:
- https://github.com/ejgallego/coq-serapi/pull/328
- https://github.com/ejgallego/coq-lsp/pull/474

### CODE REVIEW

**Comment by ppedrot** [comment]
As already advocated in the other PR, don't normalize upfront but instead take a sigma in the equality-checking function.

**Comment by SkySkimmer** [comment]
changed

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by SkySkimmer** [comment]
oh vst is broken on master
overlay need is real btw

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
