### PR TITLE
add note about expectations on answers to forum questions in CofC

### PR DESCRIPTION
**Pull request by palmskog**
Prompted by a Zulip discussion.

cc: @Zimmi48

### CODE REVIEW

**Comment by Zimmi48** [comment]
Maybe prepending the new paragraph by "Note that from experience" and postponing it with "This is not meant to say that these long questions or comments are discouraged, as long as they respect the other rules set forth in this code of conduct." would help make it clear that this is not an attempt at policing the type of questions that can be asked?

**Comment by palmskog** [comment]
@Zimmi48 I reformulated quite a lot, but with your suggestions as input, what do you think about it now?

**Comment by Zimmi48** [comment]
This looks good to me, thanks! I will leave some time for others to comment before merging.

**Comment by mattam82** [comment]
Fine with me!

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
