### PR TITLE
List members of the code of conduct enforcement team.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Review by ejgallego — APPROVED** [review]

**Comment by herbelin** [comment]
I'm trusting @Zimmi48 and @mattam82 for their general care for fairness, for their general care for using consensual neutral vocabulary and for paying attention to use appeasing words when necessary. However, the question of how to proceed when one of @zimmi48 or @mattam82 is himself involved in a "conduct" issue remains open. Do you have a proposal?

**Comment by herbelin** [comment]
So, you mean that if a member of the conduct committee takes a decision which is considered unfair by someone, the other members of the committee are expected to study the case independently in "all honesty"?

**Comment by gares** [comment]
> Do you have a proposal?

I propose that when a person has conflicts in his records, then he cannot take a seat in the committee for 5 years. If Theo or Matthieu happen to have a conflict then they should step back and find someone with clean records to replace them.

**Comment by herbelin** [comment]
> I propose that when a person has conflicts in his records, then he cannot take a seat in the committee for 5 years.

That's an interesting argument and somehow a fair one.

As far as I'm concerned, I'm someone rather emotional and who often takes things to heart. I'm unsure that this is very good to play a role of referee.

I'm also someone who tends to wait too long before realizing that something is hurting him. When I had this huge and destructive anger about `abstract` and `admit` which still haunts me for the negative impact it had, it came after 6 months of not feeling heard in my questions. Would I have expressed in real time the increasing frustration of facing what for me looked like authoritarian statements while I was instead expecting being simply heard in my suggestions, would I have had the intelligence of moving to the meta-level in real time rather than waiting being cornered in my feeling of being unrespected and reacting violently, things would probably be much different now.

In any case, I'm not asking to be part myself of the committee, if that's the question. What I'm trying to ensure is that no arbitrary or unfair decisions are taken, thinking in particular to the temporary ban which happened in July.

**Comment by gares** [comment]
I'm on the same page, i'm bad at these things. I don't think I would do a good job in that committed. Hence my proposal. 

I think your question makes sense and an answer should be given in the document (maybe another PR, since the focus of this one is another one).

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
@mattam82 could you merge this? Thanks!

**Comment by herbelin** [comment]
> @mattam82 could you merge this? Thanks!

Since we are precisely talking about how to "conduct" so that everyone feels welcome, I'd like to say that I would personally perceive a sentence such as: "Has anyone something else to add to the discussion. If not, @mattam82, there is probably no reason to postpone any longer the merge of this PR." several orders of magnitude more open. Of course, I understand that the motivation is PR-merging efficiency, since I also share this goal, but I believe that this can be compatible with explicit welcoming to the discussion.

Note that my remark is only on the principle, so that I feel respected as a member of the "community". In practice, I don't have anything to add to this particular PR apart from an explicit ok.

My remark is actually also related to the last WG. It was one of the most structured WG we had for a long time and I think that we can thank @ppedrot for the program and you (@maximedenes) for the very efficient chairing. I had only one request: I'd feel more respected as a participant if each slot were ended by some formal behavior of the form "has anyone anything else to add (2 seconds suspension), so, if no (1 more second suspension), let's move to the next topic". This is a common practice e.g. in chairing conference meetings. (If ever a question arrives,  depending on the time it would require, one can take it now or propose to come back to it later.)

Sorry if I'm a bit pushy in demanding to give _explicit_ time to discussion. Freedom of expression is central to our scientific communities and people like me need to feel that their words are welcome in whatever situations in order to feel well in such community.

**Comment by maximedenes** [comment]
I tend to agree about the WG chairing, but I'm not sure what to do about it. In fact, I think the root of the issue is that speakers consistently underestimate the time needed for discussion. At a conference, I've never seen a chair ask if somebody had something to add when the discussion had already gone 5 min+ past schedule.

So during the last WG, I chose to come back to suspended questions at the end of the schedule (you had such a question IIRC). But it would be much better indeed to allocate more time for discussion (and maybe have fewer slots/topics).

(We should move this discussion somewhere else.)

For this PR, I don't see what is wrong with my message. It is obviously not an order to @mattam82, so I was expecting him to do whatever he thinks appropriate to handle this PR, not necessarily to merge it without notice.

**Comment by mattam82** [comment]
I don't think this PR needs more discussion, so I'll merge.

**Comment by herbelin** [comment]
> For this PR, I don't see what is wrong with my message. It is obviously not an order to @mattam82 

Not obvious to me. I did perceive it as an order, and as said, it was not clear to me that the discussion was fully settled.

> so I was expecting him to do whatever he thinks appropriate to handle this PR, not necessarily to merge it without notice.

Maybe this was clear for you and him but I did not find it clear from the words you chose. For instance, other words could have been "could you take an action on this PR so that it does not vegetate? Thanks!"

About the WG, I'll open an issue to continue the discussion if I find some time. In any case, thanks for this exchange.

**Comment by Zimmi48** [comment]
It couldn't have been an order since:
- Maxime cannot give orders to Matthieu;
- the use of "could".

But anyways, whatever people ask the assignee, it is clear to me that it is the role of the assignee to decide if a PR needs a "last comments before merge" round or not, and certainly not the role of random developers asking for action on a PR.

**Comment by maximedenes** [comment]
As written above, I'm not dismissing all your points. But since you mention freedom of speech, I would appreciate that you let me choose my words without feeling entitled to tell me what I should have written instead. You tend to do this often, and here you were not even involved in the discussion.

Symmetrically, I'm sure @mattam82 can say for himself when he thinks some words were inappropriate. I'm ready to bet it is as clear to him as it is to me that he is not taking orders from me.

**Comment by herbelin** [comment]
>  I would appreciate that you let me choose my words without feeling entitled to tell me what I should have written instead. 

The discussion is degenerating on misunderstandings.

@maximedenes, you are of course free to choose the words you want. My point is not to tell you which words you should use. My point is to tell you which kind of behavior hurts me, just because I want to protect me from what hurts me, and I think that this is natural. I'm not claiming that my feeling is an absolute feeling but it is my feeling and I have no power on my feeling. I may be hypersensitive to words and I'm sorry about that. We all have to do with our respective hypersensitivity.

I know that it hurts you when I look like telling you what I think is good. So, maybe I should make efforts to make it clearer that it is not about telling you what it is good in an absolute way, but about what would save me some pain.

In particular, I did not judge whether your words to @mattam82 are appropriate or not. I replied to the assertion "It is obviously not an order to @mattam82". As said, I did perceive it as an order as a factual remark. In particular, I may try to analyse in which sense you say it is obviously not an order and why I personally feel it more as an order than as a suggestion. In particular, if I'm the only one to feel that it is a sentence which leaves little place for alternative attitudes, I can accept that it is my own hypersensitivity.

It would be absurd to turn all our communication into a purely formal communication where no word with higher pitch would be forbidden. But, at least, since there are some words from me to which you seem hypersensitive, and there are words from you to which I'm hypersensitive, I believe that it is worth at least to work at improving this communication between us.

In particular, our two first comments seem to have been constructive. Why did it degenerate?

**Comment by mattam82** [comment]
For the record, I felt absolutely not ordered to do anything, and the point of this PR was just to document the list of members of the code of conduct team, which didn't seem controversial. We're free to discuss the way the team is organised elsewhere.

**Comment by herbelin** [comment]
> For the record, I felt absolutely not ordered to do anything.

Then it is maybe that I missed some private exchange of information between @maximedenes and you. The sudden "non-order" of @maximedenes seem to have come from nowhere without the sign of a pre-established contract that he was in some way in charge of watching the PR. At least, as far as I'm concerned, I was really intending that there be a formal agreement on the names of the members of the code of conduct committee.

**Comment by Zimmi48** [comment]
I bet there was no such contact. I think you are the only one understanding things that way and over-interpreting. Maxime just asked for some action to be taken. It could have been a ping.

>I was really intending that there be a formal agreement on the names of the members of the code of conduct committee.

This was not the point of this PR. The names of the members of the enforcement team had already been settled in the previous PR. This one was just about making things explicit.

**Comment by herbelin** [comment]
> This was not the point of this PR. The names of the members of the enforcement team had already been settled in the previous PR. This one was just about making things explicit.

If you are talking about #8071, that was not so clear as far as I remember and as far as I can (quickly) rebrowse the discussion there. There was a discussion but I don't see a formal conclusion on the composition of the committee. Anyway, as said above, I approve that the committee is made of you and @mattam82, which moreover is helpful in establishing a mediating channel of communication between some people having some difficulties to find a fair common ground of interaction.

> I bet there was no such contact. I think you are the only one understanding things that way and over-interpreting. Maxime just asked for some action to be taken. It could have been a ping.

But why on this PR precisely? If Maxime wants actions to be taken, that's very good but there is a big list of PRs which require some care. For instance, it would be useful for me to have help on some of my PRs (such as checking spurious CI, applying a trivial rebase, reminding that an assignee is needed, reminding the assignee to do something, reminding me that I did not answer to a comment, ...) and it would be useful for the PRs of others too.

Actually, Maxime was formerly partly doing such job, which was useful, except that it was not as part of a clear contract and that it looked to me (and not only to me) to be done in a rather arbitrary way. So, maybe, if he wants, it may be a good moment to reconsider that Maxime helps in such "could you please do" reminders, along lines which are clear for everyone.

**Comment by maximedenes** [comment]
> It could have been a ping.

Exactly.

> Probably because he was the one who asked that this list be made explicit.

Not even, I just noticed it in the list of recently approved PRs. It was basically random.

> I'm feeling like I'm losing my time trying to explain the obvious

Same here.

**Comment by herbelin** [comment]
> Probably because he was the one who asked that this list be made explicit.

This is indeed a good reason, which I did not know.

> > I'm feeling like I'm losing my time trying to explain the obvious
> 
> Same here.

The notion of "obvious" is (obviously) context-dependent. I did not consider the list of members of the committee formally settled (even if, again, I approve it). I did not consider this PR to be just waiting for a merge which I felt to be à la hussarde. If there was a formal approval of the list, where was it done?

I'm reading in your messages that you (@zimmi48, @mattam82, @maximedenes) were in a "typing context" (a PR answering to a demand from @maximedenes for making the name public, the feeling that the list of the members was formally validated, ...). Would you accept that others can be in a different typing context and that some discussion is needed to make the two typing contexts consistent.

**Comment by maximedenes** [comment]
> This is indeed a good reason, which I did not know.

Lol. I wrote just above that it was not the reason. But never mind.

**Comment by herbelin** [comment]
>  wrote just above that it was not the reason. But never mind.

Ah sorry. (So, one hypothesis less in the typing context...)

**Pull request merged**
