### PR TITLE
The Release Plan wiki page has been removed.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation fix

@mattam82 and @ppedrot: I'll let you decide whether you want to merge this PR, or if it made sense to have those links and you want to recreate the page. In any case, we cannot leave broken links like that.

### CODE REVIEW

**Comment by ejgallego** [comment]
Removing that page seems like not a very good idea.

**Comment by gares** [comment]
If nobody keeps it up to date...

**Comment by ejgallego** [comment]
It seems to me that it is not a lot of effort to cut and paste the mail there, the information is critical I'd strongly support that RMs have to maintain it.

**Comment by Zimmi48** [comment]
Sure, I'm not arguing we should remove it. I'm only arguing that keeping 404 links in our README is bad. It's kind of disheartening to not have any single reaction of the new RMs in almost a week, but that would tend to show that this PR should be merged @ejgallego...

**Review by mattam82 — COMMENTED** [review]
Sorry didn’t see that. Can we make “symlinks” in the wiki without having to sync the guide every time? Otherwise let’s just rename the wiki page

**Comment by gares** [comment]
I think the real problem is not the broken link, but the fact that the page is/was outdated/removed.
And I don't buy the argument about copy pasting an email from coq-dev/club. What is the point of it, mailing lists are archived.

If the release manager(s) want to keep an up to date page about the plans for the next release because they believe it is useful, I pretty sure nobody objects. If they don't want to do that, let's just remove the stale link. If they prefer a project, a milestone, a whatever, they shall say so.

**Comment by Zimmi48** [comment]
> mailing lists are archived

Mailing list archives are notoriously hard to search, leading to people asking over and over the same questions. Copy/pasting the content of emails to coqdev would make sense if these e-mails are frequent enough to be up-to-date. Linking directly to the archived version of the last such e-mail would also make sense.

>Can we make “symlinks” in the wiki without having to sync the guide every time? Otherwise let’s just rename the wiki page

No, we can't unfortunately.

**Comment by mattam82** [comment]
I fixed the name of the wiki page and indeed plan to update it as we go along.

**Comment by Zimmi48** [comment]
Thanks!

**Pull request closed without merging**
