### PR TITLE
Use just one object declaration for all global universe additions

### PR DESCRIPTION
**Pull request by SkySkimmer**
The universe constraint object (for the `Constraint` command) and the universe object in hints.ml are redundant with the main universe object in declare so let's get rid of them.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
See my comments in #8113.

**Comment by ppedrot** [comment]
@herbelin are you fine with the PR so that I can merge it?

**Review by mattam82 — APPROVED** [review]
Indeed that's a welcome factorization

**Comment by ppedrot** [comment]
@SkySkimmer Can you rebase to be sure that the CI is fine?

**Comment by SkySkimmer** [comment]
Rabsed

**Comment by ppedrot** [comment]
Equations failure is spurious, it is due to the fact it was lacking a fix at the time the CI ran. I checked locally and it does compile now.

**Pull request merged**
