### PR TITLE
Modular printing algorithm for bench/render_results.

### PR DESCRIPTION
**Pull request by ppedrot**
The old code was a mess of handwritten ad-hoc code to print the result table in a fancy way. Instead of hardcoding everything this patch introduces a generic function to print a table of data. This will allow extension of the profiling information displayed to the user in an easy way.

I will first run a mini bench to check that everything is fine.

### CODE REVIEW

**Comment by ppedrot** [comment]
Mini-bench running at https://gitlab.com/coq/coq/-/jobs/861030261.

**Comment by Zimmi48** [comment]
If you're interested, you could also generate a Markdown table and store it as an artifact. If you do this, we could print it directly in the GitHub Checks tab (we could also do it with the traditional ASCII-art table of course).

**Comment by ppedrot** [comment]
The check tab is not very practical for archival purposes, I'd rather have the bot post it in the PR thread. But indeed, it's quite orthogonal to the output data representation.

**Comment by Zimmi48** [comment]
OK

**Comment by gares** [comment]
The code is much better, but I wonder if one could use OCaml's tabulation boxes (from the Format module)

**Comment by ppedrot** [comment]
@gares I don't think so, this looks to simple for the data considered here. We have to right-align, and have multicolumns. Actually I didn't find how to do that even in the github Markdown syntax.

**Comment by ppedrot** [comment]
Current display:
```
┌────────────────────────┬───────────────────────┬─────────────────────────────────────┬─────────────────────────────────────┬───────────────────────┬─────────────────┐
│                        │     user time [s]     │             CPU cycles              │          CPU instructions           │ max resident mem [KB] │   mem faults    │
│                        │                       │                                     │                                     │                       │                 │
│           package_name │    NEW     OLD  PDIFF │           NEW            OLD  PDIFF │           NEW            OLD  PDIFF │    NEW     OLD  PDIFF │ NEW  OLD  PDIFF │
├────────────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│ coq-mathcomp-ssreflect │  50.36   50.80  -0.87 │  137906721419   138461659487  -0.40 │  174559073803   174557268117   0.00 │ 514388  514484  -0.02 │   0    0    nan │
├────────────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│           coq-coqprime │  78.50   79.13  -0.80 │  216516183451   216869213479  -0.16 │  301797298830   301835127964  -0.01 │ 762768  762788  -0.00 │   0    0    nan │
├────────────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│            coq-coqutil │  58.92   59.13  -0.36 │  164564102595   164769494952  -0.12 │  202986280685   202993550477  -0.00 │ 525344  524072   0.24 │   0    0    nan │
├────────────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│                    coq │ 520.75  520.52   0.04 │ 1461280104155  1457987007848   0.23 │ 1953882938161  1953953099865  -0.00 │ 578688  578936  -0.04 │   0    0    nan │
├────────────────────────┼───────────────────────┼─────────────────────────────────────┼─────────────────────────────────────┼───────────────────────┼─────────────────┤
│              coq-flocq │ 157.12  156.44   0.43 │  436318139055   434431738007   0.43 │  539185431706   539195225832  -0.00 │ 823372  823332   0.00 │   0    0    nan │
└────────────────────────┴───────────────────────┴─────────────────────────────────────┴─────────────────────────────────────┴───────────────────────┴─────────────────┘
```

It looks good. I am just realizing that I've forgotten to add the percents in the PDIFF columns, but actually I find this output better. Anyway it's a trivial patch if you want it.

**Comment by Zimmi48** [comment]
Column-alignment in Markdown syntax is actually easier to do. E.g.,

```
| title | x |
|---:|---|
| foooooo | |
| bar | |
```

gives:

| title | x |
|---:|---|
| foooooo | |
| bar | |

However, you cannot do multi-columns AFAIK.

**Comment by ppedrot** [comment]
@SkySkimmer would you assign?

**Comment by ppedrot** [comment]
@SkySkimmer ping

**Review by SkySkimmer — APPROVED** [review]
I didn't look closely but this shouldn't be risky so let's go

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
