### PR TITLE
[warnings] [doc] Preliminary support for dumping known warnings

### PR DESCRIPTION
**Pull request by ejgallego**
This is very preliminary work adding a `-dump-warnigns` option that
could be used by IDEs and documentation to check exhaustiveness.

There still remains a non-trivial amount of work to do in order to
reify the pretty printing structure so we could produce an structured
representation of the warning message, but it is doable.

### CODE REVIEW

**Comment by gares** [comment]
My understanding is that this won't dump warnings which are declared in plugins, like Ltac1/2, ssr, ring, ...
I wonder if a command line switch is the wrong approach (even for the ref man).

If the need is the one to get an easy to parse list of documented warnings/errors with pointers to their place in the doc, maybe the input should be the doc, and not the coq binary.

**Comment by ejgallego** [comment]
> My understanding is that this won't dump warnings which are declared in plugins, like Ltac1/2, ssr, ring, ...
> I wonder if a command line switch is the wrong approach (even for the ref man).

Good point, let me add support for plugins and pass to the `coqc` call the list of plugins in the standard Coq distribution.

> If the need is the one to get an easy to parse list of documented warnings/errors with pointers to their place in the doc, maybe the input should be the doc, and not the coq binary.

That could work well too for the UI side, however the idea of this patch is to actually be able to check that docs are up-to-date in terms of warnings [they cover all of them for example]

**Comment by gares** [comment]
Basing this kind of consistency check on an open registration mechanisms seems the wrong approach to me.

One could have a common source of standard warnings, which is both embedded in the doc and compiled/linked to coq. And use a registration API only for external plugins. I mean, a file which is roughly what you are generating (plus the description), and that is both "compiled" to .rst and to .ml.

**Comment by jfehrle** [comment]
It would be great to automatically extract all the errors and warnings from the source code so the doc can be checked against that list.  A couple challenges I see and questions:

1. IIUC what you have now is an option for when you run coqtop.  Interfacing it to `doc_grammar`, which already has code to scan/update the rst files (or duplicating some of that code in a new utility) might give a bit of an unusual/complex build process.  (Just an intuition, no specific objection).

2. The doc already includes nonterminals for substituted values in various messages, such as in:
`.. warn:: @ident is already declared as a typeclass`
At the least, we want to know where values are substituted and ideally what the associated non-terminal is.  Knowing the latter may require an explicit annotation in the source code.  If we don't reliably know the non-terminal, the utility code can be somewhat clever about matching and also flagging changed messages with substitutions for manual review.  (That will still leave it pretty easy to end up with the wrong non-terminal in the doc.)

3.  It would be helpful if there was a way to uniquely identify each warning/error message.  That might permit a utility to automatically update the rst for minor wording changes.  `doc_grammar` already uses the tactic name/command name to automatically update their syntax.  But we'd need a clever idea on how to match existing vs updated messages.

4.  Currently errors and warning are spread throughout the text of the documentation, generally associated with a single tactic/command.  They include text explanations of the messages.  @Zimmi48 and I agree that this doesn't make a lot of sense because many messages apply to multiple tactics/commands.  So we might rethink how we present these messages.  Perhaps they should all be a separate section of the manual, perhaps grouped by category.

**Comment by Zimmi48** [comment]
@gares

>use a registration API only for external plugins

This was kind of the idea of #12347 (but limited to categories). IMHO one of the two approaches is needed, but I don't have a strong opinion on which.

(BTW, as soon as there is a file which lists all the warnings, even if it is an `ml` file, it is easy to ensure it is in sync with the documentation, even if only manually.)

@jfehrle 

> So we might rethink how we present these messages. Perhaps they should all be a separate section of the manual, perhaps grouped by category.

I don't think they should be grouped in a dedicated section of the manual: the index does already the job of grouping them. I think that we can inspire from what we did for attributes: most of them are documented as "top-level objects" but they are documented inside a command description when they are specific to this command. This is also how we do things for flags and options and I think we should do the same for error messages and warnings (keep the ones that are specific to a particular command / tactic in the corresponding description and document the rest of them on their own, adding a list of links from the descriptions of commands / tactics that can raise them).

BTW, Jim you might want to rename `doc_grammar` into something else if you extend it to support automatic sync of error messages / warnings / attributes (not really grammar-related).

**Comment by gares** [comment]
> This was kind of the idea of #12347 (but limited to categories).

I looked at it and its original form seems OK to me (the `+=` suggestion leads to the same problem this PR faces: the list of warnings printed depends what you link to Coq and Coq has plugins, eg ltac).

We already have in the code base some stuff like this, eg pretype_errors.ml. Of course consolidating into a single ADT all the warnings we have in the code base is quite some work, while the current patch is more lightweight, but it also makes it more correct, IMO. Side note, I'm also not a big fan of our in-tree plugins, which could be just linked in once and forall... making this argument moot.

**Comment by ejgallego** [comment]
In the short term, I think a flag `-dump-plugin-warnings plugin_name` could work well and make sense: when you are writing the doc for a plugin, it is reasonable that the doc toolchain may want to query info about that object.

Implementing the above is easy tho I'd prefer we push findlib integration first so plugin name is a findlib name which IMHO solves many issues with low-level stuff about object files.

**Comment by jfehrle** [comment]
> @Zimmi48 I don't think they should be grouped in a dedicated section of the manual: the index does already the job of grouping them. I think that we can inspire from what we did for attributes: most of them are documented as "top-level objects" but they are documented inside a command description when they are specific to this command

I expect there are many messages that apply to multiple tactics/commands.  It doesn't make too much sense to put those under a specific command.  Determining that a message is specific to a command may not be easy and can't be automated--it may require a close reading by a developer who is expert on that tactic/command.

We could, for example, group all typechecking errors together in a typechecking section in the doc, probably a good idea, but again that requires analysis of the code (though probably not as much analysis as required to attribute a message to a specific tactic/command).  For this, it would be helpful if the tooling of this PR included the name of the file where the message is defined.  Perhaps the line number, too.

There are quite a few messages that would need to be added, and probably we should review all messages to decide whether they are tactic/command specific.  Not a small effort.  Getting explanations for messages and describing them in the text would be even more work.

A few stats:
382 uses of CErrors.user_err in source code
238 `.. exn` in rst files

119 uses of CWarnings.create
35 `.. warn` in rst files

> BTW, Jim you might want to rename `doc_grammar` into something else if you extend it to support automatic sync of error messages / warnings / attributes (not really grammar-related).

Perhaps.  That's trivial.  Or it could be a separate tool.  `doc_grammar` is far more complex than what would be needed for errors and warnings.  There's perhaps 100 lines of code in `doc_grammar` for updating the rsts which could be reused or copied to create the initial version of a separate tool.  Probably better to make it a separate tool rather than trying to force all the rst-updating tooling into a single program.

**Comment by Zimmi48** [comment]
>I expect there are many messages that apply to multiple tactics/commands. It doesn't make too much sense to put those under a specific command.

We are in agreement on this. But there are also messages which are specific to a command or a tactic and those can be documented under the appropriate description. I expect that for many error messages, it's actually easy to determine if it's specific to a particular tactic / command or more generic. It's also OK to document an error message under a specific tactic / command if this is the only one we know of that raises this error message even if we could have missed some other cases. We can always refactor later on if we need to.

>We could, for example, group all typechecking errors together in a typechecking section in the doc

Indeed, type checking errors are typical examples of errors that are not specific to a particular tactic or command as they can be raised from many tactics. Furthermore, we do have a typing rules section which is only limited to a theoretical presentation and which I would like to see evolve into a type checking section with some practical matters like these error messages.

**Pull request closed without merging**
