### PR TITLE
[experiment] Synchronous constraint accumulation and merging in process_universe_constraints

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1952644440

**Comment by ppedrot** [comment]
metacoq is not part of the bench it seems, and this was the target. Not sure what to think then, probably not worth it otherwise.

**Comment by SkySkimmer** [comment]
Make a metacoq dev package and add it to the bench.

**Comment by ppedrot** [comment]
Not worth it, especially considered #15466.

**Pull request closed without merging**
