### PR TITLE
UnivSubst: don't use Not_found for flow control

### PR DESCRIPTION
**Pull request by SkySkimmer**
Overlays:
- https://github.com/SkySkimmer/coq-lean-import/pull/6

### CODE REVIEW

**Comment by Alizter** [comment]
@coqbot bench

**Comment by Alizter** [comment]
OK as expected no change in bench.

**Review by Alizter — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]
Using exceptions for global flow control should be punished by exceptional butt-kicking.

**Comment by ppedrot** [comment]
CI failures are unrelated, so @coqbot merge now

**Pull request merged**
