### PR TITLE
[xml-protocol doc] Fix link to vscoq

### PR DESCRIPTION
**Pull request by artagnon**
**Kind:** documentation.

### CODE REVIEW

**Comment by artagnon** [comment]
@herbelin Here it is.

**Review by herbelin — APPROVED** [review]
Thanks!

I'm assigning while leaving time for possible comments.

**Review by Zimmi48 — APPROVED** [review]
I guess it makes sense to fix the URL in both places and not just the second one.

**Comment by herbelin** [comment]
> I guess it makes sense to fix the URL in both places and not just the second one.

Which is what is done, right? So, merging?

**Comment by Zimmi48** [comment]
Yeah, that's the point of me approving the PR.

**Pull request merged**
