### PR TITLE
[v8.13] [CI] Update paramcoq branch to v8.13

### PR DESCRIPTION
**Pull request by proux01**

### CODE REVIEW

**Comment by gares** [comment]
great thanks!

**Comment by gares** [comment]
Sorry, I made a mistake, merged this one and then reverted it.

The branch of Coq v8.13 does not track branches in it's CI, but rather commits (pinned branches).
I'm happy to update the commit we track to the head of the branch you propose here, but not to a moving target.

**Comment by proux01** [comment]
This v8.13 branch of paramcoq is not intended to move (it could probably be just a tag, I don't remember why we made branches).
So do as you prefer (the advantage of the v8.13 branch is that we are sure it is what will be made available in the opam package).

**Comment by gares** [comment]
If you make a tag, I'll pick it up, just tell me its name

**Comment by proux01** [comment]
Here it is : https://github.com/coq-community/paramcoq/tree/v1.1.2%2Bcoq8.13

**Comment by gares** [comment]
thanks

**Pull request merged**
