### PR TITLE
Remove deprecated files in Arith and Numbers/Natural

### PR DESCRIPTION
**Pull request by Villetaneuse**
* Removed in Arith:
    - Div2.v
    - Even.v
    - Gt.v
    - Le.v
    - Lt.v
    - Max.v
    - Minus.v
    - Min.v
    - Mult.v
    - Plus.v
    - Arith_prebase.v

* Removed Numbers/Natural/Peano/NPeano.v
* Many "Require" statements involving these files removed in other parts of the library
* Several deprecated lemmas removed in Arith/EqNat
* Register commands moved from Arith_prebase to PeanoNat
* `arith` hint database moved from `Arith_prebase` to `Arith_base`
* Lemmas in `Arith_base` used only for the hint database have been blacklisted from Search
    
* Some test files had to change:
    -  bugs/bug_13307.v
    -  bugs/bug_1779.v
    -  bugs/bug_4187.v
    -  bugs/bug_4456.v
    -  modules/Nat.v
    -  success/Funind.v
    -  success/RecTutorial.v
    -  success/Require.v (Not sure about this one)
    -  success/extraction.v
    -  success/import_lib.v

- [ ] ~Added / updated **test-suite**.~

- [x] Added **changelog**.
- [ ] ~Added / updated **documentation**.~

#### Overlays (to be merged before this PR)
- [x] fiat_crypto_legacy https://github.com/mit-plv/fiat-crypto/pull/1738
- [x] https://github.com/PrincetonUniversity/VST/pull/747
- [x] Iris https://gitlab.mpi-sws.org/iris/stdpp/-/merge_requests/535
- [x] https://github.com/coq-community/corn/pull/202
- [x] https://github.com/mattam82/Coq-Equations/pull/570
- [x] https://github.com/QuickChick/QuickChick/pull/344
- [x] https://github.com/coq-community/atbr/pull/40
- [x] https://github.com/coq-community/autosubst/pull/33
- [x] https://github.com/mit-plv/bbv/pull/47
- [x] bedrock2 should be ok with https://github.com/mit-plv/kami/pull/37
- [x] https://github.com/fblanqui/color/pull/49
- [x] https://gitlab.inria.fr/coquelicot/coquelicot/-/merge_requests/11
- [x] cross_crypto in progress https://github.com/mit-plv/cross-crypto/pull/34 and https://github.com/adampetcher/fcf/pull/45 should be ok once the fcf submodule is bumped
- [x] https://github.com/coq-community/coq-dpdgraph/pull/126
- [ ] TODO fiat_parsers
- [x] https://gitlab.inria.fr/flocq/flocq/-/merge_requests/23
- [x] https://github.com/math-comp/hierarchy-builder/pull/398
- [x] https://github.com/DeepSpec/InteractionTrees/pull/260
- [x] https://github.com/coq-community/math-classes/pull/121
- [x] https://gitlab.inria.fr/fpottier/menhir/-/merge_requests/36 is merged to master but there is a version problem, see https://github.com/coq/coq/pull/18189
- [x] metacoq in progress https://github.com/MetaCoq/metacoq/pull/1011
- [x] https://github.com/Mtac2/Mtac2/pull/394
- [x] https://github.com/coq-community/paramcoq/pull/116
- [x] https://github.com/mit-pdos/perennial/pull/57
- [x] https://github.com/coq-community/coq-ext-lib/pull/140
- [x] https://github.com/mit-plv/rewriter/pull/119 and https://github.com/mit-plv/rewriter/pull/123
- [x] https://github.com/ejgallego/coq-serapi/pull/365
- [x] https://github.com/DeepSpec/sf/pull/11
- [x] https://github.com/smtcoq/smtcoq/pull/130
- [x] https://github.com/uds-psl/coq-library-undecidability/pull/210
- [x] https://github.com/uwplse/verdi-raft/pull/97

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by Villetaneuse** [comment]
Since the CI is idle on Sunday, I'm running it (I hope it's ok, sorry if it's not) to evaluate how many overlays will be needed.

**Comment by Villetaneuse** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
Wow, that sounds like a lot of work. Feel free to ping the various maintainers so that they update their code.

**Comment by proux01** [comment]
I should personally handle paramcoq and I could have a look at Flocq.

**Comment by Villetaneuse** [comment]
> Wow, that sounds like a lot of work. Feel free to ping the various maintainers so that they update their code.

Don't you think I should wait for a review before starting these?

**Comment by Villetaneuse** [comment]
I think I will have to shellscript my way out of this :D

**Comment by palmskog** [comment]
Both `ci-atbr` and `ci-verdi-raft` should be compatible with this PR now.

**Comment by Villetaneuse** [comment]
> Both `ci-atbr` and `ci-verdi-raft` should be compatible with this PR now.

ci-autosubst is also good.

**Comment by proux01** [comment]
> > Wow, that sounds like a lot of work. Feel free to ping the various maintainers so that they update their code.
> 
> Don't you think I should wait for a review before starting these?

Well, as far as I can see you are just removing things that were deprecated in 8.16 (three versions ago) so this should be consensual (I mean, if anyone opposes the deprecation, it should have already been discussed by now).

**Comment by Villetaneuse** [comment]
> > > Wow, that sounds like a lot of work. Feel free to ping the various maintainers so that they update their code.
> > 
> > 
> > Don't you think I should wait for a review before starting these?
> 
> Well, as far as I can see you are just removing things that were deprecated in 8.16 (three versions ago) so this should be consensual (I mean, if anyone opposes the deprecation, it should have already been discussed by now).

There could be a discussion about what is happening with Arith_prebase, the Search Blacklists and the modified test files. 
But you're right, it does not harm to modify the external libs anyway.

**Comment by proux01** [comment]
ci-paramcoq should now work and I have a merge request for Flocq that I'll submit when Inria gitlab is back tomorrow.

**Comment by Villetaneuse** [comment]
> ci-paramcoq should now work and I have a merge request for Flocq that I'll submit when Inria gitlab is back tomorrow.

Thank you very much!

**Comment by proux01** [comment]
Added a list of overlays (done and todo) to track them in the top comment.

**Comment by Villetaneuse** [comment]
@JasonGross It's really a lot of work. Could you do fiat-parsers yourself this time, please?

**Comment by JasonGross** [comment]
Is it not possible to write a script that processes the deprecation warnings and automatically replaces all occurrences with the suggested replacement?

**Comment by JasonGross** [comment]
Or are you suggesting that we just dump the file contents in coq-tools compat for fiat-parsers again?  That I can do, though I'm pretty busy this week and might not get to it until next week.  (Ping me again on Tuesday if you haven't seen anything from me by then)

**Comment by palmskog** [comment]
Since we merged https://github.com/ejgallego/coq-serapi/pull/365 SerAPI should now be compatible with this PR.

**Comment by Villetaneuse** [comment]
> Since we merged [ejgallego/coq-serapi#365](https://github.com/ejgallego/coq-serapi/pull/365) SerAPI should now be compatible with this PR.

Thank you very much!

**Comment by mrhaandi** [comment]
`ci-coq-library-undecidability` should be compatible with this PR since https://github.com/uds-psl/coq-library-undecidability/pull/210.

**Comment by proux01** [comment]
Let's rerun CI to get some intermediate check

@coqbot run full ci

**Comment by Villetaneuse** [comment]
The failure in `cross-crypto` was expected: the PR is not yet merged and there is also the issue of which commit they target in the git submodule `fcf`.

**Comment by Villetaneuse** [comment]
@JasonGross the current to-do list is close to complete. Could you please handle fiat-parsers (with or without coq-scripts)?

**Comment by JasonGross** [comment]
I will definitely not have time before next week, but can try to take a look shortly (work is currently extremely busy for me and I don't have much time to devote to maintenance)

**Comment by RalfJung** [comment]
FWIW std++ is building fine without any deprecation warning on Coq 8.18. So looks like there is a gap in the deprecation system: the deprecation warning does not ensure that code will actually build when the module is removed.

**Comment by Villetaneuse** [comment]
> FWIW std++ is building fine without any deprecation warning on Coq 8.18. So looks like there is a gap in the deprecation system: the deprecation warning does not ensure that code will actually build when the module is removed.

Yes, std++ is certainly one of the best maintained library I had to work with on this PR. The problem here is the lack of deprecation warning for a file in Coq. This is being addressed in Coq/Coq#18193.

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by Villetaneuse** [comment]
> @coqbot run full ci
`vst` has failed, it looks real (and new); probably discovered now because compcert and menhir now build
Iris has a timeout.
I don't understand the failure in `quickchick_test`; it does not seem related to this PR; but maybe it would be solved with a rebase on master.
All the other failures were expected:
- unmerged pull requests for `coq_dpdgraph`, `metacoq`, `equations_test`
- `fcf` not bumped in `cross-crypto`
- I still have to work on `perennial`
- We're waiting for Jason for `fiat-parsers`

**Comment by SkySkimmer** [comment]
What about fiat_crypto_legacy?

**Comment by Villetaneuse** [comment]
> What about fiat_crypto_legacy?

Hmm... Since it automatically pings Jason, I was hoping he would handle it. I can give it a try... I'm almost sure fiat crypto will also need wome work.

**Comment by JasonGross** [comment]
> I will definitely not have time before next week, but can try to take a look shortly (work is currently extremely busy for me and I don't have much time to devote to maintenance)

@Villetaneuse if you'd be willing to take a stab at this, I'd be grateful, since I'm still quite busy.  I'm happy to drop compatibility for old versions (no need to change anything in coq-scripts, and I can take care of updating the CI to remove whatever versions any PR you prepare doesn't build with), since at this point I see keeping fiat-parsers on Coq's CI as mostly just about covering things the test suite might not cover.

**Comment by proux01** [comment]
@coqbot run full ci

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
As agreed during the last meeting, putting the last failing CI entries in allow_failure mode (so that their maintainers can take care of them at their own pace) and merging.

@coqbot merge now

**Comment by proux01** [comment]
Yes, I even remember checking during the wrapup at the end of the discussion that there was no disagreement on that point. The notes indeed lack precision.

**Pull request merged**
