### PR TITLE
Do not evar normalize potential hints in TC local database construction.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
I think that some speed-ups in the per-line diff of fiat-crypto are real, but they're drowned in an ocean of noise.

**Comment by ppedrot** [comment]
This needs an assignee. @SkySkimmer maybe?

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
