### PR TITLE
[ide] Rely less on `Stateid.dummy`

### PR DESCRIPTION
**Pull request by ejgallego**
In particular, we set queries from the menu to the tip of the
document, and process feedback coming with a `dummy` id.

There are still more places to tweak, but this should be good for now.

### CODE REVIEW

**Comment by herbelin** [comment]
Queries from menu still don't work but this removes the "tip document" message. Thanks.

While we are talking about CoqIDE, this new underlining of warnings is a really great feature!

**Comment by ejgallego** [comment]
@herbelin the underlining was supposed to be in 8.6 but it somehow got masked; it would easy to fix in 8.6.

I'll have a look to see what is going on with the queries from the menu, AFAICT they should be displayed in the message buffer.

**Comment by ejgallego** [comment]
Ok @herbelin , menu queries should work now. There is some work remaining to fix the query pane display, but that may need an update to the protocol.

**Comment by herbelin** [comment]
@ejgallego: it works wondeful. Looking forward being it integrated.

**Comment by herbelin** [comment]
Hi, I fell on a similar problem with `coqtop` and `Load`, if ever there is some hint on what can be done to fix it. After loading a file which fails such as a file containing the following:
```coq
Goal True.
apply S.
```
then `Print S` returns `Currently, the parsing api only supports parsing at the tip of the document.
You wanted to parse at: 1 but the current tip is: 2`.

**Comment by ejgallego** [comment]
Hi @herbelin `Load` remains unfortunately broken for the moment.

We understand the problems and hopefully a fix will be ready soon, but it makes no sense to look at it again until #566 is resolved.

**Comment by herbelin** [comment]
@coqbot: Thanks!

**Comment by ejgallego** [comment]
thx

**Pull request merged**
