### PR TITLE
Update section on adding your project to CI and link to example PR.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Are we dropping travis?

**Review by ejgallego — APPROVED** [review]
I am OK with this; we should discuss what to do with Travis, in my view I'd like to have it as backup at least until INRIA can provide custom workers, or `-local` goes away.

But I guess we can omit the Travis information for now, as it is likely that Travis will be only used for very specific targets in the future.

**Comment by Zimmi48** [comment]
> Are we dropping travis?

Eventually, I think so. The recent ExtLib + QuickChick were approved without adding anything to Travis. I have been removing failing jobs from Travis so currently Travis is very incomplete compared to GitLab CI. I prefer not to recommend adding to Travis to avoid some later annoyance (like timeouts, not-up-to-date dependencies, etc). That doesn't mean that it's forbidden to add to Travis of course.

**Comment by ejgallego** [comment]
@SkySkimmer are you ok with this?

**Review by SkySkimmer — APPROVED** [review]

**Pull request merged**
