### PR TITLE
[experiment] Do not retype unchanged goals in the subst tactic.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
neural-net seems fake for sure, that line doesn't use subst.

**Comment by ppedrot** [comment]
The PR and commit comment are wrong, it's not really the subst tactic, rather it's an internal function used e.g. by inversion.

**Comment by ppedrot** [comment]
Let's rerun a @coqbot bench

**Pull request closed without merging**
