### PR TITLE
Respect Print Universes when printing primitive arrays

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Well found (again).

This does not need much review I believe.

Assigning and merging tomorrow.

**Comment by SkySkimmer** [comment]
@herbelin is it tomorrow yet? 
(mtac2 failure is spurious)

**Comment by herbelin** [comment]
Let's reschedule it for today, then (sorry).

**Comment by herbelin** [comment]
@coqbot: merge tonight

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
