### PR TITLE
Docker image: Bump lablgtk to 3.1.2

### PR DESCRIPTION
**Pull request by btj**
Enables PR #15399 which addresses #12779.

Waiting for https://github.com/ocaml/opam-repository/pull/20323

### CODE REVIEW

**Comment by SkySkimmer** [comment]
IMO this should be as part of #15399, not a separate PR.

**Comment by btj** [comment]
@ppedrot told me to do this in a separate PR ( https://github.com/coq/coq/pull/15399#issuecomment-1000801962 )

**Comment by ppedrot** [comment]
I think it's better to have this as a distinct PR, for better separation of concerns.

**Comment by ppedrot** [comment]
This PR should also bump the version requirements in the various build files. I see various references to lablgtk 3.1.0 in the source, e.g. `tools/configure/configure.ml` and `test-suite/coq-makefile/timing/precomputed-time-tests/007-no-output-sync/time-of-build.log.in`. I am a bit surprised that there is no explicit lablgtk dependency in the coqide opam files but I'm not a build system expert...

**Comment by SkySkimmer** [comment]
The test suite timing logs have a lot of old garbage in them.

**Comment by btj** [comment]
Status: I'm waiting for @garrigue to update opam package `lablgtk3-sourceview3`. In any case, many thanks to @garrigue for all of the efforts!

**Comment by btj** [comment]
Waiting for PR https://github.com/ocaml/opam-repository/pull/20323 to be merged.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
lablgtk 3.1.2 requires ocaml >= 4.09, but that's higher than Coq's minimum ocaml version. cc @garrigue

**Comment by NickGeek** [comment]
Is anything blocking this now that https://github.com/ocaml/opam-repository/pull/20323 has been merged?

**Comment by Zimmi48** [comment]
Yes, we have to decide if we want to bump the minimal supported OCaml version in Coq 8.16, and if yes, to which version.

**Comment by SkySkimmer** [comment]
We bumped ocaml to 4.09 so this just needs a rebase.

**Comment by btj** [comment]
Closing; fixed in https://github.com/coq/coq/commit/899f89a83518a51b59ed17f8bfab3551ebf3c673

**Pull request closed without merging**
