### PR TITLE
[stm] options are global, not per document

### PR DESCRIPTION
**Pull request by gares**
Supersedes https://github.com/coq/coq/pull/16896
CC @ppedrot

### CODE REVIEW

**Comment by SkySkimmer** [comment]
fiat-crypto seems happy

serapi wants an overlay

**Comment by gares** [comment]
I'm on the overlay. But I'm a bit confused serapi depends on mathcomp.

**Comment by gares** [comment]
This needs an assignee

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
Does somebody have access to serapi to merge the overlay? IIUC @ejgallego is in vacations so we're going to break the Coq CI for a while if we merge this now.

**Comment by Zimmi48** [comment]
Yes, I have.

**Comment by ppedrot** [comment]
OK, let's go then. @coqbot merge now

**Pull request merged**
