### PR TITLE
Convert tactics chapter to prodn, part 1

### PR DESCRIPTION
**Pull request by jfehrle**
This is not ready for a close review.  I suggest we start by considering whether there is any gross reorganization we want to do up front.  It may also make sense to review the grammar updates _en masse_.  The other question is how much of the text we want to revise in this PR.  Currently there are no changes until line 582.  The "Applying theorems" section runs to 1056.  Perhaps that's a good chunk to do in this PR?

That said, let's give priority to the review of #13892 and #13815.  And would be nice to complete #13860 and #13846, too.

WDYT?

### CODE REVIEW

**Comment by Zimmi48** [comment]
> I suggest we start by considering whether there is any gross reorganization we want to do up front.

After the sections that we have already taken out of the tactics chapter, and after #13892, the next tactics I would like to move to their dedicated page ("Reasoning with inductive types") are tactics to work with inductive types. This would be:
- `constructor`, `split`, `exists`, `left`, `right` and variants (currently presented at the end of the `Applying theorems` section)
- the entire "Case analysis and induction" section.

Other than that:
- the "Checking properties of terms" section + the `evar` tactic should move to the Ltac chapter;
- `admit` should move the Proof mode chapter (where `give_up` is already documented);
- eventually `instantiate` and possibly even `refine` (the most basic and general tactic) should move to the Proof mode chapter.

**Comment by jfehrle** [comment]
Sure, let's finish #13892 first.  Do you want to the history-preservation dance for moving some or all of these?

**Comment by Zimmi48** [comment]
Possibly yes if it's not too difficult. But I'll take care of it since I have the experience now.

**Comment by silene** [comment]
As this is still a draft, I am postponing it to 8.15.

**Comment by Zimmi48** [comment]
Since this is a pure documentation PR, it might still end up in one of the 8.14 milestone for backporting. But let's remove the milestone for now.

**Comment by jfehrle** [comment]
@Zimmi48 Can we disable the sorcerer's apprentice for draft PRs?  A updated version of this PR will certainly be merged after other doc work has been completed. The open status makes it easy for the submitter to see what tasks they have pending.  Also, there should be a tag that a submitter can set to keep a stale PR open for a while. Frankly, I don't see the value in automatically closing things--is more of a hassle for submitters, for whom contributing to Coq is not their first priority.

**Comment by Zimmi48** [comment]
I'm deferring to @ppedrot to answer to / take into account this feedback. But note that it's on purpose that draft PRs weren't excluded from this mechanism.

**Pull request closed without merging**
