### PR TITLE
NArith: add sized N2Bv

### PR DESCRIPTION
**Pull request by liyishuai**
**Kind:** feature.
- [x] Entry added in CHANGES.

### CODE REVIEW

**Comment by herbelin** [comment]
Looks indeed useful, thanks.

I incidentally have an open question at large. What would be the clearer: to use `xH`, `xI`, `xO` or to use their notations `1`, `~1`, `~0`? This would mean also changing `P2Bv`.

Anyway, the PR looks consistent enough in style with the rest of the file as it is. In the absence of further comments within a couple of days, as canonical assignee, I'll shall merge it (typically on next Wednesday).

**Comment by liyishuai** [comment]
I've realized that there already exists [N2Bv_gen](https://coq.inria.fr/library/Coq.NArith.Ndigits.html#N2Bv_gen).
Shall we revert these changes to avoid duplication?

**Comment by herbelin** [comment]
> I've realized that there already exists N2Bv_gen.

Ow. That would be better to avoid duplication indeed. But if you did not see it that's probably that `N2Bv_gen` is not visible enough. Also, is it worth to have `P2Bv_gen` (or `P2Bv_sized`)? If the author of the file (@letouzey) could comment, that would be helpful.

**Comment by liyishuai** [comment]
It would be worth keeping `P2Bv_gen` if there are real world practices that use `positive` explicitly.

**Comment by liyishuai** [comment]
https://github.com/coq/coq/pull/6597#discussion_r213880595 shows that converting between other types and `positive` is rather tricky.
I think `positive` should be limited as a helper type for constructing `Z` and `N`. There are `NArith` and `ZArith`, but nobody complained about arithmetic support for `positive`.

**Pull request merged**
