### PR TITLE
Cleanups and minor fix around evar normalization

### PR DESCRIPTION
**Pull request by SkySkimmer**
Replace https://github.com/coq/coq/pull/14373

- make UnivSubst private, avoiding misuse of nf_evars_and_universes_opt_subst 
- change the logic of to_constr aborting to check the term after normalizing. We use a mutable ref to keep track of whether we saw any undefined evars to avoid doing extra work in common cases (ie all cases which didn't abort previously). Solves incorrect aborting when an undefined evar appears as an unused argument of a defined evar.

Overlay: https://github.com/Mtac2/Mtac2/pull/337

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@herbelin do you have a test case for "Solves incorrect aborting when an undefined evar appears as an unused argument of a defined evar." / https://github.com/coq/coq/pull/14373 ?

**Comment by SkySkimmer** [comment]
Bench https://gitlab.com/coq/coq/-/jobs/1420684244

**Comment by herbelin** [comment]
> @herbelin do you have a test case for "Solves incorrect aborting when an undefined evar appears as an unused argument of a defined evar." / #14373 ?

This was in a modified version of Coq and I don't fully remember how I got the example, so it is better to renounce.

In any case, thanks for the PR. I'm closing the other one.

**Comment by SkySkimmer** [comment]
OK, I made an artificial example https://github.com/coq/coq/issues/14648

**Review by ppedrot — APPROVED** [review]
Code changes are fine. Can we get a bench though?

**Comment by ppedrot** [comment]
Ah, sorry, I've missed the bench link in the conversation, so this PR is indeed ready.

**Comment by ppedrot** [comment]
Merging soon then.

**Pull request merged**
