### PR TITLE
[general] Remove Econstr dependency from `intf`

### PR DESCRIPTION
**Pull request by ejgallego**
To this extent we factor out the relevant bits to a new file,
ltac_pretype.

### CODE REVIEW

**Comment by ppedrot** [comment]
If it's supposed to stay in pretyping, it shouldn't be called ltac-something. Otherwise it indicates it shouldn't be there.

**Comment by ejgallego** [comment]
> If it's supposed to stay in pretyping, it shouldn't be called ltac-something. Otherwise it indicates it shouldn't be there.

Umm, what would you call it? It contains stuff such as `ltac_var_map` etc... I'll happily change the name.

For better or worse the pretyper still has ltac-dependent stuff, and IMO fixing that is unrealted to this PR, which tries to fix some of the mess of `library` depending on Econstr etc...

**Comment by maximedenes** [comment]
@ppedrot do you request changes on this PR?

**Comment by maximedenes** [comment]
@ppedrot ping

**Review by ppedrot — APPROVED** [review]
Yep, sorry. While not ideal, this seems to be locally OK. Hopefully at some point we really disentangle the dependency to Ltac, but when that happens, we'll know.

**Pull request merged**
