### PR TITLE
 Removing template polymorphism for definitions.

### PR DESCRIPTION
**Pull request by ppedrot**
(This PR sits atop #888, so that only the last patch is relevant for review.)

The use of template polymorphism in constants was quite limited, as it
only applied to definitions that were exactly inductive types without any
parameter whatsoever. Furthermore, it seems that following the introduction
of polymorphic definitions, the code path enforced regular polymorphism as
soon as the type of a definition was given, which was in practice almost
always.

Removing this feature had no observable effect neither on the test-suite,
nor on any development that we monitor on Travis. I believe it is safe to
assume it was nowadays useless.

(And yes, removing template polymorphism is a feature.)

### CODE REVIEW

**Comment by silene** [comment]
That is a nice cleanup.

**Comment by herbelin** [comment]
I don't know how much template-polymorphic constants directly pointing to inductive types (such as `Definition PROD := prod`) are used. There were some requests many years ago for such feature, maybe from CoRN, I don't remember.

Is it correct that the direct workaround to recommend to users is to define instead the constant as polymorphic, i.e. `Polymorphic Definition PROD x y := prod x y.`? Or shall we thus loose the ability to instantiate universes with `Prop`? By the way, is there a reason a universe cannot be instantiated with `Prop` for those who need it?

**Comment by SkySkimmer** [comment]
I would just do `Notation PROD := prod.`
As far as I can see the use cases for template polymorphic definitions (given how restricted they are) are:
- renaming for prettiness / documentation
- different implicit argument behaviour
- alias to guide unification / typeclasses

The last one can't be done by notations but the others can.

**Comment by mattam82** [comment]
Yes that's a workaround. One reason is that it's hard to ensure we don't create universes i such that Prop < i < Set if we allow Prop in instances. We'd also have to enrich the universe algebra with an impredicative max as done in Lean for example, but it would still be imprecise I think, unless we add kind of "conditional" constraints to the graph like (i = Prop -> Prop <= j) /\ (i > Prop -> Set <= j) to propagate impredicavity.

**Comment by SkySkimmer** [comment]
I would just not handle impredicativity when instantiating with Prop.
if `A : Type@{i}` and `B : Type@{j}`, `A -> B : Type@{max i j}` is still true even if `j = Prop` after all.

**Comment by herbelin** [comment]
@SkySkimmer: Indeed.

@mattam82: OK, I can imagine the kind of problems (and forgive me if I ask the question again later on because I had forgotten the answer).

**Comment by silene** [comment]
@mattam82: Not sure if it helps, but note that your conditional constraint is just `min(i,Set) <= j` (assuming `min(Prop,Set) = Prop`).

**Comment by mattam82** [comment]
It's not min, more like imax(Set,i) <= j which is defined as 
imax(i,j) = { Prop if j = Prop ; max(i,j) otherwise }

**Review by maximedenes — APPROVED** [review]
I had only a brief look, but this clean up looks very good.

**Pull request merged**
