### PR TITLE
[coqide] Port to GtkSourceView4

### PR DESCRIPTION
**Pull request by ejgallego**
This is still a work in progress; main change upstream is the
completion API, which it is still not fully implemented.

However with https://github.com/garrigue/lablgtk/pull/101 , CoqIDE
seems to run, so we can indeed hack on both projects together.

**edit**: after merging #11400 completion is broken in this branch.

**Kind:** infrastructure

- [ ] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by ejgallego** [comment]
Until the sourceview4 package is not released into opam CI will not work properly here.

Meanwhile, it can be tested by using dune and linking the `lablgtk` folder in.

**Comment by ejgallego** [comment]
update: after merging #11400 completion is broken in this branch.

**Comment by Zimmi48** [comment]
Any reason for not having made this a Draft PR? Do you actually want the reviews that were requested?

**Comment by ejgallego** [comment]
> Any reason for not having made this a Draft PR? Do you actually want the reviews that were requested?

Indeed a Draft PR would have been better, on the other hand indeed this can use some review already from the @coq/coqide-maintainers

**Comment by herbelin** [comment]
> This is still a work in progress; main change upstream is the completion API, which it is still not fully implemented.
> 
> **edit**: after merging #11400 completion is broken in this branch.

Looks good. Do we (you or @ppedrot) know more about was is "not fully implemented"? Is there something to be done/investigated? Since the code apparently compiles without a change, Is it that maybe an initialization is missing in the code of coqide, or something still to be implemented at the lablgtk3 level?

**Comment by ejgallego** [comment]
> Do we (you or @ppedrot) know more about was is "not fully implemented"? Is there something to be done/investigated? Since the code apparently compiles without a change, Is it that maybe an initialization is missing in the code of coqide, or something still to be implemented at the lablgtk3 level?

I'd say both, the completion API is different in sourceview4, so even if it compiles it needs a different sequence of calls I think. So the current port needs action at both levels.

A reminder if someone is curious to work on this, the easiest way is:
```
$ cd coq-master && git clean -fxd # make sure the checkout is clean, beware!
$ hub checkout https://github.com/coq/coq/pull/11412
$ hub clone https://github.com/ejgallego/lablgtk/ -b lablgtk3+sourceview4 lablgtk
$ make -f Makefile.dune coqide
```

**Comment by herbelin** [comment]
For the sake of completeness of the discussion, see [lablgtk PR#101](https://github.com/garrigue/lablgtk/pull/101#issuecomment-612530951) for the very small work needed to complete the port, as far as I could see.

I'm unsure that GtkSourceView 4 differs much from GtkSourceView 3.24 at the current time, but it it cannot hurt and will allow to keep synchronized with the new evolutions to come.

**Comment by Alizter** [comment]
@ejgallego What is the status of this PR, any plans to continue?

**Comment by ppedrot** [comment]
IIUC this is essentially blocked on upstream update of the code. We should make progress there instead...

**Pull request closed without merging**
