### PR TITLE
[release] update changelog w.r.t. the latest backports on v8.18

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by maximedenes** [comment]
@coqbot merge now

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
If this was for 8.18+rc1, why was this put in the 8.18.0 milestone?

**Comment by gares** [comment]
Thanks for fixing

**Comment by SkySkimmer** [comment]
because 8.18+rc1 is closed

**Pull request merged**
