### PR TITLE
Move tests in bugs/ to the appropriate bugs/opened/ or bugs/closed/.

### PR DESCRIPTION
**Pull request by nlewycky**
**Kind:** infrastructure.

- [*] Added / updated test-suite

### CODE REVIEW

**Comment by Zimmi48** [comment]
Hum, why close the PR?

**Comment by nlewycky** [comment]
Testing failed.

**Comment by Zimmi48** [comment]
@nlewycky You shouldn't let this disturb you though. Sometimes CI failures can be independent of the PR, and even if that's not the case, we can provide help to fix the remaining issues.

**Comment by nlewycky** [comment]
I shouldn't have uploaded it at that time. The test-suite wasn't yet passing locally with no changes, so I ignored failures with the patch applied too (I checked for failures w.r.t. these specific files, but didn't see any). When the CI failed I wanted to close it quickly to avoid wasting anyone else's time looking at it. Sorry!

In the mean time, I've sorted my issues with make test-suite, and am now actually ready to start review. I'll reopen.

**Comment by nlewycky** [comment]
Sorry again. I missed that this was from nlewycky:master when it should have been from nlewycky:move-tests. The new pull request is #8455 .

**Comment by Zimmi48** [comment]
No worries. Thanks for the PR!

**Pull request closed without merging**
