### PR TITLE
coqdep: Windows: fix normalisation of paths containing \

### LINKED ISSUE #17953: Windows: coqdep does not normalise paths containing back slashes correctly
#### Description of the problem

Coq 8.17.1 introduced a change in coqdep which has the effect that paths containing a \ (which appears to be introduced by coqdep) are not normalised correctly. This breaks e.g. the build of coq-hammer-tactic on Windows.

A fix is on the way.

#### Coq Version

```
The Coq Proof Assistant, version 8.17.1
compiled with OCaml 4.14.1
```

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
Fixes / closes #17953

### CODE REVIEW

**Comment by Zimmi48** [comment]
This will also be a problem in 8.18+rc1, since this has already shipped, but the fix can be merged in time for 8.18.0.

The Windows failure is due to the Coq website being down.

**Review by rlepigre — CHANGES_REQUESTED** [review]
Thanks for fixing this!

There are two more occurrences of this pattern [higher up in the file](https://github.com/coq/coq/pull/17954/files#diff-1418ced694e4da004fe2f814f227350736818e8e71caccbc8b74bf2d31ac7f4bL94-L95), I think they need to be taken care of too.

I think it would be a good idea to have a separate function for the splitting, for example:
```ocaml
let split_file_path : string -> string list =
  if Sys.win32 then
    Str.split_delim (Str.regexp "[/\\]")
  else
    String.split_on_char '/'
```

**Comment by jp-diegidio** [comment]
I have zero experience with OCaml, anyway here is what I have found, hoping I am not simply misspeaking:

Trying to narrow this down, I have ended up with the OCaml's `Filename.dir_sep` being the culprit: whose value, I suppose (I haven't investigated further), depends on the linked library's original compilation platform (as opposed to be computed at run-time or even deployment time).

That said, since there is a `Sys.win32` property that can be used to detect the current OS, a code patch here (short of fixing OCaml itself) would be to replace the built-in `Filename.dir_sep` (all calls to it) with a custom version that does take the OS into account (as opposed to "post-patching" any path manipulations all over the place...).

(That wouldn't fix the shell scripts, though those are probably less of a problem.)

**Comment by rlepigre** [comment]
Actually, if the goal is to normalize all paths to using `/` as directory separator on windows, you replace all the calls to `Filename.concat` with something like:
```ocaml
let filename_concat : string -> string -> string =
  Printf.spritnf "%s/%s"
```
I think I introduced all the `Filename.concat` in https://github.com/coq/coq/pull/17270, thinking the code would be more portable, but that was a mistake. I would not be surprised if replacing all the `Filename.concat` would be a sufficient fix.

**Comment by rlepigre** [comment]
> IMHO we should fix the bug now, discuss what we want for the future and how to implement it and then go for it.

I agree we should not delay this fix for too long. I was just trying to make sure that this fix does not re-introduce the same kind of issue that https://github.com/coq/coq/pull/17270 was fixing. That being said, the problem would only arise on Windows, which is already broken, so just merging the current MR should not hurt more.

**Comment by gares** [comment]
My understanding is that this fix makes sense.
Ideally one would stop using OCaml's filename separator and concatenation api  everywhere.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
@coqbo run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Pull request merged**
