### PR TITLE
Cleaner fix for layout issue of #10578

### PR DESCRIPTION
**Pull request by jfehrle**
It appears to be sufficient to update the position in the idle loop (i.e. after layout is complete).  The call is described [here](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-idle-add).  Simpler than b7a9d3e02b01124179f5a9cdf217a4f4f13d8c24.

### CODE REVIEW

**Comment by ppedrot** [comment]
It depends quite a bit on implementation details of the IDLE callback, so ideally this should be tested on several machines / platforms.

**Comment by silene** [comment]
In particular, we have to make sure that no Paint event happens before the Idle event can trigger the new Layout+Paint events. Otherwise we will just be regressing to the old bug, that is, a first layout is displayed and then a second one, which causes an ugly visual glitch.

**Comment by jfehrle** [comment]
> @ppedrot ideally this should be tested on several machines / platforms.

I did the work on Ubuntu (on WSL).  I would be surprised if this doesn't work correctly on any other Linux variant.  If I'm able to build a native Windows version, I can try that, too.  Beyond those, I would need others to try it.  What other platforms would be most likely to behave differently?

> It depends quite a bit on implementation details of the IDLE callback

The event loop uses a priority system, so I expect the behavior is well-determined and consistent across platforms.  Priorities are described some [here](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#GMainLoop).

**Comment by jfehrle** [comment]
> @silene Otherwise we will just be regressing to the old bug

Do you mean #10578 or a different bug?  The original description in #10578 says:

> When starting Coqide, its layout is completely messed up until the first interaction of the user with the window (e.g., clicking the "forward step" button). Only the "messages" lower part is visible, neither script nor goals are visible. On 50 consecutive starts of Coqide, the initial layout was correct only three times.

In a couple dozen starts of CoqIDE, I always see the expected layout with this version.

I see the window is initially painted as an all-black rectangle, possibly done by XWindows.  Then the window is painted twice, which is easy to see only by adding a `Unix.sleep` call in the idle loop callback.  Otherwise, it's almost imperceptible--I have to pay close attention to notice the second paint.  The all-black paint is much more noticeable since it's a strong contrast to the white of the GUI.

The existing code with the magic numbers is very obscure.  The flicker seems quite minor to me.  Perhaps you would be willing to try the change on your system?

FWIW, [g_idle_add_full](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-idle-add-full) would let us control the priority, which might allow avoiding the extra repaint, but that's not accessible with the current  `lablgtk3`.  The [doc](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#G-PRIORITY-HIGH-IDLE:CAPS) says:

> GTK+ uses G_PRIORITY_HIGH_IDLE + 10 for resizing operations, and G_PRIORITY_HIGH_IDLE + 20 for redrawing operations. (This is done to ensure that any pending resizes are processed before any pending redraws, so that widgets are not redrawn twice unnecessarily.)

**Comment by silene** [comment]
> Do you mean #10578 or a different bug?

No, I mean the fact that the window is painted twice in a quick succession with a layout change inbetween. You say that the "flicker is quite minor". But first, it is a subjective matter. What might seem minor to you might not be for other users. And second, it is obviously dependent on the operating system, window manager, refresh rate, etc. That is why it needs to be tested on various machines by various users.

The only difference between the original code (before #10578) and yours is that the second redraw is caused by an internal event (the idle one) instead of an external one (e.g., a mouse move). This causes the second redraw to happen a bit earlier. But it does not change the fact that there are two redraws in a quick succession, which is noticeable, as minor as it might be.

**Comment by jfehrle** [comment]
Perhaps you would try the change and let us know whether it works for you.

**Comment by jfehrle** [comment]
The change works correctly on Windows.

**Comment by jfehrle** [comment]
Somewhat off topic: I see that this callback in `Coqide.build_ui` is called a couple times a second even while the GUI is idle.  That seems pretty peculiar.  The size is always the same.

```
  let _ = w#misc#connect#size_allocate
            ~callback:(fun rect -> window_size := (rect.Gtk.width, rect.Gtk.height)) in
```

**Comment by herbelin** [comment]
I used the PR for a while yesterday and it apparently works well (on MacOS X).

> Somewhat off topic: I see that this callback in `Coqide.build_ui` is called a couple times a second even while the GUI is idle. That seems pretty peculiar. The size is always the same.
> 
> ```
>   let _ = w#misc#connect#size_allocate
>             ~callback:(fun rect -> window_size := (rect.Gtk.width, rect.Gtk.height)) in
> ```

Are you suspecting a gtk or lablgtk bug in `size_allocate`?

------

PS: On MacOS, starting Coqide produces (3 copies of) a message "Drawing a gadget with negative dimensions." which I don't know how to fix. Are you trying to eventually fix this message?

**Comment by herbelin** [comment]
About the flicker, I did not notice it at first, but if one wants to pay attention, it is visible.

**Comment by ppedrot** [comment]
@herbelin so you're actually saying that this PR is indeed introducing a regression?

**Comment by herbelin** [comment]
> introducing a regression?

I would not say that. This "flickering" (*) can easily be interpreted as a step of the initialization.

(*) Concretely, the "flickering" is that "Welcome to CoqIDE, ..." appears for a 10th of a second (or even shorter) in the middle of the whole coqide windows before reappearing in the message buffer.

The code in this PR seems less tricky to me than the previous one, so I would still lean to prefer this code.

**Comment by jfehrle** [comment]
> Are you suspecting a gtk or lablgtk bug in `size_allocate`?

The number of messages smells buggy, but I don't know that it's relevant to the flicker.  I often note unexpected behavior that's not immediately relevant--sometimes they become important clues.

FWIW, I just tried this variation based on the [doc](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#G-PRIORITY-HIGH-IDLE:CAPS).  With +21 there is a flicker and with +20 the allocation is 1 (i.e. not useful for setting the divider location).

```
  let prio = Glib.(int_of_priority `HIGH_IDLE) + 21 in (* after sizing, before drawing *)
  ignore @@ Glib.Idle.add ~prio (fun _ ->
```

> PS: On MacOS, starting Coqide produces (3 copies of) a message "Drawing a gadget with negative dimensions." which I don't know how to fix. Are you trying to eventually fix this message?

No.  I don't see that message on Ubuntu or IIRC native Windows.  I do see messages like this from time to time.  Eventually I'd like to investigate why:

`GtkDialog mapped without a transient parent. This is discouraged.`

Also, I've wondered how difficult it is to get changes into lablgtk3 or gtk3 itself (if I ever am tempted to try that).  Do you have any experience doing that?

**Comment by ppedrot** [comment]
FTR, this PR works as intended on Debian amd64 + KDE + qt5-gtk. I wouldn't mind more users to test it, still.

**Comment by jfehrle** [comment]
In a Coq Call discussion, we thought we couldn't be certain that this works for all possible cases.  Hard to prove a negative with testing.

**Pull request closed without merging**
