### PR TITLE
Gitlab: retry failed jobs once

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure if we want this but let's talk about it.

### CODE REVIEW

**Comment by Zimmi48** [comment]
See also coq/bot#3.

**Comment by ejgallego** [comment]
Maybe worth doing only on failed base builds; and maybe a couple of the heavier ones, as these are more likely to be interrupted.

Tho I agree that the bot can do much better as gitlab should report if the cause of the failure was due to the script or the worker.

**Comment by Zimmi48** [comment]
> Maybe worth doing only on failed base builds

Why not for the base builds, they don't cost so much to retry.

> GitLab should report if the cause of the failure was due to the script or the worker

It does but it still misses a lot of runner failures (that are displayed as script failures). Should we report this whenever we see it?

**Comment by SkySkimmer** [comment]
It properly retried jobs which failed due to being unrebased ^^

**Comment by ejgallego** [comment]
So do we want this retry configuration? Seems a bit expensive to me?

**Comment by Zimmi48** [comment]
Let's put it only for the base builds for now.

**Review by ejgallego — CHANGES_REQUESTED** [review]
What @Zimmi48 said, let's try with base builds only for now.

**Comment by SkySkimmer** [comment]
Changed

**Review by ejgallego — APPROVED** [review]

**Pull request merged**
