### PR TITLE
Added an option Set Debug Cbv

### PR DESCRIPTION
**Pull request by herbelin**
This is the `Set Debug Cbv` I made for @JasonGross. Submitting it as a PR was suggested by @tchajed.

It is very basic and there is clearly room for more user-available debugging tool in Coq.

### CODE REVIEW

**Comment by tchajed** [comment]
Awesome, thanks @herbelin!

**Comment by JasonGross** [comment]
Thanks!  Can you also make a PR for set Ltac batch debug?

**Comment by maximedenes** [comment]
Looks good to me.

**Comment by Zimmi48** [comment]
Same question here about the absence of documentation.

**Pull request merged**
