### PR TITLE
mind_kelim is the highest allowed sort instead of a list

### PR DESCRIPTION
**Pull request by SkySkimmer**
I think this is closer to how it really works.

Overlay: https://github.com/mattam82/Coq-Equations/pull/205

### CODE REVIEW

**Comment by ppedrot** [comment]
Isn't that breaking the impredicative set option? The new code seems to preserve the old semantics, but it feels wrong that we don't have to handle the possibility that Set is another root type to prevent System U⁻-style paradox. Said otherwise, isn't the current code already broken?

**Comment by SkySkimmer** [comment]
What's a root type, and what would it mean to handle Set as a root type in the context of allowed eliminations?

**Comment by ppedrot** [comment]
A universe `U` is a root in the sense that no other sort has this type, i.e. there is no other universe `s : U`. Girard's paradox essentially states that it is not possible to have two non-root impredicative universes, IIRC. In presence of inductive types you have to be careful to reflect this in their elimination rules, otherwise you can trigger the paradox via boxing.

I never quite understood the rules for impredicative Set, but I thought that they were tricky enough to break the linear ordering of elimination you're making explicit in this PR.

**Comment by SkySkimmer** [comment]
If we can eliminate to a predicate in Set then by cumulativity we can also eliminate to a predicate in Prop.

**Comment by ppedrot** [comment]
But is Prop ⊆ Set in impredicative mode?

**Comment by SkySkimmer** [comment]
Yes

Gaëtan Gilbert

**Review by ppedrot — APPROVED** [review]
I am convinced.

**Comment by ppedrot** [comment]
I'll let @maximedenes and @mattam82 optionally comment before merging, just in case.

**Comment by ppedrot** [comment]
This needs a rebase (and the overlay as well probably), I'll merge this PR afterwards.

**Review by maximedenes — COMMENTED** [review]
I'm not competent to comment on the interaction between this and `-impredicative-set`. An ok from @mattam82 would be welcome.

**Comment by SkySkimmer** [comment]
Why would there be an interaction? This just replaces the list [0..n] by 
the number n.

Gaëtan Gilbert

**Comment by maximedenes** [comment]
> Why would there be an interaction? This just replaces the list [0..n] by the number n.

What I'd like is a confirmation that this PR is not making obvious that we handle `-impredicative-set` incorrectly. It is a non-blocking request (i.e. this can be merged meanwhile).

**Comment by SkySkimmer** [comment]
>What I'd like is a confirmation that this PR is not making obvious that we handle -impredicative-set incorrectly.

I don't understand this sentence.

**Comment by ppedrot** [comment]
@maximedenes the PR doesn't change the current behaviour. At worst, master is already broken w.r.t. impredicative set.

**Comment by gares** [comment]
> > What I'd like is a confirmation that this PR is not making obvious that we handle -impredicative-set incorrectly.
> 
> I don't understand this sentence.

I think @maximedenes understands this PR is just a cleanup. Now that the code is clean, and semantically equivalent, he is asking if the code is correct. If it is not the case, then we should open an issue and fix it.

**Comment by maximedenes** [comment]
> I think @maximedenes understands this PR is just a cleanup. Now that the code is clean, and semantically equivalent, he is asking if the code is correct. If it is not the case, then we should open an issue and fix it.

Exactly.

**Review by mattam82 — COMMENTED** [review]
Looks very good to me, it’s a welcome simplification I was going to suggest from formalizing this in MetaCoq :)

**Comment by mattam82** [comment]
About impredicative-set, I think what should happen is that ind_squashed becomes true when using impredicative-set to put a large type in set, the everything should work similarly to Prop-squashing. Not sure this happens today though.

**Pull request merged**
