### PR TITLE
restrict minimization to set to flexibles

### PR DESCRIPTION
**Pull request by SkySkimmer**
Split from #10331
Fix part of #8196
Replaces #9343

### CODE REVIEW

**Comment by Janno** [comment]
Based on my local build using your branch it seems like this part of the patch doesn't break Mtac2 in any way.

**Comment by maximedenes** [comment]
@SkySkimmer what's the status of this?

**Comment by maximedenes** [comment]
Will rebase.

**Comment by maximedenes** [comment]
Could this get a quick review? @ppedrot or @mattam82 maybe?

**Comment by ppedrot** [comment]
Unfortunately I cannot swear I understand this code...

**Comment by maximedenes** [comment]
@mattam82 I believe you had discussed this patch with @SkySkimmer during the CUDW. Can you give a final green light? Note that the other part of the patch is still to be studied as part of #10331.

**Review by mattam82 — APPROVED** [review]
Yep, it is a fine bugfix, we should not tamper with rigid universes.

**Pull request merged**
