### PR TITLE
Further round of simplification of the Future API

### PR DESCRIPTION
**Pull request by ppedrot**
This PR simplifies quite a bit the Future API and provides new invariants enforced by typing. Each commit message is pretty self-explanatory, but for the sake of completeness let us mention here the major changes.
- Future joining was removed and implemented locally in the opaque table module (the only place that needs it)
- Non-blocking futures (that were never used) have been removed
- The fix_exn type was defunctionalized
- The delegated future implementation was (internally) defunctionalized
- The `par:` implementation does not use futures anymore
- A couple of clean-ups.

Now we only have one call defining delayed futures and one call defining delegated futures in the STM. Very little code actually uses the future API which should make it even easier to turn this into something easy to reason about.

Overlays:
- https://github.com/maximedenes/vscoq/pull/2

### CODE REVIEW

**Comment by gares** [comment]
> What's the difference between force and join exactly?

I was documented in the header: a joined thunk cannot be chained. When a thunk reached the safe env, that was final an joining it would have freed a system state (morally the closure). Now that futures are ouside, where states are handled, I don't think we should keep that.

**Comment by ppedrot** [comment]
> Am I right that force now changed meaning?

No, the resulting value is still stored. There used to be two references per future: one for the join, one for the force. Only the former was removed, and we still store imperatively the result of force into the latter.

**Review by gares — CHANGES_REQUESTED** [review]

**Comment by gares** [comment]
My point is that your fix in the overlay is breaking the (experimental) vscoq backend (in a way it was not broken before).

>  If incorrect I can amend this PR to reinstate nonblocking futures, it's fairly easy.

So I think you should amend.

I know fixing the situation is much more work, as you observed one has to fix all clients. This is why non-blocking futures were cheaper. Leave them there, they don't seem to impede the other cleanups in this PR.

**Comment by ppedrot** [comment]
> So I think you should amend.

If you're happy with that I can go that way.

> My point is that your fix in the overlay is breaking the (experimental) vscoq backend (in a way it was not broken before).

Even with a reinstatement of non-blocking futures, I'd like some empirical argument for that and / or @maximedenes input on the topic. I don't think that this PR is making this backend more broken than it is currently, and I'd like to be challenged on that.

**Review by gares — APPROVED** [review]

**Pull request merged**
