### PR TITLE
[api] Move `Evar` out of API.

### PR DESCRIPTION
**Pull request by ejgallego**
We need to determine what part of the API should do in internal.
I'm afraid I am not qualified for that, so comments welcome.

c.f. issue #6008

### CODE REVIEW

**Comment by SkySkimmer** [comment]
`unsafe_of_int` should probably be internal.
Maybe `repr` too.

**Comment by ejgallego** [comment]
> unsafe_of_int should probably be internal.
> Maybe repr too.

Done, thanks!

**Comment by herbelin** [comment]
I don't understand this `unsafe_int` business. Why not to move generation of evars in `evar.ml` with  a `create : unit -> t`, and to replace the `repr` by a `to_string`? Then, we get a true abstraction without an unsafe_thing whose name suggests that it is not needed but which in practice is the only available constructor.

**Comment by JasonGross** [comment]
> I don't understand this `unsafe_int` business. Why not to move generation of evars in `evar.ml` with  a `create : unit -> t`, and to replace the `repr` by a `to_string`?

I like this proposal.  However, if we ever want (e.g., in template-coq) to be able to reflect evars and denote them back, we should probably keep something like `Unsafe.to_int` and `Unsafe.of_int`.  (Actually, there's a similar issue in universes, where currently (template-coq can't reflect and denote universes)[https://github.com/gmalecha/template-coq/blob/3798874/src/reify.ml4#L158-L160] because there's no unsafe universe API that round-trips to a non-opaque representation.

**Comment by herbelin** [comment]
@JasonGross: To reflect evars, you could reflect them through `string`, without having to know the exact internal representation, but, for the reverse path, one would need also an `of_string`, I agree.

For universes, to extract, one could probably decode `Pp.of_string (Univ.pr u)`, but indeed, I don't see anything to get an "arithmetical" representation of `universe` suitable for representation in Gallina. Is there already a PR about that?

PS: @ejgallego: I allow myself to change EVar to Evar in the PR title!

**Comment by herbelin** [comment]
... but I suspect that by using `Universe.sup`, `Universe.super`, `Level.var`, `Universe.make`, you can re-embed what the decoding of `Univ.pr` would have given you. (But I agree that relying on `pr` is fragile).

**Comment by ppedrot** [comment]
@herbelin Ideally, evars should not be generated by a global uid generator, but should be local to every evar-map (notwithstanding issues like `par:` and the like that would need some careful design). We should go towards more purity, not less. But then you get some loop between Evd and the kernel, and you have to resort to this unsafe hatch to cut it out.

Also, it's generally better to have an API flagged as *don't use it* if it has clear simple semantics (here, the identity) and can sometimes save the day for the plugin writer.

**Comment by SkySkimmer** [comment]
Evar (and universe level) generation doesn't sound like the responsibility of the kernel to me.

Universe levels can be roundtripped, see the hack `interp_universe_level_name` in pretyping which is used by funind.
Algebraic universes can be roundtripped if you hack around with references and `Univ.Universe.for_all`.
In both cases there's no clean way to do it though.

**Comment by herbelin** [comment]
> But then you get some loop between Evd and the kernel

I realized this afterwards. Sorry for having spoken too fast.

> and you have to resort to this unsafe hatch to cut it out.

But then, it is an issue with the underlying programming language. There is nothing "unsafe" in `unsafe_int`. It is more "don't use, it is to circumvent the difficulty to lately define the effective-though-concealed implementation of the type".

As was mentioned by @mattam82, or you, I don't know remember exactly, what we would like is that `Constr.t` depends abstractly on `Name.t`, on `Id.t`, on `Evar.t`, on `metavariable`, without the burden of manipulating everywhere in the kernel an heavy-to-read type `('n,'i,'e,'m) Constr.t`.

Are there languages which would allow such kind of abstraction: `evar.mli` declares a `type t = '_a`, and, later, the instantiation is given by `type Evar.t = int` in `evd.ml`, with the additional guarantee that `Evar.t` has never been instantiated before this`type Evar.t = int`, thus ensuring that this `'_a` behaved like an abstract parameter for the kernel?

Or maybe we can simulate this with a function `Evar.activate : unit -> (int -> Evar.t) * (Evar.t -> int)`, whose code would check that it is activated only once, so that after `Evd` uses it, no one else can use it anymore.

**Comment by ejgallego** [comment]
Closing #6075 #6076 #6077 as it seems they are not gaining a lot of traction. In the past they used to be largish PRs, however, after the API removal all the PRs on the kernel are just a few lines, as these base libraries tend to have a full public interface. #6008 still applies thou.

**Pull request closed without merging**
