### PR TITLE
Clean the API of Evar_tactics

### PR DESCRIPTION
**Pull request by ppedrot**
We move this module from the Ltac plugin to the tactics/ folder and merge it with proofs/evar_refiner. This removes some dubious APIs in the process.

Overlays:
- https://github.com/ejgallego/coq-serapi/pull/290

### CODE REVIEW

**Comment by ppedrot** [comment]
Argh, `lglob` doesn't parse at the same level as `uconstr`...

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
The fix was actually easier than expected, so I consider this ready. (There is even an added test for a simple behaviour we didn't check.)

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Missing link to overlay PR

**Pull request merged**
