### PR TITLE
Clean transparent state

### PR DESCRIPTION
**Pull request by ppedrot**
We move `Names.transparent_state` to its own module `TranspState`. We furthermore turn it into a named record and provide accessors functions. This was documented in `dev/changes.md`. Due to the architecture of the `Names` module I could not add deprecation around the old API (this would have created a dependency cycle), but they are probably rarely used by plugins.

### CODE REVIEW

**Comment by gares** [comment]
Hum, two things:
- between `TranspState` and `TransparentState` I prefer the latter, given how little the former saves you and how obvious the latter makes the transition (in habit)
- if we have to rename this, I think we could also take the occasion to pick a name that does not mean "the state is transparent" but rather "constants to be (not) unfolded"

Bottom line: you don't need to clean the state, it is already transparent...

**Comment by mattam82** [comment]
Agreed with @gares here, it should already have been transparency_state or unfolding_state, and equations will likely need an overlay.

**Comment by ppedrot** [comment]
So should I call this module `TransparencyState`?

**Comment by gares** [comment]
I would propose `UnfoldBlacklist` but looking at its content I'm not sure I totally understand which piece of info it holds. I suspect is maps constants names to `YesUnfoldMe`, `NoDon'tUnfoldMe`, `DoAsYouWhish`...
`UnfoldingPreference`?

**Comment by ppedrot** [comment]
It just holds a boolean for every constant / variable, contrarily to `conv_oracle` which contains a full strategy.

**Comment by ppedrot** [comment]
So, any contender for the name?

**Review by maximedenes — APPROVED** [review]
No strong opinion. Change to record looks good.

**Comment by maximedenes** [comment]
This needs a rebase, it seems.

**Review by herbelin — COMMENTED** [review]
OK to me.

**Review by Zimmi48 — APPROVED** [review]
This makes things much clearer, thanks!
You could have made the type opaque and added setters to change the opacity of one variable / constant but I suppose you didn't because there was no point in doing this...
Why are some o(caml)doc comments above what they document and some below?

**Comment by ppedrot** [comment]
This still needs an overlay though, I'll try to find time to write this down.

**Comment by SkySkimmer** [comment]
>This still needs an overlay though, I'll try to find time to write this down.

How's it going?

**Comment by ppedrot** [comment]
Almost done, it's just a mess to compile dependencies that are implicit in the CI. I'll update this shortly.

**Comment by ejgallego** [comment]
What do you mean @ppedrot?

**Comment by Zimmi48** [comment]
Submodules, I suppose.

**Comment by ppedrot** [comment]
For some reason the overlays are not working properly, but the respective downstream changes do compile manually. Anybody understanding this better than me?

**Comment by Zimmi48** [comment]
The error in Windows is because the overlay for equation was not correctly picked up. Looking at the log, `CI_PULL_REQUEST` and `CI_BRANCH` were given empty values:

```
+13:37:08 '[' -n '' ']'
+13:37:08 export CI_BRANCH=
+13:37:08 CI_BRANCH=
+13:37:08 export CI_PULL_REQUEST=
+13:37:08 CI_PULL_REQUEST=
+13:37:08 export TRAVIS_BRANCH=
+13:37:08 TRAVIS_BRANCH=
+13:37:08 export TRAVIS_PULL_REQUEST=
+13:37:08 TRAVIS_PULL_REQUEST=
```

@SkySkimmer @ejgallego @MSoegtropIMC I wondered what changed and could have broken this (it used to work, right?)

**Comment by ppedrot** [comment]
As far as I am concerned, the PR is ready. CI failure on windows is spurious and reflects an unrelated bug of the latter.

**Comment by MSoegtropIMC** [comment]
@ppedrot : ok @Zimmi48 found the issue and fixed it in #8918. So I agree that the Windows64 failure was due to a bug in my CI code.

**Comment by SkySkimmer** [comment]
>@ppedrot : ok @Zimmi48 found the issue and fixed it in #8918. So I agree that the Windows64 failure was due to a bug in my CI code.

That is not a @Zimmi48 PR ;)

**Review by maximedenes — CHANGES_REQUESTED** [review]
Sorry, but @gares' comment was ignored: can we get `TransparentState` instead of `TranspState`? I can do the change if you like.

**Comment by maximedenes** [comment]
Also, is the Dune failure real?

**Comment by ppedrot** [comment]
@maximedenes I quite don't care about the name. If you have time to perform the diff and adapt the overlays I'd be glad but otherwise I'll do it.

**Comment by ppedrot** [comment]
This is ready. The windows64 failure is spurious.

**Review by maximedenes — APPROVED** [review]

**Pull request merged**
