### PR TITLE
CI: disable bin_annot (for smaller artifacts)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
build:base:dev size is reduced 235MB (example https://gitlab.inria.fr/coq/coq/-/jobs/5082020) -> 184MB

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Not a huge effect but probably worth it since it's so easy to do.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
