### PR TITLE
No implicit shelving

### PR DESCRIPTION
**Pull request by maximedenes**
This is an experiment following a comment by @mattam82. This PR is on top of #12872, to view the real change, look at the last commit.

I realized that for #7825, we need to know the future, which is not easy. Indeed, we need to know whether `future_goals` are going to be shelved or not by the caller. Of course, I could blindly propagate the information, but I'd rather understand first why we need this implicit shelving (as opposed to making `future_goals`... future goals).

The first failures I saw in the test suite were all due to a `Grab Existential Variables` that was used to unshelve the implicitly shelved goals, which makes me wonder if it is a feature or a bug.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Looks like it makes it so that econstructor stops shelving. Typically
~~~coq
Goal exists n:nat, n = n.
Proof.
  econstructor;[reflexivity|exact 0].
Qed.
~~~
shouldn't work.

**Comment by maximedenes** [comment]
You're example does not work :) but I see your point, something has to be done for `econstructor`.

**Comment by SkySkimmer** [comment]
Oh that's funny, the `.` is making the second goal available so when I tested `2: exact 0` it worked

**Comment by maximedenes** [comment]
> Oh that's funny, the `.` is making the second goal available so when I tested `2: exact 0` it worked

Yeah, in fact the more I think about it, the more I find that most people expect `run_tactic` to not do anything. In master it shelves, here it creates new goals. But anything it does is a difference between `tac1; tac2` and `tac1. tac2.`

**Comment by maximedenes** [comment]
In fact, I don't see why the shelving is done by `run_tactic` rather than the tactic itself (like for `refine`). @ppedrot, do you know?

**Comment by mattam82** [comment]
I also think it should be the responsibility of the tactic to say which goals are shelved and which should stay as future_goals. I guess the implicit shelving was the most backward compatible option.

**Pull request closed without merging**
