### PR TITLE
user-overlays/README.md: Fix 404 error

### PR DESCRIPTION
**Pull request by Blaisorblade**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@Zimmi48 This is probably entirely harmless, but I don't think the readme counts as an overlay here.

**Comment by Alizter** [comment]
@Blaisorblade Thanks for the fix!

**Comment by Zimmi48** [comment]
> @Zimmi48 This is probably entirely harmless, but I don't think the readme counts as an overlay here.

Indeed, this check is really dumb for now. Another issue is when overlays are removed (this also triggers a notification). See coq/bot#114.

**Pull request merged**
