### PR TITLE
Printer.pr_evgl_sign is only called on undefined evars

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
WTF is osx talking about?
~~~
File "printing/printer.ml", line 548, characters 4-18:
548 |   | Evar_defined b -> Retyping.get_type_of env sigma b (* FIXME ? *)
          ^^^^^^^^^^^^^^
Error: This pattern matches values of type Evd.defined Evd.evar_body
       but a pattern was expected which matches values of type
         Evd.undefined Evd.evar_body
       Type Evd.defined = [ `defined ] is not compatible with type
         Evd.undefined = [ `undefined ] 
~~~
I don't see that in the code

**Comment by SkySkimmer** [comment]
oh auto merge

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
