### PR TITLE
[ci] use elpi 2.0.4

### PR DESCRIPTION
**Pull request by gares**
it reports better type checking errors

### CODE REVIEW

**Comment by gares** [comment]
@coqbot run full ci

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
trakt has some issue

**Comment by gares** [comment]
I can't reproduce it locally. I don't know how, but it insists in picking an old version of trakt. I rebased to see if CI finds his senses again.

**Comment by gares** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Note that our CI uses trakt `coq-master` not `master`

**Comment by gares** [comment]
I'm using Makefile.ci, it cannot be that

**Comment by CohenCyril** [comment]
@Tragicus this is the exact same error you have on your pr #19833

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/blob/beb35a7a0d0d63045150b09b0abf0ae92d476317/dev/ci/ci-basic-overlay.sh#L549 says coq-master

**Comment by SkySkimmer** [comment]
@coqbot  merge now

**Pull request merged**
