### PR TITLE
Take "simpl never" into account for "simpl" in position of argument of a "match", "fix" or projection

### PR DESCRIPTION
**Pull request by herbelin**
This PR ensures that `simpl never` strongly forbids the reduction of terms in position of argument of `match`, `fix` or a projection for `simpl`, as e.g. in:
```coq
Record T := {p:nat}.
Definition a := {|p:=0|}.
Arguments p : simpl nomatch.
Arguments a : simpl never.
Eval simpl in a.(p). 
(* Before: 0 ; After a.(p) *)
```

Depends on #18576 (merged), #18577 (merged), #18579 (merged), #18580.

Note a positive impact of the PR also on `hnf` but I don't understand well the reason.

- [x] Added / updated **test-suite**.
- [ ] Added **changelog**.

### CODE REVIEW

**Comment by herbelin** [comment]
Relatively a lot of incompatibilities. Don't know what to do.

**Comment by gares** [comment]
Note that simpl never (misnamed, my bad) is supposed to reduce in the context of a match.
No reduction at all should be obtained with Opaque.
I think it is documented as such.

**Comment by herbelin** [comment]
If the intent is to ignore `simpl never` in the argument of a match/fix/proj and to only care about `Opaque`, I'm ok with it. What I currently found in the documentation of Arguments is only: *"simpl never" indicates that a constant should never be unfolded by cbn or simpl*.

**Comment by gares** [comment]
The point is that `simpl` does not unfold it, but when it sees a `match t with ... end` it does call `whd` on `t` (not simpl).
It is not `simpl` that unfolds it...

The doc should be clarified.

**Comment by herbelin** [comment]
OK, if this is the (in)formal consensus, I'll replace the PR with a change of the doc (or maybe you want to do it?).

The code is rather subtle actually. It carries two transparency states (the one from env, used in whd_construct and the one updated with "never", used in red_elim_const) + does direct calls to ReductionBehavior and it is probably worth to document the code as well.

**Comment by herbelin** [comment]
An extra question: if `simpl` is right, then it is `cbn` which should be changed and which should drop the `simpl never` flag in position of argument of a `match`/`fix`/projection?

**Comment by herbelin** [comment]
> The point is that `simpl` does not unfold it, but when it sees a `match t with ... end` it does call `whd` on `t` (not simpl). It is not `simpl` that unfolds it...

Are you sure? If I'm correct, it is in `whd_construct` which recursively calls `whd_simpl_stack` except that `whd_construct` manages constant sequences of unfoldings itself with `match_eval_ref` which uses only opacity (and not "never simpl").

> The doc should be clarified.

I propose this:
```
`simpl never` indicates that a :term:`constant` should not be unfolded by :tacn:`cbn` or
:tacn:`simpl` when in head position of a reduction. However, the
modifier does not apply in position of the main argument of a `match`, `fix`,
primitive projection, or of an unfoldable constant hiding a `match`,
`fix` or primitive projection.
 
 .. example::
 
    .. coqtop:: all
 
       Arguments Nat.sub n m : simpl never.
 
  After that command an expression like :g:`(Nat.sub (S x) y)` is left
  untouched by the tactics :tacn:`cbn` and :tacn:`simpl`.

  On the other side, an expression like :g:`(Nat.sub (S x) 0) + 1`
  reduces to :g:`S (x + 1)` (via first :g:`S x + 1`) because `Nat.sub`
  is this time in position of main argument of `+`.
```
WDYT?

**Comment by gares** [comment]
Much better!

**Comment by silene** [comment]
It is still a bit misleading, as the modifier is also honored in those positions. The case where it is ignored is if the simplified term would further trigger a reduction in those positions. Consider the following function:
```coq
Definition foo x y := match x with S _ => y | O => x end.
Arguments foo x y : simpl never.
```
Then, `foo (S x) y + 1`  is not simplified to `y + 1`, but `foo (S x) (S y) + 1` is simplified to `S (y + 1)`.

So, the word `reduction` should be removed from the first sentence and moved into the second one, somehow.

**Comment by herbelin** [comment]
Also, I quickly look at `cbn` and I failed to easily deactivate `simpl never` in position of argument of a destructor. Unless someone is willing to do the change, I would by default document the current status, that is, taking `cbn` out of the sentence above and say instead:
```
The modifier `simpl never` also applies to `cbn`  to indicate this time that a :term:`constant`
should never be unfolded.
```

**Comment by gares** [comment]
The way I explain it is that `simpl` traverses the term, and for each named constant has to make a decision.
In both cases `simpl` does decides to not unfold `foo`, but when it comes to `plus` it calls another procedure to see if the match can fire, and that procedure only honors `Opaque`.

Another way to put it is that the fact that `foo` is never simplified does not impact if `plus` is. The user never said `plus` is simpl never. If one simpl never all constants in the goal (and there are no other explicit iotas around) then simpl should do nothing.

Dunno if this can help clarifying the text.

**Comment by herbelin** [comment]
Replaced with a documentation of the current situation in #18602.

**Comment by herbelin** [comment]
Reopening as a [demand](https://coq.zulipchat.com/#narrow/stream/237658-MetaCoq/topic/Cbn.20vs.20simpl.20in.20MetaCoq/near/419224753) has been made on Zulip for a variant of simpl that respects simpl never.

But then, we would need a specific syntax for it, `simpl+`, `strict simpl`, ...

**Pull request closed without merging**
