### PR TITLE
guard against timelog2html failure

### PR DESCRIPTION
**Pull request by SkySkimmer**
Example failure: https://gitlab.com/coq/coq/-/jobs/1301186577

### CODE REVIEW

**Comment by SkySkimmer** [comment]
testing at https://gitlab.com/coq/coq/-/jobs/1303567423

**Comment by ppedrot** [comment]
@SkySkimmer the test looks successful, doesn't it?

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
The test shows I didn't break the bench, we didn't get the random failure so we can't tell how well that will behave.

**Comment by ppedrot** [comment]
> The test shows I didn't break the bench

This looks enough to me, let's merge and if we ever see the weird failure again we will try something else.

**Comment by ppedrot** [comment]
On an unrelated note, it'd be good to fix the failing packages on the bench.

**Pull request merged**
