### PR TITLE
[experiment, micro-optim] Inlining critical functions in Logic_monad.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1595971698

**Comment by JasonGross** [comment]
Looks like this breaks an invariant of the Ltac profiler:
Error:
Anomaly
"Ltac Profiler encountered an invalid stack (wrong self node) likely due to backtracking into multi-success tactics."
Please report at http://coq.inria.fr/bugs/.

**Comment by ejgallego** [comment]
I'm not sure doing the job of flambda manually is gonna be a good strategy. Is the bench using flambda by the way?

**Comment by ppedrot** [comment]
As the tag implies, this is just an experiment. I agree we shouldn't make the job of flambda, but flambda is not a silver bullet either. I wanted to get a specific timing for this single change. Anyways, closing.

**Pull request closed without merging**
