### PR TITLE
CI: configure dune to limit concurrency by default

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
This is indeed something that has been on my mind for a while. I wonder tho if we couldn't rely on the auto-detection of `dune` working properly, so runners would export the number of processors CI jobs would use?

This way we would get `(jobs 4)` in large runners for example.

**Comment by SkySkimmer** [comment]
No, our runners expose all the processors of the machine even though there are multiple runners on 1 machine

**Comment by ejgallego** [comment]
> No, our runners expose all the processors of the machine even though there are multiple runners on 1 machine

What I mean is that maybe we should have the runners expose some sort of variable instead of a fixed `2` number?

`dune` will call `nproc` on Unix to determine the number of processors (on Win it uses the `NUMBER_OF_PROCESSORS` env var) , so `ulimit -n $NJOBS` for example should work too.

We can have the docker mount routine read an env var an generate the `dune/config` file too if we don't like `ulimit`, I dunno, but IMHO it'd be good to have some sort of env var that states the number of real available processors for the job.

**Review by Zimmi48 — APPROVED** [review]
Maybe this could be done better (by adapting itself to the runner), but it seems to me that this is a step in the right direction (enforcing that a runner shall not use more than 2 CPUs).

**Comment by silene** [comment]
> `dune` will call `nproc` on Unix to determine the number of processors, so `ulimit -n $NJOBS` for example should work too.

As far as I know, `ulimit` cannot limit the number of cores used by a process (and certainly not `ulimit -n`). The only way I know to influence `nproc` is to change the CPU affinity, but then you have to explicitly tell which cores the process is meant to use:
```
$ taskset -c 5,12-14,17 nproc
5
```

So, there is no way to make such a decision from inside the container. It has to come from the outside world (e.g., option `--cpuset-cpus` of `docker run`).

**Comment by ejgallego** [comment]
Indeed @silene thanks, you are correct, I don't know where I googled about this, but it was incorrect. `nproc` uses `sched_getaffinity` to compute its number, so it needs a different setup method, usually cpusets.

That being said, maybe still worth exploring to see if the runners could take the `cpuset` parameters and we could keep some auto-detection on.

For example, when we did our experiments on Inria gitlab, it was nice to get `-j 4` for our builds automatically. Also github actions are using more and more runners with 4 cpus it seems.

**Comment by Zimmi48** [comment]
In the meantime, let's merge this PR, no?
@SkySkimmer Now it needs a rebase though.

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
