### PR TITLE
Make the micromega extraction check a regular output test.

### PR DESCRIPTION
**Pull request by SkySkimmer**
As we can see in #6212 micromega's extraction is a valuable test, but when it breaks it stops the stdlib/test suite/CI from executing.

This allows us to continue checking it without breaking the build when it doesn't.

It also makes sense semantically to put tests in the test suite.

I chose to put only the `Recursive Extraction` command in the test suite, keeping the directives in the stdlib in case someone is doing `Require Import MExtraction` for them, but maybe that's not necessary.

### CODE REVIEW

**Comment by Zimmi48** [comment]
So is this refinement of #6161?

**Comment by SkySkimmer** [comment]
>So is this refinement of #6161?

You can see it that way.

**Comment by SkySkimmer** [comment]
NB: I was too clever for my own good and ended up incompatible with OSX.

**Comment by SkySkimmer** [comment]
(fixed now)

**Review by ejgallego — APPROVED** [review]
Great idea.

**Comment by Zimmi48** [comment]
Did I correctly understand that people want this backported because of this Alpine issue?

**Comment by ejgallego** [comment]
That would solve the trivial problem with diff, note however that the backport may not be risk-free, I am unsure how stable is 8.7 wrt file.

**Comment by ejgallego** [comment]
Personally, I would not backport any Alpine-linux related fix, and let the OPAM packagers take care of that as it is the only use case where Alpine matters.

**Comment by Zimmi48** [comment]
OK, although I don't think the backport would be risky because any issue would be found by tests.

**Pull request merged**
