### PR TITLE
Faster heuristic for elimination principle computation.

### PR DESCRIPTION
**Pull request by ppedrot**
Instead of generating the induction principle just to drop it immediately, we return the trivial amount of data that is needed from this principle. That is, just the inductive type itself and the number of parameters.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by ppedrot** [comment]
@coqbot bench

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
