### PR TITLE
[sysinit] fix oversight

### PR DESCRIPTION
**Pull request by gares**
CC @maximedenes

### CODE REVIEW

**Comment by gares** [comment]
@ejgallego can you take care of this one?

**Comment by ejgallego** [comment]
Umm, not sure if the CI failure is spurious or not? @gares , can you rebase or have a look?

**Comment by gares** [comment]
done

**Comment by gares** [comment]
failure equations is unrelated, it fails in other pipelines as well

**Comment by ejgallego** [comment]
> failure equations is unrelated, it fails in other pipelines as well

Async is consistently failing tho.

**Comment by ejgallego** [comment]
Umm, there is still a bug in the arguments passed if we need to disable async, right?

**Comment by gares** [comment]
I don't know if it's a bug or not, we systematically drop warnings when we craft the command line options for the workers:
https://github.com/coq/coq/blob/3e7015736b8c5e85d01361b16e6033059e11d191/stm/asyncTaskQueue.ml#L121

So the test in question (with async on) is hitting that line of code (it used to bypass it because of the bug this PR fixes, I guess).
We can change the spec, but this seems another story.

**Comment by ejgallego** [comment]
> We can change the spec, but this seems another story.

I agree, let's open a bug about warnings being dropped by workers, this seems not right.

**Review by ejgallego — APPROVED** [review]
LGTM, @gares , this seems like a critical bug for 8.14, right?

**Comment by gares** [comment]
I would not say so, the fact that the piece of code was not called in the workers is minor because anyway the (initial) state is sent by master. Indeed the async job found a discrepancy only about a warning being set also in the worker.

It was making the code impossible to understand, and @maximedenes was hit by this twice, so I decided to fix it.

**Comment by ejgallego** [comment]
Ok, if the Stm doesn't need the new_doc call in the workers then that's fine.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
