### PR TITLE
[camlpX] Remove camlp4 compat layer.

### PR DESCRIPTION
**Pull request by ejgallego**
We remove the camlp4 compatibility layer, and try to clean up most structures. `parsing/compat` is gone.

We added some documentation to the lexer/parser interfaces that are often obscured by module includes.

### CODE REVIEW

**Comment by gares** [comment]
On the plane I did the same removal.
Patches are not 100% identical, so I attach it for reference.
   https://github.com/gares/coq/commit/3b2b55c4571338de03b5dfa15343f8f69fe31c4c

**Comment by gares** [comment]
In particular I moved some duplicate code to q_util while you did much more refactoring here and there.

**Comment by ejgallego** [comment]
Cool I'll have a look. IIRC I only duplicated one function.

**Comment by ejgallego** [comment]
Ok, @gares I have incorporated a few changes from your tree that I hadn't done. Other than, it seems to me that the main difference now is that I did away with the compat file and indeed placed the proper signatures in the lexing/parsing `.mli` and removed the non needed functorialization.

IMVHO this seems ready to go.

**Comment by ejgallego** [comment]
Builld with overlay at https://travis-ci.org/ejgallego/coq/builds/209142495

**Review by ppedrot — APPROVED** [review]

**Comment by ejgallego** [comment]
Remember to merge the ssr PR too

**Pull request merged**
