### PR TITLE
[coqdep] Remove unhandled Add LoadPath Code

### PR DESCRIPTION
**Pull request by ejgallego**
The command is scheduled to be removed from the vernacular anyways.

### CODE REVIEW

**Comment by Alizter** [comment]
What are the other issues PRs coordinating the removal?

**Comment by ejgallego** [comment]
Off the top of my head https://github.com/coq/coq/issues/15062 and https://github.com/coq/coq/pull/15652

**Comment by ejgallego** [comment]
Note that this code was "dead" so IMHO not a big deal on this removal, but indeed another choice would be to fix coqdep to handle this, but I guess we agree that we better remove these commands and let the build systems take care of path handling.

**Comment by ejgallego** [comment]
Note that indeed, as discussed in jsCoq, we want to improve loadpath API so build systems / document managers can interact better with Coq, for example, it makes sense for the build system to incercept `Require` calls. jsCoq already does that (and will load libraries on-demands), but it is using a hack.

**Comment by Alizter** [comment]
Hopefully Coq can do that natively using the Dune Action Plugin soon.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
Merging soon

**Comment by gares** [comment]
Hum, I've mixed feelings about this, since the AST is still part of Coq. IMO Coq (or coqdep) should warn that the directive is being removed. This PR removes no-op code, so it is fine per se. But, do we already have that warning or note in the refman? If not, it should add it.

**Comment by ejgallego** [comment]
@gares the directive has been deprecated since a while, as noted in the PR.

**Comment by gares** [comment]
I don't see it being deprecated here https://coq.inria.fr/refman/proof-engine/vernacular-commands.html?highlight=add%20loadpath#coq:cmd.Add-LoadPath

**Comment by gares** [comment]
Oh I see, it is on 8.16. Fine then.

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
