### PR TITLE
Remove deprecated command line arguments

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
See commit messages for deprecation details.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@SkySkimmer this LGTM, but needs a changelog entry

**Comment by ejgallego** [comment]
Looks fine, tho we need to be careful about users of `-inputstate` , last time we tried to remove it it turned out some people were still using it and was hard to replace for them.

The deprecation is there to warn that indeed, side-loading the raw state is not tested and can be potentially dangerous, but as of today it more or less work.

**Comment by Zimmi48** [comment]
> Looks fine, tho we need to be careful about users of `-inputstate` , last time we tried to remove it it turned out some people were still using it and was hard to replace for them.

This was also my recollection but I couldn't find the corresponding PR to provide a reference.

**Comment by ppedrot** [comment]
There is #1145.

**Comment by gares** [comment]
From a cpdt snapshot from 2/2/2020
```
gares@ollypat:/tmp/cpdt$ rgrep -- inputstate .
gares@ollypat:/tmp/cpdt$ 
```
So, I guess is does not "depend" on it.

**Comment by ejgallego** [comment]
Use case was more like people saving extremly long proof sessions and resuming them (cc @JasonGross ) 

Given that removing the option doesn't really allow for any code improvement in Coq itself we kept it.

**Comment by gares** [comment]
Even that use case.. 
Today virtualbox can snapshot/restore a VM in a *reliable* way in seconds. And I'm sure other virtualization solutions can do the same. Not to talk about suspension to ram that is not a dream, even on linux: you close the lid and open it again tomorrow.

Even if the gain in LOC is trivial, I believe there is no use for this "fingers crossed" feature (which has better alternatives, BTW).

**Comment by SkySkimmer** [comment]
There's still the command so this mostly simplifies command line interpretation imo

**Comment by ppedrot** [comment]
> Even if the gain in LOC is trivial
Last time I had a look at it this feature was relying on very dubious code paths, so even if that's a small set of LOC it's a fairly critical one.

**Comment by JasonGross** [comment]
I don't think I've ever actually used inputstate.  It would be nice to be able to run coqc processes in a depth-first way, where, say, I give each of a couple hundred v files 1 minute each, then 10 minutes each, then an hour each, where I don't have to restart from scratch on timeout (and I don't have enough disk space for a couple hundred vms, but probably do have enough space for a couple hundred coqc process states).  But this requires being able to pause coc in the middle of, e.g., vm_compute, which I don't think inputstate can do.  In any case, I do not object to it's removal.

**Comment by achlipala** [comment]
FWIW, I don't recognize any of the arguments mentioned in commit messages, so it's not clear there's any CPDT problem.  If there was some past discussion to the contrary, I could use a pointer to it.

**Comment by gares** [comment]
This PR only remove command line parsing, so it is a green flag to me.

The comments seems to suggest the feature itself has no users and can be remove (in another PR).

@coqbot merge now

**Pull request merged**
