### PR TITLE
Fix "inconsistent assumptions" error message

### LINKED ISSUE #17973: Compiled library ... makes inconsistent assumptions over library ... is both inaccurate and less helpful than it used to be
```
File "./src/Float/Primitive_ops.v", line 17, characters 0-21:
Error:
Compiled library Interval.Real.Xreal (in file /home/jgross/.local64/coq/coq-master/lib/coq/user-contrib/mathcomp/ssreflect/eqtype.vo) makes inconsistent assumptions over library mathcomp.ssreflect.eqtype
File "./src/Poly/Datatypes.v", line 28, characters 0-22:
Error:
Compiled library Interval.Missing.Stdlib (in file /home/jgross/.local64/coq/coq-master/lib/coq/user-contrib/mathcomp/ssreflect/eqtype.vo) makes inconsistent assumptions over library mathcomp.ssreflect.eqtype
```
The logic in https://github.com/coq/coq/blob/854d46bdb7699dc08410690d80ffdf107ce641d6/vernac/library.ml#L303-L310 seems straightforwardly wrong, and I think maybe
https://github.com/coq/coq/blob/854d46bdb7699dc08410690d80ffdf107ce641d6/vernac/library.ml#L305
should use `caller` not `dir`.  I don't understand @ejgallego 's refactoring at a22ae6e27c01b868450f3a43e997dd78884adbdc, but that seems plausibly the regression?

### PR DESCRIPTION
**Pull request by JasonGross**
Fixes #17973

- [ ] Added / updated **test-suite**. (not sure how)
- [] ~Added **changelog**.~
- [] ~Added / updated **documentation**.~

N.B. I haven't tested this

Btw, @ejgallego did you deliberately do the refactoring of a22ae6e27c01b868450f3a43e997dd78884adbdc in vernac/library.ml but not topbin/coqnative_bin.ml?  They seem to have very similar intern_library logic.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Looks definitely legit.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
> @coqbot run full ci


Are you expecting anything here?  The code path shouldn't even be triggered on CI, iiuc

**Comment by ppedrot** [comment]
It doesn't hurt to run a CI, even if effectively this path is probably dead code there.

**Comment by JasonGross** [comment]
Hmm, does asking coqbot to run the CI twice result in a cancelled pipeline @coq/coqbot-maintainers ?

**Comment by JasonGross** [comment]
@ppedrot I think this is ready for merge?

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
