### PR TITLE
[doc] Remove unused dependencies.

### PR DESCRIPTION
**Pull request by ejgallego**
AFAICS `imagemagick` `hacha` and `transfig` are not used anymore.

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
Approving if CI goes through.

**Comment by ejgallego** [comment]
Gitlab has finished before the others have even started :octocat: [and that's without the most optimized caching that I hope comes soon]

**Review by SkySkimmer — APPROVED** [review]

**Comment by Zimmi48** [comment]
Merging without waiting for @letouzey review given that the changes in the Makefile are pretty trivial (and CI passed).

**Comment by ejgallego** [comment]
Merci!

**Pull request merged**
