### PR TITLE
[plugins] (re)-export AST witnesses.

### PR DESCRIPTION
**Pull request by ejgallego**
Fix downfall of #17293 :/

cc: https://github.com/ejgallego/coq-serapi/issues/371

### CODE REVIEW

**Comment by ejgallego** [comment]
Pushed a few more fixes.

It is very annoying that I had to take care of this despite the warning.

**Comment by toku-sa-n** [comment]
Thank you for the fix for https://github.com/ejgallego/coq-serapi/issues/371. I feel exposing only three values in `g_extraction.mli` isn't enough, although I still can't get what's in `g_extraction.mlg` because I don't know how to read the file. Are you going to add more later, or is it actually enough?

**Comment by ejgallego** [comment]
> Thank you for the fix for [ejgallego/coq-serapi#371](https://github.com/ejgallego/coq-serapi/issues/371). I feel exposing only three values in `g_extraction.mli` isn't enough, although I still can't get what's in `g_extraction.mlg` because I don't know how to read the file. Are you going to add more later, or is it actually enough?

Thank you for having a look @toku-sa-n ; I think the fix should be enough, what `serlib` needs to know is about the new generic argument types, so it can extract the corresponding type for each tag.

Do you have some test cases for extraction that we could add to `serlib`'s test-suite?

**Comment by ejgallego** [comment]
@coqbot run full CI

**Comment by toku-sa-n** [comment]
@ejgallego Thank you for the reply. I tried most of the commands in https://coq.inria.fr/refman/addendum/extraction.html on serlib, and it turned out that actually those three definitions were enough.

For the test case, how about this?

```coq
Require Coq.extraction.Extraction.

Extraction Language Haskell.

Extraction Implicit pred [1].

Axiom Y : Set -> Set -> Set.
Extract Constant Y "'a" "'b" => " 'a * 'b ".
```

The last `Axiom` and `Extract Constant` are taken from [the docs](https://coq.inria.fr/refman/addendum/extraction.html#coq:cmd.Extract-Constant).

**Comment by ejgallego** [comment]
@toku-sa-n thank you for the quick example and for the tests! It is very useful! Indeed in my experience exporting all 3 witnesses should work for our purposes.

It seems to me that the example looks like a good candidate for the test suite. Can you please submit a SerAPI PR with that example in the test suite?

I suggest you place it in `tests/genarg/extraction.v`, you need to update the `tests/genarg/dune` file too.

These tests will check that we can serialize and de-seralize the AST back, so they are very useful and will prevent from further problems in the future.

**Comment by toku-sa-n** [comment]
@ejgallego Done in https://github.com/ejgallego/coq-serapi/pull/375.

**Comment by ejgallego** [comment]
Thank you very much @toku-sa-n ; I will merge the SerAPI PR once this PR is merged on the Coq side.

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
Thanks!

**Pull request merged**
