### PR TITLE
Fix checker soundness bug with polymorphism capturing global univs

### PR DESCRIPTION
**Pull request by SkySkimmer**
Followup for #8341.

Not making a test as that's too difficult with our current infrastructure.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>The comment that precedes your change seems directly related. Should it be removed?
>A few lines later, the exact same code appears. Why is it not a mistake there too?

The comment applies to the second function. It's not a mistake because we still double-declare universes in Include and especially side effects.

>Is the exception ever caught?

Let me add it to `Checker.explain_exn`.

**Review by ppedrot — APPROVED** [review]
The checker does fancy stuff w.r.t. module inclusion and the like, and it adds global monomorphic constraints for no good reason. This should be fixed, but in the meantime the following PR makes the checker more robust. It might also reveal other bugs, so that's very good.

**Comment by ppedrot** [comment]
@SkySkimmer will you adapt the exception explanation or should I merge?

**Comment by SkySkimmer** [comment]
merge

Gaëtan Gilbert

**Pull request merged**
