### PR TITLE
Fast meta check subst defined

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
Bench: https://gitlab.com/coq/coq/-/jobs/1377490779.

**Comment by ppedrot** [comment]
```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                             │                         │                                       │                                       │                         │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-performance-tests-lite │ 1514.13  1553.77  -2.55 │  4226512930620   4334875430615  -2.50 │  6887516176041   7126784954280  -3.36 │ 2079152  2079292  -0.01 │   0    0    nan │
│                  coq-stdlib │  407.30   412.12  -1.17 │  1137564931174   1153841356623  -1.41 │  1416555398271   1474356827882  -3.92 │  590080   595872  -0.97 │   0    0    nan │
│              coq-verdi-raft │ 1095.84  1101.74  -0.54 │  3050931005311   3065313867351  -0.47 │  4275046133646   4324182120280  -1.14 │  904376   902864   0.17 │   0    0    nan │
│                  coq-geocoq │ 1323.06  1329.26  -0.47 │  3686965052779   3705269085275  -0.49 │  5395952050798   5468681077464  -1.33 │  995696   987492   0.83 │   0    0    nan │
│                    coq-corn │ 1466.91  1473.43  -0.44 │  4084008870226   4099219971551  -0.37 │  5843925213832   5897472035090  -0.91 │  812844   812608   0.03 │   0    0    nan │
│                coq-bedrock2 │  308.23   309.54  -0.42 │   854289927606    858170379579  -0.45 │  1496118531153   1503807645033  -0.51 │  798344   798360  -0.00 │   0    0    nan │
│                    coq-core │  106.59   107.01  -0.39 │   296456158053    295978986751   0.16 │   458409665436    458290834498   0.03 │  303796   303856  -0.02 │   0    0    nan │
│                 coq-unimath │ 4262.05  4272.66  -0.25 │ 11855906556301  11889328401774  -0.28 │ 22667988162572  22680431460351  -0.05 │ 3262976  3283400  -0.62 │   0    0    nan │
│ coq-rewriter-perf-SuperFast │  737.18   738.54  -0.18 │  2052702737281   2054118254992  -0.07 │  3207046126387   3213516615611  -0.20 │ 1072052  1071948   0.01 │   0    0    nan │
│                   coq-flocq │  146.40   146.41  -0.01 │   406789153854    406251932937   0.13 │   504625133216    504801640446  -0.03 │  808412   808436  -0.00 │   0    0    nan │
│       coq-mathcomp-fingroup │   48.03    48.03   0.00 │   132921522741    132798798363   0.09 │   186061287915    186142028145  -0.04 │  481680   482040  -0.07 │   0    0    nan │
│                   coq-verdi │   98.04    98.02   0.02 │   270399744210    269523196400   0.33 │   379218747226    378858375844   0.10 │  542028   544252  -0.41 │   0    0    nan │
│            coq-fiat-parsers │  583.29   583.14   0.03 │  1628227808880   1630530829915  -0.14 │  2489436628766   2496033371141  -0.26 │ 3475216  3475360  -0.00 │   0    0    nan │
│                 coq-bignums │   56.01    55.97   0.07 │   153849491955    153665121213   0.12 │   206253928177    206342745231  -0.04 │  463732   464180  -0.10 │   0    0    nan │
│               coq-fourcolor │ 2551.67  2549.61   0.08 │  7111682109424   7106968385467   0.07 │ 12238786222169  12240734575857  -0.02 │  730940   730944  -0.00 │   0    0    nan │
│             coq-fiat-crypto │ 4813.57  4807.24   0.13 │ 13372059067781  13350873366344   0.16 │ 23517547083744  23585976586714  -0.29 │ 2222268  2220468   0.08 │   0    0    nan │
│                    coq-hott │  278.89   278.48   0.15 │   766711325671    766877216035  -0.02 │  1185002920662   1187380829691  -0.20 │  570256   570044   0.04 │   0    0    nan │
│                   coq-color │  482.56   481.76   0.17 │  1347049354722   1345499166346   0.12 │  1691452991984   1699039653018  -0.45 │ 1151476  1101088   4.58 │   0    0    nan │
│       coq-mathcomp-solvable │  169.52   169.17   0.21 │   471544024480    470894649023   0.14 │   668109426988    668280977009  -0.03 │  673004   689964  -2.46 │   0    0    nan │
│               coq-perennial │ 6827.91  6811.24   0.24 │ 19019121648889  18966317558161   0.28 │ 28994795550093  29087334101876  -0.32 │ 3115688  3077232   1.25 │   0    0    nan │
│               coq-fiat-core │  108.19   107.90   0.27 │   306057762080    305618972062   0.14 │   413253650365    412447534744   0.20 │  481124   480556   0.12 │   0    0    nan │
│        coq-mathcomp-algebra │  140.79   140.40   0.28 │   391887041944    390736381704   0.29 │   510703841957    510904949443  -0.04 │  553908   553812   0.02 │   0    0    nan │
│             coq-lambda-rust │ 1262.98  1258.33   0.37 │  3514663453780   3502525470319   0.35 │  5053998172522   5063324068926  -0.18 │ 1106596  1077148   2.73 │   0    0    nan │
│      coq-mathcomp-character │  150.18   149.62   0.37 │   417059026273    416057759938   0.24 │   584784965084    584862266765  -0.01 │  730896   730816   0.01 │   0    0    nan │
│      coq-mathcomp-odd-order │ 1058.04  1053.25   0.45 │  2947343026331   2931037629069   0.56 │  4662949865538   4665027120230  -0.04 │  939588   939616  -0.00 │   0    0    nan │
│          coq-mathcomp-field │  222.13   221.04   0.49 │   618410521189    615517274572   0.47 │   939799464609    940304361602  -0.05 │  668096   670024  -0.29 │   0    0    nan │
│            coq-math-classes │  174.61   173.53   0.62 │   487496090009    484248984875   0.67 │   642684091989    643999798255  -0.20 │  481376   481428  -0.01 │   0    0    nan │
│       coq-engine-bench-lite │  314.16   312.16   0.64 │   883752939821    878832732966   0.56 │  1641594558935   1638637831471   0.18 │ 3506320  3506180   0.00 │   0    0    nan │
│                coq-rewriter │  670.30   665.78   0.68 │  1859346919237   1847789197743   0.63 │  2841180681061   2843525237409  -0.08 │ 1072240  1071996   0.02 │   0    0    nan │
│      coq-mathcomp-ssreflect │   53.87    53.48   0.73 │   146866823286    146572169833   0.20 │   190037140643    190138679274  -0.05 │  525412   526272  -0.16 │   0    0    nan │
│                coq-coqprime │  331.78   329.19   0.79 │   920730332695    914995800559   0.63 │  1595421120073   1594853452085   0.04 │  921288   918516   0.30 │   0    0    nan │
│                 coq-coqutil │   58.88    58.14   1.27 │   162744718123    161526190071   0.75 │   214484051366    214024193929   0.21 │  600732   600740  -0.00 │   0    0    nan │
│              coq-coquelicot │   69.19    67.94   1.84 │   187520480160    185872507856   0.89 │   239898651401    238997523882   0.38 │  558280   557720   0.10 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Some per-line diffs show interesting behaviours, but I don't think that the PR is really worth it. Let's close.

**Comment by SkySkimmer** [comment]
If we never merge small speedups how are we supposed to get faster? This PR doesn't seem to make the code more complicated either.

**Comment by ppedrot** [comment]
Right, right. The main issue I have with this code is that it's unclear it's correct. But, well, the same can be said of any `Unification`-related issue.

**Pull request closed without merging**
