### PR TITLE
Move coqperf to a separate opam package

### PR DESCRIPTION
**Pull request by SkySkimmer**
This makes it optional on linux instead of forcing everyone to install kernel headers.

We could also move it to a plugin (using a hook in lib I guess) so that installing it doesn't require recompiling everything. Note that this would mean instruction counts in NewProfile would only be available after the plugin is loaded though.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
cc @rlepigre

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by rlepigre** [comment]
I'm not too keen on making this a separate package, as perf support ought to be a configure step thing at most in my opinion. I tried playing with `dune`, but since there is no `findlib` package associated to `conf-linux-libc-dev` we can't use the following trick:
```diff
diff --git a/perf/dune b/perf/dune
index 4fe5923874..8fc92b1856 100644
--- a/perf/dune
+++ b/perf/dune
@@ -4,6 +4,8 @@
  (public_name coq-core.perf)
  (wrapped false)
  (foreign_stubs (language c) (names perf))
+ (optional)
+ (libraries conf-linux-libc-dev)
  ; Just "linux" is not enough, see https://github.com/ocaml/dune/issues/4895.
  (enabled_if
   (or
```
I also tried using `(virtual_deps conf-linux-libc-dev)`, but that is not take into account by `(optional)`, since it has a different purpose.

Could we do something like:
```diff
diff --git a/perf/dune b/perf/dune
index 4fe5923874..6b0c29f2e6 100644
--- a/perf/dune
+++ b/perf/dune
@@ -6,9 +6,11 @@
  (foreign_stubs (language c) (names perf))
  ; Just "linux" is not enough, see https://github.com/ocaml/dune/issues/4895.
  (enabled_if
-  (or
-   (= %{system} "linux")
-   (= %{system} "linux_eabi")
-   (= %{system} "linux_eabihf")
-   (= %{system} "linux_elf")
-   (= %{system} "elf"))))
+  (and
+   PERF_SUPPORT
+   (or
+    (= %{system} "linux")
+    (= %{system} "linux_eabi")
+    (= %{system} "linux_eabihf")
+    (= %{system} "linux_elf")
+    (= %{system} "elf")))))
```
and use `sed` to change `PERF_SUPPORT` into `true` or `false`? Or generate the `dune` file?

**Comment by ejgallego** [comment]
I think `select` may work for this, or else just generate a .ml file with a noop interface?

**Comment by ejgallego** [comment]
Yeah I think that a package is a bit too heavy for this, also depopts are tricky in opam.

IMHO we can just have a script generate the file, as is done in the select stuff.

We have a few cases of this pattern already in the codebase, so maybe time to make a general util for this kind of conditional options.

Using some form of preprocessor would also work if we feel like it, but adds a dependency (or we can use `cpp`)

**Comment by rlepigre** [comment]
(Oups, I just noticed on Zulip that I set a milestone here, that was not intentional.)

**Comment by SkySkimmer** [comment]
Not sure how using a script would work TBH

**Comment by ejgallego** [comment]
> Not sure how using a script would work TBH

I was assuming we put the perf support under a configure option.

The script would check the configure value and generate the corresponding .ml file. So:
- configure checks the headers are installed (or user flag)
- script checks Coq_config and links the right file. We actually have a few cases like this in the codebase, so we could share the code.

**Comment by SkySkimmer** [comment]
>configure checks the headers are installed

How does that work for the automatic invocation by dune? Wouldn't we have to say it depends on `universe`?

**Comment by ejgallego** [comment]
> How does that work for the automatic invocation by dune? Wouldn't we have to say it depends on `universe`?

That's an option, however it seems like a PITA to re-run configure on every command, or we could also require users to re-run configure manually if they want to re-detect stuff.

But indeed, this kind of usability problems are a big deal with "optional deps" on things that are not tracked by the build system, once you want to have reproducible / cacheable rules.

We may have the same problem with other stuff in configure actually, in the sense that Dune may not re-run configure.

Indeed, it is not clear to me for example how the setup with a package, as is done here, works, in the sense that the same problem w.r.t. global stuff.

I'm unsure what is best here, maybe we should discuss in Zulip / call ?

**Pull request closed without merging**
