### PR TITLE
Remove probably useless doc/sphinx/coqdoc.css.

### LINKED ISSUE #8404: [doc] multiple coqdoc.css in the source tree
```shell
$ find . -name coqdoc.css | xargs md5sum
1a2707d6ae8e074cce4442c496552d50  ./tools/coqdoc/coqdoc.css
1ea9c912f98d7b5094f3f3232ead4b06  ./doc/common/styles/html/coqremote/sites/all/themes/coq/coqdoc.css
b975f72cc3bfebd7de424decd20014ba  ./doc/sphinx/coqdoc.css
2e5e585faaf1f01c4f1704e9a63b1ebc  ./doc/sphinx/_static/coqdoc.css
```

IIRC I'm the one that added the coqremote, since we don't use the regular coqdoc.css on the website (why?). The two about Sphinx.. I've no clue @maximedenes 

Bottom line, I'd like to tweak the css to make the doc of plugins/ssr/*.v look decent.

### PR DESCRIPTION
**Pull request by Zimmi48**
@maximedenes Do you know why it was added initally? (Cf. 4aaf28cc905bebf757b02ad911a6eed78714cac7). @cpitclaudel says it was not part of his prototype.

Note that the important stylesheet is `doc/sphinx/_static/coqdoc.css` which was also introduced in the same commit.

### CODE REVIEW

**Comment by ejgallego** [comment]
Needs rebase to pass the CI.

**Comment by ejgallego** [comment]
Note that the file you are removing is a duplicate of the one in `common/styles/html/coqremote/sites` which I ignore what it does.

**Comment by Zimmi48** [comment]
> Note that the file you are removing is a duplicate of the one in `common/styles/html/coqremote/sites` which I ignore what it does.

Good point. This was added by @gares for a `serve-refman-8080` target but isn't needed anymore either since the Sphinx migration.

**Comment by herbelin** [comment]
I saw your message at #8404. Do you need an assignee for this PR?

**Comment by Zimmi48** [comment]
Yes, thanks!

**Comment by herbelin** [comment]
OK, will merge tomorrow.

**Comment by Zimmi48** [comment]
Don't forget that now, we have enforced the "requested reviews" even for administrators, which means that you have to "approve" using the GItHub feature before you can merge.

**Review by herbelin — APPROVED** [review]
The reference file for coqdoc is in tools. If ever improvements in the reference file are worth to be taken from the removed files, it shall be possible to reconstruct them afterwards. At the moment, the reasons for different variants have been lost.

**Pull request merged**
