### PR TITLE
Don't use Prop lbound for definitional classes

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure what the practical consequences are but Prop lbound is more intended for inductives.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Definitely makes sense to me, given that this bound business is only here to support (the quirky parts of) template polymorphism.

**Comment by ppedrot** [comment]
@SkySkimmer if you're happy with the current code I can merge right away.

**Comment by SkySkimmer** [comment]
merge on

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
