### PR TITLE
Add an index for attributes.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** documentation

Even if this index is not very big yet, I think it is still useful to provide it. Especially now that (after #11601) this is not going to pollute the main TOC.

@cpitclaudel Ideally, I would have wished to put the file in the new file tree, i.e. as `attributes.rst` under `appendix/indexes/` but given the magic behind the generation of indexes, I am not sure how this could be done.

Still on the topic of indexes, @jfehrle mentioned that it would be good to have a "topic index" and since we are currently improving a lot the documentation of grammars, I think it would be great to have an index of nonterminals (I don't know how to create any of these). Finally, I am not personally very convinced by the interest of the general index. WDYT?

### CODE REVIEW

**Comment by jfehrle** [comment]
I have no objection to adding an index for attributes or an index of nonterminals though I don't expect I would use those.  I don't use the general index (the one under "Index" in the TOC, right), but it's harmless to keep for the time being.  I would like a distinct topical index (perhaps including glossary items) in the future.

**Comment by Zimmi48** [comment]
The index for nonterminal could become useful once the documented nonterminal are made closer to the ones actually used in the parser to better understand parsing errors.

**Comment by jfehrle** [comment]
Good point, although improving the error messages looks like it would be a bit of a project.  I think we'd want to get rid of the prefixes as in `vernac:gallina`.

Nor is this too informative:

```
Definition foo := WRONG fix foo (n : nat) { wf n n } := 0.

Syntax error: '.' expected after [vernac:gallina] (in [vernac_aux]).
```

Then there is `Print Grammar <symbol>` and various other uses of nonterminal names to consider.

**Comment by Zimmi48** [comment]
@cpitclaudel Would you mind having a look?

**Review by cpitclaudel — APPROVED** [review]
This looks good.  I think domain indices in Sphinx are forced to be called "{domain}-{name}.html", so "coq-attrindex" in this case.  Changing this to allow a custom path or even embedding the index anywhere in a page would be worth a feature request, I think.  Alternatively, we could overwrite `write_domain_indices` in the html builder.

**Comment by Zimmi48** [comment]
> This looks good. I think domain indices in Sphinx are forced to be called "{domain}-{name}.html", so "coq-attrindex" in this case. Changing this to allow a custom path or even embedding the index anywhere in a page would be worth a feature request, I think. Alternatively, we could overwrite `write_domain_indices` in the html builder.

OK thanks for the feedback. This is too much about my grade in Sphinx, so if you want to open a feature request, I'll let you do it. But this is also acceptable that all the indexes are at the root.

**Pull request merged**
