### PR TITLE
[coq] Untabify the whole ML codebase.

### PR DESCRIPTION
**Pull request by ejgallego**
I think we still are seeing too much noise due to tabs in files; IMHO the time has come to get rid of the problem for once and for all.

My diff setup does ignore tab to space changes, so this is not so noisy [see manual for `git diff`]

### CODE REVIEW

**Review by herbelin — APPROVED** [review]

**Comment by JasonGross** [comment]
While you're at it, do you want to remove all trailing spaces?

**Comment by SkySkimmer** [comment]
Seems like this would be annoying for backporters if it gets merged just after the branch.

**Comment by Zimmi48** [comment]
> While you're at it, do you want to remove all trailing spaces?

Seems reasonable: if we do remove tabs in one big commit, we should fix all whitespace issues at once.

@ejgallego I'd be interested if you could apply exactly the same script as @SkySkimmer in #6225: I want to know how much the number of lines to fix has been reduced in the last two years.

**Comment by Zimmi48** [comment]
> Seems like this would be annoying for backporters if it gets merged just after the branch.

We could untabify at once master, v8.11, and v8.10.

**Comment by ejgallego** [comment]
> While you're at it, do you want to remove all trailing spaces?

I'd be OK removing the trailing whitespaces, on the other hand I am not sure it is useful if their checking is disabled on the pre-commit script.

**Comment by Zimmi48** [comment]
> their checking is disabled on the pre-commit script

That's not the case. What made you think that?

**Comment by ejgallego** [comment]
> That's not the case. What made you think that?

Indeed, I got confused sorry.

**Comment by ejgallego** [comment]
I'll rebase this PR as soon as it gets an assignee.

**Comment by herbelin** [comment]
I can be the assignee but should I then consider that who did not speak consent?

As far as I'm concerned, I approved, but in practice, I feel neutral as there will be both advantages and inconveniences.

> We could untabify at once master, v8.11, and v8.10.

Looks good.

**Comment by Zimmi48** [comment]
> I can be the assignee but should I then consider that who did not speak consent?

Being an assignee does not mean approving the PR. All PRs should ideally get an assignee within days of being opened, and the assignee should ensure that a decision is taken in the end. You could decide to leave an additional week for everyone to express their opinion, this could be a topic for the Coq Call, etc.

**Comment by gares** [comment]
we decided to do it now but also remove trailing spaces

**Comment by herbelin** [comment]
Since this seems to have been relatively consensual, maybe someone more involved in this kind of issue than me would like to assign? @SkySkimmer maybe?

**Comment by SkySkimmer** [comment]
IIRC this is milestone 8.11
@ejgallego ping me when you've rebased (remember to remove trailing spaces, maybe just run the script in https://github.com/coq/coq/pull/6225)

**Comment by ejgallego** [comment]
I'll take care of this ASAP.

**Comment by Zimmi48** [comment]
Given that we have three active branches, this PR can either be in milestone 8.10.2 (backport to v8.10 and v8.11) or be in milestone 8.12+beta1 and two specific PRs be opened on v8.10 and v8.11. First option could work, but second option is more straightforward.

**Comment by ejgallego** [comment]
Note that backporting is not very useful IMO, I think it is better to just run the script on each branch.

**Comment by Zimmi48** [comment]
> Note that backporting is not very useful IMO, I think it is better to just run the script on each branch.

Agreed. So let's put the 8.12+beta1 milestone on this one.

**Comment by ejgallego** [comment]
Ok, new version pushed.

I've used this script:
```bash
for i in `find . -name '*.ml' -or -name '*.mli' -or -name '*.mlg'`; do expand -i "$i" | sponge "$i"; sed -e's/[[:space:]]*$//' -i.bak "$i"; done
```
I guess we could run this on more files, but I am happy with ML files for now.

**Review by SkySkimmer — APPROVED** [review]
No point waiting for ~conflicts~full CI, let's merge.

**Comment by ppedrot** [comment]
@ejgallego Am I supposed to apply this script directly to the 8.11 branch then?

**Comment by ejgallego** [comment]
Merci @SkySkimmer ; @ppedrot yes, just run it like that, remove the `.bak` files, do a `git diff --ignore-whitespace` for sanity and push.

**Comment by Zimmi48** [comment]
@vbgl You should do the same for v8.10 if you want to avoid merge conflicts when backporting.

**Comment by Zimmi48** [comment]
@ppedrot and @vbgl: I suggest being careful on when exactly you apply this script: you should clear the backport queue from any PR dating from before this patch *before* applying the whitespace removal, otherwise you risk conflicts when backporting those.

**Comment by ejgallego** [comment]
> otherwise you risk conflicts when backporting those

Indeed, on the other hand they could _temporarily_ tweak the backport script as to use the right `--whitespace` option in `git apply`

**Pull request merged**
