### PR TITLE
Make discriminate tactic compatible with HoTT

### PR DESCRIPTION
**Pull request by andreaslyn**
**Kind:** feature.

- [x] Added / updated test-suite

- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Review by ppedrot — CHANGES_REQUESTED** [review]
This looks wrong. Instead of making the scheme generator lazy, you should take an additional argument and dispatch on the value of the indices-matter flag when calling it to generate the scheme. This piece of code is already horrible, let's not worsen the situation.

**Comment by andreaslyn** [comment]
Lint says: `http://dl-cdn.alpinelinux.org/alpine/v3.9/main: temporary error (try again later)`

**Comment by andreaslyn** [comment]
I have removed the indices-matter check. The proper sort family for the elimination scheme can be deduced from the type of `core.eq.True` and `core.eq.False`.

**Comment by andreaslyn** [comment]
Hi @mattam82 I am working on porting the ssreflect tactics to HoTT, as you suggested. Do you have any suggestions, or shall I wait for @ppedrot?

**Review by ppedrot — APPROVED** [review]
This seems way better.

**Comment by ppedrot** [comment]
I'll wait a bit for a potential @mattam82 (or somebody else) input, and will merge after.

**Review by mattam82 — APPROVED** [review]
Looks good to me too.

**Comment by ppedrot** [comment]
@andreaslyn can you add a change entry? This is a user facing feature after all.

**Comment by gares** [comment]
@andreaslyn also fixed a few ssr tactics to work with Hott, but I did not ask a changelog entry. The point being that I believe it is a bug not to work in some situations and we don't put all bug fixed in the changelog file.

**Comment by ppedrot** [comment]
Fair enough.

**Comment by andreaslyn** [comment]
I have added a changelog entry.

**Review by Zimmi48 — APPROVED** [review]

**Comment by ppedrot** [comment]
Spurious CI failure, let's merge.

**Comment by Zimmi48** [comment]
@vbgl You have decided to backport #10302 and #10305 but you have missed this PR. This is inconsistent. I discovered this when preparing #10385.

**Comment by vbgl** [comment]
Thanks Théo. This PR has now been backported. The change-log for 8.10+β2 is thus inaccurate…

**Comment by Zimmi48** [comment]
Indeed good point @vbgl. I have opened #10392 fixing this.

**Pull request merged**
