### PR TITLE
[gc] Set GC policy as best-fit in OCaml >= 4.10.0

### LINKED ISSUE #11277: Performance suggestion: Investigate the impact of the `best-fit` allocator, new in OCaml 4.10
(This is an enhancement suggestion rather than a bug.)

OCaml 4.10 should be released within a few months. The main feature of the new release (besides breaking internals-using C code) is a new `best-fit` allocator for the OCaml major heap, who appears to do wonders on memory-constrained programs by reducing fragmentation in the major heap. Benchmarks have shown that, in some cases, enabling it (it is not currently the default) can lead to programs that are both faster and use less memory.

*If* your workload results in major-heap fragmentation, which may or may be the case of Coq proofs, we've observed 30%-or-more reductions in memory usage, some of which can be traded back into reductions of the GC time of the program. (What's a typical proportion of Gc time for a large Coq development?)
(One reason why Coq proof may *not* suffer from major-heap fragmentation is that hashconsing may result in fairly different liveness patterns from usual programs. Another is that the Coq term representation may result in few larger blocks on the heap -- except in native-compute scenarios, are there Coq terms with arrays of size above 16? It's hard to tell without an experiment.)

I'm creating this issue to encourage Coq maintainers to experiment with the `best-fit` allocator, once they have a version of Coq that is compatible with OCaml 4.10, and track the effectiveness (or not) of this experiment.

No change to the build system is required, you just have to run your OCaml program under the `OCAMLRUNPARAM="a=2"` environment setting. It may also be beneficial to increase the `space_overhead` setting of the GC (this will reduce GC time at the cost of increased memory usage; this may let you convert some of the space reduction into a time reduction), for example `OCAMLRUNPARAM="a=2,o=100"` (or `120`, etc.; this is a memory overhead in percentage of the live heap size, the default is `80`).

For slightly more details on the `best-fit` memory allocator, see the [gc.mli documentation](https://github.com/ocaml/ocaml/blob/4.10/stdlib/gc.mli), in particular the `allocation_policy` field.

### PR DESCRIPTION
**Pull request by ejgallego**
Closes #11277

### CODE REVIEW

**Comment by ejgallego** [comment]
4.07.1 vs 4.11.1 + best_fit (https://gitlab.com/coq/coq/-/jobs/741853859)
```
┌─────────────────────────────┬──────────────────────────┬──────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]       │                  CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                          │                                              │                                             │                                │                   │
│                package_name │     NEW     OLD  PDIFF   │               NEW               OLD  PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2208.20 2515.67 -12.22 % │     6159422285184     7013825265291 -12.18 % │    12479144575450    11447327440831 +9.01 % │     853156     775076 +10.07 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  619.50  646.15  -4.12 % │     1735126031141     1808696168932  -4.07 % │     2838550717211     2718308274041 +4.42 % │    3185216    2997820  +6.25 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1030.98 1062.95  -3.01 % │     2867748850504     2957929888632  -3.05 % │     4585672381839     4629792501126 -0.95 % │    1300288    1070648 +21.45 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-engine-bench-lite │  374.03  382.28  -2.16 % │     1051103034220     1075893896203  -2.30 % │     1737296645168     1836802613305 -5.42 % │    4070992    3508608 +16.03 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  598.61  610.92  -2.01 % │     1661211393708     1697511318644  -2.14 % │     2574577998925     2583861631743 -0.36 % │    1047460    1036884  +1.02 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   58.26   59.18  -1.55 % │      161580392326      164369606377  -1.70 % │      208089699381      204982955620 +1.52 % │     531876     528920  +0.56 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   80.06   81.10  -1.28 % │      219965606364      222148875778  -0.98 % │      319079856819      310407543066 +2.79 % │     782048     768480  +1.77 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 3962.45 4003.12  -1.02 % │    11024288561939    11138423121186  -1.02 % │    21051121077382    21169051946498 -0.56 % │    1214140    1113564  +9.03 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  159.30  160.55  -0.78 % │      442141054386      444858019255  -0.61 % │      555367689174      553082669644 +0.41 % │     873748     822152  +6.28 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 4919.52 4955.62  -0.73 % │    13651691890501    13765111101646  -0.82 % │    24269169435898    23635281614825 +2.68 % │    2156812    2339816  -7.82 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1252.41 1261.15  -0.69 % │     3488554192335     3509951514886  -0.61 % │     4875375109872     4897289511440 -0.45 % │     947468     934672  +1.37 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  289.33  291.03  -0.58 % │      805174394380      810577501518  -0.67 % │     1238371870909     1249551428572 -0.89 % │     873180     825976  +5.71 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  218.48  219.42  -0.43 % │      604883094095      608617199014  -0.61 % │     1001695193394     1003268567223 -0.16 % │    1149148    1087364  +5.68 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1472.14 1474.00  -0.13 % │     4102229640371     4112364285360  -0.25 % │     6236354838250     6222306192639 +0.23 % │    1231056    1147624  +7.27 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│  coq-performance-tests-lite │  545.55  546.06  -0.09 % │     1523706134075     1525018234346  -0.09 % │     2650504876062     2794681720014 -5.16 % │     756544     747360  +1.23 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   48.11   48.06  +0.10 % │      133142460404      133348436384  -0.15 % │      186097692665      183850811227 +1.22 % │     493724     486340  +1.52 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   58.32   58.11  +0.36 % │      160860843862      160627147837  +0.15 % │      219322383504      215331314434 +1.85 % │     474828     472144  +0.57 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1074.52 1068.44  +0.57 % │     2992236515501     2978079039587  +0.48 % │     4725839951155     4750344215863 -0.52 % │    1004716     994032  +1.07 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1771.62 1761.20  +0.59 % │     4934590397008     4901326716356  +0.68 % │     7611974748873     7512882355561 +1.32 % │     950988     855988 +11.10 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  160.98  159.90  +0.68 % │      447187125934      445380591886  +0.41 % │      623765722069      619098431123 +0.75 % │     790548     736704  +7.31 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1274.17 1263.20  +0.87 % │     3545991125663     3516340102274  +0.84 % │     5016270117803     4947745242286 +1.38 % │    1222968    1174820  +4.10 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  174.01  172.51  +0.87 % │      484446784090      480253546322  +0.87 % │      686104243810      677668026916 +1.24 % │     679492     691948  -1.80 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  318.06  315.05  +0.96 % │      861854398522      856708496892  +0.60 % │     1398975739207     1376024905209 +1.67 % │     579712     635964  -8.85 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  122.79  121.62  +0.96 % │      338703843788      335957978534  +0.82 % │      421118943256      413673407150 +1.80 % │     570748     574240  -0.61 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   51.17   50.66  +1.01 % │      139831170592      138430324263  +1.01 % │      182268137034      176280676935 +3.40 % │     532584     520832  +2.26 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  141.93  140.34  +1.13 % │      393248098935      390141024521  +0.80 % │      513136676800      503715278515 +1.87 % │     574280     565036  +1.64 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   70.84   69.87  +1.39 % │      194607296865      191135104045  +1.82 % │      254996589554      245303622507 +3.95 % │     599300     587168  +2.07 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  678.71  665.87  +1.93 % │     1889485385741     1856340836411  +1.79 % │     2649341650215     2555954385433 +3.65 % │    1124164    1131392  -0.64 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  193.92  190.08  +2.02 % │      540195760748      530267944670  +1.87 % │      719549432958      700334701606 +2.74 % │     498856     504748  -1.17 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  633.18  617.46  +2.55 % │     1766537049254     1724694289532  +2.43 % │     2292326187434     2190545821844 +4.65 % │    1638820    1455240 +12.62 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  110.22  105.95  +4.03 % │      312971015270      301974056873  +3.64 % │      426957676501      401523424965 +6.33 % │     484804     487364  -0.53 % │    0    0  +nan % │
├─────────────────────────────┼──────────────────────────┼──────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  566.12  542.99  +4.26 % │     1580218181016     1517998084424  +4.10 % │     2187950201891     2073653504771 +5.51 % │     597436     592388  +0.85 % │    0    0  +nan % │
└─────────────────────────────┴──────────────────────────┴──────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```

**Comment by ejgallego** [comment]
Interesting results; in particular w.r.t. max memory consumption, is the bench script even doing the right thing?

**Comment by gares** [comment]
Side note: together with Benjamin we just discovered coq-coqprime does not run the test/bench suite in examples/ when compiled. This makes sense for a final user installing coqprime, but not for the bench system, especially if you look at it as a vm_intensive job.

**Comment by gasche** [comment]
This test run uses `space_overhead=200`: it should improve throughput (and indeed it does, with a nice -7% on coquelicot) but this aggressive setting (compared to the default =80, which is known to be too low for best-fit) also has a risk of increasing memory consumption (and indeed it does with +15% in some cases; not necessarily correlated with strong performance wins).

(See [this blog post](https://blog.janestreet.com/memory-allocator-showdown/) on why one has  to tune the space-overhead numbers when moving to best-fit.)

**Comment by ejgallego** [comment]
> This test run uses `space_overhead=200`: it should improve throughput (and indeed it does, with a nice -7% on coquelicot) but this aggressive setting (compared to the default =80, which is known to be too low for best-fit) also has a risk of increasing memory consumption (and indeed it does with +15% in some cases; not necessarily correlated with strong performance wins).
> 
> (See [this blog post](https://blog.janestreet.com/memory-allocator-showdown/) on why one has to tune the space-overhead numbers when moving to best-fit.)

Thanks @gasche , indeed we discussed the JS on Zulip, for now we use 200 as we would like to offset the performance loss in 4.08, likely the optimal value is lower.

**Comment by SkySkimmer** [comment]
I set to draft, undraft when you remove the bench commit.

**Comment by gares** [comment]
@ejgallego you did put 8.13+beta1 milestone on draft that needs a rebase, was it intended?

**Comment by ejgallego** [comment]
> @ejgallego you did put 8.13+beta1 milestone on draft that needs a rebase, was it intended?

Yes sorry, I just didn't manage to update it; will do now. IMHO this is small enough as to try in 8.13.

**Comment by ejgallego** [comment]
> Yes sorry, I just didn't manage to update it; will do now. IMHO this is small enough as to try in 8.13.

Ok, updated; I've chosen the settings that offer best performance, at the cost of 10% more memory in unimath. IMHO this is a reasonable compromise, as there is no best setting in general.

**Comment by gares** [comment]
This needs a quick review, especially of the bench, and an assignee

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
This is probably not going to help perennial not dying of OOM, but, well.

**Comment by ejgallego** [comment]
> This is probably not going to help perennial not dying of OOM, but, well.

Actually you have a good point, we could set `OCAMLRUNPARAM` on the perennial CI to an aggressive policy and see what happens.

**Comment by gares** [comment]
if it's ready, please merge

**Comment by gares** [comment]
> Actually you have a good point, we could set `OCAMLRUNPARAM` on the perennial CI to an aggressive policy and see what happens.

sure, but that would be another PR

**Comment by ejgallego** [comment]
> sure, but that would be another PR

Of course ! Actually we can tweak the GC settings for perennial even without this PR by using the env variable.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
@coqbot merge now

**Comment by ejgallego** [comment]
Thanks folks!

**Pull request merged**
