### PR TITLE
Don't nf_univ_variables in prepare_hint

### PR DESCRIPTION
**Pull request by SkySkimmer**
Seems not useful and may result in a speedup

cf https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/Universe.20normalization.20in.20.60make_local_hint_db.60

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Review by ppedrot — APPROVED** [review]
Aight.

**Comment by Janno** [comment]
Took a little longer but I can now confirm that this change brings the expected performance impact in the files I was profiling when I first noticed the function call.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
