### PR TITLE
[doc] [api] Remove `ocamldoc` support in favor of `odoc`

### PR DESCRIPTION
**Pull request by ejgallego**
This PR removes support for `ocamldoc` in favor of `odoc`.

Following a recent discussion in OCaml's discord, it turns out that
basically all the ecosystem has migrated to odoc, thus we follow suit
and may focus on `odoc` for Coq's ML API documentation.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Is odoc dune only?

**Comment by ejgallego** [comment]
> Is odoc dune only?

No.

**Review by Zimmi48 — APPROVED** [review]
No pb with the clean-up in `Makefile.doc`.

**Review by SkySkimmer — APPROVED** [review]
CI OK.

**Comment by ejgallego** [comment]
cc #7155

**Review by gares — COMMENTED** [review]
Lets put it like that: migrating infrastructure to dune only is a premature commitment and I find this way of doing things intellectually borderline, pretty much definable as "lock in". This is my position, and the fact that the title of this PR does not even acknowledge that you now need dune for that functionality makes me think this is done deliberately.

I won't oppose to this PR, since html doc of the ml API is totally irrelevant to me. But I won't accept any sensible piece of infrastructure to be moved to dune only, at least at the best of my radar range.

**Comment by ejgallego** [comment]
> including the compiler I heard

Just to be clear and avoid confusing the compiler won't require Dune to be built, but support it. But obviously this is a piece of infrastructure where indeed does make sense not to require a tool written in OCaml to bootstrap.

**Comment by Zimmi48** [comment]
Given @gares's statement, I guess he won't be the assignee. Should it be @SkySkimmer?

**Comment by SkySkimmer** [comment]
This should be assigned to doc people, not CI people.

Gaëtan Gilbert

**Comment by ejgallego** [comment]
> This should be assigned to doc people, not CI people.

Indeed. Well, this is more suited for a missing role in Coq, let's call it "API maintainer" or "common infrastructure person" as it indeed impacts the whole project.

**Comment by Zimmi48** [comment]
The only file changed that is in the doc realm is `Makefile.doc` and it is only code removal there. But OK, taking this.

**Comment by ejgallego** [comment]
> I don't think you realize that the dune files look definitely more obscure than the make file ones to _most_ of us.

Define _most_. The current makefiles look pretty obscure to me; to the point I can bet money I can do a quizz on the current make system and nobody will know what they do.

Not to say that we have dozen of bugs opened for the Makefiles, some of them pretty serious and long-lived, and we don't have a few dozens more because I just decided to stop reporting new ones.

> using odoc with dune is much more complicated than using odoc with make.

How so? What is the exact difficulty?

**Comment by Zimmi48** [comment]
I personally always *refused* to learn about make, so yes, I prefer investing some time learning Dune that to waste time with an ~~old and horrible~~ build system (strike-through added to not start a troll).

That being said, we should probably avoid bash and try writing more things with OCaml for the same reasons.

As for using odoc, you don't actually need to understand the build system to do so.

**Comment by maximedenes** [comment]
> Note that this PR was motivated by @maximedenes deciding to upload the odoc-generated docs to https://coq.inria.fr/api/master/ [strangely without any coordination with the ML API issues currently opened].

This was done as an experiment, but I can easily remove it if you like.

**Comment by maximedenes** [comment]
> Interesting deduction.

Sorry, what do you mean?

**Comment by ejgallego** [comment]
> Sorry, what do you mean?

I mean how did you infer that I would like for the API page to be removed?

**Comment by maximedenes** [comment]
> I mean how did you infer that I would like for the API page to be removed?

I did not infer, I asked. Your message seemed to imply you wanted to do something more coordinated instead.

**Comment by ejgallego** [comment]
I think the current site is fine, however it would be great if you could share any update on plans / status on #7155 , otherwise, people willing to help won't be up to date as to what the current situation is.

**Pull request merged**
