### PR TITLE
Cleanup implementation of normalize_context_set a bit 

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure about the second commit, but it looks a bit cleaner to me that way.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/360/

**Comment by SkySkimmer** [comment]
```

┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                     │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  189.11  190.99 -0.98 % │  525858749511  528404490192 -0.48 % │   761505669781   761479680693 +0.00 % │  716252  716256 -0.00 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  808.95  816.18 -0.89 % │ 2254085073367 2277863222420 -1.04 % │  3423291008094  3425940437523 -0.08 % │ 1369948 1369664 +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  102.30  103.18 -0.85 % │  291405536428  291186942528 +0.08 % │   377762994883   378203871789 -0.12 % │  501520  501228 +0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  165.53  166.70 -0.70 % │  459494284286  460944522204 -0.31 % │   699138843781   699212437533 -0.01 % │  715240  715420 -0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3034.68 3044.00 -0.31 % │ 8448201121568 8470006054502 -0.26 % │ 13963963110481 13965814915864 -0.01 % │ 1241856 1242044 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-corn │ 1478.93 1481.88 -0.20 % │ 4104095366713 4112327747108 -0.20 % │  6396684887230  6400162898732 -0.05 % │  835744  835868 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  262.72  263.21 -0.19 % │  728598119278  730480345105 -0.26 % │  1074031253436  1074574667130 -0.05 % │  984884  983072 +0.18 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  662.08  663.13 -0.16 % │ 1847927003283 1848318583932 -0.02 % │  2957630521731  2958331707210 -0.02 % │ 3348184 3348540 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  570.06  570.63 -0.10 % │ 1588221601144 1587811523293 +0.03 % │  1989677614101  1990015594706 -0.02 % │ 1439616 1439048 +0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   60.61   60.66 -0.08 % │  166633185855  166813460805 -0.11 % │   231170460027   231393450636 -0.10 % │  529824  526328 +0.66 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  440.13  439.95 +0.04 % │ 1221816084634 1221610795765 +0.02 % │  2023986187421  2025158549071 -0.06 % │  714512  713904 +0.09 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   75.52   75.36 +0.21 % │  208644656868  208983700603 -0.16 % │   283284322983   283323467069 -0.01 % │  526352  526560 -0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│      coq-formal-topology │   34.22   34.12 +0.29 % │   94902514905   94761359419 +0.15 % │   124851476284   125013005653 -0.13 % │  483888  483784 +0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   75.75   75.46 +0.38 % │  208180553796  208157232958 +0.01 % │   259873385631   259981568634 -0.04 % │  656336  656400 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   59.90   59.51 +0.66 % │  163870084482  164071631069 -0.12 % │   211441140681   211573911571 -0.06 % │  660916  660844 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1353.56 1344.07 +0.71 % │ 3765462407791 3733286312127 +0.86 % │  6591004837442  6591263805627 -0.00 % │  989000  988892 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   41.02   40.61 +1.01 % │  111741960239  111481868320 +0.23 % │   137264744411   137338505342 -0.05 % │  478908  479016 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  169.36  167.54 +1.09 % │  467386342006  465530492254 +0.40 % │   655490219976   655757301035 -0.04 % │  588716  588452 +0.04 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                 coq-hott │  313.44  309.46 +1.29 % │  854382143076  843696191578 +1.27 % │  1375249819960  1375967494201 -0.05 % │  496912  496660 +0.05 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘

INFO: the following OPAM-packages:
- coq-fiat-crypto
- coq-sf-lf
- coq-sf-plf
- coq-sf-vfa
- coq-unimath
- coq-vst
cannot be installed (exit 1)

```

**Comment by maximedenes** [comment]
So the HoTT slowdown seems to exist. Do you plan to work on this for 8.8+beta1?

**Comment by SkySkimmer** [comment]
>So the HoTT slowdown seems to exist. Do you plan to work on this for 8.8+beta1?

I'm going to rebench first.

**Comment by SkySkimmer** [comment]
OK this won't make it for 8.8.

**Comment by mattam82** [comment]
Do you have an idea why this slows down HoTT? It's not just a cleanup it seems

**Comment by SkySkimmer** [comment]
It seems the html files for the bench expired (I get 404 error), rerunning to regenerate them at https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/396/console

**Review by ppedrot — COMMENTED** [review]
Nothing specific to say, it does look kind of cleaner to me.

**Comment by ppedrot** [comment]
@mattam82 Are you OK with the changes in the end?

@maximedenes The changes in the kernel are actualy unrelated to it, the corresponding function should be moved out but is there for abstraction reasons, I believe. Do you quickly agree that this is OK?

**Review by mattam82 — APPROVED** [review]
Yes, I approve!

**Review by maximedenes — COMMENTED** [review]
I have no idea what this does, but I'm ready to trust other reviewers. @ppedrot you say the function should be moved out from the kernel, who's taking care of that?

**Comment by ppedrot** [comment]
@maximedenes I'll probably open up another PR when I have spare time.

**Pull request merged**
