### PR TITLE
Remove camlp4 remains

### PR DESCRIPTION
**Pull request by ppedrot**
A two-patch cleanup on the way to getting rid^W^W enhancing the support of Camlp5 in Coq.

- Remove dead code that used to be there for CamlpX compatibility.

  Part of this code has been introduced very recently in 7c62654 in spite of the existence of a proper API. This means that this should be better documented.

- Introduce a Pcoq.Entry module for functions that ought to be exported.
    
    We deprecate the corresponding functions in Pcoq.Gram. The motivation is that the Gram module is used as an argument to Camlp5 functors, so that it is not stable by extension. Enforcing that its type is literally the one Camlp5 expects ensures robustness to extension statically.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>robustness to extension

What do you mean by that exactly?

**Comment by ppedrot** [comment]
Like the fact that adding a type in the Coq `Gram` module break compatibility with the recent master branch of Camlp5.

**Review by gares — APPROVED** [review]
trivial changes in files i own

**Comment by ejgallego** [comment]
> Part of this code has been introduced very recently in 7c62654 in spite of the existence of a proper API. This means that this should be better documented.

I need to review the PR but I'd be surprised if that's the case; the commit you point out only moved code around.

**Comment by ppedrot** [comment]
@ejgallego You needed to extend the API to export stuff that was only used internally to Pcoq.

**Comment by ejgallego** [comment]
Ah indeed I had to export a couple ofnm functions, didn't think a lot about it

**Comment by ppedrot** [comment]
pidetop needs to be adapted it seems.

**Review by herbelin — COMMENTED** [review]
Good to me.

But notice probable merge conflicts with other PRs touching parsing. That would be a pity to enter (again) variants of "rebase -> silence -> ping -> silence -> rebase -> waiting"-like cycles for these older PRs.

**Review by ejgallego — APPROVED** [review]

**Comment by ppedrot** [comment]
I don't really know how to submit a PR to pidetop for that. People have suggested workarounds on gitter, but it requires @gares's cooperation in any case.

**Comment by gares** [comment]
I've asked @ale-f to get pidetop on github under the coqoon organization but I still have no answer.
In the meanwhile you make a PR here https://bitbucket.org/coqpide/pidetop

**Comment by ejgallego** [comment]
@ppedrot just add pidetop to github or gitlab and then delete the repos.

Who's taking over this PR?

**Comment by ppedrot** [comment]
I don't manage to compile `pidetop` on my machine, let alone fix it. For some reason jbuilder picks the wrong Coq installation, even though `COQBIN`, `COQLIB` and `PATH` are properly set. What am I supposed to do?

**Comment by gares** [comment]
I guess you could post a log and @ejgallego help you find out the problem...

**Comment by ppedrot** [comment]
@gares I won't be very informative, but here it is:
```
pm@ouranos:~/sources/pidetop$ jbuilder build
      ocamlc pide_bin/.pideproofworker_top.eobjs/pideproofworker_top.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/pm/.opam/4.04.0+fp/bin/ocamlc.opt -rectypes -g -bin-annot -I pide_bin/.pideproofworker_top.eobjs -I /home/pm/.opam/4.04.0+fp/lib/camlp5 -I /home/pm/.opam/4.04.0+fp/lib/coq/clib -I /home/pm/.opam/4.04.0+fp/lib/coq/config -I /home/pm/.opam/4.04.0+fp/lib/coq/engine -I /home/pm/.opam/4.04.0+fp/lib/coq/interp -I /home/pm/.opam/4.04.0+fp/lib/coq/kernel -I /home/pm/.opam/4.04.0+fp/lib/coq/kernel/byterun -I /home/pm/.opam/4.04.0+fp/lib/coq/lib -I /home/pm/.opam/4.04.0+fp/lib/coq/library -I /home/pm/.opam/4.04.0+fp/lib/coq/parsing -I /home/pm/.opam/4.04.0+fp/lib/coq/pretyping -I /home/pm/.opam/4.04.0+fp/lib/coq/printing -I /home/pm/.opam/4.04.0+fp/lib/coq/proofs -I /home/pm/.opam/4.04.0+fp/lib/coq/stm -I /home/pm/.opam/4.04.0+fp/lib/coq/tactics -I /home/pm/.opam/4.04.0+fp/lib/coq/toplevel -I /home/pm/.opam/4.04.0+fp/lib/coq/vernac -I /home/pm/.opam/4.04.0+fp/lib/num -I /home/pm/.opam/4.04.0+fp/lib/ocaml/threads -I pide/.pidetop.objs -no-alias-deps -o pide_bin/.pideproofworker_top.eobjs/pideproofworker_top.cmo -c -impl pide_bin/pideproofworker_top.ml)
File "pide_bin/pideproofworker_top.ml", line 8, characters 4-138:
Error: This function should have type Stateid.t -> Exninfo.iexn -> unit
       but its first argument is labelled ~doc
      ocamlc pide_bin/.pide_top.eobjs/pide_top.{cmi,cmo,cmt} (exit 2)
(cd _build/default && /home/pm/.opam/4.04.0+fp/bin/ocamlc.opt -rectypes -g -bin-annot -I pide_bin/.pide_top.eobjs -I /home/pm/.opam/4.04.0+fp/lib/camlp5 -I /home/pm/.opam/4.04.0+fp/lib/coq/clib -I /home/pm/.opam/4.04.0+fp/lib/coq/config -I /home/pm/.opam/4.04.0+fp/lib/coq/engine -I /home/pm/.opam/4.04.0+fp/lib/coq/interp -I /home/pm/.opam/4.04.0+fp/lib/coq/kernel -I /home/pm/.opam/4.04.0+fp/lib/coq/kernel/byterun -I /home/pm/.opam/4.04.0+fp/lib/coq/lib -I /home/pm/.opam/4.04.0+fp/lib/coq/library -I /home/pm/.opam/4.04.0+fp/lib/coq/parsing -I /home/pm/.opam/4.04.0+fp/lib/coq/pretyping -I /home/pm/.opam/4.04.0+fp/lib/coq/printing -I /home/pm/.opam/4.04.0+fp/lib/coq/proofs -I /home/pm/.opam/4.04.0+fp/lib/coq/stm -I /home/pm/.opam/4.04.0+fp/lib/coq/tactics -I /home/pm/.opam/4.04.0+fp/lib/coq/toplevel -I /home/pm/.opam/4.04.0+fp/lib/coq/vernac -I /home/pm/.opam/4.04.0+fp/lib/num -I /home/pm/.opam/4.04.0+fp/lib/ocaml/threads -I pide/.pidetop.objs -no-alias-deps -o pide_bin/.pide_top.eobjs/pide_top.cmo -c -impl pide_bin/pide_top.ml)
File "pide_bin/pide_top.ml", line 13, characters 4-126:
Error: This function should have type Stateid.t -> Exninfo.iexn -> unit
       but its first argument is labelled ~doc
```
The problem is that Coq is living in `/home/pm/sources/coq/` and for some reason `jbuilder` is picking the one that is installed in the opam repository. I guess it is the intended behaviour, but that's **really** annoying. I don't want to install development versions of Coq globally, and I don't want to recompile opam switches everytime I need to test a development that's using dune.

**Comment by ejgallego** [comment]
You could have had a brief look to the `ci-pidetop` target, which would tell you that your problem here is `ocamlfind` not Dune; solution:
```
    export OCAMLPATH="$PWD/_install_ci/lib:$OCAMLPATH"
```

**Comment by ppedrot** [comment]
@ejgallego I actually looked at that file. Where does this magic global variable appear in it?

**Comment by ejgallego** [comment]
> @ejgallego I actually looked at that file. Where does this magic global variable appear in it?

It is now set globally for all ci setups in `ci-common.sh`.

**Comment by ejgallego** [comment]
Once #6857 is merged things will work out of the box a bit better if you chose to fixup trees using the `ci-*` target.

**Comment by ejgallego** [comment]
15 days and no assignee, I offered to take this in the past to @ppedrot , offer stands, but of course a more direct maintainer is welcome to take it.

**Comment by ejgallego** [comment]
The PR is merged, @gares can you pull from https://github.com/ppedrot/pidetop/tree/rm-campl4-remains ?

**Comment by Zimmi48** [comment]
@gares ping

**Comment by ejgallego** [comment]
@gares I've created a PR so you have an easier time merging:

https://bitbucket.org/coqpide/pidetop/pull-requests/8/fix-compilation-wrt-coq-pr-7898/diff

**Comment by gares** [comment]
done, I'm sorry for the repo still being on bitbucket :-/

**Comment by ejgallego** [comment]
Thanks Enrico.

**Pull request merged**
