### PR TITLE
Extrude the computation of redexp flags in reduce.

### PR DESCRIPTION
**Pull request by ppedrot**
This was a source of slowdown observed in bedrock2.
bench https://gitlab.com/coq/coq/-/jobs/903611583

### CODE REVIEW

**Comment by SkySkimmer** [comment]
~~~
┌────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                        │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                        │                         │                                       │                                       │                         │                 │
│           package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-fourcolor │ 2575.05  2597.82  -0.88 │  7179967377674   7231675075844  -0.72 │ 12429896555501  12429684089965   0.00 │  728428   728512  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coqprime │   78.74    79.41  -0.84 │   216860877140    217351117117  -0.23 │   307197729496    307192135266   0.00 │  764356   764444  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-algebra │  137.89   138.48  -0.43 │   383766017452    383799761167  -0.01 │   499710613804    499771855363  -0.01 │  549052   547364   0.31 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-geocoq │ 1452.27  1456.25  -0.27 │  4050408639280   4060088725818  -0.24 │  6183125286052   6183289452555  -0.00 │ 1027976  1028236  -0.03 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-math-classes │  211.66   212.10  -0.21 │   590693112208    592607386725  -0.32 │   813215951003    813148804711   0.01 │  522360   522756  -0.08 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-ssreflect │   51.12    51.19  -0.14 │   139016469241    139537209394  -0.37 │   178467360164    178373510885   0.05 │  509816   509892  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                    coq │  518.90   519.61  -0.14 │  1449435587856   1452936444919  -0.24 │  1955191210536   1955152594156   0.00 │  568264   565440   0.50 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-coqutil │   60.56    60.60  -0.07 │   168531111783    167881319204   0.39 │   209922572534    209912009791   0.01 │  527160   527136   0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-fiat-parsers │  626.80   627.12  -0.05 │  1754260542212   1753467718904   0.05 │  2695782767320   2695755958991   0.00 │ 3241848  3241676   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-corn │ 1619.89  1620.51  -0.04 │  4507644356909   4511375048520  -0.08 │  6940722902209   6940399905408   0.00 │  774584   774684  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-color │  504.90   504.80   0.02 │  1408893045622   1409808343310  -0.06 │  1786686724728   1786577771468   0.01 │ 1133648  1133492   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-hott │  328.08   327.93   0.05 │   890473631813    890029090884   0.05 │  1452159822207   1451750901573   0.03 │  602600   602636  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-bignums │   56.45    56.42   0.05 │   155938130613    156093940861  -0.10 │   210276837613    210262130384   0.01 │  474416   474376   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-character │  154.23   154.10   0.08 │   428566462633    428594611678  -0.01 │   602360562872    602315472622   0.01 │  711064   711300  -0.03 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-bedrock2 │  223.58   223.32   0.12 │   617910023106    617512074721   0.06 │  1031171929956   1031313303906  -0.01 │ 1027564  1027636  -0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-verdi │  101.55   101.42   0.13 │   279537586253    278884165224   0.23 │   396341052119    395404439998   0.24 │  547036   546160   0.16 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-fiat-core │  102.29   102.12   0.17 │   291650309285    291321298783   0.11 │   389352219015    388050048975   0.34 │  479280   479428  -0.03 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq-perennial │ 5479.44  5468.84   0.19 │ 15223346934611  15206486912756   0.11 │ 23041207605918  23022987168943   0.08 │ 3205072  3056988   4.84 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-verdi-raft │ 1227.37  1224.66   0.22 │  3415091080379   3412025534977   0.09 │  4860856494919   4859950583675   0.02 │  902928   902748   0.02 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-mathcomp-solvable │  169.16   168.76   0.24 │   470095884025    469123571924   0.21 │   669520300175    669626882565  -0.02 │  662532   662488   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-coquelicot │   66.87    66.69   0.27 │   183760756274    183385332495   0.20 │   235736819712    234993744758   0.32 │  567804   567948  -0.03 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│        coq-lambda-rust │ 1222.26  1218.86   0.28 │  3402123187835   3392918170193   0.27 │  4926480957601   4927448531543  -0.02 │ 1091880  1090764   0.10 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-compcert │  635.27   633.40   0.30 │  1768531381715   1764547654197   0.23 │  2469153909708   2469215570546  -0.00 │ 1047212  1047136   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-unimath │ 3983.86  3970.97   0.32 │ 11086440775091  11052497899657   0.31 │ 21366109406678  21363086012978   0.01 │ 1140872  1140780   0.01 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-flocq │  156.26   155.70   0.36 │   434131635812    431219047759   0.68 │   540812218972    540763975312   0.01 │  821120   820920   0.02 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-mathcomp-fingroup │   47.33    47.05   0.60 │   130877799880    130500322614   0.29 │   182209888506    182127853919   0.05 │  480904   480916  -0.00 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-field │  222.69   221.10   0.72 │   619098197807    616262363271   0.46 │   949797143398    949819616068  -0.00 │  677356   676500   0.13 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-odd-order │ 1049.24  1041.24   0.77 │  2921135920316   2900939332932   0.70 │  4664396191171   4664318632798   0.00 │  974304   983200  -0.90 │   0    0    nan │
├────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│  coq-engine-bench-lite │  343.88   341.16   0.80 │   967215979002    961255047198   0.62 │  1741419062977   1741175058909   0.01 │ 3500024  3499960   0.00 │   0    0    nan │
└────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘

INFO: failed to install:
coq-fiat-crypto
coq-performance-tests-lite
coq-rewriter
coq-rewriter-perf-SuperFast
coq-sf-plf
~~~

**Comment by ppedrot** [comment]
I am a bit surprised by the absence of change on bedrock since the hotspots I was seeing locally have disappeared after this patch. What is the bedrock2 opam package compiling exactly? They have so many submodules it might appear somewhere else...

**Comment by SkySkimmer** [comment]
Considering bedrock takes <4min on the bench and around 2h in CI it's definitely under-compiling.
The opam file is https://github.com/coq/opam-coq-archive/blob/6f0ecd46bedd6852b34f273eb691f35ffa7bf43b/extra-dev/packages/coq-bedrock2/coq-bedrock2.dev/opam#L12

**Comment by ppedrot** [comment]
Any way to get this to run without hacking my own opam package?

**Comment by ppedrot** [comment]
Let's see if this works: https://gitlab.com/coq/coq/-/jobs/905643426.

**Comment by ppedrot** [comment]
On our fancy bedrock, it's observable.
```
┌──────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│              │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│              │                         │                                       │                                       │                         │                 │
│ package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD  PDIFF │ NEW  OLD  PDIFF │
├──────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-bedrock2 │ 4454.90  4487.81  -0.73 │ 12402168269267  12495470679165  -0.75 │ 19693099930862  19920007902635  -1.14 │ 3615992  3793956  -4.69 │   0    0    nan │
├──────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│          coq │  518.07   516.40   0.32 │  1448957824442   1447420715384   0.11 │  1954426252191   1954657786849  -0.01 │  568316   568160   0.03 │   0    0    nan │
└──────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘
```
Not so much at the level of the whole development, which is gargantuan, but some individual lines are notoriously faster. Here is a list of lines that are faster by more than 1s:
```
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:2727 -22.94 225.76 202.82 (-10%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:3016 -5.94 55.50 49.56 (-11%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:1706 -2.82 28.14 25.32 (-10%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:1851 -2.59 29.07 26.48 (-9%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:2356 -1.55 15.45 13.90 (-10%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:2496 -1.54 15.22 13.68 (-10%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:2671 -1.34 3.10 1.76 (-43%)
html/coq-bedrock2/processor/src/processor/KamiRiscvStep.v.html:2947 -1.19 56.91 55.72 (-2%)
```

**Comment by ppedrot** [comment]
I have tweaked the PR a bit so as to be backwards-compatible API-wise. This should not require an overlay anymore.

**Review by herbelin — APPROVED** [review]
Basically, is it that you split the interpretation of redexp into a part which is common to all hyps (the flags) and a part which is hyp-related (the occurrences)?

By curiosity, why interpreting flags is so costly? This looks like small objects.

**Comment by ppedrot** [comment]
> By curiosity, why interpreting flags is so costly? This looks like small objects.

Do something cheap for every single hypothesis in a huge context, it'll end up costing quite a bit.

**Comment by herbelin** [comment]
Some `in *` then I guess. I see.

**Comment by ppedrot** [comment]
@herbelin are you assigning?

**Comment by herbelin** [comment]
OK

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
