### PR TITLE
Delay inventing names for monomorphic universes

### PR DESCRIPTION
**Pull request by SkySkimmer**
This avoids doing it repeatedly for nothing in intern/extern.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Bench https://gitlab.com/coq/coq/-/jobs/885977299

**Comment by Janno** [comment]
That looks like 100% positive benchmark!

```
┌─────────────────────────────┬─────────────────────────┬───────────────────────────────────────┬───────────────────────────────────────┬──────────────────────────┬─────────────────┐
│                             │      user time [s]      │              CPU cycles               │           CPU instructions            │  max resident mem [KB]   │   mem faults    │
│                             │                         │                                       │                                       │                          │                 │
│                package_name │     NEW      OLD  PDIFF │            NEW             OLD  PDIFF │            NEW             OLD  PDIFF │     NEW      OLD   PDIFF │ NEW  OLD  PDIFF │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-bedrock2 │  222.03   226.07  -1.79 │   614003614950    625568578775  -1.85 │  1020447240907   1040905059009  -1.97 │ 1160064  1160020    0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-fiat-crypto │ 5016.48  5087.67  -1.40 │ 13939394305105  14134437439615  -1.38 │ 24572929762074  24809162157739  -0.95 │ 2269536  2278240   -0.38 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-perennial │ 5100.73  5158.06  -1.11 │ 14168691179329  14324573633038  -1.09 │ 21386773647814  21641222101209  -1.18 │ 3200608  3085984    3.71 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-solvable │  167.40   169.05  -0.98 │   467040817830    470502311302  -0.74 │   665132188266    669748215064  -0.69 │  675168   685172   -1.46 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-odd-order │ 1040.48  1050.72  -0.97 │  2895740131046   2924819011283  -0.99 │  4633635309683   4686544662604  -1.13 │  983892   984220   -0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│ coq-rewriter-perf-SuperFast │  781.37   788.39  -0.89 │  2177025537519   2195012309342  -0.82 │  3459179631716   3472076399141  -0.37 │  985300   992940   -0.77 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-rewriter │  711.67   717.56  -0.82 │  1976861640197   1993517658637  -0.84 │  3078370142405   3100318907195  -0.71 │  985384   973888    1.18 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-verdi │  101.39   102.05  -0.65 │   279429504578    280270605300  -0.30 │   396547488850    397192289606  -0.16 │  546328   547492   -0.21 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│          coq-mathcomp-field │  219.83   221.24  -0.64 │   611568925590    616152083104  -0.74 │   938726116389    948920732967  -1.07 │  669336   673952   -0.68 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-hott │  316.60   318.24  -0.52 │   861192868532    865672146605  -0.52 │  1412369805692   1424092557380  -0.82 │  619700   618632    0.17 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                         coq │  515.87   518.20  -0.45 │  1443920626436   1452145828166  -0.57 │  1951357807472   1956104212736  -0.24 │  569072   569252   -0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│             coq-lambda-rust │ 1221.96  1227.11  -0.42 │  3400092098240   3413864611543  -0.40 │  4928066632124   4961380602947  -0.67 │ 1119032  1114308    0.42 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-fiat-parsers │  626.71   628.84  -0.34 │  1754161915959   1762466753471  -0.47 │  2699100092876   2713291379789  -0.52 │ 3640492  3241936   12.29 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-color │  502.60   504.05  -0.29 │  1405232170323   1406251716988  -0.07 │  1783450320877   1784116935511  -0.04 │ 1133684  1133672    0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-engine-bench-lite │  364.64   365.57  -0.25 │  1025860211854   1027457117059  -0.16 │  1743269125755   1743939842295  -0.04 │ 3499912  3979000  -12.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-character │  153.17   153.54  -0.24 │   425827271833    426532569821  -0.17 │   596855338132    597925651267  -0.18 │  706800   710460   -0.52 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│        coq-mathcomp-algebra │  136.06   136.35  -0.21 │   378500026881    379543472567  -0.27 │   492736533184    493590777088  -0.17 │  548268   545852    0.44 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                    coq-corn │ 1616.49  1619.85  -0.21 │  4500080695749   4504597712087  -0.10 │  6915564210050   6934066151966  -0.27 │  808904   809056   -0.02 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fiat-core │  102.37   102.51  -0.14 │   291803241872    291454439739   0.12 │   389422745831    389428866866  -0.00 │  478916   478624    0.06 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                   coq-flocq │  155.07   155.26  -0.12 │   431118226312    430874470260   0.06 │   539809703050    539931703889  -0.02 │  820704   820724   -0.00 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-compcert │  633.64   634.40  -0.12 │  1766682502805   1769337606507  -0.15 │  2466396378809   2468643527255  -0.09 │ 1047128  1047492   -0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-verdi-raft │ 1217.16  1217.87  -0.06 │  3390076702840   3393930359433  -0.11 │  4829555246160   4830873028598  -0.03 │  902636   903768   -0.13 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│            coq-math-classes │  211.74   211.84  -0.05 │   590605966418    590982999061  -0.06 │   812541933361    812720135383  -0.02 │  524340   524524   -0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│               coq-fourcolor │ 2564.40  2564.33   0.00 │  7149279381432   7150202189376  -0.01 │ 12420303449207  12426894800788  -0.05 │  728428   728684   -0.04 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-bignums │   56.55    56.54   0.02 │   156357960664    156044916990   0.20 │   211088081803    211132079310  -0.02 │  473756   473620    0.03 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│              coq-coquelicot │   67.31    67.28   0.04 │   184079791918    184546477937  -0.25 │   236206445290    236906504582  -0.30 │  566452   564296    0.38 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│       coq-mathcomp-fingroup │   47.13    47.08   0.11 │   130400281384    130254772117   0.11 │   180814824696    180909513150  -0.05 │  477096   478940   -0.39 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-unimath │ 3906.96  3901.93   0.13 │ 10867881613621  10853348780852   0.13 │ 20920705124112  20927352038084  -0.03 │ 1122020  1142364   -1.78 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                  coq-geocoq │ 1447.25  1445.19   0.14 │  4031131107851   4026267053795   0.12 │  6135575364655   6135552671337   0.00 │ 1017988  1016768    0.12 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                coq-coqprime │   79.05    78.58   0.60 │   216450136715    216025044476   0.20 │   305573632429    305658294048  -0.03 │  764172   762908    0.17 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│                 coq-coqutil │   60.48    60.05   0.72 │   167643164657    167110812290   0.32 │   208951116437    209050229462  -0.05 │  524332   524264    0.01 │   0    0    nan │
├─────────────────────────────┼─────────────────────────┼───────────────────────────────────────┼───────────────────────────────────────┼──────────────────────────┼─────────────────┤
│      coq-mathcomp-ssreflect │   51.33    50.85   0.94 │   138854170849    138684093935   0.12 │   177615362161    177943903377  -0.18 │  510852   507976    0.57 │   0    0    nan │
└─────────────────────────────┴─────────────────────────┴───────────────────────────────────────┴───────────────────────────────────────┴──────────────────────────┴─────────────────┘
```

**Comment by ppedrot** [comment]
I am assigning despite not being an official maintainer.

**Comment by ppedrot** [comment]
@SkySkimmer There are other users of `universe_binders`, do they all go through the declaration functions you've modified?

**Comment by SkySkimmer** [comment]
Not sure what you mean.
The UnivBinders output test is relatively thorough so the change should be correct.

**Comment by gares** [comment]
if OK, please merge this now, or change milestone

**Review by ppedrot — APPROVED** [review]
Code changes are fine I believe.

**Comment by ppedrot** [comment]
Waiting for CI still.

**Comment by SkySkimmer** [comment]
ci green

**Comment by gares** [comment]
Even on this pr the bench is mostly noise. Are these two pr fixing a real issue or not? Please explain why they need to be in 8.13.

**Comment by SkySkimmer** [comment]
That's not noise. Also it fixes a printing bug where we qualify universe names too much (see test suite addition).

**Comment by SkySkimmer** [comment]
A bunch of long lines in https://coq.gitlab.io/-/coq/-/jobs/885977299/artifacts/_bench/html/coq-fiat-crypto/src/PushButtonSynthesis/WordByWordMontgomeryReificationCache.v.html show 16% improvement for instance.

**Pull request merged**
