### PR TITLE
swap sval and @sval notations

### LINKED ISSUE #17248: printing of the sval notation
#### Description of the problem

```coq
Axiom T : Type.
Axiom P Q : T -> Prop.
Axiom u : sig P.
Check svalP u
```
prints as `svalP u : P ((@sval) T P u)` instead of `svalP u`

#### Coq Version

Coq 8.15.2

### PR DESCRIPTION
**Pull request by affeldt-aist**
Fixes #17248

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
The linter complains, you probably have a trailing space

**Comment by SkySkimmer** [comment]
No, the linter complains because this PR is based on an old commit. You should rebase on master.

**Comment by gares** [comment]
@coqbot merge now

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot merge now

**Comment by pi8027** [comment]
Now I'm changing the `"@ 'sval'"` notation on the MathComp side in math-comp/math-comp#1131. Turning it into an "only parsing" notation would be a more robust solution.

**Pull request merged**
