### PR TITLE
Update CAMLDONTLINK in CoqMakefile.in

### LINKED ISSUE #12603: coq_makefile CAMLDONTLINK list is incomplete?
#### Description of the problem

https://github.com/coq/coq/blob/5ea6ef71681770a98edc5ede8614d2cf0bd48554/tools/CoqMakefile.in#L106-L107

is a strict subset of

https://github.com/coq/coq/blob/42e9c71b8f0b27c7720c22cd57517af77a5f8e90/Makefile.build#L305

and manually adding `num` to the generated Makefile makes SMTCoq build for me https://github.com/smtcoq/smtcoq/pull/62#issuecomment-591849379 error `The module 'Int_misc' is already loaded`.

#### Coq Version

observed on 8.11.2, links above are from searching on master

### PR DESCRIPTION
**Pull request by andres-erbsen**
I used SYSMOD from Makefile.build as the ground truth.

This is would be an immediate fix for #12603, let's see what the CI says.

### CODE REVIEW

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Great, thanks

**Comment by Zimmi48** [comment]
Following this change, we have observed that several Coq plugins (bignums, Equations, aac-tactics) needed to specify `num` as an explicit dependency (when building with Nix). Is this a normal consequence of this change? I was a bit surprised by this change given that for aac-tactics for instance, is not supposed to depend on `num` directly according to its Dune file.

**Comment by gares** [comment]
What this change should do is that, even if your plugin depends on one of the modules listed (like num) then it is not linked (to avoid linking it twice, since one copy is linked by Coq already).

I don't know what happens on Nix, I guess num should be pulled in by Coq. Isn't it?

**Comment by Zimmi48** [comment]
Coq depends on `num` but the dependency is not propagated. Contrary to an opam setup where all the libraries are installed in the same place and thus `ocamlfind` can see all the direct and transitive dependencies, in a Nix setup the libraries are installed in various places and `OCAMLPATH` is populated with their locations. Because the dependency on `num` is not propagated, it isn't added to `OCAMLPATH` and `ocamlfind` cannot find it. What changed is that plugins that should not depend on `num` directly (only transitively because of Coq) suddenly fail to build because `num` cannot be found. Let us know if you think that's normal or unexpected. If it's normal, then it probably means that we should propagate the `num` dependency from now on.

**Comment by gares** [comment]
What I don't get is how this pr changed that. I don't think it did.

I'm sorry but I don't know what is the best thing for nix. In Debian one would have coq ans coq-dev, the latter pulling in all deps for developing on top of coq, the former just the binaries (no cmi for example).

**Comment by Zimmi48** [comment]
>What I don't get is how this pr changed that. I don't think it did.

FTR I just confirmed that this PR was the one that changed this behavior, at least for aac-tactics, by running the following (inside the aac-tactics repository at commit coq-community/aac-tactics@4810d80566f844cbde6caa25ced5409e8b771270):

```bash
nix-build --argstr coq-version-or-url https://github.com/coq/coq/tarball/61aeca9ca2a7c46b143b90583dfb84b037eccc5b
# success
nix-build --argstr coq-version-or-url https://github.com/coq/coq/tarball/a039e78c821ba6a0da5d3364b98491707eab8add
# fail with ocamlfind: Package `num' not found
```

>I'm sorry but I don't know what is the best thing for nix.

Thanks for trying anyway. @vbgl What do you think? Should we just propagate the `num` dependency and forget about it?

**Comment by silene** [comment]
I am quite confused. You said that `OCAMLPATH` had not been populated with the location of the `num` library, but I do not understand who is responsible for populating it. Is this Nix? Is this Dune? Is this someone else? According to your testing, it seems that whoever is populating `OCAMLPATH` is taking a look at the `CAMLDONTLINK` variable from CoqMakefile, since that is the only thing that changed.

**Comment by Zimmi48** [comment]
This is Nix who is responsible for populating `OCAMLPATH`. What `OCAMLPATH` contains did not change after this PR. `num` is not listed in `OCAMLPATH` unless we explicitly ask Nix that it be, easier by making `num` an explicit dependency of these plugins (which it isn't supposed to be) or by propagating this dependency of Coq. The only thing that changed after this PR is that `ocamlfind` suddenly started looking for `num` even though it is not a direct dependency of those plugins.

**Comment by silene** [comment]
I see. So, it is kind of misfeature of `ocamlfind`, as it is resolving `-dontlink` packages. I guess the point can be made either way. Do not resolve them as they are useless; resolve them, so as to detect a user typo.

Still, making `num` an explicit dependency of plugins does not seem like the best solutions. Does Nix support some kind of global package variable? That way, the Coq package would define a variable mentioning all the builtin dependencies (including `num`), while libraries would depend on the content of this variable. Thus, if the dependencies of Coq ever change, the dependencies of the plugin do not have to be modified accordingly.

**Comment by Zimmi48** [comment]
If I understood correctly what you mean, this is what is done in Nix with dependency propagation.

**Pull request merged**
