### PR TITLE
Fix a few bugs in the checker

### PR DESCRIPTION
**Pull request by vbgl**

### CODE REVIEW

**Comment by herbelin** [comment]
Shall we infer that these bugs are found by running the checker on the test suite? If yes, congratulations.

**Comment by maximedenes** [comment]
> Shall we infer that these bugs are found by running the checker on the test suite?

Yes, indeed.

**Review by ppedrot — APPROVED** [review]
Looks like a backport of the kernel changes. I am not quite proficient about the typing rules of inductive types and fixpoints, but hopefully the kernel is correct. This means that the current PR is OK. I'll wait for more knowledgeable devs to comment though.

**Comment by ppedrot** [comment]
@herbelin @maximedenes @mattam82 Are you fine with the changes?

**Review by maximedenes — APPROVED** [review]

**Review by herbelin — APPROVED** [review]
Seems canonical backport, so approve.

**Comment by ppedrot** [comment]
CI failure looks spurious, I'll merge altogether.

**Pull request merged**
