### PR TITLE
Avoid extra univ constraint in array literal elaboration

### LINKED ISSUE #18480: Array pretyping introduces unnecessary universe constraints
#### Description of the problem
```coq
Require Import PArray.
Universes u v.

Definition a : array@{v} nat := [| | 0 |]@{u}.
Print Universes Subgraph (u v).
(* Set < u, Set < v *)
Definition b : array@{v} _ := [| | 0 |]@{u}.
Print Universes Subgraph (u v).
(* Set < u, Set < v, v <= u *)
```

This additional constraint is added here:
https://github.com/coq/coq/blob/db93e18bd758c68f62753392b8606f2f089f8294/pretyping/pretyping.ml#L1390

#### Coq Version
8.18.0, 8.20+alpha

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close #18480

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Not sure if we want to do this, @coq/pretyper-maintainers any opinions?

**Comment by ppedrot** [comment]
@SkySkimmer what do you consider problematic with this PR? The code is slightly more complex but that's about it.

**Comment by SkySkimmer** [comment]
I guess it's ok, but retyping something we typechecked feels a bit awkward

**Review by ppedrot — APPROVED** [review]
Good enough for me.

**Comment by ppedrot** [comment]
Will merge soon in case someone wants to object.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
