### PR TITLE
Link plugins against their dependencies

### PR DESCRIPTION
**Pull request by bluelightning32**
Android does not properly support the RTLD_GLOBAL flag to dlopen. So .cmxs
plugins need to be linked against all other plugins they get symbols from.

### CODE REVIEW

**Comment by ejgallego** [comment]
Umm, so in the case of plugins `A B`, with `B` depending on `A`, `A` will be linked to each `B`. So when we load `B`, it's copy of `A` will be loaded too? Is that supported? Will its side effects be performed twice?

**Comment by bluelightning32** [comment]
Apparently for mutual dependencies, they all share the same copy.

I wasn't sure, so I had to test it. I get the same output from this test on Linux and Android 8.0.

[src.tar.gz](https://github.com/coq/coq/files/1413455/src.tar.gz)
```
bash-4.4$ tar -xvzf src.tar.gz 
a.c
b.c
main.c

bash-4.4$ gcc -fPIC -Wall -shared -o liba.so a.c -Wl,-init,ALoad -Wl,--no-undefined

bash-4.4$ gcc -fPIC -Wall -shared -o libb.so b.c -Wl,-init,BLoad -Wl,--no-undefined ./liba.so

bash-4.4$ gcc -ggdb -Wall -o main main.c -ldl

bash-4.4$ ./main 
loading a
A loaded
loading b
B loaded
Setting A.value to 0 and B.A.value to 0
A.value=0 B.A.value=0
Setting A.value to 1
A.value=1 B.A.value=1
Setting B.A.value to 2
A.value=2 B.A.value=2
```

**Comment by ejgallego** [comment]
I think we should also test OCaml's semantics for plugins, that is to say:
- `A.ml` -> plugin with some static initialization [such as `printf`]
- `B.ml` -> plugin that depends on `A`.
then, load `A`, then, after `B` and observe which side-effects are performed.

**Comment by bluelightning32** [comment]
So I haven't actually written ocaml code before, but I think this is what you asked me to test (output from Android and Linux is similar):
[ocaml-example.tar.gz](https://github.com/coq/coq/files/1417136/ocaml-example.tar.gz)
```
bash-4.4$ tar -xvzf ocaml-example.tar.gz 
a.ml
b.ml
main.ml

bash-4.4$ ocamlopt -shared a.ml -o a.cmxs

bash-4.4$ ocamlopt -shared b.ml -o b.cmxs -cclib ./a.cmxs

bash-4.4$ ldd b.cmxs
./a.cmxs
libdl.so
libc.so

bash-4.4$ ocamlopt dynlink.cmxa main.ml -o main

bash-4.4$ ./main 
main started
a loaded
b loaded
main done loading libraries
```

**Comment by ejgallego** [comment]
> bash-4.4$ ocamlopt -shared b.ml -o b.cmxs -cclib ./a.cmxs

Umm, this line is not linking `a` properly. This one does:
```
ocamlopt -shared b.ml a.cmx -o b.cmxs
```
and indeed then I see the problem:
```
main started
a loaded
b loaded
a loaded
main done loading libraries
```

**Comment by bluelightning32** [comment]
Passing a.cmx statically links another copy of the library. That's completely different from -cclib a.cmxs, which dynamically links in the same copy. Statically linking a.cmx is like copy and pasting all the code again.

Using -cclib a.cmxs works, but passing a.cmx does not work. Why is -cclib a.cmxs not proper?

I could use patchelf to add the a.cmxs dependency to b.cmxs after the fact, but that seems like a hack to me.

Do you have a better suggestion of how to get Coq to load on Android?

**Comment by ejgallego** [comment]
Thanks for the explanation of course thanks a lot for the patch. Indeed I am confused what is the role of `-cclib` here as you usually use that in ocaml for the C libraries, however you are using it for CAML-only plugins.

What symbols fail to be resolved if you don't pass `-cclib`? @letouzey , do you know a bit more about this? What do you think of the makefile patch?

Does anyone have a reference for OCaml dynlink in Android that we could consult? [I am afraid few of the Coq devs know about Android peculiarities] 

By the way, it is Coq policy that all PR are opened against master [and backported if appropiate] so if you rebase please do change the branch to `master`.

**Comment by bluelightning32** [comment]
Typically when one writes a .so, the .so links against all of its dependencies, so that the .so has no undefined symbols. Although it is possible for the .so to have undefined symbols, which get resolved against the executable's symbols and the symbols of any libraries the executable has already loaded with dlopen using the RTLD_GLOBAL flag.

The RTLD_GLOBAL flag does not work on Android. If you pass it to dlopen, dlopen treats it as if RTLD_LOCAL was passed instead. So instead I had to link to .so against its dependencies. -cclib is the only ocamlopt option that can do that.

You asked about which symnbols fail to resolve. Any time a Coq plugin depends on another one, it gets unresolved symbols on Android without my patch. Here's the first one that causes the build to fail:
```
# Error:                                                                                                                              
# while loading                                                                                                                       
# /data/data/com.termux/files/home/.opam/4.06.0+beta2/build/coq.dev/plugins/ltac/tauto_plugin.cmxs:                                   
# error loading shared library: dlopen failed: cannot locate symbol "camlLtac_plugin__Taccoerce__to_constr_8093" referenced by "/data/
data/com.termux/files/home/.opam/4.06.0+beta2/build/coq.dev/plugins/ltac/tauto_plugin.cmxs"...
```

I rebased my changes against the master branch. I want to keep the bluelightning32:v8.7-android branch on version 8.7, for any users who are relying on it until the PR is accepted. I couldn't find a way to change the source branch for an existing PR, so I created a new one, https://github.com/coq/coq/pull/6033.

Please continue the discussion on the new PR. I'll close this one.

**Comment by ejgallego** [comment]
Thanks!

**Pull request closed without merging**
