### PR TITLE
Merging the code paths for fixpoint and cofixpoints

### PR DESCRIPTION
**Pull request by herbelin**
This is the second part of #18811.

The merge is obtained by using a data type `recursion_order_expr` that tells if an optional `struct`/`wf`/`measure` (as in `Fixpoint`) or a corecursion (as in `CoFixpoint`) or an unknown cause of recursion (as in `Theorem with`). This is then interpreted as a `possible_guard` (which can be either a recursion or a corecursion, thanks to #18743).

Depends on:
- #19105

Synchronous overlays:
- ejgallego/coq-lsp#792
- uds-psl/autosubst-ocaml#17

### CODE REVIEW

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
Certainly a nice cleanup we want to merge in master but no particular need to get it in 8.20, postponing the milestone.

**Review by SkySkimmer — APPROVED** [review]

**Comment by herbelin** [comment]
Rebased to restart CI.

**Comment by herbelin** [comment]
At first view, the CI failures are the standard current ones.

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
