### PR TITLE
Define Makefile.dune partial targets for every theories/ subdirectory

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
The names of the targets should get a prefix so as to be (potentially) conflict-free and easier to predict. Maybe a pattern like `stdlib-FOO` or something?

**Comment by SkySkimmer** [comment]
Let's go with `theories-foo`

**Comment by ejgallego** [comment]
Note that we could actually define an alias in Dune for this, see https://dune.readthedocs.io/en/stable/usage.html#aliases 

This way, we could just do `dune build @theories/Arith/vo-files` , or pick your own one.

This is in my to-do list for dune, but it wouldn't hurt to submit a feature request.

**Review by ejgallego — APPROVED** [review]
My make hackery cannot really understand this, but trusting GG.

**Pull request merged**
