### PR TITLE
ci-fiat_crypto: try setting -async-proofs-tac-j 0

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
https://gitlab.inria.fr/coq/coq/-/jobs/3597073 got 
~~~
File "./src/Curves/Weierstrass/Projective.v", line 129, characters 6-60:
Error: Anomaly "Worker failed (for goal 21)"
~~~
then it passed in the backup make call.

**Comment by SkySkimmer** [comment]
Rerunning the job to see if it keeps working

**Comment by ppedrot** [comment]
Why not 0 so as to skip par altogether?

**Comment by JasonGross** [comment]
Don't we want some test of `par:` on the CI?

**Comment by ppedrot** [comment]
Maybe fiat-crypto the memory-eating ogre is not the best candidate to test the par: feature...

**Comment by SkySkimmer** [comment]
trying -j 0

**Comment by SkySkimmer** [comment]
https://gitlab.inria.fr/coq/coq/-/jobs/3620537 worked, rerunning

**Comment by SkySkimmer** [comment]
It failed. Top real times:
~~~
      Time |   Peak Mem | File Name                                                                                              
---------------------------------------------------------------------------------------------------------------------------------
218m07.22s | 2970764 ko | Total Time / Peak Mem                                                                                  
---------------------------------------------------------------------------------------------------------------------------------
 37m05.29s | 1637376 ko | SlowPrimeSynthesisExamples.vo                                                                          
 11m36.96s | 1085256 ko | UnsaturatedSolinasHeuristics/Tests.vo                                                                  
 11m09.95s | 2278716 ko | Bedrock/End2End/X25519/GarageDoor.vo                                                                   
  7m29.94s | 2970764 ko | Curves/Weierstrass/AffineProofs.vo                                                                     
~~~
Weierstrass/AffineProofs got killed while SlowPrimeSynthesisExamples was running then succeeded in the retry.
Almost 3GB indeed seems too much for parallel execution...

**Pull request closed without merging**
