### PR TITLE
Fix overlay system when used locally (out of CI)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
I was workarounding this locally using my own git tooling [which I hope can push some day]

Seems fine to me.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by ejgallego** [comment]
> @ejgallego: Please take care of the following overlays:
> 
> * README.md

lol

**Comment by Zimmi48** [comment]
Yeah, sorry about that. The overlay detection system is very basic and I've not invested time in improving it yet.

**Comment by ejgallego** [comment]
> Yeah, sorry about that. The overlay detection system is very basic and I've not invested time in improving it yet.

No worries about that at all, IMHO not worth to handle that, I just found it funny.

**Pull request merged**
