### PR TITLE
Allows a level in the raw and glob printers 

### PR DESCRIPTION
**Pull request by herbelin**
We offer the possibility to use a level also for raw and glob printers and not only for top printers as in #6047.

This is the "feature" part out of #6113 (it still includes #6113 but I guess this will be recognized as already existing at the time of merge).

### CODE REVIEW

**Comment by Zimmi48** [comment]
@herbelin @ppedrot This PR is apparently breaking Ltac2.

**Comment by ppedrot** [comment]
@Zimmi48 Probably a minor breakage, I'll have a look. That said, this printing implementation looks more and more like a *usine à gaz*, I think we should have cleaned up the printing API before trying to fix the precedence issues.

**Comment by herbelin** [comment]
> That said, this printing implementation looks more and more like a usine à gaz, I think we should have cleaned up the printing API before trying to fix the precedence issues.

Yes, it is a bit like a usine à gaz. Anyway, this is not exclusive. I'd be happy to see a cleaned printing API.

**Comment by maximedenes** [comment]
The overlay looks suspicious.

**Comment by herbelin** [comment]
> The overlay looks suspicious.

Indeed, lol! Fixed.

**Comment by Zimmi48** [comment]
There seems to be an issue with Equations:

```
File "src/equations_common.ml", line 183, characters 14-34:
Error: Unbound value Evd.const_univ_entry
```

**Comment by Zimmi48** [comment]
Or is it some known problem? @mattam82?

**Comment by SkySkimmer** [comment]
Sounds like travis didn't merge #1033.

**Comment by maximedenes** [comment]
I believe this is a non-backward compatible overlay which was merged in Equations after another PR. So it should be fine.

**Comment by mattam82** [comment]
Hmm, doesn't it just mean that this PR should be rebased on master? Does travis tests the merge or the PR commit?

**Comment by Zimmi48** [comment]
Yes Travis is supposed to use the latest merge, but sometimes it takes a bit of time to get it.
See here https://travis-ci.org/coq/coq/jobs/307991514#L702-L723

**Comment by maximedenes** [comment]
It tests the merge, but that was done too long ago, due to the back log. We could close and reopen if we want to.

**Comment by mattam82** [comment]
I see

**Comment by Zimmi48** [comment]
I would advise against closing / reopening or rebasing. Just relaunching the failed build should be sufficient.

**Comment by maximedenes** [comment]
> That said, this printing implementation looks more and more like a usine à gaz, I think we should have cleaned up the printing API before trying to fix the precedence issues.

@ppedrot Are you ok with merging this, nonetheless?

**Comment by ppedrot** [comment]
@herbelin Do you have another motivation that printing properly `intros **`?

**Comment by herbelin** [comment]
The `intros **` printing is unrelated. I fall on a need for a raw/glob level but I don't remember which it was.

**Comment by ppedrot** [comment]
I'm OK for merging anyways.

**Pull request merged**
