### PR TITLE
Warn when minimizing inductive to set even though minim to set is off

### PR DESCRIPTION
**Pull request by SkySkimmer**
This should be backported to ease the change in #17795

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Failures should be approximately the ones needing overlays in https://github.com/coq/coq/pull/17795

**Comment by SkySkimmer** [comment]
It worked

@gares this must be in 8.18 to be any use.

**Comment by gares** [comment]
The please get a review and merge quickly
ping @coq/vernac-maintainers

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
This piece of code is in my ballpark since I've (unfortunately) fiddled quite a bit with ComInductive internals, so I'll assign.

**Comment by ppedrot** [comment]
Just in case @coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
