### PR TITLE
Extract and consolidate new refman page on reasoning with inductive types.

### PR DESCRIPTION
**Pull request by Zimmi48**
As I understand it, @jfehrle is not actively working on #14179 because finishing the visual debugger is his current priority. While delaying documentation PRs for after the branching point is generally fine, the problem is that this PR won't be backportable if it contains any merge commit, as we usually do for preserving git history when restructuring the manual. Therefore, I open the current PR with the minimal changes to proceed with the new page creation. I can take care of rebasing #14179 (and #14174) when this one is merged.

### CODE REVIEW

**Review by jfehrle — APPROVED** [review]
Looks good.  I did not read every word :-) but the number of lines added and deleted is about the same.  The TOC in the rendered doc seems fine.  And breaking up the enormous tactics chapter is wonderful!  Shall I go ahead and merge ASAP?  I can't think of a reason to wait.

I don't expect to do anything more on #14179 until early June, and indeed I'm giving priority to getting the debugger finished for 8.14.

**Comment by Zimmi48** [comment]
>Shall I go ahead and merge ASAP?

Yes, thanks!

**Comment by jfehrle** [comment]
@coqbot: merge now

**Comment by jfehrle** [comment]
Your plan is to rebase 14179 immediately or just prior to merging it?  (Just in case I spend time on that sooner than anticipated.)

**Comment by Zimmi48** [comment]
I plan on doing it ASAP although probably not today.

**Pull request merged**
