### PR TITLE
Switch default locality for TC transparency to Export + followup cleanup

### PR DESCRIPTION
**Pull request by SkySkimmer**
It has been warning since 8.15.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I actually planned to do that for quite a while...

**Comment by ppedrot** [comment]
Some people are seemingly ignoring their warnings... Maybe we should have a version with this warning an error by default before changing the default behaviour?

**Comment by SkySkimmer** [comment]
>Maybe we should have a version with this warning an error by default before changing the default behaviour?

I don't think that's particularly useful.

**Comment by SkySkimmer** [comment]
Actually the category theory failure is due to a change in equations, should be fixed now
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
