### PR TITLE
Remove the Template Check option.

### PR DESCRIPTION
**Pull request by ppedrot**
Mostly an experiment for the CI right now, but will become relevant when Coq89.v goes away after the 8.12 branch.

### CODE REVIEW

**Comment by ppedrot** [comment]
Judging from the fact our CI passes with a 2-line backward compatible overlay, I am turning this from draft to actual PR.

**Comment by Zimmi48** [comment]
`Coq89.v` goes away *before* the 8.12 branch (cf. #11551).

Regarding the `Template Check` flag, I believe @JasonGross had some reason for wanting to preserve it until some things were supported, but he'll explain better than I can.

**Review by Zimmi48 — COMMENTED** [review]
Wait for #11551 to be merged first.

**Comment by ppedrot** [comment]
@Zimmi48 the other PR is likely to need more overlays.

**Comment by Zimmi48** [comment]
Oh, but I see you've already had this discussion on Gitter: https://gitter.im/coq/coq?at=5e3da4bc63c15921f465f24f

>the other PR is likely to need more overlays.

I bet it doesn't. I don't think we have any project in CI relying on `-compat 8.9`.

**Comment by ppedrot** [comment]
@Zimmi48 well at least it will require mit-plv/fiat#33, so you should probably add this overlay to the other PR.

**Comment by ejgallego** [comment]
It doesn't require the overlay, that's what I meant on Gitter, so this PR is altering the semantics beyond what the flag does.

**Comment by ppedrot** [comment]
@ejgallego the reason is that somehow fiat is generating the `src/Common/Coq__8_4__8_5__Compat.v` file that contains a global unset of the `Template Check` option. I don't really understand how the script generating this works (@JasonGross?) but even on PR #11551 the line removing the option appears. So even without the Coq 8.9 compat file it will generate buggy template inductive types.

**Comment by ppedrot** [comment]
Bottom line: this PR does not change the semantics without the flag.

**Comment by ejgallego** [comment]
@ppedrot I thought I had indeed checked that the flag was actually set when compiling locally, but I likely messed up; merging this anyways as to set `master` to 8.10 compat-level.

**Comment by ejgallego** [comment]
> @ppedrot I thought I had indeed checked that the flag was actually set when compiling locally, but I likely messed up; merging this anyways as to set `master` to 8.10 compat-level.

Sorry I meant to say will merge https://github.com/coq/coq/pull/11551 not this

**Comment by JasonGross** [comment]
@ppedrot the file is copied from https://github.com/JasonGross/coq-scripts/blob/master/compatibility/Coq__8_12__Compat.v (or the equivalent one for whatever version of Coq is currently being used).  That file is itself generated by https://github.com/JasonGross/coq-scripts/blob/master/compatibility/generate-compat-files.sh (but the generated files are checked in); this is what I have to modify to support new version numbers.  The Temple Check option is grabbed from https://github.com/JasonGross/coq-scripts/blob/master/compatibility/fragments/Grab88v811.v, which I wrote by hand.

**Comment by ppedrot** [comment]
Anyways, since the removal of the compat file and the fiat-parser upstream fix, I think this is good to go. It needs a reviewer / assignee, @SkySkimmer maybe?

**Review by SkySkimmer — APPROVED** [review]
I intend to merge tomorrow unless someone complains.

**Comment by herbelin** [comment]
> I intend to merge tomorrow unless someone complains.

I'm approving the PR: this option is an ad hoc flag which has to go away. 

I'm sorry not to have followed closely the subtle work done over the last year on this matter, but, while we are at it, could someone kindly remind where we are in the process of subsuming template polymorphism into full polymorphism and what are the next steps? In particular:

- Is there still something missing so that `type_of_inductive_knowing_parameters` is technically simulatable by an appropriate instantiation of universe variables?
- Is it agreed or debated that including `Prop` (at least optionally) in the polymorphic quantification over universe levels is eventually worth to be supported?

In relation with this last point, @letouzey and I actually started to investigate a theory with explicit subtyping from `Prop` to `Type` allowing extraction to track when the minimal sort of a type changes from `Type` to `Prop` by application, and I would be happy to share where we are.

**Comment by ppedrot** [comment]
@herbelin the major problem with getting rid of template polymorphism is not so much the kernel than porting all the code that only works in monomorphic mode. This is the case for most of the plugins, and that's a *lot* of code.

**Comment by herbelin** [comment]
> @herbelin the major problem with getting rid of template polymorphism is not so much the kernel than porting all the code that only works in monomorphic mode. This is the case for most of the plugins, and that's a _lot_ of code.

Interesting, I did not pay attention to that! Are you talking about `firstorder`, `cc`, etc. Are you talking about uses of template polymorphism on `prod`, `sig`, `list`, `option`?

So, to be sure I understand correctly, if we now set e.g. `list` and `option` polymorphic, many plugins break?

**Comment by ppedrot** [comment]
> So, to be sure I understand correctly, if we now set e.g. list and option polymorphic, many plugins break?

Yes.

**Comment by herbelin** [comment]
> > f we now set e.g. list and option polymorphic, many plugins break?
>
> Yes

Sorry to insist, but in order to know where we need to make the next progresses, can the name of such plugins be given? Ok, sure, I can try and recompile myself to see which ones, but that may be useful to write black-on-white where we aim/want/have to go (or don't if too costly).

**Comment by ppedrot** [comment]
@herbelin grepping for `constr_of_monomorphic_global` should give a rough idea of the incriminated plugins. For me, this gives
```
btauto
funind
micromega
nsatz
omega
rtauto
setoid_ring
ssr
```

Note that the amount of lines this appears is decorrelated from the actual work needed, because it is often factorized through helper functions. Also, how to fix that properly is not clear. I have started several times porting those plugins, only to realized I didn't know how to do that in both a clean and efficient (performance-wise) way.

**Comment by herbelin** [comment]
> grepping for `constr_of_monomorphic_global` should give a rough idea of the incriminated plugins.

Thanks a lot!

> Also, how to fix that properly is not clear. 

Do you mean e.g. between fixing some universe levels globally for a whole run of `ring` or `lia`, or using fresh variables at every new use of the global, relying on unification for reducing the graph of universes?

> I have started several times porting those plugins, only to realized I didn't know how to do that in both a clean and efficient (performance-wise) way.

I guess that there is no question that it has to be efficient. So, the question is how to preserve efficiency w/o making the code too complicated. What were the issues with that (if ever you have some time to explain)?

**Comment by Zimmi48** [comment]
The doc for this flag was not removed and no changelog entry was added :unamused: I'm taking care of this as part of #11665.

**Pull request merged**
