### PR TITLE
[stdlib] [init] deprecate `identity` in favour of `eq`

### PR DESCRIPTION
**Pull request by olaure01**
The two inductives `identity` and `eq` happen to be the same, both living in `Prop`.
We deprecate `identity`. After that, the only remaining definition in `Init.Logic_Type` being `notT`, we move it to `Init.Logic` and remove the `Init.Logic_Type` file.

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.
- [x] Opened **overlay** pull requests.
  - coq-community/paramcoq#87
<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
I'm curious to see if this breaks anything in the CI.

**Review by Blaisorblade — APPROVED** [review]

**Comment by Alizter** [comment]
The overlay looks simple, just remove the import of `Logic_Type`.

**Comment by ppedrot** [comment]
Wait, are those both template polymorphic or what?

**Comment by ppedrot** [comment]
I just checked and indeed those two types are not completely equivalent. While `eq` is really in `Prop`, `identity` is template polymorphic. I am not sure that the good solution is to remove it since the motivation was to have a part of the stdlib compatible with the HoTT library (I think, cc @herbelin ?). If anything this highlights the annoying bug that inductive definition tries to read your mind regarding the arity of the type. We should probably fix this instead. (See also #14471 for a little museum of horrors.)

**Comment by Blaisorblade** [comment]
But if HoTT and Unimath aren’t using it and @Alizter doesn’t see a point to it, what’s `identity` good for? If it were submitted today, would you accept the PR? Without a compelling use case, I’d say no. “Some compatibility with HoTT” seems weak.

**Comment by Alizter** [comment]
@ppedrot Both HoTT and Unimath avoid using the stdlib. HoTT used to have a copy of the init, but that was later rid of.

**Comment by herbelin** [comment]
>  I am not sure that the good solution is to remove it since the motivation was to have a part of the stdlib compatible with the HoTT library (I think, cc @herbelin ?). 

As `-indices-matter` is not retroactive, `identity` lands in `Prop` in any case. So I'm unsure to see an interest in keeping it for itself (unless moving to `-indices-matter` by default, see below).

> Both HoTT and Unimath avoid using the stdlib

Let me by the way point to this [comment](https://hott.zulipchat.com/#narrow/stream/235257-coq-HoTT/topic/other.20Coq.20libraries) on HoTT zulip. Is there anything that can be done to share more contents between HoTT and (some of) the standard library?

Among possible strategies, there was the idea to rethink Coq's Type(n) as HoTT's hSet(n) and to add a new sort, say Univ(n), to mean Type(n) in HoTT sense. Then, Coq's `eq` would be in `Prop` even under HoTT's eye, `-indices-matter` could be activated by default, and `identity` would make sense again as the family of equalities over HoTT's Type(n). I'd be curious to hear more comments about this proposal.

**Comment by Blaisorblade** [comment]
@herbelin That might be a FAQ but too speculative for this MR; we should not keep almost-dead code because it might become useful — and who knows if you'd want separate equalities in that kind of stdlib.

Especially, if we can't remove something with so little use, it feels like we can't ever remove anything from the stdlib.

**Comment by Alizter** [comment]
Will merge this soon

**Comment by olaure01** [comment]
Isn't it better to wait for the merging of coq-community/paramcoq#87?

**Comment by Zimmi48** [comment]
Indeed, since the overlay is backward compatible, it should be merged first.

**Comment by herbelin** [comment]
> @herbelin That might be a FAQ but too speculative for this MR; we should not keep almost-dead code because it might become useful — and who knows if you'd want separate equalities in that kind of stdlib.

Sure, I'm not advocating for keeping `identity`. What I was trying to trigger is rather a path towards having `-indices-matter` available by default.

**Comment by Alizter** [comment]
@herbelin I've been experimenting with -indices-matter by default today. I have made a draft: #15260

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
