### PR TITLE
Elimschemes cleanup

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
See also https://github.com/coq/coq/pull/18299/#issuecomment-1910364748

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
Simplified PR to only simple cleanup commits, the more complex changes are redundant with the new state of https://github.com/coq/coq/pull/18299

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
