### PR TITLE
Direct implementation of Ascii.eqb and String.eqb (take 2)

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** feature

Supersedes #6948
Closes #6948

Do we need any of these?
- [ ] Added / updated test-suite
- [ ] Corresponding documentation was added / updated
- [x] Entry added in CHANGES.

### CODE REVIEW

**Review by herbelin — COMMENTED** [review]
OK to me. If there are specific questions, I can take a closer look, otherwise trusting the maturation of the predecessor of the PR.

**Review by maximedenes — APPROVED** [review]
Extraction files look ok.

**Comment by maximedenes** [comment]
@herbelin is the natural owner here.

**Comment by JasonGross** [comment]
Rebased to retry ci-cross-crypto, which was failing at https://gitlab.com/coq/coq/-/jobs/81764255 with a connection error.

**Comment by Zimmi48** [comment]
@JasonGross You can also apply to join the https://gitlab.com/coq organization to have the ability to restart single failed jobs by yourself (cf. https://github.com/coq/coq/blob/master/dev/doc/MERGING.md#merging).

**Comment by JasonGross** [comment]
@Zimmi48 How do I join?  (In this case, I wanted to leave the failed log around for https://github.com/coq/bot/issues/9, but it'd be nice to be able to do that myself in the future)

**Comment by JasonGross** [comment]
Oh, I found it, I think the answer was "I need to be logged into gitlab to request access"

**Comment by Zimmi48** [comment]
> In this case, I wanted to leave the failed log around for coq/bot#9, but it'd be nice to be able to do that myself in the future

GitLab CI is more sensible than Travis and do not remove the previous logs when you retry a job.

**Comment by herbelin** [comment]
OK, shall merge Monday late.

**Pull request merged**
