### PR TITLE
Add check for inductive privacy in kernel

### LINKED ISSUE #9608: `Private Inductive` does not prevent generating a match
I believe the following should not be accepted:

```coq
Module M.
Private Inductive foo := C : foo -> foo.
End M.

Scheme Induction for M.foo Sort Prop.
```

I'm very surprised because privacy is seen by the kernel, so how come it can be circumvented?

### PR DESCRIPTION
**Pull request by SkySkimmer**
Backward compatible overlay https://github.com/HoTT/HoTT/pull/1006

Fix #9608

### CODE REVIEW

**Comment by maximedenes** [comment]
Should fix #9608.

**Comment by ppedrot** [comment]
FTR, rewrite rules in the Coq kernel might land sooner than what we think, and they would allow to implement HITs without relying on this kind of hacks...

**Comment by maximedenes** [comment]
@SkySkimmer what's the status of this?

**Comment by SkySkimmer** [comment]
Looks like CI failed spuriously, AFAIR it was ready
I need to look at the HoTT side discussion again though

**Comment by maximedenes** [comment]
Sounds good, let me know when you want me to act on this.

**Comment by SkySkimmer** [comment]
Don't have time/motivation to figure this out further.

**Pull request closed without merging**
