### PR TITLE
Mention template polymorphism in the documentation.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Since About mentions it the doc should as well.

### CODE REVIEW

**Comment by matej-kosik** [comment]
I am not sure if this is the right fix to the problem.

Are there cases when Coq implementation itself uses the term _sort polymorphism_? If not, maybe instead of introducing an alternative name, we might want to drop the name _sort polymorphism_ and simply just use _template universe polymorphism_ directly in the Reference Manual?

What do you think ( @herbelin @mattam82 )?

**Comment by herbelin** [comment]
Either is fine for me. Sort polymorphism and template polymorphism look equally intelligible to me in themselves. An advantage of template polymorphism would be the analogy with c++ template polymorphism. Sort polymorphism would give a more "type theory" feeling. Are there other connections to mention relative to the usage of one or the other terminology in the general cultural background of a Coq user?

In any case, I agree with @matej-kosik, it should be called the same in the manual and in About, and the manual should just add a "(also called machin polymorphism)" somewhere to help the reader in connecting the two terminology usages.

Who else has an opinion or additional useful information to give? Then, we may let @mattam82 do the final choice.

**Comment by herbelin** [comment]
Let me finally express an opinion: I feel that _template polymorphism_ is better. It expresses stronglier the difference between _universe polymorphism_ and the kind of polymorphism that inductive types have in the absence of the Polymorphic keyword, than _sort polymorphism_. So, I would advocate to change the reference manual by using _template polymorphism_ as the primary terminology.

**Comment by SkySkimmer** [comment]
So what should I do?
@mattam82 ?

**Comment by mattam82** [comment]
I agree with Hugo's last comment, I also think it's easier to distinguish template polymorphism from universe polymorphism.

**Comment by SkySkimmer** [comment]
There are a few comments which use "Sort-polymorphism of inductive types" (eg https://github.com/coq/coq/blob/trunk/pretyping/typing.ml#L226 or https://github.com/coq/coq/blob/trunk/test-suite/failure/proofirrelevance.v) as well as some old CHANGES/whodidwhat/RefMan-pre entries.
I'm leaving all of them alone unless someone disagrees.

**Comment by herbelin** [comment]
@SkySkimmer: In the code it is maybe as good to do the replacement, or at worst to say "template polymorphism, also known  formely as sort-polymorphism of inductive types". In the CHANGES and co, we cannot indeed revise history. But the next whodidwhat can explain the change of terminology (if we succeed in not forgetting to do it).

**Comment by SkySkimmer** [comment]
Updated most comments found by grepping.
Also changed RefMan-pre.tex, in a separate commit in case that's the wrong thing to do.

The comment https://github.com/coq/coq/blob/trunk/test-suite/success/polymorphism.v#L263 is a remnant from dfe9772 testing how template polymorphism of prod interacts with sections, but a404360 turned the whole file into a test of universe polymorphism.
I'm not sure what I should do with it. Do I remove the comment, turn the section back into a template polymorphism test, or just remove it?

From comments I found 1 test of template polymorphism at https://github.com/coq/coq/blob/trunk/test-suite/success/Inductive.v#L167, maybe more should be added.

**Comment by SkySkimmer** [comment]
And rebased to deal with econstr conflicts.

**Comment by SkySkimmer** [comment]
Is there anything stopping this?

**Comment by maximedenes** [comment]
That looks good to me! @herbelin, @mattam82, is the current state satisfactory for you too?

**Comment by herbelin** [comment]
Maybe would it be worth in `doc/refman/RefMan-cic.tex` to add a remark in the `Template polymorphism` section, that "template polymorphism was formerly called sort-polymorphism of inductive types before universe polymorphism (see  Section ...) was introduced.".

I have no idea how people could get confused by the change. Maybe "Sort-polymorphism of inductive types" should be kept in the index pointing to the remark. On the other side, keeping it make the index referring to information destined to become useless. So, let's try without keeping it in the index.

**Comment by SkySkimmer** [comment]
@herbelin like this?

**Comment by herbelin** [comment]
@SkySkimmer:Obviously you checked yourself the rendering. At least it looks ok from reading the source. Thanks!

**Comment by SkySkimmer** [comment]
bump

**Comment by maximedenes** [comment]
Merged. Thanks and sorry for the delay.

**Pull request merged**
