### PR TITLE
[build] Ensure `dune install` is called with the right root detection options

### LINKED ISSUE #15044: Cannot install coq 8.14.0 in local switches inside directories with dune-project
#### Description of the problem

This seems to be a similar problem as https://github.com/coq/coq/issues/14915 but for Coq 8.14.0. I get the following error if I try to install Coq 8.14.0 in a switch inside a directory with a `dune-project` file:

```
$ cat dune-project                                                       
(lang dune 2.7)
(name test)
(using coq 0.2)
(using menhir 2.1)
$ opam pin coq 8.14.0
[NOTE] Pinning unchanged
coq is now pinned to version 8.14.0

The following actions will be performed:
  ∗ install coq 8.14.0*
Do you want to continue? [Y/n] y

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⬇ retrieved coq.8.14.0  (cached)
[ERROR] The installation of coq failed at "make COQ_USE_DUNE= install".

#=== ERROR while installing coq.8.14.0 ========================================#
# context     2.1.0 | linux/x86_64 | ocaml-base-compiler.4.11.1 | pinned(https://github.com/coq/coq/archive/refs/tags/V8.14.0.tar.gz)
# path        /tmp/test_opam/_opam/.opam-switch/build/coq.8.14.0
# command     /usr/bin/make COQ_USE_DUNE= install
# exit-code   2
# env-file    /local/home/mackie/.opam/log/coq-14082-b9c925.env
# output-file /local/home/mackie/.opam/log/coq-14082-b9c925.out
### output ###
# /usr/bin/make --warn-undefined-variable --no-builtin-rules -f Makefile.build install
# make[1]: Entering directory '/tmp/test_opam/_opam/.opam-switch/build/coq.8.14.0'
# DUNE      sources
# dune install --display quiet  --mandir=""/tmp/test_opam/_opam/man"" --prefix="/tmp/test_opam/_opam" coq-core
# Entering directory '/tmp/test_opam'
# Error: Unknown package coq-core!
# make[1]: *** [Makefile.install:56: install-dune] Error 1
# make[1]: Leaving directory '/tmp/test_opam/_opam/.opam-switch/build/coq.8.14.0'
# make: *** [Makefile.make:122: submake] Error 2
```

#### Coq Version

Tested with 8.14.0.

### PR DESCRIPTION
**Pull request by ejgallego**
Should fix #15044

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
Version for 8.14 can be found at https://github.com/ocaml/opam-repository/pull/19808

**Comment by silene** [comment]
There are too many differences between master and 8.14 to backport this pull request. Will make a dedicated pull request.

**Comment by ejgallego** [comment]
> There are too many differences between master and 8.14 to backport this pull request. Will make a dedicated pull request.

@silene the path in the opam package should apply cleanly, see my comment above

**Comment by silene** [comment]
Yes, that is my point. I backported the one from the Opam package, not this pull request.

**Pull request merged**
