### PR TITLE
Missing changelogs added between 8.16+rc1 and 8.16.0.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by Alizter** [comment]
By the way, I noticed a mistake in one of the changelogs:

>Added: A deprecation warning that the [:g:`Class >`](https://github.com/ppedrot/coq/blob/changelog-8.16.0/doc/sphinx/changes.rst#id199) syntax, that is currently doing nothing, will in the future declare

It should be "which is currently doing nothing"

**Comment by Zimmi48** [comment]
> By the way, I noticed a mistake in one of the changelogs:
> 
> > Added: A deprecation warning that the [:g:`Class >`](https://github.com/ppedrot/coq/blob/changelog-8.16.0/doc/sphinx/changes.rst#id199) syntax, that is currently doing nothing, will in the future declare
> 
> It should be "which is currently doing nothing"

@Alizter if you open a PR fixing this, I can take care of merging it.

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Comment by jfehrle** [comment]
>> @Alizter Added: A deprecation warning that the [:g:`Class >`](https://github.com/ppedrot/coq/blob/changelog-8.16.0/doc/sphinx/changes.rst#id199) syntax, that is currently doing nothing, will in the future declare

> It should be "which is currently doing nothing"

Better "which currently does nothing".  No need to use a progressive verb.

I can't find this changelog in master.

**Pull request merged**
