### PR TITLE
Slight simplification of Indtyping.get_template logic

### PR DESCRIPTION
**Pull request by SkySkimmer**
The entry having Template_ind_entry forces TemplateArity, so we don't
need to check.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I think you could even enforce more invariants by tweaking `abstract_packets` but this will do for the time being.

**Comment by ppedrot** [comment]
Will merge when CI finishes.

**Comment by ppedrot** [comment]
elpi looks like it's not happy...

**Comment by SkySkimmer** [comment]
Same in master https://gitlab.com/coq/coq/-/jobs/1612557142n waiting for https://github.com/LPCIC/coq-elpi/pull/289

**Comment by ppedrot** [comment]
OK. Rewriter failure is unrelated, and there is virtually no chance this PR affects it anyway. Let's merge.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
