### PR TITLE
[ci] elpi 1.11.4

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Review by MSoegtropIMC — APPROVED** [review]
LGTM

**Comment by Zimmi48** [comment]
@gares Do you want this in v8.12 as well or not?

**Comment by gares** [comment]
I guess it makes sense

**Comment by gares** [comment]
OSX problem is unrelated

**Review by Zimmi48 — APPROVED** [review]
@coqbot: merge now

**Comment by Zimmi48** [comment]
@coqbot: merge now

**Comment by Zimmi48** [comment]
@gares I get this error on Windows when trying to backport: https://coq.gitlab.io/-/coq/-/jobs/786709601/artifacts/artifacts/buildlogs/elpi-dune-build_err.txt

Do you get what this mean?

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : the opam package for elpi-1-11.4 in the opam MINGW repo does work (last tested yesterday).

**Comment by gares** [comment]
Yes, there is no `shasum` binary installed. In master, and in the patch `-1`, I switched to an approach that requires no external binary.

The short fix is to install `shasum`.
The longer fix is to apply the patch in the windows build as well.

**Comment by Zimmi48** [comment]
Thanks for the feedback! Applying the patch is quite straightforward since the Windows build scripts already provide a mechanism to do so.

**Comment by Zimmi48** [comment]
Actually, @MSoegtropIMC, we have an issue which is that we have `make_elpi` and `make_addon_elpi` which share the name, and because of this the patch is applied to both (making the second build fail). See https://github.com/Zimmi48/coq/commit/88290e8109158adf06d2f527ba671a2fd19360b3 and https://coq.gitlab.io/-/coq/-/jobs/788488283/artifacts/artifacts/buildlogs/elpi-v1.5.1-patch_log.txt.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : in this case one should give an explicit module name which is unique. See the parameters to build_prep at

(https://github.com/coq/coq/blob/411025844a4c005ce03d77c6c640807c28269d4a/dev/build/windows/makecoq_mingw.sh#L339-L358)

The parameter $5 should be unique for every module - otherwise strange things might happen e.g. with managing installer dependencies. But you can also control the base name of patches separately with parameter $6. I guess I messed this up originally.

**Comment by Zimmi48** [comment]
Thanks. For the backport, I've renamed `elpi` to `elpi-base`, but possibly the better fix for `master` would be for the elpi add-on which to be renamed to `coq-elpi` (but `build_prep_overlay` currently doesn't support this).

**Pull request merged**
