### PR TITLE
[ci] bump elpi to 2.0.x

### PR DESCRIPTION
**Pull request by gares**
Overlay PR:
- https://github.com/LPCIC/coq-elpi/pull/719
- https://github.com/ecranceMERCE/trakt/pull/15
- https://github.com/coq-community/corn/pull/212

### CODE REVIEW

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
All green, but I'd like to wait for https://github.com/ocaml/opam-repository/pull/26974 since elpi 2.0.2 has an embarrassing parsing bug I'd rather avoid having in CI.

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@SkySkimmer would you mind taking this one?

**Comment by gares** [comment]
The real pipeline is here: https://gitlab.inria.fr/coq/coq/-/pipelines/1076550

**Comment by SkySkimmer** [comment]
hb_test is failing

**Comment by gares** [comment]
I fixed upstream, but rerunning it does not check out the new version. If I rerun HB the whole MC ci reruns

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
green!

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
