### PR TITLE
Travis+4.05.0

### PR DESCRIPTION
**Pull request by ejgallego**
Depends on ocaml/opam-repository#9817

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Could you change the gitlab.yml too? (variables   
```
COMPILER_BLEEDING_EDGE: "4.04.1"
CAMLP5_VER_BLEEDING_EDGE: "6.17"
```
near the top)

**Comment by ejgallego** [comment]
Done.

**Comment by ejgallego** [comment]
Ok if Travis passes this should be ready to go.

**Comment by SkySkimmer** [comment]
Not working on gitlab, I think it may need an `opam update` in the script or something.
Will look into it tomorrow.

**Comment by SkySkimmer** [comment]
Adding `opam update` allows installing 4.05 but then I get `[ERROR] No package matches camlp5.7.01.` https://gitlab.com/SkySkimmer/coq/-/jobs/22643651
I think the repository lists are locally installed in the docker used by gitlab, and it got updated ~2 hours before the camlp5 PR got merged.
I don't know how often that image (https://hub.docker.com/r/ocaml/opam/) gets updated.

**Comment by SkySkimmer** [comment]
The docker was updated but it still doesn't work https://gitlab.com/SkySkimmer/coq/-/jobs/22969245
I have no idea why.

Maybe I shouldn't use the opam image and just install opam on a debian base image.

**Comment by ejgallego** [comment]
It looks indeed like the repos has not been updated, you could try to insert an `opam list -a` to see what is going on; another solution could be to unpin the local repos and add the remote.

**Pull request merged**
