### PR TITLE
deprecate Zmod

### PR DESCRIPTION
**Pull request by andres-erbsen**
- [x] Added **changelog**.

### CODE REVIEW

**Review by JasonGross — APPROVED** [review]
Edit: I missed the changelog since the box was not checked in the PR description<strike>I think it's probably worth adding a changelog entry, but otherwise</strike> this looks good

**Comment by andres-erbsen** [comment]
I checked the box after I pushed the commit with the changelog after I downloaded the PR number after I created to PR.

**Comment by JasonGross** [comment]
I don't think we actually need a full CI on this, since it's only adding depression warnings

**Comment by Zimmi48** [comment]
Are you self-assigning @JasonGross?

**Comment by JasonGross** [comment]
@coqbot run full ci

**Comment by JasonGross** [comment]
If no one objects and CI passes, I will merge in about 24h

**Comment by JasonGross** [comment]
(running full ci as per https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs-.26-plugin-devs/topic/full.20CI.20on.20innocuous.20PRs)

**Comment by Zimmi48** [comment]
Yes, unfortunately, you'll need to wait for #16895 to get merged before you can run the full CI usefully.

**Comment by Zimmi48** [comment]
@coqbot run full CI

**Comment by andres-erbsen** [comment]
The failures are not deprecation warnings as errors; they look like running out of memory.

**Comment by andres-erbsen** [comment]
I am not sure what is causing this repeated CI failure, but I don't see how it would be this PR (I'm not sure what [this comment](https://github.com/coq/coq/pull/16801#issuecomment-1326421117) is about.
```coq
Command terminated by signal 9
src/Curves/Weierstrass/AffineProofs.vo (real: 81.60, user: 2.59, sys: 0.52, mem: 1421804 ko)
```
The [source line](https://github.com/mit-plv/fiat-crypto/blob/master/src/Curves/Weierstrass/AffineProofs.v#L48) does not do anything related.

Can we merge?

**Comment by Zimmi48** [comment]
>I'm not sure what [this comment](https://github.com/coq/coq/pull/16801#issuecomment-1326421117) is about.

The comment is not relevant anymore, but you can indeed exclude that such a change would trigger such an error.

**Comment by JasonGross** [comment]
@coqbot merge now

**Comment by JasonGross** [comment]
> @coqbot merge now

**Pull request merged**
