### PR TITLE
[api] Split API in logical files.

### PR DESCRIPTION
**Pull request by ejgallego**
We split the API in their "logical" components to ease the handling of
the API.mli file, and hopefully facilitate the life of each subsystem
maintainer.

This commit is not yet ready, but it already makes the coupling
between components more explicit, and indeed from small experiments I
can attests that the coupling could be greatly improved with minor
changes to the codebase.

### CODE REVIEW

**Comment by ejgallego** [comment]
Again only the last commit is good for review, sending this in for comments on the approach.

**Comment by ejgallego** [comment]
Indeed, with a bit more of refactoring I could imagine that the large majority of plugins should use only:
```
open Kernel_API
open Engine_API
open Pretyping_API
```
this is considerable smaller than what we currently expose. Maybe in the future we could devise a mechanism so all the plugins get this by default, and the few more than need access to special parts could declare so in their linking options.

**Comment by Zimmi48** [comment]
Having an API per logical component seems like a sensible approach to me except, I guess, I would call it `kernel/API.mli` instead of `API/kernel_API.mli`...
When you say that the majority of plugins should use:

```
open Kernel_API
open Engine_API
open Pretyping_API
```

I suppose you're not talking about making these `open` explicit.

I have a somehow really really naive question: why only plugins should be put behind such API? Why not the Coq code base as well? (A sort of logical component level opacity.)

**Comment by ejgallego** [comment]
> Having an API per logical component seems like a sensible approach to me except, I guess, I would call it kernel/API.mli instead of API/kernel_API.mli...

Unfortunately as we don't do packing of modules that is not possible currently.

> I suppose you're not talking about making these open explicit.

No, I was thinking of the implicit opens. It was more of  a conceptual idea thou, as now we are far from it.
 
> I have a somehow really really naive question: why only plugins should be put behind such API? Why not the Coq code base as well? (A sort of logical component level opacity.)

Good question, I guess that in the end this is what the goal is. And in fact, due to technical reasons, it could be the case that the final implementation of the API has to do this.

**Comment by ejgallego** [comment]
This is gonna take a long time to get ready due to technical problems, closing for now.

**Pull request closed without merging**
