### PR TITLE
Fix evar sensitivity in subst_defined_metas_evars

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
This one definitely needs a bench. I'll wait for the pipeline to finish to run it.

**Comment by ppedrot** [comment]
@coqbot bench

**Comment by Alizter** [comment]
```
│   0.1160    1.5520  1.4360  1237.93%   339  coq-perennial/src/program_proof/mpaxos/apply_proof.v.html                                                                 
│   0.1690    1.4420  1.2730   753.25%    87  coq-unimath/UniMath/CategoryTheory/Monoidal/AlternativeDefinitions/EquivalenceWhiskeredNonCurriedMonoidalCategories.v.html │
```
Are these just unlucky garbage collections or is something else going on here?

**Comment by SkySkimmer** [comment]
color failed in fetch, probably intermittent network issues

**Comment by ppedrot** [comment]
Both Unimath and Perennial have frequent hiccups in per-line diffs. Since there is no macroscopic effect even in terms of CPU instructions I'm not worried.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
