### PR TITLE
Improved adding of Ltac2 backtraces for externals

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
At BedRock we've come up with the following API for handling backtraces:

```coq
  Ltac2 Type exninfo.

  Ltac2 @ external throw_bt : exn -> exninfo -> 'a :=
    "ltac2_extensions" "throw_bt".

  Ltac2 @ external zero_bt : exn -> exninfo -> 'a :=
    "ltac2_extensions" "zero_bt".

  Ltac2 @ external plus_bt : (unit -> 'a) -> (exn -> exninfo -> 'a) -> 'a :=
    "ltac2_extensions" "plus_bt".
```

It seems to work fine for our use cases.

We also have
```coq
  Ltac2 @ external clear_exn_info : exn -> exn :=
    "ltac2_extensions" "clear_exn_info".
```
but I don't think it is used at all.

**Comment by SkySkimmer** [comment]
@Janno that may be related to https://github.com/coq/coq/issues/10112

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
