### PR TITLE
Points to Flocq official repository.

### PR DESCRIPTION
**Pull request by Zimmi48**
Following comment at https://github.com/coq/coq/pull/6596#issuecomment-358246528.

cc @SkySkimmer @silene

### CODE REVIEW

**Review by silene — APPROVED** [review]

**Review by SkySkimmer — APPROVED** [review]

**Comment by maximedenes** [comment]
Flocq now fails with authentication error.

**Comment by Zimmi48** [comment]
@silene What happened? I could see this repository before but now I'm getting a 404.

**Comment by silene** [comment]
It works fine for me:
```
$ git fetch public
Depuis https://gitlab.inria.fr/flocq/flocq
 * [nouvelle branche] IZR        -> public/IZR
 * [nouvelle branche] flocq-2.2  -> public/flocq-2.2
 * [nouvelle branche] flocq-2.5  -> public/flocq-2.5
 * [nouvelle branche] master     -> public/master
 * [nouvelle branche] noauto     -> public/noauto
 * [nouvelle branche] renaming   -> public/renaming
```

**Comment by SkySkimmer** [comment]
>Depuis https://gitlab.inria.fr/flocq/flocq

The PR has gitlab.com which has no flocq.

**Comment by maximedenes** [comment]
This PR uses gitlab.com, not gitlab.inria.fr.

Note that using gitlab.inria.fr will prevent all our non-Inria contributors to submit PRs against Flocq using the gitlab interface, AFAIK.

**Comment by maximedenes** [comment]
Out of curiosity, @silene, did you consider moving Flocq to a more open platform, which would not make non-Inria contributors second class citizens?

**Comment by silene** [comment]
> which would not make non-Inria contributors second class citizens?

First, the distinction is not between Inria and non-Inria, it is whether someone participates to a project or not. Second, "second-class" is a bit excessive, since the only thing that people outside a project cannot do is to press a button to request a pull. Instead, they have to copy-paste the url to their repository.

**Comment by maximedenes** [comment]
> First, the distinction is not between Inria and non-Inria, it is whether someone participates to a project or not. Second, "second-class" is a bit excessive, since the only thing that people outside a project cannot do is to press a button to request a pull. Instead, they have to copy-paste the url to their repository.

Oh! I wasn't aware of that. I thought, they really could not use the PR interface (with comments, code reviews, etc).

I just created a non-Inria account to try by myself. First, I can't create a Flocq fork ("You have reached your project limit", which is 0 projects). What is the procedure I should follow to create a merge request? Do I have to push a fork of Flocq on gitlab.com?

**Comment by silene** [comment]
> What is the procedure I should follow to create a merge request?

I think you misunderstood me. What I meant is that you just create an issue with the url of your repository (or you send it to me, as did Jason).

**Comment by maximedenes** [comment]
Oh yeah sure, but then it's really what I meant by second-class citizen. Unless gitlab then recognizes it as a merge-request and let's you comment code etc.

In fact, it means that for external contributors, there is not much difference between gforge and gitlab, which is a pity.

**Comment by maximedenes** [comment]
Anyway, back to the main topic: as soon as Travis builds Flocq on this PR, I'll merge.

**Comment by Zimmi48** [comment]
Done here: https://travis-ci.org/Zimmi48/coq

**Pull request merged**
