### PR TITLE
Allow levels not mentioned in the conclusion to be template (typically `eq` is now template poly)

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Does not seem particularly faster or slower
It's interesting that we end up needing 1 less universe for all_stdlib.

**Comment by ppedrot** [comment]
I'd still favour making eq template poly. The fact that it's currently a bit slower will probably be offset by the tweaks to come.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
