### PR TITLE
Fix CoqIDE progress bar.

### PR DESCRIPTION
**Pull request by ppedrot**
This brings back the progress bar feature of CoqIDE after #9279.

### CODE REVIEW

**Comment by vbgl** [comment]
The nix job failing on CI is probably due to cairo being there at version 0.5. I’m working on this.

**Comment by ejgallego** [comment]
> The nix job failing on CI is probably due to cairo being there at version 0.5. I’m working on this.

Yup Cairo support needs both the latest ocaml-cairo and lablgtk3 beta.

**Comment by vbgl** [comment]
Should be fixed after https://github.com/NixOS/nixpkgs/pull/57965 is merged.

**Comment by vbgl** [comment]
I’ve just updated the reference to nixpkgs. CI seems happy now.

**Comment by vbgl** [comment]
Ping secondary code owners @gares @herbelin

**Review by Zimmi48 — APPROVED** [review]

**Comment by gares** [comment]
thanks!

**Pull request merged**
