### PR TITLE
Improve do_split option of typeclass resolution

### PR DESCRIPTION
**Pull request by mattam82**
It used to compute the dependencies of all undefined evars of the
evar_map, while only the dependencies of resolvable evars are necessary (assuming EConstr of course, which ensures that we will catch transitive dependencies through defined evars).

### CODE REVIEW

**Comment by JasonGross** [comment]
Why target master rather than 8.7 for this?

**Comment by mattam82** [comment]
Didn't think of it. Sure why not.

**Comment by mattam82** [comment]
Actually the new policy for bugfixes like these is to not put a milestone and let the RM for the stable (soon to be 8.7 branch) backport it.

**Comment by ppedrot** [comment]
FTR, I already witnessed the evar collection function as an important hotspot in various developments, so this should provide a net gain.

**Comment by mattam82** [comment]
Indeed this is an expensive operation, it could be further improved by maintaining a cache of evar dependencies for each evar , which could also be used for shelve_unifiable and the like, I think that would provide another net gain (we're working on that with @psteckler )

**Comment by maximedenes** [comment]
Are we sure that this is not going to change the behavior in some cases, like a non-resolvable `Evar` instantiated to a resolvable one (or the other way around)? Not all code is `EConstr`-correct yet.

**Comment by ppedrot** [comment]
@maximedenes It doesn't break anything on Travis, so I'd be pretty confident that if we changed the semantics, this is in a very specific corner case.

**Comment by mattam82** [comment]
It has nothing do to with any other code being EConstr'ed than evars_of_evar_info

**Comment by maximedenes** [comment]
> It has nothing do to with any other code being EConstr'ed than evars_of_evar_info

Yep, and that seems ok.

**Comment by maximedenes** [comment]
This is not a fix, but an optimization, though, right?

**Comment by mattam82** [comment]
It fixes a performance problem ;)

**Comment by maximedenes** [comment]
Yeah but then a feature fixes a user need :)

**Comment by mattam82** [comment]
Semantics semantics

**Comment by ppedrot** [comment]
It's a shame though :/

**Comment by maximedenes** [comment]
> It's a shame though :/

What is a shame?!

**Comment by ppedrot** [comment]
That's not going to be merged in 8.7, right?

**Comment by maximedenes** [comment]
> That's not going to be merged in 8.7, right?

Oh, I think we can integrate it. The branch is not fully stable yet, so small optimizations like that are still ok IMHO.

**Comment by Zimmi48** [comment]
Now backported in v8.7.

**Pull request merged**
