### PR TITLE
A common execution path for universe restriction + universe declaration check

### PR DESCRIPTION
**Pull request by herbelin**
The PR redirects the calls to `UState.restrict` on definitions/theorems/fixpoints in `declare.ml` towards a reusable encapsulation `make_univs` of the three functions used to build monomorphic deferred, polymorphic private or regular universe restrictions (still to be done for obligations, Derive, Equations though).

In addtion to the centralization, it ensures that `Set Private Universes` is used when defining an opaque polymorphic non-interactive definition or fixpoint (so assuming that a `sealed` attribute is available).

Depends on:
- #18743
- #18795 
- #19090
- #19091

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by herbelin** [comment]
The category_theory failure is due to the hook receiving the unrestricted uctx instead of the restricted one (in `declare_definition_core` of the second commit). Will double-check that this is done in all cases of application of a hook (i.e. also `declare_possibly_mutual_definition`).

**Comment by herbelin** [comment]
I fixed the ustate for the hook in `prepare_definition` and CI is green.

**Comment by herbelin** [comment]
This PR is a priori ready. Looking for a reviewer.

**Review by SkySkimmer — APPROVED** [review]
seems ok

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Pull request merged**
