### PR TITLE
Revert "[ci-itauto] adds itauto to the CI"

### PR DESCRIPTION
**Pull request by SkySkimmer**
This reverts commit 392c114a8886735054f6f6becf7261c6a66e3399.

The itauto build system is broken, see eg https://gitlab.com/coq/coq/-/jobs/1791724894

cc @fajb

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I was worried about the build system in #15146 but let it pass, it seems not ready in the end.

**Comment by Alizter** [comment]
Why did the CI succeed in #15146 if it is broken?

**Comment by SkySkimmer** [comment]
Because it's broken in a non reliable way.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
I'll merge when the CI finishes.

**Comment by ejgallego** [comment]
Why don't we fix the build system instead?

**Comment by SkySkimmer** [comment]
I looked but it's too complicated/messy for me, and meanwhile it's breaking CI.
IMO we should have low tolerance for broken CI.

**Comment by ejgallego** [comment]
> IMO we should have low tolerance for broken CI.

Sure, if @fajb is interested in using dune to fix these problems I'd be happy to help

**Comment by fajb** [comment]
Can I get some info on the breakage?
I never had any problem on my machine... How weird is the CI environment?

**Comment by SkySkimmer** [comment]
I think it's a problem with -j (the CI uses -j 2)

**Comment by fajb** [comment]
Ok, thanks. 
I have added a .NOTPARALLEL to the Makefile. How can I test?

**Comment by Zimmi48** [comment]
Should we just close this PR and reopen if there is still a problem?

**Comment by SkySkimmer** [comment]
Let's see how it goes.

**Pull request closed without merging**
