### PR TITLE
Non-persistent cache of hints in typeclass resolution.

### PR DESCRIPTION
**Pull request by mattam82**
The cache is rebuilt at each resolution invocation. This seems to have a non-negligible impact on compcert... https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/136/console

```
┌─────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┐
│                     │      user time [s]      │             CPU cycles              │           CPU instructions            │
│                     │                         │                                     │                                       │
│        package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│              coq-sf │   45.18   45.38 -0.44 % │  123648624847  123665003767 -0.01 % │   161325956483   160615248987 +0.44 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│           coq-flocq │   55.91   56.03 -0.21 % │  153290002214  152821107850 +0.31 % │   197902095789   197502307515 +0.20 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│ coq-formal-topology │   37.58   37.63 -0.13 % │  101450395411  100991865934 +0.45 % │   138099645734   137902780679 +0.14 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│         coq-unimath │ 1177.54 1176.44 +0.09 % │ 3264022351503 3259147438811 +0.15 % │  5583001174843  5579093582616 +0.07 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│           coq-color │  584.08  581.48 +0.45 % │ 1623195245692 1613357163559 +0.61 % │  2048155954644  2030479524603 +0.87 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│     coq-fiat-crypto │ 2228.94 2218.24 +0.48 % │ 6169706933165 6141392009039 +0.46 % │ 10278400716504 10248188780620 +0.29 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│             coq-vst │ 1309.62 1302.32 +0.56 % │ 3636563231863 3614914725473 +0.60 % │  5366552548472  5364142054567 +0.04 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│          coq-geocoq │ 2178.33 2154.65 +1.10 % │ 6067750240337 5999761147473 +1.13 % │ 10109204021348 10091556004243 +0.17 % │
├─────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┤
│        coq-compcert │  813.50  802.31 +1.39 % │ 2256046010635 2228034839622 +1.26 % │  3402780154711  3401571299898 +0.04 % │
└─────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┘
```

### CODE REVIEW

**Comment by Zimmi48** [comment]
It could be worth doing multiple runs to see what the impact is on average. Maybe a per-file timing would be interesting to have also.

**Comment by ejgallego** [comment]
@mattam82 I assume you consider this preferable to #727, why?

I think there is no technical problem in storing the cache in the summary, if needed.

**Comment by mattam82** [comment]
@ejgallego it makes the resolution more purely functional and avoids marshalling issues.

**Comment by ejgallego** [comment]
Ok, then I should close #727.

Note that we have to deal with marshaling issues already, so IMHO adding the cache to the wouldn't be an additional problem; as @ppedrot pointed out, we could just drop it at marshaling time.

**Comment by mattam82** [comment]
@ejgallego don't close it just yet, it might be the better way to go

**Comment by maximedenes** [comment]
@mattam82 do you still plan to have this ready by tomorrow? if not, please update the milestone.

**Comment by maximedenes** [comment]
@mattam82 ping

**Comment by maximedenes** [comment]
Milestone was never updated, so I'm removing it. @mattam82 please add one that reflects your schedule.

**Comment by ppedrot** [comment]
What is the relation of this PR with #8212?

**Comment by mattam82** [comment]
The two are slightly different. This one is just making the cache of autogoal hints not persist across calls, avoiding issues with side-effects. When you have n goals with the same context it produces only one hint db for that context, shared across all the goals.

**Comment by SkySkimmer** [comment]
Dead PR

**Pull request closed without merging**
