### PR TITLE
Create deployment environment for Cachix.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, thanks!

**Comment by SkySkimmer** [comment]
I haven't looked into gitlab environments, does it work properly on forks?

**Comment by Zimmi48** [comment]
@SkySkimmer Here is an example on my fork where I had the `only` / `except` logic wrong: https://gitlab.com/Zimmi48/coq/-/jobs/153519510

It seems to show that environments "work" on forks (look at the top of the log), but I'm not sure what exactly you had in mind.

**Comment by SkySkimmer** [comment]
Why does nix build findlib and some other stuff by the way? https://gitlab.com/coq/coq/-/jobs/153581000
~~~
...
/nix/store/mnpiwd0lv0xljk7nl5rsmdvcz52xp9j1-ocaml-findlib-1.8.0/bin/ocamlfind ocamldep -package uutf -package uchar -package re -modules lib/xml_iter.mli > lib/xml_iter.mli.depends
...
~~~

**Comment by Zimmi48** [comment]
That could be because we are not using the default OCaml version from this version of nixpkgs. @vbgl might be able to confirm this.

**Review by SkySkimmer — APPROVED** [review]

**Comment by Zimmi48** [comment]
@vbgl #9442 should avoid this, shouldn't it?

**Comment by vbgl** [comment]
You still need to have `odoc` in some cache.

**Comment by Zimmi48** [comment]
Right, but #9442 also updates the public key for Coq's own Cachix which should help to recover this property.

**Comment by vbgl** [comment]
I don’t think you ever push `odoc` in that cache.

**Pull request merged**
