### PR TITLE
Rename VM-related kernel/cfoo files to kernel/vmfoo

### PR DESCRIPTION
**Pull request by SkySkimmer**
See also https://github.com/coq/coq/pull/12848

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
I support this change. Dunno what the "C" prefix stood for before...

**Comment by herbelin** [comment]
> Dunno what the "C" prefix stood for before...

At a time where OCaml did not support files with name clashing with its own files, like `bytecomp/opcodes.ml` (and maybe it is still the case), we got the habits to prefix clashing names with a `c` (standing for `coq`, afaicu).

**Comment by maximedenes** [comment]
> At a time where OCaml did not support files with name clashing with its own files

Isn't it still the case today? If so, isn't the change a bit risky?

**Comment by SkySkimmer** [comment]
The conflicting name is foo not vmfoo

**Comment by maximedenes** [comment]
Ok, no strong opinion on this.

**Review by gares — APPROVED** [review]

**Comment by ppedrot** [comment]
Will merge soon if nobody complains.

**Review by silene — APPROVED** [review]

**Pull request merged**
