### PR TITLE
[RM] V8.18 backports

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coqbot run full ci

**Comment by gares** [comment]
@coq/ci-maintainers I've a problem with this one, the status

**Comment by gares** [comment]
@coqbot run full ci

**Comment by Zimmi48** [comment]
> I've a problem with this one, the status seems wrong, it is spinning yellow but the PR was stuck due to CI infrastructure issues.

Yeah, we don't really have any support for detecting and reporting stuck status. I am unsure if this triggers any sort of webhook.

**Pull request closed without merging**
