### PR TITLE
Factorize goal selector handling

### PR DESCRIPTION
**Pull request by SkySkimmer**
As a bonus ltac2 can produce bullet suggestions.

### CODE REVIEW

**Comment by ppedrot** [comment]
@SkySkimmer You need to add Goal_select to the corresponding mllib.

**Comment by SkySkimmer** [comment]
>@SkySkimmer You need to add Goal_select to the corresponding mllib.
EDIT: actually you also need to move it to engine/.

It only needed reordering in the proofs.mllib afaict

**Review by ppedrot — APPROVED** [review]
Fairly straightforward.

**Comment by ppedrot** [comment]
Merging soon, this is essentially moving code around.

**Pull request merged**
