### PR TITLE
values.ml use Proxy instead of direct recursive values everywhere

### PR DESCRIPTION
**Pull request by SkySkimmer**
cc @ppedrot

### CODE REVIEW

**Comment by ppedrot** [comment]
The concept looks nice, but is there a way to check that this does not wreak havoc with the physical equality cache for validation introduced recently?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
needs:progress until the bench is done

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer you still have to pop the coqchk commit.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
