### PR TITLE
Send debugger init even when no breakpoints are set

### PR DESCRIPTION
**Pull request by jfehrle**
I noticed that the CoqIDE hangs when
- `Ltac Debug` is set and
- no breakpoints are set and
- CoqIDE reaches an Ltac tactic call.

This is the fix.  Let's get this into 8.15 also.

### CODE REVIEW

**Comment by ejgallego** [comment]
I'm having trouble understanding this, what is coqide hanging when always sending the breakpoints? It should not be a problem even if they are an empty set?

**Comment by jfehrle** [comment]
db_upd_bpts doesn't send a message if there are no breakpoints to update, so the "config complete" was not being sent.  CoqIDE checks for updated breakpoint locations due to editing the script every time the debugger stops--very frequently.

**Comment by ejgallego** [comment]
> db_upd_bpts doesn't send a message if there are no breakpoints to update, so the "config complete" was not being sent. CoqIDE checks for updated breakpoint locations due to editing the script every time the debugger stops--very frequently.

Shouldn't it be better than the breakpoint message is always sent instead of adding a conditional code path?

**Comment by jfehrle** [comment]
I made a conservative fix for now because it's so close to the 8.15 release date.  Don't think of this as the final code. There's still lots to do completing/refining the debugger.  I plan to do some cleanup later on to how messages are sent, but those changes has more risk of making mistakes that I might not catch and fix in time for the release.  There will be lots of time to do that in 8.16.

Generally I try to avoid sending messages that are no-ops.  They also add clutter when debugging the protocol.

FWIW, I plan to queue up the configd immediately after sending the db_upd_bpts rather than waiting for the reply to db_upd_bpts (since the return value is not meaningful.  Also `try_grab` isn't a great method--for clarity I would have its callers (e.g. when the user presses certain keys) check directly whether a message can be sent.  This is not a pretty pattern:

```
    ignore @@ Coq.try_grab ~db:true sn.coqtop
      (sn.coqops#process_db_configd () ~next:(function | _ -> Coq.return ()))
      (fun () -> Minilib.log "Coq busy, discarding db_configd")
```

**Comment by jfehrle** [comment]
Ping @ejgallego.  Let's make sure a fix gets into 8.15.

**Comment by jfehrle** [comment]
Ping @ejgallego Hellooo out there.  Anybody home?

**Comment by ejgallego** [comment]
> Ping @ejgallego Hellooo out there. Anybody home?

My belly is still full of Turkey , please bear with me!

Well, I'm unsure I follow the logic here, your explanation confused me even more. As you point out, not having uniformity is not the best thing to do, now the state machine in the server side has to work even when the protocol doesn't send the "see my breakpoints" part.

The alternative fix seems actually more conservative to me that this convoluted conditional logic, but if you prefer that I guess we can go ahead.

**Comment by jfehrle** [comment]
Let's go with this for 8.15.  There's still lots more to work to do on the debugger, such as adding Ltac2, GUI improvements and other goodies.

> now the state machine in the server side has to work even when the protocol doesn't send the "see my breakpoints" part.

FWIW, [DAP](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized) doesn't send a `setBreakpoints` message if there aren't any breakpoints set: "_frontend sends **zero** or more ‘setBreakpoints’ requests_"

> My belly is still full of Turkey

Were you in the States for the holiday?

**Comment by ejgallego** [comment]
Yup I am in the states and was lucky to see some friends, happy holidays!

Ok so let's push this then.

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by jfehrle** [comment]
Great, thanks!

**Pull request merged**
