### PR TITLE
Test suite file for bug #4851

### PR DESCRIPTION
**Pull request by JasonGross**

### CODE REVIEW

**Comment by mattam82** [comment]
Could you explain why you have to add Google to the copyright clause?

**Comment by JasonGross** [comment]
I'm interning at Google this summer, and to release code that I write while employed by google, I either need to give it a Google Apache license, or submit it as a patch to existing open source software with an approved license (LGPL is fine).  The instructions say:

> For all patches to open source projects, whether through this form or on the whitelist:
> 
> - If copyright authors are listed in a LICENSE, COPYING, AUTHORS or similar file, please add Google Inc. if it's not already there.
> - Please associate your commit with your google.com email unless you have a history of contributing to the repo under a different email before your employment at Google. How to associate your commit with a google.com email.

dc859d7 is my interpretation of the first item

**Comment by JasonGross** [comment]
I guess the question is, which is the list of "copyright authors" in the Coq repo?

**Comment by ppedrot** [comment]
I'm not sure that a patch whose essential content fits in 3 lines of code qualifies for copyright, and thus that you need to add Google to the list of authors. What I'm pretty sure about though is that the addition of Google to the list of authors will trigger a jurist apocalypse on INRIA side...

**Comment by JasonGross** [comment]
Sure.  I mostly just don't want to get in trouble with Google.

In this case, the essential content is "`nsatz` can't handle duplicate hypotheses"; there are simpler examples, so feel free to make and merge one of those and just close this pull request.

But if INRIA doesn't want Google on the list of authors, what should I do when my test case is a few hundred (or a thousand) lines?  I can stuff it in the fiat-crypto repository under the MIT license (joint between MIT CSAIL and Google, once we figure out where copyright authors are listed), or I can release the code snippet under a Google Apache 2 license, or I can submit it as a patch to this repo (under the license of this repo), but then I'm supposed to add Google to the list of copyright authors, because google retains the copyright to the patch.  (Legal is so annoying >.< )

**Comment by ppedrot** [comment]
As far as I understand this legal mess, all Coq contributors (i.e. for non-trivial patches) are assumed to waive their copyright to INRIA... Until recently this has been more or less enforced by construction (i.e. all authors were working at INRIA) but with the advent of PR this is changing. Better claim I have no idea!

**Comment by JasonGross** [comment]
Should I ask the Google legal team to look at this / to talk to the INRIA legal team?

**Comment by gares** [comment]
What the "copyright" law protects is investment, in terms of energy/time/money.  Yes, it is expressed as a creativity stuff, but investment is really what it is about. A 10 line patch given no copy right IMO.

So to me where the copyright line should be is in the test file itself.  Also because the test suite is not part of the Coq source code, to which the COPYRIGHT file you changed is about.

In any case people in contact with the legal department are getting some enlightenment about that matter.  What may happen is that they ask you (i.e. your employer) to sign a contribution agreement...

**Comment by JasonGross** [comment]
So would the test suite file get a LGPL license with Google named, or would it get Google's Apache 2 license?

And, dSure, if there's some agreement that needs to be signed, I can forward it along to the Google legal team.

**Comment by herbelin** [comment]
Hi Jason, as Enrico said, a copyright should cover something substantial, and for substantial code, there is an "official" agreement about which you have to get in touch with Maxime.

Moreover, my perception is that Google is certainly not the prioritary social entity to protect about recognition of credits, even financial ones. I guess Google managers would themselves admit it! Would I be myself in position of deciding in Google, would I certainly instead freely offer to help valuable academic projects such as Coq without expecting anything in return. This would just be a socially good decision!

**Comment by gares** [comment]
Well, it seems Jason is working for Google, hence it is not a matter of choice: the employer holds the copyright on code written by employees during working hours. The debate is how to appropriately recognize that this contribution to Coq was sponsored by Google, in conformance to the *law*.

It is not a philosophical discussion about Google needing or deserving recognition and protection.  Everybody may have his opinion, but that does not change the law.
Personally, I think that letting Jason contribute to Coq during his working hours is a way to support Coq.  But again this is off topic.

**Comment by herbelin** [comment]
Hi Enrico,

No philosophy here. Not an opinion either but an attempt to describe a reality from a societal point of view. Do you really think that my perception on the place of Google in the society and on the positive social role they could play by generously supporting research such as the one done in Coq is wrong?

There are rules being settled for contributing in Coq. There are default rules applying to Google's employes. If we can find an agreement, that's perfect. If we cannot, that's not a serious problem either. In the current case, I'm ready to bet that most lawyers would share the analysis made by participants to the discussion that the proposal for addition of an extra 9 lines file to a test suite does not qualify as substantial work,

Again, considering the growing importance of certifying software in the world of today, considering that it is more and more important for companies to give an image of contributing to the general interest of the society rather than primarily contributing to their own private interest, I would be Google, I would see a win-win opportunity in generously supporting a reasonably good, challenging and impactful research such as the one done in Coq.

**Comment by ecvideo** [comment]
Hi,  Google wouldn't be you and their interest were, so will be , took in consideration only, They really don't care about real worlds, only about what people will be as foolish to believe. We can verify easily too that themselves They are opportunist doing one Day the contrary of the préviens one.Sure 9 lines is reasonnably not a substantial contribution, but how many years of Court procédures could you pay to démonstrateur it? And will you éven win at least.Forget google.                                                                                                                                                                                                                                                                                                                                         Envoyé de mon smartphone BlackBerry 10.                                                                                                                                                                                                                De: Hugo HerbelinEnvoyé: dimanche 26 juin 2016 02:52À: coq/coqRépondre à: coq/coqObjet: Re: [coq/coq] Test suite file for bug #4851 (#219)Hi Enrico,

No philosophy here. Not an opinion either but an attempt to describe a reality from a societal point of view. Do you really think that my perception on the place of Google in the society and on the positive social role they could play by generously supporting research such as the one done in Coq is wrong?

There are rules being settled for contributing in Coq. There are default rules applying to Google's employes. If we can find an agreement, that's perfect. If we cannot, that's not a serious problem either. In the current case, I'm ready to bet that most lawyers would share the analysis made by participants to the discussion that the proposal for addition of an extra 9 lines file to a test suite does not qualify as substantial work,

Again, considering the growing importance of certifying software in the world of today, considering that it is more and more important for companies to give an image of contributing to the general interest of the society rather than primarily contributing to their own private interest, I would be Google, I would see a win-win opportunity in generously supporting a reasonably good, challenging and impactful research such as the one done in Coq.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by herbelin** [comment]
@ecvideo, not sure that your comment fits the discussion which is about Coq! And why to be so negative? Don't you appreciate Google softwares? Did you have negative experiences which would justify your remark? In any case, please write to me personally to continue the discussion, this will be more appropriate.

**Comment by maximedenes** [comment]
Given the legal issues around this PR, wouldn't it be simpler to close it? I think we can live without this test case.

**Comment by Zimmi48** [comment]
It's interesting to note that Google has open sourced its open source policy. Anyone can now have a look at it at the following address: https://opensource.google.com/docs/

In particular, the part that Jason quoted appears here: https://opensource.google.com/docs/patching/#how-to-patch

My impression on the issue which was discussed is that Google requirements are completely normal. In particular, requiring attribution is not due to Google wanting more recognition or expecting something in return for its contributions but just because attribution is at the heart of open source software. See [this discussion on open source vs public domain on the OSI FAQ](https://opensource.org/faq#public-domain) and [this answer on Open Source SE](http://opensource.stackexchange.com/a/4587/5858).

If we forget about the fact that adding a few tests to the test-suite is probably not significant enough to warrant copyright, that Jason had to add Google at what seemed like a very inappropriate place was justified in my eyes by the fact that the current `COPYRIGHT` file:
```
Copyright 1999-2016 The Coq development team, INRIA, CNRS, University
Paris Sud, University Paris 7, Ecole Polytechnique.

This product includes also software developed by
  Pierre Crégut, France Telecom R & D (plugins/omega and plugins/romega)
  Pierre Courtieu and Julien Forest, CNAM (plugins/funind)
  Claudio Sacerdoti Coen, HELM, University of Bologna, (plugins/xml)
  Pierre Corbineau, Radboud University, Nijmegen (declarative mode)
  John Harrison, University of Cambridge (csdp wrapper)
  Georges Gonthier, Microsoft Research - Inria Joint Centre (plugins/ssrmatching)

The file CREDITS contains a list of contributors.
The credits section in the Reference Manual details contributions.
```
gives the impression that it is giving an exhaustive list of copyright holders.
If it were changed to say:
```
Copyright 1999-2016 The Coq development team (INRIA, CNRS, University
Paris Sud, University Paris 7, Ecole Polytechnique) and external contributors (see CREDITS).
```
it would be more faithful to the reality and would mean that other copyright holders could be listed in `CREDITS`.

Anyways, it's just my 2 cents and it is not my intention to stir up the debate again. I think that the decision of not integrating this PR was the right one, simply because it is useful to limit the spread of copyright holders on the code of Coq at a time where we would like to get every copyright holder to sign an agreement with INRIA.

**Comment by ejgallego** [comment]
I think @Zimmi48 has a point here, in special wrt copyright of other contributors.

**Pull request closed without merging**
