### PR TITLE
Bench NEW=32bit OLD=64bit

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
The bench builds stdlib (and core) with -j 12 but everythng else wth -j 1, I wonder if that's why they're the ones to go faster

**Comment by andres-erbsen** [comment]
Can we see performance counters for these runs? If the bottleneck was memory bandwidth, only saturated during parallel build, we would expect to see a threshold value of cache misses at some level.

**Comment by SkySkimmer** [comment]
You can have a look at the stuff in https://gitlab.inria.fr/coq/coq/-/jobs/4893346/artifacts/browse/_bench/logs/
the `.time` files are the output of `/usr/bin/time --format="%U %M %F"` ie user time (seconds), max resident set size (kB), major page faults

**Pull request closed without merging**
