### PR TITLE
Add some minor results about single-step behavior of nth_error

### PR DESCRIPTION
**Pull request by JasonGross**
- [x] Added **changelog**.

### CODE REVIEW

**Review by andres-erbsen — APPROVED** [review]

**Comment by andres-erbsen** [comment]
Metacoq timeout also appears on master https://github.com/coq/coq/runs/16427207787

**Comment by andres-erbsen** [comment]
@coqbot merge

**Comment by andres-erbsen** [comment]
@coqbot merge now

**Comment by Zimmi48** [comment]
> Metacoq timeout also appears on master https://github.com/coq/coq/runs/16427207787

Indeed. It is likely related to the migration to Inria GitLab CI, and probably means that we should bump this timeout.

**Pull request merged**
