### PR TITLE
Simplify CircleCI script

### PR DESCRIPTION
**Pull request by liyishuai**
**Kind:** infrastructure.

Append `source ~/.profile` to `$BASH_ENV` file to avoid redundancy.

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
Nice.

**Comment by SkySkimmer** [comment]
Note https://github.com/circleci/circleci-docs/issues/1650 for related discussion.

**Comment by SkySkimmer** [comment]
Looks like there was an issue due to retrying the circle job with ssh (?)
I'm going to close and reopen, hopefully that will work.

**Comment by SkySkimmer** [comment]
Nope it only uselessly rebooted travis and appveyor.

**Comment by SkySkimmer** [comment]
@liyishuai did you cancel the build? Circle CI seems to want to run the build on your account (maybe because you're not part of the coq org? I don't know). If so please rerun it.

**Comment by liyishuai** [comment]
OK I’ve just restarted the CircleCI build.

**Comment by SkySkimmer** [comment]
Thanks!

**Pull request merged**
