### PR TITLE
Remove fiat-crypto-legacy from CI

### PR DESCRIPTION
**Pull request by maximedenes**
Motivations:
- We should have only maintained developments in our CI
- `make ci-fiat-crypto-legacy` takes about 15 mins before the first call
to `coqc`, making it unusable to work on overlays
- The coding style of this development is so fragile that adapting to
any change of behavior requires diffing gigabytes of Ltac traces.
@mattam82 and I have been blocked for 6 months this way, when working on
unifall.

I understand this development was meant to stress-test some components
like printing, but I think the trade-off is bad. We should rather come
up with specialized test suites for these components.

### CODE REVIEW

**Review by vbgl — APPROVED** [review]

**Comment by mattam82** [comment]
I second this.

**Review by SkySkimmer — APPROVED** [review]
Fine with me. @ejgallego WDYT?

**Comment by SkySkimmer** [comment]
Also cc @JasonGross

**Review by ppedrot — APPROVED** [review]
FTR, this particular development prevented me to finish a few PRs, because it was too messy to fix. In particular, anything touching Ltac or auto-like tactics make porting this a hell on earth. I am pretty sure @maximedenes lost his sanity in the Export fix on fiat-crypto, so I definitely support removal (of fiat-crypto, not of @maximedenes).

**Comment by maximedenes** [comment]
> of fiat-crypto, not of @maximedenes

Thanks for the clarification :D

**Review by gares — APPROVED** [review]
I think we should take the occasion to make it clear what should be accepted in CI in the first place.
As far as I can tell, the arguments for removing this job are valid now as much as they were valid back then.

**Comment by ejgallego** [comment]
> Fine with me. @ejgallego WDYT?

Let's wait to hear what @JasonGross thinks.

**Comment by ejgallego** [comment]
My point of view is that I'd tend to follow what the upstream authors do suggest; point 1, I ignore, indeed there needs to be some amount of maintenance as for us to keep the projects in the CI, the fact that a project is in legacy mode doesn't imply it is not maintained or used.

Point 2 is easily solvable tho by using non hackish build setups [for example Dune can do the transitive computation at the root of that problem]

Point 3 is indeed quite more serious, a gigabyte-sized trace indeed it is going to be hard to even print. I certainly was not aware the f-c-l was a blocker for so many PRs, in this case I think it would be reasonable to ask upstream to perform the overlay or else get the development removed.

But point 3 indeed maybe signals that there are conflicting goals between our compatibility policy and our development policy; a project such as unifall is likely to do compat damage far beyond f-c-l so it is not clear how that would fit among more active users; maybe we should provide both an unifall and a legacy unif mode for a few releases?

Additionally, the policy calls for an `allowed_fail: true` transition period instead of removal, but that doesn't apply in this case as the development still builds in master.

> I think we should take the occasion to make it clear what should be accepted in CI in the first place.

What do you suggest to change from the current CI policy?

**Review by Zimmi48 — APPROVED** [review]
>this particular development prevented me to finish a few PRs, because it was too messy to fix

This is bad. But that would be the case even if the project was actually maintained. We should not hesitate to raise the issue when this happens *and* request maintainers to help us prepare fixes.

**Comment by Zimmi48** [comment]
Basically, I am OK with the removal in this precise case, but I also agree with Emilio that this kind of issues should generally be discussed/tackled sooner. We don't want to drive developers or contributors mad because of our CI policy.

**Comment by maximedenes** [comment]
@ejgallego So let's be concrete. https://github.com/coq/coq/pull/10734 is blocked on a fiat-crypto-legacy failure. The change of semantics is expected. The build system may be easy to fix but hasn't been in a year (see https://github.com/coq/coq/issues/9298). Well, technically it has, but in fiat-crypto, not the legacy version.

What shoud I do? Are you suggesting I ask fiat-crypto-legacy authors to prepare a patch for me?

**Comment by maximedenes** [comment]
> blocked on a fiat-crypto-legacy failure

(I prepared patches for the other ones)

**Comment by ejgallego** [comment]
> What shoud I do? Are you suggesting I ask fiat-crypto-legacy authors to prepare a patch for me?

Indeed I think that raising discussion here is the right thing to do, next step is to hear from upstream authors.

As Théo has pointed out, I do think that given the complexity of the development, authors are expected to provide overlays themselves in this cases in reasonable time, otherwise the PR is allowed to move the development to allowed fail.

Regarding the build system indeed we could also set a deadline for fixing it or also risk removal.

**Comment by ppedrot** [comment]
> Regarding the build system indeed we could also set a deadline for fixing it or also risk removal.

Sorry to hijack this thread, but reading this I cannot help remembering everytime I want to make a fine-grained bench of a development, until I realize it uses the glorious `remake` build system. @silene mostly brushed it off last time I asked him and vaguely promised a support for the `-timing` flag, but for all the `lia` related changes that means that developments using this *unique* build system cannot be easily checked for per-line performance regressions. Should the above guideline also apply to `remake`?

**Comment by SkySkimmer** [comment]
>Should the above guideline also apply to remake?

If you want to stop benching those projects I guess

**Comment by ppedrot** [comment]
`coquelicot` is in the CI and uses `remake` FWIW.

**Comment by ejgallego** [comment]
@ppedrot indeed requiring standard tooling (and hosting) is the CI roadmap, things still need to be discussed of course, I think the main blocker is that the tooling is still not 100% ready IMHO as to start requiring it.

**Comment by JasonGross** [comment]
I will not block removing fiat-crypto-legacy.  Indeed, it is a bad tradeoff to be costing the developers so much time.  (If you do remove it, it should probably also be removed from opam and from the bench.)

Let me respond to the various points that were, raised, though; perhaps it is not yet time to remove it.

> We should have only maintained developments in our CI

I maintain fiat-crypto-legacy, even if it sees no active development and is not expected to.

> adapting to any change of behavior requires diffing gigabytes of Ltac traces.

I was under the impression that this was easy with `Set Ltac Debug. Set Ltac Batch Debug.` and `diff`>. The size of the trace should not matter so much, as most of it will be the same.  Am I missing something?

> @mattam82 and I have been blocked for 6 months this way, when working on unifall.

Are you still blocked, or were you blocked in the past but no longer are?  My understanding is that the issue with fiat-crypto-legacy and my subsequent investigation revealed both a genuine bug and a significant usability regression, and that the PR is currently blocked on that, c.f. https://github.com/coq/coq/pull/7825#issuecomment-565725327

> I understand this development was meant to stress-test some components like printing, but I think the trade-off is bad. We should rather come up with specialized test suites for these components.

I agree.  I would still be a bit sad to see fiat-crypto-legacy go before such test-suites are developed.

> FTR, this particular development prevented me to finish a few PRs, because it was too messy to fix. In particular, anything touching Ltac or auto-like tactics make porting this a hell on earth.

Feel free to open draft PRs on Coq and then open an issue on fiat-crypto(-legacy) requesting help porting to the draft PR.  I'm not sure how much time I'll have to devote to this, and it might take up to a week for me to dig into any given issue, but I'm certainly willing to spend more time than I have so far (which amounted to maybe half an hour making https://github.com/mit-plv/fiat-crypto/pull/623 backwards compatible).  Another benefit of this strategy is that then you're more likely to get me requesting the removal of fiat-crypto-legacy, if it becomes too burdensome ;-) (You may instead get me strongly requesting better debugging options / tools, though.)
(Note also that if you can point out what behavior change is the issue and what the general backwards-compatible fix is, I'm happy to go track down where it's being an issue in fiat-crypto-legacy and implement the fix.  But I am still willing to help even if you don't know that yet.)

> But point 3 indeed maybe signals that there are conflicting goals between our compatibility policy and our development policy; a project such as unifall is likely to do compat damage far beyond f-c-l so it is not clear how that would fit among more active users; maybe we should provide both an unifall and a legacy unif mode for a few releases?

I agree with this.  I would be interested in seeing the fraction of changes to fiat-crypto-legacy that were caught by other developments and merely required effort to apply the fix here, vs changes that were caught by fiat-crypto-legacy alone.  Even if fiat-crypto-legacy is a painful test-case, if it catches things others do not, this is pointing to a deficiency in the testing ecosystem.

> #10734 is blocked on a fiat-crypto-legacy failure. The change of semantics is expected. 

It seems also blocked on fiat-crypto (non-legacy), no?  If you prepare a patch for fiat-crypto, I'm happy to backport it to fiat-crypto-legacy (and anyway I'm pretty sure that the bits using fields and rings have not changed, so I expect the backport to be easy).
But from what I see in https://github.com/coq-community/math-classes/pull/81 it looks like there perhaps does not exist a backwards-compatible overlay?  (If that is the case, I think the best solution is to add a compatibility option for a couple of versions.)

> The build system may be easy to fix but hasn't been in a year (see #9298). Well, technically it has, but in fiat-crypto, not the legacy version

I did not invest any time into fixing it because my question about whether it was still an issue, which I asked in June (https://github.com/coq/coq/issues/9298#issuecomment-500527723), was only answered just now.  I have just asked a follow-up question (whether or not the issue persists after calling `./etc/ci/remove_autogenerated.sh`), and, if the answer to that question is that it is still an issue, I can fix the build system within 10 days.  Or if you want me to fix it so that it works even without running the script, I can create alternate targets for Coq's CI that do this anyway? (Again, within 10 days.)

**Comment by ejgallego** [comment]
> I will not block removing fiat-crypto-legacy.
> perhaps it is not yet time to remove it.

Thanks @JasonGross for the comprehensive answer; IMHO given that you are the maintainer in principle I propose we follow your recommendation; I think PR authors should be more active then in requesting help with `fiat-crypto`, or in moving it to allow_fail if the PRs need to go forward.

IMHO more discussion on the compat policy may be needed.

**Comment by maximedenes** [comment]
Thanks @JasonGross for the detailed answer. I should have mentioned that this PR should not be seen as any kind of criticism addressed to fiat-crypto's authors. In particular you have always been responsive, and tried to improve the situation when possible.

Sorry about the miscommunication on the build-related issue, I did not really understand your question back then, since nothing had changed in the way our CI builds fiat-crypto-legacy, so the issue had to be still there. I should have answered nonetheless.

Anyway, the question I was asking here is a pragmatic one. In my experience, maintaining fiat-crypto-legacy in our CI has a huge cost in my experience, for little benefits. Exploring very large ltac traces is problematic, for many reasons:
- diff is not semantic, so you find a lot of spurious differences (alpha renamings, evars renumbering, etc)
- the first difference is very often the same tactic being applied to a new goal. The exercise of figuring out the proof structure and the origin of the new goal is usually left to the reader

On the other hand, I'm not sure what we gain concretely by having it. How often has fiat-crypto-legacy been the only development signalling an important bug? In the unifall nightmare, two problems were detected. The first one, which took months to investigate by @mattam82 and me, is (as often with Ltac) relying on an undocumented behavior, which had changed. The second one (which is the one you pointed to) was already revealed by Iris, IIRC. Here again, fiat-crypto-legacy is not to blame, it is rather the underspecification of tactics and Ltac.

Keeping a development in our CI is a decision that impacts the entire development team, so we should think it in terms of where we want to invest our (limited) resources. This is were the criterion of being actively developed (I wrote maintained instead, sorry for the confusion) is relevant IMHO.

So, to start assessing the benefit/cost ratio, maybe it would be good to recall what the concrete motivation is for keeping fiat-crypto in our CI. @ejgallego do you have any evidence that it is indeed a useful test case in practice?

**Comment by JasonGross** [comment]
> So, to start assessing the benefit/cost ratio, maybe it would be good to recall what the concrete motivation is for keeping fiat-crypto in our CI.

I assume you mean fiat-crypto-legacy here?  The motivations for fiat-crypto and fiat-crypto-legacy are different; the former is a project that is under development, and which I actually plan on releasing soon, and which I think would be good to keep working.  On the other hand, fiat-crypto-legacy, as far as I'm concerned, is in the CI purely for regression-testing of Coq (the same applies to fiat-parsers, by the way).

**Comment by JasonGross** [comment]
Also, fiat-crypto-legacy did catch https://github.com/coq/coq/issues/6416

**Comment by maximedenes** [comment]
> I assume you mean fiat-crypto-legacy here?

Yes, of course, sorry!

**Comment by JasonGross** [comment]
> > I assume you mean fiat-crypto-legacy here?
> 
> Yes, of course, sorry!

No worries

**Comment by ejgallego** [comment]
> @ejgallego do you have any evidence that it is indeed a useful test case in practice?

The CI criteria does not require or define such "evidence"; do you have evidence about the rest of developments in CI being useful test cases? How does it look like?

CI is not really about testing w.r.t. a specification, but more about controlling and managing regressions / compatibility changes.

Also, we don't require developments to be actively developed, but only actively maintained.

In my view we should be quite conservative on breaking user-level code; large chunks of Coq behavior are indeed under-specified so it is hard to take documentation as a base for compatibility.

I fully support tho that for developments that we consider too complex to maintain ourselves, upstream authors should be the ones in charge of providing overlays; this can in fact help to improve the specification of the feature.

Personally, as long as @JasonGross wants to keep fiat-crypto v1 in the CI and he's willing to maintain it I'm OK with keeping it there.

**Comment by Zimmi48** [comment]
> The CI criteria does not require or define such "evidence"; do you have evidence about the rest of developments in CI being useful test cases? How does it look like?

That's a good question though. In [my thesis](https://www.irif.fr/_media/users/theo/memoirthesis.pdf), I started gathering some metrics close to this (see 3.6, and more particularly 3.6.4). It was my plan anyway to look into this more precisely (as part of what's discussed in [here](https://github.com/coq/coq/pull/10770#issuecomment-539599935)), but I could look at this sooner for the specific case of fiat-crypto-legacy.

**Comment by ejgallego** [comment]
I guess predicting how useful a particular development may be pretty hard; this is the reason we just welcome any project to the CI as long as they are willing to do their part.

It could be the case that there are few releases where, let's say, feature X, used by project P is not modified in Coq, then in the next development cycle modifications on X do happen. Thus, while P was not useful in the last few cycles, now it becomes useful.

Also, the way Coq is develop looks to me like it fits that pattern [for example EConstr, Unifall, etc...]

Would be great if we could have a strong enough test-suite as not to depend so heavily on CI, but that seems long-term.

**Comment by JasonGross** [comment]
> > The build system may be easy to fix but hasn't been in a year (see #9298). Well, technically it has, but in fiat-crypto, not the legacy version
> 
> I did not invest any time into fixing it because my question about whether it was still an issue, which I asked in June ([#9298 (comment)](https://github.com/coq/coq/issues/9298#issuecomment-500527723)), was only answered just now. [...] I will prepare a fix within 10 days.

I got it done ahead of time: #11500

**Comment by Zimmi48** [comment]
Related to this PR: I opened #11499 to clarify that contributors should not always be the one to prepare compatibility fixes.

**Comment by herbelin** [comment]
In addition to the interesting comments above, which help to find an appropriate compromise, let me add the following.

Regarding unif-all, is it realistic to hope a full compatibility? My feeling is that we have more to gain to offer a non-strictly-compatible unification/tactic system open to the future than trying to keep compatibility at all prices (which also means versioning).

With this regard, fiat-crypto(-legacy) debugging shall be useful to understand fine semantics differences but not a necessity either if it happens to be blocking as it seems to be in the present case of unif-all. We should not make a confusion between "maintaining" what is in CI (which is not our job per se) and using CI to check that our changes of semantics are right - or not - (which is our job).

Also, we are very lucky that the authors of fiat-crypto(-legacy) are willing to interact with us, but there are users who don't talk about the many problems they have with Coq and I suspect these users to be very very numerous (discuss with people at the JFLA where I am currently for instance). Keeping this or that development in the CI (independently of the question of who addresses the compatibility issues) is not only about this development itself but also about what exists in the wild and which we are not necessarily explicitly aware of.

**Comment by maximedenes** [comment]
@JasonGross I recall you mentioned it recently, but I forgot about the details: what are the components you think fiat-crypto-legacy tests more than other developments we have in CI?

I wonder how hard it would be to extract from fiat-crypto-legacy a set of minimized test cases for these components, that would not relying on Ltac. Unlike the current situation, in the case of failure, we could get some meaningful information without crawling these traces for days.

**Comment by maximedenes** [comment]
> that would not relying on Ltac

(by this I mean to not rely on large scale fragile automation, calling some tactics is obviously ok)

**Comment by Zimmi48** [comment]
> Regarding unif-all, is it realistic to hope a full compatibility? My feeling is that we have more to gain to offer a non-strictly-compatible unification/tactic system open to the future than trying to keep compatibility at all prices (which also means versioning).

:+1: Like for Ltac2, or stdlib2, it makes sense to provide explicit flags for switching the unification engine and help maintain backward compatibility during a few releases. OTOH, if unifall is only one step but the next one is switching again the unification engine to Unicoq, then it doesn't seem worth it to force everyone to migrate to the intermediate state is more breakage is to come.

**Comment by JasonGross** [comment]
>  I recall you mentioned it recently, but I forgot about the details: what are the components you think fiat-crypto-legacy tests more than other developments we have in CI?

@maximedenes it tests printing performance when there are thousands of notations.  (Unfortunately I did not have a check of printing behavior, and there was a regression between 8.8 and 8.9.)
It stresses the VM and conversion somewhat heavily, but that's probably not exclusive to this development.  I believe it stresses `pattern` in a way that no other development does (calling it on much larger terms), if I recall correctly.  That's what I recall currently, though I may be missing something.

**Comment by ejgallego** [comment]
Based on the discussion I propose to close this PR, regarding the original points:
- points 1 and 2 [maintenance and problems with build script] don't apply anymore, f-c-l is maintained by Jason and the build system should be fine [there is also an option to use a less hackish setup if needed]
- for point 3, I propose indeed that updating f-c-l should not block any PR, if there is wide consensus that a change of semantics that breaks f-c-l should be accepted, f-c-l maintainers should take care of updating it; if that's not feasible we may reconsider dropping it again. I believe that unifall for example is not blocked only on f-c-l but as @herbelin points out wider breakage is expected, is that correct?
- IMHO it seems that f-c-l still does stresses some unique parts of Coq, and thus while at some point we may drop it from the CI, as of today it help detecting impact on changes; I agree with @herbelin in that still our CI system is not enough to achieve fully controlled regression testing for project in the wild.

**Comment by maximedenes** [comment]
I suggest we discuss this during a Coq call, so far a majority of core developers wrote they were in favor of removal.

My personal opinion depends on a more precise question : if I'm working on a PR which breaks fiat-crypto-legacy (but say, no other developments at that point). Who has to conduct the investigation of what broke and why? If it is me, I'm still in favor of removing it because I found it too costly many times.

**Comment by ejgallego** [comment]
Discussing in a call seems fine.

> My personal opinion depends on a more precise question : if I'm working on a PR which breaks fiat-crypto-legacy (but say, no other developments at that point), who has to conduct the investigation of what broke and why? If it is me, I'm still in favor of removing it because I found it too costly many times.

The way I see it is that first of all, the PR is breaking f-c-l because is altering the semantics of Coq; the fact that we f-c-l is a witness of the breakage doesn't mean that it is not going to affect any other of the dozens of developments in the wild. Two scenarios can happen w.r.t. breakage:
- the breakage was intended by the PR [controlled compat change] , thus, the PR can be merged and complex developments in the CI should be fixed by their maintainers of else moved to allow_failure
- the breakage was unintended: then something funny is going on thus it would deserve more research, hopefully jointly between the failing projects and the PR authors.

In both cases I'd dare to say that feedback from the broken project maintainers would be always pretty useful and a good contribution to Coq itself, which is one of the goals of the CI system [give a voice to 3rd party projects on Coq's changes]

**Comment by ejgallego** [comment]
> I'm working on a PR which breaks fiat-crypto-legacy (but say, no other developments at that point)

Maybe the original example [unifall] is not a good motivation for this PR as indeed it does break more than f-c-l , right? So for this case the answer is, ignore f-c-l for now; but still the question of what to do with the rest of breakage does remain.

**Comment by maximedenes** [comment]
> Maybe the original example [unifall] is not a good motivation for this PR as indeed it does break more than f-c-l , right? So for this case the answer is, ignore f-c-l for now; but still the question of what to do with the rest of breakage does remain.

My point is what to do with the fiat-crypto-legacy failure is the only *remaining* one.

Unifall is currently waiting for https://github.com/coq/coq/pull/7825, which at some point was delayed by about 6 months because we had to investigate and fix fiat-crypto-legacy. Not sure why it would not be a good motivation for this PR.

**Comment by ejgallego** [comment]
> My point is what to do with the fiat-crypto-legacy failure is the only _remaining_ one.

As proposed above the PR could proceed moving f-c-l to allow failure and requesting collaboration from the maintainers.

> Unifall is currently waiting for #7825, which at some point was delayed by about 6 months because we had to investigate and fix fiat-crypto-legacy. Not sure why it would not be a good motivation for this PR.

I'm not very sure I understand all the details of that PR, but it seems to me that #7825 is indeed a case supporting to have f-c-l in the CI, IIUC its maintainer found a bug in the PR, and provided what seems very valuable feedback; moreover it is claimed that "Note that this should also fix the issue with fiat-crypto legacy without any need for an overlay." I do agree tho that we should improve collaboration with upstream authors so Coq dev don't have to do these painful debugging again tho.

**Comment by Zimmi48** [comment]
> My personal opinion depends on a more precise question : if I'm working on a PR which breaks fiat-crypto-legacy (but say, no other developments at that point), who has to conduct the investigation of what broke and why? If it is me, I'm still in favor of removing it because I found it too costly many times.

That's a great question! In theory, most of the time, the author of the PR should be able to understand the problem by themselves. But this would require that the projects we test have: a standard build system, follow best practices and write robust proof scripts, and are generally understandable to external Coq users. Unfortunately, it is still far from being the case for many such projects. So that makes sense to request help from project maintainers in this case as well. Should I further tweak #11499 to express this?

**Comment by ejgallego** [comment]
> Should I further tweak #11499 to express this?

Sure, IMHO our tooling is still not good enough as to suggest people to adopt a standard one _right now_, at some point indeed when the full machinery is ready so developers can do `test-overlays` and get a list of things to do we can start becoming more strict.

Indeed it should be clear to PR authors that overlays come with limits; at least from my own contributions to the CI system it was never the idea that we would have to spend months, not even a single full day on fixing / adapting 3rd party code, but yeah, it is hard to write that kind of thinking down, as Benjamin calls it "the curse of knowledge"

Personally I see overlays more as in the linux kernel model: my impression there is that if you break the API, you are supposed to fix drivers too; however if the driver itself is a mess the maintainer may have to do it; lack of maintainership results in removal of the tree.

**Comment by maximedenes** [comment]
> is indeed a case supporting to have f-c-l in the CI, IIUC its maintainer found a bug in the PR

You probably missed it in the discussion above, but I already mentioned that the change of behavior which caused the original fiat-crypto-legacy breakage and long investigation was not the "bug" (in fact, another change of semantics), which was then discussed in the PR. That second change was already found in Iris, IIRC (and in fact, was intended from the start by @mattam82). So this entire situation would have been better approached by removing fragile test cases (of which fiat-crypto-legacy is an archetype) and better communication with users (because @JasonGross 's feedback regarding the intended change, with a point of view centered on automation, was very valuable). We could have got a similar feedback by sending an e-mail to Jason describing the change.

**Comment by ejgallego** [comment]
The gist here IMHO is that it is should be made clear that PR authors have the right to refuse to create complex overlays for a particular project; I think that this doesn't equate as removing such project from the CI.

**Comment by maximedenes** [comment]
> PR authors have the right to refuse to create complex overlays

Not sure how to communicate this better, but again, the problem in practice is *not* the complexity of the overlay. It often ends up being a one line change. The problem is the investigation of the breakage.

**Comment by ejgallego** [comment]
By complexity I mean the complexity of writing the overlay.

**Comment by gares** [comment]
It it relevant for f-c-l to work with the very last version of Coq? Just asking.

**Comment by gares** [comment]
I mean, there is a new version to be released soon.

**Comment by JasonGross** [comment]
> It it relevant for f-c-l to work with the very last version of Coq?

Fiat-crypto-legacy is in the CI just to test Coq.  If it were not in the CI, I would stop maintaining it.  Note that it is already broken for it's intended purpose since 8.9, because I forgot to have it test notation printing and thus did not catch breaking changes.

**Comment by ejgallego** [comment]
So @JasonGross what's your view on keeping f-c-l then? I understood you would not block its removal, but would you like we keep it in then?

Somehow I understood that you were advocating for keeping it in the CI; for what me concerns, the call is yours.

My idea on the CI is that we trust the 3rd party maintainers as whether to add or remove projects (*)

(*) I know this is not true as of today as when we bootstrapped the CI we hand-picked a few, however I'd expect this to become true in the short-medium term tho.

**Comment by JasonGross** [comment]
Yes, my current preference is to keep f-c-l in the CI, and have developers ping more actively when compatibility issues arise.

**Comment by mattam82** [comment]
We discussed this at the call and balanced the potential usefulness of mainting f-c-l for the Coq team vs its cost and the majority ruled towards removing it, mainly because it is maintained just for us, doesn't actually test printing anymore and relies on very hard to debug Ltac code. So, let's remove it. @JasonGross I want to stress that it's been a useful test in the past and the decision has nothing to do with your handling and maintainance of fiat-crypto-legacy, which is always top-notch :)

**Comment by JasonGross** [comment]
Sounds good.  Should we (or I) look into the new failure on the unification PR before we drop it, or just assume that it's an expected failure?  (Btw, I'm currently running the minimizer on the not-legacy anomaly.)

**Comment by JasonGross** [comment]
I've minimized the issue with #7825 arising from fiat-crypto-legacy.  It was a genuinely new bug not caught by anything else in the CI.  It took me about 1--1.5 hours to track down.  (The bug is a discrepancy in how evars are handled depending on whether evar creation is separated from `simple refine` with `;` or with `.`)

**Comment by JasonGross** [comment]
Since it turns out I'm still collecting data from fiat-crypto-legacy on new versions of Coq, and also that it's being used to track down memory issues in #12487 and that the bug in #7825 is genuine, I've created #12554 to add it back to the CI (on a temporary basis).  Feel free to discuss, I can also come on the Coq call this week if further discussion is needed.

**Pull request merged**
