### PR TITLE
Additions to String module and extraction to OCaml native strings

### PR DESCRIPTION
**Pull request by BridgeTheMasterBuilder**
Hi, this is my first PR to the repository, I apologize in advance for any potential missteps!

Summary of changes:
- Added functions `map` and `forallb`
- Added support for extracting `map` and `forallb` to OCaml's `String.map` and `String.for_all` in module `ExtrOcamlNativeString`

- [ ] Added / updated **test-suite**.

- [x] Added **changelog**.
- [ ] Added / updated **documentation**.

- [ ] Opened **overlay** pull requests.
(I'm pretty sure this doesn't apply but I'm leaving it here just in case)

I used these in a [toy project](https://github.com/BridgeTheMasterBuilder/vericaeser) to be able to extract to idiomatic OCaml string code without having to explode strings into a list of characters.

The definitions are essentially identical to those found in the `List` module except specialized to `ascii`. I also attempted to mirror the documentation style in the `List` module to some extent in anticipation of future expansion but I welcome feedback. The headings should probably be made bigger, also I'd be happy to flesh the module out a bit more by adding `fold`, `existsb`, etc. so the headings actually make sense.

Since these functions are primarily intended for computation/extraction, I'm not sure if associated lemmas are high priority, as you can probably convert the string to `list ascii` to do proofs (that's what I did in the linked project). I'm curious what the standard library's policy on lemma reuse is in general. Since `string` has the same shape as `list ascii`, it seems like a lot of the lemmas in `List` that you would want to include in `String` would have essentially similar proofs, so there would be a lot of duplication.

I have yet to complete the necessary tasks like updating the changelog, polishing the documentation, tests etc. As per the recommendation in the contributor's guide I'm opening this PR now to get feedback. Please let me know if I need to change anything.

### CODE REVIEW

**Review by andres-erbsen — APPROVED** [review]
Additions like this are welcome. If you have lemmas that relate these new functions to versions that operate on `list`, these lemmas would be welcome as well.

The future of the string and ascii types is unclear, and the two are somewhat neglected. Maybe one day we will standardize on `list byte`, but we are not ready to do the switch now.

Perhaps it would make sense to add a compilation test for the extracted code [here](https://github.com/coq/coq/blob/38d6695084c9d38b5af7258a85702a1d01a49dce/test-suite/success/extraction.v#L669)? IIUC We currently don't have execution tests for most Extraction directives, so I don't think it makes sense to require them now. Or is there an easy example that could be followed? @coq/extraction-maintainers 

Please add a changelog entry as explained in https://github.com/coq/coq/tree/master/doc/changelog#how-to-add-an-entry

Let's find out whether we need overlays (perhaps because some user of stdlib already defines a function with the same name).

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by andres-erbsen** [comment]
Yes, this change making import order significant could be a compat nuisance as you describe. I'll kick off the CI again, maybe it'll work this time.

@coqot run full ci

**Comment by andres-erbsen** [comment]
@coqbot run full ci

**Comment by Villetaneuse** [comment]
Thank you very much for your contribution, @BridgeTheMasterBuilder.
It is indeed a breaking change, but it is not hard to fix: either `Import List` after `String` or
`sed 's/\<map\>/List.map/g'`.
Another possibility would be to split your `String.v` into `String.v` and `StringMap.v`, but I like it less (multiplying stdlib files creates entropy).
@proux01 what is the policy about such a change? Does it break the "2 consecutive versions contract"?

**Comment by JasonGross** [comment]
> Does it break the "2 consecutive versions contract"?

AIUI, this contact can only be broken when there's no backwards-compatible fix.  Since there's an easy backwards compatible fix here, we just need to update CI developments.  It might be worth writing a script (more robust than the sed script) to do this: it should be possible to write a generic `qualify-names Coq.Lists.List.map map List.map .` (`qualify-names fully-qualified-constant search-text replacement-text list-of-files-or-directories`) script that parses .glob files to find instances of the search text which refer to the fully qualified constant, and replaces them.  (Presumably coq-lsp could do something similar.)

In fact, https://github.com/JasonGross/coq-tools/blob/master/coq_tools/absolutize_imports.py could do the job with just minor changes, namely the code at https://github.com/JasonGross/coq-tools/blob/b29cc4488f36e420ff892a7db7333d26219d0db9/coq_tools/import_util.py#L509-L546 needs to get extra arguments for "restrict the search text (cur_code) to this set of constants" and "restrict the fully qualified names (rep_orig) to this set of constants", and then https://github.com/JasonGross/coq-tools/blob/b29cc4488f36e420ff892a7db7333d26219d0db9/coq_tools/absolutize_imports.py#L33 / https://github.com/JasonGross/coq-tools/blob/b29cc4488f36e420ff892a7db7333d26219d0db9/coq_tools/absolutize_imports.py#L47-L56 would have to pass these two new arguments as well as passing something like `mod_remap={'Coq.Lists.List':'List'}` (to be constructed from command line arguments).  (And then we'd need to pass [`-a`](https://github.com/JasonGross/coq-tools/blob/b29cc4488f36e420ff892a7db7333d26219d0db9/coq_tools/absolutize_imports.py#L18) to absolutize all constants and not just imports.

**Pull request closed without merging**
