### PR TITLE
Fix "make test-suite" with legacy build

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
Umm, I am seeing very weird failure in my laptop so I'm having trouble testing this
```
==========> TESTING success/sprop_uip.v <==========
File "./success/sprop_uip.v", line 103, characters 0-62:
Error:
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"/tmp/Coq_native6510c7/Coq_native7a7369.cmxs: failed to map segment from shared object\")")
```
not the most assuring feeling O_O

This used to work, when it did get broken?

I'm a bit scared by the way we setup the rules, for the test suite it is fine, but all the rules of the bridge rely on referencing `_build/default` , only the `.install` file will populate .install so I dunno.

**Comment by SkySkimmer** [comment]
@ejgallego I can't reproduce that error

**Comment by ejgallego** [comment]
> @ejgallego I can't reproduce that error

I still get these errors on a fresh rebase of this on `master` and OCaml 4.12.1

```
==========> TESTING bugs/closed/bug_7854.v <==========
File "./bugs/closed/bug_7854.v", line 10, characters 0-64:
Error:
Dynlink error: error loading shared library: Dynlink.Error (Dynlink.Cannot_open_dll "Failure(\"/tmp/Coq_native21ac23/Coq_native5b78f1.cmxs: failed to map segment from shared object\")")

0m0.000000s 0m0.000000s
0m0.230000s 0m0.140000s
```
Ummm, let me do a fresh switch opam

**Comment by gares** [comment]
@ejgallego the errors you see have nothing to do with this PR, it seems more something like a bug in 4.12 fixed in 4.13

**Comment by SkySkimmer** [comment]
@ejgallego ping

**Comment by ejgallego** [comment]
> @ejgallego ping

Ok testing with 4.13 underway , couldn't really test this while on the road sorry.

**Comment by ejgallego** [comment]
Still broken for me with 4.13, something is going on.

**Comment by SkySkimmer** [comment]
Is it more broken than before though?

**Comment by ejgallego** [comment]
@SkySkimmer does `./configure -profile devel && make -j world && make -j test-suite` work for you? If so, in which OCaml version?

> Is it more broken than before though?

Seems less broken, tho for some reason the fix doesn't fully work, before we get:
```
Error: Unbound module Nativevalues
File "./primitive/sint63/mod.v", line 9, characters 0-34:
Error: Native compiler exited with status 2
```
after the Dynlink error.

**Comment by SkySkimmer** [comment]
NO FAILURES
also with native configured on
ocaml 4.09.1

How are you getting native errors if you use configure devel?

**Comment by SkySkimmer** [comment]
If it doesn't make things worse can we get this merged and figure out what the other issue is later?

**Comment by ejgallego** [comment]
> How are you getting native errors if you use configure devel?

Good question, let me do another try :S

**Comment by ejgallego** [comment]
I'm clueless what to do with this PR, still native part of test suite is broken, and I get this:
```
Makefile:158: atención: la variable 'COQ_NOT_CONFIGURED' no ha sido definida
Makefile:168: atención: la variable 'COQLIB_NOT_FOUND' no ha sido definida
Makefile:187: atención: la variable 'BUGS' no ha sido definida
```

**Comment by SkySkimmer** [comment]
What commit are you running? the first 2 variables were already fixed (I fixed BUGS just now)

**Comment by ejgallego** [comment]
> What commit are you running? the first 2 variables were already fixed (I fixed BUGS just now)

Let me retry with current tip here; anyways let's go ahead with this, the current mess needs a bit more work.

**Review by ejgallego — APPROVED** [review]
Still got problems with native, but we'll see.

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
