### PR TITLE
Please ignore! 8.12 windows CI pinning variant test

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
Please ignore.

This is just to test a merge between PRs #12475 and #12415 and implementation variant

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : the compcert Linux test fails because I need to install Flocq and possibly MenhirLib before. I might not have time to do this before today evening. The Windows build looks fine.

**Comment by Zimmi48** [comment]
Please focus on the Windows build, I can adapt the Linux CI if necessary.

**Comment by Zimmi48** [comment]
IIUC you still have to fix which version of VST is used and figure out how to build Gappa. That's already a lot on your plate.

**Comment by MSoegtropIMC** [comment]
> IIUC you still have to fix which version of VST is used and figure out how to build Gappa. That's already a lot on your plate.

I did already discuss the version to pick with Andrew and did a lot of work on the VST build system recently, so I know it quite well - this shouldn't be an issue. If CompCert and its prerequisites build, VST is fine. But the Linux CI of VST will get tricky because I plan to use a version which uses the platform CopmCert and Flocq. So one needs to install it.

It might be worthwhile discussing if for now we use different versions on Linux CI (CompCert and VST use bundled components) and on the Windows platform build (CompCert and VST use platform components).

If you want to fix the CompCert CI build, please feel free to push to my branch of this PR - I won't touch it until after 5 PM.

I didn't look at Gappa as yet, so I can't tell how much work this will be.

**Comment by MSoegtropIMC** [comment]
> If you want to fix the CompCert CI build, please feel free to push to my branch of this PR - I won't touch it until after 5 PM.

But as I said, using simply different versions on Windows and Linux might also be an option.

**Comment by Zimmi48** [comment]
> It might be worthwhile discussing if for now we use different versions on Linux CI (CompCert and VST use bundled components) and on the Windows platform build (CompCert and VST use platform components).

That could be an option indeed as it is relatively easy to implement.

**Comment by MSoegtropIMC** [comment]
> That could be an option indeed as it is relatively easy to implement.

I think we should go for that, also because it doesn't make sense to merge the CI changes into master, since CompCert master uses the bundled Flocq.

How should I do it? As a local definition in the Windows build file or have an additional definition in ci-basic-overlay to make it clear that Windows/platform does somethign else?

**Comment by Zimmi48** [comment]
As you prefer. I don't have an opinion.

**Comment by Zimmi48** [comment]
@MSoegtropIMC Can you give me a summary of what works, what doesn't and what remains to do?

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I need to check. This should have gone through - likely just a typo. So compcert Windows + CI should work. VST should be easy - I can for sure finish it today evening. Gappa I have to see.

**Comment by Zimmi48** [comment]
OK, keep me posted. Thanks!

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I plan to merge this on #12475 today evening so that you can merge it into 8.12. It will include those changes from your PR I rely on (should be only Flocq). It will most likely contain Menhir, Menhir Coq lib, CompCert and VST, maybe Gappa.

**Comment by Zimmi48** [comment]
>It will include those changes from your PR I rely on (should be only Flocq).

Note that fixes to the build of `Flocq` have been integrated separately into #12451 (which has already been backported).

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : for the gappa tool some cygwin compatibility automake stuff doesn't work any more (a standard mechanism to find a a compiler for the build OS since gappa builds remake and remake needs to run under cygwin). I see what I can do about this but automake is quite a pain ...

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I got the gaooa tool built, but the plugin is game over for today. I get a "Unbound module Vernacstate.Proof_global" in the OCaml part. Does this tell you something?

I will now merge this to my other PR which is not based on yours. I will include the gappa tool - it might make it easier to get the plugin running, since it is easier to test then.

**Pull request closed without merging**
