### PR TITLE
Extend hack to use postponed constraints in retyping to template poly

### LINKED ISSUE #9809: Anomaly : "not an arity"
#### Description of the problem
Trying to define the (not-well typed) function `fib0` below  raise an `Error: Anomaly "Not an arity." Please report at http://coq.inria.fr/bugs/.`. If `Program Definition` is used instead of `Definition` the type error is correctly reported. Inlining the parameters `gen_op` and `gen_ty` of `FreeF` also remove the error. 

```Coq
Section FreeMonad.

  Variable S : Type.
  Variable P : S -> Type.

  Inductive FreeF A : Type :=
  | retFree : A -> FreeF A
  | opr     : forall s, (P s -> FreeF A) -> FreeF A.

End FreeMonad.

Section Fibonnacci.

  Inductive gen_op := call_op : nat -> gen_op.
  Definition gen_ty (op : gen_op) :=
    match op with
    | call_op _ => nat
    end.

  Definition fib0 (n:nat) : FreeF gen_op gen_ty nat :=
    match n  with
    | 0
    | 1 => retFree _ _ _ 1
    | S (S k) => opr _ _ _ (call_op (S k)) 
(fun r1 => opr _ _ _ (call_op k) 
(fun r0 => retFree (* _ _ _ *) (r1 + r0)))
    end.

End Fibonnacci.
```

#### Coq Version
Version 8.8.2 and master (revision `beaccf0befcc59178ca59913e63625fa42f6d186`)

Would it be related to #7645 ?

### LINKED ISSUE #13366: Anomaly: "not an arity"
#### Description of the problem

Minimized example:

```
Class Functor (F : Type -> Type) : Type :=
  fmap : F nat.

Lemma blah : sum fmap.
```

Output:

```
Anomaly "Not an arity." Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

Tested on 8.12, dev a10e7b3e47

### PR DESCRIPTION
**Pull request by SkySkimmer**
See 742ef62fe8050a6865d06bd644e30cbec0e7eb02

Fix #13366
Fix #9809

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
The fix relies on the (expected) invariant that the sort of any subterm of a typed expression has already been typed and that if a subterm of the expression is of a type `T` which has to reduce to a specific form but does not, then it is because of an evar `?x` blocking the computation and there is a postponed equation which involves `T` and its blocking evar.

The way to recover the equation (provided by `get_type_from_constraints`) can certainly be improved. For instance, the evar is not necessarily blocking only in an applicative term of the form `?x args` as it can also be blocking a `match`, a `fix`, or a projection. Also, the set of postponed constrained to look in can be made smaller by keeping only the constraints explicitly mentioning `?x`. Also, using full `conversion` is maybe a bit too strong comparing to first trying to match with syntactic equality and only after with conversion.

Nevertheless, these concerns are not directly related to the PR which, under the assumption that `get_type_from_constraints` does the job, fixes an inelegant anomaly in a simple way.

In particular, I'm advocating for 8.13 integration.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
please merge

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
