### PR TITLE
Cleanup checker/values after removal of vio

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
I think this is going the wrong way, actually: we should use proxy more and rely less on cyclic values for recursive types.

**Comment by SkySkimmer** [comment]
Removed removal of Proxy

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
