### PR TITLE
Fixes #11402: Reserved Infix supports infix notations with extra parameters among the list of symbols

### LINKED ISSUE #11402: Reserved Infix fails to reserve
#### Description of the problem

```coq
Reserved Infix "||->{ f }" (at level 50, left associativity).
Infix "||->{ f }" := f.
(* Error: A left-recursive notation must have an explicit level. *)
Reserved Infix "||->[ f ]" (at level 50, left associativity).
Infix "||->[ f ]" := f.
(* Error: A left-recursive notation must have an explicit level. *)
```

cc @herbelin 

Maybe related to #4970 / #2867 ?

#### Coq Version

8.10.0

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** enhancement

Fixes / closes #11402

~~Note that `Reserved Infix` is still a hack though.~~ 27 June 21: A new fix is adopted, on top of #13353. 

- [X] Added / updated test-suite
- [X] Entry added in the changelog

### CODE REVIEW

**Comment by JasonGross** [comment]
The changelog should also mention the change in the meaning of `Reserved Infix "'o'"`.  Speaking of which, what's the correct way to reserve an infix for
```coq
Notation "f 'o' g" := (compose f g).
```
?  And what's the corresponding `Infix` command?  I thought it was `Infix "'o'"` and `Reserved Infix "'o'"`, is this not the case?  Was this the case but it no longer is?

**Comment by herbelin** [comment]
> The changelog should also mention the change in the meaning of `Reserved Infix "'o'"`. Speaking of which, what's the correct way to reserve an infix for
> 
> ```coq
> Notation "f 'o' g" := (compose f g).
> ```
> 
> ? And what's the corresponding `Infix` command? I thought it was `Infix "'o'"` and `Reserved Infix "'o'"`, is this not the case? Was this the case but it no longer is?

This is not changed by the PR. You should use `Infix "o"`/`Reserved Infix "o"` (without single quotes). Using `Infix "'o'"`/`Reserved Infix "`o`"` used to only declared the token `'o'`, not `o`.

Actually, I could also make that `Reserved Infix "'o'"` continues to reserve `'o'` to better compatibility, but it seems that this is not what was expected by users.

**Comment by herbelin** [comment]
In the PR, some consistency is lost between `Infix` and `Reserved Infix` (as shown by fiat-crypto). I would prefer to redo this PR in a cleaner way on top of #13353. Postponing to 8.15.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Test-suite needs a trivial fix, though.

**Comment by ppedrot** [comment]
@herbelin ping

**Comment by ppedrot** [comment]
Last call for comments before merging.

**Pull request merged**
