### PR TITLE
Refine Auto Template Polymorphism option: allow auto template polymorphism without a warning.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** enhancement.

The warning is now triggered if the option is not set and no attribute is used.
The option can be set to "enabled" or "disabled" and in both cases it will disable the warning.

- [ ] Added / updated test-suite
- [ ] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [ ] Entry added in CHANGES.md.

### CODE REVIEW

**Review by SkySkimmer — CHANGES_REQUESTED** [review]
There's already `Set Warnings "-auto-template".` so I don't see the benefit.

**Comment by Zimmi48** [comment]
The idea is that it doesn't make sense that asking explicitly for auto template polymorphism requires you to additionally disable a warning. In the future, the default value of this option is planned to change and the warning will be removed.

But anyways, I'm currently considering that it would be even better to go all the way towards the solution I recommended in https://github.com/coq/coq/issues/8027#issuecomment-441090197 and introduce `Universes` option with possible values, `"monomorphic"`, `"template"`, `"polymorphic"`, `"cumulative"` and same for the values of the `universes` attribute. In 8.10, we would emit the auto template warning if this option is unset and there are no attributes. In 8.11, we would make `"monomorphic"` the default value and stop emitting the warning.

**Comment by SkySkimmer** [comment]
>In the future, the default value of this option is planned to change and the warning will be removed.

The whole option is going away, not just the default IMO.

**Comment by Zimmi48** [comment]
>The whole option is going away, not just the default IMO.

Why should there be a way of making universe polymorphism automatic but none for template polymorphism?

**Comment by SkySkimmer** [comment]
Because the option is actually "make template polymorphism some types chosen in an occult way"

**Comment by Zimmi48** [comment]
I see...

**Comment by herbelin** [comment]
I'm supportive of this PR.

Thanks for all the work aiming at clarifying how to work with universe polymorphism. A question though, @Skyskimmer, I don't understand what you mean by "chosen in an occult way"?

**Comment by SkySkimmer** [comment]
Why should there be a special meaning in using `Type` for inductive types? ie why would `Inductive prod A B : Type := pair : A -> B -> prod A B.` be template polymorphic but not `Inductive prod@{i j} (A:Type@{i}) (B:Type@{j}) : Type@{max(i,j)} := ...`? Especially when `Print prod` with print universes on will show the later one.

**Comment by herbelin** [comment]
> Why should there be a special meaning in using `Type` for inductive types?

Why `Type` has a special meaning in inductive types is somehow a convention. It was at a time where there was not the rich language of universes that we have now. It was at a time where we were not considering different forms of polymorphism but were instead looking for a default form of polymorphism obtained without extra syntax.

> ie why would `Inductive prod A B : Type := pair : A -> B -> prod A B.` be template polymorphic but not `Inductive prod@{i j} (A:Type@{i}) (B:Type@{j}) : Type@{max(i,j)} := ...`? Especially when `Print prod` with print universes on will show the later one.

Are you saying that there is no big difference between template polymorphism and the "full" polymorphism? If yes, I will agree. We can certainly reformulate the current implementation of template polymorphism as a particular case of full polymorphism where generalization is only on the conclusion of parameters (i.e. not on occurrences of`Type` in the types of constructors) and where instantiation of universes uses an ad hoc form of implicit arguments:

- `template_polymorphic_prod A B := prod@{inferred-level-of-A,inferred-level-of-B} A B`
- `template_polymorphic_prod A := prod@{inferred-level-of-A,prod.u1} A` (which can alternatively be seen as an eta-reduction of `fun B : Type@{prod.u1} => prod@{inferred-level-of-A,inferred-level-of-B} A B`)
- `template_polymorphic_prod :=prod@{prod.u0,prod.u1}` (which can alternatively be seen also as an eta-reduction of `fun (A : Type@{prod.u0}) (B : Type@{prod.u1}) => prod@{inferred-level-of-A,inferred-level-of-B} A B`)

With all the "uglyness" of having universe quantifiers only prenex and to use fixed levels (the `prod.u0` and `prod.u1`) to fill these quantifiers whenever `prod` is not fully applied.

But I'm unsure to exactly answer your comment. For instance, do you agree with the view I give above of "template polymorphism"?

**Comment by SkySkimmer** [comment]
>Are you saying that there is no big difference between template polymorphism and the "full" polymorphism? 

No, I'm saying that using the type annotation to decide between monomorphic and template polymorphic is confusing (it certainly confused me for a while).

>But I'm unsure to exactly answer your comment.

The question is how should the choice between template poly and monomorphic be made. I want to move towards only explicit and specific annotations (currently using the attribute system), this PR goes in another direction.

**Comment by Zimmi48** [comment]
I had missed the "lack of explicitness considered harmful" meaning in Gaëtan's PR. I will close this PR because it goes indeed against this spirit but I strongly recommend making the doc better.

First, the warning should be in the "deprecated" category, e.g. "Automatically declaring an inductive type template polymorphic is deprecated: make this explicit with an attribute or disable this behavior with option...".

Then, the documentation of the option should make the plan that this option will eventually be turned off by default explicit, and the warning should be documented alongside.

**Pull request closed without merging**
