### PR TITLE
Trunk+fix coq makefile test suite on nixos

### PR DESCRIPTION
**Pull request by Zimmi48**
Commit 92792db isn't actually necessary but should be harmless and as @ejgallego said it is always more robust to use a specific shell instead of the default `/bin/sh` because you might be using e.g. bash features without realizing it and then it will fail on some other's machine where the default shell is different.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]

**Comment by gares** [comment]
Hum, which bash-only feature do I use?

**Comment by gares** [comment]
Do you really experience a bug on nixos?

**Comment by gares** [comment]
The PR works fine on my github space but for UniMath. I've seen a commit changing the overlay, not sure the new overlay includes my little fix the their Makefile

**Comment by Zimmi48** [comment]
@gares 
> Hum, which bash-only feature do I use?

I suppose you don't but I can't be sure unless I trust you or I trust myself because the only other way would be to run these tests with every possible shells. For reproducibility it's much better to decide that the tests depend on a specific shell (bash) because then we can be sure that they are always run in a similar environment.

> Do you really experience a bug on nixos?

I  do. I talked about it on Gitter. Basically, I had all the tests starting by `#!/bin/bash` failing because there is no such executable on NixOS. The only two commands that are available from a fixed path under NixOS are `/bin/sh` and `/usr/bin/env` and the latter must be used to call any other command in a shebang such as bash, python... (but it's already very common to see that in the wild, so it isn't purely NixOS-related).

**Pull request merged**
