### PR TITLE
Extra work on ltac printing: fixing #5787, some parentheses

### PR DESCRIPTION
**Pull request by herbelin**
These are two fixes and a feature extending the recent #6047 (edited: feature moved to PR #6158):

- Fixing printing of `constr:` in ltac arguments (#5787)
- Fixing extra parentheses in printing tactic arguments
- Offering the possibility to use a level also for raw and glob printers and not only for top printers as in #6047 (edited: moved to PR #6158)

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by Zimmi48** [comment]
There are some conflicts.

(@maximedenes: Remember to put a comment when adding a `needs: rebase` label because just adding labels does not trigger notifications. So the PR author can overlook the needed action on their side, which results in avoidable delays.)

**Comment by Zimmi48** [comment]
Two remarks:
- is it easy separating the fixes and the feature so as to make backporting to 8.7 possible or shall we say that these are 8.8-only fixes?
- try using "fix" or "fixes" instead of "fixing" (remember: GitHub is dumb) and adding a space between "PR" and "#' in commit messages.

**Comment by herbelin** [comment]
> is it easy separating the fixes and the feature so as to make backporting to 8.7 possible or shall we say that these are 8.8-only fixes?

Done (feature in #6158).

> try using "fix" or "fixes" instead of "fixing" (remember: GitHub is dumb) and adding a space between "PR" and "#' in commit messages.

Done.

Rebase: done.

**Comment by Zimmi48** [comment]
Thanks!

**Comment by maximedenes** [comment]
Waiting for Travis. Will merge once tested.

**Comment by maximedenes** [comment]
Test-suite fails.

**Comment by herbelin** [comment]
Should hopefully be ok now.

**Comment by maximedenes** [comment]
Succeeded here: https://travis-ci.org/herbelin/github-coq/builds/304916532 so will merge to reduce Travis backlog.

**Comment by Zimmi48** [comment]
Merging one PR alone does not really reduce the backlog because it creates a new build job on the master branch ;-)
Will backport later with other PRs to reduce Travis load.

**Pull request merged**
