### PR TITLE
Add CACHEKEY editing step to release process.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Maybe it should also advise that to build the new image you need to trigger the build manually on GitLab because the bot only runs this step manually when the Dockerfile has changed (unless you want to refine the bot's criterion).

**Comment by ejgallego** [comment]
We used to have the cachekey in the `Dockerfile` precisely for this purpose. Maybe we could set some variable such as `COQ_BRANCH_DOCKER=master` that could be updated?

**Comment by Zimmi48** [comment]
> Maybe we could set some variable such as `COQ_BRANCH_DOCKER=master` that could be updated?

This sounds like a good suggestion!

**Comment by SkySkimmer** [comment]
Can't we have the bot look at CACHEKEY instead of dockerfile?

**Comment by ejgallego** [comment]
Ok, one way or another seems fine to me. Let's open an issue about it before I merge this PR so we don't forget tho.

**Comment by SkySkimmer** [comment]
https://github.com/coq/bot/issues/235

**Comment by ejgallego** [comment]
@coqbot: merge now

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Pull request merged**
