### PR TITLE
Stop using flambda for fiat-crypto connected jobs

### LINKED ISSUE #12400: Coq's CI fails on at least some developments using native_compute due to incompatible OCaml versions (fiat-crypto)
#### Description of the problem

```
File "/tmp/Coq_native97170a/Coq_native2ba814.native", line 1:
 Error: /builds/coq/coq/_install_ci/lib/coq/kernel/nativevalues.cmi
 is not a compiled interface for this version of OCaml.
 It seems to be for a newer version of OCaml.
 Finished failing transaction in 1.16 secs (0.017u,0.007s) (failure)
 File "./src/UnsaturatedSolinasHeuristics/Tests.v", line 138, characters 0-459:
 Error: Native compiler exited with status 2
 Command exited with non-zero status 1
```
https://gitlab.com/coq/coq/-/jobs/565436568

cc @coq/ci-maintainers 

#### Coq Version

16e0877c6e3ec6228875e10afb1ec17d640eb1e9

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #12400

### CODE REVIEW

**Comment by SkySkimmer** [comment]
This needs backporting as the bug is since c7b82d512e15c857cf8176dfae9584fdf203fafa / https://github.com/coq/coq/pull/12036

**Review by Zimmi48 — APPROVED** [review]
This is indeed the only reasonable thing to do. Too bad to stop using flambda on so many jobs but that's the issue with using a language that provides such low compatibility between versions...

**Comment by Zimmi48** [comment]
I'll merge tomorrow.

**Comment by ejgallego** [comment]
I'm not so convinced this is the way to go; I'd like we think a bit more. A few (disconnected thoughts):
- fiat crypto is almost 3h so it feels a tad heavy to me, maybe we should return to flambda and disable the tests that are too heavy for ocamlc?
- the way we do install in the CI is indeed a problem, on the other hand using a composed build should prevent this problem; how will we approach that?
- instead of doing this change, we could provide two versions of bignums, indeed, one would imagine a better versioning setup for artifacts.

**Comment by Zimmi48** [comment]
Only the first of your three proposals seems immediately applicable to me... And we should really merge a fix in 8.12+beta1.

**Comment by ejgallego** [comment]
> Only the first of your three proposals seems immediately applicable to me... And we should really merge a fix in 8.12+beta1.

3rd one is also fine I think; it is likely that we the time we lose by compiling another fiat-crypto is recovered by the gains we have in other devs.

**Comment by ejgallego** [comment]
First proposal also makes sense to me as f-c is super heavy so even a 5-10% gain would help IMO. Let's see what @JasonGross thinks; indeed we shouldn't delay this ideally later than tomorrow.

**Comment by Zimmi48** [comment]
> > Only the first of your three proposals seems immediately applicable to me... And we should really merge a fix in 8.12+beta1.
> 
> 3rd one is also fine I think; it is likely that we the time we lose by compiling another fiat-crypto is recovered by the gains we have in other devs.

Right, coqprime could be a second stage job recompiling its own version of bignums.

**Comment by ejgallego** [comment]
> Right, coqprime could be a second stage job recompiling its own version of bignums.

I was more thinking of adding `bignums:base` and `bignums:edge`

**Comment by JasonGross** [comment]
I'm a bit concerned about disabling the tests that are too heavy for ocamlopt in fiat-crypto.  As I understand it, all of the extracted code is too heavy for ocamlopt + flambda, and I don't want Coq to end up moving to compatibility only with a version of OCaml that can't handle the extracted code.  Here are some options I see:
1. I could use `vm_compute` rather than `native_compute` in fiat-crypto, and trim down the test-case so this doesn't add much time (it's a shame, though, as the one file we use it in is about 87% faster with native_compute than vm_compute)
2. I could give you all a somewhat lighter target.  For example, simply removing the heaviest extracted file from the build would shave off about half an hour of serial build time.  (I could shave off more than that by leaving only the lightest of the extracted files.)
3. I could possibly put in some time optimizing some parts of fiat-crypto, such as our reification.  I think optimizing the reification code might allow ocamlopt + flamda to handle things, but it's going to be a pain to do, and will probably take a couple weeks.

I could even do both 1 and 2 at the same time, if desired.

**Comment by ejgallego** [comment]
Hi @JasonGross ,

overall my main concern is that f-c is getting quite close to the 3h mark and indeed some jobs have been failing of pure timeouts. I think that a medium-term goal of the CI is to support such large builds, however IMO we are not ready yet to handle such large tests.

> I'm a bit concerned about disabling the tests that are too heavy for ocamlopt in fiat-crypto. As I understand it, all of the extracted code is too heavy for ocamlopt + flambda, and I don't want Coq to end up moving to compatibility only with a version of OCaml that can't handle the extracted code.

IMHO that's not a big risk, in the sense that I would omit only the test that is too heavy, but keep others still in the CI. Coq will be supported in both flambda / non-flambda for the near future.

> Here are some options I see:
> 
> 1. I could use `vm_compute` rather than `native_compute` in fiat-crypto, and trim down the test-case so this doesn't add much time (it's a shame, though, as the one file we use it in is about 87% faster with native_compute than vm_compute)

IMO I wouldn't go that route, I think it is good that we are testing native_compute, which is fairly understested as of today.

> 2. I could give you all a somewhat lighter target.  For example, simply removing the heaviest extracted file from the build would shave off about half an hour of serial build time.  (I could shave off more than that by leaving only the lightest of the extracted files.)

That may be cool, as indeed would put f-c back to around 2h (or even less if we can use flambda). How hard would it be to run these heavy tests as their own CI job?

> 3. I could possibly put in some time optimizing some parts of fiat-crypto, such as our reification.  I think optimizing the reification code might allow ocamlopt + flamda to handle things, but it's going to be a pain to do, and will probably take a couple weeks.

That would be cool, but IMO not necessary. I think we can do two builds of bignums for now.

**Comment by JasonGross** [comment]
> That may be cool, as indeed would put f-c back to around 2h (or even less if we can use flambda). How hard would it be to run these heavy tests as their own CI job?

It depends how the communication between artifacts works.  I see the following options:
1. If we get the same build directory, we can split up the jobs however we want; once the code is extracted, it's basically standalone, and once it's compiled, it's even more standalone.  So we could extract the code in the flambda job, and build it and run it in the next job with not flambda.
2. If we have to install the development, then it's significantly easier for me if we extract+compile in the same job (this would still be too heavy for flambda), and then it should be pretty easy to have a separate job that runs the extracted+compiled code (this job should almost never fail, unless extraction is broken in a way that leaves it syntactically valid but semantically broken).
3. I could make a variant of the install target that installs the .ml files, and then build them in a separate job.  I'd really rather not though.

Overall, I'd prefer 1, if that's possible with the CI setup.

> IMHO that's not a big risk, in the sense that I would omit only the test that is too heavy, but keep others still in the CI. Coq will be supported in both flambda / non-flambda for the near future.

If I understand correctly, 4.10 cannot build fiat-crypto due to regressions, even without flambda enabled.  This is the issue that @ppedrot reported about quadratic closure compilation in OCaml , I'll try to dig it up if someone else doesn't first.  And furthermore, "omit only the test that is too heavy" would be reassuring if any of our OCaml tests were not too heavy for flambda, but as I understand it, of our 8 or so of our extracted files, each of which takes about 30--60 seconds to compile in 4.05 (4.06?) without flambda, all of them are too heavy with flambda.  (The heavy tests that I'd be excluding to reduce the CI time are tests that involve running these compiled binaries.)

**Comment by ejgallego** [comment]
> If I understand correctly, 4.10 cannot build fiat-crypto due to regressions, even without flambda enabled.

You mean the OCaml part? IMHO I'd keep the OCaml part quite separate from the Coq part, in the sense that OCaml regressions should be handled upstream.

It looks fine to me to try to split the Coq / OCaml jobs if possible.

**Comment by JasonGross** [comment]
@ejgallego I've now made targets that we can split as follows:
1. vMultithreaded targets not requiring OCaml compilation of extracted files: `pre-standalone-extracted printlite lite`
2. Single-threaded targets (still not requiring OCaml compilation of extracted files): `all-except-compiled`
3. Multithreaded targets for building the OCaml files and testing them: `standalone-ocaml lite-generated-files`
4. Multithreaded targets for heavy testing of the compiled extracted files: `all` (or `generated-files`)

Presumably we can put the first two jobs into one script that uses flambda, and then put the next two jobs (or you can just combine them and run the `all` target) into a separate job that uses non-flambda.

> in the sense that OCaml regressions should be handled upstream.

Sure, but it might be the case that something breaks extraction and we don't notice it without trying to compile the extracted code, and this provides a test of that.  (Perhaps we might also want to test compilation of extracted Haskell code too?)

**Comment by ejgallego** [comment]
Thanks @JasonGross , @SkySkimmer , can you update the PR? [Or if you are away we can take care]

> Sure, but it might be the case that something breaks extraction and we don't notice it without trying to compile the extracted code, and this provides a test of that. (Perhaps we might also want to test compilation of extracted Haskell code too?)

Indeed, what I mean is that we cannot consider OCaml [or Haskell] bugs blockers for Coq; actually it would make sense to extract the problematic code from your examples and add it to the OCaml test-suite itself.

For extraction, I have a feeling that would be better served by improving Coq's own test-suite, I dunno. We already have quite a few bugs open in that sense, not even MetaCoq can be compiled correctly by `master`

**Comment by SkySkimmer** [comment]
I'll let Jason implement his plan

**Comment by JasonGross** [comment]
https://github.com/coq/coq/pull/12431

**Pull request closed without merging**
