### PR TITLE
Fix `remember` with sort polymorphic equality and values

### LINKED ISSUE #19203: `remember` cannot handle sort-polymorphic registered equality.
### Description of the problem

I'm trying to use a sort-polymorphic equality to show some stuff with sort-polymorphic booleans, but I noticed the equation generation of `remember` doesn't support this use case, generating binders with the wrong relevance. `Validate Proof` generates an anomaly.

The second example uses ssreflect, and ssreflect's `rewrite` cannot handle this sort-polymorphic equality either. Using `rewrite ->` instead works.

### Small Coq file to reproduce the bug

```coq
Set Universe Polymorphism.

Inductive bool@{q| |} : Type@{q|Set} := | true : bool | false : bool.

Definition nand@{q| |} (a b : bool@{q|}) : bool@{q|} :=
  match a , b with
  | true , true => false
  | _ , _ => true
  end.

Inductive seq@{q|u|} {A : Type@{q|u}} (a : A) : A -> Type@{q|u} := | srefl : seq a a.
Arguments srefl {_ _}.

Definition seq_elim@{q|u v|} :=
  fun (A : Type@{q|u}) (x : A) (P : A -> Type@{q|v}) (f : P x) (a : A) (e : seq x a) =>
  match e in (seq _ a0) return (P a0) with
  | srefl => f
  end.

Register seq as core.eq.type.
Register srefl as core.eq.refl.
Register seq_elim as core.eq.rect.

Lemma f3_eq_f@{q| |} (f : bool@{q|} -> bool@{q|}) (x : bool@{q|}) : seq (f (f (f x))) (f x).
Proof.
  remember (f true) as b eqn : ftrue.
  remember (f false) as c eqn : ffalse.
  Show Proof.
  Validate Proof.
Abort.

Require Import ssreflect.
Lemma f3_eq_f@{q| |} (f : bool@{q|} -> bool@{q|}) (x : bool@{q|}) : seq (f (f (f x))) (f x).
Proof.
  assert (seq (f true) (f true)) as ftrue by reflexivity.
  move: {2}(f true) ftrue => b ftrue.
  assert (seq (f false) (f false)) as ffalse by reflexivity.
  move: {2}(f false) ffalse => c ffalse.
  destruct b; destruct c; destruct x; now do 3 first [rewrite ftrue|rewrite ffalse].
Admitted.
```

### Version of Coq where this bug occurs

8.19.2

### Last version of Coq where the bug did not occur

_No response_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #19203 (the ssr part should be treated as a separate bug)

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
CI failures spurious, @coqbot merge now

**Comment by proux01** [comment]
@ppedrot master shows a failure on VST: https://gitlab.inria.fr/coq/coq/-/jobs/4444412 could it be a bad interaction between recently merged PRs ? (the CI was 3 days "old")

**Comment by ppedrot** [comment]
I don't think that this precise PR could have any negative effect on the CI. What are the other recently merged PRs?

**Comment by SkySkimmer** [comment]
First master failure is https://gitlab.inria.fr/coq/coq/-/jobs/4443580, master before that succeeded https://gitlab.inria.fr/coq/coq/-/jobs/4439906

**Comment by SkySkimmer** [comment]
Both ran on the current vst commit (https://github.com/PrincetonUniversity/VST/commit/0eed04f85ecfa9607d200b37aa69ac0fb39a1071)

**Comment by SkySkimmer** [comment]
Probably https://github.com/AbsInt/CompCert/pull/513 broke vst

**Pull request merged**
