### PR TITLE
Syntactically delimit match construct (fix #16284).

### LINKED ISSUE #16284: Regression in 8.16: Anomaly "Uncaught exception Failure("List.chop")."
When trying to port Interval to Coq 8.16, several files of its testsuite exhibit the following failure. This is a regression with respect to 8.15.

Presumably, the bug was introduced by #15923. @ppedrot 

```
Error: Anomaly "Uncaught exception Failure("List.chop")."
Please report at http://coq.inria.fr/bugs/.
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Cbv.cbv_stack_value in file "pretyping/cbv.ml", line 632, characters 18-38
Called from Cbv.norm_head in file "pretyping/cbv.ml", line 498, characters 29-60
Called from Cbv.cbv_stack_term in file "pretyping/cbv.ml", line 560, characters 27-55
Called from Cbv.norm_head in file "pretyping/cbv.ml", line 498, characters 29-60
Called from Cbv.cbv_stack_term in file "pretyping/cbv.ml" (inlined), line 560, characters 27-55
Called from Cbv.cbv_value_cache in file "pretyping/cbv.ml", line 670, characters 16-56
Called from Cbv.norm_head_ref in file "pretyping/cbv.ml", line 534, characters 10-36
Called from Cbv.cbv_stack_term in file "pretyping/cbv.ml" (inlined), line 560, characters 27-55
Called from Cbv.cbv_stack_value in file "pretyping/cbv.ml", line 603, characters 8-50
Called from Cbv.norm_head.fold in file "pretyping/cbv.ml", line 455, characters 22-51
Called from Stdlib__Array.fold_right in file "array.ml", line 184, characters 9-30
Called from Cbv.norm_head in file "pretyping/cbv.ml", line 460, characters 21-51
Called from Cbv.cbv_stack_term in file "pretyping/cbv.ml" (inlined), line 560, characters 27-55
Called from Cbv.cbv_stack_value.apply in file "pretyping/cbv.ml", line 569, characters 8-37
Called from Cbv.norm_head.fold in file "pretyping/cbv.ml", line 455, characters 22-51
Called from Stdlib__Array.fold_right in file "array.ml", line 184, characters 9-30
Called from Cbv.norm_head in file "pretyping/cbv.ml", line 460, characters 21-51
Called from Cbv.cbv_stack_term in file "pretyping/cbv.ml" (inlined), line 560, characters 27-55
Called from Cbv.cbv_stack_value in file "pretyping/cbv.ml", line 616, characters 8-50
Called from Cbv.cbv_stack_term in file "pretyping/cbv.ml" (inlined), line 560, characters 2-55
Called from Cbv.cbv_norm_term in file "pretyping/cbv.ml", line 718, characters 22-53
Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27
Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11
Called from Cbv.cbv_norm in file "pretyping/cbv.ml", line 762, characters 20-80
Called from Redexpr.e_red in file "tactics/redexpr.ml" (inlined), line 201, characters 29-40
Called from Redexpr.reduction_of_red_expr_val in file "tactics/redexpr.ml", line 247, characters 14-38
...
```

### PR DESCRIPTION
**Pull request by silene**
Fixes / closes #16284

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Do not assign other people.

**Comment by silene** [comment]
Please do not unassign the release manager for Coq 8.16 unless you think it is not a blocker for the release of 8.16.

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
Blame points to https://github.com/coq/coq/commit/712a63aa0acca547cc45d7dae9ef541e2b754dc2 so @ppedrot should be in the loop anyway.

**Review by ppedrot — APPROVED** [review]
Not the first time we have funny errors introduced this way. At least it's not in the kernel this time...

**Comment by gares** [comment]
@coqbot merge now

**Comment by maximedenes** [comment]
Isn't this PR missing a regression test?

**Comment by silene** [comment]
Yes. But I was unable to make a self-contained one.

**Pull request merged**
