### PR TITLE
Small pretyping/ cleanups

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by herbelin** [comment]
I like the idea, but it is not fully clear to me that having `typing.ml`, `reductionops`, `inductiveops`, `cbv.ml`, `arguments_renaming.ml`, `retyping`, `pretype_errors.ml` ... in `unification`, but `unification.ml` in `pretyping` is intelligible. Maybe dispatch into three directories, or move some files to `engine`.

> `unification.ml` cannot be easily moved

Would cutting it in two parts work?

**Comment by ppedrot** [comment]
@herbelin you probably commented in the wrong PR and should move the message to #15303. This one is only about some minimal cleanups.

**Comment by ppedrot** [comment]
No need to wait too much, this is fairly trivial. Let's merge.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
