### PR TITLE
Remove ad-hoc xor function, making the logic more explicit.

### PR DESCRIPTION
**Pull request by maximedenes**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
I propose instead we just always print `Monomorphic`/`Polymorphic`.

**Comment by maximedenes** [comment]
> I propose instead we just always print Monomorphic/Polymorphic (which is what we do for (Non)Cumulative).

Sounds good indeed.

**Comment by maximedenes** [comment]
Test suite needs updating.

**Comment by maximedenes** [comment]
>> I propose instead we just always print Monomorphic/Polymorphic (which is what we do for (Non)Cumulative).
> Sounds good indeed.

In fact, I changed my mind. I don't think it is a good idea to print this, as it is very confusing for beginners. In particular, nothing says it is about universes...

**Pull request closed without merging**
