### PR TITLE
Fix #9351 in master (Add Flocq, CoqInterval, Gappa tool and Gappa)

### LINKED ISSUE #9351: Windows installer: and Flocq and Interval as packages to Windows installer
I want to add Flocq (indepdendent of VST or CompCert) and Coq-Interval as Windows installer packages. On the way I would also add Interval to CI.

Configuring and building Flocq and Interval is straight forward, but there are a few issues with remake install:

- cause of the mix of MinGW and cygwin, the install path ends up to have a \r in it, which is added to the path - likely some issue with awk (it does not strip \r on cygwin)
- examples are not installed
- README is not installed
- quite a few (but not all) examples import Interval with Require Import Interval_tactic (without Interval.)

I think the last one should be fixed in the Interval sources, but for the install issues I am not so sure. Redoing the installer and including examples and README would be 3 lines in the shell script. On the other hand fixing the \r issue might be rather intricate since I think awk or whatever is called via some automake / configure magic, so that I can't easily add a strip (might have to patch automake). We had a lot of similar issues with sed and I ended up compiling a patched sed which strips \r.

@silene : First I hope that you don't have any objections against adding Flocq and Interval. Then I would like to have your opinion on how to get around the install issues:

a) simply write my own install procedure
b) Fix the /r issue and add installation of examples and README to the remake install target

### PR DESCRIPTION
**Pull request by MSoegtropIMC**
As requested in #10500, this adds the following addons to the Windows installer:

- Flocq,
- CoInterval
- Gappa tool
- Gappa plugin

This was already done in 8.9.1 with PR #9792.

Note: a cherry pick of the corresponding commit in 8.9.1 failed badly, so I merged this over manually.

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Note: I started the Gitlab CI manually with `WINDOWS=enabled_all_addons`. Otherwise CI for this PR wouldn't be meaningful.

**Comment by MSoegtropIMC** [comment]
Note on the patches: 
- for matc2 I created PR <https://github.com/Mtac2/Mtac2/pull/220> upstream
- for flocq, gappa and interval I sent the patches to @silene via email - inria gitlab doesn't allow external PRs (as far as I can tell).

**Comment by SkySkimmer** [comment]
This stuff (except flocq) isn't in the regular CI, should it be?

**Comment by MSoegtropIMC** [comment]
> This stuff (except flocq) isn't in the regular CI, should it be?

Yes, something I have on my todo list. Gappa tool might not be that trivial to build, though - it requires among other things BOOST and the GMP and MPFR multi precision libraries. Gappa-plugin could be built without gappa tool to see if the OCaml stuff is compatible, but one obviously couldn't test it without the tool.

Interval is pure Coq, though, so it should be trivial to add a CI test. Maybe I do this first until I have time to add a test for Gappa. For the time being we could enable Gappa in the windows64 build to have some testing.

**Comment by MSoegtropIMC** [comment]
> Yes, I think you should add both Interval and the plugin part of Gappa to CI without waiting further. This would allow Coq devs to keep the plugin building with Coq master.

Sure, I will do this. But let's do it as a separate PR. I would prefer to see if gappa tool is indeed substantial effort or can be done in an hour or so.

Btw.: @silene wrote the patches I sent will be upstream   some time soon.

**Comment by ejgallego** [comment]
> Yes, I think you should add both Interval and the plugin part of Gappa to CI without waiting further. This would allow Coq devs to keep the plugin building with Coq master.

What does the Gappa / Interval authors think about this?

It should be them IMHO who propose this addition. For a start I wonder about where are these projects hosted and what's their CI policy.

**Comment by MSoegtropIMC** [comment]
> It should be them IMHO who propose this addition. For a start I wonder about where are these projects hosted and what's their CI policy.

These projects are hosted at `gitlab.inria.fr`. As far as I can tell there is no automated CI for these projects on the project side. There are no references to test results in the commit lists, which I guess would be there if CI would be run automatically.

@silene : I guess you can speak for the authors of these projects. Can you give your opinion on putting these under main Coq CI? As you know we already build them with the Windows installer, but it is not tested regularly there - add-ons are only built on release branches, not on master for CI performance reasons.

**Comment by ejgallego** [comment]
> These projects are hosted at `gitlab.inria.fr`. As far as I can tell there is no automated CI for these projects on the project side.

I'm much afraid that the upcoming platform / CI tooling will not be able to deal with closed hosting, so that's a serious problem I'm much afraid :S :S

**Comment by silene** [comment]
I am not proposing the addition of CoqInterval and Gappa to Coq's continuous integration. (And I didn't propose the addition of Flocq or Coquelicot either, for that matter.) I understand how adding these projects might help Coq improve its backward compatibility story. That is why I won't oppose it (nor did I oppose the addition of Flocq and Coquelicot), but that is about it.

**Comment by ejgallego** [comment]
> I didn't propose the addition of Flocq or Coquelicot either, for that matter

I added these projects personally as I was distributing them with jsCoq and I thought they were important projects to test against.

But that was like 3 years ago and I hope we re-evaluate CI policy in the fall, with particular emphasis towards automating full-scale refactoring.

Of course I need to discuss with the other maintainers but it is my impression that projects that don't explicitly solicit to be included in the CI will be very likely dropped, thus backwards compatibility for such projects won't be guaranteed anymore.

Thus I guess this could be a good moment for package authors to think what kind of model they would like to see in their relationship with Coq, so hopefully we can do something that makes everyone happy.

**Comment by MSoegtropIMC** [comment]
@silene: does that mean that you would prefer to keep it as is, that is that these modules are in the Windows installer and we fix possible issues shortly before a release, in case there are any?

**Comment by MSoegtropIMC** [comment]
@ejgallego : is there are discussion on platform / CI policy going on somewhere in public?

**Comment by Zimmi48** [comment]
If we don't have the invariant that the platform is a strict subset of what is tested in CI, then it starts to make a lot of sense to have the platform being developed as a separate repository...

**Comment by ejgallego** [comment]
> @ejgallego : is there are discussion on platform / CI policy going on somewhere in public?

Sure, for now is mostly de-centralized (gitter, mailing list, etc...) but I am trying to organize it more. Just as you wrote I was creating a project to recopilate issues, but I think that somebody (likely @Zimmi48 ) already created it, https://github.com/coq/coq/projects/34 , we also have https://github.com/coq/coq/projects/20 which seems a bit redundant so maybe we should merge both.

I think the discussion about the platform proper will start in the next Working Group, and from there we will see where to go.

**Comment by ejgallego** [comment]
> If we don't have the invariant that the platform is a strict subset of what is tested in CI, then it starts to make a lot of sense to have the platform being developed as a separate repository...

Yup indeed it seems to me that the platform will have wider scope than CI.

CI I think can only be supported for projects that are willing to collaborate with the Coq team to keep things running, but of course it is very legitimate to consider that a big load and prefer to deal only with releases.

**Comment by MSoegtropIMC** [comment]
@vbgl: a short progress note: I am struggling a bit with the upstream merges of the windows configure patches. See <https://gitlab.inria.fr/coqinterval/interval/issues/1>. This used to work with applying the patches locally and I have not the slightest clue what is going wrong now. @silene did some minor changes to the patches, but they should be fine and I don't see how these changes could cause the effects I see.

**Comment by MSoegtropIMC** [comment]
@vbgl: the CI failures are spurious (it did ran through with a reduced Windows test before).

So I would say this is ready for merge.

**Comment by Zimmi48** [comment]
@ejgallego What is [this Dune test-suite error](https://gitlab.com/coq/coq/-/jobs/255722421)? I have never seen it before and it worries me that we are going to ignore it without trying to understand it, even though it is most likely unrelated to this PR. (Re-running just in case.)

**Comment by ejgallego** [comment]
@Zimmi48 the `build_all_stdlib.sh` script exited with a return code of 127, maybe a disk-space issue? Hard to tell, I guess we should improve the script so it reports what is wrong.

Indeed, running in a regular worker seems to have succeeded.

**Review by vbgl — APPROVED** [review]

**Comment by vbgl** [comment]
Thanks Michael. This seems good to go.

Ping @maximedenes, secondary maintainer of `/dev/build/windows`.

**Comment by MSoegtropIMC** [comment]
Thanks for merging - I will make a backport to 8.10 and rebase #10500 to this (both in one PR).

Btw.: CoqInterval has a serious regression vs the version we have in 8.9.1 - see <https://gitlab.inria.fr/coqinterval/interval/issues/2>. I need to check if this is also there in 8.10.

**Comment by Zimmi48** [comment]
>I will make a backport to 8.10

Do you have reasons to think that a standard automatic backport won't work?

**Comment by MSoegtropIMC** [comment]
> Do you have reasons to think that a standard automatic backport won't work?

As long as it is 8.10 is not picked it should work. But I need it in order to continue with #10500 

@vbgl : can you do the backport to 8.10 some time soon?

**Comment by vbgl** [comment]
Here you go: https://gitlab.com/coq/coq/pipelines/72251527

**Comment by vbgl** [comment]
The job failed; apparently because of Mtac2: https://coq.gitlab.io/-/coq/-/jobs/256998375/artifacts/artifacts/buildlogs/mtac2-bddfd3e8b36fbe6fead5254342eb2f082ff36179-make-install_err.txt

**Comment by MSoegtropIMC** [comment]
Ah yes, the version of mtac2 needs to be updated because I removed the local patch.
See <https://github.com/Mtac2/Mtac2/pull/220>.
It works on master because Coq master pulls in mtac2 master.
Can you do this or shall I do it?

**Comment by vbgl** [comment]
I’ll give a try. Thanks for the hint.

**Comment by vbgl** [comment]
This time it worked: https://gitlab.com/coq/coq/pipelines/72479484 The windows64 jobs had all add-ons enabled.

**Pull request merged**
