### PR TITLE
Use Cases to implement "let (x, y) := ..." instead of adhoc implem

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #14774, probably others too

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Equations fails on something like
~~~coq 
Require Import Program.Tactics.

Program Definition foo (x:{m|m > 0}) := let (k,_) := x in k.
~~~
The term `x` gets de-programmed to the first projection which has type `nat` and so cannot be let-destructed. In master program mode is not used when checking that the let value is in an inductive type.

Not sure if we want to keep this change.

**Comment by SkySkimmer** [comment]
@coqbot ci minimize

**Comment by SkySkimmer** [comment]
The fiat-crypto error (both legacy and master) seems to be about
~~~coq
Definition Let_In {A P} (x : A) (f : forall a : A, P a) : P x := let y := x in f y.

Section MontgomeryCurve.

  Context {Z F:Type}.

  Check fun (xy:F * F) =>
        Let_In true (fun b =>
        let (x, y) := xy in
        (x,y)).
(* Error: In environment
Z : Type
F : Type
xy : F * F
b : bool
x : F
y : F
Unable to unify "(F * F)%type" with "?T@{x0:=(x, y)} b" (cannot unify "F" and "b").
*)
~~~
In master this passes, in this PR it fails with the commented error.

As one might expect, the same error can be gotten in master by using `let '(x,y) := ...` instead of `let (x,y) := ...`.

This is quite a strange unification error, is there any chance to solve this problem? cc @herbelin

**Comment by JasonGross** [comment]
> This is quite a strange unification error, is there any chance to solve this problem? 

I suspect part of the issue is that this doesn't quite fall within the pattern fragment because Coq doesn't know that it can invert constructors to find variables.  (I guess technically you'd need primitive projections on for this to truly fall within the pattern fragment.)

**Comment by SkySkimmer** [comment]
It's a bit more complicated than that, for instance 
~~~coq
  Check
    let T0 := fun (xy : F * F) (b:Z) => _ : Type in
    fun x y b =>
    let T := T0 (x, y) b in
    fun z : T => z : F * F.

   Check
    let T0 := fun xy : F * F => _ : Z -> Type in
    fun x y b =>
    let T := T0 (x, y) b in
    fun z : T => z : F * F.
~~~
The first Check succeeds, the second fails. Why does it matter whether `b` is part of the instance vs if it's an argument?

**Comment by JasonGross** [comment]
If I had to guess, I'd guess that in the first Check, the first-order heuristic gives the correct instantiation of the evar to F * F, while in the second Check, the first-order heuristic tries to instantiate the evar to `prod F`

**Comment by SkySkimmer** [comment]
In mathcomp it seems the 
~~~coq
Local Notation inlined_sub_rect :=
  (fun K K_S u => let (x, Px) as u  return K u := u in K_S x Px).
~~~
used through definition `sig_subType` produces a somehow different result.
The same error can be gotten in master and older (tested 8.11.2) by modifying the notation to 
~~~coq
Local Notation inlined_sub_rect :=
  (fun K K_S u => let '(exist x Px) as u := u return K u in K_S x Px).
~~~
(it's used at type `sig` throughout the minimized file)

The error 
~~~
Error: The LHS of __top_assumption_
    (hA (h i))
does not match any subterm of the goal
~~~
is strange in that it doesn't seem like we should be seeing that generated name in user messages. cc @coq/ssreflect-maintainers

**Comment by herbelin** [comment]
> I suspect part of the issue is that this doesn't quite fall within the pattern fragment because Coq doesn't know that it can invert constructors to find variables. (I guess technically you'd need primitive projections on for this to truly fall within the pattern fragment.)

Extending the pattern fragment to tuples is something which I have in mind! I think what is needed is only the ability to define projection so I don't think it strictly requires primitive projections.

Technically, in the `Let_In` example, what makes the example works is that let-tuple compilation uses the type of the right-hand side to infer the `return` clause, something that `match` compilation does not do. This is more difficult to do with `match` as 1) there is a priori an unlimited number of right-hand sides to take into account 2) the pattern is arbitrarily deep and, even if one may want to treat specially the unary case, computing in advance the typing context of the right-hand side is not so easy.

We may try to add the `LetTuple` return predicate strategy in the function `Cases.prepare_predicate` which is in charge of proposing a potential `return` type, but I would somehow lean towards instead first improving unification about which there are a few directions to follow (and then maybe delay this PR in the meantime, what do you think?).


> If I had to guess, I'd guess that in the first Check, the first-order heuristic gives the correct instantiation of the evar to F * F, while in the second Check, the first-order heuristic tries to instantiate the evar to `prod F`

Yes. The first case has the form `?e@{xy:=(x,y);b:=b}` so first-order heuristic is actually not applicable, while in the second case, it is the form `?e@{xy:=(x,y)} b` and the heuristics (call to `second_order_matching_with_args` in `apply_conversion_problem_heuristic`) is too shy to simply define `?e := fun _ => F * F`. (I vaguely remembered having tried to improve the heuristics once and concluded it would require the loop to better support backtracking so that e.g. when applying an heuristics to an equation happen to be incompatible with a further equation, another heuristic can be tried on the first equation. One day, we should take "the bull by the horns".)

**Comment by SkySkimmer** [comment]
ping @coq/ssreflect-maintainers about the `LHS of __top_assumption_` error

**Comment by SkySkimmer** [comment]
Using `return _` when no return is specified is more compatible in a few cases, but worse in general (https://gitlab.com/coq/coq/-/pipelines/369662181)

**Pull request closed without merging**
