### PR TITLE
Remove "VARIABLE" object, Print All, Print Section, Inspect

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
I have no idea of the underlying reason for removing these commands, and I guess the users won't have any idea either unless you give some hint in the changelog entry.
Usually, we don't remove commands that were not deprecated before. However, because these are query commands, it seems safe to remove without deprecation if the need for the removal is pressing.

**Comment by maximedenes** [comment]
I'm also surprised by the removal of these commands. I though instead we'd try to re-express the printable objects in direct style, to avoid having to inspect the tags.

What's the motivation?

**Comment by ejgallego** [comment]
A question here is why the print commands need to access "the objects" for printing, couldn't they just fold over the current environment in most cases? [Printing a closed section could be indeed a different story]

**Comment by SkySkimmer** [comment]
IMO the question is whether these commands are valuable enough to keep the dummy object for. Removing the dummy object would be a small gain in simplifying the code, so if we want to keep the Print variants it's probably not enough gain to justify refactoring them and we can just keep the dummy.

> [Printing a closed section could be indeed a different story]

@ejgallego Closed sections don't appear in objects, did you mean open sections?

**Comment by gares** [comment]
WG: This PR is missing two things. The Print All command is useful (debug or know automatically derived stuff) but the implementation based on the VARIABLE libobject is broken and ugly. But Print All would be useful even without printing section variables. Decision: we can remove the object, but the commands.

**Pull request closed without merging**
