### PR TITLE
[CI] elpi 1.0 has an official opam package

### PR DESCRIPTION
**Pull request by gares**
~~Blocked by ocaml/opam-repository#11870~~

Depends on #7367 ( requested by @ejgallego )

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM, @gares can you paste your private Travis build here?

**Comment by Zimmi48** [comment]
I don't understand this PR.

**Comment by SkySkimmer** [comment]
>I don't understand this PR.

IIUC `elpi` is a non-coq-specific package and we want to test `coq-elpi` which interacts with it and with Coq.

**Comment by ejgallego** [comment]
@gares please rebase so tests are ran again and please post a link to your personal Travis build for this branch.

**Comment by ejgallego** [comment]
link to full build https://travis-ci.org/gares/coq/builds/372001658

**Comment by ejgallego** [comment]
Umm, what's going on with circle :S

**Comment by SkySkimmer** [comment]
>Umm, what's going on with circle :S

It's unrelated to this PR except that it modifies the circle ci file.
It's grabbing a cache from before 05ad387ae6 which contains gtk opam packages. Then because we don't pin versions it wants to upgrade them and this breaks since we don't install gtk anymore.

**Comment by ejgallego** [comment]
So I guess cleaning the caches should be enough, pinning is not gonna work in this case.

**Comment by SkySkimmer** [comment]
See #7367.

**Comment by ejgallego** [comment]
@gares can you rebase on top of #7367

**Comment by gares** [comment]
I've anothe probllm on my side, then I'll rebase

**Comment by ejgallego** [comment]
> rebased: https://travis-ci.org/gares/coq/jobs/372044557 . It compiles!

Please don't cancel builds for private Travis branches in the future, this kind of PR could have some effect on other developments so I prefer to see a full build, that being said not a problem here.

**Comment by ejgallego** [comment]
Waited for appveyor just to have it randomly fail.

**Pull request merged**
