### PR TITLE
[experiment] Do not turn evars into metas in ssr FO hack.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot ci minimize

**Comment by ppedrot** [comment]
Extracted example from mathcomp:
```coq
Require Import Coq.ssr.ssreflect.

Parameter bigop : (nat -> bool) -> unit.

Axiom big_filter : forall (P : nat -> bool),
  eq tt (bigop (fun i : nat => P i)).

Goal forall (P : nat -> bool),
  eq
    (bigop (fun i : nat => true))
    (bigop (fun i : nat => P i)).
Proof.
intros.
rewrite -big_filter.
match goal with [ |- eq tt _ ] => idtac end. (* On master, rewrites the lhs of the equation, with this PR rewrites the rhs *)
```
Not sure what the evar-to-meta business has to do with that change...

**Comment by gares** [comment]
probably `?m i = true` fails on master, but works in this pr, where ?m is ?e

**Comment by ppedrot** [comment]
@gares even with a more dependent function this behaves the same. The original example had something like `fun i => andb (P i) (Q i)` instead of `fun i => true`.

**Comment by ppedrot** [comment]
Anyways, @gares if you have a bit of time one day I'd like to understand the ssr hacks for FO unification. Indeed, ssreflect is the last part of the code that uses metas in a non-well scoped way. All other places introduce metas through clenvs and clear them while calling Logic.refiner.

**Comment by gares** [comment]
Sure, next week. It codes a first pass wich does not perform conversion on arguments. IMO in mater this pass was worked ng on the lhs since metas don't even see it is an HO case

**Comment by gares** [comment]
this approach may be wrong, but I can help killing this piece of code

**Pull request closed without merging**
