### PR TITLE
Proof irrelevance

### PR DESCRIPTION
**Pull request by bMhLbkDUbUXp2pc9wU**

### CODE REVIEW

**Comment by herbelin** [comment]
These facts about proof-irrelevance are ok to me, but as there are specific to proof-irrelevance, I would rather see them in ProofIrrelevanceFacts.v.

The notation pip does not seem standard, nor is it appealing to me. At least "pi" would be a bit better. It is short and hence source of confusion, but keeping it Local would be ok.

**Comment by bMhLbkDUbUXp2pc9wU** [comment]
ProofIrrelevanceFacts.v talks of consequences of adding proof irrelevance axiom, but these proofs say about properties they are proof irrelevant, so I think they are here.

**Comment by herbelin** [comment]
Hi, but as ChoiceFacts and ClassicalFacts are about general properties of choice and classical axioms respectively, ProofIrrelevanceFacts could very well be generalized from "This defines the functor that build consequences of proof-irrelevance" to "Some facts and definitions concerning proof-irrelevance. Also defines the functor that build consequences of proof-irrelevance", with a table of contents, as it is the case in EqdepFacts, which is itself another example of file proving facts about an axiom (morally axiom K) and defining a module over this axiom. So, I would insist for having them in ProofIrrelevanceFacts.

**Comment by silene** [comment]
I tend to agree with Bmhl here: the NoDup_In_proof_irrelevant theorem is a consequence of the definitions of NoDup and In, and as such it belongs to the set of files defining these terms. If we were to put all the theorems proving proof irrelevance of predicates in a single file, we would obtain a file that would eventually depend on all the files of the standard library. This is hardly modular.

As for the NoDup_In_proof_irrelevant2 theorem, I feel it is kind of pointless, since it is an immediate consequence of the previous one composed with the decidability of equality. Worse, it requires a NoDup hypothesis. I understand why it is needed (the In predicate is intrinsically proof relevant), but once equality becomes decidable, you can define an In2 predicate that is equivalent to the In predicate yet proof irrelevant, even when the list contains duplicate elements. So I would simply get rid of it.

**Comment by bMhLbkDUbUXp2pc9wU** [comment]
> we would obtain a file that would eventually depend on all the files of the standard library

this is why I feel too

> I feel it is kind of pointless, since it is an immediate consequence of the previous one composed with the decidability of equality

I think because in a standard library people put wheels, not make everybody make the wheels. Decision procedures are normal, I think basing a helper on it is more useful.

> In2 predicate that is equivalent to the In predicate yet proof irrelevant
I will add a new pull request with this.

**Comment by bMhLbkDUbUXp2pc9wU** [comment]
>I will add a new pull request with this.

it needs a lot of stuff to change, so no pull req:

https://github.com/coq/coq/compare/trunk...bMhLbkDUbUXp2pc9wU:proof_irrelevant_In

**Comment by herbelin** [comment]
Silene, I agree with your concerns. I'm backtracking on my two comments and I'm coming with more questions (also reiterating Yves' questions).

What is the generality of the proposal? Why to state "pip" for "and", and not generically for all singleton types, including e.g those not in Prop? What is the specificity of In in the story and what other types or propositions would be legitimately equipped with a "pip" lemma? Why to call it pip and not, say is_singleton, or is_prop?

**Comment by bMhLbkDUbUXp2pc9wU** [comment]
>What is the generality of the proposal?

Not general, special for these, I needed.

> Why to state "pip" for "and", and not generically for all singleton types, including e.g those not in Prop?

I don't understand this: proof irrelevance is not true for Props, singletons in Set can destruct in all environments, don't need special treatment.

>What is the specificity of In in the story

I needed this proof, so I thought I share

>and what other types or propositions would be legitimately equipped with a "pip" lemma?

I like developing without axioms, so ideally all props :)

>Why to call it pip and not, say is_singleton, or is_prop?

no reason, just a local notation, I can change to anything you like

**Comment by herbelin** [comment]
> I don't understand this: proof irrelevance is not true for Props, singletons in Set can destruct in all environments, don't need special treatment.

Sorry, I don't understand either. Why are you referring to "destruct"? Maybe could you explain your typical usage of pi_In_proof_irrelevant?

**Comment by bMhLbkDUbUXp2pc9wU** [comment]
>>I don't understand this: proof irrelevance is not true for Props, singletons in Set can destruct in all environments, don't need special treatment.

>Sorry, I don't understand either. Why are you referring to "destruct"? Maybe could you explain your typical usage of pi_In_proof_irrelevant?

I don't use `pi_In_proof_irrelevan`, just was an idea that I not liked.

typical is with In: `Goal forall A (l : list A) (x y : {a | In a l}), proj1_sig x = proj1_sig y -> x = y.`

destruct: I misunderstanded you

 singleton in Set I don't needed, singleton in Prop I needed sometime :). Proof irrelevance is a thing, "value irrelevance" I never know.

**Comment by maximedenes** [comment]
test build

**Comment by maximedenes** [comment]
test build

**Pull request closed without merging**
