### PR TITLE
Inline calls to Functional Scheme in FMapAVL.

### PR DESCRIPTION
**Pull request by ppedrot**
This is quite ugly, but still effective. We shouldn't be using these principles in the first place, they have terrible types that make them very unwieldy.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
This looks pretty bad. Could we fix the proofs to avoid needing the principles instead?

**Comment by ppedrot** [comment]
I don't want to rewrite proofs for morally deprecated code. In theory the FMap module should have been replaced by a MMap than never came.

**Comment by proux01** [comment]
@coqbot merge now

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
@coqbot merge now

**Pull request merged**
