### PR TITLE
Fix binder_tactic after #18220 (see #18368)

### LINKED ISSUE #18368: Levels of tactic notations no longer properly respected
Since #18220 it seems that tactic levels are no longer properly respected, as in the following case.
CC @herbelin. Is this intended? If so, what are the new semantics of these levels?

```coq
Tactic Notation (at level 4) "test" := idtac "A".
Tactic Notation (at level 5) "test" := idtac "B".

Goal True.
test. (* Prints A, used to print B *)
```

#### Coq Version

Since #18220

### PR DESCRIPTION
**Pull request by herbelin**
Fixes / closes #18368

The move of binder_tactic at level 1 of ltac_expr in #18220 was incomplete. This PR tries to complete it (removing all references to `binder_tactic`).

- [x] Added / updated **test-suite**.

### CODE REVIEW

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@herbelin the metacoq failure is likely real

**Comment by herbelin** [comment]
> @herbelin the metacoq failure is likely real

Metacoq apparently due to the merge of [#18374](https://github.com/coq/coq/pull/18374#issuecomment-1847181088).

**Review by proux01 — APPROVED** [review]

**Comment by proux01** [comment]
Indeed, so CI is "green", let's merge.

@coqbot merge now

**Pull request merged**
