### PR TITLE
Reduce the use of Logic.refiner

### PR DESCRIPTION
**Pull request by ppedrot**
We remove some calls to Logic.refiner in Equality and funind where we statically know that the argument is meta-free, and thus equivalent to the exact tactic.

### CODE REVIEW

**Review by Matafou — APPROVED** [review]
Seems reasonable to me. Are calls to the refiner deprecated?

**Comment by ppedrot** [comment]
@Matafou yes, although it's still critically used by core tactics like apply and destruct. That's the whole point about the unifall branch, btw.

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
merging soon

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
