### PR TITLE
Bump version number to 8.10+alpha.

### PR DESCRIPTION
**Pull request by silene**

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Please merge yourself when you want this to land in master.

**Comment by Zimmi48** [comment]
>Please merge yourself

This goes against the only rule written in all caps in the merging doc. We can debate if this rule is right (see also the impromptu discussion at https://github.com/coq/coq/pull/8135#issuecomment-416668326) but until this rule is changed, I think we should keep self-merging by the RM restricted to stable branches only.

**Comment by ejgallego** [comment]
> This goes against the only rule written in all caps in the merging doc. We can debate if this rule is right (see also the impromptu discussion at #8135 (comment)) but until this rule is changed, I think we should keep self-merging by the RM restricted to stable branches only.

Well I felt that this was a clear special case due to wanting to put this as the first commit of the `master` branch; as 8.9 is created, merging anyways.

**Comment by Zimmi48** [comment]
Indeed, that won't be the first commit on master. v8.9 is already well behind.

I don't understand what's going on with Iris but it's failing very consistently and not anywhere else it seems (cc @RalfJung).

**Comment by RalfJung** [comment]
Ah. Coq 8.9 is whitelisted in Iris's test suite (which also checks the output printed by Coq, to make sure we do not regress our notation or error messages), it is allowed to have broken output because of https://github.com/coq/coq/issues/6764. I guess I can mark Coq 8.10 as equally broken?

Though it seems that is not the only change, the diff seems to indicate that Ltac backtraces also got worse in some places?

**Comment by Zimmi48** [comment]
OK, so because #6764 is making Iris unusable, we missed other regressions? That's pretty bad, maybe it's time to fix this bug by reverting the feature *in master as well*. Unless the patch is ready of course.

**Comment by RalfJung** [comment]
Well, we missed other changes. I consider them regressions as far as Iris is concerned, but they may have been deliberate. Once #6764 is fixed I can investigate, but currently there is just too much noise in the diff.

**Comment by RalfJung** [comment]
I marked Coq 8.10 as broken in Iris, and bumped Iris in lambdaRust. In <30min, the new lambdaRust should appear on opam, fixing CI here.

**Comment by ybertot** [comment]
coq-dpdgraph should be fixed now.  The problem was not about bumping versions, but about the fact that version 8.10 was recognized as a variant of version 8.1

**Comment by ejgallego** [comment]
> I will fix Fiat tomorrow

Great @JasonGross , please hit the retry button on the CI when you do this.

**Comment by JasonGross** [comment]
Fiat succeeded

**Comment by ejgallego** [comment]
Great, will merge soon unless people oppose.

**Pull request merged**
