### PR TITLE
Simplify Lib section handling

### PR DESCRIPTION
**Pull request by ppedrot**
This PR is a series of small cleanups with the purpose of easing the kernel integration of the section mechanism.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
LGTM

**Review by herbelin — APPROVED** [review]
Looks good.

It took me a little time to realize that `Context` was not related to the command `Context` but that it was a recording of the polymorphic universe variables implicitly declared in the section. Maybe could it be renamed into `UniverseContext`, or `PolymorphicUniverses`, or whatever.

**Comment by ppedrot** [comment]
@herbelin this code is bound to disappear soon. I am reimplementing it kernel-side, the current PR is just here to make some invariants more explicit so as to trust more easily the reimplementation.

**Comment by herbelin** [comment]
@ppedrot: Fine then.

**Comment by ppedrot** [comment]
@herbelin do you want to assign?

**Comment by ejgallego** [comment]
I guess that given @herbelin 's approval we can just merge [it will avoid further conflicts with some ongoing trees]

**Pull request merged**
