### PR TITLE
Towards a more uniform API for declare.ml (part declaring mutual statements)

### PR DESCRIPTION
**Pull request by herbelin**
The purpose of this PR is to present some uniformity in the API of `declare.ml` so that it is clearer to compare the different functions. It should not change the semantics.

Depends on ~~#18742 and~~ #18743 (merged).

It has an impact on the exact API though with the following API changes:
- function renamings
  - `declare_mutually_recursive` -> `declare_mutual_definition` (+ label `rec_declaration` -> `bodies`), consistently with `declare_definition`
  - `start_with_initialization` -> `start_definition`
  - `start_mutual_with_initialization` -> `start_mutual_definition` (+ label `init_term` -> `bodies`)
- other labels renaming
  - in `add_definition`: `term` -> `body`, and `opaque` made mandatory
  - in `add_mutual_definitions`: argument (cinfo,bodies,obls) -> labels `cinfo` and `bodies` + obls kept as unnamed argument

- [ ] TODO, pending question: mutual_definition or mutual_definitions?

Overlays (due to opaque made mandatory)
- MetaCoq/metacoq#1083
- mattam82/Coq-Equations#599

### CODE REVIEW

**Comment by herbelin** [comment]
@coqbot run full ci

**Review by ejgallego — APPROVED** [review]
LGTM thanks

**Comment by herbelin** [comment]
@ejgallego: any preference between `mutual_definition` and `mutual_definitions`? (Google says 602 for `"mutual definition" coq` and 509 for `"mutual definitions" coq` though the context of course matters.)

In the absence of preferences I would go for singular, but I'm ready for plural too.

**Comment by ejgallego** [comment]
> The most conservative would be mutual definitions since it would preserve the old name `add_mutual_definitions`, so I'm leaning for it.

Sounds good @herbelin , I have no strong opinion, if we find a better name we can change it later of course.

**Comment by herbelin** [comment]
Adopting the plural form then.

**Review by ppedrot — APPROVED** [review]

**Pull request merged**
