### PR TITLE
Allow existing instances of existing classes of primitive projections, fix #14652

### LINKED ISSUE #14652: Primitive projection declared as existing class cannot have existing instances
In #12975 it was noticed that there was an arbitrary restriction on primitive projections becoming existing classes. In #9711 this was fixed. However now there is a strange bug where primitive projections which are existing classes cannot have existing instances.

cc @mattam82 

Here is an example:
```coq
Record myRecord := {
  my_class : Type ;
}.

Fail Instance my_instance : forall x, my_class x.

Existing Class my_class.

Instance my_instance : forall x, my_class x. Abort.

Definition my_existing_instance : forall x, my_class x. Admitted.

#[export]
Existing Instance my_existing_instance.

Set Primitive Projections.

Record myOtherRecord := {
  my_other_class : Type ;
}.

Fail Instance my_other_instance : forall x, my_other_class x.

Existing Class my_other_class.

Instance my_other_instance : forall x, my_other_class x. Abort.

Definition my_other_existing_instance : forall x, my_other_class x. Admitted.

(* ??? *)
(* Constant does not build instances of a declared type class. *)
#[export]
Existing Instance my_other_existing_instance.
```

8.15+alpha

### PR DESCRIPTION
**Pull request by Alizter**
It was pointed out in #14652 by @herbelin that the is a bug with de Bruijn indices in `vernac/classes.v`. This PR implements the suggested change and adds #14652 to the test-suite. This allows for primitive projections to be declared as existing classes, and terms of those classes to be declared as existing instances which wasn't possible before.

Running the test-suite gives only one error:
```
    complexity/pretyping.v...Error! (should run faster (168 >= 150))
```
So it seems performance took a hit for some reason. Not sure why. This was on my machine however, so we will see what the test-suite on the CI says. 

Fixes / closes #14652

- [x] Added / updated **test-suite**.
- [x] Added **changelog**.

### CODE REVIEW

**Review by herbelin — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by Alizter** [comment]
Should I add a changelog entry?

**Comment by herbelin** [comment]
> Should I add a changelog entry?

I think that's the rule, yes, for bug fixes. You can then mention our two names.

**Comment by Alizter** [comment]
@herbelin The changelog has been updated.

**Comment by herbelin** [comment]
Relying on @ppedrot's green, @coqbot: merge now.

**Comment by herbelin** [comment]
@coqbot: merge now

**Pull request merged**
