### PR TITLE
Fix ci-fiat-crypto to have a proper lite target

### PR DESCRIPTION
**Pull request by JasonGross**
The lite target depends on having the submodule cloned to generate the
list of files to not build.

(Hopefully; I'm not 100% certain this will fix things.)

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
I am OK with this.

**Comment by maximedenes** [comment]
@JasonGross It seems the build failed on fiat-crypto here: https://travis-ci.org/JasonGross/coq/builds/242922366

**Comment by JasonGross** [comment]
I'm confused how this could have changed things.  Anyway, the failure mode is
```
make[2]: *** write jobserver: Bad file descriptor.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** write jobserver: Bad file descriptor.  Stop.
make[1]: *** [coqprime] Error 2
make[1]: INTERNAL: Exiting with 1 jobserver tokens available; should be 2!
make[1]: Leaving directory `/home/travis/build/JasonGross/coq/_build_ci/fiat-c
```
This, I think, is a thing that happens when you call a shell script from `make -j`, and that shell script calls `make` without `-j` (or it calls `make` with `-j` and a submake is invoked without `-j`).  I don't know how to fix it; we can't disable parallel builds, because then fiat-crypto will be too slow.  We're not willing to force parallel builds in our submake.  Who knows how to wrangle `make` better than I do?  @ejgallego ?

**Comment by JasonGross** [comment]
https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html#Options_002fRecursion suggests that `-j` might not be needed in the ci targets?

**Comment by JasonGross** [comment]
Should hopefully be fixed, now.

**Comment by Zimmi48** [comment]
I don't think we are testing the right thing here given the current fiat-crypto overlay. If you retarget this to 8.6 it should work better (and anyways this fix *has to* be merged in v8.6).

**Comment by JasonGross** [comment]
Is v8.6 going to be merged into trunk more, or is the model now to cherry-pick from trunk to v8.6?

Alternatively, I can put this on top of #782...

**Comment by Zimmi48** [comment]
Yes, at least one final time.

**Pull request merged**
