### PR TITLE
Fix Timeout on failing command leaking timeouts

### LINKED ISSUE #14567: Strange timeout behaviour
~~~coq
Fail Timeout 1 Check Prop : Prop.
Check ltac:(repeat pose 0). (* or any other command which takes a while *)
~~~
After about 1s the `repeat` will timeout.

This is a real problem when the command would otherwise terminate ;)

This causes random timeouts with proof general and -noinit, because PG runs `Timeout 1 Print Grammar tactic.` (and coqtop implicitly catches the error from `tactic` not being defined)

NB: AFAICT no bug with `Timeout 1 Fail`

### PR DESCRIPTION
**Pull request by SkySkimmer**
No idea how to add a test for this.

Fix #14567

### CODE REVIEW

**Comment by ppedrot** [comment]
Can't you add a misc test?

**Comment by SkySkimmer** [comment]
What would the test do exactly?

**Comment by ejgallego** [comment]
cc @LasseBlaauwbroek

**Comment by LasseBlaauwbroek** [comment]
LGTM! Getting every possible control flow path to work for `timeout` seems to be a rather uphill battle...

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Let's merge without a fix then.

**Pull request merged**
