### PR TITLE
Sphinx/chapter 9

### PR DESCRIPTION
**Pull request by Zimmi48**
I had some time in the plane so I started the migration. I won't be available to finish it however and even the part I ported should be checked, because I didn't have access to an online reference on the plane and there are many conventions I could only guess.

### CODE REVIEW

**Comment by maximedenes** [comment]
Argh!! I guess you didn't see my messages on gitter, I started working on it too.

**Comment by maximedenes** [comment]
Did you do a fresh pandoc translation to start with a recent version?

**Comment by Zimmi48** [comment]
Indeed I didn't and I started from the freshest version possible but I don't know precisely what you mean by pandoc translation. All the people I asked to told me there was no way to partially mechanize the translation. Anyways feel free to simplify close this PR. I won't feel bad if you do. And by translation is probably less good than yours because I don't understand Sphinx well.

**Comment by maximedenes** [comment]
> All the people I asked to told me there was no way to partially mechanize the translation

Oh, I doubt it, since the "raw" versions in the `sphinx-doc` branch were obtained automatically, AFAIK (using pandoc I believe).

But anyway, thanks for getting the work started!

**Comment by Zimmi48** [comment]
There were raw versions provided? Interesting :p
Definitely not something I could have learned from my plane XD

**Comment by maximedenes** [comment]
Superseded by #7250.

**Pull request closed without merging**
