### PR TITLE
Update update-compat.py

### PR DESCRIPTION
**Pull request by JasonGross**
**Kind:** bug fix / enhacsement / infrastructure.

c.f. #11032

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]
The automatic update of the notation deprecation test file might not be much used in the future, because compat notations are a deprecated feature that could be removed anytime, while deprecated attributes do not require to be updated because they are not linked to the compat infrastructure.

**Comment by Zimmi48** [comment]
It seems that there is an issue with the test-suite. I haven't looked into it.

**Comment by JasonGross** [comment]
I've removed the auto-update of notation deprecations, since there's another PR that removes them

**Review by Zimmi48 — APPROVED** [review]

**Comment by Zimmi48** [comment]
> I've removed the auto-update of notation deprecations, since there's another PR that removes them

Sorry about the extra work this represented.

**Comment by Zimmi48** [comment]
It seems there is still an issue with the test-suite.

**Comment by JasonGross** [comment]
Right, python3 is stricter than python2 about file reading, so I'm getting "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1025: ordinal not in range(128)" on reading from files with Unicode.  I'll plan to look into a fix later today.

**Comment by JasonGross** [comment]
Should be fixed now.  Note that this conflicts with the other change to `update-compat.py` in #11113; this change modifies some code in functions that the other change removes/changes.  I can rebase whichever one is to be merged second.

**Comment by ejgallego** [comment]
Somehow this made https://github.com/coq/coq/pull/11158 fail unless I tweaked the python file to include parenthesis around `print`. I wonder what's going on.

**Pull request merged**
