### PR TITLE
Ensuring all .v files end with a newline to make "sed -i" work better on them

### PR DESCRIPTION
**Pull request by herbelin**
This is a purely technical PR to ease transitions such as in PR #884.

By the way, @mattam82, @maximedenes, @Zimmi48, there are so many things to do in Coq. How could we organize better to satisfy all needs at best?

### CODE REVIEW

**Comment by Zimmi48** [comment]
On the PR topic: I'm for this change if we can ensure that this criterion (no file with no newline at the end) can be enforced in the future. I'd anyone aware of a way of ensuring this / a specialized testing service that we could use?

On the organization topic: sorry, I said earlier that I would be answering this on coqdev but delayed my response a lot.
My point of view currently if that the good way to organize ourselves would be to really take advantage of our bug tracker. That is, to report all the tasks that should be done, easy or hard, on the bug tracker, and flag them appropriately. That we haven't done this so far led me to consider that our current bug tracker isn't the right tool. That TODO lists, Wish lists, CEPs... were used also seems to indicate that our bug tracker isn't satisfying. That's why I would be currently very much in favor of switching to GitHub issues. Using `needs: help` on issues we don't feel like tackling ourselves, linking this flag from the contributing guide, and advertising that we are always looking for new contributors on Coq-Club could be the next steps to ensure that a larger force is available to tackle the challenge. 
Finally, GitHub issues would also allow to use checklists for issues with multiple instances such as those which were listed by @matejkosik in #866.

**Comment by herbelin** [comment]
@Zimmi48, on the PR: I'm not good at commit hooks, but stackoverflow seems to propose `if [ -z "$(tail -c 1 "$1")" ]` to test a ending newline. This could then go in a hook, if someone knows how to do that.

**Comment by SkySkimmer** [comment]
Additionally we could `(require-final-newline t)` in `.dir-locals.el`.

**Comment by maximedenes** [comment]
I'm going to merge this PR. We can see the hooks later.

**Comment by Zimmi48** [comment]
Indeed, but let's not forget about it. BTW how about using http://editorconfig.org/? NixOS/nixpkgs uses this (that's how I've discovered about it.) The language is precise enough to impose different formatting styles on different types of files and has the notable advantage to support non-Emacs users. The slight drawback is that it requires installing a plugin / package.

**Pull request merged**
