### PR TITLE
More complete handling of universe names

### PR DESCRIPTION
**Pull request by SkySkimmer**
After this AFAICT the only global universes still using raw ints are the ones from module types (because the name object doesn't escape)

- fix collision with generated names
- generate names for more global universes (from section variable and from private constants)
- universe names are now Keep instead of Substitute, this better matches how they work (also avoids collision when including modules which have universes)
- new libobject classification "Escape" for universe names

Depends:
- https://github.com/coq/coq/pull/19754

Overlays:
- https://github.com/JasonGross/coq-tools/pull/239

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
changed:

- universe names are now Keep instead of Substitute, this better matches how they work (also avoids collision when including modules which have universes)
- Keep survives functors and module types (this may break some stuff as it's not clear which objects are Keep)

**Comment by SkySkimmer** [comment]
After this and https://github.com/coq/coq/pull/19723 the only non-named universes in stdlib are from ssrunder which looks like
~~~coq
Module Type T.
Parameter foo : forall A:Type, ...
End T.

Module M : T.
Definition foo (A:Type) := ...
End M.
(* opaque module ascription eats name of M.foo.u0
NB: M.foo.u0 = T.foo.u0 since we have no contravariance on forall domain, otherwise it would be T.foo.u0 <= M.foo.u0 *)
~~~

**Comment by SkySkimmer** [comment]
@JasonGross not sure how to fix the coq-tools failure (example 27). It seems to expect
~~~coq
Module Export Foo_DOT_A_WRAPPED.
Module Export A.
Definition foo : Type.
Admitted.

End A.
Module Export Foo.
Module A.
Include Foo_DOT_A_WRAPPED.A.
End A.

Check Foo.A.foo : Set.
~~~
which on master produces 
~~~
Error:
The term "A.foo" has type "Type" while it is expected to have type "Set"
(universe inconsistency: Cannot enforce A.foo.u0 <= Set).
~~~
The universe name Foo_DOT_A_WRAPPED.A.foo.u0 gets duplicated by the Include such that the underlying universe thinks its name is Foo_DOT_A_WRAPPED.Foo.A.foo.u0 and the export for Foo_DOT_A_WRAPPED.A has no effect.

In this PR the universe name is not duplicated by Include so the underlying universe still considers its name to be Foo_DOT_A_WRAPPED.A.foo.u0 and the export for Foo_DOT_A_WRAPPED.A makes the shortest available name `foo.u0`.
We get error message
~~~
Error:
The term "A.foo" has type "Type" while it is expected to have type "Set"
(universe inconsistency: Cannot enforce foo.u0 <= Set).
~~~
and further minimization to 
~~~coq
Module Export Foo.
Module A.
Definition foo : Type.
Admitted.
End A.
Check Foo.A.foo : Set.
~~~

**Comment by JasonGross** [comment]
Thank you for diagnosing this.  The most straightforward thing to do is to just consider both of these to be valid minimizations.  I think if you modify
https://github.com/JasonGross/coq-tools/blob/b0ab353f51d4d6ffbee97b2ad6e04fd90846369c/examples/run-example-027.sh#L90-L101 with
```diff
 Module Export Foo_DOT_A_WRAPPED\.
 Module Export A\.
 Definition foo : Type\.
 Admitted\.
-
+\(
 End A\.
 Module Export Foo\.
 Module A\.
 Include Foo_DOT_A_WRAPPED\.A\.
-End A\.
+\)\?End A\.
-
+\?
 Check Foo\.A\.foo : Set\.
```
(or some similar regex fix), it should work.

**Comment by SkySkimmer** [comment]
@JasonGross  That regex change doesn't work and I don't know how to make one that works.

**Comment by JasonGross** [comment]
Oh, I guess I forgot to make the first line optional, try
```diff
-Module Export Foo_DOT_A_WRAPPED\.
+\(Module Export Foo_DOT_A_WRAPPED\.
-Module Export A\.
+\)\?Module Export A\.
 Definition foo : Type\.
 Admitted\.
-
+\(
 End A\.
 Module Export Foo\.
 Module A\.
 Include Foo_DOT_A_WRAPPED\.A\.
-End A\.
+\)\?End A\.
-
+\?
 Check Foo\.A\.foo : Set\.
```
If this doesn't work, you can make two regexes and just have the if statement check if either one matches.

**Comment by SkySkimmer** [comment]
Please do it yourself, I'm not familiar enough with this regex format to do it without wasting a ton of time.

**Comment by JasonGross** [comment]
Hopefully https://github.com/JasonGross/coq-tools/pull/237 will fix the issue.

>  I'm not familiar enough with this regex format

The format is just that of `grep` (except that both the search pattern and the text being searched are pre-processed with `| grep -v '^$' | tr '\n' '\1'` to remove empty lines and substitute newlines so plain `grep` can handle it)

**Comment by JasonGross** [comment]
Trying again with https://github.com/JasonGross/coq-tools/pull/239, this time I've tested locally with grep

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
top file size changes
~~~
coq-rewriter/./src/Rewriter/Demo.vo 323862 340741 16879 5%
coq-fiat-parsers/./src/ADTRefinement/Refinements/SimplifyRep.vo 955 1001 46 4%
coq-fiat-core/./src/ADTRefinement/Refinements/SimplifyRep.vo 955 1001 46 4%
/./ssr/ssrunder.vo 4524 4700 176 3%
coq-rewriter/./src/Rewriter/Rewriter/Examples.vo 2034792 2098773 63981 3%
coq-rewriter/./src/Rewriter/Rewriter/Examples/PrefixSums.vo 614434 634396 19962 3%
coq-rewriter-perf-SuperFast/./src/Rewriter/Rewriter/Examples/PerfTesting/UnderLetsPlus0.vo 747695 7701
58 22463 3%
coq-fiat-core/./src/ADTRefinement/BuildADTRefinements/SimplifyRep.vo 1503 1549 46 3%
coq-rewriter/./src/Rewriter/Rewriter/Examples/PerfTesting/UnderLetsPlus0.vo 748147 769767 21620 2%
coq-rewriter/./src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.vo 1587575 1625031 37456
 2%
coq-rewriter-perf-SuperFast/./src/Rewriter/Rewriter/Examples/PerfTesting/SieveOfEratosthenes.vo 158757
3 1626902 39329 2%
coq-neural-net-interp-computed-lite/./theories/Util/Relations/Relation_Definitions/Hetero.vo 2481 2545
 64 2%
coq-fiat-parsers/./src/Parsers/ContextFreeGrammar/Fix/FromAbstractInterpretationDefinitionsRelations.v
o 2529 2580 51 2%
coq-fiat-parsers/./src/ADTRefinement/Refinements/DelegateMethods.vo 2355 2404 49 2%
coq-fiat-crypto-with-bedrock/./src/Util/Tower.vo 6549 6695 146 2%
coq-fiat-core/./src/ADTRefinement/Refinements/DelegateMethods.vo 2355 2404 49 2%
~~~
after that it's <=1%

**Comment by ppedrot** [comment]
If everybody is happy about the new classification introduced in Libobject in will merge soon.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
