### PR TITLE
Remove optional header in UserError

### PR DESCRIPTION
**Pull request by SkySkimmer**
It was only used in coqchk -debug ie completely useless.

Note the 2 places where we did `try ... with UserError (Some "foo", _) -> ...` 
- tactics.ml for "move_hyp", the user_err was converted to a custom exception
- funind recdef.ml for "Refined.thensn_tac3" (can't find any user_err
  with this header) and "Refiner.tclFAIL_s" (raised by old engine
  tclTHENS, so this catch has been dead code since the port to the
  Tacticals.New).
  Conclusion: catch removed.

Overlays:
- https://github.com/maximedenes/vscoq/pull/1
- https://github.com/Mtac2/Mtac2/pull/346
- https://github.com/mattam82/Coq-Equations/pull/432
- https://github.com/lukaszcz/coqhammer/pull/111

Backwards compatible (uses only user_err, not UserError):
- https://github.com/coq-community/paramcoq/pull/83
- https://github.com/MetaCoq/metacoq/pull/591
- https://github.com/LPCIC/coq-elpi/pull/298
- https://github.com/coq/bignums/pull/61

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by SkySkimmer** [comment]
>I took the opportunity to tweak some of the messages.

Please make a separate PR instead.

**Review by ppedrot — APPROVED** [review]
At last!

**Review by ejgallego — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer can you remove the backwards compatible overlays from the PR? They've been all merged upstream now.

**Comment by Alizter** [comment]
@SkySkimmer Something went wrong there

**Pull request merged**
