### PR TITLE
Workaround for CoqIDE preferences crashing on MacOS (#16136).

### LINKED ISSUE #16136: IDE crashed when trying to do edit->preferences
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               coqide.exe [7799]
Path:                  /Applications/Coq-Platform~8.15~2022.04.app/Contents/Resources/bin/coqide.exe
Identifier:            coqide.exe
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               503

Date/Time:             2022-05-22 17:44:01.5214 -0400
OS Version:            macOS 12.3.1 (21E258)
Report Version:        12
Bridge OS Version:     6.5 (19P5071)
Anonymous UUID:        D3DFB2CA-165E-DE9E-8BC6-33029E6CAF79

Sleep/Wake UUID:       01F49602-791E-4A05-A683-64D2A6D85425

Time Awake Since Boot: 7200 seconds
Time Since Wake:       6040 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [7799]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 4511461368
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10ce77000-10d1e7000    [ 3520K] r-x/r-x SM=COW  ...in/coqide.exe
```
I was on BigSur with the january version, and preference just crashes the ide. I updated to Monterey, and is using `coqIDE 8.15`, and this issue seems to still persist.

### PR DESCRIPTION
**Pull request by ppedrot**
We implement a poor man's font selection dialog, but this should be enough.

Arguably fixes #16136.

cc @herbelin @MSoegtropIMC

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
I can't say much about it from looking at the code, but I could take it as opam level patch in the 2022.09 beta.

**Comment by ppedrot** [comment]
I wouldn't mind some testing on MacOS to check it works as intended. It works for me on Linux by disabling the Darwin check, but YMMV.

**Comment by MSoegtropIMC** [comment]
I plan to take this into the Coq Platform beta as opam level patch - I will post test results here.

**Comment by MSoegtropIMC** [comment]
@ppedrot : technically it works. The only issue is that since the "poor mans font dialog" has only 2 lines and since it is the first tab, the settings dialog is very small when it comes up. Would it be possible to include a spacer of say 3 lines height?

**Comment by ppedrot** [comment]
@MSoegtropIMC I've added some handpicked size request, now the widget is at least 300×200 pixels. Does it look OK to you?

**Comment by MSoegtropIMC** [comment]
@ppedrot : thanks, looks good to me now.

**Review by MSoegtropIMC — APPROVED** [review]

**Comment by ppedrot** [comment]
Any assignee? This is somewhat urgent. @herbelin maybe?

**Comment by Zimmi48** [comment]
This could also be @MSoegtropIMC, since he reviewed it already.

**Comment by MSoegtropIMC** [comment]
Sorry I got new PCs and didn't set up the signing yet for a merge with the good old script and I am not sure I understand how coqbot works in case there are CI failures. I do this rarely since Coq Platform ...

Is there a documentation of coqbot btw? I usually get usage notes from the release notes.

**Comment by Zimmi48** [comment]
> Sorry I got new PCs and didn't set up the signing yet for a merge with the good old script and I am not sure I understand how coqbot works in case there are CI failures. I do this rarely since Coq Platform ...

No need to use the good old script nowadays. coqbot does not check CI failures, it is the role of the reviewers to do it. It checks the rest of the criteria and you cannot bypass them.

>Is there a documentation of coqbot btw? I usually get usage notes from the release notes.

Documentation is limited unfortunately:
- https://github.com/coq/bot/#a-multi-function-bot-written-in-ocaml (does not talk about the merge feature)
- https://github.com/coq/coq/blob/master/CONTRIBUTING.md#merging-pull-requests

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : thanks - the lines in the contributing guides where the ones I was looking for (in the wrong place). I will merge then.

@coqbot: merge now

**Comment by MSoegtropIMC** [comment]
@coqbot: merge now

**Pull request merged**
