### PR TITLE
[ci] [docker] Upgrade odoc to 1.4.0

### PR DESCRIPTION
**Pull request by ejgallego**
This is routine as for API doc writers to be able to access the newer
features.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Should we do any other updates while we're at it? eg dune

**Comment by ejgallego** [comment]
> Should we do any other updates while we're at it? eg dune

hehehe I was indeed going to do it but I thought you would tell me "do in a different PR" :)

Given that we still set `(lang dune 1.6)` let's keep using 1.6 for a bit more; we shall increase the version number to 1.9 I think next time, which will include quite a few nice features for Coq.

**Comment by SkySkimmer** [comment]
>hehehe I was indeed going to do it but I thought you would tell me "do in a different PR" :)

That's pretty easy to avoid, just name the PR "[docker] update opam packages" or some such less specific thing ;)

**Review by SkySkimmer — APPROVED** [review]

**Comment by ejgallego** [comment]
Seems to work fine, https://coq.gitlab.io/-/coq/-/jobs/175353544/artifacts/_build/default/_doc/_html/index.html

**Pull request merged**
