### PR TITLE
Add test for possible bug encountered in #14480

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Obvious

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by SkySkimmer** [comment]
@herbelin ping

**Comment by herbelin** [comment]
@coqbot: merge now

**Comment by SkySkimmer** [comment]
@herbelin ping again

**Comment by herbelin** [comment]
Ah...

@coqbot: merge now

**Pull request merged**
