### PR TITLE
 Remove all `nf_evar` from `cases.ml` and `pretyping.ml` if they affected the elaborated term

### PR DESCRIPTION
**Pull request by yannl35133**
Test for removing instances of `nf_evar` during pretyping.

Needs PR #18847

### CODE REVIEW

**Comment by ppedrot** [comment]
This was already tried and is catastrophic for performance IIRC.

**Comment by yannl35133** [comment]
I would be fine to set this behaviour behind a flag (`flags.expand_evars` seems to be intended for that)

**Comment by SkySkimmer** [comment]
Needing to avoid nf_evar smells of legacy_bad_pattern_of_constr

**Comment by ppedrot** [comment]
@SkySkimmer This is the other way around, we *want* to normalize evars for efficiency purposes, rather than not normalizing it to please the function whose name shall not be uttered.

**Comment by SkySkimmer** [comment]
This PR is removing nf_evar calls though

**Comment by ejgallego** [comment]
Actually @afdw was asking me today about why we ever need to perform `nf_evar` instead of being fully under demand; ccing her so she can follow the discussion.

**Comment by JasonGross** [comment]
> Actually @afdw was asking me today about why we ever need to perform `nf_evar` instead of being fully under demand; ccing her so she can follow the discussion.

Isn't this because `EConstr` doesn't actually cache evar expansion (so as to be compatible with backtracking?), so we'd end up evar-expanding repeatedly?

Would it make sense to have evar maps store ... a map of hash-cons'd constrs to partially evaluated constrs or something?  Or more generally is there a good way to mix lazy and backtracking?

**Pull request closed without merging**
