### PR TITLE
Use stages in gitlab-ci.yml

### PR DESCRIPTION
**Pull request by SkySkimmer**
This makes the default pipeline view print all jobs (there is a 100 job/stage limit).

### CODE REVIEW

**Comment by ppedrot** [comment]
This should be autogenerated with a script, otherwise we'll lose track of the dependency depth and introduce inconsistencies?

**Comment by SkySkimmer** [comment]
Inconsistencies will be caught by CI

**Review by Zimmi48 — APPROVED** [review]
Inconsistencies will be caught immediately when the pipeline starts, right? No need to even wait for the CI to complete. However, we will still need to trigger a full CI run.

**Comment by SkySkimmer** [comment]
If something is put in a later stage than it must (eg if a dependency is removed) it won't be caught, but I'm not sure if that has happened in the history of Coq's CI.
Other issues will make the pipeline refuse to start.

**Comment by Zimmi48** [comment]
It wouldn't be a big deal anyway.

Let's try @coqbot run full CI.

Is this OK if I merge this without waiting for the pipeline to run as long as it did start?

**Comment by SkySkimmer** [comment]
merge on
Looks like the biggest stage is build-1 at 59 jobs

**Pull request merged**
