### PR TITLE
Generate parsing statistics

### PR DESCRIPTION
**Pull request by jfehrle**
This PR provides a simple mechanism for developers to gather statistics across multiple runs of `coqc`, whether in a local build or in CI.  The initial version counts how many times each parser production is invoked.  The code can be adapted to gather other statistics.

See `statistics.md` for more detail.

I did this to get an idea of the most commonly used tactics and commands to help decide what should be documented first.  The parsing statistics may help identify obsolete or unused constructs that might be removed in future releases.  Or, with a bit more packaging, it could help users identify how often they use deprecated constructs.

Full sample output across most of the CI jobs is here: https://github.com/coq/coq/wiki/Use-counts-for-parser-productions.

Some background discussion here: https://github.com/coq/coq/issues/10675

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
I am not sure I am convinced by this approach; we have the ability now to dump the exact AST of Coq developements [tested at a relatively large scale]

Thus I wonder why such a a tool shouldn't simply be a post-processor of the dumped AST.

**Comment by gares** [comment]
It would be nice to see an example of the dump, especially of tactic code, and also instructions on how to produce it (I don't recall a -dump option n to Coqc).

**Comment by ejgallego** [comment]
> It would be nice to see an example of the dump, especially of tactic code, and also instructions on how to produce it (I don't recall a -dump option n to Coqc).

`sercomp --mode=sexp` will do, example for
```
Lemma foo : True.
Proof. now apply I. Qed.
```
you get
```
(VernacExpr ()
 (VernacStartTheoremProof Lemma
  ((((Id foo) ()) (() (CRef (Ser_Qualid (DirPath ()) (Id True)) ()))))))
(VernacExpr () (VernacProof () ()))
(VernacExpr ()
 (VernacExtend (VernacSolve 0)
  ((GenArg raw (OptArg (ExtraArg ltac_selector)) ())
   (GenArg raw (OptArg (ExtraArg ltac_info)) ())
   (GenArg raw (ExtraArg tactic)
    (TacAlias
     ((((fname (InFile k.v)) (line_nb 2) (bol_pos 18) 
        (line_nb_last 2) (bol_pos_last 18) (bp 25) 
        (ep 36)))
      ((Kername (MPfile (DirPath ((Id Tactics) (Id Init) (Id Coq))))
        (DirPath ()) (Id now_#_62200C10))
       ((Tacexp
         (TacAtom
          ((((fname (InFile k.v)) (line_nb 2) (bol_pos 18) 
             (line_nb_last 2) (bol_pos_last 18) (bp 29) 
             (ep 36)))
           (TacApply true false
            ((() ((CRef (Ser_Qualid (DirPath ()) (Id I)) ()) NoBindings)))
            ())))))))))
   (GenArg raw (ExtraArg ltac_use_default) false))))
(VernacExpr () (VernacEndProof (Proved Opaque ())))
```
which is fairly easy to process to get "the most commonly used tactics and commands to help decide what should be documented first."

**Comment by ejgallego** [comment]
Actually note that `sercomp` does already provide a `stats` output mode, intended to replace coqwc, but of course could be extended to provide more info.

**Comment by jfehrle** [comment]
> I am not sure I am convinced by this approach; we have the ability now to dump the exact AST of Coq developments

> Thus I wonder why such a tool shouldn't simply be a post-processor of the dumped AST.

The AST is interesting but isn't a great fit for what I want to do.  I'm not doing a GUI, nor is this PR doing really doing code analysis.

It seems like there would be a lot of post-processing to extract the tactics and productions from the AST.  Whether the AST is available as a string or as an OCaml datatype, I'd have to parse/step through the tree with different logic for each type of node.  For example, in your example, how do I know that `(Id now_#_62200C10)` represents a `now` tactic?  AFAIK there's not a lot of documentation about what all the `Vernac*` mean, which would require reverse engineering all of them to learn what they do from the code.  And likely more brittle to future changes to Coq.

An AST that includes only production identifiers and tokens would be more appropriate, but with the approach I've taken there is no need to step through any tree.  The interface between the parser and the stats code is tiny.

For the Coq documentation, I'm working with the grammar.  It's very helpful to see that some of these forms are not used at all:

```
      0  simple_tactic:  "autorewrite" "*" "with" LIST1 preident clause
      0  simple_tactic:  "autorewrite" "*" "with" LIST1 preident clause "using" tactic
   1023  simple_tactic:  "autorewrite" "with" LIST1 preident clause
     31  simple_tactic:  "autorewrite" "with" LIST1 preident clause "using" tactic
```

How would I tell that some tactic/production has 0 uses from the AST?  That's very interesting information to know.

This PR makes it very easy to gather and combine statistics across a large body of .v files without requiring changes to their build files--which would seem necessary to invoke with `sercomp --mode=sexp`.  Furthermore, the statistics-gathering framework makes it pretty painless to collect statistics.  There are many other stats that would be interesting to examine, though not all of them will be worth adding to master.

Finally, we should encourage a certain amount of experimentation with alternative approaches.  The SERAPI doc says `The protocol is experimental and may change often.`  It seems premature to try to force others to use it.

> [tested at a relatively large scale]

I've run this against most of the CI jobs, representing over 3.4 million simple tactics.

**Comment by Zimmi48** [comment]
I don't know whether this PR will end up getting merged or not but:
1. it's not particularly urgent;
2. it can be useful even if it doesn't get merged

However, for it to be useful, we will have to determine what use case we want to give to it. Identifying parsing constructs which are never used is interesting. However, the conclusion should not always be deprecation. Sometimes, it is normal not to find any use in finished proof scripts, but it doesn't mean it is not used in wip proof scripts. Sometimes, if a feature is unused, it means that it is not sufficiently advertised (e.g. because it is undocumented). E.g., that's the case of `Export Set`. (And I'm immensely surprised it is not used!)

**Comment by Zimmi48** [comment]
> Finally, we should encourage a certain amount of experimentation with alternative approaches. The SERAPI doc says `The protocol is experimental and may change often.` It seems premature to try to force others to use it.

IIUC that's not really true anymore. SerAPI has become quite stable.

**Comment by jfehrle** [comment]
> I don't know whether this PR will end up getting merged or not but:

> it's not particularly urgent;
it can be useful even if it doesn't get merged

Who are the appropriate reviewers for this?  The review comments I got earlier didn't understand or ignored what the PR does.  I suspected it might be a long and maybe fruitless discussion; the parser stats were useful to generate at the time.  The stats-gathering framework and the ability to gather stats across CI without any build changes are reusable for many other stats.  Using SerAPI would be harder and less functional.

**Comment by gares** [comment]
I find the stats interesting and the patch simple enough, but there must be something wrong. I was looking at the results you post and some SSR productions that are surely used are marked with 0 counts. For example the binder "of" and "&" is used, at least in math-comp.
A simple test `Definition foo of nat := 2. `

**Comment by jfehrle** [comment]
> I find the stats interesting and the patch simple enough, but there must be something wrong.

Maybe more interesting than you thought.  The example you gave me is parsed as a `closed_binder`, not as an `ssrbinder`.  I verified this by adding a print statement in the .mlg.

**Comment by gares** [comment]
Maybe I read the stats wrong, or I get the name of the non terminals wrong. In SSR we extend the standard coq non terminal called closed_binder, I thought, with a production mentioning SSRbinder, but I guess I was wrong and SSRbinder is another thing. I'll check more carefully.

**Review by maximedenes — COMMENTED** [review]
What's the motivation for integrating this in Coq, as opposed to making it an external tool, used by documentation maintainers to define priorities, as mentioned in the original PR message?

**Comment by jfehrle** [comment]
> What's the motivation for integrating this in Coq, as opposed to making it an external tool, used by documentation maintainers to define priorities, as mentioned in the original PR message?

Do you mean not in the Coq executable or not in the source tree at all?  Even as an external tool, it would need to include and modify Coq source.

Please read the description again:

> This PR provides a simple mechanism for developers to gather statistics across multiple runs of coqc, whether in a local build or in CI. The initial version counts how many times each parser production is invoked. The code can be adapted to gather other statistics.

The most interesting part here is that it provides an easy way to instrument the Coq source code to gather statistics across a large corpus of .v files, e.g. all the .v files in a CI build--without changing the build process used in CI or whatever package you're working with.  For example, you could use the same framework to find the largest proof terms within a code base.  Or to locate all the places where the `apply` tactic successfully uses second-order unification, which I wanted to know when trying to find examples for the documentation.  The general instrumentation mechanism seems like something others might want to use and adapt for their own purposes.

I could split this into two parts: the general mechanism, to include in master, and the parsing statistics, which could be a branch in Coq or published in my own repository.  (I've not considered anything in my repository "published" before, not sure if I'd need to do anything differently.)  The developer writeup in the Coq repository could mention where to find the parsing stats branch.

**Comment by jfehrle** [comment]
Also, can this be assigned to someone so there can be a focused discussion and some resolution?  It's almost a year since I submitted the PR.

**Comment by gares** [comment]
I think this PR should be discussed during a Coq call: https://github.com/coq/coq/wiki/Coq-Calls
(unfortunately I will be probably missing the next one, but others will surely attend)

If it is just to decide a roadmap for the doc, well, we could run it just once or twice, so I understand the point made by Maxime. I see this piece of code as a useful deprecation and usage-analysis tool, and while it is trues that the same functionality can probably be provided with other means, the one proposed here is not in CI, AFAIK, so it may break tomorrow.

My personal opinion is that the patch is simple enough to be maintained, and the feature looks useful enough to me, but I'm not a maintainer of clib or coqpp, I guess they should have the last word.

My2C

**Comment by jfehrle** [comment]
Links from @ejgallego during the Coq Call:

Emilio Jesús Gallego Arias: https://github.com/coq/coq/pull/12259

Emilio Jesús Gallego Arias: https://x80.org/coq-coverage/vernac/g_vernac.ml.html

**Comment by jfehrle** [comment]
@palmskog We were discussing this in the Coq call today.  Someone suggested you might have useful opinions on this PR.

I expect we can improve how the parser statistics are gathered in future PRs; what I did in here was the best I could at the time--it takes a while to figure out how the parsing code works.  BTW, I've made some good progress recently toward generating a full parse tree.  This could generate parsing statistics in more robustly.  Tool developers should be able to use the parse tree callbacks for parsing Coq input in their tools, packaging TBD.

**Comment by jfehrle** [comment]
My thoughts on putting this into a branch are:
- How would anyone ever discover the branch exists?  (If there are a number of such private branches, we should have something in the main repository that points to them and briefly describes them.)
- As a developer tool (stats-gathering across the CI), it's not really tied to a specific release, so it's not clear when I should update the branch due to changes in master.
- It is more awkward to use if the code and documentation is in a branch.  Gathering stats seems like fairly basic functionality that's useful during the development process.

I think it's fair to say that the way the parser stats are collected and displayed isn't elegant.  It could be done better, but that was best I could do a year ago.  I think the general stats-gathering part of the code is clean, simple and easy to use.  I don't claim this addresses all stats-gathering requirements (e.g. predefined stats collection points that users can turn on at runtime).

**Comment by ejgallego** [comment]
One concern also discussed is whether the PR is hooking at the right level, not all parsing entries are registered thru `coqpp`.

**Comment by jfehrle** [comment]
Yeah, there may be additional points at which stats should be collected.  They can be added.  Even so, getting everything in the .mlgs is a good start.

**Comment by jfehrle** [comment]
@herbelin Will you be able to review this and eventually merge it?  On the Coq Call a week ago it sounded like you were willing to do so.  Thanks.

**Comment by herbelin** [comment]
> @herbelin Will you be able to review this and eventually merge it? On the Coq Call a week ago it sounded like you were willing to do so. Thanks.

As far as I'm concerned, I'm ok with it to be merged up to two comments: that the code added in `g_ltac.mlg` (`reference` case) is reduced to one line calling an auxiliary function, and, similarly in `tacentries.ml`. This is so that it is easy for other developers to see what is related to statistics and to choose more easily when reading these files on what to put their focus on.

Otherwise, my comments would depend on what you are expecting. Knowing how many times each tactic is called, or how many global references there are in the CI (8.9 millions if I read correctly) is interesting and certainly worth to be advertised somewhere (e.g. in a "statistics about Coq" web page), but maybe this does not need to be recomputed at each CI.

It also depends on how other developers feel about the change. Considering the size of the existing code base, the fear of adding technical debt is important (and this is why I recommend the changes above, so that the code is more modular). About passing or not via serapi is also a good question, which would allow to produce maybe different statistics. More generally, as was asked above, what kind of statistic do we want to collect, and, accordingly, where to put the hooks?

In any case, as said above and as far as I'm concerned, under the convention that you are the maintainer of the code producing statistics, I don't have more objections than the two comments above to merge, on the contrary, as I believe that to complement the advertising about Coq with a couple of various statistics would be cool.

So, maybe could we leave two weeks more to developers to comments and discuss the PR, and, if in two weeks, the conclusion remains that:
- it is useful for various purposes (help in possible deprecation, help in advertising)
- we may eventually need to add hook at other places
- using serapi could be considered for providing other kinds of statistics
- the added code should be well delimited so as to prevent technical debt

and that noone objects, then, I'll merge. Does it sound good to everyone?

**Review by ppedrot — COMMENTED** [review]
I side with @maximedenes on this one, i.e. I don't think it should be integrated in the main Coq branch.

This is the kind of quick-and-dirty patches I keep on a separate branch of mine that I apply on current master whenever I need to get such statistics. I have several of them already, e.g. memory profiling with statmemprof, dynamic stats of evars allocated with identity instances, histogram representation of the length of evar chains, etc.

So, I wouldn't complain too much if this were integrated, but I do find the patch:
- quite ugly, polluting parsing with global imperative code,
- and fairly specific in its goal, lexing considerations doesn't look like a very interesting metric, the important one being instead runtime number of tactic calls.

Thus I'd still like to have a bit more motivation rather than "we can do it".

**Comment by jfehrle** [comment]
@herbelin

> Knowing how many times each tactic is called, or how many global references there are in the CI (8.9 millions if I read correctly) is interesting and certainly worth to be advertised somewhere (e.g. in a "statistics about Coq" web page), but maybe this does not need to be recomputed at each CI.

It's not.  It runs conditionally in CI, controlled by whether `COQ_STATS_DIR` is set.

**Comment by jfehrle** [comment]
@ppedrot 

If you merged your memprof branch (making its activation conditional, maybe through an environment variable), you'd save others the time of reinventing it and make it easier to use.  It's pretty much undiscoverable by others as it is.  Or we could create a list of useful private branches.

> and fairly specific in its goal, lexing considerations doesn't look like a very interesting metric, the important one being instead runtime number of tactic calls meh

Depends on what you want to do--you use different statistics for different purposes.  I would like to add counts of tactics executed, their execution times, etc. if that's not already available.  This PR is also a step toward a common stats framework.

It would be much cleaner to generate parsing statistics in the parser itself.  I’ll figure out how to do that sometime in the next couple of months and then submit an updated PR.  So let's not merge this in its current form.

**Comment by herbelin** [comment]
> If you merged your memprof branch (making its activation conditional, maybe through an environment variable), you'd save others the time of reinventing it and make it easier to use. It's pretty much undiscoverable by others as it is. Or we could create a list of useful private branches.

This looks to me like a good point. A clean common modular reusable stats framework looks to me like a nice thing to have (talking only for myself though, of course).

**Comment by ppedrot** [comment]
The profiling patch requires a specific branch of the OCaml compiler, which is not really maintained. Hence it doesn't look like a good idea to me to merge this into the Coq main branch. It seems that there is recent work to get the statmemprof upstream, but when this happens I might reconsider my position.

**Comment by jfehrle** [comment]
> The profiling patch requires a specific branch of the OCaml compiler, which is not really maintained.

Meaning that it doesn't work or that it's not prebuilt in opam?  Opam has memprof variants for 4.06, which is what I used.  What do we want the OCaml folks to do?  Has anyone asked the OCaml folks about this?

**Comment by silene** [comment]
As this is still marked as needing discussion, I am removing the milestone.

**Pull request closed without merging**
