### PR TITLE
Fix #9613 use -coqlib when invoking coqchk

### LINKED ISSUE #9613: coq.dev opam package fails to build
#### Description of the problem

The coq.dev opam package fails to build, meaning many of our CI jobs are currently failing:

```
#=== ERROR while compiling coq.dev ============================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.07.0 | pinned(git+https://github.com/coq/coq.git#master#924468eb)
# path                 /builds/iris/stdpp/opamroot/ocaml-base-compiler.4.07.0/.opam-switch/build/coq.dev
# command              /usr/bin/make -j39
# exit-code            2
# env-file             /builds/iris/stdpp/opamroot/log/coq-749-865888.env
# output-file          /builds/iris/stdpp/opamroot/log/coq-749-865888.out
### output ###
# [...]
# Fatal Error: Failure: Validation failed: tuple size: found 11, expected 12 (in mutual_inductive_body).
#              Please report at http://coq.inria.fr/bugs/.
# Makefile.build:826: recipe for target 'theories/Logic/Hurkens.vo' failed
# make[1]: *** [theories/Logic/Hurkens.vo] Error 1
# COQCHK    Coq.Numbers.DecimalFacts
# Fatal Error: Failure: Validation failed: tuple size: found 11, expected 12 (in mutual_inductive_body).
#              Please report at http://coq.inria.fr/bugs/.
# Makefile.build:826: recipe for target 'theories/Numbers/DecimalFacts.vo' failed
# make[1]: *** [theories/Numbers/DecimalFacts.vo] Error 1
# make[1]: Leaving directory '/builds/iris/stdpp/opamroot/ocaml-base-compiler.4.07.0/.opam-switch/build/coq.dev'
# Makefile:166: recipe for target 'submake' failed
# make: *** [submake] Error 2
```

Is building master broken, somehow?

### PR DESCRIPTION
**Pull request by SkySkimmer**
In passing add -coqlib to coqchk's usage message.

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
There is quite a bit of overlap with #9576 , they don't exactly do the same choices in some parts; maybe I should just add the one line fix to that one, I dunno.

**Comment by SkySkimmer** [comment]
Lots of spurious failures

**Comment by SkySkimmer** [comment]
>There is qutie a bit of overlap with #9576 

It removes the argument parsing for -boot in coqchk but doesn't fix #9613 so it's only barely overlap IMO

**Comment by ejgallego** [comment]
I mean why does this PR remove the boot argument, is that needed to do the fix?

**Comment by SkySkimmer** [comment]
It's in passing since it's a noop. If you like I can put it back.

**Comment by gares** [comment]
I think it makes sense to merge this and #9576 (and merge the result ASAP)

**Comment by ejgallego** [comment]
> It's in passing since it's a noop. If you like I can put it back.

As you wish, I dunno if that would make the fix clearer; would certainly help in having less of a conflict to fix, not likely not a big deal.

**Comment by SkySkimmer** [comment]
changed

Gaëtan Gilbert

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
> I think it makes sense to merge this and #9576 (and merge the result ASAP)

Yup it does, please merge this [or I can take care] and I'll rebase #9576

**Comment by gares** [comment]
Please do it, I m a bit lost

**Comment by ejgallego** [comment]
> Please do it, I m a bit lost

Sure, thanks @gares .

**Pull request merged**
