### PR TITLE
Add colors in the CI

### PR DESCRIPTION
**Pull request by Villetaneuse**
We export a global "COQEXTRAFLAGS" in ci-wrapper.sh containing '-color yes'.

### CODE REVIEW

**Comment by Villetaneuse** [comment]
Idle CI.

@coqbot run full ci

**Comment by Villetaneuse** [comment]
@coqbot run full ci

**Comment by Villetaneuse** [comment]
Failures:
- plugin:ci-reduction_effects compares output of `coqc` with an expected output during tests (I should have anticipated this...)
- plugin:ci-hb_test same thing
- plugin:ci-atbr has timeout
- library:ci-http has a connection timeout `TimeoutError: [Errno 110] Connection timed out` could be related to this, if say, some `coqc` output is used to generate an http request? (I admit I don't know much about what this library really does).
- library:ci-mathcomp_test compares output of `coqc` with an expected output
- library:ci-iris compares output of `coqc` with an expected output during tests
- library:fiat_crypto_legacy : `COQC src/Curves/Edwards/XYZT/Basic.v Don't know what to do with `-color yes`
  Hmm... this is sad because this is the library that actually made me want to have coloured output in the first place.

For the `test` libraries, it is easy to use `-color no` instead. It is also possible to do it for a few chosen libraries.

I thought it would be nice to have an easier CI output to work with. Finding the error in a wall of warnings can be hard.

Do you think this is worth the effort?

Are there more robust ways to do it?

**Comment by SkySkimmer** [comment]
>I thought it would be nice to have an easier CI output to work with. Finding the error in a wall of warnings can be hard.

searching for `Error:` from the bottom usually works ok

**Comment by Villetaneuse** [comment]
> > I thought it would be nice to have an easier CI output to work with. Finding the error in a wall of warnings can be hard.
> 
> searching for `Error:` from the bottom usually works ok

You're right. But sometimes, for computation heavy libraries, I `make -j<N>`, which leads to a handful of errors and I want to correct all of them before the next run (starting the run itself can be quite sluggish).

But well, if I'm the only person to find these colours useful, I can close this PR and use a local hack.

Maybe still change:
```sh
export COQEXTRAFLAGS='-native-compiler no'
```
into
```sh
export COQEXTRAFLAGS="$COQEXTRAFLAGS -native-compiler no"
```
so that we can locally `export COQEXTRAFLAGS='-color yes'` (or whatever option we like) without getting it overwritten?

**Comment by SkySkimmer** [comment]
>But well, if I'm the only person to find these colours useful, I can close this PR and use a local hack.

I guess auto colors don't work in local because we pipe the log.

We could wrap the call in `script` to preserve colors, ie (slightly pseudocode)
~~~bash
if isatty && script command available; then
script -qfc ci-$foo | tee 
else ci-$foo | tee 
fi
~~~

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/18338

**Comment by JasonGross** [comment]
> Maybe still change:
> 
> ```shell
> export COQEXTRAFLAGS='-native-compiler no'
> ```
> into
> ```sh
> export COQEXTRAFLAGS="$COQEXTRAFLAGS -native-compiler no"
> ```
> so that we can locally `export COQEXTRAFLAGS='-color yes'` (or whatever option we like) without getting it overwritten?

I agree, this is a good idea.  Do you want to prepare a PR with just these changes?

**Comment by SkySkimmer** [comment]
I think this PR should be closed in favor of https://github.com/coq/coq/pull/18338

**Comment by Villetaneuse** [comment]
> I think this PR should be closed in favor of #18338

Done.

**Pull request closed without merging**
