### PR TITLE
docs(release-process.md): Add steps

### PR DESCRIPTION
**Pull request by erikmd**
- [x] Added / updated **documentation**.

Related:

- PR https://github.com/coq/opam/pull/3050 
- PR https://github.com/coq-community/docker-coq/pull/65#issuecomment-2178143747

Cc @proux01 @Zimmi48 (this is a doc-only draft PR, to be finalized after your feedback related to the PRs above)

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by proux01** [comment]
LGTM

**Comment by erikmd** [comment]
@proux01 OK thanks.

I'll wait for today's 1-to-1 call with @Zimmi48 to finalize the webhook part of this documentation.

**Comment by erikmd** [comment]
Ready. @Zimmi48 can you be the assignee?

**Review by Zimmi48 — APPROVED** [review]
@coqbot merge now

**Pull request merged**
