### PR TITLE
Understand some inductive cumulativity in old unification

### PR DESCRIPTION
**Pull request by SkySkimmer**
Part of https://github.com/coq/coq/issues/6976

Overlays: https://github.com/HoTT/HoTT/pull/1404

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Currently I've only wired it for the alpha-equal shortcut, which is enough to check that it allows a workaround to the example in https://github.com/coq/coq/issues/12623
Threading the `nargs` farther should be possible.

**Comment by SkySkimmer** [comment]
This ended up not needed for #12623. 
In light of unifall I don't have the motivation to be more complete.

**Comment by SkySkimmer** [comment]
waiting for https://github.com/coq/coq/pull/13644

**Comment by ppedrot** [comment]
Whats the status of this PR?

**Comment by SkySkimmer** [comment]
I'm going to bench just to see (https://gitlab.com/coq/coq/-/jobs/1036293640)
Considering it needs a hott overlay and low benefits it's probably not worth merging.

**Comment by ppedrot** [comment]
Let's close then.

**Pull request closed without merging**
