### PR TITLE
 Put common parts of ltac2 and ltac1 in vernac and put interop in new plugin

### PR DESCRIPTION
**Pull request by SkySkimmer**
profile_ltac is actually a generic profiler for Proofview.tactic so
goes in engine.

The goal selector grammar goes in g_vernac.

The VERNAC ARGUMENT EXTEND for ltac_selector and ltad_use_default stay
in g_ltac and get duplicated in g_ltac2 (they're trivial
declarations).

Replace https://github.com/coq/coq/pull/18352

Overlays:
- https://github.com/coq-tactician/coq-tactician/pull/76
- https://github.com/ejgallego/coq-serapi/pull/385

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
:clap: :clap: :clap:

**Review by ppedrot — APPROVED** [review]
As discussed offline I'm not super happy about the profiler in its current shape being part of engine, but I guess the PR is still a net increase in code quality, so good enough for me.

**Comment by ejgallego** [comment]
That's a good point @ppedrot , but indeed I think that getting the profiler nearer to the engine is a first step to clean it up.

**Comment by ppedrot** [comment]
We already discussed most of the contents in the base PR, I think we can merge already. @coqbot merge now

**Pull request merged**
