### PR TITLE
HMap: avoid hashing when map is empty, use Int.Map combinators more

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
fiat crypto in the bench says it failed with 
~~~
- tput: No value for $TERM and no -T specified
~~~
cc @JasonGross

**Comment by JasonGross** [comment]
> fiat crypto in the bench says it failed with
> 
> ```
> - tput: No value for $TERM and no -T specified
> ```
> 
> cc @JasonGross

I've seen that message a lot on our CI, but it's never been a fatal error.  (I'm not sure where it comes from, I never dug into it.). Is there another error in the log?  I'm guessing you caught Fiat Crypto in an inconsistent state, after some PR has been merged in Coq but before all the overlays had been merged into Fiat Crypto and its dependencies?  (It seems like there's been a new breaking change in Coq every day or every couple of days lately.)

**Comment by SkySkimmer** [comment]
It also says 
~~~
- make[1]: *** No rule to make target 'install-extra'.  Stop.
~~~

**Comment by JasonGross** [comment]
I see
```
[ERROR] The installation of coq-fiat-crypto-with-bedrock failed at "make EXTERNAL_REWRITER=1 EXTERNAL_COQPRIME=1 BINDIR=/home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/bin install install-standalone-ocaml".

#=== ERROR while installing coq-fiat-crypto-with-bedrock.dev ==================#
# context              2.1.3 | linux/x86_64 | ocaml-base-compiler.4.09.1 | file:///home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/new_coq_opam_archive/extra-dev
# path                 ~/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/.opam-switch/build/coq-fiat-crypto-with-bedrock.dev
# command              /usr/bin/make EXTERNAL_REWRITER=1 EXTERNAL_COQPRIME=1 BINDIR=/home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/bin install install-standalone-ocaml
# exit-code            2
# env-file             ~/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/log/coq-fiat-crypto-with-bedrock-27571-562391.env
# output-file          ~/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/log/coq-fiat-crypto-with-bedrock-27571-562391.out
### output ###
# [...]
# INSTALL src/Util/ZUtil/Tactics/ZeroBounds.glob /home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq//user-contrib/Crypto//Util/ZUtil/Tactics
# INSTALL src/Util/ZUtil/Tactics/Ztestbit.glob /home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq//user-contrib/Crypto//Util/ZUtil/Tactics
# INSTALL src/Util/ZUtil/Tactics/PullPush/Modulo.glob /home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq//user-contrib/Crypto//Util/ZUtil/Tactics/PullPush
# INSTALL src/Util/ZUtil/ZSimplify/Autogenerated.glob /home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq//user-contrib/Crypto//Util/ZUtil/ZSimplify
# INSTALL src/Util/ZUtil/ZSimplify/Core.glob /home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq//user-contrib/Crypto//Util/ZUtil/ZSimplify
# INSTALL src/Util/ZUtil/ZSimplify/Simple.glob /home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/lib/coq//user-contrib/Crypto//Util/ZUtil/ZSimplify
# make[1]: Entering directory '/home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/.opam-switch/build/coq-fiat-crypto-with-bedrock.dev'
# tput: No value for $TERM and no -T specified
# tput: No value for $TERM and no -T specified
# make[1]: *** No rule to make target 'install-extra'.  Stop.
# make[1]: Leaving directory '/home/gitlab-runner/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/ocaml-NEW/.opam-switch/build/coq-fiat-crypto-with-bedrock.dev'
# make: *** [Makefile.coq:621: install] Error 2

'opam install -v -b -j1 coq-fiat-crypto-with-bedrock' failed.
```
But this is not useful, and I think the true error is earlier.  Where can I find ~/builds/gGKko-aj/0/coq/coq/_bench/opam.NEW/log/coq-fiat-crypto-with-bedrock-27571-562391.out?

I think the install-extra error just means something failed around
https://github.com/coq/coq/blob/b262febae87ca31aec84b5ee9eaa9d7ebba3f9d0/tools/CoqMakefile.in#L632
it seems like a bogus message to me, though I don't understand what's going on.

**Comment by SkySkimmer** [comment]
https://coq.gitlabpages.inria.fr/-/coq/-/jobs/3592114/artifacts/_bench/logs/coq-fiat-crypto-with-bedrock.NEW.opam_install.1.stdout.log has the whole log

**Comment by SkySkimmer** [comment]
The setting of SELF in https://github.com/mit-plv/fiat-crypto/pull/1710 is probably the cause of the issue
Makefile.standalone is included in the main Makefile so will override SELF there

**Comment by JasonGross** [comment]
Oh, I see, let me fix that

**Comment by JasonGross** [comment]
https://github.com/mit-plv/fiat-crypto/commit/a0085a892cd18edf97de79ee203523d1520dca1d thanks for tracking this down @SkySkimmer

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
