### PR TITLE
make sure `subst` preserves the order of hypotheses

### PR DESCRIPTION
**Pull request by samuelgruetter**
According to the [refman](https://coq.inria.fr/refman/proofs/writing-proofs/equality.html#coq:tacn.subst), `subst` preserves the order of hypotheses.

However, in the following example, it flips the order of `A` and `B`:

```coq
Lemma test(k f: nat)(E: k = f)(A: k < 3)(B: 3 < k): False.
Proof.
  subst k.
```

This PR attempts to make sure the hypothesis order is always preserved.
The original code already tried to do that, but seems incorrect in the case where two hypotheses containing the variable to substitute appear next to each other.

The reason I care about this is that when analyzing what a tactic `tac` does, I want to diff the goal before and after running `tac`, and if `tac` invokes `subst` and that changes the hypothesis order, I get an unnecessarily big diff.

- [X] Added / updated **test-suite**.
- [ ] Added **changelog**.
- [ ] Opened **overlay** pull requests.

### CODE REVIEW

**Comment by ppedrot** [comment]
If we want to proceed with this it will need some overlays (and probably a compat flag).

**Comment by SkySkimmer** [comment]
@samuelgruetter are you planning to write overlays?

**Comment by ppedrot** [comment]
@samuelgruetter any current plan for this PR?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by SkySkimmer** [comment]
With nobody writing overlays this cannot get merged.

**Pull request closed without merging**
