### PR TITLE
New warnings machinery

### PR DESCRIPTION
**Pull request by maximedenes**
Warnings can now be enabled and disabled through command line, locations are printed and active by default in coqc.

### CODE REVIEW

**Comment by ejgallego** [comment]
Congrats on the cool stuff!! A few comments:

- How does this interact with IDEs? AFAICS the IDEs will get warnings without position info?
- The patch provides a new notification mechanism, but it looks to me that it should use `Feedback` for consistency. Feedback already provides a `MsgError` message; IMHO a `Feedback` message restructuration could happen in the future, but note the overlap here; `Feedback` needs to provide per domain/per component filtering notifications, etc... There is no reason `kind` should be exclusive to warnings for example.
- I'm not sure the flag parsing belongs in the place it is.
- With regards to `cur_location`, I think this codepath is not used in the IDE case. Also, there could be two potential problems: warnings that happen in parsing will be reported with incorrect location(confirmed). Also warnings that happen at Qed may be potentially misreported, but I need to double check this second case. IMHO making location optional could be interesting. I also pushed a small extension of the current feedback there: https://github.com/ejgallego/coq/tree/add_loc_to_feedback but it won't work for IDEs as the message has to forget the location. (It could be extended thou, at the cost of yet another API change).
- I'm not sure about the warning registration mechanism, I like to register all warnings in a central place  (even if they are extensible), but this would not be compatible with the current approach.
- The motivation for using `Dyn` here seems a bit weak:
  - Almost all warnings are called only once, 
  - As usual in Dyn, you need anyways to register a projection to a common datatype.
  - This code doesn't rely on any special machinery and achieves a similar purpose. It also allow warnings to take different arguments, which could be convient:
```ocaml
val ecreate : name:string -> bool -> ('a -> Pp.std_ppcmds) -> 'a -> unit

let w : (string, bool) Hashtbl.t = Hashtbl.create 100

let ecreate ~name b pp =
  Hashtbl.add w name b;
  fun x -> Feedback.msg_warning (pp x)
```

**Comment by herbelin** [comment]
Looks very good! Congrats too.

**Comment by maximedenes** [comment]
Thanks a lot for the feedback, Emilio. I got rid of Dyn.t, it was indeed not needed here. Can you say more about "warnings that happen at Qed may be potentially misreported"? Do you have concrete examples.

**Comment by ejgallego** [comment]
I'll rerun my "test-suite", let me get back to you tomorrow!

**Comment by ejgallego** [comment]
Hi Max, here are my comments for the current version of the patch:
- A CHANGUES entry is missing.
- I must disagree with the modification of the `Warning` constructor of `Feedback.level`. This seems to break the XML protocol and is IMO not the right place to touch.
- I must disagree too with the introduction of a new `MsgWarning` type, IMO, messages should gain location info as outlined in the add_loc tree. Emitting a double `Feedback` is IMVHO a **critical** issue with the patch.
- `parse_flags` should not be in cWarning but in the corresponding toplevel IMO (For instance SerAPI uses a different command line library)
- The `print_ghost` parameter in `Pp.pr_loc` is interesting, but I'm not sure pr_loc should have control over this and not the callers themselves. But IMO, the right fix is to make the located type
  `'a located = ('a * Loc.t option).
- Regarding warnings on Qed, sorry, I can't reproduce it o_o
- I suggest you declare the output format experimental as tools don't rely too much on parsing it.

Apart from the double-feedback issue and the small nits, again, amazing work! It is so good to get this!

**Comment by ejgallego** [comment]
#223 tries to help this patch to report warnings with a single feedback message.

**Comment by ejgallego** [comment]
I rebased the tree wrt #223 , in case it helps.
https://github.com/ejgallego/coq/commits/warnings

**Comment by ejgallego** [comment]
Still note that there is the printing duplication in ppstyle. I may extract that from PR #185 and give it a go.

**Comment by ejgallego** [comment]
Ok, done in #224, this should further simplify this patch but I'll await for comment to rebase more.

**Comment by maximedenes** [comment]
Rebased and merged. Thanks for your help, Emilio!

**Pull request closed without merging**
