### PR TITLE
Moving file in obsolete doc/changelog/08-tools change log directory to a more appropriate change log directory

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** infrastructure

PR #13460 may have introduced some confusion in the `doc/changelog` directory. It added a changelog file in `08-tools` while this directory was (apparently concurrently) renamed into `08-cli-tools`. This resulted into two directories numbered `08` and `make-changelog.sh` is now unhappy.

Assuming that the changelog for #13460 present in 08-tools has now been taken into account for 8.15 and is thus obsolete for master, the current PR removed the confusing directory.

Hoping this is the right thing to do (cc @Zimmi48, @SkySkimmer)??

### CODE REVIEW

**Comment by SkySkimmer** [comment]
>Assuming that the changelog for #13460 present in 08-tools has now been taken into account for 8.15

Milestone is 8.16 though

**Comment by Zimmi48** [comment]
>Milestone is 8.16 though

Then the PR should just move the file instead of deleting it.

**Comment by herbelin** [comment]
OK, moved from 08-tools to 08-cli-tools then.

**Review by Zimmi48 — APPROVED** [review]
Will merge when the refman CI passes.

**Comment by Zimmi48** [comment]
Sorry, I just realized that this changelog entry is about extraction, and thus not really suite for CLI tools. Usually, extraction goes to Misc, although we could also consider introducing a new category specifically for it.

**Comment by herbelin** [comment]
OK, moving it to misc at the current time. I would otherwise advocate for adding a more specific section in the longer term.

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
