### PR TITLE
Improve field_simplify on fractions with constant denominator

### LINKED ISSUE #9370: Weird behaviour of field_simplify with 1/1
Dear Coq Team,

the following sequence of Coq commands results in the goals in the comments:
```
Require Import Reals.
Open Scope R_scope.
Goal 1/1=1.
Proof.
  field_simplify(1/1). (* 1 / 1 = 1 *)
  field_simplify. (* 1 / 1 / (1 / 1) = 1 / 1 *)
  field_simplify. (* 1 / 1 = 1 / 1 *)
```

I would expect that field_simplify (1/1) simplifies 1/1 to 1. The following field_simplify is rather weird. Of cause field can solve this, but I frequently use field_simplify for subexpressions of terms field can't handle.

Otherwise I am quite happy with field_simplify, although I think one might be able to extend it to what radcan does in Maxima (which also takes care of roots and powers and usually gets the job done).

This is on Coq 8.9 master from a week back,

Best regards,

Michael

### PR DESCRIPTION
**Pull request by thery**
Before this patch, `x` was "simplified" to `x / 1`.

- [x] Added / updated test-suite
- [ ] Entry added in CHANGES.md.

Fixes #9370.

Overlays:

 - [x] CompCert: [branch](https://github.com/vbgl/CompCert/tree/field_simplify_int); [PR](https://github.com/AbsInt/CompCert/pull/291)
 - [x] VST: [issue](https://github.com/PrincetonUniversity/VST/issues/335)
 - [ ] Coquelicot: https://gitlab.com/vbgl/coquelicot/commits/field_simplify_int

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
@thery : this is definitely an improvement, but I wonder if this wouldn't break a lot of proofs. It would definitely break a lot of my proofs. I use field simplify frequently to simplify arguments of functions and right now I frequently do a rewrite x/1->x afterwards. I guess this rewrite would fail now. Of cause I have no issues changing my proofs, I just want to avoid pain for others.

Does all code in CI run through with this change?

**Comment by maximedenes** [comment]
> Does all code in CI run through with this change?

CI run has just started. We indeed expect a lot of proofs to break, but they should be easy to fix (most often, it is just that this post-processing is no longer necessary).

**Comment by thery** [comment]
@MSoegtropIMC it broke already one file of the standard Ratan but the patch was simply to remove code. Maybe in your case, you could turn your rewrite Rdiv_1_r into rewrite ?Rdiv_1_r so it will work with both versions.

**Comment by amahboubi** [comment]
Hi @thery. I am happy to have a look at this, but rather next week if possible.

**Comment by maximedenes** [comment]
> Hi @thery. I am happy to have a look at this, but rather next week if possible.

Unfortunately, we are freezing on Tuesday, and this would be a nice improvement to have in 8.10. But maybe we can find another reviewer, don't worry :)

**Comment by maximedenes** [comment]
(or maybe Monday works for you)

**Comment by thery** [comment]
@amahboubi @maximedenes let's wait to see what is the consequence of this change on the CI....

**Comment by thery** [comment]
> Hi @thery. I am happy to have a look at this, but rather next week if possible.

@amahboubi don't worry, the system submitted the review request automatically, not me....

**Comment by MSoegtropIMC** [comment]
I am anyway working on the atan file over the weekend (getting the asin and acos PR + my enhacements in), so I can take care of the atan file.

> Maybe in your case, you could turn your rewrite Rdiv_1_r into rewrite ?Rdiv_1_r so it will work with both versions.

Yes, definitely an easy option, and then remove it after the new version is official.

**Comment by maximedenes** [comment]
Ok, so this breaks flocq, corn, coquelicot and compcert. I'll try to prepare backward-compatible patches, it should not be too hard.

**Comment by MSoegtropIMC** [comment]
> Ok, so this breaks flocq, corn, coquelicot and compcert. I'll try to prepare backward-compatible patches, it should not be too hard.

We can share the work, I could do flocq or coquelicot, maybe both. It would be fair since I created the mess (by stating that x/1 is a suboptimal result for a simplifier).

**Comment by maximedenes** [comment]
> We can share the work, I could do flocq or coquelicot, maybe both.

Ok, thanks! I'll work on other urgent things meanwhile, then.



> I created the mess (by stating that x/1 is a suboptimal result for a simplifier).

I think you're not the only one to find `x/1` suboptimal ;)

**Comment by MSoegtropIMC** [comment]
> Ok, thanks! I'll work on other urgent things meanwhile, then.

Ok, I start with Flocq and then work on Coquelicot. Shall I fix it so that it works with both versions (e.g. use ? for extra rewrites) or should I "clean it up"?

**Comment by maximedenes** [comment]
> Ok, I start with Flocq and then work on Coquelicot. Shall I fix it so that it works with both versions (e.g. use ? for extra rewrites) or should I "clean it up"?

It would probably be better to submit backward-compatible patches and let downstream do the "clean-up" when they like.

**Comment by MSoegtropIMC** [comment]
Apparently I can't fork the flocq project on INRIA gitlab - it says "You have reached your project limit" (I have no projects on INRIA gitlab as yet). I guess as external user I am simply not allowed to fork a project.

Can someone give me the rights to do so, or should I just replicate it and send patches? I guess I can't create pull requests from a gitlab.com replication of the repo, so it would be convenient to create a fork.

**Comment by MSoegtropIMC** [comment]
I sent patches for Flocq and Coquelicot to @silene via email. I could look at the others as well (it is quite easy to fix).

**Comment by maximedenes** [comment]
Flocq and Coquelicot have been updated. I'll try to fix Corn and CompCert.

**Comment by maximedenes** [comment]
Fix submitted to Corn. I'll wait for reviewers approval here before submitting the fix to CompCert.

But basically this is ready modulo reviews.

**Comment by maximedenes** [comment]
@amahboubi any chance you can look at it this week?

**Comment by MSoegtropIMC** [comment]
@maximedenes : are the addon patches integrated? Should we rerun CI to see if this is fixed now?

**Comment by maximedenes** [comment]
> No sorry, I will be mostly offline until April 22nd...

@amahboubi No worries, thanks for letting us know!

> are the addon patches integrated? Should we rerun CI to see if this is fixed now?

@MSoegtropIMC They have been, except for CompCert. Xavier asked us to submit patches only once the Coq PR has been approved (to reduce noise). So I'm afraid we'd need a reviewer first.

But I think if you approve the change, it should be enough. We were already had pairs of eyes on the code.

**Comment by MSoegtropIMC** [comment]
@maximedenes : ok, I just restarted CI and will do a final review.

**Comment by MSoegtropIMC** [comment]
@maximedenes : I will look into the entities still failing in CI (except CompCert).

Is there a fork which contains the CompCert patch? If so I would prefer to redirect CompCert to the fork until it is merged in master.

**Comment by MSoegtropIMC** [comment]
@silene : did the patch for Coquelicot I sent you March 31st make it into git? I can't find it in
https://gforge.inria.fr/scm/browser.php?group_id=3599.

The Flocq patch I sent with the same mail is merged into Flocq master and picked up here.

**Comment by MSoegtropIMC** [comment]
Since CI failures are increasing I will rebase and compare the failures with a CI run on master.

**Comment by MSoegtropIMC** [comment]
Here is the reference CI run to the master ref I rebased to (11dd3aeedd5662ea67c89bacb02cce5b562a9532):

<https://gitlab.com/coq/coq/pipelines/57208884>

I would say all deviations in CI results must be fixed before this can be merged. I will work on this.

Since pushing changes upstream seems to take a while I will redirect all CI projects which need changes to clones, so that we can get forward with this PR.

**Comment by MSoegtropIMC** [comment]
@maximedenes : it is unclear to me if you already did the CompCert patch or want to wait until this is merged. Since I can't find a branch on your fork of CompCert, I guess the latter. If you already have a patch, please send it to me asap, otherwise I will (re)do the CompCert patch. I will then switch CI to a fork of CompCert until the patch is merged upstream.

After the rebase still failing are:
- Coquelicot (fix is sent to @silene but not yet merged upstream - I will fork)
- VST (fails in CompCert but might have additional issues)
- CompCert
- nix - it fails in the test suite in a `test-suite/modules/PO.v` which does contain arithmetic but no field stuff - I will check if it is related.

**Comment by maximedenes** [comment]
This is still pending on a review. Any chance @amahboubi or maybe @ppedrot could look at it?

**Comment by MSoegtropIMC** [comment]
This is also pending a passing CI - something I am working on but I priorized it behind the Windows CoqIDE.

**Comment by maximedenes** [comment]
> This is also pending a passing CI - something I am working on but I priorized it behind the Windows CoqIDE.

Yes, but as I wrote above, I'm waiting for an approving review before submitting a patch to CompCert.

**Comment by MSoegtropIMC** [comment]
@maximedenes : It would be easy to redirect CompCert to a private fork until it is fixed. I would prefer this and having CI pass over disabling CompCert in CI or waiting between approval and merging until the change is done upstream.

**Comment by maximedenes** [comment]
> waiting between approval and merging until the change is done upstream.

So far, I've always experienced a very high reactivity from the CompCert developers, as long as the Coq patches had been approved, so I'd rather go for that. Switching to tracking a fork will be much more complicated if people need other overlays for CompCert.

If neither @amahboubi nor @ppedrot are available, maybe @vbgl can have a look at this. The change is fairly straightforward anyway.

**Comment by vbgl** [comment]
No problem. I’ll look into it today.

**Review by vbgl — APPROVED** [review]

**Review by amahboubi — APPROVED** [review]
Looks good to me.

**Comment by vbgl** [comment]
CompCert and VST have been updated. This is now only waiting for coquelicot. May by any chance Guillaume incorporated the relevant patch? Thanks.

Ping @silene

**Comment by Zimmi48** [comment]
If this is something you want to merge without delay, you could still temporarily change the location of coquelicot in `ci-basic-overlays.sh` to use a fork...

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : 

> If this is something you want to merge without delay, you could still temporarily change the location of coquelicot in `ci-basic-overlays.sh` to use a fork...

This is already done in commit <https://github.com/coq/coq/pull/9854/commits/b50bd0f9fd2fedb7dd14edd39baabf2fc3be8e3b>. It passes in CI.

I would say we should go for it with this temporary redirection.

**Review by MSoegtropIMC — APPROVED** [review]
Definitely an improvement and with all modules in CI passing good to go.

**Comment by vbgl** [comment]
The overlay machinery is a kludge: it passes CI, but breaks once merged!

**Comment by MSoegtropIMC** [comment]
Hmm, looking at it the changes are integrated into Coquelicot master - just @silene changed the repository to <https://gitlab.inria.fr/coquelicot/coquelicot.git>. This was on my request since the old scm.gforge.inria.fr is harder to use. Sorry, I should have changed it in the ci-basic-overlay.sh file - to busy with the IDE stuff. I will change it now.

**Review by Zimmi48 — COMMENTED** [review]
@MSoegtropIMC Since you are changing the location of Coquelicot to a GitLab instance, you should also remove `FORCE_GIT=1` from `dev/ci/ci-coquelicot.sh`.

**Comment by MSoegtropIMC** [comment]
> @MSoegtropIMC Since you are changing the location of Coquelicot to a GitLab instance, you should also remove `FORCE_GIT=1` from `dev/ci/ci-coquelicot.sh`.

Ah ok, that's how it works in the main CI (I am more familiar with how it works in the Windows build). I will change it later today.

An etiquette question: is it considered OK to amend and force push to some else's PR branch or should I do a separate commit for this?

**Comment by Zimmi48** [comment]
Yes it's OK as long as you announce it so that the other is not taken by surprise.

**Comment by Zimmi48** [comment]
I'm only thinking about this now but it is not normal that this PR did not have a changelog entry given that it broke compatibility.

**Comment by MSoegtropIMC** [comment]
Good point, sorry that I missed it during the final review before merging.

@thery : can you create a small PR for this?

**Comment by Zimmi48** [comment]
I'm preparing a PR to move the last changelog entries so you may just want to give me the text to include, especially what kind of breakage is to be expected.

**Comment by thery** [comment]
@Zimmi48 
The simplified value returned by `field_simplify`  is not always a fraction anymore. 
When the denominator is 1, it returns `x` while previously it was returning  `x/1`.
This change could break codes that were post-processing application of `field_simplify` to get rid of these `x/1`.

**Comment by Zimmi48** [comment]
Thanks!

**Pull request merged**
