### PR TITLE
Turn "algebraic on the right" error into regular univ inconsistency

### LINKED ISSUE #17464: "Algebraic universe on the right" is underinformative and should specify where the algebraic universe is coming from
#### Description of the problem

Consider
```coq
Polymorphic Definition foo@{u} (x : Type@{u+1}) := x.
Definition bar (x : Type) := foo x.
(* Error: Algebraic universe on the right *)
```

The error message does not specify what the algebraic universe is, nor where it's coming from.  I ran into this because I accidentally wrote `Definition foo@{u} (A : Type@{u+1}) : Type@{u}` instead of `Definition foo@{u} (A : Type@{u}) : Type@{u+1}` in my code; the `u+1` is necessary to write code that works with both `Set Universe Checking` and `Unset Universe Checking`, and the thing I'm asking for here is that Coq give me a bit more help in finding where I made my mistake in writing algebraic universes.

#### Coq Version

8.16

### PR DESCRIPTION
**Pull request by SkySkimmer**
The error message will say something like "cannot enforce x <= y+1" which is true.

Fix #17464

Overlays:
- https://github.com/ejgallego/coq-serapi/pull/330

### CODE REVIEW

**Comment by JasonGross** [comment]
> The error message will say something like "cannot enforce x <= y+1" which is true.

Can we make sure that the explainer says "because y+1 is algebraic" or "because y+1 is algebraic and algebraic universes on the right are not supported"?  (Maybe add a output test case?). Otherwise we're just asking for users to be confused about this error message.

**Comment by JasonGross** [comment]
(do the "cannot enforce x < y (because y <= z <= x)" messages come from sort_inconsistency, or somewhere else?)

**Review by ppedrot — CHANGES_REQUESTED** [review]
I am also concerned that the message is more confusing now than before. The displayed message should mention something about the unification engine not being able to handle this class of problems.

**Comment by ppedrot** [comment]
@coqbot run full ci

**Review by ppedrot — APPROVED** [review]

**Review by Alizter — APPROVED** [review]

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
