### PR TITLE
[api] Make `vernac/` self-contained.

### PR DESCRIPTION
**Pull request by ejgallego**
We make the vernacular implementation self-contained in the `vernac/`
directory. To this extent we relocate the parser, printer, and AST to
the `vernac/` directory, and move a couple of hint-related types to
`Hints`, where they do indeed belong.

IMO this makes the code easier to understand, and provides a better
modularity of the codebase as now all things under `tactics` have 0
knowledge about vernaculars.

The vernacular extension machinery has also been moved to `vernac/`,
this will help when #6171 [proof state cleanup] is completed along
with a stronger typing for vernacular interpretation that can
distinguish different types of effects vernacular commands can perform.

This PR introduces some very minor source-level incompatibilities due
to a different module layering [thus deprecating is not
possible]. Impact should be relatively minor.

Overlays:
- https://github.com/Mtac2/Mtac2/pull/90
- https://github.com/ppedrot/ltac2/pull/60
- https://github.com/mattam82/Coq-Equations/pull/94

### CODE REVIEW

**Comment by ejgallego** [comment]
Adjusted reviewers based on code owners, `dev/base_include/top_printers` seem to be orphan, should we open a bug?

**Comment by ejgallego** [comment]
For those wondering about the motivation of the vernac refactorings, it is mainly due to wanting to improve a bit the interfaces exported by `Vernacinterp` and friends so document managers have an easier time to implement incremental compilation and parallel processing.

**Comment by ejgallego** [comment]
Most of the patch is just `PCoq -> PVernac` renaming. Pity we don't have packing yet, but I understand that Dune will provide facilitates in the future that would allow one to extend modules, so for example `PCoq` could have been extended by `vernac` so the users above wouldn't need to change it.

**Review by ppedrot — APPROVED** [review]
LGTM.

**Comment by maximedenes** [comment]
I can take this PR as the vernac secondary maintainer.

**Review by maximedenes — APPROVED** [review]
Looks good to me as well. This PR contains one unrelated, but very minor change.

**Comment by maximedenes** [comment]
@herbelin anything to add?

**Comment by maximedenes** [comment]
If no objection, I will merge tomorrow.

**Pull request merged**
