### PR TITLE
Add back [Bind Scope ... with Funclass] and [Bind Scope ... with Sortclass], move [type_scope] declaration out of OCaml and in to Init.Notations, declare function_scope in Init.Notations (on trunk)

### PR DESCRIPTION
**Pull request by JasonGross**
This replaces #77, and is based on trunk rather than v8.5.

### CODE REVIEW

**Comment by JasonGross** [comment]
Rebased against trunk.  Any updates on merging this?  (@mattam82?)

**Comment by mattam82** [comment]
test build

**Comment by mattam82** [comment]
I tested it locally and it is fine, merged in trunk.

**Comment by JasonGross** [comment]
Thanks!

**Pull request closed without merging**
