### PR TITLE
[v8.12] Carefully select which versions of add-ons are included in the Windows installer.

### PR DESCRIPTION
**Pull request by Zimmi48**
Cf. #12360.

@Janno: Should mtac2 get a new `master-8.12` branch? The start point could be mtac2/mtac2@62071fe76d05e7d1bd43583514ad498102b556bd.

- [x] bignums
- [x] equations
- [x] mtac2
- [x] mathcomp
- [x] menhir
- [x] menhirlib
- [x] compcert
- [x] extlib
- [x] quickchick
- [x] coquelicot
- [x] vst
- [x] aactactics
- [x] flocq
- [x] interval
- [x] gappa_tool
- [x] gappa
- [x] elpi
- [x] HB

Link to trigger a pipeline with only the Windows build with all addons: https://gitlab.com/coq/coq/pipelines/new?var[ONLY_WINDOWS]=true&var[WINDOWS]=enabled_all_addons&ref=pr-12415

### CODE REVIEW

**Comment by Zimmi48** [comment]
cc @MSoegtropIMC: the part that is already done can already be reviewed. Note that for the beta release, I think this is OK to be approximate and to find a good compromise between effort and quality. For the final (8.12.0) release, we can expect that most libraries will have got new compatibility releases, and we can use these.

**Comment by Janno** [comment]
Done! https://github.com/Mtac2/Mtac2/tree/master-8.12

**Comment by gares** [comment]
For HB we should soon make a 0.9.1 release for coq-elpi 1.4.
It is not clear how can we help/synchronize in this PR. Do you want us to make a coq-8.12 branch and push he re a commit updating basic-overlay?
CC @CohenCyril @pi8027

**Comment by Zimmi48** [comment]
@gares Your choice on creating an 8.12-specific branch or not. The important thing for us is that *you* decide what gets included in the Windows installer. If the tag is ready soon, we can use this.

**Comment by gares** [comment]
It depends if point releases of Coq are allowed to pick up updates of add-ons. If so making a branch, and have basic-overlays point to a branch rather than a commit, is probably the best option.

**Comment by Zimmi48** [comment]
Yes, this is fine.

**Comment by Zimmi48** [comment]
>with the policy that you upstream only push fixes on that branch

I assume that by "you upstream" you mean the project's maintainers.

**Comment by gares** [comment]
Yes (given I'm also an upstream I got messy).

**Comment by gares** [comment]
WRT HB, I've this PR https://github.com/math-comp/hierarchy-builder/pull/76 updating coq-master to a commit we would be OK to release with Coq. Still waiting for CI.

**Comment by gares** [comment]
It is merged now

**Comment by Zimmi48** [comment]
So IIUC you are recommending to use the current head of `coq-master`, that is math-comp/hierarchy-builder@d450025f89fccb1c48c82b7747321367868fa5e1, not the head of `master` (math-comp/hierarchy-builder@9d4cc1ac363782aecb61da3d19f61b98f2c93fd3), nor the new `v0.9.1` tag

**Comment by gares** [comment]
Indeed using the tag would be best, I got confused. I shoul crete a branch coq-v8.11 from the tag.

**Comment by Zimmi48** [comment]
I guess you meant `coq-v8.12`.

**Comment by Zimmi48** [comment]
In the current state, menhir doesn't build. The error message is:

```
File "src/stage2/dune", line 66, characters 18-21:
66 |   (libraries unix fix menhirLib menhirSdk)
                       ^^^
Error: Library "fix" not found.
Hint: try: dune external-lib-deps --missing -p menhirLib,menhirSdk,menhir @install
File "src/stage1/dune", line 16, characters 18-21:
16 |   (libraries unix fix menhirLib menhirSdk)
                       ^^^
Error: Library "fix" not found.
Hint: try: dune external-lib-deps --missing -p menhirLib,menhirSdk,menhir @install
        pack lib/pack/menhirLib.{ml,mli}
Creating menhirLib.ml...
Creating menhirLib.mli...
```

in the Dune build step. I've disabled building menhir and its reverse dependencies for now. I don't think I'll spend more time looking into it for the beta.

The other add-ons that still haven't been tested (I've picked their version blindly, and I am not very confident on them building correctly) are gappa and interval (since they are not part of the CI).

Apart from this and the testing of the resulting installer, this PR is virtually ready.

**Comment by Zimmi48** [comment]
The latest run failed immediately. I expect this is an issue with disk space that may have been polluted by the previous runs.

**Comment by Zimmi48** [comment]
@gares There seems to be an issue with building Elpi. Can you help me figure it out?

```
Error: stat: tests/sources/elpi-checker-copy.elpi: No such file or directory
Error: stat: tests/sources/elpi2html-copy.elpi: No such file or directory
make: *** [Makefile:30: build] Error 1
```
(https://gitlab.com/coq/coq/-/jobs/582934382/artifacts/browse/artifacts/)

BTW, it looks like there is a problem in the naming of the artifact files (flag files and build logs): only the version number is shown, not the name of the add-on.

**Comment by Zimmi48** [comment]
@MSoegtropIMC FTR, with the minor fix that this PR contains, the Interval library builds correctly. However, the gappa-tool doesn't. It fails with this error:
```
./configure: line 3162: AX_PROG_CXX_FOR_BUILD: command not found
./configure: line 3356: -Wall: command not found
configure: error: in `/build/gappa_tool-f53e105cd73484fc76eb58ba24ead73be502c608':
configure: error: failed
See `config.log' for more details
```

I'm not going to investigate this.

So the current status of this PR is that menhir, elpi and gappa-tools are the three things that fail (possibly some of their reverse dependencies too, but we cannot test that yet).

**Comment by gares** [comment]
These files are symlinks, But are also only needed to run the test suite. Did yo change the build script? We don't need to run it. I don't think I run it in the pr that added elpi, did I?

**Comment by Zimmi48** [comment]
No I didn't change anything to the way Elpi is built.

**Comment by gares** [comment]
Something must have changed. Maybe something is built there by dune even if th Tess are not run. Are all slave set up the same wrt symlinks? Cygwin has multiple settings, IIRC, and these two files are the only symlinks. Finally I suspect calling dune build -p elpi does not look at these files, while make build is probably doing @all

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I am a bit confused - I saw that menhir and menhirlib is still excluded so I worked on these but then I saw you changed the build instructions. I guess these instructions don't work?

**Comment by Zimmi48** [comment]
Indeed, they don't. I gave you the error message that this results in, in a comment above.

**Comment by Zimmi48** [comment]
Looking at #12475, it looks like I wasn't so far from succeeding.

**Comment by MSoegtropIMC** [comment]
> Indeed, they don't. I gave you the error message that this results in, in a comment above.

OK, fine. I am almost there - it builds but the addon_install step then fails because file locations changed.

I wonder what is the most effective way of working on this. I guess I make a branch based on yours but do a separate PR for CI checking?

**Comment by MSoegtropIMC** [comment]
> Looking at #12475, it looks like I wasn't so far from succeeding.

Yes - the mysteries for dune. I guess they took the name of this novel for a reason ;-)

**Comment by MSoegtropIMC** [comment]
I just rebased on yours - I think it is more convenient.

**Comment by Zimmi48** [comment]
What convenience does it bring to you? To me it is convenient since I won't be able to merge your branch as easily.

**Comment by MSoegtropIMC** [comment]
> What convenience does it bring to you? To me it is convenient since I won't be able to merge your branch as easily.

For me it is easier to locally test VST when coqinterval and gappa work. I guess these are OK in your branch since they are active in the gitlab.bat - or is there something I need to do for these?

I can easily remove this when I am finished.

Btw.: in the release branches it is common to have the addons always enabled. Do you always make a manual pipeline with "WINDOWS=enable_all_pipelines" or is there some trick?

**Comment by Zimmi48** [comment]
VST is disabled in my branch since it depends on CompCert which depends on menhir.
Interval builds just fine but Gappa doesn't. I gave you the error message in a [comment above](https://github.com/coq/coq/pull/12415#issuecomment-639818415).

**Comment by Zimmi48** [comment]
> Btw.: in the release branches it is common to have the addons always enabled. Do you always make a manual pipeline with "WINDOWS=enable_all_pipelines" or is there some trick?

I do. I forgot it was common to always enable them!

**Comment by MSoegtropIMC** [comment]
> VST is disabled in my branch since it depends on CompCert which depends on menhir.
> Interval builds just fine but Gappa doesn't. I gave you the error message

OK, I will do CompCert and VST next. For CompCert I will reproduce the platform friendly variant in opam. For VST I also agreed on a certain commit + patch with Andrew. I should be able to finish this today. We discuss Gappa afterwards.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I am a bit unsure how to handle CompCert technically. We should base it on the 3.7 platform friendly opam release (which is agreed on with @xavierleroy). This already has quite a few patches:
(https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-compcert/coq-compcert.3.7%7Ecoq-platform/files)
If I put the patches required for 8.12 on top, this gets a bit confusing. Shall I release this for the beta from my private fork instead, where I collect the patches as cherry picks?

From previous conversations with @xavierleroy I would say he would prefer minimal patches over the last release and no patches which do functional changes - only compatibility and build oriented things.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I will prepare a branch for CompCert on my fork. If we want to use Coq local patches, we can still create these from there.

**Comment by Zimmi48** [comment]
> Shall I release this for the beta from my private fork instead, where I collect the patches as cherry picks?

Sounds good. Anyway, this is just the beta, so not a big deal if this is not a properly picked version. We can try to do better for the final release. (Maybe ask @xavierleroy to release a patch-level version of 3.7 with the right set of patches.)

**Comment by Zimmi48** [comment]
`mathcomp-1.11.0` has been released so this PR should be updated to use this tag.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : sorry I didn't see your comment. I would think any diff should do it. The name must be either gappa.patch or gappa-<hash>.patch.

**Comment by Zimmi48** [comment]
So the name of the files mentioned in the diff is not relevant?

**Comment by MSoegtropIMC** [comment]
The patch mechanisms strips away one folder level, so the top level folder names don't matter. What is below the top level folder must be the names relative to the top level folder of the git repo of the respective project.

**Comment by MSoegtropIMC** [comment]
Btw.: in the interest of a platform build it might make more sense to link your fork in ci-basic-overlay as I did for VST and CompCert. But if I do that, I document in ci-basic-overlay how this fork defers from the original source.

**Comment by Zimmi48** [comment]
Given how dirty the patch is, I'd rather not do that.

**Comment by MSoegtropIMC** [comment]
> Given how dirty the patch is, I'd rather not do that.

That I can't judge. You mean it is somehow dangerous?

**Comment by Zimmi48** [comment]
Not dangerous: but the code of Gappa is made to be compatible with several versions of Coq at once (using `ifdef`) and this patch breaks this property, so it couldn't be submitted to upstream as is.

**Comment by Zimmi48** [comment]
The proper way of doing it would be to add a new `ifdef` but I didn't bother enough.

**Comment by MSoegtropIMC** [comment]
> The proper way of doing it would be to add a new `ifdef` but I didn't bother enough.

And I guess it is not appreciated everywhere to introduce new uses of the V82 compatibility layer ...

**Comment by Zimmi48** [comment]
> And I guess it is not appreciated everywhere to introduce new uses of the V82 compatibility layer ...

It's not the perfect fix but certainly the less invasive, and I copied this fix from what @ppedrot (the author of this API change) did to funind.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : sorry I gave you a wrong filename. It should be `gappa_plugin.patch` or `gappa_plugin-gappalib-coq-1.4.3.patch`.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : shalll I qickly fix it on your branch?

**Comment by Zimmi48** [comment]
No I'm taking care of it.

**Comment by MSoegtropIMC** [comment]
OK, I meanwhile do a local test if your patch works for me

**Comment by Zimmi48** [comment]
The Gappa plugin has built correctly :tada:

**Comment by MSoegtropIMC** [comment]
> The Gappa plugin has built correctly 🎉

I did a local test and it did work fine. As soon as the installer is through, I will run a few tests on all plugins / libraries.

**Comment by Zimmi48** [comment]
Thanks. I'm posting the direct link to the build here because I might force-push before it is over. We are currently 85 minutes in, so it should be finished in about 3 hours.

https://gitlab.com/coq/coq/-/jobs/591578678

**Comment by gares** [comment]
I made a v8.12 branch for coq-elpi: https://github.com/LPCIC/coq-elpi/tree/coq-v8.12

**Comment by gares** [comment]
(update the ref at your convenience)

**Comment by Zimmi48** [comment]
> (update the ref at your convenience)

This will be after the beta, because I do not want to take any risk right now :smile:

**Review by MSoegtropIMC — COMMENTED** [review]
Since this contains changes from me I cannot approve it, but I wanted to state here that to me this looks good.

**Comment by ejgallego** [comment]
Will wait for windows build to finish, then merge.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I think there is one mistake I made: VST should now depend on CompCert, so that the installer also selects CompCert when VST is installed. But I think for a beta it is OK. One just has to check CompCert when one checks VST - traditionally one did do this anyway becaise most people using VST need clightgen. But now VST likely wouldn't work at all without selecting CompCert.

@ejgallego : please give me some time to test it. I guess it will be finished in less than 1 hour and then I will look at it.

**Comment by Zimmi48** [comment]
Yep, I think it is OK like this for a beta. The build is still ongoing but should be over in a dozen minutes or so.

**Comment by MSoegtropIMC** [comment]
> 
> 
> Yep, I think it is OK like this for a beta. The build is still ongoing but should be over in a dozen minutes or so.

Hmm you pushed again on hour ago. Usually the full Wundows build takes more like 3..4 hours.

**Comment by Zimmi48** [comment]
@MSoegtropIMC I gave you above the link to the build that was still running from before the push. It is here: https://gitlab.com/coq/coq/-/jobs/591578678
What I force-pushed is equivalent so no need to wait for its completion.

**Comment by MSoegtropIMC** [comment]
@gares : do you have a simple test case for Elpi I can run to see if everything is installed properly?

**Comment by Zimmi48** [comment]
There are some examples in the README of https://github.com/LPCIC/coq-elpi

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I did run my little test suite. Basically it seems to work, but I need to adjust my test cases for aac-tactics, quickchick and VST - my tests don't run through any more. For Elpi I picked randomly two of the examples and they work fine. I also need to Check Hierarchy builder and UniCoq.

**Review by ejgallego — APPROVED** [review]
Approving as per github constraints.

**Comment by gares** [comment]
Coq elpi is a plugin, all the files are morally tests. If make works then it is ok. The same for HB, 1 file is the program, all the rest is test.

**Comment by MSoegtropIMC** [comment]
@gares : yes I would say Elpi is fine. I will check HB around noon. Btw.: is there an elpi discussion forum on zulip - I couldn't find one. Should I just start a thread there with the questions I have?

**Comment by gares** [comment]
I don't have a coq-elpi specific stream. I'd say you post in coq user (or coq dev depending on the question) and then we will see.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I did a test of a few examples both on the command line and in CoqIDE for all addons and plugins delivered in the Windows Installer except for menhir and menhirlib. For compcert I tested just clightgen (in a cygwin console where gcc is installed since clightgen needs a preprocessor).

So from the Windows point of view the release is good to go :-)

**Comment by MSoegtropIMC** [comment]
P.S.: if you have a good way to pusblish my nini test suite ... the main issue is that the files have quite a variety of licenses. One option might be to pull them from the respective repositories.

**Comment by Zimmi48** [comment]
> So from the Windows point of view the release is good to go :-)

Except that no because the Windows 32 bit build is failing with an OOM on Elpi. See the discussion in the release thread on Zulip and the fix being currently tested at #12501.

**Comment by MSoegtropIMC** [comment]
> But you might also have some tests integrating several independent add-ons together?

Thats what I do in my day job ;-) But I think as a test it is not so convenient in case one has to debug it.

**Comment by Zimmi48** [comment]
It might still make sense as an additional test on top of all the project-specific tests.

**Comment by MSoegtropIMC** [comment]
> It might still make sense as an additional test on top of all the project-specific tests.

Indeed, especially since there are tricky dependencies like insisting that libraries are not copied. I see what I can do.

**Comment by Zimmi48** [comment]
FTR a new version of the Gappa plugin has already been released and the compatibility commit with 8.12 does the same thing as my patch, except it wraps it in the proper `#ifdef`.

**Comment by Zimmi48** [comment]
Cf. #12511

**Comment by Zimmi48** [comment]
> > @Janno: Should mtac2 get a new master-8.12 branch? The start point could be [Mtac2/Mtac2@62071fe](https://github.com/Mtac2/Mtac2/commit/62071fe).
> 
> Done! https://github.com/Mtac2/Mtac2/tree/master-8.12

This is actually a tag, not a branch. Is that normal? It looks like a branch name to me.

**Comment by Janno** [comment]
> This is actually a tag, not a branch. Is that normal? It looks like a branch name to me.

Well spotted. Thanks! It should be a branch now!

**Pull request merged**
