### PR TITLE
Add bmsherman/topology to the ci

### PR DESCRIPTION
**Pull request by JasonGross**
This development of @bmsherman tests universe polymorphism and setoid
rewriting in type, and should build with v8.6 and trunk.

(cc @ejgallego )

### CODE REVIEW

**Comment by JasonGross** [comment]
Hmm, maybe we should call it something other than topology, because topology is already the name of one of the coq contribs

**Comment by JasonGross** [comment]
Renamed to `formal-topology` at the suggestion of @bmsherman.

**Comment by ejgallego** [comment]
You forgot to edit `Makefile.ci` . Sorry for the non-optimal process, I hope we can streamline things soon.

**Comment by JasonGross** [comment]
Updated `Makefile.ci`

**Comment by Zimmi48** [comment]
Just a small question. Why not add formal-topology to the existing math-classes / corn target instead of making a new one ?
Maybe for clarity it could be renamed ci-math-classes-corn-topology.

**Comment by JasonGross** [comment]
Amended the commit to `chmod +x dev/ci/ci-formal-topology.sh`

@Zimmi48 I am fine with either, and want to know what @ejgallego thinks and suggests.

**Comment by ejgallego** [comment]
After some thought it makes sense to keep tests organized by upstream, thus I propose we keep this separate.

**Comment by JasonGross** [comment]
I forgot to change one of the `topology`s to `formal_topology`.  Fixed that, trying travis again.

**Comment by JasonGross** [comment]
Updated to `make install` CoRN, and to point at the branch `ci`, as per @bmsherman's request.

**Comment by maximedenes** [comment]
@ejgallego Does this now look good to you?

**Comment by ejgallego** [comment]
Looks good even if getting too close to the time limit. An additional nit is that all the CI are sorted by alphabetical order, but this doesn't hold anymore after the renaming, so please fix.

**Comment by JasonGross** [comment]
@ejgallego @maximedenes fixed

**Comment by maximedenes** [comment]
Let's merge this one. If unstable because too close to the time limit, we can still change our mind.

**Pull request merged**
