### PR TITLE
Pattern-matching with small inversion

### PR DESCRIPTION
**Pull request by thierry-martinez**
This is a *draft* pull-request for a new implementation of the pattern-matching elaboration, supporting deep pattern-matching with small inversion. Some tests in the test suite still have to be fixed.

This pull-request makes Coq able to compile pattern-matching like this:
```coq
Inductive vector (A : Type) : nat -> Type :=
| Nil : vector A O
| Cons n (_ : A) (_ : vector A n) : vector A (S n).

Fixpoint map2 A0 A1 B (n : nat) (f : A0 -> A1 -> B) (v0 : vector A0 n) (v1 : vector A1 n) : vector B n :=
  match v0, v1 with
  | Nil _, Nil _ => Nil _
  | Cons _ _ hd0 tl0, Cons _ _ hd1 tl1 =>
    Cons _ _ (f hd0 hd1) (map2 _ _ _ _ f tl0 tl1)
  end.
```

Fixes #5054, #16749.

### CODE REVIEW

**Comment by Alizter** [comment]
@thierry-martinez Very cool! Only just saw this. Are you planning to work on it further? What needs to be done?

**Comment by Zimmi48** [comment]
@herbelin No need for a dummy commit for CI, you can also ask coqbot to trigger it for you. See https://github.com/coq/coq/pull/16600#issuecomment-1270067377.

**Comment by herbelin** [comment]
For the record, related links: #13323 (documentation) as well as #5021, #4891 and #4989 (small inversion as a tactic).

**Comment by thierry-martinez** [comment]
I will push a rebase for this PR.

**Pull request closed without merging**
