### PR TITLE
Fix #8873: coqchk on inductive with letin parameter

### LINKED ISSUE #8873: validate fails on inductive type with letin parameter
Specifically on 
~~~coq
Inductive IND2 (A:Type) (T:=fun _ : Type->Type => A) := CONS2 : IND2 A -> IND2 (T IND2).
~~~

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by ppedrot — COMMENTED** [review]
Utterly incompetent on that change. Summoning @mattam82 and @maximedenes.

**Comment by SkySkimmer** [comment]
By the way, this looks like 7061f479eaf148779d216ad6779cf153076fb005 ported to the checker.

**Comment by herbelin** [comment]
> By the way, this looks like 7061f47 ported to the checker.

Indeed.

**Review by ppedrot — APPROVED** [review]
OK, it does look like a backport of the mentioned commit. So it is at least as wrong as the kernel. I am going to merge this except if some specialist of the inductive type-checking quickly shrieks in pain in this thread. @mattam82? @maximedenes?

**Pull request merged**
