### PR TITLE
[CI] FCSL-pcm now depends on MathComp 2

### PR DESCRIPTION
**Pull request by proux01**
Apparently it switched to MC2 a few days ago.
Since it was the last thing depending on MC1 in the CI, we can also get rid of MC1.

### CODE REVIEW

**Comment by proux01** [comment]
BTW @aleksnanevski thanks for the update! Just to avoid disruptions in the CI of Coq here next time, it's nice to coordinate with Coq devs. This PR should fix things anyway.

**Comment by proux01** [comment]
Well, this seems quite broken (@aleksnanevski is it expected?), let's mark it as allow failure so as to allow time for it to get fixed

**Comment by proux01** [comment]
@SkySkimmer I consider this ready (as a short term solution)

**Comment by aleksnanevski** [comment]
we haven't yet determined on which versions this works, aside from 18.9. this is why we haven't registered with opam yet. sasha gryzlov (@clayrat) planned on figuring this out soon. he should be in the conversation, but i'm not sure how to add him.

**Comment by proux01** [comment]
Ideally, nothing should have been pushed to the master branch until this is sorted out (on a specific branch). But well, now it's done, we'll mark it as allow failure here until you told us it's working again with Coq master.

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
@coqbot merge now

**Comment by proux01** [comment]
Here was the failing CI job https://gitlab.inria.fr/coq/coq/-/jobs/4722024 (Coq master and MathComp master)

**Comment by aleksnanevski** [comment]
I guess, one question is: which coq and mc2 you're using in CI? Is it the one I get from opam when I use the tag dev?

**Comment by proux01** [comment]
Yes, Coq should match coq.dev in the core-dev OPAM repo and mathcomp should match coq-mathcomp-*.dev in the extra-dev OPAM repo (you can do an `opam update` to ensure they are up to date)
If your problem seems specific to mathcomp, feel free to discuss it in more details in an issue there or simply on the dedicated zulip stream https://coq.zulipchat.com/#narrow/stream/237664-math-comp-users/

**Comment by proux01** [comment]
> Basically, I've been defining various properties of morphisms on partial commutative monoids (pcm), and I needed to show that function composition preserves these properties. For example, to declare that composition preserves fullness and binormality (it doesn't matter what these are now), this is the way I did that in 8.19/20:
> 
> HB.instance Definition _ (f : full_binorm_pcm_morph U V) (g : full_binorm_pcm_morph V W) := Full_Binorm_PCM_morphism.copy (g \o f) (Full_Binorm_PCM_morphism.pack_ (Binorm_PCM_morphism.class (g \o f)) (Norm_PCM_morphism.class (g \o f)) (Full_PCM_morphism.class (g \o f))).

Indeed, `.pack_` should not be used directly. Maybe
```Coq
HB.instance Definition _ (f : full_binorm_pcm_morph U V) (g : full_binorm_pcm_morph V W) := Full_Binorm_PCM_morphism.on (g \o f).
```
is enough since you seem to already have all the appropriate instances lying around?

> First, I have ported fcsl-pcm to the dev variants of everything. The port is in the branch coqdev_port of [git@github.com](mailto:git@github.com):imdea-software/fcsl-pcm.git. Do you have a way to send this to your CI so we can see if it works? If it does, then I suppose I should just merge that branch into master. Then I can prepare the release that's compatible with 8.19 and 8.20 in a separate branch (basically, take our current master and rename it, and register that with opam).

Sure, I (or you) can open a draft pull request here to remove the allow_failure and change the branch in dev/ci/ci-basic-overlay.sh
Maybe better to do so once the above point is fixed.

**Comment by aleksnanevski** [comment]
ok, just did it. let's see what the solution is.

**Pull request merged**
