### PR TITLE
Exporting sigT Notations, plus some theorems between (A * B) and {_ : A & B}

### PR DESCRIPTION
**Pull request by thery**
- [x] Added **changelog**.

### CODE REVIEW

**Review by herbelin — APPROVED** [review]
Good on my side. Don't know if it should be advertised more.

**Comment by olaure01** [comment]
@thery there is apparently a problem with an empty line in changelog.

**Comment by thery** [comment]
@olaure01  sorry with `md` and `rst` I am getting lost. I've tried something.

**Comment by Alizter** [comment]
We also use `(_;_)` for sigma pairs in the HoTT library, but I've always wondered what is obstructing the use of `(_,_)` for both prod and sigmaT? I know that the associativity of the notation is different, but is this the only pronlem?

**Comment by thery** [comment]
@Alizter seems the category is failing for another reason `File "./Lib/TList.v", line 14, characters 15-34:
Error: Unable to locate library Equations.Equations.`

**Comment by thery** [comment]
@Alizter  anyway if you also use the notation, we should sync then (associativity, and precedence). Where is it defined?

**Comment by thery** [comment]
@Alizter  sorry I've deleted your comment by mistake (I wanted to delete my responses that were not appropriate).
Yes @herbelin in  #14809 mentioned that it would be nice to have some kind of subtyping in this kind of situation.

**Comment by Alizter** [comment]
@thery no worries, let me ask again: is it possible to use the `(_, _) ` notation for both prod and sigma? If not what are the blockers? IIRC the notation for Sigma is left assoc whilst prod is right.

**Comment by thery** [comment]
@Alizter I am not an expert in notation but if I read [this](https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#reserving-notations) Coq seems to enforce that a notation has always the same associativity. Maybe @herbelin  is more expert than me in that matters.

**Comment by Alizter** [comment]
Yes, I suspected the reserved notation had something to do with it. I wonder if it is a historical accident that we have both products and sigma types rather than defining products as a special case of sigma.

Why for instance are product types right associative?

I guess these questions are for @herbelin

**Comment by herbelin** [comment]
> Yes, I suspected the reserved notation had something to do with it. I wonder if it is a historical accident that we have both products and sigma types rather than defining products as a special case of sigma.
> 
> Why for instance are product types right associative?

It is an historical accident that associativity of `and`/`or`/`exists` and `prod`/`sum` do not match. Changing it now would be quite complicated :(

However, the difference between product and sigma types is also motivated by the difference of underlying intuition and by the constraints of unification. For instance, I don't think that the type of pairs in sigma-types can be inferred in general without some context. So, just writing e.g. `Check (0,0)` would not lead to an inferable type if the pair were intended to be in a sigma type.

Nevertheless, I agree that that would be comfortable to be able to overload the notations for pairs and projections in prod and sigT.

While at it, there was the question at some time to provide an alternative syntax to `sigT` which can be iterated easily. The candidate was `sigma binders, typ` (following the model of `exists binders, typ`). Do you have an opinion?

In this case, we could even make the notation `( t ; u )` recursive (with associativity on the right...)

**Comment by olaure01** [comment]
But `/\` and `*` associate differently #7676

**Comment by herbelin** [comment]
An additional problem is that `*` is used both as an arithmetic operator (with the constraint coming from `/`) and as type combinator (which probably is a bad choice, that's another question). With a smarter system of notations, we could have different precedences of binary operators depending on the scope but the current constraint is that we need the same associativity. (Typically, to support associativity based on the interpretation, one would need the parser to simply return a list of expressions rather than an already associated binary tree of expressions.)

Regarding `/\`, one of the constraints is e.g. that nested `/\` have to support the `&` introduction patterns and the latter associates to the right. Again, we could make `&` associates differently depending on what it destructs but that's not the case currently.

So, nothing impossible to implement per se, though, even if we implement the infrastructure for a more flexible management of associativity, it is not so clear how to make a transition.

**Comment by Zimmi48** [comment]
>I wanted to delete my responses that were not appropriate

You should probably hide comments instead of deleting them, as this would avoid such mistakes.

**Comment by olaure01** [comment]
@herbelin 
> While at it, there was the question at some time to provide an alternative syntax to `sigT` which can be iterated easily. The candidate was `sigma binders, typ` (following the model of `exists binders, typ`). Do you have an opinion?
> 
> In this case, we could even make the notation `( t ; u )` recursive (with associativity on the right...)

Do you mean being able to write something like `{ x & P1 x & P2 x & P3 x & P4 x }` or  `{ x | Q1 x & Q2 x & Q3 x & Q4 x }`?
I would be very happy to have this.

**Comment by herbelin** [comment]
> @herbelin
> 
> > While at it, there was the question at some time to provide an alternative syntax to `sigT` which can be iterated easily. The candidate was `sigma binders, typ` (following the model of `exists binders, typ`). Do you have an opinion?
> > In this case, we could even make the notation `( t ; u )` recursive (with associativity on the right...)
> 
> Do you mean being able to write something like `{ x & P1 x & P2 x & P3 x & P4 x }` or `{ x | Q1 x & Q2 x & Q3 x & Q4 x }`?
> I would be very happy to have this.

Yes, this is what I mean.

If we only want the two variants that you're showing, I think it can already be done as follows:
```
Notation "{ x & P  & ..  & Q & R }" := (sigT (fun x => (P * .. (Q * R) ..)%type)).
Context (P1 P2 P3 P4 : nat -> Type).
Check { x & P1 x & P2 x & P3 x & P4 x }.

Notation "{ x | P  & ..  & Q & R }" := (sig (fun x => P /\ .. (Q /\ R) ..)).
Context (Q1 Q2 Q3 Q4 : nat -> Prop).
Check { x | Q1 x & Q2 x & Q3 x & Q4 x }.
```
If we'd potentially like several binders, that's more complicated, because of the required factorization with `{ A } + { B }`. Assuming a hack to manage the conflict is ever possible, the general form would be `{ x .. y & P .. Q }` with `x .. y` binders. Personally, I find the aesthetics e.g. of `{ (x y : nat)  (z u : bool) & P x y z u }` not so nice, due to the presence of both `{` and `(`, compared to a notation of the form, say `sigma (x y : nat)  (z u : bool), P x y z u`, but it has the advantage of compatibility and we could also get used to it... Then, we would have also `{ x .. y | P & .. & Q }` and the types `sig2` and `sigT2` could then be deprecated.

**Comment by olaure01** [comment]
Should we consider first merging the PR in its current state? It seems without problem while the other directions probably deserve more discussion/work.

**Comment by herbelin** [comment]
> Should we consider first merging the PR in its current state? It seems without problem while the other directions probably deserve more discussion/work.

A pending question is also whether it is worth going now to the generalization `Notation "( x ; .. ; y ; z )" := (existT _ x .. (existT _ y z) ..)` or if if is better to have a discussion about it too.

In any case, I'm ok with merging this one now (or the part of it which does not depend on #14809 if #14809 is finally merged after).

**Comment by Alizter** [comment]
What's going on with the ci?

**Comment by herbelin** [comment]
> What's going on with the ci?

Category Theory fails everywhere. Windows64 seems unrelated (and I saw it failing easily recently).

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
