### PR TITLE
Change ltac2 value representation to reuse ocaml values

### PR DESCRIPTION
**Pull request by SkySkimmer**
This is definitely more fragile but perhaps faster or less memory hungry.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Most packages don't use ltac2 AFAIK so only benching a few https://gitlab.com/coq/coq/-/jobs/3156072491

**Comment by ppedrot** [comment]
Very bad idea™. Due to functors, the type system of Ltac2 is unsound. In the current implementation you'll just get an anomaly if you break soundness, but with Obj.magic everywhere expect dragons to fly out your nose. We shouldn't expose to our end users a way to break the memory safety of the host language.

**Comment by DemiMarie** [comment]
> Very bad idea™. Due to functors, the type system of Ltac2 is unsound. In the current implementation you'll just get an anomaly if you break soundness, but with Obj.magic everywhere expect dragons to fly out your nose. We shouldn't expose to our end users a way to break the memory safety of the host language.

Time to fix the type system?

**Comment by ppedrot** [comment]
> Time to fix the type system?

Unfortunately, if that were so easy I'd have do it from the beginning. The problem is that the Coq module system is crazy implementationwise. Ltac2 is not the only victim of this fact, but it's the most flamboyant one because otherwise you can only get weird anomalies in severe corner-cases. To fix the issue we basically need to reimplement the module system of Coq from scratch.

**Comment by DemiMarie** [comment]
> we basically need to reimplement the module system of Coq from scratch.

Time to reimplement the module system in Coq (extracted to OCaml) and make Coq (partially) bootstrapped?  (Mostly, but not entirely, joking.)

**Comment by ppedrot** [comment]
@SkySkimmer I still stand my ground that I don't want this to reach mainstream usage.

**Pull request closed without merging**
