### PR TITLE
Remove library-specific code for `Import`.

### LINKED ISSUE #10474: `Export` in a module `foo` has effect in modules that do not import `foo`
The following example succeeds:

A.v
```coq
Require B.
Import B.
Check b.
```
B.v
```coq
Require C.
Import C.
```
C.v
```coq
Require D.
Export D.
```
D.v
```coq
Definition b := true.
```

Is this expected?

About `Export`, the manual says:

> When the module containing the command Export qualid is imported, qualid is imported as well.

but here, `A` does not import `C`.

### LINKED ISSUE #10480: `Export` sometimes has no effect
Consider the following example:

A.v
```coq
Require Import B.
Require Import C.
Eval compute in b.
```
B.v
```coq
Require Export D.
Definition b := true.
```
C.v
```coq
Require Export D.
```
D.v
```coq
Definition b := false.
```

In `A.v`, Coq incorrectly reports that `b` evaluates to `true`. That is, the `Require Import C` command did not have any effect.

Interestingly, merging the two `Require`s into `Require Import B C` fixes the problem.

This bug is fixed by #10476, but some libraries seem to rely on it.

### PR DESCRIPTION
**Pull request by maximedenes**
Libraries are now handled like other modules.

Fixes #10480, fixes #10474.

### CODE REVIEW

**Comment by maximedenes** [comment]
@ppedrot @SkySkimmer you mentioned that you attempted this patch before. Did it look like this?

**Comment by SkySkimmer** [comment]
I had less simplification for sure, beyond that I don't remember.

**Comment by maximedenes** [comment]
From the timings I observe, this "library optimization" was critical. I guess I'll need to reimplement it at the module level, and hopefully make it correct.

**Comment by maximedenes** [comment]
@gares it seems that elpi still does not compile with this branch, unfortunately

**Comment by maximedenes** [comment]
Oh, in fact it looks like a coqbot bug, the last time I relaunched the job it succeeded but the status was not updated. CC @Zimmi48

**Comment by Zimmi48** [comment]
> Oh, in fact it looks like a coqbot bug, the last time I relaunched the job it succeeded but the status was not updated. CC @Zimmi48

That was a transient problem due to the change in @coqbot status checks titles.

**Review by gares — APPROVED** [review]
Modulo bench on pendulum.

**Comment by maximedenes** [comment]
Benchmark running here: https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/771/console

**Comment by ppedrot** [comment]
@maximedenes We might try to mitigate the slowdown by reducing the number of libobject declarations, maybe? Or do you think it's related to something else?

**Comment by maximedenes** [comment]
> We might try to mitigate the slowdown by reducing the number of libobject declarations, maybe? Or do you think it's related to something else?

Which slowdown? In fact, this patch generalizes some optimizations, so I'm pretty sure it is making things faster. If you are comparing with master, it is of course unfair as precisely this fix is making `Import` have an effect when previously it was sometimes incorrectly dropped. Note that thanks to the optimizations, the observed "slowdown" is just slightly above 1% in the worst cases.

**Comment by maximedenes** [comment]
Btw, this pacth already reduces the number of libobject declarations (`Import` no longer declares an object, only `Export` does).

And I'm confident that on the longer term, having a more first class structure for libobjects would enable many more optimizations than the current bread-dead approach (store all the actions and replay them). This patch is a step towards this direction.

**Review by ppedrot — APPROVED** [review]
I wholeheartedly support this PR, but it breaking the backwards compatibility might be puzzling for end-users. It could probably be advertised more emphatically in the changelog, maybe?

**Comment by maximedenes** [comment]
> It could probably be advertised more emphatically in the changelog, maybe?

I did put an entry that I tried to make specific enough. Suggestions for improvement are welcome, though. What do you have in mind?

**Review by gares — APPROVED** [review]

**Comment by gares** [comment]
The changelog entry looks OK to me, so I merge.

It would be nice to say "if you get this problem, then fix your imports" but unfortunately anything can change if you randomly drop a libobject action, so I'm not so sure we can be more specific in the changelog.

**Comment by SkySkimmer** [comment]
When can we expect the SF overlay to be upstream?

**Comment by maximedenes** [comment]
> When can we expect the SF overlay to be upstream?

I don't know, what's the expected workflow @coq/ci-maintainers ?

**Comment by SkySkimmer** [comment]
This is the first overlay we've had on SF (AFAIR) so we haven't thought about it previously.

Note that if adding SF was proposed today it would probably be rejected, eg in our CI policy it says `Your development is publicly available in a git repository and we can easily
  send patches to you (e.g. through pull / merge requests).`

**Comment by maximedenes** [comment]
I will submit a PR since I have access to the SF repo, but indeed I was wondering how other Coq devs were expected to proceed.

**Comment by herbelin** [comment]
@maximedenes: to help migrating, I'm trying to see if a warning can be output everytime an `Export` is not done anymore but I must confess that I fail to find exactly where to put the warning. Line 1029 of `declaremods.ml` seems to be the main line causing a change, but the impact of the added `if export then` is indirect. Do you have an idea of where in the code I should add a warning exactly characterizing the change of semantics. Side condition: is the change of semantics only for libraries or also for modules?

Thanks in advance.

**Comment by Zimmi48** [comment]
This PR changed the output of `Print Libraries` without updating the documentation. Not a big deal, I will take care of preparing the fix.

**Pull request merged**
