### PR TITLE
Add alienclean target to remove compilation products with no source.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by mattam82 — APPROVED** [review]
I want it, the logic looks fine to me but I'm not the most expert on Makefile stuff

**Comment by ejgallego** [comment]
Is it correct to state that the patch makes `make clean` and `make IGNOREALIEN` slower ? [Excuse my terrible make fu]

**Comment by SkySkimmer** [comment]
I suppose there's a couple more calls to `find`, but since there's already several (existing ml, unsaved files, etc) I doubt it has a significant effect.

**Comment by SkySkimmer** [comment]
Feel free to bench though.

**Pull request merged**
