### PR TITLE
[stm] push functional API further

### PR DESCRIPTION
**Pull request by gares**
This API change makes the hooks receive the document, it is a followup of #1087

### CODE REVIEW

**Comment by gares** [comment]
I can hack around this in pidetop for 8.8, hence the milestone

**Comment by ejgallego** [comment]
I think what the doc is still a bit open [as state can many times be recovered so you can have doc + cache], but the VCS is in for sure.

**Review by ejgallego — APPROVED** [review]
Looks good to me; indeed maybe we should got farther in the types used; but for now this is OK.

**Comment by ejgallego** [comment]
Equations is broken by other reasons it seems, merging.

**Pull request merged**
