### PR TITLE
[lexer] Minor state cleanup.

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Comment by maximedenes** [comment]
Something odd happened, restarting the build.

**Review by SkySkimmer — APPROVED** [review]
Sure why not

**Comment by SkySkimmer** [comment]
Let's have a bench https://ci.inria.fr/coq/view/benchmarking/job/benchmark-part-of-the-branch/289/console

**Comment by SkySkimmer** [comment]
Bench done
```

┌──────────────────────────┬─────────────────────────┬─────────────────────────────────────┬───────────────────────────────────────┬─────────────────────────┬─────────────────┐
│                          │      user time [s]      │             CPU cycles              │           CPU instructions            │  max resident mem [KB]  │   mem faults    │
│                          │                         │                                     │                                       │                         │                 │
│             package_name │     NEW     OLD PDIFF   │           NEW           OLD PDIFF   │            NEW            OLD PDIFF   │     NEW     OLD PDIFF   │ NEW OLD PDIFF   │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-sf-lf │   15.11   15.36 -1.63 % │   41843613429   42059518501 -0.51 % │    57402654074    57562110464 -0.28 % │  423720  423424 +0.07 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-ssreflect │   39.69   39.69 +0.00 % │  109608822574  109383540480 +0.21 % │   135771326854   135778229151 -0.01 % │  480164  480128 +0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│ coq-mathcomp-real_closed │  168.24  168.08 +0.10 % │  467502484062  466958198933 +0.12 % │   716397604002   716315655169 +0.01 % │  729724  727560 +0.30 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-sf-plf │   41.71   41.67 +0.10 % │  116513654921  116117574845 +0.34 % │   151700717076   151802530715 -0.07 % │  510124  510160 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-color │  569.53  568.97 +0.10 % │ 1592170120525 1590113255353 +0.13 % │  2008683234032  2008253701614 +0.02 % │ 1487828 1487428 +0.03 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│               coq-geocoq │ 3086.51 3081.13 +0.17 % │ 8600335999081 8594462341966 +0.07 % │ 14319200984251 14323111809922 -0.03 % │ 1215808 1252132 -2.90 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-character │  266.73  266.24 +0.18 % │  741529603358  739737332003 +0.24 % │  1096069050921  1095974579790 +0.01 % │  982348  982552 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│       coq-mathcomp-field │  450.30  448.80 +0.33 % │ 1252535824988 1249819991629 +0.22 % │  2094851819188  2094860412046 -0.00 % │  731376  732040 -0.09 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                  coq-vst │ 2160.48 2151.36 +0.42 % │ 6023644343721 5996122489017 +0.46 % │  8802873209110  8802319746993 +0.01 % │ 1950056 1951352 -0.07 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-fingroup │   60.69   60.40 +0.48 % │  167182811415  166811690205 +0.22 % │   232648701031   232840460359 -0.08 % │  529612  531780 -0.41 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│    coq-mathcomp-solvable │  192.76  191.80 +0.50 % │  535537478034  533262084388 +0.43 % │   774395768612   774359997235 +0.00 % │  715496  715628 -0.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│         coq-fiat-parsers │  672.11  668.37 +0.56 % │ 1858617703853 1849016368711 +0.52 % │  3014962194174  3012663422830 +0.08 % │ 3517772 3513968 +0.11 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-unimath │ 1293.29 1286.07 +0.56 % │ 3607197367435 3588622321765 +0.52 % │  6223192522734  6224304079098 -0.02 % │ 1051956 1053796 -0.17 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│           coq-coquelicot │   74.84   74.40 +0.59 % │  205774553414  204986157246 +0.38 % │   256023766417   256229953087 -0.08 % │  659480  659108 +0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│     coq-mathcomp-algebra │  172.04  170.97 +0.63 % │  476464976195  474601862331 +0.39 % │   674478808955   674342922006 +0.02 % │  590412  590468 -0.01 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│             coq-compcert │  809.00  803.82 +0.64 % │ 2254879212323 2240124049267 +0.66 % │  3414896239658  3416350664495 -0.04 % │ 1389832 1389072 +0.05 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│            coq-fiat-core │  119.79  119.02 +0.65 % │  315088739764  313708876457 +0.44 % │   421006774510   419292780929 +0.41 % │  503056  502740 +0.06 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│   coq-mathcomp-odd_order │ 1387.54 1375.28 +0.89 % │ 3866689799911 3832564269067 +0.89 % │  6716419776994  6719307875646 -0.04 % │ 1122484 1115084 +0.66 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│                coq-flocq │   58.73   58.09 +1.10 % │  161201030895  160657828281 +0.34 % │   206981746402   207232312026 -0.12 % │  645064  651684 -1.02 % │   0   0  +nan % │
├──────────────────────────┼─────────────────────────┼─────────────────────────────────────┼───────────────────────────────────────┼─────────────────────────┼─────────────────┤
│              coq-bignums │   76.34   75.30 +1.38 % │  211811642905  209717705055 +1.00 % │   287737697289   287554444780 +0.06 % │  530868  530784 +0.02 % │   0   0  +nan % │
└──────────────────────────┴─────────────────────────┴─────────────────────────────────────┴───────────────────────────────────────┴─────────────────────────┴─────────────────┘


```

**Comment by maximedenes** [comment]
Do we consider that to be noise?

**Comment by ppedrot** [comment]
It's hard to tell, it might well be the case that overallocating in the lexer has observable consequences. That said, the difference seems small enough that I wouldn't personally bother merging this PR, considering the cleaning it provides.

**Comment by ejgallego** [comment]
I will rerun the bench, I don't like these numbers TBH.

**Comment by ejgallego** [comment]
So indeed maybe the cleaning should be deeper so we get more benefits.

**Review by maximedenes — APPROVED** [review]
Having all the lexer state in one place seems good, on the other hand, it may allocate more. So no opposition, but we need to see if we are ready to pay the cost (timings suggest it is small, but still).

**Comment by maximedenes** [comment]
I'll mark this PR as `needs: progress` until @ejgallego decides what he wants to do.

**Review by herbelin — COMMENTED** [review]
Whatever is decided for this PR, I'm ok with the changes. If you want me to be the "assignee", I can do it.

**Comment by ppedrot** [comment]
@ejgallego I'd be in favour of merging this PR quickly and then we'll see for further cleanups. WDYT?

**Comment by ejgallego** [comment]
Quieto ahí no me cierres los PR XD

Seriously, this needs a pass or another bench, I was not happy with the observed perf impact. The problem is that this is so looow priority.

**Comment by ppedrot** [comment]
@ejgallego If you rebase it I can rerun a bench.

**Comment by ejgallego** [comment]
> @ejgallego If you rebase it I can rerun a bench.

I'll rebase but I'm afraid I need to find 5 mins to tweak a couple of things. It is in my todo list, I have not so many pending PRs these days.

**Comment by ejgallego** [comment]
Yeah I guess lexer functionalization needs more work and it will be some other person the one who does it.

**Pull request closed without merging**
