### PR TITLE
[travis] CoqIde + doc + last available LST

### PR DESCRIPTION
**Pull request by strub**
I tried to integrate all the comments of #418.

### CODE REVIEW

**Comment by ejgallego** [comment]
Cool, thanks. @strub, you are missing a few packages for the docs, see https://github.com/ejgallego/coq/commit/1afe5cd0b0030498915f0c19056b9b4680578521 In particular:
that is the right incantation:
texlive-latex-base texlive-latex-extra texlive-math-extra texlive-fonts-recommended transfig imagemagick

**Comment by ejgallego** [comment]
Ok test build at https://travis-ci.org/ejgallego/coq/builds/198313417

**Comment by ejgallego** [comment]
I think we should also use `-j 2` for all `make` invocations. Test build at https://travis-ci.org/ejgallego/coq/builds/198318682

**Comment by strub** [comment]
@ejgallego, sure. I'm currently testing the cache and will push this in that PR.

**Comment by ejgallego** [comment]
Cool thanks, my current branch with the experiments is here: https://github.com/ejgallego/coq/tree/travis-2

We may want to move the `-j 2` to the env section and use a `NJOBS` variable, currently container-based solutions ship 2 cores (I've read).

**Comment by ejgallego** [comment]
Maybe I got unlucky, but with the new container-based setup (`sudo = false`), I get much slower build times. Example:

- 148.56s: opam init --compiler=4.02.3 -y -v 148.56s
- 340.39s: [ -e .opam ] || opam init --compiler=4.02.3 -y 

I'm afraid with this performance, the build will timeout :S

**Comment by strub** [comment]
Yes, I noticed the same problem. We should continue using a non-container-based solution.

**Comment by ejgallego** [comment]
I understand travis folks are interested in cases where the container builds are slower, I'll let them know. 

Containers are supposed to have 2 reals cores vs 1.5 in the VM, so comparing could be worth.

**Comment by ejgallego** [comment]
Pffff, `-j 2` is slower than `-j 1`, so much for "containers have 2 cores". Also, note than the container system installs less latex packages for some reason so I had to tweak again the latex includes... waiting for the build.

**Comment by ejgallego** [comment]
LGTM, thanks!

Regarding the build matrix I would personally have a matrix of size 2 with Ocaml 4.04.0 too.
I am unsure whether the `campl4` build should be added to the matrix, it seems that there are some issues with the test suite?

**Comment by ejgallego** [comment]
FTR, `NJOBS=2` improved build time 3 minutes.

**Comment by ejgallego** [comment]
Hi folks, here are some further refinements (may submit after @strub  PR is taken) https://github.com/ejgallego/coq/tree/travis-2

Basically I've enabled parallel builds; with a bit more optimization we can have close to 40 minutes for each contribution.

**Comment by ejgallego** [comment]
This is how the builds look like: https://travis-ci.org/ejgallego/coq/builds/198407766

**Comment by maximedenes** [comment]
Is this ready for merge? I'd like to merge other PRs today and an automated testing infrastructure would make it smoother. So if ready, I'd merge this one right now (and #421 as well).

**Comment by strub** [comment]
Yes, it is.

Le lun. 6 févr. 2017 à 09:06, Maxime Dénès <notifications@github.com> a
écrit :

**Pull request merged**
