### PR TITLE
Make "Found no matching notation to enable or disable." a warning

### PR DESCRIPTION
**Pull request by proux01**
instead of an error

- [x] Added / updated **test-suite**.

- [ ] Added **changelog**.
- [x] Added / updated **documentation**.
  
  - [x] Documented any new / changed **user messages**.
  - [ ] ~Updated **documented syntax** by running `make doc_gram_rsts`.~

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by herbelin** [comment]
No, my comment is wrong. Let me think again.

**Comment by herbelin** [comment]
I updated my comment. I would simply ignore the absence of a notation when deactivation comes from an `Import`.

Here is another variant of the Zulip example, showing a desynchronisation of imports:
```
(* comp.v *)
Definition comp {A B C} (f : B -> C) (g: A -> B) : A -> C := 
    fun a => f (g a).

Notation " g '\o' f " := (comp g f) (at level 40, left associativity).
Check ((@id nat) \o (@id nat)).
```

```
(* comp_utf.v *)
Require Import NotationTest.comp.

Disable Notation "\o".

Notation " g '∘' f " := (comp g f) (at level 40, left associativity).
```

```
(* comp_utf2.v *)
Require Import NotationTest.comp_utf.

Enable Notation "\o".
```
and 

```
(* user.v*)
Require Import comp.
Require comp_utf.
Locate "\o". (* Notation " g '\o' f " := (comp g f) (default interpretation) *)
Require Import comp_utf2. (* Error: Found no matching notation to enable or disable *)
```

**Comment by herbelin** [comment]
It brings something so I'm leaning towards merging.

**Review by herbelin — APPROVED** [review]
More convenient than an error.

**Comment by herbelin** [comment]
@coqbot merge now

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@herbelin unimath failure is unrelated (c.f. https://github.com/coq/coq/pull/18726 )

**Comment by herbelin** [comment]
OK

@coqbot merge now

**Pull request merged**
