### PR TITLE
[vernac] Improve alpha-renaming in record projection types

### LINKED ISSUE #13727: Avoid alpha-renaming in projection types
#### Description of the problem

In a `Record` declaration, the first letter of the record is used as a variable name for such a record in the type of a projection, which may collide with other variables in the field type.

```coq
Record Adjunction :=
  { unit : forall {a}, a }.

About unit.
```

We get

```
Adunction -> forall a0, a0   (* i.e.,   forall (a : Adjunction), forall a0, a0 *)
```

instead of

```
Adjunction -> forall a, a
```

There is apparently no way to get that latter result other than painfully renaming each projection with `Arguments`.

Proposal: rename the record instead, so we get `unit : forall (a0 : Adjunction), forall a, a`. This is backwards compatible in the sense that if anyone somehow wanted the current behavior, they could just alpha rename their fields, avoiding the name collision while getting the same result.

Another idea would be to explicitly specify the new variable name via an annotation, but it's more syntactic noise.

#### Coq Version

Tested on Coq 8.12

### PR DESCRIPTION
**Pull request by Lysxia**
**Kind:** feature

Closes #13727 

- [x] Added / updated test-suite
- [x] Corresponding documentation was added / updated (including any warning and error messages added / removed / modified).
- [x] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

Overlay: https://github.com/AbsInt/CompCert/pull/388

### CODE REVIEW

**Comment by Lysxia** [comment]
Is there a better way of doing this?

**Comment by SkySkimmer** [comment]
The compcert error is because of something like
~~~coq
Record nlalal := {
  x:nat;
  f : forall n:nat, n=x -> True
}.

Goal True.
  apply f with (n0:=0).
~~~

**Review by SkySkimmer — APPROVED** [review]
I'll wait for the overlay to be merged upstream before merging this.

**Comment by SkySkimmer** [comment]
@coqbot: merge now

**Pull request merged**
