### PR TITLE
Do not call 'auto with *' in (d) intuition but 'auto' instead.

### PR DESCRIPTION
**Pull request by ppedrot**
This is a kamikaze PR. Fire in the hole!

Fixes #4949.

### CODE REVIEW

**Comment by ppedrot** [comment]
@SkySkimmer nope, I am not that stupid!

**Comment by ppedrot** [comment]
Let's close this and ponder about a proper fix...

**Comment by JasonGross** [comment]
I think the proper fix involves adding a variant of `info_(e)auto` which names the databases the hints are pulled from, and then doing exactly what this PR does, but also adding a thing in `Coq.Compat.Coq88` which defines `intuition` to be `intuition info_with_db_info_auto with *`, so that it is quite easy to pull the relevant databases needed from the output of the tactic.

**Comment by JasonGross** [comment]
If you set things up right, and manage to get it to spit out location information, it might even be possible to write an automated translation tool which first compiles with `-compat 8.8`, aggregates the databases for each location across all files in the project, and then updates the calls to `intuition` which mention more than `core` to `intuition auto with ...`.

**Pull request closed without merging**
