### PR TITLE
CI Quickchick: don't install quickchick executable to opam

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ejgallego** [comment]
@coqbot: merge now

**Review by ejgallego — APPROVED** [review]

**Comment by ejgallego** [comment]
@coqbot: merge now

**Comment by liyishuai** [comment]
Is there a specific reason for this? I wanted to add `make tests` to the CI script, which depends on `make install`. Is there a PATH in the CI for installing executables?

**Comment by SkySkimmer** [comment]
There's `$CI_INSTALL_DIR/bin`

**Pull request merged**
