### PR TITLE
[funind] [cleanup] Remove unused function parameters

### PR DESCRIPTION
**Pull request by ejgallego**
Very minor cleanup sitting on my HD.

### CODE REVIEW

**Comment by ejgallego** [comment]
Ping @Matafou @forestjulien , CI failure is spurious.

**Review by Matafou — APPROVED** [review]
This seems innocuous.

**Comment by ejgallego** [comment]
Needs someone to merge.

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
*En avant Guingamp.*

**Pull request merged**
