### PR TITLE
elpi 1.8

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by gares** [comment]
I plan to "backport" this to v8.11

**Review by SkySkimmer — APPROVED** [review]

**Comment by SkySkimmer** [comment]
Running https://gitlab.com/coq/coq/pipelines/93773494 with no docker_skip

**Comment by gares** [comment]
thanks!

**Review by ejgallego — APPROVED** [review]
Please improve the commit descriptions in the future; it makes the shortlog very hard to read.

**Pull request merged**
