### PR TITLE
Control the transparency of compatibility constants via their projections.

### PR DESCRIPTION
**Pull request by rlepigre**
This is roughly the first part of https://github.com/coq/coq/pull/18327.

- [ ] Added **changelog**.
- [ ] Added / updated **documentation**.
- [ ] Updated **documented syntax** by running `make doc_gram_rsts`.
- [ ] Opened **overlay** pull requests.

### CODE REVIEW

**Comment by herbelin** [comment]
The failure of bug_17774.v is easy to fix, isn't?

**Comment by rlepigre** [comment]
> The failure of bug_17774.v is easy to fix, isn't?

Probably, I did not yet had the time to look into this.

**Comment by herbelin** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
@coqbot run full ci

**Comment by Janno** [comment]
@coqbot run full ci

**Comment by rlepigre** [comment]
Closing since this is part of #18327.

**Comment by herbelin** [comment]
Maybe this PR would still be merged quicklier if kept independent from #18327.

**Comment by rlepigre** [comment]
> Maybe this PR would still be merged quicklier if kept independent from #18327.

Possibly, but that would require to move the overlays here, and the other MR will hopefully be ready in the next few days (we were only stuck because the whole CI setup was broken).

**Comment by herbelin** [comment]
> Possibly, but that would require to move the overlays here, and the other MR will hopefully be ready in the next few days (we were only stuck because the whole CI setup was broken).

I see. Another argument I can give otherwise is that reviewing the current PR would be easier than reviewing it together with #18327 (assuming that I correctly understand that it changes the infrastructure but a priori not the observational semantics).

**Comment by rlepigre** [comment]
> I see. Another argument I can give otherwise is that reviewing the current PR would be easier than reviewing it together with #18327 (assuming that I correctly understand that it changes the infrastructure but a priori not the observational semantics).

I understand, but given that #18327 adds very little on top of this PR, and that it can still be easily reviewed by commit (with changes from this PR coming first), I don't think it is worth the extra effort to maintain two different PRs. But of course, if reviewing turns out to be too difficult, we can come back to taking two independent steps later.

**Pull request closed without merging**
