### PR TITLE
Fixes #12787: anomaly of tactic injection in the presence of artificial dependencies disappearing by reduction

### LINKED ISSUE #12787: Injection raises “Anomaly "File "tactics/equality.ml", line 1316, characters 2-8: Assertion failed."”
#### Description of the problem

```coq
Inductive sigT3 {A: Type} {P: A -> Type} (Q: forall a: A, P a -> Type) :=
  existT3: forall a: A, forall b: P a, Q a b -> sigT3 Q
.

Definition projT3_1 {A: Type} {P: A -> Type} {Q: forall a: A, P a -> Type} (a: sigT3 Q) :=
  let 'existT3 _ x0 _ _ := a in x0.

Definition projT3_2 {A: Type} {P: A -> Type} {Q: forall a: A, P a -> Type} (a: sigT3 Q) : P (projT3_1 a) :=
  let 'existT3 _ x0 x1 _ := a in x1.



Lemma projT3_3_eq' (A B: Type) (Q: B -> Type) (a b: sigT3 (fun (_: A) b => Q b)) (H: a = b) :
  unit.
  
  destruct a as [x0 x1 x2], b as [y0 y1 y2].
  assert (H' := f_equal projT3_1 H).
  cbn in H'.
  subst x0.
  assert (H' := f_equal (projT3_2 (P := fun _ => B)) H).
  cbn in H'.
  subst x1.

  inversion H. (* both raise the same anomaly *)
  injection H.
Admitted.
```

#### Coq Version

```
The Coq Proof Assistant, version 8.11.2 (June 2020)
compiled on Jun 15 2020 9:11:00 with OCaml 4.10.0
```

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

The fix is to use the same reduction strategy (namely `simpl`) to reduce K-redexes the same in the both places which compute the dependencies of a dependent equality (namely `make_tuple` and `minimal_free_rels`).

Fixes / closes #12787

- [X] Added / updated test-suite
- [X] Entry added in the changelog (see https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog for details).

### CODE REVIEW

**Comment by herbelin** [comment]
> ppedrot added the needs: benchmarking label 9 days ago

I need help to launch a benchmarking... Note that we shall observe probably nothing because the added `simpl` is only when `injection` produces a dependent pair and this is presumably very rare.

**Comment by ppedrot** [comment]
@herbelin see https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Bench.3F for a howto.

**Comment by herbelin** [comment]
> see https://coq.zulipchat.com/#narrow/stream/237656-Coq-devs.20.26.20plugin.20devs/topic/Bench.3F for a howto.

A bit tricky to launch at the moment but an interesting new approach!

**Comment by ppedrot** [comment]
@herbelin I think that the bench is wrong since it's testing a merge of this PR over master (609152467f4d717713b7ea700f5155fc9f341cd7) against an old master (ef08abec26c2f0017d1136870f8f99144e579538). Thus you're witnessing the speedups of the hint-related functions in this bench.

**Comment by ppedrot** [comment]
I've cancelled the bench, I believe you have to rebase to get a proper timing.

**Comment by herbelin** [comment]
OK, made in sync with current master.

**Review by ppedrot — APPROVED** [review]
Code change is fine, waiting for the bench.

**Comment by ppedrot** [comment]
Bench within noise range:
```
┌─────────────────────────────┬─────────────────────────┬─────────────────────────────────────────────┬─────────────────────────────────────────────┬────────────────────────────────┬───────────────────┐
│                             │      user time [s]      │                 CPU cycles                  │              CPU instructions               │     max resident mem [KB]      │    mem faults     │
│                             │                         │                                             │                                             │                                │                   │
│                package_name │     NEW     OLD PDIFF   │               NEW               OLD PDIFF   │               NEW               OLD PDIFF   │        NEW        OLD  PDIFF   │  NEW  OLD PDIFF   │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-coquelicot │   72.89   73.58 -0.94 % │      200164544202      201069439610 -0.45 % │      260939943034      260905182458 +0.01 % │     582528     582328  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│ coq-rewriter-perf-SuperFast │ 1043.82 1051.47 -0.73 % │     2905437464888     2925381771400 -0.68 % │     4589323727211     4591990982133 -0.06 % │    1070756    1070692  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-fingroup │   49.39   49.59 -0.40 % │      136584858287      137038396128 -0.33 % │      189387278000      189301130677 +0.05 % │     484652     484872  -0.05 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│              coq-verdi-raft │ 1268.91 1274.04 -0.40 % │     3533450635301     3547968751445 -0.41 % │     4948773812974     4948700558384 +0.00 % │     922776     922796  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-coqutil │   60.03   60.24 -0.35 % │      167127022547      167195990616 -0.04 % │      210754970478      210777113613 -0.01 % │     533844     533788  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-bedrock2 │  224.00  224.75 -0.33 % │      620621139594      622374717497 -0.28 % │     1027629915184     1027651978667 -0.00 % │    1087104    1087352  -0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-color │  678.18  680.41 -0.33 % │     1892322746782     1896614736852 -0.23 % │     2423803700887     2423724714936 +0.00 % │    1510880    1510840  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                         coq │  563.48  565.06 -0.28 % │     1575675821589     1581105141361 -0.34 % │     2157660473382     2157611014001 +0.00 % │     592876     592948  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-character │  162.83  163.26 -0.26 % │      452677261133      453691460796 -0.22 % │      627549430242      627529316117 +0.00 % │     716224     716184  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-coqprime │   84.93   85.15 -0.26 % │      233240774780      233512803038 -0.12 % │      330121991609      330124201195 -0.00 % │     766288     769508  -0.42 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│          coq-mathcomp-field │  294.32  294.95 -0.21 % │      820005252024      822232113874 -0.27 % │     1262338642211     1262348990757 -0.00 % │     823268     824816  -0.19 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│        coq-mathcomp-algebra │  142.38  142.68 -0.21 % │      395765719915      396793275799 -0.26 % │      514961804799      514904899855 +0.01 % │     561588     561252  +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-fiat-crypto │ 5187.48 5196.83 -0.18 % │    14408844142679    14432922328579 -0.17 % │    24670603471160    24673508728796 -0.01 % │    2418252    2432660  -0.59 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-odd-order │ 1083.08 1084.94 -0.17 % │     3016479420569     3021304801474 -0.16 % │     4795239177400     4795246189846 -0.00 % │    1019936    1019904  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-unimath │ 4076.42 4083.07 -0.16 % │    11340857370854    11359421414831 -0.16 % │    21546453844760    21548237846787 -0.01 % │    1111336    1010268 +10.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-rewriter │  622.77  623.74 -0.16 % │     1729614788777     1730604969066 -0.06 % │     2645085271504     2645100606302 -0.00 % │    1036112    1036228  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│             coq-lambda-rust │ 1401.74 1403.63 -0.13 % │     3903172962819     3908210623973 -0.13 % │     5542833815362     5542626145471 +0.00 % │    1188332    1179548  +0.74 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-flocq │  170.74  170.96 -0.13 % │      474050384564      473514201199 +0.11 % │      596282799978      596320135090 -0.01 % │     822424     822524  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-fiat-parsers │  657.42  658.24 -0.12 % │     1840138696457     1842456029544 -0.13 % │     2778502416122     2778473506515 +0.00 % │    3001332    3001312  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                   coq-verdi │  121.50  121.57 -0.06 % │      335347002100      336286856133 -0.28 % │      417760581891      417793728962 -0.01 % │     571992     572032  -0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-engine-bench │ 1255.63 1256.32 -0.05 % │     3518520396726     3521576181950 -0.09 % │     6065981173765     6057237271656 +0.14 % │    3995124    3994860  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                 coq-bignums │   58.84   58.87 -0.05 % │      163003055992      163359090311 -0.22 % │      220597226744      220584849809 +0.01 % │     474444     474300  +0.03 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-mathcomp-solvable │  174.75  174.83 -0.05 % │      486241092786      487550434056 -0.27 % │      686595076410      686604312540 -0.00 % │     683596     683620  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fourcolor │ 2510.49 2511.17 -0.03 % │     6999328039048     6992172425920 +0.10 % │    11461263685330    11461225119983 +0.00 % │     764232     764204  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                coq-compcert │  686.06  686.12 -0.01 % │     1910373855229     1912229889096 -0.10 % │     2652285297245     2652190168604 +0.00 % │    1131104    1131064  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-corn │ 1725.17 1724.34 +0.05 % │     4799555330047     4800885368054 -0.03 % │     7303448793065     7303327243267 +0.00 % │     758008     758012  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-geocoq │ 1488.20 1486.99 +0.08 % │     4145215813587     4149458823514 -0.10 % │     6300812455718     6300791787557 +0.00 % │    1115308    1115200  +0.01 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│            coq-math-classes │  199.50  199.29 +0.11 % │      555946839757      557518739093 -0.28 % │      734476333467      734436671350 +0.01 % │     505968     505652  +0.06 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│               coq-fiat-core │  108.86  108.55 +0.29 % │      308919661788      309621705387 -0.23 % │      412121749890      412055578790 +0.02 % │     484772     484948  -0.04 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│       coq-performance-tests │ 2786.52 2778.48 +0.29 % │     7764744627920     7741279389995 +0.30 % │    14754415942327    14756552542055 -0.01 % │    4316400    4316252  +0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│      coq-mathcomp-ssreflect │   52.11   51.91 +0.39 % │      142616783023      142601440930 +0.01 % │      184822462703      184814743580 +0.00 % │     518912     518804  +0.02 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                    coq-hott │  338.32  336.83 +0.44 % │      914955675953      914666476594 +0.03 % │     1477797385922     1477420889691 +0.03 % │     657816     657820  -0.00 % │    0    0  +nan % │
├─────────────────────────────┼─────────────────────────┼─────────────────────────────────────────────┼─────────────────────────────────────────────┼────────────────────────────────┼───────────────────┤
│                  coq-sf-plf │   44.50   44.17 +0.75 % │      123175734013      123180222229 -0.00 % │      168961092894      168945163285 +0.01 % │     496408     496432  -0.00 % │    0    0  +nan % │
└─────────────────────────────┴─────────────────────────┴─────────────────────────────────────────────┴─────────────────────────────────────────────┴────────────────────────────────┴───────────────────┘
```

Let's merge!

**Comment by Zimmi48** [comment]
@ppedrot Was it intended that the code for the benchmarking job would be added as part of this PR? I guess not but also that such a thing was bound to happen eventually.

**Comment by ppedrot** [comment]
Woops... Usually I am the one benching in draft mode, and I remove the commit before undrafting.

**Comment by Zimmi48** [comment]
FTR I've prepared a backport for this PR without the last commit.

**Pull request merged**
