### PR TITLE
Fix anomaly when doing [all:Check _.] during a proof.

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by gares** [comment]
My code was assuming `VernacError` was never used, but `all:Check _` is parsed as such?
I see you remove an `assert false` and replace it with a reasonable value, but I still don't get why we reach that branch.  Did you dig it?

**Comment by gares** [comment]
I mean the patch is clearly safe, but I'm puzzled ;-)

**Comment by SkySkimmer** [comment]
It's produced here https://github.com/coq/coq/blob/trunk/parsing/g_vernac.ml4#L111

**Comment by aspiwack** [comment]
That's on me I'm afraid. Doesn't it make sense?

**Comment by maximedenes** [comment]
Shouldn't this fix be applied on 8.6?

**Comment by SkySkimmer** [comment]
@maximedenes it is now.

**Comment by gares** [comment]
Hem, @maximedenes  my question was:
- what the hell `VernacError` means? If you need a vernacular command that fails to test `Fail` I have others in mind
- why a concrete syntax that is not `Error ...` is parser as VernacError? A parser can simply fail, isn't it?

**Comment by silene** [comment]
> A parser can simply fail, isn't it?

I share Enrico's concern. I would like to understand why this parsing error is so special that it needs its very own dedicated error machinery. If it is just to work around a camlp5 bug, I would much prefer that just a warning saying that "all: is ignored before query commands" be displayed.

**Comment by maximedenes** [comment]
@gares Sorry, I thought "the patch is clearly safe" meant that we can merge it and understand more afterwards.

**Comment by SkySkimmer** [comment]
@maximedenes Is this going into trunk as well?

**Pull request merged**
