### PR TITLE
[test] Upgrade base OCaml to 4.08.1

### PR DESCRIPTION
**Pull request by ejgallego**
Stronger linking restrictions were introduced in OCaml 4.08, I'd like
to have a look at what the impact is over the CI.

### CODE REVIEW

**Comment by ejgallego** [comment]
Effectively at least mtac2 does fail with:
```
Error:
 Dynlink error: The module `Int_misc' is already loaded (either by the main program or a previously-dynlinked library)
```
will report a bug for coq_makefile in time.

Also, the 32bit suite failure is quite suspicious, due to native ints again.

**Comment by proux01** [comment]
> Also, the 32bit suite failure is quite suspicious, due to native ints again.

Hopefully, this is fixed by #11805

**Comment by ejgallego** [comment]
Thanks @proux01 , PR rebased on top of your fix.

**Comment by ejgallego** [comment]
I will close this PR and turn this into an issue once I have minute; the issue seems quite serious to me; Dune + findlib provide a fix; but even with that is still a lot of work.

**Comment by ejgallego** [comment]
Issue in #12067

**Pull request closed without merging**
