### PR TITLE
Fix dependent evars line with defined evars

### LINKED ISSUE #18980: commit 5c94d0d375 breaks dependent evar line
### Description of the problem

Commit 5c94d0d375 (Drop evar_concl from defined evars.) has the effect that the dependent evar line does not contain all existential variables any more. This breaks prooftrees functionality to track the status of existential variables.

The dependent evar line was reintroduced in PR #10489 as a response to feature request #10420.

In Coq before commit 5c94d0d375 the small Coq sample add below prints `(dependent evars: ?X10:?n; in current goal:)`. After this commit one gets `(dependent evars: ; in current goal:)`, which is wrong (at least with respect to feature request #10420), because `?n` is still an open existential at that point, even though it does not appear in the current goal any more.

### Small Coq file to reproduce the bug

```coq
Set Printing Dependent Evars Line.
Lemma x : (exists(n : nat), n = 5 \/ True) /\ (exists(m : nat), m = 6 \/ True).
Proof using.
  split.
    eexists.
    right.
```

### Version of Coq where this bug occurs

8.18.0, 8.19, everything after 5c94d0d375

### Last version of Coq where the bug did not occur

8.17.1, everything before 5c94d0d375

### PR DESCRIPTION
**Pull request by SkySkimmer**
Not sure how much we care about this feature but as long as it's an easy fix we may as well.

Fix #18980

### CODE REVIEW

**Comment by ppedrot** [comment]
I've been convinced for a while that this feature is an explicit breakage of invariants of the proof engine. Since the fix is local I agree with @SkySkimmer that it's fine to merge it, but future changes to the engine (e.g. a proper GC for the evar map) will likely break it again, and for good. I'd advise the maintainers of the UI relying on this to seriously start thinking about another approach.

**Review by ppedrot — APPROVED** [review]

**Comment by hendriktews** [comment]
Thanks for working on this! The current version of the PR works on the example in #18980, however, it does not fix all problems with the dependent evar line, see #18980 for another example.

**Comment by hendriktews** [comment]
@ppedrot : I opened #19001 in order to discuss alternatives of the dependent evar line.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
