### PR TITLE
coqchk respects sharing flag per-definition

### LINKED ISSUE #7086: No way to deactivate sharing in the checker
As mentioned in #7085, there is no way to selectively deactivate the sharing feature of the conversion algorithm. This probably prevents the checker from working on developments that critically rely on that feature like e.g. unimath.

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #7086

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]
Brace for CI!

**Comment by Alizter** [comment]
Worth adding a test? There is a way to test coqchk in the test-suite right?

**Comment by SkySkimmer** [comment]
We can test coqchk but the only impact of this should be perf, and testing coqchk perf is not easy.

**Comment by ppedrot** [comment]
There is probably a way to craft an example that overflow the stack in one case and not the other, but it's a bit hackish.

**Comment by ppedrot** [comment]
@SkySkimmer can you add a changelog entry? This can be quite visible a change.

**Comment by ppedrot** [comment]
Merging very soon.

**Comment by silene** [comment]
That does not seem like a good fit for 8.14.1.

**Pull request merged**
