### PR TITLE
Add TLC library to CI.

### PR DESCRIPTION
**Pull request by Zimmi48**
**Kind:** infrastructure.

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Thanks @Zimmi48 , note however that `gitlab.inria.fr` does not meet our CI policy w.r.t. upstream hosting.

We may grandfather this for a while but this is in conflict with my ongoing Coq universe tool that requires for open hosting platforms so it can submit Pull Requests.

**Comment by SkySkimmer** [comment]
I actually get 404 when I go to https://gitlab.inria.fr/tlc/tlc after login, this is pretty bad

**Comment by SkySkimmer** [comment]
Also we don't test tlc at all AFAICT
git grep tlc:
~~~
Makefile.ci:    ci-tlc \
dev/ci/ci-basic-overlay.sh:: "${tlc_CI_REF:=master}"
dev/ci/ci-basic-overlay.sh:: "${tlc_CI_GITURL:=https://gforge.inria.fr/git/tlc/tlc}"
dev/ci/ci-tlc.sh:git_download tlc
dev/ci/ci-tlc.sh:( cd "${CI_BUILD_DIR}/tlc" && make )
interp/discharge.ml:      let shortlc =
interp/discharge.ml:    mind_entry_lc = shortlc })
~~~
So maybe we should just delete it.

**Comment by ejgallego** [comment]
> Also we don't test tlc at all AFAICT

Oh good point Gaëtan, I added TLC back in the day as it was a part of the original jsCoq distribution, but I didn't enable it as it was not compiling with `master` at that point.

**Comment by Zimmi48** [comment]
Sorry, this was an overlook. The right URL was https://gitlab.inria.fr/charguer/tlc.

>I added TLC back in the day as it was a part of the original jsCoq distribution, but I didn't enable it as it was not compiling with master at that point.

OK, so time to decide what to do wrt testing it or removing it. I tentatively enabled testing TLC in this branch. But I'm not sure it will work.

**Comment by ejgallego** [comment]
> But I'm not sure it will work.

Indeed this is not the right thing to do; we should remove it and @charguer should be the one requesting its addition.

**Comment by Zimmi48** [comment]
OK, then I'll update this PR to remove it.

> note however that `gitlab.inria.fr` does not meet our CI policy w.r.t. upstream hosting.
> 
> We may grandfather this for a while but this is in conflict with my ongoing Coq universe tool that requires for open hosting platforms so it can submit Pull Requests.

Inria's GitLab may be at the verge of acceptability. Anyway, you will need to be more specific on the tool you're building if you want it to influence what we accept or refuse in the CI.

**Comment by ejgallego** [comment]
> Anyway, you will need to be more specific on the tool you're building if you want it to influence what we accept or refuse in the CI.

Indeed we have just started to open the discussion, the tool could interface with many systems.

> Inria's GitLab may be at the verge of acceptability.

IMHO it already doesn't meet the current policy.

**Comment by ejgallego** [comment]
> OK, then I'll update this PR to remove it.

Thanks, indeed no point in adding TLC if the author doesn't commit to the CI policy.

**Comment by Zimmi48** [comment]
>IMHO it already doesn't meet the current policy.

Not clear. Some of us can actually submit PRs to Inria's GitLab repositories. The policy is pretty vague about this. An automatized solution doesn't necessarily require an open platform BTW. I have already mentioned solutions that do not require it. Anyway, that's not the place nor the time to discuss this.

**Comment by ejgallego** [comment]
> Some of us can actually submit PRs to Inria's GitLab repositories. The policy is pretty vague about this.

The policy is mostly a "should" as we want to be flexible, but given that I wrote that paragraph IIRC the interpretation of intent is clear to me.

> An automatized solution doesn't necessarily require an open platform BTW.

This is more of a philosophical choice if you want, but I'd rather steer clear of non-open platforms; IMHO even if we work fine today with them, in the long term they will prove problematic. I'd rather leave to whoever is coming next to help with Coq a fully free architecture.

**Comment by charguer** [comment]
I think it's a good idea to keep TLC in Coq CI, as it exercices many features. 

I'm happy to add any coq dev as contributor to tlc if that can help.

If absolutely necessary, i could consider migration to github.

**Comment by ejgallego** [comment]
So @charguer this is the current CI policy, let us know if that'd work for you https://github.com/coq/coq/blob/master/dev/ci/README-users.md

**Comment by Zimmi48** [comment]
@charguer I will revert this PR to my previous commit adding TLC testing.

For now, don't change TLC location, your project is not the only one on Inria's GitLab and I want to complete the discussion on the policy and tooling with @ejgallego before enforcing any decision. In particular, it would be weird that a policy that mandates openness encourages a migration to a free, self-hosted platform, to a non-free, centralized one.

**Comment by ejgallego** [comment]
> So @charguer this is the current CI policy, let us know if that'd work for you https://github.com/coq/coq/blob/master/dev/ci/README-users.md

Thanks @Zimmi48 , @charguer I will merge tomorrow in case you want to comment on the CI policy.

**Comment by ejgallego** [comment]
In particular @charguer there is one point that we don't enforce now but we may soon: contribs included in the CI should have their own CI setup testing against the supported versions of Coq.

What is the CI policy/plan for TLC?

**Comment by Zimmi48** [comment]
>The policy is mostly a "should" as we want to be flexible, but given that I wrote that paragraph IIRC the interpretation of intent is clear to me.

I actually wrote that policy @ejgallego :wink: (cf. #1032)

**Comment by Zimmi48** [comment]
@ejgallego If you don't merge this soon, you should remove it from the current milestone.

**Comment by ejgallego** [comment]
Where do you get that from @zimmi48? I asked and got no clear policy , maybe I've missed some message?

**Comment by Zimmi48** [comment]
That's how I understand:

>This is a kind reminder that the 8.10 branch will be created next week.
>After that point, the 8.10+β1 milestone should no longer be used for new issues/PRs (bugs and bug fixes excepted).

**Comment by ejgallego** [comment]
> After that point, the 8.10+β1 milestone should no longer be used for new issues/PRs (bugs and bug fixes excepted).

Yeah it says "for new issues"; so this doesn't need like super immediate merge, right?

**Comment by Zimmi48** [comment]
That's ambiguous indeed but I personally interpret the “new PR” part as “newly merged PRs should be in the 8.11 milestone unless they are bug fixes”. I am pretty sure that this is what @vbgl meant.

**Comment by ejgallego** [comment]
> I am pretty sure that this is what @vbgl meant.

I am not so sure given his wordings in a few PRs, anyways he can always clarify. IMHO we still could use more detailed release updates / plans.

**Comment by ejgallego** [comment]
> What is the CI policy/plan for TLC?

This is so far blocked on this question; if we don't make progress on this soon I'd rather close this PR, of course @charguer can resubmit when he wants.

**Comment by Zimmi48** [comment]
It is a bit of a pity to have decided not to test TLC because it doesn't have any kind of CI when you know that most of the projects we test didn't have a CI either, and we helped them put it in place.

In any case, I'm reopening this PR because if the decision is to not test TLC, then the PR can still be hard reset to an earlier stage, 29ed7ccab9aa6e521db06761427c12e0f1be2a32, when the point of the PR was not to test TLC but to clean-up the CI scripts from something that is actually (and has always been) dead code.

**Comment by charguer** [comment]
After reading the CI documentation and discussing with @Armael, we came to the conclusion that:
- it would be desirable for us to set up CI for TLC
- when it is ready, TLC would naturally be ready to enter back into Coq CI.

There is one difficulty that I still need to investigate (and might take a bit of time for me to figure out). For each version of Coq, TLC would provide one branch, dedicated to Coq CI. Yet, from reading the current documentation of CI, it does not seem completely obvious how to set up the CI script to indicate which branch of TLC should compile with with version of Coq.

Until I resolve this issue, I am fine with manually testing Coq beta-releases on TLC.

**Comment by Zimmi48** [comment]
> For each version of Coq, TLC would provide one branch, dedicated to Coq CI.

This is one possible setup, but not the one I would recommend: Coq libraries (as opposed to plugins) can generally manage to maintain compatibility with several versions of Coq, so it is generally preferable to have a single branch (e.g. master) that is tested with a few versions of Coq (including Coq's master branch). On the other hand, you are free (if you prefer) to follow the model recommended for plugins, i.e. having a dedicated branch per version of Coq.

I would also discourage you to create specific branch for Coq CI. The patches we deliver are safe to main in your main development branches. The only inconvenience this may create is that you should then favor pushing new commits on topic branches to run CI before merging to master.

>from reading the current documentation of CI, it does not seem completely obvious how to set up the CI script to indicate which branch of TLC should compile with with version of Coq.

It is not clear from your question if you are asking about the CI setup on the Coq side or on the TLC side. If you are talking about the Coq side, then the only thing you have to worry about for now is what is the branch tracking Coq master. If you are asking about the setup on the TLC side, then I recommend you look at this doc https://github.com/coq-community/docker-coq/wiki/CI-setup, and the example GitLab projects.

**Comment by Zimmi48** [comment]
> Until I resolve this issue, I am fine with manually testing Coq beta-releases on TLC.

Note that the whole point of the CI is to not just test the beta-releases but also the development branch of Coq (master) itself.

**Comment by ejgallego** [comment]
@charguer I think we have gathered enough experimental evidence to do as @Zimmi48 suggests: your main development branch should be good for Coq's CI.

Coq is committed to n.+1 version compatibility at the bare minimum so you should be able to develop in Coq 8.x and have your library work in 8.x.+1 without changes [in theory].

For users of the ML API, that's a different story. I still expect a lot of churn and indeed as of today the most practical is to tie plugin releases to Coq releases.

**Comment by ejgallego** [comment]
@charguer a good real CI setup is the one in math-comp https://github.com/math-comp/math-comp/blob/master/.travis.yml

**Comment by Zimmi48** [comment]
Nope. This setup is outdated, not currently in use, and does not rely on any of the two recommended solutions. The setup *currently* in use in math-comp is good but overly complicated to show as an example. The examples in the link I gave above may be toy but they are good enough.

**Comment by ejgallego** [comment]
Oh indeed, I meant to point to the real one; I took for given the ones in the example of course, I just wanted to point out to a fancier one in case TLC wants to setup CI for the developments depending on it [which are quite a few IIAC]

**Comment by Zimmi48** [comment]
I see, then the link is https://github.com/math-comp/math-comp/blob/master/.gitlab-ci.yml. But I think anyway, this should be considered as a second step (as it is much more complex than just setting up basic CI).

**Comment by ejgallego** [comment]
I guess discussion is stalled, I'm closing this PR, the TLC authors are very welcome to resubmit.

**Pull request closed without merging**
