### PR TITLE
[stdlib]Reals: use “lia” rather than “omega”

### PR DESCRIPTION
**Pull request by vbgl**
This is a small step to help removing “omega” from the code base. See #7878 for details.

### CODE REVIEW

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
This is a fairly trivial, low-risk PR. I'm merging it into 8.11 myself then.

**Comment by vbgl** [comment]
Thanks. It would be nice if we could deprecate “omega” in 8.11: “lia” is ready to replace it.

**Comment by ppedrot** [comment]
I don't think we'll have time for that though, it's quite a major change.

**Comment by ejgallego** [comment]
We can do it first commit in the 8.12 tree; we have quite a few of `master` testers so it would be great to have them test it during the whole 8.12 cycle.

**Comment by vbgl** [comment]
I don’t think deprecation is such a big change. Removing “omega” will be the big change. This is why it is announced — through a deprecation warning — one version in advance.

**Comment by ppedrot** [comment]
@vbgl what's missing too remove all uses of omega in the Coq codebase?

**Comment by ejgallego** [comment]
> I don’t think deprecation is such a big change. Removing “omega” will be the big change. This is why it is announced — through a deprecation warning — one version in advance.

Likely I got lost on the original plan. Do you folks still plan to alias `omega` to `lia` ?

**Pull request merged**
