### PR TITLE
Keep cache of (constant / inductive) -> needed section variables in environ

### PR DESCRIPTION
**Pull request by SkySkimmer**
possibly helps with https://coq.zulipchat.com/#narrow/channel/237656-Coq-devs-.26-plugin-devs/topic/Some.20performance.20numbers.20for.208.2E19.20-.3E.208.2E20.2C.208.2E19.20-.3E.20master/near/479485561

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by SkySkimmer** [comment]
Related https://github.com/coq/coq/pull/12941

**Comment by Janno** [comment]
Copied from the zulip thread: the performance results on BlueRock (formerly BedRock) code. The numbers are billions of instructions. Divide by 6 to get a rough estimate in seconds. 

| Relative | Master   | MR       | Change   | Files
|---------:|---------:|---------:|---------:|----------
|   -0.06% |  33622.0 |  33602.6 |    -19.4 | generated
|   -0.97% |  83723.3 |  82909.6 |   -813.7 | proofs
|   -0.71% | 117345.3 | 116512.2 |   -833.1 | total

**Comment by ppedrot** [comment]
I'm fine with the code change, but is it worth it?

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
Private answer: yes. @coqbot merge now

**Pull request merged**
