### PR TITLE
Moving interpretation of constr and redexpr to vernac for usage of Eval (fixes #8240)

### LINKED ISSUE #8240: -noinit anomaly in Definition := Eval cbv in.
~~~~~
The Coq Proof Assistant, version 8.8.1 (July 2018)
compiled on Jul 5 2018 7:25:50 with OCaml 4.06.0
~~~~~

~~~~~
(* -noinit *)
Example simple_cbn := Eval cbn in (fun x:Set => x).
(* Error:
Anomaly "Uncaught exception Invalid_argument("Lexer: location function")."
Please report at http://coq.inria.fr/bugs/. *)
Example simple_cbv := Eval cbv in (fun x:Set => x).
Example simple_vm_compute := Eval vm_compute in (fun x:Set => x).
~~~~~

Works fine without `-noinit`. I am looking for a way to create big terms without loading the prelude to make less flaky memory usage benchmarks.

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** redesign

#### Summary

Reduction relation can be used independently of Ltac using `Eval`. This PR moves their interpretation in vernac so that `Eval` works independently of the presence of Ltac.

Fixes / closes #8240

#### Description and questions

1. This interpretation remains over terms with variables from a meta-language, but this meta-language is now "abstract" (I even added a field to parameterize the name of the meta-language in error messages).
2. I made the `strict_check` global reference a field of the glob_sign (much nicer)
3. I was lazy in building the `mli` (copying the result of `ocamlc -i`).
4. There should not be changes of semantics, except:
   - strict mode used to interpret `Extern` hints, `autorewrite` hints, `Proof using`, obligations (in `G_obligations.with_tac`: is it ok?), as well as `ltac:()`/`ltac2()` expressions occurring in terms which themselves are not occurring in tactics which themselves are at toplevel and not part of an `Ltac`/`Ltac2` definition (as e.g. in `Definition d := ltac:(...)`)
   - poly attribute used to interpret `Declare Reduction` as well as in toplevel `Eval`
   - red expr interpreted for `Eval` in strict mode
#### Questions

1. Architectural questions:

   First, it creates files in `vernac`
   - `Constrmetainterp`, `Constrmetaintern`: the interpretation of `constr` containing "metalanguage" variables (ltac or ltac2)
   - `Redexprinterp`, `Redexprintern`: the interpretation of `red_expr` containing "metalanguage" variables

   @ejgallego: Is `vernac` the good place? (I had to depend on `Genprint` which is in printing, so `interp` was to low)

   Somehow, one could have also a file:
   - `Stdarginterp` for the interpretation of basic arguments: mainly `int` and its variant

2. In passing, wasn't there a naming decision taken between `red_expr`, `redexpr`, `redexp`?

3. In `Declare Reduction id := red_expr`, with which value of `poly` do we want the constr inside to be evaluated? The one given by `atts`, the one by default?

4. I used a module for abstracting over coercion functions from `Taccoerce`. But why not to put these basic coercion functions in `vernac` too?

- [X] Added / updated test-suite
- [ ] Entry added in the changelog

### CODE REVIEW

**Comment by ejgallego** [comment]
Trying to solve this some months ago I followed a different approach; I split the interpretation up into `pretying/valinterp` and `interp/geninterp`; I dunno if that's the right approach, I have to think about it.

**Comment by herbelin** [comment]
> Trying to solve this some months ago I followed a different approach; I split the interpretation up into `pretying/valinterp` and `interp/geninterp`; I dunno if that's the right approach, I have to think about it.

I would have liked to put them in `pretyping` and `interp`, but I had dependency problems (in particular wrt printing in `genprint.ml`).

Up to which point did you try? Did you have something operational?

**Comment by ejgallego** [comment]
I had some problems but I don't remember exactly what.

I don't see how printing is a problem in this version tho; it looks that the problem you have could be avoided by defining a regular exception instead of using `user_err`. I just did that and things worked fine; you could even refine it more doing the split I think.

Another question is whether `interp_red_expr/intern_red_expr` should be defined in the genredexpr module themselves, so the module would have a signature of "interpretable object"

I dunno, I tried to follow this approach so instead of adding a functor I did define a gencoerce module.

**Comment by herbelin** [comment]
> I don't see how printing is a problem in this version tho; it looks that the problem you have could be avoided by defining a regular exception instead of using `user_err`. 

OK, I made a new error and I move `constrmetainter{p,n}.ml` to `interp` (next to `constrintern.ml`) and `redexprinter{p,n}.ml` to tactics (next to `genredexpr.ml`)

Some further refactoring with `constrintern.ml` is probably feasible (but maybe for a next time).

> Another question is whether `interp_red_expr`/`intern_red_expr` should be defined in the `genredexpr` module themselves, so the module would have a signature of "interpretable object"

File `genredexpr.ml` is only about types, so I renounced to add code in it.

> I dunno, I tried to follow this approach so instead of adding a functor I did define a gencoerce module.

I can do that if @ppedrot is also ok.

Note: I did not smash yet, so that new commits can be checked independently.

**Comment by ejgallego** [comment]
Thanks @herbelin I'll have a more detailed look ASAP, but in principle I'm OK with merging now and doing more refinements later if we want. The question about the organization I wait for @ppedrot 's opinion.

@ppedrot would you like to assign? I can take it too otherwise.

**Comment by ppedrot** [comment]
I didn't review carefully yet, but I am slightly concerned by the introduced amount of Ltac-ish dependency into standard Coq code. Judging from the kind of bug this is trying to solve, this looks very suspicious. I'll have a deeper look and think a bit about it though.

**Review by ppedrot — CHANGES_REQUESTED** [review]
Sorry for the late answer, but this PR went under my radar. This is going the wrong direction, as this is adding hard coupling with Ltac-specific code in unrelated parts. Instead, the `Eval .. in ...` feature should be registered dynamically by the Ltac plugin. One should introduce a specific parsing entry for it, as well as a table of interpretation functions per plugin. Other plugins might want to perform the same kind of tricks, there is no reason that LtacX should deserve special treatment.

**Comment by herbelin** [comment]
@ppedrot: Thanks for your comments.

Do you mean that the `Eval`-in-terms syntax should be not hard-wired and unavailable without loading any plugin, or do you mean that the `red_expr` syntax should not be hard-wired and be empty without loading any plugin?

Regarding the interpretation of reduction functions, do you have concerns about their syntax? About the coercions used while interpreting?

Do you have concerns about the `strict_check` flag?

I'd like that the implemented approach is generic (if ever it needs to be repeated, if I spend time working in relation to Ltac1, that does not mean not working with Ltac2 in sight too!).

**Comment by ppedrot** [comment]
> Do you mean that the Eval-in-terms syntax should be not hard-wired and unavailable without loading any plugin, or do you mean that the red_expr syntax should not be hard-wired and be empty without loading any plugin?

The first one. The `red_expr` entry shouldn't even be a part of the core vernacular syntax, it should be define in Ltac instead.

> What kind of specific dynamically registered parsing entries do you have concretely in mind?

The kind of stuff we do for proof modes.

> Regarding the interpretation of reduction functions, do you have concerns about their syntax? About the coercions used while interpreting?

The syntax is defined by the caller, so it's their responsibility. As is well-known, that is highly non-modular but I don't think many plugins would define conflicting syntaxes of their own. As for the rest, the interpretation should be as straightforward as possible, but we have to be backwards compatible though, so...

> Do you have concerns about the strict_check flag?

About that one, I wanted to ask for introducing it in a separate PR. It's actually cleaner, useful in general, but on second thought it's also potentially going to make some external users unknowingly depending on LtacX-specific features. So, I'd like to have it done still, but maybe protected by some deprecation flag or something.

**Comment by herbelin** [comment]
> The first one. The red_expr entry shouldn't even be a part of the core vernacular syntax, it should be define in Ltac instead.

I don't think that `Eval` is specific to `Ltac1`. So, a possibility could be to isolate a new (standard) plugin, say, `evalconstr`, that declare the `Eval` entry, together with the `red_expr` syntax for reduction functions. What do you think? This plugin would have to anticipate that the `Eval` hook can contain metavariables (i.e. LtacX variables) though, so that tactic language plugins can reuse the code. Would it be ok to you?

> > Do you have concerns about the `strict_check` flag?
> 
> About that one, I wanted to ask for introducing it in a separate PR.

I can do that (but I don't believe it is LtacX specific in itself, it is just about whether a tactic language is allowed to implicitly refer to the current context of a goal). Moreover, in `constrmetaintern.ml`, this is even just about whether unbound variables are allowed in a term or not, like the `for_grammar` modifier already does. So, no need here to talk about a tactic language explicitly.

Additionally, I have ideas about how to replace the "ugly" pair `glob_constr * constr_expr option` with a `glob_constr` together with the list of variables to be dynamically interpreted, so that we don't need to re-intern, but only to interp with a dynamic behavior for variables.

> So, I'd like to have it done still, but maybe protected by some deprecation flag or something.

What deprecation strategy do you have in mind? I mean, beside applying a translator to rewrite all tactics that refer implicitly to a variable of the context, I don't see how the `strict_check` can be removed.

> As for the rest, the interpretation should be as straightforward as possible, but we have to be backwards compatible though, so...

Are the current versions of `constrmetainterp` and `constrmetaintern` enough standard to you (up to maybe clarifying and documenting the differences between the various `{open_,u}constr{,_no_classes}`)? Probably, you'd like `interp_constr_list` to be back in `ltac`. This could be done if you think so.

For `redexprintern.ml` and `redexprinterp.ml`, since it is `red_expr` specific, it would go in the new plugin though.

**Comment by ppedrot** [comment]
> I don't think that Eval is specific to Ltac1

Depends on what you call `Eval` exactly, but what is inside the node clearly is. Reduction expressions are literally Ltac1 syntax. So, I am not surprised that you were forced to push back Ltac-specific code in this PR.

> This plugin would have to anticipate that the Eval hook can contain metavariables (i.e. LtacX variables) though, so that tactic language plugins can reuse the code. Would it be ok to you?

This looks *very* wrong. Why on earth should you depend on this? `Eval` is reimplementable merely using tactic-in-terms, so I don't understand why you need to deploy such an apparatus. Furthermore, you don't even need that much power since the places where `Eval` can appear are really restricted.

> I don't see how the strict_check can be removed.

I think there was a misunderstanding: I don't want to remove it, I want to pass it functionally without allowing casual users to access it.

**Comment by herbelin** [comment]
> Depends on what you call Eval exactly, but what is inside the node clearly is. Reduction expressions are literally Ltac1 syntax. So, I am not surprised that you were forced to push back Ltac-specific code in this PR.

Indeed, it depends about we intend by `Eval`. The forms available in Gallina are only closed forms, without metavariables to interpret. So, in this sense, they are not related (at all) to a tactic "language".

It also depends about we intend by reduction algorithms. Per se, `simpl`, `cbn`, etc. are independent of any form of tactic language (even if they need a concrete syntax). So, the point of view that Ltac1 reuses and extends the reduction language of Gallina's `Eval` with variables is as defendable as the point of view that `red_expr` is something from the tactic language whose close instances are reused in Gallina.

So, I believe that the question is really about what syntax we want for reduction algorithms in Gallina, and if we want this syntax to be fixed for everyone (i.e. attached to Gallina) or customizable (i.e. attached to plugins).

Do you also conclude that this is the question?

> `Eval` is reimplementable merely using tactic-in-terms

Yes. So, this is related to the previous question. Is Gallina's `Eval` a (proper) Gallina thing or a feature incidentally provided (only) by tactic languages?

**Comment by herbelin** [comment]
In passing, an example to consider in order the more clearly specify the semantics of `Eval` we want:
```
Definition f (a:=0) := Eval lazy delta [a] in a=a.
(* Error: The reference a was not found in the current environment. *)
```

**Comment by ejgallego** [comment]
Indeed, what belongs in ltac and what doesn't seems like an interesting question; maybe we should chat in the call about that. For example a non-trivial chunk of `tactics` can be indeed seen to belong to `ltac` , whereas others are used by the core vernacular; it seems hard to make everyone happy here.

**Comment by herbelin** [comment]
@ppedrot: It looks like we are stuck on a conceptual issue.

To address the issue from a practical point of view, maybe the question is the one of whether there are plans to rethink the design of reduction commands? If not, maybe the status quo proposed by this PR may not be that bad until we come with more concrete plans?

**Comment by Zimmi48** [comment]
> Instead, the `Eval .. in ...` feature should be registered dynamically by the Ltac plugin

What?! But there is nothing Ltac in `Eval vm_compute in ...`

I strongly oppose to the view expressed by @ppedrot. As said by @herbelin, there is no reason why `red_expr` syntax should be considered Ltac syntax except the fact that the parsing code was moved there when the Ltac plugin was introduced (like the tactics, with all the duplication trouble that it is causing now with Ltac2).

IIUC this PR hardwires some `red_expr` into core and lets Ltac or any other plugin extend it. This seems very reasonable to me. Sorry for not having shown support earlier.

> 2\. In passing, wasn't there a naming decision taken between `red_expr`, `redexpr`, `redexp`?

In the doc, we opted for `red_expr`.

**Comment by ppedrot** [comment]
@Zimmi48 that is true for `vm_compute` which is just a name, but we also have more complex tactics that definitely import Ltac syntax like `unfold` or `pattern`. Assuming we want to support this syntax inside `Eval` nodes regardless of the Ltac syntax, this should *not* introduce a code dependency into the crazy features of the Ltac term interpretation, which is what this PR does.

**Comment by ppedrot** [comment]
To be clear: my problem with this PR is not conceptual in any way, it's about the implementation. I am actually fine with the dual view that `Eval ... in ...` is vernacular syntax, and that Ltac does its best to mimic this syntax.

But precisely, this highlights that Ltac is *mimicking* the syntax, not *sharing* it. If Ltac had a proper antiquotation syntax, then it'd be obvious that the two syntaxes are actually different, since the vernacular one doesn't contain antiquotations. See Ltac2 for a manifestation of this phenomenon.

So, there is no reason to try to share the intern / interp functions between the two variants since *they can't be shared* because *they do not match*. For a concrete example of Ltac-specific runtime in this PR, look at `interp_in_compound_list` whose only reason of existence is to ultimately support Ltac tactic notations!!! I am not sure it is worth to share the AST, but definitely we should not even try to share the aforementioned functions, and actually not trying to do that is probably going to make the PR smaller.

**Comment by herbelin** [comment]
> the two syntaxes are actually different, since the vernacular one doesn't contain antiquotations. 

Even if Gallina does not have antiquotations, which I actually prefer to call metalanguage variables (in practice either Ltac or Ltac2 variables) because antiquotations refers to how metalanguage variables are syntactically denoted while the question is here semantical, it is already the case that `constrintern.ml` and `pretyping.ml` have an anticipated support for metalanguages variables, because we would not like to rewrite the whole `constrintern` and `pretyping` from scratch in LtacX (accordingly, this anticipated support could be done in an oriented-object way - as you prepared it for pretyping - rather than by using a hard-wired field in the interning and pretyping environments - I'd be ok to go this route).

As for the `interp_in_compound_list` thing, we can see it as a syntax thing but we can dually see it as a subtyping thing, that is as the ability to coerce a variable of type something into a variable of type list of something by taking the singleton list of its value. With types, as Ltac2 has, there would be no need for `interp_in_compound_list` because we would statically know that this or that metalanguage variable is of type a list of something or of type something, and we would be able to insert the coercion statically. 

And I agree,  `interp_in_compound_list` could be moved to `taccoerce.ml`.

Concretely, what to do? I suspect that what you would like to have is the ability to insert hooks in each of the `interp_constr`, `interp_constr_list`, `interp_open_constr`, etc, so that the metalanguage variables are not managed at the Gallina level but by means of hooks set by LtacX. Would that fit your objectives? (Or is the current abstraction over coercions (with `interp_in_compound_list` then integrated to `coerce_to_constr_list`) ok enough?)

**Comment by ppedrot** [comment]
> Concretely, what to do?

First, decide what we're actually aiming for. This PR was originally only about fixing the fact that `Eval ... in` triggers an anomaly when Ltac is not loaded. This is trivial to fix with a hook in less than 10 lines of code. But it might be the right time to ponder about the `Eval ... in` feature instead.

Fun fact: those two are not equivalent. Guess why, and explain why it's adding water to my mill.
```
Definition foo (x := 0) := ltac:(let c := eval unfold x in x in exact c).
Definition foo' (x := 0) := Eval unfold x in x.
```

**Comment by Zimmi48** [comment]
While I understand @ppedrot's concerns, I am not qualified to discuss all the implementation quirks. I don't have any practical solution to propose but to me this is all about seeing `red_expr` as something extensible (just like the grammar of Coq generally is). I would also be happy to see this extensibility better expressed in the code base for instance with an object-oriented approach as proposed by @ppedrot and reminded by @herbelin.

Regarding the anti-quotations you mentioned, are there in the `Eval ...` part or in the `in ...` part? If they are in the former, then I don't see the issue with the view that `red_expr` is extensible and that the actual "reduction" process will be left to the plugin extending the base `red_expr`. If they are in the latter, then I need an example.

**Comment by ppedrot** [comment]
> Regarding the anti-quotations you mentioned, are there in the Eval ... part or in the in ... part?

In the first part.

> If they are in the former, then I don't see the issue with the view that red_expr is extensible and that the actual "reduction" process will be left to the plugin extending the base red_expr. 

But then this is not coherent with the view that `Eval ... in` is part of the vernacular. What you're saying is that these reduction functions should be implemented in the Ltac plugin and thus rely on its semantics.

**Comment by herbelin** [comment]
@ppedrot:
> Fun fact: those two are not equivalent. Guess why, and explain why it's adding water to my mill.

Is the following a correct way to rephrase your mill: the binding structure of an expression mixing both metalanguage binders and object level binders is not necessarily very intuitive and it's better to have different name spaces (i.e. different name spaces for metalanguage variables and for object language variables) so that things are clearer for the user (even if the price is to force using `$` here and there)?

@Zimmi48:
> Regarding the anti-quotations you mentioned, are there in the Eval ... part or in the in ... part?

What @ppedrot calls anti-quotations is to make a syntactic distinction between LtacX variables and constr variables (my way to say it, at least). They can occur in both the `Eval` part and the `in` part. In Ltac1, there is a semantic distinction but no syntactic distinction. In Ltac2, there is a semantic distinction and also a syntactic distinction.

Here is an example with LtacX variables in both the `Eval` part and the `in` part:
```
Ltac f x ::= let y := eval unfold x in (x _ 0) in assert (y = y).
Goal True.
f id.
(* 0 = 0 *)
```
I don't know how to exactly write the same code in Ltac2, but morally (up to a coercion between constr and reference), my understanding is that it is something like:
```
Require Import Ltac2.Ltac2.
Ltac2 g x := let y := eval unfold $x in ($x _ 0) in assert ($y = $y).
g id.
```
In particular, what needs to be dynamically extended is not the set of possible reduction strategies but the ability to interpret `$x` variables. In the case of `Eval` (in definitions), it is syntactically impossible to have such ambient LtacX variables present, so the problem is only in LtacX code referring to reduction expressions.

**Comment by herbelin** [comment]
@herbelin:
> In the first part.

@ppedrot
> They can occur in both the Eval part and the in part.

Ah, our answers are inconsistent...

**Comment by ppedrot** [comment]
> Is the following a correct way to rephrase your mill

It's even before reaching that kind of high-level consideration.

If we agree that this difference of behaviour is a bug, this shows that `Eval X in Y` should be syntactic sugar for `ltac:(let c := eval X in Y in exact c)`. In particular, this makes obvious that we must rely on Ltac semantics for bindings, and thus that the contents of `Eval ... in` are actually Ltac expressions, whether you want it or not.

**Comment by ppedrot** [comment]
> Ah, our answers are inconsistent...

You don't have to use dynamic binding in the RHS, do you? In particular, the LHS of the Eval clause cannot bind in the RHS... Or can it? Please tell me we don't allow `change` with patterns in `Eval`...

**Comment by herbelin** [comment]
> If we agree that this difference of behaviour is a bug, this shows that Eval X in Y should be syntactic sugar for ltac:(let c := eval X in Y in exact c). In particular, this makes obvious that we must rely on Ltac semantics for bindings, and thus that the contents of Eval ... in are actually Ltac expressions, whether you want it or not.

I'm lost in terminology. We have an LtacX variable `c` but only because it is not possible to write the syntax `ltac:(exact (eval X in Y)) (or even `ltac:(eval X in X)`, assuming that an Ltac expression returning a term would be allowed) . So, strictly speaking we don't need LtacX variables here.

In particular, in `Definition foo (x := 0) := ltac:(let c := eval unfold x in x in exact c).`, the dependency is not in an LtacX variable but in a variable of the Coq-level context.

> You don't have to use dynamic binding in the RHS, do you? In particular, the LHS of the Eval clause cannot bind in the RHS... Or can it? Please tell me we don't allow change with patterns in Eval...

I'm lost in terminology also here. In the example `Definition foo (x := 0) := ltac:(let c := eval unfold x in x in exact c).`, why do you call the binding of `x` as dynamic more in the LHS of `eval ... in ...` than in the RHS. In both cases, it is the same reference to a variable of the context, doesn't it?

**Comment by ppedrot** [comment]
@herbelin you're missing the point, `c` is just noise. It's about `X` referring to dynamic variables.

**Comment by Zimmi48** [comment]
> In the case of `Eval` (in definitions), it is syntactically impossible to have such ambient LtacX variables present, so the problem is only in LtacX code referring to reduction expressions.

I was asking about `Eval` not `eval`.

> > If they are in the former, then I don't see the issue with the view that red_expr is extensible and that the actual "reduction" process will be left to the plugin extending the base red_expr.
> 
> But then this is not coherent with the view that `Eval ... in` is part of the vernacular. What you're saying is that these reduction functions should be implemented in the Ltac plugin and thus rely on its semantics.

Some of them, sure. But the `native_compute` and `vm_compute` at the very least as part of the kernel, and independent of Ltac. I believe that there is also one of the other reduction machines (is it `lazy`?) that is implemented in the kernel. We could also admit that in `lazy delta [ foo ]`, `foo` must be an object known by the kernel and cannot be an Ltac (implicit) antiquotation (which I believe is anyway the behavior exhibited by your example). What is the issue with having `Eval ... in` part of the base syntax, but admit that its behavior is delegated to plugins when such plugins choose to extend the `red_expr` syntax? Sure, you would probably need some new `RED_EXPR EXTEND` macro in the `mlg` file to materialize this.

**Comment by ppedrot** [comment]
> What is the issue with having Eval ... in part of the base syntax, but admit that its behavior is delegated to plugins when such plugins choose to extend the red_expr syntax?

I think we do not disagree, actually. My problem is not `Eval`, it's what's in there. My proposal was precisely to extend the contents of the `Eval` statement dynamically on a plugin basis...

**Comment by herbelin** [comment]
> @herbelin you're missing the point, `c` is just noise. It's about `X` referring to dynamic variables.

Yes, `c` is noise in the discussion, and I apologize for not having understood that it is `x` that you were referring as a dynamic binding. And if you call it dynamic, I suppose that this is because of the general situation of an ltacX expression involving various combinations of `intros`, `clear`, `rename` liable to modify the context.

I have two objections though:
- in the current example, there is no such modification of the context, so the context is clearly "statically" known at the time of the `eval`;
- even in the general case, I remain motivated by the perspective that the changes in the context could eventually be tracked with typing (with the little price of restricting ourselves to a class of bindings whose evolution can be traced statically).

**Comment by herbelin** [comment]
@ppedrot: would you be ok to take over with this PR (the way you'd like it to be)?

**Comment by ppedrot** [comment]
@herbelin fine with me.

**Review by maximedenes — COMMENTED** [review]
@ppedrot since you're taking over, how about turning this PR into a draft until it is ready for review?

**Comment by ppedrot** [comment]
@maximedenes I'd rather close it and start afresh, there is little to salvage from this PR.

**Comment by herbelin** [comment]
> > would you be ok to take over with this PR (the way you'd like it to be)?
> fine with me.

@ppedrot: would you find time to do something about this issue?

**Comment by ppedrot** [comment]
Since #8240 has been solve by some magical side-effect, let's close this PR.

**Pull request closed without merging**
