### PR TITLE
[ssr] Rm cast notation

### PR DESCRIPTION
**Pull request by proux01**
To enable https://github.com/coq/coq/pull/18014 via #6134 

Replaces #6133 

- [ ] ~Added / updated **test-suite**.~

- [ ] Added **changelog**.
- [ ] ~Added / updated **documentation**.~
  
  - [ ] ~Documented any new / changed **user messages**.~
  - [ ] ~Updated **documented syntax** by running `make doc_gram_rsts`.~

- [x] Opened **overlay** pull requests.

#### Overlays (to be merged before the current PR

- [x] https://github.com/coq/stdlib2/pull/28
- [x] https://github.com/math-comp/math-comp/pull/1070
- [x] https://github.com/math-comp/math-comp/pull/1071

<!-- Pointers to relevant developer documentation:

Contributing guide: https://github.com/coq/coq/blob/master/CONTRIBUTING.md

Test-suite: https://github.com/coq/coq/blob/master/test-suite/README.md

Changelog: https://github.com/coq/coq/blob/master/doc/changelog/README.md

Building the doc: https://github.com/coq/coq/blob/master/doc/README.md
Sphinx: https://github.com/coq/coq/blob/master/doc/sphinx/README.rst
doc_gram: https://github.com/coq/coq/blob/master/doc/tools/docgram/README.md

Overlays: https://github.com/coq/coq/blob/master/dev/ci/user-overlays/README.md

### CODE REVIEW

**Comment by proux01** [comment]
@coqbot run full ci

**Comment by proux01** [comment]
@herbelin sorry for the delay. This is finally ready if you want to merge it (the failure with deriving is unrelated and fixed there: https://github.com/coq/coq/pull/18079 )

**Comment by herbelin** [comment]
If ok for everyone, including ssr developers, I can assign.

**Review by gares — COMMENTED** [review]
Shouldn't you also remove the CoqCast definition?

**Comment by proux01** [comment]
@gares it's still in use a few lines later: https://github.com/coq/coq/blob/045c362bae8074c77196959c26fe3d11eef56495/theories/ssr/ssreflect.v#L199
But anyway, it will disappear with #6134

**Comment by gares** [comment]
OK!

**Comment by herbelin** [comment]
OK, then I propose to approve and to merge relatively soon.

**Review by herbelin — APPROVED** [review]

**Comment by herbelin** [comment]
Related: #6078

**Comment by proux01** [comment]
Apparently it was reopened as https://github.com/coq/coq/issues/14959

**Comment by herbelin** [comment]
@coqbot merge now

**Comment by herbelin** [comment]
@coqbot merge now

**Pull request merged**
