### PR TITLE
Fixes #12139: tactic subst missing clear with section variables indirectly dependent in goal

### LINKED ISSUE #12139: subst substitutes but does not clear equation
I was assuming that when `subst x` substitutes `x`, the equation used to substitute `x` is cleared.

Other Coq users seem to make this assumption too, because otherwise [this Ltac code](https://github.com/achlipala/frap/blob/69de20dec86597534052615349203477b3612bc3/MessagesAndRefinement.v#L14-L17) can loop infinitely, as shown in this standalone example:

```coq
Axiom proc : Type.
Axiom mkproc : nat -> nat -> proc.

Section WithParams.
  Context (input aggregatorIn : nat).

  Definition MapReduceImpl : proc := mkproc input aggregatorIn.

  Inductive R: proc -> proc -> Prop :=
  | BuildR : forall pr1 pr2,
      pr1 = MapReduceImpl ->
      pr2 = MapReduceImpl ->
      R pr1 pr2.

  Goal forall pr1 pr2,
      input = aggregatorIn ->
      R pr1 pr2 /\ aggregatorIn = input.
  Proof.
    intros.
    subst input. (* Bad: makes progress but does not clear H *)
    (* Bad: loops forever *)
    repeat match goal with
           | x: _ |- _ => subst x
           end.
```

Related to https://github.com/coq/coq/issues/10812:

```coq
  Goal forall pr1 pr2,
      input = aggregatorIn ->
      R pr1 pr2.
  Proof.
    intros.
    Fail subst.
    (* Error: Found no subterm matching "input" in the current goal. *)
    (* Bad: "subst" without arguments should never fail *)
  Abort.
```

Coq version: 8.11.0

This occurred while designing a problem set for our [FRAP class](http://adam.chlipala.net/frap/).

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix
    
If the section variable cannot be cleared, try nevertheless to clear the equation.

This is a potential source of incompatibilites, but it also has to be fixed.

Fixes  #12139 

- [X] Added / updated test-suite
- [X] Entry added in the changelog

### CODE REVIEW

**Comment by herbelin** [comment]
By the way, @ppedrot: what is the current "consensus" about distinguishing section variables from goal variables in named contexts?

**Comment by ppedrot** [comment]
I don't think there is one, as observed in #6826. We should definitely have uniform behaviour across tactics, but I am afraid that this require serious design and backwards-incompatibility, as well as rehauling of the section mechanism.

**Comment by herbelin** [comment]
But were there an agreement:
- at least to keep an information in the goal context to remember what is the copy of a section variable and what is not, which is the mimima to be able to implement decisions about section variables?
- to make a difference between a Var node and a VarRef node in terms (for the same reason)?

**Comment by ppedrot** [comment]
This looks like the definition of "rehauling the section mechanism", and I don't think that there was any consensus on that either. In any case we've been plagued by this for years if not decades, it's not the kind of problem that will magically disappear overnight. My take on that is that design-wise it's on par with universe polymorphism, i.e. requires deep changes that will take a lot of time to be ironed out.

**Comment by herbelin** [comment]
> requires deep changes that will take a lot of time to be ironed out.

In the meantime, maybe small changes can be made, like the one I proposed, i.e. to add to the `named_context` an `Id.Set.t` which tells among the names of the context, which ones are copy of a section variable?

**Comment by ppedrot** [comment]
CI *really* not happy.

**Comment by herbelin** [comment]
Color needs three changes. Verdi fails several times, basically because for `secvar_x = y`, it is now the substitution of `secvar_x` by `y` which is done. Not clear what to do yet.

**Comment by herbelin** [comment]
There is a 3-person consensus at [#12139](https://github.com/coq/coq/issues/12139#issuecomment-623048008) to recommend that `subst` does not work at all on section variables indirectly dependent in the goal. This provides with a different fix for #12139 than this PR. So, closing this PR.

**Comment by samuelgruetter** [comment]
For the record, I was thinking about whether we should reconsider this PR and change the semantics of `subst a` to the temptingly simple spec of always clearing `a` and always clearing the equation, even if there are indirect dependencies on `a` (this would also require `clear` to not remove cleared section variables from the *global* context, but to only remove them from the *goal* context, so that they remain referenceable by the implicit dependencies).

However, this would make `subst` "unsafe" in the sense that it can turn a provable goal into an unprovable goal, which is definitely undesirable.

```coq
Section Foo.

  Variable a: nat.
  Definition b := a + a.

  Goal forall c: nat, c = a -> b = c + c.
  Proof.
    intros.

    (* This goal is provable *)
    assert_succeeds solve[unfold b; subst c; reflexivity].

    Fail subst a. (* Error: Found no subterm matching "a" in the current goal. *)
    (* If we changed the implementation of "subst a" to replace all occurrences
       of a by c (i.e. none) and then clear the equation, the goal would
       become unprovable. *)
    clear H.
    unfold b. (* oops, unprovable *)
```

**Comment by JasonGross** [comment]
> (this would also require `clear` to not remove cleared section variables from the _global_ context, but to only remove them from the _goal_ context, so that they remain referenceable by the implicit dependencies).

I think I've said this before, but I can't find where: There should be two versions of `clear`, one of which is "make it invisible to `match goal`, `assumption`, etc" and the other of which is "make it an error for the proof to depend on it".  It's not clear to me whether `subst` should do the former or the latter (perhaps make it a setting?  or two versions of `subst`?).   Note that I believe this is also the correct solution to #8153 (which continues to be a thorn in my side and makes `Proof using` essentially incompatible with `Let`), that `Let`-bound section variables should be impossible to remove from the global context (much like `Definitions`s), and should only ever be removed from the list of hypotheses.

**Pull request closed without merging**
