### PR TITLE
coqworker: worker names are not mutable

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Comment by Alizter** [comment]
will merge tomorrow

**Comment by Alizter** [comment]
Wow that's the first green CI I've seen in a while.

**Comment by Alizter** [comment]
@coqbot run full CI

**Review by ppedrot — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

**Pull request merged**
