### PR TITLE
Emit Feedback.AddedAxiom in Declare instead of higher layers

### PR DESCRIPTION
**Pull request by SkySkimmer**
This lets us remove the passing around of "status" in comassumption
and generally makes highlighting axiom adding lines in coqide more
reliable as there's no need for per-command code.

If a command adds multiple axioms it will emit AddedAxiom multiple
times, this doesn't seem to be a problem though.

We may wonder if "Fail Fail Axiom" should be highlighted as
"Axiom" (both before and after this commit it is).

Ovrlay: https://github.com/LPCIC/coq-elpi/pull/75

### CODE REVIEW

**Comment by ejgallego** [comment]
Looks like a very nice refactoring.

> If a command adds multiple axioms it will emit AddedAxiom multiple
> times, this doesn't seem to be a problem though.

You could extend the `AddedAxiom` constructor as to include the concrete name? This way UIs could display "Axioms a1, ... an" have been added if they want.

**Review by ppedrot — APPROVED** [review]
Fine with me.

**Comment by SkySkimmer** [comment]
>You could extend the AddedAxiom constructor as to include the concrete name? This way UIs could display "Axioms a1, ... an" have been added if they want.

Maybe in the future (and we could also notify about non-axioms) but I think it's beyond the scope of this PR.

**Comment by SkySkimmer** [comment]
Should be ready to merge, who should be assignee?

**Pull request merged**
