### PR TITLE
Add missing build dependency in `coq.opam`

### LINKED ISSUE #9956: Missing build dependency in coq.opam
#### Description of the problem

I've noticed this issue when refactoring the docker-coq build infrastructure:
Unlike https://github.com/coq/opam-coq-archive/blob/master/core-dev/packages/coq/coq.dev/opam, the `ocamlfind {build}` dependency is missing in the `coq.opam` file of branch `master`.

As a result, if one runs in a fresh opam environment (e.g. in a Docker image) the following:

```
eval $(opam env --switch=4.05.0 --set-switch)
opam repository add --all-switches --set-default coq-extra-dev https://coq.inria.fr/opam/extra-dev
opam repository add --all-switches --set-default coq-core-dev https://coq.inria.fr/opam/core-dev
opam update -y -u
opam pin add -n -y -k git coq "git+https://github.com/coq/coq#${COQ_COMMIT}"
opam install -y -j ${NJOBS} coq bignums
```

we end up with a build error:

<details><summary>Details with OCaml 4.05.0</summary>

```
(…)
coq is now pinned to git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806 (version dev)
+ opam install -y -j 2 coq coq-bignums
<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[coq.dev] no changes from git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806
The following actions will be performed:
- install dune 1.9.1 [required by coq]
- install base-num base [required by num]
- install num 0 [required by coq]
- install coq dev*
- install coq-bignums dev
===== 5 to install =====
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dune.1.9.1] downloaded from cache at https://opam.ocaml.org/cache
[coq-bignums.dev] synchronised from git+https://github.com/coq/bignums.git#master
[coq.dev] synchronised from git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-num.base
-> installed num.0
-> installed dune.1.9.1
[ERROR] The compilation of coq failed at "/home/coq/.opam/4.05.0/bin/dune build @vodeps".
#=== ERROR while compiling coq.dev ============================================#
# context 2.0.4 | linux/x86_64 | ocaml-base-compiler.4.05.0 | pinned(git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806#adc53b59)
# path ~/.opam/4.05.0/.opam-switch/build/coq.dev
# command ~/.opam/4.05.0/bin/dune build @vodeps
# exit-code 1
# env-file ~/.opam/log/coq-125-695c4f.env
# output-file ~/.opam/log/coq-125-695c4f.out
### output ###
# ocaml config/Makefile,config/coq_config.{ml,py} (exit 1)
# (cd _build/default && /home/coq/.opam/4.05.0/bin/ocaml configure.ml -no-ask -native-compiler no)
# Error: cannot find 'ocamlfind' in your path!
# Please adjust your path or use the -ocamlfind option of ./configure
# Configuration script failed!
```

</details>

As an aside, the error does not show up with `4.07.0+flambda` because in this case `coq` seems to depend on `num.1.1` which itself depends on `ocamlfind`…

<details><summary>Details with OCaml 4.07.0+flambda</summary>

```
coq is now pinned to git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806 (version dev)
+ opam install -y -j 2 coq coq-bignums
<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[coq.dev] no changes from git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806
The following actions will be performed:
- install dune 1.9.1 [required by coq]
- install conf-m4 1 [required by ocamlfind]
- install ocamlfind 1.8.0 [required by num]
- install num 1.1 [required by coq]
- install coq dev*
- install coq-bignums dev
===== 6 to install =====
<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[dune.1.9.1] downloaded from cache at https://opam.ocaml.org/cache
[num.1.1] downloaded from cache at https://opam.ocaml.org/cache
[ocamlfind.1.8.0] downloaded from cache at https://opam.ocaml.org/cache
[coq-bignums.dev] synchronised from git+https://github.com/coq/bignums.git#master
[coq.dev] synchronised from git+https://github.com/coq/coq#adc53b598ee2787cf23d8540f03634d19457c806
<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed conf-m4.1
-> installed ocamlfind.1.8.0
-> installed num.1.1
-> installed dune.1.9.1
-> installed coq.dev
-> installed coq-bignums.dev
Done.
```

</details>

### PR DESCRIPTION
**Pull request by erikmd**
**Kind:** bug fix / infrastructure.

Fixes coq/coq#9956

### CODE REVIEW

**Comment by ejgallego** [comment]
As I mentioned on the issue thread, the bug is in configure not in the `opam` file; we could take this fix tho as the easiest path until I push my `mini_conf` branch.

**Review by ejgallego — APPROVED** [review]
Merging as tho help the Docker infrastructure, however the correct fix is to have configure not fail when called from Dune as `ocamlfind` is not needed.

**Comment by erikmd** [comment]
> Merging as tho help the Docker infrastructure, however the correct fix is to have configure not fail when called from Dune as ocamlfind is not needed.

@ejgallego thanks for the merge! regarding the ideal fix you mention, do you plan to take a look at this later? or should I add this to my todo list (but in the latter case I'm afraid I can't promise to do it quickly)

Cheers, Erik

**Comment by erikmd** [comment]
@ejgallego sorry I've just realized you already replied to my question :) cf. your comment in #9956 :

> In fact I already have a configure version that does this in some branch; but I am not sure when it will be pushed.

**Comment by ejgallego** [comment]
Thanks to you, @erikmd ! It seems that opam files will be automatically generated soon by Dune so this problem should sort out by itself. I'm sorry I knew about it but didn't worry to fix it in 4.05.0 as we only use Dune in a 4.07.1 build context.

**Comment by erikmd** [comment]
@ejgallego 
> It seems that opam files will be automatically generated soon by Dune so this problem should sort out by itself

OK great!

BTW, you mention 4.07.1 as an ocaml version; hence my question: should we bump the "edge+flambda" (a.k.a. `$COMPILER_EDGE`) version of ocaml in the docker-coq images to 4.07.1+flambda?
Currently it is 4.07.0+flambda: https://github.com/coq-community/docker-coq/wiki#supported-tags

**Comment by ejgallego** [comment]
> should we bump the "edge+flambda" (a.k.a. `$COMPILER_EDGE`) version of ocaml in the docker-coq images to 4.07.1+flambda?

Sure, for minor OCaml releases I think it is OK to always prefer to latest one.

**Pull request merged**
