### PR TITLE
[default.nix] Unpin nixpkgs

### PR DESCRIPTION
**Pull request by maximedenes**
I hope I understand correctly that the pin in #6953 was temporary. I seems it is no longer needed, so this PR removes it.

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
I'll pass on to @vbgl (and @aspiwack) to approve and merge this PR.

**Comment by aspiwack** [comment]
I have nothing on this. It's a choice whether to pin or not to pin, with pros and cons to both.

The PR is obviously correct.

**Comment by vbgl** [comment]
Maxime, can you please remind us what was the motivation for pinning? and clarify how this motivation is no longer relevant?

**Comment by maximedenes** [comment]
@vbgl Like you wrote in #6953, the motivation was that the new Sphinx infrastructure was requiring packages that hadn't made their way into the channels at the time. I believe that it now works fine with the unstable channel, but that should be double-checked.

**Comment by Zimmi48** [comment]
Note in passing, one advantage of keeping the pin would be for people using a stable nixpkgs channel instead of nixpkgs-unstable. I don't know exactly what pros and cons @aspiwack has in mind.

**Comment by aspiwack** [comment]
I didn't mean anything particularly mysterious: if you pin, you won't have surprises due to update. Which is good. Reproducible, and all that. But if you pin, you don't automatically follow updates, which can be a pain, and after some time, the cache will be discarded, and you will try and build the world just for `which` to lend in your closure.

**Comment by Zimmi48** [comment]
> But if you pin, you don't automatically follow updates

Indeed, if we decided to keep pinning, we would need a process for pin updates. I'd rather not have this.

**Comment by maximedenes** [comment]
closing/reopening for a Gitlab CI integration test.

**Comment by ejgallego** [comment]
Ping @Zimmi48

**Comment by Zimmi48** [comment]
I think we'll keep pinning for now. If we introduce a CI job for Nix, this will avoid breaking it uncontrollably. And when I propose a mechanism to update hashes as proposed in #6724, it can also be done to update this one.

**Comment by ejgallego** [comment]
So this PR should be closed, delayed?

**Comment by Zimmi48** [comment]
Let's close it for now.

**Pull request merged**
