### PR TITLE
CI category_theory: use build:base to match equations

### PR DESCRIPTION
**Pull request by SkySkimmer**

### CODE REVIEW

**Comment by ppedrot** [comment]
It's a net progress, but it does not seem to be enough...

**Comment by Zimmi48** [comment]
As discussed on Zulip, there's also an issue that's not on Coq's side.

**Comment by Zimmi48** [comment]
So IMHO it's still worth merging as is.

**Comment by Zimmi48** [comment]
@jwiegley said on Zulip that he's disabled the parts that are not building with `master`, so I'm restarting the job to check that everything is in order now.

**Comment by ppedrot** [comment]
Looks like it worked. Can we get a quick merge please?

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@coqbot merge now

**Comment by Alizter** [comment]
@coqbot merge now

**Review by Alizter — APPROVED** [review]

**Review by Zimmi48 — APPROVED** [review]

**Comment by Alizter** [comment]
@coqbot merge now

please

**Comment by ppedrot** [comment]
*You can get much farther with a kind word and a gun than you can with a kind word alone.* :skull_and_crossbones:

**Comment by Alizter** [comment]
@Zimmi48 Is it possible for coqbot to complain about all the missing things all at once in order to avoid the repetition?

**Comment by Zimmi48** [comment]
@Alizter You will notice that the first message contained two pieces of information, but you probably read too fast and saw only one:

>You can't merge the PR because there is no kind: label and no milestone is set.

The reason why it also doesn't include the info on the missing review is because at this point in the process, it hasn't fetched it yet, cf.: https://github.com/coq/bot/blob/a48d26947e0ce679529d1308a40b06cb05ea3e1f/src/actions.ml#L1650-L1681

We could change the process to always fetch the reviews before announcing the other reasons for not merging if you think that'd be worthwhile (in this case, feel free to open a PR).

**Comment by Alizter** [comment]
It might be helpful to write the information as a list:
* No kind: label
* No milestone
So that impatient users such as myself can quickly parse the message.

**Comment by Zimmi48** [comment]
Sounds good, please open either a PR or an issue on the bot repository to track that.

**Pull request merged**
