### PR TITLE
Recordops: unify struc_typ summary record and libobject entry struc_tuple

### LINKED ISSUE #12649: Functor signatures over module type with record causes anomaly on Print
#### Description of the problem

I get an anomaly from `Print UseA.` below, as long as `A` contains a record (or class).

```coq
Module Type A.
(* OK *)
(* Definition foo := 0. *)
(* OK *)
(* Inductive foo := bar. *)
(* Makes Print UseA fail. *)
Record baz : Prop := { }. (* any sort would do *)
End A.

Print A.
Module Type UseA (c: A). End UseA.
Print UseA. (* ANOMALY! *)
```

causes

```
Module Type A = Sig Record baz : Prop := Build_baz {  } End
File "./mixin_anomaly.v", line 12, characters 0-11:
Error:
Anomaly "File "clib/int.ml", line 46, characters 14-20: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

#### Coq Version

8.11.2

### PR DESCRIPTION
**Pull request by SkySkimmer**
This requires updating the parameter count at section end, I felt it
was easier to do with rebuild_function but it could be done in
discharge if needed.

Incidentally fixes #12649.

Overlays: https://github.com/LPCIC/coq-elpi/pull/154

### CODE REVIEW

**Comment by ppedrot** [comment]
@SkySkimmer what's the root of the printing bug? Is it caching an object that accesses the wrong environment?

**Review by ppedrot — APPROVED** [review]

**Comment by SkySkimmer** [comment]
AFAICT when we add the module argument for printing we don't add it to the global env, so looking up the inductive to get its param count fails.

**Comment by ejgallego** [comment]
Would be great to get this merged soon as to ship it in 8.12, CI should be fine now if you wanna rebase @SkySkimmer

**Comment by gares** [comment]
On zulip @Zimmi48 asked to stop merging PR's with overlays...

**Comment by Zimmi48** [comment]
This is not yet a strict ban, if you feel this is an important fix to backport and it is merged quickly.

PS: if it's not, then this can simply be moved to 8.13.

**Comment by ejgallego** [comment]
Yup, indeed I think what we discussed was more "no new PRs targetting 8.12 can contain overlays", we still need to backport a few PRs that require bumping the CI refs so this should be fine.

The bug seems pretty ugly so IMO I'll backport this.

**Comment by ppedrot** [comment]
IIUC CI failure is unrelated, so I'll merge this soon (tomorrow?) if nobody complains.

**Pull request merged**
