### PR TITLE
Revert "Stop doing early universe minimization and nf_evar in abstract"

### LINKED ISSUE #18636: Spurious universe inconsistencies in Coq 8.19 with abstracted proofs.
Some of my large proofs break in Coq 8.19. Inserting the following command at the failure point
```coq
exfalso ; clear ; assert True by abstract (exact I).
```
gives
```
Universe inconsistency. Cannot enforce Set = Foo.154 because Set < Foo.154.
```
Forcefully ending the proof with `apply FALSE. Qed.` succeeds without triggering an universe inconsistency. So, the inconsistency does not seem to be present in the current proof term, but instead to be in the proof term created by `abstract` (or in its application to the current goal).

Unfortunately, I do not have a small reproducer. (This can be triggered by compiling the `master` branch of CoqInterval.)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #18636

### CODE REVIEW

**Comment by ppedrot** [comment]
We should probably @coqbot bench

**Comment by SkySkimmer** [comment]
just added changelog

**Review by ppedrot — APPROVED** [review]
Fine as a hotfix.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
