### PR TITLE
Small mod_checking cleanups

### PR DESCRIPTION
**Pull request by SkySkimmer**
See individual commits.

### CODE REVIEW

**Comment by ppedrot** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@SkySkimmer this will conflict with #17049, which one goes first?

**Comment by SkySkimmer** [comment]
I don't care

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
OK, I'll merge this one first since the other is easier to rebase.

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
