### PR TITLE
Fix handling of StuckClass in recursive typeclass search

### LINKED ISSUE #14441: Unexpected type class failure in the presence of Hint Mode
#### Description of the problem

@Blaisorblade tried to use `Hint Mode` for the `Equiv` class in std++/Iris but that attempt failed: some type annotations are needed because of unexpected type class failures.

Below I have included a minimized example: 

```coq
Require Import Utf8 Relation_Definitions.

Class Equiv A := equiv: relation A.
Hint Mode Equiv ! : typeclass_instances.

Class Lookup (K A M : Type) := lookup: K → M → option A.
Hint Mode Lookup ! - - : typeclass_instances.
Hint Mode Lookup - - ! : typeclass_instances.

Parameter list_equiv : ∀ A, Equiv A → Equiv (list A).
Parameter option_equiv : ∀ A, Equiv A → Equiv (option A).
Parameter list_lookup : ∀ A, Lookup nat A (list A).

Existing Instance list_equiv.
Existing Instance option_equiv.
Existing Instance list_lookup.

Set Typeclasses Debug.
(* fails *)
Fail Lemma list_equiv_lookup {A} `{Equiv A} (l k : list A) :
  equiv l k ↔ ∀ i, equiv (lookup i l) (lookup i k).
(*
?Equiv : "Equiv (option ?A)"

?Lookup : "Lookup ?K ?A (list A)"

?Lookup0 : "Lookup ?K ?A (list A)"
*)
```

This example is essentially the same as I used in #5735. We see that `Lookup ?K ?A (list A)` fails, while with mode `Lookup - - !` the instance `list_lookup` should be found.

In #5735, @maximedenes conjectured that the fix for #9058 should fix this example too, but that turns out to be not the case.

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 13 2021 10:35:46 with OCaml 4.11.1
```

/cc @RalfJung @Blaisorblade

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #14441

### CODE REVIEW

**Comment by SkySkimmer** [comment]
BTW without this PR StuckClass would print anomalies (without failing) with TC debug verbosity 2.

**Comment by SkySkimmer** [comment]
@coqbot ci minimize ci-iris

**Comment by SkySkimmer** [comment]
Further minimized:
~~~coq
Require Import Coq.Setoids.Setoid Coq.Classes.Morphisms.

Class PartialOrder {A} (R : relation A) : Prop := {
  partial_order_pre :> PreOrder R;
}.
Global Hint Mode PartialOrder ! ! : typeclass_instances.

Axiom Permutation : forall {A:Type}, list A -> list A -> Prop.

Infix "≡ₚ" := Permutation (at level 70, no associativity).

Global Declare Instance Permutation_cons A :
 Proper (Logic.eq ==> @Permutation A ==> @Permutation A) (@cons A) | 7.
(* priority < 7 does not trigger the bug *)

Global Declare Instance Permutation_Equivalence A : Equivalence (@Permutation A).

Lemma bla A (x:A) (lc lc' lac lbc : list A) (Hc: lac ++ lbc ≡ₚ lc')
  : True /\ x :: lac ++ lbc ≡ₚ lc.
Proof.
  rewrite Hc.
~~~

**Comment by SkySkimmer** [comment]
I can't figure this out further.
cc @mattam82

**Comment by mattam82** [comment]
It looks like a failure to backtrack after a stuck class is found, likely solved by PR #13952

**Comment by SkySkimmer** [comment]
>It looks like a failure to backtrack after a stuck class is found, likely solved by PR #13952

Confirm solved by #13952

**Comment by RalfJung** [comment]
I am confused... https://github.com/coq/coq/issues/14441 is still open, is it not?

**Comment by RalfJung** [comment]
Oh I see, https://github.com/coq/coq/pull/13952 has not landed yet.

**Pull request closed without merging**
