### PR TITLE
Rocq CLI prototype (dynlink based)

### PR DESCRIPTION
**Pull request by SkySkimmer**
https://github.com/coq/coq/pull/19764 is exec based version

### CODE REVIEW

**Comment by SkySkimmer** [comment]
@coqbot bench

**Comment by silene** [comment]
The performance profile is really surprising. Either an optimization is no longer performed at link time (e.g., function interposition gets enabled) or there is a bad interaction with the garbage collector (e.g., toplevel values in dynlinked modules are quite different from those in plain executables, gc-wise).

**Comment by SkySkimmer** [comment]
IIRC there was something about dynlink being quadratic in the number of dynlinked modules
maybe @ppedrot remembers better

**Comment by silene** [comment]
Yes, this is a bug I had reported, but it was specific to OCaml 5, so it should not matter here.

**Pull request closed without merging**
