### PR TITLE
Check VM is enabled in vm_compute

### LINKED ISSUE #16929: `-bytecode-compiler no` does not work
#### Description of the problem

The examples from https://github.com/coq/coq/issues/16891 cause a crash even with `-bytecode-compiler no -native-compiler no`.

```sh
browse@ashryn ~/coq (git)-[fd50789516] % gdb -q coqc -ex 'run -bytecode-compiler no -native-compiler no ../sseg.v' -ex bt -ex q 2>&1 | grep vm
#2  0x000055555602e598 in camlVmsymtable__eval_to_patch_1592 () at kernel/vmsymtable.ml:313
#3  0x0000555555ec0d7b in camlVnorm__cbv_vm_3466 () at kernel/vmsymtable.ml:332
browse@ashryn ~/coq (git)-[fd50789516] % gdb -q coqc -ex 'run -bytecode-compiler no -native-compiler no ../nvag.v' -ex bt -ex q 2>&1 | grep vm
vm_compute. [native-compute-disabled,native-compiler]
#6  0x000055555602e598 in camlVmsymtable__eval_to_patch_1592 () at kernel/vmsymtable.ml:313
#7  0x0000555555ec0d7b in camlVnorm__cbv_vm_3466 () at kernel/vmsymtable.ml:332
browse@ashryn ~/coq (git)-[fd50789516] % gdb -q coqc -ex 'run -bytecode-compiler no -native-compiler no ../vmseg.v' -ex bt -ex q 2>&1 | grep vm 
Starting program: /usr/bin/coqc -bytecode-compiler no -native-compiler no ../vmseg.v
#6  0x000055555602e598 in camlVmsymtable__eval_to_patch_1592 () at kernel/vmsymtable.ml:313
#7  0x0000555555ec0d7b in camlVnorm__cbv_vm_3466 () at kernel/vmsymtable.ml:332
```

#### Coq Version

8.16.0

### PR DESCRIPTION
**Pull request by SkySkimmer**
Fix #16929

### CODE REVIEW

**Review by silene — CHANGES_REQUESTED** [review]
If I understand correctly this pull request, it is a major change of behavior and I am against it.

Up to now, if `-bytecode-compiler no` was passed, any conversion problem implying a VM cast would fall back to the the lazy conversion algorithm (a la `coqchk`). After this pull request, any use of `vm_compute` will just fail. You will not even be able to compile the standard library that way.

**Comment by SkySkimmer** [comment]
This is the out of kernel reduction, not conversion. I copied what was done for native.

What should we do instead? Fallback to cbv?

**Comment by silene** [comment]
I don't understand what you mean. The behavior from `native_compute` is not to error out:
```console
$ rlwrap coqtop -native-compiler no
> Eval native_compute in 0.
Warning: native_compute disabled at configure time; falling back to vm_compute. [native-compute-disabled,native-compiler]
     = 0
     : nat
```

**Comment by JasonGross** [comment]
> What should we do instead? Fallback to cbv?

Yes.

**Comment by SkySkimmer** [comment]
>I don't understand what you mean. The behavior from native_compute is not to error out:

I see, it checks in redexpr and never reaches the error in nativenorm

changed

**Comment by JasonGross** [comment]
Is it worth also providing a flag for coqchk?  (Coqchk is not susceptible to the same bug AFAIK, but it might be nice to provide this flag anyway?)

**Comment by SkySkimmer** [comment]
also coqchk just never enables vm and native AFAIR

**Comment by JasonGross** [comment]
> also coqchk just never enables vm and native AFAIR

I guess this was the historical behavior.  I thought it recently got a flag to enable native, but probably I'm misremembering and it actually got a flag to enable VM.  (We use this flag on fiat-crypto to avoid timing out of GH Actions CI in coqchk.)

**Comment by SkySkimmer** [comment]
Indeed there is a vm flag in coqchk
the flag is properly checked in conversion so should be fine

**Review by silene — APPROVED** [review]

**Review by ppedrot — APPROVED** [review]

**Comment by ppedrot** [comment]
@SkySkimmer do you want to add a changelog?

**Comment by SkySkimmer** [comment]
@coqbot run full ci

**Comment by ppedrot** [comment]
@coqbot merge now

**Pull request merged**
