### PR TITLE
Doc: Remove duplicate `match_term_context` label in ltac2.rst

### PR DESCRIPTION
**Pull request by SkySkimmer**
It already exists iin the ltac chapter.

### CODE REVIEW

**Review by jfehrle — APPROVED** [review]
Seems like something Sphinx should detect and report.

**Comment by jfehrle** [comment]
@coqbot merge now

**Comment by SkySkimmer** [comment]
It's detected in whatever version debian testing installed, that's how I found out about it.

**Comment by jfehrle** [comment]
If it's no trouble, what version is used on Debian?  Maybe we should go to the newer version.

**Pull request merged**
