### PR TITLE
Run update-compat script with --release option.

### PR DESCRIPTION
**Pull request by Zimmi48**
This should ideally have been done before the 8.11 branching, so will need to be backported, and must be merged before any PR updating the version number in master.

**Kind:** clean-up / infrastructure.

[BTW, @JasonGross when the script is not provided any option, it is only a warning, but it is possible to continue. It should not be the case, because then it behaves almost as if run with the right option, except that the `tools/update-compat/run.sh` test does not pass then.]

### CODE REVIEW

**Comment by Zimmi48** [comment]
Apart from the changes in `test-suite/success/NotationDeprecation.v` and the deletion of `test-suite/success/Compat88.v`, the rest of the changes are the results of running the script.

**Comment by JasonGross** [comment]
> [BTW, @JasonGross when the script is not provided any option, it is only a warning, but it is possible to continue. It should not be the case, because then it behaves almost as if run with the right option, except that the `tools/update-compat/run.sh` test does not pass then.]

I'll open an issue about this and submit a PR to fix it.

> Apart from the changes in `test-suite/success/NotationDeprecation.v`

I can also update the compat script to handle this.

**Review by JasonGross — APPROVED** [review]
The files owned by me LGTM.  I suppose I should update fiat-parsers to not rely on the existence of Coq.Compat.Coq88...

**Comment by Zimmi48** [comment]
@ppedrot As the RM, you could be the assignee for this one.

**Review by ppedrot — COMMENTED** [review]
It seems to be OK, let's merge then.

**Pull request merged**
