### PR TITLE
add sifive/kami to ci (through RiscvSpecFormal)

### PR DESCRIPTION
**Pull request by andres-erbsen-sifive**
for now just testing whether this would work infrastructure-wise.

### CODE REVIEW

**Comment by andres-erbsen-sifive** [comment]
`FAILED    modules/pliczek.v.log`
...
```
make[3]: Entering directory '/builds/coq/coq/nix-build-coq.drv-0/2zlcbck1pnnz1r15h9p6zi60wrrpm21w-source/test-suite'
BUILDING SUMMARY FILE
FAILURES
    modules/pliczek.v...could not be checked (Error!)
To print details of failed tests, rerun with environment variable PRINT_LOGS=1
eg "make report PRINT_LOGS=1" from the test suite directory"
See README.md in the test suite directory for more information.
```

I don't understand this, but I sure hope this is unrelated.

**Comment by SkySkimmer** [comment]
The test suite makefile is a mess, I think the dependencies may be incorrect. I rebooted the job.

**Review by ejgallego — APPROVED** [review]
Looks fine to me, @andres-erbsen-sifive would you like this to get merged?

It seems the upstream project has some CI instability ?

**Comment by andres-erbsen-sifive** [comment]
No, we are not ready for this to be merged yet.

**Comment by ejgallego** [comment]
> No, we are not ready for this to be merged yet.

Ok, please ping when you are.

**Comment by ppedrot** [comment]
@andres-erbsen-sifive status of this?

**Comment by Zimmi48** [comment]
cc @andres-erbsen (account might be more relevant)

**Comment by ppedrot** [comment]
No answer and this is getting stale, let's close for the while.

**Pull request closed without merging**
