### PR TITLE
Notations: Removing useless parentheses on abbreviations shortening a strict prefix of an application

### PR DESCRIPTION
**Pull request by herbelin**
**Kind:** bug fix

We avoid useless parentheses when using abbreviations to shorten the prefix of an application. Example:
```
Definition myAnd A B := A /\ B.
Notation myAnd1 A := (myAnd A).
Check myAnd1 True True. (* used to print "(myAnd1 True) True" *)
```

- [X] Added / updated test-suite

Thanks to @ggonthier for reporting.

### CODE REVIEW

**Comment by herbelin** [comment]
Hi, I'm a bit confused. How do we send pull requests to Iris? Do we need to register for an mpi-sws account? Thanks in advance for any help.

**Comment by ppedrot** [comment]
@herbelin I guess that a simple way is to ping @RalfJung to set up your PR. (Note that I happen to still have an account there, but I don't want to mess with their process.)

**Comment by RalfJung** [comment]
See https://gitlab.mpi-sws.org/FP/iris-coq/blob/master/CONTRIBUTING.md for how to contribute to Iris. @herbelin if you already have an account at https://gitlab.mpi-sws.org/, please let me know your handle so I can unlock you for creating forks.

**Comment by herbelin** [comment]
Rebased + overlay submitted upstream. This shall need a synchronisation between the assignee and the Iris maintainers. @ejgallego, maybe would you be ok to assign?

**Comment by ejgallego** [comment]
> @ejgallego, maybe would you be ok to assign?

Sure @herbelin ; it seems a few places need fixing, will wait for the tweaks and review/merge ASAP.

**Comment by herbelin** [comment]
> it seems a few places need fixing

Was just a collision with the new template warnings. Now deactivated it.

**Comment by ejgallego** [comment]
@herbelin for some reason the overlay failed, is your branch properly set?

**Comment by herbelin** [comment]
> @herbelin for some reason the overlay failed, is your branch properly set?

Probably not. The CI file for Iris seems to force a specific `Iris_CI_REF` (line 12 of `ci-iris-lambda-rust.sh`) which overrides the name of the branch I gave in the userlay. I don't know what to do.

**Comment by RalfJung** [comment]
I updated Iris and LambdaRust to not test Coq 8.10 output.  I think that should fix CI for this PR.

**Comment by ejgallego** [comment]
> I updated Iris and LambdaRust to not test Coq 8.10 output. I think that should fix CI for this PR.

@RalfJung I am not sure this is the best thing to do. The Iris/LR test suite is very useful in order to track notation / printing regressions.

Wouldn't it be possible to add a few version-specific tests?

The idea for 8.10 is to make some notation changes [for the better] so IMHO we should allow them but on the other hand they should happen in a controlled way.

**Comment by RalfJung** [comment]
> Wouldn't it be possible to add a few version-specific tests?

Do you have any proposal for how the reference files should be updated when adding a new test?  The only scheme I can think of would require us (Iris devs) to  run `make REF=1` with two different Coq versions (including recompiling Iris in between because Coq's build system stores the `.vo` files always in the same place)

**Comment by ejgallego** [comment]
> Do you have any proposal for how the reference files should be updated when adding a new test? The only scheme I can think of would require us (Iris devs) to run `make REF=1` with two different Coq versions (including recompiling Iris in between because Coq's build system stores the `.vo` files always in the same place)

That's indeed a problem :( maybe the 8.10 tests should be ignored on IRIS CI, but fatal on Coq's CI?

**Comment by ejgallego** [comment]
That wouldn't be so perfect unfortunately as it only covers test creation. Ummm, let's think for a bit.

**Comment by ejgallego** [comment]
Let's think a bit about this, but IMHO we should devise a scheme that allows us to improve notations / printing while keeping the current coverage.

**Comment by ejgallego** [comment]
@herbelin please rebase as it seems that's the only way to test the IRIS setup.

**Comment by herbelin** [comment]
I rebased but should I removed the iris overlay? It seems that CI is looking for a specific commit hash in my branch of iris rather than the head of my iris branch.

**Comment by RalfJung** [comment]
Is the Iris overlay the only thing blocking this?  If yes, we can coordinate to move it forward.  I'll temporarily disable notation checking for Coq 8.10 so that @herbelin's PR fixing the ref file can be merged, then CI here should pass, then this can get merged and then I can enable notation checking again on the Iris side.

**Comment by herbelin** [comment]
OK, I rebased w/o the Iris overlay.

**Comment by RalfJung** [comment]
I merged your PR on the Iris side, and disabled printing testing so that our CI remains green.  That means CI here should work now.

**Comment by ejgallego** [comment]
Great, thanks a lot folks; your help is really appreciated and in particular Iris test-suite is of great use to Coq.

I am going to merge this then, I hope it doesn't create too much pain and we can keep evolving to a model that is painless for everybody.

**Review by ejgallego — APPROVED** [review]
LGTM. 

@herbelin , will merge this tomorrow, but a small question before we merge: it seems to me that this is an user-facing change, so maybe it would merit an entry in `CHANGES` under "Printing / Notations"?

**Comment by RalfJung** [comment]
> will merge this tomorrow

Tomorrow has passed. What is blocking this?
(I'd like to merge https://gitlab.mpi-sws.org/FP/iris-coq/merge_requests/208 on our side which is blocked on this.)

**Comment by herbelin** [comment]
> it seems to me that this is an user-facing change, so maybe it would merit an entry in CHANGES under "Printing / Notations"?

I could add a note but this a fix for a bug with only rare occurrences. That would be somehow strange to do it for this fix and not for all bug fixes. As a compromise, knowing that "we" do not report all bug fixes, I added a (non-exclusive) generic line mentioning in particular #9214.

**Comment by RalfJung** [comment]
Aaand the notation tests in Iris are passing and enabled again.  Thanks all!

**Pull request merged**
