### PR TITLE
Fix votour compilation after #8102.

### PR DESCRIPTION
**Pull request by ppedrot**
Quite urgent.

### CODE REVIEW

**Comment by ejgallego** [comment]
This is ready to merge, any volunteer?

**Review by JasonGross — DISMISSED** [review]
Perhaps the CI should be updated to build votour, so this doesn't happen again?

**Comment by ppedrot** [comment]
I am no CI specialist, so I'll defer that to somebody else.

**Review by ejgallego — APPROVED** [review]
CI passes, no idea about if the patch itself is correct.

**Comment by SkySkimmer** [comment]
@JasonGross 
CI does test votour https://gitlab.com/coq/coq/-/jobs/101817168

**Comment by SkySkimmer** [comment]
Although it's kinda in a fragile way it seems.

**Comment by ejgallego** [comment]
> Although it's kinda in a fragile way it seems.

Why?

**Comment by JasonGross** [comment]
I would suggest adding a line to the beginning of the `script` part of `test-suite-template` in `.gitlab.yml ` that says
```
- make -j "$NJOBS" bin/votour # test the success of extra makefile targets that aren't built by default
```

**Comment by SkySkimmer** [comment]
Not in the test suite template, it would need to rebuild the 
dependencies of votour

It seems fragile because only one job failed, even dune+flambda didn't 
see the issue

Gaëtan Gilbert

**Comment by ejgallego** [comment]
@JasonGross note that this problem occurred by a transitory state of the CI system where it indeed was incomplete wrt the binaries.

**Comment by JasonGross** [comment]
Oh, is the issue that the breaking PR was tested before the dune PR was merged, and so the failure of votour wasn't caught?

**Comment by ejgallego** [comment]
> Oh, is the issue that the breaking PR was tested before the dune PR was merged, and so the failure of votour wasn't caught?

Yeah, `votour` used to be tested before in the normal CI, we will likely restore that by forcing `make coqocaml` in the main builds.

**Pull request merged**
