### PR TITLE
[ci] Add four color theorem proof to CI

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by SkySkimmer — APPROVED** [review]
I wonder if we should split math-comp.sh into multiple files (ala formaltopology/corn/mathclasses).

**Comment by ejgallego** [comment]
> I wonder if we should split math-comp.sh into multiple files (ala formaltopology/corn/mathclasses).

I don't think we'll be able to gain a lot with this setup, I think the splitting above stems from historical reasons [where they used to be tested separadtley]

But indeed it seems that `fourcolor` is broken in master :(

**Comment by ppedrot** [comment]
> But indeed it seems that fourcolor is broken in master :(

A kind soul around willing to fix it?

**Comment by ejgallego** [comment]
https://github.com/math-comp/fourcolor/pull/2

**Comment by ejgallego** [comment]
Fix applied upstream, rerunning the CI to see if it is fine.

**Comment by SkySkimmer** [comment]
Looks fine, shall I merge?

**Comment by ejgallego** [comment]
Yes please.

**Pull request merged**
