### PR TITLE
CI: add fcsl-pcm

### PR DESCRIPTION
**Pull request by anton-trunov**
**Kind:** infrastructure.

Adding freshly released fcsl-pcm library to CI.
The library depends on coq-mathcomp-ssreflect.
Please let me know if I need to change something because of this dependency.

### CODE REVIEW

**Comment by SkySkimmer** [comment]
> Please let me know if I need to change something because of this dependency.

I think you need to add a `install_ssreflect` call like coquelicot and iris-lambda-rust do.

**Comment by anton-trunov** [comment]
> I think you need to add a install_ssreflect call like coquelicot and iris-lambda-rust do.

Done. Thank you.

**Comment by Zimmi48** [comment]
There is also a `.circleci/config.yml` file to update. Sorry, this is not documented yet.

However if, like I read in your announcement e-mail, this library depends on Math-Comp and not just on SSReflect, what you did is not going to be enough. And I fear that we can't test your library right now because the total build time Coq + Math-Comp is already too close to the 50-minute limit imposed on us by Travis.

@SkySkimmer WDYT?

**Comment by anton-trunov** [comment]
I looked in `ci/ci-common.sh` and it says:
>this installs just the ssreflect library of math-comp

This seems as exactly what we need.

**Comment by anton-trunov** [comment]
>There is also a .circleci/config.yml file to update.

updated

**Comment by anton-trunov** [comment]
> There is also a .circleci/config.yml file to update. Sorry, this is not documented yet.

Has it been filed as an issue or should I open a new one?

**Comment by Zimmi48** [comment]
This is #6807.

**Comment by SkySkimmer** [comment]
Travis: https://travis-ci.org/SkySkimmer/coq/jobs/369261154
Gitlab: https://gitlab.com/SkySkimmer/coq/-/jobs/64205900

**Comment by anton-trunov** [comment]
Looks like successful build, right?

**Comment by SkySkimmer** [comment]
Yes

**Review by SkySkimmer — APPROVED** [review]

**Review by ejgallego — APPROVED** [review]

**Comment by anton-trunov** [comment]
Thanks for merging!

**Pull request merged**
