### PR TITLE
adding fiat-parser-ci in failure of.gitlab-ci.yml

### PR DESCRIPTION
**Pull request by forestjulien**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please change the commit message to say "allowed failure" or something similar instead of just "failure".

**Comment by forestjulien** [comment]
oups sorry

**Comment by JasonGross** [comment]
What?  Why would you do this rather than merge #782, which actually fixes the underlying issue (and is approved and ready for merge)?

**Comment by forestjulien** [comment]
Sorry, I did not saw  #782 . 
I close this one

**Pull request closed without merging**
