### PR TITLE
Prevent CoqIDE from hanging when invalid channels are still open.

### PR DESCRIPTION
**Pull request by ppedrot**
This behaviour happens as a sub-bug of #10169 for instance.

### CODE REVIEW

**Comment by MSoegtropIMC** [comment]
Are suprocesses created such that they are killed by the OS with CoqIDE on all platforms or is this something which the OCaml standard library does on exit? I frequently have some zombie coq workers hanging around and I wonder if this change improves this as well, is indifferent or makes this worse.

**Comment by ppedrot** [comment]
This cleanup is performed when calling OCaml `Stdlib.exit`. This PR does not touch Coq workers, but maybe we can apply the same strategy in these programs.

**Comment by MSoegtropIMC** [comment]
I meant that CoqIDE starts processes and might have to explicitly kill them somehow again. The question is: are you sure that the OCaml library exit cleanup - which this change seems to skip - does not do anything in this direction. Since processes sometimes survive CoqIDE this doesn't seem to be made such that the worker processes are killed automatically by the OS when the CoqIDE parent die.

**Comment by ppedrot** [comment]
When not loading any module, the vanilla OCaml `at_exit` [merely flushes the opened channels](https://github.com/ocaml/ocaml/blob/4d4a056bc7823fb94813afe8d9ad6e72fa83e504/stdlib/stdlib.ml#L545). We don't register any callback in CoqIDE, and most OCaml libraries do not either, except for:
- Format which [flushes the formatters](https://github.com/ocaml/ocaml/blob/4d4a056bc7823fb94813afe8d9ad6e72fa83e504/stdlib/format.ml#L1381)
- The Win32 Posix compatibility layer, which [does cleanup stuff](https://github.com/ocaml/ocaml/blob/4d4a056bc7823fb94813afe8d9ad6e72fa83e504/otherlibs/win32unix/unix.ml#L21). You can have a look at [the implementation](https://github.com/ocaml/ocaml/blob/4d4a056bc7823fb94813afe8d9ad6e72fa83e504/otherlibs/win32unix/startup.c#L43-L51), I am not sure what this does.

**Comment by MSoegtropIMC** [comment]
>     * The Win32 Posix compatibility layer, which [does cleanup stuff](https://github.com/ocaml/ocaml/blob/4d4a056bc7823fb94813afe8d9ad6e72fa83e504/otherlibs/win32unix/unix.ml#L21). You can have a look at [the implementation](https://github.com/ocaml/ocaml/blob/4d4a056bc7823fb94813afe8d9ad6e72fa83e504/otherlibs/win32unix/startup.c#L43-L51), I am not sure what this does.

As far as I can see the Windows implementation does indeed call `worker_free` on exit which appears to send commands to the workers to exit and waits for them to do so. I am not sure that this is an optimal implementation but I would say that without changing the Windows implementation skipping the exit handling will result in not terminating the workers. Shall I make a test build an try it?

**Comment by ppedrot** [comment]
> Shall I make a test build an try it?

Go ahead.

**Comment by MSoegtropIMC** [comment]
I tested the CI build of this PR. The workers are killed - not sure if this is done in a nice way but they disappear. The code is unchanged since 2008, so I don't think the original author still remembers the details of this.

**Review by MSoegtropIMC — APPROVED** [review]
Tested that this does not have negative consequences on Windows (where exit code exists to clean up runners).

**Pull request merged**
