### PR TITLE
LtacProf for trunk

### PR DESCRIPTION
**Pull request by JasonGross**
This is #150, but for trunk.  Many thanks to Paul Steckler for figuring out how to port this to trunk.

### CODE REVIEW

**Comment by JasonGross** [comment]
What's blocking this from being merged?

**Comment by JasonGross** [comment]
I've rebased against current trunk, and merged all commits from #150.  It builds and seems to work fine.
(@ppedrot)

**Comment by ppedrot** [comment]
I've proofread your patch and have some remarks.

- There are some warning issues with the code, most notably a missing `open Goptions` somewhere in `profile_ltac.ml` that goes unnoticed because of OCaml default behaviour.
- The ML style looks a bit inexperienced, both from the point of view of syntax and semantics. E.g., I know that we live in the 21st century indeed, but the antique 80-column restriction is still live and we decided to stick to it (mostly, offenders including myself ought to be whipped).
- Why is the profiling code in a separate `ltacprof` folder?

But for the last point, I can add a few patches on my own atop of your code. As for the last one, is there a motivation for your code to be in `ltacprof`? I believe it should definitely be in the `ltac` folder. Adding new folders in the Coq archive should be a well-thought process.

**Comment by JasonGross** [comment]
I believe it's in a separate folder because the `ltac` folder didn't exist in 8.4 (if I recall correctly), or possibly because, as a patch on top of Coq code, it was a feature rather than a bug to have it be as independent of the Coq code base as possible.  The longest lines are my fault; sorry about that.  Please do feel free to move the code into the `ltac` folder, and reformat the rest of the code as necessary.

**Comment by ppedrot** [comment]
Please note that at some point we still need to think how to do Ltac profiling properly. I have no doubt that this PR somehow works in most use cases, but the more I clean the code up, the more I come to think this is just wrong. There are many places that can just go awry, between serialization and sharing of imperative datastructures, one clearly ill-defined equality test and an overall impression of hackishness...

**Comment by JasonGross** [comment]
Duly noted.  (Thanks for cleaning it up!)  The serialization is safe because the mutability of the datastructure is irrelevant across statement boundaries; the `stack` should be singleton after each `.`, and I don't believe there's any sharing between a node and its children.

I looked a bit into the imperative datastructure sharing, and was reminded of [this article I recently read](http://www.pbm.com/~lindahl/mel.html).  I'll let @tebbi give any more details on how it works.

I hope the hackishness of the time aggregation code won't prevent the patch from getting merged in time for 8.6.

**Comment by ppedrot** [comment]
Don't worry, I'm about to merge it. But I'm seriously considering rewriting it from scratch in 8.7 (which it needs anyway, to handle backtracking).

**Comment by ppedrot** [comment]
We also need to think were to put the corresponding "Declare ML Module" vernacular command. For now, it is not exported anywhere so that a user wishing to use the start/stop ltac profiling tactics needs to import it herself.

**Comment by JasonGross** [comment]
Thanks!

Oh, huh.  Any reason not to add it to `Notations.v`, like all the rest?  (And then add a test to the ltacprof test-suite file.)

**Pull request merged**
