### PR TITLE
Allow calling doc_gram targets through Makefile.dune

### LINKED ISSUE #15246: Possibly, the `CODEOWNERS` file should also be adapted so that `Makefile.docgram` stays in the realm of @coq/doc-maintainers...
Possibly, the `CODEOWNERS` file should also be adapted so that `Makefile.docgram` stays in the realm of @coq/doc-maintainers...

_Originally posted by @Zimmi48 in https://github.com/coq/coq/pull/15241#pullrequestreview-815203329_

### PR DESCRIPTION
**Pull request by SkySkimmer**
Notably this allows to run them without explicit configuration.

Closes #15246

### CODE REVIEW

**Comment by Zimmi48** [comment]
Great! Please use it to remove the call to `./configure -profile devel` in the linter and in the PR template.

**Comment by Zimmi48** [comment]
I guess it would also be reasonable to remove the `doc_gram` targets from the Dune file.

**Review by Zimmi48 — APPROVED** [review]
Possibly, the `CODEOWNERS` file should also be adapted so that `Makefile.docgram` stays in the realm of @coq/doc-maintainers...

**Review by jfehrle — CHANGES_REQUESTED** [review]
I tested the PR locally.  I can't build with dune, also the non-dune target is still present as a trap for the unwary.

```
$ make -f Makefile.dune doc_gram_rsts
make: *** No rule to make target 'doc_gram_rsts'.  Stop.
$ make -f Makefile.dune doc_gram
make: *** No rule to make target 'doc_gram'.  Stop.

$ make doc_gram_rsts
Please run ./configure first to continue building with make
or pass option "-f Makefile.dune" to let dune manage the build
Makefile.make:125: recipe for target 'noconfig' failed
make: *** [noconfig] Error 1
```

**Comment by SkySkimmer** [comment]
That makes no sense, are you sure you checked out the right commit?

**Comment by jfehrle** [comment]
Looks like what I did was:

```
$ git remote add SkySkimmer https://github.com/SkySkimmer/coq.git
$ git fetch SkySkimmer docgram-noconf
$ git checkout -b docgram-noconf
```

but it should have been without the `-b` on the checkout.  The `make -f Makefile.dune doc_gram_rsts` now works.

`make -f Makefile.dune doc_gram` will rebuild if `doc_grammar.ml` is changed, but doesn't notice changes to the mlgs.  This target updates fullGrammar and orderedGrammar without updating the rsts.  If that's easy to fix, would you do so?

Also please disable `make doc_gram_rsts`.

**Comment by SkySkimmer** [comment]
>Also please disable make doc_gram_rsts.

Why?

**Comment by jfehrle** [comment]
It's too easy to mistakenly type `make doc_gram_rsts`, especially after doing that so many times.  Is there a reason to still keep it around?

**Comment by SkySkimmer** [comment]
>It's too easy to mistakenly type make doc_gram_rsts

It should still work fine

**Review by jfehrle — APPROVED** [review]
OK, let's leave `make doc_gram_rsts` as is, but I hope you'll try to get `make -f Makefile.dune doc_gram` to work as I suggested.

**Comment by SkySkimmer** [comment]
>make -f Makefile.dune doc_gram will rebuild if doc_grammar.ml is changed, but doesn't notice changes to the mlgs. This target should update fullGrammar and orderedGrammar without updating the rsts. If that's easy to fix, would you do so?

Currently it's functionally PHONY since the exe is marked phony, do you think having accurate dependencies is important for this?

**Comment by jfehrle** [comment]
It's actually OK as-is, my bad.  Would you like me to assign/merge?

**Comment by SkySkimmer** [comment]
@Zimmi48 is already assigned though

**Comment by Zimmi48** [comment]
@coqbot merge now

**Pull request merged**
