### PR TITLE
Partially revert #18108: go back to canonical coq.inria.fr URLs.

### PR DESCRIPTION
**Pull request by Zimmi48**
Partially revert #18108: go back to canonical coq.inria.fr URLs.

Now that redirects work for them and old doc versions were uploaded to the doc repo.

Cf. coq/www#233.

### CODE REVIEW

**Review by jfehrle — APPROVED** [review]
Looks OK but mostly expecting that you've done the right thing

Perhaps Maxime would be the best assignee?  Or I can do it.

**Comment by Zimmi48** [comment]
> Looks OK but mostly expecting that you've done the right thing

I've checked that all the links included are correct by opening them.
 
> Perhaps Maxime would be the best assignee? Or I can do it.

Maxime has left all the maintainers teams (after he moved to a different position at Inria), so he cannot merge PRs on the Coq repository anymore.

**Comment by jfehrle** [comment]
@coqbot merge now

**Comment by jfehrle** [comment]
@coqbot merge no

**Comment by jfehrle** [comment]
@coqbot merge now

**Pull request merged**
